### ISSUE TITLE
Broken link for Windows Installer

### ISSUE THREAD

**Issue by life777eternal** [certbot/certbot#10005]
The link for the windows installer on https://certbot.eff.org/instructions?ws=other&os=windows goes to a 404 page. 

https://github.com/certbot/certbot/releases/latest/download/certbot-beta-installer-win_amd64_signed.exe

Why does the latest two releases only have tar.gz files? and no exe files.

Thank you, Shalom.

**Comment by osirisinferi** [comment]
The instruction generator is "maintained" (sort of, the code has gone "internal" for some reason) on the certbot/website repository. There's already an issue there about this at https://github.com/certbot/website/issues/812, so I'm closing this as a duplicate (even though it's a different repository).
