### ISSUE TITLE
Certbot gives a timeout error

### ISSUE THREAD

**Issue by alex-ritter** [certbot/certbot#10028]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## I ran this command and it produced this output: 

certbot -d test.moonbyte.net --nginx -m corporate@moonbyte.net --agree-tos --redirect --non-interactive --keep -v

Certbot failed to authenticate some domains (authenticator: nginx). The Certificate Authority reported these problems:
  Domain: test.moonbyte.net
  Type:   unauthorized
  Detail: During secondary validation: 2a06:98c1:3121::1: Invalid response from http://test.moonbyte.net/.well-known/acme-challenge/Vc8OqajF2pYc6fHsFFOC-tJDTtogtFgBkAHh_UTIV_o: 522

## Certbot's behavior differed from what I expected because:

The certificate authority always return a timeout error when trying to access the acme challenge. This web server is reachable on both HTTP and HTTPS without any firewall restrictions for proxied cloudflare IP's. I've also tried this on a domain without being proxied, same issue. 

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator nginx, Installer nginx
Requesting a certificate for test.moonbyte.net
Performing the following challenges:
http-01 challenge for test.moonbyte.net
Waiting for verification...
Challenge failed for domain test.moonbyte.net
http-01 challenge for test.moonbyte.net

Certbot failed to authenticate some domains (authenticator: nginx). The Certificate Authority reported these problems:
  Domain: test.moonbyte.net
  Type:   unauthorized
  Detail: During secondary validation: 2a06:98c1:3121::1: Invalid response from http://test.moonbyte.net/.well-known/acme-challenge/Vc8OqajF2pYc6fHsFFOC-tJDTtogtFgBkAHh_UTIV_o: 522

Hint: The Certificate Authority failed to verify the temporary nginx configuration changes made by Certbot. Ensure the listed domains point to this nginx server and that it is accessible from the internet.

Cleaning up challenges
Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

server {
    listen 80;
    server_name test.moonbyte.net;

    access_log /var/log/nginx/test_access.log;
    error_log /var/log/nginx/test_error.log;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}

**Comment by osirisinferi** [comment]
Please open a new thread in the `Help` section on the Let's Encrypt Community as mentioned at the top of this issue template. Because this is not a Certbot issue per se, but more an implementation issue which is better addressed on the Community. Thank you.

**Comment by alex-ritter** [comment]
Adding a comment to document the issue.

It turns out I had country restrictions on my firewall and Lets Encrypt's request was coming from a country that was not on the list.

After removing country restrictions on my firewall this started working again.

**Comment by mdPlusPlus** [comment]
I think you've just solved my mystery. My renewals are failing with `Failed to renew certificate $DOMAIN with error: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Read timed out. (read timeout=45)`.  
The common solution to this issue seems to be to lower the MTU to 1300 (which honestly just sounds absolutely ridiculous).  
But I've recently enabled `banIP` on my OpenWrt router with inbound blocks for most countries. This might just be the issue.
