### ISSUE TITLE
Broken download link on website

### ISSUE THREAD

**Issue by Jacob-NX** [certbot/certbot#10029]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Windows server 22

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
X

## I ran this command and it produced this output:
X

## Certbot's behavior differed from what I expected because:
X

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
X
## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
X

https://certbot.eff.org/instructions?ws=nginx&os=windows

On this website link to download for nginx and for windows is broken. I can't download binary, did i need to prepare env to compile it by myself or is there alternative source?

**Comment by DorianCoding** [comment]
Hello,

Windows support has been discontinued. 
More infos here: https://community.letsencrypt.org/t/certbot-discontinuing-windows-beta-support-in-2024/208101

**Comment by Jacob-NX** [comment]
Thanks, would it be possible to add this under download? I think a lot of people would find it very helpfull.
