### ISSUE TITLE
snap_config.py is stuck on Python version 3.12 via hardcoded number (reopened/rewritten from #9772)

### ISSUE THREAD

**Issue by mahtin** [certbot/certbot#10030]
In file [snap_config.py](https://github.com/certbot/certbot/blob/master/certbot/certbot/_internal/snap_config.py) there seems to be a dependency on Python 3.12 vs the current version. Line 74:
```
    connections = ['/snap/{0}/current/lib/python3.12/site-packages/'.format(item['slot']['snap'])
```
While I'm not affected by this line of code, I believe it would benefit from using the current Python version number, as in:
```
$ python
...
...
>>> from platform import python_version
>>> python_version()
'3.11.5'
>>> ^D
$
```
That is unless I'm missing something important about snap. Am I?

NOTE: This is the second time this have been raised as an issue. The file in question above has been edited by @wgreenberg & @ohemorange back in August from `3.8` to `3.12`; but that doesn't really fix the issue long term (or for folks running earlier than 3.12). Using the current version number would be the right (long term) answer.

 (reopened/rewritten from #9772)

**Comment by osirisinferi** [comment]
I'm not sure I understand what you mean. The snap package comes with its own Python. I assume the "current Python version number" is simply your local installation of Python? If so, it's normal that this version is different than the Python version within the Certbot snap.

**Comment by wgreenberg** [comment]
As Osiris says, snap comes with a version of python that we define and will remain stable across major versions of Certbot. Since this version is effectively set in stone (and hardcoded) in `snap/snapcraft.yaml`, i think parsing the version string `platform.python_version()` returns to derive the import path seems unnecessary.

**Comment by mahtin** [comment]
> ... i think parsing the version string `platform.python_version()` returns to derive the import path seems unnecessary.

OK - I understand the included Python issue. However, I would disagree with the close of this issue. Presently you have a hard code number in the code (which needs to be manually edited into the code. By using `python_version()` you never need to update this file.

**Comment by wgreenberg** [comment]
i do understand the virtue of not hardcoding things, but in this particular case, having to parse a version string to dynamically produce a value that's known to be `python3.12` until 3.12's EOL (2028) doesn't strike me as worth implementing.

**Comment by mahtin** [comment]
OK, so be it ... let's move on.
