### ISSUE TITLE
Webroot plugin should delete .well-known/acme-challenge on cleanup

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#1003]
`cleanup()` should delete `.well-known/acme-challenge` when all previously perfomed challenges have been cleaned up. This requires us to track the status of all incoming challenges, just like standalone2 does.

**Comment by pde** [comment]
This might have been a somewhat involved task for a first PR, but since there's an implementation to work from, it shouldn't be too bad.

**Comment by filipochnik** [comment]
I started working on this.
IMO `.well-known` should be removed as well if it wasn't present before. We want to leave everything as it was. Is that correct?

**Comment by hlieberman** [comment]
I think it should be removed regardless of whether it was present before.  We're going to blindly overwrite what was there anyway, so there doesn't seem to be much point to keeping it around even if it was present before.

**Comment by filipochnik** [comment]
Maybe I'm not seeing something, but aren't we writing only to `.well-known/acme-challenge`? Seem like all other files and directories in `.well-known` are left untouched.

**Comment by hlieberman** [comment]
On February 16, 2016 12:35:44 AM EST, Filip Ochnik <notifications@github.com> wrote:
>Maybe I'm not seeing something, but aren't we writing only to
>`.well-known/acme-challenge`? Seem like all other files and directories
>in `.well-known` are left untouched.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/letsencrypt/letsencrypt/issues/1003#issuecomment-184527930

Agreed. This is just about the acme-challenge.
-- 
Harlan Lieberman-Berg
~hlieberman

**Comment by alanhogan** [comment]
It was confusing when I used Dreamhost's one-click Let’s Encrypt integration and then was left trying to figure out who left me a greeting card named `.well-known`. The entire `.well-known` folder should be deleted, right? Assuming it only contains files for "let's encrypt"

**Comment by hlieberman** [comment]
On March 25, 2016 5:54:38 PM EDT, Alan Hogan <notifications@github.com> wrote:
>It was confusing when I used Dreamhost's one-click Let’s Encrypt
>integration and then was left trying to figure out who left me a
>greeting card named `.well-known`. The entire `.well-known` folder
>should be deleted, right? Assuming it only contains files for "let's
>encrypt"
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/letsencrypt/letsencrypt/issues/1003#issuecomment-201532994


More things than just Let's Encrypt use .well-known.

We should delete our files, and then delete the directory if it's empty.

-- 
Harlan Lieberman-Berg
~hlieberman

**Comment by bmw** [comment]
To repeat what I said [here](https://github.com/letsencrypt/letsencrypt/pull/2480#issuecomment-196501440):
> I'm working on a major webroot rewrite. In this I'm fixing permission problems, allowing for interactively choosing webroot paths, and I also plan to work on this issue. What I'm planning on doing is deleting .well-known if the client created it and leaving it untouched otherwise.

**Comment by textshell** [comment]
For setups with an alias into a letsencrypt directory even removing the 'acme-challenge' directory would be the wrong thing to do, because that would leave the alias point to a non existing directory.

    Alias "/.well-known/acme-challenge" "/srv/letsencrypt/example.com/.well-known/acme-challenge"

On the other hand, adding a /srv/letsencrypt/example.com/.well-known/acme-challenge/.keep file of course allows to work around the deletion if the acme-challenge directory too.

This kind of alias structure is nice because things are cleanly separated and an concurrent update (like rsync -delete) in the normal location will not mess up certificate renewal.

**Comment by bmw** [comment]
By the way, I unfortunately didn't get to this in my rewrite mentioned [here](https://github.com/certbot/certbot/issues/1003#issuecomment-201538065).

**Comment by sydneyli** [comment]
Re-opening until bugfix is landed.

**Comment by bmw** [comment]
Fixed in #5577.
