### ISSUE TITLE
drop python 3.8 support

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#10035]
what the title says

**Comment by ohemorange** [comment]
when we do this, we'll want to run a search for things like `if sys.version_info >= (3, 9)` in addition to the similar things done in https://github.com/certbot/certbot/pull/9792/

**Comment by ohemorange** [comment]
Hello @mrx23dot, please make sure that your future comments adhere to the [EFF Public Projects Code of Conduct](https://www.eff.org/pages/eppcode). Certbot is written in Python; your understanding is fundamentally incorrect. Python 3.8 reached EOL a month ago, so we are removing our official support, which is to say, the guarantee that we will work correctly on python 3.8. If you would like to continue to use python 3.8 despite it being deprecated, you may continue to do so, and certbot may continue to work for you, but we will no longer guarantee it. I am deleting your comment as the tone is not in line with our goal of making this project a welcoming place.
