### ISSUE TITLE
wildcard certificate name breaking change

### ISSUE THREAD

**Issue by milkshakeuk** [certbot/certbot#10059]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
ubuntu 22.04 jammy

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
snap

## I ran this command and it produced this output:
`sudo certbot certonly --dns-cloudflare --dns-cloudflare-credentials cloudflare.ini -d *.wildcardexample.co.uk -m certcontact@wildcardexample.co.uk --cert-name *.wildcardexample.co.uk --key-type rsa --agree-tos --non-interactive`

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Requesting a certificate for *.wildcardexample.co.uk
Waiting 10 seconds for DNS changes to propagate

Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/*.wildcardexample.co.uk/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/*.wildcardexample.co.uk/privkey.pem
This certificate expires on 2025-02-12.
These files will be updated when the certificate renews.
Certbot has set up a scheduled task to automatically renew this certificate in the background.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

## Certbot's behavior differed from what I expected because:
cert bot used to create the certificate (and folder) name `wildcardexample.co.uk`  and now it creates certificate (and folder) `*.wildcardexample.co.uk` which has broken how our automation pipeline works

**Comment by osirisinferi** [comment]
> cert bot used to create the certificate (and folder) name `wildcardexample.co.uk` and now it creates certificate (and folder) `*.wildcardexample.co.uk` which has broken how our automation pipeline works

Well, you actually *asked* for this:

> --cert-name *.wildcardexample.co.uk

Did you always include the `*.` in the certificate name before?

**Comment by milkshakeuk** [comment]
I'm pretty sure I did but I'll check the git history.

**Comment by osirisinferi** [comment]
I don't think the relevant parts have been touched for years:

https://github.com/certbot/certbot/blame/main/certbot/certbot/_internal/cli/__init__.py#L137-L148

https://github.com/certbot/certbot/blame/main/certbot/certbot/_internal/main.py#L368-L408

https://github.com/certbot/certbot/blame/main/certbot/certbot/_internal/cert_manager.py#L107-L123

https://github.com/certbot/certbot/blame/main/certbot/certbot/util.py#L267-L292

All code I can find seems to "just" use the `--cert-name` variable "as is". If something was checking for and removing wildcard labels at the front, it has been removed YEARS ago.

**Comment by milkshakeuk** [comment]
@osirisinferi looks like it started when we added the `cert-name` param (we were forced to add it when specifying the cert be RSA - from memory)
