### ISSUE TITLE
Crash when calling certbot list with new certbot on raspbian

### ISSUE THREAD

**Issue by akc42** [certbot/certbot#10055]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Raspian `uname -a` gives:

`Linux chip 5.10.63-v8+ #1459 SMP PREEMPT Wed Oct 6 16:42:49 BST 2021 aarch64 GNU/Linux`

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
 its installed using snap

## I ran this command and it produced this output:
`certbot list` produced
```
Traceback (most recent call last):
  File "/snap/certbot/4183/bin/certbot", line 5, in <module>
    from certbot.main import main
  File "/snap/certbot/4183/lib/python3.12/site-packages/certbot/main.py", line 6, in <module>
    from certbot._internal import main as internal_main
  File "/snap/certbot/4183/lib/python3.12/site-packages/certbot/_internal/main.py", line 20, in <module>
    import josepy as jose
  File "/snap/certbot/4183/lib/python3.12/site-packages/josepy/__init__.py", line 40, in <module>
    from josepy.json_util import (
  File "/snap/certbot/4183/lib/python3.12/site-packages/josepy/json_util.py", line 24, in <module>
    from OpenSSL import crypto
  File "/snap/certbot/4183/lib/python3.12/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/snap/certbot/4183/lib/python3.12/site-packages/OpenSSL/SSL.py", line 11, in <module>
    from OpenSSL._util import (
  File "/snap/certbot/4183/lib/python3.12/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/snap/certbot/4183/lib/python3.12/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 15, in <module>
    from cryptography.exceptions import InternalError
  File "/snap/certbot/4183/lib/python3.12/site-packages/cryptography/exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
RuntimeError: OpenSSL 3.0's legacy provider failed to load. This is a fatal error by default, but cryptography supports running without legacy algorithms by setting the environment variable CRYPTOGRAPHY_OPENSSL_NO_LEGACY. If you did not expect this error, you have likely made a mistake with your OpenSSL configuration.
```

## Certbot's behavior differed from what I expected because:
Crashed rather than showed list of certificates.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
N/A
## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
N/A

Just as a comment, this certificate is for a mail server.  I have other certificates on another machine, so I normally only manually run certbot renew every 90 days after I have manually moved my port forwarding of port 80.  Current certificate does not expire until 15th January, so its only by chance that I ran it today and I have not changed port 80 forwarding.

**Comment by akc42** [comment]
upgraded to certbot 3.0.1 but that didn't change the outcome.

**Comment by jzischkau** [comment]
I'm experiencing the same issue (certbot installed from snap, Raspbian, identical error message).

**Comment by Leah96xxx** [comment]
Also experiencing this issue on identical setup (snap, Rapsbian, same error message). It seems to be working fine on another machine running Ubuntu

**Comment by ohemorange** [comment]
This looks related to https://github.com/pyca/cryptography/issues/11450

**Comment by willivolt** [comment]
Same error here on Rapsbian. I was able to workaround and manually renew with:
`sudo CRYPTOGRAPHY_OPENSSL_NO_LEGACY=1 certbot renew`

**Comment by bmw** [comment]
could someone provide the output of the command `sudo snap list certbot` from a system that's hitting this problem?

**Comment by Leah96xxx** [comment]
> could someone provide the output of the command `sudo snap list certbot` from a system that's hitting this problem?

From my Pi, running just certbot and Docker
```
$ sudo snap list
Name                    Version             Rev    Tracking       Publisher     Notes
certbot                 3.0.1               4194   latest/stable  certbot-eff✓  classic
certbot-dns-cloudflare  3.0.1               3812   latest/stable  certbot-eff✓  -
core                    16-2.61.4-20240607  17202  latest/stable  canonical✓    core
core20                  20240911            2435   latest/stable  canonical✓    base
core24                  20240920            611    latest/stable  canonical✓    base
```

**Comment by jzischkau** [comment]
> could someone provide the output of the command `sudo snap list certbot` from a system that's hitting this problem?

`$ sudo snap list certbot`
```
Name     Version  Rev   Tracking       Publisher     Notes
certbot  3.0.1    4194  latest/stable  certbot-eff✓  classic
```

**Comment by akc42** [comment]
> could someone provide the output of the command `sudo snap list certbot` from a system that's hitting this problem?
```
root@chip:~# snap list certbot
Name     Version  Rev   Tracking       Publisher     Notes
certbot  3.0.1    4194  latest/stable  certbot-eff✓  classic
root@chip:~# 
```

I go straight into root from my ssh call - since I never do anything on this system other than as root.

**Comment by akc42** [comment]
> Same error here on Rapsbian. I was able to workaround and manually renew with: `sudo CRYPTOGRAPHY_OPENSSL_NO_LEGACY=1 certbot renew`

I haven't tried to renew yet (I have to change port forwarding and my certificates don't expire until 15th Jan 2025) but all the other commands that failed before now work in the `CRYPTOGRAPHY_OPENSSL_NO_LEGACY=1` before hand on the command line

**Comment by bmw** [comment]
a fix for this was just pushed to our "edge" [snap channel](https://snapcraft.io/docs/channels). this channel is updated nightly, but only if every test we have for certbot passes

to update your local snap to install from channel, you can run
```
sudo snap refresh --channel=edge certbot
```
when you want to switch back to the default, stable channel you can run
```
sudo snap refresh --channel=stable certbot
```
i'll make another post here when the stable channel is also updated so people know they can switch back if they want to

**Comment by jordanbs** [comment]
I was hitting this, and updating to `certbot 3.1.0.dev0` via snapd's edge channel per @bmw's comment resolved the issue.

**Comment by HannesVo** [comment]
> I was hitting this, and updating to `certbot 3.1.0.dev0` via snapd's edge channel per @bmw's comment resolved the issue.

Same here, same error same solution, thank's a lot.

**Comment by paul-danford** [comment]
certbot 3.1.0.dev0 working fine for me also, thank you.

Will revert back to stable when advised to.

**Comment by martin762** [comment]
Many thanks. worked for me too.

**Comment by ferrets6** [comment]
@bmw, works fine for me too. Following this issue to know when to switch back to stable.

**Comment by Ivano62** [comment]
Same error here on Rapsbian.

uname -a
```
Linux raspberrynord 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux
```
sudo snap list certbot
```
Name     Version  Rev   Tracking       Publisher     Notes
certbot  3.0.1    4194  latest/stable  certbot-eff✓  classic
```

I was able to workaround and manually renew with:
```
sudo CRYPTOGRAPHY_OPENSSL_NO_LEGACY=1 certbot renew
```

**Comment by Asydom** [comment]
Update done to certbot 3.1.0.dev0 via snapd's edge channel as per as per @bmw's instruction. Issue solved. Many tahnks to @bmw

**Comment by F4FXL** [comment]
Hi there, ran into this issue today on Armbian. Udpating to dev0 solved it. What is the ETA to have this fix in stable?

**Comment by davdidatoakside** [comment]
Affected me today *Raspberry Pi OS".  NoLegacy workaround was effective

**Comment by F4FXL** [comment]
> Affected me today *Raspberry Pi OS". NoLegacy workaround was effective

On my Raspi-OS it is working using stable and 3.0.1.... Not sure why

**Comment by bmw** [comment]
certbot 3.1.0 with this change was just released

like i said at https://github.com/certbot/certbot/issues/10055#issuecomment-2495090398, if you were previously using our edge snap channel, you can switch back to our normal, stable channel if you want by running
```
sudo snap refresh --channel=stable certbot
```
for those of you who worked around the problem by setting `CRYPTOGRAPHY_OPENSSL_NO_LEGACY=1`, continuing to do so shouldn't hurt anything, but you can also remove this environment variable once your certbot snap has updated to 3.1.0
