### ISSUE TITLE
Scriptable Manual mode

### ISSUE THREAD

**Issue by fluffy** [certbot/certbot#1015]
This is a feature request not bug 

When using the manual mode in scripts, it would be nice if it could be run as two separate invocation instead of pausing in the middle and asking the user to hit enter after the challenge field was installed.

I'm thinking of something like "authgen" does first half, and has a CLI to put the out put challenge in a given file, then you run the client a second time with something like "authcheck"

The current CLI is pretty hard to automate.

**Comment by kuba** [comment]
Manual mode as the name suggests is not meant to be run by automation!

Have you tried using the `standalone` plugin (`letsencrypt -a standalone`)? It requires access to either port 80 (`--standalone-supported-challenges simpleHttp`) or 443 (`--standalone-supported-challenges dvsni`), and if `--standalone-supported-challenges` is not supplied it will randomly pick one or the other.

You can also easily automate the `webroot` plugin. :)

**Comment by kuba** [comment]
And btw, there is `--manual-test-mode`, which runs the manual plugin commands by itself, but this should only be used for testing purposes!

**Comment by fluffy** [comment]
> On Oct 17, 2015, at 6:54 AM, Jakub Warmuz <notifications@github.com> wrote:
> 
> Manual mode as the name suggests is not meant to be run by automation!
> 
> Have you tried using the standalone plugin (letsencrypt -a standalone)? It requires access to either port 80 (--standalone-supported-challenges simpleHttp) or 443 (--standalone-supported-challenges dvsni), and if --standalone-supported-challenges is not supplied it will randomly pick one or the other.
> 
> You can also easily automate the webroot plugin. :)
> 
> —
> Reply to this email directly or view it on GitHub.
> 

the standalone mode does work for me - i like it - but I can't run it on the servers the DNS for the domain points to. (it's a large cloud site - https://web.ciscospark.com - with front end load balancers that terminate TLS and end up with different technology in different data centers )

Any suggestions on what is the best approach for people using LE on on deployments like this. If there a different tool I should be using ? I did look at webroot a little bit but that looked like it was only for if the TLS was terminated with apache. Perhaps I did not look deep enough at this, pointers to things I should read?

Thanks, Cullen

**Comment by pde** [comment]
One solution that is in the engineering pipeline post-launch is a DNS based challenge.  Another solution which is in the pipeline is challenges sent to a port other than 443. 

A more immediately available solution is to write your own client plugin which works for Cisco's infrastructure.  That should be simple; the authenticator and installer interfaces are explained [here](https://letsencrypt.readthedocs.org/en/latest/contributing.html#plugin-architecture) and defined [here](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/interfaces.py#L132)

**Comment by fluffy** [comment]
> On Oct 19, 2015, at 7:21 PM, Peter Eckersley <notifications@github.com> wrote:
> 
> One solution that is in the engineering pipeline post-launch is a DNS based challenge. Another solution which is in the pipeline is challenges sent to a port other than 443.
> 
> A more immediately available solution is to write your own client plugin which works for Cisco's infrastructure. That should be simple; the authenticator and installer interfaces are explained here <https://letsencrypt.readthedocs.org/en/latest/contributing.html#plugin-architecture> and defined here <https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/interfaces.py#L132>
> —
> Reply to this email directly or view it on GitHub <https://github.com/letsencrypt/letsencrypt/issues/1015#issuecomment-149406439>.
> 

Thanks Peter - I will look at the client API. I had not done that. 

I’ll add a +1 to I would love support for the ACME DNS flow when we can.

**Comment by schoen** [comment]
I think that this was effectively fixed a couple of years ago by the `--manual-auth-hook` feature, although there are certainly things that people don't like about that. `--manual-auth-hook` is specifically designed for integrating your own scripts, and provides the necessary information in environment variables so that your script doesn't have to interact with Certbot via its stdin and stdout.

@ohemorange is currently working on a proposal to refactor this entire interface in a way that would give plugin and script authors more flexibility. If there's something specific that you find unsuitable about `--manual-auth-hook` (which I think many people do), please open a new issue about that and tag her so that she can take your feedback into account when designing the new interface.
