### ISSUE TITLE
pem file naming can be confusing when it comes time to add them to the server config files.

### ISSUE THREAD

**Issue by kruug** [certbot/certbot#1047]
Currently, the two files that would need to be added to apache are:
  `cert.pem`
  `chain.pem`
  `privkey.pem`

and nginx are
  `fullchain.pem`
  `privkey.pem`

Looking at https://httpd.apache.org/docs/2.4/ssl/ssl_howto.html and https://www.digicert.com/ssl-certificate-installation-apache.htm, it would appear that Apache requires `SSLCertificateFile`, `SSLCertificateKeyFile`, and `SSLCertificateChainFile`.  These would be `cert.pem`, `privkey.pem`, and `chain.pem`, respectively.

Looking at https://www.digicert.com/ssl-certificate-installation-nginx.htm, it would appear that Nginx requires `ssl_certificate` and `ssl_certificate_key`.  These would be `fullchain.pem` and `privkey.pem`, respectively.

I propose renaming the files to something that better matches what the documentations state for the settings.  In my mind, what makes sense would be renaming `fullchain.pem` to `certificatebundle.pem` (or certbundle.pem to keep it short) and renaming `privkey.pem` to `certificatekey.pem` (or `certkey.pem to keep it short).

**Comment by nagisa** [comment]
As somebody who did it without using documentation and mediocre crypto/SSL knowledge filenames weren’t unclear to me per se.

However, I still messed up and used `cert.pem` instead of `fullchain.pem` for `ssl_certificate` the first time. Not sure how different filenames would’ve prevented that.

**Comment by bmw** [comment]
There's a PR (#1077) that will point people towards `fullchain.pem` instead of `cert.pem` as this is what most modern web browsers will want ([Apache](https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslcertificatefile) can also use this). As a further improvement, we plan on resolving #608 before launch which suggests documenting the purpose of all four files.

**Comment by pde** [comment]
Per Brad's comment, Apache supports `fullchain.pem` though only from version 2.4.8 onwards.  That includes, say, Debian jessie but not wheezy, and Ubuntu from utopic but not trusty 14.04 LTS :(

I'd actually be fine with the logic [here](https://github.com/letsencrypt/letsencrypt/pull/1077/files#diff-54b2f468d57ef7436008bd031bc89711R279) getting even fancier to try to give the user information tuned to the servers they have installed.  But it's not a 1.0 ticket for us.

**Comment by pde** [comment]
Though pull requests are welcome @kruug ! ;)

**Comment by James-TR** [comment]
If you set apache to use the same file for both `SSLCertificateFile` and `SSLCertificateChainFile` it will just work. Mind this is about the same as the other solution :)

**Comment by louisameline** [comment]
+1, had to search to make sure and found this page. Thanks for the clarification @kruug.

**Comment by bmw** [comment]
While we didn't end up renaming these files, Certbot now adds a README to each directory containing them describing their contents and provides a link to further documentation on the Certbot website. With this in mind, I think this issue can be closed.
