### ISSUE TITLE
Suppress expected errors in test suite

### ISSUE THREAD

**Issue by hlieberman** [certbot/certbot#1056]
Currently, the test suite produces many errors on run.  Unfortunately, the names of some of the tests lead me to believe that some of the errors that it produces might be desirable.  Because of this, I'm not sure which errors should be reported or acted on, and the test suite is of less usefulness.

An example test log is at https://blog.setec.io/.letsencrypt/testlog.txt

**Comment by kuba** [comment]
```
Ran 384 tests in 3.838s

OK
```

No errors happened, easy case. Try to intentionally introduce a bug in a test to see how the output differs.

**Comment by bmw** [comment]
Despite this issue being created first, I'm closing this in favor of #3580 as we should suppress all expected warnings as well.
