### ISSUE TITLE
Make it clear that Apache/nginx is not required

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#1067]
Some people (https://github.com/xenolf/lego/issues/12#issue-112577357) seem to be confused about this. We need more docs.

**Comment by kuba** [comment]
Apart from docs, `letsencrypt-auto` doesn't suggest standalone as viable option (default mode is `run` => only auth+install plugin combos).

**Comment by bmw** [comment]
[Related](https://community.letsencrypt.org/t/no-installers-seem-to-be-present-and-working-on-your-system/1791)

**Comment by pde** [comment]
Done
