### ISSUE TITLE
GPG key as account signing key (for smartcard/HSM use)

### ISSUE THREAD

**Issue by diafygi** [certbot/certbot#1083]
When I register a new user account, I'd like to sign things with my gpg key instead of generating a new keypair. That way, I don't have to worry about keeping secure some new account private key.

Also, this means account private keys could be kept on a smartcard or HSM that's gnupg's configured to use, which means the letsencrypt client doesn't have to roll it's own smartcard/HSM interaction layer.

The goal of this is to allow managed platforms (e.g. shared hosting providers) to deploy an HSM that has their account key, then they can safely issue new HTTPS certificates for their users' websites.

**Comment by kuba** [comment]
Nice feature, but definitely not for GA :)

**Comment by diafygi** [comment]
Yep, definitely a longer term goal.

**Comment by diafygi** [comment]
This isn't so much an issue as a feature request. I'd still be interested in being able to use my gpg key (or smartcard/yubikey) to sign requests for new certificates. It doesn't even have to be a built-in feature. It can just be a tutorial in the documentation that goes through the steps on how to set up signing requests using gpg keys or smart cards.
