### ISSUE TITLE
lestsencrypt --help PLUGIN should print .more_info() string

### ISSUE THREAD

**Issue by pde** [certbot/certbot#1101]
Plugins are required to produce a [help string](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/interfaces.py#L121).  We should print it if the user asks for help with that plugin as a topic.

**Comment by pde** [comment]
This is *probably* an easy ticket, although it depends on whether argparse gives us a nice place to drop this in.

**Comment by pde** [comment]
I tried briefly to make this happen, but it's actually quite difficult.  The natural place to add this would in the [`description` field](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/cli.py#L718) of the relevant argparse group.  

But that fails, at least in the case of nginx, because the plugin reports its internal state in complex ways, meaning `.more_info()` can't be called without a true instance of the plugin class.  You can't make a true instance of the plugin without a full config object for that plugin.  Making a fake one is a complex process when it's done in the tests, and that's just for the test cases.  We can't use the real one because it doesn't exist yet.

**Comment by SwartzCr** [comment]
Is this still a needed thing? @bmw

**Comment by bmw** [comment]
It's a nice to have. At least for our own plugins, the `more_info` output is much more descriptive than what we currently print.
