### ISSUE TITLE
Integration tests for CLI < -- > plugin interactions

### ISSUE THREAD

**Issue by pde** [certbot/certbot#1122]
Unit testing of cli.py's responses to various types of misconfigured plugins is quite an intricate task, because the plugins are not present when unit tests are run, and because mocking out the relevant bits of disco and plugins while keeping the tests meaningful is a very elaborate process.

Instead, we should use integration tests where the plugins are actually available, and we can mock up things like broken Apache and Nginx configurations.

**Comment by kuba** [comment]
I don't agree it's a very elaborate process to mock out `PluginsRegistry` - it's the same mock process that's used throughout the code base:

```python
misconf = mock.Mock(misconfigured=True)
with mock.patch('letsencrypt.cli.plugins_disco.PluginsRegistry') as plugins_registry_cls:
    PluginsRegistry.find_all.return_value = [misconf]
    letsencrypt.cli.foo()
```

**Comment by pde** [comment]
Brad and I tried a few variants on that theme, and after spending 30-60 minutes without success, we decided it wasn't a good use of our time.  It's possible that we were making foolish errors.  But feel free to add a PR if you think it's the most important thing in the universe.  Personally I don't; unit tests are great but it's better to use them strategically rather than religiously.
