### ISSUE TITLE
sudo might use secure_path

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#1127]
If `Defaults secure_path` is used in your sudoers file, then `sudo letsencrypt` (e.g. when used in dev env) will not work.

Thanks to @ArchimedesPi to reporting, and @bmw for debugging.

**Comment by schoen** [comment]
I haven't heard anyone complain about this on the forum over the past 3 years so I'm going to assume that our documentation has usefully addressed this in the meantime (maybe the documentation now encourages people to `sudo -s` before activating the virtual environment or something?).
