### ISSUE TITLE
Clean up wiki

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#1128]
There is really some really old documentation in the GitHub wiki. We should fix it to avoid confusion. I'm looking at the following dinosaurs:
- https://github.com/letsencrypt/letsencrypt/wiki/Documentation
- https://github.com/letsencrypt/letsencrypt/wiki

**Comment by ArchimedesPi** [comment]
@kuba: done.

**Comment by kuba** [comment]
@ArchimedesPi I'm not sure if nuking all content was the best thing to do. The wiki contained some information that is not present in the RTD. Could you have another go, please? On the other hand... misinformation is worse than anything else.

**Comment by pde** [comment]
The wiki has been migrated into our other docs, and closed down.
