### ISSUE TITLE
If TLS to the acme server fails, print / log some meaningful diagnostics.

### ISSUE THREAD

**Issue by pde** [certbot/certbot#1136]
We saw in #1060 that the Python traceback cause by a TLS failure from a wrong clock was utterly unheplful.  Perhaps if TLS to the acme server fails, we should try harder to get a reason from our libraries, or if that's impossible, perhaps shell out to `openssl s_client connect` and print/log the reason for validation failure.

**Comment by schoen** [comment]
This continues to be a reasonably common problem—when people have bad DNS or have a firewall blocking outbound connections, the error messages they get from Certbot are rarely very useful in terms of saying "you probably have a bad DNS configuration" or "you probably have a firewall blocking outbound connections". Even if they just mentioned these possibilities, it could help a lot!

**Comment by bmw** [comment]
This seems like an uncommon problem to me and I'd rather see it fixed in `requests` so I'm going to close this for now.
