### ISSUE TITLE
Need to specify Python 2 when setting up virtualenv

### ISSUE THREAD

**Issue by njurgens** [certbot/certbot#120]
The command to setup the virtualenv should specify Python 2 for compatibility with Linux distributions that use Python 3 as the default interpreter (Arch Linux, for example).  Otherwise `setup.py` fails with syntax errors.

`virtualenv --no-site-packages --python=python2 venv`

**Comment by mnot** [comment]
FWIW - on arch you need to do a lot more than this:

> ~/letsencrypt> virtualenv2 --no-site-packages -p python2 venv
> /venv/bin/pip2 install -r requirements.txt acme/ . letsencrypt-apache/ letsencrypt-nginx/

**Comment by kuba** [comment]
@mnot, please open a new bug report

**Comment by bmw** [comment]
@mnot, I develop on Arch and specifying `pip2` isn't necessary, at least on my computer.
```
$ virtualenv2 --no-site-packages -p python2 venv
Already using interpreter /usr/bin/python2
New python executable in venv/bin/python2
Also creating executable in venv/bin/python
Installing setuptools, pip, wheel...done.
$ diff ./venv/bin/pip ./venv/bin/pip2
```
