### ISSUE TITLE
Crash in storage.py if user deleted accounts directory

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#1214]
Reported at https://community.letsencrypt.org/t/storage-py-nonetype-found/2529

If a user deletes the entire `accounts` directory, `storage.py` gives a crash on next run.

Deleting `accounts` without deleting the associated certs is not a recommended action (effectively it creates a referential integrity problem between the two), but maybe `storage.py` should be more robust and can give a more specific and useful error. I'll also file a related issue about how to change e-mail addresses, which in this case is what the user was trying to do.

**Comment by centminmod** [comment]
what about auto backing up `accounts` directory to another location if it's that important ?

**Comment by kuba** [comment]
if we back it up to `/var/lib/letsencrypt/backups` users will also delete this one...

**Comment by AndreasFagschlunger** [comment]
I was the bad guy who deleted the accounts directory and I wanted to mention that I've got the idea from the "Let's Encrypt Closed Beta Invite" mail where it says:

"This means you should avoid deleting the /etc/letsencrypt/accounts folder, or you may not be able to re-register."

**Comment by simonsmiley** [comment]
I guess letsencrypt should provide means of deleting accounts with all the associated certs/keys/....

**Comment by SwartzCr** [comment]
related to #775

**Comment by schoen** [comment]
I updated #775 to include this specific issue, so we can continue to track it over there.
