### ISSUE TITLE
Warning about port in use should appear earlier

### ISSUE THREAD

**Issue by chk1** [certbot/certbot#1216]
`The program nginx (process ID 12345) is already listening on TCP port 80. This will prevent us from binding to that port. Please stop the nginx program temporarily and then try again.`

From a usability standpoint I think it would be better to display this warning earlier in the process when running `letsencrypt-auto`, as I have to re-enter my domain names and go through all the steps. Maybe a kind of list or auto-suggestion feature for domains that I have already used would be nice.

**Comment by centminmod** [comment]
+1 this would be much better and clearer for end users :)

**Comment by wjdavis5** [comment]
+1 agreed this one got me for sure.

**Comment by pde** [comment]
I'd have marked this **2.0** but since several of you noted it as problematic, it's **nice for 1.0**.

**Comment by shrikrishnaholla** [comment]
I am planning on taking this up. Seems easy enough to begin with :+1:

**Comment by pde** [comment]
The right moment for this test is *probably* immediately after the plugins have been selected, if and only if the user is using the `standalone` authenticator:

https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/cli.py#L427

**Comment by metachris** [comment]
This PR is my suggestion of a minimal intrusive fix without code duplication: https://github.com/letsencrypt/letsencrypt/pull/1474.

**Comment by bmw** [comment]
Catching this error earlier in Certbot's execution requires checking that ports are available before we know what challenges we need to perform. For example, with the current state of the ACME protocol, Certbot, and Let's Encrypt, if you use the standalone plugin without specifying `--standalone-supported-challenges` or `--preferred-challenges` on the command line, only the `TLS-SNI-01` challenge is performed and we only check that this port is available.

To move this check any earlier than we do now we either need to:

1. Code in assumptions that we can't safely make about the ACME protocol and Let's Encrypt's behavior about what challenges will be performed.
2. Check that every port that is possibly required is available.

We feel that either of these options is worse than what we're currently doing so I'm marking this issue as wontfix.
