### ISSUE TITLE
Can't automatically configure Apache configs when using mod_macro

### ISSUE THREAD

**Issue by codecat** [certbot/certbot#1224]
I use mod_macro to configure my vhosts, so that I can do this:

```
Use VHost example.com
```

But this is not recognized.

**Comment by pde** [comment]
There are probably going to be lots of cases like this where some Apache module requires special handling.  Step one here would be to provide a clear error message if this situation applies.

Beyond that, actually emulating mod_macro in special cases or all cases sounds like a fun project for someone with strong CS skillz :)

**Comment by pde** [comment]
The error message would be a **Nice for 1.0** ticket.  Emulating mod_macro is definitely a wishlist ticket for now.

**Comment by AngeloG** [comment]
Would be very nice to have! Is there any way to manually set up my Apache config for now, though? (Or maybe it's possible to run the standalone plugin on a different port than 80 or 443?)

**Comment by joohoi** [comment]
I'm working on this currently, it seems to be a good entry issue into the codebase.

**Comment by pde** [comment]
Having landed #1385, I think the remainder of the ticket (actually parsing and editing user macros) is a wishlist ticket.

**Comment by Hinnack** [comment]
Maybe this is starting point:
https://github.com/IMSoP/mod-macro-simulator

**Comment by cylott** [comment]
I'm using mod_macro and currently can't renew my certificates. I am getting the error:
"Unfortunately mod_macro is not yet supported"

**Comment by jsoref** [comment]
I wish there was an `apachectl -S` parser, since at least then one could get the domain for the file.

I tripped on this today. (Commenting because I don't like stale bot)

**Comment by leonardosahon** [comment]
just as @cylott stated, "Unfortunately mod_macro is not yet supported" is what i receive when i try to run certbot for my multiple vhosts, please is there a way around this?

**Comment by codecat** [comment]
This is in no way the answer for everyone, but personally I switched to Caddy for my webserver needs, which does certificates automatically, and you still get that nice mod_macro configuration feel. It's ultimately a lot easier to configure and set up with automatic certificates than Apache is.

Perhaps it's a good alternative for some people in this thread.
