### ISSUE TITLE
Idea: webroot-php can set Content-Type

### ISSUE THREAD

**Issue by seraphyn** [certbot/certbot#1230]
I had problems with the manual method at All-inkl.com

At least I made my way easy and made with:
`mkdir -p .well-known/acme-challenge/`
a directory in the webroot.

Startet letsencrypt with:
`./letsencrypt-auto auth -d DOMAINNAME --authenticator manual`
Then I wrote a php-file with name well-known/acme-challenge/$CRYPTICNAME.php and the content:

``` <?php
$data = '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "blablabla"}}, "payload": "blabla", "signature": "blabla"}';
header('Content-Type: application/jose+json');
echo $data;
?> 
```

It worked.

IMO there should be an automatism to generate the content of this php-files. 
It will be  easier to use letsencrypt for customers of webhosting plattforms

**Comment by kuba** [comment]
That's what the `webroot` plugin is for: try it with `letsencrypt-auto -a webroot --webroot-path path/to/your/public_html`. The only thing that you need to do is to make sure that `Content-Type` is set up correctly.

Creating PHP files is a bit over-enginnering and non-generic solution - though it kind of solves the Content-Type problem. You can always [write your own plugin](http://letsencrypt.readthedocs.org/en/latest/contributing.html#writing-your-own-plugin) that is based on `webroot`... :)

**Comment by kuba** [comment]
Maybe we could just have `--webroot-php` flag for that?

**Comment by the-real-tokai** [comment]
I'm using the German **allinkl** web hosting service too. I simply dropped a `.htaccess` file with `ForceType application/jose+json` into the `.well-known/acme-challenge/` directory, no need for PHP.


I run **letsencrypt** in a dedicated ubuntu VM. The main problem is that it's rather time consuming to manually transfer the challenge files to the actual host on the webhoster's server. Doing this every 60 days can be a bit stressful, especially when you have to do it for a bunch of domains. :)

Maybe there could be something like `--remote-webroot-path=` where you could specify something `ssh://user@example.com/www/htdocs/foobar/public_html/`(or similar) and it would automatically sync the challenge files from the local system to the actual remote server we want to create the certificate for per ssh. Perhaps an idea to consider.

Best would be if the web hoster would support letsencrypt natively, so you just would need to enable support for it in the administration interface.

**Comment by the-real-tokai** [comment]
I guess mounting the remote server via `sshfs` locally and then passing the mount location via `-webroot-path` could do the trick, no need for a `--remote-webroot-path=` thingy. Would be interesting to know if that would work.

**Comment by kuba** [comment]
Yes, `sshfs` works OK.

**Comment by schoen** [comment]
I'm going to suggest that the last two comments successfully solved this issue back in 2015 (although maybe we should give an example of this in our documentation).
