### ISSUE TITLE
renewer should use acme.client.Client.refresh

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#1234]
`renewer.py` currently calls out to `le_client.obtain_certificate(sans)`, which does the entire authentication again and thus forces users to take down their webservers. We should use `acme.client.Client.refresh` which implements ACME Certificate Refresh.

**Comment by kuba** [comment]
Blocked on https://github.com/letsencrypt/boulder/issues/359.

**Comment by schoen** [comment]
This mechanism was subsequently obsoleted by removal of the corresponding functionality on the CA side in the ACME specification.
