### ISSUE TITLE
Uninstalling Certbot

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#1245]
As suggested by @centminmod, we should provide help for users who wish to uninstall Let's Encrypt. At a minimum, we need documentation on the process. Additionally, we could write an uninstall script that deletes the virtual environment, `logs_dir`, and `work_dir`. `config_dir` is a bit more complicated as we don't want to delete certificates and keys that the user may still be using.

**Comment by centminmod** [comment]
Also doesn't pip command for install have `--log` flag you could take advantage of ?

**Comment by yhorian1** [comment]
Being able to install and uninstall to demo the system would be brilliant.

Is anyone working on a debian package?

**Comment by bmw** [comment]
https://tracker.debian.org/news/732106

**Comment by mlissner** [comment]
+1

**Comment by connor-baer** [comment]
:+1:

**Comment by MegaMind98** [comment]
Any progress on this? This seem to be a genuine addition, users must be able to uninstall if they wish(at least the documentation).

**Comment by asafco4** [comment]
I ran certbot-auto --apache and created a certificate for a sub domain on my ubuntu server.

Now I want to revoke it, remove the SSL and delete it all, how can I do it? please elaborate?
revoking the certificate using the certbot-auto is fine, deleting the folder /etc/letsencrypt also fine, but waht changes do I need to do to my apache config? it doesn't start after the above.

**Comment by bmw** [comment]
Did Apache not start before deleting`/etc/letsencrypt`? If so, we'd love more information so we could track down the problem. For example, was is the error message when you run `apachectl -t`?

If Apache worked before deleting `/etc/letsencrypt`, the problem now is references to that directory. Normally, you could just run `certbot rollback --checkpoints 9001`, but this won't work if Apache is in a broken state.

First, you'll manually have to remove all directives referencing `/etc/letsencrypt` from your apache config. After that, see if Apache starts. Once it does, you should be able to run the rollback command above to restore your Apache config.

Finally, run `rm -rf /etc/letsencrypt /var/log/letsencrypt /var/lib/letsencrypt ${XDG_DATA_HOME:-~/.local/share}/letsencrypt` and delete the `certbot-auto` script to completely remove Certbot, including all certs, generated keys, backups, logs, etc. from your system.

**Comment by asafco4** [comment]
Hey,
Apache works well BEFORE the installation.
After the installation with the new cert and all - still working great with SSL

When I try to uninstall it, since I don't know what changes the "certbot-auto --apache" made then I can't undo it.
I can manually revoke the cert, I can delete the /etc/letsencrypt directory but some references were made in the Apache config files that needs to be undone.
I would think the best way to implement it is during the install, create a backup of every Apache config file you edit, so it can be restored automatically or manually when user choose to uninstall.

Hope it makes sense :)

**Comment by bmw** [comment]
> create a backup of every Apache config file you edit, so it can be restored automatically or manually when user choose to uninstall.

We do that. It's in `/var/lib/letsencrypt`. `certbot rollback` automatically restores your config, however, as a general rule, Certbot will not attempt to modify configurations that are already broken. 

You can attempt to restore the files manually, but the files and directory structure in there are a bit confusing. I'd personally just run `grep -r /etc/letsencrypt /etc/apache2/`, delete the lines found by `grep`, and then run `certbot rollback`.

**Comment by asafco4** [comment]
Well, that's the first time I hear about this: certbot rollback, that's exactly what I (and I think all of the people in this thread) were looking for.

You need to document it will, as I persoanlly search a lot to find an uninstall/rollback but couldn't,
as you can figure out from my failed try above to just delete folders...

Thanks.

**Comment by kimseasok** [comment]
I ran `grep -r /etc/letsencrypt /etc/apache2/` but found nothing just empty line. What's more, when run `sudo certbot rollback`, I found this error message `Certbot hasn't modified your configuration, so rollback isn't available.`

**Comment by jjakob** [comment]
Any news on this?
A command line switch for certbot to uninstall itself would be nice, but at least some docs on manual uninstallation would be necessary as currently there is absolutely no info on how to uninstall.

**Comment by bmw** [comment]
Unfortunately there's not. What you like to write a PR? The information at https://github.com/certbot/certbot/issues/1245#issuecomment-235042618 is still correct with the addition of the `/opt/eff.org` directory which should be deleted.

**Comment by jjakob** [comment]
This is still open, no documentation or fix for uninstalling. I uninstalled it recently by removing /opt/eff.org, the python packages certbot-auto installed during the bootstrap process, the above mentioned configuration and certificate dirs, and the binaries in /usr/local/bin.

**Comment by qpidcock** [comment]
Is there seriously not an uninstall for this or documentation on how to do so? Not really excited about reverse-engineering the install.

**Comment by jjakob** [comment]
The script itself doesn't install anything, it uses the certbot installed by the user to request certificates and uses standard zmcertmgr comm command to deploy it. Uninstalling it is as simple as deleting the cron jobs or timers and the script itself. If you don't need the certificate for Zimbra any more, use certbot's commands to delete it.

**Comment by jjakob** [comment]
AFAIK uninstalling certbot-auto is by deleting /opt/eff.org and the binary itself. Uninstalling certbot installed through the package manager is by using the package manager (apt-get uninstall or purge). In the certbot-auto and uninstall case /etc/letsencrypt will remain with the certificates and account data, if you don't need it that can be deleted as far as I know.

**Comment by qpidcock** [comment]
See, that's what I thought but there is nothing there. My big issue is after I installed it I started getting an error saying I had two versions installed. Now I can't seem to kill it. I even purged certbot, autoremoved all dependencies, cleaned leftover files and that didn't work. 

So I then done something horrible... not sure what I was thinking. 🤦 

import os
os.system('updatedb')
os.system('locate certbot > cert.txt')
f=open('cert.txt','r')
for x in f:
      os.system(f'rm -fr {x}')

now I'm just having a ball over here.

🤣

**Comment by jjakob** [comment]
What method did you install certbot with, certbot-auto or the package manager? Certbot-auto installs its venv into /opt/eff.org. Versions installed through the package manager should get uninstalled completely by the package manater (other than any manual configuration like cron jobs and /etc/letsencrypt). Do you have the 'letsencrypt' package installed by chance? I recall it used to be called that before 'certbot'. What does 'which certbot' and 'which certbot-auto' return?
