### ISSUE TITLE
Bundle fullchain and privkey (weechat, quassel)

### ISSUE THREAD

**Issue by evrial** [certbot/certbot#1250]
See docs here:
https://www.weechat.org/files/doc/stable/weechat_user.en.html#relay_ssl

Some software uses just one file, but `cat` each renew would be a pain.

**Comment by jleclanche** [comment]
quassel core uses the same format: https://www.youtube.com/watch?v=yjpGh9ZDECs

**Comment by jleclanche** [comment]
quassel core uses the same format: http://quassel-irc.org/faq/cert

**Comment by kuba** [comment]
this might be a duplicate of #1201, but I'm not sure

**Comment by jleclanche** [comment]
Yes it is.

**Comment by kuba** [comment]
It's not, fixing titles.

**Comment by pataquets** [comment]
Tomcat also needs fullchain + privkey file.

**Comment by jleclanche** [comment]
@kuba is this on track for a fix? It's super frustrating having to update my quassel key every few months.

**Comment by JoKeyser** [comment]
Until fixed, a good workaround would be to define a renew-hook that creates the necessary files upon successful certificate renewal. That way you don't have to re-do that manually.

**Comment by sydneyli** [comment]
Given that the most discussion is on #5087 about this exact issue, I'm closing this in favor of that one.
