### ISSUE TITLE
Unable to install certficiate to Apache

### ISSUE THREAD

**Issue by xZise** [certbot/certbot#1266]
I tried to obtain and install a certificate for Apache today and while I was able to obtain one, I wasn't able to install it. Apart from the fact that the command in the beta invite e-mail was using auth which is afaik not installing the certificate and you can't simply say “okay now install it”.

Anyway I got the following error:

    Cannot find a cert or key directive in
    /files/etc/apache2/sites-available/ssl.conf/virtualhost.
    VirtualHost was not modified

And I'm wondering what exactly that means. Now looking at the [source code](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt-apache/letsencrypt_apache/configurator.py#L203) it seems that `ssl.conf` already needs to contain `SSLCertificateFile` and `SSLCertificateKeyFile` which seem odd because if they are already there… I wouldn't need to install it.

Now for full disclosure, I already had tried to use SSL so the file already had `SSLCertificateFile` defined (but not the `SSLCertificateKeyFile`). So maybe that's the issue?

**Comment by pde** [comment]
Related to #1213.  Probably a good patch for that bug will fix this too.

**Comment by waspinator** [comment]
I'm still having this issue. I'm confused why it's looking for things in /files/... I don't have that directory

**Comment by bmw** [comment]
@waspinator, the Apache plugin internally uses [Augeas](http://augeas.net/) to help with parsing/modifying configuration files. The `/files/...` prefix is simply Augeas's representation of the path. Regardless, this is confusing and we should not be showing this to users so I created #2246 to track the issue.

**Comment by awikatchikaen** [comment]
Hi, i've got the same problem on a fresh install of apache/certbot on a debian. 

"Unable to find cert and/or key directives" ... obvious, don't have any yet ...

**Comment by bmw** [comment]
@awikatchikaen what commands did you run?

**Comment by awikatchikaen** [comment]
À simple command :

Certbot --apache

**Comment by steckerhalter** [comment]
I have the same issue using `certbot --apache`. I had to add:

```
	SSLEngine on
	SSLCertificateFile    /etc/ssl/certs/ssl-cert-snakeoil.pem
	SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key
```

for it to work. using certbot 0.6.0 from debian jessie backports

**Comment by steckerhalter** [comment]
I realized just now that 0.6.0 is quite behind the current 0.8.0. Maybe jessie backports shouldn't be advertised if it is lagging behind like this?

**Comment by patf** [comment]
`0.7.0` and `0.8.0` were released 8 and 2 days ago respectively. There haven't been *that* many changes between those two/three releases and `0.6.0` is still fairly recent. The debian package is tracking upstream pretty closely, `0.8.0` hit `unstable/NEW` last night and should hit jessie-backports soon enough (not sure what the usual timeframe is).

**Comment by steckerhalter** [comment]
ok, assumed 0.6.0 <> 0.8.0 would be quite a difference... then it's just a problem anyway I guess :)

**Comment by awikatchikaen** [comment]
Hi,

I resolve the problem, and it was a bit my fault. I had create the vhost with port 443, so certbot was looking for certificate.
I change the 443 to 80, restart certbot with "certbot --apache -d mydomain.com" and ask a automatic redirection. Certbot create the new 443 vhost file with correct lines.

Thank you !!

**Comment by steckerhalter** [comment]
hmm, so maybe I misunderstood how this is supposed to work? should first create virtualhost with port 80 and certbot will then create the other vhost?

**Comment by bmw** [comment]
@steckerhalter, you should first create at least one vhost for the domain you want to set up HTTPS for. This can either be an HTTP vhost, an HTTPS vhost, or both. After doing that, `certbot` should be able to run and create/modify the correct vhost to set up HTTPS, redirects, etc. It needs at least one vhost that it can use as a template when creating/modifying the other vhosts.

You said you had to add SSL directives before in order to make `certbot` work. Did you encounter the problem by creating a vhost that didn't support HTTPS on port 443?

**Comment by steckerhalter** [comment]
@bmw yes, that's what I encountered. I had to add the ssl directives, otherwise I got the message "Unable to find cert and/or key directives"

This was not the only issue. The other problem was that I said certbot should create redirects (having old https vhosts that were correctly modified). The redirects were not done even though it said they already exist. So I had to create them manually.

**Comment by bmw** [comment]
OK. I successfully reproduced the "Unable to find cert and/or key directives" error and created #3136 to track that specific issue.

As for the redirect problem, based on what you posted I'm assuming you saw a message like this:
```
2016-06-08 10:33:20,756:WARNING:certbot.client:Enhancement redirect was already set.
```

If so, is it possible the redirect was created somewhere where you didn't expect? For example, if you don't have a port 80 vhost for the domain you're trying to enable the redirect for, Apache may have put the redirect in the the default 80 vhost like this:

```
RewriteEngine on
RewriteCond %{SERVER_NAME} =example.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]
```

If you `grep` your vhosts for the domain where you had this problem, does it come up anywhere that you did not expect?

If you did not see the "Enhancement redirect was already set" message or `grep` doesn't shed any light on the issue, do you have the logs from this run? By default, logs are stored in `/var/log/letsencrypt`. Alternatively, if you can reproduce the problem, simply run the client with `-vv`.

**Comment by steckerhalter** [comment]
i removed my redirect vhosts and tried again. Apparently another RewriteRule for an outdated (and different) domain from a previous test had been added to `000-default.conf`. I removed that and certbot added a RewriteRule for the domain in question but not for the  two subdomains. (I have three vhosts of which two are subdomains). It said twice that `Enhancement redirect was already set` but it doesn't redirect the subdomains.

**Comment by bmw** [comment]
@steckerhalter, which version of `certbot`/`letsencrypt` are you using?

**Comment by steckerhalter** [comment]
0.6.0  currently. But I also tried with with 0.8.0 (see comments above)

**Comment by bmw** [comment]
Sorry for all the questions but I'm unable to reproduce this problem.

What command did you run to enable the redirect? Do you have a single cert for all subdomains? Is each subdomain in the same HTTPS vhost file or are they in separate ones?

**Comment by steckerhalter** [comment]
I used either `certbot` or `certbot --apache`. I can't reproduce exactly what happened. I decided to start anew with vhosts containing ` :80` and now certbot created le-ssl files with proper redirects. I guess this is pretty complex because there are so many different constellations.

IMO it would make sense to direct the user what he should prepare in order to activate letsencrypt for now and add support for all the edge cases as time goes by.

**Comment by bmw** [comment]
Yeah the redirect issue is a bit tricky. Regardless, `certbot` should either properly set up the redirect or tell the user it was unable to do so. We want to avoid partially or even worse incorrectly setting up the redirect.

I created #3136 to track the issue of adding documentation about how to prep an Apache config for use with `certbot`.

If you're able to reproduce the redirect problem, please open a new issue with steps to reproduce the problem. Thanks for all your time @steckerhalter.
