### ISSUE TITLE
Minor errors in CPS

### ISSUE THREAD

**Issue by heypete** [certbot/certbot#1267]
The CPS available at http://cps.letsencrypt.org/ has some errors:

3.2.2.2 For DV-SSL Certificates, the CA provides a secure means of validating the Applicant’s control over, the device and domain name for which a Certificate is requested. 
- There should be no comma between "control over" and "the device".

4.6.1 Circumstance for Certificate Renewal
A Certificate may be renewed if the Key Pair has not reached the end of its validity, the Private Key has not been compromised, and the Certificate information and attributes are correct. Thus, the CA may choose to implement a three-year re-key period with an initial issue and two annual renewals before Renewal is required. The old Certificate need not be revoked, but must not be further renewed or updated.

-Is this supposed to say -- as written -- "Thus, the CA may choose to implement a three-year re-key period with an initial issue and two annual renewals before Renewal is required." or should it say "...a three-year renewal period...before re-keying is required"? The way it's written in the CPS doesn't make much sense to me.

**Comment by SwartzCr** [comment]
Unfortunately thes comments should be referred to let's encrypt and not certbot. Feel free to post about them at https://community.letsencrypt.org/
