### ISSUE TITLE
Letsencrypt deinstalls postfix on FreeBSD

### ISSUE THREAD

**Issue by mfechner** [certbot/certbot#1270]
Install letsencrypt and start it on FreeBSD with:
./letsencrypt-auto --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory auth

It killed my complete mailsetup as it starts to install packages using pkg on FreeBSD and does not use the already installed packages.
It uninstalled postfix and installed sendmail, this can be seen as absolutely critical, this needs really to be fixed, as the complete mailsetup on this system is now destroyed and I have to reinstall all manually now.

Suggestion: If you start to install software on the computer with root privileges, ask the user before.
Here the user should get a prompt and endless time to read what he is doing!
I do not even have an idea how letsencrypt can do this, as I was logged in as normal user.

**Comment by barshinoff** [comment]
I don't know why this bug wasn't taken more seriously.

Deinstalling packages seems like a extremely serious bug. All this attention has been given to making sure conf file changes can be undone when you use letsencrypt but you might just break your webserver when you install letsencrypt in the first place and the only comment was have it require --debug.

Break a few webservers and nobody will trust this software.

**Comment by ohemorange** [comment]
There's an official package for FreeBSD, so I'm closing this.
