### ISSUE TITLE
http-01 support in nginx

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#1273]
It's not that simple as #1272, because you can't use `location{}` outside `server{}`, but we could add only `include /etc/letsencrypt/nginx-http01-location.conf` to all affected `server{}` stanzas. Less messing with user's config => better experience!

**Comment by ZeusF1** [comment]
Agree, this would safe a lot time while configuring nginx
   Detail: Failed to connect to <>:443 for TLS-SNI-01

No idea why at first install it trying to get to SSL port, which is not configured yet.

**Comment by sydneyli** [comment]
fixed in #5414.
