### ISSUE TITLE
Clarify Copyright

### ISSUE THREAD

**Issue by hlieberman** [certbot/certbot#1275]
I'd like to see a bit more clarification about exactly who the copyright holders are for the code as it currently stands.  The documentation has 2014-2015, Let's Encrypt Project, while the LICENSE file says that it's 2015, EFF "and others".  I don't mind the generic blanket "and others" (though probably I'd use the language "contributors"), but Debian will want more clarity around who exactly owns the code, not just that it's Apache-2.0.

2014-2015, Let's Encrypt Contributors would work.

@pde, this is probably in your lap?

**Comment by kuba** [comment]
related to #211

**Comment by pde** [comment]
@hlieberman would EFF and other Contributors work for you?

**Comment by hlieberman** [comment]
Yeah. Consistency is the most important thing. The docs and license need to
agree.
