### ISSUE TITLE
Generate dhparams.pem

### ISSUE THREAD

**Issue by jleclanche** [certbot/certbot#1277]
cf https://weakdh.org/sysadmin.html

Recommended ssl configs include this. LE could generate that alongside the certs.

**Comment by evaryont** [comment]
Just to be clear, you're only considering the generation of the dhparams file? Configuring the servers could be done in the plugins, and would require a consistent path. (Perhaps `live/dhparams.pem`?)

**Comment by jleclanche** [comment]
Yes.

**Comment by ohemorange** [comment]
Done: https://github.com/certbot/certbot/issues/374#issuecomment-337328034
