### ISSUE TITLE
JSON parsing logic

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#1295]
JSON parsing logic is overly complex. The reason we use JSON is so that when you ingest messages, you can just do a `JSON.parse()` and go about your business. Instead, the client has this whole fancy encoder/decoder architecture. Is this necessary?

**Comment by schoen** [comment]
@bmw, is this old issue referring to the ACME implementation in particular?

**Comment by bmw** [comment]
It was about simplifying `josepy` when it was still in this repo. This issue is very vague and doesn't seem like the kind of thing we'll get to for a very long time so I'm closing this issue.
