### ISSUE TITLE
Client is not factored into separate pieces

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#1299]
The client needs to be more cleanly broken it to separate pieces and modules. This makes the client easier to understand, easier to use, and more maintainable.

**Comment by pde** [comment]
The client *is* factored into pieces -- acme, the plugins, and the main client to bind them together.  What more factoring would we want to do?

**Comment by jhalderm** [comment]
If one piece was just a minimal ACME client, we could distribute that separately, minimizing dependencies.

**Comment by bmw** [comment]
I agree that further splitting up the client would also help reduce our dependencies. Additionally, further subdividing the client allows users to only install the functionality they want instead of a large, monolithic client.

With that said, there are few problems with doing this:

1) This minimal client should probably still depend on the `acme` library for interfacing with `boulder`. The `acme` package has the following dependencies:
* OS dependencies
  * python-dev
  * virtualenv
  * gcc
  * libssl-dev
  * libff-dev
* Python dependencies:
  * cryptography
  * ndg-httpsclient
  * pyasn1
  * PyOpenSSL
  * pytz
  * requests
  * setuptools
  * six
  * werkzeug

This list is certainly smaller than the full list of client dependencies, but it still quite large.

2) Due to the architecture of the `letsencrypt` client, it would be much easier to simply write a separate, standalone client than try to factor out pieces of the main client. Perhaps the effort of splitting functionality out of the main client might be worth it in the long run, but it would take significantly more time.

**Comment by kuba** [comment]
NB that was the whole idea behind #358 - which would leave the `standalone` and `webroot` in the core package only. Unfortuntely, @pde seems to prefer to bundle everything together :(.

BTW I invite everyone interested to have a look at https://github.com/kuba/simp_le and contribute :) Together with `pyinstaller` setup it's possible to turn entire client into 8MB single executable that depends on glibc only. :)
