### ISSUE TITLE
Too many dependencies

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#1301]
Users/developers have reported that our project has too many Python dependencies. This is related to things being overly complex.

Here is pde's attempt to characterize what our dependencies currently are: 

> 1. Purely for certbot-auto and the things it needs to build, not for
>    the python code itself (these no longer apply on recent OSes where we have packages):
>    
>    ~~git~~
>    gcc 
>    python-dev
>    libffi-dev
>    libssl-dev
>    setuptools
>    virtualenv
> 2. Essential OS packages
>    python
>    openssl
> 3. Semi-essential OS packages:
>    ~~dialog~~
> 4. Needed for specific plugins:
>    
>    ~~python-psutil (standalone -- see what has bound :80 or :443)~~ (now only "recommended")
>    libaugeas0 (apache -- parse & edit conf files)
>    python-augeas
> 5. Python dependencies:
>    
>    ConfigArgParse       (for reading config files)
>    configobj            (for writing & reading renewal conf files)
>    python-cryptography (>= 0.8)
>    PyOpenSSL  ~~(>= 0.15)~~ (>= 0.13)
>    ~~pythondialog~~
>    ~~ndg-httpsclient  (for working around TLS insecurities in older Python versions)~~
>    requests
>    six 
> 6. Python dependencies specifically related to time processing. It seems
>    absurd that there are four of these:
>    
>    ~~werkzeug~~
>    pytz
>    parsedatetime
>    pyicu (needed by parsedatetime)
>    pyrfc3339
> 7. Python dependencies for python-cryptography:
>    idna
>    enum34
>    ipaddress
>    cffi
>    pycparser (build dep only, but affects letsencrypt-auto)
>    pyasn1
> 8. These were used to define plugin interfaces.  Not sure if that was wise,
>    but it's probably annoying to third parties if we ditch them:
>    
>    zope.components
>    zope.interface
>    zope.event
> 9. Development and doc-building dependencies.  For reasons I don't
>    yet understand, pip always fetches some of these too:
>    
>    mock
>    funcsigs (mock depends on this)
>    pbr (mock depends on this)
>    sphinxdocs

**Comment by pde** [comment]
We should be able to remove some of them.  At some point we could go from needing argparse (which isn't a non-Python dependency), configargparse, and configobj, to needing zero or one of those.

Perhaps we one day we can get rid of PyOpenSSL.

We have three time-related dependencies, pyrfc3339, parsedatetime, pytz.  Perhaps we can rationalise those.

**Comment by pde** [comment]
First small subticket: #1861

**Comment by pde** [comment]
Here is my attempt to characterise what our dependencies currently are: 

1. Purely for letsencrypt-auto and the things it needs to build, not for
the python code itself:

    git
    gcc
    python-dev
    libffi-dev
    libssl-dev
    setuptools
    virtualenv

2. Essential OS packages
    python

3. Semi-essential OS packages:
    dialog

4. Needed for specific plugins:

    python-psutil (standalone -- see what has bound :80 or :443)
    libaugeas0 (apache -- parse & edit conf files)
    python-augeas

5. Python dependencies:

    ConfigArgParse       (for reading config files)
    configobj            (for writing & reading renewal conf files)
    python-cryptography
    PyOpenSSL
    pyasn1          (unclear why we depend on this... maybe InsecurePlatformWarning)
    pythondialog
    ndg-httpsclient
    requests
    six

6. Python dependencies specifically related to time processing. It seems
absurd that there are four of these:

    werkzeug
    pytz
    parsedatetime
    pyrfc3339

7. Python dependencies for python-cryptography:
    idna
    enum34
    ipaddress
    cffi
    pycparser (build dep only, but affects letsencrypt-auto)

8. These were used to define plugin interfaces.  Not sure if that was wise,
but it's probably annoying to third parties if we ditch them:

    zope.components
    zope.interface
    zope.event

9. Development and doc-building dependencies.  For reasons I don't
yet understand, pip always fetches some of these too:

    mock
    funcsigs (mock depends on this)
    pbr (mock depends on this)
    sphinxdocs

**Comment by bmw** [comment]
To elaborate on @pde's comments (which I moved to the first post in this issue), I tried to characterize some actions we could take to reduce or dependencies. While I believe reducing our dependencies is a worthwhile goal, it is worth noting that it will slow down development on other features of the client.

### Remove dependency on git
This is going away in `0.2.0` with the changes to `letsencrypt-auto`.

### Remove psutil, cryptography, and PyOpenSSL
This would be a major change. We currently use the three packages for the following:

##### psutil
* Used to tell the user what process is listening on the port we want

##### cryptography
* SHA2
* HMAC
* RSA 
    - PSS and PKCS1v15 padding
    - Help with RSA to/from JSON
* Serializing/parsing keys and certs
* Loading/saving/converting keys

##### PyOpenSSL
* Generating RSA keys
* Serializing/Parsing certs and CSRs
    - Getting data like notBefore/notAfter values from certs
* TLS handshake
* Creating certs/CSRs
* Loading/saving/converting certs and CSRs

Removing `psutil` may be a minor usability loss and removing `cryptography` and `PyOpenSSL` would be a lot of work. We could likely replace all/most of this functionality with calls to the `openssl` command line. I don't think that's as clean from a code quality perspective, but it would allow us to drastically reduce our dependencies. Removing these three dependencies removes the following additional packages:

##### OS packages:
* gcc 
* python-dev
* libffi-dev
* libssl-dev

##### Python packages
* idna
* enum34
* ipaddress
* cffi
* pycparser

### Consolidate werkzeug, pytz, parsedatetime, and pyrfc3339 into one package

There packages are all for parsing/manipulating dates and may are only used in one or two places in the code. Do we really need four packages for this or can we consolidate them? Their current uses are:

##### werkzeug (used exactly once in the code)
* parse value of Retry-After header

##### pytz
* specifying UTC timezone to other libraries

##### parsedatetime
* determining the difference between two date/times

##### pyrfc3339
* you guessed it: parse/generate RFC3339 timestamp

### Consolidate/remove configargparse/configobj
These packages are both used for processing config files. They do slightly different things, but we could remove `configargparse` and only use `configobj`. It'd be slightly hacky and only allows us to drop one package, but we have code that does a lot of what `configargparse` does using `configobj` in `renewer.py`.

With this said, both projects are largely unmaintained and perhaps we should consider other alternatives.

### Install pyasn1 and ndg-httpsclient only when needed
These packages are used to fix the `InsecurePlatformWarning` that occurs while using `urllib3` with older versions of Python. We currently always install these packages and doing so is not necessary.

**Comment by kuba** [comment]
If you want to `subprocess` everything to `openssl` binary maybe you should consider switching the default client to C/C++? :P Or maybe Go?

To be clear here, I don't want `acme` to be using `subprocess`, so that would have to be a completely new project / library.

**Comment by bmw** [comment]
We should maybe look into `dateutil` as a replacement for our 3 date/time parsing packages.

**Comment by bmw** [comment]
For more progress here, we've removed `dialog` and are planning on removing the optional dependencies `psutil` and `dnspython` in the next release.

**Comment by ekohl** [comment]
Moving mock to ```tests_require``` would also be great. I'd like to include ```acme``` in my setup.py requirements but that would also require me to deploy mock on my production machines.

**Comment by pde** [comment]
The dialog dependencies were removed by #3662.

**Comment by pde** [comment]
The `ndg-httpsclient` dependency was removed by #3805. We still depend on `pyasn1`, unfortunately, because PyOpenSSL requires it.

**Comment by bmw** [comment]
We've discussed the possibility of removing our reliance on `PyOpenSSL`. I was thinking about this and one area where this may be especially hard is getting around the lack of TLS support in older versions of Python.

**Comment by pde** [comment]
One measure of how we're doing on this is the bandwidth taken to install a packaged copy of certbot:
```
root@jessie-bloat-test:~# apt-get install certbot python-certbot -t jessie-backports
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  python-cffi python-ply python-pycparser
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  dialog python-acme python-cffi python-cffi-backend python-configargparse python-cryptography python-dialog python-dnspython python-enum34 python-funcsigs
  python-idna python-ipaddress python-mock python-openssl python-parsedatetime python-pbr python-pkg-resources python-psutil python-pyasn1 python-pyicu python-rfc3339
  python-setuptools python-six python-tz python-zope.component python-zope.event python-zope.interface
Suggested packages:
  python-certbot-apache python-certbot-doc python-acme-doc python-dev python-cryptography-doc python-cryptography-vectors python-enum34-doc python-funcsigs-doc
  python-mock-doc python-openssl-doc python-openssl-dbg python-psutil-doc doc-base python-setuptools-doc
Recommended packages:
  letsencrypt
The following NEW packages will be installed:
  certbot dialog python-acme python-certbot python-cffi-backend python-configargparse python-dialog python-dnspython python-enum34 python-funcsigs python-idna
  python-ipaddress python-mock python-parsedatetime python-pbr python-psutil python-pyicu python-rfc3339 python-tz python-zope.component python-zope.event
  python-zope.interface
The following packages will be upgraded:
  python-cffi python-cryptography python-openssl python-pkg-resources python-pyasn1 python-setuptools python-six
7 upgraded, 22 newly installed, 0 to remove and 55 not upgraded.
Need to get 2,164 kB of archives.
After this operation, 8,158 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
```
The Nginx plugin increases that to 2,250 kB of archives; the Apache plugin increases it to 3,883 kB.

**Comment by pde** [comment]
On a Yackety droplet it's a 6,075kB download, but that includes Python.  Assuming the user already has Python installed:
```
root@yackety-bloat-test:~# apt-get install certbot
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  grub-pc-bin
Use 'apt autoremove' to remove it.
The following additional packages will be installed:
  dialog libpython-stdlib python python-acme python-certbot python-cffi-backend python-chardet python-configargparse python-configobj python-cryptography
  python-dialog python-enum34 python-funcsigs python-idna python-ipaddress python-minimal python-mock python-ndg-httpsclient python-openssl python-parsedatetime
  python-pbr python-pkg-resources python-psutil python-pyasn1 python-pyicu python-requests python-rfc3339 python-setuptools python-six python-tz python-urllib3
  python-zope.component python-zope.event python-zope.hookable python-zope.interface
Suggested packages:
  python-certbot-apache python-certbot-doc python-doc python-tk python-acme-doc python-configobj-doc python-cryptography-doc python-cryptography-vectors
  python-enum34-doc python-funcsigs-doc python-mock-doc python-openssl-doc python-openssl-dbg python-psutil-doc doc-base python-socks python-setuptools-doc
  python-ntlm
The following NEW packages will be installed:
  certbot dialog libpython-stdlib python python-acme python-certbot python-cffi-backend python-chardet python-configargparse python-configobj python-cryptography
  python-dialog python-enum34 python-funcsigs python-idna python-ipaddress python-minimal python-mock python-ndg-httpsclient python-openssl python-parsedatetime
  python-pbr python-pkg-resources python-psutil python-pyasn1 python-pyicu python-requests python-rfc3339 python-setuptools python-six python-tz python-urllib3
  python-zope.component python-zope.event python-zope.hookable python-zope.interface
0 upgraded, 36 newly installed, 0 to remove and 0 not upgraded.
Need to get 2,310 kB of archives.
After this operation, 12.5 MB of additional disk space will be used.
```

**Comment by dancvrcek** [comment]
ah, this was needed

sudo pip install --upgrade six

**Comment by SwartzCr** [comment]
Is the goal of this issue to entirely get rid of dependencies, or do we have a target for an acceptable amount?

**Comment by ekohl** [comment]
As a user I'd say some dependencies make sense. You do not want to rewrite things like requests. What does annoy me is that testing dependencies (mock) also end up being needed at runtime.

**Comment by pde** [comment]
The goal of this ticket was just to shrink the dependency set to get to a point where it's non-painful to install and upgrade Certbot, even on slow machines with slow internet connections.

@ekohl if you're still seeing things like mock being pulled in for runtime installs: what method of installation are you using?

**Comment by ekohl** [comment]
@pde because of https://github.com/certbot/certbot/blob/bf30226c697402adac656bfd7956395fc104714b/setup.py#L45 I'm sure pip will pull it in. Typically I use my distro packages and both Gentoo and Fedora still require mock as a runtime dependency.

**Comment by ekohl** [comment]
Mock is still a install dependency where I'd expect it to be a dev dependency.
https://github.com/certbot/certbot/blob/02cf051e45e4a5eb4a941857cc6b54846099ad82/setup.py#L46

**Comment by FelixSchwarz** [comment]
@ekohl #6604 is specifically about the `mock` issue.

(Side note: I'll try to add Fedora-specific patch so at least with Fedora+EPEL you don't get `python3-mock` anymore.)

**Comment by ekohl** [comment]
Looks like now `mock` is only required on Python < 3.3 so I think this is mostly solved. At this point the only candidate I see is `six`, but that probably requires dropping Python 2 support. In my experience it's better to have a focused issue for that though.

**Comment by bmw** [comment]
I'm also in favor of more specific issues so I'm closing this and referencing the specific issues https://github.com/certbot/certbot/issues/8492, https://github.com/certbot/certbot/issues/8493, https://github.com/certbot/certbot/issues/8494, https://github.com/certbot/certbot/issues/7913, and https://github.com/certbot/certbot/issues/7901.
