### ISSUE TITLE
Command line parsing

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#1305]
This is hacked together making it very hard for new contributors to understand what is going on.

**Comment by TheNavigat** [comment]
Yep, that is true, it is very hard for new contributors to understand what is going on ._.

**Comment by pde** [comment]
Rewriting the CLI in a fundamental way would be ideal, but won't happen until 2.0 at the earliest.  Realistically in the mean time, we could add a brief into doc in cli.py that explains the HelpfulArgumentParser and the way the plugins enter into the CLI.

**Comment by bmw** [comment]
Closing in favor of https://github.com/certbot/certbot/issues/4493 which has more discussion.
