### ISSUE TITLE
Clarify purpose of --email

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#1310]
This is another good issue pointed out by @centminmod. How is `--email` actually used? If you're automating running `letsencrypt`, should the flag be included every time? Does it need to be the same e-mail address each time? What happens if it's different?

The current behavior is `--email` is only used if you're creating a new account with the ACME server, otherwise the flag is ignored. Is this the behavior we want? Could we filter/choose your account based on the e-mail address if you have multiple ACME accounts? Even if we do not want to change its behavior, the purpose of this flag should be better documented.

**Comment by centminmod** [comment]
thanks @bmw the original context of my question at https://community.letsencrypt.org/t/clarify-the-email-flag-requirements/2603

**Comment by bmw** [comment]
The value is saved on the ACME server as well as locally in a JSON file locally. The local copy is in the configuration directory, so using the default paths, its location would look something like:
```
/etc/letsencrypt/accounts/<server_url>/directory/<hash>/regr.json
```
where the values between the brackets are replaced with their respective values.

**Comment by SwartzCr** [comment]
I think that we should have a whole section of the documentation that describes acme accounts - It should also mention that we don't currently support multiple email addresses per account: #4242

**Comment by ohemorange** [comment]
We now have `--update-registration`, where you can pass `--email` to update your email address on the server. And #6006 aims to make that process even easier. Closing this issue because now the information is here, where people can find it just as easily as in our official documentation using a search engine.
