### ISSUE TITLE
Remove testing packages from PyPI

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#1318]
@pavel-paulau, could you please remove the following package from PyPI: https://pypi.python.org/pypi/3ab8c7d15dcda79f1a5cde4f39b06614/0.0.0.dev20151024. It's showing up, when querying for letsencrypt: https://pypi.python.org/pypi?%3Aaction=search&term=letsencrypt&submit=search

Unfortunately, all other letsenncrypt-nginx-\* packages, although already removed, are also visible in the results. Would you be able to talk to PyPI team to resolve this issue, @pavel-paulau?

**Comment by pavel-paulau** [comment]
@kuba,

I removed the package you mentioned above.

I will try to reach out to PyPI team. However, the project is almost abandoned and I would not expect resolution any time soon.

**Comment by bmw** [comment]
This has been fixed.
