### ISSUE TITLE
Certificate signed but not installed

### ISSUE THREAD

**Issue by hansharhoff** [certbot/certbot#1323]
I followed the instruction from the BETA email as follows:

```
git clone https://github.com/letsencrypt/letsencrypt
cd letsencrypt
./letsencrypt-auto --agree-dev-preview --server \
   https://acme-v01.api.letsencrypt.org/directory auth
```

and I fill out the desired hostname etc.

I receive this response:

```
IMPORTANT NOTES:
- Congratulations! Your certificate and chain have been saved at
/etc/letsencrypt/live/iontrap.phys.au.dk/fullchain.pem. Your cert
will expire on 2016-02-02. To obtain a new version of the
certificate in the future, simply run Let's Encrypt again.
```

Indicating that Let's encrypt was succesful, but no indication of what further action is needed on my part. I was using a self-signed certificate which is still the one being used by apache2.

1) It was my understanding that running the letsencrypt should complete the install. Perhaps a note at the beginning should indicate what is the expected outcome of running the program e.g.:

"This is Let's encrypt. By running this command you will generate, have signed, and install a certificate to your webserver"

2) Then if letsencrypt does not in the end install the certificate it could have an (additional) important note saying:

"Letsencrypt did not install the newly signed certificate since you are already using a certificate.
To replace this certificate run this command (or see this website) or change this config-file"
or it could ask whether to install the certificate.

I believe that otherwise users would try to manually point apache2 to the new certs manually or perhaps copy the new certs to the location of the old certs which would then not work when the certs where to be renewed.

**Comment by notDavid** [comment]
Confusing indeed. I was also wondering whether the certificates got configured automatically or not. In my case it wasn't configured, so i had to do it manually.
A message indicating that automatic configuration has failed and pointing to the right website (like https://letsencrypt.readthedocs.org/en/latest/using.html#where-are-my-certificates perhaps) wouldn't hurt...

**Comment by hansharhoff** [comment]
@notDavid , thanks this was the page I needed for being confident enough to configure apache2 with letsencrypt.
I think a simply link like that would offset the disadvantage of not automatically installing the certs.

**Comment by SwartzCr** [comment]
I'm going to close this as resolved, due to the age of this ticket.
