### ISSUE TITLE
renewer does not use full path when accessing config files

### ISSUE THREAD

**Issue by marcan** [certbot/certbot#1325]
`os.listdir` returns basenames only, not full paths:
https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/renewer.py#L171

This makes the renewer only work if it is run from the `/etc/letsencrypt/renewal` directory. `cli_config.renewal_configs_dir` needs to be prepended to `renewal_file`.

**Comment by SwartzCr** [comment]
I believe this is resolved, closing.
