### ISSUE TITLE
documentation:  ./letsencrypt not equivalent to ./letsencrypt-auto

### ISSUE THREAD

**Issue by JohnDenker** [certbot/certbot#1338]
The documentation at https://letsencrypt.readthedocs.org/en/latest/using.html#id5 says:

> Throughout the documentation, whenever you see references to letsencrypt script/binary, you can substitute in letsencrypt-auto. For example, to get the help you would type:

That seems to imply that  ./letsencrypt and ./letsencrypt-auto are equivalent.  In fact they are not. 
1. I observe that  ./letsencrypt-auto is a useful executable script.
2. It is not a script/binary.  It is just a script.
3. ./letsencrypt is neither a script nor a binary.  It's a directory.

Specific suggestions:  
- Main point:  The documentation should be changed to eliminate references to ./letsencrypt in places where ./letsencrypt-auto is needed.
- Minor point:  documentation shouldn't say script/binary.  Perhaps the intent was to say "executable script".
# 

Details:

```
:; git show HEAD
commit de182946b5cf09a3486f38d3df0c43e2280b3654

:; ./letsencrypt-auto --version
Updating letsencrypt and virtual environment dependencies......
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt --version
letsencrypt 0.0.0.dev20151104

:; uname -a
Linux cloud 3.11.4+ #11 Fri Oct 11 05:39:29 PDT 2013 x86_64 x86_64 x86_64 GNU/Linux

ubuntu trusty LTS
```

**Comment by kuba** [comment]
I don't agree with the suggestion to swap all occurrences of `letsencrypt` with `letsencrypt-auto`.  I think you're missing some conceptual context here.  No one talks about `./letsencrypt`, but `letsencrypt`, the script installed in `~/.local/share/bin/letsencrypt`, the same script that will be installed in Debian as `/usr/local/bin/letsencrypt`, etc.

**Comment by JohnDenker** [comment]
In any case, if we want to have user-friendly code and user-friendly documentation, the point remains:

For whatever scripts and/or binaries we are talking about, each one should have a unique, definite name.   One concept per name, and one name per concept.  The user should not be asked to rewrite the documentation on the fly.

**Comment by pde** [comment]
@JohnDenker The real answer is `letsencrypt-auto` is a wrapper that's intended to work pretty well on OSes where Let's Encrypt isn't packaged yet.  Once it's packaged, there will be a `letsencrypt` command.  `letsencrypt-auto` has enough side effects (it installs a few OS dependencies and lots more stuff in a virtual environment, and it auto-updates the client) that we didn't want to name it `letsencrypt` (and would have had to restructure our tree to move `letsencrypt/` out of the way to do so, too).

If you have a suggestion about how to document that in a simple and efficient manner, please send a pull request :)

**Comment by JohnDenker** [comment]
Here's a possibility to consider.  As a general rule, if the program behavior is that difficult to document, the first thing it needs is better behavior.  Once we have decent behavior we can decide how to document it.

Here a possible step in the right direction.  This is modeled on more-or-less every app I can think of.  Pick a name for the user interface.  Stick with this name.  Document this name.  Do whatever is necessary in the code to make it work.  Often this involves layers of indirection.  For example, on my system ``firefox`` is shorthand for ``/usr/bin/firefox`` which is a symlink to ``/usr/lib/firefox/firefox.sh`` which in turn is a shell script that serves as a wrapper for ``/usr/lib/firefox/firefox`` which is the binary that does most of the work.

The point is that the name seen by the user interface (and the documentation!) remains the same, even as the implementation details change from time to time and from platform to platform.

**Comment by SwartzCr** [comment]
I believe this was fixed with the re-name. See: https://letsencrypt.readthedocs.io/en/latest/using.html#certbot-commands
I'm going to close this issue, @JohnDenker if you feel like the documentation could still be improved, let me know and I'd be happy to expand/update it
