### ISSUE TITLE
Persistence of .pyc files causes periodic local tox failures

### ISSUE THREAD

**Issue by pde** [certbot/certbot#1342]
I just wasted a bunch of time chasing down another instance of this. We should probably rm them in the `dev/venv.sh` script, at the very least.

**Comment by kuba** [comment]
Are you using `./venv/bin/tox` or system wide `tox`?

**Comment by pde** [comment]
The problem happened with both.

**Comment by pde** [comment]
(venv activated or not)

**Comment by pde** [comment]
Once .pyc files were deleted, both started working.

**Comment by pde** [comment]
The errors were https://paste.debian.net/hidden/2a0964f1/, presumably caused by some .py file moving around?

**Comment by devnsec-com** [comment]
Why don't we just simply set the `PYTHONDONTWRITEBYTECODE` environment variable in that script?

**Comment by SwartzCr** [comment]
closing this issue as resolved
