### ISSUE TITLE
Manual authenticator should support DVSNI 

### ISSUE THREAD

**Issue by bluecmd** [certbot/certbot#1347]
Hi,

Unless I'm missing something the manual authenticator should be able to support DVSNI.
I cannot use HTTP01 since we don't allow any incoming HTTP connections, and I would prefer to have an automatable way to using non-supported webservers for certificate validation - and manual seems to be easiest way of doing this.

This is also reflected in the code: https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/plugins/manual.py#L34

**Comment by pde** [comment]
Deprecating in favour of #4636
