### ISSUE TITLE
Tool for A+ SSL rating

### ISSUE THREAD

**Issue by mommel** [certbot/certbot#1368]
I made an easy way to get the DH Parameter patched certificate updated. I put a small shell script on
https://github.com/mommel/letsencrypt-aplus
Maybe this is something for the project.

**Comment by BurakDev** [comment]
+1, Perfect :+1:

**Comment by jmhodges** [comment]
One quibble here. 

Unfortunately, validating DH parameters that are not previously specified is too expensive for clients to do. However, current attacks only work on 1024-bit RSA keys. Any similar breaks on 2048-bit RSA keys would, basically, apocalyptic across most crypto systems. (At least in a pre-quantum crypto world.)

So, the current solution for weak DH parameters is to use a cipher suite that requires 2048-bit DH.

**Comment by bmw** [comment]
If you'd like to see this in the client, you can open a pull request and we can consider it. Since this isn't really an issue though, I'm closing this.
