### ISSUE TITLE
Improve error message about bound port in standalone

### ISSUE THREAD

**Issue by pointlessone** [certbot/certbot#1370]
Hello,

This is something that I can't find answer to elsewhere so please bear with me.

I use Nginx as my webserver. When I run `letsencrypt-auto` it complains that port 80 is already taken, obviously. So have to take down Nginx, run `letsencrypt-auto` and then bring Nginx back up.

Why does `letsencrypt-auto` require port 80? Why can't it run on any other port? Requirement to take down webserver isn't clear. Granted, my server is small and doesn't have much load so I can take it down for a minute or two but this is completely unacceptable for any production system with a constant load.

**Comment by ik0** [comment]
+1
I can't stop my nginx too. It will be perfect to bind on another port !

**Comment by BurakDev** [comment]
Just use webroot plugin, example :
./letsencrypt-auto -d yourdomain.tld certonly --webroot-path "/var/www/"

replace /var/www/ with your correct webroot path, letsencrypt create http://yourdomain/.well-known/acme-challenge/randomstring file to validate it without binding the port.

**Comment by ik0** [comment]
Thanks, BurakDev. That's work !

**Comment by BurakDev** [comment]
No problem, and other way is :
./letsencrypt-auto -d yourdomain.tld certonly -a manual

You get the needed file path and the needed content on this file, btw you can use letsencrypt on a local private server :+1:

**Comment by bisho** [comment]
Can the error message be improved? Point users to the manual/webroot methods if port 80 is already used.

**Comment by BurakDev** [comment]
If you read the docs, it specify all methods (webroot, manual..)

**Comment by bmw** [comment]
Yes, our `standalone` plugin requires binding to port 80/443. This allows you to complete domain validation challenges even if you do not have a webserver. If you are currently running a server that you understandably cannot temporarily stop, `webroot` or `manual` should be used.

Perhaps this error message about the bound port should point users towards these plugins? I'm updating the title of this issue to reflect this idea.

**Comment by BurakDev** [comment]
The only improve on error message you can do is specify webroot and manual method as alternative when user trying to use standalone method.

**Comment by nkrul** [comment]
I'm using a handful of hosts aliases, and I don't believe that I should have to effectively take down a site in order to prove I own the host.
the "webroot " method doesn't work if you aren't serving content from there (proxypass for an active app), and "manual" still expects port 80.
Please include the option to specify a port when using the 'manual' mode.
And, since this *is* github :octocat: ... I'll try and submit a pull request.

**Comment by nkrul** [comment]
*sigh*.... technically the ACME spec is 80/443 only... it would be *very* nice if it could have support for different ports...

**Comment by bmw** [comment]
ietf-wg-acme/acme#4

**Comment by ohemorange** [comment]
We have an Nginx plugin now that should fix this problem, check out documentation here using the dropdown: https://certbot.eff.org/
