### ISSUE TITLE
the help message should be more explicit about the effect of the -d option

### ISSUE THREAD

**Issue by JohnDenker** [certbot/certbot#1376]
#### Hypothetical language

A suggestion, possibly mostly correct:

If the -d option is mentioned more than once on the command line, a _single_ certificate will be created to cover all the domains that were mentioned.  In particular:
- The first-mentioned domain will be the Subject CN of the certificate.
- All the domains (including the first) will be version-3 Subject Alternative Names on the certificate.
- The certificate will be stored with a filename derived from the first-mentioned domain.
#### Question

Suppose there are multiple inequivalent certificates having the same first domain but different additional domains.  There is the potential for conflict with the filename.  How is this conflict resolved?
#### Suggestion

The stated goal is to make the process easy.  To this end, it would be helpful for somebody who understands the process to document it in the help message.

**Comment by bmw** [comment]
I agree this could be more clear.

To answer your question, if there is a conflict with filenames, a number is appended to the name of the directory. For example, if you have `example.com`, the next directory will be called `example.com-0001`, followed by `example.com-0002`, etc.

**Comment by SwartzCr** [comment]
This should still be mentioned in the documentation
