### ISSUE TITLE
Python3 VirtualEnv conflicts with required Python2 VirtualEnv

### ISSUE THREAD

**Issue by Deledrius** [certbot/certbot#1377]
When running `letsencrypt-auto` using the recommended parameters on Ubuntu 14.04LTS, the script successfully installs its dependencies, but soon stops with this failure:

```
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (virtualenv 13.1.2 (/usr/local/lib/python3.4/dist-packages), Requirement.parse('virtualenv==13.2.0.dev0'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: virtualenv==13.2.0.dev0
```

I manually upgraded virtualenv with pip, but that only took it to v13.1.2 from v13.1.0, not the required 13.2.0.dev0.  Python version currently installed is 3.4.3.  I then updated the virtualenv installed for Python 2.7.6 on this system using pip2, and the script was able to complete.  It would seem that despite `letsencrypt-auto` checking Python3 by default, it is expecting to only work with Python2?

**Comment by pde** [comment]
My first attempt to reproduce this:
* Start with a fresh Ubuntu 14.04 LTS image on AWS
* Search for a python3 version of virtualenv, but there's only one package, `python-virtualenv`, which is for python2.7
* There *is* a python3-pip package, so I installed that

After those steps `./letsencrypt-auto` still worked.

@Deledrius was your python3 version of virtualenv from a PPA or some other source?  If so, which one?

**Comment by pde** [comment]
Attempt at reproducing pasted [here](https://paste.debian.net/324683/)

**Comment by Deledrius** [comment]
I don't have any PPAs in use on this system.  I believe that Py3's virtualenv was installed via pip for use with Django.

What's odd here is that the exception clearly shows it was using the Py3 installation of virtualenv, and when I upgraded that the version in the error did change to reflect it, and yet once I updated Py2's virtualenv (from v1.10.1 to 13.1.2 -- still not the version the error suggested was needed) it successfully found that and used it as expected.

**Comment by devnsec-com** [comment]
My guess for reproduce this (not tested):
* Install `pip` for python 3
* Run `python3-pip install virtualenv`, which will install `virtualenv` for python 3
* Run `letsencrypt-auto`, it will use `virtualenv` command to create a venv for Py3

**Comment by brbsix** [comment]
I believe the previous poster has assessed this correctly. Installing packages into `/usr/local/bin` via `sudo pip install PACKAGE` is generally not recommended. `pip install --user PACKAGE` to install into `~/.local/bin` is recommended in most situations. I'd guess the Python 3 version of `virtualenv` was installed to `/usr/local/bin/virtualenv` via `sudo pip3 install virtualenv` then upon updating `virtualenv` for Python 2.7.6, the script was overwritten with the Python 2 version. When creating a new environment, `virtualenv` defaults to interpreter that it was installed with. Thus upon later execution all was as expected.

**Comment by ywarnier** [comment]
I had the same problem (also on Ubuntu 14.04 LTS) and solved it doing the following as root (based on the explanations by @devnsec-com and @brbsix):
```
which virtualenv
```
(this confirmed virtualenv was installed in /usr/local/bin/virtualenv)
```
apt-get remove python-virtualenv
which virtualenv
```
(this confirmed that although it was uninstalled through Ubuntu's packaging system, the file was still there, so I did the following which is probably not a good idea if you have something else using virtualenv)
```
mv /usr/local/bin/virtualenv /tmp/
./letsencrypt-auto --help
```
Apparently, the fact that /usr/local/bin/virtualenv was not there anymore let letsencrypt re-generate virtualenv with a new environment (Python 2.7.6) and this was it... letsencrypt is installed and well.

**Comment by SwartzCr** [comment]
@yan12125 is this still true now that we support python 3?

**Comment by ywarnier** [comment]
I just tried on a fresh Ubuntu 14.04 and it seems to be working fine. Thanks!

**Comment by yan12125** [comment]
@SwartzCr: sorry, my mailbox was flooded and I missed some GitHub notifications.

I believe the problem is not directly related to Python 3 support. The actual reason appears to be that distro virtualenv packages installed by certbot-auto conflicts with pre-existing virtualenv installations. As a workaround, certbot-auto may skip installing virtualenv if there's already one in ```$PATH```.
