### ISSUE TITLE
mutliple-SAN UI for webroot

### ISSUE THREAD

**Issue by pde** [certbot/certbot#1393]
Once #1016 is done, it would need interactive UI if it is going to work for the maximum number of users.  It should call out to IDisplay once for each domain name, to figure out what the webroot is.  Ideally if the domains are `example.com` and `www.example.com` the text box for the second of them can be pre-populated with the preceding value?

**Comment by bmw** [comment]
I'm not sold on anything, but I had a few ideas for this.

In the long run I think we want to use #445 for this so we can help users input their paths correctly. We certainly don't have to block this on #445, but I think #445 provides a much nicer UI/UX.

Also, I was thinking about the following interface. For each domain, we do the following:
1. We populate a list of all webroots input so far. The first option is to input a new webroot. If no webroots have been entered, we skip this step (which I believe is automatically done by the display code if there is only one option).
2. If the user requested to enter a new webroot, we prompt for the user input one.

I think this approach minimizes typing and provides a pretty good workflow. Unfortunately, I think the pathological case is likely to occur for someone. In this case, no two domains share the same webroot. The menu is useless and provides unnecessary work for the user. Luckily, this work is only repeatedly choosing the first option, but it certainly isn't ideal.

**Comment by bmw** [comment]
This should remain a high priority, but I don't believe it is reasonable to expect this to be done by Thursday.

**Comment by pde** [comment]
Flagging this as urgent because for many people, webroot is a better answer than standalone.

**Comment by pde** [comment]
This was #2758
