### ISSUE TITLE
Worried about continuing with the client on a Mac

### ISSUE THREAD

**Issue by ericandrewlewis** [certbot/certbot#1406]
I ran the Let's Encrypt script on my Mac and got an error that has me a bit worried about continuing.

``` bash
$ ./letsencrypt-auto --agree-dev-preview --server \
→       https://acme-v01.api.letsencrypt.org/directory auth
WARNING: Mac OS X support is very experimental at present...
if you would like to work on improving it, please ensure you have backups
and then run this script again with the --debug flag!
```

What does "backups" mean in this context? Should I back up my entire hard drive, and proceed knowing that the script could mess up my entire computer?

**Comment by pde** [comment]
It means backups of any webserver configuration.  I'll update that text.

**Comment by pde** [comment]
I guess in one case we saw a FreeBSD bug report that our install scripts triggered *uninstallation* of a mailserver package.  So maybe saying you need backups is not exactly right, but we do want to ensure that people are cautious about running the experimental bootstrap scripts.

**Comment by sydneyli** [comment]
We now support MacOS. Certbot should be installed via homebrew on MacOS!
