### ISSUE TITLE
Implement HTTPS redirection only for clients that properly support it

### ISSUE THREAD

**Issue by matjon** [certbot/certbot#142]
Hello,
There are users out there that do not have fully HTTPS capable client devices (i.e. a browser that does not support TLS1.0 or Server Name Indication). Especially, default Android 2.x browser and any version of IE on Windows XP do not support SNI. What is more, users of Android 2.x usually do not have any way to upgrade to an SNI-compliant browser apart from getting a new device (as AFAIK Google Chrome requires Android 4.0 and Firefox requires much free RAM).

Some websites may still wish to support such users.

So, when the Let's encrypt client enables full HTTPS redirection, there should be some user-agent sniffing going on so that only recent browsers (those that support required HTTPS features) get full encryption. Google has been doing this since it enabled HTTPS search by default.

**Comment by riccardodivirgilio** [comment]
please not that this would not solve compatibility issue in total.
if google is indexing pages as https:// and a windows xp client lands on https there is nothing you can do because the browser will prevent any redirection to http://

**Comment by schoen** [comment]
I don't believe that this is something that EFF would likely want to implement directly in 2018, especially in the knowledge that it would leave an opening for downgrade attacks. If there are still users who are concerned about these compatibility problems and want to mitigate them this way, I'd suggest that a different project should offer a sample configuration to support this case.
