### ISSUE TITLE
prefabricated revocation request

### ISSUE THREAD

**Issue by JohnDenker** [certbot/certbot#1420]
#### Use Case / Scenario:

Suppose Joe User has set up his own web site and obtained a certificate from letsencrypt.   At some point down the road, the site gets pwned by hackers.  The first thing Joe is going to do is take down the site.  He's going to preserve the disk for forensic analysis.  It may take him a while to obtain new hardware and configure a replacement site.  Meanwhile, the bad guys are doing who-knows-what with his certificate.  Because his site is down, Joe has no way of revoking the certificate, according to the instructions given at:  https://letsencrypt.org/howitworks/technology/#certificate-issuance-and-revocation

#### Desired Behavior / Suggested Solution:

Standard good practice in the security business suggests that whenever any certificate is issued by letsencrypt, a ***revocation request*** should be issued also.  It should be contained in a file, along with instructions on how to use it.

> -----BEGIN PGP SIGNED MESSAGE-----
>  * Put this file on a thumb drive and store it in your first-aid kit, along with bandages and other things that you keep on hand but hope never to need.  (Don't leave the only copy on your server, because you might need it sometime when the server is down.)
>  * If you ever need to revoke the associated certificate, email this file to <revoke@letsencrypt.org> or upload it via the form at http://letsencrypt.org/revoke/.
>  * This revocation request is associated with your certificate www.xxx.yyy.pem issued on dd-mmm-yyyy.

#### Details:

The revocation request contains a human-readable but structured payload.  It is PGP-signed by letsencrypt.org, so we know it's authentic and nobody has any doubt about what it means.  For practical purposes the only thing that is needed is the serial number of the certificate to be revoked, but additional details improve usability and instill user confidence.  Perhaps something like this:
```
Certificate to be revoked:
    Data:
        Serial Number:
            01:4f:1d:54:f3:d7:cc:0f:6e:.....
    Signature Algorithm: sha256WithRSAEncryption
        Validity
            Not Before: Nov  5 20:05:00 2015 GMT
            Not After : Feb  3 20:05:00 2016 GMT
        Subject: CN=www.example.com
        X509v3 extensions:
            X509v3 Subject Alternative Name: 
                DNS:example.com, DNS:www.example.com
-----END PGP SIGNED MESSAGE-----
-----BEGIN PGP SIGNATURE-----
whatever
-----END PGP SIGNATURE-----
```

#### Also:

It should go without saying that the documentation should be updated to highlight this feature and explain how to use it.

**Comment by bmw** [comment]
This request is outside of the scope of the client. If you'd still like to see this feature added, feel free to open up an issue/pull request at https://github.com/ietf-wg-acme/acme.
