### ISSUE TITLE
-vvvv should imply --text

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#1430]
Running with -vvvv results in a series of ncurses windows that get filled with rapidly scrolling text. I think -vvvv should imply --text, or it should provide the output in a log or some other readable method.

**Comment by bmw** [comment]
Everything that is shown with `-vv` is written to a log in the logs directory whether or not `-vv` is included on the command line. I agree that the rapidly scrolling text in `dialog` has little/no value though.

**Comment by bmw** [comment]
#2674 is a duplicate of this and while this issue came first, the other has more thorough discussion so I'm closing this one.
