### ISSUE TITLE
Warn when multiple IP addresses for a requested name

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#1431]
Right now, Boulder will attempt validation of just one of the IP addresses in DNS. It would be helpful if the client did a lookup and warned the user that it can't guarantee success if there are multiple IP addresses for a given name.

**Comment by bmw** [comment]
Related #360.

**Comment by jsha** [comment]
I think we probably won't do this; I don't see a lot of reports of people having trouble with this problem.
