### ISSUE TITLE
Installer should only select domains covered by the cert

### ISSUE THREAD

**Issue by nils-ohlmeier** [certbot/certbot#1433]
After getting my first cert I used the installer to install the cert into my Apache configuration. When requesting the certificate I only requests a cert for www.MYDOMAIN.com.

When I ran this command:

`./letsencrypt-auto install --cert-path /etc/letsencrypt/live/www.MYDOMAIN.com/fullchain.pem --key-path /etc/letsencrypt/live/www.MYDOMAIN.com/privkey.pem`

the installer offered me 5 hosts to install the cert for, including just the IP address and MYDOMAIN.com and all of them were selected.
I think it's great that the installer figured out all the host names of my server. But offering host names which are not covered by the cert is actually asking for trouble. I think the installer should look into the cert and select only the host names which are included in the cert.

**Comment by pde** [comment]
Related: #1231

**Comment by schoen** [comment]
Our installers are a lot more sophisticated now than when this issue was filed in 2015, although their behavior isn't perfect. Could @nils-ohlmeier or anyone else confirm whether the current behavior is still a problem and whether it ought to be improved in a particular respect?

**Comment by bmw** [comment]
This issue hasn't seen an update in almost a year so I'm going to close this for now. If the problem persists, please comment here or open a new issue.
