### ISSUE TITLE
Include IP address which backend tried to connect to

### ISSUE THREAD

**Issue by nils-ohlmeier** [certbot/certbot#1434]
Shortly before requesting my first certificate I moved the domain to a different host. This resulted in the auto client failing with a generic error message that the authorization failed.

I had to run tcpdump on the old and the new server to figure out that the reason why the authorization failed was because the LE backend kept trying to connect to the old IP address.

Obviously it is not a good idea to change IP address before questing certificates, but I think it could save some users hours of debugging if the authorization error message would include the IP and port number the LE backend tried to connect to.

**Comment by nils-ohlmeier** [comment]
I think I pretty clearly stated that I got into this problem, because I changed DNS information. So yes it was an administrative error.

My request/suggestion was about improving the error message from the LE backend to the client. And maybe the client is not the right area to request this, but then I would appreciate it to get pointed to the suitable component rather then closing old, stale tickets, because nobody worked or even looked at them.

**Comment by joohoi** [comment]
Ah, I'm sorry. Unfortunately we don't have the information on the client side.

I think the correct place to propose such change would be the [acme spec](https://tools.ietf.org/html/draft-ietf-acme-acme-07) the github repository can be found at https://github.com/ietf-wg-acme/acme

The server side software of Let's Encrypt is hosted at https://github.com/letsencrypt/boulder

**Comment by cpu** [comment]
We could update the `urn:acme:error:connection` problem that Boulder is returning to also include the address in the "Connection refused" message but there is also sufficient information in the valid/invalid authz after POSTing a challenge to say where the connection was made (for HTTP-01 and TLS-SNI-01 challenges anyway) client-side.

The challenge that was POSTed will have a populated `validationRecord` which contains the IP address that was contacted immediately prior to the authz being set invalid (or valid if the challenge succeeded) as the `addressUsed` field:

```
<snip>
    {
      "type": "tls-sni-01",
      "status": "invalid",
      "error": {
        "type": "urn:acme:error:connection",
        "detail": "Connection refused",
        "status": 400
      },
      "uri": "http://localhost:4000/acme/challenge/1wyQnI3wNfmHgk0dJduU9vR79n8a2yQPKBuAXpAaLmM/788",
      "token": "gAzImcXtXZJB5naUqGmvC6pTMT58htFJwn64S-WPwFk",
      "keyAuthorization": "gAzImcXtXZJB5naUqGmvC6pTMT58htFJwn64S-WPwFk.J30itYNXOSDiZLg55hMbl1iqDnvw66sa8LGaNftbbp4",
      "validationRecord": [
        {
          "hostname": "www.example.com",
          "port": "5001",
          "addressesResolved": [
            "127.0.0.1"
          ],
          "addressUsed": "127.0.0.1",
          "addressesTried": []
        }
      ]
    },
<snip>
```

I pulled the above out of a Certbot run with `--debug` and `--vv` set, so in the short term it seems like running Certbot with these flags will give you enough information to know which IP address was contacted by the VA.

**Comment by joohoi** [comment]
I stand corrected, awesome! Reopening the issue.

**Comment by joohoi** [comment]
Adding the information to UI would also help people that have a broken AAAA records in place and are not aware of Let's Encrypt preferring IPv6. This is unfortunately still somewhat common.
