### ISSUE TITLE
Installer plugin documentation is lacking/confusing

### ISSUE THREAD

**Issue by sesse** [certbot/certbot#1435]
Hi,

I'm trying to write an installer plugin. The IInstaller interface has lots of different functions that I seemingly need to override, but the documentation is very unclear about the larger picture. In normal use, I can only see prepare, deploy_cert, save and restart be called; however, there are lots of others, including get_all_names (which is hard for me to find without opening and parsing the actual certificates) and then lots of rollback/recovery stuff which somehow may or may not integrate with a “reverter” module. I _think_ some of the rollback stuff is called if I throw an exception from any of the others, but exactly when a checkpoint is set (I can be asked to rollback N checkpoints, so it would be good to know when I am expected to take a checkpoint) or how all of this is used is unclear.

It looks like somehow the installer interface might also be used for authentication via DVSNI. If that's a correct guess (so it means installers overlap with authenticators wrt. purpose), perhaps it should be split out from the much simpler concept of just deploying an existing certificate authenticated by another module?

Thanks!

**Comment by pde** [comment]
Yes! 

`get_all_names` is simple: it's used if the user doesn't specify any domains, to pre-populate the domains they might want to obtain a cert for.  Conceptually easy to determine in apache or nginx. But in some servers this is an unanswerable question, so we should specify what to return in that case.

As for the reverter functions: those are called during exceptions and also if the user runs `letsencrypt rollback`.  We'll need someone to go through one of the existing implementations (apache is more mature, nginx is simpler) and write up when where & why those are called.

**Comment by boldandbusted** [comment]
Howdy. Is this still an issue, or have the docs improved enough to address it since? Cheers.

**Comment by SwartzCr** [comment]
closing this in favor of #3225
