### ISSUE TITLE
Pip install failure on Ubuntu 14.04

### ISSUE THREAD

**Issue by dnw3039** [certbot/certbot#1469]
## Console message:

"dnw@capulet:/test/letsencrypt$ ./letsencrypt-auto --verbose
Updating letsencrypt and virtual environment dependencies...
/home/dnw/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.

....................
 Could not find a version that satisfies the requirement letsencrypt (from versions: )
## No matching distribution found for letsencrypt"

on Ubuntu 14.04, I have upgraded python to 2.7.9 I am using todays clone of letsencrypt.

I have spend several hours on this. I have tried all the suggested fixes for this problem I could find such as:

 pip install pyopenssl ndg-httpsclient pyasn1
apt-get install libffi-dev libssl-dev
pip install requests[security]
pip install pyOpenSSL

I have compiled and installed the latest pyOpenSSL 0.15.1

Nothing I have tried has changed the error messages.

**Comment by pde** [comment]
InsecurePlatformWarning, though it looks scary, is definitely not the problem here.

**Comment by pde** [comment]
What's the output of `pip --version`?

**Comment by dnw3039** [comment]
pip --version
pip 1.5.4 from
/usr/local/lib/python2.7.9/lib/python2.7/site-packages/pip-1.5.4-py2.7.egg
(python 2.7)

**Comment by kuba** [comment]
Suggestion to run `pip --version` is utterly confusing, because we use `~/.local/share/letsencrypt/bin/pip` instead...

**Comment by dnw3039** [comment]
kuba, Thanks, yes that was the the problem ~/.local/share/letsencrypt/bin/pip was a different version of pip. I have corrected that.

I now do not get any warnings. But any command only produces the output:

"Updating letsencrypt and virtual environment dependencies...."

and nothing else

for example:

 ./letsencrypt-auto certonly -a manual -d igking.info \
>  --server https://acme-v01.api.letsencrypt.org/directory --agree-dev-preview
Updating letsencrypt and virtual environment dependencies.....

**Comment by kuba** [comment]
You should NOT use `pip` yourself :( It's an implementation detail of `letsencrypt-auto`. I'm not sure what you actually did, because you did not follow official installation instructions, which explicitly ask not to do any `pip install`: https://letsencrypt.readthedocs.org/en/latest/using.html#from-source.

Please `rm -rf ~/.local/share/letsencrypt`, run `letsencrypt-auto -vvvv plugins`, and paste the **entire** output over here.

**Comment by dnw3039** [comment]
I realised that I had messed up Python on my system and have installed
Python 2.7.10
pip is 1.5.4

I have deleted ~/.local/share/letsencrypt

and tried for a fresh rebuild. I get the error:

*Collecting letsencrypt*
*  Could not find a version that satisfies the requirement letsencrypt
(from versions: )*
*No matching distribution found for letsencrypt*

Here is the full console trace:

 ./letsencrypt-auto -vvvv
-vvvv
Bootstrapping dependencies for Debian-based OSes...
Ign http://mirror.aarnet.edu.au trusty InRelease
Hit http://mirror.aarnet.edu.au trusty-updates InRelease

Hit http://mirror.aarnet.edu.au trusty-backports InRelease

Ign http://dl.google.com stable InRelease

Hit http://mirror.aarnet.edu.au trusty-security InRelease

Hit http://mirror.aarnet.edu.au trusty Release.gpg

Hit http://mirror.aarnet.edu.au trusty-updates/main Sources

Hit http://mirror.aarnet.edu.au trusty-updates/restricted Sources

Hit http://mirror.aarnet.edu.au trusty-updates/universe Sources

Ign http://dl.google.com stable InRelease

Hit http://mirror.aarnet.edu.au trusty-updates/multiverse Sources

Hit http://mirror.aarnet.edu.au trusty-updates/main amd64 Packages

Hit http://mirror.aarnet.edu.au trusty-updates/restricted amd64 Packages

Ign http://archive.canonical.com trusty InRelease

Ign http://ppa.launchpad.net trusty InRelease

Hit http://mirror.aarnet.edu.au trusty-updates/universe amd64 Packages

Ign http://extras.ubuntu.com trusty InRelease

Hit http://mirror.aarnet.edu.au trusty-updates/multiverse amd64 Packages

Hit http://mirror.aarnet.edu.au trusty-updates/main i386 Packages

Get:1 https://apt.dockerproject.org ubuntu-trusty InRelease

Ign https://apt.dockerproject.org ubuntu-trusty InRelease

Ign http://dl.google.com stable InRelease

Hit http://mirror.aarnet.edu.au trusty-updates/restricted i386 Packages

Hit https://apt.dockerproject.org ubuntu-trusty Release.gpg

Hit http://mirror.aarnet.edu.au trusty-updates/universe i386 Packages

Hit https://apt.dockerproject.org ubuntu-trusty Release

Hit https://apt.dockerproject.org ubuntu-trusty/main amd64 Packages

Hit http://mirror.aarnet.edu.au trusty-updates/multiverse i386 Packages

Ign http://download.opensuse.org  InRelease

Hit https://apt.dockerproject.org ubuntu-trusty/main i386 Packages

Hit http://archive.canonical.com trusty Release.gpg

Hit http://ppa.launchpad.net trusty InRelease

Hit http://extras.ubuntu.com trusty Release.gpg

Hit http://mirror.aarnet.edu.au trusty-updates/main Translation-en

Hit http://mirror.aarnet.edu.au trusty-updates/multiverse Translation-en

Hit http://dl.google.com stable Release.gpg

Hit http://mirror.aarnet.edu.au trusty-updates/restricted Translation-en

Hit http://mirror.aarnet.edu.au trusty-updates/universe Translation-en

Get:2 https://apt.dockerproject.org ubuntu-trusty/main Translation-en_AU

Hit http://mirror.aarnet.edu.au trusty-backports/main Sources

Hit http://archive.canonical.com trusty Release

Hit http://mirror.aarnet.edu.au trusty-backports/restricted Sources

Hit http://ppa.launchpad.net trusty InRelease

Ign http://download.opensuse.org  Release.gpg

Hit http://mirror.aarnet.edu.au trusty-backports/universe Sources

Hit http://extras.ubuntu.com trusty Release

Hit http://mirror.aarnet.edu.au trusty-backports/multiverse Sources

Hit http://dl.google.com stable Release.gpg

Hit http://mirror.aarnet.edu.au trusty-backports/main amd64 Packages

Hit http://mirror.aarnet.edu.au trusty-backports/restricted amd64 Packages

Hit http://archive.canonical.com trusty/partner amd64 Packages

Hit http://ppa.launchpad.net trusty Release.gpg

Hit http://mirror.aarnet.edu.au trusty-backports/universe amd64 Packages

Ign http://download.opensuse.org  Release

Hit http://extras.ubuntu.com trusty/main Sources

Hit http://dl.google.com stable Release.gpg

Hit http://mirror.aarnet.edu.au trusty-backports/multiverse amd64 Packages

Hit http://mirror.aarnet.edu.au trusty-backports/main i386 Packages

Hit http://mirror.aarnet.edu.au trusty-backports/restricted i386 Packages

Hit http://mirror.aarnet.edu.au trusty-backports/universe i386 Packages

Hit http://archive.canonical.com trusty/partner i386 Packages

Hit http://mirror.aarnet.edu.au trusty-backports/multiverse i386 Packages

Hit http://ppa.launchpad.net trusty/main amd64 Packages

Hit http://mirror.aarnet.edu.au trusty-backports/main Translation-en

Hit http://dl.google.com stable Release

Hit http://extras.ubuntu.com trusty/main amd64 Packages

Ign http://download.opensuse.org  Packages/DiffIndex

Hit http://mirror.aarnet.edu.au trusty-backports/multiverse Translation-en

Hit http://mirror.aarnet.edu.au trusty-backports/restricted Translation-en

Hit http://mirror.aarnet.edu.au trusty-backports/universe Translation-en

Hit http://mirror.aarnet.edu.au trusty-security/main Sources

Hit http://ppa.launchpad.net trusty/main i386 Packages

Hit http://dl.google.com stable Release

Hit http://mirror.aarnet.edu.au trusty-security/restricted Sources

Hit http://mirror.aarnet.edu.au trusty-security/universe Sources

Hit http://extras.ubuntu.com trusty/main i386 Packages

Hit http://mirror.aarnet.edu.au trusty-security/multiverse Sources

Hit http://dl.google.com stable Release

Hit http://mirror.aarnet.edu.au trusty-security/main amd64 Packages

Hit http://mirror.aarnet.edu.au trusty-security/restricted amd64 Packages

Hit http://mirror.aarnet.edu.au trusty-security/universe amd64 Packages

Hit http://ppa.launchpad.net trusty/main Translation-en

Hit http://dl.google.com stable/main amd64 Packages

Hit http://mirror.aarnet.edu.au trusty-security/multiverse amd64 Packages

Hit http://mirror.aarnet.edu.au trusty-security/main i386 Packages

Hit http://dl.google.com stable/main i386 Packages

Hit http://mirror.aarnet.edu.au trusty-security/restricted i386 Packages

Hit http://mirror.aarnet.edu.au trusty-security/universe i386 Packages

Ign http://archive.canonical.com trusty/partner Translation-en

Hit http://mirror.aarnet.edu.au trusty-security/multiverse i386 Packages

Hit http://ppa.launchpad.net trusty/main amd64 Packages

Hit http://mirror.aarnet.edu.au trusty-security/main Translation-en

Hit http://mirror.aarnet.edu.au trusty-security/multiverse Translation-en

Hit http://mirror.aarnet.edu.au trusty-security/restricted Translation-en

Hit http://mirror.aarnet.edu.au trusty-security/universe Translation-en

Hit http://mirror.aarnet.edu.au trusty Release

Hit http://ppa.launchpad.net trusty/main i386 Packages

Hit http://mirror.aarnet.edu.au trusty/main Sources

Hit http://dl.google.com stable/main amd64 Packages

Hit http://mirror.aarnet.edu.au trusty/restricted Sources

Hit http://mirror.aarnet.edu.au trusty/universe Sources

Hit http://mirror.aarnet.edu.au trusty/multiverse Sources

Hit http://dl.google.com stable/main i386 Packages

Hit http://mirror.aarnet.edu.au trusty/main amd64 Packages

Hit http://mirror.aarnet.edu.au trusty/restricted amd64 Packages

Hit http://mirror.aarnet.edu.au trusty/universe amd64 Packages

Hit http://ppa.launchpad.net trusty/main Translation-en

Hit http://mirror.aarnet.edu.au trusty/multiverse amd64 Packages

Hit http://mirror.aarnet.edu.au trusty/main i386 Packages

Hit http://mirror.aarnet.edu.au trusty/restricted i386 Packages

Hit http://mirror.aarnet.edu.au trusty/universe i386 Packages

Hit http://mirror.aarnet.edu.au trusty/multiverse i386 Packages

Hit http://mirror.aarnet.edu.au trusty/main Translation-en_AU

Hit http://ppa.launchpad.net trusty Release

Hit http://mirror.aarnet.edu.au trusty/main Translation-en

Hit http://dl.google.com stable/main amd64 Packages

Hit http://mirror.aarnet.edu.au trusty/multiverse Translation-en_AU

Hit http://mirror.aarnet.edu.au trusty/multiverse Translation-en

Hit http://dl.google.com stable/main i386 Packages

Hit http://mirror.aarnet.edu.au trusty/restricted Translation-en_AU

Hit http://mirror.aarnet.edu.au trusty/restricted Translation-en

Hit http://ppa.launchpad.net trusty/main amd64 Packages

Hit http://mirror.aarnet.edu.au trusty/universe Translation-en_AU

Hit http://mirror.aarnet.edu.au trusty/universe Translation-en

Hit http://ppa.launchpad.net trusty/main i386 Packages

Hit http://ppa.launchpad.net trusty/main Translation-en

Ign https://apt.dockerproject.org ubuntu-trusty/main Translation-en_AU

Ign http://extras.ubuntu.com trusty/main Translation-en_AU

Ign https://apt.dockerproject.org ubuntu-trusty/main Translation-en

Ign http://extras.ubuntu.com trusty/main Translation-en

Ign http://download.opensuse.org  Translation-en_AU

Ign http://download.opensuse.org  Translation-en

Err http://download.opensuse.org  Packages

  404  Not Found [IP: 195.135.221.134 80]
Ign http://dl.google.com stable/main Translation-en_AU

Ign http://dl.google.com stable/main Translation-en

Ign http://dl.google.com stable/main Translation-en_AU

Ign http://dl.google.com stable/main Translation-en

Ign http://dl.google.com stable/main Translation-en_AU

Ign http://dl.google.com stable/main Translation-en

W: Failed to fetch
http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/xUbuntu_14.10/Packages
 404  Not Found [IP: 195.135.221.134 80]

E: Some index files failed to download. They have been ignored, or old ones
used instead.
E: No package found
Reading package lists... Done
Building dependency tree
Reading state information... Done
dialog is already the newest version.
gcc is already the newest version.
libffi-dev is already the newest version.
python is already the newest version.
python-dev is already the newest version.
python-virtualenv is already the newest version.
ca-certificates is already the newest version.
git is already the newest version.
libaugeas0 is already the newest version.
libssl-dev is already the newest version.
0 to upgrade, 0 to newly install, 0 to remove and 12 not to upgrade.
Creating virtual environment...
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/dnw/.local/share/letsencrypt/bin/python2
Also creating executable in /home/dnw/.local/share/letsencrypt/bin/python
Installing setuptools, pip, wheel...done.
Updating letsencrypt and virtual environment dependencies...
Requirement already up-to-date: setuptools in
/home/dnw/.local/share/letsencrypt/lib/python2.7/site-packages
Requirement already up-to-date: pip in
/home/dnw/.local/share/letsencrypt/lib/python2.7/site-packages
Collecting letsencrypt
  Could not find a version that satisfies the requirement letsencrypt (from
versions: )
No matching distribution found for letsencrypt

**Comment by thuandt** [comment]
I faced same problem when install letsencrypt in Debian Wheezy

**Comment by dnw3039** [comment]
I gave up on Unbutu 14.04 and upgraded to 15.10 and it all worked.

**Comment by DenisMir** [comment]
I have got the same error on Ubuntu 14.04. I have followed the instructions sent to me in the email in the beta program. No chance. It does not work with the 14.04 LTS.

**Comment by hadim** [comment]
`sudo pip install -U pip` should do it !

**Comment by KeiroD** [comment]
Had this issue myself, was able to correct by installing `python-pip`. Now to wait for my account to be approved... I actually just wanted to test automating `./letsencrypt-auto` for a couple of my systems... but fortunately, I see it uses the staging server for that.

**Comment by thuandt** [comment]
@hadim @KeiroD `pip` package in my system is latest version in PyPi, but it's don't work.

Should I use `pip` provider by distro?

**Comment by erikrose** [comment]
pip 1.4 and later doesn't install prelease versions of packages by default. From the pip changelog...

    **1.4 (2013-07-23)**

    * **BACKWARD INCOMPATIBLE** pip now only installs stable versions by default,
      and offers a new ``--pre`` option to also find pre-release and development
      versions. (:pull:`834`)

Our version string, "0.0.0.dev20151114", doesn't conform to PEP 440 and is thus parsed as a prerelease (which it is anyway, so there's no rush to fix that). If we want letsencrypt-auto to work for dev releases, we'll need to add --pre to the "pip install" command.

**Comment by KeiroD** [comment]
@thuandt Ahh... don't know. But installing `python-pip` via `apt-get install` then running `./letsencrypt-auto` did the trick for me. I guess you could try it that way without installing anything else but `python-pip` and see what happens?

**Comment by bmw** [comment]
@erikrose, but shouldn't this problem be resolved by running `pip install -U pip` in the virtualenv? This is done by `letsencrypt-auto`.

**Comment by erikrose** [comment]
@bmw Quite the opposite, unfortunately. It's the *newer* pips that won't install dev versions without the --pre flag.

**Comment by bmw** [comment]
Ah! I should read more closely. It appears the opposite conclusion was made [here](https://github.com/letsencrypt/letsencrypt/issues/1064#issuecomment-149965190). Looking at the `pip` documentation, I can see that you are right though.

With this in mind, should we add `--pre` to `letsencrypt-auto` while we continue to do dev releases? I'm not sure how `letsencrypt-auto` has worked so well when it always updates `pip` before installing any Let's Encrypt packages...

**Comment by erikrose** [comment]
Yes, +1 for --pre for now. I'm not sure how it's worked thus far either.

**Comment by jeyemwey** [comment]
@DenisMir Do you have any updated information regarding Let's Encrypt on 14.04? I am somehow scared of updating my system because I am very happy with it.. :confused:

**Comment by dnw3039** [comment]
Jannik,

I have upraded to Ubuntu 15:10 with no problems. Sorry I have no more
information about Encrypt on 14:04 but what I have see suggests that it
either very difficult or impossiable.


Regards.

David

**Comment by jeyemwey** [comment]
David, thank you for your message. It looks like I've got attack the
upgrade during the holidays :)

Am 20.12.2015 um 21:49 schrieb David:
> Jannik,
>
> I have upraded to Ubuntu 15:10 with no problems. Sorry I have no more
> information about Encrypt on 14:04 but what I have see suggests that it
> either very difficult or impossiable.
>
>
> Regards.
>
> David
>

**Comment by thuandt** [comment]
Any updates? I still can't install latest `letsencrypt` in Debian wheezy

**Comment by erikrose** [comment]
I don't have any updates on the specific problem you encountered, but I will say that an upcoming version of letsencrypt-auto, to be released shortly after 0.2.0, will be tested against wheezy. In fact, that's what I'm working on today. I'll be very interested if that doesn't work for you.

**Comment by bmw** [comment]
It looks like the issue here was pre-release and development versions of letsencrypt/Certbot. Since we've been releasing stable versions for years now and we haven't seen any new comments here, I'm closing this issue.
