### ISSUE TITLE
unable to set up for Google App Engine

### ISSUE THREAD

**Issue by arkarkark** [certbot/certbot#1480]
I'm trying to generate an SSL cert to add to Google App Engine. I'll admit to not having a clue about what I'm doing.

I'm following instructions from [here](https://cloud.google.com/appengine/docs/using-custom-domains-and-ssl?hl=en#adding_ssl_to_your_custom_domain) which send me to this [console](https://console.developers.google.com/project/_/appengine/settings/certificates)

It's asking for this:
![image](https://cloud.githubusercontent.com/assets/877895/11127752/aa33b810-892a-11e5-852a-fe0d73b8b9fc.png)

when I run `./letsencrypt-auto certonly` and enter `wtwf.com` for the domain I get back

```
Failed authorization procedure. wtwf.com (tls-sni-01): connection :: The server could not connect to the client for DV :: Failed to connect to host for DVSNI challenge
```

from what I gather from https://github.com/letsencrypt/acme-spec/issues/19 it's trying to connect on port 443 to verify the domain (but I doubt that'll work until I have it set up, catch22?)

I also tried `./letsencrypt-auto -d wtwf.com certonly` and even added in a `-d www.wtwf.com` too

running  `./letsencrypt-auto certonly` and typing `www.wtwf.com` gets me a `Error creating new authz`

I'm running all this on an El Capitan Mac I've run `./bootstrap/mac.sh`

in `/etc/letsencrypt` I have lots of `.pem` files under `csr/` and `keys/`

**Comment by dgrilli** [comment]
I think the only way you can obtain a certificate for the app engine is with the manual plugin in this way:

./letsencrypt-auto -t -a manual -d yourdomain.com auth

It will use the "file" challenge so it will show you a text string to put in a file. 
Before press enter you have to create this file and upload it in your app engine and you have to be sure that app engine knows this is a static file in text/plain mime type.

An easy way could be to add this to your app.yaml file:

- url: /\.well-known/acme-challenge/(.+)
  static_files: wordpress/.well-known/acme-challenge/\1
  mime_type: text/plain
  upload: wordpress/.well-known/acme-challenge/.*
  application_readable: true

Then you can press enter a letsencrypt should be able to check the challenge.
When finish you should have your certificate in your pc: in linux is in /etc/letsencrpyt/live/ folder. I am not sure where in MacOsX.

Before to be able to upload the script on the google cloud console you also need to convert the private key in RSA. I can do that with this command:

openssl rsa -in privkey.pem -out privkeyRSA.pem

Now you are ready to upload cert and privatekey and enable https in your app engine.

I am not sure about the renew: I have not tried yet.

**Comment by dgrilli** [comment]
Ah, I forgot:

when you upload the certificate in google cloud console you have to import the fullchain.pem

**Comment by SebastianBoyd** [comment]
It would be nice if this could be somehow integrated into the app engine console, but google would have to do that.

**Comment by pde** [comment]
Really it should be Google that does this work, but in the mean time the most realistic option is a whole separate ACME client that's designed to pass HTTP01 challenges on App Engine for you.

**Comment by pde** [comment]
Though maybe it could actually make sense to make this an authenticator and installer plugin for the Python client...

**Comment by ping** [comment]
I was able to generate and install the LE cert for GAE via the manual plugin. 
OSX Mavericks

1. Generate private key and csr
	```
	$ openssl req -newkey rsa:2048 -keyout example.com.private.key -nodes -sha512 -subj "/CN=example.com" -reqexts SAN -out example.com.csr.der -outform der -config <(cat /System/Library/OpenSSL/openssl.cnf <(printf "[SAN]\nsubjectAltName=DNS:example.com,DNS:www.example.com"))
	```

2. Two files should be generated: ``example.com.private.key`` and ``example.com.csr.der``

3. Run ./letencrypt-auto
	```
	./letsencrypt-auto certonly -a manual --server https://acme-v01.api.letsencrypt.org/directory --agree-dev-preview --csr example.com.csr.der
	```

4. Depending on your app, you will need to make changes to generate the verification text response as prompted. If you're generating the cert for both www. and the naked domain, you will be challenged twice with 2 different texts.

5. When the certificate and chain files are successfully generated, go to https://console.developers.google.com/project/_/appengine/settings/certificates and choose "Upload a new certificate".

6. For "Unencrypted PEM encoded RSA private key", upload ``example.com.private.key``
   For "PEM encoded X.509 public key certificate", upload ``0001_chain.pem``

7. Proceed as the app engine console instructs. If all goes well, you will be given the choice to enable the uploaded SSL cert for your domain.

**Comment by jscissr** [comment]
The appengine issue is here: https://code.google.com/p/googleappengine/issues/detail?id=12535 It looks like Google will work on it :smile: :+1:

**Comment by duanev** [comment]
I'm just serving simple static pages in Google Cloud with no launched "app" or software packages but setting up the app.yaml was a royal PITA.  With the help from above (thanks dgrilli!), here's what I finally got to work.  (ps. I'm on Arch Linux and there is a package for letsencrypt so `pacman -S letsencrypt` installs the tools and letsencrypt-auto is not needed)

1. (you must be root)  # letsencrypt certonly --manual <your_domain>

2. Accept "log my IP"

3. A challenge url and text will be printed.  Open a different terminal and leave this one waiting.  Add a file in your google cloud project's root directory (where the app.yaml file is found) like `acme.txt` and place the challenge text inside followed by a newline.

4. Add an entry in your app.yaml at the top of `handlers:` like the one described below.

5. (assuming you have done `gcloud auth login`) `git add app.yaml acme.txt` , `git commit -m cert` , `git push -u origin master`

6. `cd ..; gcloud preview app deploy default/app.yaml`

7. Test the challenge url in a browser, the challenge text should appear in the main browser window.

8. Press Enter in the terminal running the letsencrypt command, it should complete and generate the fullchain.pem file.

9. Change a terminal current directory to a place where your browser can upload files and run `# openssl rsa -in /etc/letsencrypt/keys/XXXX_key-letsencrypt.pem -out privkey-rsa.pem` where XXXX is the latest version.  (`pacman -S openssl` will install this tool)

10. Copy `/etc/letsencrypt/live/<your_domain>/fullchain.pem` to the current directory.

11. Using Google Cloud Console got to:  Menu -> App Engine -> Settings -> SSL Certificates -> Upload and fill in the form.

12. Delete the .pem files in the current directory to mitigate unexpected propagation ...




(and here is the app.yaml insert - markdown won't let me inline this)
```yaml
 - url: /.well-known/acme-challenge/IdJh2tPenuHk5NUns2uaS9AXooLuTl_fHzSbxxxXXXxx
   static_files: acme.txt
   mime_type: text/plain
   upload: acme.txt
```

**Comment by walkr** [comment]
@duanev Thank you! It worked for me. 👍🏽

**Comment by GeekLad** [comment]
I was able to do configure the `app.yaml` by just creating a static directory:

```yaml
- url: /.well-known/acme-challenge
  static_dir: acme-challenge
  mime_type: text/plain
```

I just created files in a directory called `acme-challenge`, with the appropriate filenames and contents.

When I ran the `letsencrypt` command, I wanted to verify the root domain as well as the www subdomain.  Using a static_dir made it easier to deal with the multiple files since I only needed to edit the `app.yaml` once.

**Comment by bmw** [comment]
While not trivial, it appears that users have figured out how to use Certbot with Google App engine so I'm closing this issue. Post a comment yelling at me if you'd like me to reconsider.

**Comment by arkarkark** [comment]
All the replies here really helped thanks. I ended up forking letsencrypt-nosudo and writing a teeny handler that would accept well known facts (password protected) and managed to automate almost all the process.

You can see the results here
https://github.com/arkarkark/letsencrypt-nosudo

When the cert signer needs well known facts to be served, it posts them to your app engine (no need to keep deploying for each hostname to serve from). Right now I'm putting the result in `pbcopy` so I can just paste it into the [google cloud ssl cert page](https://console.cloud.google.com/appengine/settings/certificates). Hopefully sometime there'll be an api (or `gcloud` command) for that or even just [full gcloud/appengine integration](https://code.google.com/p/googleappengine/issues/detail?id=12535).
