### ISSUE TITLE
Allow cert creation with specified key

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#1491]
Users should be able to specify a key on the command line when creating a certificate. The public key should be stored in the created certificate.

**Comment by schoen** [comment]
If we do allow the use of an existing key, we should be careful to check that none of the sanity checks or logic in `storage.py` interfere with this (for example, because `archive` will then contain a symlink, where previously only `live` contained symlinks!).

**Comment by jsha** [comment]
This is implemented in https://github.com/certbot/certbot/pull/3819.

**Comment by bmw** [comment]
You can use your own key with `--csr` with downsides tracked by other issues like https://github.com/certbot/certbot/issues/3690.

I personally haven't seen any external requests for this feature so until we do, I think we should close this issue.
