### ISSUE TITLE
Thoughts on RPM builds? 

### ISSUE THREAD

**Issue by willnewby** [certbot/certbot#15]
Are there already plans for packaging this as an RPM for easy installation?

If so, great! How can I help?

If not, I'd like to volunteer to build them. 

Either way, I'd like to help out in any way that I can.

**Comment by AaronNGray** [comment]
Looks like it builds properly on Fedora. I built it last night on my main server and noticed the word "error" flashing by but they were not errors, so erroniously thought there were errors despite the "success !" message. Theres quite a few warning though, but they look safe.

Documented here :-

    https://github.com/AaronNGray/lets-encrypt-preview/blob/fedora/debug/out

**Comment by lhaig** [comment]
On 25/02/2015 17:24, AaronNGray wrote:
>
> Looks like it builds properly on Fedora. I built it last night on my 
> main server and noticed the word "error" flashing by but they were not 
> errors, so erroniously thought there were errors despite the "success 
> !" message. Theres quite a few warning though, but they look safe.
>
> Documented here :-
>
> |https://github.com/AaronNGray/lets-encrypt-preview/blob/fedora/debug/out
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/letsencrypt/lets-encrypt-preview/issues/15#issuecomment-75979327>.
>
Hi,

do you have a spec file to share yet?

Regards

Lance

**Comment by AaronNGray** [comment]
No. I have only compiled from source using :-

http://www.aarongray.org/letsencrypt/letsencrypt.html

**Comment by lhaig** [comment]
Hi All,

I have quickly this morning created these packages 

https://build.opensuse.org/package/show/home:lhaig/letsencrypt-preview

Can you guys test please and tell me if anything is not working

Thanks

Lance

**Comment by lhaig** [comment]
Hi have just finished the Debian based builds as well. They all need testing.
https://build.opensuse.org/package/show/home:lhaig/letsencrypt-preview

**Comment by danimo** [comment]
@lhaig what happened to your OBS package?

**Comment by lhaig** [comment]
I removed the packages as it seemed that they were not necessary as I found out in the IRC channel

**Comment by danimo** [comment]
@lhaig can you elaborate why that is? what are the alternatives?

**Comment by lhaig** [comment]
In a discussion with someone on the IRC channel I was told only debian was supported and the OBS packages were not needed. So I did not waste any more time on them. I will upload what I have now into my OBS account and if anyone is interested they can find the files there

**Comment by lhaig** [comment]
I will leave the Debian based builds out of the account

**Comment by tdfischer** [comment]
Hi, all.

I've created this packaging bug against Fedora for tracking EPEL/Fedora packaging:

https://bugzilla.redhat.com/show_bug.cgi?id=1215478

A sample package for Fedora 22 is available here:

https://copr.fedoraproject.org/coprs/tdfischer/lets-encrypt/

And here's a mailing list thread for some other information:

https://groups.google.com/a/letsencrypt.org/forum/#!topic/client-dev/ZQ_hnSxxQYE

**Comment by NoodlesNZ** [comment]
@tdfischer Any luck getting the package picked up by fedora? I don't mind looking after EPEL 6/7, but can't see it in package db (I'm not familiar with COPR).

**Comment by FelixSchwarz** [comment]
@NoodlesNZ the package is not in Fedora yet because the packaging is not (yet) up to Fedora's standards (check the Red Hat bugzilla link for details) and it seems that reviewers are waiting for a response from @tdfischer for some time now. All packages in Fedora must pass the review to minimize the amount of errors (i.e. "you should be able to run the application after installing the rpm"). As far as I can see the spotted problems are pretty simple but need to be fixed before acceptance.

One danger I see here is that if @tdfischer lost interest/time other potential packagers might not take the package because they might get the impression that "someone else" is already doing it.

**Comment by sparksis** [comment]
@tdfischer Are you able to setup copr for an epel (7) release?  I've seen quite a few RPMs on copr with both Fedora and EPEL releases and it would be beneficial to have it available for centos.

**Comment by NoodlesNZ** [comment]
It looks to be in review (https://bugzilla.redhat.com/show_bug.cgi?id=1215478). Once the package is in Fedora then we can create EPEL packages, but at the moment it looks like we're short a couple of python dependencies (at least when I build from the src package in copr).

**Comment by tscherf** [comment]
The letsencrypt package is now available in Fedora:

http://koji.fedoraproject.org/koji/packageinfo?packageID=21509

**Comment by Deathnerd** [comment]
@tscherf a bit of a fedora/CentOS noob here. Can I use those packages on CentOS as well?

**Comment by NoodlesNZ** [comment]
@Deathnerd no, you generally can't use fedora packages on CentOS. If you're using CentOS 7 Let's Encrypt is available from EPEL (https://fedoraproject.org/wiki/EPEL), the package name is letsencrypt

**Comment by Deathnerd** [comment]
@NoodlesNZ thanks for the info!

**Comment by kyanha** [comment]
Any love for CentOS 6?

**Comment by NoodlesNZ** [comment]
A few dependencies that need to be addressed before it's released. Hopefully we'll get there but a bit harder than CentOS 7

**Comment by rbu** [comment]
If you want to follow/help with the addition to EPEL for RHEL/CentOS 6, there's two detailed bug reports at https://bugzilla.redhat.com/show_bug.cgi?id=1288999 and https://bugzilla.redhat.com/show_bug.cgi?id=1288744

We'd need to update and add several components, and for two of those it's not yet clear if they actually support Python 2.6 (namely idna, see https://github.com/kjd/idna/issues/20 and parsedatetime).

**Comment by pde** [comment]
I gather that Certbot EPEL 6 packages have been deemed a "wontfix" due to dependency issues, so we're going to continue to support and improve `certbot-auto` for CentOS 6 users.  Other than that, we're well packaged on more modern RPM distros, and I think we can close this!
