### ISSUE TITLE
--cert-path prepends a numeric prefix to the filename

### ISSUE THREAD

**Issue by kerio92** [certbot/certbot#1505]
When using `--csr` and `--cert-path`, the certificate is placed in a different location than what was specified by the user.

```
root@connor:~# /usr/local/bin/openssl req -new -newkey rsa:2048 -keyout dank.ninja.key -nodes -subj "/CN=dank.ninja" -reqexts SAN -config <( cat /usr/local/etc/ssl/openssl.cnf; echo "[SAN]"; echo subjectAltName=DNS:dank.ninja,DNS:www.dank.ninja ) -outform der -out dank.ninja.csr
Generating a 2048 bit RSA private key
.......................+++
....................................................+++
writing new private key to 'dank.ninja'
-----
```
```
root@connor:~# letsencrypt certonly --csr dank.ninja.csr --cert-path dank.ninja.crt

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /root/0001_chain.pem. Your cert will expire on 2016-02-12. To
   obtain a new version of the certificate in the future, simply run
   Let's Encrypt again.
```
```
root@connor:~# ls dank.ninja.crt
ls: dank.ninja.crt: No such file or directory
```
```
root@connor:~# ls 0000_dank.ninja.crt
0000_dank.ninja.crt
```

**Comment by bmw** [comment]
@sagi is going to take a look at this.

**Comment by PatrickHeppler** [comment]
Same with --chain-path and --fullchain-path, both get prefixed too. Either stop prefixing or set symlinks like in /etc/letsencrypt/live/example.com where current certs are symlinks to /etc/letsencrypt/archive/example.com/

**Comment by hlpinform** [comment]
Are there any news when this bug will be fixed? Because we want to use --fullchain-path and --cert-path parameter (we want to use the same private key, unless it becomes compromised, so that we can use hpkp with longer time periods). But right now, after every single renewal I have to "fix" the httpd ssl config or have to remove the numeric prefix and reload httpd (okay reloading httpd is inevitable either way).

**Comment by sagi** [comment]
Thanks for bumping it up.
@bmw: the `save_certificate(...)` function is triggered and saves the chain and crt files with unique file names that were generated by the  `le_util.unique_file(...)` function.

I'm currently thinking on creating a default arg `(..., unique_files=false)` that will be responsible for that.

**Comment by bmw** [comment]
@sagi, something like that would work. If `cert_path` is set on the command line, you can set `unique_files` to `False`. You would probably want the default of `unique_files` to be `True` to not break behavior elsewhere though.

With that said, it might be easier to just call [safe_open](https://github.com/letsencrypt/letsencrypt/blob/master/certbot/le_util.py#L154) directly with the arguments you want if `cert_path` is set.
