### ISSUE TITLE
Avoiding disabling Pylint's "too many arguments" in storage.py

### ISSUE THREAD

**Issue by TheNavigat** [certbot/certbot#1507]
Pylint's standards are broken a lot in this file, but this particular case https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/storage.py#L544 should be easily fixed by calling the function using a dictionary instead of 8 arguments.

We don't have to change a lot of depending code, since the function is only called at `client.py`, https://github.com/letsencrypt/letsencrypt/blob/151c674cba6cd1e88521dbb5141d0c25662757b1/letsencrypt/client.py#L272, and the function's own unit testing function, https://github.com/letsencrypt/letsencrypt/blob/5d9c32b583972e7581cecb5b2b51f0f73d509d6e/letsencrypt/tests/renewer_test.py#L539

**Comment by kuba** [comment]
This code needs refactoring, but I don't think using a dict is better from what we have now.

**Comment by TheNavigat** [comment]
Personally I think it's okay, but since we're supposedly following Pylint's guidelines, we should fix it. Otherwise, we should leave it there, doesn't look too bad.

**Comment by schoen** [comment]
I'm happy to see that this test is no longer disabled as of early 2016. :slightly_smiling_face:
