### ISSUE TITLE
Stop hardcoding plugin flags

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#1549]
We have currently hardcoded `--apache`, `--nginx`, `--standalone`, and `--webroot`. This isn't ideal for a number of reasons:

1) It requires us to have special logic for plugins that might not always be installed such as Apache or Nginx.
2) As the list of plugins grows, this becomes less maintainable.
3) It provides less visibility for 3rd party plugins. We're not likely to hardcode information like this for third party plugins which makes me question us doing it for our own plugins.

Instead, we should try to generate these flags dynamically based on the available plugins or not provide them at all.

**Comment by BurakDev** [comment]
+1 :+1:

**Comment by pde** [comment]
I think autogenerating them is a semi-reasonable plan, so long as nobody picks crazy names for their third party plugins...

**Comment by kuba** [comment]
@pde, have a look at `disco.py` and `PREFIX_FREE_DISTRIBUTIONS` in particular. If you're worried about people doing crazy stuff, then generate `--$plugin` flags only for plugins coming from `PREFIX_FREE_DISTRIBUTIONS`. Nevertheless, I'm against `--$plugin` in general and I much prefer `-a/i $plugin`.

**Comment by adferrand** [comment]
Still relevant, in my opinion.
