### ISSUE TITLE
documentation needs troubleshooting section

### ISSUE THREAD

**Issue by centminmod** [certbot/certbot#1550]
Online documentation section at https://letsencrypt.readthedocs.org/en/latest/index.html needs a troubleshooting section and maybe a standardised list of config files, log or debug log output and settings folks need provide to LE and/or steps for folks to find such info i.e. `-v` verbose flag on command line etc so you can help troubleshoot issues.

**Comment by SwartzCr** [comment]
closing this in favor of more recent tickets
