### ISSUE TITLE
letsencrypt-auto should notice if it's out of date

### ISSUE THREAD

**Issue by pde** [certbot/certbot#1560]
And suggest `git pull` or somesuch in that case.

**Comment by centminmod** [comment]
indeed i was going to post a new issue suggestion that all letsencrypt manual documentation, github readme, beta invite email and forum sticky threads so make note to always update the letsencrypt client etc before being run https://community.letsencrypt.org/t/beta-program-announcements/1631/7

there's just many changes being committed still, so conditioning folks into making it routine to update the client before running is good idea.

**Comment by centminmod** [comment]
thanks @pde for the clarification (maybe add to official docs too a section on updating the client)

**Comment by bmw** [comment]
This was resolved in 0.4.0.
