### ISSUE TITLE
Verboser DNS error message

### ISSUE THREAD

**Issue by da2x** [certbot/certbot#1567]
Please be a bit more descriptive than this so it actually can be troubleshooted and resolved. What IP did it expect to see? What IP did it see instead? This would be very useful information in this context.

```
 - The following 'unauthorized' errors were reported by the server:

   Domains: example.com www.example.com
   Error: The client lacks sufficient authorization

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.
```

**Comment by sydneyli** [comment]
This still seems like it would be useful in Certbot! For anyone who happens on this issue, there are third-party tools like [Let's Debug](https://letsdebug.net/) now that can help you debug failed ACME challenges.
