### ISSUE TITLE
Invalid certificate purpose for client auth

### ISSUE THREAD

**Issue by turowicz** [certbot/certbot#1578]
## Description

After converting the pem files into a windows-compatible pfx file we get a successful server https connection and everything works fine for hosting websites.
## Converting pem files into pfx

We issue the following command:

`openssl pkcs12 -export -out cert.pfx -in cert.pem -inkey privkey.pem -certfile chain.pem`
## Problem

We also use the certificates for client authentication. While the certificate's headers state clearly that purpose is both for client and server auth (below), windows only detects the server auth. I've noticed that the header value has purposes in a different order than my other windows-compatible certificates.

What's in the LE-signed certificate:

```
Enchaned Key Usage
Server Authentication (1.3.6.1.5.5.7.3.1)
Client Authentication (1.3.6.1.5.5.7.3.2)
```

What's in an example self-signed certificate:

```
Enchaned Key Usage
Client Authentication (1.3.6.1.5.5.7.3.2)
Server Authentication (1.3.6.1.5.5.7.3.1)
```
## Question

Has anyone got any ideas? 

Maybe I'm converting it wrong. 

LE bug?

Really I suspect it's probably just Windows being a buzzkill.

**Comment by pde** [comment]
This definitely isn't a Let's Encrypt client bug, though it could be whatever Windows application you're using, our boulder server...

Those EKU fields clearly have the same OIDs so unless Windows have an order-dependency bug, that's not it.  Can you dump all of the fields in an entire cert to see if there are any other interesting differences?

**Comment by turowicz** [comment]
Can't really give you my certificate's data but that is the only difference.

![image](https://cloud.githubusercontent.com/assets/1055391/11364549/f9790ca0-9298-11e5-9097-357a0acf5136.png)

**Comment by turowicz** [comment]
To me it does look like windows is being funny or I am converting it wrong. All the fields are there it's just how they are being picked up.

**Comment by turowicz** [comment]
One more thing: I am trying to use Google Chrome to authenticate to a website using a certificate.

**Comment by sydneyli** [comment]
This doesn't seem to be a Certbot bug-- If I'm mistaken feel free to yell at me and I'll re-open this ticket. If by any chance you still are having trouble with this, I'd recommend posting on the [community forums](https://community.letsencrypt.org/c/help)!
