### ISSUE TITLE
"letsencrypt rollback" asking about plugins is confusing

### ISSUE THREAD

**Issue by pde** [certbot/certbot#1581]
If you have letsencrypt-{nginx,apache} installed, executing `letsencrypt rollback` will trigger a plugin choice question.  Probably it should only do that if changes have been made by both plugins, and even then it should use different wording for the question.

**Comment by TheNavigat** [comment]
This is my own mistake, so first of all, I apologise for being repetitive, and for having a bad memory.

On the IRC you mentioned how I can retrieve the configuration file, which stores the current configuration. You also showed an example where the configuration file was retrieved and data was parsed and used.

I lost those messages. I'd be grateful if you could mention how to get started on this here again.

**Comment by TheNavigat** [comment]
@pde Ping

**Comment by pde** [comment]
@TheNavigat the files are stored in `/var/lib/letsencrypt/backups`.
