### ISSUE TITLE
Please add a workflow to use letsencrypt in manual mode

### ISSUE THREAD

**Issue by rubo77** [certbot/certbot#1649]
I found this instructions how to use the service without using the python install scripts:

https://www.tty1.net/blog/2015/using-letsencrypt-in-manual-mode_en.html

Please add a hint in your email how to use the manual mode and also a small summary, what the scripts do.

Otherwise, we will earn a lot of distrust by users, that already know how to create certificates and administrate their servers, that don't like to execute a python script in a box, without knowing EXACTLY what the script does.

We need transparency and a good HowTo how to use the service manually

**Comment by pde** [comment]
We've sent the last of those emails (Public Beta starts on Thursday) but perhaps we can embed or link to that post in the docs.

**Comment by pde** [comment]
Though it's not clear whether those instructions are better than one of these options:

https://github.com/diafygi/letsencrypt-nosudo
https://github.com/kuba/simp_le

**Comment by sydneyli** [comment]
We have documentation on using Certbot in both [manual](https://certbot.eff.org/docs/using.html#manual) and [standalone](https://certbot.eff.org/docs/using.html#standalone) modes.
