### ISSUE TITLE
Mac bootstrap script trusts PyPI for virtualenv installation

### ISSUE THREAD

**Issue by erikrose** [certbot/certbot#1659]
`pip install virtualenv`

That's no good if PyPI gets owned. I don't see a virtualenv package in homebrew, so I suppose the next best thing is to use `pip --require-hashes` and verify a pinned version against a hash.

**Comment by schoen** [comment]
@erikrose, is this problem still a concern nowadays? This issue is almost three years old and quite a lot has changed in the packaging since then.

**Comment by erikrose** [comment]
Yes, it looks like it: https://github.com/certbot/certbot/blob/06174bc11300fa5ccf406fcec3c165910da2c3d0/letsencrypt-auto-source/pieces/bootstrappers/mac.sh#L46

**Comment by erikrose** [comment]
@stale Yep, still a problem.
