### ISSUE TITLE
Where is the code for 0.1.0 release?

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#1672]
I don't see any tags nor branches in the repo. How can I reproduce the release?

**Comment by pde** [comment]
Pushed

**Comment by kuba** [comment]
`dev-release.sh` script doesn't support release without `dev` in the version label, so how did you build and release those PyPI packages? https://github.com/letsencrypt/letsencrypt/tree/v0.1.0 does not contain any additional release scripts.

**Comment by bmw** [comment]
While this is a problem for 0.1.0, it was fixed for all later releases where we used `tools/release.sh` to build the release. Closing this as fixed/wontfix.
