### ISSUE TITLE
Changelog is not up to date

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#1674]
`CHANGES.rst` should be updated

**Comment by kuba** [comment]
Also `long_description=readme,  # later: + '\n\n' + changes` should be fixed.

**Comment by Bubu** [comment]
Even more out of date now that 0.20 is released.

**Comment by tuxayo** [comment]
An changelog is essential to allow the users to check if there is a change that might break their renewal script for example.

**Comment by bmw** [comment]
This was fixed with the addition of CHANGELOG.md.
