### ISSUE TITLE
Implement a --debug-challenge option

### ISSUE THREAD

**Issue by pde** [certbot/certbot#1684]
If the client fails DV, there should be a way to keep the challenges deployed so that the user can go and manually inspect them to see what's failing.

It could be --debug-challenge.  Or it could be the default behaviour if DV fails during --debug.  Or it could be that --debug implies --debug-challenge by default.

**Comment by SwartzCr** [comment]
@bmw wanna add some context to this?

**Comment by pde** [comment]
The most ambitious version of what this flag might do is:

* if a challenge fails, pause and print some information:
  * what the challenge was, and how it is supposed to work
  * information on your current state (eg, "Certbot has made temporary changes to your Apache config to serve this TLS-SNI-01 cert (perhaps printing the config diff or pointing to a file that contains it) when things are correct you should be able to see that cert by doing curl/wget/nmap command XYZ", or "Certbot has deployed an HTTP-01 challenge file at path XYZ, you should be able to inspect it with wget blah")
* offer a prompt to either unpause and quit, or retry the challenge

**Comment by bmw** [comment]
I think instead we should just have a flag that always pauses after challenges are set up but before notifying the ACME server. I'm open to ideas on what this flag should be called.

**Comment by dhuang** [comment]
Working on a less ambitious version of this. Pausing after challenges are setup and suggesting the user use "-v" to debug further.

**Comment by pde** [comment]
Closing this as done. We can make a new ticket if we want the more ambitious versions!
