### ISSUE TITLE
ExecutableNotFound

### ISSUE THREAD

**Issue by spaceone** [certbot/certbot#1689]
```
Traceback (most recent call last):
  File "/usr/local/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1251, in main
    setup_logging(args, _cli_log_handler, logfile='letsencrypt.log')
  File "/usr/local/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1165, in setup_logging
    cli_handler = cli_handler_factory(args, level, fmt)
  File "/usr/local/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1152, in _cli_log_handler
    handler = log.DialogHandler()
  File "/usr/local/lib/python2.7/dist-packages/letsencrypt/log.py", line 29, in __init__
    self.d = dialog.Dialog() if d is None else d
  File "/usr/local/lib/python2.7/dist-packages/dialog.py", line 1013, in __init__
    self._dialog_prg = _path_to_executable(dialog)
  File "/usr/local/lib/python2.7/dist-packages/dialog.py", line 477, in _path_to_executable
    "can't find the executable for the dialog-like "
ExecutableNotFound
```

Which executable does it search for?

**Comment by kuba** [comment]
It searches for `dialog` executable. Are you using `letsencrypt-auto`? What Operating System exactly (including version) are you running?

**Comment by spaceone** [comment]
Debian GNU/Linux 7
letsencrypt 0.1.0

It happens when doing:
letsencrypt certonly --standalone -d www.example.com

**Comment by spaceone** [comment]
apt-get install python-dialog helped. Why isn't it a pip dependency?

**Comment by kuba** [comment]
How did you install `letsencrypt`? FYI installing using `pip` is not supported, please read big yellow warning at https://letsencrypt.readthedocs.org/en/latest/using.html#from-source.

**Comment by spaceone** [comment]
Well, I didn't knew and did it via pip.

**Comment by acdha** [comment]
Yeah, I'm puzzled that it's on PyPI at all before that works. If nothing else, the note should be very prominent rather than buried in a different section of the documentation.

**Comment by spaceone** [comment]
You could emit a warning in setup.py. If you want you can close this issue. Everything here seems to work, If I update I will see that I use some debian packages.

**Comment by fredguest** [comment]
@kuba a tool that is referenced in the certbot user guide here https://github.com/certbot/certbot/blob/2fa15641e3cb90bce34f650f9a56a0de905361e0/docs/using.rst#third-party-plugins instructs people to `pip install letsencrypt` here https://github.com/dlapiduz/letsencrypt-s3front#setup cc @dlapiduz

**Comment by bmw** [comment]
Due to problems like this (as well as other motivating factors), we've completely removed dialog as a dependency of this project in favor of our text interface for our next release. With this in mind, I'm closing this issue.
