### ISSUE TITLE
Bad LogFormat in /etc/letsencrypt/options-ssl-apache.conf?

### ISSUE THREAD

**Issue by mgedmin** [certbot/certbot#1720]
I ran `letsencrypt-auto` for the first time, generated a cert, and then started looking around.
I see this:

```
$ grep LogFormat /etc/letsencrypt/options-ssl-apache.conf 
LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"" vhost_combined
LogFormat "%v %h %l %u %t \"%r\" %>s %b" vhost_common
```

Compare that the default /etc/apache2/apache2.conf from Ubuntu's apache 2.4 package:

```
$ grep LogFormat /etc/apache2/apache2.conf 
LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %O" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent
```

Note that the "vhost_combined" log format you're defining in /etc/letsencrypt/options-ssl-apache.conf is identical to the "combined" log format and does not have the vhost:port information.

This seems wrong.

(Luckily, grep tells me options-ssl-apache.conf is not actually included anywhere from my Apache config files.)

**Comment by mgedmin** [comment]
> (Luckily, grep tells me options-ssl-apache.conf is not actually included anywhere from my Apache config files.)

Ah, I misunderstood the purpose of this file.

It's only used for the ephemeral `$hash.acme.invalid` vhost that's used for TLS-SNI domain validation.  Initially I thought it was intended to be used for every SSL vhost, to keep an automatically-updated set of SSL option tweaks for best security.

**Comment by sydneyli** [comment]
It seems like this issue was resolved. If I misunderstood, just poke me and I'll be happy to re-open.
