### ISSUE TITLE
No SSL for Amazon Cloudfront domain

### ISSUE THREAD

**Issue by ashwin31** [certbot/certbot#1727]
I am using amazon cloudfront cdn and new i wanted to use my custom domain name. So, I jave created a CNAME for a subdomain and pointed it to CloudFront domain. 

I tried to register my domain with letsencrypt and got the following error.
## Command:

```
./letsencrypt-auto certonly -a standalone -d peeljobs.com -d www.peeljobs.com -d cdn.peeljobs.com --server https://acme-v01.api.letsencrypt.org/directory --agree-dev-preview
```
## Error:

```
 - The following 'urn:acme:error:unauthorized' errors were reported by
   the server:

   Domains: cdn.peeljobs.com
   Error: The client lacks sufficient authorization
```

**Comment by michelmelo** [comment]
+ 1

**Comment by ashleyconnor** [comment]
+1

**Comment by bmw** [comment]
Our documentation has improved quite a bit in the last few months, including us providing a link to the third party s3front plugin in our [documentation](https://certbot.eff.org/docs/using.html#third-party-plugins). With that said, I created certbot/website#175 to track the issue of adding an option for this use case to our instruction generator. I'm closing this in favor of that issue.
