### ISSUE TITLE
Non-helpful error messages

### ISSUE THREAD

**Issue by sharpless** [certbot/certbot#1730]
If I have some kind of error in any of the config files for Apache, letsencrypt-auto fails.

If I run "./letsencrypt-auto", I get the response "No installers seem to be present and working on your system; fix that or try running letsencrypt with the "certonly" command", which really don't say anything. Of course I can check the logs to find out what went wrong, but that requires knowledge that the logs exist.

If I run "./letsencrypt-auto --apache", I get an error at least, but it might be a bit hard to understand: "The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/apache2/sites-available/error', u'Syntax error'),)".

Sure, it tells me that there is a problem in a specific file, but it doesn't tell me where or what.

For my example I am using Ubuntu 14.04.3, and created a file called "/etc/apache2/sites-available/error", containing the text "<>".

**Comment by bmw** [comment]
Related #1576

**Comment by sydneyli** [comment]
#1576 has been resolved, and we run `configtest` beforehands now. Any config parsing error from `apachectl configtest` is forwarded properly now.
