### ISSUE TITLE
nginx adapter not including options-ssl-nginx.conf with existing HTTPS server

### ISSUE THREAD

**Issue by aprescott** [certbot/certbot#1743]
Found this while using letsencrypt 0.1.0.

I have `/etc/nginx/nginx.conf` which has these sections in its `http {}` (among other configuration):

```
ssl_prefer_server_ciphers   on;
ssl_ciphers  DEFAULT:!aNULL:!eNULL:!ADH:!RC4:!RC2:!DES:+HIGH:+MEDIUM:!LOW:!SSLv2:!EXP:!MD5:!DSS:!PSK;
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
```

(Note this existing configuration is a default in a `http {}` block in `/etc/nginx/nginx.conf`, not specific to any individual `server {}`.)

It then uses

```
include sites-enabled/*.conf;
```

to pull in `/etc/nginx/sites-enabled/example.com.conf`, which defines an existing SSL-enabled server:

```
server {
  server_name www.example.com;
  rewrite ^ https://example.com$request_uri? permanent;
}

server {
  # ...

  listen 443 ssl spdy;
  server_name example.com;

  ssl                  on;
  ssl_certificate      ssl/foo-cert.pem;
  ssl_certificate_key  ssl/foo-key.key;

  ssl_session_cache    shared:SSL:5m;
  ssl_session_timeout  5m;
  # ...
}
```

After accounting for #921 (which causes problems because of the `ssl_session_cache`) I found that `letsencrypt --nginx -d example.com` will correctly update the `example.com.conf` file to have the correct `ssl_certificate` and `ssl_certificate_key` values. It _doesn't_, however, seem to include `options-ssl-nginx.conf` anywhere. (Before touching anything to do with `letsencrypt`, I did a `git init .` in my `/etc/nginx` directory, which has let me `git diff` on the file changes.)

I'm not sure what I was expecting, though. I guess I thought that the `server {}` block in `example.com.conf` would get the `include options-ssl-nginx.conf`. Does that override the SSL configuration for _only_ `https://example.com`, and leave the `/etc/nginx/nginx.conf` default? Is that actually expected because of `-d example.com`?

**Comment by olabini** [comment]
The options-ssl-nginx.conf file is only used when turning a vhost from a non-https to an https based vhost, it will never be added when changing an existing SSL configuration.
I'm currently working on a patch that will not use the conf-file at all, because of things like #921

**Comment by olabini** [comment]
In my opinion, this ticket can be closed

**Comment by aprescott** [comment]
I would personally rather see this stay open until it genuinely is fixed in the application. I know #2262 is open, but it isn't merged yet.

**Comment by olabini** [comment]
Well, the reason I said that is because it seems to me that the issue is saying that "options-ssl-nginx.conf" is not used for existing server blocks - and that is completely correct, and expected behavior. I'm not sure I understand what this issue wants to have fixed.

**Comment by aprescott** [comment]
That's fair. It comes down to what options-ssl-nginx.conf was/is used for. I'm not knowledgeable on the ins and outs of this project, but I opened this because it didn't seem correct that letsencrypt's main configuration file was being left out. If letsencrypt intends to automatically update a cipher suite configuration over time, then leaving out options-ssl-nginx.conf (where the cipher suite configuration happens(?)) would break that functionality.

So I guess you could interpret this issue as "whatever you were intending to use options-ssl-nginx.conf for: it's not being used." I see there's some discussion at https://github.com/letsencrypt/letsencrypt/pull/2262#issuecomment-174060593 about some of this.
