### ISSUE TITLE
custom ssl ports apache2

### ISSUE THREAD

**Issue by joostvanviegen** [certbot/certbot#1754]
I have my apache2 server running behind an openvpn server, which passes trough anything not vpn related. the problem is that when I run let's encrypt with the apache plugin, it messes with my ports.conf. So I first have to stop openvpn, then start the let's encrypt script. after that, I have to cleanup my configs so it'l have port 4545 for ssl instead of 443. Then I need to restart apache2 and after that I can start my vpn again. I really don't want to write a script that does all of the above.

Will there be  or is there a way to specify costum ports for the apache2 configs beforehand?

**Comment by pde** [comment]
The apache plugin is both an authenticator and an installer; it's probably the second of these two steps that's causing you the problem, so it may be that if you run in `certonly` mode it'll obtain the cert without leaving any persistent modifications to your conf file.
