### ISSUE TITLE
Apache plugin fails; syntax problem with mod_deflate.conf

### ISSUE THREAD

**Issue by seezee** [certbot/certbot#1755]
Command:
user@server:~/letsencrypt$ ./letsencrypt-auto run --apache -d domain.com -d www.domain.com

Result:
Updating letsencrypt and virtual environment dependencies.......
Running with virtualenv: sudo /home/user/.local/share/letsencrypt/bin/letsencrypt run --apache -d domain.com -d www.domain.com
The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/apache2/conf.d/mod_deflate.conf', u'Syntax error'),)

Contents of mod_deflate.conf:
# Enable mod_deflate (gzip)
    SetOutputFilter DEFLATE
    # Do not attempt to compress the following extensions
    SetEnvIfNoCase Request_URI \
    \.(?:gif|jpe?g|png|swf|flv|zip|gz|tar|mp3|mp4|m4v)$ no-gzip dont-vary

**Comment by pde** [comment]
This is the same bug as #1531.  Has now been fixed in master.

**Comment by pde** [comment]
(Fix was #1692)

**Comment by pde** [comment]
I was wrong, this isn't fixed by #1692.

**Comment by pde** [comment]
But it does appear to be fixed by #1827 :)

**Comment by domcleal** [comment]
Seems to be #1692 as you first said I think.

**Comment by MarcelWaldvogel** [comment]
On a fresh `git clone`, `letsencrypt-auto --apache -d example.com -d www.example.com` still fails on
```SetEnvIfNoCase Request_URI \.(?:exe|t?gz|zip|iso|Z|bz2|sit|rar|png|jpg|gif|jpeg|flv|swf|mp3)$ no-gzip dont-vary```

**Comment by domcleal** [comment]
We're discussing why this doesn't seem to be fixed at https://github.com/letsencrypt/letsencrypt/issues/1531#issuecomment-162809832 and subsequent comments.  I suspect letsencrypt-auto isn't updating the lens in ~/.local.
