### ISSUE TITLE
Installation fail + Segmentation fault on Debian 8

### ISSUE THREAD

**Issue by stylersnico** [certbot/certbot#1764]
Hi,

As said in #1737 , a segmentation fault occur when venv.sh is executed.

root@webhost:/tmp/letsencrypt/bootstrap# ./venv.sh
Segmentation fault
root@webhost:/tmp/letsencrypt/bootstrap#

@pde reccommended to install letsencrypt from package but I have this error:

apt-get -t experimental install python-letsencrypt
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
python-letsencrypt : Depends: python-acme (>= 0.1.0) but it is not going to be installed
Depends: python-configargparse but it is not installable
Depends: python-cryptography (>= 0.7) but 0.6.1-1 is to be installed
Depends: python-dialog but it is not installable
Recommends: letsencrypt but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Any idea? Please don't close the bug this time if it's not solved :)

**Comment by ParisLiakos** [comment]
wrote an article on how to install letsencrypt on debian 8.
https://www.rootatwc.com/blog/article/4

in short: make sure your stable pin is less than 990

**Comment by hlieberman** [comment]
If you are still having problems, I recommend trying again with the new packages.  The packages referred to in this ticket are quite dated.

@pde, please close.
