### ISSUE TITLE
Support creating a new certificate without making it "live"

### ISSUE THREAD

**Issue by RalfJung** [certbot/certbot#1769]
My server's DNS zone is secured via DNSSEC and TLSA, so I cannot just create a new certificate and use it. I have to create it, put its fingerprint into the zone, wait for 24h until that new TLSA record propagated, and only _then_ actually make the certificate live.

So far, I haven't figured out a good way to do this with the letsencrypt client.

**Comment by pde** [comment]
Are you running with the Apache plugin?

Running the `certonly` subcommand will get you a cert but not install it.

However the symlinks below `/etc/letsencrypt/live` will always be updated by that command to point to the newest cert, so if you have those entries in your conf files, any webserver reload event will cause them to be deployed.

The code in `renewer.py`, which isn't ready for use yet, actually has the ability to wait for a defined number of days before updating those symlinks.  You can emulate its behaviour by having your conf file point to the entries in `/etc/letsencrypt/archive/`, and updating them manually when you're ready to deploy a new cert.

**Comment by RalfJung** [comment]
> The code in renewer.py, which isn't ready for use yet, actually has the ability to wait for a defined number of days before updating those symlinks. 

That sounds like exactly what I need.

> You can emulate its behaviour by having your conf file point to the entries in /etc/letsencrypt/archive/, and updating them manually when you're ready to deploy a new cert.

Well, sure. But that's not rally practical. Of course I want to automate all this, and I won't have any automated tool mess with my config files.

It turns out that acme-tiny actually gives me the right amount of control that I need, so that I can develop a "staging" solution manually. It also lets me re-use key file more easily, so that I don't have to do a transition in the DNS so often (if the cert changes, but the key doesn't, DNS doesn't need updating if the TLSA records are set up properly.) So that's what I am going to go with, for now.

**Comment by reimarstier** [comment]
Given the API documentation at https://certbot.eff.org/docs/api/constants.html
following settings in **/etc/letsencrypt/renewal/mydomain.conf** exist:
* renew_before_expiry = 30 days
* deploy_before_expiry = 25 days (default 99 years)


Does this renew my certificate 30 days before expiry and update the symlinks 25 days before expiry?
