### ISSUE TITLE
Fix UI flow for the manual plugin

### ISSUE THREAD

**Issue by pde** [certbot/certbot#1777]
Currently it confuses people greatly with its mix of iDisplay and non-iDisplay output, and it doesn't do a good job of explaining the narrative flow it's creating ("in another window, open a shell to your server and do X").

http://mojzis.com/software/letsencryptshell/

might be one source of ideas for doing a better job.

**Comment by pde** [comment]
One review of the manual plugin from 1775 was:

> Fanky cli experience, step-by-step:
> 1) Manual mode presents a direction of what should be done to server on a domain to prove, and asks  to press return when done
> 2) Upon pressing a return after some 20 minutes (in which time server is properly configured), a screen  with color-in-cli appears showing something about error in validation, as a single line header.
> 3) A few seconds later, new line appear in cli (non-gui) style, saying that everything is OK, and pointing to places with certs.
> Given that step 3 shows success, warning display at step 2 just "puts hair on fire"

**Comment by bmw** [comment]
With the removal of `dialog` and the manual plugin now always using `IDisplay`, this can be closed.
