### ISSUE TITLE
Installation/user guide issues

### ISSUE THREAD

**Issue by Efreak** [certbot/certbot#1781]
I followed the instructions over in the [user guide](https://letsencrypt.readthedocs.org/en/latest/using.html#installation) for installation and running the client. The script *immediately* ran apt-get update, which surprised me--I expected a prompt of some type telling me what it was going to do first, possibly offering options.

- There should be some way of bypassing the repo update and software installation without commenting out stuff from the bootstrap file, as some systems (like my WD MyCloud NAS, as an example) break when you run these things; the user should be able to install the dependencies manually before running the automated script. This can be solved in several ways:
  - Provide a parameter to bypass the install entirely
  - Check to see if it's installed, and require an optional parameter to continue with installation, otherwise abort
  - Provide an interactive mode that prompts the user.

- `./letsencrypt-auto --help` doesn't provide any help or other information until *after* client installation. This help should be available *before* the client is installed, possibly with a notice that the software needs to be installed before any commands are available. Given that it runs from the repo, it should be relatively simple to extract the help info from cli.py without actually running it.

- The User Guide has an example command in the [webroot section](https://letsencrypt.readthedocs.org/en/latest/using.html#webroot) that doesn't wrap in small windows and the css is preventing scroll bars. Screenshot [here](http://vgy.me/LULkqY.png).

**Comment by chrisRidgers** [comment]
I was a little jarred by the client attempting to install when all i'd done was pass the help flag as well.

**Comment by bmw** [comment]
These issues have been resolved with more recent versions of `certbot-auto` and documentation.
