### ISSUE TITLE
Split into a small "expert" package and a big "users" package

### ISSUE THREAD

**Issue by htgoebel** [certbot/certbot#1793]
I just installed letsencrypt on a test-system and I'm quite startled about all the stuff it requires. While this is very useful for those not that skilled, it's alarming for those trying to minimise the footprint of their system.

Please split this tool into two packages:
- a small one for experts. Containing only the "manual" plugin part. No change to webserver-config, not fancy dialogs, not web-service.
- a full-featured one, containing all the bells and whistles.

**Comment by kuba** [comment]
This is somewhat related to #358

**Comment by sydneyli** [comment]
Since this, we've separated things into optional plugin packages! Core certbot allows you to obtain certs via `standalone` or `webroot` modes. For even more minimal use cases, there are also other more minimal acme clients, like acme.sh.
