### ISSUE TITLE
Is support planned for Windows / IIS..?

### ISSUE THREAD

**Issue by mcquiggd** [certbot/certbot#1794]
Obviously it is early days, but interested to know if Windows / IIS hosts are planned to be supported in the future.

Great initiative by the way...

**Comment by ScottRFrost** [comment]
https://github.com/ebekker/ACMESharp seems to be working toward this.  I found this project via a search on the Lets Encrypt forum: https://community.letsencrypt.org/search?q=IIS

**Comment by mcquiggd** [comment]
@ScottRFrost 

Thanks for the heads up... it looks like there are a few unofficial implementations worth evaluating - cheers for both links!

**Comment by ScottRFrost** [comment]
https://github.com/oocx/acme.net looked interesting too, but seems to be less mature / less far along in the development cycle.  Let us know which ones you test and which one you decide on.

**Comment by pde** [comment]
We've had some discussions about an IIS [plugin](https://letsencrypt.readthedocs.org/en/latest/contributing.html#plugin-architecture), but we don't have staff to work on it in the short term.

**Comment by pde** [comment]
It should actually not be particularly hard to do; I would recommend having the plugin call out to this code: https://github.com/natemrice/letsencrypt-powershell/

**Comment by eliotcougar** [comment]
I would like to have support for Apache running on Windows... Through configurable links to 'webroot' and Apache 'conf' folders...
I have Python here, but it's not enough...

**Comment by neographikal** [comment]
I would like Windows support as well, remarkable service but IIS support would be nice: it is quite a popular web server.

**Comment by CryptonZylog** [comment]
Yes, please!

I also manage a small network and would be great to also sign certificates for other network enable/IoT devices we manage.

**Comment by nitmir** [comment]
Even if I successfully install the letsencrypt client on windows (a windows 7 vm), It fails by using the function [geteuid](https://docs.python.org/2/library/os.html#os.geteuid) of the os modules only available on unix systems. cf https://community.letsencrypt.org/t/python-virtualenv-on-windows-10-attributeerror-geteuid. It would be nice for windows people to at least have certonly support.

Bellow, my letsencrypt installation tracelog on windows:

    C:\>pip install virtualenv 
    Collecting virtualenv 
      Downloading virtualenv-14.0.6-py2.py3-none-any.whl (1.8MB) 
        100% |################################| 1.8MB 217kB/s 
    Installing collected packages: virtualenv 
    Successfully installed virtualenv-14.0.6 
    You are using pip version 7.1.2, however version 8.0.2 is available. 
    You should consider upgrading via the 'python -m pip install --upgrade pip' comm 
    and. 
     
    C:\>virtualenv letsencrypt 
    New python executable in C:\letsencrypt\Scripts\python.exe 
    Installing setuptools, pip, wheel...done. 
     
    C:\>cd letsencrypt 
     
    C:\letsencrypt>cd Scripts 
     
    C:\letsencrypt\Scripts>activate.bat 
     
    (letsencrypt) C:\letsencrypt\Scripts>pip install letsencrypt 
    Collecting letsencrypt 
      Downloading letsencrypt-0.4.0-py2-none-any.whl (197kB) 
        100% |################################| 200kB 660kB/s 
    Collecting zope.interface (from letsencrypt) 
      Downloading zope.interface-4.1.3.tar.gz (141kB) 
        100% |################################| 143kB 1.3MB/s 
    Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\letse 
    ncrypt\lib\site-packages (from letsencrypt) 
    Collecting python2-pythondialog>=3.2.2rc1 (from letsencrypt) 
      Downloading python2-pythondialog-3.3.0.tar.bz2 (1.8MB) 
        100% |################################| 1.8MB 217kB/s 
    Collecting PyOpenSSL (from letsencrypt) 
      Downloading pyOpenSSL-0.15.1-py2.py3-none-any.whl (102kB) 
        100% |################################| 106kB 1.3MB/s 
    Collecting cryptography>=0.7 (from letsencrypt) 
      Downloading cryptography-1.2.2-cp27-none-win_amd64.whl (1.3MB) 
        100% |################################| 1.3MB 260kB/s 
    Collecting ConfigArgParse>=0.9.3 (from letsencrypt) 
      Downloading ConfigArgParse-0.10.0.tar.gz 
    Collecting parsedatetime (from letsencrypt) 
      Downloading parsedatetime-1.5-py2-none-any.whl (50kB) 
        100% |################################| 53kB 890kB/s 
    Collecting configobj (from letsencrypt) 
      Downloading configobj-5.0.6.tar.gz 
    Collecting pytz (from letsencrypt) 
      Downloading pytz-2015.7-py2.py3-none-any.whl (476kB) 
        100% |################################| 479kB 525kB/s 
    Collecting psutil>=2.1.0 (from letsencrypt) 
      Downloading psutil-4.0.0-cp27-cp27m-win_amd64.whl (156kB) 
        100% |################################| 159kB 871kB/s 
    Collecting six (from letsencrypt) 
      Downloading six-1.10.0-py2.py3-none-any.whl 
    Collecting acme==0.4.0 (from letsencrypt) 
      Downloading acme-0.4.0-py2.py3-none-any.whl (95kB) 
        100% |################################| 98kB 871kB/s 
    Collecting zope.component (from letsencrypt) 
      Downloading zope.component-4.2.2.tar.gz (546kB) 
        100% |################################| 548kB 660kB/s 
    Collecting mock (from letsencrypt) 
      Downloading mock-1.3.0-py2.py3-none-any.whl (56kB) 
        100% |################################| 57kB 871kB/s 
    Collecting pyrfc3339 (from letsencrypt) 
      Downloading pyRFC3339-1.0-py2.py3-none-any.whl 
    Collecting enum34 (from cryptography>=0.7->letsencrypt) 
      Downloading enum34-1.1.2.tar.gz (46kB) 
        100% |################################| 49kB 1.3MB/s 
    Collecting ipaddress (from cryptography>=0.7->letsencrypt) 
      Downloading ipaddress-1.0.16-py27-none-any.whl 
    Collecting pyasn1>=0.1.8 (from cryptography>=0.7->letsencrypt) 
      Downloading pyasn1-0.1.9-py2.py3-none-any.whl 
    Collecting idna>=2.0 (from cryptography>=0.7->letsencrypt) 
      Downloading idna-2.0-py2.py3-none-any.whl (61kB) 
        100% |################################| 61kB 1.3MB/s 
    Collecting cffi>=1.4.1 (from cryptography>=0.7->letsencrypt) 
      Downloading cffi-1.5.2-cp27-none-win_amd64.whl (150kB) 
        100% |################################| 151kB 871kB/s 
    Collecting requests (from acme==0.4.0->letsencrypt) 
      Downloading requests-2.9.1-py2.py3-none-any.whl (501kB) 
        100% |################################| 503kB 525kB/s 
    Collecting ndg-httpsclient (from acme==0.4.0->letsencrypt) 
      Downloading ndg_httpsclient-0.4.0.tar.gz 
    Collecting werkzeug (from acme==0.4.0->letsencrypt) 
      Downloading Werkzeug-0.11.4-py2.py3-none-any.whl (305kB) 
        100% |################################| 307kB 1.3MB/s 
    Collecting zope.event (from zope.component->letsencrypt) 
      Downloading zope.event-4.2.0-py2-none-any.whl 
    Collecting funcsigs (from mock->letsencrypt) 
      Downloading funcsigs-0.4-py2.py3-none-any.whl 
    Collecting pbr>=0.11 (from mock->letsencrypt) 
      Downloading pbr-1.8.1-py2.py3-none-any.whl (89kB) 
        100% |################################| 90kB 1.3MB/s 
    Collecting pycparser (from cffi>=1.4.1->cryptography>=0.7->letsencrypt) 
      Downloading pycparser-2.14.tar.gz (223kB) 
        100% |################################| 225kB 871kB/s 
    Building wheels for collected packages: zope.interface, python2-pythondialog, Co 
    nfigArgParse, configobj, zope.component, enum34, ndg-httpsclient, pycparser 
      Running setup.py bdist_wheel for zope.interface ... done 
      Stored in directory: C:\Users\Valentin\AppData\Local\pip\Cache\wheels\c9\15\5b 
    \3a7e3c7c3b67b5ee002c0ebe8ac1f46ec3c0379c5037c6ab71 
      Running setup.py bdist_wheel for python2-pythondialog ... done 
      Stored in directory: C:\Users\Valentin\AppData\Local\pip\Cache\wheels\f0\5f\b6 
    \531cf000ffa0221f1c1dd4e95004248e664b90e673e5be8741 
      Running setup.py bdist_wheel for ConfigArgParse ... done 
      Stored in directory: C:\Users\Valentin\AppData\Local\pip\Cache\wheels\c0\ce\1b 
    \bb8d37531096afe7a604aab11423df765c232b6d8d2ebaa2de 
      Running setup.py bdist_wheel for configobj ... done 
      Stored in directory: C:\Users\Valentin\AppData\Local\pip\Cache\wheels\d0\18\3a 
    \88a9e8e07940560496c247872870978bf9b6cd5d914c0eac3e 
      Running setup.py bdist_wheel for zope.component ... done 
      Stored in directory: C:\Users\Valentin\AppData\Local\pip\Cache\wheels\64\b9\9d 
    \df8cb192e4b1cb5691fa67c56a841500ac562bd99337d6ef5a 
      Running setup.py bdist_wheel for enum34 ... done 
      Stored in directory: C:\Users\Valentin\AppData\Local\pip\Cache\wheels\1a\4e\a5 
    \bc564dd03d9abe991425c88d88aa8c5c99ad9a733551b69b4e 
      Running setup.py bdist_wheel for ndg-httpsclient ... done 
      Stored in directory: C:\Users\Valentin\AppData\Local\pip\Cache\wheels\30\85\40 
    \a29750f9287fe119a10708580a73cfb16f51e5f9a820430a2d 
      Running setup.py bdist_wheel for pycparser ... done 
      Stored in directory: C:\Users\Valentin\AppData\Local\pip\Cache\wheels\c7\28\31 
    \bac6d0b118c0bdcbf57f9219afdf2e624379c07efa6c769dbc 
    Successfully built zope.interface python2-pythondialog ConfigArgParse configobj 
    zope.component enum34 ndg-httpsclient pycparser 
    Installing collected packages: zope.interface, python2-pythondialog, six, enum34 
    , ipaddress, pyasn1, idna, pycparser, cffi, cryptography, PyOpenSSL, ConfigArgPa 
    rse, parsedatetime, configobj, pytz, psutil, requests, ndg-httpsclient, werkzeug 
    , funcsigs, pbr, mock, pyrfc3339, acme, zope.event, zope.component, letsencrypt 
    Successfully installed ConfigArgParse-0.10.0 PyOpenSSL-0.15.1 acme-0.4.0 cffi-1. 
    5.2 configobj-5.0.6 cryptography-1.2.2 enum34-1.1.2 funcsigs-0.4 idna-2.0 ipaddr 
    ess-1.0.16 letsencrypt-0.4.0 mock-1.3.0 ndg-httpsclient-0.4.0 parsedatetime-1.5 
    pbr-1.8.1 psutil-4.0.0 pyasn1-0.1.9 pycparser-2.14 pyrfc3339-1.0 python2-pythond 
    ialog-3.3.0 pytz-2015.7 requests-2.9.1 six-1.10.0 werkzeug-0.11.4 zope.component 
    -4.2.2 zope.event-4.2.0 zope.interface-4.1.3 
     
     
    (letsencrypt) C:\letsencrypt\Scripts>letsencrypt.exe --help 
     
      letsencrypt [SUBCOMMAND] [options] [-d domain] [-d domain] ... 
     
    The Let's Encrypt agent can obtain and install HTTPS/TLS/SSL certificates.  By 
    default, it will attempt to use a webserver both for obtaining and installing 
    the cert. Major SUBCOMMANDS are: 
     
      (default) run        Obtain & install a cert in your current webserver 
      certonly             Obtain cert, but do not install it (aka "auth") 
      install              Install a previously obtained cert in a server 
      renew                Renew previously obtained certs that are near expiry 
      revoke               Revoke a previously obtained certificate 
      rollback             Rollback server configuration changes made during install 
     
      config_changes       Show changes made to server config during installation 
      plugins              Display information about installed plugins 
     
    Choice of server plugins for obtaining and installing cert: 
     
      (the apache plugin is not installed) 
      --standalone      Run a standalone webserver for authentication 
      (nginx support is experimental, buggy, and not installed by default) 
      --webroot         Place files in a server's webroot folder for authentication 
     
    OR use different plugins to obtain (authenticate) the cert and then install it: 
     
      --authenticator standalone --installer apache 
     
    More detailed help: 
     
      -h, --help [topic]    print this message, or detailed help on a topic; 
                            the available topics are: 
     
       all, automation, paths, security, testing, or any of the subcommands or 
       plugins (certonly, install, nginx, apache, standalone, webroot, etc) 
     
     
    (letsencrypt) C:\letsencrypt\Scripts>

**Comment by markadrake** [comment]
+1 - I was very excited to see that Let's Encrypt was issuing certificates but looks like there is no way to download a certificate for use on IIS? Please correct me if I'm wrong.

**Comment by kinguru** [comment]
Hi all,

Very need Windows implementation of LetsEncrypt cert. 
I tried few times with thoughts - ok, there is nothing hard, I will do it now.
And after hours of "doing things" I was unable to generate certificate on Windows system.
Please, make a windows tools or Certbot page for Windows/IIS platform.

**Comment by bmw** [comment]
@kinguru, while Certbot would need quite a bit of work to support Windows, there are many Windows clients that can be used with Let's Encrypt listed [here](https://community.letsencrypt.org/t/list-of-client-implementations/2103).

**Comment by stelf** [comment]
+1

**Comment by Foxtrek64** [comment]
For those that need support for Windows because they do not have any Linux machines available, one solution might be to purchase a thumb drive (8gb or larger) or a DVD, download your favorite Linux distro, and look into directions on that distro's site about how to set up a [Live Disc](https://en.wikipedia.org/wiki/Live_CD). For instance, [Ubuntu LiveCD](https://help.ubuntu.com/community/LiveCD). You should then be able to, following CertBot documentation, generate and export your certificates and then add them to your Windows host (or anywhere else) manually. Unfortunately, this solution does not support automated renewal, but is a good temporary work-around if you do not have the money to drop on a new dedicated Linux box or are just looking to do one-time cert generation for testing purposes.

**Comment by phisad** [comment]
I got certbot run with the recent Windows Linux Subsystem after installation of **Ubuntu Bash for Windows 10**

1. Install and Start Ubuntu Bash for Windows
2. Download certbot-auto
3. Run certbot-auto (will install python etc.)

**Comment by kinguru** [comment]
Thank you, Philipp,

getting an error in process of generating certificate:

root@PROMETEY:/var/log/letsencrypt# tail letsencrypt.log
   File 
"/home/kinguru/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", 
line 197, in _poll_challenges
     _report_failed_challs(all_failed_achalls)
   File 
"/home/kinguru/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", 
line 488, in _report_failed_challs
     _generate_failed_chall_msg(achalls), reporter.MEDIUM_PRIORITY)
   File 
"/home/kinguru/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", 
line 504, in _generate_failed_chall_msg
     if messages.is_acme_error(error):
   File 
"/home/kinguru/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/messages.py", 
line 39, in is_acme_error
*    return (ERROR_PREFIX in str(err)) or (OLD_ERROR_PREFIX in str(err))**
**UnicodeEncodeError: 'ascii' codec can't encode characters in position 
321-322: ordinal not in range(128)*

**Comment by ThomasCr** [comment]
@bmw
but the most use ACMESharp, which seams far behind certbot - specially when u don't need it for IIS!

**Comment by kinguru** [comment]
I need very simple task. 
Generate
A LetsEncrypt certificate
Locally
On my Windows machine
For my Windows hosting provider

I have no understanding how to do it. Still after maybe a year of trying time ti time - no way to do it.
That is what i call linux vs windows usability.

**Comment by ThomasCr** [comment]
I managed to get cert with ACMESharp PS Module, but there are currently some thinks I really dont like:
- [only 2048 bit keys](https://github.com/ebekker/ACMESharp/issues/220)
- [no tls challenge support](https://github.com/ebekker/ACMESharp/issues/122)
- its not easy to use - a lot of scripting needed [example](https://github.com/ebekker/ACMESharp/issues/219) and no pre/post handling, no easy update,...

**Comment by phisad** [comment]
Well, I removed my solution as it seems a bit off-topic here. And I cannot see how IIS is different in certificate handling. But unfortunately, I couldn't fully run it through, because the remote server wasn't accessible in the required way. I'd run `certbot-auto --manual`

**Comment by kinguru** [comment]
Right, you should not access remote server to create a cert. Why?
IIS hosting providers do not provide console access to server. So you can't run anything on server like script. And you do not need to do that.

**Comment by phisad** [comment]
Hm? With LetsEncrypt it's pretty reasonable that the creator of the certificate must show ownership of the server for which the certificate is made for (since anybody can create such certificates). Well, maybe I could have shown ownership with my FTP access to the server. You have to put a certain file on it.

**Comment by bmw** [comment]
A small step towards doing the work necessary to make Certbot work on Windows was done in #4950. That code was added to https://github.com/certbot/certbot/tree/ahaw021-windows.

**Comment by adferrand** [comment]
Little update to inform that Certbot for Windows is in an active development state.

Relevant PRs so far: 
- merged: #6296, #6361, #6374, #6415, #6431, #6435, #6490 
- in progress: #6416, #6417, #6440, #6487, #6493, #6497

Relevant issues: #4510, #6354, #6355, #6356, #6430

**Comment by bmw** [comment]
Begone stale bot. We're still actively working on this.

**Comment by b9chris** [comment]
Is this still under active dev?

I don't know if it helps any but my process from where certbot leaves IIS users is:

openssl pkcs12 -export -out cert.pfx -in fullchain.pem -inkey privkey.pem -pass <pass>
certutil –p "<pass>" -importPFX "cert.pfx"

After those 2 commands, I still have a little more work - I need to use a tool to edit the Friendly Name to something that leads with an asterisk - I use the format *lets20191025 or whatever date the cert was generated on - and then I need to open IIS Administrator and change the HTTPS cert for one site using the old cert, to the updated one - this causes all the rest to use the new one automatically.

But, if certbot just issued the above steps - of getting the cert installed in the machine's cert list - I'd have a little less manual work to do every 60 days. And it might not be a lot to add, to issue those 2 commands, with this guidance?

**Comment by bmw** [comment]
IIS support isn't on our roadmap for the next year, but we may add it in the future.

In the meantime, you should take a look at Certbot's `--deploy-hook` option. You can put those commands in a batch or powershell script and Certbot will run the command every time the certificate is renewed, setting environment variables that can be used to find the certificate. You can find more information about this at https://certbot.eff.org/docs/using.html#renewing-certificates and Certbot's `--help` output:
```
  --deploy-hook DEPLOY_HOOK
                        Command to be run in a shell once for each
                        successfully issued certificate. For this command, the
                        shell variable $RENEWED_LINEAGE will point to the
                        config live subdirectory (for example,
                        "/etc/letsencrypt/live/example.com") containing the
                        new certificates and keys; the shell variable
                        $RENEWED_DOMAINS will contain a space-delimited list
                        of renewed certificate domains (for example,
                        "example.com www.example.com" (default: None)
```

**Comment by b9chris** [comment]
OK; I see that IIS support has been on again/off again for 5 years; if I can get a deploy-hook that works for most IIS users working, could that be something that's included in the certbot repo and mentioned in the certbot docs?

A deploy-hook might be wiser anyway - from reading the dev docs, having to dev on Linux I'm sure makes working with IIS extremely hard to test.

**Comment by bmw** [comment]
> if I can get a deploy-hook that works for most IIS users working, could that be something that's included in the certbot repo and mentioned in the certbot docs?

If the focus is on a good, clear example we could probably do something like that. It could go in [certbot/examples](https://github.com/certbot/certbot/tree/master/certbot/examples) and/or https://certbot.eff.org/docs/using.html.

**Comment by alexhass** [comment]
See https://www.win-acme.com/ for a great Windows / IIS solution.
