### ISSUE TITLE
fails to run on debian jessie, no error reported

### ISSUE THREAD

**Issue by antonpiatek** [certbot/certbot#1803]
I'm having some problems running letsencrypt on Debian Jessie

```
./letsencrypt-auto --help
Updating letsencrypt and virtual environment dependencies...
```

Nothing appears to happen, and no error is reported.

Looking at the script source, I found a debug flag:

```
./letsencrypt-auto -v
Updating letsencrypt and virtual environment dependencies...
Cannot fetch index base URL https://pypi.python.org/simple/
Could not find any downloads that satisfy the requirement setuptools in /home/anton/.local/share/letsencrypt/lib/python2.7/site-packages
Downloading/unpacking setuptools
Cleaning up...
No distributions at all found for setuptools in /home/anton/.local/share/letsencrypt/lib/python2.7/site-packages
Storing debug log for failure in /home/anton/.pip/pip.log
```

Looking at the pip log shows several lines like

```
Could not fetch URL https://pypi.python.org/simple/setuptools/: connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
Will skip URL https://pypi.python.org/simple/setuptools/ when looking for download links for setuptools in /home/anton/.local/share/letsencrypt/lib/python2.7/site-packages
```

Now, I'll admit that the underlying cause is probably a debian bug in ssl certificates, however shell script should really be detecting this and reporting that it failed to configure environment

Python version is: Python 2.7.9

**Comment by pde** [comment]
Tens of thousands of people have run `letsencrypt-auto` successfully on Debian Jessie, so it's unlikely to be a universal bug in the `ssl-certificates` package.  Does the bug persist for you?  Is the certificate at https://pypi.python.org/simple/setuptools/ correct from your network endpoint?

**Comment by antonpiatek** [comment]
The certificates issue was due to not selecting enough new certs during
upgrade, however the letsencrypt script could have pointed me to the log
sooner or at least told me it errored

**Comment by ellipsisno** [comment]
@antonpiatek encountered a similar problem a few moments ago. No SSL verification errors, though, simply a connection timeout.

I wouldn't have known to check pip.log if it weren't for this thread (likewise, nothing happened & no error appeared after 'Updating letsencrypt and virtual environment dependencies...').

**Comment by poizan42** [comment]
I'm getting the same error on debian jessie, but this is written directly to the console:
```
...
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
augeas-lenses is already the newest version.
libaugeas0 is already the newest version.
ca-certificates is already the newest version.
dialog is already the newest version.
gcc is already the newest version.
libffi-dev is already the newest version.
python is already the newest version.
python-dev is already the newest version.
python-virtualenv is already the newest version.
virtualenv is already the newest version.
libssl-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
WARNING: unable to check for updates.
Creating virtual environment...
Installing Python packages...
Traceback (most recent call last):
  File "/tmp/tmp.umYKNSkiOI/pipstrap.py", line 146, in <module>
    exit(main())
  File "/tmp/tmp.umYKNSkiOI/pipstrap.py", line 130, in main
    for url, digest in PACKAGES]
  File "/tmp/tmp.umYKNSkiOI/pipstrap.py", line 112, in hashed_download
    response = opener().open(url)
  File "/usr/lib/python2.7/urllib2.py", line 432, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 450, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 410, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
```

@pde debian jessie does not have any packages named "ssl-certificates"

@antonpiatek Which package was that? I have never been asked anything about selecting certificates AFAIR

Also I should note that it worked correctly for me back in april.

**Comment by bmw** [comment]
By the way, if you're on Jessie, it is strongly recommended to use the [packages from backports](https://certbot.eff.org/#debianjessie-other) over `certbot-auto`/`letsencrypt-auto`.

**Comment by sydneyli** [comment]
I'm closing this ticket since it hasn't gotten much traffic since; if you're still experiencing this problem please nudge me here and I'll re-open it!
