### ISSUE TITLE
Create validation files automatically (for shared web hosting)

### ISSUE THREAD

**Issue by FerhatAkgun** [certbot/certbot#1817]
Running "./letsencrypt-auto certonly --manual -c cli.ini" shows the below message template for each domain listed in cli.ini. 

MESSAGE_TEMPLATE = """\
Make sure your web server displays the following content at
{uri} before continuing:
{validation}
If you don't have HTTP server configured, you can run the following
command on the target server (as root):
{command}

I am running letsencrypt on my local machine to create certificates for my domains, which are hosted on a foreign server. 
Currently I need to copy "abcd.efgh" of the below terminal output into a text editor and save it into a the file "abcd".
"printf "%s" abcd.efgh > .well-known/acme-challenge/abcd"
This must to be done for each domain name listed in cli.ini.

It would be better if I could pass an additional parameter like:
./letsencrypt-auto certonly --manual -c cli.ini --validation-path ~/tmp/

In that case letsencrypt would create automatically all the validation files inside ~/tmp/.
Than it would stop and notify the user, that he can upload now these files via FTP to his server.
After file transfer is finished the user hits on OK inside letsencrypt and the validation starts.

**Comment by marcohu** [comment]
+1

But please don't stop at the creation of the challenge files. I would like to be able to automate the upload to the shared server as well.

It might be (already) possible to write a custom plugin for the creation and uploading. It's not exactly clear to me how plugin mechanism works.

**Comment by kuba** [comment]
I suggest to mount the FTP as file system (e.g. using https://wiki.archlinux.org/index.php/CurlFtpFS) and use `webroot` plugin instead (that plugin saves files to file system, you can also use it for `sshfs` etc.).

**Comment by marcohu** [comment]
It works! Thanks much for sharing!

**Comment by Wardevour** [comment]
This seems really straight forward, but I cant get the webroot plugin to recognize the mount point, for sshfs, as a directory. The webroot is mounted at /home/kenny/sftpmnt/. I can create files there and browse my website

Here's the output with debugging enabled: http://pastebin.com/BfwR5vkL

letsencrypt 0.4.0
commit 27b0cb0c4da96908c62ce1018da80a82b81b27cf

Ubuntu GNOME 14.04 3.16.0-59-generic

**Comment by sydneyli** [comment]
Our `webroot` plugin should work well for this use case! Closing this issue.
@Wardevour, if you're still having trouble with this, feel free to ask for help on [our community forums](https://community.letsencrypt.org/c/help) -- there's a big audience of folks there who are also quite familiar with the project. You'll get faster help there!
