### ISSUE TITLE
Add a README file to each live directory explaining its contents

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#1819]
Individually tracking the suggestion at

https://github.com/letsencrypt/letsencrypt/issues/1201#issuecomment-155652280

to have a README file to explain to users what's going on.

**Comment by bmw** [comment]
Related to #608.

**Comment by schoen** [comment]
Does anyone want to propose what this paragraph might say?

**Comment by pde** [comment]
Perhaps steal some of the text that you use for #3232?

**Comment by schoen** [comment]
(about the explanation of lineages)

**Comment by pde** [comment]
I'd do this: write just a paragraph about what files are in the lineage, and how to work with them (eg, always refer `/etc/letsencrypt/live` rather than the `archive` files etc).

Then link to your new docs that provide more narrative about flags for working with lineages.

**Comment by bmw** [comment]
Related #3615
