### ISSUE TITLE
implement json header for .pem files

### ISSUE THREAD

**Issue by ThomasWaldmann** [certbot/certbot#182]
splitting this issue off from #179:

jdkasten:
"""
I do think we need to do a better job of communicating the key's purpose and its abilities. Right now, every key-letsencrypt_*.pem key is technically an authorized (account) key within ACME... which will/can be different than the certificate key in the CSR. Perhaps we should write comments in the pem files themselves about the capabilities of the key.

Example:
Authorization valid until: XXXXX
This key is an ACME authorized key for the following names: example.com, foo.example.com
(This key is not known to be contained within any Let's Encrypt certificate)????
-----BEGIN CERTIFICATE-----
....
or
Authorization valid until: XXXXX
This key is an ACME authorized key for the following names: example.com, foo.example.com
This key is used in the certificate:
Issued at:
Issuer:
Domains:
Original filepath:
-----BEGIN CERTIFICATE-----
...

This allows for a bit more flexibility and gives power users more info. Thoughts?
"""

thomaswaldmann:
"""
use (pretty formatted) json for the header, so it can be parsed automatically also.
"""

**Comment by kuba** [comment]
Unfortunately, JSON doesn't get along very well with standard UNIX tools. I like the header idea, but can we please have it easily `grep`able etc.? :)

**Comment by ohemorange** [comment]
I don't think we actually need this feature.
