### ISSUE TITLE
Apache2 Auto-install issues with WSGI server modules...

### ISSUE THREAD

**Issue by dewhisna** [certbot/certbot#1820]
I attempted to use the letsencrypt-auto script to install a cert on one of my domains that is using WSGI modules on Apache2.  The problem is that when it copies the base .conf file to generate one for the SSL equivalent, it doesn't generate new WSGIDaemonProcess names.

The error you get is as follows:

> Error while running apache2ctl configtest.
> Action 'configtest' failed.
> The Apache error log may have more information.
> AH00526: Syntax error on line 36 of 
> /etc/apache2/sites-enabled/mysite.conf:
> Name duplicates previous WSGI daemon definition.

The Apache log file doesn't have any additional details, but the problem is the following line in the conf files:

```
        WSGIDaemonProcess mydaemon \
            processes=2 \
            threads=1 \
            display-name=%{GROUP} \
            python-path=/var/www/myserver/venv/lib/python2.7/site-packages \
            python-eggs=/var/www/myserver/data/python-egg-cache

        WSGIProcessGroup mydaemon
```

The WSGI Daemon Process name must be unique and there's already one in the base mysite.conf file and so the mysite.conf-le-ssl.conf (or whatever it gets called) causes a duplicate name.

I don't know that there's an easy fix for the auto script because I believe it's going to necessitate having two different daemons running -- one for the SSL version and one for unencrypted.  If the user is switching to encrypted only where there's only one daemon running, perhaps it would work, if the unencrypted gets dropped or delegated to the encrypted.

Otherwise, where it will get tricky is whether or not two daemons will play nicely when run from the same setup (i.e. same files).  Now in my case, as evidenced above, it's a Python script and it happens to interface with a mysql engine on the backend, etc.  The mysql daemon should sort out database accesses, but it may be desired (or even necessary) to have separate caches and scripts, etc, between the two for the configuration files and things that would otherwise be co-accessed, as the daemon may not be expecting to have to do file locking and such.

I had a similar issue when setting up my development environment on this server, though that is a completely separate code base with different paths, etc, so I just named it something like "mydaemon-dev" and ran different daemons.  But letsencrypt-auto probably won't know if two daemons can run simultaneously with the same configuration or not, and so it probably can't just change the name to mydaemon-ssl or something for the copy and expect it to work.

The simple solution is for the user to manually add the SSL setup to the server, but what this bug report is about is for adding a detection mechanism to the letencrypt-auto script to see if a WSGIDaemonProcess is defined and properly notify the user that it has to be manually enabled rather than spewing out a bunch of warnings and exiting in a somewhat incomplete state (as I don't think it finished setting up my other virtual domains that otherwise had no issues until I ran it again and excluded this domain).

Thanks!
Donna

**Comment by zenite** [comment]
I also have this issue, and another issue that comes with it is that if you retry the process, a new certificate seems to be installed (even if the previous worked), and you eventually exceed your limit.

So even if the limit is exceeded during this process, it might be possible to make it work with the last created certificate.


I solved this by:

* creating an ssl certificate for apache
* including the normal wsgi setting, but without the lines WSGIDaemonProcess and WSGIProcessGroup.
* Then copied these lines into the bottom, before </VirtualHost

SSLCertificateFile /etc/letsencrypt/live/mydomain.com/cert.pem
SSLCertificateKeyFile /etc/letsencrypt/live/mydomain.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateChainFile /etc/letsencrypt/live/mydomain.com/chain.pem

**Comment by dos1** [comment]
+1ing as I just got bitten by it as well.

**Comment by chrisbog94** [comment]
BUMP
Having this issue also

**Comment by pde** [comment]
This might be a good volunteer task for someone who's a strong programmer and willing to wrangle with Augeas?

**Comment by mattbrosenberg** [comment]
I was able to set up my standalone app and work around the `Name duplicates previous WSGI daemon definition.`-problem successfully by doing this alteration:

In `sites-enabled/000-default.conf`:
``` apache
WSGIDaemonProcess myproject python-path=/path/to/lib/python3.4/site-packages
WSGIProcessGroup myproject
WSGIScriptAlias / /path/to/wsgi.py
```
In `sites-enabled/000-default-le-ssl.conf`:
```apache

# COMMENT_OUT_OR_REMOVE_THIS_LINE--> WSGIDaemonProcess myproject python-path=/path/to/lib/python3.4/site-packages
WSGIProcessGroup myproject
WSGIScriptAlias / /path/to/wsgi.py
```

It was some time ago, so I forget if I had to comment-out that line in `000-default.conf` in order to run the auto-install, and then comment it back in, or if I was able to run the auto-install and then commented it out afterwards. Either way, this is how it exists on my server now and works.

**Comment by geckon** [comment]
I encountered the issue as well. I had to comment the WSGIDaemonProcess line out before running letsencrypt. Then I uncommented it again.

**Comment by gfairchild** [comment]
I just encountered this same issue. @geckon's solution (commenting out the `WSGIDaemonProcess` line) allowed letsencrypt to continue, but that's an undesirable fragile solution.

A better solution would be for letsencrypt to change the `WSGIDaemonProcess` name. If the port 80 VirtualHost's `WSGIDaemonProcess` was named `process`, then something like `process-le` or `process-tls` would make good sense.

**Comment by pde** [comment]
Kicking :(

**Comment by bmw** [comment]
@joohoi, same question here as https://github.com/certbot/certbot/issues/2726#issuecomment-294034882

**Comment by Alirezaies** [comment]
+1 @mattbrosenberg

**Comment by joohoi** [comment]
I created an umbrella issue for this and similar ones, so I'm closing this, feel free to continue discussion in #4797

**Comment by eddyizm** [comment]
I just ran into this issue and tried @mattbrosenberg 's work around however I forced the redirect to https option when running through the automatic install. 

this led me to do the same commenting out of the  WSGIDaemonProcess  line however I did it to my original default file instead of the ssl conf file, Basically the opposite in order to get this to work.

**Comment by bluppfisk** [comment]
I think I solved it on the Django level by adding the path to the challenge as a static path in *settings.py*:

```
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
    os.path.join(BASE_DIR, "static/.well-known/acme-challenge"),
    os.path.join(ANGULAR_APP_DIR),
)
```
