### ISSUE TITLE
NoInstallationError() from Apache plugin within renewal cron jobs due to /usr/sbin not being in the PATH

### ISSUE THREAD

**Issue by linuxlurak** [certbot/certbot#1833]
Im running a cron job that executes a script with the following content:
```
#!/bin/sh
echo "" >> /var/log/letsencrypt/$1.log
echo "$(date): Certificate Renewal of $1">> /var/log/letsencrypt/$1.log
echo "-----------------------------------------------------------------"
/root/letsencrypt/letsencrypt-auto certonly --apache --rsa-key-size 4096 --renew-by-default --hsts --redirect --agree-tos -m EMAIL.TLD -d $1 --text >> /var/log/letsencrypt/$1.log 2>&1
```

I get this Error:
```
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt certonly --apache --rsa-key-size 4096 --renew-by-default --hsts --redirect --agree-tos -m EMAIL.TLD -d DOMAIN.TLD --text
The apache plugin is not working; there may be problems with your existing configuration.
The error was: NoInstallationError()"
```

Anything i can do?

**Comment by pde** [comment]
Run interactively with -vvv and --debug, to get more detail on what the problem is.  I suspect but am not sure that the apache plugin is crashing on one of your conf files; if you can figure out which one, can you paste it?

**Comment by linuxlurak** [comment]
Debug log:
```
2015-12-09 18:57:29,688:DEBUG:letsencrypt.cli:Root logging level set at 0
2015-12-09 18:57:29,689:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2015-12-09 18:57:29,689:DEBUG:letsencrypt.cli:letsencrypt version: 0.1.0
2015-12-09 18:57:29,690:DEBUG:letsencrypt.cli:Arguments: ['--debug', '-vvv', '--apache', '--rsa-key-size', '4096', '--renew-by-default', '--hsts', '--redirect', '--agree-tos', '-m', 'REMOVED', '-d', 'REMOVED', '--text']
2015-12-09 18:57:29,690:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2015-12-09 18:57:29,692:DEBUG:letsencrypt.cli:Requested authenticator apache and installer apache
2015-12-09 18:57:29,713:DEBUG:letsencrypt.plugins.disco:No installation (PluginEntryPoint#apache):
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 142, in prepare
    raise errors.NoInstallationError
NoInstallationError
2015-12-09 18:57:29,715:DEBUG:letsencrypt.display.ops:No candidate plugin
2015-12-09 18:57:29,716:DEBUG:letsencrypt.cli:Selected authenticator None and installer None
```

stderr and stdout:
```
-vvv
Updating letsencrypt and virtual environment dependencies...
Requirement already up-to-date: setuptools in ./.local/share/letsencrypt/lib/python2.7/site-packages
Requirement already up-to-date: pip in ./.local/share/letsencrypt/lib/python2.7/site-packages
Requirement already up-to-date: letsencrypt in ./.local/share/letsencrypt/lib/python2.7/site-packages
Requirement already up-to-date: letsencrypt-apache in ./.local/share/letsencrypt/lib/python2.7/site-packages
Collecting ConfigArgParse from git+https://github.com/kuba/ConfigArgParse.git@python2.6-0.9.3#egg=ConfigArgParse (from -r /root/letsencrypt/py26reqs.txt (line 1))
  Cloning https://github.com/kuba/ConfigArgParse.git (to python2.6-0.9.3) to /tmp/pip-build-JknXHd/ConfigArgParse
Requirement already up-to-date: acme==0.1.0 in ./.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: setuptools in ./.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: python2-pythondialog>=3.2.2rc1 in ./.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: PyOpenSSL in ./.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: requests in ./.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: parsedatetime in ./.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: configobj in ./.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: pytz in ./.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: psutil>=2.1.0 in ./.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: six in ./.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: cryptography>=0.7 in ./.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: zope.interface in ./.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: zope.component in ./.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: mock in ./.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: pyrfc3339 in ./.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: python-augeas in ./.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt-apache)
Requirement already up-to-date: pyasn1 in ./.local/share/letsencrypt/lib/python2.7/site-packages (from acme==0.1.0->letsencrypt)
Requirement already up-to-date: ndg-httpsclient in ./.local/share/letsencrypt/lib/python2.7/site-packages (from acme==0.1.0->letsencrypt)
Requirement already up-to-date: werkzeug in ./.local/share/letsencrypt/lib/python2.7/site-packages (from acme==0.1.0->letsencrypt)
Requirement already up-to-date: idna>=2.0 in ./.local/share/letsencrypt/lib/python2.7/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: enum34 in ./.local/share/letsencrypt/lib/python2.7/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: ipaddress in ./.local/share/letsencrypt/lib/python2.7/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: cffi>=1.1.0 in ./.local/share/letsencrypt/lib/python2.7/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: zope.event in ./.local/share/letsencrypt/lib/python2.7/site-packages (from zope.component->letsencrypt)
Requirement already up-to-date: funcsigs in ./.local/share/letsencrypt/lib/python2.7/site-packages (from mock->letsencrypt)
Requirement already up-to-date: pbr>=0.11 in ./.local/share/letsencrypt/lib/python2.7/site-packages (from mock->letsencrypt)
Requirement already up-to-date: pycparser in ./.local/share/letsencrypt/lib/python2.7/site-packages (from cffi>=1.1.0->cryptography>=0.7->letsencrypt)
Installing collected packages: ConfigArgParse
  Found existing installation: ConfigArgParse 0.9.3
    Uninstalling ConfigArgParse-0.9.3:
      Successfully uninstalled ConfigArgParse-0.9.3
  Running setup.py install for ConfigArgParse
Successfully installed ConfigArgParse-0.9.3
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt --debug -vvv --apache --rsa-key-size 4096 --renew-by-default --hsts --redirect --agree-tos -m REMOVED -d REMOVED --text
2015-12-09 19:57:29,688:DEBUG:letsencrypt.cli:Root logging level set at 0
2015-12-09 19:57:29,689:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2015-12-09 19:57:29,689:DEBUG:letsencrypt.cli:letsencrypt version: 0.1.0
2015-12-09 19:57:29,690:DEBUG:letsencrypt.cli:Arguments: ['--debug', '-vvv', '--apache', '--rsa-key-size', '4096', '--renew-by-default', '--hsts', '--redirect', '--agree-tos', '-m', 'REMOVED', '-d', 'REMOVED', '--text']
2015-12-09 19:57:29,690:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2015-12-09 19:57:29,692:DEBUG:letsencrypt.cli:Requested authenticator apache and installer apache
2015-12-09 19:57:29,713:DEBUG:letsencrypt.plugins.disco:No installation (PluginEntryPoint#apache):
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 142, in prepare
    raise errors.NoInstallationError
NoInstallationError
2015-12-09 19:57:29,715:DEBUG:letsencrypt.display.ops:No candidate plugin
2015-12-09 19:57:29,716:DEBUG:letsencrypt.cli:Selected authenticator None and installer None
The apache plugin is not working; there may be problems with your existing configuration.
The error was: NoInstallationError()
```

**Comment by joohoi** [comment]
Seems like it's not able to find the executables. This is most likely due cron using more sparse env variables as opposed to the user (including PATH - variable) try setting them separately.

**Comment by linuxlurak** [comment]
Can you give me a hint? I put some apache env vars in my script. Perhaps not what you meant...
```
#!/bin/sh
export APACHE_RUN_USER=www-data
export APACHE_RUN_GROUP=www-data
# temporary state file location. This might be changed to /run in Wheezy+1
export APACHE_PID_FILE=/var/run/apache2/apache2$SUFFIX.pid
export APACHE_RUN_DIR=/var/run/apache2$SUFFIX
export APACHE_LOCK_DIR=/var/lock/apache2$SUFFIX
# Only /var/log/apache2 is handled by /etc/logrotate.d/apache2.
export APACHE_LOG_DIR=/var/log/apache2$SUFFIX

echo "" >> /var/log/letsencrypt/$1.log
echo "$(date): Certificate Renewal of $1">> /var/log/letsencrypt/$1.log
echo "-----------------------------------------------------------------">> /var/log/letsencrypt/$1.log
/root/letsencrypt/letsencrypt-auto --debug -vvv --apache --rsa-key-size 4096 --renew-by-default --hsts --redirect --agree-tos -m REMOVE -d $1 --text >> /var/log/letsencrypt/$1.log 2>&1
```
Same result. What env vars do i have to put where? Thanks for your help.

**Comment by joohoi** [comment]
You need to set your PATH - environment variable in that .sh file. I guess cron doesn't hold the same $PATH as your user does, so you'll need to add it manually.

**Comment by linuxlurak** [comment]
Thank you very much. Now it works. I did the following:
1. As user get your PATH-environment variable content by this: echo $PATH
2.Copy the content you get to your script and set the variable: PATH=CONTENT-YOU-GOT

So my working script looks like this:
```
#!/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
echo "" >> /var/log/letsencrypt/$1.log
echo "$(date): Certificate Renewal of $1">> /var/log/letsencrypt/$1.log
echo "-----------------------------------------------------------------">> /var/log/letsencrypt/$1.log
/root/letsencrypt/letsencrypt-auto --apache --rsa-key-size 4096 --renew-by-default --hsts --redirect --agree-tos -m EMAIL.TLD -d $1 --text >> /var/log/letsencrypt/$1.log 2>&1
```

My cron job (edit root crontab by running "crontab -e" as root) to run the renewal-script every two months looks like this:
```
* * * */2 * /root/letsencrypt-renewal.sh DOMAIN.TLD
```

**Comment by linuxlurak** [comment]
Last question: Is there already a working fully automated renewal so my script could be obsolete?

**Comment by joohoi** [comment]
I don't think there is. The configurations vary so much that it's a lot of work and testing.

**Comment by linas** [comment]
seems to be a common problem that bites lots of people.  At least, that's what a google search suggests.

**Comment by bmw** [comment]
@linas,

1. What OS are you using?
2. How did you install Certbot?
3. Do you have a log of the issue (feel free to redact domain names and e-mail addresses if you prefer)?

**Comment by linas** [comment]
Hi,
1. Ubuntu 14.04.4 LTS
2. Don't recall ... followed instructions on website
3. The general issue is essentially the same as that posted above; see also
https://community.letsencrypt.org/t/fails-when-running-cronjob/8207
https://community.letsencrypt.org/t/letsencrypt-renew-not-working-with-cronjob-manually-it-works/16738

I am assuming that 100% of it is explainable by the missing/empty PATH environment variable in cron.

**Comment by linas** [comment]
Here are relevant extracts from syslog:
```
2016-06-12 04:33:05,786:DEBUG:letsencrypt.plugins.disco:No installation (PluginE
ntryPoint#apache): 
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsenc
rypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsenc
rypt_apache/configurator.py", line 152, in prepare
    raise errors.NoInstallationError
NoInstallationError
2016-06-12 04:33:05,805:DEBUG:letsencrypt.display.ops:No candidate plugin
2016-06-12 04:33:05,805:DEBUG:letsencrypt.display.ops:No candidate plugin
2016-06-12 04:33:05,805:DEBUG:letsencrypt.cli:Selected authenticator None and installer None
```
and more error messages follow, but the above seems to be the only relevant one.

**Comment by linas** [comment]
The problem can be reproduced at the command line by saying
```
export PATH=/usr/bin:/sbin:/bin
/root/.local/share/letsencrypt/bin/letsencrypt renew --apache --renew-by-default  --no-self-upgrade --no-redirect --text --agree-tos --dry-run
```
which will lead to the failure, whereas 
```
export PATH=/usr/bin:/usr/sbin:/sbin:/bin
```
is enough to get it to work, it seems.  Looking at the contents of `/usr/sbin`, I notiice that `apache2` is there ... I don't see how anything else in that directory would matter. and this makes sense ... the error is from `python2.7/site-packages/letsencrypt_apache/configurator.py` so, without /usr/sbin, its not finding apache2 and its croaking as a result.

**Comment by joohoi** [comment]
I think this should be added to documentation. It's distribution specific, but certbot site howto would be able to guide people forward. I don't think there's a good way to mitigate this at certbot code, we should assume that OS configuration is sane to begin with.

All in all, this is mostly a shortcoming in distribution specific default cron configuration.

**Comment by linas** [comment]
Yes, a documentation fix would be good, although I'm not sure that the idea of using cron is documented anywhere -- its just one of those tricks all sysadmins know, and do reflexively for this.  

The idea that `letsencrypt_apache/configurator.py` is explicitly searching for the `apache2` daemon is what catches one off-guard. Its not entirely clear to me why this is even needed; I guess its somehow used to compute a path to locate where the certs should be placed? Is the check for `apache2` really needed, or is it just someone being excessively strict?

**Comment by linas** [comment]
As to it being a "distribution issue" -- it is following the FHS-- here: https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard and so it seems like checking `/usr/sbin` for `apache2` seems like an entirely reasonable thing to do: essentially all distros are going to adhere to this standard -- this is the point of standardization.  So blaming it on the distro doesn't quite seem right.

**Comment by joohoi** [comment]
Certbot actually needs apache2 for various tasks. It needs it to validate the configuration to be able to back off and restore the original configuration for user if there's a problem with autoconfigured parts. It also needs to restart apache2 to be able to perform the validation, and again to activate the new configuration and new certificate.

I think it's a distribution issue, because distribution is responsible of default paths that are available for cron through $PATH, and also controls the installation paths for software, apache2 in this case. So as I see it, distribution should either install software (in this case apache2) to a path already available to cron, or append the new installation path to the default $PATH.

**Comment by linas** [comment]
Hmm. Maybe.  If you feel that the distro really is the one at fault, and not your s/w -- then open a bug report.  I can't really be a go-between between you and the distro, relaying who said what to whom -- this needs to be a direct conversation between you and them (or possibly between the packager and them, as I assume that someday, there will be debs and rpms for this) -- I've located the core bug: a lack of `/usr/sbin` in `$PATH`, I can't do more.

**Comment by bmw** [comment]
So there are a few actions we can take here, none of which are mutually exclusive:

1. Make the error messge raised more useful by explicitly stating the executable we were looking for and could not find. We could also mention potential problems with `PATH` if we want.
2. File a bug against relevant distros who don't have the relevant Apache binaries available through `PATH` in cron.
3. Search `/usr/sbin` for binaries if it's not included in `PATH`.

I think we should do 1 and maybe 2. We could do 3 but it's an ugly hack.

**Comment by paour** [comment]
Note that on Debian, merely adding the `PATH=<snip>:/usr/sbin/` line to crontab didn't work: I had to change my weekly cron line to `export PATH=$PATH && certbot renew --quiet` for the path to be correctly propagated all the way to the apache plugin.

**Comment by bigretromike** [comment]
Debian 8.5 also have this problem.

@paour so adding "export PATH=$PATH && " before certbot renew in cron will do the trick?

**Comment by paour** [comment]
@bigretromike I thought so at first, but I've now switched to using `30 2 * * 1 export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin && certbot renew --quiet`.

**Comment by bigretromike** [comment]
I just made script 
```
#!/bin/bash

PATH=$PATH:/usr/sbin
export PATH && certbot renew --quiet
```

I dont think that PATH will change dramaticly on server so your solution is probably better :-) Thanks

**Comment by katopz** [comment]
Hi guys,

Why I didn't see this `export PATH` mention in [doc](https://certbot.eff.org/#ubuntutrusty-nginx)?
And how can I print log via `certbot` ? [doc](https://certbot.eff.org/docs/search.html?q=log&check_keywords=yes&area=default) didn't tell me anything.
And why you guys didn't print log at all? How you ensure it work without log?

Thanks

**Comment by bmw** [comment]
> Why I didn't see this export PATH mention in doc?

Because we've solved this issue in Certbot 0.9.0 by manually checking a few directories.

> And how can I print log via certbot ? doc didn't tell me anything.
> And why you guys didn't print log at all? How you ensure it work without log?

You're right we say very little about our logs in our documentation. I created #3898 to track this issue. Certbot stores all of its logs in `/var/log/letsencrypt` (unless you changed the directory with the `--log-dir` option).

Additionally, if you're running Certbot without the `--quiet` flag, it prints a lot of information about what it's doing to the terminal. If you add the `--quiet` flag, it will notify you if an error occurs. This flag is useful when running Certbot non-interactively with something like `cron` or `systemd`.

**Comment by tinodj** [comment]
Hi, how can I check which Certbot version I have installed? 

I expirience this problem still with:
Ubuntu 16.04
letsencrypt 0.4.1

**Comment by bigretromike** [comment]
@tinodj not included in `-h` but its `certbot --version`

**Comment by tinodj** [comment]
@bigretromike I thought that letsencrypt and certbot have different versions. I did check the letsencrypt version and reported in the first post. If that is also my certbot version, then it is clear why the problem is still there. Nonetheless, why Ubuntu 16.04 do not have newer version of certbot?

**Comment by bigretromike** [comment]
for 16.04 its python-letsencrypt-apache and its old;
You can always install newer version yourself or move to newer ubuntu

**Comment by tinodj** [comment]
@bigretromike Thanks. 16.04. is not that old it is not even full year. But yes, I can install myself newer version.

**Comment by jmurphyau** [comment]
cron does allow variables at the top of the config, e.g:

```
[root@ip-10-249-77-171 ~]# crontab -l
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/aws/bin:/usr/bin:/root/bin

0 8,20 * * * /usr/local/bin/certbot-auto renew
```
