### ISSUE TITLE
Renewal of certificate ignores --cert-path

### ISSUE THREAD

**Issue by philpennock** [certbot/certbot#1835]
During the closed beta, I created a certificate for use by a non-webserver using letsencrypt-auto; the `--cert-path` option was honoured.  When renewing (during open beta), the `--cert-path` was ignored.

Is this semantic confusion over the interaction between `certonly` and `--cert-path` during renewal?  I expected that locations where artifacts were placed during install would also be touched during update.  Anything else I should be doing?

I've obfuscated only the closed-beta URL.

```
./letsencrypt-auto certonly \
    --server $closed_beta_url --agree-dev-preview \
    -a standalone -d demo.nats.io --cert-path /etc/nats/tls
```

Renewal was with the same command but with `--server` and `--agree-dev-previews` options dropped.

Notably, the original `--cert-path` has generation numbers in the filenames for the placed certs, the same generation numbers which were updated by this renewal.

I would naively expect the contents of `--cert-path` to look very like the contents of `/etc/letsencrypt/live/demo.nats.io` except with files instead of symlinks.

**Comment by bmw** [comment]
Did you use a custom CSR during closed beta? When used with `certonly`, `--cert-path` currently only works if `--csr` was specified on the command line. I believe this has been the case since before closed beta began and is still the case today.

**Comment by philpennock** [comment]
No, the command-line used was as above and the `--cert-path` was created.

Git reflog says that the repo was at commit 6fbcebd when I created the initial cert.

**Comment by fresheneesz** [comment]
This seems to still be a problem I saw this on centos 6.5. `certbot-auto --version` gives me `letsencrypt 0.9.1`.

**Comment by zeropopular** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mrniceguyzero@gmail.com
    Domain thezeroworld.com has exceeded the max emails per hour (7/7 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:33625)
	by node87.certushost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-7f84-zero=thezeroworld.com@sgmail.github.com>)
	id 1btn6T-0007if-GF
	for zero@thezeroworld.com; Mon, 10 Oct 2016 22:47:41 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=InUgMhjuBsSO5Hnh3Qsxm3BWrW4=; b=tQGDDjlPP9eEYwp/
	68X2CSuJVkBzzvamUoH8hOeshzbcHqJeOGgk+LKOGZdPNDqzJlY/FjnVbZ/GjpVT
	1BeC3sdRkqtHS2S0KRCGGr1O8yRXNQuZTjgMLpznpC9VI2nodO6LbScEwVDlZQMH
	NX4OTkVUxt44ksW863eQcWwgzi4=
Received: by filter0929p1mdw1.sendgrid.net with SMTP id filter0929p1mdw1.7038.57FC52A424
        2016-10-11 02:47:00.786175592 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id PI5vXpYtRF2fYQWrWuoZsg
	for <zero@thezeroworld.com>; Tue, 11 Oct 2016 02:47:00.817 +0000 (UTC)
Date: Mon, 10 Oct 2016 19:47:00 -0700

**Comment by bmw** [comment]
@fresheneesz, the docs say:
```
  --cert-path CERT_PATH
                        Path to where cert is saved (with auth --csr),
                        installed from or revoked. (default: None)
```
We should update this help description, but `auth` is the old name of `certonly`. In other words, `--cert-path` can only be used to control where the certificate is saved when using a custom CSR and the `certonly` subcommand. We hope to change this in the future, but it is the state of the client right now.

**Comment by fresheneesz** [comment]
@bmw Hmm a couple things:

1. In that case, what certbot-auto should do is error with a messaging informing the user of that requirement (--csr and certonly). I was actually using certonly, but the short text "with auth --csr" didn't hold any meaning to me, so I ignored it. If you put a message in the CLI, then you don't even need to mention that requirement in the docs - the cli will tell you. 

2. Why should you  need to pass the --csr option? I only want to control where the resulting certificate is saved, not control what signing request is used. It should be possible to specify where cerbot saves the cert even if you allow certbot to create new keys (and thus a new certificate signing request) for you.

**Comment by bmw** [comment]
So let me start by saying I agree with you that we should support what you were trying to do. It's just that in the current stage of Certbot, which is still in beta and only worked on by a small team of developers.

1. I agree this is better, however, what we should really do here is support the functionality you describe in 2. docs is worse than CLI errors which is worse than supporting the desired functionality.
2. There is no reason you need to other than it needing to be implemented.

If you're so inclined, we'd welcome a pull request adding this functionality.

**Comment by fresheneesz** [comment]
Gotcha. Thanks for the info. I've got my hands full at the moment, but maybe I'll come back to this if I find time.
