### ISSUE TITLE
AWS IAM/ELB Installation Support

### ISSUE THREAD

**Issue by rnhurt** [certbot/certbot#1839]
I was looking through the plugin examples and I think it might not be too difficult to create an Installer that pushes certs to AWS.  There is an [API call to upload certs to IAM](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/ssl-server-cert.html#upload-cert) and another one to [update the ELB config to use the new cert](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/elb-update-ssl-cert.html#us-update-lb-SSLcert-cli).  Both of these API calls are available in the AWS Python SDK and should be pretty straightforward to execute.

Does this look feasible to you?  I'm not a Python guy (Ruby is more my thing) but is this something that I might be able to handle, with a little help from you?  :smile:

**Comment by pde** [comment]
If you want to try a full-on plugin, you can read the Plugin Architecture docs at https://letsencrypt.readthedocs.org/en/latest/contributing.html#plugin-architecture , then look at a simple plugin like webroot.py for an example implementation.

Note that another way to get certs from behind an ELB is to serve an HTTP redirect from `.well-known/acme-challenge/` to one of the boxes in particular (perhaps using its amazon public hostname) and then run the webroot plugin on that box.

So you could even make a plugin modelled on/inheriting from webroot.py that does that!

**Comment by pde** [comment]
That would work from behind any TLS load balancer, not just ELB.

**Comment by pde** [comment]
I guess I was getting a little over-excited there.  We can't really serve that redirect from one client endpoint under normal circumstances.

**Comment by pde** [comment]
Related: #1419

**Comment by rnhurt** [comment]
I think there is now a [Route53 plugin](https://certbot-dns-route53.readthedocs.io/en/stable/) which makes this problem easier to deal with.
