### ISSUE TITLE
Update fails silently if outbound connection is blocked

### ISSUE THREAD

**Issue by DevCybran** [certbot/certbot#1843]
letsencrypt-auto silently fails to update (on first startup) if no outbound connection can be established (for example because an outbound firewall is blocking the requests).

The only thing to be seen is

`Updating letsencrypt and virtual environment dependencies...`

before dropping back to a shell. Please add appropriate error messages in case a connection cannot be established, otherwise troubleshooting may become very hard.

**Comment by sydneyli** [comment]
If `certbot-auto` can't update, now it'll spit out a warning as of #2875, but continue running the outdated version of Certbot.

Feel free to bug me to re-open this issue if you think the current error messaging isn't enough!
