### ISSUE TITLE
ImportError: cannot import name _compare_digest

### ISSUE THREAD

**Issue by albertotb** [certbot/certbot#1845]
When running `./letsencrypt-auto` I get this error:

```
Traceback (most recent call last):
  File "/home/alberto/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from letsencrypt.cli import main
  File "/home/alberto/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 30, in <module>
    from letsencrypt import client
  File "/home/alberto/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 20, in <module>
    from letsencrypt import continuity_auth
  File "/home/alberto/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/continuity_auth.py", line 9, in <module>
    from letsencrypt import proof_of_possession
  File "/home/alberto/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/proof_of_possession.py", line 5, in <module>
    from cryptography import x509
  File "/home/alberto/.local/share/letsencrypt/lib/python2.7/site-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "/home/alberto/.local/share/letsencrypt/lib/python2.7/site-packages/cryptography/x509/base.py", line 15, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/home/alberto/.local/share/letsencrypt/lib/python2.7/site-packages/cryptography/x509/extensions.py", line 18, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "/home/alberto/.local/share/letsencrypt/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py", line 7, in <module>
    import hmac
  File "/home/alberto/anaconda/lib/python2.7/hmac.py", line 8, in <module>
    from operator import _compare_digest as compare_digest
ImportError: cannot import name _compare_digest
```

I tracked it down to this issue http://stackoverflow.com/questions/26535043/python-flask-error-importerror-cannot-import-name-compare-digest. In fact, if I do

```
source ~/.local/share/letsencrypt/bin/activate
python --version
```

I get that the Python version is 2.7.6. However, outside that virtualenv my Python version is 2.7.11 (Anaconda dist). However `letsencrypt-auto` is creating a virtualenv with my system Python version (from `/usr/bin/python`). After creating the virtualenv, as it can be seen in the log, correctly tries to import the newer `hmac.py` from Anaconda (Python 2.7.11) and the mismatch occurs. How can I fix this?

**Comment by bmw** [comment]
What OS are you running?

**Comment by albertotb** [comment]
@bmw 

```
alberto@febris ~ $ uname -a 
Linux febris 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by greatbn** [comment]
@albertotb  I have same problem with you. I have updated python to 2.7.10 but when
```
source ~/.local/share/letsencrypt/bin/activate
python --version
```
It returns 2.7.6.
have you solved it yet?

**Comment by garethellis36** [comment]
Same error here. I tried running `letsencrypt-auto` with Python at 2.7.6 but got `InsecurePlatformWarning` as per #1883. I upgraded Python to 2.7.10 and now get the above errors. `python --version` returns 2.7.10 normally but returns 2.7.6 when run from source context as per @greatbn

**Comment by albertotb** [comment]
@greatbn @garethellis36 I haven't solved it yet. I suspect that letsencrypt creates de virtualenv with the system Python instead of the new version. In Ubuntu 2.7.6 it's the last version in the repos and for ```hmac.py``` to work you need at least 2.7.7, so no luck there.

If you are running another dist and upgraded your system Python it may be worth a try to remove the ```.local/share/letsencrypt``` folder and run it again to force it to create a new virtualenv with hopefully the new version.

**Comment by devster31** [comment]
@albertotb First you could run a `which virtualenv` to see where it was installed virtualenv, since it uses the interpeter that it was installed with by default and it's possible anaconda installation messes with python paths. Then you could try manually recreating the virtualenv with `virtualenv --no-site-packages --always-copy` and `--python=` with the full path to the anaconda interpreter instead of the system one.
@garethellis36, @albertotb If you upgraded your system python after creating the virtualenv you need to recreate the virtualenv with the new version of the interpreter, you could try deleting the folder and running `./letsencrypt-auto` again.

**Comment by garethellis36** [comment]
@devster31 sorry, which folder should I delete? The whole `letsencrypt` folder or something else?

**Comment by devster31** [comment]
The virtualenv folder, if you just ran `./letsencrypt-auto` the directory that contains the virtualenv should exist in `~/local/share/letsencrypt`, this directory is the one that should be deleted. If you want details [you can find something more here](https://community.letsencrypt.org/t/uninstalling-letsencrypt/2517).

**Comment by garethellis36** [comment]
That solved it, thanks!

**Comment by schoen** [comment]
I'm going to regard this as closed, but if anyone is still experiencing any related errors with current versions of `certbot-auto`, please do open a new issue and indicate the associated OS version, Python version, and `certbot-auto` version.

Thanks!
