### ISSUE TITLE
Nginx extended SSL configuration

### ISSUE THREAD

**Issue by riyadhalnur** [certbot/certbot#1852]
There are a few other recommended configurations when configuring an NGINX server for server like adding the `ssl_protocols`, `ssl_session` and so on.

I started working on extending the `Nginx` plugin already to add these directives when configuring the server but tests are failing due to the parser adding directives at `0` index when in reality, it should be appended after the `ssl_certificate` and `ssl_certificate_key` fields respectively.

I'm still looking into a way to get around this. The Nginx issue 810 has been closed with a `wontfix` label which makes matters a little troubling.

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.
