### ISSUE TITLE
LE requiers ServerName directive to be all lowercase 

### ISSUE THREAD

**Issue by dClauzel** [certbot/certbot#1858]
When using an apache config containing `ServerName Damien.Clauzel.eu`, LE fails to identify the VirtualHost. Renaming it to `ServerName damien.clauzel.eu` solves the problem.

LE should handle this better, by supporting ServerName with mixed cases, or by giving an explicit error message.

**Comment by joohoi** [comment]
This is very old issue, and I verified it as fixed somewhere along the way. Closing it as fixed.
