### ISSUE TITLE
Root certificate is included in fullchain.pem for nginx ssl_certificate

### ISSUE THREAD

**Issue by miki725** [certbot/certbot#1872]
As per [docs](http://letsencrypt.readthedocs.org/en/latest/using.html#where-are-my-certificates) `fullchain.pem` includes all certificates root, intermediate and domain certificate. It is also stated that this file can be used for nginx `ssl_certificate`. However as per nginx docs it only states that client and intermediate certs should be included:

> Specifies a file with the certificate in the PEM format for the given virtual server. If intermediate certificates should be specified in addition to a primary certificate, they should be specified in the same file in the following order: the primary certificate comes first, then the intermediate certificates. A secret key in the PEM format may be placed in the same file.

That makes sense since root cert should already be present in the user trust-store. Also SSL Labs frowns upon doing that. Here is a quote from one of their [support pages](https://community.qualys.com/docs/DOC-1931):

> **Certificate chains that are too long**; Sites often include more certificates in the handshake than necessary. Of those, most include one extra certificate, and that is the actual trusted root certificate (which browsers already have in their storage). This last certificate is not needed for the validation process. Having an additional certificate in the chain wastes bandwidth and decreases overal performance slightly.

Sorry Im not familiar of the exact RFC which specifies all of this so cant point to definitive reference stating which certs should be sent to the user.

From my previous TLS configurations, I never included root cert and it seems to work as expected.

So my actual GH issue. Can lets encrypt generate a new file which will not include root cert for use with nginx.

**Comment by osirisinferi** [comment]
The docs are wrong IMO. Unless there has been a commit which has changed the source code which generates chain.pem since I've generated my certificate.

My chain.pem **only** contains the X1 Intermediate certificate and fullchain.pem **only** contains the leaf and intermediate certificate. No root certificate is to be found in those two PEM files.

**Comment by miki725** [comment]
Thanks @osirisinferi. Ill try to test it out. If docs are wrong, I Ill try to send PR correcting them.

**Comment by schoen** [comment]
In the current version of the docs, it doesn't state that a root certificate is included (but we'd still be happy to have a PR rephrasing the description of `fullchain.pem` if anyone finds it confusing).

Thanks!

**Comment by osirisinferi** [comment]
@RalphCorderoy It's actually a cross-signed version of a root certificate, **acting as an intermediate certificate**. See for more info: https://letsencrypt.org/2020/12/21/extending-android-compatibility.html
