### ISSUE TITLE
Error creating new authz

### ISSUE THREAD

**Issue by frutality** [certbot/certbot#1886]
I've installed letsencrypt without any issues. 
Configured nginx to serve content from /.well-known/acme-challenge/ (double-checked - it seems fine).

./letsencrypt-auto certonly --webroot -w /tmp/letsencrypt-auto -d www.metalhail.ru -d metalhail.ru --verbose

/var/log/letsencrypt/letsencrypt.log: http://pastebin.com/FhEh4W1E

It seems to me like POST to https://acme-v01.api.letsencrypt.org/acme/new-authz returns 500 code but I'm not sure why.

**Comment by pde** [comment]
That would be a [boulder](https://github.com/letsencrypt/boulder) bug, not a client bug.

**Comment by cpu** [comment]
@pde Another candidate for closing. I think it's too far in the past for Boulder to troubleshoot or match to a maintenance window.
