### ISSUE TITLE
Installing in OSX with conda?

### ISSUE THREAD

**Issue by alexweissman** [certbot/certbot#1889]
I'm getting stuck when I try to install letsencrypt in OSX.  It appears to have a dependency on `virtualenv` as an environment manager, but unfortunately my python environment uses `conda` instead (an alternative to `virtualenv`).  Is there a way to get this to work in OSX without `virtualenv`, or alternatively, is there a distribution that will use an environment managed by `conda` instead?

Here are the last few lines of output when I tried to run `./letsencrypt-auto` with the `--debug` flag, when it tries to install `virtualenv`:

```
...
...

🍺  /usr/local/Cellar/dialog/1.2-20130928: 7 files, 664K, built in 13 seconds
virtualenv Not Installed
Installing with pip

WARNING: using virtualenv with Anaconda is untested and not recommended.
    We suggest using the conda command to create environments instead.
    For more information about creating conda environments, please see:
         http://docs.continuum.io/conda/examples/create.html

Proceed (y/n)? n
```

Honestly, all I really want for now is to get a CRT that I can upload into a shared hosting account through cpanel (until I have a chance to set up my own VPS).

**Comment by stopspazzing** [comment]
Wow, you would have to manually make an environment and set it up, that sounds like a huge pain. 2 options, recommend an option to use Anaconda or virtualenv when installing letsencrypt or yolo it and just install both. 

OR you could boot a live cd like Linux Mint, install git, and just run everything there, get the keys upload them and save them locally then go about your business for 3 months.

**Comment by alexweissman** [comment]
Yeah, I'll probably end up going the VirtualBox route - just wanted to make sure I wasn't missing anything obvious.  Also, I know @dantman wanted to see better support for OSX (#1437), so I thought I'd mention this issue.

Hopefully I'll have a VPS Linux box up and running in 3 months, and it won't be an issue (for me) anymore.

**Comment by stopspazzing** [comment]
Hopefully shared hosting providers will get the crap together and support it out of the box. ;)

**Comment by dantman** [comment]
Shared hosing users shouldn't need to continually run cli commands to keep certs up to date. So I do agree with you that hosting providers should support lets encrypt themselves.

However my use case for OSX support was different. So I still think proper support for the various OSX configurations might be worthwhile for other users with either @alexweissman's conda quirk or my quirk of using MacPorts.

My use case was [Pagekite](https://pagekite.net/). At least when run on your own domain through a custom CNAME or running your own instance.

The pagekite+letsencrypt combination would allow development to happen on a local machine, with the result available on a public domain (and hence compatible with webhooks and other parts of development that don't work on localhost), and HTTPS could be tested.

**Comment by alexweissman** [comment]
Well I was able to successfully generate my CRT, private key, and CA bundle using VirtualBox+Ubuntu 14.04.  So, yaay!

There are a few caveats though, which made it a suboptimal experience:
- Apparently you can't copy-paste between VirtualBox and OSX (even after following the instructions that supposedly enable this feature).  So if you manually generate a cert, you need to find some other way to securely transfer the cert from the virtual environment to your server (encrypt+email, local network share, etc).
- By default, it would seem that the certs are placed in a folder `etc/letsencrypt/live` that is not accessible by regular user accounts.  I guess this makes sense for a shared environment, but for a VirtualBox it doesn't really matter.  Is there a configuration option to choose where the certs are saved?
- The `.pem` files generated by Let's Encrypt seem to be treated by Ubuntu as symlinks.  This means I can't just zip the files into an encrypted archive, because Ubuntu will just try to zip the links.  To get the actual text, I had to individually open each `.pem` file and then copy the contents into a text file.  It would be cool if `letsencrypt` had a flag to generate plain text files instead.

An easy way to do this natively on OSX would be good.  Even better, would be a web app (served over https of course) that just does all of this for me on Let's Encrypts' own servers - I imagine something where I enter my email address, get the acme challenge sent to me, and then another button I can click to verify my domain and receive the certificates.  This app could also email me when my cert is expiring soon, and provide an interface for easily renewing (and also encourage me to install `letsencrypt` on my server so I can have it done automatically).

This type of interface, I think, would really help push up the implementation rate for `https` - especially when you consider how many web "developers" are out there on shared hosting accounts, who have no clue how to use a CLI.

**Comment by coolaj86** [comment]
There's now a node version available:

https://github.com/Daplie/node-letsencrypt-cli

```bash
# Install node.js
curl -L bit.ly/iojs-min | bash

# Install LetsEncrypt
npm install -g letsencrypt-cli

# get certs
letsencrypt certonly \
  --agree-tos --email john.doe@example.com \
  --standalone \
  --domains example.com,www.example.com \
  --server https://acme-staging.api.letsencrypt.org/directory \

# take a look
ls ~/letsencrypt/etc/live
```

**Comment by blootsvoets** [comment]
The only way to get any kind of virtualenv on my hosting provider is to use miniconda. The hosting provider uses a limited Linux VM based on Red Hat. There are no build tools installed, so the build of cffi fails. Likewise, I cannot install npm there. If certbot had a conda package, it would be far easier to install. Does the linux label also apply?

**Comment by cowlicks** [comment]
@blootsvoets conda provides some build tools, like gcc. You could try installing these with conda.

Do you not have sudo access?

**Comment by blootsvoets** [comment]
@cowlicks I switched to a PHP solution: https://github.com/kelunik/acme-client. This also does not have the next obstacle I ran into with certbot: the writable `/etc/letsencrypt` directory.

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.
