### ISSUE TITLE
Debugging OSX+Docker-Machine+Letsencrypt+Pagekite

### ISSUE THREAD

**Issue by dantman** [certbot/certbot#1894]
I'm trying to get letsencrypt working in my development setup. In which my OS is OSX, I forward two local ports to my server using pagekite to expose them to the internet. And letsencrypt is run using docker and docker-machine.
- Pagekite runs publicly on my server.
  - It is bound to the secondary IP which the dns for test1.vm.dev.otakuseek.net points to.
  - It is configured to listen on 80 and 443 and forward http and https (using sni)
- The pagekite client runs on my computer.
  - It is configured to expose localhost:3000 as http and localhost:3001 as https to my pagekite server.
- docker and docker-machine are freshly installed through Docker Toolbox
- letsencrypt is run with a variation of the docker command in letsencrypt's manual
  - `-p 3001:443 -p 3000:80` are used for ports
  - I've tried variations on the letsencrypt command incl. swapping the port order (ie: `-p 443:3001` just in case), using `certonly` instead of `auth`, and including `--standalone`.
  - I later changed the `-v` entries to `-v "/Users/daniel/.letsencrypt/etc:/etc/letsencrypt" -v "/Users/daniel/.letsencrypt/lib:/var/lib/letsencrypt"` to ensure there were no permission issues. As docker/docker-machine cannot be trivially run with sudo/as root.

When running the command I end up with this type of error:

``` console
Daniels-MacBook-Air:output daniel$ docker run -it --rm -p 3001:443 -p 3000:80 --name letsencrypt -v "/Users/daniel/.letsencrypt/etc:/etc/letsencrypt" -v "/Users/daniel/.letsencrypt/lib:/var/lib/letsencrypt" quay.io/letsencrypt/letsencrypt:latest auth --standalone -d test1.vm.dev.otakuseek.net
# ...
Failed authorization procedure. test1.vm.dev.otakuseek.net (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Failed to connect to host for DVSNI challenge

IMPORTANT NOTES:
 - If you lose your account credentials, you can recover through
   e-mails sent to d@danf.ca.
 - The following 'urn:acme:error:connection' errors were reported by
   the server:

   Domains: test1.vm.dev.otakuseek.net
   Error: The server could not connect to the client to verify the
   domain
 - Your account credentials have been saved in your Let's Encrypt
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Let's
   Encrypt so making regular backups of this folder is ideal.
Daniels-MacBook-Air:output daniel$ docker run -it --rm -p 3001:443 -p 3000:80 --name letsencrypt -v "/Users/daniel/.letsencrypt/etc:/etc/letsencrypt" -v "/Users/daniel/.letsencrypt/lib:/var/lib/letsencrypt" quay.io/letsencrypt/letsencrypt:latest certonly --standalone -d test1.vm.dev.otakuseek.net
Failed authorization procedure. test1.vm.dev.otakuseek.net (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Failed to connect to host for DVSNI challenge

IMPORTANT NOTES:
 - The following 'urn:acme:error:connection' errors were reported by
   the server:

   Domains: test1.vm.dev.otakuseek.net
   Error: The server could not connect to the client to verify the
   domain
```

I've done some extra debugging and verification of my own:
- I exposed a dummy http server on 0.0.0.0:3000 and confirmed that visiting my domain over http is forwarded to that dummy server
- I created a self-signed certificate and exposed a dummy https server on 0.0.0.0:3001 and confirmed that visiting my domain over https is forwarded to that dummy server

So the pagekite portion of this is working fine.

**Comment by schoen** [comment]
I hope that you've managed to figure something out in the intervening time and I'm sorry that nobody has followed up on this issue.

This kind of discussion is probably best handled at the Community Forum at https://community.letsencrypt.org/ rather than on GitHub because a much wider variety of people monitor it and are willing to discuss and help debug things like Docker configurations.

Thanks!
