### ISSUE TITLE
GitHub IRC notifications

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#191]
@jdkasten, could you please set up [GitHub IRC notification service](https://github.com/letsencrypt/lets-encrypt-preview/settings/hooks/new?service=irc)? :)

**Comment by jdkasten** [comment]
The link is broken for me, but I will look it up.

**Comment by kuba** [comment]
Travis notifications added thanks to @jdkasten #192

**Comment by jdkasten** [comment]
Still don't have admin rights to the repo... when I do I will come back and figure this out.  (I would also like to add coveralls)

**Comment by jdkasten** [comment]
I now have admin rights... I will switch out Travis notifications and put in GitHub notifications.

**Comment by jsha** [comment]
Closing out as obsolete.
