### ISSUE TITLE
SSLCertificateChainFile not added, config_changes states that it was

### ISSUE THREAD

**Issue by ghormoon** [certbot/certbot#1912]
I've run ./letsencrypt-auto --apache -d domain.tld, it correctly found the virtualhost and changed paths in SSLCertificateFile and SSLCertificateKeyFile, didn't touch SSLCACertificateFile, and also didn't add any SSLCertificateChainFile.
runing ./letsencrypt-auto config_changes shows that it set SSLCertificateFile, SSLCertificateKeyFile, SSLCertificateChainFile which is inconsistent with what happened.
may be related to https://github.com/letsencrypt/letsencrypt/issues/1723

**Comment by ghormoon** [comment]
I've retried it with example vhost, attached old.txt (before letsencrypt) and new.txt (after installed certificate with --apache)
config_changes states:

    Thu Dec 17 10:23:19 2015 
    -- Deployed Let's Encrypt Certificate -- 
    Changed vhost at /etc/apache2/sites-available/900-xxx-tld.conf with 
    addresses of *:443 
    SSLCertificateFile /etc/letsencrypt/live/ourcloud.cz/fullchain.pem 
    SSLCertificateKeyFile /etc/letsencrypt/live/ourcloud.cz/privkey.pem 
    SSLCertificateChainFile /etc/letsencrypt/live/ourcloud.cz/chain.pem 
    
    Affected files:  
    /etc/apache2/sites-available/900-xxx-tld.conf

[old.txt](https://github.com/letsencrypt/letsencrypt/files/65175/old.txt)
[new.txt](https://github.com/letsencrypt/letsencrypt/files/65176/new.txt)

**Comment by pde** [comment]
Are you still experiencing this after letsencrypt 0.1.1 was released? (release was Tuesday evening SF time last week, almost exactly when you were filing this bug)

**Comment by pde** [comment]
Actually, I'm sorry, I was misreading your bug report.  I believe your Apache config is as intended per #1423.  The use of fullchain.pem in the CertificateFile directive makes CertificateChainFile unnecessary as of Apache 2.4.8 or later:

https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslcertificatefile

So the issue is that config_changes isn't recording the change correctly.  @ArchimedesPi, would you be interested in looking into this?

**Comment by ghormoon** [comment]
I can confirm that the fullchain.pem works correctly without the SSLCertificateChainFile. config_changes says it added it though, so there seems to be the issue - it should show what it really done so it doesn't puzzle someone who tries to use it to fix/revert/verify the changes.

**Comment by ArchimedesPi** [comment]
@ghormoon what version of apache are you on?

**Comment by ghormoon** [comment]
2.4.10-10+deb8u3 from debian jessie repos, so it's ok that the chain is not used, it's only "logged" wrong.

**Comment by joohoi** [comment]
This is an very old issue and a lot has been changed in certbot-apache since then. I'm very confident that this issue has been solved. If this is not the case, feel free to comment here and we'll reopen the issue.
