### ISSUE TITLE
Set upgrade-insecure-requests where we can do so safely

### ISSUE THREAD

**Issue by pde** [certbot/certbot#1931]
This will be a significant usability win for users who are facing mixed content situations.

**Comment by pde** [comment]
Turns out the spec/implementations have made this [problematic to enable](https://isnot.org/mixed-uir), so it's not really something we can do unless that changes :(

**Comment by schoen** [comment]
As @pde indicated at the time that we probably can't do this, I'm going to close this. We could open a new issue to track CSP-related security enhancement options.

(It doesn't seem like our users have been asking for this, and maybe it's sort of collaterally handled in a large but random minority of cases by HSTS and HTTPS Everywhere?)
