### ISSUE TITLE
Improve error messages when failing to parse CSR

### ISSUE THREAD

**Issue by nileshtrivedi** [certbot/certbot#1935]
I'm trying to run "letsencrypt-auto certonly --csr mydomain.csr":

('asn1 encoding routines', 'ASN1_CHECK_TLEN', 'wrong tag'), ('asn1  │  
  │ encoding routines', 'ASN1_ITEM_EX_D2I', 'nested asn1 error')]        │  
  │ Traceback (most recent call last):                                   │  
  │   File                                                               │  
  │ "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/le │  
  │ tsencrypt/crypto_util.py", line 225, in _get_sans_from_cert_or_req   │  
  │     cert_or_req = load_func(typ, cert_or_req_str)                    │  
  │   File                                                               │  
  │ "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/Op │  
  │ enSSL/crypto.py", line 2380, in load_certificate_request             │  
  │     _raise_current_error()                                           │  
  │   File                                                               │  
  │ "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/Op │  
  │ enSSL/_util.py", line 48, in exception_from_error_queue              │  
  │     raise exception_type(errors)                                     │  
  │ Error: [('asn1 encoding routines', 'ASN1_CHECK_TLEN', 'wrong tag'),  │  
  │ ('asn1 encoding routines', 'ASN1_ITEM_EX_D2I', 'nested asn1 error')]

**Comment by alex** [comment]
What format is the CSR you are using in?

**Comment by bmw** [comment]
This problem occurs if you give the client a PEM encoded CSR. Currently, the client only accepts DER encoded CSRs, but #1082 hopes to change that.

Regardless, we should give a better error message in this case. I'm modifying the title of this issue to reflect this.
