### ISSUE TITLE
Better error for people attempt to use IDNs (Currently, UnicodeDecodeError)

### ISSUE THREAD

**Issue by Jnbond** [certbot/certbot#1939]
Hello, 

" root@ns3:~/letsencrypt# ./letsencrypt-auto
Updating letsencrypt and virtual environment dependencies.......
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt
An unexpected error occurred:
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 9: invalid continuation byte
Please see the logfiles in /var/log/letsencrypt for more details. " 

This is a domain containing accents, how can I fix that?

Sincerely

**Comment by pde** [comment]
Unfortunately we can't issue for IDN/punycode domains yet: 

* https://community.letsencrypt.org/t/punycode-domains/5315
* https://github.com/letsencrypt/boulder/issues/597

Retitling this issue...

**Comment by pde** [comment]
This was fixed a while ago. And 0.10.0 is going to include real IDN support!
