### ISSUE TITLE
Support conditional upgrades to HTTPS (modern browsers only)

### ISSUE THREAD

**Issue by pde** [certbot/certbot#1942]
One way to do this would be to detect an income `upgrade-insecure-requests: 1` header.  Another way would be to fingerprint modern browsers that support Let's Encrypt certs.

**Comment by sydneyli** [comment]
The  `redirect` enhancement exists and works now! Assuming that's what you meant here :) If not, if you clarify this ticket a bit I'm happy to re-open.
