### ISSUE TITLE
tos as url (or true) in renewal/:hostname.conf

### ISSUE THREAD

**Issue by coolaj86** [certbot/certbot#1957]
I see that `:conf/renewal/:hostname.conf`has a field `tos = True` and I couldn't find anything out about it [in the docs](http://letsencrypt.readthedocs.org/en/latest/search.html?q=renewal&check_keywords=yes&area=default), but I'd like to suggest that it allow either a string url or True.

The **purpose of the string url** is that if the tos changes and the user has decided (in some user interface) that they would not like certificates to renew until they have had the **opportunity to view the revised terms** to which they will be **legally bound** that the renewal should fail.

I know this seems unlikely, but there are some people who take this stuff very seriously and others [who don't](http://www.foxnews.com/tech/2010/04/15/online-shoppers-unknowingly-sold-souls.html).

As of the current date I think it's generally agreed upon that Mozilla and the EFF have goals and values that align with their customers. And of course they always will be, forever (maybe).

But other companies may step up to the plate that do not have their customers' best interests in mind - those who use free ssl as a marketing tactic and later abuse their customers privacy or other rights. It's uncomfortable to unwittingly sell your immortal soul, especially *automatically*.

* http://www.foxnews.com/tech/2010/04/15/online-shoppers-unknowingly-sold-souls.html

**Comment by kuba** [comment]
Renewal config generator is really dummy - it dumps entire app state into that file. Things such as `tos = True` shouldn't even be there.

**Comment by bmw** [comment]
This has been resolved. `agree_tos` is only set to True if you did it manually by including `--agree-tos` on the command line before getting linked to the TOS.
