### ISSUE TITLE
Move acme to own repository

### ISSUE THREAD

**Issue by trestoa** [certbot/certbot#1958]
I would suggest to move the acme part of the project to its own repository.
Doing so would make it much easier to use the python acme implementation for other projects.

**Comment by alex** [comment]
It's released independently on PyPI, so it's easy for projects to just `pip install acme` without the rest of `letsencrypt`. (I dont' have an opinion on your proposal, just want to point out that it's not really a blocker)

**Comment by kleiinnn** [comment]
Ah, I did not know that, but it's good to know. Then it actually makes no difference from the viewpoint of an consumer of the library.

**Comment by kuba** [comment]
Working on it :)

As @alex said, though, `acme` is already packaged separately with tarballs uploaded to https://pypi.python.org/pypi/acme. Distros should package is separately as well (that's what is being done for Debian for instance).
