### ISSUE TITLE
AttributeError: 'module' object has no attribute 'packages'

### ISSUE THREAD

**Issue by roelandp** [certbot/certbot#1968]
after installing letsencrypt following the docs on my virtual machine:
- Vagrant VM with NGINX 
- Python 2.7.6
- Ubuntu 14.04.3 LTS

I get the following error after executing `letsencrypt certonly`:

```
Traceback (most recent call last):
  File "/usr/local/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1.1', 'console_scripts', 'letsencrypt')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/letsencrypt/cli.py", line 30, in <module>
    from letsencrypt import client
  File "/usr/local/lib/python2.7/dist-packages/letsencrypt/client.py", line 10, in <module>
    from acme import client as acme_client
  File "build/bdist.linux-x86_64/egg/acme/client.py", line 28, in <module>
AttributeError: 'module' object has no attribute 'packages'
```

Is there something i'm missing? I'm quite noobish in this, would love to run letsencrypt!

**Comment by MichaelKeidler** [comment]
Hello,

I have the exact some issue.
python 2.7.6, ubuntu 14.04. LTS on VMWare Workstation 12.
installed and started as described [here](https://letsencrypt.org/getting-started/)
just one little difference, i installed the acme 0.5.0 form the letsencrypt git repository.
in pip there is only a 0.4.x.

Thanks a lot for any hint,
Michael

**Comment by somtin** [comment]
I am having the same issue here.
Ubuntu 14.04.1
Python 2.7.6
OpenSSL 1.0.1f
python packages installed from pip:
- cryptography 1.2.3
- letsencrypt 0.4.2
- acme 0.4.2

**Comment by HardlyMirage** [comment]
Same issue here. I'm unable to renew my cert because of this error.

Ubuntu 14.04.3 LTS
Python 2.7.6
OpenSSL 1.0.2j

**Comment by armetiz** [comment]
Same issue. I'm unable to generate cert.

Centos 7.1
Python 2.7.5
OpenSSL 1.0.1e

**Comment by gianpaj** [comment]
This worked for me on CentOS 7.0, Python 2.7.5, OpenSSL 1.0.1e-fips

Error:
```
$ certbot --help all
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.9.3', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 19, in <module>
    from certbot import client
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 10, in <module>
    from acme import client as acme_client
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 29, in <module>
    requests.packages.urllib3.contrib.pyopenssl.inject_into_urllib3()
```

Fix:
```
$ sudo easy_install --upgrade pip
...
Installed /usr/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg
Processing dependencies for pip
Finished processing dependencies for pip

$ sudo pip uninstall requests
...
  Successfully uninstalled requests-1.1.0

$ sudo pip install requests
...
Successfully installed requests-2.12.4
```

**Comment by chriszrc** [comment]
Hmm, 

I updated requests, but then I got another error:

`ImportError: 'pyOpenSSL' module missing required functionality. Try upgrading to v0.14 or newer.
`

I noticed during the requests install that there were some warnings:

`“InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
           InsecurePlatformWarning”`

Googling that lead me to a page that said I had to update more than just requests, it said to:

`pip install requests[security]`

Now that did upgrade the pyOpenSSL to 16.2.0, but running certbot again just gives me the same error

**Comment by Ark74** [comment]
Try 
`pip install -U six`

It worked for me.

**Comment by sydneyli** [comment]
We don't recommend that people install Certbot using `pip`, which is what it looks like in OP's case. A couple of the other issues in this thread look like their `pip` environments could be corrupted in different ways. We recommend using our [instruction generator](https://certbot.eff.org/) for our officially supported installation method on your system.

If you get a similar problem, you can ask for help [at the Let's Encrypt community forums](https://community.letsencrypt.org/c/help) or make a new issue if you're sure it's a Certbot issue (it's often not, though, and you'll get faster help on the forums in these cases). Both have issue templates that you should fill out that will give us more context about your particular setup and issue!
