### ISSUE TITLE
Add more docs to Docker image

### ISSUE THREAD

**Issue by iBobik** [certbot/certbot#2003]
[There](https://github.com/letsencrypt/letsencrypt/blob/master/docs/using.rst#running-with-docker) is some info about Docker image, but I miss:
- What features it supports?
- Can it run in loop and fetch renewed certificates when they are going to expire?
- How to configure it to maintain multiple domains in one image?

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.
