### ISSUE TITLE
Offer a non-Github git mirror

### ISSUE THREAD

**Issue by KOLANICH** [certbot/certbot#2011]
>git clone https://github.com/letsencrypt/letsencrypt

Is dangerous: the users will have to trust github and their CAs.
You should host this on your own servers.

**Comment by pde** [comment]
We do have signatures on our PyPI uploads and signed git release tags.  But it's probably good to have a git mirror for reliability, as well.

**Comment by KOLANICH** [comment]
>
```bash
$ git clone https://github.com/letsencrypt/letsencrypt
$ cd letsencrypt
$ ./letsencrypt-auto --help
```

I don't see here any signature verification.



>We do have signatures on our PyPI uploads and signed git release tags. But it's probably good to have a git mirror for reliability, as well.

I meant that main version is on YOUR servers, but the GitHub one is just a mirror.

**Comment by pde** [comment]
Take a look at #1665; after that lands we'll be able to serve letsencrypt-auto without git.

**Comment by bmw** [comment]
This has been resolved. Current [installation instructions](https://certbot.eff.org/docs/intro.html#installation) have you download `certbot-auto` from EFF's server and verify a GPG signature using a key signed by the EFF developers.
