### ISSUE TITLE
Sandbox/Test mode for certonly operation

### ISSUE THREAD

**Issue by languitar** [certbot/certbot#2035]
When setting up the automation to renew certificates (in case you are using the "manual" modes like `certonly` or with CSRs). Some steps might need to be repeated several times until everything works as expected. It would be nice if the client supported such a testing mode, by e.g. issuing only self-signed certificates, so that you do not actually request real certificates and easily end up in the rate limit and waste resources of the CA.

**Comment by smeinecke** [comment]
:+1: would be really nice as we run in limits only by testing

**Comment by mickael9** [comment]
I think you can use `--staging` option to use the staging server :
```
  --test-cert, --staging
                        Use the staging server to obtain test (invalid) certs;
                        staging.api.letsencrypt.org/directory (default: False)
```

**Comment by languitar** [comment]
Would be nice if this was documented more prominently in the online manual.

**Comment by bmw** [comment]
This is documented in help provided by the `letsencrypt` client, but I agree our online documentation needs some work..

**Comment by languitar** [comment]
Given the fact that probably everyone needs to test things first, it might actually also be a good idea to make this the default operation and force users to provide an additional flag which switches to production mode.

**Comment by TheWalkers** [comment]
++.  We were bit by this as well.

**Comment by sashahilton00** [comment]
+1 for default dev mode as well, and when ready running certbot once with --production to enable production mode henceforth.
