### ISSUE TITLE
Apache plugin fails to parse OWASP's ModSecurity ruleset

### ISSUE THREAD

**Issue by netpalantir** [certbot/certbot#2050]
Hi,

I have been trying to run the Apache module, but unfortunately it is unable to parse some configuration files from OWASP's ModSecurity core ruleset. The problematic files can be found here:

https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/master/base_rules/modsecurity_crs_60_correlation.conf

https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/master/base_rules/modsecurity_crs_40_generic_attacks.conf

https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/master/base_rules/modsecurity_crs_47_common_exceptions.conf

The error I am getting is: 

```
PluginError: ('There has been an error in parsing the file (%s): %s', u'/etc/modsecurity/owasp-modsecurity-crs/activated_rules/modsecurity_crs_60_correlation.conf', u'Syntax error')
```
Temporarily removing those three files will solve the problem.

I am on Ubuntu 14.04 with mod_security2 installed.

Thanks for the great work!!

**Comment by domcleal** [comment]
Thanks for the report, but I think this has now been fixed through PR #1945 as I'm now able to parse these example files.  This fix is available in version v0.2.0 or higher.

**Comment by TrueSelenis** [comment]
Unfortunately it doesn't seem to be fixed :-/
this is the error I get with setting up a new cert and renewing it:
`The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/httpd/modsecurity.d/modsecurity_crs_10_config.conf', u'Syntax error'),). Skipping.`

Temporary removal of the conf file from Apache config fixes the problem when requesting a new cert but autorenewal willbe iffy.

**Comment by domcleal** [comment]
> modsecurity_crs_10_config.conf

This isn't any of the config files specified above, so it's likely to be a different bug. Could you please gist the entire, unaltered file?

**Comment by TrueSelenis** [comment]
hi thanks for the quick reply
 modsecurity_crs_10_config.conf is the base conf file of modsec that sets basic parameters / rules. The files named above are part of the then sdditionally loaded package.

I have attached the file.
To my knowledge its the standard ruleset I got from regular yum install on RHEL 6

[modsecurity_crs_10_config.txt](https://github.com/certbot/certbot/files/325490/modsecurity_crs_10_config.txt)

**Comment by domcleal** [comment]
Thanks for the copy of the file, I've fixed it in Augeas at https://github.com/hercules-team/augeas/commit/64189250e2c49442a0875fa46dfb1d76a4371bde and opened a PR for certbot at #3201.
