### ISSUE TITLE
Ubuntu 14.04 fix 

### ISSUE THREAD

**Issue by omgbox** [certbot/certbot#2051]
yycman December 27, 2015

Thanks for the tutorial. Very helpful.

Seems the default version of python supplied with Ubuntu 14.04 may need some extra updates to run letsencrypt.
I needed to update python's ssl libraries:

apt-get install python-dev libffi-dev libssl-dev
apt-get install python-pip
pip install 'requests[security]'
pip install pyopenssl ndg-httpsclient pyasn1

Then I needed to import ssl into python.

python
import ssl
quit()

Also, I found my domain name example.com must have an A record on the DNS server
and it must be the same IP address as the A record for www.example.com
A CNAME DNS record for www.example.com is not sufficient -- it must be an A record.

**Comment by Levino** [comment]
I was able to issue certs with a CNAME DNS record. For example by using my docker image [here](https://hub.docker.com/r/levino/letsencrypt-cert-service/). The important part is that www.example.com/.well-known/ is ending up where your letsencrypt server is running.

**Comment by Dannyzen** [comment]
Thanks for this!
