### ISSUE TITLE
Provide a way to run a script for setting up HTTP / DNS for validation

### ISSUE THREAD

**Issue by silbe** [certbot/certbot#2053]
While a lot of sites can get by using the plug-ins shipped by letsencrypt (both existing and future ones), there will always be sites that require custom operations for provisioning the resources required for validation (e.g. files on a web server for Simple HTTP validation, DNS records for DNS validation). The easiest and most flexible way to automate this is running a user-provided script that gets passed the challenge type, identifiers (domains) and some challenge type specific parameters. E.g. for Simple HTTP validation, it could look like this:

`custom-provision-script --type simpleHttp --tls false --path .well-known/acme-challenge/Token1 --content '{ "type": "simpleHttp", "token": "Token1", "tls": false}' --domain example.com --path .well-known/acme-challenge/Token2 --content '{ "type": "simpleHttp", "token": "Token", "tls": false}' --domain example.com`

For DNS validation, it could look like this:

`custom-provision-script --type dns --name _acme-challenge --type txt --content Token1 --domain example.org --name _acme-challenge --type txt --content Token2 --domain example.com`

While those sites could write and use custom Authenticator plug-ins, scripts are easier to deploy. You  can invoke scripts with their full path, whereas letsencrypt plug-ins need to be installed using setuptools.

This has come up before (see e.g. #1015, #1475). While some users could make webroot work for them in combination with FUSE-based file systems (e.g. sshfs) or are satisfied with an interactive solution (using the manual plug-in), this isn't practical for many sites (including mine).

**Comment by silbe** [comment]
I hacked up a script plug-in (simpleHttp only) in a separate package, available at [git://git.silbe.org/letsencrypt-script-plugin.git](git://git.silbe.org/letsencrypt-script-plugin.git). It can be used like this:
`letsencrypt --authenticator letsencrypt-script-plugin:script --letsencrypt-script-plugin:script-auth-script custom-provision-script <other letsencrypt options>`

Apparently at least the Python argparse option parsing library has trouble parsing option values that may start with dashes (which can happen for tokens). So contrary to the syntax in the original report, no argument names are passed, only the options. Example:
`custom-provision-script simpleHttp .well-known/acme-challenge/token1 token1value example.com .well-known/acme-challenge/token2 token2value example.com`

This is enough to get me started using letsencrypt, but obviously lacks documentation and hasn't been polished, so I'm not proposing it for inclusion (⇒ no pull request). Feel free to use it as a basis for the official client, though.

**Comment by ph4r05** [comment]
We implemented the plugin that does quite similar thing, please see:

* https://github.com/EnigmaBridge/certbot-external-auth
* https://community.letsencrypt.org/t/is-there-any-better-documentation-for-dns-01-challenge-validation/15665/12?u=ph4r05

**Comment by pde** [comment]
This has landed in git master now (#3521)! Though the interface will probably change before it ships in the 0.10.0 release: #3767
