### ISSUE TITLE
What would be the correct permissions for the LetsEncrypt directory on OS X?

### ISSUE THREAD

**Issue by ebonsi** [certbot/certbot#2076]
Hi, I am on OS X Server Client 10.9.5 Mavericks and I went to the process of installing LetsEncrypt. Now I am going to the process of configuring the certificates. I already started a threat on the LetsEncrypt Communities under the title;
Installing LetsEncrypt on a Mac OS X Client Server (Sorry, the post title has been edited)
https://community.letsencrypt.org/t/installing-letsencrypt-on-a-mac-os-x-client-server-questions/7839/13

My problem is that I ran into permissions issues and I need to find out what is the right permissions for the directory LetsEncrypt installed on /etc/letsencrypt? .. or if there are different permissions for the sub-directories, 
a. accounts
b. archive
c. csr
d. keys
e. live 
f. renewal

I have tested the server and so far I could not make Apache 2.4 work. Any suggestions? Thanks!
Thanks!
E\

Ps: I did read other posts but they have some many different answers that I got confused as "what are the correct permissions". This should not be a charade in the development.

**Comment by ebonsi** [comment]
Hello,
It seems like no one can answer me to this question, I went along and test myself with this permissions and everything worked just fine.

/etc/letsencrypt   <--- 0755
a. accounts         <--- 0700
b. archive            <--- 0700
c. csr                   <--- 0755
d. keys                <--- 0700
e. live                  <--- 0705
f. renewal            <--- 0755

If you are part of the development, please take a look and comment + please, scrutinize what I did. In addition to that I was looking at the /renew/domain.conf file on the renew directory and I see that is pointing to the OS X System Apache original directory, /etc/apache.
There was no way for you to know that but I am on Mavericks still, but I realized the native apache on Mavericks got obsolete and I installed Bitnami Mamp with a brand new spanking Apache 2.4 that support all the new ciphers. So I corrected the directory by hand as root.

For the permission please, refer to the LetsEncrypt Community post;
https://community.letsencrypt.org/t/installing-letsencrypt-on-a-mac-os-x-client-server/7839

**Comment by ilanbiala** [comment]
Any update on what the correct permissions are?

**Comment by viharm** [comment]
It is very dangerous to allow "others" to read the diretory structure as it contains the private keys.

I suggest changing group to `ssl-cert`, and giving group read permissions to archive and live directories.

Users for all services should then be added to `ssl-cert` group.

**Comment by sydneyli** [comment]
From the thread it looks like the current default permissions on Certbot's directory are too restrictive, i.e. since your server software doesn't run as `root`, it can't access your certificates. 

If that's the case, [this issue](https://github.com/certbot/certbot/issues/1473) is tracking development options about options that Certbot can provide to configure the proper permissions for you.

As a temporary solution, we don't recommend making `/live/` world-readable, but to use a secure group like @viharm mentioned, and specify a `post-hook` in Certbot to fix the permissions for you after each renewal.
