### ISSUE TITLE
Error creating new cert :: Too many certificates already issued for: selfhost.eu

### ISSUE THREAD

**Issue by somniumAeternam** [certbot/certbot#2091]
Is there a way to use letsencrypt with dyndns services? I use selfhost for my home server and I'm not able to create a certificate because of the above mentioned error. Selfhost itself has also different top level domains (e. g. .org, .de ...)

**Comment by somniumAeternam** [comment]
I talked to the selfhost support. They don't want to make an entry into the public suffix list, maybe because they want to sell their own certificates. So is there an possibility to use lets encrypt with selfhost-dyndns?

**Comment by 0xCD** [comment]
@somniumAeternam you can try to create free .cf/.ga/.tk/.ml/.gq second-level domain [here](http://www.freenom.com/en/) and add the CNAME record for your selfhost.eu domain.

**Comment by axtux** [comment]
I'm using Let's Encrypt certificate with a free domain name and it's working fine. StartSSL had refused to issue a free certificate for that domain.

You could just get rid of your DynDNS domain by using your free domain with a DNS manager that accept DynDNS. I'm using OVH and CloudFlare's that are completely free.

**Comment by maschs** [comment]
I'm experiencing the same error with ovh.net. Every VPS with OVH is assigned a static subdomain of the kind "vps123456.ovh.net". Unfortunately too many certificates have already been issued for ovh.net.

Pretty funny if you remember ovh is a platinum sponsor of Let's Encrypt.

**Comment by CannyFoxx** [comment]
Yeah, limits are weird. I have a lot of subdomain for all my applications (eg. owncloud.domain.tld, redmine.domain.tld... up to 15 names). Today i reinstall my server and found that i backup symlinks of certificates (dir live; yes, i'm probably idiot). Now i need 3-4 weeks (read as month) for create all certs.

I hope mozilla team will raise limits on next beta test stage

**Comment by levinus** [comment]
With letsencrypt you can issue certs with much more than one (sub)domain. With the certonly option you can write up to 100 (as far as I know) (sub)domains as alternative names (with -d [DOMAIN]...) . They are also accepted by browsers... (I dont know how its with the apache plugin but similar I think..) This is not very helpful for the real topic but an comment for @CannyFoxx :)

**Comment by CannyFoxx** [comment]
Thanks, i will try it. I'm using nginx as main webserver and before used 'letsencrypt auth -d domain.tld -d...' for certificate creating

**Comment by CannyFoxx** [comment]
Not working, raise same error

**Comment by levinus** [comment]
@CannyFoxx The "Too many certs already issued for.. "? The cert that you issue counts as 1. Have you already issued 5 this week? Wait for the next period, try again. (Maybe try with ./letsencrypt-auto certonly -d domain.tld -d sub.domain.tld ...)

**Comment by CannyFoxx** [comment]
Yesterday i created 1 new certificate (this project may have separate cert by security reasons):
`./letsencrypt-auto auth -d sub1.domain.tld -d www.sub1.domain.tld`

After i tried to get another one:
`./letsencrypt-auto auth -d domain.tld -d www.domain.tld -d sub2.domain.tld [...] -d sub9.domain.tld`

Today i tried `certonly`, but steel have this error

**Comment by levinus** [comment]
@CannyFoxx Then you have to wait a few days and retry, I think... Sometimes I dont understand the limits...

**Comment by lichtamberg** [comment]
When is this going to be released? 
We have this problem too... We have subdomain for each of our customers, f.e. customer1.mydomain.com, customer2.mydomain.com, customer3.mydomain.com, ... 
And each of them has an own server and we need seperate subdomain certificates.

This service is really nice in general already, but not usable for us with this limitation!

**Comment by Mika56** [comment]
Same problem with http://www.azote.org/ domains:
 - .fr.cr
 - .fr.nf
 - .ze.cx
 - .asso.st
 - .infos.st
 - .xxl.st

I think you need to consider _some_ sub-domains as TLD, like you probably do to .co.uk for exemple

**Comment by schoen** [comment]
> I think you need to consider _some_ sub-domains as TLD, like you probably do to .co.uk for exemple

If the domains allow the general public to register under them, they can
be added to the public suffix list.

https://publicsuffix.org/

The Let's Encrypt CA regularly imports updated versions of this list and
treats it specially for rate-limiting purposes. It is also worth being
on the list for safer browser handling of cookie sharing policies (so
that one site under `co.uk` can't receive cookies from others, for
example).

**Comment by Mika56** [comment]
Thanks for the quick reply!
I sent them a mail, let's hope they'll add their domains to this list :)

**Comment by shanteadam** [comment]
FYI, the public suffix list is not really an adequate solution to this issue since they have expressed that they are receiving more requests than they can handle. There are pull requests pending from early December. They have also made it sound like they are unsure how they will move forward handling these requests. https://github.com/publicsuffix/list/pull/64

**Comment by weppos** [comment]
> FYI, the public suffix list is not really an adequate solution to this issue since they have expressed that they are receiving more requests than they can handle.

This is inaccurate. We can handle them, but we are weighting the priorities.

> They have also made it sound like they are unsure how they will move forward handling these requests.

This is more accurate. We are currently working to ensure we can properly verify the validity of such requests (as in most cases they are inaccurate, incomplete, submitted by users with no ownership, etc). 

It takes time, and if the only intent is to be in the list is to be able to obtain more Let's Encrypt certificates and bypass the current rate-limiting, then I agree that you should not bother submitting your domains to the list but rather wait for Let's Encrypt to relax the limits when they will be ready to do it.

**Comment by hbielenia** [comment]
> if the only intent is to be in the list is to be able to obtain more Let's Encrypt certificates and bypass the current rate-limiting

Well, it would serve to make the list more complete, as ovh.net is without a doubt available to general public.

On topic, I filed support ticket for my VPS and got following response (translation mine):

> We do not support this solution and xxx.ovh.net is merely a technical name.

Kinda disappointing from Let's Encrypt platinum sponsor. Looks like we will have to wait a long time until LE's mission of encrypted web will be fullfilled, if ever.

**Comment by bmw** [comment]
Adding domains to the public suffix list is the current solution to this problem.

Also, this issue is outside of the scope of the Certbot client as rate limits are set by the Let's Encrypt CA so I'm closing this issue.
