### ISSUE TITLE
Challenge files should get chowned like acme-challenge folder

### ISSUE THREAD

**Issue by lucasRolff** [certbot/certbot#2096]
Currently when you use the webroot plugin, it tries to chown the ache-challenge folder to the parent permissions (e.g. `$user:nobody`) - which is awesome, the thing is the challenge files are still owned by root, meaning servers that runs with symlink protection (basically disallowing users from reading other users files) it results in not being able to validate the challenge because the challenge files are owned by root.

What would make sense is to either allow setting the uid/gid of which the challenge files should be owned  (might be I want the files to be owned as `www-data:www-data`) - or even better even just copy the block as here https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/plugins/webroot.py#L73 - put it in the `_perform_single` function to do the same for the `validation_file`.

This would be a big plus, specially for hosting providers, currently we have to start a sub-process that chowns everything in the challenge folder to make letsencrypt work on a shared hosting environment that does prevent reading files from other users.

**Comment by lucasRolff** [comment]
Small update - I can see this code that was merged 25 days ago, was actually the cause of breaking it:
https://github.com/letsencrypt/letsencrypt/pull/1875/files

It used to chown the `path` with in the `_perform_single` function https://github.com/letsencrypt/letsencrypt/pull/1875/files#diff-522ab130649a0ce14df40114d4ccd0b5L109

Then it got removed - and broke stuff

**Comment by kuba** [comment]
Can you link to the "symlink protection" you're referring to?

**Comment by lucasRolff** [comment]
https://documentation.cpanel.net/display/EA/Symlink+Race+Condition+Protection

Anyway - regardless of the patch, deciding ownership for those files make sense anyway - either in an automated or non-automated way - I don't really like the fact that the webserver has to be able to show files owned by root.

**Comment by bmw** [comment]
I think automatically creating the file with the same permissions makes sense. If anyone is interested, feel free to submit a PR.

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.
