### ISSUE TITLE
libffi dependecies not accepting a newer version

### ISSUE THREAD

**Issue by andreapernici** [certbot/certbot#2099]
When I execute on Centos the letsencrypt auto I get a strange error:

Transaction Check Error:
  package libffi-3.0.9-1.el5.rf.x86_64 (which is newer than libffi-3.0.5-1.el5.i386) is already installed

So having a newer package of libffi prevent me from using letsencrypt?
Is it a bug or is it the intended behaviour?

**Comment by pde** [comment]
Is this during the bootstrapping (install OS dependencies) phase of `letsencrypt-auto`?

**Comment by naimhusin** [comment]
I had faced the same error.

Yes it is during bootstrapping.

`Transaction Check Error:`
  `package libffi-3.0.9-1.el5.rf.x86_64 (which is newer than libffi-3.0.5-1.el5.i386) is already installed`
   `package libffi-devel-3.0.9-1.el5.rf.x86_64 (which is newer than libffi-devel-3.0.5-1.el5.i386) is already installed`

`Error Summary`
`-------------`

`Could not install additional dependencies. Aborting bootstrap!`

OS: CentOS 5.11

**Comment by simps-oonops** [comment]
certbot-auto on Scientific Linux release 6.8 (Carbon) also aborts:
`Protected multilib versions: libffi-3.0.5-3.2.el6.i686 != libffi-3.0.9-1.el3.rf.x86_64
Could not install OS dependencies. Aborting bootstrap!`

**Comment by bmw** [comment]
This issue hasn't seen any updates in almost 2 years and we have tens of thousands of certbot-auto users on RHEL 6 based systems so I'm closing this issue. If you're continuing to have problems, please comment or open a new issue.
