### ISSUE TITLE
add AUTHORS, CONTRIBUTORS or CREDITS to toplevel dir

### ISSUE THREAD

**Issue by ThomasWaldmann** [certbot/certbot#211]
it's useful so people know who worked on the software.
also it can be referred to in (c) notices (if appropriate).

.rst maybe?

**Comment by kuba** [comment]
It would be nice to include it in the docs, just like we do with README.md.

**Comment by ThomasWaldmann** [comment]
see PR #213

**Comment by cowlicks** [comment]
This is still needed.

@ThomasWaldmann Do you have the code laying around which you made #213 with? Shouldn't this just be a list of the github contributors?

**Comment by ThomasWaldmann** [comment]
No, but IIRC it was just some git log + uniq + sort or so.

**Comment by SwartzCr** [comment]
@pde thoughts?

**Comment by bmw** [comment]
Not Peter, but I also support this. See #3802.

**Comment by SwartzCr** [comment]
I generally like #213 and would be pro redoing it. Though it's worth noting that now we have 235 contributors to this repository. Some of them have very small amounts of code committed (less than 10 lines) but they're still there. So if we are to do this we should have some policy about this - or decide that we do want to list all 235 people.

**Comment by bmw** [comment]
Do you like the idea of letting people add themselves as they like in the future? If so, we just have to figure out what we want to do for past contributors.

I'd personally lean towards just adding everyone who contributed in the past, but I don't think it'd be a big deal to only add people who have added/removed X lines of code to keep the list a little more manageable. If people who have contributed in the past show up wanting to be added to the list, I think we'd happily approve a PR from them adding themselves.

**Comment by cowlicks** [comment]
I like your suggestion @bmw add all previous contributors, then new contributors can add themselves if they want. It gives new contributors a nice little ego boost :)

**Comment by SwartzCr** [comment]
@bmw I like the idea of letting people add themselves. I'm pro: adding some of the existing ones (based on lines) but then letting them add themselves, but also happy to just include all of them (since I don't know what the line cut off should be)

**Comment by bmw** [comment]
@SwartzCr, if you're up for making the PR, you can take whichever approach you prefer and I'll review it.

**Comment by SwartzCr** [comment]
So I'm about to make a PR for this, but it seems kinda bad to include everyone's email...
If we just put their names it also seems kind unhelpful. I'd ideally like to link to all these people's githubs? but I also don't want to have to manually search them

**Comment by SwartzCr** [comment]
Made a PR for it

**Comment by zjs** [comment]
> I'd ideally like to link to all these people's githubs? but I also don't want to have to manually search them

Maybe using the info here would avoid needing to search: https://github.com/certbot/certbot/graphs/contributors

If you want to format things as email addresses, you could follow the pattern of `zjs@users.noreply.github.com`.

**Comment by SwartzCr** [comment]
@zjs, unfortunately I think the info on that github link misses a lot of contributors? Maybe that's just the contributors that committed with a github account? I'm not sure.
If that's the case I could put them as links in the PR, and leave the others blank (and then maybe people could make PRs adding links to their GHs or websites?)
