### ISSUE TITLE
Fix sporadic Apache unit test failures

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#2118]
The Apache plugin has begun sporadically failing unit tests in Travis. I have only seen this occur during coverage tests. Here's 3 different logs of the problem: [log1](https://gist.github.com/5d6e16b74e1b7008d5a6), [log2](https://travis-ci.org/letsencrypt/letsencrypt/jobs/100924529), [log3](https://gist.github.com/c464d11fb30c56ffac2c).

These problems need to be fixed as it slows down development, confuses new contributors, and may be caused by larger problems with the plugin.

**Comment by pde** [comment]
I suspect this is fixed...
