### ISSUE TITLE
Problems with undefined symbol  building on CentOS 6.7

### ISSUE THREAD

**Issue by tfrangio** [certbot/certbot#2122]
I have been studying the other **undefined symbol** issues and I can not find anyone with my exact issue. I am on **CentOS6.7**. What is driving me crazy is I have Letsencrypt working on a different CentOS6.7 installation so I know it can work. 

When I run :

> /Timstmp/Letsencrypt-Source/letsencrypt/letsencrypt-auto --config /Timstmp/Letsencrypt-Source/ssl-certs/cli.ini --debug certonly

I get this error:

> File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module> from cryptography.hazmat.bindings._openssl import ffi, lib ImportError: /root/.local/share/letsencrypt/lib/python2.6/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: **EC_GROUP_new_curve_GF2m**

FYI the "cli.ini" file contains these lines:

```
# the default is 2048 (more is better)
rsa-key-size = 4096

# plugin
authenticator = webroot

# webroot
webroot-path = /home/baystate/public_html

# domains
domains = baystate.academy,www.baystate.academy

# flags
# renew is good for automation
renew-by-default
```

My first thought was it must be **openssl** but that does not seem to be a problem.
Here are my **openssl version -a** results:

> (letsencrypt)root@server01 [/Timstmp/Letsencrypt-Source2/letsencrypt]# openssl version -a
> OpenSSL 1.0.1e-fips 11 Feb 2013
> built on: Thu Jan  7 19:19:21 UTC 2016
> platform: linux-x86_64
> options:  bn(64,64) md2(int) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx)
> compiler: gcc -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT >-DDSO_DLFCN -DHAVE_DLFCN_H -DKRB5_MIT -m64 -DL_ENDIAN -DTERMIO -Wall -O2 -g -pipe >-Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 >-mtune=generic -Wa,--noexecstack -DPURIFY -DOPENSSL_IA32_SSE2 >-DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m >-DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM >-DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
> OPENSSLDIR: "/etc/pki/tls"
> engines:  dynamic
> (letsencrypt)root@server01 [/Timstmp/Letsencrypt-Source2/letsencrypt]#

Please let me know if you have seen this and if you have any suggestions?

**Comment by pde** [comment]
Does the [new letsencrypt-auto script](https://community.letsencrypt.org/t/help-test-the-new-letsencrypt-auto-script/8544) also have this problem for you?

**Comment by pde** [comment]
(The new version pins its dependencies, rather than always installing the latest versions of them, avoiding bugs like that one which was [in python-cryptography bug](https://github.com/pyca/cryptography/issues/900) I think.  Though I'm a little puzzled you were still seeing it...)

**Comment by tfrangio** [comment]
I tried the new script that pde suggested and search for days but could not get this to work. Eventually I upgraded to CentOS 7 and that solved all my problems. I know that is like using a nuclear bomb to kill a fly but, I was going to upgrade the os anyways this just lite a fire under my butt ;-)

**Comment by zimmski** [comment]
The new version solved this for me on openSUSE 42.1

**Comment by pde** [comment]
These bugs are caused by incompatibilities between versions of python-cryptography/pyOpenSSL, and openssl / libssl/-dev. We're going to do something like #3895 to help with the ones that occur at runtime; the compile-time ones for `certbot-auto` are trickier and are ultimately best mitigated by native OS packaging...

**Comment by feiyan35488** [comment]
I got this problem , and I solved .
1.  yum remove openssl-devel
2. rf -rf ~/.local/share/letscrpyt
3. certbot-auto  // re-execute this command for reinstall 

one month before I upgrade openssl to 1.0.2j, and certbot needs  openssl 1.0.1e ,    maybe it's the problem,
