### ISSUE TITLE
Option to not display donation message (for running in scripts)

### ISSUE THREAD

**Issue by daviessm** [certbot/certbot#2142]
Have a command line parameter to not display the donation message which can be used when the client is being run from a cron job or similar.

**Comment by pde** [comment]
What about all the other notification messages, regarding the location of keys, account backups, etc?  It seems that presently stdout is very much non-empty, even in the forthcoming [non-interactive mode](https://github.com/letsencrypt/letsencrypt/pull/2078)

**Comment by pde** [comment]
(And that this should be part of a plan to make stdout meaningful for scripting).

We could in theory disable the donation message for all noninteractive execution, although probably there are a lot of users who will prefer to use non-interactive mode interactively (they want to run a shell command without being asked any subsequent questions, but they do want to see full / rich output describing what happened).

**Comment by daviessm** [comment]
Exactly, my ideal solution would be to run the client noninteractively but only show me output when it's done something or an error condition has occurred. Currently I'm running it daily with the --reinstall option so that it will grab a new certificate when the current one is close to expiry, but I would like it to tell me when it's done so.

**Comment by pde** [comment]
@daviessm take a look at this model script for a workaround:

https://letsencrypt.org/howitworks/#writing-your-own-renewal-script

**Comment by daviessm** [comment]
@pde thanks, I've ended up doing something similar (with --webroot), passing the response into sed to chop out the unwanted log lines and checking the result of that.

**Comment by schoen** [comment]
I think this should be closed because Certbot has by now long had a noninteractive mode which works well in scripts. There may still be a few things that can't be done properly in noninteractive mode, but those things, if they exist, are all worthy of their own separate issues!
