### ISSUE TITLE
Add a timeout to HTTPS connections

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#2148]
In https://community.letsencrypt.org/t/client-takes-almost-one-hour-to-create-certificate/8579/3 and https://github.com/letsencrypt/letsencrypt/issues/1648#issuecomment-170773846 we've seen users for whom the client is very slow. The root cause winds up being that outbound IPv6 connectivity from their web host is broken in some way.

We should add timeouts to the HTTPS connections, and produce an error message if it takes more than, say, a minute to connect. We could include a few ideas on how to fix, including checking IPv6 connectivity with `wget -6 https://www.google.com` as described at https://community.letsencrypt.org/t/client-takes-almost-one-hour-to-create-certificate/8579/3.

**Comment by kuba** [comment]
Dupe of #1543?

**Comment by jsha** [comment]
Yep, dupe of #1543. I closed that one and kept this one though, since this has more current context.

**Comment by ehampshire** [comment]
Would love to get this parametized.  I found where to update the client.py file to up the timeout.  I'm writing my own ACME proxy server and our backend SSL issuance takes ~1.5 minutes, so twice as long as the default timeout value.

Here's the value to change in CertBot's client.py (it's at the top):
DEFAULT_NETWORK_TIMEOUT = 45

**Comment by jsha** [comment]
This will get a lot better with ACMEv2, which has asynchronous issuance. One hack you could do in the meantime is for new-cert to 301 every few seconds to a new URL until the issuance is actually done.

I'm reluctant to add another flag to the Certbot command line without a very strong reason, and since this issue will go away eventually I would recommend against adding the flag.

**Comment by ehampshire** [comment]
Ah, thank you!  I will investigate the 301 approach... since LE issues pretty much immediately I couldn't figure out what needed to be done to tell the client to keep polling like it does on the challenges.

**Comment by jsha** [comment]
To clarify: For challenges, the client explicitly re-requests until the status changes from "pending." The server doesn't do any 301's there. The 301 approach would be a hack that I *think* would work to convince the client to incidentally poll. One note: There may be a max redirect limit, so you might want to redirect every 30 seconds to maximize that limit.

**Comment by jsha** [comment]
Fixed in https://github.com/certbot/certbot/pull/4217, https://github.com/certbot/certbot/pull/4237, and https://github.com/certbot/certbot/commit/9be4fedeecf2489f7c707030bb6ad944e68d52d5.
