### ISSUE TITLE
Compilation/installation error

### ISSUE THREAD

**Issue by ZlatyChlapec** [certbot/certbot#2149]
Few months ago it was working just fine and today when I wanted to run letsencrypt again to renew certs I ended up with error

```
./letsencrypt-auto --help
Updating letsencrypt and virtual environment dependencies.....Command "/root/.local/share/letsencrypt/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-PGmqEf/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-gvaH1u-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.local/share/letsencrypt/include/site/python2.7/cffi" failed with error code 1 in /tmp/pip-build-PGmqEf/cffi
```

I tried to delete and redownload letsencrypt but it didn't help.

**Comment by ZlatyChlapec** [comment]
If I use command

    . ./letsencrypt-auto certonly --webroot -w path l -d domain
it's working even tho it still write errors but I get certs issued by happy hacker

**Comment by ZlatyChlapec** [comment]
With this command it's working

    . ./letsencrypt-auto --agree-dev-preview --webroot -w path -d domain --server https://acme-v01.api.letsencrypt.org/directory auth
but there are still same errors as you can see http://pastebin.com/yCs2uvSc.

**Comment by ndrewh** [comment]
+1 I get this too

**Comment by rroseselavy42** [comment]
getting same on Debian 8 looks like an issue with cffi

**Comment by ZlatyChlapec** [comment]
@rroseselavy42 No I don't think so but I am not 100% sure, it was 9 days ago sorry. Tho it happend on Debian 8 as well, and I think that in some cases I did delete /etc/letsencrypt/archive/domain, /etc/letsencrypt/domain and /etc/letsencrypt/renewal/domain.conf. Be sure to take backup in case of deleting those.

**Comment by rroseselavy42** [comment]
looks like this is a problem with compiling cffi for letsencrypt. 

<addr> x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    In file included from /usr/include/limits.h:25:0,
                     from /usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed/limits.h:168,
                     from /usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed/syslimits.h:7,
                     from /usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed/limits.h:34,
                     from /usr/include/python2.7/Python.h:19,
                     from c/_cffi_backend.c:2:
    /usr/include/features.h:374:25: fatal error: sys/cdefs.h: No such file or directory
     #  include <sys/cdefs.h>
                             ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/jessie/.local/share/letsencrypt/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-BEzCRx/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Apyegq-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jessie/.local/share/letsencrypt/include/site/python2.7/cffi" failed with error code 1 in /tmp/pip-build-BEzCRx/cffi
</addr>

**Comment by kabo** [comment]
I'm also having this issue.

**Comment by ohemorange** [comment]
We have a compiled version on Ubuntu 14.04 now, see certbot.eff.org for details.
