### ISSUE TITLE
Enable EPEL in RPM bootstrapper

### ISSUE THREAD

**Issue by erikrose** [certbot/certbot#2158]
[Some letsencrypt-auto runs on CentOS fail](https://community.letsencrypt.org/t/help-test-the-new-letsencrypt-auto-script/8544/4) due to the EPEL repository being disabled, which [is the default for CentOS and perhaps others](https://community.letsencrypt.org/t/help-test-the-new-letsencrypt-auto-script/8544/4). We should probably enable EPEL in our bootstrap script, since we enable Debian Backports in our Debian one.

**Comment by motokochan** [comment]
I'd be in favor of issuing a warning or error that EPEL is needed and not enabling/installing by default. As it is, letsencrypt-auto makes quite a few system-level changes, but I'm not in favor of adding a whole package repository automatically.

**Comment by erikrose** [comment]
I'd also be perfectly satisfied to remove the backports activation from the Debian scripts; as long as we're consistent, I'm happy. Let's see what everyone else has to say.

**Comment by srvrco** [comment]
Like motokochan, I'm in favour of a warning of what is missing, and what needs to be added.   On production servers I really don't like it making the changes by default.  

I think, given the warning, it's OK to ask the question "do you want to automatically add the repository and install all these missing elements ? " , those that are happy to can just say yes and have it done.

**Comment by bmw** [comment]
+1 to prompting the user instead of just enabling backports/EPEL ourselves. Doing it automatically seems like a good way to make unwanted changes to a user's system.

**Comment by bmw** [comment]
With #2885, the user is prompted before we enable backports. I think we should do the same thing here with EPEL.

**Comment by pde** [comment]
Much of the logic for doing this can be cribbed [from the Debian boostrapper](https://github.com/certbot/certbot/blob/master/letsencrypt-auto-source/pieces/bootstrappers/deb_common.sh#L41)
