### ISSUE TITLE
Remove [testing] setuptools extras

### ISSUE THREAD

**Issue by erikrose** [certbot/certbot#2167]
In #1665, I moved mock from the packages' `install_requires` to their `tests_require`, which allowed me to switch from an explicit invocation of nose in tox.ini to `python setup.py test`. However, to minimize disruption late in the release cycle and keep my PR on target, I did only what was necessary. This ticket is about finishing the job.

Let's…
- Move nose from the `testing` extra to `tests_require` (if we in fact require it). [Ed: we don't.]
- Move auxiliary tools like coverage and pep8 from the testing extra to tox, which is what calls them.
- Remove the testing extra altogether if it ends up being empty.

**Comment by kuba** [comment]
NB this might stand in conflict with pending #2141

**Comment by ohemorange** [comment]
We don't even have a `tests_require` or a `testing` anymore, so I'm closing this. Feel free to reopen if I'm wrong.
