### ISSUE TITLE
Dynamically computed install_requires: investigate potential problems

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#2176]
In https://github.com/letsencrypt/letsencrypt/pull/1661#discussion_r46522959 @mgedmin said:

> Hmm. Dynamically-computed install_requires causes problems for users of pip >= 7.0, which has wheel caching enabled by default: pypa/pip#3025. Short version:
> - I pip install letsencrypt on Python 2.7, pip runs setup.py and builds a wheel (marked -py2-none-any.whl) and puts it in ~/.cache/pip/
> - I pip install letsencrypt on Python 2.6, pip discovers a valid wheel and installs it, using install_requires computed earlier for a different Python version."
#2175 might be related

**Comment by Natim** [comment]
In #2175 I added an extra_requires rule that will be taken into account when installing wheel and make it possible to build universal wheel.
