### ISSUE TITLE
Run test farm tests automatically

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#2189]
We're getting some decent test farm tests written, but it does us no good if they're not run. We should set up a system to run these tests regularly off of `master` (every 24 hours?) and e-mail the results (or regressions) to the client dev team.

**Comment by pde** [comment]
Hey look, we already have this ticket!

**Comment by pde** [comment]
Maybe we also want to do #2427

**Comment by bmw** [comment]
Hoping to resolve this before the next release.

**Comment by bmw** [comment]
I always remember talking about how we can't do this because the tests are too flakey, but this isn't a big deal for our nightly tests so maybe we should finally set this up.

**Comment by bmw** [comment]
This was done in https://github.com/certbot/certbot/pull/7072.
