### ISSUE TITLE
A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail

### ISSUE THREAD

**Issue by unbaiat** [certbot/certbot#2195]
When running ./letsencrypt-auto certonly --standalone

Warning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail

OS: Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.41-2+deb7u2 x86_64 GNU/Linux
OS: Debian GNU/Linux 7 \n \l
Python version: Python 2.7.3

**Comment by unbaiat** [comment]
I have fixed this using: sudo easy_install && sudo pip install pyopenssl ndg-httpsclient pyasn1. 
Can some also re-validate this the correct fix?

**Comment by kuba** [comment]
It is not the correct fix. Tip from me: do not ever do `sudo pip` or `sudo easy_install` - `~/.local/share/letsencrypt/venv/bin/pip` is the binary that should be used for `letsencrypt-auto` environment, but this is actually an implementation detail that you should not care about. In general, I advise not to experiment with `pip` and just report the issue to GitHub.

This smells like #2175 issues

**Comment by unbaiat** [comment]
Yep. Same issue. I will read the code to fully understand how it should be fixed

**Comment by LMCv3** [comment]
I've you're running Debian Wheezy, apt-get install ndg-httpsclient should also handle this for you.
