### ISSUE TITLE
Release workflow misses update of version strings in master

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#2198]
Follow-up for #2197. I've reported similar issues to  multiple times. What is your plan of actually fixing the release workflow?

**Comment by kuba** [comment]
Also, why is `merge` lagging behind `v0.2.0` tag? The latter has one additional commit and I believe this should be reflected in the `master` commit log.

**Comment by pde** [comment]
Yeah, the version strings get updated off in the cloned release branch, and I don't think @bmw pushed that somewhere mergeable?  But if we merge #2199 we should get the bump?

**Comment by kuba** [comment]
I'm not talking here about one-off solution lke #2199. It should be part of automated workflow because you forget about it every single time.

**Comment by bmw** [comment]
This time it was my fault.

I agree we should update the tag and version number automatically though.

**Comment by bmw** [comment]
This has been fixed.
