### ISSUE TITLE
/var/log/letsencrypt/letsencrypt.log is readable for all users

### ISSUE THREAD

**Issue by otrosien** [certbot/certbot#2203]
I cannot tell for sure, but it looks like this log contains sensitive information like debug log entries containing private keys, so when creating it should really be made sure it is not readable by others.
I'm using letsencrypt-auto (commit ff7e7656) on centos 6.6.

**Comment by kuba** [comment]
There should be no sensitive information in the logs. If you find private key in there, please open a new bug report!

**Comment by otrosien** [comment]
Well, I know too few of the communication protocol, but I see tokens, challenges, keyAuthorization fields, replay-nonces and urls that look like they contain random key tokens in them... And you're saying nothing of it is sensitive? Even if what you're saying is true, with this way of debug-level logging (why is this enabled by default in the first place?), don't you think it can easily happen in the future?

Or the other way round: What is the rationale behind keeping this file world-readable?

**Comment by sydneyli** [comment]
Related to #525...

**Comment by sydneyli** [comment]
As @bmw said:

> The individual log files are world readable, but we enforce that the log directory is only accessible by the current user at https://github.com/certbot/certbot/blob/master/certbot/log.py#L136.

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.
