### ISSUE TITLE
Special-Use Domain Names instead of le*.wtf

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#2205]
`*.example.{com,net,org}` or `*.test` as defined in [RFC6761](https://tools.ietf.org/html/rfc6761) should be used instead of `le*.wtf` (mainly for integration testing with Boulder)

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.
