### ISSUE TITLE
--csr option without certonly

### ISSUE THREAD

**Issue by kroeckx** [certbot/certbot#2206]
The --csr option seems to be doing strange things when used without certonly.  It's asking me if I want to expand the certificate to have more hostnames and things like that.  It seems to have generated it's own keypair again, it's own csr, and so on.  That clearly wasn't what I wanted.

Maybe you're not supposed to run it in that mode?

**Comment by pde** [comment]
Yes, I believe that `--csr` is ignored in "run" mode.  We should document that now, and fix it at some point.

**Comment by pde** [comment]
Ok, I've made a PR (#2218) to fix the doc issue, and this ticket can be for the longer term wishlist item of supporting --csr in all cases.

**Comment by schoen** [comment]
I have an additional PR (#2504) to add an explicit error message for this case to reduce users' confusion. (It doesn't fix the issue, if we regard the issue as tracking the desire to be able to use `--csr` with `run` in the long run.)

**Comment by bmw** [comment]
While this issue came first, I believe it has been superseded by #2373 so I'm closing this issue.
