### ISSUE TITLE
document threat/security model and supported ways of using

### ISSUE THREAD

**Issue by ThomasWaldmann** [certbot/certbot#221]
there is a more-or-less unrelated and out-of-scope security disussion in PR #200 which mostly comes from a unclear / undocumented threat model, still existing general problems in letsencrypt (like always and early requiring root, see also issue #204), scope of what a user can configure (or not), what a user can give (or not) on cli interface.

also it seems to be that usage of letsencrypt is meant not to be limited to direct manual commandline use _by some user_, but also as a tool that is embedded into other tools (like a library or via calling letsencrypt automatically).

to keep the discussion of PR #200 in-scope, I suggest to create documentation that gives threat models we need to deal with, documents already existing solutions against these threats or proposes yet-to-get implemented solutions (and shows how they are effective against the threat in case that is non-obvious).
for stuff that is still to do in general / global for misc. parts of the code, separate issues shall get opened.

**Comment by ThomasWaldmann** [comment]
I have started writing some docs...

**Comment by ThomasWaldmann** [comment]
PR #222 was rejected by @jdkasten.

**Comment by jdkasten** [comment]
@ThomasWaldmann I would gladly accept a PR that is complete on any particular topic.  The PR given did not cover any topic thoroughly and would have created more questions than answers.  I felt the PR wasn't on point and did not cover any of the true security concerns (many of which are already outlined in the Wiki in regards to the master branch).  The PR would have required 10x more effort on my part to fix than it took to write.

I think the only point that caused any confusion was that input intended to be given by the user should not allow arbitrary execution.  I think this is standard and doesn't require much explanation, but I will be sure to add it to the wiki.

**Comment by ThomasWaldmann** [comment]
@bmw so, can you link to the changeset that fixed this issue?

**Comment by bmw** [comment]
@ThomasWaldmann, thank you for commenting. I was going through the issue list trying to update the status of old issues and I certainly didn't mean to dismiss yours. This was created before I even became involved in the project. Reopening.
