### ISSUE TITLE
Notify user they should be running command on target server

### ISSUE THREAD

**Issue by lorensr** [certbot/certbot#2224]
First I read this:

`http://letsencrypt.readthedocs.org/en/latest/using.html#installation`

and then I ran this on my Mac dev machine:

`./letsencrypt-auto`

which told me to run this:

`./letsencrypt-auto certonly`

which resulted in this error:

```
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: mydomain.com
   Type:   urn:acme:error:tls
   Detail: Failed to connect to host for DVSNI challenge
```

After further reading, I'm guessing it's because I'm not running the command on `mydomain.com`?

I think the ideal UX would be:
- When `./letsencrypt-auto` is run, ask user whether they are on the server they want a cert for.
- If yes, continue
- If no, say "This process is much easier if you run this command on the server you want a cert for. Can you run this command on that server?"
  - If yes, print installation options – `git clone` or `yum/apt/etc install letsencrypt` , then exit
  - If no, start the manual process

**Comment by jordila** [comment]
Indeed, the further reading might help in making the whole process much more intuitive.
Subscribe.

**Comment by schoen** [comment]
This is a great point. I opened a PR at

https://github.com/certbot/certbot/pull/6422

to address this.
