### ISSUE TITLE
renewal notice : email should link to documentation

### ISSUE THREAD

**Issue by JohnDenker** [certbot/certbot#2272]
A stated goal of the project is to be easy to use ... easy even for non-experts.
#### Suggestions:
- It would make life easier if the renewal notice email contained a link to the relevant documentation, perhaps https://letsencrypt.org/howitworks/#renewing-a-certificate
- In turn, those instructions should be more correct and more detailed, as discussed in item #2271.

**Comment by pde** [comment]
This probably needs to be re-filed against https://github.com/letsencrypt/boulder

**Comment by JohnDenker** [comment]
Re-filed as   https://github.com/letsencrypt/boulder/issues/1424

**Comment by cpu** [comment]
@pde Do you want to close this? I agree that further discussion should happen on Boulder #1424

**Comment by pde** [comment]
OK, closing; discussion can continue on the boulder ticket.
