### ISSUE TITLE
idea: add support for vulcand

### ISSUE THREAD

**Issue by philhug** [certbot/certbot#228]
Vulcand is a reverse proxy which stores its configuration in etcd.
It can be configured without restarting either using a REST api or etcd directly.
URL: https://vulcand.io/

The process would look like this
1. lets-encrypt regulary checks etcd for new hosts in /vulcand/hosts
2. it generates and sets the ssl key, automatically adds a new frontend/backend to map to letsencrypt
3. requests certificate issuance
4. installs new certificate

Instead of duplicating too much, a docker container running apache could be used and only some additional calls to update the certificates/backend/frontend would be neeaded.

This idea of this issue is to track progress on such an implementation to avoid duplicate effort.

**Comment by hmatinho** [comment]
+1

**Comment by schoen** [comment]
It looks like support subsequently got added upstream by @archisgore.

https://github.com/vulcand/vulcand/pull/339

It's really nice to see upstream support for Let's Encrypt directly from other tools that perform their own TLS termination. If the upstream implementation is lacking something that we could help with, maybe someone could open a new issue.
