### ISSUE TITLE
Don't fail when Detail field is empty

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#2289]
The Detail field of a [Problem Detail](https://tools.ietf.org/html/draft-ietf-appsawg-http-problem-03) is not required, and may in particular be absent when it is redundant with the status field. Right now the client throws a nasty exception when it receives a Problem Detail without a Detail field. Instead it should just print the type.

**Comment by kuba** [comment]
This is not a bug in the implementation, but in the spec (at most). https://ietf-wg-acme.github.io/acme/#rfc.section.5.4: "The “type” and “detail” fields MUST be populated.". I can fix this, but please send a PR against spec first.

**Comment by jsha** [comment]
https://github.com/ietf-wg-acme/acme/pull/84
