### ISSUE TITLE
certonly --standalone fails with multiple domains: Failed to connect to host for DVSNI challenge

### ISSUE THREAD

**Issue by mmehnert** [certbot/certbot#2294]
I was running something like:

./letsencrypt-auto certonly --standalone -d  one.mydomain.org -d two.mydomain.org -d three.mydomain.org

and got the error:

    2016-01-27 14:36:55,569:INFO:letsencrypt.reporter:Reporting to user: The following errors were reported by the server:

    Domain: one.mydomain.org
    Type:   urn:acme:error:tls
    Detail: Failed to connect to host for DVSNI challenge

Creating certificates individually for the subdomains  works - but since I've got a few of them, I'm running into the rate limit with that.

**Comment by mmehnert** [comment]
I just realized that one of the sub-domains did resolve to a different IP (belonging to cloudflare.com).
That may have been the issue - but I have to wait for a week to let the rate limit time out in order to try again.

**Comment by mmehnert** [comment]
It worked with --staging. So I'll close this.

**Comment by night-crawler** [comment]
I have the same problem with multiple subdomains on different ips:
```
./letsencrypt-auto certonly --standalone --agree-tos -d www.example.com -d example.com -d help.example.com -d billing.example.com -d client.example.com -d lk.example.com -d login.example.com -d sip.example.com -d backup.example.com -d sentry.example.com -d error.example.com --test-cert --verbose
```
```
Domain: sentry.example.com
Type:   urn:acme:error:connection
Detail: Failed to connect to host for DVSNI challenge
```

**Comment by bmw** [comment]
@night-crawler, if you're still having this problem, comment and I'll reopen.

**Comment by motion-x86** [comment]
@bmw I'm having this problem as well. If I attempt to fetch a cert for a long list of sub-domains ~15, I get a timeout error, however when I request just a couple of them it goes well so I know it's not a problem with the connection. Any ideas on what can be causing this? is there a way to increase the timeout threshold?
