### ISSUE TITLE
virtualenv vs virtualenv-2.7 path for CentOS 6.x

### ISSUE THREAD

**Issue by centminmod** [certbot/certbot#2300]
In order to install letsencrypt on CentOS 6.x with python 2.7 i use IUS Community YUM repo and that installs virtualenv-2.7 which is at a path that letsencrypt-auto doesn't detect for https://community.letsencrypt.org/t/client-version-0-3-0/9654/2/

```
Creating virtual environment...
./letsencrypt-auto: line 167: virtualenv: command not found
```

path

```
rpm -ql python27-virtualenv | grep bin
/usr/bin/virtualenv-2.7
```

so you might need to edit letsencrypt-auto to check for paths like you did for python binary

**Comment by ohemorange** [comment]
Certbot uses Python 3 on CentOS 6 now.
