### ISSUE TITLE
Ways of specifying what to renew

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#2305]
# 2304 provides for a new `renew` verb. Its default behavior is probably to renew everything possible. However, we also need to figure out possible ways of being more specific about what to renew, like how to interpret `-d` in this context.

**Comment by bmw** [comment]
We want this, but we think that `letsencrypt renew` should renew all certs by default and are pushing this functionality to a later release.

**Comment by bmw** [comment]
See #3615.

**Comment by pde** [comment]
Will be closed as part of #3615
