### ISSUE TITLE
Error that results when run without root is unclear

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#2306]
When running `letsencrypt` without root, I get

```
An unexpected error occurred:
OSError: [Errno 13] Permission denied: '/etc/letsencrypt'
Please see the logfile 'letsencrypt.log' for more details.
```

The underlying reason is that, to run without root, I need to specify `--config-dir`, `--work-dir`, and `--logs-dir`. However, the client doesn't give me any suggestion about this or about the possibility of doing anything (even reading help) without root access.

While a sysadmin would probably conclude that the reason for the `OSError` is simply that the client needs root to run, it would be great to have a clearer and more useful error message in this case.

**Comment by kehugter** [comment]
`certbot.eff.org` shows the instructions as regular user (starting with `$`), which adds to the confusion.

**Comment by bmw** [comment]
This wasn't solved by #3164. We check `/etc/letsencrypt`, `/var/lib/letsencrypt` and `/var/log/letsencrypt` in that order. For this reason I think most people get an error about `/etc/letsencrypt` (such as Seth above in the description of this issue).

**Comment by VoidVolker** [comment]
Yes. Run from root - is bad practice. Only installation and listening port need root. Renew must be safe without root, if not use internal web-server. I'm using node https server and it runs without root, but when certificate updates from root - I need copy files to another directory, then use chown to allow node read certificate and then restart node https server with new certs.

**Comment by pde** [comment]
@bmw is going to do a sweep of all the issues and PRs floating around about root-related errors...
