### ISSUE TITLE
Standalone Renewal: Automation and Domain Verification

### ISSUE THREAD

**Issue by poing** [certbot/certbot#2310]
The renewal process becomes cumbersome, when I have to restart or manually verify the domain.  Especially, when using letsencrypt certs on an unsupported platform.  For instance, AWS Elastic Beanstalk.

Please consider a method to, renew by authenticating against a key or previous validation.  Such as ```privkey.pem``` or other variable.  **Maybe?**

I understand the reason for verification, no looking to circumvent it.  There should me a method to verify once and allow for a simpler re-verification.  How about, allowing the manual method ```.hidden_path_name/file``` to remain valid (unless a single check fails).

Otherwise, for me, renewal involve DNS changes to point to a temporary server.  Renewal, push certs to live system, then revert the DNS.

Anyway, just some thoughts on enhancing the renewal process.  _Thanks for reading._

**Comment by bmw** [comment]
Unfortunately, this is outside of the scope of the Certbot client. Feel free to make an issue/PR against the spec though:

https://github.com/ietf-wg-acme/acme
