### ISSUE TITLE
letsencrypt error aws

### ISSUE THREAD

**Issue by jhiew** [certbot/certbot#2340]
HI Guys,

I hit this error as below when running ./letsencrypt-auto on AWS RHEL v6.6 
Error msg as follow 

Command "/root/.local/share/letsencrypt/bin/python2.7 -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-JRpGnW/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-amq3gz-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.local/share/letsencrypt/include/site/python2.7/cffi" failed with error code

Any suggestion ?

**Comment by pde** [comment]
Hi, can you try the new version of `letsencrypt-auto`?  If you `git pull` to the latest version of the tree, it's in the `letsencrypt-auto-source` subdirectory...

**Comment by jhiew** [comment]
HI Peter,

Thanks. I did try that in the first instance. Still hit the error. ☹

**Comment by ohemorange** [comment]
Certbot uses Python 3 on RHEL 6 now.
