### ISSUE TITLE
SSLEngine on missing from virtualhost config

### ISSUE THREAD

**Issue by AutomatedTester** [certbot/certbot#2355]
I installed a cert on https://futurama.theautomatedtester.co.uk but Apache wouldn't start up. 

`[Wed Feb 03 16:20:25.876214 2016] [ssl:emerg] [pid 24501] AH02311: Fatal error initialising mod_ssl, exiting. See /var/log/apache2/futurama-error.log for more information`

which had 

`
[Wed Feb 03 15:29:40.678671 2016] [ssl:emerg] [pid 12371] AH01910: Oops, no RSA, DSA or ECC server certificate found for 'futurama.theautomatedtester.co.uk:0'?!
`

After Googling around for a while I found it was because `SSLEngine on` was not in the conf file for that virtualhost. This should probably be handled automatically.

**Comment by joohoi** [comment]
This is now added in the included options-ssl-apache.conf closing as fixed
