### ISSUE TITLE
save_successor fixes now lose renewer options

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#2384]
After the recent fixes to `save_successor` to make it update renewal config files, we now lose renewer options (not renewalparams) such as `renew_before_expiry`.

We weren't very worried about this because the use of these options isn't documented or encouraged anywhere; probably everyone using them is directly involved with the development of the project, or so we hope. It would be good for the code that updates the renewal config files to not lose these parameters, though!

**Comment by schoen** [comment]
To be clear, we also lose user-supplied comments, which were one of the reasons that we chose to use `ConfigObj` in the first place.

**Comment by bmw** [comment]
I believe this was resolved with your recent work on `storage.py` @schoen. If I'm wrong, please reopen.
