### ISSUE TITLE
renew --dry-run shouldn't treat rate limits as outright failures

### ISSUE THREAD

**Issue by pde** [certbot/certbot#2416]
Since (1) being staging-ratelimited isn't the same thing as being prod-ratelimited and (2) for most people it'll be fine in the end.

Instead, let's print a note ("Rate limited, but by the test server not the production server") and count these as successes.  And then maybe link to public docs on rate limit in case anyone is anxious or needs to know more.

**Comment by schoen** [comment]
> Since (1) being staging-ratelimited isn't the same thing as being prod-ratelimited and (2) for most people it'll be fine in the end.
> 
> Instead, let's print a note ("Rate limited, but by the test server not the production server") and count these as successes.  And then maybe link to public docs on rate limit in case anyone is anxious or needs to know more.

I don't know offhand how to detect the rate-limiting condition; does
anybody else?

**Comment by pde** [comment]
In order to figure out the different rate limit error types, just run the client with `-n -vv --debug --force-renewal` until you hit them.  There are a few different types, but if you run it in a loop you'll catch them.

**Comment by schoen** [comment]
I pushed work in progress on this to my `dry_run_ratelimits` branch, based on discussions with @bmw. The branch currently tries to raise special dry run rate limit exceptions in appropriate circumstances, but doesn't include the code to catch those exceptions yet.

**Comment by bmw** [comment]
Any progress on this @schoen?

**Comment by bmw** [comment]
I think this could be nice, but I haven't seen much demand for it, especially relative to the 500 other Certbot issues we have. Because of that, I don't think the small Certbot team would be able to prioritize this anytime soon so I'm closing this issue for now.
