### ISSUE TITLE
letsencrypt renew fails to renew authenticator=standalone lineage after installer=apache

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#2419]
Right now, if you do `service apache2 stop` in the hope of renewing `standalone` lineages, but the renewer decides to renew any `installer=apache` lineage, the renewer will call `.restart()` which will then cause `apache2` to start again! That, in turn, will cause TCP ports to be in use and `standalone` to be unable to renew its lineages.

The `apache` plugin should not actually "reload" a non-running Apache; there's arguably no need to do so because the new cert, if any, will be picked up automatically the next time that Apache is started.

**Comment by brendanhowell** [comment]
This seems to also have the side-effect of starting apache2 on machines that are not necessarily using it.  I use nginx which I stopped for the renew.  After successful renewals, I found apache2 had taken over port 80 and had to be stopped manually.  I do have apache2 installed on my box but it is only there to satisfy a few dependencies and does not run.

**Comment by bmw** [comment]
This is an interesting idea and would solve the problems in #5486 and #5555. My initial concerns are:

1. How hard is it to detect whether or not the server is already running in a reliable, platform independent way?
2. This might be OK, but this doesn't do anything to help the case where you're mixing standalone and Apache authenticators for different lineages unless the Apache authenticator turns Apache off it wasn't already running. Maybe we should do this too though.

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.
