### ISSUE TITLE
Tolerate renaming of renewal configs

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#2422]
Right now some code derives paths from the "lineage name", defined as the portion of the renewal config basename that precedes the traiiling `.conf`. For renewal/successor purposes, there is no apparent need to do this because all of the path components are explicitly specified inside the file.

A consequence of the current behavior is that you can't safely rename a renewal config file, even if you don't change its contents.

A benefit of the current behavior is a form of referential integrity checking: if `example.com.conf` doesn't exist, it's automatically safe to create `../archive/example.com/`, which wouldn't be true if renewal config files could be renamed. On the other hand, users can simply rename them now with `mv`, but they can get various unexpected errors after doing so.

Improving this behavior would also be useful when thinking about changes and migrations in the `/etc/letsencrypt` tree, for example the suggestion to separate private and public keys into separate directory hierarchies.

**Comment by schoen** [comment]
As an example of what can go wrong if you do rename a renewal config file today, if you change `example.com.conf` to `something-else.conf`, and then get a new certificate that includes `example.com` as the first SAN (with `--duplicate` if it's the same as the contents of `something-else.conf`), you'll get a failure to save the new lineage because `../archive/example.com/` already exists (and you'll also get a new *empty* `example.com.conf`, which can't be right!).

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.
