### ISSUE TITLE
test_leauto_upgrades should be fixed for amazonlinux

### ISSUE THREAD

**Issue by pde** [certbot/certbot#2427]
Currently, it fails because `letsencrypt-auto` didn't work on that platform for the 0.1.0 release.  So we should begin with the first working version on the amazonlinux AMIs

**Comment by SwartzCr** [comment]
assigning this to @bmw who is assigned to #2189 and thus plausibly can manage this

**Comment by bmw** [comment]
I'm personally leaning towards removing `amazonlinux` support from `certbot-auto` entirely (see [my community forum post](https://community.letsencrypt.org/t/getting-error-couldnt-get-currently-installed-version-for-letsencrypt-when-trying-to-renew-my-certificates/27031/21?u=bmw)). `amazonlinux` support in `*-auto` has basically never worked and while I haven't spent much time on it, I have yet to see anyone suggest a reliable solution to the problems we have.

**Comment by SwartzCr** [comment]
We have removed support for amazon linux so I am going to close this issue. If the amazon linux team wants to package certbot they can get in touch with us (but have so far not responded to our requests to discuss this)
