### ISSUE TITLE
Add a "register" verb

### ISSUE THREAD

**Issue by pde** [certbot/certbot#2446]

**Comment by bmw** [comment]
To provide more information to this issue, @jvanasco added in #2980:
>I'm not sure if this is a dupe of #2446 , which has no description

>The intent of this ticket is that the certbot program would have a switch that will (only) create a new account (with TOS registration, etc).

>There are at least 2 reasons for this:

>a user may want to create an account / accept the TOS on "machine 1", but run certbot on "machine 2"
a user may want to use another client, but that client does not offer the account creation/management - and expects the account to be created on the official client.

>full disclosure: i wrote a client that I'm opensourcing and we're the second case.
