### ISSUE TITLE
Apache plugin error: 'Error parsing variable' when envvars are used

### ISSUE THREAD

**Issue by chriteixeira** [certbot/certbot#2481]
When I use the command ./letsencrypt-auto --apache I receive the following message:

> The apache plugin is not working; there may be problems with your existing configuration.
> The error was: PluginError(u'Error Parsing variable: ${INSTANCE_ADDRESS}',)

Looks like the plugin is not being able to parse the env_var in the address field. Here's the conf file with the env_var:
`<VirtualHost *:80>

```
ServerAdmin <*removed*>
ServerName <*removed*>
ServerAlias ${INSTANCE_ADDRESS}

ErrorLog ${APACHE_LOG_DIR}/author.log
CustomLog ${APACHE_LOG_DIR}/access.log combined

RequestHeader unset Authorization
```

</VirtualHost>
`

**Comment by bmw** [comment]
Another user encountered this problem with a directive like the following in a virtual host:
```
ServerName ${FOO}.example.org
```

**Comment by bmw** [comment]
A very detailed report of this problem was provided in #6345.

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.
