### ISSUE TITLE
Let user specify challenge file owner and mode for webroot authentication

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#2488]
This was requested at

https://community.letsencrypt.org/t/suggestion-flag-to-set-challenge-file-owner-permission/10965

**Comment by matuskosut** [comment]
if you are passing by you may use an info, that it is supposed to use the owner of the parent folder, according to this source:
./certbot/plugins/webroot.py:178
but for me it was not working, it was still set to root/ the owner of the process

**Comment by bmw** [comment]
I'm personally more interested in seeing #2096 resolved than this issue. For that reason, I'm closing this, but if people have a strong preference for this with reasonable use cases that #2096 doesn't solve, I'm happy to reconsider.
