### ISSUE TITLE
--dry-run creates persistent keys in /etc/letsencrypt/keys

### ISSUE THREAD

**Issue by pde** [certbot/certbot#2495]
It shouldn't... probably they should be deleted.  Maybe they should also be in /tmp though that reduces the realism of the dry run simulation.

**Comment by bmw** [comment]
It also saves the staging account (which I believe you're aware of) and the CSR it creates to obtain the new certificate.

**Comment by pde** [comment]
Yup.  I think keeping the staging account is a lesser-of-two-evils thing, since it's actually useful.  The keys and CSRs don't have a reason for persisting, really.

**Comment by bmw** [comment]
We basically just need to add `if not config.dry_run` around the place we write the keys and CSRs to disk.

**Comment by dhuang** [comment]
Grabbing this one!
