### ISSUE TITLE
sed -i '4arenew_before_expiry = 10 years' "/var/folders/18/96y990v ...": invalid command code f

### ISSUE THREAD

**Issue by sunny-g** [certbot/certbot#2517]
On OS X 10.10.5, when installing `letsencrypt` as part of running the `boulder`'s integration tests (`RUN="integration" ./test.sh`), I get the following error stemming from `letsencrypt/tests/boulder-integration.sh`:

``` sh
+ sed -i '4arenew_before_expiry = 10 years' /var/folders/.../conf/renewal/le.wtf.conf
sed: 1: "/var/folders/18/96y990v ...": invalid command code f
```

I'm pretty unfamiliar with `sed` and everything I've found suggests that the command should look differently on OS X, though I'm unsure how. Any insights?

**Comment by 0xmohit** [comment]
Just wondering if `perl` could be used instead of `sed` here.  I guess that it's already being used in git commit hooks so wouldn't introduce a new dependency.  Thoughts?

**Comment by bmw** [comment]
Many of our development scripts assume that you're using GNU tools causing the problems on macOS here. I'd be open to a PR that fixes this, but I don't think this is something we'll ever have the time to do ourselves so I'm closing this issue as wontfix.
