### ISSUE TITLE
automatic virtualenv package name detection broken on Ubuntu 14.04

### ISSUE THREAD

**Issue by vondrt4** [certbot/certbot#2532]
...because of:
# apt-cache show virtualenv

N: Can't select versions from package 'virtualenv' as it is purely virtual
N: No packages found
# echo $?

0

I've just cloned the master branch.

By the way, I think that installing system packages from inside a script without asking the user, and before being able to show help, is highly rude.

**Comment by akheron** [comment]
I have the same issue on Ubuntu 14.04. `apt-cache` exit status is 0 even though virtualenv is not an installable package.

**Comment by starchy** [comment]
This also affects Debian Wheezy.

**Comment by ohemorange** [comment]
There's now a PPA for Ubuntu.
