### ISSUE TITLE
Instructions to create a certificate for S3 static hosted site in a bucket

### ISSUE THREAD

**Issue by lordloh** [certbot/certbot#2539]
I have a AWS hosted site. Letsencrypt certificate worked well on apache on EC2. But my images are in an S3 bucket.

It would be nice to have some instructions to create a certificate for S3 static hosted site in a bucket.  Attempt to generate it gets me - 

```
Failed authorization procedure. cdn.example.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Failed to connect to host for DVSNI challenge

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: cdn.example.com
   Type:   connection
   Detail: Failed to connect to host for DVSNI challenge

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.

```

**Comment by coloradomountain** [comment]
I am using lets encrypt on one of my static S3 sites, I will do add documentation to resolve this issue.

**Comment by michelmelo** [comment]
@coloradomountain :+1:

**Comment by ashwin31** [comment]
Hi @coloradomountain can you look into #1727 and suggest how it can be done? I saw your pull request #2539 and it seems to be for s3, does it work with cloudfront too?

**Comment by bmw** [comment]
Our documentation has improved quite a bit in the last few months, including us providing a link to the third party s3front plugin in our [documentation](https://certbot.eff.org/docs/using.html#third-party-plugins). With that said, I created certbot/website#175 to track the issue of adding an option for this use case to our instruction generator. I'm closing this in favor of that issue.
