### ISSUE TITLE
letsencrypt-auto gives "sudo" is not available

### ISSUE THREAD

**Issue by lazharichir** [certbot/certbot#2540]
Hello guys,

Look at the below, I am trying to set it up.

>
> bash-3.2$ ./letsencrypt-auto —help
> “sudo” is not available, will use “su” for installation steps…
> Sorry, I don’t know how to bootstrap Let’s Encrypt on your operating system!
> 
> You will need to bootstrap, configure virtualenv, and run a peep install manually.
> Please see https://letsencrypt.readthedocs.org/en/latest/contributing.html#prerequisites
> for more info.
> Checking for new version…
> ./letsencrypt-auto: line 108: [: too many arguments
>   File “/tmp/tmp.jEueeZ1320/fetch.py”, line 57
>     except (HTTPError, IOError) as exc:
>                                  ^
> SyntaxError: invalid syntax
> bash-3.2$ 
>

I am hosted on TSOHOST.COM on Apache -- any guess on what is going wrong here?

**Comment by coloradomountain** [comment]
Does your hosting provider allow root access or use of the sudo/su commands?  You can 
also try prepending sudo to the command like so:

sudo ./letsenncrypt-auto

**Comment by SecretA** [comment]
i tried the command:  sudo ./letsenncrypt-auto
it outputs: 
-bash: sudo: command not found
 any suggestions??

**Comment by bmw** [comment]
@SecretA, you should not run `letsencrypt-auto` with `sudo`. It will prompt you and ask for `sudo` permissions if it needs it.

**Comment by bmw** [comment]
There's a couple things going on here.

@lazharichir, what OS are you using? It appears `letsencrypt-auto` doesn't (yet) support your OS, however, you found a bug. The script should exit after printing instructions for how to install the project yourself, however, it didn't do so. I opened #3111 to solve this issue.

@SecretA, while you shouldn't be running `letsencrypt-auto` with `sudo`, it appears that you don't have `sudo` installed on your system at all.
