### ISSUE TITLE
Suggestion- Explain the mechanism at the top of "user docs" and "--dry-run" or manual testing for `webroot`

### ISSUE THREAD

**Issue by jvanasco** [certbot/certbot#2543]
1. The top of the user docs should plainly state that letsencrypt requires domain validation, which is either automatically handled through a server-specific plugin, run through a `standalone` server, or read through a specially configured `webroot`.  It's not until you're deep in the docs that it becomes clear one must stop or restart their main webserver.  That should be up top in a narrative overview.

2. There should be some way to test the 'webroot' system.  This could be a `--dry-run` flag that writes to the webroot and reads from it's public address to ensure it's set up right for reading and writing, or maybe some manual instructions on how to test/ensure.

**Comment by nitmir** [comment]
You do not need to stop or restart your main webserver if using ```webroot```.

**Comment by bmw** [comment]
As nitmir said, you do not need to stop/restart your webserver to use `webroot`.

Additionally, there is a `--dry-run` flag which uses the Let's Encrypt CA's test server to see if you're solving the challenges correctly. The test server has no effect on production rate limits.
