### ISSUE TITLE
Add integration test cases for must staple and ECDSA

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#2545]
Now that Boulder supports Must Staple and ECDSA, it would be nice to have test cases for them. We would have to manually generate CSRs for them, like so:

Must Staple:
`openssl req -new -sha256 -key rsa.key -subj "/" -reqexts SAN -config <(cat /etc/ssl/openssl.cnf <(printf "[SAN]\nsubjectAltName=DNS:must-staple.le.wtf\n1.3.6.1.5.5.7.1.24=DER:30:03:02:01:05")) -out must-staple.csr.pem`

ECDSA:
`openssl ecparam -genkey -name secp384r1 > privkey-p384.pem ; openssl req -new -sha256 -key privkey-p384.pem -subj "/" -reqexts SAN -config <(cat /etc/ssl/openssl.cnf <(printf "[SAN]\nsubjectAltName=DNS:ecdsa.le.wtf")) -outform der -out csr-p384.der `

**Comment by jsha** [comment]
(Also note: Must Staple is not yet enabled in test/boulder-config.json, but we can do that soon).

**Comment by kerio92** [comment]
95% bikeshedding, but you should probably use example.com or example.org, not some domain that might end up being real

**Comment by jsha** [comment]
Ping on this: Must staple now has its own flag so it will be easier. @osirisinferi, @benileo, any interesting in picking up this issue?

**Comment by benileo** [comment]
@jsha I can take a stab at it.
