### ISSUE TITLE
What to do if parsing of renewal config file fails?

### ISSUE THREAD

**Issue by lu-x** [certbot/certbot#2550]
Seems like one of my config-files is broken somehow.
I get this when trying to renew my cert:
`WARNING:letsencrypt.cli:Renewal configuration file /etc/letsencrypt/renewal/*.conf is broken. Skipping.` and
`Additionally, the following renewal configuration files were invalid:
/path/to/conf (parsefail)
`

**Comment by pde** [comment]
That's odd.  Is there anything in `/etc/letsencrypt/renewal/`?

**Comment by pde** [comment]
Also, what version of the client are you running?

**Comment by pde** [comment]
Or is it possible that you actually edited the output to make it say `*.conf`?  Because I can't see how the 0.4.0 client could have produced that message...

**Comment by pde** [comment]
In general, you either want to fix the renewal conf file, or delete it and optionally the associated certs in `/etc/letsencrypt/live` and `/etc/letsencrypt/archive`, then re-obtain the cert; when you do that, you'll get a new and correct renewal conf file...

But my questions about the mysterious `*.conf` in your error message still stand.

**Comment by kas70** [comment]
yep, sorry. * is a placeholder for my domain. ok, thanks, i'll try.

**Comment by kas70** [comment]
Don't know exactly what is broken. I obtained a new certificate for the same domain. Now the folder is named domain-0001 in /etc/letsencrypt/live/.
Also, i'm not able to revoke the old cert (i get: `letsencrypt: error: argument --cert-path: No such file or directory`).

**Comment by bmw** [comment]
> Don't know exactly what is broken. I obtained a new certificate for the same domain. Now the folder is named domain-0001 in /etc/letsencrypt/live/.

If you want the folder to use the same name, you should delete (or move) the files/directories `/etc/letsencrypt/renewal/domain.conf`, `/etc/letsencrypt/live/domain`, and `/etc/letsencrypt/archive/domain`. If the certificates you're having problems with are the only ones you care about on this system, it may be easier to just delete (or move) the entire `/etc/letsencrypt` directory.

> Also, i'm not able to revoke the old cert (i get: letsencrypt: error: argument --cert-path: No such file or directory).

I have to ask, does the path you provided to `--cert-path` exist?

**Comment by kas70** [comment]
Renaming the files/directories didn't work. I got the parser error again. However, after changing it back, everything seems to work fine.
A little off-topic: Is it save to delete revoked certificate-folders?

**Comment by pcav** [comment]
I have the same error, and the file is empty. Any suggestion on how to properly fix this would be welcome.

**Comment by bmw** [comment]
@kas70, yes, it should be safe to delete revoked certificate folders. To do this properly, you should delete `/etc/letsencrypt/archive/<domain>`, `/etc/letsencrypt/live/<domain>`, and `/etc/letsencrypt/renewal/<domain>.conf` (assuming default paths).

@pcav, your file in `/etc/letsencrypt/renewal/domain.conf` is empty? Can you describe what you've done with `letsencrypt` so far?

**Comment by pcav** [comment]
Thanks. Yes, the file is empty. Sorry I did too many attempts, and I cannot replicate the steps.
I'm waiting to be allowed to issue new certificates, I'll redo all more cleanly and I'll report back.

**Comment by gonchs** [comment]
In case it may help someone, the parsefail issue could also occur because the cert files in /etc/letsencrypt/live/yoursite.com are NOT symlinked from /etc/letsencrypt/archive/youtsite.com. This fixed it for me:

```
sudo mv /etc/letsencrypt/live/youtsite.com/fullchain.pem /etc/letsencrypt/live/youtsite.com/fullchain.pem.old
sudo ln -s /etc/letsencrypt/archive/youtsite.com/fullchain1.pem /etc/letsencrypt/live/youtsite.com/fullchain.pem

sudo mv /etc/letsencrypt/live/youtsite.com/cert.pem /etc/letsencrypt/live/youtsite.com/cert.pem.old
sudo ln -s /etc/letsencrypt/archive/youtsite.com/cert1.pem /etc/letsencrypt/live/youtsite.com/cert.pem

sudo mv /etc/letsencrypt/live/youtsite.com/chain.pem /etc/letsencrypt/live/youtsite.com/chain.pem.old
sudo ln -s /etc/letsencrypt/archive/youtsite.com/chain1.pem /etc/letsencrypt/live/youtsite.com/chain.pem

sudo mv /etc/letsencrypt/live/youtsite.com/privkey.pem /etc/letsencrypt/live/youtsite.com/privkey.pem.old
sudo ln -s /etc/letsencrypt/archive/youtsite.com/privkey1.pem /etc/letsencrypt/live/youtsite.com/privkey.pem
```

**Comment by lukyer** [comment]
@gonchs thans, it helped me with this issue!

**Comment by AykutCevik** [comment]
@gonchs Thanks!

**Comment by meansl63** [comment]
gonchs - this was the exact fix i needed for my renew process to work after being broken. Thanks alot

**Comment by keith24** [comment]
@kas70 Taking a wild guess here... You don't have wildcards in your `letsencrypt.cli`, do you? They [aren't supported](https://github.com/certbot/certbot/issues/66#issuecomment-160487331).

**Comment by alexweissman** [comment]
I'm having this problem with nginx on Ubuntu:

```
WARNING:letsencrypt.cli:Renewal configuration file /etc/letsencrypt/renewal/<site>.conf is broken. Skipping.
** DRY RUN: simulating 'letsencrypt renew' close to cert expiry
**          (The test certificates below have not been saved.)

No renewals were attempted.

Additionally, the following renewal configuration files were invalid: 
  /etc/letsencrypt/renewal/<site>.conf (parsefail)
** DRY RUN: simulating 'letsencrypt renew' close to cert expiry
**          (The test certificates above have not been saved.)
0 renew failure(s), 1 parse failure(s)
```

My symlinks are correct.

**Comment by egeu5** [comment]
I had the same issue - all the symlinks where correct. I tried different solutions but none worked for me. At the end it was fixed by:
1.  mv /etc/letsencrypt/renewal/YOURDOMAIN.conf /etc/letsencrypt/renewal/YOURDOMAIN.conf.old
2. mv /etc/letsencrypt/archive/ /etc/letsencrypt/archive.old
3. Run certbot certonly --webroot -w /var/www/html/SOMEDIRECTORY/ -d SOMEDOMAIN.bla (In my opinion you should first always try it with --dry-run)
4. Furthermore the certificates where saved under a new location (instead of /etc/letsencrypt/live/mydomein.bla/ they where now in /etc/letsencrypt/live/SOMEDOMAIN.bla-0001/) So i had to edit the config files of the domains (eg. nano /etc/httpd/sites-enabled/YOURDOMAIN.bla-le-ssl.conf and change the path lines of the cert, privkey and chain)
It's not a real solution but worked for me.
I'm using Centos 7 - some files are saved under a different location if you use another distro (eg. /etc/apache insted of /etc/httpd

**Comment by alexweissman** [comment]
For me, it ended up being a combination of issues:

- Updating from `letsencrypt` to the new `certbot` client.
- Permissions.  I have root login disabled on my VPS.  When I ran `certbot-auto renew` it still failed with a "parse error", but then when I ran `sudo certbot-auto renew`, it succeeded!

I didn't want to have to run as root so I gave my user account ownership and permissions of my config file, as well as my certs and the log file, but `certbot-auto renew` still failed with a "parse error".  So, it looks like it has to be run with root permissions.  Fortunately, adding it to `sudo crontab -e` seems to let it run as root automatically now.

**Comment by helgatheviking** [comment]
>Updating from letsencrypt to the new certbot client.

This helped me too. The install from the ubuntu repo is apparently still letsencrypt. I had to install from a git clone. Though renewal still won't run successfully while apache is running, but I presume that's a different issue.

**Comment by vstokarev** [comment]
I had the same issue and resolved it by just copying conf file from another domain and replacing domain name in its name and its content. Can be helpful if you have several domains and one of them doesn't want to renew, but another one works fine.

**Comment by counterpoint** [comment]
I'm having this problem with certbot version 0.10.2 in Debian Stretch. A number of domains were set up, so far as I know in exactly the same way. When attempting "certbot renew" 13 domains appear correct - currently they are listed and skipped as renewal is not yet needed. But the other 7 are listed under "Additionally, the following renewal configuration files were invalid:". Each one is listed as "/etc/letsencrypt/renewal/example.com.conf (parsefail)". I cannot see any difference between the files that are described as "parsefail" and the corresponding files that do not fail (apart from the different domain names). All the files mentioned in the .conf file exist, are owned by root and have reasonable permissions. Is there any robust solution for this?

**Comment by counterpoint** [comment]
Probably my fault, although I don't know how. Deleting and recreating the problem domains fixed it.

**Comment by Bielecki** [comment]
@gonchs thank you. I wrote a short script using your fix, so if anyone has more than one domain - you can use it from my repo: [Bielecki/certbot-renew_fix](https://github.com/Bielecki/certbot-renew_fix)

**Comment by schoen** [comment]
I think #775 and #6276 are currently better places to track this in our issue tracker (although I agree that this is still a real concern).

**Comment by l2zeo** [comment]
> @gonchs thank you. I wrote a short script using your fix, so if anyone has more than one domain - you can use it from my repo: [Bielecki/certbot-renew_fix](https://github.com/Bielecki/certbot-renew_fix)

It was very helpful.
Thank you.

**Comment by ermenkov** [comment]
Just delete the got damn ```/etc/letsencrypt/renewal/domain.com.conf``` file.

That costed an hour of my life that nobody will give me back.

**Comment by xibsked** [comment]
> 
> 
> Just backup the got damn `/etc/letsencrypt/renewal/domain.com.conf` file and delete it.
> 
> That costed an hour of my life that nobody will give me back.

You saved my precious hours ! Thanks a ton!

**Comment by KMJ-007** [comment]
I am still facing the same error,

I tried all the above solutions, 

tried symbolic links,

tried to reinstall certbot completely,

what am I doing wrong ?

![image](https://user-images.githubusercontent.com/86996507/214506181-b43f2de1-19a4-415a-a8a0-0362858f7a3f.png)

**Comment by counterpoint** [comment]
Sorry, I don't know. But I've moved to an automated DNS based mechanism that creates wild card certificates. I've made it generally available for a small fee at https://encrypt.bsr.cloud. Works pretty well.
