### ISSUE TITLE
Non standard path(s), might not work with crontab installed by your operating system package manager

### ISSUE THREAD

**Issue by pde** [certbot/certbot#2552]
It's really weird to get this message if you aren't using OS packages...

**Comment by mitar** [comment]
Yes. How can I make this quiet? Because now I am getting in my own cron all the time to my email. :-)

**Comment by pde** [comment]
@mitar running with `--quiet` /  `-q` *should* suppress that message?

**Comment by mitar** [comment]
@pde: [This is what I use](https://github.com/tozd/docker-nginx-proxy/blob/master/letsencrypt/dockergen.sh#L23) and it does not suppress it.

**Comment by mitar** [comment]
But it is true. It seems to be output only when a key is generated, if I have it in cron and nothing has to be done (no keys are to be renowed) it is quiet. Only when a key is generated this additional warning comes out.

**Comment by ezekiel** [comment]
Would really like to see this message squelched by `--quiet`.

**Comment by ezekiel** [comment]
One simple way to handle this is adjusting the message level from "Warning" to "Info".
To this end, I have submitted pull request #5743 

If this simple method is not suitable, I would really appreciate further guidance, and I will be happy to adjust/enhance the implementation.

**Comment by schoen** [comment]
@pde, would you be willing to opine on @ezekiel 's proposed solution?

**Comment by ezekiel** [comment]
output from `--help` for various commands gives the following info for `--quiet`:

> Silence all output except errors. Useful for automation via cron. Implies --non-interactive.

As such, perhaps it is a better choice for me to track down the code to make that accurate and to silence all messages below "Error" level, rather than decrease a "Warning" message to an "Info" message to silence it.

**Comment by ezekiel** [comment]
Found it: the constant called `QUIET_LOGGING_LEVEL` is currently set to `WARNING`, I have another branch prepared with a very simple change for this constant (to `ERROR`). I can submit this as a new pull request, which may be a better choice overall.

**Comment by ohemorange** [comment]
Hey @pde, any opinions here?

**Comment by pde** [comment]
My sense is that many of those are serious, fatal or almost-always-fatal conditions that should be flagged despite running in cron. So if we were going to take #5773 we should probably also define semantics for these levels formally and refactor many of the `WARNING`s to `ERROR`s.
