### ISSUE TITLE
A query to request the quota status (like a '-quota' option)

### ISSUE THREAD

**Issue by quenenni** [certbot/certbot#2555]
Is it possible to know my quota status?

Isn't there an argument (I couldn't find) to achieve that without actually create a certificate?

In my context, in the hosting control panel, I should ask for our quota status and, if already at the max, explain the users the situation and that they have to wait a few days in order to be able to create their owncloud instance (and have their certificate created and the owncloud only accessible via https).

Thanks

**Comment by quenenni** [comment]
I'm still a bit surprised I'm the first one to ask that (well I didn't find anything related to this). 

I have no problem with the quota system if it helps you manage your system.
But as soon as you put such a feature in place, you should provide a way for the people to know what's the status outside the cert creation procedure.

Can't you add an option, like '-quota' or 'quota-status' that just send back that info and the date when new cert creation will be available?

I'm sure it's already (more or less) implemented as you have to do the same when we ask for a new cert.

Without it, it's very difficult to script the auto management of new certs in a sharing environment.

**Comment by eedev** [comment]
I would also like this, it would be great for planning ahead :+1:

**Comment by bmw** [comment]
While this issue was first, it seems it has been superseded by #2637 as there has been much more discussion there. With this in mind, I'm closing this issue.
