### ISSUE TITLE
find_best_vhost cleanup

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#2560]
There's a couple things we can do here:
1. `find_best_vhost` now awards more points to exact `ServerName/ServerAlias` matches than to wildcards. Apache doesn't do this and I don't think we should either.
2. Currently, if there are multiple vhosts with the same number of points, we arbitrarily pick the first one. We shouldn't be doing this, at least not in all cases as it could be the sign of a problem with someone's Apache config.

**Comment by joohoi** [comment]
IPv6 should be taken in to the consideration, as we'll have to fit it in sooner than later (and hopefully sooner). It will give us a fair bit of a challenge with the priorization & (de)duplication.

**Comment by jmorahan** [comment]
[This person in the forum](https://community.letsencrypt.org/t/can-not-renew-expand-certificate/66359) ran into trouble because they had declared separate vhosts on IPv4 and IPv6 with the same ServerName, and Certbot picked the first which happened to be IPv4.

**Comment by joohoi** [comment]
Thanks for bringing this up @jmorahan ! I believe the correct way forward here would be to configure all the VirtualHosts matching the requested domain for both challenge validation, and the actual HTTPS configuration as well.

**Comment by sydneyli** [comment]
It looks like this [may have come up again](https://community.letsencrypt.org/t/how-to-force-certbot-to-use-domain-name-not-nameserver/73675) on the forums!

**Comment by bmw** [comment]
I think the problems I flagged in my original post here are still valid.
