### ISSUE TITLE
unable to generate certs in local machine?

### ISSUE THREAD

**Issue by calidion** [certbot/certbot#2571]
It seems that this program can run on exactly the server where the certs be installed?

I got errors from my local machine:

```
Failed authorization procedure. xxx.xxx.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Failed to connect to host for DVSNI challenge


IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: xxx.xxx.com
   Type:   connection
   Detail: Failed to connect to host for DVSNI challenge

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.

```

**Comment by bmw** [comment]
In general you are correct that `letsencrypt` must run on the machine pointed to by your DNS records. The benefit of doing this is that you can set up automatic renewal so you don't have to worry about your certificates expiring.

If you can/do not want to do this, you can use the [manual](https://letsencrypt.readthedocs.org/en/latest/using.html#manual) plugin to obtain a certificate while running `letsencrypt` on your local machine. With that said, this plugin lacks some polish and is still under development.

**Comment by calidion** [comment]
@bmw 

it is not working by adding --manual.

**Comment by bmw** [comment]
@calidion, if you're using the manual plugin, you can run `letsencrypt` on your local machine, however, you must run the shell script that is output on the machine pointed to by your DNS records.

**Comment by calidion** [comment]
@bmw 

Sometimes we don't have a server to be able to verify our domain, because our sites are hosted by some restricted server. they will only allow us to upload certificates, but won't let us compile or run programs.

so current method won't work well for such situations.

I would like to suggest a simple way to verify the ownership of a dns.
1. generate a special subdomain and a special key
2. users should add such subdomain
3. verify subdomain if it is created
4. execute current commands respectively if the sub domain is verified but with the special key
5. then we get the generated certifications.

**Comment by bmw** [comment]
I was misleading in my earlier post. You can either run the shell script output by `letsencrypt` or create a file at a specific path which should work in your case. An example of the instructions from `letsencrypt` are:
```
Make sure your web server displays the following content at
http://example.com/.well-known/acme-challenge/PuZ2DGq32dKyNH_XGDbA8LBcvgec5Autp0MYdS8O3C4 before continuing:

PuZ2DGq32dKyNH_XGDbA8LBcvgec5Autp0MYdS8O3C4.ig8UlfjDc0emv6RIedoqYNZO_KS2JV0qqBmpQ57jwQc
```

**Comment by calidion** [comment]
@bmw 
how can i get such instruction?

I executed:

```sh
./letsencrypt-auto certonly --standalone --email calidion@gmail.com -d t1bao.com -d www.t1bao.com -d m.t1bao.com -d o.t1bao.com -d open.t1bao.com -d oauth.t1bao.com -d mobile.t1bao.com -d api.t1bao.com
```

but got the follow errors:

```sh
- The following errors were reported by the server:

   Domain: open.t1bao.com
   Type:   unknownHost
   Detail: No IPv4 addresses found for open.t1bao.com

   Domain: mobile.t1bao.com
   Type:   unknownHost
   Detail: No IPv4 addresses found for mobile.t1bao.com

   Domain: o.t1bao.com
   Type:   unknownHost
   Detail: No IPv4 addresses found for o.t1bao.com

   Domain: oauth.t1bao.com
   Type:   unknownHost
   Detail: No IPv4 addresses found for oauth.t1bao.com

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.
 - The following errors were reported by the server:

   Domain: www.t1bao.com
   Type:   unauthorized
   Detail: Correct zName not found for TLS SNI challenge. Found
   '*.dpfile.com, *.cdn.myqcloud.com'

   Domain: t1bao.com
   Type:   unauthorized
   Detail: Correct zName not found for TLS SNI challenge. Found
   '*.dpfile.com, *.cdn.myqcloud.com'

   Domain: m.t1bao.com
   Type:   unauthorized
   Detail: Correct zName not found for TLS SNI challenge. Found
   'bizz.vizz.buzz, www.bizz.vizz.buzz'

```

**Comment by bmw** [comment]
Replace `--standalone` with `--manual`. You'll get an output similar to my previous post for each domain name which is a bit cumbersome, but each is solving a challenge proving you have control over the specified domain.

**Comment by bmw** [comment]
These errors though:
```
- The following errors were reported by the server:

   Domain: open.t1bao.com
   Type:   unknownHost
   Detail: No IPv4 addresses found for open.t1bao.com

   Domain: mobile.t1bao.com
   Type:   unknownHost
   Detail: No IPv4 addresses found for mobile.t1bao.com

   Domain: o.t1bao.com
   Type:   unknownHost
   Detail: No IPv4 addresses found for o.t1bao.com

   Domain: oauth.t1bao.com
   Type:   unknownHost
   Detail: No IPv4 addresses found for oauth.t1bao.com

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.
```
are caused by the lack of a DNS A record for that domain, as suggested by the output.
