### ISSUE TITLE
DNS problem: SERVFAIL looking up A for <domain>.co.uk

### ISSUE THREAD

**Issue by samkelleher** [certbot/certbot#2580]
Unable to do the email verification (that does the MX record lookup). Or certificate generation (that does the A record lookup).

Both fail.

The server in question is:
* Hosted by Dyn Inc (one of the larges DNS providers).
* Setup and functioning normally, and has been for a long time.
* Using DNSSEC, which is configured and working normally.

The command is:
```
./letsencrypt-auto certonly --standalone --register-unsafely-without-email -d example.co.uk -d www.example.co.uk --agree-tos
```

Doing a `dig a example.co.uk` (using Google Public DNS as the servers resolver), the IP is returned as expected, so the DNS appears to be working correctly. Also, since Google Public DNS supports DNSSEC, the successful resolution indicates that it isn't a DNSSEC issue).

I'm running the command from a Debian 8.3 box, fresh brand new instance on Digital Ocean. The IP for the box is also the domains IP.

Same issue on Fedora 23 when installed by the package manager. On a different server, also on Digital Ocean. Again, a manual `dig` reveals the IP without issue.

**Comment by BredeBS** [comment]
I'm in the same issue. Works just one time (at number n retry in one server), but the two others servers doesn't resolve the mx.
I tried with your `--register-unsafely-without-email` and the debug options `-vvvvvvv --text` and works fine:

`./letsencrypt-auto certonly --standalone --register-unsafely-without-email --agree-tos -d example.com -vvvvvvv --text`

**Comment by samkelleher** [comment]
It seems to be an intermittant DNS issue at letsencrypt's end.  While my issue is still not resolved. Using the `--text` flags I am able to see that is their server at `acme-v01.api.letsencrypt.org` that returns the `SERVFAIL looking up A for example.com` error as part of the error attribute in the JSON response.

**Comment by kaminoo** [comment]
I'm having the same problem with two of my domains, that letsencrypt is unable to get the A records, although I have A, and AAAA uploaded correctly in the DNS.
Any workarounds?
Any info I can provide for you to solve this?

**Comment by samkelleher** [comment]
I think there is strong DNS caching at the servers running letsencrypt services, eventually (24 hours +) the issue for the specific domain I was trying to setup resolved itself.

**Comment by kaminoo** [comment]
In my case its been more than 10 days and nothing, still broken

**Comment by bmw** [comment]
Are you guys still having this issue?

If so, I encourage you to open an issue at https://github.com/letsencrypt/boulder.
