### ISSUE TITLE
Do not install mod_ssl - it can cause an outage

### ISSUE THREAD

**Issue by driskell** [certbot/certbot#2589]
Hi,

I have been having random outages on a development environment recently, usually during a configuration converge or (most often) after a reboot, where Apache would all of a sudden steal port 443 and mean Nginx couldn't bind to it anymore when it was restarted.

I found the cause was the `mod_ssl` package kept being installed (it's a CentOS system). It seemed really odd that it was being installed as it was completely unwanted. Initially I thought I had messed up somewhere and accidentally installed it, but it happened another two times.

I finally found the problem was Let's Encrypt - letsencrypt-auto seems to install `mod_ssl` onto the server because it has `httpd` package installed. It's just sods law that this completely breaks my configuration. :cry: 

Is there a specific reason this is being installed? Python packages and dependencies I can understand, but `mod_ssl` drops in configurations and example SSL configurations which means it enables port 443 and I can't understand why this would be needed by a certificate tool.

I can raise a PR to remove it if there's no reason for it to be installed - maybe it's a remnant of a previous era :smile:

**Comment by driskell** [comment]
On a side note - it's been working absolutely beautifully otherwise. Absolutely appreciate all the excellent work happening here :+1:

**Comment by pde** [comment]
Ugh.  The reason we were installing it is that on systems with a current Apache install, some users expect us to be able get their Apache to speak TLS correctly. If we need `mod_ssl` for that to work, we're going to be caught in a bind between helping our apache users and keeping things for our non-apache users...

**Comment by driskell** [comment]
Maybe its worth asking or informing the user something is missing and reporting error.
If automating, informing them would be useful as they'll know how to fix the problem.
If not automating, they'll see it and fix it.

Or, third possibility which may be a best of both worlds - only install it if it is actually needed. In my scenario I'm using certonly and --webroot-path so it's not touching any web server configuration. I guess this impacts the separation of concern though as I guess bootstrap is where everything is "installed" and this would require it to be installed within lets encrypt itself.

Maybe something to discuss.

For now I may need to just drop an empty ssl.conf into all my Apache folders so having mod_ssl installed doesn't break things - but I hope you agree this is not ideal as it adds some overheads :-1:

**Comment by pde** [comment]
If you're on CentOS 7: does installing `letsencrypt` from EPEL 7 work for you?
If you're on CentOS 6: does `pip install letsencrypt` function as a suitable workaround?

**Comment by hogarthj** [comment]
@driskell so you're aware the EPEL7 certbot doesn't pull in mod_ssl but the python-certbot-apache optional module will pull it in (as of the build just pushed out today).

**Comment by C4llumD** [comment]
Just experienced a similar issue.  System has Apache on 80, Nginx on 443.  Installed certbot which unknown to me had added mod_ssl to my Apache installation.  Apache subsequently failed to reload when  logrotate ran causing a call to an out-of-hours technician at 4:00am.

May be best to ask/prompt rather than forcibly installing mod_ssl behind the scenes?

#2605 appears to have been closed without this being addressed.
