### ISSUE TITLE
Letsencrypt-auto fails to build wheel for cryptography

### ISSUE THREAD

**Issue by ooii** [certbot/certbot#2603]
Hi,

I'm running letsencrypt on osx 10.11. Yesterday, it was working flowlessly. I did not update anything since.
But this morning, when I try to get a certificate for a personal domain, it fails with
`Failed building wheel for cryptography`.
First, it warns about `using pip version 7.0.1, however version 8.0.3 is available` while my `pip` version is `8.0.3`.
Then I have the following error

```
Failed building wheel for cryptography
Command "/Users/radar/.local/share/letsencrypt/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-DUfJSa-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-SC_OjG-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/radar/.local/share/letsencrypt/include/site/python2.7/cryptography" failed with error code 1 in /tmp/pip-DUfJSa-build
```

Note that I have no `.local/share/letsencrypt/` folder in my home directory.

Actually, it fails when building `wheels for collected packages: cryptography` with the following error

```
build/temp.macosx-10.11-intel-2.7/_openssl.c:423:10: fatal error: 'openssl/aes.h' file not found
  #include <openssl/aes.h>
           ^
  1 error generated.
  error: command 'cc' failed with exit status 1
```

Note that I tried to install `cryptography` outside a `virtuelenv` and I did not encounter any issue.

Any idea how I can fix that? And any explanation why it worked yesterday and not today?
Thanks in advance.

**Comment by grigutis** [comment]
Same here. I pulled the latest master branch and installed the latest version of pip via MacPorts, but it is unrecognized. MacPorts support is a separate issue (#2447), but there is at least a patch waiting to be merged (#2448). If there is a branch OS X users can help test, that would be great.

**Comment by tixastronauta** [comment]
Same here. I tried to revert to a previous commit but it still did not work.

**Comment by knot123** [comment]
This is my temporary solution:
1. install openssl
`brew install openssl
`
2. add these environment variables by running in terminal (or you can copy paste it to .bashrc and restart terminal) 
```
export ARCHFLAGS="-arch x86_64"
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CFLAGS="-I/usr/local/opt/openssl/include"
export PATH="/usr/local/opt/openssl/bin:$PATH"
```

Finally: Run
`./letsencrypt-auto certonly --debug`

**Comment by ooii** [comment]
Thanks.

**Comment by bmw** [comment]
This issue hasn't seen any activity since 2016 so I'm closing it. If you're having the same issue, please comment or open a new issue.
