### ISSUE TITLE
Add --must-staple flag

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#2626]
We should have a flag that adds the Must Staple extension in CSRs, per https://tools.ietf.org/html/rfc7633.

**Comment by cybernet** [comment]
+1

**Comment by nitmir** [comment]
:+1:

**Comment by jsha** [comment]
I've got a branch in progress at https://github.com/letsencrypt/letsencrypt/compare/master...jsha:must-staple?expand=1. Needs tests.
