### ISSUE TITLE
letsencrypt-auto apache 2.4 domains selection not user-friendly

### ISSUE THREAD

**Issue by gndgnd** [certbot/certbot#2627]
hi, 

Im running letsencrypt-auto on Debian 8 server with Apache 2.4. We are hosting over a hundred domains and the experience with the domain selection is kinda frustrating:
- the domains are show in a very small window, enabling to see only the next 5/6 domains at once
- the domains are not ordered alphabetically but in some weird garbled order (maybe by .conf creaton time ?) This makes the navigation very cumbersome.
- It would be definitely better if the domains shown would be the domains that are enabled in apache - eg. symlinks in the "sites-enabled" directory as compared to the files in the "sites-available" directory as it is now.
- i understand Lets Encrypt wants to push for more web encryption, but maybe a better default for first run would be to have all the domains unchecked, rather then checked. Especially if its a first time user, and hosts many domains, he might spend some considerable time unchecking all he doesnt want to encrypt. Maybe a solution would be a option to "check / uncheck all". 

thank you for you consideration and great work !

**Comment by joohoi** [comment]
I suspect that this is referring to the old ncurses frontend that's removed from certbot now. Can we close the issue @gndgnd ?

**Comment by gnd** [comment]
@joohoi yes :)

**Comment by joohoi** [comment]
Awesome, closing as solved.
