### ISSUE TITLE
Please provide switch to NOT update client!

### ISSUE THREAD

**Issue by PatrickHeppler** [certbot/certbot#2628]
I have build up my own workflow with a small python script which stops nginx, calls letsencrypt to renew, creates TLSA record which get pushed to DNS and creates symlinks for the certs and starts nginx again.
Every now and then the auto-update breaks my workflow. So please give us a switch to NOT update on every client call!

**Comment by cybernet** [comment]
+1

**Comment by nitmir** [comment]
Is not the `--no-self-upgrade` parameter what you are seeking ?

**Comment by bmw** [comment]
Yes, `--no-self-upgrade` should accomplish what you're after. Neither the Python packages nor the `letsencrypt-auto` script will be upgraded.

**Comment by HansVanEijsden** [comment]
Hi @PatrickHeppler, please would you care to share your python script? I would love to have TLSA with Let's Encrypt automatically. Thanks!

**Comment by PatrickHeppler** [comment]
@HansVanEijsden here is my script: https://gist.github.com/PatrickHeppler/064f6463d14fcf7d7a99f18f68a10684
I'm using a single certificate for all of my domains, so I can use my own CSR and PrivKey. My script uses the API from Rage4 to update the zones. Maybe it's not perfect but it gets the job done.

**Comment by HansVanEijsden** [comment]
@PatrickHeppler thank you very much. This will do exactly what I'm looking for, I'll try it out!

**Comment by PatrickHeppler** [comment]
You're welcome

**Comment by bmw** [comment]
I'm glad you found a script that works for your needs, however, since `--no-self-upgrade` stops any client updates, I believe this issue can be closed.
