### ISSUE TITLE
Add an option to configure dual RSA/ECDSA certificates

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#2632]
Related to #2625: In addition to / alternatively to explicitly choosing a key type, we should have a flag to automatically get both an RSA and an ECDSA cert, and offer both depending on what the client accepts. Eventually (after experimentation) we might want to make this the default.

Here's info on how to do it in Apache: https://blog.joelj.org/dual-rsaecdsa-certificates-in-apache-2-4/

**Comment by nitmir** [comment]
:+1:

**Comment by J0WI** [comment]
This is currently also planned for nginx 1.11:
https://trac.nginx.org/nginx/roadmap

**Comment by jonnybarnes** [comment]
Indeed dual cert support was added to nginx v1.11.0: http://nginx.org/en/CHANGES

**Comment by Yamakaky** [comment]
At least it should be supported by `certonly`.

**Comment by jonnybarnes** [comment]
Do we have any more of an idea of the timescale for this?

**Comment by STonEDSTonE** [comment]
Any update on this matter? This feature would be awesome!

**Comment by udf2457** [comment]
Yeah guys.... where is it ?

**Comment by jookk** [comment]
Here :O https://github.com/Neilpang/acme.sh
I am now using two clients.

**Comment by sanmai** [comment]
This issue is still relevant.

**Comment by udf2457** [comment]
Agree with @sanmai .  The only thing stale are the certbot developers. ;-)

**Comment by bmw** [comment]
Since this issue was opened, I think the landscape has changed a bit. For instance, [Mozilla's TLS recommendations](https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28recommended.29) recommend an ECDSA cert over a RSA cert and using ECDSA has more compatibility with old clients than RSA with the cipher suites they recommend.

If anyone has a use case for this other than supporting clients older than [Mozilla supports in their intermediate config](https://wiki.mozilla.org/Security/Server_Side_TLS#Recommended_configurations), I'd love to hear about it.

**Comment by jsha** [comment]
The proposal is to implement ECDSA, but without a "dual cert" option? That does seem like a nice way to unblock progress on #2625, since it would simplify a bunch of things. If anyone has concrete data on specific clients or OS' that break with ECDSA-only certs, that would be helpful.

**Comment by rhymeswithmogul** [comment]
> The proposal is to implement ECDSA, but without a "dual cert" option? That does seem like a nice way to unblock progress on #2625, since it would simplify a bunch of things. If anyone has concrete data on specific clients or OS' that break with ECDSA-only certs, that would be helpful.

I have dual certs on my web server.  According to SSL Labs, these clients do not support ECDSA certificates:
- Android 2
- Internet Explorer (all versions), only when run on Windows XP and older
- Google Chrome (all versions), only when run on Windows XP
- Java 6 and older
- OpenSSL 0.9.8 and older

**Comment by bmw** [comment]
> The proposal is to implement ECDSA, but without a "dual cert" option?

Right. I've started discussing the idea with Erica, but we haven't come to a consensus yet. I want to gather more information, but I'm personally pretty motivated by the fact that according to Mozilla's TLS recommendations which we follow, clients that don't support ECDSA are older than the configurations created by our Apache and Nginx plugin support anyway.

**Comment by adferrand** [comment]
> 
> 
> The proposal is to implement ECDSA, but without a "dual cert" option? That does seem like a nice way to unblock progress on #2625, since it would simplify a bunch of things. If anyone has concrete data on specific clients or OS' that break with ECDSA-only certs, that would be helpful.

For Windows, if we consider only non EOL versions, you will lose Windows 2008R2 on kernel network calls. About Internet Explorer, you need to go to the insanely old and unsupported IE 6.

**Comment by J0WI** [comment]
Android 2, IE on XP and and Java 6 do not even support SNI. So for them most hosts will raise an error anyway.

**Comment by udf2457** [comment]
> For Windows, if we consider only non EOL versions

^^^This a million times !

Frankly I (and nobody else who cares about security) should spend even a nanosecond thinking about supporting users who are still on Windows XP (or other EOL versions).

In the case of XP, Microsoft gave many years of prior notice that EOL was coming.  Then they pushed back that EOL date, and pushed it back some more until finally pulling the plug.

Windows XP has no place on the internet.  Not for the security of people using it, and not for the rest of us on the internet who will be affected by the zombie-nets used to attack everyone else.

Rant over !

**Comment by bmw** [comment]
After the recent discussion had here and internally, I am closing this issue.

For us, this issue was tracking adding a feature to Certbot to issue and install ECDSA and RSA certificates together automatically. This would include keeping things like domains and renewal options in sync. It also would include automatically configuring Apache and Nginx to use both ECDSA and RSA certificates. All of this is actually pretty difficult to implement in Certbot and in 2020, we don't think that most users need these features as all modern clients support ECDSA certificates.

With that said, we still have every intention to add support for ECDSA certificates to Certbot. Once that feature is added, people who want dual certificates can still obtain them, just as far as Certbot is concerned, they are separate certificates and you'll have to manually configure your server to use both certificates. That work is being tracked by https://github.com/certbot/certbot/issues/2163.

**Comment by omya3qno** [comment]
> If anyone has concrete data on specific clients or OS' that break with ECDSA-only certs, that would be helpful.

I have a Brother MFC-L3770CDW printer, that insists on RSA certificates.

**Comment by paulintrognon** [comment]
OCPP, which is the protocol under most EV charge points communicate with their server, requires both RSA and ECDSA to be supported :

> The CSMS SHALL support at least the following four cipher suites:
> TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
> TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
> TLS_RSA_WITH_AES_128_GCM_SHA256
> TLS_RSA_WITH_AES_256_GCM_SHA384
> Note: The CSMS will have to provide 2 different certificates to support both cipher suites. Also when using security profile 3, the CSMS should be capable of generating client side certificates for both cipher suites.

I think this is a valid case for supporting both certificates

**Comment by rhymeswithmogul** [comment]
> @jsha
> [OCSP], which is the protocol under most EV charge points communicate with their server, requires both RSA and ECDSA to be supported

Those are TLS ciphers, not certificate public key types.  The specification you referenced only mandates that OCSP providers support one of those ciphers when negotiating a TLS 1.2 connection.  Despite the confusing naming scheme you're seeing, it has nothing to do with dual certificates.  This merely requires strong AES-GCM encryption methods;  on top of that, ECDSA ciphers are negotiated with ECDSA certificates, and RSA ciphers go with RSA certificates.

That being said, I used to be a huge fan of ECDSA+RSA dual deployments, and did it myself for many years.  At this point, though, the only major browser left that doesn't support ECDSA is Chrome on Windows XP and old versions of Android.  While I can see keeping ECDSA+RSA as an option in Certbot for deployments that need to target a sizable but shrinking number of endpoints, the only dual certificate option worth implementing at this point would be dual EdDSA+ECDSA certificates (assuming the CA/B Forum has allowed EdDSA certs).

**Comment by jsha** [comment]
I was curious about this so I googled and found https://raw.githubusercontent.com/mobilityhouse/ocpp/master/docs/v201/OCPP-2.0.1_part2_specification.pdf

> Those are TLS ciphers, not certificate public key types.

This is true, but the first part of these cipher suites specifies a key agreement algorithm: ECDHE_ECDSA or RSA. Per [RFC 5246, page 48 and 49](https://www.rfc-editor.org/rfc/rfc5246#page-48):

>    -  The end entity certificate's public key (and associated
>      restrictions) MUST be compatible with the selected key exchange
>      algorithm.
> ...
>       Key Exchange Alg.  Certificate Key Type
>      RSA                RSA public key; the certificate MUST allow the
>      RSA_PSK            key to be used for encryption (the
>                         keyEncipherment bit MUST be set if the key
>                         usage extension is present).
>                         Note: RSA_PSK is defined in [[TLSPSK](https://www.rfc-editor.org/rfc/rfc5246#ref-TLSPSK)].
> ...
> ECDHE_ECDSA        ECDSA-capable public key; the certificate MUST
>                         allow the key to be used for signing with the
>                         hash algorithm that will be employed in the
>                         server key exchange message.  The public key
>                         MUST use a curve and point format supported by
>                         the client, as described in  [[TLSECC](https://www.rfc-editor.org/rfc/rfc5246#ref-TLSECC)].

So I believe @paulintrognon is correct that the **OCPP** spec requires support dual certificate support for the Charging Station Management System (CSMS). Interestingly, the Charging Station is only required to support one or the other of the groups of cipher suites (this is specified in the next chunk down from the one @paulintrognon quoted).

At any rate, it's useful to know this dual certificates are a requirement for OCPP. @paulintrognon out of curiosity are you using Certbot to maintain certificates for a CSMS? If you manage the two types of certificates manually, are you running into obstacles?

**Comment by WestFarmer** [comment]
poste.io a mail solution, only accepts RSA certs.

**Comment by pfactum** [comment]
> > If anyone has concrete data on specific clients or OS' that break with ECDSA-only certs, that would be helpful.
> 
> I have a Brother MFC-L3770CDW printer, that insists on RSA certificates.

@omya3qno Have you managed to tame your printer? I've got the same issue. I use a different SMTP with RSA as a workaround now, but I'd really want this mofo to work with ECDSA instead.

**Comment by omya3qno** [comment]
> > > If anyone has concrete data on specific clients or OS' that break with ECDSA-only certs, that would be helpful.
> > 
> > 
> > I have a Brother MFC-L3770CDW printer, that insists on RSA certificates.
> 
> @omya3qno Have you managed to tame your printer? I've got the same issue. I use a different SMTP with RSA as a workaround now, but I'd really want this mofo to work with ECDSA instead.

negative. I continue to ask letsencrypt to issue RSA to satisfy my printer.

**Comment by pfactum** [comment]
> > @omya3qno Have you managed to tame your printer? I've got the same issue. I use a different SMTP with RSA as a workaround now, but I'd really want this mofo to work with ECDSA instead.
> 
> negative. I continue to ask letsencrypt to issue RSA to satisfy my printer.

Ack, thank you for responding.
