### ISSUE TITLE
letsencrypt subcommand for base directory

### ISSUE THREAD

**Issue by pusateri** [certbot/certbot#2633]
It would be nice to have a sub command to show where the base letsencrypt directory is. On FreeBSD, this is /usr/local/etc/letsencrypt. On Linux, it's /etc/letsencrypt. It might be other places on OSX.

**Comment by bmw** [comment]
Interesting. The default for the project is `/etc/letsencrypt` but it appears the maintainer of the FreeBSD port changed the location to better fit the system. That's great.

When you obtain a certificate, `letsencrypt` should give you output like:
```
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/example.com/fullchain.pem...
```
which indirectly shows the location of the configuration directory.

If we implemented a subcommand for showing such information, what other information would you want? All relevant defaults such as the log directory, server URL, etc? Values which will be used by `letsencrypt` at runtime including defaults, values from configuration files, and maybe even provided command line flags?

I'm just trying to understand what you'd like this subcommand to accomplish.

**Comment by pusateri** [comment]
I have a portable daemon that I author and was considering the auto configuration case. When my daemon initializes, it would be great if it could locate the certificate without additional configuration. I can add a search path but calling the letsencrypt command and getting the path would be better. I could default to looking at $sysconfdir/letsencrypt/live/`hostname`/cert.pem. This would do the right thing on both FreeBSD and Linux and so maybe it's enough. But, in addition to the base path, you could return the location of the cert, key, and chain files for a given domain:
$ lets encrypt showpath
/etc/letsencrypt
$ letsencrypt showpath --cert foo.bar.com
/etc/letsencrypt/live/foo.bar.com/cert.pem
$ letsencrypt showpath --key foo.bar.com
$ letsencrypt showpath --chain foo.bar.com
$ letsencrypt showpath --logdir

**Comment by ohemorange** [comment]
We now have `certbot certificates`, which will show information that includes the path to each certificate's certificate and private key files.
