### ISSUE TITLE
Add some way to check quotas

### ISSUE THREAD

**Issue by ZlatyChlapec** [certbot/certbot#2637]
Right now there are some limits https://community.letsencrypt.org/t/public-beta-rate-limits/4772/3 which will probably change in future but they will still be there.

If limits are just temporary it's not worth of developing I guess, but if they'll stay it would be really nice to have an option to check how many certs I have left before reaching limit. Also I don't know how excatly it works but it would be nice if revoke would give me back number previously taken by revoked cert or something in that spirit.

**Comment by pde** [comment]
Cc @jsha @rolandshoemaker @riking

**Comment by riking** [comment]
This would also require some ACME spec changes, I believe. What's an appropriate wire format for expressing rate limits and exceptions?

**Comment by riking** [comment]
And the reason revocation doesn't give back rate limit tokens is that we still need to sign OCSP responses for revoked certificates.

**Comment by nitmir** [comment]
If I not mistaken, the CA just need one OCSP signature when the cert is revoked and then, do not need any-more to renew the OCSP signature every 4 days.

**Comment by riking** [comment]
No. Per the Baseline Requirements:

> §4.9.10 On-line Revocation Checking Requirements
> ...
> For the status of Subscriber Certificates:
>>The CA SHALL update information provided via an Online Certificate Status Protocol at least every four days.
>>OCSP responses from this service MUST have a maximum expiration time of ten days.

There is no exception on expiry time for revoked certificates.

**Comment by nitmir** [comment]
Maybe the quota check could use https://crt.sh/ (or anything exposing CT logs) to compute the quota, without using ACME. Like https://community.letsencrypt.org/t/newbie-question-seeking-advice/12526/5

**Comment by jsha** [comment]
Definitely a tool using crt.sh would be a relatively quick way to help people figure out rate limit problems. It has the disadvantage that it will not always have the very latest data.

I'm definitely open to adding this information. I have been thinking it would be an HTTP header returned on relevant requests (e.g. new-cert):

Rate-Limit-Remaining: certificatesPerName=3, certificatesPerFQDNSet=1

For requests that actually hit a rate limit, we could include in the problem details some information about when the limit will expire.

**Comment by quenenni** [comment]
I'm very interested by this feature too: https://github.com/letsencrypt/letsencrypt/issues/2555
