### ISSUE TITLE
Rename the Github Repository

### ISSUE THREAD

**Issue by SwartzCr** [certbot/certbot#2638]
We'd like to remove all references to Let's Encrypt once we decide on a new name - this includes migrating the github repo from letsencrypt/letsencrypt

**Comment by cowlicks** [comment]
Is there an explanation of the rename somewhere?

**Comment by bmw** [comment]
Yes, there were two blog posts about it. One from [ISRG](https://letsencrypt.org/2016/03/09/le-client-new-home.html) and one from [EFF](https://www.eff.org/deeplinks/2016/03/new-name-and-roadmap-lets-encrypt-client).

**Comment by SwartzCr** [comment]
I am going to do some tests wrt this and report back on how well redirects work

**Comment by SwartzCr** [comment]
I've tested changing repo name and org ownership
pulls/pushes work, issues and urls redirect
one thing is that the folder for the main repo on disk (if cloned) doesn't change name when you pull after the move

**Comment by bmw** [comment]
We should resolve #2871 before we rename this issue.

**Comment by SwartzCr** [comment]
A few things are blocking on this:
change URLs in letsencrypt-auto to point to github.com/certbot/certbot
update the docs especially readme.rst to mention 
 
@bmw has some fear that #2871 will have trouble with the repo rename

@pde did you not want to do the rename of the repo until we had the site ready? Or can we do it now to help push some of these tickets out

**Comment by bmw** [comment]
#2912 is blocking this.

**Comment by SwartzCr** [comment]
Done!
