### ISSUE TITLE
Update any EFF tiny URLs that link to documentation

### ISSUE THREAD

**Issue by pde** [certbot/certbot#2672]
We have a couple of EFF tiny URLs that point to docs on letsencrypt.readthedocs.org; once we movethedocs to eff.org (#2648) we should track those down and update them.

**Comment by schoen** [comment]
@SwartzCr is wondering how to find these or looking for specific examples.

**Comment by pde** [comment]
They're findable here: https://kittens.eff.org/admin/config/search/redirect

**Comment by pde** [comment]
(But i just edited all those links)
