### ISSUE TITLE
-v should imply --text

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#2674]
If you specify the -v flag without --text, the verbose logging gets sent into an ncurses text box, and is impossible to read. We should automatically assume --text when -v is specified.

**Comment by pde** [comment]
This should have been fixed (#2338 / #2389).  Under what circumstances are you still seeing it?

**Comment by pde** [comment]
Citation: https://github.com/letsencrypt/letsencrypt/pull/2338/files#diff-54b2f468d57ef7436008bd031bc89711R1742

**Comment by bmw** [comment]
@pde, I believe what you're talking about only applies when using `renew/--noninteractive`. When running `letsencrypt` with neither of those flags, logging is sent to `dialog` (in addition to log files) regardless of the level of verbosity.

**Comment by pde** [comment]
(Didn't make the cut in our 0.5.0 triage meeting)

**Comment by bmw** [comment]
Fixed in #3064.
