### ISSUE TITLE
letsencrypt apache, bad domain order

### ISSUE THREAD

**Issue by puggan** [certbot/certbot#2685]
when running `/root/.local/share/letsencrypt/bin/letsencrypt --apache`

First I have to deselect all, one by one, then i need to find the domain, and its alias, of the vhost i want to make a cert for.

Current behaviour:
When I press ok, a cert is created, using the vhosts ServerAlias as main domain, and the ServerName as additional domain.

Expected behaviour:
When I press ok, a cert is created, using the vhosts ServerName as main domain, and the ServerAlias as additional domain.

**Comment by pde** [comment]
Fixing this involves ordering the `config.domains` list so that the `ServerName` entry comes first.

As a workaround, you can specify the domains in the order you want with `-d` on the command line.

**Comment by bmw** [comment]
Now that we put all domains as SANs with none in the common name field of the CSR, I don't think changing our behavior here makes sense so I'm closing this issue.
