### ISSUE TITLE
Packages for Debian Wheezy

### ISSUE THREAD

**Issue by Ninos** [certbot/certbot#2686]
Hey there,
I'm one of the developers of the i-MSCP project (https://i-mscp.net/) and planning a plugin for our open-source control panel. With this plugin for customers it should be possible to activate https with a valid connection in just one click.
ATM for installation our customers need to clone the current git repository and rerun installation routine. Packages are just available for the debian testing repositories (as I read). It would be very nice to ship packages also for at least Debian Jessie and Ubuntu 14.04 :-)

Best regards

**Comment by bmw** [comment]
That's fantastic that your planning on integrating Let's Encrypt with your control panel!

@hlieberman is a good person to talk about this, but thanks to his work, we're available in Jessie backports ([source](https://packages.debian.org/search?keywords=letsencrypt&searchon=names&section=all&suite=jessie-backports)). hlieberman has also created a PPA for Ubuntu Wily as discussed in #1706.

We will be packages in Ubuntu 16.04 and there has been talk of creating a PPA for Ubuntu 14.04 as well.

**Comment by Ninos** [comment]
Nice to hear, isn't it better to also have your own repository, so you can ship your packages for old systems, too (in an easy way)?

**Comment by hlieberman** [comment]
Hello @Ninos!  There are packages for Debian Jessie available in backports at the moment; we're looking into supporting 14.04 after the name change in mid-April.

**Comment by Ninos** [comment]
Ok thank you for feedback.

**Comment by Ninos** [comment]
Small question. I already finished the plugin for imscp (just need testing). Atm it's working fine on jessie-systems. I cannot wait to mid April, so are there any precompiled packages available? Otherwise I need to find a solution for that problem :)

BTW: What will be the changes for us as developers after the name change? New packages names? New command name? Servers we need to add manually...?

**Comment by pde** [comment]
@Ninos your options would include:

1. Use `letsencrypt-auto` (you can add `--no-self-upgrade` to prevent it from auto-updating).
2. Install with `pip` (though I don't recommend that, it's very non-dpkg-friendly)
3. Hack on the jessie packages until you get something that's installable on wheezy.  But I suspect `python-cryptography` will be hard.

**Comment by pde** [comment]
We already have issue #1706 for Ubuntu packaging, and Jessie is done, so narrowing this one to be Wheezy-specific.

**Comment by pde** [comment]
4. Follow the [developer instructions](https://letsencrypt.readthedocs.org/en/latest/contributing.html#running-a-local-copy-of-the-client) to get fine-grained control of exactly which release you're running from a python virtualenv.

**Comment by Polve** [comment]
Hello, is there any progress on a wheezy package?
I found a debian 7 package on this page, can it be helpful?
https://software.opensuse.org/package/certbot

**Comment by ohemorange** [comment]
Updates on the status of our packaging on various systems can be found at https://certbot.eff.org/
