### ISSUE TITLE
letsencrypt_apache/configurator.py finds zero vhosts

### ISSUE THREAD

**Issue by alexlauerman** [certbot/certbot#2694]
[Line 720](https://github.com/letsencrypt/letsencrypt/blob/01608d4d8d0a23578d3509799a597d0272513a40/letsencrypt-apache/letsencrypt_apache/configurator.py#L720) of letsencrypt_apache/configurator.py finds zero vhosts when it looks at /etc/apache2/apache2-le-ssl.conf (the file it creates by calling _copy_create_ssl_vhost_skeleton and passing in /etc/apache2/apache2.conf). 

Here are the last few lines of my apache2.conf:

```
<VirtualHost *:80>
   ServerAdmin myfirstname@trustfoundry.net
   DocumentRoot /var/www
   ServerAlias trustfoundry.net
</VirtualHost>
```

The statement that gets entered, and error that gets output is on lines [723 through 725](https://github.com/letsencrypt/letsencrypt/blob/01608d4d8d0a23578d3509799a597d0272513a40/letsencrypt-apache/letsencrypt_apache/configurator.py#L723,L725):

```
Error: should only be one vhost in /etc/apache2/apache2.conf 
Currently, we only support configurations with one vhost per file
```
- I have confirmed that zero "VirtualHost" matches are found.
- I have confirmed the file apache2-le-ssl.conf gets created.
- I have also confirmed that it does correctly find one vhost if I pass in avail_fp as the file to search, which is /etc/apache2/apache2.conf. 
- I have also introduced a sleep to attempt to confirm it's not a race condition, and it did not fix the error.

**Comment by joohoi** [comment]
What OS (and Apache version) are you running? Configuration constants are set per OS basis, and it could help us pinpoint the problem. Also Apache plugin is built on assumption that the VirtualHosts reside in separate files (and one per file), which might be the root of the problem.

**Comment by alexlauerman** [comment]
Ubuntu 14.04.4 and Apache/2.4.7.

I moved the VirtualHosts entry into a separate file and that fixed the issue. I'm not sure where this threw it off, or if the error could be handled better (it didn't indicate the issue).

**Comment by joohoi** [comment]
Closing the issue, as multiple vhosts in single file is working in recent versions of Certbot.
