### ISSUE TITLE
Populate instructions in .rst files from instruction generator

### ISSUE THREAD

**Issue by pde** [certbot/certbot#2713]
When we have an instruction generator (#2704) it will initially duplicate some strings from `using.rst` and `contributing.rst` in a JSON blob.  It looks theoretically possible to use [a mechanism like this](http://docutils.sourceforge.net/docs/howto/rst-roles.html) to load JSON elements into our reStructuredText to prevent string duplication.

**Comment by pde** [comment]
CC: @vbrown608

**Comment by SwartzCr** [comment]
@pde that link doesn't seem to be resolving

**Comment by SwartzCr** [comment]
The instruction generator isn't using any copied text from the .rst files. I'm going to close this, since I think any re-use will be dealt with by including links
