### ISSUE TITLE
Magic configurator flags

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#2714]
So this technically isn't a bug, but I think the behavior is very confusing.

When using `--apache` or `--nginx`, as stated in the help, both the authenticator and installer are set. The problem with this occurs during renewal.

Suppose you ran the client with both `--apache` and `certonly`. In this example, due to this bug, both `authenticator` and `installer` are set in the renewal config file. When a user runs `letsencrypt renew` and obtains his new certificate, the following message will be output:

```
new certificate deployed with reload of apache server; fullchain is /etc/letsencrypt/live/pickupapp.me/fullchain.pem
```

Is this the behavior we want?

**Comment by pde** [comment]
The thing is that the authenticator plugin will necessarily perform that reload as a side effect of obtaining the cert; the output is kind of an afterthought, though necessarily accurate.

**Comment by pde** [comment]
Unless you can think of a better/less confusing wording for this message, I think this has to be a `wonftfix`.

**Comment by bmw** [comment]
To make my confusion more explicit: `--apache certonly` sets Apache as an installer when I expected it to only set it as an authenticator.

In my opinion, we can either:
a) Have the `--apache`, `--nginx`, etc. flags only set values for necessary for the requested command.

| verb | sets |
|--------|----------|
| run   | authenticator and installer |
| certonly | authenticator |
| install | installer |
| renew | ??? |

b) Do nothing and close this issue.

Either way is fine, but like I said, the behavior surprised me and perhaps we should consider changing it.

**Comment by ohemorange** [comment]
I'm closing this because `renew` doesn't install certificates.
