### ISSUE TITLE
Failed authorization procedure with Apache proxy-pass entries

### ISSUE THREAD

**Issue by willin** [certbot/certbot#2726]
```
Failed authorization procedure. sh.gg (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Correct zName not found for TLS SNI challenge. Found 'wuliangroup.cn, www.wuliangroup.cn, api.wuliangroup.cn, account.wuliangroup.cn'

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: sh.gg
   Type:   unauthorized
   Detail: Correct zName not found for TLS SNI challenge. Found
   'wuliangroup.cn, www.wuliangroup.cn, api.wuliangroup.cn,
   account.wuliangroup.cn'

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.
```

what does it mean and how to fix these?

**Comment by bmw** [comment]
It means that the client could not prove to the Let's Encrypt server that you had control of your requested domains. To fix this problem, make sure you're running `letsencrypt` on the machine pointed to by the DNS A records of the domains you requested.

**Comment by eleumik** [comment]
Hi, 
I've got the same error running on the machine pointed by DNS. I ran `./letsencrypt --apache` For some reason the apache web server stops after choosing the domains, at that point, being the web sites down, the message is displayed.

**Comment by pde** [comment]
@eleumik is there any information in your logs that shows what change the client made to your server config?  If so, that might explain why the attempt to perform a `reload` is stopping your server...

**Comment by pde** [comment]
(I'm also not sure that @eleumik's issue is the same as @willin's...)

**Comment by eleumik** [comment]
Hi,
I am not sure the config is modified, in any case if I `restart` apache manually after the failure, everything works. Where should I look for logs ? Thanks

**Comment by bmw** [comment]
Logs can be found in `/var/log/letsencrypt` by default.

**Comment by pde** [comment]
Sounds like @eleumik may have a real Apache bug, putting it into the 0.6.0 milestone if we can get enough information to attack it properly.

**Comment by pde** [comment]
Also @eleumik if you're able to share your Apache configuration that would be very helpful.

**Comment by eleumik** [comment]
Hi,
I have the following configuration for domain `example.org`:

```

	ServerName example.org
	ServerAlias app.example.org 
	ServerAlias www.example.org 


	ProxyPreserveHost on
	ProxyRequests off	
	ProxyPass / ajp://127.0.0.1:8009/
	ProxyPassReverse / ajp://127.0.0.1:8009/

	CustomLog ${APACHE_LOG_DIR}/example.org-access_log common
        ErrorLog ${APACHE_LOG_DIR}/example.org-error_log

```


I think that first time I ran `./letsencrypt --apache` and selected all virtual hosts, eg: `example.org www.example.org app.example.org` but it failed with the "cannot connect" message of this issue, before getting to second screen. After exit Apache was stopped, its configuration was not modified, no changes seen using `config_changes`, when I restarted apache everything was working as before.

The second time, since I do not really use `www.example.org` but always redirect those requests to `example.org`, I selected only the two hosts I actually use `example.org app.example.org` and it worked.

I compared the logs of the two cases and I found that after this:

`2016-03-30 05:25:49,076:DEBUG:letsencrypt.reverter:Creating backup of /etc/apache2/apache2.conf`

these were only present when it failed:

```
2016-03-30 05:25:49,842:DEBUG:letsencrypt_apache.configurator:Setting VirtualHost at *:443 to be a name based virtual host
2016-03-30 05:25:49,842:DEBUG:letsencrypt_apache.configurator:Setting *:443 to be NameBasedVirtualHost
	Directive added to None
```

If you need more infos let me know.

**Comment by pde** [comment]
We didn't get to this for 0.6.0, bumping to 0.7.0.

**Comment by MiguelQueiroz** [comment]
I also have this problem. 
I have my domain "example.com" A record pointing to a hosted Server , that also provides my email etc.. but the Ip is not my VM. What i then do on the A record, is to redirect requests to the www.example.com, and also have a CNAME for other subdmains like api.example.com... 

But the thing is the error tells me i dont own the domain, which is wrong... You should use a different method of evaluating this, not for the A record! also in somecases that one uses load balacing the ip will not be the machine one. So... you should instead install a file in the public html, and read if the token is there.. etc... I had to use AutoSSL to make it work. But would much more enjoy the letsencrypt one...

**Comment by pde** [comment]
@MiguelQueiroz that's a different issue again.  The use of `A` records is part of the [ACME spec](https://tools.ietf.org/html/draft-ietf-acme-acme-02) so if you wanted different behaviour, please discuss it on the IETF ACME list. But note that if you use the [webroot plugin](https://certbot.eff.org/docs/using.html#webroot) you can serve redirects from `.well-know/acme-challenge/` to control which server the

**Comment by pde** [comment]
I think this is getting kicked for the time being...

**Comment by bmw** [comment]
@joohoi suggested as a potential possibility here is commenting out problematic directives such as this and #1820, notifying the user, and letting them update their config manually. Obviously it would be nice if we could just handle this properly ourselves, but that is much harder and commenting out some directives allows us to make some forward progress on this issue.

**Comment by bmw** [comment]
@joohoi are you still interested in working on this? If so that'd be great, but there's currently a lot of stuff assigned to you for 0.14.0. If you want to work on it and think you'll get to it in time for the release, feel free to move it back to the milestone.

**Comment by joohoi** [comment]
I created an umbrella issue for this and similar ones, so I'm closing this, feel free to continue discussion in #4797
