### ISSUE TITLE
Fails to Parse Apache Configuration File on Host with Multiple Domains managed by Plesk

### ISSUE THREAD

**Issue by sokser** [certbot/certbot#2731]
I've used letsencrypt successfully on other servers, however when I test it on a server that is hosting multiple domains it fails to correctly parse the apache config file. When I attempt to run it I get the following error:

<pre><code>The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/httpd/conf/plesk.conf.d/server.conf', u'Syntax error'),)</code></pre>

However when I check the config file for errors, it returns an ok status:

<pre><code>apachectl configtest
Syntax OK
</code></pre>

Below you can see the configuration file:

https://gist.github.com/sokser/b0618d033f75e5687983dfa1003a935f

**Comment by pde** [comment]
@domcleal this might be for you

**Comment by cosimosimeoneTR** [comment]
Same here, with pretty much default apache2.conf file, apache version 2.2.22-13+deb7u6
What i added in conf file (diff from default one):

```
<
< ServerName <my ip>
<
< #Compress
< <IfModule mod_mime.c>
<  AddType application/x-javascript .js
<  AddType text/css .css
< </IfModule>
< <IfModule mod_deflate.c>
<  SetOutputFilter DEFLATE
<  <IfModule mod_setenvif.c>
<   SetEnvIfNoCase Request_URI \.(?:rar|zip)$ no-gzip dont-vary
<   SetEnvIfNoCase Request_URI \.(?:gif|jpg|png)$ no-gzip dont-vary
<   SetEnvIfNoCase Request_URI \.(?:avi|mov|mp4)$ no-gzip dont-vary
<   SetEnvIfNoCase Request_URI \.mp3$ no-gzip dont-vary
<  </IfModule>
<  <IfModule mod_headers.c>
<   Header append Vary User-Agent env=!dont-vary
<  </IfModule>
<
```

Hope this helps

**Comment by domcleal** [comment]
@cosimosimeoneTR I don't think your issue is related, the problem with the OP's config file was some empty line continuations within VirtualHosts.

It looks like your config fragment is missing an ending `</IfModule>`, and after adding that it parses fine. If you still have a problem, please open a new issue and we can look at it in more detail.  Thanks.

**Comment by domcleal** [comment]
@sokser thanks for filing the issue with the full config file, I've sent a patch which parses the example correctly now.

**Comment by cosimosimeoneTR** [comment]
Shame on me :-)
