### ISSUE TITLE
Still having backslash parsing errors in apache config file (0.4.2)

### ISSUE THREAD

**Issue by jradwan** [certbot/certbot#2735]
I've seen all the old bugs about Apache config file parsing errors with regards to backslashes and updates to the augeas lenses, but I'm still getting this error when trying to run 'letsencrypt-auto --apache':

`The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/apache2/sites-enabled/piwigo.conf', u'Syntax error'),)`

caused by these two RewriteCond lines (which have backslashes):

```
RewriteCond %{HTTP:Content-Disposition} \.php [NC]
RewriteCond %{THE_REQUEST} ^[A-Z]{3,9}\ /.+/trackback/?\ HTTP/ [NC]
```

If I comment those out, the parsing works (and then I run into the "Failed to connect to host for DVSNI challenge" problem, which I'm still working on.

I even tried updating to the 1.4.0 versions of augeas-lenses and libaugeas0 (I had 1.3.0 on Wily, 1.4.0 is coming with Xenial) but that didn't help either. I'm guessing it's safe to just leave those lines commented out to get past the parsing and then turn them back on once I'm done with the letsencrypt process/setup?

**Comment by pde** [comment]
Also for @domcleal

**Comment by domcleal** [comment]
Thanks for for the report, I've opened a PR with a fix that parses the problematic second directive.  Sorry for the delay!

**Comment by jradwan** [comment]
No worries, thanks!
