### ISSUE TITLE
Invalid warning about Apache redirect

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#2736]
With a fresh install of Apache on Debian Jessie, I created this vhost:
```
<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        ServerName example.com
        ServerAlias www.example.com

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf
</VirtualHost>
```
This is the only vhost I had enabled. When running `letsencrypt run --redirect` I get the error message:
```
WARNING:letsencrypt.client:Enhancement redirect was already set.
```
Despite this error message, the redirect was correctly enabled. Are we trying to set up the redirect twice?

**Comment by pde** [comment]
So, you've run the client exactly once and it produces that error?  That is a little weird.  I would expect the error if you re-ran things a second time (the client doesn't yet have a way of telling that it had already enabled redirects in the past).  But not for it to try twice in one run.

**Comment by pde** [comment]
@sagi, any thoughts on this?

**Comment by bmw** [comment]
Yes. I got this error when running the client for the first time.

**Comment by sagi** [comment]
I couldn't reproduce it.

I tried to delete the renewal / archive / live files for a specific domain, then ran the `letsencrypt run --redirect`. 

In the first trial I selected only the ServerName from the domain list, and in the second trial (again deleting the renewal / archive / live) both the ServerName and the ServerAlias.

**Comment by bmw** [comment]
@sagi: Here's a [recording](https://asciinema.org/a/159cgn15k9oji4jjfsrcb1rif) of the problem. I hope this helps you repo it.

**Comment by sagi** [comment]
Awesome! Thanks!

**Comment by pde** [comment]
Since we don't have a PR for this, kicking it to 0.7.0!

**Comment by sagi** [comment]
Still can't reproduce it. Would appreciate if we can sit and talk about it @bmw.

**Comment by bmw** [comment]
@sagi, sure! I'm planning on working from home tomorrow, but I'm free to work with you on it on Wednesday if you're available.

**Comment by sagi** [comment]
Great! I'm available.
