### ISSUE TITLE
multiple -d options are ignored in letsencrypt-auto -- only the first one works

### ISSUE THREAD

**Issue by cpg** [certbot/certbot#2752]
I tried to script some things and I have 5 subdomains .. when I found that when i do

``letsencrypt-auto certonly -d subd1 -d subd2 -d subd3 ..``

after the process completed, I only had a cert for subd1.

Unless I am missing something, that seems like a bug. I tried to find it here to see if it's open already, however, a quick search did not seem to indicate this was known already.

**Comment by pde** [comment]
Which plugin are you selecting?  Can you provide full output when run with `-tvv`?

**Comment by pde** [comment]
If you're using the Apache plugin, can you paste your config files?

**Comment by lmsurpre** [comment]
I thought we were bumping into a similar issue, but after looking deeper it was just my own misunderstanding. I thought passing multiple domains (via -d) would generate multiple certificates but it actually applies the domains to the SAN field of a single certificate.  Not sure if that's what happened here or not...maybe its enough to close it?

**Comment by bmw** [comment]
That's certainly a common misunderstanding and I think that's probably what's going on here so I'm going to close the issue. If it turns out it's a different problem, post a comment and I'll reopen.
