### ISSUE TITLE
Better support for "pip install letsencrypt" or "pip install letsencrypt-nginx" etc via error messages

### ISSUE THREAD

**Issue by pde** [certbot/certbot#2769]
Currently, it's possible to do `pip install letsencrypt-apache` and get a copy of the client.  But there are many things that can go wrong:
- OS level dependencies can be missing, causing the client to error out
- `pip` won't upgrade any packages that are provided by the OS, but at the wrong version, so various python API errors will occur in that case

For these reasons, we currently don't officially support `pip install letsencrypt`, but people try it anyway.  It would probably be good to go through, catch all the exceptions that happen for the reasons above, and print helpful error messages ("you need openssl installed"; "your version of python-cryptography is less than X", etc) in each case.

I don't think the core team will have time for this, but it's a pretty self-contained task that a volunteer might be able to take on.

**Comment by bmw** [comment]
I'm not sure how to do this. I've never seen another Python package do it and I don't know of a good way to determine that the necessary OS dependencies aren't available.

**Comment by chefscott** [comment]
Updates on how to go about this? I'd like to contribute but not sure how to get started.

**Comment by bmw** [comment]
This is bit of a research question. When someone tries to `pip install` one of our packages but doesn't have the necessary dependencies installed, can we give them a reasonable error message?

**Comment by bmw** [comment]
@chefscott, thanks for your interest in contributing. If you see a "Good Volunteer Task" issue that sounds interesting to you, I'd encourage you to try it and I'll happily answer any questions you have. I can also help you find an issue if nothing stands out. Feel free to join us in #letsencrypt-dev on Freenode where most of the Let's Encrypt and Certbot developers hang out.
