### ISSUE TITLE
Misleading dns-error message

### ISSUE THREAD

**Issue by puggan** [certbot/certbot#2780]
If you try to put up a multi-domain cert (with certonly and webroot), for
- example.com
- www.example.com
- cdn.example.com
- www.cdn.example.com

And www.cdn.example.com don't have a A-record, you get an error saying that the there was a DNS timeout for example.com.

Expected behavior: 
Report that there was a DNS error with www.cdn.example.com

Current behavior: 
- its removing the subdomain part (www.cdn), 
- or its just reporting the first domain name in the list (example.com)

**Comment by ohemorange** [comment]
This doesn't seem to be the case any longer.
