### ISSUE TITLE
acme and unknown JSON fields

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#2786]
A more general form of #2768, I think the `acme` module should ignore unknown fields instead of raising an error. Erroring out at unexpected fields provides little benefit, violates the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle), and causes problems like #2768 while the ACME protocol is under development.

@kuba, if you have any thoughts on this, I'd love to hear them.

**Comment by kuba** [comment]
When I designed this in the first place I didn't have enough time to consider security consequences of ignoring such fields. I'm happy to have the discussion, but we should likely do it on ACME mailing list. The outcome should probably be recommendation in the spec advising for or against ignoring unknown fields.

cc @jsha

**Comment by bmw** [comment]
I believe this has been resolved. Let's Encrypt has been adding random fields to their directory for a while now.

**Comment by jsha** [comment]
Do you know if it's been resolved for parsing other things like accounts, orders, authorizations, and challenges?

**Comment by bmw** [comment]
Good question! It seems like it. I spent 15-20 minutes playing around with the different objects and their `from_json` methods inserting random data and couldn't cause an error.
