### ISSUE TITLE
Functions in reverter.py should defer KeyboardInterrupt and similar kill signals

### ISSUE THREAD

**Issue by pde** [certbot/certbot#2791]
Many of the operations in `reverter.py` should be treated as atomic, to the greatest extent possible.  They should begin by registering a handler for these events, and end by raising an exception if any such events arrived.

**Comment by pde** [comment]
There is some signal handling infrastructure in `errors_handler.py` that may be reusable or at least adaptable for this purpose.

**Comment by bmw** [comment]
I'm not sure to what extent this is necessary. I believe most of the functions are written to work correctly if they crash in the middle, but we should look into this ourselves and describe what exactly needs to be done.

**Comment by vedranmiletic** [comment]
Is this the part of the code that handles prompts for user input such as `Enter email address (used for urgent renewal and security notices) (Enter 'c' to cancel):`?

If yes, I would be interested in contributing the fix.
