### ISSUE TITLE
Using dialog in small terminals

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#2812]
We have hard coded that the dialog window be 24 characters tall and 72 characters wide in `letsencrypt/display/util.py`. If the terminal is smaller than that, `dialog` raises an exception. This exception may be unnecessary because the requested `dialog` widget may fit in a terminal smaller than 24 x 72.

`dialog` has the ability to [autosize widgets](http://pythondialog.sourceforge.net/doc/Dialog_class_overview.html#autowidgetsize) which we might want to use. If we take this route, we should do the following:

1. Make sure this works on all system with both new and old version of `dialog`.
2. Make sure we're happy with how the autosized widgets look.

**Comment by pde** [comment]
@bmw can you still reproduce this?  If so, can I give you #3177 to review?

**Comment by bmw** [comment]
I've kind of been able to reproduce the issue, but the terminal needs to be absolutely tiny. Maybe something changed in newer versions of `dialog`/`python-dialog` to mitigate the problem. If so, we may still want a fix to help those running with older versions of those packages.

I'll try and take a look at this again soon.
