### ISSUE TITLE
‘Unrecognized arguments’ error misleading when plugin not installed

### ISSUE THREAD

**Issue by Smylers** [certbot/certbot#2816]
When the requested plugin hasn't been found, please give the error message about that as a higher priority to the one about unrecognized arguments. The unrecognized arguments may well be because of the missing plugin, so that's the first issue that the user needs to address.

I first tried this command:

```
$ ./letsencrypt-auto certonly --webroot -w /srv/example/www -d www.example.org
```

Which yields this error message:

```
letsencrypt: error: unrecognized arguments: -w /srv/example/www
```

That's misleading, giving little clue as to the actual problem. However, if I try omitting the complained-of arguments:

```
$ ./letsencrypt-auto certonly --webroot -d www.example.org
```

It gives the more relevant error message:

```
The requested webroot plugin does not appear to be installed
```

That explains why `-w` wasn't recognized. It'd be much more helpful to give that error message in the first place, and not quibble over what to do about optional arguments when there's the much more significant issue of the entire plugin being missing.

**Comment by bmw** [comment]
We might be able to use argparse's `parse_known_args` method to implement this.

**Comment by chrissound** [comment]
#4431

**Comment by chrissound** [comment]
Is the webroot plugin installed by default? If not, how do you install it?

**Comment by Smylers** [comment]
> Is the webroot plugin installed by default? If not, how do you install it?

Sorry, I can't remember any more.

I suspect that it is supposed to be installed by default, but either something was up with my installation or this was a server with a very old Certbot. However, a better error message would've let me track down the actual cause of the problem a lot quicker.

And the general point stands regardless, applicable to all plug-ins: if a requested plug-in isn't available, for whatever reason, then be sure to complain about that.

**Comment by instantname** [comment]
I am having the same issue, on a fairly fresh Debian Stretch install with the packaged certbot installed, and Nginx. Anyone knows how to install the webroot plugin or make it work?
