### ISSUE TITLE
`revoke` doesn't output any status

### ISSUE THREAD

**Issue by jvanasco** [certbot/certbot#2819]
If I revoke:

```
$ ./letsencrypt-auto revoke --cert-path=/path/to/cert1.pem --key-path=/path/to/privkey1.pem
```

This is the output: 

```
Checking for new version...
Requesting root privileges to run letsencrypt...
   sudo /Users/jvanasco/.local/share/letsencrypt/bin/letsencrypt revoke --cert-path=/path/to/cert1.pem --key-path=/path/to/privkey1.pem
```

Did it work?  Let's try it again.

```
$ ./letsencrypt-auto revoke --cert-path=/path/to/cert1.pem --key-path=/path/to/privkey1.pem
```

An unexpected error occurred:
The request message was malformed :: Certificate already revoked
Please see the logfiles in /var/log/letsencrypt for more details.

The log is not "human readable" when it comes to figuring out if there was a success or not.  I can parse the info, I'm pretty sure most people can't.

This command really needs to output a success message.

**Comment by Dmole** [comment]
I guess 'echo $?' is not user friendly enough and should only be expected to be used when the command has no output.

**Comment by bmw** [comment]
Yes. `echo $?` works, however, given how the rest of the client displays messages about what it has done, we should add a message here as well for better usability and consistency.
