### ISSUE TITLE
git clone on the homepage

### ISSUE THREAD

**Issue by szepeviktor** [certbot/certbot#2826]
Please consider changing `git clone https://github.com/letsencrypt/letsencrypt` to
`git clone https://github.com/letsencrypt/letsencrypt.git`
on https://letsencrypt.org/getting-started/
Thanks.

**Comment by bmw** [comment]
What is the benefit of doing this?

**Comment by szepeviktor** [comment]
GitHub gives you this URL
`https://github.com/certbot/certbot.git`
I would stick to it.
But you decide.

**Comment by bmw** [comment]
`git clone https://gitub.com/certbot/certbot` works and is a bit shorter so I think we'll keep things as is. Thanks for checking with us though.
