### ISSUE TITLE
letsencrypt files and directories

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#2830]
Are default paths like `/etc/letsencrypt/`, `/var/lib/letsencrypt`, `/var/log/letsencrypt` changing with the rename? If so, how do we prevent breakage for existing users?

**Comment by bmw** [comment]
Additionally, what about the name of the logfiles? We can just change everything to `secretname.log`, however, it will leave the directory cluttered with old `letsencrypt.log` files that are never used.

**Comment by bmw** [comment]
Also, what about the venv name in `~/.local/share/letsencrypt`?

**Comment by bmw** [comment]
I think we decided we would push all of these changes until later (if ever)?

**Comment by bmw** [comment]
Another example of this is the location of the CLI configuration file.

**Comment by SwartzCr** [comment]
@bmw is this fixed now? Can we close this?

**Comment by bmw** [comment]
Sort of. We decided not to do this now but left it open as a future possibility. I'd prefer to leave it open for 1.0 or 2.0 when we can make breaking changes to Certbot.

**Comment by bmw** [comment]
I think we should still do this at some point.

**Comment by bmw** [comment]
This would be nice, but I don't think we'll do this anytime soon, if ever, so I'm closing this issue.
