### ISSUE TITLE
Renewal conf file logging

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#2843]
We should be logging which renewal conf file we're about to process. When the client fails parsing a file, the corrupted file isn't mentioned in the logs.

**Comment by schoen** [comment]
@bmw, from our discussion just now it seems like common renewal configuration parse failures would actually end up getting logged (with the name of the file in question) from `__init__` at around

https://github.com/certbot/certbot/blob/master/certbot/storage.py#L229

Can you or anyone else identify a case or a kind of parse failure in which this information wouldn't make it to the user?

**Comment by bmw** [comment]
Looking at this again. I seem to either have been mistaken or this issue is resolved.
