### ISSUE TITLE
Domain selected from list behaves differently from domain specified by -d

### ISSUE THREAD

**Issue by ThomasMatzner** [certbot/certbot#2847]
[letsencrypt.txt](https://github.com/letsencrypt/letsencrypt/files/220468/letsencrypt.txt)

The attached log resulted from running ./letsencrypt-auto, selecting only one domain, namely www.tamatzner.de, from the offered list of domains. The error, as discussed in https://community.letsencrypt.org/t/name-does-not-end-in-a-public-suffix-on-eu-and-de-domain/14270, probably resulted from an attempt to certify another domain, namely horde.webmail. This domain wasn't even offered in the list of selectable domains.

Anyway, when running ./letsencrypt-auto -d www.tamatzner.de, the error disappeared, so the both don't appear to be exactly equivalent.

I'd be ready to share my Apache configuration. But this is a Plesk-managed server that has quite a lot of auto-generated config files. Also, by fiddling around with SSL options, they probably got modified since the time the error occurred.

**Comment by joohoi** [comment]
This is an very old issue and a lot has been changed in certbot-apache since then. I'm very confident that this issue has been solved. If this is not the case, feel free to comment here and we'll reopen the issue.
