### ISSUE TITLE
--post-hook option for certonly to automate certificate installation tasks

### ISSUE THREAD

**Issue by dentm42** [certbot/certbot#2859]
In considering automating some post certificate creation/renewal tasks - I ran across the --renew-hook option in the "renew" command.  It seems that such options would be very helpful also for the certonly command - especially since "certonly" is recommended for "more fine-grained control" in the renewal of specific certificate lineages.  It would allow users to script certificate installation within applications after certs are created increasing options for automation.

Does this make sense, or is there already some other way to have LE report the LINEAGE and DOMAINS in order to script installation of certificates once they are created/renewed with certonly?

**Comment by bmw** [comment]
Under `certbot --help renew`, there is a `--post-hook` flag that runs after all certificates that are due for renewal have been renewed. This flag also works with the `certonly` subcommand and will run after your cert is renewed (it isn't listed under the help for `certonly` due to #1460). If your cert is not due for renewal and you included `--keep-until-expiring` on the command line, `--post-hook` is not run.

I believe this does what you want, so I'm closing this issue. If you disagree, just comment on the issue and I'll reopen.

**Comment by dentm42** [comment]
Because `post-hook` runs after all the certs have been renewed, this would not accomplish what is needed.  What's needed is something that reports PER certificate where things are stored as it appears renew-hook does.  This would allow, for instance, the programatic installation of each certificate individually into its proper place.

In my environment, there are multiple server processes that need the certificate (eg., web and email).  I have all the certs installed into a central location and then update symlinks so each application references the latest certificate.  In some cases, a new cert is generated (for example if domains were added/removed) and the directory containing the keys and info has an extension appended (eg., -0003).   As it is, I have a script look through the directory for the highest serialization and use that as the symlink file.  

What would be better is if, after LE renewed/generated the cert files/directory, it could fire off a specified installation script, setting some environment variables to indicate, for example, what domain(s) the certificate was issued for (including SNI domains), and the directory into which the files were installed and possibly the individual filenames of the private and public keys.  That way the installation script didn't have to "guess" but would be given this info and could run it's process based on those passed values.

It also seemed to me that this would be the way to modularize cert installation and allow 3rd party "cert install" scripts to be fired off for various non-standard web servers/email servers/etc. or just more complex install scenarios rather than the LE devs needing to try to keep up with rolling them into LE.

Hopefully that makes some sense...  Since I have something that mostly works and hasn't caused grief (yet), I haven't thought about this for a while.
