### ISSUE TITLE
Packaging Wiki

### ISSUE THREAD

**Issue by Edenhofer** [certbot/certbot#2862]
The following section can be found on the packaging wiki. 

> The following scripts are used in the process:
> 
> * https://github.com/letsencrypt/letsencrypt/blob/master/tools/dev-release.sh
> * https://gist.github.com/kuba/b9a3a2ca3bd35b8368ef

The first link is simply broken and the second one links to a script which brings no real gain to a package maintainer IMHO. The paragraph should probably be rewritten and merely refer to [release.sh](https://github.com/letsencrypt/letsencrypt/blob/master/tools/release.sh), which was really helpful while assembling a proper package.

EDIT: I did not edit the section myself because I might be completely wrong about this. I did not write letsencrypt-code and therefore want to be very cautious about altering the documentation.

**Comment by kuba** [comment]
You're quoting "Releases" section (https://github.com/letsencrypt/letsencrypt/wiki/Packaging#releases). None of these is relevant to package maintainers. What is relevant for you is the "Notes for package maintainers" section (https://github.com/letsencrypt/letsencrypt/wiki/Packaging#notes-for-package-maintainers).

All of these should be slightly refreshed, including broken links or client rename.

**Comment by Edenhofer** [comment]
The whole page is called "Packaging" and possibly every piece of it is of interest to a maintainer. Seeing how you build the PyPI packages might help anyone trying to build it manually.
Either way the links are outdated and probably the most reasonable link would be [release.sh](https://github.com/letsencrypt/letsencrypt/blob/master/tools/release.sh).

**Comment by kuba** [comment]
To set the expectation clear: that wiki page is both for internal release process as well as advice for futher packaging. While the second link doesn't give any value to you (package maintainer) it provides value for us (devs).

I've renamed the page to ["Releases and packaging"](https://github.com/letsencrypt/letsencrypt/wiki/Releases-and-packaging) to better reflect the intention.

That being said, you shouldn't build stuff manually. It's expected that package maintainers grab tar/egg from PyPI and other ways are not supported (c.f. 1st point from https://github.com/letsencrypt/letsencrypt/wiki/Packaging#notes-for-package-maintainers: "Please use our releases, not `master`!"). Internals of this process should be oblivious to package maintainers. :)

**Comment by Edenhofer** [comment]
Surely building from the master branch is not supported but it is still possible and might make sense for testing, developing or just beeing on the bleeding edge. Furthermore since this page has been renamed it becomes even clearer that a link to https://github.com/letsencrypt/letsencrypt/blob/master/tools/release.sh should be included. I have updated the Wiki entry accordingly since there are no objections towards this change.

**Comment by pde** [comment]
In our documentation cleanup plan, we concluded that's in the wiki that's still relevant/accurate should migrate into `docs/*.rst`, and the wiki should be closed.  See #2931 and #2938.
