### ISSUE TITLE
README talks about "Let's Encrypt Client" instead of Certbot

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#2869]
This causes confusion such as te one from #2866.

**Comment by bmw** [comment]
This is a more specific version of #2738, however, since `README.rst` wasn't modified in #2865, I'll leave this open to make sure it gets done.

**Comment by SwartzCr** [comment]
I can add these changes to #2865 and then merge them all at once? Which can be maybe right before or after the repo re-name?

**Comment by SwartzCr** [comment]
I've added README.rst to #2865, please feel free to comment on them

**Comment by SwartzCr** [comment]
I'm going to close this, @kuba please look at #2865 and comment if you'd like
