### ISSUE TITLE
Major Issue - Please Help

### ISSUE THREAD

**Issue by bgengs** [certbot/certbot#2874]
My fellow developers, i'm experiencing a code red. 

System set up: Digital Ocean, NGINX, PHP, etc... 

Succesfully installed Letencrypt at Envesti.com but when installing on BeLikeBrit.org, I have crashed the website :( 

![image](https://cloud.githubusercontent.com/assets/15181256/14652413/cf71ef16-0639-11e6-8f1f-3234d3408cc4.png)

![image](https://cloud.githubusercontent.com/assets/15181256/14652398/c26df2f6-0639-11e6-9fb9-82a92b83c2f4.png)

**Comment by bgengs** [comment]
*400 SSL_do_handshake() failed (SSL: error:14094085:SSL routines:SSL3_READ_BYTES:ccs received early) while SSL handshaking, client: 64.41.200.103, server: 0.0.0.0:443

**Comment by bgengs** [comment]
![image](https://cloud.githubusercontent.com/assets/15181256/14652606/a4fb3656-063a-11e6-9f6f-dc40ae8ff704.png)

**Comment by bgengs** [comment]
server {
        listen 443 ssl;
        root /var/www/belikebrit.org/public_html;
        index index.html index.htm index.php;
        server_name belikebrit.org www.belikebrit.org;
        ssl_certificate /etc/letsencrypt/live/belikebrit.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/belikebrit.org/privkey.pem;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_dhparam /etc/ssl/certs/dhparam.pem;
        ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:50m;
        ssl_stapling on;
        ssl_stapling_verify on;
        add_header Strict-Transport-Security max-age=15768000;

**Comment by bgengs** [comment]
![image](https://cloud.githubusercontent.com/assets/15181256/14652705/0e128acc-063b-11e6-9d3d-741760355714.png)

**Comment by bmw** [comment]
What did you do with the Let's Encrypt client? How did you install it, what commands did you run, etc?

What is the output of `openssl x509 -in /etc/letsencrypt/live/belikebrit.org/fullchain.pem -noout -text`?

Do you have any logs available for us to help debug your problem? They can be found in `/var/log/letsencrypt` by default.

**Comment by SwartzCr** [comment]
Looks like it works now, closing
