### ISSUE TITLE
Modify GitHub URL in letsencrypt-auto

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#2884]
There is no rush to do this. I verified for #2639 that `letsencrypt-auto` will still receive updates after the repo rename. Changing the URL in `letsencrypt-auto` should only be done for aesthetic.

If we don't rename the repo until shortly before the rename, I believe we should wait to do this until 0.7.0 to avoid making last minute changes.

**Comment by SwartzCr** [comment]
I'm in favor of moving this to 0.7.0 along with the pypi change, so long as there's no breakage from the gh redirects

**Comment by bmw** [comment]
We decided to move this to 0.7.0.
