### ISSUE TITLE
Problematic symlink creation in mac.sh bootstrapper

### ISSUE THREAD

**Issue by MichalMMac** [certbot/certbot#2890]
I've just started experimenting with letsencrypt on OS X. I am also using MacPorts. When trying to run `letsencrypt-auto` I got following import error `raise ImportError("Unable to import lib%s!" % args[0])`. Similiar problem is described in this community [thread](https://community.letsencrypt.org/t/unable-to-import-libaugeas-on-osx-el-capitan/5794/4).

In file `letsencrypt-auto-source/pieces/bootstrappers/mac.sh` there is code responsible for creating `libaugeas.dylib` symlink:

```
# Workaround for _dlopen not finding augeas on OS X
  if [ "$pkgman" = "port" ] && ! [ -e "/usr/local/lib/libaugeas.dylib" ] && [ -e "/opt/local/lib/libaugeas.dylib" ]; then
    echo "Applying augeas workaround"
    $SUDO ln -s /opt/local/lib/libaugeas.dylib /usr/local/lib
  fi
```

`ln` command is making assumption that `/usr/local/lib` directory exists. If it does **not** exist bogus symlink `/usr/local/lib -> /opt/local/lib/libaugeas.dylib` is created.

1. Script should make sure `/usr/local/lib` directory exists (if not create it)
2. $SUDO ln -s /opt/local/lib/libaugeas.dylib /usr/local/lib/

Possible fix:

```
then
    echo "Applying augeas workaround"
    $SUDO mkdir -p /usr/local/lib/
    $SUDO ln -s /opt/local/lib/libaugeas.dylib /usr/local/lib/
  fi
```

I would submit PR but since I am new to this project It is probably better for someone with more insigh to look at it.

**Comment by MichalMMac** [comment]
Perhaps @nneonneo or @erikrose could look at this.

**Comment by nneonneo** [comment]
That's a good fix. I'm a bit concerned that we could fail to make `/usr/local/lib` on certain El Capitan installs, but that's a matter for a different PR. 

Make a PR and submit it: I would sign off on it.

**Comment by MichalMMac** [comment]
Ok PR #2943 created.

@nneonneo By El Capitan installs you mean possible problem with System Integrity Protection? /usrl/local content is not under SIP. If for some reason /usr/local itself does not exists that would be a problem but you would have to disable SIP and delete it somehow in first place.

**Comment by nneonneo** [comment]
Aha, understood. I knew that /usr/local was excluded from SIP but didn't
realize it couldn't be deleted under SIP. So I suppose there's no problem
there.

**Comment by MichalMMac** [comment]
@nneonneo Acutally I was wrong. I've just tested that `/usr/local/` can be deleted/created. 
I misinterpreted how SIP exception in `/System/Library/Sandbox/rootless.conf` works.
