### ISSUE TITLE
Ciphersuite adjustments (incl. SSL deprecation) should be an explicit enhancement

### ISSUE THREAD

**Issue by pde** [certbot/certbot#2892]
At the moment, the Apache installer tweaks ciphersuites automatically.  It should probably do that via an explicit `IAuthenticator` enhancement.  This will be part of implementing #1123.

**Comment by pde** [comment]
@azet you may be creating this enhancement in the course of making STARTTLS Everywhere into a Certbot plugin; we can go back and use it in the Apache and Nginx plugins too.

**Comment by joohoi** [comment]
Closing as per https://github.com/certbot/certbot/issues/1123#issuecomment-307879558
