### ISSUE TITLE
suggestion - version the certificates with the directory, not the filename

### ISSUE THREAD

**Issue by jvanasco** [certbot/certbot#2897]
I'm in the process of a server migration, and only need to move over the latest certs

this is a bit more work that it could be, because the versioning is:
- archive/example.com/cert1.pem
- archive/example.com/cert2.pem
- archive/example.com/cert3.pem
- archive/example.com/cert4.pem
- archive/example.com/cert5.pem

and the links are:
   cert.pem -> ../../archive/example.com/cert5.pem

that is for each domain x 4 (cert, chain, fullchain, privkey)

my suggestion is to use versioning in buckets:
- archive/example.com/0005/cert.pem
- cert.pem -> ../../archive/example.com/0005/cert.pem

this would allow people to just grab a single bucket when moving servers (or cleaning up)

**Comment by schoen** [comment]
This is related to a meeting I'm going to have in the Netherlands soon about certificate storage directory structure. I'll bring up this suggestion as part of that discussion.

**Comment by jvanasco** [comment]
@schoen a related suggestion for the directory structure (#2880) is to include a `.txt` file for each cert that lists the domains in plaintext.  this would allow commandline tools like `grep` to aid in deriving which certs/domains are associated to one another.

since certbot is Python based, one could also manage the archive – along with associated data such as activity – in a `sqlite.db` file.  the certbot client could then write/delete 'live' files onto the directory structure.

**Comment by pde** [comment]
Yes, and a (possibbly symlinked) README explaining what all the files are exactly, and all of the non-privatekey-containing formats we can dream up for the certs :)

**Comment by SwartzCr** [comment]
@bmw is this a feature we still plan to support?

**Comment by bmw** [comment]
Dunno. @schoen has been the architect behind the way we store certificates and has thought about it quite a bit. It's been a bit of a wishlist item to change things around a bit.

**Comment by jvanasco** [comment]
fwiw, every 60-90 days I hate the current filename based storage even more ;)

**Comment by jvanasco** [comment]
`certbot==0.35.0` - a certificate's files are still grouped with a sequence id as a filepath suffix. versioning would still be preferable as directory-based and not filename-based.

**Comment by jvanasco** [comment]
a certificate's files are still grouped with a sequence id as a filepath suffix. versioning would still be preferable as directory-based and not filename-based.

```
-rw-r--r--  1 root root 1.9K Sep 29  2017 cert10.pem
-rw-r--r--  1 root root 1.9K Nov 29  2017 cert11.pem
-rw-r--r--  1 root root 1.9K Jan 19  2018 cert12.pem
-rw-r--r--  1 root root 1.9K Jan 19  2018 cert13.pem
-rw-r--r--  1 root root 1.9K Feb  9  2018 cert14.pem
-rw-r--r--  1 root root 1.9K Feb 14  2018 cert15.pem
-rw-r--r--  1 root root 1.9K Mar 16  2018 cert16.pem
-rw-r--r--  1 root root 2.3K Apr  6  2018 cert17.pem
-rw-r--r--  1 root root 2.3K Apr  6  2018 cert18.pem
-rw-r--r--  1 root root 2.3K May 30  2018 cert19.pem
-rw-r--r--  1 root root 1.8K Apr 15  2016 cert1.pem
-rw-r--r--  1 root root 2.3K Aug 29  2018 cert20.pem
-rw-r--r--  1 root root 2.3K Aug 29  2018 cert21.pem
-rw-r--r--  1 root root 2.1K Nov 28  2018 cert22.pem
-rw-r--r--  1 root root 2.1K Apr  5  2019 cert23.pem
-rw-r--r--  1 root root 2.1K Sep  4  2019 cert24.pem
-rw-r--r--  1 root root 2.1K Dec 10 21:38 cert25.pem
-rw-r--r--  1 root root 2.1K Mar  3 20:54 cert26.pem
-rw-r--r--  1 root root 2.1K Jun  1 19:46 cert27.pem
-rw-r--r--  1 root root 1.9K Apr 25  2016 cert2.pem
-rw-r--r--  1 root root 1.9K Jul  8  2016 cert3.pem
-rw-r--r--  1 root root 1.9K Sep 23  2016 cert4.pem
-rw-r--r--  1 root root 1.9K Dec  1  2016 cert5.pem
-rw-r--r--  1 root root 1.9K Feb  5  2017 cert6.pem
-rw-r--r--  1 root root 1.9K Apr 18  2017 cert7.pem
-rw-r--r--  1 root root 1.9K Apr 18  2017 cert8.pem
-rw-r--r--  1 root root 1.9K Jul  7  2017 cert9.pem
-rw-r--r--  1 root root 1.7K Sep 29  2017 chain10.pem
-rw-r--r--  1 root root 1.7K Nov 29  2017 chain11.pem
-rw-r--r--  1 root root 1.7K Jan 19  2018 chain12.pem
-rw-r--r--  1 root root 1.7K Jan 19  2018 chain13.pem
-rw-r--r--  1 root root 1.7K Feb  9  2018 chain14.pem
-rw-r--r--  1 root root 1.7K Feb 14  2018 chain15.pem
-rw-r--r--  1 root root 1.7K Mar 16  2018 chain16.pem
-rw-r--r--  1 root root 1.7K Apr  6  2018 chain17.pem
-rw-r--r--  1 root root 1.7K Apr  6  2018 chain18.pem
-rw-r--r--  1 root root 1.7K May 30  2018 chain19.pem
-rw-r--r--  1 root root 1.7K Apr 15  2016 chain1.pem
-rw-r--r--  1 root root 1.7K Aug 29  2018 chain20.pem
-rw-r--r--  1 root root 1.7K Aug 29  2018 chain21.pem
-rw-r--r--  1 root root 1.7K Nov 28  2018 chain22.pem
-rw-r--r--  1 root root 1.7K Apr  5  2019 chain23.pem
-rw-r--r--  1 root root 1.7K Sep  4  2019 chain24.pem
-rw-r--r--  1 root root 1.7K Dec 10 21:38 chain25.pem
-rw-r--r--  1 root root 1.7K Mar  3 20:54 chain26.pem
-rw-r--r--  1 root root 1.7K Jun  1 19:46 chain27.pem
-rw-r--r--  1 root root 1.7K Apr 25  2016 chain2.pem
-rw-r--r--  1 root root 1.7K Jul  8  2016 chain3.pem
-rw-r--r--  1 root root 1.7K Sep 23  2016 chain4.pem
-rw-r--r--  1 root root 1.7K Dec  1  2016 chain5.pem
-rw-r--r--  1 root root 1.7K Feb  5  2017 chain6.pem
-rw-r--r--  1 root root 1.7K Apr 18  2017 chain7.pem
-rw-r--r--  1 root root 1.7K Apr 18  2017 chain8.pem
-rw-r--r--  1 root root 1.7K Jul  7  2017 chain9.pem
-rw-r--r--  1 root root 3.5K Sep 29  2017 fullchain10.pem
-rw-r--r--  1 root root 3.5K Nov 29  2017 fullchain11.pem
-rw-r--r--  1 root root 3.5K Jan 19  2018 fullchain12.pem
-rw-r--r--  1 root root 3.5K Jan 19  2018 fullchain13.pem
-rw-r--r--  1 root root 3.5K Feb  9  2018 fullchain14.pem
-rw-r--r--  1 root root 3.5K Feb 14  2018 fullchain15.pem
-rw-r--r--  1 root root 3.5K Mar 16  2018 fullchain16.pem
-rw-r--r--  1 root root 3.9K Apr  6  2018 fullchain17.pem
-rw-r--r--  1 root root 3.9K Apr  6  2018 fullchain18.pem
-rw-r--r--  1 root root 3.9K May 30  2018 fullchain19.pem
-rw-r--r--  1 root root 3.4K Apr 15  2016 fullchain1.pem
-rw-r--r--  1 root root 3.9K Aug 29  2018 fullchain20.pem
-rw-r--r--  1 root root 3.9K Aug 29  2018 fullchain21.pem
-rw-r--r--  1 root root 3.7K Nov 28  2018 fullchain22.pem
-rw-r--r--  1 root root 3.7K Apr  5  2019 fullchain23.pem
-rw-r--r--  1 root root 3.7K Sep  4  2019 fullchain24.pem
-rw-r--r--  1 root root 3.7K Dec 10 21:38 fullchain25.pem
-rw-r--r--  1 root root 3.7K Mar  3 20:54 fullchain26.pem
-rw-r--r--  1 root root 3.7K Jun  1 19:46 fullchain27.pem
-rw-r--r--  1 root root 3.5K Apr 25  2016 fullchain2.pem
-rw-r--r--  1 root root 3.5K Jul  8  2016 fullchain3.pem
-rw-r--r--  1 root root 3.5K Sep 23  2016 fullchain4.pem
-rw-r--r--  1 root root 3.5K Dec  1  2016 fullchain5.pem
-rw-r--r--  1 root root 3.5K Feb  5  2017 fullchain6.pem
-rw-r--r--  1 root root 3.5K Apr 18  2017 fullchain7.pem
-rw-r--r--  1 root root 3.5K Apr 18  2017 fullchain8.pem
-rw-r--r--  1 root root 3.5K Jul  7  2017 fullchain9.pem
-rw-r--r--  1 root root 1.7K Sep 29  2017 privkey10.pem
-rw-r--r--  1 root root 1.7K Nov 29  2017 privkey11.pem
-rw-r--r--  1 root root 1.7K Jan 19  2018 privkey12.pem
-rw-r--r--  1 root root 1.7K Jan 19  2018 privkey13.pem
-rw-r--r--  1 root root 1.7K Feb  9  2018 privkey14.pem
-rw-r--r--  1 root root 1.7K Feb 14  2018 privkey15.pem
-rw-r--r--  1 root root 1.7K Mar 16  2018 privkey16.pem
-rw-r--r--  1 root root 1.7K Apr  6  2018 privkey17.pem
-rw-r--r--  1 root root 1.7K Apr  6  2018 privkey18.pem
-rw-r--r--  1 root root 1.7K May 30  2018 privkey19.pem
-rw-r--r--  1 root root 1.7K Apr 15  2016 privkey1.pem
-rw-r--r--  1 root root 1.7K Aug 29  2018 privkey20.pem
-rw-r--r--  1 root root 1.7K Aug 29  2018 privkey21.pem
-rw-r--r--  1 root root 1.7K Nov 28  2018 privkey22.pem
-rw-r--r--  1 root root 1.7K Apr  5  2019 privkey23.pem
-rw-r--r--  1 root root 1.7K Sep  4  2019 privkey24.pem
-rw-r--r--  1 root root 1.7K Dec 10 21:38 privkey25.pem
-rw-r--r--  1 root root 1.7K Mar  3 20:54 privkey26.pem
-rw-r--r--  1 root root 1.7K Jun  1 19:46 privkey27.pem
-rw-r--r--  1 root root 1.7K Apr 25  2016 privkey2.pem
-rw-r--r--  1 root root 1.7K Jul  8  2016 privkey3.pem
-rw-r--r--  1 root root 1.7K Sep 23  2016 privkey4.pem
-rw-r--r--  1 root root 1.7K Dec  1  2016 privkey5.pem
-rw-r--r--  1 root root 1.7K Feb  5  2017 privkey6.pem
-rw-r--r--  1 root root 1.7K Apr 18  2017 privkey7.pem
-rw-r--r--  1 root root 1.7K Apr 18  2017 privkey8.pem
-rw-r--r--  1 root root 1.7K Jul  7  2017 privkey9.pem
```

**Comment by jvanasco** [comment]
This is still the behavior.

**Comment by osirisinferi** [comment]
I'm not sure if I fully understand the added benefit of this extra directory depth: you're just *moving* the increment number from a suffix to a directory? In the proposed situation, your migration script would still need to figure out which increment number is being used to be able to copy/migrate the correct directory, right? If your script kan determine the increment number for directories, I'm sure it can figure that out for filename suffixes, right?

This all assumes you're actually using a script, although with your comment "every 60-90 days I hate the current filename based storage even more", I'm not so sure. If you're doing this manually, I'm not sure if the certbot team should indulge a feature for a recurring event which IMHO should be scripted anyway.

**Comment by ikabod** [comment]
I would prefer no versioning at all. This would prevent filling folder with files who almost nobody needs anymore.

Why not get rid of the symlinks from the live directory to the archive directory at all?
Before replacing the current files in the live directory, copy them to the archive directory and get them a version number there. And I would prefer to be able to setup a maximum of files in the archive directory since in the last 2 years I never have had the need to look at these old certificates. So I would set it to a maximum of 1.

These symlinks makes it hard for me (I'm not a linux expert) to back them up on my local system and to restore them on a new server.

If I could simply copy the live directory without symlinks in it, all would be easier.

Only my 2 cents, I'm not a certificate specialist either.
