### ISSUE TITLE
Use pip on Debian

### ISSUE THREAD

**Issue by szepeviktor** [certbot/certbot#2899]
How could I prevent installing `python-chardet-whl python-colorama-whl python-distlib-whl python-html5lib-whl python-pip-whl python-requests-whl python-setuptools-whl python-six-whl python-urllib3-whl` Debian packages and install the by pip in the local virtualenv?

**Comment by pde** [comment]
What command did you run that pulled in those dependencies? What version of Debian are you on?

**Comment by szepeviktor** [comment]
I've ran `letsencrypt-auto`, it installed those packages on Debian Jessie.
https://github.com/certbot/certbot/blob/master/letsencrypt-auto#L241-L250

**Comment by szepeviktor** [comment]
Please consider allowing pip-only installs. Thanks.

**Comment by bmw** [comment]
All of the OS packages installed [here](https://github.com/certbot/certbot/blob/master/letsencrypt-auto#L241-L250) are required for our Python packages to work. For example, `pythondialog` [requires dialog](https://pypi.python.org/pypi/python2-pythondialog/3.3.0#requirements) to run.

**Comment by szepeviktor** [comment]
Yes.
All of them except virtualenv which is a pure python package.

**Comment by szepeviktor** [comment]
I've just fired up jessie in a Docker container:

```
The following NEW packages will be installed:
  augeas-lenses binutils cpp cpp-4.9 dialog gcc gcc-4.9 libasan1 libatomic1 libaugeas0 libc-dev-bin libc6-dev libcilkrts5
  libcloog-isl4 libexpat1-dev libffi-dev libgcc-4.9-dev libgomp1 libisl10 libitm1 liblsan0 libmpc3 libmpfr4 libpython-dev
  libpython-stdlib libpython2.7 libpython2.7-dev libpython2.7-minimal libpython2.7-stdlib libquadmath0 libssl-dev libtsan0
  libubsan0 libxml2 linux-libc-dev python python-chardet-whl python-colorama-whl python-dev python-distlib-whl
  python-html5lib-whl python-minimal python-pip-whl python-pkg-resources python-requests-whl python-setuptools-whl python-six-whl
  python-urllib3-whl python-virtualenv python2.7 python2.7-dev python2.7-minimal python3-pkg-resources python3-virtualenv
  virtualenv zlib1g-dev
```

**Comment by szepeviktor** [comment]
Any Python Debian package conflicts with a system-wide pip.
That is why I avoid using apt for python.

**Comment by bmw** [comment]
We use virtualenv so we can create an environment for installing packages through `pip` that doesn't affect the rest of your system. Alternatively, we could install `python-pip` through your package manager, and then install packages through `pip`, but I think the first approach is very much preferred.

Also, if you're on Jessie, you can use the [package](https://packages.debian.org/jessie-backports/letsencrypt) in `jessie-backports`. For most people, this should be preferred over `letsencrypt-auto`.

**Comment by szepeviktor** [comment]
Thank you.
As I've said I am trying to avoid Debian Python packages.
For example: one of the Debian Python packages depend on requests and I have some pip installed packages. When I do `pip install PKG -U` pip overwrites Debian's python-requests package and debsums alerts me.
That is why I am asking for a pure pip-only install if it is possible.

**Comment by szepeviktor** [comment]
BTW What is the purpose of `*-dev` Debian pacakges?

**Comment by bmw** [comment]
> That is why I am asking for a pure pip-only install if it is possible.

Sure, but you'll do the install by hand.
1. Install non-Python Debian packages `python python-dev gcc dialog libaugeas0 augeas-lenses libssl-dev libffi-dev ca-certificates` (if you're not planning on using the Apache plugin, you can omit `libaugeas0 augeas-lenses`).
2. Finally, `pip install certbot -U`.

Does this work for you?

> What is the purpose of *-dev Debian pacakges?

If you're referring to `python-dev`, this is the header files and static library needed to compile Python packages that communicate with programs written in something like C.

**Comment by szepeviktor** [comment]
Thank you very much! This is very kind from you. I like stripped-down solutions.
Is there a way to avoid C bindings?

**Comment by bmw** [comment]
This currently isn't possible with the Certbot client. Other more minimalistic clients such as https://github.com/diafygi/acme-tiny/blob/master/acme_tiny.py have done this though. If you're interested, you should definitely take a look.

While this isn't supported in Certbot, it's something we're very interested in doing, but it would require rewriting our `acme` module to shell out to `openssl` instead of binding to `libssl` directly. We'd certainly consider a PR that does this!
