### ISSUE TITLE
Update readthedocs endpoint to change with repo rename

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#2912]

**Comment by bmw** [comment]
After testing this, our readthedocs site won't be deleted, however, it will no longer automatically update when our documentation changes. To fix this, we have to remember to update our GitHub URL on readthedocs after the repo rename.

**Comment by SwartzCr** [comment]
@bmw make sure to close this once you've moved readthedocs

**Comment by bmw** [comment]
I moved and successfully tested it still works. Woo!
