### ISSUE TITLE
Useful errors when data within /etc/letsencrypt is inconsistent or corrupt

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#2918]
A recent issue (#2903) showed that if users manually edit the contents of `/etc/letsencrypt` in a way that the client regards as inconsistent (for example, some files no longer exist in the relationships that `storage.py` expects), the client is often not cautious enough to notice and explain the problem, and instead may crash with an exception. This isn't very helpful; what would be more helpful would be to tell the user something like "This certificate lineage appears to have been modified or partially deleted on disk, and the client can't find some of the associated files" instead of (e.g.) "ValueError: max() arg is an empty sequence", or various other cases that it's probably possible to trigger by deleting symlink targets.

We should go through and look at everywhere that the renewer or `storage.py` follows a symlink or creates or reads a file, and make sure that failures based on corrupted lineage structure are handled intelligently.

**Comment by bmw** [comment]
The code [here](https://github.com/letsencrypt/letsencrypt/blob/master/certbot/storage.py#L271) was supposed to catch this early, however, it appears more thorough error checking is needed.

**Comment by schoen** [comment]
Yeah, I think there are several ways things can still go wrong!

**Comment by ohemorange** [comment]
Hey @schoen, what are some examples of specific ways this could go wrong, when we would hit this?

**Comment by schoen** [comment]
I think this is actually a duplicate of #775!
