### ISSUE TITLE
letsencrypt shim tests

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#2924]
For some reason, the `letsencrypt` shim package doesn't have any tests (all other shim packages run the tests of the package they are a shim for). I don't think this is a problem, but perhaps we should investigate and fix it regardless.

**Comment by bmw** [comment]
Tests work when running `python setup.py test -s letsencrypt` but not `nosetests letsencrypt`.

**Comment by bmw** [comment]
@erikrose, you know a thing or two about Python packages and `nosetests`. Any thoughts on this?

**Comment by erikrose** [comment]
Nose does an awful lot of import magic while finding tests. My initial suspicions would be…

1. Another thing in the cwd called `letsencrypt`. Try running nose on both the working and the non-working shims from a shell whose cwd is, say, `/tmp`. See if that makes any difference.
2. Another thing in `sys.path` called `letsencrypt`. See if `sys.path` has anything untoward in it.

**Comment by bmw** [comment]
Your suspicions are correct. With the current version of `nose`, it appears that if you run `nosetests letsencrypt` and there is both a module and a directory named `letsencrypt`, `nose` only searches the directory for tests. Changing my cwd fixed the problem. Thanks Erik!

**Comment by erikrose** [comment]
Glad it was a simple fix! :-D
