### ISSUE TITLE
setup.py: datetime dep needs versioning

### ISSUE THREAD

**Issue by fooishbar** [certbot/certbot#2934]
letsencrypt actually requires datetime >= 1.2, however the dependency in setup.py is unversioned, meaning it can be satisfied by old distro packages. Versioning it forces an install from a newer upstream version, which resolves the breakage.

**Comment by bmw** [comment]
Please correct me if I'm wrong, but I believe you're referring to `parsedatetime` and I think the version needs to be pinned at `parsedatetime>=1.3`. Tests fail on my system when using `parsedatetime==1.2`.

**Comment by fooishbar** [comment]
@pde Wow, that was a name I wasn't expecting to see - thanks!
