### ISSUE TITLE
letsencrypt-auto --help: E: There are problems and -y was used without --force-yes

### ISSUE THREAD

**Issue by aebrow4** [certbot/certbot#2946]
Running any form of `letsencrypt-auto` or `letsencrypt certonly` results in the following error on the Raspberry pi:  `E: There are problems and -y was used without --force-yes`

Running with sudo or --force-yes does not make a difference

**Comment by bmw** [comment]
Which OS are you running your Raspberry pi?

**Comment by aebrow4** [comment]
Debian/Raspbian.  I got around the issue by manually apt-getting all of the packages and then re-running the command, so you can close the issue if you want, though theoretically it will remain for other Raspberry Pi users.

**Comment by bmw** [comment]
Yeah. This should definitely stay open so we can fix the issue for others. I'm glad you found a workaround though!

**Comment by LiamK** [comment]
I was able to get around this using --force-yes.  That worked for me.
uname -a
Linux ip-10-0-0-10 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux
cat /etc/debian_version 
8.4

**Comment by bmw** [comment]
Since this issue hasn't seen any traffic since 2016, I'm closing, however, anyone continues to hit this issue, please comment or open a new issue.
