### ISSUE TITLE
letsencrypt-auto parses any file in apache2/sites-available directory

### ISSUE THREAD

**Issue by cosimosimeoneTR** [certbot/certbot#2949]
Hey there!
I realized by running 
```
# ./letsencrypt-auto --apache -d myDomainName.com -d www.myDomainName.com
Checking for new version...
Requesting root privileges to run letsencrypt...
   /root/.local/share/letsencrypt/bin/letsencrypt --apache -d myDomainName.com -d www.myDomainName.com
An unexpected error occurred:
RuntimeError: ('Error during match procedure!', u'/files/etc/apache2/sites-available/000-default.conf,OLD/VirtualHost/arg')
Please see the logfiles in /var/log/letsencrypt for more details.
```
that parser checks ```000-default.conf,OLD```, which is not a configuration (```.conf```) file.
Plus, ```myDomainName.com``` has its own configuration file in ```sites-available```, so i'm wondering if parser should check  ```000-default``` as all.

Thanks!

**Comment by pde** [comment]
Passing to @joohoi for evaluation.

**Comment by joohoi** [comment]
Yes, this is correct, on Debian / Ubuntu at least, defined here: https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/constants.py#L9

As I see it, the handling of actually active configuration is done by symlinking a config.conf from sites-enabled to sites-available, not by renaming files in sites-available. Debian 7 actually does read sites-enabled/* while Debian 8 only reads sites-enabled/*.conf. This also includes support for non .conf configuration files by a2ensite & a2dissite.

**Comment by joohoi** [comment]
However, we seem to have an bug in reading filenames with comma in it, so thanks for reporting this! 

I will create a new issue for the actual underlying issue.

**Comment by cosimosimeoneTR** [comment]
Indeed, agree! :-)
But file returning exception (regardless of comma problem) is in `/files/etc/apache2/sites-available/`, not in `sites-enabled` which, as you said, should correct path to parse files.
So, line https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/constants.py#L8 might be changed as well (?)

Plus -more as a question than as a requirement-, should `000-default.com` be parsed, when i have a .conf file for myDomainName.com, which i passed as parameter?

**Comment by joohoi** [comment]
Parsing sites-available enables user to create a virtualhost that is not served via HTTP at any point, and letting certbot to further configure the vhost for HTTPS. 

ie: user would create an vhost file under sites-available but not activate it by symlinking from sites-enabled. Upon running certbot, the HTTPS vhost would be created and activated, resulting in a scenario where only HTTPS vhost is served through Apache.

Answer to the question about 000-default is yes, it should be parsed. The comma bug just errors out completely, so it can't proceed.

**Comment by pde** [comment]
OK, closing this since we now have #2983
