### ISSUE TITLE
letsencrypt/tests/display/completer_test fails without gnureadline

### ISSUE THREAD

**Issue by groxxda** [certbot/certbot#2956]
`gnureadline` should either be a documented dependency or the test should pass without it.
Modifying the import like in letsencrypt/display/completer.py:

```
try:
    import readline
except ImportError:
    import letsencrypt.display.dummy_readline as readline
```

is not enough since `test_import_error` will still try to load the original readline.

**Comment by pde** [comment]
Hmmm, do you think we can get away with making this a `dev_extras` dependency?

**Comment by groxxda** [comment]
If we add it as dev_extras dependency, it will be used for tests and might not be available during runtime, right? So there will be a code branch that's not going to be tested :sad:
I'd rather adjust the import in the tests to match the runtime code and skip the one failing test when fakereadline is used.
Just my opinion without deeper knowledge of the project :wink:

**Comment by bmw** [comment]
> If we add it as dev_extras dependency, it will be used for tests and might not be available during runtime, right? So there will be a code branch that's not going to be tested.

Actually, there's a test that forces `import readline` to fail even if it's available on the system ([source](https://github.com/certbot/certbot/blob/master/certbot/tests/display/completer_test.py#L53)), so adding `readline` as a `dev_extra` dependency should work I think.

**Comment by groxxda** [comment]
The test you mentioned is the one that fails with the dummy_readline import (the one I suggested skipping when no readline is available).
I have no preference how this is fixed, although I don't understand why we should add a dependency to make a test happy that explicitly removes the dependency :wink:

**Comment by pde** [comment]
@groxxda do you think you might be able to send us a PR for this?
