### ISSUE TITLE
Problem using Gandi plugin 

### ISSUE THREAD

**Issue by Canalytic** [certbot/certbot#2957]
The instructions for the [gandi plugin](https://github.com/Gandi/letsencrypt-gandi) call for:

`~/letsencrypt-gandi $ ~/.local/share/letsencrypt/bin/pip install -e .`

But the new repository for letsencrypt at certbot contains no bin directory, so I am getting a No such file or directory error

**Comment by pde** [comment]
That's weird. The `bin` directory within the `~/.local/share/letsencrypt/` virutalenv directory should still be created when you run `letsencrypt-auto` (or after 0.6.0 is released on Thursday, it will also be called `certbot-auto`).

Alternatively you could make and use a virtualenv directory by following these directions: https://letsencrypt.readthedocs.org/en/latest/contributing.html#running-a-local-copy-of-the-client

**Comment by SwartzCr** [comment]
Looks this was fixed upstream, closing, but feel free to re-open if you can repro
