### ISSUE TITLE
Add an command line option to define uid / gid for certificate file & path

### ISSUE THREAD

**Issue by joohoi** [certbot/certbot#2964]
Users need to be able to define custom privileges for cert & pk paths to be able to benefit from the certs and autogenerated symlinks as a static path for software that doesn't run as a root (even before dropping privileges).

**Comment by pde** [comment]
See also #1473

**Comment by pde** [comment]
@NoodlesNZ do you think you or one of the other RPM packaging folks would be interested in working on this and #1473? It's a feature that makes most sense in combination with OS packaging that ensures that there is an appropriately configured GID in place from the OS's perspective. We've talked about it a bit with @hlieberman (on the Debian side, the relevant group is probably `ssl-cert`) but I suspect he's sufficiently busy with backporting and Ubuntu wrangling tasks that he won't get to this soon.

**Comment by pde** [comment]
Related: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=859209

**Comment by boltronics** [comment]
Also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=893738

**Comment by Neustradamus** [comment]
Any news on it?

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.
