### ISSUE TITLE
Final style tweaks

### ISSUE THREAD

**Issue by hughillustration** [certbot/certbot#2972]
Home:
Tagline line height is too narrow. I’d like to see this type smaller and on one line on desktop view.

Privacy policy page:
H2 is too big, should match H2 on FAQ

Home mobile views:
Logo comes back in upper left.

Instructions have too much white space above

Tag line should reduce in size and line height fixed

About:
I notice the visited state on links is still enabled. Let’s remove that. (applies throughout)

**Comment by pde** [comment]
@hughillustration this issue was filed against the wrong repo (certbot/certbot rather than certbot/website). If any of these issues are outstanding, file an issue for those here: https://github.com/certbot/website/issues
