### ISSUE TITLE
OS X Tests

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#2978]
Travis supports [OS X Build Environments](https://docs.travis-ci.com/user/osx-ci-environment/). We should set one of these up for fixing/preventing regressions on OS X.

**Comment by bmw** [comment]
@TheNavigat might be interested in this

**Comment by TheNavigat** [comment]
I think we need to fix https://github.com/certbot/certbot/issues/1535 first.

**Comment by TheNavigat** [comment]
Fixed. Working on this issue.

**Comment by yan12125** [comment]
There's a blocker: https://github.com/travis-ci/cpython-builder/pull/3

As Python 3 support is almost there, I think it's good to test both Python 2 and 3 on macOS. However, the aforementioned issue should be resolved first, or the common ```python: "x.y"``` pattern in ```.travis.yml``` won't work.

**Comment by bmw** [comment]
I agree testing with multiple Python versions on macOS is valuable, but could we test using a single Python version on macOS until that issue is resolved?

**Comment by yan12125** [comment]
It's possible to use the system Python on Travis CI. More work should be done so that all tests pass on macOS.

For those who are interested, here's my previous try: https://travis-ci.org/yan12125/certbot/builds/227099560

**Comment by bmw** [comment]
Fixed in #4697.
