### ISSUE TITLE
renew --dry-run picks up all past certs; how to discount certs i no longer need?

### ISSUE THREAD

**Issue by fsantiago07044** [certbot/certbot#2985]
i have several sites I've requested certs for in the past but no longer host. ./certbot-auto renew still tries these no longer needed certs, understandably. --dry-run reports failures on these attempts since I originally used webroot and my web server no longer responds to those sites plus i've largely deleted the dns records. 

with that all being said, how can i stop the certbot client from trying the sites i no longer need?

**Comment by schoen** [comment]
@fsantiago07044, we plan to eventually create a "Certificate Manager" that will let you view, modify, and delete certificates that you have installed. Until that's done, you have to make these changes pretty manually. In this case, you can do

`cd /etc/letsencrypt/renewal`

In that directory, you'll see a number of files that end in `.conf`. Each of these should correspond to one of the certificates for which renewal is being attempted. If you can figure out which files you want to disable, you can then run something like

`mv example.com.conf example.com.conf.disabled`

That will still keep the certificate data around but will stop `certbot renew` from trying to renew it. (However, there may be a bug if you subsequently try to get a fresh certificate for one of those names; if you ever find that you need to do that, you might want to do `mv example.com.conf.disabled example.com.conf` to re-enable it before trying to get the new certificate.)

**Comment by pde** [comment]
Duplicate of: #2305.
