### ISSUE TITLE
*-auto arg parsing problems

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#2987]
If you run `certbot-auto --os-packages-only`, `getopts` parses the `n`, thinks you mean `-n` and forces yes in your package manager.

To do what we want in a portable way, I think we'll have to do argument parsing by hand.

**Comment by pde** [comment]
Is `--os-packages-only` still respected in this case?

**Comment by pde** [comment]
(If no, this would be really bad; if yes, it's non-optimal but not so terrible)

**Comment by pde** [comment]
Since the user *did* just ask to have OS packages installed :)

**Comment by bmw** [comment]
Yes, `--os-packages-only` is still respected,

Basically, all long options work fine, however, the script will incorrectly think short options were passed.

For `letsencrypt-auto`, all this means is sometimes you'll get the verbose output from `letsencrypt-auto` when you didn't ask for it. This happens if you run things like `letsencrypt-auto --non-interactive`, `letsencrypt-auto revoke`, `letsencrypt-auto --version`, etc. Anything that includes a `v` will trigger verbose output.

For `certbot-auto`, you have the above problem, as well as sometimes forcing yes if you didn't ask for it (if any flags you pass include an `n`). I think the worst problem though is if you don't have a venv for `certbot` and you pass a flag that includes an `h`, you'll get the `--help` output and then the script will exit.

I believe I have a working branch that fixes this, but I'm working on testing.
