### ISSUE TITLE
Renew option is renewing certs daily despite no need 

### ISSUE THREAD

**Issue by fsantiago07044** [certbot/certbot#2993]
I've been running as a cron job the new certbot with renew option for two days and it's been renewing my certs each time instead of detecting there's no need to. This will find me rate limited soon. In addition to the extra overhead on your systems. What to do?

**Comment by fsantiago07044** [comment]
And I've been rate limited.....

**Comment by schoen** [comment]
Did you include `--renew-by-default` or `--force-renewal` in your command line anywhere?

**Comment by fsantiago07044** [comment]
No I did not. Only the renew and quiet options. 

On May 16, 2016 12:07:02 AM EDT, schoen <notifications@github.com> wrote:
>Did you include `--renew-by-default` or `--force-renewal` in your
>command line anywhere?
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/certbot/certbot/issues/2993#issuecomment-219344572

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by schoen** [comment]
Could you tell me what command line you're using for the renewal process?

How many items do you have in `/etc/letsencrypt/live/example.com` for your domain? Can you confirm that there's a new set each time that the command was run?

Did you change any settings in `cli.ini` or in `example.com.conf` for your domain? What version of the client are you using and how did you install it?

Thanks.

**Comment by fsantiago07044** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

My apologies.....I misunderstood all that the new certbot and renew option were doing. All fixed now. I just had to append my prior cli and tweak some settings. Thanks. It's working as it should now.

Fabe


On May 17, 2016 12:39:37 PM EDT, schoen <notifications@github.com> wrote:
>Could you tell me what command line you're using for the renewal
>process?
>
>How many items do you have in `/etc/letsencrypt/live/example.com` for
>your domain? Can you confirm that there's a new set each time that the
>command was run?
>
>Did you change any settings in `cli.ini` or in `example.com.conf` for
>your domain? What version of the client are you using and how did you
>install it?
>
>Thanks.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/certbot/certbot/issues/2993#issuecomment-219777436

- --
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJLBAEBCgA1BQJXPQlwLhxGYWJpYW4gU2FudGlhZ28gPGZzYW50aWFnb0BnYXJi
YWdlLWp1aWNlLmNvbT4ACgkQB1PGHhrXmkEToQ/+IOb2w5YXhyl+WStGBF5mzSHj
mgi1JeMhsQNrVcI23EvveMsrQr3efLaVpf2XU6hKvdbPlXeiVUaBhd1FYppka0EC
/N3aX5DRARCeKGk1DwGSpAaQ6SQ90DdgXEYXMVK72Cxq/MOPaGTBoOTsZ2Zvl8WE
zF9pi86QbqfiuX9twvtBL8Zqv+4LpEeTB6jKz7hI3NXVpkdxjBeHbRwx2umMtJXQ
ATtBoWYLIaqGLplfvaNhpfY90FrWrddefb3Foqd8rYJY+q3iCyDtQRfGsW+RAaXi
FIUhvib/34FH21LY+5oJJihviajBacAA7aK/CajkDkAHeijEoz+IxTAwEDXT5nlT
c1b7EK3NQ9055zHon1yV7p4IAHVZqZeKkVrhwTunzYcvlbLpRgKt1jDGCa9sjTkA
8V08vle76rVptFfkbWXJ1RmlGuWwEZlvLeX7ROjF3J2nnRZ2e9LCp3f6RzkDva9N
evF/58uixVtDvFVgQUI9b0LdjwHumNnqQS7RjyUb7E2+vpuK3uk4ZJ3Hu9X5TDi7
A/8P6k8bUJqcETFJQGuZTEuzmBGuRRzDTJoO2Kfo31xA3gNIyImsjh2PLDGjbwa6
87CM/nFdneldSaQZvOfRsVH1PXc/Kn1MkWpbeoDZVINWe8hzDwVTvrFjHIOI4vTG
oldC3k9/9tNpvUV+ZfI=
=VADk
-----END PGP SIGNATURE-----

**Comment by bmw** [comment]
Glad you've got it working!
