### ISSUE TITLE
OOM killed installer

### ISSUE THREAD

**Issue by surfskidude** [certbot/certbot#2995]
The OOM killed the certbot installer (probably during python configuration) on my VPS. At one time, the VPS crashed and I had to reboot the VPS. I am using the Blueberry plan: https://www.berry.pw/

It's time to redesign certboot using less bloated software. The tool should be designed as a native C program.

**Comment by schoen** [comment]
I filed issue #3001 to track this general problem, which we've also seen from Raspberry Pi users and at least one other VPS user.

I don't think we would ever rewrite Certbot in C, but I do think we should be able to improve the installation memory footprint. (An alternative which isn't a complete solution is to make more OS packages available.)

**Comment by schoen** [comment]
This turns out to already be tracked at #1081.
