### ISSUE TITLE
Support for startssl?

### ISSUE THREAD

**Issue by Harvie** [certbot/certbot#2996]
Hello,
i've heard that StartSSL offers similar service, but currently uses different protocol. Do you think it would be possible for EFF and StartSSL to make things compatible, so we can use single client with multiple CAs?

**Comment by schoen** [comment]
You'll need to ask StartSSL whether they'd like to implement the ACME protocol. We have no control over that, but Certbot will work with StartSSL (probably without modification!) if it adds ACME support on the certificate authority side.
