### ISSUE TITLE
Letsencrypt-auto fails to build wheel for cffi Amazon Linux

### ISSUE THREAD

**Issue by abdullahshahin** [certbot/certbot#2997]
I have a problem when issuing a certificate for a domain under Amazon linux, below is the command

> ./letsencrypt-auto --python="/usr/bin/python2.7" --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory certonly -d domain.com -v --debug

I have tried all available options from earlier and similar cases with no luck, below is the error

> gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DUSE__THREAD -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o {standard input}:
> 
> Assembler messages: 
> {standard input}:802: Error: expecting string instruction after rep' 
> {standard input}:1064: Error: expecting string instruction afterrep'
>  {standard input}:12644: Error: expecting string instruction after rep'
>  {standard input}:13262: Error: expecting string instruction afterrep' 
> {standard input}:13299: Error: expecting string instruction after `rep' 
> error: command 'gcc' failed with exit status 1

the OS version is Amazon Linux AMI release 2013.03, and the web server is Apache/2.4.18 (Amazon)

**Comment by pde** [comment]
I think unfortunately we aren't going to be able to support such old versions of Amazon Linux, but happy to take a volunteer patch for this.

**Comment by sydneyli** [comment]
Closing in favor of tracking at #6505.
