### ISSUE TITLE
[INVALID Authority] Cert Authority NOT recognized on Android browsers

### ISSUE THREAD

**Issue by Atrix1987** [certbot/certbot#3000]
While it works on iPhone and Chrome on Macbook Pro, on some android devices (One Plus X, Intex) both chrome and default browsers, it says Cert Authority is **INVALID**. Tried this on my website (www.abhisheknandi.com) to confirm everything is fine and finally I added it on my company dashboard and APIs. Now am not sure whether to revoke it and buy one like old days or do I wait for something to get fixed? 

<img width="489" alt="screen shot 2016-05-16 at 8 52 24 am" src="https://cloud.githubusercontent.com/assets/2898596/15279588/993370b8-1b43-11e6-82da-3bd792d54d68.png">

Clearly **Let's Encrypt Authority X3** is not added as a trusted authority in certain cases. Please help.

![13234863_10209508144605528_1741411533_o](https://cloud.githubusercontent.com/assets/2898596/15279498/955e27b8-1b42-11e6-8c36-e47ac7422a68.png)

![13241572_10156869238730392_1163547241_o](https://cloud.githubusercontent.com/assets/2898596/15279499/955ec376-1b42-11e6-9686-ada4a2ec3732.jpg)

**Comment by schoen** [comment]
You need to serve the complete certificate chain, not just the end-entity certificate.

The intermediate certificate is available in `chain.pem` (or `fullchain.pem`). You must configure your web server to use one of those files in order to provide the complete chain. Then use https://www.ssllabs.com/ssltest/ to check whether the configuration is correct.

**Comment by parmonov98** [comment]
> You need to serve the complete certificate chain, not just the end-entity certificate.
> 
> The intermediate certificate is available in `chain.pem` (or `fullchain.pem`). You must configure your web server to use one of those files in order to provide the complete chain. Then use https://www.ssllabs.com/ssltest/ to check whether the configuration is correct.

![image](https://user-images.githubusercontent.com/24564577/169164945-8015cf1d-355c-4fc9-9e6e-2670253bf89b.png)

on older browsers (os x) Safari failed to open page,  same issue on chrome on the same OS.
but other browsers on other OS s are working without problem. 
what might be wrong here? 

all4u.market can you check the domain here?
