### ISSUE TITLE
Certbot installer has very large memory requirements

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#3001]
We're getting periodic reports that people on small-memory systems are unable to complete the installation process (using `certbot-auto`) because they get out-of-memory errors. (This is most common on a Raspberry Pi, but we've also gotten these reports from people using a memory-limited VPS configuration.)

This seems somewhat unreasonable to me; I don't understand why our resource requirements are so great.

**Comment by bmw** [comment]
Dupe of #1081?

**Comment by schoen** [comment]
Agreed, sorry.
