### ISSUE TITLE
Zero-downtime renewed certificate deployment

### ISSUE THREAD

**Issue by eligrey** [certbot/certbot#3002]
I can auto-renew certs without any downtime by using webroot, but the only way for Nginx and Apache to actually *use* the new certs is to restart/reload the webserver. There should be a way to deploy renewed certs without any downtime.

I currently use `@monthly service nginx reload` in my root crontab so nginx automatically restarts once a month to use new certs, but this introduces a couple seconds of downtime.

**Comment by bmw** [comment]
My understanding is `service nginx reload` should not introduce any downtime. [Relevant discussion on Stack Exchange](https://serverfault.com/questions/378581/nginx-config-reload-without-downtime).

**Comment by eligrey** [comment]
Ah, I didn't realize this. I just assumed that nginx wouldn't be responsive during that 2-second pause in my terminal. Thank you for the info. You can close the issue if you want.

Btw, does Apache have similar functionality?

**Comment by bmw** [comment]
It does. In Apache, it's called [graceful](https://httpd.apache.org/docs/current/stopping.html#graceful).
