### ISSUE TITLE
Too many flags setting configurators/installers/authenticators 

### ISSUE THREAD

**Issue by hannesa2** [certbot/certbot#3006]
When I try to reuqire a new cert, I receive this

```
./letsencrypt-auto certonly --standalone --email name@googlemail.com  -d my.domain.info -d my2.domain.info
Checking for new version...
Requesting root privileges to run certbot...
sudo CERTBOT_AUTO=./letsencrypt-auto /home/seppl/.local/share/letsencrypt/bin/letsencrypt certonly --standalone --email name@googlemail.com  -d my.domain.info -d my2.domain.info
Use of --agree-dev-preview is deprecated.
Too many flags setting configurators/installers/authenticators 'webroot' -> 'standalone'
```

.. but I've no idea how to solve this. Any ideas ?

**Comment by bmw** [comment]
Do you have a [configuration file](https://certbot.eff.org/docs/using.html#configuration-file)?

**Comment by antonin07130** [comment]
I can't get the configuration file setup to work with the docker image if certbot :
* is that image from certbot team : quay.io/letsencrypt/letsencrypt:latest ?
* if so is there a simple way to make it work with a configuration file ? (I tried mounting the file and starting the container with -c "filename.ini" with no success).

**Comment by schoen** [comment]
I'm going to close this. @hannesa2, it looks like you probably had a `cli.ini` configuration file (hopefully you figured that out eventually). @antonin07130, if you're still having trouble using Certbot with Docker, please open a separate issue.

Thanks!
