### ISSUE TITLE
Not running on Raspberry Pi 2B  Raspbian 7 running Apache server.

### ISSUE THREAD

**Issue by jimaldon** [certbot/certbot#3007]
I get the following when I run `./certbot-auto --apache`

`Checking for new version...
Requesting root privileges to run certbot...
sudo CERTBOT_AUTO=./certbot-auto /home/pi/.local/share/letsencrypt/bin/letsencrypt --apache
The apache plugin is not working; there may be problems with your existing configuration.
The error was: NotSupportedError('Apache plugin support requires libaugeas0 and augeas-lenses version 1.2.0 or higher, please make sure you have you have those installed.',)
`

**Comment by bmw** [comment]
The Apache plugin requires `libaugeas0` >= 1.2.0 and `augeas-lenses`  to be installed in order to work. Are these packages available through your package manager?

**Comment by bmw** [comment]
Raspbian 7 is no longer supported and Raspbian 8+ should have a new enough version of Augeas so I'm closing this issue.
