### ISSUE TITLE
trouble with Listen directives in CentOS 7 / ssl.conf

### ISSUE THREAD

**Issue by dpocock** [certbot/certbot#3022]
On a CentOS7 box, I had Listen directives in /etc/httpd/conf.d/ssl.conf binding to a specific IP and port 443:

```
Listen 195.8.117.80:443 https
Listen [2001:67c:1388:1001::6]:443 https
```

and other services running on other IP addresses bound to port 443.

Running letsencrypt-auto I was getting this in the httpd error_log:

```
(98)Address already in use: AH00072: make_sock: could not bind to address [::]:443
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:443
```

I stopped the other services temporarily but letsencrypt-auto still failed.

I commented the Listen lines and then the letsencrypt-auto command worked.

After running it, I noticed it had created new Listen directives at the bottom of /etc/httpd/conf/httpd.conf:

```
<IfModule mod_ssl.c>
Listen [2001:67c:1388:1001::6]:443
Listen 195.8.117.80:443
</IfModule>
```

so I didn't uncomment the Listen directives in /etc/httpd/conf.d/ssl.conf

**Comment by pde** [comment]
This seems like a recurrence of #1994, though it's possible that the circumstances are different.

@dpocock, did you by any chance have two vhosts in a single configuration file here? Would you be able to post your entire configuration?

**Comment by dpocock** [comment]
This box runs a public demo of WebRTC for the Fedora community, let me know if you want anything else from the config as it is generally meant to be there for sharing.  It is a vanilla install of CentOS7 + EPEL7 with the reSIProcate packages (repro and reTurnServer also use port 443)

I cloned letsencrypt under /opt, last commit 248dc0962e676382740002ae3743e518d7870345

```
# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether a6:ff:d9:19:f9:9e brd ff:ff:ff:ff:ff:ff
    inet 195.8.117.80/27 brd 195.8.117.95 scope global eth0
       valid_lft forever preferred_lft forever
    inet 195.8.117.81/27 brd 195.8.117.95 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 195.8.117.82/27 brd 195.8.117.95 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet6 2001:67c:1388:1001::7/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 2001:67c:1388:1001::6/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::a4ff:d9ff:fe19:f99e/64 scope link 
       valid_lft forever preferred_lft forever

# netstat -nlp | grep 443
tcp        0      0 195.8.117.80:8443       0.0.0.0:*               LISTEN      6654/repro          
tcp        0      0 195.8.117.80:443        0.0.0.0:*               LISTEN      6463/httpd          
tcp        0      0 195.8.117.82:443        0.0.0.0:*               LISTEN      6408/reTurnServer   
tcp6       0      0 2001:67c:1388:1001:8443 :::*                    LISTEN      6654/repro          
tcp6       0      0 2001:67c:1388:1001::443 :::*                    LISTEN      6463/httpd          
tcp6       0      0 2001:67c:1388:1001::443 :::*                    LISTEN      6408/reTurnServer   

```



Here is ```/etc/httpd/conf.d/fedrtc.org.conf```

```
<VirtualHost *:80>
    ServerName fedrtc.org
    DocumentRoot /var/www/fedrtc.org
    Redirect 301 / https://fedrtc.org/
    ErrorLog "logs/fedrtc.org/http_error_log"
    CustomLog "logs/fedrtc.org/http_access_log" combined
</VirtualHost>

<IfModule mod_ssl.c>
<VirtualHost *:443>
    SSLEngine on
    ServerName fedrtc.org
    DocumentRoot /var/www/fedrtc.org
    SSLCertificateFile /etc/letsencrypt/live/fedrtc.org/cert.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/fedrtc.org/privkey.pem
    ErrorLog "logs/fedrtc.org/https_error_log"
    CustomLog "logs/fedrtc.org/https_access_log" combined
    Header always add Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"
    SSLCertificateChainFile /etc/letsencrypt/live/fedrtc.org/chain.pem
</VirtualHost>
</IfModule>

```

**Comment by joohoi** [comment]
First of all, @dpocock thanks for a very detailed report! 

I poked around this, and it's actually not related to CentOS, but the way we use to evaluate if we need to add a Listen statement to configuration. Currently, if no global listen statement for port 443 is found in the configuration, the plugin attempts to add one. This of course will conflict with the one for specific IP already defined in the configuration.

I think we should trust the users ability to resolve the case in this issue, and refrain from adding a global Listen directive to Apache configuration, while possibly printing a line to error log about this issue. This is also relevant for people running something on port 443 on specific IP addresses on the host already. The con in this resolution would be inability to activate SSL on an additional IP not already running SSL on the host, however also this would need some work around it.

I will bring this issue up in tonights client discussion, and will return to it shortly. The fix itself is pretty easy after we figure out what we would like to do.
