### ISSUE TITLE
Docs speak of --quiet for Xenial, but it is not supported there

### ISSUE THREAD

**Issue by piepmatz** [certbot/certbot#3031]
The quick start over at [certbot.eff.org](https://certbot.eff.org/#ubuntuxenial-nginx) recommends `letsencrypt renew --quiet` for automatic renewal on Ubuntu Xenial (and nginx).

The current version of letsencrypt in the Xenial repositories is 0.4.1-1, which does not yet understand `--quiet`.

**Comment by bmw** [comment]
You're right. Thanks for reporting the issue.

We have a separate repo for the Certbot website, so I made an issue there and linked to this one.
