### ISSUE TITLE
Accept domains containing underscores as FQDNs

### ISSUE THREAD

**Issue by eligrey** [certbot/certbot#3036]
I understand that domains containing underscores are a violation of one or more RFC specs, but all major browsers support them, all popular DNS providers support them, and some software needs them for "magic subdomains" that start with a leading underscore.

I'm trying to get a certificate for a domain that's in the format of `_something.example.org`, which some software needs.

When I try to register this domain, I get an error that says "Requested domain \[domain\] is not a FQDN"

**Comment by bmw** [comment]
This restriction is set by the Let's Encrypt CA and they closed this issue as a won't fix on their repo letsencrypt/boulder#1225.
