### ISSUE TITLE
Asking for input despite --noninteractive

### ISSUE THREAD

**Issue by mitar** [certbot/certbot#3039]
I am using [this script](https://github.com/tozd/docker-nginx-proxy/blob/master/letsencrypt/dockergen.sh) to automatically generate certificates for my domains. I have the following command:

```
/letsencrypt/data/letsencrypt/bin/letsencrypt --no-self-upgrade --noninteractive --quiet --agree-tos --email "${LETSENCRYPT_EMAIL}" \
 --config-dir /ssl/letsencrypt certonly --webroot --keep-until-expiring --rsa-key-size 4096 \
 --webroot-map "${LIST_JSON}"
```

As you see, I use `--noninteractive`. But despite this, my automatic process has been stopped by (I see in the log) the following prompt:

```
You have an existing certificate that contains a portion of the domains you requested (ref: /ssl/letsencrypt/renewal/example.com.conf)

It contains these names: example.com

You requested these names for the new certificate: example.com, test.example.com.

Do you want to expand and replace this existing certificate with the new certificate?

(You can set this with the --expand flag)
```

I do not want to expand it the domain, and I would assume that `--noninteractive` should choose the default: not to expand and just do it.

**Comment by bmw** [comment]
So what `--noninteractive` does is ensure the client doesn't hang waiting for user input. It does not automatically answer questions for you, it will error out when it encounters a prompt, telling you how to  specify the answer to that prompt on the command line. This is useful when running the client automatically using something like `cron` so it will not hang forever waiting for user input.

Here, the client didn't know whether you wanted to expand the existing cert or to create an entirely separate one. If you want to expand the existing cert, include `--expand` on the command line. If you want to create a new lineage, use `--duplicate` (although you probably don't want to use this for every renewal, as it will create new directories in `/etc/letsencrypt` on every run).

If I'm incorrect about the issue you're reporting, please let me know, however, I believe this is just a misunderstanding of the purpose of `--noninteractive`.

**Comment by mitar** [comment]
Hm, but why is `test.example.com` and `example.com` domains considered a duplicate?

**Comment by bmw** [comment]
Because they both contain `example.com`. It's an additional certificate lineage containing the same domain name.

**Comment by mitar** [comment]
Moreover, how can I then use it for every run? So that not multiple directories are created.

So I cannot create a cert which is only for `test.example.com`. It has to include `example.com` as well?

**Comment by bmw** [comment]
`${LIST_JSON}` contains both `test.example.com` and `example.com`.

If you want two certificates, each containing a single name, you should run the client after removing the `example.com` entry from  from `${LIST_JSON}`. To renew these certificates, I recommend you look at the [renew subcommand](https://certbot.eff.org/docs/using.html#renewal).

If you want one certificate, each with a single domain name, you should run the client once manually, including `--duplicate` on the command line and removing `--keep-until-expiring` to create the new certificate lineage. After that, you can run the client with your command line above to renew the certificate.

**Comment by mitar** [comment]
`${LIST_JSON}` contains the following:

```
{
  "example.com": "/ssl/webroot/example.com/",
  "test.example.com": "/ssl/webroot/test.example.com/",
}
```

I assumed that this will generate one certificate per JSON entry, the same as if I would go and run it multiple times for every domain. Have I been mistaken in assuming that? So that the above is one certificate per domain. And the following is one certificate for two domains:

```json
{
  "example.com,test.example.com": "/ssl/webroot/example.com/"
}
```

So I would agree that there should be an error if I would to change `"example.com"` to `"example.com,test.example.com"` and run the program.

**Comment by bmw** [comment]
With the exception of `renew`, at most one certificate is obtained on a single client run and both versions of the webroot map posted above have the same effect - you will obtain one certificate containing both domains.

`{"example.com,test.example.com": "/ssl/webroot/example.com/"}` is simply short hand for the previous version. This allows people with multiple domains with different webroots to obtain a single certificate if they so desire.

**Comment by bmw** [comment]
Feel free to ask additional questions if you have them here, on https://community.letsencrypt.org, or the #certbot IRC channel on OFTC, but I think this issue can be closed.

**Comment by mitar** [comment]
> you will obtain one certificate containing both domains.

But they have different webroot directories specified? Because of that I assumed that multiple certificates will be created.

**Comment by bmw** [comment]
Sure. You can have domains using different webroot directories and still obtain a single certificate.

**Comment by mitar** [comment]
Thanks for all the help!
