### ISSUE TITLE
Certificate storage location

### ISSUE THREAD

**Issue by szepeviktor** [certbot/certbot#3045]
Hello!

Actually I am a Debian user. Debian stores all (CA, user etc.) certs in `/etc/ssl`.
I think other distros do the same: http://www.tldp.org/LDP/solrhe/Securing-Optimizing-Linux-RH-Edition-v1.3/chap24sec194.html

Would it be possible for certbot to do it also?

**Comment by bmw** [comment]
ping @hlieberman

**Comment by shr3k** [comment]
:+1: and for ssl-cert group and 640 for private key in Debian

**Comment by bmw** [comment]
I don't think we're going to do this. Different distros have different conventions and trying to write code in Certbot to cater to each of them increases Certbot's complexity for little benefit. If there's a standard, by all means we should try to follow it, but I don't think we're going to make changes like this to conform to the conventions of specific distros.

If someone disagrees, feel free to comment or open a new issue explaining why this would be a beneficial feature to you.
