### ISSUE TITLE
Installation in MAC OS X

### ISSUE THREAD

**Issue by ericaudo** [certbot/certbot#3049]
Hi,

I am creating this issues in order to give you a feedback on my installation experience:

I am a beginner in SSL implementation, so I am following exactly your installation instructions.
I am testing the implementation in my MAC Book Pro - 10.9.5.

I have downloaded/compiled/installed "wget" successfully.
Then I am following your installation instructions at [https://certbot.eff.org/#osx-apache]

Beginning of the extract of my terminal prompt:

MacBook-Pro-de-Eric-3:conf eric$ wget https://dl.eff.org/certbot-auto
--2016-05-22 16:50:22--  https://dl.eff.org/certbot-auto
Resolving dl.eff.org... 173.239.79.196
Connecting to dl.eff.org|173.239.79.196|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 43233 (42K) [text/plain]
Saving to: 'certbot-auto'

100%[============================================================================================================================>] 43,233       251KB/s   in 0.2s   

2016-05-22 16:50:29 (251 KB/s) - 'certbot-auto' saved [43233/43233]

MacBook-Pro-de-Eric-3:conf eric$ chmod a+x certbot-auto
MacBook-Pro-de-Eric-3:conf eric$ ./certbot-auto
WARNING: Mac OS X support is very experimental at present...
if you would like to work on improving it, please ensure you have backups
and then run this script again with the --debug flag!
MacBook-Pro-de-Eric-3:conf eric$ 
MacBook-Pro-de-Eric-3:conf eric$ ./certbot-auto --debug
Bootstrapping dependencies via Mac OS X...
No Homebrew/MacPorts; installing Homebrew...
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
==> The following directories will be made group writable:
/usr/local/.
/usr/local/etc
/usr/local/share/info
==> The following directories will have their owner set to eric:
/usr/local/.
/usr/local/etc
/usr/local/share/info
==> The following directories will have their group set to admin:
/usr/local/.
/usr/local/etc

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/. /usr/local/etc /usr/local/share/info
==> /usr/bin/sudo /usr/sbin/chown eric /usr/local/. /usr/local/etc /usr/local/share/info
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/. /usr/local/etc
==> /usr/bin/sudo /bin/mkdir /Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown eric /Library/Caches/Homebrew
==> Downloading and installing Homebrew...
remote: Counting objects: 487, done.
remote: Compressing objects: 100% (441/441), done.
remote: Total 487 (delta 27), reused 331 (delta 17), pack-reused 0
Receiving objects: 100% (487/487), 771.99 KiB | 471.00 KiB/s, done.
Resolving deltas: 100% (27/27), done.
From https://github.com/Homebrew/brew
- [new branch]      master     -> origin/master
  HEAD is now at 375efe0 Remove LLVM-GCC support. (#252)
  ==> Tapping homebrew/core
  Cloning into '/usr/local/Library/Taps/homebrew/homebrew-core'...
  remote: Counting objects: 3706, done.
  remote: Compressing objects: 100% (3587/3587), done.
  remote: Total 3706 (delta 13), reused 2497 (delta 9), pack-reused 0
  Receiving objects: 100% (3706/3706), 2.87 MiB | 1.29 MiB/s, done.
  Resolving deltas: 100% (13/13), done.
  Checking connectivity... done.
  Tapped 3583 formulae (3,732 files, 8.9M)
  ==> Installation successful!
  ==> Next steps
  Run `brew help` to get started
  Further documentation: https://git.io/brew-docs
  ==> Homebrew has enabled anonymous aggregate user behaviour analytics
  Read the analytics documentation (and how to opt-out) here:
  https://git.io/brew-analytics
  ==> Installing dependencies for augeas: libxml2, readline
  ==> Installing augeas dependency: libxml2
  ==> Downloading https://homebrew.bintray.com/bottles/libxml2-2.9.3.mavericks.bottle.tar.gz
  ######################################################################## 100.0%
  ==> Pouring libxml2-2.9.3.mavericks.bottle.tar.gz
  ==> Caveats
  This formula is keg-only, which means it was not symlinked into /usr/local.

OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

```
LDFLAGS:  -L/usr/local/opt/libxml2/lib
CPPFLAGS: -I/usr/local/opt/libxml2/include
```

==> Summary
נ÷  /usr/local/Cellar/libxml2/2.9.3: 276 files, 10M
==> Installing augeas dependency: readline
==> Downloading https://homebrew.bintray.com/bottles/readline-6.3.8.mavericks.bottle.tar.gz
###### ################################################################## 100.0%

==> Pouring readline-6.3.8.mavericks.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

```
LDFLAGS:  -L/usr/local/opt/readline/lib
CPPFLAGS: -I/usr/local/opt/readline/include
```

==> Summary
נ÷  /usr/local/Cellar/readline/6.3.8: 46 files, 2M
==> Installing augeas
==> Downloading https://homebrew.bintray.com/bottles/augeas-1.4.0.mavericks.bottle.1.tar.gz
###### ################################################################## 100.0%

==> Pouring augeas-1.4.0.mavericks.bottle.1.tar.gz
==> Caveats
Lenses have been installed to:
  /usr/local/share/augeas/lenses/dist
==> Summary
נ÷  /usr/local/Cellar/augeas/1.4.0: 422 files, 3M
==> Downloading https://homebrew.bintray.com/bottles/dialog-1.3-20160209.mavericks.bottle.tar.gz
###### ################################################################## 100.0%

==> Pouring dialog-1.3-20160209.mavericks.bottle.tar.gz
נ÷  /usr/local/Cellar/dialog/1.3-20160209: 13 files, 843.4K
pip not installed
Installing pip...
Collecting pip
/var/folders/zp/xklt2b5j46zcj847z8qt202c0000gn/T/tmpu3cL4q/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
/var/folders/zp/xklt2b5j46zcj847z8qt202c0000gn/T/tmpu3cL4q/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  Downloading pip-8.1.2-py2.py3-none-any.whl (1.2MB)
    100% |################################| 1.2MB 834kB/s 
Collecting wheel
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
    100% |################################| 71kB 2.9MB/s 
Installing collected packages: pip, wheel
Exception:
Traceback (most recent call last):
  File "/var/folders/zp/xklt2b5j46zcj847z8qt202c0000gn/T/tmpu3cL4q/pip.zip/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/var/folders/zp/xklt2b5j46zcj847z8qt202c0000gn/T/tmpu3cL4q/pip.zip/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/var/folders/zp/xklt2b5j46zcj847z8qt202c0000gn/T/tmpu3cL4q/pip.zip/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/var/folders/zp/xklt2b5j46zcj847z8qt202c0000gn/T/tmpu3cL4q/pip.zip/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/var/folders/zp/xklt2b5j46zcj847z8qt202c0000gn/T/tmpu3cL4q/pip.zip/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/var/folders/zp/xklt2b5j46zcj847z8qt202c0000gn/T/tmpu3cL4q/pip.zip/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/var/folders/zp/xklt2b5j46zcj847z8qt202c0000gn/T/tmpu3cL4q/pip.zip/pip/wheel.py", line 317, in clobber
    ensure_dir(destdir)
  File "/var/folders/zp/xklt2b5j46zcj847z8qt202c0000gn/T/tmpu3cL4q/pip.zip/pip/utils/**init**.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/pip'

End of extract of my terminal prompt.
After analyzing the error (permission denied), i have set the /Library/Python folder writable to every one.
Then I started again the installation:

Beginning of my terminal prompt:

MacBook-Pro-de-Eric-3:conf eric$ su
Password:
sh-3.2# chmod -R a+w /Library/Python
MacBook-Pro-de-Eric-3:conf eric$ ./certbot-auto --debug
Bootstrapping dependencies via Mac OS X...
Using Homebrew to install dependencies...
Warning: augeas-1.4.0 already installed
Warning: dialog-1.3-20160209 already installed
pip not installed
Installing pip...
Collecting pip
/var/folders/zp/xklt2b5j46zcj847z8qt202c0000gn/T/tmpP3YZjX/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
/var/folders/zp/xklt2b5j46zcj847z8qt202c0000gn/T/tmpP3YZjX/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  Using cached pip-8.1.2-py2.py3-none-any.whl
Collecting wheel
  Using cached wheel-0.29.0-py2.py3-none-any.whl
Installing collected packages: pip, wheel
Successfully installed pip-8.1.2 wheel-0.29.0
/var/folders/zp/xklt2b5j46zcj847z8qt202c0000gn/T/tmpP3YZjX/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
virtualenv not installed.
Installing with pip...
Collecting virtualenv
/Library/Python/2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/Library/Python/2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading virtualenv-15.0.1-py2.py3-none-any.whl (1.8MB)
    100% |################################| 1.8MB 668kB/s 
Installing collected packages: virtualenv
Successfully installed virtualenv-15.0.1
Checking for new version...
Creating virtual environment...
Installing Python packages...
Installation succeeded.
Requesting root privileges to run certbot...
   sudo CERTBOT_AUTO=./certbot-auto /Users/eric/.local/share/letsencrypt/bin/letsencrypt --debug
Password:
An unexpected error occurred:
LookupError: unknown encoding: 
Please see the logfile 'certbot.log' for more details.
MacBook-Pro-de-Eric-3:conf eric$ cat certbot.log 
Traceback (most recent call last):
  File "/Users/eric/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/Users/eric/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 663, in main
    setup_logging(config, _cli_log_handler, logfile='letsencrypt.log')
  File "/Users/eric/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 577, in setup_logging
    cli_handler = cli_handler_factory(config, level, fmt)
  File "/Users/eric/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 564, in _cli_log_handler
    handler = log.DialogHandler()
  File "/Users/eric/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/log.py", line 29, in __init__
    self.d = dialog.Dialog() if d is None else d
  File "/Users/eric/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1038, in **init**
    self.backend_version())
  File "/Users/eric/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1817, in backend_version
    use_persistent_args=False)
  File "/Users/eric/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1541, in _perform
    args_file)
  File "/Users/eric/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1502, in _handle_program_exit
    child_output_rfd)
  File "/Users/eric/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1426, in _wait_for_program_termination
    with open(child_output_rfd, "r") as f:
LookupError: unknown encoding: 

End of the extract of my terminal prompt.

I don't unserstand completely the problem (Python version issue, or missing SNI extension to TLS).
As I told you, I opened this issue just for a feedback for you. I hope it may help you to improve the MAC OS X installation.

Regards,

eric.audouin@gmail.com

**Comment by anton44eg** [comment]
Why not just install it with homebrew?

**Comment by bmw** [comment]
We're deprecating and removing macOS support from `certbot-auto`/`letsencrypt-auto` (see #4520). Instead, users should use Homebrew or MacPorts to install Certbot. Instructions for doing this with Homebrew can be found [here](https://certbot.eff.org/#osx-other).

**Comment by ernani** [comment]
@soldierofgood seems like one you own and real and one that can respond to requests, aka, a real working domain name.
