### ISSUE TITLE
Installing with pip3 breaks due to pydialog

### ISSUE THREAD

**Issue by profhase** [certbot/certbot#3050]
## Problem

Trying to install letsencrypt with pip3

```
pip3 install letsencrypt
```

I am constantly getting:

> ...
> 
> Downloading/unpacking python2-pythondialog>=3.2.2rc1 (from certbot->letsencrypt)
>   Downloading python2-pythondialog-3.4.0.tar.gz (1.5MB): 1.5MB downloaded
>   Running setup.py (path:/tmp/pip-build-kucg1yr1/python2-pythondialog/setup.py) egg_info for package python2-pythondialog
>     Traceback (most recent call last):
>       File "<string>", line 17, in <module>
>       File "/tmp/pip-build-kucg1yr1/python2-pythondialog/setup.py", line 32, in <module>
>         from dialog import **version** as VERSION
>       File "/tmp/pip-build-kucg1yr1/python2-pythondialog/dialog.py", line 264
>         except OSError, e:
>                       ^
>     SyntaxError: invalid syntax
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
> 
>   File "<string>", line 17, in <module>
> 
>   File "/tmp/pip-build-kucg1yr1/python2-pythondialog/setup.py", line 32, in <module>
> 
> ```
> from dialog import __version__ as VERSION
> ```
> 
>   File "/tmp/pip-build-kucg1yr1/python2-pythondialog/dialog.py", line 264
> 
> ```
> except OSError, e:
> ```

(Which seems that there is a false dependency on python2-pythondialog).
## Workaround

use pip2

**Comment by bmw** [comment]
Yes, the client is currently not Python 3 compatible as stated [here](https://github.com/certbot/certbot#system-requirements). Perhaps we should make this requirement more prominent or provide better error messages when trying to install with Python 3?

**Comment by profhase** [comment]
Maybe something like:
    import sys

    if sys.version_info.major == 3:
        sys.stderr.write("Python 3 is currently not supported, exiting... \n")
        sys.exit(1)

in `setup.py`?

**Comment by eirnym** [comment]
@bmw CryptoBot should use pythondialog for Python3, and python2-pythondialog for Python2. Almost all code is python3-compatible.

**Comment by bmw** [comment]
While we're still not quite Python 3 compatible (although we are very close), we have removed `dialog` as a dependency on this project so I'm closing this issue.
