### ISSUE TITLE
RequirementParseError when using tls-sni-01 challenge

### ISSUE THREAD

**Issue by Poorchop** [certbot/certbot#3078]
System: Fedora 23

One of my servers is behind an ISP that blocks port 80 but not port 443. I found some threads that suggest workarounds so that I can still obtain a certificate, like [this one](https://community.letsencrypt.org/t/cant-host-anything-on-port-80/5250/4). However, when I enter the following:

```
certbot certonly --standalone --standalone-supported-challenges tls-sni-01 --domains example.com,www.example.com
```

I get an error with the traceback:

```pytb
Traceback (most recent call last):
  File "/bin/certbot", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 847, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2602, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2597, in _dep_map
    dm.setdefault(extra,[]).extend(parse_requirements(reqs))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2930, in parse_requirements
    "version spec")
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2895, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
pkg_resources.RequirementParseError: Expected version spec in 8 CY:3V▒▒▒ at  CY:3V▒▒▒
```

Those are the actual glyphs that I saw in my terminal and I don't know what they mean. I also did not generate a self-signed certificate for the domain, and I'm not sure if that could be causing issues.

**Comment by bmw** [comment]
@Poorchop, how did you install `certbot`?

**Comment by Poorchop** [comment]
`dnf install certbot`

**Comment by bmw** [comment]
Hm. I'm struggling to reproduce this with the Fedora 23 docker image.

Any thoughts @hogarthj? The program is crashing when trying to import `pkg_resources` to load the entry point to start `certbot`.

**Comment by Poorchop** [comment]
I was able to get certificates on my CentOS VPS without any issue. In that case, I download certbot-auto from https://dl.eff.org/certbot-auto and I had my certificates in seconds. The CentOS VPS isn't behind a firewall though so `./certbot-auto certonly --webroot -w /var/www/example -d example.com` worked without any issues.

I tried the same thing on Fedora initially even though I knew port 80 was blocked and everything ran fine apart from the fact that my server was not reachable. That's why I think it's only a problem with the tls challenge. I can try the same thing on my VPS and just block port 80 in my software firewall if you think it's worth a shot. I'm just not sure if it's a good idea to request a certificate that I won't use.

Also I'm not sure if this is necessary info but I'm using nginx. I stopped the web server before using the `--standalone` method above.

**Comment by bmw** [comment]
@Poorchop the problem causing the traceback you posted above occurred before `certbot` even really started. It was running generic code generated by `setuptools` in order to actually start `certbot`.

If you run `certbot` with different arguments, do you see the same problem? Also, while OS packages should certainly be preferred, do you have the problem using `certbot-auto` on your Fedora machine?

**Comment by Poorchop** [comment]
@bmw I gave it a try with `certbot-auto` and it worked perfectly. It pulled in 29 additional dependencies, which was a surprise because I thought `dnf install certbot` had already pulled in everything that it needed. Thanks for the suggestion.

If there's any additional information that I can provide in order to help figure out what went wrong my initial attempt, I'd be happy to help.

**Comment by hogarthj** [comment]
Did you definitely have your system updated fully?

I used the --webroot option when testing on my own server...

I'll try and do a test with --standalone a little later

**Comment by Poorchop** [comment]
Yes, I'm positive that I updated my system fully before running certbot. I think it works fine with the webroot option - the problem seems to be specifically with the tls challenge flag, or possibly the standalone a flag.

**Comment by bmw** [comment]
@Poorchop, can you successfully use the `certbot` command (not `certbot-auto`) using any other flags? For example, does `certbot --help` work?

Like I said before, the program is crashing before `certbot` ever really starts so the flags seem like they should be irrelevant.

**Comment by Poorchop** [comment]
>For example, does `certbot --help` work?

Nope. It generates the same exact error message so you're definitely right about the program crashing before `certbot` starts.

However, I just reinstalled cerbot and all of its dependencies, and `certbot --help` worked without any issues. Since certbot worked initially and works now after resintalling, I'm guessing one of the packages got messed up at some point but clearly the issue is only on my end. I don't have the means for testing it right now but I'm sure the tls challenge will work now if I were to try it. Sorry for all of the confusion and thanks for your help and patience.
