### ISSUE TITLE
Add a --user flag for certbot to run as non-privileged

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#3079]
Certbot currently needs root for these reasons:

All:
- Write to /var/log/letsencrypt/
- (Create and) write to /etc/letsencrypt/
- Write to /var/lib/letsencrypt

Apache:
- Write to /etc/apache2
- Run `apachectl`

Standalone:
- Bind to port 443

Manual:
- None

Lots of third-party Let's Encrypt clients were written because people want to use something like manual mode without root. Right now, certbot lets you do that, but it's complicated. You have to set `--work-dir`, `--conf-dir`, and `--log-dir`. I propose that we add a `--user` flag, or `--no-root` or `--unprivileged` or similar. That would default those three log files to point to `$HOME/certbot/work`, `$HOME/certbot/`, and `$HOME/certbot/logs`, respectively. This would also allow standalone mode to work as non-root, so long as the user was granted the privilege to bind 443.

Slight disadvantage: The keys wind up owned by non-root. But I think that's fine.

**Comment by jsha** [comment]
Another possible flag name: `--nosudo`, in honor of diafygi/letsencrypt-nosudo.

**Comment by pde** [comment]
Related: #2964

**Comment by bmw** [comment]
@jsha, you and I also talked out of band about providing a flag like `--dir-prefix` which would cause `certbot` to create the config, work, and logs dir under the directory passed in `--dir-prefix`. Do you prefer `--user`/`--nosudo` to this? Do you want both?

**Comment by jsha** [comment]
One or the other is better, not both. I've gone back and forth about which approach I prefer, and I'm definitely interested in your thoughts. I think `--prefix` is a flag that describes what it *does*, which is appealing to us as developers. I think `--user` (or `--nosudo`) is a flag that describe what the user wants to accomplish, which probably makes easier to understand and more appealing for end-users. So right now I'm leaning towards that.

**Comment by bmw** [comment]
I think I agree with you that `--nosudo` is better for the user. It's a little less flexible than `--prefix`, however, all of this simply avoids users having to set `--config-dir`, `--work-dir`, and `--logs-dir` manually so people who want the extra control have it either way.

We'll have to figure out the best place for `--nosudo` though. #843 proposed to permanently move Certbot directories to those owned by the user and suggested following XDG Base Directory Spec.

**Comment by bmw** [comment]
Related: #973

**Comment by bmw** [comment]
I still personally want us to do something here. I don't have strong opinions on the exact design, but I think we can and should make it significantly easier to run Certbot without root privileges.

**Comment by adferrand** [comment]
At this occasion I would remind the proposition I made here https://github.com/certbot/certbot/issues/6785, to assert about on the main blocker about handling properly a non privileged execution of Certbot, that are the locks.

**Comment by bmw** [comment]
I don't know if we'll ever realistically get to this.

With that said, I think it'd be nice to do in the long term and I think there is some valuable discussion here so begone stale bot!
