### ISSUE TITLE
Phython returned non-zero exit status 2

### ISSUE THREAD

**Issue by AndrinS** [certbot/certbot#3080]
When trying:
`./certbot-auto certonly --standalone --email admin@mydomain.com --agree-tos -d cloud.mydomain.com`

```
.
.
.
Checking for new version...
Creating virtual environment...
Installing Python packages...
Traceback (most recent call last):
  File "/tmp/tmp.lZwwFi6TvF/pipstrap.py", line 146, in <module>
    exit(main())
  File "/tmp/tmp.lZwwFi6TvF/pipstrap.py", line 133, in main
    shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'pip install --no-index --no-deps -U /tmp/pipstrap-xcfZLh/pip-8.0.3.tar.gz /tmp/pipstrap-xcfZLh/setuptools-20.2.2.tar.gz /tmp/pipstrap-xcfZLh/wheel-0.29.0.tar.gz' returned non-zero exit status 2
```

**Comment by pde** [comment]
@erikrose any thoughts on this?

**Comment by AndrinS** [comment]
*bump*

**Comment by AndrinS** [comment]
ok. I just did

```
wget https://pypi.python.org/packages/source/p/pip/pip-1.5.6.tar.gz
tar -vzxf pip-1.5.6.tar.gz
cd pip-1.5.6
python setup.py install

```
now I get

```
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 2339, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 825, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 993, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 961, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 903, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /root/.local/share/letsencrypt/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1


```

**Comment by n8henrie** [comment]
Same error? https://github.com/certbot/certbot/issues/2948

**Comment by AndrinS** [comment]
yes

**Comment by AndrinS** [comment]
Funny.. im back to exit "non-zero exit status 2".

**Comment by AndrinS** [comment]
Here the newest error:


```
.
.
.
Installing Python packages...
Traceback (most recent call last):
  File "/tmp/tmp.BiqJ2B2a9k/pipstrap.py", line 146, in <module>
    exit(main())
  File "/tmp/tmp.BiqJ2B2a9k/pipstrap.py", line 133, in main
    shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'pip install --no-index --no-deps -U /tmp/pipstrap-7tVjCC/pip-8.0.3.tar.gz /tmp/pipstrap-7tVjCC/setuptools-20.2.2.tar.gz /tmp/pipstrap-7tVjCC/wheel-0.29.0.tar.gz' returned non-zero exit status 2
```

**Comment by n8henrie** [comment]
Coming back from the other thread -- that's a pretty old pip version.

Can you upgrade it to a newer build and try again?

```
# May give you an error about permissions
pip install --upgrade pip

# If you have an error with the above
# May give you an error about the `--user` flag,
# which may not be available in that version
pip install --upgrade --user pip

# Try this if both of the above give you errors
sudo pip install --upgrade pip
```

**Comment by AndrinS** [comment]
```
$ pip install --upgrade pip
Downloading/unpacking pip from https://pypi.python.org/packages/9c/32/004ce0852e0a127f07f358b715015763273799bd798956fa930814b60f39/pip-8.1.2-py2.py3-none-any.whl#md5=0570520434c5b600d89ec95393b2650b
  Downloading pip-8.1.2-py2.py3-none-any.whl (1.2MB): 1.2MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.6
    Uninstalling pip:
      Successfully uninstalled pip
Successfully installed pip
Cleaning up...

$ python -m pip --version
pip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)

```
still the same error

**Comment by n8henrie** [comment]
Did you delete the `venv` before trying again (after updating pip)?

I've [updated my reply in the other thread](https://github.com/certbot/certbot/issues/2948#issuecomment-223311954) with a little more detailed instruction.

**Comment by AndrinS** [comment]
I don't use venv. Still exiting with code 2.

Here are my recent attempts.

```
rm -r certbot/
rm -r letsencrypt/
rm -r .~/local/share/letsencrypt/
rm -r /tmp/*
git clone https://github.com/letsencrypt/letsencrypt
cd letsencrypt/
./letsencrypt-auto certonly --standalone --email hostmaster@example.net --agree-tos -d cloud.example.net
```

Whole answer [here](http://pastebin.com/LHHirTKD) (Pastebin)

**Comment by n8henrie** [comment]
> I don't use vent.

Certbot does -- see line 84 of your pastebin.

> `rm -r .~/local/share/letsencrypt/`

That should be `rm -r ~/.local/share/letsencrypt/`. Was that a typo?

**Comment by AndrinS** [comment]
I just wrote the whole command new here. I did remove it in ~/.local though. So how do I delete venv?

**Comment by n8henrie** [comment]
That's how you do what I was asking you to do -- I just didn't know if you had done it correctly due to the typo.

Do you have multiple python2.7s installed? 

[Here](https://github.com/certbot/certbot/issues/3080#issuecomment-223613780) I see `/usr/lib/python2.7`, whereas I [here](https://github.com/certbot/certbot/issues/3080#issuecomment-223615796) I see `/usr/local/lib/python2.7`. I wonder if you updated `pip` in the wrong python.

What's the output of these?

- `command -v pip`
- `command -v python`

Is the output of the following commands all the same?

- `pip --version`
- `python -m pip --version`
- `/usr/bin/python -m pip --version`

**Comment by AndrinS** [comment]
command -v pip
`/usr/local/bin/pip`

command -v python
`/usr/bin/python`


```
# pip --version
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==1.5.6' distribution was not found and is required by the application

# python -m pip --version
pip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)

# /usr/bin/python -m pip --version
pip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python
2.7)



```
# /usr/bin/python -m pip install --upgrade pip
The directory '/root/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/root/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

The never ending story..

**Comment by n8henrie** [comment]
Why are you running these as root?

What's the output of `sudo find / -type f -path '*/bin/python2.7'` ?

**Comment by AndrinS** [comment]
Yes I, so far I runned every command as root.

```
# find / -type f -path '*/bin/python2.7'
/usr/bin/python2.7
/root/.local/share/letsencrypt/bin/python2.7
```

**Comment by n8henrie** [comment]
Have you tried *not* running as root? It will ask you to elevate permissions as needed.

**Comment by AndrinS** [comment]
Which command in specific?

**Comment by AndrinS** [comment]
Ok, I think there's another problem -.-

```
root@srv /home/user1/downloads # chown root:root /usr/bin/sudo && chmod 4755 /usr/bin/sudo
root@srv /home/user1/downloads # exit
exit
user1@srv:~/downloads$ ./certbot-auto
Bootstrapping dependencies for Debian-based OSes...
sudo: error in /etc/sudo.conf, line 0 while loading plugin `sudoers_policy'
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
apt-get update hit problems but continuing anyway...
sudo: error in /etc/sudo.conf, line 0 while loading plugin `sudoers_policy'
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
```

I think it's best if I reinstall.

**Comment by horsley** [comment]
upgrade to pip 8.1.2 fix that

**Comment by malsony** [comment]
@horsley it works after updating `pip`, thanks!

**Comment by banrieen** [comment]
On openSUSE ,I only remove the python ,python3 and re-install python,python3; the problem has been fixed.
sudo zypper rm python
sudo zypper rm python3
then:
sudo zypper install --oldpackage python
sudo zypper install --oldpackage python3
After that:
 sudo python get-pip.py 
Collecting pip
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 572kB/s 
Collecting setuptools
  Downloading setuptools-36.2.7-py2.py3-none-any.whl (477kB)
    100% |████████████████████████████████| 481kB 733kB/s 
Collecting wheel
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 962kB/s 
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-9.0.1 setuptools-36.2.7 wheel-0.29.0

**Comment by schoen** [comment]
It appears from the discussions that this is a symptom of having out-of-date Python tools installed on the system (such as a very old version of pip). Ideally, `certbot-auto` should diagnose this problem better and explain the exact reason and steps to remedy it. I'll suggest tracking that as a new issue, though (#6552).
