### ISSUE TITLE
'certbot-auto certonly' fails in an Emacs shell window

### ISSUE THREAD

**Issue by janssen** [certbot/certbot#3083]
I just see a bunch of spaces, no prompts.  This is on Ubuntu 15.04.

**Comment by pde** [comment]
Hrm.  Adding `-n` or `--non-interactive` will probably work around by disabling the (Y/N) prompts. If not, try running with `-v` to see if you learn anything more?

**Comment by pde** [comment]
But we should work out why you're not seeing the prompts in that window...

**Comment by ian-kelling** [comment]
I just ran into this. To be more specific, it printed:

Requesting root privileges to run certbot...
  /home/ian/.local/share/letsencrypt/bin/letsencrypt --apache

Then it printed 11644 spaces on a single line. I was confused, pressed enter or something, got the same thing, pressed enter, then got
"Please specify --domains, or --installer that will help in domain names autodiscovery"

**Comment by bmw** [comment]
By default, Certbot tries to use an Ncurses dialog window to interact with the user. I can see this not working in an emacs shell window.

As a work around, if you add `-t` or `--text` to the command line, does it allow you to use the client?

**Comment by janssen** [comment]
Now I can't get it to work at all; looks like it tried to update itself, and pip somehow failed:

    subprocess.CalledProcessError: Command 'pip install --no-index --no-deps -U /tmp/pipstrap-mC4_lI/pip-8.0.3.tar.gz /tmp/pipstrap-mC4_lI/setuptools-20.2.2.tar.gz /tmp/pipstrap-mC4_lI/wheel-0.29.0.tar.gz' returned non-zero exit status 1

**Comment by janssen** [comment]
Downloaded a new copy and tried that.  Fail.  This is what I'm seeing:

````
Upgrading certbot-auto 0.7.0 to 0.8.0...
Replacing certbot-auto...
Creating virtual environment...
Installing Python packages...
Traceback (most recent call last):
  File "/tmp/tmp.rvAG5SIKlA/pipstrap.py", line 146, in <module>
    exit(main())
  File "/tmp/tmp.rvAG5SIKlA/pipstrap.py", line 133, in main
    shell=True)
  File "/opt/CBMX/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'pip install --no-index --no-deps -U /tmp/pipstrap-xhaURS/pip-8.0.3.tar.gz /tmp/pipstrap-xhaURS/setuptools-20.2.2.tar.gz /tmp/pipstrap-xhaURS/wheel-0.29.0.tar.gz' returned non-zero exit status 1
wjanssen@archie:/tmp$ 
```

**Comment by janssen** [comment]
Completely hosed.  How do I install an older version and prevent it from updating itself?

**Comment by ohemorange** [comment]
`certbot-auto` is no longer the supported method for Ubuntu; see https://certbot.eff.org/ for more info.
