### ISSUE TITLE
Failed authorization procedure. www..com (http-01): urn:acme:error:unauthorized 

### ISSUE THREAD

**Issue by Leo-G** [certbot/certbot#3087]
```
  Failed authorization procedure. www..com (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://www.techarena51.com/.well-known/acme-challenge/rbOOhfADe27wCVJnrPrBve5cyR0JTLurRz7-1Fdq4L4 [23.254.97.180]: 404, beautygyaan.com (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://mysite.com/.well-known/acme-challenge/dKH14-pgyA8lfYJ3pVYQWIghOX5q6vYjNnI0LQjWFyo: "<html>
  <head><title>404 Not Found</title></head>
  <body bgcolor="white">
  <center><h1>404 Not Found</h1></center>
  <hr><center>"
```

I see that the .well-known folder exists but there are no files or folders inside it. I am not sure why the files are not being created, I even tried running the command as root.

Any help will be apreciated

**Comment by bmw** [comment]
I'm assuming you're using the webroot plugin.

If so, Certbot should create the necessary files and folders, but it removes them before exiting which is why you don't see anything there.

If you create an `acme-challenge` directory under `.well-known` with a text file inside if it, can you access it through your browser? Some webservers will not server files in hidden directories (`.well-known`) by default.

**Comment by Leo-G** [comment]
@bmw Thanks will check and get back to you

**Comment by ksaylor11** [comment]
This appears to still be an issue. I am able access files through the browser. What additional information would be helpful?

**Comment by ksaylor11** [comment]
I can also verify that its not the same issue as [#2044](https://github.com/certbot/certbot/issues/2044)

**Comment by merwok** [comment]
Lost a bit of time today with this, even though I deployed certs with success on a few servers previously.

I suspended the letsencrypt process after it created the challenge file and was able to see it in my browser.

In the end I stopped my server, ran in standalone mode and that one worked.

**Comment by adferrand** [comment]
This issue has not been updated for a long time. So I assume it is solved, or not relevant anymore. If not, do not hesitate to reopen an issue with updated info about its context.
