### ISSUE TITLE
Cert without Common Name

### ISSUE THREAD

**Issue by xkpd3** [certbot/certbot#3088]
Hello,
Is it possible to create a certificate without common name? Or set a fee text as common name?

I have many domains listed as subject alternative names. If the common name has to be a domain, it looks very confusing to users, as the common name is often displayed first when the user checks the certificate details.

How can I keep the common name empty?

Best Regards,
Stefan

**Comment by bmw** [comment]
Unfortunately, this is not currently supported by `boulder`, the server side of Let's Encrypt. While out of the scope of this repo, perhaps we can make an issue at https://github.com/letsencrypt/boulder.

@jsha: Should we make an issue/are there any plans to support this in the future?

**Comment by jsha** [comment]
We will eventually issue certs without common name in Boulder. I think there's no need for special handling on the client side at present. It's always possible to manually generate a CSR.

**Comment by bmw** [comment]
I meant should we make an issue on the boulder repo to track the issue of creating certificates without a common name.
