### ISSUE TITLE
Rename letsencypt package to certbot

### ISSUE THREAD

**Issue by danger89** [certbot/certbot#3096]
Hi,

Following the guide on:
https://certbot.eff.org/#debianjessie-nginx

They say I need to install `letsencrypt` package:
`sudo apt-get install letsencrypt -t jessie-backports`

This is not right any-more, and gives a lot of unmet dependency problems. The guide should be updated saying you should install the `certbot` package instead. Meaning the following **DOES WORK**:
`sudo apt-get install certbot -t jessie-backports`

Kind regards,
Melroy van den Berg

**Comment by MrBrax** [comment]
Thanks, was really confused when trying to install and it not working.

**Comment by danger89** [comment]
I was too ;)

**Comment by chriscroome** [comment]
There is a ticket here for this https://github.com/certbot/website/issues/120

**Comment by bmw** [comment]
Sorry for the trouble. @chriscroome, is correct though the issue for this is certbot/website#120, so I'm closing this issue in favor of the one against the website repo.
