### ISSUE TITLE
certbot-auto renew --dryrun it doesn't works with apache

### ISSUE THREAD

**Issue by rkmax** [certbot/certbot#3097]
I made the cert with the following command. 

    ./certbot-auto certonly --webroot /var/www/www.example.com -d www.example.com -d example.com

the DNS are correct. then I just try the renew --dry-run

    ./certbot-auto renew --dry-run

 always I got

    2016-05-30 15:05:17,853:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/www.example.com.conf produced an unexpected error: Failed authorization procedure. example.com (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Could not connect to http://example.com/.well-known/acme-challenge/78q6nKlt-wFcYnxxtr8r-hdZU8OrDIzGwItnQHPPeqE, www.example.com (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Could not connect to http://www.example.com/.well-known/acme-challenge/3yBxHBqoX34VUeaja8MVWoR81iQss_YWg-vwmIbWKlY. Skipping.

the certs was correctly generate with the setup that I have the root of each domain it's accesible by the script to place the /.well-known/acme-challenge/hash file

I've tried with standalone flag and it works

My webserver is running on a Ubuntu 12.04 with Apache 2.4.10 and my virtualhost setup is the following

```xml
<VirtualHost *:80>
    ServerName example.com
    ServerAlias www.example.com        
    DocumentRoot "/var/www/www.example.com"
    Redirect permanent / https://www.example.com
</VirtualHost>

<VirtualHost *:443>
    ServerName example.com
    ServerAlias www.example.com

    DocumentRoot "/var/www/www.example.com"

    <Directory /var/www/www.example.com>
        DirectoryIndex index.php
        Options +Indexes +FollowSymLinks +Includes
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/example.com-error.log
    CustomLog ${APACHE_LOG_DIR}/example.com-access.log combined

    SSLEngine on
    SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem
    SSLCertificateFile /etc/letsencrypt/live/example.com/fullchain.pem
</VirtualHost>
```

today (30 may 2016) I've tested with the version 0.7.0

**Comment by bmw** [comment]
Thanks for the detailed bug report @rkmax.

Do you know if your Apache is configured not to serve files in hidden directories (e.g. `.well-known`)? You can test this by hand by creating the `/var/www/www.example.com/.well-known` directory and placing a text file inside. Can you then access this file in your browser?

**Comment by rkmax** [comment]
@bmw I've tested it and  Apache is serving the .well-known directory and files inside

**Comment by bmw** [comment]
Have you ever successfully used `webroot` for this domain?

It seems unlikely that `--dry-run` is the problem. I think it's a more general problem with `renew`/webroot/Apache.

**Comment by rkmax** [comment]
Yes, I create the cert using

    certbot-auto certonly 

and choosing that same path

**Comment by bmw** [comment]
You can check the configuration file in `/etc/letsencrypt/renewal` to make sure all the values there look correct. For example, has your webroot changed since the configuration file was created?

Also, depending on how far you are away from hitting the server [rate limits](https://community.letsencrypt.org/t/rate-limits-for-lets-encrypt/6769) you could try a couple things:

1. You could try renewing without `--dry-run` by using `certbot-auto renew --force-renewal`.
2. You can try the command you used to obtain the cert with `certonly`.

If either of these work, try running `certbot-auto renew --dry-run` and see if you still have the problem.

**Comment by rkmax** [comment]
@bmw I confirmed that the problem is the redirection I just commented the line

    Redirect permanent / https://www.example.com

and works fine. this also affect the --force-renewal and run the command without the --dry-run option

**Comment by bmw** [comment]
Oh! I'm sorry @rkmax, I totally missed the `Redirect` directive before. I believe you need a trailing slash on `https://www.example.com`. Testing on one of my servers, without the trailing slash, I get redirected to `https://www.example.com.well-known/acme-challenge/<hash>`

**Comment by rkmax** [comment]
Thanks a lot @bmw the trailing hash was the problem. now I can setup my crontab
