### ISSUE TITLE
python-acme FTBFS [test_del (acme.client_test.ClientNetworkTest)]

### ISSUE THREAD

**Issue by hlieberman** [certbot/certbot#3098]
Hello!

Certbot's python-acme, v. 0.7.0 is failing to build from source both in Debian sid and Fedora Rawhide.

The test failure is in the ClientNetworkTest.  Partial error follows; full log attached.
```
======================================================================
ERROR: test_del (acme.client_test.ClientNetworkTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/acme/client_test.py", line 575, in test_del
    sess.close.assert_called_once()
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 721, in __getattr__
    raise AttributeError(name)
AttributeError: assert_called_once

----------------------------------------------------------------------
Ran 334 tests in 5.950s

FAILED (errors=1)
Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method ClientNetwork.__del__ of <acme.client.ClientNetwork object at 0x7f4c082da490>> ignored
```
[python-acme_0.7.0-1_amd64-20160529-2045.build.txt](https://github.com/certbot/certbot/files/290325/python-acme_0.7.0-1_amd64-20160529-2045.build.txt)

**Comment by hlieberman** [comment]
CC: @nbebout

**Comment by kuba** [comment]
looks like #2855, cc @jsha

**Comment by jsha** [comment]
I believe what's happening is that, even though we call `del` on the `ClientNetwork` object in the test, for whatever reason, that is not calling `__del__`, so the `close` attribute on the MagicMock isn't created. Not sure why that would be different on sid and rawhide, though, vs trusty where we run our Travis builds. Is there anything unusual in those distributions with regards to Python's handling of `__del__`?

```
class ClientNetwork(object):  # pylint: disable=too-many-instance-attributes
    ...
    def __del__(self):
        self.session.close()
```

```
test_del(self):
        sess = mock.MagicMock()
        self.net.session = sess
        del self.net
        sess.close.assert_called_once()
```

**Comment by bmw** [comment]
The problem here is that `assert_called_once` isn't a valid assertion. There's no method on of a `MagicMock` called `assert_called_once`.

When we run our tests, we run with the latest version of `mock` (due to `pip`s preference for preferring the latest version of a package available). In `mock` 2.0+, `sess.close.assert_called_once()` just becomes another mocked out call.

In previous versions of `mock`, however, it looks for a method with that name, doesn't find one, and raises an `AttributeError`.

**Comment by bmw** [comment]
Just wanted to clarify, I was a bit wrong here. There is an `assert_called_once` method in new versions of `mock` which I missed in researching this issue. Regardless, #3100 resolved the problem.
