### ISSUE TITLE
256bit ECC certificate by default?

### ISSUE THREAD

**Issue by JimmyRittenborg** [certbot/certbot#31]
In my opinion it should install a prime256v1 ecc certificate by default, for pure performance benefits - I'm just wondering if that's going to be the case? :)

This is a very important and great initiative by the way! Thanks :+1:

**Comment by JimmyRittenborg** [comment]
Has support for these safer and way smaller Elliptic Curve certificates landed ?

**Comment by JimmyRittenborg** [comment]
Or does https://github.com/letsencrypt/letsencrypt/wiki/Ciphersuite-guidance says it currently won't be supported due to lack of support in various UA's ?

**Comment by JimmyRittenborg** [comment]
On the other hand, it looks like support for ECC certificates indeed is planed in 2016 :heart_eyes: 
https://community.letsencrypt.org/t/elliptic-curve-cryptography-ecc-support/34

**Comment by hlx98007** [comment]
It is 2018 and LE has EC support, are there any plans for certbot to support EC certs?

**Comment by bmw** [comment]
@hlx98007 this is being tracked at #2163.

**Comment by hlx98007** [comment]
@bmw Thanks!
