### ISSUE TITLE
certbot-auto --apache Doesn't Detect Additional Virtual Domains In Separate Files

### ISSUE THREAD

**Issue by ScottPedigo** [certbot/certbot#3103]
I previously used _./letsencrypt-auto --apache_ and it detected my virtual domains. I had one cert for the primary virtual domain which contained aliases for the other virtual domains.

When I got an e-mail that the cert was expiring, I tried to renew using the same command. It was suggested to install and use _certbot_ instead.

_certbot-auto --apache_ only listed the primary virtual domain. I found a hint after searching for the issue that it would work if the virtual domains were in separate files. However, mine already were in separate files.

I tried specifying the domains in combination with the _--apache_ parameter after seeing that in an example in the documentation:
_certbot-auto --apache -d www.domain1.com -d www.domain2.com -d www.domain3.com_
but that failed with an error. I still have the log file. The end of the log entry contained
`MissingNonce: Server POST response did not include a replay nonce, headers: {'Content-Length': '1488', 'Expires': 'Wed, 01 Jun 2016 12:12:33 GMT', 'Server': 'nginx', 'Connection': 'close', 'ETag': '"55f255cc-5d0"', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 01 Jun 2016 12:12:33 GMT', 'Content-Type': 'text/html'}`

I then tried without the _--apache_ parameter and it worked:
_certbot-auto -d www.domain1.com -d www.domain2.com -d www.domain3.com_

**Comment by pde** [comment]
Can you post a copy of your apache configuration?

**Comment by pde** [comment]
I've never seen that `MissingNonce` error before, so flagging it for the boulder team.

**Comment by pde** [comment]
Answer from the boulder team: the `MissingNonce` problem is likely a serverside availability issue.  So you probably hit two bugs.  This command should definitely work under normal serverside circumstances:

`certbot-auto --apache -d www.domain1.com -d www.domain2.com -d www.domain3.com`

But the fact that we were failing to find all your domains automatically is a bug that we should investigate, but will need your config files to do so.

(Aside: you can also do `certbot-auto renew` if you have existing certificates you'd like to renew. It also takes options like `--dry-run` for testing and `--quiet` for use in cron scripts.)

**Comment by ScottPedigo** [comment]
My Apache configuration, file structure:
/etc/apache2/
  -rw-r--r--   root root  apache2.conf
  drwxr-xr-x   root root  sites-available/
    -rw-r--r--  root root . . . domain1.conf
    -rw-r--r--  root root . . . domain1-ssl.conf
    -rw-r--r--  root root . . . domain2.conf
    -rw-r--r--  root root . . . domain2-le-ssl.conf
    -rw-r--r--  root root . . . domain3.conf
    -rw-r--r--  root root . . . domain3-le-ssl.conf
  drwxr-xr-x   root root  sites-enabled/
    lrwxrwxrwx  root root   000-domain1-ssl.conf -> ../sites-available/domain1-ssl.conf
    lrwxrwxrwx  root root   001-domain1.conf -> ../sites-available/domain1.conf
    lrwxrwxrwx  root root   002-domain2.conf -> ../sites-available/domain2.conf
    lrwxrwxrwx  root root   003-domain3.conf -> ../sites-available/domain3.conf
    lrwxrwxrwx  root root   102-domain2-ssl.conf -> ../sites-available/domain2-le-ssl.conf
    lrwxrwxrwx  root root   103-domain3-ssl.conf -> ../sites-available/domain3-le-ssl.conf
  drwxr-xr-x   root root  ssl/
/etc/letsencrypt
  . . .

**Comment by ScottPedigo** [comment]
`<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName domain1.com

        ServerAdmin me@somemailaddress.com

        Redirect '/twiki/bin/view/xxx' 'http://www.domain2.org/twiki/bin/view/xxx'

        DocumentRoot /home/domain1admin/domain1.com/html
        <Directory />
                Options FollowSymLinks
                AllowOverride None
        </Directory>
        <Directory /home/domain1admin/domain1.com/html/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride None
                Require all granted
        </Directory>

        ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
        <Directory "/usr/lib/cgi-bin">
                AllowOverride None
                Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
                Require all granted
        </Directory>

        LogLevel warn

        CustomLog ${APACHE_LOG_DIR}/access.log combined
        ErrorLog ${APACHE_LOG_DIR}/error.log

        Alias /doc/ "/usr/share/doc/"
        <Directory "/usr/share/doc/">
                Options Indexes MultiViews FollowSymLinks
                AllowOverride None
                Require host 127.0.0.0/255.0.0.0 ::1/128
        </Directory>

        #   SSL Engine Switch:
        SSLEngine on

        SSLCertificateFile    /etc/letsencrypt/live/www.rangelaw.com/cert.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/www.rangelaw.com/privkey.pem

        #   SSL Engine Options:
        <FilesMatch "\.(cgi|shtml|phtml|php)$">
                SSLOptions +StdEnvVars
        </FilesMatch>
        <Directory /usr/lib/cgi-bin>
                SSLOptions +StdEnvVars
        </Directory>

        BrowserMatch "MSIE [2-6]" \
                nokeepalive ssl-unclean-shutdown \
                downgrade-1.0 force-response-1.0
        # MSIE 7 and newer should be able to use keepalive
        BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown

ServerAlias www.domain1.com
ServerAlias www.domain2.org
ServerAlias www.domain3.net
SSLCertificateChainFile /etc/letsencrypt/live/www.domain1.com/chain.pem
</VirtualHost>
</IfModule>
`

**Comment by ScottPedigo** [comment]
# domain1.conf

&lt;virtualhost *:80&gt;
ServerName domain1.com
ServerAlias www.domain1.com ftp.domain1.com
ServerAdmin me@someemailadress.com
DocumentRoot /home/domain1admin/domain1.com/html/

&lt;directory /home/domain1admin/domain1.com/html/&gt;
  Options Indexes FollowSymLinks Includes
  AllowOverride none
  Require all granted
&lt;/directory&gt;

ProxyPass '/servlets/' 'http://www.domain1.com:8180/servlets/'
ProxyPassReverse '/servlets/' 'http://www.domain1.com:8180/servlets/'

ScriptAlias '/cgi-bin/' '/home/domain1ladmin/domain1.com/cgi-bin/'

CustomLog ${APACHE_LOG_DIR}/access.log combined
ErrorLog ${APACHE_LOG_DIR}/error.log
&lt;/virtualhost&gt;

**Comment by ScottPedigo** [comment]
# domain2-le-ssl.conf

&lt;IfModule mod_ssl.c&gt;
&lt;virtualhost *:443&gt;
ServerName domain2.org
ServerAlias www.domain2.org
ServerAdmin me@someemailadress.com

DocumentRoot /home/domain2admin/domain2.org/html/

&lt;/home/domain2admin/domain2.org/html/&gt;
  Options Indexes FollowSymLinks Includes
  AllowOverride none
  Require all granted
&lt;/directory&gt;

ProxyPass    '/xxx/'    'http://www.domain2.org:8180/xxx/'
ProxyPassReverse '/xxx/'    'http://www.domain2.org:8180/xxx/'

CustomLog ${APACHE_LOG_DIR}/access.log combined
ErrorLog ${APACHE_LOG_DIR}/error.log
SSLCertificateFile /etc/letsencrypt/live/domain1.com/cert.pem
SSLCertificateKeyFile /etc/letsencrypt/live/domain1.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateChainFile /etc/letsencrypt/live/domain1.com/chain.pem
&lt;/virtualhost&gt;
</IfModule>

**Comment by ScottPedigo** [comment]
# domain2.conf

&lt;virtualhost *:80&gt;
ServerName domain2.org
ServerAlias www.domain2.org
ServerAdmin me@someemailaddress.com

DocumentRoot /home/domain2admin/domain2.org/html/

&lt;directory /home/domain2admin/domain2.org/html/&gt;
  Options Indexes FollowSymLinks Includes
  AllowOverride none
  Require all granted
&lt;/directory&gt;

ProxyPass    '/xxx/'    'http://www.domain2.org:8180/xxx/'
ProxyPassReverse '/xxx/'    'http://www.domain2.org:8180/xxx/'

CustomLog ${APACHE_LOG_DIR}/access.log combined
ErrorLog ${APACHE_LOG_DIR}/error.log
&lt;/virtualhost&gt;

**Comment by ScottPedigo** [comment]
The configuration files for the other virtual domains look similar to those of domain2.

**Comment by jiachenning** [comment]
+1
meet the same problem, can not find my vhost file

- *command*     `sudo ./certbot-auto --apache certonly --domains my.domain.com`
- *expected* my domain should be in the select list, *but* my domain disappear
- *platform* `ubuntu 14.14 trusty`
- *vhost dir* `/etc/apache2/sites-enabled/`

but I notice the key files are at `/etc/letsencrypt/live/`, so I do the rest things manually~

**Comment by Berrot** [comment]
I know this is an old thread, but figured out why I had to problems, and seems like this also goes for ScottPedigo. Seems like certbot is quite picky when it comes to how you spell <VirtualHost...>. I had <Virtualhost .....> and it refused to detect it. As soon as I changed it to <VirtualHost....> it worked like a dream. Notice the capital letters.

**Comment by jenlampton** [comment]
I'm having the same problem with an Apache / CentOS server. I believe the site is using a certificate from let's encrypt I set up last June, but when I tried to update it today using Certbot the bot was unable to read my ViurtualHost configurations. 

* My vhosts are in the bottom of my `httpd.conf` file, so I'm not running into the problem of them not being located because they are in separate files.
* My virtualhost directives are spelled out `<VirtualHost *:8080>` so I am not running into an issue with capitalization.

I've also been displeased with the lack of the most basic of documentation on CertBot. For example, where do I need to be on the server before running the commands listed on https://certbot.eff.org/#centos6-apache? How many times do I need to run through those instructions if I have three sites/domains I want certificates for on the same server? Three times, or just once? Does the certbot-auto file really need to be placed into the document root for each site on the server? If not, where is the correct location(s) for that file? 

These instructions seem to assume a very high level of understanding of how certbot works - or at the very least what it's doing - but none of that information is provided before we're launched into running these commands. Even just a paragraph saying what will happen when you run it would be helpful. Something like "THESE files will be placed in THIS directory" might help us figure out where to run the commands.

**Comment by schwindelbub** [comment]
Same problem here: Apache 2 with about 30 virtual hosts. Some already with ssl. apachectl -S is listing all hosts correctly. The config is a copy of a default config. So they are all identicaly.
But one domain could not handled with certbot. It doesn't recognize the domain. Even if i start certbot with this domain: `certbot -d <domain> --apache certonly`

Debian 8.7
Server version: Apache/2.4.10 (Debian)
certbot 0.9.3

Sample Virtualhost config
```
<Directory /var/www/__domain__/>
        php_admin_value open_basedir /var/www/__domain__/:/usr/local/lib/php:/tmp
        php_admin_value sendmail_path '/usr/sbin/sendmail -t -f no-reply@__domain__'
        DirectoryIndex index.htm index.html index.shtml start.htm start.html start.shtm index.php index.php3 index.php4
        Options -Indexes
</Directory>

<VirtualHost *:80>
        DocumentRoot /var/www/__domain__/html/
        ServerName __domain__
        ServerAlias www.__domain__
        ServerAdmin hostmaster@__domain__

        ErrorLog ${APACHE_LOG_DIR}/__domain__-error.log  
        LogLevel warn
        CustomLog ${APACHE_LOG_DIR}/__domain__-access.log combined

        RUidGid __domain__ __domain__

        # Domainrewrite
        RewriteEngine on
        RewriteCond %{HTTPS} !=on
        RewriteRule ^/?(.*) https://www.__domain__/$1 [R,L]

        <Location />
                SetOutputFilter DEFLATE
                BrowserMatch ^Mozilla/4 gzip-only-text/html
                BrowserMatch ^Mozilla/4\.0[678] no-gzip
                BrowserMatch \bMSIE !no-gzip !gzip-only-text/html
                BrowserMatch \bMSI[E] !no-gzip !gzip-only-text/html
                SetEnvIfNoCase Request_URI \
                \.(?:gif|jpe?g|png|ogg|ogv|swf|mp4|flv|html)$ no-gzip dont-vary
                Header append Vary User-Agent env=!dont-vary
        </Location>
</VirtualHost>

<VirtualHost *:443>
        DocumentRoot /var/www/__domain__/html/
        ServerName __domain__
        ServerAlias www.__domain__
        ServerAdmin hostmaster@__domain__

        ErrorLog ${APACHE_LOG_DIR}/__domain__-error.log  
        LogLevel warn
        CustomLog ${APACHE_LOG_DIR}/__domain__-access.log combined

        RUidGid __domain__ __domain__
       
        SSLEngine on
        SSLProtocol All -SSLv2 -SSLv3

        SSLCertificateFile /etc/apache2/ssl/__domain__/__domain__.crt
        SSLCertificateKeyFile /etc/apache2/ssl/__domain__/__domain__.key
        Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"

        <Location />
                SetOutputFilter DEFLATE 
                BrowserMatch ^Mozilla/4 gzip-only-text/html
                BrowserMatch ^Mozilla/4\.0[678] no-gzip
                BrowserMatch \bMSIE !no-gzip !gzip-only-text/html
                BrowserMatch \bMSI[E] !no-gzip !gzip-only-text/html
                SetEnvIfNoCase Request_URI \
                \.(?:gif|jpe?g|png|ogg|ogv|swf|mp4|flv|html)$ no-gzip dont-vary
                Header append Vary User-Agent env=!dont-vary
        </Location>
</VirtualHost>
```

Any ideas?

**Comment by schwindelbub** [comment]
I have the problem with a couple of other domains too. I don't see a relation between the domains. At the moment 4 of 43. They are two .de-Domains, one .net one .nrw.

**Comment by schwindelbub** [comment]
My Solution or workaround: apt-get remove --purge certbot && wget -O -  https://get.acme.sh | sh :-DD

**Comment by niklasfink** [comment]
Problem is solved by using only **one** VirtualHost per conf-file. Certbot does **not** support multiple VirtualHosts per file.

**Comment by schwindelbub** [comment]
I dont think that this is the only problem: 
On my system every domain, which is already configured with ssl has two virtualHost (80 and 443) in one file.
But in my case the certbot has to ignore more than only 4 virtualhost ...

**Comment by mGsWcJj86izf40K1TogLjKzvoNZdWe99** [comment]
same here, certbot for apache on centos7. I have two http (*:80) vhosts configured in sites-available and symlinked to sites-enabled. the two configs are completely identical, except domain and docroot. but the certbot only seems to detect the first config file and shows me only this one domain.

**Comment by tbandy** [comment]
I had a same problem... the solution was I'm running ISPConfig, and already set up a self-signed SSL cert. When I remove it cert-bot found the domain, and created the cert.

**Comment by vaninv** [comment]
Hi. And i had the same problem on the CentOS 7 but i've solved it. 
I have separated directories with configuration files for different users. (it's because of ISPManager)
It looks like this:
conf/vhosts-default/
conf/vhosts/user1
conf/vhosts/user2
conf/vhosts/user3
etc...

My solution is to create symbolic link to configuration file located in the user's directory, in the 'vhosts-default' directory. And everything works fine.

**Comment by bandtank** [comment]
+1 still happening to me on ubuntu with apache

**Comment by itbidhan** [comment]
I am using CentOs 7. ( $ sudo certbot --apache) Not working for me. please chack attached ScreenShot.

![imgpsh_fullsize](https://user-images.githubusercontent.com/23380310/37471968-22a958b6-2895-11e8-9ca6-e4a382d8e073.png)

**Comment by jpswade** [comment]
The default PHP + Apache AWS Elasticbeanstalk images don't have a VirtualHost, they use the default httpd.conf which serves there.

> PluginError: Unable to find a virtual host listening on port 80 which is currently needed for Certbot to prove to the CA that you control your domain. Please add a virtual host for port 80.

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.

**Comment by DanmarCRM** [comment]
got it working after removing all content from the folder:
/etc/letsencrypt/accounts/acme-v02.api.letsencrypt.org

server: Ubuntu 20.04.4 LTS \n \l
