### ISSUE TITLE
/certbot-auto not building - undefined symbol: X509_VERIFY_PARAM_set1_ip_asc

### ISSUE THREAD

**Issue by countii** [certbot/certbot#3107]
>  ./certbot-auto --help
> Creating virtual environment...
> Installing Python packages...
> Installation succeeded.
> Traceback (most recent call last):
>   File "/home/administrator/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
>     from certbot.main import main
>   File "/home/administrator/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 13, in <module>
>     from acme import jose
>   File "/home/administrator/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/__init__.py", line 37, in <module>
>     from acme.jose.interfaces import JSONDeSerializable
>   File "/home/administrator/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/interfaces.py", line 9, in <module>
>     from acme.jose import util
>   File "/home/administrator/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/util.py", line 5, in <module>
>     import OpenSSL
>   File "/home/administrator/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
>     from OpenSSL import rand, crypto, SSL
>   File "/home/administrator/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
>     from OpenSSL._util import (
>   File "/home/administrator/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
>     from cryptography.hazmat.bindings.openssl.binding import Binding
>   File "/home/administrator/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
>     from cryptography.hazmat.bindings._openssl import ffi, lib
> ImportError: /home/administrator/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: X509_VERIFY_PARAM_set1_ip_asc

Issue on an up-to-date Ubuntu 14.04.4 LTS
- Updated openSSL to 1.0.2h(newest), didnt help. 
- also tried openSSL versions 1.0.1f, 1.0.1t(newest), 1.0.1s; none worked.
- rm (..)/.local/share/letsencrypt -R didn't help (https://community.letsencrypt.org/t/undefined-symbol-x509-verify-param-set1-ip-asc/4251)

**Comment by pde** [comment]
@alex any thoughts on this?

**Comment by JakeDEvans** [comment]
Same Issue, also note 

`python -c "import ssl; print ssl.OPENSSL_VERSION"`
`OpenSSL 1.0.1f 6 Jan 2014`

**Comment by countii** [comment]
Following closely: https://github.com/SickGear/SickGear/wiki/Upgrade-SSL

> # sudo apt-get install --reinstall build-essential python-pip python-dev libssl-dev libffi-dev
> # sudo pip2.7 install -U setuptools pip pyasn1 ndg-httpsclient pyopenssl==0.13.1
> # sudo apt-get install build-essential python-pip python-dev libffi-dev libssl-dev
> # wget https://bootstrap.pypa.io/ez_setup.py -O - | sudo python
> # sudo pip install -U cryptography ndg-httpsclient pyopenssl

(for upuntu:)

> # sudo add-apt-repository ppa:fkrull/deadsnakes-python2.7
> # sudo apt-get update
> # sudo apt-get install python2.7

> # curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
> # export PATH="/home/administrator/.pyenv/bin:$PATH"
> # eval "$(pyenv init -)"
> # eval "$(pyenv virtualenv-init -)"


> # pyenv install 2.7.10
and then INSIDE you certbot directory:
> # pyenv local 2.7.10

This seems to have worked for me

**Comment by alex** [comment]
This error looks like it would occur if your headers and `.so` do not match. Without more detail I'd expect a 1.0.2 headers and a 1.0.1 `.so`.

**Comment by JakeDEvans** [comment]
`sudo apt-get install --reinstall build-essential python-pip python-dev libssl-dev libffi-dev` was enough for me.
