### ISSUE TITLE
On Mac OSX: "." or number causes ncurses to crash

### ISSUE THREAD

**Issue by Salmonhands** [certbot/certbot#3119]
Using Mac OS X 10.11.5 following instructions from https://certbot.eff.org/#osx-apache

When running ./certbot-auto, on the the input windows for domains and email addresses, as soon as I type a period or number it returns to the command prompt with one of the following messages:

"Please specify --domains, or --installer that will help in domain names autodiscovery"
"An e-mail address or --register-unsafely-without-email must be provided"

Appending -t and using the text mode lets me respond to the prompts correctly.

**Comment by bmw** [comment]
Certbot no longer uses ncurses so I'm closing this issue.
