### ISSUE TITLE
On Mac OSX: "ValueError: Invalid header value"

### ISSUE THREAD

**Issue by Salmonhands** [certbot/certbot#3120]
On Mac OS X 10.11.5, while running certbot-auto after entering an email address I receive the following error:

"ValueError: Invalid header value 'CertbotACMEClient/0.8.0 (darwin 10.11.5\n) Authenticator/apache Installer/apache'
Please see the logfiles in /var/log/letsencrypt for more details"

The most recent logfile in that directory is [letsencrypt.txt](https://github.com/certbot/certbot/files/298002/letsencrypt.txt)

**Comment by mrstanwell** [comment]
I've submitted a [pull request for a fix](https://github.com/certbot/certbot/pull/3118).

**Comment by pathros** [comment]
I get the same error:

An unexpected error occurred:
ValueError: Invalid header value 'CertbotACMEClient/0.8.0 (darwin 10.10.5\n) Authenticator/manual Installer/None'

**Comment by schoen** [comment]
@mrstanwell's PR #3118 should fix this issue (at least, it matches my understanding of what was causing this problem).
