### ISSUE TITLE
Mac OS X support installs Homebrew!

### ISSUE THREAD

**Issue by janssen** [certbot/certbot#3122]
If you think this is OK, I can't explain why it's a bug.

**Comment by bmw** [comment]
`certbot-auto`'s support of OS X is certainly less than ideal. This is why it is hidden by a `--debug` flag to even be able to run it.

You can find the logic of OS X bootstrapping [here](https://github.com/certbot/certbot/blob/master/letsencrypt-auto-source/pieces/bootstrappers/mac.sh). If you have ideas on how it can be improved, we'd certainly appreciate a pull request.

All of the officially supported systems prompt the user before making any changes like this to the user's system. Perhaps the OS X bootstrapper can do the same. Examples for how this is done can be found in the Arch, Debian, Red Hat, and SUSE bootstrappers in the same directory.

**Comment by janssen** [comment]
At the very least, you could warn that the --debug flag is equivalent to --install-homebrew-and-run.  Or just change it to that flag.

**Comment by bmw** [comment]
I'm sorry you `certbot-auto` didn't work as you expected.

We currently say "attempt experimental installation" in the help for the `--debug` flag. Perhaps we can use even harsher wording here.

**Comment by janssen** [comment]
````
[foo:~] wjanssen% ./certbot-auto
WARNING: Mac OS X support is very experimental at present...
if you would like to work on improving it, please ensure you have backups
and then run this script again with the --debug flag!
[foo:~] wjanssen% ./certbot-auto --debug
Bootstrapping dependencies via Mac OS X...
No Homebrew/MacPorts; installing Homebrew...
````

**Comment by janssen** [comment]
Perhaps a chroot jail?

**Comment by pde** [comment]
Perhaps the [instruction generator for certbot.eff.org](https://github.com/certbot/website/tree/master/_scripts/instruction-widget) should warn that this is necessary at present?

**Comment by bmw** [comment]
We're deprecating and removing macOS support from `certbot-auto`/`letsencrypt-auto` (see #4520). Instead, users should use Homebrew or MacPorts to install Certbot. Instructions for doing this with Homebrew can be found [here](https://certbot.eff.org/#osx-other).

**Comment by eschaton** [comment]
What should users who don't want to use either MacPorts or Homebrew do?

**Comment by bmw** [comment]
What do you want to use instead?

You could use [docker](https://certbot.eff.org/docs/install.html#running-with-docker), but since this runs Certbot inside a container where it cannot (easily) manipulate your webserver, you'll get a subset of Certbot's functionality.

Alternatively, after getting the right packages installed, you could create a Python virtual environment and `pip install certbot`. If you use `pip`, we strongly encourage using a virtual environment rather than installing the packages globally. See [Installing from source](https://certbot.eff.org/docs/install.html#installing-from-source) for more about this approach.

**Comment by eschaton** [comment]
I just want to use letsencrypt to set up SSL for my macOS Server without installing a package manager, containerization, etc. Simplest possible potential use.

**Comment by bmw** [comment]
Certbot has many dependencies not making this very feasible. I think something like [acme.sh](https://github.com/Neilpang/acme.sh) would better suited for your use case.
