### ISSUE TITLE
Cannot update certificate common name

### ISSUE THREAD

**Issue by robflop** [certbot/certbot#3123]
Edit2: Resolved by pfg in the freenode IRC channel!

Right, so let me start explaining my problem.

I am running a website called megumin.love, and I previously used the hostname "19502.s.time4vps.eu" (default). When I created certificates using Certbot I was still using this hostname.

However, not long ago I changed the hostname to the domain name, so megumin.love. This seems to have broken the certificate for the main domain -- and only the main domain.

The previously created certificates still work for all of my subdomains, for example i.megumin.love. 
My subdomains and my main domain are using the same fullchain.pem and same privkey.pem file, however only the main domain cert seems to have stopped working.

I have tried updating the certificates using " certbot certonly --standalone -d megumin.love -d www.megumin.love -d i.megumin.love", however this only updated the certificates for the subdomain, the main site cert yet remains to take up function again -- it still specifies that the cert was signed and issued by my old hostname, which is 19502.s.time4vps.eu.

My httpd.conf displays no configuration errors, I have checked this several times.
Edit: I have deactivated SSL for the main page while it is broken, in case you are checking the site and noticing this. So yes, it is intended to be deactivated. It remains active for subdomains.

OS: CentOS 7

**Comment by bmw** [comment]
@robflop, what are the contents of the `/etc/letsencrypt/live/` directory? In your httpd configuration, what is the value of the `SSLCertificateFile` directive being used for the megumin.love domain?

Also, as of writing this, the certificate being served at https://i.megumin.love contains megumin.love as the common name (as well as other names such as i.megumin.love in the subject alternative names).

**Comment by robflop** [comment]
@bmw The contents of my /etc/letsencrypt/live folder are a folder called "megumin.love", the value of my SSLCertificateFile being used is "/etc/letsencrypt/live/megumin.live/fullchain.pem".
