### ISSUE TITLE
sites-enabled not always enabled

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3131]
I came across this bug when working with Seth on `certbot-compatibility-test`. The problem that occurred was one of the configurations had a typo and there was a symlink in `sites-enabled` named `example.comf`. The main Apache conf file, however, contained this line `IncludeOptional sites-enabled/*.conf`. This means that `example.comf` is not actually included in the Apache configuration and the site is not enabled.

The `is_site_enabled` method in the Apache plugin, however, considers every file in `sites-enabled` to be enabled, regardless of the extension. When asked to enable a redirect on the vhost, Apache properly modified the file but didn't enable the vhost because it thought it was already enabled.

Ideally, we should parse the paths included in the main Apache configuration file to determine whether or not the vhost is actually being included in the Apache configuration.

**Comment by joohoi** [comment]
This got fixed in #4104 \o/
