### ISSUE TITLE
"DNS problem: networking error looking up A" for CNAME?

### ISSUE THREAD

**Issue by gerwitz** [certbot/certbot#3135]
I have two hostnames with very similar configurations. Both are hosted on the same nameservers, both have a CNAME to a Heroku hostname. Which then, itself, resolves to a second CNAME before finally an A is found.

The first, `www.toicon.com` worked as expected.

The second, `inside.theartificial.nl` complains:

> DNS problem: networking error looking up A 

Is there something magic about `www` hostnames that make CNAME acceptable, or is my simple domain somehow misconfigured?

**Comment by bmw** [comment]
@jsha do you have any thoughts on this?

**Comment by jsha** [comment]
The timestamp on your issue corresponds pretty closely to an outage earlier today: https://letsencrypt.status.io/pages/incident/55957a99e800baa4470002da/575835e45202927335000513. Can you try again and see if it works now?

**Comment by igo** [comment]
Same problem again. Doesn't look like a stable feature https://letsencrypt.status.io/pages/incident/55957a99e800baa4470002da/578a9c5ec211074a0e0001b5

**Comment by jsha** [comment]
FYI, incidents relating to DNS handling don't actually mean that CNAME handling is unstable, it just means that our DNS processing is having trouble. I recommend all future visitors to the issue first check https://letsencrypt.status.io/ for the latest status, and then post on the community forums at https://community.letsencrypt.org/. Tickets on the certbot repo are not a very good way to reach the Let's Encrypt Ops team if there's an outage.

Locking this thread to help direct traffic to the right place.
