### ISSUE TITLE
Installation instructions for debian 8 apache incorrect

### ISSUE THREAD

**Issue by MartijnBraam** [certbot/certbot#3145]
When installing on debian 8 with jessie backports you get python-psutil 2.1.1
This version is too old for certbot:

```
Traceback (most recent call last):
  File "/usr/bin/certbot", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: psutil>=2.2.1
```

**Comment by jcouelier** [comment]
Hi Martin,

to solve this issue did you just upgrade psutil to the latest version or are you still blocked?

**Comment by MartijnBraam** [comment]
I installed a newer psutil with pip so the certbot works. But now I have a non-managed python package on my server.

**Comment by jcouelier** [comment]
Which version of Psutil did you installed (4.2.0)?
What is the consequence of having a non managed python package on your server?

**Comment by MartijnBraam** [comment]
I now have 4.2.0 installed from pip. The problem with that is that psutil is not upgraded together with the other software on the server. If the version in the debian repository is upgraded then it might fail installation because it is overwriting non managed files.

**Comment by jcouelier** [comment]
understood. Thanks Martjin for the update

**Comment by spieiga** [comment]
I'm having the same issue.  I wish I hadn't had updated :(

**Comment by jumphog** [comment]
Just as a me also; I'm also getting the same on a new 8.5 install after updating from;

`deb http://ftp.debian.org/debian/ jessie-backports main`

`apt-get install python-certbot-apache -t jessie-backports`

```
Traceback (most recent call last):
  File "/usr/bin/certbot", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3124, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 663, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 676, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'psutil>=2.2.1' distribution was not found and is required by certbot

```
(I'm yet to update psutil)

**Comment by hlieberman** [comment]
Hello everyone!

This is fixed with the upload of 0.8.0-1~bpo8+2; my apologies for the trouble.

**Comment by mossroy** [comment]
The upgrade to 0.8.0-1~bpo8+2 fixed this issue for me too.
But now the command-line
`letsencrypt --apache`
ends up with : 
`The requested apache plugin does not appear to be installed`
I do have libaugeas0 package installed, version 1.2.0-0.2+deb8u1 and it was working a few weeks ago.

**Comment by hlieberman** [comment]
On June 11, 2016 4:41:56 AM EDT, Mossroy <notifications@github.com> wrote:
>The upgrade to 0.8.0-1~bpo8+2 fixed this issue for me too.
>But now the command-line
>`letsencrypt --apache`
>ends up with : 
>`The requested apache plugin does not appear to be installed`
>I do have libaugeas0 package installed, version 1.2.0-0.2+deb8u1 and it
>was working a few weeks ago.
>
>---
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/certbot/certbot/issues/3145#issuecomment-225344840

Can you make sure you have python-certbot-apache installed?
-- 
Harlan Lieberman-Berg
~hlieberman

**Comment by mossroy** [comment]
No I did not, and installing it solved the issue.

I thought that the upgrade would handle all the necessary to replace the python-letsencrypt-* plugin packages with python-certbot-* packages.
Anyway : problem solved. Thanks a lot!

**Comment by bamberino** [comment]
i'm getting now (0.8.0-1~bpo8+2) another error on debian 8.5 when running:
certbot renew --dry-run

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/*****.***.conf
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/dist-packages/certbot/colored_logging.py", line 41, in format
    else super(StreamHandler, self).format(record))
  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
  File "/usr/lib/python2.7/dist-packages/certbot/errors.py", line 52, in __str__
    for achall in self.failed_achalls if achall.error is not None))
  File "/usr/lib/python2.7/dist-packages/certbot/errors.py", line 52, in <genexpr>
    for achall in self.failed_achalls if achall.error is not None))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 293: ordinal not in range(128)
Logged from file renewal.py, line 352
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python2.7/logging/handlers.py", line 156, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
  File "/usr/lib/python2.7/dist-packages/certbot/errors.py", line 52, in __str__
    for achall in self.failed_achalls if achall.error is not None))
  File "/usr/lib/python2.7/dist-packages/certbot/errors.py", line 52, in <genexpr>
    for achall in self.failed_achalls if achall.error is not None))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 293: ordinal not in range(128)
Logged from file renewal.py, line 352

**Comment by hlieberman** [comment]
On June 14, 2016 12:34:34 AM EDT, bamberino <notifications@github.com> wrote:
>i'm getting now (0.8.0-1~bpo8+2) another error on debian 8.5 when
>running:
>certbot renew --dry-run
>
>-------------------------------------------------------------------------------
>Processing /etc/letsencrypt/renewal/*****.***.conf
>-------------------------------------------------------------------------------
>Traceback (most recent call last):
>  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
>    msg = self.format(record)
>File "/usr/lib/python2.7/dist-packages/certbot/colored_logging.py",
>line 41, in format
>    else super(StreamHandler, self).format(record))
>  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
>    return fmt.format(record)
>  File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
>    record.message = record.getMessage()
> File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage
>    msg = msg % self.args
>File "/usr/lib/python2.7/dist-packages/certbot/errors.py", line 52, in
>__str__
>    for achall in self.failed_achalls if achall.error is not None))
>File "/usr/lib/python2.7/dist-packages/certbot/errors.py", line 52, in
><genexpr>
>    for achall in self.failed_achalls if achall.error is not None))
>UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in
>position 293: ordinal not in range(128)
>Logged from file renewal.py, line 352
>Traceback (most recent call last):
>  File "/usr/lib/python2.7/logging/handlers.py", line 76, in emit
>    if self.shouldRollover(record):
>File "/usr/lib/python2.7/logging/handlers.py", line 156, in
>shouldRollover
>    msg = "%s\n" % self.format(record)
>  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
>    return fmt.format(record)
>  File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
>    record.message = record.getMessage()
> File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage
>    msg = msg % self.args
>File "/usr/lib/python2.7/dist-packages/certbot/errors.py", line 52, in
>__str__
>    for achall in self.failed_achalls if achall.error is not None))
>File "/usr/lib/python2.7/dist-packages/certbot/errors.py", line 52, in
><genexpr>
>    for achall in self.failed_achalls if achall.error is not None))
>UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in
>position 293: ordinal not in range(128)
>Logged from file renewal.py, line 352
>
>---
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/certbot/certbot/issues/3145#issuecomment-225777690

Hi!

This appears to be a new error not related to the Debian packaging.

Please check to see if there's an open ticket that matches and, if not, open one.
-- 
Harlan Lieberman-Berg
~hlieberman
