### ISSUE TITLE
Not redirecting to HTTPS

### ISSUE THREAD

**Issue by markcoker** [certbot/certbot#3146]
Redirection to https isn't working for 

> cokers.com.au

The following is in virtual host settings:
`
RewriteEngine on
RewriteCond %{SERVER_NAME} =cokers.com.au [OR]
RewriteCond %{SERVER_NAME} =www.cokers.com.au
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]
`

the following has been ran:
$ /home/user/.local/share/letsencrypt/bin/letsencrypt --apache --redirect --reinstall

But still does not redirect to HTTPS... subdomain 100.cokers.com.au was installed first, this does redirect properly and contains the same information.
(i have disable default virtual host, this was causing default site to be shown even when cokers.com.au was typed).

**Comment by bmw** [comment]
Have you enabled HTTPS for cokers.com.au? I'm unable to reach the site when explicitly typing `https://cokers.com.au`.

Also, is the vhost containing the rewrite rules posted above enabled? If so, can you provide the contents of the `vhost` file as well as the output of `apachectl -t -D DUMP_VHOSTS`?

**Comment by markcoker** [comment]
Sorry have changed host. I'll reset up soon. Fine to close for now.
