### ISSUE TITLE
Hook scripts directory

### ISSUE THREAD

**Issue by ebourg** [certbot/certbot#3147]
Hi,

I'd like to suggest the addition of a directory for storing hook scripts executed after a certificate renewal (for example `/etc/letsencrypt/hooks.d`). This would allow third party packages to easily integrate with certbot without overloading the `--post-hook` parameter in the cron file. For example a tomcat package could install a script in this directory to create a PKCS12 keystore in `/etc/tomcat` from the pem files and restart the Tomcat connector after each renewal.

**Comment by came88** [comment]
Related to the discussion in #3394, these hooks should be global or per lineage?

**Comment by ebourg** [comment]
Per lineage hooks might be a good idea, but the hook I had in mind was a global one (with an extra parameter indicating which certificate was renewed).

**Comment by pde** [comment]
Related: #2782

**Comment by pde** [comment]
(Giving this to @joohoi since he's also working on the script plugin)

**Comment by edwardotis** [comment]
Hi @joohoi, any update on this hook scripts feature?

**Comment by joohoi** [comment]
Hi, the functionality was split off from the script plugin in the process after all. I believe @oerdnj is working on this issue currently.

**Comment by edwardotis** [comment]
Gotcha, thanks. @oerdnj, any news?

**Comment by oerdnj** [comment]
@edwardotis I mentioned I might look into this if I find some free time. No continuous free time has popped up yet. So if there are any takers, feel free to implement this before me.

**Comment by edwardotis** [comment]
@oerdnj thanks for the update

**Comment by joohoi** [comment]
This issue will be tracked in #3868 , it has been assigned to milestone for v0.11

**Comment by bmw** [comment]
Our packaging maintainers are continuing to get requests about this feature. To prevent them from caving and making a change like this themselves, I promised we'd ship this in 0.18.0 or 0.19.0.

Putting this in 0.18.0 for now to try and land it sooner rather than later.

**Comment by bmw** [comment]
In Certbot's next minor release, we are planning on adding hook directories to Certbot to allow users and package maintainers to add scripts to be run during certificate renewal by simply placing an executable file in the appropriate directory. We wanted to post the proposed design of this system publicly to get feedback on it and to make sure it covers the majority of the desired use cases. If you are not already familiar with hooks in Certbot, see the documentation about the --pre-hook, --deploy-hook, and --post-hook flags found at https://certbot.eff.org/docs/using.html#renewing-certificates.

The proposed design is to create a directory named something like "renew-hooks" in Certbot's configuration directory (which is located at /etc/letsencrypt by default). Inside of this directory are three additional directories called "pre", "deploy", and "post" where hooks of each type can be placed. Certbot will create this directories itself if not already done so by the packaging system that installed Certbot.

When Certbot is run with the "renew" subcommand and there are certificates due for renewal, all executable files found in these directories will be run like other hooks of the same type and will run in addition to any hooks defined through existing means such as the command line, INI configuration file, or renewal configuration file. Hooks defined in these directories will not be stored in renewal configuration files, but they will continue to be run when certificates are renewed with the "renew" subcommand as long as they remain in the appropriate directory.

Hooks defined in these directories will only be run with the "renew" subcommand and will be ignored when running with the "certonly" or "run" subcommands. If you want to use hooks with these other subcommands, you will have to define them on the command line or Certbot INI file.

If anyone has any feedback on this plan, we'd love to hear it!

**Comment by ebourg** [comment]
Thank you for implementing this! Do the hook scripts get a parameter specifying the domains renewed?

**Comment by joohoi** [comment]
ebourg, yes! pre- and post hooks don't get those naturally, but the deploy hook has the following environment variables available:

- RENEWED_DOMAINS: space separated list of domains in the certificate that got renewed
- RENEWED_LINEAGE: filesystem path for the lineage that the domains belong to
