### ISSUE TITLE
certbot-auto renew cannot connect and blocks port 443

### ISSUE THREAD

**Issue by ArondeParon** [certbot/certbot#3149]
Two problems:

**Problem 1:**

For some reason `certbot-auto renew` results in connection errors for me:

`2016-06-10 14:43:07,461:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/<redacted>.conf produced an unexpected error: Failed authorization procedure. <redacted> (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Failed to connect to <redacted>:443 for TLS-SNI-01 challenge. Skipping.`

My domains and IP address are perfectly accessible over HTTPS, so I'm a bit confused here.

**Problem 2:**

When running `certbot-auto renew` any traffic to port 443 seems to be delayed/blocked. Browsers will show "Establishing secure connection" while the process is running.

Any help is appreciated.

**Comment by bmw** [comment]
I'm assuming you're using the Apache plugin. The Apache plugin has to create temporary vhosts for the purposes of solving the challenge. If your curious, you can read what exactly is required by reading the relevant section the [ACME spec](https://tools.ietf.org/html/draft-ietf-acme-acme-02#section-7.3).

After creating these vhosts, Apache has to reload your web server. This is not a full restart, but a "graceful" reload. No connections should be dropped but this might be the cause of the delay you're seeing. To work around this problem, you could try to use the [webroot](https://certbot.eff.org/docs/using.html#webroot) plugin to renew your certificates.

To actually fix this problem though, I need a little more information. Would you be willing to provide the virtual hosts files you have enabled on your site? You can redact any values you want, but this would allow us to see the configuration you're using and give us more information to help diagnose the problem.

**Comment by Ribesg** [comment]
I have a similar problem. I'm using nginx, but nginx wasn't supported at all when I installed my certs a long time ago (no idea if it is supported now, and I don't really care).

I can't renew my certs, because when running `renew --standalone`, it looks like the first renewal does not free the port 443 after success. I have to use `certonly --standalone` for each of my certs, waiting an undefined amount of time between 2 certs, waiting for the 443 port to be free again.

Meanwhile, my webserver (nginx) is down...

I'm on Ubuntu 14.04, certs installed with v0.8.1 (Maybe, it's what's written in the renewal confs).

**Comment by bmw** [comment]
@Ribesg, sorry you're having trouble. I think the issue you're having is a little different than the one reported here as I believe the original poster was using the Apache plugin. If you can open a new issue, ideally a full log where standalone doesn't properly free the port, I'd be happy to look into it. Feel free to redact domains, e-mails, and IP addresses that may be in the log as you deem appropriate.

**Comment by ArondeParon** [comment]
Quite late, but some updates to this issue:

1. Seems to have been caused by a domain that was secured with basic auth, causing the renew client to be unable to connect. Doh!
2. I am still not very clear about the root cause of the problem, but it seems to have solved itself.

I will close this issue for now.
