### ISSUE TITLE
Use root domain as folder

### ISSUE THREAD

**Issue by tinganho** [certbot/certbot#3151]
The following command in letsencrypt early version:
```shell
./letsencrypt-auto certonly --standalone --agree-tos --email me@domain.com --renew-by-default --rsa-key-size 4096 --standalone-supported-challenges http-01 -d domain.com -d sub.domain.com
```

I've had an old script that expect it to create a folder in `/etc/letsencrypt/live/domain.com`. But now it creates in `/etc/letsencrypt/live/sub.domain.com`. Which broke my whole website.

```shell
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/content.rosegarden.se/fullchain.pem. Your
   cert will expire on 2016-09-08. To obtain a new or tweaked version
   of this certificate in the future, simply run certbot-auto again.
   To non-interactively renew *all* of your certificates, run
   "certbot-auto renew"
 - If you like Certbot, please consider supporting our work by:
```

I'm trying to make certbot to create the folder `/etc/letsencrypt/live/domain.com` instead of the sub domain `/etc/letsencrypt/live/sub.domain.com`. How do I accomplish that?

**Comment by bmw** [comment]
I don't know anything about your script, but he name of the directory under live should be the first given on the command line. If you temporarily move `/etc/letsencrypt` can you repo this? You probably will want to add `--staging` to the command line which will obtain your certificate from a test server. This avoids problems with production rate limits.

To fix your current `/etc/letsencrypt` folder, you have a few options. You can delete `/etc/letsencrypt/live/sub.domain.com`, `/etc/letsencrypt/archive/sub.domain.com` and `/etc/letsencrypt/renewal/sub.domain.com.conf` and try again. If this is the only certificate lineage on this server (it's the only folder in `/etc/letsencrypt/live`), it's probably easiest to delete `/etc/letsencrypt` altogether.

**Comment by tinganho** [comment]
@bmw I tried deleting `/etc/letsencrypt` and I can confirm it doesn't solve the problem.

It depended on order before when the command was `letsencrypt-auto`. So whatever the first option `-d domain` was defined, it decided the name of the folder. But that is no longer true.

```
ubuntu@ip-172-31-11-99:~$ ./certbot-auto certonly --standalone --agree-tos --email tingan87@gmail.com --renew-by-default --rsa-key-size 4096 --standalone-supported-challenges http-01 -d content.rosegarden.se -d rosegarden.se
Requesting root privileges to run certbot...
  /home/ubuntu/.local/share/letsencrypt/bin/letsencrypt certonly --standalone --agree-tos --email tingan87@gmail.com --renew-by-default --rsa-key-size 4096 --standalone-supported-challenges http-01 -d content.rosegarden.se -d rosegarden.se

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/content.rosegarden.se/fullchain.pem. Your
   cert will expire on 2016-09-08. To obtain a new or tweaked version
   of this certificate in the future, simply run certbot-auto again.
   To non-interactively renew *all* of your certificates, run
   "certbot-auto renew"
```


```
ubuntu@ip-172-31-11-99:~$ ./certbot-auto certonly --standalone --agree-tos --email tingan87@gmail.com --renew-by-default --rsa-key-size 4096 --standalone-supported-challenges http-01 -d rosegarden.se -d content.rosegarden.se
Requesting root privileges to run certbot...
  /home/ubuntu/.local/share/letsencrypt/bin/letsencrypt certonly --standalone --agree-tos --email tingan87@gmail.com --renew-by-default --rsa-key-size 4096 --standalone-supported-challenges http-01 -d rosegarden.se -d content.rosegarden.se

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/content.rosegarden.se/fullchain.pem. Your
   cert will expire on 2016-09-08. To obtain a new or tweaked version
   of this certificate in the future, simply run certbot-auto again.
   To non-interactively renew *all* of your certificates, run
   "certbot-auto renew"
```

**Comment by bmw** [comment]
Just to be clear, if you delete `/etc/letsencrypt` and then run:
```
./certbot-auto certonly --standalone --agree-tos --email tingan87@gmail.com --renew-by-default --rsa-key-size 4096 --standalone-supported-challenges http-01 -d content.rosegarden.se -d rosegarden.se
```
Followed by:
```
./certbot-auto certonly --standalone --agree-tos --email tingan87@gmail.com --renew-by-default --rsa-key-size 4096 --standalone-supported-challenges http-01 -d rosegarden.se -d content.rosegarden.se
```
You will see the behavior described. The reason for this is when choosing which certificate to renew `certbot` does not consider domain order. So if you already have a certificate containing exactly the names `rosegarden.se` and `content.rosegarden.se`, the latter command will renew that certificate, regardless of the path in `/etc/letsencrypt/live`. This prevents the problem of accidentally creating a new path in `/etc/letsencrypt/live` when you simply meant to renew your existing cert.

If you deleted `/etc/letsencrypt` and ran:
```
./certbot-auto certonly --standalone --agree-tos --email tingan87@gmail.com --renew-by-default --rsa-key-size 4096 --standalone-supported-challenges http-01 -d rosegarden.se -d content.rosegarden.se
```
without first running the command with the domains in the opposite order, you should get `/etc/letsencrypt/live/rosegarden.se`.

**Comment by tinganho** [comment]
@bmw I can try your suggestion and report the result on a later occasion.

**Comment by tinganho** [comment]
It seems like it creates the first one.
