### ISSUE TITLE
certbot-auto not quiet when used with regular user

### ISSUE THREAD

**Issue by gdoucet** [certbot/certbot#3154]
When certbot-auto is call from a regular user crontab, certbot-auto is not quiet even when used with --quiet.

The following is print to the script even when with the --quiet argument:
$ ./certbot-auto renew --quiet
Requesting root privileges to run certbot...
  /home/gdoucet/.local/share/letsencrypt/bin/letsencrypt renew --quiet

**Comment by bmw** [comment]
fixed in #3155
