### ISSUE TITLE
certbot-auto trouble finding Python interpreter on Mac OS X system

### ISSUE THREAD

**Issue by herohamp** [certbot/certbot#3157]
When I run on a mac I keep getting this error
./certbot-auto: /usr/local/bin/pip: /usr/local/opt/python/bin/python2.7: bad interpreter: No such file or directory

**Comment by bmw** [comment]
A workaround to this problem is to use the `certbot` formula from Homebrew instead of `certbot-auto`.

**Comment by bmw** [comment]
We're deprecating and removing macOS support from `certbot-auto`/`letsencrypt-auto` (see #4520). Instead, users should use Homebrew or MacPorts to install Certbot. Instructions for doing this with Homebrew can be found [here](https://certbot.eff.org/#osx-other).
