### ISSUE TITLE
Log whether renewing or obtaining a new certificate

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3166]
It appears we don't log whether we're renewing an existing certificate or obtaining a new one. We should do this as it makes our logs more useful for debugging.

**Comment by jsachs** [comment]
@bmw  I'm going to start taking a crack at this one as a volunteer.

Is there a single place in the code where cert obtainment/renewal occurs, or are there a variety of places that this can happen?

**Comment by bmw** [comment]
Great! If you have any questions don't hesitate to stop by #letsencrypt-dev on Freenode or #certbot-dev on OFTC.

The common function here is `_auth_from_domains` in `certbot/main.py`. The purpose of this function is to determine whether we should get a new cert, renew an existing one, or simply reinstall the current certificate. We should log the choice here as I was trying to help as user debug a problem they were having with the client and couldn't tell exactly what the client was doing.
