### ISSUE TITLE
relative webroot paths stored in config

### ISSUE THREAD

**Issue by puggan** [certbot/certbot#3167]
When adding a certificate, for the webfolder you just set up, its easy to just use "." as reference, but when thats whats get stored in the config-file, it failed when it's renewed.
> [[webroot_map]]
> example.com = .

Please convert relative adresses, before saving them to the config-file.

**Comment by bmw** [comment]
To make sure I'm understanding you correctly, you're using `.` as a webroot path on the command line but it isn't being converted to an absolute path before being saved in the config file?

What version of the client are you using? This should be done in current versions of `certbot`.

**Comment by puggan** [comment]
I don't think the config-file includes what version autogenerated it.

The current version installed "letsencrypt 0.4.2"

**Comment by bmw** [comment]
Ah. This was fixed in #2758 so all releases from 0.5.0 onward do this correctly.
