### ISSUE TITLE
"certbot renew --standalone" restarts apache (all webservers?) after a renewal.

### ISSUE THREAD

**Issue by KoffieNu** [certbot/certbot#3170]
Kinda related to #3149 .

To work around this I was able to renew my certificates by stopping apache, using the standalone option and then starting it. However, after each renewed cert, apache is reloaded, even when certbot runs in standalone mode and the web server wasn't running when certbot was started. (can't it wants the port available)

It's totally logical to reload a web server when using it's plugin, but please, leave the server alone when running in standalone mode. It's a fallback for when the regular modes don't work. (or you're renewing a cert for something else, like an imap server...)

**Comment by pde** [comment]
We certainly shouldn't do this. I suspect that, because `standalone` is an Authenticator plugin only, `certbot` is noticing that Apache is available, and picking that up as an installer.  Can you provide the logfile from `/var/log/letsencrypt` that corresponds to this happening so we can confirm that?

**Comment by bmw** [comment]
I suspect the renewal config file in `/etc/letsencrypt/renewal` corresponding to the cert that was renewed has `installer = apache` in it. Changing this line to `installer = None` should resolve the problem for you but did you ever use the Apache plugin with this certificate in the past?

**Comment by pde** [comment]
@bmw yes and my concern is essentially that someone can do `certbot --standalone` and get the apache installer by default / surprise.

**Comment by KoffieNu** [comment]
Logfile:

`-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/www.vanstrik.nl.conf
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
new certificate deployed with reload of apache server; fullchain is
/etc/letsencrypt/live/www.vanstrik.nl/fullchain.pem
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/www.jbs-us.nl.conf
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
The program apache2 (process ID 17667) is already listening on TCP port 80. This
will prevent us from binding to that port. Please stop the apache2 program
temporarily and then try again. For automated renewal, you may want to use a
script that stops and starts your webserver. You can find an example at
https://letsencrypt.org/howitworks/#writing-your-own-renewal-script.
Alternatively you can use the webroot plugin to renew without needing to stop
and start your webserver.
-------------------------------------------------------------------------------
2016-06-14 10:55:28,073:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/www.jbs-us.nl.conf produced an unexpected error: At least one of the (possibly) required ports is already taken.. Skipping.`

And yeah, the certs that were giving issues had installer apache set, changed them to None to prevent this in the future.

It still is strange behavior to me, why restart a process when it was not running?

**Comment by pde** [comment]
Two questions to ask ourselves:

1. Would running `certbot` and selecting standalone on a system with Apache installed easily lead to this situation
2. Should we be saving the installer value if the verb is `certonly`?
