### ISSUE TITLE
python-certbot update issue

### ISSUE THREAD

**Issue by xWiBx** [certbot/certbot#3171]
Greetings.

While updating to new version I was faced with the following problem:

apt-get -y install certbot python-certbot ..
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-certbot : Depends: python-psutil (>= 2.2.1) but 2.1.1-1+b1 is to be installed
E: Unable to correct problems, you have held broken packages.

Can you please kindly help me with this issue?
Thanks in advance,
Kindest regards

**Comment by bmw** [comment]
Which OS are you on?

Also, make sure you've ran `apt-get update` and if you're on Debian Jessie, [install the package from backports](https://certbot.eff.org/#debianjessie-other).

**Comment by xWiBx** [comment]
Hi, I'm on Debian Linux 8, Linux 3.16.0-4-amd64 on x86_64.
and I have:
`deb http://ftp.debian.org/debian jessie-backports main`
string in the /etc/apt/sources.list
