### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3179]
Just opening this issue for tracking purposes because it appears we don't have one. Ideally, Python 3 support should be added to `certbot` and its official plugins.

**Comment by jacnoc** [comment]
This really needs to be high priority. I just looked it up and Python 3.4 is already TWO years old. Adding support for Python 3 will also encourage people to stop using older versions of Python (2.6/2.7)

**Comment by Super-Baleine** [comment]
Yea, i agree. But it requires to adapt the code in version 3, so it requires to change many lines, it will take a long time, isn't it ?

**Comment by bmw** [comment]
Yes, The `acme` module (a library for speaking the ACME protocol with Let's Encrypt) already works on Python 2.6, 2.7, and 3.3+. Adding support to the other parts of the project requires rewriting a significant portion of code.

We'll likely do it at some point (and if any of you would like to help with the effort, we'd certainly accept good PRs), however, support for Python 2.6 and 2.7 cannot be dropped due to the number of older systems using Certbot.

**Comment by Super-Baleine** [comment]
oh yea, there are many old systems which don't have python3...

**Comment by bmw** [comment]
See #4264 for a specific problem someone had trying to run Certbot with Python 3.

**Comment by ynasser** [comment]
Here is a summary (mostly written for a Pycon-affiliated sprint, but applicable to all) if someone wants to get started working on this issue:

There's lots of investigating to be done for this issue. Almost all our unit tests currently pass with Python 3 (except `certbot-nginx`), but certbot doesn't actually work with Python 3. Ideas on where to start:


- run certbot with Python 3 with the staging environment, and try to fix it when it breaks
- run the integration tests with Python 3 and figure out how to fix them when they break
- look through the issues referenced above and try to figure out what’s wrong with them individually/how to fix them
- a fairly self-contained issue would be to try and make the nginx unit tests pass with Python 3, as they’re currently the only ones which don’t
- add Python 3 support for a specific subcommand (kind of like this: https://github.com/certbot/certbot/pull/3269) 

Here’s a guide on how to support versions both 2 and 3 simultaneously: https://docs.python.org/3/howto/pyporting.html (pay particular attention to the “text vs binary data” section, as that’s where most projects run into problems.)

As for getting setup with Python 3 using a development version of certbot, follow the steps here: https://certbot.eff.org/docs/contributing.html#getting-started, but replace `./tools/venv.sh` with `./tools/venv3.sh`. Then run: `pip install -e .[dev,docs] -e certbot-apache -e certbot-nginx`.

**Comment by hogarthj** [comment]
@bmw @ynasser so the 0.14.0 release specifically mentioned py3 compatibility ...

Is it time for me to flip the switch and move Fedora over ... or is it still better to wait a bit yet?

**Comment by bmw** [comment]
@hogarthj, we are not aware of any problems on Python 3 and it is now officially supported by the Certbot team but it's had very little field testing with users trying things we may not have tested ourselves. What I told our Debian maintainer is it's slightly beneficial to wait until this has had more testing, but if there are significant benefits for you moving to Python 3 sooner rather than later, you should go ahead and package it for Python 3.

**Comment by hogarthj** [comment]
@bmw cheers ... I spoke to pdee in IRC today about this as well.

What I'm going to do is (as soon as the augeas blocker for 0.14 is fixed) is do initial builds on py2 as per current.

Then a few days later I'll flip rawhide and F26 to py3 ahead of the F26 beta to give plenty of testing there, and to allow any F26 beta testers to easily drop back to the older package if any issues are found.

After the F26 release if there are no py3 related reports I'll flip F25 over as well.

**Comment by bmw** [comment]
We've had no issues with our Python 3 support so we can close this issue.

**Comment by Tectract** [comment]
I still use python 2.7.6 and there is a VERY GOOD REASON FOR THAT. It is the operating system version of python for Ubuntu 14.04 and ubuntu 14.04 is the last version of ubuntu that did not use systemd init system, and I don't want to switch to systemd init (ever). I'm honestly not sure how to run certbot anymore now that python2.7 has been deprecated!

How do I tell certbot to use the python3 installed on my system?

Please guys do not make breaking changes to "encourage people to upgrade" their libraries!!! Please make backwards-compatible library support a priority in the future, instead!
