### ISSUE TITLE
Standardized error outputs showing reasons for failures

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#3180]
To facilitate automation, we should have error status results be clearly distinguishable from one another in a machine-readable way (either using distinctive return codes based on the error reason or having a standard set of error strings that are output).

Right now, ACME-related errors can be distinguished using the `urn:acme:error` strings that are sent by the server (and can be displayed to the user), but non-ACME-related errors can't be unless you make your own table of the particular strings that get displayed. And the return status is always 1 regardless of the reason.

**Comment by jsha** [comment]
In my opinion, we shouldn't cater to automation of Certbot by consuming commandline text output, since it prevents us from making changes. Instead, we should encourage automation through our three existing methods (plugins, hooks, and the other kind of hooks :-))
