### ISSUE TITLE
Allow explicitly expanding an existing certificate

### ISSUE THREAD

**Issue by strugee** [certbot/certbot#3183]
There should be a commandline option to explicitly name a certificate to expand, rather than acquire a brand-new cert.

**Comment by bmw** [comment]
While the context is a little different, this is actually a duplicate of #2128 which also requests a way to specify which certificate is modified on the command line.

Thanks for taking the time to create the issue though. I think this is important and personally feel we should have this before we consider releasing `certbot` 1.0.
