### ISSUE TITLE
certonly with webroot plugin: Cannot create multiple certificates with one command

### ISSUE THREAD

**Issue by fideloper** [certbot/certbot#3190]
Hello!

Following the [documentation here](https://certbot.eff.org/docs/using.html#webroot) for the webroot plugin, it appears that I should be able to create multiple certificates in one go. Specifically. I have two sites with two web roots.

The example given in the docs:

> [Taken from docs:] When requesting a certificate for multiple domains, each domain will use the most recently specified --webroot-path. So, for instance,

``` bash
certbot certonly --webroot -w /var/www/example/ -d www.example.com -d example.com -w /var/www/other -d other.example.net -d another.other.example.net
```
## Reproduce
- System: Ubuntu 16.04 x64, brand new server (DigitalOcean droplet)
- Nginx 1.10.0
- Python 2.7.11 (although I'm not sure what certbot uses with the virtualenv it creates)

I've tried both latest `master` and release `v0.8.1` - here's the commands I run to create two new certificates:

``` bash
# Use root
sudo su

# clone repo and use certbot
cd /opt
git clone https://github.com/certbot/certbot
cd /opt/certbot
git checkout v0.8.1

# create two certs
# note these webroots do exist and work (DNS is set)
./certbot-auto certonly --webroot \
    -w /var/www/one.example.io -d one.example.io \
    -w /var/www/two.example.io -d two.example.io \
    --non-interactive --agree-tos --email me@example.io
```
## Result

Everything seems to run smoothly, however only the first certificate is created.

```
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/one.example.io/fullchain.pem....
 - If you lose your account credentials...
 - Your account credentials have been saved...
 - If you like Certbot...

    Donating ...

```

(No output regarding the second webroot or domain)

**Only one certificate is created (the first listed). The second is ignored, and there is no related output.**

This is the same for the `renew` command as well as both `certonly` both ignore the second webroot.

Let me know if it looks like I'm in error or if I can send along any other information!

**Comment by schoen** [comment]
Hi @fideloper, this is the intended behavior. Each invocation of `certbot` only ever obtains a single certificate. The certificate you obtained, however, will contain subjectAltName extensions so that it applies to all of the domains you mentioned.

When the documentation says "When requesting a certificate for multiple domains, each domain will use the most recently specified --webroot-path`", it really means requesting "a" certificate for many domains, as there is no way to do the contrary. Can you think of a way that the documentation would have been clearer to you?

**Comment by fideloper** [comment]
Thank you for clarifying!

**Comment by fideloper** [comment]
Thanks for clarifying! 

I suppose saying explicitly `Each invocation of certbot only ever obtains a single certificate` is the clearest, albeit least clever way of putting it in. That begs the question of where to put that, however. 

Perhaps in the man page (CLI options docs), and repeated between Getting Certbot and Plugins sections?

**Comment by sw00** [comment]
Ah, this also clarified it for me. I was trying to automate cert retrieval on a server with multiple domains, expecting multiple `/etc/letsencrypt/live/$DOMAIN` directories to be created.

**Comment by ye** [comment]
I had the same question when I follow through the documentation here: https://certbot.eff.org/docs/using.html#where-are-my-certificates

In particular this line "All generated keys and issued certificates can be found in `/etc/letsencrypt/live/$domain`. " I feel strongly that we should explain what this `$domain` variable should be for the cases of a SAN certificate with multiple alternative names. Documentation should add "`$domain` is the first domain passed in via `-d` parameter" to make it crystal clear in addition to the mention of a SAN certificate. My two cents.

**Comment by bmw** [comment]
We'd accept a PR clarifying these points if someone would like to write it. The relevant file is https://github.com/certbot/certbot/blob/master/docs/using.rst.

**Comment by ye** [comment]
@bmw sure I can submit a PR for the doc clarification. What's the target branch for the PR I am submitting to? `devdocs`?

**Comment by bmw** [comment]
`master` is fine. Thanks @ye!
