### ISSUE TITLE
Create issue template

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3195]
We should create an issue template for this repo to help make sure we get relevant information from a user reporting a new issue. Potential questions we could include in the template are:
- Which OS are you using?
- How did you install Certbot?
- What command(s) did you run?
- What did you expect?
- What was the result?
- Can you provide a log of the problem?

We want to be careful not to discourage users from opening new issues, but getting this information up front allows us to better solve a user's problem.

**Comment by bmw** [comment]
Also, if relevant, can you provide the Apache/Nginx configuration file Certbot is struggling with?

**Comment by SwartzCr** [comment]
@schoen can you link me to the template on the community forums?

**Comment by schoen** [comment]
I'm not sure where the canonical URL is, but if you choose new topic
category Help, it pre-fills the following text:


Please fill out the fields below so we can help you better.

My domain is:

I ran this command:

It produced this output:

My operating system is (include version):

My web server is (include version):

My hosting provider, if applicable, is:

I can login to a root shell on my machine (yes or no, or I don't know):

I'm using a control panel to manage my site (no, or provide the name and
version of the control panel):

**Comment by SwartzCr** [comment]
Okay I'd like to publish these with a few changes:

- add 'how did you install certbot' after 'my operating system is'
- add 'what did you expect to happen' after 'I ran this command'
- add 'can you provide a log of the output (either from certbot itself or from the relevant webserver)' at the bottom
- move 'My domain is' to the end and add language to explain why it is important
-- possible language: "Many problems occur due to misconfigurations with your webserver or DNS record. If you share the domain you're attempting to validate with us we can often debug the issue by accessing the URL and getting some information about this configuration. If you have concerns about publishing this domain publicly you contact one of the maintainers to share it over email."

**Comment by bmw** [comment]
My two cents: I think there's a balance to strike here. More information helps us solve the problem, but asking too many questions is likely to frustrate people and/or cause them to not fill out the form.

I have some suggestions on things to remove below, but I personally think asking for relevant Apache/Nginx configuration files is extremely valuable as most problems with Apache or Nginx need this information to be resolved.

> My domain is:

> I ran this command:

>  It produced this output: 

All of this information *should* be automatically included in Certbot's logs, but it might be awkward to leave some of these questions out as they're somewhat standard for these kind of forms. Perhaps we shouldn't ask for the domain directly and rely on the log?

> My hosting provider, if applicable, is:

> I'm using a control panel to manage my site (no, or provide the name and version of the control panel):

I'm not sure if these are necessary here as it's rare for your hosting provider/control panel to be relevant when resolving an issue.

> I can login to a root shell on my machine (yes or no, or I don't know):

`root` is also less of an issue. It has come up, but `certbot-auto` automatically tries to `sudo`/`su` to `root` (and refuses to work if that fails) and we have half way decent error messages if you try to run `certbot` itself without `root`:
```
The following error was encountered:
[Errno 13] Permission denied: '/etc/letsencrypt'
If running as non-root, set --config-dir, --work-dir, and --logs-dir to writeable paths.
```

> add 'can you provide a log of the output (either from certbot itself or from the relevant webserver)' at the bottom

I think we should tell the user that logs are by default stored in `/var/log/letsencrypt` so they know where to find them. While Certbot logs are one of the most valuable things we can get, logs from your webserver are unlikely to be necessary.

> Many problems occur due to misconfigurations with your webserver or DNS record. If you share the domain you're attempting to validate with us we can often debug the issue by accessing the URL and getting some information about this configuration. If you have concerns about publishing this domain publicly you contact one of the maintainers to share it over email.

nit: I'd change the first line to something like: "Many problems can occur due to your webserver or DNS records being misconfigured."

**Comment by SwartzCr** [comment]
great - I'm going to implement these! And we can adjust them as we see fit

**Comment by SwartzCr** [comment]
check out #4201 for proposed wording - feel free to suggest edits there
