### ISSUE TITLE
Website: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by kfirba** [certbot/certbot#3198]
Hey.

I tried accessing the website to get a quick snippet of commands to run. I looked at https://certbot.eff.org/.

When I tried to pick a OS nothing happened, I didn't see any list of snippets coming up. I checked the console and saw the error: `Uncaught TypeError: Cannot read property 'addEventListener' of null`.

Thought I should let you know.

**Comment by bmw** [comment]
@kfirba, thanks for reporting the issue but there's actually a separate repository for the Certbot website. I created certbot/website#139 to track the issue there.
