### ISSUE TITLE
certbot removes http->https rules corrupts ruleset

### ISSUE THREAD

**Issue by padjon** [certbot/certbot#3210]
certbot removes rewrite-rules which may result in endless forwarding rules. It should also remove the corresponding conditions because this corrupts the ruleset otherwise.

Here is my ruleset:

RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteRule .* https://%{SERVER_NAME}%{REQUEST_URI} [NE,R,L]
RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
RewriteRule ^/(.*)$ balancer://unicornservers%{REQUEST_URI} [P,QSA,L]

certbot changes this to:

RewriteEngine On
RewriteCond %{HTTPS} !=on
#RewriteRule .* https://%{SERVER_NAME}%{REQUEST_URI} [NE,R,L]
RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
RewriteRule ^/(.*)$ balancer://unicornservers%{REQUEST_URI} [P,QSA,L]

Now the RewriteCond in line 1 is applied to the last RewriteRule and changes thereby the conditions for this rule.

**Comment by pde** [comment]
@sagi do you have time to look at this?

**Comment by sagi** [comment]
Yes. I'll do my best to start work on it today or tomorrow.
