### ISSUE TITLE
Certbot support for CouchDB?

### ISSUE THREAD

**Issue by controversial** [certbot/certbot#3211]
I'm trying to add SSL to my CouchDB database as described [here](http://docs.couchdb.org/en/1.6.1/config/http.html#config-ssl). When using `certbot` to try to register a certificate for that domain, I got the following error:

```
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: db.pythonista.cloud
   Type:   unauthorized
   Detail: Invalid response from
   http://db.pythonista.cloud/.well-known/acme-challenge/X_F_dkc5wQCl38ZA2HLOdfIC2olLFBhUEP8UihTxdIU:
   "{"error":"illegal_database_name","reason":"Name: '.well-known'.
   Only lowercase characters (a-z), digits (0-9), and any of the ch"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.
```
because this subdomain hosts CouchDB, which looks for a database with this (illegal) name. How should I proceed?

**Comment by joohoi** [comment]
Seems like CouchDB is serving all the requests, including the ones to /.well-known/acme-challenge/... So certbot is unable to get the challenge files served. 

Your options boil down to:
1) Get CouchDB to serve requests to /.well-known/acme-challenge/ from filesystem, and use webroot plugin in certbot
2) Shut down CouchDB before certbot run, and use standalone plugin to answer the challenge. Restart CouchDB after
3) Set up a HTTP proxy in front of CouchDB, that would pick up requests to /.well-known/acme-challenge/ and serve them from filesystem, and proxy the rest to CouchDB. Use webroot plugin

**Comment by pde** [comment]
4) write a couchdb [plugin](https://certbot.eff.org/docs/using.html#plugins) so that Certbot can make temporary tweaks to your couchdb config to obtain and/or install certificates :)

**Comment by controversial** [comment]
Thanks a lot, I'll try these suggestions. I can probably close this, because these sound like good suggestions.
