### ISSUE TITLE
Should the client revert temporary and in progress changes during the next run?

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3216]
If the Certbot exits with backups that weren't finalized in a checkpoint, the client will attempt to restore these backups on the next run. Is this the correct behavior? While largely mitigated by #814, it can theoretically cause issues like the one described in #940 and #1456.

**Comment by schoen** [comment]
One question related to this is whether there should be some kind of locking related to client runs, or related to `/etc/letsencrypt`, or individual lineages (to deal with the case where cron ends up trying to run two copies of the client at the same time).

**Comment by bmw** [comment]
Issues specifically addressing that are #335 and #933. I think this issue can be addressed separately though because the Reverter only rolls back changes to the user's Apache/Nginx config. `/etc/letsencrypt` isn't modified (although `/var/log/letsencrypt` and `/var/lib/letsencrypt` are).

**Comment by bmw** [comment]
I still think the behavior here can be improved/clarified.
