### ISSUE TITLE
FreeBSD error

### ISSUE THREAD

**Issue by Fastidious** [certbot/certbot#3221]
After installing (from ports), I get this error:

```
An unexpected error occurred:
VersionConflict: (acme 0.8.1 (/usr/local/lib/python2.7/site-packages), Requirement.parse('acme==0.5.0'))
Please see the logfile 'certbot.log' for more details.
```

The certbot.log contains:

```
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.8.1', 'console_scripts', 'certbot')()
  File "/usr/local/lib/python2.7/site-packages/certbot/main.py", line 700, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 174, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 33, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2379, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2396, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 833, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (acme 0.8.1 (/usr/local/lib/python2.7/site-packages), Requirement.parse('acme==0.5.0'))
```

**Comment by Bobzikwick** [comment]
What condition are your ports in? I don't the same as you.

I see:
root@piglet:~ # pkg which `which certbot`
/usr/local/bin/certbot was installed by package py27-certbot-0.8.1,1
root@piglet:~ # pkg info -d py27-certbot-0.8.1,1 | grep acme
        py27-acme-0.8.1,1
root@piglet:~ #

**Comment by Fastidious** [comment]
Brand new FreeBSD install. All ports up-to-date.

**Comment by Bobzikwick** [comment]
I'm not a python guru, but does your computer really say:
```
# pkg which 'which certbot'
/usr/local/bin/certbot was installed by package py27-certbot-0.8.1,1
```

**Comment by Fastidious** [comment]
Yup.

```
root@daemon:/usr/ports/security/py-certbot # pkg which `which certbot`
/usr/local/bin/certbot was installed by package py27-certbot-0.8.1,1
root@daemon:/usr/ports/security/py-certbot # pkg info -d py27-certbot-0.8.1,1 | grep acme
	py27-acme-0.8.1,1
root@daemon:/usr/ports/security/py-certbot # 
```

**Comment by Bobzikwick** [comment]
Well, looking at your error:
`VersionConflict: (acme 0.8.1 (/usr/local/lib/python2.7/site-packages), Requirement.parse('acme==0.5.0'))`

In my /usr/local/lib/python2.7/site-packages/certbot-0.8.1-py2.7.egg-info/requires.txt file I have a line:
`acme==0.8.1`

What does yours say?

**Comment by Fastidious** [comment]
The same. Complete `requires.txt`:

```
acme==0.8.1
ConfigArgParse>=0.9.3
configobj
cryptography>=0.7
parsedatetime>=1.3
psutil>=2.2.1
PyOpenSSL
pyrfc3339
python2-pythondialog>=3.2.2rc1
pytz
setuptools>=1.0
six
zope.component
zope.interface
mock

[dev]
astroid==1.3.5
coverage
nose
nosexcover
pep8
pylint==1.4.2
tox
twine
wheel

[docs]
repoze.sphinx.autointerface
Sphinx>=1.0
sphinx_rtd_theme
sphinxcontrib-programoutput
```

**Comment by Fastidious** [comment]
To add to this, a `portmaster -a` will always render certbot as available to re-install:

```
root@daemon:~ # portmaster -a
===>>> Gathering distinfo list for installed ports

===>>> Starting check of installed ports for available updates

	===>>> The security/py-letsencrypt port moved to security/py-certbot
	===>>> Reason: The LetsEncrypt project has renamed the utility

===>>> Launching child to reinstall py27-letsencrypt-0.5.0,1

===>>> All >> py27-letsencrypt-0.5.0,1 (1/1)

	===>>> The security/py-letsencrypt port moved to security/py-certbot
	===>>> Reason: The LetsEncrypt project has renamed the utility


===>>> Currently installed version: py27-certbot-0.8.1,1
===>>> Port directory: /usr/ports/security/py-certbot

===>>> Launching 'make checksum' for security/py-certbot in background
===>>> Gathering dependency list for security/py-certbot from ports
===>>> Initial dependency check complete for security/py-certbot

===>>> Returning to update check of installed ports


===>>> All >> (1)

===>>> The following actions will be taken if you choose to proceed:
	Re-install py27-certbot-0.8.1,1

===>>> Proceed? y/n [y] 
```

**Comment by Bobzikwick** [comment]
Your requires.txt is identical to mine 
I just ran `certbot renew` again to be sure and it worked ok...

I would have thought portmaster would do the right thing. I didn't use it though. I use pkg or make. Looks like a FreeBSD ports problem to me rather than a certbot thing.

**Comment by Fastidious** [comment]
I have pinged the maintainer to see if he can shed some light.

**Comment by koobs** [comment]
Tracking in [FreeBSD Issue #210617](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=210617)

If the root cause turns out to be the port, I'll reference this issue in the commit message

Long term, it would be great for all certbot requirements to be `>=`

**Comment by koobs** [comment]
Issue has been resolved.

Cause: stale/multiple letsencrypt versions due to use of pip to install/manage/update packages in system site-packages rather than strictly ports/packages. pkg_resources importing the older version, resulting in the mismatched (stale) version requirement

**Comment by bmw** [comment]
Great! I'm glad this was resolved.

**Comment by jmarca** [comment]
@koobs can you post a quick synopsis of how to clean up the issue?  I am hitting the same problem on slackware linux, but my python skills are super weak.

**Comment by Fastidious** [comment]
@jmarca did as you wrote, yet each time I run `portmaster -a` it will re-install `py27-certbot-0.8.1,1`. Running `pip list |grep encrypt` renders no results, while `pip list |grep cerbot` renders `certbot (0.8.1)`.  Any idea on what to do from here, @koobs?

**Comment by koobs** [comment]
@Fastidious Don't use pip to manage system site-packages? :)

**Comment by Fastidious** [comment]
@koobs I didn't. I have not used pip, I first used the ports (`make install`), then I used `pkg` to install. Still `py27-certbot` will insist on re-installing each time.

**Comment by koobs** [comment]
@Fastidious Let's take this off upstreams issue tracker :) Email me the full log of pkg version -v | grep certbot -> install certbot with portmaster and we'll go from there. I'm koobs freebsd org

**Comment by vbotka** [comment]
For the record.:
```
 pkg_deinstall py27-certbot
 pkg_deinstall py27-letsencrypt
 portinstall -R py27-certbot
```
solved the problem.
