### ISSUE TITLE
Unable to run certbot: import zope.component: ImportError: No module named component

### ISSUE THREAD

**Issue by couven92** [certbot/certbot#3228]
After installing certbot using `pip install certbot`

Running `certbot --help` returns:

```
Traceback (most recent call last):
  File "certbot\main.py", line 12, in <module>
    import zope.component
ImportError: No module named component
```

`pip list` confirms that `zope.component` is installed and I have located `zope.component-4.2.2-py2.7.egg` in my `lib/site-packages/`folder, next to the `certbot` folder

Also tried running `python setup.py install` inside a clone of this repo and that didn't help.

**Comment by pde** [comment]
What OS are you on? The backslash in the traceback suggests it might be Windows?  What's your PYTHONPATH?  Are there other copies of zope earlier in the path than `/lib/site-packages/?  What happens if you just try `import zope.component` from the python prompt?

**Comment by couven92** [comment]
Ah yes:
Python: `Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32`
Windows 10 (x64)

I have nothing with zope further up in the directory tree, but I do have a folder named `zope` in `lib/site-packages` that contains one lonely folder `zope/event`

And `import zope.component` does the following:
```
$ python
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import zope.component
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named component
```

Yes, I know, `certbot` is not supported for Windows, it's only for Linux/Apache and so on. But this error actually look much like a different problem... I just wanted to see how far I would get and what we would need to do, to port this to Windows...
I'm jsut spinning up my Linux VM, to see what happens there...

**Comment by henderea** [comment]
@pde/@couven92: This is definitely not a Windows-only issue.  I actually encountered this exact same issue on a Ubuntu xenial instance (a DO droplet), and found this GitHub issue while looking for a solution.  Unfortunately, this ticket didn't have a solution listed, but I managed to figure it out on my own, and thought I would post what helped me.

`zope.component` is a dependency of the `certbot` package, and I *did* have it installed and on the latest version.  So I tried uninstalling and reinstalling `zope.component` and suddenly the certbot command worked.

My guess is that the `zope.component` package got corrupted somehow, and that reinstalling it fixed whatever was wrong with it.  For anyone else with this error, it's worth a try.

**Comment by pit** [comment]
Same error here, but I'm running certbot from inside AWS Lambda function.
All pip dependencies are installed via 'pip install' includeing zope.component
But when running lambda function I have error:

No module named zope.component

**Comment by Gwyll** [comment]
In my case a simple pip uninstall zope.component, then a pip install zope.component==4.3.0 solved the problem.

**Comment by ssunagari** [comment]
@pit I ran into the same `No module named zope.component` problem trying to run certbot inside AWS Lambda under the python2.7 environment, but switching to the python3.6 environment effectively resolved the issue.

(Off-topic for the thread, but the next issue I encountered is that only `/tmp` is writable in the lambda execution environment, so you'll need to set up `--config-dir`, `--work-dir`, and `--logs-dir` appropriately)

**Comment by tommedema** [comment]
@ssunagari @pit I'm very interesting in running certbot from AWS lambda (i.e. without sudo). How did you manage to get it to work? How did you install certbot, or did you download a binary from somewhere? Is this binary statically linked (so you don't need to install dependencies)?

**Comment by ssunagari** [comment]
@tommedema we're using Docker to build a python 3.6 package for lambda; the handler is essentially a wrapper around `certbot.main(...)`

**Comment by tommedema** [comment]
@ssunagari that's very interesting, but how do you build packages with docker for lambda? I get that you can build a docker container, but you cannot run docker on lambda (no root). Also I read that while certbot is written in python, it cannot be directly accessed from a python script. Apparently this is only possible with the lower level acme library. Is this wrong?

**Comment by ssunagari** [comment]
I was unclear -- we're not running docker in lambda.  Docker is used so that dependencies for the python script are built in the same `amazonlinux` environment that they will run in when they run in lambda.  The ultimate output of the Dockerfile is the self-contained ZIP file package that gets uploaded to AWS.  Google should produce a number of hits, I forget which one I originally based our approach off of.

As I alluded to, you can `import certbot` and invoke its `main` method from a python script.

We're getting off-topic for the original issue, so if you still have questions after Googling around you should probably contact me directly via the e-mail address in my profile.  (I might write this up for our engineering blog too)

**Comment by bmw** [comment]
This issue hasn't seen any updates in a long time so I'm closing it. If you're still having this problem, please open a new issue.
