### ISSUE TITLE
Certbot --dry-run and --staging work but production won't

### ISSUE THREAD

**Issue by tebruno99** [certbot/certbot#3231]
./certbot-auto certonly --webroot -w /var/www/api.naveoss.com/public_html/ -d api.naveoss.com

If I use --dry-run, or --staging I get:

```
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/api.naveoss.com/fullchain.pem. Your cert will
   expire on 2016-09-28. To obtain a new or tweaked version of this
   certificate in the future, simply run certbot-auto again. To
   non-interactively renew *all* of your certificates, run
   "certbot-auto renew"
 - If you lose your account credentials, you can recover through
   e-mails sent to tebruno99@gmail.com.
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
```

However if I try to go live with a real cert:
`Failed authorization procedure. api.naveoss.com (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Could not connect to http://api.naveoss.com/.well-known/acme-challenge/hXD7XmAaqONHkdB8D64bl9hOqDzrBP6G1THd2VoBrQQ`

**Comment by tebruno99** [comment]
The Staging try comes up in my access.log but the live/production attempt doesn't even show up in my access log.  The DNS for the domain is many months old so it is not DNS propagation error.

**Comment by bmw** [comment]
@jsha, any ideas? Are there any changes in staging that are yet to land in prod that would cause this?

**Comment by jsha** [comment]
Nope, staging and prod are running the same software right now.

**Comment by bmw** [comment]
@tebruno99, are you still experiencing this problem?

If so, can you provide logs of the problem, ideally one where the client with `--staging` succeeds but fails without that flag. Logs are stored in `/var/log/letsencrypt` by default.

**Comment by tebruno99** [comment]
I'm unable to even test now because both staging and production say they are unable to resolve the MX of my email due to dns failure (wonder if this is related)

```
2016-07-07 19:06:21,534:DEBUG:acme.client:Received response <Response [400]> (headers: {'Content-Length': '133', 'Boulder-Request-Id': '7BHqE3QRUbxhF-cfCOQHkWwx4ymbSEW9T4NJanK6UcY', 'Expires': 'Thu, 07 Jul 2016 19:06:21 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 07 Jul 2016 19:06:21 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'a2A9yrbbTByjYoTYrX6LbLxKJBihcppikddHeViV9MY'}): '{\n  "type": "urn:acme:error:invalidEmail",\n  "detail": "DNS problem: networking error looking up MX for gmail.com",\n  "status": 400\n}'
```

**Comment by ivanbaldo** [comment]
Definitely Staging is different than Production.
On Staging I don't need to open port 80 in the firewall to get the certificate.
I solved it by opening port 80 temporarily, asking the certificate, then closing port 80.
Maybe I am wrong, but it would be nice to be able to use the webroot plugin with port 443 directly (with self signed or other invalid certificate).

**Comment by timoruppell** [comment]
I had this exact same problem, found a difference in staging vs production. The staging env works fine:

`certbot certonly --webroot --webroot-path /var/www/html -d foo.com --staging` 

And without `--staging` certbot throws an error:

`Failed authorization procedure. foo.com (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Could not connect to foo.com

I double checked that port 80 is open, checked that the `.well-known` is accessible. Finally when diffing the certbot logs for both attempts I found that the production command actually tries `tls-sni-01` even though the error message says 'http-01`.

So this then finally worked:

`certbot certonly --webroot --webroot-path /var/www/html --preferred-challenges http-01 -d foo.com`

**Comment by jsha** [comment]
My guess is that some of these examples of staging vs production are a result of having a cached, valid authorization on staging, and not on production. @timoruppell, it sounds like your problem is solved. If not, please post a followup on https://community.letsencrypt.org/. Thanks!

**Comment by tebruno99** [comment]
This has never happened to me again. I will close.
