### ISSUE TITLE
Allow requesting wildcard certificates in the client

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3233]
The ACME spec allows for the possibility of wildcard certificates. Certbot is an ACME client that should be able to be used by any ACME server so, as suggested by @terribleplan, we should try to allow users to request wildcard certificates as well.

Since Let's Encrypt is currently the only ACME server, all requests for wildcard certificates will fail. With this in mind, we should make sure that the error message given to the user when they request wildcard certificates is reasonable. Ideally, this is done by showing the error message returned by Let's Encrypt. If that doesn't work, we can either add our own warning message or own error checking when the server is Let's Encrypt.

**Comment by bmw** [comment]
This has been done!

**Comment by arunasank** [comment]
What version of certbot is this available on?
