### ISSUE TITLE
Cleanup "Other methods of installation"

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3237]
We should clean up https://certbot.eff.org/docs/using.html#other-methods-of-installation.

In particular, we currently list instructions for OS packages in two places which makes it harder for them to stay up to date/in sync (especially since they are in two different repos). Additionally, I think some of this information should be changed. For example, we say

> Unless you have a very specific requirements, we kindly suggest that you use the certbot-auto method.

I think this is incorrect. In almost all cases, OS packages should be preferred over `certbot-auto`.

**Comment by pconrad-fb** [comment]
I'll put this on my list.

**Comment by bmw** [comment]
Great! Please let me know if you have any questions.

**Comment by pconrad-fb** [comment]
Questions:

1. Running with Docker: 
You can't install a cert that you get via Docker because the plugins can't reach into the Docker container to get it. We should add a sentence that starts with "If you use Docker, you'll have to..." and then explains what the docker run command below will do. What does it do?
Here, we're also recommending certbot-auto. Should we be recommending OS package instructions instead? In what cases should we recommend certbot-auto?

2. Operating System Packages:
I understand that on Debian, Ubuntu, and other Linux distros, the package exists in one of the default repositories and you can just apt-get or yum install or whatever. On FreeBSD and OpenBSD, does the /usr/ports/security/py-letsencrypt directory exist right out of the box?

3. Proposed change based on your comments:
Change "Unless you have very specific requirements" to "If a package does not exist for your operating system".

**Comment by bmw** [comment]
1) Running with Docker:

> You can't install a cert that you get via Docker because the plugins can't reach into the Docker container to get it.

Actually, all of Certbot, including the plugins, are running inside of Docker. The problem is the plugins can't reach outside of the container. So, for example, if you're running an Apache webserver and then use Certbot, Certbot is unable to reach outside of Docker to modify Apache.

> We should add a sentence that starts with "If you use Docker, you'll have to..." and then explains what the docker run command below will do. What does it do?

Using the long `sudo docker run ...` command given in our documentation, Certbot will obtain a certificate and place it in the directories under `/etc/letsencrypt` on your system. The [Where are my certificates?](https://certbot.eff.org/docs/using.html#where-certs) linked in to in our Docker documentation further explains the layout of this directory. After running Certbot, the user will have to manually install their new certificates (because as explained above, Certbot is unable to do so while running inside of Docker).

> Here, we're also recommending certbot-auto. Should we be recommending OS package instructions instead? In what cases should we recommend certbot-auto?

In my opinion, the main use cases for using Docker with Certbot are:

1. Power users who only want to use Certbot to obtain a certificate.
2. Sysadmins who like the repeatability Docker containers provide.
3. Users who want to minimize the amount of changes Certbot makes to their system. This could be due to security concerns or people wanting more control over the process.

In general, these are advanced users and I think all/most of them going in will know they want to user Docker. For the average user, OS packages and `certbot-auto` should be preferred and OS packages should be preferred over `certbot-auto`. People should be using `certbot-auto` if there aren't OS packages available on their system.

2) Operating System Packages:

> I understand that on Debian, Ubuntu, and other Linux distros, the package exists in one of the default repositories and you can just apt-get or yum install or whatever. On FreeBSD and OpenBSD, does the /usr/ports/security/py-letsencrypt directory exist right out of the box?

Kind of. On BSD systems, the package instructions are similar to the `apt-get` or `yum` Linux users are familiar with. Someone makes a precompiled package that other users can download and easily install on their system.

The port system on the other hand, allows users to compile and install programs themselves using the source code. By default, `/usr/ports` is empty, however, the user uses a set of command similar to `apt-get update` which will fill `/usr/ports` with all the files they need, including `/usr/ports/security/py-letsencrypt`.

To directly answer your question, no, the files are not there out of the box. With that said, creating those files is done through basic, generic commands that a user runs to install anything from ports and for a BSD user, it really is as basic as running `apt-get update`. With this in mind, I personally don't feel  we need to specify this, but I could be convinced otherwise. For more information, see [packages and ports](https://www.freebsd.org/doc/en/articles/linux-users/software.html) from FreeBSD's official documentation.

3) Proposed change based on your comments:

> Change "Unless you have very specific requirements" to "If a package does not exist for your operating system".

I think that's a step in the right direction, however, the rest of that paragraph goes on to talk about how `certbot-auto` is the "best", "fastest", and "most reliable" method. In general, I think the paragraph should say something along the lines of:

Unless you have very specific requirements, we kindly suggest that you use the Certbot packages provided by your package manager. If such packages are not available, we recommend using `certbot-auto`, which will automate the process of installing our software on your system.

**Comment by pconrad-fb** [comment]
This is awesome. Thanks. I'll start incorporating this info.

Peter



Peter Conrad

Staff Technical Writer: Infrastructure | salesforce.com

Office: (415) 471-5265


[image: http://www.salesforce.com/signature]
<http://www.salesforce.com/signature>

--

**Comment by bmw** [comment]
This issue was fixed in #3747.
