### ISSUE TITLE
Unexpected error: NoInstallationError()

### ISSUE THREAD

**Issue by bigretromike** [certbot/certbot#3244]
Hello, 
been using letsencrypt for some time now, after rename I deleted /opt/letsencrypt and moved to apt-get install certbot.
Debian 8.5

from time to time im getting email (on root):
WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/DOMAIN.conf produced an unexpected error: The apache plugin is not working; there may be problems with your exisitng configuration. The error was: NoInstallationError(). Skipping. The following certs are not sue for renewal yet:
/etc/letsencrypt/live/domain2/fullchain.pem (skipped)
/etc/letsencrypt/live/domain3/fullchain.pem (skipped)

All renewal attempts failed. The following certs could not be renewed:
/etc/letsencrypt/live/DOMAIN/fullchain.pem (failure)

conf is:
```
cert = /etc/letsencrypt/live/DOMAIN/cert.pem
privkey = /etc/letsencrypt/live/DOMAIN/privkey.pem
chain = /etc/letsencrypt/live/DOMAIN/chain.pem
fullchain = /etc/letsencrypt/live/DOMAIN/fullchain.pem

# Options used in the renewal process
[renewalparams]
authenticator = apache
installer = apache
account = account_hash
```

Fun part is that running 'dry' or by hand resolve this problem until the time it hits it again.

```
DRY RUN: simulating 'certbot renew' close to cert expiry
          (The test certificates below have not been saved.)

Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/domain2/fullchain.pem (success)
  /etc/letsencrypt/live/DOMAIN/fullchain.pem (success)
  /etc/letsencrypt/live/domain3/fullchain.pem (success)
```

Package: certbot
Source: python-certbot
Version: 0.8.0-1~bpo8+2

Package: python-certbot-apache
Version: 0.8.0-1~bpo8+1

**Comment by pde** [comment]
This is very odd. It's really hard to see why you would get this error from the cron job in `/etc/cron.daily/`, but not while running interactively.  Although one possibility is that there are still some remnants of a previous install somewhere (did you possibly use `pip` to install?) and that differences in your environment variables are causing [parts of] that old copy to be run from cron but not from the shell.

**Comment by pde** [comment]
The most likely place that this exception is being raised would be [here](https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/configurator.py#L159), which is roughly consistent with my theory above.  I don't think there are any other places where `NoInstallationError` is raised without an explanatory string...

**Comment by pde** [comment]
CC: @joohoi @hlieberman

**Comment by pde** [comment]
Oh, actually.  Reading the code what's probably happening is that the Apache plugin checks that `apache2ctl` is available in the PATH and raises `NoInstallationError` if it can't find it.  On Debian that command is normally in `/usr/sbin/`.  Maybe the cron job is being executed with a PATH that doesn't include `/usr/sbin/`? Or your copy of `apache2ctl` is somewhere more exotic?

**Comment by bigretromike** [comment]
No i didnt install it with pip. Also crontab is clean 

On July 6, 2016 9:28:16 PM GMT+02:00, Peter Eckersley <notifications@github.com> wrote:
>This is very odd. It's really hard to see why you would get this error
>from the cron job in `/etc/cron.daily/`, but not while running
>interactively.  Although one possibility is that there are still some
>remnants of a previous install somewhere (did you possibly use `pip` to
>install?) and that differences in your environment variables are
>causing [parts of] that old copy to be run from cron but not from the
>shell.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/certbot/certbot/issues/3244#issuecomment-230880585

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pde** [comment]
@bigretromike where is your copy of `apache2ctl` located? And can you figure out what the PATH is set to inside the environment variable?  One way to do that would be to edit `/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py` and add something like this:

`print "PATH is set to ", os.environ["PATH"]`

in between lines 154 and 155, as the exception is about to be raised.

**Comment by pde** [comment]
(Then you will get that information the next time the cron job runs)

**Comment by pde** [comment]
(Correction to post about: "environment variable" -> "cron job")

**Comment by bigretromike** [comment]
I will post results as soon as possible 

On July 6, 2016 10:38:34 PM GMT+02:00, Peter Eckersley <notifications@github.com> wrote:
>(Correction to post about: "environment variable" -> "cron job")
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/certbot/certbot/issues/3244#issuecomment-230898776

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
`apache2ctl: /usr/sbin/apache2ctl /usr/share/man/man8/apache2ctl.8.gz`


also as you suggested I added new line so its looks now like this:
```
 # Verify Apache is installed
        if not util.exe_exists(constants.os_constant("restart_cmd")[0]):
            print "PATH is set to ", os.environ["PATH"]
            raise errors.NoInstallationError
```

When "NoInstallationError" will be raise I will post value that print returns

**Comment by joohoi** [comment]
For some reason Ubuntu decided not to include /usr/sbin to cron PATH, but can remedy this by extending the path variable by hand. 

This issue is discussed in length here: #1833

**Comment by bigretromike** [comment]
NoInstallationError(). Skipping.
PATH is set to /usr/bin:/bin

On July 7, 2016 8:47:16 AM GMT+02:00, Joona Hoikkala <notifications@github.com> wrote:
>For some reason Ubuntu decided not to include /usr/sbin to cron PATH,
>but can remedy this by extending the path variable by hand. 
>
>This issue is discussed in length here: #1833
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/certbot/certbot/issues/3244#issuecomment-230996537

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
Im using Debian 8.5 so probably Ubuntu took that out of Debian

Also, I will close thise as you told to go to #1833
