### ISSUE TITLE
certbot-auto on-screen instructions for removing domains from certificate

### ISSUE THREAD

**Issue by dkieffer** [certbot/certbot#3248]
As an unskilled, non technical person I got stuck on the command line renew page on how to remove domain names from the list of domains. Luckily I was sitting next to a skilled person at my coworking space, and they advised me to press space bar to deselect a selected domain.  Adding a line of instruction here would be helpful.

**Comment by ohemorange** [comment]
Certbot no longer uses the curses interface.
