### ISSUE TITLE
doesn't work on OS X: "ImportError: No module named six"

### ISSUE THREAD

**Issue by aljosa** [certbot/certbot#3256]
$ wget https://dl.eff.org/certbot-auto
$ chmod a+x certbot-auto
$ ./certbot-auto
$ ./certbot-auto --debug

```
...
Creating virtual environment...
Installing Python packages...
Installation succeeded.
Requesting root privileges to run certbot...
  /Users/[...]/.local/share/letsencrypt/bin/letsencrypt --debug
Password:
Traceback (most recent call last):
  File "/Users/[...]/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/Users/[...]/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 14, in <module>
    from acme import jose
  File "/Users/[...]/.local/share/letsencrypt/lib/python2.7/site-packages/acme/jose/__init__.py", line 25, in <module>
    from acme.jose.b64 import (
  File "/Users/[...]/.local/share/letsencrypt/lib/python2.7/site-packages/acme/jose/b64.py", line 18, in <module>
    import six
ImportError: No module named six
```

**Comment by bmw** [comment]
`certbot-auto` installs `six` as one of its dependencies so either it failed to install or `python` is having trouble finding the package.

If you delete `/Users/[...]/.local/share/letsencrypt` and run `./certbot-auto plugins --verbose`, what happens? Does the script exit with a non-zero status? Do you see any messages about problems installing `six`?

If you're still having the problem, what is the output of:
```
/Users/[...]/.local/share/letsencrypt/bin/pip freeze
```
and
```
/Users/[...]/.local/share/letsencrypt/bin/python -c "import six"
```

**Comment by aljosa** [comment]
$ rm -rf .local/share/letsencrypt/

$ cd Projects/certbot/

$ ./certbot-auto plugins --verbose
WARNING: Mac OS X support is very experimental at present...
if you would like to work on improving it, please ensure you have backups
and then run this script again with the --debug flag!

$ ./certbot-auto plugins --verbose --debug
Bootstrapping dependencies via Mac OS X...
Using Homebrew to install dependencies...
Warning: augeas-1.5.0 already installed
Warning: dialog-1.3-20160209 already installed
Creating virtual environment...
Running virtualenv with interpreter /usr/local/bin/python2.7
New python executable in /Users/aljosa/.local/share/letsencrypt/bin/python2.7
Also creating executable in /Users/aljosa/.local/share/letsencrypt/bin/python
Installing setuptools, pip, wheel...done.
Installing Python packages...
Installation succeeded.
Requesting root privileges to run certbot...
  /Users/aljosa/.local/share/letsencrypt/bin/letsencrypt plugins --verbose --debug
Password:
Traceback (most recent call last):
  File "/Users/aljosa/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/Users/aljosa/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 14, in <module>
    from acme import jose
  File "/Users/aljosa/.local/share/letsencrypt/lib/python2.7/site-packages/acme/jose/__init__.py", line 25, in <module>
    from acme.jose.b64 import (
  File "/Users/aljosa/.local/share/letsencrypt/lib/python2.7/site-packages/acme/jose/b64.py", line 18, in <module>
    import six
ImportError: No module named six

$ cd

$ ./.local/share/letsencrypt/bin/pip freeze
acme==0.8.1
appnope==0.1.0
argh==0.26.2
autoenv==1.0.0
backports.shutil-get-terminal-size==1.0.0
certbot==0.8.1
certbot-apache==0.8.1
cffi==1.4.2
ConfigArgParse==0.10.0
configobj==5.0.6
cryptography==1.2.3
decorator==4.0.10
enum34==1.1.2
flake8==2.6.0
funcsigs==0.4
futures==3.0.5
gnureadline==6.3.3
greenlet==0.4.10
idna==2.0
ipaddress==1.0.16
ipdb==0.10.1
ipython==4.2.0
ipython-genutils==0.1.0
letsencrypt==0.7.0
linecache2==1.0.0
mccabe==0.5.0
mock==1.0.1
msgpack-python==0.4.7
ndg-httpsclient==0.4.0
neovim==0.1.9
ordereddict==1.1
parsedatetime==2.1
pathlib2==2.1.0
pathtools==0.1.2
pbr==1.10.0
pexpect==4.1.0
pickleshare==0.7.2
psutil==3.3.0
ptyprocess==0.5.1
pyasn1==0.1.9
pycodestyle==2.0.0
pycparser==2.14
pyflakes==1.2.3
pyOpenSSL==0.15.1
pyRFC3339==1.0
python-augeas==0.5.0
python2-pythondialog==3.3.0
pytz==2015.7
PyYAML==3.11
requests==2.9.1
simplegeneric==0.8.1
six==1.10.0
stevedore==1.15.0
traceback2==1.4.0
traitlets==4.2.1
trollius==2.1
unittest2==1.1.0
virtualenv==15.0.2
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.1
watchdog==0.8.3
zope.component==4.2.2
zope.event==4.1.0
zope.interface==4.1.3

$ ./.local/share/letsencrypt/bin/python -c "import six"

# nothing, just a blank newline output for "import six"

**Comment by bmw** [comment]
Hm. It's not immediately clear to me what the problem is. `six` is installed, but the Python interpreter used by `certbot-auto` is unable to find the package.

As a workaround, if you're using `brew`, I'd recommend the Homebrew formula over `certbot-auto`. We're planning on updating https://certbot.eff.org to prefer that over `certbot-auto` over OS X here soon.

**Comment by Chaz6** [comment]
I have the same problem on Centos 7 (Linux).

Creating virtual environment...
Installing Python packages...
Installation succeeded.
Requesting root privileges to run certbot...
  /home/chaz/.local/share/letsencrypt/bin/letsencrypt --help
Traceback (most recent call last):
  File "/home/chaz/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/home/chaz/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 14, in <module>
    from acme import jose
  File "/home/chaz/.local/share/letsencrypt/lib/python2.7/site-packages/acme/jose/__init__.py", line 25, in <module>
    from acme.jose.b64 import (
  File "/home/chaz/.local/share/letsencrypt/lib/python2.7/site-packages/acme/jose/b64.py", line 18, in <module>
    import six
ImportError: No module named six

**Comment by pde** [comment]
Do people who are encountreing this have a `PYTHONPATH` environment variable set? What is it set to?

**Comment by bmw** [comment]
We're deprecating and removing macOS support from `certbot-auto`/`letsencrypt-auto` (see #4520). Instead, users should use Homebrew or MacPorts to install Certbot. Instructions for doing this with Homebrew can be found [here](https://certbot.eff.org/#osx-other).
