### ISSUE TITLE
CentOS 7: No package certbot available.

### ISSUE THREAD

**Issue by ibwhite** [certbot/certbot#3257]
I'm having a little trouble installing certbot on CentOS 7 -- I've run `sudo yum install epel-release`:

```
[centos@jump-1 ~]$ sudo yum install epel-release
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.solarvps.com
 * epel: mirror.us.leaseweb.net
 * extras: mirrors.lga7.us.voxel.net
 * updates: mirror.datto.com
Package epel-release-7-6.noarch already installed and latest version
Nothing to do
```

but `sudo yum install certbot` comes up:

```
[centos@jump-1 ~]$ sudo yum install certbot
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.solarvps.com
 * epel: mirror.symnds.com
 * extras: mirrors.lga7.us.voxel.net
 * updates: mirrors.advancedhosters.com
No package certbot available.
Error: Nothing to do
```

What should I be trying?

**Comment by bmw** [comment]
@hogarthj, any ideas?

**Comment by hogarthj** [comment]
It's in the repo...

https://dl.fedoraproject.org/pub/epel/7/x86_64/c/

Can you see any other epel packages?

You might want to try clearing the yum cache otherwise please run it with a high level debug and paste the output.

**Comment by ibwhite** [comment]
Thanks for pointing me in the right direction -- I apparently had a bad `epel.repo` in `/etc/yum.repos.d` -- I `rm`ed it, removed `epel-release`, cleared the yum cache, and re-installed `epel-release`, and it works now.
