### ISSUE TITLE
cerbot renew exit status

### ISSUE THREAD

**Issue by fungs** [certbot/certbot#3262]
Hi,

I would like to be able to figure out (in a Cron job) whether the renew command changed the certificate. IMO this would best be done by an appropriate exit code, for instance returning 0 when updated an something else when not. If certificates are shared by services, often they need to be notified when certificates changes.

**Comment by dusek** [comment]
For the use case you are mentioning (notifying services of renewed certificates), you can use the `certbot` options `--pre-hook`, `--post-hook` and `--renew-hook` option - more in the [docs on command line options](https://certbot.eff.org/docs/using.html#command-line-options) (there section "renew").

I personally use `--renew-hook`, as it, unlike the other two options, enables one to identify the renewed cert through shell variables, and based on that to decide exactly which services need to be restarted/notified.

**Comment by fungs** [comment]
So the `--renew-hook` is only called when the certificate is actually updated? If it is always called, then there is not much gained from using it.

Anyways, using exit codes and documenting them does make certbot work much nicer in shell scripts. It does not prevent people from using the hooks, if they want.

**Comment by dusek** [comment]
For each certificate that was successfully renewed (that is there was a new certificate actually issued), `--renew-hook` is called again. It is not called for certificates that were not actually renewed. So for example if there are no renewed certificates, `--renew-hook` is not called at all.

**Comment by pde** [comment]
@fungs we used `--renew-hook` instead of exit status because exit status has too many constraints and limitations.  For instance, `cron` will view any return code except 0 as a failure, but (as you've noticed) there is more than one type of success that is possible, including "nothing happened" and "a cert was due for renewal and was successfully renewed".

**Comment by deterenkelt** [comment]
> we used --renew-hook instead of exit status because exit status has too many constraints and limitations.

What.
> For instance, cron will view any return code except 0 as a failure

And that’s completely okay.
> but (as you've noticed) there is more than one type of success that is possible, including "nothing happened" and "a cert was due for renewal and was successfully renewed".

A job can be either done or not done. Can’t certbot decide when it got the job done? Laughable.
> b-but muh several states…

For those who didn’t understand: 

- if the certs are not present, they should be created, if they cannot be created – it is a failure; 
- if the certs are expiring and should be renewed – they should be renewed or it is a failure;
- if the certs are not expiring, and there’s no need to renew them – `renew` should return OK, for this state doesn’t harm certificates;
- but if we force the renewal, then renew should update the certs and return OK only on success. And return FAIL if it couldn’t;
- if among the passed domains there are those that expire soon, and those that do not expire, then certbot should return OK if after the end of the procedure there are left no certificates needing renewal.

For the cron job **the only thing that is important, is to know that all of the expiring certificates are updated.**

**Comment by yonjah** [comment]
@deterenkelt I think you misunderstood the issue.

@fungs  is asking for two different success status to distinguish cases where no renewal was needed and cases where renewal was actually performed successfully.
This is not possible with returning an error code from the process since as you clearly mentioned only 0 indicates success (hence the limitations)

**Comment by fungs** [comment]
I guess this issue was about two things:

1. The exit status and the renew comand: this was sufficiently solved by using the renew hook.
2. Properly supporting exit codes (one success possibility, multiple failure reasons) so that the software integrates better into UNIX systems and scripts and doesn't feel like so alien.

**So I don't know, but do any of the certbot commands actually return a non-zero exit state upon failure?**

> Anyways, using exit codes and documenting them does make certbot work much nicer in shell scripts. It does not prevent people from using the hooks, if they want.

**Comment by yonjah** [comment]
@fungs  from my short exploration of the code, any error raised causes the program to exit with status code 1 but I might missed something ( I agree that the documentation should be a bit more clear about that). 

I guess there might be some usefulness for returning different codes for different errors.
But do you have any specific use case for that ?
I think in the case of automation either you can't predict the error and then all errors are the same (you want to notify someone to check the process) or you know what may cause certain errors and you can configure your automation in a way that mitigate them so they wont happen.

**Comment by fungs** [comment]
@yonjah seems fine to me, returning non-zero on error is the minimum to be functional. Of course, returning other non-zero codes makes it easier to write scripts around certbot and to debug problems.

**Comment by bbigras** [comment]
Renew exit status would be useful if running in docker and while avoiding to use docker's socket in containers.

This command can't work since the hook is run inside the container and not on the host:

```
/usr/bin/docker run --rm \
-v [...]
quay.io/letsencrypt/letsencrypt renew --quiet --agree-tos --post-hook "docker service update test_nginx"
```

**Comment by C-Duv** [comment]
One could *echo* stuff using the `--post-hook` and use this output (which is readable to the Docker host) to determine if at least one renewal occurred (and then act accordingly)?

**Comment by Dmole** [comment]
Old thread, but I found myself here looking to renew N domains and only act if one or more were updated. 2 options I see are checking the ctime of the certs, and using something like `--renew-hook >(echo 1)` .
