### ISSUE TITLE
Refactor Apache configurator

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3273]
The file is massive, requiring `pylint: disable=too-many-lines` to pass `lint`. Does this file have to be this large? Is there a way to logically separate the file into smaller pieces/tests? Are they really ALL unit tests on the Apache configurator?

If there's no good way to separate out the tests, we can just close this issue, but I think we should take some time in the future to investigate this.

**Comment by pde** [comment]
`certbot-apache/certbot_apache/configurator.py` is also large enough to require a pylint disable. So perhaps we should refactor that before we worry about its tests :)

**Comment by bmw** [comment]
I still think we should do this.

This probably doesn't make sense to do during our current parser work, but just in case he disagrees...

cc @joohoi

**Comment by joohoi** [comment]
Agreed, let's keep it open.

**Comment by bmw** [comment]
I still think this should be done in theory, but I don't think it's something we'll get to anytime soon in practice so I'm closing this for now.
