### ISSUE TITLE
better docs for `--expand` flag

### ISSUE THREAD

**Issue by jvanasco** [certbot/certbot#3276]
I just had to get a new certificate.  i had `a, b, c, d` and needed to add `e, f`.

I knew I needed a new certificate, but I could not figure out how to cancel or keep the first certificate from rewing. 

I could not figure out how to `add` names to a certificate.

the docstring on `letsencrypt-auto` was not very helpful.  the faqs weren't either.

I eventually found a recommendation to use `--expand` on a forum post.  it was exactly what was needed.

I don't think the command needs to change, but the docs and faq should make this a lot more apparent.  I was very close to doing a revoke+create

**Comment by lkraav** [comment]
One of the things this enhanced `--expand` documentation could explain is why it isn't possible to simply add another row in `/etc/letsencrypt/renewal/domain.com.conf`? Following https://en.wikipedia.org/wiki/Single_source_of_truth it would make sense to have the domain list only in this file, but apparently one is recommended to keep the domain list in some other scratchpad / script, then find a way to build a comma-separated (not very human readable) command-line with it.
