### ISSUE TITLE
Installation on OSX Server

### ISSUE THREAD

**Issue by ekrekeler** [certbot/certbot#3277]
When I attempt installation on a Macintosh running OSX Server 5, the installation fails after installing the virtual environment. This is the debug output:
 
 
 

> Bootstrapping dependencies via Mac OS X...
> Using Homebrew to install dependencies...
> Warning: augeas-1.5.0 already installed
> Warning: dialog-1.3-20160209 already installed
> Creating virtual environment...
> Installing Python packages...
> /bin/sh: /Network/Servers/server.example.com/Volumes/Macintosh HD/Users/user/.local/share/letsencrypt/bin/pip: "/Network/Servers/server.example.com/Volumes/Macintosh: bad interpreter: No such file or directory
> Traceback (most recent call last):
>   File "/var/folders/x8/xjwh4w1j2f11vchcqtb1cfxh0000gn/T/tmp.DytMxdUk/pipstrap.py", line 146, in <module>
>     exit(main())
>   File "/var/folders/x8/xjwh4w1j2f11vchcqtb1cfxh0000gn/T/tmp.DytMxdUk/pipstrap.py", line 133, in main
>     shell=True)
>   File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 574, in check_output
>     raise CalledProcessError(retcode, cmd, output=output)
> subprocess.CalledProcessError: Command 'pip install --no-index --no-deps -U /var/folders/x8/xjwh4w1j2f11vchcqtb1cfxh0000gn/T/pipstrap-596Q5K/pip-8.0.3.tar.gz /var/folders/x8/xjwh4w1j2f11vchcqtb1cfxh0000gn/T/pipstrap-596Q5K/setuptools-20.2.2.tar.gz /var/folders/x8/xjwh4w1j2f11vchcqtb1cfxh0000gn/T/pipstrap-596Q5K/wheel-0.29.0.tar.gz' returned non-zero exit status 126

 
 
 
 
 
It seems that the installer fails as a result of the virtual environment setting the VIRTUAL_ENV variable to the full path of the system, including the domain name of the server and the name of the hard drive, which is by default "Macintosh HD". The space in the name of the hard drive kills it. I changed all the path variables according to [this thread](http://stackoverflow.com/questions/15472430/using-virtualenv-with-spaces-in-a-path), however running certbot-auto deletes the old virtual environment and creates a new one when it is run, wiping out any changes.

**Comment by bmw** [comment]
Unfortunately, our [OS X instructions](https://certbot.eff.org/#osx-other) are a bit out of date. There's a quality Homebrew formula for Certbot that should be preferred over `certbot-auto`. OS X support in `certbot-auto` has always been experimental and since you already have `brew` installed, I recommend you use that to install Certbot.

Because of this issue, I'm bumping the priority of certbot/website#130.

**Comment by cowlicks** [comment]
@bmw I think this is closeable since certbot/website#148 went in and certbot/website#130 is closed.

Also, that is cool I didn't know you could reference issues across repos with that syntax.

**Comment by pde** [comment]
OK, closing.
