### ISSUE TITLE
Cron documentation

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3284]
We don't say anything in our documentation about the Debian package including a crontab by default. We perhaps should be a little careful to avoid duplicating information across repos (see #3237), but we should make sure people know it exists as some users have been confused/surprised.

**Comment by Daniel15** [comment]
Currently the docs at https://certbot.eff.org/#debianjessie-nginx say this:

> The Debian packaged version of Certbot installs a cron job automatically into /etc/cron.d/certbot. This cronjob runs certbot renew twice a day which will renew certificates that are within the renewal window.

But they also say this on the same page:
>  you can arrange for automatic renewal by adding a cron or systemd job which runs the following:
> certbot renew --quiet 

Which is a bit confusing.

**Comment by obfusk** [comment]
I just followed the instructions on https://certbot.eff.org/#ubuntutrusty-nginx and only realised that I had added a cron job myself even though one was already installed after re-reading the instructions extra carefully to check for anything I might have missed. So still slightly confusing indeed.

**Comment by csdev** [comment]
I agree that the documentation should be updated to emphasize that certbot is installing its own crontab on Ubuntu/Debian, as this feature could cause some nasty surprises. For instance, if you use plugins that automatically deploy renewed certificates, then the default crontab could cause your server to restart at an inopportune time. Or, if you have a custom way of calling the `renew` command to specify renew/deploy hooks, you could run into a situation where the default crontab runs first, renews your certificates, but never calls your deploy hooks.

**Comment by bmw** [comment]
I believe this issue has been resolved so I'm closing it. If you think I missed something, please add a comment or open a new issue.
