### ISSUE TITLE
Point people towards OS packages

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3286]
`certbot-auto` has been helpful, but people really should be using OS packages unless they have a good reason not to do so. We should add logic to detect if there are OS packages available and if so print a message pointing them towards those packages. We should not do this if the user included `-q/--quiet` on the command line.

**Comment by surya-v** [comment]
@bmw I would like to pick this up. 
----------------------------------------
This is my understanding of the issue:
----------------------------------------
-> Execution of "certbot-auto" script should be stopped if it is found that the host OS is already packaged with certbot and show the installed package.
-> If "-q/--quite" is used while running certbot-auto, the execution should not be interrupted.

------------------------------
Thoughts on Implementation:
------------------------------
-> Add a logic to check if "letsencrypt" package is installed and interrupt the execution if found.
-> Need inputs on how the interrupt message should look like ?

**Comment by bmw** [comment]
@surya-v, I believe this would be the 3rd issue you've tackled in 3 days. Thanks for all the contributions! Feel free to join in us #letsencrypt-dev on Freenode if you have any questions or want to chat.

This issue will honestly be a tricky one; both in terms of implementation and in coming up with an approach that will appease all of the Certbot developers. If you still want to take this issue, let me know and I can give you some guidance, however, it may be easier to take another issue.

**Comment by surya-v** [comment]
I would definitely like to give a try. Can you throw more light on the possible solutions.

**Comment by bmw** [comment]
You'll want to modify the bootstrap scripts found in `letsencrypt-auto-source/pieces/bootstrappers`. You only need to worry about the Debian (`deb_common.sh`) and Red Hat (`rpm_common.sh`) scripts at this time. These are the only scripts that are officially supported that have OS packages available on some systems and don't already have a mechanism pointing users towards those packages (Arch already has [one](https://github.com/certbot/certbot/blob/master/letsencrypt-auto-source/letsencrypt-auto.template#L184)).

In each of these scripts, you'll need to use the package manager to identify if there's an OS package available. In most cases, you can simply search for a `certbot` package, however, the package is still named `letsencrypt` on Ubuntu Xenial. Be careful here as there's a `letsencrypt.sh` package out there which is a different project.

If you've determined that there is an OS package available, you need to tell the user. Probably the safest thing to do is here is simply print a message like I suggested in the original post on this issue and continue with the installation process.

After making changes to the bootstrap scripts, run `letsencrypt-auto-source/build.py` which will update `letsencrypt-auto-source/letsencrypt-auto`. Do not modify any of the `*-auto` scripts in the root directory. For legacy reasons, they are only modified during releases.

Don't hesitate to ask if you have any more questions.

cc @pde

**Comment by TheNavigat** [comment]
This issue has a PR, https://github.com/certbot/certbot/pull/3701
