### ISSUE TITLE
cryptography>=1.3 and PyOpenSSL<16.0.0

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3298]
The combination of the packages and the versions in the title causes problems as described in pyca/cryptography#2837. This problem was encountered in `jessie-backports`.

While we cannot bump our minimum `PyOpenSSL` version as CentOS 7 uses 0.13.1, perhaps we can find another workaround to a least make the problem clear for users/package maintainers.

**Comment by pde** [comment]
Would we want CentOS to try to update `PyOpenSSL`, or patch it, to mitigate this? If so we could work with out RPM team on how to proceed.

Alternatively, we can just try to detect the error by traceback inspection and tell users what is causing it.
