### ISSUE TITLE
SUSE: Please ensure that the values for --apache-handle-sites and --apache-server-root are correct for your environment.

### ISSUE THREAD

**Issue by codekraft-studio** [certbot/certbot#3302]
When I run `./letsencrypt-auto --apache -d mydomain.com` I get this:

`Directory '/etc/apache2/sites-enabled' does not exist. Please ensure that the values for --apache-handle-sites and --apache-server-root are correct for your environment.`

In the suse version of apache we are not supposed to have or use the _sites-enabled_ folder, how can I tell to the script I want to use **vhosts.d**.. I tried this:

_./letsencrypt-auto --apache --apache-handle-sites /etc/apache2/vhosts.d/ -d mydomain.com_
same error.

In my vhosts.d folder I got 2 vhost one for port 80 and another for port 443, same server name.

Thanks in advance.

**Comment by bmw** [comment]
So this is a little verbose but what if you run:
```
./letsencrypt-auto --apache --apache-handle-modules "" --apache-handle-sites "" --apache-vhost-root /etc/apache2/vhosts.d/ -d mydomain.com
```
Basically, the problem is code expecting the Debian `sites-available`/`sites-enabled` layout is running and causing problems.
