### ISSUE TITLE
Apache default default

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3307]
So in `certbot_apache/constants.py` we have this code:
```
    os_info = util.get_os_info()
    try:
        constants = CLI_DEFAULTS[os_info[0].lower()]
    except KeyError:
        constants = CLI_DEFAULTS["debian"]
```
Basically, if you're OS isn't one we we expect, we assume it's Debian. Is this the correct behavior? With Debian, we assume there are `sites-available`/`sites-enabled`, `mods-available`/`mods-enabled`/, `a2enmod`/`a2dismod`, etc.

Perhaps if we can't recognize your OS, we should choose defaults with `handle_mods` and `handle_sites` set to `False` by default. I created this issue in response to #3302.

@joohoi, IIRC you wrote most of this code. What do you think?

**Comment by joohoi** [comment]
You are right. defaulting to debian configuration is & was in place from the time we moved from debian / ubuntu only to multi-distro support to keep the original behavior as fallback for some possible corner cases. 

Debian / Ubuntu plays nicely along with distribution detection, so it should be safe to move to more widely working defaults.

**Comment by jpluimers** [comment]
Basically https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/constants.py is missing settings for `ID=opensuse` / `ID_LIKE="suse"`

This results in the issue mentioned at https://github.com/certbot/certbot/issues/3302

On my openSUSE Tumbleweed system, the content of `/etc/os-release` is this:

```
NAME=openSUSE
VERSION="Tumbleweed"
VERSION_ID="20160726"
PRETTY_NAME="openSUSE Tumbleweed (20160726) (x86_64)"
ID=opensuse
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:opensuse:20160726"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
ID_LIKE="suse"
```

Even though I'm not a Python developer, I think this should be added:

```
CLI_DEFAULTS_OPENSUSE = dict(
    server_root="/etc/apache2",
    vhost_root="/etc/apache2/vhosts.d",
    vhost_files="*.conf",
    version_cmd=['apache2ctl', '-v'],
    define_cmd=['apache2ctl', '-t', '-D', 'DUMP_RUN_CFG'],
    restart_cmd=['apache2ctl', 'graceful'],
    conftest_cmd=['apache2ctl', 'configtest'],
    enmod="a2enmod",
    dismod="a2dismod",
    le_vhost_ext="-le-ssl.conf",
    handle_mods=True,
    handle_sites=True,
    challenge_location="/etc/apache2/vhosts.d",
    MOD_SSL_CONF_SRC=pkg_resources.resource_filename(
        "certbot_apache", "options-ssl-apache.conf")
)
```

Then for `CLI_DEFAULTS` add this entry at the end:

```
    "opensuse": CLI_DEFAULTS_OPENSUSE,
```

**Comment by joohoi** [comment]
Awesome, thanks for the openSUSE constants! I'll add that to the PR taking care of this issue ( #3356 )

**Comment by joohoi** [comment]
The openSUSE constants you provided are now in with minor changes (suse doesn't seem to have a2ensite / a2dissite functionality, so had to change handle_sites False). However I don't personally have SUSE box at hand, so perhaps @jpluimers you could test it out and report if something still needs changing.

**Comment by jpluimers** [comment]
@joohoi Thanks for the update, though no success yet, I think it's a step forward. Lets see if we can get even further.

After `git checkout -b origin/osrelease_like` only the last statement below succeeded; the first ones are permutations with less parameters to see which of the constants work (but I'm not well enough into them to understand what is breaking: please enlighten).

```
# ./certbot-auto certonly --noninteractive --apache --domains 4delphi.com,www.4delphi.com
Directory '/etc/apache2/sites-enabled' does not exist. Please ensure that the values for --apache-handle-sites and --apache-server-root are correct for your environment.

# ./certbot-auto certonly --noninteractive --apache --apache-handle-modules "" --domains 4delphi.com,www.4delphi.com
Directory '/etc/apache2/sites-enabled' does not exist. Please ensure that the values for --apache-handle-sites and --apache-server-root are correct for your environment.

# ./certbot-auto certonly --noninteractive --apache --apache-handle-sites "" --domains 4delphi.com,www.4delphi.com
Unsupported directory layout. You may try to enable mod socache_shmcb and try again.

# ./certbot-auto certonly --noninteractive --apache --apache-handle-modules "" --apache-handle-sites "" --apache-vhost-root /etc/apache2/vhosts.d/ --domains 4delphi.com,www.4delphi.com

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/4delphi.com/fullchain.pem. Your cert will
   expire on 2016-10-30. To obtain a new or tweaked version of this
   certificate in the future, simply run certbot-auto again. To
   non-interactively renew *all* of your certificates, run
   "certbot-auto renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le
```

**Comment by jpluimers** [comment]
@joohoi Thanks for the update. I did `git checkout -b origin/osrelease_like` and tested but we're not there yet.

The good news is: the `--apache-vhost-root` part is not needed any more in

```
# ./certbot-auto certonly --noninteractive --apache --apache-handle-modules "" --apache-handle-sites "" --apache-vhost-root /etc/apache2/vhosts.d/ --domains 4delphi.com,www.4delphi.com
```

The bad news: the other parameters are still needed.

I'm not deep enough in python to understand what's really going on so need some more help. Only the last statement below works, the others are permutations of parameters I thought we could remove. Hopefully that helps point in the right direction of fixing.

```
# ./certbot-auto certonly --noninteractive --apache --domains 4delphi.com,www.4delphi.com
Directory '/etc/apache2/sites-enabled' does not exist. Please ensure that the values for --apache-handle-sites and --apache-server-root are correct for your environment.

# ./certbot-auto certonly --noninteractive --apache --apache-handle-modules "" --domains 4delphi.com,www.4delphi.com
Directory '/etc/apache2/sites-enabled' does not exist. Please ensure that the values for --apache-handle-sites and --apache-server-root are correct for your environment.

# ./certbot-auto certonly --noninteractive --apache --apache-handle-sites "" --domains 4delphi.com,www.4delphi.com
Unsupported directory layout. You may try to enable mod socache_shmcb and try again.

# ./certbot-auto certonly --noninteractive --apache --apache-handle-modules "" --apache-handle-sites "" --domains 4delphi.com,www.4delphi.com

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/4delphi.com/fullchain.pem. Your cert will
   expire on 2016-10-30. To obtain a new or tweaked version of this
   certificate in the future, simply run certbot-auto again. To
   non-interactively renew *all* of your certificates, run
   "certbot-auto renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le
```

**Comment by joohoi** [comment]
Thanks again for very comprehensive reporting, helps a lot!

I was a bit vague in the request for testing. cerbot-auto doesn't actually use the local copy of the client, but fetches the packages for last release from pypi. So to effectively test & run the local copy, follow the instructions here: https://certbot.eff.org/docs/contributing.html#running-a-local-copy-of-the-client

Also I think you should use --staging CLI parameter to avoid running into rate limiting problems. This uses the staging servers as endpoint, and you'll get a cert signed by the staging server. This won't show as  valid for browsers, but helps in client testing, because the rate limits are so high that they are practically nonexistent.

Per your post, I changed the handle-mods default parameter for SUSE, so you should pull the latest changes for testing from branch osrelease_like

Thanks for your effort!

**Comment by jpluimers** [comment]
@joohoi too many abbrs (; venv? pypi? relative n00bs like me will have a really hard time to understand it. So I'll ask more questions. 

Note even certbot is too much abbreviated for most noobs: I only got there because I followed https://github.com/letsencrypt/letsencrypt and was amazed to end up at https://github.com/certbot/certbot and asked "Hmm, should I trust this? It's not letsencrypt and does not advertise as originating from the Internet Security Research Group nor mentioned at https://github.com/letsencrypt! Then followed some links for like 10 minutes and decided 'this might be OK, lets try it despite it wants to run as root'."

The same for pypi (which I guess is not Pippi Langstrump): if I get something from github, I don't expect it to run something it downloaded from another source, especially not when it needs to run as root.

Don't regard that as negative criticism: letsencrypt wants everyone to use a more secure and trustworthy TLS/SSL so anything involved in that process needs to be top-notch understandable and secure including obtaining and downloading any tooling in such an obvious way that one does not need to read actual documentation.

Anyway towards the questions; this is how I started at the first time: https://gist.github.com/jpluimers/55d06cf817295051c561e77091179099 (github doesn't render reStructuredText very well, but for that gist it's good enough)

- Can I convert my `/root/Versioned/certbot` directory to become a "venv" and back again?
- When not: will a new "venv" influence anything in `etc` that I should roll-back later?
- If I need to roll-back: what?

**Comment by joohoi** [comment]
Ok, I'll try to clarify a bit.

venv - Isolated python enviroment, making sure that our dependencies, and our dependencies only are available for python. The isolation is only on the python & python package level.

pypi - definately not Pippi Langstrump, but might have monkeys around it as well. It's the python package index. Place where the releases end up for distribution. And it's used by certbot-auto to be able to do an actual version control per default regardless of the rolling release nature of git. This also allows us to verify the hash of downloaded packages, for the very reason - running stuff as root.

**Comment by jpluimers** [comment]
Are these the basic consequences of your write-up?

1. you need `venv` to ensure you run only the github code
2. `venv` does not isolate `/etc` so you if you want `/etc` untouched you need to be able to roll-back `/etc`

**Comment by joohoi** [comment]
1. simple answer is yes, it's the best practice
2. correct. certbot has ability to roll back the changes in apache configuration, but it will touch /etc/letsencrypt as well.

**Comment by jpluimers** [comment]
Sorry for getting back this late. It's been a really busy week and I needed to reserve enough time to setup a test environment.

I get the same error in this branch as with https://github.com/certbot/certbot/issues/3377 so I think the two are related. Did a merge go wrong?

Is there anyway to make the dump "richer"? (I'm a Python n00b, tried getting https://pymotw.com/2/cgitb/ to work but couldn't).

This is what I did:

```
git checkout osrelease_like
./tools/venv.sh
source ./venv/bin/activate
certbot
```

Output:

```
An unexpected error occurred:
TypeError: 'NoneType' object has no attribute '__getitem__'
Please see the logfiles in /var/log/letsencrypt for more details.
(venv)
```

Details:

```
2016-08-07 18:52:57,403:DEBUG:certbot.main:Root logging level set at 20
2016-08-07 18:52:57,409:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-08-07 18:52:57,450:DEBUG:certbot.main:certbot version: 0.9.0.dev0
2016-08-07 18:52:57,451:DEBUG:certbot.main:Arguments: []
2016-08-07 18:52:57,455:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2016-08-07 18:52:57,487:DEBUG:certbot.plugins.selection:Requested authenticator None and installer None
2016-08-07 18:52:58,563:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/Versioned/certbot/venv/bin/certbot", line 9, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/root/Versioned/certbot/certbot/main.py", line 770, in main
    return config.func(config, plugins)
  File "/root/Versioned/certbot/certbot/main.py", line 504, in run
    installer, authenticator = plug_sel.choose_configurator_plugins(config, plugins, "run")
  File "/root/Versioned/certbot/certbot/plugins/selection.py", line 184, in choose_configurator_plugins
    authenticator = installer = pick_configurator(config, req_inst, plugins)
  File "/root/Versioned/certbot/certbot/plugins/selection.py", line 24, in pick_configurator
    (interfaces.IAuthenticator, interfaces.IInstaller))
  File "/root/Versioned/certbot/certbot/plugins/selection.py", line 76, in pick_plugin
    verified.prepare()
  File "/root/Versioned/certbot/certbot/plugins/disco.py", line 219, in prepare
    return [plugin_ep.prepare() for plugin_ep in self._plugins.itervalues()]
  File "/root/Versioned/certbot/certbot/plugins/disco.py", line 105, in prepare
    self._initialized.prepare()
  File "/root/Versioned/certbot/certbot-apache/certbot_apache/configurator.py", line 191, in prepare
    self.vhosts = self.get_virtual_hosts()
  File "/root/Versioned/certbot/certbot-apache/certbot_apache/configurator.py", line 573, in get_virtual_hosts
    new_vhost = self._create_vhost(path)
  File "/root/Versioned/certbot/certbot-apache/certbot_apache/configurator.py", line 540, in _create_vhost
    filename = get_file_path(self.aug.get("/augeas/files%s/path" % get_file_path(path)))
  File "/root/Versioned/certbot/certbot-apache/certbot_apache/configurator.py", line 1805, in get_file_path
    avail_fp = vhost_path[6:]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by bmw** [comment]
The error you got looks like another instance of #3319.

**Comment by jpluimers** [comment]
Still "no cigar" in `(venv)`:

```
# git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
# date
Sat Aug 13 18:59:55 CEST 2016
# ./certbot-auto certonly --noninteractive --apache --domains pcm.4delphi.com
Directory '/etc/apache2/sites-enabled' does not exist. Please ensure that the values for --apache-handle-sites and --apache-server-root are correct for your environment.

# ./certbot-auto certonly --noninteractive --apache --apache-handle-sites "" --domains pcm.4delphi.com
Unsupported directory layout. You may try to enable mod socache_shmcb and try again.

# ./certbot-auto certonly --noninteractive --apache --apache-handle-modules "" --apache-handle-sites "" --domains pcm.4delphi.com

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/pcm.4delphi.com/fullchain.pem. Your cert will
   expire on 2016-11-11. To obtain a new or tweaked version of this
   certificate in the future, simply run certbot-auto again. To
   non-interactively renew *all* of your certificates, run
   "certbot-auto renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le
```
