### ISSUE TITLE
Verification URL after successful certificate configuration can't be opened from terminal

### ISSUE THREAD

**Issue by krichter722** [certbot/certbot#3309]
After successful creation of a certificate with `letsencrypt run` a dialog with content

```
Congratulations! You have successfully created
[URL]

You should test you configuration at:
https://www.ssllabs.com/ssltest/analyze.html?d=[URL]
```

The URL can't be opened from terminal (`gnome-terminal`). URL in the output of other applications are recognized correctly and can be opened in browser (e.g. `echo https://example.com`).

experienced with 0.4.1 on Ubuntu 16.04

**Comment by bmw** [comment]
Thanks for reporting the issue @krichter722.

Repoed on Debian Jessie with `master`. The links seem to be clickable in scrollback after `dialog` exits, however, I'm unable to use the links when `dialog` is active.

We can see if there's a setting in `dialog` that we can use to fix this. Alternatively, we could add the `ssllabs` links to the `Reporter`. This will cause the links to display as normal text output when the program exits and the links will be clickable.

**Comment by bmw** [comment]
We have completely removed `dialog` from the project in favor of our text interface. There all links are clickable so I'm closing this issue.
