### ISSUE TITLE
how to change email address for certificates

### ISSUE THREAD

**Issue by darkworks** [certbot/certbot#3310]
hi  i want to change email address for certificates  ,  as it start when i was registering certificate it my debian server it asked me for address , email address etc information . now i want to change email address , as people can see that email because am contacted by few people through my private mail address , so i want to change it for security reasons ,

thanks

**Comment by bmw** [comment]
With the exception of the incident reported [here](https://community.letsencrypt.org/t/email-address-disclosures-june-11-2016/17025), e-mail addresses you give to Let's Encrypt are private and not shared with anyone. With that said, you're still welcome to change your e-mail address.

To do so, run `certbot register --update-registration --email <email>`. Note, this feature requires Certbot version >= 0.8.0.

**Comment by darkworks** [comment]
thanks

**Comment by enbrnz** [comment]
```
certbot update_account -m <email>
```
As this was the first search result I'm commenting here.
