### ISSUE TITLE
Fatal warnings

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3311]
As reported by @Mechazawa [here](https://github.com/certbot/certbot/commit/d2f1ae9c3870289b52fb1c0ab5130c8fae52aa72#commitcomment-18318527), if `*-auto` needs the `--debug` flag on your system, it will display a warning and then exits abnormally.

Since it causes the program to exit, it's not really a warning so we should not report it as such.

**Comment by Mechazawa** [comment]
I'll submit a patch in a bit.

**Comment by bmw** [comment]
Awesome! The way we modify `certbot-auto` and `letsencrypt-auto` is a bit weird. In this case, you'll want to modify `letsencrypt-auto-source/letsencrypt-auto.template` and then run `build.py` in that same directory. The two `*-auto` scripts in the root of our repo should not be modified. We only modify them during releases.
