### ISSUE TITLE
Support correct error namespace

### ISSUE THREAD

**Issue by rolandshoemaker** [certbot/certbot#3312]
Currently Boulder uses the old 01-draft error namespace (`urn:acme:error:`) but we plan to move to the correct (as of draft-03) namespace `urn:ietf:params:acme:error:` in the near future. In order to easily transition it would probably make sense to support both namespaces for a short period of time.

**Comment by bmw** [comment]
One important thing to note is that while most platforms will get updates pretty quickly, Ubuntu 16.04 is pretty far behind (they're currently on 0.4.1). Other systems like Debian, RHEL, and CentOS will likely be in a similar situation when we get in their main repositories.

We can add support for both, but there will probably have to be support for the old namespace for quite a while if we want to avoid breakage.

**Comment by pde** [comment]
Whatever the IETF says, I don't think Boulder should change things like this without revising the protocol version number and changing the entry URL.

**Comment by bmw** [comment]
Certbot's behavior when it sees a different error namespace isn't THAT bad. Relevant `acme` code is [here](https://github.com/certbot/certbot/blob/master/acme/acme/messages.py#L11).

Basically, we lose descriptions of the error (such as the ones from the ACME spec but also longer ones telling the user how to fix the problem) and no longer remove the namespace before showing the error type to the user.

**Comment by rolandshoemaker** [comment]
Since draft-03 introduces a number of breaking changes we will need to
implement some kind of API versioning in the relatively near future.
Most likely this change will be bundled with a number of the other
breaking changes into the second API version provided by Boulder.

**Comment by bmw** [comment]
Fixed in #3469
