### ISSUE TITLE
prevent JOSE algorithm type confusion

### ISSUE THREAD

**Issue by diracdeltas** [certbot/certbot#332]
cf https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

I don't think the current JOSE implementation supports the 'None' alg type, but it does support HMAC and RSA. If the verifier isn't explicitly checking for the one that it's expecting, an attacker could potentially use this to construct valid payloads.

The blog post recommends:

> The server should already know what algorithm it uses to sign tokens, and it's not safe to allow attackers to provide this value.
> Some might argue that some servers need to support more than one algorithm for compatibility reasons. In this case, a separate key can (and should) be used for each supported algorithm. JWT conveniently provides a "key ID" field (kid) for exactly this purpose. Since servers can use the key ID to look up the key and its corresponding algorithm, attackers are no longer able to control the manner in which a key is used for verification. In any case, I don't think JWT libraries should even look at the alg field in the header, except maybe to check that it matches what was the expected algorithm.

**Comment by kuba** [comment]
Please note that no JWS is ever sent from server to the client, it's the other way round. Client does not verify JWS at any point. Hence, client cannot be vulnerable.

Nevertheless, our `acme.jose` module, which is meant to be used by possible server implementations is somewhat vulnerable. I'll send a PR with necessary warnings and, as suggested in the blog post, `verify(payload, key, alg)` signature.

**Comment by diracdeltas** [comment]
That's what I thought too. I took a quick look at the JOSE verification code in Boulder and it looks like it only accepts RSA or ECDSA so there's not an obvious issue there.

**Comment by bmw** [comment]
Closing due to the new issue #992.

**Comment by kuba** [comment]
This should be reopened and labelled as `security`. #992 is about different "types".

**Comment by bmw** [comment]
I moved this to the josepy repo which now contains the relevant code.
