### ISSUE TITLE
Webroot option should explain what a webroot is

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#3322]

**Comment by jsha** [comment]
Related: #5431

**Comment by bmw** [comment]
Yeah. This seems valuable.

I don't want to ping you on too much all at once @schoen, but are you interested in working on this? Seems like a pretty basic, glaring issue that has been there for a long time.

The title of this issue to me seems like it's mainly referring to the `--help` output or interactive menus, but I bet there's also work to be done here at https://certbot.eff.org/docs/using.html#webroot or in our instruction generator.
