### ISSUE TITLE
Parsing error in apache configuration

### ISSUE THREAD

**Issue by Polve** [certbot/certbot#3325]
The following Location directive in my apache config file:

```
  <Location ~ "/(.*)/adm>
  # things
  </Location>
```

gives the following error:

> The apache plugin is not working; there may be problems with your existing configuration.
> The error was: PluginError(('There has been an error in parsing the file (%s): %s', '/etc/apache2/sites-enabled/https.conf', 'Syntax error'),)

Using certbot 8.1 from Debian Jessie backports.

This forces to me to not use the apache plugin e renew the certificate by hand using webroot.

**Comment by bmw** [comment]
@domcleal, I believe this is an Augeas parsing error.

**Comment by domcleal** [comment]
Thanks @bmw. The issue is the mismatched quote - as a workaround, add it:

    <Location ~ "/(.*)/adm">
