### ISSUE TITLE
No Installers Error - Apache is installed

### ISSUE THREAD

**Issue by cferrier1995** [certbot/certbot#3326]
I am attempting to get certbot working on the following amazon ec2 LAMP stack instance: https://aws.amazon.com/marketplace/pp/B007IN7GJA

The instance comes pre-installed with apache, however when I run the the steps outlined in https://certbot.eff.org/#ubuntutrusty-apache from the home directory I receive the following error after running the ./certbot-auto command: 

> Fetched 1,706 kB in 7s (217 kB/s)                                              
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dialog is already the newest version.
gcc is already the newest version.
python is already the newest version.
python-dev is already the newest version.
augeas-lenses is already the newest version.
ca-certificates is already the newest version.
libaugeas0 is already the newest version.
libffi-dev is already the newest version.
libssl-dev is already the newest version.
python-virtualenv is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.
Creating virtual environment...
Installing Python packages...
Installation succeeded.
No installers seem to be present and working on your system; fix that or try running certbot with the "certonly" command

Afterwards, when I run the certbot-auto --apache command I recieve the following error: 

> The apache plugin is not working; there may be problems with your existing configuration.

My understanding is these errors are suppose to trigger when Apache isn't installed properly on the system, but since Apache is on the system and I'm running Ubuntu 14.04, this should not be the case.

**Comment by bmw** [comment]
This error is raised when either there is a problem with the Apache configuration (`apachectl -t` exits with a non-zero status) or our parser can't parse your config files. You can provide the content of the log files in `/var/log/letsencrypt`?

**Comment by cferrier1995** [comment]
I ended up starting up a new instance and just using the webroot certonly
method, then manually adding the certs to the ssl conf file. Sorry that I
didn't get the logs beforehand and thanks for responding so quickly.

**Comment by pde** [comment]
@cferrier1995 the logs from previous runs should probably still be around...

**Comment by pde** [comment]
Closing this since we probably don't have enough information to track it down. Please reopen if you do happen to find those logs!
