### ISSUE TITLE
Add "Secure + HSTS" to "Easy vs Secure" prompt

### ISSUE THREAD

**Issue by theel0ja** [certbot/certbot#3329]
Ok, we have in certbot-auto prompt like this (see below), we could add choice named "Secure + HSTS" that automatically installs the current "Secure" and HSTS to our webserver conf-files.

```
Please choose whether HTTPS access is required or optional.
-------------------------------------------------------------------------------
1: Easy - Allow both HTTP and HTTPS access to these sites
2: Secure - Make all requests redirect to secure HTTPS access
-------------------------------------------------------------------------------
```

Like this:

```
Please choose whether HTTPS access is required or optional.
-------------------------------------------------------------------------------
1: Easy - Allow both HTTP and HTTPS access to these sites
2: Secure - Make all requests redirect to secure HTTPS access
3. Secure + HSTS - Make all requests redirect to secure HTTPS access and use HSTS
-------------------------------------------------------------------------------
```

or something like that

**Comment by pde** [comment]
Related: #1123 

The way I was inclined to implement this is to offer "Easy", "Secure", and "Custom".  Picking "Secure" should over time lead to a user experience that walks you through the steps to enabling HSTS, after checking things aren't breaking.  Picking "Custom" would give you a full checklist of every enhancement we support.

But the design could probably use some input from a UX/UI person!

**Comment by theel0ja** [comment]
Is HSTS available on the latest version?

**Comment by pde** [comment]
@joohoi this one's also for you to keep or close.
