### ISSUE TITLE
/.well-known/ webroot path not updated on renewal execution of certbot

### ISSUE THREAD

**Issue by fsantiago07044** [certbot/certbot#3332]
Originally created cert using the webroot method and with defined path x.

web path x has since been updated to path y.

now, on running certbot to renew this cert with the parameters:

/certbot/certbot-auto renew -c /etc/letsencrypt/cli.ini

cli.ini = 

keep
noninteractive
agree-tos
email = <my email>

it produces a 404 error:

1 renew failure(s), 0 parse failure(s)
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: <my domain>
   Type:   unauthorized
   Detail: Invalid response from
   <my domain>/.well-known/acme-challenge/YxkZqsf2GvY8fv0GRawD-Hmj2JlOEo-sYaTR_X1ROTQ:
   "<html>
   <head><title>404 Not Found</title></head>
   <body bgcolor="white">
   <center><h1>404 Not Found</h1></center>
   <hr><center>"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.

************************************************************************************

i fixed it by manually editing the file: /etc/letsencrypt/renewal/<my domain>.conf

and updating the webroot path specified in the parameter: [[webroot_map]]

is this normal? Thanks.

**Comment by bmw** [comment]
Yes. This is normal.

The purpose of the files in `/etc/letsencrypt/renewal` is to save the parameters that were used to obtain your certificate so we can use them again for renewal. These values can be overridden by:

1. Setting the values you want to be changed on the command line or a `cli.ini` file.
2. Modifying the value directly in `/etc/letsencrypt/renewal` like you did.

It's important to note, however, if you do option 1 and run `certbot renew`, it will modify the parameter in every file in `/etc/letsencrypt/renewal` that is due for renewal. This will be changed in the near future, but currently the only way to get finer grained control on which files are changes is to use the `certbot certonly` command.

More information about this is provided in our [renewal documentation](https://certbot.eff.org/docs/using.html#renewal).

**Comment by fsantiago07044** [comment]
understood. thank you for your prompt response.
