### ISSUE TITLE
letsencrypt-auto-source/letsencrypt-auto should be the output of build.py

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3338]
`letsencrypt-auto-source/letsencrypt-auto` should be the output of `letsencrypt-auto-source/build.py`. We should write a test that enforces this and run it in Travis. If the files differ, error out with a warning message explaining the problem.

**Comment by TheNavigat** [comment]
This should be tagged with has PR. https://github.com/certbot/certbot/pull/3460
