### ISSUE TITLE
Run simple certbot-auto tests with `tox`

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3339]
#3337 and #3338 should ideally run when the user type `tox`. This allows them to catch the problem locally before they make a PR.

**Comment by surya-v** [comment]
@bmw i would like to start contributing to Certbot and I would like to start off with this issue. I would pick this up once #3338 is closed.
I have the following doubts:
1) When i run the tox command in the venv, i get an error saying "InterpretorNotFound: python" for versions 2.6, 3.3 and 3.4. Do i need to install them into the venv explicitly ?
2) For #3337, do i have to do anything else apart from adding the the  "certbot_compatibility_test.sh" in the tox.ini file ?
Request you to help me through this, as this is my very first open-source contribution.

**Comment by bmw** [comment]
Thanks for your interest in contributing to the project!

> 1) When i run the tox command in the venv, i get an error saying "InterpretorNotFound: python" for versions 2.6, 3.3 and 3.4. Do i need to install them into the venv explicitly ?

No. `tox` will use the versions of Python you have available (in your case Python 2.7 and Python 3.5) and error out for any missing versions. Most Certbot devs don't worry about these errors as the tests will be run in Travis for all Python versions. You can get a prettier error message here by running `tox --skip-missing-interpreters`.

> 2) For #3337, do i have to do anything else apart from adding the the "certbot_compatibility_test.sh" in the tox.ini file ?

Do you mean `modification-check.sh`? To resolve this issue, you should add a new `testenv` to `tox.ini` (see the current file for examples) that simply runs `modification-check.sh`. See [this](https://github.com/certbot/certbot/blob/master/tox.ini#L101) for an example. You should add the `testenv` to the `envlist` in the top of the file so it's automatically run when the user types `tox`.

**Comment by surya-v** [comment]
Thank you @bmw for the detailed explanation. I have added a new  testenv to only run "modification_check.sh" and also appended the same to "envlist". I would submit a pull request after making the changes required for #3338, once it is closed.
