### ISSUE TITLE
letsencrypt-auto-source/letsencrypt-auto

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3340]
Some changes we make in between releases can break this script.

For example, we recently removed the `psutil` dependency from `setup.py`. We could remove it from `requirements.txt` as well, however, this script would fail to run because `requirements.txt` pins the last version of Certbot released to PyPI.

At least 3 options here:
1. Decide that we don't care that this script is broken. People should be using the version in the root of the repo. This means we may not be able to use the script for testing purposes in between releases.
2. Make this script pull from `git`. This means that either the production `certbot-auto` script has a branch that pulls from `git` or we remove that code during releases.
3. Only make breaking changes during the release process.

**Comment by pde** [comment]
Have `certbot-auto` support something like `--version $TAG` that runs whatever that git branch is?

**Comment by bmw** [comment]
If it's a released version number on PyPI, that wouldn't be too bad, but if you wanted to be able to test an arbitrary `git` branch, we'd have to depend on and use `git` in `certbot-auto`.

**Comment by pde** [comment]
If it's a flag like this intended for developer usage, I think it'd be okay to error out and say `Sorry, you need to install git if you want to specificy a version to run`.

**Comment by bmw** [comment]
We could, but it's extra complexity in an already complex script. I wonder if it wouldn't be better to write a script to automate building packages and a version of `certbot-auto` that uses a dummy key.

**Comment by bmw** [comment]
This hasn't bit us, but this is still a thing that can cause things like our test farm tests to fail. Hopefully this issue will be closed by the removal of certbot-auto.

**Comment by bmw** [comment]
certbot-auto has been deprecated, will error out on new systems, and existing installations are no longer receiving updates so I'm closing this.
