### ISSUE TITLE
Rationalise challenge and port selection flags

### ISSUE THREAD

**Issue by pde** [certbot/certbot#3343]
We need to choose challenge types for:
* manual
* the (currently nonexistent) script plugin
* standalone

We need to choose ports for:
* standalone
* testing deployments
* things that are running behind proxies

The flags for doing all of these things should probably be cleaned up and rationalised.

**Comment by pde** [comment]
Needed for: #2782

**Comment by pde** [comment]
Needed for turning #2061 into an end user feature.

**Comment by bmw** [comment]
To add more info here, we want a flag (or flags) in the core of the client (not in any of the plugins) that can be used for challenge selection. Flags like `--standalone-supported-challenges` and `--manual-supported-challenges` should be removed.

Probably the best way for this to work is to have a flag like `--preferred-challenges` or `--challenge-preferences` that can be used to provide a delimited list of the preferred challenges you want Certbot to perform, listed in the order they are preferred. This is like the `--standalone-support-challenges` flag.

Normally, Certbot determines that challenges that will be performed with the `gen_challenge_path` function in `certbot/auth_handler.py`. `get_chall_pref` is called on the selected plugin and is passed as the `preferences` argument to this function, which then uses these preferences and the challenges required by the server to determine which challenge to perform.

With the addition of the flag described above, the `preferences` parameter to this function should be the intersection of the challenges provided by the user in the new flag and the return value of `get_chall_pref`, with the order of the challenges being determined the user in the new flag.

For example, if the user provides `--preferred-challenges dns-01,tls-sni-01,http-01` and `get_chall_pref` returns `[tls-sni-01,dns-01]`, the value for `preferences` should be `[dns-01,tls-sni-01]`. Note: `gen_challenge_path` expects `acme.challenges.Challenge` classes, not simple strings as shown in my example.

If the intersection between the challenges requested by the user and those preferred by the plugin is empty, Certbot should error out (this may happen automatically, but this is the desired end result as there is no way to satisfy the CA and the user).

This issue also requests the ability to specify ports which is available through the `--http-01-port` and `--tls-sni-01-port` flags. Not much (or anything?) has to be done here, except maybe move them out of the testing section of help and fix up their documentation.

This was quite the brain dump, so if you have any questions, don't hesitate to ask.

**Comment by SwartzCr** [comment]
PR at #3457
