### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

### ISSUE THREAD

**Issue by bazo** [certbot/certbot#3346]
hi,

when trying to run certbot i get this error

this is the full log
```
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.8.1', 'console_scripts', 'certbot')()
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 348, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2311, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2025, in load
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 18, in <module>
    from certbot import account
  File "/usr/lib/python2.7/dist-packages/certbot/account.py", line 15, in <module>
    from acme import messages
  File "/usr/lib/python2.7/dist-packages/acme/messages.py", line 4, in <module>
    from acme import challenges
  File "/usr/lib/python2.7/dist-packages/acme/challenges.py", line 10, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 43, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

```

debian 8. i updated and upgraded my packages, certbot installed today

i believe ssl v3 shouldn't be used due to poodle attack. 
can i fix this or workaround it somehow?

thank

**Comment by ldidry** [comment]
Could you try to install python-requests from jessie-backports? Seems to fix the problem (which I got today).

**Comment by bazo** [comment]
apt says that python-requests are already the newest version...

**Comment by ldidry** [comment]
From backports, really? Its version is 2.8.1 in backports and 2.4.3 in jessie. Also, you may have to install python-urllib3 from backports too.

**Comment by bazo** [comment]
the same
````
root@vps:~# apt-get install python-requests -t jessie-backports && apt-get install python-urllib3 -t jessie-backports
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-requests is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-urllib3 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
````

maybe those 10 not upgraded are the problem, but i have no idea what to do with them

**Comment by ldidry** [comment]
What are those not-upgraded packages? (`apt-get dist-upgrade -t jessie-backports`, then say no to upgrade).

Also, did you do an `apt-get update` before `apt-get install …`? 'Cause it's really strange, since it solved the bug for me…

**Comment by bazo** [comment]
yes I did apt-get update before i installed certbot, also before trying to install python-requests

the 10 packages are debhelper e2fslibs e2fsprogs ifupdown libpam-systemd libsystemd0 libudev1 neo4j-enterprise systemd udev

doesn't seem related to this issue

**Comment by ldidry** [comment]
> doesn't seem related to this issue

Nope, indeed.

What about the version of `python-openssl`? I have it from jessie-backports too.

**Comment by bazo** [comment]
nothing.

i even purged all the packages you mentioned, certbot too
installed them all again from backports
the error is still there

**Comment by ldidry** [comment]
Sorry, I can't help anymore, I don't know what could cause that 😞

**Comment by bazo** [comment]
ok, thanks for the help so far. will have to try the original client which i have lying around somewhere

**Comment by bmw** [comment]
Any thoughts about what could be going on here @hlieberman?

**Comment by bazo** [comment]
in the end, i used the original client installation from source. it updated itself to certbot and i could renew my domains. although i had to do it one by one, but that's another issue

**Comment by inglor** [comment]
This is a urllib3 library issue as noted by [this]. I manually patched the file and worked.

[this]: https://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue/29081240

**Comment by bmw** [comment]
Closing the issue as I believe this is resolved.
