### ISSUE TITLE
Error message for empty domain name is incorrect

### ISSUE THREAD

**Issue by ye** [certbot/certbot#3347]
In a recent commit that [Fix FQDN checks](https://github.com/certbot/certbot/commit/6156b452bcf7c924f12c334e7094ff5a9049ee37),
 the error message fails to address the case where domain name is an empty string. See below.

`--domain` is a CSV string, but the 2nd DNS name is parsed to be an empty string, which caused 
and error message `Requested domain  is not a FQDN because label  is too long.`. 

It would have been more logically to say `Requested domain "" is not a FQDN because label  is either empty or too long.`

The check it failed is here: https://github.com/certbot/certbot/blob/6156b452bcf7c924f12c334e7094ff5a9049ee37/certbot/util.py#L432

``` bash
$ docker run --rm -it --entrypoint bash quay.io/letsencrypt/letsencrypt:latest
root@4b80271cdd6c:/opt/certbot# certbot certonly \
>     --webroot \
>     --non-interactive \
>     --agree-tos \
>     --email test@test.com \
>     --webroot-path /var/lib/letsencrypt \
>     --domain www.example.com,,test1.example.com \
>     --no-verify-ssl \
>     --debug \
>    --test-cert
Requested domain  is not a FQDN because label  is too long.
```

**Comment by ye** [comment]
@pde I suppose I could help to fix this - any pointers for the contributing guidelines? Much appreciated!

**Comment by jpluimers** [comment]
Taken.

**Comment by ye** [comment]
@jpluimers by whom? Shouldn't this be mentioned so that an association can be established?

**Comment by jpluimers** [comment]
I've taken it (;

**Comment by bmw** [comment]
#3445 still needs a bit of work. Just commenting here to keep the issue up to date in case anyone else would like to take this issue.
