### ISSUE TITLE
File locking method

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#335]
We're creating a cert database (probably called `/etc/letsencrypt/certdb.json`), initially as a JSON file and maybe later with SQLite. The cert database is tracking certs that are under management of the Let's Encrypt client for both renewal and revocation purposes.

We need a file locking mechanism to exclude conflicting updates to this database by separate instances of the client or the renewer cron job. What is the best and safest way to do file locking from Python, ideally as portably as possible? Is the Python `lockfile` module reasonable?

**Comment by bmw** [comment]
I think this question is a bit outdated, but problems can certainly occur if the renewer and client are attempting to modify lineages at the same time. We should use something like the `lockfile` module to prevent against this problem.

**Comment by pde** [comment]
Closing in favour of #933
