### ISSUE TITLE
Warning message for low memory servers 

### ISSUE THREAD

**Issue by benileo** [certbot/certbot#3355]
I've ran into it a couple times where I'm installing a certificate on a tiny server. In my case it was Ubuntu 14.04, which still does not have the letsencrypt package (not sure if that is coming). 

It would be nice if `certbot-auto` printed a warning message before trying to install the Python packages (in this case it is cryptography that is failing to build). 

The message could be something like:
`Warning your system only contains 0.5 GB of memory which is less the recommended 2.0 GB, you may no be able to build the proper dependencies needed`. 

Just an idea..

**Comment by pde** [comment]
This is a good idea!

**Comment by surya-v** [comment]
Implemented the suggested check.

**Comment by pde** [comment]
Fixed by #3473
