### ISSUE TITLE
How to install if my web server is deployed as Docker?

### ISSUE THREAD

**Issue by sunshineo** [certbot/certbot#3360]
Hello,

I tried to do this myself for couple hours but did not success.
My web server is a haproxy docker image that I deployed through cloud.docker.com onto a physical machine I created at www.packet.net
What's the proper way to get a certificate to serve https?

The docker image allows set certificate through env variable only. So does this mean I must to obtain it manually?

Thank you!

**Comment by pde** [comment]
There's no single answer to this question. If you have a webroot directory behind your haproxy instance you could run Certbot using the [webroot plugin](http://letsencrypt.readthedocs.io/en/latest/using.html#webroot) and then taking the resulting cert and putting it in the environment variable.

Or you could customize your docker instance to use the [experimental Certbot haproxy plugin](https://code.greenhost.net/open/letsencrypt-haproxy).

**Comment by pde** [comment]
(I'd recommend asking on community.letsencrypt.org if you're still stuck)

**Comment by sunshineo** [comment]
Thank you for the response!
