### ISSUE TITLE
"LE probably shut down unexpectedly"

### ISSUE THREAD

**Issue by ChrisHoman** [certbot/certbot#3362]
Tried running LE on Centos 6 - Apache 2.4.3

Installed using these root commands:

```
yum install epel-release
wget https://dl.eff.org/certbot-auto
chmod a+x certbot-auto
```

When I run `./certbot-auto --apache` I run through these dialogs:

![screen shot 2016-08-01 at 15 26 25](https://cloud.githubusercontent.com/assets/2571694/17297175/85b186f6-57fc-11e6-8170-0149c17bc0d0.png)
![screen shot 2016-08-01 at 15 26 43](https://cloud.githubusercontent.com/assets/2571694/17297182/88e49ebc-57fc-11e6-97cf-2702a7f09ee2.png)
![screen shot 2016-08-01 at 15 26 58](https://cloud.githubusercontent.com/assets/2571694/17297192/90aa8eea-57fc-11e6-8dcf-491685f7db3b.png)
And I get this error: 

An unexpected error occurred:  
IOError: [Errno 2] No such file or directory: '/etc/httpd/conf.d/le_tls_sni_01_cert_challenge.conf'
Please see the logfiles in /var/log/letsencrypt for more details.

The log file is attached here:

[letsencrypt.log.txt](https://github.com/certbot/certbot/files/394038/letsencrypt.log.txt)

**Comment by pde** [comment]
@ChrisHoman Do you by any chance have Apache config files that contain multiple vhosts per filename?

**Comment by pde** [comment]
(Either way, would you be able to post your Apache config?)

**Comment by ChrisHoman** [comment]
Here's the httpd.conf

[httpd.conf.txt](https://github.com/certbot/certbot/files/398103/httpd.conf.txt)

**Comment by woeitje** [comment]
I get the same error using letscrypt in combination with Apache/DirectAdmin on CentOS7.

**Comment by mrwigster** [comment]
I'm getting this same issue on CentOS and apache (Media Temple VPS).

**Comment by woeitje** [comment]
I managed to work around this issue by generating the certificates manually:
`certbot certonly --webroot-path /home/USER/domains/DOMAIN/public_html/ -d DOMAIN -d www.DOMAIN`
and installed the certificates myself and symlinked them to the 
/etc/letsencrypt/live/DOMAIN/* files.
This is not directly related to the issue but can help people that end up here in this thread.

**Comment by mrwigster** [comment]
I've also tried creating domain.com.conf which didn't solve the issue.

**Comment by bmw** [comment]
The Apache plugin seems to raise this error when the challenge directory doesn't exist. On Red Hat systems, the default challenge directory is `/etc/httpd/conf.d`. We should improve the error message and do a better job choosing the default if we're getting it wrong on some systems.

For those having the issue, how did you install Apache? The default server root of Apache is `/etc/httpd` on Red Hat systems. As a workaround, you can specify the paths used on the command line. `--apache-challenge-location` can be used to specify the path causing this error. A full listing of configurable paths can be found by running `certbot --help apache`.

**Comment by mrwigster** [comment]
For reference:
My cPanel/WHM VPS is using apache/conf in this location:
/usr/local/apache/conf/httpd.conf

Is there a way to manually point to this location for the vhosts in the `./cerbot-auto` command?

**Comment by bmw** [comment]
Yep. Run `./certbot-auto --help apache` and you can see all configurable flags and what their defaults will be on your system.

**Comment by qf19910623** [comment]
I have got the same error. The Apache I use is not pre-installed . I have uninstalled it and install one by myself.My Apache directory is /usr/local/apache

**Comment by ThibauldNuyten** [comment]
What is this 'challenge' and where do I find where it's supposed to be? apache_vhost_root is set to /etc/httpd/conf.d but that's not a path or file.

**Comment by DamienDaco** [comment]
I also had this issue, using CentOS7 and httpd24 from Software Collections.

> IOError: [Errno 2] No such file or directory: '/etc/httpd/conf.d/le_tls_sni_01_cert_challenge.conf'

Here's very simple fix, just create the missing directory:
`mkdir -p /etc/httpd/conf.d/`

The certbot installer should be happy now.

**Comment by bmw** [comment]
Somewhat related #3967.

**Comment by alexweissman** [comment]
I'm experiencing this same problem on a Ubuntu 14.04 server, during my auto-renewal task.  It's actually shutting down Apache and then not being able to restart it!  I experienced several hours of downtime this morning because of this :-/

In my Apache error log:

```
[Thu Jun 29 06:19:08.515504 2017] [mpm_prefork:notice] [pid 19898] AH00171: Graceful restart requested, doing restart
apache2: Syntax error on line 222 of /etc/apache2/apache2.conf: Could not open configuration file /etc/apache2/le_tls_sni_01_cert_challenge.conf: No such file or directory

[Thu Jun 29 10:34:20.066181 2017] [ssl:warn] [pid 25333] AH02292: Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Thu Jun 29 10:34:20.537739 2017] [ssl:warn] [pid 25334] AH02292: Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Thu Jun 29 10:34:20.537825 2017] [core:warn] [pid 25334] AH00098: pid file /var/run/apache2/apache2.pid overwritten -- Unclean shutdown of previous Apache run?
[Thu Jun 29 10:34:20.566082 2017] [mpm_prefork:notice] [pid 25334] AH00163: Apache/2.4.7 (Ubuntu) OpenSSL/1.0.1f configured -- resuming normal operations
[Thu Jun 29 10:34:20.566130 2017] [core:notice] [pid 25334] AH00094: Command line: '/usr/sbin/apache2'
```

The restart attempt happened at 6:19 (when my cron task is scheduled), and 10:34 is when I was alerted of the downtime and restarted Apache manually.
