### ISSUE TITLE
Allow certbot client to pass GET path for acme-challenge

### ISSUE THREAD

**Issue by jovobe** [certbot/certbot#3368]
In my setup the web folder is a subfolder of the website root. All requests send to example.domain.com are passed to a script. To access a static file only files in the web folder are served to users. Here is a little example:

- root of website: `/var/www/example` accessible over http://example.domain.com, but `/var/www/example/test.txt` is not accessible, because "test.txt" is passed to the framework.
- root of static files: `/var/www/example/static` is accessible over http://example.domain.com/static and `/var/www/example/static/test.txt` (http://example.domain.com/static/test.txt) will be served to clients.

For this reason I suggest an option for certonly plugin to take a get-path argument so I can set `/var/www/example/static` as webroot and the acme-challange will go to http://example.domain.com/static/.well-known/acme-challenge...
For example like: `certbot-auto certonly --webroot -w /var/www/example/static -d example.domain.com -p static` where "-p static" says, that the acme-GET call should go to "example.domain.com/static/..."

**Comment by bmw** [comment]
Certbot is an [ACME](https://github.com/ietf-wg-acme/acme) client and ACME dictates that `.well-known/acme-challenge` must be used as the prefix. Making such a plugin would not work at this time because no ACME servers allow you to choose an alternate prefix.

This is outside of the scope of EFF's ACME client. If you would like to see this changed, feel free to reach out to the IETF working group. Alternatively, configure your webserver so requests to `.well-known/acme-challenge` are handled in a way that is compatible with ACME.

**Comment by cpu** [comment]
To expand briefly on @bmw's answer from the perspective of the boulder team: It's unlikely that the ACME working group or any ACME servers will be able to offer support for an arbitrary validation directory. 

The CABF baseline requirements for domain validation were recently updated with [Ballot 169](https://cabforum.org/pipermail/public/2016-August/008184.html) to specifically tighten the options for what is/isn't allowed with domain validation. Section `3.2.2.4.6`, "Agreed-Upon Change to Website" now says that only `/.well-known/pki-validation` or an IANA registered path for the purpose of domain-validation can be used for DV.

We are already going to need an IANA registration for `/.well-known/acme-challenge`, we definitely won't be able to use a URL specified by the user of the ACME client, sorry!

**Comment by jovobe** [comment]
Thanks for the answers and the hint @bmw. I solved it by creating an alias to .well-known.
