### ISSUE TITLE
Select from challenge types prompt

### ISSUE THREAD

**Issue by theel0ja** [certbot/certbot#3374]
People is using CloudFlare, Incapsula, etc. and them can't get Let's Encrypt without [fumbling](https://community.letsencrypt.org/t/how-to-get-a-lets-encrypt-certificate-while-using-cloudflare/6338), so we should add prompt or `--advanced`, etc. flags for getting certbot-auto for reverse proxies (webroot method).

Like this:

```
Please choose challenge type.
-------------------------------------------------------------------------------
1: Normal - Works for basic configurations
2: Advanced - Works also for reverse proxies
-------------------------------------------------------------------------------
```

The Normal is the IP-challenge (**tls-sni**) and Advanced is **webroot** file challenge.

**Comment by bmw** [comment]
I don't like the characterization of `normal` vs. `advanced`, but we could certainly make using Certbot in this way easier.

`certbot --webroot --installer apache` is currently the most succinct way to do what you want (use the `webroot` plugin for authentication and the `Apache` plugin for installation). We could potentially shorten this just down to just `certbot --webroot`, but the thought was that if people are manually specifying `webroot`, we're not sure whether or not they want to use `Apache` for automatically installation.

We could also potentially add support for the `http-01` challenge (the one that `webroot` uses) to the Apache plugin. We could even make it the preferred challenge type for Apache to get around these issues, but we'd have to do a lot of testing to make sure we're not causing more problems with this change.
