### ISSUE TITLE
Let's Encrypt Certificate Manager

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#338]
We should have a Let's Encrypt Certificate Manager tool that helps users understand what keys and certs they currently have in `/etc/letsencrypt` (and the revocation/expiry/installation/autorenewal status of each of them), as well as initiating operations like
- enable/disable autorenewal
- adjust choice of installer to be used for autorenewal
- attempt to renew now
- attempt to revoke now
- import (non-LE-managed key and cert into the local LE cert store)
- export (obtain a copy of a key, cert, and chain for use elsewhere)
- purge (remove from LE management and attempt to securely delete key material)
- merge/split certs (by issuing new successor certs)

Some or all of these operations might also be available from the client using particular command-line options, but there should probably be a unified interactive interface to do them, which can be separate from the client.

I'm marking this as a 2.0 feature, but it would probably be good to have at least a rudimentary version for 1.0, or a cookbook explaining to sysadmins how to perform each of these tasks.

**Comment by schoen** [comment]
Other features (from my duplicate issue #408):

* rekeying a cert (obtaining a single successor cert with a different subject public key)
* adding or subtracting subject DNS names (obtaining a single successor cert with more or fewer or different subject names)

**Comment by bmw** [comment]
Currently, the best way to determine what certificates you have is to examine `/etc/letsencrypt`.A certificate manager would help this.

**Comment by bmw** [comment]
Just saw [this](https://youtu.be/Gas_sSB-5SU?t=2m25s) where we had a working certificate manager for revocation. Not sure if there's any code we can salvage there.

**Comment by ohemorange** [comment]
Perhaps, for 0.10.0, we add a list command that lists each cert and some information about it, such as the domains it includes, or its expiry date.

**Comment by jdkasten** [comment]
@bmw regarding the demo link.

I had some working code that was a more advanced version of the demo in this very stale (year old) branch.  https://github.com/certbot/certbot/tree/cert_manager
Here is a link to the specific "manager" code. https://github.com/certbot/certbot/blob/cert_manager/letsencrypt/cert_manager.py
IIRC, it needed some polish and more unittests (I got sidetracked in the process).

It allowed you to see all of your certificates along with their respective status.  The menu additionally allowed you to see more info, revoke and delete selected certificates.

Sorry for the late reply.

**Comment by bmw** [comment]
@jdkasten, no problem about the delay. We unfortunately haven't got around to working on this issue until recently.

Thanks for the info. I believe you told me about the `cert_manager` branch before. I'll make sure @ohemorange takes a look to see what we can reuse there.

**Comment by bmw** [comment]
We should split this into separate issues we care about.

**Comment by bmw** [comment]
Assigning to Erica to break this into separate issues.

**Comment by ohemorange** [comment]
Added the ones that still make sense and haven't yet been implemented to Wishlist.
