### ISSUE TITLE
--{cert,key,chain,fullchain}-path flags need better descriptions

### ISSUE THREAD

**Issue by Ninos** [certbot/certbot#3386]
Following path-params are not working on `certonly` renew/creation/...:
- key-path
- cert-path
- chain-path
- fullchain-path

I've tried following:

```
/usr/local/sbin/certbot-auto certonly --no-self-upgrade --text --agree-tos --non-interactive --verbose --email my@email.tld --webroot --webroot-path /var/www/virtual/LetsEncrypt --rsa-key-size 2048 --domains test.example.tld --domains www.test.example.tld --cert-path /etc/letsencrypt/live/prefix_test.example.tld/cert.pem --key-path /etc/letsencrypt/live/prefix_test.example.tld/privkey.pem --fullchain-path /etc/letsencrypt/live/prefix_test.example.tld/fullchain.pem --chain-path /etc/letsencrypt/live/prefix_test.example.tld/chain.pem
```

and also following:

```
/usr/local/sbin/certbot-auto certonly --no-self-upgrade --text --agree-tos --non-interactive --verbose --email my@email.tld --webroot --webroot-path /var/www/virtual/LetsEncrypt --rsa-key-size 2048 --domains test.example.tld --domains www.test.example.tld --cert-path /etc/letsencrypt/live/prefix_test.example.tld/ --key-path /etc/letsencrypt/live/prefix_test.example.tld/ --fullchain-path /etc/letsencrypt/live/prefix_test.example.tld/ --chain-path /etc/letsencrypt/live/prefix_test.example.tld/
```

See doc:
https://certbot.eff.org/docs/using.html#command-line-options

**Comment by bmw** [comment]
Those four path values cannot be used in that way, although that's not particularly clear from our listing of command line options. Can you tell me more about what you're trying to do?

* Are you trying to create a certificate containing only the domain `www.test.example.tld` and save it in a directory named `prefix_test.example.tld`?
* Are you trying to add `www.test.example.tld` to the certificate saved in `prefix_test.example.tld`? If so, do you have any other certificates with the names `prefix_test.example.tld` or `www.test.example.tld`?

**Comment by Ninos** [comment]
Hey there,
problem is following:
1. You create a certificate for `domain.tld`
2. Certs will be saved under `/etc/letsencrypt/live/domain.tld/`
3. You create another certificate for `domain.tld` `www.domain.tld` b another customer
4. Certs will be saved under `/etc/letsencrypt/live/domain.tld-0001/`

Problem here is following:
For our open-source iscp (i-mscp.net) we've created a plugin for admins to give possiblity for customers to enable/disable Let's Encrypt for each of their domain. Let's Encrypt is implemented into the infrastructure of imscp via plugin (for renew and revoke we use the certbot script).
Now to the problem. If certificates are saved under `/domain.tld-0001/` we get an error or invalid (old) certificates, because we always asking for `/etc/letsencrypt/live/domain.tld/`. So here we want to enforce usage of the folder `/etc/letsencrypt/live/domain.tld/`.

**Comment by bmw** [comment]
Sorry for the delay in response. I got pulled into working on some other things.

In the 4 step scenario you outlined above, you can use the `--expand` option to add `www.domain.tld` to the certificate under `/etc/letsencrypt/live/domain.tld` (make sure `--duplicate` isn't set on the command line or in a Certbot config file).

While this solves the problem of adding a domain to a certificate, it currently isn't possible to remove a name from a lineage (see #2071). Similarly, if the user never requests a cert for `domain.tld` and only requests subdomains, there is currently no way to use `/etc/letsencrypt/live/domain.tld` (see #2128).

We certainly want to change this in the future, but currently this isn't possible. The two solutions I see in the meantime are:

1. Submit a PR! These features are in high demand and we will certainly review a PR adding support.
2. After running Certbot, move/fix up the files using another script.

If you decided to use an external script, it would have to:
* Move the directory `/etc/letsencrypt/archive/www.domain.tld`
* Fix the symlinks in `/etc/letsencrypt/live/www.domain.tld`
* Move the directory `/etc/letsencrypt/live/www.domain.tld`
* Fix the paths at the top of `/etc/letsencrypt/renewal/www.domain.tld`
* Move the file `/etc/letsencrypt/renewal/www.domain.tld.conf`

**Comment by Ninos** [comment]
@bmw thx for feedback. So with `--expand` no `/etc/letsencrypt/live/domain-tld-0001/` folder is created anymore, certs in `/etc/letsencrypt/live/domain.tld/` will be replaced instead, right? This would solve our problem...

**Comment by bmw** [comment]
I believe you have `--duplicate` set somewhere, either on the command line or in a [configuration file](https://certbot.eff.org/docs/using.html#configuration-file). That would cause the behavior you're seeing, even with the `--expand` flag.

This will work for adding domains, but there is currently no way to remove a domain as I mentioned above.

**Comment by Ninos** [comment]
Perfect description. Now I understood. Strange that expand did not worked. I'll have a look into my config files, surely somewhere is an entry. But I think #3395 will more solve my problems to find correct folder

**Comment by bmw** [comment]
After talking through this with you, I think the only thing here we don't already have an issue for is the bad descriptions of the `--*-path` flags. With this in mind, I'll change the title of the issue to track this problem. If you think there is more going on here that I'm overlooking, please let me know.

**Comment by SwartzCr** [comment]
I think this is relevant for @pconrad-fb

**Comment by pconrad-fb** [comment]
Finally getting to this one. The descriptions are indeed a little cryptic, partly because we haven't defined "chain" anywhere. What do the four paths mean?

**Comment by SwartzCr** [comment]
the four paths would be:
key-path
cert-path
chain-path
fullchain-path
Which are the files that certbot stores in /etc/letsencrypt/live/domain_name/ after a successful validation

**Comment by SwartzCr** [comment]
I believe this is resolved by https://github.com/certbot/certbot/pull/4137, so I will close this issue
