### ISSUE TITLE
Register –update-registration error 

### ISSUE THREAD

**Issue by stel-0** [certbot/certbot#3391]
Trying to change the account recovery and expiry notification e-mail I get the following error:

Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf]
Please see the logfiles in /var/log/letsencrypt for more details.
Didn't find any clue at the log files.

**Comment by bmw** [comment]
This is an instance of letsencrypt/boulder#2102 which is on the server side. There's an open PR for the issue and it should be resolved soon.

In the meantime, you should be able to work around the problem by changing the https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf URLs in:
```
/etc/letsencrypt/account/acme-v01.api.letsencrypt.org/directory/<hash>/regr.json
```
to the https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf URL.
