### ISSUE TITLE
Define lineage_path variable for pre_hook and post_hook

### ISSUE THREAD

**Issue by Ninos** [certbot/certbot#3395]
Hey there,
is it possible to define the lineage_path variable for the pre_hook and post_hook if available?
### Reason

I am running following command on renewal:
`--renew-hook "echo $RENEWED_LINEAGE > /tmp/letsencrypt-plugin-renewed-lineage"`
### Background Information

The `--renew-hook` is only triggered when a new cert was created, not if a certificate is not due renewal.
### Problem

I need the lineage_path also if the certificate is not due renewal.
#### Reason

For our open-source iscp (i-mscp.net) we've created a plugin for admins to give possiblity for customers to enable/disable Let's Encrypt for each of their domain. Let's Encrypt is implemented into the infrastructure of imscp via plugin (for renew and revoke we use the certbot script). It can be possible that sometimes a customer created a cert with certbot before using our plugin (already happened some times), so certificate is not due renewal. In this scenario we must also copy the certificate to the imscp db.
Before we used hardcoded variables e.g. `/etc/letsencrypt/live/domain.tld/` to get the certificates. But because of following "bugs" #3386 #2128 this is not really possible. So we want to use a variable returned by letsencrypt. The `$RENEWED_LINEAGE` variable is perfect for that, but only used in some scenarios.

**Comment by bmw** [comment]
`--pre-hook` and `--post-hook` are also only called when a certificate is due for renewal. Additionally, having a `$RENEWED_LINEAGE` variable for the pre and post hooks doesn't really make sense. `certbot renew` renews all certificates that are due for renewal, including multiple lineages. pre and post hooks are meant to run once before any certificates are renewed and once after all certificates are renewed respectively. Because these hooks are for the entire run and not individual lineages, there isn't a single value for the `$RENEWED_LINEAGE` variable.

If you simply want to know if the user already has a lineage, why can't you just run `ls /etc/letsencrypt/live`?

**Comment by Ninos** [comment]
Oh ok understand.

>If you simply want to know if the user already has a lineage, why can't you just run ls /etc/letsencrypt/live?

Because it's possible that a user has domain.tld-0001 domain.tld-0002... So I don't know which certs are relevant for me. I have another idea, is it possible to add a command which returns the lineage_path of specific domains.
e.g.
```
certbot-auto lineage_path --domains domain.tld --domains www.domain.tld
```

or more specific returning most of all informations you can find in the /etc/letsencrypt/renewal/domain.tld*.conf configuration file.
```
certbot-auto info --domains domain.tld --domains www.domain.tld
```

Otherwise I need to parse all configuration files by myown to get the correct lineage_path.

**Comment by bmw** [comment]
> Because it's possible that a user has domain.tld-0001 domain.tld-0002... So I don't know which certs are relevant for me.

Can you explain what makes the certificate relevant for you? Is it just the domains it contains? Trying to help you find a workaround until we have a more permanent solution built into the client.

Currently, what we're calling "certificate management" with Certbot needs some work. This is one of the main things we want to improve before we release Certbot 1.0. @schoen, use cases like these is something we should think about when designing the next release.

**Comment by Ninos** [comment]
ATM we're generating our certificates (only domain.tld & www.domainlt.d) with the certbot script. After that we take them from path `/etc/letsencrypt/live/domain.tld/`. Problem here, path can also be something like `/etc/letsencrypt/live/domain.tld-0001/`. Then we get an old cert instead of the correct one. So we want to get the correct path via a command line tool e.g. get path for domains xyz.

Why we cannot use the `--renew-hook`? Just simple: sometimes we also try to create/renew certs if a valid cert already exists (user created one by its own in past, instead of using our plugin), so then the hook is not triggered.

Hope it's clear now, otherwise just ask :)

**Comment by Ninos** [comment]
@bmw can you may tell me the roadmap for the planned certificate management? :-)

**Comment by pde** [comment]
Hi Ninos, the current `git master` branch, and the forthcoming 0.10.0 release, include a `certbot certificates` command that should let you easily tell the correct directory for your certs.

Additionally, we could implement an equivalent to `RENEWED_LINEAGE` for `--pre-hook` and `--post-hook`.  One complication is that if you run `certbot renew`, there could actually be multiple lineages renewed on this run, and that would need to be conveyed to the hook script.

Passing a list of directories out to a script would be hokey, maybe we could escape any spaces and shell meta characters in filenames to make it safe?

We could probably do this with two separate sets of variables, one for the lineages that are actually being renewed right now, and one for the ones that are simply being examined and possibly not renewed.

For me, the question is: do enough people need this that it's worth the time and effort to code it correctly.

**Comment by pde** [comment]
> Passing a list of directories out to a script would be hokey, maybe we could escape any spaces and shell meta characters in filenames to make it safe?

This is looking harder than I thought:
```
pde@host:~/certbot/certbot$ mkdir /tmp/"a thing"
pde@host:~/certbot/certbot$ mkdir /tmp/"b thing"
pde@host:~/certbot/certbot$ export DIRS="/tmp/a\ thing /tmp/b\ thing"
pde@host:~/certbot/certbot$ for dir in $DIRS ; do ls -la "$dir" ; done
ls: cannot access /tmp/a\: No such file or directory
ls: cannot access thing: No such file or directory
ls: cannot access /tmp/b\: No such file or directory
ls: cannot access thing: No such file or directory
```

**Comment by pde** [comment]
Moving to 0.11.0 since it's not yet clear how to do this.

**Comment by Ninos** [comment]
@pde what's possible with the command `certbot certificates`? Currently I cannot find any documentation :/

**Comment by pde** [comment]
@Ninos that's because it's not released yet. But you can try it out by [running the latest code from git](https://certbot.eff.org/docs/contributing.html#running-a-local-copy-of-the-client) and doing `certbot certificates` (or `certbot --help certificates`).

The `certificates` command will probably get more features in future releases, eg #3907 #3908

**Comment by pde** [comment]
Also it will probably support some machine readable formats (JSON and one-line greppable) for convenience.

**Comment by Ninos** [comment]
Sounds nice. Thx for implementing such commands :)

**Comment by bmw** [comment]
@Ninos, does our current `certificates` command work for you here? We're considering different ways to control this output (see #3909, #3910, #4238), but parsing the current output isn't too bad. It looks like:
```
$ sudo certbot certificates
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Found the following certs:
  Certificate Name: example.org
    Domains: example.org
    Expiry Date: 2017-06-07 17:09:00+00:00 (INVALID: TEST_CERT)
    Certificate Path: /etc/letsencrypt/live/example.org/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/example.org/privkey.pem
  Certificate Name: example.net
    Domains: example.net www.example.net
    Expiry Date: 2017-06-07 19:38:00+00:00 (INVALID: TEST_CERT)
    Certificate Path: /etc/letsencrypt/live/example.net/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/example.net/privkey.pem
-------------------------------------------------------------------------------
```
I'm just trying to determine what additional action is needed here.

**Comment by Ninos** [comment]
Hey @bmw,
yes the command is fine. I get all needed informations. The only problem: If you have lots of certs the list gets very long. I also recomment something like that:
`certbot certificates example.tld www.example.tld` (just receiving relevant certs)

**Comment by ohemorange** [comment]
Ninos: you can specify a single cert with `certbot certificates --cert-name example.tld` to get information about a single certificate.
