### ISSUE TITLE
unable to execute 'swig': No such file or directory

### ISSUE THREAD

**Issue by nagedoer** [certbot/certbot#34]
Hello Lets-encrypt,
While installing it in my ubuntu VPS i am getting the following error. 
![letusencrypt](https://cloud.githubusercontent.com/assets/9193287/5120693/a22468f0-70ac-11e4-9829-9c2f25303d8f.png)

**Comment by dookdick** [comment]
Thanks jdkasten for your tips on re-installation of swig. Absolutely work for me!

**Comment by gurjarr587** [comment]
Or you can try this in command line:
sudo apt-get install swig

**Comment by NadunKulatunge** [comment]
> I am guessing you didn't install it correctly. I would try to `sudo apt-get install swig` again.

If you are on **MacOSX** then, try this command.

    brew install swig

**Comment by darshan-mandhane** [comment]
You need to first run if brew is of older version
`git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow`
and then run 
`brew install swig`
