### ISSUE TITLE
domain names was not valid, has an  _ (underscore) in the name

### ISSUE THREAD

**Issue by SergioMartinezP** [certbot/certbot#3401]
I received an error saying Requested domain oai_pmh.repositorionacionalcti.mx is not a FQDN, But I got the cert for repositorionacionalcti.mx, www.repositorionacionalcti.mx, so I think that the **_** is the character that raised the error, even though is a valid DNS, running on version certbot 0.8.1

**Comment by cowlicks** [comment]
I'll chime in here since no one from Lets Encrypt (LE) has. I think that while certbot allows for you to attempt to use any FQDN, it is up to each certificate authority (CA) to decide what FQDN's are allowed. In this case LE (the CA), does not allow underscores in domain names.

**Comment by cowlicks** [comment]
Also can anyone point me to where in LE's policy this is stated? I think it is in here somewhere https://letsencrypt.org/repository/

**Comment by cpu** [comment]
@cowlicks I'm not sure off-hand if we specify this anywhere in a policy document (e.g. in our Certificate Practice Statement). You can see where this is [enforced programmatically](https://github.com/letsencrypt/boulder/blob/master/policy/pa.go#L104:L109) in the Policy Authority component of Boulder.

**Comment by cowlicks** [comment]
I suppose this is closeable then, since certbot can't resolve the issue for @SergioMartinezP . 

You can take this up with LE.

**Comment by SergioMartinezP** [comment]
thanks a lot, I'll try to see it with LE, maybe there is a very good reason to do that.

**Comment by SergioMartinezP** [comment]
I assumed that because my DNS software accepted that name it was a preferred one, the [RFC 1034](https://tools.ietf.org/html/rfc1034) in section 3.5 specifies what a Preferred name syntax is, and according to that this restriction is appropriate.

**Comment by bmw** [comment]
If you haven't seen letsencrypt/boulder#1225, one of the Let's Encrypt engineers explained their reasoning for not allowing underscores in domain names.

**Comment by cowlicks** [comment]
So basically LE requires domain names be valid hostnames.
