### ISSUE TITLE
following guide to lets encrypt gives an error - "Error in parsing the file....

### ISSUE THREAD

**Issue by rpilman** [certbot/certbot#3402]
To whom to may concern: 

   I've googled on this for a few hours, and first off I'm very new to ubuntu and cmd lines linx systems.. But,  I'm unable to find the file where I need to fix this so I can get an SSL for my website forum.eveminions.com.  Please help. 

The error I get is The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/apache2/mods-enabled/alias.conf', u'Syntax error'),)  

I ran a syntax check and it said Syntax OK - Please help me get this fixed as I'd  like to secure my website. 

My OS is ubuntu 16.04 hosted by digital ocean 
the guide I followed is https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-14-04

Please help

**Comment by joohoi** [comment]
Could you post the contents of /etc/apache2/mods-enabled/alias.conf so we can investigate further. Seems like something inside it confuses certbot

**Comment by rmcginnis** [comment]
Hi @joohoi -  Attached is the alias.conf


[alias.conf.txt](https://github.com/certbot/certbot/files/416774/alias.conf.txt)

**Comment by rmcginnis** [comment]
Any updates ? @joohoi

**Comment by joohoi** [comment]
The file looks completely normal. Could you post also the contents of /var/log/letsencrypt/letsencrypt.log ?

Unrelated; you should check out https://certbot.eff.org/ for up to date instructions to get you running. That article you were following was seriously outdated, and also you are running distro which has certbot in package management already.

**Comment by rmcginnis** [comment]
Here's the file from /var/log/letsencrypt 

[letsencrypt.log.zip](https://github.com/certbot/certbot/files/417126/letsencrypt.log.zip)

**Comment by rmcginnis** [comment]
i went to the certbot.eff.org  - and when i got to  letsencrypt --apache  it gave this error 

ronnie@forum:~$ letsencrypt --apache
An unexpected error occurred:
IOError: [Errno 13] Permission denied: '/var/log/letsencrypt/letsencrypt.log'
Please see the logfile 'letsencrypt.log' for more details.
ronnie@forum:~$

[letsencrypt.log.txt](https://github.com/certbot/certbot/files/417130/letsencrypt.log.txt)

**Comment by joohoi** [comment]
You should run letsencrypt --apache with sudo to give it permissions to write the needed files.

To the original issue, logfile indicates that there's parsing error in another file, perhaps you could post its contents as well.

'''PluginError: ('There has been an error in parsing the file (%s): %s', u'/etc/apache2/sites-available/eveminions', u'Syntax error')'''

**Comment by rmcginnis** [comment]
Hey @joohoi - 

     I ran it in this order  according to https://certbot.eff.org and selecting Apache and OS as ubuntu 16.04

```
sudo apt-get install python-letsencrypt-apache 
```

Then after it installed everything I then ran this
```
letsencrypt --apache
```

Are you saying I should have ran ?
```
sudo letsencrypt --apache
```

Here's the file you requested for the error 
```
PluginError: ('There has been an error in parsing the file (%s): %s', u'/etc/apache2/sites-available/eveminions', u'Syntax error')
```

[eveminions.txt](https://github.com/certbot/certbot/files/417351/eveminions.txt)

**Comment by rmcginnis** [comment]
I ran sudo letsencrypt --apache and got this 

```
ronnie@forum:~$ sudo letsencrypt --apache
[sudo] password for ronnie:
The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/apache2/sites-available/eveminions', u'Syntax error'),)
ronnie@forum:~$
```

**Comment by joohoi** [comment]
Try fixing the broken comment line in eveminions configuration file:

```
Possible values include debug, info, notice, warn, error, crit, alert, emerg
```

To:

```
# Possible values include debug, info, notice, warn, error, crit, alert, emerg
```

**Comment by rmcginnis** [comment]
I changed it to what you suggested and when doing sudo letsencrypt --apache   it gives 

The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/apache2/sites-available/eveminions', u'Syntax error'),)
ronnie@forum:~$

**Comment by domcleal** [comment]
The last line of the file also has invalid syntax, it should be:

    </VirtualHost>

to close it.

**Comment by rmcginnis** [comment]
and the first line is ok  ? <VirtualHost *:80>

**Comment by domcleal** [comment]
Yes, that's correct.

**Comment by rmcginnis** [comment]
Ok   i ran sudo letsencrypt --apache  and now get this lol in the box that popped up  i selected forum.eveminions.com 

```
Failed authorization procedure. forum.eveminions.com (tls-sni-01): urn:acme:error:tls :: The server experienced a TLS error during domain verification :: Failed to connect to 104.18.38.77:443 for TLS-SNI-01 challenge

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: forum.eveminions.com
   Type:   tls
   Detail: Failed to connect to 104.18.38.77:443 for TLS-SNI-01
   challenge

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   you have an up-to-date TLS configuration that allows the server to
   communicate with the Let's Encrypt client.
ronnie@forum:~$
```

**Comment by rmcginnis** [comment]
I think I fixed it...  it says congrats  and  that i should test the https site   at a very long address lol

**Comment by rmcginnis** [comment]
when I go to forum.eveminions.com  - it's not rewriting/redirecting to https://forum.eveminions.com  -   forum.eveminions.com is now ssl certified =]  but how do i get it to go to https://  is someone types http://forum.eveminions.com or forum.eveminions.com

**Comment by rmcginnis** [comment]
also when going to the next step of doing the renew dry run I get this 

```
root@forum:~# letsencrypt renew --dry-run
Processing /etc/letsencrypt/renewal/forum.eveminions.com.conf
2016-08-15 10:53:44,070:WARNING:letsencrypt.client:Registering without email!
2016-08-15 10:53:44,893:WARNING:letsencrypt.cli:Attempting to renew cert from /etc/letsencrypt/renewal/forum.eveminions.com.conf produced an unexpected error: Missing command line flag or config entry for this setting:
Please read the Terms of Service at https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf. You must agree in order to register with the ACME server at https://acme-staging.api.letsencrypt.org/directory

(You can set this with the --agree-tos flag). Skipping.
** DRY RUN: simulating 'letsencrypt renew' close to cert expiry
**          (The test certificates below have not been saved.)

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/forum.eveminions.com/fullchain.pem (failure)
** DRY RUN: simulating 'letsencrypt renew' close to cert expiry
**          (The test certificates above have not been saved.)
1 renew failure(s), 0 parse failure(s)
root@forum:~#
```

**Comment by domcleal** [comment]
> so, I may have fixed the re-direct but not sure.. in chrome when i go to https://forum.eveminions.com it shows all sort of errors in the console
> 
> 2016-08-15_10-43-10

These errors are because the page contains lots of references to `http:`. You may need to reconfigure your forum software to use the HTTPS URL for the URL of the website.

**Comment by hvanmegen** [comment]
This config of mine is also giving me issues..
[mydomain.com.conf](https://github.com/certbot/certbot/files/804043/mydomain.com.conf.txt)

**Comment by domcleal** [comment]
@hvanmegen could you create a new issue please? I don't think your issue is the same as the above questions, best not to hijack this thread.

**Comment by joohoi** [comment]
Is this issue still valid @rpilman ?

**Comment by joohoi** [comment]
Looks like it's not.
