### ISSUE TITLE
Experimental support on gentoo auto-installs packages

### ISSUE THREAD

**Issue by SwartzCr** [certbot/certbot#3408]
reportd by @mstrache in #3319 - emerge doesn't use the --ask flag when installing system packages:

> Btw, nice job automatically calling emerge to install missing dependencies. Only one thing: it would be nice if you run emerge --ask ... to give the user the chance to review dependencies and cancel the process. As a gentoo user I like to have control over what packages are installed (it's just a gentoo thing).

@mstrache would you be willing to update the code to use the right flags? The gentoo bootstrap script is defined here: https://github.com/certbot/certbot/blob/master/letsencrypt-auto-source/pieces/bootstrappers/gentoo_common.sh
and should use the yes flag as specified here: https://github.com/certbot/certbot/blob/master/letsencrypt-auto-source/letsencrypt-auto#L191

**Comment by mstrache** [comment]
Change committed. I generally would recommend to use `local` to declare variables inside functions. It prevents nasty side effects from recurring variable names.

**Comment by SwartzCr** [comment]
Not only did we merge a change to ask before bootstrapping, but we're now installable via emerge, so I am closing this
