### ISSUE TITLE
certificate issue problem with www and non-www

### ISSUE THREAD

**Issue by darkworks** [certbot/certbot#3414]
i found one issue that certbot issue certificate only to specific domain , like  github.com      www.github.com ... i mean www and non-www are treated differently

so it will be good when certbot issue certificate it works for bot www and non-www 

like    

>  *.github.com

**Comment by bmw** [comment]
Well we can't issue for `*.github.com` as no ACME servers yet support wildcards (see this [thread](https://community.letsencrypt.org/t/please-support-wildcard-certificates/258)). Automatically making the certificate cover both `example.com` and `www.example.com` is covered in #363.

If you think there is something else here I'm missing, please comment and I'll reopen.

**Comment by darkworks** [comment]
my site is giving me problem :: https://www.w3tools.xyz/domain-into-ip/

ok with out www :: https://w3tools.xyz/domain-into-ip/

that why i reported it :(

**Comment by bmw** [comment]
@darkworks, are you still having problems with this? I suspect it has to do with your DNS/server configuration. Probably the best place for that kind of help is https://community.letsencrypt.org, but I can try to help if you'd like.

**Comment by darkworks** [comment]
its fixed now :) 

thanks
