### ISSUE TITLE
Changelog information is not discoverable (not in README, no longer in docs)

### ISSUE THREAD

**Issue by jpluimers** [certbot/certbot#3420]
For n00bs like me (that sort of know git, but are relatively new to the github project management stuff), the README should at least point to https://github.com/certbot/certbot/milestones and maybe explain a bit on how to find out which issues end up where in the release cycle.

**Comment by pde** [comment]
That information is in the [CHANGES.rst file](https://github.com/certbot/certbot/blob/master/CHANGES.rst), which is used to be part of the docs, but no longer seems to.

**Comment by pde** [comment]
I guess we could put it back into the README file, though I think there was an effort underway to simplify that, and this is sort of the opposite.

Alternatively, if we're going to discuss the milestones and soforth, it might be better to put that information in the [Developer Guide](https://certbot.eff.org/docs/contributing.html)?

**Comment by jpluimers** [comment]
The CHANGES.rst should (also?) point to https://github.com/certbot/certbot/milestones as that gives a nicer overview than the current URL in it: https://github.com/certbot/certbot/issues?utf8=%E2%9C%93&q=milestone%3A0.3.0

I understand the README needs to be balanced, but for me watching my issues go into a milestone and tracking the progress of that milestone is a bit different from "contributing". It's more "bug reporting" to me, so didn't even think of needing the "Developer Guide" to find out how to track progress.

Eventually I got directed to the "Developer Guide" when reproducing stuff from my reports (specifically the https://github.com/certbot/certbot/blob/master/docs/contributing.rst#running-a-local-copy-of-the-client bits) but I think that should go in a separate subject "reporting bugs and testing them locally" somewhere.

It's hard to get documentation right, so try to follow me here:

I think most people starting to use certbot either get it to work immediately, or bump into a problem and start discussing them as an issue or try to find their ways through the docs. Even fewer will be "contributors". 

The point here for me: documentation in the README should focus to the "how to get things to work" and "what if it doesn't work" bits. The former is well covered, the latter can be improved.

**Comment by jaywink** [comment]
Is there a reason why a [proper changelog](http://keepachangelog.com) isn't maintained? It doesn't have to cover the time before the changelog, and if enforced in the PR level, it will maintain itself and be ready to publish at release time.

Certbot is used by millions. Making users browse commit logs to find out when some new cli flag was added so they know if they can support it in their automation thingy (for example, might have just spent 30 minutes looking for something like that ;)) is just not very user friendly.

I realize the promise is to fix this in 1.0, but is there a reason that cannot start now?

**Comment by jsha** [comment]
@jaywink I think it does make sense to start keeping a changelog now. For now, though, I've sent a PR to use your more useful GitHub link: #3541. Thanks for suggesting it!

**Comment by jaywink** [comment]
I really hope the changelog will start to be maintained soon. Tried to make sense what has changed since 0.8.1 and the milestone browsing is just a huge headache. Gave up, *I guess* nothing major happened `¯\_(ツ)_/¯`.

**Comment by SwartzCr** [comment]
We've started keeping track of the changelog, I've made a PR to mention it in the readme, so that should resolve this issue
