### ISSUE TITLE
Current README link to "the" mailing list (`client-dev`) is broken

### ISSUE THREAD

**Issue by jpluimers** [certbot/certbot#3421]
`client-dev` mailing list link at https://certbot.eff.org/docs/resources.html#resources points to https://groups.google.com/a/letsencrypt.org/forum/#!forum/client-dev

`client-dev` mailing list link at https://github.com/certbot/certbot#links points to https://github.com/certbot/certbot#id7 which does not get you to the mailing list.

**Comment by bmw** [comment]
This is a subset of the problems identified in #3416.
