### ISSUE TITLE
python-certbot-apache EPEL package should depend on apache mod_ssl 

### ISSUE THREAD

**Issue by joohoi** [certbot/certbot#3424]
python-certbot-apache needs to depend on mod_ssl to avoid bouncing users from error messages to install it.

**Comment by pde** [comment]
Oh, I think this should be [over here](https://bugzilla.redhat.com/buglist.cgi?quicksearch=certbot)

**Comment by pde** [comment]
Forwarded: https://bugzilla.redhat.com/show_bug.cgi?id=1367943

**Comment by hogarthj** [comment]
This requires has been added to the python-certbot-apache packages pushed to fedora and epel today.

**Comment by hogarthj** [comment]
This is now in the stable Fedora and EPEL repos and can be closed.
