### ISSUE TITLE
Offer to enable EPEL on RHEL

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3433]
Turns out this is a bit tricky. `yum install epel-release` only works on CentOS systems. On Red Hat systems, we have to `wget` a package and install it directly through `rpm`. Testing this for RHN users will likely be a pain as it appears we have'd have to sign up for a Red Hat subscription. Additionally, the EPEL package you download is different depending on your version of RHEL.

**Comment by jsoref** [comment]
Note: you can skip the wget. rpm supports urls.

At least for initial testing, I have more than enough computers which have redhat subscriptions (usually we get this from our hosting provider).

**Comment by SwartzCr** [comment]
@jsoref wanna make a PR to that effect?

**Comment by SwartzCr** [comment]
@jsoref do we still fail by default on RHEL 6? i.e. is #3992 still valid?

**Comment by jsoref** [comment]
@SwartzCr: I'll try at some point to do the rpm thing. I'll have to see if I have any rhel instances handy that haven't been too modified or whether I'll just have to install a clean one. Sadly, I probably can't do much until October (other deadlines).

**Comment by bmw** [comment]
I don't think we'll ever do this. RHEL 7+ systems shouldn't use `certbot-auto` and RHEL 6 stops getting security updates next year.
