### ISSUE TITLE
parse error 

### ISSUE THREAD

**Issue by ifastnet** [certbot/certbot#3441]
Im seeing : 

The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/usr/local/apache/conf/modsec2.user.conf', u'Syntax error'),)

the file is attached. 
[modsec2.user.conf.txt](https://github.com/certbot/certbot/files/426656/modsec2.user.conf.txt)

**Comment by domcleal** [comment]
Thanks for the report. This is due to an additional, mismatched quote at the end of line 97:

      SecRule TX:HEADER_ORDER "@streq , Accept-Encoding, Host, Keep-Alive, User-Agent, Accept-Charset, Connection, Referer, Cache-Control""

As a workaround, remove the second quote from the end of the line and the file should parse OK.

**Comment by ifastnet** [comment]
Thanks ! that done the trick, have another parse error, ill make a new request
