### ISSUE TITLE
parse error 

### ISSUE THREAD

**Issue by ifastnet** [certbot/certbot#3442]
Hi im seeing the following parse error when trying to add a cert. 

The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/usr/local/apache/modsec/10_asl_rules.conf', u'Syntax error'),

Ive attached the file.
[10_asl_rules.conf.txt](https://github.com/certbot/certbot/files/426686/10_asl_rules.conf.txt)

**Comment by domcleal** [comment]
Thanks for the report! There are two similar parse errors in this file, where line continuations are present but the lines aren't actually continued. Here is a diff showing the necessary workarounds:

<pre>
---  10_asl_rules.conf.txt.bak     2016-08-19 10:21:52.000000000 +0100
+++  10_asl_rules.conf.txt 2016-08-19 10:27:44.190079278 +0100
@@ -954,7 +954,7 @@
 # Rule 340140: bogus graphics file
 SecRule REQUEST_HEADERS:Content-Disposition "\.(?:php|txt|asp|pl|exe)" \
        "phase:2,deny,status:403,t:none,t:urlDecodeUni,t:lowercase,id:340140,rev:4,severity:2,msg:'Atomicorp.com WAF Rules: Bogus graphics file'"
-#SecRule REQUEST_HEADERS:Content-Type "(?:image/gif|image/jpg|image/png|image/bmp)" \
+#SecRule REQUEST_HEADERS:Content-Type "(?:image/gif|image/jpg|image/png|image/bmp)" 
 
 SecMarker END_IMAGE_CHECKS
 
@@ -1126,7 +1126,7 @@
 # Rule 380007: generic SQL injection sigs using PCRE
 SecRule REQUEST_URI "!(/immagini/)"  \
        "phase:2,deny,status:403,chain,t:none,t:lowercase,id:380007,rev:5,severity:2,msg:'Atomicorp.com WAF Rules: SQL Inject Generic signature'"
-SecRule REQUEST_URI|ARGS|!ARGS:areas|!ARGS:templatecode "/\w*(\x27|\’)(\x6f|o|\x4f)(\x72|r|\x52).*!(\.(jpe?g|png|bmp|gif|mpe?g|avi|flv|wmv|ico)$)" \
+SecRule REQUEST_URI|ARGS|!ARGS:areas|!ARGS:templatecode "/\w*(\x27|\’)(\x6f|o|\x4f)(\x72|r|\x52).*!(\.(jpe?g|png|bmp|gif|mpe?g|avi|flv|wmv|ico)$)" 
 
 SecMarker END_MISC_CHECKS
 
</pre>

(lines 957 and 1129)

**Comment by joohoi** [comment]
This is most likely fixed now? Can you confirm @ifastnet

**Comment by ifastnet** [comment]
I can confirm this fixed the issue.

**Comment by ifastnet** [comment]
thanks !
