### ISSUE TITLE
Apache plugin should use mod_alias Redirect

### ISSUE THREAD

**Issue by hirvinen** [certbot/certbot#3443]
Apache wiki [recommends using mod_alias Redirect](https://wiki.apache.org/httpd/RedirectSSL) directive instead of mod_rewrite when the objective is to simply redirect to the same path on an SSL enabled host. 

This should also have the added benefit of less potential to mess with existing rewrite directives.

**Comment by joohoi** [comment]
Related to #3363 these should be looked into simultaneously.

**Comment by bmw** [comment]
The reason why we don't do this is because we want to be able to only add redirects for the specific domains that we enabled HTTPS for. If your HTTP vhost is being used for other domains and that aren't in the certificate, redirecting them to HTTPS will cause an error for your users.
