### ISSUE TITLE
Option to never request for SUDO or ignore permission tests

### ISSUE THREAD

**Issue by jhawkwind** [certbot/certbot#3444]
It is requested that an optional flag be available to allow it to assume that the current account has the appropriate access to the needed areas and **never request for SUDO**/elevation, just do not even test for it.

So that for people that want to set the appropriate permissions manually and add things to the appropriate groups, they do not need to give the cron automatic access to root. This allows those that want to tighten their system for least privilege can do so.

**Comment by bmw** [comment]
This is for `certbot-auto` which is meant to be a temporary workaround while OS packages are created. With that said, we can perhaps look into adding this feature.

In the meantime, you can manually run `~/.local/share/letsencrypt/bin/letsencrypt` which is what `certbot-auto` does. Note that this will not automatically update Certbot (which might be the behavior you want anyway for more stable automated renewal).

**Comment by bmw** [comment]
While modern `certbot-auto` is more likely to need root, this can be accomplished by setting the environment variable `LE_AUTO_SUDO` to an empty string.
