### ISSUE TITLE
Build our wheels properly

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3455]
It turns out we're not building our wheels for PyPI correctly. Due to the way we're adding conditional dependencies, the dependencies that get added to the wheel are only those that were required on the system that built the wheel. For example, all of our `setup.py` files contains code like this:

```
if sys.version_info < (2, 7): 
    install_requires.extend([
        'argparse',
        'mock<1.1.0',
    ])  
else:
    install_requires.append('mock')
```

We have always built our wheels on Python 2.7, however,  which means our wheels will never install `argparse` or `mock<1.1.0`. This problem doesn't affect `certbot-auto`, but affects people installing through `pip`.

Fixing this problem without breaking people on old versions of `setuptools`/`pip` will be tricky (or impossible).

**Comment by erikrose** [comment]
For completeness, I'll mention [environment markers](https://www.python.org/dev/peps/pep-0496/), which would solve the problem in the event we are unable to dispense with the conditonals. But, as you hint, those work only in pip >= 6.0.

**Comment by bmw** [comment]
Another option I've seen is to use `setup.cfg` and `metadata`. Although this is technically depreciated, it is still used by a number of very popular and maintained Python packages such as [twine](https://github.com/pypa/twine).

**Comment by erikrose** [comment]
> Another option I've seen is to use setup.cfg and metadata.

Yes, those are another place to put environment markers. They can also go right in setup.py. The user would need pip>=6.0 [or setuptools>=20.6.0](https://setuptools.readthedocs.io/en/latest/history.html#v20-6-8) to respect them.
