### ISSUE TITLE
certbot-auto with --quiet

### ISSUE THREAD

**Issue by vietnamxinhdep** [certbot/certbot#3459]
hello, i want to make a small bug report:

i have written a script which turns off my httpd and extends my certificate. (i know there are other ways to do it but i have to do it like that because of other issues)

anyway this script contains the parameter --quiet since its an automated crontab. when i install my linux machine freshly however, i launch that cron manually for the first time and there comes the problem:
the first time, certbot-auto launches apt-get and wants to install some packages like python, which is fine.

with the --quiet parameter however the output is surpressed and the need for confirmation (do you wanna install following NEW packages?) is invisible. since i know the process from calling it without the --quiet parameter, i knew what to do blindly (write "y" and enter). and it worked flawlessly.

but is it possible to add the "-y" parameter for the apt-get installs in case certbot-auto was launched in "--quiet" mode? it makes even sense just from a logical standpoint since human interaction is surely not wanted in an automated process. and that is what --quiet was added for, no?

thank you for reading everybody.

**Comment by tcottier-enalean** [comment]
I confirm this issue, -n option does not seems to work (It does not trigger the ASSUME_YES variable).

Using --noninteractive solves the issue.

**Comment by vietnamxinhdep** [comment]
thank you for your answer. i don't know if your commit does fix the problem since i dont use "-q" but "--quiet" and according to your problem description, only the short form of arguments are ignored.

my issue has more to do with the fact that on a fresh linux box where there is no python and other packages installed, apt-get firsty produces some unpacking output and secondly as well as far more worse, it needs a confirmation to install those packages. ("y" and enter, without the question visible and therefore blindly!) despite the quiet argument.

according to the manual "--quiet" does imply "--non-interactive" so there should(?) be no reason to define it again since its a bug with the quiet functionality, no?

  -q, --quiet           Silence all output except errors. Useful for
                        automation via cron. Implies --non-interactive.
                        (default: False)

**Comment by tcottier-enalean** [comment]
Hi, from what I saw, there are no "-q" or "--quiet" options in certbot-auto (but there are in letsencrypt-auto which is deprecated from what I understood).

Initially I had the same problem as you have: even with --noninteractive, It asked me to confirm packages installation, my commit resolves this issue

**Comment by vietnamxinhdep** [comment]
hello tcottier-enelean,



i did see some days ago that i was overtaken and i was very happy. suddenly i see now that there is an error with a commit. i am paciently awaiting the fix of this bug since i wanna test my install routine. may i ask how i can help to speed up that process?



thank you.

**Comment by tcottier-enalean** [comment]
Hi,

There is currently a problem with the CI process, not linked to my commit but with the general process. It means my small patch can not be reviewed or merged. We have to wait for the cerbot CI gods to solve the issue :wink:

**Comment by SwartzCr** [comment]
I'm going to assume with the PR this is resolved. Feel free to re-open if not.
If it's still just the case that you need something to say Yes to prompts, have you tried piping yes to it?
