### ISSUE TITLE
certbot --dry-run changes letsencrypt/keys/*-key-certbot.pem

### ISSUE THREAD

**Issue by vbotka** [certbot/certbot#3462]
"certbot renew --dry-run" succeeds [1], but changes letsencrypt/keys/ [2,3].

I understand, that in this case --dry-run means "no renewal", but also I didn't expect any changes with --dryrun. 

[1]
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)
Congratulations, all renewals succeeded. The following certs have been renewed:

[2]
letsencrypt/keys/0040_key-certbot.pem does NOT match
letsencrypt/keys/0041_key-certbot.pem does NOT match
...

[3]
letsencrypt/keys: 
	modification time (Sat Aug 27 02:20:34 2016, Sun Aug 28 02:20:34 2016)
extra: letsencrypt/keys/0040_key-certbot.pem
extra: letsencrypt/keys/0041_key-certbot.pem
...

**Comment by bmw** [comment]
Dupe of #2495.
