### ISSUE TITLE
I installed certbot-auto but all I get is "basename: not found"

### ISSUE THREAD

**Issue by oliveratgithub** [certbot/certbot#3467]
Hi there,
I followed the simple installation steps here https://certbot.eff.org/#ubuntuother-apache and successfully (it seems) downloaded & installed _certbot-auto_ on into my virtual Ubuntu 12 hosting.

However, after installing, whenever I run ANY command (even --help) for certbot-auto, I get the message:

> $ ./certbot-auto --help
> ./certbot-auto: 23: ./certbot-auto: basename: not found

...which refers to the following line #23 
`BASENAME=$(basename $0)`

Didn't find any information on this error neither here on Github, in Let's Encrypt Community Forums nor with a Google Search.

I'm on a Parallels Plesk based virtual dedicated hosting environment, where I can only SSH into my Accounts root-directory. Ubuntu OS Version is 12.04.4 LTS. The file & directory structure looks like the following:

```
$ ls
drwxr-x---    5    4.0K    Oct 21  2013    anon_ftp/
drwxr-xr-x    2    4.0K    Aug 30 20:15    bin/
-rwxr-xr-x    1   44.0K    Aug  1 19:35    certbot-auto*
drwxr-x---    2    4.0K    Oct 21  2013    cgi-bin/
lrwxrwxrwx    1    0.0K    Oct 24  2013    conf -> alias
drwxr-xr-x    2    4.0K    Aug 30 20:15    dev/
drwxr-xr-x    2    4.0K    Oct 21  2013    error_docs/
drwxr-xr-x    2    4.0K    Aug 30 20:15    etc/
drwxr-x---    5    4.0K    Oct  7  2015    httpdocs/
drwxr-xr-x    3    4.0K    Aug 30 20:15    lib/
drwxr-xr-x    2    4.0K    Oct 21  2013    lib64/
drwx------    5    4.0K    Aug 31 04:26    logs/
drwx------    2    4.0K    Oct 21  2013    private/
drwxr-xr-x    3    4.0K    Oct 21  2013    subdomains/
drwxrwxrwt    2    4.0K    Oct 21  2013    tmp/
drwxr-xr-x    3    4.0K    Oct 21  2013    usr/
drwxr-xr-x    3    4.0K    Oct 21  2013    var/
drwxr-xr-x    2    4.0K    Oct 21  2013    web_users/
```

**Does anybody have a clue what might be going on and how I can fix this? Or can I even assume that a manual run of cerbot on my Plesk based Ubuntu Hosting will not work due to limited access?**

Thanks for any help, much appreciated!

**Comment by erikrose** [comment]
On Ubuntu 14.04, `basename` is in `/usr/bin`. Is it there for you? If so, maybe your `$PATH` is unusual.

**Comment by joohoi** [comment]
For plesk, you should try https://www.plesk.com/extensions/letsencrypt/

**Comment by oliveratgithub** [comment]
Thanks for the info. I guess @joohoi 's solution is most likely the best way to generate a Let's Encrypt cert with Plesk.
