### ISSUE TITLE
Seperate the virtual environment creation step and the actual task

### ISSUE THREAD

**Issue by timdream** [certbot/certbot#3472]
We got `--os-packages-only` and I recommend we create an option `--venv-only`.

There are times it make sense to create venv first without doing anything, for example, get the environment to set up in automation so that human can do things quickly later.

Good idea?

**Comment by timdream** [comment]
I am refer to `certbot-auto` here so please add that label for me.

**Comment by bmw** [comment]
That might be a good idea. `certbot-auto` is simply meant to be a temporary workaround for OS packaging while we wait for it to catch up. For this reason, I personally try to avoid adding unnecessary complexity or features to it because it will be going away.

While it's certainly less elegant, people can simply run something like `certbot-auto --version` for this purpose. I'm inclined not to add a `--venv-only` flag, but I could be convinced.

**Comment by timdream** [comment]
> While it's certainly less elegant, people can simply run something like certbot-auto --version for this purpose. I'm inclined not to add a --venv-only flag, but I could be convinced.

@bmw What if I propose a doc change `--version` instead? I was reading the code and the doc for quite some time but didn't figure out `--version` could do what you said.

**Comment by bmw** [comment]
I think that's fine. To be clear, the main purpose of `--version` is to print the current version of Certbot, however, it will also work for your purposes because Certbot will simply print its version string and exit.

**Comment by timdream** [comment]
#3512 proposed.

**Comment by bmw** [comment]
I've actually changed my mind about this. We should provide a flag like `--install` that will install Certbot without running it. This flag should never be passed to Certbot as `certbot-auto` should exit before calling into Certbot.

Providing this feature helps cases like #3691.

**Comment by timdream** [comment]
@bmw Should I close #3529 then? I might not be able to produce a patch for `--install` soon-ish.

**Comment by bmw** [comment]
@timdream, yes we should probably close that PR. Sorry I lead you down the wrong path and we didn't end up taking the PR. I hope to have this feature soon though.

**Comment by bmw** [comment]
This was done with the flag `--install-only`.
