### ISSUE TITLE
~/.local/share/letsencrypt/ folder does not exist

### ISSUE THREAD

**Issue by bronch** [certbot/certbot#3476]
When I run `./certbot-auto`, after it says `Installing Python packages`, after a while it gives me a very long error which ends with `You are using pip version 8.0.3, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`
I tried the command that the error suggests and pip is already up-to-date. Then searching on Google I found that I had to upgrade the pip command inside the folder `.local/share/letsencrypt/` but the folder `letsencrypt` inside the `share` folder doesn't exist.
So, what the heck should I do??
_Sorry for bad English_

**Comment by erikrose** [comment]
It's only an advisory message—and one we should disable. You can safely ignore it.

I'll leave this open to remind us to pass the option which turns off this confusing message.

**Comment by bronch** [comment]
@erikrose In the meanwhile, is there a method to bypass that thing?
