### ISSUE TITLE
Update from 0.4.1 -> 0.8.1, renewal config error

### ISSUE THREAD

**Issue by Croydon** [certbot/certbot#3477]
I recently updated my certbot package from v0.4.1 to v0.8.1.
I set up a cronjob for renewals before and it worked as expected with v0.4.1.
Now it seems like the renewal configuration file is invalid with v0.8.1 and didn't got modified in the update process.

I get the following error when running _letsencrypt renew_ as cronjob:
> WARNING:certbot.renewal:Renewal configuration file /etc/letsencrypt/renewal/domain.conf produced an unexpected error: 'Namespace' object has no attribute 'apache_enmod'. Skipping.

Is there a way I can manually patch it? If yes, how? If not, do I have to resetup it completely?

**Comment by bmw** [comment]
Can you post the contents of the file? Which [plugin](https://certbot.eff.org/docs/using.html#getting-certificates)(s) were you using?

**Comment by Croydon** [comment]
@bmw I'm using the Apache plugin. Here is my config file (domain names replaced)

> cert = /etc/letsencrypt/live/domain/cert.pem
privkey = /etc/letsencrypt/live/domain/privkey.pem
chain = /etc/letsencrypt/live/domain/chain.pem
fullchain = /etc/letsencrypt/live/domain/fullchain.pem
# Options and defaults used in the renewal process
[renewalparams]
apache_enmod = a2enmod
checkpoints = 1
ifaces = None
installer = apache
text_mode = False
staging = False
prepare = False
work_dir = /var/lib/letsencrypt
tos = False
duplicate = False
init = False
apache_challenge_location = /etc/apache2
agree_dev_preview = None
renew_by_default = False
authenticator = apache
nginx = False
verb = renew
func = <function renew at 0x725a00223140>
reinstall = False
account = 8086e246ec037fd60225bbf82aa6e9ec
manual_public_ip_logging_ok = False
standalone = False
manual = False
server = https://acme-v01.api.letsencrypt.org/directory
standalone_supported_challenges = "tls-sni-01,http-01"
apache_init_script = None
debug = False
tls_sni_01_port = 443
apache_vhost_root = /etc/apache2/sites-available
configurator = None
no_self_upgrade = False
no_verify_ssl = False
apache_dismod = a2dismod
register_unsafely_without_email = False
uir = None
config_dir = /etc/letsencrypt
dry_run = False
http01_port = 80
apache_le_vhost_ext = -le-ssl.conf
noninteractive_mode = False
key_path = None
fullchain_path = None
email = None
csr = None
redirect = None
verbose_count = -3
config_file = None
hsts = False
apache_handle_sites = True
apache_handle_modules = True
logs_dir = /var/log/letsencrypt
rsa_key_size = 2048
manual_test_mode = False
apache = False
cert_path = None
webroot_path = ,
expand = False
strict_permissions = False
apache_server_root = /etc/apache2
chain_path = None
break_my_certs = False
webroot = False
os_packages_only = False
user_agent = None
apache_ctl = None
domains = domain, domain2
[[webroot_map]]

**Comment by bmw** [comment]
I'm having a hard time reproducing the problem, even using your configuration file. The program is complaining because `apache_enmod` isn't defined, but you can see it is in your configuration file above.

Do you happen to have a complete log of the issue? They should be found in `/var/log/letsencrypt`. Feel free to redact your domain/e-mail address from the log.

Also, how did you install 0.8.1?

**Comment by Croydon** [comment]
Oh man.
Sorry @bmw for wasting your time. 😒

I'm using this ppa: https://launchpad.net/%7Eondrej/+archive/ubuntu/letsencrypt
Somewhere along my update process the apache plugin just got lost. Now after reinstalling  python-certbot-apache it is working great.

Sorry again.

**Comment by lorrin** [comment]
I also got this error upgrading from the 0.4.1 in xenial to 0.14.1 in the PPA. This seems like an error message that could use some improvement.

**Comment by ojaynico** [comment]
@Croydon reinstalling python-certbot-apache fixed my problem too. Thanks

**Comment by rsecor** [comment]
I just had the same issue with a machine I had to upgrade to certbot from the letsencrypt command-line tools.
python-certbot-apache should be a requirement and thus installed by apt (in my case).

**Comment by MichaelKofler** [comment]
Found this page after doing a distribution update from Ubuntu 16.04 to 18.04. Same error message, same reason (python-certbot-apache was not installed). Easy to fix, but it would be helpful if the error message of certbot would recommend installing this package.

**Comment by kaimast** [comment]
Had the same problem just now.

Don't think this issue should be closed before a proper error message has been added.

**Comment by giox069** [comment]
Same problem for me: I upgraded now (Aug 10 2018) from the stock certbot package of Ubuntu 16.04 to `ppa:certbot/certbot` PPA, and I got the same error reported in the 1st post.
`apt install python-certbot-apache` solved it. Please fix dependencies in the PPA or make the error message show a helpful solution, as suggested above.

**Comment by diltonm** [comment]
I had this issue, I noticed python3-(etc) was installed and installed the python3-(etc) package and it did fix the issue, thanks to those who found it and provided information on the fix.
