### ISSUE TITLE
--force-renew vs --force-renewal

### ISSUE THREAD

**Issue by vietnamxinhdep** [certbot/certbot#3478]
hello i would like to make a small bug report regarding the manual.

inside the text of the manual there is a passage:

> The --force-renew flag may be helpful for automating renewal; it causes the expiration time of the certificate(s) to be ignored when considering renewal, and attempts to renew each and every installed certificate regardless of its age. (This form is not appropriate to run daily because each certificate will be renewed every day, which will quickly run into the certificate authority rate limit.)

if continued to scroll down however, one can see that there is no "--force-renew" but only a "--force-renewal" parameter.

>   --force-renewal, --renew-by-default
>                         If a certificate already exists for the requested
>                         domains, renew it now, regardless of whether it is
>                         near expiry. (Often --keep-until-expiring is more
>                         appropriate). Also implies --expand. (default: False)

it confused at least me so much that i now use --renew-by-default instead of the other one(s). maybe someone wanna fix that. thank you for your attention.

**Comment by cowlicks** [comment]
This was already fixed in the documentation here https://github.com/certbot/certbot/commit/f3915705668f1da08077c2f5e42b317b14df462b 

[The docs](https://certbot.eff.org/docs/using.html?highlight=renew) are still out of date. But this can probably be closed since they will update soon enough.

**Comment by schoen** [comment]
@vietnamxinhdep, the answer is that they are the same (if you write `--force-renew`, the option parser understands it as a synonym for `--force-renewal`). But @cowlicks has pointed out that we have also now fixed the documentation. Sorry for the confusion!
