### ISSUE TITLE
OS X MacPorts problem when installing python

### ISSUE THREAD

**Issue by MichalMMac** [certbot/certbot#3479]
OS X 10.11.6 with latest Macports installed.
Cerbot scripts are unable to install python via MacPorts. 

```
echo "Installing python..."
Error: Port python not found
```

This concerns following files:

```
certbot-auto:   
letsencrypt-auto:   
letsencrypt-auto-source/letsencrypt-auto
letsencrypt-auto-source/pieces/bootstrappers/mac.sh
```

This happens because `sudo port install python` returns `Error: Port python not found`. My workaround is to replace `$pkgcmd python` with `$pkgcmd python27`

I am not sure if `sudo port install python` is suposed to work and something is broken on MacPorts side.

**Comment by billc108** [comment]
You need to designate which version of python in your MacPorts command. So:

sudo port install python27

or 

sudo port install python36

etc.   See https://www.macports.org/ports.php?by=name&substr=python&page=2&pagesize=50 for the current versions.

**Comment by MichalMMac** [comment]
I submited pull requrest #4188 to fix this. Any further ideas welcomed.

**Comment by bmw** [comment]
Closing for the reason described [here](https://github.com/certbot/certbot/pull/4190#issuecomment-294998771).
