### ISSUE TITLE
certbot-auto doesn't appear to respect HTTPS_PROXY env var

### ISSUE THREAD

**Issue by botandrose** [certbot/certbot#3480]
Hello, thanks for certbot! I'm attempting to use it behind an https proxy, and it hangs after asking me for my email address, eventually erroring out with this message:

```
ConnectionError: HTTPSConnectionPool(host='acme-v01.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f7f4f42f510>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```

I'm fairly confident that this is due to it not using the https proxy set in both `https_proxy` and `HTTPS_PROXY` environment variables. Any ideas?

**Comment by bmw** [comment]
Certbot uses `python-requests` to communicate with the server which [respects the HTTPS_PROXY env var](http://docs.python-requests.org/en/master/user/advanced/#proxies).

Are you using `letsencrypt-auto`/`certbot-auto`? If so, I suspect the problem is `sudo`. The script uses `sudo` internally to invoke Certbot which will drop your environment variables by default.

**Comment by jsoref** [comment]
Assuming the subject is correct, certbot-auto could probably warn if it detects HTTPS_PROXY and has selected sudo...

**Comment by bmw** [comment]
Another thing we could do here is to run certbot with something like `sudo HTTPS_PROXY=$HTTPS_PROXY certbot ...` if we detect the variable is set. This way, it continues to work and the user doesn't have to know/worry about it.

**Comment by lindhe** [comment]
I'm getting the exact same error, but having no `HTTPS_PROXY` set. Any idea how to debug?

**Comment by bmw** [comment]
Certbot is unable to communicate with Let's Encrypt. On your server where you are having this problem, what is the output of `curl https://acme-v01.api.letsencrypt.org/directory`?

**Comment by lindhe** [comment]
```
{
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
}
```

**Comment by lindhe** [comment]
I see that I have lied to you. It's not the exact same error, only rather similar:

```
ConnectionError: HTTPSConnectionPool(host='acme-staging.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fb7eba77910>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```
