### ISSUE TITLE
acme standalone tests depend on port 1234 being free

### ISSUE THREAD

**Issue by Baughn** [certbot/certbot#3482]
...but it's not, causing the build to fail.

The proper solution would be to bind to port 0, letting the OS choose a free port, then using getsockname to find out which port it was.

**Comment by bmw** [comment]
You're correct. We'll gladly accept a PR if you want to work on this. Otherwise, we'll change this behavior when Certbot development slows down a bit.

**Comment by bmw** [comment]
This has been resolved.
