### ISSUE TITLE
Implement account deactivation

### ISSUE THREAD

**Issue by rolandshoemaker** [certbot/certbot#3483]
Boulder recently merged code to allow for [ACME draft-03 style](https://tools.ietf.org/html/draft-ietf-acme-acme-03#section-6.2.2) account deactivation.

The process is extremely simple, to deactivate their account a user must POST a signed payload containing `{"status":"deactivated"}` to the `/acme/reg/{id}` endpoint. The server will respond with 200 and the contents of the deactivated registration if successful.

**Comment by cowlicks** [comment]
I can check this out this weekend.

**Comment by cowlicks** [comment]
This is still on my radar, but I haven't started. So if anyone else feels so motivated feel free to take this on. Just lmk so we don't duplicate effort.

**Comment by cowlicks** [comment]
@rolandshoemaker I noticed y'all reverted then re-reverted this feature. Is it good to go now?

**Comment by cowlicks** [comment]
Ah looks like it is still turned off here https://github.com/letsencrypt/boulder/blob/master/wfe/wfe.go#L455
