### ISSUE TITLE
Deprecate old certificates

### ISSUE THREAD

**Issue by tinganho** [certbot/certbot#3484]
I'm the maintainer of this lib https://github.com/tinganho/haproxy-with-letsencrypt-auto-renewal.

I've recently updated my certificate or actually created a new certificate with an additional domain. I then received a notification that my certificate(old certificate) was being near expiration. I suddenly freaked out and needed to check my server and verify that this was not the case. 

People don't keep track of what is new or old certificate or what's the difference between them. And I don't want to freak out every time you send me expiry information when I add a new domain to my certificate. Could you add method for deprecating old certificates, to deal with this issue?

**Comment by cowlicks** [comment]
You can revoke your old certificate if you are not using it anymore with `certbot revoke ...`.

**Comment by tinganho** [comment]
@cowlicks I cannot see any information about renew with a new added domain? I looked at your website and the `--help all`? Do I just pass all the domains in `-d`?

Also in revoke, do I just pass all the domains in `-d`?

**Comment by pde** [comment]
This is really a ticket for the boulder team, since it's that codebase that sends those reminder emails...

**Comment by jsha** [comment]
@cowlicks has the right idea: If you have an old certificate and you don't want to receive expiration warnings about it, you can revoke it. You would need to find the old certificate in /etc/letsencrypt/archive/ and revoke it with `certbot revoke --cert-path /path/to/old/cert`.

**Comment by tinganho** [comment]
Thanks
