### ISSUE TITLE
Renew doesn't use account from renewal configs

### ISSUE THREAD

**Issue by DjSlash** [certbot/certbot#3485]
When having multiple accounts, and using `certbot renew`, it doesn't honor `account` from the renewal configs. It complains that it doesn't know what account to use. But when giving the accountid manually it also renews certs which are not linked to that account.

Edit: adjusted text according to the actual behaviour instead of what I remembered.

**Comment by pde** [comment]
@schoen, want to take a look at this?

**Comment by schoen** [comment]
Sure, I'll take a look.

**Comment by schoen** [comment]
@DjSlash, could you please give us a little more information about your situation? How many accounts do you have, which version of certbot, what command line are you using, and what output do you see?

Thanks!

**Comment by DjSlash** [comment]
Two accounts, latest version that Debian testing provides (0.8.1), `certbot renew`, output:

```
-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/example.com.conf
-------------------------------------------------------------------------------
2016-10-05 09:18:28,369:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/example.com.conf produced an unexpected error: Missing command line flag or config entry for this setting:
Please choose an account
Choices: ['example.com@2016-01-05T16:37:27Z (bf96)', 'example.com@2015-12-15T11:07:02Z (9b38)']. Skipping.
```

**Comment by bmw** [comment]
This should be fixed. If anyone is still having problems with this, please comment or open a new issue.
