### ISSUE TITLE
Ability to set source IP

### ISSUE THREAD

**Issue by urusha** [certbot/certbot#3489]
It would be nice if we could set the source IP address that certbot will use for outgoing connections. Just like wget's --bind-address or curl's --interface . For now I have to use such hack: http://daniel-lange.com/archives/53-Binding-applications-to-a-specific-IP.html

**Comment by pde** [comment]
We'd take a well-written patch for this.

**Comment by xomka686** [comment]
Hi! Is there any roadmap for that feature or patch is still being awaited from the community?

**Comment by bmw** [comment]
This isn't currently on the core Certbot team's roadmap. We'd probably get to it eventually, but the feature would land much faster if an external contributor submitted a well written PR.

**Comment by bmw** [comment]
Specifying this for acme was done in #5990. We now need to add a flag to allow users to set this in Certbot.

**Comment by bmw** [comment]
More progress on this was made in #6007 whose code was moved to https://github.com/certbot/certbot/tree/signop-plumb_source_address_setting.

**Comment by urusha** [comment]
letting you know...

**Comment by urusha** [comment]
letting you know...

**Comment by urusha** [comment]
Still have this issue...

**Comment by alexzorin** [comment]
@urusha in making a decision about this feature, I'd love to find out more about why you would find this feature valuable:

- Why is the default route not appropriate in your environment?
- Why is something like normal source-based routing (e.g. `ip route`) not suitable in your environment?
- Do you need to be able to vary the source IP per certificate? If so, why?

If you are able to find the time to respond, that would be great. Thank you.

**Comment by urusha** [comment]
@alexzorin  to have 2 or more independent domains (read ip addresses) and LE accounts per domain on the same server. Source ip of the acme requests is logged (with manual dns hook its required to confirm this before continue), so why not to bring the ability to choose it in case of multiple ips or vpn+source based routing.

**Comment by strugee** [comment]
@alexzorin personally I could use the ability to vary source IP per certificate. I have multiple IPs on the same network interface and I use `--standalone` in prod, and currently I have to shut down _all_ web servers listening on port 80/443 for Certbot to work. If I could choose the address to have Certbot bind to, I would be able to shut down only the web servers needed.

Not sure that was clear so I'll give an example: say I have Apache on address A, port 80/443. I have [Sandstorm](https://sandstorm.io/) on address B, port 80/443. Sandstorm DNS points to address B, my website's DNS points to address A. Now I want to go and renew my Sandstorm cert. Currently Certbot binds to all interfaces, so I have to shut down Apache or I'll get EADDRINUSE for address A. If I could tell Certbot to bind only to address B, I could keep Apache up. The reverse is true for when I go to renew Apache certs.

**Comment by alexzorin** [comment]
@strugee in that case it sounds like you could use `--http-01-address` (and also `--http-01-port`), which allows you to control the address that `--standalone` binds to. 

`--source-address` would be binding a local address to the outgoing socket that talks to the ACME server.

**Comment by bmw** [comment]
To contradict my former boss and former self, I don't think we want this feature. I believe I understand your use case urusha, but I think it's niche enough that it's not a good use of the Certbot team's time when we are stretched very thin.

I'm sure that's not what you wanted to hear, but I hope you understand and I'm glad you've found the workaround you described in your initial post.
