### ISSUE TITLE
Add documentation at the top of .pem files

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#3491]
One of the neat things about .pem is that stuff outside the `----------` delimiters will be ignored. So we can insert arbitrary text at the top of `cert.pem`, `chain.pem` and `fullchain.pem` explaining what they are for.

**Comment by pde** [comment]
I'm a little skeptical that this would be true of every piece of PEM parsing code under the sun. An alternative would be to finish #1819 ...

**Comment by jsha** [comment]
Agree the README is a better solution (though I think most PEM parsers really would be fine). Closing.
