### ISSUE TITLE
should_autorenew ignores symlinks

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3497]
Imagine the following scenario (which happened to a user). You've successfully completed your challenges from Let's Encrypt and you're renewing your certificates. After saving all four of `cert.pem`, `privkey.pem`, `chain.pem`, and `fullchain.pem` to `/etc/letsencrypt/archive`, you hit ctrl+C. Your symlinks in `/etc/letsencrypt/live` were never updated.

When you run `certbot renew` again, Certbot will tell your certificate is not due for renewal. This is because we currently check the expiration of the newest entry in `/etc/letsencrypt/archive` that has all four of the files listed above ([source](https://github.com/certbot/certbot/blob/master/certbot/storage.py#L706)). We do not check the symlink.

There are a number of ways to fix this, but this is a pretty bad bug and should be resolved before we release 0.9.0.

**Comment by pde** [comment]
I guess under the current semantics of `storage.py`, the problem is that deployment is overdue, not that renewal hasn't happened...

**Comment by bmw** [comment]
My understanding is renewal has occurred and `should_autorenew` will return `False` because the updated versions of the files were written to `/etc/letsencrypt/archive`. `should_autorenew` is the only metric we currently use for whether or not to renew certificates and `should_autodeploy` is never called.

**Comment by pde** [comment]
Agreed. I'm thinking about addressing this by adding a call to `should_autodeploy`. That's a little frightening, because it's never been used before and I'll need to ensure that it's sane. But that will prevent our solution from breaking the hidden `deploy_before_expiry` feature.

**Comment by bmw** [comment]
I'm personally not sure if that alone will work. Depending on how long ago the user encountered the error in this PR, `should_autodeploy` could return `True` or `False`. My understanding is the default `deploy_before_expiry` value is 5 days. You could potentially fix this problem by changing the default value to be the same as `renew_before_expiry`.

Also, I could be wrong, but I think other work would have to be done to actually respect `deploy_before_expiry`. For instance, as we just discussed, we choose whether or not to renew on the basis of `should_autorenew`. During renewal we do [this](https://github.com/certbot/certbot/blob/master/certbot/renewal.py#L249) which immediately deploys the cert, regardless of the `deploy_before_expiry` value.

**Comment by pde** [comment]
> You could potentially fix this problem by changing the default value to be the same as renew_before_expiry.

I'm planning to do that, yes.

**Comment by pde** [comment]
The subtle thing to get right here is: if a deployment is needed, how does that interact with anything else the user asked for? Should we deploy before doing anything for `run` / `certonly` / `renew`? Or instead of? Or afterwards?

**Comment by bmw** [comment]
I think delving into making `deploy_before_expiry` work well is a lot more work than is needed by this issue which could otherwise be fixed in ~2 lines of code (plus tests :smile:).

If you want to do that work for 0.9.0 though, my instinct on the "correct" behavior is for all three subcommands is if the cert is due for deployment and not renewal, we should deploy the cert instead of fetching a new one. From the point of view of most users who aren't looking in `/etc/letsencrypt/archive`, they will have obtained a new certificate. This approach respects the `deploy_before_expiry` value, allows it to work with all three cert fetching subcommands, and helps the users with rate limits.

Also, I believe @schoen has thought the most about this stuff so it might be good to get his opinion as well.

**Comment by pde** [comment]
So, reading the docs for the various functions in `storage.py`,  I want to do this by adding something like this to `main._handle_identical_cert_request`:
```
if lineage.has_pending_deployment():
        lineage.update_all_links_to(lineage.latest_common_version())
        logger.warn("Found a new cert /archive/ that was not linked to in /live/; " 
                    "fixing and reinstalling..")
        return "reinstall"
```
I do that because internally `has_pending_deployment` uses `latest_common_version` as the standard for newness.

BUT at the top of this ticket @bmw flagged that `latest_common_version()` seems to be looking at `archive`, not `live`. That conflicts with the attempt to use it [in has_pending_deployment](https://github.com/certbot/certbot/blob/master/certbot/storage.py#L535).  Does that mean `has_pending_deployment` is buggy? We don't currently use it.

**Comment by bmw** [comment]
I think what you described would be a fairly elegant solution to the problem. I didn't test it (someone probably should :smile:) but I believe `has_pending_deployment` is correct. `latest_common_version` does look at `archive` not `live`. The function that looks at `live` is `current_version` which is also used in `has_pending_deployment`.

In pseudocode, my understanding of `has_pending_deployment` is:
```
smallest_current := version pointed at by symlinks
largest_archive := latest version in archive
return smallest_current < largest_archive
```
This seems correct. I believe `smallest_current` is effectively the version pointed at by symlinks. More accurately, the pseudocode would be something like `smallest version pointed to by any symlink` but because of the use of `_fix_symlinks`, I believe they should all point to the same version. I think the code is fine as it is though as it's trying to be defensive.

**Comment by bmw** [comment]
In investigating #3552, I found that #3533 does not fix this issue. In #3533, we added a call to `has_pending_deployment` to `_handle_identical_cert_request`. However, `_handle_identical_cert_request` is only ever called from `_treat_as_renewal`, which is only ever called from `_auth_from_domains` where we skip the call to `_treat_as_renewal` if the function was called with a `lineage` parameter. Since we always call this function with a `lineage` parameter during renewal, the change in #3533 has no effect on the `renew` subcommand.

**Comment by pde** [comment]
Ugh you're right, I reasoned from the call graph without looking at the semantics closely enough. I think the best fix will be pulling the test for inconsistent state up into `_auth_from_domains`.
