### ISSUE TITLE
Need assistance to validate using DNS

### ISSUE THREAD

**Issue by vbezruchkin** [certbot/certbot#3501]
Hello guys,

I searched for the instructions many times and I cannot find the way to validate certificate using DNS. Could you please refer me to the correct instructions how to do that? What records should be added in my dns configuration for domain?

I would like to issue a cert for gitlab installation running nginx. I have root access to the server.

Thanks in advance. 

UPD:
I managed to validate through http anyhow, a clear instruction how to do that would be of great help.

Thanks

**Comment by bmw** [comment]
Certbot doesn't yet support validation through DNS. There are open PRs to add such support, but it isn't yet available in `master` or any of Certbot's releases.
