### ISSUE TITLE
Please provide examples of renew hook RENEWED_LINEAGE and RENEWED_DOMAINS values

### ISSUE THREAD

**Issue by jwm** [certbot/certbot#3502]
Thanks for all your work on Let's Encrypt, it's fantastic!

I wrote a renew hook that would only be triggered by a certain domain. Renew hooks are a little tricky to get right since they get called infrequently (only at renewal time, usually every couple of months).

I assumed the lineage directory (`RENEWED_LINEAGE`) was `/etc/letsencrypt/live`, but it's really `/etc/letsencrypt/live/$domain`.

It would be awesome if the CLI help for `--renew-hook` had example values for these environment variables. It would give hook authors more confidence that they've got their code right.

Perhaps something like this:

```
the shell variable $RENEWED_LINEAGE will point to the config live subdirectory
(for example, "/etc/letsencrypt/live/example.com") containing the new certs and
keys; the shell variable $RENEWED_DOMAINS will contain a space-delimited list
of renewed cert domains (for example, "example.com www.example.com").
```

**Comment by pde** [comment]
Yes, this is a good idea! In the mean time, you should be able to test them with `--dry-run`...

**Comment by jwm** [comment]
Hi Peter, thanks for your reply.

Unfortunately, it looks like renew hooks aren't called during a `renew` dry run (https://github.com/certbot/certbot/blob/master/certbot/cli.py#L710).

**Comment by pde** [comment]
You're right :). I guess I did that because I was concerned that renew hooks would often deploy certs to services, and deploying ephemeral test certs that way would break things.

Want to make a PR with the cli wording change you suggested?

**Comment by pde** [comment]
If you're motivated to provide an example, adding it to [this section](https://github.com/certbot/certbot/blob/master/docs/using.rst#renewing-certificates) would be great.

I guess the other way you can try to test `--renew-hook` is with `--force-renewal`. Though that has some drawbacks, particularly burning through peoples' [rate limits](https://letsencrypt.org/docs/rate-limits/).

**Comment by jwm** [comment]
Opened #4028 just now - sorry it took so long!

**Comment by SwartzCr** [comment]
closing since the PR was merged, I've opened a new issue for documenting hooks at #5066 - please comment there if you feel there are ways things could be better improved
