### ISSUE TITLE
Implement Nginx server block selection

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3505]
* NGINX server block treatment sync
  * Installing certificates
    * If >= 1 matching sslish block, add cert info to all matching sslish blocks
    * Else if >= 1 matching non-sslish block, make all matching non-sslish blocks sslish, and add cert info
    * For 0.9.0, if there are no matching blocks, error out and say “sorry you need to give me a relevant server block before I can install a cert for you”.
  * Redirect enhancement
    * At redirect time, there will be at least one matching sslish block.
    * If there are only matching sslish blocks, add listen on 80 and if statement redirect to all matching sslish blocks.
    * Else if there are both matching sslish and matching plaintextish blocks, add the if statement redirect to all matching plaintextish blocks.

**Comment by ohemorange** [comment]
Relies on #3506

**Comment by bmw** [comment]
Related #1825

**Comment by ohemorange** [comment]
"At redirect time, there will be at least one matching sslish block."
This may not be true, if the user calls directly into the enhance flow. Can they do that? We should check anyway.

**Comment by bmw** [comment]
They can't call directly into the enhance flow at this time. We've talked about adding a way to do this in the future though.

**Comment by ohemorange** [comment]
https://github.com/certbot/certbot/compare/master...no_new_server_blocks

WIP, mostly code changes for installation path

**Comment by ohemorange** [comment]
Proposed update:

* Selection protocols
 * Installing certificates
    * Choose a block as currently implemented - rank by nginx matching, then within those levels by sslishness.
    * If the chosen block isn't sslish, make it so.
    * For 0.9.0, if there are no matching blocks, error out and say “sorry you need to give me a relevant server block before I can install a cert for you”.
  * Redirect enhancement
    * Filter all hosts for those that include `listen 80` but do not include `ssl on`
    * Of these, run `get_best_match`. Add a redirect statement to that one.
    * More precisely, we should do this for every port - for each port number, if there are blocks that listen on that port in a nonsslish way (`listen portnum`, no `ssl on` in the block), we should find the most matching one and add a redirect statement.

For installing certificates, we want this because:
```
server {
    listen 443;
    server_name *.example.com;
}
server {
    listen 80;
    server_name chat.example.com;
}
```
It makes more sense to edit the latter one.

For redirect enhancement, what we're trying to provide is a guarantee that you won't get any non-https traffic to that particular domain. This will satisfy that property.

**Comment by pde** [comment]
@ohemorange that reads right to me.

**Comment by ohemorange** [comment]
Update: for each port number, if there are blocks that listen on that port in a nonsslish way (listen portnum, no ssl on in the block), we should find the most matching one and add a redirect statement. include blocks with no listen directive with the listen 80s, since that's the default.

**Comment by ohemorange** [comment]
More specifically, get all numerical ports, and 80. For each of these ports, test each vhost to see if it will match on that port.

**Comment by ohemorange** [comment]
See further commentary at #3546.
