### ISSUE TITLE
Fix Nginx prompt

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3509]
Saw the following prompt when using Nginx
```
-------------------------------------------------------------------------------
No names were found in your configuration files.
You should specify ServerNames in your config files in order to allow for
accurate installation of your certificate.
If you do use the default vhost, you may specify the name manually. Would you
like to continue?
-------------------------------------------------------------------------------
(Y)es/(N)o: 
```
`ServerName` is Apache specific and based on #3508, we don't want to allow people to use the default vhost.

**Comment by ohemorange** [comment]
Was this copied from Apache, or was there some previous active decision to allow modifying the default vhost and specifying the name manually?

**Comment by bmw** [comment]
It's part of the core client (see [this](https://github.com/certbot/certbot/blob/master/certbot/display/ops.py#L107)). If the [get_all_names](https://github.com/certbot/certbot/blob/master/certbot/interfaces.py#L254) method of a plugin returns an empty list, it gives you that question.

The Apache plugin will currently make a copy of the default vhost and add names for you. Based on that behavior and prompts like this, it seems like that decision was deliberate.

I can't remember why that decision was made though (it might predate my involvement). I do remember there was some embarrassment that the plugin didn't work with the default configuration (which comes with no server names specified). Perhaps this feature was simply added so you could use our plugin out of the box?
