### ISSUE TITLE
Inconsistent error placement

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#3511]
Steps to reproduce:
1. Set up certbot development environment.
2. Make sure neither Nginx nor Apache is installed.
3. Run `certbot --config-dir /tmp --logs-dir /tmp --work-dir /tmp --staging`

Expected result: Error about no installer plugins (#3504).

Actual result: Error about installer plugins is printed in text at the bottom of the screen. A different error message is left in the dialog window above it. See screenshot.

![two-errors](https://cloud.githubusercontent.com/assets/220205/18605098/85f26da0-7c3d-11e6-8870-144ea5b252fc.png)

**Comment by bmw** [comment]
This is due to logging messages being sent to the NCurses dialog while fatal exceptions are printed to the terminal. We could potentially catch all error messages at the top level and add them to dialog.

**Comment by jsha** [comment]
Alternately, we could remove our dependency on dialog and go to a text-only interface, which would simplify some other failure cases (e.g. #3324).

**Comment by bmw** [comment]
With the death of `dialog` comes consistent error placement.
