### ISSUE TITLE
Make parser.py: add_server_directives documentation consistent with functionality

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#3514]
Documentation and at least one calling function assume that add_server_directives performs: "Add or replace directives in the first server block with names."

Instead, it add or replaces directives in all server blocks with names

**Comment by ohemorange** [comment]
This manifests itself when there is an 80 and a 443 server block with the same name. `choose_vhost` will act as documented, but after choosing, when modifying, `add_server_directives` will attempt to modify both.

**Comment by ohemorange** [comment]
Also, "first server block with names" throws out the logic of `choose_vhost`. This only makes sense if there the set of names in a server block uniquely identify a server block, which is not the case.

**Comment by ohemorange** [comment]
On the other hand, if we go with the implemented behavior rather than the documented, this makes switching over to "modify all matching sslish blocks" behavior much more straightforward.

**Comment by ohemorange** [comment]
This also causes a bug if there is more than one plaintextish matching server block in the initial config - it will make all of them sslish, and then add the cert information to all of them.

**Comment by ohemorange** [comment]
This probably means that _get_ranked_matches is broken is multiple server blocks have the same set of names, too.

**Comment by bmw** [comment]
This only causes matching server blocks in the same file to be modified correct?

**Comment by bmw** [comment]
Fixed in #3528.
