### ISSUE TITLE
Apache SoftwareCollections

### ISSUE THREAD

**Issue by ILMostro** [certbot/certbot#3520]
It might be useful to allow the script to detect if `scl enable httpd24 /bin/bash` is applied when searching for DocRoot.  As it stands, the script doesn't allow for installation when the default apache package is `httpd24-httpd`, rather than `httpd` on RHEL7/CentOS7.  It looks for vhosts in `/etc/httpd/conf.d/*` for `ServerName` and/or `ServerAlias`.  However, when httpd24-httpd from SoftwareCollections is used, those are specified in `/opt/rh/httpd24/root/etc/httpd/conf.d`.

**Comment by ILMostro** [comment]
I'm not sure how the configuration and/or docroot is picked up or checked; however, when `scl enable httpd24 /bin/bash` is used **before** you run the `letsencrypt-auto`, the `httpd` tool corresponds, correctly, to the `httpd24-httpd` package.  Therefore, one possibility is to simply check the configuration like this:

```
]# httpd -t -D DUMP_RUN_CFG
ServerRoot: "/opt/rh/httpd24/root/etc/httpd"
Main DocumentRoot: "/opt/rh/httpd24/root/var/www/html"
Main ErrorLog: "/opt/rh/httpd24/root/etc/httpd/logs/error_log"
Mutex mpm-accept: using_defaults
Mutex cache-socache: using_defaults
Mutex authdigest-opaque: using_defaults
Mutex proxy-balancer-shm: using_defaults
Mutex rewrite-map: using_defaults
Mutex ssl-stapling-refresh: using_defaults
Mutex authdigest-client: using_defaults
Mutex lua-ivm-shm: using_defaults
Mutex ssl-stapling: using_defaults
Mutex proxy: using_defaults
Mutex ldap-cache: using_defaults
Mutex authn-socache: using_defaults
Mutex ssl-cache: using_defaults
Mutex default: dir="/opt/rh/httpd24/root/var/run/httpd/" mechanism=default 
PidFile: "/opt/rh/httpd24/root/var/run/httpd/httpd.pid"
Define: DUMP_RUN_CFG
User: name="apache" id=48
Group: name="apache" id=48
```

**Comment by ILMostro** [comment]
Actually, the following would also work (work better?):

```
# httpd -S
VirtualHost configuration:
*:443                  www.domain.tld (/opt/rh/httpd24/root/etc/httpd/conf.d/ssl.conf:56)
ServerRoot: "/opt/rh/httpd24/root/etc/httpd"
Main DocumentRoot: "/opt/rh/httpd24/root/var/www/html"
Main ErrorLog: "/opt/rh/httpd24/root/etc/httpd/logs/error_log"
Mutex proxy-balancer-shm: using_defaults
Mutex rewrite-map: using_defaults
Mutex ssl-stapling-refresh: using_defaults
Mutex authdigest-client: using_defaults
Mutex lua-ivm-shm: using_defaults
Mutex ssl-stapling: using_defaults
Mutex proxy: using_defaults
Mutex ldap-cache: using_defaults
Mutex authn-socache: using_defaults
Mutex ssl-cache: using_defaults
Mutex default: dir="/opt/rh/httpd24/root/var/run/httpd/" mechanism=default 
Mutex mpm-accept: using_defaults
Mutex cache-socache: using_defaults
Mutex authdigest-opaque: using_defaults
PidFile: "/opt/rh/httpd24/root/var/run/httpd/httpd.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="apache" id=48
Group: name="apache" id=48
```

**Comment by ILMostro** [comment]
I tried adding the paths to `augeas`, as it seems to have hard-coded file paths.  However, there was no change in behavior:

```
# tail -n22 certbot-apache/certbot_apache/augeas_lens/httpd.aug 
let rec content = section (content|directive)
                | perl_section

let lns = (content|directive|comment|empty)*

let filter = (incl "/etc/apache2/apache2.conf") .
             (incl "/etc/apache2/httpd.conf") .
             (incl "/etc/apache2/ports.conf") .
             (incl "/etc/apache2/conf.d/*") .
             (incl "/etc/apache2/conf-available/*.conf") .
             (incl "/etc/apache2/mods-available/*") .
             (incl "/etc/apache2/sites-available/*") .
             (incl "/etc/apache2/vhosts.d/*.conf") .
             (incl "/etc/httpd/conf.d/*.conf") .
             (incl "/etc/httpd/httpd.conf") .
             (incl "/etc/httpd/conf/httpd.conf") .
             (incl "/opt/rh/httpd24/root/etc/httpd/conf.d/*.conf") .
             (incl "/opt/rh/httpd24/root/etc/httpd/httpd.conf") .
             (incl "/opt/rh/httpd24/root/etc/httpd/conf/httpd.conf") .
             Util.stdexcl

let xfm = transform lns filter
```

**Comment by bmw** [comment]
You should be able to control the names of the executables and the paths Certbot uses when searching for things like vhosts by setting values on the command line or in a [configuration file](https://certbot.eff.org/docs/using.html#configuration-file). Below is a snippet of the output of `certbot --help apache` showing the Red Hat defaults and configurable flags:
```
  --apache-enmod APACHE_ENMOD
                        Path to the Apache 'a2enmod' binary. (default: None)
  --apache-dismod APACHE_DISMOD
                        Path to the Apache 'a2dismod' binary. (default: None)
  --apache-le-vhost-ext APACHE_LE_VHOST_EXT
                        SSL vhost configuration extension. (default: -le-
                        ssl.conf)
  --apache-server-root APACHE_SERVER_ROOT
                        Apache server root directory. (default: /etc/httpd)
  --apache-vhost-root APACHE_VHOST_ROOT
                        Apache server VirtualHost configuration root (default:
                        /etc/httpd/conf.d)
  --apache-challenge-location APACHE_CHALLENGE_LOCATION
                        Directory path for challenge configuration. (default:
                        /etc/httpd/conf.d)
  --apache-handle-modules APACHE_HANDLE_MODULES
                        Let installer handle enabling required modules for
                        you.(Only Ubuntu/Debian currently) (default: False)
  --apache-handle-sites APACHE_HANDLE_SITES
                        Let installer handle enabling sites for you.(Only
                        Ubuntu/Debian currently) (default: False)
```
Please let me know if this doesn't work for you.

**Comment by ILMostro** [comment]
I'll check it out shortly.  Thanks for that info; I'm not sure if/how I missed that as I was going through the source files and commandline options.

Assuming that works, it would be a short-term fix.  I'm still curious about a potential solution that might deal with this scenario automatically.  

Thanks again.

**Comment by ILMostro** [comment]
That worked!

```
# ./letsencrypt-auto --apache --apache-server-root /opt/rh/httpd24/root/etc/httpd --apache-vhost-root /opt/rh/httpd24/root/etc/httpd/sites-enabled -d www.domain.tld
```
Obviously, the domain needs to be replaced with a valid domain.

**Comment by ILMostro** [comment]
Unfortunately, I have not had a way to automate the renewal using `cron`, as the process is trying to validate certs against `httpd` instead of `httpd24-httpd`.  If anyone has a handy work-around, it'd be greatly appreciated.  I might have to dig into the sources and documentation again when I get home.

**Comment by ILMostro** [comment]
The configuration file seems to be the best way for now.  Sorry, I haven't dealt with certs since the last time I posted on here; will post if/when I get the issue resolved.

**Comment by ILMostro** [comment]
It seems I had a missing argument passed to `scl` in the `cron` job.  The following line is a working cron-job to renew letsencrypt certs for  RHEL7 systems with `httpd-httpd24` as the running apache instance.  The package is provided via *SoftwareCollections*, e.g. if non-default `php` version is desired/required/used on systems.

```
26 15 * * * /bin/scl enable httpd24 /bin/bash && /bin/bash /opt/letsencrypt/letsencrypt-auto renew >> /var/log/le-renew.log
```

**Comment by joohoi** [comment]
Looks like this is resolved, closing the issue.

**Comment by johnsimcall** [comment]
Thanks for sharing, this post helped me.  I took a little different route to get the httpd24 Software Collection (scl) working with LetsEncrypt.  Here is what I did...

# cat /etc/letsencrypt/cli.ini 
apache-server-root=/opt/rh/httpd24/root/etc/httpd/
apache-challenge-location=/opt/rh/httpd24/root/etc/httpd/conf.d/

# scl enable httpd24 -- /usr/local/sbin/certbot-auto             |

**Comment by noloader** [comment]
Related, were have Apache 2.4 installed through SCL on out CentOS 7 VM. We are trying to use Certbot to update our HTTPS certificate (related, see [EFF CentOS7+Apache instructions](https://certbot.eff.org/lets-encrypt/centosrhel7-apache)).

Certbot is failing because it hardcodes `httpd.service`. Because of the Apache from SCL our service is actually `httpd24.service` (IIRC). Also see [Failed Let's Encrypt request](https://pastebin.com/K1WwFV9g).

**Comment by noloader** [comment]
@joohoi,

> Looks like this is resolved, closing the issue.

Could you add a section in the manual for:

1. How to configure CentOS+Apache when using SCL
2. How to continue/restart a failed transaction

For (1) I'm not sure if we did everything that was needed for CentOS using Red Hat's SCL. Maybe that should go in [CentOS7+Apache](https://certbot.eff.org/lets-encrypt/centosrhel7-apache) web page.

For (2) we need a procedure to continue/restart a failed transaction. The best I can tell the [manual](https://certbot.eff.org/docs/using.html) does not discuss the topic or detail a procedure.

**Comment by noloader** [comment]
@joohoi,

One other thing... If you need to setup a VM for testing, then setup a standard CentOS 7 VM. Then, follow the instructions documented at [How to update Apache to 2.4.29 using SCL?](https://unix.stackexchange.com/a/412171/56041) It takes you through enabling the Software Collections and installing an updated Apache and PHP.
