### ISSUE TITLE
standalone: add configurable wait before running challenges

### ISSUE THREAD

**Issue by henridwyer** [certbot/certbot#3525]
In a setup with a reverse proxy sending the challenges to the standalone webserver, the challenges can fail because the reverse proxy may require a few seconds to resolve the standalone webserver and start redirecting traffic to it. As a result, this sometimes causes the challenges to fail.

Adding a (configurable) wait between starting the standalone webserver and running the challenges would solve this issue.

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.
