### ISSUE TITLE
Create leaf.pem instead of cert.pem for new lineages

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#3539]
We see a fairly large number of sites misconfigured to serve only the end-entity (leaf) certificate, not the entire chain. I believe part of this is that we create a file `cert.pem` in addition to `fullchain.pem`. For someone looking to manually install a certificate, `cert.pem` looks like the natural choice. We can help people configure their sites correctly by renaming `cert.pem` to something else, like leaf.pem. This should be accompanied by a README in the certificates directory explaining what each file is.

We don't want to disrupt existing lineages where people are depending on certain naming conventions, but can can have Certbot take this new behavior for new lineages.

I realize this is a fairly disruptive change, but since part of our goal is to remove the human error and pain points in deploying certificates, it seems worthwhile.

**Comment by bmw** [comment]
Related: #2880

How do you suggest such a change is implemented? If a lineage already exists using `cert.pem`, continue using that convention (and maybe add an extra symlink for `leaf.pem`), but if we're creating a new lineage, only create `leaf.pem`?

**Comment by jsha** [comment]
Yep, exactly.

**Comment by schoen** [comment]
This might cause backwards compatibility problems with scripts and tools that integrate with Certbot -- for example, if there are scripts to integrate with control panels or something that automatically pull in `cert.pem` under that name. I'm concerned that we'd trigger a lot of integration bugs as a result, even though I think it would become clearer for people who use Certbot directly on the command line.

**Comment by ohemorange** [comment]
Maybe we could symlink fullchain.pem to something like the-thing-you-want.pem (but better named).

**Comment by schoen** [comment]
Well, at least creating a README could help because maybe then some people would look at it!

**Comment by schoen** [comment]
I'd also like to get @pde's view of the backwards-compatibility issue. I agree with @jsha's underlying concern, so if it weren't for the backwards-compatibility problem (that is, third-party scripts and tools that may wrap Certbot and assume the presence of `cert.pem`), I'd favor making this change.

**Comment by pde** [comment]
`leaf.pem` might have been a better choice, but I don't think we should change it now. We can do #1819 instead...

**Comment by pde** [comment]
@ohemorange unfortunately the-thing-you-want depends on what server you're using. Most often it's `fullchain.pem`, sometimes it's `cert.pem` and `chain.pem` separately, sometimes it's the concatenation of `fullchain.pem` and `privkey.pem`.  See #1250 and #1201.

**Comment by cowlicks** [comment]
I know at least one user this fooled (@rhodey)

**Comment by pde** [comment]
Conclusions:

* We need to scan deployed LE certs serverside and email the accountholders that got this wrong
* We can't get rid of `cert.pem`, since it's an interface
* We can (one day) rename it to `leaf.pem` or something, but only if we also deprecate `/etc/letsencrypt/live`, keeping it around but pointing users to a different directory with the new filenames.

**Comment by jsha** [comment]
Reopening to discuss: Rename cert.pem to leaf.pem, but always create a symlink from cert.pem to leaf.pem. The idea is that this somewhat increases the chance that someone just looking at the files will notice cert.pem links to leaf.pem and realize it's sufficiently un-straightforward to read the README.

**Comment by ohemorange** [comment]
I'm not super convinced that people will notice that cert.pem links to leaf.pem - if they just cat it, it'll still print the contents.

**Comment by jsha** [comment]
What about: rename + symlink + doc-only deprecation of cert.pem, with no intent to hard-deprecate for at least a year, maybe two.
