### ISSUE TITLE
Installation fails on RHL 7

### ISSUE THREAD

**Issue by basic612** [certbot/certbot#3544]
Using the [RHEL 7 / Centos 7 install instructions](https://certbot.eff.org/#centosrhel7-apache) I get an error about missing dependency when trying to install on an Amazon RHEL 7.2 instance.

Checking [RHEL 7 documentation](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Migration_Planning_Guide/sect-Red_Hat_Enterprise_Linux-Migration_Planning_Guide-Removed_Packages.html) I see that python-zope-interface is no longer available

> The following packages have been removed from Red Hat Enterprise Linux between version 6 and version 7 and are no longer supported
> 
> (snipped a load of irrelevant stuff)
> 
> python-zope-interface

Thanks for looking!

---

[root@rhel7]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.2 (Maipo)

[root@rhel7]# yum install python-certbot-apache
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Resolving Dependencies
--> Running transaction check
---> Package python2-certbot-apache.noarch 0:0.8.1-2.el7 will be installed
--> Processing Dependency: python2-certbot = 0.8.1 for package: python2-certbot-apache-0.8.1-2.el7.noarch
--> Processing Dependency: certbot = 0.8.1 for package: python2-certbot-apache-0.8.1-2.el7.noarch
--> Processing Dependency: python-augeas for package: python2-certbot-apache-0.8.1-2.el7.noarch
--> Running transaction check
---> Package certbot.noarch 0:0.8.1-2.el7 will be installed
---> Package python-augeas.noarch 0:0.5.0-2.el7 will be installed
--> Processing Dependency: augeas-libs for package: python-augeas-0.5.0-2.el7.noarch
---> Package python2-certbot.noarch 0:0.8.1-2.el7 will be installed
--> Processing Dependency: python2-acme = 0.8.1 for package: python2-certbot-0.8.1-2.el7.noarch
--> Processing Dependency: python2-dialog >= 3.3.0 for package: python2-certbot-0.8.1-2.el7.noarch
--> Processing Dependency: python2-configargparse >= 0.10.0 for package: python2-certbot-0.8.1-2.el7.noarch
--> Processing Dependency: python-psutil >= 2.1.0 for package: python2-certbot-0.8.1-2.el7.noarch
--> Processing Dependency: python-zope-interface for package: python2-certbot-0.8.1-2.el7.noarch
--> Processing Dependency: python-zope-component for package: python2-certbot-0.8.1-2.el7.noarch
--> Processing Dependency: python-parsedatetime for package: python2-certbot-0.8.1-2.el7.noarch
--> Processing Dependency: python-mock for package: python2-certbot-0.8.1-2.el7.noarch
--> Running transaction check
---> Package augeas-libs.x86_64 0:1.4.0-2.el7 will be installed
---> Package python-parsedatetime.noarch 0:1.5-3.el7 will be installed
---> Package python-psutil.x86_64 0:2.2.1-1.el7 will be installed
---> Package python-zope-component.noarch 1:4.1.0-1.el7 will be installed
--> Processing Dependency: python-zope-interface for package: 1:python-zope-component-4.1.0-1.el7.noarch
--> Processing Dependency: python-zope-event for package: 1:python-zope-component-4.1.0-1.el7.noarch
---> Package python2-acme.noarch 0:0.8.1-1.el7 will be installed
--> Processing Dependency: pytz for package: python2-acme-0.8.1-1.el7.noarch
--> Processing Dependency: python-pyrfc3339 for package: python2-acme-0.8.1-1.el7.noarch
--> Processing Dependency: python-pyasn1 for package: python2-acme-0.8.1-1.el7.noarch
--> Processing Dependency: python-ndg_httpsclient for package: python2-acme-0.8.1-1.el7.noarch
--> Processing Dependency: python-cryptography for package: python2-acme-0.8.1-1.el7.noarch
---> Package python2-certbot.noarch 0:0.8.1-2.el7 will be installed
--> Processing Dependency: python-zope-interface for package: python2-certbot-0.8.1-2.el7.noarch
---> Package python2-configargparse.noarch 0:0.10.0-1.el7 will be installed
---> Package python2-dialog.noarch 0:3.3.0-6.el7 will be installed
--> Processing Dependency: dialog for package: python2-dialog-3.3.0-6.el7.noarch
---> Package python2-mock.noarch 0:1.0.1-9.el7 will be installed
--> Running transaction check
---> Package dialog.x86_64 0:1.2-4.20130523.el7 will be installed
---> Package python-cryptography.x86_64 0:0.8.2-1.el7 will be installed
--> Processing Dependency: python-cffi >= 0.8 for package: python-cryptography-0.8.2-1.el7.x86_64
--> Processing Dependency: python-enum34 for package: python-cryptography-0.8.2-1.el7.x86_64
---> Package python-ndg_httpsclient.noarch 0:0.3.2-1.el7 will be installed
--> Processing Dependency: python-setuptools for package: python-ndg_httpsclient-0.3.2-1.el7.noarch
---> Package python-pyasn1.noarch 0:0.1.6-2.el7 will be installed
---> Package python-zope-component.noarch 1:4.1.0-1.el7 will be installed
--> Processing Dependency: python-zope-interface for package: 1:python-zope-component-4.1.0-1.el7.noarch
---> Package python-zope-event.noarch 0:4.0.3-2.el7 will be installed
---> Package python2-certbot.noarch 0:0.8.1-2.el7 will be installed
--> Processing Dependency: python-zope-interface for package: python2-certbot-0.8.1-2.el7.noarch
---> Package python2-pyrfc3339.noarch 0:1.0-2.el7 will be installed
---> Package pytz.noarch 0:2012d-5.el7 will be installed
--> Running transaction check
---> Package python-cffi.x86_64 0:0.8.6-2.el7 will be installed
--> Processing Dependency: python-pycparser for package: python-cffi-0.8.6-2.el7.x86_64
---> Package python-enum34.noarch 0:1.0.4-1.el7 will be installed
---> Package python-setuptools.noarch 0:0.9.8-4.el7 will be installed
---> Package python-zope-component.noarch 1:4.1.0-1.el7 will be installed
--> Processing Dependency: python-zope-interface for package: 1:python-zope-component-4.1.0-1.el7.noarch
---> Package python2-certbot.noarch 0:0.8.1-2.el7 will be installed
--> Processing Dependency: python-zope-interface for package: python2-certbot-0.8.1-2.el7.noarch
--> Running transaction check
---> Package python-pycparser.noarch 0:2.14-1.el7 will be installed
--> Processing Dependency: python-ply for package: python-pycparser-2.14-1.el7.noarch
---> Package python-zope-component.noarch 1:4.1.0-1.el7 will be installed
--> Processing Dependency: python-zope-interface for package: 1:python-zope-component-4.1.0-1.el7.noarch
---> Package python2-certbot.noarch 0:0.8.1-2.el7 will be installed
--> Processing Dependency: python-zope-interface for package: python2-certbot-0.8.1-2.el7.noarch
--> Running transaction check
---> Package python-ply.noarch 0:3.4-10.el7 will be installed
---> Package python-zope-component.noarch 1:4.1.0-1.el7 will be installed
--> Processing Dependency: python-zope-interface for package: 1:python-zope-component-4.1.0-1.el7.noarch
---> Package python2-certbot.noarch 0:0.8.1-2.el7 will be installed
--> Processing Dependency: python-zope-interface for package: python2-certbot-0.8.1-2.el7.noarch
--> Finished Dependency Resolution
Error: Package: python2-certbot-0.8.1-2.el7.noarch (epel)
           Requires: python-zope-interface
Error: Package: 1:python-zope-component-4.1.0-1.el7.noarch (epel)
           Requires: python-zope-interface
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by bmw** [comment]
Any thoughts @hogarthj?

**Comment by hogarthj** [comment]
The python-zope-interface package is in the optional channel on RHEL7 which is why it can't be in EPEL

As per the EPEL enabling instructions on the EPEL site any RHEL, as opposed to CentOS, users should enable the optional channel via subscription-manager

**Comment by pde** [comment]
I think this means we need to revise the instructions for that platform...

**Comment by verne-wv** [comment]
who manages the actual site https://certbot.eff.org/   ... its been MONTHS and nothing has been updated in regards to the python-zope-interface package ... I just wasted my time figuring all this out for Apache on RedHat 7   !!!!

**Comment by bmw** [comment]
Our link with the text "enable the EPEL repository" links to https://fedoraproject.org/wiki/EPEL#How_can_I_use_these_extra_packages.3F where it is explained that the optional repository has to be enabled as well to use EPEL.

Perhaps this isn't enough though. This would cause us to have to split RHEL7 and CentOS7 into separate categories, but we could change our link text to say "enable the optional and EPEL repositories" to draw more attention to it.

**Comment by chriszrc** [comment]
I think a separate explanation in warranted. The "note" about the "optional" channel at that link makes it look like you can skip that step. 

On top of that, since I'm running this on ec2, I don't have a personal subscription to redhat, and couldn't even add the optional channel the way they describe. For ec2 I had to follow these instructions:

https://forums.aws.amazon.com/thread.jspa?messageID=551601

Which boils down to:

`
  yum -y install yum-utils
  yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional
`

**Comment by akadata** [comment]
+1 chriszrc for 

  yum -y install yum-utils
  yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-opt

That worked for me in EC2 with 
[root@ns0 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Comment by SwartzCr** [comment]
There's a PR open for this now on the certbot website repo if anyone wants to comment there on the best way to explain this issue and fix: https://github.com/certbot/website/pull/195
I'll happily merge it ASAP if we can agree on a good way to explain it!

**Comment by SwartzCr** [comment]
@akadata @chriszrc @verne-wv would any of you like to comment on https://github.com/certbot/website/pull/195 ?

**Comment by SwartzCr** [comment]
This seems to be fixed in https://github.com/certbot/website/pull/208
Feel free to still provide feedback on https://github.com/certbot/website/pull/195
But I am going to close this issue, since the website now gives an installation path

**Comment by pkaramol** [comment]
sudo yum-config-manager --enable rhui-us-east-1-rhel-server-extras rhui-us-east-1-rhel-server-opt
sudo yum -y install yum-utils

but still ...


```--> Finished Dependency Resolution
Error: Package: python2-certbot-0.18.1-1.el7.noarch (epel)
           Requires: python-zope-interface
Error: Package: 1:python-zope-component-4.1.0-3.el7.noarch (epel)
           Requires: python-zope-interface
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by ivalexm** [comment]
In rhel 7.5, certbot can be installed by:
`yum install certbot python-zope-interface --enablerepo="rhel-7-server-rpms" --enablerepo="rhel-7-server-e4s-optional-rpms" --enablerepo=epel`

**Comment by jblom** [comment]
Had to slightly change @ivalexm 's command to make it work on my RHEL7 machine

yum install certbot python-zope-interface --enablerepo="rhel-7-server-rpms" --enablerepo="rhel-7-server-optional-rpms" --enablerepo=epel

**Comment by dineshv1234567** [comment]
@jblom Could you please help me out or anyone? 
> yum install certbot python-zope-interface --enablerepo="rhel-7-server-rpms" --enablerepo="rhel-7-server-optional-rpms" --enablerepo=epel
Loaded plugins: ulninfo

Error getting repository data for rhel-7-server-rpms, repository not found

**Comment by bmw** [comment]
@dineshv1234567, I'd recommend posting to https://community.letsencrypt.org for help like this.

**Comment by Faq** [comment]
had the same problem like @dineshv1234567, went with:
```
sudo yum localinstall http://mirror.centos.org/centos/7/os/x86_64/Packages/python-zope-interface-4.0.5-4.el7.x86_64.rpm
yum install certbot
```

**Comment by gentwins** [comment]
> had the same problem like @dineshv1234567, went with:
> 
> ```
> sudo yum localinstall http://mirror.centos.org/centos/7/os/x86_64/Packages/python-zope-interface-4.0.5-4.el7.x86_64.rpm
> yum install certbot
> ```

Thanks for solution but above link is died too.
This is the one thats alive

https://yum.oracle.com/repo/OracleLinux/OL7/optional/developer/x86_64/getPackage/python-zope-interface-4.0.5-4.el7.x86_64.rpm
