### ISSUE TITLE
Create new block during redirect enhancement

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#3550]
If redirect enhancement is requested and there are no blocks listening plaintextishly, create a new block, listen plaintextishly, and add a redirect statement to that block.

**Comment by ohemorange** [comment]
Although I am creating this issue, I note my dissent here, because consider two cases in how we deployed the cert. First, we previously installed a cert on a plaintext-ish block. In this case, that block already has a plaintextish listen directive on a non-443 port, and we would have found that block and added the redirect statement to it. Thus, we only encounter this problem in the second case, where we previously installed a cert on a sslish block that doesn't also have a plaintextish listen directive in it. This means that before we came along the user didn't get that http traffic at all, and now they do and it redirects to https.

@bmw @pde

**Comment by bmw** [comment]
We should kick this conversation down the road, but for the purposes of presenting the other side while this issue sits here publicly, I'll weigh in. I support this issue given the current state of the rest of Certbot. Certbot provides help output like this:
```
  --redirect            Automatically redirect all HTTP traffic to HTTPS for
                        the newly authenticated vhost. (default: None)
```
It also asks questions like this:
```
Please choose whether HTTPS access is required or optional.
-------------------------------------------------------------------------------
1: Easy - Allow both HTTP and HTTPS access to these sites
2: Secure - Make all requests redirect to secure HTTPS access
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel):
```
The `Easy` and `Secure` distinction sucks. Additionally, in this instance it's incorrect that `Easy` allows "both HTTP and HTTPS access to these sites." If you're site wasn't already set up for HTTP, it still won't be.

While the framing sucks when asked interactively (although the command line flag is very clear), the intent is to ask the user if they want an HTTP->HTTPS redirect. If they say yes, I think we should give it to them.

We certainly should not start listening on port 80 unless the user asked for it. Sounds like a good way to make people mad.

**Comment by ohemorange** [comment]
The correct way to do this is probably to always create a new server block when we find a non-sslish one. Then, when enhancing, add the redirect to the original block we modified, if we duplicated a block to create the new one.

**Comment by ohemorange** [comment]
This issue is probably obsoleted by #5297.

**Comment by bmw** [comment]
I think this issue is largely unrelated to #5297.

**Comment by bmw** [comment]
I still personally think this is an issue that should eventually be fixed either by adding this feature to our Nginx plugin or updating our prompts/documentation around redirects.
