### ISSUE TITLE
Recommended renewal strategy should not trigger rate limiting if the script is failing

### ISSUE THREAD

**Issue by dehnert** [certbot/certbot#3553]
Issue #3552 describes an issue where certbot would fetch a cert and then fail to save it. Because I'm running it twice a day ([as recommended](https://certbot.eff.org/all-instructions/)), I've hit the renewal frequency rate limit, so now I can't easily renew it, even though I've moved the missing directory.

This seems like it could be a wide class of problems: some error causes a new cert to be fetched, but a later error prevents it from being saved successfully. Even if certbot was modified to detect _this_ issue before getting a new cert (the topic of #3552), It might be more broadly nice if the recommended usage and rate-limiting config were such that rate-limiting wouldn't be triggered by a constantly-failing script. This could mean changing the recommended usage ([source](https://github.com/certbot/website/blob/master/_scripts/instruction-widget/templates/getting-started/renewal.html)) to alternating days or the rate-limiting to allow up to 15-20 certs a week. A third approach would be to maintain a count of renewal attempts, and automatically skip some renewal attempts if recent attempts have been failing. 

(The first two solutions would presumably be implemented in another repository, but between the third solution and the fact that #3552 is in this repo, I'm filing it here. Hopefully that's not too confusing.)

**Comment by bmw** [comment]
This is an interesting problem and something we should think about more. Thanks for reporting the issues and suggesting three different approaches, any of which would help mitigate the problem.

cc @pde, @schoen, @jsha

**Comment by jsha** [comment]
I think the quickest and easiest solution is to change the recommended usage to run every other day rather than every day.

**Comment by pde** [comment]
@jsha we run twice a day so that (with some OCSP code we haven't landed yet) we will have time to check for pending revocations and reissue if required, which under the BRs would have a maximum window of 24 hours.

**Comment by pde** [comment]
I think we just need to completely remove the class of bugs that can cause this failure mode. As far as I'm aware, they're all caused by people trying to edit or move files around in `/etc/letsencrypt`, and it shouldn't be that hard to be more robust in the way we handle those situations.

**Comment by jsha** [comment]
> I think we just need to completely remove the class of bugs that can cause this failure mode.

That's true, but bugs may always arise in the future, so it's good to be robust to this class of bugs.

> we run twice a day so that (with some OCSP code we haven't landed yet) we will have time to check for pending revocations and reissue if required

Good point!

What do you think about keeping track of failures and implementing a backoff? I.e. run twice a day but only attempt renewals if it's time to renew AND the most recent failure was > 2 days ago?

Alternately: What if we recommend to run the command twice a day but only attempt renewal for any given certificate every other day? We could do some cute hackery like `if daysRemaining % 2 == 0:`

**Comment by 0xpr03** [comment]
I've kinda hit the same error. I've had some nginx configuration failures after recent changes & had to try some times. Now I've hit the limit, 6 days before expiration, as I wasn't aware of auto-renewal failing.

**Comment by schoen** [comment]
@0xpr03, can you try posting on the forum for suggestions about what to do? https://community.letsencrypt.org/

Was the problem related to a situation where Certbot couldn't save the new certificates that it obtained?

**Comment by 0xpr03** [comment]
Weird, my post edit ist gone..
@schoen no no, I just had problems in my nginx config and apparently never got any information that the auto-renew failed. While figuring out what was causing my problem in all the config files I hit the `Failed Validation limit of 5 failures per account, per hostname, per hour`limit pretty fast and got a little bit panicky because of the expiration next Sunday.
I'd recommend to print some info besides having hit the rate limit. Something like "you can retry in an hour, as described in [the rate limit docs](https://letsencrypt.org/docs/rate-limits/).

**Comment by jsha** [comment]
I think it is correct to close this out. The original class of bugs that caused this problem is relatively rare now, and new bugs will be handled as they come up.
