### ISSUE TITLE
Play nicely with containers

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#3564]
Got the following feedback from someone who had tried to use certbot, but couldn't due to complications:

there's nothing specifically wrong with let's encrypt, it's more of a function of our infrastructure. in order to validate our domain with let's encrypt, we need to periodically (every ~3 months) pass an acme challenge by hosting a file they give us. this is relatively harder when using kubernetes, or any other container orchestration framework, because containers are scheduled across a variety of nodes depending on their resource constraints. each container usually does only performs a single role (e.g. run the web service, run nginx, run a single background job, etc.), so it's not as easy as just adding a cron job like the documentation says

one option is to spin up another container whose job it is to update the cert periodically, serve the acme challenge on some local server, link it to the nginx container, and have nginx proxy for that local server

or share a filesystem mount between the two containers, but that could be problematic because containers are separated across hosts (though kubernetes specifically does have a good abstraction for this)

another option is to directly integrate with nginx or haproxy by using their scripting extensions. for instance, nginx has the lua open resty module that lets you dynamically request certs and cache them within nginx, which is super nice because it doesn't involve any additional coordination between containers or host mounts

but there's no standard open resty image that does that for you easily. I spent a good few days writing and configuring one for my personal websites, and got it working, but imo it's not worth the effort right now

and that's really the ultimate issue with all of this - it's definitely possible, but it takes a good amount of time, and the other option is clicking a few buttons and getting a cert for 1 year or longer
so to let us focus on development and not ssl configuration, just buying a cert at this stage for 1 or more years makes more sense imo

questions:
does the plugin automatically request and renew certs for virtual hosts? will they be providing a docker image that has that functionality built it? does nginx need to be compiled with certain extensions (e.g. lua) to work with that functionality? how does it persist the certs? will the certs get cycled every time containers are restarted or rescheduled?

**Comment by pde** [comment]
Sounds like the nginx plugin *probably* wouldn't work for them, unless they have a single unique nginx instance terminating TLS for each domain they host (which becomes unlikely at scale). TLS-SNI-01 is built on that assumption. 

If it's violated, the two best options are:
1) have all of their webservers serve a redirect from `/.well-known/acme-challenge` to a dedicated authentication server that they use to provision all their certs, and run the webroot plugin there.  They might then need a simple internal API to grab the certs from their provision server.
2) use the DNS01 challenge, and provision from their DNS infrastructure. Certbot is currently working on nice support for that via the script plugin (#3521).

If they'd like to talk more about the most pragmatic strategies for deployment, https://community.letsencrypt.org is probably better than github tickets!

**Comment by pde** [comment]
Sorry, also answering some questions:

> does the plugin automatically request and renew certs for virtual hosts? 

if you ask it to

> will they be providing a docker image that has that functionality built it? 

our docker images should do that, yes

> does nginx need to be compiled with certain extensions (e.g. lua) to work with that functionality? 

I don't believe so

> how does it persist the certs? will the certs get cycled every time containers are restarted or rescheduled?

Certs get written to `/etc/letsencrypt/{archive,live}` by default, though you can configure that. If you push a shared account key into each container as it's spun up, you can give it the authority to request a new cert without having to re-prove domain control. Such authority persists for a reasonably long time (60 or 90 days at the moment, ask @jsha) after a given account key has been authorized to issue for a particular FQDN.

**Comment by cowlicks** [comment]
I think cases like this are out of the scope of certbot. My understanding is that certbot tries to make enabling tls really easy for average users. People who want to enable tls on kubernetes services are not average users. But they can still use LetsEncrypt!

I'd recommend checking out https://github.com/munnerz/kube-acme which seems to be designed for your use case.

There is also https://github.com/offblast/achmed which is pretty cool, but you'll have to ask @mischief for documentation.

**Comment by mischief** [comment]
probably want to look at https://github.com/jetstack/kube-lego instead - it's been around a bit longer.

i'm working on a custom kubernetes ingress with achmed which is designed a little different from kube-lego - it only handles tls for kubernetes Ingress, stores certs from ACME in etcd3 gpg-encrypted, and doesn't do http path routing.
