### ISSUE TITLE
certbot deleting dir acme-challenge nginx

### ISSUE THREAD

**Issue by rmalenko** [certbot/certbot#3567]
Nginx vhost has 
location ~ /.well-known\/acme-challenge {
    allow all;
}
Directory has /.well-known/acme-challenge/ path

After I run 
./letsencrypt-auto certonly --agree-tos --email info@com.nl --webroot -w /home/www/com.nl/httpdocs -d com.nl -d www.com.nl

The folder acme-challenge deleted and I got error message 
Detail: Invalid response from
   http://www.com.nl/.well-known/acme-challenge/06H_uJkoBpDtUqAM8ppL9d4GVwMRuQ286T7Y9ElGmUs

**Comment by bmw** [comment]
Certbot deletes the directory only after Let's Encrypt has connected to your server. Not deleting the directory if the user manually created it is covered by #1003. If you would like more help in debugging the problem, I need a little more information. Could you provide a full log of the failed run (which by default is saved in `/var/log/letsencrypt`)? Feel free to redact domains and e-mail addresses as you deem appropriate.

**Comment by cyplo** [comment]
Hello ! @rmalenko is this still an issue ?

**Comment by bmw** [comment]
Since there's not an actionable bug report here and it hasn't seen a response from the affected user in 6+ months, I'm closing this issue.
