### ISSUE TITLE
write normal output to logfile, too

### ISSUE THREAD

**Issue by dingens** [certbot/certbot#3572]
I am using `certbot renew -q` from within a cronjob. I noticed the debug log only contains the debug stuff, but not the normal output that is usually written to stdout (when not using `-q`).
However, the debug information doesn't help in analyzing what went wrong without the normal output giving some context ("processing ...conf", "no renewals attempted", etc).

I'd thus suggest to always write the latter details to the logfile, too (most importantly when `-q` is used, but I think it's helpful in any case)

0.8.1 on debian

**Comment by bmw** [comment]
That's a good idea. In general, we generate output printed to the terminal using

1. Python's `logging` module
2. The [IDisplay](https://github.com/certbot/certbot/blob/master/certbot/interfaces.py#L378) interface.
3. `print` statements

As you might expect, output generated from option 1, but output from options 2 or 3 are not.

**Comment by bmw** [comment]
I still think this is a good idea.
