### ISSUE TITLE
tests/integration/_common.sh script broken for interactive use

### ISSUE THREAD

**Issue by cowlicks** [certbot/certbot#3577]
I'm running a instance of boulder for local integration testing. Boulder recommends working with certbot in this way: 
> Check out the Certbot client from https://github.com/certbot/certbot and follow the setup instructions there. Once you've got the client set up, you'll probably want to run it against your local Boulder. There are a number of command line flags that are necessary to run the client against a local Boulder, and without root access. The simplest way to run the client locally is to source a file that provides an alias for certbot (certbot_test) that has all those flags:
```
source ~/certbot/tests/integration/_common.sh
certbot_test certonly -a standalone -d example.com
 ```

But here is what happens for me:
```bash
(venv) ➜  letsencrypt git:(master) ✗ source tests/integration/_common.sh
Root integration tests directory: /tmp/leiteKaS
(venv) ➜  letsencrypt git:(master) ✗ certbot_test certonly -a standalone -d example.com
usage: 
  certbot [SUBCOMMAND] [options] [-d domain] [-d domain] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
cert. Major SUBCOMMANDS are:

  (default) run        Obtain & install a cert in your current webserver
  certonly             Obtain cert, but do not install it (aka "auth")
  install              Install a previously obtained cert in a server
  renew                Renew previously obtained certs that are near expiry
  revoke               Revoke a previously obtained certificate
  register             Perform tasks related to registering with the CA
  rollback             Rollback server configuration changes made during install
  config_changes       Show changes made to server config during installation
  plugins              Display information about installed plugins
certbot: error: unrecognized arguments: --config-dir /tmp/leiteKaS/conf --work-dir /tmp/leiteKaS/work --logs-dir /tmp/leiteKaS/logs
```

Basically the `$store_flags` line in `_common.sh` isn't working right.

I can apply [this dirty hack](https://gist.github.com/cowlicks/bf1521fc1407f07d59a6e8a373f6b135) to get things to work, but there must be a better way.

**Comment by bmw** [comment]
What shell are you using @cowlicks? Boulder's instructions work fine for me with both bash and dash on Ubuntu 16.04.

**Comment by cowlicks** [comment]
@bmw I'm using zsh. I just tried with bash and it works. So this must be a zsh bug.

It'd be nice if certbot had a clean workaround, but it probably isn't worth spending much time on.

**Comment by bmw** [comment]
If working on `certbot-auto` has taught me anything, it's that writing a shell script that works on the massive variety of POSIX compliant (and not so POSIX compliant) shells out there is a real pain. If you find a way to make this work in zsh without breaking support for other shells, I'll review and merge.

**Comment by orboan** [comment]
Hello,

I've installed cerbot in CentOS7 and it works. I've also run boulder docker containers to set a local boulder, using docker-compose as explained, and all tests passed ok.

Now, trying to configure certbot to use local boulder, it is said to run
source ~/certbot/tests/integration/_common.sh

But the fact is that in my home directory (regular user or root) there is no certbot directory. So I cannot load the alias with all options to connect to local boulder. Have I understood it well? Where should the script _common.sh be located? I cannot find it.

Thanks for your help.
