### ISSUE TITLE
Plugins packaging

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#358]
Here's an idea: move all plugins to separate git repositories and distribute them in a separate PyPI/Debian/etc. packages (that is all apart from standalone, which is probably best to be left in the main distribution). setuptools entry_points system, which is already being used in `master`, makes such transformation a breeze.

| entry point name | GitHub | PyPI | Debian |
| --- | --- | --- | --- |
| apache | letsencrypt-apache | letsencrypt-apache | letsencrypt-apache |
| nginx | letsencrypt-nginx | letsencrypt-nginx | letsencrypt-nginx |
| ... | ... | ... | ... |
- PyPI packages would have to `install_requires.append('letsencrypt')`, as well as set up `entry_points` appropriately
- Debian plugin packages would `Require: letsencrypt` as well as specific server software, e.g. `letsecrnypt-apache` would `Require: apache`. `letsencrypt` Debian package could `Suggest: letsencrypt-apache`, etc.
- CLI would automatically populate `--{plugin_name}-{option_name}`, similarly `{plugin_name}_{option_name}` for config

This would simplify a lot of things, such as release process, Python 3 compatibility transition, OS support (e.g. AFAIR augeas, necessary for apache or nginx plugins, is not even available on Windows, what about it's py3 compat?)... Main cons is probably less control over the namespace (e.g. PyPI), or establising unique `{plugin_name}` etc.

https://github.com/kuba/lets-encrypt-preview/tree/cli brings us closer to the required architecture (moves plugin specific constants and CLI arguments to plugins subdirs, first attempt at unique plugin names problem)

cc: @jdkasten, @fmarier

**Comment by fmarier** [comment]
In the above example, you'd still have a base package (`letsencrypt`) that would contain the files common to all plugins?

From a Debian point of view, it's very easy to build several "binary" packages from the same source package. We already build a separate letsencrypt-doc package for example. These binary packages can have different dependencies too.

So I don't really have a strong opinion either way.

**Comment by kuba** [comment]
Yes, there would be a base package (`letsencrypt`) that does all the CLI logic and loads entry_points plugins.

**Comment by kuba** [comment]
https://github.com/letsencrypt/lets-encrypt-preview/pull/376#issuecomment-99358828 Quick summary: great idea for the future, but we are not yet ready. Sounds plausible to me. I will close this for now, noting that #376 is a big step towards this goal.

**Comment by kuba** [comment]
Reopening for launch. Progress made with #531.

**Comment by jsha** [comment]
This is now done, to the extent that the plugins are their own packages. I think we've decided to keep maintaining everything in the same repo, though.
