### ISSUE TITLE
certbot-auto 0.9.0 not quiet anymore

### ISSUE THREAD

**Issue by manuelmeurer** [certbot/certbot#3592]
I have a cron job set up that runs `sudo /usr/local/bin/certbot-auto renew --quiet` every day. Normally it produces no output but yesterday it updated `certbot-auto` to v0.9.0 and since then I get the following output on every run:

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Cert not yet due for renewal
Cert not yet due for renewal
Cert not yet due for renewal
Cert not yet due for renewal
Cert not yet due for renewal
Cert not yet due for renewal
Cert not yet due for renewal
```

**Comment by Philippe23** [comment]
Seeing same since certbot-auto self-updated to 0.9.0 yesterday.

**Comment by bmw** [comment]
Thanks for reporting this. I've repoed the problem and I'm working on a patch. We'll probably do a 0.9.1 release to resolve this.
