### ISSUE TITLE
Client should look up identifiers during validation process

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#360]
So that it can (a) verify the identifier points at itself, and (b) give a warning if there are multiple IP addresses for the identifier, as extra work will probably be needed to ensure each IP address is capable of answering the challenges.

**Comment by schoen** [comment]
I'm not very convinced the client can know if the identifier points at itself. A number of servers are behind some kind of proxy or firewall where they don't know all the IP addresses at which other people can reach them. Notably, AWS is this way: when I run `ifconfig` on an AWS instance, I don't see any public IP address at all, yet there are public IP addresses that Amazon maps to that instance. This can also be a consequence of various methods for supporting IPv6 on operating systems or hosts that aren't natively fully IPv6-capable.

**Comment by jsha** [comment]
Yes, this is challenging. In theory the client can look up its IP address and attempt to connect to it, but if we are limited in the extent to which we can connect to ourselves, or if we want to limit the number of webserver reconfigurations, that could be hard.

We could define some way for the server to tell the client "Here's the IP address I see your requests coming from," and the client could check that.

We should probably at least have the client check that the name resolves in DNS, and warn if either (a) it doesn't resolve, or (b) it resolves to more than one IP. Doesn't have to be a hard fail, but this can help users figure out a whole class of errors that might be hard to debug otherwise.

**Comment by jsha** [comment]
This ticket is obsolete. `simple_verify` does some of this.
