### ISSUE TITLE
standalone plugin does not respect new --preferred-challenges flag

### ISSUE THREAD

**Issue by yareckon** [certbot/certbot#3601]
The standalone plugin will no longer respect the new --preferred-challenges flag.  

this can easily be seen for instance by starting a process that will occupy port 443, and limiting preferred challenges to challenges that will not use that port: 
This works fine:
certbot-auto certonly --force-renewal --standalone --standalone-supported-challenges http-01
But this new syntax will bomb out
certbot-auto certonly --force-renewal --standalone --preferred-challenges http-01
with "MisconfigurationError: At least one of the (possibly) required ports is already taken."  .. because it tests 443 despite being told not to.  
This is probably just a problem in the commandline parsing somewhere, or a function referring back the old config values.

**Comment by bmw** [comment]
Thanks for reporting this problem @yareckon. It will be fixed in the 0.9.2 release.

**Comment by yareckon** [comment]
Many thanks!
