### ISSUE TITLE
Python 3 and dnspython

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3603]
When adding support for the DNS challenge to `acme`, [I suggested we avoid adding conditional dependencies](https://github.com/certbot/certbot/pull/2061#r71929407) due to [the problems they cause](https://github.com/certbot/certbot/issues/3455).

`dnspython` says that they've had a single codebase for Python 2 and Python 3 since version 1.12 ([source](https://github.com/rthalley/dnspython#new-since-1120)). This version of `dnspython` doesn't work on Python 3 for our use case though. When importing `dns.resolver` in `acme/dns_resolver.py`, you get a traceback like the following:

```
Traceback (most recent call last):
  File "/root/venv3/lib/python3.4/site-packages/acme/dns_resolver.py", line 6, in <module>
    import dns.resolver
  File "/root/venv3/lib/python3.4/site-packages/dns/resolver.py", line 32, in <module>
    import dns.flags
  File "/root/venv3/lib/python3.4/site-packages/dns/flags.py", line 51, in <module>
    _by_value = dict([(y, x) for x, y in _by_text.iteritems()])
AttributeError: 'dict' object has no attribute 'iteritems'
```

Normally, I'd suggest we just bump the version number, however, `dnspython 1.12` is the latest version available on some systems we are packaged such as RHEL/CentOS 7 and this package works properly when using Python 2. Other potential solutions to this problem are making this dependency conditional or simply adding a comment about these problems to `acme/setup.py`.

**Comment by hobarrera** [comment]
> however, dnspython 1.12 is the latest version available on some systems we are packaged such as RHEL/CentOS 7

Downstream packagers can always avoid packaging newer certbot versions until they update their dnspython packages. That's really a non-issue.

**Comment by bmw** [comment]
We removed `dnspython` as a dependency in 0.11.0.
