### ISSUE TITLE
Checking for optional dependencies at runtime

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3604]
We have a problem with our optional dependencies `psutil` and `dnspython` that was identified in #3599.

#### Problem

1. The user does not install the optional dependency when installing our packages.
2. We try to import the optional dependency at runtime. We catch the `ImportError` if the package is not available, however, if this package was installed through other means, it may not be the version we require causing other errors at import time or later in execution.

#### Solution

Use `pkg_resources.get_distribution(<module_name>).version` to get the version number. If the function raises `pkg_resources.DistributionNotFound`, we assume this package isn't available. Once we have the version number, we use something like the class `distutils.version.StrictVersion` to compare the version number to the one we require. If the version number is okay, we import the module, otherwise, we don't.

@erikrose, what do you think?

**Comment by bmw** [comment]
#### Potential concerns

* `pkg_resources.get_distribution` raises something other than `pkg_resources.DistributionNotFound`
* the return value of `pkg_resources.get_distribution` doesn't have a `version` attribute
* reliably comparing version numbers as this depends on the versioning scheme used which can be changed by our dependency package maintainers in subsequent releases

Keep in mind that we need to support a dizzying number of `setuptools` versions. I haven't looked into how much `pkg_resources` has changed in the past couple years.

Another and much simpler option is to remove optional dependencies like this entirely. This would be a large change for a point release, especially as we'd be breaking the challenge API in `acme`. If we go this route, I think we should wait for 0.10.0.

**Comment by erikrose** [comment]
In general, I'm in favor of reducing or eliminating conditional or optional dependencies, because conditions lead to differences, differences to uncaught bugs, bugs to anger, anger to hate, and hate to the Dark Side.

Absent that, I like using pkg_resources. I did [something like this in peep](https://github.com/erikrose/peep/blob/master/peep.py#L65-L78), and I don't recall having any reported problems (so I recommend stealing that verbatim). That said, it's worth testing whether non-pip ways of installing packages (e.g. apt-get) fail to show up in `pkg_resources.require()` checks.

**Comment by bmw** [comment]
+1 to simplicity and not contributing to the power of the Sith.

Testing that code on Debian and Red Hat with both Python 2 and Python 3, it always managed to find a package regardless of how it was installed. More importantly in my opinion, the `except` statement always properly caught any errors. I think we should implement this for 0.9.2 and consider removing these dependencies entirely for 0.10.0.
