### ISSUE TITLE
nginx + separate ssl/non-ssl blocks

### ISSUE THREAD

**Issue by pnomolos** [certbot/certbot#3605]
We have our sites set up with two server blocks per site, as so:

```
server {
    listen 80;
    server_name domain.name;
    return 301 https://$http_host$request_uri;
}

server {
    listen 443;
    server_name domain.name;
    # ...
}
```

(See https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#using-if - it's explicitly recommend to set things up this way rather than using an if block).

The nginx plugin currently doesn't deal very well with this set up.  I had to manually disable my SSL directives in the SSL server block for the certbot auth to succeed, then it created all the directives in the non-SSL server block, resulting in a redirect loop :)

/cc @ohemorange @bmw 

(In reference to: https://community.letsencrypt.org/t/seeking-feedback-on-new-certbot-nginx-plugin/20693/7?u=pnomolos)

**Comment by ohemorange** [comment]
Thanks for your feedback! Can you let us know what errors you were getting, such that you had to manually disable your SSL directives for the certbot auth to succeed?

**Comment by ohemorange** [comment]
Also, could you post your entire original config file?

**Comment by pnomolos** [comment]
@ohemorange Without disabling the SSL parameters I was getting the following:

`Failed authorization procedure. domain.name (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Failed to connect to [IP]:443 for TLS-SNI-01 challenge`.

Once I got it working, certbot "succeeded", but ended up with a slightly hashed configuration.

Here's the original (anonymized) configuration:

```
upstream app_server {
    # for UNIX domain socket setups:
    server unix:/home/deployer/vhosts/domain.name/shared/tmp/sockets/unicorn.sock;
}

server {
    listen 80;
    server_name domain.name;
    return 301 https://$http_host$request_uri;
}

server {
    listen 443;

    ssl on;
    
    # These had to be commented out for auth to even succeed
    ssl_certificate /etc/nginx/ssl/STAR_domain_name.pem;
    ssl_certificate_key /etc/nginx/ssl/STAR_domain_name.key;

    client_max_body_size 4G;
    server_name domain.name;

    keepalive_timeout 5;

    # path for static files
    root /home/deployer/vhosts/domain.name/current/public;

    try_files $uri/index.html $uri.html $uri @app;

    # Rails error pages
    error_page 503 @maintenance;
    error_page 500 502 504 /500.html;
    location = /500.html {
      root /home/deployer/vhosts/domain.name/current/public;
    }

    set $maintenance off;

    if (-f /home/deployer/vhosts/domain.name/current/public/system/maintenance.html) {
      set $maintenance on;
    }

    if ($http_maintenance = 'disable') {
      set $maintenance off;
    }

    if ($maintenance = on) {
      return 503;
    }

    location @maintenance {
      if (-f $request_filename) {
        break;
      }
      rewrite ^(.*)$ /system/maintenance.html break;
    }

    location @app {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_set_header Host $http_host;

      proxy_redirect off;

      proxy_pass http://app_server;
    }
}
```

**Comment by zeropopular** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mrniceguyzero@gmail.com
    Domain thezeroworld.com has exceeded the max emails per hour (7/7 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:35174 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by node87.certushost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bthrc-0006qQ-UF
	for zero@thezeroworld.com; Mon, 10 Oct 2016 17:12:01 -0400
Date: Mon, 10 Oct 2016 14:11:20 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1476133880;
	bh=Gv2UlvLEU/KLL0uqyAZER954ztYDRnxU/Yy9Xlmtkao=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Cu210hoj5bC6gGT4bqV1rJMJSeQyQfo/iiZpEq260zS+Ne1KL78F0/Cu6MtF/0Xeg
	 jquRfiC39Gra1d8f0AHyD0axNMNvSP3WeWDF7Ov5eJ+UrwCgfJk/VSKy6w3fe77Nlq
	 /mrPPfKmQgCRfGpMQ9op+m9ExJ/TvFJXBq6hlCvU=

**Comment by ohemorange** [comment]
Ok, looks like this is a bug on our end - since the original config has `listen 443; ssl on;` rather than `listen 443 ssl;`, we incorrectly fail to copy over the `ssl on;` to the block we use for authorization. We're working on getting a fix out; it is our goal to support your original, unmodified config.

**Comment by pnomolos** [comment]
@ohemorange Cool, thanks!  For now I'm using the certbot-modified variant, but being able to keep the original config would be optimal :)
