### ISSUE TITLE
Client should check OCSP status after issuing

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#361]
Our OCSP responder should have a 'good' OCSP response available for a certificate immediately upon issuance. If the client double-checks for this, we can surface errors at a time when the Subscriber is still paying attention. This will also help ensure that OCSP Stapling will work properly.

**Comment by jsha** [comment]
Here's an example openssl commandline I used to check OCSP on EFF's certificate:

```
openssl ocsp -sha256 -issuer sub.class2.server.ca.pem  -url http://ocsp.startssl.com/sub/class2/server/ca -cert www.eff.org2.pem  -CAfile sub.class2.server.ca.pem -no_nonce -header Host ocsp.startssl.com 
```

where sub.class2.server.ca.pem is the intermediate certificate.

**Comment by jdkasten** [comment]
Will OCSP really be updated that quickly?  I have run an OpenSSL OCSP
server and you have to restart it for new certificates.

I have also personally experienced StartCom's OCSP servers not resolving
new certificates immediately.

In which cases would the server issue a certificate and then immediately
revoke it?  This seems like a problem with Boulder issuance if this is the
case as revocation doesn't really work.  Do you propose this more as a test
against Boulder?

**Comment by jsha** [comment]
Yep, I'm thinking of this more as a test against Boulder. It seems like OCSP is easy to screw up, and it may be hard to notice when we do.

I'm not surprised OpenSSL's built-in OCSP server needs to restart for new certificates. My understanding is that most of the OpenSSL command-line client is meant to be treated more as demo-quality code than production code.

I think we *may* be required to respond with something other than "Unknown" to OCSP responses starting immediately from certificate issuance, and I'm planning to write the code so we are able to do so. But it's possible that not everyone does this successfully.

**Comment by jdkasten** [comment]
For reference, the cert_manager branch now runs OCSP queries for all of the stored certificates.  ```./venv/bin/letsencrypt --agree-eula revoke```  will bring up the menu.

Nothing is displayed on the screen if OCSP is valid.  Revoked appears if the cert is revoked and (OCSP Failure) appears if there is an error in the OCSP query.

The branch seems to be in pretty stable condition, but unittests haven't been written yet.

**Comment by jsha** [comment]
We should just consider this part of #956
