### ISSUE TITLE
certbot-auto renew ignores --key-path

### ISSUE THREAD

**Issue by fresheneesz** [certbot/certbot#3611]
I tried a dry run of renewal with the following command:

`./certbot-auto renew --key-path path/to/my/privateKey.pem --dry-run`

and it generated a key. Shouldn't it be using the key I specify? Here's the full output:

```
/root/.local/share/letsencrypt/lib/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 i            supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Py
  DeprecationWarning
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/<my domain>.conf
-------------------------------------------------------------------------------
Cert not due for renewal, but simulating renewal for dry run
Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for <my domain>
http-01 challenge for <my domain 2>
http-01 challenge for <my domain 3>
http-01 challenge for <my domain 4>
Waiting for verification...
Cleaning up challenges
Generating key (4096 bits): /etc/letsencrypt/keys/0006_key-certbot.pem
Creating CSR: /etc/letsencrypt/csr/0006_csr-certbot.pem
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)

Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/tixit.me/fullchain.pem (success)
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates above have not been saved.)
```

**Comment by bmw** [comment]
While we would like to support this behavior in the future, `--key-path` cannot be currently used in this way. The help output for the flag is:
```
  --key-path KEY_PATH   Path to private key for cert installation or
                        revocation (if account key is missing) (default: None)
```
We should also improve this help output which is the topic of #3386.

**Comment by fresheneesz** [comment]
"--key-path cannot be currently used in this way"

What way can it be used? I agree that the description there needs to be improved - I have no idea what "if account key is missing" means or how that implies what you could do with that parameter other than what i'm trying to do (specify the private key to use).

**Comment by bmw** [comment]
It can be used to automatically install the certificate/private key you already have to a web server like Apache or Nginx or to revoke a certificate you obtained from Let's Encrypt.

**Comment by forsan-co** [comment]
dear bmw, i have get similar problem, i want renew,  and it generated  a new key named "0001_key-certbot.pem",
 but in my nginx vhost conf,  i use  "/etc/letsencrypt/keys/0000_key-certbot.pem" , it's my first generation , when i use renew  command "/my/path/certbot-auto renew --dry-run", 
should i change my original conf to "0001_key-certbot.pem" ?
and when i replaced as 0001,
i have reloaded nginx, and nginx shows me 
"Reload service nginx... nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/letsencrypt/keys/0001_key-certbot.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
 done"



i have some question, 
why auto-renew cannot auto replace 0000_key-certbot.pem.....
and how to solve this problem, thx so much~

**Comment by snez** [comment]
@bmw what does that mean, the documentation is really bad for --key-path and --fullchain-path - all we need to do is to generate the files in a given path so that they can be used from within the web server configuration files. How do you generate them at a specific path?

**Comment by lichtamberg** [comment]
Yeah the description is really bad and i spent the whole day figuring out what I did wrong.

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.
