### ISSUE TITLE
certbot-auto igoring --key-path

### ISSUE THREAD

**Issue by fresheneesz** [certbot/certbot#3612]
I generated a certificate using the following command:

`./certbot-auto certonly --rsa-key-size 4096 --key-path tixit/privateKey.pem --webroot -w path/to/my/webroot -d <my domain 1> -d <my domain 2> -d <my domain 3> -d <my domain 4>`

When I used the certificate `fullchain.pem`, it said there was a mismatch between my cert and my key, and so I checked and the cert did indeed match with a newly generated key in the `/etc/letsencrypt/live/<my domain>/` folder. My specified key was smaller than 4096, so maybe it just thought "ok i'll make a new one" without telling me? Either it should use my specified key, or it should error and say my key doesn't match my key size spec. Something's going wrong here.

**Comment by bmw** [comment]
While we would like to support this behavior in the future, `--key-path` cannot be currently used in this way. The help output for the flag is:
```
  --key-path KEY_PATH   Path to private key for cert installation or
                        revocation (if account key is missing) (default: None)
```
We should also improve this help output which is the topic of #3386.

**Comment by bmw** [comment]
Related #3611

**Comment by fresheneesz** [comment]
I responded in #3611, tho this is really the more general issue I think.

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.
