### ISSUE TITLE
Debian packages for 13.10 ubuntu?

### ISSUE THREAD

**Issue by Ashviniv** [certbot/certbot#3628]
Can Anyone help me where should I get debian packages to install cerbot on ubuntu 13.10?. When I am trying to install cerbot using `./certbot-auto` it results following error:
````
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libtinfo5 : Breaks: dialog (< 1.2-20130523) but 1.1-20080819-1 is to be installed
 logrotate : Depends: cron or
                      anacron but it is not going to be installed or
                      cron-daemon
 python-dev : Depends: python (= 2.6.5-0ubuntu1.1) but 2.7.5-5ubuntu1 is to be installed
              Depends: python2.6-dev (>= 2.6.5) but it is not going to be installed
 python-virtualenv : Depends: python-support (>= 0.90.0) but it is not going to be installed
                     Depends: python-setuptools (>= 0.6.10) but it is not going to be installed
                     Depends: python-pip but it is not going to be installed
 python2.7 : Breaks: python-virtualenv (< 1.7.1.2-2~) but 1.4.5-1ubuntu1 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
````

So, I am trying to find out packages to install certbot.

**Comment by pde** [comment]
1. It looks like you have a debian package problem that's preventing the `certbot-auto` script from getting to the step where it builds a python venv. If you want, you could look at [this script](https://github.com/certbot/certbot/blob/master/letsencrypt-auto-source/pieces/bootstrappers/deb_common.sh) to debug why that's failing on your system.
2. Alternatively, you could [follow our developer instructions](https://certbot.eff.org/docs/contributing.html#running-a-local-copy-of-the-client) to run without bootstrapping. Just skip over the line that says `./letsencrypt-auto-source/letsencrypt-auto --os-packages-only`, and figure out how to get the OS-level dependencies working yourself (most of the Python ones will still be handled nicely inside a venv for you).
3. We aren't going to provide official packages for such an old, non-LTS release of Ubuntu. But if you really want to try, I would suggest starting with jonathonf's [Trusty PPA]( https://launchpad.net/~jonathonf/+archive/ubuntu/letsencrypt). Maybe that will just work on Ubuntu 13.10.  Or maybe you could re-build the packages in it from source and have them work.
