### ISSUE TITLE
Include www variant by default

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#363]
When configuring for example.com, the client should by default attempt to authorize itself for both example.com and www.example.com, and issue a certificate containing both.

Similarly, when configuring for www.example.com, the client should also attempt to authorize both domains.

We should only attempt do this if a DNS lookup reveals that both hostnames resolve to the same address.

**Comment by kuba** [comment]
Is it really necessary? Seems like a bad idea from the UX point of view. Also, what would I have to do, if I don't want the prefix to be included? If we really have to, then I'd suggest `--add-www` defaulting to `False`.

**Comment by jsha** [comment]
If you consider the UX of end users, I think it's actually a win. It's very common for a site to host both example.com and www.example.com. If a user visits www.example.com, with HSTS, and gets a certificate warning, we are not accomplishing our goals of universal easy-to-use HTTPS encryption.

The way StartSSL goes about this is that, if they validate `example.com`, they require you to issue a cert with at least one additional SAN under example.com, e.g. `foo.example.com`, and they recommend that `www` is a good one. We could follow that model on the client side. To be absolutely clear, I'm not suggesting we forbid single-name certs on the server side, just that we encourage the correct behavior with good defaults.

**Comment by PatrickHeppler** [comment]
Comodo PositiveSSL certificates also cover example.com and www.example.com by default.
Most configs I've seen run both names within one vhost.

**Comment by jsha** [comment]
More detail on this:

If a Subscriber requests example.com, we should attempt to include www.example.com as well. If a Subscriber requests www.example.com, we should attempt to include example.com as well.

'Attempt to include' == First, DNS lookup the requested name and store the result. Second, DNS lookup the other name and compare the result. If they are the same, proceed to attempt authorization for both names. Otherwise, attempt authorization only for the requested name.

I would suggest that this should be opt-out, with an optional flag --no-www.

**Comment by schoen** [comment]
The DNS lookup can be done via

`socket.gethostbyname(name) == socket.gethostbyname("www." + name)`

Apart from the possible problem of split DNS or servers that are for some reason not allowed to make outbound DNS requests at all, this could go awry given round-robin DNS.  For example,

`socket.gethostbyname("www.google.com") == socket.gethostbyname("www.google.com")`

is usually False!

There is `socket.gethostbyname_ex` which will return multiple addresses, so one strategy would then be

`bool(set(socket.gethostbyname_ex("www.google.com")[2]).intersection(set(socket.gethostbyname_ex("www.google.com")[2])))`

Amusingly the google.com and www.google.com names don't resolve to any of the same IP addresses for me at the moment, but this technique seems feasible for most servers to determine whether it's plausible that the same HTTP server will handle requests to both kinds of names.

**Comment by schoen** [comment]
To be clear, the strategy that I'm thinking of for the actual code is something like

`bool(set(socket.gethostbyname_ex(basename)[2]).intersection(set(socket.gethostbyname_ex("www." + basename)[2])))`

An alternative and possibly clearer way of writing this is

`not set(socket.gethostbyname_ex(basename)[2]).isdisjoint(set(socket.gethostbyname_ex("www." + basename)[2]))`

**Comment by pde** [comment]
Instinctively I feel that plugins should be returning all of the names that a server is answering for including the variants with and without `www.`, but perhaps the issue is that too often the vhost is just * and we know the domain only from the command line?  Or are there other cases where this is needed?

**Comment by jsha** [comment]
I think another common case is that there's a single vhost for foo.com, and www.foo.com "just works" because it's also the default vhost.

**Comment by jgelens** [comment]
Including example.org when creating www.example.org is pretty common. SSL server test tools also check this. This shows up for ssllabs: ``Prefix handling: Not valid for "example.org"   CONFUSING``. Creating 2 certs for this use-case would be inconvenient.

**Comment by casz** [comment]
This is definitely still a issue especially when trying to setup a Synology with DSM 6's included function for letsencrypt

**Comment by jsha** [comment]
The established behavior is to not include www, and I think it would be too disruptive to change now. Closing.
