### ISSUE TITLE
Be more conservative when suggesting domains in Apache

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3638]
I did this in Nginx by filtering all names through `certbot.util.enforce_le_validity`. I think we should do the same thing here, otherwise, we suggest the user obtains a certificate for things like wildcards.

**Comment by dashaxiong** [comment]
The `certbot_apache.tests.MultipleVhostsTest.test_get_all_names` expects to find a wildcard domain for "*.blue.purple.com". This test would need to be altered once the names are filtered.

**Comment by dashaxiong** [comment]
The `certbot.util.enforce_le_validity` also rejects domain names which have less than two labels. For instance "ip-172-30-0-17" which is set in `certbot_apache.tests.util.py:get_vh_truth`. This means that I also had to change the number of domains expected in the `certbot_apache.tests.MultipleVhostsTest.test_get_all_names_addrs` once the names are filtered.

**Comment by dashaxiong** [comment]
Please ignore my commit above, I didn't realise this issue was already being dealt with.
