### ISSUE TITLE
[nginx] Cert for two domains in one virtaulhost fails

### ISSUE THREAD

**Issue by emilstahl** [certbot/certbot#3642]
When trying to obtain or renew a cert for two domains which is listed in `server_name` in one virtualhost the operation fails.

### Fails
**00-default.conf**
`server_name   _ example.com sub.example.com;`

```
# ./certbot-auto renew --dry-run
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/example.com.conf
-------------------------------------------------------------------------------
Cert not due for renewal, but simulating renewal for dry run
Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for example.com
tls-sni-01 challenge for sub.example.com
Cleaning up challenges
Attempting to renew cert from /etc/letsencrypt/renewal/example.com.conf produced an unexpected error: nginx restart failed:

nginx: [emerg] a duplicate default server for 0.0.0.0:443 in /etc/letsencrypt/le_tls_sni_01_cert_challenge.conf:36
. Skipping.
```

### Works
**00-default.conf**
`server_name   _ example.com;`

**sub.conf**
`server_name   sub.example.com;`

### Info
```
# ./certbot-auto --version
letsencrypt 0.9.3
# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
```

**Comment by bmw** [comment]
cc @ohemorange

**Comment by ohemorange** [comment]
As far as I know, it is impossible to have two certificates in a single server block in Nginx. Thus, if you want both example.com and sub.example.com to serve valid certificates, they need to be in two different server blocks, as it seems you have correctly set up above. This is working as expected, so I'm closing this issue. Thanks for your feedback, and please do let us know if you see follow-up bugs, or if this is not the problem you were experiencing.

**Comment by emilstahl** [comment]
@ohemorange It is the same cert, multi domain. Please reopen. It is definitely possible, I'm doing it right now..

**Comment by bmw** [comment]
@ohemorange, I think you misread the issue. They weren't trying to use two certificates in one server block, they were trying to obtain a single certificate for two domains.

With that said, I don't think that's what causes the problem. I was successfully able to obtain a certificate with two domains in one server block, however, I was also able to repo the problem by creating a server block for my desired domain which was also the default server for port 443. The exact server block I used was:
```
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    include snippets/snakeoil.conf;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _ example.com;
    location / { 
        try_files $uri $uri/ =404;
    }   
}
```
What I believe happens is when we create `/etc/letsencrypt/le_tls_sni_01_cert_challenge.conf`, we simply copy the listen directive from the existing server block. The result is we have two server blocks with `listen 443 ssl default_server`, causing the error shown above.

We should add a test case for configurations like this to the compatibility test. After performing a simple grep, it doesn't look like we have one.
