### ISSUE TITLE
Standalone option for running a TLS server when validating HTTP-01 challenges

### ISSUE THREAD

**Issue by benileo** [certbot/certbot#3645]
Boulder will follow insecure redirects when validating a http-01 challenge. Hence, redirects to insecure TLS domains will be followed.

Since the `ServerManager` has all the certificates needed to run a TLS server already, there should be an option to use TLS when validating a HTTP-01 challenge.

**Comment by bmw** [comment]
What is the benefit of this?

**Comment by benileo** [comment]
I proxy in front of the acme client is running an http -> https redirect. Furthermore, I'm not able to use the TLS-SNI challenge becuase I'm doing TLS-SNI based routing using the same proxy.

**Comment by bmw** [comment]
What about using [webroot](https://certbot.eff.org/docs/using.html#webroot)?

**Comment by benileo** [comment]
I never thought of that. That would work if an upstream proxy redirected from http://ben.com/well-known/... to **https**://ben.com/well-known/... ?

**Comment by benileo** [comment]
On second thought, I need to use the standalone plugin. I need to setup the certificates before I start nginx.

**Comment by bmw** [comment]
Ah that makes sense. Another scenario where someone might need this is they're running a web app that isn't simply serving files out of a directory.

**Comment by benileo** [comment]
Awesome! I can pick this one up. I've built it, just needs review and testing :)

**Comment by bmw** [comment]
I believe another workaround for this scenario was found in #3673 so I'm closing this issue.
