### ISSUE TITLE
HTTP2 support in Apache

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3647]
The Apache version of #3646.

**Comment by bmw** [comment]
While I've seen way more [requests for this in Nginx](https://github.com/certbot/certbot/issues/3646) than Apache, I think this is probably still something we should do. As of writing this, the proposed changes to Mozilla's SSL config generator tell you to enable HTTP2.

**Comment by osirisinferi** [comment]
@bmw I'm curious why this issue with priority significant is being closed? 🙂 To me it still sounds like a good idea.

**Comment by bmw** [comment]
It's something we haven't gotten to and/or prioritized in almost 7 years and it seems unlikely to happen to me especially when there doesn't seem to be significant user demand for it. With that said, if you think this issue is especially important, you're welcome to reopen it with your GitHub powers.

**Comment by osirisinferi** [comment]
> especially when there doesn't seem to be significant user demand for it.

That's a good point. I guess most novice users won't care (ignorance is bliss) and advanced users will know how to enable it manually. Let's keep it closed unless someone actively asks for it :slightly_smiling_face:
