### ISSUE TITLE
UIR support in the Nginx plugin

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3649]
Currently only the Apache plugin supports this.

**Comment by bmw** [comment]
#1395

**Comment by bmw** [comment]
Doing this in Nginx might actually be trickier than I thought. Assuming we don't want to include this header in the HTTP response, I believe we'd need to split the Nginx server block into separate HTTP and HTTPS blocks.

**Comment by bmw** [comment]
Another approach I've seen is to use a [map directive](https://websistent.com/add-the-hsts-header-only-for-https-requests-nginx/) but this would also be a bit of work because it can't be added inside the `server` block (see https://nginx.org/en/docs/http/ngx_http_map_module.html).

**Comment by ohemorange** [comment]
I mean, seems like this is a good reason to finally do it correctly and just add another block. Yeah it'll be some work, but it's not impossible.

**Comment by bmw** [comment]
While I think there's still some value in doing this, I don't think it's very high, there's almost no demand for it, and it's probably not something we'll ever get to so I'm closing this.

Erica, if you disagree, feel free to just reopen it. I don't have a strong opinion here.
