### ISSUE TITLE
Handle included ssl_certificate and ssl_certificate_key directives.

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#3654]
```
server {
  include /path/to/ssl_certificate/and/ssl_certificate_key/directives/;
}
```

Currently, we will only modify/ add directives in the file that defines the server block. This leads to errors.

Considerations:
- If we have to edit an included directives, we may want to copy the included directives over, modify those, and comment out the original include directives. For example, if we've included from `snippets/`.

**Comment by bmw** [comment]
@ohemorange, do you know if this is still an issue?

**Comment by ohemorange** [comment]
Pretty sure it still is, but since roughly 0 people ever do this as evidenced by not having seen any issues come in about it, I think we should close this as wontfix.
