### ISSUE TITLE
Add a command to list all certificates currently installed and their domains

### ISSUE THREAD

**Issue by multiwebinc** [certbot/certbot#3656]
I propose we add a `certbot list` command which will list all current certificates, the expiration and any domains.

Sample output:

```
$ certbot list
2 certificates were found on this system:
-------------------------------------------------------------------------------
File: /etc/letsencrypt/renewal/domain1.com.conf
Certificate expiration: 2016-11-15
Primary domain: domain1.com
Alternative domains: domain2.net, domain3.org, domain4.co.uk
-------------------------------------------------------------------------------
File: /etc/letsencrypt/renewal/example1.com.conf
Certificate expiration: 2016-12-25
Primary domain: example1.com
Alternative domains: example2.net, example3.org, example4.co.uk
-------------------------------------------------------------------------------
```

**Comment by bmw** [comment]
Good news! We already have an issue for this and we plan to implement it in our next release. See #3615.

**Comment by multiwebinc** [comment]
@bmw Thanks for the info. For the life of me I couldn't find any bugs that mentioned this searching here and Google. Glad to hear it's in the works.

**Comment by LymeSimon** [comment]
October 2017. Bump?

**Comment by bmw** [comment]
@LymeSimon, per the issue I linked above, the command was implemented. Run `certbot certificates`.

**Comment by LymeSimon** [comment]
Thanks BMW... I assumed it was `certbot list` and didn't check the linked issue. I'll probably get *Must try harder* on my school report now! ;-)

**Comment by comm1x** [comment]
Just `certbot ls`

**Comment by leymannx** [comment]
Just for reference for all people coming here via Google. It's

```
sudo certbot certificates
```
