### ISSUE TITLE
cli.ini domains = <multiple> only takes first

### ISSUE THREAD

**Issue by Fjodor42** [certbot/certbot#3658]
I have tried specifying the list both with and without spaces after the commas, but it seems that certbot-auto only creates a cert for the first entry.

Furthermore, it would seem that even if one specifies an alternative cli.ini to the default one in /etc/letsencrypt/cli.ini, the latter is still consulted, which shows itselv with the domain list being seen by certbot-auto -c <alternative> renew complaining that it can only renew all, not a list...

**Comment by Fjodor42** [comment]
Ah, I see - it creates SANs for all domains in the list on the one certificate - can that be overridden?

**Comment by bmw** [comment]
> Ah, I see - it creates SANs for all domains in the list on the one certificate - can that be overridden?

Overridden to do what? Request a separate certificate for each domain? No, this isn't currently supported. To achieve this, you need to run Certbot once for each domain. Afterwards, you can use `certbot renew` to keep all certificates up to date like normal.

> Furthermore, it would seem that even if one specifies an alternative cli.ini to the default one in /etc/letsencrypt/cli.ini, the latter is still consulted, which shows itselv with the domain list being seen by certbot-auto -c renew complaining that it can only renew all, not a list...

This seems to be the behavior of `ConfigArgParse` which we use to support configuration files. In fact, [we support multiple locations for configuration files](https://certbot.eff.org/docs/using.html#configuration-file) and `ConfigArgParse` will read from all of them on a single run. We could potentially change this behavior, however, it'd be a breaking change for some users.

**Comment by Fjodor42** [comment]
Ad 1: Fair enough. I don't see it as much of a problem, after I discovered that it did SANs for all domains in the list.

Ad 2: Well, I have worked around it by having no cli.ini, but still, the normal behaviour for other programs, when one specifies an alternative config file on the command line is for that one to take preference over the standard locations. That one had me stumped for a bit...

**Comment by bmw** [comment]
Understandable. To be honest, I was a bit surprised by the behavior myself. I created #3682 to track the issue so I'm closing this one. If you think I missed something, feel free to comment and I'll reopen.
