### ISSUE TITLE
domain name with www getting certificate error in browser

### ISSUE THREAD

**Issue by Ranjith1985** [certbot/certbot#3660]
Hi, 

I am getting SSL error while trying to access https://www.fulspoon.com.  I have to click on advanced and  proceed to load the site.  While installing SSL using certbot, I can see only fulspoon.com in the domains list. Web server: apache. 

https://www.sslshopper.com/ssl-checker.html#hostname=www.fulspoon.com

None of the common names in the certificate match the name that was entered (www.fulspoon.com). You may receive an error when accessing this site in a web browser. 

The site works fine without www (https://fulspoon.com)

**Comment by cowlicks** [comment]
Maybe you installed `cert.pem` instead of `fullchain.pem`?

**Comment by bmw** [comment]
Looking at your domain now, this appears to have been resolved. Let me know if you're still having issues and I'll reopen.
