### ISSUE TITLE
letsencrypt: error: unrecognized arguments: --renew-hook

### ISSUE THREAD

**Issue by doovers** [certbot/certbot#3663]
According to the documentation, I can use `--renew-hook` to run a command on successful renewal of a cert. However, I'm getting this error when I try to use it. Is this a bug?

Setup:
Ubuntu 16.04, Nginx, Node+express

**Comment by bmw** [comment]
The version of Certbot in Ubuntu 16.04 is quite old and unfortunately doesn't support this command line option. This was added in Certbot 0.5.0.

While we're currently trying to get Ubuntu to upgrade to a newer version Certbot, we should make this clearer in our documentation in the meantime. I'm assuming you read about this flag in our [user guide](https://certbot.eff.org/docs/using.html)?

**Comment by doovers** [comment]
Yep, that's where I read that. Any workaround for this until the ubuntu version is updated?

**Comment by bmw** [comment]
Probably the simplest option is to use [certbot-auto](https://certbot.eff.org/#ubuntuother-other) where `--renew-hook` is available. This bypasses Ubuntu's packaging and uses an up to date version of Certbot. If you go this route, ignore the rest of this post.

Alternatively, you can make it work with the current version in Ubuntu's repos, but it's not exactly pretty. If you want to do the same thing whenever a specific certificate is renewed you can do:

```
letsencrypt renew | tee | grep -q "/etc/letsencrypt/live/<domain>/fullchain.pem (success)" && <command or script here>
```

You can test that it works by changing `letsencrypt renew` to `letsencrypt renew --dry-run --agree-tos` and ensuring that your `<command or script>` was run. You should also probably check that when running the command above without adding the `--dry-run` flag, `<command or script>` isn't run (assuming your certificate isn't due for renewal).

If you need to do different things for different certificates/domains, however, you'd probably want to modify/remove the `grep` command and pipe `stdout` into a script you write. In that script you can look for lines like the one in the `grep` command above and do different things according to what you input you get. If need help writing such a script, let me know.

**Comment by JetForMe** [comment]
So, what will it take to get the latest `letsencrypt` command installed in Ubuntu 16.04?

**Comment by bmw** [comment]
Using our official PPA as described [here](https://certbot.eff.org/#ubuntuxenial-other).

**Comment by JetForMe** [comment]
Outstanding, thank you. I ran into another issue I can't find an answer for, but I'll create a new issue for it.
