### ISSUE TITLE
unittest2 downloaded as part of certbot-auto

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#3667]
Steps to reproduce:

With certbot-auto 0.8.0 installed, run certbot-auto.

Expected results:

unittest2 is not installed.

Actual results:

```
Collecting unittest2==1.1.0 (from -r /tmp/tmp.t1lthTaPGY/letsencrypt-auto-requirements.txt (line 139))
  Downloading unittest2-1.1.0-py2.py3-none-any.whl (96kB)
    100% |████████████████████████████████| 98kB 8.5MB/s 
```

**Comment by bmw** [comment]
The reason for this is explained in #2334. I'm inclined not to fix this though as it would require us to use different requirements files based on the Python version determined at run time. The extra complexity and potential for bugs doesn't seem worth the 98kB to me.

**Comment by jsha** [comment]
Works for me, thanks for the context!
