### ISSUE TITLE
Unable to register an account with ACME server - AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by macpraveen** [certbot/certbot#3671]
I am getting the following error when I run certbot-auto in Amazon Linux
Downloaded from
`wget https://dl.eff.org/certbot-auto`
Error
```
Requesting root privileges to run certbot...
  /home/ec2-user/.local/share/letsencrypt/bin/letsencrypt certonly --debug --non-interactive --email myemail@yyy.com --agree-tos --standalone --domains xxx.yyy.com --keep-until-expiring
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Traceback (most recent call last):
  File "/home/ec2-user/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/ec2-user/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 776, in main
    return config.func(config, plugins)
  File "/home/ec2-user/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 558, in obtain_cert
    le_client = _init_le_client(config, auth, installer)
  File "/home/ec2-user/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 368, in _init_le_client
    acc, acme = _determine_account(config)
  File "/home/ec2-user/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 359, in _determine_account
    "Unable to register an account with ACME server")
Error: Unable to register an account with ACME server
```

**Comment by bmw** [comment]
Can you provide a complete log of this issue? By default, logfiles are stored in `/var/log/letsencrypt`. Feel free to redact information such as e-mail addresses, domain names, and IP addresses as you wish.

**Comment by macpraveen** [comment]
Actually the error is due to incorrect dns configuration of my email server. The debug log showed this error.

`The ACME server believes xxx@yyy.com is an invalid email address. Please ensure it is a valid email and attempt registration again`

After making dns and mail server config changes, it worked.

Thanks.

**Comment by criskolkman** [comment]
I have the same issue/error with my certbot.
It tells me that the ACME server believes postmaster@sub4.domain.com is an invalid email address.
I do have an A record for sub4.domain.com

**Comment by cpu** [comment]
@criskolkman What is the email that you're trying to use that Boulder rejects? Have you checked that you have an MX record in addition to the A record? 

I would be happy to help you troubleshoot further [if you file a Boulder issue](https://github.com/letsencrypt/boulder/issues) with domain names. Email validation is performed by that codebase and the error is unlikely to be related to Certbot.

**Comment by criskolkman** [comment]
Hello @cpu 
I do not have a MX record for that subdomain because it's not being used for e-mail.
I don't know why but I tried it a couple times and suddenly it worked and created the cert for me, really strange.
