### ISSUE TITLE
Put files in webroot and then invoke a hook

### ISSUE THREAD

**Issue by nivanson** [certbot/certbot#3676]
Hi,

I run the certbot on my working station which will then upload the certificate files to amazon s3 for which my servers have a proxy for /.well-known/*

I was experimenting with the hooks but none of them seem to be in between where the files are generated to webroot and when the testing of accessing those files are.

Not really sure how to handle this kind of scenario I looked into plugins but I believe the s3 plugin I was able to find is for bucket hosted websites, which is not the case for me.

I just want to be able to run any arbitrary shell command when the acme-challenge files are created but not yet tested to be reached.

I did workaround the issue by modifying auth_handler.py but I wonder if maybe here would be a good place for a hook or maybe some other approach in the documentation to handle the scenario where I want to create the files and then do something before validation.

I hope I did not miss something obvious in the documentation. Been reading about command line arguments for hours.

Thank you!

**Comment by bmw** [comment]
I think this use case (and as well as much more complex ones) will be handled when #2782 is closed. There is an open PR for this in #3521. For your use case, I believe it would be two one line shell scripts that look something like:

#### authenticator.sh
```
#!/bin/bash
ssh nivanson@server "echo $CERBOT_VALIDATION > /var/www/html/.well-known/acme-challenge/$CERTBOT_TOKEN"
```
#### cleanup.sh
````
#!/bin/bash
ssh nivanson@server "rm /var/www/html/.well-known/acme-challenge/$CERTBOT_TOKEN"
```

If for some reason this doesn't work for you or you think this solution is inadequate, let me know. We hope to have this feature supported in our next release.

**Comment by SwartzCr** [comment]
I'm going to close this issue as resolved but feel free to re-open it if you still have questions or need help!
