### ISSUE TITLE
webroot can't set permissions over sshfs

### ISSUE THREAD

**Issue by pknowles** [certbot/certbot#3679]
I tried setting various workarounds and umask but nothing worked. I'm more than happy to do this myself, but I'm not really given the chance. Instead I left this running on the server:

```
while [ 1 ] ; do chmod -R o+rX ~/public_html ; sleep 0.01 ; done
```

Maybe the script should pause with the files created to give the user a chance to see what the problem is?

**Comment by bmw** [comment]
I swore we had an issue for this but I can't seem to find it. Yes. I think an option to pause after setting up the challenge is a great idea.

I've honestly never used `sshfs`. Should webroot be setting permissions differently for this to work or do they need to be set on the remote machine?

Also, #3521 might be better for you in the future. We hope to include this plugin in our next release.

**Comment by pknowles** [comment]
I'm not sure if it's a fault with sshfs, or the config of sshd on my shared host, it could have been any number of things I guess.

Thanks for the tip. That `authenticator.sh` method looks quite versatile.

The reason for resorting to not running certbot on the webserver was no root access or gcc for compiling during `pip install`. I suspect many shared hosts will be similar. `certbot-auto` was giving `Sorry, I don't know how to bootstrap Certbot on your operating system!`. `sshfs` made things much easier.
