### ISSUE TITLE
--dry-run and expiration e-mails

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3692]
Running Certbot with `--dry-run` can cause expiration e-mails from staging. How?
1. If you do not yet have a staging account and you've provided an e-mail address on the command line or in a configuration file, Certbot will use that e-mail address when creating a new account, resulting in expiration e-mails from staging.
2. If you already have a staging account, Certbot uses it. If this staging account has an e-mail address registered to it, you will receive expiration e-mails (unless you've unsubscribed).

We should fix this, first by never using an e-mail address with `--dry-run` and second by always creating a new, temporary staging account, which is not saved to disk.

**Comment by schoen** [comment]
How much account-creation traffic are staging and production willing to see? Is it costly for them? There was a discussion from people who were unhappy about how authzs work where someone suggested creating a new account *for production* for every cert operation. While I don't think the best solution to not wanting persistent authzs (a better solution would be to deactivate them), I'm wondering how harmful to Let's Encrypt that behavior would be if it became popular.

**Comment by bmw** [comment]
cc @jsha

**Comment by jsha** [comment]
We'd prefer to see accounts reused. It makes a bunch of things a lot easier, and it does make for less resource usage. One concrete benefit for users: For expiration mails, Boulder will not send mail for a renewed certificate, but it only checks with a single account. If you create a new account each time, you'll get unnecessary expiration emails.

Have many users reported this as an issue?

**Comment by pde** [comment]
We could make an ephemeral account for `--dry-run` execution.

Or we could add something to the protocol to indicate that certain certs are epehemeral.

Or we could revoke them at the end of the dry run?

**Comment by jsha** [comment]
Let's do this:
 - If `--dry-run` is used, and there is no staging account, create one with no email.
 - Otherwise, reuse the existing staging account.

That means that people who specifically created a staging account with an email address do get staging emails, but people who don't know about staging don't get them.

**Comment by vhquang** [comment]
I will work on this during the sprint.

**Comment by TyrannosourceExe** [comment]
vhquang, any updates on this? I am also working on this issue at PyCon2018 Sprints

**Comment by vhquang** [comment]
@TyrannosourceExe I spent half of yesterday on airplane, and did not get much done on this. Feel free to take on this Issue if you like.

**Comment by bmw** [comment]
Fixed in #6015.
