### ISSUE TITLE
Common Name inconsistent with --webroot-map

### ISSUE THREAD

**Issue by pfigel** [certbot/certbot#3698]
When the user invokes `certbot` with `-d`, the Common Name field is set to the first domain passed via that argument. `webroot-map`, which is essentially a combination of `-d` and `-w`, does not seem to follow this behavior and sets the Common Name to a (seemingly) random domain from the map. It would make sense for this to be consistent with `-d`, or at least to document this behaviour somewhere.

Sample `config.ini` to replicate:

```
webroot-map = {"example.com,1.example.com,2.example.com":"/var/www/html", "3.example.com":"/var/www/html", "4.example.com":"/var/www/html"}
```

Expected CN: `example.com`
Actual CN: `4.example.com`

Originally reported [here](https://community.letsencrypt.org/t/set-default-cn-name-for-multiple-certificate/21625/5?u=pfg) (includes a workaround).

**Comment by Ketrel** [comment]
This occurs for me as well

-w and -d maintain my order and issues the cert correctly, but --webroot-map is choosing one of the subdomains intended to be a SAN as the CN.

**Comment by bmw** [comment]
Thanks for reporting this. The problem here is the order of objects in a dict isn't defined. We should fix this though. Here's an [approach](https://stackoverflow.com/questions/6921699/can-i-get-json-to-load-into-an-ordereddict-in-python). that could work, but `OrderedDict` is only available in the standard library in Python 2.7+.

**Comment by mnordhoff** [comment]
Would it be reasonable to use OrderedDict on Python 2.7, continue using dict on older versions, and file it under "WONTFIX, upgrade to Python from this decade if you want it to work right" for older systems?

**Comment by mnordhoff** [comment]
In fact, it looks like certbot-auto already does depend on ordereddict for some reason (unconditionally, even on Python 2.7). Probably a dependency of a dependency. So it's probably best to go with that.

**Comment by bmw** [comment]
One of our dependencies requires `ordereddict` on Python 2.6. To try and provide some extra simplicity, consistency, and stability, we always install the same packages in `certbot-auto` even if they're not required for that Python version. Once we decide the approach we're going to take for conditional dependencies in our own packages in #4379, we can do this with `ordereddict` to solve this issue.

**Comment by kgoedecke** [comment]
are there any updates on this?

**Comment by bmw** [comment]
We conditionally depend on `ordereddict` for Python 2.6, but have deprecated Python 2.6 support and are working on removing it entirely (see #5508). We'd accept a well written PR for this.
