### ISSUE TITLE
Unable to find 'openssl/opensslv.h' 

### ISSUE THREAD

**Issue by mousavian** [certbot/certbot#37]
I faced this error 

```
SWIG/_m2crypto.i:30: Error: Unable to find 'openssl/opensslv.h'
```

and I solved it by installing **libssl-dev** package.
So I think this is another requirement.

```
sudo apt-get install libssl-dev
```

**Comment by yuzaipiaofei** [comment]
For Ubuntu16.04 , i meet same build error about opensslv.h  .

Solution:  apt-get install libssl-dev
