### ISSUE TITLE
le-auto upgrading fails if virtualenv isn't installed

### ISSUE THREAD

**Issue by TheNavigat** [certbot/certbot#3707]
`letsencrypt-auto` fails at https://github.com/certbot/certbot/blob/master/letsencrypt-auto-source/letsencrypt-auto#L577 if there's a newer version of Certbot while virtualenv isn't installed.

**Comment by SwartzCr** [comment]
@TheNavigat think we can close this since now people are probably using a different version, namely certbot auto? Or do you still think it's a problem?

**Comment by SwartzCr** [comment]
I think this is no longer an issue, so I'm closing it
