### ISSUE TITLE
Get Certbot 0.14.1 into Xenial

### ISSUE THREAD

**Issue by b264** [certbot/certbot#3708]
Why is Ubuntu 16 installing version 0.4.1 still when 0.9.3 has been released?

**Comment by pde** [comment]
Because we have to jump through all of these hoops to get 0.9.3 into Xenial:

https://wiki.ubuntu.com/StableReleaseUpdates

We're working on it.

**Comment by pde** [comment]
(In the mean time, you can run `certbot-auto` if you need the latest Certbot on xenial)

**Comment by pde** [comment]
Actually I'm going to reopen this to track progress on that task.

**Comment by b264** [comment]
Is there anything I can do to help?

**Comment by pde** [comment]
This is pretty close now: https://bugs.launchpad.net/ubuntu/+source/python-letsencrypt/+bug/1640978

**Comment by pde** [comment]
@basak is working on reviewing the Ubuntu SRU packages, we hope they'll be done by next week. However kicking this ticket in the mean time...

**Comment by b264** [comment]
Is this not going to happen?

**Comment by bmw** [comment]
Certbot 0.14.1 isn't coming to Xenial.

Certbot 0.23.0 hopefully is though.

Whether or not this happens isn't something that we have control over at the end of the day though. It's up to Canonical.

With that said, you can track the progress of this work at https://bugs.launchpad.net/ubuntu/xenial/+source/python-letsencrypt/+bug/1640978.
