### ISSUE TITLE
Cleanup log for failed Authenticator prepare() functions

### ISSUE THREAD

**Issue by jdkasten** [certbot/certbot#371]
If your Authenticator is misconfigured, it is correctly displayed.  However, the authenticator should not touch the log as it ruins the output shown by "correctly functioning and selected" authenticators.

Apache currently has this problem.

**Comment by kuba** [comment]
What do you mean? Could you give an example, please?

**Comment by jdkasten** [comment]
1. Misconfigure Apache, (run once and then delete accounts directory -- removing the SSLKeyFile)
2. Stop Apache
3. Run client, select Standalone from the menu.

As the menu is generated, each authenticator's prepare function runs and it currently logs error output to the UI... 
This error message remains when the standalone authenticator runs.  This is being fixed in the Apache overhaul.
