### ISSUE TITLE
Error Shell Init

### ISSUE THREAD

**Issue by hrace009** [certbot/certbot#3717]
Hello, When i try to renew cert using `certbot renew --dry-run` i got following error:
<pre><code>shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory</code></pre>
but the renew is success, just curious why i got that error. is there something application that i need to install?
Thank You

**Comment by pde** [comment]
Hi @hrace009, 

What directory were you in when you ran this?

Also, can you provide the copy of `letsencrypt.log` (probably in `/var/log/letsencrypt`) that was generated in that run?

**Comment by hrace009** [comment]
hi sorry,
Just forgot this case, it because i already delete the folder in other console, and the console i run, it still active. it now run fine
