### ISSUE TITLE
Remove sphinxcontrib-programoutput dependency?

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3729]
It's not maintained and the owner chose to delete the project because no one offered to take it over. It was reuploaded to PyPI when everyone's builds broke, but we might want to look into removing this dependency entirely to prevent more problems in the future.

See lunaryorn/sphinxcontrib-programoutput#10 for more information.

**Comment by bmw** [comment]
Supposedly we don't even use this dependency (any more). If this is the case, this is a very easy fix.

**Comment by bmw** [comment]
It looks like we do use this in https://github.com/certbot/certbot/blob/master/acme/docs/man/jws.rst

**Comment by pde** [comment]
OK, if you still want to remove the dependency you can do the same thing I did to create the certbot man page [here](https://github.com/certbot/certbot/blob/master/tools/release.sh#L149) and [here](https://github.com/certbot/certbot/blob/master/docs/man/certbot.rst).

**Comment by bmw** [comment]
Fixed in #3830.
