### ISSUE TITLE
python-cryptography build failure on sid

### ISSUE THREAD

**Issue by pde** [certbot/certbot#3732]
Discovered while investigating #3730. I have a system where `certbot-auto` is failing due to a py-ca build failure.  `tools/venv.sh` works on the same system.

Full output of the build failure [is here](https://gist.github.com/pde/ace9c84f9f25b10ff995514f656e0df3).

**Comment by pde** [comment]
There are [other reports of this problem](https://community.letsencrypt.org/t/cryptography-python-error-running-letsencrypt-auto/20909/1) that were attributed to funny openssl versions in `/usr/local/bin/`, but I haven't been able to find such an obvious cause yet.

**Comment by pde** [comment]
It appears that in my case, the problem is that the lastest version of `libssl-dev` in Debian sid is `1.1.0b-2`, and that seems to cause this build failure. If I forcibly downgrade to `libssl-dev 1.0.2i-1`, the problem goes away.

**Comment by bmw** [comment]
I think what's going on is `cryptography` didn't support OpenSSL 1.1.0 until version 1.5 ([source](https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst#15---2016-08-26)). In `certbot-auto`, we pin version 1.3.4 to continue support older versions of OpenSSL where support was dropped in 1.4.

**Comment by pde** [comment]
Yeah, just realised that was the situation. Did we hit this on another platform recently?

**Comment by bmw** [comment]
Not to my knowledge. This is the first bug report about it I've seen. There are probably few systems who ship packages as new as OpenSSL 1.1.0 and also don't ship Certbot.

**Comment by pde** [comment]
People who ship Certbot probably don't have this problem, because they probably don't pin old `python-cryptography` versions like we do.
