### ISSUE TITLE
Cli help is sometimes wrong about what the default for something is

### ISSUE THREAD

**Issue by pde** [certbot/certbot#3734]
Because `argparse.ArgumentDefaultsHelpFormatter` really doesn't understand the default behaviour of the program, or the semantics of different values.

A few examples:

```
  --disable-hook-validation
                        Ordinarily the commands specified for --pre-hook
                        /--post-hook/--renew-hook will be checked for
                        validity, to see if the programs being run are in the
                        $PATH, so that mistakes can be caught early, even when
                        the hooks aren't being run just yet. The validation is
                        rather simplistic and fails if you use more advanced
                        shell constructs, so you can use this switch to
                        disable it. (default: True)
```
As far as the user is concerned, the real default is `False` (but argparse doesn't understand its own `store_false` semantics.)

```
  --dialog              Run using interactive dialog menus (default: False)
```
This is a flag that shadows the default behaviour of the code (though it's now deprecated).

```
  -d DOMAIN, --domains DOMAIN, --domain DOMAIN
                        Domain names to apply. For multiple domains you can
                        use multiple -d flags or enter a comma separated list
                        of domains as a parameter. (default: [])

  --expand              If an existing cert covers some subset of the
                        requested names, always expand and replace it with the
                        additional names. (default: False)
```
The real default in these cases is "Ask" :)

```
  -c CONFIG_FILE, --config CONFIG_FILE
                        config file path (default: None)
```
The real default here is loaded from `certbot/constants.py`, and is `/etc/letsencrypt/cli.ini`.

**Comment by pde** [comment]
I have a branch that's starting to fix this by creating ridiculous classes that are pythonically `False` or `True`, but which render as the correct string in the argparse output. This is skeezy but seems to work...

**Comment by pde** [comment]
@bitdancer I see you wontfixed [the argparse bug](https://bugs.python.org/issue27153) for the case of `store_false` flags. I think you might have made the wrong decision there, because you're reasoning about the default value of an internal Python variable, whereas a user reading commandline help has no idea about Python variables, and is thinking about the default for whether a *flag* is in effect or not.

But a general question: is there a sane way to stop `argparse` from printing an incorrect default for a few flags, but keep it printing defaults for all the other ones? That would clearly be useful for projects like this one that have dozens or hundreds of flags, most but not all of which are correctly documented by `argparse`.

**Comment by bitdancer** [comment]
On Fri, 04 Nov 2016 13:12:17 -0700, Peter Eckersley <notifications@github.com> wrote:
> @bitdancer I see you wontfixed [the argparse
> bug](https://bugs.python.org/issue27153) for the case of `store_false`
> flags. I think you might have made the wrong decision there, because
> you're reasoning about the default value of an internal Python
> variable, whereas a user reading commandline help has no idea about
> Python variables, and is thinking about the default for whether a
> *flag* is in effect or not.

Yes, that was exactly my point.  What does

    --no-foo  Suppress foo (default: False)

mean?  It could mean that foo is off by default.  You just can't tell,
given only the phrase 'suppress foo' as the description of the flag.  So
it wouldn't help to flip the value of the default, the sentence is
ambiguous either way.  What you need to do is write the sentence so
that it is not ambiguous, if you can.  But I'm not sure you can,
because of the inherent nonsensicality of mentioning the default
value of a variable that is, as you say, hidden from the user.

> But a general question: is there a sane way to stop `argparse` from
> printing an incorrect default for a few flags, but keep it printing
> defaults for all the other ones? That would clearly be useful for
> projects like this one that have dozens or hundreds of flags, most but
> not all of which are correctly documented by `argparse`.

Not currently.  Enhancement patches welcome :)

--David

**Comment by pde** [comment]
@bitdancer I've written a patch for Python2.7's `argparse.py` to do that: https://gist.github.com/pde/daec08cadc21bca0d62852020887ee13

Let me know what you think of that approach, and what the right place for submitting it would be.  We may vendor some version of this patch for ourselves in the mean time.

**Comment by bitdancer** [comment]
It looks like a reasonable proposal.  However, as a new feature it could only go into 3.7.  You should submit the patch to bugs.python.org.  It will need docs and tests before being accepted (you don't necessarily need to be the one to supply them; if you post it to bugs someone else may pick it up and finish it).

**Comment by pde** [comment]
@bitdancer thanks I've started a ticket over there: https://bugs.python.org/issue28742

I've updated the patch so it's now against the latest Python development tree, and includes unit test cases.
