### ISSUE TITLE
NoInstallationError('Problem in Augeas installation',)

### ISSUE THREAD

**Issue by YuGiOhJCJ** [certbot/certbot#3735]
Hello,

I built from source code certbot-0.9.2 on Slackware64.
I built from source code some dependencies to be able to run certbot:
- python-acme-0.9.2
- python-certbot-0.9.2
- python-cffi-1.8.3
- python-configargparse-0.11.0
- python-configobj-5.0.6
- python-cryptography-1.5.2
- python-enum34-1.1.6
- python-funcsigs-1.0.2
- python-idna-2.1
- python-ipaddress-1.0.17
- python-mock-2.0.0
- python-ndg_httpsclient-0.4.2
- python-parsedatetime-2.1
- python-pbr-1.10.0
- python-pyasn1-0.1.9
- python-pycparser-2.16
- python-pyopenssl-0.15.1
- python-pyrfc3339-1.0
- python-python2-pythondialog-3.4.0
- python-pytz-2016.7
- python-requests-2.11.1
- python-six-1.9.0
- python-zope-component-4.3.0
- python-zope-event-4.2.0
- python-zope-interface-4.3.2

Then I discovered that I need to build the certbot apache plugin.
So, I did it from the certbot-0.9.2 source code.

After that, I built from source code a missing dependency to be able to run certbot with the certbot apache plugin:
- python-augeas-0.5.0

And here is the result:
```
$ certbot --config-dir conf --logs-dir logs --work-dir work --apache
The apache plugin is not working; there may be problems with your existing configuration.
The error was: NoInstallationError('Problem in Augeas installation',)
```

Did I miss something please?

Thank you.
Best regards.

**Comment by pde** [comment]
What happens if you run python interactively and type `import augeas`?

**Comment by pde** [comment]
Also, if you want full control over how you run certbot (which I understand is not quite the same as building from source, Slackware style) you might find these instructions to be less work:

https://certbot.eff.org/docs/contributing.html#running-a-local-copy-of-the-client

**Comment by YuGiOhJCJ** [comment]
It seems that augeas is not installed correctly:
```
$ python
Python 2.7.11 (default, Mar  3 2016, 13:35:30) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import augeas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/augeas.py", line 78, in <module>
    class Augeas(object):
  File "/usr/lib64/python2.7/site-packages/augeas.py", line 82, in Augeas
    _libaugeas = _dlopen("augeas")
  File "/usr/lib64/python2.7/site-packages/augeas.py", line 75, in _dlopen
    raise ImportError("Unable to import lib%s!" % args[0])
ImportError: Unable to import libaugeas!
```

That's how I built the augeas package:
```
tar xvf python-augeas-0.5.0
cd python-augeas-0.5.0
python setup.py install --root /tmp/python-python-augeas-0.5.0
```
I guess that I did it wrong.

The result is:
```
usr/
usr/lib64/
usr/lib64/python2.7/
usr/lib64/python2.7/site-packages/
usr/lib64/python2.7/site-packages/augeas.py
usr/lib64/python2.7/site-packages/augeas.pyc
usr/lib64/python2.7/site-packages/python_augeas-0.5.0-py2.7.egg-info
```

**Comment by willysr** [comment]
@YuGiOhJCJ : Did you install them manually from source code or do you use SlackBuild script ?
We have this script in SBo project: https://slackbuilds.org/repository/14.2/system/letsencrypt/

another option if you don't want to tackle with all the deps, you can try dehydrated: https://slackbuilds.org/repository/14.2/system/dehydrated/

**Comment by willysr** [comment]
and it seems you miss [augeas](https://slackbuilds.org/repository/14.2/system/augeas/) (it's a dependency for [python-augeas](https://slackbuilds.org/repository/14.2/python/python-augeas/))

**Comment by YuGiOhJCJ** [comment]
I installed them automatically from source code using my own scripts because I don't like SlackBuilds.
Indeed, the problem with SlackBuilds is that they require to be "root" to be able to run them whereas a lot of things can be done by a simple user.
But I like watching the content of SlackBuilds in order to make my own scripts because I can see how the program is built.
Sometimes I watch also how packages are built from other operating systems (like ArchLinux).

Anyway thank you I was not aware that augeas was a dependency of python-augeas.
So, I installed augeas and now the previous error has gone:
```
$ certbot --config-dir conf --logs-dir logs --work-dir work --apache
The apache plugin is not working; there may be problems with your existing configuration.
The error was: NoInstallationError('Cannot find Apache control command apache2ctl',)
```

The problem is just that apache2ctl is named apachectl on Slackware64.
So it should be easy to resolve.

Anyway, why apache2ctl is called?
I only want my certificates, I don't want to start/restart my webserver for that.
That's a bit weird that apache2ctl is called.

The same things happen when I use the certonly command:
```
$ certbot --config-dir conf --logs-dir logs --work-dir work --apache certonly
The apache plugin is not working; there may be problems with your existing configuration.
The error was: NoInstallationError('Cannot find Apache control command apache2ctl',)
```

Sorry, I am noob, it is the first time I use certbot and Let's Encrypt.

**Comment by willysr** [comment]
AFAIK the apache plugin do not work in Slackware. It works for Ubuntu and probably some other distribution though

**Comment by YuGiOhJCJ** [comment]
Well, maybe I don't need this apache plugin.
What I need is only a way to generate certificates through command line in non-interactive mode.
I don't want that certbot runs apache because I don't think there is a good reason for that.

I did:
```
$ certbot --config-dir conf --logs-dir logs --work-dir work certonly
```
Then I chose: Place files in webroot directory > "gsw.1s.fr" > Enter a new webroot > "/tmp/toto/root"

The result is a failure:
```
   │ Saving debug log to /tmp/toto/logs/letsencrypt.log
   │ Failed to find apache2ctl in PATH:
   │ /bin:/sbin:/usr/bin:/usr/sbin:/usr/games:[...]
   │ Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
   │ Obtaining a new certificate
   │ Performing the following challenges:
   │ http-01 challenge for gsw.1s.fr                            
   │ Waiting for verification...                                
   │ Cleaning up challenges
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: gsw.1s.fr
   Type:   unauthorized
   Detail: Invalid response from
   http://gsw.1s.fr/.well-known/acme-challenge/-pgvEFhzP_fXsNqd5tJQp21bMT1ByjW3oj7g2MgSRwE:
   "<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
   <html>
           <head>
                   <title>
                           Gensiteweb - Générateur de sites w"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.
```

I was not on the webserver during this test, so I guess this is the reason of the error above, but is it the correct way to use certbot please?
Anyway I should close the ticket now because the problem of my first post is solved.

**Comment by willysr** [comment]
It's already mentioned on the [README.Slackware](https://slackbuilds.org/slackbuilds/14.2/system/letsencrypt/README.Slackware) on SBo.

This is what i used and so far it's working well:
make a new entry in /etc/cron.monthly/letsencrypt (you can pick other names)
```
/etc/rc.d/rc.httpd stop
sleep 2
certbot certonly --webroot-path=<PATH> --standalone-supported-challenges tls-sni-01 -d <DOMAIN> --email <EMAIL> --renew-by-default --agree-tos --text --standalone --rsa-key-size 4096
/etc/rc.d/rc.httpd start
```

**Comment by YuGiOhJCJ** [comment]
OK done.
Here is the result on my server through the port 443 (after shutting down my apache web server):
```
$ certbot certonly --webroot-path=/home/www --standalone-supported-challenges tls-sni-01 -d gsw.1s.fr --email yugiohNOjcjSPAM@1s.fr --renew-by-default --agree-tos --text --standalone --config-dir=certbot/config --logs-dir=certbot/logs --work-dir=certbot/work
WARNING: The standalone specific supported challenges flag is deprecated.
Please use the --preferred-challenges flag instead.
Saving debug log to /home/spierre/certbot/logs/letsencrypt.log
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Obtaining a new certificate
Performing the following challenges:
tls-sni-01 challenge for gsw.1s.fr

-------------------------------------------------------------------------------
Port 443 is already in use by another process. This will prevent us from binding
to that port. Please stop the process that is populating the port in question
and try again.
-------------------------------------------------------------------------------
Press Enter to Continue
Cleaning up challenges
At least one of the required ports is already taken.
```
And through the port 80:
```
$ certbot certonly --webroot-path=/home/www --standalone-supported-challenges http-01 -d gsw.1s.fr --email yugiohNOjcjSPAM@1s.fr --renew-by-default --agree-tos --text --standalone --config-dir=certbot/config --logs-dir=certbot/logs --work-dir=certbot/work
WARNING: The standalone specific supported challenges flag is deprecated.
Please use the --preferred-challenges flag instead.
Saving debug log to /home/yugiohjcj/certbot/logs/letsencrypt.log
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for gsw.1s.fr

-------------------------------------------------------------------------------
Port 80 is already in use by another process. This will prevent us from binding
to that port. Please stop the process that is populating the port in question
and try again.
-------------------------------------------------------------------------------
Press Enter to Continue
Cleaning up challenges
At least one of the required ports is already taken.
```

I guess that the problem is that I am using venez [1] services to get my free domain "gsw.1s.fr".

What do you think about my error and my guess?

[1] https://www.venez.fr/

**Comment by willysr** [comment]
thanks for noticing the deprecated --standalone-supported-challenges. I will need to update my scripts, but the original still works

```
WARNING: The standalone specific supported challenges flag is deprecated.
Please use the --preferred-challenges flag instead.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for <DOMAIN>
/usr/lib64/python2.7/site-packages/OpenSSL/rand.py:58: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  result_code = _lib.RAND_bytes(result_buffer, num_bytes)
Waiting for verification...
Cleaning up challenges
Generating key (4096 bits): /etc/letsencrypt/keys/0006_key-certbot.pem
Creating CSR: /etc/letsencrypt/csr/0006_csr-certbot.pem

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/<DOMAIN>fullchain.pem. Your cert
   will expire on 2017-02-08. To obtain a new or tweaked version of
   this certificate in the future, simply run certbot again. To
   non-interactively renew *all* of your certificates, run "certbot
   renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le
```

**Comment by drguildo** [comment]
I had the same (or at least very similair) error on Ubuntu 16.04.3 LTS. Seems Certbot wasn't smart enough to do `apt-get install python-augeas`. Doing it manually fixed the problem for me.

**Comment by pde** [comment]
@drguildo can you please file another bug if you want that addressed? Be sure to include the method that you used to install Certbot...

**Comment by gmegidish** [comment]
Just for completeness and for search sake. On Amazon Linux 2 I used `yum install -y python-augeas` and that solved the problem for me.

**Comment by while-true-work** [comment]
CentOS/RHEL:
Login as root:

# yum install augeas-libs

Done.
