### ISSUE TITLE
Possible Nginx if-statement weirdness

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#3745]
If an `ssl on` directive can be within an `if` directive, we should consider what to do if we encounter one when determining if that directive applies to all `listen` directives in the block.

**Comment by bmw** [comment]
@ohemorange, do you know if this is still an issue?

**Comment by ohemorange** [comment]
Pretty sure it still is, but since roughly 0 people ever do this as evidenced by not having seen any issues come in about it, I think we should close this as wontfix.
