### ISSUE TITLE
Generalize return types for plugin interfaces

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3748]
For example, in `interfaces.py` we say that `IInstaller.get_all_names()` must return a `list`, yet both of our plugins return a `set`. We should both make sure our documentation doesn't specify unnecessary requirements as well as try and simplify our code if necessary so more general types such as any [iterable](https://docs.python.org/2/glossary.html#term-iterable) works properly.

**Comment by dashaxiong** [comment]
@bmw I have submitted a pull request for changing the return types specified in the interface documentation. The code where the list return values from IInstaller and IAuthenticator are consumed, are already suitable to handle any iterable. Is there more intended with this issue than changing up the docstrings in the interfaces?
