### ISSUE TITLE
Certbot Manual Private Key World Readable

### ISSUE THREAD

**Issue by rossja** [certbot/certbot#3754]
I've just created a new certificate for my domain using certbot in manual mode. 
The resulting private key file is world-readable.

Below steps show how to reproduce:

~~~ bash
$ certbot certonly --manual
<follow instructions>
~~~

After certificate has been generated successfully:

~~~ bash
ls -l /etc/letsencrypt/live/<domain>/privkey.pem 
lrwxrwxrwx 1 root root 46 Nov  5 09:56 /etc/letsencrypt/live/<domain>/privkey.pem -> ../../archive/<domain>/privkey1.pem

ls -l /etc/letsencrypt/archive/<domain>/privkey1.pem 
-rw-r--r-- 1 root root 1704 Nov  5 09:56 /etc/letsencrypt/archive/<domain>/privkey1.pem
~~~

This is somewhat mitigated by the fact that both the `live` and `archive` directories are not world-readable or executable by default. However, I believe there is benefit to having the file itself not be world-readable as a defense-in-depth measure. 

* Version used: certbot 0.9.3
* Command line: `certbot certonly --manual`

**Comment by pde** [comment]
Duplicates: #1473 #3108
