### ISSUE TITLE
Certbot opens curses sessions for informational notices, breaking automation

### ISSUE THREAD

**Issue by starchy** [certbot/certbot#3764]
This was spotted on older clients still using the letsencrypt-auto command line. Our cron jobs:
<code>/opt/letsencrypt/letsencrypt-auto certonly --config /etc/letsencrypt/cli.ini --agree-tos --renew-by-default --expand</code>
failed with:
<code>An unexpected error occurred:
Bug in pythondialog: expected an empty output from u'infobox', but got: u'Error opening terminal: unknown.\n'Please see the logfile 'certbot.log' for more details.</code>
Running interactively shows the client opening a curses dialog (where previous versions did not), although there were only an information notices displayed:
<code><pre>
      | Saving debug log to /var/log/letsencrypt/letsencrypt.log             │        
      │ Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org      │        
      │ Renewing an existing certificate                                     │        
      │ Performing the following challenges:                                 │        
      │ http-01 challenge for irc.eff.org                                    │        
      │ Using the webroot path /var/www/letsencrypt for all unmatched        │        
      │ domains.                                                             │        
      │ Waiting for verification...                                          │        
      │ Cleaning up challenges                                               │        
      │ Generating key (2048 bits):                                          │        
      │ /etc/letsencrypt/keys/0004_key-certbot.pem                           │        
      │ Creating CSR: /etc/letsencrypt/csr/0004_csr-certbot.pem  |
</pre></code>
Adding the --non-interactive switch resolves the issue, but this is a breaking change for many existing pre-certbot cronjobs.

**Comment by pde** [comment]
Ahhh, I think this is already fixed (by drastic means, removing the `dialog`-based user interface) in git master and the forthcoming 0.10.0 release.

**Comment by pde** [comment]
Could you confirm that by trying to run the current git master tree (https://certbot.eff.org/docs/contributing.html#running-a-local-copy-of-the-client) with the same flags and seeing if it works?

**Comment by pde** [comment]
BTW, you should definitely deprecate that commandline; `--renew-by-default` aka `--force-renewal` should no longer be necessary for a good renewal script.

**Comment by pde** [comment]
Closing this, but please reopen if you can reproduce with the current git master tree.
