### ISSUE TITLE
renew doesn't print a timestamp for logging purposes

### ISSUE THREAD

**Issue by sbwoodside** [certbot/certbot#3778]
My crontab contains:

    30 2 * * 1 /opt/letsencrypt/letsencrypt-auto renew >> /var/log/le-renew.log

As recommended by this article: https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-16-04

This seems like a better option than simply suppressing output using --quiet, but it does have one problem, there is no timestamp in the log files. Is it reasonable to request that a timestamp be included in the output?

**Comment by SwartzCr** [comment]
@bmw would know about the specifics of this - I think there were some situations where we were duplicating timestamps

**Comment by bmw** [comment]
Logfiles are written to `/var/log/letsencrypt` and include timestamps. @SwartzCr, perhaps we should contact digital ocean and explain this. To be clear, they should not be redirecting output and should instead be using `--quiet` and the log files in `/var/log/letsencrypt`.

**Comment by SwartzCr** [comment]
@erikaheidi would you be willing to edit the article?

**Comment by SwartzCr** [comment]
The digital ocean article in question has been updated, closing
