### ISSUE TITLE
dns-01 auth with hooks instead of manual

### ISSUE THREAD

**Issue by grinapo** [certbot/certbot#3781]
I am glad to see that dns-01 auth is working in manual mode, which is nice to test it. 
Now, I have tested it, fine, so I'd like to use it non-interactively. 

In theory I would prefer a general framework: 
* selecting a plugin to auth (dns)
* selecting a plugin to install (none)
* setting a hook for prepare (/tmp/dns-prepare.sh)
* setting a hook to cleanup (/tmp/dns-cleanup.sh)
(all these in the .conf) and running _certonly_ or _renew_ from then on, and I would implement 
* whatever my DNS implementation needs to create an RR, checking the secondary being in synch, and
* I would implement removing it afterwards, 
outside certbot code.

As far as I see in practice this doesn't work now (or if it does I would appreciate knowing how), so something should be done. What I don't see is what would be the preferred solution?
* could you easily implement the above (my preference), or
* shall I create a new plugin doing that (my code is expected to be ugly as I'm not a python guru), or
* it won't work that way and I should hack the main code (which I probably would skip).

dns-01 validation is the only way to validate internal hosts with no or restricted public net access, or behind strict firewalls (no 80/443).

**Comment by pde** [comment]
This has already landed in the tree (#3521) but will probably change before shipping (#3767).
