### ISSUE TITLE
Rewrite our Dockerfile

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3782]
Our current Dockerfile was largely written roughly 6 months before Let's Encrypt entered beta and it was a convenient way to test the project on different systems. It's in need of an update. I propose we update our Dockerfile to do the following:

* Continue installing from our repo rather than OS packages
* Remove unneeded OS dependencies after installing Certbot (such as `gcc`?)
* Clean `pip` cache after installing `certbot` (or don't use it all)
* Don't install the Apache or Nginx plugins

The resulting image should be roughly the size if we simply installed the `certbot` OS package. If this isn't possible for some reason, we may have to choose a different approach.

**Comment by bmw** [comment]
I just realized I should have added more to this issue. I think we should still probably experiment with creating different Docker images for people. Something like what was proposed [here](https://community.letsencrypt.org/t/what-would-you-want-from-a-certbot-docker-image/21471/2) could be really cool. With that said, I still think we need a simple, stripped down, Certbot docker image. Some people want this and we can ideally build off of it for other images.

**Comment by bmw** [comment]
To continue my conversation with myself, I provided a lot more context in #2717 about why I prefer this approach.

**Comment by thomaszbz** [comment]
To join your conversation: Could you please add more documentation in respect to the docker image? E.g. how to run certbot in Docker for test purposes when domain verification is not possible (dev system behind firewalls etc.). E.g. how to run boulder in the docker instance, with the dockered certbot connecting to it. Thanks!

**Comment by ctrlok** [comment]
HI, to make docker image more lightweight I can rewrite it to [Rockerfile](https://github.com/grammarly/rocker), but docker 1.13 [will support](https://github.com/docker/docker/pull/22641) `--squash` option, so it may fix this problem and you can just remove all unnecessary data just in docker file.

**Comment by bmw** [comment]
@joohoi, what do you think about what I proposed here?

**Comment by joohoi** [comment]
It's a good idea. Having a build for every version, and also (daily or at-merge) builds of master would be very nice.

In my opinion the optimal combination would be to have webroot and standalone containers (most likely a single one for both) with minimal everything, but providing a bit bulkier image for manual plugin for added automation options (having curl, etc). Alpine is a good base the build all of them on.

So we could for example have a following fleet:
certbot-rolling - daily / at-merge builds from master
certbot - the as-compact-as-possible container, built on every release for standalone / webroot / simple manual plugin usage
certbot-large - same as the "certbot" container above, could even use it as a base image. comes with added tools for manual plugin automation

**Comment by bmw** [comment]
I think that makes a lot of sense and the rolling image is a great idea.

What do you think we should do to the quay.io image? Suddenly changing `latest` to Alpine may break people's integrations, however, I think this is the default image we want long term. We can either:

1. Leave the quay.io image untouched for now and use the new Docker image as `certbot-alpine`. We can make the Alpine version the default if we want on Docker Hub.
2. Just make the breaking change. We can try to notify people to mitigate the problem.

I'm leaning towards 2 personally.

**Comment by joohoi** [comment]
I think we should go with 2, but after few months of printing deprecation warnings or something alike, noting the users that there's going to be a considerable change to the container image.
