### ISSUE TITLE
certbot fails parsing apache configuration (macros)

### ISSUE THREAD

**Issue by tobiasherp** [certbot/certbot#3783]
certbot 0.9.3 on CentOS Linux release 7.0.1406 (Core)

My Apache configuration contains macros which use variables; parsing lines like this:

  IncludeOptional conf/snippets/$(NAME)/00-hd-*.inc

(`$(NAME)` being a positional argument which is replaced when the macro is used) a `RuntimeError` occurs:

  `RuntimeError: ('Error during match procedure!', u"/files/etc/httpd/conf/snippets/$(NAME)/* [label()=~regexp('00\\-hd\\-.*\\.inc')]//*[self::directive=~regexp('([Ll][Oo][Aa][Dd][Mm][Oo][Dd][Uu][Ll][Ee])|([Ii][Nn][Cc][Ll][Uu][Dd][Ee])|([Ii][Nn][Cc][Ll][Uu][Dd][Ee][Oo][Pp][Tt][Ii][Oo][Nn][Aa][Ll])')]")`

Ok, certbot doesn't understand Apache macros yet, but when executing `certbot certonly -d my.domain` you don't expect a show-stopping parsing error.

Suggestions:

- Catch the RuntimeError and tell about the line;
- if possible, proceed (`certbot` tolerates the *usage* of macros as well, despite not understanding them);
- otherwise re-raise the exception

When I comment out my `IncludeOptional` lines mentioned above, certbot resumes parsing

**Comment by tobiasherp** [comment]
I updated augeas (yum update augeas, in my case; CentOS 7) from version 1.1.0-12 to 1.4.0-2; this didn't help.

**Comment by SwartzCr** [comment]
hmm this seems along the lines of the things @joohoi was hoping to not copy over when creating new apache conf files. I can't seem to find the relevant issue, so maybe he can link to it.

**Comment by daincredibleholg** [comment]
I just came across the same issue. Looks like this is more due to the usage `IncludeOptional` than the variable. It fails for me with having this line in my config:

```
IncludeOptional /etc/apache2/vhost-opt-configs.d/test.local/*.conf
```

**Comment by SwartzCr** [comment]
Ah - okay, this is a simple missing file issue, closing
