### ISSUE TITLE
Delete account when deactivating it

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3787]
This is probably safe to just do as deactivating an account registers it useless. Alternatively, we could provide it as an option to the user.

**Comment by ynasser** [comment]
@bmw I think this has already been implemented. In `certbot/main.py` in the the `unregister` function, there's a line for "deleting on boulder" and one for "deleting local account files": https://github.com/certbot/certbot/blob/master/certbot/main.py#L421. What else is there to delete?

**Comment by bmw** [comment]
You're right!

It looks like I created this issue after writing [this comment](https://github.com/certbot/certbot/pull/3571#discussion_r87881367) but this functionality ended up being added to #3571 when it was merged months later.

Nice catch!

**Comment by ynasser** [comment]
OK, we should look for a good replacement issue for the livestream.

**Comment by bmw** [comment]
Sure! Happy to comment on any issues you find about whether or not I think they'd be good issues for the livestream. Also happy to look for something you have an idea for the kind of thing you'd like to work on.

**Comment by ynasser** [comment]
Yeah, commenting on any good issues you come across would be helpful, esp since you go through the issue queue more often than me. Regarding what the issue would be like, something similar to this one in terms of difficulty because of the 90 minute time constraint (and there are other issues).

**Comment by bmw** [comment]
I'll keep this in mind while I'm playing the role of @SwartzCr and responding to active issues.

Let me know if you see an older issue that you'd like my opinion on or if you have a specific topic you'd like to work on.
