### ISSUE TITLE
Certbot and --apache modules looks for vhost conf files in sites-available causing missconfigurations in edge cases

### ISSUE THREAD

**Issue by ophiocus** [certbot/certbot#3791]
This will cause the configuration to be written to the wrong conf file 

>>>if more than one vhost file has the same servername specified<<<

repro steps

- in apache2 create 2 vhosts*80 files in sites-available, give theme the same server name, enable the one that is alpahabetiacally last ( Avhost.conf and Bvhost.conf, enable Bvhost)

- run certbot; (sudo letsencrypt --apache -d commonname.com -d www.commonname.com ) 

configurations will be written to the first conf, which is dissabled and the resulting -le-ssl conf file in sites enabled is name based off the dissabled configuration (Avhost.conf has redirect rules, and Avhost-le-ssl.conf is now created as a new vhost and enabled as a new site )

Potential fix-

only look for vhosts conf files present in sites-enabled when using the apache plugin unless otherwise specified

NOTE: i only noticed this because the force secure connection was not working, this led me to find the configuration for the redirect in Avhost which is a dissabled vhost

**Comment by pde** [comment]
@joohoi, thoughts?

**Comment by joohoi** [comment]
Thanks for the report @ophiocus  . It boils down to the question: do we want to search and suggest vhosts in currently active configuration or all possible in the system. 

I think I might agree with @ophiocus . People are prepared to see only the vhosts they have active listed by Certbot, and expect the configuration to be the one that's actually active. I think it's pretty rare to hit this bug however.

The fix itself is merely a OS constants fix.

**Comment by joohoi** [comment]
We discussed this issue, and agreed to modify the process so that we'll search vhosts from sites-enabled explicitly, with a possibility to override the default directory using a cli parameter. This will require some refactoring of the code, but we'll track the process with this issue#

**Comment by jenlampton** [comment]
I'm not using a version of apache that has the `sites-available` directory, and all my virtual hosts are defined in the bottom of my `httpd.conf` file.  I often add a duplicate virtual host entry at the very bottom to catch redirect any errant traffic that didn't match any of the defined virtual hosts, and 301 redirect it back to my primary site, like so:

```
# Redirect all other subdomains to www.
#<VirtualHost *:8080>
#    ServerName www.example.com
#    ServerAlias *.example.com
#    Redirect 301 / http://www.example.com/
#</VirtualHost>\
```

I've been having trouble with the Certbot being able to identify my primary domain, and after seeing this comment: 

> if more than one vhost file has the same servername specified

I wonder if that could be the issue?

**Comment by joohoi** [comment]
@jenlampton Yes, I very much think so. You could try splitting each virtualhost configuration to a separate configuration file. Iirc CentOS reads /etc/httpd/conf.d/*.conf so you could try creating /etc/httpd/conf.d/virtualhost_one.conf, /etc/httpd/conf.d/virtualhost_two.conf and so on.

**Comment by jenlampton** [comment]
Thanks for your reply @joohoi. For my use case, I need my virtual hosts to be loaded in a specific order (see comment above about the redirect coming last) and I'm not sure if/how that can be done if they were all in separate files. 

I have opened a separate issue recommending a scan of the main apache configuration file in addition to the various other files: https://github.com/certbot/certbot/issues/4001

I'm hoping this will be a simple change that should spare people the time reconfiguring their servers just so they can use Certbot :)  Keep up the good work!

**Comment by joohoi** [comment]
We are working on supporting multiple virtualhosts in one file: #1042

Apache configuration tip: you can split your configuration to different vhosts already, if you just define "catch-all" ServerAlias for your default vhost using a wildcard:
eg:
`ServerAlias *`
