### ISSUE TITLE
does not work in nginx 1.10.2 CentOs6.8

### ISSUE THREAD

**Issue by shaqueoneal** [certbot/certbot#3796]
when I use ./certbot-auto certonly --standalone -d xxx.com -d www.xxx.com  in CentOs 6.8 with nginx 1.10.2, it gives below errors, I really don't know what's wrong! 

Failed authorization procedure. xxx.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for TLS-SNI-01 challenge. Requested 19652f9e8502f323c7f3bfb9c5d90b44.eb4fb28a79262d98c28bdaef62f59fcd.acme.invalid from 141.0.173.173:443. Received certificate containing '', www.xxx.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for TLS-SNI-01 challenge. Requested 893592b0701018d7728a4c1deac26bc1.4315f46cb6f85514be9a3d919ea14e9e.acme.invalid from 141.0.173.173:443. Received certificate containing ''

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: xxx.com
   Type:   unauthorized
   Detail: Incorrect validation certificate for TLS-SNI-01 challenge.
   Requested
   19652f9e8502f323c7f3bfb9c5d90b44.eb4fb28a79262d98c28bdaef62f59fcd.acme.invalid
   from 141.0.173.173:443. Received certificate containing ''

   Domain: www.xxx.com
   Type:   unauthorized
   Detail: Incorrect validation certificate for TLS-SNI-01 challenge.
   Requested
   893592b0701018d7728a4c1deac26bc1.4315f46cb6f85514be9a3d919ea14e9e.acme.invalid
   from 141.0.173.173:443. Received certificate containing ''

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.

**Comment by bmw** [comment]
I'm sorry this issue slipped through the cracks and no one ever responded.

If you or anyone else is having similar problems here, you should make a post at https://community.letsencrypt.org where there is a large community of people familiar with the project that should be able to help you resolve the issue.
