### ISSUE TITLE
nginxparser fails for given test case

### ISSUE THREAD

**Issue by joystein** [certbot/certbot#3798]
Versoin of certbot (installed as root with `pip install --user certbot-nginx`):

```bash
# pip list --user | grep certbot
certbot (0.9.3)
certbot-nginx (0.9.3)
```

Os: debian wheezy (7.11)

Command (run through fabric from workstation to remote server):
```
~/.local/bin/certbot certonly --nginx --email username@domain.no -d sub.domain.no # (real domain redacted)
```

Actual output:
```
Cannot find a VirtualHost matching domain player.fabelapp.no.
```

Expected: that certbot would have found the server block in the nginx config files.

I should note that i have a possibly unusual structure for nginx config files:
```
|-> nginx 
|        |-> sites-{available,enabled}
|        |        |-> domain1.no
|        |        |       |-> www.conf
|        |        |       |-> api.conf
|        |        |-> domain2.no
|        |        |       |-> www.conf
|        |        |       |-> api.conf
|        |        |-> domain3.no
|        |        |       |-> www.conf
|        |        |       |-> api.conf
```

This is matched with the following include statements in the main nginx config:
```
    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*.conf;
    include /etc/nginx/sites-enabled/*/*.conf;
```

I have however tried moving the config files i have been testing to directly under `sites-{available,enabled}` and i still get the same error.

In the end, i downgraded to `pip install ---user 'certbot-nginx < 0.9.0'` and finally the command ran, and i could go on with the installation step.

**Comment by bmw** [comment]
@ohemorange, any ideas here?

**Comment by ohemorange** [comment]
Hi @joystein, would you feel comfortable posting an example config file? Feel free to redact any information you'd like.

**Comment by joystein** [comment]
It should be pretty standard stuff, i believe. The initial file looked something like (only domain name altered):

```
/etc/nginx/sites-{available,enabled}/domain1.no/api.conf:

server {
    listen 80;
    server_name api.domain1.no;
    access_log /var/log/nginx/api_domain1_no.access.log;
    error_log /var/log/nginx/api_domain1_no.error.log;
    gzip on;
    gzip_types application/json;

    location / {
        uwsgi_pass uwsgi-router-local;
        include uwsgi_params;
        uwsgi_param HTTP_X_FORWARDED_PROTO     $scheme;
    }
}
```

After running `certbot-nginx < 0.9.0` it looks something like this:

```
server {
    listen 80;
    server_name api.domain1.no;
    access_log /var/log/nginx/api_domain1_no.access.log;
    error_log /var/log/nginx/api_domain1_no.error.log;
    gzip on;
    gzip_types application/json;

    location / {
        uwsgi_pass uwsgi-router-local;
        include uwsgi_params;
        uwsgi_param HTTP_X_FORWARDED_PROTO     $scheme;
    }
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/api.fabelapp.no/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.fabelapp.no/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_trusted_certificate /etc/letsencrypt/live/api.fabelapp.no/chain.pem;
    ssl_stapling on;
    ssl_stapling_verify on;

    if ($scheme != "https") {
        return 301 https://$host$request_uri;
    }
}
```

The actual file resides in `sites-available` and then there is a symlink from `sites-enabled`.

**Comment by ohemorange** [comment]
Ok, I've set up debian wheezy with this folder and naming structure and version of certbot and I cannot get this to reproduce. @bmw, any sense of something that this might be, in the category of "nginx changes between 0.8.1 and 0.9.0"?

**Comment by joystein** [comment]
@ohemorange , would you consider adding this structure to the testdata directory? Then i could check out the repo and see if i can get any closer in reproducing.

**Comment by ohemorange** [comment]
The testdata directory is used for unit testing and would probably not help in this situation. Would you mind checking if it works properly when you run master?

**Comment by bmw** [comment]
> @bmw, any sense of something that this might be, in the category of "nginx changes between 0.8.1 and 0.9.0"?

As you know, we largely rewrote the Nginx plugin between those two releases so there quite a few different things it could be I think. With that said, I think the most likely thing is in 0.8.1 we add a server block to `nginx.conf` if a matching one cannot be found. We removed this behavior from 0.9.0.

@joystein, when you say it works with 0.8.1, which of your Nginx configuration files are modified?

**Comment by ohemorange** [comment]
@bmw I thought that as well but looking at his server configs it seems like it adds them to the correctly found server block in the correct file.

**Comment by bmw** [comment]
> @bmw I thought that as well but looking at his server configs it seems like it adds them to the correctly found server block in the correct file.

You're correct. I should have read the entire thread before replying. I still suspect something related to that is going on though.

@joystein, after running Certbot, have `server` blocks been added to your main nginx config?

**Comment by joystein** [comment]
@bmw : with 0.8.1 _all_ my nginx config files are modified, which is part of the reason that i eagerly installed the latest version when i were about to work on certificates again.

It is only white space modifications for those files not relevant to the domain, but its still annoying to clean it up afterwards. Luckily we keep these files in git, so its not that bad.

For the config relevant to the domain, i seem to get the correct certificate settings in addition to the white space changes. And i don't think any other files gets real config changes.

**Comment by joystein** [comment]
@ohemorange : I just now tried running a version from master following these instructions:

https://certbot.eff.org/docs/contributing.html

I then get the same as before:

`Cannot find a VirtualHost matching domain some.domain.no.`

Looking closer at the logs in /var/log/letsencrypt/letsencrypt.log, it seems like certbot struggles to parse the main nginx config:

```
2016-11-29 13:28:05,710:DEBUG:certbot.main:Root logging level set at 20
2016-11-29 13:28:05,710:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-11-29 13:28:05,710:DEBUG:certbot.main:certbot version: 0.10.0.dev0
2016-11-29 13:28:05,711:DEBUG:certbot.main:Arguments: ['--nginx', '--email', 'XXXXXXX@YYYYYY.ZZZZ', '-d', 'XXXX.YYYY.ZZZZ']
2016-11-29 13:28:05,711:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#script,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#nginx,PluginEntryPoint#apache,PluginEntryPoint#null)
2016-11-29 13:28:05,711:DEBUG:certbot.plugins.selection:Requested authenticator nginx and installer nginx
2016-11-29 13:28:05,872:DEBUG:certbot_nginx.parser:Could not parse file: /etc/nginx/nginx.conf
2016-11-29 13:28:05,897:DEBUG:certbot.plugins.selection:Single candidate plugin: * nginx
```

**Comment by joystein** [comment]
If i print the error from the ParseException around  https://github.com/certbot/certbot/blob/master/certbot-nginx/certbot_nginx/parser.py#L173, i get:
```
Expected stringEnd (at char 177), (line:10, col:1)
```

The section in the config that relates to these lines:
```
user nginx;
worker_processes 10;
#error_log  /var/log/nginx/error.log warn;
error_log /var/log/nginx/error.log;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {                                                 <- should be this line
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
```

As a side-note, maybe consider changing
```
    except pyparsing.ParseException:
        logger.debug("Could not parse file: %s", item)
```
to
```
    except pyparsing.ParseException as err:
        logger.debug("Could not parse file: %s dues to %s", (item, err))
```
so there is more feedback for such issues.

**Comment by ohemorange** [comment]
Ah, thanks for the logs. Looks like this is an issue in `nginxparser.py`, which was changed to fix the spacing issue you mentioned for 0.9 - it's failing to parse the http block correctly. Looks like @pde and @bmw worked on that bit.

**Comment by joystein** [comment]
So i think i have a mostly minimal test case.

I create a small test script:
```
from certbot_nginx import parser
nginx_config_root = '/path/to/copy/of/nginx/config/root'
res = parser.NginxParser(nginx_config_root, None)
print(res)
```

I then reduce my config to this:
```
events {}
http {
map $http_x_some_header $some_var {
default "val1";
true "val2";
}
# include ;
}
```

Which fails with `Expected stringEnd (at char 10), (line:2, col:1)` (ref above comment about how to print this information prom the parsing exception).

If i remove either the events block, the map directive or the commented out include, i do not see the parsing error.

This works:
```
http {
map $http_x_some_header $some_var {
default "val1";
true "val2";
}
# include ;
}
```

This works:
```
events {}
http {
# include ;
}
```

This works:
```
events {}
http {
map $http_x_some_header $some_var {
default "val1";
true "val2";
}
}
```

**Comment by joystein** [comment]
The frustrating thing is that i can't reproduce this locally, only on the server where i originally had the issue.. :-/

**Comment by pde** [comment]
@joystein can you reproduce this on your server if you run 0.9.3 via `certbot-auto`? I'd just like to rule out the hypothesis that pip might have you using a funny version of some library or module.

**Comment by Kyoshiro-san** [comment]
I have the same issue with 0.9.3 nginx module.
> Could not parse file: /etc/nginx/nginx.conf due to error Expected stringEnd (at char 116), (line:11, col:1)

Line 11 col 1 is the beginning of the http block. Config first lines are : 
```
user www-data;
worker_processes 4;
pid /run/nginx.pid;

events {
        worker_connections 768;
        # multi_accept on;
}


http {

        ##
        # Basic Settings
        ##

```

If I move away at the end the first 3 lines it still fails on http {
Same if I move the events block.

> cat /etc/debian_version 
> 8.6

Here are my python-related packages versions : 

> libpython-dev:amd64     2.7.9-1
> libpython-stdlib:amd64  2.7.9-1
> libpython2.7:amd64      2.7.9-2+deb8u1
> libpython2.7-dev:amd64  2.7.9-2+deb8u1
> libpython2.7-minimal:amd64      2.7.9-2+deb8u1
> libpython2.7-stdlib:amd64       2.7.9-2+deb8u1
> libpython3-stdlib:amd64 3.4.2-2
> libpython3.4-minimal:amd64      3.4.2-1
> libpython3.4-stdlib:amd64       3.4.2-1
> python  2.7.9-1
> python-chardet-whl      2.3.0-1
> python-colorama-whl     0.3.2-1
> python-dev      2.7.9-1
> python-distlib-whl      0.1.9-1
> python-html5lib-whl     0.999-3
> python-minimal  2.7.9-1
> python-pip-whl  1.5.6-5
> python-pkg-resources    5.5.1-1
> python-pylibacl 0.5.2-1
> python-pyxattr  0.5.3-1
> python-requests-whl     2.4.3-6
> python-setuptools-whl   5.5.1-1
> python-six-whl  1.8.0-1
> python-urllib3-whl      1.9.1-3
> python-virtualenv       1.11.6+ds-1
> python2.7       2.7.9-2+deb8u1
> python2.7-dev   2.7.9-2+deb8u1
> python2.7-minimal       2.7.9-2+deb8u1
> python3 3.4.2-2
> python3-minimal 3.4.2-2
> python3-pkg-resources   5.5.1-1
> python3-virtualenv      1.11.6+ds-1
> python3.4       3.4.2-1
> python3.4-minimal       3.4.2-1

**Comment by ohemorange** [comment]
@Kyoshiro-san this error message is caused by a failure to parse the http block. Could you post the contents of your http block, sanitized to any extent you find comfortable?

**Comment by pierremoreau** [comment]
I have been having some parsing issues with certbot 0.10.2 and nginx 1.10.3. If I have my nginx.conf containing:
```
# General configuration file

user http;
worker_processes  4;
error_log /var/log/nginx/error.log error;
error_log syslog:server=unix:/dev/log error;
error_log /var/log/nginx/info.log info;
pid /run/nginx/nginx.pid;


events
{
    worker_connections  1024;
}


http
{
    include       mime.types;
    default_type  application/octet-stream;

    upstream php-fpm-sock
    {
        server unix:/run/php-fpm/php-fpm.sock;
    }

    upstream websocket_pool
    {
        ip_hash;
        server 127.0.0.1:22280;
    }

    map $http_upgrade $connection_upgrade
    {
        default upgrade;
        '' close;
    }

    client_max_body_size  4096;
    client_header_timeout 10;
    client_body_timeout   10;
    keepalive_timeout     10 10;
    send_timeout          10;

    server_tokens off;

    gzip  on;

    # certs sent to the client in SERVER_HELLO are concatenated in ssl_certificate
    ssl_certificate           /etc/ca-certificates/trust-source/anchors/ssl-bundle.crt;
    ssl_certificate_key       /etc/ca-certificates/trust-source/anchors/ssl-key-decrypted_2.key;
    ssl_session_timeout       1d;
    ssl_session_cache         shared:SSL:50m;
    ssl_session_tickets       off;

    # modern configuration. tweak to your needs.
    ssl_protocols             TLSv1.2;
    ssl_ciphers               'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
    ssl_prefer_server_ciphers on;

    # OCSP Stapling
    # fetch OCSP records from URL in ssl_certificate and cache them
    ssl_stapling on;
    ssl_stapling_verify on;

#    # verify chain of trust of OCSP response using Root CA and Intermediate certs
#    ssl_trusted_certificate

    include sites-available/mail.conf;
    include sites-available/nouveau.conf;
    include sites-available/perso.conf;
    include sites-available/phabricator.conf;
    include sites-available/blog.conf;
    include sites-available/trips.conf;
}
```

If I remove the map block from the config file, everything works fine:
```
    map $http_upgrade $connection_upgrade
    {
        default upgrade;
        '' close;
    }
```

I'll be happy to provide more information if needed.

**Comment by Kyoshiro-san** [comment]
Sorry for the delay, here is mine.
This could indeed be the map block.

> user www-data;
> worker_processes 4;
> pid /run/nginx.pid;
> 
> events {
>         worker_connections 768;
>         # multi_accept on;
> }
> 
> 
> http {
> 
>         ##
>         # Basic Settings
>         ##
> 
>         sendfile on;
>         tcp_nopush on;
>         tcp_nodelay on;
>         keepalive_timeout 65;
>         types_hash_max_size 2048;
>         # server_tokens off;
> 
>         # server_names_hash_bucket_size 64;
>         # server_name_in_redirect off;
> 
>         include /etc/nginx/mime.types;
>         default_type application/octet-stream;
> 
>         ##
>         # Logging Settings
>         ##
> 
>         access_log /var/log/nginx/access.log;
>         error_log /var/log/nginx/error.log;
> 
>         ##
>         # Gzip Settings
>         ##
> 
>         gzip on;
>         gzip_disable "msie6";
> 
>         gzip_vary on;
>         gzip_proxied any;
>         gzip_comp_level 6;
>         gzip_buffers 16 8k;
>         gzip_http_version 1.1;
>         gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
> 
>         ##
>         # Virtual Host Configs
>         ##
>         map $http_upgrade $connection_upgrade {
>           default upgrade;
>           ''      close;
>         }
> 
>         include /etc/nginx/conf.d/*.conf;
>         include /etc/nginx/sites-enabled/*;
> }
>

**Comment by srnfr** [comment]
I've found another "keyword" that get the nginx parser to fail parsing the conf file : access **syslog**:

`DEBUG:certbot_nginx.parser:Could not parse file: /etc/nginx/xxx.conf`

The conf file contains:
`access_log syslog:server=unix:/dev/log,facility=auth,tag=nginx_post,severity=info custom;`

Commenting this line makes the parser work ok.
Hope this helps.

**Comment by silverwind** [comment]
I've also been hit by this parser bug, specifically this line triggers it

```nginx
add_header Cache-Control no-cache,no-store,must-revalidate,max-age=0;
```

Quoting the string fixed it for me:

```nginx
add_header Cache-Control "no-cache,no-store,must-revalidate,max-age=0";
```

**Comment by joystein** [comment]
After this was merged, things are now working as expected. Thanks a lot!

**Comment by ohemorange** [comment]
Glad to hear that! Be sure to report back if you encounter any issues.

**Comment by pierremoreau** [comment]
I can confirm that 0.13 fixed my issue as well. Thank you very much!
