### ISSUE TITLE
certbot node server port 9001

### ISSUE THREAD

**Issue by GiacomoSilli** [certbot/certbot#3801]
Hi everyone, I just installed certbot! Fantastic.
It works correctly with apache.
https: // myvps / website /

I have a question, if I want to use it  for a node.js server is possible?
i.e. https: // myvpsdomain: 9001

I am not sure if i can do something like that, what do you think?
I tried to change the ports of the node server from 9001 to 80/443, of course disabling apache.

But maybe,  my reasoning is wrong, the certification does not work without apache, right?

**Comment by GiacomoSilli** [comment]
Well, i've solved by adding this in my server.js

var options = {
        key: fs.readFileSync('/etc/letsencrypt/archive/*******/privkey1.pem'),
        cert: fs.readFileSync('/etc/letsencrypt/archive/***********/cert1.pem'),
        ca: fs.readFileSync("/etc/letsencrypt/archive/**********/chain1.pem")
    };

**Comment by joohoi** [comment]
> Well, i've solved by adding this in my server.js

>var options = {
>        key: fs.readFileSync('/etc/letsencrypt/archive/*******/privkey1.pem'),
>        cert: fs.readFileSync('/etc/letsencrypt/archive/***********/cert1.pem'),
>        ca: fs.readFileSync("/etc/letsencrypt/archive/**********/chain1.pem")
>    };


I don't know about node but my guess is that it should be able to follow symlinks. Hence it's better to use paths /etc/letsencrypt/live/******/privkey.pem and so on. It's a symlink to the most recent cert under archive - directory and is kept up to date after renewals by certbot.

**Comment by GiacomoSilli** [comment]
hi,
Do you mean, i should use live folder instead of archive?
If it is not what you mean, can you give me an example?

**Comment by joohoi** [comment]
That's exactly what I mean, use live directory instead of archive :)

**Comment by GiacomoSilli** [comment]
Thank you!

But still I did not understand the mechanism

If i use port 443 with apache, I can use the https for X websites

But if i use the port 443 on node server for my app, I can not use the https for nothing else, for example turnserver, or another app on port 8083

The question is, can i use certbot on more than one port? Rather than just port 443?

**Comment by joohoi** [comment]
If you have port 80 or 443 free, you can use Certbot to acquire a certificate using Standalone plugin.

If you are running Apache in the ports mentioned above, you can use Apache plugin to acquire certificate.

If you are running a httpd of any flavor that serves files off from filesystem, you can use Webroot plugin to acquire certificate.

Regardless of the method used to get the certificate, you are able to use the cert in any software supporting X509 certificates, and serving from the domain you have the certificate for.

**Comment by GiacomoSilli** [comment]
I just realized that I can use the same certificate for apache and node servers in the same way, so not only on port 443, but on all the ports I want.

I have only a problem using those certificates for turnserver/coturn, but I do not think I can ask for help about this, here.

Thanks for the help.
