### ISSUE TITLE
Add an AUTHORS.rst file

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3802]
People like to be recognized for their work. I don't think it's necessary for us to add someone's name after every PR, however, we should tell people it's there and they're free to add their name to the file if they make a contribution to Certbot.

Since we're adding this file years into Certbot development, we should make sure we include everyone who helped us get where we are now. Going forward, I think we can only add people who send us a PR with the change themselves or make a truly notable contribution to Certbot that we want to recognize them for.

We can potentially also think about a hierarchy for listing contributors. On the one hand, this brings special attention to people who have really helped the project and we want to thank for all their help, but on the other hand it creates likely arbitrary boundaries where we are recognizing some people more than others.

**Comment by thomaszbz** [comment]
There's another advantage: Attracting more developers by documenting that the project is really open to new contributors. I even think that especially one-time-committers document such an openness in a perfect manner (e.g. low hurdle to contribute).

If there is some sort of hierarchy (e.g. core-devs), I think that should not be an issue.

**Comment by bmw** [comment]
Closing as a duplicate of #211.
