### ISSUE TITLE
Error codes for restart script?

### ISSUE THREAD

**Issue by yamlfd** [certbot/certbot#3812]
Is there a way to get an error code from certbot-auto? I'd only like to run this commands if the certificate has been successfully renewed.

```
service apache2 reload
service postfix reload
service dovecot restart
```

and if the certificate renew failed I'd like to get an email...

**Comment by pde** [comment]
Try this: `certbot renew --renew-hook "service apache2 reload && service postfix reload && service dovecot restart"`.

Be aware of #3394 until 0.10.0 is released.
