### ISSUE TITLE
"pip install cryptography" failure on CentOS 7 VPS

### ISSUE THREAD

**Issue by powernic** [certbot/certbot#3813]
VPS 2GB RAM - CentOS 7
Get error:
`Command "/root/.local/share/letsencrypt/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-OMw1wU/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-PXNHBL-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.local/share/letsencrypt/include/site/python2.7/cryptography" failed with error code 1 in /tmp/pip-build-OMw1wU/cryptography
You are using pip version 8.0.3, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

`[*****@****     letsencrypt]# pip -V`
`pip 9.0.1 from /usr/lib/python2.7/site-packages (python 2.7)`

letsencrypt wget in /opt/letsencrypt

`[*****@****     letsencrypt]# ~/.local/share/letsencrypt
-bash: /root/.local/share/letsencrypt: No such file or directory`

Why I get this error?

> You are using pip version 8.0.3, however version 9.0.1 is available

`

**Comment by pde** [comment]
That's not the real error -- `pip install cryptography` is failing. Do you get more information if you run with `-vv`?

**Comment by alexsibtone** [comment]
python -m pip install --upgrade pip
