### ISSUE TITLE
ExecutableNotFound exception when "" is attempted to be executed.

### ISSUE THREAD

**Issue by jayofdoom** [certbot/certbot#3818]
Certbot appears to be attempting to execute "" (empty string) on my local machine when trying to install and test. Notably, it works when installed from the fedora package, but not when installed from pip.

Environment:
- Fully updated Fedora 24
- Virtualenv w/Python 2.7
- Installed from pip (pip install certbot)

When running certbot, I got the following error:

```
(venv) [root@levitra ~]# certbot
An unexpected error occurred:
Executable not found: can't find the executable for the dialog-like programPlease see the logfile 'certbot.log' for more details.
(venv) [root@levitra ~]# cat certbot.log
Traceback (most recent call last):
  File "/root/venv/bin/certbot", line 11, in <module>
    sys.exit(main())
  File "/root/venv/lib/python2.7/site-packages/certbot/main.py", line 749, in main
    setup_logging(config)
  File "/root/venv/lib/python2.7/site-packages/certbot/main.py", line 643, in setup_logging
    cli_handler = _cli_log_handler(config, level, cli_fmt)
  File "/root/venv/lib/python2.7/site-packages/certbot/main.py", line 621, in _cli_log_handler
    handler = log.DialogHandler()
  File "/root/venv/lib/python2.7/site-packages/certbot/log.py", line 29, in __init__
    self.d = dialog.Dialog() if d is None else d
  File "/root/venv/lib/python2.7/site-packages/dialog.py", line 1015, in __init__
    self._dialog_prg = _path_to_executable(dialog)
  File "/root/venv/lib/python2.7/site-packages/dialog.py", line 479, in _path_to_executable
    "can't find the executable for the dialog-like "
ExecutableNotFound
```

As I said, it appears to be attempting to execute or find a program called '' (empty string) locally.

**Comment by jayofdoom** [comment]
Because I saw the previous issue about dialog potentially not supporting python 2, I verified the issue also occurs in a virtualenv built with python3.5. The traceback is nearly identical.

**Comment by bmw** [comment]
I'm also currently on Fedora 24 but I have no trouble running Certbot. Our developer installation instructions can be found [here](https://certbot.eff.org/docs/contributing.html#running-a-local-copy-of-the-client). I think the problem is that you're missing some of Certbot's non-Python dependencies.

**Comment by SwartzCr** [comment]
@jayofdoom - is this still a problem for you? If so would you be willing to try to see what versions of certbot's dependencies you have?

**Comment by SwartzCr** [comment]
I am closing this issue since it seems to be stale and no one else has reported issues with certbot-auto on fedora. Feel free to re-open, or prompt me if you feel that this is still an issue
