### ISSUE TITLE
Why does `apt-get install` installs apache2?

### ISSUE THREAD

**Issue by binarykitchen** [certbot/certbot#3822]
On my server I had all my sites configured with nginx. After installing certbot via apt-get and doing some configurations for nginx, I restarted server and after that, all my sites were down.

This because, without my knowledge, an apache2 was up running, blocking the port and thus preventing nginx from starting up. Boom.

Tried to remove apache2 only:

```
michael.heuberger@binarykitchen ~ ❯❯❯ sudo apt-get remove apache2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  apache2-bin apache2-data apache2-utils augeas-lenses certbot libaprutil1-dbd-sqlite3 libaprutil1-ldap libaugeas0 python-acme python-augeas python-certbot python-configargparse python-dialog python-funcsigs python-mock
  python-parsedatetime python-pbr python-psutil python-pyicu python-rfc3339 python-zope.component python-zope.event python-zope.hookable
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  apache2 python-certbot-apache
0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
After this operation, 751 kB disk space will be freed.
Do you want to continue? [Y/n] 
```

But no, it would uninstall everything else including certbot. Don't want to uninstall certbox when uninstalling apache2.

Is there no way to install certbot without apache2?

**Comment by hlieberman** [comment]
Hello!

This should only happen if you install python-certbot-apache.  Installing just certbot should fix the problem.  It's perfectly safe for you to remove python-certbot-apache, if you're using nginx; the certbot package shouldn't be removed.

**Comment by binarykitchen** [comment]
@hlieberman thanks but that's not entirely accurate and probably a packaging problem. already have installed like that `apt-get install certbot`. The problem is that it also installs python-certbot-apache. Here evidence, an output of what packages it installs with:

```
michael.heuberger@binarykitchen ~ ❯❯❯ sudo apt-cache depends certbot
certbot
  Depends: dialog
  Depends: python-certbot
  Depends: <python:any>
    python
  Breaks: letsencrypt
  Suggests: python-certbot-apache
  Suggests: python-certbot-doc
  Replaces: letsencrypt
    certbot
```

When I attempt to uninstall `python-certbot-apache` alone, it also will uninstall certbot, unfortunately, see:

```
michael.heuberger@binarykitchen ~ ❯❯❯ sudo apt-get remove python-certbot-apache
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  augeas-lenses **certbot** (<------ HERE) libaugeas0 python-acme python-augeas python-certbot python-configargparse python-dialog python-funcsigs python-mock python-parsedatetime python-pbr python-psutil python-pyicu python-rfc3339
  python-zope.component python-zope.event python-zope.hookable
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  python-certbot-apache
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 251 kB disk space will be freed.
Do you want to continue? [Y/n] 
```

this leads me to believe it's a packaging problem. We probably need something like `certbot-core` which doesn't install anything related to apache.

**Comment by hlieberman** [comment]
Hello @binarykitchen,

In this case, it appears you installed only python-certbot-apache.  This would pull in certbot as a leaf dependency, and cause it to be suggested for removal when you remove python-certbot-apache.

You can validate this by running `apt-mark showauto *certbot*`.  If it returns certbot in that list, then it was automatically installed as a dependency (probably by `apt-get install python-certbot-apache`), rather than as a direct installation.

You can tell apt that you want to keep certbot around after removing python-certbot-apache by running: `apt-mark manual certbot`.  Then it should be safe to remove python-certbot-apache.

**Comment by binarykitchen** [comment]
thanks - done that and works
