### ISSUE TITLE
Inconsistent domain requests

### ISSUE THREAD

**Issue by porunov** [certbot/certbot#3826]
Hello, I have a problem with obtaining certificate with certbot.

Certbot: v 0.9.3
OS: CentOS 7

Commands which I run:

```
//To generate CSR:
# openssl req -new -key mydomain.com.key -sha256 -nodes \
-subj '/C=US/ST=MyState/L=MyCity/O=MyCOMPANY/OU=IT Department/CN=mydomain.com/emailAddress=admin@mydomain.com/subjectAltName=DNS.1=www.mydomain.com,DNS.2=admin.mydomain.com,DNS.3=www.admin.mydomain.com,DNS.4=mydomain.tk,DNS.5=www.mydomain.tk' \
-outform DER -out mydomain.com.der
```

```
//To get certificate:
# certbot certonly --webroot \
--csr mydomain.com.der \
-w "/root/ssl/Ordinary_Certificate/cert/com" -d www.mydomain.com -d mydomain.com -d admin.mydomain.com -d www.admin.mydomain.com \
-w "/root/ssl/Ordinary_Certificate/cert/tk" -d mydomain.tk -d www.mydomain.tk 

Inconsistent domain requests:
From the CSR: mydomain.com
From command line/config: admin.mydomain.com, mydomain.tk, www.mydomain.tk, mydomain.com, www.admin.mydomain.com, www.mydomain.com
```

What you expected to happen:
Get a certificate

What actually happened:
I get an error

P.S. I don't run it on an actual server. After I obtain needed files I will manually send them to the server (To prove my domain).

Sincerely,
Alexandr

**Comment by pde** [comment]
What's the output of `openssl req -noout -text -in mydomain.com.der`?  It'll need to have all of the Subject Alternative Names that you're putting on the commandline.

**Comment by pde** [comment]
Oh wait, actually, I can see the problem:

You can't just add the Subject Alternative Names as part of the Subject field; they're actually a totally different field (I see [this advice](http://blog.endpoint.com/2014/10/openssl-csr-with-alternative-names-one.html) but it's never worked when I've tried it).  See these instructions instead for how to add Subject Alternative names to a CSR file:

https://www.citrix.com/blogs/2015/04/10/how-to-create-a-csr-for-a-san-certificate-on-netscaler/

**Comment by porunov** [comment]
Thank you very much! It helps.
