### ISSUE TITLE
Code duplication between apache and nginx plugins

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#383]
Rather than copying code and changing it just slightly, those plugins should share reusable code.

**Comment by diracdeltas** [comment]
This could definitely be improved by sharing common util functions (as you did in #382, thanks) and creating a configurator superclass. It didn't make sense to subclass the nginx configurator from the apache one since apache inherits from AugeasConfigurator and nginx doesn't use Augeas at all.

**Comment by kuba** [comment]
This is very partially fixed in #474.

**Comment by jdkasten** [comment]
Of course it makes editing the common code more dangerous.  As plugins (which can now be developed in complete isolation to the project) use the "common functions" we now have to worry about breaking other plugin code.

**Comment by jsha** [comment]
I think these two plugins are dramatically different now. If there's specific code that needs to be de-duplicated, please comment and reopen.
