### ISSUE TITLE
Break MainTest into BaseMainTest + class per verb

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#3832]
From https://github.com/certbot/certbot/pull/3828#discussion_r90139120

**Comment by bmw** [comment]
I still think we should do this or at the very least some major refactoring/rewriting here.

**Comment by bmw** [comment]
I think we can. Adrien and I have complained to each other about these tests in IRC and this was one of the main files I had in mind when I told @maximillianh that we had some unit tests that were hard to maintain and needed to be largely rewritten. They can be found at https://github.com/certbot/certbot/blob/master/certbot/tests/main_test.py.

I personally go back and forth about with how much I value I think there is in writing real unit tests for these high level functions vs. getting code coverage and testing on them through integration tests. Regardless, I think we should do something here and I'd be interested in hearing other people's opinions on this.
