### ISSUE TITLE
updating email address a setup-less way

### ISSUE THREAD

**Issue by drzraf** [certbot/certbot#3839]
I manage my servers' SSL using acme_tiny. I have a LE email registration and an account private key.
I'd would like to change this email ([acme_tiny](https://github.com/diafygi/acme-tiny) does not provide such an _advanced_ feature). Thus I finally installed certbot for this sole purpose.

But it happens that `certbot register --update-registration --email` does **not** accept a simple `--private-key=<PATH>` but rather expects a full _installation/initiatialization/setup/..._  phase
Am I overlooking something or is it that _certbot_ can't update the email in a simple/one-shot command run?

**Comment by pde** [comment]
@drzraf unfortunately to my knowledge, nobody has implemented account registration / portability across ACME clients. We'd certainly consider taking a PR that implements `register --import-account <keyfile>`, if someone is motivated to write one!

If you'd like to try to hack this together, you'll need to put the right contents into `/etc/letsencrypt/accounts`.  To see what it should look like, run `certbot register --register-unsafely-without-email --staging --agree-tos`, and you'll be able to see what the structure below `/etc/letsencrypt/accounts` should look like.

**Comment by pde** [comment]
It'd also make sense to support `--export-account` to spit out the account key as PEM rather than the JWS format it's currently stored in.

**Comment by drzraf** [comment]
>  [...] put the  right contents into `/etc/letsencrypt/accounts`.
> run `certbot register --register-unsafely-without-email --staging --agree-tos`

Thank you very much for the hint!
The resulting /etc/letsencrypt/accounts is not that simple.
Although import/export is clearly doable, I don't currently have the
time to automate the conversion:
(From a quick look I couldn't find an ASN1 <-> JWS Python library converter inside certbot
 sources/installed dependencies)

**Comment by bmw** [comment]
Closing in favor of #4251 which specifies the direct problem.
