### ISSUE TITLE
certbot fails to build on Gentoo

### ISSUE THREAD

**Issue by garyemiller** [certbot/certbot#3840]
Cerbot needs mock which needs the unmaintained python package bbfreeze.

Can you change certbot to only depend on packages that do not depend on abandoned code?

Also partly a gentoo packaging issue.

**Comment by pde** [comment]
We can't remove the `mock` dependency; it's used throughout our test cases.  It is however only a build/test dependency; it's not required for actually running a copy of Certbot.

**Comment by pde** [comment]
@mrueg this might be for you.

**Comment by mrueg** [comment]
@garyemiller can you provide a build log?

**Comment by garyemiller** [comment]
lots more info in the Gentoo bug:

https://bugs.gentoo.org/show_bug.cgi?id=601390

When I try to attach the build log this system says unsupported file type!

**Comment by osirisinferi** [comment]
I'm not sure how this is a `certbot` problem. I tend to think this is more a local problem: my (mostly) stable Gentoo box can `emerge` mock-2.0.0 without any problem.

**Comment by garyemiller** [comment]
This is a certbot problem because the gentoo certbot package depends on a package that can not be built.

I'd be really interested to know how you can compile mock-2.0.0.  I just tried again on a (mostly) stable host and I still get the same error.

  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2293, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named bdist_ccfreeze
error in setup command: Error parsing /var/tmp/portage/dev-python/mock-2.0.0/work/mock-2.0.0/setup.cfg: ImportError: No module named bdist_ccfreeze

**Comment by garyemiller** [comment]
I still can't figure out how to upload a build log, here it is inline.
``
 * Package:    dev-python/mock-2.0.0
 * Repository: gentoo
 * Maintainer: python@gentoo.org
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux python_targets_python2_7 python_targets_python3_4 userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking mock-2.0.0.tar.gz to /var/tmp/portage/dev-python/mock-2.0.0/work
>>> Source unpacked in /var/tmp/portage/dev-python/mock-2.0.0/work
>>> Preparing source in /var/tmp/portage/dev-python/mock-2.0.0/work/mock-2.0.0 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/mock-2.0.0/work/mock-2.0.0 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/mock-2.0.0/work/mock-2.0.0 ...
 * python2_7: running distutils-r1_run_phase distutils-r1_python_compile
/usr/bin/python2.7 setup.py build
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/usr/lib64/python2.7/site-packages/pbr/util.py", line 264, in cfg_to_args
    wrap_commands(kwargs)
  File "/usr/lib64/python2.7/site-packages/pbr/util.py", line 566, in wrap_commands
    cmdclass = ep.resolve()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2293, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named bdist_ccfreeze
error in setup command: Error parsing /var/tmp/portage/dev-python/mock-2.0.0/work/mock-2.0.0/setup.cfg: ImportError: No module named bdist_ccfreeze
 * ERROR: dev-python/mock-2.0.0::gentoo failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  115:  Called src_compile
 *   environment, line 2645:  Called distutils-r1_src_compile
 *   environment, line  783:  Called _distutils-r1_run_foreach_impl 'distutils-r1_python_compile'
 *   environment, line  342:  Called python_foreach_impl 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2175:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 1483:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 1481:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line  533:  Called distutils-r1_run_phase 'distutils-r1_python_compile'
 *   environment, line  774:  Called distutils-r1_python_compile
 *   environment, line  649:  Called esetup.py 'build'
 *   environment, line 1028:  Called die
 * The specific snippet of code:
 *       "${@}" || die "${die_args[@]}";
 * 
 * If you need support, post the output of `emerge --info '=dev-python/mock-2.0.0::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-python/mock-2.0.0::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/dev-python/mock-2.0.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-python/mock-2.0.0/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-python/mock-2.0.0/work/mock-2.0.0'
 * S: '/var/tmp/portage/dev-python/mock-2.0.0/work/mock-2.0.0'

**Comment by osirisinferi** [comment]
> I'd be really interested to know how you can compile mock-2.0.0.

I just ran `emerge -1v mock` :slightly_smiling_face: 

Also, when I run:

    # ebuild /usr/portage/dev-python/mock/mock-2.0.0.ebuild prepare
    # cd /var/tmp/portage/dev-python/mock-2.0.0/work/mock-2.0.0
    # grep -R bdist *

The only result I get is:

    docs/index.txt:2. setup.py sdist bdist_wheel upload -s
    setup.cfg:[bdist_wheel]

So I'm really not sure how your system get an error about `bdist_ccfreeze`? Do you use the Gentoo repository for this ebuild? Do you have custom patches for the ebuild?

**Comment by garyemiller** [comment]
> So I'm really not sure how your system get an error about bdist_ccfreeze?

I'm not really not sure how your system does not get an error about bdist_ccfreeze.

> Do you use the Gentoo repository for this ebuild?

Yep.  Whenever possible I use only Gentoo stable official ebuildfs.
 
 > Do you have custom patches for the ebuild?

My stable hosts have zero custom patches.

I can't figure out where bbdist_ccfreeze is supposed to come from.  Since you seem to have it, can you see how you got it?  Maybe a missing dependency in the mock ebuild?  Maybe something you pulled in from pip?

**Comment by osirisinferi** [comment]
> I can't figure out where bbdist_ccfreeze is supposed to come from. Since you seem to have it, can you see how you got it? Maybe a missing dependency in the mock ebuild? Maybe something you pulled in from pip?

I've searched with `locate -i bdist` if I've got anything like that, but I don't. It's *not* on my computer. I've got no clue why your setup would want it.

**Comment by bmw** [comment]
This issue hasn't seen any updates since 2017 and it seems to be more of an issue with the tools you're using on Gentoo. For this reason, I'm closing this, but please comment or open a new issue if you're continuing to have problems and would like me to reconsider.
