### ISSUE TITLE
error: Name does not end in a public suffix

### ISSUE THREAD

**Issue by zennokey** [certbot/certbot#3851]
not working with domen ...... **.xn--90ais**
./letsencrypt-auto certonly --manual -d ......./letsencrypt-auto ..... .xn--90ais
error:  Punycode domains are not supported

certbot certonly --manual -d ....... .xn--90ais
error: The request message was malformed :: Name does not end in a public suffix

http://letsencrypt.readthedocs.io/en/latest/contributing.html#running-a-local-copy-of-the-client

certbot version: 0.10.0.dev0

**Comment by cpu** [comment]
@zennokey This isn't a Certbot bug, but a bug with Boulder (the server side of Let's Encrypt). It's already been fixed, but the fix hasn't been deployed to production yet. You should [follow Boulder Issue 2277](https://github.com/letsencrypt/boulder/issues/2277) for more information. Thanks!

**Comment by zennokey** [comment]
How update boulder in Certbot?

**Comment by cpu** [comment]
@zennokey Certbot's tests use `tests/boulder-fetch.sh` (I believe), which is currently checking out the `docker-integration` branch of Boulder. This branch is significantly behind master and won't have IDN support (for domains or tlds). There is an outstanding issue (https://github.com/certbot/certbot/issues/3655) to update this but it will require some work on the Certbot side to fix tests.

What are you trying to accomplish? It might be easier to clone Boulder master, follow our quick-start guide, run Boulder, and then configure your Certbot clone to talk to the Boulder docker containers. This is typically how the Boulder team tests new features with Certbot.

**Comment by zennokey** [comment]
I want to get a certificate from Let's Encrypt. My domen is IDN. I do not know how ...

**Comment by mnordhoff** [comment]
@zennokey Boulder is the Let's Encrypt server software. You can't update Let's Encrypt's servers. You need to wait for them to.

https://github.com/letsencrypt/boulder/issues/2277
