### ISSUE TITLE
Turn off coveralls commenting

### ISSUE THREAD

**Issue by cowlicks** [certbot/certbot#3852]
The comments are redundant with github's new PR approval integrations.

**Comment by bmw** [comment]
The big thing we use coveralls for is the nice UI for examining which lines have cover and which don't. Has GH added this functionality and we missed it somehow?

**Comment by cowlicks** [comment]
@bmw yes, it is included in the "checks" part. See image:
![screenshot from 2016-12-07 11-15-55](https://cloud.githubusercontent.com/assets/598099/20982727/9364f388-bc6e-11e6-9a12-e6e59c0cfda8.png)

**Comment by bmw** [comment]
Ah gotcha. I misread and thought you were suggesting we could stop using coveralls entirely. I just turned off commenting.

**Comment by cowlicks** [comment]
@coveralls
You are gone but not forgotten.
We pledge to you today.
A hallowed place within the PR approval system
is where you'll always stay.

RIP
