### ISSUE TITLE
Path names with spaces

### ISSUE THREAD

**Issue by elharo** [certbot/certbot#3853]
On Mac OS X I ran

$ letsencrypt/letsencrypt-auto certonly --manual --debug

which produced a bunch of output ending in:

Creating virtual environment...
Installing Python packages...
/bin/sh: /Volumes/Macintosh HD/Users/elharo/.local/share/letsencrypt/bin/pip: "/Volumes/Macintosh: bad interpreter: No such file or directory
Traceback (most recent call last):

Looking at the output, it seems likely that the problem is some script is confused because the very common (on Macs) volume name "Macintosh HD" in my path contains a space. Probably some path needs to be double quoted somewhere in a shell or Python script. 

I believe this is 0.7.0

**Comment by pde** [comment]
Do you also see this with certbot-auto from the latest release, 0.9.3?

**Comment by pde** [comment]
In any case, I find this quite mystifying. @erikrose can you see any way this could happen?

**Comment by elharo** [comment]
I installed with homebrew. Where do I get a more recent version?

Also, looking at this now there's another possibility. It could be that the problem is a missing file or directory and a bad interpreter. However whatever code generates the error message is getting confused by the space and reporting the bad path as /Volumes/Macintosh instead of
/Volumes/Macintosh HD/Users/elharo/.local/share/letsencrypt/bin/pip

Again, just hypothesizing based on the error message. I haven't looked at the code.

**Comment by erikrose** [comment]
It sounds like the shebang line in pip itself may be bad—perhaps because of an old, buggy version of virtualenv that generated it? Can you quote for us the first few lines of `/Volumes/Macintosh HD/Users/elharo/.local/share/letsencrypt/bin/pip`?

**Comment by elharo** [comment]
I may have manually edited this to add the quotes, but right now it is:


~/xom$ more "/Volumes/Macintosh HD/Users/elharo/.local/share/letsencrypt/bin/pip"
#!"/Volumes/Macintosh HD/Users/elharo/.local/share/letsencrypt/bin/python"

# -*- coding: utf-8 -*-
import re
import sys

from pip import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

**Comment by erikrose** [comment]
Hmm. Well, time has gone by, and, unless there's some script floating around, likely in your virtualenv, with no quotes around "Macintosh HD", I'm out of ideas. It might be worth a quick recursive grep through your venv.

**Comment by bmw** [comment]
Support for certbot-auto on macOS is deprecated so I'm closing this issue.
