### ISSUE TITLE
Fully check for Nginx address equality

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#3855]
`"0.0.0.0"`, `"*"`, and `""` are equivalent to Nginx but not to the parser. This will manifest as a failure to correctly label server blocks as `ssl`, or anywhere else address equality is tested. This should probably be fixed in the Nginx `Addr` object when testing equality.

**Comment by pde** [comment]
Assigning it to Joona or Erica, whoever gets there first :)
