### ISSUE TITLE
Implement a hooks directory

### ISSUE THREAD

**Issue by pde** [certbot/certbot#3868]
It could be `/etc/letsencrypt/hooks.d/pre/`, `/etc/letsencrypt/hooks.d/deploy/` (`--renew-hook` is likely to become `--deploy-hook`), `/etc/letsencrypt/hooks.d/auth/`, etc.

**Comment by joohoi** [comment]
@oerdnj we'll be using this issue to track the process with hooks directory implementation. To avoid overlapping work, let's comment on this issue if starting work on the task.

**Comment by bmw** [comment]
Closing in favor of the older and more popular #3147.
