### ISSUE TITLE
Refactor tests to patch more correctly

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#3874]
We shouldn't really be patching in `setUp` and saving the patched mocks.

"If you use this technique you must ensure that the patching is “undone” by calling stop. This can be fiddlier than you might think, because if an exception is raised in the setUp then tearDown is not called. unittest.TestCase.addCleanup() makes this easier"
from https://docs.python.org/3.5/library/unittest.mock-examples.html

**Comment by ohemorange** [comment]
This would still be nice to clean up!

**Comment by taixx046** [comment]
Could you provide more guidance on which files and which parts need refactor?
Thanks.

**Comment by ohemorange** [comment]
A common pattern in our tests is to call `mock.patch` in the `setUp` method of our test cases, and do the associated cleanup in `tearDown`. The correct way to do it is to instead do the cleanup by calling `addCleanup`, like so:

https://github.com/certbot/certbot/blob/35fb99b86f4802694acfdefe5bcc5ba1d28e70c6/certbot/tests/ocsp_test.py#L164

I would try grepping for where `mock.patch` is called in `setUp` and seeing where there are associated calls in `tearDown`.
