### ISSUE TITLE
Self-Signed Certficates

### ISSUE THREAD

**Issue by KeremTubluk** [certbot/certbot#3879]
For environment coherency I personally like to have a way of generating self-signed certificates trough certbot that does not require a publicly accessible ip. 

Much like the --test-cert or --staging flag, a flag like --self-signed would be much appreciated.

**Comment by pde** [comment]
You can make your own self signed certs using a hook like this:

```
--renew-hook 'cd "$RENEWED_LINEAGE" && openssl req -x509 -key privkey.pem -keyout pubkey.pem -out self-signed.pem -days 365'
```

That's not a complete solution, because `openssl` still asks for things (including the domains) interactively, but you have them available by via the `$RENEWED_DOMAINS` variable so you should be able to `cat` them into an openssl conf file to automate this fully.

**Comment by pde** [comment]
If there was a broad use for this we would consider a PR for it, but it sounds like it might be something specific to your infrastructure, in which case a script hook solution may be best.

**Comment by pde** [comment]
Tagging this wontfix for now, but would reconsider if others also want this, or if the `--renew-hook` solution doesn't address your issue.

**Comment by KeremTubluk** [comment]
@pde Can probably get the --renew-hook to work and/or can always generate my own. 

Regarding the infrastructure, it is probably more about the tools/development-practices I use then the actual "infrastructure". I prefer my environments (:production, ...) to use roughly if not exactly the same setup. 

The specific problem for me was when I was trying to setup a https only development server using docker, nginx and certbot and as I later will deploy using docker and docker-cloud I would like to test as much as I can using the same configurations and tools.

**Comment by KeremTubluk** [comment]
Or perhaps I am making it more complicated then it needs to be. The better solution could be to have my development own CA using boulder.

**Comment by cpu** [comment]
> Or perhaps I am making it more complicated then it needs to be. The better solution could be to have my own development CA using boulder.

That might be the best bet. If you follow the setup instructions from the Boulder repo (I highly recommend the quickstart) and then reference the ["working with a client"](https://github.com/letsencrypt/boulder#working-with-a-client) part of the setup instructions you shouldn't have any trouble using Certbot to get a self-signed certificate from a local dev Boulder instance. Feel free to open an issue on the Boulder repo if you run into difficulties.

**Comment by pde** [comment]
OK, closing this ticket for now. Feel free to reopen if you conclude this is really of general use to the community.

**Comment by jeromeetienne** [comment]
i would like to reopen, for developement we are require to use https sometime, like when using webrtc.

And believe me to create a selfsigned certificate isnt easy, i have been looking for some time. So if certbot could help it would be great :)

**Comment by wolfgang42** [comment]
I, too, vote to reopen.

My use case is CI testing for a server configuration: part of the test involves making sure that SSL certificates are being obtained and installed correctly. At the moment, I'm using `certbot --staging` to obtain a certificate, but I want to be able to run these tests without having a public IP address.
I'd like to be able to swap `--staging` for `--self-signed` and have a setup that generates certificates with the same arrangement as a normal certificate, but without contacting an ACME sever. (Ideally, it would even check that the web server was serving `/.well-known/acme-challenge` correctly too, but that would be extra.)

**Comment by Kristaba** [comment]
I would be really interested to have this feature too.
My situation is quite similar to @wolfgang42 (not CI, but manual testing of an automatic deployment of a server infrastructure). Being able to use a simple flag for switching to self-signed certificates would make the tests more useful and easier to maintain.
I never touch the certbot's code for now, so I have no idea of the difficulty of implementation and maintaining in certbot.

**Comment by brunogoossens** [comment]
+1

**Comment by kpants** [comment]
+1. Being able to have dev and test environments identical to prod save for a command line switch would be nice. Right now I need to generate ssl certs differently and my nginx conf files are different.

**Comment by WohthaN** [comment]
+1

**Comment by hillsy** [comment]
+1 for the same sorts of reasons others have mentioned. I spin up local dev instances where I don't care if the SSL certs are trusted. But they do need to be valid e.g. for nginx to start up with the same config. 

It'd be great if all Ansible, build pipeline, nginx etc config could be **identical** except for one flag that tells certbot just to generate an untrusted certificate.

**Comment by lu4p** [comment]
+1 because it would be easier to just let certbot take care of local certificates.

**Comment by tifDev** [comment]
Is this feature implemented? I want to setup HTTPS for an IP for local access only within my home network. This would be very useful.

**Comment by fancsali** [comment]
+1 I can only second those. It would be great help when developing infrastructure automation scripts and tools.

**Comment by sobornostea** [comment]
I second those. When testing with softwares like ansible, it would be great to be able to create a certificate without having to make the IP public
