### ISSUE TITLE
Cert not yet due for renewal (but it did)

### ISSUE THREAD

**Issue by katopz** [certbot/certbot#3896]
- The version of Certbot you're running.
  * 0.9.3
- The operating system you're running it on.
  * Ubuntu 16.04.1 LTS
- The commands you ran.

`cron`
```shell
# hourly for testing usually daily
@hourly /etc/renew.sh
```
`renew.sh`
```shell
#!/bin/sh

# https://github.com/certbot/certbot/issues/1833
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

# renew
/etc/certbot-auto renew --no-self-upgrade >> /var/log/letsencrypt/renew.log

# log
echo $(date)'|Renewal' >> /var/log/letsencrypt/daily.log
```
- What you expected to happen, and
renewal success.

- What actually happened.
no renewal failures

```shell
# cat letsencrypt.log
2016-12-12 08:00:03,520:DEBUG:certbot.main:Root logging level set at 20
2016-12-12 08:00:03,522:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-12-12 08:00:03,523:DEBUG:certbot.main:certbot version: 0.9.3
2016-12-12 08:00:03,523:DEBUG:certbot.main:Arguments: ['--no-self-upgrade']
2016-12-12 08:00:03,523:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2016-12-12 08:00:03,540:INFO:certbot.renewal:Cert not yet due for renewal
2016-12-12 08:00:03,540:DEBUG:certbot.renewal:no renewal failures
```
```shell
# cat renew.log 

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/clogii.com.conf
-------------------------------------------------------------------------------

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/clogii.com/fullchain.pem (skipped)
No renewals were attempted.
```

And it actually appear [expired](https://www.ssllabs.com/ssltest/analyze.html?d=clogii.com&hideResults=on) atm.

![screen shot 2016-12-12 at 15 24 57](https://cloud.githubusercontent.com/assets/97060/21092484/4168af60-c07f-11e6-923e-ad88b789bd60.png)

I never success renewal by `cron` btw I do have another domain which can manually renewal but I won't manually renew this one yet because I really want to know what I did wrong.

Anyway I've 10 days left before it hit 30 days which I've to reinstall instead after that (am I right?) so I'll manually renew before that day which can become another issue and really hope I get answer before that.

Thanks

**Comment by joohoi** [comment]
Could you do this manual check for the cert in your system: 
`openssl x509 -dates -noout < /etc/letsencrypt/live/clogii.com/fullchain.pem`
The notAfter line shows your certificates expiration date, and this is also the check certbot does.

**Comment by katopz** [comment]
@joohoi Thanks, here it is.
`# openssl x509 -dates -noout < /etc/letsencrypt/live/clogii.com/fullchain.pem`
```
notBefore=Dec 12 05:00:00 2016 GMT
notAfter=Mar 12 05:00:00 2017 GMT
```
`# cat  /etc/nginx/conf.d/default.conf`
```
   ...
   ssl_certificate /etc/letsencrypt/live/clogii.com/fullchain.pem;
   ssl_certificate_key /etc/letsencrypt/live/clogii.com/privkey.pem;
   ...
```
And now it's working after restart `nginx` 🐛  
- - -
It's seem like I've to restart `nginx` when it success renewal am I right?
I got old let's encrypt script that will reboot after renewal but I didn't include it after migrate to `certbot` and I thought it'll do the trick for me but apparently its not.

So my `renew.sh` should be
```shell
#!/bin/sh

# log
echo $(date)'|Renewal' >> /var/log/letsencrypt/daily.log

# https://github.com/certbot/certbot/issues/1833
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

# renew
if ! /etc/certbot-auto renew --no-self-upgrade >> /var/log/letsencrypt/renew.log 2>&1 ; then
    echo Automated renewal failed:
    cat /var/log/letsencrypt/renew.log
    exit 1
fi

# reload when renew succeed
nginx -t && nginx -s reload
```

Sorry if I'm asking noob question but I'm not sure what `... 2>&1` mean and how to search for it and I feel shame to copy and paste without knowing what it did.

Thanks

**Comment by joohoi** [comment]
I think your best bet would be to use --post-hook in the cron script, eg:
`certbot-auto renew --no-self-upgrade --post-hook "service nginx restart"`

You can read more about the hook options here:
https://certbot.eff.org/docs/using.html#renewing-certificates

**Comment by katopz** [comment]
@joohoi Cool Thanks!

**Comment by Oliboy50** [comment]
it's sad, but I think @joohoi is the only way to go...
nginx is too dump to see that the certificate file has changed... so we need to restart it

**Comment by joohoi** [comment]
@Oliboy50 if you use Certbot Nginx plugin, available with the newer versions, the nginx process is restarted during the renewal, mitigating this issue. 

When using webroot, standalone or manual validation, Certbot doesn't know about the context that the renewed certificate is used in, it could be pretty much any and many services using TLS on the box, so you will have to tell Certbot which services to restart by using the provided hooks functionality.

**Comment by joohoi** [comment]
On that note, newer versions of Certbot also supports running shell scripts in hooks directories under `/etc/letsencrypt/renewal-hooks`, namely:  
- `/etc/letsencrypt/renewal-hooks/pre` for running scripts before renewal
- `/etc/letsencrypt/renewal-hooks/deploy` for running scripts when a new certificate has been acquired
- `/etc/letsencrypt/renewal-hooks/post` for running scripts after renewal

You can find more information regarding these hook directories in the [User Guide](https://certbot.eff.org/docs/using.html#pre-and-post-validation-hooks)
