### ISSUE TITLE
"certbot certificates --greppable"

### ISSUE THREAD

**Issue by pde** [certbot/certbot#3910]
The `certbot certificates` subcommand should have a flag like `--greppable` or `--grep` or `--oneline` which emits exactly one line of output per lingeage, with a constant number of columns separated by exactly one space, so that people can parse its output easily in shell scripts via `cut`.

**Comment by SwartzCr** [comment]
We've decided to close this in favor of #3909 since that is a more standardized data format, and should allow for a more wide range of uses
