### ISSUE TITLE
Extending --version

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#392]
Possible enhancements:
- return git commit if `letsencrypt --version` is run from a git working directory and an appropriate `clean`/`dirty` state indicator
- Python version
- dependent package versions (something like `pip freeze`)

This would save some effort while reporting/debugging bugs.

**Comment by bmw** [comment]
I believe this has been fixed.

**Comment by laebshade** [comment]
A --debuginfo flag might be a better idea.

**Comment by jsha** [comment]
Has experience shown that this would be useful? It seems that for most of the threads in the forums, the simple `--version` output is enough.

**Comment by bmw** [comment]
I agree. Closing this issue.
