### ISSUE TITLE
Add optional parameters to relevant commands

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#3921]
`certbot delete my_cert`, `certbot rename oldname newname`

**Comment by ohemorange** [comment]
This would still be cool to have! And would make a good issue for someone looking to dip their feet into the codebase.

**Comment by taixx046** [comment]
I don't quite understand here.
Certbot does have the delete cert functionality.
e.g. certbot delete --cert-name
Could you be more specific about what optional parameters are looking to implement?

**Comment by ohemorange** [comment]
basically, to not have to say `--cert-name`. currently you have to say `certbot delete --cert-name CERTNAME` but this is to make it so you can just say `certbot delete CERTNAME`. the `rename` subcommand no longer exists, so that part is no longer relevant.

**Comment by sshehata** [comment]
Hello, I would like to work on this issue if still relevant.
