### ISSUE TITLE
activate https for ip instead of domain

### ISSUE THREAD

**Issue by d33pak-s1ngh** [certbot/certbot#3924]
i dont have a domain name i want an https for my ip so i can access it like following
https://104.132.22.103/
is it possible to access like that 
any suggetion will be helpful.

**Comment by cpu** [comment]
Hi @d33pak-s1ngh - Boulder, the server-side component that Certbot talks to, won't issue for IP addresses. You will have to get a domain name of your own to get a Let's Encrypt certificate.
