### ISSUE TITLE
 None of the preferred challenges are supported by the selected plugin. Skipping.

### ISSUE THREAD

**Issue by garygreen** [certbot/certbot#3926]
On version 0.9.3

Trying to run:

```shell
./certbot-auto renew --dry-run --preferred-challenges=tls-sni-01
```

Results in the error:

```
Cert is due for renewal, auto-renewing...
Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
Renewing an existing certificate
Performing the following challenges:
Attempting to renew cert from /etc/letsencrypt/renewal/www.<site>.com.conf produced an unexpected error: None of the preferred challenges are supported by the selected plugin. Skipping.
```

Can't seem to find anything on google and according to the docs the "tls-sni-01" is [supported](https://certbot.eff.org/docs/using.html#getting-certificates-and-choosing-plugins), is this a bug or am I using it wrong?

**Comment by pde** [comment]
Can you post the contents of `/etc/letsencrypt/renewal/www.<site>.com.conf`?

**Comment by garygreen** [comment]
I think it's because I'm using webroot as authenticator, so you can't override for one specific command? Closing this in favour of #3742 as that's why I didn't want to use webroot and try something else like tls challenge
