### ISSUE TITLE
Renewal configuration file properties question

### ISSUE THREAD

**Issue by NazarkinRoman** [certbot/certbot#3930]
Is it possible to set `pre-hook` and `post-hook`parameters via revewal configuration files(like `/etc/letsencrypt/renewal/mysite.com.conf`)? If so, how should I do this, what section and what property names to use?

Thanks.

**Comment by pde** [comment]
It will be possible in Certbot 0.10.0 and above (See #3918 #3394).  In 0.9.3 and below, you have to set hooks on the command line or in a config file (which forces them to be the same for all of your certificates).
