### ISSUE TITLE
dns-01 challenge: allow user to configure DNS servers instead of system-defined one

### ISSUE THREAD

**Issue by leeyc0** [certbot/certbot#3933]
My company environment requires us to have different internal and public DNS servers. I need to deploy certbot in an internal network (which is configured to use internal DNS servers), but of course the DNS challenge need to be deployed in public DNS server.

Now, after I deployed the DNS challenge in public DNS server, certbot is unable to verify the DNS record (since it is NOT deployed in internal DNS server).

To workaround this issue, I have to modify the function txt_records_for_name() in certbot/acme/acme/dns_resolver.py (replaces line 37):

```
resolver = dns.resolver.Resolver(filename="user_defined_resolv.conf")
dns_response = resolver.query(name, 'TXT')
```

so that I have to define public DNS servers in user_defined_resolv.conf.

I believe it need to be changed to be a configurable option instead of hard-coded.

**Comment by joohoi** [comment]
We are going to stop using local simple_verify (which is biting you here) when we get #3890 merged, see the PR description for further details.
