### ISSUE TITLE
Does certbot renewals handle permanent 301 redirects to https?

### ISSUE THREAD

**Issue by larssn** [certbot/certbot#3950]
Our site redirects all traffic to https.

**Comment by pde** [comment]
Whether this is even a meaningful question depends on the [plugin](https://certbot.eff.org/docs/using.html#plugins) you're using and which authentication plugin(s) that challenge is using.

If you're using TLS-SNI-01 or DNS-01 authentication, this definitely won't matter.

If you're using HTTP-01 authentication, things should definitely be fine as long as you don't let your cert expire (maybe afterwards, but see varying reports https://github.com/letsencrypt/boulder/issues/1492).
