### ISSUE TITLE
What is the IP address of the verification bot?

### ISSUE THREAD

**Issue by peterkahl** [certbot/certbot#3952]
I am using an extensive blacklist of IP addresses to secure my server. This has not been a problem in the past, because the Certbot verification bot was using IP address `66.133.109.36`.

Today, I am unable to have my domain verified by the bot. Can't even see any attempt in the HTTP server logs. I suspect that my firewall is dropping the packets because the IP is no longer `66.133.109.36`.

Can you publish the list of possible source IPs?

**Comment by pde** [comment]
Let's Encrypt can't publish a list, because it is likely to change more rapidly in the future for security reasons. This is also not a Certbot issue.

I you need to confirm/deny that this is your problem today, please post this question on https://community.letsencrypt.org, or if you're really stuck, against https://github.com/letsencrypt/boulder.

**Comment by pde** [comment]
(FAQ item about this: https://letsencrypt.org/docs/faq/#what-ip-addresses-does-lets-encrypt-use-to-validate-my-web-server)

**Comment by peterkahl** [comment]
Thanks.

**Comment by peterkahl** [comment]
I've removed my firewall blocking. No change in results.

Then I used this `www.sslfofree.com` to get my certificate (getting verified).

```
Domain "i.colossalmind.com" challenge3 failed. { "type": "http-01", "status": "invalid", "error": { "type": "urn:acme:error:connection", "detail": "Could not connect to i.colossalmind.com", "status": 400 }, "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/IO--awNF3PA6eYDoVv44a-nwUiJKH-7qDmNZmAHHF2Q/440680135", "token": "efTykErs4qmVRVCIubsJ8iLdXUh7bvZ2-8VbuToDbIo", "keyAuthorization": "efTykErs4qmVRVCIubsJ8iLdXUh7bvZ2-8VbuToDbIo.jJ4zQwQTRI11WYICcefMLZFqcNd7NEp7vB9gtMzYr50", "validationRecord": [ { "url": "http://i.colossalmind.com/.well-known/acme-challenge/efTykErs4qmVRVCIubsJ8iLdXUh7bvZ2-8VbuToDbIo", "hostname": "i.colossalmind.com", "port": "80", "addressesResolved": [ "128.199.89.185", "2400:6180:0:d0::3c7:9001" ], "addressUsed": "128.199.89.185" } ] }
```

It says `status 400`, but my HTTP server logs don't record any activity whatsover. I wish there'd be more clues to help me get this sorted.

**Comment by peterkahl** [comment]
My bad. Need to understand firewalls better. Now it works. Close this ticket.
