### ISSUE TITLE
Yet another "Failed Authorization procedure"

### ISSUE THREAD

**Issue by Paladin2067** [certbot/certbot#3959]
Just setup a new virtual server with Ubuntu LAMP 16.04, when I attempt to run ./certbot-auto, I am prompted to enter the virtualhosts, however when performing the challenges I get the error message stating....

Failed authorization procedure. nextcloud.mydomain.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for TLS-SNI-01 challenge. Requested 0055bde84feaf1d831c0088e5cc832d0.0af27a65997b46e4983eabe4216289f1.acme.invalid from 1.1.1.1:443. Received certificate containing '', www.mydomain.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for TLS-SNI-01 challenge. Requested f0f2693873edf47962d5d828a20c287f.036ee57ddfb6285050d39e0480af3e7b.acme.invalid from 1.1.1.1:443. Received certificate containing '', mydomain.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for TLS-SNI-01 challenge. Requested 48ead4a02e7198d0a4913fa203119bd9.be09a817a8428cb7f1055ae1148b56d4.acme.invalid from 1.1.1.1:443. Received certificate containing '', remote.mydomain.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for TLS-SNI-01 challenge. Requested 352c8f616f797a15aa6c8404c45dbfde.e064b2ad0aa1ca126fea3415bf79878e.acme.invalid from 1.1.1.1:443. Received certificate containing ''

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: nextcloud.mydomain.com
   Type:   unauthorized
   Detail: Incorrect validation certificate for TLS-SNI-01 challenge.
   Requested
   0055bde84feaf1d831c0088e5cc832d0.0af27a65997b46e4983eabe4216289f1.acme.invalid
   from 1.1.1.1:443. Received certificate containing ''

   Domain: www.mydomain.com
   Type:   unauthorized
   Detail: Incorrect validation certificate for TLS-SNI-01 challenge.
   Requested
   f0f2693873edf47962d5d828a20c287f.036ee57ddfb6285050d39e0480af3e7b.acme.invalid
   from 1.1.1.1:443. Received certificate containing ''

   Domain: mydomain.com
   Type:   unauthorized
   Detail: Incorrect validation certificate for TLS-SNI-01 challenge.
   Requested
   48ead4a02e7198d0a4913fa203119bd9.be09a817a8428cb7f1055ae1148b56d4.acme.invalid
   from 1.1.1.1:443. Received certificate containing ''

   Domain: remote.mydomain.com
   Type:   unauthorized
   Detail: Incorrect validation certificate for TLS-SNI-01 challenge.
   Requested
   352c8f616f797a15aa6c8404c45dbfde.e064b2ad0aa1ca126fea3415bf79878e.acme.invalid
   from 1.1.1.1:443. Received certificate containing ''

Any help will be greatly appreciated.

Thanks

**Comment by pde** [comment]
Hi. Can you post the contents of `/var/log/letsencrypt/letsencrypt.log` from this run?  They should show the actual vhosts that Certbot installed for trying to pass Authorization.

**Comment by pde** [comment]
@jsha @rolandshoemaker @cpu those error messaages from Boulder are pretty uninformative -- did this webserver really present some kind of blank cert in response to the TLS-SNI-01 challenge?  Or are we just failing to populate good infromation into the ACME error here?

**Comment by cpu** [comment]
@pde No certificate at all would result in a message like "TLS-SNI-01 challenge for $BLAH resulted in no certificates" so there was definitely **some** certificate there. It does seem like the most likely explanation here is the server returned a certificate with no SANs. I don't think we consider the subject CN for the `Received certificate containing ''` message.

I believe we log the received certificate's DER bytes server-side. If @Paladin2067 can share the full logs & domain names we should be able to look at the certificate returned by the SNI server during the failed challenge validation.

**Comment by joohoi** [comment]
@Paladin2067 is this issue still relevant? If it is, could you provide logs for us to work on?

**Comment by joohoi** [comment]
Closing because of the lack of additional information
