### ISSUE TITLE
 Error while running apache2ctl graceful. ;  httpd not running, trying to start   ; Action 'graceful' failed.  

### ISSUE THREAD

**Issue by Dulanic** [certbot/certbot#3961]
Every time I try to run letsencrypt it fails.
`
![image](https://cloud.githubusercontent.com/assets/2948206/21474543/891e69a0-cae6-11e6-9836-6f889b558a97.png)

error.log
`[Sun Dec 25 21:12:28.025335 2016] [ssl:emerg] [pid 18124] AH02562: Failed to conf$
[Sun Dec 25 21:12:28.025396 2016] [ssl:emerg] [pid 18124] SSL Library Error: erro$
[Sun Dec 25 21:12:28.025416 2016] [ssl:emerg] [pid 18124] SSL Library Error: erro$
AH00016: Configuration Failed
[Sun Dec 25 21:12:28.551407 2016] [ssl:emerg] [pid 18133] AH02562: Failed to conf$
[Sun Dec 25 21:12:28.551461 2016] [ssl:emerg] [pid 18133] SSL Library Error: erro$
[Sun Dec 25 21:12:28.551476 2016] [ssl:emerg] [pid 18133] SSL Library Error: erro$
AH00016: Configuration Failed
`

**Comment by pde** [comment]
It looks like you have some problem with Apache and its SSL libraries, or perhaps with your Apache configuration. If you can figure out what that problem is and fix it, Certbot may start working!
