### ISSUE TITLE
ipv4 only support

### ISSUE THREAD

**Issue by d3xt3r01** [certbot/certbot#3963]
So, today it seems that I have an issue connecting to acme-v01.api.letsencrypt.org via ipv6 ...

```
$ curl https://acme-v01.api.letsencrypt.org -6 -v
* Rebuilt URL to: https://acme-v01.api.letsencrypt.org/
*   Trying 2a02:26f0:c000:182::3d5...
* TCP_NODELAY set
 
$ sudo mtr -n -6 -c1 --report acme-v01.api.letsencrypt.org
Start: Thu Dec 29 01:22:16 2016
HOST: d3xbucharest                Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- 2001:470:1f1b:1cb::3       0.0%     1    0.7   0.7   0.7   0.7   0.0
  2.|-- 2001:470:1f1a:1cb::1       0.0%     1   15.5  15.5  15.5  15.5   0.0
  3.|-- 2001:470:0:2ba::1          0.0%     1   15.1  15.1  15.1  15.1   0.0
  4.|-- 2001:470:0:2b3::1          0.0%     1   24.6  24.6  24.6  24.6   0.0
  5.|-- 2001:470:0:1b4::1          0.0%     1   36.8  36.8  36.8  36.8   0.0
  6.|-- 2001:470:0:213::1          0.0%     1   34.8  34.8  34.8  34.8   0.0
  7.|-- 2001:7f8::cb9:0:1          0.0%     1   42.8  42.8  42.8  42.8   0.0
  8.|-- ???                       100.0     1    0.0   0.0   0.0   0.0   0.0
```

Not sure exactly where the issue is .. other sites work just fine on v6.
Anyhow, I thought about using ipv4 .. but it seems to lack a param for that.
So, I hacked /usr/lib64/python2.7/site-packages/acme/client.py and added this

```
# At the top
from requests_toolbelt.adapters.source import SourceAddressAdapter

# At line 513
self.session.mount('http://', SourceAddressAdapter('localip'))
self.session.mount('https://', SourceAddressAdapter('localip'))
```

**Comment by d3xt3r01** [comment]
The issue at hand seems to be because sometimes acme-v01.api.letsencrypt.org resolves to 2a02:26f0:c000:183::3d5 which I fail to reach from some reason. Probably a problem on akamai peering side ... still, there should be an option to restrict connections to ipv4.

**Comment by pde** [comment]
I've asked the Let's Encrypt ops team to take a look at your routing issue. As for the Certbot flag you're after, I think we would take a PR for it so long as it preserved backwards compatibility in the `acme` module's API.

**Comment by pde** [comment]
Meanwhile you could probably work around this by editing `gai.conf`?

**Comment by d3xt3r01** [comment]
I have no idea about ```gai.conf``` !

**Comment by pde** [comment]
https://unix.stackexchange.com/questions/207312/force-ipv4-over-ipv6-only-for-certain-addresses

**Comment by pde** [comment]
(You could also put the IPv4 address for `acme-v01.api.letsencrypt.org` in `/etc/hosts`, though that's not future-proof and you would probably have to remember to take it out again once this routing problem is resolved, lest the ACME server's IP address change in the future)

**Comment by sxpert** [comment]
seems I am having a similar problem. 
connection works for ipv4, but not on ipv6.
forcing the ipv4 ip in /etc/hosts worksaround the issue.
now, I tried to debug this and here's what I have : 
we peer directly with akamai, and we go direct for ipv4, however, for some reason, we don't go direct for ipv6, the path is the following : 50620 6939 6461 20940 20940
it seems, 6461 (zayo) is doing something stupid...
