### ISSUE TITLE
Feature request: Add ability to wait N seconds after creating .well-known challenges and before checking them

### ISSUE THREAD

**Issue by archon810** [certbot/certbot#3968]
Hi,

I have a multi-server configuration with rsyncs (via lsyncd) syncing all the files across servers. A successful sync can take up to 15s, and during this moment, the webroot verification fails for a subset of subdomains.

I'd love an ability to add a custom pause as described in the title to let the file system settle.

**Comment by pde** [comment]
In the imminent 0.10.0 release, you can get something like this by using the `manual` plugin and `--manual-auth-hook` (#3890) to write, rsync, cache-clear etc your authentication files.
