### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by JustMaffie** [certbot/certbot#3970]
Hey,
I was trying to install Certbot on my CentOS 7 server.
But I got this output using the command `sudo yum install python-certbot-apache`:
`[root@*******~]# sudo yum install python-certbot-apache
Loaded plugins: fastestmirror, presto
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirrors.ircam.fr
 * epel: mirror.imt-systems.com
 * extras: mirrors.ircam.fr
 * remi: mirror.23media.de
 * remi-php56: mirror.23media.de
 * rpmforge: mirrors.ircam.fr
 * updates: mirrors.ircam.fr
No package python-certbot-apache available.
Error: Nothing to do
`

**Comment by bmw** [comment]
You have to enable the EPEL repository first. See our instructions [here](https://certbot.eff.org/#centosrhel7-apache).

**Comment by JustMaffie** [comment]
I already have EPEL repo enabled and installed.

**Comment by bmw** [comment]
Take a look at #3257 where another user was having the same problem due to issues with `yum`. If that doesn't help, let me know and I'll ping our CentOS package maintainers.

**Comment by JustMaffie** [comment]
I tried this, and it doesn't help.

**Comment by bmw** [comment]
@hogarthj, @NoodlesNZ: any ideas?

**Comment by NoodlesNZ** [comment]
Try `yum install python2-certbot-apache`

**Comment by JustMaffie** [comment]
`sudo yum install python2-certbot-apache
Loaded plugins: fastestmirror, presto
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror1.evolution-host.com
 * epel: mirror.imt-systems.com
 * extras: mirrors.ircam.fr
 * remi: mirror.23media.de
 * remi-php56: mirror.23media.de
 * rpmforge: mirrors.ircam.fr
 * updates: mirrors.ircam.fr
No package python2-certbot-apache available.
Error: Nothing to do
`

**Comment by NoodlesNZ** [comment]
I can see it on your EPEL mirror here: http://mirror.imt-systems.com/epel/7/x86_64/p/python2-certbot-apache-0.9.3-1.el7.noarch.rpm

This is not an issue with certbot. @bmw can you look at closing? Thanks

**Comment by bmw** [comment]
Thanks for looking into it!
