### ISSUE TITLE
Mention line in (Apache) conf file in case of Augeas parse/syntax error

### ISSUE THREAD

**Issue by osirisinferi** [certbot/certbot#3971]
See also the community thread [Certbot renew fails on current fedora 24 w/ apache](https://community.letsencrypt.org/t/certbot-renew-fails-on-current-fedora-24-w-apache/25046).

In summary:

When a syntax/parse error occurs when Augeas tries to parse Apache configuration files, `certbot` raises an error and mentions the file in question and the Augeaus error message.

Unfortunately, the *message* itself doesn't contain a line number, so the user has to spit through all the lines, perhaps not even knowing why Augeas complains in the first place. It would be very helpful if the error message also would contain a line number.

On [some blog post](https://stomp.colorado.edu/blog/blog/2011/01/07/on-finding-and-fixing-augeas-parse-errors/) I found Augeas does provide a line number, but this is separate from the message. And `certbot` [only fetches the message, not the line number](https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/augeas_configurator.py#L73).

Could we, for example, change the code to something like:

                msg = (
                    "There has been an error in parsing the file %s on line %s: %s",
                    # Strip off /augeas/files and /error
                    path[13:len(path) - 6], self.aug.get(path + "/line"), self.aug.get(path + "/message"))

If deemed helpful, would it need a check if there's a line number present in the Augeas error? Or does it always come with a line number? (I'm not familiar with Augeas...)

(Untested code by the way :stuck_out_tongue:)

**Comment by pde** [comment]
@osirisinferi test it and send us a PR!
