### ISSUE TITLE
Hook for after certificate is initially created

### ISSUE THREAD

**Issue by alexbowers** [certbot/certbot#3993]
Reading over the documentation it appears that the hooks only occur after `renew` is ran.

Our setup uses `certonly` and `--renew-by-default`, however when generating a certificate we have a script that must be ran, to standardise the location of the certificate and concatenate the fullchain and privkey together.

Is there a hook that gets the domain names etc like `--renew-hook` does, but is always called, on renew, create etc.

**Comment by SwartzCr** [comment]
Yeah! It's the post-hook as documented here: https://certbot.eff.org/docs/using.html?highlight=hook#renewing-certificates
That should fix things for you - I'm going to close this issue, but if you still have problems feel free to re-open it or come chat with us in #letsencrypt on freenode
