### ISSUE TITLE
cerbot rename should rename all relevant files

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#3998]

**Comment by ohemorange** [comment]
Oh yeah, just remembering why we didn't do this in the first place:

If someone's manually gone in and renamed the appropriate files and updated the renewal conf file and updated the symlinks, do we blow that all away by matching all the names to the new cert name?

I think we should.

**Comment by bmw** [comment]
In the normal case, we should rename the renewal conf file, the directory in archive, and the directory in live. I don't have a strong opinion on what we do in the case when things have inconsistent names. Some options are;

1. Change all the things.
2. Change only renewal conf file (in which case reinstallation doesn't have to happen).
3. Allow the user to choose with a prompt and/or command line flags.

To me, 3 feels the most correct™, but I'm fine with the simpler approach of 1 or 2 for now if you prefer.

**Comment by ohemorange** [comment]
Or, probably best but most annoying:

4. Just change them, but then print "we changed all the things! run <command> to undo these changes."

**Comment by bmw** [comment]
5. "We only changed your renewal conf file, run again with `--rename-all` to rename all the things"

**Comment by ohemorange** [comment]
This really isn't actually a commonly requested feature, and honestly doesn't seem worth the work it would take to get it working correctly.
