### ISSUE TITLE
Remove extra character in help output

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#3999]

**Comment by bmw** [comment]
This is a weird one. The output of `certbot --help all` has an extra space at the very beginning after "usage:". This space isn't present in the help string we provide to `ConfigArgParse`, however, the space isn't there after checking out the `v0.9.3` tag. What did we change?

**Comment by ohemorange** [comment]
Many things. See #3923.

**Comment by ohemorange** [comment]
although perhaps bisecting is the move

**Comment by ohemorange** [comment]
Are you sure it's not there in 0.9.3? I'm seeing it there as far back as ff57c718024000373923e6f80953a704cedf6647

**Comment by bmw** [comment]
You're right. I don't know why I didn't think this problem was in `v0.9.3`.

Removing the milestone tag entirely because while this should be fixed, I think it is extremely low priority.

**Comment by jsoref** [comment]
`venv/lib/python2.7/site-packages/argparse.py`:
```py
class HelpFormatter(object):
    def _format_usage(self, usage, actions, groups, prefix):
            prefix = _('usage: ')
```

**Comment by bmw** [comment]
That'd do it :smile: Thanks for looking into this @jsoref. It probably makes sense for `argparse` to do this as most programs keep the example command line format on the same line as "usage:", while we put it on the next line.

**Comment by jsoref** [comment]
I'm pretty sure you could try to pass `prefix` in to override this behavior. If you want a call stack, I should be able to get it (as could anyone else...).
