### ISSUE TITLE
running certbot turns valid-but-useless config into invalid config and fails to install when it probably can

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#4000]
```
server {
	listen 443 ssl;
	server_name existing.com;
	ssl_certificate...
}

server {
	listen 443;
	server_name new.com;

	listen 443 ssl; # managed by Certbot
	ssl_certificate... # managed by Certbot
}

server {
	listen 80;
	server_name *.com;
}
```

**Comment by bmw** [comment]
Possible solution: Don't add `listen 443 ssl;` here because it's unnecessary.

**Comment by ohemorange** [comment]
Ok, possible solutions:

- create `parser.py: add_or_update_server_directives`, which adds directives if they don't exist, and updates them to the new values if they do. use this for already-sslish blocks only. problem: we'll overwrite people's existing config settings. tricky bit: will need to check to make sure this works with included directives.

- special-case to fix this specific problem. problem: we haven't had any reports of this problem in real life, so, why?

I actually think fixing this might cause more problems than the zero problems it solves, because I think this is a different problem from the two others in #583. So, closing this.
