### ISSUE TITLE
Scan main apache configuration file for VirtualHost directives

### ISSUE THREAD

**Issue by jenlampton** [certbot/certbot#4001]
After looking over a few [other](https://github.com/certbot/certbot/issues/3791) issues it sounds like the problem I'm facing is that Certbot does not check the main httpd.conf (or apache2.conf) for any possible VirtualHost directives contained within. I understand that on Debian/Ubuntu there shouldn't be any in there, but on CentOS it is common for people to add their virualhost directives directly into the main file -- especially if there are only a few  on the server. 

I am running CentOS 6 + Apache on several Linodes and wanted to use letsencrypt. I tried to use the Certbot to install the certificates, but it was unable to locate any of the sites on the server.

I'd like to propose the code be altered to first check the main configuration file for any virtual host directives, which I hope is a simple task. (Or better yet, perhaps there is a way to ask Apache directly what it's sites are, instead of scanning the files at all.)

**Comment by joohoi** [comment]
I think the case here is that all vhosts that exist in the same file with others get ignored. We should be scanning apache2.conf / httpd.conf already, as they are default entry paths for augeas lens we are using.

Trying to handle multiple vhosts in single file caused some broken configurations getting generated, so they are currently just being ignored. There's ongoing work on this issue however.

**Comment by joohoi** [comment]
Parsing multiple vhosts per file is fixed and working, sites-available is not parsed per default in the master (and upcoming 0.19) anymore. Closing as fixed.
