### ISSUE TITLE
`cert_manager.lineage_for_certname` doesn't properly reconstitute based on `renewalparams`

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#4013]
Saw this with `server` -- it's not grabbing the staging server.

**Comment by ohemorange** [comment]
The problem is in `cert_manager.py:_search_lineages`

**Comment by ohemorange** [comment]
nvm this is a different bug because of other stuff (cert and renewal conf file out of sync).

**Comment by pde** [comment]
Is this a generalisation of #3922

**Comment by ohemorange** [comment]
Nope! This is related to #3997, in that when you hit that and then it tries to update the cert but there's an error installing, it gets the cert but doesn't save the renewal conf file, which means you have a real cert with a staging renewal conf file.

**Comment by ohemorange** [comment]
@ohemorange and @bmw will look at the community forum post
