### ISSUE TITLE
Document lineages in our user guide

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4016]
We used this concept a lot when developing Certbot and it's often a useful abstraction for thinking about certificates. We've never properly explained this term, however, so we can't really use it in our documentation.

We may or may not want to explain how lineages work to the average user, but at the very least they should be documented somewhere.

**Comment by pconrad-fb** [comment]
Looking at this from a documentation standpoint, I think it might actually be useful to add a "What Are Certificates?" section. This would accomplish two things:

- It would avoid having to jam a "Lineages" section into some other random place
- It would provide a place for the naive user to get started

We could link to a Lineages subsection in the What Are Certificates section from a few places in the doc, and then we're free to use the term "lineages" anywhere we want without worry.

If this proposal is too heavyweight, then we could add a short "Certificates and Lineages" section to either the Introduction or "Getting Certificates" in the User Guide. I'm okay with any of these options, so please pick whichever one you like.

**Comment by SwartzCr** [comment]
+1 to a "What are Certificates" section, with a lineages sub section
+1 to short thing in the introduction. It could say something along the lines of "What the client is doing is generating a ssl certificate for you. To find out more about what those are and how Certbot keeps them up to date, look here." Or something along those lines.
Looking forward to seeing a draft!

**Comment by SwartzCr** [comment]
just so I don't lose it here's seth explaining part of it: https://community.letsencrypt.org/t/link-point-to-wrong-certs/28441

**Comment by SwartzCr** [comment]
@pconrad-fb any progress?

**Comment by pconrad-fb** [comment]
I haven't jumped into lineages. I expect to do that this Wednesday or Thursday. In the mean time, "Certificates" is stalled. Can I get more directive feedback on this thread: https://github.com/certbot/certbot/pull/4370#pullrequestreview-27701860

**Comment by SwartzCr** [comment]
This should likely be closed once #4948 gets merged
