### ISSUE TITLE
Don't offer Please choose whether HTTPS access is required or optional if :80 isn't configured

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#4024]
My server isn't configured to listen to `:80`, but certbot still gives:

```
# ./certbot-auto -t -v
...
Please choose whether HTTPS access is required or optional.
-------------------------------------------------------------------------------
1: Easy - Allow both HTTP and HTTPS access to these sites
2: Secure - Make all requests redirect to secure HTTPS access
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): c

-------------------------------------------------------------------------------
Congratulations! You have successfully enabled
https://test.{fqdn} and https://{censored}-test.{fqdn2}

You should test your configuration at:
https://www.ssllabs.com/ssltest/analyze.html?d=test.{fqdn}
https://www.ssllabs.com/ssltest/analyze.html?d={censored}-test.{fqdn2}
```

speaking w/ @joohoi , it seems like the right behavior is to recognize the lack of a configured web server for :80 and not ask the question at all.

Notably: the default (non `-t`) does not make it apparent that you can safely "cancel" -- which makes the default experience even less friendly.

**Comment by jsha** [comment]
Note that as of 0.10.0 we are only offering the text UI, so the "cancel" thing is not as much of an issue.

Related issue: clarify Easy/Secure language: https://github.com/certbot/certbot/issues/3328.

Also, can I ask: Why do you choose to disable port 80? It doesn't prevent a MitM from maliciously answering 80 on your behalf, and in the non-MitM case it allows you to serve a redirect just in case somebody leaves off the `https://`, or a readable error page if you want to avoid masking misconfigurations.

**Comment by jsoref** [comment]
I inheritted this configuration.

There's a lot of security through obscurity in how we run. Many of our servers while "on the internet" are only really designed for use by an individual entity, and I think a previous IT person saw :80 as an attractive nuisance.

I'm not sure that they were wrong on that point.

And yes, I understand HSTS is important. I will certainly be adjusting our configurations with time (e.g. I'm trying to deploy Let's Encrypt).

Anncedotally: we had a fax machine which was constantly getting junk faxes, I left it off for a few weeks and when I turned it back on, it didn't seem to receive the junk anymore.

**Comment by pde** [comment]
We're going to refactor the UI for the security enhancements soon (#3837 and #1123). I'm not sure whether it will go as far as not offering an 80 -> 443 redirect for people who don't listen on 80; it may be best practice to listen on 80 just to serve the redirect (though being in the preload list arguably obsoletes this, there may still be clients out there that don't know about it)

**Comment by jsha** [comment]
I think we can close this now that we just automatically add the HTTPS redirect.
