### ISSUE TITLE
Test order causes failures on some systems

### ISSUE THREAD

**Issue by felixonmars** [certbot/certbot#4030]
I am getting the following test failure in 0.10.0:

```
======================================================================
FAIL: test_post_hooks (certbot.tests.hook_test.HookTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/certbot/src/certbot-0.10.0/certbot/tests/hook_test.py", line 70, in test_post_hooks
    self._test_renew_post_hooks(0)
  File "/build/certbot/src/certbot-0.10.0/certbot/tests/hook_test.py", line 64, in _test_renew_post_hooks
    self.assertEqual(mock_run.call_count, expected_count)
AssertionError: 1 != 0
```

**Comment by bmw** [comment]
Thanks for letting us know. I'll take a look at this issue this morning and potentially do a follow up release to fix the problem.

**Comment by bmw** [comment]
The failure here has to do with the order that `python2 setup.py test` runs our unit tests. Some orderings cause the failure and some do not. Testing on ~15 different systems, about 40% have the problem. We'll do a 0.10.1 release to fix this problem so it doesn't hinder other package maintainers.

**Comment by cpu82** [comment]
Hi,

Another test failed in `certbot-0.10.0`
```
======================================================================
ERROR: test_success_revocation (certbot.tests.display.ops_test.SuccessRevocationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/usr/ports/security/py-certbot/work/certbot-0.10.0/certbot/tests/display/ops_test.py", line 401, in test_success_revocation
    mock_util().notification.assert_called_once()
  File "/usr/local/lib/python2.7/site-packages/mock/mock.py", line 721, in __getattr__
    raise AttributeError(name)
AttributeError: assert_called_once

----------------------------------------------------------------------
Ran 583 tests in 34.629s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=583 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=583 errors=1 failures=0>
```

**Comment by bmw** [comment]
@cpu82, what system are you on? How did you run our tests to trigger this error?

**Comment by cpu82** [comment]
I'm using FreeBSD 10.3/amd64, but it also fails in other supported releases.

I ran the following command:
`# /usr/local/bin/python2.7 -c  "import sys; import setuptools;  __file__='setup.py'; sys.argv[0]='setup.py';  exec(compile(open(__file__, 'rb').read().replace(b'\\r\\n', b'\\n'), __file__, 'exec'))" test`

**Comment by bmw** [comment]
Made #4040 to track that specific problem. We'll do an 0.10.1 release to fix both problems soon.

**Comment by cpu82** [comment]
Thanks for the quick fix.
