### ISSUE TITLE
Could not find a version that satisfies the requirement acme is 0.10.0

### ISSUE THREAD

**Issue by liuchao1986105** [certbot/certbot#4033]
Collecting acme is 0.10.0 (from -r /tmp/tmp.QkR9wXt106/letsencrypt-auto-requirements.txt (line 174))
  Could not find a version that satisfies the requirement acme is 0.10.0 (from -r /tmp/tmp.QkR9wXt106/letsencrypt-auto-requirements.txt (line 174)) (from versions: 0.0.0.dev20151006, 0.0.0.dev20151008, 0.0.0.dev20151017, 0.0.0.dev20151020, 0.0.0.dev20151021, 0.0.0.dev20151024, 0.0.0.dev20151030, 0.0.0.dev20151104, 0.0.0.dev20151107, 0.0.0.dev20151108, 0.0.0.dev20151114, 0.0.0.dev20151123, 0.0.0.dev20151201, 0.1.0, 0.1.1, 0.2.0, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.9.2, 0.9.3)
No matching distribution found for acme==0.10.0 (from -r /tmp/tmp.QkR9wXt106/letsencrypt-auto-requirements.txt (line 174))
/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
 SNIMissingWarning
/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 8.0.3, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
  

Certbot has problem setting up the virtual environment.

**Comment by yannik-b** [comment]
Had same issue and upgraded pip to version 9.0.1. Now I have the following error:
`Creating virtual environment...
Installing Python packages...
Installation succeeded.
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 13, in <module>
    from acme import jose
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /root/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: OPENSSL_sk_num`

**Comment by ohemorange** [comment]
@liuchao1986105, could you try running it again? This is likely caused by a delay between when some packages were uploaded to the server but other hadn't been yet, and all packages should be on the server now.

**Comment by ohemorange** [comment]
@yannik-b, try running `rm -rf ~/.local/share/letsencrypt` and then rerunning `certbot-auto`. This may be the same issue as https://github.com/certbot/certbot/issues/1646#issuecomment-265113738.

**Comment by yannik-b** [comment]
@ohemorange No. It's the same problem again

**Comment by bmw** [comment]
@yannik-b, what's the output of `openssl version`?

**Comment by yannik-b** [comment]
@bmw 
> OpenSSL 1.1.0c  10 Nov 2016

**Comment by bmw** [comment]
@reaperhulk, any thoughts here? Cryptography errors out at runtime when it's imported with:
```
ImportError: /root/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: OPENSSL_sk_num
```

**Comment by reaperhulk** [comment]
`OPENSSL_sk_num` is a symbol used under the covers for manipulating stack structures. It was added in 1.1.0 and did not exist prior to that, so the problem here is likely that it's looking at the 1.1.0 include headers during compile but then loading an older OpenSSL.

I really cannot emphasize enough that it is extremely difficult to install your own custom OpenSSL and expect it to work reliably. The way the compiler does include and linker paths can be extremely counterintuitive.

**Comment by zjjott** [comment]
+1
`from certbot.main import main` raise this exception

**Comment by philippeowagner** [comment]
Have the same issue on an older server having OpenSSL `0.9.8o 01 Jun 2010`.

**Comment by philippeowagner** [comment]
This worked for me 

```git clone https://github.com/letsencrypt/letsencrypt/
cd letsencrypt
git reset --hard ce4e00569e6d8ed3d51c5a078d4281bec5f8e5f0 # see release page for more info
./letsencrypt-auto  --no-self-upgrade renew
```

**Comment by morganrallen** [comment]
I'm experiencing this same problem. My system has pip 9.0.1 installed but `letsencrypt-auto` insists I have 8.0.3 installed.

**Comment by quinncomendant** [comment]
I was getting the same error of `Certbot has problem setting up the virtual environment` and `You are using pip version 8.0.3, however version 9.0.1 is available` when running certbot-auto via cron. Running certbot-auto regularly (as root) works fine. To solve this I had to add `export HOME=/root` to the start of the cron command, like this:

    48 */11 * * * export HOME=/root; /root/bin/certbot-auto renew --quiet --no-self-upgrade

**Comment by morganrallen** [comment]
Thanks for the tip, that got me running again.

**Comment by philippeowagner** [comment]
Today my [suggested work around](https://github.com/certbot/certbot/issues/4033#issuecomment-273486374) stopped working. The problem was, that I had not enough free memory on the server. After freeing the memory I was able to re-use letsencrypt-auto.

**Comment by SwartzCr** [comment]
So is this fixed for people now? Or are new occurrences still popping up?
It seems like the pip mismatch came from a bad release - so now it shouldn't be an issue? What do you think @ohemorange ?

**Comment by ohemorange** [comment]
@SwartzCr nope, this wasn't a bad release -- this is both having custom versions of OpenSSL and cron not running as root.

**Comment by hangqiu** [comment]
@philippeowagner after using the workaround, I'm still having the OPENSSL_sk_num issue. Nobody touched the server for openssl upgrade. The version was 1.0.1. I tried installing the newer version 1.1.0 but it seems that the certbot would never recognize it. Any thoughts?

**Comment by fengmk2** [comment]
https://github.com/certbot/certbot/issues/4309 Maybe cause by pip mirror.

**Comment by philippeowagner** [comment]
I still have issues w/o the work around.

**Comment by pde** [comment]
Changing the bug title to not have a misleading messages that causes people to wind up here from searches.

**Comment by pde** [comment]
Since the the original reporter had a Chinese name, I suspect they may have been having trouble with pip mirrors (as per #4309) because pypi itself is blocked in China? Because of the confusing message about pip versions, I think lots of other people have been winding up on this issue for unrelated reasons.
