### ISSUE TITLE
certbot-auto re-installs virtualenv when plugin is causing issues

### ISSUE THREAD

**Issue by gboudreau** [certbot/certbot#4034]
When running `certbot-auto`, and it tries to see if it needs to update itself, if a plugin is causing the `letsencrypt --version` to NOT return the version number, `certbot-auto` will not show any error, and will simply re-install the virtualenv completely.
I would expect certbot-auto to instead return the error returned by `letsencrypt --version`, and simply exit.
This will allow me to fix what is wrong with the installed plugin, or uninstall it.

**Comment by pde** [comment]
Can you provide an example of one of these plugin errors?

**Comment by gboudreau** [comment]
Most definitely; I had it with my own plugin: [certbot-heroku](https://github.com/gboudreau/certbot-heroku)

    $ ~/.local/share/letsencrypt/bin/letsencrypt --version
    Error: can't find Heroku CLI

Granted, what the plugin did was quite dumb (looking for the Heroku CLI binary outside the class, and raising a `PluginError()` if not found; something I now fixed), but I don't think `certbot-auto` shouldn't assume all plugins will always act as expected, and thus it should properly handle failures to get the letencrypt version.

Or maybe we want to fix this kind of issues _deeper_, and we would want certbot to somehow protect itself from bad plugins, by catching exceptions thrown when loading the plugin classes, and outputing a warning maybe?
