### ISSUE TITLE
certbot won't start because of AttributeError: 'module' object has no attribute 'DependencyError'

### ISSUE THREAD

**Issue by dongmaster** [certbot/certbot#4036]
- The version of Certbot you're running.
0.9.3

- The operating system you're running it on.
Debian testing

- The commands you ran.
```
$ sudo apt-get install python-certbot-apache
$ certbot --help
```

- What you expected to happen, and
I expected to get the output of the --help switch.

- What actually happened.
```
$ certbot --help
An unexpected error occurred:
AttributeError: 'module' object has no attribute 'DependencyError'
Please see the logfile 'certbot.log' for more details.
```
certbot.log:
```
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.9.3', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 732, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/disco.py", line 175, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/disco.py", line 34, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2264, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2270, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 21, in <module>
    from certbot.plugins.util import path_surgery
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/util.py", line 20, in <module>
    except acme_errors.DependencyError:  # pragma: no cover
AttributeError: 'module' object has no attribute 'DependencyError'
```

**Comment by dongmaster** [comment]
Fixed it by installing certbot with this https://certbot.eff.org/docs/install.html#certbot-auto

**Comment by sjalex** [comment]
that's not a fix!

**Comment by own3mall** [comment]
Happened to me as well on Ubuntu 14.04.

I ran this command to fix it:

`python2 -m pip install --upgrade six`

**Comment by smremde** [comment]
This should be reopened and fixed. I just got this on ubuntu 16.04

```
$ sudo certbot --nginx
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.19.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 16, in <module>
    from certbot import account
  File "/usr/lib/python2.7/dist-packages/certbot/account.py", line 17, in <module>
    from acme import messages
  File "/usr/lib/python2.7/dist-packages/acme/messages.py", line 46, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
```
Fixed it with
```
$ pip install -U six
Collecting six
  Downloading six-1.11.0-py2.py3-none-any.whl
Installing collected packages: six
  Found existing installation: six 1.8.0
    Uninstalling six-1.8.0:
      Successfully uninstalled six-1.8.0
Successfully installed six-1.11.0
$sudo certbot --nginx
```

**Comment by bmw** [comment]
I think the cause of these problems is a mix of Python packages provided from your package manager and `pip`. [We strongly recommend](https://certbot.eff.org/docs/install.html#installing-from-source) you don't `pip install` packages like this as it can corrupt packages on your system and results in problems like this.

`certbot-auto` works around the problem by minimizing it's reliance on packages installed elsewhere on your system. Our [PPA](https://launchpad.net/~certbot/+archive/ubuntu/certbot) is unaffected by this problem as it includes a version of `six` new enough to avoid these issues.

If you don't think this is the cause of your problems, I'm happy to look into it, however, I'd like to know what supported installation method you used that resulted in a newer version of `six` not being installed.

**Comment by bmw** [comment]
If you hit this problem installing from `pip`, we [don't support installing Certbot from pip outside of a virtualenv](https://certbot.eff.org/docs/install.html#installing-from-source), but #5339 should help workaround the problem for future users who try this.

**Comment by smremde** [comment]
To be clear: I didn't install cert-bot using pip. I followed the instructions here: https://certbot.eff.org/#ubuntuxenial-nginx

**Comment by bmw** [comment]
But how did you end up with `six 1.8.0` installed on Xenial? It comes with [six 1.10.0](https://packages.ubuntu.com/xenial/python-six) and our PPA includes a newer version as well as I wrote above.

I think the answer is `six 1.8` was installed through `pip`. I was able to reproduce this by installing `six 1.8` through `pip` and then installing our packages through the PPA. While a newer version of `six` is installed, the version installed by `pip` takes precedence.

I'm glad you got your installation working and if you have suggestions of things we can reasonably do on our end to help with this, I'm open to ideas, but I think is a general and hard problem resulting from using multiple package managers that don't know about each other on the same system.

**Comment by smremde** [comment]
I think maybe I miss-understood your comment https://github.com/certbot/certbot/issues/4036#issuecomment-352636492 and thought you thought I was installing certbot via pip. 

It is possible that I installed six via pip in the dim and distance past. apt does indeed show six 1.10  installed. I think your hypothesis is correct. 

I don't know python or pip, but I do find it strange that that you can't specify which version of a package you want to use, if multiple ones are available.

**Comment by bmw** [comment]
> I think maybe I miss-understood your comment https://github.com/certbot/certbot/issues/4036#issuecomment-352636492 and thought you thought I was installing certbot via pip. 

I wasn't sure how you installed Certbot but your interpretation was correct. I was talking about installing Certbot through `pip` there as the linked PR should slightly improve the experience there. I talked about `certbot-auto` and our PPA in the prior post.

> I don't know python or pip, but I do find it strange that that you can't specify which version of a package you want to use, if multiple ones are available.

You can specify this at install time, we do, and both `apt` and `pip` will install the correct versions. The problem comes at runtime where Python just imports the package with the matching name. Python looks in different directories on your system for a matching package and may find one that wasn't properly updated such as `six` because `pip` didn't know Certbot was installed and `six` had to be upgraded.

I hope that helps explain the issue here!

**Comment by smremde** [comment]
It does - thanks. I'm not sure there is much more you can do. Perhaps the installation guide could have a troubleshooting section, but the small minority of people who have this issue using this software will be the kind of people who can easily google the answer!

Keep up the good work!

**Comment by SimZal** [comment]
I got the [same](https://github.com/certbot/certbot/issues/4036#issuecomment-352401140) error with a fresh install of Ubuntu 16.04 with LAMP. 
I followed the [certbot docs](https://certbot.eff.org/#ubuntuxenial-apache).
