### ISSUE TITLE
nginx plugin fails to recognize server_names in multiple server blocks in single file

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#4061]
Steps to reproduce:

- Create a file in /etc/nginx/sites-enabled/default that contains two `server { }` blocks, each with a different `server_name`
- Run `certbot-auto --nginx`

Expected result:

Prompted to activate HTTPS for both `server_name`s.

Actual result:

Prompted to activate HTTPS only for the first `server_name`.

**Comment by bmw** [comment]
Interesting. Testing this with the following file and Certbot `master`, I can't repro:
```
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    server_name example.org;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 80;
    listen [::]:80;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    server_name www.example.org;

    location / {
        try_files $uri $uri/ =404;
    }
}
```
Can you provide a copy of the file you used?

**Comment by jsha** [comment]
Ok, looks like this was a case of user error. Unfortunately I already modified the files that were affected, but I followed the same steps to reproduce and couldn't reproduce. I think I must have copied the server block and run certbot before remembering to change the server_name in the second server block. Sorry for the bother!
