### ISSUE TITLE
Failures in storage.py

### ISSUE THREAD

**Issue by myrrlyn** [certbot/certbot#4077]
Usage: any invocation of `certbot`

Installation: `sudo pacman -S certbot` => `/usr/lib/python2.7/site-packages/certbot`

Error: An unexpected error occurred: ValueError: max() args is an empty sequence

Traceback: storage.py, line 682, in latest_common_version

Code:
```python
    def latest_common_version(self):
        """Newest version for which all items are available?

        :returns: the newest available version for which all members
            (``cert, ``privkey``, ``chain``, and ``fullchain``) exist
        :rtype: int

        """
        # TODO: this can raise CertStorageError if there is no version overlap
        #       (it should probably return None instead)
        # TODO: this can raise a spurious AttributeError if the current
        #       link for any kind is missing (it should probably return None)
        versions = [self.available_versions(x) for x in ALL_FOUR]
        return max(n for n in versions[0] if all(n in v for v in versions[1:]))
```

Fix:
```python
        #return max(n for n in versions[0] if all(n in v for v in versions[1:]))
        try:
                return max(n for n in versions[0] if all(n in v for v in versions[1:]))
        except:
                return 1
```

**Comment by bmw** [comment]
What Certbot commands did you run to make this happen? Do you have any logs of the issue? They are stored in `/var/log/letsencrypt` by default. Feel free to redact any information like e-mail/IP addresses and domain names as you feel is appropriate.

**Comment by myrrlyn** [comment]
The initial bug incident occurred during `certbot certonly`, but attempts to reproduce by discarding my certificates and starting over work perfectly.

`certbot renew`, however, fails with the same error. The log is [here](https://myrrlyn.net/certbot-renew.log). The stderr printout is:

```
λ sudo certbot renew
[sudo] password for myrrlyn: 
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/ts.myrrlyn.net.conf
-------------------------------------------------------------------------------
Attempting to renew cert from /etc/letsencrypt/renewal/ts.myrrlyn.net.conf produced an unexpected error: max() arg is an empty sequence. Skipping.

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/apocrypha.es.conf
-------------------------------------------------------------------------------
Attempting to renew cert from /etc/letsencrypt/renewal/apocrypha.es.conf produced an unexpected error: max() arg is an empty sequence. Skipping.

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/myrrlyn.net.conf
-------------------------------------------------------------------------------
Attempting to renew cert from /etc/letsencrypt/renewal/myrrlyn.net.conf produced an unexpected error: max() arg is an empty sequence. Skipping.

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/ts.myrrlyn.net/fullchain.pem (failure)
  /etc/letsencrypt/live/apocrypha.es/fullchain.pem (failure)
  /etc/letsencrypt/live/myrrlyn.net/fullchain.pem (failure)
3 renew failure(s), 0 parse failure(s)
```

**Comment by bmw** [comment]
Have you manually modified your `/etc/letsencrypt` directory? This should only be possible if you moved files in `/etc/letsencrypt/live` or `/etc/letsencrypt/archive`.

**Comment by myrrlyn** [comment]
I threw out `live` and `archive` to try again for that log; after throwing out the entire `/etc/letsencrypt` directory and starting from scratch, `certonly` and `renew` both appear to have worked correctly.

Close this as a Heisenbug, I guess.

**Comment by bmw** [comment]
Basically it's hard coded assumptions in Certbot about the contents of `/etc/letsencrypt`. We're trying to be more flexible here and produce better errors though (see #2918).

If you ran into this bug running `certbot certonly` without a manually modified `/etc/letsencrypt` directory, I'd like to keep this open to see if we can find the problem. You don't happen to have a log of the initial incident do you?

**Comment by myrrlyn** [comment]
Trackpad slipped and I clicked the wrong comment button -_-

Get Outlook for Android<https://aka.ms/ghei36>




On Thu, Jan 19, 2017 at 12:33 PM -0700, "Brad Warren" <notifications@github.com<mailto:notifications@github.com>> wrote:


Reopened #4077<https://github.com/certbot/certbot/issues/4077>.

**Comment by myrrlyn** [comment]
I will try to reproduce and get a clean log.

**Comment by bmw** [comment]
Any luck reproducing?

**Comment by myrrlyn** [comment]
Not yet. Waiting on a certificate expiry.

On Mar 9, 2017 12:17 PM, Brad Warren <notifications@github.com> wrote:

Any luck reproducing?

**Comment by an8** [comment]
Hello,

Might not be related but I had the same error and it was due to a misnamming of my key files. Specifically in my case:

/etc/letsencrypt/archive/domain.com/privkey1.key
instead of
/etc/letsencrypt/archive/domain.com/privkey1.pem
