### ISSUE TITLE
certbot/cli.py is too long

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4081]
Probably the easiest approach is to put `HelpfulArgumentParser` and related classes/methods into their own file. We can then use the class in `cli.py`, but it doesn't have to also be defined there.

This also dramatically simplifies unit testing `HelpfulArgumentParser`.

**Comment by SandstormVR** [comment]
Hey, my university project team and I will start working on this. We might not do it completely but we'll share what we've done anyway!
