### ISSUE TITLE
Autogenerating .ics

### ISSUE THREAD

**Issue by maxwell-public** [certbot/certbot#4084]
Hello. During generating cert, it would be great to autogenerate .ics file with cert expiration date for one--click import in internet-calendar. Therefore admin could always see all its certs.

**Comment by bmw** [comment]
Ideally, the sysadmin doesn't need to keep track of this. If Certbot is set up for automatic renewal, the certificates will renewed before they expire. If Certbot is unable to renew these certificates for some reason, it will exit with an error code and more information about what went wrong which should cause a notification to be sent to a sysadmin if root e-mail is properly set up (which I know it often isn't).

Additionally, Let's Encrypt sends you e-mail if your certificate has not been renewed and it is approaching expiration. I believe it does this 3 weeks before expiration and then again 1 week before. With this setup, if you ever get an e-mail from Let's Encrypt about expired certificates, you know there might be a problem.

If these notifications aren't enough for your use case, we could consider adding this, however, it'll probably be a wishlist ticket until other issues have been resolved.

**Comment by cpu** [comment]
> Additionally, Let's Encrypt sends you e-mail if your certificate has not been renewed and it is approaching expiration. I believe it does this 3 weeks before expiration and then again 1 week before. 

Close! 20 days, 10 days and 1 day before expiration.

**Comment by cpu** [comment]
@maxwell-public As another idea., some members of the community forum have also built a tool they call ["Let's Monitor"](https://community.letsencrypt.org/t/letsmonitor-org-monitoring-certificates/17469) (note: unofficial third party, not directly affiliated with Lets Encrypt) that can alert you about soon to expire certificates through a number of channels (SMS, etc)

**Comment by bmw** [comment]
I don't think we're going to do this in Certbot so I'm closing this issue as won't fix.
