### ISSUE TITLE
--staging places certs in /etc/letsencrypt/live/ directory

### ISSUE THREAD

**Issue by jaddison** [certbot/certbot#4086]
Shouldn't `--staging` place certs in a `/etc/letsencrypt/staging/` directory?

I'm using `--manual` mode via https://github.com/jaddison/certbot_py.

**Comment by bmw** [comment]
No. Staging also places certs in live. For it to overwrite valid certs, you have to provide `--break-my-certs` on the command line (or in a [configuration file](https://certbot.eff.org/docs/using.html#configuration-file)). You don't have to do this to overwrite staging certs with valid certs.

You can also run against staging without saving the resulting certs at all `--dry-run`.

**Comment by jaddison** [comment]
Thanks for the explanation, @bmw. For first timers, I must say it's a bit confusing. If there's never a `staging` directory, it's unfortunate that the directory that is used is labelled `live`. I assume this is a legacy decision?

No matter, you've set the record straight, will close this now. Cheers!
