### ISSUE TITLE
bug in parsing apache conf with named regex backreferences, fails with "There has been an error in parsing the file"

### ISSUE THREAD

**Issue by qnxor** [certbot/certbot#4100]
I'm on Ubuntu 16.04.1 with the deb letsencrypt 0.4.1-1. I have a section in my apache `mydomain.com-ssl.conf` as
```
<LocationMatch ^/ec/(?<userid>foo|bar)>
  Require user %{env:MATCH_USERID}
</LocationMatch>
```
This is perfectly [valid](https://httpd.apache.org/docs/2.4/mod/core.html#locationmatch) (as of apache 2.4.8) and working just fine, but letsencrypt chokes with
```
The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/apache2/sites-enabled/mydomain.com-ssl.conf', u'Syntax error'),)
```
Commenting out the section makes letsencrypt happy.

**Comment by bmw** [comment]
I reproduced this problem with `master`. Changing the line to
```
<LocationMatch "^/ec/(?<userid>foo|bar)">
```
seems to work around the problem but we should still fix this.

cc @domcleal

**Comment by qnxor** [comment]
Quotes ... well spotted (optional in this case according to spec so worth fixing, as you said)

**Comment by bmw** [comment]
I can still reproduce the problem here.

This issue might be resolved with https://github.com/certbot/certbot/issues/4799, but @joohoi, can you file an upstream bug about this? I suspect you'll be able to give them an example they can easily reproduce using something like `augtool` faster than I can.

**Comment by bmw** [comment]
This issue should be resolved when we stop using Augeas, but it just checked and it's still an issue now.
