### ISSUE TITLE
improve error reporting

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#4102]
Using `cerbot -d foo`:

Actual results:
```
Obtaining a new certificate
An unexpected error occurred:
The request message was malformed :: DNS name does not have enough labels
Please see the logfiles in ... for more details.
```

Expected results:
1. Tell me the problematic domain (certbot does when it reports errors, but not when it gets an error from boulder)
1. Ideally, I should get a single message for a single problem, not two possible errors for the same problem (see below for an actual instance of this)
1. It should be possible for certbot to report errors to users in a language other than English (this means that boulder should be reporting errors by identifier + message instead of just message)
1. Explain the problem in English (not RFC-speak)
* In English, that means "request message was malformed" should go
* If there's a problem, the explanation should also be in English, so instead of "not enough labels", hint at how many labels are required (currently it's hard coded to 2 -- but, based on what boulder could know from publicsuffix, I think this could theoretically be dynamic)

I'm not sure if certbot can report the problematic domain.
The `labels` bit comes from boulder.
The malformed bit comes from certbot.

This whole process is spread across two to four repositories (certbot/certbot, certbot/website, letsencrypt/boulder, letsencrypt/website). There's no good place for me to manage this process.

I'm happy to provide replacement text and even do the PRs. 

For reference:
```
$ certbot -d foo -d b-r -d aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -d a...a -d a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a
Requested domain aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa is not a FQDN because label aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa is too long.
```

```
$ certbot -d foo -d b-r -d a...a -d a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a
Requested domain a...a is not a FQDN because it contains an empty label.
```

```
$ certbot -d foo -d b_r -d a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a
Obtaining a new certificate
An unexpected error occurred:
The request message was malformed :: DNS name does not have enough labels
```

```
$ certbot  -d b_r -d a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.
a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.
a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.
a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a
Obtaining a new certificate
An unexpected error occurred:
The request message was malformed :: Invalid character in DNS name
```

```
$ certbot -d a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a
Obtaining a new certificate
An unexpected error occurred:
The request message was malformed :: DNS name too long
```

```
$ certbot -d a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a
Obtaining a new certificate
An unexpected error occurred:
The request message was malformed :: DNS name has too many labels
```

Personally, my preference is to be told about all errors at once.
One of the most annoying experiences I have when picking a password is being told "password too short" only to be told later "doesn't have a number" and later "needs a symbol" and then "needs a capital letter".

I'm not a strickler on that point.

But, the fact that both the client and server are trying to handle some of the same errors (`too long`) is a bit odd.
If reporting won't be "all problems", I'd personally favor reporting the error along the critical path. For my:
`a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a`
item, that would be "too may levels" as opposed to  "too long", because even if I shortened it, I would still get too many levels (as shown above).

**Comment by jsoref** [comment]
The too long instance was already fixed: #3994

**Comment by jsoref** [comment]
Imo, boulder is abusing `malformed` (which is suggested for a bad `nonce`) in ACME: https://tools.ietf.org/html/draft-ietf-acme-acme-04#section-5.5.2

**Comment by bmw** [comment]
>  Tell me the problematic domain (certbot does when it reports errors, but not when it gets an error from boulder)

I agree. This can be fixed either by having `boulder` include the problematic domain or Certbot wrapping the returned error message. Certbot is able to wrap the error message to include the problematic domain in the [current version of ACME implemented by Let's Encrypt](https://tools.ietf.org/html/draft-ietf-acme-acme-01) as each domain is requested individually. I'm not sure this is possible on our side in later versions of ACME, however, as all domains are requested at once by submitting a CSR.

> Ideally, I should get a single message for a single problem, not two possible errors for the same problem (see below for an actual instance of this)

I think this problem would have to be resolved by https://github.com/letsencrypt/boulder. Certbot is just reporting the error returned by Let's Encrypt and while we could make assumptions about what other problems might be, this is CA dependent so I think it's best solved on their end.

> It should be possible for certbot to report errors to users in a language other than English (this means that boulder should be reporting errors by identifier + message instead of just message)

This is a hard one. See #115 for the more general problem on the Certbot side. If you want `boulder` to change their error format, you should open an issue either on their repo and/or send a message to the [ACME mailing list](https://mailarchive.ietf.org/arch/search/?email_list=acme) if what you have in mind involves a protocol change.

> Explain the problem in English (not RFC-speak)

Here's what Certbot is doing here. It is taking the error type returned by the ACME CA and using it to include information about what the problem is in the general sense. This is where "The request message was malformed" comes from for `malformed` errors.

The other part of the error message comes from the CA. This is included in the detail field of the error as described in [ACME](https://tools.ietf.org/html/draft-ietf-acme-acme-04#section-5.7) and the linked RFC. With this in mind, you're proposing we rely entirely on the `detail` field provided by the CA to explain the problem to the user?

> This whole process is spread across two to four repositories (certbot/certbot, certbot/website, letsencrypt/boulder, letsencrypt/website). There's no good place for me to manage this process.

You're right that this problem touches multiple repos, however, as I described in certbot/website#184, I think the most important thing here is to improve the error messages. In my opinion, if the error messages are good enough, you don't need to document the issue on the Certbot or Let's Encrypt websites. If you agree, this problem only affects the certbot/certbot and letsencrypt/boulder repos.

> Imo, letsencrypt/boulder is abusing malformed (which is suggested for a bad nonce) in ACME

I don't think this is correct as their a `badNonce` error type specifically for this problem, however, feel free to open an issue against the letsencrypt/boulder repo if you disagree.

**Comment by jsoref** [comment]
> If you want boulder to change their error format, you should open an issue either on their repo and/or send a message to the ACME mailing list if what you have in mind involves a protocol change.

I filed https://github.com/letsencrypt/boulder/issues/2518
Offhand, I think to get this right does involve a protocol change.

**Comment by jsoref** [comment]
> Here's what Certbot is doing here. It is taking the error type returned by the ACME CA and using it to include information about what the problem is in the general sense. This is where "The request message was malformed" comes from for malformed errors.

> The other part of the error message comes from the CA. This is included in the detail field of the error as described in ACME and the linked RFC. With this in mind, you're proposing we rely entirely on the detail field provided by the CA to explain the problem to the user?

I think I'm asking for support in having ACME/boulder provide some other state than malformed for such errors. Possibly with an extensibility field to make it easier for tokens to be experimented with.

Right now, "malformed" is a poorly designed with an RFC suggested unhelpful message, and boulder has decided to use it as a catchall.

As an interim thing short of fully redesigning the RFC, It'd be helpful if there was an RFC error state
{extendedError} (wordsmithing on that elsewhere/later) which defined a two part error:
{errorToken} {errorMessage} -- where the errorToken could be treated like `malformed` and other standard errors if the client was aware of it, and with a generic `Server responded with unrecognized error condition {errorToken} saying: {errorMessage}` otherwise.

(This probably belongs in the boulder issue, but I'd like to gather some support from certbot before moving a proposal along to boulder/acme.)

**Comment by jsoref** [comment]
> Personally, my preference is to be told about all errors at once.
> One of the most annoying experiences I have when picking a password is being told "password too short" only to be told later "doesn't have a number" and later "needs a symbol" and then "needs a capital letter".

Can I gather some opinions on this point?

Imagine an ACME request could include 100 domains each with its own error.
Really, as a user, would you want to submit a request, and be told about one problem w/ your 100 domains, fix it, submit again, only to be told about a different problem (either with the same domain, or the next one)?

**Comment by jsoref** [comment]
```sh
certbot -d foo -d b_r -d a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator apache, Installer apache
Obtaining a new certificate
An unexpected error occurred:
Error creating new order :: Cannot issue for "a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a": Domain name is longer than 253 bytes (and 2 more problems. Refer to sub-problems for more information.)
Please see the logfiles in /var/log/letsencrypt for more details.
```

This is definitely an improvement. If I go to the log, I can see the other messages (not necessarily ideal, but it's better).

For the most part, the errors do appear to be English and not RFC speak.

**Comment by bmw** [comment]
Thanks for taking another look at this @jsoref.

I think the original concerns, especially the ones we can control on the Certbot side, have largely been resolved.

Some of the RFC speak such as talking about sub-problems should be resolved by the more specific https://github.com/certbot/certbot/issues/7046.

Are there other changes you think we should make here or can we close this issue? If there are other changes you'd like to see, what are they?

**Comment by jsoref** [comment]
I think I've run out of energy for this.

I might revisit at some point.

Some of the systems we were using certbot on recently lost support (from their distro and certbot), and for our newer systems are using cert-manager to wrap lets-encrypt instead of certbot.

It appears I didn't have the energy to deal w/ the RFC land. It's too bad.
