### ISSUE TITLE
Certbot struggles with hundreds of thousands certificates

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4106]
See https://community.letsencrypt.org/t/performance-issues-when-creating-renewing-certificates/26341.

Putting this in 0.11.0 for now, but we can move it as necessary.

**Comment by bmw** [comment]
One potentially easy fix here is to use `certbot.storage.renewal_filename_for_lineagename` to find the lineage matching `--cert-name` rather than iterating through `/etc/letsencrypt/renewal`.

We'd need to carefully verify we don't search `/etc/letsencrypt/renewal` anywhere else though when creating/modifying a cert with `certonly`.

**Comment by bmw** [comment]
cc @ohemorange

**Comment by schoen** [comment]
My hypothesis in that thread is that the existing command line flag `--duplicate` will succeed in skipping this check and making things faster. (Though it's not clear that this is the best solution or that people should be required to do this.)
