### ISSUE TITLE
Revoke should offer to delete revoked certificates

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4109]
See #4108.

**Comment by bmw** [comment]
Not too worried about this, but I was thinking... Will server configurations be left misconfigured after deleting certificates? Do we need an `uninstall` method for installers? (Perhaps we should write a tool call `certstrip` that converts HTTPS server configurations to HTTP :smile: .)

**Comment by lelutin** [comment]
Since !3913 implemented a `delete` option, the code for this could be reused to add this functionality at the end of a `revoke` command.

**Comment by ynasser** [comment]
@lelutin yes, that's what's currently in PR #4202 :)

We're just deciding on what do about other certs in the lineage when you revoke + delete the most recent one.
