### ISSUE TITLE
add the word `instead` to renew error

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#4118]
I tried to renew a certificate:

```sh
# ~/certbot-auto -d server.example.com renew
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Currently, the renew verb is capable of either renewing all installed certificates that are due to be renewed or renewing a single certificate specified by its name. If you would like to renew specific certificates by their domains, use the certonly command. The renew verb may provide other options for selecting certificates to renew in the future.
```

I'm not sure why my original command was rejected, I only specified one domain.
So, I naively tried to fix my command:
```sh
# ~/certbot-auto certonly -d server.example.com renew
usage:
  certbot-auto [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the


cert.


certbot: error: unrecognized arguments: certonly
```

Suggestions:
1. Accept the input I provided (my guess is that the order `-d foo renew` confused renew and had I used `renew -d foo` it would have been ok)
1. Change `the certonly command` to `the certonly command instead`. I'm not really sure why I think the word "instead" would have queued my brain to drop the word renew from the command, but I think it would have.

**Comment by bmw** [comment]
Actually you (currently) can't use `-d/--domains` with `renew` (see #4096), but we can certainly add "instead" to the error message.
