### ISSUE TITLE
certbot-auto renew not working with multiple vhosts (apache)

### ISSUE THREAD

**Issue by janvantseer** [certbot/certbot#4122]
Hi,

I have multiple vhosts on the same public ip.
When I want to update one of the vhosts, I get an error message saying that the certificate requested contains info on the **alphabetically first** vhost !

 
# /root/letsencrypt/certbot-auto renew
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/shiftz.be.conf
-------------------------------------------------------------------------------
Cert is due for renewal, auto-renewing...
Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for **shiftz.be**
tls-sni-01 challenge for **www.shiftz.be**
Waiting for verification...
Cleaning up challenges
Attempting to renew cert from /etc/letsencrypt/renewal/shiftz.be.conf produced an unexpected error: Failed authorization procedure. shiftz.be (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for TLS-SNI-01 challenge. Requested 20872c4186a3f7526f2d22d1adbf1885.b52a1de9f3bcc383715fc7b4b09cbb55.acme.invalid from 13.93.109.31:443. Received certificate containing '**barton-systems.be**, barton-systems.com, barton-systems.nl, bartonsystems.be, bartonsystems.com, bartonsystems.nl, storagespacesarray.com, www.barton-systems.com, www.bartonsystems.com, www.storagespacesarray.com', www.shiftz.be (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for TLS-SNI-01 challenge. Requested fa1a0d0131f7508d24a152d80968c10a.6064495d413079b2d8ba8806a8142d8c.acme.invalid from 13.93.109.31:443. Received certificate containing 'barton-systems.be, barton-systems.com, barton-systems.nl, bartonsystems.be, bartonsystems.com, bartonsystems.nl, storagespacesarray.com, www.barton-systems.com, www.bartonsystems.com, www.storagespacesarray.com'. Skipping.

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/shiftz.be/fullchain.pem (failure)
1 renew failure(s), 0 parse failure(s)

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: shiftz.be
   Type:   unauthorized
   Detail: Incorrect validation certificate for TLS-SNI-01 challenge.
   Requested
   20872c4186a3f7526f2d22d1adbf1885.b52a1de9f3bcc383715fc7b4b09cbb55.acme.invalid
   from 13.93.109.31:443. Received certificate containing
   'barton-systems.be, barton-systems.com, barton-systems.nl,
   bartonsystems.be, bartonsystems.com, bartonsystems.nl,
   storagespacesarray.com, www.barton-systems.com,
   www.bartonsystems.com, www.storagespacesarray.com'

   Domain: www.shiftz.be
   Type:   unauthorized
   Detail: Incorrect validation certificate for TLS-SNI-01 challenge.
   Requested
   fa1a0d0131f7508d24a152d80968c10a.6064495d413079b2d8ba8806a8142d8c.acme.invalid
   from 13.93.109.31:443. Received certificate containing
   'barton-systems.be, barton-systems.com, barton-systems.nl,
   bartonsystems.be, bartonsystems.com, bartonsystems.nl,
   storagespacesarray.com, www.barton-systems.com,
   www.bartonsystems.com, www.storagespacesarray.com'

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.

Please advise if this is a bug.

Thanks,
Jan

**Comment by pde** [comment]
Selecting the alphabetically first vhost is what you'd expect if there's no matching vhost. It looks like the Apache plugin should be creating a new vhost to perform (re)authentication, but isn't. @joohoi, want to take a look at this?

**Comment by janvantseer** [comment]
Hi,

I think I found the reason. FYI, I'm using unison to sync 2 webhosts. Every now and then, I notice a conflict. Unison then makes a copy of, in this case, the vhost configuration file. That's where Certbot stops searching for other vhosts.

Can you close this ticket?  If for any reason, I notice the same beheaviour, I'll come back to you.

Sorry for any inconvenience, thanks for replying.

Best regards,
Jan

On 31 January 2017 19:40:01 CET, Peter Eckersley <notifications@github.com> wrote:
>Selecting the alphabetically first vhost is what you'd expect if
>there's no matching vhost. It looks like the Apache plugin should be
>creating a new vhost to perform (re)authentication, but isn't. @joohoi,
>want to take a look at this?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/certbot/certbot/issues/4122#issuecomment-276451887

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
