### ISSUE TITLE
crt vs pem

### ISSUE THREAD

**Issue by FinnFrotscher** [certbot/certbot#4123]
How do I get the certifications in `.crt` and`private.key` instead of `.pem`?

I use `mup` to deploy my `meteor` app onto a server running `ubuntu 16.04`. 
`mup` requires `.crt` instead of `.pem` to run the app on https.
I used `standalone` mode and a fresh install via `apt install`.

The why and where is explained [ here ](https://github.com/kadirahq/meteor-up/issues/423)

**Comment by bmw** [comment]
`.crt` and `.key` are just different conventions. `.pem` signifies the file format, while `.crt` and `.key` signify the contents of the file. I suspect the `fullchain.pem` and `privkey.pem` files will just work for you as is, but if they don't you can follow a guide [here](https://github.com/arunoda/meteor-up#ssl-support) that makes a combined `ssl.pem` file containing the cert and key.

**Comment by FinnFrotscher** [comment]
the mup of you example is different from the one I use. Most visibly is the config from one in `json` while the other is `js`.
also: the nginx config of my mup uses [an absolute filename for the certs](https://github.com/meteorhacks/mup-frontend-server/blob/master/lib/nginx.conf#L29-L30)

**Comment by bmw** [comment]
Unfortunately, I'm not familiar with `mup` or `meteor`, however, hopefully my explanation of file conventions makes sense. If you need more help I encourage you to take a look at https://community.letsencrypt.org. There are a lot more people monitoring that forum, some of which may be able to help you configure your software. Sorry I couldn't help directly!
