### ISSUE TITLE
Parser fails parsing WebSocket connection upgrade map block

### ISSUE THREAD

**Issue by massada** [certbot/certbot#4125]
Parser fails when trying to parse the following map block:

```
map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}
```

With error:

```
Cannot find a VirtualHost matching domain
```

By removing the map block the parsing is successfully. As a workaround (in nginx) I moved the WebSocket connection upgrade to a location block and removed the map block.

I'm running version 0.9.3 on Debian 8 (Jessy).

**Comment by bmw** [comment]
Interesting! Is the `map` block and the `server` block in the same file? If so, can you provide the full contents of the file, redacting values as you feel is necessary. I'm struggling to reproduce.

**Comment by massada** [comment]
The map block was in the http block. If I move it to a different file with the server block it does work.

Here's a simple one failing:

```
events {}
http {
  map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
  }
  # include;
}
```

Fails with:
```
Expected stringEnd (at char 10), (line:2, col:1)
```

**Comment by bmw** [comment]
Got it! Thanks for the bug report and example. We'll look into this for our 0.12.0 release.

**Comment by ohemorange** [comment]
This is the same as mentioned [here](https://github.com/certbot/certbot/issues/3798#issuecomment-277311682), and should by fixed in 0.13.0.

**Comment by ohemorange** [comment]
Going to check that this is fixed, then close it.

**Comment by ohemorange** [comment]
Tested, should be working now! Look forward to this in our next release, which is due out next week.
