### ISSUE TITLE
rename common name

### ISSUE THREAD

**Issue by reynas** [certbot/certbot#4133]
I would like to change the common name of my certificates.. 
I have a domain test.example.com with a few subdomains e.g. subd1.test.example.com, subd2.test.example.com.

When I make certificates for all domains, it takes subd1.test.example.com as the common name for every subdomain I have. This can be seen by the file: 
/etc/letsencrypt/renewal/subd1.test.example.com.conf

How can I change the common name for all subdomains to just test.example.com ?

Thanks in advance!

**Comment by pde** [comment]
Certbot uses the first domain name in the list you provide/select as the CN field. So forcibly renewing the cert with the domains in a new order should do it.  Eg, run `certbot certonly --force-renew --cert-name $NAME_OF_CERT -d test.example.com,otherdomain.example.com` plus any other flags you need/are using.
