### ISSUE TITLE
Unable to connect to Let's Encrypt

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4149]
@lindhe in #3480 is reporting difficulties connecting to Let's Encrypt. Despite similar errors, the cause is likely very different than the `HTTPS_PROXY` environment variable, so we should track it in a separate issue.

@lindhe, if you're still having problems, can you run the following on your server?
```
${XDG_DATA_HOME:-~/.local/share}/letsencrypt/bin/python -c 'import requests; print requests.get("https://acme-v01.api.letsencrypt.org/directory").text'
```

**Comment by lindhe** [comment]
I couldn't run that command, most likely because I'm running certbot via a [snap of Nextcloud](https://github.com/nextcloud/nextcloud-snap/issues/178). I'm afraid I don't know how to do that correctly for the snap installation...

**Comment by kyrofa** [comment]
@lindhe ignore the snap, install certbot like you normally would.

**Comment by lindhe** [comment]
OK. I installed it via `apt install certbot`, and when I run your command I get `zsh: no such file or directory: /home/andreas/.local/share/letsencrypt/bin/python`.

However, if I run a `sudo certbot certonly -d andreaslindhe.com --dry-run`, I'm thrown into a pseudo graphical UI, and the test seems successful.

![screenshot from 2017-02-04 19-51-38](https://cloud.githubusercontent.com/assets/7773090/22620805/c6374a4e-eb13-11e6-9b9c-5fed7194e48f.png)

**Comment by bmw** [comment]
The issue you originally commented on was talking about `certbot-auto` so I assumed you were using that as well. The command I posted won't work for OS packages, but OS packages are certainly preferred for your system if they're available.

Since it appears everything is working properly for you now, I'm closing this issue.
