### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by aday395** [certbot/certbot#4150]
I got an error when running ./certbot-auto for letsencrypt: 

> IndexError: list index out of range

certbot.log showed:

> Traceback (most recent call last):
>   File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
>     sys.exit(main())
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 861, in main
>     args = cli.prepare_and_parse_args(plugins, cli_args)
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/cli.py", line 814, in prepare_and_parse_args
>     helpful = HelpfulArgumentParser(args, plugins, detect_defaults)
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/cli.py", line 442, in __init__
>     if self.args[0] == 'help':
> IndexError: list index out of range

**Comment by bmw** [comment]
Thanks for reporting this. I've repoed the problem and I'll be releasing 0.11.1 shortly.
