### ISSUE TITLE
Document configuration files

### ISSUE THREAD

**Issue by SwartzCr** [certbot/certbot#4152]
Certbot has a number of configuration files. Specifically we have a cli.ini file that handles global configuration & files in /etc/letsencrypyt/renewal that are lineage configuration files (relating to #4016)
This also relates to #4096 
These need to be documented!
In theory we only need to document cli.ini since we have other documentation about how to update the renewal configs, but if we decide that we want people to edit these by hand it would be prudent to document them.

**Comment by SwartzCr** [comment]
It sounds like @pde is interested in working on this - via his work on #4096. So I'm tagging him here so that if he chooses to do more expansive documentation we can close this ticket

**Comment by SwartzCr** [comment]
There's also #4407 and #4490 which should be mentioned (for people wanting to edit their own config files)

**Comment by troy-lamerton** [comment]
Is anyone working on this? I could pick it up.

Is it a matter of rewriting the docs in https://certbot.eff.org/docs/api/cli.html for the `cli.ini` file?

**Comment by bmw** [comment]
I think the biggest thing that needs to be done here is expanding https://certbot.eff.org/docs/using.html#configuration-file to describe how it works. The very brief version is setting options there is equivalent to setting them on the command line. If the same option is set both in the `cli.ini` file and the command line, I forget it's behavior.

Just a better description of what you can put in this file and how it works should be added to our documentation.
