### ISSUE TITLE
Document all challenges and their relationship with Certbot

### ISSUE THREAD

**Issue by SwartzCr** [certbot/certbot#4153]
Right now we suggest users use manual auth hooks to allow them to do the DNS challenge, and we even go so far as to suggest example scripts for them to run, but at no point do we explain what that challenge is doing!

There is already some things written about this in the manual plugin, which gets written out to the user when they call `certbot certonly --manual` without an auth hook flag. This command can give you information about any of our challenges, and you can specify which one by specifying that challenge with the --preferred-challenge flag.

Note that like the webroot challenge, certbot will tell the user to put certain files in certain directories to be served as part of the challenge. These files and directories are generated randomly for each run and shouldn't be put verbatim into the documentation. You can also look at these suggestions directly in the code: https://github.com/certbot/certbot/blob/master/certbot/plugins/manual.py

**Comment by schoen** [comment]
This issue should actually be about a new documentation section that talks about *all* of the challenges, what they require, and how Certbot can use each of them.

**Comment by schoen** [comment]
I'm suggesting calling the documentation section "How Certbot proves your ownership of domains".

**Comment by schoen** [comment]
@pconrad-fb, I might try to work on this but I'll let you know if I do or what progress I make.

**Comment by SwartzCr** [comment]
fyi that @schoen has a draft of this that I'm looking over - hopefully we'll have something PRable by next week

**Comment by pconrad-fb** [comment]
I'm looking at what.rst today, but as long as I'm in the neighborhood, is there a draft of the challenges content that you'd like me to look at @schoen @SwartzCr ?

**Comment by SwartzCr** [comment]
@schoen mentioned he'd post it, but I'm not sure that he has yet

**Comment by schoen** [comment]
Sorry this took me a while to put into a PR. Now available here for your editing and commenting as #4509.

**Comment by pconrad-fb** [comment]
Okay, I took a look at this. It's good, and has plenty of information. I do think there is a lot I can do to compress and restructure it without losing information. If you merge it into master, I'm happy to pull it down and submit a PR. If there's another approach you'd like me to take, let me know.

**Comment by SwartzCr** [comment]
@pconrad-fb I've merged it, so feel free to edit
I'll probably make edits on top of your edit? But as long as we don't add it to the index file it won't get published so we can edit it in master

**Comment by pconrad-fb** [comment]
I've pushed up the initial edit. Might not be perfectly clean yet (may be a typo or two in there somewhere) as I was mainly focusing on restructuring the content.

Remaining questions:
Can manual also use TLS-SNI-01?
What assumptions to plugins make about the Apache or NGINX configuration, and what should the reader do with this information?
What should the user do if Certbot seems unable to modify the Apache or NGINX configuration correctly?

TIA @SwartzCr @schoen

**Comment by SwartzCr** [comment]
1) You cannot manually use tls-sni-01 since it requires certbot to send a specific certificate response to a port 443 request, as opposed to just serving a file.
2) We assume that you have a working apache or nginx config. Which means the reader should check the validity of their config before using certbot (if they have made a new one and haven't been already using it to host a webserver). I don't think we assume much else. Previously we assumed that all vhost blocks were in separate files, but now we support more than one vhost per file.
3) The user should use certonly and manually install the certificate - there's lots of information on how to do that online so it shouldn't be too hard. Luckily installation only needs to happen once, and renewal will work even if the initial installation failed (as long as they manually add it to their config files)

**Comment by bmw** [comment]
I think this was fixed in #4948.
