### ISSUE TITLE
certbot-auto -q prints messages on upgrade

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#4163]
This may be "working as intended," or "too much hassle to fix, since it would involve overlapping arg parsers," but I figured I'd post for discussion:

I have a cron job that runs `certbot-auto -q renew`. Normally it produces no output, but on the most recent run, it printed (and therefore emailed me):

```
Upgrading certbot-auto 0.10.2 to 0.11.0...
Replacing certbot-auto...
Creating virtual environment...
Installing Python packages...
Installation succeeded.
```

Expected results: No output on self-upgrade when `-q` is present.

**Comment by jsha** [comment]
Oops, just caught up with the release notes and I see this is fixed in the latest release. Thanks!

**Comment by bmw** [comment]
This output is actually still printed (and you'll probably get e-mail about updating to 0.11.1 if you haven't already). In the latest release, we just silenced output from your OS package manager which should only happen when Certbot first runs.

This should be pretty easy to fix though. Basically we just have to make sure that all `echo` statements that aren't errors are only printed if `-q/--quiet` isn't provided.

**Comment by jsha** [comment]
I think this is fixed now; is that right?

**Comment by bmw** [comment]
Yep! Thanks for catching this.
