### ISSUE TITLE
Incorrect validation ... first certificate had names "uvw.xy"

### ISSUE THREAD

**Issue by yt42** [certbot/certbot#4169]
Hello, 

I have an Apache installation on Ubuntu Trusty with a previous certificate made with openssl. That worked fine. Because there are now a few websites on the host, I did tried to remove openssl and installed certbot, but can't obtain an vaild certificate with certbot --apache.
I did restarted apache services, the command certbot --apache ends up with
this error message, repeating for each domain (virtual host) on this IP.

>   Detail: Incorrect validation certificate for TLS-SNI-01 challenge.
>    Requested
>    [123#.123#].acme.invalid from [IP Number]:443. Received 1 certificate(s), first
>    certificate had names "[domain.name]"

I've searched the web for this Error message, to find someone with same problem, but with no luck. 

If anyone has an Idea on how to fix without reinstall from scratch, it would be a great help for me.
Meanwhile my search will go on, and of course I'll leave my solution here if I find one by myself.

**Comment by bmw** [comment]
This looks like a bug. The problem here is Certbot failed to configure Apache to pass the domain validation challenges required by Let's Encrypt. Can you provide a full log of the issue (which is stored in `/var/log/letsencrypt` by default) and the file containing the Apache `VirtualHost` you're trying to enable HTTPS on? Feel free to redact values like e-mail/IP addresses and domain names as you feel appropriate.

In the meantime, you can try to workaround the problem if Apache is serving files out of a directory for the requested domain (rather than serving as a proxy for example). To do this, change your command line to `certbot --authenticator webroot --installer apache`.

**Comment by thoj** [comment]
I actually have the same issue. Se attached log. IP and domains are replaced. 
[letsencrypt.txt](https://github.com/certbot/certbot/files/757479/letsencrypt.txt)

**Comment by thoj** [comment]
It works with webroot.

**Comment by yt42** [comment]
Hi, thank you for your suggestion and help. 
I made a few attempts with "certbot-auto --authenticator webroot --installer apache" but resolving a new Error Message. This is the output:

```
  Domain: www.example.de
   Type:   unauthorized
   Detail: Invalid response from
   http://www.example.de/.well-known/acme-challenge/[#1234]:
   "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
   <html><head>
   <title>403 Forbidden</title>
   </head><body>
   <h1>Forbidden</h1>
   <p"

```
This repeats for each of the four Domains. 
Webroot is in 
/var/www/html/

domains are in 
/var/www/html/example.de/
/var/www/html/example1.de/
/var/www/html/example2.de/

afaik, apache has no problems to serve hidden directorys by default and well, I can't remember that I've changed this, so the request should be served. But maybe it is a permission problem?
I can see the .well-known directory, but it is empty and of course not written by the user, which files are accessible from the web.

Following is a part of the full log - replaced domain to [example.de], ip to [ip127], crunshed challenges and token to [#1234].

```
[2017-02-07 13:34:46,903:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/acme/authz/#1234.
2017-02-07 13:34:47,098:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "GET /acme/authz/[#1234] HTTP/1.1" 200 1444
2017-02-07 13:34:47,099:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Content-Type: application/json
Content-Length: 1444
Boulder-Request-Id: [#1234]
Link: <https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"
Replay-Nonce: [#1234]
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Tue, 07 Feb 2017 13:34:47 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Tue, 07 Feb 2017 13:34:47 GMT
Connection: keep-alive

{
  "identifier": {
    "type": "dns",
    "value": "www.[example.de]"
  },
  "status": "valid",
  "expires": "2017-04-08T13:32:55Z",
  "challenges": [
    {
      "type": "dns-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/[#1234]/[#1234]",
      "token": "[#1234]"
    },
    {
      "type": "http-01",
      "status": "valid",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/[#1234]/[#1234]",
      "token": "[#1234]",
      "keyAuthorization": "[#1234].[#1234]",
      "validationRecord": [
        {
          "url": "http://www.[example.de]/.well-known/acme-challenge/[#1234]",
          "hostname": "www.[example.de]",
          "port": "80",
          "addressesResolved": [
            "[ip127]"
          ],
          "addressUsed": "[ip127]"
        }
      ]
    },
    {
      "type": "tls-sni-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/[#1234]/[#1234]",
      "token": "[#1234]"
    }
  ],
  "combinations": [
    [
      1
    ],
    [
      2
    ],
    [
      0
    ]
  ]
}
      0
    ]
  ]
}
```

**Comment by bmw** [comment]
@thoj, can you also provide a copy of the file containing the `VirtualHost` you're trying to enable HTTPS on?

@yt42, you can test if Apache is properly serving files in the hidden directory. Create the directory `.well-known/acme-challenge/` in the directory Apache is serving files out of for the domain you're trying to enable HTTPS on. In this directory create a file, with no extension, containing arbitrary text. After doing this, can you access this file in your browser?

**Comment by thoj** [comment]
Here they are:

```
<VirtualHost *>
DocumentRoot "/var/www/html/subdomain.myvailddomain.xyz/"
ServerName subdomain.myvailddomain.xyz
<Directory "/var/www/html/subdomain.myvailddomain.xyz/">
allow from all
Options None
Require all granted
</Directory>
</VirtualHost>

<VirtualHost _default_>
DocumentRoot /var/www/html/myvaliddomain.xyz/
<Directory "/var/www/html/myvaliddomain.xyz/">
allow from all
Options None
Require all granted
</Directory>
ServerName myvaliddomain.xyz
</VirtualHost>
```

**Comment by bmw** [comment]
Thanks @thoj. I think the problem you're having is an instance of #3981.

**Comment by thoj** [comment]
Ah. Makes sense. This config was generated by webmin. But great to know! :)

**Comment by mmccoy** [comment]
I believe I'm having the same issue -- I have other Vhosts on the same server which certbot has happily configured and renewed.. I'm a little stumped.

Here's the Vhost config:
```
<VirtualHost *:80>
  ServerName    domain-a.com
  ServerAlias   www.domain-a.com
  DocumentRoot  /var/www/static/www.domain-a.com
  ErrorLog      ${APACHE_LOG_DIR}/www.domain-a.com/error.log
  CustomLog     ${APACHE_LOG_DIR}/www.domain-a.com/access.log combined
</VirtualHost>
```

Dead simple vhost config, but it fails with the following:

```
$ ./certbot-auto -d domain-a.com -d www.domain-a.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Obtaining a new certificate
Performing the following challenges:
tls-sni-01 challenge for domain-a.com
tls-sni-01 challenge for www.domain-a.com
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. domain-a.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for TLS-SNI-01 challenge. Requested d9c174f2169eeff6fbde2ca12824eb8e.fd43550f8436fda5d706778fa650e055.acme.invalid from 206.71.169.211:443. Received 2 certificate(s), first certificate had names "domain-b.com", www.domain-a.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for TLS-SNI-01 challenge. Requested 3b1b837a81819075680ecb0d7edcd260.800df112c271d6b1197dc2811d420e6c.acme.invalid from 206.71.169.211:443. Received 2 certificate(s), first certificate had names "domain-b.com"

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: domain-a.com
   Type:   unauthorized
   Detail: Incorrect validation certificate for TLS-SNI-01 challenge.
   Requested
   d9c174f2169eeff6fbde2ca12824eb8e.fd43550f8436fda5d706778fa650e055.acme.invalid
   from 206.71.169.211:443. Received 2 certificate(s), first
   certificate had names "domain-b.com"

   Domain: www.domain-a.com
   Type:   unauthorized
   Detail: Incorrect validation certificate for TLS-SNI-01 challenge.
   Requested
   3b1b837a81819075680ecb0d7edcd260.800df112c271d6b1197dc2811d420e6c.acme.invalid
   from 206.71.169.211:443. Received 2 certificate(s), first
   certificate had names "domain-b.com"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.
```

You'll notice in that outbut the reference to 'domain-b.com' being on the certificate.  That domain is the default domain/vhost on the server, and it is serving https traffic successfully (as configured by certbot).

DNS zones for both domains are effectively identical.  I have no idea why domain-a is failing certbot authorization.

Certbot log is attached.

Please let me know if I can provide any other details.
[letsencrypt-log.txt](https://github.com/certbot/certbot/files/765434/letsencrypt-log.txt)

**Comment by bmw** [comment]
@mmccoy, thanks for all the info. In your case, it looks like the vhost Certbot creates to solve the challenge conflicts with or is being overwritten by the `domain-b.com` HTTPS vhost. Can you provide a copy of this vhost as well?

Also, are either `domain-a.com` or `domain-b.com` vhosts in the same file as other vhosts?

**Comment by yt42** [comment]
> @yt42, you can test if Apache is properly serving files in the hidden directory. Create the directory .well-known/acme-challenge/ in the directory Apache is serving files out of for the domain you're trying to enable HTTPS on. In this directory create a file, with no extension, containing arbitrary text. After doing this, can you access this file in your browser?

thanks for your answer, sorry for answering that late - personal problems in the past ... 

yes I can create those, .well-known is automatically created from certbot-auto but was empty.
Then I created .well-known/acme-challenge/test and made it accessable by modifying .httaccess so it could be seen from the web.

Using certbot 0.13.0 on Ubuntu 14.04.5 LTS

`./certbot-auto certonly --no-self-upgrade --webroot -d domain-name --webroot-path /var/www/html/`

Ending with:

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for domain-name
Using the webroot path /var/www/html for all unmatched domains.
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. domain-name (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://domain-name/.well-known/acme-challenge/ExlTc17uVXIGZbSvv8dAjzemxtASRWZImqUW61BJ_T8: "<!DOCTYPE html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" href="h"

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: yours-truly.de
   Type:   unauthorized
   Detail: Invalid response from
   http://domain-name/.well-known/acme-challenge/ExlTc17uVXIGZbSvv8dAjzemxtASRWZImqUW61BJ_T8:
   "<!DOCTYPE html>
   <head>
     <meta http-equiv="Content-Type" content="text/html;
   charset=utf-8" />
   <link rel="shortcut icon" href="h"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.
```
-------

Meanwhile, everything is running fine, with an old, outdated, certificate ...

**Comment by polarapfel** [comment]
@bmw Does the webroot based authentication also work with renew? Running certbot renew fails for me with the same issue. Thanks!

**Comment by SwartzCr** [comment]
@polarapfel yes you can use webroot with renewal - if you have any more questions please feel free to open new issues, so that we can make sure they get responded to promptly

**Comment by SwartzCr** [comment]
@yt42 are you still having issues?

**Comment by SwartzCr** [comment]
I am going to close this issue as stale, users who are still experiencing issues should open new ones so that we can properly address them
