### ISSUE TITLE
Make sure IMPORTANT NOTES do not obscure error output

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#4170]
I recently tried to issue on a new host, and provided a hostname for which there was no VirtualHost. However, Certbot led me through the whole account creation process first. Not a big deal in general, but the problem is that, if account creation happens, Certbot will print the "IMPORTANT NOTES" section after running to completion. This obscures the more important "Cannot find a VirtualHost" error. It would probably be better to check for ability to perform the challenges before attempting registration.

```
./certbot-auto -d blocktogether.org -d www.blocktogether.org -w /data/blocktogether/current/static/ --nginx

... prompt for email address etc ...

Performing the following challenges:
tls-sni-01 challenge for blocktogether.org
tls-sni-01 challenge for www.blocktogether.org
Cleaning up challenges
Cannot find a VirtualHost matching domain www.blocktogether.org.

IMPORTANT NOTES:
 - If you lose your account credentials, you can recover through
   e-mails sent to XXXXXXX.
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
```

**Comment by bmw** [comment]
I agree this output should be improved, but I'd like to generalize the problem a bit so Certbot can provide better output in more cases. The general problem is if Certbot crashes with a fatal error, that error may be obscured by "IMPORTANT NOTES:" output.

A few potential options in my order of preference:

1. Include the error as a section in "IMPORTANT NOTES:".
2. Add a note mentioning that an error occurred and more information can be found above "IMPORTANT NOTES:".
3. Print the error after "IMPORTANT NOTES:", but not as an indented/formatted section.

One thing to keep in mind about doing a more general approach is we already include error output in "IMPORTANT NOTES:" if the ACME server reports that we failed a challenge. We want to make sure this still looks reasonable after resolving this issue.

**Comment by bmw** [comment]
I think this issue is largely captured in our UI redesign which proposes removing the important notes section entirely. That project is currently on hold though and I think this issue is a good idea, so I think it's probably worth keeping this open to make sure we do something here.

**Comment by jsha** [comment]
I think it's okay to consider this covered by the overall UI redesign project. Closing.
