### ISSUE TITLE
Update plugin documentation

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#4171]
https://certbot.eff.org/docs/contributing.html#authenticators describes a category of ContinuityChallenge that doesn't exist anymore; also it mentions ApacheConfigurator and StandaloneAuthenticator but not Nginx.

**Comment by SwartzCr** [comment]
@zjs expressed interest in writing up some documentation on how to create a plugin - maybe he's also be interested in cleaning it up?

**Comment by jsha** [comment]
I landed a fix for this: https://github.com/certbot/certbot/pull/4329
