### ISSUE TITLE
acme: Change public interfaces to receive / give PEM instead of OpenSSL types

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#4177]
Per https://github.com/pyca/pyopenssl/issues/291, the `cryptography` package probably covers all the things we need from pyOpenSSL, meaning we could in theory drop the depedency. One particular stumbling block: the `acme` library has public interfaces that take OpenSSL, in particular `CertificateRequest`, `CertificateResource`, `Revocation`, `request_issuance`, `poll_and_request_issuance`, `fetch_chain`, and `revoke`.

We should probably take a major semver change to turn these all into giving/receiving PEM, so the `acme` library can be agnostic of whether people are using `pyOpenSSL`, `cryptography`, or something else.

**Comment by jsha** [comment]
This doesn't seem like a high priority for anyone - AFAIK there aren't many clients other than Certbot using the acme library, and if they are they seem to be okay with the current pyOpenSSL interfaces.

**Comment by plinss** [comment]
I wouldn't call it a high priority as the existing code works, but the conflation of pyOpenSSL and cryptography apis was a bit of a burden for writing [acmebot](/plinss/acmebot) (especially as pyOpenSSL was lacking some necessary features last time I looked).

I don't have the bandwidth at the moment, but I might be willing to submit a PR to remove the pyOpenSSL dependency from the acme library at some point in the future if that would be welcome.
