### ISSUE TITLE
Apache lowercase h isn't accepted <VirtualHost> works <Virtualhost> doesn't

### ISSUE THREAD

**Issue by kublermdk** [certbot/certbot#4183]
### The version of Certbot you're running :
I'm using certbot **v0.11.1**

### The operating system you're running it on:
**Ubuntu 14.04.5 LTS**

### The commands you ran
./certbot-auto

### What you expected to happen
I expected to be able to see my sites listed

> Which names would you like to activate HTTPS for?
> -------------------------------------------------------------------------------
> 1: fendamenda.com.au
> 2: www.fendamenda.com.au
> 3: fendamenda.com
> 4: www.fendamenda.com
> 5: staging.fendamenda.com.au
> -------------------------------------------------------------------------------

### What actually happened

> Which names would you like to activate HTTPS for?
> -------------------------------------------------------------------------------
> 1: staging.fendamenda.com.au
> -------------------------------------------------------------------------------

certbot didn't understand the sites which used `<Virtualhost> ... </Virtualhost>` although Apache accepted them fine. When capitalising the h and using `<VirtualHost> ... <VirtualHost>` it worked and picked up the other site configs.

I've posted an example virtualhost entry and basic info at http://www.kublermdk.com/2017/02/08/letsencrypt-certbot-virtualhost-vs-virtualhost/

**Comment by bmw** [comment]
@joohoi, was this a regression or something we never supported properly?

**Comment by joohoi** [comment]
Regression introduced in commit 0aed0e90f1a1a8e0ca67b83e7187ac44966b593e
