### ISSUE TITLE
macOS BootstrapMac fails to install pip and virtualenv due to permission error

### ISSUE THREAD

**Issue by MichalMMac** [certbot/certbot#4189]
When running `letsencrypt-auto --help --debug` `BootstrapMac` function attempts to install `pip` and `virtualenv` with this code:

```
curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py |  python
pip install virtualenv
```
Since `/Library/Python/2.7/site-packages/` is owned by `root` with 755 permissions installation fails with permission error.

One way to "fix" it is to chmod -R 777  site-packages packages directory as described in this blog [post](https://community.letsencrypt.org/t/complete-guide-to-install-ssl-certificate-on-your-os-x-server-hosted-website/15005).

Another way is to add $SUDO to install commands:

```
curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py |  $SUDO python
$SUDO pip install virtualenv
```

This appears to work (tested on Sierra 10.12.3 with both MacPorts and HomeBrew).

**Comment by SwartzCr** [comment]
@bmw who works on mac PRs? This also seems pretty simple to handle - want to assign someone?

**Comment by bmw** [comment]
@SwartzCr, no one regularly does, but @MichalMMac showed up with a PR.

**Comment by MichalMMac** [comment]
@bmw With this PR it would be better if `BootstrapMac` original author could take a look at this change. There may be some assumptions about runinng stuff with/without root with relation to Python.

**Comment by bmw** [comment]
Closing for the reason described [here](https://github.com/certbot/certbot/pull/4190#issuecomment-294998771).
