### ISSUE TITLE
How to disable forced redirect to https previously selected?

### ISSUE THREAD

**Issue by twinpigs** [certbot/certbot#4198]
I need prepare my content better before switch to permanent https.

How to stop permanent redirect from http to https for my site? Or completely remove https setup for a while? And how to enable it back when i'll be ready?

**Comment by SwartzCr** [comment]
great question!
@twinpigs can you give us some more information about the system you're running this on? What OS is it? What are you using for server management? (apache? nginx?) What command did you run with Certbot? I'm happy to help instruct if you can give me a little more info :D

**Comment by twinpigs** [comment]
Thank you. It was Ubuntu 14.04 with Apache. Command I run was mostly:
`certbot-auto --apache -d domen.com -d www.domen.com`

**Comment by twinpigs** [comment]
I think it was my Wordpress config. Seems working now.

**Comment by SwartzCr** [comment]
glad to hear it - feel free to open new issues if more problems come up!

**Comment by JO-WTF** [comment]
@SwartzCr Hi, Sorry but I think the question was not answered...

I also chose force direction by mistake but don't know how to disable it.

Thanks.

**Comment by twinpigs** [comment]
Try to repeat whole procedure, but choose right answer this time.

**Comment by TJH43** [comment]
i have the same issue.  

I tried "certbot --reinstall --no-redirect." That did not seem to work.  the HTTPS required/optional question did not get asked.  My .conf files appear to be unchanged after an Apache restart.  The 443 vhost file options-ssl-apache.conf still contains "SSLOptions +StrictRequire" and the "anyPort" vhost mydomain.conf file still has "RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]".  

Is there a way to do this without going through the ertbot install process ... and without manually editing the .conf files?

This seems like it would be a common mistake.  

I have Ubuntu 14.04 and Apache 2.4.7

Thanks

**Comment by SwartzCr** [comment]
@TJH43 we're going to add a #managedbycertbot comment into apache configs (which is being tracked in #4526) which should help with manual removal of misadded flags.
You should also be able to rollback the changes to your configuration using the rollback command (look here for more info: https://certbot.eff.org/docs/using.html#certbot-command-line-options) and then run it again without choosing that option.
Does that make sense? Let me know if that doesn't solve what you want

**Comment by Crewchief85** [comment]
If anyone else has this problem in the future.  I just ran the command 'certbot' from the terminal.  Then I selected the site I wanted to edit and it gave me the choice of whether or not to require https again.

**Comment by remaindeer** [comment]
I think that running certbot again and not choosing "require https" doesn't work because it doesn't overwrite the necessary files. How I solved it was by editing my Virtual Host file (replace "mydomain.com" with your own correct file location):
`$ sudo vim /etc/apache2/sites-available/mydomain.com.conf` 

In that file that I deleted the following lines:
`RewriteEngine on`
`RewriteCond %{SERVER_NAME} =mydomain.com`
`RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]`
