### ISSUE TITLE
Overwrite Existing Certificates Not-Tracked by Certbot on Successful Generation

### ISSUE THREAD

**Issue by own3mall** [certbot/certbot#4203]
Is there a way to force Certbot to overwrite existing SSL certificates (that were not originally generated or tracked by Certbot) upon successful verification?

I'm trying to integrate Let's Encrypt into the Easy Hosting Control Panel (http://ehcpforce.tk).  

Currently, the panel creates symlinks in the directories used by Certbot to the server's generic SSL certificate before making a certbot certificate request.  These symlinks will be used as a fallback in the nginx or apache2 template for the domain in-case anything goes wrong with the certbot certificate generation.  In this way, a security certificate will always exist and nginx won't crash complaining that one doesn't exist if certbot's process fails.    

When I use the following command:
```
/usr/local/bin/certbot certonly --quiet --webroot --agree-tos --email myemail@weeee.com -d domain.com -d www.domain.com -w /var/www/vhosts/{RESTOFPATH}
```
Certbot sees that a folder exists in /etc/letsencrypt/live/domain.com, so instead of deleting the symlinks in that folder that point to a generic (invalid and self signed) certificate that I manually configured before certbot's run, it creates a new folder /etc/letsencrypt/live/domain.com-0001

Any chance it can overwrite what is in /etc/letsencrypt/live/domain.com

I do this because the control panel works by building a template file.  Subdomains and domains may not be added to the master template until the run is over.  As such, I want to run all certbot requests post template generation and an nginx reload or apache2 reload.  The templates will find a certificate no matter what the result of certbot is.  

I suppose I could script this myself, but it would be nice to have the option to overwrite what is there.

**Comment by sc-perth** [comment]
Consider the [--post-hook](https://certbot.eff.org/docs/using.html#certbot-command-line-options) option.

**Comment by SwartzCr** [comment]
I don't know if we'd want to officially support this - I kind of think this is the point of having the script plug-in (to allow you to manage this)
But if @bmw or @ohemorange wants to chime in and contradict me I'd be happy for them to put it into an upcoming milestone

**Comment by ohemorange** [comment]
Using `--post-hook` could work. You could also try running certbot then adding in the other backup certs. I agree that we probably don't want to support this in the main codebase.

**Comment by SwartzCr** [comment]
I believe that this is now fixed via --expand. Additionally it seems that we wouldn't want to support a specific fix for this, so I am closing the issue.
