### ISSUE TITLE
Several sites on one IP can't obtain certs

### ISSUE THREAD

**Issue by twinpigs** [certbot/certbot#4205]
Previously I had successfully obtained certificate for one of my sites. Now I have to add certs to another three sites (they all are virtual hosts sharing single IP with first site, but each of them have it's own DNS records). But I get error:

> Failed authorization procedure. **mynewsite.com** (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for TLS-SNI-01 challenge. Requested f544c91aa78c8e3185d89b0647f460cc.8e9c2579c00173d8f366c31d3ca1d230.acme.invalid from 78.47.232.162:443. Received 2 certificate(s), first certificate had names "**myfirstsite.com**", 

For each of three sites with their's names at start and one "first site" names at end (where "first certificate had names" is).

What should I do? (Ubuntu 14.04, Apache)

**Comment by vcenturion** [comment]
I have the same problem (Ubuntu 16.10, Apache)

Domain: test2.*****.com.py
   Type:   unauthorized
   Detail: Incorrect validation certificate for TLS-SNI-01 challenge.
   Requested
   cce5e494f88c175984163454e2c58467.a5ea114acc9ed328b60621515700139b.acme.invalid
   from 130.211.202.42:443. Received 2 certificate(s), first
   certificate had names "test.api.***.com.py"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.


test2.*****.com.py  -> IP1
test.api.***.com.py  -> IP2

**Comment by SwartzCr** [comment]
is there a reason you're using the DNS test instead of one of the other verification methods?

**Comment by twinpigs** [comment]
This reason is "I dot know how to use other methods and I did'n know I should to" :)

**Comment by twinpigs** [comment]
Now I know the answer:
1. it's not DNS but it is TLS-SNI-01 challenge 
2. "Apache" plugin does not support other challenges.

**Comment by twinpigs** [comment]
I fixed this with set all my virtual hosts port 80 instead of *.
[https://community.letsencrypt.org/t/several-sites-on-one-ip-cant-obtain-certs/28262/3](url)
