### ISSUE TITLE
(http-01): urn:acme:error:connection ::

### ISSUE THREAD

**Issue by grvlle** [certbot/certbot#4206]
The setup: Got a virtual machine running Ubuntu 16.04. On that virtual machine I'm also running a VPN service and nginx webserver. I'm also using a bridged adapter.

I'm able to access the webserver from my domain name on the internet and locally on the VM IP.

The problem: I am now trying to use Let's Encrypt and certbot in order to create an SSL certificate. But it fails claiming it cannot reach the webserver using the domain name. No can I ping the domain name from the guest either, nor the public IP mapped to the domain name from the VM guest. I can ping it from the Windows host however.

`sudo letsencrypt certonly -a webroot --webroot-path=/var/www/html -d domain.se -d srv01.domain.se Failed authorization procedure. domain.se (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Could not connect to domain.se, srv01.domain.se (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Could not connect to srv01.domain.se
`

Let me know if you need more information I'd be glad to provide logs or any other information if necessary.

**Comment by grvlle** [comment]
Update: Oops, the site isn't accessible from the internet apparently. Only locally. Will continue troubleshooting.

**Comment by SwartzCr** [comment]
Okay! I'm going to close this ticket for now - but feel free to re-open it if/when you have more questions. Also logs are always useful, so include them if you can!
