### ISSUE TITLE
certbot and cron not quiet in the logs 

### ISSUE THREAD

**Issue by saintger** [certbot/certbot#4210]
Hello,
Working on Debian Jessie with certbot 0.9.3-1~bpo8+2, I noticed that certbot is no longer quiet when it is launched every 12h through CRON:
Feb 10 00:00:01 systemd[1]: Starting Certbot...
Feb 10 00:41:37 systemd[1]: Started Certbot.
Feb 10 12:00:01 systemd[1]: Starting Certbot...
Feb 10 12:29:38 systemd[1]: Started Certbot.

The relevant line in cron is:
`0 */12 * * * root test -x /usr/bin/certbot -a \! -d /run/systemd/system && perl -e 'sleep int(rand(3600))' && certbot -q renew`

How can I instruct certbot not to log these ?

Thanks

**Comment by hlieberman** [comment]
This is actually not a problem with cron, but rather with the systemd timer shipped in the certbot package.  Can you please email debian-backports@lists.debian.org and report this bug there?  I'm on vacation this weekend, but I can look at it when I get back if one of my teammates doesn't take care of it before then.

**Comment by saintger** [comment]
Ok it's done here:
https://lists.debian.org/debian-backports/2017/02/msg00028.html
