### ISSUE TITLE
Plugin renewalparams not saved in renewal config files

### ISSUE THREAD

**Issue by code-tree** [certbot/certbot#4219]
I'm using the s3front plugin and I set various args via the commandline (e.g. --certbot-s3front:auth-s3-bucket). However, these args are not saved in the renewal config file. So when certbot detects the cert needs renewing it fails as no args for the plugin were given.

Any ideas why this is?

(using 0.11.1)

**Comment by code-tree** [comment]
Example of args saved in a renewal file:

```
[renewalparams]
installer = certbot-s3front:installer
config_dir = ...
authenticator = certbot-s3front:auth
account = ...
logs_dir = ...
```

**Comment by SwartzCr** [comment]
@bmw any idea how we should be handling this?

**Comment by bmw** [comment]
We should be saving these values not dropping them.

Thanks for reporting the bug @code-tree. I've reproduced it and am working on a fix now.

**Comment by bmw** [comment]
I didn't see this in time to get a patch ready for this release, but our fix will be included in our release next month. In the meantime, you can set these values in a [configuration file](https://certbot.eff.org/docs/using.html#configuration-file) and they'll automatically be picked up when running Certbot (including `certbot renew`).
