### ISSUE TITLE
Incorrect validation certificate

### ISSUE THREAD

**Issue by anthonywoodley** [certbot/certbot#4220]
Hi There,
New to Cerbot. Can you give me an hand with an error on my new mail server?. 

It an Cento 6.8/apache environment without a www site conf.

So the server will be, dedicated for my email accounts.

This is the error:

./certbot-auto
/root/.local/share/letsencrypt/lib/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
Saving debug log to /var/log/letsencrypt/letsencrypt.log
No names were found in your configuration files. Please enter in your domain
name(s) (comma and/or space separated)  (Enter 'c' to cancel):#######.co.uk
Obtaining a new certificate
Performing the following challenges:
tls-sni-01 challenge for ########.co.uk

We were unable to find a vhost with a ServerName or Address of #.co.uk.
Which virtual host would you like to choose?
(note: conf files with multiple vhosts are not yet supported)
-------------------------------------------------------------------------------
1: ssl.conf                       |                       | HTTPS | Enabled
-------------------------------------------------------------------------------
Press 1 [enter] to confirm the selection (press 'c' to cancel): 1
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. ########.co.uk (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for TLS-SNI-01 challenge. Requested 1e906bda3e19062d613b2fcc5b468f4d.73b43dc269b888a7361ac2278b3814d1.acme.invalid from 66.96.162.142:443. Received 3 certificate(s), first certificate had names "*.domain.com, domain.com"

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: ########.co.uk
   Type:   unauthorized
   Detail: Incorrect validation certificate for TLS-SNI-01 challenge.
   Requested
   1e906bda3e19062d613b2fcc5b468f4d.73b43dc269b888a7361ac2278b3814d1.acme.invalid
   from 66.96.162.142:443. Received 3 certificate(s), first
   certificate had names "*.domain.com, domain.com"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.

Let me know your thoughts.

**Comment by SwartzCr** [comment]
would you be able to post the contents of the ssl.conf file that you're using?

**Comment by anthonywoodley** [comment]
Hi Swartz, Sorry for the delay. File attached.
[ssl.conf.zip](https://github.com/certbot/certbot/files/777338/ssl.conf.zip)

**Comment by SwartzCr** [comment]
@anthonywoodly Ah thanks for attaching that.
I'm a bit confused because that ssl.conf file doesn't specify a ServerName anywhere in it. What's possibly happening is that Certbot is generating a more specific ssl vhost and when the ACME server tries to access it this ssl.conf file takes precedence (since it's overly broad) and prevents the ACME server from getting the response it expects.
My guess is that if you specify a domain for this vhost - then it should work. Though I could be wrong, @bmw wanna check my logic?

**Comment by anthonywoodley** [comment]
Hi there, this server is for mail only and the the A record www is pointing somewhere else?,  coulc that play a part in this?

**Comment by bmw** [comment]
@SwartzCr, I don't think that's the problem. When we create the challenge vhost and add the `ServerName` directive for the challenge, that vhost should now take precedence over the vhost in `ssl.conf`.

@anthonywoodley yes that'd definitely be a problem. Let's Encrypt is trying to connect to your server to verify your domain. If you're unable to run Certbot on the server pointed at by the domain, you can try the [manual plugin](https://certbot.eff.org/docs/using.html#manual) although using it is somewhat tedious.

**Comment by walttheboss** [comment]
I have this problem and may be related.  I have one server currently running certbot fine.  I am building a new server at the same WAN but different LAN address.  Running server is at .13.  New server at .14  When I run sudo certbot-auto --apache -d msgkmg.com -d www.msgkmg.com

It always fails with:

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: www.msgkmg.com
   Type:   unauthorized
   Detail: Incorrect validation certificate for tls-sni-01 challenge.
   Requested
   fe0590540c4bcd860d78f8b33567e468.42396efa9f010f0d06aece98c3435185.acme.invalid
   from 182.242.56.104:443. Received 1 certificate(s), first
   certificate had names "msgkmg.com, www.msgkmg.com"

   Domain: msgkmg.com
   Type:   unauthorized
   Detail: Incorrect validation certificate for tls-sni-01 challenge.
   Requested
   31fe2f3c31cd20735704893504fb7d3c.0575a278ce6bf72721b341730da933f6.acme.invalid
   from 182.242.56.104:443. Received 1 certificate(s), first
   certificate had names "msgkmg.com, www.msgkmg.com"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.

**Comment by SwartzCr** [comment]
@anthonywoodley have you managed to get a certificate?

**Comment by SwartzCr** [comment]
It seems that in both cases you are attempting to get a certificated for a domain that is not hosted on the webserver.
You can try to use the `webroot` challenge, but it will likely require manually copying the challenge information to the other server.
Additionally we do not yet support mail server authentication, but we're working on adding that separately.
I am going to close this issue - but feel free to open new ones if you are still unable to find a way to get a certificate.
Also keep an eye on our posfix plugin if you require mailserver certs.
