### ISSUE TITLE
certbot on ubuntu 12.04 ?

### ISSUE THREAD

**Issue by phil123456** [certbot/certbot#4222]
hello,

(I did not know were to ask,so I came here) 

I found out there were no instruction to install certbot on ubuntu 12.04
does this meant it is not compatible ?

we have an old system and migration/upgrades are not possible becos of some php applications, but I was interested in installing certbot on that machine

thanks

**Comment by SwartzCr** [comment]
Hi @phil123456 !
I think this generally falls under the 'Ubuntu (other)' selection on certbot.eff.org, you can read the appropriate instructions here: https://certbot.eff.org/#ubuntuother-other
They should tell you how to use certbot-auto to get a working version of certbot up and running on your machine.
I'm going to close this issue, but feel free to re-open it if that doesn't work, or to open a new one if you run into any other problems!
(and sorry for the slow reply, last week was hectic)
