### ISSUE TITLE
Certbot fails to bind on port 443 when there is no deafult Listen

### ISSUE THREAD

**Issue by met67** [certbot/certbot#4223]
I was trying to install a Let's encrypt certificate on a site which is hosted on Apache in a RedHat Enterprise Linux 6.8.
The server hosts several sites, each one with its IP, and Apache doesn't listen on port 80 or 443 by default.
Each site has its file in conf.d directory, which defines the Virtual Host and Listen on the right port:

*site.conf*

    Listen w.x.y.z.:80
    NameVirtualHost w.x.y.z:80
    <VirtualHost w.x.y.z.:80>
    ...
    </VirtualHost>

In this situation, the first run of certbot didn't modify the configuration to listen on port 443, so the verification failed.
Moreover, since certbot stores the challenge configuration file in conf.d, with RedHat standard file structure this is included twice, one in `Include conf.d/*.conf` in the middle of httpd.conf and the second in `Include /etc/httpd/conf.d/le_tls_sni_01_cert_challenge.conf` at the end as a result of certbot's modifications.

**Comment by SwartzCr** [comment]
@joohoi any ideas on how we should be handling this?

**Comment by joohoi** [comment]
I'm going to take a better look on Listen statement writing as a part of work for enabling modules in non-debian based distributions, and I'm hoping to fix this case in the process.

**Comment by hogarthj** [comment]
On RHEL/CentOS Listen 443 is provided by ssl.conf which in turn comes from the mod_ssl package ...

**Comment by bmw** [comment]
@joohoi, is this still a valid issue?

**Comment by joohoi** [comment]
I think this should be fixed with the various fixes enabling challenges (and directive discovery / writing) has seen during the last few years. I'm closing this for now. If someone hits this again, we'll reopen the issue.
