### ISSUE TITLE
Invalid instruction - raspbian - raspi 1B+

### ISSUE THREAD

**Issue by black-snow** [certbot/certbot#4232]
Sadly https://github.com/certbot/certbot/issues/2673 was closed. This is pretty much a dupe.

As mentioned in the OP `import augeas` in the pythin repl yields and *invalid instruction* or *module not found*.

How can I use `certbot` on my raspi 1 --- will this be fixed (in jessie backports)?

Cheers

**Comment by SwartzCr** [comment]
@hlieberman any ideas?

**Comment by SwartzCr** [comment]
it looks like this has since been fixed for raspian, based on https://github.com/certbot/certbot/issues/2673#issuecomment-286276081
So I am going to close this issue
