### ISSUE TITLE
--cert-name option not honored on new SSL certificate issuance

### ISSUE THREAD

**Issue by nuxwin** [certbot/certbot#4233]
Hello,

```shell
root@stretch:~# certbot-auto --version
certbot 0.11.1
```
```shell
# certbot-auto \
certonly \
--non-interactive \
--agree-tos --email <email> \
--staging \
--webroot --webroot-path <path> \
--allow-subset-of-names \
--domain unresolvable.domain.tld \
--domain resolvable.domain.tld \
--cert-name unresolvable.domain.tld
```
Result in:
```shell
No certificate found with name unresolvable.domain.tld (expected /etc/letsencrypt/renewal/unresolvable.domain.tld.conf).
```
But help say (When creating a new certificate ...):
```
--cert-name CERTNAME  Certificate name to apply. Only one certificate name
                        can be used per Certbot run. To see certificate names,
                        run 'certbot certificates'. When creating a new
                        certificate, specifies the new certificate's name.
                        (default: None)
```

Thank you.

**Comment by bmw** [comment]
cc @ohemorange

**Comment by nuxwin** [comment]
Furthermore:

For us, it would be much appreciated to have the `--cert-name` command line option also working for new SSL certificate issuances, allowing us to specify lineage name. This is needed in our case because our plugin are as per lineage basis.

In the command above, even if there is a auth failure for the `unresolvable.domain.tld` domain, we want it as the lineage name. Our plugin use that lineage name for internal retrieval. Right now, it seem that the first SAN passed in to certbot (`--domain <SAN>`) is always used as lineage name but it would be more practicable to make this explicite using the `--cert-name` option as stated in its current description.

**Comment by ohemorange** [comment]
This is a regression caused by #4128. Looking into a solution.

**Comment by nuxwin** [comment]
@ohemorange 

Thank for taking this in consideration ;) That is much appreciated.

**Comment by sandrinr** [comment]
Since this is fixed in upstream it would be much appreciated if you could consider doing a patch release for that issue. I am guessing people doing automatic provisioning of Let's Encrypt certificates run into this, like we did.

**Comment by ohemorange** [comment]
We plan to release the next version of Certbot, which will include this fix, within the next day or so.
