### ISSUE TITLE
certbot certificates should support sorting by (validity period, certificate name, reverse-tld)

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#4238]
I'm not sure what the current sort order represents, but it's a bit odd

Being able to sort by validity is helpful for figuring out what's expiring soon.
Being able to sort by certificate name is helpful because it's an easier thing to understand than the random sort that's currently deployed.

fwiw, I currently have:
```
b.example.com (valid 58 days)
a.example.com (valid 89 days)
c.example.com (valid 58 days)
n.example.com (valid 58 days)
example.net (valid 63 days)
l.example.com (valid 58 days)
```

It clearly isn't sorted by name (b/a), by validity (58, 89, 58), nor tld.

Sorting by each of those could be useful.

Expected for validity:
```
a.example.com (valid 89 days)
example.net (valid 63 days)
b.example.com (valid 58 days)
c.example.com (valid 58 days)
n.example.com (valid 58 days)
l.example.com (valid 58 days)
```

Expected for certificate:
```
a.example.com (valid 89 days)
b.example.com (valid 58 days)
c.example.com (valid 58 days)
example.net (valid 63 days)
l.example.com (valid 58 days)
n.example.com (valid 58 days)
```

For tld, I think the algorithm should be:
sort by by each leaf, resorting by leafs to the right.

```
a.example.com (valid 89 days)
b.example.com (valid 58 days)
c.example.com (valid 58 days)
l.example.com (valid 58 days)
n.example.com (valid 58 days)
example.net (valid 63 days)
```

**Comment by SwartzCr** [comment]
@ohemorange any interest in taking this on? (or at least milestoning it?)

**Comment by ohemorange** [comment]
@pde might be interested

**Comment by SwartzCr** [comment]
Hey @jsoref we're going to try to accomplish this via #3909 which should allow you to pipe the JSON formatted output into any sort of sorting mechanism you'd like. I'm going to close this issue in favor of #3909, but let us know in that thread if there are reasons why it won't work for your use case.

**Comment by jsoref** [comment]
So... While someone (including me) could write something to do this (using a json api), it isn't reasonable to expect average people to do so.

**Comment by ohemorange** [comment]
Thanks for the perspective. We expect that sorting is an advanced use case, for people with large amounts of certificates or uncommon setups. In those cases, we can allow the greatest flexibility by giving people data in a machine-readable format and allowing them to transform it for their precise needs.
