### ISSUE TITLE
Distinguish renewer run from cron from renewer run interactively

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#424]
The renewer will probably normally run from `/etc/cron.daily` on most systems, and there is a config file option to inhibit this from doing anything. But if the renewer is run manually, it should probably be able to perform renewals and ignore that option (thus distinguishing "automated renewal" from "manual renewal").

One option for this is just to look at `sys.argv[0]` to see what name the renewer was run under, and tell packagers to call the symlink in `/etc/cron.daily` something other than the name of the manual renewer script.

Cc @pde (technically another aspect of CLI design, maybe?).

**Comment by kuba** [comment]
`sys.argv[0]` option seems really fragile... why not simply add a flag `--cron` that, if present, will make sure script respects the autorenew setting and otherwise ignore the autorenew setting?

**Comment by schoen** [comment]
I originally wanted to do that, but if files are put in `/etc/cron.daily` rather than into `/etc/crontab` (apparently a preferred packaging option on modern distributions), we don't get to control what arguments they're run with -- the `run-parts` script will just run each script with no arguments.

**Comment by kuba** [comment]
Solution: rather than directly symlinking `letsencrypt-renewer` in any of `cron.d`-like places, the package maintainer shall create an appropriate wrapper script.

**Comment by schoen** [comment]
OK, that makes sense.

**Comment by kuba** [comment]
I left a stub `# parser.add_argument("--cron"...` in #473.

**Comment by bmw** [comment]
`certbot renew` is always non-interactive now so this can be closed.
