### ISSUE TITLE
Generating certificate for subdomains inside ".space" zone

### ISSUE THREAD

**Issue by opiumfor** [certbot/certbot#4241]
I'm trying to generate certificate for any domain like this:

aaa.ukit.space
123.ukit.space
1b3.ukit.space

but always getting this error:

docker run --rm -ti --name certbot_ulanding1 -v $PWD/letsencrypt/etc:/etc/letsencrypt -v $PWD/letsencrypt/data:/var/lib/letsencrypt -v $PWD/letsencrypt/well-known:/well-known/.well-known quay.io/letsencrypt/letsencrypt:latest certonly --webroot -w / -d ulanding.ukit.space
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for ulanding.ukit.space
Using the webroot path / for all unmatched domains.
Waiting for verification...
Cleaning up challenges
**An unexpected error occurred:
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 268: ordinal not in range(128)**

**Comment by SwartzCr** [comment]
Weird!
Question 1: have you gotten it to work with other domains?
Question 2: what is the os of the docker container
Question 3: can you attach the certbot error log? it should be in `/var/log/letsencrypt`
\u2014 is an em dash http://www.fileformat.info/info/unicode/char//2014/index.htm so I'm curious if some file has the a non-ascii character in it for some odd reason

**Comment by SwartzCr** [comment]
@opiumfor any chance you're also using Docker? It looks like the issue with #4273 was due to docker weirdness (as documented here: https://meta.discourse.org/t/advanced-troubleshooting-with-docker/15927)

**Comment by opiumfor** [comment]
Sorry, It was just my misconfigured nginx, it didn't served the challenge file. And the "strange error" was because of my "fancy" error page, which looks like this https://ukit.com/gimme404dude (localization may differ depending on your browser accept-language, in my case it was russian). That's it. Sorry again for disturbance.

**Comment by SwartzCr** [comment]
no worries, I'm going to close this as duplicate then
