### ISSUE TITLE
Add sanity checks for recent regressions in the integration test

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#4246]

**Comment by ohemorange** [comment]
There's a nice list of these in #4053.

**Comment by ohemorange** [comment]
And commit 17641ee6ed3d805ba6c2ea1456886932a9650326 gets boulder working.

**Comment by SwartzCr** [comment]
@ohemorange wanna put this in a milestone?

**Comment by bmw** [comment]
Closed #4054 in favor of this. We should make sure we're checking for regressions of #4053.

**Comment by SwartzCr** [comment]
@ohemorange any progress on this?

**Comment by ohemorange** [comment]
Nope! But it's also more of a "keep in mind as we find new things" sort of issue.
