### ISSUE TITLE
Support importing an account via private key

### ISSUE THREAD

**Issue by rolandshoemaker** [certbot/certbot#4251]
So people can use accounts that weren't initially created using Certbot.

**Comment by bmw** [comment]
I agree we should support this, however, it's a pretty niche feature so to be honest we probably won't get to it for a while.

**Comment by bmw** [comment]
I think we'd still accept a well written PR for this, but I doubt this is something the Certbot team will ever realistically get to. In most cases, I'd tell people to just create a new account for use with Certbot.

For that reason, I'm closing this, but if you still think this is important Roland, please chime in describing why and we can maybe reopen the issue.
