### ISSUE TITLE
Allow detemining whether certs need renewal via exit code

### ISSUE THREAD

**Issue by strugee** [certbot/certbot#4253]
Currently the script I use for managing Let's Encrypt renewals has to stop all active web servers because of #255. It'd be nice if I was able to add some logic that checked if any of the certs needed renewal and abort if they don't.

**Comment by SwartzCr** [comment]
this sounds like a pretty useful enhancement.
Correct me if I'm wrong, but what you're looking for is a command that you can run that says "these scripts are within the renewal window and will trigger a challenge if you run certbot renew"
Then you could take the output of that and know whether to stop the servers on your computer and then run `certbot renew`
right? or were you thinking of a different workflow?

**Comment by strugee** [comment]
@SwartzCr that'd be useful, but what's really important is the exit code so I can do e.g.:

```bash
#!/bin/sh

if certbot renew --check-renewal > /dev/null; then
    certbot renew
fi
```

That way you don't have to parse the output, it's just "is there any cert that can be renewed? Yes? Renew 'em all"

**Comment by SwartzCr** [comment]
@strugee got it
@ohemorange wanna put this into a milestone? Seems like a plausible feature

**Comment by bmw** [comment]
As explained in #3262, we decided not to use different exit codes for renewal in favor of a hooks system. For your case, you'd want something like:
```
certbot renew --pre-hook "service myserver stop" --post-hook "service myserver start"
```
These hooks will only run when a certificate has to be renewed. If I'm misunderstanding your use case and this won't work for some reason, please let me know and I'll reopen.

**Comment by ohemorange** [comment]
I agree with Brad. Also, if you really want to do things this way, #4138 should let you answer this and other questions programmatically.

**Comment by strugee** [comment]
Oh yeah, that seems to satisfy my use case. Do hooks do error handling? I.e. if a hook exits with an exit code of 1, will certbot fail accordingly? This isn't documented anywhere.

**Comment by bmw** [comment]
If you cert is due for renewal and a hook fails, it will print the error to `stderr` but still try to renew the cert. A failing hook doesn't cause Certbot to exit with a non-zero error code.

**Comment by SwartzCr** [comment]
@strugee any interest in documenting this? There's now a section for hooks in the documentation I think it'd be nice to mention error handling there. If you're up for writing something I'd be happy to review and merge it!
