### ISSUE TITLE
OSError: Command /root/.local/share/letsencrypt...on2.7 -c "#!python

### ISSUE THREAD

**Issue by claytonwells** [certbot/certbot#4261]
## My operating system is (include version):
Fedora 14

## How did you install Certbot:
wget https://dl.eff.org/certbot-auto
chmod a+x certbot-auto

## What command did you run and what output did it produce?
./certbot-auto

###### It is stored by default in `/var/log/letsencrypt` - feel free to redact domain names, e-mail and IP addresses as you see fit

./certbot-auto
Bootstrapping dependencies for RedHat-based OSes...
yum is /usr/bin/yum
Loaded plugins: langpacks, presto, refresh-packagekit
Adding en_US to language list
Setting up Install Process
Package gcc-4.5.1-4.fc14.i686 already installed and latest version
Package augeas-libs-0.9.0-1.fc14.i686 already installed and latest version
Package openssl-1.0.0e-1.fc14.i686 already installed and latest version
Package openssl-devel-1.0.0e-1.fc14.i686 already installed and latest version
Package libffi-devel-3.0.9-1.fc13.i686 already installed and latest version
Package redhat-rpm-config-9.1.0-8.fc14.noarch already installed and latest version
Package ca-certificates-2011.78-1.fc14.noarch already installed and latest version
Package python-2.7-8.fc14.1.i686 already installed and latest version
Package python-devel-2.7-8.fc14.1.i686 already installed and latest version
Package python-virtualenv-1.5.1-1.fc14.noarch already installed and latest version
Package python-tools-2.7-8.fc14.1.i686 already installed and latest version
Package python-pip-0.8.3-1.fc14.noarch already installed and latest version
Package 1:mod_ssl-2.2.17-1.fc14.i686 already installed and latest version
Nothing to do
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 1647, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 558, in main
    prompt=options.prompt)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 654, in create_environment
    install_setuptools(py_executable, unzip=unzip_setuptools)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 384, in install_setuptools
    _install_req(py_executable, unzip)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 360, in _install_req
    cwd=cwd)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 624, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /root/.local/share/letsencrypt...on2.7 -c "#!python
\"\"\"Bootstrap setuptoo...

**Comment by bmw** [comment]
Fedora 14 was EOL'd in [2011](https://en.wikipedia.org/wiki/Fedora_version_history#Version_history). Due to it not being widely used and no longer supported by Fedora, I unfortunately don't think we're going to invest resources into maintaining support in `letsencrypt-auto`. If you'd like to try to get Certbot working on the system, you can try following our [developer instructions](https://certbot.eff.org/docs/contributing.html), but I think it's quite likely that the OS packages available are too old to support Certbot.
