### ISSUE TITLE
Feature request: Allow discovery of verification addresses/ports via DNS SRV

### ISSUE THREAD

**Issue by matthanley** [certbot/certbot#4265]
Seems like a sensible solution to #2697 and similar without compromising security would be to allow discovery of the port via DNS SRV record. Letsencrypt could query a record like

```
_letsencrypt._tcp IN SRV 0 0 8080 10.10.10.10
```

on the domain and forward verification requests to the resulting address/port combination. This has the same benefits as DNS verification but without the drawback of requiring dynamic updates.

This would also mean users could easily centralise the management of their certificates if they wish, by referencing a central cert server.

**Comment by SwartzCr** [comment]
I'd say this would be a major change to the ACME spec and might not work from the boulder side - so I'm going to tag @jsha to add his thoughts to this.

**Comment by jsha** [comment]
That's correct. It would need an ACME change, but also (more difficult) would need buy-in from the CA/Browser forum, which is unlikely (it's been discussed there already).

**Comment by eberls** [comment]
Got a link to that discussion, and/or a detailed threat model this is trying to prevent?

**Comment by jsha** [comment]
Sorry, I'd have to search the archives for it, but it's somewhere under https://cabforum.org/pipermail/public/.
