### ISSUE TITLE
Make our own deb and rpm packages

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4274]
This allows us to have more control over our dependencies and helps people get precompiled and up to date versions of our packages sooner.

**Comment by hlieberman** [comment]
Mmmmm... :-1:.  If you really want to go down this road, please don't ship debian/ in the root package directory; that will make things much more complicated and annoying.  Additionally, you will need to commit to maintaining an apt repository for all the different distributions; distributing .debs directly is essentially engineering malpractice.

**Comment by bmw** [comment]
If we go down this road, we certainly would avoid doing anything that would your life more complicated.

How do the Google Chrome's, Dropbox's, and Vagrant's of the world just ship a single 32-bit and 64-bit .deb that works on multiple systems then?

**Comment by strugee** [comment]
IIRC those .debs include a file in `/etc/apt/sources.list.d`. Probably they have a postinstall script to import the right keys too.

That being said, I haven't looked in a long time. So this might not be it.

**Comment by ohemorange** [comment]
sticking this here for posterity: https://medium.com/@sdboyer/so-you-want-to-write-a-package-manager-4ae9c17d9527

**Comment by strugee** [comment]
@ohemorange having read a couple paragraphs in I'm unclear as to how that article applies to this bug? That's about writing a new package manager, not creating a package _for_ an existing package manager

**Comment by bmw** [comment]
This issue isn't really needed.

We're probably going to create [snaps](https://snapcraft.io/) instead but if we decide to revisit this approach, I don't think there's any context in this issue that hasn't already been captured elsewhere so I'm closing this.
