### ISSUE TITLE
Ubuntu 16.04 Apache Error and Failing to Encrypt. 

### ISSUE THREAD

**Issue by SkiDooGuy** [certbot/certbot#4276]
## Letsencrypt Log:

2017-03-01 15:42:27,954:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.4.1', 'console_scripts', 'letsencrypt')()
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1986, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 662, in run
    lineage, action = _auth_from_domains(le_client, config, domains)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 474, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/client.py", line 269, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/client.py", line 252, in obtain_certificate
    return self.obtain_certificate_from_csr(domains, csr) + (key, csr)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/client.py", line 225, in obtain_certificate_from_csr
    authzr = self.auth_handler.get_authorizations(domains)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/auth_handler.py", line 80, in get_authorizations
    cont_resp, dv_resp = self._solve_challenges()
  File "/usr/lib/python2.7/dist-packages/letsencrypt/auth_handler.py", line 115, in _solve_challenges
    dv_resp = self.dv_auth.perform(self.dv_c)
  File "/usr/lib/python2.7/dist-packages/letsencrypt_apache/configurator.py", line 1554, in perform
    self.restart()
  File "/usr/lib/python2.7/dist-packages/letsencrypt_apache/configurator.py", line 1463, in restart
    self._reload()
  File "/usr/lib/python2.7/dist-packages/letsencrypt_apache/configurator.py", line 1474, in _reload
    raise errors.MisconfigurationError(str(err))
MisconfigurationError: Error while running apache2ctl graceful.
httpd not running, trying to start
Action 'graceful' failed.
The Apache error log may have more information.

AH00112: Warning: DocumentRoot [/var/lib/letsencrypt/tls_sni_01_page/] does not exist
AH00112: Warning: DocumentRoot [/var/lib/letsencrypt/tls_sni_01_page/] does not exist

## Apache error.log:

[Wed Mar 01 10:42:27.572152 2017] [ssl:warn] [pid 3552] AH01906: be2d88c3054ac88db159a89f6ae3c7a8.beba212c3b5883ce3fa43d701a2eb6d3.acme.invalid:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Wed Mar 01 10:42:27.572883 2017] [ssl:warn] [pid 3552] AH01906: 0d7631cdaca62a7451d509b42feae6cb.f2bd692515e37f1309501e500adee06c.acme.invalid:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Wed Mar 01 10:42:27.573224 2017] [ssl:emerg] [pid 3552] AH02572: Failed to configure at least one certificate and key for example.com:443
[Wed Mar 01 10:42:27.573257 2017] [ssl:emerg] [pid 3552] SSL Library Error: error:0906D06C:PEM routines:PEM_read_bio:no start line (Expecting: DH PARAMETERS) -- Bad file contents or format - or even just a forgotten SSLCertificateKeyFile?
[Wed Mar 01 10:42:27.573283 2017] [ssl:emerg] [pid 3552] SSL Library Error: error:0906D06C:PEM routines:PEM_read_bio:no start line (Expecting: EC PARAMETERS) -- Bad file contents or format - or even just a forgotten SSLCertificateKeyFile?
[Wed Mar 01 10:42:27.573315 2017] [ssl:emerg] [pid 3552] SSL Library Error: error:140A80B1:SSL routines:SSL_CTX_check_private_key:no certificate assigned
[Wed Mar 01 10:42:27.573332 2017] [ssl:emerg] [pid 3552] AH02311: Fatal error initialising mod_ssl, exiting. See /var/log/apache2/error.log for more information
AH00016: Configuration Failed
[Wed Mar 01 10:42:27.882106 2017] [ssl:emerg] [pid 3560] AH02572: Failed to configure at least one certificate and key for example.com:443
[Wed Mar 01 10:42:27.882224 2017] [ssl:emerg] [pid 3560] SSL Library Error: error:140A80B1:SSL routines:SSL_CTX_check_private_key:no certificate assigned
[Wed Mar 01 10:42:27.882241 2017] [ssl:emerg] [pid 3560] AH02311: Fatal error initialising mod_ssl, exiting. See /var/log/apache2/error.log for more information
AH00016: Configuration Failed

I've done as much searching as I can. I am stumped. It almost appears that there are some other certs causing issues? But this is a fresh whipe/install of Unbuntu last night, and I have installed everything manually, no back up usage. So everything should be in a fresh state.

Any assistance would be appreciated.

**Comment by SkiDooGuy** [comment]
Figured it out. 

PHP7 is a bugger to work with. I removed all PHP programs and files from my machine and began fresh. A bit of tinkering with configs dealing with PHP and Apache and it worked without a hitch.

**Comment by SwartzCr** [comment]
great - I'm going to close this - feel free to open new issues if any come up for you!
