### ISSUE TITLE
Failed to find apache2ctl in PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

### ISSUE THREAD

**Issue by EmersonBR** [certbot/certbot#4282]
## My operating system is (include version):
raspian 1.1 Pi

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
?

## I ran this command and it produced this output:
pi@hassbian:~ $ cd letsencrypt
pi@hassbian:~/letsencrypt $ ./letsencrypt-auto certonly --email xxxxxxx@gmail.com -d xxxxxxxxxxx.duckdns.org

## Certbot's behavior differed from what I expected because:

Got an error:

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Failed to find apache2ctl in PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

How would you like to authenticate with the ACME CA?
-------------------------------------------------------------------------------
1: Place files in webroot directory (webroot)
2: Spin up a temporary webserver (standalone)
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): Traceback (most recent call last):
  File "/home/pi/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 882, in main
    return config.func(config, plugins)
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 650, in obtain_cert
    installer, auth = plug_sel.choose_configurator_plugins(config, plugins, "certonly")
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/selection.py", line 190, in choose_configurator_plugins
    authenticator = pick_authenticator(config, req_auth, plugins)
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/selection.py", line 40, in pick_authenticator
    config, default, plugins, question, (interfaces.IAuthenticator,))
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/selection.py", line 82, in pick_plugin
    plugin_ep = choose_plugin(list(six.itervalues(prepared)), question)
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/selection.py", line 115, in choose_plugin
    question, opts, help_label="More Info", force_interactive=True)
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/display/util.py", line 120, in menu
    code, selection = self._get_valid_int_ans(len(choices))
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/display/util.py", line 392, in _get_valid_int_ans
    ans = six.moves.input(input_msg)
KeyboardInterrupt

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

I can't find the letsencryp log either. I am trying to install let's encrypt using Putty on my Raspberry Pi 3.

what to do? Thank you in advance for your help.

**Comment by GenZai** [comment]
Same error message here, but it didn't burden the rest  of the process (my certificate works well)
On Ubuntu 14.04

**Comment by bmw** [comment]
> KeyboardInterrupt

This error would be caused by hitting ctrl+c when Certbot is running. Are you able to reproduce this problem (without hitting ctrl+c)?

**Comment by EmersonBR** [comment]
I hit crtl C after to copy everything.

**Comment by bmw** [comment]
ctrl+c is what would cause the `KeyboardInterrupt` error and crash you included above. What's the problem you're having?

**Comment by EmersonBR** [comment]
I can't get a certificate from lets encrypt. How do I check for the certificate? 

Also,  Domain: xxxxxxxxxxxx.duckdns.org
Type: connection
Detail: Failed to connect to xx.xx.xx.xxx:443 for TLS-SNI-01
challenge

To fix these errors, please make sure that your domain name was
entered correctly and the DNS A record(s) for that domain
contain(s) the right IP address. Additionally, please check that
your computer has a publicly routable IP address and that no
firewalls are preventing the server from communicating with the
client. If you're using the webroot plugin, you should also verify
that you are serving files from the webroot path you provided.

Your account credentials have been saved in your Certbot
configuration directory at /etc/letsencrypt. You should make a
secure backup of this folder now. This configuration directory will
also contain certificates and private keys obtained by Certbot so
making regular backups of this folder is ideal.

Thank you again BMW.

**Comment by bmw** [comment]
If you're not running Apache on your Raspberry Pi, the message about not finding Apache binaries is to be expected. What's the difference between this issue and #4285? Do we need both?

**Comment by besi** [comment]
I just ran into this problem using the following command:

    /somepath/bin/certbot-auto --pre-hook "service nginx stop" --post-hook "service nginx start"

Please note that I'm not using apache so I don't see why `apachectl` should be used. So currently I can't update my SSL certificate and I'm wondering if there is a way to work around this problem.

**Comment by alex-bukach** [comment]
Same for me.
