### ISSUE TITLE
Certbot automatic nginx configuration breaks android 16 4.x.x (not browser just java) 

### ISSUE THREAD

**Issue by marlaw** [certbot/certbot#4284]
Tested on Android 16 x86 as per Android Studio AVD

Certbot sets in Nginx

ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-ECDSA-AES256-GCM-SHA384 ECDHE-ECDSA-AES128-SHA ECDHE-ECDSA-AES256-SHA ECDHE-ECDSA-AES128-SHA256 ECDHE-ECDSA-AES256-SHA384 ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES128-SHA ECDHE-RSA-AES128-SHA256 ECDHE-RSA-AES256-SHA384 DHE-RSA-AES128-GCM-SHA256 DHE-RSA-AES256-GCM-SHA384 DHE-RSA-AES128-SHA DHE-RSA-AES256-SHA DHE-RSA-AES128-SHA256 DHE-RSA-AES256-SHA256 EDH-RSA-DES-CBC3-SHA"; # managed by Certbot

This however seems to break Android devices running Android 16 (4.x.x) but not the browser just Java clients (like Netty 4.1.4)

Is this expected? It works fine on latest two major releases of Android and I suspect it is broken on Android 14 too.

Please let me know if I can provide more information.

**Comment by bmw** [comment]
Thanks for the report. @schoen is going to take a look at this.

**Comment by schoen** [comment]
@bmw, it looks like that ciphersuite list is based on `certbot/certbot-nginx/certbot_nginx/options-ssl-nginx.conf`, which says

`ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-ECDSA-AES256-GCM-SHA384 ECDHE-ECDSA-AES128-SHA ECDHE-ECDSA-AES256-SHA ECDHE-ECDSA-AES128-SHA256 ECDHE-ECDSA-AES256-SHA384 ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES128-SHA ECDHE-RSA-AES128-SHA256 ECDHE-RSA-AES256-SHA384 DHE-RSA-AES128-GCM-SHA256 DHE-RSA-AES256-GCM-SHA384 DHE-RSA-AES128-SHA DHE-RSA-AES256-SHA DHE-RSA-AES128-SHA256 DHE-RSA-AES256-SHA256 EDH-RSA-DES-CBC3-SHA";`

I'm not sure where this particular list originates. I thought we decided that we would use the Mozilla configuration generator as the basis of all the ciphersuite settings, but currently the above list doesn't match either the "Modern" or "Intermediate" nginx configuration generated by

https://mozilla.github.io/server-side-tls/ssl-config-generator/

It's somewhat intermediate in length between the two, which makes me think that it either comes from elsewhere, or is the "Modern" output from some time in the past. Or maybe it was taken from nginx's own defaults?

According to my understanding, the default should be Mozilla's "Intermediate" recommendation, which for nginx is currently

`    ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS';`

and which claim compatibility back to

> Firefox 1, Chrome 1, IE 7, Opera 5, Safari 1, Windows XP IE8, Android 2.3, Java 7

**Comment by bmw** [comment]
> I'm not sure where this particular list originates.

It's based on "Bulletproof SSL and TLS", however, this is a legacy decision and we decided we'd use Mozilla's recommendations as described [here](https://certbot.eff.org/docs/ciphers.html#sources-of-defaults). Looks like Nginx never never got updated.

We should make sure we change this before unhiding the Nginx plugin.

And just so she's aware of this issue, cc @ohemorange

**Comment by bmw** [comment]
We should check if old nginx installations are updated to the new ciphersuites.

**Comment by ohemorange** [comment]
Ok, so we currently have three places where it might be logical to go in and update the ciphersuites:

1. Renew
2. Run/Install - create
3. Run/Install - update

As things currently stand (https://github.com/certbot/certbot/pull/4426), 2 is really the only one where we'd be putting in new ciphersuites. This seems insufficient.

3 is doable by modifying only the Nginx plugin.

1, however, would mean hooking into `reload` (seems wrong), or adding a new call to `(re)install` after renewal (better), or adding a new plugin call like `update_to_modern_config` (maybe a bit too many calls to have). [Interestingly, a side effect of reinstalling the cert after each renewal means that the whole symlinking and pretending we renew certs loses much of its benefits, at least for those using the plugin. Which... may not be the worst thing? But I'm not suggesting we should kill lineages right now, more of a side note.]

I assume there have been previously design conversation around this, when certbot was younger. Any decisions we made then that we definitely want to stick to now?

**Comment by bmw** [comment]
I have a preference for a new, optional renew reinstall method like the one described in #4046 or #4199. This allows us and other plugin authors to do things like this after renewing a cert which isn't currently possible without butchering our hooks system.

@schoen, would know the most about the design decisions surrounding renewal though.

**Comment by schoen** [comment]
@pde had a theory about this back in the day (around "applying new enhancements", which could be extremely far-ranging and include significant changes to web server configurations in the service of mitigating vulnerabilities or enabling cool new technology). But I don't believe that we have any specific deployed precedent for this, which makes me think it is actually flexible at the moment.

By the way, I approved #4426.

**Comment by ohemorange** [comment]
Sounds like @schoen's stuff could work either way. I could go for the additional reinstall method. Moving discussion to the existing PR.

**Comment by ohemorange** [comment]
Created issues #4524, #4525, #4526, and #4527 to follow-up on this issue; closing in favor of those.

Broadly, we will change the infrastructure so we don't have to call `deploy_cert` during renew to update, for example, ciphersuites.
