### ISSUE TITLE
Command-line options for renewer script

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#429]
The renewer script is most commonly meant to run from cron, and that's the feature set that I've provided for so far (trying to make decisions automatically in an unattended fashion).

There is an `/etc/letsencrypt/renewer.conf` which can provide defaults to decide whether autorenewal and autodeployment are enabled or disabled, when renewal and deployment should happen, and other topics. To control the behavior of the renewer when run in unattended mode, that file should be edited.

I haven't considered what kind of command-line options we might want to have for the case where the user runs the renewer script manually (for example, to try to renew one particular lineage).

**Comment by schoen** [comment]
Slightly related to #421. What options get set from the command line (and how), and what options get set from the renewal config file or the systemwide renewer config?

I'm committing something that improves the config behavior slightly but still doesn't attempt to parse command-line arguments at all.

**Comment by pde** [comment]
Mostly done. Some parts left: #1028
