### ISSUE TITLE
Multiple alias hosts issues with nginx

### ISSUE THREAD

**Issue by zenny** [certbot/certbot#4307]
I am having multiple alias hosts problem similar to https://github.com/certbot/certbot/issues/1042 with a Debian8 Jessie server running nginx. Certbot version is 0.9.3-1~bpo8+2 installed using apt from jessie-backports.

I have four domains pointing to the same site and all DNS entries points to the same domain (All others except FIRST-DOMAIN.ORG are aliases). 

The certs were issued three months back with the same vhosts config. But it failed when trying to renew the LE certs. The supposedly problematic FIRSTDOMAIN.ORG as of below is reachable from the Internet. Therefore. I tried to obtain certificate manually, yet one of the alias domain fails as of below:

> ​​# certbot certonly -n --text --agree-tos --authenticator webroot --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --email noreply@SECOND-DOMAIN.COM -d FIRST-DOMAIN.ORG -d www.FIRST-DOMAIN.ORG -d FIRSTDOMAIN.ORG -d www.FIRSTDOMAIN.ORG -d SECOND-DOMAIN.COM -d www.SECOND-DOMAIN.COM -d SECONDDOMAIN.COM -d www.SECONDDOMAIN.COM  --webroot-path /usr/local/ispconfig/interface/acme
> Saving debug log to /var/log/letsencrypt/letsencrypt.log
> Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
> Obtaining a new certificate
> Performing the following challenges:
> http-01 challenge for FIRST-DOMAIN.ORG
> http-01 challenge for www.FIRST-DOMAIN.ORG
> http-01 challenge for FIRSTDOMAIN.ORG
> http-01 challenge for www.FIRSTDOMAIN.ORG
> http-01 challenge for SECOND-DOMAIN.COM
> http-01 challenge for www.SECOND-DOMAIN.COM
> http-01 challenge for SECONDDOMAIN.COM
> http-01 challenge for www.SECONDDOMAIN.COM
> Using the webroot path /usr/local/ispconfig/interface/acme for all unmatched domains.
> Waiting for verification...
> Cleaning up challenges
> Unable to clean up challenge directory /usr/local/ispconfig/interface/acme/.well-known/acme-challenge
> Failed authorization procedure. FIRSTDOMAIN.ORG (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Could not connect to www.FIRSTDOMAIN.ORG
> 
> IMPORTANT NOTES:
>  - The following errors were reported by the server:
> 
>    Domain: FIRSTDOMAIN.ORG
>    Type:   connection
>    Detail: Could not connect to www.FIRSTDOMAIN.ORG
> 
>    To fix these errors, please make sure that your domain name was
>    entered correctly and the DNS A record(s) for that domain
>    contain(s) the right IP address. Additionally, please check that
>    your computer has a publicly routable IP address and that no
>    firewalls are preventing the server from communicating with the
>    client. If you're using the webroot plugin, you should also verify
>    that you are serving files from the webroot path you provided.

**Comment by bmw** [comment]
#1042 is about our Apache parser being unable to parse multiple files containing multiple `VirtualHost` directives. This situation is quite a bit different because your webserver is irrelevant when using webroot. Certbot is just placing files at the path you specified and not parsing your webserver configuration in any way.

I suspect what happened here is your Nginx configuration changed and it's no longer serving files out of `/usr/local/ispconfig/interface/acme`. To test this, run:
```
mkdir -p /usr/local/ispconfig/interface/acme/.well-known/acme-challenge
echo "hello" > /usr/local/ispconfig/interface/acme/.well-known/acme-challenge/foo
```
Then access http://www.FIRSTDOMAIN.ORG/.well-known/acme-challenge/foo in your web browser. Do you see "hello"? If not, configure Nginx to serve challenge files out of that directory.

**Comment by zenny** [comment]
@bmw Thanks. However, I have already tried that way as posted [ https://www.howtoforge.com/community/threads/ispconfig-3-1-2-letsencrypt-certificates-were-not-renewed-automatically.75771/#post-357051](here). Nginx vhosts files are working alright except certbot seems to behaving very randomly.

**Comment by bmw** [comment]
I missed something in your output above. Let's Encrypt's not reporting that you're serving the wrong response to the challenge, it's saying it can't connect to that domain at all.

If that doesn't help you debug the problem yourself, do you feel comfortable sharing the domain with me so I can take a look at DNS and try to connect to the server? You can send me an e-mail if you prefer. Address is bmw@eff.org.

**Comment by zenny** [comment]
@bmw, sent an email with details as your asked for. Appreciate your inputs. Thanks in advance! Chhers, /z

**Comment by bmw** [comment]
I think this issue has been resolved on the community forums. If not, please comment and I'll reopen.
