### ISSUE TITLE
SHA1 is used in certbot-auto.asc

### ISSUE THREAD

**Issue by fedor-brunner** [certbot/certbot#4308]
When verifying certbot-auto.asc

gpg --verbose --verify certbot-auto.asc

gpg: binary signature, digest algorithm SHA1

Please upgrade the SHA1 signature to SHA-512

Also the PGP key
A2CF B51F A275 A728 6234  E7B2 4D17 C995 CD97 75F2
is using only 2048 bit RSA. Please upgrade this key.

gpg --edit-key letsencrypt-client@eff.org
pub  2048R/0x4D17C995CD9775F2  created: 2015-11-25  expires: 2027-11-22  usage: SC  
                               trust: unknown       validity: unknown
sub  2048R/0xBD654F823B5F4B12  created: 2015-11-25  expires: 2027-11-22  usage: E   
sub  2048R/0x5B1EB9897C7F55C1  created: 2015-11-25  expires: 2027-11-22  usage: A

**Comment by bmw** [comment]
Thanks for pointing this out. I'll update our release process to ensure a SHA2 algorithm is used in the future.
