### ISSUE TITLE
document how different display modes interact with force_interactive

### ISSUE THREAD

**Issue by void-elf** [certbot/certbot#4310]
... because `force_interactive` doesn't actually force interactivity in non-interactive mode (it just uses the default instead), which is unintuitive and isn't written down anywhere.

**Comment by kevinkle** [comment]
If I remember what @bmw said correctly, the `force_interactive` flag isn't absolute as it checks for an actual console.

**Comment by bmw** [comment]
Correct. The high level goal of `force_interactive` has a one line description in `certbot/interfaces.py`. To briefly expand on that, it's to prevent workflow regressions for people who are getting away with running certbot non-interactively without `--non-interactive`.

To see how the implementation of this and what exactly it's doing, `certbot.display.util.FileDisplay._can_interact`.

**Comment by bmw** [comment]
This (or https://github.com/certbot/certbot/issues/3915) still needs to be done.
