### ISSUE TITLE
Error encountered using certbot on CentOS 7 w/certonly --webroot

### ISSUE THREAD

**Issue by Approach** [certbot/certbot#4314]
## My operating system is (include version):
centos 7

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
yum

## I ran this command and it produced this output:

certbot certonly --webroot -w /srv -d fakedomain.co -d www.fakedomain.co -d static.fakedomain.co -d service.fakedomain.co -d portal.fakedomain.co -d admin.fakedomain.co -d user.fakedomain.co -d secure.fakedomain.co -d portal.fakedomain.co -d dev.fakedomain.co -d staging.fakedomain.co -d backup.fakedomain.co -d garet.fakedomain.co -d sean.fakedomain.co -d system.fakedomain.co -d anthony.fakedomain.co -d test.fakedomain.co -d spare.fakedomain.co -d api.fakedomain.co

...
http-01 challenge for user.fakedomain.co
http-01 challenge for secure.fakedomain.co
http-01 challenge for dev.fakedomain.co
http-01 challenge for staging.fakedomain.co
http-01 challenge for backup.fakedomain.co
http-01 challenge for garet.fakedomain.co
http-01 challenge for sean.fakedomain.co
http-01 challenge for system.fakedomain.co
http-01 challenge for anthony.fakedomain.co
http-01 challenge for test.fakedomain.co
http-01 challenge for spare.fakedomain.co
http-01 challenge for api.fakedomain.co
Using the webroot path /srv for all unmatched domains.
Waiting for verification...
Cleaning up challenges
Unable to clean up challenge directory /srv/.well-known/acme-challenge
Generating key (2048 bits): /etc/letsencrypt/keys/0001_key-certbot.pem
Creating CSR: /etc/letsencrypt/csr/0001_csr-certbot.pem
An unexpected error occurred:
The server experienced an internal error :: Error creating new cert
Please see the logfiles in /var/log/letsencrypt for more details.

2017-03-09 18:20:03,121:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.11.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 882, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 659, in obtain_cert
    action, _ = _auth_from_available(le_client, config, domains, certname, lineage)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 108, in _auth_from_available
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 294, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 275, in obtain_certificate
    return (self.obtain_certificate_from_csr(domains, csr, authzr=authzr)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 246, in obtain_certificate_from_csr
    authzr)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 330, in request_issuance
    headers={'Accept': content_type})
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 685, in post
    return self._post_once(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 698, in _post_once
    return self._check_response(response, content_type=content_type)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 586, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:acme:error:serverInternal :: The server experienced an internal error :: Error creating new cert

## Certbot's behavior differed from what I expected because:

I have CSR files, not sure if they are valid or contain all my domains.. don't see anything on crt.sh right away. first time user. anyway this is the error i got in case it is useful at all.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

[LE.txt](https://github.com/certbot/certbot/files/831974/LE.txt)

**Comment by Approach** [comment]
oh also it worked after 2 tries, same command, just wanted to inform in case useful

**Comment by bmw** [comment]
I'm glad you got it to work. It looks like Let's Encrypt was performing some maintenance then with some expected downtime (see [this](https://letsencrypt.status.io/pages/history/55957a99e800baa4470002da)). Thanks for taking the time to file an issue and provide all of this information though!
