### ISSUE TITLE
Rewrite our various `if os.path.exists`s atomically.

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#4319]

**Comment by bobstrecansky** [comment]
Working on this at PyCon 2017.

**Comment by bobstrecansky** [comment]
@ohemorange - wanted to make sure this is what you want before I go on with the rest:
https://github.com/certbot/certbot/pull/4730

**Comment by chefscott** [comment]
What should happen if the file exists? Throw an error?

**Comment by ohemorange** [comment]
@chefscott The behavior should be the same, but with atomicity. So if the code block previously raised an error, it should be rewritten to continue to raise that error. There's further explanation at #4730 if you're looking to take this on.

**Comment by bobstrecansky** [comment]
Picking this back up; my apologies on the delay; was working through some other tickets first.

**Comment by fr0zenbits** [comment]
Is this still a valid task?  #4730 was closed yesterday.

**Comment by sydneyli** [comment]
@fr0zenbits Yes, this task is still available. The contributor who was working on #4730 didn't get the chance to finish it. You're welcome to pick it back up if you like, and there's a lot of relevant context/comments on that PR thread. Let us know if you have any more questions!

**Comment by camservo** [comment]
Looking for a first issue to help out on.  Was there a consensus on how these should be rewritten?

**Comment by ohemorange** [comment]
@camservo see discussion here: https://github.com/certbot/certbot/pull/4730#issuecomment-303933896

**Comment by ohemorange** [comment]
This is still important, and a good choice for people who want to contribute who don't have extensive knowledge of our codebase! Some information about how to implement this is available here: https://stackoverflow.com/questions/2333872/atomic-writing-to-file-with-python

**Comment by martinraag** [comment]
Looking at this as a potential first issue. For me, the description leaves a lot to interpretation and is perhaps a bit confusing. Judging by a couple of misguided attempts at solving this, I'm not alone.

As I gather, what is required are atomic versions of operations that include `os.path.exists`, to avoid potential race conditions. Looking at the source code, these vary from a simple rename referenced in [#4730 (comment)](https://github.com/certbot/certbot/pull/4730#issuecomment-303933896), to creating a single directory, creating multiple directories, opening and writing to a file, copying permissions, deleting a file, creating symlinks and launching Docker in a subprocess.

For someone new to the codebase, or at least for me, it would be useful to have more context about which operations and modules are potentially problematic. Also, whether we're trying to protect against race conditions between multiple threads, or multiple processes of certbot.

Depending on whether I have the right understanding of the amount of operations that should be made atomic, I wonder if implementing cross platform solutions to all of them is practical? Perhaps some form of locking would be more pragmatic?

Apologies if the questions sound silly or misguided, I'm very new to the project.

**Comment by ohemorange** [comment]
Hi @martinraag, welcome! The work you've done so far looking into this is exactly what we'd be looking for -- understanding the places where/if atomicity is a problem, and figuring out which are likely to cause problems when multiple instances of certbot are running simultaneously, or in any cases where there might be multi-threading. I think a good first step would be to put together a document (the Certbot team tends to use Google Docs for this) identifying the places in the codebase where the `if os.path.exists` pattern is used, and under which conditions the usage might be problematic. Then, these could either be replaced wholesale with a different style if appropriate. Certbot does already have a [locking mechanism](https://github.com/certbot/certbot/blob/ab76834100d75e5330f585b9619332e2e0c8a43e/certbot/lock.py) that's used for some things; I think it would be a useful analysis to see if that makes this issue obsolete.

**Comment by ohemorange** [comment]
I feel like I saw a PR for this go by recently-ish? Maybe not though since I don't see one here.
