### ISSUE TITLE
nginxparser from PyPI instead of vendoring

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#432]
@diracdeltas, do you think we could work with the upstream (I guess that's https://github.com/fatiherikli/nginxparser) to contribute back our changes and make sure `nginxparser` is released to PyPI (not there yet: https://pypi.python.org/pypi?%3Aaction=search&term=Nginxparser&submit=search), rather than embedding the code directly within our source tree? I'm happy to help (with the packaging).

**Comment by diracdeltas** [comment]
That would probably be good, though the upstream maintainer is not super responsive. (Ex: I don't think he's addressed https://github.com/fatiherikli/nginxparser/pull/14#issuecomment-86639221 so tests probably aren't passing.)

OTOH the code is not very complex, and we've probably used it more extensively than anyone else at this point.

**Comment by GitHubGeek** [comment]
Could be done with a fork of `nginxparser` and use the `git+` syntax, e.g.:

```
# requirements.txt
# ...
git+https://github.com/letsencrypt/nginxparser.git
```

**Comment by pde** [comment]
For the time being I think we're heading off into fork-land for Nginxparser.  Perhaps we should try to preserve APIs and upstream our changes, but it's not a top priority ATM.
