### ISSUE TITLE
certbot registration update fails due to updated terms-and-conditions

### ISSUE THREAD

**Issue by jimbauwens** [certbot/certbot#4330]
## My operating system is (include version):

Debian 8

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

apt-get (using backports), certbot 0.9.3

## I ran this command and it produced this output:

```
$ certbot register --update-registration --email new-xx@xx.xx

An unexpected error occurred:
UnexpectedUpdate: RegistrationResource(body=Registration(certificates=None, contact=('mailto:x@xx.xx',), authorizations=None, agreement=u'https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf', key=JWKRSA(key=<ComparableRSAKey(<cryptography.hazmat.backends.openssl.rsa._RSAPublicKey object at ..>)>)), uri=u'https://acme-v01.api.letsencrypt.org/acme/reg/..', new_authzr_uri=u'https://acme-v01.api.letsencrypt.org/acme/new-authz', terms_of_service=u'https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf')
```

## Certbot's behavior differed from what I expected because:

Update_registration (acme/client.py) certbot is too strict:
```
       if updated_regr != regr:
           raise errors.UnexpectedUpdate(updated_regr)
```

In my case the terms-and-conditions got updated and certbot failed.

**Comment by SwartzCr** [comment]
Hmm this does seem like a bug - I think in theory you're supposed to use --agree-tos to work around this, but it seems to only work for creating new registrations, not updating them.
Additionally I'd be curious to hear what the output of `certbot register --help` is for you.

**Comment by SwartzCr** [comment]
Also maybe @ohemorange wants to take this on? Or at least put it in a milestone? Since they previously worked on the code for updating lineages.

**Comment by ohemorange** [comment]
I think this is fixed in master. I know we were talking about it, let me check if it got merged.

**Comment by ohemorange** [comment]
Yup, see #4197.

**Comment by jimbauwens** [comment]
Ah, indeed, I missed that issue, glad it seems to be resolved.

@SwartzCr, I suppose you don't need the output of the command anymore, but in any case I had already updated my registration by manually commenting out the check in the source code.

**Comment by SwartzCr** [comment]
great, since this is fixed in master I'm going to close this issue
