### ISSUE TITLE
No package python-certbot-apache available.

### ISSUE THREAD

**Issue by mr0x20wednesday** [certbot/certbot#4332]
My operating system is: Amazon Linux 4.4.51-40.58.amzn1.x86_64

I tried to install certbot using the official instructions for RHEL7 as that appeared to be most similar to Amazon Linux. 

I ran `yum install python-certbot-apache` and it produced this output:

`Loaded plugins: priorities, update-motd, upgrade-helper
amzn-main/latest                                         | 2.1 kB     00:00     
amzn-updates/latest                                      | 2.3 kB     00:00     
epel/x86_64/metalink                                     |  11 kB     00:00     
epel-debuginfo/x86_64/metalink                           | 9.5 kB     00:00     
epel-source/x86_64/metalink                              |  10 kB     00:00     
989 packages excluded due to repository priority protections
No package python-certbot-apache available.
Error: Nothing to do`

After reading #3970 and #3257 I suspected that there was a problem with epel but it appears to be working properly. 

`yum repolist
Loaded plugins: priorities, update-motd, upgrade-helper
989 packages excluded due to repository priority protections
repo id               repo name                                       status
amzn-main/latest      amzn-main-Base                                       5,612
amzn-updates/latest   amzn-updates-Base                                      949
epel/x86_64           Extra Packages for Enterprise Linux 6 - x86_64  11,366+989
epel-debuginfo/x86_64 Extra Packages for Enterprise Linux 6 - x86_64       2,220
epel-source/x86_64    Extra Packages for Enterprise Linux 6 - x86_64           0
repolist: 20,147`

I also tried python2-certbot-apache with the same results.

**Comment by pde** [comment]
What version of Fedora is that Amazon Linux based on? Have you tried the `certbot-auto` script?

**Comment by hogarthj** [comment]
From the output you can see that amaxon linux is based on EL6, and due to version dependency issues we can't package certbot in EPEL6.

You will need to use an EL7 (or fedora) based instance or use a virtualenv based certbot-auto on that system.

**Comment by sogen** [comment]
It would be better to suggest to use --debug for Amazon instances since the default way doesn't work ATM.

**Comment by NameTheJew** [comment]
Also facing this problem
Linux 4.14.62-70.117.amzn2.x86_64 x86_64
> You will need to use an EL7 (or fedora) based instance or use a virtualenv based certbot-auto on that system.

@hogarthj  Not an option. **Amazon Linux 2** kernel tuned for performance on Amazon EC2.
Have you got another solution to get certbot working?
'Thanks

**Comment by sydneyli** [comment]
Closing in favor of tracking Amazon Linux support in #6505 and #6506!
