### ISSUE TITLE
Refactor Apache plugin unit tests to decouple test config files

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4338]
Apache version of #3873

**Comment by igy254** [comment]
Hi @bmw if no one is working on this one, I would gladly take it. It seems like a good issue to get started.

**Comment by bmw** [comment]
Hey @igy254! No one is currently working on this so feel free to take it. If you need any help, don't hesitate to ask!

**Comment by igy254** [comment]
@bmw great, I'm on it. No problem, I sure will ask if I need any help.

**Comment by igy254** [comment]
@bmw I have started to work on this today, as last few days I did not have time. Is there any way to contact you besides leaving comments here (if you don't mind), as I don't want to spam it here.

**Comment by joohoi** [comment]
We have an IRC channel #letsencrypt-dev on Freenode, feel free to join!

**Comment by bmw** [comment]
Great! @joohoi, are you able to give @rishabhkumar296 some guidance here?

**Comment by rishabhkumar296** [comment]
Hi. Any suggestions which test config file I should start from?
