### ISSUE TITLE
Relative links

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#434]
https://github.com/letsencrypt/acme-spec/issues/128; if relative links are not allowed, we should at least log an appropriate error message and notify the user, or be clever and try to normalize them based on `Location` or request URI if the former is not present.

**Comment by bmw** [comment]
Since it appears that relative links are allowed, I'm closing this issue.

**Comment by kuba** [comment]
Relative links are allowed, but our client doesn't support them. We just don't hear about it, because Boulder changed to absolute scheme upon my request. Please reopen.

**Comment by bmw** [comment]
This still seems to be an issue.
