### ISSUE TITLE
documentation, up interactive-guide-NOTICE to the first paragraph of Introduction

### ISSUE THREAD

**Issue by ppKrauss** [certbot/certbot#4341]
About the NOTICE "The best way to get started is to use our *interactive guide*" at [docs/intro.html](https://certbot.eff.org/docs/intro.html).
**Suggestion:** up it to the first paragraph! or add a lateral box (example an IMAGEM WITH THE NOTICE in red).

The Guide is so complex. All "guide readers" today use *^F* to find needs after read first paragraph... And, as a "**so impotant** notice", need the alert in the first paragraph.

The *interative guide* is so important to reduce dissatisfations with `certbot`  itself and with the Guide itself, and to reduce support demand and to reduce (expurious) communication in the forum.

**Comment by osirisinferi** [comment]
Well, the same link is present again in the "Installation" paragraph. And those section headers are like, really big. Not something one would miss.

**Comment by ppKrauss** [comment]
Hi @osirisinferi , thanks the reply!

..hum... Now I see the document style, perhaps you can use "Note" or "Hint" boxes...
... but to make sense as "big notice" must occur in or after the **first** paragraph of the Introduction, not other place.

**Comment by SwartzCr** [comment]
@pconrad-fb This looks like something you could help with! Wanna suggest a way to make it more apparent to use the instruction generator if a user has made it to the Documentation first somehow?

**Comment by pconrad-fb** [comment]
Sure! let me get my Lineages stuff in order and I'll turn my attention to this.

**Comment by pconrad-fb** [comment]
How about this approach:

=====================
Introduction
=====================

.. note::
To get started quickly, use the `interactive installation guide <https://certbot.eff.org>`_.

.. include:: ../README.rst
    :start-after: tag:intro-begin
    :end-before: tag:intro-end

This does mean it gets mentioned twice on the page, but it means I don't have to change the README.rst file, since I don't know how it is used elsewhere.

**Comment by SwartzCr** [comment]
I'd be fine with this change - since I don't think we can style notes as nicely on github I feel less of an impetus to change it in the README

**Comment by pconrad-fb** [comment]
Okay, already done and I think it's in the PR. I'll check.

**Comment by SwartzCr** [comment]
okay, feel free to tag me in it and I'll review!

**Comment by SwartzCr** [comment]
Ah I see it - taking a look now

**Comment by SwartzCr** [comment]
I think this was covered by #3675 closing - but people should feel free to re-open if you're unsatisfied by that change
