### ISSUE TITLE
Stop using Quay.io

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4343]
Now that #492 has been resolved, I think we should stop using Quay.io entirely. Why?

1. Docker Hub is the conventional place for Docker images.
2. Our current repository there is letsencrypt/letsencrypt and I'm unaware of a way to rename it. I have control of the certbot name, however, I'm unaware of a way to redirect the current repository to certbot.
3. Do we really need both Quay.io and Docker Hub?

Proposal: Change the deprecation warning in `Dockerfile-old` to say that our Dockerfile has been rewritten and moved to Docker Hub. Set up automatic builds so the image there stays up to date. Once we've waited for an extended period of time and/or Quay.io requires active maintenance, we turn off the repository entirely.

Thoughts?

cc @joohoi

**Comment by joohoi** [comment]
The proposal SGTM. I don't think we need both, and it has a high propability to confuse people in the long run. However instead of completely removing, we can just leave the image displaying the warning text, and return a non-zero value.

**Comment by bmw** [comment]
Do we keep on automatic updates and maintaining `Dockerfile-old` in the long run?

**Comment by joohoi** [comment]
I think having only one official repository that's updated and has a promise of being actively maintained is the best way forward. That being said, I think we need a grace period for people actively using Quay.io images, there was quite some, at least in some point when we discussed about the usage / download statistics. A deprecation deadline so to say, after which the actual certbot functionality should be removed, but the deprecation warning and instructions towards the maintained image (DockerHub) should be left in place.

**Comment by trusch** [comment]
Please note that rkt users are prefering quay.io because they can download native app container images. When using dockerhub a local conversion step is necessary.
