### ISSUE TITLE
3rd party plugin flags

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4351]
The name of 3rd party plugins is generated in `certbot/plugins/disco.py`. Currently, all third party plugin names are `<package>:<entry point>`. Because we use the plugin name to prefix the CLI flag name, this generates some really awkward flags `--certbot-foo:bar-baz`. We should do better, but make sure this doesn't break existing plugins by allowing the old form.

**Comment by bmw** [comment]
I think we can stop adding the name of the package to the plugin flag and just use the name of the entry point which the plugin author controls. The big thing here is we don't want to break backwards compatibility. The `package_name:entry_point_name` version of the flags still need to work. This affects both adding the plugin flags and fetching  the values from the parsed config.

Perhaps a simple solution is to pass multiple flags to `add_argument` [here](https://github.com/certbot/certbot/blob/master/certbot/plugins/common.py#L79) if `option_namespace` contains the package name. The `option_namespace` should probably still comes first as that's what affects the path in the parsed config, however, plugins can access these values using [conf()](https://github.com/certbot/certbot/blob/master/certbot/plugins/common.py#L103) so they don't have to see this ugliness. Only downside with this approach I see is the `package_name:entry_point_name` version will be used in renewal configuration files, but I can't see any other problems here. I definitely could be overlooking something though so this will require some experimentation and testing.

**Comment by bmw** [comment]
I still think we should do this. It's easily the most common complaint I see about writing 3rd party Certbot plugins.

**Comment by Fluepke** [comment]
Due to the colon it is not possible to provide configurations for plugins in the `cli.ini` configuration file.
