### ISSUE TITLE
ConnectionError heisenbug in our tests

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4363]
We get this from time to time and we should investigate it to make sure it's not a real issue and to stop slowing down developers.

Here's a [log](https://github.com/certbot/certbot/files/848883/log.txt) of the problem.

**Comment by jsha** [comment]
I added code to dump the boulder logs on failures, which may make more information available next time this happens. Add another log if you see it, please!

**Comment by bmw** [comment]
I don't think we've seen this error since around the time I created this issue so I'm closing this.
