### ISSUE TITLE
Documentation: bootstrapping link isn't informative

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#4366]
Per https://community.letsencrypt.org/t/dont-know-how-to-bootstrap-certbot-on-your-os/29905, if you try to install certbot-auto on an OS it doesn't recognize, it says

> Sorry, I don't know how to bootstrap Certbot on your operating system!
> You will need to bootstrap, configure virtualenv, and run pip install manually.
> Please see https://letsencrypt.readthedocs.org/en/latest/contributing.html#prerequisites

However, that documentation link doesn't actually explain how to bootstrap if the certbot-auto bootstrapper doesn't work. We should improve the documentation.

**Comment by SwartzCr** [comment]
@jsha - interesting, do you think that it should link to the Certbot documentation instead?

**Comment by jsha** [comment]
Actually, I didn't even notice that that pointed at the old URL. What I was pointing out was that both old an new URLs say this:

https://certbot.eff.org/docs/contributing.html#prerequisites
> OS-level dependencies can be installed like so:
> letsencrypt-auto-source/letsencrypt-auto --os-packages-only
> In general...
> sudo is required as a suggested way of running privileged process

Since we point here after a failure to run the bootstrapping in `certbot-auto`, we shouldn't instruct people to run the same bootstrapping again. We should probably have a section for developers that says to use the built-in bootstrapping, and have a section for people for whom bootstrapping failed (users or devs) that actually instructs them what packages to install. Right now we just say this:

> Python 2.6/2.7 is required
> Augeas is required for the Python bindings
> virtualenv and pip are used for managing other python library dependencies

I think this is incomplete, and doesn't provide imperative instructions. Instead we should say something like "If bootstrapping fails, you'll need to install a number of packages yourself. Note: this may be time-consuming and you may want to try an alternate client. You should find and install these libraries and programs, which may are may not be packaged for your OS:
..."

As a bonus, it would be nice to provide instructions on how to gather more info about what OS you're running, in order to file a bug to more specifically recognize that OS. For instance, in https://community.letsencrypt.org/t/dont-know-how-to-bootstrap-certbot-on-your-os/29905, the reporter can only find out that their OS is "Linux", but we don't know more than that.

**Comment by SwartzCr** [comment]
Yeah, and possibly it should point people back to certbot.eff.org, especially as things that have historically been certbot-auto suggested become system packages.
@schoen do you have any interest in taking this on? I think it requires some amount of subtlety in wording that you excel at.

**Comment by SwartzCr** [comment]
I think this text should be changed to say that we don't support certbot-auto on the user's system and suggest that they try to run certbot in a docker or something.
We do a good job of suggesting that people get a packaged version if they are trying to use certbot-auto on a system for which it was previously experimental but is now packaged (see #4520)
@bmw do you know of any good docker documentation?

**Comment by bmw** [comment]
I don't think we should suggest Docker for most people. See the wording of [our Docker documentation](https://certbot.eff.org/docs/install.html#running-with-docker) that I worked on with Peter Conrad:
> Most users should use the operating system packages (see instructions at certbot.eff.org) or, as a fallback, certbot-auto. You should only use Docker if you are sure you know what you are doing and have a good reason to do so.

I personally think that the best solution to this is #4521.

**Comment by joohoi** [comment]
Moving this issue to Wishlist as well as it's (now apparent) parent #4521

**Comment by bmw** [comment]
certbot-auto has been deprecated, will error out on new systems, and existing installations are no longer receiving updates so I'm closing this.
