### ISSUE TITLE
Documentation: Developer's Guide does not mention steps needed to define a new plugin

### ISSUE THREAD

**Issue by zjs** [certbot/certbot#4368]
https://certbot.eff.org/docs/contributing.html states:

> If you’re running on Linux, you can run the following commands to install dependencies and set up a virtual environment where you can run Certbot. You only need to do this once.
>
> ```
> cd certbot
> ./certbot-auto --os-packages-only
> ./tools/venv.sh
> ```

While this seems to be accurate for many (most?) cases, it seems to be necessary to re-run `./tools/venv.sh` when defining a new plugin in `setup.py`.

That may be an uncommon use case though, so perhaps that caveat belongs in the "Writing your own plugin" section. That section could also be expanded to describe the high-level changes which are necessary for defining a new plugin.

**Comment by SwartzCr** [comment]
Yeah - ideally this should be added to the Developer's Guide part of the documentation. Want to take a pass at writing something up for it?

**Comment by zjs** [comment]
Sure, but I may hold off until I write a couple more to see what other useful information I learn.

**Comment by SwartzCr** [comment]
okay - but feel free to write whenever and we can edit

**Comment by SwartzCr** [comment]
this should be closed due to the merge of #4455
