### ISSUE TITLE
Automatically use a mirror if pypi.python.org is blocked

### ISSUE THREAD

**Issue by pde** [certbot/certbot#4371]
If people try to run `certbot-auto` in certain countries, they may encounter #2516. Perhaps certbot-auto could detect that, and try some mirrors?

This should be safe, since we're checking hashes on all of our python dependencies.

**Comment by kevinkle** [comment]
Being discuessed in https://github.com/certbot/certbot/pull/4711

**Comment by SwartzCr** [comment]
@kevinkle did you end up opening an issue in pipstrap for this?

**Comment by kevinkle** [comment]
Yup, it's at https://github.com/erikrose/pipstrap/issues/8

**Comment by SwartzCr** [comment]
@erikrose does https://github.com/erikrose/pipstrap/commit/19824c6011ccd083c7f182089004cf0d283779c3 close this?

**Comment by erikrose** [comment]
@SwartzCr Partly. I lost momentum when [I realized](https://github.com/erikrose/pipstrap/pull/10#issuecomment-314830591) that it solves only half the problem: the half which doesn't use pip itself. So some work remains to be done.

**Comment by bmw** [comment]
Some work on this was done in #5158 and the code was saved in the [branch pypi-mirrors](https://github.com/certbot/certbot/tree/pypi-mirrors).
