### ISSUE TITLE
pip failing to run git in docker

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4382]
When running tests with our `docker-compose` development setup, you see output like:
```
lint installed: Error [Errno 2] No such file or directory while executing command git config --get-regexp remote\..*\.url,cannot determine version of editable source in /opt/certbot/src (git command not found in path),Error [Errno 2] No such file or directory while executing command git rev-parse,Error [Errno 2] No such file or directory while executing command git rev-parse,Error [Errno 2] No such file or directory while executing command git rev-parse,Error [Errno 2] No such file or directory while executing command git rev-parse,Error [Errno 2] No such file or directory while executing command git rev-parse,acme==0.13.0.dev0...
```
This confuses new developers (and me until I figured out what was going on). This is `pip` noticing that the files installed in editable mode are part of a `git` directory and trying to use it to track changes. We have `.git` in our `.dockerignore`, but because we mount the cloned Certbot repo on the host inside the docker container, `.git` is available inside of `Docker`.

Perhaps we should install `git` in `Docker-dev`. Is the difference in `git` version between the host and container a possible problem if we do this? At the very least, we should document this behavior to avoid confusion.

**Comment by six8** [comment]
Seems like pip should be made to ignore `.git` if `git` command is missing.

**Comment by bmw** [comment]
Fixed in #4703.

**Comment by virgincodes** [comment]
try this 
```
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git
```

**Comment by virgincodes** [comment]
OR 
```
RUN apt-get install --assume-yes git
```
