### ISSUE TITLE
The server could not connect to the client to verify the domain

### ISSUE THREAD

**Issue by ezekel** [certbot/certbot#4388]
In my go daddy account I created A record for subdomain and point to i.p address of my google compute engine . in my GCE or google compute engine i createad server block because I am using nginx. my subdomain is working fine now I decided to install letetsencrypt and I use certbot. when I followed the tutorial issuing this command

`
./certbot-auto certonly --webroot -w /var/www/project -d mysubdomain.mydomain.com --non-interactive --agree-tos --email mygmail@gmail.com`

after I hit enter it says

`
Failed authorization procedure. mysubdomain.mydomain.com (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Could not connect to xxx.xxx.xxx.xxx
`

can I used letsencrypt in GCE ?

**Comment by SwartzCr** [comment]
Have you tried hosting a file at that endpoint and then navigating to it via a web browser? I'd work to make sure that you can navigate to a file placed in the same directory as you are specifying for Certbot. If you can and it still isn't working via certbot please share a debug log after you run certbot

**Comment by SwartzCr** [comment]
@tonsV2 can you give more context on the server that's running the nginx server on Fedora? How is it hosted? It's not also Google Compute Engine, right?
@ohemorange or @joohoi any ideas on how to debug?

**Comment by ohemorange** [comment]
@tonsV2 is your fedora machine assigned a static IP address, or is it a VM in a service that assigns ephemeral IPs? Do you have any redirects in your configuration?

Would you mind posting your (redacted) configuration files and logs?

**Comment by tonsV2** [comment]
My fedora server gets an ip from my DHCP server (running on my router)... So yeah, somewhat static and not a VM. I run several docker containers on it but beside that isn't configured in any special way. And as mentioned before, I can run a nginx server (using docker, but I would be very surprised if I couldn't get it to work without docker) and get traffic from WAN on port 443.

I've attached the letsencrypt log and the output of ifconfig. Please let me know if i can assist further.

[letsencrypt_redacted.log.txt](https://github.com/certbot/certbot/files/917305/letsencrypt_redacted.log.txt)
[ifconfig.txt](https://github.com/certbot/certbot/files/917306/ifconfig.txt)

**Comment by ohemorange** [comment]
@tonsV2 Sorry, I meant Nginx config files, not ifconfig. That's helpful too though!

**Comment by tonsV2** [comment]
docker run --name some-nginx -v /some/content:/usr/share/nginx/html:ro -p 443:80 -d nginx

I used the above while testing... Normally I run a openvpn server on port 443 though.

**Comment by ohemorange** [comment]
According to the logs, standalone is correctly starting up a server that binds to 443. I'd recommend using the `--debug-challenges` flag that shipped in 0.13.0, and seeing if you can connect to 443 at that point.

I'd also recommend posting on the let's encrypt community forums, where there are many more people who collectively know about lots of edge cases, and who will probably be able to respond on a shorter cycle.

**Comment by tonsV2** [comment]
If I understod you right I'm suppose to telnet (or the like) to port 443 when certbot pauses and says the challenges are loaded, right?
I can not connect using telnet. However I can connect if I'm firing up the some-nginx docker container I had from before.

This is working just fine on my raspberrypi so I already have my certs. I'm merely posting here to help you guys debug.... As I'm 99% sure I'm not to blame.

**Comment by ohemorange** [comment]
Ok, you should be able to connect on port 443 using telnet. If you can do that successfully and it still doesn't work, please let us know.

**Comment by tonsV2** [comment]
I can't connect to certbot using telnet. But I can connect if I'm running nginx... That's the problem.

**Comment by SwartzCr** [comment]
@tonsV2 have you tried a validation method that isn't standalone? If you're running nginx you could use either the webroot or (beta) nginx validator as well. That way you wouldn't have to rely on the server that certbot spawns, and you should be able to get a certificate

**Comment by tonsV2** [comment]
No this is all I tried. After a few tries I assumed something was off and decided to try it on another box where it worked... So end of tries. I'm not currently using nginx for anything. I only used it as a test to see if I could connect to something on the box in question.

Can you give me a hint about where certbot spawns it's server? Line number?

I've attached a screenshot of the two terminals I used to test this with.
![screenshot from 2017-04-13 01-22-16_redacted](https://cloud.githubusercontent.com/assets/46254/24983668/f50661b6-1fe8-11e7-8c5c-0b00a0f73f8b.png)

**Comment by SwartzCr** [comment]
@tonsV2 sure thing! The standalone server code should be here: https://github.com/certbot/certbot/blob/master/certbot/plugins/standalone.py#L45

**Comment by wayneworkman** [comment]
I had this same error, for me it was because I was being dumb and blocking port 443. Once I opened this, it worked.

**Comment by printercu** [comment]
Hi! Faced same issue. For me the problem was, that I had ip v4 and v6 address for domain but disabled ipv6 support on server. It was also not so obvious, because main domain has been verified by ipv4, but for subdomain ipv6 address was chosen (may be order of dns records, have not paid attention).

**Comment by SwartzCr** [comment]
@tonsV2 and @ezekel have you managed to resolve your problems?

**Comment by SwartzCr** [comment]
I'm closing this issue as stale, but if either @tonsV2 or @ezekel are still having issues, please open new issues and we can address them there
