### ISSUE TITLE
Asynchronous new certificate generation not supported

### ISSUE THREAD

**Issue by laran** [certbot/certbot#4389]
## My operating system is (include version):
OSX

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
From source (github 0.11 branch)

## I ran this command and it produced this output:

```
(venv) ➜  certbot git:(0.11.x) sudo certbot certonly --server http://localhost:8080/acme/975717a0-0a9d-11e7-b694-959dec08e8ae --standalone -d localhost
Password:
Saving debug log to /Users/laran.evans/.certbot/dev/logs/letsencrypt.log
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for localhost
Waiting for verification...
Cleaning up challenges
Generating key (2048 bits): /Users/laran.evans/.certbot/dev/config/keys/0038_key-certbot.pem
Creating CSR: /Users/laran.evans/.certbot/dev/config/csr/0038_csr-certbot.pem
An unexpected error occurred:
Error: [('asn1 encoding routines', 'ASN1_get_object', 'header too long')]
Please see the logfiles in /Users/laran.evans/.certbot/dev/logs for more details.
(venv) ➜  certbot git:(0.11.x)
```

## Certbot's behavior differed from what I expected because:

The spec says that when a certificate cannot be issued at the time of the new-cert request, an empty response should be sent.

https://github.com/letsencrypt/acme-spec/blob/e20e28aad7048e62f2927044c6b84c42fee490a3/draft-barnes-acme.md#certificate-issuance

My local acme server returns a response with a 201 status and an empty body. But certbot blows up on it because the response is empty. It seems that certbot does not support asynchronous certificate generation.

I've attached screenshots which show the response from my server with the relevant bits selected.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

```
2017-03-20 22:46:48,715:DEBUG:requests.packages.urllib3.connectionpool:http://localhost:8080 "POST /acme/975717a0-0a9d-11e7-b694-959dec08e8ae/new-cert HTTP/1.1" 201 0
2017-03-20 22:46:48,717:DEBUG:acme.client:Received response:
HTTP 201
Date: Mon, 20 Mar 2017 22:46:48 GMT
X-XSS-Protection: 1; mode=block
X-Frame-Options: sameorigin
X-Content-Type-Options: nosniff
Access-Control-Allow-Headers: origin, content-type, accept, authorization, x-applicationurl, x-requested-with
Access-Control-Expose-Headers: authorization, x-auth-token
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,HEAD
Access-Control-Allow-Credentials: true
Location: http://localhost:8080/acme/975717a0-0a9d-11e7-b694-959dec08e8ae/cert/1a2a1690-0dbf-11e7-8d30-5ba23700a27f
Link: <http://localhost:8080/acme/975717a0-0a9d-11e7-b694-959dec08e8ae/cert/1a2a1690-0dbf-11e7-8d30-5ba23700a27f>; rel="up"
Content-Type: application/json
Replay-Nonce: OTc1NzE3YTAtMGE5ZC0xMWU3LWI2OTQtOTU5ZGVjMDhlOGFlXzRhNTlmNTYxLWFlNDMtNDE0OS1hZjQ0LWNmNGNlZWUxMGY4Nw
Content-Length: 0
Server: Jetty(9.3.3.v20150827)


2017-03-20 22:46:48,718:DEBUG:acme.client:Storing nonce: OTc1NzE3YTAtMGE5ZC0xMWU3LWI2OTQtOTU5ZGVjMDhlOGFlXzRhNTlmNTYxLWFlNDMtNDE0OS1hZjQ0LWNmNGNlZWUxMGY4Nw
2017-03-20 22:47:29,789:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/Users/laran.evans/workspace/certbot/venv/bin/certbot", line 17, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/Users/laran.evans/workspace/certbot/certbot/main.py", line 882, in main
    return config.func(config, plugins)
  File "/Users/laran.evans/workspace/certbot/certbot/main.py", line 659, in obtain_cert
    action, _ = _auth_from_available(le_client, config, domains, certname, lineage)
  File "/Users/laran.evans/workspace/certbot/certbot/main.py", line 108, in _auth_from_available
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/Users/laran.evans/workspace/certbot/certbot/client.py", line 294, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/Users/laran.evans/workspace/certbot/certbot/client.py", line 275, in obtain_certificate
    return (self.obtain_certificate_from_csr(domains, csr, authzr=authzr)
  File "/Users/laran.evans/workspace/certbot/certbot/client.py", line 246, in obtain_certificate_from_csr
    authzr)
  File "/Users/laran.evans/workspace/certbot/acme/acme/client.py", line 342, in request_issuance
    OpenSSL.crypto.FILETYPE_ASN1, response.content)))
  File "/Users/laran.evans/workspace/certbot/venv/lib/python2.7/site-packages/OpenSSL/crypto.py", line 1661, in load_certificate
    _raise_current_error()
  File "/Users/laran.evans/workspace/certbot/venv/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('asn1 encoding routines', 'ASN1_get_object', 'header too long')]
![crypto py](https://cloud.githubusercontent.com/assets/8204/24125335/6e1e87fc-0d85-11e7-8568-3df2e9288025.png)
![client py](https://cloud.githubusercontent.com/assets/8204/24125336/6e21ff36-0d85-11e7-8f98-903d34dadf39.png)


```

**Comment by laran** [comment]
![crypto py](https://cloud.githubusercontent.com/assets/8204/24125431/df728188-0d85-11e7-9b1e-ffbf3ef0a903.png)
![client py](https://cloud.githubusercontent.com/assets/8204/24125430/df71b1c2-0d85-11e7-81ba-24e2a76ab416.png)

**Comment by SwartzCr** [comment]
pinging @bmw & @jsha who might be able to provide a better answer here than I can

**Comment by jsha** [comment]
Hi @laran,

Sounds like you are implementing an ACME server - awesome! If you haven't already read it, https://github.com/letsencrypt/boulder/blob/release/docs/acme-divergences.md documents what is implemented in Boulder, which is somewhat different from the current ACME draft. You may also be interested in https://github.com/letsencrypt/pebble, which is our in-progress reference implementation for the latest version of the ACME draft. We will eventually start implementing the latest draft in Boulder.

Right now Certbot doesn't bother to implement async issuance because it wasn't specified at the time the relevant code was written, and it isn't currently supported by Boulder. Once Boulder implements the latest ACME draft, it will inherently support async issuance because that's how the latest version works. And Certbot will implement support as part of its move to the latest spec also.

Is that sufficient? If async issuance handling in Certbot is a hard blocker on your current work, we could talk about whether it makes sense to add to Certbot without waiting for the protocol revision.

**Comment by laran** [comment]
Hi @jsha! You're correct. I have an ACME server in the works. I read the divergences doc a couple of months ago. I see it's had several updates since then. I'll review those. It's good to see the divergences doc keeping up with the updates to the acme spec (orders vs. applications, etc.)

Async issuance is a requirement for me. The way the acme spec outlines the polling used to check on challenges as well as certificate issuance makes a lot of sense to me. I think the protocol as it's described in the acme spec will work really well for me.

I would really love to get certbot in line with the spec, and issuance is a real blocker. So it would be a great place to start.

In general, just fyi, I've been coding the server to the acme spec. This worked fine for a while (registrations, challenges, authorizations) but then things sort of went off the rails as I started to find places where certbot just wasn't compatible with the spec. I've just been finding this by running certbot against my server and then going back to the certbot code to find where/how/why it doesn't work. So it's been a bit of a forensic exercise, and somewhat more time consuming.

Getting certbot in line with the spec will make the server development a lot smoother and probably less error prone. I have corrected and/or worked around the places where I found that certbot was different than the spec. But without a spec describing ALL the places that certbot differs it becomes difficult to ensure that I have caught all of the differences. The divergences doc helps. But having a spec and having certbot in line with that spec will make it much easier to ensure that I have captured all of the use cases properly. Right now it's a bit of a "you can support certbot or the acme spec, but not really both".

Does a roadmap exist with plans and potentially a timeline for getting certbot and pebble both online and inline with the official spec?

**Comment by SwartzCr** [comment]
So the cerbot roadmap lives in github milestones - the two upcoming ones are 0.13.0 and 0.14.0 which can be viewed here: https://github.com/certbot/certbot/milestone/34 and https://github.com/certbot/certbot/milestone/35
We have a more general milestone for 1.0 where we've been making sure to place any issues that we think are needed for our first non-beta release: https://github.com/certbot/certbot/milestone/8
I'd think that it's important that we make sure any discrepancies with the acme spec are documented and at the very least end up in that milestone - so feel free to open specific issues about places where we don't meet the spec and I'll make sure that they get tracked.
The certbot team additionally has weekly meetings where we review our progress on the current milestone and do things like move things out of or into it from larger milestones like 1.0
If you want to chat with us about what we're prioritizing, or specific features that you think we're not tracking #letsencrypt-dev on irc.freenode.net is where we mostly hang out and talk about this stuff.
If you have an interest in submitting code to certbot you'd be welcome to join the weekly meetings and talk about your progress in getting us in line with the spec.
Alternately I think a number of us would be interested in having a conversation about how to implement some of the features we don't support yet - so if you have thoughts on implementation or arcitecture I'd be happy to schedule separate specific meetings.

**Comment by jsha** [comment]
> Does a roadmap exist with plans and potentially a timeline for getting certbot and pebble both online and inline with the official spec?

We haven't committed to a timeline yet. Note that `pebble` will always be a non-production testing backend; the plan is to incorporate the lessons / code from pebble into Boulder for production use.

Check out the `acme-v2` branch on this repo for some work I've been doing toward making Certbot compatible with the current spec.

**Comment by SwartzCr** [comment]
assigning @bmw and @jsha so that they can schedule a discussion about support for this

**Comment by jsha** [comment]
@laran do you have time for a call or video chat about your needs? If so, email Brad and I to schedule. Our handles + @eff.org.

**Comment by laran** [comment]
You guys rock! Yes. I'll follow up with you tomorrow. Thanks guys.

**Comment by SwartzCr** [comment]
@jsha and @laran did any progress get made on this?

**Comment by jsha** [comment]
I'm afraid I never wrote down the conclusion of our meeting! But acme-v2 work continues.

**Comment by bmw** [comment]
Certbot now supports the standardized ACME spec so I think this can be closed, but if you're missing any features, please comment or open a new issue/PR.
