### ISSUE TITLE
config_changes uses a messed up non-pager

### ISSUE THREAD

**Issue by pde** [certbot/certbot#4392]
If you have more than one page full of output from the `config_changes` subcommand, you will get the last page listed with a weird "Press Enter to Continue" prompt.

Probably what that command should do if stdout is a terminal is invoke `$PAGER` to list the changes, in the same way that `git log` does. But failing that it should just output the stream of data so the user can pipe it to their preferred pager.

**Comment by kevinkle** [comment]
Hi! I'll try to take a shot at this.
