### ISSUE TITLE
Certbot --apache not working on Gentoo

### ISSUE THREAD

**Issue by sebastianheyn** [certbot/certbot#4401]
## My operating system is (include version):
Gentoo Base System release 2.3

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
emerge certbot-apache (9999 version from git)

## I ran this command and it produced this output:
router / # certbot --apache
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/certbot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3015, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2999, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3028, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'fasteners' distribution was not found and is required by certbot

## Certbot's behavior differed from what I expected because:
cannot identify distribution

**Comment by mrueg** [comment]
This is likely a missing package depencendy for certbot-9999 on dev-python/fasteners. I usually fix those when a new version is available. For right now, please emerge dev-python/fasteners

**Comment by sebastianheyn** [comment]
Thanks,

the next one on the list is argparse -however i can do a python and then import argparse manually and it works? There seems to be no argparse package

**Comment by sebastianheyn** [comment]
edit: installing the package argpase with pip did NOT help

**Comment by joohoi** [comment]
pinging @osirisinferi for Gentoo insights.

**Comment by osirisinferi** [comment]
Interesting.. I don't have `fasteners` installed and always run `certbot` from git without any problem..

I'll update to the latest commit and see what I can find.

**Comment by erikrose** [comment]
Is Gentoo pulling directly from certbot's master branch? That strikes me as unwise, as we might flop back and forth on important decisions like dependencies several times between releases.

**Comment by osirisinferi** [comment]
Yes, it's quite "normal" for Gentoo packages to have an ebuild which fetches the latest master branch from a VCS. They normally have the version number "9999", so it will always be the latest and to use such a package, the user must manually enable Portage to use it. The packages aren't in the `testing` branch, but actually "branch-less", so users are usualy aware of the possible limitations (some even won't compile).

**Comment by erikrose** [comment]
Very good. Then, in the spirit of information ahead of time, have a look at https://github.com/certbot/certbot/pull/4379#issuecomment-288501426: we're likely going to be reworking how we depend on argparse again.

**Comment by osirisinferi** [comment]
Although I'm not the maintainer of the Gentoo package, I'll follow it like a hawk ;)

**Comment by bmw** [comment]
Certbot no longer depends on fasteners so I suspect this issue has been resolved. If you're still having problems, please comment or open a new issue.
