### ISSUE TITLE
failing to renew cerificate

### ISSUE THREAD

**Issue by fiyona** [certbot/certbot#4405]
![image](https://cloud.githubusercontent.com/assets/19567585/24233448/5ff9db5c-0fa3-11e7-86c8-1de7e7d87a5b.png)

Am getting this error on renewing my certificates help

**Comment by SwartzCr** [comment]
Do you think you could share your renewal conf file with us? That'd help us see what domain is specified for this renewal

**Comment by SwartzCr** [comment]
Closing as stale since @fiyona has failed to provide more info.
If you're still having issues, let us know and we can work to fix them.
