### ISSUE TITLE
In certbot-auto "quiet" mode, print information to stdout when renewal is performed

### ISSUE THREAD

**Issue by nemecec** [certbot/certbot#4406]
About `certbot-auto` command line interface.

## Current behaviour

If use `--quiet` option, I get no output at all (as long as there are no errors).

If I do not use `--quiet` option, the output is fairly verbose:

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/blaah.com.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/blaah.com/fullchain.pem (skipped)
No renewals were attempted.
No hooks were run.
```

## Desired behaviour

I'm running `certbot-auto renew` inside a cron job. And I would like to see output from `certbot-auto` in case of either an error or in case certbot actually renewed some certificate. This would make it easier to troubleshoot the cron job. Also, as the actual renewal only happens once per month, it is not too much output. At least for me.

So, I would like a `--print-renewals` flag (used in combination with `--quiet` flag) that would allow be to tell `certbot-auto` to print out information about attempted renewals and their result (success or failure). And, in case no renewal is needed, certbot would not output anything (as is usual with `--quiet` flag).

**Comment by SwartzCr** [comment]
I'm curious what @ohemorange thinks about this

**Comment by ohemorange** [comment]
```
  --renew-hook RENEW_HOOK
                        Command to be run in a shell once for each
                        successfully renewed certificate. For this command,
                        the shell variable $RENEWED_LINEAGE will point to the
                        config live subdirectory containing the new certs and
                        keys; the shell variable $RENEWED_DOMAINS will contain
                        a space-delimited list of renewed cert domains
                        (default: None)
```
Sounds like `--renew-hook` will work for your purposes; then you can customize your printed message.

**Comment by nemecec** [comment]
Good catch!

So, something like this should do the trick?

`certbot-auto renew -n --quiet --pre-hook "service nginx stop" --post-hook "service nginx start" --renew-hook "echo Renewed $RENEWED_DOMAINS"`

**Comment by ohemorange** [comment]
yup, that looks good!
