### ISSUE TITLE
--register-unsafely-without-email prints message even with --quiet

### ISSUE THREAD

**Issue by jethrogb** [certbot/certbot#4408]
## My operating system is (include version):

Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

`sudo pip install certbot`

## I ran this command and it produced this output:

```
$ certbot register --non-interactive --quiet --agree-tos --register-unsafely-without-email
Registering without email!
```

## Certbot's behavior differed from what I expected because:

From `certbot --help all`:

```
  -q, --quiet           Silence all output except errors. Useful for
                        automation via cron. Implies --non-interactive.
                        (default: False)
```

**Comment by SwartzCr** [comment]
ooh - seems like a bug in --quiet, pinging @ohemorange, do you think this is an easy fix?

**Comment by ohemorange** [comment]
Yup, this is a bug, and should definitely be an easy fix.

**Comment by SwartzCr** [comment]
Wow - look at how fast that was - good job everyone!
