### ISSUE TITLE
Make adding and removing domains more intuitive and less ambiguous

### ISSUE THREAD

**Issue by St-Ranger** [certbot/certbot#4410]
I propose two changes that would make adding and removing domains to/from existing certificates more intuitive and less confusing (and a bit more "automated").

**Change 1**
_Preamble:_ 
I have been using certbot for some time (FreeBSD 10.0.*, certbot 0.10.2, 0.11.1), while reading the documentation and issues and talking to people on #certbot OTC irc channel. 
I was pleasantly surprised (very much!) how easy it was to create and install certs using `--webroot` option with apache 2.4 on FreeBSD. (I had only 8 `--dry-run`'s, of which 3 were to debug --post-hook, and 3-4 were to fix the issues with the correct root directories for a dozen or so domains of which a few are not used for web functions, but for smtp, imap, pop,  - so, they didn't have the corresponding vhosts in apache).

_Issue background_
There were a few options that I've since stumbled upon, and judging from the previous issues here, I am not the only one. The most representative examples include: #2071 and #3664 .
There is a rather confusing `--expand` ( #3664 ). There is a never-implemented `--shrink` (--compress).
Recently, with the new `--lineage` ( #3587 )  option, those two options are obsolete in a way.
I understand that `--expand` is kept, since it's already there, but I suspect it would not have been implemented today, after `--lineage`.

_Existing confusions_
(a) As discussed in #3664 , it was not clear that one has to list **all** the existing domains.
Regardless of the documentation, it would be great to just **add** new domains to the existing set without needing to repeat all of them on the command line.
Note: explicitly listing all of the domains is error prone and makes very little sense if you want to "expand" (i.e. **add**) a domain(s). What you would do is: `certbot certificates` , and then copy and paste it to the new command. That's what programs can do much better than humans.
(b) If you want to remove one domain (SANS) from the existing set, you do almost the same, but just omit the one you want to remove and add `--lineage` option. That has the same drawbacks.

_Proposed change **1**_
  New options:
**`--remove-domain`** 
**`--add-domain`**

With them, a request for the modification of the existing certificate (replacement with a sub- or super-set of the existing domains) would look like this:

**`certbot renew --add-domain new1.domain.com --add-domain new2.domain.com --remove-domain old1.domain.com --lineage mydomain.com`**

The proposed functionality is probably obvious, but just in case: 
Certbot would:
1. Open the existing certificate named mydomain.com (through an error if it doesn't exist)
2. Read all the existing domain names
3., Analyze if _all_ the removal requests can be fulfilled. (otherwise through an error)
4. Add the new domains to the list
5. Request the new certificates and place them into the same lineage name as it is done now with `--lineage`

Side Effect: 
With that the option `--expand` would be deprecated (and eventually dropped, I'd think).

**Change 2**
_Issue background / Existing confusions_
There are some confusions around **renew** -al vs. obtaining **new** certificates with the same **`--lineage`**
Just one example: Do you need `renew` with --lineage?  (or with --expand?)  
(Also, while less relevant here, it shows the degree of confusion:
Some new users think that "renew" does not replace the certificate, just somehow automagically extend the validity of the existing certificate.  )

_Proposed change **2**_
So, I propose the following new command _unambiguously_ reflecting the changes:
 **`modify`**  

With this, the options proposed in **1.** above, would look:

**`certbot modify --add-domain new1.domain.com --add-domain new2.domain.com --remove-domain old1.domain.com --lineage mydomain.com`**

**Comment by SwartzCr** [comment]
Whoa @St-Ranger thanks so much for the well written and well thought out issue!
First off I'd invite you to join #letsencrypt-dev on irc.freenode.net where a few more developers hang out than do on #certbot on irc.OFTC.net, looking forward to chatting with you more there.
Second I'm going to tag @ohemorange who undoubtedly has thoughts on implementing a new `modify` flag
Third I'm going to tag @pconrad-fb who is working on documenting lineages and might benefit from seeing some of the existing confusion around them.

**Comment by St-Ranger** [comment]
I have more thoughts on `modify` (from a different perspective).
As a matter of fact, I've drafted a different suggestion for some CLI changes (more drastic), but it is independent of the changes proposed here (with no contradiction to the proposed use of `modify`). So, to avoid any confusion I will be submitting that other one as a separate issue a bit later, when I finish it. (I have some other deadlines today.)
Is there any discussion thread(s) (issue(s)) on implementing `modify` command/flag? I could not find any, but maybe I didn't search the right way.

Thank you, for the invitation to #letsencrypt-dev, I will try to get there a bit later.

**Comment by ohemorange** [comment]
Thanks for the extensive writeup!

I have many thoughts, but perhaps the most important is in response to this:
> Some new users think that "renew" does not replace the certificate, just somehow automagically extend the validity of the existing certificate.

This is an intentional design choice. Our goal is to create an abstraction, so that most users don't need to know that `renew` does not automagically extend the validity of the existing certificate.

With that out of the way, on more substantive topics:

- I like the `--add-domain` and `--remove-domain` flags! That's a great idea. It follows clearly from the `--cert-name`/`--lineage` flag, and you make a fantastic point about computers being better able to copy over domain names than humans can.
- How would you imagine these flags affecting certonly/run commands? At first glance those don't appear to be related, but if you request an existing cert name that isn't close to expiry, we catch that and ask if you'd like to not get a new cert just yet.
- Do you imagine that modify is an exact stand-in for renew? If a cert isn't due for renewal, should calling modify get a new cert anyway?
- On the topic of deprecation, we are more likely to hide things from the help interface than to actually deprecate them -- people script things in their cron jobs and never look at them again, and we can't break that. We also have requirements to our distributors to keep existing workflows stable.

**Comment by St-Ranger** [comment]
> >   Some new users think that "renew" does not replace the certificate, just somehow automagically  extend the validity of the existing certificate.
>
> This is an intentional design choice. Our goal is to create an abstraction, so that most users don't need to know that renew does not automagically extend the validity of the existing certificate.

I completely agree that it's nice to a have an automagically working, 'push-button" "appliance" that you don't need to tune.  Then you can work with it as a "black-box" abstraction.
But  due to the variation of the systems and setups, people need to introduce changes, and that where a misunderstanding can lead to a disaster. One specific example: A user thought that he/she can **move** (not copy!) the certificates to a different server, while the renewal process would be happening from the initial server (and was obviously surprise why the renewal did not happen). I hope this example shows clearly why _understanding_ of the "magic" is often important.
However, while this question is interesting and important, here, I used it only to illustrate where some (sometimes very strange sounding) misunderstandings stem from.


Now, let's ~~encry...~~  focus on the _essential topics_:
You asked very good questions.
Let me start with the simple answer first:
- Re: deprecation: yes, I understand that the backward compatibility is important. And in this case, indeed hiding --expand should be fine. What I actually had in mind is along the lines of what is typically written in such cases:
"The older syntax is still supported for backwards-compatibility reasons, but has been deprecated and may go away in the future."

> - Do you imagine modify is an exact stand-in for renew?
- No, it is not a substitute. From the user's perspective it **must** be very different, and that why I actually proposed to use `modify` here (with --add-domain and --delete-domain) **instead** of renew.
(This will become more clear in a few moments, when I will describe my "broad-scale" view of certbot after answering the questions first.)

> - If a cert is not due fore renewal, should calling modify get a new cert anyway?
- Yes! 
(In principle, one can add a verification here, but I would argue that from the logic of `modify`, as I am proposing it, that verification would be counter-intuitive.)

> - How would you imagine these flags affecting certonly/run commands?
- You mostly answered it yourself: They are very different and independent. So, the answer is "No".


###  -----------------------------------

Let me now share with you you I see certbot on a "broad-scale". This is not necessarily how things are implemented under the hood, but how they are seen from the user's perspective, and from the use cases. (I actually started drafting this earlier as a separate issue, but it looks like its time to bring it up here).

Let me first quote an excerpt from a recent irc conversation with @osirisinferi (I hope he doesn't mind me quoting him):
```
<OsirisInferi> ... From the user's perspective, there are actually 3 modes of operation 
                      of certbot: 
<OsirisInferi> A) Initialize a new lineage with one or more domains
<OsirisInferi> B) Modify a current lineage
<OsirisInferi> C) Renewal 
```
I actually agree with that point of view, but with a few modes added:
D) revoke (cert[s])
E) account management (register, modify and un-register account,)
F) manage locally [certs and server configs locally] (install, delete, update_symlinks, [view] certificates .... , config_changes, rollback)

The first 4, A-D, are 4 modes that work on certs with the CA server. 
E) does account management.
F) does local cert and server config management 

In principle, F) consists of two parts: manage certs and manage server configs [both .locally]. I am not sure if separating makes it more clear or not.

I think this classification and separation makes a much clearer picture for anybody who starts using certbot. And I think it makes my responses above to @ohemorange 's questions about `modify` vs. `renew` clear (yet without any specific explanations), right? And  it becomes clear why "modify" does not really need a confirmation for non-expiring certs (well, because you asked to **modify**).

This classification/separation helps clearing all sort of confusions or ambiguities. E.g., do you need `renew` with --lineage, if you want to remove one of the domains from the existing cert? (Or should it be nothing, because _nothing_ implicitly stands for `run`?)
[Whoever was the author of the initial cli with `renew`, `run`, please don't take it wrong: What you've done is great. I am just trying to share with you what most of the core team have never experienced: how the current cli looks to people learning about certbot from scratch.)]

I have more thoughts on this, but let me stop here for now,
I'd like to hear feedback on what I described above, and I would be happy to address questions if any.

**Comment by ppKrauss** [comment]
This issue seems duplicate. See also:

* "Implement 'rm_domain' or 'remove_domain' subcommand" at #4352 <br/>(there are some advances in algorithm discussion)

* similar discussion, about add/remove (add ~ expand), at  #4052, implemented at [pull/4053](https://github.com/certbot/certbot/pull/4053)  and [pull/4055](https://github.com/certbot/certbot/pull/4055).

**Comment by MichaelHierweck** [comment]
What is *today* the recommended ways of altering the set of SANs (which implies a new cert will be issued)?

a) adding a SAN
b) removing a SAN

(I tried it out and I didn't figure out a difference between using --expand certonly and certonly along with the designated set of SANs. Even --expand managed to remove SANs.)

**Comment by SwartzCr** [comment]
Hi @MichaelHierweck - we're documenting that currently, but you'll find the information you need about the `--expand` and `--cert-name` commands in this thread: https://github.com/certbot/certbot/issues/4660

**Comment by gregorg** [comment]
Will you implement a way to remove a SAN ? acmetool did it with "unwant" command but I do not look inside the way they did it.

**Comment by bmw** [comment]
@gregorg, you can do this currently with `--cert-name <cert name to update> --domains <comma delimited list of domains you want in the cert>`. There's some ideas in this issue which we may implement in the future to make this less verbose though.

**Comment by gregorg** [comment]
@bmw we can't do that for renewal, it's really annoying, I have to handle manually each failed certificats to renew...

**Comment by bmw** [comment]
@gregorg, I'm not sure I understand the problem. Do you have multiple certificates containing a domain and you want to remove that domain from all certificates?

**Comment by gregorg** [comment]
I have certificates with many SAN and want to remove 1 SAN at renewal when this SAN doesn't exists anymore.

**Comment by bmw** [comment]
If the domain you want to remove is in the SANs for many certificates, you currently either have to remove it individually using a command like the one I described above or you could set `--allow-subset-of-names` on the command line which will cause domains you cannot complete validation for to be automatically dropped from the certificate. A flag like `--allow-subset-of-names` must be used with caution though as you don't want names you expected to be able to successfully complete validation for to be dropped from the certificate.

There are other options discussed in this issue which we could implement in the future and we'll take a look at what `acmetool` did with "unwant" as you suggested.

**Comment by ppKrauss** [comment]
Hi, some news here?  The solution is to use `certbot-auto`?  ([example](https://stackoverflow.com/a/43750270/287948)).

PS:  @ohemorange, after [your comment](#issuecomment-289148271) about  `--add-domain`, some implementation?

**Comment by ohemorange** [comment]
Getting back around to this:

I think the cleanest, simplest thing to do here is to add the `--add-domain` and `--remove-domain` flags (perhaps with alternate plural forms) to take a comma-separated list of domains. They must be called with `renew --cert-name <certname>`. Adding either of these flags should set `--force-renew` to `True`.

**Comment by ohemorange** [comment]
Since we've had `--cert-name`, we haven't really seen requests for this come up much anymore, so I'm closing this issue.
