### ISSUE TITLE
 Dashes causing trouble generating certs

### ISSUE THREAD

**Issue by greg1988** [certbot/certbot#4411]
## My operating system is (include version):
Ubuntu 14.04.5 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
**Command:**
`/etc/scripts/certbot-auto certonly -a webroot --webroot-path=/etc/letsencrypt/live/ --keep-until-expiring --no-self-upgrade --agree-tos --force-renewal --non-interactive  -d "--leadingdashes.com" 2>&1`

**Response:**
"certbot: error: argument -d/--domains/--domain: expected one argument"

Also 
**Command:**
`/etc/scripts/certbot-auto certonly -a webroot --webroot-path=/etc/letsencrypt/live/ --keep-until-expiring --no-self-upgrade --agree-tos --force-renewal --non-interactive  -d "dash-.nexttoperiod.com" 2>&1`

**Response:**
"The request message was malformed :: Invalid character in DNS name"

## Certbot's behavior differed from what I expected because:
I do not control these domains but I would expect the test to execute and fail after my system is able to prove control over the domains (I have also tried with domains I control and got the same errors)

The pattern that I am seeing is that if the url contains leading dashes it seems to be interpreted as a command flag

OR 

If the url contains dashes that are next to a period, the command fails saying there was an invalid character.

**Comment by SwartzCr** [comment]
Hmm this seems like a problem with argparse - @bmw any idea how we'd fix this?
Is there a way that argparse wants us to be escaping these characters?

**Comment by osirisinferi** [comment]
> If the url contains dashes that are next to a period, the command fails saying there was an invalid character.

Dashes/hyphens at the "outside" of labels are prohibited according to [RFC 1035](https://tools.ietf.org/html/rfc1035#section-2.3.1):

> The labels must follow the rules for ARPANET host names.  They must start with a letter, end with a letter or digit, and have as interior characters only letters, digits, and hyphen.

Although [later](https://tools.ietf.org/html/rfc2181#section-11), the application of DNS was widened (including binary), this probably wouldn't be the case for the use of hostnames, like in the PKIX system.

**Comment by greg1988** [comment]
Hey guys thanks for the help. So starting with leading dashes:

I ran

`/etc/scripts/certbot-auto certonly -a webroot --webroot-path=/etc/letsencrypt/live/ --keep-until-expiring --no-self-upgrade --agree-tos --force-renewal --non-interactive  -d -- "--leadingdashes.com" 2>&1`

I also ran:

`/etc/scripts/certbot-auto certonly -a webroot --webroot-path=/etc/letsencrypt/live/ --keep-until-expiring --no-self-upgrade --agree-tos --force-renewal --non-interactive  -d -- --leadingdashes.com 2>&1`

Both cases did indeed fail in the same manner (certbot: error: argument -d/--domains/--domain: expected one argument) :(

I notice that it comes back to me in either case saying “requesting root privileges to run certbot…” then printing out the command I give it without the quotes around the domain.

----

Anyways for dashes next to a period: I looked over that section in RFC 1035 that you linked. The restriction on dashes being internal does make sense, however I'll cite this example:

http://--photography1234--.awesomeimages.us

This is a working domain (the one that caused us to find this error) and it violates the rule you stated as I understand it. Is there something I'm missing?

Again really appreciate the help

**Comment by osirisinferi** [comment]
> Anyways for dashes next to a period: I looked over that section in RFC 1035 that you linked. The restriction on dashes being internal does make sense, however I'll cite this example:
> 
> http://--photography1234--.awesomeimages.us
> 
> This is a working domain (the one that caused us to find this error) and it violates the rule you stated as I understand it. Is there something I'm missing?

It could be other (more recent) RFC's have lifted some restrictions. Or the DNS servers used aren't RFC compliant.

**Comment by greg1988** [comment]
Ok we've decided that we will not be supporting domains with this format (since they are far edge cases)

If you guys determine that RFC has lifted that restriction and that you should accommodate these urls I'll be around to run some tests if needed.

Thanks for all the great work you guys do!

**Comment by SwartzCr** [comment]
OK
Thanks for opening the issue @greg1988 and thanks for the RFC citation @osirisinferi 
I'm going to close this, but feel free to open new issues if you run into any more problems!
