### ISSUE TITLE
`manual` plugin not available when running `certonly` without other options

### ISSUE THREAD

**Issue by osirisinferi** [certbot/certbot#4414]
## My operating system is (include version):
Gentoo, profile 13.0

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager "Portage".

## I ran this command and it produced this output:
    `certbot certonly`

> How would you like to authenticate with the ACME CA?
> -------------------------------------------------------------------------------
> 1: Apache Web Server plugin - Beta (apache)
> 2: Place files in webroot directory (webroot)
> 3: Spin up a temporary webserver (standalone)
> -------------------------------------------------------------------------------
> Select the appropriate number [1-3] then [enter] (press 'c' to cancel): 
> 

## Certbot's behavior differed from what I expected because:

The `manual` plugin is missing.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

> Multiple candidate plugins: * apache
> Description: Apache Web Server plugin - Beta
> Interfaces: IAuthenticator, IInstaller, IPlugin
> Entry point: apache = certbot_apache.configurator:ApacheConfigurator
> Initialized: <certbot_apache.configurator.ApacheConfigurator object at 0x7f9e0b8d0890>
> Prep: True
> 
> * webroot
> Description: Place files in webroot directory
> Interfaces: IAuthenticator, IPlugin
> Entry point: webroot = certbot.plugins.webroot:Authenticator
> Initialized: <certbot.plugins.webroot.Authenticator object at 0x7f9e0b87f350>
> Prep: True
> 
> * standalone
> Description: Spin up a temporary webserver
> Interfaces: IAuthenticator, IPlugin
> Entry point: standalone = certbot.plugins.standalone:Authenticator
> Initialized: <certbot.plugins.standalone.Authenticator object at 0x7f9e0b87fed0>
> Prep: True
> 
> How would you like to authenticate with the ACME CA?

Manually selecting the `manual` plugin with `-a manual` works like a charm.. Expected behaviour: possibility to choose the `manual` plugin without specifying `-a`.

**Comment by SwartzCr** [comment]
Do you know which version of Certbot this was? Is it still occurring for you?

**Comment by bmw** [comment]
This was done on purpose because the interactive UI for using the manual plugin is pretty bad right now and if you're using the manual plugin without setting manual hooks on the command line, you're probably going to have a bad time because you need to manually renew the certificate every 3 months which is pretty counter to the goals of Certbot/Let's Encrypt.

Since we purposefully are hiding the manual plugin like this, I'm closing this issue as wontfix, but if you think I should reconsider, feel free to comment explaining why and I'll consider reopening it.
