### ISSUE TITLE
Python-augeas pinning

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4424]
We should investigate this before releasing 0.13.0. If distros are successfully packaging `python-augeas` 1.0, we make sure Certbot still works with that version (once it's installed) and move our pinning to `tools/venv.sh` or modify `certbot-auto` so the necessary dependencies are installed.

**Comment by bmw** [comment]
@erikrose and @ohemorange this is related to the IRC conversation I haven't responded to yet.

**Comment by erikrose** [comment]
See #4433 for a writeup of the results of that conversation.
