### ISSUE TITLE
How to create SSL for IP:3030?

### ISSUE THREAD

**Issue by lautiamkok** [certbot/certbot#4428]
I have an ExpressJS app that is running on an IP address only at port 3030.

How can I create the SSL cert and key for this type of address?

I tried with:

`$ certbot certonly --standalone --email test1@yahoo.co.uk -d 127.0.1.1:3030`

I get this error:

`Requested domain 127.0.1.1:3030 is not a FQDN`

Any ideas?

**Comment by zjs** [comment]
Let's Encrypt, the Certificate Authority (CA) Certbot uses by default, and similar CAs [don't allow creation of certificates for IP addresses](https://community.letsencrypt.org/t/certificate-for-public-ip-without-domain-name/6082/25). To get an SSL certificate through Let's Encrypt, you'll need a domain name. To get an SSL certificate for an IP address, you would have to use a different CA.

In case you weren't just using it as an example: 127.0.1.1 is a [loopback address](https://tools.ietf.org/html/rfc5735#section-4), so the [baseline requirements](https://cabforum.org/wp-content/uploads/CAB-Forum-BR-1.3.0.pdf) which apply to all CAs would prohibit issuing a certificate for that address.

**Comment by jsha** [comment]
Yep, what @zjs says is correct. If you have further questions, please start a thread at https://community.letsencrypt.org/new-topic. Thanks!
