### ISSUE TITLE
What is the official docker hub image name?

### ISSUE THREAD

**Issue by chrissound** [certbot/certbot#4429]
I don't see it listed anywhere, can't seem to find it on google.

**Comment by zjs** [comment]
The official image is [certbot/certbot](https://hub.docker.com/r/certbot/certbot/) (per [this comment](https://github.com/certbot/certbot/issues/492#issuecomment-286522268)).

This should probably be added to the documentation.

**Comment by SwartzCr** [comment]
Our documentation seems to mention this in the command it suggests:
```
sudo docker run -it --rm -p 443:443 -p 80:80 --name certbot \
            -v "/etc/letsencrypt:/etc/letsencrypt" \
            -v "/var/lib/letsencrypt:/var/lib/letsencrypt" \
            certbot/certbot certonly
```
Do you think that's sufficient @zjs ?

**Comment by SwartzCr** [comment]
I'm closing this since certbot/certbot is in our documentation, and is the first google hit, and no one else has had an issue with this since march
