### ISSUE TITLE
Command line arguments not working correctly in 0.12 but does in 0.9.3

### ISSUE THREAD

**Issue by chrissound** [certbot/certbot#4431]
```
sudo docker run --rm -v $pwd/dataStatic/nginx/:/var/www/html/public/ -it certbot/certbot "certonly --webroot -w /var/www/example/ -d www.example.com -d example.com -w /var/www/other -d other.example.net -d another.other.example.net"
usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
cert. 
certbot: error: unrecognized arguments: certonly --webroot -w /var/www/example/ -d www.example.com -d example.com -w /var/www/other -d other.example.net -d another.other.example.net
```
Which is version 0.12, I found the `certonly --webroot -w /var/www/example/ -d www.example.com -d example.com -w /var/www/other -d other.example.net -d another.other.example.net` directly from https://certbot.eff.org/docs/using.html#certbot-commands

This appeared to work fine in 0.9.3

**Comment by chrissound** [comment]
This does work if I use something like `docker exec $containerName /bin/sh -c "certbot certonly --webroot --webroot-path /var/www/html/public/ -d $domain -m $email --agree-tos -n"`

Not too sure why though

**Comment by SwartzCr** [comment]
That is confusing. `-w` should work, at least it's still in our docs. @bmw any idea what might be causing this? Do you think the order matters at all?

**Comment by bmw** [comment]
The quotes around the arguments to the Docker image cause it to be treated as one long command line argument to Certbot. Removing the quotes should solve the problem.

**Comment by SwartzCr** [comment]
@chrissound have you been able to get it working?

**Comment by adferrand** [comment]
This issue has not been updated for a long time, and concerns a very old version of Certbot. So I assume it is solved, or not relevant anymore. If not, do not hesitate to reopen an issue with updated info about its context.
