### ISSUE TITLE
Shiny Server and NodeJS

### ISSUE THREAD

**Issue by lautiamkok** [certbot/certbot#4436]
I wonder if we can use certbot for apps that are running on Shiny Server and NodeJS?

Any reliable guide available for configuring these servers? I have these apps in Arch Linux and this is the guide I found https://wiki.archlinux.org/index.php/Let%E2%80%99s_Encrypt

But I am a bit confused as it says:

> The webserver must be started and accepting HTTP traffic on port 80.

My apps are on the port 3838 (Shiny app) and 3000 (ExpressJS/ NodeJS app).

**Comment by SwartzCr** [comment]
Hi @lautiamkok !
So that note in the Arch Linux guide refers specifically to the webroot challenge.
For certbot to get you a certificate from Let's Encrypt it can perform any one of three challenges. Once you have that certificate you can use whatever you like to serve it (such as Shiny Server or a Node JS Server).
If you don't have a webserver occupying port 80 or 443 on your server you might try the `standalone` command. If you have something like apache running in front of your shiny server you could use the `apache` command, or if you are hosting things on port 80, the `webroot` command might actually be right for you.
You can read more about these commands here: https://certbot.eff.org/docs/using.html#certbot-commands
Once you use one of these to obtain a certificate you'll have to figure out how Shiny or Node would like you to serve them. Feel free to let me know how it goes here, or you're also welcome to come chat in #letsencrypt on irc.freenode.net if you want more interactive/hands on help!

**Comment by lautiamkok** [comment]
Hi @SwartzCr,

I have a WordPress website running on port 80 by default. The Shiny server is independent from Apache. 

My WordPress website is on HTTPS already so I need HTTPS for our Shiny and NodeJS apps. I am loading these apps into the two separate WP pages via iframe.

Since the WP webiste is on HTTPS so must be the iframe content or I will get the mixed-content error.

How can we join #letsencrypt on irc.freenode.net? Is it this link to go for https://webchat.freenode.net/?

**Comment by lautiamkok** [comment]
By the way, can I create the certificates through my localhost (Ubuntu) then uploaded them to the production server (Arch)?

**Comment by SwartzCr** [comment]
As long as the certificate that you generate is for the domain name that you want to host it on, it will work.
This means that if you use the Apache plugin for certbot on your WP server you'll probably be able to correctly make a certificate for your shiny server app - as long as they share a domain. But unfortunately you probably won't be able to generate it on your local host, as the DNS for your domain name probably doesn't point to the IP address of your local machine.
That link should work - feel free to ping me (swartzcr) in that channel once you join

**Comment by lautiamkok** [comment]
@SwartzCr thanks. Will get on to that. I just realised that there is no app occupying port 80 or 443. The WordPress site is on another webserver actually. 

The Shiny app is on port 3838 (but it is accessed over a subdomain, eg. http://openair.my-wordpress-site.com - no idea how this subdomain got here!)

The Node app is on port 3000 (it is accessed over an ip with :3000, eg http://127.0.1.1:3000)

I will need to find out more info before pinging you there.

**Comment by lautiamkok** [comment]
@SwartzCr there is no domain name associated with the IP address at Linode yet where host our Shiny and Node apps.

We are planning to get a domain name and have it pointed it to Linode's nameservers, but I notice that many registrars offer SSL certs, eg. https://www.123-reg.co.uk/ssl-certificates/, so do we still need  cetbot to generate the certs if we get the SSL domain name at, eg. reg-123?

**Comment by lautiamkok** [comment]
I have a domain name pointed to our server at Linode and I have run the command below:

```
$ sudo certbot certonly --standalone -d example.co.uk -d www.example.co.uk
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Obtaining a new certificate
Performing the following challenges:
tls-sni-01 challenge for example.co.uk
tls-sni-01 challenge for www.example.co.uk
Waiting for verification...
Cleaning up challenges
Generating key (2048 bits): /etc/letsencrypt/keys/0000_key-certbot.pem
Creating CSR: /etc/letsencrypt/csr/0000_csr-certbot.pem

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/example.co.uk/fullchain.pem. Your cert
   will expire on 2017-07-03. To obtain a new or tweaked version of
   this certificate in the future, simply run certbot again. To
   non-interactively renew *all* of your certificates, run "certbot
   renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le
```

What should I go from here next then?

I don't see the HTTPS working when I access the server with https://example.co.uk/

What I get is the page of:

> This site can’t be reached

**Comment by lautiamkok** [comment]
Following this guide for my nodejs app https://startupnextdoor.com/how-to-obtain-and-renew-ssl-certs-with-lets-encrypt-on-node-js/

I have added the code below in my bin/www:

```
this.express = require('express');  
this.app = this.express();

var http = require('https');  
var fs = require('fs');

var sslPath = '/etc/letsencrypt/live/yourdomain.example.com/';

var options = {  
    key: fs.readFileSync(sslPath + 'privkey.pem'),
    cert: fs.readFileSync(sslPath + 'fullchain.pem')
};

this.server = http.createServer(options, this.app);  
this.io = require('socket.io').listen(this.server);  
this.server.listen(443); 
```

But I get an error:

```
www-0 (err):     at Object.fs.openSync (fs.js:634:18)
www-0 (err):     at Object.fs.readFileSync (fs.js:502:33)
www-0 (err):     at Object.<anonymous> (/usr/local/chroot/my-express-app/bin/www:140:13)
www-0 (err):     at Module._compile (module.js:541:32)
www-0 (err):     at Object.Module._extensions..js (module.js:550:10)
www-0 (err):     at Module.load (module.js:458:32)
www-0 (err):     at tryModuleLoad (module.js:417:12)
www-0 (err):     at Function.Module._load (module.js:409:3)
www-0 (err):     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
www-0 (err): Error: EACCES: permission denied, open '/etc/letsencrypt/live/citizensense.co.uk/privkey.pem'
www-0 (err):     at Error (native)
www-0 (err):     at Object.fs.openSync (fs.js:634:18)
www-0 (err):     at Object.fs.readFileSync (fs.js:502:33)
www-0 (err):     at Object.<anonymous> (/usr/local/chroot/my-express-app/bin/www:140:13)
www-0 (err):     at Module._compile (module.js:541:32)
www-0 (err):     at Object.Module._extensions..js (module.js:550:10)
www-0 (err):     at Module.load (module.js:458:32)
www-0 (err):     at tryModuleLoad (module.js:417:12)
www-0 (err):     at Function.Module._load (module.js:409:3)
www-0 (err):     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
```

I even have changed the folder permissions:

`sudo chmod -R 777 /etc/letsencrypt/live/example.co.uk/`

**Comment by SwartzCr** [comment]
So, you will need a domain name for the service that you want an SSL cert for, certbot can't get you a certificate if you don't have a domain associated with the IP address
That said, once you get the domain name you're welcome to go with another Certificate Authority besides Let's Encrypt, and another certificate generation method than Certbot, though if you choose to go that route we won't be able to provide much support (but maybe you want need it!)
If that's the case, feel free to close this ticket :D

**Comment by lautiamkok** [comment]
@SwartzCr thanks. 

I managed to get HTTPS for the nodejs app following this guide https://startupnextdoor.com/how-to-obtain-and-renew-ssl-certs-with-lets-encrypt-on-node-js/

But I can't get HTTPS running for my Shiny app. Any guides around?

**Comment by SwartzCr** [comment]
I don't have any specific knowledge on this, but a quick googling turned up this: https://www.r-bloggers.com/shiny-https-securing-shiny-open-source-with-ssl/
It's a bit complicated, but if you start at part 5 - it might be simple enough. Basically it suggests you use apache to handle the https, and then do forwarding between apache and shiny

**Comment by SwartzCr** [comment]
oh, and I'm going to close this issue - since it seems like you were able to get a cert :)
But I bet you could get some good help in the IRC room (or maybe the shiny support channel) if you continue to have trouble getting https to work

**Comment by lautiamkok** [comment]
@SwartzCr Thanks for link. Seen that already. Got it sorted with Nginx server instead. Shiny open source does not support SSL unless you are using the Pro version.

So using Nginx is a hack - by redirecting a port to Shiny's, eg:

```
server {
        listen 8888 ssl;
        server_name xxx.co.uk www.xxx.co.uk;

        ssl_certificate /etc/letsencrypt/live/xxx.co.uk/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/xxx.co.uk/privkey.pem;

        location ~ /.well-known {
            allow all;
        }

        location / {
                proxy_set_header   X-Real-IP $remote_addr;
                proxy_set_header   Host      $http_host;
                proxy_pass         http://127.0.0.1:3838;
        }

    }
```

**Comment by SwartzCr** [comment]
sweet - glad you got it working :D
