### ISSUE TITLE
Should be able to make multiple selections in certificate manager

### ISSUE THREAD

**Issue by joohoi** [certbot/certbot#4438]
## I ran this command and it produced this output:
certbot delete

## Certbot's behavior differed from what I expected because:
I was prompted a list of certificates that are handled by Certbot. I expected to be able to select multiple certificates for removal at once, as is the fact in other such lists inside Certbot (domain selection inside Apache plugin for example). The usual behaviour is to be able to select multiple selections separated by comma or space. This UI didn't allow me to do this, but would only accept a single selection per run.

**Comment by SwartzCr** [comment]
assigning this to @ohemorange who is probably most knowledgeable about this

**Comment by SwartzCr** [comment]
@ohemorange does this belong in a milestone? Would you like to be unassigned to this?

**Comment by ohemorange** [comment]
I can take this.
