### ISSUE TITLE
Travis CI vs. Circle CI Tracking Issue

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#4439]
To be updated with pros/cons/comparisons.

**Comment by ohemorange** [comment]
Motivation: a series of Travis outages, including Github integration problems.

CircleCI supports only 2 versions of Ubuntu for free (12.04 & 14.04) and MacOS as a paid part
Travis can run Linux and Mac tests at the same time
Travis has a build matrix (but tox, which we already use, would do this on CircleCI)

Drone is an open-source CI that appears to be more for running yourself than on cloud infra. It has a GitHub integration though. We could set it up ourselves on a digitalocean instance, but that's more things to support ourselves.

Circle CI:
Free for 1 job, 1 container, then +$50 / container.
So that would be $450 at the current level, at-cost.

Travis:
Free for open source projects
$129/m for 2 concurrent builds
$249/m for 5 concurrent builds
$489/m for 10 concurrent builds
We might be paying to get more builds for our open source project though? I can't find anywhere where it says how many builds open source projects get, anyone know?

Travis might be faster, based on one person's test.

Travis is roughly double as popular: https://stackshare.io/stackups/travis-ci-vs-circleci-vs-jenkins

Searching for "resolved:" on the status twitter accounts:
Travis: 49 incidents this year
CircleCI: 17 incidents this year

**Comment by ohemorange** [comment]
CircleCI lets you ssh into your builds

**Comment by ohemorange** [comment]
[This post](https://www.itcentralstation.com/product_reviews/travis-ci-review-32073-by-ben-dougherty) claims identical build times for Circle and Travis.

**Comment by bmw** [comment]
There's a minor benefit from Travis which we're not using yet. AFAICT, you have to pay for Linux and OS X containers as separate things from Circle CI. In Travis, this is not the case and you just get N containers which you can use for whatever you want. We've wanted to set up OS X testing for a while, but found that Certbot had some issues on the system.

**Comment by bmw** [comment]
After talking about this, we renewed our Travis service through October of this year. If we want to switch to Circle CI, we should try it using their [free open source containers](https://circleci.com/pricing/#faq-section-linux) and see what we think.

**Comment by bmw** [comment]
I'm closing this issue in favor of our internal one.
