### ISSUE TITLE
Renew fails, even with --allow-subset-of-names

### ISSUE THREAD

**Issue by nhathaway** [certbot/certbot#4452]
## My operating system is (include version):
Ubuntu 14.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
/usr/local/sbin/certbot-auto renew --post-hook=/etc/letsencrypt/renew-hook.sh --allow-subset-of-names

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/XXXXX.com.conf
-------------------------------------------------------------------------------
Cert is due for renewal, auto-renewing...
Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for XXXXX.com
tls-sni-01 challenge for mail.XXXXX.com
tls-sni-01 challenge for www.XXXXX.com
Cleaning up challenges
Attempting to renew cert from /etc/letsencrypt/renewal/XXXXX.com.conf produced an unexpected error: Cannot find a VirtualHost matching domain mail.XXXXX.com.. Skipping.

## Certbot's behavior differed from what I expected because:
I expected it to ignore the fact that mail.XXXXX.com is not served using nginx and to renew anyway. I used certbot-auto to set up this arrangement without error, so surely it should renew without error?

**Comment by SwartzCr** [comment]
Are you saying that it didn't successfully renew for XXXXX.com?
Could you attach the relevant certbot log? that'd be super helpful for figuring out where it's getting ahead of itself and erroring out

**Comment by nhathaway** [comment]
Here is the log:

[letsencrypt.log.txt](https://github.com/certbot/certbot/files/895331/letsencrypt.log.txt)

Correct: it failed to renew.

**Comment by nhathaway** [comment]
In the end, in order to get the certificates to renew, I had to stop nginx and use standalone mode for certbot. Obviously, on a live server (which this is) this is something you don't want to do.

Note that the sub-domain mail.XXXXX.com is not used by the web server, but is used by postfix/dovecot.

**Comment by SwartzCr** [comment]
Hmm - so it seems like it's checking for the vhost for each domain for every one of the domains in your list, and so each one fails since it can't find the mail.XXXX.com vhost. @ohemorange did the most work on the nginx code, so maybe she has some insight?

**Comment by ohemorange** [comment]
I don't think this is an Nginx-specific bug, since "failed to find a vhost for this domain" raises the same error in both Nginx and Apache. I'm less familiar with (read: I have never before seen) the parts of the code where this is likely to actually be, but I can look into it anyway.

**Comment by ohemorange** [comment]
@nhathaway, for your specific use case: if you use the Nginx plugin, it assumes that you want to use Nginx to authorize every domain contained in the cert. `--allow-subset-of-names`, if it didn't error out, would just drop the mail subdomain from the cert and successfully renew with the remainder of the domains.

I would recommend getting two different certs, one just for the mail that's renewed using standalone, and one with every subdomain that you use within Nginx.

It's hard for us to generically add functionality to authorize a domain that Nginx doesn't know about at all (where there's no server block that could possibly match that subdomain), because we use your server settings like port number to know how we should talk to that specific subdomain.

**Comment by ohemorange** [comment]
Additionally, I think the best way to fix this specific bug is to deprecate this flag: see #4470.

I'm closing this issue in favor of the other; @nhathaway, please let us know if this doesn't fix things for you, and thanks for the report!

**Comment by nhathaway** [comment]
@ohemorange : your suggestion of having different certificates doesn't solve the problem. You still have to stop nginx to run the standalone server to renew mail.XXXXX.com, and so you may as well renew the single certificate that way.

The problem is that this is a live server, and that doing it this way causes a potentially unacceptable outage of the web service.

What would be a lot better is if the standalone method didn't have to use port 443, and could use a port not used by any of the standard services.

**Comment by ohemorange** [comment]
Good point. Here are some other options:

- Create a server block with `server_name mail.XXXXX.com`, and have it return an error. Then the plugin will be able to find a matching server block, and will authorize correctly.
- Create a default matching server block with `server_name *.XXXXX.com`. Then the plugin will be able to find a matching server block, and will authorize correctly.
- Use the DNS challenge type for that subdomain.

Unfortunately, the ACME spec doesn't allow for using other ports.
