### ISSUE TITLE
storage.py config inputs via command line in client

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#446]
Right now it is hard to configure on the command line the variables that `storage.py` will use to decide things like where to save certs.  (They can be configured via a configuration file, but not on the command line.)  We should integrate the configuration of the renewal store with the regular command-line configuration.

This is tricky because the renewal-related code all uses `configobj`, while the client CLI uses `configargparse`.  They don't really have the same model of how to define or represent options.

**Comment by kuba** [comment]
Partially fixed in #473.

**Comment by boldandbusted** [comment]
Howdy. Has this been satisfactorily resolved by the fix mentioned by @kuba ? And possibly #447 and #469 ? If yes, should this be closed? Cheers.

**Comment by SwartzCr** [comment]
I believe this is resolved now, with flags like --config-dir and --cert-path
Closing as resolved, but feel free to re-open if you disagree
