### ISSUE TITLE
Cannot find Apache control command apache2ctl on Arch Linux

### ISSUE THREAD

**Issue by lautiamkok** [certbot/certbot#4461]
I have this problem when using certbot for apache following this guide http://letsencrypt.readthedocs.io/en/latest/using.html#apache

```
$ sudo certbot --apache
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Failed to find apache2ctl in expanded PATH: /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/sbin
The apache plugin is not working; there may be problems with your existing configuration.
The error was: NoInstallationError('Cannot find Apache control command apache2ctl',)
```
I am on Arch Linux, and it seems that there is no apache2ctl for Arch but certbot requires it?

I tried to installed it but no luck:

```
$ sudo pacman -S apache2
error: target not found: apache2
```

My Apache's version:

```
$ httpd -v
Server version: Apache/2.4.25 (Unix)
Server built:   Dec 20 2016 13:02:2
```

**Comment by yan12125** [comment]
Apparently the Apache plugin is not officially supported on Arch Linux. I have a patch for that but I'm not sure whether it's completely correct or not. Check out https://github.com/yan12125/certbot/commit/ab22efe1093b8f730246331081160059c095bdcb

**Comment by SwartzCr** [comment]
Maybe @joohoi can provide more info

**Comment by joohoi** [comment]
@yan12125 that looks correct from the Certbot point of view. Not sure about Arch, but I can test it out. Want to submit a PR? We would be happy to have Arch Linux specific constants in the certbot-apache.

**Comment by yan12125** [comment]
Here it is :) #4466

**Comment by daviddavo** [comment]
I'm having the same problem, but using arch

**Comment by yan12125** [comment]
@daviddavo: The issue should have been fixed for Arch since certbot version 0.16.0. Did you install all of apache, certbot and certbot-apache from official repositories?

Pasting full output of your certbot command will be helpful on diagnosing, too.

**Comment by ShapeShifter499** [comment]
@daviddavo I'm running Arch Linux and this appears to work just fine for me

**Comment by daviddavo** [comment]
Working for me on Manjaro, sorry for not posting the logs before
