### ISSUE TITLE
Debian 8 installation fails - unmet dependencies

### ISSUE THREAD

**Issue by iggs0** [certbot/certbot#4465]
## My operating system is (include version):
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.7 (jessie)
Release:	8.7
Codename:	jessie
Linux xxx 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS Package - Backports

## I ran this command and it produced this output:
##Sources list
root@xxx:~# cat /etc/apt/sources.list
deb http://ftp.de.debian.org/debian/ jessie main
deb-src http://ftp.de.debian.org/debian/ jessie main
deb http://security.debian.org/ jessie/updates main
deb-src http://security.debian.org/ jessie/updates main
deb http://ftp.de.debian.org/debian/ jessie-updates main
deb-src http://ftp.de.debian.org/debian/ jessie-updates main
deb http://ftp.debian.org/debian jessie-backports main

## update apt
root@ xxx:~# apt update
Hit http://security.debian.org jessie/updates InRelease
Ign http://ftp.de.debian.org jessie InRelease                          
Hit http://ftp.debian.org jessie-backports InRelease                   
Hit http://ftp.de.debian.org jessie-updates InRelease                  
Hit http://ftp.de.debian.org jessie Release.gpg   
Hit http://security.debian.org jessie/updates/main Sources             
Hit http://ftp.de.debian.org jessie Release                            
Hit http://security.debian.org jessie/updates/main amd64 Packages                         
Get:1 http://ftp.debian.org jessie-backports/main amd64 Packages/DiffIndex [27.8 kB]      
Hit http://security.debian.org jessie/updates/main Translation-en                                    
Get:2 http://ftp.debian.org jessie-backports/main Translation-en/DiffIndex [27.8 kB]                 
Hit http://ftp.de.debian.org jessie-updates/main Sources                                                  
Get:3 http://ftp.de.debian.org jessie-updates/main amd64 Packages/DiffIndex [7,408 B]
Get:4 http://ftp.de.debian.org jessie-updates/main Translation-en/DiffIndex [2,704 B]
Hit http://ftp.de.debian.org jessie/main Sources
Hit http://ftp.de.debian.org jessie/main amd64 Packages
Hit http://ftp.de.debian.org jessie/main Translation-en
Hit http://ftp.de.debian.org jessie/main Translation-de
Fetched 65.7 kB in 2s (24.6 kB/s)       
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.

## INSTALL CERBOT
root@xxx:~# apt-get install certbot python-certbot -t jessie-backports -f
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-certbot : Depends: python-acme (>= 0.9.3) but it is not going to be installed
                  Depends: python-cryptography (>= 0.7) but 0.6.1-1 is to be installed
                  Recommends: python-psutil (>= 2.2.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

## Certbot's behavior differed from what I expected because:

Fails to install - see above

**Comment by iggs0** [comment]
fixed it.
Deinstalled phyton and dependencies. Used aptitude -t jessie-backports install certbot and selected a solution which installed all dependencies.

**Comment by iggs0** [comment]
sorry not fixed. Now I have broken packages. Some support here would be appreciated
`root@vserver6:~# sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-cffi-backend : Breaks: python-cffi (< 1) but 0.8.6-1 is to be installed
E: Broken packages
`

**Comment by SwartzCr** [comment]
can you do `apt-get install -f`?

**Comment by iggs0** [comment]
Yes. But does not help. It would deinstall cerbot.

```
root@xxx:~# apt-get install 
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 5 nicht aktualisiert.
root@xxx:~# apt-get install -f python-cffi
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  python-chardet python-configargparse python-configobj python-dnspython python-enum34 python-idna python-ipaddress python-mock python-parsedatetime python-pyasn1 python-pyicu python-requests python-rfc3339 python-six python-support python-tz python-urllib3
  python-zope.component python-zope.event python-zope.interface
Verwenden Sie »apt-get autoremove«, um sie zu entfernen.
Die folgenden zusätzlichen Pakete werden installiert:
  python-ply python-pycparser
Vorgeschlagene Pakete:
  python-dev python-ply-doc
Die folgenden Pakete werden ENTFERNT:
  certbot python-acme python-certbot python-cffi-backend python-cryptography python-ndg-httpsclient python-openssl
Die folgenden NEUEN Pakete werden installiert:
  python-cffi python-ply python-pycparser
0 aktualisiert, 3 neu installiert, 7 zu entfernen und 3 nicht aktualisiert.
Es müssen 189 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 2'214 kB Plattenplatz freigegeben.
Möchten Sie fortfahren? [J/n] `

```

**Comment by SwartzCr** [comment]
I think it'd still be useful to do, but also seeing your sources.list file would be helpful here
@hlieberman is more of a debian wizard than I am, so maybe he has better debug advice

**Comment by hlieberman** [comment]
Hm.  Yes, I would still recommend doing the install -f and removing certbot.  I'm a little bit concerned that your system may be in an unhealthy state; it looks like you have half an install right now.

After you do the apt-get install -f and remove certbot, it would be helpful to see the output of `apt-get install -Vst jessie-backports certbot`.

If you'd rather get more synchronous help and could join the #letsencrypt channel on Freenode IRC, feel free to highlight me -- if I'm around, I can help then.

**Comment by iggs0** [comment]
o.k. I performed the install -f and certbot disappears.
```
root@xxx:~$ apt-get install -f python-cffi
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  python-chardet python-configargparse python-configobj python-dnspython python-enum34 python-idna python-ipaddress python-mock python-parsedatetime python-pyasn1 python-pyicu python-requests python-rfc3339 python-six python-support python-tz python-urllib3
  python-zope.component python-zope.event python-zope.interface
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  python-ply python-pycparser
Suggested packages:
  python-dev python-ply-doc
The following packages will be REMOVED:
  certbot python-acme python-certbot python-cffi-backend python-cryptography python-ndg-httpsclient python-openssl
The following NEW packages will be installed:
  python-cffi python-ply python-pycparser
0 upgraded, 3 newly installed, 7 to remove and 3 not upgraded.
Need to get 189 kB of archives.
After this operation, 2214 kB disk space will be freed.
Do you want to continue? [Y/n] Y
Get:1 http://ftp.de.debian.org/debian/ jessie/main python-ply all 3.4-5 [62.9 kB]
Get:2 http://ftp.de.debian.org/debian/ jessie/main python-pycparser all 2.10+dfsg-3 [58.8 kB]
Get:3 http://ftp.de.debian.org/debian/ jessie/main python-cffi amd64 0.8.6-1 [67.2 kB]
Fetched 189 kB in 0s (586 kB/s)   
(Reading database ... 74551 files and directories currently installed.)
Removing certbot (0.10.2-1~bpo8+1) ...
Removing python-certbot (0.10.2-1~bpo8+1) ...
Removing python-acme (0.10.2-1~bpo8+1) ...
Removing python-ndg-httpsclient (0.3.2-1) ...
Removing python-openssl (16.0.0-1~bpo8+1) ...
Removing python-cryptography (1.3.4-1~bpo8+2) ...
Removing python-cffi-backend (1.4.2-2~bpo8+1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Processing triggers for python-support (1.0.15) ...
Selecting previously unselected package python-ply.
(Reading database ... 74211 files and directories currently installed.)
Preparing to unpack .../python-ply_3.4-5_all.deb ...
Unpacking python-ply (3.4-5) ...
Selecting previously unselected package python-pycparser.
Preparing to unpack .../python-pycparser_2.10+dfsg-3_all.deb ...
Unpacking python-pycparser (2.10+dfsg-3) ...
Selecting previously unselected package python-cffi.
Preparing to unpack .../python-cffi_0.8.6-1_amd64.deb ...
Unpacking python-cffi (0.8.6-1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Setting up python-ply (3.4-5) ...
Setting up python-pycparser (2.10+dfsg-3) ...
Setting up python-cffi (0.8.6-1) ...

```




 So I execute the install cerbot 
```
root@vserver6:~# apt-get install -Vst jessie-backports certbot
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 certbot : Depends: python-certbot (= 0.10.2-1~bpo8+1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Help very much appreciated

**Comment by hlieberman** [comment]
Hm.  That's very strange.  Can you please give me the output of `aptitude
install -VDst jessie-backports certbot`?

-- 
Harlan Lieberman-Berg
~hlieberman

**Comment by iggs0** [comment]
Hello Harlan,
appreciate your help very much. This is the output of the requested command:

```
aptitude install -VDst jessie-backports certbot
The following NEW packages will be installed:
  certbot [0.10.2-1~bpo8+1]  python-acme{ab} [0.10.2-1~bpo8+1] (D: python-cryptography, D: python-openssl)  python-certbot{ab} [0.10.2-1~bpo8+1] (D: python-cryptography)  python-cryptography{a} [0.6.1-1+deb8u1] (D: python-openssl)  
  python-openssl{a} [0.14-1] (D: python-certbot, R: python-requests, R: python-urllib3)  
The following packages will be REMOVED:
  python-enum34{u} [1.0.3-1]  python-idna{u} [2.0-3~bpo8+1]  python-ipaddress{u} [1.0.16-1~bpo8+1]  python-support{u} [1.0.15]  
0 packages upgraded, 5 newly installed, 4 to remove and 38 not upgraded.
Need to get 245 kB/479 kB of archives. After unpacking 1956 kB will be used.
The following packages have unmet dependencies:
 python-acme : Depends: python-openssl (>= 0.15) but 0.14-1 is to be installed.
               Depends: python-cryptography (>= 0.8) but 0.6.1-1+deb8u1 is to be installed.
 python-certbot : Depends: python-cryptography (>= 0.7) but 0.6.1-1+deb8u1 is to be installed.
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     certbot [Not Installed]                            
2)     python-acme [Not Installed]                        
3)     python-certbot [Not Installed]                     

cheers iggs
```

**Comment by ravloony** [comment]
@iggs0 You might want to try adding `contrib` to the end of this line in sources.list:

`deb http://ftp.de.debian.org/debian/ jessie main contrib`

That appears to have fixed the issue for me.

**Comment by iggs0** [comment]
@ravloony thanks for replying. I wanted to try - and saw - it is workging now. Somehow self healing.
Very strange. But thanks for your update
