### ISSUE TITLE
Deprecate --allow-subset-of-names

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#4470]

**Comment by ohemorange** [comment]
3:53:25 PM - ericaportnoy: hey does anyone know who wrote --allow-subset-of-names?
3:53:42 PM - ericaportnoy: slash know all the things about how it works
3:54:11 PM - ericaportnoy: specifically, if it fails to pass the challenge for every subdomain on the cert, does it get a cert with the remaining names?
3:56:33 PM - ebe [~eagle@unaffiliated/eagle] entered the room.
4:01:28 PM - schoen: ericaportnoy: I think that's the goal
4:01:36 PM - schoen: ericaportnoy: that is, it gets a cert for the ones where the challenge did pass
4:02:05 PM - ericaportnoy: so, drop the failing one from the cert?
4:02:36 PM - schoen: yes, so you can get a new cert with fewer names than before
4:02:49 PM - schoen: like if you renew an existing lineage with --allow-subset-of-names
4:02:58 PM - schoen: the renewed one can have fewer subject names than the old one did
4:03:16 PM - schoen: there was a question about whether to somehow save an "aspiration" to re-add those in future renewals
4:03:31 PM - schoen: but there's currently nowhere to store that information that would work correctly with "certbot renew"
4:03:45 PM - schoen: so I think the answer is that currently the aspirational names just get dropped permanently
4:03:56 PM - schoen: instead of aspirational names, I should probably call them irredentist names
4:04:05 PM - ericaportnoy: what was the driving use case for this?
4:04:14 PM - schoen: https://en.wikipedia.org/wiki/Irredentism
4:04:42 PM - schoen: ericaportnoy: originally it was pdeee's concern that if you had like 100 names on a cert (maybe for different customers of the same hosting provider or something)
4:04:50 PM - schoen: and one of them failed due to someone not renewing a domain name registration
4:05:02 PM - schoen: it would be bad for everyone else if that resulted in a complete nonrenewal of the cert
4:05:17 PM - schoen: however, this can probably only happen if you're going for a super-high level of automation with a super-low level of potential human intervention
4:05:47 PM - schoen: but I guess the use case is sort of like "we expect some renewals to happen with somewhat inadequate human oversight, and we don't want to break the other things that are part of the same cert as a result" (?)
4:06:39 PM - schoen: I have to say that the painting that illustrates the Wikipedia article on irredentism is super-disturbing to me
4:07:37 PM - schoen: if you have big certs with lots of SANs, and you don't --allow-subset-of-names, then you have a greater likelihood of needing human intervention more early or more often
4:07:52 PM - schoen: especially if the SANs refer to things that are under the effective responsibility of different people
4:07:56 PM - schoen: like different shared hosting customers
4:08:18 PM - ericaportnoy: Do you think anyone is using this in practice who isn't using it as a hack for the functionality that was added with --cert-name?
4:08:20 PM - schoen: but one could also say that this human intervention is necessary and appropriate, and anyway you should get a month's notice
4:08:24 PM - schoen: don't know
4:08:28 PM - ericaportnoy: to intentionally reduce the number of domains on a cert
4:08:35 PM - schoen: I don't think someone has mentioned using it on the forums
4:08:39 PM - schoen: let me search the forums to check on that
4:08:45 PM - ericaportnoy: checking now, so far it seems that way.
4:08:49 PM - schoen: were you thinking of removing it?
4:08:53 PM - schoen: or deprecating it?
4:09:01 PM - ericaportnoy: I'm not super convinced it actually works?
4:09:52 PM - schoen: wow, one person had an unbelievably hacky use for it
4:10:00 PM - schoen: https://community.letsencrypt.org/t/re-installing-server-other-things/28650
4:10:03 PM - ericaportnoy: yeah.
4:10:08 PM - schoen: that is the all-time hackiest use I have ever heard of for any Certbot feature!
4:10:24 PM - schoen: "Do you think it's possible to use same certbot command line on ALL servers (prod & tests), and have different certificates installed, knowing they manage different subdomains ?"
4:10:48 PM - ericaportnoy: https://community.letsencrypt.org/t/relaxed-checks-on-renewal-and-only-with-config-file/25023
4:10:57 PM - ericaportnoy: this person seems to actually want the flag for its intended use
4:11:04 PM - ericaportnoy: yeahhh.
4:11:07 PM - schoen: yeah
4:12:18 PM - ericaportnoy: ok, so except for that one person, who might not have actually been able to use it, every single other instance that mentions it tries to use it to reduce the number of domains on a cert, which you can now do using --cert-name.
4:13:15 PM - ericaportnoy: the flag currently works with standalone, but I'm not super convinced it plays nicely with either apache or nginx plugins
4:13:19 PM - ericaportnoy: nginx we just got a bug for
4:13:38 PM - schoen: yeah, I didn't find anyone else using it for the intended purpose
4:13:54 PM - ericaportnoy: but apache does things like using other virtualhosts when it can't find a perfect one, and creating new ones? not super familiar with what's going on there, but it seems to interact weirdly with this flag.
4:14:00 PM - ericaportnoy: ok cool.
4:14:20 PM - ericaportnoy: it's not urgent and this release is almost done, but for next release I think I'd like to mark it deprecated.
4:15:01 PM - ericaportnoy: because supporting it seems not worth it due to the complexity required to support it, unclear UX, and automagicalness of it in that its behavior isn't precisely specified and obvious.

**Comment by pde** [comment]
I think we agree that this flag is not great. I believe we should replace it with a flag that causes this behaviour to kick in _N_ days before cert expiry, or never.  `N=3` or `never` would be the two plausible defaults. However we certainly should have a design meeting to talk about that.

In the mean time, kicking this issue and trying to collect data about the prevalence of this flag.

**Comment by pde** [comment]
The data came back saying that this flag was fairly widely used (maybe 5% of cerbot certs IIRC)
