### ISSUE TITLE
"Running setup.py install for python-augeas" failing

### ISSUE THREAD

**Issue by kevjs1982** [certbot/certbot#4474]
## My operating system is (include version):
Ubuntu 14.4.1LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Programme letsencrypt-auto (Installed and has been working since December 2015 so can't remember exactly how it was installed)

## I ran this command and it produced this output:
`cd /usr/local/bin/letsencrypt;/usr/local/bin/letsencrypt/letsencrypt-auto --verbose --renew-by-default -a webroot --webroot-path /var/www/html/ --email me@example.com --text --agree-tos -d domain.example.com auth`

```
Installing` collected packages: python-augeas
  Found existing installation: python-augeas 0.5.0
    Uninstalling python-augeas-0.5.0:
      Successfully uninstalled python-augeas-0.5.0
  Running setup.py install for python-augeas ... error
    Complete output from command /root/.local/share/letsencrypt/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Sxj9Hr/python-augeas/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-9sKRoC-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.local/share/letsencrypt/include/site/python2.7/python-augeas:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/augeas
    copying augeas/ffi.py -> build/lib.linux-x86_64-2.7/augeas
    copying augeas/__init__.py -> build/lib.linux-x86_64-2.7/augeas
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-2.7/augeas.c'
    creating build/temp.linux-x86_64-2.7
    building 'augeas' extension
    creating build/temp.linux-x86_64-2.7/build
    creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/libxml2 -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/augeas.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/augeas.o
    build/temp.linux-x86_64-2.7/augeas.c:434:35: fatal error: augeas.h: No such file or directory
                    #include <augeas.h>
                                       ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
  Rolling back uninstall of python-augeas
Command "/root/.local/share/letsencrypt/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Sxj9Hr/python-augeas/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-9sKRoC-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.local/share/letsencrypt/include/site/python2.7/python-augeas" failed with error code 1 in /tmp/pip-build-Sxj9Hr/python-augeas/
```
## Certbot's behavior differed from what I expected because:
Until this week this would have generated a certificate.  Was working fine (for a different domain - name based virtual host) on 27th March, failed on 4th April and each day since.

Have tried running with `--no-self-upgrade` but the same error persists (i.e. it still tries to upgrade then errors)

I've also tried installing the certbot ppa but that encounters an error too "AttributeError: 'module' object has no attribute 'pyopenssl'"

I notice in https://github.com/certbot/certbot/pull/4422/commits/7ddb8fb7bca1101f1811db738afedb5795b7b469 that the setup.py should pin the augeas requirement to 0.5.0 but trying to change that has had no effect

```
/usr/local/bin/letsencrypt# grep augeas */*.py
letsencrypt-apache/setup.py:    'python-augeas'<=0.5.0',
letsencrypt/reverter.py:        Note: this function does not reload augeas.`
```

Does this broken version mean that the updated fixed version from that commit can't be pulled or does a infrequent (weekly?) upgrade check of some description, and I simply need to force that update - if so how?

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
Error output shown above

**Comment by ohemorange** [comment]
This is a known issue that you can resolve by downloading the latest version of `certbot-auto`, available at https://dl.eff.org/certbot-auto, or by installing Certbot using any other method appropriate for your operating system as described on [https://certbot.eff.org/](https://certbot.eff.org/).
