### ISSUE TITLE
How to separate each certificates?

### ISSUE THREAD

**Issue by antoine-pous** [certbot/certbot#4482]
Hi,

i had a small problem with the current certbot's behavior. Currently when i generate my certificates certbot put all the key in the same directory. With that a client can know all my subdomains names.

This is problematic when we have development and live testing vhosts. Each vhost is protected, but if I refuse that the search engines referencing them, it's not for see them listed on the certificate :disappointed: 

I'm looking for a way to get one certificate/fullchain for each vhost like:

```
/etc/letsencrypt/live/domain.tld/my.vhost/
/etc/letsencrypt/live/domain.tld/vhost/
/etc/letsencrypt/live/domain.tld/another.vhost/
```

Can you add something like `--splitted-certs` to do it easily ?

Thank you !

**Comment by ArchangeGabriel** [comment]
When using `renew`, if the certs were split initially they should stay like that.

But if you asked for multiple certificates initially, they were put together indeed. To work around that, read at https://certbot.eff.org/docs/using.html#changing-a-certificate-s-domains.

**Comment by SwartzCr** [comment]
Yup as @ArchangeGabriel said you can modify your existing vhosts. Or you can create new certs for each domain. If you do them separately (listing only one domain under -d for each) they'll stay separate when you renew.
I'm going to close this ticket, but feel free to re-open it if this doesn't work for you, or come chat with us in #letsencrypt on irc.freenode.net

**Comment by antoine-pous** [comment]
I'll try that, but a flag would be really usefull to do this painless.

**Comment by mkormendy** [comment]
I agree .. just make a flag to do that. If domains change on the letsencrypt account then it would automatically just keep them separate.
