### ISSUE TITLE
renew-hook output from the command run by it

### ISSUE THREAD

**Issue by zzz2002** [certbot/certbot#4487]
## I installed Certbot with (certbot-auto, OS package manager, pip, etc): 
Aptitude, certbot version 11.1-1

## I ran this command and it produced this output:
certbot --renew --staging --force-renewal --cert-name imap.klam.ca --renew-hook /root/CertbotTLSAgen

Produced the standard output on the terminal. 
I cannot copy output as certbot is running on my server which I can only get to via ssh.

## Certbot's behavior differed from what I expected because:
My hook code outputs progress and info messages to stdout as well as to a log file/var/log/tlsagen.log
Running my code standalone I get all messages both on the terminal and in the log.
Running from certbot renew-hook all stdout messages are dropped

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
There are no messages in the log, other than: 

Running renew-hook command: /root/CertbotTLSAgen
DEBUG:certbot.renewal:no renewal failures
... post-hook command: /bin/run-parts /etc/letsencrypt/post-hook.d/

**Comment by SwartzCr** [comment]
Hmm, maybe @bmw knows how stdout is handled with scripts during renew

**Comment by bmw** [comment]
Yeah. Scripts are run [here](https://github.com/certbot/certbot/blob/v0.13.0/certbot/hooks.py#L119), but only `stderr` output is shown to the user. Adding a `logger.info` call with `stdout` output shouldn't be a problem and will be shown to the user as long as `--quiet` isn't set on the command line or in a configuration file.

**Comment by bmw** [comment]
Fixed in #4702.
