### ISSUE TITLE
Package in Debian `jessie-backports` is out of date with `stretch` (current testing)

### ISSUE THREAD

**Issue by Techwolfy** [certbot/certbot#4488]
I'm running Debian Jessie (stable, 8.7), with Certbot version 0.9.3-1~bpo8+2 installed via `apt-get` from `jessie-backports`.

I just finished setting up a hook script to handle the DNS-01 challenge to issue certificates, but that feature was added in Certbot v10. Debian Testing has had the updated package since late January, but it hasn't been backported. Can you submit the newer package to the backports repository as well, or is there a technical reason it's missing?

**Comment by SwartzCr** [comment]
pinging @hlieberman who can answer this question

**Comment by hlieberman** [comment]
Noah Swartz <notifications@github.com> writes:
> pinging @hlieberman who can answer this question

Yup -- this is my bad.  Like an idiot, I tried to backport the version
from unstable instead of from testing -- and the backports masters
rightfully rejected it.  I then totally forgot about the backport
because "I had already done it."  Derp.

Uploading it now.

-- 
Harlan Lieberman-Berg
~hlieberman

**Comment by SwartzCr** [comment]
Thanks Harlan! I'm going to close this, @Techwolfy feel free to ping me if it doesn't appear soon and I can re-open

**Comment by Techwolfy** [comment]
@hlieberman, @SwartzCr: Certbot v0.11.1-1 was rejected from the backports-policy queue since it's newer than the version in testing (currently 0.10.2-1). I'm not sure if you can update both at once, but you should be able to upload 0.10.2-1 to jessie-backports while 0.11.1-1 is in the queue for testing if not.

**Comment by Techwolfy** [comment]
0.10.2-1 is now in jessie-backports. Thanks for the updates!
