### ISSUE TITLE
Having a faulty `cli.ini` variable breaks *all* of `certbot`, including `--version`

### ISSUE THREAD

**Issue by osirisinferi** [certbot/certbot#4491]
## My operating system is (include version):
Gentoo profile 13.0

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
`emerge app-crypt/certbot-9999` (= latest git master commit)

## I ran this command and it produced this output:
```
server ~ # certbot -vv --version
usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
cert. 
certbot: error: must-staple is a flag but is being set to 'False'
server ~ # 
```

## Certbot's behavior differed from what I expected because:
Partially related: #4490 (it "broke" my `certbot` by having a faulty `cli.ini` variable).

I would expect functions like `--version` to be able to run without a problem, even when some parts of the program would result in an error.

## Here is a Certbot log showing the issue (if available):
There's no log generated. The above is all `certbot` is outputting, even with `-vv`.

**Comment by SwartzCr** [comment]
While annoying I'm not sure that this exactly a problem. I think we should discourage people from modifying their cli.ini files except in specific situations. While, yes, it would be nice if --version worked, certbot likely still won't run properly so this is a good way to entice you to unedit your cli.ini file.
But I'm curious to hear what @pde thinks

**Comment by SwartzCr** [comment]
We have discouraged people from editing cli.ini in #4427
I've recommended that we move `certbot --version` to a similar status as `certbot --help` so that this won't occur in #4350
So I'm going to close this issue as a duplicate
