### ISSUE TITLE
Allow a user to export (obtain a copy of a key, cert, and chain for use elsewhere)

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#4506]
From #338.

**Comment by bobstrecansky** [comment]
working on this at PyCon17

**Comment by bobstrecansky** [comment]
https://github.com/certbot/certbot/pull/4713

**Comment by bmw** [comment]
Given the files are stored on disk with a path we regularly give you, I don't think this feature makes sense. If you disagree, comment and I'll consider reopening.
