### ISSUE TITLE
os.Rename() Causing Issues on Windows

### ISSUE THREAD

**Issue by ahaw021** [certbot/certbot#4510]
## My operating system is (include version):
windows 2012 r2

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

pip
## I ran this command and it produced this output:

certbot certonly

['--manual', '--expand', '-d', 'f5-site.firecube.xyz', '-d', 'f5-site4.firecube.xyz', '--preferred-challenges=dns']

## Certbot's behavior differed from what I expected because:

**Error**

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\etc\\letsencrypt\\renewal\\f5-site.firecube.xyz.conf.new' -> 'C:\\etc\\letsencrypt\\renewal\\f5-site.firecube.xyz.conf'

**Root Cause**

On Unix, if dst exists and is a file, it will be replaced silently if the user has permission. The operation may fail on some Unix flavors if src and dst are on different filesystems. If successful, the renaming will be an atomic operation (this is a POSIX requirement). On Windows, if dst already exists, OSError will be raised even if it is a file.

**Fix:** 

I replaced the the os.rename() functions with os.replace()

Storage.py - Lines 165 and 136

Reading the documentation this should not impact linux b

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

Traceback (most recent call last):
  File "c:\python37\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Certbot-Production\Scripts\certbot.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\certbot-production\lib\site-packages\certbot\main.py", line 755, in main
    return config.func(config, plugins)
  File "c:\certbot-production\lib\site-packages\certbot\main.py", line 682, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "c:\certbot-production\lib\site-packages\certbot\main.py", line 77, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "c:\certbot-production\lib\site-packages\certbot\renewal.py", line 306, in renew_cert
    lineage.save_successor(prior_version, new_cert, new_key.pem, new_chain, config)
  File "c:\certbot-production\lib\site-packages\certbot\storage.py", line 1100, in save_successor
    self.lineagename, self.archive_dir, symlinks, cli_config)
  File "c:\certbot-production\lib\site-packages\certbot\storage.py", line 158, in update_configuration
    os.rename(temp_filename, config_filename)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\etc\\letsencrypt\\renewal\\f5-site.firecube.xyz.conf.new' -> 'C:\\etc\\letsencrypt\\renewal\\f5-site.firecube.xyz.conf'

**Comment by SwartzCr** [comment]
Interesting
@ahaw can you let us know what version of certbot you got from pip?
Also I'm curious if this will work on older versions of python, it looks like yours is using 3.7?
@bmw or @erikrose or @yan12125 any thoughts on the safety/reasonability of this?

**Comment by ahaw021** [comment]
hi @SwartzCr 

Version 0.13.0

Having a look at the github code os.rename() is still used

The issue is that os.rename() work on linux with no issues but will not work with windows if the files are already there (os documenation in python specifies the same)

I have a build script for windows which I will replace the os.rename() method with the os.replace()

My feeling is for cross platform support os.replace is the better option. 

Andrei

**Comment by yan12125** [comment]
If a stable Python version like 3.6 suffers from the same problem, it worths a look. @ahaw021 Did you try it on 3.6 or older?

Here comes another question: is Windows fully supported? Seems there are no unit tests running for Windows, and I can't find a planned issue like #2978, which targets macOS.

**Comment by ahaw021** [comment]
Hi Guys

I am using 3.6. As per Python 

 os.rename(src, dst, *, src_dir_fd=None, dst_dir_fd=None)

    Rename the file or directory src to dst. If dst is a directory, OSError will be raised. On Unix, if dst exists and is a file, it will be replaced silently if the user has permission. The operation may fail on some Unix flavors if src and dst are on different filesystems. If successful, the renaming will be an atomic operation (this is a POSIX requirement). On Windows, if dst already exists, OSError will be raised even if it is a file.

It is a windows issue not a python version issue

Andrei

**Comment by yan12125** [comment]
Thanks. Unfortunately ```os.replace``` is not available until Python 3.3. Maybe a wrapper with try-catch blocks do things well, too.

**Comment by ahaw021** [comment]
ah ok - didn't read that bit :(

I am using 3.6 in my builds and as it's the only windows certbot build at the moment find and repace in the sript will work. Longer term I agree there should be  python version try catch 

Andrei

**Comment by alexhass** [comment]
Are you making any progress on getting this issue resolved?

**Comment by adferrand** [comment]
Resolved by #6415
