### ISSUE TITLE
Clarify documentation of configuration file

### ISSUE THREAD

**Issue by ian-kelling** [certbot/certbot#4512]
https://certbot.eff.org/docs/using.html#configuration-file says::

```
# All flags used by the client can be configured here. Run Certbot with
# "--help" to learn more about the available options.
```

This begs the question of whether there are configuration options that are not flags to the client, and it is not answered in this section. This should be clarified, either by discussing which options are configuration file only, or changing the above to something like:

```
# The possible configuration options are exactly the same as the flags
# used by the client. Run Certbot with "--help" to learn more about the
# available options.
```

**Comment by SwartzCr** [comment]
Assigning @pde and linking to #4152

**Comment by bmw** [comment]
Feel free to open a PR with this change, but this is a pretty minor point in my opinion so I'm closing this issue.
