### ISSUE TITLE
Build/verify the unicode sandwich

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4516]
Everything I've ever read about properly handling strings in Python says that you should use Unicode throughout your program and then convert them to/from the correct external encoding at the edges of your program. This means decoding input from a user, file, or network and converting it to Unicode as soon as possible and conversely encoding output right before it is sent. I've heard this described as the "Unicode sandwich". To do this, you should use `unicode/str` in Python 2 and 3 respectively throughout your program and convert to `str/bytes` respectively before output. `six.text_type` and `six.binary_type` help with this.

I don't think we currently do this correctly in Certbot. For example, see #4273. If someone is aware of a better way to handle text encoding, I'm open to other suggestions, but AFAIK this is the best way to do things. We should look through our code and make sure we a have a Unicode sandwich, correcting code as necessary.

@yan12125, you may be interested in this.

**Comment by yan12125** [comment]
IMO it's better to have #2208 fixed first before going down this way. In my experience in Python 2.6 and earlier 2.7 versions, CPython's standard library doesn't support Unicode strings well. Here are some examples I saw in another Python project:

* https://bugs.python.org/issue2646: Unicode keyword arguments are not supported in Python < 2.6.5
* https://bugs.python.org/issue19099: struct.pack and struct.unpack don't accept Unicode as the format in Python < 2.7.7

If certbot aims to support as much Python versions as possible and switch to a "all-Unicode" model, I guess there will be lots of workarounds.

**Comment by bmw** [comment]
Ugh good point. We shouldn't do this until we drop Python 2.6 support. Based on what I've read about this, despite the standard library having issues in some places, it's still worth doing to have a clear model and boundaries to prevent bugs like #4273. Again, I'm open to other ideas though.

Another thing we could do to help this is to work more quickly towards dropping Python 2 support all together. The Python community is heading this way and I'm not aware of any systems we support that don't have some version of Python 3 available (although it may be in an optional repository like EPEL on CentOS).. This will be a longer process though.

**Comment by yan12125** [comment]
I've started some experiments by adding ```from __future__ import unicode_literals``` to all some files and checking unit tests. Apparently things are much better than I've thought. No tricky workarounds are necessary so far.

By switching all internal data to unicode, it's possible that third party plugins will get broken. Do you think certbot needs a transition plan? Or is it OK to force all plugins to use ```from __future__ import unicode_literals``` since some point?

**Comment by bmw** [comment]
> I've started some experiments by adding from __future__ import unicode_literals to all some files and checking unit tests. Apparently things are much better than I've thought. No tricky workarounds are necessary so far.

That's great! I'm glad it's going well and thanks for working on it.

> By switching all internal data to unicode, it's possible that third party plugins will get broken. Do you think certbot needs a transition plan? Or is it OK to force all plugins to use from __future__ import unicode_literals since some point?

Another good point. We certainly want to avoid breakage for 3rd party plugins. I'm open to ideas on how to best accomplish this. We could maybe handle the conversion for them and if they return a non-Unicode string we just convert it, but there also the opposite problem of us suddenly giving them Unicode which may cause issues.

Unless you see a reasonable path forward there (or somewhere else), I think the best approach is to work with them towards this change. We maintain a list of most 3rd party plugins that we are aware of [here](https://certbot.eff.org/docs/using.html#third-party-plugins). We can reach out to them to make sure they are aware of what we're doing and help them through the process.

I do think it's reasonable to say after point X we will be making this change, but we should do everything we can to make sure 3rd party plugins are updated before that time comes.

**Comment by bmw** [comment]
By the way, this came up during a meeting and it was suggested that whoever works on this may want to block this issue on #4244 which is blocked on #2208. This certainly doesn't have to be the case, but if this would make life easier for whoever works on this, it seems reasonable to me.

**Comment by SwartzCr** [comment]
We've been having a lot of reports recently of issues relating to this - so I'm going to put this in the next milestone

**Comment by bmw** [comment]
Unfortunately doing this is a lot of work (and would be a lot easier if we added mypy type annotations as described above which is also a lot of work), but I agree this would be valuable. I suspect we'll have to kick this further down the road, but prioritizing this should eliminate a lot of bugs and make working on Certbot more enjoyable for devs by adding better documentation and testing.

**Comment by ohemorange** [comment]
I made a project board for this so we can split it down into smaller tasks that are more collaborative.
