### ISSUE TITLE
Print deprecation warning on experimental systems in certbot-auto

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4520]
We have a number of systems where we have "experimental" bootstrap support but we have OS packages available. We should print a deprecation warning for these systems telling users that support is going away including how to install the OS packages. We will be removing support completely for these systems in a few months. The current experimental systems are:

* Mageia
* Manjaro 
* Gentoo
* FreeBSD
* macOS
* Amazon Linux
* Joyent SmartOS Zone

At the very least, Gentoo, FreeBSD, and macOS have other options but we should check out other systems as well.

**Comment by SwartzCr** [comment]
So here's what I've found:
It seems like we're packaged for Mageia - http://check.mageia.org/cauldron/updates.html
It's possible that this netbsd package works for manjaro - http://cdn.netbsd.org/pub/pkgsrc/current/pkgsrc/README-all.html
It's possible that the arch package of certbot works for Joyent Smart OS
Doubt there's anything for Amazon Linux (they never responded to me)

**Comment by bmw** [comment]
Also, we should print this deprecation warning more often rather than just when we bootstrap the system.

**Comment by bmw** [comment]
certbot-auto has been deprecated, will error out on new systems, and existing installations are no longer receiving updates so I'm closing this.
