### ISSUE TITLE
Message when certbot-auto can't handle OS deps

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4521]
We should list the name of the required OS packages and then tell users to run with `--no-bootstrap`.

**Comment by SwartzCr** [comment]
But should we? I think we should be careful about what we do here, for example look at: https://github.com/certbot/certbot/issues/5023
Where we might tell someone to install a lot of dependencies on a system that will never work.

**Comment by bmw** [comment]
I'm unaware of any reason that Certbot shouldn't work on a UNIX-like system. People have gotten it to run on things like [Solaris](https://wiki.enterpriselab.ch/el/public:sysadmin:letsencrypt:install-solaris-11) in the past.

**Comment by bmw** [comment]
The dependencies are listed in the bootstrap scripts in `letsencrypt-auto-source/pieces/bootstrappers`. The exact names of these dependencies are going to vary based on the system so I think we should just list the human readable package name. They shouldn't need `gcc` specifically, but they'll need a compiler on systems where they cannot use `cryptography`'s precompiled wheel.

**Comment by bmw** [comment]
certbot-auto has been deprecated, will error out on new systems, and existing installations are no longer receiving updates so I'm closing this.
