### ISSUE TITLE
Don't parse files other than *.conf on Debian 8

### ISSUE THREAD

**Issue by jmorahan** [certbot/certbot#4523]
## My operating system is (include version):
Debian 8 (I expect Ubuntu 14.04 and later will also be affected)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Probably OS package manager (I don't know for sure because I'm filing this bug report based on [someone else's post](https://community.letsencrypt.org/t/the-apache-plugin-is-not-working/32279?u=jmorahan) in the community forum)

## I ran this command and it produced this output:
    sudo certbot --apache
    The apache plugin is not working; there may be problems with your existing configuration.
    The error was: PluginError(('There has been an error in parsing the file (%s): %s', '/etc/apache2/sites-available/000-default.conf.save', 'Syntax error'),)

## Certbot's behavior differed from what I expected because:
Certbot shouldn't have tried to parse that file at all, because Apache only includes files matching `*.conf` by default on Debian 8.

**Comment by jmorahan** [comment]
I can't find a handy link but you can compare the `/etc/apache2/apache2.conf` from eg. https://packages.debian.org/wheezy/amd64/apache2.2-common/download vs https://packages.debian.org/jessie/amd64/apache2/download

Similarly for Ubuntu, http://packages.ubuntu.com/precise/amd64/apache2.2-common/download vs http://packages.ubuntu.com/trusty/amd64/apache2/download

**Comment by SwartzCr** [comment]
@joohoi any thoughts?

**Comment by SwartzCr** [comment]
I'm going to assign this to @joohoi, and he can make a determination about whether this is a legitimate issue when he starts working on apache reliability
