### ISSUE TITLE
Future-proof against #4284

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#4527]
- Should we not save the installer when we run `certonly`?
- Should `restart` be called inside of `deploy_cert`?

**Comment by ohemorange** [comment]
Link: #4284.

**Comment by bmw** [comment]
[TLS-SNI is dead](https://community.letsencrypt.org/t/2018-01-11-update-regarding-acme-tls-sni-and-shared-hosting-infrastructure/50188) so I'm closing this issue.
