### ISSUE TITLE
Renewing certificates documentation is ambiguous regarding hooks persistence

### ISSUE THREAD

**Issue by mnewberry** [certbot/certbot#4534]
After certbot automatically renewed its certificates, I realized I would need to restart services to read the new certs.

The user's guide section on renewing certificates (https://certbot.eff.org/docs/using.html#renewing-certificates) says that I can use `certbot renew --renew-hook /path/to/renew-hook-script` to specify a script that will restart services.

I am confused, however, about what behaviour this would result in next time certificates are automatically renewed.  If I run `certbot renew --renew-hook my-script` once, will it run `my-script` on automatic renewal?  If not, how do I specify that the hook should be executed on automatic renewal?  If so, how would I see which scripts would be run on automatic renewal?

The confusion is exacerbated because there are multiple places on the system where information about what hooks to run could reside: a crontab that invokes certbot renew, systemd's certbot.service, or in certbot's configuration in /etc/.

For someone who has been running certbot, the user guide section is the natural place to look for answers to the questions above, so my feature request is to have these questions clarified in that section of the documentation.

**Comment by SwartzCr** [comment]
adding to the #4152 thread

**Comment by bmw** [comment]
I'm going to close this as a piece of #5066 where this issue is linked and tracking the bigger picture of better documentation around these hooks.
