### ISSUE TITLE
Unwrap "max retries exceeded" errors

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#4535]
When there is some sort of network problem, or the server is unavailable, we get an error like:

> An unexpected error occurred: ConnectionError: HTTPSConnectionPool(host='acme-v01.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f020eee70d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

This is confusing because it emphasizes the "retries" part, when the important part is the "Name or service not known" part. We should handle this type of error specially and just show the actual error, not the part about exceeding retries.

**Comment by bobstrecansky** [comment]
Working on this one at PyCon2017

**Comment by bobstrecansky** [comment]
Proposed starting to implementation: https://github.com/kennethreitz/requests/pull/4047

**Comment by bobstrecansky** [comment]
Talked to the requests library maintainers; they mentioned that I could take this exception; wrap it as a string, and parse it.  Going to take a stab at that today.

**Comment by bobstrecansky** [comment]
WIP: https://github.com/certbot/certbot/pull/4733

**Comment by bmw** [comment]
@jsha, Noah said you might be interested in working on this?
