### ISSUE TITLE
Syntax Error in Apache conf

### ISSUE THREAD

**Issue by kernm** [certbot/certbot#4536]
## My operating system is:
Debian 8.7

## I installed Certbot with:
apt-get and jessie-backports

## I ran this command and it produced this output:
certbot --apache certonly

```
The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError(('There has been an error in parsing the file (%s): %s', '/etc/apache2/sites-enabled/ssl-conf.conf', 'Syntax error'),)
```

## Here is a Certbot log showing the issue:

[letsencrypt.txt](https://github.com/certbot/certbot/files/947011/letsencrypt.txt)
[ssl-conf.txt](https://github.com/certbot/certbot/files/947020/ssl-conf.txt)

I can't see any Syntax Error in this Config file, may you can?

**Comment by SwartzCr** [comment]
Hmm
Can you try running `apache2ctl configtest` and see what it says about the syntax.
Alternately this might be a problem with augeas @domcleal or @joohoi any ideas?

**Comment by joohoi** [comment]
It must be the unclosed quote on line. Apache seems to ignore this and reports syntax ok, but it causes error for the parser.

```
SSLCipherSuite 'EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA:EECDH:EDH+AESGCM:EDH:+3DES:ECDH+AESGCM:ECDH+AES:ECDH:AES:HIGH:MEDIUM:!RC4:!CAMELLIA:!SEED:!a$
```

**Comment by kernm** [comment]
Thanks for your answer!
The problem was indeed the missing quote in the end of the line. Thanks alot @joohoi

**Comment by joohoi** [comment]
No problem! Glad you got it working. I'll close the issue, but if you continue experiencing related problems, feel free to reopen it.
