### ISSUE TITLE
Discuss: Freezing + PIP as distribution model

### ISSUE THREAD

**Issue by zjs** [certbot/certbot#4537]
It seems like Certbot encounters numerous issues around distribution and dependency management.

It seems like [freezing](https://python-guide-pt-br.readthedocs.io/en/latest/shipping/freezing/#freezing-your-code-ref) using a tool like [cx_Freeze](https://anthony-tuininga.github.io/cx_Freeze/) or [PyInstaller](http://www.pyinstaller.org/) would greatly simplify the experience for end-users: a release would be a sets of binaries, including all necessary dependencies, for each platform. The main drawback of this is that it means that new Certbot releases would be required to pick up fixes (including security fixes) in dependencies or Python itself, but it comes with a significant advantage that everyone using a given version of Certbot will be using a single well-known and tested version of each dependency.

Essentially: ship an end-user application instead of a collection of python modules.

Those who use Certbot as a library (and more savvy users who want control over the versions of dependencies used) could get Certbot via PIP.

**Comment by yan12125** [comment]
Related: #334

Here's an question: if freezing is going to be implemented, should certbot be updated whenever a dependency releases a new version? If so ```pyup``` can be useful. Here's another project using it: https://github.com/pypa/warehouse/commits/master

**Comment by zjs** [comment]
> Related: #334

I suspected this would be a duplicate, but couldn't find that. Thanks!

> if freezing is going to be implemented, should certbot be updated whenever a dependency releases a new version?

I think it makes sense to update `master` and `pyup` seems like a good way to do that.

When an update to a dependency fixes a bug that's impacting Certbot users, a micro/Z release could be considered (based on usage data for the impacted version(s)/feature(s) of Certbot and the severity of the bug that was fixed).

**Comment by bmw** [comment]
Most of us on the Certbot team (including me) want to change our approach to packaging and have for a while now. There's a couple who don't though and that's the current blocker.

Personally, I'd like to investigate making our own .deb and .rpm packages (see #4274). I like this approach because:

* In my experience, this is the approach taken by most major, fast moving Linux projects regardless of their language choice. There are definite benefits to using a distribution method users are used to and other projects have done before.
* We've talked about rewriting Certbot in another language someday (see #4039) and work we do here could be reused.

I'm definitely open to other approaches to though. Most Linux distros being slow to update their packages and the instability of `certbot-auto` isn't working very well.

cc @ohemorange

**Comment by ohemorange** [comment]
How do cx_Freeze and PyInstaller interact with our OS dependencies? Would we just have to list the system dependencies separately, or do they have a way of specifying them? It may be that freezing is a step in releasing .deb and .rpm packages, or that it ends up being easier to pass the freezing and build those packages directly.

I definitely think there are major benefits to doing it this way, and I'm up for doing it whichever way makes it easiest for most users to install.

**Comment by bmw** [comment]
Another minor point for .deb and .rpm packages is it may be easier for people to keep Certbot up to date if we do what Google does with Chrome for example and add our repository to the repo list.

**Comment by zjs** [comment]
> How do cx_Freeze and PyInstaller interact with our OS dependencies? Would we just have to list the system dependencies separately, or do they have a way of specifying them? It may be that freezing is a step in releasing .deb and .rpm packages, or that it ends up being easier to pass the freezing and build those packages directly.

I was envisioning freezing as a step towards creating packages. Freezing would pull in the python-level dependencies (and python). With or without freezing, I think using an OS package (.deb, .rpm, etc.) to express OS dependencies makes sense. I think both would be valuable and would solve distinct problems.

**Comment by bmw** [comment]
There is interesting discussion here, but I'm closing this issue in favor of the more widely scoped #5884.
