### ISSUE TITLE
CentOS 7 No module named contrib.pyopenssl

### ISSUE THREAD

**Issue by plutext** [certbot/certbot#4540]
## My operating system is (include version): 

CentOS Linux release 7.0.1406

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

following https://certbot.eff.org/#centosrhel7-nginx

sudo yum install certbot

## I ran this command and it produced this output:

certbot certonly --webroot -w /opt/Foo -d www.foo.com
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.12.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 21, in <module>
    from certbot import client
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 10, in <module>
    from acme import client as acme_client
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 33, in <module>
    import urllib3.contrib.pyopenssl  # pylint: disable=import-error
ImportError: No module named contrib.pyopenssl

## Certbot's behavior differed from what I expected because:

ImportError: No module named contrib.pyopenssl

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

No log file

**Comment by plutext** [comment]
Workaround:

wget https://dl.eff.org/certbot-auto
chmod a+x certbot-auto
./certbot-auto certonly --webroot -w /opt/Foo -d www.foo.com

**Comment by plutext** [comment]
This is an EC2 machine created from CentOS 7 x86_64 (2014_09_29) EBS HVM-b7ee8a69-ee97-4a49-9e68-afaee216db2e-ami-d2a117ba.2 (ami-e4ff5c93)

**Comment by yan12125** [comment]
I guess CentOS 7 comes with older requests or urllib3. Could you check versions of the two?

Ref: #4537

**Comment by hogarthj** [comment]
That's an ancient version of centos and we only support the current version in EPEL.

If you could do a yum update that would be helpful... also enable epel-testing to get the current 0.13.0 package which hasn't reached stable yet.

**Comment by tisc0** [comment]
Also having the problem.
context : 
pyOpenSSL 0.13.1-3.el7 installed from @base 
certbot 0.14.1-3.el7 from @epel 
CentOS Linux release 7.3.1611 (Core)  freshly updated
Really problematic to put certbot in production.
Thanks in advance, ask if you need anything like feedsback or tests.

**Comment by hogarthj** [comment]
@tisc0 "also having the problem" is not that helpful ...

The exact steps you carried out to reproduce this along with the exact error messages or stacktraces would be helpful.

**Comment by tisc0** [comment]
Oh sorry, my mistake, I was sure I posted on the issue #4514 , and then got disturbed, and thought my comment disappeared from over there, and reposted, and lost the one here !
onz

**Comment by SwartzCr** [comment]
I'm going to close this issue in favor of #4514
