### ISSUE TITLE
Apache plugin crashing with Unicode ServerNames

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#4544]
Reported at

https://community.letsencrypt.org/t/requesting-certs-for-non-ascii-domain-idn-via-certbot-causes-trouble/32637

It looks like a ServerName directive containing an ü is causing a crash in `choose_vhost`.

@jsha said in response to an earlier issue that users would commonly use the Punycode representation of their domain names in other contexts such as web server configurations, but this appears to be a counterexample to that, and one that we don't handle gracefully. :smile:

**Comment by schoen** [comment]
I was able to reproduce this on 0.13.0 by putting a non-ASCII character in an Apache virtual host's `ServerName` and then running `./certbot-auto -d foo.example.com`. It crashed with a `UnicodeEncodeError`. (Just running `./certbot-auto`, interestingly, didn't trigger the bug.)

**Comment by jsha** [comment]
I believe what I said previously was that Apache does not support U-labels in ServerName, and wouldn't properly serve them. I would be curious to know if that's not the case.

Certainly crashing is the wrong thing to do, of course.

**Comment by SwartzCr** [comment]
tagging #4516

**Comment by jsha** [comment]
I tested this on certbot-auto 0.35.1 on Ubuntu 18.04, and it no longer crashes. When I put:

```
        ServerName www.exómple.com
```

In my config and run:

```
certbot-auto --staging
```

I get:

```
No names were found in your configuration files. Please enter in your domain name(s):
```

I think this is fine.
