### ISSUE TITLE
Get our OS packagers on a mailing list

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4545]
We should reach out to our OS package maintainers and try to get them on a mailing list so we can easily send messages with them. Currently, only our Debian, Fedora/EPEL, and Ubuntu PPA package maintainers are on our `certbot-dev` mailing list. We can either ask others to join `certbot-dev`, make a `certbot-packaging` list, or a `certbot-announce` list.

cc @ohemorange

**Comment by ohemorange** [comment]
do we still want to do this?

**Comment by bmw** [comment]
Good question. This is mainly useful when we have a generic message we want to communicate to all or the majority of our package maintainers. I think this is somewhat rare, but does come up. Since we've started distro packaging in 2015, I think this has happened 4 times (letsencrypt->certbot rename, nginx, josepy, and DNS packages).

My feeling is this is nice to have but not essential. Do other people feel differently?

**Comment by joohoi** [comment]
I think it would be good to have. Of course the Debian / EPEL / Ubuntu are the largest ones, but the others would be nice to have onboard as well.

I can think of two things to communicate for the pkg maintainers (especially for ones of the smaller distributions, that we don't have on the list for atm), being:

1) Certbot-apache now supports easy distribution specific specialization, so if there's anything your flavor of Linux needs, that we don't do right now, there's an easy access to adding or modifying those.
2) We're currently in process of implementing cron jobs to certbot-auto, but advocating installation from distributions package management, which is reasonable. This however can cause conflicts or confusion when installing on a machine that has a cronjob created by certbot-auto. Maybe something that doesn't need, or cannot be fixed, but should be noted at least.

**Comment by bmw** [comment]
I'm personally less interested in this since we're deciding to take control of packaging ourselves so I'm closing this issue. Please let me know if you think I should reconsider.
