### ISSUE TITLE
Create certbot-large Dockerfile

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4556]
As suggested [here](https://github.com/certbot/certbot/issues/3782#issuecomment-282555091), we should make a certbot-large image for people who want additional utilities available for use with hooks. Thoughts:

* It should build off our current Dockerfile
* We should stick to common tools we expect people will need and use, but should err on the side of including extra stuff size given the name of the image. At the very least, we need `curl` (see #4552).

cc @joohoi

**Comment by liquidstate** [comment]
+1 for this and installation of `curl` and also `bash` (the two tools required for the cloud flare example)

**Comment by bmw** [comment]
While this could be cool, it's not something I think we'd get to for a long time and it can easily be solved by people installing the tools they need so I'm closing this. If someone thinks I should reconsider, please let me know.
