### ISSUE TITLE
reopen ticket

### ISSUE THREAD

**Issue by batkins62** [certbot/certbot#4565]
please reopen: https://github.com/certbot/certbot/issues/4550

thank you :-)

**Comment by yan12125** [comment]
ping @SwartzCr

On Github non-developers can't reopen tickets not closed by themselves. [1][2] (I can't reopen issues, either :D) Maybe don't ask people to reopen issues in the future.

[1] http://stackoverflow.com/a/21333938/3786245
[2] https://help.github.com/articles/repository-permission-levels-for-an-organization/

**Comment by SwartzCr** [comment]
Ahh - I didn't realize this :(
I'll be less aggressive about closing tickets in the future, but feel free to mention it in issues that I closed. Sorry about that!
