### ISSUE TITLE
Random failures with python-openssl

### ISSUE THREAD

**Issue by devalfrz** [certbot/certbot#4576]
## Random failures with python-openssl
The old script (./certbot-auto) failed while updating the virtualenv, so I went to the documentation and installed certbot using apt-get.
My system got random errors (it failed some times) with the message: `('bad handshake: SysCallError(0, None)',)`. Searching the internet I found that uninstalling `python-openssl` would fix the problem and it did!
Uninstalling the package removed `python-certbot` since it was a dependency.

**Comment by pde** [comment]
So are you saying that you uninstalled `python-certbot` but `certbot` is still running?

It sounds like you probably did `sudo pip install certbot` or similar at some point in the past, and the copy that installed in `/usr/local/` was fighting with your Ubuntu packages.  The more correct solution is probably to `sudo pip uninstall python-certbot` and `sudo pip uninstall python-openssl` (and anything else lying around in `/usr/local/lib` that you don't need) and go back to the Ubuntu PPA packages.

**Comment by pde** [comment]
@SwartzCr you might want to track down whatever advice recommends uninstalling packages, and get it changed to recommend `pip uinstall` ing things.

**Comment by pde** [comment]
@devalfrz what do you get if you type `which certbot`? Are there certbot libraries in `/usr/local/lib/python2.7/dist-packages/`?

**Comment by SwartzCr** [comment]
@devalfrz would you mind linking me to the advice you found that you ended up following?

**Comment by devalfrz** [comment]
I simply uninstalled the official ubuntu package from my system `sudo apt-get remove certbot` and cloned the certbot repository ([https://github.com/certbot/certbot](https://github.com/certbot/certbot)) so it would run as a standalone application.
```
git clone https://github.com/certbot/certbot
cd certbot
./certbot-auto certonly -d mydomain.com
```

**Comment by SwartzCr** [comment]
I'm closing this issue since out packaging is better now and since devalfrz seems to have a working version of certbot.
For future reference users should rely on the packaged version of certbot and not use a version cloned from git.
