### ISSUE TITLE
Missing installation instructions/package for Zesty

### ISSUE THREAD

**Issue by jtojnar** [certbot/certbot#4578]
The website only contains instructions for Trusty, Xenial and Yakkety. Option for recently released Ubuntu 17.04 (Zesty) is missing. The [official PPA](https://launchpad.net/~certbot/+archive/ubuntu/certbot) also lacks zesty packages.

There is, of course, a package in the [official repositories](http://packages.ubuntu.com/zesty/python-certbot) but it is slightly older.

**Comment by SwartzCr** [comment]
So until we package it for Zesty, it'll fall under Ubuntu (other), which currently recommends using Certbot Auto, which will be a newer version that the officially packaged for Ubuntu one.
We'll make a new entry for it once it's in the PPA. Hopefully that makes sense?
If you think we should still have an explicit entry for it let me know!

**Comment by jtojnar** [comment]
@SwartzCr It looks like there is a Zesty package in the PPA now.

**Comment by SwartzCr** [comment]
true! I'll update the instructions

**Comment by SwartzCr** [comment]
and it's here: https://github.com/certbot/website/pull/222

**Comment by SwartzCr** [comment]
and it's merged
