### ISSUE TITLE
mydomain.com.key is empty

### ISSUE THREAD

**Issue by rayidi** [certbot/certbot#4580]
## My operating system is (include version):
Ubuntu 14.04 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
acme.sh

## I ran this command and it produced this output:
acme.sh --issue --dns -d inet.amaravti.net

## Certbot's behavior differed from what I expected because:
.key file is empty

**Comment by yan12125** [comment]
Seems you're using https://github.com/Neilpang/acme.sh? That's a different project than certbot. If you have a problem, the issue tracker there is a better place.
