### ISSUE TITLE
letshelp-certbot test failures on Arch Linux

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4586]
Running `tox -e py27` on 4ca702f6fbd5936f1b1e4ee794ebca09d5acd6fb (`master` at the time of this writing), `letshelp-certbot` unit tests fail with:
```
ERROR: test_copy_config (letshelp_certbot.apache_test.LetsHelpApacheTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/certbot/letshelp-certbot/letshelp_certbot/apache_test.py", line 79, in test_copy_config
    letshelp_le_apache.copy_config(server_root, tempdir)
  File "/root/certbot/letshelp-certbot/letshelp_certbot/apache.py", line 105, in copy_config
    elif safe_config_file(config_file_path):
  File "/root/certbot/letshelp-certbot/letshelp_certbot/apache.py", line 149, in safe_config_file
    universal_newlines=True)
  File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

----------------------------------------------------------------------
```
We don't ship this package, but our tests should pass and this could cause problems for new developers. This is not a regression as tests also fail on v0.13.0 which was our last release.

**Comment by yan12125** [comment]
Tests pass here. Did you run this in containers like docker? The ```file``` package is not critical for Arch Linux and I guess some docker image maintainers may remove it. If so ```pacman -S file``` should fix it.

**Comment by bmw** [comment]
Yep! You figured it out. I ran this in `docker` and `file` wasn't available. Since this package is in the [base](https://www.archlinux.org/groups/x86_64/base/) group, this shouldn't be an issue for devs actually running Arch, but perhaps we should do something for other people who try to test in these minimal docker images. Probably the easiest approach is to check if the `file` command is available in `letshelp` and print a useful error message if it is not.

**Comment by yan12125** [comment]
Good idea! letshelp is broken with Python 3. Let me fix it first :)

**Comment by ArchangeGabriel** [comment]
Just to be clear, having the whole `base` group is not mandatory at all on Arch Linux. That being said, I still expect most people to have file installed. ;)

**Comment by bmw** [comment]
I doubt we'll ever fix this. We don't ship this package, [advise against packaging it downstream](https://certbot.eff.org/docs/packaging.html#notes-for-package-maintainers), and this code has never really been used.

We'll probably just end up deleting the package entirely and if not, I doubt we'll ever prioritize fixing this extreme edge cases in the package's tests.
