### ISSUE TITLE
Implement a Lexicon-based DNS authenticator for Lua DNS

### ISSUE THREAD

**Issue by zjs** [certbot/certbot#4593]
Implement an Authenticator plugin which can fulfill a dns-01 challenge using Lexicon.

**Comment by gbrackley** [comment]
I was looking at the series of authenticators put in and wondered if they support querying a CNAME record and then register the authentication TXT record based on that CNAME record (as a redirect).  This allows DNS-01 style authentication to be delegated to another DNS zone (with a static CNAME record).
