### ISSUE TITLE
Not clear if I should logrotate via crontab?

### ISSUE THREAD

**Issue by binarykitchen** [certbot/certbot#4606]
In my /var/log/letsencrypt/ I have over 235 log files (letsencrypt.log.xxx) - so many!

Not sure if letsencrypt does rotate them or if I should configure manual logrotation for them via a weekly crontab or so?

If so, what's the recommended recipe to rotate? Something like this?

```
/var/log/letsencrypt/letsencrypt.log {
        su root root
        rotate 4
        missingok
        create 640 root root
        postrotate
                # should i restart some services here? nginx?
        endscript
}
```

Thanks for any clues. Using v0.11 here on Ubuntu 16.10

**Comment by SwartzCr** [comment]
So Certbot currently will do log rotation after 1000 logs. We have a PR open that configures this number #4195. So while you could set up your own script, it might just be a better idea to comment on the PR & help get it merged :)

**Comment by binarykitchen** [comment]
ah, ok, all good then
