### ISSUE TITLE
permissions issue appeared again in 0.14.0

### ISSUE THREAD

**Issue by yaccin** [certbot/certbot#4621]
Webroot plugin should override permisions of files / dirs created #1389 << this issue seems to have appeared again in the latest version.

## My operating system is (include version):
archlinux

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
os package manager

## I ran this command and it produced this output:
certbot renew --dry-run

## Certbot's behavior differed from what I expected because:
challenge requests return permission denied because the files have the wrong permissions for web servers running as a different user/group

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

```
Attempting to renew cert from /etc/letsencrypt/renewal/domain.com.conf produced an unexpected error: Failed authorization procedure. domain.com (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://domain.com/.well-known/acme-challenge/KbVSsiUjN_YLvOlo-gASt8362tBtlmYs6iPohCW_Q6k: "<!DOCTYPE html>
<html class="nojs html css_verticalspacer" lang="en-US">
 <head>

  <meta http-equiv="Content-type" content=", www.domain.com (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://www.domain.com/.well-known/acme-challenge/kjyat6_GuHtwrLFXKNQWfyeOhMaxLEoLHDhYsBoAKG0: "<!DOCTYPE html>
<html class="nojs html css_verticalspacer" lang="en-US">
 <head>

  <meta http-equiv="Content-type" content=". Skipping.
```

**Comment by bmw** [comment]
Thanks for reporting the problem. The way we handle permissions with webroot hasn't changed in over a dozen releases so while I don't think this is a new problem with 0.14.0, it's possible our solution to #1389 broke a long time ago or you have a configuration that isn't handled by that solution. Let's fix it.

If you run:
```
certbot certonly --debug-challenges --domains <domain> --dry-run --webroot --webroot-path <webroot>
```
where you replace `<domain>` and `<webroot>` with the values for your system, Certbot will run but pause after placing the files in your webroot. In another terminal, go to your webroot and check the permissions of these files.

The `.well-known` and `acme-challenge` directory inside it should be owned by the user and group you ran Certbot as with 755 permissions. The file inside `.well-known/acme-challenge` should have the same owner and group with 644 permissions. Do you see different permissions? If the permissions are as I described, does this not work for your setup? The files are world readable so they should be served by most web servers. Are you able to access the files in your browser?

Thanks for the additional information and I'm sorry for the trouble!

**Comment by yaccin** [comment]
thank you for the additional information! I was able to resolve the issue on my end. It looks like someone broke the redirects from http to https which caused all http requests to fail. Perhaps for renewals the requests could first be done via https instead of http as it is likely that https is working already? Anyways, the issue was with the web server configuration, so sorry for opening a bug report & thanks again for the help.

**Comment by bmw** [comment]
Great! I'm glad you got it working.

Unfortunately, having the ACME server (Let's Encrypt) first attempt to connect over HTTPS has been heavily debated, it was decided to forbid it in [the protocol](https://tools.ietf.org/html/draft-ietf-acme-acme-06#section-8.2), and changing this is outside of the scope of Certbot. You can see the discussion of this issue on the [mailing list](https://mailarchive.ietf.org/arch/search/?email_list=acme) if you're interested, but at the very least I'm glad you were able to resolve the problem.

**Comment by francisrod01** [comment]
@bmw the problem is to use certbot with Aws beanstalk nodejs stack.
The website path is `nodejs` user/group.

I received this output always that I try generate this certificate:

```
Failed authorization procedure. my-site.domain.com (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response
```
