### ISSUE TITLE
Update README.rst

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4622]
This file hasn't really changed much in a long time and plenty of features have been added/removed. We should update it to reflect the current state of Certbot.

**Comment by SwartzCr** [comment]
feel fee to point out specific parts that need updating if you think they're non-obvious & I can make sure to update them

**Comment by bmw** [comment]
In most cases I think it's in pretty good shape. I think the main thing that needs to be done is editing the "Current Features" section at the bottom of the file. Most of this section was written in 2015 and should probably be updated using our changelog as a reference.

**Comment by SwartzCr** [comment]
oh yeah - that's so many things, okay

**Comment by bmw** [comment]
We definitely don't have to duplicate our changelog here, it just might be a good idea to list some of the noteworthy features that we've added in the past year and a half.

**Comment by SwartzCr** [comment]
I kind of feel like the things listed at the bottom are generic enough that it'd be hard to add much to them - like we say we're automatic, I don't think we've added anything at that level
