### ISSUE TITLE
Certbot trying to join wrong url for .well-known?

### ISSUE THREAD

**Issue by EmmanuelBeziat** [certbot/certbot#4631]
## My operating system is (include version):
Debian 8 (Nginx server)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Package manager (following this https://certbot.eff.org/#debianjessie-nginx )

## I ran this command and it produced this output:
```bash
certbot certonly --webroot -w /var/www/***/site -d ***.com -d www.***.com
```

```bash
Failed authorization procedure. ***.com (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Could not connect to www.***.com.well-known
```

## Certbot's behavior differed from what I expected because:
Did it really tried to access `mydomain.com.well-known` instead of `mydomain.com/.well-known`? Because it surely wouldn’t reach anything if so… What could be the problem and how to fix it?

## Here is a Certbot log showing the issue (if available):

```bash
2017-05-09 03:33:05,009:DEBUG:certbot.reporter:Reporting to user: The following errors were reported by the server:

Domain: ***.com
Type:   connection
Detail: Could not connect to www.***.com.well-known

To fix these errors, please make sure that your domain name was entered correctly and the DNS A record(s) for that domain contain(s) the right IP address. Additionally, please check that your computer has a publicly routable IP address and that no firewalls are preventing the server from communicating with the client. If you're using the webroot plugin, you should also verify that you are serving files from the webroot path you provided.
2017-05-09 03:33:05,010:INFO:certbot.auth_handler:Cleaning up challenges
2017-05-09 03:33:05,010:DEBUG:certbot.plugins.webroot:Removing /var/www/***/site/.well-known/acme-challenge/5_JZh_a7UyquBi-pHs_eHwPS_tvleupsTAVp7q_thJY
2017-05-09 03:33:05,011:DEBUG:certbot.plugins.webroot:Removing /var/www/***/site/.well-known/acme-challenge/NvvOQda38gqyz4j-vUAKI1FWYfAmQHZlnVCdPu5mdi0
2017-05-09 03:33:05,012:DEBUG:certbot.plugins.webroot:All challenges cleaned up, removing /var/www/***/site/.well-known/acme-challenge
2017-05-09 03:33:05,013:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.10.2', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 849, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 626, in obtain_cert
    action, _ = _auth_from_available(le_client, config, domains, certname, lineage)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 107, in _auth_from_available
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 291, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 262, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 77, in get_authorizations
    self._respond(resp, best_effort)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 134, in _respond
    self._poll_challenges(chall_update, best_effort)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 198, in _poll_challenges
    raise errors.FailedChallenges(all_failed_achalls)
FailedChallenges: Failed authorization procedure. ***.com (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Could not connect to www.***.com.well-known
```

## Notes

The DNS records are ok, the website is totally available, and I'm familiar with the "old" way of using let's encrypt (before certbot). Nothing changed, except the use of certbot instead of the previous tool.

Thanks :)

**Comment by EmmanuelBeziat** [comment]
Found this https://github.com/plesk/letsencrypt-plesk/issues/153 It says that it was resolved by removing a ssl redirection, but at that time i have no ssl redirection going on.

**Comment by EmmanuelBeziat** [comment]
Okay, I found the problem.

I was using Nginx as a reverse-proxy for apache, and here's the problem:
```
<VirtualHost 127.0.0.1:8082>
	ServerName ***.com
	ServerAlias ***.com

	Redirect permanent / http://www.***.com
</VirtualHost>
```

The last line must end with a / for the redirection. It wasn’t happening on the previous version of the tool.

**Comment by schoen** [comment]
Hi @EmmanuelBeziat,

You are not the first person to encounter this kind problem, but I don't believe that Certbot was responsible for adding that `Redirect permanent` line to your configuration.

When Certbot adds redirections to configuration files, it uses `mod_rewrite` with a `RewriteRule`. I haven't found any code in Certbot that could have been responsible for putting the line you found into your configuration file.

**Comment by EmmanuelBeziat** [comment]
Hi,

I didn't mean Certbot was responsible :) What I mean is that this difference at the end of a vhost wan drive him crazy.

In this particular case, I was having a whole bunch of vhost files, and some of it where gettint the error I mentionned. It took me some time to find out what the problem was. But the point is, I don't remember having this issue with the old tool (let's encrypt script), though the configuration files didn't changed since then.

**Comment by ldo** [comment]
Let me add my vote to the fact that this is a common web server misconfiguration issue that, while it might not be Certbot’s fault, should perhaps be mentioned in a FAQ somewhere as something you should check.

**Comment by bmw** [comment]
I think detecting the problem beforehand programmatically with the webroot plugin is actually quite difficult to do reliably.

As for documentation, we currently don't have a great place to put documentation for a somewhat niche problem like this (although maybe we should create one) and now googling "certbot .well-known slash" comes up with a bunch of results for how to fix this specific problem so I'm not sure if it is necessary.

With all that said, one thing we could probably pretty easily do is look for a lack of a slash before `.well-known` in the error message returned by Let's Encrypt and add output to Certbot suggesting that the user looks into this problem.
