### ISSUE TITLE
Multiple accounts: expiration email sent to wrong account

### ISSUE THREAD

**Issue by Ezwen** [certbot/certbot#4633]
## My operating system is (include version): 
Fedora 25

## I installed Certbot with (certbot-auto, OS package manager, pip, etc): 
- package manager
- certbot version: 0.12.0

## Context and expected behavior:

- I have a certbot installation with two different accounts (A and B), and each account has one certificate.
- When a certificate is about to expire, an email should be sent to the account owning the certificate.

## Certbot's behavior differed from what I expected because:

- When the certificate of account A is about to expire, an email is sent to the address of account A, which is good.
- However, when the certificate of account B is about to expire, an email is also sent to the address of account A, and not of account B, which is not good.

**Comment by pde** [comment]
It sounds likely that both certs are actually associated with account A. What commands did you use to try to get the second cert to belong to B?

**Comment by Gwend4l** [comment]
Hi! thanks for the answer :)

Accounts A and B were at first on different computers, and I had "merged" the certbot configurations on the same computer at some point - event though A nd B belong to different individuals.

So the current state is:
- In the `accounts/acme-v01.api.letsencrypt.org/directory/` folder, I have one folder for account `A`, and one folder for account `B`. Each `regr.json` file has a different `contact` address.
- In the `renewal` folder, I have one conf file per domain, and there is one domain per certificate, hence two conf files. Each conf file has the `account line` properly set up, ie. `account=A` for one domain and `account=B` for the other domain

**Comment by pde** [comment]
@jsha any thoughts on this? What would Boulder do if accout A obtained a certificate at first, and then account B renewed it?

**Comment by pde** [comment]
@Gwend4l was it the case that when the certs were first obtained, they both came from account A? Or does that seem to have become the case since you merged the accounts?

**Comment by jsha** [comment]
So long as any certificate with the same name exists and is current (regardless of account), Boulder won't send mail.

**Comment by Gwend4l** [comment]
> @Gwend4l was it the case that when the certs were first obtained, they both came from account A? Or does that seem to have become the case since you merged the accounts?

Nope, one cert was obtained with A, and the other with B :(

**Comment by bmw** [comment]
This issue hasn't seen any updates in almost 2 years so I'm closing the issue. If you continue to have the problem, please comment or open a new issue.
