### ISSUE TITLE
Deprecate /etc/letsencrypt/{keys,csr}

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#4634]
Although these were added for super-plausible reasons about going back and finding stuff that people might need, I'm not sure if I've ever come across any case where someone successfully used their contents correctly (with the possible exception of people who naively deleted all of `/etc/letsencrypt/archive`), and I've come across many people who were confused by their presence, some of whom even thought that the CSR was the cert and that they were supposed to point Apache to the most recent CSR in `/etc/letsencrypt/csr` and the most recent key in `/etc/letsencrypt/keys`.

I think it is possible that almost no users manage to use these backups correctly and that they ought to be deprecated and removed.

**Comment by St-Ranger** [comment]
While I understand the argument for deleting private keys (for the future secrecy (FS)), I might be missing the argument(s) for deleting the past CSRs (except for people being confused).
I don't think CSRs affect FS, do they?

I've just actually looked at CSRs to analyze certain aspects of it... While it is not a common use (or, rather, it might be very uncommon), I used them nevertheless.

**Comment by schoen** [comment]
@St-Ranger, could you describe how you found the CSRs useful?

We just had a forum thread where someone said that they took up a lot of disk space and so I'm interested in pursuing the question of having Certbot save fewer archival files that it doesn't refer back to itself.

**Comment by mnordhoff** [comment]
FWIW, you can extract the CSR from `letsencrypt.log`. It would be a hassle to do routinely, but still useful for a debugging emergency.

**Comment by bmw** [comment]
I personally think we can just make these change. We never heard back on the use case for `/etc/letsencrypt/csr`, we didn't consider either directory something that should be considered stable as part of 1.0 (see https://certbot.eff.org/docs/compatibility.html), and I can't imagine us no longer using these directories would affect (m)any users.

No longer using `/etc/letsencrypt/csr` should be easy, however, one nice thing about `/etc/letsencrypt/keys` is I believe that is the only place the key is written to disk before we obtain a certificate. If Certbot crashes after the CA issues the cert but before we could write it and the key to disk, it's currently the only way to recover and use that certificate (which can be obtained from public logs).

While I do think this is useful in theory, in practice probably everyone just reissues their cert. If we did want to preserve this behavior though, I think we'd need to do something like either refactoring things to write the key to `/etc/letsencrypt/archive` before the certificate is obtained or delete the copy of the key written in `/etc/letsencrypt/keys` after it was written to the archive.

**Comment by fmunteanu** [comment]
@bmw any update on this issue?

**Comment by schoen** [comment]
@bmw One idea that wouldn't require making code changes in Certbot itself would be to have some of the installation methods, at least on Linux, add timers or cronjobs that run something like

`find /etc/letsencrypt/keys -type f -mtime +30 -delete`
`find /etc/letsencrypt/csr -type f -mtime +30 -delete`

Or even some other number instead of 30. (GNU find counts mtime in terms of days.)

This would stop tons of older files from accumulating in these directories, in advance of any behavior change inside Certbot's code.

I can double-check whether this syntax works in other versions of find or whether anything is a GNU-specific extension.

**Comment by bmw** [comment]
Hey Seth. @alexzorin has actually been working on this issue and https://github.com/certbot/certbot/issues/4635 a bit lately. I'll let him decide whether he wants to share his current thinking more widely right now, but regardless, stay tuned. I think people should expect to see something here in the coming months.
