### ISSUE TITLE
Augeas parsing error

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4637]
As reported at https://community.letsencrypt.org/t/the-error-was-pluginerror-there-has-been-an-error-in-parsing-the-file/33792, Certbot currently errors out when parsing the following snippet of an Apache configuration file:
```
RewriteEngine On
RewriteMap symlinks prg:/var/www/redirector.pl
RewriteCond ${symlinks:%{HTTP_HOST}} !=""
RewriteRule ^/(.*) http://${symlinks:%{HTTP_HOST}}/$1 [R=301,L]
```
The line causing the problem is:
```
RewriteCond ${symlinks:%{HTTP_HOST}} !=""
```
Apache doesn't have a problem with this syntax.

cc @domcleal

**Comment by domcleal** [comment]
Thanks @bmw. This looks the same as #3536, which we're tracking (but still unfixed) at https://github.com/hercules-team/augeas/issues/429.

**Comment by bmw** [comment]
Ah you're right!

Thanks for taking a look and I'm closing this as a duplicate.
