### ISSUE TITLE
Support --certbot-dir?

### ISSUE THREAD

**Issue by pde** [certbot/certbot#4638]
There are a bunch of cases where for various reasons people want to change Certbot's directories, including running as non-root, testing things, and even [performance through parallelism](https://github.com/certbot/certbot/pull/4449#issuecomment-299802507). The UI for that is quite awkward, with three flags (`--config-dir`, `--work-dir` and `--logs-dir`) that the user has to provide.

Perhaps we should support a `--certbot-dir` flag that sets `--config-dir`, but also sets `--work-dir` to something like `$CONFIG_DIR/state` and `--logs-dir` to `$CONFIG_DIR/logs`, so the user only needs to set one flag.

**Comment by bmw** [comment]
Related: #3079

**Comment by bmw** [comment]
Closing in favor of the older #3079 which discusses a flag like this as well as other options.
