### ISSUE TITLE
Prompt to press enter for manual challenge is confusing

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#4641]
Running `certbot-auto --staging --manual certonly --preferred-challenges=dns -d cname.hoffman-andrews.com`, I get:

```
Please deploy a DNS TXT record under the name
_acme-challenge.cname.hoffman-andrews.com with the following value:

09umZRw2jgsPJWudFFgMiFbUdbqsEvF0MkSOxxBK7GQ

Once this is deployed,
-------------------------------------------------------------------------------
Press Enter to Continue
```

This is confusing, because it looks like "Once this is deployed," is part of a sentence that got cut off, since there's a horizontal line immediately after it, and because "Press Enter to Continue" uses different case and doesn't end in a period.

**Comment by anna-liao** [comment]
I'm working on this one.

**Comment by anna-liao** [comment]
Pull request at
https://github.com/certbot/certbot/pull/4704
