### ISSUE TITLE
What is configargparse.ACTION_TYPES_THAT_DONT_NEED_A_VALUE and why is it throwing errors?

### ISSUE THREAD

**Issue by ahaw021** [certbot/certbot#4659]
I thought this would be a Python 3.6 Issue however it happens in 2.7 as well

## My operating system is (include version):
Windows Server 2012 R2 Python 3.6

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

pip install certbot==0.13.0

## I ran this command and it produced this output:

certbot certificates

## Certbot's behavior differed from what I expected because:

I would expect cetbot to list the certificates
I have fixed by commenting out a line in the util section 
configargparse.ACTION_TYPES_THAT_DONT_NEED_A_VALUE.add(ShowWarning)

**Before Fix (Python 3.6)**

![image](https://cloud.githubusercontent.com/assets/26753809/26031265/3a59ed98-38b0-11e7-8729-31d28289eb36.png)

**Before Fix (Python 2.7)**

![image](https://cloud.githubusercontent.com/assets/26753809/26031303/1f4e81de-38b1-11e7-9607-2be466a15e67.png)

**Fix (Both 3.6 and 2.7):**

![image](https://cloud.githubusercontent.com/assets/26753809/26031276/6ec58146-38b0-11e7-8f71-b8fdb2beae9e.png)

**After Fix (Python 3.6)**

![image](https://cloud.githubusercontent.com/assets/26753809/26031262/207b74c8-38b0-11e7-8e5a-f4dd857d6aac.png)

**After Fix (Python 2.7):**

![image](https://cloud.githubusercontent.com/assets/26753809/26031312/5f2461ca-38b1-11e7-9d1c-127b6d70017d.png)

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

![image](https://cloud.githubusercontent.com/assets/26753809/26031245/91a18454-38af-11e7-9836-2c47f533bc73.png)

  File "c:\certbot-test\lib\site-packages\certbot\util.py", line 440, in add_deprecated_argument
    configargparse.ACTION_TYPES_THAT_DONT_NEED_A_VALUE.add(ShowWarning)
AttributeError: 'tuple' object has no attribute 'add'

**Comment by yan12125** [comment]
ConfigArgParse 0.12.0 changed its internal and breaks certbot. See #4648

**Comment by ahaw021** [comment]
no problems - looks like there is a fix in the works

will close this off

**Comment by yan12125** [comment]
Hey, don't comment out codes! The correct fix is changing
```
configargparse.ACTION_TYPES_THAT_DONT_NEED_A_VALUE.add(_ShowWarning)
```
to
```
configargparse.ACTION_TYPES_THAT_DONT_NEED_A_VALUE += (_ShowWarning,)
```

**Comment by ahaw021** [comment]
I can comment out codes if i so choose ;)

have tried your suggestion but it's not working

![image](https://cloud.githubusercontent.com/assets/26753809/26032801/93c34c10-38df-11e7-93d9-d754309ee3ee.png)

![image](https://cloud.githubusercontent.com/assets/26753809/26032807/a1cb05d2-38df-11e7-9a56-413885185c9f.png)

**Comment by ahaw021** [comment]
also tried ShowWarning as how it was originally defined

![image](https://cloud.githubusercontent.com/assets/26753809/26032819/db91fb18-38df-11e7-82c8-24c4055b1d11.png)


![image](https://cloud.githubusercontent.com/assets/26753809/26032817/d1f352be-38df-11e7-8e41-c4a6b0aabcb4.png)

**Comment by yan12125** [comment]
Sorry, it should be:
```
configargparse.ACTION_TYPES_THAT_DONT_NEED_A_VALUE += (ShowWarning,)
```

**Comment by ahaw021** [comment]
thanks 

works like a charm

![image](https://cloud.githubusercontent.com/assets/26753809/26033040/bd57021e-38e5-11e7-980b-7be6423517a2.png)

![image](https://cloud.githubusercontent.com/assets/26753809/26033132/03bdf08a-38e8-11e7-9fce-63741062bf91.png)


Andrei
