### ISSUE TITLE
DocumentRoot not found

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4667]
If I change the ending of `certbot-apache/certbot_apache/tests/testdata/debian_apache_2_4/multiple_vhosts/apache2/sites-available/encryption-example.conf` from:
```
    </Directory>

</VirtualHost>
```
to
```
    </Directory></VirtualHost> # line formatted this way to test Augeas span
```
`certbot_apache.tests.parser_test.BasicParserTest.test_find_dir` fails.

**Comment by joohoi** [comment]
This seems to be fixed along the way. There is a failing test however:
`test_make_vhost_ssl_with_mock_span (certbot_apache.tests.configurator_test.MultipleVhostsTest)` but that is because of the hardcoded byte indices in the test (testing the Augeas span), so it's expected.
