### ISSUE TITLE
Write an Exim installer plugin

### ISSUE THREAD

**Issue by pde** [certbot/certbot#4671]
This would be a big win for email security!

**Comment by zjs** [comment]
Planning to work on this August 16-17. If there are any additional requirements to keep in mind, let me know.

**Comment by sydneyli** [comment]
Assigning this to myself since it's relevant to STARTTLS Everywhere; will get to it after finishing postfix plugin.

**Comment by bmw** [comment]
I think we've decided against mail server plugins like this so I'm closing this issue.
