### ISSUE TITLE
Python warning on Ubuntu Trusty

### ISSUE THREAD

**Issue by Rudloff** [certbot/certbot#4679]
## My operating system is (include version):
Ubuntu 14.04.5 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Ubuntu package 0.12.0-1+certbot~trusty+5

## I ran this command and it produced this output:
`certbot renew` outputs this warning:
```
/usr/lib/python2.7/dist-packages/OpenSSL/rand.py:58: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  result_code = _lib.RAND_bytes(result_buffer, num_bytes)
```

## Certbot's behavior differed from what I expected because:
The command seems to correctly renew the certificates but it is a bit annoying because cron sends me an email each time.

As mentionned in #4299, I think this might be fixed by updating the python-openssl provided in the Cerbot PPA.

**Comment by Rudloff** [comment]
I also get the same error on Ubuntu 16.04.2 LTS with certbot 0.12.0-1+certbot~xenial+5.

**Comment by oerdnj** [comment]
This is a pyOpenSSL bug introduced as incompatibility between cffi and pyopenssl binding (not the first time this has happened according to the Internet).

I will update pyOpenSSL and cffi to latest upstream versions and if this doesn't go away it needs to be fixed in pyOpenSSL.

**Comment by alex** [comment]
If this is still happening with the latest release, please file a pyOpenSSL bug and we can fix it up.

That said, what's pyOpenSSL's random number generator? It probably ought to be ported to `os.urandom`.

**Comment by Rudloff** [comment]
I don't get these warnings anymore since the upgrade to python-openssl 17.0.0-0+certbot~trusty+1.

**Comment by Talkless** [comment]
Same error on Debian 8 (Jessie).

**Comment by rpadovani** [comment]
This is quite annoying because I receive emails every day with this error. Any way to silence that from the cron job for the renew, or any ETA on the fix?

**Comment by RalphCorderoy** [comment]
Opened https://github.com/pyca/pyopenssl/issues/698 as it's still occurring in Debian 8.9.

**Comment by adferrand** [comment]
This issue concerns an EOL version of Ubuntu. Related issue about Debian Jessie has been resolved. I am closing the issue.
