### ISSUE TITLE
DNS verification for multiple subdomains (given the lack of wildcard support)

### ISSUE THREAD

**Issue by damianobarbati** [certbot/certbot#4681]
It's pretty painful to set a txt record for each subdomain wanted.

My case for instance:
- .it domain
- .com domain
- subdomains dev.*, stg.*, www.* and [empty].*

I have to set **8 txt records**, one for each of them! Why not giving the chance to set just 1 txt record for domain and having certbox check automatically for a common txt record?

**Comment by SwartzCr** [comment]
Maybe the automatic dns validation that @zjs is working on can help with this?

**Comment by zjs** [comment]
@damianobarbati: Which plugin are you currently using? What DNS provider(s) do you use?

> Why not giving the chance to set just 1 txt record for domain and having certbox check automatically for a common txt record?

As a part of the ACME protocol, you need to prove control over each FQDN. As a result of CAB Forum requirements, each of proof of control must involve a random token.

**Comment by zjs** [comment]
I'm still interested in answers to above questions, but I don't think there's anything actionable here at the moment (and I hope that the new DNS plugins can greatly simplify this workflow), so I'm going to go ahead and close this.
