### ISSUE TITLE
Add certbot-route53 to our tree

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4688]
After talking to the maintainers we're going to make https://github.com/lifeonmarspt/certbot-route53 an official plugin and move it into our repo. Things we want with this transition are:

* Git history is preserved
* We have a plugin under the name certbot-dns-route53 in our tree
* We have a plugin or at least something to upload to the name certbot-route53 on PyPI so users under that name continue to get updates as the plugin is further developed. In theory, this could be the same package as `certbot-dns-route53` but we'd want to make sure the user experience is sane if both are installed.
* The certbot-route53 package should continue to work with the plugin name `certbot-route53:auth` due to the way we name 3rd party plugins (see #4351). Whether or not it also works with `certbot-route53` is an implementation detail in my opinion.

I don't really have a preference for how this is implemented. My instinct is it'll be easiest to make `certbot-route53` a shim package around `certbot-dns-route53`. We did something similar for the `letsencrypt` package in our 0.7.0 release. This can be left up to whoever takes this ticket though.

@zjs, if you have an interest in working on this, that'd be useful, otherwise, I can take it when I get some spare cycles.

**Comment by bmw** [comment]
@zjs, what's the plan for uploading these packages to PyPI? Make `certbot-route53` a shim package around `certbot-dns-route53`? If so, do you have time to prepare a simple shim package? You can see an example of this at https://github.com/certbot/certbot/tree/v0.7.0/letsencrypt-apache.

**Comment by zjs** [comment]
There's a change ready to go for that here: https://github.com/lifeonmarspt/certbot-route53/pull/5

**Comment by bmw** [comment]
Oh wow. Thanks for taking care of that. That's super helpful.

**Comment by bmw** [comment]
With lifeonmarspt/certbot-route53#5, I think this has been resolved. Thanks Zach!
