### ISSUE TITLE
IPv6-only not properly working?

### ISSUE THREAD

**Issue by mdavids** [certbot/certbot#4698]
## My operating system is (include version):
Ubuntu 16.04.2 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt-get install certbot
(now running: 0.12.0-1+certbot~xenial+5)

## I ran this command and it produced this output:
certbot certonly --webroot -w /var/www-cultrix/ -d cultrix.nl -d www.cultrix.nl --must-staple --rsa-key-size 4096 --staging

## Certbot's behavior differed from what I expected because:
```
 - The following errors were reported by the server:

   Domain: www.cultrix.nl
   Type:   connection
   Detail: DNS problem: NXDOMAIN looking up A for www.cultrix.nl

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.

```
###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

[not relevant -  errors seems self-explanatory enough]

**Comment by zjs** [comment]
I see an AAAA record for cultrix.nl, but I don't see any A or AAAA records for www.cultrix.nl (the FQDN the server complaining about).

**Comment by mdavids** [comment]
Oops, my bad! Fixed it, will try again. sorry for wasting your time.
