### ISSUE TITLE
Test dockerfiles regularly

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4705]
We should test our Dockerfiles regularly with automated tests so we know if they break.

**Comment by kevinkle** [comment]
I'll type on something this morning at Pycon.

**Comment by bmw** [comment]
We now do this for `Dockerfile-dev` but not for our production Dockerfiles. There is currently a little uncertainty with what we are going to do with our Docker images going forward so I'm moving this to wishlist. If we keep our Docker images though, this is something we should set up.

**Comment by bmw** [comment]
I'm closing this in favor of https://github.com/certbot-docker/certbot-docker/issues/15.
