### ISSUE TITLE
Certboot only configure one apache configuration file per domain

### ISSUE THREAD

**Issue by juanyque** [certbot/certbot#4714]
## My operating system is (include version):

debian_version 8.8
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

deb http://ftp.debian.org/debian jessie-backports main

## I ran this command and it produced this output:

certbot --apache

I have two different apache configuration files for two different ports but only one file was reconfigured.

## Certbot's behavior differed from what I expected because:

I expect both will be changed or tool allow manage it in any way (for example: showing the port on available domain names list to select witch will be configured)

**Comment by SwartzCr** [comment]
Out of curiosity which ports are the configs for? And which one got edited by certbot?
I'm not sure how we should deal with situations like this, since I don't think we pay too much attention to which ones are enabled, so we might not want to corrupt all the files that are in sites-available just because they have similar domains in them? But maybe @joohoi has different thoughts

**Comment by juanyque** [comment]
I have two configuration files: one for 443 port and other one for 8006.

Only 8006 file was configured.

The most strange was that really only 443 was published to Internet on the router.

**Comment by SwartzCr** [comment]
What were the configuration changes? Did you select secure mode - and then got a rewrite rule added to it to forward it to the 443 config? Or is this for cert locations?

**Comment by juanyque** [comment]
Configuration changes:
- Cert configuration (note that I had a chain entry that was removed, but work)
- It touch ProxyPass configuration entries, but no changes really (only blank spaces)

I does not select secure mode, because I had my own rules for non secure port.

**Comment by SwartzCr** [comment]
Would you be willing to share the final configs? Feel free to replace your domain with an example one if you don't want to share that.

**Comment by SwartzCr** [comment]
I am going to close this issue as stale, but will re-open it if @juanyque can provide more information
I'm also going to tag @joohoi in case he wants to incorporate this into his improvement of the apache plugin
