### ISSUE TITLE
Temporal files and dirs not removed from /tmp

### ISSUE THREAD

**Issue by sahsanu** [certbot/certbot#4719]
Since certbot-auto 0.14.0, every time `certbot-auto renew --quiet` runs on my cron job it left behind a tmp file in /tmp.

Just an example:

```
-rw-------  1 root root  361 May 22 12:17 tmpzdqsnC
-rw-------  1 root root  361 May 22 18:17 tmptUuhXk
-rw-------  1 root root  361 May 23 00:17 tmp1T_Xes
-rw-------  1 root root  361 May 23 06:17 tmp3vaADu
-rw-------  1 root root  361 May 23 12:17 tmpSuRRuU
-rw-------  1 root root  361 May 23 18:17 tmpgtxFOp
-rw-------  1 root root  361 May 24 00:17 tmpZF3Xp3
```
The content of these files are like this:
```
2017-05-22 12:17:01,586:DEBUG:certbot.main:certbot version: 0.14.1
2017-05-22 12:17:01,586:DEBUG:certbot.main:Arguments: ['--version']
2017-05-22 12:17:01,586:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
```
Also there is a tmp dir,

`drwx------ 2 root root 4096 May 24 00:33 tmp.ccaHF7JIEe/`

Tha only have a file inside:

`-rw-r--r-- 1 root root 4614 May 19 12:28 fetch.py`

As I said, checking the tmp files, it is happening from version 0.14.0 and I think they should be removed automatically.

Here a community buddy asking the same question. https://community.letsencrypt.org/t/certbot-auto-recently-starting-to-leave-files-in-tmp/34789

**Comment by bmw** [comment]
Are you sure these files are left by the command `certbot-auto renew --quiet`? If you run that command manually, are additional files created? If so, is the command failing?

I was able to reproduce it though in some cases. In particular, `certbot-auto --help` creates the file.

**Comment by sahsanu** [comment]
> Are you sure these files are left by the command certbot-auto renew --quiet? If you run that command manually, are additional files created? If so, is the command failing?

Yes, the files are left by `certbot-auto renew --quiet` command, their timestamps are the same as my cron job runs. And the command is not failing. Anyway, I can reproduce this behaviour with any command executed manually.

```
certbot-auto renew
certbot-auto renew --help
certbot-auto --help
certbot-auto --version
certbot-auto certificates
certbot-auto certificates --debug
```

I've created a dirty script to log this issue, the script is this and executes the command `certbot-auto certificates --debug`:

```
#!/bin/bash

touch /tmp/tmpControl
> /var/log/letsencrypt/letsencrypt.log
echo -e "#Checking certbot-auto issue #4719 - $(date)\n"

echo -e "#Executing certbot-auto certificates --debug:\n"
/root/certbot/certbot-auto certificates --debug

#Get last tmp* file
echo -e "\n#Executing ls -lrt /tmp/tmp*:\n"
tmpdir="$(ls -lrt /tmp/tmp* > /tmp/issue-tmp)"
lasttmpfile="$(cat "/tmp/issue-tmp" | tail -1 | awk -F ' ' '{print $NF}')"

if [ "${lasttmpfile}" = "/tmp/tmpControl" ]; then
    echo -e "\n#There is no tmp file created by certbot-auto in /tmp\n"
else
    echo -e "\n#Last tmp file found in /tmp is ${lasttmpfile}\n"
        ls -l "${lasttmpfile}"
        echo -e "\n#Contents of file ${lasttmpfile}\n"
        cat "${lasttmpfile}"
fi

echo -e "\n#Contents of /var/log/letsencrypt/letsencrypt.log:\n"
cat "/var/log/letsencrypt/letsencrypt.log"
rm /tmp/tmpControl
```
I've executed the script 3 times.

**1.-** It left behind the file `/tmp/tmpccsciq`
Ourput: https://gist.github.com/sahsanu/22e47e2e62196692dd1fdd933cb26e18

**2.-** I removed the virtualenv dir `/root/.local/share/letsencrypt/` and it didn't left behind a tmp file.
Output: https://gist.github.com/sahsanu/ffa1cadee5e0d3cb59fe40c885e9a978

**3.-** A new execution and again it left behind the file `/tmp/tmp2PQrpg`
Output: https://gist.github.com/sahsanu/423805cd66d2eb6b9a678be0a04209b3

> The temporary directory is interesting and is created by certbot-auto. Do you know if certbot-auto tried to update to 0.14.1 and failed?

This directory only appears in 1 of my servers, I didn't receive any notification about a failed upgrade of certbot-auto (self upgrade), if any error to upgrade I would receive a mail and as I said, I didn't receive any. Anyway, I can't reproduce this issue (regarding the dir) in any other server so I suppose it was just a temporal failure.

> Are there any currently running instances of certbot-auto on your system?

No, there are no other instances of `certbot-auto` running at the same tyme in my systems.

If you need any other test or whatever, don't hesitate to contact me.

Appreciate your hard work.

**Comment by bmw** [comment]
@sahsanu, thanks for the detailed information. One more question for you: What OS is this on?

**Comment by sahsanu** [comment]
@bmw, Debian Jessie 8.8 64 bits
