### ISSUE TITLE
Syntax Error on Valid Apache RequestHeader Conf Statement

### ISSUE THREAD

**Issue by mfurdyk** [certbot/certbot#4734]
The error was: PluginError('There has been an error in parsing the file /etc/httpd/vhosts/zulu.xyz.net.conf on line 41: Syntax error',)

The line is:

RequestHeader set X-Forwarded-Proto https expr=(%{HTTP:CF-Visitor}='{"scheme":"https"}')

This line is required for Symfony to work on our domain so I can't comment it out...

**Comment by SwartzCr** [comment]
Can you tun the apache config tester and see what it outputs?

**Comment by mfurdyk** [comment]
Yup, no errors on Apachectl configtest (-t):

[root@cloud vhosts]# apachectl -t
Syntax OK
[root@cloud vhosts]#

**Comment by SwartzCr** [comment]
@domcleal or @joohoi have any ideas? Is this something that Augeas can't read?

**Comment by domcleal** [comment]
Thanks for the report, I've filed it against Augeas to fix at https://github.com/hercules-team/augeas/issues/470 as it does appear to be a parsing bug.

Putting spaces around the single quote marks should let Augeas parse it, and I _think_ this might be valid Apache syntax too (sorry, untested):

    RequestHeader set X-Forwarded-Proto https expr=(%{HTTP:CF-Visitor} = '{"scheme":"https"}' )

**Comment by mfurdyk** [comment]
Sadly no - tried that :(

May 26 17:33:50 cloud.tigweb.org httpd[5443]: AH00526: Syntax error on line 41 of /etc/httpd/vhosts/zulu.eqwiphubs.net.conf:
May 26 17:33:50 cloud.tigweb.org httpd[5443]: RequestHeader has too many arguments
