### ISSUE TITLE
Add --install(ation)-only flag to certbot-auto

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4741]
This allows people to separate installing Certbot and running it for the first time. It does the same thing as `certbot-auto --version`, however, this flag makes it explicit this functionality is available and doesn't actually invoke Certbot.

cc @nuxwin

**Comment by nuxwin** [comment]
@bmw 


@bmw 

Really, your involvement here is much appreciated ;)
Keep up your good work ;)

Thank again.

**Comment by bmw** [comment]
As I've described it, this flag would also update Certbot to the latest version. I think there's benefit of having this flag work this way as well (and those who don't want this behavior can use `--no-self-upgrade`) so we should make this clear in the flag name/documentation.

**Comment by sydneyli** [comment]
ill take this on for the PR demo tomorrow!

**Comment by nuxwin** [comment]
@sydneyli Thank youf or merging this ;) That is much appreciated.
