### ISSUE TITLE
How to change 'redirect to secure HTTPS' ... to 'allow both HTTP and HTTPS'?

### ISSUE THREAD

**Issue by TJH43** [certbot/certbot#4749]
My operating system is Ubuntu 14.04 with Apache 2.4.7

I ran "certbot --apache" and answered the question "Please choose whether HTTPS access is required or optional" with "2: Secure - Make all requests redirect to secure HTTPS access".  Eight certificates were installed with this option.

What is the recommended command sequence or method  to reset this option to "1: Easy - Allow both HTTP and HTTPS access to these sites."?

The 443 vhost file options-ssl-apache.conf now contains "SSLOptions +StrictRequire" ....

....and the "anyPort" vhost mydomain.conf file now contains "RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]".

Thanks

**Comment by SwartzCr** [comment]
Hi @TJH43 I commented on your response on another closed ticket - but the way to do this is to use the rollback command. It's not very well documented, but here's the pydoc info: https://certbot.eff.org/docs/api/client.html?highlight=rollback#certbot.client.rollback
or there's a little info in the user guide: https://certbot.eff.org/docs/using.html?highlight=rollback
That should allow you to return all of those configs to their original state and then to re-make without the secure upgrade.
Let me know if that doesn't work!

**Comment by joohoi** [comment]
I think this is resolved, feel free to comment here if this is not the case and we'll reopen the issue.
