### ISSUE TITLE
Certbot-auto virtual env setup fails with >1k lines of OpenSSL errors

### ISSUE THREAD

**Issue by pokrface** [certbot/certbot#4751]
## My operating system is (include version):
Ubuntu 16.04.02 LTS (4.4.0-72)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Certbot-auto, currently using version 0.14.2

## I ran this command and it produced this output:
Running certbot-auto produces [this output](https://gist.github.com/pokrface/55a3f71e975098f7ebfd695560f5425f). There are lots of openssl references in there, and I believe my problem might be because I'm using OpenSSL 1.1.0f. However, I thought certbot supported OpenSSL 1.1.0 as of at least a few months ago (though I don't know).

## Certbot's behavior differed from what I expected because:
Certbot fails to bootstrap and will not start.

## Here is a Certbot log showing the issue (if available):
N/A - certbot doesn't get far enough to start logging and so the log contains no information

## Speculation follows
I'm using OpenSSL 1.1.0f and I suspect this is the problem.

**Comment by SwartzCr** [comment]
Yes that is likely the problem. You might instead try to install it from the ubuntu ppa: https://launchpad.net/~certbot/+archive/ubuntu/certbot
Which also has 0.14.2 - though it might still break if you have the wrong version of openssl installed.
Let me know if that doesn't work?

**Comment by SwartzCr** [comment]
Alternatively you might just need to rebuild certbot-auto. You could try deleting it and installing it again.
What is possibly happening here is that when you built certbot-auto it built a version of pythoncryptography to go along with your version of openssl - and made bindings to it's API. Now those API endpoints have changed and it has the wrong bindings. So if you rebuild pythoncryptography it might fix itself.
You can do this by having certbot-auto remake it's virtual environment. This happens typically only when we bump a version, but you can make it do this be deleting and re-installing it

**Comment by pokrface** [comment]
Thanks, @SwartzCr - the errors occur during the virtual environment build, while certbot is compiling pythoncryptography. Based on the giant error dump, the failing command is:

```
Command 
"/home/lee/.local/share/letsencrypt/bin/python2.7 -u -c "import 
setuptools, 
tokenize;__file__='/tmp/pip-build-7qg1M5/cryptography/setup.py';exec(compile(getattr(tokenize,
 'open', open)(__file__).read().replace('

', '

'), __file__, 'exec'))" install --record 
/tmp/pip-SOmLff-record/install-record.txt 
--single-version-externally-managed --compile --install-headers 
/home/lee/.local/share/letsencrypt/include/site/python2.7/cryptography" 
failed with error code 1 in /tmp/pip-build-7qg1M5/cryptography
```

I'm willing to kill certbot and reinstall from the PPA, but I'm not hopeful that will fix the issue if it's an openssl problem (and I'm stuck on the newer version of openssl for other external requirements that I cannot change).

**Comment by yan12125** [comment]
Apparently OpenSSL 1.1.0f changes some function prototypes and breaks python-cryptography. Bumping to cryptography 1.8.2 (#4755) should fix it. 
Ref: https://github.com/pyca/cryptography/pull/3603

**Comment by SwartzCr** [comment]
Okay - so we've bumped the version of cryptography that we require - unfortunately that won't fix your problem until we do a release.
You could clone this repo and run it from it's current state via a virtual environment (details on how to do this can be found in the developer guide: https://certbot.eff.org/docs/contributing.html) or wait until our next release (which should be in a week)

**Comment by pokrface** [comment]
That's awesome, @SwartzCr, thank you. I've got >60 days on all my active certs, so I'll happily wait for the next tagged release and update then. I'll close this issue if it nails the problem. Thanks very much for the quick response—you folks are all doing excellent work!

**Comment by pokrface** [comment]
Confirm that this issue no longer affects me with certbot 0.15.0 and OpenSSL 1.1.0f. Thank you!
