### ISSUE TITLE
Confusing Error message

### ISSUE THREAD

**Issue by gitrago** [certbot/certbot#4759]
## My operating system is (include version):

ubuntu 16.10
## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

apt-get
## I ran this command and it produced this output:

I misconfigured my DNS zone, my A record pointed to the wrong IP.

## Certbot's behavior differed from what I expected because:

I got
```
Domain: yourdoma.in
Type:   unknownHost
Detail: No valid IP addresses found for yourdoma.in

To fix these errors, please make sure that your domain name was entered correctly and the DNS A record(s) for that domain contain(s) the right IP address.
```

This message suggests that the DNS lookup failed while in fact it didn't. Would be more useful if it said something like `Type: notReachable`

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
2017-05-30 12:51:21,447:INFO:letsencrypt.reporter:Reporting to user: The following errors were reported by the server:

**Comment by SwartzCr** [comment]
Thanks for the feedback @gitrago - if you want to make a PR for this we'd be happy to review and merge it. I've added some labels to it that will hopefully help us prioritize it when we work on ui/ux revisions

**Comment by Baeumla** [comment]
Since this is already a month old, I assume @gitrago does not want to make the PR for this, so I would do it

**Comment by SwartzCr** [comment]
@Baeumla please do! Tag me in it so that I can review and merge it, thanks!

**Comment by Baeumla** [comment]
@SwartzCr Okay. But since I'm working on two other issues right now, this could take a little while.

**Comment by Baeumla** [comment]
I got some time today to take a deeper look into this but I can't make out the functions which set the error type for the failed challenges. 

Is it possible that this happens somewhere in `acme/client.py` s function `request_challenges` ? Unfortunately this function uses `_authzr_from_response` which is not documented, so its kind of hard to see what it does. 

I'm sorry that I wasn't able to create the PR for this right away but I'm still pretty new to the project.

**Comment by SwartzCr** [comment]
The text looks like the `_ERROR_HELP_COMMON` text https://github.com/certbot/certbot/blob/498f8ad75ca6d677bd8898453300e1e6c60a731c/certbot/auth_handler.py#L445
Which gets raised from `_generate_failed_chall_msg`:
https://github.com/certbot/certbot/blob/498f8ad75ca6d677bd8898453300e1e6c60a731c/certbot/auth_handler.py#L495
both in auth_handler.py
I think the whole stack starts in `get_authorizations` in the same file.
It seems that we have optional types to add things to that error output, and in this case it seems the text for the "connection" error would be most apropriate, but for whatever reason the `typ` "connection" isn't being added to the failed challenge. Which seems like it'd happen here? https://github.com/certbot/certbot/blob/498f8ad75ca6d677bd8898453300e1e6c60a731c/certbot/auth_handler.py#L208
Let me know if that helps! If you want more direct help feel free to drop in on IRC and ask some questions, we are in #letsencrypt-dev on irc.freenode.net

**Comment by Baeumla** [comment]
Thank you foru your response, but what I actually wanted to figure out was where the Error in the ChallengeBody is determined. I thought that this happens somewhere in the `acme/client.py` and I thought that the problem might be in there.

**Comment by SwartzCr** [comment]
Ah got it, let me know if you make any progress

**Comment by SwartzCr** [comment]
@Baeumla have you had a chance to try making a PR for this?

**Comment by Baeumla** [comment]
@SwartzCr Since I started a new job I barely got time to work on this, so unfortunately not.
