### ISSUE TITLE
Domain (or any other prefix of "domains") in cli.ini breaks renew

### ISSUE THREAD

**Issue by andreas-wolf** [certbot/certbot#4774]
## My operating system is (include version):
openSUSE Leap 42.2

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
certbot-auto renew --dry-run

Currently, the renew verb is capable of either renewing all installed certificates that are due to be renewed or renewing a single certificate specified by its name. If you would like to renew specific certificates by their domains, use the certonly command. The renew verb may provide other options for selecting certificates to renew in the future.

## Certbot's behavior differed from what I expected because:
It should simulate to renew the certs.

## Here is a Certbot log showing the issue (if available):
2017-06-03 22:13:31,963:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 742, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 692, in renew
    renewal.handle_renewal_request(config)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/renewal.py", line 370, in handle_renewal_request
    raise errors.Error("Currently, the renew verb is capable of either "
Error: Currently, the renew verb is capable of either renewing all installed certificates that are due to be renewed or renewing a single certificate specified by its name. If you would like to renew specific certificates by their domains, use the certonly command. The renew verb may provide other options for selecting certificates to renew in the future.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
N/A

Further information
The reason for this error is a line in cli.ini:
domain = d1.example.com,d2.example.com

I added this line because of this "workaround" https://community.letsencrypt.org/t/set-default-cn-name-for-multiple-certificate/21625/4 mentioned in this issue: https://github.com/certbot/certbot/issues/3698
I also found this issue about domains in cli.ini https://github.com/certbot/certbot/issues/4096

From https://github.com/certbot/certbot/issues/4096 it seems that the proper key in cli.ini is "domains" instead of "domain". The odd thing is, that I could get a cert with all my domains using "domain".
Unfortunately the proper key is undocumented in https://github.com/certbot/certbot/blob/master/examples/cli.ini

Either there is no error message about the wrong key or bug #4096 fixes only a part of the problem.

**Comment by schoen** [comment]
@pde, it appears that for some reason the solution in #4479 was incomplete, apparently due to another bug.

**Comment by schoen** [comment]
@andreas-wolf, thanks for telling us about this problem.

The reason that I took out the documentation about the key from `cli.ini` was to *stop* people from trying to specify domains in `cli.ini`. Specifying domains there does not match our general understanding of how Certbot should be used or what these options mean, because it basically hard-codes a single set of domains system-wide, while we intend Certbot to be usable to manage many different certificates, each of which covers a completely different set of domains.

Removing the documentation about this key there has reduced the number of people who ran into bugs like this because fewer people think of the idea of specifying domains there. In parallel, #4479 says that this key should be completely ignored by the renewal script when it is placed in `cli.ini` (but apparently that didn't work in this case due to a further bug, which we'll need to try to fix).

**Comment by pde** [comment]
Hi @andreas-wolf!

The problem is that you specified `domain = ` in your `cli.ini` file, while Certbot expects `domains = `.  Argparse was clever enough to figure out that by `"domain"` you meant `"domains"`, but our code for handling corner cases wasn't clever enough to do the same.

**Comment by pde** [comment]
@bmw it's amazing that this is the first time we've had a bug like this...

**Comment by pde** [comment]
Although it's easy to fix if the user supplies `domain = ` in the config file, I can't see the easy way to ask argparse / configargparse whether `dom = ` also maps to `domains`. I think that's what I'd want from a solution, but it doesn't feel like a good use of time to research. But leaving this open in case someone cares and wants to spend time on this.

**Comment by andreas-wolf** [comment]
@schoen @pde
Thanks for your message. Wouldn't it be easier to remove the domain(s) key from the cli.ini file parser if you don't want people to use it any more? Or at least give a deprecation warning in the documentation.

@pde 
"it's amazing that this is the first time we've had a bug like this"
I'm a developer myself and that is one of the sentences I hear a lot. Apparently I have the magic ability to break things in an odd way and some of my colleagues already hate my code reviews. ("Odd. It was working on my machine.") ;-)
