### ISSUE TITLE
ubuntu1604 install ssl certificate has  a error

### ISSUE THREAD

**Issue by kelelee** [certbot/certbot#4778]
## My operating system is (include version):
ubuntu1604

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
./letsencrypt-auto certonly --standalone --email admin@xxx.org -d xxx.org

output:
OSError: Command /root/.local/share/letsencrypt/bin/python2.7 - setuptools pkg_resources pip wheel failed with error code 2

**Comment by SwartzCr** [comment]
could you attach the more verbose error log which can be found in `/var/log/letsencrypt`? This will help us figure out which package is causing the problem
Altrenately if you destroy the virtualenv that certbot-auto has made and reinstall it from scratch it should fix the problem

**Comment by bmw** [comment]
Since this issue hasn't seen any updates in almost 2 years, I'm closing it. If you're still having this problem, please open a new issue and completely fill out the issue template.
