### ISSUE TITLE
Certbot doesn't update data for reminder mail

### ISSUE THREAD

**Issue by MichaelKohler** [certbot/certbot#4787]
## My operating system is (include version):

Linux Debian

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

certbot-auto

## I ran this command and it produced this output:

certbot renew

## Certbot's behavior differed from what I expected because:

The certificate is extended, but I still get a reminder email about expiry with an incorrect date.

![screen shot 2017-06-06 at 21 28 53](https://user-images.githubusercontent.com/330324/26848018-5b681c6a-4aff-11e7-8f3b-cc1d82d0621a.png)

**Comment by SwartzCr** [comment]
Did you add or remove any domains from the certificate? If so then you got an expirey for the old version of it. If not @jsha should be made aware that this might be a bug with expirey emails

**Comment by MichaelKohler** [comment]
I haven't removed any domains recently (at least not on purpose). Is there a way I could check this?

**Comment by jsha** [comment]
This is warning you about [this certificate](https://crt.sh/?id=105855613), issued on March 18 and expiring June 16, for the single name `juniorfoodart.ch`. You have [a more recent certificate](https://crt.sh/?id=148872494) that has the names `juniorfoodart.ch` and `www.juniorfoodart.ch`, so Let's Encrypt considers it a different certificate, and warns you that the other one is expiring.
