### ISSUE TITLE
Stop using Augeas

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4799]
While Augeas saved us writing a grammar for Apache config files, it has caused us a lot of other issues. Off the top of my head:

hercules-team/augeas#423
hercules-team/augeas#435
hercules-team/augeas#466
hercules-team/augeas#467
hercules-team/augeas#470
hercules-team/python-augeas#15
hercules-team/python-augeas#21
and recently hercules-team/python-augeas#30

There are also well over a dozen bugs that have been found in their Apache configuration parsing that have subsequently been fixed. While upstream has always been willing to help (and their help has been greatly appreciated), we continue to have issues, some of which are quite serious. Even worse, issues like hercules-team/python-augeas#15 have sat around for over a year with no signs of progress.

While Augeas has been useful for us, I think it's time we investigate finding another library for parsing Apache configuration files. Ideally, this library should not be reliant on any non-Python libraries or programs as this dramatically simplifies packaging.

**Comment by ahaw021** [comment]
hi @bmw 

Is augeas used for apache files only?

How are you parsing NGINX files?

Andrei

**Comment by bmw** [comment]
Yes. We wrote our own parser for nginx using `pyparsing`. You can find this code [here](https://github.com/certbot/certbot/blob/master/certbot-nginx/certbot_nginx/nginxparser.py).

**Comment by SwartzCr** [comment]
I +1 this
While the augeas maintainers have been really great about helping us out when we run into an issue, it's been hard to rely on them to fix major issues when they come up. I think moving to something that either we have more control over, or is more actively maintained (outside of bugfixes) could be helpful.

**Comment by ahaw021** [comment]
hi @bmw @SwartzCr 

Done some research on this.

PyParsing generally has a bad time with Apache so we can look at a few options

https://bitbucket.org/ericsnowcurrently/apache_conf_parser/src
https://gist.github.com/jakubjedelsky/3142806
https://github.com/egeland/apache_conf_parser/blob/master/apache_conf_parser.py

I like the last two as they are self sustaining libraries

@bmw  - do you have a list of functional requirements for the parser

E.g. does it need to return hosts etc 
does it need to change the files or does another bit of code do that
is there specific methods that need to be implemented or wrapped

Andrei

**Comment by bmw** [comment]
I do not have a complete list of functionality the parser must have. In general, anything we are using `augeas` for in `certbot-apache` must be replaced either by another parser or additional functionality built around it. If you want to look through this yourself, usually the `augeas` object is referred to in the code as `aug`. Somewhat quickly looking the code, this functionality includes:

* Read in and represent an entire Apache configuration. This must be the entire configuration, not just virtual hosts.
* Get the value of any directive.
* Determine the file system path to the file containing a specific directive or object such as a virtual host.
* Add, modify, or delete directives at arbitrary places in a configuration. For example, being able to add the directive `SetHandler server-status` to a specific location block, vhost, and file of an Apache config. This must work for both single line directives and block directives like `Location`.
* Search a configuration for all directives of a specific type such as `VirtualHosts`.
* Copy directives (including block directives) from one place in the the configuration to another.
* Create new files and add them to the Apache configuration.
* Be able to make changes in memory and later write out all modifications to the user's Apache config.
* Preserve all whitespace, formatting, comments, etc. Reading a configuration in and immediately writing it back out should not change the contents of a user's file in any way.

I'm ccing @joohoi on this for two reasons:

1. He is more familiar with the Apache plugin than I am.
2. He may be working on this in the coming months so if you were planning on working on this yourself, you should definitely coordinate your work with him.

@ahaw021, as an aside, are you still planning on working on Certbot on Windows? While removing Augeas would help with Windows support, people can't use the Apache plugin on Windows until the Certbot core works on Windows as well. We're still excited to see PRs from you here!

**Comment by ahaw021** [comment]
@bmw 

Yes I am augeas and locks are two problematic libraries for windows so chipping away at those

the locks one is a killer at the moment so it will be the first one to attack 🗡 

after that will look at the existing plugins

Apache - doesn't work
Nginx - doesn't work but i suspect this is to do with the way plugins are identified
IIS - will write this based on the iis_brige library - will not import the whole library just the useful bits 
Standalone - no issues
Manual - no issues

Happy for others to take the lead on the apache plugin but I wanted to put some influence on this before another linux only library is seletcted :(

Andrei

**Comment by thedrow** [comment]
I'm really sorry you guys are struggling with this.
I'm maintaining python-augeas but I don't have a lot of time to invest on it.
I wish we could make augeas portable to Windows but that's unlikely to happen anytime soon unless someone comes along with the funding and manpower to do so.
https://github.com/hercules-team/python-augeas/issues/21 was completely my fault and I'm sorry it affected you guys.
https://github.com/hercules-team/python-augeas/issues/30 is now fixed with tests to ensure it won't regress.

I'll investigate https://github.com/hercules-team/python-augeas/issues/15 as soon as I can though I appreciate any help doing so.

**Comment by SwartzCr** [comment]
@thedrow - thanks for all the work that you've done on python-augeas. We appreciate it, and understand that it's volunteer work.
We'll be sure to let you know if we run into python-augeas problems in the future, and hopefully we can get it to a point of stability where we're comfortable with having certbot rely on it.

**Comment by SwartzCr** [comment]
Also for reference our corresponding issue for augeas 15 is #2265

**Comment by lutter** [comment]
I am likewise very sorry you are having so much trouble with augeas - unfortunately, httpd is a monster to parse. I am wondering if there is a way to write an augeas lens that tries to do much less, i.e. only picks out the things you actually need to access/modify in Apache configuration so that at least you don't have to deal with problems in directives you don't care about. The idea would be that that lens treats anything that isn't of interest to you as an opaque block of data (kinda like a comment), and only maps interesting things into the tree.

**Comment by SwartzCr** [comment]
Hmm - would you like to provide comments on our lens? I think we'd be willing to edit it since we're already shipping a custom one

**Comment by ahaw021** [comment]
what advantage do lenses have over just python regex ?

**Comment by lutter** [comment]
@ahaw021 the biggest advantage is that lenses are bidirectional, and make sure that changes made to the Augeas tree do not affect other things in a file (e.g., comments or other entries) The [quick tour](http://augeas.net/tour.html) goes into more detail on that.

@SwartzCr I'll try and have a look later

**Comment by SwartzCr** [comment]
@lutter Awesome
adding @joohoi to this thread so that he can keep an eye on it while he works on apache things

**Comment by bmw** [comment]
I'm closing this in favor of https://github.com/certbot/certbot/issues/6665. Regardless of the pros and cons of Augeas, it doesn't support Windows and [doesn't seem likely to in the near future](https://github.com/hercules-team/augeas/issues/612) so we're switching to parser that works on both Windows and UNIX.
