### ISSUE TITLE
Simplify http instructions in manual plugin

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#4804]
Right now when you run the manual plugin for an HTTP challenge, you get the following message:

```
Make sure your web server displays the following content at
http://4544ad.com/.well-known/acme-challenge/UlK01OTOxzjsZO74kSzj53goMdIaJKlf6xEVoAlImBE before continuing:

UlK01OTOxzjsZO74kSzj53goMdIaJKlf6xEVoAlImBE.W1iiTykicy7OqjL-Fu3XxEut3RTonSfTtbV6mRA2u4g

If you don't have HTTP server configured, you can run the following
command on the target server (as root):

mkdir -p /tmp/certbot/public_html/.well-known/acme-challenge
cd /tmp/certbot/public_html
printf "%s" UlK01OTOxzjsZO74kSzj53goMdIaJKlf6xEVoAlImBE.W1iiTykicy7OqjL-Fu3XxEut3RTonSfTtbV6mRA2u4g > .well-known/acme-challenge/UlK01OTOxzjsZO74kSzj53goMdIaJKlf6xEVoAlImBE
# run only once per server:
$(command -v python2 || command -v python2.7 || command -v python2.6) -c \
"import BaseHTTPServer, SimpleHTTPServer; \
s = BaseHTTPServer.HTTPServer(('', 5002), SimpleHTTPServer.SimpleHTTPRequestHandler); \
s.serve_forever()" 
```

I would argue that the code at the bottom is visual noise and distracts from the more important information up top. I also think that most people using the manual plugin with the HTTP challenge don't want these instructions to set up a Python server, because they are probably planning to push the challenge file to an already-running web server of some sort.

I think we should rip out everything below "If you don't have...". Note that the integration tests, last I checked, expect to parse out this message and run it, so that integration test will need to be updated.

**Comment by jsha** [comment]
Also, "Make sure your web server displays the following content at" is ambiguous. Should I expect that my web server already displays that content, and I'm just double-checking? We should update this message to say something like "put a file containing this data on your web server at this url."

**Comment by tsundeoku** [comment]
I used this Python code regularly to create certificates for remote hosts that are not web servers and just discovered today that it has been removed. Considering that this is a command line utility for server configuration, I have to say I am puzzled by the concern about "visual noise" and "distraction." SSL certificates are widely used for all manner of services, but the current form of the command output and the thinking I have been able to cover that informs it points to an assumption that SSL is only for web servers. The instructions in the output take for a given that the user is making the certificate for a web server, and that an httpd is already running on the target host. For users who do not fit that mold, this is confusing.

If the aesthetic objections to having certbot --manual output this Python code are too strong to entertain returning it, I would at least like to ask that some provision be made for situations where the target host is not a web server. Asking people to install, configure, and run a permanent httpd as a prerequisite to having an SSL certificate on any given host seems inappropriately heavy-handed.

**Comment by jsha** [comment]
@tsundeoku It sounds like you would be better served by a plugin that combines SSH + SimplePythonServer to automate the process, rather than copying and pasting code each time. What do you think of that idea?

FWIW, my objections were less aesthetic than user-experience based. The more information you give someone, the less likely they are to read it all. In this case, the example code was a lot of information for very little benefit, and made it much harder to see the important information at the top.

**Comment by tsundeoku** [comment]
That sounds promising, as long as it is simple and does not have too many dependencies, although I also think it is important to have a quick one-time way to generate a certificate for remote host without having to set up a web server on it. Perhaps an optional argument to dump this output?

I always found the existing text to be very clear, especially the "If you don't have HTTP server configured" part, compared to the current version that assumes the presence of an httpd and leaves nothing at all for those without one, but I can see how opinions vary and I am more interested in a quick means of doing this being available some way than asking for it to return to the default output specifically.
