### ISSUE TITLE
Crash in Debian

### ISSUE THREAD

**Issue by kosfango** [certbot/certbot#4807]
## My operating system is (include version):

Debian 7.11

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Installed by git clone https://github.com/certbot/certbot.git

## I ran this command and it produced this output:

# /root/certbot-auto --debug
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Enter email address (used for urgent renewal and security notices) (Enter 'c' to
cancel):admin@mail.com
./certbot-auto: line 1272:   986 Killed                  $SUDO "$VENV_BIN/letsencrypt" "$@"

## Certbot's behavior differed from what I expected because:

the program fails

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

2017-06-08 21:41:20,800:DEBUG:certbot.main:certbot version: 0.15.0
2017-06-08 21:41:20,800:DEBUG:certbot.main:Arguments: []
2017-06-08 21:41:20,800:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint
#webroot)
2017-06-08 21:41:20,828:DEBUG:certbot.log:Root logging level set at 20
2017-06-08 21:41:20,828:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-06-08 21:41:20,828:DEBUG:certbot.plugins.selection:Requested authenticator None and installer None
2017-06-08 21:41:20,925:DEBUG:certbot_apache.configurator:Apache version is 2.2.22
2017-06-08 21:41:21,535:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin - Beta
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.configurator:ApacheConfigurator
Initialized: <certbot_apache.configurator.ApacheConfigurator object at 0x1976c10>
Prep: True
2017-06-08 21:41:21,535:DEBUG:certbot.plugins.selection:Selected authenticator <certbot_apache.configurator.ApacheConfigurator object at 0x1976c10> and installer <certbot_apache.configurator.ApacheConfigurator object
 at 0x1976c10>
2017-06-08 21:41:26,057:DEBUG:acme.client:Sending GET request to https://acme-v01.api.letsencrypt.org/directory.
2017-06-08 21:41:26,064:DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org

**Comment by SwartzCr** [comment]
This seems pretty bizarre, but I'm willing to bet that this problem would go away if you installed it from backports. Would you be willing to try that?
Once you install the packaged version let me know how it goes and we can continue to debug.

**Comment by kosfango** [comment]
Thank you for advice. I tried to add repo:
deb http://ftp.debian.org/debian wheezy-backports main contrib non-free
then
apt-get update
apt-cache search certbot
blank (package not found)

**Comment by SwartzCr** [comment]
Oops sorry, it's not bakcported for wheezy, you'll have to use certbot-auto to install it. It's still a lot better than cloning the git repo. Instructions can be found here: https://certbot.eff.org/#debianwheezy-apache

**Comment by kosfango** [comment]
I tried official way before. Unfortunately, the same result. 

#whoami
root
#cd /root
#wget https://dl.eff.org/certbot-auto
#chmod a+x certbot-auto
#./certbot-auto
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Enter email address (used for urgent renewal and security notices) (Enter 'c' to
cancel):admin@mail.com
./certbot-auto: line 1272: 12656 Killed                  $SUDO "$VENV_BIN/letsencrypt" "$@"

**Comment by kosfango** [comment]
I think that something broken in the OS. While, I don't know cause of the issue. Maybe the system is somehow customized.

**Comment by bmw** [comment]
Is `certbot-auto` hanging and you're killing the program or something else killing it?

**Comment by kosfango** [comment]
The process stops on its own

**Comment by bmw** [comment]
Interesting. I've got a few things for you to try so we can get some more information to try and narrow down the problem. What's the output of:

1. `python -c 'import requests; print requests.Session().request("GET", "https://acme-v01.api.letsencrypt.org/directory", verify=True, timeout=45, headers={"User-Agent": "CertbotACMEClient/0.15.0 (certbot-auto; Debian GNU/Linux 7 (wheezy)) Authenticator/apache Installer/apache (run; flags: ) Py/2.7.3"}).text'` If this is `ImportError: No module named requests`, that's fine.
2. `${XDG_DATA_HOME:-~/.local/share}/letsencrypt/bin/python -c 'import requests; print requests.Session().request("GET", "https://acme-v01.api.letsencrypt.org/directory", verify=True, timeout=45, headers={"User-Agent": "CertbotACMEClient/0.15.0 (certbot-auto; Debian GNU/Linux 7 (wheezy)) Authenticator/apache Installer/apache (run; flags: ) Py/2.7.3"}).text'`
3. `curl https://acme-v01.api.letsencrypt.org/directory`
4. `ls -l /bin/sh`
5. The version of whatever `/bin/sh` points to. For example, if `/bin/sh` points to `dash`, can you provide the output of `dpkg -s dash`?

**Comment by kosfango** [comment]
I reproduce your commands:

1. #python -c 'import requests; print requests.Session().request("GET", "https://acme-v01.api.letsencrypt.org/directory", verify=True, timeout=45, headers={"User-Agent": "CertbotACMEClient/0.15.0 (certbot-auto; Debian GNU/Linux 7 (wheezy)) Authenticator/apache Installer/apache (run; flags: ) Py/2.7.3"}).text'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named requests

2. #${XDG_DATA_HOME:-~/.local/share}/letsencrypt/bin/python -c 'import requests; print requests.Session().request("GET", "https://acme-v01.api.letsencrypt.org/directory", verify=True, timeout=45, headers={"User-Agent": "CertbotACMEClient/0.15.0 (certbot-auto; Debian GNU/Linux 7 (wheezy)) Authenticator/apache Installer/apache (run; flags: ) Py/2.7.3"}).text'
Killed

3. #curl https://acme-v01.api.letsencrypt.org/directory
{
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
}

4. #ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Sep 10  2014 /bin/sh -> bash

5. #dpkg -s bash
Package: bash
Essential: yes
Status: install ok installed
Priority: required
Section: shells
Installed-Size: 3941
Maintainer: Matthias Klose <doko@debian.org>
Architecture: amd64
Multi-Arch: foreign
Version: 4.2+dfsg-0.1+deb7u4
Replaces: bash-completion (<< 20060301-0), bash-doc (<= 2.05-1)
Depends: base-files (>= 2.1.12), debianutils (>= 2.15)
Pre-Depends: dash (>= 0.5.5.1-2.2), libc6 (>= 2.11), libtinfo5
Recommends: bash-completion (>= 20060301-0)
Suggests: bash-doc
Conflicts: bash-completion (<< 20060301-0)
Conffiles:
 /etc/bash.bashrc 6334b485d48f479d8de056806b274cd3
 /etc/skel/.bash_logout 22bfb8c1dd94b5f3813a2b25da67463f
 /etc/skel/.bashrc d5f897a5ec2b5f55b412004e7715977f
 /etc/skel/.profile ecb6d3479ac3823f1da7f314d871989b
 /etc/bash_completion 9da8d1c95748865d516764fb9af82af9 obsolete
Description: GNU Bourne Again SHell
 Bash is an sh-compatible command language interpreter that executes
 commands read from the standard input or from a file.  Bash also
 incorporates useful features from the Korn and C shells (ksh and csh).
 .
 Bash is ultimately intended to be a conformant implementation of the
 IEEE POSIX Shell and Tools specification (IEEE Working Group 1003.2).
 .
 The Programmable Completion Code, by Ian Macdonald, is now found in
 the bash-completion package.
Homepage: http://tiswww.case.edu/php/chet/bash/bashtop.html

**Comment by bmw** [comment]
Thanks for the additional info. It's really strange. Something is killing the process when Python tries to make a simple GET request to Let's Encrypt's server. This could be the Python interpreter, a bug in the popular `requests` module, or something external running on your server. At least we know for sure the problem isn't your shell though (`certbot-auto` does things like running itself internally so I wanted to make sure there wasn't a problem there).

If there's nothing unusual about your server that you're aware of that may be causing this, I have a few more things for you to try if you don't mind.

1. Immediately after running the command in step 2 above, what is the output of `echo $?`?
2. If you run `rm -rf ${XDG_DATA_HOME:-~/.local/share}/letsencrypt` and run `certbot-auto` again, do you get the same problem?
3. If you run `${XDG_DATA_HOME:-~/.local/share}/letsencrypt/bin/pip install -U requests` and then either `certbot-auto` or the command from step 2 in my prior instructions, do you get the same issue?
4. You don't have to do this, but I'm curious if you run `sudo apt-get update && sudo apt-get install python-requests` and then run the command in step 1 of my previous instructions, is the process still killed?

**Comment by kosfango** [comment]
> Immediately after running the command in step 2 above, what is the output of echo $??

#${XDG_DATA_HOME:-~/.local/share}/letsencrypt/bin/python -c 'import requests; print requests.Session().request("GET", "https://acme-v01.api.letsencrypt.org/directory", verify=True, timeout=45, headers={"User-Agent": "CertbotACMEClient/0.15.0 (certbot-auto; Debian GNU/Linux 7 (wheezy)) Authenticator/apache Installer/apache (run; flags: ) Py/2.7.3"}).text'
Killed
#echo $?
137

> If you run rm -rf ${XDG_DATA_HOME:-~/.local/share}/letsencrypt and run certbot-auto again, do you get the same problem?

Yes, the same:
https://pastebin.com/USAC9Cb1

> If you run ${XDG_DATA_HOME:-~/.local/share}/letsencrypt/bin/pip install -U request

https://pastebin.com/DYpYuTXJ
The sam issue ./certbot-auto: line 1272: 19735 Killed                  $SUDO "$VENV_BIN/letsencrypt" "$@"

but if I run:
#${XDG_DATA_HOME:-~/.local/share}/letsencrypt/bin/python -c 'import requests; print requests.Session().request("GET", "https://acme-v01.api.letsencrypt.org/directory", verify=True, timeout=45, headers={"User-Agent": "CertbotACMEClient/0.15.0 (certbot-auto; Debian GNU/Linux 7 (wheezy)) Authenticator/apache Installer/apache (run; flags: ) Py/2.7.3"}).text'

empty output

> You don't have to do this, but I'm curious if you run sudo apt-get update && sudo apt-get install python-requests and then run the command in step 1 of my previous instructions, is the process still killed?

Unfortunately, yes the same

**Comment by kosfango** [comment]
Also, I marked interesting thing:

# pip install --upgrade pip
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by kosfango** [comment]
May be cert bot fails with the similar error?

**Comment by bmw** [comment]
> 137

This usually means that something sent SIGKILL to the process. Do you have something like SELinux running on the system that may be killing Python when it tries to make the outbound request?

> but if I run:
> #${XDG_DATA_HOME:-~/.local/share}/letsencrypt/bin/python -c 'import requests; print requests.Session().request("GET", "https://acme-v01.api.letsencrypt.org/directory", verify=True, timeout=45, headers={"User-Agent": "CertbotACMEClient/0.15.0 (certbot-auto; Debian GNU/Linux 7 (wheezy)) Authenticator/apache Installer/apache (run; flags: ) Py/2.7.3"}).text'

> empty output

If you're still getting this behavior, what is the exit code here? That command should print the same thing as `curl` did before.

> May be cert bot fails with the similar error?

It shouldn't. Certbot works around this problem by having it use a newer TLS library that the one included in the Python standard library.

**Comment by GovanifY** [comment]
Hey,
I have an idea from the reason of this issue.
Did you happen to use PaX on your server?
PaX decides certbot is harmful in its current form and so issue this nice syslog:

```
Aug 14 15:18:22 fujiwara kernel: [ 1495.896338] PAX: From 1.2.3.4: execution attempt in: /usr/lib64/python3.4/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so, 35420b8f000-35420b97000 00159000
Aug 14 15:18:22 fujiwara kernel: [ 1495.896342] PAX: terminating task: /usr/bin/python3.4m(certbot):4411, uid/euid: 0/0, PC: 0000035420b969b0, SP: 0000039ac7c7df58
Aug 14 15:18:22 fujiwara kernel: [ 1495.896345] PAX: bytes at PC: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Aug 14 15:18:22 fujiwara kernel: [ 1495.896352] PAX: bytes at SP-8: 000000547d948cc0 00000354205e1eb5 0000000000000001 000000547e3f2114 0000000000000001 00000354255a98aa 0000000000000000 0000035425926b25 0000035421ed0c00 ecd35e73bb9e4600 000000000000000a
```
This might explain quite a bit the issue

**Comment by bmw** [comment]
This issue hasn't been updated in a long time and Debian 7 has reached it's end of life.

If you're still having problems, please comment or open a new issue.

**Comment by gcs-github** [comment]
This is most likely a PaX-related problem. If anyone stumbles upon this issue, first look for confirmation by running `dmesg`. If you find a line with PaX complaining about an execution attempt related to python or a python module, try disabling EMUTRAMP and MPROTECT for the version of python certbot is running with.

For example, my specific Gentoo configuration required `paxctl-ng -em /usr/bin/python3.6m` for certbot to run successfully.
