### ISSUE TITLE
Crash on Debian

### ISSUE THREAD

**Issue by skid9000** [certbot/certbot#4820]
## My operating system is (include version):
Debian 8.8 amd64

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt, on Jessie backports

## I ran this command and it produced this output:
`certbot -d www.tuto-craft.com -d forum.tuto-craft.com -d blog.tuto-craft.com -d support.tuto-craft.com -d puush.tuto-craft.com -d siteisn.tuto-craft.com --nginx --rsa-key-size=4096 --email skid@tuto-craft.com --debug`

`Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.10.2', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 828, in main
    args = cli.prepare_and_parse_args(plugins, cli_args)
  File "/usr/lib/python2.7/dist-packages/certbot/cli.py", line 1045, in prepare_and_parse_args
    helpful.add_deprecated_argument("--agree-dev-preview", 0)
  File "/usr/lib/python2.7/dist-packages/certbot/cli.py", line 717, in add_deprecated_argument
    self.parser.add_argument, argument_name, num_args)
  File "/usr/lib/python2.7/dist-packages/certbot/util.py", line 393, in add_deprecated_argument
    configargparse.ACTION_TYPES_THAT_DONT_NEED_A_VALUE.add(ShowWarning)
AttributeError: 'tuple' object has no attribute 'add'`

**Comment by yan12125** [comment]
This is fixed since certbot 0.14.1 while the one in Debian is not updated yet. For now could you try the certbot-auto way? More details can be fetched from https://certbot.eff.org/#debianwheezy-nginx. Don't forget to remove 0.10.2 via apt-get first.

**Comment by skid9000** [comment]
It work with this method, thanks :)
