### ISSUE TITLE
Should return non-0 if all certs too recent for renewal

### ISSUE THREAD

**Issue by DNied** [certbot/certbot#4823]
`renew` should return a non zero exit code if all certificates are too recent for renewal. This would allow a script to execute commands only if a successful renewal took place.

The `--renew-hook` option is unsuitable, because it's executed for *each* certificate renewed. But if there are many certificates to be renewed, and the desired action is to restart the web and mail servers, many useless restarts would ensue; thus causing disruptions in ongoing connections and unnecessary CPU and disk load.

Returning a non-zero status is *clearly* the right thing to do. Consider return codes such as EAGAIN (11) or EX_TEMPFAIL (75).

## My operating system is (include version):
`Linux 2.6.32-042stab120.20 #1 SMP Fri Mar 10 16:52:50 MSK 2017 x86_64 x86_64 x86_64 GNU/Linux`
(CentOS Linux release 7.3.1611 (Core))

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager (yum)

**Comment by SwartzCr** [comment]
--renew-hook is per specific certificates, so if you want to restart a webserver you can have a renew-hook that runs specifically for certs on that webserver. --post-hook will run at the end for any certificate that's renewed. There's more info here: https://certbot.eff.org/docs/using.html?highlight=hooks#pre-and-post-validation-hooks
Let me know if that suits your needs, or if you need better explanation of what these do

**Comment by bmw** [comment]
We talked a lot about error codes vs. hooks internally and decided to offer hooks instead so I'm closing this issue as won't fix for now.
