### ISSUE TITLE
CAA record for <my_domain> prevents issuance

### ISSUE THREAD

**Issue by harvey637** [certbot/certbot#4827]
## I ran this command and it produced this output:

> certbot certonly --manual --preferred-challenges dns --dry-run -d <my_domain> --manual-auth-hook renew_auth.sh

My renew_auth.sh successfully integrates the $CERTBOT_VALIDATION into <my_domain> TXT record.

## Certbot's behavior differed from what I expected because:
Additionally to TXT I have a CAA record for <my_domain> saying:

> <my_domain>     rdata_257 = 128 issue "Let's Encrypt Authority X3"

which is perfect for A+ validating <my_domain> with ssslabs.com and to me it looks great.

But then I get 

> -- The following errors were reported by the server:
>   Domain: <my_domain>
>   Type:   connection
>   Detail: CAA record for <my_domain> prevents issuance

## Here is a Certbot log showing the issue (if available): same as above

From my point of view a valid CAA record explaining lets encrypt as certificate authority is
a building block in ssl confidence and validation and should not interfere and **prevent** with renewal of my
certificate.

dirty workaround: remove CAA record and add it again after renewal

**Comment by harvey637** [comment]
ok, I found out, that the CAA Line is wrong. Renewals work with a CAA record like:

<my_domain>               CAA      128 issue "letsencrypt.org"

So it is NOT what the certificate tells me as "validated from" nor "issued by" nor the CN nor O of the
certificate. I did not find the strin "letsencrypt.org" inside the cert, but hey, it is working now.

So I still do not close this ticket to hopefully encourage you to add this to the documentation!
Thanks.

**Comment by SwartzCr** [comment]
Would you be willing to write up a PR for our documentation to mention this? Altrenately this should go somewhere on the letsencrypt.org site and maybe @jsha or @cpu would be up for adding that since this isn't technically a certbot issue

**Comment by cpu** [comment]
I'm not sure I follow what the problem was here, but I _think_ it was that @harvey637 had published a CAA record for their domain, but with the wrong value (e.g. not `"letsencrypt.org"`) and so Boulder rightly refused to issue since it thought we weren't a whitelisted CA.

If that assessment is correct, I think the best thing Boulder can do is to add the `"caa-identities"` key to the `/directory` response's `"meta"` key. This will expose the string that should be used for CAA to ACME clients in a generic way and Certbot could do whatever it wanted with the information (display it, validate a domain's CAA record contains the correct string ahead of time with a DNS lookup, etc). I opened https://github.com/letsencrypt/boulder/issues/2811 for this - there may be a reason we were holding this back for the "acme v2" API that I'm overlooking.

Thanks! Apologies if I misconstrued the problem. Please let me know if so.

**Comment by harvey637** [comment]
Hi @cpu
perfectly correct, I took the wrong info from the certificate-issuer field, this: CN = Let's Encrypt Authority X3
and added this into my CAA record. This was positiv acknowledged by testing with ssllabs.
So my fault was to believe that "certificate issuer" is "et's Encrypt Authority X3" as read from the cert.
Correct entry in the CAA record is "letsencrypt.org" which was hard to find. In the end I was lucky inside the forum.
So my whish is avoid my mistake by exposing the string to be used as the CAA record, just as @cpu suggests. 
PS VALIDATING the CAA record should only occur when a CAA record exists, as it is not widly spread and not yet/never mandatory to create one. So if it is THERE and WRONG, prevent the renewal, if it is missing, continue with renewal (and show the CAA record to be used, just as a hint/info, not as error or warning)
Thanks!
Harvey637

**Comment by cpu** [comment]
@harvey637 Great! I'm glad I understood correctly, thanks for verifying.

> PS VALIDATING the CAA record should only occur when a CAA record exists, as it is not widly spread and not yet/never mandatory to create one. So if it is THERE and WRONG, prevent the renewal, if it is missing, continue with renewal

That's the way Boulder works today so there's nothing to fix in that sense :tada:

**Comment by SwartzCr** [comment]
Okay I'm going to close this issue, @harvey637 feel free to open new issues if you run into problems in the future!

**Comment by valignatev** [comment]
Sorry for necroposting this, but I got the same error message while issuing a wildcard certificate.
My problem was that I didn't have `issuewild "letsencrypt.org"` in my CAA record.
Hope it'll help somebody, cheers :)

**Comment by dseeker** [comment]
@valignatev how did you add that? I tried to renew a 3 month SLL now and it's returning this error, not sure if I have to start the process from scratch to make it work again

> Cert is due for renewal, auto-renewing...
> Plugins selected: Authenticator webroot, Installer None
> Renewing an existing certificate
> Performing the following challenges:
> http-01 challenge for static.103.68.216.95.clients.your-server.de
> Waiting for verification...
> Cleaning up challenges
> Attempting to renew cert (static.103.68.216.95.clients.your-server.de) from /etc/letsencrypt/renewal/static.103.68.216.95.clients.your-server.de.conf produced an unexpected error: Failed authorization procedure. static.103.68.216.95.clients.your-server.de (http-01): urn:ietf:params:acme:error:caa :: CAA record for static.103.68.216.95.clients.your-server.de prevents issuance. Skipping.
> All renewal attempts failed. The following certs could not be renewed:
>   /etc/letsencrypt/live/static.103.68.216.95.clients.your-server.de/fullchain.pem (failure)
> 
> Detail: CAA record for static.103.68.216.95.clients.your-server.de
   prevents issuance

https://check-your-website.server-daten.de/?q=static.103.68.216.95.clients.your-server.de

**Comment by valignatev** [comment]
@dseeker You have to add needed CAA record to your domain. There is a nice site https://sslmate.com/caa/ which could help with generating the correct string, you then just have to paste it wherever you manage your domains.

**Comment by dseeker** [comment]
@valignatev thanks. I don't actually own the domain and don't have access to set anything on DNS, it's provided as courtesy by the hosting company to access the server instead of directly using IP.  seems strange they would disable any other SSL providers

**Comment by jsha** [comment]
Hi! You'll get much better help by posting at https://community.letsencrypt.org/. I'm going to lock this issue thread for now.

Thanks,
Jacob
