### ISSUE TITLE
Make use of "caa-identities" metadata

### ISSUE THREAD

**Issue by zjs** [certbot/certbot#4836]
If the ACME server exposes a `"caa-identities"` key in its `/directory` response's `"meta"` key, Certbot should expose that to users so that they know what string to use if they wish to configure CAA.

Additionally, if the ACME servers exposes such a key, Certbot could attempt to verify the domain does not have a conflicting CAA record prior to trying to obtain a certificate (to fail fast with a helpful error message).

See also:
* letsencrypt/boulder#2811
* #4827

**Comment by pde** [comment]
This would be a good volunteer task if the core team specified what the mechanism of exposure was?

**Comment by mnordhoff** [comment]
Still relevant, bot.

**Comment by cpu** [comment]
> If the ACME server exposes a "caa-identities" key in its /directory response's "meta" key, Certbot should expose that to users so that they know what string to use if they wish to configure CAA.

One update: per [RFC 8555 Section 7.1.1](https://tools.ietf.org/html/rfc8555#section-7.1.1) this is now the `"caaIdentities"` key. All of the hyphenated directory keys were changed to camel case at some point during the standardization process.

**Comment by osirisinferi** [comment]
Probably still a good idea, inadvertably closed by stalebot.

**Comment by hablutzel1** [comment]
In addition, certbot could provide a hook (or something like that) to automatically update the DNS CAA records for the specific domains covered by the ACME order.
