### ISSUE TITLE
Certbot code of conduct

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4838]
GitHub added a community profile page recently. Here is [Certbot's](https://github.com/certbot/certbot/community) which I think accurately suggests we should have a code of conduct.

cc @SwartzCr

**Comment by cpu** [comment]
As one datum, for the Boulder repo we ended up [linking from in-repo](https://github.com/letsencrypt/boulder/blob/master/CODE_OF_CONDUCT.md) to the [community forum code of conduct](https://community.letsencrypt.org/guidelines), which we updated to a version of the [ Contributor Covenant](http://contributor-covenant.org/).

**Comment by ynasser** [comment]
Let's also update #letsencrypt-dev's channel purpose to link to this when it's ready. Linking to the existing LE one might also work, but we'd need to update the list of moderators to include @bmw, @SwartzCr, and @ohemorange, perhaps?

**Comment by SwartzCr** [comment]
I think it makes a lot of sense for the #letsencrypt channel to link to the community forum guidelines (if it doesn't already)
I think the dev channel should link to whatever we decide. @ynasser do you want to help with writing up a code of conduct?

**Comment by koops76** [comment]
We'll have to wait for EFF lawyers to write up something first.

**Comment by bmw** [comment]
This is done! The code of conduct is at https://github.com/certbot/certbot/blob/master/CODE_OF_CONDUCT.md
