### ISSUE TITLE
Error while pocketsphinx installation 

### ISSUE THREAD

**Issue by x-heel** [certbot/certbot#4848]
![untitled](https://user-images.githubusercontent.com/28453767/27259261-7dffae88-53c3-11e7-9b17-8da560f7371b.jpg)
help me to fix it plz..

**Comment by SwartzCr** [comment]
Hi @x-heel 
Technically we don't support windows as a platform for certbot - but I'm still happy to try to help if I can. Before we get too far into figuring out why PocketSphinx isn't installing I'd like to ask a few questions.
Where are the websites you're trying to get certificates for hosted? 
Are they hosted on this machine or on a server somewhere?
How did you download Certbot?

**Comment by x-heel** [comment]
i have not downloaded certbot, i only work on pocketsphinx ,and use google speech recognition .

**Comment by SwartzCr** [comment]
Oh I think you want to be posting this to the pocketsphinx issue queue. It can be found here: https://github.com/cmusphinx/pocketsphinx/issues/new
