### ISSUE TITLE
certbot standalone IPv6 global unicast: "no working IP addresses found"

### ISSUE THREAD

**Issue by zxyz** [certbot/certbot#4851]
## My operating system is (include version):
ubuntu 16.04
certbot 0.14.2-1

gloabl unicast IPv6 address, RFC1918 IPv4 address. removing IPv4 address from DNS doesn't change anything.

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

via apt-repository ppa:certbot/certbot

## I ran this command and it produced this output:

sudo certbot --standalone certonly -d DOMAIN

```
Obtaining a new certificate
Performing the following challenges:
tls-sni-01 challenge for DOMAIN
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. DOMAIN (tls-sni-01): urn:acme:error:malformed :: The request message was malformed :: no working IP addresses found for "DOMAIN"
```

## Certbot's behavior differed from what I expected because:

should use the found IPv6 address (see below) 

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

```
{
  "identifier": {
    "type": "dns",
    "value": "DOMAIN"
  },
  "status": "invalid",
  "expires": "2017-06-26T17:55:51Z",
  "challenges": [
    {
      "type": "dns-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/JRQrbCbBvEolrVXFuVq-wS9Ez3ezEwQhbjz1wFu0WiI/1374973784",
      "token": "0Xizles4kiaZ0_jnF3uj2IsfmbaLdmhBQEjbFjNnup4"
    },
    {
      "type": "tls-sni-01",
      "status": "invalid",
      "error": {
        "type": "urn:acme:error:malformed",
        "detail": "no working IP addresses found for \"DOMAIN\"",
        "status": 400
      },
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/JRQrbCbBvEolrVXFuVq-wS9Ez3ezEwQhbjz1wFu0WiI/1374973786",
      "token": "UYZsArNYwxCQUVpHU6Bg1qfS23LkBUmbI1-vlT_Dqbw",
      "keyAuthorization": "UYZsArNYwxCQUVpHU6Bg1qfS23LkBUmbI1-vlT_Dqbw.C2y0w-d6Pxu_iqfsZWbNFF8GTXDxu4bHv1FVOdtanEU",
      "validationRecord": [
        {
          "hostname": "DOMAIN",
          "port": "443",
          "addressesResolved": [
            "<correct global unicast IPv6 address>"
          ],
          "addressUsed": "<correct global unicast IPv6 address>",
          "addressesTried": [
            "<correct global unicast IPv6 address>"
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

DNS is working, correct IPv6 address also found by certbot as I can see in the logs.
If I run `sudo certbot certonly -d DOMAIN -w /tmp` for testing (withou an actual webserver running) it fails as expected with 

```
The server could not connect to the client to verify the domain :: Fetching http://DOMAIN/.well-known/acme-challenge/sH6LdEj-HpGB6I0n2xWRjE28HXjsB4NoseznhsEyj9E: Error getting validation data
```
but is not complaining for a missing IP address ("addressUsed" and "addressesTried" in the log are the same correct IPv6 addresses as above).

**Comment by bmw** [comment]
Support for IPv6 with standalone was only added in Certbot 0.15.0 which came out earlier this month. Unfortunately, Debian (and our PPA maintained by the Debian maintainers) hasn't been updated yet to this version. I'll try to nudge them a long, but after this happens, you should be able to issue a certificate with standalone.

In the meantime, (as you're probably already aware) you can work around the problem if you can configure an IPv6 web server for that domain and use it with Certbot's webroot plugin.

**Comment by bmw** [comment]
@jsha, @cpu: Could the error message from boulder here be improved? If DNS is properly configured for the domain but the client failed the challenge, perhaps it should return an `unauthorized` error about failing to complete the challenge rather than a `malformed` error about no working IP addresses?

**Comment by zxyz** [comment]
@bmw thanks for the quick reply. 
before I messed around with `address_family = socket.AF_INET6` in standalone.py but I somehow thought IPv6 would have been implemented meanwhile, which it did - thanks for that btw - just not in the version in the ppa.

**Comment by zxyz** [comment]
ups, wrong button :)

**Comment by cpu** [comment]
> Could the error message from boulder here be improved? If DNS is properly configured for the domain but the client failed the challenge,

@bmw I think there's room for improvement. I'll open an issue. In this case it should say something about the IPv6 address being unreachable and there was not an IPv4 address to try as a fallback.

**Comment by cpu** [comment]
https://github.com/letsencrypt/boulder/issues/2821

**Comment by bmw** [comment]
OK. With that issue and 0.15.0 which should be in the PPA relatively soon, I think this issue can be closed. @zxyz, thanks for reporting this and please comment if you'd like me to reopen.
