### ISSUE TITLE
Log doesn't mention hook scripts being called

### ISSUE THREAD

**Issue by georgehank** [certbot/certbot#4853]
## My operating system is (include version):
Debian unstable

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot 0.11.1 from Debian unstable

## I ran this command and it produced this output:
certbot renew with lots of --verbose... and it produces tons of output

## Certbot's behavior differed from what I expected because:
I expected it to log when/where it invokes my manual-auth and manual-cleanup scripts.  It didn't.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

Here is nothing because the problem is that it *DOESNT* show what I want it to

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
Irrelevant since I'm doing "manual" (scripted) DNS auth... it ends up used by lighttpd, but that's irrelevant since the scripts don't depend on lighttpd.

I'm trying to find out (docs are mumm about this) when auth/cleanup scripts get called for a cert WITH MULTIPLE NAMES.  Namely, jaerhard.com and www.jaerhard.com.  And it looks (but the log doesn't actually have that info hence this PR) like it calls manual auth separately for both names, then does the online part for one of the names, then does the cleanup, and then tries the other names.  Both names are in the zone file at one point (I have the script copy the zone file), so both auths should succeed.  But one doesn't.

Again, I need enough info to even debug this.

**Comment by SwartzCr** [comment]
Weird!
The file that runs the hooks seems to have logger lines in it: https://github.com/certbot/certbot/blob/master/certbot/hooks.py
I'm curious if you can find evidence of them in any of your logs, specifically ones where you're sure they're being run (based on the results).
It might also be worth checking to see if the hooks got added properly to your renewal conf file. You should be able to find it in /etc/letsencrypt/renewal/DOMAIN_NAME.conf

**Comment by georgehank** [comment]
I looked at this a bit more yesterday after logging (hah ;-)) this PR.  Yes, it has logger lines, but in the manual-auth/cleanup-hook path it only logs errors.  In the pre/post hooks, it also logs scripts as they are being called.

**Comment by SwartzCr** [comment]
Hmm can you point me to the functions that you'd like to log more?

**Comment by georgehank** [comment]
hooks.execute would probably do the trick.

My big problem here is actually (and that would be another PR, but for that I'd like to first make sure it's not my mistake) that for a cert with multiple SANs, the auth and cleanup hooks are called for each SAN, but in a confusing (and I suspect wrong) order.  I find only one of the SANs being successfully auth'd, while both get a TXT RR in bind.  But again, I first want to make sure I'm seeing things right (and I don't see anything right now :D)

**Comment by SwartzCr** [comment]
Interesting
It seems that execute is wrapped by _run_hook, and as far as I can tell every instance of _run_hook is prepended by a log statement, which allows us to say whether it's a pre/post/validation hook. Do you see any that are missing?

**Comment by georgehank** [comment]
execute is called directly from plugins/manual.py (I didn't do a complete call trace, but the only place manual-auth/cleanup are referenced is there IINM).

**Comment by SwartzCr** [comment]
could you point me at a line number?
