### ISSUE TITLE
Certbot-auto did not email on failed renewal

### ISSUE THREAD

**Issue by lesliev** [certbot/certbot#4859]
Certbot failed to renew our certificate and did not notify us via email.

I loaded up notify.py in the python console and tested that email sending does actually work (and it did):
https://github.com/certbot/certbot/blob/b1826d657ffc7c278041cc0c8e14dc2ba23f95e3/certbot/notify.py

So it appears Certbot didn't try to send an email.

## My operating system is (include version):
Ubuntu 12.04.1 LTS 

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command via crontab:
/opt/certbot-auto renew --quiet --no-self-upgrade --renew-hook "service nginx reload"

## Certbot's behavior differed from what I expected because:
It did not email us about the error during renewal of the certificate.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

2017-06-18 15:42:37,501:INFO:certbot.reporter:Reporting to user: The following errors were reported by the server:

Domain: media.nzonscreen.com
Type:   connection
Detail: DNS problem: query timed out looking up A for media.nzonscreen.com

To fix these errors, please make sure that your domain name was entered correctly and the DNS A record(s) for that domain contain(s) the right IP address. Additionally, please check that your computer has a publicly routable IP address and that no firewalls are preventing the server from communicating with the client. If you're using the webroot plugin, you should also verify that you are serving files from the webroot path you provided.
2017-06-18 15:42:37,502:INFO:certbot.auth_handler:Cleaning up challenges
2017-06-18 15:42:37,503:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/media.nzonscreen.com.conf produced an unexpected error: Failed authorization procedure. media.nzonscreen.com (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: DNS problem: query timed out looking up A for media.nzonscreen.com. Skipping.
2017-06-18 15:42:37,506:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/renewal.py", line 342, in renew_all_lineages
    main.obtain_cert(lineage_config, plugins, renewal_candidate)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 509, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 90, in _auth_from_domains
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/renewal.py", line 236, in renew_cert
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 246, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 74, in get_authorizations
    self._respond(resp, best_effort)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 131, in _respond
    self._poll_challenges(chall_update, best_effort)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 195, in _poll_challenges
    raise errors.FailedChallenges(all_failed_achalls)
FailedChallenges: Failed authorization procedure. media.nzonscreen.com (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: DNS problem: query timed out looking up A for media.nzonscreen.com

2017-06-18 15:42:37,507:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 693, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 538, in renew
    renewal.renew_all_lineages(config)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/renewal.py", line 359, in renew_all_lineages
    len(renew_failures), len(parse_failures)))
Error: 1 renew failure(s), 0 parse failure(s)

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
N/A

**Comment by SwartzCr** [comment]
Hey @lesliev I'm really sorry to hear about that, it sounds like you had an unexpected outage for your site, which is never fun.
I'm curious if you were expecting certbot to send you an email, at the address that you entered when you first ran certbot, to inform you of this error.
The email that you use to register an account (the first time you use certbot) is sent to the Let's Encrypt CA to inform you of expiring certs, and is not stored for use by certbot. Did you get an email from Let's Encrypt saying that your cert was going to expire soon? The subject should be "Let's Encrypt certificate expiration notice" and the from address should be "expiry@letsencrypt.org"
The 'emails' that certbot is supposed to send you are system level notification mails. I'm curious if you run `mail` on your server if you'll see a bunch of messages from cron showing those errors. Have you tried that yet?
We currently don't use notify.py anywhere in the codebase. It was written with the thought that it might be useful to have certbot email you on renewal failure, but then never fully implemented. I'd be happy to discuss whether you think we should complete that feature, and I'm curious if you expected that feature to have already been implemented.

**Comment by lesliev** [comment]
We received "Let's Encrypt certificate expiration notice" emails last year - to notify us that the certificate would expire on 23 Aug 16. But none this year. Not sure what went wrong there, the email is correct in regr.json.

I have run "mail" for root but there are none.

I couldn't find much detail about how the emailing works online, though I did see it mentioned somewhere that the CA sends the emails. In the end I read the source, but yeah, didn't see how notify.py was being used.

Personally I'd prefer being notified by certbot if something goes wrong rather than getting more and more upcoming expiry notifications (as I use it on more servers) and having to check manually that all is well. 

Though it would be great to also get notified by the CA if the certificate gets within a week of expiry, which should never happen if auto-renew is working.

**Comment by SwartzCr** [comment]
@jsha or @cpu would you be willing to help figure out why the CA didn't send an expiry notice?
@bmw any idea why the errors didn't make their way out of cron?

**Comment by cpu** [comment]
@lesliev Is `media.nzonscreen.com` the only domain that was on an expired certificate that you didn't receive an email warning for?

**Comment by bmw** [comment]
> any idea why the errors didn't make their way out of cron?

`cron` normally sends mail if the command it runs produces any output which `certbot-auto renew --quiet` does if there are any failures. You can find information on how to configure `cron` to do this on websites like [this](https://serverfault.com/questions/54152/how-to-get-e-mail-from-failed-cron-jobs-in-ubuntu). If you want `cron` email sent to an external account, you'll need to configure a mail transfer agent (MTA) like `postfix`. You can find a guide on how to do this [here](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-postfix-as-a-send-only-smtp-server-on-ubuntu-14-04). Getting mail fron `cron` is a good practice as you can be notified of potential problems on your system beyond Certbot failures.

With that said, if you provided an email address to Certbot when you first started using it on this system and didn't unsubscribe from the Let's Encrypt expiration emails, Let's Encrypt should email you when your certificate approaches expiration and has not been renewed. These emails are only sent after Certbot should have already renewed your certificate, so if this is configured properly, you'll only get email if renewal is failing. If you answer cpu's question above, he should be able to help you figure out why you didn't get this message.

**Comment by bmw** [comment]
This issue refers to problems with the LE server or cron configuration so I'm closing this issue. If you're still having problems, please open an issue at https://community.letsencrypt.org.
