### ISSUE TITLE
Feature request: Switch to choose ports for standalone mode

### ISSUE THREAD

**Issue by bemeyert** [certbot/certbot#4864]
## My operating system is (include version):
CentOS6/7, Archlinux

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Offiical Docker images

## I ran this command and it produced this output:

`docker run -it --rm --user $(id -u) --volume lib:/var/lib/letsencrypt --volume etc:/etc/letsencrypt certbot/certbot certonly --register-unsafely-without-email --standalone -d www.example.de -v`

## Certbot's behavior and what I need

Certbot starts the server in standalone mode on ports 80 and 443. Therefore it needs root privileges. But I have to run certbot as the user who is starting the container. Otherwise the data in the external volumes belong to root and are more or less unusable. In this case I want to run the certbot Docker image in a Jenkins job. So the user who is starting the container is `jenkins` and the volumes cannot be removed by it.

It would really help if I could assign other ports to the two servers. Via Dockers port mapping I can remap them on the "outside" back to 80 and 443.

**Comment by bmw** [comment]
I think this is a duplicate of #2697. The certificate authority is still going to try to connect to your server through 80/443, however, you can specify alternate ports for standalone to bind to with `--http-01-port` and `--tls-sni-01-port`

**Comment by bemeyert** [comment]
@bmw You're right. I didn't RTFM'd. Sry. That was exactly the option I asked for. Thx
