### ISSUE TITLE
Max retries exceeded with url directory Name or service not known

### ISSUE THREAD

**Issue by GusevVictor** [certbot/certbot#4872]
## My operating system is (include version):
Debian 8 in a lxc container without systemd

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
0.10.2-1~bpo8+1 from ftp.debian.org_debian_dists_jessie-backports_main_binary-amd64_Packages repo.

## I ran this command and it produced this output:
My cronjob run this:
`test -x /usr/bin/certbot -a \! -d /run/systemd/system && perl -e 'sleep int(rand(3600))' && certbot -q renew`

My output this one:

> Attempting to renew cert from /etc/letsencrypt/renewal/service.company.com.conf produced an unexpected error: HTTPSConnectionPool(host='acme-v01.api.letsencrypt.org',
> +port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9ddc996450>:
> +Failed to establish a new connection: [Errno -2] Name or service not known',)). Skipping.

## Certbot's behavior differed from what I expected because:
If I run the command from console, it works but cronjob - fail.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
There is no any helpful information in /var/log/letsencrypt file

**Comment by SwartzCr** [comment]
What permissions are you running it with when you run it yourself, and what permissions is cron running it with?
The max retries is a somewhat spurious error. It's probably not able to establish a connection at all - and then it does it a few times, none of which work.

**Comment by GusevVictor** [comment]
dear @SwartzCr , in both case I run certbot as root. There is no any problem with DNS. For example, I see the error from cron job error log after that, I run 'certbot -q renew' from console and there no any error. It is not first time of the error. I have this for 6 months.

Best regards.

**Comment by SwartzCr** [comment]
Okay - then I'm going to close this issue, feel free to open another one if you run into problems on Ubuntu.
Hope it's all fixed now!
