### ISSUE TITLE
certbot-auto does not support --dns-route53

### ISSUE THREAD

**Issue by airbone42** [certbot/certbot#4873]
Hi,

when running `# ./certbot-auto certonly --dns-route53 --debug`, we end up with the error message `PluginSelectionError: The requested dns-route53 plugin does not appear to be installed`.

Is there any way to install this plugin so it runs with certbot-auto? We install certbot-auto via `wget https://dl.eff.org/certbot-auto;chmod a+x certbot-auto` and run this in CentOS.

**Comment by SwartzCr** [comment]
Unfortunately at the moment it's very hard for the DNS plugin to work on certbot-auto: https://github.com/certbot/certbot/issues/4767
https://github.com/certbot/certbot/blob/master/CHANGELOG.md#added
We plan to have a solution sometime in the next month or two, but for now I don't have a good suggestion

**Comment by airbone42** [comment]
Thanks for the answer. Would be really great to see this in certbot-auto, especially as the default Amazon Linux OS is CentOS, which has no certbot package and the install instructions recommend certbot-auto.

**Comment by SwartzCr** [comment]
What version of CentOS is it?

**Comment by airbone42** [comment]
We're using the Amazon Linux AMI which is afaik based on CentOS:
`
       __|  __|_  )
       _|  (     /   Amazon Linux AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-ami/2017.03-release-notes/
`

To be honest, I don't know how to find out the beneath CentOs version

**Comment by SwartzCr** [comment]
No worries. I'm going to tag @bmw here because he's interested in taking on the task of geting certbot-auto to support our DNS plugins

**Comment by airbone42** [comment]
Just let me know if we can help you here in any way.

**Comment by SwartzCr** [comment]
We're actually tracking this in #4767
I'm going to close this ticket in favor of that one - but you should for sure watch and comment on that issue!

**Comment by SwartzCr** [comment]
additionally you can put pressure on the CentOS packaging team to package it, like was done in Arch
