### ISSUE TITLE
ImportError: No module named urllib3.exceptions

### ISSUE THREAD

**Issue by klevstul** [certbot/certbot#4886]
## Operating system:
Debian 9 Stretch
```
# uname -rv
4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26)
```

## Webserver
lighttpd

## I installed Certbot with:
OS package manager, running
`apt-get install certbot`

## Command and output:
```
root@klevstul:/home/klevstul# certbot certonly --webroot -w /var/certbot/public_html -d foreneno.com -d www.foreneno.com
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.10.2', 'console_scripts', 'certbot')()
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 357, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2394, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2108, in load
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 14, in <module>
    from acme import messages
  File "/usr/lib/python2.7/dist-packages/acme/messages.py", line 4, in <module>
    from acme import challenges
  File "/usr/lib/python2.7/dist-packages/acme/challenges.py", line 10, in <module>
    import requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 60, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
ImportError: No module named urllib3.exceptions
```

## Additional info
I am sorry if this is a duplicate of #2902. It seems related, but not the same. And in my case it is not happening through lack of memory.

**Comment by SwartzCr** [comment]
Can you see what version of urllib3 you have installed? `pip freeze` or `dpkg -l` might help with this.

**Comment by klevstul** [comment]
@SwartzCr 
```
klevstul@klevstul:~$ dpkg -l | grep 'urllib3'
ii  python-urllib3                  1.19.1-1                       all          HTTP library with thread-safe connection pooling for Python
ii  python3-urllib3                 1.19.1-1                       all          HTTP library with thread-safe connection pooling for Python3
```

**Comment by kiarn** [comment]
`pip install --upgrade six`

solved the problem for me.

**Comment by SwartzCr** [comment]
Awesome, @klevstul have you tried something along those lines?

**Comment by klevstul** [comment]
@kiarn @SwartzCr 
sorry for my late feedback. have been busy with other project recent days. anyhow,
`pip install --upgrade six`
did work for me as well.

thanks a lot!

**Comment by SwartzCr** [comment]
Awesome - maybe @erikrose or @hlieberman  has a sense of why we can't install against urllib3?
is it possible that we need to update our dependencies?

**Comment by erikrose** [comment]
I'm also curious what version of `requests` you're using. urllib3 has an exceptions module both in 1.19.1 and in the latest tip of trunk, so my initial suspicion about it being a requests/urllib3 version mismatch didn't prove out. requests has been vendoring, unvendoring, and quasi-re-vendoring its dependencies lately, so we should make sure everything's well with it.

**Comment by kiarn** [comment]
```
# pip list | grep 'six\|req\|cert\|url'
certbot (0.10.2)
certbot-apache (0.10.2)
requests (2.12.4)
six (1.10.0)
urllib3 (1.19.1)
```

**Comment by erikrose** [comment]
It's that `requests` does `from .packages.urllib3.contrib import pyopenssl` and urllib3's pyopenssl module does merely `import six` rather than the proper, vendored version. Thus, it's at the mercy of whatever version of six you have floating around in your Python environment, if any. It's still that way in the latest `requests` and `urllib3`. I'll file a bug.

certbot-auto installs should not be have this problem, because we pin six ourselves as part of dependency-requirements.txt.

I'll try to get this fixed fast upstream so we don't have to burn energy working around it in our OS packages.

(I'm still not sure why six has anything to do with the import failure.)

**Comment by erikrose** [comment]
Submitted [a patch](https://github.com/shazow/urllib3/pull/1231).

**Comment by erikrose** [comment]
Now we wait for a new urllib3 release (1.22) and a new requests release that depends on it (>2.18.1), then we revise all our OS packages to depend on the new requests (which we may have to package).

**Comment by erikrose** [comment]
@bmw actually had a look at the .dsc file for the python-certbot package in Debian 9 (kudos) and found that it actually depends on python-six itself. So, @klevstul, you have something deeper and weirder going on.

**Comment by klevstul** [comment]
strange, @erikrose. seems like @kiarn and i had the same problems. my system has the same versions [as kiarn's](https://github.com/certbot/certbot/issues/4886#issuecomment-315458921).

**Comment by erikrose** [comment]
The new `requests` (2.18.2) is out, FWIW. If we have any OS packages that do *not* happen to pull in `six`, we should update them.

**Comment by bmw** [comment]
I mentioned this to Erik out of band, but we depend on `six` in Certbot's [setup.py](https://github.com/certbot/certbot/blob/d7f9859c3f69f76e27514c a59cf708929977631b/setup.py#L53) and we've done this since our [first non-dev release](https://github.com/certbot/certbot/blob/v0.1.0/setup.py#L46). With this in mind, all of our OS packages should be OK (and I'm not sure personally how this bug happened in the first place).

**Comment by JRCrawford** [comment]
Running `certbot --nginx -d yoursite.com` still results in an error on ubuntu 16.04.  I see that error is because the code here: https://certbot.eff.org/#ubuntuxenial-nginx still uses the old version: `    load_entry_point('certbot==0.21.1', 'console_scripts', 'certbot')()`

**Comment by caffeinum** [comment]
Any of these didn't help me.

```[user@localhost ~]$ certbot
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.26.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 21, in <module>
    from certbot import client
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 16, in <module>
    from acme import client as acme_client
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 39, in <module>
    urllib3.contrib.pyopenssl.inject_into_urllib3()
AttributeError: 'module' object has no attribute 'pyopenssl'
```

```[user@localhost ~]$ pip list | grep 'six\|req\|cert\|url'
certbot                          0.26.1     
certbot-nginx                    0.26.1     
certifi                          2018.4.16  
pycurl                           7.19.0     
requests                         2.19.1     
requests-toolbelt                0.8.0      
six                              1.11.0     
urlgrabber                       3.10       
urllib3                          1.22       ```

**Comment by cbillowes** [comment]
I know that it has worked on this server and then all of a sudden it didn't. Something must have gone wrong with my Python environment. After uninstalling Python then reinstalling certbot, I no longer got that error.
