### ISSUE TITLE
More copypastable output

### ISSUE THREAD

**Issue by maximal** [certbot/certbot#4893]
The thing is that cert paths are usually copied to another place (web server configs etc).

Now the successful output looks like this:
```
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/domain.com/fullchain.pem. Your cert
   will expire on 2666-06-06. To obtain a new or tweaked version of
   this certificate in the future, simply run certbot-auto again. To
   non-interactively renew *all* of your certificates, run
   "certbot-auto renew"
```

Notice a dot after the cert path which is being selected after the double-click on the terminal:
![image](https://user-images.githubusercontent.com/980679/27731421-8a80cc1a-5d95-11e7-9761-b0406e74a439.png)

I would also include a key path there, it is needed in most usecases (`ssl_certificate_key` in nginx). Now, I have to manually change `fullchain.pem` to `privkey.pem` in the cert path.

I think the following format would be way more usable:
```
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/domain.com/fullchain.pem
   Key file has been saved at:
   /etc/letsencrypt/live/domain.com/privkey.pem
   Your cert will expire on 2666-06-06. To obtain a new or tweaked
   version of this certificate in the future, simply run
   certbot-auto again. To non-interactively renew *all* of your
   certificates, run "certbot-auto renew"
```

What do you think?

**Comment by SwartzCr** [comment]
That makes sense to me! Would you be willing to make a PR with that change?

**Comment by cj-dev** [comment]
I can probably take this since there hasn't been word from the reporter in a bit.

**Comment by SwartzCr** [comment]
Fixed - thanks @cj-dev 
Feel free to find some other volunteer issues to fix!

**Comment by maximal** [comment]
Sorry guys. I’ve just been busy these days.

**Comment by SwartzCr** [comment]
No worries @maximal! Glad you're giving us good feedback!
