### ISSUE TITLE
Hook errors from dry-run

### ISSUE THREAD

**Issue by TheoJL** [certbot/certbot#4900]
I've just upgraded to Certbot 0.14.2 and in the middle of the upgrade I got this message that said _"The default certbot cron hooks have been disabled!"_. I don't really know what that means. 
Using **certbot renew --dry-run** will output some errors regarding the hooks, so something must have happened here I guess? 

My crontab looks like this 
`0 0 * * * certbot renew --post-hook "service apache2 reload" >> /var/log/le-renew.log`

## My operating system is (include version):
Ubuntu 16.04.2
Apache 2.4.18
Certbot 0.14.2

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
I believe it was certbot-auto

## I ran this command and it produced this output:
sudo certbot renew --dry-run

```-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/www.testsite.se.conf
-------------------------------------------------------------------------------
Cert not due for renewal, but simulating renewal for dry run
Running pre-hook command: /bin/run-parts /etc/letsencrypt/pre-hook.d/
Hook command "/bin/run-parts /etc/letsencrypt/pre-hook.d/" returned error code 1
Error output from run-parts:
run-parts: failed to open directory /etc/letsencrypt/pre-hook.d/: No such file or directory

Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for www.testsite.se
Waiting for verification...
Cleaning up challenges
Dry run: skipping renewal hook command: /bin/run-parts /etc/letsencrypt/renew-hook.d/

-------------------------------------------------------------------------------
new certificate deployed with reload of apache server; fullchain is
/etc/letsencrypt/live/www.testsite.se/fullchain.pem
-------------------------------------------------------------------------------
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)

Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/www.testsite.se/fullchain.pem (success)
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates above have not been saved.)
Running post-hook command: /bin/run-parts /etc/letsencrypt/post-hook.d/
Hook command "/bin/run-parts /etc/letsencrypt/post-hook.d/" returned error code 1
Error output from run-parts:
run-parts: failed to open directory /etc/letsencrypt/post-hook.d/: No such file or directory
```
There are some errors in this output

## Certbot's behavior differed from what I expected because:
Yes, there shouldn't be hook errors in my output above, right?

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
If you need the log I'll share it. 

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
not relevant

**Comment by SwartzCr** [comment]
@TheoJL Sorry to hear you're having this problem. It seems that this is a result of the path that the Ubuntu package took to get to it's current renewal configuration. For a while it was set up as systemd timers, which ran from those directories. Unfortunately this was set up in such a way that it'd override pre-existing cron renewal configurations, so it was changed back to a cronjob. It seems like now it also tries to include those systemd folders. But as you've noticed - if you skip over that version of the package you never get those folders and then get an error on renewal.
Hopefully @oerdnj is aware of this problem and has some thoughts on how to fix it for users who don't have the `pre-hook.d` and `post-hook.d` folders.
To fix your problem in the short term, I'd edit your `www.testsite.se.conf` file to remove references to these folders. Or make blank folders that correspond to the ones being referenced.

**Comment by SwartzCr** [comment]
@TheoJL have you gotten your configuration working?

**Comment by SwartzCr** [comment]
related to #3147

**Comment by TheoJL** [comment]
@SwartzCr 
When the day came for certbot to renew my certs it did so without any problem regardless of the errors. After that I followed your recommendation to remove the references in the ___.conf___ file and my error are now gone when I do ___dry-run___. So your solution was perfect, thank you!

Btw, these were the ones to remove:
```
post_hook = /bin/run-parts /etc/letsencrypt/post-hook.d/
renew_hook = /bin/run-parts /etc/letsencrypt/renew-hook.d/
pre_hook = /bin/run-parts /etc/letsencrypt/pre-hook.d/
```

**Comment by SwartzCr** [comment]
Great - I'm going to close this, feel free to open new issues if you run into any!
