### ISSUE TITLE
certbot.service: Failed at step EXEC spawning /usr/bin/certbot: No such file or directory

### ISSUE THREAD

**Issue by binarykitchen** [certbot/certbot#4909]
How can I investigate the above error best? What directory exactly is missing?

Using certbot version 0.16.0 on Ubuntu 17.04 here

**Comment by SwartzCr** [comment]
How did you install certbot?
Can you figure out where it's installed to?
@bmw is certbot supposed to be a service on ubuntu?

**Comment by binarykitchen** [comment]
already solved, had a mess with too many different installs of certbot. wish certbot would have detected and complained about this.
