### ISSUE TITLE
renew certs error through Haproxy

### ISSUE THREAD

**Issue by ibizista** [certbot/certbot#4913]
## My operating system is (include version):
Debian 8.7

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
 (I've changed the domain and IP)

certbot-auto certonly -n -d example.example.com --standalone --renew-by-default

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for example.example.com
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. example.example.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for tls-sni-01 challenge. Requested 852ba7cdb5c08e5cb264f2e47f203653.3c1752edd065662535953644bf49d80f.acme.invalid from 69.187.94.163:443. Received 2 certificate(s), first certificate had names "example.example.com"

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: example.example.com
   Type:   unauthorized
   Detail: Incorrect validation certificate for tls-sni-01 challenge.
   Requested
   852ba7cdb5c08e5cb264f2e47f203653.3c1752edd065662535953644bf49d80f.acme.invalid
   from 69.187.94.163:443. Received 2 certificate(s), first
   certificate had names "example.example.com"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.

I'm using a haproxy that catch all 
 /.well-known/acme-challenge
And send it to the server that manage the certs
## Certbot's behavior differed from what I expected because:

I've created the certificate in the same way succesfully
Haproxy manage diferents certs for the same IP, but, its working right if I use firefox or chrome.

## Here is the relevant HAPROXY server block for the domain I am configuring:
    acl letsencrypt path_beg -i /.well-known/acme-challenge
    rspadd Strict-Transport-Security:\ max-age=31536000;\ includeSubDomains;\ preload
    use_backend letsencrypt_server if letsencrypt

**Comment by ynasser** [comment]
@ibizista

My interpretation of what you're experiencing (and please correct me if I'm wrong) is that:

1. In the past you got a certificate for, say, `dog.example.com`.
2. You decide to change your server to `cat.example.com`.
3. Original certificate no longer works or is about to expire, so you try to renew and you get the above errors.

If you've changed the domain or subdomain, you either need to:
- get a new certificate for the new one, or
- add it to your old one by specifying the existing `certname` and adding the new domain via the `-d` flag (see here for instructions about certificate management: https://certbot.eff.org/docs/using.html#changing-a-certificate-s-domains)

Let me know if that helps or if I've misunderstood your problem.

**Comment by ibizista** [comment]
Hello,

Thanks for your answer.
I have multiple certificates, but have always had the same subdomain.
I think that maybe the problem is that Haproxy manage all certs in the same "virtual host", and when you get the page, haproxy send you the appropriate cert.

`The client lacks sufficient authorization :: Incorrect validation certificate for tls-sni-01 challenge. Requested 852ba7cdb5c08e5cb264f2e47f203653.3c1752edd065662535953644bf49d80f.acme.invalid from 69.187.94.163:443. Received 2 certificate(s), first certificate had names "example.example.com"`

If I use a browser or a curl, the certs seem valid:

```
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: example.example.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=example.example.com
* 	 start date: Wed, 03 May 2017 11:20:00 GMT
* 	 expire date: Tue, 01 Aug 2017 11:20:00 GMT
* 	 issuer: C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3
* 	 compression: NULL
* ALPN, server did not agree to a protocol
* Connection #0 to host example.example.com left intact
```

**Comment by SwartzCr** [comment]
I think the issue might be that you're using the wrong authentication method. You mentioned that you have it set up to move around things that end up in the `.well-known` directory in order to pass challenges. But the error output mentions that you're using the `tls-sni-01` challenge for authentication.  It's possible that the challenge type didn't get saved in your renewal configuration. Could you check to see if there's a line called `pref_challs`? And if not you could try to fix it by either requesting a new certificate and using the --preferred-challenges flag or by adding that line to the renewal conf with the value `http-01`
Let me know if that helps!

**Comment by ibizista** [comment]
Thanks!!!!
With **--preferred-challenges http** option works like a charm

**Comment by SwartzCr** [comment]
Awesome!
I'm going to close this issue, but feel free to open new ones if you run into more problems.
