### ISSUE TITLE
Challenge seems to fail because '/files' is not stripped from path to apache2.conf

### ISSUE THREAD

**Issue by codemusings** [certbot/certbot#4921]
## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Installed certbot from the PPA as per User Guide. Its version is `certbot 0.14.2`.

## I ran this command and it produced this output:
certbot --apache -d mydomain.com

## Certbot's behavior differed from what I expected because:
The challenge fails.

## Here is a Certbot log showing the issue (if available):
[letsencrypt.txt](https://github.com/certbot/certbot/files/1139290/letsencrypt.txt)

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
[mydomain.txt](https://github.com/certbot/certbot/files/1139297/mydomain.txt)

According to the letsencrypt.log file it seems that it tries to include the challenge config to the `apache2.conf` under `/files/etc/apache2/` which of course doesn't exist.

**Comment by gggerd** [comment]
Got the same issue (Ubuntu 16.4, too):
`Cannot find a cert or key directive in /**files**/etc/apache2/sites-available/...`

**Comment by SwartzCr** [comment]
hmmm maybe @joohoi has some insight on this

**Comment by SwartzCr** [comment]
Oh so this is actually the way that augeas lists files that it has knowledge of. `/files/` is an augeas annotation that is making it's way into the error output, but I don't think that it is what is causing this issue.
@codemusings I think the issue you're running into is that you have an overly broad listen directive somewhere that is preventing the certbot challenge cert from getting sent to the CA, see the final line of your error log:
`FailedChallenges: Failed authorization procedure. www.mydomain.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for tls-sni-01 challenge. Requested 5b4af91e3d8c7fd846a59073a56f5f08.7928546b09c32410ed04c6d96acfd551.acme.invalid from X.X.X.X:443. Received 1 certificate(s), first certificate had names "localhost.localdomain"`
@gggerd to answer your issue I'd need more information, would you be willing to open a new issue?

**Comment by adferrand** [comment]
This issue has not been updated for a long time, while info is required to move on. So I assume it is solved, or not relevant anymore. If not, do not hesitate to reopen an issue with updated info about its context.
