### ISSUE TITLE
Lack of Subject Name gives error on MacOS Sierra

### ISSUE THREAD

**Issue by wilddev65** [certbot/certbot#4922]
## My operating system is (include version):
MacOS 10.12.5, CentOS 7.3-1611

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
CentOS EPEL repository using Yum
Certbot version 0.14.1

## Certbot's behavior differed from what I expected because:
Certificate was issued with no Subject Name

I was able to install the certificate and have it currently running on my Apache server on CentOS. I am unable to generate a certificate with a Subject Name, only one's that have DNS SANs. For my Windows clients this doesn't seem to be an issue, however, MacOS Sierra gives net::ERR_CERT_INVALID and when examining the certificate the error is This certificate is not valid (empty subject name).
From reading through discussions it was stated that the first domain name on the cli with -d is used for the Subject Name, but this did not seem to work for me. Both a single domain name and multiple names resulted in them just being used in the SAN. I examined the CSR that certbot generated with openssl to verify that the SN was not in the CSR.

**Comment by SwartzCr** [comment]
This seems related to #4918
I'd watch that discussion as well

**Comment by wilddev65** [comment]
Not sure why you think this is related. Is it because the parsing of domains is failing? My main issue is I get no Subject Name in certificates and because of a bug in MacOS is is rejected outright.

**Comment by SwartzCr** [comment]
I'm sorry, maybe I'm misunderstanding. Would you be willing to point me to documentation on the Subject Name field of ssl certificates?

**Comment by wilddev65** [comment]
https://www.ietf.org/rfc/rfc5280.txt in 4.1.2.6.  Subject

**Comment by SwartzCr** [comment]
So I seem to have a certificate with CN = my.domain.name in the subject field. Can you link me to your cert so I can take a look at this?
This also doesn't seem like a problem with certbot necessarily, and maybe a problem with lets encrypt? So maybe @jsha should weigh in.

**Comment by wilddev65** [comment]
Ok, so the reason I think it's certbot is because the CSR also has no Subject. It's possible I am not putting something on the cli to generate it properly. This is what I used (note I'm using a special ACME server, not letsencrypt);
sudo certbot certonly --webroot -w /var/www/html --server https://ray.pki-warrior.com/vacme/v1/acme/directory --cert-name oliver.pki-warrior.com -d oliver.pki-warrior.com -d www.pki-warrior.com

I believe that the underlying CSR is generated using openssl by certbot, so I'm including the openssl version as well;

openssl 1.0.1e.60.el7_3.1

[certs.zip](https://github.com/certbot/certbot/files/1150036/certs.zip)

BTW, before I generate this cert, I had gotten one with letsencrypt and it also had no Subject.

**Comment by jsha** [comment]
> (note I'm using a special ACME server, not letsencrypt)

Which ACME server are you using? It's up to the CA policy whether to include one of the SANs in the Subject CommonName field. It's common practice to do so (in part because of breakage on macOS), but hostnames in CommonName are actually deprecated, and Let's Encrypt will eventually start issuing certain certificates without CommonName.

You may be able to solve your problem short term by providing a CSR to Certbot with `--csr`. In the long term, you should convince your CA to put something in the Subject when it would otherwise be empty. For instance, there's a proposal that's been put before the CA/Browser Forum to use dnQualifier for that purpose, which should work.

**Comment by wilddev65** [comment]
My CA is an internal MSCA and it's using Venafi as the ACME server. As such I have control over the CA and there isn't something to put in the subject that I need to convince the CA operator (me) to do. I realize CommonName is deprecated, however the issue is that from the cli with openssl I can generate a CSR with the Subject name correctly, but Certbot is not doing this correctly. As far as I can see from the forums, Certbot was generating the Subject as late as the end of last year and I see no discussion about it being removed. I'm not sure what else you need to be convinced this is something going wrong with Certbot, I have a lot of other certs not using this that work and generate a Subject Name.

**Comment by jsha** [comment]
I believe @tr1ck3r works for Venafi and may be able to help with software updates or configuration to get the behavior you want from your internal CA.

@tr1ck3r, TL;DR: Certificates with empty Subjects are likely to cause compatibility issues on some platforms. The best path forward, IMO, and the one being discussed at CA/Browser Forum, is to use [dnQualifier](https://cabforum.org/pipermail/public/2017-March/010146.html) to ensure that Subject is non-empty even when following best practices by omitting CommonName.

**Comment by lastusrnameon3** [comment]
@wilddev65  - I'm using Venafi as our certificate management software. 
We have a crap-load of certs and a small team to help our devs that (on soapbox) don't want to learn about certs or security (off soapbox) Has CertBot helped you automate the cert requests and renewals to a point where you you consider this for an enterprise solution?

**Comment by wilddev65** [comment]
@lastusrnameon3 Certbot fills a specific need for what it does. The question would be better does it fit your needs. There's lots of ways to skin this cat and Venafi provides alternatives to do that. I would talk to your support or sales people if automating requests with Venafi is what you want and they can give you the relevant information. This isn't really a forum for that question.

**Comment by lastusrnameon3** [comment]
Unfortunately there’s not many forums for this type of question, especially
with Venafi. But I’ll take it to the support site

**Comment by stiobhan** [comment]
I don't understand why this was closed without any action. Is it not `certbot` that creates the CSR with the empty subject field? Why not add a command line option for setting the subject field if that's what a user would like to do?

**Comment by parthjoshi-pc** [comment]
Agree with @stiobhan. I'm having issues with using Digicert's ACME directory URLs because they server responds with invalid common name whenever certbot sends a CSR without a Common Name in the Subject. It would be great if there was a command line parameter that could be used to control whether the CN is added or not.
