### ISSUE TITLE
certbot broke an apache vhost by not paying attention/warning about vhost-SAN needs

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#4927]
## My operating system is (include version):
RHEL6

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
```sh
./certbot-auto
...
Which names would you like to activate HTTPS for?
-------------------------------------------------------------------------------
{7 domains listed}
-------------------------------------------------------------------------------
Select the appropriate numbers separated by commas and/or spaces, or leave input
blank to select all options shown (Enter 'c' to cancel): 3
Obtaining a new certificate
Performing the following challenges:
...
Deploying Certificate for ... to VirtualHost /etc/httpd/conf.d/001-test-ssl.conf
...
Please choose whether or not to redirect HTTP traffic to HTTPS, removing HTTP access.
-------------------------------------------------------------------------------
1: No redirect - Make no further changes to the webserver configuration.
2: Redirect - Make all requests redirect to secure HTTPS access. Choose this for
new sites, or if you're confident your site works on HTTPS. You can undo this
change by editing your web server's configuration.
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 2
Redirecting vhost in /etc/httpd/conf.d/001-test.conf to ssl vhost in /etc/httpd/conf.d/001-test-ssl.conf
```

## Certbot's behavior differed from what I expected because:
It broke my SAN certificate (which held 2 of the 7 domains) and was used by the vhost that it was editing

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
(Available if necessary)

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
```
<VirtualHost *:80>
        Servername test.example.com
        ServerAlias example.example.org
        ServerAlias test
        ServerAlias example
</VirtualHost>
```

Essentially, by asking me a question about domains (1..7) instead of vhosts (1..4), certbot enabled me to replace a working SAN cert (which was configured for 2 of the 7 domains) for a vhost with a single domain cert (one of the 7 domains) for the vhost which broke the other domain.

When using the apache widget, it needs to be aware of related certs and should suggest converting them as sets. If a user asks to do something that would break a vhost, they should probably be told to edit the vhost first. if someone asks for all of the domains in a vhost + more, that's totally fine, since that wouldn't break a vhost, and could be useful if one is planning to expand...

**Comment by SwartzCr** [comment]
This seems like something @joohoi should be made aware of for his upcoming apache reliability work
