### ISSUE TITLE
./path/to/certbot-auto --nginx

### ISSUE THREAD

**Issue by allenwtl** [certbot/certbot#4937]
## My operating system is (include version):
CentOS release 6.8 (Final)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
wget  
https://certbot.eff.org/#centos6-nginx

## I ran this command and it produced this output:
--this command 
$ sudo ./path/to/certbot-auto --nginx

--output
Dependency Updated:
  python-libs.x86_64 0:2.6.6-66.el6_8                                                                                                                                                                    

Complete!
Creating virtual environment...
Installing Python packages...
Installation succeeded.
/root/.local/share/letsencrypt/lib/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
Saving debug log to /var/log/letsencrypt/letsencrypt.log
The nginx plugin is not working; there may be problems with your existing configuration.
The error was: NoInstallationError()

## Certbot's behavior differed from what I expected because:
i don't know

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

2017-07-15 14:25:35,514:DEBUG:certbot.main:certbot version: 0.16.0
2017-07-15 14:25:35,514:DEBUG:certbot.main:Arguments: ['--nginx']
2017-07-15 14:25:35,514:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2017-07-15 14:25:35,529:DEBUG:certbot.log:Root logging level set at 20
2017-07-15 14:25:35,529:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-07-15 14:25:35,529:DEBUG:certbot.plugins.selection:Requested authenticator nginx and installer nginx
2017-07-15 14:25:35,534:DEBUG:certbot.plugins.disco:No installation (PluginEntryPoint#nginx): 
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot/plugins/disco.py", line 130, in prepare
    self._initialized.prepare()
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot_nginx/configurator.py", line 155, in prepare
    raise errors.NoInstallationError
NoInstallationError
2017-07-15 14:25:35,535:DEBUG:certbot.plugins.selection:No candidate plugin
2017-07-15 14:25:35,535:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
nginx server

**Comment by SwartzCr** [comment]
Do you have nginx installed? I think certbot is complaining that it can't find nginx on your system

**Comment by allenwtl** [comment]
I have installed nginx, but still not. I would like to ask, “certbot-auto - nginx” this order is automatically added   https configuration  for nginx?   like this ?
![image](https://user-images.githubusercontent.com/3185867/28302701-8a61dbfe-6bc1-11e7-8085-7b07186e6f14.png)

**Comment by SwartzCr** [comment]
hmm I can't reproduce the problem with nginx installed
Can you give me the output of these commands?
`which nginx`
`yum info nginx`

**Comment by allenwtl** [comment]
![image](https://user-images.githubusercontent.com/3185867/28346607-a4f22390-6c64-11e7-82a7-1d64e8bdd07f.png)


![image](https://user-images.githubusercontent.com/3185867/28346615-b4046406-6c64-11e7-84b3-335a89fec4e7.png)

**Comment by SwartzCr** [comment]
Ah well if which can't find nginx then I bet certbot can't either. Can you figure out where it's installed to, and maybe move it to a proper place, or add it's path to your env_vars?

**Comment by zimmertr** [comment]
@SwartzCr @allenwtl 

When you manually build nginx from source it installs to `/usr/local/nginx/sbin/nginx` and is not automatically added to your PATH.

What environment variable should be exported so `Certbot` knows where to look for the binary?

**Comment by SadPencil** [comment]
@zimmertr
for me, I created two symlinks to solve this problem
```
ln -s /usr/local/nginx/sbin/nginx /usr/bin/nginx
ln -s /usr/local/nginx/conf/ /etc/nginx
```

**Comment by zimmertr** [comment]
@SadPencil that is exactly what I ended up doing. Well, I created the first symlink and then just modified my systemd service file to look for my config file where it's supposed to be... `/etc/nginx/sites-enabled/website.com.conf`

**Comment by SwartzCr** [comment]
@allenwtl did creating the symlinks that @SadPencil mentioned help?

**Comment by jacobshare** [comment]
thanks @SadPencil, I was having the exact same problem and for the same reasons. /etc/nginx was already being used for conf files, but once I setup the symlink to the nginx binary, my certbot-auto cron started running successfully

**Comment by mingalevme** [comment]
In case of CentsOS/RHEL: https://unix.stackexchange.com/questions/148133/how-to-set-crontab-path-variable. So add `. /etc/profile;` before your `certbot`-command, e.g.:
`0     1,13    *       *       *       . /etc/profile; sleep $((RANDOM\%3600)); certbot renew --quiet --post-hook "systemctl reload nginx"`

**Comment by Bryant-Yang** [comment]
I encountered this issue too, renew in cron task said not found nginx bin. cron has it's own PATH environment, so just add PATH assignment in your config (crontab -e), ahead the schedule line.
