### ISSUE TITLE
Getting error while installing certificates

### ISSUE THREAD

**Issue by adnanmayo** [certbot/certbot#4938]
## My operating system is (include version):
  OS Ubuntu 16.04
Amazon free-tier with 1 GB ram. I have also created a swapfile still getting the same error

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Trying to install with certbot -auto
`sudo certbot-auto --debug -v --server https://acme-v01.api.letsencrypt.org/directory certonly -d mydomain.com`

## I ran this command and it produced this output:
<img width="1440" alt="screen shot 2017-07-16 at 11 49 17 am" src="https://user-images.githubusercontent.com/9306690/28245394-2bf3e5d8-6a1f-11e7-8afa-50b037c0a9d2.png">

**Comment by fmd** [comment]
Me too, out of nowhere, on multiple servers. Looks like it's failing somewhere near pipstrap? Very worrying!

**Comment by fmd** [comment]
looks like `chown -R root:root ~/.cache` has fixed this, but no idea why it's happening like this out of nowhere.

**Comment by SwartzCr** [comment]
I wonder if pip changed something recently in how it works?
@erikrose any clue?
@fmd what OS are you experiencing this on?

**Comment by bouchard** [comment]
I've gotten this error on Ubuntu 16.04.

This error occurs if certbot-auto is run in a root shell (i.e. `sudo bash` after logging in as your web user). This error disappears if run as non-root (which I assume is intended behaviour - the regression is that it used to work as `root`).

Hope that helps!

**Comment by adnanmayo** [comment]
@bouchard  i have tried with out sudo it says permission denied on some directories is there another way?

**Comment by bouchard** [comment]
You probably need to delete those directories then... but maybe list them here first to check? Or alternatively you can chown them as your user.

**Comment by fmd** [comment]
@SwartzCr it happens on ubuntu `16.04`, things are fine on `14.04`. haven't tested any others. 
@bouchard as I wrote above, you're right, `sudo chown -R root:root ~/.cache` fixes the issue.

**Comment by bmw** [comment]
@erikrose, I think this is a bug in `pipstrap`. The underlying bug is probably in `pip` or `setuptools`, but now that buggy versions of those packages have been released, we have to live with it. I was able to repro on other systems by doing the following:
```
virtualenv --no-site-packages --setuptools venv
./venv/bin/pip install pip==9.0.1
./venv/bin/pip install setuptools==36.2.0
sudo ./venv/bin/python pipstrap.py
```

Until this is fixed, the solution is either to run `certbot-auto` without `sudo` (it'll use `sudo` internally when it's actually necessary) or use `sudo -H`.

**Comment by adnanmayo** [comment]
@fmd `sudo chown -R root:root ~/.cache` worked for me. Thanks

**Comment by erikrose** [comment]
@bmw I'm having trouble reproducing it reliably. I got it the first time, but now it just works quietly:

    [10:42:20]% virtualenv --no-site-packages --setuptools venv2
    New python executable in /Users/erose/Desktop/venv2/bin/python2.7
    Also creating executable in /Users/erose/Desktop/venv2/bin/python
    Installing setuptools, pip, wheel...done.% ./venv2/bin/pip install pip==9.0.1
    ./venv2/bin/pip install setuptools==36.2.0
    Collecting pip==9.0.1
      Using cached pip-9.0.1-py2.py3-none-any.whl
    Installing collected packages: pip
      Found existing installation: pip 8.0.2
        Uninstalling pip-8.0.2:
          Successfully uninstalled pip-8.0.2
    Successfully installed pip-9.0.1
    Collecting setuptools==36.2.0
      Using cached setuptools-36.2.0-py2.py3-none-any.whl
    Installing collected packages: setuptools
      Found existing installation: setuptools 19.6.1
        Uninstalling setuptools-19.6.1:
          Successfully uninstalled setuptools-19.6.1
    Successfully installed setuptools-36.2.0
    [12:11:49]% sudo ./venv2/bin/python /Users/erose/Checkouts/pipstrap/pipstrap.py
    Password:
    [12:12:13]%

It's not a bug in pip or pipstrap; pip is just trying to dodge a privilege escalation, and pipstrap does nothing but call pip. However, I think we could work around it in pipstrap by passing --no-cache-dir to pip.

Could somebody who can reproduce this reliably try adding --no-cache-dir to their pipstrap (just search for "pip install")?

**Comment by bmw** [comment]
> It's not a bug in pip or pipstrap; pip is just trying to dodge a privilege escalation, and pipstrap does nothing but call pip.

I agree that the error message is correct, but we shouldn't get a traceback.

I can reproduce fairly reliably. A few interesting things to note:

1. Using `--no-cache-dir` suppresses the warning, but we still get the traceback.
2. The problem occurs when installing the `setuptools` package.
3. Testing on both Ubuntu and Fedora, I get failures the first time, but if I try to run `pipstrap` again, the problem goes away.
4. If I modify `pipstrap` so that two `pip` invocations are used with the first one installing `pip` (and optionally `wheel`) and the second installing `setuptools`, it works.

@erikrose, having `pipstrap` use the approach described in 4) doesn't seem crazy to me. Would you like me to make a PR?

**Comment by bmw** [comment]
Actually, it looks like Ubuntu 16.04 updated their `virtualenv` package, `setuptools 36.2.4` is installed in the virtual environment, and `certbot-auto` now works without issue.

I'm closing this issue for now, but if anyone can reproduce on an up to date Ubuntu 16.04 system (or any other up to date system for that matter), please comment and I'll reopen.

**Comment by erikrose** [comment]
Yes, I'd take a PR to do 2 pip invocations, gladly.

**Comment by bmw** [comment]
Great. It's probably not a high priority at this point as I'm unaware of any distros that ship with a version of `pip` in `virtualenv` that have this problem, but I'll submit a PR once erikrose/pipstrap#11 lands to avoid merge conflicts.
