### ISSUE TITLE
Add Warning for Certificates Linking to Wrong Archive

### ISSUE THREAD

**Issue by gyroninja** [certbot/certbot#4940]
## My operating system is (include version):
Ubuntu 16.10

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
package manager

I was receiving error messages about being rate limited from renewing my certificate. Upon further investigation it turns out that my certificates in live/domain were not symlinked to the correct archive folder. This mismatch was causing certs to be generated rapidly and for confusion on my part. In order to avoid this it would be nice if there was a warning.
Inside of the renewal config file it should check that the cert, privkey, chain, and fullchain are symlinks into archive_dir. I could be missing a use case for why it would not be set up this way. It would also be in the best interest of Let's Encrypt if there wasn't a new certificate being issued twice a day.

**Comment by SwartzCr** [comment]
Oof this sounds like a bad problem
Can you be more specific about what happened in your case?
For example could you draw out for me what sym links were and were not there?
ls -la should give you a sense if any sym links were there (even if they were wrong)

**Comment by gyroninja** [comment]
Certs in /etc/letsencrypt/live/domain were symlinked to their respective file names in /etc/letsencrypt/archive_dir/notthedomainname
If you take a look at /etc/letsencrypt/renewl/domain.conf the archive_dir is set to /etc/letsencrypt/archive/domain and the certs are set to the symlink in /etc/letsencrypt/live/domain.
This mismatch between the correct archive_dir found in the config and the archive_dir used by the symlinks is the issue

**Comment by SwartzCr** [comment]
huh - that is strange. Do you happen to still have the log file from when those certificates were first generated? I'd be curious to see if there was a reason they were incorrectly symlinked in the first place. @bmw any idea why something like this might happen?

**Comment by bmw** [comment]
@gyroninja, have you manually done any modifications to the `/etc/letsencrypt` directory? While we should probably have more validity checks in our code, Certbot often behaves incorrectly if `/etc/letsencrypt` is put in an invalid state.

Also, it'd be useful to see all of the logs in `/var/log/letsencrypt`. That way we can track when the cert was created to when the symlinks were created incorrectly.

In every case of this I've seen (see https://community.letsencrypt.org/t/certbot-live-symlinks-not-updating-as-expected-new-certificate-available-but-not-used/35181/11), the user had improperly modified `/etc/letsencrypt`.

**Comment by gyroninja** [comment]
@bmw I manually renamed a directory, it wasn't certbot's fault. (This was due to me doing something and essentially now having like a domain-01 folder. I ended up renaming it back to domain which caused this problem).
While it was my bad for making this error, it would be best if certbot wasn't in a state where it would always **silently** fail requesting 2 new certificates for the domain every day (by default).

**Comment by bmw** [comment]
Yes, I completely agree we should handle cases like this better. Do you remember exactly what modification(s) you made so we can reproduce the problem and check for it in the future? Did you just change the name of the directory in `/etc/letsencrypt/archive`?

**Comment by gyroninja** [comment]
>Did you just change the name of the directory in /etc/letsencrypt/archive?
That was probably it. As I said in my OP the archive dir in the configuration and the archive dir used by the symlinks did not match. Detecting the mismatch would probably be enough.

**Comment by mnordhoff** [comment]
It's self-centered of me to say this without proposing a patch, but:

Can you bump the priority of this issue a bit, and stick it on the 1.0.0 milestone or something?

As far as we know, only like half a dozen people have run into this, but it's one of Certbot's worst failure modes. It's one thing if renaming files causes Certbot to stop working right; it's worse when it causes Certbot to stop working right **and** causes `certbot renew` to continually issue duplicate certificates.

**Comment by gyroninja** [comment]
Also when people realize they've encountered this bug, it will already be too late and become a big problem. Luckily, since I am mainly just a hobbyist I can handle the rate limits, but it would be disasterous if a larger site had to wait a week or whatever to be able to get a new certificate. This issue just creates unneeded stress for discoverring what the problem is (you have to notice a symlink is slightly wrong causing it to be broken), and not having any power to renew your certificate since you are rate limited.

**Comment by bmw** [comment]
I'll bump it into our next milestone for us to look at. Checking for specific modifications to `/etc/letsencrypt` and trying to clean up, print a warning, or error out nicely is easy and we already do a lot of this, but trying to detect this stuff in the general case is hard for us.

We've discussed other approaches such as dropping `README` files all over telling people that they should not modify these files or restructuring the directory to try and hide directories like `archive`, but none of these solutions are bulletproof.

If people have other ideas, I'd love to hear them or see a PR.

**Comment by mnordhoff** [comment]
[looks at @stale]
