### ISSUE TITLE
Implement authorization deactivation in acme

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#4945]
The acme package should offer a method to deactivate authorizations. I don't think this needs to be part of the Certbot CLI, but it would be useful for the Boulder integration tester (chisel) and possible other users of the acme package.

**Comment by tehfink** [comment]
Would this be part of the procedure for importing certificates/accounts from other clients?

**Comment by jsha** [comment]
Nope! :-)

**Comment by adferrand** [comment]
@jsha, is this requirement still relevant ?

**Comment by jsha** [comment]
I think so, but it's fairly low priority.

**Comment by adferrand** [comment]
OK, I put it on the wishlist then.
