### ISSUE TITLE
Certbot issues verification string / file name starting with underscore character  - causes BadRequest error in Zope application server

### ISSUE THREAD

**Issue by mtrebron** [certbot/certbot#4951]
## My operating system is (include version):
Ubuntu something LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
from git

## I ran this command and it produced this output:
```
root@localhost:/usr/local/src/git-repository/letsencrypt# ./certbot-auto certonly --manual -d example.com -d www.example.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Cert is due for renewal, auto-renewing...
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for example.com
http-01 challenge for www.example.com

-------------------------------------------------------------------------------
NOTE: The IP of this machine will be publicly logged as having requested this
certificate. If you're running certbot in manual mode on a machine that is not
your server, please ensure you're okay with that.

Are you OK with your IP being logged?
-------------------------------------------------------------------------------
(Y)es/(N)o: y

-------------------------------------------------------------------------------
Create a file containing just this data:

_0mEhMs-cOSAHjZ797i_3FNJpcTY_h8jvfOYtR0HfXo.GjGX4-3ANAgwv9Oo8bWgigOBDXw9_JfCZrGl0O5eAls

And make it available on your web server at this URL:

http://example.com/.well-known/acme-challenge/_0mEhMs-cOSAHjZ797i_3FNJpcTY_h8jvfOYtR0HfXo

-------------------------------------------------------------------------------
Press Enter to Continue

```

## Certbot's behavior differed from what I expected because:

A widely used web application server / content management framework: Zope / Plone barfs when asked to create a file which starts with an underscore.

e.g.
```
Zope Error

Zope has encountered an error while publishing this resource.

Error Type: BadRequest
Error Value: The id "_0mEhMs-cOSAHjZ797i_3FNJpcTY_h8jvfOYtR0HfXo" is invalid because it begins with an underscore.
```
###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
irrelevant
## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

```
# Everything else goes to Zope server
 RewriteRule ^/(.*) http://127.0.0.1:8080/VirtualHostBase/http/%{HTTP_HOST}:80/$1 [L,P]
```

**Comment by bmw** [comment]
Unfortunately, I don't think this is something that Certbot is able to fix. The need to provision a file with an underscore was mandated by the server which is following the [ACME protocol](https://github.com/ietf-wg-acme/acme) which is being standardized by the IETF. Certbot is an ACME client. If you would like to forbid ACME from requesting a file with a leading underscore, I recommend you send an email to the [ACME IETF mailing list](https://www.ietf.org/mailman/listinfo/acme).

I'm closing this as I don't think this problem is in the scope of Certbot, however, if you'd like to see us do something else, please comment and I'll consider reopening.

**Comment by mtrebron** [comment]
Thanks for the reply. Have crossposted to the Zope/Plone community, maybe someone there wishes to follow up at IETF level.
