### ISSUE TITLE
What are the IPs used by the server to verifiy my domain?

### ISSUE THREAD

**Issue by charlesmilette** [certbot/certbot#4954]
I am whitelisting access to my domain via IPTables, so i would like to know which ips i should whitelist to be able to have certbot verify my domain.

**Comment by SwartzCr** [comment]
For info on what IPs Let's Encrypt uses for validation you should read this thread on the Let's Encrypt community forums: https://community.letsencrypt.org/t/ip-addresses-le-is-validating-from-to-build-firewall-rule/5410/24
If you have more questions about this issue, you should probably ask there.
I'm going to close this issue, but if you have more questions feel free to open new issues, or ask on the community forums.
