### ISSUE TITLE
Decoding issue in python-pkg-resources shipped via Ubuntu PPA 

### ISSUE THREAD

**Issue by GhostLyrics** [certbot/certbot#4958]
## My operating system is (include version): 
Ubuntu 14.04.5 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Ubuntu PPA (`add-apt-repository …`)

## I ran this command and it produced this output:
the supplied cronjob

`/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py:1869: UserWarning: /usr/lib/pymodules/python2.7/rpl-1.5.5.egg-info could not be properly decoded in UTF-8
 warnings.warn(msg)`

```plain
python-pkg-resources:
  Installed: 33.1.1-1+certbot~trusty+1
rpl:
  Installed: 1.5.5-1
```

## Certbot's behavior differed from what I expected because:
This message only showed up after I installed `rpl` via the standard Ubuntu Trusty sources. Previously it ran perfectly quiet. The same thing seems to work without issue on Debian Jessie or Ubuntu Xenial.

*Please let me know if you believe this is not your bug instead of closing without comment so I can report it elsewhere.*

**Comment by bmw** [comment]
I can reproduce the problem by only installing `python-pkg-resources` from the PPA, installing `rpl` and running `python -c 'import pkg_resources'`. My guess the problem is a new version of `pkg-resources` with an older version of `rpl`.

@erikrose, do you have any thoughts here? If not, I can dig into it further.

**Comment by erikrose** [comment]
Nothing comes to mind.

**Comment by bmw** [comment]
Testing this in a virtual environment, installing the contents of the `rpl` package of Ubuntu, I get errors going all the way back to `setuptools==3.1` which is the version used in Trusty. Figuring out how to quiet this error message will take some digging into `setuptools` and `rpl`.

**Comment by erikrose** [comment]
One idea: what if rpl registers a setuptools entry point that has non-UTF-8-happy bytes in it? Certbot makes use of entry points, so the iteration over all the registered ones (embodied as files in the egg-info folders) could trigger the error.

**Comment by GhostLyrics** [comment]
If it is any help, I have the same symptoms with a second package, `python-elasticsearch-curator` from here: `http://packages.elasticsearch.org/curator/3/debian/ stable/main amd64 Packages`, version `3.5.1`.

**Comment by markussc** [comment]
Fixed the problem as follows: the file <code>/usr/lib/pymodules/python2.7/rpl-1.5.5.egg-info</code> contains author information which can not be decoded as UTF8 correctly. Simply rename "Göran Weinholt" to "Goran Weinholt" and you're fine!

**Comment by erikrose** [comment]
@markussc Have you thought about submitting that upstream?

**Comment by markussc** [comment]
@erikrose From what I understand, they are aware of it since quite some time: https://github.com/pypa/setuptools/issues/719
