### ISSUE TITLE
Certbot should provide information about how to rerun to debug

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#4959]
## My operating system is (include version):
Debian Stetch 9.0

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
```cron
13 7 * * * root /root/bin/certbot-renew
```
```#!/bin/sh
/root/bin/certbot-auto -q renew
```
## Certbot's behavior differed from what I expected because:

It doesn't tell me what command I should run in order to debug / what command failed.

> Encountered vhost ambiguity but unable to ask for user guidance in non-interactive mode.
> Currently Certbot needs each vhost to be in its own conf file,
> and may need vhosts to be explicitly labelled with ServerName or ServerAlias directives.

This is mentioned in #4727. It doesn't always appear, but I expect it to tell me which domain(s) / vhost(s) are impacting it.

> Falling back to default vhost *:443...

> Attempting to renew cert from /etc/letsencrypt/renewal/censored.conf produced an unexpected error:
> Failed authorization procedure. www.domain.brokencaa-response-from-dns-server.example.com (tls-sni-01):
> urn:acme:error:connection :: The server could not connect to the client to verify the domain ::
> DNS problem: SERVFAIL looking up CAA for www.domain.brokencaa-response-from-dns-server.example.com, domain.brokencaa-response-from-dns-server.example.com (tls-sni-01):
> urn:acme:error:connection :: The server could not connect to the client to verify the domain ::
> DNS problem: SERVFAIL looking up CAA for domain.brokencaa-response-from-dns-server.example.com. Skipping.

Problems:
If there's a problem, and running it interactively is necessary to resolve the problem, certbot should provide an actual commandline to be run with instead of forcing the user to guess. I've hit this general issue repeatedly.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

The logfile says:
```
2017-07-25 11:13:06,053:DEBUG:certbot.main:certbot version: 0.16.0
2017-07-25 11:13:06,054:DEBUG:certbot.main:Arguments: ['-q']
```

This is odd, since there's also a `renew` somewhere, I'm not sure where it went.

Running `HOME= /root/bin/certbot-auto renew` does not produce the same output as when run from cron.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

The vhost ambiguity message should indicate the domain(s) and vhost / config files which are confusing it to enable an admin to debug / try to improve matters.

Because it didn't, I really have no idea which one(s) are relevant. This system has 20+ letsencrypt issued certificates...

**Comment by SwartzCr** [comment]
I think there's some nuance to this issue. Would you be able to share the whole log file with me?
First of you're using CAAs which are relatively uncommon. Is the command `certbot-renew` aliased on your machine? Also I haven't seen a vhost ambiguity error before, so I'd really want to make sure I understand what's going on before I try to think of how best to prompt a user to debug.
Have you been able to resolve your issue?

**Comment by joohoi** [comment]
Closing, as it looks like this issue was solved quite a long time ago.
