### ISSUE TITLE
Fast-guide of use-cases as started

### ISSUE THREAD

**Issue by ppKrauss** [certbot/certbot#4961]
See [example here](https://github.com/ppKrauss/certbot-faq) and original discussion: https://community.letsencrypt.org/t/certbot-fast-guide/29969 

... Let's do something?

**Comment by SwartzCr** [comment]
Interesting!
I like this idea - sort of like a getting started guide.
I think we could write something like this, between me and @pconrad-fb and you it shouldn't be hard.
I think what would be most useful is a list of use cases that you'd like to see covered. Want to just write up a list of things you want to see covered and I can help with writing the guide itself?

**Comment by ppKrauss** [comment]
Hi @SwartzCr , thanks. Yes, let's use your knowledge to draft and discuss here a list of important use-cases... With time I will building, translating in guide topics... When  the guide grow with ~10 topics we think about definitive place and design.

PS: some use cases will be for "started guide" public, but all others (can grow) to show best practices, frequent uses/questions,  and to illustrate the many options of the `certbot` command (perhaps in the future the main documentation can citate use-cases as cross-reference).

**Comment by pconrad-fb** [comment]
This will be a cool project and I think will help untangle some of the confusion about how to do certain things.

**Comment by schoen** [comment]
Hi @ppKrauss,

Alguns colegas meus me avisaram hoje que você é falante nativo de português. Sou empregado da EFF trabalhando (às vezes) no projeto Certbot e falo português como língua estrangeira. Se quiser discutir quaisquer aspectos do projeto em português, ou se precisar de uma tradução de quaisquer conteúdos de português para inglês para fins de documentação, estarei disponível e também gosto bastante das oportunidades de usar a língua portuguesa no âmbito do meu trabalho. :smile:

**Comment by ppKrauss** [comment]
Hi @schoen,  

Obrigado pelo convite!  Que agradável surpresa alguém de fora abraçar o português! Vamos aproveitar então para expandir o projeto para outras línguas, tendo o inglês como referencial... Pronto, criei a primeira tradução como [README-pt.md](https://github.com/ppKrauss/certbot-faq/blob/master/README-pt.md). Você tem permissão para editar direto (sem pull-request) qualquer um dos READMEs, no inicio é mais prático. 

Posso ajudar  também  na revisão da [página Wikipedia Português do `certbot`](https://pt.wikipedia.org/wiki/certbot), que acha?

**Comment by pconrad-fb** [comment]
This issue dovetails with the comment I left on #5032 about chunking out the docs and making them more task-oriented. We should have quick tutorials for the 80% use cases.

**Comment by OlafvdSpek** [comment]
It'd be nice if common use cases wouldn't require users to read documentation. For example:
```
How would you like to authenticate with the ACME CA?
-------------------------------------------------------------------------------
1: Place files in webroot directory (webroot)
2: Spin up a temporary webserver (standalone)
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel):
```

As far as I know webroot is recommended but this isn't clear from the output.
Is standalone commonly used at all? If not, it might make sense to skip this question and default to webroot.

**Comment by SwartzCr** [comment]
@OlafvdSpek standalone is used in cases where there isn't already a webserver running, or when a user would prefer to not configure their webserver to host a .well-known file.
It is true that this is somewhat rarely used since it would require any existing webservers to temporarily stop operating, but similarly it'd be a large assumption to presume that an existing webserver would serve a .well-known directory.
I'm in favor of making what the two modes do more clear so that users can choose between them, but I'd prefer not to make a recommendation. Do you have a suggestion for how to do this?
It's possible that we could link to the documentation from this prompt, but the URLs might be too long to be aesthetic. What would you suggest?

**Comment by OlafvdSpek** [comment]
> it would require any existing webservers to temporarily stop operating,

What about doing the authentication on a non-standard port?

> but the URLs might be too long

URL shortener?

> Do you have a suggestion for how to do this?

The prompt should mention standalone is problematic with renewals. 
It should mention what is required (a given directory available on port 80, or was it 443?)

**Comment by SwartzCr** [comment]
Unfortunately the acme spec only accepts port 443 for authentication (see #4214 and #341) so users would have to configure that themselves.

Including a shortened link in the command line output for certbot scares me, unless EFF manages the shortened link, @starchy any interest in doing that?

Possibly under the prompt for the two it can link to a section in the documentation that explains what they do?

**Comment by starchy** [comment]
@SwartzCr You can very easily manage this yourself. Please search our wiki or open an internal ticket if you need help, but this would not be a good place to document that.

**Comment by SwartzCr** [comment]
reasonable, I'll investigate it once I'm back in the office

**Comment by SwartzCr** [comment]
I'm going to close this issue since it doesn't seem that we've made useful progress on it and no one else has expressed need for such a guide. If people feel differently I'd encourage them to take a first pass at such a guide and submit it as a PR
