### ISSUE TITLE
certbot-auto permission denied

### ISSUE THREAD

**Issue by poizenlab** [certbot/certbot#4968]
## Cannot execute ./certbot-auto

![issue](https://user-images.githubusercontent.com/6507233/28662059-6ccfa67c-72d6-11e7-86ed-d3b473e526c3.png)

**Comment by bmw** [comment]
Interesting. Sorry for the trouble.

What OS are you on? What's the output of `grep -m1 LE_AUTO_VERSION certbot-auto`? Does `su root -c 'apt-get update'` work when using the same user account as you were when you got this error?

**Comment by creepersbane** [comment]
Try `su root -c 'apt-get install sudo; sudo ./certbot-auto`
