### ISSUE TITLE
Been renewing on Ubuntu since 2016, Now Cannot Renew after tls-sni-01 challenge and "Connection refused"

### ISSUE THREAD

**Issue by bob-zs** [certbot/certbot#4976]
## My operating system is (include version):
Ubuntu recently upgraded from 14.04 trusty  to 16.04 xenial in digitalocean
With 
```
Server version: Apache/2.4.18 (Ubuntu)
```

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
With certbot command as shown in https://certbot.eff.org/#ubuntuxenial-apache

## I ran this command and it produced this output:
```bash
$certbot --apache
```
Output:
```shell
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org

Which names would you like to activate HTTPS for?
-------------------------------------------------------------------------------
1: my.domain.org
-------------------------------------------------------------------------------
Select the appropriate numbers separated by commas and/or spaces, or leave input
blank to select all options shown (Enter 'c' to cancel):1
Cert is due for renewal, auto-renewing...
Renewing an existing certificate
Resetting dropped connection: acme-v01.api.letsencrypt.org
Performing the following challenges:
tls-sni-01 challenge for my.domain.org
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. my.domain.org (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Connection refused

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: my.domain.org
   Type:   connection
   Detail: Connection refused

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
```

## Certbot's behavior differed from what I expected because:
We used the old `certbot-auto` back in September 2016 on our Ubuntu 14.04 trusty server, and it worked perfectly. After upgrading to xenial 16.04 and downloading the new version of the certbot client, as stated above, we have a `Failed authorization procedure. ` after the `tls-sni-01 challenge`.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
```
<VirtualHost *:80>
	ServerName my.domain.org

	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

     <Directory /var/www/html/>
                    Options Indexes FollowSymLinks MultiViews
                    AllowOverride All
                    Order allow,deny
                    allow from all
     </Directory>
RewriteEngine on
RewriteCond %{SERVER_NAME} =my.domain.org
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
```

**Comment by bob-zs** [comment]
Just for those trying to find the solution:
After a few hours, what ended up finally fixing the issue was turning off the apache server and turning it back on `service apache2 restart`, then rerunning the `certbot --apache` command. 

How did having the apache server restart allow the certbot to connect and validate the server?

**Comment by SwartzCr** [comment]
Hmm that's really bizarre
Do you know if you had been using the tls-sni-01 challenge the whole time (as opposed to say, the webroot challenge)?
It generally seems like apache got itself into a state where it wasn't accepting connections, but I don't know why that would have happened on a certbot upgrade. 
Just to confirm, you did manage to get your certificates renewed, yes?

**Comment by SwartzCr** [comment]
@bob-zs are you still encountering this problem? Or have you been able to get certbot working?

**Comment by bob-zs** [comment]
@SwartzCr, it is and it isn't still an issue. I still have the issue, but I found the issue goes away when I restart my apache server and quickly run the certbot immediately. Wait awhile after the restart, and the certbot doesn't work again:

Restart -> run certbot immediately -> works
Restart -> run certbot after some time -> error

**Comment by SwartzCr** [comment]
That's very strange
If you have through logs or steps that someone could use to reproduce this, I bet @joohoi would be interest in making sure we fix the underlying issue

**Comment by joohoi** [comment]
Certbot does restarts on it's own after adding the challenge configuration for Apache.

I'll take a wild guess what's going on in here; your server is under heavy or moderate load, serving requests that take a long time to serve. What Certbot uses for Apache restarts isn't the actual "restart" verb for apachectl, but "graceful" which restarts the workers but only after they have finished serving the requests, in order to not to kill active connections. Now the latency is too long or available connection pool is exhausted because of the load, and because the active connections haven't been forcefully shut down so Apache isn't able to serve the challenge. 

What you could do to debug the problem: after Apache has been serving for a while, try simple curl requests directly to the IP, with whatever Host header not in use, this is pretty much the thing that Let's Encrypt is doing in the renewal. for example `curl -v -k https://your.ip.address/ -H "Host: somethingsomething.whatever.invalid"`. And check how long it takes for your server to answer, perhaps by prepending the command with `time`.
