### ISSUE TITLE
Why do you enable SSLv3?

### ISSUE THREAD

**Issue by GlenKPeterson** [certbot/certbot#5]
When I look in lets-encrypt-preview / letsencrypt / client / options-ssl.conf, it looks like you are enabling SSLv3.  I thought that the POODLE attack rendered it obsolete?

I've found it really helpful to check my TLS settings here:
https://www.ssllabs.com/ssltest/

**Comment by schoen** [comment]
I made an updated list of resources for choosing ciphersuites and configurations at

https://github.com/letsencrypt/lets-encrypt-preview/wiki/Ciphersuite-guidance

("The great thing about standards is that there are so many to choose from.")
