### ISSUE TITLE
acme==0.18.0.dev0 missing

### ISSUE THREAD

**Issue by basd82** [certbot/certbot#5008]
## My operating system is (include version):

Ubuntu 16.04
## I ran this command and it produced this output:
 ./certbot-auto

## Certbot's behavior differed from what I expected because:

Error: couldn't get currently installed version for /root/.local/share/letsencrypt/bin/letsencrypt:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 9, in <module>
    from acme import jose
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 12, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: libssl.so.1.0.2: cannot open shared object file: No such file or directory

so i runed python ./setup.py install 

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

an then i get this error 

Installed /usr/local/lib/python2.7/dist-packages/certbot-0.18.0.dev0-py2.7.egg
Processing dependencies for certbot==0.18.0.dev0
Searching for acme==0.18.0.dev0
Reading https://pypi.python.org/simple/acme/
No local packages or download links found for acme==0.18.0.dev0
error: Could not find suitable distribution for Requirement.parse('acme==0.18.0.dev0')

**Comment by zingmars** [comment]
While `pip install certbot` did work for me, I had the same error message about it looking for libssl.so.1.0.2 when running from the repository (on Ubuntu 16.04 Server). What's that about?

**Comment by basd82** [comment]
Correct from the repo give that error

**Comment by skftn** [comment]
Same here. Production server(s) down.

**Comment by skftn** [comment]
acme 0.18.0.dev0 is not in pypi: https://pypi.python.org/pypi/acme

**Comment by SwartzCr** [comment]
@basd82 Sorry to hear you're having issues with certbot.
First off, installing via pip isn't recommended as you will run into many problems with using the proper python packages - it's highly recommended to use the packaged version of certbot instead.
In your original error I notice that you invoked certbot-auto instead of the `certbot` command like you would have if you had installed it from the certbot ppa. Also the version in the ppa is 0.14.2 not 0.17.0 which you claim to have.
Why did you choose to install it via certbot-auto and not the ppa? If you look at the install instructions, they recommend using the ppa: https://certbot.eff.org/#ubuntuxenial-apache 
Did you follow a different guide for installing certbot?
@zingmars I would recommend not installing via pip and instead getting a version of certbot from the PPA. Did you get a libssl error when you ran `apt-get install python-certbot`?
I tried to reproduce this on a fresh 16.04 install and couldn't. I was able to run the packaged version of python-certbot as well as certbot-auto.
Can you run `~/.local/share/letsencrypt/bin/pip freeze` and share what the output is?

**Comment by SwartzCr** [comment]
For example this is what I get:
```
root@noah-ubuntu-testlibssl:~/.local/share/letsencrypt/bin# ./pip freeze
acme==0.17.0
asn1crypto==0.22.0
certbot==0.17.0
certbot-apache==0.17.0
certbot-nginx==0.17.0
cffi==1.10.0
ConfigArgParse==0.10.0
configobj==5.0.6
cryptography==2.0.2
enum34==1.1.2
funcsigs==1.0.2
idna==2.5
ipaddress==1.0.16
letsencrypt==0.7.0
linecache2==1.0.0
mock==2.0.0
ordereddict==1.1
packaging==16.8
parsedatetime==2.1
pbr==1.8.1
pkg-resources==0.0.0
pycparser==2.14
pyOpenSSL==16.2.0
pyparsing==2.1.8
pyRFC3339==1.0
python-augeas==0.5.0
pytz==2015.7
requests==2.12.1
six==1.10.0
traceback2==1.4.0
unittest2==1.1.0
zope.component==4.2.2
zope.event==4.1.0
zope.interface==4.1.3
```
and 
```
root@noah-ubuntu-testlibssl:~/.local/share/letsencrypt/bin# dpkg -l | grep ssl
ii  libgnutls-openssl27:amd64        3.4.10-4ubuntu1.3                            amd64        GNU TLS library - OpenSSL wrapper
ii  libssl-dev:amd64                 1.0.2g-1ubuntu4.8                            amd64        Secure Sockets Layer toolkit - development files
ii  libssl1.0.0:amd64                1.0.2g-1ubuntu4.8                            amd64        Secure Sockets Layer toolkit - shared libraries
ii  openssl                          1.0.2g-1ubuntu4.8                            amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  python-openssl                   17.0.0-0+certbot~xenial+1                    all          Python 2 wrapper around the OpenSSL library
ii  ssl-cert                         1.0.37                                       all          simple debconf wrapper for OpenSSL
```

**Comment by SwartzCr** [comment]
Additionally can you tell me the output of `ls -d ${XDG_DATA_HOME:-~/.local/share}/letsencrypt/lib/python2.7/site-packages/cryptography*` ?

**Comment by zingmars** [comment]
In my instance (and I suspect in OP's as well) I was running certbot directly from a cloned repository. It was a really ancient install that was set up before the PPA was made, and was simply forgotten about (until I got the email about expiration a few days back, which makes for the 2nd time in the last few months as you guys managed to break my old Gentoo setup as well). I ran `pip install certbot` and the version that got installed seemed to work, but I guess I'll switch to the PPA when I get the chance.

**Comment by basd82** [comment]
Witch ppa?



Met vriendelijke mobiele groet,

Bas van Den Dikkenberg


-------- Oorspronkelijk bericht --------
Van: Ingmars Melkis <notifications@github.com>
Datum: 11-08-2017 18:54 (GMT+01:00)
Aan: certbot/certbot <certbot@noreply.github.com>
Cc: Bas van den Dikkenberg <bas@Dikkenberg.net>, Mention <mention@noreply.github.com>
Onderwerp: Re: [certbot/certbot] acme==0.18.0.dev0 missing (#5008)


In my instance (and I suspect in OP's as well) I was running certbot directly from a cloned repository. It was a really ancient install that was set up before the PPA was made, and was simply forgotten about (until I got the email about expiration a few days back, which makes for the 2nd time in the last few months as you guys managed to break my old Gentoo setup as well). I ran pip install certbot and the version that got installed seemed to work, but I guess I'll switch to the PPA when I get the chance.

-

**Comment by zingmars** [comment]
Er, package. I googled the package and saw a launchpad link and I instantly assumed it was a custom PPA for some reason. Sorry about that.

**Comment by SwartzCr** [comment]
The PPA can be found here: https://launchpad.net/~certbot/+archive/ubuntu/certbot

**Comment by SwartzCr** [comment]
I'm going to close this issue as it seems like you both have a path to a working setup of certbot. Feel free to open new issues if you run into future issues.

**Comment by basd82** [comment]
Please reopen

i did full reinstall from the ppa and still te same erorr
root@Joomla-lb1:/opt# apt-get install certbot python-certbot-apache python-certbot-doc python-certbot-apache-doc python-certbot
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  certbot python-certbot python-certbot-apache python-certbot-apache-doc python-certbot-doc
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 3006 kB of archives.
After this operation, 8777 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main amd64 python-certbot all 0.17.0-2+ubuntu16.04.1+certbot+1 [179 kB]
Get:2 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main amd64 certbot all 0.17.0-2+ubuntu16.04.1+certbot+1 [19.0 kB]
Get:3 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main amd64 python-certbot-apache all 0.17.0-1+ubuntu16.04.1+certbot+1 [38.7 kB]
Get:4 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main amd64 python-certbot-apache-doc all 0.17.0-1+ubuntu16.04.1+certbot+1 [72.0 kB]
Get:5 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main amd64 python-certbot-doc all 0.17.0-2+ubuntu16.04.1+certbot+1 [2697 kB]
Fetched 3006 kB in 2s (1240 kB/s)
Selecting previously unselected package python-certbot.
(Reading database ... 114400 files and directories currently installed.)
Preparing to unpack .../python-certbot_0.17.0-2+ubuntu16.04.1+certbot+1_all.deb ...
Unpacking python-certbot (0.17.0-2+ubuntu16.04.1+certbot+1) ...
Selecting previously unselected package certbot.
Preparing to unpack .../certbot_0.17.0-2+ubuntu16.04.1+certbot+1_all.deb ...
Unpacking certbot (0.17.0-2+ubuntu16.04.1+certbot+1) ...
Selecting previously unselected package python-certbot-apache.
Preparing to unpack .../python-certbot-apache_0.17.0-1+ubuntu16.04.1+certbot+1_all.deb ...
Unpacking python-certbot-apache (0.17.0-1+ubuntu16.04.1+certbot+1) ...
Selecting previously unselected package python-certbot-apache-doc.
Preparing to unpack .../python-certbot-apache-doc_0.17.0-1+ubuntu16.04.1+certbot+1_all.deb ...
Unpacking python-certbot-apache-doc (0.17.0-1+ubuntu16.04.1+certbot+1) ...
Selecting previously unselected package python-certbot-doc.
Preparing to unpack .../python-certbot-doc_0.17.0-2+ubuntu16.04.1+certbot+1_all.deb ...
Unpacking python-certbot-doc (0.17.0-2+ubuntu16.04.1+certbot+1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up python-certbot (0.17.0-2+ubuntu16.04.1+certbot+1) ...
Setting up certbot (0.17.0-2+ubuntu16.04.1+certbot+1) ...
Setting up python-certbot-apache (0.17.0-1+ubuntu16.04.1+certbot+1) ...
Setting up python-certbot-apache-doc (0.17.0-1+ubuntu16.04.1+certbot+1) ...
Setting up python-certbot-doc (0.17.0-2+ubuntu16.04.1+certbot+1) ...
root@Joomla-lb1:/opt# update-db
-bash: update-db: command not found
root@Joomla-lb1:/opt# updatedb
root@Joomla-lb1:/opt# certbot
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'acme==0.18.0.dev0' distribution was not found and is required by certbot

**Comment by SwartzCr** [comment]
the issue that you're running into is that you still have the previous version installed as well. 
It's trying to run certbot from `/usr/local/bin/certbot` instead of `/usr/bin/cerbot` where the version from the PPA should have ended up.
You'll probably see `/usr/local/bin/certbot` if you run `which certbot`
You'll need to uninstall the version that you installed with setup.py, maybe try `pip uninstall certbot`?
Let me know if that helps. Also you can join us on IRC in #letsencrypt on irc.freenode.org for more help

**Comment by basd82** [comment]
Yes everything works now

Van: Noah Swartz [mailto:notifications@github.com]
Verzonden: donderdag 24 augustus 2017 21:07
Aan: certbot/certbot <certbot@noreply.github.com>
CC: Bas van den Dikkenberg <bas@Dikkenberg.net>; Mention <mention@noreply.github.com>
Onderwerp: Re: [certbot/certbot] acme==0.18.0.dev0 missing (#5008)


the issue that you're running into is that you still have the previous version installed as well.
It's trying to run certbot from /usr/local/bin/certbot instead of /usr/bin/cerbot where the version from the PPA should have ended up.
You'll probably see /usr/local/bin/certbot if you run which certbot
You'll need to uninstall the version that you installed with setup.py, maybe try pip uninstall certbot?
Let me know if that helps. Also you can join us on IRC in #letsencrypt on irc.freenode.org for more help

**Comment by femz12** [comment]
I am having the same issue as above I ran `pip uninstall certbot` i got an error

Cannot uninstall requirement certbot, not installed
Storing debug log for failure in /home/ubuntu/.pip/pip.log

What can I do?

`which certbot` shows `/usr/local/bin/certbot`
