### ISSUE TITLE
Don't crash when writing the cert to disk

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5009]
We've had a number of problems due to assumptions made about the layout of `/etc/letsencrypt`. Unfortunately, we had one user for whom `--dry-run` succeeded, however, we'd always crash when writing the cert to disk during renewal with the traceback:
```
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 626, in obtain_cert
    action, _ = _auth_from_available(le_client, config, domains, certname, lineage)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 103, in _auth_from_available
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/lib/python2.7/dist-packages/certbot/renewal.py", line 306, in renew_cert
    lineage.save_successor(prior_version, new_cert, new_key.pem, new_chain, config)
  File "/usr/lib/python2.7/dist-packages/certbot/storage.py", line 1060, in save_successor
    with open(target["privkey"], "w") as f:
IOError: [Errno 2] No such file or directory: '/etc/letsencrypt/archive/<domain>/privkey2.pem'
```
To help with matching line numbers, the version being used is 0.10.2.

While we can only be so defensive against user changes, crashing at this point is not OK. Ideally, `--dry-run` should never succeed when real issuance fails and we shouldn't crash when writing the cert to disk. 

We need to check for problems like this earlier in Certbot's execution so avoid rate limiting users and allow them to debug the problem using `--dry-run`.

**Comment by mnordhoff** [comment]
This still matters, bot. (Probably.)
