### ISSUE TITLE
Configuration file version differences documentation (I have a mismatch)

### ISSUE THREAD

**Issue by JetForMe** [certbot/certbot#5013]
## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot ppa

## I ran this command and it produced this output:
`/usr/bin/letsencrypt renew --renew-hook "service nginx reload"`

## Certbot's behavior differed from what I expected because:
It seemed to work, but I got this warning:

```
Attempting to parse the version 0.17.0 renewal configuration file found at /etc/letsencrypt/renewal/mydomain.org.conf with version 0.14.2 of Certbot. This might not work.
```

This occurred after I updated from the default certbot available with Ubuntu to the one provided by Let's Encrypt's PPA. I don't recall which version was installed before, but I thought it was something like 0.4.1. So, I don't know why I have a config file with version 0.17.0 specified.

Config file:
```
# cat /etc/letsencrypt/renewal/mydomain.org.conf
# renew_before_expiry = 30 days
cert = /etc/letsencrypt/live/mydomain.org/cert.pem
privkey = /etc/letsencrypt/live/mydomain.org/privkey.pem
chain = /etc/letsencrypt/live/mydomain.org/chain.pem
fullchain = /etc/letsencrypt/live/mydomain.org/fullchain.pem
version = 0.17.0
archive_dir = /etc/letsencrypt/archive/mydomain.org

# Options and defaults used in the renewal process
[renewalparams]
installer = None
authenticator = webroot
account = <redacted>
[[webroot_map]]
mydomain.org = /var/www/html
```

I couldn't find anything that discusses the the config file differences between versions. Can I just change the version number here to silence the warning? Or does my config file need to change in some way. I think it was generated by the previous certbot that was installed, but again, I don't know why the version is 0.17.0.

I updated to the PPA version (0.14.2) in order to be able to use the `--renew-hook` option.

**Comment by SwartzCr** [comment]
Have you ever run `certbot-auto` of `letsencrypt-auto`? If so, that could have created a 0.17.0 config file.
We haven't changed the format of the config files between 0.14.2 and 0.17.0, so you should be alright.

**Comment by bmw** [comment]
I think this question was answered so I'm closing the issue.
