### ISSUE TITLE
skipped output is too noisy for certbot -q renew

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#5016]
## My operating system is (include version):
debian 9.1

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto 0.17.0

## I ran this command and it produced this output:
```sh
certbot-auto -q renew

...
Attempting to renew cert (broken.example.com) from /etc/letsencrypt/renewal/broken.example.com.conf produced an unexpected error: Failed authorization procedure. www.test.other.example.net (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: DNS problem: SERVFAIL looking up CAA for www.test.other.example.net, test.other.example.net (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: DNS problem: SERVFAIL looking up CAA for test.other.example.net. Skipping.

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/a.example.com/fullchain.pem (skipped)
  /etc/letsencrypt/live/b.example.com/fullchain.pem (skipped)
  /etc/letsencrypt/live/c.example.com/fullchain.pem (skipped)
  /etc/letsencrypt/live/b.example.com-0001/fullchain.pem (skipped)
  /etc/letsencrypt/live/e.example.com/fullchain.pem (skipped)
  /etc/letsencrypt/live/f.example.com/fullchain.pem (skipped)
  /etc/letsencrypt/live/example.org/fullchain.pem (skipped)
  /etc/letsencrypt/live/g.site.example.com/fullchain.pem (skipped)
  /etc/letsencrypt/live/example.net/fullchain.pem (skipped)
  /etc/letsencrypt/live/h.example.net/fullchain.pem (skipped)
  /etc/letsencrypt/live/i.example.com/fullchain.pem (skipped)
  /etc/letsencrypt/live/j.test.site.example.com/fullchain.pem (skipped)
  /etc/letsencrypt/live/broken.site.example.com/fullchain.pem (skipped)
  /etc/letsencrypt/live/k.example.com/fullchain.pem (skipped)
  /etc/letsencrypt/live/www.h.example.net/fullchain.pem (skipped)
  /etc/letsencrypt/live/l.example.com/fullchain.pem (skipped)
  /etc/letsencrypt/live/m.example.com/fullchain.pem (skipped)
  /etc/letsencrypt/live/site.example.com/fullchain.pem (skipped)
  /etc/letsencrypt/live/n.example.com/fullchain.pem (skipped)
  /etc/letsencrypt/live/o.example.com/fullchain.pem (skipped)
  /etc/letsencrypt/live/p.example.com/fullchain.pem (skipped)
  /etc/letsencrypt/live/q.example.net/fullchain.pem (skipped)
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/broken.example.com/fullchain.pem (failure)
1 renew failure(s), 0 parse failure(s)
```

## Certbot's behavior differed from what I expected because:
I'm drowning in information that really isn't relevant to what I was trying to do. And I mean drowning -- best practices for certbot is that it runs twice daily from cron, that means that I'm getting 2 emails a day (I was on vacation for a week) where ~80% of the content is noise (22/28 lines per email * ~20 emails).

Personally, if I have more than 3 sites, all I want is:
1. the ones that are failing
2. the ones that were renewed (probably, although, possibly not)
3. a count of the number of sites that were skipped (maybe, possibly not even) -- but if it's included, it should be on that last line that currently says "1 renew failure(s), 0 parse failure(s)"

So, it should have said:

```sh
certbot-auto -q renew

...
Attempting to renew cert (broken.example.com) from /etc/letsencrypt/renewal/broken.example.com.conf produced an unexpected error: Failed authorization procedure. www.test.other.example.net (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: DNS problem: SERVFAIL looking up CAA for www.test.other.example.net, test.other.example.net (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: DNS problem: SERVFAIL looking up CAA for test.other.example.net. Skipping.

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/broken.example.com/fullchain.pem (failure)
1 renew failure(s), 0 parse failure(s), 22 not due for renewal
```

**Comment by SwartzCr** [comment]
Oh interesting!
It looks like the thing that outputs that is an errant print statement in renewal.py rather than a logger call, which would get silenced by `-q`
It's here: https://github.com/certbot/certbot/blob/142ced234b7561c24f2fd089090cf16b64566ae8/certbot/renewal.py#L361
It looks like @pde wrote this even when there were other logger calls in the file so I don't want to definitely say that it shouldn't be there: https://github.com/certbot/certbot/commit/f5e0aca89129918bc488a97452b7714274ebe956
But maybe @bmw can say if it should be changed. If so, it's an easy fix!

**Comment by bmw** [comment]
Yes this should be changed. The high level issue for this is #3720.

**Comment by SwartzCr** [comment]
@r5d, @ecastro, or @dhuang: Any of you up for doing this simple PR?

**Comment by r5d** [comment]
@SwartzCr, I'll look into it.

**Comment by SwartzCr** [comment]
Awesome! Let me know if you need any help!

**Comment by r5d** [comment]
@SwartzCr, Does this b8db13b397e67c7f1e5433eae0bc61a76dc98dc6 look good?

**Comment by bmw** [comment]
@r5d, I added some comments to your commit, but I think you're on the right track!

**Comment by r5d** [comment]
@bmw, Thanks for the feedback. See if this looks good: https://github.com/r5d/certbot/commit/12d874eabfe3fb9b932ee2b3627946404ba15d70 ([tests pass](https://travis-ci.org/r5d/certbot/builds/269435640))

**Comment by bmw** [comment]
Other than my nitpicky inline comment, it LGTM. Feel free to open a PR!

**Comment by r5d** [comment]
@bmw, opened a PR (https://github.com/certbot/certbot/pull/5062).

**Comment by bmw** [comment]
Fixed in #5062.

**Comment by SwartzCr** [comment]
Awesome! Thanks @r5d!
If you have some more time, we'd love some help with #4350 or #4879, let me know if you want to work on either of those, or need any pointers to get started!

**Comment by r5d** [comment]
@SwartCr, I'll look into #4350.
