### ISSUE TITLE
Allow to set Posix ACLs on keys and directories

### ISSUE THREAD

**Issue by s-fritsch** [certbot/certbot#5017]
As discussed in the BoF at Debconf17:

In order to avoid having to copy key files with different permissions to a location that a server can access them, it would be nice if one could set arbitrary Posix ACLs on the keys files and the directories they are located in. See the getfacl / setfacl man pages for more information.

If this should be done via some hook script, maybe you could provide some pointers in the documentation.

**Comment by SwartzCr** [comment]
Thanks for filing the issue!
I'm going to tag @bmw to see if he has thoughts on this and how we should prioritize this

**Comment by bmw** [comment]
The main issue for this is #1473 which discusses changes the default and allowing users to set their own values.

**Comment by JoKeyser** [comment]
@s-fritsch , I guess you refer to the Let's Encrypt BoF? On https://debconf17.debconf.org/talks/188/ no minutes are indicated, but maybe there exist some?
I would be interested in the reasoning behind this request, and more specifically whether there are any plans in Debian to formulate/implement a consensus what the file permissions should be -- especially in regards to using the certs and keys by different daemons/servers (see https://github.com/freedombox/Plinth/issues/1125).

**Comment by eomanis** [comment]
One can use default ACLs on directories to control which ACLs newly created files get, and can for example place such default ACLs on the "archive" directory in the configuration directory.
In my setup this is how I grant the "http" user read access to the .pem files.

Unfortunately certbot makes a mockery of this by deliberately applying 0600 permissions to the privkeyN.pem files.
I was forced to set up my automatic renewal job in such a way that after certbot is done a script is run that restores readability of these files for the "http" user.

An option `--ignore-permissions` that turns off any permissions handling whatsoever, and makes certbot assume that all permissions-related things are handled by other means, would have saved me this hassle, and might be rather straightforward to implement.

(Personal opinion coming, stop reading if you don't care)
Generally I suspect that having applications make assumptions about a system's permissions setup is conceptually flawed – the applications typically lack the information required for a good decision, and they therefore often rely on possibly wrong assumptions. Examples of this include `gpg` and `rsync` which both refuse to do certain things if they do not like certain configuration files' permissions, and are at the same time completely oblivious of eventual ACLs on said files.

**Comment by expressrussian** [comment]
> An option `--ignore-permissions` that turns off any permissions handling whatsoever, and makes certbot assume that all permissions-related things are handled by other means, would have saved me this hassle, and might be rather straightforward to implement.
-----------------
Yes, we need a solution to our problems with non-root applications which do not use privilege elevation. These non-root users/groups need to have an access to the certificates/keys.

**Comment by bmw** [comment]
There still is not a way to set arbitrary ACLs on certs/keys created on Certbot, but just in case anyone reading this is not aware, Certbot does preserve the group owner and permissions between renewals. From our 0.29.0 changelog:

> Private key permissioning changes: Renewal preserves existing group mode & gid of previous private key material. Private keys for new lineages (i.e. new certs, not renewed) default to 0o600.
