### ISSUE TITLE
deleted vhost doesn't suggest deleting corresponding letsencrypt config

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#5018]
## My operating system is (include version):
CentOS release 6.9

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot 0.17.0

## I ran this command and it produced this output:
`certbot -q renew`

triggering:
`Encountered vhost ambiguity but unable to ask for user guidance in non-interactive mode. Certbot may need vhosts to be explicitly labelled with ServerName or ServerAlias directives.`

## Certbot's behavior differed from what I expected because:
At one point there was an apache vhost for this config, there now isn't.

It would be nice if certbot knew that it had seen a vhost (and which config file) and could say "your vhost seems to have been deleted did you forget to delete the letsencrypt config?"

**Comment by jsoref** [comment]
Actually, I think I'm wrong. I may have been mislead...
In this case, I had a proxy running on a different server, and had decommissioned the site from the proxy but failed to remove the letsencrypt config...
Sorry.

**Comment by jsoref** [comment]
Actually, thinking about this some more...

Ideally, certbot should be able to know that there once /was/ an apache config, and that it seems to be missing. It is totally reasonable for an admin (like me) to delete an apache config and neglect to delete the corresponding certbot bits (it isn't particularly obvious to anyone how to do that).

**Comment by SwartzCr** [comment]
Interesting, I can see why this might be useful, but I'm not really sure how we'd implement it or if it's worthwhile for us to spend upcoming dev time to work on this.
I'm going to put this in the wishlist milestone, though if someone came along with a PR it could get merged earlier.

**Comment by jsoref** [comment]
Offhand, the easiest implementation is to record which file was responsible for a domain. There next time around, if there's no matching domain, it can check to see the status of the file...

**Comment by jsoref** [comment]
Sorry bot, I can't imagine this was fixed w/o consulting this bug.
