### ISSUE TITLE
Automatic creation of a certificate without having to agree to terms?

### ISSUE THREAD

**Issue by eddiejibson** [certbot/certbot#5020]
Hi,

So I want to be-able to just execute a command line to generate a certificate without having to agree to multiple terms as this can't be automated. Of course I'm more than happy to set that I agree globally to such terms in a config file.

I just want this to work easily within the PHP shell execution function and without having to manually agree to the terms each time, it can be done easily.

Is there anyway of doing this via commandline? 

Thank-you.

**Comment by schoen** [comment]
Hi @eddiejibson,

If you add `--agree-tos` to your Certbot command line, then it will always indicate agreement without a user interaction.

My recollection is also that your agreement is saved somewhere after you've agreed for the first time. I believe this is saved locally in the account data under `/etc/letsencrypt/accounts`.

**Comment by eddiejibson** [comment]
Great, this helped a lot. Thank-you.

**Comment by eddiejibson** [comment]
Hi @schoen,

I just tried doing this:

sudo certbot certonly --webroot -w (my domain dir) -d (my domain) --agree-tos

Yet it still asked me for both my email and to agree to the terms?

Thanks again

**Comment by SwartzCr** [comment]
You should also be able to specify the email on the command line as well, see the output of `certbot --help register` or look at all the command line options here: https://certbot.eff.org/docs/using.html#certbot-command-line-options

**Comment by SwartzCr** [comment]
I am going to close this as it seems due to the lack of response that it's been resolved. @eddiejibson if you are still having issues, please let us know

**Comment by mrunc** [comment]
Well there is also the email sharing question how can you automate saying no to that too?

**Comment by bmw** [comment]
You're probably referring to the question of sharing your email address with EFF. You can say no to that on the command line with `--no-eff-email`.

**Comment by mrunc** [comment]
@bmw Thank you, that was helpful
