### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by kamikaze** [certbot/certbot#5024]
Are you really sure that certbot needs so many zope-like dependencies to work over the network with letsencrypt? How about lowering dependency count?

**Comment by SwartzCr** [comment]
Hi @kamikaze! We've done a lot of work to limit the dependencies that we use. Is there a specific one that you have an issue with?
If you'd prefer to use a client with less dependencies, you can try using letsencrypt-nosudo: https://github.com/diafygi/letsencrypt-nosudo

**Comment by bmw** [comment]
Closing as an issue of #1301.
