### ISSUE TITLE
provide a param to turn off symlink, use copy file

### ISSUE THREAD

**Issue by zh99998** [certbot/certbot#5027]
currently generated certificate in `live` directory are using symlink.
it's inconvenience in some use case, for example, docker volume.
If it's regular file, I can just mount the `fullchain.pem`and `privkey.pem` into app's default cert path.

but it's symlink so I must mount whole directory into container, and specific cert path in app's configuration. well... some app may don't have such a configuration and forced path to somewhere like `cert.pem` in its path. I have to copy that file into such destination and... well docker even don't allow a pre-start hook so I even have to override `cmd` or `entrypoint` to a shell script... it's such complex.

if there is a switch to make them to a regular file, everything will work fine.

**Comment by SwartzCr** [comment]
You should be able to use a certbot hook to manually move or copy the file to a place where docker can see it - though I don't know if this will cause similar problems with dockers permissions.
For more info on the certbot hooks you can read about them here: https://certbot.eff.org/docs/using.html#pre-and-post-validation-hooks
