### ISSUE TITLE
key too large 8192 

### ISSUE THREAD

**Issue by lgg** [certbot/certbot#5031]
## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt-get install certbot

## I ran this command and it produced this output:
`sudo certbot certonly --standalone --preferred-challenges http --rsa-key-size 8192 -d mydomain.com`

## Certbot's behavior differed from what I expected because:
>The request message was malformed :: Invalid key in certificate request :: key too large: 8192 > 4096

But I can't find any faq/docs with key-size limits

this is certbot limits or let's encrypt limits?

**Comment by schoen** [comment]
Hi @lgg,

It's a Let's Encrypt limit, not a Certbot limit. (Indeed, the nature of the error shows that Certbot attempted to send your request to the Let's Encrypt CA, and the CA replied that it was disallowed.)

See "DV-SSL End Entity Certificate" in

https://letsencrypt.org/documents/isrg-cps-v2.0/

The maximum subject key modulus size for an RSA key is 4096 bits.

**Comment by cpu** [comment]
If you're also interested in seeing this from a programmatic angle in addition to the policy side that @schoen shared (Thanks!) the [Boulder CA](https://github.com/letsencrypt/boulder/) uses the [goodkey](https://github.com/letsencrypt/boulder/blob/e670e6e6b5db9a8173d506b6d6e1e78084cf4f10/goodkey/good_key.go) package for this purpose. [This is the function](https://github.com/letsencrypt/boulder/blob/e670e6e6b5db9a8173d506b6d6e1e78084cf4f10/goodkey/good_key.go#L196:L238) that checks RSA keys and rejects greater than 4096 bit RSA moduli. There is [a similar goodkey function for ECDSA keys](https://github.com/letsencrypt/boulder/blob/e670e6e6b5db9a8173d506b6d6e1e78084cf4f10/goodkey/good_key.go#L85:L172).
