### ISSUE TITLE
Zesty PPA missing

### ISSUE THREAD

**Issue by gregbenner** [certbot/certbot#5036]
## My operating system is (include version):
17.04 Ubunutu

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
$ sudo apt-get update
$ sudo apt-get install software-properties-common
$ sudo add-apt-repository ppa:certbot/certbot
$ sudo apt-get update
$ sudo apt-get install python-certbot-nginx 

## I ran this command and it produced this output:
 sudo apt-get install python-certbot-nginx 

## Certbot's behavior differed from what I expected because:
`W: Failed to fetch http://ppa.launchpad.net/certbot/certbot/ubuntu/dists/jessie/main/binary-amd64/Packages  404  No
t Found`

**Comment by SwartzCr** [comment]
That's weird, it's definitely here: https://launchpad.net/~certbot/+archive/ubuntu/certbot?field.series_filter=zesty
maybe the url got messed up somehow?

**Comment by gregbenner** [comment]
It's through the automated script, so probably a bug somewhere. I managed the install manually for myself.

**Comment by SwartzCr** [comment]
Okay great! Glad you got it working!
I'm going to close this issue, but feel free to open new ones if you run into any more problems!

**Comment by Juddling** [comment]
This is no longer there for me, I'm assuming because zesty reached EOL in Jan 2018, is there any way I can still install?
