### ISSUE TITLE
(tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the do MAIN ::TIMEOUT

### ISSUE THREAD

**Issue by denispolicarpocampos** [certbot/certbot#5042]
## My operating system is (include version): 

CENTOS 7.3

## I installed Certbot with (certbot-auto, OS package manager, pip, etc): 

certbot-auto

## I ran this command and it produced this output:

./letsencrypt-auto certonly --standalone

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Cert is due for renewal, auto-renewing...
Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for ped.lupatecnologia.com.br
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. ped.lupatecnologia.com.br (tls-sni-01): urn:acme                                                :error:connection :: The server could not connect to the client to verify the do                                                main :: Timeout

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: ped.lupatecnologia.com.br
   Type:   connection
   Detail: Timeout

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.

## Here is a Certbot log showing the issue (if available):

2017-08-21 17:46:29,460:DEBUG:certbot.reporter:Reporting to user: The following errors were reported by the server:

Domain: ped.lupatecnologia.com.br
Type:   connection
Detail: Timeout

To fix these errors, please make sure that your domain name was entered correctly and the DNS A/AAAA record(s) for that domain contain(s) the right IP address. Additionally, please check that your computer has a publicly routable IP address and that no firewalls are preventing the server from communicating with the client. If you're using the webroot plugin, you should also verify that you are serving files from the webroot path you provided.
2017-08-21 17:46:29,460:INFO:certbot.auth_handler:Cleaning up challenges
2017-08-21 17:46:29,461:DEBUG:certbot.plugins.standalone:Stopping server at :::443...
2017-08-21 17:46:29,485:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 753, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 692, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 77, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/renewal.py", line 297, in renew_cert
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/client.py", line 318, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/auth_handler.py", line 81, in get_authorizations
    self._respond(resp, best_effort)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/auth_handler.py", line 138, in _respond
    self._poll_challenges(chall_update, best_effort)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/auth_handler.py", line 202, in _poll_challenges
    raise errors.FailedChallenges(all_failed_achalls)
FailedChallenges: Failed authorization procedure. ped.lupatecnologia.com.br (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout
[root@ped letsencrypt]# ./letsencrypt-auto certonly --standalone Domain: ped.lupatecnologia.com.br
-bash: ./letsencrypt-auto: Arquivo ou diretório não encontrado

**Comment by creepersbane** [comment]
The site you are updating the certificate is unresponsive. Make sure the domain is pointing to the correct address.

The current IP of the domain is 200.195.38.35

**Comment by liyu001989** [comment]
same issue, because my vps deny 443 port default

**Comment by M1seRy** [comment]
same issue with nginx + centOS: Failed authorization procedure. (tls-sni-01): urn:acme:error:connection ,The server could not connect to the client to verify the domain.

**Comment by whoget** [comment]
Allow open port 443 in firewall or security group roles

**Comment by AnjaneyuluBatta505** [comment]
I've tried with multiple domains I got the above error. After I've changed it to a single domain then It worked for me.

**Comment by lagden** [comment]
@denispolicarpocampos 

use: `--preferred-challenges http`

**example:**  
`certbot-auto certonly --standalone -d your.domain.com --preferred-challenges http`

the port 80 must be open and released to do this

**Comment by schoen** [comment]
I believe that the error message originally reported by Certbot in this case was accurate. Also, @lagden's workaround is now the default behavior in newer versions of Certbot.

If anyone happens across this particular issue in the future, please ask questions about this kind of topic over on the Let's Encrypt Forum

https://community.letsencrypt.org/

You'll get much better debugging assistance over there!
