### ISSUE TITLE
https://www.generalopinion.org/---An unsafe message appears

### ISSUE THREAD

**Issue by samiwo123** [certbot/certbot#5043]
IMPORTANT NOTES:
 - An error occurred and we failed to restore your config and restart
   your server. Please submit a bug report to
   https://github.com/letsencrypt/letsencrypt
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/generalopinion.org/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/generalopinion.org/privkey.pem
   Your cert will expire on 2017-11-20. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot-auto
   again with the "certonly" option. To non-interactively renew *all*
   of your certificates, run "certbot-auto renew"

**Comment by strugee** [comment]
@samiwo123 you need to edit your issue and fill out the issue template. Without this information, no one can help you or find the bug you're hitting.

**Comment by SwartzCr** [comment]
So it looks like you're serving a certificate for example.com on your server. Based on the message in the error output from certbot it seems that it was able to fetch you a certificate but not install it for you.
What webserver are you using?
You can add a reference to that certificate in your VirtualHost file and everything should work fine (including future renewals)
The key and certificate files live at `/etc/letsencrypt/live`
If you need help figuring out what you need to add to those files feel free to ask here

**Comment by samiwo123** [comment]
thank you.
Use Wordpress supported by BitNami.
-
Computer Engineering

**Comment by samiwo123** [comment]
Succeeded the first time.
But there was a fatal error on the site.
And when trying again the problems started

**Comment by samiwo123** [comment]
thank you.
Really succeeded.
After you try.
I will warn you not to speak English well.
German

**Comment by SwartzCr** [comment]
Ok, es ist grossartig das es funktioniert.  Ich schlesse dieses Issue jetzt.  Wenn sie neue Problemen siehst, bitte einen neuen Issue machen.
