### ISSUE TITLE
Renewal docs don't mention dry run

### ISSUE THREAD

**Issue by SwartzCr** [certbot/certbot#5044]
I'm working on a issue #5041 and noticed that our documentation doesn't mention dry-run at all except for in the --help output, yet we suggest everyone run it in the installation instructions. This seems wrong. We should add a blurb to the renewal portion of the docs explaining what it does.
@pconrad-fb want to take a crack at this?

**Comment by pconrad-fb** [comment]
Cool. As usual, Thursday is a good day for me to clear some time to work on it. I'll take a look.

**Comment by SwartzCr** [comment]
Awesome! Keep me posted
