### ISSUE TITLE
Show expiration and renew dates in certbot renew output

### ISSUE THREAD

**Issue by jkufner** [certbot/certbot#5045]
When running `certbot renew` it shows following info (paths truncated):

`````
The following certs are not due for renewal yet:
  /etc/letsencrypt/live/.../fullchain.pem (skipped)
  /etc/letsencrypt/live/.../fullchain.pem (skipped)
  /etc/letsencrypt/live/.../fullchain.pem (skipped)
No renewals were attempted.
`````

It would be muchmore useful if it said when the certificates are going to expire and when they are due to renewal. For example:

`````
The following certs are not due for renewal yet:
  /etc/letsencrypt/live/.../fullchain.pem (skipped; exp. 2017-12-01, renew 2017-11-01)
  /etc/letsencrypt/live/.../fullchain.pem (skipped; exp. 2017-12-05, renew 2017-11-05)
  /etc/letsencrypt/live/.../fullchain.pem (skipped; exp. 2017-11-01, renew 2017-10-01)
No renewals were attempted.
`````

**Comment by SwartzCr** [comment]
Interesting!
That would be useful, let me add it to the wishlist milestone, but mark it as a bite sized task that someone could work on. Maybe @ynasser would want to tackle this when she does her livestream?

**Comment by ynasser** [comment]
Yes, this would be a great issue to implement in the livestream. Thanks @SwartzCr!

**Comment by ppKrauss** [comment]
Hi,  #5065 is perhaps a variant... But about user needs, is not only dates, but a clue about "What Do I Do Now??" 

`certbot`  stop to work (!) and no clue about how to workaround or redo something.

**Comment by ynasser** [comment]
@ppKrauss When I implement this, I'll try to make it more clear in the user interface how users should use the dates we provide them with, that way they'll understand how to use the data we're giving them. So, instead of just saying `Cert not yet due for renewal`, it'll say something like, `Cert not yet due for renewal yet. See recommended renewal dates listed above. For documentation, see: https://certbot.eff.org/docs/using.html#renewing-certificates`.

**Comment by jkufner** [comment]
@ynasser That is awful lot of words. Keep it short.

**Comment by SwartzCr** [comment]
@jkufner do you have a recommendation for a potential wording?

**Comment by SwartzCr** [comment]
@jkufner do you have a proposed wording?

**Comment by jkufner** [comment]
@SwartzCr See the first comment ;-)

**Comment by SwartzCr** [comment]
I think @ynasser's suggestion is for the preceding text, and it will also include your suggestion of adding dates, making it look something like:
```
The following certs are not due for renewal yet. See recommended renewal dates listed below. For documentation, see: https://certbot.eff.org/docs/using.html#renewing-certificates:
  /etc/letsencrypt/live/.../fullchain.pem (skipped; exp. 2017-12-01, renew 2017-11-01)
  /etc/letsencrypt/live/.../fullchain.pem (skipped; exp. 2017-12-05, renew 2017-11-05)
  /etc/letsencrypt/live/.../fullchain.pem (skipped; exp. 2017-11-01, renew 2017-10-01)
No renewals were attempted.
```
I think this wording is good, it's a little long, but not obtrusively so, and links to our documentation.

**Comment by ppKrauss** [comment]
Hi @ynasser  thanks for your efforts on implementation (!).  About message, this log of dates say nothing to a "dummy user", the user need a clue like **"try comand X  and read document Y"**.

**Comment by SwartzCr** [comment]
I've taken a first stab at this in pr #5259
