### ISSUE TITLE
Problem with certbot dependency

### ISSUE THREAD

**Issue by cosmonova** [certbot/certbot#5046]
## My operating system is (include version):
Ubuntu 14

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt-get

## I ran this command and it produced this output:
certbot renew

VersionConflict: (acme 0.17.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('acme==0.14.1'))

## Certbot's behavior differed from what I expected because:
I managed to install the certificates previously using certbot

**Comment by SwartzCr** [comment]
Hi!
How did you previously install certbot? Was it via certbot-auto or did you previously use pip to install it?
It seems like the version that is packaged for you is older than the version currently on your system. You'll likely have to completely uninstall the version that's currently there to be able to install the proper dependencies for the packaged version.

**Comment by cosmonova** [comment]
Hi,

I install it via apt-get and I tried to remove it but no luck. However it worked to renew the certificates using certbot-auto.

**Comment by SwartzCr** [comment]
Okay! Should we close this issue, or would you like us to help you get the packaged version?

**Comment by cosmonova** [comment]
I think we can close this.
