### ISSUE TITLE
Error with Apache Plugin.  Error parsing file (default-ssl.conf.save)

### ISSUE THREAD

**Issue by calciosf** [certbot/certbot#5049]
Having issues with running Certbot on standard DigitalOcean Wordpress droplet.  Followed steps but am hitting an error which is preventing me from finishing.

## I ran this command and it produced this output:
certbot --apache -d my domain.com -d www.mydomain.com

## Certbot's behavior differed from what I expected because:
PluginError "There has been an error in parsing the file /etc/apache2/sites-available/default-ssl.conf.save on line 118: Syntax error. 

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

certbot.plugins.selection:No candidate plugin
certbot.plugins.selection:selected authenticator None and installer None

**Comment by SwartzCr** [comment]
That's a shame.
Certbot runs a check to see if apache is properly configured before using it. It seems that this syntax error is preventing it from selecting apache. Can you share what is on line 118?

**Comment by SwartzCr** [comment]
@calciosf have you been able to resolve this issue? Have you managed to get a certificate?

**Comment by calciosf** [comment]
No, I grew frustrated and dropped setting up SSL for this site.  I was not able to solve the issue and finally moved on to other projects which had priority.  I intended to return to this at sometime in the future, but I have been too busy.

**Comment by SwartzCr** [comment]
Okay, let us know when you return it it, and feel free to ping @joohoi if you continue to run into issues with apache parsing

**Comment by joohoi** [comment]
This was actually fixed in #4104 so the fix will be included in the release 0.19 of certbot-apache. Closing the issue for now, feel free to continue discussion here, if you still encounter the issue after the release.

**Comment by calciosf** [comment]
When will 0.19 be released?

**Comment by SwartzCr** [comment]
Releases happen at the beginning of the month, so likely the first week of October
