### ISSUE TITLE
Make rollback respect --nginx cli flag.

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#5056]
It currently ignores the `--nginx` flag. It might also ignore `--apache`, or other forms of choosing the plugin.

We should also make sure that this all works as expected given the method we used to unhide Nginx.

**Comment by ohemorange** [comment]
See https://community.letsencrypt.org/t/rollback-on-certificate-created-with-test-cert/40369/13 for some background on how this was discovered.

**Comment by bmw** [comment]
I think this is a duplicate of #4858. The solution right now is to use `--installer nginx`.

**Comment by ohemorange** [comment]
Agreed, closing.
