### ISSUE TITLE
HOW TO REVOKE THE CERT AND RECREATE A NEW ONE

### ISSUE THREAD

**Issue by FreshCodeMan** [certbot/certbot#5059]
## I ran this command and it produced this output: certbot-auto --nginx
The following errors were reported by the server:
```
   Domain: wechat.cfpu.com
   Type:   unauthorized
   Detail: Incorrect validation certificate for tls-sni-01 challenge.
   Requested
   1979d3b313013726063083acd526f7b2.148a574b2da0b859dd61beb07854d2b2.acme.invalid
   from *.*.*.*(hidden):443. Received 2 certificate(s), first certificate
   had names "test.cfpu.com"
```
Thanks for providing such a nice tool,it makes me can use SSL easily.
I got a problem here:
I applied a cert for my test server(i only have one physical server), its domain is "test.cfpu.com",and it worked well,after that,i wanted to change the server's domain to "wechat.cfpu.com", this is the formal domain, so i change the domain resolution to "wechat.cfpu.com" and i executed the command "certbot revoke --cert-path /etc/letsencrypt/live/mycert/cert.pem" and "certbot delete ......" after all this,it still told me the message above.so what can i do now to solve this problem?

**Comment by SwartzCr** [comment]
Hi!
Did you literally write `/etc/letsencrypt/live/mycert/cert.pem` or did you write `/etc/letsencrypt/live/test.cfpu.com/test.cfpu.com.pem`? additionally you should see 4 files in that `/live/` directory, and you should only need to refer to it by the name `test.cfpu.com`
You also shouldn't need to delete one cert to make another.
I would edit your server's configuration file to stop serving `test.cfpu.com` and just ask for the `wechat.cfpu.com` cert and it should be okay without having to delete the old one.
What server do you use?

**Comment by FreshCodeMan** [comment]
@SwartzCr thanks for your reply, i did write `/etc/letsencrypt/live/test.cfpu.com/test.cfpu.com.pem` and my server is tomcat and Nginx proxy pass,now it works very well,thanks for your helping!
