### ISSUE TITLE
would letsencrypt support j2ee servers like tomcat?

### ISSUE THREAD

**Issue by xiasenhai** [certbot/certbot#506]
letsencrypt is really a great tool. but now seems that it cannot be installed to `j2ee servers` like `tomcat/websphere/glassfish`. would letsencrypt support these servers later? i think this `should on the roadmap` right?

**Comment by schoen** [comment]
Right now you could get a certificate using the standalone mode and then manually install it in the server (which should still be more convenient, in many cases, than other existing options for obtaining certificates).

We would welcome contributions of code to integrate more smoothly and automatically with these servers. There is a plugin API to allow extending the client to work with a wider range of software (currently used for Apache, nginx, and standalone mode).

**Comment by alejandrodavila** [comment]
Is it really working for Glassfish?
If i get .pem certificates and convert to der, then import to glassfish is not working

**Comment by digulla** [comment]
This is related to issue #1701

For all Java servers, the client has to export the certificate in DER format (whatever that is). The next step is then to create a new key store or to import the key into an existing key store.

For details, see https://stackoverflow.com/questions/2138940/import-pem-into-java-key-store

**Comment by xjiaoyang** [comment]
@digulla i will try this later!

**Comment by jimdowling** [comment]
Please report back if it works.

**Comment by melo0187** [comment]
I can confirm that this works with Tomcat 7!

I got LE cert for my NAS and then manually imported them into a JKS which can be provided to Tomcat 7 to also use the cert.

It is not all straight forward because you can't simply create a JKS from existing pem files, but need to create a p12 keystore and import that into a JKS instead...
I described the steps here:
https://melo.myds.me/wordpress/lets-encrypt-for-tomcat-7-on-ds/

**Comment by xjiaoyang** [comment]
@melo0187 :+1:

**Comment by ebourg** [comment]
@melo0187 Tomcat accepts PKCS12 keystores, you can skip the PKCS12->JKS conversion.

**Comment by melo0187** [comment]
@ebourg Thank you very much for letting me know! The next certificate renewal is approaching I will definitely try to use the PKCS12 keystore in Tomcat saving me the conversion step =)

**Comment by qidaneix** [comment]
题主是中国小伙伴不？找到解决办法了不？

**Comment by darckyn** [comment]
It will be awesome to have a plugin that makes automatic conversion java server with automatic certificate renewal, we are not going to worry about certificates on java servers anymore.

This is not only good for tomcat but for all Java servers like glassfish, wildfly, jetty etc.

Please make it happen :)

**Comment by ebourg** [comment]
FYI Tomcat now even accepts PEM certificates, so no conversion is required anyone, just moving/chmoding the certificates and restarting the Tomcat connector. This would be easier to implement with #3147.

**Comment by edwardotis** [comment]
Hi @ebourg ,   it sounds like you have figured out a simpler solution than the ones above. Would you be able to provide the  steps required for a letsencrypt newbie to perform this on a tomcat 8 install with certbot? I'd be interested in adding my own cron job script to do this while we wait on the official certbot update.

**Comment by edwardotis** [comment]
Or perhaps this is what I'm looking for?
https://mladenadamovic.wordpress.com/2016/09/06/configure-tomcat-with-ssl-on-ubuntu-minimal/

**Comment by ebourg** [comment]
@edwardotis Yes that's an example of using Tomcat with a PEM certificate (however on Debian/Ubuntu I'd rather use the tomcat8 package provided by the distribution).

**Comment by edwardotis** [comment]
gotcha, thanks, @ebourg

**Comment by ernitishkumar** [comment]
How to do all these on windows 10 or on any windows machine running tomcat 7 ??

Hope to see a response

**Comment by hgasimov** [comment]
One more example with Tomcat + PEM certificate https://gasimof.com/install-free-ssl-certificate-for-tomcat/

**Comment by ebourg** [comment]
@hgasimov This example won't work on Debian/Ubuntu with the tomcat8 ant certbot packages. `/etc/letsencrypt/live` isn't world readable and Tomcat doesn't run as root. Also Tomcat isn't restarted automatically on renewals.

**Comment by StrangeNoises** [comment]
Just making the observation that the posts above saying how to use Tomcat with PEM certificates don't make it immediately obvious that this works by using the APR library in Tomcat, which basically offloads the work to the native OpenSSL library. So you need a good OpenSSL in the environment for that to work, and in this fallen world of ours that isn't always possible. To use the fully native-java JSSE implementation you do still definitely need to convert the certs into a keystore, though it can be, interchangeably, a PKCS12 or JKS keystore these days.

**Comment by ebourg** [comment]
@StrangeNoises Since Tomcat 8.5.1 you can also use the PEM certificates directly with the NIO/NIO2 connectors. You no longer have to put the certificates in a PKCS12/JKS keystore.

**Comment by StrangeNoises** [comment]
Only if it's using an OpenSSL implementation, ie `sslImplementationName="org.apache.tomcat.util.net.openssl.OpenSSLImplementation"`, which may be selected implicitly if the APR library and a good enough OpenSSL library are available. If `sslImplementationName="org.apache.tomcat.util.net.jsse.JSSEImplementation"` you can't.

NB: I'm looking at the Tomcat 9.0.20 docs, as that's what I'm using, but I expect this part is the same. The docs are written a bit clumsily IMHO but essentially you can only use the OpenSSL options if you're using an OpenSSL implementation, either via the Http11AprProtocol or via either of the Http11Nio[2]Protocols if using the OpenSSL implementation.

**Comment by ebourg** [comment]
@StrangeNoises Tomcat also supports PEM certificates with the JSSE implementation (since Tomcat 8.0.34, 8.5.1 and 9.0.0.M5)
