### ISSUE TITLE
Improve renewal hook documentation

### ISSUE THREAD

**Issue by SwartzCr** [certbot/certbot#5066]
The documentation for renewal hooks is very bad. Considering how complicated these hooks are it is important that the documentation for them is clear.
Related issues are: 
#2364 about how to run separate pre/post hooks for different renewals
#4561 lack of a single --help output for hooks
#4564 lack of cohesive tutorial for using hooks
#4534 documentation doesn't mention how command line arguments persist
#4323 unclear that global hooks override per lineage
#4103 unclear that renew-hook isn't run on first issuance
#3147 we need to support hook scripts directories
https://github.com/certbot/certbot/issues/5935 when are directory hooks run
Additionally at various times we say that pre and post hooks are per lineage, but we also say they're sometimes global, and we don't suggest a way to specify hooks for only one lineage

**Comment by SwartzCr** [comment]
@bmw would you be willing to chat with peter about hooks?

**Comment by bmw** [comment]
Sure, but I'm going to be pretty busy until the latter half of next week. Would next Thursday work for you?

**Comment by pconrad-fb** [comment]
Almost all Thursdays are good for me, except for a standing meeting that is usually at 10:30 (but sometimes moves).

**Comment by bmw** [comment]
@schoen are you still interested in working on this, maybe with help from @pconrad-fb?

**Comment by pconrad-fb** [comment]
I would love to help with this.

**Comment by AJRepo** [comment]
I've created a certbot deploy hook script that sends emails with the known deploy hook variables. I've been using it for 
both regular and wildcard certificates (e.g. *.example.org). Hopefully this is helpful https://github.com/AJRepo/certbot_haproxy/blob/master/50_haproxy_deploy.sh for those wanting to see a deploy hook script.
