### ISSUE TITLE
list accounts issued/renewed on `certbot certificates`

### ISSUE THREAD

**Issue by jvanasco** [certbot/certbot#5071]
The current output is:

	Certificate Name: xxxxxxx
		Domains: yyyyyy
		Expiry Date: zzzzz
		Certificate Path: aaaaaa
		Private Key Path: bbbbbb

It would be nice if this was augmented with the renewal and/or issuing account info:

	Certificate Name: xxxxxxx
		Domains: yyyyyy
		Expiry Date: zzzzz
		Certificate Path: aaaaaa
		Private Key Path: bbbbbb
  		Account Issued: md5
  		Account Renewal (configurable): md5

The renewal account is tracked in `/etc/letsencrypt/renewal/{certificate-name}`

I'm not sure if the issuing account is tracked outside of the log.

why?

Maintenance. it would be nice to keep the list of accounts clean and only with active/necessary ones.  The renewal account lets us know what accounts are needed for renewal.  The issuing account lets us know what accounts are needed for revocation.

**Comment by SwartzCr** [comment]
@bmw want to add this to a milestone?

**Comment by jvanasco** [comment]
This information is still not easily accessible in `certbot==0.35.0`.
