### ISSUE TITLE
certbot standalone renewal with a VPN tunnel

### ISSUE THREAD

**Issue by jjssoftware** [certbot/certbot#5072]
I was trying to renew a cert for one of my servers:

`./certbot certonly --standalone -d <my-domain-here>`

..and I kept seeing a failure that looked like this:

```
certbot urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout

To fix these errors, please make sure that your domain name was entered correctly and the DNSA/
AAAA record(s) for that domain contain(s) the right IP address.
Additionally, please check that your computer has a publicly routable IP address and that no firewalls are preventing the server from communicating with the client.
If you're using the webroot plugin, you should also verify that you are serving files from the webroot path you provided.
```

At first I found this error a bit odd but then it occurred to me that I had a VPN up on the box where I was issuing the `./certbot` renewal request and I didn't when I originally created the cert some time ago. At this point the error made sense (it being related to my IP address not being recognized by the remote challenge response server), I dropped the VPN, re-attempted the renewal and it worked without an issue.

My question is: is it possible to make renewal work without having to drop the VPN tunnel?

Thanks!

**Comment by SwartzCr** [comment]
I feel like this is a question that @jsha or @cpu would be better at answering than I would, any ideas?

**Comment by jsha** [comment]
Without more details about your VPN setup, I can't really say, but most likely not. If you'd like to post on https://community.letsencrypt.org/ with more details of your setup, people may be able to help you brainstorm a solution there.

**Comment by bmw** [comment]
I agree with jsha that https://community.letsencrypt.org/ is the place for questions like this so I'm closing this issue.
