### ISSUE TITLE
Unable to create ssl while depolying application on google cloud

### ISSUE THREAD

**Issue by gauravkhrnr** [certbot/certbot#5073]
**My Operating system windows 10**

**bug report**
Unable to create ssl while depolying application on google cloud .we are getting below error
DNS problem: SERVFAIL looking up A for crypcash.com

 **I ran "certbot certonly --standalone -d example.com -d crypcash.com" command and it produced the below output:**
![certerror](https://user-images.githubusercontent.com/20242899/30047624-d4be4acc-922f-11e7-80f9-5f33f4d0f815.png)

**Comment by SwartzCr** [comment]
It seems like you have one of two possible problems.
Either your website isn't properly being served (can you reach the site normally? I can't seem to get it to load)
Or you have an overly broad listen in one of your VirtualHost files, in this case it seems to be serving a lot of example certificates. Removing those directives should help.

**Comment by SwartzCr** [comment]
@gauravkhrnr have you had any success with getting a certificate? Have you gotten past this issue?
