### ISSUE TITLE
Feature request: support for FreeIPA DNS

### ISSUE THREAD

**Issue by cjeanneret** [certbot/certbot#5074]
Dear certbot team,

It would be really cool if certbot could talk to freeIPA DNS service in order to validate a domain.

Lemme explain the usecase:
We're managing a public DNS zone with a FreeIPA cluster, and are wanting to set up Let's Encrypt certificates for some services. We can't rely on the "http" validation, because the application is running on a cluster (if I say "openstack horizon on three controllers"…).

Thus, the best way to get the certificate would be to do a DNS validation, meaning certbot must be able to talk to our freeIPA.

Of course, we might as well use the "manual" way, providing a --manual-auth-hook script doing the API calls against freeIPA, but… I can't think we're the only one in that case. Are we?

Thank you in advance for your support, and a big :+1: to the certbot project :).

Cheers,

C.

**Comment by SwartzCr** [comment]
Do you know if freeIPA provides an API with which you can automatically make edits to your DNS records?
While I don't think we have immediate plans to add more DNS plugins, we'd always be happy to accept PRs for new ones, so long as it's possible.
Additionally you can likely manage the DNS validation challenge with a script, even if there's no plugin for it.

**Comment by cjeanneret** [comment]
Hello @SwartzCr 

Yep, FreeIPA has a JSON-RPC API for all the things it can manage, among them the DNS part. There are also the "ipa" CLI command which is the best way to do the things, as it can do the authentication part automatically using a keytab (kerberos authentication).

If I find the time to create a script for that purpose, I suppose it might be used as base for a possible plugin?

Cheers,

C.

**Comment by SwartzCr** [comment]
Yes, let us know. You can look at the code for the other plugins here as inspiration, for example here is the cloudflare code: https://github.com/certbot/certbot/blob/master/certbot-dns-cloudflare/certbot_dns_cloudflare/dns_cloudflare.py
