### ISSUE TITLE
Does not execute multiple command line --renew-hook

### ISSUE THREAD

**Issue by zylongaming1** [certbot/certbot#5076]
## My operating system is (include version):
Arch Linux (4.11.6-1-ARCH)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Pacman (Certbot version certbot 0.15.0)

## I ran this command and it produced this output:
Created a timer which runs once daily to check for renewal for my certs.  It worked fine, however a bug with running multiple renew hooks post renewal of certificates.

## Certbot's behavior differed from what I expected because:
It did not run all 3 hooks after renewing the certs.  It only seems to run the last one given in the arguments (If I am doing this wrong, then sorry for wasting your time.  I haven't been able to get it to work yet and I read here that it is possible: https://stackoverflow.com/a/42433109

## This is my service that is ran once the timer is fired.
[Unit]
Description=Let's Encrypt renewal

[Service]
Type=oneshot
ExecStart=/usr/bin/certbot renew --agree-tos --renew-hook "systemctl reload nginx.service" --renew-hook "systemctl restart vsftpd.service" --renew-hook "systemctl reload postfix.service" --renew-hook "systemctl reload dovecot.service"

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
Aug 23 00:41:35 redacted systemd[1]: Starting Let's Encrypt renewal...
Aug 23 00:41:42 redacted certbot[30507]: Saving debug log to /var/log/letsencrypt/letsencrypt.log
Aug 23 00:41:42 redacted certbot[30507]: Cert is due for renewal, auto-renewing...
Aug 23 00:41:42 redacted certbot[30507]: Renewing an existing certificate
Aug 23 00:41:44 redacted certbot[30507]: Performing the following challenges:
Aug 23 00:41:44 redacted certbot[30507]: http-01 challenge for redacted
Aug 23 00:41:44 redacted certbot[30507]: http-01 challenge for redacted
Aug 23 00:41:44 redacted certbot[30507]: http-01 challenge for redacted
Aug 23 00:41:44 redacted certbot[30507]: http-01 challenge for redacted
Aug 23 00:41:44 redacted certbot[30507]: http-01 challenge for redacted
Aug 23 00:41:44 redacted certbot[30507]: http-01 challenge for redacted
Aug 23 00:41:44 redacted certbot[30507]: http-01 challenge for redacted
Aug 23 00:41:44 redacted certbot[30507]: http-01 challenge for redacted
Aug 23 00:41:44 redacted certbot[30507]: http-01 challenge for redacted
Aug 23 00:41:44 redacted certbot[30507]: http-01 challenge for redacted
Aug 23 00:41:44 redacted certbot[30507]: http-01 challenge for redacted
Aug 23 00:41:44 redacted certbot[30507]: http-01 challenge for redacted
Aug 23 00:41:44 redacted certbot[30507]: http-01 challenge for redacted
Aug 23 00:41:44 redacted certbot[30507]: http-01 challenge for redacted
Aug 23 00:41:44 redacted certbot[30507]: Waiting for verification...
Aug 23 00:41:49 redacted certbot[30507]: Cleaning up challenges
Aug 23 00:41:51 redacted certbot[30507]: Running renew-hook command: systemctl reload dovecot.service
Aug 23 00:41:52 redacted certbot[30507]: Cert is due for renewal, auto-renewing...
Aug 23 00:41:52 redacted certbot[30507]: Renewing an existing certificate
Aug 23 00:41:53 redacted certbot[30507]: Performing the following challenges:
Aug 23 00:41:53 redacted certbot[30507]: http-01 challenge for redacted
Aug 23 00:41:53 redacted certbot[30507]: http-01 challenge for redacted
Aug 23 00:41:53 redacted certbot[30507]: Waiting for verification...
Aug 23 00:41:56 redacted certbot[30507]: Cleaning up challenges
Aug 23 00:41:58 redacted certbot[30507]: Running renew-hook command: systemctl reload dovecot.service
Aug 23 00:41:58 redacted certbot[30507]: Cert is due for renewal, auto-renewing...
Aug 23 00:41:59 redacted certbot[30507]: Renewing an existing certificate
Aug 23 00:41:59 redacted certbot[30507]: Performing the following challenges:
Aug 23 00:41:59 redacted certbot[30507]: http-01 challenge for redacted
Aug 23 00:41:59 redacted certbot[30507]: http-01 challenge for redacted
Aug 23 00:41:59 redacted certbot[30507]: http-01 challenge for redacted
Aug 23 00:41:59 redacted certbot[30507]: Waiting for verification...
Aug 23 00:42:03 redacted certbot[30507]: Cleaning up challenges
Aug 23 00:42:05 redacted certbot[30507]: Running renew-hook command: systemctl reload dovecot.service
Aug 23 00:42:05 redacted certbot[30507]: -------------------------------------------------------------------------------
Aug 23 00:42:05 redacted certbot[30507]: Processing /etc/letsencrypt/renewal/redacted.conf
Aug 23 00:42:05 redacted certbot[30507]: -------------------------------------------------------------------------------
Aug 23 00:42:05 redacted certbot[30507]: new certificate deployed without reload, fullchain is
Aug 23 00:42:05 redacted certbot[30507]: /etc/letsencrypt/live/redacted/fullchain.pem
Aug 23 00:42:05 redacted certbot[30507]: -------------------------------------------------------------------------------
Aug 23 00:42:05 redacted certbot[30507]: Processing /etc/letsencrypt/renewal/redacted.conf
Aug 23 00:42:05 redacted certbot[30507]: -------------------------------------------------------------------------------
Aug 23 00:42:05 redacted certbot[30507]: new certificate deployed without reload, fullchain is
Aug 23 00:42:05 redacted certbot[30507]: /etc/letsencrypt/live/redacted/fullchain.pem
Aug 23 00:42:05 redacted certbot[30507]: -------------------------------------------------------------------------------
Aug 23 00:42:05 redacted certbot[30507]: Processing /etc/letsencrypt/renewal/redacted.conf
Aug 23 00:42:05 redacted certbot[30507]: -------------------------------------------------------------------------------
Aug 23 00:42:05 redacted certbot[30507]: new certificate deployed without reload, fullchain is
Aug 23 00:42:05 redacted certbot[30507]: /etc/letsencrypt/live/redacted/fullchain.pem
Aug 23 00:42:05 redacted certbot[30507]: -------------------------------------------------------------------------------
Aug 23 00:42:05 redacted certbot[30507]: Congratulations, all renewals succeeded. The following certs have been renewed:
Aug 23 00:42:05 redacted certbot[30507]:   /etc/letsencrypt/live/redacted/fullchain.pem (success)
Aug 23 00:42:05 redacted certbot[30507]:   /etc/letsencrypt/live/redacted/fullchain.pem (success)
Aug 23 00:42:05 redacted certbot[30507]:   /etc/letsencrypt/live/redacted/fullchain.pem (success)
Aug 23 00:42:05 redacted systemd[1]: Started Let's Encrypt renewal.

**Comment by SwartzCr** [comment]
I believe you are only able to store one renew hook per certificate configuration file.
I think in your case you should combine them all into one bash command like `service postfix reload && service dovecot restart && service apache2 reload`
Let me know if that works for you.
We're working on updating our renewal documentation in #5067 so maybe this should also be clarified there.

**Comment by IvanAnishchuk** [comment]
It actually would make sense to allow multiple commands. Note that `&&` combination would produce unexpected results if one of them failed. Actually semicolon `;` combination can do something very unexpected as well and it won't even return you a proper exit status. And in both cases you'd have a hard time figuring out which of the command fails while multiple hook parameters can be debugged and fixed very easily (certbot can print failed command in the log and that's it).

Also I'm generally strongly opposed to relying on shell in such matters.

**Comment by Pascal666** [comment]
Systemctl itself can take multiple services.  So until certbot is fixed, you could use:
`systemctl restart nginx vsftpd postfix dovecot`

**Comment by SwartzCr** [comment]
I believe this is now fixed by the new renewal hook directories which can hold a number of hooks, and run each hook script pre/post/or on deploy of a certificate renewal: https://certbot.eff.org/docs/using.html#renewing-certificates
I'm going to close this as resolved, but please feel free to comment if you think there are still things you're unable to achieve.

**Comment by mallikharjunakambampati** [comment]
@SwartzCr can you please let us know how can we use these post and pre hooks directories ?
we need to use two commands to start the services here, we are using below command through cron but it is not working properly any help on this ?

30 3 * * * certbot renew --pre-hook  'sudo service nginx stop,sudo service openvpnas stop'  --post-hook 'sudo service nginx start,sudo service openvpnas start'

**Comment by mallikharjunakambampati** [comment]
how do we need to add the commands to pre and post hooks folders to consider while we running cerbot renew commands?

**Comment by raforg** [comment]
That's unfortunate. It seems like such a simple thing to support. If it's not going to be supported, it would be good to clearly document the fact that each hook command line option may only be used once (both in the command line documentation and in the config file documentation). It might save many users time and bother.

There are instructions on the internet written by someone who clearly thinks that all of their deploy hooks are being executed. That alone is reason enough to support it. People are actively assuming that it works. Please follow the principle of least astonishment.

The alternative of putting scripts in the renewal-hooks directory isn't an ideal substitute, because if you have multiple certificates, and only one that requires multiple deploy hooks for one of them, you need to write a script in /etc/letsencrypt/renewal-hooks/deploy that requires additional certbot-specific code just to ensure that it only does its thing for the correct domain and not for any of the others (e.g. certificates for many websites but only one of them being used for mail servers). Being able to just associate multiple hooks with the domain in question is more efficient for the system administrator and for the computer.

Supporting domain-specific subdirectories under the renewal-hooks/{deploy,pre,post} directories would be satisfactory (but documenting whether the hook command line options can be used only once or multiple times would still be needed).

**Comment by lordspace** [comment]
@raforg yep. I have seen tutorials too that give that as an example and have many servers not reload their updated SSLs. I didn't wait and created a separate script to handle this
