### ISSUE TITLE
Detect and handle ManagedDomain directive

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#5079]
The [mod_md Apache module](https://github.com/icing/mod_md/) will add native ACME support to Apache. I think Certbot should probably look for the main directive `ManagedDomain` and not try to autoconfigure Apache when that's present. Otherwise I think the results are likely to get complicated and hard to support.

**Comment by bmw** [comment]
Let's keep an eye on this as `mod_md` becomes packaged and shipped by different distros.
