### ISSUE TITLE
OSError: ctypes.util.find_library() did not manage to locate a library called 'augeas'

### ISSUE THREAD

**Issue by alyssais** [certbot/certbot#5084]
I'm a Homebrew maintainer, and we've noticed certbot won't build any more.

We need a way to tell the build process where to find augeas. (See https://github.com/Homebrew/homebrew-core/issues/16757#issuecomment-327772596.) Our only alternative at the moment seems to be to do some [hacky string replacement](https://github.com/Homebrew/homebrew-core/issues/16757#issuecomment-322445469), which isn't good for anyone.

***

## My operating system is (include version):

macOS Sierra

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Homebrew

## I ran this command and it produced this output:

<dl>
<dt><kbd>brew install --build-from-source certbot</kbd></dt>
<dd><blockquote><pre>OSError: ctypes.util.find_library() did not manage to locate a library called 'augeas'</pre></blockquote></dd>
</dl>

## Certbot's behavior differed from what I expected because:

It didn't compile.

**Comment by bmw** [comment]
Thanks for reporting the issue @alyssais. This problem is from one of our dependencies and I've reported the problem to them at hercules-team/python-augeas#32 along with what a suggestion for what I think would be a viable solution.

Sorry for the trouble and let me know if there's anything else I can do to help! We can leave this issue open until the problem is resolved.

**Comment by taikedz** [comment]
Any progress on this?

I'm encountering the same issue in a docker container based on `ubuntu:xenial`, installing via `pip`

Current workaround is to use the PPA `ppa:certbot/certbot` to install `python-certbot-apache`. Is this now the recommended way to install the apache-compatible module?

Output of installing `certbot-apache` from pip:

```bash
# pip install certbot-apache
Collecting certbot-apache
  Downloading certbot_apache-0.19.0-py2.py3-none-any.whl (141kB)
    100% |################################| 143kB 660kB/s 
Requirement already satisfied: zope.interface in /usr/local/lib/python2.7/dist-packages (from certbot-apache)
Requirement already satisfied: setuptools>=1.0 in /usr/lib/python2.7/dist-packages (from certbot-apache)
Requirement already satisfied: certbot==0.19.0 in /usr/local/lib/python2.7/dist-packages (from certbot-apache)
Requirement already satisfied: zope.component in /usr/local/lib/python2.7/dist-packages (from certbot-apache)
Requirement already satisfied: acme==0.19.0 in /usr/local/lib/python2.7/dist-packages (from certbot-apache)
Collecting python-augeas (from certbot-apache)
  Downloading python-augeas-1.0.3.tar.gz (92kB)
    100% |################################| 102kB 2.7MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-BYvDW4/python-augeas/setup.py", line 23, in <module>
        url = "http://augeas.net/",
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/local/lib/python2.7/dist-packages/cffi/setuptools_ext.py", line 188, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/usr/local/lib/python2.7/dist-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/usr/local/lib/python2.7/dist-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "augeas/ffi.py", line 42, in <module>
        lib = ffi.dlopen("augeas")
      File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 141, in dlopen
        lib, function_cache = _make_ffi_library(self, name, flags)
      File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 795, in _make_ffi_library
        backendlib = _load_backend_lib(backend, libname, flags)
      File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 790, in _load_backend_lib
        raise OSError(msg)
    OSError: ctypes.util.find_library() did not manage to locate a library called 'augeas'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-BYvDW4/python-augeas/

```

**Comment by bmw** [comment]
> Current workaround is to use the PPA ppa:certbot/certbot to install python-certbot-apache. Is this now the recommended way to install the apache-compatible module?

Yes. See https://certbot.eff.org/#ubuntuxenial-apache.

We do not recommend you install Certbot through `pip` for a number of reasons, but if you still want to do this, I suspect your problem can be resolved by running:
```
apt-get update
apt-get install libaugeas0 augeas-lenses
```

**Comment by alyssais** [comment]
It looks like it already is! However, I'm no longer working on Homebrew, and I just successfully `brew install -s`ed certbot, so I'm going to close this.

**Comment by taikedz** [comment]
That sounds completely unrelated...

Also `vim` should indeed be owned by root, don't simply start changing ownership of system files !

It's more likely that `brew install augeas` was the solution

**Comment by aiya000** [comment]
I couldn't understand, but just it fixed...
(`brew install augeas` doesn't fix it :thinking:)

**Comment by alyssais** [comment]
`/usr/local/<whatever>` is a Homebrew file, not a system file.

**Comment by kaddynator** [comment]
Anyone was able to resolve this error ? I am using a Windows 10 OS. I am also getting the same error. 

my file name is "libbcAPI.so"


OSError: cannot load library 'libbcAPI.so': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libbcAPI.so'
