### ISSUE TITLE
VersionConflict error message should provide more detail

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#5092]
Steps to reproduce:

Install certbot and certbot-nginx OS packages on Ubuntu. Currently this gets you version 0.17.0.
`pip install certbot-dns-route53` Currently this gets you version 0.18.0.
`certbot -q renew`

Output:

```
An unexpected error occurred:
VersionConflict: (certbot 0.17.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('certbot==0.18.0'))
Please see the logfile '/tmp/tmpnrNdZI' for more details.
```

/tmp/tmpnrNdZI:
```
2017-09-08 18:51:59,525:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.17.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 733, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/disco.py", line 203, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/disco.py", line 50, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2340, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2363, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (certbot 0.17.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('certbot==0.18.0'))
```

Ideally this should provide more detailed help, like "This can result from having Certbot plugins installed that require a different version of Certbot than you are running, or generally from having some Certbot-related packages installed by your OS package manager, and some installed using `pip`. Try either uninstalling your OS-packaged certbot packages, or uninstalling your pip-packaged certbot packages."

**Comment by SwartzCr** [comment]
What do you think @bmw?
I'm happy to expand the error string, but we do try very hard to prevent people from installing via pip.

**Comment by jsha** [comment]
Note that it's probably also possible to wind up in this situation even without pip. For instance, if you install a plugin not maintained by the Certbot devs, and that plugin pins a specific Certbot version. Then next time you upgrade Certbot, you'll get a VersionConflict in disco.py trying to load that plugin. At the least we could try and name the package that we were trying to load when the exception happened.

**Comment by bmw** [comment]
I'm fine improving the error message as long as it doesn't hide information that would be useful to people familiar with Python's packaging modules. We determine the name of the plugin we're trying to load on the last line of our code before this exception was raised.

**Comment by adferrand** [comment]
@bmw, @jsha? From time to time, we have still reports including this kind of version conflict during plugin discovery. Do you want to move this issue on a milestone?

**Comment by bmw** [comment]
I agree this error message should be improved but I personally don't think it's a high priority. As long as the packages were installed using the same package manager, I think most package managers will recognize this problem (including the one jsha described in his second post) at install time. With that said, some package manager's behavior here isn't great (pip prints a message that your packages now have unsatisfied dependencies, but will happily put you in that scenario where running Certbot causes this error) so we probably should still fix this on our end.

We might also want to try and get it fixed upstream where it'll have the most benefit. This exception is raised by setuptools which is a core Python packaging library and this output is the same if you run an executable from a Python package with unsatisfied dependencies.

I'm moving this to wishlist and adding the "Good first issue" label.

**Comment by jsha** [comment]
I think we should keep this one around.
