### ISSUE TITLE
ImportError: No module named interface from zope.interface

### ISSUE THREAD

**Issue by nikolaevra** [certbot/certbot#5100]
## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

```
wget https://dl.eff.org/certbot-auto
chmod a+x certbot-auto
```

## I ran this command and it produced this output:

ran this command `sudo ./path/to/certbot-auto --nginx`
and it produced 

```
Error: couldn't get currently installed version for /opt/eff.org/certbot/venv/bin/letsencrypt:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/main.py", line 7, in <module>
    import zope.component
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/zope/component/__init__.py", line 16, in <module>
    from zope.interface import Interface
ImportError: No module named interface
```

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

No logs for me:

```
tail -500 /var/log/letsencrypt
tail: cannot open ‘/var/log/letsencrypt’ for reading: No such file or directory
```

**Comment by SwartzCr** [comment]
So we don't currently support Amazon Linux, but it seems like Python is having a hard time installing proper dependencies on it.
I'd recommend looking through old issues on github and seeing if you can find people who have successfully debugged it, but barring that I can't really help until we've been packaged for Amazon.

**Comment by Jlaird** [comment]
Were you able to fix this? I am also having the same error.

**Comment by ming-chu** [comment]
My Env: 
Amazon EC2 instance
Python 2.7.12

I got the following error which similar to yours.
`
$ /opt/eff.org/certbot/venv/local/bin/certbot --help

Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/local/bin/certbot", line 7, in <module>
    from certbot.main import main
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/main.py", line 7, in <module>
    import zope.component
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/zope/component/__init__.py", line 16, in <module>
    from zope.interface import Interface
ImportError: No module named interface
`

**And it works after execute the following commands:**
`
$ unset PYTHON_INSTALL_LAYOUT
$ /opt/eff.org/certbot/venv/local/bin/pip install --upgrade certbot
$ /opt/eff.org/certbot/venv/local/bin/certbot --help

-------------------------------------------------------------------------------

  letsencrypt-auto [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. The most common SUBCOMMANDS and flags are:

obtain, install, and renew certificates:
    (default) run   Obtain & install a certificate in your current webserver
    certonly        Obtain or renew a certificate, but do not install it
    renew           Renew all previously obtained certificates that are near
...
...
`

Hope it can help :)

**Comment by ashsha** [comment]
@ming-chu Thank you!

**Comment by sjberry** [comment]
For whatever it's worth, I referenced this issue recently when renewing certificates on an old AMI. The suggestion from @ming-chu worked for me with v0.19.0 or v0.20.0. I'm guessing it would still work. Didn't find it necessary with v0.21.1 on a fresh AMI as of 2-3 days ago though. Worked right out of the box with whatever changed within certbot or the AMI itself.

**Old:**
AMI Release: 2017.09
Kernel: 4.9.76-3.78.amzn1.x86_64
Python: 2.7.12
Letsencrypt: v0.19.0 or v0.20.0

**New:**
AMI Release: 2017.09
Kernel: 4.9.62-21.56.amzn1.x86_64
Python: 2.7.12
Letsencrypt: v0.21.1

**Comment by SwartzCr** [comment]
Maybe it's time to close this issue then?
@bmw to take over this ticket
