### ISSUE TITLE
--dry-run should prevent authz reuse

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5116]
Some users get themselves into a situation where `--dry-run` works but production does not (see #3231 and #5040). This is due to the user having a valid authorization from staging which is reused, but not from production. This results in people having to use the production server to test their configuration.

We should do something to work around this problem. This probably involves deactivating valid authorizations so the challenge is actually checked by the CA. This requires obtaining the URL of a valid authorization and currently the only way I'm aware of to get the URL of a valid authz from Let's Encrypt that will be reused is to request new authzs for the same domains.

Perhaps we should implement a subcommand that requests a new authz from Let's Encrypt and deactivates it and/or deactivate any valid authorization returned during a `--dry-run` and automatically request a new one.

Related #4945 

cc @jsha, @SwartzCr

**Comment by ohemorange** [comment]
`--staging` is also a good contender for not reusing authzs.

**Comment by jsha** [comment]
> deactivate any valid authorization returned during a --dry-run and automatically request a new one.

This seems like the more straightforward approach, since it doesn't add a command, and should "just work" in most cases.

Any of these interventions have the problem that they make `--dry-run` more dissimilar from prod, though, which means we're likely to see other confusing scenarios crop up as a result.

Would it solve the issue if we reduced the lifetime of valid authzs in staging to a week or a day?

**Comment by bmw** [comment]
I'd still like to see this resolved. I don't think it's uncommon for people to hit authz reuse when using `--dry-run` which can cause problems to not be found until their production cert needs to be renewed.

**Comment by bmw** [comment]
Another example of a user hitting this (and being frustrated by it) is at https://community.letsencrypt.org/t/dry-run-cert-renewal-works-live-cert-renewal-fails-on-400-error/95543.

**Comment by alexzorin** [comment]
I can have a crack at a PR, but my Python is pretty raw so I'll need some help.

For design, the approach that pops out to me is to perform authz deactivation on the tail ends of `obtain_certificate_from_csr` and `obtain_certificate`. All paths that issue seem to come through these two sites.

I would prefer not to deactivate authzs at the start of orders. Once the deactivation behavior is established, doing it at the end of should be all that's needed. Saves on some complexity and wasted/re-created orders.

Any hints appreciated!

**Comment by bmw** [comment]
That would be great @alexzorin! Don't hesitate to ask for help.

That's a pretty clever design.

I am slightly worried about the pathological case where Certbot crashes after performing challenges but before deactivating authorizations allowing a future dry run to still potentially spuriously succeed. No matter what we do in our code, we cannot entirely prevent this from happening if we deactivate authorizations after performing challenges rather than before. With that said, this is a pretty extreme corner case and never throwing away newly created orders is pretty nice so if you still prefer your initial design with this drawback stated explicitly, it works for me.

As a starting point on this issue, I'd first resolve https://github.com/certbot/certbot/issues/4945 in its own PR (as breaking things up into smaller chunks makes getting things reviewed and merged so much easier). I would recommend doing this in [acme.client.ClientBase](https://github.com/certbot/certbot/blob/41a17f913e7d710c584105a4f16cc13d0640b88e/acme/acme/client.py#L47) because authorization deactivation should work the same way on both of Let's Encrypt's endpoints. This should have a simple unit test or two in `acme/acme/client_test.py` to make our tests pass.

After that, we can resolve this issue. If more than a couple lines of code are needed in Certbot, I'd put it in a new function in [certbot.auth_handler.AuthHandler](https://github.com/certbot/certbot/blob/41a17f913e7d710c584105a4f16cc13d0640b88e/certbot/auth_handler.py#L21) since this class is supposed to "handle" authorizations. If we stick with your original design, I'd call that function from [certbot.client.Client.obtain_certificate_from_csr](https://github.com/certbot/certbot/blob/41a17f913e7d710c584105a4f16cc13d0640b88e/certbot/client.py#L271) after calling `finalize_order`. I think if we deactivate authorizations before this point, it will prevent us from downloading the certificate.

Hopefully that helps!

**Comment by ohemorange** [comment]
I'm actually good with all the approaches mentioned here, just wanted to add some thoughts.

> I am slightly worried about the pathological case where Certbot crashes after performing challenges but before deactivating authorizations allowing a future dry run to still potentially spuriously succeed. No matter what we do in our code, we cannot entirely prevent this from happening if we deactivate authorizations after performing challenges rather than before. With that said, this is a pretty extreme corner case and never throwing away newly created orders is pretty nice so if you still prefer your initial design with this drawback stated explicitly, it works for me.

I actually don't mind this not because it's a corner case, but because at worst we fail into what we're already doing.

On another note, another potential drawback of putting it at the end is that the first dry-run for existing users will keep the current behavior. I don't think that's that big of a deal. I also don't think taking more time/doing more work/ creating spurious objects is that big of a deal either.

IMO we shouldn't worry too much about the effects of scale here; the main thing is having behavior that's clear and expected for the user trying to use this for debugging.

**Comment by alexzorin** [comment]
No problem - my main hesitation with it was that it would eventually become a never-executed code path once 30 days since release have elapsed. But doing it both ways would actually guard against Certbot crashing too early, so let's do it.
