### ISSUE TITLE
Openssl show not installed but actually installed (Py-openssl is installed either)

### ISSUE THREAD

**Issue by stevenzhu25** [certbot/certbot#5130]
## My operating system is (include version):
centos-release-7-4.1708.el7.centos.x86_64

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
yum  install certbot

## I ran this command and it produced this output:
all certbot command:

```
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.18.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 9, in <module>
    from acme import jose
  File "/usr/lib/python2.7/site-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/usr/lib/python2.7/site-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/usr/lib/python2.7/site-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
ImportError: No module named OpenSSL

```
## Certbot's behavior differed from what I expected because:
I assure you I got OpenSSL & python-OpenSSL installed, it keeps giving me this output after I upgrade my OpenSSL to mainline version (Via source) and reverted to OpenSSL 1.0.2k-fips  26 Jan 2017 after I saw it doesn't work in OpenSSL 1.1.0f. However, it doesn't work in OpenSSL 1.0.2k too now (used to work)

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
There is no log for me to see as the script didn't run.
## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
It doesn't matter

**Comment by stevenzhu25** [comment]
Show in output:
```
pip list

pyOpenSSL (0.13.1)

```

**Comment by stevenzhu25** [comment]
OpenSSL version 

```
openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017
```

**Comment by SwartzCr** [comment]
I was able to run it just now on a fresh centos box, and have the same versions of both of those.
Is there a way that you could re-install or fix the install of certbot via yum?

**Comment by stevenzhu25** [comment]
Yeah.. I know.The error seems related to :Reinstalled OpenSSLOn Sep 21, 2017 17:28, Noah Swartz <notifications@github.com> wrote:I was able to run it just now on a fresh centos box, and have the same versions of both of those.
Is there a way that you could re-install or fix the install of certbot via yum?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. You cannot use or forward any attachments in the email. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system.

**Comment by stevenzhu25** [comment]
I tried to reinstall from yum and it doesn't work for me.. I think there is something happens to urllib3 and pyopenssl.On Sep 21, 2017 17:28, Noah Swartz <notifications@github.com> wrote:I was able to run it just now on a fresh centos box, and have the same versions of both of those.
Is there a way that you could re-install or fix the install of certbot via yum?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. You cannot use or forward any attachments in the email. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system.

**Comment by SwartzCr** [comment]
Can you explain why you think urllib3 is involved? I don't see it in your error message

**Comment by stevenzhu25** [comment]
Because the first time, it tells me urllib3 is outdated and I updated via pip.Then this error message showed up.Now it seems went into a dead loop..On Sep 21, 2017 18:37, Noah Swartz <notifications@github.com> wrote:Can you explain why you think urllib3 is involved? I don't see it in your error message

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. You cannot use or forward any attachments in the email. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system.

**Comment by SwartzCr** [comment]
Can you share the full output of `pip freeze`?

**Comment by stevenzhu25** [comment]
```
[root@las2 ~]# pip freeze
acme==0.18.1
asn1crypto==0.22.0
backports.ssl-match-hostname==3.4.0.2
beautifulsoup4==4.6.0
certbot==0.18.1
certifi==2017.7.27.1
cffi==1.11.0
chardet==3.0.4
ConfigArgParse==0.11.0
configobj==4.7.2
cryptography==2.0.3
decorator==3.4.0
enum34==1.0.4
future==0.16.0
idna==2.6
iniparse==0.4
ipaddress==1.0.16
IPy==0.75
mock==1.0.1
mutagen==1.38
ndg-httpsclient==0.3.2
pafy==0.5.3.1
parsedatetime==1.5
pathlib==1.0.1
ply==3.4
policycoreutils-default-encoding==0.1
psutil==2.2.1
pyasn1==0.1.9
pycparser==2.14
pycurl==7.19.0
pygobject==3.22.0
pygpgme==0.3
pyliblzma==0.5.3
pyOpenSSL==0.13.1
pyparsing==1.5.6
pyRFC3339==1.0
python2-pythondialog==3.3.0
pytz==2016.10
pyxattr==0.5.1
requests==2.18.4
seobject==0.1
sepolicy==1.1
shadowsocks==2.8.2
six==1.10.0
slip==0.4.0
slip.dbus==0.4.0
spotipy==2.4.4
titlecase==0.11.0
unicode-slugify==0.1.3
Unidecode==0.4.21
urlgrabber==3.10
urllib3==1.22
youtube-dl==2017.9.2
yum-metadata-parser==1.1.4
zope.component==4.1.0
zope.event==4.0.3
zope.interface==4.0.5

```

**Comment by bmw** [comment]
We strongly discourage `pip` installing packages globally as it can corrupt OS packages on your system. `urllib3` sometimes uses `pyopenssl` to provide better SSL support than is found in the Python standard library.

At this point, it might be easiest to work around the problem by using [certbot-auto](https://certbot.eff.org/docs/install.html#certbot-auto) which installs Certbot in an isolated virtual environment without minimal reliance on the Python packages found on your system.

**Comment by joohoi** [comment]
Closing as it's something unfortunately not in our control. We have no way to track global dependency library versions currently outside of our own venv.
