### ISSUE TITLE
Renew Failed after Pacman -Syyu

### ISSUE THREAD

**Issue by tpu01yzx** [certbot/certbot#5131]
## My operating system is (include version):
Linux 4.12.13-1-ARCH #1 SMP PREEMPT Fri Sep 15 06:56:11 UTC 2017 i686 GNU/Linux
Python 3.6.2
pip 9.0.1 from /usr/lib/python3.6/site-packages (python 3.6)
certbot 0.18.2

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Both:
1) pacman -S certbot
2) pip install certbot

## I ran this command and it produced this output:
Run as root:  certbot renew
Output:
> Saving debug log to /var/log/letsencrypt/letsencrypt.log
> 
>  -------------------------------------------------------------------------------
>  Processing /etc/letsencrypt/renewal/XXX.conf
>  -------------------------------------------------------------------------------
>  Attempting to renew cert (XXX) from /etc/letsencrypt/renewal/XXX.conf produced an unexpected error: '<' not supported between instances of 'NoneType' and 'int'. Skipping.
> All renewal attempts failed. The following certs could not be renewed:
>   /etc/letsencrypt/live/XXX/fullchain.pem (failure)
> 
>  -------------------------------------------------------------------------------
> 
>  All renewal attempts failed. The following certs could not be renewed:
>   /etc/letsencrypt/live/XXX/fullchain.pem (failure)
>  -------------------------------------------------------------------------------
>  1 renew failure(s), 0 parse failure(s)
> 

## Certbot's behavior differed from what I expected because:
I have no idea why it fails,  since it has worked well.

## Here is a Certbot log showing the issue (if available):
/var/log/letsencrypt/letsencrypt.log :
> 2017-09-25 07:47:47,387:DEBUG:certbot.main:certbot version: 0.18.2
> 2017-09-25 07:47:47,388:DEBUG:certbot.main:Arguments: []
> 2017-09-25 07:47:47,389:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
> 2017-09-25 07:47:47,413:DEBUG:certbot.log:Root logging level set at 20
> 2017-09-25 07:47:47,414:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
> 2017-09-25 07:47:47,442:DEBUG:certbot.plugins.selection:Requested authenticator <certbot.cli._Default object at 0xb5a4ef4c> and installer <certbot.cli._Default object at 0xb5a4ef4c>
> 2017-09-25 07:47:47,443:DEBUG:certbot.cli:Default Detector is Namespace(account=<certbot.cli._Default object at 0xb5a4aa8c>, agree_dev_preview=None, allow_subset_of_names=<certbot.cli._Default object at 0xb5a4a98c>, apache=<certbot.cli._Default object at 0xb5a511ac>, apache_challenge_location=<certbot.cli._Default object at 0xb5a4c7cc>, apache_ctl=<certbot.cli._Default object at 0xb5a4cfcc>, apache_dismod=<certbot.cli._Default object at 0xb5a4e32c>, apache_enmod=<certbot.cli._Default object at 0xb5a4e0cc>, apache_handle_modules=<certbot.cli._Default object at 0xb5a4c64c>, apache_handle_sites=<certbot.cli._Default object at 0xb5a4c4cc>, apache_init_script=<certbot.cli._Default object at 0xb5a4c40c>, apache_le_vhost_ext=<certbot.cli._Default object at 0xb5a4cdcc>, apache_logs_root=<certbot.cli._Default object at 0xb5a4c94c>, apache_server_root=<certbot.cli._Default object at 0xb5a4cc6c>, apache_vhost_root=<certbot.cli._Default object at 0xb5a4cacc>, authenticator=<certbot.cli._Default object at 0xb5a4ef4c>, break_my_certs=<certbot.cli._Default object at 0xb5a4c22c>, cert_path=<certbot.cli._Default object at 0xb5a4e92c>, certname=<certbot.cli._Default object at 0xb5a4a38c>, chain_path=<certbot.cli._Default object at 0xb5a4eb8c>, checkpoints=<certbot.cli._Default object at 0xb5a4e54c>, config_dir=<certbot.cli._Default object at 0xb5a4ec2c>, config_file=None, configurator=<certbot.cli._Default object at 0xb5a4ef4c>, csr=<certbot.cli._Default object at 0xb5a4e36c>, debug=<certbot.cli._Default object at 0xb5a4ae2c>, debug_challenges=<certbot.cli._Default object at 0xb5a4aecc>, deploy_hook=<certbot.cli._Default object at 0xb5a4ce0c>, dialog=None, dns_cloudflare=<certbot.cli._Default object at 0xb5a5160c>, dns_cloudxns=<certbot.cli._Default object at 0xb5a516cc>, dns_digitalocean=<certbot.cli._Default object at 0xb5a4efac>, dns_dnsimple=<certbot.cli._Default object at 0xb5a4ee0c>, dns_dnsmadeeasy=<certbot.cli._Default object at 0xb5a4ec8c>, dns_google=<certbot.cli._Default object at 0xb5a4eb2c>, dns_luadns=<certbot.cli._Default object at 0xb5a4e9ac>, dns_nsone=<certbot.cli._Default object at 0xb5a4e80c>, dns_rfc2136=<certbot.cli._Default object at 0xb5a4e66c>, dns_route53=<certbot.cli._Default object at 0xb5a4e4cc>, domains=<certbot.cli._Default object at 0xb5a4a30c>, dry_run=<certbot.cli._Default object at 0xb5a4a1ec>, duplicate=<certbot.cli._Default object at 0xb5a4ab2c>, eff_email=<certbot.cli._Default object at 0xb5a4a5ec>, email=<certbot.cli._Default object at 0xb5a4a54c>, expand=<certbot.cli._Default object at 0xb5a4a76c>, force_interactive=<certbot.cli._Default object at 0xb5a4a28c>, fullchain_path=<certbot.cli._Default object at 0xb5a4eaac>, func=<function renew at 0xb5b0b7c4>, hsts=<certbot.cli._Default object at 0xb5a4c5cc>, http01_address=<certbot.cli._Default object at 0xb5a4c16c>, http01_port=<certbot.cli._Default object at 0xb5a4c0ec>, ifaces=<certbot.cli._Default object at 0xb5a4e7ac>, init=<certbot.cli._Default object at 0xb5a4e5ec>, installer=<certbot.cli._Default object at 0xb5a4ef4c>, key_path=<certbot.cli._Default object at 0xb5a4ea0c>, logs_dir=<certbot.cli._Default object at 0xb5a4edac>, manual=<certbot.cli._Default object at 0xb5a5144c>, manual_auth_hook=<certbot.cli._Default object at 0xb5a4e30c>, manual_cleanup_hook=<certbot.cli._Default object at 0xb5a4c14c>, manual_public_ip_logging_ok=<certbot.cli._Default object at 0xb5a4c04c>, max_log_backups=<certbot.cli._Default object at 0xb5a4a14c>, must_staple=<certbot.cli._Default object at 0xb5a4c38c>, nginx=<certbot.cli._Default object at 0xb5a512ac>, no_bootstrap=<certbot.cli._Default object at 0xb5a4acac>, no_self_upgrade=<certbot.cli._Default object at 0xb5a4ac2c>, no_verify_ssl=<certbot.cli._Default object at 0xb5a4af4c>, noninteractive_mode=<certbot.cli._Default object at 0xb5a4a20c>, num=<certbot.cli._Default object at 0xb5a4e10c>, os_packages_only=<certbot.cli._Default object at 0xb5a4abac>, post_hook=<certbot.cli._Default object at 0xb5a4cc8c>, pre_hook=<certbot.cli._Default object at 0xb5a4cc0c>, pref_challs=<certbot.cli._Default object at 0xb5a4cb2c>, prepare=<certbot.cli._Default object at 0xb5a4e6cc>, quiet=<certbot.cli._Default object at 0xb5a4ad2c>, reason=<certbot.cli._Default object at 0xb5a4e44c>, redirect=<certbot.cli._Default object at 0xb5a4c44c>, register_unsafely_without_email=<certbot.cli._Default object at 0xb5a4a44c>, reinstall=<certbot.cli._Default object at 0xb5a4a6ec>, renew_by_default=<certbot.cli._Default object at 0xb5a4a88c>, renew_hook=<certbot.cli._Default object at 0xb5a4cd4c>, renew_with_new_domains=<certbot.cli._Default object at 0xb5a4a90c>, rsa_key_size=<certbot.cli._Default object at 0xb5a4c2cc>, server=<certbot.cli._Default object at 0xb5a4ee6c>, staging=<certbot.cli._Default object at 0xb5a4adac>, standalone=<certbot.cli._Default object at 0xb5a5138c>, standalone_supported_challenges=<certbot.cli._Default object at 0xb5a4af2c>, staple=<certbot.cli._Default object at 0xb5a4c8cc>, strict_permissions=<certbot.cli._Default object at 0xb5a4ca4c>, text_mode=<certbot.cli._Default object at 0xb5a4a0cc>, tls_sni_01_address=<certbot.cli._Default object at 0xb5a4c06c>, tls_sni_01_port=<certbot.cli._Default object at 0xb5a4afcc>, tos=<certbot.cli._Default object at 0xb5a4aa0c>, uir=<certbot.cli._Default object at 0xb5a4c74c>, update_registration=<certbot.cli._Default object at 0xb5a4a4cc>, user_agent=<certbot.cli._Default object at 0xb5a4e1ec>, user_agent_comment=<certbot.cli._Default object at 0xb5a4e2ac>, validate_hooks=<certbot.cli._Default object at 0xb5a4cecc>, verb='renew', verbose_count=<certbot.cli._Default object at 0xb5abba2c>, webroot=<certbot.cli._Default object at 0xb5a5152c>, webroot_map=<certbot.cli._Default object at 0xb5a4ad0c>, webroot_path=<certbot.cli._Default object at 0xb5a4c28c>, work_dir=<certbot.cli._Default object at 0xb5a4ecec>)
> 2017-09-25 07:47:47,445:DEBUG:certbot.storage:No matches for target privkey.
> 2017-09-25 07:47:47,446:WARNING:certbot.renewal:Attempting to renew cert (XXX) from /etc/letsencrypt/renewal/XXX.conf produced an unexpected error: '<' not supported between instances of 'NoneType' and 'int'. Skipping.
> 2017-09-25 07:47:47,446:DEBUG:certbot.renewal:Traceback was:
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/certbot/renewal.py", line 416, in handle_renewal_request
>     renewal_candidate.ensure_deployed()
>   File "/usr/lib/python3.6/site-packages/certbot/storage.py", line 753, in ensure_deployed
>     if self.has_pending_deployment():
>   File "/usr/lib/python3.6/site-packages/certbot/storage.py", line 772, in has_pending_deployment
>     smallest_current = min(self.current_version(x) for x in ALL_FOUR)
> TypeError: '<' not supported between instances of 'NoneType' and 'int'
> 
> 2017-09-25 07:47:47,446:ERROR:certbot.renewal:All renewal attempts failed. The following certs could not be renewed:
> 2017-09-25 07:47:47,447:ERROR:certbot.renewal:  /etc/letsencrypt/live/XXX/fullchain.pem (failure)
> 2017-09-25 07:47:47,447:DEBUG:certbot.log:Exiting abnormally:
> Traceback (most recent call last):
>   File "/usr/bin/certbot", line 11, in <module>
>     sys.exit(main())
>   File "/usr/lib/python3.6/site-packages/certbot/main.py", line 755, in main
>     return config.func(config, plugins)
>   File "/usr/lib/python3.6/site-packages/certbot/main.py", line 705, in renew
>     renewal.handle_renewal_request(config)
>   File "/usr/lib/python3.6/site-packages/certbot/renewal.py", line 443, in handle_renewal_request
>     len(renew_failures), len(parse_failures)))
> certbot.errors.Error: 1 renew failure(s), 0 parse failure(s)

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

> <VirtualHost *:80>
>     ServerAdmin XXX@gmail.com
>     DocumentRoot "/srv/http"
>     ServerName XXX
>     ServerAlias www.XXX ipv6.XXX ipv4.XXX
>     ErrorLog "/var/log/httpd/XXX-error_log"
>     CustomLog "/var/log/httpd/XXX-access_log" http_log
>     DirectoryIndex index.htm index.html index.php
>     <Directory "/srv/http">
>         Options FollowSymLinks
>         AllowOverride All
>         Order Allow,Deny
>         Allow from All
>         #Deny from 183.36.49.212
>     </Directory>
>     <Location "/wang">
>         Options Indexes FollowSymLinks
>     </Location>
>     <Location "/shumo">
>         Options Indexes FollowSymLinks
>     </Location>
> </VirtualHost>
> 
> <VirtualHost _default_:443>
>     ServerAdmin XXX@gmail.com
>     DocumentRoot "/srv/http"
>     ServerName XXX
>     ServerAlias www.XXX ipv4.XXX
>     ErrorLog "/var/log/httpd/XXX-https-error_log"
>     CustomLog "/var/log/httpd/XXX-https--access_log" http_log
>     DirectoryIndex index.htm index.html index.php
>     Header always set Strict-Transport-Security "max-age=15552000; includeSubdomains; preload"
>     Header always set X-Frame-Options DENY
>     Header always set Public-Key-Pins 'pin-sha256="YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg="; pin-sha256="FDa2YLUb+/nfevziv5m1UI6TKOtZmCiBmawe1cOQwyE=";  max-age=15552000; includeSubDomains'
>     <Directory "/srv/http">
>         Options FollowSymLinks
>         AllowOverride All
>         Order Allow,Deny
>         Allow from All
>         #Deny from 183.36.49.212
>     </Directory>
>     <Location "/wang">
>         Options Indexes FollowSymLinks
>     </Location>
>     <Location "/shumo">
>         Options Indexes FollowSymLinks
>     </Location>
> 
> 
> SSLEngine on
> SSLProtocol all -SSLv2 -SSLv3
> SSLHonorCipherOrder on
> 
> SSLCipherSuite "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH+aRSA+RC4 EECDH EDH+aRSA RC4 !EDH RSA+AES+SHA !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS !RC4"
> SSLCertificateFile "/etc/httpd/conf/XXX.fullchain.pem"
> SSLCertificateKeyFile "/etc/httpd/conf/XXX.privkey.pem"
> SSLCertificateChainFile "/etc/letsencrypt/live/XXX/chain.pem"
> SSLCACertificateFile "/etc/httpd/conf/ca-bundle-wosign.crt"
> 
> 
> <FilesMatch "\.(cgi|shtml|phtml|php)$">
>     SSLOptions +StdEnvVars
> </FilesMatch>
> 
> BrowserMatch "MSIE [2-5]" \
>          nokeepalive ssl-unclean-shutdown \
>          downgrade-1.0 force-response-1.0
> 
> CustomLog "/var/log/httpd/ssl_request_log" \
>           "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b"
> 
> </VirtualHost>

.htaccess in webroot:

>  #  BEGIN Redirect to HTTPS
> <IfModule mod_rewrite.c>
> RewriteEngine On
> RewriteBase /
> RewriteCond %{SERVER_PORT} !^443$
> RewriteCond %{SERVER_NAME} ^XXX\.me$
> RewriteRule ^(.*)?$ https://%{SERVER_NAME}/$1 [L,R]
> </IfModule>
>  # END Redirect to HTTPS

/etc/letsencrypt/renewal/XXX.conf : 

>  #  renew_before_expiry = 30 days
> cert = /etc/letsencrypt/live/XXX/cert.pem
> privkey = /etc/letsencrypt/live/XXX/privkey.pem
> chain = /etc/letsencrypt/live/XXX/chain.pem
> fullchain = /etc/letsencrypt/live/XXX/fullchain.pem
>  # version = 0.18.2
> archive_dir = /etc/letsencrypt/archive/XXX
> 
>  # Options used in the renewal process
> [renewalparams]
> authenticator = webroot
> #installer = None
> account = XXX
> [[webroot_map]]
> XXX = /srv/http

**Comment by SwartzCr** [comment]
It is really frowned upon to install certbot from pip, installing from pip once you already had installed it from pacman is very likely what caused this issue.
When you ran certbot most recently, which certbot did you invoke? The system installed one or the pip installed one?

**Comment by tpu01yzx** [comment]
The system installed one, maybe two months ago. .

**Comment by SwartzCr** [comment]
I would uninstall it via pip, then re-install it via pacman, and see if that fixes it. It's likely that you have some python package version problems.
If you use IRC I'm happy to do more hands on debugging in the #letsencrypt channel on irc.freenode.org
Feel free to ping me, my irc name is swartzcr

**Comment by tpu01yzx** [comment]
This problem is solved. Thanks.

 It's nothing about the packages. Two of the ALL_FOUR are link symbols, and it seems that storage.py can't get the correct version and returns None, which makes this issuse. After  I created link symbols of ALL_FOUR in the archive directory, everything works well.

In the following, the number "10" is the greatest number in the archive directory. and some configurations of httpd and certbot,  should make minor changes for the corresponding options.
```
ln -sf /etc/letsencrypt/archeive/XXX/cert10.pem /etc/letsencrypt/live/XXX/cert.pem
ln -sf /etc/letsencrypt/archeive/XXX/privkey10.pem /etc/letsencrypt/live/XXX/privkey.pem
ln -sf /etc/letsencrypt/archeive/XXX/chain10.pem /etc/letsencrypt/live/XXX/chain.pem
ln -sf /etc/letsencrypt/archeive/XXX/fullchain10.pem /etc/letsencrypt/live/XXX/fullchain.pem

ln -sf  /etc/letsencrypt/live/XXX/privkey.pem /etc/httpd/conf/XXX.privkey.pem
ln -sf  /etc/letsencrypt/live/XXX/fullchain.pem /etc/httpd/conf/XXX.fullchain.pem
```
