### ISSUE TITLE
Using certbot via proxy

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [certbot/certbot#5136]
## My operating system is (include version):
RHEL 7

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
package manager

## I ran this command and it produced this output:
sudo certbot certonly

## Certbot's behavior differed from what I expected because:
My Virtual machine can access to interent only via proxy.

## Here is a Certbot log showing the issue (if available):
An unexpected error occurred:
ConnectionError: ('Connection aborted.', error(101, 'Network is unreachable'))
Please see the logfiles in /var/log/letsencrypt for more details.

Is it possible to set proxy for certbot?

**Comment by bmw** [comment]
Certbot uses the requests library internally which allows you to set environment variables like the ones described [here](http://docs.python-requests.org/en/master/user/advanced/#proxies). Does this work for your use case?

**Comment by SuperMasterBlasterLaser** [comment]
@bmw Thank you. environment variables worked. I just got used to other softwares that requires setting proxy explicitly in their config files.
