### ISSUE TITLE
Unable to use certbot on FreeBSD 12.0

### ISSUE THREAD

**Issue by PeterAS17** [certbot/certbot#5140]
## My operating system is (include version):
FreeBSD 12.0

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
pkg install py27-certbot

## Certbot's behavior differed from what I expected because:
certbot renew --dry-run

```
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3038, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3022, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3051, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 659, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 672, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 862, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cryptography 1.7.2 (/usr/local/lib/python2.7/site-packages), Requirement.parse('cryptography>=1.9'), set(['PyOpenSSL']))
```

No matter what command I run, it outputs an error.
Is this a known issue on the version 12?

PeterAS17

**Comment by bmw** [comment]
I wasn't aware there was a FreeBSD 12.

As long as you haven't done anything like install packages on your system through another mechanism like `pip` and your system is up to date, the versions of py27-cryptography and py27-openssl offered on this system may not be compatible with each other.

Any thoughts @koobs?

**Comment by koobs** [comment]
@bmw FreeBSD 12 is the version of the development (HEAD) branch (named: 12-CURRENT), and has not yet been "-RELEASE'd"

The version conflict issue reported here was reported in [FreeBSD Bug 222536](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=222536) and resolved on 2017-09-24 05:00:51, in:

 * [FreeBSD Bug 222519](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=222519)
 * [FreeBSD Bug 222520](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=222520)

@PeterAS17 Please update your ports tree (or package repository) to the latest version and reinstall certbot. The issue should be resolved. Please open an new issue in the [FreeBSD Issue Tracker](https://bugs.freebsd.org/bugzilla/) for any future issues with the certbot port/package

**Comment by bmw** [comment]
Thanks @koobs!

I'm closing this issue as it appears to have been resolved.
