### ISSUE TITLE
dry-run doesn't work but works correctly without dry-run.

### ISSUE THREAD

**Issue by lyenliang** [certbot/certbot#5141]
## My operating system is (include version):
macOS Sierra
Version 10.12.6

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
command with `--dry-run` doesn't work: 
`./certbot-auto certonly --dry-run --keep --webroot -w /usr/share/nginx/html -d myDomain.com`

output with error messages:

    Saving debug log to /var/log/letsencrypt/letsencrypt.log
    Plugins selected: Authenticator webroot, Installer None
    Cert not due for renewal, but simulating renewal for dry run
    Renewing an existing certificate
    Performing the following challenges:
    http-01 challenge for myDomain.com
    Using the webroot path /usr/share/nginx/html for all unmatched domains.
    Waiting for verification...
    Cleaning up challenges
    Failed authorization procedure. myDomain.com (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: DNS problem: SERVFAIL looking up A for myDomain.com

    IMPORTANT NOTES:
    - The following errors were reported by the server:

    Domain: myDomain.com
    Type:   connection
    Detail: DNS problem: SERVFAIL looking up A for
    myDomain.com

    To fix these errors, please make sure that your domain name was
    entered correctly and the DNS A/AAAA record(s) for that domain
    contain(s) the right IP address. Additionally, please check that
    your computer has a publicly routable IP address and that no
    firewalls are preventing the server from communicating with the
    client. If you're using the webroot plugin, you should also verify
    that you are serving files from the webroot path you provided.

command without `--dry-run` works correctly: 
`./certbot-auto certonly --keep --webroot -w /usr/share/nginx/html -d myDomain.com`

successful output: 

    Saving debug log to /var/log/letsencrypt/letsencrypt.log
    Plugins selected: Authenticator webroot, Installer None
    Obtaining a new certificate
    Performing the following challenges:
    http-01 challenge for myDomain.com
    Using the webroot path /usr/share/nginx/html for all unmatched domains.
    Waiting for verification...
    Cleaning up challenges

    IMPORTANT NOTES:
    - Congratulations! Your certificate and chain have been saved at:
    /etc/letsencrypt/live/myDomain.com/fullchain.pem
    Your key file has been saved at:
    /etc/letsencrypt/live/myDomain.com/privkey.pem
    Your cert will expire on 2017-12-26. To obtain a new or tweaked
    version of this certificate in the future, simply run certbot-auto
    again. To non-interactively renew *all* of your certificates, run
    "certbot-auto renew"
    - If you like Certbot, please consider supporting our work by:

    Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
    Donating to EFF:                    https://eff.org/donate-le

I expect the command with `--dry-run` works correctly, but it doesn't. Is this a bug of certbot?

Another thing I need to mention is that `myDomain.com` is a `CNAME`, not an `A` record.

**Comment by cpu** [comment]
@lyenliang Can you share the affected domain name? It's difficult to debug this problem without knowing that.

> I expect the command with --dry-run works correctly, but it doesn't. Is this a bug of certbot?

I believe Certbot isn't the problem here. I suspect in the production environment (the one used without `--dry-run`) you had successfully issued a certificate for this name using the same Certbot account within the last 30 days. The authorization created from that issuance is reused and so no fresh `http-01` challenge is performed. Meanwhile, in the staging environment (the one used with `--dry-run`) I suspect you don't have a cached authorization and so a fresh `http-01` challenge is done and this underlying problem with your DNS becomes visible.

I suspect if you created a new Certbot account and tried to issue for this domain without `--dry-run` it would fail with the same error message as you see now.

If you share your domain name I can try and help you diagnose why some part of your DNS infrastructure for this domain is returning a SERVFAIL error.

**Comment by lyenliang** [comment]
Hi, @cpu, thanks for your reply. But The domain name I run `cert-bot` with is a private domain name that belongs to the company I work for. Even if I tell you the domain name, you will not be able to access it. It is public only before I renew it. It becomes private right after the renew command.

**Comment by cpu** [comment]
Hi @lyenliang Did you try my idea to test if the confusion about `--dry-run` vs not is the product of a reused authorization?

I suspect if you created a new Certbot account and tried to issue for this domain without `--dry-run` it would fail with the CAA error you see using `--dry-run`.

> Even if I tell you the domain name, you will not be able to access it. It is public only before I renew it. It becomes private right after the renew command.

That's ok, I don't need to access the site to help diagnose a CAA SERVFAIL error as long as the nameservers for the domain are publicly accessible. I recommend you [check out our documentation page on CAA SERVFAIL errors](https://letsencrypt.org/docs/caa/) as well, it's a very helpful resource.

It might be a better idea to post on [the community forum](https://community.letsencrypt.org) with a mention of the CAA failure you're seeing. I don't believe there are any certbot bugs involved in the problems you describe for the team to address on this repository.

**Comment by lyenliang** [comment]
Hi, I haven't figured out how to create a new Certbot account. But I have tried registering a new domain with `--dry-run` option. I still the same error saying `SERVFAIL looking up A for myDomain`.  

This means that even if I hadn't issued a certificate for this new domain using the Certbot account within the last 30 days. Running the command with `--dry-run` options still fails.

**Comment by adferrand** [comment]
This issue has not been updated for a long time. So I assume it is solved, or not relevant anymore. If not, do not hesitate to reopen an issue with updated info about its context.
