### ISSUE TITLE
Bump apt-get version from 0.17.0 to 0.18.2

### ISSUE THREAD

**Issue by binarykitchen** [certbot/certbot#5145]
I see, when I install certbot for Ubuntu 17 via apt-get, the 0.17.0 version is installed. But when via pip, the newer 0.18.2 version is installed.

Reluctant here to install it via pip. apt-get is the standard by why is the version not updated there to 0.18.2 like the python one? Just curious ...

**Comment by bmw** [comment]
Our PPA is maintained by Debian developers who take the packages from Debian sid (unstable) which is [still at 0.17.0](https://packages.debian.org/sid/certbot).

@hlieberman, any time line on when you expect to update these packages. FYI, 0.19.0 will be coming out next week.

**Comment by joohoi** [comment]
Closing
