### ISSUE TITLE
tests/modification-check.sh problems

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5147]
Imagine the following sequence of events:

1. We do a release, adding a new git tag with changes to our certbot-auto/letsencrypt-auto script.
2. An unrelated PR lands in master triggering CI.
3. A PR updating *-auto in the root of our repo to match the version from the release lands in master.
4. If tests/modification-check.sh has not been run yet for the first PR, when it does run, it will first compare certbot-auto to the files in master. Since these files were just updated in step 3, this check fails. It then compares the file to the version from our most recent git tag which also fails causing the entire test to fail.

This happened [here](https://travis-ci.org/certbot/certbot/jobs/280647927). Our test should try to be more robust than this.

**Comment by joohoi** [comment]
Is this still relevant for our current release process?

**Comment by bmw** [comment]
Technically yes but the PR updating `certbot-auto`/`letsencrypt-auto` in the root of our repo has to land between tests starting to run and the test pulling the latest version of the file from GitHub. I'm not sure if I've seen this in the year and a half since I wrote this issue.

On our list of the 758 open issues to work on, this seems near the bottom and can be fixed by rerunning tests so I'm closing this.
