### ISSUE TITLE
Enable certificate verification (incl. revocation) by installing OpenSSL on Docker image

### ISSUE THREAD

**Issue by gghidini** [certbot/certbot#5154]
Could `openssl` be installed into Docker image so that certifcates can be tested for revocation?

I noticed `openssl-dev` is installed among `.build-deps` at https://github.com/certbot/certbot/blob/0.18.x/Dockerfile#L20 and then duly removed.

Sure enough certbot DID test for revocation after I installed `openssl` on my running container w/:

```
# apk info openssl
```

(after updating `apk` w/ `# apk update`)

## My operating system is (include version):

DigitalOcean Ubuntu 16.04.3 x64

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

```
$ docker run -it \
  --entrypoint=ash \
  certbot/certbot:v0.18.2
```

## I ran this command and it produced this output:

```
/opt/certbot # certbot certificates
Saving debug log to /var/log/letsencrypt/letsencrypt.log
openssl not installed, can't check revocation

-------------------------------------------------------------------------------
Found the following certs:
  Certificate Name: <my cert>
    Domains: <my domain>
    Expiry Date: 2017-12-31 <time> (INVALID: TEST_CERT)
    Certificate Path: /etc/letsencrypt/live/<name>/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/<name>/privkey.pem
-------------------------------------------------------------------------------
```

## Certbot's behavior differed from what I expected because:

Unless there's some other issue (image size, openssl version compatibility, etc), I think it would make sense to install openssl into Docker image, so that certificates can be tested for revocation.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

N/A

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

N/A

**Comment by bmw** [comment]
Yes the `openssl` package should be added to the Docker image so this works. Probably we should just install the `openssl` package with ".certbot-deps" and continue to install and remove the `openssl-dev` build dependency.

**Comment by bmw** [comment]
Thanks for reporting this issue!

**Comment by gghidini** [comment]
Thanks @bmw .

I agree w/ proposed solution.

Since it's rather simple at this time, I can take care of this, if you want me to.

**Comment by bmw** [comment]
That'd be great! I'll happily review the PR.

**Comment by gghidini** [comment]
Cool. I'll get on it.
