### ISSUE TITLE
Replace instances of isinstance(x, str) with isinstance(x, six.string_types)

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#5155]
To properly detect unicode and be python3-safe.

**Comment by mvi-x** [comment]
is this a simple search in all files ```isinstance(x, str)``` and replace for ```isinstance(x, six.string_types)```?
If so, I could do it. I've been looking forward to contributing somehow towards security and privacy with my limited ability and this could be a way to get started in a project I respect greatly.

**Comment by bmw** [comment]
Yes that's it! Thanks for the interest and the kind words. We'd happily accept a PR that makes this change.

**Comment by mvi-x** [comment]
Thanks for the prompt reply! I may be missing something here, but I've checked the whole code base and it'd seem to me like this has already been done. I guess this means one concern less!

**Comment by bmw** [comment]
I think I found a few! Go to the root of the Certbot repo and run `git grep "isinstance.*str)"`

**Comment by mvi-x** [comment]
Oh man. Sorry and thanks for being nice about this. I think I got them now!
