### ISSUE TITLE
add_server_directives should pick up whitespace from context rather than having the caller set it, and definitely for replace it should just replace the contents.

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#5157]

**Comment by lwm** [comment]
Right, I started to get setup and lost into the source. I want to write a test first, I guess that this would go in `certbot-nginx/certbot_nginx/tests/parser_test.py` and might look like this:

``` python
    def test_add_server_directives_indent_from_context(self):
        server_block = nginxparser.loads("""
            server {
                listen 80;
            }""")
        # TODO: add some directive
        # TODO: test that we got the same indentation

        server_block = nginxparser.loads("""
            server {
                    listen 80;
            }""")
        # TODO: add some directive
        # TODO: test that we got the same indentation

        server_block = nginxparser.loads("""
            server {
                listen 80;
                    index star.html;
            }""")
        # TODO: add some directive
        # TODO: test that we got the same indentation
        # TODO: Different indentations!?
```

Is this the right approach? I just want to write a fresh configuration and check that what I put in gets the right indentation.

One question I thought about - what happens when there are various levels of indentation (see third example in the test). What should be done about that?

**Comment by ohemorange** [comment]
Yes, this is definitely the right track!

I could see the tests going either there, in `certbot-nginx/certbot_nginx/tests/nginxparser_test.py`, or in both, depending. `parser.py` has our directive-and-higher level code, whereas `nginxparser.py` is more about parsing into lists and such.

For different indentations, you can make that decision as the implementer -- match the previous line, match the next line, and match whatever seems to be the dominant indentation in that block all seem defensible to me.

Some additional test ideas:
- What happens when there's indentation in the server directive being added?
- What happens when the previous or next line is just a newline?
- What happens when the new directive is just whitespace?

Thanks for your work on this!

**Comment by bmw** [comment]
It looks like we're making progress on this in issues like #5823.

**Comment by ohemorange** [comment]
while not necessarily necessary to have this as a standalone issue, I think it's nice to keep open as a reminder as part of a larger nginx parser rehaul.

**Comment by martindale** [comment]
Any progress on this?

**Comment by nocturn9x** [comment]
It's useless to close issues as duplicates and link to this one if the problem wasn't fixed :)
