### ISSUE TITLE
Generated nginx configuration is missing IPv6 listen directive

### ISSUE THREAD

**Issue by jplatte** [certbot/certbot#5165]
This is probably due to bad documentation on nginx side, but currently CertBot only generates a `listen 443 ssl;` directive, both for the validation domain used for tls-sni-01 and the actual domain(s) the certificate is for. This means that tls-sni-01 validation currently doesn't work on ipv6-enabled servers running nginx unless the validation server chooses ipv4 over ipv6 (which I'd assume it probably never does when the server has DNS records for both).

This issue should be reproducible by installing nginx on a server with both an ipv4 and an ipv6, plus corresponding A/AAAA DNS entries, and adding a simple server block like the following:

```nginx
server {
    listen 80;
    listen [::]:80;

    server_name mydomain.horse;
    root /srv/http/mydomain.horse;
}
```

... and then running `certbot --nginx -d mydomain.horse`.

**Comment by jplatte** [comment]
To be clear, the directive that is missing in the generated config is

```nginx
listen [::]:443 ssl;
```

**Comment by bmw** [comment]
@ohemorange, can you take a look at this?

**Comment by ohemorange** [comment]
Yes, this is an open issue. Thank you for reporting that it's helpful for your use case, closing in favor of #3640 and #4992.
