### ISSUE TITLE
Add install information for nixos

### ISSUE THREAD

**Issue by nico202** [certbot/certbot#5175]
nix (and so nixOS) provide a package for coreboot available [here
](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/admin/certbot/default.nix) but on the website is not listed. 

Thanks :)

**Comment by bmw** [comment]
Thanks for reporting this! I made an issue for this on the repo for our website at certbot/website#279.

Closing this ticket in favor of that one.
