### ISSUE TITLE
certonly command with --cert-name flag still suffixes certificate directories with -001, -002, etc.

### ISSUE THREAD

**Issue by axsuul** [certbot/certbot#5177]
## My operating system is (include version):

Docker image 0.17.0

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Docker image 0.17.0

## I ran this command and it produced this output:

```
certbot \
  certonly \
  --standalone \
  --non-interactive \
  --preferred-challenges http-01 \
  --agree-tos \
  --no-eff-email \
  --email admin@trunkinventory.com \
  --domains example.com,admin.example.com \
  --cert-name example \
  --reinstall
```

running this command will generate the appropriate certs as expected in `live/example`. However, running this command (with intention to renew) a few days later will not replace the original certificates in `live/example` but will instead place them in a new directory `live/example-001`. 

I was under the impression that this was addressed in https://github.com/certbot/certbot/issues/2071 and https://github.com/certbot/certbot/issues/3615 so not sure if this is a regression or bug. 

If this is not in fact a bug, how would I achieve overwriting existing certificates of the same lineage when using `certonly`?

**Comment by bmw** [comment]
@ohemorange, can you take a look at this?

**Comment by ohemorange** [comment]
You correctly understand the intended behavior, and I'm having trouble reproducing this issue. Would you mind pasting relevant logs into a gist?

**Comment by fitzg2** [comment]
The issue is that it isn't clear why if /etc/letsencrypt/live/xyz.com/xyz.pem points to the latest generated certificates while it keeps creating -0001 folders on live. @axsuul please correct me if am wrong.

Another reason could be because you created a certificate for example.com first and added admin.example.com

**Comment by axsuul** [comment]
Actually I believe my issue was my `renewal/DOMAIN.conf` was blank which might've been screwing with the lineages. I'm still investigating.

**Comment by tomwassenberg** [comment]
@axsuul I think I also ran into that today in #5395. I also deleted my renewal config beforehand.

**Comment by ohemorange** [comment]
@axsuul did you end up figuring out what happened here? sounds to me like the renewal conf file was wiped for some reason, leading to this behavior.

**Comment by ohemorange** [comment]
No responses, so closing this.
