### ISSUE TITLE
debian packages are outdated

### ISSUE THREAD

**Issue by mhow2** [certbot/certbot#5179]
## My operating system is (include version):

Debian Stretch 9.1

## I installed Certbot with OS package manager:

By following the guidelines from https://certbot.eff.org/
Leading to https://certbot.eff.org/#debianstretch-apache for my OS and it installed version 0.10.2-1

## Certbot's behavior differed from what I expected because:

version that is included in Stretch doesn't implement the changes from #1042  (for example)

The workaround is to use certbot-auto of course but as said in the docs  https://certbot.eff.org/docs/install.html#about-certbot 

> Unless you have very specific requirements, we kindly suggest that you use the Certbot packages provided by your package manager

**Comment by bmw** [comment]
@hlieberman, what's the status of getting Certbot into stretch-backports?

**Comment by bmw** [comment]
@mhow2, in the meantime, if you need features only available in newer versions of Certbot, I recommend you use [certbot-auto](https://certbot.eff.org/docs/install.html#certbot-auto).

**Comment by hlieberman** [comment]
@mhow2, @bmw, a new version has been uploaded to stretch-backports.  It's in the backports-NEW queue at the moment, but it should be released in the next couple of days.

**Comment by bmw** [comment]
Great. I'm closing this issue.

I opened certbot/website#283 to track updating our documentation to tell users to use backports.
