### ISSUE TITLE
Describe Dockerfile tags/features in description on Docker Hub

### ISSUE THREAD

**Issue by MulticolorWorld** [certbot/certbot#5190]
This is not a bug report.

Description of [dockerhub](https://hub.docker.com/r/certbot/certbot/) is not explanation of certbot docker "image".
It should be written about image tag, command to running, configuration particular to docker, in dockerhub description (like [nginx](https://hub.docker.com/_/nginx/)).

Maybe it is needed massive change repository structure.
But I think that this change is necessary to use this image easier.

Very poor english sorry.

**Comment by bmw** [comment]
I agree this should be improved. Currently it's just pulling in the general README for this repo.

We'll get to this eventually, but if someone else wants to write up an improved version and tell me how to have it use that description on Docker Hub, I'll gladly update it.

Thanks for reporting this!

**Comment by MulticolorWorld** [comment]
We configure dockerhub build settings, then dockerhub use README in same folder of Dockerfile.
In other words, at master branch, we set Dockerfile Location to folder except root and put Dockerfile and README file in that folder, so we can show dedicated README for DockerHub.

Referenced: [Configure automated builds on Docker Hub](https://docs.docker.com/docker-hub/builds/)

**Comment by MulticolorWorld** [comment]
I am thinking pull request about this issue(Moving Dockerfile and copy readme etc....).
At that time, I should know meaning of some Dockerfiles and build script in this repo.
Would you show me these information or documentation?

**Comment by bmw** [comment]
I'm not sure there's any written documentation for it, but I'm happy to answer any questions that you have. With the approach of putting the Dockerfile in a subdirectory of the root of the repository, are you still able to configure Docker Hub/Quay.io use the root of the repository as the build context? All of our Dockerfiles copy in multiple files/directories from the root of our repo.

If this is possible, `Dockerfile-dev` can/should probably left alone as it's a Dockerfile for people developing Certbot with no automated builds anywhere. `Dockerfile` and `Dockerfile-old` are our Dockerfiles used by end users with `Dockerfile-old` being deprecated. Our documentation for how to use this Dockerfile can be found [here](https://certbot.eff.org/docs/install.html#running-with-docker).

**Comment by bmw** [comment]
I think this issue can be closed with the move to https://github.com/certbot-docker/certbot-docker/ making the READMEs specific to our Docker images and https://github.com/certbot-docker/certbot-docker/issues/2 tracking improving the documentation found in those files.
