### ISSUE TITLE
certbot: error: unrecognized arguments: –-post-hook

### ISSUE THREAD

**Issue by lordspace** [certbot/certbot#5191]
## My operating system is (include version):
ubuntu 16

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
```
git clone https://github.com/letsencrypt/letsencrypt /opt/letsencrypt
cd /opt/letsencrypt
chmod 0755 /opt/letsencrypt/certbot-auto
```

## I ran this command and it produced this output:
```
root@app:/opt/letsencrypt# /opt/letsencrypt/certbot-auto renew  –-post-hook='nginx -s reload'
usage:
  certbot-auto [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate.
certbot: error: unrecognized arguments: –-post-hook=nginx -s reload
```

## Certbot's behavior differed from what I expected because:
According to docs there's a --post-hook but the binary complains that it doesn't have that kind of argument.

here's the doc I used.
 /opt/letsencrypt/certbot-auto --help renew

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

`/opt/letsencrypt/certbot-auto certonly --webroot --webroot-path /var/www/vhosts/example.com/htdocs --no-eff-email --noninteractive --verbose --rsa-key-size 4096 --email admin+clients+example@example.com --verbose --text --agree-tos -d example.com -d www.example.com  2>&1 | tee -a ssl.log
`

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
n/a

**Comment by bmw** [comment]
I think the problem here is the hyphens before `post-hook`. Looking at what you posted above, the first hyphen is the "En Dash" Unicode character not found in standard ASCII, while the 2nd hyphen is the conventional one found in ASCII and most UNIX command lines. I expect fixing this so your command becomes:
```
/opt/letsencrypt/certbot-auto renew  --post-hook='nginx -s reload'
```
will solve the problem.

**Comment by adferrand** [comment]
This issue has not been updated for a long time, while info is required to move on, and a solution has been proposed. So I assume it is solved, or not relevant anymore. If not, do not hesitate to reopen an issue with updated info about its context.
