### ISSUE TITLE
Nginx plugin not finding HTTP server block it created

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5196]
## My operating system is (include version):

Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Dev instructions

## I ran this command and it produced this output:

Starting with the default Nginx config on Ubuntu 16.04, I ran:
```
$ sudo certbot -d example.org,www.example.org --nginx --redirect
...
No matching insecure server blocks listening on port 80 found.
No matching insecure server blocks listening on port 80 found.
...
```

## Certbot's behavior differed from what I expected because:
Nginx is listening on port 80 and continuing to serve insecure HTTP traffic for these domains.

Probably what we should do is if no matching server block is found is if Nginx is listening on port 80 at all, we should create new server block(s) for the purpose of redirecting the traffic.

cc @ohemorange

**Comment by bmw** [comment]
While we should eventually be creating a separate server block, the actual bug right now is our Nginx plugin is failing to find the server block we created from the default that is listening on both port 80 and 443.

**Comment by ohemorange** [comment]
Is this still a problem when you apply #5192?

**Comment by bmw** [comment]
Yes. I was testing that PR when I came across this.
