### ISSUE TITLE
Another instance of Certbot is already running.

### ISSUE THREAD

**Issue by BevanH** [certbot/certbot#5200]
## My operating system is (include version):
AWS -Amazon Linux

## I ran this command and it produced this output:
letsencrypt-auto --debug

## Certbot's behavior differed from what I expected because:

Requesting to rerun ./letsencrypt-auto with root privileges...
Another instance of Certbot is already running.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
1-58-100 letsencrypt]$ ./letsencrypt-auto --debug
Requesting to rerun ./letsencrypt-auto with root privileges...
Bootstrapping dependencies for Amazon... (you can skip this with --no-bootstrap)
yum is /usr/bin/yum
Loaded plugins: priorities, update-motd, upgrade-helper
amzn-main                                                | 2.1 kB     00:00
amzn-updates                                             | 2.5 kB     00:00
Package gcc-4.8.5-1.22.amzn1.noarch already installed and latest version
Package augeas-libs-1.0.0-5.7.amzn1.x86_64 already installed and latest version
Package 1:openssl-1.0.2k-7.103.amzn1.x86_64 already installed and latest version
Package 1:openssl-devel-1.0.2k-7.103.amzn1.x86_64 already installed and latest version
Package libffi-devel-3.0.13-16.5.amzn1.x86_64 already installed and latest version
Package system-rpm-config-9.0.3-42.28.amzn1.noarch already installed and latest version
Package ca-certificates-2015.2.6-65.0.1.16.amzn1.noarch already installed and latest version
Package python27-2.7.12-2.120.amzn1.x86_64 already installed and latest version
Package python27-devel-2.7.12-2.120.amzn1.x86_64 already installed and latest version
Package python27-virtualenv-15.1.0-1.14.amzn1.noarch already installed and latest version
Package python27-tools-2.7.12-2.120.amzn1.x86_64 already installed and latest version
Package python27-pip-9.0.1-1.24.amzn1.noarch already installed and latest version
Nothing to do
Creating virtual environment...
Installing Python packages...
Installation succeeded.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator apache, Installer apache

Which names would you like to activate HTTPS for?
-------------------------------------------------------------------------------

**Comment by BevanH** [comment]
How do I stop "Another instance of Certbot is already running"?

**Comment by bmw** [comment]
You need to kill or wait for other Certbot processes running on your machine to finish. I suspect if you try running `letsencrypt-auto` again, you won't have this problem, but if you do, run `pgrep letsencrypt,certbot` to get the process ID of the running instances or `pkill letsencrypt,certbot` to just kill them.

**Comment by BevanH** [comment]
Thanks Brad.  It's done.
