### ISSUE TITLE
Running with invalid parameters causes program to hang for an extended period of time.

### ISSUE THREAD

**Issue by popey456963** [certbot/certbot#5206]
## My operating system is (include version):
Ubuntu, 16.04.

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Apt Package Manager

## I ran this command and it produced this output:
```
$ sudo certbot --apache2
(... 30 seconds later)
certbot: error: unrecognized arguments: --apache2
```

## Certbot's behavior differed from what I expected because:
It took nearly half a minute to error out.

**Comment by bmw** [comment]
Strange! The flag is `--apache` and the Apache plugin needs to be installed for it to work, but it certainly shouldn't take 30 seconds to error out.

Can you run `python -m cProfile -o <output file name> $(which certbot) --apache2` (replacing <output file name> with an arbitrary file name) and give me the resulting file? This profiles the command so I can see where Certbot is hanging.

**Comment by popey456963** [comment]
Woops, sorry for the long reply.  Found out it was an issue with the service provider, they were having disk issues which resulted in the application taking a significantly longer time than expected.
