### ISSUE TITLE
Improve UX for users who request more than 300 domains in a single cert

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5208]
Let's Encrypt has a limit of 100 names per cert and 300 pending authorizations per account. Currently nothing in Certbot prevents you from making a request for 300+ domains though. If a user does this, Certbot creates as many authorizations as it can, gets rate limited, and exits with a message about too many pending authorizations which doesn't describe the root problem here.

We should see if we can improve this. Really what we'd like to happen is to error early and say that you are trying to include too many names in the cert. While writing code to error at more than 100 names is trivial, this number is specific to Let's Encrypt policy, not in the ACME spec, and could change at any time. As versions of Certbot get entombed in Linux distros that are hesitant to do upgrades, a hard limit like this would prevent Certbot users from issuing certs that the CA would otherwise accept.

While it's not immediately clear how to fix this, luckily this problem will be resolved in the new version of the ACME protocol Let's Encrypt is launching in January. In the current ACME flow, the client doesn't tell the server what names it wants in a cert until the end of the process. In the new ACME flow, this is given to the server first so the server can reject the request for a cert with too many names before any authorizations are created.

If we can reasonably and easily fix this in the current protocol we should, but it's not immediately clear how to do this and the problem will be going away soon anyway.

**Comment by ahaw021** [comment]
limits could be published in a JSON API end point? Though not part of the ACME spec it would solve some of the problems with changing policy (e.g. this and the number of unique certificates per week)

**Comment by jsha** [comment]
I think it would be reasonable for Certbot to say it refuses to manage certificates with >100 domains, regardless of provider. Such large certificates are harmful to the ecosystem, and also probably tickle untested areas of Certbot's code, in terms of performance.

**Comment by bmw** [comment]
I'm interested to know how certs with >100 domains is harmful, but my preference is we do nothing here and just have this be resolved for most users when we switch the default to ACMEv2 which we're planning to do in our release in a couple weeks. With this approach, Certbot will fail fast by default, but for the few users who specify a different ACME server URL, it still allows them to make the requests they want and let the CA to decide whether they're willing to issue.

**Comment by jsha** [comment]
> I'm interested to know how certs with >100 domains is harmful

Mainly it bloats TLS handshakes, which makes HTTPS potentially a lot slower. Secondarily, most hosting providers that try to squeeze everyone onto 100-SAN certificates find that it causes a lot of renewal hassles, as domains leave their service, or have CAA problems or other issues.

**Comment by bmw** [comment]
I think things have been improved here with ACMEv2 and no one has requested this feature but me so I'm closing this issue.
