### ISSUE TITLE
Ability to specify "flags" in renew configuration

### ISSUE THREAD

**Issue by stevenproctor** [certbot/certbot#5210]
## My operating system is (include version):
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```
## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
`apt-get install certbot`

## I ran this command and it produced this output:

I installed the `certbot-dns-cloudflare` plugin, and updated the renew configuration for the certificates to include:
```
[renewalparams]
authenticator = dns-cloudflare
```

When I run `certbot renew --dry-run` it fails renewing that certificate grouping with

```
unexpected error: Missing command line flag or config entry for this setting:
Input the path to your Cloudflare credentials INI file. Skipping.
```

If I pass in the flags on the command line during renew like so:
```
certbot renew --dry-run --dns-cloudflare-credentials <path to ini file>
```
the renew succeeds.

## Certbot's behavior differed from what I expected because:

I was hoping that there would be an ability to specify flags in the `renewparams` so that those flags only get applied to the certificate set that I am renewing instead of being applied globally.

## Possible feature idea to address the issue

In the `renewal.py` code, there is the list of configuration settings.

```
STR_CONFIG_ITEMS = ["config_dir", "logs_dir", "work_dir", "user_agent",
                    "server", "account", "authenticator", "installer",
                    "standalone_supported_challenges", "renew_hook",
                    "pre_hook", "post_hook", "tls_sni_01_address",
                    "http01_address"]
```

Is there a possibility that there could be something like a `"flags"` entry, that would then take any other command line arguments in that `flags` entry that only applies to that configuration?

Doing so could allow users to do something like the following, and it would seem to be generic enough to be applicable to any other plugin besides the `dns-cloudflare` plugin that I am using:

```
[renewalparams]
authenticator = dns-cloudflare
flags = "--dns-cloudflare-credentials <path to ini file>"
```

**Comment by bmw** [comment]
If you (re)issue a certificate using the the Cloudflare plugin, this should be automatically added be added to the renewal configuration file. Alternatively, you can add the line yourself. It would look like:
```
[renewalparams]
dns_cloudflare_credentials = /path/to/credentials/file
```

**Comment by stevenproctor** [comment]
Adding that setting manually worked for me.  I was trying to guess that setting before and doing a `--dry-run` but it kept failing, but this took, both on the `--dry-run` and `--force-renewal`

Thanks!!

**Comment by stevenproctor** [comment]
You solved my problem, so please feel free to close this issue if desired.

**Comment by bmw** [comment]
Great! Glad I could help.

**Comment by stevenproctor** [comment]
Thank you and the team for LetsEncrypt/Certbot!!!
