### ISSUE TITLE
allow for java keystore as output format ".jks"

### ISSUE THREAD

**Issue by ralfhauser** [certbot/certbot#5212]
## My operating system is (include version):
Debian stable

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
yes

Manually, I use openssl to convert the pem into a .pfx / .p12 and then I import it manually with
http://keystore-explorer.org/ into a java keystore

Goal: if java is installed, the certbot should offer to do this automatically

**Comment by bmw** [comment]
This is very closely related to #506 and #1701.

**Comment by schoen** [comment]
I'll consider this a duplicate of #1701.
