### ISSUE TITLE
Unable to "renew"

### ISSUE THREAD

**Issue by GildedHonour** [certbot/certbot#5213]
Trying to renew:

```
sudo /usr/bin/certbot renew --quiet --nginx        
WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/my_website.com.conf produced an unexpected error: The requested nginx plugin does not appear to be installed. Skipping.    

```
In the log:

`      PluginSelectionError: The requested nginx plugin does not appear to be installed
`

How to install a plugin for nginx? None of these works:

```
apt-get install python3-certbot-nginx
apt-get install python-certbot-nginx
apt-get install python-letencrypt-nginx


```
Not found.

**Comment by SwartzCr** [comment]
Sorry to hear about the issue, can you tell me:
- what version of certbot you have installed
- what OS and OS version you have
- what version of nginx you have installed

If you're on debian/ubuntu it really should be called python-certbot-nginx, but you might need to enable backports to get it

**Comment by adferrand** [comment]
This issue has not been updated for a long time, while info is required to move on. So I assume it is solved, or not relevant anymore. If not, do not hesitate to reopen an issue with updated info about its context.
