### ISSUE TITLE
Provide instructions when single domain fails

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#5217]
Steps to reproduce:

Set up Certbot with a single certificate containing two names. Remove one of the names from the config. Sixty days later, run `certbot -q renew`. Output:

```
Attempting to renew cert (metrics.crud.net) from /etc/letsencrypt/renewal/metrics.crud.net.conf produced an unexpected error: Cannot find a VirtualHost matching domain metrics.crud.net. In order for Certbot to correctly perform the challenge please add a corresponding server_name directive to your nginx configuration: https://nginx.org/en/docs/http/server_names.html. Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/metrics.crud.net/fullchain.pem (failure)
```

I also ran `certbot certificates`:

```
-------------------------------------------------------------------------------
Found the following certs:
  Certificate Name: metrics.crud.net
    Domains: grafana.crud.net metrics.crud.net
    Expiry Date: 2017-11-02 23:41:00+00:00 (INVALID: EXPIRED)
    Certificate Path: /etc/letsencrypt/live/metrics.crud.net/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/metrics.crud.net/privkey.pem
-------------------------------------------------------------------------------
```

In my opinion, both of these places should include instructions on how to delete a name from a certificate so that it can be renewed. For instance "If you no longer need a certificate for X, run Y. If you still need a certificate for X, edit your (Nginx|Apache) configs to add a server_name directive for it."

I believe the right option here is `--allow-subset-of-names`. However, running `certbot renew --allow-subset-of-names` produces the same error above. Any advice on how best to remove a name from a certificate?

**Comment by TheNavigat** [comment]
Shouldn't `--allow-subset-of-names` avoid failing in that case? That's from a logical point of view. not an "is there a bug?" point of view. If you agree that it should, maybe we should make it do that.

**Comment by jsha** [comment]
Yep, I agree that it should work, but I wasn't sure if I was just misunderstanding, or if it was a legit bug. BTW, I still have this server setup if anyone would like me to test things.

**Comment by adferrand** [comment]
This issue has not been updated for a long time, and a solution has been proposed. So I assume it is solved, or not relevant anymore. If not, do not hesitate to reopen an issue with updated info about its context.
