### ISSUE TITLE
Azure DNS auth

### ISSUE THREAD

**Issue by eduvik** [certbot/certbot#5218]
Apologies if this is the wrong place to put this, but I'm seeking some clarification on development guidelines.

I've created a plugin for Azure DNS auth at https://github.com/askvictor/certbot/tree/feature/azure-dns but haven't created any tests for it. I've done some manual tests and have successfully created some certs. However, I was wanting to write some tests before submitting a PR, but have no idea what constitutes a useful test in this situation - how do you test the response from a cloud service the requires a subscription and credentials?

**Comment by joohoi** [comment]
I think the correct approach here would be mocking the API responses. [dns-cloudflare plugin tests](https://github.com/certbot/certbot/blob/master/certbot-dns-cloudflare/certbot_dns_cloudflare/dns_cloudflare_test.py) have a good example of how to accomplish that, solving the exact same issue.

**Comment by elmariofredo** [comment]
@eduvik thanks for adding azure-dns support! Just is there any trick how to make you branch working? After successful build it will return following:

```
usage:
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate.
certbot: error: unrecognized arguments: --dns-azure-credentials /azure.json --dns-azure-resource-group res
```
Thanks!

**Comment by elmariofredo** [comment]
@eduvik AWESOME! It's working sorry didn't realised that I have to explicitly build `certbot-dns-azure` plugin, for others struggling see my Dockerfile diff below.

If you want I can try to add tests as per @joohoi suggestion.

Let me know

Cheers!

```diff
diff --git a/Dockerfile b/Dockerfile
index cf4e9afa..213cbe6a 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -8,6 +8,7 @@ WORKDIR /opt/certbot
 COPY CHANGES.rst README.rst setup.py src/
 COPY acme src/acme
 COPY certbot src/certbot
+COPY certbot-dns-azure src/certbot-dns-azure

 RUN apk add --no-cache --virtual .certbot-deps \
         libffi \
@@ -24,4 +25,6 @@ RUN apk add --no-cache --virtual .build-deps \
     && pip install --no-cache-dir \
         --editable /opt/certbot/src/acme \
         --editable /opt/certbot/src \
+        --editable /opt/certbot/src/certbot-dns-azure \
+        httplib2 \
     && apk del .build-deps
```

**Comment by eduvik** [comment]
@elmariofredo Glad to see you got it working. I've changed jobs recently and don't have any need for this anymore, nor any time to work on it unfortunately. Feel free to add tests, or indeed to take over this little part of the project.

Cheers,

**Comment by elmariofredo** [comment]
Ok will try to do my best, WIP PR here #5560

Cheers 🍻
