### ISSUE TITLE
Add an indentation optional flag?

### ISSUE THREAD

**Issue by lwm** [certbot/certbot#5223]
It kinda helps me to read my nginx configuration if certbot uses the same indentation level. For example, I typically use a 2 space indentation level and certbox comes along and smashes it with 4 spaces ;). I propose to add a `--indent=<INT>` flag so that we can set this from the CLI. As far as I can see, this isn't available? Will submit a PR if we're agreed.

**Comment by joohoi** [comment]
I believe this is for Nginx plugin? Apache plugin uses Augeas, which does'nt have a simple option for indentation.

Additional idea: automatically detecting the indentation level when parsing the file. As you might know, we have quite a lot of CLI parameters already.

**Comment by lwm** [comment]
Hey, yes, it's for the nginx plugin. I like your idea, I think it would be a good one, as far as I saw, different options specified from command line even end up with different indentation, so this might be a better solution. Shall I try to submit a PR?

**Comment by joohoi** [comment]
By all means! I think that'd be very useful to maintain configuration file readibility.

**Comment by ohemorange** [comment]
Hi! Thanks for jumping in on this one, this would be a great improvement. I agree that automatically detecting indentation is the correct way. It might be a bit tricky given our current way of parsing, so let me know if you run into any complications.

**Comment by ohemorange** [comment]
This is a duplicate of https://github.com/certbot/certbot/issues/5157

**Comment by lwm** [comment]
Ah, will close then! Still didn't get around to this though .... some time soon!

**Comment by lwm** [comment]
Got started but there are questions, of course ;) Please give a look at #5157 if you have time!
