### ISSUE TITLE
add a sign or expiration date to the list, where I select a server for new certs

### ISSUE THREAD

**Issue by Hinnack** [certbot/certbot#5224]
if I run ./certbot-auto I get the list of domains but all domains are listed and I do not know, if that server already has a cert
at least for apache on debian

**Comment by SwartzCr** [comment]
Can you elaborate? Do you want to know which domains don't already have certificates issued for them?

**Comment by Hinnack** [comment]
yes, that would be helpful

**Comment by SwartzCr** [comment]
I believe you can get the information you want from the `certbot certificates` command.
See this documentation for more information: https://certbot.eff.org/docs/using.html#managing-certificates
