### ISSUE TITLE
Timeout when try to get certifacation or renew with webroot

### ISSUE THREAD

**Issue by CordlessWool** [certbot/certbot#5231]
## My operating system is (include version):
Official docker container  

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Docker container

## I ran this command and it produced this output:
it gives a timeout and says that it could not verify the address, but I get it with standalone and do not find the error message anymore

## Certbot's behavior differed from what I expected because:
I have a server with A records there it works also with nginx but on my server at home, have c records it do not work with nginx but with standalone

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
location /.well-known/acme-challenge {
		root /var/www/html/certbot/;
  }

**Comment by SwartzCr** [comment]
Are you able to navigate to that endpoint when running the webroot challenge?
Is there a reason that you don't want to use the nginx plugin directly?

**Comment by CordlessWool** [comment]
yes I try it with a file and it works, configuration is also nearly the same to the other server. I shortly try to use the nginx plugin, but nginx and lets encrypt are to different container. I share volumes-from the nginx docker but it told me: 

> Could not choose appropriate plugin: The requested nginx plugin does not appear to be installed
> The requested nginx plugin does not appear to be installed

**Comment by SwartzCr** [comment]
Would you be able to paste the exact timeout error message here, or even better share the whole log from a failed run?

**Comment by CordlessWool** [comment]
Have to wait till one certificate expire, because there are all not need to renew now I do not get a error message

**Comment by SwartzCr** [comment]
you can use the `--force-renewal` flag to trigger renewal for domains not in their renewal window, but if you'd like to wait for this to naturally occur again, I'm happy to wait until

**Comment by CordlessWool** [comment]
Cert not due for renewal, but simulating renewal for dry run
Plugins selected: Authenticator webroot, Installer None
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for sub.domain.tld
Using the webroot path /var/www for all unmatched domains.
Waiting for verification...
Cleaning up challenges
Unable to clean up challenge directory /var/www/.well-known/acme-challenge
[31mAttempting to renew cert (sub.domain.tld) from /etc/letsencrypt/renewal/sub.domain.tld.conf produced an unexpected error: Failed authorization procedure. sub.domain.tld (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://sub.domain.tld/.well-known/acme-challenge/tin63dHOU_vfyy3FC7fN-DPL7_gVHdLnlqHDl1JMob0: Timeout. Skipping.[0m




1 renew failure(s), 0 parse failure(s)
[1m
IMPORTANT NOTES:
[0m - The following errors were reported by the server:

   Domain: sub.domain.tld
   Type:   connection
   Detail: Fetching
   http://sub.domain.tld/.well-known/acme-challenge/tin63dHOU_vfyy3FC7fN-DPL7_gVHdLnlqHDl1JMob0:
   Timeout

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
Build step 'Execute shell' marked build as failure
Sending e-mails to: ....
Finished: FAILURE

**Comment by SwartzCr** [comment]
A question:
Are you running nginx in the same container that you're running certbot? If not you may want to use the commands in this community forum post as a guide for how to properly set-up webroot: https://community.letsencrypt.org/t/what-would-you-want-from-a-certbot-docker-image/21471
Did you get your certificate initially with webroot?
If that post doesn't help you - it would be useful for me to see a full certbot log, rather than just the command line output

**Comment by CordlessWool** [comment]
Nginx and certbot runs in different container and both container have access to the same file. Initially brings the same error, I remember it worked one time in the past and I also initially it via webroot, but some time after I set up a cronjob it stops working. I have an other server, there it works... only different should be that the other server has an A record and do not need cname... and there also less urls. how do I get log file?

**Comment by CordlessWool** [comment]
ok I get it and found following error in the log file. I try it some times before I got it. But command line output also had showing the timeout error after I get the log file - if this is necessary. 

2017-11-29 18:59:58,336:WARNING:certbot.renewal:Attempting to renew cert (url) from /etc/letsencrypt/renewal/url.conf produced an unexpected error: urn:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new authz :: Too many failed authorizations recently.. Skipping.
2017-11-29 18:59:58,340:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/renewal.py", line 425, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/opt/certbot/src/certbot/main.py", line 743, in renew_cert
    _get_and_save_cert(le_client, config, lineage=lineage)
  File "/opt/certbot/src/certbot/main.py", line 80, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/opt/certbot/src/certbot/renewal.py", line 297, in renew_cert
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/client.py", line 318, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/auth_handler.py", line 66, in get_authorizations
    self.authzr[domain] = self.acme.request_domain_challenges(domain)
  File "/opt/certbot/src/acme/acme/client.py", line 212, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authzr_uri)
  File "/opt/certbot/src/acme/acme/client.py", line 191, in request_challenges
    response = self.net.post(self.directory.new_authz, new_authz)
  File "/opt/certbot/src/acme/acme/client.py", line 682, in post
    return self._post_once(*args, **kwargs)
  File "/opt/certbot/src/acme/acme/client.py", line 695, in _post_once
    return self._check_response(response, content_type=content_type)
  File "/opt/certbot/src/acme/acme/client.py", line 582, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new authz :: Too many failed authorizations recently.

**Comment by SwartzCr** [comment]
So that error is from a ratelimit from acme. It's because you've had too many recent failed attempts. It'll last 1 hour, and then you should be able to try again.
In order to not run into that problem again, I'd recommend using the staging server until you get your issue resolved.
To do this you should use the `--staging` flag when running certbot until you get a success. The certificate that you receive won't be trusted in browsers, so afterwards you'll have to run it again without the `--staging` flag, but this will prevent you from getting rate limited again. You can find out more about this in the testing section of certbot help: https://certbot.eff.org/docs/using.html#certbot-command-line-options
As for fixing your initial issue, you should really make sure that certbot is able to create or use a webroot directory that your nginx docker has access to. You may want to make use of the `--webroot-path` flag when running certbot again, or reading the instructions that I linked to before.

**Comment by CordlessWool** [comment]
Here is the log information, I do not get more information as before, but maybe you will find something.
Also the command I used till now. The nginx container has also access to the ...html/certbot directory as you see above at the nginx conf snipped. 

docker run -t --rm \
 -v "/etc/letsencrypt:/etc/letsencrypt" \
 -v "/var/www/html/certbot:/var/www" \
 certbot/certbot:latest renew --webroot --webroot-path "/var/www" --rsa-key-size 4096
 
[certbot.log](https://github.com/certbot/certbot/files/1515709/certbot.log)

**Comment by SwartzCr** [comment]
Can you try running it again with the `--debug-challenges` flag? It will pause after setting up the challenge but before contacting the CA. You should then be able to try to navigate to the .well-known url and see if you can see the challenge. If you can't then there is an issue with how webroot is working.

**Comment by CordlessWool** [comment]
ok, I do not get a link on which I could click on. But I enter the nginx container and saw the challenge in the "acme-challenge" directory

**Comment by SwartzCr** [comment]
I would navigate to: http://sub.domain.tld/.well-known/acme-challenge
and see if it resolves

**Comment by CordlessWool** [comment]
ok I activate autoindex and open the file, inside the file is a hash. some big and small letter, numbers and the signs _ . -

**Comment by SwartzCr** [comment]
Okay - can you compare the URL that you use to see the file to the URL that certbot logs in it's output?

**Comment by CordlessWool** [comment]
Yes both looks totally the same

**Comment by SwartzCr** [comment]
And you're still getting the timeout error?

**Comment by CordlessWool** [comment]
yes, I also do not understand

**Comment by SwartzCr** [comment]
Would you be able to give me a complete log from certbot, not a truncated one?
You're welcome to email it to me at noah@eff.org if you don't want to post it. Preferably send me the one of your most recent failure.

**Comment by bmw** [comment]
If you're still having validation issues, please go to https://community.letsencrypt.org where there is a large group of people who would be happy to help you.
