### ISSUE TITLE
Certbot dieing with "does not match current agreement"

### ISSUE THREAD

**Issue by nigel-aves** [certbot/certbot#5240]
## My operating system is (include version):

CentOS Linux 7.4.1708

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

yum install certbot-apache
( python2-certbot-apache-0.19.0-1.el7.noarch)

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
Parsing account key...
Parsing CSR...
Registering account...
Traceback (most recent call last):
  File "/usr/libexec/webmin/webmin/acme_tiny.py", line 235, in <module>
    main(sys.argv[1:])
  File "/usr/libexec/webmin/webmin/acme_tiny.py", line 231, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, args.dns_hook, args.cleanup_hook, log=LOGGER, CA=args.ca)
  File "/usr/libexec/webmin/webmin/acme_tiny.py", line 106, in get_crt
    raise ValueError("Error registering: {0} {1}".format(code, result))
ValueError: Error registering: 400 {
  "type": "urn:acme:error:malformed",
  "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf]",
  "status": 400
}

Not sure what I should do. But I find it strange that the document is dated today (LE-SA-v1.2-November-15-2017.pdf).

**Comment by cpu** [comment]
Hi @nigel-aves,

> But I find it strange that the document is dated today (LE-SA-v1.2-November-15-2017.pdf).

Let's Encrypt did [change the agreement URL](https://community.letsencrypt.org/t/subscriber-agreement-update-november-15-2017/45607) today.

> File "/usr/libexec/webmin/webmin/acme_tiny.py", line 106, in get_crt

It looks like while you installed Certbot the actual error is coming from a Webmin plugin (?) called `acme-tiny.py`. This **isn't Certbot**! Unfortunately you'll likely have to raise this error with the maintainers of the Webmin plugin & `acme_tiny.py`.

If you can use Certbot it will handle the new terms of service agreement URL without error.

**Comment by cpu** [comment]
Hi @nigel-aves,

I found the Webmin repository with this buggy code and opened an issue for you: https://github.com/webmin/webmin/issues/699

I would recommend you subscribe to issue 699 on the Webmin repository to learn when this bug will be fixed.

I'm going to close this issue for now since it isn't a problem with Certbot.

Thanks for reporting!

**Comment by nigel-aves** [comment]
Thank you kindly ... Nigel.
