### ISSUE TITLE
redirect isn't properly handled

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#5245]
## My operating system is (include version):
ubuntu 16.04.3 xenial

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
ppa:certbot/certbot

## I ran this command and it produced this output:
```
certbot
```
```
Please choose whether or not to redirect HTTP traffic to HTTPS, removing HTTP access.
-------------------------------------------------------------------------------
1: No redirect - Make no further changes to the webserver configuration.
2: Redirect - Make all requests redirect to secure HTTPS access. Choose this for
new sites, or if you're confident your site works on HTTPS. You can undo this
change by editing your web server's configuration.
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 2
Enhancement redirect was already set.
```

## Certbot's behavior differed from what I expected because:
I had copied a file for `foo:80` and changed its host to `bar:80`, but the redirect was for `foo:80 -> foo:443`. It didn't write a redirect or warn that the redirect wouldn't work.
Expected: replace the unrelated redirect of `foo:80->foo:443` with one for `bar:80->bar:443`

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
```2017-11-16 20:55:06,383:DEBUG:certbot.reporter:Reporting to user: Some rewrite rules copied from /etc/apache2/sites-enabled/site.conf were disabled in the vhost for your HTTPS site located at /etc/apache2/sites-available/site-le-ssl.conf because they have the potential to create redirection loops.```
```
2017-11-16 20:55:13,259:WARNING:certbot.client:Enhancement redirect was already set.
```

**Comment by SwartzCr** [comment]
I'd have to look into the apache code to see why this happens, but it might be as simple as us doing dumb augeas matching?
@joohoi thoughts?

**Comment by adferrand** [comment]
As there is no response on both side since more than one year, I will close the issue. Do not hesitate to give update if there is still problems with Apache config parsing here.
