### ISSUE TITLE
Should we reissue a certificate if different attributes are requested?

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5249]
This was suggested [here](https://community.letsencrypt.org/t/certbot-how-can-i-renew-if-staging-certs-exist-but-i-want-production-certs/46472/8). I'm potentially OK with this change, but we should consider how/if we want to do this very carefully and what attributes we care about. Doing this complicates both our code and our explanation of how Certbot works. There will be some instances like those discussed in the linked forum post where this will be the behavior that is intuitive for people, but we should make sure this is the case and it won't negatively impact others in the future.

**Comment by barrychapman** [comment]
This would be infinitely useful

**Comment by sixthgear** [comment]
This would be very lovely for my ansible workflow.

**Comment by bmw** [comment]
I think it'd be beneficial for whoever works on this issue if users interested in it described their workflow where Certbot's current behavior could be improved by resolving this issue. If your workflow has more or less already been described please just +1 the GitHub comment if it exists or link to the post on Let's Encrypt's community forum to streamline the comments a bit.

**Comment by bmw** [comment]
I doubt we'll change this, but I hope https://github.com/certbot/certbot/pull/9355 which solved some related issues helps.
