### ISSUE TITLE
Logs and sensitive data

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#525]
We should make sure that logs do not contain sensitive data (such as private key contents). This is important, because people provide these logs for debugging purposes.

**Comment by bmw** [comment]
This is especially import as I will likely be writing functionality similar to `letshelp-letsencrypt` that gives people the option to bundle up their entire Let's Encrypt config, server config, and logs and send them to us. This allows us to more easily debug and fix problems people are having with the client.
