### ISSUE TITLE
Fail gracefully when file can't be written to

### ISSUE THREAD

**Issue by joohoi** [certbot/certbot#5250]
Add tests before trying to write files with augeas to catch situations like when we don't have write permission to a file. Fail early with informative error message.

Steps to reproduce:
`chattr +i /etc/apache2/apache2.conf`
`certbot --apache -d whatever.tld`

Ends up in #5251

**Comment by bmw** [comment]
We should definitely fix this, but I think the main reason this is bad is it ends up in #5251 which needs to be fixed on its own. If we just crashed saying we couldn't write to the file (maybe with a better error message?), I personally don't think that behavior is that bad.
