### ISSUE TITLE
Should be able to recover a situation where temporary checkpoint is out of sync with filesystem

### ISSUE THREAD

**Issue by joohoi** [certbot/certbot#5251]
If temp_checkpoint is out of sync with filesystem, in a way that prevents it copying backed up files back to their location, Certbot will fail to run, crashing with:

```
$ certbot --staging --apache          
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Unable to recover files from /var/lib/letsencrypt/temp_checkpoint
Incomplete or failed recovery for /var/lib/letsencrypt/temp_checkpoint
The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('Unable to revert temporary config',)
```

This situation is irrecoverable if `/var/lib/letsencrypt/temp_checkpoint` isn't deleted.

How to reproduce:
```
mkdir -p /var/lib/letsencrypt/temp_checkpoint
echo "/tmp/nonexistent_path" > /var/lib/letsencrypt/temp_checkpoint/FILEPATHS
certbot 
```
note that the above example fails because Certbot can't open the file to copy FROM `/var/lib/letsencrypt/temp_checkpoint/nonexistent_path_0`. The error however is identical if file can't be copied over the existing one, like the situation is with #5250

**Comment by marceloagil** [comment]
I'm having same issue. Ubuntu server.

**Comment by dreyTee** [comment]
Pretty similar symptoms:

`# certbot renew 
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/$TLD.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert is due for renewal, auto-renewing...
Unable to recover files from /var/lib/letsencrypt/temp_checkpoint
Incomplete or failed recovery for /var/lib/letsencrypt/temp_checkpoint
Attempting to renew cert ($TLD) from /etc/letsencrypt/renewal/$TLD.conf produced an unexpected error: Unable to revert temporary config. Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/$TLD/fullchain.pem (failure)
`
Manual deletion of /var/lib/letsencrypt/temp_checkpoint/* fixes process.

I suggest allowing user to start over w/o these files.
Let's ask user if he wants to start from the beginning (removing theses useless files)?
