### ISSUE TITLE
certbot-nginx asks about redirects even if Nginx has no port 80 block

### ISSUE THREAD

**Issue by randombit** [certbot/certbot#5253]
## My operating system is (include version):

Arch Linux (latest)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

From OS package manager. 

```
$ certbot --version
certbot 0.19.0
```

## I ran this command and it produced this output:

```
$ certbot --renew
... normal renewal output
Please choose whether or not to redirect HTTP traffic to HTTPS, removing HTTP access.
-------------------------------------------------------------------------------
1: No redirect - Make no further changes to the webserver configuration.
2: Redirect - Make all requests redirect to secure HTTPS access. Choose this for
new sites, or if you're confident your site works on HTTPS. You can undo this
change by editing your web server's configuration.
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 2
No matching insecure server blocks listening on port 80 found.
No matching insecure server blocks listening on port 80 found.
2017/11/21 11:11:54 [notice] 23645#23645: signal process started

-------------------------------------------------------------------------------
Your existing certificate has been successfully renewed, and the new certificate
has been installed.
```

## Certbot's behavior differed from what I expected because:

Since Nginx is not listening on port 80 at all, I would expect certbot to skip the question given its attempt to edit the server block will fail.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

```
    server {
        listen       443 ssl;
        server_name  practicalselfreliance.com www.practicalselfreliance.com;
ssl_certificate /etc/letsencrypt/live/practicalselfreliance.com/fullchain.pem; # managed by Certbot                                                                                   
ssl_certificate_key /etc/letsencrypt/live/practicalselfreliance.com/privkey.pem; # managed by Certbot                                                                                 

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  15m;

        ssl_ciphers  HIGH:!aNULL;
        #ssl_prefer_server_ciphers  on;                                                                                                                                               

        #access_log  logs/host.access.log  main;                                                                                                                                      

        location / {

            proxy_pass            http://127.0.0.1:80;
            proxy_read_timeout    10;
            proxy_connect_timeout 10;
            proxy_redirect        off;

            proxy_set_header      X-Real-IP $remote_addr;
            proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header      X-Forwarded-Proto https;
            proxy_set_header      X-Forwarded-Port 443;
            proxy_set_header      Host $host;
            }

        #error_page  404              /404.html;                                                                                                                                      

        # redirect server error pages to the static page /50x.html                                                                                                                    
        #                                                                                                                                                                             
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
```
## Further Background

Nginx is acting as a TLS terminator in front of Varnish which in turns talks to Apache/PHP/Wordpress. Varnish handles port 80, and HTTP->HTTPS redirects are done using a VCL rule. The setup is basically as described in https://www.smashingmagazine.com/2015/09/https-everywhere-with-nginx-varnish-apache/

It would be nice if certbot-nginx would detect this situation (at least to the extent that it would realize nginx isn't configured to listen on port 80, and thus its attempt to modify the server block will fail anyway) and skip the question.

**Comment by SwartzCr** [comment]
@ohemorange any thoughts? This seems like a reasonable, though not pressing, ui fix

**Comment by ohemorange** [comment]
This is reasonable from the UI side, but would require restructuring the way we handle security enhancement to dynamically provide this information.

Tagging @bmw because he's working on restructuring that workflow and this use case might factor into considerations.

**Comment by bmw** [comment]
Hm. I wasn't planning on changing any existing enhancements as the system that I'm working on is specifically for enhancements that require ongoing maintenance instead one time things like setting up a redirect but I'll keep this in mind.

This issue would also be resolved if the problem originally described in #3550 is fixed.

**Comment by ohemorange** [comment]
I don't think it would; we don't create a new port 80 block if one doesn't exist, and we'll still be asking if they want a redirect enhancement.

**Comment by bmw** [comment]
I know your PR doesn't currently do this, but the plan to "create a new block, listen plaintextishly, and add a redirect statement to that block" would resolve it.

**Comment by ohemorange** [comment]
So first, that's when there are *no* matching server blocks. Here, there is one, just only a 443 one, in which case we wouldn't create a new plaintext server block.

Second, I haven't responded to those comments yet -- I think that though the issue originally said that, that's a bad idea and we shouldn't be adding plaintextish blocks where none exist.

**Comment by bmw** [comment]
First, that's not my reading of the initial issue an our conversation there and second, happy to talk to you about it more on your PR.

**Comment by ohemorange** [comment]
I'm closing this because I think we're unlikely to ever address it.
