### ISSUE TITLE
certbot complains about nAAAA records after reboot but 2nd attempt works fine

### ISSUE THREAD

**Issue by toralf** [certbot/certbot#5254]
[letsencrypt.log](https://github.com/certbot/certbot/files/1492630/letsencrypt.log)
## My operating system is (include version):
stable Gentoo linux

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Gentoo package manager

## I ran this command and it produced this output:
/usr/bin/certbot renew --max-log-backups 5 --standalone --non-interactive --text 
The cert if for my jabber server, therefore I have a script which runs
    /usr/bin/certbot renew --max-log-backups 5 --standalone --non-interactive --text
    cat /etc/letsencrypt/live/jabber.zwiebeltoralf.de/{privkey,fullchain}.pem > $pem
after rboot

## Certbot's behavior differed from what I expected because:
times out immediately in reboot if called from script, works fine if running at the command line

**Comment by toralf** [comment]
FWIW a has nothing to do with reboot.
When I delete the current valid cert data (pem, csr, keys) and set the symlinks appropriately and rerun by script, then it fails at every 2nd attempt or so.
Attached is the debug log where it works fine, the difference is (not surprisingly) 
{{
b'{\n  "type": "tls-sni-01",\n  "status": "valid",\n 
}}
versus
{{
b'{\n  "type": "tls-sni-01",\n  "status": "pending",\n 
[letsencrypt-ok.log](https://github.com/certbot/certbot/files/1492874/letsencrypt-ok.log)

}}

**Comment by joohoi** [comment]
Could the issue be that one (or more) of nameservers of your domain have dysfunctional AAAA record in place? AFAIK Let's Encrypt uses one of the authoritative nameservers, but not always the first one.

**Comment by toralf** [comment]
Hhm, I do use dnsmasq with DNSSEC here using
`
# grep ^server /etc/dnsmasq.conf 
server=2a01:4f8:0:a0a1::add:1010
server=2a01:4f8:0:a102::add:9999
server=2a01:4f8:0:a111::add:9898
server=213.133.98.98
server=213.133.99.99
server=213.133.100.100
`
didn't realized bigger issues here till now.

**Comment by toralf** [comment]
But well, I do donder why the 2nd call of dig gave less information than the 1st
`
mr-fox ~ # /etc/init.d/dnsmasq restart
 * Stopping dnsmasq ...                                                                                                               [ ok ]
 * Starting dnsmasq ...                                                                                                               [ ok ]
mr-fox ~ # dig letsencrypt.com +dnssec                                                                          
                                                                                                                
; <<>> DiG 9.11.1-P3 <<>> letsencrypt.com +dnssec                                                               
;; global options: +cmd                                                                                         
;; Got answer:                                                                                                  
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42602                                                                   
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 5, ADDITIONAL: 1                                                        
                                                                                                                                            
;; OPT PSEUDOSECTION:                                                                                                                       
; EDNS: version: 0, flags: do; udp: 4096                                                                                                    
;; QUESTION SECTION:                                                                                                                        
;letsencrypt.com.               IN      A                                                                                                   
                                                                                                                                            
;; ANSWER SECTION:                                                                                                                          
letsencrypt.com.        1751    IN      A       192.64.119.63                                                                               
                                                                                                                                            
;; AUTHORITY SECTION:                                                                                                                       
letsencrypt.com.        1751    IN      NS      dns4.registrar-servers.com.
letsencrypt.com.        1751    IN      NS      dns3.registrar-servers.com.
letsencrypt.com.        1751    IN      NS      dns5.registrar-servers.com.
letsencrypt.com.        1751    IN      NS      dns1.registrar-servers.com.
letsencrypt.com.        1751    IN      NS      dns2.registrar-servers.com.

;; Query time: 6 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Nov 21 23:55:03 CET 2017
;; MSG SIZE  rcvd: 173

mr-fox ~ # dig letsencrypt.com +dnssec 

; <<>> DiG 9.11.1-P3 <<>> letsencrypt.com +dnssec
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57634
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;letsencrypt.com.               IN      A

;; ANSWER SECTION:
letsencrypt.com.        1750    IN      A       192.64.119.63

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Nov 21 23:55:04 CET 2017
;; MSG SIZE  rcvd: 60

`

**Comment by joohoi** [comment]
According to logs (both, working and non-working ones) your server seems to be receiving quite a lot of DDoS looking traffic to port 443.
```
2017-11-21 20:21:16,710:DEBUG:acme.crypto_util:Performing handshake with ('::ffff:51.15.52.120', 34370, 0, 0)
2017-11-21 20:21:16,713:DEBUG:acme.crypto_util:Server name (b'www.buxmqn7xxscm.com') not recognized, dropping SSL
2017-11-21 20:21:16,739:DEBUG:acme.crypto_util:Performing handshake with ('::ffff:91.219.29.238', 51880, 0, 0)
2017-11-21 20:21:16,740:DEBUG:acme.crypto_util:Server name (b'www.7tttg3bl4j77.com') not recognized, dropping SSL
2017-11-21 20:21:17,332:DEBUG:acme.crypto_util:Performing handshake with ('::ffff:176.122.120.71', 32814, 0, 0)
2017-11-21 20:21:17,465:DEBUG:acme.crypto_util:Server name (b'www.qn7esykfe7a6p2moih2kdz.com') not recognized, dropping SSL
2017-11-21 20:21:17,466:DEBUG:acme.crypto_util:Performing handshake with ('::ffff:5.148.175.35', 47436, 0, 0)
2017-11-21 20:21:17,467:DEBUG:acme.crypto_util:Server name (b'www.xpe4nv7t4n4r.com') not recognized, dropping SSL
2017-11-21 20:21:17,467:DEBUG:acme.crypto_util:Performing handshake with ('::ffff:79.137.106.154', 32817, 0, 0)
2017-11-21 20:21:17,468:DEBUG:acme.crypto_util:Server name (b'www.75cdjnkhhvmvcj2w37.com') not recognized, dropping SSL
2017-11-21 20:21:17,575:DEBUG:acme.crypto_util:Performing handshake with ('::ffff:128.31.0.39', 44778, 0, 0)
2017-11-21 20:21:17,576:DEBUG:acme.crypto_util:Server name (b'www.v23rakqqmfirztfj.com') not recognized, dropping SSL
2017-11-21 20:21:17,651:DEBUG:acme.crypto_util:Performing handshake with ('::ffff:163.172.210.167', 58008, 0, 0)
2017-11-21 20:21:17,695:DEBUG:acme.crypto_util:Server name (b'www.btxaocfxgsorgubupv6ovzp.com') not recognized, dropping SSL
2017-11-21 20:21:17,713:DEBUG:acme.crypto_util:Performing handshake with ('::ffff:173.255.229.194', 54466, 0, 0)
2017-11-21 20:21:17,714:DEBUG:acme.crypto_util:Server name (b'www.5uvhoqm.com') not recognized, dropping SSL
2017-11-21 20:21:17,777:DEBUG:acme.client:Sending GET request to https://acme-v01.api.letsencrypt.org/acme/authz/3E9NZ2KBf8ps_5WQOzI03xcB9Us3d8b4Jf5xghtEYqM.
2017-11-21 20:21:17,830:DEBUG:acme.crypto_util:Performing handshake with ('::ffff:62.141.48.175', 38167, 0, 0)
2017-11-21 20:21:17,831:DEBUG:acme.crypto_util:Server name (b'www.nm4up2paynoxc64.com') not recognized, dropping SSL
```

These could be blocking the actual validation request.

**Comment by toralf** [comment]
well, this is a fast Tor exit node - so not surprising.
It would help if certbot would accept different ports than 443 and 80.

**Comment by schoen** [comment]
@toralf, are you still having trouble related to this (particularly now that the TLS-SNI-01 challenge is no longer supported by Let's Encrypt)?

**Comment by toralf** [comment]
Well, can't tell, the old hardware is gone and at the new I didn't have a ACME client

**Comment by schoen** [comment]
Thanks, sorry that we weren't able to help you more while it was relevant to your setup!
