### ISSUE TITLE
Error certbot-auto renew Ubuntu Xenial

### ISSUE THREAD

**Issue by flymikeG** [certbot/certbot#5265]
## My operating system is (include version):
Ubuntu Xenial (upgraded from Trusty)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
as per https://certbot.eff.org/#ubuntuxenial-apache

## I ran this command and it produced this output:
```
(via root cron) /usr/local/sbin/certbot-auto renew >> /var/log/le-renew.log
Error: couldn't get currently installed version for /opt/eff.org/certbot/venv/bin/letsencrypt: 
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/main.py", line 11, in <module>
    from acme import jose
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/OpenSSL/crypto.py", line 1, in <module>
    import datetime
ImportError: **No module named datetime**
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring

The solution in [Issue 4776](https://github.com/certbot/certbot/issues/4776) did not work for me

Here's the output of the command requested by yan12125 in that Issue:
```
root@neely:/home/flymike# source /root/.local/share/letsencrypt/bin/activate
(venv)root@neely:/home/flymike# python2 -c 'import sys; print(sys.path)'
['', '/opt/eff.org/certbot/venv/lib/python2.7', '/opt/eff.org/certbot/venv/lib/python2.7/plat-x86_64-linux-gnu', '/opt/eff.org/certbot/venv/lib/python2.7/lib-tk', '/opt/eff.org/certbot/venv/lib/python2.7/lib-old', '/opt/eff.org/certbot/venv/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages', '/opt/eff.org/certbot/venv/lib/python2.7/site-packages']
(venv)root@neely:/home/flymike# deactivate
root@neely:/home/flymike# python2 -c 'import datetime; print(datetime)'
<module 'datetime' (built-in)>
```

**Comment by SwartzCr** [comment]
Hmm, what if you run that same command on the `/opt/eff.org/certbot/venv/`?
It seems that you might have two venvs for certbot.
Also I believe our instructions recommend installing certbot from the PPA, but it seems that you're running `certbot-auto` - is that what the instructions suggested when you first followed them? Or do you also have a system packaged version of certbot installed?

**Comment by flymikeG** [comment]
Sorry, I don't know what is meant by "run that same command on /opt/eff.org/certbot/venv/".
The original installation was from the PPA - but on Ubuntu Trusty - which has now been upgraded to Xenial.
How can I clean up and reinstall on Xenial without losing my certificates?

**Comment by SwartzCr** [comment]
As long as you don't run `apt-get --purge` you should be fine. The relevant cert files are stored in `/etc/letsencrypt` and will persist even if you change the version of certbot you're running.
Can you share with me the output of `dpkg -l | grep certbot`?

**Comment by SwartzCr** [comment]
Does running the command `certbot renew` work?
If so, I'd suggest replacing your cronjob with that command, instead of having it invoke `/usr/local/sbin/certbot-auto renew`
If `certbot renew` brings up a similar error for you then there may need to be more debugging of your python environment

**Comment by flymikeG** [comment]
Yes, `certbot renew` does work. I will replace that cronjob. Thanks.
