### ISSUE TITLE
Use nginx plugin, but don't rewrite configs

### ISSUE THREAD

**Issue by francoism90** [certbot/certbot#5268]
## My operating system is (include version):
Arch Linux 4.13

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Package manager

## I ran this command and it produced this output:
# certbot --nginx

## Certbot's behavior differed from what I expected because:
Yes, on the second question it ask to rewrite the config files. Although it does only state to rewrite configs for redirection, I would like to see an option that doesn't edit the configs at all and/or restores them to state before running `certbot --nginx` (if possible).

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
```
server {
   server_name example.com;
   include conf.d/*.conf; // this already includes the certbot main config (ssl_certificate, ssl_certificate_key, options-ssl-nginx.conf, ssl-dhparams.pem - so it should not be added again.
 ..
}
```

Thanks!

**Comment by jsha** [comment]
Hi,

Can you answer this question?

> Certbot's behavior differed from what I expected because:

**Comment by francoism90** [comment]
@jsha Added. :)

**Comment by jsha** [comment]
I think the command you want is:

```
certbot --authenticator nginx --installer none
```

or

```
certbot certonly --nginx
```

(Note: I'm not positive about either of these, and haven't tested. :-)

**Comment by bmw** [comment]
`certbot certonly --nginx` works. This is described in more detail under the "Getting Started" section of https://certbot.eff.org/#arch-nginx.

I'm closing this issue as I think we've answered your question, but if I'm wrong, please comment and I'll reopen.

**Comment by francoism90** [comment]
@jsha Last one is the command that works for me! :)
@bmw Didn't see that page, bookmarked!

Thanks for the help.
