### ISSUE TITLE
Show a diff when re-creating certificate instead of full list of domains

### ISSUE THREAD

**Issue by Eccenux** [certbot/certbot#5274]
## My operating system is (include version):

Debian GNU/Linux 7 (wheezy)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

certbot-auto

## I ran this command and it produced this output:

`./certbot-auto certonly --cert-name demo.example.com --webroot -w /var/www/html/acme-challenge/ -d demo.example.com -d demo1.example.com -d demo2.example.com -d demo4.example.com`

```
-------------------------------------------------------------------------------
You are updating certificate demo.example.com to include domains: 
demo.example.com, demo1.example.com, demo2.example.com, 
demo4.example.com 

It previously included domains: 
demo.example.com, demo1.example.com, demo3.example.com

Did you intend to make this change?
-------------------------------------------------------------------------------
(U)pdate cert/(C)ancel:
```

## Certbot's behavior differed from what I expected because:

For long lists it's very hard to make sure I'm actually changing what I want. Comparing automatically should be fairly easy though.

Something like this maybe:
```
-------------------------------------------------------------------------------
You are updating certificate demo.example.com to include new domain(s): 
demo2.example.com, demo4.example.com

You are also removing previously included domain(s):
demo3.example.com

Did you intend to make this change?
-------------------------------------------------------------------------------
(U)pdate cert/(C)ancel:
```

Certbot is in Python right? This should work to get those lists:
```python
before = ['demo.example.com', 'demo1.example.com', 'demo3.example.com']
after = ['demo.example.com', 'demo1.example.com', 'demo2.example.com', 'demo4.example.com']

added = list(set(after) - set(before))
removed = list(set(before) - set(after))
added.sort()
removed.sort()
# added = ['demo2.example.com', 'demo4.example.com']
# removed = ['demo3.example.com']
```

**Comment by SwartzCr** [comment]
Good point!
I've flagged this as a good first issue for a volunteer, since it seems like a pretty simple ui improvement to make. If we find ourselves with extra time in a milestone I may be able to get to it, but I'd be very happy to review a PR that implements this :D

**Comment by Eccenux** [comment]
Hope this will do :-). I don't write too much in Python and never written tests for it. Not sure if you write unit tests for private functions/methods here. I guess those functions might be used to some utility class, but not sure if that would not be an overkill ;-)

**Comment by sydneyli** [comment]
Looks like this issue was resolved! closing.
