### ISSUE TITLE
Deprecate Python 3.3

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5278]
This requires a little research into best practices here, but we should start reporting that our ACME module is dropping Python 3.3 support using best practices for a library and we should start logging at the warning level in Certbot about the same problem.

Python 3.3 is no longer supported by CPython and there are no (major) distros using it. I want this for our next release so we can remove support in the release after that.

cc @joohoi and @SwartzCr another good target

**Comment by hugovk** [comment]
Have a look at the practicalities section of http://www.python3statement.org/practicalities/ for some ideas which can be applied specifically for 2.6 and 3.3.

**Comment by SwartzCr** [comment]
Thanks for the comment & link! Please let us know if you think there's anything else we should be doing!
(p.s. I really liked your NaNoGenMo Meowby Dick!)

**Comment by bmw** [comment]
Fixed in #5283.
