### ISSUE TITLE
Set up a linter for our shell scripts like certbot-auto

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5280]

**Comment by sydneyli** [comment]
Something like this would prevent future Travis false negatives like in #5531, where `set -e` didn't cause the program to exit because an error occurred inside a conditional.

**Comment by sydneyli** [comment]
Maybe [shellcheck](https://github.com/koalaman/shellcheck)?

**Comment by bmw** [comment]
Maybe! To be honest, I haven't done any research into potential linters we could use here but I've heard of shellcheck before.

**Comment by bmw** [comment]
We're currently reducing our reliance on shell scripts in favor of more Python, but if we keep any significant shell code, I think this has value but isn't a huge priority.

I'm moving this to wishlist.
