### ISSUE TITLE
Info Message is send to stderr

### ISSUE THREAD

**Issue by schnello** [certbot/certbot#5286]
## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Packed manager, certbot 0.19.0
 

## I ran this command and it produced this output:
certbot renew --post-hook "systemctl reload apache2" > /dev/null

## Certbot's behavior differed from what I expected because:
No output... because all is OK
But Certbot send the Info to stderr:
```
root@uplink:/home/nas# certbot renew --post-hook "systemctl reload apache2" > /dev/null
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Cert not yet due for renewal
```

I use cron to renew my certificate. 
The "problem" is now: Every day i get a mail from my server regarding an "Error for Certbot"
Sure... i can now redirect also the error output to /dev/null.... but what is if "Certbot" has a real problem.
Also the debug log specified this messages as "Info" 

`2017-12-01 09:37:47,514:INFO:certbot.renewal:Cert not yet due for renewal
`

Could you please send the messages for "Cert not yet due for renewal" and "Saving debug log to /var/log/letsencrypt/letsencrypt.log" to stdout?

**Comment by SwartzCr** [comment]
This is a duplicate of #3666 and some other issues. Some work on this was done by @r5d, and hopefully we'll prioritize more of it.
If you're willing to comment on the aforementioned issue, I think we should close this one in favor of that, and discuss overall error message handling in a single thread

**Comment by schnello** [comment]
Thank you for the information and sorry for the duplicate.
