### ISSUE TITLE
Error while creating new certs after deleting old one

### ISSUE THREAD

**Issue by rvsky** [certbot/certbot#5307]
Hi! I have ubuntu 16.04 with nginx. I added two domains (worked good), then I deleted it. Now I want to add the same domains again but with different configuration - I use command sudo certbot --nginx
and then I get error. Below is full log. Can you help me?

```
2017-12-07 15:31:27,501:DEBUG:certbot.main:certbot version: 0.19.0
2017-12-07 15:31:27,502:DEBUG:certbot.main:Arguments: ['--nginx']
2017-12-07 15:31:27,502:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2017-12-07 15:31:27,514:DEBUG:certbot.log:Root logging level set at 20
2017-12-07 15:31:27,514:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-12-07 15:31:27,515:DEBUG:certbot.plugins.selection:Requested authenticator nginx and installer nginx
2017-12-07 15:31:27,537:ERROR:certbot.util:Error while running nginx -c /etc/nginx/nginx.conf -t.

nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/xyz.xyz.pl/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/xyz.xyz.pl/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed

2017-12-07 15:31:27,537:DEBUG:certbot.plugins.disco:Misconfigured PluginEntryPoint#nginx: Error while running nginx -c /etc/nginx/nginx.conf -t.

nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/xyz.xyz.pl/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/xyz.xyz.pl/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/disco.py", line 130, in prepare
    self._initialized.prepare()
  File "/usr/lib/python2.7/dist-packages/certbot_nginx/configurator.py", line 153, in prepare
    self.config_test()
  File "/usr/lib/python2.7/dist-packages/certbot_nginx/configurator.py", line 604, in config_test
    raise errors.MisconfigurationError(str(err))
MisconfigurationError: Error while running nginx -c /etc/nginx/nginx.conf -t.

nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/xyz.xyz.pl/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/xyz.xyz.pl/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed

2017-12-07 15:31:27,538:DEBUG:certbot.plugins.selection:Single candidate plugin: * nginx
Description: Nginx Web Server plugin - Alpha
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: nginx = certbot_nginx.configurator:NginxConfigurator
Initialized: <certbot_nginx.configurator.NginxConfigurator object at 0x7f12c58acd90>
Prep: Error while running nginx -c /etc/nginx/nginx.conf -t.

nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/xyz.xyz.pl/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/xyz.xyz.pl/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed

2017-12-07 15:31:27,539:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None

```

**Comment by SwartzCr** [comment]
Yes - the issue is that you manually deleted the cert file (probably with a command like `rm`)
Unfortunately a reference to it is still in your nginx config file.
Before we run certbot we check that your current webserver configuration is valid.
as seen in this line: `nginx: configuration file /etc/nginx/nginx.conf test failed`
The issue is that when we check the validity of the conf file we check to make sure all files referenced in it exist, in this case your old certificate no longer exists on your hard drive, as seen here:
`(SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/xyz.xyz.pl/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)`
So to get certbot to run with nginx again, you'll have to remove all references to your old certificate from your nginx config file.
Let me know if that works!

**Comment by rvsky** [comment]
@SwartzCr I did it using delete command :)

**Comment by SwartzCr** [comment]
Do you see any other references to files? The paths might be stored in another config

**Comment by rvsky** [comment]
@SwartzCr nope... Where can it be?

**Comment by SwartzCr** [comment]
@ohemorange do you think you could help debug this? I worry that my lack of knowledge and constraints on my time are preventing me from properly helping @rvsky

**Comment by ohemorange** [comment]
What Noah's said so far is correct.

You should check inside files in `/etc/nginx/sites-available/` or `/etc/nginx/sites-enabled` for any lines that say `# managed by Certbot` and delete them.

**Comment by rvsky** [comment]
@ohemorange Thanks, now works.

**Comment by ohemorange** [comment]
Great, glad to hear it!

**Comment by Andrewyg** [comment]
I have the same issue here, but what I'm encountering is for deleted domains, so I've issued a ssl for a domain where I delete the config file later. I'm sure I've delete the cert with `certbot delete` but now I'm continuously entering the error that said SSL cert not found while there's no config file for the domain.

Who can help me out?
