### ISSUE TITLE
Error Host Certification

### ISSUE THREAD

**Issue by goodspeed666** [certbot/certbot#5309]
## My operating system is (include version):
CentOS7x64

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
certbot certonly --webroot -d kitchen.maan.tw

## Certbot's behavior differed from what I expected because:
I apply to "kitchen.maan.tw" certification.
But the certificate point to "li1707-88.members.linode.com". (I use linode VPS.)
I regenerate for many times, and got the same result.
PS. The "course.maan.tw" is fine. They put in the same host.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
2017-12-07 02:34:29,240:DEBUG:acme.client:Storing nonce: QBy4UUbIAG3-rUdUCS0thqYlBmrX7yh6yVL2fSNaEzY
2017-12-07 02:34:29,268:DEBUG:acme.client:Sending GET request to https://acme-v01.api.letsencrypt.org/acme/issuer-cert.
2017-12-07 02:34:29,435:DEBUG:requests.packages.urllib3.connectionpool:"GET /acme/issuer-cert HTTP/1.1" 200 1174
2017-12-07 02:34:29,436:DEBUG:acme.client:Received response:
HTTP 200
content-length: 1174
expires: Thu, 07 Dec 2017 02:34:29 GMT
strict-transport-security: max-age=604800
server: nginx
connection: keep-alive
pragma: no-cache
cache-control: max-age=0, no-cache, no-store
date: Thu, 07 Dec 2017 02:34:29 GMT
x-frame-options: DENY
content-type: application/pkix-cert
replay-nonce: JbFOuBGDoomLLmCFBU8zsPgSYScBv8sVPUTugMjxTuU

MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMTDkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0NlowSjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMTGkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EFq6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8SMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0Z8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWAa6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj/PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIGCCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNvbTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9kc3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAwVAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcCARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAzMDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwuY3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsFAAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJouM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/wApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwuX4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlGPfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==
2017-12-07 02:34:29,453:DEBUG:certbot.storage:Archive directory /etc/letsencrypt/archive/kitchen.maan.tw and live directory /etc/letsencrypt/live/kitchen.maan.tw created.
2017-12-07 02:34:29,453:DEBUG:certbot.storage:Writing certificate to /etc/letsencrypt/live/kitchen.maan.tw/cert.pem.
2017-12-07 02:34:29,453:DEBUG:certbot.storage:Writing private key to /etc/letsencrypt/live/kitchen.maan.tw/privkey.pem.
2017-12-07 02:34:29,454:DEBUG:certbot.storage:Writing chain to /etc/letsencrypt/live/kitchen.maan.tw/chain.pem.
2017-12-07 02:34:29,454:DEBUG:certbot.storage:Writing full chain to /etc/letsencrypt/live/kitchen.maan.tw/fullchain.pem.
2017-12-07 02:34:29,454:DEBUG:certbot.storage:Writing README to /etc/letsencrypt/live/kitchen.maan.tw/README.
2017-12-07 02:34:29,471:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer <certbot.cli._Default object at 0x2d94850>

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
<VirtualHost *:443>
    ServerName kitchen.maan.tw
    DocumentRoot /var/www/html/kitchen
    ErrorLog /var/log/httpd/kitchen.maan.tw-ssl-error.log
    CustomLog /var/log/httpd/kitchen.maan.tw-ssl-access.log combined

    SSLEngine On
    SSLCertificateFile /etc/letsencrypt/live/kitchen.maan.tw/cert.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/kitchen.maan.tw/privkey.pem
    Include /etc/letsencrypt/options-ssl-apache.conf
    SSLCertificateChainFile /etc/letsencrypt/live/kitchen.maan.tw/chain.pem
</VirtualHost>

**Comment by Edelwiess** [comment]
never mind, there is no important data on this sever, I will reinstall the whole system.
Thanks for your help.
I will close this case now,

**Comment by goodspeed666** [comment]
I don't know what you mean ?

**Comment by SwartzCr** [comment]
It seems like maybe @Edelwiess responded to the wrong issue by accident.
@goodspeed666 do you think you'd be able to share the whole log file, not just a snippet of it?

**Comment by adferrand** [comment]
This issue has not been updated for a long time, while info is required to move on. So I assume it is solved, or not relevant anymore. If not, do not hesitate to reopen an issue with updated info about its context.
