### ISSUE TITLE
Not a FQDN because label is too long

### ISSUE THREAD

**Issue by chrisRidgers** [certbot/certbot#5311]
## My operating system is (include version):
 
Ubuntu 14.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

git checkout of version 0.19.0, letsecnrypt-auto 

## I ran this command and it produced this output:

/letsencrypt-auto certonly --post-hook=service nginx reload --no-self-upgrade --webroot -w /var/www/letsencrypt -d production.ldt.mashbodev.com -d reallyabsurdlystupidlylongdomainnamethatisdefinitelygoingtobeoverthe63characterlimitbloodyhellthisislongchillyourbeansman.mashbodev.com

Requested domain reallyabsurdlystupidlylongdomainnamethatisdefinitelygoingtobeoverthe63characterlimitbloodyhellthisislongchillyourbeansman.mashbodev.com is not a FQDN because label reallyabsurdlystupidlylongdomainnamethatisdefinitelygoingtobeoverthe63characterlimitbloodyhellthisislongchillyourbeansman is too long.

## Certbot's behavior differed from what I expected because:

Other tickets discussions have indicated that long domain names +64 characters can be validated as domains by including them as alternative subject names instead of the common name.  Also, isn't certbot supposed to take the first domain as the common name?  In this case production.ldt.mashbodev.com ? Which is under 64 characters and should be fine?

https://github.com/certbot/certbot/issues/1915
https://community.letsencrypt.org/t/ssl-for-a-63-character-max-number-of-characters-domain-name-s/36387/20

**Comment by SwartzCr** [comment]
I think this length restriction is specified in the IETF spec, not as something specific to Certbot: https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_hostnames
Is the case that you're actually hosting a domain with a label of length 64+? Does it resolve?

**Comment by chrisRidgers** [comment]
It did yeh.

We build up our staging names around our client/ project name combinations, so you might get a domain like:  staging.client-name.project-name.our-domain.com

Whenwe get a client with a long name that we dont abbreviate by default it suddenly becomes quite long.  (Usually something like 'The Awesome Shoe Zone' new webstore under the name of aweomeshoes)  staging.the-awesome-shoe-zone.awesomeshoes.mashbodev.com (which is 58, throw in www. because that's what they're going to use or some other subdomain and it starts hitting that limit).

(but yeh they will resolve so we can use them).

**Comment by chrisRidgers** [comment]
(We can do it other ways but by default our in house tools will build a domain similar ish to that which then fails to generate a certificate when provisioning a new environment).

**Comment by bmw** [comment]
Names longer than 64 characters are forbidden by the RFCs Certbot is built on, so I'm closing this issue.

**Comment by flipkickmedia** [comment]
This is possibly the only place to leave comment but surely the whole point of using SSL is to secure domains, to allow people to secure them for a low cost (i.e free) and if you are developing a cluster, and you have clustered DNS names with multiple subdomains, or you just have a long domain name with a single subdomain you are going to be disallowed to use certbot. 

The Certbot RFC should follow the DNS RFC which states that domains can have a maximum length of 253 characters. The labels for any given DNS name should be no more than 63 characters, i.e. a subdomain.

https://tools.ietf.org/html/rfc1035

I've hit this issue. Frustrating.
