### ISSUE TITLE
Remove support for Python 3.3

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5312]
After #5283 ships in 0.21.0, we can remove support for Python 3.3. To do this, we should:

1. Appropriately update `setup.py` so our packages aren't listed as supporting Python 3.3.
2. Remove all Python 3.3 tests.
3. Remove Python 3.3 deprecation warnngs

**Comment by bmw** [comment]
I'm not that familiar with the process, but I believe if we modify `setup.py` right, `pip` is smart enough to notice that a package isn't listed as supporting the Python version and won't try to install it. We should look into this a bit and try to do it as right as we can.

**Comment by hugovk** [comment]
Yes, by adding `python_requires` to `setup()`. This is for 2.7 and 3.4+:

```python
python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*',
```

Links to more info: https://stackoverflow.com/q/44660448/724176
