### ISSUE TITLE
Could someone have a look on this error message?

### ISSUE THREAD

**Issue by Edelwiess** [certbot/certbot#5319]
## My operating system is (include version):

Ubuntu 16.04 TLS
## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

certbot-auto
## I ran this command and it produced this output:

sudo certbot --apache

98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs

Cleaning up challenges
Error while running apache2ctl graceful.
httpd not running, trying to start
Action 'graceful' failed.
The Apache error log may have more information.

AH00557: apache2: apr_sockaddr_info_get() failed for Edel-Hongkong1
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs

Encountered exception during recovery
Error while running apache2ctl graceful.
httpd not running, trying to start
Action 'graceful' failed.
The Apache error log may have more information.

AH00557: apache2: apr_sockaddr_info_get() failed for Edel-Hongkong1
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/error_handler.py", line 100, in _call_registered
    self.funcs[-1]()
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 284, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 1945, in cleanup
    self.restart()
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 1834, in restart
    self._reload()
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 1845, in _reload
    raise errors.MisconfigurationError(str(err))
MisconfigurationError: Error while running apache2ctl graceful.
httpd not running, trying to start
Action 'graceful' failed.
The Apache error log may have more information.

AH00557: apache2: apr_sockaddr_info_get() failed for Edel-Hongkong1
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs

Error while running apache2ctl graceful.
httpd not running, trying to start
Action 'graceful' failed.
The Apache error log may have more information.

AH00112: Warning: DocumentRoot [/var/lib/letsencrypt/tls_sni_01_page/] does not exist
AH00557: apache2: apr_sockaddr_info_get() failed for Edel-Hongkong1
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
## Certbot's behavior differed from what I expected because:

I don't know whether these python error message means my cerbot has not been installed correctly.
If yes, how can I fix the cerbot?

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/error_handler.py", line 100, in _call_registered
    self.funcs[-1]()
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 284, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 1945, in cleanup
    self.restart()
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 1834, in restart
    self._reload()
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 1845, in _reload
    raise errors.MisconfigurationError(str(err))
###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
a
## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

a

**Comment by antonbormotov** [comment]
The error `could not bind to address 0.0.0.0:80` means you already have running application that is listening port 80.
Can you provide us output of `netstat -ntpl`?

**Comment by Edelwiess** [comment]
root@Edel-Hongkong1:~# netstat -ntpl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:6010          0.0.0.0:*               LISTEN      16762/0
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      14174/httpd
tcp        0      0 0.0.0.0:222             0.0.0.0:*               LISTEN      782/sshd
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      14174/httpd
tcp6       0      0 :::5672                 :::*                    LISTEN      754/python
tcp6       0      0 :::27017                :::*                    LISTEN      754/python
tcp6       0      0 :::3306                 :::*                    LISTEN      27281/mysqld
tcp6       0      0 :::49                   :::*                    LISTEN      754/python
tcp6       0      0 :::22                   :::*                    LISTEN      754/python
root@Edel-Hongkong1:~#

**Comment by Edelwiess** [comment]
It seems my apache has some problems, I'm goona reinstall my linux server.
Thanks for your help
