### ISSUE TITLE
Please add an HPKP compatible renew option

### ISSUE THREAD

**Issue by TomMettam** [certbot/certbot#5322]
Please add support for renewing certificates generated using the --csr option. This is absolutely essential for HPKP implementations.

I realise this has been discussed before, but none of the alternative options are really suitable (using the certonly command with --keep doesn't work, for example).

**Comment by SwartzCr** [comment]
@bmw do you think you could properly assign this to a milestone or lump it in with an existing issue that we're tracking?

**Comment by bmw** [comment]
I think this problem for use with `--csr` is tracked by #2373. The problem without `--csr` is tracked by #3788. I'm closing this in favor of those two issues, but if you think I'm missing something a problem here, please let me know and I'll reopen.
