### ISSUE TITLE
Make docker images for each DNS plugin

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5328]
This can be another way for people to get DNS plugins once people want them for wildcard certs.

- [x] Write Dockerfiles.
- [ ] Set up Docker Hub repos.

**Comment by bmw** [comment]
Proposal:

Put a Dockerfile under the top level directory for each DNS plugin that looks as simple as something like:
```
FROM certbot/certbot

COPY . src/certbot-dns-cloudflare

RUN pip install --no-cache-dir --editable /opt/certbot/src/certbot-dns-cloudflare
```
Set up Docker Hub repos for each plugin at either certbot/dns-cloudflare or certbot/certbot-dns-cloudflare. I personally prefer the former, but I'd appreciate feedback here.

These images will build for release tags and I'll configure Docker Hub to update the build for each plugin if the Certbot image it's based on changes.

We could offer a rolling tag for each plugin if we want, but the problem is there's no good way that I've found to automate a build for the rolling image so that it depends on the rolling Certbot image. This is desirable because if the most recent version of the DNS plugin relies on unreleased changes in Certbot, the build will fail (as long as we remember to update the plugin's setup.py so it depends on the right version). This might not be the end of the world though.

Changing the base of the Dockerfile either requires having a 2nd Dockerfile (which causes strange behavior with the Dockerfile listed on Docker Hub) or trying to use build vars which isn't officially supported on Docker Hub (see https://github.com/docker/hub-feedback/issues/508). I don't see a clear path forward here or a strong need for an automated rolling image like this, so I'm not sure it's worth the hassle.

Can I get your thoughts on this plan @joohoi?

**Comment by joohoi** [comment]
This all sounds reasonable. As we discussed on a call, it could be worth it to move the plugins to their own repositories at some point of time. 

As the Dockerfiles for DNS plugins will be so short, having only two additional layers, we probably could also ship with `docker-compose.yml` and / or in documentation give a choice of instructions for the user to build the image themselves for transparency.

**Comment by bmw** [comment]
Automated repos are now on Docker Hub. See https://hub.docker.com/u/certbot/.
