### ISSUE TITLE
Nginx http2 support

### ISSUE THREAD

**Issue by heyarne** [certbot/certbot#5346]
Hi,
I've got a question: Is it possible to add http2 support to nginx? It should just be a matter of replacing `listen 443 ssl` with `listen 443 ssl http2` and it works if nginx is compiled with HTTP2 support:

```
$ nginx -V
nginx version: nginx/1.10.3
built with OpenSSL 1.1.0f  25 May 2017
TLS SNI support enabled
configure arguments: ... --with-http_v2_module ...
```

This could be detected or made configurable with an additional flag maybe. Any thoughts on this? Can I manually configure this somehow in the meantime?

**Comment by SwartzCr** [comment]
@ohemorange Want to add this to wishlist?

**Comment by ohemorange** [comment]
Closing as duplicate of #3646.
