### ISSUE TITLE
Failed authorization procedure. git.7hu.cn (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: DNS problem: SERVFAIL looking up A for git.7hu.cn

### ISSUE THREAD

**Issue by glone008** [certbot/certbot#5347]
## My operating system is (include version):
ubuntu 14
Linux dev-bj03.7hu.cn 4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
git clone https://github.com/letsencrypt/letsencrypt

## I ran this command and it produced this output:
**./letsencrypt-auto certonly --dry-run  --standalone  --email lonelyglone@126.com  -d git.7hu.cn**

**output:**
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
tls-sni-01 challenge for git.7hu.cn
Waiting for verification...
Cleaning up challenges
**Failed authorization procedure. git.7hu.cn (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: DNS problem: SERVFAIL looking up A for git.7hu.cn**

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: git.7hu.cn
   Type:   connection
   Detail: DNS problem: SERVFAIL looking up A for git.7hu.cn

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.

## Certbot's behavior differed from what I expected because:
can't generate new ca

## Here is a Certbot log showing the issue (if available):

someone say than it should because DNSSEC,this is my DNSSEC INFO, DNSSEC  status is off.

**root@dev-bj03:~/ssl_pem/letsencrypt# dig DS 7hu.cn  @a.gtld-servers.net**

; <<>> DiG 9.10.3-P4-Ubuntu <<>> DS 7hu.cn @a.gtld-servers.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4450
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 13, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;7hu.cn.				IN	DS

;; AUTHORITY SECTION:
.			518400	IN	NS	m.root-servers.net.
.			518400	IN	NS	a.root-servers.net.
.			518400	IN	NS	b.root-servers.net.
.			518400	IN	NS	c.root-servers.net.
.			518400	IN	NS	d.root-servers.net.
.			518400	IN	NS	e.root-servers.net.
.			518400	IN	NS	f.root-servers.net.
.			518400	IN	NS	g.root-servers.net.
.			518400	IN	NS	h.root-servers.net.
.			518400	IN	NS	i.root-servers.net.
.			518400	IN	NS	j.root-servers.net.
.			518400	IN	NS	k.root-servers.net.
.			518400	IN	NS	l.root-servers.net.

;; Query time: 264 msec
;; SERVER: 192.5.6.30#53(192.5.6.30)
;; WHEN: Fri Dec 22 01:25:43 CST 2017
;; MSG SIZE  rcvd: 246

**Comment by SwartzCr** [comment]
@cpu any ideas?

**Comment by cpu** [comment]
Hi @glone008,

Your DNS for `git.7hu.cn` is misconfigured. There [seems to be some kind of loop](https://unboundtest.com/m/A/git.7hu.cn/JPQ4Q62V) in the response data. I recommend that you open a support ticket with your DNS provider to help diagnose the issue.

I'm going to close this issue since it isn't something that can be fixed by the Certbot team. If you need more help getting to the bottom of your DNS configuration problem I recommend you [post a new thread in the "Help" section of the community forum](https://community.letsencrypt.org).

Thanks!
