### ISSUE TITLE
certbot-auto did not install on CentOS 6.9 running nginx

### ISSUE THREAD

**Issue by Mcgurk-Adam** [certbot/certbot#5351]
## My operating system is (include version):
CentOS 6.9

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
I ran sudo ./path/to/certbot-auto --nginx
And it got most of the way through until it came here:

/opt/eff.org/certbot/venv/lib/python2.6/site-packages/cryptography/__init__.py:2                                       6: DeprecationWarning: Python 2.6 is no longer supported by the Python core team                                       , please upgrade your Python. A future version of cryptography will drop support                                        for Python 2.6
  DeprecationWarning
Saving debug log to /var/log/letsencrypt/letsencrypt.log
The nginx plugin is not working; there may be problems with your existing config                                       uration.
The error was: NoInstallationError()

I installed Python 3.5 and it produced the exact same output

## Certbot's behavior differed from what I expected because:

I did not expect there to be an error from running the certbot-auto command

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
Log is attached
[letsencrypt.log](https://github.com/certbot/certbot/files/1589940/letsencrypt.log)

**Comment by SwartzCr** [comment]
Do you have nginx installed?
Rather than python 2.5 could you install python 2.7?
I'd say that you should install 2.7, remove 2.6, and install nginx and try again.

**Comment by joohoi** [comment]
This issue hasn't been updated for quite a long time, and things have changed quite a bit since. I'm closing this issue as deprecated, but feel free to comment if this is not the case, and we can reopen the issue.
