### ISSUE TITLE
"ValueError: Unable to set value to path!" when doing Apache in interactive mode

### ISSUE THREAD

**Issue by Cysioland** [certbot/certbot#5353]
## My operating system is (include version):
Debian 7

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
certbot-auto

## Certbot's behavior differed from what I expected because:
It didn't install certificates successfully

## Here is a Certbot log showing the issue (if available):
https://gist.github.com/Cysioland/77a0aa40ce8f48c3c20b5ed74bc56d5f

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
https://gist.github.com/Cysioland/06c92670cf796ad3ee45705308b62c8c

**Comment by SwartzCr** [comment]
What user did you run certbot-auto as? Which user owns `/etc/letsencrypt/`?
My guess is that `/etc/letsencrypt/` is owned by root but you're running certbot-auto as your user, so that when it tries to put a certificate in `/etc/letsencrypt/` it gets an error.
Let me know what happens if you try running certbot-auto again with `sudo`?

**Comment by Cysioland** [comment]
I ran everything as root. Certificates **do** get written to `/etc/letsencrypt`, it's Apache config that doesn't. After running `certbot-auto` again, it again asks me for a list of domains to request a cert for, and after hitting ENTER it asks me whether to attempt to reinstall my existing cert, or request a new one, which is rate-limited.

**Comment by SwartzCr** [comment]
So do you think the error was incorrectly written? As in - you have a working cert successfully written?
I'd say you may as well try to request a new cert if you are working to debug this, it's rate limited but not severely.

**Comment by Cysioland** [comment]
I don't have a working cert (as in, configured with Apache and all my thirty-something vhosts), I just have **a cert**, as in a private key and a certificate written to /etc/letsencrypt

**Comment by SwartzCr** [comment]
Hmm I'm not sure what the issue is, it seems like augeas is dying for some reason.
Maybe @joohoi or @hugvok might be able to help debug.
In the mean time you can try to install that certificate without having to request a brand new one using the `install` command: https://certbot.eff.org/docs/using.html

**Comment by Cysioland** [comment]
Same error happens. I could install it by hand, but it's a metric poopton of work with my number of vHosts, and your issue still won't get fixed, so I prefer to cooperate.

**Comment by joohoi** [comment]
I wonder if some log lines that could prove useful were removed?
```
2018-01-01 21:32:28,686:INFO:certbot_apache.configurator:Deploying Certificate for www.[REDACTED] to VirtualHost /etc/apache2/sites-available/default-le-ssl.conf
[similar lines follow]
```
Certbot logs the file path that it's trying to write to, and this is where Augeas unfortunately fails. We're unable to pull error log out from Augeas about the root reason of the error, so the most recent Certbot log lines before the error are the only thing we have.

**Comment by Cysioland** [comment]
`[similar lines follow]` means, that the lines are the same save for URL

**Comment by Cysioland** [comment]
When I configure my site manually, everything works

**Comment by joohoi** [comment]
> [similar lines follow] means, that the lines are the same save for URL

The last line there should point you to the `<VirtualHost>` the command fails for. Could you pastebin the original configuration for that `<VirtualHost>` ?

**Comment by Cysioland** [comment]
https://gist.github.com/Cysioland/93fe48964e3a5e48a3ff9bdd934bb43d

**Comment by joohoi** [comment]
That seems completely fine. Is there anything strange about filename, permissions or attrs of this single file?

**Comment by Cysioland** [comment]
Filename doesn't contain any strange characters (it's basically `000-default`, don't ask me why all vhosts are in the same file, it's an inherited legacy setup), permissions are 0644, user and group is root.

**Comment by i8x4t** [comment]
Hei! I just got the same error. I had a domain.conf file in sites-available, like this:

> NameVirtualHost *:80
> 
> <VirtualHost *:80>
> ServerName domain.com
> ServerAlias www.domain.com
> [...}
> </VirtualHost>
> 
> <VirtualHost *:80>
> ServerName subdomain.domain.com
> [...]
> </VirtualHost>

I had one symlink from sites-enabled to the file above.
I just split the two VirtualHost entries in 2 sperate files domain.conf and subdomain.domain.conf, created a 2nd symlink, restarted httpd and then certbot ran through fine.

**Comment by Cysioland** [comment]
For some it's not feasible to try and split these files, so it'd be nice for this tool to be able to handle these cases.

**Comment by markyleong** [comment]
I encountered the same issue when using a single conf file with multiple vhosts. Splitting the file to one vhost per conf file fixed it.

**Comment by billynoah** [comment]
Just encountered this myself.  Ubuntu 18.04 with certbot 0.23.0

Splitting the vhosts fixed it but I've done this before on other machines and had no problem at all.  Would be really nice to see this fixed.  Not sure if this is relevant but there may be a hint here - on my second (successful) attempt I noticed this:

```
Redirecting vhost in /etc/apache2/sites-enabled/example.com.conf to ssl vhost in /etc/apache2/sites-available/example.com-le-ssl.conf
Redirecting vhost in /etc/apache2/sites-enabled/subdomain.example.com.conf to ssl vhost in /etc/apache2/sites-available/subdomain.example.com-le-ssl.conf
Enhancement redirect was already set.
```
Seemed odd to me that it says "*Enhancement redirect was already set.*" since this was a clean config file with no existing redirect.  Makes me think it's trying to open and write to the same file multiple times at once.

**Comment by joohoi** [comment]
> Seemed odd to me that it says "Enhancement redirect was already set." since this was a clean config file with no existing redirect. Makes me think it's trying to open and write to the same file multiple times at once.

Was there redirect in place in other `VirtualHost`s? What Certbot does here, is that for creating the redirect, it tries to map back to the original non-HTTPS `VirtualHost`, and looks like in your case it has picked the wrong one. Are there multiple non-HTTPS `VirtualHost`s with same (requested) domain in `ServerName` or `ServerAlias`, or perhaps only default one in place in multiple ones?

**Comment by billynoah** [comment]
@joohoi - in the log I sent, yes.  One already had a redirect in place.  But I did try removing it and the result was the same.  The only thing that fixed this was splitting the vhosts into two files.

**Comment by mcanepa** [comment]
Ok, this exact same thing was happening to me.

This was part of my vhost file:

```
<VirtualHost *:80>
    ServerName www.mydomain.com
    ServerAlias mydomain.com
    DocumentRoot /var/www/mydomain/
        <Directory /var/www/mydomain>
            AllowOverride All
        </Directory>
</VirtualHost>
```

That alias broke the whole process, so I’ve changed it to

```
<VirtualHost *:80>
    ServerName www.mydomain.com
    DocumentRoot /var/www/mydomain/
        <Directory /var/www/mydomain>
            AllowOverride All
        </Directory>
</VirtualHost>
```

Then everything worked fine

**Comment by markuszeller** [comment]
Commenting out the ServerAlias did the thing.

> 
> 
> Ok, this exact same thing was happening to me.
> 
> This was part of my vhost file:
> 
> ```
> <VirtualHost *:80>
>     ServerName www.mydomain.com
>     ServerAlias mydomain.com
>     DocumentRoot /var/www/mydomain/
>         <Directory /var/www/mydomain>
>             AllowOverride All
>         </Directory>
> </VirtualHost>
> ```
> 
> That alias broke the whole process, so I’ve changed it to
> 
> ```
> <VirtualHost *:80>
>     ServerName www.mydomain.com
>     DocumentRoot /var/www/mydomain/
>         <Directory /var/www/mydomain>
>             AllowOverride All
>         </Directory>
> </VirtualHost>
> ```
> 
> Then everything worked fine

**Comment by joohoi** [comment]
This is indeed interesting. Which version of Certbot are you running @markuszeller ?

**Comment by markuszeller** [comment]
I am running
certbot 0.23.0
> 
> 
> This is indeed interesting. Which version of Certbot are you running @markuszeller ?

**Comment by daveagp** [comment]
+1. Had to solve this by splitting out conf files and repeating everything therein :(

**Comment by passariello** [comment]
Exactly the same problem here!

**Comment by passariello** [comment]
<VirtualHost *:80>

	ServerName http://<domain>
	Redirect permanent / http://<domain>/
    
 </VirtualHost>

instead to use ServerAlias ....

**Comment by tuupola** [comment]
This seems to happen if you already have the cert set up and later add a `ServerAlias` section and request a new cert without deleting the old `www.example.com-le-ssl.conf` file first.

**Comment by dchmelik** [comment]
I have same problem on most recent RaspiOS based on Debian 11.

**Comment by fulda1** [comment]
Same for me - I have all virtual hosts in one file: etc/apache24/extra/httpd-vhosts.conf 
```
<VirtualHost *:80>
    # This first-listed virtual host is also the default for *:80
    ServerAdmin webmaster@dummy-host.example.com
    DocumentRoot "/usr/local/www/data"
    ServerName www.domain1.cz
    ErrorLog "/var/log/httpd-error_log"
    CustomLog "/var/log/httpd-access_log" combined
</VirtualHost>

<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host.example.com
    DocumentRoot "/usr/local/www/domain2.cz"
    ServerName domain2.cz
    ServerAlias www.domain2.cz
    ErrorLog "/var/log/httpd.domain2-error_log"
    CustomLog "/var/log/httpd.domain2-access_log" combined
</VirtualHost>

<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host.example.com
    DocumentRoot "/usr/local/www/domain2.cz"
    ServerName domain3.cz
    ServerAlias www.domain3.cz
    ErrorLog "/var/log/httpd.domain3-error_log"
    CustomLog "/var/log/httpd.domain3-access_log" combined
</VirtualHost>
```

I found, that script is able to edit only one domain, so requesting certs per domain fix the issue

**Comment by elnjensen** [comment]
> I found, that script is able to edit only one domain, so requesting certs per domain fix the issue

Thank you!  This worked perfectly for me.  I have two virtual hosts, each with an alias, in a single conf file.  Just running the script twice, and selecting all the hosts/aliases for only one of the two hosts, worked perfectly.
