### ISSUE TITLE
SSLCipherSuite

### ISSUE THREAD

**Issue by Nassiel** [certbot/certbot#5354]
**##The version of Certbot:** 
certbot 0.19.0
**## My operating system is:** 
Centos 7 - Kernel 3.10.0-229.11.1.el7.x86_64

Certbot installs a line to include the configuration of the file 

> options-ssl-apache.conf

According to https://www.ssllabs.com the cipher **DES-CBC3-SHA** is weak and should be disable but by default this file include it. Manual modification is not recommended and the include line is automatically added every time you new the certificates.

So, _I recommend to not include in future versions this cipher._

Thanks!

**Comment by bmw** [comment]
We're choosing our ciphersuites based on the Mozilla recommendations found [here](https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28default.29). There they say:

> DES-CBC3-SHA and EDH-RSA-DES-CBC3-SHA are maintained for backward compatibility with clients that do not support AES.

I think if this concern is no longer valid or overly conservative, this should ideally be fixed at https://github.com/mozilla/server-side-tls. Getting this change there would help more than just Certbot users and we'd follow the new Mozilla recommendations.

Also, more information about why we are using Mozilla's recommendations can be found [here](https://certbot.eff.org/docs/ciphers.html), however, this page is currently unlisted from our documentation and some of the information there like planning to make the cipher recommendation used configurable is out of date.

Thanks for opening this issue and let me know what you think!

**Comment by Nassiel** [comment]
Awesome, GitHub notified me right now about your answer... cool. I think it's quite late but it's still valid. 

From my point of view the main problem it's that you can't control which is included or not. Like other programs for auto-configure the security level, I should be able to configure certbot to use FIPS, or other recommendation tables apart from Mozilla.

Because I don't want to keep my page accessible from Windows XP or versions like Chrome 1 😄

**Comment by bmw** [comment]
Once you've used Certbot to install your certificate, you can change the TLS config and Certbot will not change it back when running `certbot renew`. If you have specific settings you want in your TLS config and you don't even temporarily want to use Certbot's default values, I'm not sure how useful automatic certificate installation is for you and you can always install the cert yourself.

I'm not sure we want to add the ability for the user to configure the TLS settings configured by Certbot. It's additional complexity that few users should be using and is ripe for potential misuse. For that reason, I'm closing this issue, but please add a comment explaining why this feature would be a significant benefit to you over the alternatives if you'd like me to reconsider.
