### ISSUE TITLE
enabling ssl for a changed foo.example.com domain results in garbage

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#5363]
## My operating system is (include version):
Ubuntu 16.04.3 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
ppa: 0.19.0-1+ubuntu16.04.1+certbot+1

## I ran this command and it produced this output:
* I have sites-available: `foo.conf` with `servername `foo-mirror.example.com`
* I have `foo-le-ssl.conf` (generated by certbot with `servername foo-mirror.example.com`)
* I changed the hostname of `foo.conf` to `foo`
```certbot```
* select the new `foo` host
* select redirect

## Certbot's behavior differed from what I expected because:
`foo-le-ssl.conf` had:
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
  ServerAdmin webmaster@localhost
  ServerName foo-mirror.example.com
...
</VirtualHost>
</IfModule>
<IfModule mod_ssl.c>
<VirtualHost *:80>
  ServerAdmin webmaster@localhost
  ServerName foo.example.com
...
RewriteEngine on
# Some rewrite rules in this file were disabled on your HTTPS site,
# because they have the potential to create redirection loops.

# RewriteCond %{SERVER_NAME} =foo.example.com
# RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
</IfModule>
```

The `:443` content was the old content.
The `:80` content was the new content.
It should have had `:443` with new content.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
```
2018-01-04 21:24:57,195:INFO:certbot_apache.configurator:Created an SSL vhost at /etc/apache2/sites-available/foo-le-ssl.conf
2018-01-04 21:24:57,684:INFO:certbot_apache.configurator:Deploying Certificate for foo.example.com to VirtualHost /etc/apache2/sites-available/foo-le-ssl.conf
```

**Comment by SwartzCr** [comment]
How did you go about changing the domain name from `foo-mirror` to `foo`?
It seems to me that that domain name should have been updated when you updated and renewed the certificate with the new name, or did you not do it through a certbot command?

**Comment by jsoref** [comment]
I just edited the ServerName field of the apache conf file.
I was hoping that certbot would recreate the ssl conf file for the newly discovered foo.

**Comment by joohoi** [comment]
This issue hasn't been updated for quite a long time, and things have changed quite a bit since. I'm closing this issue as deprecated, but feel free to comment if this is not the case, and we can reopen the issue.
