### ISSUE TITLE
Change the default ACME server to the v2 endpoint

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#5369]
Step 4 of #5365 
- [ ] tools/deactivate.py
- [ ] acme/examples/example_client.py
The backend data structures are the same for the different endpoints, but we might want to either determine the client to use based on the server like we do in certbot, or at least use acmev2 styles.

**Comment by bmw** [comment]
We won't be doing this in our 0.22.0 release which will be coming out before the endpoint goes live, so I'm kicking this to 0.23.0.

**Comment by shadycuz** [comment]
@bmw It's live, but I can't figure out how to change the endpoint? 
```
Obtaining a new certificate
The currently selected ACME CA endpoint does not support issuing wildcard certificates.
```

**Comment by shadycuz** [comment]
Oh you need server flag  --preferred-challenges dns-01 --server https://acme-v02.api.letsencrypt.org/directory

**Comment by kysil** [comment]
With command
`certbot certonly --rsa-key-size 2048  --preferred-challenges dns-01 --server https://acme-v02.api.letsencrypt.org/directory`

I have this answer:
`Obtaining a new certificate
Performing the following challenges:
None of the preferred challenges are supported by the selected plugin`

nginx 1.13.9
certbot 0.22.0
Centos 7.4

**Comment by shadycuz** [comment]
@kysil I used the instructions in this post https://github.com/certbot/certbot/issues/5719

**Comment by bmw** [comment]
Unfortunately we had to revert this change because things like `certbot revoke --cert-path /path/to/cert` would suddenly stop working due to a different account being used. #5820 should be resolved before releasing this change.
