### ISSUE TITLE
Add a message saying we plan to deprecate python2.6

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#5373]
Similarly to how we did it in #5283.

Notes:
- the biggest difference is PendingDeprecationWarning is shown by default in py 2.6 and isn't in py 3.3
- also, while I didn't worry about this for python 3.3 since there were like 7 users, it'd be nice if we printed the warnings in a way that were able to be disabled by the user
- (as for this, I think it would be nice and may be doable (you can set up logging to capture warnings if we wanted to be consistent in where they were sent), but if it's much effort don't worry about it
- we're talking about the LE_PYTHON people and people installing from pip)
- so if someone upgrades, they can see the warning but continue to use it in cron without getting email every 12 hours when certbot renew runs
- probably the warning system is the best way to do this
- it shouldn't be much code, but might take a little research

**Comment by ohemorange** [comment]
Related to #2208.

**Comment by ohemorange** [comment]
Going to come back for the fancy stuff if there's time after other things.

**Comment by bmw** [comment]
I have time now so I'll take this.
