### ISSUE TITLE
Blanket X-Frame-Options SAMEORIGIN in Apache shared config

### ISSUE THREAD

**Issue by MrPetovan** [certbot/certbot#5376]
## My operating system is (include version):
Debian 9.3 Stretch

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt, version 0.10.2 is installed

## Issue:
On my system, Certbot installed an Apache configuration file in `/etc/letsencrypt/options-ssl-apache.conf` that is included in all the automatically generated sites config. It features the following line:
`Header always set X-Frame-Options SAMEORIGIN`. It sort of makes sense to harden the web server on top of using HTTPS.

## Certbot's behavior differed from what I expected because:
It breaks WordPress OEmbed feature. OEmbed allows websites to embed a HTML snippet to display a nice render of a blog post. However, the WordPress snippet includes an iframe to an internal embed URL that can't be displayed on third-party websites if X-Frame-Options SAMEORIGIN is set for all requests.

Example WordPress embed snippet:
```html
<blockquote class="wp-embedded-content">
    <a href="https://blogs.mprnews.org/newscut/2018/01/reporters-on-icebergs-while-dc-tells-minnesota-to-stuff-it-over-our-weather-expertise/">Reporters on icebergs while DC tells Minnesota to ‘stuff’ our weather expertise</a>
</blockquote>
<script type="text/javascript"><!--//--><![CDATA[//><!-- ... //--><!]]></script>
<iframe sandbox="allow-scripts" security="restricted" src="https://blogs.mprnews.org/newscut/2018/01/reporters-on-icebergs-while-dc-tells-minnesota-to-stuff-it-over-our-weather-expertise/embed/" width="425" height="240" title="“Reporters on icebergs while DC tells Minnesota to ‘stuff’ our weather expertise” — NewsCut" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" class="wp-embedded-content"></iframe>
```

However, [the 0.10.x version of the options-ssl-apache.conf](https://github.com/certbot/certbot/blob/0.10.x/certbot-apache/certbot_apache/options-ssl-apache.conf) doesn't show this line, so I was wondering who could have made the change and how to prevent it.

I was able to comment out this line on my own server, but I can't do it on `blogs.mprnews.org` for example, which breaks their embeds without their knowledge.

**Comment by bmw** [comment]
@joohoi, can you take a look at this?

**Comment by joohoi** [comment]
I wonder if something else has added that line to the configuration. I don't think we've ever had that in our include. 

Just tested installing 0.10.2 on Debian stretch to my box and checked the file. The X-Frame-Options was missing.

**Comment by MrPetovan** [comment]
Thanks for looking into it, I checked the Debian package file list but the directive wasn’t there either. It seems unlikely you guys can do anything more about it.

Thanks for your time!
