### ISSUE TITLE
Apache SSL cipher settings are old, no ChaCha20

### ISSUE THREAD

**Issue by mnordhoff** [certbot/certbot#5379]
The Nginx plugin's `options-ssl-nginx.conf` file uses Mozilla's current intermediate SSL cipher configuration.

The Apache plugin probably did too... except it hasn't been updated since 2014: 2faacc1b43786edd5386305f9cffec376b5a5d26

Should Certbot's Apache settings be updated?

The main difference is that the new configuration adds ChaCha20 cipher suites. (It also removes a few things.)

Should this wait until after further documentation/feature improvements in #4830?

If so, how about a stopgap patch to add ChaCha20 without removing anything?

Differences with OpenSSL 1.0.2 or 1.1.0:

* Adds ChaCha20. (Yay!)
* Adds newer 3DES cipher suites with key exchange/signature algorithms other than RSA/RSA. (Probably doesn't matter. Anything that supports ECDHE-ECDSA ought to support a better cipher than 3DES. ) (Edit: Mozilla suggests that EDH-RSA 3DES is useful, though,.)
* Removes AES-CCM. (OpenSSL 1.1. Probably only included inadvertently.)
* Removes Camellia. (Perfectly nice cipher, but everybody uses AES.)
* Removes some static DH and SRP key exchange cipher suites. (Probably only included by accident, mostly or entirely ignored by servers and clients.)
* Changes the order of some things.

**Comment by bmw** [comment]
Thanks for noticing this @mnordhoff. Not updating this was an oversight on our part. I've done this in #5383 and the new recommended ciphersuites will be used in the next release.

**Comment by mnordhoff** [comment]
The credit goes to someone on IRC, actually. :sweat_smile:

Thank you for the quick fix!
