### ISSUE TITLE
SSL_DHPARAMS_SRC captures buildpath in docs

### ISSUE THREAD

**Issue by hlieberman** [certbot/certbot#5380]
Hello certbot-krew!

Because constants.py is evaluated at build time in order to generate documentation, the `pkg_resources.resource_filename` path is evaluated to include the build path.  At run time, the correct value is used from where it is installed to, but the build path being captured inside the documentation makes the package not binary reproducible.  (https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/python-certbot.html)

That seems like the only constant that's being dynamically generated like that; would it be possible to exclude it from the documentation?

Thanks!

**Comment by lamby** [comment]
Given that it captures the build path — which at runtime will be useless at best and very likely simply broken at run-time — what is even the point of capturing this variable in the first place? :)

**Comment by hlieberman** [comment]
@lamby, it's only captured in docs.  It's checked at run-time in the application itself, so it works fine there.

**Comment by lamby** [comment]
Then let's remove it from the docs :)
