### ISSUE TITLE
Document test everything setup

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5381]
We should document that additional tests are run there, how they pull in the latest version of `master`, how to add to/modify them, how to deal with merge conflicts, etc.

**Comment by joohoi** [comment]
I think this is related to the work @adferrand is doing currently on our tests, I'll add it up to the milestone and assign Adrien, feel free to modify if this is not the case.

**Comment by bmw** [comment]
Ah! This actually refers to the old setup we had where we had a separate branch named `test-everything` with additional tests that pulled in `master` in Travis. We no longer do this and everything is in the `master` branch's so I think this can be closed.

I think/hope I'm better about this now, but past Brad should write more descriptive issues...
