### ISSUE TITLE
Apache 2.4 only config options

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5384]
https://mozilla.github.io/server-side-tls/ssl-config-generator/ generates different files depending on your Apache version. Some settings such as `SSLSessionTickets` are only available in newer versions of Apache. Should we have different versions of this file for Apache 2.2 and Apache 2.4?

cc @joohoi

**Comment by joohoi** [comment]
I think we should. Most of the details stay the same regardless of the version, so should we do an additional include for these directives or just have completely own include file per version?

**Comment by bmw** [comment]
Good question. While not the cleanest from a code perspective, I think they should probably be individual, self-contained files. I think having one file for the user to modify/disable is cleaner, easier, and less error prone than the user having to know about multiple SSL options files.

To note this here for whoever works on this, it seems like the directive `SSLCompression` is only supported in Apache 2.4, however, Red Hat backported it to versions of 2.2 in their repos. Ideally, we can keep setting it for Apache 2.2 users on this systems, but always setting it for Apache 2.2 users seems like a bug waiting to happen.

**Comment by joohoi** [comment]
I think CentOS 6 is the last distribution that's running Apache 2.2, and it's going to EOL next year. We currently have quite a bit on our plates, so I'm pushing this issue to wishlist milestone.

**Comment by bmw** [comment]
The only aspect of this issue now is https://github.com/certbot/certbot/issues/7350 so I'm closing this issue in favor of that one.
