### ISSUE TITLE
The server could not connect to the client to verify the domain :: Timeout

### ISSUE THREAD

**Issue by sharmaprakash** [certbot/certbot#5385]
## I ran this command and it produced this output: certbot --apache -d domain.com -d www.domain.com

Failed authorization procedure. domain.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout, www.domain.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: jdesk9.com
   Type:   connection
   Detail: Timeout

   Domain: www.jdesk9.com
   Type:   connection
   Detail: Timeout

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.

**Comment by SwartzCr** [comment]
I seem to have a really hard time getting your domain to load, I'm not surprised that certbot is timing out.
Maybe you should see if you can improve your load time, and then hopefully certbot will be able to issue a certificate

**Comment by schoen** [comment]
It looks like you got your certificate successfully. For questions like this in the future, please consider https://community.letsencrypt.org/ (there are a lot of people there who can help diagnose problems with certificate issuance).

Thanks!
