### ISSUE TITLE
Failed authorization procedure. beta.aaa.cn (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout

### ISSUE THREAD

**Issue by SirBlues** [certbot/certbot#5403]
018-01-10 01:52:15,641:ERROR:certbot.log:An unexpected error occurred:
2018-01-10 01:52:15,641:ERROR:certbot.log:The request message was malformed :: Error creating new authz :: Invalid character in DNS name

**Comment by SwartzCr** [comment]
What dns provider are you using?

**Comment by joohoi** [comment]
This issue hasn't been updated for quite a long time, and things have changed quite a bit since. I'm closing this issue as deprecated, but feel free to comment if this is not the case, and we can reopen the issue.
