### ISSUE TITLE
letsencrypt命令和certbot命令有什么区别

### ISSUE THREAD

**Issue by SirBlues** [certbot/certbot#5404]
我看网上申请证书的命令，有用letsencrypt的，还有用certbot申请的，我想知道这两个命令有什么区别，在什么场景下用哪个命令。

**Comment by yan12125** [comment]
This tool was called 'letsencrypt'. It was renamed to 'certbot' about two years ago.

**Comment by SirBlues** [comment]
@yan12125 thanks you
