### ISSUE TITLE
Authenticator cleanup not always called

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5429]
In `auth_handler.py`, all code starting with the call to `perform` on the plugin and ending when the challenges can be cleaned up in the normal case should be wrapped in a `with error_handler.ErrorHandler(self._cleanup_challenges):` (or an equivalent) block. With the way this currently works, `_cleanup_challenges` would be called just outside the end of the `with` statement for the case when an exception/signal doesn't occur, but this could/should probably be refactored to have this handled by the `with` statement.

**Comment by bmw** [comment]
This issue isn't very specific so I'm happy to answer any questions you have here or in person.

**Comment by bmw** [comment]
@jgillula, @sydneyli was looking for a Certboty thing to work on tomorrow and offered to take a first crack at this. Any complaints with this?

Let me know if either of you need/want a new issue and I can help you find something.

**Comment by jgillula** [comment]
@sydneyli can take it :-)
