### ISSUE TITLE
Nginx Restart Failed!

### ISSUE THREAD

**Issue by N00D13** [certbot/certbot#543]
every Time i do `letsencrypt -d www.domain.de run`
i got                            Nginx Restart Failed!                                                │  
                              │ nginx: [emerg] the size 1048576 of shared memory zone "SSL"          │  
                              │ conflicts with already declared size 5242880 in                      │  
                              │ /etc/letsencrypt/options-ssl-nginx.conf:1

**Comment by PatrickHeppler** [comment]
Check your nginx config for already defined ssl_session_cache

**Comment by pde** [comment]
@diracdeltas want to take this?

**Comment by diracdeltas** [comment]
@N00D13 to confirm: do you have ssl_session_cache defined in your nginx config file somewhere? Quick fix is to delete that line, run letsencrypt, then manually edit options-ssl-nginx.conf with your original ssl_session_cache.

I can work on a real fix but it might take a week or so (busy with work).

**Comment by PatrickHeppler** [comment]
Deleting the line i a workaround but not a fix ;)

Sent from Nine

Von: Yan Zhu <notifications@github.com>
Gesendet: 30.06.2015 19:32
An: letsencrypt/letsencrypt
Cc: PatrickHeppler
Betreff: Re: [letsencrypt] Nginx Restart Failed! (#543) 

@N00D13 to confirm: do you have ssl_session_cache defined in your nginx 
config file somewhere? Quick fix is to delete that line, run letsencrypt, 
then manually edit options-ssl-nginx.conf with your original 
ssl_session_cache.

I can work on a real fix but it might take a week or so (busy with work).

---

**Comment by Japh** [comment]
I came up on this error too, so I grepped the nginx directory to find where the other entry was and changed my letsencrypt config so the times matched.

That is, in my letsencrypt version I had 
```
    ssl_session_cache shared:SSL:50m;
```

But a line in another config had `20m`, so I changed it to `20m` and all good!

**Comment by SwartzCr** [comment]
I'm going to close this - since it's probably been fixed by the nginx work that @ohemorange has been doing. Feel free to re-open it if I'm mistaken.

**Comment by ohemorange** [comment]
This was actually fixed by #2262 and #3383, but yes, it's fixed. We only modify non-ssl server blocks, and have a specific fix for the `ssl_session_cache` issue.
