### ISSUE TITLE
Link to webroot documentation from error messages

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#5431]
If you follow the autogenerated instructions to use the webroot plugin, you're likely to wind up with this error in your Certbot output:

```
Attempting to renew cert (www.hoffman-andrews.com) from /etc/letsencrypt/renewal/www.hoffman-andrews.com.conf produced an unexpected error: Missing command line flag or config entry for this setting
:
Select the webroot for www.hoffman-andrews.com:
Choices: ['Enter a new webroot']

(You can set this with the --webroot-path flag). Skipping.
The following certs could not be renewed:
  /etc/letsencrypt/live/crud.net/fullchain.pem (failure)
  /etc/letsencrypt/live/jacob.hoffman-andrews.com-0002/fullchain.pem (failure)
  /etc/letsencrypt/live/hoffman-andrews.com/fullchain.pem (failure)
  /etc/letsencrypt/live/www.hoffman-andrews.com/fullchain.pem (failure)
```

This error doesn't define "webroot", and webroot is not a well-defined term (the first page of Google results does not explain it). We shold amend these error messages to link to https://certbot.eff.org/docs/using.html#webroot. We should also update that documentation to define what "webroot" means in the first sentence. Right now it's defined in a parenthetical at the end of the first paragraph:

> In addition, you’ll need to specify --webroot-path or -w with the top-level directory (“web root”) containing the files served by your webserver. For example, --webroot-path /var/www/html or --webroot-path /usr/share/nginx/html are two common webroot paths.

**Comment by klebervirgilio** [comment]
@jsha something like that: https://github.com/certbot/certbot/pull/5583

**Comment by MarkMura** [comment]
Please also add to the documentation, that it's spelled `--webroot-path` in the CLI, but `webroot_path` in the config file
