### ISSUE TITLE
Ubuntu 16.04 PPA out-of-date

### ISSUE THREAD

**Issue by Ravenheart** [certbot/certbot#5447]
## My operating system is (include version):
Ubuntu Server x64 16.04 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
$ sudo apt-get update
$ sudo apt-get install software-properties-common
$ sudo add-apt-repository ppa:certbot/certbot
$ sudo apt-get update
$ sudo apt-get install python-certbot-apache 

## I ran this command and it produced this output:
python-certbot-apache is already the newest version (0.19.0-1+ubuntu16.04.1+certbot+1)

## Certbot's behavior differed from what I expected because:
It should be 0.21.x

**Comment by SwartzCr** [comment]
Unfortunately this will take some time, as it requires a release from the debian and ubuntu maintainers.
Until then users should use certbot-auto if they require features from the 0.21.0 release

**Comment by Ravenheart** [comment]
I am trying to deal with the aftermath of the TLS-SNI removal and the solution thus far is to update certbot, want to avoid any manual downloads/compiles and just use the official channel.

Any ETA when they packages will be updated?

**Comment by SwartzCr** [comment]
That is still being discussed. @hlieberman is in charge of releasing it, but the rest of the team (@bmw ) needs to decide which release will get locked into stable

**Comment by hlieberman** [comment]
Hello!  We just finished the migration of 0.20 to Debian testing.  I know the TLS-SNI-01 issue makes the 0.21 version more important to get out quickly, and I'm aiming to have it starting to bake in unstable in the next few days.  It will probably take at least a week to trickle out to Debian testing, and then from there down to the PPA and (eventually) a stable release update.

**Comment by Fire-Brand** [comment]
@hlieberman thank you! the sooner 0.21 is stable the sooner i can return smiling again 0_o

**Comment by Ravenheart** [comment]
So what is the correct/preffered way to get certbot-auto 0.21.x on Ubuntu 16.04 LTS?

**Comment by SwartzCr** [comment]
@Ravenheart the current best way to get certbot 0.21.0 is to download and run certbot-auto.
Alternately you should be able to use the recently updated instructions on certbot.eff.org to generate new certificates: https://certbot.eff.org/#ubuntuxenial-apache
That said, renewal should still work fine, considering tls-sni-01 is whitelisted for renewals for now.

**Comment by AndriusCTR** [comment]
@SwartzCr how can I "get certbot 0.21.0 and run certbot-auto" exactly on ubuntu 16.04? Do you have any links to more detailed help? Thank you.

**Comment by brennan-v** [comment]
@AndriusCTR This covers how to download and run certbot auto: https://certbot.eff.org/docs/install.html#alternate-installation-methods

**Comment by jszejner** [comment]
Do you need to uninstall the package? or will certbot-auto install on top and when the package is updated past 0.21.0 the ppa package will update it correctly?

**Comment by brennan-v** [comment]
@jszejner certbot-auto won't update or (install on top) of the packaging system's version of certbot. 
You can download it and use it independently of the installed managed package of certbot.

**Comment by scaytrase** [comment]
Still no certbot in PPA to fix TLS-SNI

**Comment by bmw** [comment]
Certbot 0.21.1 is now in the PPA.

**Comment by YohannParis** [comment]
It still not available to me!

I added the PPA `sudo add-apt-repository ppa:certbot/certbot`
Then I update my packet manager `sudo apt-get update && sudo apt-get upgrade`

But when I run `certbot --version` I keep getting `certbot 0.19.0`.

Any idea why?

**Comment by mnordhoff** [comment]
@YohannParis 

What does it output?

You need to use `apt-get dist-upgrade` (or the equivalent with other commands like `apt` or `aptitude`) to upgrade from 0.19.0 to 0.21.1.

**Comment by Ravenheart** [comment]
You are better off getting certbot-auto, its got the same command line arguments and will update always to the latest version.

**Comment by YohannParis** [comment]
Thanks @mnordhoff, the `dist-upgrade` did the trick.
Now I have `certbot 0.21.1`.

@Ravenheart,  I understand. But as someone who ssh to my personal server once a month, I prefer to keep using simpler version of tools. Most information online use `certbot` and not `certbot-auto` and keeping a mental note of this every time I need to work on `certbot` (which is every 6 months) is not worth the trouble. But thanks for the advice.

**Comment by hlieberman** [comment]
Hi Yohann,

That upgrade should be basically a one time thing; it’s because we switched
from using Python 2 to Python 3, so some of our old packages needed to be
replaced with the py3 versions.

Sorry for the trouble! Glad it’s working now.
-- 
Harlan Lieberman-Berg
~hlieberman

**Comment by ahrasis** [comment]
I believe this might as well be updated to version 0.22 that supports Acme V2 which is in production yesterday: https://community.letsencrypt.org/t/acme-v2-production-environment-wildcards/55578

**Comment by W360S** [comment]
this link will help you out.
https://launchpad.net/~certbot/+archive/ubuntu/certbot

**Comment by kevinjmcmahonjr** [comment]
> @YohannParis
> 
> What does it output?
> 
> You need to use `sudo apt-get dist-upgrade` (or the equivalent with other commands like `apt` or `aptitude`) to upgrade from 0.19.0 to 0.21.1.

This fixed it for me!!! I was stuck on 0.19.0 and now it's on 0.28.0 not sure why this was required, but glad I didn't have to fuss with trying to redo everything with the generic certbot-auto and was able to just update my existing package.

**Comment by Ravenheart** [comment]
The frequency with which ubuntu gets updated is irregular, i'd advise to use certbot-auto.
