### ISSUE TITLE
update CHANGELOG.md for version 0.21

### ISSUE THREAD

**Issue by majewsky** [certbot/certbot#5448]
Version 0.21 has been released, but CHANGELOG.md on master (as of aa01b7d0c047e282a456143c8c143e02601b18e8) has not been updated.

**Comment by ArchangeGabriel** [comment]
They always did that, merging the release PR and then later the CHANGELOG one (well to be exact, at first there wasn’t any changelog at all). The CHANGELOG PR is here: https://github.com/certbot/certbot/pull/5446.

**Comment by SwartzCr** [comment]
It's just been merged, closing
