### ISSUE TITLE
Link to Let's Encrypt status page from documentation

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#5449]
I'm trying to get https://letsencrypt.status.io/ to show up in a Google search for [[letsencrypt status](https://www.google.com/search?q=letsencrypt+status)]. Right now it tries to correct to our "stats" page.

One thing that would help is to get more links to it. Would Certbot be willing to add a link in the footers of the documentation saying "Let's Encrypt status" and linking to the status page? Thanks!

**Comment by SwartzCr** [comment]
I think that'd be fine - the reason you want it in the footer is so that it appears on all read the doc pages?

**Comment by jsha** [comment]
Yep!

**Comment by SwartzCr** [comment]
I'm happy to do this, but am having a hard time getting sphinx to behave - if you have any knowledge on how to edit sphinx footers, or if you'd be willing to sit down with me and work on this sometime this week that'd be awesome

**Comment by jsha** [comment]
I don't have any Sphinx experience but I'd be happy to stick our heads together tomorrow afternoon if you're free.

**Comment by SwartzCr** [comment]
Okay, I made a PR, @jsha wanna review it?
