### ISSUE TITLE
Update instruction-generator docs to recommend certbot-auto for all Apache / Nginx

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#5450]
Now that 0.21 is out, Apache and Nginx users should be fixed, but only if they're using `certbot-auto`, at least until we get into `jessie-backports` and other distro packaging. I think until that happens, we should change the docs on https://certbot.eff.org/ so that any choice of "Nginx" or "Apache" gets you the `certbot-auto` instructions, even if Certbot is packaged for your system (because the packaged Certbot is definitely broken right now).

**Comment by SwartzCr** [comment]
https://github.com/certbot/website/issues/300 seems to indicate that we've already reverted these instructions.
@hlieberman do you have a sense of when you'll be able to release 0.21.0 on debian?

**Comment by SwartzCr** [comment]
It looks like we've changed the docs to tell people to explicitly use the webroot authenticator, with a long warning about the issue, so I think this issue can be closed. I favor that solution over recommending certbot-auto
