### ISSUE TITLE
Certbot-nginx does not work with systemctl?

### ISSUE THREAD

**Issue by soggie** [certbot/certbot#5458]
## My operating system is (include version):

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

certbot-auto, as per https://certbot.eff.org/#ubuntuxenial-nginx

## I ran this command and it produced this output:

Basically, I control nginx using systemctl. However, a quick look at certbot-nginx's code reveals that when it restarts, it manually calls the command `nginx` directly, and there's no way I can disable or change that. Pre and post hooks don't even work because of that.

## Certbot's behavior differed from what I expected because:

Expected behaviour is to provide an option to override the restart command, so we don't call restart multiple times.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

Not sure which part of the logs are relevant for this issue.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

Not applicable.

**Comment by SwartzCr** [comment]
Would you be able to link to the code you're referring to? I'm confused about which calls you're talking about.
That said, I think @ohemorange would be best equipped to answer this question.

**Comment by soggie** [comment]
@SwartzCr thanks. Here's the code:

https://github.com/certbot/certbot/blob/master/certbot-nginx/certbot_nginx/configurator.py#L689

```
    def config_test(self):  # pylint: disable=no-self-use
        """Check the configuration of Nginx for errors.
        :raises .errors.MisconfigurationError: If config_test fails
        """
        try:
            util.run_script([self.conf('ctl'), "-c", self.nginx_conf, "-t"])
        except errors.SubprocessError as err:
            raise errors.MisconfigurationError(str(err))
```

From my understanding, if we are to say, manage nginx using systemctl, this would make it quite impossible to stick to systemctl.

**Comment by ohemorange** [comment]
@soggie see comment here, that should work in this situation: https://github.com/certbot/certbot/issues/5486#issuecomment-417002271

if it doesn't there's always the standalone plugin, which won't start or stop nginx at all, and you can do that as you'd like in the hooks.

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.
