### ISSUE TITLE
Don't use error in letsencrypt-auto-source/tests/centos6_tests.sh

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5474]
`error` is something we define in `certbot-auto` and isn't defined here. We should just use `echo` instead.

**Comment by bmw** [comment]
I think this test script will die before we get to this, but it's still valuable to fix this if not.

**Comment by osirisinferi** [comment]
This entire file has gone to `/dev/null` since the removal of the `certbot-auto` script, so this issue isn't relevant any longer :slightly_smiling_face:
