### ISSUE TITLE
Apache 2.4 define breaks the Apache plugin's installer

### ISSUE THREAD

**Issue by rayfoss** [certbot/certbot#5475]
## My operating system is (include version):
Ubuntu 14.04.5

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager 0.19.0

## I ran this command and it produced this output:
`sudo certbot --authenticator webroot --installer apache --redirect -w /srv/www/test6.tdspof.vblip.com/ -d test6.tdspof.vblip.com`
```
Deploying Certificate for test6.tdspof.vblip.com to VirtualHost /etc/apache2/sites-enabled/test1.tdspof.vblip.com-le-ssl.conf
```

## Certbot's behavior differed from what I expected because:
It should have created a new config, but instead chose a completely unrelated one.

## log ##
[letsencrypt.txt](https://github.com/certbot/certbot/files/1662080/letsencrypt.txt)

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
pre test6, test1.tdspof.vblip.com-le-ssl.conf
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
        Define domain test1.tdspof.vblip.com
        ServerAdmin YouAreAwesome@example.com
        ServerName ${domain}
        DocumentRoot /srv/www/${domain}/
        <Directory /srv/www/${domain}/>
                Require all granted
        </Directory>
Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateFile /etc/letsencrypt/live/test1.tdspof.vblip.com/cert.pem
SSLCertificateKeyFile /etc/letsencrypt/live/test1.tdspof.vblip.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateChainFile /etc/letsencrypt/live/test1.tdspof.vblip.com/chain.pem
</VirtualHost>
</IfModule>
```

test6.tdspof.vblip.com, remained untouched
```
<VirtualHost *:80>
	Define domain test6.tdspof.vblip.com
        ServerAdmin serveradmin@tdpowerskills.com
        ServerName ${domain}
        DocumentRoot /srv/www/${domain}/
        <Directory /srv/www/${domain}/>
                Require all granted
        </Directory>
	ErrorLog /var/log/apache2/${domain}-error.log
	CustomLog /var/log/apache2/${domain}-access.log combined
</VirtualHost>
```

post test6, test1.tdspof.vblip.com
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
        Define domain test1.tdspof.vblip.com
        ServerAdmin lol@tdpowerskills.com
        ServerName ${domain}
        DocumentRoot /srv/www/${domain}/
        <Directory /srv/www/${domain}/>
                Require all granted
        </Directory>
Include /etc/letsencrypt/options-ssl-apache.conf
Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateFile /etc/letsencrypt/live/test6.tdspof.vblip.com/cert.pem
SSLCertificateKeyFile /etc/letsencrypt/live/test6.tdspof.vblip.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateChainFile /etc/letsencrypt/live/test6.tdspof.vblip.com/chain.pem
</VirtualHost>
</IfModule>
```

**Comment by SwartzCr** [comment]
@joohoi could you look into this?

**Comment by rayfoss** [comment]
Workaround:
- Don't use a variable ServerName on any of your virtual hosts, or risk mangling
- You can use variables on everything else

**Comment by joohoi** [comment]
Thanks for opening the issue @rayfoss , and sorry that you had troubles with Certbot. Your assessment of the issue is spot on. Unfortunately we don't currently resolve variables in `ServerName` or `ServerAlias` directives and yet the `VirtualHost` selection logic relies on these values. This is definitely something we should fix in the future.
