### ISSUE TITLE
How does the application invoke the certificate?

### ISSUE THREAD

**Issue by MrLichangming** [certbot/certbot#5483]
## My operating system is (include version):

CentOS Linux release 7.3.1611 (Core)
## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

certbot-auto
## Certbot's behavior differed from what I expected because:
When I refer to the fullchain-pem certificate in the program, it always shows insecurity,why?
when my invoke certificate ,

**Comment by SwartzCr** [comment]
@cafeimao It looks like your question may have gotten cut off - can you elaborate?

**Comment by schoen** [comment]
If anyone has a web server configuration problem like this, please ask on the Let's Encrypt Community Forum at https://community.letsencrypt.org/. Thanks!
