### ISSUE TITLE
Feature request: Add option to know what is the last domain passed to dns hook script

### ISSUE THREAD

**Issue by sahsanu** [certbot/certbot#5484]
Hi,

certbot doesn't provide an official hook to work with the API of my DNS provider so I'm using my own script. Well, we know every time we create/modify a record on our DNS provider it needs to propagate to all the authoritative DNS servers, in my case it takes 1 minute and 30 seconds approx., right now, as far as I know, there is no option to know what is the last domain that is being issued so to be bullet proof, every time the script creates the _acme_challenge TXT record, I wait 1:30 minutes, well I use the API to know when the propagation is finished but as I said, it takes 1:30 minutes. If I want to issue a certificate with 100 domains it will take approx. 2 hours and 30 minutes to complete the request. If I had a way to know what is the last domain I could write all the TXT records and when the last domain is created, I could add the check to know when the propagation has finished (or just a simple sleep...) so it takes only 1:30 minutes instead of 2 hours and 30 minutes.

It would be great if certbot provided a variable like `CERTBOT_LAST_DOMAIN=true` or something like that so the script could have the logic to sleep the right amount of time to let finish the DNS  propagation or to perform the needed checks only when there are no more domains to add to our DNS provider.

As a workaround I pass the last domain to my script:

`./certbot-auto certonly --manual --preferred-challenges=dns --manual-auth-hook "/path/to/hook/dnsapi.sh yyy.domain.tld" --manual-cleanup-hook /path/to/hook/dnsapi-cleanup.sh -d zzz.domain.tld,aaa.domain.tld,yyy.domain.tld`

and it works perfectly but would be great to have this feature added directly to certbot.

Thank you in advance.

Cheers,
sahsanu

**Comment by SwartzCr** [comment]
Sounds like a question for @bmw

**Comment by bmw** [comment]
We're currently rethinking a bit about how our plugins work, but if we don't end up making major changes there, I think can and should do something like this.

**Comment by sahsanu** [comment]
That sounds good, we'll appreciate it.

Thank you very much. 

-----Original Message-----

**Comment by bmw** [comment]
We'd accept a PR for this which adds an environment variable like `CERTBOT_REMAINING_CHALLENGES` that is set for both `--manual-auth-hook` and `--manual-cleanup-hook`. The value would be the number of additional times Certbot will call the hook for the current certificate. When the hook is called for the last challenge, `CERTBOT_REMAINING_CHALLENGES` would be 0.

This was discussed in https://github.com/certbot/certbot/pull/6607.

**Comment by varun-da** [comment]
@bmw @sahsanu  I would love `CERTBOT_REMAINING_CHALLENGES`, this would speed up cert generation for us. Currently with manual-auth-hook for 28 subdomain wildcard SAN, 1 root domain wildcard SAN, 1 root domain, we are at 45 - 50 mins to generate a cert.

A implementation like this will greatly help us. Can you please consider opening this issue?

https://community.letsencrypt.org/t/parallel-run-of-certbot-manual-auth-hook-manual-cleanup-hook-for-validation-of-multidomain-cert/115352

**Comment by varun-da** [comment]
@sahsanu in the meantime you can slightly improve the time it takes for resolution with a similar implementation, based on your DNS provider, this might be helpful or not.

```
timeout 120 sh << EOF
NAME_SERVERS="$(dig +short -t NS ${DOMAIN} | tr '\n' ' ')"
echo "NAME_SERVERS=\${NAME_SERVERS}"
for NS in \$NAME_SERVERS; do
  echo "NS=\${NS}"
  until dig +short -t TXT ${ACME_CHALLENGE_DOMAIN} @\${NS} | grep -q -- "${CERTBOT_VALIDATION}"; do
    echo "$(date -Is) waiting for DNS resolution of ${ACME_CHALLENGE_DOMAIN} to show ${CERTBOT_VALIDATION} on \${NS}"
    sleep 1
  done
  echo "resolved on \${NS}"
done
echo "resolved on all name servers: \${NAME_SERVERS}"
EOF

echo "$(date -Is) sleeping for 15s for DNS propogation."
sleep 15
```

**Comment by adferrand** [comment]
[Here you go.](https://github.com/certbot/certbot/pull/7837)
