### ISSUE TITLE
Certbot keeps adding multiple options-ssl-apache.conf includes

### ISSUE THREAD

**Issue by nilsm** [certbot/certbot#5485]
## My operating system is (include version):
Debian 8, Apache 2.4

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto, gives me v0.21.0

## I ran this command and it produced this output:
```
./certbot-auto --force-renew --webroot -d domain.com -w /var/www/domain.com --installer apache
```
I chose option 2, to redirect HTTP to HTTP2.

## Certbot's behavior differed from what I expected because:
Each time I run the command, certbot keeps adding another line to include the ssl options, even though it's already present in the file:

```
Include /etc/letsencrypt/options-ssl-apache.conf'
```

I've now ended up with vhost config with 6 of these include lines, in different places. The file already had the line in once, and certbot added another 5 after consecutively running the command:

```
Include /etc/letsencrypt/options-ssl-apache.conf
Include /etc/letsencrypt/options-ssl-apache.conf
Include /etc/letsencrypt/options-ssl-apache.conf
Include /etc/letsencrypt/options-ssl-apache.conf
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

```
<VirtualHost *:443>
        ServerName domain.com
        DocumentRoot /var/www/domain.com
        ErrorLog "/var/log/apache2/error.log"
        CustomLog "/var/log/apache2/access.log" common

	Include /etc/letsencrypt/options-ssl-apache.conf

	<Directory "/var/www/domain.com">
  		AllowOverride All
 	 	Options MultiViews FollowSymLinks
   		Require all granted
	</Directory>
	        Include /etc/letsencrypt/options-ssl-apache.conf
Include /etc/letsencrypt/options-ssl-apache.conf
Include /etc/letsencrypt/options-ssl-apache.conf
Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateFile /etc/letsencrypt/live/domain.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/domain.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
```

**Comment by nilsm** [comment]
Update: even a newly generated SSL vhost has multiple include lines. Here is an example of a site that only had a :80 HTTP vhost set up:

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName domain.com
        DocumentRoot /var/www/domain.com
        ErrorLog "/var/log/apache2/error.log"
        CustomLog "/var/log/apache2/access.log" common
Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateFile /etc/letsencrypt/live/domain.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/domain.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```

**Comment by SwartzCr** [comment]
@joohoi I think this is something you've dealt with before? Is this new or a regression?

**Comment by joohoi** [comment]
Yeah, this is new, and it's a bug for sure. 

However the command line seems a bit awkward here. @nilsm If you are only renewing the certificate, you should be fine with command line `certbot-auto renew` instead of the current one used, which runs the installer every time, and installer is not required for the renewal.

That being said, the `Include` certainly should not get appended if it already exists. I'll get it fixed asap.

**Comment by nilsm** [comment]
@joohoi I ran it this way to change an existing certificate to use the webroot method + fix some the vhost setup. Probably not the best way to go about it. Thanks for looking into this.

**Comment by joohoi** [comment]
> I ran it this way to change an existing certificate to use the webroot method + fix some the vhost setup. 

I see! I submitted a PR fixing this issue, and it should be included in the next release.

**Comment by pellumbara** [comment]
Certbot   configuration directory at /etc/letsencrypt is empty!  I followed an automatic install from Certbot website for Debian 9 stretch and Apache.  as a result can not make requests via https

**Comment by pellumbara** [comment]
Certbot conf file empty!
