### ISSUE TITLE
Add automatic ACME protocol detection mechanism to the acme library

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5491]
This should work by querying the `directory` endpoint of the server and looking for new fields and/or the new names for existing fields to correctly determine the protocol version that should be used.

This should be done in a way where we store the value of the `directory` so `acme.client.Client` doesn't have to request it again. This should probably be accomplished by adding a new optional parameter to the ACME client which is the value of the directory.

There are many options on the return value here. The current plan is to have two different ACME client classes for each protocol (see #5287). With this in mind, the return value could be int/enum and directory value, ACME client type and directory, initialized ACME client of the right type, etc. I'm fine with any approach, but we have to live with the changes we make here for a long time so they should be designed carefully.

**Comment by bmw** [comment]
Another thing we may want to do in addition to or instead of this is to build a ACME client wrapper that automatically determines the ACME version (possibly by using the function described above) and creates and keeps an ACMEv1 or ACMEv2 client (#5287) as an instance variable. In addition, it could serve as a wrapper of the client and implement functions to automatically handle the differences between the two client versions.

This could allow us to handle both ACME protocols with little to no changes in Certbot and would likely be useful for other projects building off of our ACME library as well.

**Comment by ohemorange** [comment]
Make sure to add `account` parameter when we create `ClientNetwork`

**Comment by bmw** [comment]
@ohemorange, after you've designed the API you plan to implement for this issue, can you describe it here so I have a better idea of the changes we need to make in the rest of Certbot? I'm going to try and break up our current issues for ACMEv2 into smaller ones.

**Comment by ohemorange** [comment]
Ah yes, this should be pretty straightforward with the way #5287 is implemented:

In `certbot/client.py:acme_from_config_key`, we currently create an `acme/client.py:ClientNetwork` object, then create and return a `acme/client.py:Client` object. Instead, we'll create an `acme/client.py:ClientNetwork` object, fetch the directory, determine which version of the API we are based on that, and create and return either a `Client` or `Client2` object.

**Comment by ohemorange** [comment]
Then we'll later be passing around an object usually named `acme` that will have an `acme_version` flag if we need to inspect it to figure out which to use.

**Comment by ohemorange** [comment]
This implementation would put the onus of "which acme version are we" outside of `acme`, which I just noticed goes against the title of this issue. The function "take a directory json and return the acme version" can live in `acme` if we want; `Client2` takes a directory when it's initialized (and `Client` can but you don't have to), so we'll have to fetch it outside anyway.

**Comment by bmw** [comment]
> Then we'll later be passing around an object usually named acme that will have an acme_version flag if we need to inspect it to figure out which to use.

We can also inspect the type of the object.

> This implementation would put the onus of "which acme version are we" outside of acme, which I just noticed goes against the title of this issue. The function "take a directory json and return the acme version" can live in acme if we want; Client2 takes a directory when it's initialized (and Client can but you don't have to), so we'll have to fetch it outside anyway.

I think it'd be nice to put in acme so more people can benefit, but we certainly don't have to do so, especially initially.

Any thoughts on https://github.com/certbot/certbot/issues/5491#issuecomment-360670120 and trying to automatically handle the differences between the two classes?

**Comment by ohemorange** [comment]
I think whether or not that's a good idea will become more clear as we try to implement it.

**Comment by ohemorange** [comment]
I actually think that what we'd end up building re: https://github.com/certbot/certbot/issues/5491#issuecomment-360670120 is a shim over a `ClientV2` object that lets you call V1 functions from a client but call the actual V2 functions underneath.

**Comment by bmw** [comment]
I think probably doing something like that is a good idea if we can write the wrapper in a way that we don't lose much/any functionality. Otherwise, we basically have to write the code that handles the differences scattered throughout Certbot and the few other projects using the ACME library will have to do the same.

**Comment by bmw** [comment]
I updated #5367 with a number of considerations for this PR (and/or other small changes in acme).
