### ISSUE TITLE
Debian Requests for Packages

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5492]
We need to file requests for packages for:

* https://pypi.python.org/pypi/cloudflare (MIT license)
* https://pypi.python.org/pypi/dns-lexicon (MIT license)
* https://pypi.python.org/pypi/tldextract (BSD license)

I tried to do this with `reportbug`, but I don't think it worked as I never received an email with a link to the bug despite providing my email on the command line. We should verify this didn't work, and if so, do it again and send the links to the bugs to Harlan.

The hope here is these packages will be built and maintained by https://wiki.debian.org/Teams/PythonModulesTeam.

**Comment by bmw** [comment]
@ohemorange, @jgillula, and @SwartzCr, I'm not going to be able to get to this today. I tried to file the requests using `reportbug` in Docker, but apparently they were never sent.

Doing this shouldn't take that long and we should do it should do it soon as it's a blocker for getting many of our DNS plugins packaged in Debian and Ubuntu. How to do this is documented [here](https://www.debian.org/devel/wnpp/). If you have any questions, ask @SwartzCr or @hlieberman or if you're really stuck, I'll deal with this when I get back.

**Comment by SwartzCr** [comment]
I've done this, the relevant bugs are: 
Bug#888799: RFP: python-cloudflare -- A python wrapper for the Cloudflare v4 API
Bug#888800: RFP: python-dns-lexicon -- A python library for manipulating DNS records in a standardized way
Bug#888801: RFP: python-tldextract -- A Python library for accurately seperating the TLD from the registered domain or subdomains of a URL, using the Public Suffix List.
Feel free to subscribe to them for updates on their statuses

**Comment by bmw** [comment]
Thanks for doing this Noah!
