### ISSUE TITLE
test_add_listen_80_named fails on Arch

### ISSUE THREAD

**Issue by felixonmars** [certbot/certbot#5510]
## My operating system is (include version):
Arch Linux latest

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
pip

## I ran this command and it produced this output:
`python setup.py test`

```
======================================================================
FAIL: test_add_listen_80_named (certbot_apache.tests.configurator_test.MultipleVhostsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/certbot-apache/src/certbot-apache-0.21.1/certbot_apache/tests/configurator_test.py", line 477, in test_add_listen_80_named
    self.assertEqual(mock_add_dir.call_args[0][2], ['1.2.3.4:8080'])
AssertionError: Lists differ: ['1.1.1.1:8080'] != ['1.2.3.4:8080']

First differing element 0:
'1.1.1.1:8080'
'1.2.3.4:8080'

- ['1.1.1.1:8080']
?     ^ ^ ^

+ ['1.2.3.4:8080']
?     ^ ^ ^
```

## Certbot's behavior differed from what I expected because:
The tests should pass.

I did not get this error on 0.21.0, though.

**Comment by SwartzCr** [comment]
I believe certbot is packaged for arch, is there a reason that you're installing it from pip instead?
I think this is something @bmw can look into once he's back in the office next week

**Comment by felixonmars** [comment]
I am packaging certbot for Arch, in the process it was built with something like pip (setuptools actually), so I filled that.

**Comment by SwartzCr** [comment]
Ah okay, sorry for the confusion - would you be willing to tell me what version of python this is happening on?
Also is this version exactly the 0.21.1 release from pip? Or a different version

**Comment by hlieberman** [comment]
This also fails during build on Debian.  The complete log is attached, including a full system package version list.
[python-certbot-apache_0.21.1-1_amd64.build.txt](https://github.com/certbot/certbot/files/1680168/python-certbot-apache_0.21.1-1_amd64.build.txt)

**Comment by hlieberman** [comment]
For what it's worth, this error is transient.  I see about a 30% test suite failure rate that goes up to 70-80% when I just run that single test in a loop.

This kind of thing smells like a mock bug, but it'd be good to get the real answer.

**Comment by joohoi** [comment]
Sorry for the trouble! This should be fixed in the referenced PR.
