### ISSUE TITLE
Failure to Execute Certbot 0.21.1 on Ubuntu 16.04

### ISSUE THREAD

**Issue by schlpr0k-r7** [certbot/certbot#5513]
## My operating system is (include version): 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

Linux [hostname_redacted] 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Used instructions on "https://certbot.eff.org/#ubuntuxenial-nginx"
$ sudo apt update
$ sudo apt install software-properties-common
$ sudo add-apt-repository ppa:certbot/certbot
$ sudo apt update
$ sudo apt install python-certbot-nginx 

## I ran this command and it produced this output:
certbot --help <--Just an example, but it through a dependency error explicitly looking for certbot==0.19.0. Installed version was 0.21.1.

## WORKAROUND
Modified file, "/usr/bin/certbot" lines 3 and 11, to ignore hard coded certbot version 0.19.0 with 'certbot>=0.19.0' to allow version 0.19.0 and above. 

Manually configured Nginx based on: https://www.youtube.com/watch?v=m9aa7xqX67c&list=LLMc_sj86mAnw8hN7_LzilFA <--Specifically starting from Step4 at 3:31 into the video until Step 6. 

Made a simple bash script to execute 'certbot certificates' & 'certbot renew' and log/tee the output. Used this for cron job to autorenew certificate every other week.

**Comment by exocode** [comment]
have exaclty the same problem: New Ubunut 16.04 Machine
```

certbot --help
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.19.0', 'console_scripts', 'certbot')()
  File "/home/deploy/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/deploy/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/home/deploy/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/home/deploy/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 11, in <module>
    from acme import jose
ImportError: cannot import name jose
```

**Comment by SwartzCr** [comment]
@abindner-r7 can you share the exact error you got that mentioned the version mismatch?
@exocode did you also have a version mismatch, or just a lack of jose? Did you also install certbot from the ppa? What does `dpkg -l | grep certbot` return?
Tagging @bmw @hlieberman @oerdnj in case this is a result of lockstep changes

**Comment by abindner-r7** [comment]
Traceback (most recent call last):
  File "/usr/bin/certbot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'certbot==0.19.0' distribution was not found and is required by the application

### Changed instances of 'certbot==0.19.0' to 'certbot>=0.19.0' and the program executed without the error. ###

**Comment by SwartzCr** [comment]
can you share the output of `dpkg -l | grep certbot` and `pip freeze`?

**Comment by abindner-r7** [comment]
I will post a shortened view of 'pip freeze' with the packages in question, but not my package list; as that is too much information for my comfort. Sorry that is not exactly what you are looking for. Can you be more specific about certain packages and I will upload those individually?

root@[hostname_redacted]:~# pip freeze |egrep 'certbot' || 'acme'
certbot==0.21.1
certbot-nginx==0.19.0
root@[hostname_redacted]:~# pip freeze |grep -i acme
acme==0.21.1
root@[hostname_redacted]:~# pip freeze |grep -i certbot
certbot==0.21.1
certbot-nginx==0.19.0
root@[hostname_redacted]:~# pip freeze |grep -i josepy
josepy==1.0.1

**Comment by SwartzCr** [comment]
So the issue is that you have Certbot installed both via pip and via apt.
You should uninstall the pip version, which is what's causing your certbot to demand version 0.19.0
`pip uninstall certbot-nginx` should be sufficient, but you should also `pip uninstall certbot`
It might be worth it to purge their python dependencies as well, since the PPA provides system packaged versions of Certbot's python dependencies.

**Comment by abindner-r7** [comment]
I have one more web application to build and will need another certificate. I will retest and get back to you, but this sounds like the solution. Thank you.

**Comment by exocode** [comment]
@SwartzCr seems to be you are right. I installed certbot via apt-get. For me: problem solved, thank you!

**Comment by bmw** [comment]
If you're still having problems here, please comment or open a new issue!

As explained by SwartzCr, the general problem is installing Certbot's components through different package managers which can result in unsatisfied dependencies.
