### ISSUE TITLE
Add certificete to apache on arch with ddns dynu.com

### ISSUE THREAD

**Issue by ilisei** [certbot/certbot#5514]
## My operating system is (include version):
arch i686

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot

## I ran this command and it produced this output:
sudo certbot certonly --email ***
[letsencrypt.txt](https://github.com/certbot/certbot/files/1677134/letsencrypt.txt)
[letsencrypt.txt](https://github.com/certbot/certbot/files/1677139/letsencrypt.txt)

 --webroot -w /var/lib/letsencrypt/ -d brothers.dynu.net

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for brothers.dynu.net
Using the webroot path /var/lib/letsencrypt for all unmatched domains.
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. brothers.dynu.net (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://brothers.dynu.net/.well-known/acme-challenge/JU9LGmrhlWpiMiz8XDD5HQXMPTd445M4Rz_0gZzLLuI: Timeout

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: brothers.dynu.net
   Type:   connection
   Detail: Fetching
   http://brothers.dynu.net/.well-known/acme-challenge/JU9LGmrhlWpiMiz8XDD5HQXMPTd445M4Rz_0gZzLLuI:
   Timeout

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.

## Certbot's behavior differed from what I expected because:
i dont no

**Comment by SwartzCr** [comment]
It seems that your website, brothers.dnyu.net isn't up - I can't navigate to it
Which means that the CA won't be able to either.
You'll first need to fix the issues with your website before Let's Encrypt and Certbot can issue you a certificate for it.

**Comment by bmw** [comment]
If you're still having trouble here, please a thread an issue at https://community.letsencrypt.org.
