### ISSUE TITLE
certbot killed me webpage

### ISSUE THREAD

**Issue by nile16** [certbot/certbot#5515]
## My operating system is (include version):
Debian 9

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
sudo apt-get install python-certbot-apache -t stretch-backports

## I ran this command and it produced this output:
sudo certbot --authenticator standalone --installer apache --pre-hook "apachectl -k stop" --post-hook "apachectl -k start"

## Certbot's behavior differed from what I expected because:
The virtual host is unreachable, both http and https. Webserver still works for /var/www/html

**Comment by SwartzCr** [comment]
Would you be willing to share your vhost files or the log file that certbot generated? There's not much we can do without that info

**Comment by nile16** [comment]
Thanks for the responses. It works now. I uninstalled it and installed again according to https://certbot.eff.org/#debianother-apache Thanks again for the answers.

**Comment by SwartzCr** [comment]
Okay, closing this issue - feel free to open new ones if you run into more problems
