### ISSUE TITLE
New version of certbot

### ISSUE THREAD

**Issue by birdvidorg** [certbot/certbot#5522]
## My operating system is (include version): Ubuntu 16.04
Your site says the following: Due to a security issue, Let's Encrypt has stopped offering the mechanism that the Apache plugin previously used to prove you control a domain. You can read more about this here.

We are planning on releasing a new version of Certbot in the next few days that works around this 

Do you have a date for when this will be ready?

**Comment by SwartzCr** [comment]
So the version of Certbot with the fix has been released, unfortunately it has not been packaged for many distributions yet. You can get it by using the certbot-auto script, or it should ready for ubuntu soon, once it gets packaged

**Comment by birdvidorg** [comment]
Do you mean running "certbot-auto" from SSH?

**Comment by SwartzCr** [comment]
How are you currently using certbot?
Tagging @schoen to take over this ticket

**Comment by lsbyerley** [comment]
@SwartzCr any idea when that new package for ubuntu will be available?

**Comment by joohoi** [comment]
Closing this as deprecated.
