### ISSUE TITLE
CentOS 6 pip error affected by locale settings

### ISSUE THREAD

**Issue by Deno028** [certbot/certbot#5523]
I got this error from the renew command.
Error: Command '['/opt/eff.org/certbot/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1

## My operating system is (include version):
CentOS release 6.7 (Final)
Python version: 2.7.8

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
Error: Command '['/opt/eff.org/certbot/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1

## Certbot's behavior differed from what I expected because:
new update

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
nginx version: nginx/1.8.1

**Comment by Deno028** [comment]
Set LC_ALL environment before run this command solved this problem:

> export LC_ALL=C
> ./certbot-auto renew --dry-run --post-hook "service nginx reload" >> /var/log/ssl-renew.log

Also thanks for lykosis help!!!
https://community.letsencrypt.org/t/failed-to-run-certbot-auto-successfully-on-centos-6-5/51376/2

**Comment by schoen** [comment]
I don't understand the underlying reason for this, so someone familiar with packing issues should probably take a look at it at some point. While it's great that the community has found a workaround, the workaround probably shouldn't have been necessary in the first place. :slightly_smiling_face:

**Comment by rasdotsu** [comment]
change at /usr/lib/python3.4/shutil.py

line 387: 

    try:
        names = os.listdir(topfd)
    except OSError as err:


TO => :

    try:
        names = os.listdir(path)
    except OSError as err:

and all will work proper.

**Comment by mphilipps** [comment]
hi,
I am aware this issue is a bit dated, but I am having the exact same issue with CentOS 6.10. Neither setting LC_ALL nor editing /usr/lib**64**/python3.4/shutil.py helped.  The later presumably failed because it is not within the virtualenv?

Any advice on how to processed? (Besides binning CentOS 6)
