### ISSUE TITLE
Your connection is not secure

### ISSUE THREAD

**Issue by passboltUser** [certbot/certbot#5524]
From https://letsencrypt.readthedocs.io/en/latest/intro.html#installation
"... For more information, see Get Certbot." Clicking to Get Certbot (https://certbot.eff.org/docs/install.html) gives me `Your connection is not secure`

FF 58

**Comment by carlblock** [comment]
Also happens in chrome, wget, curl etc..

**Comment by michie1** [comment]
```
 The certificate expired on August 4, 2017, 1:30 AM.
```

**Comment by passboltUser** [comment]
Yes, wonder if it already has been asked.

**Comment by michie1** [comment]
The connection is now secure again for me.

**Comment by passboltUser** [comment]
Indeed it is.
