### ISSUE TITLE
support quoted values in nginx config

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [certbot/certbot#5532]
## My operating system is (include version):
Ubuntu 16.04.3 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
ppa

## I ran this command and it produced this output:
`sudo certbot -a webroot -i nginx -d test.example.com -w /var/www/test.example.com/`

```
Cannot find a VirtualHost matching domain test.example.com. In order for Certbot to correctly perform the challenge please add a corresponding server_name directive to your nginx configuration: https://nginx.org/en/docs/http/server_names.html
```

## Certbot's behavior differed from what I expected because:
failed to find server_name

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
```
2018-02-04 01:37:25,092:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
File “/usr/lib/python2.7/dist-packages/certbot/client.py”, line 452, in deploy_certificate
fullchain_path=fullchain_path)
File “/usr/lib/python2.7/dist-packages/certbot_nginx/configurator.py”, line 194, in deploy_cert
vhost = self.choose_vhost(domain)
File “/usr/lib/python2.7/dist-packages/certbot_nginx/configurator.py”, line 242, in choose_vhost
"https://nginx.org/en/docs/http/server_names.html”) % (target_name))
MisconfigurationError: Cannot find a VirtualHost matching domain test.example.com. In order for Certbot to correctly perform the challenge please add a corresponding server_name directive to your nginx configuration: https://nginx.org/en/docs/http/server_names.html
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
server_name  "test.example.com"

## issue
quoted values are valid for nginx config. certbox-nginx parser does not support quoted values

**Comment by schoen** [comment]
Thanks for the report! We'll track this issue at #5543.
