### ISSUE TITLE
Error certbot

### ISSUE THREAD

**Issue by jusebastian** [certbot/certbot#5537]
El dominio ya debe especificarse en el archivo nginx conf. El certbot toma el dominio del archivo solo sin necesidad de especificar el dominio. Siga los pasos a continuación 
1 Primero instale Cetbot con 
$ sudo apt-get install software-properties-common 
$ sudo add-apt-repository ppa: certbot / certbot 
$ sudo apt-get update 
$ sudo apt-get install certbot 
2 Instale nginx plugin con "sudo apt install python-certbot-nginx" después de instalar certbot. 
3 Ahora navegue al archivo de configuración de nginx con "sudo nano /etc/nginx/nginx.conf" 
4 aquí vaya a los archivos incluidos para los sitios habilitados en el ámbito http exp- 
"/ etc / nginx / sites-enabled /" 
5 abierta por defecto con "sudo vi default"
6 Aquí cambie "server_name" a su nombre de dominio para 443 port.These son 
bloques de servidor individuales 
7 Si necesita agregar algo en otro puerto, puede hacerlo en este archivo. 
8 Y ahora guarde el archivo 
9 inicie el bash como administrador con "sudo bash" 
10 Ahora inicie certbot con el complemento nginx. "Certbot --nginx" 
11 seleccione las opciones apropiadas y el dominio que se enumerará automáticamente. 
Esto funciona en Ubuntu 16.04, así que supongo que funcionaría en la mayoría de los demás también.

**Comment by schoen** [comment]
Hola @jusebastian, 

¿Tiene un problema específico? Parece que ha proporcionado una lista de pasos que lograron. Si tiene un error o problema, ¿puede intentar de nuevo presentándolo en nuestro foro?

https://community.letsencrypt.org/

Hay hispanohablantes en el foro y es posible discutir problemas en Español allá.

Si solo quería mostrarle a otras personas cómo hacerlo y los pasos que ellos necesitarán en esta situación, esto sería más apropiado en un blog.
