### ISSUE TITLE
Can't install certbot on Debian 9(Missing Dependencies)

### ISSUE THREAD

**Issue by TingyiChen** [certbot/certbot#5545]
## My operating system is (include version):

Debian 9 Stretch
## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

apt install certbot
## I ran this command and it produced this output:

root@isaacchen-RFCHost:/etc/nginx/sites-available# apt install certbot
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 certbot : Depends: python3-certbot (= 0.21.1-1+ubuntu17.10.1+certbot+0.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
## Certbot's behavior differed from what I expected because:
debian using libssl1.0.0 version 1.0.1 but python3-certbot needs libssl1.0.0 version 1.0.2

**Comment by TingyiChen** [comment]
More log:
root@isaacchen-RFCHost:/etc/nginx/sites-available# apt install python3-certbot
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-certbot : Depends: python3-acme (>= 0.21.1) but it is not going to be installed
                   Depends: python3-ndg-httpsclient but it is not going to be installed
                   Depends: python3-cryptography (>= 1.2) but it is not going to be installed
                   Depends: python3-zope.component but it is not going to be installed
                   Depends: python3-zope.interface but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
root@isaacchen-RFCHost:/etc/nginx/sites-available# apt install python3-cryptography
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-cryptography : Depends: python3-cffi-backend-api-min (<= 9729)
                        Depends: python3-cffi-backend-api-max (>= 9729)
                        Depends: libssl1.0.0 (>= 1.0.2~beta3) but it is not installable
E: Unable to correct problems, you have held broken packages.
root@isaacchen-RFCHost:/etc/nginx/sites-available#

**Comment by schoen** [comment]
@joohoi, do you know why this might be happening?

**Comment by joohoi** [comment]
It seems that you are trying to use Ubuntu PPA packages in your Debian 9 environment, this unfortunately doesn't work, as you noticed. The Certbot 0.21 is on its way to Debian backports, so it should soon be available for installation as instructed on the [Certbot website](https://certbot.eff.org/#debianstretch-other).
