### ISSUE TITLE
Howto script certbot running hooks only once 

### ISSUE THREAD

**Issue by mkkeck** [certbot/certbot#5546]
I have some domains with certificates. 
Now l want a script which could run only once pre hook (e.g. stop httpd, delete old certs). Then checks/renew all certs. After certbot has all done, then there should be run only one post hook (e.g. restart httpd, postfix, dovecot, copy files...)

Is that possible, perhaps with an example?

Mandy thanks.   

### My operating system is:
CentOS 7.4

**Comment by schoen** [comment]
Hi @mkkeck, could you please try asking on the Let's Encrypt Community Forum?

https://community.letsencrypt.org/ 

This issue queue is meant only for reporting bugs with Certbot, and many, many fewer people look at it, in contrast to the very active support community on the Forum. Thanks!
