### ISSUE TITLE
Support git as a reverter layer?

### ISSUE THREAD

**Issue by pde** [certbot/certbot#5553]
The reverter and rollback commands are pretty unpleasant from a UX perspective right now. We could consider the option of working with server configs in git repos (either preexisting or make one for the user), which would allow a few things to be done better:

* Provide a rich command line for winding forward and back that people might already know
* Be able to record which changes were made by Certbot (indeed, which exact run of Certbot)
* Be able to record and distinguish which changes were made by the user in between Certbot runs

**Comment by pde** [comment]
I don't think we'd want to depend on `git`, but we could offer it to people who have git installed.

**Comment by pde** [comment]
Or use https://github.com/dulwich/dulwich, which is a pure Python implementation of git.

**Comment by pde** [comment]
This is probably still a good intern project :)

**Comment by pde** [comment]
@bmw suggest re-opening for the rainy-day wishlist :)

**Comment by bmw** [comment]
I'd personally prefer to leave this closed.

While this is definitely an interesting idea, I think realistically it's not something we'd ever get to. There's just too much Certbot work we could do, too few developers, and in the grand scheme of things, this seems like a pretty low priority issue to me. I don't think many people use our reverter functionality outside of automated rollbacks when we fail to make changes which wouldn't benefit from using git.

While this is just one issue, I think us closing issues like this in general helps to cleanup our issue queue helps us to more easily see the issues we actually hope to prioritize.
