### ISSUE TITLE
letsencrypt-auto -n

### ISSUE THREAD

**Issue by aweleey** [certbot/certbot#5563]
错误：软件包：python2-certbot-0.21.1-1.el7.noarch (epel)
          需要：python2-psutil >= 2.1.0
 您可以尝试添加 --skip-broken 选项来解决该问题
** 发现 5 个已存在的 RPM 数据库问题， 'yum check' 输出如下：
bt-php-5.4.45-1.el7.centos.x86_64 有缺少的需求 libiconv
bt-php-5.4.45-1.el7.centos.x86_64 有缺少的需求 libmcrypt
bt-php-5.4.45-1.el7.centos.x86_64 有缺少的需求 libmcrypt.so.4()(64bit)
bt-php-5.4.45-1.el7.centos.x86_64 有缺少的需求 mcrypt
bt-php-5.4.45-1.el7.centos.x86_64 有缺少的需求 mhash

**Comment by schoen** [comment]
嗨 @iwlog，

对不起，这是机器翻译，因为我不会说中文。

你愿意尝试在论坛上发帖吗？

https://community.letsencrypt.org/

那里有更多的人，他们中的一些人也可以说中文（虽然不是很多）。

如果我能找出有关您的问题的任何信息，我也会通知您。 抱歉给你带来不便。

**Comment by joohoi** [comment]
这个问题已经开放了很长时间，所以我暂时关闭它。 如果问题仍然存在，请告诉我们，我们可以重新开启此问题。
