### ISSUE TITLE
Support installing to multiple vhosts

### ISSUE THREAD

**Issue by luxaritas** [certbot/certbot#5566]
(Note: I know this applies to Nginx, but with my limited knowledge of Certbot I don't know whether this applies to Apache or not)

I have multiple contexts and servers set up in my Nginx configuration, including a `stream` proxy (see #5565) listening on port 6697 and a regular `http` proxy listening on 443. I would like for Certbot to configure both (including the SSL cert, key, dhparams, etc). One of the issues I came across doing a manual copy was that ` options-ssl-nginx.conf` can't be used for more than one server, as you'd wind up with an `nginx: [emerg] the shared memory zone "le_nginx_SSL" is already declared for a different use in /etc/letsencrypt/options-ssl-nginx.conf:7`, so the `ssl_session_cache` would need to have separate entries per server.

I was surprised I couldn't find any other tickets or forum posts about this, please reference me to any existing information/discussion if I missed it.

**Comment by schoen** [comment]
Hi @LFP6, could you please give us a sample configuration illustrating how this works? I'm not familiar with this setup and I'm not sure offhand whether my other colleagues are either.

**Comment by LFP6** [comment]
Yes, of course, should have done that before. It would wind up looking something like this (abbreviated, with two HTTP servers and a stream server):

```nginx
stream {
    server {
        # Should be managed by Certbot
        ssl_certificate ...
        listen 6697 ssl;
        
        proxy_pass 127.0.0.1:6667;
    }
}

http {
    server {
        server_name  example.com;
        root         /usr/share/nginx/html;
        
        # Should be managed by Certbot
        listen 443 ssl; 
        ssl_certificate ...
        if ($scheme != "https"){
            return 301 https://$host$request_uri;
        }
    }
    
    server {
        server_name  example.com;
        root         /usr/share/nginx/html2;
        
        # Should be managed by Certbot
        listen 4432 ssl; 
        ssl_certificate ...
        if ($scheme != "https"){
            return 301 https://$host$request_uri;
        }
    }
    
    # Should be managed by Certbot
    server {
        if ($host = example.com) {
            return 301 https://$host$request_uri;
        }

        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  example.com
        return 404;
    }
}
```
