### ISSUE TITLE
Warn about out-dated apache access control configurations when performing http-01 validations

### ISSUE THREAD

**Issue by alanbirtles** [certbot/certbot#5567]
If an apache configuration file contains old style access control directives the temporary directives added by certbot may be ignored (http://httpd.apache.org/docs/current/upgrading.html), this leads to a 403 during validation of http-01 validations.
It'd be nice if cerbot raised a warning/failed when trying to add access control directives in the presence of the 2.2 style directives. Alternatively this could be detected after the 403 error if checking up front is too complex/expensive/unreliable.

**Comment by schoen** [comment]
Hi @alanbirtles, could you give us an example of a configuration file where this happens to help my colleagues understand this problem better?

Thanks for letting us know about this.

**Comment by alanbirtles** [comment]
I didn't investigate fully exactly which blocks were causing the problem but I think the main culprit was 
```
<Directory />
    Options FollowSymLinks
    AllowOverride None
    Order allow,deny
    Deny from all
</Directory>
```
Which prevents any require directives from having an effect. I then had the following to allow access to the web root
```
<Directory "/var/www/html">
    Options Indexes FollowSymLinks
    Order allow,deny
    Allow from all
</Directory>
```

**Comment by bmw** [comment]
We should fix this, ideally by fixing up our challenge setup to override directives like this.
