### ISSUE TITLE
Debian 9 - Broken Packages for stretch-backports

### ISSUE THREAD

**Issue by bstin** [certbot/certbot#5573]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
    $cat /etc/issue.net
    Debian GNU/Linux 9

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
    $sudo apt-get install python-certbot-apache -t stretch-backports

## I ran this command and it produced this output:
    $sudo apt-get upgrade
    The following packages have been kept back:
        python-acme
    
    $sudo apt-get upgrade python-acme
    The following packages have unmet dependencies:
      certbot : Depends: python-certbot (= 0.19.0-1~bpo9+1) but it is not going to be installed
      python-certbot-apache : Depends: python-certbot but it is not going to be installed
    E: Broken packages 

## Certbot's behavior differed from what I expected because:
Upgrade certbot without broken package

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
n/a

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
    $cat /etc/apt/sources.list
    #Backports - needed for certbot for letsencrypt
    deb http://ftp.debian.org/debian stretch-backports main

**Comment by joohoi** [comment]
This unfortunate situation is caused by a new part of the Certbot Debian packaging - the acme module being split into its own package, and has to go through a "NEW" package state through the release channel. Certbot will be uninstallable in stretch-backports for a couple of days because of this.

**Comment by bstin** [comment]
Thanks for the update. Will wait it out.

**Comment by butlerfr** [comment]
you can install and download the certbot-auto client:
wget https://dl.eff.org/certbot-auto
chmod a+x certbot-auto
./certbot-auto (it will install everything needed on first start)

**Comment by bmw** [comment]
This has been resolved.

**Comment by th3r3isnospoon** [comment]
This appears to still be broken, (Debian 9 - 64 BIT, Apache) please see here:

```
root@speedtest:/home/speedtest# apt-get install python-certbot-apache -t stretch-backports
Reading package lists... Done
E: The value 'stretch-backports' is invalid for APT::Default-Release as such a release is not available in the sources
root@speedtest:/home/speedtest#
```

**Comment by bmw** [comment]
Looks like `apt-get` doesn't recognize "stretch-backports". Follow the instructions [here](https://backports.debian.org/Instructions/#index2h2) to enable it.

**Comment by th3r3isnospoon** [comment]
I appreciate the response and thank you for the link.  I ended up using certbot-auto to get things up and running.  I just wanted to mention that the directions on [https://certbot.eff.org/](url) were incorrect and that you have to enable the backports in a different way.

**Comment by mcnesium** [comment]
Here is what `apt` outputs on my Debian Stretch 9.3 machine:

    root@box ~# apt update && apt upgrade
    Ign:1 http://ftp.agdsn.de/debian stretch InRelease
    Hit:2 http://ftp.agdsn.de/debian stretch-backports InRelease
    Hit:3 http://ftp.agdsn.de/debian stretch-updates InRelease
    Hit:4 http://ftp.agdsn.de/agdsn-apt stretch InRelease
    Hit:5 http://ftp.agdsn.de/debian stretch Release
    Hit:6 http://security.debian.org stretch/updates InRelease
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    3 packages can be upgraded. Run 'apt list --upgradable' to see them.
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    Calculating upgrade... Done
    The following packages have been kept back:
      certbot python-acme python-certbot-apache
    0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
    root@box ~# apt list --upgradable
    Listing... Done
    certbot/stretch-backports 0.21.1-1~bpo9+1 all [upgradable from: 0.19.0-1~bpo9+1]
    python-acme/stretch-backports 0.21.1-1~bpo9+1 all [upgradable from: 0.19.0-1~bpo9+1]
    python-certbot-apache/stretch-backports 0.21.1-1~bpo9+1 all [upgradable from: 0.19.0-1~bpo9+1]
    root@box ~# apt -t stretch-backports install python-certbot-apache python-acme certbot
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    The following packages were automatically installed and are no longer required:
      libjs-sphinxdoc libjs-underscore python-augeas python-configargparse python-configobj python-configparser python-future python-parsedatetime python-zope.component python-zope.event
      python-zope.hookable python-zope.interface
    Use 'apt autoremove' to remove them.
    The following additional packages will be installed:
      python-josepy python3-acme python3-augeas python3-certbot python3-certbot-apache python3-configargparse python3-configobj python3-future python3-josepy python3-mock python3-parsedatetime python3-pbr
      python3-rfc3339 python3-tz python3-zope.component python3-zope.event python3-zope.hookable python3-zope.interface
    Suggested packages:
      python3-certbot-nginx python-certbot-doc python-acme-doc python-certbot-apache-doc python-configobj-doc python-future-doc python-mock-doc
    The following packages will be REMOVED:
      python-certbot
    The following NEW packages will be installed:
      python-josepy python3-acme python3-augeas python3-certbot python3-certbot-apache python3-configargparse python3-configobj python3-future python3-josepy python3-mock python3-parsedatetime python3-pbr
      python3-rfc3339 python3-tz python3-zope.component python3-zope.event python3-zope.hookable python3-zope.interface
    The following packages will be upgraded:
      certbot python-acme python-certbot-apache
    3 upgraded, 18 newly installed, 1 to remove and 47 not upgraded.
    Need to get 1,155 kB of archives.
    After this operation, 4,612 kB of additional disk space will be used.
    Do you want to continue? [Y/n] n

Is this really what is supposed to happen? Lots of new packages will be installed, some become obsolete and `python-certbot` will be removed?

**Comment by bmw** [comment]
> Is this really what is supposed to happen? Lots of new packages will be installed, some become obsolete and python-certbot will be removed?

Yes. Our Debian backports maintainer recently moved Certbot from Python 2 to Python 3 causing this change.

**Comment by evilaliv3** [comment]
@bmw: do you know if stretch-backports will get the 0.25 update?

I'm particularly interested to this in relation to the breaking API change that will soon hit all 0.22 versions.

**Comment by bmw** [comment]
It should. I've been bugging our Debian/Ubuntu maintainers about this a lot lately and python-acme 0.25.1 is now in Debian testing.

It's possible there will be a brief period where 0.25 is unavailable and the breaking feature is turned on in Let's Encrypt's staging server, but hopefully we can avoid that.

cc @hlieberman

**Comment by dfabreguette-ap** [comment]
To bring clear solution to any other user facing same problem, here's what I had to do :

```
# Edit sources
vim /etc/apt/sources.list

# Uncomment backports line
deb-src http://deb.debian.org/debian stretch-backports main contrib non-free

# Save & Update
apt-get update
```

Hope it can help anyone !

**Comment by schel4ok** [comment]
I just tried, but it doesn't work.
```
# Edit sources
nano /etc/apt/sources.list

# add backports line in the end of file
deb-src http://deb.debian.org/debian stretch-backports main contrib non-free

# Save & Update
apt-get update
```

Then after those actions I tried again   `apt-get install python-certbot-apache -t stretch-backports`
But I got same error
```
Reading package lists... Done
E: The value 'stretch-backports' is invalid for APT::Default-Release as such a release is not available in the sources
```

**Comment by hlieberman** [comment]
On Tue, Oct 2, 2018 at 3:19 PM schel4ok <notifications@github.com> wrote:

> # add backports line in the end of file
> deb-src http://deb.debian.org/debian stretch-backports main contrib non-free
>
>
You need to put both a line beginning "deb" and one beginning "deb-src" in
order for this to work.  Change that, run another `apt-get update`, and you
should be all set to run the install!
-- 
Harlan Lieberman-Berg
~hlieberman

**Comment by schel4ok** [comment]
Thanks. This works.
I fixed sources, then 

```
apt-get update
apt-get install python-certbot-apache -t stretch-backports
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

then I run
apt --fix-broken install
```

and it is OK now

**Comment by rokcarl** [comment]
Doesn't work for me.

    $ cat /etc/debian_version
    9.8
    
    $ cat /etc/apt/sources.list | grep stretch
    deb http://deb.debian.org/debian stretch-backports main
    deb-src http://deb.debian.org/debian stretch-backports main contrib non-free
    
    $ sudo apt --fix-broken install
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    The following packages were automatically installed and are no longer required:
      libdate-manip-perl libsys-cpu-perl libsys-meminfo-perl
    Use 'sudo apt autoremove' to remove them.
    0 upgraded, 0 newly installed, 0 to remove and 139 not upgraded.
    
    $ sudo apt-get install certbot python-certbot-nginx -t stretch-backports
    ...
    The following packages have unmet dependencies:
     certbot : Depends: python3-certbot (= 0.28.0-1~bpo9+1) but it is not going to be installed
     python-certbot-nginx : Depends: python3-certbot-nginx but it is not going to be installed
    E: Unable to correct problems, you have held broken packages.
