### ISSUE TITLE
Delete old backups when --max-log-backups is provided

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5575]
Originally reported at https://community.letsencrypt.org/t/certbot-max-log-backups-not-working-as-expected/53090, if you have more than X logfiles and run certbot with `--max-log-backups Y` where Y is less than X, Certbot won't delete older logfiles and just manages manages the ones whose suffix is <= Y. We should delete the older logfiles.

We'd accept a well written PR to fix this.

**Comment by NickJH** [comment]
This is still an issue with certbot-0.31.

**Comment by NickJH** [comment]
This is still an issue with certbot-1.3.0-1.el7.noarch.

**Comment by radoeka** [comment]
Encountered the same issue with 1.14.

**Comment by craigmaloney** [comment]
Still an issue with 1.29.0. Looking forward to the bot asking me if this is still an issue.

**Comment by craigmaloney** [comment]
Ah, there it is. Right on schedule.
