### ISSUE TITLE
Get common name from CSR in new_order in ClientV2

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5579]
https://github.com/certbot/certbot/pull/5578#issue-169507815.

We have code in `certbot.crypto_util` that does this with the help of some ACME code. The code in `new_order` for extracting SANs is nicer than the code in `acme.crypto_util._pyopenssl_cert_or_req_san`. What I'd do is make (a) function(s) in `acme.crypto_util` that takes a string CSR and uses the SANs extracting code from `new_order` with the common name extracting code from `certbot.crypto_util` and returns the list of domains. If we're currently removing duplicates, we should do this here as well.

**Comment by ohemorange** [comment]
If we're generating the CSR ourselves, we don't actually need to get the common name because we can stick what we need in the SANs. Then we could keep all that extra OpenSSL nastiness out of `acme.crypto_util`.

**Comment by ohemorange** [comment]
Also I think our code there might be wrong... shouldn't it be ignoring the common name if there are SANs?

**Comment by bmw** [comment]
> If we're generating the CSR ourselves, we don't actually need to get the common name because we can stick what we need in the SANs. Then we could keep all that extra OpenSSL nastiness out of acme.crypto_util.

We can extract the common name with `cryptography` too if we want. https://cryptography.io/en/latest/x509/reference/#cryptography.x509.CertificateSigningRequest.subject. We should try not to spend too much time refactoring code we can change later though.
