### ISSUE TITLE
Wildcard Certificates Support

### ISSUE THREAD

**Issue by silgon** [certbot/certbot#5581]
I have a question regarding the new support in `Let's Encrypt` for wildcard certificates. As [they announced](https://letsencrypt.org/2017/07/06/wildcard-certificates-coming-jan-2018.html).

> ACME v2 and wildcard support will be fully available on February 27, 2018

However, they also say the following.

> Let’s Encrypt will begin issuing wildcard certificates in January of 2018. Wildcard certificates are a commonly requested feature and we understand that there are some use cases where they make HTTPS deployment easier. Our hope is that offering wildcards will help to accelerate the Web’s progress towards 100% HTTPS.

I would like to know if `cerbot` is already is prepared for this, and if so, is there a way to test it?

**Comment by joohoi** [comment]
We are currently preparing Certbot for this, the issue tracking the progress is #5367 . Please note that we're not ready for wildcards yet, so it can't be tested yet.
