### ISSUE TITLE
Feature request: certbot-dns-gandi

### ISSUE THREAD

**Issue by toto-jy** [certbot/certbot#5582]
The existing Gandi plugin at https://github.com/Gandi/letsencrypt-gandi only supports their v4 API and is deprecated and archived, with Gandi claiming it's not needed because they offer free SSL certificates with their hosting package. This leaves people hosting elsewhere but using Gandi DNS in the cold when it comes to setting up certbot to automate DNS verification.

However, Gandi now has a v5 API (docs at http://doc.livedns.gandi.net) and it would be great if certbot could update its DNS entries through this.

(Sadly, my Python is not currently up to writing the plugin myself and submitting a PR :)

Thanks!

**Comment by joohoi** [comment]
If someone wants to pick this up, we certainly can provide pointers where to look at and how to get going.

**Comment by maport** [comment]
I've just built a plugin for this which is available at: https://gitlab.com/cspublic/certbot-plugin-gandi.

This calls the LiveDNS API directly although it appears support for the new API is coming in Lexicon (see https://github.com/AnalogJ/lexicon/issues/171).

**Comment by tehfink** [comment]
@maport : Very cool, thanks! Would you mind making it available on PyPi?

**Comment by maport** [comment]
@tehfink: Hopefully at some point, but not sure when currently. Out of interest, do you have a particular requirement for it to be on PyPi (i.e. can you not use `pip install 'git+https://gitlab.com/cspublic/certbot-plugin-gandi.git'`)?

**Comment by reassured-jy** [comment]
Unfortunately the maintainers of the nginx/LE Docker image I use only support plugins that are part of the certbot repo — a pain for me, but I guess they want to keep maintenance simple.

@maport Would it be possible for you to submit this as a PR for certbot?

**Comment by joohoi** [comment]
Can confirm. Using lexicon makes it easier to implement, review and eventually to package by our various package maintainers.

**Comment by adferrand** [comment]
Yep, my PR for Gandi LiveDNS on lexicon has been merged few days ago. Be aware that the Gandi provider supports both APIs, and the old one is used by default. The parameter api_protocol need to be passed as 'rest' to use LiveDNS. I do not know how this kind of parameters are passed through certbot, but maintainers should be aware of that.

**Comment by tehfink** [comment]
@maport: does your plugin support LE's wildcard certificates?

**Comment by maport** [comment]
> @maport: does your plugin support LE's wildcard certificates?

@tehfink: No, afraid not, it was written before LE added support for those.

**Comment by bmw** [comment]
The resolution of this issue is currently blocked on issues like https://github.com/certbot/certbot/issues/6504 and https://github.com/certbot/certbot/issues/6464, but we can keep this open to act on depending on our decisions there.

**Comment by bmw** [comment]
We haven't had a chance to work on the issues in my last comment here, however, we're planning on working on them in the next year so be gone stalebot!

**Comment by HLFH** [comment]
`certbot-dns-gandi` is available here: https://github.com/obynio/certbot-plugin-gandi
And it works flawlessly.

**Comment by s0nik42** [comment]
Hi, is there anyplan to integrate the certbot-dns-gandi mentionned by @HLFH as a plugin ? gandi is a major Domain Name Provider, it would be great to have it integrated.

**Comment by vszakats** [comment]
Issue still relevant. This feature is still offered via a 3rd-party plugin.

Ref: https://github.com/search?q=repo%3Acertbot%2Fcertbot%20gandi&type=code
