### ISSUE TITLE
https redirect don't work for subdomains using apache plugin

### ISSUE THREAD

**Issue by danielbibit** [certbot/certbot#5589]
## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
The ppa certbot/certbot

## I ran this command and it produced this output:
$ sudo certbot --apache

I got the certficates for my domain: example.com.br and the subdomain edu.example.com.br

When asked if I wanted to reddirect http resquests to the https site I confirmed for both sites, the script then exit gracefully.

## Certbot's behavior differed from what I expected because:
When acessing http://example.com.br it reddirects me to https://example.com.br as expected.
But when I acess http://edu.example.com.br it doesn't reddirect to https://edu.example.com.br.

The script modify files on /etc/apache2/sites-enabled for both domains, but the redirect rule is the same.
On the virtualhost for the edu.example.com.br domain, I have to modify this createad by the script:

RewriteCond %{SERVER_NAME} =example.com.br 
to this
RewriteCond %{SERVER_NAME} =edu.example.com.br

I think this might be a bug because the expected behaviour is to have both redirects working out of the box, because the script do create the rule on the subdomain conf file, but not the right one.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
```
<VirtualHost *:80>
        ServerName example.com
        DocumentRoot /var/www/example.com.br
        
        //Created by certbot, this works.
        RewriteEngine on
        RewriteCond %{SERVER_NAME} =example.com.br
        RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<VirtualHost *:80>
        ServerName edu.example.com.br
        DocumentRoot /var/www/edu.example.com.br

        //Created by certbot, this DOES NOT work.
        RewriteEngine on
        RewriteCond %{SERVER_NAME} =example.com.br
        RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<VirtualHost *:80>
        ServerName edu.example.com.br
        DocumentRoot /var/www/edu.example.com.br

        //Modification to proper redirect, this DO WORK.
        RewriteEngine on
        RewriteCond %{SERVER_NAME} =edu.example.com.br
        RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
```

**Comment by ohemorange** [comment]
@joohoi, do you think this is a bug?

@danielbibit, could you provide the following to help us debug this issue:

- The results of `certbot --version`
- The contents of `/var/log/letsencrypt/letsencrypt.log`

**Comment by bmw** [comment]
I just tried to reproduce this and failed.

If you're still having this issue with an up-to-date version of Certbot, please create a new issue and completely fill out the issue template.
