### ISSUE TITLE
nginx authenticator crashes parsing non-ASCII text in comments in configuration files

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#5592]
According to

https://community.letsencrypt.org/t/ascii-codec-cant-decode-byte-0xe6-in-position-1-ordinal-not-in-range-128-skipping/53394

the authenticator crashed with 

`‘ascii’ codec can’t decode byte 0xe6 in position 1: ordinal not in range(128)`

at some point when processing an nginx config file containing Chinese-language text in comments. This was with `certbot-auto`, so it's presumably Certbot 0.21.1.

**Comment by ubani** [comment]
Happens also on Apache.

**Comment by schoen** [comment]
In that case it's not necessarily the authenticator, but might be some other part of the codebase. @ubani, do you see this only during renewal, or also at initial issuance? Do you have logs from `/var/log/letsencrypt` that might show where in the process the crash occurs?

**Comment by belegnar** [comment]
Trouble point is
```
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_nginx/nginxparser.py", line 98, in __str__
    return ''.join(self)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 2: ordinal not in range(128)
```

**Comment by idavydov** [comment]
I followed [this advice](https://community.letsencrypt.org/t/ascii-codec-cant-decode-byte-0xe6-in-position-1-ordinal-not-in-range-128-skipping/53394/4?u=idavydov) and inserted the following lines into /opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_nginx/parser.py:
```
import sys
reload(sys)
sys.setdefaultencoding('utf8')
```

Worked for me.

**Comment by schoen** [comment]
Hi @ntraut,

I'm sorry that you're having trouble with Certbot's nginx parser.  However, the most recent Certbot version is

https://community.letsencrypt.org/t/certbot-1-25-0-release/173954

So it's quite possible that your issue has been fixed in between 1.11 and 1.25.  Can you try updating to a newer version of Certbot?

**Comment by ntraut** [comment]
Hello, I updated certbot to version 1.25.0 and the renew command passed even with non-ascii characters in the nginx config file, so the issue must have indeed been fixed between those two versions.

**Comment by schoen** [comment]
Great, I'm glad to hear that worked for you!
