### ISSUE TITLE
Certbot skips storing the certificate for the second subdomain

### ISSUE THREAD

**Issue by houmie** [certbot/certbot#5593]
> OS: Ubuntu 16.04
> certbot 0.21.1

This is what I have done to create two certs for two subdomains.

```
VPNHOST="vpn-i.example.com"
APIHOST="api-i.example.com"

certbot certonly --non-interactive --agree-tos --email $EMAIL --webroot -w /var/www/letsencrypt/api -d $APIHOST -w /var/www/letsencrypt/vpn -d $VPNHOST

According to the logs it has accepted both entries and has sent and received the challenge, but it has written the certificate only for api entry.

    Saving debug log to /var/log/letsencrypt/letsencrypt.log
    Plugins selected: Authenticator webroot, Installer None
    Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
    Running pre-hook command: /sbin/iptables -I INPUT -p tcp --dport 80 -j ACCEPT
    Obtaining a new certificate
    Performing the following challenges:
    http-01 challenge for api-i.example.com
    http-01 challenge for vpn-i.example.com
    Using the webroot path /var/www/letsencrypt/vpn for all unmatched domains.
    Waiting for verification...
    Cleaning up challenges
    Running post-hook command: /sbin/iptables -D INPUT -p tcp --dport 80 -j ACCEPT

    IMPORTANT NOTES:
     - Congratulations! Your certificate and chain have been saved at:
       /etc/letsencrypt/live/api-i.example.com/fullchain.pem
       Your key file has been saved at:
       /etc/letsencrypt/live/api-i.example.com/privkey.pem
       Your cert will expire on 2018-05-19. To obtain a new or tweaked
       version of this certificate in the future, simply run certbot
       again. To non-interactively renew *all* of your certificates, run
       "certbot renew"
```

Looking into the folder, I only see the api certificate:

```
ls /etc/letsencrypt/live/
api-i.example.com
```
Seems like a bug to me.
Thanks

**Comment by mnordhoff** [comment]
That command creates one certificate with both names in it.

If you run "`certbot certificates`", it will list the certificates it's managing and the names they cover.

By default, Certbot names the directory after the first name on the command line, but the directory name doesn't really matter for anything.

If you want two certificates, you would have to run Certbot twice. (And replace or delete the certificate that already exists.)

**Comment by schoen** [comment]
Indeed, this is totally intended behavior. Let's Encrypt allows up to 100 separate names per certificate, and the multiple `-d` options is how Certbot allows users to take advantage of that.

If you can think of anywhere that it would have helped you to clarify this, please let us know and we can try to improve the documentation!

**Comment by houmie** [comment]
Thanks guys. `certbot certificates` shows me two certs and it's fine for me.
