### ISSUE TITLE
Broken Certbot Website documentation

### ISSUE THREAD

**Issue by marceliwac** [certbot/certbot#5595]
There is a problem with certbot website's documentation. The links are pointing to root's directory (i.e. `certbot.eff.org/using.html` instead of `certbot.eff.org/docs/using.html` and therefore the links are broken. Additionally the documentation menu itself displays without CSS applied which I suppose is not intentional either.

I'm not sure whether the people responsible for website even look here so if anyone knows a better place for this bug report I would be very happy to redirect the question.

#### My operating system is (include version):
MacOS 10.13.3
Chrome Version 64.0.3282.167 (Official Build) (64-bit)
Safari Version 11.0.3 (13604.5.6)

#### Here is the log of Chrome's dev tools:
```
Refused to apply style from 'https://certbot.eff.org/_static/css/theme.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

modernizr.min.js Failed to load resource: the server responded with a status of 404 (Not Found)

jquery.js Failed to load resource: the server responded with a status of 404 (Not Found)

underscore.js Failed to load resource: the server responded with a status of 404 (Not Found)

doctools.js Failed to load resource: the server responded with a status of 404 (Not Found)

theme.js Failed to load resource: the server responded with a status of 404 (Not Found)
docs:329 Uncaught ReferenceError: jQuery is not defined
    at docs:329

docs:1 Refused to apply style from 'https://certbot.eff.org/_static/css/theme.css' because its MIME 
type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

**Comment by marceliwac** [comment]
Apparently this only occurs when the I go to `https://certbot.eff.org` and selects the instance type (i.e. apache on ubuntu 16.04) and click on the documentation links inside this section. The top navigation bar works normally.

**Comment by AndraeRay** [comment]
I see the same broken documentation as marceliwac

On the page: https://certbot.eff.org/#ubuntuxenial-apache
The 'read our documentation' link is broken. Because it points to https://certbot.eff.org/docs (no trailing slash)
instead of https://certbot.eff.org/docs/ like the other links.

**Comment by schoen** [comment]
Thanks for the report and diagnosis! Hopefully the PR I've just created will fix this in practice. (Maybe we should also look into why the trailing slash is necessary at all.)
