### ISSUE TITLE
bot nginx plugin not working

### ISSUE THREAD

**Issue by jfoclpf** [certbot/certbot#5597]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

**Comment by ohemorange** [comment]
Hi @jfoclpf, it doesn't look like any information was filled out here. Could you provide us with some information to help debug your issue?

**Comment by jfoclpf** [comment]
I found the issue, it was an error with nginx.conf file. 
I must do first `nginx [file_name] -t`

**Comment by ohemorange** [comment]
Glad to hear your problem is fixed!
