### ISSUE TITLE
Google API Python Client version

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5603]
When using the version pinned in the [developer setup](https://certbot.eff.org/docs/contributing.html#running-a-local-copy-of-the-client), the automatic credential lookup added in #5117 didn't work and I got:
```
<HttpError 401 when requesting https://www.googleapis.com/dns/v1/projects/<project>/managedZones?alt=js
on&dnsName=<name> returned "Login Required">
```
Do we require a new minimum version of this library now for this feature to work? Are we using it incorrectly?

**Comment by colinmorelli** [comment]
Was having the same problem using the default python3-certbot package. Installed pip3 and upgraded `google-api-python-client` to 1.7.3 and it worked.

**Comment by bmw** [comment]
I don't have a machine handy I can test this on, but maybe we required version 1.6+. See https://github.com/googleapis/google-api-python-client/blob/ffea1a7fe9d381d23ab59048263c631cc2b45323/CHANGELOG#L165.
