### ISSUE TITLE
CERTBOT_TOKEN blank in --manual-cleanup-hook script

### ISSUE THREAD

**Issue by arthibald** [certbot/certbot#5614]
## My operating system is (include version):
Centos 7

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
yum

## I ran this command and it produced this output:
    certbot certonly --test-cert --manual --preferred-challenges=http --manual-auth-hook /path/to/http/authenticator.sh --manual-cleanup-hook /path/to/http/cleanup.sh -d example.com -d www.example.com

Inside /path/to/http/cleanup.sh:

    #!/bin/bash
    rm -f /var/www/htdocs/.well-known/acme-challenge/$CERTBOT_TOKEN

## Certbot's behavior differed from what I expected because:
It appears the $CERTBOT_TOKEN is blank and the script tried:
    
    rm -f /var/www/htdocs/.well-known/acme-challenge/

## Here is a Certbot log showing the issue (if available):
    Error output from certbot_cleanup.sh:
    rm: cannot remove ‘/var/www/htdocs/.well-known/acme-challenge/’: Is a directory

**Comment by joohoi** [comment]
Thanks for the report! This sounds rather weird, as Certbot should be checking that the value surely exists, and if it doesn't, it should rewrite it before calling the cleanup script.

Could you test the following contents for `cleanup.sh`:

```
#!/bin/bash
env > /tmp/cleanup_env_vars
```

And then checking the value of `/tmp/cleanup_env_vars`

**Comment by arthibald** [comment]
My bad, it's there.

I was actually doing two domains and:

    rm -f /var/www/htdocs/.well-known/acme-challenge/$CERTBOT_TOKEN
    ssh other.server.com 'rm -f /var/www/htdocs/.well-known/acme-challenge/$CERTBOT_TOKEN'

I thought it was failing both commands, but it was only failing the last one twice.
It works if I replace the second line with: 

    ssh other.server.com 'rm -f /var/www/htdocs/.well-known/acme-challenge/'$CERTBOT_TOKEN

User error!

Thanks for your help though
