### ISSUE TITLE
How to choose challenge port for ACME server: 80, 443, 22, 25, 115, 22

### ISSUE THREAD

**Issue by narcisgarcia** [certbot/certbot#5616]
As I understood, in CA/Browser Forum they approved "Ballot 190" (+Ballot 215) also to add more authorized TCP ports since november 2017.

How can I use this feature with "certbot certonly --standalone" ?

**Comment by joohoi** [comment]
The [current version](https://cabforum.org/baseline-requirements-documents/) of baseline requirements seems to define authorized ports as following: 80 (http), 443 (https), 25 (smtp), 22 (ssh). 

This aside, Let's Encrypt only supports port 80 for the HTTP-01 challenge validation. It will follow HTTP redirects to port 443 (https) though too. Just to note that these are the only ports Let's Encrypt will connect to for the validation (port 80 being the initial one to connect).

Certbot however does not limit the port that will be used for serving the challenge, this can be done by defining `--http-01-port` on the command line for the standalone plugin.

**Comment by narcisgarcia** [comment]
What happened with port 115 from BR 1.3.8 to BR 1.5.1 ? Also strange to not include ports 23 (Telnet) and 21 (FTP)

And Letsencrypt is not following CA/Browser Forum baseline?

**Comment by joohoi** [comment]
The authorized ports in baseline requirements are ports that the CA is *allowed* to use for domain validation, not ones that they are *required* to use. This should be pretty clear if you read the document.

Furthermore, this github repository is for ACME client called [Certbot](https://certbot.eff.org). So for your specific questions about Let's Encrypt you might want to try to [contact Let's Encrypt](https://letsencrypt.org/contact/) directly.

Closing the issue as non-related.
