### ISSUE TITLE
Invoking certbot immediately following boot, with --installer, results in error

### ISSUE THREAD

**Issue by Kramerican** [certbot/certbot#5618]
Ubuntu 16.04
Certbot 0.21.1

We invoke a workflow where we call Certbot immediately after having provisioned a server in order to secure the customer's default domain, as per the LetsEncrypt mission statement :)

However, what we have found is that Certbot will fail when restarting the webserver, for nginx this looks like:
<details><summary>CLICK ME</summary>
<p>

```
Certbot failed in newawesome Certbot message: Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer nginx
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for newawesome.sisko.webdock.io
Using the webroot path /var/www/html for all unmatched domains.
Waiting for verification...
Cleaning up challenges
Deployed Certificate to VirtualHost /etc/nginx/sites-enabled/webdock for newawesome.sisko.webdock.io
nginx: [error] open() "/run/nginx.pid" failed (2: No such file or directory)
Rolling back to previous server configuration...
nginx: [error] open() "/run/nginx.pid" failed (2: No such file or directory)
Encountered exception during recovery
nginx restart failed:
b
b
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 462, in deploy_certificate
    self.installer.restart()
  File "/usr/lib/python3/dist-packages/certbot_nginx/configurator.py", line 680, in restart
    nginx_restart(self.conf(ctl), self.nginx_conf)
  File "/usr/lib/python3/dist-packages/certbot_nginx/configurator.py", line 926, in nginx_restart
    "nginx restart failed:\n%s\n%s" % (out.read(), err.read()))
certbot.errors.MisconfigurationError: nginx restart failed:
b
b

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/error_handler.py", line 100, in _call_registered
    self.funcs[-1]()
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 557, in _rollback_and_restart
    self.installer.restart()
  File "/usr/lib/python3/dist-packages/certbot_nginx/configurator.py", line 680, in restart
    nginx_restart(self.conf(ctl), self.nginx_conf)
  File "/usr/lib/python3/dist-packages/certbot_nginx/configurator.py", line 926, in nginx_restart
    "nginx restart failed:\n%s\n%s" % (out.read(), err.read()))
certbot.errors.MisconfigurationError: nginx restart failed:
b
b
nginx restart failed:
b
b
IMPORTANT NOTES:
 - An error occurred and we failed to restore your config and restart
   your server. Please submit a bug report to
   https://github.com/letsencrypt/letsencrypt
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/newawesome.sisko.webdock.io/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/newawesome.sisko.webdock.io/privkey.pem
   Your cert will expire on 2018-05-22. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot again
   with the "certonly" option. To non-interactively renew *all* of
   your certificates, run "certbot renew"
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
```

</p>
</details>

Of course per Murphys law I cannot reproduce this atm for Apache, but I have definitely seen this happen for Apache as well. 

What's interesting is that this flips the webserver completely, and I have to issue a killall command and then bring it back up.

My solution is a dumb one: I put in a 10 second sleep command, and that seems to do the trick.

However, I am curious: How are you restarting the webserver? You're not invoking systemctl? It seems like as soon as Certbot is invoked you're doing something to interact with the webserver. I can't quite figure out what you are doing here, it's all a bit strange ...

**Edit:** Just noticed that my current test here with Apache does not result in Certbot throwing an error - the log looks clean, but Apache has not been started succesfully and I had to manually run `systemctl start apache2`

As mentioned, putting in a 10 second sleep before invoking Certbot solves all issues. 

This is all very strange, as immediately after provisioning the webserver is up and listening on port 80 and can be reached from the outside world. Certbot takes a bit of time ot auth the server (I am using webroot authentication) and one would think that Certbots interaction with the webserver in order to restart it would happen at the very end of the workflow.

But it almost seems to me you are grabbing the processes somehow very early, and then using that to restart the server, or something. Again, I find all this exceedingly bizarre.

**Comment by schoen** [comment]
Hi @Kramerican ,

Thanks for the bug report.

Currently the Apache process uses `apachectl` or `apache2ctl` `graceful` (detected based on the OS), while the nginx process uses `nginx -c yournginxconf -s reload`. There's no use of `systemctl` on any platform under any circumstances. Can you think of a particular reason why these methods would lead to the problems that you've been seeing?

If not, could you also share some of your associated log files, including the web server error logs associated with the restart, and the Certbot logs associated with the attempt to get the certificate?

Do you know how long your web servers take to reload? I think both of these plugins have a hardcoded sleep that might not be long enough because they don't know how to tell when the reload has completed (at least this is definitely true of the Apache plugin under some circumstances).

**Comment by schoen** [comment]
Also, is it clear that the server process had fully finished starting up before running Certbot? That seems like a likely problem here. I don't think our design has ever taken this question into account.

**Comment by Kramerican** [comment]
Hi @schoen 

I am quite sure this is all due to the server process not fully finishing starting up. I am running an LXD containerized environment where immediately once started I invoke Certbot in the container.

But ... What confuses me is that Certbot takes a while to do its authentication, and when it's done I am quite sure the webserver is up and ready - the webserver takes about 2-3 seconds to fully start up it seems - while the Certbot auth takes quite a bit longer.

So it stands to reason that if you are just executing an apache2ctl or nginx command at the end of the Certbot workflow we should be fine.

Maybe everything takes a lot longer to start up than I think. In any case, I'll do some tests shortly in a clean container and post some logfiles for you here :)

**Comment by schoen** [comment]
Well, the authentication process itself may also require restarting the web server, which would happen earlier on. Could that be related?

**Comment by Kramerican** [comment]
Yes that would certainly do the trick I suppose! 

If the webserver isn't ready, and you are monkeying around with it early on then that would explain this :) I think we can conclude that Certbot isn't waiting for the webserver to finish starting up. I suggest you review that codepath and if possible, put in some "are you up" detection if possible.

If that's not doable, slightly longer sleep might do the trick - or if all else fails output a nicer error message instructing the user to make sure the webserver is up (implement their own sleep, like I did)

I'm willing to help test this, as I can easily reproduce this scenario :) Would you still like to see log files?

**Comment by schoen** [comment]
It would be great to see the log files, and also to know of an appropriate method to do the "are you up" detection. The colleagues I just mentioned it to didn't know of an official way to check this.

**Comment by Kramerican** [comment]
Alrighty

Here are some logs:

**Nginx**
Server log: https://gist.github.com/anonymous/37977b47c96e4630736a4cae3c952301
Certbot log: https://gist.github.com/anonymous/764c914322251e8fc50c3641dd2fd2ed

**Apache**
Server log: https://gist.github.com/anonymous/d207bd81376b55c910b29ea42fcaa420
Certbot log: https://gist.github.com/anonymous/c456dd359870cd30328ba38fc28ac46f

PS Anything sensitive in here I should redact?

In the case of Nginx it almost seems to me that the regular startup of Nginx fails, since Certbot already started the webserver. Certbot is invoked literally immediately once the container is started, so my guess as to what is happening here is that Certbot is pre-empting regular startup of Apache/Nginx

I guess you could look for the nginx/apache process? I remember doing some bash scripting not terribly long ago and it wasn't too difficult to detect if an application was running or not ... Not sure which pitfalls might be involved though...

**Comment by schoen** [comment]
Something kind of confusing here is that it looks like you're running Certbot four times in a row, with different arguments—which Certbot commands do you run in each case and why are there so many of them (assuming I'm right that there are multiple Certbot invocations)?

**Comment by Kramerican** [comment]
@schoen 

Yes as per #5615 I am doing rollback -> rollback -> certbot

So I'm calling certbot 3 times, this is correct. Maybe it's the rollback actions doing this? Hmm ..

I swear I'm "only" invoking Certbot 3 times. Not sure what the first entry is all about!

**Comment by schoen** [comment]
Hmmm, I think it could be the rollbacks doing it. I hadn't seen that other issue and haven't looked at it closely enough yet to understand what the purpose of the rollbacks is.

Would you be able to experiment with changing where the sleep happens? (That is, does the problem persist if you do `rollback; rollback; sleep; certbot` as opposed to `sleep; rollback; rollback; certbot`?)

**Comment by Kramerican** [comment]
I just did a test with `rollback; rollback; sleep; certbot` with identical (failure) results

So yes, it seems indeed that the rollback actions are responsible. Doesn't quite rule out that the same thing might not happen without the rollbacks. But yeah, there's that :)

**Comment by schoen** [comment]
Well, I guess I'd better take a look at the other issue to understand why the rollbacks are necessary in your setup. :smiley:

**Comment by Kramerican** [comment]
Thank you @schoen - as a sidenote, the containers are 100% clean and have just had certbot installed with apt, and certbot has never been run before the container is booted and configured by our toolchain. That indicates possible buggyness in rollback (reason why I run it twice), in addition to all the other issues I mention :)

**Comment by Kramerican** [comment]
**PPS:** I can easily differentiate between first-run after provisioning and subsequent runs against a container. So I should really just take out the rollbacks at provision time, as there they are not needed. Let me try that and then report back here if the issue persists.

**Comment by Kramerican** [comment]
Ok so yeah removing the rollbacks completely solves the issue for both webservers.

So I have solved the issue I suppose :)

However, as rollback has nothing to do, and reports this in the log, it might be problematic that it then interacts with the webserver at all ... Anyway, something you might want to look at :)

**Comment by schoen** [comment]
Thanks, I will try to consider a more general solution for the future. I'm glad you've gotten this working in your particular configuration.

**Comment by Kramerican** [comment]
@schoen 

Lovely. It would be great if you could take a peek at the other issue. I think I inundated poor @joohoi with quite a lot of questions and info over there - I suspect he might need some help sorting it out :D
