### ISSUE TITLE
How can I get the SSL for Apache on CentOS 6 ?

### ISSUE THREAD

**Issue by fannyyu** [certbot/certbot#5623]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

**Comment by schoen** [comment]
Hi @fannyyu ,

Please post your question on https://community.letsencrypt.org/. There is a much larger community there of people familiar with the project who will be able to more quickly answer your questions.

Thanks!
