### ISSUE TITLE
wildcat

### ISSUE THREAD

**Issue by Schildkroete1** [certbot/certbot#5629]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt

how can i get a widcat certificate

**Comment by trinopoty** [comment]
Wildcard support is still under development for Let's Encrypt.

**Comment by ohemorange** [comment]
This post has updates on launch: https://community.letsencrypt.org/t/acmev2-and-wildcard-launch-delay/
