### ISSUE TITLE
Can't update certificates.

### ISSUE THREAD

**Issue by oppsig** [certbot/certbot#5630]
## My operating system is (include version):
Ubuntu 17.10

## I ran this command and it produced this output:
./certbot-auto
also tried this:
sudo ./certbot-auto certonly -a webroot --webroot-path=/usr/share/nginx/html -d domain.com

```
Error: couldn't get currently installed version for /opt/eff.org/certbot/venv/bin/letsencrypt: 
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/main.py", line 4, in <module>
    import logging.handlers
  File "/usr/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref

```

**Comment by ohemorange** [comment]
Hi @oppsig. Sounds like this might be an issue with how Certbot interacts with your particular setup. I recommend posting to https://community.letsencrypt.org/ to get the fastest help, and including the log file from the `/var/log/letsencrypt` folder to provide more information. There is a much larger community there of people familiar with the project who will be able to more quickly answer your questions.
