### ISSUE TITLE
[WISHLIST]Certificate for courier-imap

### ISSUE THREAD

**Issue by schlabs2** [certbot/certbot#5643]
Courier-imap use a combined certificate, and is not generated by certboot.
The combined certificate can be generated with following command:

cat fullchain.pem  privkey.pem >combined.pem

I think that is not hard to add this funcionality

**Comment by strugee** [comment]
Duplicate of #5087

**Comment by schoen** [comment]
I've noted the benefit of this for courier-imap in #5087 and I'll close this one as a duplicate.

**Comment by stokito** [comment]
https://github.com/svarshavchik/courier/issues/10
