### ISSUE TITLE
Use __hash__ correctly in Nginx and Apache

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#5647]
From the documentation for [\_\_hash\_\_](https://docs.python.org/3/reference/datamodel.html#object.__hash__):

> If a class defines mutable objects and implements an \_\_eq\_\_() method, it should not implement \_\_hash\_\_(), since the implementation of hashable collections requires that a key’s hash value is immutable (if the object’s hash value changes, it will be in the wrong hash bucket).

We don't change vhosts after they're created often, but we do in a few places and this could lead to bugs like the ones Python is warning us about. Might be worth making these objects immutable or writing our own code to eliminate duplicates from a collection of vhosts at some point.

**Comment by ohemorange** [comment]
@sydneyli perhaps something to keep in mind for the redesign

**Comment by sydneyli** [comment]
Assuming this is referring to https://github.com/certbot/certbot/blob/12ab59e1fc6929c3d9d37090e4d66438f388ba5c/certbot-nginx/certbot_nginx/obj.py#L123  fully agreed! I might have more specific thoughts on this in the future.

**Comment by ohemorange** [comment]
Yup, that's the line.

**Comment by ohemorange** [comment]
This is still done incorrectly.
