### ISSUE TITLE
KeyError when using --manual-cleanup-hook with wildcard certificate

### ISSUE THREAD

**Issue by davejamesmiller** [certbot/certbot#5659]
## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Git - commit `31805c5`

## I ran this command and it produced this output:
```bash
$ certbot --noninteractive --manual --manual-public-ip-logging-ok --preferred-challenges dns --manual-auth-hook "/srv/letsencrypt-lexicon.sh auth" --manual-cleanup-hook "/srv/letsencrypt-lexicon.sh cleanup" --server https://acme-staging-v02.api.letsencrypt.org/directory --cert-name xenial.alberon.co.uk -d xenial.alberon.co.uk,*.xenial.alberon.co.uk -m dave@davejamesmiller.com --agree-tos
...
Traceback (most recent call last):
  File "/srv/certbot/venv/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/srv/certbot/certbot/main.py", line 1266, in main
    return config.func(config, plugins)
  File "/srv/certbot/certbot/main.py", line 1157, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/srv/certbot/certbot/main.py", line 118, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/srv/certbot/certbot/client.py", line 349, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/srv/certbot/certbot/client.py", line 293, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/srv/certbot/certbot/client.py", line 329, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/srv/certbot/certbot/auth_handler.py", line 82, in handle_authorizations
    self._respond(resp, best_effort)
  File "/srv/certbot/certbot/auth_handler.py", line 159, in _respond
    self._cleanup_challenges(active_achalls)
  File "/srv/certbot/certbot/auth_handler.py", line 304, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/srv/certbot/certbot/plugins/manual.py", line 218, in cleanup
    env = self.env.pop(achall.domain)
KeyError: u'xenial.alberon.co.uk'
```

## Certbot's behavior differed from what I expected because:
It crashed.

This only seems to happen when using `--manual-cleanup-hook` *and* including both `xenial.alberon.co.uk` and `*.xenial.alberon.co.uk`.

I think `self.env.pop(achall.domain)` gets called twice, both times with `achall.domain = 'xenial.alberon.co.uk'`, and the second time it's already been removed. I would guess the key needs to be changed to something else now that one domain may require two separate challenges.

## Here is a Certbot log showing the issue (if available):
https://gist.github.com/davejamesmiller/2a8c2f7a03cac9edd573c767a8fbedec

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
N/A

**Comment by schoen** [comment]
@ohemorange @bmw, this is a bug related to the handling of challenges for wildcard requests in ACMEv2, although it was triggered by running a development version and not a released version, so I wouldn't be surprised if it's already been fixed. I just wanted to point it out to be sure that you were aware of it.

**Comment by schoen** [comment]
@davejamesmiller , thanks for pointing out the problem you ran into. Development in this area is ongoing, so if you have time, could you periodically try again with more recent commits?

**Comment by bmw** [comment]
This is probably still an issue in `master`. Thanks for flagging.

**Comment by bmw** [comment]
While we do test something like this in `master`, we don't use a cleanup method because we're just using a dummy DNS server. This problem should be fixed in #5670. Thanks a lot for reporting this @davejamesmiller.

**Comment by davejamesmiller** [comment]
Thanks @bmw!

**Comment by agarwalanirudh** [comment]
Hi @davejamesmiller ,
Could you please help me with the manual-auth-hook script to be used in case of wildcard domains?
Couldn't find any documentation regarding this.
In case of FQDNs, we get $CERTBOT_DOMAIN and $CERTBOT_VALIDATION variables with the values to be added in TXT record.
What are the variables available in case of wildcard domains, how do we get 2 TXT record values and how are you handling them?

**Comment by davejamesmiller** [comment]
@agarwalanirudh I used [this script from Lexicon](https://github.com/AnalogJ/lexicon/blob/master/examples/certbot.default.sh). It is called twice - once for each record (and then again twice more for cleanup).

**Comment by agarwalanirudh** [comment]
Thanks!
