### ISSUE TITLE
deploy_hook fails in renewal configuration files

### ISSUE THREAD

**Issue by joshp23** [certbot/certbot#5660]
## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
1.  from git source
2.  from OS package manager via ppa:certbot/certbot

## I ran this command and it produced this output:
1.  /opt/letsencrypt/letsencrypt-auto renew --dry-run
2.  certbot renew --dry-run

both commands ran a successful dry run
## Certbot's behavior differed from what I expected because:
docs and `--help renew` both instruct the usage of `DEPLOY_HOOK`

with `deploy_hook = "some-command"` in the `/etc/letsencrypt/renewal/example.com.conf` file the hook was unseen.

with the deprecated `renew_hook = "some-command"` in the `/etc/letsencrypt/renewal/example.com.conf` file the hook was seen and properly ignored.

**Comment by schoen** [comment]
Hi @joshp23 ,

Certbot doesn't run ` deploy_hook` with a dry run:

https://github.com/certbot/certbot/blob/master/certbot/hooks.py#L202

If I recall correctly, this is because the dry run does not result in saving a certificate that the deploy hook would be able to act on, so it's not a realistic situation for the deploy hook script to react to.

Please let me know if this is different from the behavior that you see or if you can think of somewhere you'd like to see this documented better.

**Comment by schoen** [comment]
See also #5658.

**Comment by joshp23** [comment]
I understand that deploy hooks are not actively executed in a dry run, it makes sense that they are not since nothing was actually deployed.

When executing a dry run the output notes that there is a deploy hook if I place an executable in the deploy hook  folder. It notes that it is not executing it. Similarly, using renew_hook in the renew config file of a particular domain results in the same behavior... The hook is recognized and ignored in the output of the dry run command.

However, when using deploy_hook in the config file no hook is recognized (to be ignored).

So the issue is not that the hook isn't executed when using deploy_hook in the config, it appears to not be recognized ... Or at least acknowledged as the other two variants are... At all.

**Comment by maxsenft** [comment]
I also think the "--dry-run" part was a bit misleading.

certbot simply does not check for "deploy_hook" when parsing the renew configuration file. As it can be seen [here](https://github.com/certbot/certbot/blob/master/certbot/renewal.py#L31), only "renew_hook" is part of the array, but not "deploy_hook".

As it was stated [here](https://community.letsencrypt.org/t/generating-certificates-for-use-in-pound/44091/5), the argument "--renew-hook" will be deprecated and it is recommended to use "--deploy-hook".

So, overall: It just seems like this renaming has not been done yet in the renewal.py script ...

**Comment by joshp23** [comment]
> So, overall: It just seems like this renaming has not been done yet in the renewal.py script ...
Yeah. That was what I was getting at. My intention was to merely bring awareness to the need for renaming.

**Comment by bmw** [comment]
Keeping the name `renew_hook` in the renewal configuration file was done for simplicity of migrating users from the old `--renew-hook` flag and the `--deploy-hook` flag. When it comes time for renewal, the flags are identical.

Also, I usually encourage people to avoid manually editing the files in `/etc/letsencrypt/renewal` as it is very error prone, however, I do see how this could be confusing. We should probably modify Certbot to translate the name `renew_hook` to `deploy_hook` in renewal configuration files so it  matches the CLI flags like the other options (more or less) do.

**Comment by bmw** [comment]
@schoen, I just noticed you had tagged this as won't fix. If you disagree with my previous post, let's chat! I can probably be convinced.

**Comment by bmw** [comment]
I still think this has some value, but because we never recommend people edit these files by hand, I think its value is quite small. Because of that, I think this something we'll probably realistically never get to so I'm closing this issue.
