### ISSUE TITLE
Documentation about DNS credential files extremly hard to find... even for 0.22

### ISSUE THREAD

**Issue by noci2012** [certbot/certbot#5663]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Gentoo-Linux 17.0

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot v0.21.1 is installed with emerge 
pip install --user for dns-rfc2163
https://pypi.python.org/pypi/certbot-dns-rfc2136/0.21.1

## I ran this command and it produced this output:
 certbot certonly --dry-run --agree-tos --preferred-challenges dns --dns-rfc2136 --dns-rfc2136-credentials /etc/letsencrypt/example.ini  -d example.comf
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-rfc2136, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for example.com
Cleaning up challenges
Encountered exception during recovery
Encountered error when making query: Text input is malformed.
Traceback (most recent call last):                                                                                                                                           
  File "/root/.local/lib64/python3.5/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 207, in _query_soa                                                              
    response = dns.query.udp(request, self.server)                                                                                                                           
  File "/root/.local/lib64/python3.5/site-packages/dns/query.py", line 242, in udp                                                                                           
    if _addresses_equal(af, from_address, destination) or \                                                                                                                  
  File "/root/.local/lib64/python3.5/site-packages/dns/query.py", line 169, in _addresses_equal                                                                              
    n2 = dns.inet.inet_pton(af, a2[0])                                                                                                                                       
  File "/root/.local/lib64/python3.5/site-packages/dns/inet.py", line 51, in inet_pton                                                                                       
    return dns.ipv4.inet_aton(text)                                                                                                                                          
  File "/root/.local/lib64/python3.5/site-packages/dns/ipv4.py", line 48, in inet_aton                                                                                       
    raise dns.exception.SyntaxError                                                                                                                                          
dns.exception.SyntaxError: Text input is malformed.                                                                                                                          

During handling of the above exception, another exception occurred:                                                                                                          

Traceback (most recent call last):                                                                                                                                           

## Certbot's behavior differed from what I expected because:
well i didn't expect much, the problem is related to the credential.ini file somehow,
except that the contents must be secret as it is impossible to find some docmentation on credential files.
Changes in the file make more sensible errors appear about f.e. missing data if it is empty or contains  a section header ('[xxx]')

Some Description is welcome...

**Comment by noci2012** [comment]
# TSIG keyname 
dns_rfc2136_name=certbot-key
# TSIG key algorithm
dns_rfc2136_algorithm=HMAC-Somewhat
# TSIG key secret
dns_rfc2136_secret= whatever
# TSIG DNS server
dns_rfc2136_server=dns-server.local

**Comment by noci2012** [comment]
not using a hostname but ipv4 address does solve this issue...., 
mistyping an ipv6 address (one colon too many).... delivers:
An unexpected error occurred:
The request message was malformed :: Error creating new authz :: Invalid character in DNS name

So why would a Domain name not work....
well anyway: whatever the credentials i supply the access remains REFUSED...

the DNS server declares that updates to example.com are forbidden.....,
example.com IS forbidden, there is an NS record for _acme-challenge.example.com
a SOA record for _acme-challenge.example.com a separate ZONE for _acme-challenge.example.com
(all NS pointing the the master Bind server).  this zone is writable for the certbot.

why the attempt to insert the record in the example.com?

**Comment by noci2012** [comment]
In summary -- Documentation leaves something to be desired.
and code is not consistent and might lack proper support for or documentation of 
signing & proper requests.

**Comment by schoen** [comment]
Hi @noci2012 , did you eventually get this to work or do you think the plugin's functionality may be entirely broken in this configuration?

**Comment by noci2012** [comment]
I have not got it to work... but due to lack of a good description of what to expect and what to do when it breaks... imho it takes a little bit too long to figure out what might be expected... and if problems are implementation errors or configuration errors or just a bad setup...?

i could insert a txt record easily with nsupdate, which makes me think the module is lacking somewhere.
First hurdle: connection is refused....

in DNS: 
example.com Zone:
example.com.             SOA ns.example.com root.example.com ( ... )
example.com              NS ns.example.com
ns.example.com         A 192.168.1.1
_acme-challenge.example.com NS ns.example.com

Other zone:
_acme-challenge.example.com SOA ns.example.com root.exampe.com (   )

In the above config nsupdate works, dns_rfc2136 module does not.

Obviously names have been changed a little, and the HMAC-MD5 is actually a valid base64 string (even without special characters)
Python i can read but it's not a language i touched a lot.

**Comment by noci2012** [comment]
These are the error message:
```
Plugins selected: Authenticator dns-rfc2136, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for example.com
Cleaning up challenges
Encountered exception during recovery
Received response from server: REFUSED
Traceback (most recent call last):                                                                                                                                           
  File "/usr/lib64/python3.5/site-packages/certbot/auth_handler.py", line 115, in _solve_challenges                                                                          
    resp = self.auth.perform(self.achalls)
  File "/usr/lib64/python3.5/site-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/root/.local/lib64/python3.5/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 74, in _perform
    self._get_rfc2136_client().add_txt_record(domain, validation_name, validation, self.ttl)
  File "/root/.local/lib64/python3.5/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 132, in add_txt_record
    .format(dns.rcode.to_text(rcode)))
certbot.errors.PluginError: Received response from server: REFUSED

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/certbot/error_handler.py", line 100, in _call_registered
    self.funcs[-1]()
  File "/usr/lib64/python3.5/site-packages/certbot/auth_handler.py", line 284, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/usr/lib64/python3.5/site-packages/certbot/plugins/dns_common.py", line 76, in cleanup
    self._cleanup(domain, validation_domain_name, validation)
  File "/root/.local/lib64/python3.5/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 77, in _cleanup
    self._get_rfc2136_client().del_txt_record(domain, validation_name, validation)
  File "/root/.local/lib64/python3.5/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 168, in del_txt_record
    .format(dns.rcode.to_text(rcode)))
certbot.errors.PluginError: Received response from server: REFUSED
Received response from server: REFUSED
```
The refused is with the same secret as in nsupdate.
(no quote marks, no special characters. ).

**Comment by schoen** [comment]
@joohoi , could you please take a look at this problem as well?

**Comment by joohoi** [comment]
I think the issue is mainly that the current implementation of `certbot-dns-rfc2136` starts searching for the proper `SOA` record from the domain up. It is currently skipping the `_acme-challenge` subdomain, and when it finds the most specific delegation apex, it will use this as a base, creating a `TXT` `ResourceRecordSet` with a name `_acme-challenge`. 

Unfortunately the current functionality does not work with the configuration described in the issue, as the most specific `SOA` record it's able to find because of the reasons described above, is `example.com` instead of `_acme-challenge.example.com`. If the delegation apex would be `first.example.com` for the domains `*.first.example.com` (hence the challenge records being `_acme-challenge.first.example.com` and so on, this would work.

**Comment by noci2012** [comment]
problem is the example.com is the (zone) domain that i can control.
the intention is to get *.example.com certificate later on.  So how to continue on this path.
For wildcards i still get: 'Wildcard domains are not supported: *.example.org'

With nsupdate there is only one string, isn't it possible to emulate the nsupdate behaviour?
Or if it should check for a SOA record for _acme-challenge.example.com and contiue from there.

**Comment by noci2012** [comment]
Success:

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-rfc2136, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for example.com
Waiting 60 seconds for DNS changes to propagate
Waiting for verification...
Cleaning up challenges

IMPORTANT NOTES:
 - The dry run was successful.


After the next code change:

```    def _find_domain(self, domain_name):
        """
        Find the closest domain with an SOA record for a given domain name.

        :param str domain_name: The domain name for which to find the closest SOA record.
        :returns: The domain, if found.
        :rtype: str
        :raises certbot.errors.PluginError: if no SOA record can be found.
        """

        domain_name_guesses = dns_common.base_domain_name_guesses(**'_acme-challenge.'+**domain_name)

        # Loop through until we find an authoritative SOA record
        for guess in domain_name_guesses:
            if self._query_soa(guess):
                return guess

        raise errors.PluginError('Unable to determine base domain for {0} using names: {1}.'
                                 .format(domain_name, domain_name_guesses))
```

**Comment by noci2012** [comment]
Right this could work, now the documentation is left...

**Comment by noci2012** [comment]
https://github.com/certbot/certbot/pull/5692

**Comment by noci2012** [comment]
https://github.com/certbot/certbot/pull/5694

**Comment by bodgit** [comment]
The documentation is in the Python code, found [here](https://github.com/certbot/certbot/blob/master/certbot-dns-rfc2136/certbot_dns_rfc2136/__init__.py) the same as the other DNS authenticators, including a description and example of the .ini file.

**Comment by noci2012** [comment]
Ang how would that showup?   
certbot --help certonly --dns-rfc2136 
or 
certbot --help certonly 

don't show anything, except the existence of --dns-rfc2136...
btw. is it by design that DNS servers need to be mentioned by ip addresses? as a hostname didn;t work.

**Comment by bodgit** [comment]
The documentation should be viewable with `pydoc` or processed into HTML so it should appear on https://letsencrypt.readthedocs.io/en/latest/# although I can't find it there, but I think that's endemic to all of the DNS plugins TBH.

Using a hostname _should_ work, if it doesn't then that's likely a bug.

**Comment by bodgit** [comment]
It's using the [dnspython](http://www.dnspython.org/) library under the hood and looking at http://www.dnspython.org/docs/1.15.0/dns.query-module.html#tcp shows it expects either an IPv4 or IPv6 address, so it's a limitation of that library. It needs an intermediate resolver step in the case the server is specified by hostname.

**Comment by noci2012** [comment]
ok thanks,

@bodgit, how about https://github.com/certbot/certbot/pull/5692 ?

**Comment by noci2012** [comment]
And this add hostname translation...   https://github.com/certbot/certbot/pull/5697

**Comment by noci2012** [comment]
New rq: https://github.com/certbot/certbot/pull/5707

**Comment by noci2012** [comment]
Now here:   https://letsencrypt.readthedocs.io/en/latest/using.html?highlight=dns#dns-plugins
