### ISSUE TITLE
ACMEv2: Use newNonce for nonce?

### ISSUE THREAD

**Issue by magnuswatn** [certbot/certbot#5666]
If acme doesn't have a nonce stored, it does a HEAD to the same resource it's about to POST to, to get a nonce. This works as long as the server responds with a nonce on that resource, but it is not required to according to the spec. A HEAD will (often) return an error, and the spec says:

> ...and SHOULD provide it in error responses as well.

Should the acme client relay on a SHOULD? According to the spec, clients should use the newNonce url to get fresh nonces.

**Comment by magnuswatn** [comment]
One way to fix this would be to give ClientNetwork a nonce_source attribute, and use that (if not None). It could default to None, and be explicit set from the directory when initializing ClientV2.

**Comment by schoen** [comment]
Hi @magnuswatn ,

I'd like to suggest that you discuss ACMEv2 protocol issues in

https://community.letsencrypt.org/

(there's a "Client Dev" topic category and we can probably get several people with relevant interests involved), or conceivably in

https://github.com/letsencrypt/boulder/issues

although I would probably advocate for bringing them up on the Community Forum.

I hope you get the replies you need (and I'm happy to help tag people on the forum if you decide to post there).

Thanks.

**Comment by magnuswatn** [comment]
Hi @schoen!

Sorry, I worded myself badly here. This was meant as a bug report for the (python) acme client that certbot uses. It should, according to the acme draft, get a new nonce from the newNonce endpoint, and it does not. This can cause compatibility issues with some servers.

It's, off course, fine if you don't think this is an issue that needs fixing, but then it deserves a "wontfix" tag :-)
