### ISSUE TITLE
Nginx-Naxsi with Certbot

### ISSUE THREAD

**Issue by heythereparis** [certbot/certbot#5683]
Hi,
I create an Azure VM (Ubuntu 16).
I installed Nginx-Naxsi and I got it to work fine. I was able to have redirect to the website I created.

The issue comes when I try to install cerbot using: apt-get install python-certbot-nginx

When installing I get:
nginx[104162]: nginx: [emerg] unknown directive “MainRule” in /etc/nginx/naxsi_core.rules:19
nginx[104162]: nginx: configuration file /etc/nginx/nginx.conf test failed
systemd[1]: nginx.service: Control process exited, code=exited status=1
systemd[1]: Failed to start A high performance web server and a reverse proxy server.
systemd[1]: nginx.service: Unit entered failed state.
systemd[1]: nginx.service: Failed with result ‘exit-code’.

Error while running nginx -c /etc/nginx/nginx.conf -t.

nginx: [emerg] unknown directive “MainRule” in /etc/nginx/naxsi_core.rules:19
nginx: configuration file /etc/nginx/nginx.conf test failed

The nginx plugin is not working; there may be problems with your existing configuration.
The error was: MisconfigurationError(‘Error while running nginx -c /etc/nginx/nginx.conf -t.\n\nnginx: [emerg] unknown directive “MainRule” in /etc/nginx/naxsi_core.rules:19\nnginx: configuration file /etc/nginx/nginx.conf test failed\n’,)

I have tried to comment out the line 19 in the naxsi_core file, but then it wants to me to comment every line after that.

Is there a solution so I can have Nginx/Naxsi work with Let’s Encrypt/Certbot?

Thanks!

**Comment by sydneyli** [comment]
How did you install naxsi? I believe naxsi requires you to compile `nginx` with their own module, and it seems that certbot is using a version of nginx that is not compiled with the module that understands how to read `naxsi_core.rules`.

**Comment by heythereparis** [comment]
@sydneyli I installed Naxsi using this: https://blog.rapid7.com/2017/06/24/how-to-install-and-configure-naxsi-firewall-on-ubuntu-linux/

**Comment by sydneyli** [comment]
@heythereparis I just tested this out myself, and wasn't able to reproduce your issue-- from certbot's side this should work. It seems you've also posted in [the community forums](https://community.letsencrypt.org/t/nginx-naxsi-with-certbox/55039/12)-- I'll continue replying there as well!

**Comment by sydneyli** [comment]
Yes. I replied to you w/ more detail on the forums!
