### ISSUE TITLE
v2: No need to send "keyAuthorization" in challenge completion

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#5686]
In ACMEv2, we've removed the requirement to send "keyAuthorization" in the POST body when completing a challenge. Certbot currently sends it, and Boulder will ignore it. But Pebble rejects it. It would be nice to update `acme` to avoid sending "keyAuthorization" on challenge POSTs.

**Comment by bmw** [comment]
This was fixed in our 0.32.0 release.
