### ISSUE TITLE
[Debian] Certbot-auto cannot be installed if its dependencies were upgraded by backports

### ISSUE THREAD

**Issue by Keyhaku** [certbot/certbot#5698]
## My operating system is : 
Debian Jessie 8.6

## I installed Certbot with
certbot-auto

## I ran this command and it produced this output:
Command : `certbot --os-packages-only`
Output : 
```Building dependency tree
Reading state information... Done

gcc is already the newest version.

gcc set to manually installed.

python is already the newest version.

python set to manually installed.

python-dev is already the newest version.

python-dev set to manually installed.

Some packages could not be installed. This may mean that yo have

requested an impossible situation or if you are using the unstable

distribution that some required packages have not yet been created

or been moved out of Incoming.

The following information may help to resolve the situation:



The following packages have unmet dependencies:

 libssl-dev : Depends: libssl1.0.0 (= 1.0.1t-1+deb8u7) but 1.0.2l-1~bpo8+1 is to be installed

E: Unable to correct problems, you have held broken packages.
```

## Certbot's behavior differed from what I expected because:

Certbot was not installed correctly

## The relevant code
`In BootstrapDebCommon()`

`
apt-get install $QUIET_FLAG $YES_FLAG --no-install-recommends \
   python \
   python-dev \
   $virtualenv \
   gcc \
   $augeas_pkg \
   openssl \
   libffi-dev \
   libssl-dev \
   ca-certificates \
`

It was resolved by spliting the command
`apt-get install $QUIET_FLAG $YES_FLAG --no-install-recommends -t jessie-backports libssl-dev`

**Comment by joohoi** [comment]
I wonder if you already had one or more of the packages that `certbot-auto` is trying to install from `jessie-backports`?

**Comment by Keyhaku** [comment]
Hi,

It's not that certbot is trying to install some packages from jessie-backports, is that some packages, here `libssl1.0.0` were upgraded, because we installed haproxy from backports (1.7.5-2~bpo8+1).
Certbot is trying to install libssl-dev that depends on libssl1.0.0.

**Comment by joohoi** [comment]
I wonder if @hlieberman has an idea what's going on in here?

**Comment by hlieberman** [comment]
I believe what's happening here is that apt is treating the command `apt-get install libssl-dev` as a request to install the stable version of libssl-dev, which strictly requires the same version of libssl1.0.0 to be installed.  If the backports version of libssl1.0.0 is installed, but the backports version of libssl-dev isn't, then this causes a conflict as apt has no way to install libssl-dev.

Though the workaround listed will certainly work, I'm not 100% sure of the easiest way to solve this in the installer. The logic isn't that trivial.  One option would be to simply check if backports is being used, and then add `-t jessie-backports` on the install line.  That's pretty aggressive, though, and is "surprising" behavior for the installer.

**Comment by Alex237** [comment]
Hello,
i might have found why we have this. in my case, i have HAPROXY installed, and it use a specific version of libssl. i have tried to install on other debuan with the same config and without haproxy installed, and it's work!
i think @Keyhaku you have somthing installed that require a specific version of libssl and once installed cannot be change

**Comment by mattimac** [comment]
I have exact same problem on unifi cloud key when trying to acquire LE certificate following this guide:
https://community.ui.com/questions/How-To-Lets-Encrypt-with-Cloud-Key-and-DNS-Challenge/5dc4f896-3e60-42a2-82b8-2cf7fe2279fc
after issuing the command 
`letsencrypt/letsencrypt-auto certonly --manual --preferred-challenges dns --email myemail --domains my domain
`
i get
`apt-get update hit problems but continuing anyway...
Reading package lists... Done
Building dependency tree
Reading state information... Done
python is already the newest version.
ca-certificates is already the newest version.
openssl is already the newest version.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libssl-dev : Depends: libssl1.0.0 (= 1.0.1t-1+deb8u11) but 1.0.2l-1~bpo8+1 is to be installed
E: Unable to correct problems, you have held broken packages.
root@UniFi-CloudKey:/home# ^C
root@UniFi-CloudKey:/home#  Depends: libssl1.0.0 (= 1.0.1t-1+deb8u11) but 1.0.2l-1~bpo8+1 is to be installed
`
already tried this and added to apt sources:
`https://unix.stackexchange.com/a/508728`
