### ISSUE TITLE
Feature request: manual hook for success/failure

### ISSUE THREAD

**Issue by pinkladywithcoco** [certbot/certbot#5704]
I'm using Certbot with the **--manual** option on macOS Sierra version 10.12.6. This way i can use my own scripts.

I want to request another manual hook that can run after:

**--manual-auth-hook**
 and 
**--manual-cleanup-hook** 

The hook must pass environment variable to indicate success/failure to our script.

This will allow us to do something incase of   success/failure, specially if some errors were reported by the server.

**Comment by bmw** [comment]
I'm curious if you can get the behavior you want without us adding another hook. As a starting point, if you want to do something based on whether all of Certbot succeeds or fails, you can use Certbot's [exit status](https://www.tldp.org/LDP/abs/html/exit-status.html).

If you want to do something if Certbot successfully obtain you a cert, you can use `--deploy-hook`. This will only be called if a cert was successfully obtained.

Using Certbot's exit status and deploy hooks, can you get the behavior you want?

**Comment by bmw** [comment]
It's been almost a year and I never got a response so I'm closing this issue. If you or others still want this, please comment or open a new issue explaining why the options I laid out above don't work for you.
