### ISSUE TITLE
Improve certbot-dns-route53 docs

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5709]
Jacob wrote the following which should probably be merged with the existing docs. Documentation like this was proposed before, but rejected due to it not being the best practice according to Amazon, but I think we should reconsider that decision. This feedback came from https://github.com/lifeonmarspt/certbot-route53/pull/3#discussion_r106011990.

Jacob's instructions were:

I've got the latest certbot master issuing wildcard+basedomain on le-test.example.com! Woo! I wrote up instructions on how I did it. 
In Route53, create a new hosted zone for le-test.example.com
Delegate from example.com to le-test.example.com by copying the NS records from the new hosted zone, and using them to create an NS record set in the example.com zone, containing those NS records.
Get the hosted zone id for the new le-test.example.com zone by clicking on that zone, and copying the slug from the last part of the URL.
Go to IAM, click Policies -> Create Policy -> JSON, and paste this in, modifying the zone ID to match yours:
```
{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Action": [
"route53:ListHostedZones",
"route53:GetChange"
],
"Resource": [
"*"
]
},
{
"Effect": "Allow",
"Action": [
"route53:ChangeResourceRecordSets"
],
"Resource": [
"arn:aws:route53:::hostedzone/MY_ZONE_ID_GOES_HERE_PLEASE"
]
}
]
}
```
In IAM, Go to Users -> Add user. Pick a name (doesn't matter) and check Programmatic access. Click Next: Permissions. Click "Attach existing policies directly." Search for the policy you created above, and select it. Click "Next: Review", then "Create user". On that screen, copy down the "access key id" and "secret access key". 
Log on to letest, and run:
sudo apt install awscli
aws configure # This will prompt for the credentials from the web page
git clone https://github.com/certbot/certbot
cd certbot
./tools/venv.sh
source venv/bin/activate
mkdir ~/cb-work # So we can run as non-root
certbot --config-dir ~/cb-work --work-dir ~/cb-work --logs-dir ~/cb-work certonly --server https://acme-staging-v02.api.letsencrypt.org/directory -a dns-route53 --email letest@example.com --agree-tos --no-eff-email -d '*.dns123.le-test.example.com' -d 'dns123.le-test.example.com'

**Comment by jsha** [comment]
Note: We may want to get a little fancier and include instructions on how to create a dedicated zone for validations.

**Comment by bmw** [comment]
Closing this 4 year old issue for now. If someone thinks it's still a problem, please open a new issue/PR or add a comment here.
