### ISSUE TITLE
Docker Hub description for DNS plugins

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5711]
I just edited these manually, but I think my changes will be overwritten by the README in the next release. We should check if this is the case and if so, update the relevant READMEs to include correct info.

**Comment by joohoi** [comment]
I looked into this, and it appears to be impossible to either have a static description in Docker Hub, or make it update from a separate `README.md`. The only option is, as stated above to modify the main `README.md` to include the relevant information. 

This is suboptimal at best and makes me wonder if the Docker people would have suggestions to work around this. Either in the current form, or as a curated, "official" image.

**Comment by bmw** [comment]
> We currently have README.rst files, but changing them to .md should do the trick!

Are you saying have both? `README.rst` for our packages and `README.md` for Docker Hub. Do you know what GitHub prioritizes?

> The other option - official builds would also fix the issue for us, but adding, reviewing and maintaining an evergrowing list of plugins in Certbot might be a bit much for the Docker Hub team.

Did you talk to them about this at all or was it just something you thought about as an option?

**Comment by joohoi** [comment]
> Did you talk to them about this at all or was it just something you thought about as an option?

The initial question was based on two approaches to make the descriptions stick, and that was the speculative answer.

**Comment by joohoi** [comment]
I suggest we create a `README.md` that's suitable for GitHub and Docker Hub for each of the DNS plugins. This should be manageable as the amount of required information is much less than what we have in our main `README.md`, and I believe can be formatted to be usable and accessible for both, GitHub and Docker Hub users.

For PyPI we can pretty much [decide the source file](https://github.com/certbot/certbot/blob/master/setup.py#L27) for the source of the description.

**Comment by bmw** [comment]
The main problem I'm having here is for Docker users, we almost certainly want them to look at https://certbot.eff.org/docs/install.html#running-with-docker. For instance, if you're using standalone and aren't mapping the ports through to the docker container, you're going to have a bad time.

People reading our README outside of Docker Hub don't certainly need this though. We could have a section like we do in our docs called "Running with Docker", but using that in our Docker Hub description seems awkward. Alternatively we could make the Docker instructions very prominent, but then it will look out of place elsewhere.

If both GitHub and Docker Hub prefer `README.md` files, we can't play precedence games there. We could potentially move the Dockerfiles to another directory with their own README, but then we'd have to do strange things like pulling Certbot with `git` rather than using the local copy which seems bad.

Unless there are other options I'm missing, I think we just try and make the single README work the best we can.
