### ISSUE TITLE
Can't parse RewriteCond with empty string in conditional

### ISSUE THREAD

**Issue by mattf10** [certbot/certbot#5714]
@domcleal - saw this in ticket #3536:

> If anybody else has Apache config file parse failures, please file a new ticket at https://github.com/letsencrypt/letsencrypt/issues/new to avoid more confusion, and feel free to mention @domcleal so I can try and help.

I have the same problem.  Here is my the offending section of my conf file:
`RewriteMap proprefs "txt:/home/matt/public/propertiesbordeaux.com/property_reference_map.txt"
  
  RewriteCond %{REQUEST_URI} ^/[^_]+_([A_Z0-9]+)/?$
  RewriteCond ${proprefs:$1} !=""
  RewriteRule ^/[^_]+_([A_Z0-9]+)/?$	/q/${proprefs:$1}/`

When trying to generate a cert, here is the error:

`The error was: PluginError('There has been an error in parsing the file /etc/apache2/sites-enabled/pb.com.conf on line 110: Syntax error',)`

Note that I Apache doesn't have any problems with the conf and the server starts with no issues.

I see there was a similar issue reported as fixed (#429) but apparently, it's still a problem.

**Comment by ohemorange** [comment]
@mattf10, could you confirm what version of Certbot you're using? You can find this by running `certbot --version`. Also, posting the entire offending conf file could help us debug this issue.

**Comment by mattf10** [comment]
Version is certbot 0.22.2.

For the time being, I have found a work-around.  Change the 2nd Condition so it doesn't require the double quotes, like so:
`RewriteCond ${proprefs:$1} .+`

Here is the conf file:
`<VirtualHost *:443>
  # Admin email, Server Name (domain name), and any aliases
  ServerAdmin contact@port80services.com
  ServerName  propertiesbordeaux.com
  ServerAlias www.propertiesbordeaux.com
  ServerAlias proprietesbordeaux.fr www.proprietesbordeaux.fr
  ServerAlias maxwellstorriebaynes.com	www.maxwellstorriebaynes.com

  # Index file and Document Root (where the public files are located)
  DirectoryIndex index.php
  DocumentRoot /home/matt/public/propertiesbordeaux.com/public

  # Log file locations
  LogLevel warn
  ErrorLog  /home/matt/public/propertiesbordeaux.com/log/error.log
  CustomLog /home/matt/public/propertiesbordeaux.com/log/access.log combined
      
  RewriteEngine On
  
  # declare the map
  RewriteMap proprefs "txt:/home/matt/public/propertiesbordeaux.com/property_reference_map.txt"
  
  RewriteCond %{REQUEST_URI} ^/[^_]+_([A-Z]{0,3}[0-9]+)/?$
  RewriteCond ${proprefs:$1} !=""
  RewriteRule ^/[^_]+_([A-Z]{0,3}[0-9]+)/?$	/q/${proprefs:$1}/
  
  #some don't have text in the url, in this case, they're just UC letters + numbers
  RewriteCond %{REQUEST_URI} ^/([A-Z]{0,3}[0-9]+)/?$
  RewriteCond ${proprefs:$1} !=""
  RewriteRule  ^/([A-Z]{0,3}[0-9]+)/?$	/q/${proprefs:$1}/

  # now redirect everything which includes rewritten urls from above
  RewriteRule ^/?(.*)$ https://www.maxwellbaynes.com/$1	[L,R=301]
  
    <Directory /home/matt/public/propertiesbordeaux.com/public/>
    Require all granted
	
	Options All -Indexes
	
	AllowOverride All
	  
  </Directory>

SSLCertificateFile /etc/letsencrypt/live/propertiesbordeaux.com/cert.pem
SSLCertificateKeyFile /etc/letsencrypt/live/propertiesbordeaux.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateChainFile /etc/letsencrypt/live/propertiesbordeaux.com/chain.pem
</VirtualHost>
</IfModule>`

**Comment by ohemorange** [comment]
@joohoi, is this enough information?

**Comment by bmw** [comment]
I believe this issue was fixed in version 0.28.0 of the Apache plugin. If anyone is still hitting this issue, please comment or open a new issue with the relevant lines in your Apache config.
