### ISSUE TITLE
Missing le_http_01_cert_challenge.conf config

### ISSUE THREAD

**Issue by KeiroD** [certbot/certbot#5715]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 14.04 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Package manager, via certbot.eff.org config

## I ran this command and it produced this output:

root@heimkoma:~# certbot --nginx certonly
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Error while running nginx -c /etc/nginx/nginx.conf -t.

nginx: [emerg] open() "/etc/letsencrypt/le_http_01_cert_challenge.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:11
nginx: configuration file /etc/nginx/nginx.conf test failed

Could not choose appropriate plugin: The nginx plugin is not working; there may be problems with your existing configuration.
The error was: MisconfigurationError('Error while running nginx -c /etc/nginx/nginx.conf -t.\n\nnginx: [emerg] open() "/etc/letsencrypt/le_http_01_cert_challenge.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:11\nnginx: configuration file /etc/nginx/nginx.conf test failed\n',)
The nginx plugin is not working; there may be problems with your existing configuration.
The error was: MisconfigurationError('Error while running nginx -c /etc/nginx/nginx.conf -t.\n\nnginx: [emerg] open() "/etc/letsencrypt/le_http_01_cert_challenge.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:11\nnginx: configuration file /etc/nginx/nginx.conf test failed\n',)
root@heimkoma:~# ls -l /etc/letsencrypt/
total 24
drwx------ 3 root root 4096 Mar 13 09:15 accounts
-rw-r--r-- 1 root root  121 Jan 30 21:02 cli.ini
-rw-r--r-- 1 root root 1143 Mar 13 09:15 options-ssl-nginx.conf
drwxr-xr-x 2 root root 4096 Mar 13 09:15 renewal
drwxr-xr-x 5 root root 4096 Mar 13 09:12 renewal-hooks
-rw-r--r-- 1 root root  424 Mar 13 09:15 ssl-dhparams.pem

## Certbot's behavior differed from what I expected because:
Why was it not able to create a new challenge.conf file as described per log?

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

https://paste.ituralde.com/roliroqibi

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
https://paste.ituralde.com/jiyonelota

**Comment by ohemorange** [comment]
Seems like there's a bunch of cascading errors going on here, including a possible issue on our part in cleaning up config changes we made.

I'd recommend removing the lines labelled `# managed by Certbot`, deleting the entire second server block, and trying again.

This recommendation comes from the assumption that this config was copied from somewhere, because it looks like the file `/etc/nginx/ssl/fullchain.pem` doesn't exist. Certbot needs Nginx to have a valid config to work properly.

**Comment by KeiroD** [comment]
>lines labelled `# managed by Certbot`, deleting the entire second server block, and trying again.

Will attempt this. As for the config, not entirely certain what you mean by this but I'll answer as best as I can. The `# managed by Certbot` wasn't an addition by me. The `nginx` config was  a default one written by `mailinabox.email`. As far as I can tell, it's a valid `nginx` config aside from the certificate issues. However, I was able to work around the issue by using `acme.sh` to generate a temporary setup until I could work out the issue with Certbot.

I'll provide an update on this a little later tonight as I'll have time to dig deeper into this at that time and provide an update on what worked and what didn't.

**Comment by ohemorange** [comment]
Hi @KeiroD, any update?

**Comment by ohemorange** [comment]
Closing this issue from staleness; feel free to update if it's still an issue.
