### ISSUE TITLE
Hook scripts directory structure not present after installing Certbot

### ISSUE THREAD

**Issue by Visnetje** [certbot/certbot#5716]
Since Certbot 0.19 it is possible to place hook scripts in `/etc/letsencrypt/renewal-hooks/`. Unfortunately this directory, including its subdirectories (pre, deploy, post) are _not_ immediately available with the installation of Certbot.

This folder structure for hook scripts seems to become available with the first attempt of obtaining a Let's Encrypt certificate. This makes it impossible to place hook scripts in these folders for usage with the first certificate obtain command, since the folder does not exist yet.

Request: please include the creation of the folder structure for `/etc/letsencrypt/` (including `/etc/letsencrypt/renewal-hooks/` and its subfolders) in the installation of Certbot. 

## My operating system is (include version):

CentOS Linux release 7.4.1708 (Core)

## I installed Certbot with OS package manager:

Using `yum install certbot`.

## I ran this command and it produced this output:

Note: I replaced the real domain with "example.com"
```
# rpm -q certbot
package certbot is not installed
# stat /etc/letsencrypt
stat: cannot stat ‘/etc/letsencrypt’: No such file or directory
# yum install certbot
# rpm -q certbot
certbot-0.21.1-1.el7.noarch
# stat /etc/letsencrypt/
stat: cannot stat ‘/etc/letsencrypt/’: No such file or directory

# /usr/bin/certbot certonly --staging -n --text --expand --agree-tos --webroot -w '/var/www/example.com/public/' -d 'example.com' --rsa-key-size 2048
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for example.com
Waiting for verification...
Cleaning up challenges

(...)
# tree /etc/letsencrypt/
/etc/letsencrypt/
├── accounts
│   └── acme-staging.api.letsencrypt.org
│       └── directory
│           └── 51eaca0ac6a962c3d854993e797b0e75
│               ├── meta.json
│               ├── private_key.json
│               └── regr.json
├── archive
│   └── example.com
│       ├── cert1.pem
│       ├── chain1.pem
│       ├── fullchain1.pem
│       └── privkey1.pem
├── csr
│   └── 0000_csr-certbot.pem
├── keys
│   └── 0000_key-certbot.pem
├── live
│   └── example.com
│       ├── cert.pem -> ../../archive/example.com/cert1.pem
│       ├── chain.pem -> ../../archive/example.com/chain1.pem
│       ├── fullchain.pem -> ../../archive/example.com/fullchain1.pem
│       ├── privkey.pem -> ../../archive/example.com/privkey1.pem
│       └── README
├── renewal
│   └── example.com.conf
└── renewal-hooks
    ├── deploy
    ├── post
    └── pre

15 directories, 15 files
```

## Certbot's behavior differed from what I expected because:

I would expect it to be possible to place hook scripts in `/etc/letsencrypt/renewal-hooks/deploy/` for usage with `certbot certonly --deploy-hook '/etc/letsencrypt/renewal-hooks/deploy/script-name'` with the first certificate request on a server.

**Comment by ohemorange** [comment]
We don't create these folders on install because we allow users to specify the location of Certbot's folders at runtime. Doing it this way lets people without root on their machines use Certbot by choosing an alternate location of `/etc/letsencrypt` and other folders. I agree that this feature would be nice to have, but reconciling these two constraints is hard.

For now, you can solve this by running `certbot certificates` before attempting to issue your first cert. This is essentially our `ls` command, but it has the side effect of creating the folders you need.
