### ISSUE TITLE
Release certbot v0.22 to the ppa

### ISSUE THREAD

**Issue by akarelas-pt** [certbot/certbot#5723]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager

The ppa has v0.21, but only v0.22 (released 7 days ago) can do wildcards.

**Comment by tofifee** [comment]
According to

[Ubuntu 16.04 PPA: How long until Certbot 0.22.0 available?](https://community.letsencrypt.org/t/ubuntu-16-04-ppa-how-long-until-certbot-0-22-0-available/55613l)

it will most likely take several weeks.

At the moment approaches like [this](https://community.letsencrypt.org/t/ubuntu-16-04-ppa-how-long-until-certbot-0-22-0-available/55613/9) - 

`git clone https://github.com/certbot/certbot
cd certbot
git checkout v0.22.0
sudo ./certbot-auto --os-packages-only
./tools/venv.sh
source venv/bin/activate
sudo ./certbot -d domain.com -d *.domain.com --manual --preferred-challenges dns-01 --server https://acme-v02.api.letsencrypt.org/directory certonly`

can work around that issue.

Also be aware that you need the plugin for nginx/apache and of the tip at the end in that post:

`MAKE SURE you include root domain and wildcard!!

You will need to make 2 TXT records. Follow the instructions provided by certbot.`

Hth

**Comment by akarelas-pt** [comment]
The link you provided has a mistake, the correct link is [here](https://community.letsencrypt.org/t/ubuntu-16-04-ppa-how-long-until-certbot-0-22-0-available/55613). Thanks.

**Comment by chrisx84** [comment]
WEEK! damn it. i was hoping to allow my users to make websites with their own custom subdomain. i tried the manual install and i seem to keep screwing it up

**Comment by readonly24** [comment]
Any update for this?  In ppa it's still version 0.21.1

**Comment by mnordhoff** [comment]
The PPA currently has 0.26.1, the most recent version of Certbot. This issue should have been closed a few months ago.

https://launchpad.net/~certbot/+archive/ubuntu/certbot

What happens when you try to upgrade? If "`apt-get upgrade"` is stuck on dependency changes, use "`apt-get dist-upgrade`".

What version of Ubuntu are you using? If it's EOL, the PPA will eventually stop carrying new packages.

**Comment by readonly24** [comment]
`apt-get dist-upgrade` was missing. Thanks mnordhoff, now I'm on 0.26.1

**Comment by akarelas-pt** [comment]
I stopped being interested in this issue. I decided to use something else other than wildcards for my problem. So I am not in a position to give you feedback. Thanks.

**Comment by adferrand** [comment]
Then we can clear out the issue. Thanks!
