### ISSUE TITLE
How to pass commands to the certbot docker container

### ISSUE THREAD

**Issue by demamoh** [certbot/certbot#5724]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):

Coreos

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

docker image

## I ran this command and it produced this output:

`docker run -it --name certbot certbot/certbot:latest`

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Certbot doesn't know how to automatically configure the web server on this system. However, it can still get a certificate for you. Please run "certbot certonly" to do so. You'll need to manually configure your web server to use the resulting certificate.
```

## Certbot's behavior differed from what I expected because:

I expected the new container to still be active, but it seems like after running and finishing the command process it shuts down the container. I understand that is how docker works, what I want to know is how to pass commands to the container without having to use `docker run` all the time.  Since it shuts down immediately there isn't enough time to use `docker exec`.

**Comment by bermeitinger-b** [comment]
You add the commands to the run command:
```
docker run -it --rm --name certbot \
-v "/etc/letsencrypt:/etc/letsencrypt" \
-v "/var/lib/letsencrypt:/var/lib/letsencrypt" \
certbot/certbot:rolling \
certonly --manual --preferred-challenges dns-01 --agree-tos -d "example.com" -d "*.example.com" --server https://acme-v02.api.letsencrypt.org/directory
```

**Comment by sydneyli** [comment]
Hi @demamoh! This happens because the entrypoint is `certbot`. You can override the entrypoint (which is `certbot`) with something like `/bin/sh`:
```
docker run --entrypoint="/bin/sh" -it --name certbot certbot/certbot:latest
```

In the future, it might be faster to find help for issues like this on the [community forums](https://community.letsencrypt.org/), since there's a larger audience of people there who are also familiar with the project.

**Comment by bmw** [comment]
@demamoh, what are you trying to do with our Certbot image other than run Certbot?

For reference, our documentation for running Certbot in Docker can be found [here](https://certbot.eff.org/docs/install.html#running-with-docker).

**Comment by demamoh** [comment]
@sydneyli The change in entry point helped to keep the container alive. Thank you @bmw, @bermeitinger-b, and @sydneyli for the help. 

@bmw I'm just trying to use the certbot container, with a linked apache container to create certificates for it.

**Comment by sydneyli** [comment]
Seems to have been resolved, so closing!

**Comment by wizardnet972** [comment]
How about docker-compose.yml file?

```
 certbot:
    image: certbot/certbot:latest
    entrypoint: '/bin/sh'
    command: '/certbot/certbot --help'
```

not work. :(

```
/bin/sh: can't open '/certbot/certbot'
```

**Comment by sydneyli** [comment]
Hi @wizardnet972, thanks for checking out Certbot!
This looks like a different issue. Could you submit a separate issue report [here](https://github.com/certbot/certbot/issues/new) and fill out the issue template there?

**Comment by robindegen** [comment]
Why is there no documentation on how to use this docker container at all on dockerhub? I was honestly surprised that there is literally nothing there at all.

**Comment by renzner** [comment]
Hello @wizardnet972  You can try this one.

` certbot:
    image: certbot/certbot:latest
    entrypoint: '/bin/sh'
    tty: true        # docker run -t`
    
What is does is allocating a pseudo-TTY on the container.
