### ISSUE TITLE
Generate wildcard + root domain certificates with certbot-dns-route53

### ISSUE THREAD

**Issue by JonasNeves** [certbot/certbot#5728]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
CentOS 6.9

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
pip

## I ran this command and it produced this output:
```
certbot certonly \
  --server https://acme-staging-v02.api.letsencrypt.org/directory
  -n --agree-tos --email DEVOPS@COMPANY.COM \
  --dns-route53 \
  -d MY.DOMAIN.NAME,*.MY.DOMAIN.NAME
```

The certificate is created successfully but only including the root domain, and ignoring the wildcard record

## Certbot's behavior differed from what I expected because:

Apparently the DNS challenge is creating the TXT record only for the root domain, ignoring the wildcard record

**Comment by sydneyli** [comment]
Thanks for the report @JonasNeves!
@bmw, this sounds like it's because both `my.domain.name` and `*.my.domain.name` expect different challenges on the same TXT record at `_acme-challenge.my.domain.name`-- is this a known issue?

**Comment by AubreyHewes** [comment]
@JonasNeves 

Based on your given command I would say you need to quote the domain(s) option...

i.e. `-d "example.com, *.example.com"`

You will then the challenged twice, once for the apex and again for the wildcard. Both need to be added to the DNS.

**Comment by AubreyHewes** [comment]
quickfix use multiple `-d` options as per https://github.com/certbot/certbot/blob/31d5d278873cbf34ec6afd0f46796e2154a6461b/certbot-dns-route53/certbot_dns_route53/__init__.py#L107

**Comment by JonasNeves** [comment]
Sorry guys, I was looking at the wrong place to check the domains included in the certificate. 
In the output of `openssl x509 -text -in certificate.pem` I was checking the `Subject:` field instead of `X509v3 Subject Alternative Name` (which is in the bottom of the output). Both root domain and wildcard record are there. I will close this issue. Thank you all for your help.

**Comment by sydneyli** [comment]
Great, glad to hear your issue was fixed!
