### ISSUE TITLE
Certbot account management, renewal and revocation

### ISSUE THREAD

**Issue by agarwalanirudh** [certbot/certbot#5740]
My setup:

A service (which'll be using certbot to generate the certificates) is running on 3 nodes.
**Q.** How do I make sure all three nodes use the same account? (I see there is a key in /etc/letsencrypt/accounts.)

Once the certificate is generated, I move it to S3 bucket and delete it from the node (security reasons) where it was generated.
The way I've thought of doing this is copying the /etc/lentsencrypt/archive/<domain-name>.
**Q.** Is there any harm in doing this? Any suggestions on how to achieve this alternatively?

As mentioned, I'll be deleting the files from all 3 folders (live, archive, renewal).
**Q.** Will certbot be able to figure out the certificates generated from The Account (essentially same account) and renew all certificates which need to be?

**Q.** Similarly, for revocation, the account used will be the same as used for generation. So, will I be able to revoke a certificate by just downloading the cert.pem from S3?

**Comment by sydneyli** [comment]
It looks like these questions were answered, so I'm closing this issue.
