### ISSUE TITLE
certbot hash file

### ISSUE THREAD

**Issue by morgana2313** [certbot/certbot#5742]
I would like to have a URL containing the hash of https://dl.eff.org/certbot-auto for automating installation with Saltstack (file.managed).

**Comment by joohoi** [comment]
Can we make this happen as a part of the release process @bmw ?

**Comment by bmw** [comment]
While I've certainly heard of it, I've never personally used Saltstack. What specifically do you need a hash for? If it's for additional verification, we host a GPG signature at https://dl.eff.org/certbot-auto.acs. Does that work for you?

**Comment by morgana2313** [comment]
Saltstack's [file.managed](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.managed
) supports:  sha512, sha384 , sha256, sha224, sha1 and md5. So GPG signatures at not supported by Saltstack this time. 

For automated installations one might want to use to a certain fixed version of this tool. 

BTW: Google cannot find the GPG certbot-auto signature, you might want to advertise that feature better...

**Comment by joohoi** [comment]
We looked into this and decided against adding a new hash download in addition to the currently provided GPG signature. A hash file obtained from the same host than `certbot-auto` would not be able to provide additional trust over the initial download of the actual script.

Instead we would suggest using the powerful features provided by Saltstack and the ability customize the behavior to download and verify the GPG signature of `certbot-auto`. This will provide an developer identity verification in addition to the file integrity verification. Instructions how to verify the signature on command line are available here: [https://certbot.eff.org/docs/install.html#certbot-auto](https://certbot.eff.org/docs/install.html#certbot-auto)
