### ISSUE TITLE
Feature request: implement a Lexicon-based DNS authenticator for Namecheap

### ISSUE THREAD

**Issue by KevinHughes** [certbot/certbot#5745]
Implement an Authenticator plugin which can fulfill a dns-01 challenge using Lexicon, now that Lexicon added support for Namecheap (January 2018).

**Comment by KevinHughes** [comment]
Would be most grateful for this functionality, whenever it may be implemented... as Namecheap is one of the largest registrars to support dynamic DNS, this would allow their customers to run servers (and smart devices) at home behind typical consumer cable connections with free auto-renewing wildcard certs!

**Comment by schubc** [comment]
I wrote a plugin
https://github.com/schubc/certbot_dns_namecheap
