### ISSUE TITLE
Add DNS authenticator for ClouDNS

### ISSUE THREAD

**Issue by Daniel15** [certbot/certbot#5753]
It would be nice to have support for ClouDNS (https://www.cloudns.net/) if possible.

**Comment by Onepamopa** [comment]
Anything about cloudns? Also, support for dns.he.net would be nice as well.

**Comment by Daniel15** [comment]
For what it's worth, I ended up using [acme-dns](https://github.com/joohoi/acme-dns) rather than using the ClouDNS API. It's safer since it's a totally separate DNS server that you can CNAME to (whereas a ClouDNS API key gives read-write access to all your DNS zones)

**Comment by bmw** [comment]
I don't think a plugin specifically for ClouDNS is something we'll ever get around to writing. If you're curious why, see issues like https://github.com/certbot/certbot/issues/6464 and https://github.com/certbot/certbot/issues/6504.

We may resolve issues like https://github.com/certbot/certbot/issues/6178 which would come with ClouDNS support and people are always welcome to write a third party plugin. With all that said, I'm closing this issue.
