### ISSUE TITLE
<https://certbot.eff.org/docs/install.html> should contain the word "ubuntu"

### ISSUE THREAD

**Issue by seanm** [certbot/certbot#5758]
According to wikipedia, ubuntu is "the most popular server Linux distribution".  It's odd then that the page at <https://certbot.eff.org/docs/install.html> doesn't contain the word "ubuntu" at all.

Worse, following the debian instructions:

```
sudo apt-get install certbot
```

results in "Unable to locate package certbot" with the current ubuntu LTS (16.04).

Seems like a big documentation fail to me. :(

**Comment by schoen** [comment]
Hi @seanm ,

The first two sections of that page say

> Certbot is packaged for many common operating systems and web servers. Check whether certbot (or letsencrypt) is packaged for your web server’s OS by visiting certbot.eff.org, where you will also find the correct installation instructions for your system.
> ! **Note**
> Unless you have very specific requirements, we kindly suggest that you use the Certbot packages provided by your package manager (see certbot.eff.org). If such packages are not available, we recommend using certbot-auto, which automates the process of installing Certbot on your system.

If you follow the link to https://certbot.eff.org/, there are menus to let you select your OS and get appropriate installation instructions, including using the 16.04 LTS.

Can you think of a way that we could make it clearer that the instructions for installing from a package manager are obtained only by following the https://certbot.eff.org/ link and are not contained elsewhere in the text of https://certbot.eff.org/docs/install.html?

**Comment by seanm** [comment]
I'd suggest either: 1) add Ubuntu to the "Operating System Packages" section or 2) remove the "Operating System Packages" section.

**Comment by pde** [comment]
@seanm want to [send us a pull request](https://github.com/certbot/certbot/edit/master/docs/install.rst)?

**Comment by seanm** [comment]
Sorry, no; there just aren't enough hours in the day to contribute to every project under the sun. :(
