### ISSUE TITLE
Set up test-everything tests for point release branches

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5760]
Not sure the best way to do this, but during the release process we should automate setting up tests like we have in the `test-everything` branch that tests the latest point release branch (e.g. `0.22.x`). This ensures that branch always works and automates testing of backported fixes.

**Comment by bmw** [comment]
Related to #4080.

**Comment by adferrand** [comment]
With recent improvements done to `.travis.yml`, that contains now all tests:
- non master branches are already fully tested (so including `0.22.x`-like branches)
- executing a complete test during the PR to merge the point release candidate to the point release branch could be done by extending conditions of the anchor `extended-test-suite` in `.travis.yml` to include also PR to point release branches.

What do you think of that @bmw ?

**Comment by bmw** [comment]
Somehow I missed my mention here and came across this issue separately... If there are other issues you've pinged me on that I missed, please let me know.

About this actual issue though, I'm personally satisfied with the state of things now. Any changes landing on a point release branch automatically triggers running the full test suite which our release instructions tell you to verify they passed before performing the release. We previously had to trigger these tests manually so I think that gets the main thing I wanted here.

There would be some value in running the full test suite on PRs to point release branches too, however, I'd personally skip doing this as I think in most cases by the time we're backporting fixes from `master`, tests should pass on the point release branch. Not only that, we should still wait for the full tests to run on the actual commit to the point release branch after a PR is merged, so I think in most cases running the full test suite on PRs unnecessarily slows down the release process.

It's certainly possible that the full test suite would fail so maybe causing the failures on PRs before it is merged would speed up the release process in those cases, however, I think that's pretty rare so I'd personally rather stick with our current setup for now.
