### ISSUE TITLE
Add dns authenticator for Linode

### ISSUE THREAD

**Issue by leonardder** [certbot/certbot#5771]
## I installed Certbot with OS package manager

Currently, there are several DNS authenticators available. One example is the Digital Ocean dns authenticator that supports authentication using the Digital Ocean API. Linode is another VPS host that also has an [API that support DNS record manipulation](https://www.linode.com/api/dns).

An authenticator for Linode would be greatly appreciated!

**Comment by sydneyli** [comment]
Thanks! A PR is open for this here: #5302. We can use this issue to track it.

**Comment by leonardder** [comment]
Closing as #5302 is now merged.
