### ISSUE TITLE
Clearly document what APIs we consider public

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5775]
For `acme` (and `josepy`), I'd say everything is public (besides objects prefixed with an underscore).

For the plugins, I'd say nothing is public besides the plugin API they implement.

For `certbot`, this is less clear. Everything in `achallenges.py`, `errors.py`, and `interfaces.py` should probably be considered public. Additionally, maybe some combination of `certbot/plugins/common.py`, `certbot/crypto_util.py`, and `certbot/util.py`?

We should clearly document this for people wanting to hack on/around the probject.

**Comment by adferrand** [comment]
Following discussions in #6841, I would like to note the inconsistency of test modules from `certbot.plugins`. They are unit tests for certbot CI process, and so are for internal use and should not be used. But they are also part of the public API, and so likely to be used by third party plugins for what `certbot.plugins` as been designed for.

In theory, and following the design for the other tests, tests modules should be a part of a `*.tests` package that by convention is private and must not be imported in any way.

Solving the inconsistency could be to have a public API for plugin testing, exposing "abstract" modules, that would be in `certbot.plugins` or a submodule. Then for internal use certbot would subclass them in a `certbot.tests.plugins` to be effectively used by the certbot CI.

**Comment by bmw** [comment]
I wrote up a proposal for how to resolve this at https://docs.google.com/document/d/1ozJvEDq2qTtKMeicCUyxH6BZ80_7XZSQDMHMo8uA1WA/edit?usp=sharing.

**Comment by bmw** [comment]
I think the only pieces left here not tracked by other issues are:

- [ ] Update the submodule on the website repo and fix any paths to the docs. See the 2nd paragraph in https://github.com/certbot/certbot/pull/7544#issuecomment-557727307.
- [ ] Fix import orders. (Maybe check out [isort](https://isort.readthedocs.io/en/stable/)?)

**Comment by bmw** [comment]
@adferrand is planning on fixing up import orders.

**Comment by bmw** [comment]
@ohemorange, is fixing up the website repo still on your radar? I didn't expect this to happen, but website builds are going to fail until this resolved because links back to the source files are broken since the docs directory moved.

**Comment by ohemorange** [comment]
> @ohemorange, is fixing up the website repo still on your radar? I didn't expect this to happen, but website builds are going to fail until this resolved because links back to the source files are broken since the docs directory moved.

Thanks for the reminder, I'll do this today

**Comment by bmw** [comment]
This is done!
