### ISSUE TITLE
Optional TSIG key for certbot-dns-rfc2136

### ISSUE THREAD

**Issue by arunisaac** [certbot/certbot#5778]
My DNS server authenticates RFC2136 DNS update requests based on the IP address of the requester. So, I don't have a TSIG key, secret and algorithm. It would be nice if certbot-dns-rfc2136 could treat them as optional.

## My operating system is (include version):
Parabola GNU/Linux (rolling release)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
cerbot 0.22.2 installed with OS package manager (pacman)

## I ran this command and it produced this output:
I ran the following command.
`certbot certonly --dns-rfc2136 --dns-rfc2136-credentials /path/to/credentials.ini --cert-name example.com -d "*.example.com" -d example.com --server https://acme-v02.api.letsencrypt.org/directory`

My credentials file has the following.
`dns_rfc2136_server=ip.address.of.server`

I got the following output.
```
Missing properties in credentials configuration file /root/scripts/rfc2136-credentials.ini:
 * Property "dns_rfc2136_name" not found (should be TSIG key name).
 * Property "dns_rfc2136_secret" not found (should be TSIG key secret).
```

## Certbot's behavior differed from what I expected because:
certbot errors out because I didn't provide TSIG information. I expected TSIG to be optional.

**Comment by sydneyli** [comment]
Thanks for reporting! I don't have much context on the DNS plugins, but how are you authenticating your DNS updates without signing them?

@joohoi , care to weigh in on this?

**Comment by arunisaac** [comment]
> how are you authenticating your DNS updates without signing them?

I run my own DNS server on a VPS. My web server and my DNS server are on a Wireguard VPN, both having static IPs. All packets on this VPN are signed. So, if a RFC2136 request comes from my web server's IP, the DNS server knows that it is legitimate. I use PowerDNS for my DNS server. PowerDNS lets me authenticate RFC2136 requests based on IP.
