### ISSUE TITLE
Certbot should respect Retry-After when polling authzs

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5789]

**Comment by adferrand** [comment]
Already implemented. Relevant method is the classmethod `retry_after` in `client.py` lines 171-201, and used during `poll_and_request_issuance` lines 458-459.

**Comment by bmw** [comment]
Nice! I don't think I realized that code was there.

I think the next problem is that `certbot/auth_handler.py` doesn't use this code though. I think we should refactor it to do so if we can without removing any of the other functionality in the file.

**Comment by bmw** [comment]
Actually, it also looks like that method is only used in the `Client` object for ACMEv1 and isn't used in ACMEv2.

**Comment by adferrand** [comment]
Allright. No breaking change in acme, and I will try to figure out how to leverage the poll retry of acme v2 protocol directly in acme module, while preserving the capability to handle each challenge independently.

**Comment by bmw** [comment]
Thanks Adrien!

> while preserving the capability to handle each challenge independently.

To be clear, last time I was doing significant work in that file I was under the impression that this feature didn't actually work like it's supposed to. I was rushing to get the code I was working on out and didn't take the time to verify, but that's what I thought at the time.

If this is the case, we could probably simplify the code significantly and just remove the feature entirely for now. We're not using it and if it doesn't work and its not a recent regression, neither are our 3rd party plugins.
