### ISSUE TITLE
Expanding cert not working

### ISSUE THREAD

**Issue by ungentilgarcon** [certbot/certbot#5792]
Ok, on stretch, using an expand in order to add base domain to a wilcard cert containing only subdomains didn't work, had to duplicate it.

Cheers

**Comment by schoen** [comment]
Hi @ungentilgarcon ,

Thanks for the bug report.

What command did you run? What version of Certbot are you running? What message did you see?

(It's very possible that this logic is broken in this way.)

**Comment by sydneyli** [comment]
Since it's been over a year, closing this issue. @ungentilgarcon if you're still having trouble you can also ask this question on the [Let's Encrypt Community Forums](https://community.letsencrypt.org/c/help), where there's a larger audience of people familiar with the project.
