### ISSUE TITLE
Cannot run Dry-Run with v2 server command

### ISSUE THREAD

**Issue by sirshurf** [certbot/certbot#5797]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 14.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Apt-GEt

## I ran this command and it produced this output:
> certbot certonly --nginx --dry-run --server https://acme-v02.api.letsencrypt.org/directory

and I got this reply
--server value conflicts with --dry-run

## Certbot's behavior differed from what I expected because:
Should have runned dry-run

**Comment by ohemorange** [comment]
This bug is fixed in the latest version of Certbot, so I'm closing this issue. Make sure you're running the latest version.
