### ISSUE TITLE
Certbot abnormal termination

### ISSUE THREAD

**Issue by sirshurf** [certbot/certbot#5798]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
ubuntu 14.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Apt-get

## I ran this command and it produced this output:
certbot -v
Root logging level set at 10
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Requested authenticator None and installer None
Single candidate plugin: * nginx
Description: Nginx Web Server plugin - Alpha
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: nginx = certbot_nginx.configurator:NginxConfigurator
Initialized: <certbot_nginx.configurator.NginxConfigurator object at 0x7fb931b7f8d0>
Prep: True
Selected authenticator <certbot_nginx.configurator.NginxConfigurator object at 0x7fb931b7f8d0> and installer <certbot_nginx.configurator.NginxConfigurator object at 0x7fb931b7f8d0>
Plugins selected: Authenticator nginx, Installer nginx
Enter email address (used for urgent renewal and security notices) (Enter 'c' to
cancel): c
Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.22.2', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1266, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1023, in run
    le_client = _init_le_client(config, authenticator, installer)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 635, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 496, in _determine_account
    config.email = display_ops.get_email()
  File "/usr/lib/python3/dist-packages/certbot/display/ops.py", line 59, in get_email
    "An e-mail address or "
certbot.errors.Error: An e-mail address or --register-unsafely-without-email must be provided.
An e-mail address or --register-unsafely-without-email must be provided.

**Comment by ohemorange** [comment]
Hi @sirshurf.

As the error message explains, an e-mail address or `--register-unsafely-without-email` must be provided.

Since this isn't a bug, if you'd like further support on this topic, please try asking for help at https://community.letsencrypt.org/. There is a much larger community there of people familiar with the project who will be able to more quickly answer your questions.
