### ISSUE TITLE
proposal - additional environment vars populated for manual plugin

### ISSUE THREAD

**Issue by jvanasco** [certbot/certbot#5805]
I've been trying to figure out how/why multiple cloud DNS systems have been failing on certificates that  contain both a wildcard and root domain. Originally I thought the verification of a first domain was caching a record, which blocked the second domain for a TTL (see #5801). Now I think the issue may be a push of the first record at the DNS provider is being cached, and blocking the second record from being read. 

To help code around this, I'd like to propose 2 adjustments to the manual plugin:

1. (simple) Augment the environment variables populated in `plugins/manual.py:Authenticator._perform_achall_with_script` with 
* `CERTBOT_BATCH_LEN` which track how many items will be called by the auth process
* `CERTBOT_BATCH_IDX` which is the current index.  This would be accomplished with about 5 clean and short lines of code.  Here's an example (I wasn't sure how to extend tests for environment vars, they might not exist?) https://github.com/jvanasco/certbot/commit/8f005bc7c678f1bdcacad64825aab772efd73708
* hook scripts would then be able to detect progress, including being on the last item, by operations like `"$(($CERTBOT_BATCH_LEN <= ($CERTBOT_BATCH_IDX + 1)))"`

2. (complex) Adding versions of the above that are locked to the second-level domain. e.g. `CERTBOT_2LD_BATCH_LEN` and `CERTBOT_2LD_BATCH_IDX`.  This isn't hard to do, but will add a chunk of code that pre-analyzes the achalls.

With that information provided to the existing manual-auth-hooks, scripts can better determine when they need to 'sleep' or execute a request to flush dns (if possible).  The first option would allow for scripts to easily detect they are the last overall invocation of the hook; the second option would note that a particular domain is finished.

**Comment by bmw** [comment]
I'm pretty hesitant to add complexity like this to our manual hooks. Hooks for the manual plugin are a nice way to automate simple tasks and that don't necessitate [writing your own plugin](https://certbot.eff.org/docs/contributing.html#writing-your-own-plugin), but as your needs get more specific and complex, I think that writing a simple authenticator plugin is a better option. Doing so only requires implementing a few functions in Python.

As a potentially even easier alternative, why not just have your hooks always include the longer sleep? It's not as efficient, but especially when it'll usually be run non-interactively by something like cron, does the longer wait time really matter in your use case?

**Comment by jvanasco** [comment]
First, thanks for your time and feedback.

I suggested using environment variables to track batch status, because it is much less complex/cleaner/more-useful than adding a hook that indicates certbot is "ready to verify" - which is the target functionality for this request.  I only need to wait (or try a DNS flush, if possible) at that point.  For 3/3 providers I could test (and likely more) knowing that is required due to how unpredictable their "enterprise" dns systems cache the duplicate TXT records.  

Thanks to boulder, one can CNAME all the `_acme-challenges` onto their best performing DNS provider. The fastest time I can 'sleep' across the multiple cloud providers I have access to and generate a root+wild certificate is 120s (off a 60s TTL, all the rest need 5m 10m or 15m). That doesn't sound bad... but with 43 domains managed (and growing) there are 86 validations (1 root, 1 wild), which translates to 172 minutes of waiting -- almost 3 hours.

Few providers have locked-down/limited ACL credentials for DNS services (i.e. only TXT records) so it is often incredibly dangerous to store (broad) DNS API credentials online for automatic renewal - a compromised server could lead to all A/MX records being changed or the domain being transferred with the registrar. The only secure way to perform DNS validation without installing additional software with many DNS services is to run certbot on a local machine where someone can decrypt the API credentials to run the script as needed. Because of the inherent security concerns with the DNS auth mechanism, our DNS renewal can't be automatic - it needs human intervention.  (sidenote: This applies to most people's DNS renewals; The scope of API credentials from most providers are outright terrifying.)

The best solution to deal with DNS auth is getting an `acme-dns` server set up and have that as the ultimate CNAME target. That's not an option for us right now, but will be in the future.  We use an in-house certificate manager which does HTTP auth and dynamically provisions certificates into an OpenResty cluster; certbot is just being used for the wildcards until the DNS auth gets built out. Until then, the easiest way for me to address this is just patching this functionality into certbot as needed.

BUT I'm fairly sure this is going to become an increasing problem for all users as wildcards get more popular.  The cloud dns systems are just completely wonky.  Doing dozens of tries against acme-staging, sometimes there would be a 1m cache, other times there would be a 2m cache; a few times things just worked the first time.  I'm pretty sure dns caching within the provider's network is the issue for a lot of random problems that people have been experiencing on the LetsEncrypt forum.

**Comment by bmw** [comment]
Thanks for the detailed writeup.

Something like the first suggestion you proposed is a common one (see https://github.com/certbot/certbot/issues/5484 or #6607) and I think we'll do something like that in the future. As I recently stated at https://github.com/certbot/certbot/issues/5484#issuecomment-484635238 though, we're currently rethinking how things like plugins and hooks work in Certbot, but if there aren't major changes to these systems which would accommodate these uses cases, I think we'll make a change like this.

If you have a use case for `CERTBOT_BATCH_IDX` over `CERTBOT_LAST_DOMAIN` as proposed in #5484, I'd love to hear about it.

I'm not sure I entirely understand your second suggestion though. Can you tell me more?

**Comment by jvanasco** [comment]
> If you have a use case for CERTBOT_BATCH_IDX over CERTBOT_LAST_DOMAIN as proposed in #5484, I'd love to hear about it.

It's been a while as I'm mostly using acme-dns or my own client now.... but reading the above and looking at my old code I think the reason for not setting `CERTBOT_LAST_DOMAIN` was 

* a cleaner change to the codebase, as the last domain status isn't figured out in Python
* some extra flexibility, as the invoked script would know where it was in the overall queue.

In terms of the second idea `CERTBOT_2LD_BATCH_LEN` and `CERTBOT_2LD_BATCH_IDX`...

Let's say my certificate request includes the following domains:

   * example.com
   * foo.example.com
   * letsencrypt.org
   * foo.letsencrypt.org
   * bar.letsencrypt.org

Two 2LD domains (`example.com`, `letsencrypt.org`) might have different DNS providers, each with a different caching timeout or the ability to request a dns flush (which are typically throttled, if available at all).

If my script knows that I am completing the final challenge for the `example.com` domain, I might perform an action on the DNS provider based on a policy that is specific to the 2LD domain.  For example: I might hardcode a 2 minute sleep for `example.com`, but perform a DNS flush against `letsencrypt.org` which has a 20 minute DNS cache.

If the script simply knows it is being invoked with the last domain in the certificate overall, the action I perform to sleep/flush/etc will be based on the aggregate/commonalities of all domains I might expect.  I would likely author the script to sleep for 21 minutes, because the certificate request *might* have a `letsencrypt.org` domain on it, and I couldn't waste one of my 2 possible DNS flushes in a 24 hour period on a potential.

**Comment by bmw** [comment]
Got it. Thanks for the extra info.

Whether we end up redesigning the plugins/hook systems or not, we'll try and keep these issues in mind and fix them one way or another.
