### ISSUE TITLE
The server experienced an internal error :: Error creating new cert

### ISSUE THREAD

**Issue by VBarzionov** [certbot/certbot#5807]
## My operating system is (include version):
Debian 9.4

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt-get install python-certbot-apache -t stretch-backports
certbot 0.21.1

## I ran this command and it produced this output:
#certbot certonly --webroot -w /www/production/public  -d jobs.staya.vc -d testing.staya.vc -d virink.staya.vc -d cgmag.staya.vc -d climbproffi.staya.vc -d weblair.staya.vc -d sellyourhead.staya.vc -d zvk123456.staya.vc -d animationclub.staya.vc -d jobs.animationclub.ru -d dobrayarabotafb.staya.vc -d realtime.staya.vc -d jobs.realtime.ru -d mopicture.staya.vc -d mcg.staya.vc -d gibrotuts.staya.vc -d specialist.staya.vc -d techrocks.staya.vc -d jobs.techrocks.ru -d cerebro.staya.vc -d jobs.cerebrohq.com -d onlinevfx.staya.vc -d jobs.online-vfx.ru -d polygon.staya.vc -d jobs.polygon.by -d 3dvis.staya.vc -d jobfeed.staya.vc -d marhr.staya.vc -d cgallies.staya.vc -d c0ding.staya.vc -d proficinema.staya.vc -d 3dyuriki.staya.vc

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for jobs.staya.vc
http-01 challenge for testing.staya.vc
http-01 challenge for virink.staya.vc
http-01 challenge for cgmag.staya.vc
http-01 challenge for climbproffi.staya.vc
http-01 challenge for weblair.staya.vc
http-01 challenge for sellyourhead.staya.vc
http-01 challenge for zvk123456.staya.vc
http-01 challenge for animationclub.staya.vc
http-01 challenge for jobs.animationclub.ru
http-01 challenge for dobrayarabotafb.staya.vc
http-01 challenge for realtime.staya.vc
http-01 challenge for jobs.realtime.ru
http-01 challenge for mopicture.staya.vc
http-01 challenge for mcg.staya.vc
http-01 challenge for gibrotuts.staya.vc
http-01 challenge for specialist.staya.vc
http-01 challenge for techrocks.staya.vc
http-01 challenge for jobs.techrocks.ru
http-01 challenge for cerebro.staya.vc
http-01 challenge for jobs.cerebrohq.com
http-01 challenge for onlinevfx.staya.vc
http-01 challenge for jobs.online-vfx.ru
http-01 challenge for polygon.staya.vc
http-01 challenge for jobs.polygon.by
http-01 challenge for 3dvis.staya.vc
http-01 challenge for jobfeed.staya.vc
http-01 challenge for marhr.staya.vc
http-01 challenge for cgallies.staya.vc
http-01 challenge for c0ding.staya.vc
http-01 challenge for proficinema.staya.vc
http-01 challenge for 3dyuriki.staya.vc
Using the webroot path /www/production/public for all unmatched domains.
Waiting for verification...
Cleaning up challenges
An unexpected error occurred:
The server experienced an internal error :: Error creating new cert
Please see the logfiles in /var/log/letsencrypt for more details.

## Certbot's behavior differed from what I expected because:
If it is not a bug, I would to know the reason why obtaining certs is not possible.

The Internal Error is somehow related with number of domains requested. If I request cert for 17 domains, the cert is obtained. As I see, according to Let's encrypt Limits there is 100 domains allowed per one cert.

All those domains located on same apache-web server.
All DNS-records for domains point on its IP. 
There is also several CNAME's e.g. jobs.cerebrohq.com -> cerebrohq.staya.vc

Apache confs look like:

<VirtualHost *:80>
ServerName jobs.staya.vc
ServerAlias testing.staya.vc virink.staya.vc cgmag.staya.vc climbproffi.staya.vc ......
......
<IfModule mod_ssl.c>
<VirtualHost *:443>
ServerName jobs.staya.vc
ServerAlias testing.staya.vc virink.staya.vc cgmag.staya.vc climbproffi.staya.vc ......
......

## Here is a Certbot log showing the issue (if available):
[letsencrypt.log](https://github.com/certbot/certbot/files/1860948/letsencrypt.log)

**Comment by bmw** [comment]
@cpu, any ideas on the cause of the `serverInternal` error here?

**Comment by bmw** [comment]
@VBarzionov, this error is coming from Let's Encrypt's server rather than Certbot. If you're repeatedly getting this issue and it wasn't a one time hiccup, please open an issue at https://github.com/letsencrypt/boulder.
