### ISSUE TITLE
Reuse ACMEv1 accounts for ACMEv2

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5820]
Boulder implemented this and making use of it is a better experience for our users and their servers.

**Comment by bmw** [comment]
The current assumption is accounts are not shared between servers at different URLs which seems like a safe and usually correct assumption, however, boulder implemented the ability to share accounts between ACME versions. (This is the case in production and probably the case in staging too but we should double check the latter.) I think we should continue to make the assumption accounts aren't shared in general and add a special case for Let's Encrypt. Normally I'm against hard coding Let's Encrypt's policies like this and having an ancient version of Certbot come back to bite us later, but this isn't likely to change and allowing the account to be shared is a significant benefit for us, Let's Encrypt, and our users.

The relevant class is `certbot.account.AccountFileStorage`, specifically it's usage of `config.accounts_dir`, and especially the `find_all` method. The way I'd do this is to make a data structure containing the server URLs across which accounts can be shared in `accounts.py`, `constants.py`, or `configuration.py`. When `find_all` is called, it can use these to check the account directories for the other endpoints to see what other accounts exist.

I think the big question here is whether we always check these other directories or only if an account doesn't exist in the account directory specifically for that endpoint. The reason for considering the latter is to avoid adding new prompts to Certbot.

If you look at `certbot.main._determine_account.py`, we will prompt if there is more than one matching account. Since people have been changing the server URL to use ACMEv2 and we switched ACMEv2 to the default staging URL, I think this will cause problems. For instance, I think it's fairly common that a user has an ACMEv1 prod account and a staging account for both endpoints. If we make the change to have `find_all` always return both accounts, if you run `certbot renew --dry-run` I'd expect Certbot to crash saying it needs you to choose an account but can't do so because `renew` implies non-interactive :/ Similar problems would happen for people who have already started using ACMEv2 in prod, have a ACMEv1 account, and are using the `--non-interactive` flag.

The other piece of this that I haven't fully thought through is if we use an account from a directory other than the one matching the server URL being used, how do we find that account during renewal? Unfortunately, I think we have to break forwards compatibility here as I don't see a way to make this work with an older version of Certbot. If we're OK with that, the two options I thought of are to add the account directory used to the runtime config and save it in the renewal conf file or to reuse the logic from `find_all` to search other account directories in `certbot.account.AccountFileStorage.load`. The latter seems much easier and less error prone to me.

If you're still with me, let me know if you have any questions about all this. Happy to answer them, talk design, or try to take this issue entirely if prefer.

**Comment by bmw** [comment]
To keep forward compatibility, we may be able to create symlinks. For example, when reusing an ACMEv1 account for ACMEv2, create the ACMEv2 account directory if it doesn't exist, and create a symlink from the directory for the ACMEv1 account you're using to the ACMEv2 directory.

No idea if this actually works but maybe something to look into. To create this symlink, we'd either have to always make these symlinks for any accounts returned from `find_all` that are from a different directory or we'd have to have other code that takes the account the user picked and creates the symlink.

**Comment by ohemorange** [comment]
I have a different idea:

we create an ordered list of related server urls (per special-cased server, such as prod and staging) that aren't interchangeable but instead are preferential

and you look up the correct one in the list and then try ones chronologically earlier than it

so if there's an acmev2 account hanging around, use that if you're an acmev2 url
and if you're an acmev2 url but there's no acmev2 account, just use the acmev1 account

but it's one way -- if you're acmev1, you can't try looking for an acmev2 account

and if acmev3 comes out, try looking for acmev2 then acmev1 

this solves the interactivity problem

for the forward compatibility problem, same symlink fix? if you have to make an acmev2 account and there's no acmev1 account hanging around, also make a symlink from all the earlier-downs to the acmev2 account.

**Comment by ohemorange** [comment]
I think it's rare that someone will actually want to see both their old and new accounts. it's rare that people have multiple accounts in the first place, and the more common case is that someone just made a new account for the new server, and don't actually care which account they use. and if they have to use an old account, they can specify `--server`
