### ISSUE TITLE
Offer interactive selection for --cert-name for install verb

### ISSUE THREAD

**Issue by joohoi** [certbot/certbot#5824]
If `--cert-name` or key and cert paths were not defined on the command line, Certbot should offer interactive selection of certificate, as implemented in enhance verb PR #5596

**Comment by sbraden** [comment]
I'm going to work on this one.

**Comment by bmw** [comment]
Looks like tests for `install` start at https://github.com/certbot/certbot/blob/802fcc99ee2150989e5a1e860b6aad490691d72f/certbot/tests/main_test.py#L699 and there's a few consecutive ones. They probably should be written in a more easily findable way and not in one giant test class.

Trying to base a test for this off of these tests and some of the enhance tests which you mentioned in https://github.com/certbot/certbot/pull/5596/files#diff-8d7d4822efd312492f20da699e3b062a is a good idea I think.

**Comment by bmw** [comment]
@sbraden, are you still planning on working on this or should one of us take over? If the latter, do you have a start on this somewhere we can build off of?
