### ISSUE TITLE
Option to update renewal configuration

### ISSUE THREAD

**Issue by jmorahan** [certbot/certbot#5828]
As discussed at https://community.letsencrypt.org/t/how-to-regenerate-renewal-config-file/58628

It might be useful to have a method to safely update the renewal configuration for an existing certificate without actually renewing the certificate.

Something like this maybe?

`certbot certonly --reconfigure-only --cert-name example.com --apache -d example.com`

So basically the existing interface for updating the config for an existing certificate, but with an additional option to not actually issue a cert immediately. Instead it could attempt a test issuance against the staging endpoint to verify that the updated settings would succeed in renewing the certificate, then write the updated options (but with account details for the live endpoint) to the existing renewal configuration file.

**Comment by mconigliaro** [comment]
OP from the forum here. I ran into this while setting up a post hook. The initial post hook I set up while running `certbot certonly` was wrong, and after fixing it in my configuration management code, I realized that the old command was still cached in all the renewal config files. Since certbot doesn't seem to provide a way to rewrite this file, I had to go around and fix it manually on every affected instance. My concern is that this is essentially a time bomb. In my case, the wrong command might have run during the renewal, and I wouldn't have known there was a problem until my monitoring system and/or angry users complained about the expired cert still cached in my application.

**Comment by linas** [comment]
Time-bomb is starting to go off? Got email requesting switch to ACMEv02 and it took me two hours to figure out that `acme-v01` is hard-coded in `/etc/letsencrypt/renewal/` ... I guess I will have to hand-edit to fix, despite warnings not to hand-edit?

**Comment by bmw** [comment]
@linas, this question is a bit off-topic for this issue. If you need help making changes to your Certbot configuration, I recommend posting to https://community.letsencrypt.org where there is a large group of people who would be happy to help you.

**Comment by linas** [comment]
Sorry, that was meant as a rhetorical question. I know what to do; a very twisty path of trying to figure out how to perform that update naturally leads one to this issue.  I also get the impression that maybe I was a very early adopter, and had a very unusual configuration that others don't have.

**Comment by orcas-apisch** [comment]
Came across this today and managed as follows:
certbot certonly --expand --webroot -w <webroot> -d <domain>
This created ~/<domain>-001 folders, so I had to proceed:
1. mv /etc/letsencrypt/archive/<domain>-001 /etc/letsencrypt/archive/<domain>
mv /etc/letsencrypt/live/<domain>-001 /etc/letsencrypt/archive/<domain>
2. change symlinks inside /etc/letsencrypt/archive/<domain> to point to the new certifactes
3. Edit /etc/letsencrypt/reneweal/<domain>-001.conf to change all paths back to ~/<domain>:
/etc/letsencrypt/archive/<domain>
/etc/letsencrypt/live/<domain>
4. mv <domain>-001.conf <domain>.conf
In fact it would have been easier to just remove old config and folders and create a new cert. So paths for applications remain intact.

**Comment by AvverbioPronome** [comment]
Same issue coming up again: https://community.letsencrypt.org/t/making-certbot-edit-its-own-config-files/118310?u=9peppe

**Comment by tomwassenberg** [comment]
This might also have some overlap with #5249. The use case there is slightly different however, since renewing _is_ desired in that scenario.

**Comment by eaglet3d** [comment]
If this ticket was implemented, would it solve the need to give the user an migration path from a certbot-auto renewal configuration file to a certbot renewal configuration file?

**Comment by bmw** [comment]
This was done in https://github.com/certbot/certbot/pull/9355.
