### ISSUE TITLE
certbot-auto crashes with "Bus error" on older machine

### ISSUE THREAD

**Issue by jherazob** [certbot/certbot#5845]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):

Debian  7 (wheezy)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

certbot-auto

## I ran this command and it produced this output:

Executed `/usr/local/bin/certbot-auto renew -v`

Received:

     Root logging level set at 10
     Saving debug log to /var/log/letsencrypt/letsencrypt.log

     -------------------------------------------------------------------------------
     Processing /etc/letsencrypt/renewal/<DOMAIN-WITHHELD>.conf
     -------------------------------------------------------------------------------
     Requested authenticator <certbot.cli._Default object at 0x23a0090> and installer <certbot.cli._Default object at 0x23a0090>
     Should renew, less than 30 days before certificate expiry 2018-04-30 19:54:44 UTC.
     Cert is due for renewal, auto-renewing...
     Requested authenticator apache and installer apache
     Apache version is 2.2.22
     /usr/local/bin/certbot-auto: line 1670: 21920 Bus error               "$VENV_BIN/letsencrypt" "$@"`

The number right before "Bus error" seems to change on every execution, and line 1670 is the last line of certbot-auto.

## Certbot's behavior differed from what I expected because:

It crashed before upgrading the certificate

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

Log stops before the error happens:

     2018-04-11 13:27:00,377:DEBUG:certbot.main:certbot version: 0.23.0
     2018-04-11 13:27:00,377:DEBUG:certbot.main:Arguments: ['-v']
     2018-04-11 13:27:00,377:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
     2018-04-11 13:27:00,394:DEBUG:certbot.log:Root logging level set at 10
     2018-04-11 13:27:00,394:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
     2018-04-11 13:27:00,424:DEBUG:certbot.plugins.selection:Requested authenticator <certbot.cli._Default object at 0x23a0090> and installer <certbot.cli._Default object at 0x23a0090>
     2018-04-11 13:27:00,431:DEBUG:certbot.storage:Should renew, less than 30 days before certificate expiry 2018-04-30 19:54:44 UTC.
     2018-04-11 13:27:00,431:INFO:certbot.renewal:Cert is due for renewal, auto-renewing...
     2018-04-11 13:27:00,454:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
     2018-04-11 13:27:00,989:DEBUG:certbot_apache.configurator:Apache version is 2.2.22

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

Doesn't seem to even get to do anything with it

All system packages are upgraded with dist-upgrade, and this used to work in the past as the certificate was created quite a while ago.

I'll provide any information you need to help debug and fix the issue.

**Comment by sydneyli** [comment]
@jherazob That's an odd bug! Does this also happen when you renew with `--dry-run`?

**Comment by jherazob** [comment]
Yep, but -h works, it's strange

**Comment by sydneyli** [comment]
@jherazob Do other commands also fail, or is it only renew?

**Comment by jherazob** [comment]
Since this is a production server i don't want to run any commands that will break the two ones that are still valid and being used, but "certificates" works just fine:

     # /usr/local/bin/certbot-auto certificates
     Saving debug log to /var/log/letsencrypt/letsencrypt.log

     -------------------------------------------------------------------------------
     Found the following certs:
       Certificate Name: <DOMAIN WITHHELD>
         Domains: <TWO DOMAINS WITHHELD>
         Expiry Date: 2018-04-30 19:54:44+00:00 (VALID: 18 days)
         Certificate Path: /etc/letsencrypt/live/<DOMAIN WITHHELD>/fullchain.pem
         Private Key Path: /etc/letsencrypt/live/<DOMAIN WITHHELD>/privkey.pem
     -------------------------------------------------------------------------------

Any idea what nondestructive testing could be done? Or will it be enough to back up the config files? Won't the certificates be invalidated if we do things with them even if we preserve the config files?

**Comment by sydneyli** [comment]
Sorry for my lateness in getting back to you.
From your logs, my initial guess is that `apache` failed to start-- Googling "apache bus error" seems to indicate that this might be the case. Can you post logs from apache?
Looping in @joohoi since he has more experience with apache things.

**Comment by jherazob** [comment]
OK, decided to take Apache out of the picture using standalone, same thing:
```
# service apache2 stop ; /usr/local/bin/certbot-auto renew --standalone --dry-run -v ; service apache2 start
[ ok ] Stopping web server: apache2 ... waiting .
Root logging level set at 10
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/<DOMAIN WITHHELD>.conf
-------------------------------------------------------------------------------
Requested authenticator standalone and installer <certbot.cli._Default object at 0x229d150>
Var dry_run=True (set by user).
Var server=set(['staging', 'dry_run']) (set by user).
Var account=set(['server']) (set by user).
Var authenticator=standalone (set by user).
Should renew, less than 30 days before certificate expiry 2018-04-30 19:54:44 UTC.
Cert is due for renewal, auto-renewing...
Requested authenticator standalone and installer apache
Apache version is 2.2.22
/usr/local/bin/certbot-auto: line 1670: 31050 Bus error               "$VENV_BIN/letsencrypt" "$@"
[ ok ] Starting web server: apache2.
```
With this, the Apache error log only shows the shutdown and start, as Apache was not running at all in the meanwhile.

Honestly, i wouldn't be surprised at all if it was something dumb like permissions or something like that, little things you don't consider could make a difference. Only with this i don't know how to check this out.

**Comment by adferrand** [comment]
Since there is not update on this issue, and may have been fixed by all improvement done to `certbot-auto`, I close this issue. Do not hesitate to ask to reopen if the issue still occurs.
