### ISSUE TITLE
Certbot crashes if EFF e-mail submission endpoint is unavailable

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#5858]
Certbot will crash if the user's e-mail information can't be submitted to the EFF endpoint:

https://community.letsencrypt.org/t/issue-when-trying-to-create-certificate/59307/1

https://github.com/certbot/certbot/blob/master/certbot/eff.py#L74

It crashes with a somewhat relevant error if the endpoint is unavailable, but a confusing error if the endpoint returns something other than JSON. It should probably not crash at all in either case. If the endpoint specifically says that the user's e-mail address is malformed, that's probably worth stopping to report to the user, but if the endpoint simply doesn't reply usefully, it's probably preferable to continue since I wouldn't think we really want to make users wait in this situation.

(Adding the "bug" tag at least for the case where the endpoint returns a non-JSON reply because the error shown to the user in this case is unhelpful.)

**Comment by douganger** [comment]
I'm working on this.
