### ISSUE TITLE
Should we keep Certbot from pushing expired certs live?

### ISSUE THREAD

**Issue by jgillula** [certbot/certbot#5869]
We had a report that due to some other misconfiguration issues, an important website had an outage because Certbot took an old, expired cert it had acquired and made it live.

Should we maybe have some checks that ensure that when Certbot makes a cert live, that cert isn't expired (unless the user uses a --force-expired flag or something like that)?

**Comment by schoen** [comment]
This is slightly related to a distinction that we used to have between renewal and deployment (which we mostly did away with for user-visible purposes).

I think this is probably a good idea. Do you have any information about exactly how this mishap happened? Maybe there's a more specific logic change that could be added that would prevent this particular combination of circumstances from arising again.

**Comment by bmw** [comment]
Do we have more details here? I can reach out to Starchy myself if not, but I'd be potentially interested in fixing this depending on the level of misconfiguration necessary to cause this issue.
