### ISSUE TITLE
Add cPanel UAPI installer

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#5881]
Over on the community forum, I was reminded that acme.sh and a couple of other clients now have support for the cPanel API that lets software use the cPanel "import external certificate" feature without manually going through the cPanel web UI. This is useful on cPanel shared hosts that allow users shell access but have AutoSSL turned off (which is a kind of strange combination but seems to come up fairly regularly—I don't know why).

Using the API, a certificate that's available in a PEM file can be imported into cPanel without having to upload it to cPanel using the web browser. On some of these hosts, clients like acme.sh are then able to have fully-integrated cPanel support for Let's Encrypt certificates that were obtained by the command-line ACME client.

This functionality could be implemented as an installer in Certbot so that users could run, for example, `certbot -a webroot -i cpanel -w /var/www/somewhere -d www.example.com -d example.com`. It would also work reasonably well with `certbot renew`. This might be a very nice experience for the users who find themselves in this particular situation.

Two drawbacks and concerns:

* Most cPanel users *shouldn't* use this method, because they'll have a much better experience using AutoSSL. If we add this, I'm afraid a lot of people will get confused into thinking that it's somehow preferable to AutoSSL, when it's really not. So, it would be interesting to think about how to bring this to the attention only of the target audience and not of the larger group of cPanel users.
* Why *don't* these hosts just have AutoSSL available to the user? Could we somehow get more hosts to do that so that there wouldn't be a need for this functionality?

You can learn more about this with the search

https://community.letsencrypt.org/search?q=uapi

(There are also several other forum threads that talk about it under the term "cPanel API", but the ones that refer to UAPI seem to have the most technical detail.)

**Comment by bmw** [comment]
Due to the drawbacks and concerns you listed and our limited resources, this to me seems like something we'd never get around to actually writing. For this reason, I'm closing this issue, but if you disagree, let's chat!
