### ISSUE TITLE
Cant both https:// & https://www. secure just one of them.

### ISSUE THREAD

**Issue by zer0nem0** [certbot/certbot#5888]
Cant both https:// & https://www. secure just one of them.

1. example.com
2. www.example.com

when i choose 1 then

https://example.com  its OK

but 2 with www is "SSL_ERROR_BAD_CERT_DOMAIN"

when i choose later 2 (www.) then later the 1. (example.com) is same problem with 

"SSL_ERROR_BAD_CERT_DOMAIN" but the www.example.com does it work... its OK

why this sh*t happenning? Please help! Thanks :)

**Comment by joohoi** [comment]
Hi! 
It looks like you are selecting only one of the available domains, and so the requested certificate will only be valid for that single one. Certbot lets you select multiple domains for a certificate, as instructed by the message of the selection dialog.

Previously you have selected either `1` or `2`, but if you select both: `1 2`, you should be good to go! I'll close this issue for now, but feel free to add additional comments if needed and I'll reopen.
