### ISSUE TITLE
Timeout after connect

### ISSUE THREAD

**Issue by hayusama** [certbot/certbot#5893]
Hi, 
I use a SSD vps from ovh my domain name is accessible outside I installed all the packages but at the time of generating the certificate I have this certificate yet everything is good on my side
DNS ok A, AAAA ok,

   Domain: XXX
   Type:   connection
   Detail: Fetching
   http://XXX.fr/.well-known/acme-challenge/OAABm_AdZD6pZjLsXng8OA0H-6bYsiR-                                 AsrZd1SdzUk:
   Timeout after connect (your server may be slow or overloaded)

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.

**Comment by pretech86** [comment]
why you close this please ?
