### ISSUE TITLE
Certbot for Openlitespeed

### ISSUE THREAD

**Issue by dattrn** [certbot/certbot#5896]
Please add a offical support for Openlitespeed.

**Comment by ohemorange** [comment]
Hi @dattrn, thanks for coming by! We'd love for you to write a Certbot plugin for Openlitespeed. You can find more information on how to write a plugin [here](https://certbot.eff.org/docs/contributing.html#writing-your-own-plugin), and if you want support while doing so, the [community forums](https://community.letsencrypt.org) should be able to help you out.
