### ISSUE TITLE
Can't create mutliple subdomains.

### ISSUE THREAD

**Issue by adespain** [certbot/certbot#5897]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## I ran this command and it produced this output:
`letsencrypt certonly --standalone --noninteractive --agree-tos --email email@email.com -d test2.zionsdirect.com --expand -d staging.zionsdirect.com --staging --break-my-certs`

test2 was created first and it works fine, I wanted to add staging.zionsdirect.com as well with the above command but it returns an error: 
```Domain: staging.zionsdirect.com
   Type:   connection
   Detail: Fetching
   http://staging.zionsdirect.com/.well-known/acme-challenge/aRw6VPUtCGnUabdPtvLY271Pv35SiBY8MY5sOjIgIbQ:
   Timeout after connect (your server may be slow or overloaded)

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.```
## Certbot's behavior differed from what I expected because: I may not be doing this right but I want to have 2 virutalhosts on my webserver, one for test2 and one for staging.


## Here is a Certbot log showing the issue (if available):
###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

**Comment by ohemorange** [comment]
Hi @adespain. Looks like this probably isn't a bug in Certbot. Please try asking on the [community forums](https://community.letsencrypt.org/) first, hope it works out for you!
