### ISSUE TITLE
certbot Docker image fails to start on armv71

### ISSUE THREAD

**Issue by scaleoutsean** [certbot/certbot#5907]
## My operating system is (include version):
Raspian Stretch on Pi B, gcc v6.3.0-4 and stock docker.io:
```
$ uname -a
Linux pib 4.14.37-v7+ #1111 SMP Thu Apr 26 13:56:59 BST 2018 armv7l GNU/Linux
```
## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Stock docker.io from Raspbian Stretch, `Docker version 1.8.3, build f4bf5c7`

## I ran this command and it produced this output:

```
$ sudo docker run -it --rm --name testbot \
-p 8080:80 -p 8443:443 \
certbot/certbot
```
After a while:
```
status: Downloaded newer image for certbot/certbot:latest
WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
exec format error

Error response from daemon: Cannot start container a121e0e51b6e613f7da37c9189f93d3e0db4bd9f1dbd8b3bdf7d000f84aba4db: [8] System error: exec format error
```

Container log doesn't contain much useful info:

```
May  1 06:09:42 p1 docker[8986]: time="2018-05-01T06:09:42.018692218+01:00" level=error msg="Handler for POST /containers/{name:.*}/start returned error: Cannot start container 94380d1c571114ea5dd492d9ddb5aecaca8b00ea19e329673ab6d7ba29e1ec78: [8] System error: exec format error"
May  1 06:09:42 p1 docker[8986]: time="2018-05-01T06:09:42.019272683+01:00" level=error msg="HTTP Error" err="Cannot start container 94380d1c571114ea5dd492d9ddb5aecaca8b00ea19e329673ab6d7ba29e1ec78: [8] System error: exec format error" statusCode=500
May  1 06:09:42 p1 docker[8986]: time="2018-05-01T06:09:42.025305044+01:00" level=info msg="DELETE /v1.20/containers/94380d1c571114ea5dd492d9ddb5aecaca8b00ea19e329673ab6d7ba29e1ec78?v=1"
May  1 06:09:42 p1 dhcpcd[318]: docker0: carrier lost
```

There was an arch-related bug in #4009 but related to building the OS.

## Certbot's behavior differed from what I expected because:

* Docker container doesn't start (Edit: I didn't expect this test container to actually work; but I did expect it to start)
* System requirements don't mention architecture support limitations

**Comment by ohemorange** [comment]
Hey @scaleoutsean, thanks for reporting! I recommend bringing this over to the [community forums](https://community.letsencrypt.org/), where people have lots of experience getting our docker images to work on a variety of systems.

**Comment by bmw** [comment]
This issue hasn't seen any updates in a long time. If anyone is still hitting this, please comment or open a new issue.
