### ISSUE TITLE
Certbot Automatically Create pem File that Contains Both privkey.pem and fullchain.pem in One

### ISSUE THREAD

**Issue by own3mall** [certbot/certbot#5909]
## Certificate with Both privkey.pem and fullchain.pem

Would it be possible for certbot to automatically create a pem certificate file that contains both the privkey and fullchain in one pem file when creating a certificate for the first time or when a certificate is renewed?

Programs like courier, lighttpd, and vsftpd use certificates in this format.

Usually, I have to run a command to manually combine both certificates like this:

`cat /etc/letsencrypt/live/test.com/privkey.pem /etc/letsencrypt/live/test.com/fullchain.pem > /etc/letsencrypt/live/test.com/courier.pem && /usr/sbin/service courier-pop-ssl restart && /usr/sbin/service courier-imap-ssl restart`

By default, certbot creates cert.pem, chain.pem, fullchain.pem, and privkey.pem files for each domain. Perhaps another one called mixed.pem could be created (and updated when renewed) by default? This would be ideal because then I don't have to manually combine them.

https://community.letsencrypt.org/t/certbot-pem-automatic-creation-create-pem-file-that-contains-both-privkey-pem-and-fullchain-pem-in-one/60881

#### I installed Certbot with certbot-auto

**Comment by ohemorange** [comment]
Thanks for reporting! Since we're a small team, we can't support every format natively -- that's why we support the hook system that sahsanu described. Looks like that works for this use case, so I'm going to close this issue.

**Comment by own3mall** [comment]
It works, but it's very inconvenient, and it doesn't allow flexibility for other apps to easily integrate with Let's Encrypt.  It would be a nice addition.

**Comment by ohemorange** [comment]
And also #1201
