### ISSUE TITLE
free certbot, why the email is not recognized?

### ISSUE THREAD

**Issue by janeli8** [certbot/certbot#5916]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## I ran this command and it produced this output:
sudo yum install git
sudo git clone https://github.com/certbot/certbot /opt/letsencrypt
cd /opt/letsencrypt
./certbot-auto certonly –standalone –email 2897xxx@qq.com -d www.example.com -d example.com
with right email of Gmail, and right domain name.
But reply with the following
###
 usage: 
  certbot-auto [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...
#
_Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: unrecognized arguments: –standalone –email ******@gmail.com_

## Certbot's behavior differed from what I expected because: there is no reason that my email unrecognized, and then installing stop. I can't find out the reason and want to solve this problem.

Sincerely waiting for news on that, thanks a lot ahead of time.

**Comment by sydneyli** [comment]
@janeli8 It looks like you're using an emdash `–` instead of a double dash `--`?

**Comment by sydneyli** [comment]
@janeli8 Feel free to reopen this if using `--` doesn't solve your issue. Closing for now.
