### ISSUE TITLE
Starting certbot runs into: error unrecognized arguments

### ISSUE THREAD

**Issue by DevTown** [certbot/certbot#5921]
Hi,
I got a problem with the current certbot Version on my system. 
After I want to run certbot renew --dry-run i got the error :  
certbot: error: unrecognized arguments: --max-log-backups 0

When I only run certbot to for displaying the options i also get the same error.
I have installed it after the tutorial for Ubuntu on the certbto main page.

Is this a known error or have i blow up something with a update of my system. ? 

## My operating system is (include version):
	Ubuntu 16.04.4 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS Package

## I ran this command and it produced this output:
 certbot
usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
cert. 

certbot: error: unrecognized arguments: --max-log-backups 0

**Comment by bmw** [comment]
What's the output of `command -v certbot` and `certbot --version`?

I think you might have multiple versions of Certbot installed on your system and the configuration included in `/etc/letsencrypt/cli.ini` from the package in our PPA is confusing the one found first in your `PATH`.

**Comment by DevTown** [comment]
Hi, 
here are the outputs:

## command -v certbot 
/usr/local/bin/certbot

## certbot --version
certbot 0.10.1

## apt search certbot
certbot/xenial,xenial,now 0.22.2-1+ubuntu16.04.1+certbot+1 all [installed]
  automatically configure HTTPS using Let's Encrypt

letsencrypt/xenial,xenial,now 0.22.2-1+ubuntu16.04.1+certbot+1 all [installed]
  transitional dummy package

python-certbot-apache/xenial,xenial 0.22.0-1+ubuntu16.04.1+certbot+2 all
  transitional dummy package

python-certbot-apache-doc/xenial,xenial 0.19.0-1+ubuntu16.04.1+certbot+1 all
  Apache plugin documentation for Certbot

python-certbot-nginx/xenial,xenial,now 0.22.0-1+ubuntu16.04.1+certbot+2 all [installed]
  transitional dummy package

python-certbot-nginx-doc/xenial,xenial 0.19.0-1+ubuntu16.04.1+certbot+1 all
  Nginx plugin documentation for Certbot

python3-certbot/xenial,xenial,now 0.22.2-1+ubuntu16.04.1+certbot+1 all [installed,automatic]
  main library for certbot

python3-certbot-apache/xenial,xenial 0.22.0-1+ubuntu16.04.1+certbot+2 all
  Apache plugin for Certbot

python3-certbot-nginx/xenial,xenial,now 0.22.0-1+ubuntu16.04.1+certbot+2 all [installed,automatic]
  Nginx plugin for Certbot

**Comment by bmw** [comment]
`certbot` in `/usr/local` wasn't installed by the OS packages. It was probably installed by `pip`. Cleaning that up by running `pip uninstall` and/or deleting those directories should solve the problem.

**Comment by DevTown** [comment]
A ok big thx. 
A rm of the file and a "command -p certbot" get it done.

**Comment by bmw** [comment]
Great! I'm going to close this issue, but feel free to comment or open a new issue if I missed something.

**Comment by kronen75** [comment]
Hi at all!

 I've the same problem. It gives me that output:
certbot: error: unrecognized arguments: --max-log-backups 0

**certbot --version**
certbot 0.10.2


**Command -v certbot**
 command -v certbot
/usr/bin/certbot

**apt search certbot:**

apt search certbot
Sorting... Done
Full Text Search... Done
certbot/stable,now 0.10.2-1 all [installed]
  automatically configure HTTPS using Let's Encrypt

letsencrypt/stable 0.10.2-1 all
  transitional dummy package

python-certbot/stable,now 0.10.2-1 all [installed,automatic]
  main library for certbot

python-certbot-apache/stable 0.10.2-1 all
  Apache plugin for Certbot

python-certbot-apache-doc/stable 0.10.2-1 all
  Apache plugin documentation for Certbot

python-certbot-dns-cloudflare-doc/unstable 0.23.0-2 all
  Documentation for the Cloudflare DNS plugin for Certbot

python-certbot-dns-digitalocean-doc/unstable 0.23.0-2 all
  Documentation for the DigitalOcean DNS plugin for Certbot

python-certbot-dns-dnsimple-doc/unstable 0.28.0-1 all
  Documentation for the DNSimple DNS plugin for Certbot

python-certbot-dns-gehirn-doc/unstable 0.28.0-1 all
  Documentation for the Gehirn DNS plugin for Certbot

python-certbot-dns-google-doc/unstable 0.23.0-2 all
  Documentation for the Google DNS plugin for Certbot

python-certbot-dns-linode-doc/unstable 0.28.0-1 all
  Documentation for the Linode DNS plugin for Certbot

python-certbot-dns-ovh-doc/unstable 0.27.1-1 all
  Documentation for the OVH DNS plugin for Certbot

python-certbot-dns-rfc2136-doc/unstable 0.24.0-2 all
  Documentation for the RFC 2136 DNS plugin for Certbot

python-certbot-dns-route53-doc/unstable 0.28.0-1 all
  Documentation for the Route53 DNS plugin for Certbot

python-certbot-dns-sakuracloud-doc/unstable 0.28.0-1 all
  Documentation for the SakuraCloud DNS plugin for Certbot

python-certbot-doc/stable 0.10.2-1 all
  client documentation for certbot

python-certbot-nginx/stable 0.10.2-1 all
  Nginx plugin for Certbot

python-certbot-nginx-doc/stable 0.10.2-1 all
  Nginx plugin documentation for Certbot

python3-certbot/unstable 0.28.0-1 all
  main library for certbot

python3-certbot-apache/unstable 0.28.0-1 all
  Apache plugin for Certbot

python3-certbot-dns-cloudflare/unstable 0.23.0-2 all
  Cloudflare DNS plugin for Certbot

python3-certbot-dns-digitalocean/unstable 0.23.0-2 all
  DigitalOcean DNS plugin for Certbot

python3-certbot-dns-dnsimple/unstable 0.28.0-1 all
  DNSimple DNS plugin for Certbot

python3-certbot-dns-gehirn/unstable 0.28.0-1 all
  Gehirn DNS plugin for Certbot

python3-certbot-dns-google/unstable 0.23.0-2 all
  Google DNS plugin for Certbot

python3-certbot-dns-linode/unstable 0.28.0-1 all
  Linode DNS plugin for Certbot

python3-certbot-dns-ovh/unstable 0.27.1-1 all
  OVH DNS plugin for Certbot

python3-certbot-dns-rfc2136/unstable 0.24.0-2 all
  RFC 2136 DNS plugin for Certbot

python3-certbot-dns-route53/unstable 0.28.0-1 all
  Route53 DNS plugin for Certbot

python3-certbot-dns-sakuracloud/unstable 0.28.0-1 all
  SakuraCloud DNS plugin for Certbot

python3-certbot-nginx/unstable 0.28.0-1 all
  Nginx plugin for Certbot


I've recently installed python3-urllib3_1.24-1_all.deb to can use netdata on my server. Is that possible that urllib3 had changed python 3 that certbot uses?
Thanks!

**Comment by bmw** [comment]
The `--max-log-backups` flag was added in Certbot 0.17.0 but you have 0.10.2 installed. See https://certbot.eff.org/ for how to install a more recent version of Certbot on your system and if you need additional help, please make a post on https://community.letsencrypt.org where there is a large community of people familiar with the project who would be happy to help you.

**Comment by AGO-NX** [comment]
I also have this very same issue:
```
root@machine~# certbot certonly --manual -d mydomain.com --rsa-key-size 4096 --agree-tos --redirect
usage:
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
cert.
certbot: error: unrecognized arguments: --max-log-backups 0

root@machine~#  command -v certbot
/usr/bin/certbot

root@machine~# certbot --version
certbot 0.10.2
```

I did not supply "--max-log-backups" on my command, so why does certbot think so ?

I installed certbot from Debian repos:
```
root@machine~#  apt policy certbot
certbot:
  Installed: 0.10.2-1
  Candidate: 0.10.2-1
  Version table:
 *** 0.10.2-1 500
        500 http://mirrors.online.net/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by nuanceraj** [comment]
Hi , i am getting issue, when i fire apt-get install nginx  command , What could be issued .
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Package nginx is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> E: Package 'nginx' has no installation candidate

**Comment by fazlihon** [comment]
> `certbot`в `/usr/local`не был установлен пакетами ОС. Вероятно, он был установлен `pip`. Очистка этого путем запуска `pip uninstall`и / или удаления этих каталогов должна решить проблему.

What if it prints like this?

certbot: error: unrecognized arguments: status
# command -v certbot
/usr/bin/certbot
# certbot --version
certbot 0.31.0
# letsencrypt --version
certbot 0.31.0
# command -v letsencrypt
/usr/bin/letsencrypt
# apt search certbot

certbot/bionic,bionic,now 0.31.0-1+ubuntu18.04.1+certbot+1 all [установлен, автоматически]
  automatically configure HTTPS using Let's Encrypt

letsencrypt/bionic,bionic 0.31.0-1+ubuntu18.04.1+certbot+1 all
  transitional dummy package

python-certbot-apache/bionic,bionic,now 0.31.0-1+ubuntu18.04.1+certbot+1 all [установлен]
  transitional dummy package

python-certbot-apache-doc/bionic,bionic,bionic,bionic 0.23.0-1 all
  Apache plugin documentation for Certbot

python-certbot-dns-cloudflare-doc/bionic,bionic 0.23.0-1ubuntu0ppa1~ubuntu18.04.1 all
  Documentation for the Cloudflare DNS plugin for Certbot

python-certbot-dns-digitalocean-doc/bionic,bionic 0.23.0-2ubuntu0ppa1~ubuntu18.04.1 all
  Documentation for the DigitalOcean DNS plugin for Certbot

python-certbot-dns-dnsimple-doc/bionic,bionic 0.23.0-2ubuntu0ppa1~ubuntu18.04.1 all
  Documentation for the DNSimple DNS plugin for Certbot

python-certbot-dns-google-doc/bionic,bionic,bionic,bionic 0.23.0-1 all
  Documentation for the Google DNS plugin for Certbot

python-certbot-dns-rfc2136-doc/bionic,bionic 0.24.0-2ubuntu0ppa1~ubuntu18.04.1 all
  Documentation for the RFC 2136 DNS plugin for Certbot

python-certbot-dns-route53-doc/bionic,bionic 0.23.0-2+ubuntu18.04.1+certbot+1 all
  Documentation for the Route53 DNS plugin for Certbot

python-certbot-doc/bionic-updates,bionic-updates,bionic-updates,bionic-updates 0.27.0-1~ubuntu18.04.1 all
  client documentation for certbot

python-certbot-nginx/bionic,bionic 0.31.0-1+ubuntu18.04.1+certbot+1 all
  transitional dummy package

python-certbot-nginx-doc/bionic,bionic,bionic,bionic 0.23.0-1 all
  Nginx plugin documentation for Certbot

python3-certbot/bionic,bionic,now 0.31.0-1+ubuntu18.04.1+certbot+1 all [установлен, автоматически]
  main library for certbot

python3-certbot-apache/bionic,bionic,now 0.31.0-1+ubuntu18.04.1+certbot+1 all [установлен, автоматически]
  Apache plugin for Certbot

python3-certbot-dns-cloudflare/bionic,bionic 0.23.0-1ubuntu0ppa1~ubuntu18.04.1 all
  Cloudflare DNS plugin for Certbot

python3-certbot-dns-digitalocean/bionic,bionic 0.23.0-2ubuntu0ppa1~ubuntu18.04.1 all
  DigitalOcean DNS plugin for Certbot

python3-certbot-dns-dnsimple/bionic,bionic 0.23.0-2ubuntu0ppa1~ubuntu18.04.1 all
  DNSimple DNS plugin for Certbot

python3-certbot-dns-google/bionic,bionic,bionic,bionic 0.23.0-1 all
  Google DNS plugin for Certbot

python3-certbot-dns-rfc2136/bionic,bionic 0.24.0-2ubuntu0ppa1~ubuntu18.04.1 all
  RFC 2136 DNS plugin for Certbot

python3-certbot-dns-route53/bionic,bionic 0.23.0-2+ubuntu18.04.1+certbot+1 all
  Route53 DNS plugin for Certbot

python3-certbot-nginx/bionic,bionic 0.31.0-1+ubuntu18.04.1+certbot+1 all
  Nginx plugin for Certbot
