### ISSUE TITLE
Port sender-only TLS configuration as a Postfix plugin enhancement

### ISSUE THREAD

**Issue by sydneyli** [certbot/certbot#5923]
@bmw and I discussed this offline, the gist of which was:
There should be an easy way for someone to set recommended SMTP configurations for a sending-only server, including the `starttls-policy` enhancement.

This is a little bit odd for `deploy_cert` to do since a sender doesn't need a certificate. Solely using `starttls-policy` to create a Postfix-compatible `tls_policy_maps` file isn't completely sufficient, either, since we'd like to help configure users' TLS setting correctly as well.

An added piece of complexity is that since this enhancement wouldn't be associated with a certificate, we want to allow the `enhance` verb to optionally not be associated with a cert, which would need some discussion around a UI change to allow for this without confusing users.

**Comment by bmw** [comment]
I think this is the kind of thing we should have a plan for and maybe implement before releasing the Postfix plugin because it could be a fairly dramatic change in behavior, but getting the base plugin merged that we can iterate on in smaller PRs seems like a good idea.

**Comment by bmw** [comment]
We're currently not planning on releasing the Postfix plugin (there just isn't the demand/need for it) so I'm closing this for now.
