### ISSUE TITLE
Postfix: Ensure `cipherlist` parameters have not been overwritten.

### ISSUE THREAD

**Issue by sydneyli** [certbot/certbot#5925]
@bmw pointed out that it's possible to [overwrite the default sets of cipherlists](http://www.postfix.org/postconf.5.html#tls_medium_cipherlist) in Postfix. We should check that the user isn't doing this.

**Comment by bmw** [comment]
We're currently not planning on releasing the Postfix plugin (there just isn't the demand/need for it) so I'm closing this for now.
