### ISSUE TITLE
Non-writing commands should work on readonly file system as well

### ISSUE THREAD

**Issue by 0815fox** [certbot/certbot#5931]
I am on an embedded system, similar to #5556. However, I have a more basic request:
1.) Commands which do not alter anything, like

```
certbot certificates
```
Should work without file system write access.
2.) Nice to have would be, when certbot would only access file system between pre-hook and post-hook on renewal, as I originally wanted to use them to remount the file system writable before and readonly after renewal.

Currently certbot wants to create a lock file in any case and expecially before executing the pre-hook:
[Errno 30] Read-only file system: '/etc/letsencrypt/.certbot.lock'

I am on ubuntu btw.

**Comment by jgillula** [comment]
I have a feeling this would require a somewhat intensive rewrite of how Certbot uses lock files. @ohemorange is that correct?

**Comment by ohemorange** [comment]
Yes, this would require adding a good deal of complexity to our lock system. I think @schoen's suggestions in #5556 will apply here as well. Closing this issue because we're unlikely to implement these changes.
