### ISSUE TITLE
Use or remove old reuse-key-related code in storage.py

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#5942]
Somewhat related to #5901.

There is existing code in `save_successor` at

https://github.com/certbot/certbot/blob/master/certbot/storage.py#L1113

when we can pass `None` instead of a new private key, and it will attempt to make a special symlink structure that literally reuses the old private key instead of making a new copy of it. I believe that I may have written other code elsewhere in `storage.py` that also recognizes this unusual symlink structure.

Currently, I believe this code and this option are never used at all under any circumstances, although they were *intended* for use in something like the `--reuse-key` option. We should review them and figure out whether we want to use this code and this approach for anything, or else maybe remove the code and the possibility of passing `None` for the private key.

(The PR at #5901 doesn't make use of this code at all; instead, it just makes a fresh copy of the old key via a separate code path in `client.py`.)

Cc @ohemorange.

**Comment by ohemorange** [comment]
@schoen is this used now? or can we still remove it?
