### ISSUE TITLE
Link HTTPS Connection Error to Status Page

### ISSUE THREAD

**Issue by JZL** [certbot/certbot#5945]
## My operating system is (include version):
Distributor ID: Debian
Description:    Debian GNU/Linux 8.10 (jessie)
Release:        8.10
Codename:       jessie

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
docker

## I ran this command and it produced this output:
`sudo docker run -it --rm --name certbot -v "/etc/letsencrypt:/etc/letsencrypt" -v "/var/lib/letsencrypt:/var/lib/letsencrypt" certbot/certbot certonly --manual --server https://acme-v02.api.letsencrypt.org/directory`
Gave
```An unexpected error occurred:
ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f53a1d351d0>: Failed to establish a new connection: [Errno -3] Try again',))
Please see the logfiles in /var/log/letsencrypt for more details.
```

## Certbot's behavior differed from what I expected because:
It does not point to https://letsencrypt.status.io/ to help demonstrate that this is a scheduled downtime

Hi,

I am finding cerbot invaluable for my small server cluster and am transitioning all my certs to using it (thanks!). In particular, I need a wildcard cert so have been using `docker` with the `v2` acme server. When I was transitioning to another server at May 9, 2018 11:28EST there is a planned maintenance (`May 9, 2018 14:46 UTC[Update] We are starting our datacenter upgrades and maintenance. Staging will be offline and unavailable during this time. Production services will be fully available.`) causing (I assume) this HTTPS connection error. I understand that scheduled maintenance is rare but, similar to #4535 I think the error message could be improved. 

I am happy to work on the PR if this seems like a good fit

**Comment by joohoi** [comment]
Hi, and thanks for opening an issue. While Certbot uses Let's Encrypt as a default CA, and uses directory paths like `/etc/letsencrypt/` and `/var/lib/letsencrypt` as a default, it's still a generic ACME client. 

My personal opinion is that we probably shouldn't tie it _more_ to Let's Encrypt, while LE is currently the only public trusted CA using ACME protocol. This, however is a personal opinion, but I'll raise this issue up for internal discussion.

**Comment by JZL** [comment]
Thanks! That makes a lot of sense, as I said, this is a really small improvement and doesn't really detract from the awesomeness of it in general. Regardless of Let's Encrypt, I think it could be helpful to improve the error catching for these types of bugs and, maybe, point the developer to look at status pages in general

Thanks again for your prompt response

**Comment by joohoi** [comment]
A bit of offtopic; there is an awesome project that helps people debug the problems they're facing with the validation that also checks the LE status: 
https://letsdebug.net/
https://github.com/letsdebug/letsdebug

**Comment by bmw** [comment]
While I appreciate the suggestion and understand it's value, I don't think we should do this for the reason joohoi described of there not being a generic status page we can point to so I'm closing this issue.

**Comment by JZL** [comment]
Thanks for your kind response and for keeping certbot running ^^
