### ISSUE TITLE
instalation error

### ISSUE THREAD

**Issue by winteraz** [certbot/certbot#5946]
I'm trying to install certbot on centos. However I get the error below. Is  there any binary form that I can use so that I can avoid all this configuration mess? 

Installed /usr/lib/python2.6/site-packages/certbot-0.25.0.dev0-py2.6.egg
Processing dependencies for certbot==0.25.0.dev0
Searching for mock
Reading https://pypi.python.org/simple/mock/
Best match: mock 2.0.0
Downloading https://files.pythonhosted.org/packages/0c/53/014354fc93c591ccc4abff12c473ad565a2eb24dcd82490fae33dbf2539f/mock-2.0.0.tar.gz#sha256=b158b6df76edd239b8208d481dc46b6afd45a846b7812ff0ce58971cf5bc8bba
Processing mock-2.0.0.tar.gz
Running mock-2.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-pS0Lq6/mock-2.0.0/egg-dist-tmp-bdou17
Checking .pth file support in .
/usr/bin/python -E -c pass
Searching for pbr>=1.3
Reading https://pypi.python.org/simple/pbr/
Best match: pbr 4.0.2
Downloading https://files.pythonhosted.org/packages/c6/46/f414e7d9ba9621c8acd3e7a82e08c47e0de34ad3e213c16e458b6c04d432/pbr-4.0.2.tar.gz#sha256=dae4aaa78eafcad10ce2581fc34d694faa616727837fd8e55c1a00951ad6744f
Processing pbr-4.0.2.tar.gz
Running pbr-4.0.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-pS0Lq6/mock-2.0.0/temp/easy_install-IGaK27/pbr-4.0.2/egg-dist-tmp-XedrKB
/usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
/usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'project_urls'
  warnings.warn(msg)

Installed /tmp/easy_install-pS0Lq6/mock-2.0.0/pbr-4.0.2-py2.6.egg
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/tmp/easy_install-pS0Lq6/mock-2.0.0/pbr-4.0.2-py2.6.egg/pbr/core.py", line 96, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/tmp/easy_install-pS0Lq6/mock-2.0.0/pbr-4.0.2-py2.6.egg/pbr/util.py", line 260, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/tmp/easy_install-pS0Lq6/mock-2.0.0/pbr-4.0.2-py2.6.egg/pbr/util.py", line 454, in setup_cfg_to_setup_kwargs
    if pkg_resources.evaluate_marker('(%s)' % env_marker):
AttributeError: 'module' object has no attribute 'evaluate_marker'
error: Setup script exited with error in setup command: Error parsing /tmp/easy_install-pS0Lq6/mock-2.0.0/setup.cfg: AttributeError: 'module' object has no attribute 'evaluate_marker'

**Comment by schoen** [comment]
Please reopen this if you're still having trouble with it and you can provide the requested information from the template! Thanks.
