### ISSUE TITLE
wildcard doesn't work.

### ISSUE THREAD

**Issue by winteraz** [certbot/certbot#5947]
I managed to run certbot from a docker image(installing locally had no chance due some python errors). However wildcard doesn't work. Why is that? I thought it's in production yet, isn't it ?

./certbot-auto certonly --standalone  -d xxx.net -d *.xxx.net
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
The currently selected ACME CA endpoint does not support issuing wildcard certificates.

**Comment by sydneyli** [comment]
Hi @winteraz! You'll need to change the endpoint to the ACME v2 endpoint with the flags `--server https://acme-v02.api.letsencrypt.org/directory`.

We have an issue open to change this to the default endpoint: #5369 so closing this in favor of that one for now. Feel free to re-open if you catch any more weirdness.
