### ISSUE TITLE
Standalone Authenticator should prompt repeatedly until 443 is available.

### ISSUE THREAD

**Issue by PatrickHeppler** [certbot/certbot#595]
When calling standalone authenticator while nginx or apache is running it should automatically stop it and restart it after finishing auth instead of throwing an error.

```
letsencrypt -d example.com -t auth

How would you like to authenticate with Let's Encrypt CA?
-------------------------------------------------------------------------------
1: Nginx Web Server (nginx)
2: Manual Authenticator (manual)
3: Standalone Authenticator (standalone)
-------------------------------------------------------------------------------
Select the appropriate number [1-3] then [enter] (press 'c' to cancel): 3

-------------------------------------------------------------------------------
The program nginx (process ID 19803) is already listening on TCP port 443. This
will prevent us from binding to that port. Please stop the nginx program
temporarily and then try again.
-------------------------------------------------------------------------------
Press Enter to Continue
An unexpected error occurred. Please see the logfiles in /var/log/letsencrypt for more details.
```

**Comment by kuba** [comment]
We don't want to take down websites without user's consent, hence the kind message: "Please stop the nginx program temporarily and the try again.". Having optional `--standalone-autostop-running-httpd` seems like an overkill to me.

Nonetheless, the last line of output shouldn't happen this way. I presume you hit Enter, without stopping nginx, which must have caused some panic in the code: and that's an error to be fixed. Please paste the full traceback, to be found in the last couple of lines of `/var/log/letsencrypt`.

**Comment by PatrickHeppler** [comment]
Yes, I just hit Enter without stopping nginx. How about asking to stop?
```
How would you like to authenticate with Let's Encrypt CA?
-------------------------------------------------------------------------------
1: Nginx Web Server (nginx)
2: Manual Authenticator (manual)
3: Standalone Authenticator (standalone)
-------------------------------------------------------------------------------
Select the appropriate number [1-3] then [enter] (press 'c' to cancel): 3

-------------------------------------------------------------------------------
The program nginx (process ID 19803) is already listening on TCP port 443. This
will prevent us from binding to that port. 
-------------------------------------------------------------------------------
Would you like to stop nginx [y/n]:
```

**Comment by kuba** [comment]
But how do you that? `kill 19803`? `kill -9 19803`? `service $proc_name stop` and hope that `$proc_name` corresponds to the service name? `systemctl stop $proc_name`? `/etc/init.d/$proc_name`? `service stop haproxy`? There are just so many different httpds, configurations, distros, so many possibilities...

**Comment by PatrickHeppler** [comment]
How does the nginx plugin handle it? Doesn't it also restart nginx?

**Comment by jsha** [comment]
I agree with Kuba: The standalone authenticator should not interact directly with the web server. However, it should definitely loop until the necessary port is actually available. Changing the ticket name appropriately.

**Comment by chilinux** [comment]
You could just leverage that Issue #19 has been resolved.   The Lets Encrypt protocol should now support use of ports other than 443.   Just re-attempt with a binding to a port other than 443.  While the protocol spec does not require the CA to support a different port than 443 (and probably should always refuse any above 1023), it should at least give an error response back specifying that is the reason why.  So there should be nothing to loose by the script at least trying.

**Comment by ssbarnea** [comment]
Any updates on this? I do not see any reasons why I should stop nginx or another web server running on the machine in order to be able to generate some certificates. The current behaviour gives a really bad user experience.

**Comment by jsha** [comment]
@ssbarnea: It sounds like you want the webroot authenticator rather than the standalone authenticator. But the choice between the two authenticators is a bit off-topic for this thread.

**Comment by bmw** [comment]
I'm planning on resolving this issue with my PR for #3650. I have to rework how we handle errors here anyway.
