### ISSUE TITLE
Apache unit tests should not touch the global Apache config

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5955]
When working on the developer docs, I came across the following text:

> Also note that the full test suite will attempt to modify your system's Apache config if your user has sudo permissions, so it should not be run on a production Apache server.

We do what?

Looking through commit history, I wonder if this info is accurate. #4211 changed the docs from talking about `apacheconftest` to the test suite run with `tox`. `apacheconftest` does modify the global config (which in my opinion is one more reason get rid of it, see #5938), but it does not run when you run `tox`. See https://tox.readthedocs.io/en/latest/config.html#confval-envlist=CSV and https://github.com/certbot/certbot/blob/8851141dcf93d8e6c080bcd1503e64762fcebf1b/tox.ini#L7.

If this information is inaccurate, we should delete it. If it is accurate, we should fix this and then delete this warning.

cc @joohoi

**Comment by joohoi** [comment]
We should probably do better job in separating the test suites that do or might do changes to the system (which, unlike the the title of this issue suggests, are not unit tests, but test units ;), and actual unit tests that we encourage (and should encourage) all contributors to run.

The separation should happen in both, documentation and the actual test code as well. Maybe we could consider having a separate repository for running the potentially destructive tests?

**Comment by bmw** [comment]
I think the issue I had in mind here is an easy fix and we should bump the priority a bit.

My reason for creating this issue was that the warning at https://certbot.eff.org/docs/contributing.html#testing seems misleading. At that link, we talk about running the "full test suite" with `tox --skip-missing-interpreters`. Right after that, we have the warning I copied above about our "full test suite" modifying your Apache config.

Unless our Apache unit tests are modifying the system's Apache config (which they certainly shouldn't be), running `tox --skip-missing-interpreters` will never modify the system's Apache config so I think that warning there unnecessarily discourages people from running our tests.

I think we should either:

1. Delete that warning.
2. Change the warning to explain that some the environments in `tox.ini` (not including any of the commands we suggest the dev run above or that are run with the simple command `tox`) can make global modifications to your system so they should not be run on a production server.
