### ISSUE TITLE
Python 3 socket.getfqdn() crashes when local hostname is more than 63 characters

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#5958]
https://community.letsencrypt.org/t/attempting-to-generate-cert-getting-unicodeerror-encoding-with-idna-codec-failed/61675

This prevents account registration in this case when Certbot is run with Python 3. It wasn't a problem in Python 2, which doesn't crash under these circumstances.

Do we want to stop using `socket.getfqdn()`, or do we want to ask the Python developers to change this behavior? (The hostnames in question *are* invalid according to the DNS specifications, so it's not quite clear what the proper behavior should be from the point of view of the `socket` library.)

We could also catch the specific exception and provide a more useful error to the user.

**Comment by SurenNihalani** [comment]
I could be wrong but from a quick grep, it seems like creation_host isn't used functionally anywhere (other than for showing in view/json reading purposes or repr purposes). I'd propose that we except the Exception and set a sane default string like "HostNameTooLong: (expected to be <= 63 chars according to RFC3490 but actually is 90 chars)"

**Comment by SurenNihalani** [comment]
Also, I think we could merge this with #5311
