### ISSUE TITLE
Sensible UI logging for typical user

### ISSUE THREAD

**Issue by jdkasten** [certbot/certbot#599]
There currently isn't any output that provides reasonable detail about the underlying process.

-v is the closest, but it suffers from informing the user about every single HTTPS connection and could use some general cleanup.

It would be nice to have a mode that was similar to the display seen in the Ncurses demo.  https://youtu.be/Gas_sSB-5SU?t=51

**Comment by kuba** [comment]
#532 and #553 have deliberately introduced named loggers: `logger = logging.getLogger(__name__)`, which allows us to create dialog [log handler](https://docs.python.org/2/howto/logging.html#handlers) or generic [filter](https://docs.python.org/2/library/logging.html#logging.Filter) that discard anything not in the `letsencrypt.*` namespace, including `requests` logs for HTTPS connections.

More info:
- https://docs.python.org/2/library/logging.html
- https://docs.python.org/2/howto/logging.html#logging-basic-tutorial
- https://docs.python.org/2/howto/logging.html#logging-advanced-tutorial

**Comment by bmw** [comment]
To provide some additional information here, we could probably cleanup the logging format provided in the UI and set the default logging level to info. We'd probably want to cleanup the messages provided to `logger.info` to make sure they are sane.
