### ISSUE TITLE
Document how to get a Python 3 venv

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5991]
`tools/venv3.sh`

**Comment by jameshiebert** [comment]
I can add this. Just in the contributing documentation, correct?

**Comment by bmw** [comment]
Yep! `docs/contributing.rst`. Probably makes the most sense to put it in the first section where it's talking about `tools/venv.sh`, but I'm open to other ideas. See https://certbot.eff.org/docs/contributing.html#updating-the-documentation for how to build the documentation locally.
