### ISSUE TITLE
Cant install on OpenBSD - python code problems

### ISSUE THREAD

**Issue by SpinMD** [certbot/certbot#6019]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
pkg_add

## I ran this command and it produced this output:
certbot certonly
python2.7:/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol '__builtin_unreachable'
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.22.2', 'console_scripts', 'certbot')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2608, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2268, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2274, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/certbot/main.py", line 10, in <module>
    import josepy as jose
  File "/usr/local/lib/python2.7/site-packages/josepy/__init__.py", line 41, in <module>
    from josepy.interfaces import JSONDeSerializable
  File "/usr/local/lib/python2.7/site-packages/josepy/interfaces.py", line 8, in <module>
    from josepy import errors, util
  File "/usr/local/lib/python2.7/site-packages/josepy/util.py", line 4, in <module>
    import OpenSSL
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: Cannot load specified object

## Certbot's behavior differed from what I expected because:
its a crash report

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
did not get that far

**Comment by joohoi** [comment]
Thanks for opening the issue. For me it looks like a dependency issue, I reached out to the Certbot OpenBSD package maintainer for insight over this, as I do not have the sufficient knowledge to assist you further.

I'll keep this issue updated.

**Comment by sthen** [comment]
Hi (OpenBSD port maintainer here). I just tested with a clean OpenBSD 6.3 installation. Steps were: install OpenBSD, login as root, pkg_add certbot, run "certbot certonly". This starts up okay so I don't think there is a general issue with the package or dependencies.

I'll go for the most likely causes first:

- Was the machine upgraded from a previous OpenBSD version? If so, did you remember to update all packages (pkg_add -u)?

- Is there anything strange in your shell environment when running this? Try "env -i certbot".

If these don't help, please post a bit more information about how the machine is setup and output from the following commands (in full, don't trim):

```
$ pkg_info
$ env LD_DEBUG=1 python2.7 -c 'from cryptography.hazmat.bindings._openssl import ffi, lib'
$ dmesg
```

I don't think this is a certbot problem as such, so it's probably best to take this to ports@openbsd.org where more people who can help are likely to see it.

**Comment by SpinMD** [comment]
Hi

This is a fresh install (done two days ago), not an upgrade. Has php,
mysql, ee and not much else.
There is a Wordpress installation which was running with a legit cert, but
Firefox decided to complain about the cert last night.


bzip2-1.0.6p8       block-sorting file compressor, unencumbered
certbot-0.22.2      client for certificate authorities using ACME protocols
curl-7.59.0         get files from FTP, Gopher, HTTP or HTTPS servers
ee-1.5.2p2v0        easy to use text editor
femail-1.0p1        simple SMTP client
femail-chroot-1.0p2 simple SMTP client for chrooted web servers
gettext-0.19.8.1p1  GNU gettext runtime libraries and programs
libffi-3.2.1p4      Foreign Function Interface
libiconv-1.14p3     character set conversion library
libidn2-2.0.0p0     implementation of IDNA2008 internationalized domain
names
libpsl-0.17.0       public suffix list library
libunistring-0.9.7  manipulate Unicode strings
libxml-2.9.8        XML parsing library
mariadb-client-10.0.34v1 multithreaded SQL database (client)
mariadb-server-10.0.34v1 multithreaded SQL database (server)
nghttp2-1.31.0      library for HTTP/2
p5-Clone-0.38       recursively copy Perl datatypes
p5-DBD-mysql-4.042  MySQL drivers for the Perl DBI
p5-DBI-1.633        unified perl interface for database access
p5-FreezeThaw-0.5001 module for converting structures to strings and back
p5-MLDBM-2.05       store multi-level hash structure in single-level tied
hash
p5-Math-Base-Convert-0.08p0 very fast base to base conversion
p5-Module-Runtime-0.014 runtime module handling
p5-Net-Daemon-0.48p0 extension for portable daemons
p5-Params-Util-1.07p1 utility to make parameter checking easier
p5-PlRPC-0.2020     module for writing rpc servers and clients
p5-SQL-Statement-1.407 SQL parsing and processing engine
pcre-8.41           perl-compatible regular expression library
php-5.6.34          server-side HTML-embedded scripting language
php-curl-5.6.34     curl URL library extensions for php
php-mysqli-5.6.34   mysql database access extensions for php
php-pdo_mysql-5.6.34 PDO mysql database access extensions for php
py-ConfigArgParse-0.12.0 argparse replacement, allows options to be set via
files/env
py-acme-0.22.2      ACME protocol implementation
py-asn1-0.3.7v0     ASN.1 library for Python
py-asn1crypto-0.23.0 fast ASN.1 parser and serializer
py-certifi-2017.4.17 Python package to check certificates using the OpenBSD
CA
py-cffi-1.10.0      Foreign Function Interface for Python calling C code
py-chardet-3.0.4    character encoding auto-detection in Python
py-configobj-5.0.6p1 config file reader and writer
py-cparser-2.18     C parser in pure Python
py-cryptography-2.1.4p0 cryptographic recipes and primitives for Python
py-enum34-1.1.6     Python 3.4 Enum backported to previous versions
py-funcsigs-1.0.2p0 Python function signatures from PEP362 for 2.6, 2.7,
3.2+
py-idna-2.5         Python library to support the IDNA protocol
py-ipaddress-1.0.18 Python 3.3's ipaddress for Python 2.6 and 2.7
py-josepy-1.0.1p0   Javascript Object Signing and Encryption (JOSE)
py-mock-2.0.0p0     python mocking and patching library for testing
py-ndg-httpsclient-0.4.3 enhanced HTTPS support for httplib and urllib2
py-openssl-16.2.0   Python interface to the OpenSSL library
py-parsedatetime-2.4 parse human-readable date/time text
py-pbr-1.8.1p0      Python Build Reasonableness
py-pyRFC3339-1.0p1  format dates according to RFC3339
py-requests-2.18.4  elegant and simple HTTP library for Python
py-setuptools-28.6.1p0v0 simplified packaging system for Python modules
py-six-1.10.0p0     Python 2 and 3 compatibility library
py-tz-2018.3        Python API for dealing with timezones
py-urllib3-1.22     HTTP library for Python
py-werkzeug-0.12.1  WSGI utility collection
py-zopecomponent-4.2.2p1 component architecture from Zope
py-zopeevent-4.2.0p0 very basic event publishing system from Zope
py-zopeinterface-4.4.0 object interface infrastructure from Zope
python-2.7.14p1     interpreted object-oriented programming language
quirks-2.414        exceptions to pkg_add rules
sqlite3-3.22.0p0    embedded SQL implementation
wget-1.19.4         retrieve files from the web via HTTP, HTTPS and FTP
xz-5.2.3p0          LZMA compression and decompression tools

env LD_DEBUG=1 python2.7 -c 'from cryptography.hazmat.bindings._openssl
import ffi, lib'
ld.so loading: 'python2.7'
exe load offset:  0x6714a00000
 flags python2.7 = 0x0
head python2.7
obj python2.7 has python2.7 as head
examining: 'python2.7'
loading: libpython2.7.so.0.0 required by python2.7
 flags /usr/local/lib/libpython2.7.so.0.0 = 0x0
obj /usr/local/lib/libpython2.7.so.0.0 has python2.7 as head
loading: libpthread.so.25.1 required by python2.7
 flags /usr/lib/libpthread.so.25.1 = 0x8
obj /usr/lib/libpthread.so.25.1 has python2.7 as head
loading: libm.so.10.1 required by python2.7
 flags /usr/lib/libm.so.10.1 = 0x0
obj /usr/lib/libm.so.10.1 has python2.7 as head
loading: libc.so.92.3 required by python2.7
 flags /usr/lib/libc.so.92.3 = 0x0
obj /usr/lib/libc.so.92.3 has python2.7 as head
loading: libutil.so.13.0 required by python2.7
 flags /usr/lib/libutil.so.13.0 = 0x0
obj /usr/lib/libutil.so.13.0 has python2.7 as head
linking dep /usr/local/lib/libpython2.7.so.0.0 as child of python2.7
objname /usr/lib/libpthread.so.25.1 is nodelete
linking dep /usr/lib/libpthread.so.25.1 as child of python2.7
linking dep /usr/lib/libutil.so.13.0 as child of python2.7
linking dep /usr/lib/libm.so.10.1 as child of python2.7
linking dep /usr/lib/libc.so.92.3 as child of python2.7
examining: '/usr/local/lib/libpython2.7.so.0.0'
loading: libm.so.10.1 required by /usr/local/lib/libpython2.7.so.0.0
loading: libpthread.so.25.1 required by /usr/local/lib/libpython2.7.so.0.0
loading: libutil.so.13.0 required by /usr/local/lib/libpython2.7.so.0.0
linking dep /usr/lib/libpthread.so.25.1 as child of
/usr/local/lib/libpython2.7.so.0.0
linking dep /usr/lib/libutil.so.13.0 as child of
/usr/local/lib/libpython2.7.so.0.0
linking dep /usr/lib/libm.so.10.1 as child of
/usr/local/lib/libpython2.7.so.0.0
examining: '/usr/lib/libpthread.so.25.1'
examining: '/usr/lib/libutil.so.13.0'
examining: '/usr/lib/libm.so.10.1'
examining: '/usr/lib/libc.so.92.3'
 flags /usr/libexec/ld.so = 0x0
obj /usr/libexec/ld.so has python2.7 as head
static tls size=0 align=8 offset=0
protect start RELRO = 0x69bf473070 in /usr/lib/libc.so.92.3
protect end RELRO = 0x69bf478000 in /usr/lib/libc.so.92.3
protect start RELRO = 0x69c358b340 in /usr/lib/libm.so.10.1
protect end RELRO = 0x69c358e000 in /usr/lib/libm.so.10.1
protect start RELRO = 0x69ced3d858 in /usr/lib/libutil.so.13.0
protect end RELRO = 0x69ced3e000 in /usr/lib/libutil.so.13.0
protect start RELRO = 0x6a05f53c50 in /usr/lib/libpthread.so.25.1
protect end RELRO = 0x6a05f54000 in /usr/lib/libpthread.so.25.1
protect start RELRO = 0x69b35420b0 in /usr/local/lib/libpython2.7.so.0.0
protect end RELRO = 0x69b354e000 in /usr/local/lib/libpython2.7.so.0.0
protect start RELRO = 0x6714d01e00 in python2.7
protect end RELRO = 0x6714d02000 in python2.7
        Start            End              Type  Open Ref GrpRef Name
        0000006714a00000 0000006714d04000 exe   2    0   0      python2.7
        00000069b3098000 00000069b35a6000 rlib  0    1   0
/usr/local/lib/libpython2.7.so.0.0
        0000006a05c4c000 0000006a05f56000 rlib  0    2   0
/usr/lib/libpthread.so.25.1
        00000069cea30000 00000069ced40000 rlib  0    2   0
/usr/lib/libutil.so.13.0
        00000069c3234000 00000069c3590000 rlib  0    2   0
/usr/lib/libm.so.10.1
        00000069bf0a0000 00000069bf490000 rlib  0    1   0
/usr/lib/libc.so.92.3
        0000006a0ef00000 0000006a0ef00000 ld.so 0    1   0
/usr/libexec/ld.so
symcache lookups 333 hits 0 ratio 0% hits
dynamic loading done, success.
tib new=0x6a13cf8d40
setting environ 0x6a0f212008@/usr/libexec/ld.so[0x691c0d8800] from
0x6a0f212008
setting __progname 0x6a0f212010@/usr/libexec/ld.so[0x691c0d8800] from
0x6a0f212010
doing ctors obj 0x69a76c4800 @0x6a05c4c2a8: [/usr/lib/libpthread.so.25.1]
doing ctors obj 0x691c0d9000 @0x69cea302a8: [/usr/lib/libutil.so.13.0]
doing ctors obj 0x69a76c4c00 @0x69c32342a8: [/usr/lib/libm.so.10.1]
doing ctors obj 0x691c0d9800 @0x69b30982e0:
[/usr/local/lib/libpython2.7.so.0.0]
entry point: 0x6714a00380
dlctl: _dl_thread_fnc set to 0x6a05c4c740
dlopen: loading: /usr/local/lib/python2.7/lib-dynload/_locale.so
 flags /usr/local/lib/python2.7/lib-dynload/_locale.so = 0x0
head /usr/local/lib/python2.7/lib-dynload/_locale.so
obj /usr/local/lib/python2.7/lib-dynload/_locale.so has
/usr/local/lib/python2.7/lib-dynload/_locale.so as head
linking /usr/local/lib/python2.7/lib-dynload/_locale.so as dlopen()ed
head [/usr/local/lib/python2.7/lib-dynload/_locale.so]
examining: '/usr/local/lib/python2.7/lib-dynload/_locale.so'
loading: libpthread.so.25.1 required by
/usr/local/lib/python2.7/lib-dynload/_locale.so
loading: libpython2.7.so.0.0 required by
/usr/local/lib/python2.7/lib-dynload/_locale.so
loading: libintl.so.6.0 required by
/usr/local/lib/python2.7/lib-dynload/_locale.so
 flags /usr/local/lib/libintl.so.6.0 = 0x0
obj /usr/local/lib/libintl.so.6.0 has
/usr/local/lib/python2.7/lib-dynload/_locale.so as head
linking dep /usr/local/lib/libintl.so.6.0 as child of
/usr/local/lib/python2.7/lib-dynload/_locale.so
linking dep /usr/local/lib/libpython2.7.so.0.0 as child of
/usr/local/lib/python2.7/lib-dynload/_locale.so
linking dep /usr/lib/libpthread.so.25.1 as child of
/usr/local/lib/python2.7/lib-dynload/_locale.so
examining: '/usr/local/lib/libintl.so.6.0'
loading: libiconv.so.6.0 required by /usr/local/lib/libintl.so.6.0
 flags /usr/local/lib/libiconv.so.6.0 = 0x0
obj /usr/local/lib/libiconv.so.6.0 has
/usr/local/lib/python2.7/lib-dynload/_locale.so as head
linking dep /usr/local/lib/libiconv.so.6.0 as child of
/usr/local/lib/libintl.so.6.0
examining: '/usr/local/lib/libiconv.so.6.0'
tail /usr/local/lib/python2.7/lib-dynload/_locale.so
protect start RELRO = 0x69b39aeca8 in /usr/local/lib/libiconv.so.6.0
protect end RELRO = 0x69b39b2000 in /usr/local/lib/libiconv.so.6.0
protect start RELRO = 0x691f67f9d0 in /usr/local/lib/libintl.so.6.0
protect end RELRO = 0x691f680000 in /usr/local/lib/libintl.so.6.0
protect start RELRO = 0x69a89ed8d0 in
/usr/local/lib/python2.7/lib-dynload/_locale.so
protect end RELRO = 0x69a89ee000 in
/usr/local/lib/python2.7/lib-dynload/_locale.so
doing ctors obj 0x69bd130400 @0x69b35a82a8: [/usr/local/lib/libiconv.so.6.0]
doing ctors obj 0x69bd131c00 @0x691f3742a8: [/usr/local/lib/libintl.so.6.0]
doing ctors obj 0x691ed8c000 @0x69a86e82e0:
[/usr/local/lib/python2.7/lib-dynload/_locale.so]
dlopen: /usr/local/lib/python2.7/lib-dynload/_locale.so: done (success).
dlsym: init_locale in /usr/local/lib/python2.7/lib-dynload/_locale.so:
0x69a86e8560
dlopen: loading:
/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
 flags
/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
= 0x0
head
/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
obj
/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
has
/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
as head
linking
/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
as dlopen()ed
head
[/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so]
examining:
'/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so'
loading: libpython2.7.so.0.0 required by
/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
loading: libpthread.so.25.1 required by
/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
loading: libcrypto.so.43.1 required by
/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
 flags /usr/lib/libcrypto.so.43.1 = 0x0
obj /usr/lib/libcrypto.so.43.1 has
/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
as head
loading: libssl.so.45.1 required by
/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
 flags /usr/lib/libssl.so.45.1 = 0x0
obj /usr/lib/libssl.so.45.1 has
/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
as head
linking dep /usr/lib/libssl.so.45.1 as child of
/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
linking dep /usr/lib/libcrypto.so.43.1 as child of
/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
linking dep /usr/local/lib/libpython2.7.so.0.0 as child of
/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
linking dep /usr/lib/libpthread.so.25.1 as child of
/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
examining: '/usr/lib/libssl.so.45.1'
loading: libcrypto.so.43.1 required by /usr/lib/libssl.so.45.1
linking dep /usr/lib/libcrypto.so.43.1 as child of /usr/lib/libssl.so.45.1
examining: '/usr/lib/libcrypto.so.43.1'
tail
/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
protect start RELRO = 0x69a3e63f28 in /usr/lib/libcrypto.so.43.1
protect end RELRO = 0x69a3e80000 in /usr/lib/libcrypto.so.43.1
protect start RELRO = 0x69cfab2d80 in /usr/lib/libssl.so.45.1
protect end RELRO = 0x69cfab6000 in /usr/lib/libssl.so.45.1
python2.7:/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so:
undefined symbol '__builtin_unreachable'
protect start RELRO = 0x6a10ac7760 in
/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
protect end RELRO = 0x6a10ade000 in
/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
unload_shlib called on
/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
unload_shlib called on /usr/lib/libssl.so.45.1
unload_shlib called on /usr/lib/libcrypto.so.43.1
unload_shlib unloading on /usr/lib/libcrypto.so.43.1
unload_shlib unloading on /usr/lib/libssl.so.45.1
unload_shlib called on /usr/lib/libcrypto.so.43.1
unload_shlib called on /usr/local/lib/libpython2.7.so.0.0
unload_shlib called on /usr/lib/libpthread.so.25.1
unload_shlib unloading on
/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
dlopen:
/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so:
done (failed).
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: Cannot load specified object
doing dtors obj 0x691ed8c000 @0x69a86e9e60:
[/usr/local/lib/python2.7/lib-dynload/_locale.so]
doing dtors obj 0x69bd131c00 @0x691f37b560: [/usr/local/lib/libintl.so.6.0]
doing dtors obj 0x69bd130400 @0x69b35c9ae0: [/usr/local/lib/libiconv.so.6.0]
doing dtors


dmesg
console is /virtual-devices@100/console@1
Copyright (c) 1982, 1986, 1989, 1991, 1993
        The Regents of the University of California.  All rights reserved.
Copyright (c) 1995-2018 OpenBSD. All rights reserved.
https://www.OpenBSD.org

OpenBSD 6.3 (GENERIC.MP) #486: Sat Mar 24 22:37:16 MDT 2018
    deraadt@sparc64.openbsd.org:/usr/src/sys/arch/sparc64/compile/GENERIC.MP
real mem = 1572864000 (1500MB)
avail mem = 1524793344 (1454MB)
mpath0 at root
scsibus0 at mpath0: 256 targets
mainbus0 at root: Sun Fire T200
cpu0 at mainbus0: SUNW,UltraSPARC-T1 (rev 0.0) @ 1000 MHz
cpu1 at mainbus0: SUNW,UltraSPARC-T1 (rev 0.0) @ 1000 MHz
vbus0 at mainbus0
"flashprom" at vbus0 not configured
cbus0 at vbus0
vdsk0 at cbus0 chan 0x2: ivec 0x4, 0x5
scsibus1 at vdsk0: 2 targets
sd0 at scsibus1 targ 0 lun 0: <SUN, Virtual Disk, 1.1> SCSI3 0/direct fixed
sd0: 6144MB, 512 bytes/sector, 12582912 sectors
vdsk1 at cbus0 chan 0x3: ivec 0x6, 0x7
scsibus2 at vdsk1: 2 targets
sd1 at scsibus2 targ 0 lun 0: <SUN, Virtual Disk, 1.1> SCSI3 0/direct fixed
sd1: 2MB, 512 bytes/sector, 5760 sectors
vnet0 at cbus0 chan 0x4: ivec 0x8, 0x9, address 00:14:4f:fa:57:21
vcons0 at vbus0: ivec 0x111, console
vrtc0 at vbus0
vscsi0 at root
scsibus3 at vscsi0: 256 targets
softraid0 at root
scsibus4 at softraid0: 256 targets
bootpath: /virtual-devices@100,0/channel-devices@200,0/disk@0,0
root on sd0a (31c2d1155bc86970.a) swap on sd0b dump on sd0b

enjoy


Andrew

**Comment by SpinMD** [comment]
Hi,

I can believe Sparc64 is different - but that means the impact will be
wider than certbot. I am not a Python user, but others are.

The problem is not urgent - it is a gentle migration and we have allowed
time for problems.

**Comment by sthen** [comment]
This can be fixed by building py-cryptography with a different compiler. On the OpenBSD architectures which still use GCC, the last GPLv2 version (v4.2.1) is still used by default, which does not support "__builtin_unreachable".

To do this you can add "COMPILER = base-clang ports-gcc" and "COMPILER_LANGS = c" to ports/security/py-cryptography/Makefile and rebuild - I would suggest "pkg_add gcc" first to avoid a huge dependency build if not already present - then "make clean; make repackage; make update".

I have committed a change to OpenBSD -current for this.

**Comment by bmw** [comment]
It sounds like this issue has been resolved and it hasn't seen any updates in almost a year so I'm closing this. If you're still hitting this problem, please comment or open a new issue.
