### ISSUE TITLE
Registration Rate Limit in Staging Using Python ACME Client

### ISSUE THREAD

**Issue by doc987** [certbot/certbot#6024]
I'm trying to use the Python ACME client in the staging environment for testing (using https://acme-staging.api.letsencrypt.org/directory).  However, I'm getting this error:

```acme.messages.Error: urn:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new registration :: too many registrations for this IP: see https://letsencrypt.org/docs/rate-limits/```

It's happening when I call ```acme.client.Client(...).register()```.  Do I have to do something different with this for staging?

**Comment by schoen** [comment]
Hi @doc987 ,

Please ask about this issue over on the Let's Encrypt Community Forum.  Thanks!

https://community.letsencrypt.org/

**Comment by doc987** [comment]
As it turns out, registrations should be saved and reused.  Some details on how to do that can be found here: https://community.letsencrypt.org/t/registration-rate-limit-in-staging-using-python-acme-client/62479

Be cautious if following the example (https://github.com/certbot/certbot/blob/master/acme/examples/example_client.py), as it does not include details on how to save registrations, and is also apparently not current anymore.
