### ISSUE TITLE
Make Certbot issue certs faster

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6027]
I haven't done any measurements myself, but I've been told it takes Certbot 10 - 15 seconds to obtain a certificate and was asked if we can do this more in the <5 second range. This would be particularly useful in large deployments using Certbot.

I suspect this won't be very hard to do because we've spent almost no time trying to optimize Certbot.

The one exception to this might be the Apache and Nginx plugins where we sleep for 3 seconds after setting up the DV challenge. The reason for this is the command you use to ask both webservers to reload their config simply sends a signal to the webserver and immediately returns. This command returning does not mean the server has finished loading their config though and I'm unaware of a reliable way for us to know when this process is complete. As a result, we currently just sleep for a few seconds and afterwards assume the config has been reloaded.

**Comment by Erutan409** [comment]
Just reading this information taught me a lot about the process and is very good to know from a devops standpoint.

**Comment by margana** [comment]
One thing I have found is that issuing a new cert without specifying `--cert-name` gets noticeably slower when you have thousands of certificates already.

Also `renew` takes about a minute per thousand certificates while none of them are due to expire, this is with certs stored on an nfs share.

**Comment by bmw** [comment]
I think we should still do this.
