### ISSUE TITLE
[Feature Request] Print output on how to validate challenges with --debug-challenges

### ISSUE THREAD

**Issue by agowa338** [certbot/certbot#6042]
Can you please add a parameter, that keeps certbot running after the challenge is served in standalone mode?
So that the internal webserver is still running, that would simplify debugging complex network issues.
Currently with "--debug-challenge --test-cert", one is asked to press return *before* the internal webserver is up. And after one pressed return it exites immediately after the challenge is completed or has failed.
Or just add a "--debug-internal-webserver" parameter that starts the internal webserver, serves a debug page, shows it's url and waits until it gets killed.

**Comment by ohemorange** [comment]
This is a great idea, feel free to submit a PR adding this feature! We called our internal webserver "standalone", so the flag should maybe reference that.

**Comment by bmw** [comment]
I think there may have been a misunderstanding here.

When running with `--debug-challenges` using the standalone plugin, the internal webserver is running when asked to press enter to continue. I think the only difference between `--debug-challenges` and the feature implemented in #6063 is the former waits before telling Let's Encrypt to verify the challenge while the latter waits afterwards. Do we need flags for both or am I missing something else?

**Comment by agowa338** [comment]
The difference is, that if you wait before, you don't get the debug output of the internal webserver. This is only outputted to the console if one waits afterwards. Also the Challenge URL is not printed to the console if you wait before it.

**Comment by bmw** [comment]
I think you only get output from the internal webserver in the case Let's Encrypt successfully reaches it. Depending on the issue you're trying to debug, you may not get that.

As for the challenge URL, the only place that's included in the case Let's Encrypt can't reach the internal webserver is in the error output from Let's Encrypt. I'm not confident this URL is included for every error case either.

Sorry for the false start on this and @ohemorange should chime in if she disagrees with my preferred approach here, but I think we should just solve the problem of not giving the user any information about how to validate the challenge themselves when `--debug-challenges` is used. This can include information like the challenge URL and allows the user to try and fix the problem before they start eating into rate limits imposed by the CA.

**Comment by agowa338** [comment]
Yea, that would also solve my problem.
So to sum this up:
- I propose giving more debug output with `--debug-challenges` then.
- This output should include received queries and the corresponding result sent back (like when letsencrypt is responding to the challenge)
- Additional debug information needed: The full Challenge url and the expected token to verify the weberver output (this is useful if one has a reverse proxy, load balance, SNI based request routing, only route .whell-known/acme... towards letsencrypt or has excessive caching infrastructure in between to debug problems there)

For not hitting rate limits, one could simply use the staging server by using the testing parameters. Than you can spam the api more frequently :p

@bmw I would be happy if someone of you could implement this, as I'm not really experienced with the codebase and I currently don't have much time to get used to it.

**Comment by bmw** [comment]
I think the main thing that needs to be added when running with `--debug-challenges` for the HTTP challenge is the full challenge URL and the expected contents like you said.

The same output from the server that is printed when Let's Encrypt is querying the challenge should already be printed, but I'd be fine with adding more `DEBUG` level logging information here if you think something is missing.

While we should definitely do this, we probably won't be able to get to this for a while. @agowa338, if you're interested and available to work on it, I'm happy to answer any questions or give you pointers to what needs to be changed to speed along the process for you.

**Comment by generalbrus** [comment]
I'm happy to take this on

**Comment by generalbrus** [comment]
I've looked into the code and I'm not sure about how to access the expected challenge response. 

I'm assuming it's the `KeyAuthorizationChallengeResponse.key_authorization` attribute, and I have not found a way to access it from an `achall` object directly.
What I'm doing right now is, I generate a new `key_autorization` with `KeyAuthorizationChallenge.validation()`, specifically: `achall.validation(achall.account_key)`, and use that.

Is that correct? And if so, is there a better approach?

**Comment by larabr** [comment]
I'm not 100% confident I've understood what was required here, so before opening a PR I want to double check.
Here's what I've implemented: https://github.com/larabr/certbot/commit/3d3d458065cc147f513c411ca51f10e706ebe455
Basically I add the URI and expected response to the printed error.

**Comment by agowa338** [comment]
> I think there may have been a misunderstanding here.
> 
> When running with `--debug-challenges` using the standalone plugin, the internal webserver is running when asked to press enter to continue. I think the only difference between `--debug-challenges` and the feature implemented in #6063 is the former waits before telling Let's Encrypt to verify the challenge while the latter waits afterwards. Do we need flags for both or am I missing something else?

For the scope of this issue I requested to print the URL that LE is trying to reach on the screen *before* the user presses return to trigger the verification.

Therefore I created this #6063 as a workaround. I was unable to find the correct spot in the code, so I did a workaround and prevented the cleanup after it failed.

**Comment by bmw** [comment]
The relevant place in the code is in the block https://github.com/certbot/certbot/blob/a1313267f033f27133d18e3e7315b5e3947a79bf/certbot/auth_handler.py#L77

This is after we've set up the challenges but before we've sent our responses to the ACME CA stating that we're ready to for it to verify them.

**Comment by larabr** [comment]
I see now, thanks for clarifying!
