### ISSUE TITLE
Same common name for multiple SSL's

### ISSUE THREAD

**Issue by farazhkhan** [certbot/certbot#6043]
I am using CentOS 7.4 and Certbot version 0.22.2

I have around 30 websites configured with Apache on single server and for them when I run command 

> sudo certbot --apache

it asks me for 'Which names would you like to activate HTTPS for?' and then I type in 1,2,......,30 all the number of websites.

All goes fine and it installs SSLs on all websites, but for some reason the common name for each website remains one and that is of the very first website. Is it something what we called the base domain or what? and how can we avoid it and make sure that each website name displaying on browser should also be separate?

**Comment by schoen** [comment]
RFC 2818 (May 2000) says:

>   If a subjectAltName extension of type dNSName is present, that MUST be used as the identity. Otherwise, the (most specific) Common Name field in the Subject field of the certificate MUST be used. Although the use of the Common Name is existing practice, it is deprecated and Certification Authorities are encouraged to use the dNSName instead.

See also https://groups.google.com/a/chromium.org/forum/#!topic/security-dev/IGT2fLJrAeo and https://letsencrypt.org/docs/rate-limits/.
