### ISSUE TITLE
certbot-apache should dump the apachectl -S when it can't renew

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#6045]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Red Hat Enterprise Linux Server release 6.9 (Santiago)
Python 2.7 (redhat scl python27)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto (0.24.0)

## I ran this command and it produced this output:
/root/bin/certbot-auto -q renew --post-hook /root/bin/certbot-renew-hook

FailedChallenges: Failed authorization procedure. site.example.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for tls-sni-01 challenge. Requested whatever.acme.invalid from IP.AD.DR.ESS:443. Received 2 certificate(s), first certificate had names "other.example.com"

## Certbot's behavior differed from what I expected because:
It could have included `apachectl -S` output (which would help debugging)

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

```
FailedChallenges: Failed authorization procedure. site.example.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for tls-sni-01 challenge. Requested whatever.acme.invalid from IP.AD.DR.ESS:443. Received 2 certificate(s), first certificate had names "other.example.com"
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

Fwiw, here's my normal -S output (minus a number of other hosts that aren't implicated by the output from certbot:
```
127.0.0.1:443          is a NameVirtualHost
         default server other.example.com (/etc/httpd/conf.d/001-other-ssl-localhost.conf:1)
         port 443 namevhost site.example.com (/etc/httpd/conf.d/103-site-ssl-localhost.conf:1)
wildcard NameVirtualHosts and _default_ servers:
*:443                  is a NameVirtualHost
         default server other.example.com (/etc/httpd/conf.d/001-other-ssl.conf:1)
         port 443 namevhost site.example.com (/etc/httpd/conf.d/003-site-ssl.conf:1)
         port 443 namevhost site.example.com (/etc/httpd/conf.d/103-site-ssl.conf:1)
*:80                   is a NameVirtualHost
         default server other.example.com (/etc/httpd/conf.d/001-other.conf:1)
         port 80 namevhost site.example.com (/etc/httpd/conf.d/001-site.conf:1)
```

**Comment by jsoref** [comment]
Note:
It could instead suggest `--debug-challenges` which helped me find the bug I was expecting (#6046).

**Comment by ohemorange** [comment]
Hey @jsoref, that's a great idea! Want to submit a PR? Tagging @joohoi so he sees this.

**Comment by joohoi** [comment]
I think this can be closed, as we nor Let's Encrypt have a support for TLS-SNI challenges. The way that the Certbot Apache plugin works since 0.31 is that it configures all the `VirtualHosts` that could answer to the validation domain instead of only one. If you disagree, feel free to comment and we can reopen if needed.
