### ISSUE TITLE
apache certbot configured a challenge to 127.0.0.1:443

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#6046]
## My operating system is (include version):
Red Hat Enterprise Linux Server release 6.9 (Santiago)
Python 2.7 (redhat scl python27)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto (0.24.0)

## I ran this command and it produced this output:
```sh
/root/bin/certbot-auto --no-self-upgrade renew --debug-challenges
```
```sh
apachectl -S
Warning: DocumentRoot [/var/lib/letsencrypt/tls_sni_01_page/] does not exist
VirtualHost configuration:
...
127.0.0.1:443          is a NameVirtualHost
         port 443 namevhost site.example.com (/etc/httpd/conf.d/103-site-ssl-localhost.conf:1)
         port 443 namevhost XXXX.YYYY.acme.invalid (/etc/httpd/conf.d/le_tls_sni_01_cert_challenge.conf:2)
wildcard NameVirtualHosts and _default_ servers:
*:443                  is a NameVirtualHost
         default server other.example.com (/etc/httpd/conf.d/001-other-ssl.conf:1)
         port 443 namevhost site.example.com (/etc/httpd/conf.d/003-site-ssl.conf:1)
         port 443 namevhost site.example.com (/etc/httpd/conf.d/103-site-ssl.conf:1)
*:80                   is a NameVirtualHost
         default server other.example.com (/etc/httpd/conf.d/001-other.conf:1)
         port 80 namevhost site.example.com (/etc/httpd/conf.d/001-site.conf:1)
```
```sh
cat /etc/httpd/conf.d/le_tls_sni_01_cert_challenge.conf
<IfModule mod_ssl.c>
<VirtualHost 127.0.0.1:443>
    ServerName XXXX.YYYY.acme.invalid
    UseCanonicalName on
    SSLStrictSNIVHostCheck on

    LimitRequestBody 1048576

    Include /etc/letsencrypt/options-ssl-apache.conf
    SSLCertificateFile /var/lib/letsencrypt/ZZZZ.crt
    SSLCertificateKeyFile /var/lib/letsencrypt/ZZZZ.pem

    DocumentRoot /var/lib/letsencrypt/tls_sni_01_page/
</VirtualHost>

</IfModule>
```

FailedChallenges: Failed authorization procedure. site.example.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for tls-sni-01 challenge. Requested whatever.acme.invalid from IP.AD.DR.ESS:443. Received 2 certificate(s), first certificate had names "other.example.com"

## Certbot's behavior differed from what I expected because:
It configured a certificate challenge on 127.0.0.1!

Essentially, the domain is configured on multiple IP addresses (127.0.0.1 and a hostname).
certbot should either listen on `*` or all ips listed for the servername (in this case that's only 127.0.0.1) + all ips that the local computer resolves as `hostname servername` (in this case, this is the path that leads to a routable ip).

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

```
FailedChallenges: Failed authorization procedure. site.example.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for tls-sni-01 challenge. Requested whatever.acme.invalid from IP.AD.DR.ESS:443. Received 2 certificate(s), first certificate had names "other.example.com"
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

Fwiw, here's my normal -S output (minus a number of other hosts that aren't implicated by the output from certbot:
```
127.0.0.1:443          is a NameVirtualHost
         default server other.example.com (/etc/httpd/conf.d/001-other-ssl-localhost.conf:1)
         port 443 namevhost site.example.com (/etc/httpd/conf.d/103-site-ssl-localhost.conf:1)
wildcard NameVirtualHosts and _default_ servers:
*:443                  is a NameVirtualHost
         default server other.example.com (/etc/httpd/conf.d/001-other-ssl.conf:1)
         port 443 namevhost site.example.com (/etc/httpd/conf.d/003-site-ssl.conf:1)
         port 443 namevhost site.example.com (/etc/httpd/conf.d/103-site-ssl.conf:1)
*:80                   is a NameVirtualHost
         default server other.example.com (/etc/httpd/conf.d/001-other.conf:1)
         port 80 namevhost site.example.com (/etc/httpd/conf.d/001-site.conf:1)
```

**Comment by schoen** [comment]
@joohoi , could you look into this?

**Comment by ohemorange** [comment]
@joohoi, could you follow up? I don't have the context for why we added this Apache behavior.

**Comment by joohoi** [comment]
Certbot runs into problems when selecting which Apache VirtualHost to use as a base for the validation because currently only one of the VirtualHosts matching the requested domain name is selected. For reference, the selection is handled here: https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/configurator.py#L589-L648

The (only) proper fix here would be to configure _all_ the matching VirtualHosts to be able to answer the HTTP challenge. Albeit localhost IP being a special case, it still doesn't mean that it's a wrong one to handle the challenge even in complex multi-VirtualHost configurations. There might be reverse proxy scheme that's effectively serving the requests from public internet by upstreaming the localhost ip, and the other matching VirtualHosts could be used to serve the internal network for example.

That being said, the current selection method is flawed, as it practically just configures the [first matching vhost](https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/configurator.py#L634-L636) for the validation.

This is related to #2560 and #3358

**Comment by jsoref** [comment]
@joohoi : Agreed on the localhost part -- I actually use things like that for a different protocol...

The simplest path I found is listening to "all" virtualhosts (there's a set guarding it, so it isn't horrible). Apache disambiguates by servername, so for SNI which we're doing, if we happen to do "all hosts apache has configured" instead of just "all hosts that we think are related to the hostname for which we're trying to prove", I don't think there's any real harm.

(My initial attempt w/ `*` didn't actually work, I think `*:*` probably would have worked, but I'm happy to go w/ something that's more "correct".)

One thing that bothers me is:
`ApacheConfigurator.choose_vhosts`
With a name like that, one would expect it to generally be willing to return multiple hosts...

But, it doesn't.
On average it calls `choose_vhost` and just wraps that single item in a list...
I'm pretty sure that could be fixed, but I decided I didn't need it for what I'm doing and I didn't want to jump through all the pieces (debugging this on a renew challenge limited budget was painful).

**Comment by joohoi** [comment]
> One thing that bothers me is:
ApacheConfigurator.choose_vhosts
With a name like that, one would expect it to generally be willing to return multiple hosts...

This is of my doing, and I apoligize for the badly named method. Currently the only case where we need to return multiple vhosts per domain inside Apache configurator is the case where we should configure multiple `VirtualHosts` if user has a wildcard certificate. This might need to change in the future, as noted in this issue and its comments. In addition to creating the TLS configuration for multiple VirtualHosts we indeed might want to configure multiple VirtualHosts to answer the ACME HTTP challenge.

**Comment by joohoi** [comment]
I think this can be closed, as we nor Let's Encrypt have a support for TLS-SNI challenges. The way that the Certbot Apache plugin works since 0.31 is that it configures all the `VirtualHost`s that could answer to the validation domain instead of only one. If you disagree, feel free to comment and we can reopen if needed.
