### ISSUE TITLE
Tweak output to not trigger markdown heading status

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#6050]
We have a lot of horizontal lines of dashes in the Certbot output, e.g.

```
Which names would you like to activate HTTPS for?
-------------------------------------------------------------------------------
1: example.com
2: www.example.com
-------------------------------------------------------------------------------
```

Unfortunately, Markdown interprets any text above one of these lines as a heading, leading to distracting and weird formatting when someone pastes it into the forum:

https://community.letsencrypt.org/t/certbot-apache-succeeded-now-site-times-out/63168/3

Arguably they should wrap things in triple-backticks, but this happens quite a lot: People who need help on the forum often don't take time to learn about Markdown. It would be nice to make a small tweak so that formatting just works correctly. Unfortunately, lines of underscores, plus signs, colons, or equal signs all have the same effect. One simple tweak that works is inserting a space (or multiple spaces) in the line of hyphens:

    - -------------------------------------------------------------------------------

or

    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by bmw** [comment]
Seems reasonable to me.

I personally have a preference for:
```
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```
but I'm open to other approaches.

The fix for this would go into `certbot/display/util.py`.

**Comment by sydneyli** [comment]
mind if I take this for a short demo at an open-source workshop next friday?

**Comment by bmw** [comment]
Go for it!

**Comment by jobst** [comment]
So will this happen when using underscores as well?

  i.e. ____________________________________________________________

because "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -" looks crap in Mutt.

Just asking ...

**Comment by jsha** [comment]
Yep, I tried a few different alternate characters, and all of them produced the Markdown heading behavior. :-(
