### ISSUE TITLE
Allow tuning of min_sleep and max_rounds in AuthHandler

### ISSUE THREAD

**Issue by ezekiel** [certbot/certbot#6051]
This is a feature request.

It would be useful in various situations for the AuthHandler `min_sleep` and `max_rounds` values to be tune-able with CLI flags or INI-file options.

**Comment by bmw** [comment]
Certainly the vast majority of Certbot users wouldn't use this feature.

Can you tell me a little more about why this would be useful to you?

**Comment by ezekiel** [comment]
Second thought, my original scenario has been fixed upstream and is very unlikely to come up again any time soon. Thanks for the consideration, I'll come back again if this seems like it'd be useful more often.
