### ISSUE TITLE
Improvement request for NGINX plugin: In-line replacements for .conf files

### ISSUE THREAD

**Issue by kristian** [certbot/certbot#6055]
I recently used the certbot NGINX plugin & webroot authenticator in order to protect my public sites (which worked like a charm btw. so huge Kudos!).

The only improvement request I would have is, that certbot automatically did motifications to my NGINX site configuration files. As I have quite a few of those files, I‘d like to keep them clean, by e.g. having the `listen` directive as a first statement in the server block. After certbot changed the configuration, the `listen 80;` lines have been removed and the new `listen 443` line was appended to the bottom of the server block. I manually had to move it to the top again.

Therefore my suggestion would be, in case a line is removed and replaced by another directive, would it be possible to replace it in the original location of the removed line? That would keep also large configurations more clean! Thanks.

**Comment by bmw** [comment]
We can look into trying to do something like this, but to be honest, we probably won't get to it for a while. If you or someone else would like to take a crack at fixing it, feel free.

The good news though is now that you have the initial setup, if you renew your certificate with `certbot renew` (which is the recommended way to do so), we won't modify your config file again.
