### ISSUE TITLE
certbot renew --dry-run failed case talks about certs that don't exist

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#6057]
## My operating system is (include version):
RHEL6.9

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
```
certbot-auto renew --debug --dry-run --preferred-challenges=tls-sni-01
...
Attempting to renew cert (a.example.com) from /etc/letsencrypt/renewal/a.example.com.conf produced an unexpected error: Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.. Skipping.
...
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/a.example.com/fullchain.pem (failure)
  /etc/letsencrypt/live/b.example.com/fullchain.pem (failure)
  /etc/letsencrypt/live/c.example.com/fullchain.pem (failure)
  /etc/letsencrypt/live/d.example.com/fullchain.pem (failure)
  /etc/letsencrypt/live/e.example.com/fullchain.pem (failure)
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates above have not been saved.)
```
## Certbot's behavior differed from what I expected because:

As there were 0 certificates issued, it should not tell me that the test certificates above were not saved, obviously they weren't saved, they weren't issued!

**Comment by joohoi** [comment]
The active renewal configuration files should be in `/etc/letsencrypt/renewal/`. These are probably remnants from your previous runs.

**Comment by jsoref** [comment]
The reason the renewals failed is that `--dry-run` switched me to **staging** and **staging** didn't like `tls-sni-01`.

There's nothing wrong with **staging** refusing to issue certificates. What I'm complaining is that it really shouldn't say `(The test certificates above have not been saved.)` when in fact there were no files that it would have modified...
