### ISSUE TITLE
certbot crash resulted in permanently broken state

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#6058]
# My operating system is (include version):
RHEL6.9

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto
+ some local changes
+ some live debugging (using pdb)

## I ran this command and it produced this output:
```
certbot renew
...
Attempting to renew cert (a.example.com) from /etc/letsencrypt/renewal/a.example.com.conf produced an unexpected error: Attempting to overwrite challenge file - /etc/httpd/conf/httpd.conf. Skipping.
```

## Certbot's behavior differed from what I expected because:
1. I'm pretty sure it spent a "renewal attempt" instead of recognizing it couldn't go forward and bailing early
2. It didn't provide any way for me to fix my condition
3. It didn't usefully explain what went wrong

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
```/etc/httpd/conf/httpd.conf
...
Include /etc/httpd/conf.d/le_tls_sni_01_cert_challenge.conf
^D
```

**Comment by joohoi** [comment]
Thanks for the report! This is described in detail in issue #5251 

I'm closing this issue as a duplicate (now that we have a link back from the issue above).
