### ISSUE TITLE
documentation: section about renewing structured below "Changing Certificates Domains"

### ISSUE THREAD

**Issue by osirisinferi** [certbot/certbot#6065]
Hi guys,

I know this is a website thingy, but the code for `using.html` is within this repo, so I'm putting the issue here too.

Something seems a little bit strange: the help text about renewing a certificate is an item structured *below* "Changing a Certificate’s Domains" in the documentation.

[In January of 2017](https://github.com/certbot/certbot/commit/bf7ce3130298016bdeb970e7c8e04cf319099969#diff-5f059e53687997d121c03d63d11f103bL259), the section "Renewing certificates" was demoted a level below the "head" section "Managing certificates". At the time, "Changing a Certificate’s Domains" was a section with the same level as renewing.

[But in March 2017](https://github.com/certbot/certbot/commit/df8b374916d2e76b2377def98a6ffcdd2a09b112), the "Changing a Certificate's Domains" section got leveled up.

From that moment on, if people are to search for "Renewing", they have to explicitly click on "Changing a Certificate's Domains" to see the renewing section in the menu.

The change in level of the heading seems unrelated to any other change. In the [PR itself](https://github.com/certbot/certbot/pull/4948) there's no mentioning of this.

Perhaps it was by accident and it slipped through?

**Comment by schoen** [comment]
Hi @osirisinferi,

I'm not sure whether this was intentional or not; perhaps we could ask @SwartzCr and @pconrad-fb.

**Comment by pconrad-fb** [comment]
There's a big doc restructuring process happening right now, which should take care of this type of oddity.

**Comment by joohoi** [comment]
This seems to still be true.
