### ISSUE TITLE
Treat warnings as failures during testing

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6080]
We should use something like https://docs.pytest.org/en/latest/warnings.html to have warnings treated as errors when running our tests with pytest so we can fix anything like deprecation warnings before it's a problem.

**Comment by bmw** [comment]
This should be relatively easy. You just need to add the command line argument `-Werror` to `pytest` and fix any errors that occur. I'm bumping the priority of this because it what have caught the need for #6184 automatically which I just happened to notice before the release.

**Comment by bmw** [comment]
The start of my work on this is in the [warnings-are-errors](https://github.com/certbot/certbot/tree/warnings-are-errors) branch. I was using the branch [test-everything-warnings](https://github.com/certbot/certbot/tree/test-everything-warnings) to see what errors caused failures running a full set of tests.

I haven't had a chance to work on this in a while, but if I remember correctly, there were some warnings occurring due to code inside the `requests` package that had yet to be fixed upstream. I was trying to figure out how to ignore these warnings and struggling, however, this issue might be resolved now and fixable by upgrading the version of `requests` pinned in `certbot-auto`.

Let me know if there's any questions about the work I've done so far.

**Comment by adferrand** [comment]
In fact everything you can pass to the -W are warning filters, as accepted by `warnings.simplefilter`. The warning filter specification is here: https://docs.python.org/3/library/warnings.html#warning-filter

Basically, you can filter warnings on their message, their classe, or the module from where they have been issued.

With this, I think you can do everything you want. In particular, considering all warnings as errors, except a declared list of acceptable warnings.

**Comment by adferrand** [comment]
Also, these `-W` directives can be passed through the env variable `PYTEST_ADDOPTS` to leverage them more dynamically. With the help of `tox`, a script could generate the env variable during the setup of specific `env` targets, certainly by reading some persistent configuration that would be committed in the certbot repository.

**Comment by ohemorange** [comment]
Thanks @adferrand! Actually, I think we can do something even more simple here: just treat DeprecationErrors as warning.

**Comment by adferrand** [comment]
Seriously, a warning class that contains `DeprecationWarning` in its name is not a subclass of `DeprecationWarning`? That would almost worth a PR for the upstream ^^

I also commented your PR about warnings generated during teardown processes on Windows to delete temporary directories. Theses warning need also to be treated specifically.

**Comment by ohemorange** [comment]
Upgrading `requests` does not help. Luckily, it is possible to granularly quash warnings using decorators.
