### ISSUE TITLE
`certbot delete` can result in a malformed Nginx config

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#6094]
Steps to reproduce:

1. `certbot --nginx -d example.com`
2. `certbot delete --cert-name example.com`.
3. `service nginx reload` (fails)

Expected result:

Certbot errors out at (2) and tells you to remove the certificate from config files before deleting it.

This is a particularly frustrating outcome because in most cases Certbot allows you to get by without editing server config files, but in this case your server will be broken until you edit the config files. And if you've only ever edited SSL/TLS configuration with Certbot, you may not know what you need to fix.

**Comment by ohemorange** [comment]
This is a little complicated -- to test if they need to be removed, we'd have to move or rename the certs, check if there's an installer for the certs and if so run reload the server to test if that breaks things, and then delete for real.

What about instead, we print a message on delete saying "delete certs from related config files"? Do we already do that?

**Comment by jsha** [comment]
I don't think we print a message like that; I think I probably would have missed it even if we did.

I realize it's hard to do this 100% right, but what if we try best-effort: If the installer was apache or nginx, do a grep of the relevant files for the filename being deleted, and fail the delete if the filename is still in those files. Or, a little fancier: Use the relevant parser to load the configs and fail only if the filename is present in a directive (this would get us two advantages: includes from different directories would work reliably, and commented-out ssl_certificate directives would be correctly ignored).

**Comment by ohemorange** [comment]
I think it'd probably be simpler and more accurate to reality to rename the files then just reload the server and see if that fails, no?

**Comment by jsha** [comment]
yeah, you're right. :-D

**Comment by ohemorange** [comment]
To sum up:

When `delete` is called, before deleting, rename the relevant files. Reload the relevant server. If that fails, print a message telling the user to first remove the files from the config because deleting them will break the server. Then, un-rename the files and re-reload the server and exit.

**Comment by jsha** [comment]
I'd still like to see this fixed. I'm surprised it doesn't come up more often as a reported problem!

**Comment by ohemorange** [comment]
I suspect `delete` has few users.

**Comment by jsha** [comment]
Given I'm the only one to have reported this in 2 years I'm okay closing it.
