### ISSUE TITLE
Spurious error parsing ssl.conf

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#6095]
When running `certbot --nginx -d jacob.hoffman-andrews.com -d hoffman-andrews.com -vv`, I got this error in the logs:

```
2018-06-11 22:35:28,771:DEBUG:certbot_nginx.parser:Could not parse file: /etc/nginx/conf.d/ssl.conf due to Expected "#" (at char 0), (line:1, col:1)
```

`ssl.conf` is empty (zero bytes)

The error was non fatal but we should tidy it up.

**Comment by mozebdi** [comment]
Hi there!
I'm a computer science student at University of Michigan, and am looking to contribute to an open-source project as part of my software engineering course.


I've used CertBot before and am familiar with Python - I'd love to tackle this issue, as it seems like a reasonably simple problem to debug. I'm also a big fan of the EFF and would love to do my part to help!

**Comment by jsha** [comment]
Awesome, welcome to the project! This issue is from a while ago, so I think the first step would be to see if you can reproduce the error locally. Developer setup instructions are at https://certbot.eff.org/docs/contributing.html. Feel free to [ask for help on Mattermost](https://certbot.eff.org/docs/contributing.html#asking-for-help).

**Comment by mozebdi** [comment]
Hey there! I figured out a workaround to this issue, and made a PR: https://github.com/certbot/certbot/pull/7636
