### ISSUE TITLE
Don't use strictly greater than requirements

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6098]
Now that we've broken lockstep, we need a way to specify that Certbot or a plugin relies on unreleased changes in acme or Certbot.

Suppose the latest released version is 0.24.0 and a package relies on unreleased changes in acme. To do this, we've been using version requirements like `acme>0.24.0`. This is because acme `0.25.0.dev0` satisfies this requirement and assuming we don't release `0.24.1` (in which case we'd have to change the requirement to `acme>0.24.1`), the only packages that satisfy this are `acme>=0.25.0`.

This is unconventional though, has caused confusion with multiple package maintainers, and could cause issues in the extremely unlikely event we release a bug fix release for `0.24` after `0.25.0` comes out.

@erikrose, do you have any thoughts on this? Is this something you think is worth changing and any suggestions on how to do it?

**Comment by erikrose** [comment]
I've never seen anyone even try to solve this problem before. Isn't the usual approach just to wait until a new certbot version is released and only then to release the dependent plugin version? Are people using unreleased versions of plugins in great number?

**Comment by erikrose** [comment]
If there is a pressing need to solve this problem—for instance, I could see setuptools getting grumpy during development while scanning for entrypoints—what about having the plugin require `acme>=0.25.0` and just making sure to bump acme's version number on master as soon as we start adding features rather than bugfixes to it?

**Comment by bmw** [comment]
The issue here is only during our development. We're still releasing every Certbot component at once and sometimes one of our plugins is requiring features that have only landed in `master` and haven't been released yet.

> what about having the plugin require acme>=0.25.0 and just making sure to bump acme's version number on master as soon as we start adding features rather than bugfixes to it?

What we currently do is as part of the release process for releasing version X, we bump the version number for every package in `master` to X+1.dev0. So when doing the release for 0.24.0, everything becomes 0.25.0.dev0.

We could remove the `.dev0` and just always have the next version without any indication that it's a dev version. Only potential downsides is sometimes people show up with logs where Certbot is reporting it's `X.dev0` which makes it clear they were running from our tree rather than a stable and tested release.

**Comment by elyscape** [comment]
It looks like pip will properly handle `acme >= 0.25.0.dev0`. Then, as part of the release step, any requirements that specify `.dev0` can have that removed.

**Comment by erikrose** [comment]
Sounds great to me, @elyscape!

**Comment by bmw** [comment]
This has been fixed.
