### ISSUE TITLE
Revert TLS-ALPN code in master

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6101]
See #6100.

**Comment by bmw** [comment]
I think what we should do here is leave a very basic version of the challenge type so our acme library can still parse it for use in chisel, but remove the rest of the code that was added in #5894.

cc @rolandshoemaker

**Comment by rolandshoemaker** [comment]
Looks like there was already a complete revert of this code. I should be in the office tomorrow, if you're around we can discuss how to best resolve this.

**Comment by bmw** [comment]
Fixed in #6144.
