### ISSUE TITLE
--manual --preferred-challenges=dns certonly cannot seem to validate multiple domains

### ISSUE THREAD

**Issue by jfinkhaeuser** [certbot/certbot#6105]
## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
From github.

## I ran this command and it produced this output:
```bash
$ sudo ./certbot-auto -d first - d second -d third -d fourth --manual --preferred-challenges=dns certonly
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for first
dns-01 challenge for second
dns-01 challenge for third
dns-01 challenge for fourth

-------------------------------------------------------------------------------
NOTE: The IP of this machine will be publicly logged as having requested this
certificate. If you're running certbot in manual mode on a machine that is not
your server, please ensure you're okay with that.

Are you OK with your IP being logged?
-------------------------------------------------------------------------------
(Y)es/(N)o: yes

-------------------------------------------------------------------------------
Please deploy a DNS TXT record under the name
_acme-challenge.first with the following value:

<snip>

Before continuing, verify the record is deployed.
(repeat three times)
Press Enter to Continue
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. first (dns-01): urn:acme:error:dns :: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.first, (repeat)
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: first
   Type:   None
   Detail: DNS problem: NXDOMAIN looking up TXT for
   _acme-challenge.first
(repeat)
```

## Certbot's behavior differed from what I expected because:
One out of four deployed TXT records can't be found by certbot, but dig finds all four. The primary DNS contains all four records, the secondary DNSes refer to the primary. Certbot randomly fails all but one of the challenges.

**Comment by bmw** [comment]
Certbot isn't the one that checks your DNS records. Let's Encrypt's CA software does this. Certbot is just the client that tells you how to set them up.

I recommend posting at https://community.letsencrypt.org. There's a large community of people there who will be able to help you.

**Comment by jfinkhaeuser** [comment]
Ok, fair enough on who does what. It's not clear when you just use the software, so thanks for the pointer!

However, a _community_ page isn't really helpful for reporting bugs. So I think I'll skip that, and not use Let's Encrypt.
