### ISSUE TITLE
Upgrade 0.25.1 fails

### ISSUE THREAD

**Issue by AleksCee** [certbot/certbot#6107]
## My operating system is (include version):
Ubuntu 16.04.4 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:

./letsencrypt-auto --version

Upgrading certbot-auto 0.24.0 to 0.25.1...
Couldn't download https://raw.githubusercontent.com/certbot/certbot/v0.25.1/letsencrypt-auto-source/letsencrypt-auto. HTTP Error 404: Not Found

## Certbot's behavior differed from what I expected because:

Download and Upgrade to the latest version.

**Comment by ajoliveau** [comment]
I was just about to post an issue as well.
I have the issue on all my servers that are running certbot-auto (two servers running Debian 8).

It fails to upgrade from 0.24.0 and from 0.25.1.

When doing a new install of certbot-auto, it's does the same thing.
It tries (and fails) to update itself on every command, including ./certbot-auto renew

**Comment by bmw** [comment]
Sorry!

This should be fixed now.
