### ISSUE TITLE
Certbot cannot detect Nginx plugin even though it is installed.

### ISSUE THREAD

**Issue by bbayer** [certbot/certbot#6114]
Certbot cannot detect Nginx plugin 

## My operating system is (include version):
* Ubuntu 16.04.4 LTS (GNU/Linux 4.15.13-x86_64-linode106 x86_64)
* nginx version: nginx/1.10.3 (Ubuntu)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

> sudo add-apt-repository ppa:certbot/certbot
> sudo apt-get update
> sudo apt-get install python-certbot-nginx
## I ran this command and it produced this output:
> $ certbot --nginx -d domain.com -d www.domain.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
The requested nginx plugin does not appear to be installed
> $ dpkg -L python-certbot-nginx
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/python-certbot-nginx
/usr/share/doc/python-certbot-nginx/changelog.Debian.gz
/usr/share/doc/python-certbot-nginx/copyright

## Certbot's behavior differed from what I expected because:
I cannot get certificates since Certbot claims that there is no cerbot-nginx plugin installed.

## Here is a Certbot log showing the issue (if available):
2018-06-14 20:41:35,350:DEBUG:certbot.main:certbot version: 0.17.0
2018-06-14 20:41:35,350:DEBUG:certbot.main:Arguments: ['--nginx', '-d', 'domain.com', '-d', 'www.domain.com']
2018-06-14 20:41:35,350:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2018-06-14 20:41:35,360:DEBUG:certbot.log:Root logging level set at 20
2018-06-14 20:41:35,361:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2018-06-14 20:41:35,361:DEBUG:certbot.plugins.selection:Requested authenticator nginx and installer nginx
2018-06-14 20:41:35,361:DEBUG:certbot.plugins.selection:No candidate plugin
2018-06-14 20:41:35,361:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
None

**Comment by bmw** [comment]
I suspect that Certbot in your path isn't the one installed from the PPA. What's the output of `command -v certbot`? Is it possible it's also been installed from `pip`?

**Comment by bbayer** [comment]
I think that is the issue.

> $ command -v certbot
/usr/local/bin/certbot
> pip list|grep certbot
certbot (0.17.0)

I got it uninstalled via pip remove, purge the package and reinstalled again. After that here is result
> $ certbot
bash: /usr/local/bin/certbot: No such file or directory

**Comment by bmw** [comment]
I think you still have files left over from your Certbot installation from `pip`, otherwise, it wouldn't be looking in `/usr/local`.

What's `command -v certbot` now? What's the content of those files? What's the output of `python3 -c 'import certbot; print(certbot.__file__)`?

**Comment by bmw** [comment]
Since I haven't heard back in a few days and [installing Certbot from pip is not supported](https://certbot.eff.org/docs/install.html#installing-from-source), I'm closing this issue.

If you're still having trouble, I recommend posting at https://community.letsencrypt.org where there's a large community of people able to help you.

**Comment by prem911** [comment]
> I think you still have files left over from your Certbot installation from `pip`, otherwise, it wouldn't be looking in `/usr/local`.
> 
> What's `command -v certbot` now? What's the content of that file? What's the output of `python3 -c 'import certbot; print(certbot.__file__)'`?

Facing the same.. result of the py command is
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'certbot'

**Comment by bmw** [comment]
@prem911, if you're still having this problem, please open a new issue and fill out the issue template.

**Comment by prem911** [comment]
> @prem911, if you're still having this problem, please open a new issue and fill out the issue template.

I had to install certbot and a certbot plugin and had messed up the steps. Its working now. No defect, everyone is happy :)

**Comment by devqx** [comment]
Running apt-get purge python-certbot certbot && apt-get install certbot python-certbot-nginx worked for me.

**Comment by Ikdemm** [comment]
For me, I just needed to install the missing plugin `python-certbot-nginx` through `apt install python-certbot-nginx`

**Comment by qwertynik** [comment]
Thanks @devqx @Ikdemm. 
In some cases, or perhaps all, `python-certbot-nginx` package maybe missing. This should work: `python3-certbot-nginx`

**Comment by MahbbRah** [comment]
> Thanks @devqx @Ikdemm. In some cases, or perhaps all, `python-certbot-nginx` package maybe missing. This should work: `python3-certbot-nginx`

that worked for me!
