### ISSUE TITLE
socket-related parameters to the listen directive should not be copied over for an already used address:port pair

### ISSUE THREAD

**Issue by galiovsky** [certbot/certbot#6118]
CentOS 7.5, certbot 0.24.0 from epel, NGINX plugin.

http-01 challenge (for a renew) failed, the modified nginx.conf resulted in a `nginx: [emerg] duplicate listen options for` error.

The original `listen` directive for port 80 had the `deferred` parameter set and this was copied over to the `listen` directive inserted by `certbot-nginx`. The `deferred` parameter can be, similarly to the `ipv6only` parameter, only specified once for a given address:port pair.

There's a whole bunch of `listen` directive parameters like this, see https://nginx.org/en/docs/http/ngx_http_core_module.html#listen. I see there's a "blacklist" in `certbot_nginx/parser.py` that (optionally) takes care of the `default_server` and `ipv6_only` parameters. I'm not aware of all the contexts in which a new server block for an already used address:port pair needs to be created by certbot-nginx, but for temporary server blocks for challenge response serving, perhaps ignoring all the listen parameters altogether, apart from the address:port pair, could be an option? (Just a speculation on my part, perhaps shortsighted...)

**Comment by joohoi** [comment]
Thanks for opening this issue! Extending the current blacklisting behavior of `ipv6_only` for the other directives with similar behavior looks like the way ahead here.

**Comment by Dreamsorcerer** [comment]
Added a pull request that adds all the options to an exclude. It should also be a little more maintainable and efficient than an ever growing list of if statements.
