### ISSUE TITLE
postfix plugin: be more conservative about changing ciphers

### ISSUE THREAD

**Issue by sydneyli** [certbot/certbot#6122]
Until there's data on how much excluding certain ciphers may impact deliverability, i'm hesitant to exclude certain ciphers by default (or at all), although we may want to disable the anonymous ciphers.

This requires a bit more research, but we should at least disable the default ciphersuite setting for now, and re-introduce it once we have more data.

**Comment by bmw** [comment]
We're currently not planning on releasing the Postfix plugin (there just isn't the demand/need for it) so I'm closing this for now.
