### ISSUE TITLE
DNS-01 Challenge Failure of SAN certificate *.xyz.com,xyz.com of the same top domain

### ISSUE THREAD

**Issue by XiaoSK** [certbot/certbot#6126]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
CentOS 7

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto yum pip

## I ran this command and it produced this output:
`./certbot-auto certonly -d *.xyz.com,xyz.com --manual --preferred-challenges dns --server https://acme-v02.api.letsencrypt.org/directory`

```
Please deploy a DNS TXT record under the name
_acme-challenge.xyz.com with the following value:

LyH9bF8fAy7usfhYwXik80id_Fasurl4XUBzRUHy22w

Before continuing, verify the record is deployed.
-------------------------------------------------------------------------------
Press Enter to Continue

-------------------------------------------------------------------------------
Please deploy a DNS TXT record under the name
_acme-challenge.xyz.com with the following value:

9jVY5u4bcpoMpWahqwh9RhAK0gh3ZxJZ1gaEpVLVa_0

Before continuing, verify the record is deployed.
-------------------------------------------------------------------------------
Press Enter to Continue
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. xyz.com (dns-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect TXT record "LyH9bF8fAy7usfhYwXik80id_Fasurl4XUBzRUHy22w" found at _acme-challenge.xyz.com
```

## Certbot's behavior differed from what I expected because:
The DNS records need to be set for *.xyz.com and xyz.com are the same one and cann't be verified at the same time.
The certbot of previous version verifies the DNS record one by one for each domain. But the latest version verifies at the same time after all domain DNS records set. This can't be done in the situation.
The certbot had better verify the domains one by one or check if it is the same top domain that don't need to be set twice.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
-

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
-

**Comment by Jeroen52** [comment]
Issuing wildcard certs work for me on both CentOS 6 and CentOS 7.

Are you sure that you added both TXT records seperately and that they are both live?

**Comment by talyguryn** [comment]
You should add both records

Check out #5719

**Comment by XiaoSK** [comment]
Oh, got it. My bad.
