### ISSUE TITLE
Don't allow special characters in lineage name

### ISSUE THREAD

**Issue by tomwassenberg** [certbot/certbot#6127]
## My operating system is (include version):
Ubuntu 16.04.4

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
PPA, certbot 0.22.2

## I ran this command and it produced this output:
```bash
root@tom-vps:/etc/letsencrypt# certbot certonly --staging --webroot -d test.tomwassenberg.nl --webroot-path /var/www/acme-challenges/ --cert-name "/example"
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for test.tomwassenberg.nl
Using the webroot path /var/www/acme-challenges for all unmatched domains.
Waiting for verification...
Cleaning up challenges

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/example/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/example/privkey.pem
   Your cert will expire on 2018-09-14. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
```

## Certbot's behavior differed from what I expected because:
Certbot should halt and return an error message stating that you can't use a slash in a lineage name. Instead, it continues normally and saves the regular output in `/etc/letsencrypt/{archive,live}/example`. However, when saving the renewal configuration, it becomes apparent the lineage name is parsed as a path because it is saved on the actual path `/example.conf`, so on the root of the filesystem. This shouldn't happen.

Also other permutations of names with special characters, like names with slashes between regular characters, or names starting with a hyphen, cause unexpected behavior.

**Comment by ohemorange** [comment]
Thanks for reporting!

**Comment by troy-lamerton** [comment]
I'm trying to fix this by raising an error in the function `get_certnames` inside `cert_manager.py`.

"certname" appears in several places though, so I'm not sure if this will cover all cases where the user has input the certname.

**Comment by ohemorange** [comment]
Since we're not actually seeing people run into this, moving it to wishlist.

**Comment by bmw** [comment]
Erica said she's not planning on implementing this issue, but wanted to make herself responsible for tracking it to make sure it gets done. If someone else wants to work on this, please do so!

**Comment by osirisinferi** [comment]
Should we use a character whitelist or blacklist?

One might think [a-zA-Z0-9_-] will suffice, but I'm sure others might not think so :stuck_out_tongue: I'm sure we don't want *all* characters minus the slashes/hyphen as a possible char, but perhaps we'd like to allow other scripts like Cyrillic or Greek or allow Unicode chars.

**Comment by ohemorange** [comment]
My ideal would be to figure out and implement the behavior that most closely matches the things accepted in practice. That is, test the system and see if other scripts work perfectly fine, what characters break things, etc. Is it literally only slashes and hyphen that break things in practice? What's causing things to break; is it NGINX's code or something about how Certbot interacts with filenames?
