### ISSUE TITLE
[Fri Jun 22 11:49:55.256356 2018] [:error] [pid 27985] mod_wsgi (pid=27985): Target WSGI script '/opt/graphite/conf/graphite.wsgi' cannot be loaded as Python module

### ISSUE THREAD

**Issue by m2cci-KGY** [certbot/certbot#6140]
[Fri Jun 22 11:49:55.236190 2018] [:error] [pid 27983] ImproperlyConfigured: The SECRET_KEY setting must not be empty.
[Fri Jun 22 11:49:55.256356 2018] [:error] [pid 27985] mod_wsgi (pid=27985): Target WSGI script '/opt/graphite/conf/graphite.wsgi' cannot be loaded as Python module.
[Fri Jun 22 11:49:55.256464 2018] [:error] [pid 27985] mod_wsgi (pid=27985): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Fri Jun 22 11:49:55.256515 2018] [:error] [pid 27985] Traceback (most recent call last):
[Fri Jun 22 11:49:55.256553 2018] [:error] [pid 27985]   File "/opt/graphite/conf/graphite.wsgi", line 7, in <module>
[Fri Jun 22 11:49:55.256687 2018] [:error] [pid 27985]     application = django.core.handlers.wsgi.WSGIHandler()
[Fri Jun 22 11:49:55.256711 2018] [:error] [pid 27985]   File "/usr/lib/python2.7/site-packages/Django-1.11.13-py2.7.egg/django/core/handlers/wsgi.py", line 151, in __init__
[Fri Jun 22 11:49:55.256875 2018] [:error] [pid 27985]     self.load_middleware()
[Fri Jun 22 11:49:55.256898 2018] [:error] [pid 27985]   File "/usr/lib/python2.7/site-packages/Django-1.11.13-py2.7.egg/django/core/handlers/base.py", line 48, in load_middleware
[Fri Jun 22 11:49:55.257077 2018] [:error] [pid 27985]     if settings.MIDDLEWARE is None:
[Fri Jun 22 11:49:55.257106 2018] [:error] [pid 27985]   File "/usr/lib/python2.7/site-packages/Django-1.11.13-py2.7.egg/django/conf/__init__.py", line 56, in __getattr__
[Fri Jun 22 11:49:55.257288 2018] [:error] [pid 27985]     self._setup(name)
[Fri Jun 22 11:49:55.257318 2018] [:error] [pid 27985]   File "/usr/lib/python2.7/site-packages/Django-1.11.13-py2.7.egg/django/conf/__init__.py", line 41, in _setup
[Fri Jun 22 11:49:55.257361 2018] [:error] [pid 27985]     self._wrapped = Settings(settings_module)
[Fri Jun 22 11:49:55.257380 2018] [:error] [pid 27985]   File "/usr/lib/python2.7/site-packages/Django-1.11.13-py2.7.egg/django/conf/__init__.py", line 129, in __init__
[Fri Jun 22 11:49:55.257431 2018] [:error] [pid 27985]     raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
[Fri Jun 22 11:49:55.257464 2018] [:error] [pid 27985] ImproperlyConfigured: The SECRET_KEY setting must not be empty.
[Fri Jun 22 11:51:18.405671 2018] [:error] [pid 30746] mod_wsgi (pid=30746): Target WSGI script '/opt/graphite/conf/graphite.wsgi' cannot be loaded as Python module.
[Fri Jun 22 11:51:18.405790 2018] [:error] [pid 30746] mod_wsgi (pid=30746): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Fri Jun 22 11:51:18.405841 2018] [:error] [pid 30746] Traceback (most recent call last):
[Fri Jun 22 11:51:18.405879 2018] [:error] [pid 30746]   File "/opt/graphite/conf/graphite.wsgi", line 7, in <module>
[Fri Jun 22 11:51:18.406012 2018] [:error] [pid 30746]     application = django.core.handlers.wsgi.WSGIHandler()
[Fri Jun 22 11:51:18.406035 2018] [:error] [pid 30746]   File "/usr/lib/python2.7/site-packages/Django-1.11.13-py2.7.egg/django/core/handlers/wsgi.py", line 151, in __init__
[Fri Jun 22 11:51:18.406195 2018] [:error] [pid 30746]     self.load_middleware()
[Fri Jun 22 11:51:18.406217 2018] [:error] [pid 30746]   File "/usr/lib/python2.7/site-packages/Django-1.11.13-py2.7.egg/django/core/handlers/base.py", line 48, in load_middleware
[Fri Jun 22 11:51:18.406431 2018] [:error] [pid 30746]     if settings.MIDDLEWARE is None:
[Fri Jun 22 11:51:18.406465 2018] [:error] [pid 30746]   File "/usr/lib/python2.7/site-packages/Django-1.11.13-py2.7.egg/django/conf/__init__.py", line 56, in __getattr__
[Fri Jun 22 11:51:18.406612 2018] [:error] [pid 30746]     self._setup(name)
[Fri Jun 22 11:51:18.406634 2018] [:error] [pid 30746]   File "/usr/lib/python2.7/site-packages/Django-1.11.13-py2.7.egg/django/conf/__init__.py", line 41, in _setup
[Fri Jun 22 11:51:18.406672 2018] [:error] [pid 30746]     self._wrapped = Settings(settings_module)
[Fri Jun 22 11:51:18.406690 2018] [:error] [pid 30746]   File "/usr/lib/python2.7/site-packages/Django-1.11.13-py2.7.egg/django/conf/__init__.py", line 129, in __init__
[Fri Jun 22 11:51:18.406744 2018] [:error] [pid 30746]     raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
[Fri Jun 22 11:51:18.406777 2018] [:error] [pid 30746] ImproperlyConfigured: The SECRET_KEY setting must not be empty.
"/logs/apache/2.4.29/apacheshinken/error_shinken.log" [readonly] 240L, 31365C

Help me I don't have Idea
Thank you

**Comment by schoen** [comment]
Hi @m2cci-KGY ,

As with #6139, this isn't a general support forum for Apache. If your problem is related to Certbot or a Let's Encrypt certificate, please try the Let's Encrypt Community Forum at https://community.letsencrypt.org/. Thanks!
