### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by valeriodeluca** [certbot/certbot#6142]
Hi guys,

I followed this digital ocean guide:

https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-14-04

I get error:

The page does not work
archeologis.com has redirected you too many times.
Try to delete cookies.
ERR_TOO_MANY_REDIRECTS

Thanks

**Comment by schoen** [comment]
Hi @valeriodeluca ,

Please try asking on the Let's Encrypt Community Forum at https://community.letsencrypt.org/. There are more people there who may be able to help you. Thanks!
