### ISSUE TITLE
Apache plugin not working with ExtFilterDefine with regex sintax in VirtualHost

### ISSUE THREAD

**Issue by luca-itro** [certbot/certbot#6148]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu Server 16.04
Apache 2.4.33

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
python-certbot-apache from ppa:certbot/certbot
always last stable :)

## I ran this command and it produced this output:
sudo certbot --apache
The error was: PluginError('There has been an error in parsing the file /etc/apache2/sites-enabled/xxxxxxxxx.conf on line xxx: Syntax error',)

## Certbot's behavior differed from what I expected because:
apache plugin is not working

## Here is the relevantApache virtualhost line for the domain I am configuring:
`ExtFilterDefine sedByBinIN mode=input cmd="/bin/sed -E 's~subdomain\.mydomain\.com~www\.my-rproxied-domain\.com~gI'"`

**Comment by bmw** [comment]
@joohoi, can you take a look at this?

**Comment by joohoi** [comment]
It looks like the configuration parsing library we're using is struggling to parse this line for some reason. I'll try to play around with it a bit and figure out what's the exact character breaking the parsing.

**Comment by itroteam** [comment]
Any news? The issue still persist.... Thank you!

**Comment by bmw** [comment]
No news. The small Certbot team is pretty swamped at the moment.

We may be able to give you the information you need to make progress on this yourself though.

@joohoi, are you able to easily explain to @itroteam how to properly report this problem to Augeas, presumably by reproducing the problem with `augtool`?
