### ISSUE TITLE
Can't update or delete registration with account reuse

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6155]
Create an ACMEv1 account by running:
```
sudo certbot register  --server https://acme-staging.api.letsencrypt.org/directory
```
Then try to delete (or update) the account when using the ACMEv2 server:
```
sudo certbot unregister --server https://acme-staging-v02.api.letsencrypt.org/directory
```
It will fail with an error message like:
```
The request message was malformed :: No JWK in JWS header
```
This happens without setting the server if you have an ACMEv1 prod account and checkout the `acmev2-default` branch.

This happens because in `acme.client.BackwardsCompatibleClientV2` we're using the ACMEv2 client, but we POST to the URL taken from the registration on disk which is an ACMEv1 URL. This mismatch causes us to send the wrong values in the request causing this error.

**Comment by ohemorange** [comment]
I plan to fix this by switching it to use the server set in the config, rather than the one taken from disk. Will probably do this tomorrow, lmk before then if that doesn't sound like a good idea.

**Comment by bmw** [comment]
The plan being to take the hostname or remove `/directory` from the initial server URL, take the path from the account URL, and add it to the end of the server URL? I worry that this hardcodes assumptions about the layout of the ACME server which isn't guaranteed.

Unless you two have talked already, I'm curious if @jsha has any suggestions here.

**Comment by bmw** [comment]
Or @cpu for that matter.

**Comment by cpu** [comment]
> The plan being to take the hostname or remove /directory from the initial server URL, take the path from the account URL, and add it to the end of the server URL? I worry that this hardcodes assumptions about the layout of the ACME server which isn't guaranteed.

I share your reservations about this approach. It's likely over-fitting to the way Let's Encrypt has set up its ACME directory URL and corresponding endpoints.

> This happens because in acme.client.BackwardsCompatibleClientV2 we're using the ACMEv2 client, but we POST to the URL taken from the registration on disk which is an ACMEv1 URL. 

Perhaps one potential solution would be to POST the `newAccount` endpoint using the ACMEv2 ["only return existing" feature](https://tools.ietf.org/html/draft-ietf-acme-acme-12#section-7.3.1) to learn the ACMEv2 account URL for the given legacy keypair. It would be an extra round trip but you would be guaranteed to get the correct URL to update for the account and wouldn't have to do any URL manipulation specific to Let's Encrypt.

**Comment by ohemorange** [comment]
I'd actually assumed we'd only saved the base server url to disk and were dynamically generating or asking LE for the rest of it. Sounds like we save the entire url though. If we are in fact dynamically generating the endpoint, this task becomes simpler.

Since it sounds like we're not, "only return existing" sounds like the perfect solution here.

**Comment by ohemorange** [comment]
As part of this, I plan to give the whole `account.py` file a closer reading, looking where we assume a server URL and making sure that makes sense. I think `delete` should be the last of it, but I want to check that.

**Comment by bmw** [comment]
> Since it sounds like we're not, "only return existing" sounds like the perfect solution here.

Agreed. The entire URL to the account object is what's saved and being reused here.

> As part of this, I plan to give the whole account.py file a closer reading, looking where we assume a server URL and making sure that makes sense. I think delete should be the last of it, but I want to check that.

Good idea!

**Comment by ohemorange** [comment]
Is `onlyReturnExisting` available in ACMEv1 or only ACMEv2?

**Comment by ohemorange** [comment]
new question: how were you hitting this error? I hadn't yet written the code to do account reuse on delete.

**Comment by ohemorange** [comment]
ah, maybe you loaded in between?

**Comment by ohemorange** [comment]
FUN FACT:

this bug is also hit when registering and unregistering an acmev2-only account on the acmev2 endpoint. it may also be triggered by account reuse.

**Comment by cpu** [comment]
> Is onlyReturnExisting available in ACMEv1 or only ACMEv2?

@ohemorange `onlyReturnExisting` is only specified in ACMEv2. 

In ACMEv1 you can find an existing registration's ID by POSTing `newRegistration` with the existing keypair but there isn't any way to indicate to the server that you don't want a new reg. to be created if one doesn't exist.

**Comment by bmw** [comment]
> Is onlyReturnExisting available in ACMEv1 or only ACMEv2?

This gets fun. On the one hand, I'm not sure we have to worry about this because we're only supporting account reuse from ACMEv1 -> ACMEv2.

On the other, if we update the ACMEv1 account URL to ACMEv2 while updating the registration, Certbot will store this change to disk. In the case of account reuse, this will cause Certbot to have an ACMEv2 account with an ACMEv2 URL and potentially other [ACMEv2 values](https://tools.ietf.org/html/draft-ietf-acme-acme-12#section-7.1.2), stored in the ACMEv1 account directory. At the very least, this would cause forward compatibility problems with updating/deleting ACMEv1 accounts.

> deactivation is broken with the acmev2 client

Really? We have integration tests for at least the [simple cases](https://github.com/certbot/certbot/blob/552e60a12691d434ea86a7c6bf5bc4a270651ba8/tests/boulder-integration.sh#L203) of this. We should add tests to catch any corner cases you found which we're not handling properly or if the tests are incorrectly passing, fix them.

> the delete method should do account reuse like find_all and load. this is probably not a problem in practice because I don't think we ever call delete without calling find_all first, but should be fixed.

Yeah. I looked into this when reviewing #6156. `find_all` and `load` are currently always called first, but it'd be good to make sure everything still works if this changes. As a more minor point, we should probably check that symlinked accounts are deleted in the way we expect.

All of this doesn't have to happen in the same PR though. Let me know if you'd like help with any of these pieces.

**Comment by bmw** [comment]
This would require some changes outside of our acme module, but what if when we updated an account from v1 to v2, we removed the symlink and wrote the ACMEv2 account to the ACMEv2 accounts directory and left the ACMEv1 account unmodified? This may require some changes to what we symlink if we want to try and keep our limited support for multiple accounts.

Bonus points if we check for this case when deleting the account and deleted both versions if they exist. I think this could probably come later though.

**Comment by ohemorange** [comment]
>> deactivation is broken with the acmev2 client

> Really? We have integration tests for at least the simple cases of this. We should add tests to catch any corner cases you found which we're not handling properly or if the tests are incorrectly passing, fix them.

?????? just did the same exact steps as I did on friday and now it's not getting that error when the server's the same. computers, man. well, at least that's one less bug to worry about.

> This would require some changes outside of our acme module, but what if when we updated an account from v1 to v2, we removed the symlink and wrote the ACMEv2 account to the ACMEv2 accounts directory and left the ACMEv1 account unmodified? This may require some changes to what we symlink if we want to try and keep our limited support for multiple accounts.
>
> Bonus points if we check for this case when deleting the account and deleted both versions if they exist. I think this could probably come later though.

An ACMEv2 account in the ACMEv1 directory with an ACMEv2 URL is not ideal. Trying to delete an account then later finding out it wasn't deleted is worse.

The reason it's not ideal is if values get put in there that break ACMEv1 code. But the reason we have them symlinked is that on the LE end they're actually the same account on the backend, it's just the middle layer that's talking that's different.

So assuming that the goal of account reuse is to not break accounts and keep them consistent, I actually think it's better to just update the URL, do unregistration properly using ACMEv2, and just save that back to the shared local storage. As long as that doesn't then break things when you try to use ACMEv1 (which I'm about to check).

**Comment by ohemorange** [comment]
Ok, so here's what was going on.

In ACMEv1, if you want to unregister, you better have a `jwk` in your header. In ACMEv2, you can have a `kid` in your payload instead, or use `jwk` if you want.

Here's the thing. `jwk` and `kid` are mutually exclusive, so if one is set, we don't include the other. We only set `kid` if a) we're using acmev2 as determined by the `--server` URL, and b) we have an account loaded into `ClientNetwork.account`.

Now. If you have an ACMEv1 account but an ACMEv2 `--server`, we were just posting it to an ACMEv1 url. But we think that we're using ACMEv2, so we set `kid`, there's no `jwk`, and the ACMEv1 server is unhappy.

Slight aside for posterity:
Getting an account using `onlyReturnExisting` was failing because the new-account endpoint on ACMEv2 doesn't accept `kid` at all, but `ClientNetwork.account` was set because there is a valid account hanging around our system so we just stuck that value in there, in an only-talking-about-one-loaded-account-this-run paradigm, which is actually mostly fine.

Anyway, it's actually perfectly fine to go ahead and continue making updates to the ACMEv1 account at the ACMEv1 URL, even if we think we're using ACMEv2. We just need to make sure that `ClientNetwork.account` isn't set for the `deactivate` operation. It's also perfectly fine to unset `ClientNetwork.account`, get the new url, make sure `ClientNetwork.account` is still unset, then deactivate at that new URL.

To actually fix this bug, we can make a one-line change. Or we could try to do fancier things, as we've discussed above. Not sure I see a pressing reason to do so (especially for this release), but willing to be convinced otherwise.

**Comment by ohemorange** [comment]
By the way, the whole "what to do after updating it" point is a bit moot, because we do the saving to disk in Certbot, and the only time we call update in this way is during deactivation, and we always delete the account immediately after that.

**Comment by ohemorange** [comment]
> As a more minor point, we should probably check that symlinked accounts are deleted in the way we expect.

See #6172.

**Comment by bmw** [comment]
> By the way, the whole "what to do after updating it" point is a bit moot, because we do the saving to disk in Certbot, and the only time we call update in this way is during deactivation, and we always delete the account immediately after that.

`certbot register --update-registration` saves the updated registration without deleting it.

**Comment by bmw** [comment]
What if we did something like this:
```
diff --git a/acme/acme/client.py b/acme/acme/client.py
index bdc07fb..b29dbd9 100644
--- a/acme/acme/client.py
+++ b/acme/acme/client.py
@@ -9,6 +9,7 @@ import time
 
 import six
 from six.moves import http_client  # pylint: disable=import-error
+from six.moves.urllib import parse
 import josepy as jose
 import OpenSSL
 import re
@@ -73,7 +74,12 @@ class ClientBase(object):  # pylint: disable=too-many-instance-attributes
             terms_of_service=terms_of_service)
 
     def _send_recv_regr(self, regr, body):
-        response = self._post(regr.uri, body)
+        kwargs = {}
+        netloc = parse.urlparse(regr.uri).netloc
+        if netloc in ('acme-staging.api.letsencrypt.org', 'acme-v01.api.letsencrypt.org'):
+            kwargs['acme_version'] = 1
+
+        response = self._post(regr.uri, body, **kwargs)
 
         # TODO: Boulder returns httplib.ACCEPTED
         #assert response.status_code == httplib.OK
```
We could move this into `ClientV2` if we wanted, but this approach saves us the extra round trip and prevents us from changing the account on disk from ACMEv1 to ACMEv2.

While we are hardcoding LE specific values which I normally don't like doing, account reuse across ACME versions like this is LE specific. The main downside I see with this approach is if LE changes the hostname where ACMEv1 registrations are stored.

@cpu, what do you think? Is there a significant risk of this happening?

**Comment by cpu** [comment]
> @cpu, what do you think? Is there a significant risk of this happening?

@bmw I don't think there's a significant risk of the `acme-v01.api.letsencrypt.org` API endpoint changing. I could imagine a world where we made `acme-staging.api.letsencrypt.org` ACMEv2 one day under the same URL - this isn't something anyone has actually proposed (and probably isn't a great idea) but seems within the realm of possibility.

**Comment by andrewbanchich** [comment]
@bmw Is this issue supposed to be fixed? I am still getting
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
An unexpected error occurred:
The request message was malformed :: No JWK in JWS header
Please see the logfiles in /var/log/letsencrypt for more details.
```
when running `sudo certbot register --update-registration --email admin@mydomain.com`

**Comment by bmw** [comment]
Are you on Ubuntu and using our PPA? Not all of the newest versions of Certbot's components have been uploaded there yet (although we should have updated our requirements so that you couldn't use the latest version of Certbot without a newer version of our ACME library as well).

You can work around this problem for now by adding `--server https://acme-v01.api.letsencrypt.org/directory` to the command line.

**Comment by andrewbanchich** [comment]
Yes to Ubuntu and PPA.

That worked. Thank you!
