### ISSUE TITLE
HelpfulArgumentParser not parsing arguments the same way when detect_defaults=True

### ISSUE THREAD

**Issue by sTywin** [certbot/certbot#6164]
Hi folks,

I am trying to write an installer plugin. I need an optional argument (parameter) from the user that has one or more values (i.e. `nargs='+'`). In the config namespace passed to my plugin's `__init__`, I can see the parameter I specify, and it works as expected:

- [x] When not specified, the config value is `None`
- [x] When specified with no values, I get an error "expected at least one argument"
- [x] When specified with a single value, the config is `["value0"]`
- [x] When specified with e.g. 2 values, the config is `["value0","value1"]`

These are all the correct behavior that I would expect from argparse.

However, if I combine this with the `--dns-route53` authenticator plugin, I run into some problems. The config my plugin get when certbot starts up is still correct in all cases, the `dns-route53` authenticator runs successfully, but then in the last case above (multiple values), I am getting `certbot: error: unrecognized arguments: value1` (along with a usage printout) before my plugin is run, and then certbot quits. 

If the `dns-route53` authenticator is skipped (i.e. because an existing certificate is found), then my installer plugin is executed correctly.

Suggestions? I'm not really set up for other authentication methods so I haven't been able to try those.

macOS 10.13.5
Python 3.6.5
certbot==0.25.1
certbot-dns-route53==0.25.1

**Comment by sTywin** [comment]
OK, I'm not sure this is related to `dns-route53` at all, so much as `certbot`'s handling of parameters, possibly when trying to write out the renewal configuration file? I'm kind fo drowning here. I've dug down and found the stack traces for where the error message pops up, both for new configurations and renewed configurations.

New:
```
main.py:main
main.py:run
main.py:_get_and_save_cert
client.py:obtain_and_enroll_certificate
storage.py:new_lineage
storage.py:relevant_values
cli.py:option_was_set
cli.py:set_by_cli
cli.py:prepare_and_parse_args
cli.py:parse_args
```

Renewal:
```
main.py:main
main.py:run
main.py:_get_and_save_cert
renewal.py:renew_cert
storage.py:save_successor
storage.py:update_configuration
storage.py:relevant_values
cli.py:option_was_set
cli.py:set_by_cli
cli.py:prepare_and_parse_args
cli.py:parse_args
```

What's interesting is that the first time `parse_args` is run on `certbot` startup, it works fine; the second time, underneath `relevant_values`, the "verb" has been moved from the beginning to the end of the `args` list, and `detect_defaults` is `True` instead of `False`.

**Comment by sTywin** [comment]
It looks like [this line](https://github.com/certbot/certbot/blob/master/certbot/cli.py#L210) in `set_by_cli` is where the verb gets moved to the end of the argument list. It is not clear to my why this is necessary (or if it is necessary at all).

**Comment by sTywin** [comment]
In [`cli.HelpfulArgumentParser.modify_kwargs_for_default_detection`](https://github.com/certbot/certbot/blob/master/certbot/cli.py#L444), any argument parameters in the list [`ARGPARSE_PARAMS_TO_REMOVE`](https://github.com/certbot/certbot/blob/master/certbot/cli.py#L123) are removed from the parser configuration if `detect_defaults` is set to `True`. This list includes the `nargs` parameter. It is not clear to me why `nargs` must be removed in order to detect whether the user has over-ridden the default.

Removing `nargs` from `ARGPARSE_PARAMS_TO_REMOVE` solves my issue for new, re-installation, and renewal. Can anyone see a reason why this should cause any issues?

**Comment by sTywin** [comment]
Removing `nargs` and `type` from `ARGPARSE_PARAMS_TO_REMOVE` (leaving only `const`) results in no errors in my test setup, and default detection remains consistent.

**Comment by bmw** [comment]
Some progress on this was made in #6188, but the PR hasn't seen any response in a couple months. I put the work in the [nargs-default](https://github.com/certbot/certbot/tree/nargs-defaults) branch if anyone wants to build off of it.

**Comment by wgreenberg** [comment]
FWIW `detect_defaults` will be going away in https://github.com/certbot/certbot/pull/9678, so this issue probably doesn't warrant keeping open.
