### ISSUE TITLE
docker image with long running process

### ISSUE THREAD

**Issue by zh99998** [certbot/certbot#6166]
currently official certbot docker images are all run one-shot. it exits after cert obtain finished.

it's really inconvenience since docker don't have a cron function and system crontab is uncomfortable when deploying to container orchestration systems.

my solution is wrap by a simple shell script loop run certbot and sleep.

```bash
#!/bin/sh

while :
do
  certbot $@
  sleep 30d
done
```
it works but I have to make my own docker image just because of this.
since it's a common behavior and totally no my own custom logic, I think certbot should get it into official docker image maybe with a tag (like certbot/certbot:cron, certbot/dns-cloudxns:cron)

or just give a command line flag (like --cron) in certbot. then I can specific it within `command` option of docker

**Comment by schoen** [comment]
@bmw, do you know anything about how other people are currently handling automated renewal with Certbot run inside of Docker?

**Comment by bmw** [comment]
I think most people are just using cron on the host system. We've talked about this before though and I think doing something like this seems reasonable. We just have to pick an approach.

cc @joohoi

**Comment by joohoi** [comment]
In some cases I have instructed people to create their own cron containers using `certbot/certbot` or relevant DNS plugin container as base image. 

We could install cron to the container, and create an init script that takes a cli flag like suggested by @zh99998 in the original message. My only concern about this approach is that the command line options would diverge from the "native" certbot at that point.

**Comment by bmw** [comment]
This is an interesting idea that we should probably look into, but to be honest, the core Certbot development team probably won't have time to get to it for a while.
