### ISSUE TITLE
Can we please just have one Lexicon DNS authentication plugin?

### ISSUE THREAD

**Issue by chris-morgan** [certbot/certbot#6178]
*Or: The approach being used for DNS authentication plugins is madness.*

Currently there are ten DNS providers, five of which are using Lexicon.¹ There are eleven issues open for creating Lexicon-backed authenticators for specific DNS providers.²

Lexicon currently supports thirty-five providers—so should there be twenty-odd more tracking issues? And it has requests for almost twenty more, and doubtless more exist that could be added.

Because I’d like to use it, I just went and created a Vultr plugin, simply copying the DNSimple one and making the required changes—which were all trivial save one, just renaming “DNSimple” to “Vultr”, “dnsimple” to “vultr”, updating the URL to instruct the user on where get the API key from, and adjusting the check for suggesting to the user that the API key might be wrong (because DNSimple uses HTTP status 401, while Vultr uses 403). The total diff is +808 −5, having created 18 files and touched 12 more, and if I submit it and it is accepted (which the existence of #4600 suggests it would be) it will definitely add to the maintenance burden. Before I started, I was kind of hoping—though not expecting—that it might be +1 −0, given that it’s just piggybacking on top of Lexicon.

This situation seems quite absurd to me: surely the whole idea of Lexicon should be to have *one* authenticator plugin, Lexicon, and let the config file which is passed in specify all necessary details for whichever provider may be desired?

Only two arguments³ get passed for each authenticator plugin—a file to look in, and a propagation-seconds figure. Currently, usage might be like this:

```sh
certbot certonly \
    --dns-vultr \
    --dns-vultr-credentials ~/.secrets/certbot/vultr.ini \
    --dns-vultr-propagation-seconds 10 \
    -d example.com \
    -d www.example.com
```

With this ~/.secrets/certbot/vultr.ini:

```ini
dns_vultr_token = THIRTYSIXRANDOMCHARACTERSOFKEYPLEASE
```

I suggest it should look rather like this:

```sh
certbot certonly \
    --dns-lexicon \
    --dns-lexicon-credentials ~/.secrets/certbot/vultr.ini \
    --dns-lexicon-propagation-seconds 10 \
    -d example.com \
    -d www.example.com
```

With this ~/.secrets/certbot/vultr.ini (feel free to replace `[vultr]` with `provider = vultr` if the former is inconvenient):

```ini
[vultr]
auth_token = THIRTYSIXRANDOMCHARACTERSOFKEYPLEASE
```

(Observe the name auth_token is from Lexicon, rather than having an unnecessary translation layer in the certbot-dns-* plugins.)

This would make *everyone’s* life better. It’d reduce the maintenance burden on Lexicon-supported DNS authentication plugins down to just the one, clean, neatly specified plugin, rather than a base layer plus five, sixteen, thirty copies of almost the same thing, except for their slight deviations and copy-paste errors and forgotten parity updates. It would also make users of other DNS providers happy because they would now be able to readily obtain wildcard certificates.

#4767 and the issues linked to from there may be relevant here; reducing most of the plugins down to just one might help with decision-making; and it’s worth noting that most of Lexicon’s providers don’t require extra dependencies: only namecheap, route53, softlayer, subreg and transip do at present.

----

¹ Those that are using Lexicon: cloudxns, dnsmadeeasy, dnsimple, luadns and nsone; those that are not: cloudflare, digitalocean, google, rfc2136 and route53.

² #4589, #4590, #4591, #4592, #4594, #4595, #4597, #4598, #4599, #4600 and #5745.

³ certbot-dns-route53 is different in that it doesn’t get passed a file name on the command line, but rather uses environment variables to find it. It’s not using Lexicon.

**Comment by bmw** [comment]
@zjs, if you have the time, I'd love to hear your thoughts on this.

**Comment by zjs** [comment]
Reducing the duplicated code between Lexicon-based plugins definitely seems like a good idea. It would definitely reduce the maintenance burden in this area, including the effort around code reviews — which I'm far too slow at.

I know that this is something we looked at last year. Unfortunately, I don't recall all of the reasons we didn't want to go this route.

I think we should be able to address the problems in this space (duplicated code, high cost of adding and reviewing new plugins, etc.), but I'm not sure the proposed implementation (a single plugin) is the best way to do so. (It may well be the best way to do so, but as with many things I think it's worth starting with the problems, considering possible solutions, and then comparing those solutions to pick the best one.)

Some things to consider:
- From the point of view of an end-user, Lexicon is an implementation detail. A typical user may know what DNS provider they use, but almost certainly doesn't know whether Lexicon supports that provider (and if Lexicon supports the provider, whether that's how Certbot has chosen to implement support for the provider — an early design principle for the DNS plugins was to prefer first-party libraries to Lexicon when available).
   - To me, this suggests that support for providers A, B, and C should _look_ the same even if A and B are supported via Lexicon and C is not.
- As mentioned above, there are differences between DNS providers which are not handled by Lexicon. The most notable area is error handling; almost every provider has a different set of errors (expressed via HTTP status or specific error strings) that indicate different mistakes a user may have made. Other differences exist in the areas of propagation delays and types of authentication information expected.
- We don't currently have a way to conduct end-to-end testing of plugins. Last I looked, Lexicon didn't either. The more tightly coupled the support for a set of providers is, the harder it is to make changes. (Currently, introducing one plugin doesn't risk breaking an existing one, but if introducing support for a new provider required updating a library used for all providers, it might be necessary to manually test all existing providers to ensure that nothing broke.)
- In addition to code-level duplication between plugins, there's also duplication around documentation. Perhaps this can/should be addressed in a broader way.
- In addition to code- and documentation-related duplication, there's also a fair bit of boilerplate to add a new plugin to the project. Perhaps this can/should be addressed in a broader way.
- Most typical users only have a single DNS provider. (I don't remember exactly why this is relevant, but it's definitely something that was pointed out previously... I think the context was essentially that all else being equal we should put the users' experience ahead of ours.)

**Comment by chris-morgan** [comment]
I agree that Lexicon should be an implementation detail. I only went for `--dns-lexicon` <i>&amp;c.</i> to present an easy way forward; what I would like ideally is more like this:

```sh
certbot certonly \
    --dns ~/.secrets/certbot/vultr.ini \
    --dns-propagation-seconds 10 \
    -d example.com \
    -d www.example.com
```

… with the same vultr.ini; and let the DNS authenticator plugin manager look at the header line in the INI file, see “vultr”, and look to see if there is a certbot-dns-vultr package installed (however you like), and if there is not, pass it on to Lexicon, and if *it* fails too, then complain to the user.

I think that mitigates some of your problems with my initial suggestion. The main hazard I can think of is if for some reason you have a custom plugin, *and* Lexicon can handles that provider, and the custom plugin isn’t installed for whatever reason, so the Lexicon one is used instead, unbeknownst to the user. But I tend to think Certbot should be aiming for *total* delegation to Lexicon, so that the certbot-dns-* package check and use could then be dropped altogether, leaving no scope for surprises. That would entail moving some things out of this repository into it (e.g. certbot-dns-rfc2136).

I only skimmed them very briefly, but my passing glance showed only two variations in the Lexicon-backed DNS authentication plugins: default propagation delay (mostly I imagine they’re just a figment of copying and pasting, but they could potentially have been adjusted for slow providers), and authentication error handing. Both of these seem to me like they should live in Lexicon—as a recommended propagation delay (just another constant on each provider), and as a new type of exception if there isn’t one for the purpose already. It seems to me that Certbot *shouldn’t* be adding anything extra to Lexicon—its DNS authentication truly should be a very thin layer on top of Lexicon in general.

Doing it all like this will require a bit of work on Lexicon as well as a substantial adjustment of how it works in certbot, but as an outsider to both projects this seems the sensible approach to me.

We could work inside the current architecture to reduce the eight hundred lines I had to change to just two or three with code generation, but it seems to me much more useful to generalise it so that there *is* only one plugin, for almost all cases at least. I recall hearing rumours of Lexicon’s route53 provider being broken, while I’m guessing Certbot’s isn’t—that would certainly be cause for keeping certbot-dns-route53 separate in the short term!

At this point, my impression is that testing is the main concern (absolutely genuine; it’s mine too), and a concern about upstream breakages and security issues (misguided, in my opinion: the new workflow would be for Certbot to specify a dependency on a particular version of Lexicon, ideally bundling it when installed via certbot-auto, and so you still have an opportune time for such review, when updating it—for all plugins at once, rather than a harum-scarum approach that will have you review inconsistently; alternatively, stop viewing it as “upstream” and review more proactively).

**Comment by adferrand** [comment]
For the record, there is currently two PR for authenticator written without Lexicon, but that Lexicon support: #6135 and #6386. I is likely that they will be re-written with Lexicon. 

So it could be a good occasion to continue the discussion here, and make the implementation of this new authenticators using the approach that will emerge here.

**Comment by noci2012** [comment]
The issue #6386 is updated to use dns-lexicon please verify. (modelled after dnsimple.

**Comment by bmw** [comment]
As I said in #6504, I think the core issue for me personally for our path forward for DNS plugins is testing which is covered by #6464. If we decide we want end to end tests of each DNS provider, I don't think we want a generic plugin based on Lexicon because we cannot reliably test all of the functionality it contains. (Such a plugin could certainly still exist as a third party plugin.) If we decide we don't need end to end tests for each DNS provider, then I'm personally beginning to lean towards this option over most other alternatives.

I'll also throw out that a variation on this issue I've seen suggested is effectively dynamically generating a new "plugin" for each DNS provider at runtime. Regardless of the implementation, I think providing good documentation and UI in both the CLI and interactive prompts is one of the trickier issues to resolve here.

**Comment by ids1024** [comment]
>  If we decide we want end to end tests of each DNS provider, I don't think we want a generic plugin based on Lexicon because we cannot reliably test all of the functionality it contains.

What about a single Lexicon plugin, with a whitelist of providers it supports? That would substantially reduce the number of plugins, while still allowing them all to be tested.

It would still be kind of annoying to someone who wants to use one of the providers not on the whitelist, but it seems better than the mess of similar plugins with Lexicon backends.

**Comment by adferrand** [comment]
What I have in mind is something like this indeed. The generic Lexicon plug-in would not give acces to every provider supported by Lexicon. Only the providers that Certbot is willing to support, so basically providers for which an acceptable test workflow exists.

In fact this plug-in would not expose itself through Certbot as a Lexicon plug-in, but as several DNS plugins for each provider enabled. With that, the fact that a given dns provider is backed by lexicon or not stays an implementation detail for a certbot user. 

The main idea with this plug-in is in fact to reduce at the minimum the duplicated code required to have support on a set of provider. Because on current situation, either backed by Lexicon or not, each DNS plug-in requires hundreds of line of code. 

So the growing codebase of Certbot can just explode with the number of providers supported, and I want to avoid that at the very most.

**Comment by zjs** [comment]
> In fact this plug-in would not expose itself through Certbot as a Lexicon plug-in, but as several DNS plugins for each provider enabled. With that, the fact that a given dns provider is backed by lexicon or not stays an implementation detail for a certbot user.

I really like this aspect of your proposed design.

**Comment by ddymko** [comment]
Hey there 👋 

Vultr engineer here - I wanted to pop in and ask if there is anything we could do to help out with getting Vultr integrated!?

**Comment by noci2012** [comment]
Or slightly more broadly what's the state of dns authenticators in general.

**Comment by bmw** [comment]
The state of DNS authenticators in Certbot hasn't changed for a while. This is something we want to resolve, but we've been busy with other parts of the project. We're still not currently accepting new DNS plugins because we want to make a decision on some of the issues like #6464, #6503, and #6504 first.

In the meantime, people are welcome to release 3rd party plugins offering support for other DNS providers. https://github.com/coldfix/certbot-dns-netcup is one example of that.

**Comment by adferrand** [comment]
Still relevant
