### ISSUE TITLE
Add options for intermediate-verbosity challenge debugging information

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#6194]
Per https://community.letsencrypt.org/t/ability-to-debug-what-ip-address-the-request-is-resolved-to/66275, it could be helpful to have some way to see a moderate amount of information about challenge verification from the ACME conversation, such as challenge types, challenge status, and resolved IP addresses, for both successful and unsuccessful validation attempts, but without the large amount of protocol data that's currently displayed by running with `-v`. Maybe there could be a summary view like

```
For requested name foo.example.com, acme-v02.api.letsencrypt.org performed successful http-01 challenge to 10.2.3.4.
For requested name bar.example.com, acme-v02.api.letsencrypt.org performed successful http-01 challenge to 10.2.3.4.
For requested name baz.example.com, acme-v02.api.letsencrypt.org performed unsuccessful http-01 challenge to 10.2.3.6. Failure information: [...]
```

**Comment by bmw** [comment]
Let's Encrypt currently includes the IP addresses, but I don't believe this is part of the ACME spec. For this reason and the fact we have a lot on our plate at the moment, I'm closing this, but if people disagree, please comment and we can chat about it!
