### ISSUE TITLE
Problem : Depends: python3-certbot-apache but it is not going to be installed

### ISSUE THREAD

**Issue by softbranch** [certbot/certbot#6199]
Hello,

I am trying to install but getting error.

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-certbot-apache : Depends: python3-certbot-apache but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Please suggest.
Waiting for reply.
Thanks

**Comment by sydneyli** [comment]
Hi, thanks for reporting @softbranch! It sounds like your packages are broken... this isn't a Certbot problem, so I'm going to close this issue. You may be able to find help troubleshooting your situation on our [community forums](https://community.letsencrypt.org/c/help), or on other sites!
