### ISSUE TITLE
--staging vs. --server - which one wins is unclear

### ISSUE THREAD

**Issue by wowcut** [certbot/certbot#6200]
I can not conclude from the docs which setting is prioritized if both have contradictory content, like e.g:
```
certbot --manual -d example.com \
  --server https://acme-v02.api.letsencrypt.org/directory \
  --staging
```

**Comment by sydneyli** [comment]
If `staging` or `dry-run` is set and `server` is set to a conflicting value, Certbot exits with the error: `--server value conflicts with --staging`. Would you like to propose an addition to https://github.com/certbot/certbot/blob/master/docs/cli-help.txt#L203 to make this behavior explicit in the documentation?

**Comment by sydneyli** [comment]
Closing since it seems like the error message is probably enough to debug this issue if it ever comes up.
