### ISSUE TITLE
docs not clear about what actually is contained in config-dir and work-dir

### ISSUE THREAD

**Issue by wowcut** [certbot/certbot#6201]
While the content of `logs-dir` is quite easy to guess, it is not clear what kind of files are expected in `work-dir` and `config-dir` - this one causing extra confusion as the [documentation](https://certbot.eff.org/docs/using.html#configuration-file) is mentioning these places for an expected configuration file:
```
/etc/letsencrypt/cli.ini
$XDG_CONFIG_HOME/letsencrypt/cli.ini
~/.config/letsencrypt/cli.ini if $XDG_CONFIG_HOME is not set
```
So what exactly **is** `config-dir`? Is it different to the directory that contains `cli.ini`? 
And what happens if `config-dir` is set to a different place than `work-dir`?

Unfortunately also the API [documentation](https://certbot.eff.org/docs/api/interfaces.html?highlight=config%20dir#certbot.interfaces.IConfig.config_dir) has no explanation.

It would be great to read about these important details, as it may help to better adopt certbot to special requirements with local installation, e.g. in a multi-user operating system. 

Thank you very much for your attention!

**Comment by sydneyli** [comment]
Thanks for the report @wowcut, we're always looking to improve our documentation!

> So what exactly is config-dir? Is it different to the directory that contains cli.ini?

It stores your cert data, as well as configuration information for how Certbot will function. We search the `renewal` subdirectory in `config-dir` for `cli.ini`. If it is not found, we search those other locations for `cli.ini` as well. So, here some things we could specify on [this page](https://certbot.eff.org/docs/using.html#configuration-file):
  - We search `config-dir` for `cli.ini` (in particular, if `config-dir` is set to something other than `/etc/letsencrypt`)
  - Which locations take priority over others.

Is there anything else that was unclear or underspecified here?

> And what happens if config-dir is set to a different place than work-dir?

They should be-- this is what happens [by default](https://github.com/certbot/certbot/blob/a2222d5bdff304f8c55b63986d09d3f155ef6893/docs/cli-help.txt#L247).

> It would be great to read about these important details, as it may help to better adopt certbot to special requirements with local installation, e.g. in a multi-user operating system.

Ideally, the function of these directories should be opaque to the user unless they wish to provide a `cli.ini` configuration file. [This FAQ entry](https://certbot.eff.org/faq/#does-certbot-require-root-administrator-privileges) about running Certbot without elevated permissions may be of use to you if you haven't already seen it; we would appreciate suggestions on the documentation there as well!
