### ISSUE TITLE
Duplicate Route53 options in `docs/cli-help.txt`

### ISSUE THREAD

**Issue by trinopoty** [certbot/certbot#6209]
There are 2 entries of `certbot-route53` in `docs/cli-help.txt`.
One around [line 496](https://github.com/certbot/certbot/blob/master/docs/cli-help.txt#L496):
`
certbot-route53:auth:
  Obtain certificates using a DNS TXT record (if you are using AWS Route53
  for DNS).
`
and another around [line 615](https://github.com/certbot/certbot/blob/master/docs/cli-help.txt#L615):
`
dns-route53:
  Obtain certificates using a DNS TXT record (if you are using AWS Route53
  for DNS).
`

Should it be like that or should one be removed?

**Comment by bmw** [comment]
> Should it be like that or should one be removed?

That's a good question. The reason for this is `certbot-route53:auth` was a 3rd party plugin that we took over maintenance of and made a shim around `certbot-dns-route53`. We keep `certbot-route53:auth` around for backwards compatibility.

@hugopeixoto, do you have a preference about whether `certbot-route53:auth` shows up in Certbot's help output?

**Comment by hugopeixoto** [comment]
@bmw I don't think it's worth keeping both lines, it can be removed

**Comment by Oshawk** [comment]
Fixed https://github.com/certbot/certbot/pull/6405
