### ISSUE TITLE
certbot-dns-google: Allow manually specifying the project id

### ISSUE THREAD

**Issue by karsthammer** [certbot/certbot#6225]
Currently certbot-dns-google only has the option of getting the project from the service account JSON or from the instance metadata. It would be nice if it would accept the project as a command line argument overriding these defaults.

Our setup consists of a Google Cloud setup with multiple projects. Servers can be in a different project than the project where we host the DNS.

Example:

* Project A has our DNS zone example.com
* Project B has a server X for which we need a certificate (x.example.com)

We create a service account in project B, to that service account we assign the correct permissions (in project A!). Because the service account is in project B and the server is in project B, certbot fails to find the dns zone.

This would be solved by allowing to manually specify the project where the dns zone is located.

**Comment by schoen** [comment]
@bmw, could you please take a look at this feature request?

**Comment by bmw** [comment]
Just to make sure I'm understanding this properly, you could also accomplish this by creating a service account JSON on server X. It's just being able to set the project id allows you to skip this step and use the metadata service for credentials. Is that right?

**Comment by karsthammer** [comment]
Yes, it would work by creating a service account in project A and using the JSON from that service account on server X in project B. I'm trying to use the metadata provider service account to accomplish this.

Additionally, adding this option would allow a service account created in project B (which in it's JSON has the project set to project B), to write DNS entries in project A. So it provides more flexibility in the way people manage service accounts. (I like to keep the service accounts used in project B in that same project regardless of where they need rights)

**Comment by zjs** [comment]
Agree that this seems reasonable. I don't think this complex project-account relationship was ever considered when the original plugin was implemented.

**Comment by karsthammer** [comment]
@bmw Yes, interested. I will try to make a start on it in the next weeks.

**Comment by emmaLP** [comment]
I have the same issue.

DNS zone is in one project but the cert will be used in another project. Ideally want to be able to specify the project name

**Comment by jenshonkan84** [comment]
I have this issue also as we have our CI/CD in one project and the zone defined in an other project.

**Comment by bahag-klickst** [comment]
We are also facing this issue and would love to see this implemented.
Any updates on this?
