### ISSUE TITLE
Use CERTBOT_DOCS for Apache CLI defaults

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6234]
Certbot often tries to determine the underlying OS and changes its default behavior and config values to match. These defaults often show up in our documentation though which means that the documentation changes based on who built it.

In #6120, we introduced the environment variable `CERTBOT_DOCS` to avoid this behavior and print the same defaults in our documentation regardless of the system it is run on. We added this to nginx in #6137. We don't do this in Apache though as can be seen at https://github.com/certbot/certbot/pull/6232#discussion_r203197775.

We should respect `CERTBOT_DOCS` in the Apache plugin.

cc @joohoi

**Comment by joohoi** [comment]
This is a nice and simple way to handle this! Looking at the Nginx implementation, it looks like it prints all the possible OS based values. I'm not sure if similar behavior is feasible for Apache plugin, as it might have a lot of different values per command line option. Should we use a generic string like `operating system default` or something like that instead?
