### ISSUE TITLE
Don't use --numprocesses auto in sudo: false builds

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6236]
Building off of #6197, it looks like `pytest-xdist` has a hard time determining the number of cores when it is run in any Travis instance with `sudo` set to false in the Travis config. See https://travis-ci.org/certbot/certbot/jobs/404581691#L813 for an example.

To fix this, I think we should configure `tox.ini` to pass through either `TRAVIS_SUDO` or `TRAVIS` for all environments running pytest and automatically use `--numprocesses 2` if the variable is set to the appropriate value. While `TRAVIS_SUDO` may be more accurate and allows us to take advantage of additional cores if they are added to other environments, all [Travis environments](https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System) use two cores, have for years, and doing this for all environments protects us from hitting this issue again if changes in `pytest-xdist` or Travis prevent it from detecting the number of cores in another environment type. I don't have a strong preference which approach is taken.

@greut, thanks for your initial PR working on this. Are you at all interested in working on this as well?

**Comment by greut** [comment]
at this point, it's probably easier to fix pytest-xdist.

**Comment by greut** [comment]
https://github.com/pytest-dev/pytest-xdist/pull/309

**Comment by bmw** [comment]
Nice work in pytest-dev/pytest-xdist#309 @greut.

Once that lands, are you interested in making a PR to revert your previous change to our tests and update our pinnings in `tools/dev_constraints.txt` to use the new version of `pytest-xdist`? Pinnings for `pytest-xdist`'s dependencies may need to be updated as well.

**Comment by greut** [comment]
I'll do that tomorrow morning then, cheers,

**Comment by bmw** [comment]
Fixed in #6253.
