### ISSUE TITLE
Security housekeeping cron job

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#624]
We want to have a script that runs once per hour to perform tasks on the system that need to happen periodically, such as adjusting HSTS and HPKP intervals, and perhaps polling OCSP to trigger renewals on the basis of CA-initiated revocations.

**Comment by pde** [comment]
Handing this to @joohoi to keep or close in the light of current HSTS work.

**Comment by joohoi** [comment]
This is implemented in #5879 and installer plugins are now able to define tasks that run on every invocation of `certbot renew`, and another one that triggers when lineage is actually renewed.
