### ISSUE TITLE
Please update the Ubuntu PPA so that Certbot 0.26.1 is going to be installed with latest version.

### ISSUE THREAD

**Issue by gopalraha** [certbot/certbot#6243]
The Certbot 0.26.1 has been released.

Please update the Ubuntu PPA so that Certbot 0.26.1 is going to be installed with latest version.

**Comment by bmw** [comment]
cc @oerdnj and @ncommander

**Comment by gopalraha** [comment]
Thanks @NCommander for updating the Ubuntu PPA.
