### ISSUE TITLE
If the account has already been created and we try to create again Json parsing exception occures

### ISSUE THREAD

**Issue by daramousk** [certbot/certbot#6246]
This issue was mistakenly reported on the CA's Issues. Read the conversation at:

https://github.com/letsencrypt/boulder/issues/3799

Using acme 0.26

**Comment by cpu** [comment]
:wave: @daramousk 

Sorry to chase you over here but I may have misunderstood when I said you should file a bug with the ACME client. I didn't understand you were using the `acme` module and thought you were using a stand-alone client (like the `certbot` command or `acme.sh`, etc).

Can you share your registration code where you are interacting with the `acme` module in this bug report? I think that will be required for the Certbot team to give you advice on the best way to use the `acme` module to only create the account resource when required.

**Comment by daramousk** [comment]
@cpu See the code here https://github.com/OCA/server-tools/pull/1194/files#diff-9b7e43b14857ae1b9294fe0125a6846fR104

**Comment by cpu** [comment]
@bmw What do you think about this issue? Should `new_account` return the existing account if called twice or should it propagate an exception?

**Comment by dovreshef** [comment]
@cpu Small data point, current client (`BackwardsCompatibleClientV2`) return the existing account on second call.

**Comment by bmw** [comment]
> Should new_account return the existing account if called twice or should it propagate an exception?

My thinking is it should propagate an exception so the caller is aware there's already an existing account rather than us suppressing this information. This is what we do for ACMEv1 when we [raise a ConflictError](https://github.com/certbot/certbot/blob/83f7e72fefb8d9087a5ad488153a644e1b905572/acme/acme/client.py#L971).

Is anyone here interested in writing a PR for this?

> Small data point, current client (BackwardsCompatibleClientV2) return the existing account on second call.

@dovreshef, are you sure? Can you provide another useful snippet like you did above showing this behavior?

**Comment by dovreshef** [comment]
@bmw I was sure, but trying again I get the same json decoding error.

```python
from acme import client as acme_client
from acme import messages
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric.rsa import generate_private_key
import josepy

rsa_key = generate_private_key(
            public_exponent=65537,
            key_size=4096,
            backend=default_backend())

)
key = josepy.JWKRSA(key=josepy.ComparableRSAKey(rsa_key))
net = acme_client.ClientNetwork(key)
server = 'https://acme-staging-v02.api.letsencrypt.org/directory'
client = acme_client.BackwardsCompatibleClientV2(net, key.public_key(), server)
account = client.new_account_and_tos(messages.NewRegistration.from_data(email='me@example.com'))
account = client.new_account_and_tos(messages.NewRegistration.from_data(email='me@example.com'))
```

**Comment by cpu** [comment]
@dovreshef When the server returns a 200 with an empty body and a `Location` header you know the account already exists. That's the only condition where this response is allowed :-)

**Comment by cpu** [comment]
Edited my above response. You should rely on the HTTP status code 200 and the `Location` header but not the empty body part. Per https://tools.ietf.org/html/draft-ietf-acme-acme-13#section-7.3.1 the body of the response should _probably_ be the account resource and not empty. I'll file a Boulder bug to fix that.

**Comment by dovreshef** [comment]
@bmw I've submitted a [PR](https://github.com/certbot/certbot/pull/6251).

**Comment by daramousk** [comment]
A question here:

Why not stick to the RFC and return 200 (and do anything else that you need to do to the state of acme) and just continue with execution?
The end user just wants to create an account, if one is already created, good. Keep going.
Why raise an exception?

**Comment by bmw** [comment]
My reasoning for preferring raising an exception over just returning the existing account was:

1. It gives more information for the caller to act on.
2. As mentioned in https://github.com/certbot/certbot/issues/6246#issuecomment-407158385, Let's Encrypt doesn't return the existing account so we'd have to make a separate query to retrieve it until this is changed.
3. What if the registration given to our library contains different values than the one on the ACME server? Should we make another request to update these values? Should we leave the values unchanged? The spec makes a decision here, but I'm not sure copying it makes the most sense for the users of our library.
4. The user of the library asked for a new account and one was not created.

I'm open to changing my mind or adding a flag or separate function to get the behavior you want, but raising an exception seems like the best path forward to me for now.

**Comment by daramousk** [comment]
@bmw I am going to deposit my reasoning as well, but take it with a grain of salt because I am not aware of many things at this project:

As I understand, acme is a *protocol implementation*. With that being said, any deviation from the protocol should not be acceptable.

Therefore, to your points:

1) The client just invoked a functionality of the RFC and they expect the protocol implementation to act accordingly. If acme starts raising exceptions when they are not expected I am not sure how will the user will react.
2) The lowest common denominator are the *must*s as per RFC2119. Therefore, it is an error to expect something in the body of the request when the CA *may* return it there. The only guarantee is that it will be on the headers so this is where the client should look at.
3) I am not sure if the users should be considered at this point. Acme being a *protocol implementation* should be just that, and not consider the users. The users should be aware of the documentation and what outcomes their actions will have. All these questions should be answered by the RFC (and as I see in 7.3.2 they are) so therefore implementing that would be a solution.
4) And that is fine.

Also, I understand that people will use acme not only with Boulder but with other CAs as well, therefore we cannot depend on Boulder getting a fix.

My problem is already resolved, since I know what happened I am in a position to avoid it. I am just throwing some ideas here in the hope of contributing to your project in a positive way. I would be happy to provide a PR for this.

Thank you and thanks for the fast responses.

**Comment by bmw** [comment]
Thanks for sharing your thoughts. Having additional perspectives is useful and should help us make better decisions.

I completely agree with you that we can only rely on the behavior specified in the ACME RFC. People are using Certbot and our ACME library with other CAs and this is something we want to continue supporting. Thanks for flagging that we have no guarantees about the body of the response.

I don't agree we should blindly follow the RFC though. My main reason for that is we do take the users of `acme` into consideration when making decisions. We didn't write `acme` with the intention of it being a simple reference implementation of an ACME client library. Instead, we wrote it with the intention of it being used by Certbot and other Python ACME clients so the library's usability is a major concern for us.

I think the RFC defines the interface between an HTTP server and client while `acme` is a Python library. I don't think the considerations, conventions, and intuitions about "correct" behavior are the same. Additionally, while reading the ACME RFC is great and almost certainly allows you to write better ACME software, if you have to read the ACME spec to use our library, I think we have some work to do.

My proposed path forward here for now is:

1. Raise an exception containing the value of the location header when the account already exists.
2. Do not add a flag or separate function to automatically return the existing account. This can be accomplished by the user of the library in my few line code snippet below and works for both ACMEv1 and ACMEv2 (at least once #6258 is resolved).
3. Document the exception and how to get the existing account in the docstring of `new_account`.

```
try:
    regr = client.new_account(new_regr)
except errors.ConflictError as e:
    regr = regr.update(uri=e.location)
    regr = client.query_registration(regr)
```

**Comment by dovreshef** [comment]
@bmw I've update the PR. 

The only thing missing is point 3. Since I am not sure how to document code in a docstring :).

**Comment by bmw** [comment]
This was fixed in #6251.

**Comment by cpu** [comment]
Thanks @dovreshef !

**Comment by evilaliv3** [comment]
@bmw: as well as for https://github.com/certbot/certbot/issues/6258#issuecomment-408682025 i consider fundamental to try to descreibe here a solution for users of 0.25.1

I suspect that any software using that verson is now failing to renew certificates if during renewal the new_account function is called

**Comment by dovreshef** [comment]
@evilaliv3 Is there an example of code that will fail?

I think no software would be trying to recreate accounts automatically since it does not seem to me like it ever worked.

If there is, you can workaround it for now by doing something like the following:
```python
from acme import client as acme_client
from acme import messages

key = ...
email = ...
new_regr = messages.NewRegistration.from_data(key=key.public_key(),   
    email=email, terms_of_service_agreed=True)
net = acme_client.ClientNetwork(key)
directory = messages.Directory.from_json(net.get( 'https://acme-staging-v02.api.letsencrypt.org/directory').json())
client = acme_client.ClientV2(directory, net)
response = client._post(client.directory['newAccount'], new_regr)
regr = messages.RegistrationResource(
            body=messages.Registration.from_json(new_regr.to_json()),
            uri=response.headers['Location'])
client.update_registration(regr)
```
