### ISSUE TITLE
Certbot installation error

### ISSUE THREAD

**Issue by thebephele** [certbot/certbot#6248]
Hi guys,

I was trying to install certbot and an error showed up.

## I ran the following command lines:

$ yum -y install yum-utils
$ yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional
$ sudo yum install python2-certbot-apache

Below is the error I received:

Error: Package: python2-certbot-apache-0.25.1-1.el7.noarch (epel)
           Requires: mod_ssl
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

Your advise will be highly appreciated.

**Comment by schoen** [comment]
@bmw, do you know what could cause this? Could it be an out-of-date set of EPEL package metadata?

**Comment by bmw** [comment]
I really don't unfortunately but our RPM package maintainers might. Any ideas @elyscape, @hogarthj, or @nbebout?

**Comment by elyscape** [comment]
@thebephele If you're on CentOS, why are you running `yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional`? That should only be necessary on RHEL.

**Comment by elyscape** [comment]
Additionally, `mod_ssl` should be present in the CentOS base repo. Have you disabled that for some reason?

**Comment by thebephele** [comment]
Hi Guys,

Thank you so much for your support. After digging around, I figured out that it was not necessary to run the certbot or try to install the ssl certificate via ssh because I am running cPanel and there is already a plugin directly on the WHM for Let's Encrypt ssl. So for any dummy like me who might battle to install the this ssl and already have cpanel installed then simply just login to your whm and go to " manage autossl " as shown from the snapshot below:
![snapshot](https://user-images.githubusercontent.com/41558707/43102773-53b80716-8ecc-11e8-8aa3-27b68246d86f.png)

I hope this info will help someone one day.

Thank you once again guys. It's great to know that there are buddies out there willing to help.

**Comment by bmw** [comment]
Thanks for writing this follow up @thebephele!
