### ISSUE TITLE
homebrew directory not empty

### ISSUE THREAD

**Issue by alper** [certbot/certbot#6255]
## My operating system is (include version):
macOS 

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
homebrew

## I ran this command and it produced this output:
`brew cleanup`
`Error: Directory not empty @ dir_s_rmdir - /usr/local/Cellar/certbot/0.25.1_1`

Why is this directory not empty? Can I hard delete the directory without problems?

**Comment by DomT4** [comment]
This can happen if you're `cd`'ed inside the `certbot` Cellar directory when you run `brew rm`. Was that the case?

**Comment by alper** [comment]
You were right I was in there… That's super weird.

Now I'm back in `~` but I still get:

```
alper@Alpers-iMac:~$ brew uninstall --force certbot
Uninstalling certbot... (392 files, 4.3MB)
Error: Directory not empty @ dir_s_rmdir - /usr/local/Cellar/certbot/0.25.1_1
```

**Comment by DomT4** [comment]
If you run another `brew uninstall --force certbot` immediately after the first does the error happen again? You can see the process Homebrew is walking through [here](https://github.com/Homebrew/brew/blob/e0a8a79921f3fa0ad33a38c24c0576166a776105/Library/Homebrew/keg.rb#L274-L321), with the seemingly problematic `rmdir_if_possible` coming from [here](https://github.com/Homebrew/brew/blob/eb5175857c9b05396b73798ff42df95ca253e1fb/Library/Homebrew/extend/pathname.rb#L228-L244).

**Comment by alper** [comment]
I would nuke the directory by hand, but it seems to have some weird permissions?

**Comment by alper** [comment]
And yes it does happen on repeated invocations as well.

**Comment by bmw** [comment]
Thanks yet again for the help @DomT4. Unless you have any other ideas, @alper, you may want to create an issue against Homebrew. They build and maintain our Homebrew formula and we don't have any familiarity or involvement in the process. Sorry I can't be more helpful!

**Comment by code918** [comment]
I had the same problem. At first I thought it was because the certbot program was used. The problem was owner rights issue. The workaround is as follows:
$ chown -R MyUser: staff /usr/local/Cellar/certbot/0.25.1_1
$ brew uninstall certbot

**Comment by rsvenkatesh** [comment]
> I had the same problem. At first I thought it was because the certbot program was used. The problem was owner rights issue. The workaround is as follows:
> $ chown -R MyUser:staff /usr/local/Cellar/certbot/0.25.1_1
> $ brew uninstall certbot

This worked for me, thank you.

**Comment by SebastianoX** [comment]
Similar problem for a 3.7.7 python env installed via brew.
The following:
```
chown -R MyUser:staff /usr/local/Cellar/python/3.7.7
```
solved the error when running `brew cleanup`.
Thanks!

**Comment by nandudb** [comment]
Thanks. It did fix the issue

**Comment by xyzst** [comment]
> Similar problem for a 3.7.7 python env installed via brew.
> The following:
> 
> ```
> chown -R MyUser:staff /usr/local/Cellar/python/3.7.7
> ```
> 
> solved the error when running `brew cleanup`.
> Thanks!

This works with any formulae that has permission issues. It appears the brew cleanup process fails to process any further if `Error: Directory not empty @ dir_s_rmdir -...` is produced at any time. After the affected directories permissions were updated, I was able to cleanup almost 5-6G of old files.

**Comment by mertasan** [comment]
`sudo -rf /usr/local/Cellar/python/3.7.7`

**Comment by Meuko** [comment]
> Similar problem for a 3.7.7 python env installed via brew.
> The following:
> 
> ```
> chown -R MyUser:staff /usr/local/Cellar/python/3.7.7
> ```
> 
> solved the error when running `brew cleanup`.
> Thanks!

Also worked for
`Error: Directory not empty @ dir_s_rmdir - /usr/local/Cellar/gdb/10.1_1`

**Comment by Wiruu** [comment]
I've been removing this by sudo force since the beginning but I don't get how people's solution is to chown stuff, and mine isn't... anyone out there with the same issue?

**Comment by iDevelop25** [comment]
> Similar problem for a 3.7.7 python env installed via brew. The following:
> 
> ```
> chown -R MyUser:staff /usr/local/Cellar/python/3.7.7
> ```
> 
> solved the error when running `brew cleanup`. Thanks!

Thanks bro, that solve me the problem.
