### ISSUE TITLE
error Cannot add PPA: 'ppa:certbot/certbot'.

### ISSUE THREAD

**Issue by mordechaihorowitz** [certbot/certbot#6260]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 14.04

## I ran this command and it produced this output:
sudo add-apt-repository ppa:certbot/certbot

Cannot add PPA: 'ppa:certbot/certbot'.

## Certbot's behavior differed from what I expected because:

I received an error message instead of installing the PPA

It appears the PPA is no longer supported.  Is there an alternative to install certbot?

**Comment by bmw** [comment]
Can you try again, following the instructions generated at https://certbot.eff.org after selecting your web server and OS? The [PPA still has Ubuntu 14.04 packages](https://launchpad.net/~certbot/+archive/ubuntu/certbot) and I just successfully spun up a Ubuntu 14.04 machine and installed Certbot from it.

**Comment by osirisinferi** [comment]
You might use the `-m` switch to get a lot of debug information, which might help the guys from `certbot` to help you with this problem:

`sudo add-apt-repository -m ppa:certbot/certbot`

Probably best to skim the output for possible privacy sensitive info and put the output in [a gist](https://gist.github.com/) and place the URL here. Or, place it directly here on the issue thread if it isn't that large.

**Comment by bmw** [comment]
This issue hasn't seen any updates in a long time and it seems to be more about `apt` or the PPA system than Certbot so I'm closing this. If you're still having trouble with this, I recommend making a post at https://community.letsencrypt.org.
