### ISSUE TITLE
Dependency management issue with requests

### ISSUE THREAD

**Issue by dlapiduz** [certbot/certbot#6262]
I am trying to get the Azure integration (https://github.com/certbot/certbot/pull/6261) finished and through CI but I am having a dependency management issue with the `requests` package during testing.

As you can see here https://travis-ci.org/certbot/certbot/jobs/408774623#L704, there seems to be an installation issue with the Azure libraries using an older version of `requests` and can't run the tests.

Does anyone have any ideas on how to fix this?

FWIW, the previous Azure PRs (from which this is based) didn't have this issue because they didn't have any tests.

**Comment by joohoi** [comment]
I replied in the PR, and am closing this issue in order to not to fragment the discussion, as I believe the PR is the correct place to try and solve the issue.
