### ISSUE TITLE
Enhacement - Better handling for ACME-DNS validation

### ISSUE THREAD

**Issue by Bizarrus** [certbot/certbot#6263]
When you try to obtain wildcard certificates, the validation process will be "blocked" with a deployment TXT record on DNS. Here, you must add the `_acme-challenge` key to your TXT records before you can continue.

The problem is, the process will be stopped here, you must explicit press enter to continue and with good luck, your DNS records are deployed in this time with the actual deploying key.

Why, certbot is here not asyncron or why these will not run in background?
DNS Records can be publish up to 48 hours - If you have lot of domains, you can not wait minutes or hours if the DNS records are published. The second problem is, you can run only one instance of certbot; If you want to create some certificates on the same time you must wait if the current validation process is finished.

My feature request contains a simple solution to handle the management of creation process. When you create a cert request for wildcards, the request will be stored under a request list.

For example, here we request a new wildcard certificat for the domain `*.example.com`:

```
./certbot-auto certonly --manual -d *.example.com --agree-tos --manual-public-ip-logging-ok --preferred-challenges dns-01 --server https://acme-v02.api.letsencrypt.org/directory
```

After this step, the request will be stored in an request-pool for future handling:

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for example.com

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Please deploy a DNS TXT record under the name
_acme-challenge.example.com with the following value:

12345ThIsIsYourKeyForDnS

Verify that the record is deployed. The certificate request will
be stored in your request list.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Press Enter to Finish
```

You can view the request pool with:

```
./certbot-auto certrequests
```

And it gives a pending list of actual requests:

```
You have currently following certificate requests:

Domain                                 Status                    Deployment Key
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
*.example.com                         [EXISTS]                12345ThIsIsYourKeyForDnS
*.anotherdomain.tld                [UNDEPLOYED]     TheValIdAtIonkeYForYOurDNs
[...]
```

Certbot will check automatically if the deployment key is available and create the certificate. Otherwise, you can check the request status:

```
./certbot-auto certrequests -d *.example.com

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for example.com

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Current DNS TXT record for _acme-challenge.example.com
are deployed with the following value:

12345ThIsIsYourKeyForDnS

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/example.com/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/example.com/privkey.pem
   Your cert will expire on YYYYYY-MM-DD. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot-auto
   again. To non-interactively renew *all* of your certificates, run
   "certbot-auto renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le
```

**Comment by lordspace** [comment]
I was thinking that there should be a better way as well.
Why not call a binary and pass some JSON to it and it can call and API to set the necessary TXT records.

**Comment by Bizarrus** [comment]
The changelog or commits contain no information as to whether this feature request has been implemented.

**Comment by Bizarrus** [comment]
Push for stale bot.

**Comment by prcmt** [comment]
This would be a very good quality of life improvement. As it is, hitting enter is risky business - will certbot see the updated record or not? If it hasn't, then it exits and you have to start the process again with a new TXT record.
