### ISSUE TITLE
Certbot should check where Apache vhosts directives are, not assume they're in external files

### ISSUE THREAD

**Issue by johnhorner** [certbot/certbot#6269]
## My operating system is (include version):

Ubuntu 14.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

sudo certbot --apache

## I ran this command and it produced this output:

Certbot created my <VHost> directive for the site correctly and placed it in the /etc/apache2/sites-enabled directory. However in my main apache2.conf file, the directive to include vhosts was commented out so this didn't work initially. I have all my vhosts configured in the main conf file, for reasons.

## Certbot's behavior differed from what I expected because:

Configuring your vhosts all within your apache2.conf file might be unusual but it's perfectly valid.

I would suggest that Certbot check whether the Include line for vhosts is commented out or not, and if it's commented out, created the directive inside the main conf file. And probably warn the user that they're not doing things the expected way.

**Comment by sydneyli** [comment]
@joohoi, what do you think about this?

**Comment by joohoi** [comment]
Thanks for opening the issue @johnhorner ! You are right here. Certbot currently relies on the distribution specific mechanisms for enabling `VirtualHosts`, for Debian and Ubuntu that is the `sites-enabled` - scheme. You have explicitly disabled this distribution specific behavior in your `apache2.conf`, and this is the reason Apache is not picking up the new configuration linked to `sites-enabled`.

That said, for general reliability and user experience, we could add a check to determine if this is the case with the current configuration, and if so, fall back to adding a direct `Include` or `IncludeOptional` directive to the root Apache configuration file. The feature request is completely reasonable.

**Comment by johnhorner** [comment]
This is still an issue. I just added a new certificate via certbot and it failed to detect that my vhosts are all configured in the main apache2.conf, not configured in separate files in the /etc/apache2/sites-available/ directory.

It's not a huge problem, and it's probably an unusual configuration, but it is a valid configuration and certbot shouldn't say "Congratulations! You have successfully enabled https <whatever>" because it hasn't.

Solutions:

1\) I suppose the absolute minimum you could do to ameliorate this problem is to document that certbot doesn't work on Apache configured this way.

2\) The next level would be to add a check to certbot to detect whether this line:

`IncludeOptional sites-enabled/*.conf`

is commented out and explain on screen that certbot won't work automatically if it is.
 
3\) The best solution would be to have certbot work on sites-enabled if it's in the config, and work on the apache2.conf if it isn't.

In the case of solutions 1) and 2) users who know what they're doing can just go to the file created and copy it into their main config. But only in the case of solution 3) does the system become usable for less technically-minded users.

**Comment by johnhorner** [comment]
I have used Certbot recently and yes, this is still a problem. 

It's not a bug. Certbot is currently coded on the assumption that domains are configured in external files. 

If they're not, which is a perfectly valid way of configuring Apache, then it doesn't work. It's not affecting my website or causing any more than a small delay, but it's still an issue.

**Comment by johnhorner** [comment]
Fine for it to be closed. The issue remains but can be worked around and I assume this content serves as an explanation.

**Comment by bmw** [comment]
Woah. Sorry @johnhorner. stale bot is supposed to notice your comment saying that you know this is still an issue, remove the `needs-update` label, and keep the issue open.

I'm reopening the issue and going to try and resolve the problem with the bot (or turn it off entirely if it doesn't behave).

**Comment by johnhorner** [comment]
I would consider this fixed if certbot simply commented something along the lines of

'your configuration doesn't use `sites-enabled/*.conf,` you're on your own'. 

A link to documentation would also be nice.

**Comment by johnhorner** [comment]
@bmw 

Not fixed. Certbot just assured me I had https-enabled a site when I hadn't.

I'm getting tired of repeating this every few months. This issue should either be fixed or closed as 'won't fix' or at least taken off stale-bot's list. But Certbot is absolutely, definitely, telling users that their sites are https-enabled when they're not, so I think you should fix it.

**Comment by johnhorner** [comment]
As I said last time, I'm getting tired of repeating the same thing. It's a bug, it's valid, it's still happening, it's confusing for users, but every time I respond to that effect, nothing happens.

**Comment by johnhorner** [comment]
If someone can point me to the section of code where it reads in/analyses the main `apache2.conf` file on Debian I will make a pull request.
