### ISSUE TITLE
certbot certificates should explain why it thinks configurations are invalid

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#6276]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 16.04.4 LTS (xenial)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt

## I ran this command and it produced this output:
```sh
$ certbot certificates
...
The following renewal configuration files were invalid:
  /etc/letsencrypt/renewal/mail.test.example.com.conf
```

## Certbot's behavior differed from what I expected because:
1. It should have told me *why* it was invalid -- the debug output for the renewal clearly explains that the files were expected to be symlinks.
1. It shouldn't say that the `configuration file is invalid`, it should say that the `configuration is invalid` -- the file itself is totally reasonable and anyone using `diff` to compare configuration files will be barking up the wrong tree.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
```
certbot.errors.CertStorageError: expected /etc/letsencrypt/live/mail.test.example.com/cert.pem to be a symlink
2018-07-23 09:37:06,826:WARNING:certbot.renewal:Renewal configuration file /etc/letsencrypt/renewal/mail.test.example.com.conf is broken. Skipping.
```

see also #2550

**Comment by Kelderic** [comment]
I just ran into this issue. I upgraded hardware and moved files wholesale. Apparently, the symlinks got broken. I spent a half hour trying to figure out why the "Configuration" was invalid.

A better error message would be to say that the symlinks aren't valid.
