### ISSUE TITLE
Error while install letsencrypt on zimbra centOS 7

### ISSUE THREAD

**Issue by arsyam** [certbot/certbot#6279]
Dear Master,

I want to ask, while i’am installing letsencrypt in my zimbra server (centOS 7) i get error like this :

[root@mail letsencrypt]# ./letsencrypt-auto certonly --standalone -d mail.domain.com -d mail.domain.id
Bootstrapping dependencies for RedHat-based OSes… (you can skip this with --no-bootstrap)
yum is /usr/bin/yum
yum is hashed (/usr/bin/yum)
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile

base: repo.apiknet.co.id
epel: mirror.smartmedia.net.id
extras: repo.apiknet.co.id
updates: repo.apiknet.co.id
Package gcc-4.8.5-28.el7_5.1.x86_64 already installed and latest version
Package augeas-libs-1.4.0-5.el7_5.1.x86_64 already installed and latest version
Package 1:openssl-1.0.2k-12.el7.x86_64 already installed and latest version
Package 1:openssl-devel-1.0.2k-12.el7.x86_64 already installed and latest version
Package libffi-devel-3.0.13-18.el7.x86_64 already installed and latest version
Package redhat-rpm-config-9.1.0-80.el7.centos.noarch already installed and latest version
Package ca-certificates-2018.2.22-70.0.el7_5.noarch already installed and latest version
Package python-devel-2.7.5-69.el7_5.x86_64 already installed and latest version
Package python-virtualenv-15.1.0-2.el7.noarch already installed and latest version
Package python-tools-2.7.5-69.el7_5.x86_64 already installed and latest version
Package python2-pip-8.1.2-6.el7.noarch already installed and latest version
Nothing to do
WARNING: unable to check for updates.
Creating virtual environment…
Installing Python packages…
Had a problem while installing Python packages.
pip prints the following errors:
Collecting argparse==1.4.0 (from -r /tmp/tmp.6suvdqmxwN/letsencrypt-auto-requirements.txt (line 11))
Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by ‘NewConnectionError(’<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe3f672add0>: Failed to establish a new connection: [Errno 101] Network is unreachable’,)’: /simple/argparse/
Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by ‘NewConnectionError(’<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe3f672a350>: Failed to establish a new connection: [Errno 101] Network is unreachable’,)’: /simple/argparse/
Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by ‘NewConnectionError(’<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe3f672a9d0>: Failed to establish a new connection: [Errno 101] Network is unreachable’,)’: /simple/argparse/
Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by ‘NewConnectionError(’<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe3f672a4d0>: Failed to establish a new connection: [Errno 101] Network is unreachable’,)’: /simple/argparse/
Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by ‘NewConnectionError(’<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe3f672a6d0>: Failed to establish a new connection: [Errno 101] Network is unreachable’,)’: /simple/argparse/
Could not find a version that satisfies the requirement argparse==1.4.0 (from -r /tmp/tmp.6suvdqmxwN/letsencrypt-auto-requirements.txt (line 11)) (from versions: )
No matching distribution found for argparse==1.4.0 (from -r /tmp/tmp.6suvdqmxwN/letsencrypt-auto-requirements.txt (line 11))
Certbot has problem setting up the virtual environment.

We were not be able to guess the right solution from your pip
output.

Consult https://certbot.eff.org/docs/install.html#problems-with-python-virtual-environment
for possible solutions.
You may also find some support resources at https://certbot.eff.org/support/ .

Please help me ! :frowning:

Regards,
Arie

**Comment by bmw** [comment]
`letsencrypt-auto` is encountering network issues trying to download packages from https://pypi.python.org. I recommend you make a post at https://community.letsencrypt.org where there is a large community of users familiar with the project who should be able to help you identify and fix the problem.

**Comment by arsyam** [comment]
I have posted a link: https://community.letsencrypt.org/t/error-while-install-letsencrypt-on-zimbra-centos-7/68334
but there is no answer.
