### ISSUE TITLE
--dry-run should not change mtime of letsencrypt directory

### ISSUE THREAD

**Issue by vbotka** [certbot/certbot#6281]
## My operating system is (include version):
uname -a
FreeBSD srv.example.com 11.2-RELEASE FreeBSD 11.2-RELEASE #0 r335510: Fri Jun 22 04:32:14 UTC 2018     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
py27-certbot-0.25.1,1

## I ran this command and it produced this output:

$ ll /usr/local/etc | grep letsencrypt
drwxr-xr-x  11 root  wheel    512 Aug  3 08:39 letsencrypt/

$ date
Fri Aug  3 08:40:45 UTC 2018

$ certbot certonly --standalone --dry-run -d example.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Cert not due for renewal, but simulating renewal for dry run
Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for example.com
Waiting for verification...
Cleaning up challenges
IMPORTANT NOTES:
The dry run was successful.

$ ll /usr/local/etc | grep letsencrypt
drwxr-xr-x  11 root  wheel    512 Aug  3 08:41 letsencrypt/

## Certbot's behavior differed from what I expected because:

"certbot certonly --dry-run ..." changed the modification time of the directory letsencrypt. There are no changes inside the directory letsencrypt, hence there is no reason to change the mtime. Probably it would be good to wipe out the changes with utime after the operation when the dir is needed for a temporary purpose.

IDS complains about changed mtime.

**Comment by sydneyli** [comment]
This is probably because lock configuration directory (by creating and removing a file) when Certbot is run. In some specific cases, `dry-run` can cause changes in a subdirectory like `accounts` as well.

Resetting the modification time of a directory that was actually modified seems odd and opaque to me. Could you instead monitor changes on other subdirectories that shouldn't be touched by `dry-run`-- for instance, `live` (where the certs live), `keys`, and maybe even the `renewal` subdirectories?

**Comment by vbotka** [comment]
Yes. IDS monitor letsencrypt subdirectories recursively. --dry-run changes the letsencrypt directory only. As of "odd and opaque" to me is to use etc for [locking](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s09.html). As of "feature request" shouldn't the report be labeled "Feature request: Make Certbot LSB compliant" ?

**Comment by sydneyli** [comment]
there was a large discussion around whether to use `/var/lock` (most of which can be found in #4449, if you're curious). a primary concern was to not break several existing renewal workflows, meaning we had to support existing integrations which include using `certbot` without root permissions.

@bmw,

**Comment by vbotka** [comment]
I wonder that this is something to discuss. [/etc ... must be static](https://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/etc.html) and [/var contains variable data](https://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/var.html). With all implications and consequences.

**Comment by bmw** [comment]
Unfortunately, Certbot doesn't exactly follow the Linux FHS. While I don't think there is a single directory that is standard for lockfiles across all UNIX systems (see [FreeBSD](https://www.freebsd.org/cgi/man.cgi?query=hier&sektion=7) for instance), you could argue that putting the lockfile somewhere in `/var` is standard. We had problems with this which are explained at the bottom of https://github.com/certbot/certbot/pull/4449#issuecomment-292578050.

While I'm sorry for the trouble and would be open to changing this in the future, I don't think we want to break backwards compatibility by moving the lockfile to another location right now.

**Comment by sydneyli** [comment]
> While I'm sorry for the trouble and would be open to changing this in the future, I don't think we want to break backwards compatibility by moving the lockfile to another location right now.

Closing this issue!
