### ISSUE TITLE
certbot renew should tell you what to do when attempting to renew certs after an upgrade

### ISSUE THREAD

**Issue by teo1978** [certbot/certbot#6286]
I had installed the older version of certbot following the instructions for Debian 7 on... a debian 7 system. And I had generated some certificates which are working fine.
Then I upgraded to debian 8, so I deleted the old version of certbot, and I installed the new one via apt-get.

Now when I run `certbot renew`, I get this warning:
```
Attempting to parse the version 0.26.1 renewal configuration file found at /etc/letsencrypt/renewal/www.matteosistisette.com.conf with version 0.10.2 of Certbot. This might not work.
```
Of course it makes sense, but the error message should also tell me what I'm supposed to do to update the configuration file so that it's compatible with the new version and I stop getting this error.

**Comment by sydneyli** [comment]
There's not much that we can recommend you do here, since you were using `certbot-auto` before (which performs automatic updates of the software) and Debian 8 packages an old version of `certbot`. It's just a warning, so you can use the `--quiet` flag to silence it on future runs.

**Comment by teo1978** [comment]
> you were using certbot-auto before (which performs automatic updates of the software) and Debian 8 packages an old version

Oh, I hadn't realized it wasn't the other way round. I thought the version I had been using before was older.

Then issue 6285 applies.

**Comment by sydneyli** [comment]
Ok, I'll respond to you there!
