### ISSUE TITLE
Certbot does not give you the option to specify challenge for domain

### ISSUE THREAD

**Issue by ShadowJonathan** [certbot/certbot#6287]
## My operating system is (include version):
`uname -a` output:
`Linux JON-LINUX 4.9.0-6-686-pae #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) i686 GNU/Linux`

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager, `apt`

## I ran this command and it produced this output:
`certbot --server https://acme-v02.api.letsencrypt.org/directory certonly -d domain.tld,*.domain.tld --preferred-challenges dns-01,http-01 --manual --manual-public-ip-logging-ok`
```bash
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Cert is due for renewal, auto-renewing...
Renewing an existing certificate
Performing the following challenges:
dns-01 challenge for domain.tld
dns-01 challenge for domain.tld

-------------------------------------------------------------------------------
Please deploy a DNS TXT record under the name
_acme-challenge.domain.tld with the following value:

[REDACTED]

Before continuing, verify the record is deployed.
-------------------------------------------------------------------------------
Press Enter to Continue

-------------------------------------------------------------------------------
Please deploy a DNS TXT record under the name
_acme-challenge.domain.tld with the following value:

[REDACTED]

Before continuing, verify the record is deployed.
-------------------------------------------------------------------------------
Press Enter to Continue
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. domain.tld (dns-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect TXT record "[REDACTED]" found at _acme-challenge.domain.tld

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: domain.tld
   Type:   unauthorized
   Detail: Incorrect TXT record
   "[REDACTED]" found at
   _acme-challenge.domain.tld

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
```

(domain has been replaced with `domain.tld`, and DNS-01 challenge strings redacted)

## Certbot's behavior differed from what I expected because:
It does not allow me to specify the challenge per domain.

Certbot is wonderful, however I am trying to register a normal domain and a wildcard domain at the same time in the same certificate for convenience, I should be able to specify a challenge for the normal domain while having a dns-01 for the wildcard.

However, certbot places a dns-01 on *both* of the domains, which are basically on the same level, requiring the same TXT record to have both values at the same time, which creates an impossible situation where a record needs to have both values at the same time.

**Comment by sydneyli** [comment]
You can set multiple TXT records on the same domain. See #5729 and https://community.letsencrypt.org/t/wildcard-base-domain-two-txts-timeout-problem/56105/3 for more information!

This isn't a Certbot bug, so I'm closing it, but if you have further issues obtaining a wildcard cert feel free to post on [our community forums](https://community.letsencrypt.org/c/help), where there's a large audience familiar with the project and may be able to help you faster!
