### ISSUE TITLE
Document OS dependencies needed to build docs in Developer Guide

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6288]
For latex and PDF docs, there's a lot. See #6070.

There are also dependencies on things like `make` which the user probably already has, but we should document for completeness.

**Comment by thejessleigh** [comment]
It looks like there's a merged PR for this issue. Can we close this out?

**Comment by bmw** [comment]
What PR are you referring to? If it's #6070, I created this issue after merging that PR to track future work.

**Comment by thejessleigh** [comment]
Oh, okay. I got emailed this issue as part of Code Triage, and it seemed like it might be outdated. Sorry about that!

**Comment by bmw** [comment]
This is still an issue stale bot.
