### ISSUE TITLE
add --http-propagation-seconds / hook after placing the files

### ISSUE THREAD

**Issue by mokraemer** [certbot/certbot#6289]
if you run multiple servers it can take some time to deploy the files between them.
It would be really helpful if certbot waits for some time after placing the files and doing the verification.

**Comment by mokraemer** [comment]
thanks for your reply. This seems to work. I hope automated renewal also works with manual mode.

**Comment by joohoi** [comment]
> I hope automated renewal also works with manual mode.

It works perfectly fine when used with `--manual-auth-hook`. Just make sure you don't accidently remove the auth hook script.

As I feel the issue was resolved, I'm closing it for now, feel free to add comments if you think we should reopen or continue the discussion.
