### ISSUE TITLE
certbot-auto --help shouldn't update

### ISSUE THREAD

**Issue by madfordmac** [certbot/certbot#6291]
## My operating system is (include version):
Debian 8

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
```
$ sudo /usr/local/sbin/certbot-auto --help
[sudo] password for alex: 
Upgrading certbot-auto 0.24.0 to 0.26.1...
Replacing certbot-auto...
Creating virtual environment...
Installing Python packages...
Installation succeeded.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  certbot-auto [SUBCOMMAND]
```
[_Help output continues._]

## Certbot's behavior differed from what I expected because:
Trying to get the help output to get the syntax correct on the actual command you want to run is not the time you want to sit and wait several minutes for the script to update and rebuild its virtual environment. The ```--help``` flag should bypass the update check. Let it update when I run a real command that I'm expecting to take a little bit of time.

## Here is a Certbot log showing the issue (if available):
N/A; logs aren't written when you request help.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
N/A

**Comment by sydneyli** [comment]
Thanks for reporting-- this seems like a reasonable thing to expect when passing in the `help` or `version` flags, unless `certbot` is not yet installed. Any thoughts on this @bmw?

**Comment by bmw** [comment]
I agree this is a little awkward. My main concern about changing this behavior though is that the help text you receive will be outdated when you go to run another command. Certbot is adding and deprecating features fairly regularly so being able to get the help output from the version of Certbot you will be running when you run a real command is kind of valuable.

**Comment by madfordmac** [comment]
How about a warning that you're not current, but don't automatically update. Maybe give the command to trigger an update?

In my case, this is the one host that certbot is not in cron for reasons, and I was thinking something along the lines of, "Is it update? Renew? There's an option I need to pass, isn't there?" I just wanted help on basic functionality.

**Comment by bmw** [comment]
I see. While we could do something like that, I think I'd personally prefer we err on the side of showing up to date instructions and we have already implemented a flag to **not** trigger an update which is `--no-self-upgrade`.

Does this option work for you or would you still like to see a change here?

**Comment by madfordmac** [comment]
For me, I wouldn't know that ``--no-self-upgrade`` was an option until I ran ``--help``. So that's not really helpful.

I admit I am probably the most basic of certbot users. 99% of what I do is just letting it run from cron. If you think the larger fraction of the user base would prefer to see the most current options, I can accept that determination.

**Comment by bmw** [comment]
That's true. With my approach, users who don't want the upgrade will probably have to upgrade once before finding the documentation for the `--no-self-upgrade` flag. It's a trade off and I personally still have the same preference.

@sydneyli, do you have an opinion here?

**Comment by bmw** [comment]
Actually, my preference for the current behavior is pretty strong so I'm going to close this issue as won't fix. Thanks for opening the issue to make sure we thought through this and sharing your thoughts though!

Sydney, sorry for the ping. If you strongly disagree with me, please speak up!
