### ISSUE TITLE
feature request: certbot-nginx: enable http/2 by default

### ISSUE THREAD

**Issue by yw662** [certbot/certbot#6301]
## My operating system is (include version):
Ubuntu 18.04.1 LTS GNU/Linux 4.15.0-20-generic x86_64

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt

## I ran this command and it produced this output:
certbot --nginx --redirect --agree-tos --no-eff-email

## Certbot's behavior differed from what I expected because:
It should be `listen 443 ssl http2; # managed by Certbot`
but it is `listen 443 ssl; # managed by Certbot`

**Comment by jgillula** [comment]
@joohoi Is this something we think we could write an optional enhancement for?

**Comment by joohoi** [comment]
It certainly is, and applies for Apache plugin as well. Something to keep in mind though: I believe some of the older distribution versions that we support, ship Nginx and Apache compiled against OpenSSL < 1.0.2, making them unable to reliably serve HTTP/2 as those versions lack support for ALPN that is the only accepted method for modern clients.

**Comment by schoen** [comment]
Maybe there will also be a possibility to write an enhancement activating TLS 1.3 support?

https://github.com/certbot/certbot/issues/6308

If so, it would have the same problem that many supported older web servers wouldn't immediately (or ever) receive software support.

**Comment by mnordhoff** [comment]
This is still an issue, stale bot.

**Comment by lenormf** [comment]
An opt-in way to set HTTP2 — or better make it default and let users opt into HTTP1 - would be great.
