### ISSUE TITLE
Integration tests should fail fast if Python isn't in your PATH

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6303]
If `python` isn't in your PATH (but is findable by the Certbot executable because it has its own version of Python), the tests fail very late with a confusing error message as seen at https://paste.ubuntu.com/p/2vjtPksBtH/.

We should add a simple check to this at the top of `tests/boulder-integration.sh`.

**Comment by adferrand** [comment]
Here you go.

**Comment by bmw** [comment]
Fixed in #6306.
