### ISSUE TITLE
Integration tests should pass with both new and old versions of openssl

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6304]
In [tests/boulder-integration.sh](https://github.com/certbot/certbot/blob/d8057f0e17dc757fae662dad91a6fedc96ad6a2d/tests/boulder-integration.sh#L394), we check that a certificate we obtained contains the must-staple extension. How `openssl` shows this depends on its version though. Instead of the pattern currently shown in the file, newer versions print `status_request`.

We should check for both versions in `openssl`'s output and pass if either are present.

**Comment by bmw** [comment]
@adferrand is going to take this

**Comment by adferrand** [comment]
I take this

**Comment by bmw** [comment]
Fixed in #6450.
