### ISSUE TITLE
TLS v1.3 when?

### ISSUE THREAD

**Issue by ghost** [certbot/certbot#6308]
Since TLSv1.3 has a [RFC doc](https://tools.ietf.org/html/rfc8446) now, is there already an ETA to include it?

OpenSSL should release it the next weeks https://github.com/openssl/openssl/milestone/9

**Comment by schoen** [comment]
Hi @luca-exe , are you looking for Certbot to automatically reconfigure Apache or nginx (or both) to use TLS 1.3 once software support for it is part of the official releases? Or some other application of TLS 1.3 in another context?

**Comment by luca-exe** [comment]
Yeah exactly :)
I wanted to know an ETA for when it is part of the official releases.

**Comment by schoen** [comment]
The submitting user's account no longer exists.

I created an issue #6367 to track the security enhancement request, and I'll close this issue in favor of that one.
