### ISSUE TITLE
Can't save certbot-auto error/success domain validation logs to file

### ISSUE THREAD

**Issue by youarelev** [certbot/certbot#6312]
## My operating system is (include version):
Ubuntu 16.04.4 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
wget https://dl.eff.org/certbot-auto

## I ran this command and it produced this output:
certbot-auto certonly ... > "/path/to/my/file.logs"
and file contains only:
...
Setting up gcc-7 (7.3.0-16ubuntu3) ...
Setting up gcc (4:7.3.0-3ubuntu2) ...
Setting up python3-virtualenv (15.1.0+ds-1.1) ...
Setting up virtualenv (15.1.0+ds-1.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Creating virtual environment...
Installing Python packages...
Installation succeeded.

## Certbot's behavior differed from what I expected because:
I get error that "too many certificates already issued for exact set of domains: ...". I want see this part of command line logs in my "/path/to/my/file.logs" too. Is it possible to do?

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
-

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
-

## Why I need this?
I have built Docker image with certbot-auto and cron tools inside. Cron is checking if certificate was generated >= 80 days ago and generate it if >= than 80 days. I know about cert lifetime 90 days, just want to have 10 days to generate it manually if something went wrong. Let's imagine this "something went wrong" happens. I want see full logs in "/path/to/my/file.logs" file.

**Comment by ohemorange** [comment]
Hello! This is possible with the current implementation of Certbot, so I'd recommend posting on the community forum where a larger number of people are available to help you with your particular setup: https://community.letsencrypt.org/
