### ISSUE TITLE
https://dl.eff.org Cert is expired and you can't download certbot-auto

### ISSUE THREAD

**Issue by gullevek** [certbot/certbot#6313]
Major problem, you can't download the certbot-auto or anything because the cert on dl.eff.org is expired. So you can't download it at all as there seems to be no alternate mirrors.

## My operating system is (include version):

CentOS 6

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Try to wget it

## I ran this command and it produced this output:

```
# wget http://dl.eff.org/certbot-auto
--2018-08-22 09:17:48--  http://dl.eff.org/certbot-auto
Resolving dl.eff.org... 151.101.72.201, 2a04:4e42:11::201
Connecting to dl.eff.org|151.101.72.201|:80... connected.
HTTP request sent, awaiting response... 503 certificate has expired
2018-08-22 09:17:49 ERROR 503: certificate has expired.
```

OR via web

```
Error 503 certificate has expired

certificate has expired
Guru Mediation:

Details: cache-hnd18749-HND 1534897431 4156288774

Varnish cache server
```

## Certbot's behavior differed from what I expected because:

I expected the certbot script, but I got nothing :(

**Comment by arturgvieira** [comment]
Same here. I tweeted about it but haven't heard back either.

**Comment by arturgvieira** [comment]
Hi @bmw, thank you for the response.

**Comment by bmw** [comment]
This has been resolved. Sorry for the trouble!
