### ISSUE TITLE
CentOS 7 Python Conflict

### ISSUE THREAD

**Issue by dave-lew99** [certbot/certbot#6314]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
CentOS 7

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS Package Manager, from EPEL

## I ran this command and it produced this output:
yum install epel-release
yum install awscli certbot certbot-dns-route53

....   file /usr/lib/python2.7/site-packages/s3transfer/__init__.py conflicts between attempted installs of python-s3transfer-0.1.10-8.el7.noarch and python2-s3transfer-0.1.10-1.el7.noarch ....

## Certbot's behavior differed from what I expected because:
It seems certbot-dns-route53 plugin cannot currently be installed alongside the awscli on CentOS 7. This seems to be due to conflicts in python packages from CentOS base and Epel. I'm unsure who can fix/who is responsible for this as it's not clear if it's a Certbot issue or a repo issue. It seems to be related to this https://bugzilla.redhat.com/show_bug.cgi?id=1578071

**Comment by jgillula** [comment]
@bmw This seems like something for the CentOS packagers, right?

**Comment by bmw** [comment]
Yep! @elyscape, do you have any guidance here?

**Comment by elyscape** [comment]
As per https://bugzilla.redhat.com/show_bug.cgi?id=1578071#c5, the EPEL-provided python2-s3transfer is now causing conflicts with the new, upstream-provided python-s3transfer package. I'm working with the other EPEL maintainers to try to get this resolved.

**Comment by elyscape** [comment]
In the meantime, you can work around this by running `yum swap python2-s3transfer python-s3transfer`.

**Comment by elyscape** [comment]
Not yet, unfortunately. I'm still working on it.
