### ISSUE TITLE
dry-run successful / real run fails 

### ISSUE THREAD

**Issue by marxenegls** [certbot/certbot#6316]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.
why was the dry-run successful but the real one a fail ?

## My operating system is (include version):
debian raspbian
armv7
## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-apache certbot  -backports stretch
it failed so upgraded 
then used certbot-auto to upgrade it installed ok and set python3 venv etc etc 

which certbot
 /usr/bin/certbot 

dry-run 
Waiting for verification...
Cleaning up challenges
Generating key (2048 bits): /etc/letsencrypt/keys/0001_key-certbot.pem
Creating CSR: /etc/letsencrypt/csr/0001_csr-certbot.pem
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)

Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/nesting-homeis.net/fullchain.pem (success)
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates above have not been saved.)

## I ran this command and it produced this output\:
real run\:
usr/lib/python2.7/dist-packages/OpenSSL/rand.py:58: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  result_code = _lib.RAND_bytes(result_buffer, num_bytes)
Waiting for verification...
Cleaning up challenges
Attempting to renew cert from /etc/letsencrypt/renewal/nest.net.conf produced an unexpected error: Failed authorization procedure. black.nest.net (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Error getting validation data
:
it seems the upgrade happened but i'm still using python2.7 + the older version of certbot acmev1
huh ?
## Certbot's behavior differed from what I expected because:
sure did..., left me boggled too 
###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 77, in get_authorizations
    self._respond(resp, best_effort)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 134, in _respond
    self._poll_challenges(chall_update, best_effort)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 198, in _poll_challenges
    raise errors.FailedChallenges(all_failed_achalls)
FailedChallenges: Failed authorization procedure. black.nest.net (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Error getting validation data, brown.nest.net (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Error getting validation data, red.nest.net (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Error getting validation data

2018-08-23 19:50:26,071:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "./certbot", line 11, in <module>
    load_entry_point('certbot==0.10.2', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 849, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 655, in renew
    renewal.handle_renewal_request(config)
  File "/usr/lib/python2.7/dist-packages/certbot/renewal.py", line 430, in handle_renewal_request
    len(renew_failures), len(parse_failures)))
Error: 1 renew failure(s), 0 parse failure(s)

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

i wanted to certs for hosts.domain i used standalone to generate the now outdated certs and it worked 
four hosts (docker swarm)
yesterday resolution of the other three failed now,today  i see that one of those three failed validation hosts is actually the host itself certbot is running on ..
i specifically installed dnsmasq to help with local subnet and domain resolution , plus i'm using my noip dyndns straight off the router which is in a dmz 

 
where did the upgrade install if not /usr/bin/certbot ?
in the same dir certbot is packaged in ?? no

**Comment by bmw** [comment]
> why was the dry-run successful but the real one a fail ?

This is tracked in https://github.com/certbot/certbot/issues/5116. The short version is you have a cached validation with Let's Encrypt's staging server (which is used with `--dry-run`) but not their production server. As a result, their production server is actually checking you are performing the challenge correctly but their staging server with `--dry-run` is not.

> where did the upgrade install if not /usr/bin/certbot ?

If you installed using `certbot-auto`, you should continue to use that script to run Certbot. To satisfy your curiosity, it installed Certbot in `/opt/eff.org`, but you shouldn't run Certbot from there and should instead continue to use the `certbot-auto` wrapper script.

Since this isn't clearly a problem with Certbot, I'm going to close this issue. Per our issue template, you should ask for help at https://community.letsencrypt.org/ first. There is a much larger community there of people familiar with the project who will be able to more quickly answer your questions.

**Comment by marxenegls** [comment]
holy cannoli ...ok 
would a thank you still count in this case or not 
i'd offer you a beer if you were near , a Belgian One
