### ISSUE TITLE
Stop preferring TLS-SNI in the Apache, Nginx, and standalone plugins

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6319]
We should still offer the challenge for now, but we should change the order they are returned in `get_chall_pref` so HTTP-01 comes before TLS-SNI-01. TLS-SNI-01 is going away.

**Comment by DimaVIII** [comment]
Yes absolutely necessary! Just run into this issue.
``` The client lacks sufficient authorization :: Incorrect validation certificate for tls-sni-01 challenge. Requested XXXXXXXXXX.acme.invalid from XXX.XXX.XXX.XXX:443. Received 1 certificate(s), first certificate had names "hostmaster", blog.XXX.XX (tls-sni-01):```

If there is a self-signed Cert installed on the IP of the the host machine, challenges will fail. 
This forced me to include "--preferred-challenges http" in every certbot call.

**Comment by bmw** [comment]
We're planning on blocking this on https://github.com/certbot/certbot/issues/5763 and https://github.com/certbot/certbot/issues/5764.
