### ISSUE TITLE
certbot_dns_rfc2136 authenticator not working programming bug

### ISSUE THREAD

**Issue by unioncos** [certbot/certbot#6322]
My edit solution at https://github.com/certbot/certbot/issues/6294 is wrong. the certbot_dns_rfc2136 authenticator is not working properly after all. When if successfully adds the TXT record it does not flush the record to the zone file/ this can be observed by doing a " rndc sync -clean " while waiting ion the TXT record to propagate. /when it goes to clean up the challenge the same occurs - it stops in the jnl file until a rndc sync -clean is done

This is programming issue I cannot configure around and it does not appear any setup will cure

**Comment by sydneyli** [comment]
Hi @unioncos -- thanks for reporting!

My understanding is that [dynamic DNS updates](https://ftp.isc.org/www/bind/arm95/Bv9ARM.ch04.html#dynamic_update) are not supposed to be immediately flushed to the master zone file after every update; you can use `rndc sync -clean` to force that flush, but that shouldn't have any affect on how your zones are resolving. 

I tried the authenticator myself just now and it seems to be working. What exactly is going wrong? Could you fill out the issue template so we can help you debug or determine whether this is a Certbot issue? We also rely on [dnspython](https://github.com/rthalley/dnspython) to perform `nsupdate`s in this plugin, so this could be an upstream problem, or it could be an issue with your DNS setup.

If you need help debugging your DNS setup in general, I'd recommend posting on the [LetsEncrypt community forums](https://community.letsencrypt.org/c/help), where there's a larger audience of people who are also familiar with the project! You might get faster help there :D

**Comment by unioncos** [comment]
I do not know where the issue template is but assuming it is the one at the head of a new issue head is he answers

## My operating system is (include version):

Centos 7 current 7.5.1804 - 4 core VPS Open VZ  Apache 2.4.34 (CodeIT) with php-frpm running php 5.6.37

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
 YUM

certbot.noarch                      0.26.1-2.el7                   @epel
python2-certbot.noarch              0.26.1-2.el7                   @epel
python2-certbot-apache.noarch       0.26.1-1.el7                   @epel-testing
python2-certbot-dns-rfc2136.noarch  0.26.1-1.el7                   @epel

AND I have these installed

python-dns.noarch                   1.12.0-4.20150617git465785f.el7
python2-certbot-dns-rfc2136.noarch  0.26.1-1.el7                   @epel
python2-dns-lexicon.noarch          2.7.0-2.el7                    @epel-testing
wbm-virtualmin-slavedns.noarch      2:1.8-1                        @virtualmin-universal

## I ran this command and it produced this output:

certbot certonly --dry-run --dns-rfc2136 --dns-rfc2136-credentials /credentials.ini -d "*.xxxxxxx.com" -d xxxxxxx.com --server https://acme-v02.api.letsencrypt.org/directory

The log already had this from cron running a renewals check

Description: Apache Web Server plugin - Beta
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.entrypoint:ENTRYPOINT
Initialized: <certbot_apache.override_centos.CentOSConfigurator object at 0x7f4d32a91a90>
2018-09-10 02:30:59,662:DEBUG:certbot.plugins.storage:Plugin storage file /etc/letsencrypt/.pluginstorage.json was empty, no values loaded
2018-09-10 02:30:59,663:DEBUG:certbot.renewal:no renewal failures

When I ran the above command it produced this new as a result

2018-09-10 15:49:13,207:INFO:certbot.auth_handler:Performing the following challenges:
2018-09-10 15:49:13,207:INFO:certbot.auth_handler:dns-01 challenge for xxxxxxx.com
2018-09-10 15:49:13,207:INFO:certbot.auth_handler:dns-01 challenge for xxxxxxx.com
2018-09-10 15:49:13,230:DEBUG:certbot_dns_rfc2136.dns_rfc2136:Received authoritative SOA response for _acme-challenge.xxxxxxx.com
2018-09-10 15:49:13,244:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 75, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 126, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/usr/lib/python2.7/site-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/lib/python2.7/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 76, in _perform
    self._get_rfc2136_client().add_txt_record(validation_name, validation, self.ttl)
  File "/usr/lib/python2.7/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 135, in add_txt_record
    .format(dns.rcode.to_text(rcode)))
PluginError: Received response from server: SERVFAIL

2018-09-10 15:49:13,244:DEBUG:certbot.error_handler:Calling registered functions
2018-09-10 15:49:13,244:INFO:certbot.auth_handler:Cleaning up challenges
2018-09-10 15:49:13,247:DEBUG:certbot_dns_rfc2136.dns_rfc2136:Received authoritative SOA response for _acme-challenge.xxxxxxx.com
2018-09-10 15:49:13,251:DEBUG:certbot_dns_rfc2136.dns_rfc2136:Successfully deleted TXT record
2018-09-10 15:49:13,264:DEBUG:certbot_dns_rfc2136.dns_rfc2136:Received authoritative SOA response for _acme-challenge.xxxxxxxx.com
2018-09-10 15:49:13,310:DEBUG:certbot_dns_rfc2136.dns_rfc2136:Successfully deleted TXT record
2018-09-10 15:49:13,310:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.26.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 1364, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 1254, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 115, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/lib/python2.7/site-packages/certbot/renewal.py", line 305, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 334, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 370, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 75, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 126, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/usr/lib/python2.7/site-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/lib/python2.7/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 76, in _perform
    self._get_rfc2136_client().add_txt_record(validation_name, validation, self.ttl)
  File "/usr/lib/python2.7/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 135, in add_txt_record
    .format(dns.rcode.to_text(rcode)))
PluginError: Received response from server: SERVFAIL

I used to get a .jnl file sitting in the /var/named directory and now no more

## Certbot's behavior differed from what I expected because:

See above

## Here is a Certbot log showing the issue (if available):
###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

See above

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

See above

I run my own DNS using Bind 9.9.4

bind.x86_64                         32:9.9.4-61.el7_5.1            @updates
bind-libs.x86_64                    32:9.9.4-61.el7_5.1            @updates
bind-libs-lite.x86_64               32:9.9.4-61.el7_5.1            @updates
bind-license.noarch                 32:9.9.4-61.el7_5.1            @updates
bind-utils.x86_64                   32:9.9.4-61.el7_5.1            @updates
rpcbind.x86_64                      0.2.0-44.el7                   @base

It is configured now to resolve to and forward to Googles public nameservers 8.8.8.8 and 8.8.4.4

My namerservers are ns1.zzzzzz.com and ns2.zzzzzz.com and have glue records to the public ips and reverse .in-addr.arpa pointing to them by the hosting company vps-dime.  I do not use their nameservers = they do not provide nameservers with the VPS accounts

A dig into the domain produces

xxxxxxxx.com.    9001    IN      A       xxx.xxx.xxx,.xxx

which is my server public IP

https://intodns.com  does not show any problems 

SELinux is disabled

If I run " setsebool -P named_write_master_zones 1 " it reports SELinux is disabled so this is not that issue

/var/named log reads general: error: /var/named/_acme-challenge.xxxxxxxx.com.db.jnl: create: permission denied

It appears to start with a permissions issue out of the box - but I do not know which permission is the issue

**Comment by sydneyli** [comment]
Thanks for following up! Sorry for the slow follow-up; as I mentioned in the previous comment, you'll probably get faster help for this sort of issue in the forums.

> When I asked at the community forums the poster of that info did not know how to do this for dtnamic update using the rfc2136 authenticator as shown here => https://community.letsencrypt.org/t/how-to-do-this-for-dns-01-challenge/70813

I wasn't able to follow this link-- is it broken?

During the 60 second waiting period, can you successfully `dig` the `TXT` challenge record from the perspective of one of your machines?

**Comment by unioncos** [comment]
I guess you cannot access it because https://community.letsencrypt.org/t/how-to-do-this-for-dns-01-challenge/70813 is a private message originated message volley

This is what it says

unioncos

At Renew using dns-01 challenge 1 you set out a procedure using a CNAME config from another domain

At step 2 you wrote

2.- When issuing a certificate with your client for external.tld , create a TXT record on your own DNS server pointing to the right token for external.tld

external.tld.own.tld IN TXT "here the token to validate external.tld"

How do I modify the zone file of the domain on “your own DNS” so the challenge TXT will go into an existing

external.tld.own.tld IN TXT “here the token to validate external.tld”

as you say

HIS REPLY

sahsanu
Community leader
22d
Hi @unioncos,

How do I modify the zone file of the domain on “your own DNS” so the challenge TXT will go into an existing external.tld.own.tld IN TXT “here the token to validate external.tld”

You only need to create a new TXT record for the subdomain external.tld.own.tld with the challenge value given by the client you are using (acme.sh, certbot, etc.).

How to do that will depend on the DNS server or DNS provider you are using.

Cheers,
sahsanu

MY REPLY 

unioncos
2 
21d
Hi and thanks for replying

I understand that . . . which you say but I am using BIND as my own nameserver on Centos 7 as BIND 9.9.4

You are saying basically to create a variable TXT field for nsupdate to populate the subdomain external.tld.own.tld

I am trying to do this for the challenge delivered by the certbot_dns_rfc2136 authenticator

Currently now today I am getting SERVFAIL errors and I do not know what is causing them

I have reviewed SERVFAIL - Wildcard DNS01 Bind 1 and SERVFAIL when using RFC 2136 plugin 1 and while I was getting jnl file writes yesterday which I had to flush to the zone file while certbot was running with a " rndc sync -clean " command in a separate terminal window, I get SERVFAIL today

There does not seem to be a complete howto to set up the rfc-2136 plugin to do automatic renewals

log output omitted - the SERVFAIL was a permission issue but still
not solve the jnl file matter

HIS FINAL REPLY

sahsanu
Community leader
20d
Hi @unioncos,

I’m sorry but I’ve never used certbot-dns-rfc2136 plugin nor configured bind to allow dynamic updates so I’ve no idea what is going on. My advice, create a new topic with all the info, commands you are using, their output and your bind configuration, I know there are several buddies in this forum using this kind of authentication and could help you out.

Cheers,
sahsanu

As to the DIG question 

NO . . . TXT unless I do a " rndc sync -clean " AND restart BIND and then the DIG shows them and the dry-run is successful - BUT NOT unless I restart BIND during the 60 second prorogation and have done a do a " rndc sync -clean " before the restart before the 60 seconds expires

**Comment by sydneyli** [comment]
Thanks for your responses! Gonna continue the thread here: https://community.letsencrypt.org/t/cname-config-and-rfc2136-authenticator-config/71965 and try and narrow down the issue!

**Comment by sydneyli** [comment]
(I'll re-open or you can feel free to file a new ticket once we've narrowed down the problem a bit!)

**Comment by unioncos** [comment]
https://community.letsencrypt.org/t/cname-config-and-rfc2136-authenticator-config/71965/2 has come to a conclusion for now

I believe that there are two bugs and one issue that needs to be addressed

The first thing on it completes a dry run and fails on the actual run

The second is it calls the same challenge txt twice and fails

The issue address is the documentation reveal nsupdate set up issues

Reading the entire gives lots of information about the process of this issue 
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 9/19/2018, 9:36 AM sydneyli <notifications@github.com> wrote:
Thanks for following up! Sorry for the slow follow-up; as I mentioned in the previous comment, you'll probably get faster help for this sort of issue in the forums.

When I asked at the community forums the poster of that info did not know how to do this for dtnamic update using the rfc2136 authenticator as shown here => https://community.letsencrypt.org/t/how-to-do-this-for-dns-01-challenge/70813

I wasn't able to follow this link-- is it broken?
During the 60 second waiting period, can you successfully dig the TXT challenge record from the perspective of one of your machines?

**Comment by unioncos** [comment]
Two people have contacted me directly to ask if I was successful in gettint it to work becasue they have the same problem.  To be honest I was surprised that people who answer at the community forum are not more knowledgable on the rfc2136 authetnicator setup issues which have to do with the Distribution of the Linux OS one is running and thus how BIND is installed as configured by it or the file that installed BIND as well as if even it is being runn as chroot

 

Osiris simply stated he could not figure out why his worked and mine was dongng strange things and mnordhoffCommunity Moderator simpoly stated he had no clue and wanted me to pastebin everything

 

The configuration page at https://certbot-dns-rfc2136.readthedocs.io/en/latest/ needs to be edited to reflect this and it would save a lot of question asking on the forum

 

I replied to them as follows =and someone should be able to use this with teh post volley to modify the documentation page

 

PASTE OF MY REPLY STARTS


See CNAME config and rfc2136 authenticator config

The issue surrounds what kind of server OS you are running and thus how BIND is configured when it is installed

The RedHat RPM based distributions like CentOS, Fedora, Red Hat Enterprise Linux (RHEL) and Mandrake also I believe have a BIND installation from RPM that usually comes with a /var/named/dynamic directory that should be used and the others use an etc/bind installation which does not have the directories and files nsupdate NEEDS to use configured with GROUP WRITE permissions

If you have a RedHat based distribution then google " /var/named/dynamic directory " and it will point you in the right direction with the searches that return - AND if you have another type of distribution like Debian, Ubuntu etc the first thing to do is make sure the GROUP WRITE permissions exist for BOTH the directory where the zone file is located and on the zone file itself also and make sure the server is otherwise setup to allow dynamic updates - which is can use nsupdate/

the post above has mostly all the info you need to get it working or tell what is wrong

Lastly, even though I got certbot working on the dry-run it still failed on the actual run for the cert and I had to restart BIND anyway while the propagation period was waiting

Restarting BIND will both flush the .jnl file changes into the zone file if they are not already written to the zone file and also push it upstream to the name server above your BIND nameserver if it is not truly an authoritative name server - and it will not be unless you have a full subnet block of IP’s so you can control your own reverse zone file

You should be able to do a " DIG “your domain name” TXT " and see the challenges there before the rfc2136 authenticator goes to look for them and then it should work.

If you have a RedHat based distro and use the /var/named/dynamic directory you may not see any TXT in a DIG but it may work - that is what I am going to have to wait to see if it truly works for REAL instead of just a dry-run in about 30 days when the cert will be able to be actually renewed and a new cert sent down.

Apparently all I can figure is in the RedHat /var/named/dynamic directory config the authenticator can read both the zone file and the .jnl file which is of the same name with different extensions and it works that way

I should not have to say - obviously this only works with the certbot client and not others like acme or dehydrated etc



Sent: Wednesday, September 19, 2018 at 4:30 PM

**Comment by sydneyli** [comment]
> To be honest I was surprised that people who answer at the community forum are not more knowledgable on the rfc2136 authetnicator setup issues which have to do with the Distribution of the Linux OS one is running and thus how BIND is installed as configured by it or the file that installed BIND as well as if even it is being runn as chroot 

I'm sorry that you've been having trouble for so long. We're doing our best to help debug your issue. Logfiles help to provide context when we're stuck. Several of us run nameservers, but DNS configuration issues can come in several different colors.

I'm glad that it seems to work now and thank you for documenting the process. Responding to some of your comments on potential actionable items from the community forum (let me know if I missed some; these are the ones I noticed):
> The page at https://certbot-dns-rfc2136.readthedocs.io/en/latest/ 1 does not give any clues on the fact both nsupdate and dnspython are needed for the certbot-dns-rfc2136 authenticator to work

Although `nsupdate` is useful for testing that your DDNS is set up correctly, the authenticator does not depend on it being installed to work properly. `dnspython` is explicitly listed as a dependency, and should be pulled automatically, via whatever installation method you chose for the Certbot plugin.

> Someone should modify the documentation page at https://certbot-dns-rfc2136.readthedocs.io/en/latest/ to warn and advise of these permissions road block issues

Just to be clear, Certbot's RFC2136 authenticator does not directly touch your zone files; it follows RFC2136's client API (just as `nsupdate` does) to tell a RFC2136-compatible DNS server to perform the proper updates. I also don't think information on how to properly set up Dynamic DNS for BIND for a particular operating system belongs in Certbot's documentation!

Let us know if you have more suggestions!

**Comment by unioncos** [comment]
Thanks Sydney

Now that I have  that information there is no way any user could be able to troubleshoot dnspython

The only way mine might be able to be working is because Bind for the Redhat based distribution is configured as a DDNS by just using the /var/named/dynamic  directory

While  how to go about configuring a DDNS on the rfc2136 documentation page is not appropriate this information you just gave on how the rfc2136 authenticator works is appropriate there

I do not know of any other way to tell if dynamic updates are working unless you test with nsupdate

If this information is not available for people somewhere people will be just like me who get the first certificate manually and they are using Bind this issue will arise over and over again as the only other option is to use manual mode with hook scripts for which I see lots of people trying which in my opinion due to the variety of how it can be done is worse

I will still have to wait and see if it actually works for me to get a new certificate via certbot renew in about 40 days now 
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 9/25/2018, 11:54 AM sydneyli <notifications@github.com> wrote:

To be honest I was surprised that people who answer at the community forum are not more knowledgable on the rfc2136 authetnicator setup issues which have to do with the Distribution of the Linux OS one is running and thus how BIND is installed as configured by it or the file that installed BIND as well as if even it is being runn as chroot

I'm sorry that you've been having trouble for so long. We're doing our best to help debug your issue. Logfiles help to provide context when we're stuck. Several of us run nameservers, but DNS configuration issues can come in several different colors.
I'm glad that it seems to work now and thank you for documenting the process. Responding to some of your comments on potential actionable items from the community forum (let me know if I missed some; these are the ones I noticed):

The page at https://certbot-dns-rfc2136.readthedocs.io/en/latest/ 1 does not give any clues on the fact both nsupdate and dnspython are needed for the certbot-dns-rfc2136 authenticator to work

Although nsupdate is useful for testing that your DDNS is set up correctly, the authenticator does not depend on it being installed to work properly. dnspython is explicitly listed as a dependency, and should be pulled automatically, via whatever installation method you chose for the Certbot plugin.

Someone should modify the documentation page at https://certbot-dns-rfc2136.readthedocs.io/en/latest/ to warn and advise of these permissions road block issues

Just to be clear, Certbot's RFC2136 authenticator does not directly touch your zone files; it follows RFC2136's client API (just as nsupdate does) to tell a RFC2136-compatible DNS server to perform the proper updates. I also don't think information on how to properly set up Dynamic DNS for BIND for a particular operating system belongs in Certbot's documentation!
Let us know if you have more suggestions!

**Comment by unioncos** [comment]
Here is what I would suggest adding to the documentation page

 

SUGGESTED ADDITION OF LANGUAGE

 

Certbot's RFC2136 authenticator does not directly touch your zone files; it follows RFC2136's client API  to tell a RFC2136-compatible DNS server to perform the proper update.  It requres a properly configured Dynamic Domain Nameserver (DDNS) to function properly.  Many servers today run a variant of the Linux operating system which runs BIND as a nameserver.

 

However only a few come configured as DDNS systems and you may need to configure whatever version of BIND you are running to do "dynmaic updates".  A good way to do this is to configure your name server to allow nsupdate to work properly.  How you do that is beyond the scope of this page, however many RedHat based Linux distributions will have a /var/named/dynamic directory indicating it is already configured to be a DDNS.  ( CentOS, Fedora, Mageia, RHEL  )  Others have it in /var/lib/named/var/named/dynamic/   If you do an internet search for " /var/named/dynamic directory " you will find leaders to how to use that out of the box feature.  If you have an another non RedH at based distribution then you will have to make sure nsupdate is set up and working to indicate the server can accept dynamic updates.  One key issue is the zone file and directory will need to have a GROUP WRITE permission usually.

 

Since Certbot's RFC2136 authenticator does not directly touch your zone files, it uses instead "DNSPYTHON" in conjunction with its coding which is written in Python to make the DNS challenges, and this is why nsupdate neeeds to be working as both use the RFC2136's client API  to tell a RFC2136-compatible DNS server to perform the proper update

 

It is recommended that you run dry-runs with the command=>  certbot certonly --dry-run --dns-rfc2136 --dns-rfc2136-credentials /path to/credentials.ini -d "*.youdomain.com" -d yourdomain.com --server https://acme-v02.api.letsencrypt.org/directory   . . . . from a ternimal window

 

which will log the run and report any errors for you and allow you to get Certbot's RFC2136 authenticator working 

 

when the dry-run returns successful, then remove the --dry-run or use a --force-renewal in its place that will modify the configuration files so a certbot renew can use the same successful run to renew the certificate when the time comes to do so

 

Although nsupdate is useful for testing that your DDNS is set up correctly, the authenticator does not depend on it being installed to work properly. dnspython is explicitly Certbot's RFC2136 authenticator dependency, and should be pulled automatically, via whatever installation method you chose for the Certbot plugin as for say an installo via YUM will do.  Since dnspython is difficult to troublsehoot directly if nsupdate is working - often Certbot's RFC2136 authenticator will then work properly too

 

Dynamic Update uses a .jnl file extension of the same name as the zone which may or may not get written to the zone file, and then Certbot's RFC2136 authenticator cleans up the challenge by removing the same TXT challenge it wrote or sent into the .jnl file

 

Certbot's RFC2136 authenticator by default will wait 60 seconds for a propagatuion of the TXT challenge to complete and during this period you should be able to do a " DIG your domain TXT " to see the challenge strings waiting.  If not they are not 'ikely propagating, however with the RedHat based Linux distributions and use of the  /var/named/dynamic directory, you may not see the DIG work and the dry-run may still complete becasue of how the RedHat based Linux distributions DDNS is confuigured to also read the .jnl file. in the /var/named/dynamic directory

 

If there are not propagating a restart of BIND while  the propogation is waiting will flush the TXT to the zone file and force a propagation and then it may work telling you that there is likely a permissions issue somewhere

 

Also the .jnl file may be left behind and has on occassion been know to prevent updates so a " rndc sync -clean " will also flush the jnl updates to the zone file and removethe jnl file itelf afterwards

 

If these two things above do not work then usually the DNS or DDNS configuration or key setup is incorrect 

 

Do Internet searchs for how to configure your specific Linux distribution, and be sure it is for your Linux distribution or which ever OS

 you have.  Setting up a working  DDNS is different for each one

 

END OF SUGGESTED ADDITION OF LANGUAGE

 

 

This could be inserted BETWEEN 

 


command like chmod 600 to restrict access to the file).

******  RIGHT HERE  ******


Sample BIND configuration

on the page at https://certbot-dns-rfc2136.readthedocs.io/en/latest

 




Sent: Tuesday, September 25, 2018 at 11:54 AM
