### ISSUE TITLE
Default Ubuntu/xenial configures *both* cron and systemd renewals

### ISSUE THREAD

**Issue by erco77** [certbot/certbot#6329]
## My operating system is (include version):
           ubuntu 16.04.5
           uname -a:
           Linux <<OUR_FQDN>> 4.17.17-x86_64-linode116 #1 SMP PREEMPT Mon Aug 20 16:07:40 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
           sudo apt-get update
           sudo apt-get install software-properties-common
           sudo add-apt-repository ppa:certbot/certbot
           sudo apt-get update
           sudo apt-get install python-certbot-apache

## I ran this command and it produced this output:
      Viewing the system logs, I noticed 'certbot -q renew' was being run by both cron AND systemd,
      both with similar timing events (twice a day at noon and midnight, random 12 hour delay), e.g.
        Aug 29 12:00:01 <<OUR_FQDN>> CRON[22255]: (root) CMD (test -x /usr/bin/certbot -a \! -d /run/systemd/system && perl -e 'sleep int(rand(43200))' && certbot -q renew)  \__ (1)
        Aug 30 00:00:01 <<OUR_FQDN>> CRON[25829]: (root) CMD (test -x /usr/bin/certbot -a \! -d /run/systemd/system && perl -e 'sleep int(rand(43200))' && certbot -q renew)  /
        Aug 30 07:13:02 <<OUR_FQDN>> systemd[1]: Starting Certbot...    \__ (2)
        Aug 30 07:13:02 <<OUR_FQDN>> systemd[1]: Started Certbot.       /

## Certbot's behavior differed from what I expected because:
     I expected only cron OR systemd configs, but not /both/.
     Seems like this is running twice as much as it needs to (4x a day instead of 2x a day;
     2x by cron, and 2x by systemd)

## Here is a Certbot log showing the issue (if available):
     See above excertps from syslog showing both CRON and systemd entries for renewal

**Comment by erco77** [comment]
I should add: I'm reporting this here because I imagine the apt package preparation for Ubuntu that is configuring both systemd and cron renewals by default is managed by certbot.eff.org, and not ubuntu, due to the "add-apt-repository ppa:certbot/certbot".

If this is something I should report to ubuntu instead, please let me know.

**Comment by bmw** [comment]
The Certbot package on Debian based distros contains both a cronjob and systemd timer. It is set up in both places to help ensure renewal occurs if cron or systemd is disabled or isn't working properly.

The cronjob is a noop when systemd is used though. If you look at the cron command being run, it starts with:
```
test -x /usr/bin/certbot -a \! -d /run/systemd/system
```
The latter part of that checks if `/run/systemd/system` exists and if it does, it exits without running Certbot.

You can verify this by looking at Certbot's logs in `/var/log/letsencrypt`.

I believe I answered your question here so I'm closing this issue, but if I didn't or you think there is more to be done here, please comment and I'll reopen.

**Comment by erco77** [comment]
Ah, yes, I missed that, and I can see why you might have that as a backup if systemd is somehow not present.

Perhaps there's reasons this isn't simply detected once during the apt install process, though I'd offer that'd be the best option. (It's hard to imagine systemd as being something that could either be added or removed after certbot is installed, as it's so completely embedded throughout the file system and kernel like a giant octopus)

Great work BTW, love the certbot tool, and will likely donate once our project settles in.

**Comment by bmw** [comment]
The cron and systemd setup was done by the packagers in Debian. For the PPA, the packages from Debian are just taken and modified slightly so they work on Ubuntu.

@hlieberman who is the Debian Developer behind this may be interested in making the change you proposed or explaining more about why the current approach was taken.

And thank you very much for the kind words about the project and considering to donate! I'm glad to hear Certbot has been working well for you.

**Comment by hlieberman** [comment]
Hello @erco77!

Because of the way Debian packaging works, it's actually a lot easier to install both a systemd timer and a cron than it is to pick only one of the two.  That's why I picked that approach when we first switched to shipping both a timer and a cron file.  The no-op inside the cron should be an insignificant load on the system -- and if you want to disable it, you can simply comment the line out.  Apt should be smart enough to see that you've modified that file and not touch it the next time certbot is updated.

Hope that answers your question!
