### ISSUE TITLE
Hooks in /etc/letsencrypt/renewal-hooks/deploy are running without using the renew subcommand

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6346]
The hooks in `/etc/letsencrypt/renewal-hooks` were designed to only run with the `renew` subcommand. The directory is named "renewal-hooks" and setting hooks on the command line for the `certonly` and `run` subcommands is more powerful because you're able to run different hooks for different lineages which isn't possible with the hook directories. The hooks used to obtain the certificate are saved and are run again when the certificate is renewed with the `renew` subcommand.

As reported in https://community.letsencrypt.org/t/is-certbot-certonly-renew-with-new-domains-executing-the-hook-deploy-scripts-if-the-cert-is-renew/70741, hooks in `/etc/letsencrypt/renewal-hooks/deploy` are running when a lineage is renewed with other subcommands. While I'm open to other options, I think we should go back to our originally desired behavior of only running these hooks with the `renew` subcommand. We should have a period where we print deprecation warnings and continue to run hooks in this directory with other subcommands to give people time to update their configuration.

**Comment by xavadu** [comment]
Hello,

As I describe here https://community.letsencrypt.org/t/is-certbot-certonly-renew-with-new-domains-executing-the-hook-deploy-scripts-if-the-cert-is-renew/70741/13?u=ejds, I think that it should be the normal behavior, script should be always a cert is renew, doesn't matter the reason.
