### ISSUE TITLE
Write descriptions for packages on PyPI

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6364]
Other than the `certbot` package, our descriptions on PyPI are blank. For example, see https://pypi.org/project/acme/.

**Comment by bmw** [comment]
That would be great. Thanks @thejessleigh!

**Comment by thejessleigh** [comment]
Sorry, this fell off my radar, but if no one else has picked this up I'll take a look this weekend. I apologize for dropping off!

**Comment by bmw** [comment]
No problem! This issue is still open for the taking. Thanks again for your interest in working on it.
