### ISSUE TITLE
Better-discourage messing with /etc/letsencrypt and better detect when it's happened

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#6382]
We should go through all of the assumptions that Certbot still makes about the `/etc/letsencrypt` renewal structures and ensure that failures of these assumptions lead to useful errors, and that the documentation also sufficiently frequently and forcefully discourages people from making changes to these names and structures.

**Comment by mnordhoff** [comment]
This still affects users, stale bot.

**Comment by AvverbioPronome** [comment]
We probably should document *how* to mess safely, instead of hoping people don't. 

(for example, I don't know where the documentation for editing `renewal` files is, nor for `cli.ini`)

**Comment by mnordhoff** [comment]
This is probably still an issue? [bonks stale bot]
