### ISSUE TITLE
Lexicon test dependencies have changed. 

### ISSUE THREAD

**Issue by AnalogJ** [certbot/certbot#6387]
Hey Certbot devs
CC @bmw 

The `lexicon` test dependencies have changed recently. Not sure what your CI pipeline looks like, but thought you might want a heads up:

https://github.com/AnalogJ/lexicon/pull/290
https://github.com/AnalogJ/lexicon/pull/291

```
pytest==3.8.0
pytest-cov==2.6.0
python-coveralls==2.9.1
vcrpy==1.13.0
pytest-xdist==1.23.0
```

**Comment by bmw** [comment]
Thanks @AnalogJ!
