### ISSUE TITLE
python2-certbot-nginx fails with message " requests 2.6.0 has no such extra feature 'security'

### ISSUE THREAD

**Issue by VirtualAirwaves** [certbot/certbot#6396]
## My operating system is (include version):

Linux ip-10-1-10-10.us-west-1.compute.internal 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

I installed certbot with 
    
    sudo yum install python2-certbot-nginx

per the instructions. 

This commane: 

    sudo certbot --nginx

gives me this message

    pkg_resources.UnknownExtra: requests 2.6.0 has no such extra feature 'security'

I tried installing the "extra" package like this:

    [centos@ip-10-1-10-10 ~]$ sudo pip install requests[security]
    Requirement already satisfied: requests[security] in /usr/lib/python2.7/site-packages (2.6.0)
    requests 2.6.0 does not provide the extra 'security'

## I ran this command and it produced this output:

The "requests" package that's missing the "extra feature" security was installed as a result of the install of python2-certbot-nginx

    [centos@ip-10-1-10-10 ~]$ sudo yum install python2-certbot-nginx
    Loaded plugins: fastestmirror
    Loading mirror speeds from cached hostfile
     * base: mirror.scalabledns.com
     * epel: s3-mirror-us-west-1.fedoraproject.org
     * extras: repos.lax.quadranet.com
     * updates: mirror.scalabledns.com
    Resolving Dependencies
    --> Running transaction check
    ---> Package python2-certbot-nginx.noarch 0:0.26.1-1.el7 will be installed
    --> Processing Dependency: python2-certbot >= 0.22.0 for package: python2-certbot-nginx-0.26.1-1.el7.noarch
    --> Processing Dependency: python2-acme >= 0.25.0 for package: python2-certbot-nginx-0.26.1-1.el7.noarch
    --> Processing Dependency: certbot >= 0.22.0 for package: python2-certbot-nginx-0.26.1-1.el7.noarch
    --> Running transaction check
    ---> Package certbot.noarch 0:0.27.1-1.el7 will be installed
    ---> Package python2-acme.noarch 0:0.26.1-1.el7 will be installed
    --> Processing Dependency: python2-requests for package: python2-acme-0.26.1-1.el7.noarch
    ---> Package python2-certbot.noarch 0:0.27.1-1.el7 will be installed
    --> Running transaction check
    ---> Package python2-requests.noarch 0:2.6.0-0.el7 will be installed
    --> Finished Dependency Resolution

    Dependencies Resolved

    ================================================================================================================ Package                             Arch                 Version                      Repository          Size ================================================================================================================Installing:
     python2-certbot-nginx               noarch               0.26.1-1.el7                 epel                67 k Installing for dependencies:
     certbot                             noarch               0.27.1-1.el7                 epel                21 k  python2-acme                        noarch               0.26.1-1.el7                 epel               140 k  python2-certbot                     noarch               0.27.1-1.el7                 epel               519 k  python2-requests                    noarch               2.6.0-0.el7                  epel               2.9 k

    Transaction Summary
    ================================================================================================================Install  1 Package (+4 Dependent packages)

    Total download size: 750 k
    Installed size: 3.3 M
    Is this ok [y/d/N]: y
    Downloading packages:
    (1/5): certbot-0.27.1-1.el7.noarch.rpm                                                   |  21 kB  00:00:00
    (2/5): python2-acme-0.26.1-1.el7.noarch.rpm                                              | 140 kB  00:00:00
    (3/5): python2-certbot-0.27.1-1.el7.noarch.rpm                                           | 519 kB  00:00:00
    (4/5): python2-certbot-nginx-0.26.1-1.el7.noarch.rpm                                     |  67 kB  00:00:00
    (5/5): python2-requests-2.6.0-0.el7.noarch.rpm                                           | 2.9 kB  00:00:00
    ----------------------------------------------------------------------------------------------------------------Total                                                                           1.1 MB/s | 750 kB  00:00:00
    Running transaction check
    Running transaction test
    Transaction test succeeded
    Running transaction
      Installing : python2-requests-2.6.0-0.el7.noarch                                                          1/5
      Installing : python2-acme-0.26.1-1.el7.noarch                                                             2/5
      Installing : python2-certbot-0.27.1-1.el7.noarch                                                          3/5
      Installing : certbot-0.27.1-1.el7.noarch                                                                  4/5
      Installing : python2-certbot-nginx-0.26.1-1.el7.noarch                                                    5/5
      Verifying  : python2-certbot-nginx-0.26.1-1.el7.noarch                                                    1/5
      Verifying  : python2-requests-2.6.0-0.el7.noarch                                                          2/5
      Verifying  : certbot-0.27.1-1.el7.noarch                                                                  3/5
      Verifying  : python2-certbot-0.27.1-1.el7.noarch                                                          4/5
      Verifying  : python2-acme-0.26.1-1.el7.noarch                                                             5/5

    Installed:
      python2-certbot-nginx.noarch 0:0.26.1-1.el7

    Dependency Installed:
      certbot.noarch 0:0.27.1-1.el7                          python2-acme.noarch 0:0.26.1-1.el7
      python2-certbot.noarch 0:0.27.1-1.el7                  python2-requests.noarch 0:2.6.0-0.el7

    Complete!
    [centos@ip-10-1-10-10 ~]$ sudo certbot --nginx

    Traceback (most recent call last):
      File "/usr/bin/certbot", line 5, in <module>
        from pkg_resources import load_entry_point
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3105, in <module>
        @_call_aside
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3089, in _call_aside
        f(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3118, in _initialize_master_working_set
        working_set = WorkingSet._build_master()
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 578, in _build_master
        ws.require(__requires__)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 895, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 789, in resolve
        new_requirements = dist.requires(req.extras)[::-1]
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2622, in requires
        "%s has no such extra feature %r" % (self, ext)
    pkg_resources.UnknownExtra: requests 2.6.0 has no such extra feature 'security'

## Certbot's behavior differed from what I expected because:

I've used this before, many times. I suspect something has recently changed. Perhaps the "security" feature is no longer an "extra?"

**Comment by sydneyli** [comment]
Thanks for reporting @VirtualAirwaves! @elyscape, does this look familiar to you?

**Comment by elyscape** [comment]
It does not, and I cannot replicate it in an empty Docker container. @VirtualAirwaves: Have you installed anything else via `pip`?

**Comment by VirtualAirwaves** [comment]
Yes, I have installed things via pip, too. This instance was created with a salt script, so I know exactly what's in it, more or less (sometimes dependencies cause things to load).

**Comment by elyscape** [comment]
You're running into something similar to what I described in [this comment on #6245][comment]. The short version is that installing Python packages system-wide with `pip` can cause problems when you then install Python `yum` packages if there's an overlap in dependencies. If possible, I would recommend installing Python packages and dependencies via `yum` when possible. If you need a Python package that either isn't available that way or is too outdated for your needs when installed through `yum`, I would recommend installing it inside a virtualenv to avoid conflicting with the system packages.

[comment]: https://github.com/certbot/certbot/issues/6245#issuecomment-407175955

**Comment by VirtualAirwaves** [comment]
Thanks! However the only way I was able to solve this problem was to use the python3 version of certbot that I installed with pip3

`pip3 install certbot-nginx`

This one installed and worked fine. I have to read about python and pip now! I had no idea "pip" was obsolete and I should look for yum. I'm still getting over the change from easy-install. (Old dogs, new tricks, etc.)

**Comment by elyscape** [comment]
>I had no idea "pip" was obsolete and I should look for yum installers for "global" python packages outside of virtualenvs.

Not quite. `pip` is very much not obsolete. The problem is that `yum` expects that it owns the system Python packages, which can cause problems if `pip` has installed any packages that `yum` wants to install.

**Comment by elyscape** [comment]
As an extension of that, a comment on this:
>Since "certbot" is a system utility, I didn't see a need to set up a virtualenv for it.

In this particular case you should be fine, as there aren't very many Python 3 packages available through `yum` on CentOS 7 and you're unlikely to want to use them anyway, but reason I recommend using virtualenv for `pip` installs is that it avoids potential conflicts between `yum` and `pip`.

**Comment by sydneyli** [comment]
Thanks for weighing in @elyscape!

**Comment by chinacode** [comment]
![image](https://user-images.githubusercontent.com/712314/82724068-e2947980-9d05-11ea-8d1e-ecc09768db06.png)
![Uploading image.png…]()

just modify like my pic , it work fine.

**Comment by chinacode** [comment]
> just modify like my pic , it work fine.

try to use python3

**Comment by Vladimir-Sl** [comment]
> just modify like my pic , it work fine.
Thanks, it helped!
Only I first checked my `certbot` version `pip3 list` on CentOS 7 and change `/bin/letsencrypt` after `pip3 install certbot-nginx`, after all the manipulations, the `certbot` worked.
