### ISSUE TITLE
Nginx could not restart after renew

### ISSUE THREAD

**Issue by StdCarrot** [certbot/certbot#6398]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 16.04 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
installed by apt-get.  
Also tested in certbot-auto after error has occurred.

## I ran this command and it produced this output:
```certbot renew```

## Certbot's behavior differed from what I expected because:
```nginx.pid``` file has been gone. But, nginx still alive in background.
So, I could not restart nginx with ```service``` or ```systemctl```.
Then, must have to do ```reboot``` or ```kill -9```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
There was a configuration for domain A and index folder was F.  
And I made cert file with certbot, this was worked well.  
Some moments later, deleted folder F because site has been closed.
But, domain A and nginx conf file still remained to show 404 page.
Next time, ```certbot renew``` was ran automatically.  
Bomb, certbot-nginx failed to create ```F/.well-known/path/to/auth```, and ```nginx.pid``` file has been gone, but nginx processes still alive in background.  

This is how it's happened.  
In my opinion, it need to extra exception handler when index folder does not exist.  
Because, nginx is fine to it.

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.
