### ISSUE TITLE
ContextualVersionConflict

### ISSUE THREAD

**Issue by Leuchtmarker** [certbot/certbot#6400]
## My operating system is (include version):
Debian 9

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt

## I ran this command and it produced this output:
`certbot --authenticator webroot --installer apache`

**output:**
`An unexpected error occurred:
ContextualVersionConflict: (cryptography 1.7.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('cryptography>=2.2.1'), set(['PyOpenSSL', 'pyOpenSSL']))
Please see the logfile '/tmp/tmptlFhxC' for more details.
`

**/tmp/tmptlFhxC:**
2018-09-28 21:50:21,362:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/certbot/main.py", line 1338, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/local/lib/python2.7/dist-packages/certbot/plugins/disco.py", line 206, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/local/lib/python2.7/dist-packages/certbot/plugins/disco.py", line 52, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2290, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2307, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (cryptography 1.7.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('cry
2018-09-28 21:50:21,363:ERROR:certbot.log:An unexpected error occurred:

## Certbot's behavior differed from what I expected because
I've tried to add a new certificate for a subdomain. Before I did this I installed python-pip.
After it this error happened for the first time I removed pip, python and certbot and reinstalled them.

**Comment by schoen** [comment]
@Leuchtmarker, it looks like the dependencies for your Debian package might have been declared incorrectly.

Did you happen to do anything on this system before installing Certbot that might have resulted in the presence of unusual versions of Python libraries?

**Comment by Leuchtmarker** [comment]
@schoen, the only other things installed on the system are dovecot, postfix, apache, mariadb and php. Before certbot I didn't do anything with python.

**Comment by sydneyli** [comment]
@Leuchtmarker It looks like certbot is installed in `/usr/local`-- did you use `pip` to install Certbot by any chance, or did you install from backports? We recommend [the latter](https://certbot.eff.org/lets-encrypt/debianstretch-apache)!

**Comment by Leuchtmarker** [comment]
@sydneyli I've installed certbot from backports. I've installed `pip` to install the cloudflare-plugin.

I thought I've removed `pip` but I removed `python3-pip` instead of `python-pip`. So I removed the right one. But know I receive this output:

Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 7, in <module>
    from certbot.main import main
  File "/usr/local/lib/python2.7/dist-packages/certbot/main.py", line 9, in <module>
    import configobj
  File "/usr/local/lib/python2.7/dist-packages/configobj.py", line 22, in <module>
    import six
ImportError: No module named six

**Comment by sydneyli** [comment]
Ah, so the cloudflare plugin install may have pulled in a `pip`-y certbot. What's the output of `pip show certbot`? You might have to `pip uninstall` it!

Also, the cloudflare DNS plugin should also be available via backports now!

```
apt install python-certbot-dns-cloudflare -t stretch-backports
```

I opened [this issue](https://github.com/certbot/website/issues/362) a while ago to help improve our documentation about this.

**Comment by Leuchtmarker** [comment]
The output of `pip show certbot` was:

Name: certbot
Version: 0.27.1
Summary: ACME client
Home-page: https://github.com/letsencrypt/letsencrypt
Author: Certbot Project
Author-email: client-dev@letsencrypt.org
License: Apache License 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: zope.interface, pyrfc3339, josepy, zope.component, acme, pytz, ConfigArgParse, configobj, setuptools, parsedatetime, mock, cryptography

I have `pip uninstall` it. Do I have to install it know again?

**Comment by sydneyli** [comment]
Try uninstalling `certbot-dns-cloudflare` as well and installing via backports this time: 
```
apt install python3-certbot-dns-cloudflare -t stretch-backports
```
let me know if that works!

**Comment by Leuchtmarker** [comment]
Yes! Everything is working fine! Thank you a lot!

**Comment by schoen** [comment]
Great debugging, @sydneyli!
