### ISSUE TITLE
Support compiled nginx with customized path settings

### ISSUE THREAD

**Issue by DanielYWoo** [certbot/certbot#6401]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Centos 7.4

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
yum

## I ran this command and it produced this output:
[root@home-server ~]# certbot --nginx
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Error while running nginx -c /etc/nginx/nginx.conf -t.

nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)
nginx: configuration file /etc/nginx/nginx.conf test failed

The nginx plugin is not working; there may be problems with your existing configuration.
The error was: MisconfigurationError('Error while running nginx -c /etc/nginx/nginx.conf -t.\n\nnginx: [emerg] open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)\nnginx: configuration file /etc/nginx/nginx.conf test failed\n',)

## Certbot's behavior differed from what I expected because:
Certbot should provide a parameter to specify the nginx config file path instead of searching /etc/nginx.conf.

**Comment by sydneyli** [comment]
If you run `certbot --help nginx`, the help output should mention that you can specify a flag `--nginx-server-root <path>` to customize your nginx server root path. Is this what you're looking for?

**Comment by DanielYWoo** [comment]
Sorry, did't read the doc carefully. Close it now.
