### ISSUE TITLE
Automatically reorder subject names if first name is >64 bytes but another isn't

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#6402]
As has come up a number of times, because of X.509 issues, a CN field can't specify a domain name longer than 64 bytes, while a SAN field can. This means that currently Let's Encrypt will not be able to issue certificates where the first requested name is too long. In many cases, simply reordering the requested names would result in successful issuance.

While we wait for Let's Encrypt to figure out whether the CN field can be deprecated entirely—a reasonably long-term process—we could probably reduce the number of confusing failed issuances by simply reordering the names on the client side if there's any name that's short enough to go into the CN field!

**Comment by schoen** [comment]
We should also make the error message more helpful here in either case!

**Comment by mnordhoff** [comment]
Certbot has not been fixed; however, _Boulder_ will now reorder them if necessary. This remains a potential issue with other CAs.
