### ISSUE TITLE
Add option for not deleting the configuration changes certbot does

### ISSUE THREAD

**Issue by Shachar** [certbot/certbot#6406]
I am having problems using certbot-auto, resulting in a 403 error from my Apache installation for the challenge files.

I've already approached the forum about this problem. The thing is, I'd probably be able to debug this for myself, except that certbot takes great pains to undo all the configuration changes it does to my setup. Normally this is a very good thing, but when things break, it completely prevents me from figuring out what went wrong.

I'd like to have an option for certbot to not undo the configuration changes it does (or, at least, store them aside).

**Comment by ohemorange** [comment]
Hey @Shachar, thanks for posting on the community forum first! Looks like you might have missed their answer, which is the the correct one -- we already have an option for this, `--debug-challenges`, which pauses in the middle so you can inspect the changes certbot makes to the config. You can also inspect the logs in `/var/log/letsencrypt` if you need to see the configuration changes after the fact. Please feel free to follow up in the community forum post.

**Comment by ohemorange** [comment]
```
$  certbot help all | grep "\-\-debug\-challenges" -A 1
  --debug-challenges    After setting up challenges, wait for user input
                        before submitting to CA (default: False)
```
