### ISSUE TITLE
deploying certificate error

### ISSUE THREAD

**Issue by ncroiset** [certbot/certbot#6408]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 14.04.5 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
via OS package manager

## I ran this command and it produced this output:
certbot --apache

## Certbot's behavior differed from what I expected because:
Deploying Certificate to VirtualHost /etc/apache2/sites-available/000_radio-campus.org-le-ssl.conf
An unexpected error occurred:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.26.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1364, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1131, in run
    _install_cert(config, le_client, domains, new_lineage)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 772, in _install_cert
    path_provider.cert_path, path_provider.chain_path, path_provider.fullchain_path)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 497, in deploy_certificate
    fullchain_path=fullchain_path)
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 306, in deploy_cert
    self._deploy_cert(vhost, cert_path, key_path, chain_path, fullchain_path)
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 416, in _deploy_cert
    self._add_dummy_ssl_directives(vhost.path)
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 1402, in _add_dummy_ssl_directives
    "insert_cert_file_path")
  File "/usr/lib/python3/dist-packages/certbot_apache/parser.py", line 328, in add_dir
    self.aug.set(aug_conf_path + "/directive[last() + 1]", directive)
  File "/usr/lib/python3/dist-packages/augeas.py", line 187, in set
    raise ValueError("Unable to set value to path!")
ValueError: Unable to set value to path!
Please see the logfiles in /var/log/letsencrypt for more details.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

<VirtualHost *:80>
ServerName server5.radio-campus.org
ServerAdmin webmaster@radio-campus.org
DocumentRoot /home/httpd/html/radio-campus.org
php_admin_value open_basedir /home/httpd/html/radio-campus.org:/tmp
ErrorLog /var/log/apache2/radio-campus.org-error.log
CustomLog /var/log/apache2/radio-campus.org-access.log combined
ScriptAlias /cgi/ "/home/httpd/html/radio-campus.org/cgi/"
<Directory "/home/httpd/html/radio-campus.org/cgi">
    AllowOverride None
    Options FollowSymLinks
    Order allow,deny
    Allow from all
</Directory>
ServerName www.radio-campus.org
ServerAdmin webmaster@radio-campus.org
DocumentRoot /home/httpd/html/radio-campus.org
php_admin_value open_basedir /home/httpd/html/radio-campus.org:/tmp
ErrorLog /var/log/apache2/radio-campus.org-error.log
CustomLog /var/log/apache2/radio-campus.org-access.log combined
ScriptAlias /cgi/ "/home/httpd/html/radio-campus.org/cgi/"
<Directory "/home/httpd/html/radio-campus.org/cgi">
    AllowOverride None
    Options FollowSymLinks
    Order allow,deny
    Allow from all
</Directory>
</VirtualHost>

<VirtualHost *:80>
ServerName server5.radio-campus.org
ServerAdmin webmaster@radio-campus.org
DocumentRoot /home/httpd/html/radio-campus.org
php_admin_value open_basedir /home/httpd/html/radio-campus.org:/tmp
ErrorLog /var/log/apache2/radio-campus.org-error.log
CustomLog /var/log/apache2/radio-campus.org-access.log combined
ScriptAlias /cgi/ "/home/httpd/html/radio-campus.org/cgi/"
<Directory "/home/httpd/html/radio-campus.org/cgi">
    AllowOverride None
    Options FollowSymLinks
    Order allow,deny
    Allow from all
</Directory>
ServerName www.radio-campus.org
ServerAdmin webmaster@radio-campus.org
DocumentRoot /home/httpd/html/radio-campus.org
php_admin_value open_basedir /home/httpd/html/radio-campus.org:/tmp
ErrorLog /var/log/apache2/radio-campus.org-error.log
CustomLog /var/log/apache2/radio-campus.org-access.log combined
ScriptAlias /cgi/ "/home/httpd/html/radio-campus.org/cgi/"
<Directory "/home/httpd/html/radio-campus.org/cgi">
    AllowOverride None
    Options FollowSymLinks
    Order allow,deny
    Allow from all
</Directory>
</VirtualHost>

<VirtualHost *:80>
ServerName webmail.radiocampus.org
ServerAlias webmail.radio-campus.org webmail.radiocampus.fr webmail.radio-campus.fr webmail.radio-campus.net webmail.iastar.fr
ServerAdmin webmaster@radio-campus.org
DocumentRoot /home/httpd/roundcube
php_admin_value open_basedir /home/httpd/roundcube:/tmp:/usr/share/misc/magic:/usr/share/php
ErrorLog /var/log/apache2/radio-campus.org-error.log
CustomLog /var/log/apache2/radio-campus.org-access.log combined
<Directory "/home/httpd/roundcube">
    AllowOverride Limit Fileinfo AuthConfig Options
    Options -FollowSymLinks +SymLinksIfOwnerMatch
    Order allow,deny
    Allow from all
</Directory>
<Directory "/home/httpd/roundcube/temp">
    Order allow,deny
    deny from all
</Directory>
</VirtualHost>

**Comment by ohemorange** [comment]
Hey @ncroiset! Please first try asking for help at https://community.letsencrypt.org/. There is a much larger community there of people familiar with the project who will be able to more quickly answer your questions.
