### ISSUE TITLE
Present all challenge instructions simultaneously in the manual authenticator

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#6423]
#6370 is going to warn `--manual` users not to undo one challenge when setting up another one. This warning is probably necessary to avoid confusion, but @joohoi suggests that it might be even clearer and easier for the users if the manual authenticator could simply present *all of the challenge instructions* in a single list, then state that all of the challenges must be ready before continuing.

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.
