### ISSUE TITLE
Certbot renew command (using the nginx plugin) causes nginx to fail

### ISSUE THREAD

**Issue by ionutzp** [certbot/certbot#6425]
Certbot renew command (using the nginx plugin) 

`sudo certbot renew --dry-run` 

produces this error:

`nginx: [error] open() "/run/nginx.pid" failed`

Resulting in spawning a rogue nginx process which needs to be killed manually and nginx needs to be started manually `service nginx start`

It looks like it runs the prehook from the configs in `/etc/letsencrypt/renewal` which stops nginx but still expects to read `/run/nginx.pid`

```
nginx version: nginx/1.14.0
ubuntu 16.04
certbot 0.26.1
```

**Comment by ohemorange** [comment]
This looks like a duplicate of #5486; is this any different?

Also, looks like you've started to investigate, how would you feel about submitting a PR to fix the issue?

**Comment by ohemorange** [comment]
Closing this issue; feel free to reopen if you feel it's not a duplicate
