### ISSUE TITLE
In docs, choosing Nginx + Ubuntu 18.04 lands on Haproxy + Ubuntu 18.04 instead 

### ISSUE THREAD

**Issue by yassineim** [certbot/certbot#6433]
Typing the link directly into the address bar works. (https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx.html)

**Comment by sydneyli** [comment]
Hi @yassineim! Thanks for reporting.

I'm going to close this here-- can you re-file this issue against [certbot/website](https://github.com/certbot/website)? (sorry, I know this information isn't very clear from the website)

That said, I also wasn't able to reproduce this bug! When you re-file, can you also mention what OS / browser you are on?

**Comment by yassineim** [comment]
I tried on another computer and that worked correctly, thank you for checking
