### ISSUE TITLE
Plugin NGINX dont install on ubuntu 18.04

### ISSUE THREAD

**Issue by brunokunace** [certbot/certbot#6441]
## My operating system is (include version):
Ubuntu-18

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package ( using the steps https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx )

## Certbot's behavior differed from what I expected because:

![image](https://user-images.githubusercontent.com/16597320/47464773-b1b63080-d7c0-11e8-9678-ac459c8d384a.png)

I try to use nginx plugin, but dont install, the screenshot show.

Any help with this?

**Comment by bmw** [comment]
It looks like you have multiple versions of Certbot installed as `certbot 0.27.1` is not yet available in the PPA. Did you install it from `pip`? If so, you should remove the packages from `pip` and try again.

If you need additional help cleaning this up, you should post to https://community.letsencrypt.org where there is a larger community of users who are able to help you get Certbot properly installed on your system.
