### ISSUE TITLE
[documentation] TLS-SNI-01 is deprecated

### ISSUE THREAD

**Issue by tdelmas** [certbot/certbot#6445]
Documentation's pages mentioning TLS-SNI-01 should indicate the deprecation status.

- https://github.com/certbot/certbot/blob/master/docs/challenges.rst
- https://github.com/certbot/certbot/blob/master/docs/using.rst

API documentation should be updated too.

https://community.letsencrypt.org/t/february-13-2019-end-of-life-for-all-tls-sni-01-validation-support/74209

> February 13, 2019: End-of-Life for All TLS-SNI-01 Validation Support

**Comment by bmw** [comment]
The docs certainly should be updated! Are you interested in submitting a PR?

**Comment by georgio** [comment]
#6470
