### ISSUE TITLE
Make a smarter resolution of certbot packages during tests

### ISSUE THREAD

**Issue by adferrand** [certbot/certbot#6453]
Following conversion of bash scripts used to setup tests environments in #6435.

Currently, when the various certbot importable packages need to be resolved (like to execute `pytest --pyargs one_package`, the package names are resolved by replacing `-` with `_` in the corresponding distributions packages (aka the python projects) available in the certbot repository.

For instance, `certbot-apache` project will assign the corresponding `certbot_apache` package.

This works only because every project in certbot corresponds to a unique package that follows the convention. If for any reason the convention is not followed any more, or if there is more than one package declared in a given project, tests are likely to fail.

As the scripts are now written in python, one can leverage the various possibilities to resolves packages from a given path: for instance, `setuptools.find_packages()`. Then use this approach each time packages need to be provided.

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.
