### ISSUE TITLE
Ubunutu 18.10.comic..Err:6 http://ppa.launchpad.net/certbot/certbot/ubuntu cosmic Release 

### ISSUE THREAD

**Issue by m85000** [certbot/certbot#6460]
brandnew - geting error for new releae...hope anyone from core can help out(downgrade not working) 
Err:6 http://ppa.launchpad.net/certbot/certbot/ubuntu cosmic Release                                                                                      
  404  Not Found [IP: 91.189.95.83 ]

Ubuntu | nginx ..or getting cycle - loop error admin.ajax.php  
any help welcome

**Comment by bmw** [comment]
Currently, there are not any packages for Ubuntu Cosmic in Certbot's PPA (cc @oerdnj and @NCommander).

In the meantime, I recommend you use skip adding the PPA and install the package with the same name directly from Ubuntu's official repos. Other than that, the instructions generated for you at https://certbot.eff.org are the same.

I created certbot/website#374 to track updating our website.
