### ISSUE TITLE
Merge conflicts in the changelog

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6462]
@joohoi pointed out that with our new approach of adding to the changelog with each relevant PR, merge conflicts frequently pop up. Is there a better way for us to handle this? This problem is certainly not unique to us.

**Comment by jgillula** [comment]
Do we think there's anything useful here https://about.gitlab.com/2018/07/03/solving-gitlabs-changelog-conflict-crisis/ ?

**Comment by ohemorange** [comment]
They're pretty easy merge conflicts to resolve, from what I've seen.

**Comment by bmw** [comment]
Thanks for the link @jgillula.

@sydneyli mentioned the solution of adding many blank changelog entries when this was initially brought up a week ago. This would help and is easy to implement, but it's not particularly elegant nor does it fully solve the problem.

GitLab's final solution would work as long as collisions between file names in their "CHANGELOG/unreleased" folder are avoided. It seems a bit heavyweight to me for our use case and it's kind of nice if we have a single changelog file that people can read about upcoming changes (which is something I've been asked for in the past), but maybe others have different thoughts.

I also personally haven't seen too many problems here though. The times I have, GitHub allows me to resolve conflicts in someone else's PR myself through the website. While trivial, we do have to take the time to do this and then wait for tests to run again. Each new commit triggers a new set of tests eating into our Travis/AppVeyor resources. We're only able to resolve their merge conflicts when people [allow us to make changes to their fork](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) too, although that is enabled by default. I do wonder if external contributors will or already have seen that there's a merge conflict and take the time to (repeatedly) resolve it themselves.

Personally, I'd be happy to change how we do things here, but I'd like the solution to be fairly low effort on our part as I haven't seen many issues here so far.

**Comment by bmw** [comment]
I haven't heard many complaints about this in a while. If you have some, please share, but I otherwise think we can close this and revisit the ideas here if it comes up again.
