### ISSUE TITLE
Integration/system tests for DNS plugins

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6464]
I think we should do more testing beyond our simple unit tests, however, I've been thinking a bit about what that'd look like. Here's a relevant conversation I had with @adferrand about the topic:
```
[2018-11-01 11:02:29] <bmw> adferrand[m]: One thing I've been thinking about lately is how to better test Certbot's DNS plugins.
[2018-11-01 11:02:49] <bmw> I was curious how your project and Lexicon handle this. Do you maintain accounts with all these different providers?
[2018-11-01 11:30:15] <adferrand[m]> In Lexicon, we use vcrpy. It works with cassettes, which are yaml files that describes a serie of http request and their response. First, a dns provider developer executes the tests against the real dns api, because at this time, the developer has a valid account on it.
[2018-11-01 11:30:46] <adferrand[m]> During this test, cassettes are recorded, and committed in the repo.
[2018-11-01 11:31:57] <adferrand[m]> In all subsequent tests execution, in particular CI, vcrpy will mock transparently any requests emitted by python (vcrpy supports the most used http libraries).
[2018-11-01 11:32:57] <adferrand[m]> If for a given test method, with its related cassette, the request corresponds to the recorded one, vcrpy will return the recorded response.
[2018-11-01 11:46:05] <bmw> Interesting.
[2018-11-01 11:46:28] <bmw> One thing we've struggled with is how to initially test these plugins as well as to regularly run tests to ensure they still work with the provider's current API.
[2018-11-01 11:47:31] <bmw> We were planning to set up accounts, but doing this for every plugin someone writes based on Lexicon isn't very sustainable.
[2018-11-01 12:53:34] <adferrand[m]> Indeed, you cannot. And if I construct a universal lexicon plug-in, it is dozens of accounts to maintain potentially. Here with Lexicon, it is possible.
[2018-11-01 12:55:04] <adferrand[m]> The only limitation, is if an actual API changes its specifications, because cassettes are not relevant anymore, and you do not know it until someone executes again a real request. But APIs of this kind
[2018-11-01 12:55:46] <adferrand[m]> are really stable. It should occurs only from time to time, I think it is doable to correct cassettes when needed.
[2018-11-01 13:08:50] <bmw> Sure.
[2018-11-01 13:09:42] <bmw> The only thing I don't like about it is it would likely be our users who run the real request and hit the bug when things change, but maybe that's not the end of the world.
[2018-11-01 13:34:40] <adferrand[m]> Yes indeed, I was already thinking about this to make something with it. 
[2018-11-01 13:35:42] <adferrand[m]> Because currently, in fact tests on dns plugind are mocking every actual call to lexicon, right?
[2018-11-01 13:36:51] <adferrand[m]> And there is already integrations tests in Lexicon that checks an acme challenge can be written in a txt record.
[2018-11-01 13:37:49] <adferrand[m]> So I thought this particular cassette could be reused during integrations tests on dns certbot plug-in that are based on lexicon.
[2018-11-01 13:38:43] <adferrand[m]> Txt deletion is not done on Lexicon, but this could stay a complete mock of Lexicon call, it is not critical.
[2018-11-01 13:39:14] <adferrand[m]> (I mean a test on txt deletion)
[2018-11-01 13:41:30] <adferrand[m]> And anyway, about your concerns on regressions that could be found only by users. It is already the case in fact, as everything is mocked, so you do not lose a lot in fact.
[2018-11-01 13:42:23] <adferrand[m]> At least with vcrpy, you will execute actual code of Lexicon providers code, and find regressions concerning the interface between Lexicon and Certbot.
```

**Comment by trinopoty** [comment]
What kind of tests do you have in mind? The provider APIs themselves almost never change in a breaking way. Even if a version of the API becomes deprecated, it's maintained for a long time to ensure existing software do not need to be modified straight away.
Also, every dns plugin goes through a level of manual testing to ensure full functionality.
Using vcrpy does not protect against a change in live API in most cases.

**Comment by adferrand** [comment]
In fact currently, lexicon-based dns plugins in certbot are running by mocking the entire lexicon client. So the tests would be unable to detect a breaking change in the interface between Lexicon and Certbot. Or a side effect that could not be catched in Lexicon CI, and occur only when Certbot is instrumenting Lexicon.

So the discussions we had were to move the mocking layer to the requests against the DNS API, like in Lexicon, in a way or another. My idea was to reuse existing cassettes and vcrpy that corresponds to actual requests when a certbot is generated using a dns challenge (typically writing TXT records with the acme hash).

So in fact, all of this is coherent with your remarks. The tests would be sensible only to breaking changes on the DNS API, and as you said, it is very unlikely that would happen.

**Comment by adferrand** [comment]
And for that matter in fact, certbot plug-ins instrumentates directly the provider classes, while Lexicon is not designed for this usage: provider should not be used directly, but through the Client that mitigates already a lot of side effects.

For instance, certbot makes a smart analysis of the domain provided, to extract all relevant parts and standardize to fqdn, while Lexicon client has already all of this.

So it would be a good first evolution, like calling the Lexicon client then mocking the provider through an smart mock that extends BaseProvider. Ultimately however, I think we should do what I described above.

**Comment by trinopoty** [comment]
If we're talking about lexicon, it's far easier to write a test for the Lexicon Certbot interface instead of possibly updating plugins. Said test would create a mock lexicon provider and run the tests in `dns_test_common_lexicon.py` to verify the interface.
If we're talking about dns plugins in general, it's possible to use vcrpy to make a recording and run that in CI but that has the problem of requiring to update the recordings if there's a breaking change in certbot for instance.

**Comment by bmw** [comment]
How to test our DNS plugins is the single greatest concern I have about them.

### Current situation

In an ideal world, what I'd personally want are end to end tests using Certbot against the live API of each DNS provider we support. This gives us the most confidence the plugins work because they are complete and unhampered tests that everything is working properly.

As of right now, this is still our plan for testing these plugins. While we don't (yet) have regularly running tests that each plugin is still working, we have taken the time and money to set up accounts for each DNS plugin when reviewing them. We're also continuing to maintain and pay for these accounts for many of our plugins with the plan to set up these regularly running tests.

I'm not sure this situation is sustainable though. We currently have 14 DNS plugins with PRs for 12 more. Does it really make sense for us to pay and maintain accounts for 26+ DNS providers? This is somewhat expensive and it's time consuming as there's legal review required of each new TOS we're agreeing to when we sign up for a new account.

Not only that, but as I explain in #6504, I was initially planning for us to happily take on new PRs based on Lexicon. As of writing this, Lexicon supports 47 providers. Perhaps that issue of which DNS plugins we take on is the problem instead of our testing, but I think something has to change.

We could consider not running end to end tests of each DNS plugin. This worries me because EFF/Certbot will be releasing and maintaining software with a major hole in its testing. Maybe this is a bad enough idea that we should end the conversation here and solve other problems with our DNS plugins, but if we were to consider this, what would this look like?

There are suggestions of things like cassettes and `vcrpy` above which are worth considering. (My main concern there is what happens when a PR like https://github.com/certbot/certbot/pull/5350 comes around which changes our interaction with many DNS providers? Do we fire up accounts again and recapture a new interaction? I kind of feel like just keeping the account around is easier at that point.

At the end of the day though, if we don't have end to end tests of our DNS libraries, we are placing more of our trust (and reputation) in hoping that the library is well tested and maintained. This might be OK, but I think we'd want to limit the libraries we do this with to either large providers and/or a single library that we build a relationship with like Lexicon.

**Comment by zjs** [comment]
I'd propose a multi-step approach to achieving this:

1. Develop end-to-end tests which can be manually executed to validate a plugin, based on the manual testing we've done historically. Going forward, these become a key component of the review process for new DNS plugins and changes which affect existing DNS plugins. 
2. Automate execution of these tests for providers accounts are already available for.
3. Consider creative ways to get results for other providers. Some providers may have developer access programs to provide free access to projects integrating with their APIs. In other cases, people with accounts may be willing to "donate" a subdomain and credentials to manage records for that subdomain.
4. Review telemetry data periodically. Consider investing in accounts for higher-use providers where automated testing is not yet available.

**Comment by trinopoty** [comment]
A complete end-to-end test system has a few but major drawbacks.
First, it would require maintaining accounts with each provider which brings with it stuff like costs.
Also, has the potential to limit the tests that an independent contributor can run.
If you go with the option of maintaining an account on all the supported providers, you will need some way to keep the access keys secure. While keeping the encrypted keys in travis config is easy enough, this would mean that DNS plugin tests will fail on a developer's local system.
These are the only major drawbacks I can think of atm. I'm sure actually sitting over it will give us a few more to deal with.
Also, this option limits running tests in parallel (includes travis and the local systems of multiple developers).

**Comment by zjs** [comment]
> Also, has the potential to limit the tests that an independent contributor can run.

We should be able to trigger tests based on a PR. While less convenient than being able to run tests from a developer's system, this may be a good complement to unit tests.

>  Also, this option limits running tests in parallel (includes travis and the local systems of multiple developers).

A unique subdomain could be used for each test run to isolate parallel runs from one another.

**Comment by adferrand** [comment]
In a logic of continuous integration testing, so automated tests that are run on push, PRs, or at the discretion of a contributor, I think that end-to-end tests are not possible. For reasons explained previously, as it require specific credentials that cannot be shared. However it does not mean that theses kind of tests should not be automated: they need to be, and be executed at least before a new certbot release on certbot dev team side.

For the continuous integration itself, I think we can use the same mechanism than Lexicon. It consists in recording the http requests exchanged between client and server, and replay them during tests.

The main advantage, is that you do not need any credentials, and access to the actual dns api. In fact, with this approach, you have a complete integration test approach, where the breaking changes not detected by the tests would not be in any python code (certbot or its dependencies), but if the DNS provider makes breaking changes on his own API.

This can be covered with end to end tests, and by making a technological watch of the DNS providers.

**Comment by adferrand** [comment]
However as said by @bmw, the cassette approach has the drawback that a recording needs to be done if the effective interaction with the API needs to change.

This is already the case in Lexicon, where half of our providers are covered about TXT recordset writing, but the other is not.

**Comment by zjs** [comment]
I see significant value in testing a project like Lexicon using recorded responses. However, given that Lexicon is already testing with recorded responses, I'm not convinced that testing Lexicon-based DNS plugins with recorded responses provides significant incremental value. 

For other DNS plugins, the library being used is maintained by the DNS provider. In those cases, I think it's reasonable to trust that the library behaves as expected, and verify with less frequent end-to-end testing.

I do think executing end-to-end tests less frequently, at least once before each release and potentially as frequently as on a nightly schedule, would be acceptable if testing in CI poses challenges.

**Comment by zjs** [comment]
> It provides one thing: to ensure that Lexicon and Certbot are correctly integrated, that is the main purpose of an integration test. But I agree that a correct mocking of internal Lexicon mechanism could also do that. And so a unit test would be sufficient to ensure the correct relationship.
> 
> In this case however, you put more trust on Lexicon quality coding to ensure that the library will not break your own code.
> 
> It may or may not be acceptable. I try to stay objective on that matter, as I contribute on both projects ^^
> 
> But I you do not trust that, the idea to reuse the existing cassettes may make sens and provide a significant value.

I think this hints at a path forward for the overall test strategy for DNS plugins:

1. Improve the way the unit tests mock Lexicon to make them more valuable with respect to ensuring Certbot plugins use Lexicon correctly. (This seems preferable to introducing new integration tests for this purpose.)
2. Add cassettes to Lexicon if they're missing for any providers we use. (Proximity between implementation code and test code should make it easier to catch failures at the right step of the development process.)
3. Use system tests to verify the end-to-end behavior of plugins we care enough about. (These would be run less frequently, and have other costs, but provide a level of confidence that other testing approaches can not.)

**Comment by adferrand** [comment]
Yes it is basically what I have in mind as a battle plan. Anyway it is a complex task, with a lot of decisions to be taken, and strongly coupled to the certbot packaging problematic.

Having 1) allow to start work without strong design decision commitment. I will open a issue for this purpose.

About 2), to add knowledge about Lexicon insights: in Lexicon, there are already cassettes to simulate a complete authentification, and another one to write a DNS challenge as a TXT record. So theses could be reused untouched to make integration tests. What is missing however, is the cassettes ensuring the ability to write two TXT records for the same name. This is required to simulate wildcard certificates. So depending on the Providers, then the test suit on Lexicon side may be extended to same level than the other ones. But anyway, we are not talking about 30 providers, but certainly 2 or 3, this is doable.

About 3), your approach in #6619 goes in that direction. I think it is not so a technical problem, but more about strategic and financial support to make end-to-end tests available for a given provider.

**Comment by bmw** [comment]
> About 3), your approach in #6619 goes in that direction. I think it is not so a technical problem, but more about strategic and financial support to make end-to-end tests available for a given provider.

I agree with this.

@zjs, you seem pretty hesitant to skip end to end tests entirely which I understand. I may be able to be convinced to skip them, but I'm concerned about it as well.

You said:

> Use system tests to verify the end-to-end behavior of plugins we care enough about. 

This might quickly start looking like #6504, but in what cases do you think we should run end to end tests on a DNS plugin? I'd like us to develop some kind of a systematic plan for testing here.

**Comment by adacaccia** [comment]
Hello, as a certbot user in the last 2 years, I'd like to point out a serious user, maybe enterprise level, definitely needs DNS01 challenge enabled certbot client. Automating that needs interfacing with the provider API, thus provider credentials are needed.

I'd like to support @zjs multi-step approach, pushing it more toward delegation:

3) as soon as any evidence suggests it, we'll draw such DNS plugin back from release, as testing is needed. Then, the first user of said plugin who needs it, will voluntarily have to test it, making it useful for him/herself, and to provide evidences of said tests to make the plugin available to other users as well.
