### ISSUE TITLE
Lexicon configuration system changing. 

### ISSUE THREAD

**Issue by AnalogJ** [certbot/certbot#6472]
Hey,

Lexicon's internal configuration system will be changing soon, once https://github.com/AnalogJ/lexicon/pull/302 is merged. 

@adferrand's PR reorganizes and refactors a not-insignificant portion of the lexicon engine and adds a much more robust config storage solution based on node's `nconf` library.

His changes are backwards compatible when `lexicon` where possible, however there may be some issues for projects using `lexicon` as a library due to class/function refactoring. 

Since you guys use `lexicon` as a library, I wanted to give you a heads up incase there's any changes in your integration/test suite you need to prepare. 

Timeline for merging the PR is next couple of days unless there are any concerns. 

-Jason

cc @bmw @adferrand

**Comment by bmw** [comment]
Thanks for the heads up @AnalogJ!

@adferrand, do you have a good understanding of how these changes will affect Certbot or should I dig into it a bit? We'll probably want to make any changes we need to make on our end before our release on Wednesday.

**Comment by adferrand** [comment]
Yes @bmw, I think I see what will break. Two things needs to be added to provide quickly the compatibility to the new version:
* on `LexiconClient`, during `_find_domain_id`, the current domain to be set on the underlying lexicon provider need to be passed on its `self.domain` parameter, not `self.options['domain']`
* for every dns plugin, when underlying provider is instantiated, the appropriate provider name needs to be passed on key `provider_name` to the dict consumed by the underlying provider constructor.

Obviously theses changes are not retro-compatible, so any dependency to lexicon will need to be upgraded to set the minimal version to the future major version. Ideally theses dependencies should be expressed to a fixed version.

**Comment by adferrand** [comment]
In fact forget what I said about retro-compatibility. I can make changes that are compatible with bot major versions. First modification can be done conditionally by testing the existence of `options` in the provider, and second modification will have no effect in older versions of Lexicon.

**Comment by adferrand** [comment]
I am working on it right now.

**Comment by bmw** [comment]
Thanks @adferrand. I would just like to get the changes into our next release if they're going to break our DNS plugins so we don't have to do a 2nd release to fix things.

**Comment by bmw** [comment]
Fixed in #6474.
