### ISSUE TITLE
Hide/suppress/fix "Legacy configuration object has been used to load the ConfigResolver."

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6475]
While #6474 allowed Certbot's DNS plugins based on Lexicon to continue to work with the changes mentioned in #6472, Certbot prints the message "Legacy configuration object has been used to load the ConfigResolver." to our users on every run.

We should hide/suppress this message or fix the problem so it no longer appears.

This has less priority for me than #6474 which prevents breakage for the small number of distros who will quickly upgrade Lexicon, however, it would be great if we could squelch this warning before our next release as well.

cc @adferrand

**Comment by adferrand** [comment]
Indeed. As soon as the new version of Lexicon is released, because this will imply to pin current lexicon-based dns plugins to the Lexicon 3.x, in order to build a non-legacy ConfigResolver that is accepted by the Lexicon providers.

Or I will refactor to use Lexicon Client class.

Or I will refactor more to use a universal dns plugin backed by Lexicon ^^

**Comment by bmw** [comment]
For the time being, could we write a simple PR that checks if `ConfigResolver` is available and use that if it is, otherwise, continuing to pass in a `dict`?

I just think that due to the way Certbot wraps Lexicon, this message isn't useful to our users and would like to hide it.

> Or I will refactor more to use a universal dns plugin backed by Lexicon ^^

Is this based on your thoughts from https://github.com/certbot/certbot/issues/6178? I think I still owe you feedback there.

**Comment by adferrand** [comment]
In fact handling both config systems is more complex, has they do not share the same architecture. I am quite reluctant to do that 48 hours before the next release of certbot.

Instead, I will shutdown this particular warning from the certbot codebase, and put a TODO inplace.

**Comment by adferrand** [comment]
Even better. By using python standard warnings, they are not displayed during a normal execution of Certbot. They will be displayed only during the integration tests.

Modification has been done on Lexicon, you can test with my branch, the warnings disappeared.

**Comment by bmw** [comment]
Fantastic. Thanks @adferrand!
