### ISSUE TITLE
Error when execute ./certbot-auto --apache certonly

### ISSUE THREAD

**Issue by eric-tc** [certbot/certbot#6477]
Hi when i'm trying to execute ./certbot-auto --apache certonly i'm getting the following error 

"Installing Python packages...
Traceback (most recent call last):
  File "/tmp/tmp.m7L4Ixj0pi/pipstrap.py", line 184, in <module>
    exit(main())
  File "/tmp/tmp.m7L4Ixj0pi/pipstrap.py", line 171, in main
    shell=True)
  File "/opt/conda/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'pip install --no-index --no-deps -U /tmp/pipstrap-1IO98R/pip-9.0.1.tar.gz /tmp/pipstrap-1IO98R/setuptools-29.0.1.tar.gz /tmp/pipstrap-1IO98R/wheel-0.29.0.tar.gz' returned non-zero exit status 1"

I cannot figure out how to solve this. 
i am on debian 8

Thanks

**Comment by ohemorange** [comment]
Hey @eric-tc! Please first try asking for help at https://community.letsencrypt.org/. There is a much larger community there of people familiar with the project who will be able to more quickly answer your questions.
