### ISSUE TITLE
How to install certbot dns

### ISSUE THREAD

**Issue by 0xC1A551C** [certbot/certbot#6484]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Debian 9.4 

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
sudo apt-get install certbot -t stretch-backports

## I ran this command and it produced this output:
certbot certonly --dns-cloudflare

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Could not choose appropriate plugin: The requested dns-cloudflare plugin does not appear to be installed
The requested dns-cloudflare plugin does not appear to be installed
```

I cannot find anywhere on the certbot wiki at all regarding the installation of plugins. There is no mention of it at all, so I found myself over here: https://devops.stackexchange.com/questions/3757/how-to-install-certbot-plugins

I ran this command to install the certbot-dns-cloudflare plugin pip install certbot-dns-cloudflare. IT does not list it under my certbot plugins list - so I ran the command again and got this output.

`pip3 install certbot-dns-cloudflare
Requirement already satisfied: certbot-dns-cloudflare in /usr/local/lib/python2.7/dist-packages/certbot_dns_cloudflare-0.29.0.dev0-py2.7.egg (0.29.0.dev0)
Requirement already satisfied: acme>=0.21.1 in /usr/local/lib/python2.7/dist-packages/acme-0.28.0-py2.7.egg (from certbot-dns-cloudflare) (0.28.0)
Requirement already satisfied: certbot>=0.21.1 in /usr/local/lib/python2.7/dist-packages/certbot-0.28.0-py2.7.egg (from certbot-dns-cloudflare) (0.28.0)
Requirement already satisfied: cloudflare>=1.5.1 in /usr/local/lib/python2.7/dist-packages/cloudflare-2.1.0-py2.7.egg (from certbot-dns-cloudflare) (2.1.0)
Requirement already satisfied: mock in /usr/local/lib/python2.7/dist-packages/mock-2.0.0-py2.7.egg (from certbot-dns-cloudflare) (2.0.0)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from certbot-dns-cloudflare) (33.1.1)
Requirement already satisfied: zope.interface in /usr/local/lib/python2.7/dist-packages/zope.interface-4.6.0-py2.7-linux-x86_64.egg (from certbot-dns-cloudflare) (4.6.0)
Requirement already satisfied: PyOpenSSL>=0.13 in /usr/local/lib/python2.7/dist-packages (from acme>=0.21.1->certbot-dns-cloudflare) (18.0.0)
Requirement already satisfied: cryptography>=0.8 in /usr/local/lib/python2.7/dist-packages (from acme>=0.21.1->certbot-dns-cloudflare) (2.3.1)
Requirement already satisfied: josepy>=1.0.0 in /usr/local/lib/python2.7/dist-packages/josepy-1.1.0-py2.7.egg (from acme>=0.21.1->certbot-dns-cloudflare) (1.1.0)
Requirement already satisfied: pyrfc3339 in /usr/local/lib/python2.7/dist-packages/pyRFC3339-1.1-py2.7.egg (from acme>=0.21.1->certbot-dns-cloudflare) (1.1)
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages/pytz-2018.7-py2.7.egg (from acme>=0.21.1->certbot-dns-cloudflare) (2018.7)
Requirement already satisfied: requests-toolbelt>=0.3.0 in /usr/local/lib/python2.7/dist-packages (from acme>=0.21.1->certbot-dns-cloudflare) (0.8.0)
Requirement already satisfied: requests[security]>=2.4.1 in /usr/local/lib/python2.7/dist-packages/requests-2.20.0-py2.7.egg (from acme>=0.21.1->certbot-dns-cloudflare) (2.20.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python2.7/dist-packages/six-1.11.0-py2.7.egg (from acme>=0.21.1->certbot-dns-cloudflare) (1.11.0)
Requirement already satisfied: ConfigArgParse>=0.9.3 in /usr/local/lib/python2.7/dist-packages (from certbot>=0.21.1->certbot-dns-cloudflare) (0.13.0)
Requirement already satisfied: configobj in /usr/local/lib/python2.7/dist-packages (from certbot>=0.21.1->certbot-dns-cloudflare) (5.0.6)
Requirement already satisfied: parsedatetime>=1.3 in /usr/local/lib/python2.7/dist-packages/parsedatetime-2.4-py2.7.egg (from certbot>=0.21.1->certbot-dns-cloudflare) (2.4)
Requirement already satisfied: zope.component in /usr/local/lib/python2.7/dist-packages/zope.component-4.5-py2.7.egg (from certbot>=0.21.1->certbot-dns-cloudflare) (4.5)
Requirement already satisfied: future in /usr/local/lib/python2.7/dist-packages/future-0.17.1-py2.7.egg (from cloudflare>=1.5.1->certbot-dns-cloudflare) (0.17.1)
Requirement already satisfied: jsonlines in /usr/local/lib/python2.7/dist-packages/jsonlines-1.2.0-py2.7.egg (from cloudflare>=1.5.1->certbot-dns-cloudflare) (1.2.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python2.7/dist-packages/PyYAML-4.2b4-py2.7-linux-x86_64.egg (from cloudflare>=1.5.1->certbot-dns-cloudflare) (4.2b4)
Requirement already satisfied: funcsigs>=1 in /usr/local/lib/python2.7/dist-packages/funcsigs-1.0.2-py2.7.egg (from mock->certbot-dns-cloudflare) (1.0.2)
Requirement already satisfied: pbr>=0.11 in /usr/local/lib/python2.7/dist-packages/pbr-5.1.1-py2.7.egg (from mock->certbot-dns-cloudflare) (5.1.1)
Requirement already satisfied: enum34; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.8->acme>=0.21.1->certbot-dns-cloudflare) (1.1.6)
Requirement already satisfied: idna>=2.1 in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.8->acme>=0.21.1->certbot-dns-cloudflare) (2.7)
Requirement already satisfied: cffi!=1.11.3,>=1.7 in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.8->acme>=0.21.1->certbot-dns-cloudflare) (1.11.5)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.8->acme>=0.21.1->certbot-dns-cloudflare) (0.24.0)
Requirement already satisfied: ipaddress; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.8->acme>=0.21.1->certbot-dns-cloudflare) (1.0.22)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests[security]>=2.4.1->acme>=0.21.1->certbot-dns-cloudflare) (2018.10.15)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests[security]>=2.4.1->acme>=0.21.1->certbot-dns-cloudflare) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests[security]>=2.4.1->acme>=0.21.1->certbot-dns-cloudflare) (1.24.1)
Requirement already satisfied: zope.deferredimport>=4.2.1 in /usr/local/lib/python2.7/dist-packages (from zope.component->certbot>=0.21.1->certbot-dns-cloudflare) (4.3)
Requirement already satisfied: zope.deprecation>=4.3.0 in /usr/local/lib/python2.7/dist-packages (from zope.component->certbot>=0.21.1->certbot-dns-cloudflare) (4.3.0)
Requirement already satisfied: zope.event in /usr/local/lib/python2.7/dist-packages (from zope.component->certbot>=0.21.1->certbot-dns-cloudflare) (4.4)
Requirement already satisfied: zope.hookable>=4.2.0 in /usr/local/lib/python2.7/dist-packages (from zope.component->certbot>=0.21.1->certbot-dns-cloudflare) (4.2.0)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi!=1.11.3,>=1.7->cryptography>=0.8->acme>=0.21.1->certbot-dns-cloudflare) (2.19)
Requirement already satisfied: zope.proxy in /usr/local/lib/python2.7/dist-packages (from zope.deferredimport>=4.2.1->zope.component->certbot>=0.21.1->certbot-dns-cloudflare) (4.3.1)
`

**Comment by bmw** [comment]
How to install Certbot plugins on your system is a better question for the community forum at https://community.letsencrypt.org where there is a larger community of users familiar with the project who will be able to help you.
