### ISSUE TITLE
Write automation for changelog changes

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6486]
The problem is that the changelog during the release shouldn't have a master section, but I'd like there to always be that section in the master branch so people can always land PRs and update the changelog accordingly, even while we're doing a release.

I think we should just make these changes locally during the release. We'd change the master section to the latest released version, do the release, and then update the changelog to include a new master section. This can then all be pushed up and landed in one PR and should be fairly easy to automate.

I'm not sure how exactly this should be handled for bug fix releases, but I'm sure we can figure something out.

@ohemorange, I did this manually for the most recent release, but we should automate it. Are you interested in working on this?

**Comment by ohemorange** [comment]
If we want this to work seamlessly for bug fix releases, the commit stack should look like this:

1. Update master section of changelog to current release info 
2. Release version whatever
3. Add master back to changelog
4. Bump version

1, 2, and 3 all get pushed to 0.version.x branch. This way, changelog is up to date with master and we don't have to worry about merge conflicts when cherry-picking, and the same release process will work for both.

**Comment by bmw** [comment]
Nice! That's a great idea and keeps things very simple.

**Comment by bmw** [comment]
I had a question about what you wrote above @ohemorange. If we had to do a point release right now, it'd be 0.28.1 but our changelog says 0.29.0. When do we change it to 0.28.1? Is this step 1 of what you wrote which we do manually when cherry picking commits to the point release branch?

**Comment by ohemorange** [comment]
The point release branch will have:

```
0.28.0 - date
Fixed added changed whatever
```

Master will have
```
0.29.0 - master
fixed
the specific thing we changed
0.28.0 - date
Fixed added changed whatever
```
When we cherry-pick the commit, the line "the specific thing we changed" will get added to the 0.28.x branch, since it was part of that commit. Then during that cherry-pick commit, we'd fix it manually for the point release branch. I guess it would also be good to test how git would interpret that in practice.

**Comment by bmw** [comment]
That makes sense! Thanks for the explanation.
