### ISSUE TITLE
Fix test_sdists test farm test

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6502]
`tests/letstest/scripts/test_sdists.sh` which we currently run as part of the release process is now failing. I think this should be fixed quickly so it doesn't cause us problems whenever we go to do our next release. The cause of the failure is that newer versions of `pytest` cannot be installed using old versions of `setuptools`.

To resolve this, we either need to use a newer version of `setuptools` or an older version of `pytest`. My thought is to upgrade `setuptools` because it should prevent problems with other packages in the future and our tests should arguably work with the latest version of every package installed, however, either approach should work.

If we upgrade `setuptools`, we need to decide where to do it. My thought would be to do it somewhere in `tools/_venv_common.py` or the scripts it calls so other code that uses `tools/_venv_common.py` would benefit. (It also looks like `tests/letstest/scripts/test_sdists.sh` still uses the old name `tools/_venv_common.sh` and needs to be updated.) `setuptools>=30.3` seems to be [required](https://github.com/pytest-dev/pytest/commit/d4351ac5a287eb96521f09618bbbe1c73f4e6884#diff-2eeaed663bd0d25b7e608891384b7298).

If we decided to pin back `pytest` (and maybe other packages) instead, I don't have an opinion on the approach.

@ohemorange or @sydneyli, are you interested in taking this? I initially planned on doing it myself but haven't managed to get to it yet and think it's important. It shouldn't be much work.

**Comment by ohemorange** [comment]
I'll add it to the highest-priority queue

**Comment by bmw** [comment]
Thank you!

**Comment by ohemorange** [comment]
I had to manually update boto3 to even get to this failure, is that a problem with my setup or should that be fixed while we're here too?

**Comment by bmw** [comment]
I responded to this out of band.

**Comment by ohemorange** [comment]
Looks like pipstrap installs a particular version of setuptools. That doesn't seem to be the version I have on my machine inside the venv, but why isn't that where the change should be?

**Comment by erikrose** [comment]
Do y'all want to inline and adopt pipstrap and bend it to your will? I think the rest of the world is done with it. I see very few visitors on the GH graphs, and pip is up to version 10 or something by now. in fact, they're not even using numbers anymore; they've gone all [Illustrator '88](https://en.wikipedia.org/wiki/Adobe_Illustrator#Versions_1%E2%80%931.6_(Illustrator_88)) on us. Also, nobody uses Linux machines for deployment now; they all use Linux machines inside of Linux machines, so it's easier to get up-to-date pips if you want.

**Comment by ohemorange** [comment]
That's a good question (especially given our current packaging reflection), and I think we shouldn't block fixing this on answering that.

**Comment by bmw** [comment]
I made https://github.com/certbot/certbot/issues/6526 to track that issue.
