### ISSUE TITLE
tools/venv*.py should also check the Python interpreter running the script

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6508]
I was writing up simple instructions for setting up a Windows VM for Certbot development and following the steps as I did so when I hit an issue. After installing Python 3.7 from https://python.org and cloning this repository, I tried running `python tools\venv3.py`. The result was `tools\venv3.py` exiting with an error saying that it couldn't find `python3` in my `PATH`. It appears the Python 3.7.1 installer put a `python` executable in my `PATH`, but not a `python3` one.

I think we can avoid errors like this and simplify this process by also checking the version of Python that was used to run the `tools\venv*.py` script. If it's the right version of Python, I think we should use it even if it's not in your `PATH`. I don't have a strong preference whether we prefer the `python` interpreter used to run the script or the one found in your `PATH` if both are available.

What do you think @adferrand? If you agree, I'd appreciate a simple PR with this change, however, I can also write it up myself if you think it's a good idea.

**Comment by adferrand** [comment]
I may have already a fix for this issue with #6493. It is not using the same approach, as it is instrumentating the python launcher `py`, but it should work for this situation if you used the standard Python installer for Windows.

However the python launcher can be uninstalled, without removing the python distribution itself, and then we fall back in the situation you described. So yes, I agreed that venv scripts should, at some point, try their own running interpreter. Certainly, in this case, as the fourth try: Linux python PATH, Windows python PATH, Windows python launcher PATH, sys.executable.

It will be a benefit for Linux system also, for corner case where you launch theses scripts from a 'portable' Linux distribution.

**Comment by adferrand** [comment]
Ah ! I am taking the problem entirely wrong!

I am thinking as if it was still a shell script, with no knowledge of python.

The most obvious python path to check is the runtime itself, current python version should be test first! The second try to do is executing `python --version, that as also the advantage to be independant from the platform itself. Then, `pythonX -- version` with X either 2 or 3 depending on the tools script that have been launched. Then finally, `py -X` for Windows platforms.

**Comment by bmw** [comment]
This was fixed in #6493.
