### ISSUE TITLE
Use the venv module instead of virtualenv in tools/venv3.py?

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6509]
When trying to use `tools/venv3.py` on Windows, I got an error that the `virtualenv` module isn't available. I installed Python using the standard Windows installer available at https://python.org.

I wonder if we shouldn't just use the [venv module](https://docs.python.org/3/library/venv.html) in `tools/venv3.py` which is available in the standard library.

If we did this, we'd also have to change the arguments we provide when running `virtualenv`/`venv` because `venv` doesn't accept `--no-site-packages` or `--setuptools`, but `venv` provides the same behavior as `virtualenv` does with these flags by default. (In fact, those flags are noops in new versions of `virtualenv` and those flags are only provided for compatibility with ancient versions of `virtualenv`.)

@adferrand, what do you think? Same as https://github.com/certbot/certbot/issues/6508, if you agree, I'd appreciate a PR with this change, however, I can also write it up myself if you think it's a good idea.

**Comment by adferrand** [comment]
I think every time we can stick to the standard, we must. So on python 3 it is the `venv` module, so it will be.

**Comment by bmw** [comment]
I did this in https://github.com/certbot/certbot/pull/6922.
