### ISSUE TITLE
Get output from subprocesses in Python tools

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6511]
Another side effect of rewriting most of our bash scripts into Python is we no longer get the output from shell commands run by the script. For example, we no longer see the output from `pip`. I hit this when the `pip install` step was failing for me but I couldn't see why because it was never output by the script.

I personally think we should change this and print the command output in all/most cases. I think this should be done whether the command was successful or not. This is unfortunately more complicated to do with Python's `subprocess` module than in a shell script, but it's certainly doable.

If we wanted to get fancy, we could print the output of commands while they're executing. This is kind of nice for long running commands such as using `pip` to install all of our packages and dependencies. With that said, I think just waiting for the command to exit before printing anything is easier to implement and is totally fine.

cc @adferrand

**Comment by adferrand** [comment]
Yes I made some tests, it is doable.

**Comment by adferrand** [comment]
In fact, it is not what is happening. If the pip command executed through subprocess does not give output, it is not because of subprocess, but because the quiet option is given to pip. It was already the case with the bash scripts.

I you do not specify a stdout to subprocess Popen method, stdout from the caller will be used: most of the time, the console from where the script has been issued. So basically you have nothing to do to have real-time output. You can see an example from the tox cover target with AppVeyor or Travis, that displays correctly the output.

For the underlying error on pip, I think you hit the same error than me: current pinned version for cffi does not have precompiled wheels for recent Python Windows version. So sources are downloaded, and should be compiled... but you do not have Visual Studio (and you do not want it). 

One of my PR already includes an upgrade of cffi pinned version to use pre-built binaries.

But I will do a specific PR of that to allow a quick integration.

**Comment by bmw** [comment]
You're right. Thanks for investigating.

I've had on my TODO list to change something here for a while. `-q` was initially added in https://github.com/certbot/certbot/pull/5288 to reduce the noise of `tox` output, but the flag has caused some problems for us.

In this case, it caused `pip` to only output `Command "python setup.py egg_info" failed with error code 1 in C:\Users\IEUser\AppData\Local\Temp\pip-install-9454c_je\cffi\` which wasn't enough for me to understand the problem. We've also had issues reviewing PRs that make changes to our pinned dependencies as it `pip` doesn't show which packages have been installed.

I'm tempted to just remove the flag as a simple fix as its the normal behavior of `tox` and it's the easiest solution to these problems, but perhaps we should conditionally set the flag instead.

The multiple tracebacks like:
```
"C:\Users\IEUser\certbot\venv3\Scripts\python.exe" -m pip install -q --constraint "C:\Users\IEUser\AppData\Local\Temp\tmp0iq674sv\all_constraints.txt" -e acme[dev] -e .[dev,docs] -e certbot-apache -e certbot-dns-cloudflare -e certbot-dns-cloudxns -e certbot-dns-digitalocean -e certbot-dns-dnsimple -e certbot-dns-dnsmadeeasy -e certbot-dns-gehirn -e certbot-dns-google -e certbot-dns-linode -e certbot-dns-luadns -e certbot-dns-nsone -e certbot-dns-ovh -e certbot-dns-rfc2136 -e certbot-dns-route53 -e certbot-dns-sakuracloud -e certbot-nginx -e certbot-postfix -e letshelp-certbot -e certbot-compatibility-test
Command "python setup.py egg_info" failed with error code 1 in C:\Users\IEUser\AppData\Local\Temp\pip-install-9454c_je\cffi\
Traceback (most recent call last):
  File "tools\pip_install.py", line 96, in <module>
    main(sys.argv[1:])
  File "tools\pip_install.py", line 90, in main
    .format(sys.executable, all_constraints, ' '.join(args)))
  File "tools\pip_install.py", line 67, in call_with_print
    subprocess.check_call(command, shell=True, cwd=cwd or os.getcwd())
  File "C:\Users\IEUser\AppData\Local\Programs\Python\Python37-32\Lib\subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"C:\Users\IEUser\certbot\venv3\Scripts\python.exe" -m pip install -q --constraint "C:\Users\IEUser\AppData\Local\Temp\tmp0iq674sv\all_constraints.txt" -e acme[dev] -e .[dev,docs] -e certbot-apache -e certbot-dns-cloudflare -e certbot-dns-cloudxns -e certbot-dns-digitalocean -e certbot-dns-dnsimple -e certbot-dns-dnsmadeeasy -e certbot-dns-gehirn -e certbot-dns-google -e certbot-dns-linode -e certbot-dns-luadns -e certbot-dns-nsone -e certbot-dns-ovh -e certbot-dns-rfc2136 -e certbot-dns-route53 -e certbot-dns-sakuracloud -e certbot-nginx -e certbot-postfix -e letshelp-certbot -e certbot-compatibility-test' returned non-zero exit status 1.
Traceback (most recent call last):
  File "tools\venv3.py", line 36, in <module>
    main()
  File "tools\venv3.py", line 32, in main
    _venv_common.main('venv3', venv_args, REQUIREMENTS)
  File "C:\Users\IEUser\certbot\tools\_venv_common.py", line 133, in main
    ' '.join(args)))
  File "C:\Users\IEUser\certbot\tools\_venv_common.py", line 96, in subprocess_with_print
    subprocess.check_call(command, shell=True)
  File "C:\Users\IEUser\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"venv3\Scripts\python.exe" tools\pip_install.py -e acme[dev] -e .[dev,docs] -e certbot-apache -e certbot-dns-cloudflare -e certbot-dns-cloudxns -e certbot-dns-digitalocean -e certbot-dns-dnsimple -e certbot-dns-dnsmadeeasy -e certbot-dns-gehirn -e certbot-dns-google -e certbot-dns-linode -e certbot-dns-luadns -e certbot-dns-nsone -e certbot-dns-ovh -e certbot-dns-rfc2136 -e certbot-dns-route53 -e certbot-dns-sakuracloud -e certbot-nginx -e certbot-postfix -e letshelp-certbot -e certbot-compatibility-test' returned non-zero exit status 1.
```
also obscures things a bit, so perhaps we should do something there as well.

Regardless, the problem I created this issue for doesn't exist so I'm closing this. Thanks again!
