### ISSUE TITLE
Add config option for cert signing timeout v2

### ISSUE THREAD

**Issue by seandilda** [certbot/certbot#6513]
Can you please add a config option to increase how long certbot will wait for an order to go from processing to valid?   This is currently hard-coded to 90 seconds at https://github.com/certbot/certbot/blob/5073090a20fa59fae45b4d90bfb41635bc181911/certbot/client.py#L282

Background:
I've written an in-house ACME server that signs the certs by sending them to our commercial CA.  About 80% of our certs are signed in less than 90 seconds, the rest can take a bit longer.  It'd a big help to us if we can edit our certbot configs to allow a longer timeout.

**Comment by ohemorange** [comment]
This seems reasonable.

**Comment by seandilda** [comment]
I've just checked the latest documentation and this feature is still not addressed.

**Comment by moratori** [comment]
Hi, I am in the same situation as @seandilda described and 
would like to fix this issue. Could you please review and merge my PR?
Thanks.
