### ISSUE TITLE
installed successfully but my website not HTTPS yet

### ISSUE THREAD

**Issue by zeze6** [certbot/certbot#6523]
i use centos 7 apache
i installed it auto install and everything is ok
no errors in log file
but my website still not showing as HTTPS
what i can do?

**Comment by zeze6** [comment]
ok it's working but i had to type my website URL starts with HTTPS but why it's not redirect to https automatically? i mean the visitors will not see the website as https if they did not type it;s URL with https at first...

**Comment by pankaj9310** [comment]
@zeze6 Please check your apache virtual host settings
check these line are present or not
```
RewriteCond %{SERVER_NAME} =*.daala.io [OR]
RewriteCond %{SERVER_NAME} =daala.io
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
```
If not then add in virtualhost  and restart apache server.
It will redirect all your http request to https

**Comment by zeze6** [comment]
they are present like this
`RewriteCond %{HTTP_HOST} =webmail.mydomain.com
RewriteRule ^(.*) https://mydomain.com:xxxxx/ [R]
RewriteCond %{HTTP_HOST} =admin.mydomain.com
RewriteRule ^(.*) https://mydomain.com:xxxxx/ [R]`
i added the lines 
`RewriteCond %{SERVER_NAME} =*.daala.io [OR]
RewriteCond %{SERVER_NAME} =daala.io
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]`
restarted apache but didn't work..

**Comment by zeze6** [comment]
for anyone who having the same issue, this fixed mine.
https://www.tecmint.com/redirect-http-to-https-on-apache/
but i had to change the location of DocumentRoot to apache config file

**Comment by ohemorange** [comment]
Looks like this is solved!
