### ISSUE TITLE
Should we stop keeping pipstrap in sync with upstream?

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6526]
This was proposed at https://github.com/certbot/certbot/issues/6502#issuecomment-440419100.

My opinion is that we should do this. I'd probably continue to ping @erikrose for reviews on changes to our copy of `pipstrap` when he's available, but I see no real downside and as Erik said, it saves us some paperwork when we want to make changes to the script.

**Comment by adferrand** [comment]
Well, I cannot disagree ^^

**Comment by bmw** [comment]
This has been done in #6775.

**Comment by erikrose** [comment]
Also just added [a note in the pipstrap repo](https://github.com/erikrose/pipstrap/commit/a90eb8fa4ae70bc92f58d2ca488c02107dd7e48c) saying it's no longer developed.
