### ISSUE TITLE
Better documentation for installing DNS plugins

### ISSUE THREAD

**Issue by 0xC1A551C** [certbot/certbot#6531]
Why is there no docs on how to install plugins like certbot-dns-cloudflare?

**Comment by 0xC1A551C** [comment]
pip install (plugin) seems to not work either. Log never generated.

An unexpected error occurred:
VersionConflict: (certbot 0.10.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('certbot>=0.21.1'))
Please see the logfile 'certbot.log' for more details.

**Comment by 0xC1A551C** [comment]
root@vps214362:/# python3 -m pip install certbot-dns-cloudflare
Collecting certbot-dns-cloudflare
From cffi callback <function _verify_callback at 0x7f49c315cc80>:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: module 'lib' has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement certbot-dns-cloudflare (from versions: )
No matching distribution found for certbot-dns-cloudflare

**Comment by 0xC1A551C** [comment]
unable to install. very frustrating

**Comment by sydneyli** [comment]
Hi @0xC1A551C, if you're still having trouble with this, I recommend you ask this question on the [Let's Encrypt Community Forums](https://community.letsencrypt.org/c/help), where there's a larger audience of people familiar with the project. You'll get much faster help there!

What OS are you on? If you use our [instruction generator](https://certbot.eff.org/) and enter your OS, if you have the DNS plugins OS packages, you should see text like:

> Certbot's DNS plugins are also available for your system which can be used to automate obtaining a wildcard certificate from Let's Encrypt's ACMEv2 server.

For instance, here's the page for [Ubuntu 14](https://certbot.eff.org/lets-encrypt/ubuntutrusty-other).

There's still an ambiguity in the package name itself-- depending on your OS, the package may be named `python2-certbot-dns-cloudflare` or `python3-certbot-dns-cloudflare` or even `python-certbot-dns-cloudflare`. We haven't properly documented this for all operating systems that these plugins are available for, so there's currently certbot/website#362 tracking this.

**Comment by 0xC1A551C** [comment]
> Hi @0xC1A551C, if you're still having trouble with this, I recommend you ask this question on the [Let's Encrypt Community Forums](https://community.letsencrypt.org/c/help), where there's a larger audience of people familiar with the project. You'll get much faster help there!
> 
> What OS are you on? If you use our [instruction generator](https://certbot.eff.org/) and enter your OS, if you have the DNS plugins OS packages, you should see text like:
> 
> > Certbot's DNS plugins are also available for your system which can be used to automate obtaining a wildcard certificate from Let's Encrypt's ACMEv2 server.
> 
> For instance, here's the page for [Ubuntu 14](https://certbot.eff.org/lets-encrypt/ubuntutrusty-other).
> 
> There's still an ambiguity in the package name itself-- depending on your OS, the package may be named `python2-certbot-dns-cloudflare` or `python3-certbot-dns-cloudflare` or even `python-certbot-dns-cloudflare`. We haven't properly documented this for all operating systems that these plugins are available for, so there's currently [certbot/website#362](https://github.com/certbot/website/issues/362) tracking this.


This needs to be added to the instructions and documents. I could not find that package anywhere. (debian 9)

**Comment by 0xC1A551C** [comment]
There are no instructions anywhere for installing the plugins at https://certbot.eff.org/docs/using.html#dns-plugins either.

sudo apt-get install python3-certbot-dns-digitalocean does work & should be added there.

**Comment by foxtrot9** [comment]
@sydneyli , I had same issue of not finding proper documentation for installation of dns plugin `certbot-dns-cloudflare` for ubuntu 14.04. A search on ubuntu14.04 reveals ambiguity in package names for plugins: Cloudflare's certbot plugin documentation has package name`python-certbot-dns-cloudflare-doc` and actual plugin is `python3-certbot-dns-cloudflare`.
```
foxtrot9@ubuntu14$ apt search certbot-dns-cloudflare
Sorting... Done
Full Text Search... Done
python-certbot-dns-cloudflare-doc/trusty 0.23.0-1ubuntu0ppa1~ubuntu14.04.1 all
  Documentation for the Cloudflare DNS plugin for Certbot

python3-certbot-dns-cloudflare/trusty,now 0.23.0-1ubuntu0ppa1~ubuntu14.04.1 all [installed]
  Cloudflare DNS plugin for Certbot
```

**Comment by sydneyli** [comment]
@foxtrot9, we're aware of this problem and have an issue tracking it at certbot/website#362!

**Comment by abhchand** [comment]
I'm still having a similar problem. The documentation around plugins seems to be really confusing.

I was able to get both working by installing both certbot and the DNS plugin (DigitalOcean) through the _same source_ (Ubuntu's `apt-get`)

I mention that because the "official" documentation on https://certbot.eff.org/ encourages people to install via `snap.d` now. Luckily, they still support installation via OS Package managers too ([see here](https://certbot.eff.org/docs/install.html#operating-system-packages))

```
sudo apt-get install python3 python3-pip

sudo apt-get install certbot
sudo apt-get install python3-certbot-dns-digitalocean
```

```
root@prod-001:~# certbot plugins
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
* dns-digitalocean
Description: Obtain certs using a DNS TXT record (if you are using DigitalOcean
for DNS).
Interfaces: IAuthenticator, IPlugin
Entry point: dns-digitalocean =
certbot_dns_digitalocean.dns_digitalocean:Authenticator

* standalone
Description: Spin up a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = certbot.plugins.standalone:Authenticator

* webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```
