### ISSUE TITLE
A simpler way to add a domain is needed

### ISSUE THREAD

**Issue by paolobenve** [certbot/certbot#6532]
As long as I know, in order to add a domain to a certificate you need to specify all the "old" domains plus the new one in the -d parameter. This way a mistake is easily made.

A simpler way to add a domain is needed: another parameter, e.g. --add-domain, which permits to add a domain to an existing certificate.

**Comment by schoen** [comment]
@ohemorange, did you have any long-term post-CMIP thinking about the merits of this kind of feature? Should there be a *CMIP 2: Revenge of the CMIP*?

**Comment by ohemorange** [comment]
This is a duplicate of #4410, see discussion there.
