### ISSUE TITLE
Cannot find any Pythons; please install one!

### ISSUE THREAD

**Issue by BrainforgeUK** [certbot/certbot#6533]
## My operating system is (include version):

Centos 6

I am aware of issue #2902

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

wget

## I ran this command and it produced this output:

# export PATH=".:$PATH"
# which python
/root/certbot/python
# certbot-auto --no-bootstrap --apache certonly
WARNING: couldn't find Python 2.7+ to check for updates.
Creating virtual environment...
Cannot find any Pythons; please install one!

## Certbot's behavior differed from what I expected because:

Expected certbot to find and use Python v3.6 in current directory (like which).

# ls -l
-rwxr-xr-x 1 root root 62298 Nov 26 21:53 certbot-auto
-rwxr-xr-x 1 root root    97 Nov 27 11:51 certbot.certonly.sh
lrwxrwxrwx 1 root root    24 Nov 27 11:43 python -> /usr/local/bin/python3.6

**Comment by schoen** [comment]
Hi @BrainforgeUK,

My suspicion is that Python is losing your custom `PATH` when it automatically runs `sudo`, and then it no longer knows to try to look in the current directory for Python. Could you try some workaround for this hypothesis? For example

`sudo PATH=".:$PATH" certbot-auto --no-bootstrap --apache certonly`

**Comment by BrainforgeUK** [comment]
Got it working like this...

_$ sudo bash
# mv /usr/bin/python /usr/bin/python.bak
# ln /usr/local/bin/python3.6 /usr/bin/python
# certbot-auto --no-bootstrap "$@" --apache certonly
Creating virtual environment...
Installing Python packages...
Installation succeeded.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
... etc ...

Hit another problem, but that is a separate issue.
Must remember to put the real python back ASAP!21

**Comment by schoen** [comment]
Great!
