### ISSUE TITLE
Wildcard request replace "*" to "wildcard" word in domain prefix

### ISSUE THREAD

**Issue by ogerasymenko** [certbot/certbot#6535]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Amazon Linux AMI release 2018.03

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
git clone https://github.com/certbot/certbot

## I ran this command and it produced this output:
Saving debug log to /path/letsencrypt/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for wildcard.example.com
Waiting for verification...
Cleaning up challenges
Non-standard path(s), might not work with crontab installed by your operating system package manager

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /path/letsencrypt/live/wildcard.example.com/fullchain.pem
   Your key file has been saved at:
   /path/letsencrypt/live/wildcard.example.com/privkey.pem
   Your cert will expire on 2019-02-26. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot-auto
   again. To non-interactively renew *all* of your certificates, run
   "certbot-auto renew"

## Certbot's behavior differed from what I expected because:
because I'm write this option --domains *.example.com and certificate got instead domain name CN=wildcard.example.com

Hello. 
Can't understand where is mistake - make cert request for wildcard cert, received one which has CN replaced "*" to "wildcard", so it is valid only for dns wildcard.example.com.

Here is command: 
`/opt/certbot/certbot-auto certonly --no-self-upgrade --no-bootstrap --non-interactive --manual \
  --manual-auth-hook "./update_dns.py -a UPSERT -d $TLD" \
  --manual-cleanup-hook "./update_dns.py -a DELETE -d $TLD" \
  --preferred-challenge dns \
  --config-dir "./output" \
  --work-dir "./output" \
  --logs-dir "./output" \
  --agree-tos \
  --manual-public-ip-logging-ok \
  --domains *.example.com \
  --server https://acme-v02.api.letsencrypt.org/directory \
  --email some@email.addr`
where $TLD is example.com

CSR file also have X509v3 Subject Alternative Name: DNS:wildcard.example.com

**Comment by schoen** [comment]
Hi @ogerasymenko,

That's an interesting problem; thanks for letting us know about it.

What's your domain name? I'd like to see the actual certificate in question.

When you specified `--domains *.example.com`, this should have been quoted as `--domains "*.example.com"` in order to prevent your shell from expanding this as a shell wildcard. What directory where you in when you ran this command? Did you previously have a file called `wildcard.example.com`? Consider this analogy:
```
$ cd /tmp
$ touch wildcard.example.com
$ echo Now *.example.com gets expanded
Now wildcard.example.com gets expanded
```

**Comment by ogerasymenko** [comment]
Thanks for response.

Actually I did a script which accept as argument ($1) - domain. Then by regular expression checks what kind of domain is argument - TopLevelDoman, SubDomain or WildCard request. After this in current directory creates folder for output and if request include "*" character, script replace "*" to word "wildcard". So before running certbot-auto in current dir present subdir, for example "wildcard.example.com". As You made right mention, Bash consider it like name of local subdirectory.

I'm change path for output files from current dir to different path and this fix problem.

So this is my mistake, not app bug)
