### ISSUE TITLE
certbot-auto should give explicit errors about (e.g. pip) dependency versions

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#6552]
There are some obscure problems possible when running `certbot-auto` with a very old version of pip. There might be other problems where certbot-auto calls various tools and libraries on the system that have an implicit minimum version that we don't explicitly check for.

So, we should go through all of `certbot-auto` and try to identify minimum required versions (perhaps of anything other than tools that are specified by POSIX or something?) and then, if possible, check for them and give a specific and useful error if the dependency isn't met.

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.
