### ISSUE TITLE
dev0 version numbers in title for docs

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6554]
As pointed out by @ohemorange, https://certbot.eff.org/docs/using.html has dev0 in the title.

I think this is because we have Sphinx configured to read Certbot's version number when building the docs and the git submodule on the website repo is at a dev0 version. I think probably the easiest fix for this is to see if we can remove the version number from our docs entirely.

**Comment by adferrand** [comment]
Still relevant.
