### ISSUE TITLE
"sudo apt-get install letsencrypt" assumes that you already have a webserver

### ISSUE THREAD

**Issue by pde** [certbot/certbot#656]
During UI testing, we've learned that some sys admins read this and assume that letsencrypt somehow is or pulls in a webserver.

Probably the best fix is that everywhere we say this, we should precede it with "once you have apache or nginx installed..."

**Comment by kuba** [comment]
You probably meant `sudo pip install`. For Apache and Nginx this should be `sudo pip install letsencrypt-apache` and `sudo pip install letsencrypt-nginx` respectively. I believe that plugins are able (or if not, they should) to detect if webserver is installed.

`sudo apt-get install letsencrypt-apache` will pull in Let's Encrypt client and Apache. Similarly for `sudo apt-get install letsenrypt-nginx`.

**Comment by pde** [comment]
We probably don't have this confusion so much with the instruction generator.
