### ISSUE TITLE
Apache may not have permission to read webroot directory for challenges

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6561]
To reproduce this problem, check out the `v0.29.0` tag and try and obtain the certificate with the Apache plugin on a default Apache configuration. I expect the challenge will fail because Apache is serving a 403. I can reliably reproduce these failures on Ubuntu 16.04 but I suspect it affects other default Apache configs as well.

After merging https://github.com/certbot/certbot/pull/6560, ~~tests pass~~ I can obtain a cert. Why?

@joohoi, this is something that might be good for you to take a look at, but I can dig into it more if you're not interested or don't have the time.

**Comment by joohoi** [comment]
The issue appears to be that with the `v0.29.0` a new work directory ( rather the work directory root `/var/letsencrypt` ) gets created with `0700` permissions, which makes the default Apache user `www-data` not being able to read the challenge config file from under the directory, effectively causing the `403` status code.

The reason why we saw this behavior in `v0.29.0` is that the release had the file path issue and all work directories and log directories were placed under `/var/letsencrypt`. When Certbot is run, the log directory `/var/letsencrypt/log/` with 0700 permissions gets created first - including the parent directory. The function to create log directories: `log.post_arg_parse_setup()` gets called in `main.py:main()` before the `make_or_verify_needed_dirs()` which would create the work directories with more relaxed permissions. Without the path issue, the log directory gets created with a separate parent to `/var/log/letsencrypt/` and the strict parent directory permissions don't affect the other work directories.

That said, this is a low priority issue, that we could fix: ensuring that the complete path to work directories have the correct permissions, regardless of existing parent directory permissions.

**Comment by bmw** [comment]
That makes sense! Thanks for digging into this @joohoi!

I agree it's not at all a high priority issue, but it's a case we could probably handle better. I'm not sure what the best approach is. Automatically relaxing the permissions on the directories seems error prone and could lead to behavior our users don't want. Alternatively, we could:

* Detect the directory permissions and error out.
* Switch to using a temporary directory for the challenge files.

**Comment by bmw** [comment]
I closed https://github.com/certbot/certbot/issues/5602 in favor of this issue which may have a slightly different cause such as the user manually modifying directory permissions, but I think the root problem is the same. That is, it's possible that Apache doesn't have permissions to read the directory where we place challenge files and it's hard to debug the problem when that happens.
