### ISSUE TITLE
Installers should refuse to run in hosting panel environments

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#6576]
I noticed there have been a few instances of people running Certbot's apache/nginx installers in environments where it is hopelessly dangerous. Environments such as (but not only):

- cPanel
- DirectAdmin
- Plesk

Whether or not Certbot will eventually sport installers for these platforms, we know that apache/nginx installers will definitely not do what the user wants and possibly hose their system.

Suggest that the apache and nginx installers can sniff out whether they are about to run in any of these environments, and abort.

OTOH it might be a rare enough occurrence that it's not worth bothering, but I'll throw this out there anyway.

**Comment by alexzorin** [comment]
A related issue: https://community.letsencrypt.org/t/installed-the-certificate-now-i-get-the-apache-default-page/79664/10

Certbot, not realizing it's in a Bitnami environment, did the wrong thing.

So if we can do some kind of sniffing for known types of environments, we could stop users before wacky stuff starts happening.

**Comment by schoen** [comment]
I'm in total agreement, @alexzorin.

Is there any risk of false positives, or of breaking some hosting provider's existing scripts? (Maybe there's a hosting provider that uses Certbot to provide certs while using some kind of panel for other purposes, and they happen not to conflict when used that way?) Does it make more sense to print a warning rather than refusing to install? (But if so, is there a practical way to get the user to notice the warning?)

**Comment by alexzorin** [comment]
> Is there any risk of false positives

To avoid breaking those integrations, if they exist, could this be implemented as a confirmation prompt only when Certbot is running interactively?

That should catch the users I'm targeting without affecting anybody else.

**Comment by alexzorin** [comment]
@schoen I was thinking along the lines of something like this: https://github.com/alexzorin/certbot/commit/6d418903ce0530a6eb78d1e75d72c7747f8bd652

```
$ certbot --apache -d example.org --staging
Saving debug log to /tmp/cb/logs/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
This system appears to be running cPanel/WHM. Using Certbot's apache plugin is
probably not what you want to do, as it may cause interoperability issues.
cPanel/WHM provides separate user interfaces and procedures to create SSL
certificates. Read more at https://blog.cpanel.com/autossl/

Are you really sure you want to continue?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(Y)es/(N)o: n
User cancelled the operation.
```

It blows up the test suite for some reason (not sure how zope components are meant to work there) and the wording can be adjusted, but it shouldn't affect any existing non-interactive stuff like renewals or existing integration scripts.

**Comment by bmw** [comment]
@joohoi, what do you think about this idea? I just read through #7125 where I was a little surprised to learn that our Apache plugin plays so poorly with CPanel.

**Comment by joohoi** [comment]
I think warning the users is the correct way to do it. I would like to see the URLs pointing to our configuration generator (which then should direct users forward) to be able to provide working URLs even though the ones upstream might change.

The apparent issue here is that cPanel and alike expect a solid state of Apache configuration that would be handled only by the panel software itself. We then again integrate directly with Apache, disturbing the expected state. I don't see robust way of handing this within Apache plugin itself, and the correct way to support deployments with configuration management software would be integrating with them directly (using a specific Installer).
