### ISSUE TITLE
Wildcard Google Cloud Driver, sys subdomains.

### ISSUE THREAD

**Issue by kwaggas** [certbot/certbot#6577]
## I ran this command and it produced this output:
sudo docker run -it --name certbot --rm -v "/etc/letsencrypt:/etc/letsencrypt" -v "/var/lib/letsencrypt:/var/lib/letsencrypt" -v "/home/$(whoami)/.secrets/certbot:/secrets" -v /var/log/letsencrypt:/var/log/letsencrypt certbot/dns-google --dns-google --dns-google-credentials /secrets/google.json --server https://acme-v02.api.letsencrypt.org/directory certonly --staging --break-my-certs -d '*.apps.cf.smart-iiot.io' -d '*.sys.cf.smart-iiot.io' -d '*.ws.cf.smart-iiot.io' -d '*.cf.smart-iiot.io' -d '*.login.sys.cf.smart-iiot.io' -d '*.uaa.sys.cf.smart-iiot.io'

It produced this output:
Failed authorization procedure. uaa.sys.cf.smart-iiot.io (dns-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: No TXT record found at _acme-challenge.uaa.sys.cf.smart-iiot.io, sys.cf.smart-iiot.io (dns-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: No TXT record found at _acme-challenge.sys.cf.smart-iiot.io, login.sys.cf.smart-iiot.io (dns-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: No TXT record found at _acme-challenge.login.sys.cf.smart-iiot.io

IMPORTANT NOTES:

The following errors were reported by the server:

Domain: uaa.sys.cf.smart-iiot.io
Type: unauthorized
Detail: No TXT record found at
_acme-challenge.uaa.sys.cf.smart-iiot.io

Domain: sys.cf.smart-iiot.io
Type: unauthorized
Detail: No TXT record found at _acme-challenge.sys.cf.smart-iiot.io

Domain: login.sys.cf.smart-iiot.io
Type: unauthorized
Detail: No TXT record found at
_acme-challenge.login.sys.cf.smart-iiot.io

To fix these errors, please make sure that your domain name was
entered correctly and the DNS A/AAAA record(s) for that domain
contain(s) the right IP address.

## Certbot's behavior differed from what I expected because:
The behavior resulted in an error.

I have tested several scenarios and came to the realization that I only get the errors when I use a URL that contains a sys sub-domain like: *.sys.cf.smart-iiot.io.
If I change the sub-domain to system e.g: *.system.cf.smart-iiot.io then it will work.
I have tested several such URLs and the same happens with all of them.

I strongly suspect that there might be a bug concerning using an URL with a sub-domain sys.

Thank you.

**Comment by schoen** [comment]
Hi @kwaggas,

I think this may be a problem on the Google Domains end rather than in Certbot; the nameservers themselves might be treating `sys.cf.smart-iiot.io` qualitatively differently than they treat other subdomains. There isn't any code in the `certbot-dns-google` package that's designed to treat a subdomain called `sys` differently.

Since it's not yet totally clear that Certbot is responsible for this, could you please start in the Community Forum at https://community.letsencrypt.org/ and try to get a diagnosis there? There are many more people there who are prepared to help diagnose validation problems than here in the Certbot issue tracker.

Good luck!

**Comment by kwaggas** [comment]
Hi,

Thank you for your reply.

I have actually first posted this issue on the
https://community.letsencrypt.org/ forum.

There was a suggestion that I post this issue here at Certbot issue
tracker, hence the reason for the post.

If there is no code in certbot-dns-google that can cause this anomaly, then
it perhaps it is a google problem.
I have resolve my issue by changing sys to system, which resolved the issue
for me, but I thought it being helpful to post is on Certbot issue tracker,
so that the developers of Certbot can take note of it.
