### ISSUE TITLE
Add simple unit tests that don't pin dependencies in test everything

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6582]
This would allow us to catch problems with the latest versions of our dependencies such as unexpected API breakage.

I think this could be done either by configuring `tox` to not use our install scripts for these tests or by setting an environment variable or flag that skips the normal pinning in our scripts.

I think this should just be done in the test-everything branch so failures here don't block all development.

**Comment by adferrand** [comment]
There is an environment variable already available, if unit tests are executed through `install_and_test.py`: it is `CERTBOT_NO_PIN`, that needs in this case to be set to `1`.

**Comment by adferrand** [comment]
Done, in #6595
