### ISSUE TITLE
Update dependencies pinned in certbot-auto

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6583]
The relevant file here is https://github.com/certbot/certbot/blob/master/letsencrypt-auto-source/pieces/dependency-requirements.txt. I think that many of these dependencies haven't been updated in a very long time.

Doing this unfortunately is a little tricky because:

* Dependencies can be added conditionally using project's arbitrary `setup.py` files. The dependencies could change based on the Python version or the OS it is run on and this file must contain any possible dependencies we need, otherwise, `certbot-auto` will blow up if it needs a dependencies we don't have pinned.
* We need to make sure we don't drop support for any non-EOL'd OSes we currently support.
* This will likely uncover new warnings which will cause our tests that error on warnings to fail. This would require fixing up any code in a way that removes the warning but also works with older versions of our dependencies used in our "oldest" tests.

The way I might do this is running `pip install certbot-apache certbot-nginx` on many different OSes using their version of both Python 2 and Python 3, running `pip freeze` and recording the result. Ideally, you should also make sure that the installed copy of Certbot works either by running tests manually or running our integration tests.

I'd probably keep `python-augeas` pinned at it's current version because it can have issues finding Augeas in newer versions that don't exist at it's current version.

After that all of output of `pip freeze` would need to be combined into a single file with duplicate dependencies removed. Then you can use `hashin` to get hashes as described at the top of the linked `dependency-requirements.txt` file.

Our test farm tests that use `certbot-auto` should also be run on any changes here which might help us catch problems. If anyone needs help with this piece, please ping me.

Bonus points should be given if whoever takes this:

* Investigates the changed dependencies' changelogs to look for dropped support we may be relying on.
* Writes a script to automate all of this in the future. Regardless of the approach to packaging we take, this is something we will have to do repeatedly in the future.

If the latter isn't done now, I think another issue should be open to track doing that going forward.

@erikrose, you may have some thoughts on this issue and if so, I'd love to hear them.

**Comment by erikrose** [comment]
The repeated `pip freeze` approach sounds sane to me. I don't think we were nearly so careful last time, but that just shows how rare things like environment markers are in the wild. Those are the corner cases you'd be looking for. You may also choose to grep through the setup.py and setup.cfg files of our dependencies for env marker syntax.

**Comment by adferrand** [comment]
Automating a boring and repetitive task, and give it to our Nux minions ? I love this kind of tasks.

**Comment by bmw** [comment]
@erikrose, in talking to Adrien about this, I realized I'm not exactly sure how to handle differences in `pip freeze` output.

I think that for packages that are only found in the output of `pip freeze` on some systems, we should add them to our requirements file and then make sure that `certbot-auto` still works on all the systems we're testing on when those additional packages are required to be installed.

If there is a package that has different versions installed on different systems, I think we'll just need to manually investigate there as I'm not aware of a sane programatic way for us to figure out what to do here.

Any thoughts?

**Comment by erikrose** [comment]
Going with the union, as you suggest, is what I've done in the past (argparse on Python <2.7 being the main one I can remember). I don't have any grand, insightful rule, but has anybody run a few representative `pip freeze`s? I hold out hope that differences are few and far between.

**Comment by bmw** [comment]
If we want to automate this, perhaps we should do this incrementally then to help see what functionality we really need.

I think the first step is automating recreating certbot-auto's virtual environment without installing additional Python packages. Sometimes `certbot-auto` uses Python 2 and sometimes it uses Python 3. Rather than trying to create new code that mimics this, I think we should refactor the code that does this out of certbot-auto so we can make sure we use the same code.

As a bonus, this script could probably be rewritten in Python. The only potential hurdle I see is ensure the Python interpreter is reliably found on an arbitrary system. Previously, we have been relying on the existence of `venv/bin/python`. If we're too worried about this causing problems, I think we could stick to `bash`.

Regardless of the language the script is written in, I think the workflow would look something like:
```
cd letsencrypt-auto-source
letsencrypt-auto --os-packages-only -n
pieces/create_venv.py
pieces/pipstrap.py
. path/to/venv
...
```

Alternatively, we could have certbot-auto install packages first and then we uninstall/upgrade them, but I'm a little worried about getting strange differences in behavior when certbot-auto is run normally where it always starts with a clean venv and the uninstall/upgrade case (see https://github.com/certbot/certbot/pull/4047).

**Comment by bmw** [comment]
We hit an issue with my plan because we don't know whether or not `USE_PYTHON_3` should be set on the venv script we're moving out of `certbot-auto`. My proposal is to first run `certbot-auto --install-only --non-interactive` without modifications, run `/opt/eff.org/certbot/venv/bin/python --version`, and if the version is Python 3, set `USE_PYTHON_3`.

What do you think @adferrand?
