### ISSUE TITLE
Hello, my problem is create certificate postfix with let's encrypt 

### ISSUE THREAD

**Issue by techcomputerworld** [certbot/certbot#6589]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## I ran this command and it produced this output:
I run the command: 
certbot certonly -d domain.com -d domain2.com -d domain3.info can run the command but the thunderbird say the certificate is not valid, this is the problem

**Comment by schoen** [comment]
Hi @techcomputerworld,

Please ask this question on the Let's Encrypt Community Forum at https://community.letsencrypt.org/. That's the best place to get help with Let's Encrypt certificates. There's no error message from Certbot here, so there's no evidence that this is a Certbot bug.

Thanks!
