### ISSUE TITLE
Make mock a test dependency of Certbot

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6604]
Our packages currently add `mock` to `install_requires`. Here is [one example](https://github.com/certbot/certbot/blob/346a4246398b72d27b74b537142ee05073e71cd0/setup.py#L42) but I think this is done in all/most of our packages.

Really, we should only need `mock` when running tests, so why not make it a test dependency like we do for `pytest` [here](https://github.com/certbot/certbot/blob/346a4246398b72d27b74b537142ee05073e71cd0/acme/setup.py#L83)? Us doing this was requested by our PPA maintainers.

We should look through very old commits and the referenced PRs because I believe Kuba had a reason for us doing things that way. I think it's no longer necessary given `test_requires` is working for us, but it'd good to verify there's not something I have forgotten.

**Comment by FelixSchwarz** [comment]
+1 from a Fedora packager :-)

**Comment by bmw** [comment]
Hi @FelixSchwarz. Thanks for the work you've been doing trying to get Certbot packaged in EPEL 8 :smile:

We're stretched pretty thin at the moment, but don't hesitate to ask if you have any questions or suggestions that would make packaging significantly easier for you. You're welcome to communicate with us over GitHub but you can also stop by [our Mattermost instance](https://certbot.eff.org/docs/contributing.html#asking-for-help) or the #certbot-devel IRC on Freenode which it is connected to.

As for this issue, unless it's a significant hurdle for you, we probably won't get to it soon especially since `test_requires` is now deprecated so we'll have to take another approach to solving this problem (see https://github.com/pypa/setuptools/issues/1684), but thanks for expressing your interest in this issue.

**Comment by FelixSchwarz** [comment]
No worries I think we can carry that patch just fine.

**Comment by ekohl** [comment]
Also note that since Python 3.3 mock is part of `unittest`. It would be preferable to use that instead of an external dependency when available.

**Comment by bmw** [comment]
I'm going to close this issue in favor of https://github.com/certbot/certbot/issues/7886 which lays out a plan for removing our dependency on `mock` entirely.
