### ISSUE TITLE
default for auth -> install

### ISSUE THREAD

**Issue by yaseminacar** [certbot/certbot#661]
Right now, if auth is followed by install, all the information, e.g. cert_path, is required to be entered again. 
Might make sense to use the 'auth' information as default (or at least offer the option to reuse without re-entering).

**Comment by kuba** [comment]
That's why we have `run`, which is meant to be `auth` followed by `install`.

**Comment by schoen** [comment]
I think this now works as intended in most cases, although there is still some confusion about people using `certonly` who didn't mean to. There's also now a new round of CLI UI work which may be able to address some remaining misconceptions.

**Comment by schoen** [comment]
(Most of the command line options *are* successfully now saved after `certonly`, and don't need to be respecified to `install`.)
