### ISSUE TITLE
Redesign of DNS common plugin base for Lexicon

### ISSUE THREAD

**Issue by adferrand** [certbot/certbot#6621]
I open this issue to track down specifications of the redesign mentionned as a first step in https://github.com/certbot/certbot/issues/6464#issuecomment-449680428

This spec is NOT about:
* addressing a proposition about how plugins are handled in general in Lexicon
* modifying how dns plugins are consumed in Certbot (so not about a generic DNS Lexicon plugin)
* changing the test strategy of DNS plugins

The three objectives here:
1. using preferred way to operate Lexicon as a library
2. leveraging most of Lexicon handling logic in the common plugin base
3. construct unit tests that triger most of the Lexicon internal logic, without falling down to an integration test approach

**Comment by adferrand** [comment]
cc @bmw, @ohemorange and @zjs

**Comment by adferrand** [comment]
For 1., it is about the fact that dns plugins instantiate directly an object from the relevant `Provider` lexicon class. Instead, the `Client` class should be used. Lexicon as a library is designed to use `Client` to leverage the logic of instantiating the correct provider. In fact, I am planning in Lexicon to make all the `provider` package an internal package.

I will put retro-compatibility of course, but it is a good occasion for the main upstream from Lexicon that is Certbot, to settle things correctly on that matter.

**Comment by adferrand** [comment]
For 2., my idea is that in theory, if a dns plugin follow the standard logic in the common base, all effective code required in the DNS plugin should be something like:
```python
from import certbot.plugins import LexiconPluginBase
class AProviderPlugin(LexiconPluginBase):
   pass
```
and:
```python
from import certbot.plugins import LexiconPluginBaseTest
class AProviderPluginTest(LexiconPluginBaseTest):
   pass
```

So the methods in the common base should be overriden in the concrete class only if custom logic needs to be applied. 

So far I see two methods:
* a method that generates the dict necessary to build a `ConfigResolver` for the Lexicon `Client`
* a method to enrich the Certbot parser and provide the relevant command line arguments

For the first method, it should generate by default a dict corresponding to all arguments relevant for the DNS plugin passed from the command line, plus the `ttl` value and the provider name. Provider name can be inferred from runtime (plugin name), or by an abstract getter that needs to be overriden in the plugin class. Relevant arguments can be extracted out from the second method I will describe just after.

For the second method, it consists in setting the relevant CLI arguments that need to be passed. By default, theses arguments can be inferred from the `ProviderParser` method in lexicon provider modules.

**Comment by adferrand** [comment]
For 3., instead of mocking the entire Lexicon modules, a custom provider may be forged. It would respect the API of a Lexicon `Provider`, and so would be accepted by the `Client`. But of course, all responses inside the provider would be mocked. This way, unit tests would trigger most logic of Lexicon, except the actual logic of a given provider.

For the logic of a given provider, we are on an integration tests approach, maybe using vcrpy to mock the Http requests, but this is another story.

**Comment by bmw** [comment]
I'm not against this, but I personally don't think we should go too far down this road just yet. In my opinion, we don't have a clear picture on the path forward in #6464 (which impacts my views on #6504) and Erica's work on redoing plugin interfaces (#6613) may cause changes here as well.
