### ISSUE TITLE
WARNING: autodoc: failed to import module

### ISSUE THREAD

**Issue by sharpaper** [certbot/certbot#6622]
## My operating system is (include version):
Debian stable

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Debian package manager

## I ran this command and it produced this output:

    cd docs
    make dirhtml

    docs/api/account.rst:4: WARNING: autodoc: failed to import module u'certbot.account';

## Certbot's behavior differed from what I expected because:
It doesn't build all the documentation

**Comment by sydneyli** [comment]
If you'd like to install the docs for certbot, they're packaged in debian as `python-certbot-<plugin>-doc`. So `python-certbot-doc` and `python-certbot-nginx-doc` for instance.

If you want to make modifications to the documentation and re-build them, you'll have to install Certbot via our [developer guide](https://certbot.eff.org/docs/contributing.html).

Let us know if you have any more trouble with this!
