### ISSUE TITLE
certbot delete list must be sorted

### ISSUE THREAD

**Issue by bes-internal** [certbot/certbot#6624]
Subj.

**Comment by sydneyli** [comment]
Would you like to propose a sorting scheme and PR for this, @bes-internal ? The relevant code is in this function: https://github.com/certbot/certbot/blob/master/certbot/storage.py#L44 which is called by `certbot/cert_manager.py` to grab the certificate names.

**Comment by jsha** [comment]
Hi @bes-internal! I noticed that in this issue and in #6625 you used "must," which people may interpret as demanding and rude. I'm sure that's not what you intended. You might have better results in the future replacing "must" with "should," which is less likely to be understood as demanding.

Also, in this particular case, can you explain more about the task you are trying to achieve and why sorting the list would help with that task?

**Comment by bes-internal** [comment]
> why sorting the list would help with that task

Because `certbot delete` provides an interactive interface for the user in order to find the one he needs cert name. Maybe it works for 5-10 domains, but not for 1500 in my case.
And no matter what other functions this subcommand has (--cert-name). We are talking about the interactive select.

P.S. My "must" is not rude, but indicate requirement level. Thank you, I will take your comments for normal speech, because apparently there will be a discussion.

**Comment by schoen** [comment]
@bes-internal, could you try the pull request that was submitted by @trinopoty and see if it works for you? It's a very small code change to a single file aimed at addressing your concern. I don't know how you've installed Certbot or what your level of familiarity with Certbot development is, so let me know if you need help with that or find it impractical in your situation.

**Comment by bes-internal** [comment]
Great, this is what we need.

**Comment by schoen** [comment]
Great, thanks for checking, @bes-internal!
