### ISSUE TITLE
Remove leading $ in documentation

### ISSUE THREAD

**Issue by vjeux** [certbot/certbot#6627]
In the getting started ( https://certbot.eff.org/lets-encrypt/ubuntutrusty-apache ), would be nice to remove the leading `$` so that we can copy and paste the list of commands to the terminal directly.

![image](https://user-images.githubusercontent.com/197597/50575169-61091800-0dad-11e9-84c7-c1f417d19162.png)

**Comment by sydneyli** [comment]
Hi @vjeux, thanks for the suggestion! We have an issue tracking this here: certbot/website#301

**Comment by vjeux** [comment]
Thanks!
