### ISSUE TITLE
certbot-auto's fetch.py step takes over 2 minutes to complete every time

### ISSUE THREAD

**Issue by dim1triy** [certbot/certbot#6628]
## My operating system is (include version):
Debian 8

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
user@webserver:~$ wget https://dl.eff.org/certbot-auto
user@webserver:~$ chmod a+x ./certbot-auto
user@webserver:~$ ./certbot-auto --help

## I ran this command and it produced this output:

run # time ./certbot-auto --help
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
...
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 real    2m31.165s
 user    0m0.904s
 sys     0m0.092s

run # time ./certbot-auto --version
 certbot 0.29.1

 real    2m31.283s
 user    0m0.976s
 sys     0m0.072s

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
log not create with run this commands

**Comment by schoen** [comment]
Hi @dim1triy,

That's an interesting problem! I don't think I've seen this problem before. Did the help message eventually appear in the part that you've replaced with `...`?

If you edit your local copy of `certbot-auto` with a text editor, you could change this line

`set -e  # Work even if somebody does "sh thisscript.sh".`

to

`set -ex  # Work even if somebody does "sh thisscript.sh".`

In that case, `certbot-auto` will print out each step as it's run so you could try to see which step is taking so much time.

Does this computer have broadband Internet access? The `certbot-auto` script does connect to a web site to check whether there are new Certbot versions or library versions that need to be downloaded, which might possibly take a very long time on a very slow Internet connection. You can also see whether this is a factor by running

`./certbot-auto --no-self-upgrade --version`

If that is much faster than `./certbot-auto --version` by itself, the delay is probably happening when `certbot-auto` tries to check for updates to the installation.

**Comment by schoen** [comment]
@dim1triy, thanks for checking that and I'm glad that `--no-self-upgrade` helps (although if you use it *every* time, you wouldn't receive new released versions of Certbot).

Would you be willing to run some other checks for us to figure out why `fetch.py` is so slow in your environment? On most hosted servers this command usually completes in under 1-2 seconds if there's no upgrade to download, so it would be helpful to know why it runs slowly on your system.

**Comment by dim1triy** [comment]
@schoen Found a problem. Connection for some reason goes through ipv6, but not ipv4. And on time out hanging can not connect.

`
root@server01:/tmp/tmp.5VqiKwcdAh# time wget https://pypi.org/pypi/certbot/json                                                                                                                                 
--2019-01-08 10:33:10--  https://pypi.org/pypi/certbot/json
Resolving pypi.org (pypi.org)... 2a04:4e42:400::223, 2a04:4e42:600::223, 2a04:4e42::223, ...
Connecting to pypi.org (pypi.org)|2a04:4e42:400::223|:443... failed: Connection timed out.
Connecting to pypi.org (pypi.org)|2a04:4e42:600::223|:443... failed: Connection timed out.
Connecting to pypi.org (pypi.org)|2a04:4e42::223|:443... failed: Connection timed out.
Connecting to pypi.org (pypi.org)|2a04:4e42:200::223|:443... failed: Connection timed out.
Connecting to pypi.org (pypi.org)|151.101.192.223|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 58576 (57K) [application/json]
Saving to: ‘json’

json                                                 100%[=======================================================================================================================>]  57.20K  --.-KB/s   in 0.01s  

2019-01-08 10:41:39 (5.40 MB/s) - ‘json’ saved [58576/58576]


real    8m29.015s
user    0m0.016s
sys     0m0.000s
`

Fix problem
Edit /etc/gai.conf
and uncomment 
precedence ::ffff:0:0/96  100

`
root@server01:/tmp/tmp.5VqiKwcdAh# time wget https://pypi.org/pypi/certbot/json
--2019-01-08 10:44:37--  https://pypi.org/pypi/certbot/json
Resolving pypi.org (pypi.org)... 151.101.0.223, 151.101.64.223, 151.101.128.223, ...
Connecting to pypi.org (pypi.org)|151.101.0.223|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 58576 (57K) [application/json]
Saving to: ‘json.1’

json.1                                               100%[=======================================================================================================================>]  57.20K  --.-KB/s   in 0.01s  

2019-01-08 10:44:37 (5.26 MB/s) - ‘json.1’ saved [58576/58576]


real    0m0.069s
user    0m0.016s
sys     0m0.000s

`

**Comment by bmw** [comment]
certbot-auto has been deprecated, will error out on new systems, and existing installations are no longer receiving updates so I'm closing this.G
