### ISSUE TITLE
Ensure readthedocs isn't relying on GitHub Services

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6631]
GitHub Services are going away at the end of this month. See https://developer.github.com/v3/guides/replacing-github-services/. It looks like our readthedocs setup is relying on GitHub services.

**Comment by bmw** [comment]
@ohemorange, here are some info that will hopefully help you with this.

This process seems to be extremely provider specific. FWIW, [here](https://docs.travis-ci.com/user/legacy-services-to-github-apps-migration-guide/)'s the process for how to do this with Travis, but I don't think this will help much.

Readthedocs' docs about how to work around this problem can be found at https://docs.readthedocs.io/en/latest/webhooks.html#i-was-warned-i-shouldn-t-use-github-services. Quickly looking at it, this might be a painfully manual process due to all of the readthedocs projects we have and the fact that they don't seem to be able to automate this for you. Hopefully I'm wrong and there's a quick and/or more automated approach or you're able to channel your inner zen to while doing this potentially repetitive task.

Once the process is done, you can remove the readthedocs GH service at https://github.com/certbot/certbot/settings/installations.

Let me know if there's anything else I can do to help.

**Comment by ohemorange** [comment]
Ok, set up most of these. I have a couple questions:

- Do we expect readthedocs builds to be failing for letsencrypt, letsencrypt-apache, letsencrypt-compatibility-test, letsencrypt-nginx, and letshelp-letsencrypt?
- Do we expect to see "No integrations are currently configured." on the integrations tab of the settings page in readthedocs for those same packages, and also for acme-python?

If both of these are "yes", we should be good to turn off the readthedocs Github service.

**Comment by bmw** [comment]
> Ok, set up most of these.

Thanks for doing that! Did you end up having to update them all manually?

> Do we expect readthedocs builds to be failing for letsencrypt, letsencrypt-apache, letsencrypt-compatibility-test, letsencrypt-nginx, and letshelp-letsencrypt?

Not `letsencrypt`, but it looks like the other ones have been failing for a long time.

`letsencrypt` is shown as passing for me, however, the redirect I set up to certbot.eff.org in https://github.com/certbot/certbot/issues/6444 seems to be broken for some reason. I created https://github.com/certbot/certbot/issues/6728 to track that.

I think we can probably just delete the other failing projects though. The Apache and Nginx docs are just API docs, but the plugins don't have a stable API and the docs are horribly out of date. We could fix that or set up `certbot-apache` and `certbot-nginx` repos and redirect those docs but it doesn't seem worth it to me.

We've never used letshelp and the compatibility tests are an internal tool.

What do you think?

> Do we expect to see "No integrations are currently configured." on the integrations tab of the settings page in readthedocs for those same packages, and also for acme-python?

I'm not sure. Do you know what that means? It seems like the `acme-python` package has been being built along with the other packages despite any integrations it's been lacking.

Although something happened because the docs haven't been updated in over a month. Hopefully your recent changes also fixed whatever the problem was.

**Comment by ohemorange** [comment]
Ok, let's remember to check back in next time we expect a change to have updated our readthedocs (when will that be?)

**Comment by bmw** [comment]
The next time a build is triggered should be the next time we commit to master.

**Comment by ohemorange** [comment]
Well, that's when readthedocs finds out about it. But does readthedocs trigger builds based on that, or only when the commit updates the relevant docs sections?

**Comment by ohemorange** [comment]
No, looks like it does just update `latest` on push to master across the board (or it's supposed to, even though it hasn't been).

**Comment by bmw** [comment]
If you want to test now, you could review one of the simple cleanup PRs I wrote a while ago which are https://github.com/certbot/certbot/pull/6572 and https://github.com/certbot/certbot/pull/6573.

I think it's also fine to wait if you prefer.

**Comment by ohemorange** [comment]
Looks like it's updating!
