### ISSUE TITLE
missing / in URL

### ISSUE THREAD

**Issue by jaapbril** [certbot/certbot#6634]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
freebsd 11.1-RELEASE

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS-package manager

## I ran this command and it produced this output:
certbot certonly --webroot -w /usr/local/www/acme -d domain.nl -d www.domain.nl -d hermes.domain.nl -d imap.domain.nl

 - The following errors were reported by the server:

   Domain: imap.domain.nl
   Type:   connection
   Detail: Fetching
   https://**imap.domain.nl.well-known/acme-challenge** /tB2rClCTVMGoKcPKIC4kiIA30Bp3oMNYjvL_7PvqEL0:
   Error getting validation data

   Domain: hermes.camelopardus.nl
   Type:   connection
   Detail: Fetching
   https://**hermes.domain.nl.well-known/acme-challenge**/nFGZ-xq4kA-4vF_KoSFE9NNXcqHSUB4wHIdpfLq0C8U:
   Error getting validation data

## Certbot's behavior differed from what I expected because:
Due to **missing / (slash)** between nl an .well-known the URL is wrong

**Comment by alexzorin** [comment]
> Due to missing / (slash) between nl an .well-known the URL is wrong

That's because your server is generating a redirect that is missing the forward slash.

Probably easy to reproduce with:

    curl -X GET -I imap.domain.nl/.well-known/acme-challenge/xx

**Comment by schoen** [comment]
@alexzorin's explanation is right. If you have any trouble fixing this, please follow up on the Community Forum (https://community.letsencrypt.org/). Thanks!
