### ISSUE TITLE
Ensure all documentation links use HTTPS if the target supports it

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6640]
Some of our documentation links to sites using HTTP rather than HTTPS. We should always use HTTPS if the target supports it.

**Comment by bmw** [comment]
Writing a find and replace for this is easy. The harder part is actually verifying all the links support HTTPS.

**Comment by hichamelkaddioui** [comment]
Should URLs be replaced in license files?

E.g. the Apache license URL `http://www.apache.org/licenses/` in [certbot-nginx/LICENSE.txt](https://github.com/certbot/certbot/blob/a43fac3277fbadaea0311e915efa03aa15f94542/certbot-nginx/LICENSE.txt)

**Comment by bmw** [comment]
Good question. I think we should leave those unchanged for now.

**Comment by Hanse00** [comment]
I'd like to take a look at this. So let's clarify the issue exactly:

We want to walk all documentation files (*.rst, *.txt, *.md), with certain exceptions (LICENSE.txt, others?). For these files we should find all HTTP links (http://*), modify them to HTTPS links, and try to send a get request, to ensure that the link works with HTTPS. If it does, modify the link, if it doesn't, leave it alone.

Sound about right? I think that should be reasonably easily scriptable.
We just need to make sure if there are any other files that should be avoided or included, besides the ones I suggested.
