### ISSUE TITLE
.rpm research

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6650]
If we make our own Certbot .rpms, can we handle the difference in package names (e.g. python, python2, python3) inside the .rpm? How well can we handle differences in dependency packages in general?

Additionally, how reliably can we set up automatic renewal?

The biggest systems here are the non-EOL'd versions of systems based on RHEL (which includes Amazon Linux and CentOS) and maybe openSUSE.

**Comment by adferrand** [comment]
Some results from my researches. Starting with the basic requirement to have Python 3.4+ available, with `venv` module included to setup a virtualenv for Certbot.

Every RPM non-EOL Linux distribution have in a way or another Python 3.4+.

We have on one side CentOS/RHEL 6/7, and every other distributions on the other side. For the other distributions, `python3` package is available, and can be declared as a dependency.

For CentOS/RHEL, things are more complicated. Indeed, Python 3.x is not available by default. EPEL repositories gives Python 3.4 for CentOS/RHEL 6, and Python 3.4 & 3.6 for CentOS/RHEL 7. However, relevant dependencies are `python34` and `python36`, not `python3`.

In the perspective of a unified package, boolean logic can be used in a require assertion, like `Requires: python3 or python34`, that allow to check two different packages to fullfill the requirement. However, this is supported by RPM 4.13. CentOS/RHEL 7 is covered, but not CentOS/RHEL 6.

So from what I see, we cannot have a unified package. At least, we can have everything except CentOS/RHEL 6 with one package, using boolean logic on dependencies to covert CentOS/RHEL 7. But for CentOS/RHEL 6, a different package is mandatory.

Considering also that EPEL repositories are required anyway for CentOS/RHEL, maybe a good approach would be to distribute the new package in EPEL, and as a standalone RPM for every other RPM-based distributions.

**Comment by bmw** [comment]
> For the other distributions, python3 package is available, and can be declared as a dependency.

Does this include both Amazon Linux 1 and Amazon Linux 2?

> However, this is supported by RPM 4.13. CentOS/RHEL 7 is covered, but not CentOS/RHEL 6.
>
> So from what I see, we cannot have a unified package.

That is disappointing. As far as you know, another way to accomplish this didn't exist before RPM 4.13?

> Considering also that EPEL repositories are required anyway for CentOS/RHEL, maybe a good approach would be to distribute the new package in EPEL, and as a standalone RPM for every other RPM-based distributions.

That'd be great. I've tried a couple times to get us packaged in EPEL 6 but no one wants to do that work. There is a large number of packages that must be backported and CentOS 6 is only supported until November 30th, 2020.

**Comment by bmw** [comment]
One other piece that still needs looking into here if it hasn't been done already is:

> Additionally, how reliably can we set up automatic renewal?

**Comment by adferrand** [comment]
Yes, I am checking in comparison to what you found for deb packages, and I will study the current rpm package of Certbot published to EPEL.

**Comment by bmw** [comment]
No worries!

Just wanted to make sure we didn't forget this piece.

**Comment by adferrand** [comment]
So I give a report after a discussion with @elyscape.

RHEL, CentOS and Amazon Linux definitively needs to be treated separately. Either EL6 or EL7, boolean dependencies are not supported, and python3 needs to be taken from EPEL. So theses packages needs to assert a Require on python34 (EL6/EL7) or python 36 (EL7).

Other distributions can rely on `python3` package.

For the automated renewal, RHEL-like distributions will be really deterministic about the presence of systemd or not. EL6 will not have systemd and needs to use a cron, EL7 will have systemd and can use its timers.

For the other distribution, it should be possible to do a runtime resolution of systemd, and so dynamic behavior: either during the RPM installation, with a bash script afterwards, or inside the new certbot manager.

Anyway, building a all-in-one distribution that self updates, is not a good fit for EPEL, but can be used in a CORP. Note that a package from a CORP repository can rely on an EPEL package. So best distribution so far for RHEL-like systems is to setup a CORP repository.

For the other distributions, it can be a CORP or direct distribution, as the package can be universal and rely on official dependencies.

**Comment by elyscape** [comment]
Minor correction: it's COPR, not CORP. [COPRs][copr] are Fedora's analogues to Ubuntu/Debian PPAs.

[copr]: https://copr.fedorainfracloud.org/

**Comment by bmw** [comment]
If we're comfortable hosting/building our packages on COPR, it seems like it might be a decent solution for us. As of right now, the systems we can automating building our packages for there are:

* epel-6-i386
* epel-6-x86_64 
* epel-7-ppc64le
* epel-7-x86_64 
* fedora-28-i386
* fedora-28-ppc64le
* fedora-28-x86_64 
* fedora-29-i386
* fedora-29-ppc64le
* fedora-29-x86_64 
* fedora-rawhide-i386
* fedora-rawhide-ppc64le
* fedora-rawhide-x86_64 
* mageia-6-i586
* mageia-6-x86_64 
* mageia-cauldron-i586
* mageia-cauldron-x86_64 
* opensuse-leap-15.0-x86_64 
* opensuse-tumbleweed-i586
* opensuse-tumbleweed-ppc64le
* opensuse-tumbleweed-x86_64

**Comment by bmw** [comment]
I suppose one major system for us missing from this list is Amazon Linux. Perhaps they can use the EPEL images?

**Comment by adferrand** [comment]
Amazon Linux seems to work as RHEL/CentOS. So yes, they can be treated as these systems, and use EPEL.

https://aws.amazon.com/en/premiumsupport/knowledge-center/ec2-enable-epel/

**Comment by bmw** [comment]
We've decided not to go this route and are planning to distribute snaps instead.
