### ISSUE TITLE
Stop using _SIG_OIDS_TO_HASH in certbot/ocsp.py

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6654]
See https://github.com/certbot/certbot/pull/6603#discussion_r246886454. Since we should still work with cryptography 2.4, I think we should check for the existence of a `signature_hash_algorithm` attribute, if it exists use that, and otherwise continue to use ` _SIG_OIDS_TO_HASH`.

Alternatively, we can only use cryptography to check OCSP with cryptography>=2.5, but the check in the code will have to be changed.

**Comment by adferrand** [comment]
If it is reasonable to require 2.5 as a minimal version when it is released, I would go for the second option, and not rely on a private field if possible.
