### ISSUE TITLE
Write up instructions for how to get Certbot off of TLS-SNI

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6666]
The simple case is easy. They just need to update Certbot, test renewal with `--dry-run`, and make sure that they've configured automatic renewal for that version of Certbot.

It gets more complex if the user has set `--preferred-challenges` in the past. It gets more complex if there are different challenge preferences that must be remembered for different lineages.

**Comment by KlausGPaul** [comment]
As an idea to the above, one has to force renewal of an ACME TLE-SNI-01 cert if is not close enough to its expiry date, see [here](https://community.letsencrypt.org/t/tls-sni-01-deprecation-mail-which-domain-s/82976/9).
As an alternative, this could be added as a feature request to the code, consider validation mode when auto rnewing, not just time stamp.

**Comment by bmw** [comment]
This is done at https://community.letsencrypt.org/t/how-to-stop-using-tls-sni-01-with-certbot/83210.
