### ISSUE TITLE
Certbot maps memory region as both executable and writable

### ISSUE THREAD

**Issue by charly4711** [certbot/certbot#6673]
## My operating system is (include version):
Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt-get from stretch-backports

## I ran this command and it produced this output:
sudo certbot --preferred-challenges dns --manual certonly
... (output as expected, certificates were created)

## Certbot's behavior differed from what I expected because:
selinux blocks this if not in permissive mode and allow_execstack boolean is not set.

## Here is a Certbot log showing the issue (if available):
```
# audit2allow -b -w
type=AVC msg=audit(1547761878.932:91): avc:  denied  { execmem } for  pid=1509 comm="certbot" scontext=unconfined_u:unconfined_r:unconfined_t:s0 tcontext=unconfined_u:unconfined_r:unconfined_t:s0 tclass=process permissive=1
	Was caused by:
	One of the following booleans was set incorrectly.
	Description:
	Allow unconfined executables to map a memory region as both executable and writable, this is dangerous and the executable should be reported in bugzilla")

	Allow access by executing:
	# setsebool -P allow_execmem 1
	Description:
	Allow unconfined executables to make their stack executable.  This should never, ever be necessary. Probably indicates a badly coded executable, but could indicate an attack. This executable should be reported in bugzilla")

	Allow access by executing:
	# setsebool -P allow_execstack 1
```

As audit2allow reports "This should never, ever be necessary." and "this is dangerous"

Can we avoid this so I don't have to open that up?

**Comment by joohoi** [comment]
Thanks for opening the issue!

Certbot uses the system Python executable to run its code, and the only other non-Python libraries that get installed currently exist in package `python3-certbot-apache` or `python-certbot-apache` for Debian. This another library is the `libaugeas` we're currently using to parse Apache configuration. I wonder if you have one of the apache packages installed? 

It would help to know which executable or library has the requirement for execstack, you should be able to find this out by running: 
```
find /usr/lib -exec execstack -q {} \; -print 2> /dev/null | grep ^X 
find /usr/lib -exec execstack -q {} \; -print 2> /dev/null | grep ^X 
```

**Comment by charly4711** [comment]
Sure:

# find /usr/lib -exec execstack -q {} \; -print 2> /dev/null | grep ^X 
X /usr/lib/klibc/bin/poweroff
X /usr/lib/klibc/bin/ipconfig
X /usr/lib/klibc/bin/halt
X /usr/lib/klibc/bin/minips
X /usr/lib/klibc/bin/mount
X /usr/lib/klibc/bin/reboot
X /usr/lib/klibc/bin/fstype
X /usr/lib/klibc/bin/sh.shared
X /usr/lib/klibc/bin/gunzip
X /usr/lib/klibc/bin/cat
X /usr/lib/klibc/bin/mknod
X /usr/lib/klibc/bin/zcat
X /usr/lib/klibc/bin/uname
X /usr/lib/klibc/bin/true
X /usr/lib/klibc/bin/readlink
X /usr/lib/klibc/bin/cpio
X /usr/lib/klibc/bin/sync
X /usr/lib/klibc/bin/nuke
X /usr/lib/klibc/bin/kinit.shared
X /usr/lib/klibc/bin/mv
X /usr/lib/klibc/bin/umount
X /usr/lib/klibc/bin/nfsmount
X /usr/lib/klibc/bin/dd
X /usr/lib/klibc/bin/resume
X /usr/lib/klibc/bin/false
X /usr/lib/klibc/bin/mkfifo
X /usr/lib/klibc/bin/mkdir
X /usr/lib/klibc/bin/ls
X /usr/lib/klibc/bin/losetup
X /usr/lib/klibc/bin/kill
X /usr/lib/klibc/bin/sleep
X /usr/lib/klibc/bin/dmesg
X /usr/lib/klibc/bin/kinit
X /usr/lib/klibc/bin/gzip
X /usr/lib/klibc/bin/ln
X /usr/lib/klibc/bin/pivot_root
X /usr/lib/klibc/bin/chroot
X /usr/lib/grub/i386-pc/kernel.img

Hmm ... and no results for /usr/bin

**Comment by joohoi** [comment]
I did some digging around, and it seems that python modules `cffi` and `ctypes` do not play nicely with memexec protection in SELinux. I'll label this issue and leave it open, but it's not likely we'll be able to get around fixing that very soon unfortunately.

**Comment by charly4711** [comment]
Thanks.
I'll permit it on demand, then, until there is a fix. Didn't expect to get a fix in a day or two but wanted to bring this to your attention, so it'll maybe get scheduled for _some_ release. It seems to make sense that a tool that improves security on one end doesn't do so by opening holes on another (even if the latter may be smaller.) If the issue needs to be addressed somewhere upstream and there's anything I can do to help, let me know.
