### ISSUE TITLE
Pin pip version during virtualenv creation through certbot-auto

### ISSUE THREAD

**Issue by adferrand** [certbot/certbot#6685]
Issue #6682 enlighted a breakage on certbot-auto since version 19.0 of pip has been released that contains a bug. Issue on upstream as been filled here pypa/pip#6158 and bug fix version is incoming.

What I want to study here, is how to avoid that this kind of breakage breaks certbot-auto. It impacted us because by default, virtualenv will try upon its creation to update its fundamental components like pip or setuptools to the latest version available on PyPI. So a temporary fix on our side is to set the `--no-download` to virtualenv to disable the automated update, and use the modules packages in the OS distribution instead.

I think this is not a complete solution, as it makes certbot-auto be sticked with potentially very old modules, that would gain some benefit to be updated nonetheless. For pip at least, we are covered to avoid too old pip versions, but if its logic is triggered, it will still get the latest pip version, so we are again on the same situation.

In fact, we use pinned versions for every other certbot dependencies exactly for this purpose, avoid to have unexpected breakage in recent releases in some modules. 

I propose to do the same for pip and pin its version. This could be done through the pipstrap process.

What do you think?

cc @bmw @ohemorange

**Comment by adferrand** [comment]
It seems that there is two independent problems, related to the wheel module of pip:
* Failing assertion `building_is_possible` #6682
* Failing parsing on files with comma #6687

@cailen, you confirm that neither issues are corrected by pip 19.0.1 ?

**Comment by bmw** [comment]
I agree and I think doing this should be as simple as removing the branch https://github.com/certbot/certbot/blob/1dd7db12e05c7a52f1b1092d76a14caf0bf4c4cc/letsencrypt-auto-source/pieces/pipstrap.py#L152

Erik originally offered to help here, however, because it looks like we may need to put out a bug fix release with this change, I personally think someone from the core Certbot team should probably take this to make sure it can be done quickly.

I also think we should run our test farm tests before landing changes here to make sure the pinned version of pip and friends is working well on various distros.

@ohemorange, are you interested in taking this?

**Comment by ohemorange** [comment]
Reposting here: #6682 is addressed by 19.0.1, but certbot-auto still hits #6687. Currently looking into getting that addressed.

**Comment by ohemorange** [comment]
@bmw yes

**Comment by ohemorange** [comment]
My plan here is to try three separate things, and put them up as three separate PRs so we can decide separately about them.

1. add `--no-download`. this will for sure fix everything right now for most users.
2. fix the potential certbot-apache filename thing. this will hopefully make certbot work with the current version of pip.
3. pin pip, as this issue actually says.

**Comment by ohemorange** [comment]
The PRs above have been tested on Ubuntu 16.04 with Python 2.7 and initial `virtualenv` of 15.0.1 and initial `pip` of 8.1.1. They should be tested on a lower initial `pip` (Debian jessie) and with Python 3 (CentOS, or test manually with `tools/venv3.py`).

**Comment by adferrand** [comment]
I close the issue, as the appropriate improvements have been developed, tested and released in 0.30.1.
