### ISSUE TITLE
Certbot-auto 0.30.1 fails to install with pip 19.0.1

### ISSUE THREAD

**Issue by jldeen** [certbot/certbot#6697]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 18.0.4.1 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
using certbot-auto via git repo (installed via `git clone https://github.com/certbot/certbot.git`) 

## I ran this command and it produced this output:
`sudo ./certbot-auto --no-bootstrap`
```
Creating virtual environment...
Installing Python packages...
Command "/opt/eff.org/certbot/venv/bin/python2.7 -u -c "import setuptools, tokenize;file='/tmp/pip-3yySnw-build/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /tmp/pip-oamDAe-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/eff.org/certbot/venv/include/site/python2.7/wheel" failed with error code 1 in /tmp/pip-3yySnw-build/
Traceback (most recent call last):
File "/tmp/tmp.cfxY1NQimR/pipstrap.py", line 177, in 
exit(main())
File "/tmp/tmp.cfxY1NQimR/pipstrap.py", line 164, in main
shell=True)
File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'pip install --no-index --no-deps -U --no-cache-dir /tmp/pipstrap-eTH3eH/pip-9.0.1.tar.gz /tmp/pipstrap-eTH3eH/setuptools-29.0.1.tar.gz /tmp/pipstrap-eTH3eH/wheel-0.29.0.tar.gz' returned non-zero exit status 1
```
## Certbot's behavior differed from what I expected because:
I expect the correct output:

```
Requesting to rerun ./certbot-auto with root privileges...
Creating virtual environment...
Installing Python packages...
Installation succeeded.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator apache, Installer apache

Which names would you like to activate HTTPS for?
```
###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
NA
## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
NA

## Additional relevant information: 
Originally hopped on issue #6682 but was asked to open a new issue. This first began today with the update to 0.30.1. I upgraded pip accordingly and now have 19.0.1 installed. To troubleshoot I ran the following series of commands, which worked. 
```
sudo rm certbot-auto
wget https://dl.eff.org/certbot-auto
export VIRTUALENV_NO_DOWNLOAD=1
chmod a+x certbot-auto
./certbot-auto --no-bootstrap --no-self-upgrade
```
This leads me to believe something is broken when upgrade to 0.30.1. I also have blown away venv via `sudo rm -rf /opt/eff.org/certbot/venv`

**Comment by ohemorange** [comment]
Thanks for reporting over here! You mentioned that it was working last night for you, right? That's surprising to me. Do you have the logs from that? Looking for what version of certbot-auto was running, and ideally what version of pip and virtualenv you had before you ran certbot-auto, and if possible also what version of virtualenv and pip certbot-auto installed.

**Comment by jldeen** [comment]
@ohemorange I just got it to work now by removing 0.30.1 and replacing it with 0.30.1 - see the end of my issue for all commands ran to remove certbot-auto. I can give you logs though if you still need. Pip version was still 19.0.1 and venv was a fresh install from today.

**Comment by ohemorange** [comment]
We're currently looking into this. In the meantime, the most correct fix for anyone else running into this is to use the ppa on Ubuntu 18.04. See instructions for Apache [here](https://certbot.eff.org/lets-encrypt/ubuntubionic-apache) and Nginx [here](https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx).

**Comment by ohemorange** [comment]
Hey @erikrose -- looks like changing the pinned version of setuptools in pipstrap to 30.3.0 fixes this issue. How do you find the URL to get the tarball directly from?And is it just a hash of the tarball in there?

This might lead us into problems with `--no-deps` but the easiest way to figure that out is to test that.

**Comment by jldeen** [comment]
@ohemorange Thanks for that! I did start to setup ppa for Ubuntu, however I wanted to use certbot-auto and I didn't think I could use that with the ppa. Am I incorrect?

**Comment by bmw** [comment]
Nice work finding that.

Not Erik but I've written/reviewed a few PRs to pipstrap over the years...

> How do you find the URL to get the tarball directly from?

If you look up the package and version on PyPI, you can find the link for the tarball. For instance, here's all the files for that version of setuptools. The full URL is:

https://pypi.python.org/packages/e0/b4/1e023e0f0e3a1475c146889f91989a306162c162d76eceac8ad13d6fad8d/setuptools-30.3.0.tar.gz

(The hostname shown by PyPI is different, but the path is the same. If you try and fetch the URL shown above, it redirects you a bunch before you wind up at the hostname given by PyPI.)

> And is it just a hash of the tarball in there?

Yep. SHA-256 hash of the file. The hash for the file linked above is 2ea217cc858de2ad59c87a5ccb4d22422abd8cf7235803b06df7983e1a581096.

> This might lead us into problems with --no-deps but the easiest way to figure that out is to test that.

Yeah. This will require a lot of testing and maybe also carefully looking at `setuptools` to make sure the changes they made between these versions won't cause any trouble for us.

Erik and I looked into this before the last time we bumped the version of setuptools used here. Going to dig a bit and see if I can find the relevant discussion and concerns.

**Comment by ohemorange** [comment]
@jldeen `certbot-auto` is just a wrapper around `certbot`, it does all of the same things, the `auto` just refers to the installation method that automatically updates immediately when we do a release. You might be referring to the automatic renewal functionality, which is present in `certbot`.

**Comment by erikrose** [comment]
Sorry for being a day behind on my email here. Looks like y'all did the Right Things. I especially enjoyed @bmw's extremely thorough commit message on 53d13ff3a32aa448a8320ae464bedf4fb7b12c52!
