### ISSUE TITLE
certbot-auto doesn't work on Fedora 29

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6698]
## My operating system is (include version):

Fedora 29

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

certbot-auto

## I ran this command and it produced this output:

```
# git checkout v0.30.0
# ./certbot-auto -n
<bunch of stuff>
Creating virtual environment...
./certbot-auto: line 1003: virtualenv: command not found
```

## Certbot's behavior differed from what I expected because:

`virtualenv` should probably be found.

**Comment by bmw** [comment]
Kind of? `certbot-auto` did used to work on Fedora and we're still passing tests on an old version in our test farm tests. I think what probably happened here is a more recent Fedora version changed the name of the virtualenv package and we haven't yet updated certbot-auto to reflect that.

I think we should fix this and I think doing so is probably pretty easy, however, I don't think it's a super high priority because we have very few Fedora users. As far as I know, no users have reported this bug yet.

**Comment by ohemorange** [comment]
I mean, is this a regression based on our recent changes in response to the `pip` issues.

**Comment by bmw** [comment]
Oh. No it is not.

**Comment by ohemorange** [comment]
> /usr/bin/virtualenv is now in the python3-virtualenv package
> The virtualenv command now comes from the python3-virtualenv package, as opposed to earlier releases where the command was in the python2-virtualenv. This effectively switches the command to Python 3; if you run virtualenv without any additional options, it will create Python 3 environments. Use virtualenv -p python2.7 to get the previously default behavior.

https://docs.fedoraproject.org/en-US/fedora/f29/release-notes/developers/Development_Python/

**Comment by bmw** [comment]
Nice find!

If all non-EOL'd Fedora versions made that change, I think this fix would be trivial. Unfortunately, it looks like Fedora 28 doesn't have a definitive deprecation date yet and looking at the pattern in https://en.wikipedia.org/wiki/Fedora_version_history, it will probably be at least a few months.

With that in mind, I think we need to modify certbot-auto to work with both package names.

@ohemorange, do you have the interest/cycles to work on this?

**Comment by ohemorange** [comment]
I don't think I can get to it this sprint, but happy to do it in a future one.
