### ISSUE TITLE
certbot-auto fails on Ubuntu 16.04 and 18.04

### ISSUE THREAD

**Issue by diolwe** [certbot/certbot#6701]
certbot-auto renew failed on several Ubuntu 16.04 and 18.04 (up to date) machines with:

<pre>
Command "/opt/eff.org/certbot/venv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-dd2_om-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-U04XuH-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/eff.org/certbot/venv/include/site/python2.7/wheel" failed with error code 1 in /tmp/pip-dd2_om-build/
Traceback (most recent call last):
  File "/tmp/tmp.KQjC2hSYai/pipstrap.py", line 177, in <module>
    exit(main())
  File "/tmp/tmp.KQjC2hSYai/pipstrap.py", line 164, in main
    shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'pip install --no-index --no-deps -U --no-cache-dir /tmp/pipstrap-JotPY8/pip-9.0.1.tar.gz /tmp/pipstrap-JotPY8/setuptools-29.0.1.tar.gz /tmp/pipstrap-JotPY8/wheel-0.29.0.tar.gz' returned non-zero exit status 1
</pre>

I tried to have a look at the internals of the files /tmp/tmp.KQjC2hSYai/pipstrap.py, /tmp/tmp.KQjC2hSYai/pipstrap.py - but I seem to have misunderstood something, because they aren't there (prob. inside some virtual environment only?): /tmp is empty. 

Any recommendations what to do?

**Comment by joohoi** [comment]
Hi! There's currently an ongoing issue with `pip`, and this work is tracked at #6697 

I'm closing this issue as duplicate.
