### ISSUE TITLE
Options for update_account missing

### ISSUE THREAD

**Issue by Klaus-Tockloth** [certbot/certbot#6712]
Certbot (0.30.0) does not show the options for "--update_account" with "certbot --help all":
```
certbot --help all
...
update_account:
  Options for account modification

unregister:
  Options for account deactivation.

  --account ACCOUNT_ID  Account ID to use (default: None)
...
```

"certbot --help update_account" shows this:
```
certbot --help update_account
usage: 

  certbot update_account --email updated_email@example.com [options]

optional arguments:
  -h, --help            show this help message and exit
  -c CONFIG_FILE, --config CONFIG_FILE
                        path to config file (default: /etc/letsencrypt/cli.ini
                        and ~/.config/letsencrypt/cli.ini)

update_account:
  Options for account modification

  -m EMAIL, --email EMAIL
                        Email used for registration and recovery contact. Use
                        comma to register multiple emails, ex:
                        u1@example.com,u2@example.com. (default: Ask).
  --eff-email           Share your e-mail address with EFF (default: None)
  --no-eff-email        Don't share your e-mail address with EFF (default:
                        None)

```

**Comment by adferrand** [comment]
In fact this is not a bug, but a potentially missing feature.

A given flag can be attached to several commands. Here, for instance, `--eff-mail` can be used for `register`, `update_account` and `automation`. Calling help for each of these command will show correctly the flag and its usage.

However, there is also the help on `all`, that display help for all commands. Currently the way the CLI help of Certbot is designed, is to assign the flag to one unique command (in fact, the first one on which the flag is attached). For `--eff-mail`, this is `register`, and the other command, in the help `all`, will not display the flag.

I think the way it is designed is to try to keep "short" the `all` help as a kind of detailed overview, by displaying only once each flag where is it more relevant, then allowing to get the complete help for a specific command once you know what you are looking for from this `all` help.

I am removing the bug flag. Improvement could certainly be done here, but I think it is not urgent and should wait. @bmw, what do you think of this?

**Comment by bmw** [comment]
Thanks for looking into this @adferrand. I agree we can wait on this.

In addition to how much doing this would add to our `--help all` output, doing it is kind of tricky with the way our argument parsing works. Each subcommand is an [argument group](https://docs.python.org/3/library/argparse.html#argument-groups) and you can't have the same flag in multiple argument groups.

Alternatively, we could stop telling people to run `--help all` and just use it ourselves for https://certbot.eff.org/docs/using.html#certbot-command-line-options, remove it entirely, or have the output look more like `--help subcommands` and then let people get the specific flags for each subcommand by running `--help <subcommand>`.
