### ISSUE TITLE
Print warning when you're renewing a certificate less than 25 days before expiration

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6719]
As suggested by @jsha, we could print a warning suggesting the user automates renewal if Certbot tries to renew a certificate and there's less than 25 days until the certificate expires. If there's less than 25 days, the user likely hasn't automated renewal (properly) because we tell people to run `certbot renew` every 12 hours and Certbot renews certificates when they're less than 30 days from expiration. I think this is a great idea.

**Comment by schoen** [comment]
Would you want to do this at the beginning or end of the process? (If at the end, only on success or on either success or failure?)

Is there a page in our documentation that we could point to? Maybe@jsha could compose an essay on letsencrypt.org about the very high importance that we ascribe to automation?

**Comment by jsha** [comment]
The integration guide currently recommends 30 day renewals, we could link to that.

**Comment by bmw** [comment]
> Would you want to do this at the beginning or end of the process? (If at the end, only on success or on either success or failure?)

I was personally thinking we'd just log a warning wherever is most natural in the code which is probably when checking whether or not we need to renew.

As part of the terminal cleanup we're trying to reduce Certbot's verbosity so warnings like this can occur anywhere and not be missed, but if we're worried about this being missed with the current state of things, we could also add the message to the `Reporter` which is the thing that prints the following text when Certbot exits:
```
IMPORTANT NOTES:
- blah
```

**Comment by bmw** [comment]
I think the best place to put this code is in https://github.com/certbot/certbot/blob/d56cd4ef01d3dbc1323c3464cedc7d150bb854f1/certbot/_internal/storage.py#L915.

**Comment by ali-alsabbah** [comment]
I’d like to work on this, probably over the weekend.

**Comment by ali-alsabbah** [comment]
My PR has been submitted :D 

Let me know if my warning is too verbose.

**Comment by bmw** [comment]
Hmm. I'm not personally particularly worried about this anymore either so I'm going to close it. @vernazxx, if you're looking for an issue to work on, maybe https://github.com/certbot/certbot/issues/6802 or https://github.com/certbot/certbot/issues/9598 would interest you?

**Comment by vernazxx** [comment]
OK. I'll look into one of those and leave a comment there.
Thanks.
