### ISSUE TITLE
pkg_resources.DistributionNotFound: acme>=0.29.0

### ISSUE THREAD

**Issue by muellermichel** [certbot/certbot#6721]
Tried to upgrade certbot; 

     yum uninstall certbot
     -> Complete!
     yum install python2-certbot-apache
     -> Complete

But then..

    certbot
    Traceback (most recent call last):
    File "/usr/bin/certbot", line 5, in <module>
    from pkg_resources import load_entry_point
    File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3011, in <module>
    parse_requirements(__requires__), Environment()
    File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: acme>=0.29.0

I'm aware that this is essentially https://github.com/certbot/certbot/issues/4934 but the resolution there didn't help me - the binary I have came in with the yum install, the old one was correctly removed (and was actually working)

## My operating system is (include version):
CentOS Linux release 7.5.1804 (Core)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
yum

## I ran this command and it produced this output:
see above

## Certbot's behavior differed from what I expected because:
not working

**Comment by mlipman** [comment]
I got the same error and fixed it by explicitly updating python2-acme:
`sudo yum install python2-acme`

However, I thought that since python2-acme is a dependency, yum installing or updating certbot would take care of it. Maybe a dependency list for certbot somewhere isn't updated?

**Comment by mlipman** [comment]
Hard for me to tell because it's all now installed

**Comment by ohemorange** [comment]
@muellermichel would you mind checking?

**Comment by muellermichel** [comment]
sorry, this can be closed - I missed the notifications for this and don't have the RedHat system to check this anymore.
