### ISSUE TITLE
Feature request: add environment variable CERTBOT_DOMAIN to all applicable hooks

### ISSUE THREAD

**Issue by Albrecht-S** [certbot/certbot#6722]
## My operating system is (include version):
Linux (Ubuntu 16.04)
Apache 2.4.18
certbot 0.28.0

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt-get (Ubuntu PPA)

## I ran this command and it produced this output:
`certbot renew`
and/or auto renewal (effectively the same command)

## Certbot's behavior differed from what I expected because:
I expected the environment variable CERTBOT_DOMAIN to be defined in pre, post, and deploy hooks, but this doesn't seem to be the case. I tried to use the hooks defined in  `/etc/letsencrypt/renewal-hooks/{pre,post,deploy}` . This is probably not documented anywhere for this particular case but I got the impression that it would be the case.

## Here is the issue I'd like to resolve
First of all, documentation of hooks is confusing, but I saw that there are already some issues raised regarding this.

My concern is to be able to define a pre-hook and a post-hook in `/etc/letsencrypt/renewal-hooks/{pre,post,deploy}` such that I can use the same hook for several domains and know which domain is being renewed. The reason is that I need to reconfigure the web server (apache) config for some of the domains so domain validation can work. The certs were acquired with certbot certonly in the first place.

### Proposed solution
Please add CERTBOT_DOMAIN and maybe more environment variables to all applicable invocations of hooks, not only to the 'manual' plugin hooks as it appears to be now (documented). I believe that this can be done w/o breaking anybody's configuration and would be helpful for others as well.

Documentation should be clear about which environment variables are defined in which hooks.

Side note: documentation should also mention in which order hooks are called. I assumed that deploy hooks would be called after post hooks but the order I found was pre - deploy - post. I see that this is useful but it should be documented.

### My current solution
Instead of having one central pre-hook and one post-hook script, resp. for all domains (with common code -> easier to maintain) I used --pre-hook and --post-hook to define per-domain hooks which works for me now.

## Suggested labels for this issue:

- "area: hooks"
- "area: renewal"

Thanks for the good work and for considering this RFE.

**Comment by ohemorange** [comment]
Thanks for the suggestion! @joohoi, is it simple to expose that variable for these hooks?

**Comment by joohoi** [comment]
Thanks for the well written and informative issue @Albrecht-S !

This usecase where actual pre- and post- hooks would be domain specific certainly wasn't on the table when designing the hook functionality. 

I'll look into this, but my initial take is that this would be a pretty simple addition that wouldn't have any negative side effects for other functionalities of Certbot, Tagging it for future development!

**Comment by Albrecht-S** [comment]
Thanks for your positive comments, @ohemorange and @joohoi.

After thinking about it a little more I'm not sure what the contents of CERTBOT_DOMAIN should be in the case of a certificate with multiple domains, e.g. `example.com` + `www.example.com`. And what is it currently in the `manual` plugin hooks described here: [Pre and Post Validation Hooks](https://certbot.eff.org/docs/using.html#pre-and-post-validation-hooks) ? The docs say:

> CERTBOT_DOMAIN: The domain being authenticated

It's singular "The domain" but the `--pre-hook` (etc.) is run only once per certificate (just tested), so what would it be? Any one of the domains or maybe a list? If the latter, what format? Again, the documentation is not clear about it.

That said, I'd like to extend my feature request to provide additionally the cert name being validated because this is clear and unambiguous. A possible format could be:

CERTBOT_CERTNAME: The certificate [name] being authenticated

Thanks for considering my request.

**Comment by joohoi** [comment]
> It's singular "The domain" but the --pre-hook (etc.) is run only once per certificate (just tested), so what would it be? Any one of the domains or maybe a list? If the latter, what format? Again, the documentation is not clear about it.

I believe it should work in the same way that tne `$RENEWED_DOMAINS` environmental variable works for deploy hooks. That means that the `$CERTBOT_DOMAIN` variable would have a space-delimited list of domains that Certbot is going to try to renew on this run. For example script that makes use of the `$RENEWED_DOMAINS` is available in the documentation, under the title [Renewing certificates](https://certbot.eff.org/docs/using.html#renewing-certificates).

**Comment by Albrecht-S** [comment]
Thanks for your comment and your explanations. I'm fine with everything that provides the relevant information and is documented. ;-)

> An example script that makes use of the $RENEWED_DOMAINS is available in the documentation, under the title Renewing certificates.

OK, I see:
> When renewing several certificates that have identical pre-hooks, only the first will be executed.

Question: if I have a domain that uses `/etc/letsencrypt/renewal-hooks/pre/my-hook xyz` (i.e. the standard hook script with a commandline argument), would this be considered "identical"? Is this at all possible? I think it should work (not tested, but comparing with the examples that use `service apache reload` or similar I assume it would). [Sorry, I'm not able to test this all on a production system.]

Further thinking aloud: we might better use the plural form with lists for the env var names like in `$RENEWED_DOMAINS`, hence:

- the `$CERTBOT_DOMAINS` variable would have a space-delimited list of **domains** that Certbot is going to try to renew on this run.
- the `$CERTBOT_CERTIFICATES` variable would have a space-delimited list of **certificates** that Certbot is going to try to renew on this run.

It is important that these variables contain the identical information in pre- and post- hooks since this is essential to prepare and to reset any (all) domain configurations. To be precise, the documentation of these variables in the context of post hooks could use the past tense, i.e. "tried to renew". This is different than the deploy hook that does only contain the domains that were successfully renewed.

The problem with the plural form of `$CERTBOT_DOMAINS` would be the conflict with the singular form `$CERTBOT_DOMAIN` as defined for the `manual plugin` hooks. I'm not sure what I would do about it, I'm certainly leaving this decision up to you. TIA.

**Comment by Albrecht-S** [comment]
Clarification: why `$CERTBOT_CERTNAMES` ?

In my use case I have three certificates with a total of four domains. We can assume that someone who uses the `$CERTBOT_CERTNAMES` variable knows which domains are included in each certificate.

The `$CERTBOT_CERTNAMES` variable would include the certificate names as they would be used in the `--cert-name` commandline argument, for instance in `certbot renew --cert-name example.com` which is not necessarily the domain "example.com" and/or can contain more than one domain.

The `$CERTBOT_DOMAIN(S)` variable would be useful for other usage scenarios.

PS: in my previous reply (edited later) I accidentally used `$CERTBOT_CERTIFICATES` instead of `$CERTBOT_CERTNAMES` but I think `$CERTBOT_CERTNAMES` would be the better choice in analogy with the commandline switch `--cert-name`.

**Comment by Albrecht-S** [comment]
I still think that my feature request would be a valuable addition, but I can't test with any later versions than `certbot 0.28.0` right now. My certbot usage works with a workaround but is a little unpleasant and not scalable.

I'm leaving it up to you (the maintainers) to close this issue if you think it is solved or not going to be solved at all.

Thanks for this great tool anyway.
