### ISSUE TITLE
`delete` might check if a certificate is in-use to avoid breaking web server configs

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#6734]
There's have been a few instances of Certbot users ending up with busted Apache/nginx configurations after using `certbot delete` against in-use certificates.

Without a sophisticated understanding of how the `apache`/`nginx` plugins work, the user couldn't  reasonably be expected to know that they need to remove these references before `delete` can be safely used.

I cannot find any user-facing documentation that identifies this limitation and risk.

Some potential approaches for mitigations:

- `delete`, when running interactively, might warn the user that they should ensure that no active configuration makes reference to this certificate. Additionally, include the same information in the help topic for `delete`. Bare minimum warning to the user. Or,
- `delete`, when running interactively, might refuse to run if there is an installer and it can use the installer plugin to identify that the certificate is in use. Requires an enhancement to `IInstaller`. Or,
- `delete` might undeploy the certificate if there is an installer, where undeploy might mean replacing with snakeoil or removing the virtual host entirely. Requires an enhancement to `IInstaller`.

**Comment by bmw** [comment]
I personally think we should do something here so I'm reopening this issue.
