### ISSUE TITLE
Apache plugin modifies all port 80 vhosts if requested domain is not found

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6736]
On Ubuntu 16.04, I experienced some behavior from our Apache plugin which surprised me.

If you request a certificate for a domain that is not found in your Apache config, the plugin modifies all HTTP vhosts to perform the challenge. I can't remember Apache's vhost precedence rules about this off the top of my head, but isn't there a default vhost we can modify?

We'd need to check the behavior on both Apache 2.2 and 2.4 before making any changes here.

I observed this behavior both with and without the changes in #6729.

I think we've had this behavior for a while so it isn't a high priority problem, but I think it's excessive and could slow things down a lot on systems with many virtual hosts.

cc @joohoi

**Comment by joohoi** [comment]
That's an absolute fallback in situations where we really can't find the correct `VirtualHost` to modify. Unfortunately the default `VirtualHost` for HTTP is the one that was included first in the whole Apache configuration tree. Usually for Ubuntu and Debian, this means the `000-default.conf` in sites-enabled -> sites-available (hence the naming of the default file). But there's no guarantee that the users haven't modified their configuration to have includes to other `VirtualHost` configuration files that are called before the `sites-enabled/*.conf` Include glob.

**Comment by bmw** [comment]
You're right.

I think I knew this at one point and forgot. If Apache is consistent, I think we may want to consider writing code in the future to determine what the first vhost is, but that's a separate issue so I'm closing this.

Thanks for the explanation!
