### ISSUE TITLE
Should we change the behavior of --preferred-challenges?

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6742]
There are at least a couple concerns here:

1. Despite the name being **preferred** challenges, this flag restricts Certbot to only performing challenge types given to this flag.
2. After support for TLS-SNI-01 is removed, `--preferred-challenges tls-sni` = never renew my certs.

We could change Certbot's behavior to try to perform challenges included in `--preferred-challenges` but if that's not possible, perform other challenge types instead.

Use cases that were brought up where the ability to restrict the challenge types that Certbot performs were:

1. The manual plugin where you have hooks set up to perform a certain challenge type. If we let other challenges be performed when using `--preferred-challenges` we risk trying to use these hooks with the wrong challenge type which would result in confusing errors that are hidden by the fact we're performing an unexpected challenge type.
2. @adferrand had concerns about more corporate environments where Certbot doing something like grabbing a different port could sound the alarms.
3. Our own testing.

If you have other thoughts, please share!

**Comment by bmw** [comment]
I just pulled some numbers to try and get an idea how many people will have set `--preferred-challenges tls-sni` on a recent version of Certbot potentially shooting themselves in the foot. Looking only at Certbot 0.28.0+ users over the past 60 days, these are the challenges used counted by unique IP address:

| Challenge Type | IP Count |
| --- | --- |
| http-01 | 823,060 |
| dns-01 | 58,177 |
| tls-sni-01 | 12,710 |

TLS-SNI-01 users are ~1.5% and I think this overestimates the number of users affected here as another possibility is they have Certbot 0.28.0+ but an older version of the Apache or Nginx plugin.

**Comment by maximillianh** [comment]
Given that user share, I think changing the behavior of --preferred-challenges is a 'nice-to-have' for the current milestone.

**Comment by bmw** [comment]
I'm personally not particularly worried about this anymore so I'm going to close this issue until there's a demand for a change here.
