### ISSUE TITLE
Certbot Fails To Rewrite HTTP Server Block And Renew Certificate

### ISSUE THREAD

**Issue by jwashington104** [certbot/certbot#6744]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Centos 6.9

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
`0 0,12 * * * env PATH="$PATH:/usr/sbin" /root/certbot-auto renew --pre-hook "/sbin/service nginx stop" --post-hook "/sbin/service nginx start" > /tmp/lets-encrypt_cert_log.log 2>&1`

[Errror in pastebin](https://pastebin.com/WB3QPiYW)

## Certbot's behavior differed from what I expected because:
It failed to rewrite the HTTP server block in my config which has resulted in the certificate not renewing due to a non-secure to sure redirect directive directing all traffic back to my application server:

```
2019-02-06 12:01:07,219:DEBUG:certbot_nginx.parser:Writing nginx conf tree to /etc/nginx/conf.d/subdomain.example.c
onf:
upstream server {
        server 127.0.0.1:8082;
        server 127.0.0.1:8083;
        server 127.0.0.1:8085;
        server 127.0.0.1:8086;
        server 127.0.0.1:8087;
        server 127.0.0.1:8088;
        server 127.0.0.1:8089;
        server 127.0.0.1:8090;
}

server {rewrite ^(/.well-known/acme-challenge/.*) $1 break; # managed by Certbot


    listen      subdomain.example.co.uk:80;
    server_name        subdomain.example.co.uk;
    return 301 https://$server_name$request_uri;
location = /.well-known/acme-challenge/aqYC2ZeettBJzUNNCeXCUR-ZsVNwH09fRCJjumKVHB4{default_type text/plain;return 200 aqYC2ZeettBJzUNNCeXCUR-ZsVNwH09fRCJjumKVHB4.lpk35UZHk93QJD25xXO8QY5cp41Zlsnd7-MVW8IITy8;} # managed by Certbot

}

server {
  # Allow large uploads
  client_max_body_size 500M;
  listen              subdomain.example.co.uk:443;
```

As you can see, it leaves in the `return 301 https://$server_name$request_uri;` which redirects all of the traffic back to HTTPS.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

[Log in pastebin](https://pastebin.com/gEUeFwzB)

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

[Config in pastebin](https://pastebin.com/gsRavvZh)

**Comment by ohemorange** [comment]
Hey @jwashington104! Please first try asking for help at https://community.letsencrypt.org/. There is a much larger community there of people familiar with the project who will be able to more quickly answer your questions.

I'd also recommend including the entire Nginx config, to figure out why Certbot didn't find the https server block that the server block you indicated is redirecting to.

**Comment by jwashington104** [comment]
Hey @ohemorange, thanks for the reply - I've included the entire config as a pastebin due to formatting issues, I've also included the log file as the template suggests. 

I would like to point out that up until version 30.2 of certbot, all was well with the auto renewal of certificates.
