### ISSUE TITLE
Test farm tests can silently drop test instances

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6748]
The tests in https://github.com/certbot/certbot/tree/master/tests/letstest can silently drop test instances causing neither success or failure to be reported from them with no mention of the problem of the dropped instance.

This is really bad. The error message that seems to occur when this happens is `ResponseParserError: Unable to parse response (no element found: line 1, column 0), invalid XML received:`. Maybe we can just fix that problem.

Alternatively or in addition to that, the tests create a file at the end called `results` containing the result from each test instance. We can assert that the number of instances we're reporting is equal to the number of instances we started (not counting boulder) and if they're not equal, error out.

**Comment by ohemorange** [comment]
If for some reason we do decide to fix this instead of deprecating the entire framework, this may be relevant: https://github.com/ceph/ceph/pull/13461/files
