### ISSUE TITLE
flag --version takes 16s to complete

### ISSUE THREAD

**Issue by ra1u** [certbot/certbot#6750]
## My operating system is (include version):
Raspbian GNU/Linux 7

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
upgraded from old version insatlled from certbot-auto.

## I ran this command and it produced this output:
```
time ./certbot --version --no-self-upgrade
certbot 0.30.2

real	0m16.749s
user	0m15.850s
sys	0m0.780s

```
## Certbot's behavior differed from what I expected because:
it requres approximatly 10e9 instructions to produce a string having 14 characters. I believe that is way to much of an energy/co2.
System is not loaded

```
$ uptime
17:42:17 up 54 days, 22:45,  1 user,  load average: 0.00, 0.03, 0.04
```

**Comment by bmw** [comment]
If you run the command again, does it take as long? I suspect `certbot-auto` had to set up Certbot's Python environment so it could be run to get you Certbot's `--version` output.

**Comment by bmw** [comment]
Since this hasn't seen any updates, I'm closing this issue.
