### ISSUE TITLE
Remove keyAuthorization field when POSTing challenges

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#6755]
The latest ACME spec doesn't want a keyAuthorization field when POSTing a challenge; now you just POST a signed "{}".

This is enforced by Pebble in `-strict` mode, and we're planning to make that the default on Feb 15: https://github.com/letsencrypt/pebble/issues/192. After that you'll be able to check out an older tagged version of Pebble to make sure tests don't break.

If there's any concern about breaking with non-public servers that aren't up-to-date with the spec, it would be reasonable to make this a v2-only change if that's not too hard. Boulder should support "{}" for both v1 and v2.

**Comment by adferrand** [comment]
@bmw, I take this also.
