### ISSUE TITLE
Fix test_letsencrypt_auto_certonly_standalone.sh test to work with cryptography OCSP

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6760]
The relevant lines of this file are https://github.com/certbot/certbot/blob/master/tests/letstest/scripts/test_letsencrypt_auto_certonly_standalone.sh#L25-L39.

There are a few problems with this code.

1. It uses LE's staging server meaning if the server is down, we can't successfully run tests.
2. It's relying on openssl's lenient behavior of expired OCSP responses only being a warning rather than a fatal error which is not what we're doing in our OCSP code written using `cryptography`.

After thinking about this a little bit, it's my opinion that instead of fixing the test here, we should remove them from this file and put them in our main integration tests.

The thing that was previously nice about having this test in our test farm test was we got to test with the various versions of openssl used on these different platforms, however, now this isn't so easy. We will have pinned a version of `cryptography` that allows us to use `cryptography` rather than shelling out to OpenSSL and our "oldest" requirements don't work on various distros. We could either install unpinned dependencies like `pip install cryptography<2.5` or create a 3rd set of pinnings which could be used for these tests, but both seem like a bad idea to me.

Instead, if we put a test in our main integration tests, they'd be run with both new and old versions of our dependencies allowing us to continue testing with `openssl` on some platforms. This certainly isn't as thorough, but it's better than nothing and seems sufficient to me especially with the way we're using OCSP checks.

We should be able to request the OCSP status of a certificate we revoked from boulder. jsha told me that we should be able to get a revoked response in <= 5s.

If (and only if) running `certbot certificates` like is done in the tests linked above still prints `TEST_CERT` if it's unable to reach boulder, I think we should add this test to our integration tests as well. If not, we can probably just delete these files assuming they're not used elsewhere.

**Comment by bmw** [comment]
@adferrand, I updated the above post to provide more information. Let me know what you think!

**Comment by adferrand** [comment]
I agree with you that this test will naturally fit in the CI during integration tests. Indeed, it is better to think of it in the perspective of `cryptography`, not `openssl` binary, as it will become the major situation in the future. And having a test running consistently is better than a flaky test.

Only question here is the exact meaning of having `TEST_CERT` in the output. It is expected to be displayed if the CA server is not available to give the OCSP response? And in this case, you are thinking in making the local Boulder temporarily unavailable (for instance, by giving a false directory URL to certbot for that), and assert the behavior?

**Comment by bmw** [comment]
> Only question here is the exact meaning of having `TEST_CERT` in the output.

This is only output if it's a certificate obtained from Let's Encrypt's staging server.

> It is expected to be displayed if the CA server is not available to give the OCSP response?

I think so! You also verifying this doesn't hurt, but I turned off the internet on my laptop and ran:
```
$ certbot certificates --config-dir sample-config/ --logs-dir $(mktemp -d) --work-dir $(mktemp -d)
Saving debug log to /var/folders/3b/zg8fdh5j71x92yyzc1tyllfw0000gp/T/tmp.qhIL1Zsfxv/letsencrypt.log
OCSP check failed for sample-config/live/a.encryption-example.com/cert.pem (are we offline?)
OCSP check failed for sample-config/live/b.encryption-example.com/cert.pem (are we offline?)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Found the following certs:
  Certificate Name: a.encryption-example.com
    Domains: a.encryption-example.com
    Expiry Date: 2017-03-23 01:02:00+00:00 (INVALID: TEST_CERT, EXPIRED)
    Certificate Path: sample-config/live/a.encryption-example.com/fullchain.pem
    Private Key Path: sample-config/live/a.encryption-example.com/privkey.pem
  Certificate Name: b.encryption-example.com
    Domains: b.encryption-example.com
    Expiry Date: 2017-03-23 01:04:00+00:00 (INVALID: TEST_CERT, EXPIRED)
    Certificate Path: sample-config/live/b.encryption-example.com/fullchain.pem
    Private Key Path: sample-config/live/b.encryption-example.com/privkey.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```
where `sample-config` is the directory used in the tests linked above.

To test this in our integration tests, we'd just continue to keep around the old staging certs and check the `certbot certificates` output, however, we should only be looking for `TEST_CERT` (and maybe `EXPIRED`?) and not looking for any OCSP information which should hopefully allow these tests to work regardless of the LE server status.

**Comment by adferrand** [comment]
As this test would be in certbot-boulder-integration-tests.sh, and we then have a live Boulder instance, I was also thinking to add an effective test for the REVOKED status.

The idea is to get a certificate, revoke it without deleting it, then expect REVOKED to be output when `certbot certificates` is executed.

What do you think?

**Comment by bmw** [comment]
Definitely! I was thinking we could do these somewhat strange tests on staging certificates in addition to checking the status of both revoked and unrevoked certificates against the local boulder and making sure the output matches.

**Comment by adferrand** [comment]
Done.
