### ISSUE TITLE
certbot release version is 0.17.0 in ubuntu 17 ppa  

### ISSUE THREAD

**Issue by chefjuanpi** [certbot/certbot#6768]
Hi i receibe a email about TLS-SNI-01
i verify and my system had certbot 0.25
but after upgrade the new version is 0.17.0 and is block in this version.
i not sure if is related but i use ubuntu 17, maybe you have a typo bug in the ppa?

## My operating system is (include version):
ubuntu 17

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt-get install certbot

## I ran this command and it produced this output:

    certbot --version

certbot 0.17.0

    apt-get update
    apt-get upgrade certbot

Reading package lists... Done
Building dependency tree
Reading state information... Done
certbot is already the newest version (0.17.0-2).
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

## Certbot's behavior differed from what I expected because:
cerbot version shoul be 0.28.0 or more

**Comment by chefjuanpi** [comment]
I save my day using Certbot-Auto for obtain my new certificates

**Comment by bmw** [comment]
Both of Ubuntu 17.04 and Ubuntu 17.10 have reached their end of life and are no longer receiving any updates from Ubuntu. For this reason, we are no longer supporting the platform either. I'm glad `certbot-auto` is currently working for you but I strongly recommend you upgrade to a newer version of Ubuntu.

If you need additional help using Certbot, I recommend posting at https://community.letsencrypt.org where there is a large group of people who would be happy to help you.
