### ISSUE TITLE
Support "new config file" when no vhost / servername found

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#677]
Using the Apache configurator on our acme-client test machine, I got a cert for one of my hostnames that didn't already exist in any of the Apache configs. At one point I got a screen that said "We were unable to find a vhost with a ServerName or Address of abcde.crud.net. Which virtual host would you like to choose?"

None of the virtual hosts was really suitable, since I hadn't yet set one up for that hostname on that machine. Ideally we should offer a "new vhost" option that would create a file in the appropriate directory. I realize this is probably quite fraught: How do we know if the new file will be included into the main config; what do we set its documentroot to.

As a stopgap, to make the messaging clearer, maybe we should add language like: "If you haven't yet set up Apache for <host> on this machine, we suggest doing that now and running letsencrypt again."

**Comment by jdkasten** [comment]
Sounds good.  The menu options display need some tweeking...
