### ISSUE TITLE
BIND needs restart for dns-01 to work

### ISSUE THREAD

**Issue by unioncos** [certbot/certbot#6773]
open or re-open ??  See https://github.com/certbot/certbot/issues/6322

I think certbot  with the rfc 2136 authenticator option being used does not send the equivalent of a "rndc sync" command to cause the .jnl file with the TXT entries to write to the zone file - and it fails without a manual restart while the 60 sec period is waiting.

Then on cleanup does not send the equivalent of a "rndc sync -clean"  to remove the entries and delete the journal file

On 2/14/2019 10:40 AM, Sydney wrote:
> Hello! I'm not currently working on Certbot; could you open an issue on
> GitHub? that way the team can track your request & problem ^_^ I'm happy
> to hop on and provide more context in the GH issue thread if you'd like!
>
> On 2/14/19 9:52 AM, Wilbur Union wrote:
I have the rfc2136 authenticator working with a cname setup for
letsencrypt wildcard ssl certificate dns-01 authentication renewal

During the 60 second delay wait for propagation I have to MANUALLY
restart BIND or the .jnl file with the TXT records sits uncommitted to
the zone

I have written about this before

I looked at the authenticator code but I am not a python programmer

Does the code issue a "rndc sync" command - because this is NEEDED to
flush the ..jnl file changes into the zone file so the authenticator can
"see" them

rndc sync -clean is needed to cleanup the TXT line entries

The problem is as you said in a previous email - certbot and the rfc
2136 authenticator command line option does not properly use actually
nsupdate.  It uses API calls using dns-python

Also since the freeze - thaw commands are obsoleted by sync in BIND 9.9
could this be an issue ??  See
ftp://ftp.isc.org/isc/bind9/9.9.0/RELEASE-NOTES-BIND-9.9.0.txt at NEW
FEATURES

"   "rndc sync" command dumps pending changes in a dynamic zone
    to disk without a freeze/thaw cycle. "rndc sync -clean" removes
    the journal file after syncing. "rndc freeze" no longer removes
    journal files. [RT #22473]"

The other way to dump the changes is to restart BIND or stop it and
start it which is my workaround to flush the changes

The fastest way for me is to use Webnmin and hit the recycle BIND icon.

Is it possible the rfc 2136 authenticator needs to be re-written to
issue a sync command before the propagation wait of 60 seconds

**Comment by noci2012** [comment]
rfc2136 tries to UPDATE the DNS directly (nsupdate) so it should not sync and allow for manual edit.
That does require that certbot is allowed to update the zone file where the key needs to go.

AFAICT nsupdate never requires execution of RNDC commands neither does it need reloading of files.
(The in memory structures get updated, as well as the journal, when flushed).
Can you check the log from bind for errors?

**Comment by bmw** [comment]
@joohoi, you know more about our RFC 2136 plugin than I do. Are you able to comment on this?

**Comment by joohoi** [comment]
Yeah, I feel that @noci2012 answered this pretty comprehensively. The BIND configuration probably plays a role here as well. In general, (wihle most likely not the case here), these kind of issues are best fixed upstream (in this case in `dnspython` library).

**Comment by noci2012** [comment]
If the reporter can show some of the setup s/he used relevant parts are master/slave involved?
how are those synced, can nsupdate add a key to the zone?  Then maybe some of the fog can be lifted.

**Comment by unioncos** [comment]
I waited for replies and none showed - until I recycled the page 5 days later.

According to sydney - nsupdate is not used by the rfc 2136 authenticator - - dnspython is -- as joohoi noted however doing testing with nsupdate - the same issue exhibits itself.  It writes a jnl file that sits

Doing testing with nsupdate I get this output and  debug

[root@main ~]# nsupdate -k ddns-key.txt -v update_dns1.txt
Outgoing update query:
;; ->>HEADER<<- opcode: UPDATE, status: NOERROR, id:      0
;; flags:; ZONE: 0, PREREQ: 0, UPDATE: 0, ADDITIONAL: 0
;; ZONE SECTION:
;_acme-challenge.yyyyyyyyyyy.com. IN        SOA

;; UPDATE SECTION:
_acme-challenge.yyyyyyyyyyyy.com. 120 IN TXT "xxxyyy4u2809frkobhjc kjlh bjbgkjn1234567wwwkkk"

Sending update to xxx.xxx.xxx.xxx#53
Outgoing update query:
;; ->>HEADER<<- opcode: UPDATE, status: NOERROR, id:  27035
;; flags:; ZONE: 1, PREREQ: 0, UPDATE: 1, ADDITIONAL: 1
;; ZONE SECTION:
;_acme-challenge.yyyyyyyyyy.com. IN        SOA

;; UPDATE SECTION:
_acme-challenge.yyyyyyyyyyy.com. 120 IN TXT "xxxyyy4u2809frkobhjc kjlh bjbgkjn1234567wwwkkk"

;; TSIG PSEUDOSECTION:
_acme-challenge.yyyyyyyyyyyy.com. 0 ANY TSIG hmac-sha512. 1551205853 300 64 JPZPIu9b/DpT6IbszonMV2Lko/BPDz3K30opNLYV5vv5ZHe7EdL5V+xH qya+NNBtpKXCpg6Pw2yZ5YEExzwOew== 27035 NOERROR 0


Reply from update query:
;; ->>HEADER<<- opcode: UPDATE, status: NOERROR, id:  27035
;; flags: qr ra; ZONE: 1, PREREQ: 0, UPDATE: 0, ADDITIONAL: 1
;; ZONE SECTION:
;_acme-challenge.yyyyyyyyyyy.com. IN        SOA

;; TSIG PSEUDOSECTION:
_acme-challenge.yyyyyyyyyyyy.com. 0 ANY TSIG hmac-sha512. 1551205853 300 64 rjsnCqlMQjQLBifmNa/ZyBnwLSo79u7t6TxAcLlW3fT6mJr2n07JqjVG l1cyFQTDpflGqP1H9r5mvrlHRL6YeA== 27035 NOERROR 0

this is using a setup process from http://agiletesting.blogspot.com/2012/03/dynamic-dns-updates-with-nsupdate-and.html

It lands in a .jnl file and it does not go to the zone file without a "rndc sync" command

update_dns1.txt is . . . 

server ns1.xxxxxxxx.com
debug yes
zone _acme-challenge.yyyyyyyyyy.com
update add _acme-challenge.yyyyyyyyyy.com 120 TXT "xxxyyy4u2809frkobhjc kjlh bjbgkjn1234567wwwkkk"
show
send

Obviously the key file is correct

I stumbled across this information by the author of a book DNS and BIND

"That's not the way BIND's processing of dynamic updates
works.

The dynamic updates take effect immediately, but aren't
written to the zone data file right away. Instead, the name
server stores a record of the change made in the .log file.
Roughly hourly, the name server writes the whole zone to
the zone data file and deletes the .log file.

. . . 

cricket

Men & Mice
DNS Software, Training and Consulting
www.menandmice.com

The DNS and BIND Cookbook, now available!
http://www.oreilly.com/catalog/dnsbindckbk/"

Cricket - is Cricket Liu the author

It tends to support that nothing in the rfc 2136 authenticator is flushing the TXT changes immediately to the actual zone file because the original poster says his updates are not getting written and take effect until an hour later

This came from a 16 year old post at https://bind-users.isc.narkive.com/QK0Lon5A/nsupdate-qestion

It is exactly the problem I have

What other parts of the BIND config could cause this ??

Why would it work fine on a restart or sync command ??

**Comment by unioncos** [comment]
Since this is going to be a head scratchier - I just used tmux and the sleep command to create a script that launches cerbot with the rfc 2136 authenticator and then waits 20 seconds and then restarts named in another window and when certbot exists - it does a rndc sync --clean

**Comment by noci2012** [comment]
again what is in the config for a zone...
There is NO need for the data to land on disk.... (what for...)
The memory image of BIND is what counts.... If data is **missing** there; it either finds it on disk for local zones or requests it through forwarders; or resolves it recursively from the root servers.

When YOU want to manual edit a zone, the in memory version needs to be save to disk, so you do:

rndc sync -clean  ; rndc freeze ZONE; edit ZONE file (including Soa sequence #) ; rndc thaw ZONE;

Otherwise the zone & Journal files  are mean for static data so the system can continue in the state it left when a restart is done.
