### ISSUE TITLE
certbot fails to aquire lock on read-only root

### ISSUE THREAD

**Issue by jo-so** [certbot/certbot#6774]
* OS: Debian, stable 9.7
* Certbot via Debian package, 0.28.0-1~deb9u1
* daily systemd.timer `/usr/bin/certbot -q renew` produces

```
certbot[8208]: The following error was encountered:
certbot[8208]: [Errno 30] Read-only file system: '/etc/letsencrypt/.certbot.lock'
certbot[8208]: Either run as root, or set --config-dir, --work-dir, and --logs-dir to writeable paths.
```

I'm using a read-only root and remount it with the pre- and post-hook. I've put a symlink on /etc/letsencrypt/.certbot.lock, but unfortunately certbot removes it every time the filesystem is writeable. I've changed certbot to respect the symlink.

```
--- /tmp/lock.py        2019-02-16 18:42:26.562278204 +0100
+++ /usr/lib/python3/dist-packages/certbot/lock.py      2019-02-16 18:46:13.877481907 +0100
@@ -119,6 +119,9 @@
     def release(self):
         """Remove, close, and release the lock file."""
         try:
-            compat.release_locked_file(self._fd, self._path)
+            path = self._path
+            if os.path.islink(path):
+                path = os.readlink(path)
+            compat.release_locked_file(self._fd, path)
         finally:
             self._fd = None
```

**Comment by jo-so** [comment]
This would fix #6087 and #5931, too.

**Comment by ohemorange** [comment]
@adferrand, this looks like it might tie into your lock work.

**Comment by Darkvater** [comment]
I think certbot implement either this or something similar. As it is now it is simply unworkable on a RO filesystem (unless one uses something like an overlayfs). The convention is that configuration files go into the /etc(/letsencrypt) path which is not expected to change at runtime, especially not with lock files.

Something like should be doable, no?
* read-only (immutable) configuration in /etc
* certificates in /var/lib
