### ISSUE TITLE
unable to find CentoOS' httpd24 path

### ISSUE THREAD

**Issue by nunoplopes** [certbot/certbot#6777]
When running certbot on CentOS with httpd24-httpd installed, I get the following error message:
```The error was: NoInstallationError('Could not find configuration root',)```

The problem seems to be that `override_centos.py` sets `server_root="/etc/httpd"`, while for the httpd24 packages it's `/opt/rh/httpd24/root/etc/httpd`.
This is not picked up because parser.py does this:
```
        self.root = os.path.abspath(root)
        self.loc = {"root": self._find_config_root()}
        self.parse_file(self.loc["root"])

        if version >= (2, 4):
            # Look up variables from httpd and add to DOM if not already parsed
            self.update_runtime_variables()
```

So cerbot only tries to figure out the right paths (through update_runtime_variables) *after* trying to parse the config file. The order should be changed.

**Comment by ohemorange** [comment]
@joohoi, do you have any insight here?

**Comment by joohoi** [comment]
Hi @nunoplopes ! You should be able to get on going with non-default paths by telling Certbot where to look configuration from, by using Apache plugin CLI variables (the following is a subset of Apache CLI config values, that I think can help you (the defaults shown below are OS dependent, so probably different ones for you):

```
  --apache-server-root APACHE_SERVER_ROOT
                        Apache server root directory (default: /etc/apache2)
  --apache-vhost-root APACHE_VHOST_ROOT
                        Apache server VirtualHost configuration root (default:
                        None)
  --apache-challenge-location APACHE_CHALLENGE_LOCATION
                        Directory path for challenge configuration (default:
                        /etc/apache2)
  --apache-ctl APACHE_CTL
                        Full path to Apache control script (default:
                        apache2ctl)
```

**Comment by nunoplopes** [comment]
Thanks. I found those as well. Eventually I found out the apache module doesn't work with wildcard certs.
Anyway, the code itself looks buggy. Please see my first post for details.

**Comment by joohoi** [comment]
> Thanks. I found those as well. Eventually I found out the apache module doesn't work with wildcard certs.
> Anyway, the code itself looks buggy. Please see my first post for details.

The operations taking place in `update_runtime_variables()` do not have an effect on Certbot finding the actual root configuration file (and the operations are rather naive). I believe you are referring to Certbot not being able to read the configuration tree correctly if it doesn't know about the additional `Include` and `Define` directives, right? 

Currently, the Certbot configuration parser unfortunately (and fortunately in this case) doesn't do a single-pass parsing for the configuration. So bascally everything in the code that tries to search or access parts of the configuration tree, recursively take the found `Include` and `Define` statements in account.

You are right in the fact that not doing a single-pass parsing for the configuration might give us too broad results in some cases. Problematic configuration example below:
```
<IfDefine test>
   # This should never be effective.
</IfDefine>
# ... later in the configuration
Define test
```

Now as we're not doing single-pass parsing, the contents of the `<IfDefine test>` would be seen as effective by Certbot parser. This is something that we're working to address currently as a part of larger Apache parser project we're doing.

I hope I understood your concern correctly, if this is not the case here, please feel free to elaborate.

**Comment by nunoplopes** [comment]
I think `self.update_runtime_variables()` should be called before `self._find_config_root()`. First it should try to find the root path (done in `update_runtime_variables()`) and only then access the config file. Right now the logic is inverted.

**Comment by joohoi** [comment]
I don't think that the root path discovery is done in `update_runtime_variables()`. That basically only leverages `apache2ctl` script (that's defined either in the OS specific defaults or provided on CLI by the user) to ensure that we won't miss OS specific `Include` or `Define` directives.

**Comment by pa-jberanek** [comment]
I just hit this on my CentOS 7 server with the SCL httpd24 installed. Tried using --apache-server-root /opt/rh/httpd24/root/etc/httpd but certbot kept trying to use /etc/httpd.

I only worked around it by moving /etc/httpd to /etc/httpd.off and symlinking /etc/httpd to /opt/httpd24/root/etc/httpd ...

**Comment by pa-jberanek** [comment]
Oh, I'd remove the standard CentOS 7 'httpd' package, except the certbot package requires it..

```
Removing:
 httpd                                           x86_64                          2.4.6-88.el7.centos                             @System                          9.4 M
Removing dependent packages:
 php                                             x86_64                          5.4.16-46.el7                                   @System                          4.4 M
 python2-certbot-apache                          noarch                          0.30.2-1.el7                                    @epel                            906 k
```

**Comment by pa-jberanek** [comment]
Apologies, given certbot's requirement is actually on mod_ssl, the full dnf output is more appropriate:

```
# dnf remove httpd
Dependencies resolved.
========================================================================================================================================================================
 Package                                         Arch                            Version                                         Repository                        Size
========================================================================================================================================================================
Removing:
 httpd                                           x86_64                          2.4.6-88.el7.centos                             @System                          9.4 M
Removing dependent packages:
 php                                             x86_64                          5.4.16-46.el7                                   @System                          4.4 M
 python2-certbot-apache                          noarch                          0.30.2-1.el7                                    @epel                            906 k
Removing unused dependencies:
 mod_ssl                                         x86_64                          1:2.4.6-88.el7.centos                           @System                          224 k

Transaction Summary
========================================================================================================================================================================
Remove  4 Packages
```

**Comment by pa-jberanek** [comment]
If I run "scl enable httpd24 -- /usr/bin/certbot -v renew --dry-run --apache-server-root /opt/rh/httpd24/root/etc/httpd" the output contains:

```
IOError: [Errno 2] No such file or directory: '/etc/httpd/conf.d/le_http_01_challenge_pre.conf'
```

but also at the top:

```
Var apache_server_root=/opt/rh/httpd24/root/etc/httpd (set by user).
```

**Comment by nunoplopes** [comment]
Yeh.. CentOS doesn't have a certbot package for httpd24, only for the main/old httpd. Would be nice to get this fixed, but I guess this is not the place.

**Comment by pa-jberanek** [comment]
Probably worth mentioning that my config worked with certbot 0.29.1 and only stopped working when I updated to certbot 0.30.2.

**Comment by pa-jberanek** [comment]
Hmm, it could have been further back, as certbot hadn't generated a new cert since Dec 2018 on this system.

**Comment by pa-jberanek** [comment]
OK, so a little investigation further it seems like the problem that I'm hitting is caused by the settings for "challenge_location" in certbot_apache/override_centos.py

This is set to "/etc/httpd/conf.d" which isn't where the challenges configuration needs to be put on a CentOS system with the SCL Apache 2.4 installed.

I've not discovered a way to override the value of challenge_location when running certbot - is it possible?

**Comment by pa-jberanek** [comment]
I tested my theory with the following change in certbot_apache/override_centos.py, which did allow a "certbot renew --dry-run" to complete successfully. This is clearly not a great solution :)

```
--- /usr/lib/python2.7/site-packages/certbot_apache/override_centos.py.orig     2019-01-25 21:15:41.000000000 +0100
+++ /usr/lib/python2.7/site-packages/certbot_apache/override_centos.py  2019-03-03 21:09:19.695452473 +0100
@@ -28,7 +28,7 @@
         le_vhost_ext="-le-ssl.conf",
         handle_modules=False,
         handle_sites=False,
-        challenge_location="/etc/httpd/conf.d",
+        challenge_location="/opt/rh/httpd24/root/etc/httpd/conf.d",
         MOD_SSL_CONF_SRC=pkg_resources.resource_filename(
             "certbot_apache", "centos-options-ssl-apache.conf")
     )
```

**Comment by joohoi** [comment]
You should be able to set challenge location on command line by using `--apache-challenge-location`

**Comment by pa-jberanek** [comment]
> You should be able to set challenge location on command line by using `--apache-challenge-location`

Thank you, that's not something I'd manage to figure out while grepping the code. Can this be set in the renewal configuration file too?

**Comment by joohoi** [comment]
> Thank you, that's not something I'd manage to figure out while grepping the code. Can this be set in the renewal configuration file too?

Yeah, it's automatically saved to renew configuration after it's used on the command line.

**Comment by pa-jberanek** [comment]
> > Thank you, that's not something I'd manage to figure out while grepping the code. Can this be set in the renewal configuration file too?
> 
> Yeah, it's automatically saved to renew configuration after it's used on the command line.

Presumably only when a renewal actually occurs? It's not added itself after either a dry-run or a "Cert not yet due for renewal".

**Comment by joohoi** [comment]
> Presumably only when a renewal actually occurs?

Yeah, that's right. Or you can request a certain certificate again with the same subset of domains just like you have done it initially.
