### ISSUE TITLE
Add info about --version parameter

### ISSUE THREAD

**Issue by sblondon** [certbot/certbot#6779]
`--help` parameter does not show the ability to get the version number of `cerbot` with `--version` parameter.
It's probably nice to document it for beginners.

The patch would be trivial by modifying lines around: https://github.com/certbot/certbot/blob/36c8a457133413925a902af7c599649fd05432a4/certbot/cli.py#L114

I installed the cerbot package provided by stretch-backports as said by the documentation (https://certbot.eff.org/lets-encrypt/debianstretch-apache).

```
$ certbot --version
certbot 0.28.0
```

**Comment by schoen** [comment]
Fixed in #6780 (you could use the "Fixes" keyword rather than "is attached to" to get GitHub to close the issue automatically when the PR is merged).

Thanks!

**Comment by sblondon** [comment]
@schoen thank you for the tip! :)
