### ISSUE TITLE
ACME: errors.ValidationError does not print `failed_authzrs`

### ISSUE THREAD

**Issue by daramousk** [certbot/certbot#6790]
## My operating system is (include version):
Debian 9.8

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
pip install acme

## I ran this command and it produced this output:
Traceback (most recent call last):
...
    order_resource = client.poll_and_finalize(authzr, deadline)
  File "/home/../odoo/eggs/acme-0.27.0-py2.7.egg/acme/client.py", line 674, in po
ll_and_finalize
    orderr = self.poll_authorizations(orderr, deadline)
  File "/home/../odoo/eggs/acme-0.27.0-py2.7.egg/acme/client.py", line 698, in po
ll_authorizations
    raise errors.ValidationError(failed)
ValidationError

## Certbot's behavior differed from what I expected because:
The ValidationError does not print out what was wrong

I am not sure if this is a bug or feature.

**Comment by joohoi** [comment]
I'm going to summon @bmw to answer if this is intentional or not.

However, if you have many challenges to solve, the error message output could get really cluttered, so this might well be an intended design. You can access the failed authzrs by doing:
```
try:
    client.poll_and_finalize(...)
except ValidationError as e:
    for rs in e.failed_authzrs:
        print("Whatever information you wish to pull from the failed authzrs")
```

**Comment by bmw** [comment]
I think printing this error nicely is just something we never really considered.

It could be done by adding a `__str__` method to error class which is found at https://github.com/certbot/certbot/blob/31b4b8e57c542577d35a20f87eaad60d5ce37193/acme/acme/errors.py#L86

**Comment by daramousk** [comment]
I have implemented this here https://github.com/certbot/certbot/pull/7066.

**Comment by osirisinferi** [comment]
Probably nice to implement and the PR fixing this issue is still open.
