### ISSUE TITLE
Dyn.com integration problems in certbot wildcard certificate renewal with manual hooks

### ISSUE THREAD

**Issue by strenker** [certbot/certbot#6793]
## My operating system is (include version):
Gentoo (default/linux/amd64/17.0/desktop/plasma (stable))

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
tekener ~ # emerge -pv certbot
[ebuild   R   ~] app-crypt/certbot-0.31.0::gentoo  USE="-test" PYTHON_TARGETS="python2_7 python3_6 -python3_4 -python3_5" 0 KiB
[ebuild   R   ~] app-crypt/acme-0.31.0::gentoo  USE="-test" PYTHON_TARGETS="python2_7 python3_6 -python3_4 -python3_5" 0 KiB

## I ran this command and it produced this output:
certbot renew --dry-run --config /etc/letsencrypt/cli.ini --preferred-challenges=dns --manual --manual-auth-hook /usr/local/bin/certbot-dns-hook.sh --manual-cleanup-hook /usr/local/bin/certbot-dns-cleanup-hook.sh --manual-public-ip-logging-ok
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/trenker.xyz.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert not due for renewal, but simulating renewal for dry run
Plugins selected: Authenticator manual, Installer None
Renewing an existing certificate
Performing the following challenges:
dns-01 challenge for trenker.xyz
dns-01 challenge for trenker.xyz
Waiting for verification...
Cleaning up challenges
Attempting to renew cert (trenker.xyz) from /etc/letsencrypt/renewal/trenker.xyz.conf produced an unexpected error: Failed authorization procedure. trenker.xyz (dns-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect TXT record "ZeN953IpV68wCn0aBWb6EzesihOV7IVvvfozzOfe7TI" found at _acme-challenge.trenker.xyz. Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/trenker.xyz/fullchain.pem (failure)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/trenker.xyz/fullchain.pem (failure)
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates above have not been saved.)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1 renew failure(s), 0 parse failure(s)

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: trenker.xyz
   Type:   unauthorized
   Detail: Incorrect TXT record
   "ZeN953IpV68wCn0aBWb6EzesihOV7IVvvfozzOfe7TI" found at
   _acme-challenge.trenker.xyz

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
tekener ~ # certbot renew --dry-run --config /etc/letsencrypt/cli.ini --preferred-challenges=dns --manual --manual-auth-hook /usr/local/bin/certbot-dns-hook.sh --manual-cleanup-hook /usr/local/bin/certbot-dns-cleanup-hook.sh --manual-public-ip-logging-ok
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/trenker.xyz.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert not due for renewal, but simulating renewal for dry run
Plugins selected: Authenticator manual, Installer None
Renewing an existing certificate
Performing the following challenges:
dns-01 challenge for trenker.xyz
dns-01 challenge for trenker.xyz
Waiting for verification...
Cleaning up challenges
Attempting to renew cert (trenker.xyz) from /etc/letsencrypt/renewal/trenker.xyz.conf produced an unexpected error: Failed authorization procedure. trenker.xyz (dns-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect TXT record "ftXt2xzybG7u220pxsArlk7KipyoetWZ9A2Ia1-GeWg" found at _acme-challenge.trenker.xyz. Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/trenker.xyz/fullchain.pem (failure)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/trenker.xyz/fullchain.pem (failure)
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates above have not been saved.)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1 renew failure(s), 0 parse failure(s)

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: trenker.xyz
   Type:   unauthorized
   Detail: Incorrect TXT record
   "ftXt2xzybG7u220pxsArlk7KipyoetWZ9A2Ia1-GeWg" found at
   _acme-challenge.trenker.xyz

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.

## Certbot's behavior differed from what I expected because:
I ran the above command 18 times and it worked exactly once.
The hook-scripts set/delete the DNS-01-Challenge utilizing "nsupdate". They work as desired.

The Problem is a race condition. The Cert to renew contains two subjects/subjectAltName with domain.tld and *.domain.tld.

Certbot calls the challenge hook two times (i believe 1 call for validating the subject and 1 call for validating the subjectAltName contaiing the wildcard). The Problem is, that a given TXT-Record can exist just once (its unique, not like A- or AAAA-Records which can exist multiple times).

What happens is that the second challenge overrides the first one, but certbot first issues all the challenges and then tries to verify these challenges. The verification of the first challenge always fails because the challenge is overridden by the second one.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
see attachment

[letsencrypt.log](https://github.com/certbot/certbot/files/2897179/letsencrypt.log)

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
not relevant

**Comment by alexzorin** [comment]
> The Problem is, that a given TXT-Record can exist just once (its unique, not like A- or AAAA-Records which can exist multiple times).

This is not the case - they are just like A records in that respect.

e.g.

    $ dig +noall +answer _acme-challenge.plugindev.ga txt
    _acme-challenge.plugindev.ga. 599 IN    TXT     "SLqPIPKURLJYkWvm8Xl1tpJP3WKNMNfYKqC0cCxHAxo"
    _acme-challenge.plugindev.ga. 599 IN    TXT     "7S4ZVbhZ0NU86o1qK0xnEaInqHRy4pB7KZem1nQva2Q"

**Comment by strenker** [comment]
> > The Problem is, that a given TXT-Record can exist just once (its unique, not like A- or AAAA-Records which can exist multiple times).
> 
> This is not the case - they are just like A records in that respect.
> 
> e.g.
> 
> ```
> $ dig +noall +answer _acme-challenge.plugindev.ga txt
> _acme-challenge.plugindev.ga. 599 IN    TXT     "SLqPIPKURLJYkWvm8Xl1tpJP3WKNMNfYKqC0cCxHAxo"
> _acme-challenge.plugindev.ga. 599 IN    TXT     "7S4ZVbhZ0NU86o1qK0xnEaInqHRy4pB7KZem1nQva2Q"
> ```

You are right!

The problem lies with my DNS-Provider dyn.com. Dyn.com overrides the first challenge-TXT-record with the second one. At least when I add it with nsupdate.

So certbot renewal would work with dyn.com if the workflow would be "challenge, then test; next chellenge, next test; ... and so on"

**Comment by alexzorin** [comment]
> At least when I add it with nsupdate

You could try [certbot-dns-rfc2136](https://certbot-dns-rfc2136.readthedocs.io/en/latest/) instead of shelling out to `nsupdate`, you may find some success.

acme.sh and lego also provide implementations for DNS validation for Dyn (via its API), so if you wish to continue with your authentication hook, you could refer to those to see how they modify record sets without overwriting others.

**Comment by adferrand** [comment]
According to the documentation of dyndns, there seems to have three way to write a TXT record:
* add a record: https://help.dyn.com/create-txt-record-api/
* update a record: https://help.dyn.com/update-txt-record-api/
* replace all records: https://help.dyn.com/replace-txt-records-api/

I suspect you use the last one, that is executed on a `PUT` verb. The first one seems to correspond to the usual endpoint to append a new TXT record. It is triggered on a `POST` verb.

You should check precisely which endpoint you are using in your manual hooks.

**Comment by strenker** [comment]
> You could try [certbot-dns-rfc2136](https://certbot-dns-rfc2136.readthedocs.io/en/latest/) instead of shelling out to `nsupdate`, you may find some success.

Good Idea. I just have to find out, how to install the plugin. Its not in Gentoo's portage tree.

> acme.sh and lego also provide implementations for DNS validation for Dyn (via its API), so if you wish to continue with your authentication hook, you could refer to those to see how they modify record sets without overwriting others.

My understanding is, that whith acme.sh I have to use nsupdate as well, since I am on a DDNS account with Dyn.com and not on a Managed DNS account where the REST-API could be used, too.

**Comment by strenker** [comment]
> According to the documentation of dyndns, it seems there are three ways to write a TXT record:
> 
> * add a record: https://help.dyn.com/create-txt-record-api/
> * update a record: https://help.dyn.com/update-txt-record-api/
> * replace all records: https://help.dyn.com/replace-txt-records-api/
> 
> I suspect you use the last one, that is executed on a `PUT` verb. The first one seems to correspond to the usual endpoint to append a new TXT record. It is triggered on a `POST` verb.
> 
> You should check precisely which endpoint you are using in your manual hooks.

The REST-API is as of my understanding only available for Dyn.com Managed DNS customers. I am on a DDNS account.

**Comment by schoen** [comment]
Maybe you could also ask on https://community.letsencrypt.org/ to see whether other people have had success with this DNS provider.

**Comment by noci2012** [comment]
> > You could try [certbot-dns-rfc2136](https://certbot-dns-rfc2136.readthedocs.io/en/latest/) instead of shelling out to `nsupdate`, you may find some success.
> 
> Good Idea. I just have to find out, how to install the plugin. Its not in Gentoo's portage tree.
> 

Actually there is a request on this.   https://bugs.gentoo.org/646298
(Although the version mentions  22..,   it will still work woth the latest 0.32.0

[I] app-crypt/certbot-dns-rfc2136 [1]
     Available versions:  (~)0.30.0 (~)0.30.1 (~)0.31.0 (~)0.32.0 {PYTHON_TARGETS="python2_7 python3_4 python3_5 python3_6"}
     Installed versions:  0.32.0[?](08:46:12 PM 03/09/2019)(PYTHON_TARGETS="python2_7 python3_5 python3_6 -python3_4")
     Homepage:            https://github.com/certbot/certbot https://letsencrypt.org/
     Description:         RFC2136 DNS plugin for certbot (Let's Encrypt Client)

**Comment by strenker** [comment]
> and then install it.

I managed to install `app-crypt/certbot-dns-rfc2136` into my local portage tree. But it does not work with dyn.com.

The plugin uses the the same server-ip as configured in the plugin-config-file-parameter `dns_rfc2136_server` for DNS-queries (SOA-Records) to determine the right DNS-Zone for the update (i did a tcpdump trace to verify this). But this kind of queries are not supported for the same IP-Address which has to be used for the updates. At least with dyn.com. 

It would have been a better idea, to make DNS-update-zone configurable by the plugin-config-file as well.

**Comment by noci2012** [comment]
That server is the only server that is specified in configs.
Not sure why you can update a server and not query it. (if only to verify settings just done).
Querying somewhere else, might give stale records (due to TTL, slow forwards to slaves).
The update zone is zone file that specifies: _acme-challenge.{the domain}... . not a lot of choice there.  The zone is the SOA that is above this [ DNS setup requirements AFAIK ].
So if _ACME-challenge is setup as a zone, then it should also have a SOA record set, if it is one higher then the zone is {the domain}.

**Comment by strenker** [comment]
> That server is the only server that is specified in configs.

Dyn.com provides just one FQDN for its update-server which resolves as of now to a single A-record.

> Not sure why you can update a server and not query it. (if only to verify settings just done).

I do not know either.

> Querying somewhere else, might give stale records (due to TTL, slow forwards to slaves).

This is tunable by `--dns-rfc2136-propagation-seconds`

> The update zone is zone file that specifies: _acme-challenge.{the domain}... . not a lot of choice there. The zone is the SOA that is above this [ DNS setup requirements AFAIK ].

Why probe for the SOA? just use **the domain**

**Comment by noci2012** [comment]
> Why probe for the SOA? just use the domain
because there exist environment (which was the previous way to setup DNS authentication)
where the _acme_challenge was in a separate zone,  even on a distinct server because the DNS server could not even be updated.   Therefore the SOA record needs to be queried to establish where the update should go. (the _acme_challenge, or the domain.xxx.yyy.tld zone, or the xxx.yyy.tld zone...)
the first SOA that is found determines the server to update.

>> Querying somewhere else, might give stale records (due to TTL, slow forwards to slaves).
> This is tunable by --dns-rfc2136-propagation-seconds
No this is the delay between the update to DNS and signaling the boulder server that it may query the record.
