### ISSUE TITLE
Sudo certbot renew --dry-run ERROR

### ISSUE THREAD

**Issue by bmac7** [certbot/certbot#6796]
I received an email from Let's Encrypt telling me I need to update my ACME client to use an alternative validation method (HTTP-01, DNS-01 or TLS-ALPN-01).  Currently using TLS-SNI-01.. I was following the guide below and received an error while running the final command in the tutorial:

https://community.letsencrypt.org/t/how-to-stop-using-tls-sni-01-with-certbot/83210

## It produced this output:
"Client with the currently selected authenticator does not support any combinatio                                                                                                                                                             n of challenges that will satisfy the CA. Attempting to renew cert (-------------) from /etc/letsencrypt/renewal/--------------.conf produced an unexpected error: Client with 
the currently selected authenticator does not support any combination of challenges 
that will satisfy the CA.. Skipping."

![image](https://user-images.githubusercontent.com/48020679/53419255-84180880-39a7-11e9-888b-5002145adaf4.png)

**Comment by adferrand** [comment]
Hello!

Could you provide the edited content of /etc/letsencrypt/***.conf? I suspect its content is wrong in some way. Also, could you double check the version of Certbot you are using?

**Comment by bmac7** [comment]
using version 0.17.0

Conf file:
![image](https://user-images.githubusercontent.com/48020679/53493734-0ff26900-3a6a-11e9-8196-9183c7832143.png)

**Comment by adferrand** [comment]
Your configuration is valid. This indicates that your certbot version is too old. Could you check that your certbot version is 0.28.0 or higher, using `certbot --version` command?

If not, I invite you to go to https://certbot.eff.org, and, regarding your webserver and os system, follow the given instructions to upgrade Certbot.

**Comment by bmac7** [comment]
I had certbot 0.17.0..  I went on their website and followed the instructions and now when I use the certbot command I get the following error:
![image](https://user-images.githubusercontent.com/48020679/53504206-864d9600-3a7f-11e9-941d-450d1cee62b0.png)

**Comment by adferrand** [comment]
Thanks for your response. From this log, it looks like that your system's Python environment is in an unstable state. This typically happens when Python packages are installed using a mix of various package managers, like `apt` and `pip`. Unfortunately we cannot help you to debug your specific situation here. I would advice you to post about your situation on the Certbot community forum: https://community.letsencrypt.org. You will find there a large group of people really familiar with the project, and very likely to be helpful for you.
