### ISSUE TITLE
ImportError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by zvermafia** [certbot/certbot#6797]
## I ran this command:
`sudo certbot --nginx`

and it produced this output:
```
Traceback (most recent call last):
  File "/usr/bin/certbot", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named 'pkg_resources'
```

**Comment by adferrand** [comment]
Hello! Could you provide the full stacktrace generated by certbot on your command?

**Comment by zvermafia** [comment]
How to do it? I showed all output of the command...

**Comment by adferrand** [comment]
Try enable the maximum verbosity on Certbot, you can add the flags `--debug -vv` to the certbot cli.

**Comment by adferrand** [comment]
Also, for the context, so you saw this error from a first install of Certbot through certbot-auto?

**Comment by zvermafia** [comment]
> Try enable the maximum verbosity on Certbot, you can add the flags `--debug -vv` to the certbot cli.

**Command:** `sudo certbot --nginx --debug -vv`
**Output:**
```
Traceback (most recent call last):
  File "/usr/bin/certbot", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named 'pkg_resources'
```



> Also, for the context, so you saw this error from a first install of Certbot through certbot-auto?

Firstly I saw this from already installed and worked certbot auto, then I tried to remove -> install but it didn't help (result is the same, not worked).

**Comment by sensiarion** [comment]
Fixed by reinstalling python3 setup tools
` sudo apt-get install python3-setuptools`

**Comment by GabLeRoux** [comment]
Getting the same issue on an archlinux server. I did run with strace, couldn't find anything interesing. I do have `python-setuptools` installed. Running with `--debug -vv` doesn't change output.

**Comment by alexjurkiewicz** [comment]
This fixed the issue for me:

```
apt install --reinstall python3-pkg-resources python3-setuptools
```

**Comment by zvermafia** [comment]
I'm closing this issue because it's been a long time and I'm not working on it anymore. And also it seems there is a solution from @alexjurkiewicz.

**Comment by alexjurkiewicz** [comment]
Please don't close the issue... It's still an issue for others. Just click unsubscribe.

**Comment by bmw** [comment]
The installation method used in the initial report here was certbot-auto. certbot-auto has been deprecated, will error out on new systems, and existing installations are no longer receiving updates. Because of this, I'm closing this issue, but if you're having this problem with another installation method, please open a new issue.

**Comment by phayes** [comment]
This is still an issue on a fresh install of certbot (via homebrew) on Mac Ventura
