### ISSUE TITLE
certbot-auto --apache doesn't work on default Fedora config

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6828]
## My operating system is (include version):

Fedora 28

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

certbot-auto

## I ran this command and it produced this output:

On a freshly installed Fedora 28 machine I ran:

```
dnf install httpd wget -y
wget https://dl.eff.org/certbot-auto
chmod +x certbot-auto
./certbot-auto --apache --non-interactive
```

The relevant certbot-auto output is:
```
Error while running apachectl configtest.

AH00526: Syntax error on line 102 of /etc/httpd/conf.d/ssl.conf:
SSLCertificateFile: file '/etc/pki/tls/certs/localhost.crt' does not exist or is empty

The apache plugin is not working; there may be problems with your existing configuration.
The error was: MisconfigurationError("Error while running apachectl configtest.\n\nAH00526: Syntax error on line 102 of /etc/httpd/conf.d/ssl.conf:\nSSLCertificateFile: file '/etc/pki/tls/certs/localhost.crt' does not exist or is empty\n",)
```

## Certbot's behavior differed from what I expected because:

certbot-auto should work on the system's default configuration

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

```
2019-03-07 23:09:59,032:DEBUG:certbot.main:certbot version: 0.32.0
2019-03-07 23:09:59,033:DEBUG:certbot.main:Arguments: ['--apache', '--non-interactive']
2019-03-07 23:09:59,033:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2019-03-07 23:09:59,053:DEBUG:certbot.log:Root logging level set at 20
2019-03-07 23:09:59,053:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2019-03-07 23:09:59,055:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2019-03-07 23:09:59,164:ERROR:certbot.util:Error while running apachectl configtest.

AH00526: Syntax error on line 102 of /etc/httpd/conf.d/ssl.conf:
SSLCertificateFile: file '/etc/pki/tls/certs/localhost.crt' does not exist or is empty

2019-03-07 23:09:59,165:DEBUG:certbot.plugins.disco:Misconfigured PluginEntryPoint#apache: Error while running apachectl configtest.

AH00526: Syntax error on line 102 of /etc/httpd/conf.d/ssl.conf:
SSLCertificateFile: file '/etc/pki/tls/certs/localhost.crt' does not exist or is empty
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/plugins/disco.py", line 132, in prepare
    self._initialized.prepare()
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/configurator.py", line 248, in prepare
    self.config_test()
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/configurator.py", line 2227, in config_test
    raise errors.MisconfigurationError(str(err))
MisconfigurationError: Error while running apachectl configtest.

AH00526: Syntax error on line 102 of /etc/httpd/conf.d/ssl.conf:
SSLCertificateFile: file '/etc/pki/tls/certs/localhost.crt' does not exist or is empty

2019-03-07 23:09:59,166:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.entrypoint:ENTRYPOINT
Initialized: <certbot_apache.override_centos.CentOSConfigurator object at 0x7f9926b67890>
Prep: Error while running apachectl configtest.

AH00526: Syntax error on line 102 of /etc/httpd/conf.d/ssl.conf:
SSLCertificateFile: file '/etc/pki/tls/certs/localhost.crt' does not exist or is empty

2019-03-07 23:09:59,167:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
```

I looked into this a bit and the problem is that `/etc/pki/tls/certs/localhost.crt` isn't created until the httpd systemd service is (re)started after `mod_ssl` is installed which is not being done by certbot(-auto).

I'm not sure what the best approach is to fix this. @joohoi, do you have any ideas?

**Comment by joohoi** [comment]
Is this specific to Fedora 28, or are other versions of Fedora affected as well?

Regardless, I think the least interfering thing to do here would be to override `ApacheConfigurator.prepare()` in the distro specific overrides, and check if we're running affected version of Fedora. If this is the case, we'd do an additional `configcheck` and catch the possible exception. If exception was thrown, we should try to restart the service, and then execute the `ApacheConfigurator.prepare()`.

The only downside of this would be that if the user had an actually broken configuration, but the httpd was running, the restart action would basically kill it, so we might need to parse the `configtest` output to see if the error is due to this unfortunate feature or something else.

**Comment by bmw** [comment]
This affects all non-EOL'd Fedora versions. It doesn't seem to affect any RHEL based systems, but it may affect RHEL 8 when it comes out. Fedora made this change in September 2017[1].

I think the solution you proposed here is the simplest one. I'm a little hesitant to rely too much on the exact error printed because I think that could change if things are refactored in the Fedora package.

One thing that's slightly awkward is we have to restart httpd with `systemctl` for this to work. I could see this potentially causing issues if the user has a custom Apache instance and we don't offer the user a way to control this behavior, but for the sake of simplicity, I think we shouldn't worry about making it configurable for now. I think we should only restart Apache with `systemctl` in this very specific scenario and if a user comes around asking for a way to make this configurable, we can consider adding it and give them the workaround of making the configuration test pass until the fix is released.

What do you think?

[1] https://src.fedoraproject.org/rpms/httpd/pull-request/1#
