### ISSUE TITLE
Tell certbot-auto users up front when their operating system is at EOL

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#6832]
We've had a number of issues where someone is using `certbot-auto` under an operating system that's no longer supported by the OS vendor. Among other ways that this can cause Certbot to fail, it could mean that `certbot-auto` can no longer download particular dependencies because they're no longer served by the OS package repositories, or because a particular version of a dependency isn't available because the OS vendor hasn't packaged it.

We would like to detect this situation where possible and explicitly tell the user right at the outset that `certbot-auto` isn't supported and that the underlying OS needs to be upgraded. (`certbot-auto` can still attempt to run, but if it fails, there should be a clear indication of why.)

This is an incremental benefit in the sense that detecting and warning about any particular EOL distribution or release is better than not detecting it, even if we haven't detected all other EOL systems.

Cc @adferrand, @bmw

**Comment by schoen** [comment]
(Are there cases in which OS-packaged versions of Certbot should also do this? If we try to do this outside of `certbot-auto`, will that potentially antagonize the OS packagers, who might feel that there are other ways that they prefer to handle this situation?)

**Comment by bmw** [comment]
certbot-auto has been deprecated, will error out on new systems, and existing installations are no longer receiving updates so I'm closing this.
