### ISSUE TITLE
certbot-auto: line 878: python3: command not found

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#6837]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
CentOS release 6.10 (Final)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
```sh
certbot-auto
WARNING: couldn't find Python 2.7+ to check for updates.
/root/bin/certbot-auto: line 878: python3: command not found
```

## Certbot's behavior differed from what I expected because:

```sh
sh -x ./certbot-auto
+ set -e
+ '[' -z /root ']'
+ '[' -z '' ']'
+ XDG_DATA_HOME=/root/.local/share
+ '[' -z '' ']'
+ export OLD_VENV_PATH=/root/.local/share/letsencrypt
+ OLD_VENV_PATH=/root/.local/share/letsencrypt
+ export VENV_PATH=/opt/eff.org/certbot/venv
+ VENV_PATH=/opt/eff.org/certbot/venv
+ VENV_BIN=/opt/eff.org/certbot/venv/bin
+ BOOTSTRAP_VERSION_PATH=/opt/eff.org/certbot/venv/certbot-auto-bootstrap-version.txt
+ LE_AUTO_VERSION=0.32.0
++ basename ./certbot-auto
+ BASENAME=certbot-auto
+ USAGE='Usage: certbot-auto [OPTIONS]
A self-updating wrapper script for the Certbot ACME client. When run, updates
to both this script and certbot will be downloaded and installed. After
ensuring you have the latest versions installed, certbot will be invoked with
all arguments you have provided.

Help for certbot itself cannot be provided until it is installed.

  --debug                                   attempt experimental installation
  -h, --help                                print this help
  -n, --non-interactive, --noninteractive   run without asking for user input
  --no-bootstrap                            do not install OS dependencies
  --no-self-upgrade                         do not download updates
  --os-packages-only                        install OS dependencies and exit
  --install-only                            install certbot, upgrade if needed, and exit
  -v, --verbose                             provide more output
  -q, --quiet                               provide only update/error output;
                                            implies --non-interactive

All arguments are accepted and forwarded to the Certbot client when run.'
+ export CERTBOT_AUTO=./certbot-auto
+ CERTBOT_AUTO=./certbot-auto
+ '[' certbot-auto = letsencrypt-auto ']'
+ '[' '' = 1 -o '' = 1 ']'
+ command -v command
+ export 'EXISTS=command -v'
+ EXISTS='command -v'
+ '[' '' = --cb-auto-has-root ']'
+ SetRootAuthMechanism
+ SUDO=
+ '[' -n '' ']'
++ id -u
+ test 0 -ne 0
+ '[' -n '' ']'
+ MIN_PYTHON_VERSION=2.7
++ echo 2.7
++ sed 's/\.//'
+ MIN_PYVER=27
+ BOOTSTRAP_DEB_COMMON_VERSION=1
+ BOOTSTRAP_RPM_COMMON_VERSION=1
+ BOOTSTRAP_RPM_PYTHON3_VERSION=1
+ BOOTSTRAP_SUSE_COMMON_VERSION=1
+ BOOTSTRAP_ARCH_COMMON_VERSION=1
+ BOOTSTRAP_GENTOO_COMMON_VERSION=1
+ BOOTSTRAP_FREEBSD_VERSION=1
+ BOOTSTRAP_MAC_VERSION=1
+ BOOTSTRAP_SMARTOS_VERSION=1
+ BOOTSTRAP_MAGEIA_COMMON_VERSION=1
+ '[' -f /etc/debian_version ']'
+ '[' -f /etc/mageia-release ']'
+ '[' -f /etc/redhat-release ']'
+ prev_le_python=
+ unset LE_PYTHON
+ DeterminePythonVersion NOCRASH
+ '[' '' = 1 ']'
+ for LE_PYTHON in '"$LE_PYTHON"' python2.7 python27 python2 python
+ command -v ''
+ for LE_PYTHON in '"$LE_PYTHON"' python2.7 python27 python2 python
+ command -v python2.7
+ for LE_PYTHON in '"$LE_PYTHON"' python2.7 python27 python2 python
+ command -v python27
+ for LE_PYTHON in '"$LE_PYTHON"' python2.7 python27 python2 python
+ command -v python2
+ break
+ '[' 0 '!=' 0 ']'
++ python2 -V
++ sed 's/\.//'
++ cut -d. -f1,2
++ cut '-d ' -f 2
+ PYVER=26
+ '[' 26 -lt 27 ']'
+ '[' NOCRASH '!=' NOCRASH ']'
+ '[' 26 -eq 26 ']'
+ USE_PYTHON_3=1
+ BOOTSTRAP_VERSION='BootstrapRpmPython3 1'
+ LE_PYTHON=
+ '[' '' = 1 ']'
+ '[' '' = --le-auto-phase2 ']'
+ export PHASE_1_VERSION=0.32.0
+ PHASE_1_VERSION=0.32.0
+ '[' '!' -f /opt/eff.org/certbot/venv/bin/letsencrypt ']'
+ '[' '' = 1 ']'
+ '[' '' '!=' 1 ']'
++ TempDir
++ mktemp -d
+ TEMP_DIR=/tmp/tmp.1A5WoJOoLP
+ trap 'rm -rf "$TEMP_DIR"' EXIT
+ cat
+ DeterminePythonVersion NOCRASH
+ '[' 1 = 1 ']'
+ for LE_PYTHON in '"$LE_PYTHON"' python3
+ command -v ''
+ for LE_PYTHON in '"$LE_PYTHON"' python3
+ command -v python3
+ '[' 1 '!=' 0 ']'
+ '[' NOCRASH '!=' NOCRASH ']'
+ PYVER=0
+ return 0
+ '[' 0 -lt 27 ']'
+ error 'WARNING: couldn'\''t find Python 2.7+ to check for updates.'
+ echo 'WARNING: couldn'\''t find Python 2.7+ to check for updates.'
WARNING: couldn't find Python 2.7+ to check for updates.
++ CompareVersions python3 0.32.0 ''
++ python3 - 0.32.0 ''
./certbot-auto: line 878: python3: command not found
+ LE_VERSION_STATE=
+ rm -rf /tmp/tmp.1A5WoJOoLP
```

**Comment by adferrand** [comment]
Your system seems to be partially broken.

The executable `python3` is missing, while it should have been installed by certbot-auto when `python34` is installed through the EPEL repository. Just tested that on a fresh new instance of CentOS 6. For some reason it have been uninstalled afterwards on your system.

Try `yum install python34-devel python34-tools` to reinstall Python 3. If it does not work, I invite you to check with the Letsencrypt community, on https://community.letsencrypt.org/. Many people are using CentOS with Certbot, you are very likely to find there the support you need.

**Comment by jsoref** [comment]
Sorry. I've found at least two threads with this problem and no help.

I also have a couple of systems where this worked without issue.

Given certbot-auto is supposed to be able to install python 3.4 magically, that it's failing to get things the way it wants, that's its problem, not just "blame the user".

As such, this is a bug. It's one thing if only one user hits a problem, it's another if multiple systems and multiple users hit it.

It seems that there should be more logging/debugging at least.

**Comment by adferrand** [comment]
Well, it is not a question a blaming the user, but to consider if it is a bug.

The problem is that when certbot is installed, certbot-auto ensures from the bootstrap process that required packages have been installed (for CentOS 6, `python34-devel` and `python34-tools`). It was done on your system and certbot could work correctly. Later, Python 3 has been removed, for any reason that can be an explicit action to an implicit consequence of another action. Nobody to blame here, it happens for a lot of reason.

This would not happen with Certbot installed as an OS package, since the dependency graph would trigger that python 3 cannot be removed because Certbot relies on it. But, this is not available for CentOS 6, `certbot-auto` needs to be used. However, the `certbot-auto` script does not know about this dependency graph. To do so, it would need, at each execution, to check if the runtime is still healthy, then log or auto fix it. It is too complex for the numerous reasons that can provoke a system to become unhealthy, and so out of scope of this script.

We are working to create a new packaging approach that would take advantage of the OS packages system and the flexibility of certbot-auto to be installed in various systems.

Until that, `certbot-auto` will not take any significant new features.

Besides that, did my command fix your system?

**Comment by jsoref** [comment]
Yes, and it seems to me like it could be suggested-- even if you don't want to add the code to run it yourself.

**Comment by CanadianJeff** [comment]
```
[root@jeff:/tmp] # echo $PATH
/opt/centos/devtoolset-1.1/root/usr/bin/:/usr/local/jdk/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/usr/local/rvm/bin:/usr/local/bin:/usr/X11R6/bin:/root/bin
[root@jeff:/tmp] # ln -s /usr/local/bin/python3.6 /usr/local/bin/python3
ln: creating symbolic link `/usr/local/bin/python3': File exists
[root@jeff:/tmp] 1 # ls -l /usr/local/bin/python3
lrwxrwxrwx. 1 root root 24 Jun  5 15:57 /usr/local/bin/python3 -> /usr/local/bin/python3.6*
[root@jeff:/tmp] # sudo /usr/local/bin/certbot-auto --apache --verbose
WARNING: couldn't find Python 2.7+ to check for updates.
/usr/local/bin/certbot-auto: line 898: python3: command not found
[root@jeff:/tmp] 127 # python3
Python 3.6.8 (default, May 24 2019, 18:20:29)
[GCC 4.7.2 20121015 (Red Hat 4.7.2-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by CanadianJeff** [comment]
I clearly have python3 it is in my $PATH this is on CentOS 6.10 so........... fix your script?
