### ISSUE TITLE
Certbot and Nginx config

### ISSUE THREAD

**Issue by alex4554** [certbot/certbot#6840]
## I installed Certbot with (certbot-auto, OS package manager, pip, etc): OS package manager - https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx

During installation I was asked if I want to auto redirect http to https, I answered "Yes" and the following config was inserted into my domain's nginx config:
server {
    if ($host = www.example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    if ($host = example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    listen 80;
    listen [::]:80;
    server_name example.com www.example.com;
    return 404; # managed by Certbot
}

According to the official nginx website, using "if" directive for checking the host is extremely inefficient. 
Quote from https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#server-name-if : 
> "When NGINX receives a request no matter what is the subdomain being requested, be it www.example.com or just the plain example.com this if directive is **always** evaluated. Since you’re requesting NGINX to check for the Host header for **every request**. It’s extremely inefficient. You should avoid it. Instead use two server directives..."

So what I did is that I split the above server directive into two ones without any ifs:
server {
    listen 80;
    listen [::]:80;
    server_name example.com;
    return 301 https://example.com$request_uri;
}
server {
    listen 80;
    listen [::]:80;
    server_name www.example.com;
    return 301 https://www.example.com$request_uri;
}

Maybe you should also consider removing the "if" directive and use more than one server directives.

**Comment by schoen** [comment]
@ohemorange, I think we do it this way for a reason, but I'm not sure offhand what the reason is. Are you aware of some tradeoffs that potentially favor keeping the current structure?

**Comment by alex4554** [comment]
I am not sure, I am just referring to nginx developers config advice and if they are saying such config is inefficient, I just trust them and follow the instructions how to make it better, as for sure they know the insides of their system better.
There should be a reason they explicitly included this advice in their "Pitfalls and Common Mistakes" guide.

**Comment by ohemorange** [comment]
Yes, we do have a reason. We add ifs to protect against a specific vulnerability that came up in some cases. If that creates too much of a slowdown, feel free to use a custom config. Also, this isn't quite the situation described in the Nginx docs above -- it already selects the vhost based on the `server_name` directive, but then double-checks before redirecting.

**Comment by alex4554** [comment]
Yes, you're right, this isn't quite the situation described in the Nginx docs above, but main point here is to try to avoid the ifs, which are checking for the Host header for every request.
