### ISSUE TITLE
Instructions on certbot.eff.org doesn't give the latest certbot on Debian 9

### ISSUE THREAD

**Issue by maniac0s** [certbot/certbot#6843]
I followed the instructions to install certbot on certbot.eff.org for my system Debian 9 stretch as suggested in the installation instructions on readme.md file. I am using stretch-backport but that gives me 0.28 and not 0.33

With 0.28 I also get a parsing error

	root@test ~/certbot # apt-get install certbot python-certbot-apache -t stretch-backports
	(...)
	root@test ~/certbot # certbot --version
	certbot 0.28.0
	root@test ~/certbot # certbot renew --dry-run
	Saving debug log to /var/log/letsencrypt/letsencrypt.log

	- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	Processing /etc/letsencrypt/renewal/somedomain.conf
	- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	Cert is due for renewal, auto-renewing...
	Encountered a problem while parsing file: /files/etc/apache2/sites-enabled/*.somedomain.conf/VirtualHost[1], skipping
	Encountered a problem while parsing file: /files/etc/apache2/sites-enabled/*.somedomain.conf/VirtualHost[2], skipping
	Encountered a problem while parsing file: /files/etc/apache2/sites-enabled/*.somedomain.conf/VirtualHost[1], skipping
	Encountered a problem while parsing file: /files/etc/apache2/sites-enabled/*.somedomain.conf/VirtualHost[2], skipping

**Comment by schoen** [comment]
@maniac0s, thank you for letting us know about this.

Does the name of your Apache configuration file literally start with an asterisk character? Could you please show us the content of that file, as well as the content of the renewal configuration file from `/etc/letsencrypt/renewal`? (You can keep replacing your domain name with `somedomain`, but it would be helpful to see the file contents here.)

**Comment by maniac0s** [comment]
Yeah I don't know I took the server over from another guy but it shouldn't matter, right?	

    <VirtualHost *:80>
			ServerAdmin webmaster@somedomain.net
			ServerName somedomain.de
			
			DocumentRoot /var/web

			<Directory />
					Options +FollowSymLinks
					AllowOverride None
			</Directory>

			<Directory /var/web/>
					Options -Indexes +FollowSymLinks -MultiViews -SymLinksIfOwnerMatch

					Require all granted
					AllowOverride All

			</Directory>


			ErrorLog ${APACHE_LOG_DIR}/somedomain.error.log

			# Possible values include: debug, info, notice, warn, error, crit,
			# alert, emerg.
			LogLevel warn

			CustomLog ${APACHE_LOG_DIR}/somed.access.log combined

		Protocols h2c http/1.1
	</VirtualHost>

	<VirtualHost *:443>
			ServerAdmin webmaster@somedomain.net
			ServerName somedomain.de
			
			DocumentRoot /var/web

			<Directory />
					Options +FollowSymLinks
					AllowOverride None
			</Directory>

			<Directory /var/web/>
					Options -Indexes +FollowSymLinks -MultiViews -SymLinksIfOwnerMatch

					Require all granted
					AllowOverride All

			</Directory>

			ErrorLog ${APACHE_LOG_DIR}/somedomain.error.log

			# Possible values include: debug, info, notice, warn, error, crit,
			# alert, emerg.
			LogLevel warn

			CustomLog ${APACHE_LOG_DIR}/somedomain.access.log combined

		SSLEngine On
		SSLCertificateFile /etc/ssl/somedomain2017/*.somedomain.de.crt
			SSLCertificateKeyFile /etc/ssl/somedomain2017/*.somedomain.de.key
			SSLCertificateChainFile /etc/ssl/somedomain2017/*.somedomain.de.ca

		#Include /etc/letsencrypt/options-ssl-apache.conf
		Protocols h2 http/1.1

	</VirtualHost>

**Comment by pconrad-fb** [comment]
I'm still available to work on this stuff. Let me know how I can help!

**Comment by maniac0s** [comment]
The problem with the parsing still exists.
