### ISSUE TITLE
Renewal config should have global section headers

### ISSUE THREAD

**Issue by ageis** [certbot/certbot#6847]
## My operating system is (include version):
Debian GNU/Linux buster/sid, kernel 5.0

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot 0.32.0 via PyPi

## I ran this command and it produced this output:

Tried to use Configparser Python module (actually, a dependency of the ["INI" file lookup in Ansible](https://docs.ansible.com/ansible/latest/plugins/lookup/ini.html)) to open configs in `/etc/letsencrypt/renewal/*conf` and extract values from keys.

## Certbot's behavior differed from what I expected because:

This does not work due to:
Error: 'File contains no section headers.'
Even though I'm trying to read hooks from the `[renewalparams]` section.
The file usually begins with `version =` or a comment instead of a section header.

Can you make this conform to ordinary INI format by making a `[global]` section header at the top?

**Comment by adferrand** [comment]
In fact the configuration renewal files do not follow the INI format, but the `ConfigObj` one, that is a superset of the INI format. See https://configobj.readthedocs.io/en/latest/configobj.html#config-files

So I think that in general, you will have problems if you try to read theses files using the `ConfigParser` for INI files.

Changing the configuration format would create several retro-compatibility problem, so it is really not an easy path. 

As an alternative, you could use a patched version of the Ansible INI parser module, that uses `ConfigObj`, like this example: https://gist.github.com/ntrrgc/10007589

What do you think of that?

**Comment by adferrand** [comment]
@ageis, do you have some feedback on my alternative?

**Comment by ageis** [comment]
@adferrand Just saw this. Thanks for researching a workaround.. Trying it now.

**Comment by ageis** [comment]
@adferrand Okay, well the patched module you linked to is for modifications (add/change/remove) rather than lookups. However, I understand the general approach and have written my own Ansible plugins/callbacks/modules before, so given that it sounds like it'd be too much strain/churn to change the INI format on your end, then I will handle my issue with a custom patch. Thanks, and feel free to close this issue!

P.S. I applied to the open Let's Encrypt SRE position. looking forward to _maybe_ speaking/working with you! ([more about me]([https://cointel.pro/kevingallagher_resume.pdf]))

**Comment by adferrand** [comment]
That is great! Thanks for sharing the code here, sure it will be useful for others.

Then, looking forward to see you soon in the team maybe!
