### ISSUE TITLE
Remove TLS-SNI-01 tests and code

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6849]
Let's Encrypt is turning off TLS-SNI-01 tomorrow, this challenge is no longer part of the ACME spec, and we have deprecated our support for a while. I think it's time to delete a lot of code.

I think we should:

- [x] Remove all tests using TLS-SNI-01
- [x] Remove any special code configuring boulder to still offer TLS-SNI-01 during tests
- [x] Remove code in Certbot and its plugins for performing TLS-SNI-01
- [x] Remove unit tests in Certbot and its plugins for performing TLS-SNI-01

And that may be it for now.

I think we should be a little careful in `acme`. Do we really want code like:
```
if isinstance(foo, acme.challenges.TLSSNI01):
```
to suddenly blow up? Code like this has never printed deprecation warnings.

I'm happy to talk about the `acme` stuff, but I think we may want to talk about how to remove that separately.

**Comment by bmw** [comment]
Also, this should probably be done incrementally in separate PRs because the number of lines deleted here is going to be well over 1000.

**Comment by adferrand** [comment]
I will happily take this charge, if you want.

**Comment by bmw** [comment]
The first piece of this we should do is integration tests because boulder is planning on removing their TLS-SNI-01 code as well.

**Comment by bmw** [comment]
Also also, another thing I think we should be careful about is references to TLS-SNI in configuration files. In particular, I don't think we should suddenly blow up if `tls-sni` is included in the preferred challenges list.

**Comment by adferrand** [comment]
Considering your comments, here is the plan I am thinking.

PR1: Remove integration tests
PR2: Remove unit tests
PR3: Make tls-sni-01 execute a http-01 instead on Certbot, with a deprecation warning
PR4: Make any call of tls-sni from acme generate a deprecation warning 

Then, with one or two releases after 
PR5: Make any call of tls-sni a no-op with failure from certbot

Finally, one or two releases more:
PR6: Remove tls-sni-01 from acme. No code referring to tls-sni-01 on certbot and acme anymore.

**Comment by adferrand** [comment]
I separated PR5 and PR6 to let acme, as a library, behave with a smooth deprecation path, because in theory, other acme CA servers could still offer tls-sni-01.

But we can be faster about our droping support because it is a security issue, and make PR6 on the same time than PR5 if you want.

**Comment by bmw** [comment]
> PR1: Remove integration tests

I think we should do this relatively soon (probably before nailing down the rest of the details here) because if boulder beats us to it, our tests will fail.

> PR2: Remove unit tests

What unit tests are you planning on removing in PR2? There are TLS-SNI-01 tests for the standalone, Apache, and Nginx plugins.

When are you planning on removing the implementations of the TLS-SNI-1 challenges in these plugins?

> PR3: Make tls-sni-01 execute a http-01 instead on Certbot, with a deprecation warning

I should have been more clear in my comments. I don't think we should do any automatic translation of TLS-SNI-01 to HTTP-01. What I meant by my most recent comments about `--preferred-challenges` is I don't personally think that if someone had the equivalent of:
```
--preferred-challenges http,tls-sni
```
in a configuration file, if we should suddenly start failing in our next release with:
```
certbot: error: argument --preferred-challenges: Unrecognized challenges: tls-sni
```
I think we should still successfully parse `tls-sni`, but none of our plugins would ever do it because it's not supported anymore. I think we get this behavior automatically if we don't remove the TLS-SNI-01 challenge type in our `acme` code.

Alternatively/in addition, we could warn about the inclusion of TLS-SNI-01 in the list and start erroring on it in the future and/or just drop it from the list which would clean up renewal configuration files going forward.

> PR4: Make any call of tls-sni-01 from acme generate a deprecation warning

I'm curious what you had in mind here. Depending on what you were thinking, we already do this at:
https://github.com/certbot/certbot/blob/cf29e89366c7eb57dd48a99a06fe05ceaa9057fa/acme/acme/challenges.py#L518

This doesn't cause any deprecation warnings for the use I described in my initial post though. I'm actually not immediately sure the best way for us to go about gradually ripping out code like this.

**Comment by bmw** [comment]
I should add that Max and I talked about the problem of people who had set `--preferred-challenges tls-sni-01` where tls-sni-01 is the only supported challenge and we decided not to add any magic to help them. See https://github.com/certbot/certbot/issues/6742.

**Comment by adferrand** [comment]
OK we are agree about PR1 and PR2. Yes for PR2 I am thinking of all the unit test you mentionned. 

About PR3, I was not clear at all about what I had in my mind, and forgot a part of the context (including my own participation to it). It was about behavior around preferred challenges.

So the deprecation warning is about having tls-sni in your preferred challenge config, either from cli or from the renewal configuration.

It is also the good occasion, I think we all agreed and you mention it with #6742, to give to preferred challenge its "real" purpose: try the preferred challenges first, then the other if the preferred ones failed.

So:

PR3: Change preferred challenges meaning to a real preference, not a constraint, and print warning if tls-sni-01 is part of them in a config.

**Comment by adferrand** [comment]
However, as I said before, I strongly militate to add an option in certbot that limit the challenges that can be used by Certbot.

This can wait until tls-alpn-01 is here, because in practice no installer can do two different challenges, except the manual, but for which the action is explicitly coded or done by the user.

**Comment by adferrand** [comment]
PR4 may be not necessary, I need to check the code. It is just about been sure that any call to this part of acme code generate the proper warning. At this point, knowing which version of certbot will remove it, we could make the deprecation warning more precise by giving this deadline.

**Comment by adferrand** [comment]
In this context, removing the tls-sni-01 implementation are done in PR5.

**Comment by adferrand** [comment]
Finally for PR6, the idea is do remove as the last step for the real library in certbot project, acme, as it is for libraries that the migration path should be longest one.

**Comment by bmw** [comment]
> PR3: Change preferred challenges meaning to a real preference, not a constraint, and print warning if tls-sni-01 is part of them in a config.

I strongly disagree about looping in #6742 with the changes here. I think they are separate issues. The issue I'm personally concerned about here is a minor detail of parsing `--preferred-challenges` which is in `cli.py` while the changes in #6742 has to do with how these parsed values are used in `auth_handler.py`. Again, as long as the `acme` code isn't modified, the simplest form of the behavior I personally want here should happen automatically.

I think any discussion about #6742 should happen there and be in its own PR. If you want to discuss this issue, feel free to post there, however, I think the value of making changes there is pretty limited while the only plugin that supports multiple challenges that are supported by Let's Encrypt is the manual plugin which I think you reasonably argued probably shouldn't fallback to other challenge types.

> PR4 may be not necessary, I need to check the code. It is just about been sure that any call to this part of acme code generate the proper warning.

Yes. I think you should look into this issue more before proposing a path forward for any `acme` changes. As I suggested in my initial post, we may want to hold off on making any changes there for the reasons I have described above.

> In this context, removing the tls-sni-01 implementation for certbot plugins are done in PR5.

By the time these changes go out, we will have been printing deprecation warnings about TLS-SNI-01 for 5 months. I personally think that's long enough and we can remove support for TLS-SNI-01 in our plugins. I'd like to propose removing unit tests and the implementation in each plugin at once and perhaps break up the PRs by plugin. Let's not leave untested code in our code base.

It seems unnecessary to me for us to go down this road, but if we want to continue supporting TLS-SNI-01 for longer period of time, I think we may want to revisit the idea of removing all of our tests that TLS-SNI-01 in Certbot is working correctly.

**Comment by adferrand** [comment]
So.

PR1: Remove integration tests (soon because we will drop support of Boulder on it)
PR2: Deprecation warning of having tls-sni-01 challenge from CLI for preferred challenges

X months later

PR(s) one each removing tls-sni-01 from a plugin (code + tests) 

Y months later

PR: Removing tls-sni from acme

With X = 3 or 4, Y = 1

Also on PR2, I think we should check for remaining tls-sni-01 values in renewal configs.

**Comment by bmw** [comment]
Why should we wait X months to remove support for TLS-SNI-01 from our plugins? Certbot has been printing deprecation warnings every time it performs a TLS-SNI-01 challenge since November. See https://github.com/certbot/certbot/blob/cf29e89366c7eb57dd48a99a06fe05ceaa9057fa/certbot/auth_handler.py#L186

**Comment by bmw** [comment]
It seems I haven't explained my minor concern about `--preferred-challenges` very well.

The general concern which you also expressed above is being careful around references to TLS-SNI-01 in people's Certbot's configurations. This includes command line options, their global configuration file, and their renewal configuration file. While Certbot has been printing warnings every time its TLS-SNI-01 support is used for a long time, suddenly changing the behavior of configuration options could cause unexpected problems for people.

I singled in on `--preferred-challenges`, however, I think this will also affect flags like `--standalone-supported-challenges`, `--tls-sni-01-address`, and `--tls-sni-01-port`. There may be more flags as well.

To describe the concern I have about `--preferred-challenges`, imagine the user is using the standalone plugin and for whatever reason has set `--preferred-challenges http,tls-sni`. Assuming the user is using Let's Encrypt, Certbot will have happily understood the meaning of `tls-sni`, however, the challenge type was never used and HTTP-01 was used instead. Because TLS-SNI-01 was never used, Certbot never printed a deprecation warning.

If we just blindly deleted all TLS-SNI-01 code from Certbot, this user would suddenly start getting:
```
certbot: error: argument --preferred-challenges: Unrecognized challenges: tls-sni
```
This sucks. The user was given no warning by Certbot and it just suddenly blew up when it upgraded. Because of this, I do not think we should start erroring in this case when these changes land.

I proposed a few ways we could deal with this which were:

1. Just continue to happily accept the challenge in the list forever.
2. We could warn about the inclusion of TLS-SNI-01 in the list and start erroring on it in the future.
3. Just silently drop the value from the list during parsing.

I'm happy to talk more about these 3 options, but I honestly don't have too strong of a preference between them.

**Comment by adferrand** [comment]
OK I understand know what was wrong in the conversation: we were not on the same page. Probably influenced by our previous discussion around test modules in `certbot.plugins`, and the advertised sunset if ACMEv1, I interpretated in the wrong direction your concern about tls-sni related cli options that you explained completely here.

I went to the idea that you wanted a new sunset of tls-sni-01 capabilities in certbot over several months. In fact it was about having several short PRs to remove it now, plus something to not fail immediately certbot if someone has still some tls-sni related flags registered in several cron jobs for instance.

So now it is clear. About the strategy for cli, I am in favor of 2, as do not see the benefit to keep that kind of code forever.

**Comment by bmw** [comment]
> So now it is clear. About the strategy for cli, I am in favor of 2, as I do not see the benefit to keep that kind of code forever.

I think that's fine.

For the `--tls-sni-*` options, I recommend looking at [add_deprecated_argument](https://github.com/certbot/certbot/blob/cf29e89366c7eb57dd48a99a06fe05ceaa9057fa/certbot/cli.py#L807) if you haven't seen it already

**Comment by adferrand** [comment]
Ok @bmw. The storm of PR-nado is over. Full removal path of TLS-SNI is here, and available for review.

**Comment by bmw** [comment]
This was done in 0.33.0.
