### ISSUE TITLE
Fix remaining broken tests on Windows

### ISSUE THREAD

**Issue by adferrand** [certbot/certbot#6850]
When I started to port Certbot on Windows, a lot of unit tests or the logic tested by them were not working on this platform.

In order to still have a working CI during the port, all failing tests where marked with a temporary decorator, `@broken_on_windows` to skip their execution. At this time, there is 40 units tests left in this state.

This issue is done to track the complete removal of broken tests on Windows, either by fix the test or code logic, or by skipping definitively some of theses tests for a good reason with `@skip_on_windows`.

**Comment by adferrand** [comment]
Once mentioned PRs above are merged, plus logic from #6497 and #6859, all unit tests will be compatible with Windows, or skipped for a good reason.

**Comment by bmw** [comment]
The last pieces of this are (at least partially) blocked on landing #6895.
