### ISSUE TITLE
Update the official dockerfile to use Python3

### ISSUE THREAD

**Issue by larssb** [certbot/certbot#6851]
# INFO

## My operating system is (include version):
* Docker v18.09.2

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
* Nope, using this: https://hub.docker.com/r/certbot/certbot/dockerfile

## Other info
* Certbot version: provided by the docker image

# WISH

I would like the official Certbot image/dockerfile to be updated so that it uses `python:3-alpine3.9` (or a newer version of Alpine, if available) .. the important part is the Python version. Right now the Certbot docker image uses python v2.
I can confirm that certbot should officially be supporting Python3, e.g. #3179 and #4507 ... so is there a good reason for not using Python v3+ in the image?

Thank you so much 💯

**Comment by larssb** [comment]
Hi @adferrand,

Thank you for responding. 

You certainly state good reasons for this project using v2.7 of Python. The thing is that I've coded some automation scripts for handling LetsEncrypt certificates (renewal, expanding and such).
These scripts use code that take advantage of features only available in Python v3. E.g. the `run()` of the `subprocess` module in the std. Python library.

Maybe there could be two Docker images. One with a tag of `py3-0.31.0` and the other `py2-0.31.0`. That is my cup of tea :-)

Have a great day.

**Comment by purificant** [comment]
I would like to see an official Python 3 docker image for certbot.

I am using `FROM certbot/certbot` in my container and applying further customisation such as adding plugins. I often see this warning in logs:

> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.

**Comment by J0WI** [comment]
There is already a pending PR: #6759

**Comment by bmw** [comment]
This was done in https://github.com/certbot-docker/certbot-docker/pull/5.
