### ISSUE TITLE
certbot verification URL missing domain

### ISSUE THREAD

**Issue by seanthegeek** [certbot/certbot#6862]
## My operating system is (include version):

Ubuntu 18.10 (GNU/Linux 4.18.0-16-generic x86_64)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

certbot 0.31.0 via the certbot/certbot PPA

## I ran this command and it produced this output:

```
sudo certbot --nginx certonly -d sandbox.example.net
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator nginx, Installer nginx
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for sandbox.example.net
Using default address 80 for authentication.
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. sandbox.example.net (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching https:///.well-known/acme-challenge/44zO-fsY4mlc0QpyTtFevdWRR5KuvrXKKd5Wn5XfZz0: unknownHost :: No valid IP addresses found for

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: sandbox.example.net
   Type:   connection
   Detail: Fetching
   https:///.well-known/acme-challenge/44zO-fsY4mlc0QpyTtFevdWRR5KuvrXKKd5Wn5XfZz0:
   unknownHost :: No valid IP addresses found for

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
```

**Comment by cpu** [comment]
:wave: @seanthegeek This looked pretty curious so I took a quick look. I was able to take the challenge token from the error message you shared and work backwards to your actual domain (not the `sandbox.example.net` replacement) in the server-side validation logs.

It looks like your server is misconfigured and sending a bad redirect to requests for `http://sandbox.example.net/.well-known/acme-challenge/<token>`:

```
HTTP/1.1 301 Moved Permanently
Server: nginx/1.15.5 (Ubuntu)
Date: Thu, 14 Mar 2019 19:52:39 GMT
Content-Type: text/html
Content-Length: 178
Connection: keep-alive
Location: https:///.well-known/acme-challenge/44zO-fsY4mlc0QpyTtFevdWRR5KuvrXKKd5Wn5XfZz0
```

I think the Let's Encrypt server-side CA software could be improved to make this error clearer but I don't think its a Certbot bug in this case (unless Certbot created that redirect somehow).

**Comment by bmw** [comment]
Certbot shouldn't have created a redirect so I agree with cpu that your server seems misconfigured and fixing this redirect should solve the problem.

With that said, Certbot plays games with nginx directive precedence and I wouldn't expect to see this error. Can you please provide the sections from our issue template which you omitted which are:

## Here is a Certbot log showing the issue (if available):
###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

**Comment by seanthegeek** [comment]
I figured out what the problem was. I forgot I had a preexisting server block redirect from http to https, where I have a self-signed cert set up. I removed that and everything worked. D'oh! D'oh! D'oh!

**Comment by cpu** [comment]
@seanthegeek Thanks for opening an issue!
