### ISSUE TITLE
suggested improvement for certbot webpage in crontab entry for certbot automating renewal

### ISSUE THREAD

**Issue by carlalbing** [certbot/certbot#6863]
The main certbot web page of instructions (for various OS/server combinations) includes a section titled 
Automating renewal
In that section (for all the various Linux/BSD/macOS systems) it suggests a crontab entry that includes the command:
    python -c 'import random; import time; time.sleep(random.random() * 3600)'
I would suggest a lighter-weight shell-based mechanism to get the desired time offset, simply:
    sleep $(( RANDOM/10 )) 
prior to the remainder of that line, the: && /path/to/certbot-auto renew 
It's clearer about what's being done, simply a sleep, and it avoids the need to load python and import two packages.  The shell variable RANDOM returns an integer from 0 to 32767.  (The $ isn't needed inside of $(( )) though it would be fine to include it.  The resulting integer divide will give a random sleep from 0 to 54 minutes - close enough for these purposes.
The complete crontab line would therefore read:
    0 0,12 * * * sleep $$( RANDOM/10 )) && certbot renew 

Thanks for considering this change/improvement.

**Comment by joohoi** [comment]
Thanks for the suggestion. Unfortunately this doesn't work for all shells, but is a feature of bash and zsh. Because of this, we won't be able to change the default instruction. I'll close the issue for now to avoid clutter. If you feel that it should be reopened, let me know and I'll do so.
