### ISSUE TITLE
Amazon Linux2 support (add these lines)

### ISSUE THREAD

**Issue by bundgaard** [certbot/certbot#6864]
Was using Amazon Linux2 and needed to grab a certificate from LetsEncrypt.

You would want to add these lines
```
elif [ -f /etc/system-release ] && grep -iq "Amazon Linux" /etc/system-release ; then
  Bootstrap() {
    ExperimentalBootstrap "Amazon Linux" BootstrapRpmCommon
  }
  BOOTSTRAP_VERSION="BootstrapRpmCommon $BOOTSTRAP_RPM_COMMON_VERSION"
```

**Comment by joohoi** [comment]
Thanks for opening the issue, would you like to submit pull request to fix this, as it looks like you did the work already?

**Comment by schoen** [comment]
I guess you could also use `grep -sqi "Amazon Linux" /etc/system-release` and omit the test for the existence of the file (although that might be harder to read).

**Comment by schoen** [comment]
@bundgaard, would you be willing to open a PR here on GitHub as suggested by @joohoi?

**Comment by bundgaard** [comment]
Hi, sorry didnt see any updates on this matter, didn't think it was taken seriously...
I will look into making an PR if its still needed...

**Comment by bundgaard** [comment]
Already in the certbot...

will close this instead. 

Sorry for not seeing this in time!

**Comment by dmitriyshashkin** [comment]
@bundgaard the version that went into certbot differs from the one you suggested and doesn't seem to work. It checks /etc/issue instead of /etc/system-release and on a new installation of the amazon linux I don't have "Amazon Linux" phrase in the /etc/issue file. Meanwhile, the version you suggested works just fine
