### ISSUE TITLE
Generating wildcard certificates *.domain.com and domain.com at the same time always fails.

### ISSUE THREAD

**Issue by kssion** [certbot/certbot#6871]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
macOS 10.14.3

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager “brew”

## I ran this command and it produced this output:
```
### Input:
sudo certbot certonly --server https://acme-v02.api.letsencrypt.org/directory -d domain.cc -d *.domain.cc --manual --preferred-challenges dns-01 --dry-run  --manual-auth-hook /Users/domain/Developer/letsencrypt/certbot-auto/au.sh

### Output:
Waiting for verification...
Challenge failed for domain domain.cc
dns-01 challenge for domain.cc
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: domain.cc
   Type:   unauthorized
   Detail: Incorrect TXT record
   "1wQ37NX8GjQQKt5BwsA6Yii6-rob1bMe_hgzoFOFNq8" found at
   _acme-challenge.domain.cc

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
```

## Certbot's behavior differed from what I expected because:
我想要的是一张证书包含 *.domain.com and domain.com

## Here is a Certbot log showing the issue (if available):
结果是错误的，应该成功，但其实是失败

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
```
### au.sh is a script that automatically updates DNS TXT records
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for domain.cc
dns-01 challenge for domain.cc

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
NOTE: The IP of this machine will be publicly logged as having requested this
certificate. If you're running certbot in manual mode on a machine that is not
your server, please ensure you're okay with that.

Are you OK with your IP being logged?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(Y)es/(N)o: Y
Running manual-auth-hook command: /Users/domain/Developer/letsencrypt/certbot-auto/au.sh
Output from manual-auth-hook command au.sh:
/Users/domain/Developer/letsencrypt/certbot-auto/alydns.php
domain.cc  _acme-challenge  iCto9008ctydRLzUHOXMnY_DgNUMW2qKleErCU3yOmQ
END

Running manual-auth-hook command: /Users/domain/Developer/letsencrypt/certbot-auto/au.sh
Output from manual-auth-hook command au.sh:
/Users/domain/Developer/letsencrypt/certbot-auto/alydns.php
domain.cc  _acme-challenge  1wQ37NX8GjQQKt5BwsA6Yii6-rob1bMe_hgzoFOFNq8
END

Waiting for verification...
Challenge failed for domain domain.cc
dns-01 challenge for domain.cc
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: domain.cc
   Type:   unauthorized
   Detail: Incorrect TXT record
   "1wQ37NX8GjQQKt5BwsA6Yii6-rob1bMe_hgzoFOFNq8" found at
   _acme-challenge.domain.cc

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
未使用自动配置证书

**Comment by schoen** [comment]
Hi @kssion,

This looks like a problem with `/Users/domain/Developer/letsencrypt/certbot-auto/alydns.php`. Specifically, it looks like this script can't handle the situation where it needs to create two different TXT records with the same name (which is what's required in this situation). Did you write this script yourself or did you get it from someone else?

Since this script isn't maintained or distributed by the Certbot team, I don't think this is a bug in Certbot. Please discuss this on the Let's Encrypt Community Forum at https://community.letsencrypt.org/. There's also at least one person there who can help discuss your problem in Chinese if you would prefer.

Thanks!

**Comment by kssion** [comment]
明白了！原来同一个域名的多个子域名是需要创建多个同名的不同TXT记录，是的，那个脚本无法完成这个操作。感谢，让我找到了原因。

**Comment by schoen** [comment]
Good luck, and please ask on the forum if you need help (as I mentioned, there is one person there who can help in Chinese).
