### ISSUE TITLE
Docker version not working for Raspberry Pi 3

### ISSUE THREAD

**Issue by petr-ujezdsky** [certbot/certbot#6878]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Raspberry Pi 3
```
$ uname -a
Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
```
## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
```
$ docker pull certbot/certbot
```

## I ran this command and it produced this output:
```
$ docker run -it --rm certbot/certbot:latest certbot-auto --help all
standard_init_linux.go:190: exec user process caused "exec format error"
```

```
$ docker run -it --rm certbot/certbot:v0.30.2 certbot-auto --help all
standard_init_linux.go:190: exec user process caused "exec format error"
```

## Certbot's behavior differed from what I expected because:
If I run it on my Macbook, it works fine:
```
$ docker run -it --rm certbot/certbot certbot-auto --help all
usage:
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
...
```

**Comment by Legion2** [comment]
you can build the image locally using `docker build -t certbot https://github.com/certbot/certbot.git` and then use the local image `certbot`.

**Comment by petr-ujezdsky** [comment]
**I have built the image myself and everything works now**. Thanks for the advice.

Btw I did not know I can build image directly from github without checking out the repo 👍
