### ISSUE TITLE
Unregister command not listed in help

### ISSUE THREAD

**Issue by martijnjanssen** [certbot/certbot#6879]
## I ran this command and it produced this output:
The command `certbot --help` only lists the `register` and `update_account`
commands.

```
manage your account with Let's Encrypt:
    register        Create a Let's Encrypt ACME account
    update_account  Update a Let's Encrypt ACME account
  --agree-tos       Agree to the ACME server's Subscriber Agreement
   -m EMAIL         Email address for important account notifications
```

## Certbot's behavior differed from what I expected because:
The help command should list the `unregister` under manage account.

Additionally it is not completely clear from the `--help` output that a more complete help is available with `--help all`, which does list the `unregister`.

**Comment by schoen** [comment]
@bmw, do you think this omission in the help output was intentional or deliberate?

**Comment by bmw** [comment]
No I think this was a simple oversight. Thanks for noticing this @martijnjanssen.

Fixing this is as simple as adding a line to the string at https://github.com/certbot/certbot/blob/50607eb0ff4279f3395231f3c6f35586d21557f3/certbot/cli.py#L78.

**Comment by aditj** [comment]
I am taking this up if thats not a problem :) 
(I see no open pull regarding this)
(Also this is my first issue on certbot)

**Comment by martijnjanssen** [comment]
Sure, go ahead!
