### ISSUE TITLE
Finish Apache test coverage

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6880]
While #6873 resolved #6813, test coverage is still not at 100% for the plugin. I think what happened is the TLS-SNI tests which have now been removed were also testing functions in other files so now we're missing a couple more lines of test coverage.

I think we should get test coverage on these lines and bump Apache required coverage back to 100%.

**Comment by adferrand** [comment]
Coverage on certbot-apache is 100% in the latest cron build: https://travis-ci.org/certbot/certbot/jobs/479250098

To which coverage are you refering to ?

**Comment by bmw** [comment]
This has been resolved.
