### ISSUE TITLE
Linode API Keys

### ISSUE THREAD

**Issue by jonahbron** [certbot/certbot#6896]
I ran into an issue want wanted to document my solution here in case anyone else runs into it.  I used the latest cloud.linode.com dashboard to generate an API key to use with the dns-linode plugin. However, it seems that the keys generated there are not connected to the legacy manager.linode.com dashboard.  You must log-in to the older interface in order to generate the correct type of token.  Here's the error I got when running with the wrong type of token:

```
Unexpected error determining zone identifier for jonah.name: Linode api error: [{u'ERRORCODE': 4, u'ERRORMESSAGE': u'Authentication failed'}]
```

**Comment by F21** [comment]
Also encountered this myself. I think #6588 should will fix this once merged.
