### ISSUE TITLE
Has certbot-dns-rfc2136 changed and nobody's updated the docs ?

### ISSUE THREAD

**Issue by udf2457** [certbot/certbot#6897]
I was happily using Certbot + certbot-dns-rfc2136 on openSUSE LEAP 15.

Until today when I updated it:
```
rpm -qa --last | fgrep certbot
python3-certbot-0.30.2-lp150.2.1.noarch       Sat 30 Mar 2019 10:12:42 GMT
python2-certbot-dns-rfc2136-0.30.2-lp150.2.1.noarch Sat 30 Mar 2019 10:12:38 GMT
python2-certbot-0.30.2-lp150.2.1.noarch       Sat 30 Mar 2019 10:12:34 GMT
```

Now when I run:
 `certbot certonly --deploy-hook /etc/foobar/certbot/certbot_deploy_hook.sh --server https://acme-v02.api.letsencrypt.org/directory --dns-rfc2136 --no-eff-email --dns-rfc2136-credentials /etc/foobar/certbot/certbot.ini -d '*.example.com'`  

I get the following error:

`certbot: error: unrecognized arguments: --dns-rfc2136-credentials /etc/foobar/certbot/certbot.ini`

The docs (https://certbot-dns-rfc2136.readthedocs.io/en/stable/) still seem to suggest `--dns-rfc2136-credentials` is still a perfectly acceptable flag ?

**Comment by schoen** [comment]
Hi @udf2457,

There haven't been any changes to our upstream version of this plugin since last April (almost a year ago).

@bmw, do you know what could cause this problem? I think it's a Python version skew problem, because probably Certbot is now running with py3 by default and unable to find the py2 plugin module?

**Comment by udf2457** [comment]
@schoen @bmw 

I think @schoen is onto something. I changed my script to call `/usr/bin/certbot-2.7` instead and the error no longer occurs.   So I suspect `dns-rfc2136` needs to be brought into the 21st century (a.k.a. made py3 friendly).

**Comment by bmw** [comment]
Installing the `python3-certbot-dns-rfc2136` package with `zypper` should solve your problem.

**Comment by isiko** [comment]
Hey, any Updates here? I'm currently getting the same Error

**Comment by udf2457** [comment]
@isiko Sorry, can't help, I gave up on certbot a long time ago. I thoroughly recommend using LEGO instead.  Written in Go, no silly Python dependencies, just a single binary deployment.  Works beautifully. https://go-acme.github.io/lego/

**Comment by isiko** [comment]
For anybody reading this, I think I just found the solution: You have to add quotation marks around the path

`--dns-rfc2136-credentials /root/credentials.ini` -> `--dns-rfc2136-credentials "/root/credentials.ini"`

**Comment by ckahlo** [comment]
In my case it was
`pip install certbot-dns-rfc2136`

The module has to be installed separately.
