### ISSUE TITLE
Are the uses of os.linesep in certbot/reverter.py incorrect?

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6899]
I think they are and Python 3 will automatically convert `\n` to the correct line ending on the platform, but we should verify this is also true in the ways `os.linesep` is being used here and then make the change or close this issue.

If someone wants to take this on, please include an explanation for why the uses of `os.linesep` are or are not correct.

**Comment by commit-dkp** [comment]
@bmw https://docs.python.org/3/library/os.html#os.linesep says "Do not use os.linesep as a line terminator when writing files opened in text mode", but both
https://github.com/certbot/certbot/blob/master/certbot/reverter.py#L187 and https://github.com/certbot/certbot/blob/master/certbot/display/util.py#L115 are writing to stdout in text mode according to https://github.com/certbot/certbot/blob/master/certbot/main.py#L1330 .

**Comment by bmw** [comment]
Thanks for looking into this @commit-dkp. The [docs for Python 2.7](https://docs.python.org/2.7/library/os.html#os.linesep) say the same thing so I think these uses of `os.linesep` are wrong and should be changed to `\n`. If you make a PR to make this change, we'll merge it.

What about the uses of `os.linesep` with the `logging` module in `reverter.py` though? I suspect the advice is the same because in the end the logging module will route this output to a file in text mode but it's probably not a bad idea to look into this a bit.

**Comment by commit-dkp** [comment]
@bmw The default advice is indeed the same for the `logging` module, since https://github.com/python/cpython/blob/3.7/Lib/logging/__init__.py#L1835 explains the default is a stream handler that writes to stderr, and `reverter.py` is using the default logger.

**Comment by bmw** [comment]
I don't think Certbot is using the `basicConfig`. We actually have a somewhat complex logging setup and all the code for it is in https://github.com/certbot/certbot/blob/master/certbot/log.py.

With that said, I suspect the advice is still true for the handlers we do configure.

**Comment by commit-dkp** [comment]
@bmw Thanks for clarifying.  Yes, none of the handlers in https://github.com/certbot/certbot/blob/master/certbot/log.py are configured to use binary mode.
