### ISSUE TITLE
Disable TLS session tickets in Apache?

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6901]
Inspired by https://jhalderm.com/pub/papers/forward-secrecy-imc16.pdf, we might want to look into changing our Apache plugin's behavior around TLS session tickets. The [Mozilla site](https://mozilla.github.io/server-side-tls/ssl-config-generator/) where we get our TLS config from has TLS session tickets disabled, but this setting is not present in our config files:

* https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/centos-options-ssl-apache.conf
* https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/options-ssl-apache.conf

This is likely due to the minimum version Apache that supports these settings, however, I don't believe this has been investigated for a while. We should see what version these settings were added and what versions are available in major distros.

Even if support is not available everywhere yet, it may be worth adding these values conditionally as I suspect it will work on the vast majority of systems.

**Comment by joohoi** [comment]
The support seems to be there from Apache 2.4.11 onward. They also have a [notification in their documentation](https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslsessionticketkeyfile) about the option compromising PFS, unfortunately the option is on by default and hence I doubt many people will see the notification :(

**Comment by bmw** [comment]
> In addition:
I'll try to contact Apache ppl to add information about this to their document: [SSL/TLS Strong Encryption: How-To](https://httpd.apache.org/docs/2.4/ssl/ssl_howto.html)

I think that would be very useful!

It looks like it was added to the 2.2.x branch in 2.2.30 according to their [docs](https://httpd.apache.org/docs/2.2/mod/mod_ssl.html#sslsessiontickets), however, this setting isn't in Mozilla's config generator for 2.2.30+. Apache 2.2 has reached it's EOL, but it still might be worth filing a bug about while they continue to generate configurations for Apache 2.2 on their site.

I suppose my other major question for me for this issue is what are the versions of Apache in major LTS distros right now. I'm thinking of CentOS 6 and 7, Debian 8, and Ubuntu 16.04. (Ubuntu 14.04 is EOL'd this month.)

If the version in some distro is too old, it might also be worth us double checking the distro didn't backport support for this feature.

**Comment by bmw** [comment]
Apparently you can buy extended support for Ubuntu 14.04 until 2022 so I think it's worth checking what the situation is there too.

**Comment by bmw** [comment]
It still would be useful to figure out what are the oldest versions of Apache that are still being used in popular OSes, but we're currently claiming to work on [any Apache 2.2+ system](https://github.com/certbot/certbot/blob/e9bcaaa576eb3bb29a71252f64c6cbde03d230d5/certbot-apache/certbot_apache/configurator.py#L253) and I don't think we should change that as a solution to this issue.

The way we were thinking this would work is very similar to https://github.com/certbot/certbot/pull/7092. We create a new TLS config file like those in my original post which contain all the same settings but have TLS session tickets disabled. The new versions of the file should be used on versions of Apache that support this directive and the old version should be used on versions that do not.

For Apache, we probably will need to add 2 new files. One generic one and one for CentOS. While this config file explosion is a little ugly, we thought it was better than trying to dynamically modify the file. The reason for this is the hash of the file is important and if the user has manually modified their installed copy of the file, [we print an error message with a link to our copy](https://github.com/certbot/certbot/blob/e9bcaaa576eb3bb29a71252f64c6cbde03d230d5/certbot/plugins/common.py#L460). We felt dynamically modifying the file complicated these two things too much to be worth it.

@joohoi, if I'm missing anything, please let me know.

@adferrand, if you have any questions, don't hesitate to ask and thanks for working on this!

**Comment by bmw** [comment]
Closing in favor of https://github.com/certbot/certbot/issues/7350.
