### ISSUE TITLE
Should we give SSL sessions in Nginx a 1 day timeout?

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6903]
Inspired by https://jhalderm.com/pub/papers/forward-secrecy-imc16.pdf, we might want to look into changing our nginx plugin's behavior around TLS sessions. The [Mozilla site](https://mozilla.github.io/server-side-tls/ssl-config-generator/) where we get our TLS config from has the TLS session timeout a 1 day which is much longer than nginx's default of 5 minutes.

This behavior is not necessarily wrong, but it's making a tradeoff for performance over security and more in the favor of performance than is recommended in the paper linked above.

The purpose of this issue is to track looking into this. Why does Mozilla have this recommendation? Do we agree? If so, we can close this issue, but if not, we should update our configuration file at https://github.com/certbot/certbot/blob/master/certbot-nginx/certbot_nginx/options-ssl-nginx.conf.

**Comment by sydneyli** [comment]
It was recommended to [improve performance](https://github.com/mozilla/server-side-tls/pull/24) afaict. There still seems to be some disagreement about it as per mozilla/server-side-tls#198.

For this and other reasons outlined in [the paper you linked](https://jhalderm.com/pub/papers/forward-secrecy-imc16.pdf) and [others](https://svs.informatik.uni-hamburg.de/publications/2018/2018-12-06-Sy-ACSAC-Tracking_Users_across_the_Web_via_TLS_Session_Resumption.pdf) I don't feel comfortable following this particular guideline. I'll also comment upstream!
