### ISSUE TITLE
Find new Debian Jessie AMI

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6907]
Debian removed `jessie-updates` from its mirrors which is causing tests on the AMI at https://github.com/certbot/certbot/blob/3830c0f9005ba8c301a6e0bedc129a3a4be723a6/tests/letstest/targets.yaml#L36 to fail.

We could update our test scripts to fix up the apt config, but I think ideally we should just find a new Debian 8 AMI that has this problem resolved out of the box.

However we fix this, we should make sure the changes cause all tests we run as the part of the release process to pass on Debian 8 before merging.

**Comment by bmw** [comment]
This has not been fixed in the official Debian 8 AMI which is still available but no longer receiving updates from the Debian team. I spent a couple minutes looking for a third party Debian AMI, but didn't find anything that looked particularly reliable.

To fix this, I'm thinking that we should just create a new AMI ourselves based on the official Debian 8 AMI with the problem resolved.

**Comment by ohemorange** [comment]
Additional resources used:
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/creating-an-ami-ebs.html
- https://aws.amazon.com/premiumsupport/knowledge-center/launch-instance-custom-ami/
- https://www.lucas-nussbaum.net/blog/?p=947

Todo:
- [ ] terminate instance used to create copy
- [ ] give new ami appropriate permissions
- [ ] run letstest tests with new image
