### ISSUE TITLE
Raspberry Pi: certbot-auto hash error 

### ISSUE THREAD

**Issue by maroph** [certbot/certbot#6918]
## My operating system is (include version):
lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.8 (stretch)
Release:        9.8
Codename:       stretch

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt install certbot python-certbot-apache
git clone https://github.com/certbot/certbot.git

python --version
Python 2.7.13
python3 --version
Python 3.5.3

## I ran this command and it produced this output:
./certbot-auto renew --apache --dry-run -d <mydomain> --redirect --email <mymail> --agree-tos --renew-by-default

Output:  
...  
  Downloading https://files.pythonhosted.org/packages/85/40/41af45945649321b4d9dabe91abad617e59b12ec617930ecfcac1e1d6e2c/certbot_apache-0.33.0-py2.py3-none-any.whl (249kB)
Collecting certbot-nginx==0.33.0 (from -r /tmp/tmp.4QILeGQBKW/letsencrypt-auto-requirements.txt (line 213))
  Downloading https://files.pythonhosted.org/packages/f2/0c/2816571232606b7a3364b2738b01c94898861e6c3ba37e63b04a0468a524/certbot_nginx-0.33.0-py2.py3-none-any.whl (86kB)
Requirement already satisfied: setuptools>=1.0 in /opt/eff.org/certbot/venv/lib/python2.7/site-packages (from josepy==1.1.0->-r /tmp/tmp.4QILeGQBKW/letsencrypt-auto-requirements.txt (line 87))
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    pycparser==2.19 from https://www.piwheels.org/simple/pycparser/pycparser-2.19-py2.py3-none-any.whl#sha256=344870c533812cb119c5475b5aed033ec546118711338ff9b2b78e67098d64e7 (from -r /tmp/tmp.4QILeGQBKW/letsencrypt-auto-requirements.txt (line 105)):
        Expected sha256 a988718abfad80b6b157acce7bf130a30876d27603738ac39f140993246b25b3
             Got        344870c533812cb119c5475b5aed033ec546118711338ff9b2b78e67098d64e7

## Certbot's behavior differed from what I expected because:
A month ago the renewal process works flawless

**Comment by schoen** [comment]
Hi @maroph,

Please see

https://community.letsencrypt.org/t/certbot-auto-certificates-fails-while-installing-phyton-packages-with-these-packages-do-not-match-the-hashes/90363

Note @bmw's discussion there. (Please feel free to join the discussion on the forum if the solutions presented in that thread don't apply to you. Changing how you install and run Certbot won't remove your existing certificates.)
