### ISSUE TITLE
DOCs, FAQ for lack-of-http-80 still recommends TLS-SNI-01

### ISSUE THREAD

**Issue by fermulator** [certbot/certbot#6924]
As per https://community.letsencrypt.org/t/march-13-2019-end-of-life-for-all-tls-sni-01-validation-support/74209
, TLS-SNI-01 validation is deprecated.

Many users were using this method if their server was not listening on port 80
https://certbot.eff.org/faq/#can-i-issue-a-certificate-if-my-webserver-doesn-t-listen-on-port-80
> Yes, using the TLS-SNI-01 challenge. At the moment, Certbot only implements this challenge for Apache. If you’re using the webroot mode, your web server must listen on port 80.

Oops.
When I go through these instructions
https://community.letsencrypt.org/t/how-to-stop-using-tls-sni-01-with-certbot/83210

It assumes HTTP-01 method.

**Comment by schoen** [comment]
Good point! Thanks for letting us know about this, @fermulator.
