### ISSUE TITLE
proposal add into FAQ how to use HTTP-01 + webroot without redirecting .well-known/acme-challenge

### ISSUE THREAD

**Issue by fermulator** [certbot/certbot#6925]
My setup is:

1. apache2
2. SSL proxy front-end
3. certbot
4. port80 was NOT exposed to the proxy host running certbot

Was previously using the SNI method, but since it's now deprecated, we need a workaround.

Thinking it would be good to add into the FAQ something like this:

 * Q: How can I leverage HTTP-01 renewal method when I'm redirecting all HTTP port 80 to HTTPs port 443?
 * A: Exclude the `.well-known/acme-challenge` directory used during renewal by certbot from the redirect rule.
 For example, if using Apache2:
```
        RewriteEngine on
        # Redirect ALL HTTP requests to HTTPS
        # (except) - the acme-challenge path required for certbot
        RewriteCond %{HTTPS} !=on
        RewriteRule !^/?.well-known/acme-challenge https://%{SERVER_NAME}/$1 [R=301,L]
```

**Comment by schoen** [comment]
Hi @fermulator,

I think the existing functionality in `--apache` and `--nginx` already works well for most people when they have HTTP-level redirections, so most people don't need documentation about this unless they're using `--webroot`.

Let's discuss this on the Community Forum at https://community.letsencrypt.org/. If you're still convinced that the FAQ needs to be updated after that discussion is complete, we can definitely update it.

Also, you can propose website-specific changes over at

https://github.com/certbot/website/issues

Thanks!

**Comment by fermulator** [comment]
Thanks @schoen ;  I figure http redirects are _quite_ common ... which would render this idea valuable.

None-the-less, I have for now deferred the idea into the forums for community assessment.
https://community.letsencrypt.org/t/proposal-add-into-faq-how-to-use-http-01-webroot-without-redirecting-well-known-acme-challenge/90885
