### ISSUE TITLE
Raspberry Pi wheels hash mismatch

### ISSUE THREAD

**Issue by bennuttall** [certbot/certbot#6933]
As raised in #6918 and discussed on [community](https://community.letsencrypt.org/t/certbot-auto-certificates-fails-while-installing-phyton-packages-with-these-packages-do-not-match-the-hashes/90363), users installing certbot on Raspberry Pi have hash mismatches because Raspbian is configured to use [piwheels.org](https://www.piwheels.org) as an additional index.

I'm the maintainer of piwheels.org - it provides wheels built for Raspberry Pi (so users don't have to build from source which can be time consuming on the Pi).

Would it be possible to solve this problem somehow? Some options to explore:

- Add hashes of piwheels files to requirements file in certbot
- File a bug with pip to suggest it uses the hash to find a match rather than fail when it picks up the wrong file

I'm not sure it's possible to specify "only use pypi", as using the `-i` flag sets the index url, but doesn't unset `--extra-index-url`.

I would rather the solution to this not be to delete `/etc/pip.conf` as suggested in the community thread.

Thanks!

P.S. piwheels.org uses certbot, obvs. :100:

**Comment by adferrand** [comment]
Hello @bennuttall. Indeed I understand that `pipwheel` is of a great help for Raspbian users.

We advised to rely only on pypi as a temporary solution, until we decide what is the best thing to do here. Indeed, as a first level of decision, Certbot is available for Debian-like systems, and so is the preferred way to install it, while `certbot-auto` approach is more brittle.

If we go to improve the `certbot-auto` support on Raspberry Pi, I think indeed that your first solution proposed could be a good approach. It would require to add additional hashes as exposed by pipwheels.org, but I do not see technical blocker for `pip`, it should be supported directly. Then it would require either that we implement the hash retrieval from our scripts, or by asking to add this capability to `hashin` (which is used to calculate the hashes here, maybe it is already supported).

@bmw, what do you have an opinion here?

**Comment by bmw** [comment]
> I would rather the solution to this not be to delete /etc/pip.conf as suggested in the community thread.

Yeah. Our preferred solution to this is for people to follow our [installation instructions for Raspbian Stretch](https://certbot.eff.org/lets-encrypt/debianstretch-other) or [newer](https://certbot.eff.org/lets-encrypt/debiantesting-other) which doesn't use pip at all avoiding this problem.

I added another [post to the community forum](https://community.letsencrypt.org/t/certbot-auto-certificates-fails-while-installing-phyton-packages-with-these-packages-do-not-match-the-hashes/90363/8) explaining this and why this solution should be preferred (at least on our end) over deleting `/etc/pip.conf` to hopefully deter some people from doing so.

> Add hashes of piwheels files to requirements file in certbot

I think this is probably the best solution. In theory, it does reduce certbot-auto's security slightly because we're configuring it to trust additional packages from third party sources that most of our users should never use because they're not on Raspbian, but in practice I don't think it's likely to be a problem.

Do you have any concerns about this @erikrose?

**Comment by adferrand** [comment]
I checked, `hashin` can be used with an alternative index url, and can be called as a library. With this, we can write a consolidated hashed requirement file in the script in `letsencrypt-auto-source`.

**Comment by erikrose** [comment]
> In theory, it does reduce certbot-auto's security slightly because we're configuring it to trust additional packages from third party sources that most of our users should never use because they're not on Raspbian, but in practice I don't think it's likely to be a problem.
> 
> Do you have any concerns about this @erikrose?

@bmw I am not overjoyed about it, as it adds a whole independent provider whose compromise could pwn our users, if we're just blindly trusting hashes we get from hashin. (Remember that we should always at least run hashin from multiple network locations and at different times and make sure everything at least agrees before committing; let's not get cavalier.) piwheels is not shy about publishing "none-any" wheels ([example](https://www.piwheels.org/project/wheel/))—ones with no platform or architecture restriction—and besides, I'm not aware of any pip feature that can limit what repos are looked at for which platform, so we'd really be exposing our whole certbot-auto userbase to any hijinks on piwheels. Further, I suspect piwheels is a softer target than PyPI; for one thing, its audience is smaller and may thus take longer to notice a bad package. Can we just lean harder on Raspbian packages? My second choice would be an architecture detection test in certbot-auto which adds the piwheels hashes to the mix.

**Comment by bcutter** [comment]
I use certbot-auto on a Pi 3B+ with Raspbian Stretch (Debian 9) which is setting up a virtual env and ran into this hash mismatch issue. Very frustrating to finally find these information here.

Only solution to get virtual env and therefore certbot-auto to run was to change "extra-index-url=https://www.piwheels.org/simple" to "#extra-index-url=https://www.piwheels.org/simple" in "etc/pip.conf" (didn´t want to delete the whole file at this time).

I guess https://github.com/pypa/pip/issues/6395 would be a solution for this.

**Comment by bennuttall** [comment]
Completely understand - it's a tricky one to solve. Ideally, one or both of my suggestions to pip will be accepted and that will resolve the problem.

All I want to try and avoid is:

- Users get stuck and confused trying to install certbot
- Users are recommended to remove `pip.conf` in order to solve the problem

If your documentation can suggest the debian packaged solution and deter pip installation on Raspbian, this is perfectly suitable.

**Comment by bmw** [comment]
@erikrose, I agree with you. Depending on what decide with packaging going forward, we may need to revisit this problem, but for now I think we should just tell people to use the Debian packages.

> If your documentation can suggest the debian packaged solution and deter pip installation on Raspbian, this is perfectly suitable.

I created https://github.com/certbot/website/issues/404 to track us doing this on the main page of https://certbot.eff.org. If there is other documentation you've seen around this that you think can be improved, please send me a link!

**Comment by Akito13** [comment]
> 
> 
> I use certbot-auto on a Pi 3B+ with Raspbian Stretch (Debian 9) which is setting up a virtual env and ran into this hash mismatch issue. Very frustrating to finally find these information here.
> 
> Only solution to get virtual env and therefore certbot-auto to run was to change "extra-index-url=https://www.piwheels.org/simple" to "#extra-index-url=https://www.piwheels.org/simple" in "etc/pip.conf" (didn´t want to delete the whole file at this time).
> 
> I guess [pypa/pip#6395](https://github.com/pypa/pip/issues/6395) would be a solution for this.

Same environment, same setup, same problem, here.

**Comment by bereska** [comment]
@bcutter , thank you. It was the only solution to this very frustrating problem

**Comment by cjerdonek** [comment]
FYI, this issue was recently addressed and merged in pip: https://github.com/pypa/pip/pull/6699

**Comment by bmw** [comment]
I saw! Thanks for writing that PR and following up with an update :smile:

Once a new version of `pip` is out containing that PR, we can potentially update the version pinned in [pipstrap](https://github.com/certbot/certbot/blob/master/letsencrypt-auto-source/pieces/pipstrap.py) and it should definitively solve this problem.

**Comment by cjerdonek** [comment]
Great!

**Comment by adferrand** [comment]
Ok, pip 19.2 contains the fix. However, it is also dropping support for Python 3.4. So if we upgrade certbot-auto, CentOS 6 users, who have only certbot-auto as official installation method, and use Python 3.4, will be on their own.

If we make the upgrade, we need to quite quickly migrate CentOS 6 Certbot users to Python 3.6.

cc @bmw

**Comment by erikrose** [comment]
I did a casual review (read the PR prose but not the code) of the pip patches, and they looks great to me. Good design, security not impacted (modulo bugs). Is there a Python 3.6 package for CentOS in a reasonable repo? If so, I think we have a good path here.

**Comment by bmw** [comment]
We're planning on deprecating certbot-auto on Raspbian systems (as well as most other OSes) in the coming months so I'm going to close this issue as wontfix.

**Comment by theAkito** [comment]
@bmw Where's the announcement for that?

**Comment by bmw** [comment]
There isn't one yet because we don't have the system we're going to recommend people migrate to ([snaps](https://snapcraft.io/)) quite ready yet.

When it is, our installation instructions on https://certbot.eff.org will be updated and we'll make posts on [Let's Encrypt's community forum](https://community.letsencrypt.org/). If things are going well, shortly after that existing certbot-auto installations will continue to work, but they will stop upgrading itself telling users that if they want a newer version of Certbot, they'll have to use a different installation method.
