### ISSUE TITLE
Insecure default permissions for renewal configuration

### ISSUE THREAD

**Issue by flexponsive** [certbot/certbot#6936]
My certbot by default makes the folder ``/etc/letsencrypt/renewal/`` world readable. This is a security risk, because the files in that folder may contain confidential access tokens. These tokens are exposed to any user on the machine.

*Example*: I'm using certbot with a plugin for my DNS provider, Gandi, in order to benefit from wildcard certificates. This means the renewal configuration contains their LiveDNS access token, which is as good as having the admin password to my DNS account.

## My operating system is (include version):

Ubuntu 18.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Installed from ``ppa:certbot/certbot``, I have version 0.31.0

## I ran this command and it produced this output:

(not applicable)

## Certbot's behavior differed from what I expected because:

I expect the ``/etc/letsencrypt/renewal/`` to have the same default permissions as the keys folder, because the data are equally sensitive.

## Workaround

Manually change the permissions for the folder. Certbot + renewal still work for me.

**Comment by alexzorin** [comment]
Every single Certbot DNS plugin will accept credentials ONLY via an external file, separate to the renewal parameters (examples: [cloudflare](https://certbot-dns-cloudflare.readthedocs.io/en/stable/), [rfc2136](https://certbot-dns-rfc2136.readthedocs.io/en/latest/), [linode](https://certbot-dns-linode.readthedocs.io/en/stable/)).

In fact, Certbot will even warn you if the credentials file has unsafe file permissions:

https://github.com/certbot/certbot/blob/12ab59e1fc6929c3d9d37090e4d66438f388ba5c/certbot/plugins/dns_common.py#L309-L316

Similar story with third-party DNS plugins: https://github.com/obynio/certbot-plugin-gandi - they should/do instruct you to use a separate credentials file, and to permission it appropriately.

If you have identified a plugin which takes credentials as part of its renewal parameters file, that should be a bug report on that plugin.

**Comment by flexponsive** [comment]
Thank you for the fast reply!

Indeed the plugin you mentioned is the one I recreated everything following according their instructions. The initial certificate is created with an external credentials file like this:

    certbot certonly --noninteractive -a certbot-plugin-gandi:dns 
       --certbot-plugin-gandi:dns-credentials gandi.ini -d domain.com

A side-effect of this command is that a file is created in the `/etc/letsencrypt/renewal` folder with this content:

    # renew_before_expiry = 30 days
	version = 0.31.0
	archive_dir = /etc/letsencrypt/archive/domain.com
	cert = /etc/letsencrypt/live/domain.com/cert.pem
	privkey = /etc/letsencrypt/live/domain.com/privkey.pem
	chain = /etc/letsencrypt/live/domain.com/chain.pem
	fullchain = /etc/letsencrypt/live/domain.com/fullchain.pem

	# Options used in the renewal process
	[renewalparams]
	account = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	authenticator = certbot-plugin-gandi:dns
	certbot_plugin_gandi:dns_credentials = gandi.ini
	server = https://acme-v02.api.letsencrypt.org/directory

So the renewal file references the credentials file, but it also contains an `account` field. My question is now, is it OK to have this `account` field in a world readable file?

**Comment by alexzorin** [comment]
`account` refers to the MD5 digest of the public key of your ACME account. If you look in `/etc/letsencrypt/accounts/*/directory/`, you will see it matches. It is totally non-sensitive.

**Comment by flexponsive** [comment]
Thanks for this clarification, this issue can be closed because it was a misunderstanding.

I was following along the documentation here: https://certbot.eff.org/docs/using.html#plugins and was under the impression that account is sensitive (e.g. "If your account key has been compromised or you otherwise need to revoke a certificate")

**Comment by adferrand** [comment]
Yes as usual with method based on asynchronous cryptography, the private key is sensible, not the public one. Here it is the public key that is stored in word readable permissions.

Ok, I close.
