### ISSUE TITLE
Problems with the IP address local versus global : how to make cerbot working?

### ISSUE THREAD

**Issue by marcoippolito** [certbot/certbot#6942]
Hi,
I'm developing a web page with my PC Ubuntu 18.04.01 Server Edition connected to my Internet Service Provider's router (called "station") 
I bought an internet domain with Namecheap.com and linked it as Dynamic DNS Record with the global IP Address of the Internet Service Provider's station, since it is not possible to link an internet domain to a local IP address like 192.168.1.9
In this way, when inserting the local IP address into the web browser in a laptop connected to the same ISP's "station", or when I insert the domain name in a laptop or in a smartphone not connected to my local network , I get the webpage correctly

Now, I want to get a https certificate via certbot but I get this error message:

    marco@pc01:~/go/src/MyPage$ sudo certbot certonly --webroot -w 
    /home/marco/go/src/MyPage -d ggc.world -d www.mypage.org
    [sudo] password for marco:
    Saving debug log to /var/log/letsencrypt/letsencrypt.log
    Plugins selected: Authenticator webroot, Installer None
    Obtaining a new certificate
    Performing the following challenges:
    http-01 challenge for mypage.org
    http-01 challenge for www.mypage.org
    Using the webroot path /home/marco/go/src/MyPage for all unmatched domains.
    Waiting for verification...
    Cleaning up challenges
    Failed authorization procedure. www.mypage.org (http-01): urn:ietf:params:acme:error:connection  
    :: The server could not connect to the client to verify the domain :: Fetching 
    http://www.mypage.org/.well-known/acme-challenge/RyUD0QsqGz-  
    14UpDytB1ybTCiXfYivGPCzl62uwxUgE: Connection refused, mypage.org (http-01):  
    urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the 
    domain :: Fetching http://mypage.org/.well-known/acme-challenge 
    /qFfREkIdFgSaIEVEIM1dXeu4oEl8YBWD38hMs6cQz6c: Connection refused

    IMPORTANT NOTES:
    - The following errors were reported by the server:

    Domain: www.mypage.org
    Type: connection
    Detail: Fetching
    http://www.mypage.org/.well-known/acme-challenge/RyUD0QsqGz-   
    14UpDytB1ybTCiXfYivGPCzl62uwxUgE:
    Connection refused

    Domain: mypage.org
    Type: connection
    Detail: Fetching
    http://mypage.org/.well-known/acme-challenge  
    /qFfREkIdFgSaIEVEIM1dXeu4oEl8YBWD38hMs6cQz6c:
    Connection refused

    To fix these errors, please make sure that your domain name was
    entered correctly and the DNS A/AAAA record(s) for that domain
    contain(s) the right IP address. Additionally, please check that
    your computer has a publicly routable IP address and that no
    firewalls are preventing the server from communicating with the
    client. If you're using the webroot plugin, you should also verify
    that you are serving files from the webroot path you provided.

In the configuration file of my webpage I put this: 

    httpaddr = 192.168.1.7
    httpport = 8080

where 192.168.1.7 is the local address

while in the configuration of the domain I put the global IP address of the Internet Service Provider's router.

But if i put in the configuratoin file of the web page the Global IP Address, which here I put as  11.111.111.111, the web page doesn't show up:

    marco@pc01:~/go/src/MyPages$ bee run
    ______
    | ___ \
    | |_/ / ___ ___
    | ___ \ / _ \ / _ \
    | |_/ /| __/| __/
    \____/ \___| \___| v1.10.0
    2019/04/10 17:13:15 INFO ▶ 0001 Using 'MyPage' as 'appname'
    2019/04/10 17:13:15 INFO ▶ 0002 Initializing watcher...
    2019/04/10 17:13:16 SUCCESS ▶ 0003 Built Successfully!
    2019/04/10 17:13:16 INFO ▶ 0004 Restarting 'MyPage'...
    2019/04/10 17:13:16 SUCCESS ▶ 0005 './MyPage' is running...
    2019/04/10 17:13:16.170 [I] [asm_amd64.s:2361] http server Running on http://11.111.111.111:8080
    2019/04/10 17:13:16.170 [C] [asm_amd64.s:2361] ListenAndServe: listen tcp 
    11.111.111.111:8080: bind: cannot assign requested address

so... briefly the problem is that in the Namecheap.com's configuration I had to insert the IP global address of the Internet Service Provider's router, and in the webpage configuration file I have to put the local IP address, which is not accepted by Certbot, because it requires only Global IP Addresses.

So... how can I successfully proceed with cerbot in order to obtain the https certificate?

Looking forward to your kind help.
Marco

**Comment by ohemorange** [comment]
Hey @marcoippolito! This is expected behavior, not a bug with Certbot. I recommend describing your situation on the community forum at https://community.letsencrypt.org/, where a larger community of people familiar with the project will be able to more quickly answer your questions.

**Comment by marcoippolito** [comment]
Thanks @ohemorange for indicating me the letsencrypt's community. I posted my question there.
Marco
