### ISSUE TITLE
[FR] argument zone for certbot-dns-google 

### ISSUE THREAD

**Issue by davidebelloni** [certbot/certbot#6945]
Hi,
I would use certbot with dns google plugin but in my environment is not possible.

I've a GCP project dedicated to a service (www.example.com) with a DNS zone (where I would to insert TXT record) that is different from any "progressively less-specific domain names" of FQDN. I've this setup because the domain of FQDN is managed by our provider and they have setup up a CNAME to GCP.

So in DNS provider there is the following record:
`www.example.com CNAME www.example.com.google.example.com`

And in GCP DNS there is "www.example.com.google.example.com" zone where I want to insert the TXT ACME record for www.example.com certificate.

With certbot-dns-google plugin this is not possible because it search for the following zones in GCP project: www.example.com, example.com and com

If I could pass the zone to change, this setup should works

Thanks

**Comment by bmw** [comment]
I believe this features is being tracked by #6566 so I'm closing this issue, but if you think I've missed something, please let me know!

**Comment by davidebelloni** [comment]
You are absolutely right. I had search only for issues with Google dns label
