### ISSUE TITLE
Implement redirect by default

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#6960]
https://docs.google.com/document/d/1aKnQYEzCrZgYX-iuE-ErOdIKERUuLmZSX_BDb7d0M6I/edit

# Transitioning users

I think we need to properly announce the change and transition here as running Certbot in non-interactive mode defaults to no redirect.

> Which users will see this message? 

In addition to there being various ways that they could see that output, I'd want the change to be mentioned in our changelog and release announcement. It's not perfect, but I think it's the simple and standard way to try and give people a heads up.

> Of those, which will have problems if we don't do it?

A very small minority. With that said, I think it costs us very little and I think it's good practice to try and help people relying on our software.

> Which users will get confused and erroneously add the flag?

I'm pretty open to the wording on the message and we don't have to mention --no-redirect. It was just the first wording that came to mind.

# Consistent behavior

I think our current behavior is "it works this way except when". I think that because we say "certbot automatically sets up https for you except it doesn't actually unless you select the correct answer to this question". redirect should be part of install, not an enhancement. the fact that it's currently implemented as an enhancement is an implementation detail that shouldn't govern our decisions about certbot's behavior.

> How would this work if the installer doesn't support redirects either because support for it was just never written or because it's for something other than a webserver like postfix where HTTP redirects don't make sense?

The action certbot's default run should take is "turn on https", whatever that means for the server. Honestly, that could even mean switching redirect to be part of deploy for nginx and apache.

> When I initially wrote that question I was worried about having consistent behavior and communicating the server's current state to the user.
>
> Now I think we can pretty easily solve this though by making our own plugins consistent and encouraging third party installer plugins (if they exist by the time we make these changes) to do the same.

**Comment by bmw** [comment]
I would like to bump the priority of this. At the very least, I think changes to the non-interactive flow would be nice to land before Certbot 1.0.

**Comment by bmw** [comment]
Superseded by #7594.
