### ISSUE TITLE
client.query_registration uses POST instead of POST as GET

### ISSUE THREAD

**Issue by wmwmw** [certbot/certbot#6962]
[Here](https://github.com/certbot/certbot/blob/d7610c1ae73699cbac7d3433d8ff286d201ea018/acme/acme/client.py#L134) acme module uses empty UpdateRegistration message (POST with payload `{}`), instead of using standard POST as GET (POST with `null` content), resulting in some servers (`pebble` in strict mode) rejecting these requests.

**Comment by adferrand** [comment]
Is it something you started to see with recent versions of Pebble? If so, do you know which one?

**Comment by cpu** [comment]
It should be reproduce-able with Pebble 2.0.x and up.  https://github.com/letsencrypt/pebble/commit/fea30198d2ca1f74f558824c76510ae7ff70e439 is when Pebble's `wfe.UpdateAccount` function would have started to return an error for an empty account update.
