### ISSUE TITLE
Deduplicate Dockerfile-dev and Dockerfile

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#698]
[Dockerfile-dev](https://github.com/letsencrypt/letsencrypt/blob/26c1f003d0d05397154fe63e1f452ed2148cfe75/Dockerfile-dev) is 99% copy and paste from [Dockerfile](https://github.com/letsencrypt/letsencrypt/blob/26c1f003d0d05397154fe63e1f452ed2148cfe75/Dockerfile). However, I'm not sure how to reference local files in the `FROM` directive...

**Comment by kuba** [comment]
Also, instructions could probably use `docker build -t letsencrypt-dev` instead of `docker build -t letsencrypt`

**Comment by SwartzCr** [comment]
I believe this has been resolved
