### ISSUE TITLE
CERTBOT : issue pkg_ressources

### ISSUE THREAD

**Issue by grulles** [certbot/certbot#6981]
Hi, 
Since 2 days I have some trouble with certbot. After a yum update cerbot doesn't work. 
See the log 
/usr/bin/certbot renew --pre-hook "systemctl stop httpd" --post-hook "systemctl start httpd"
2497, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: requests 2.6.0 has no such extra feature 'security'
[root@srvprod01 tmp]# /usr/bin/certbot renew --pre-hook "systemctl stop httpd" --post-hook "systemctl start httpd"
Traceback (most recent call last):
  File "/usr/bin/certbot", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3011, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2497, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: requests 2.6.0 has no such extra feature 'security'

OS : CentOS Linux release 7.6.1810 (Core) 
Certbot installed using yum.  : yum install python-certbot-apache
No issue during installation process
If you need more details, just ask. 
Regards,
Damien.

**Comment by schoen** [comment]
Hi @grulles,

Did you install Certbot from EPEL?

Have you ever installed or updated any Python packages on this system with `pip`?
