### ISSUE TITLE
ValueError: Requesting acme-v01.api.letsencrypt.org/directory: Network is unreachable

### ISSUE THREAD

**Issue by JuggernautPanda** [certbot/certbot#6987]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

My domain is: www.vesso.in

I ran this command: sudo certbot --apache

It produced this output: OSError: [Errno 101] Network is unreachable
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7ff2ad6085f8>: Failed to establish a new connection: [Errno 101] Network is unreachable

My web server is (include version): Apache

The operating system my web server runs on is (include version): Ubuntu 18.04

My hosting provider, if applicable, is: AWS

I can login to a root shell on my machine (yes or no, or I don’t know): yes

I’m using a control panel to manage my site (no, or provide the name and version of the control panel): No

The version of my client is (e.g. output of certbot --version or certbot-auto --version if you’re using Certbot): certbot 0.23.0

**Comment by adferrand** [comment]
Hello! From the logs, it seems that your AWS instance is not able to connect to the ACME server, and certainly more generally to the outside world. 

This is most likely a firewall or network configuration problem. I invite you to reach the community forum https://community.letsencrypt.org and get the appropriate help to configure your instance.
