### ISSUE TITLE
Depends: libssl1.1 but 1.1.1b-2 is to be installed

### ISSUE THREAD

**Issue by janw-me** [certbot/certbot#6991]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):

Raspbian Stretch Lite, version april 2019 (freshly installed

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Followin the guide: https://certbot.eff.org/lets-encrypt/debianstretch-nginx  
Rasbian does not have _stretch-backports_ So I picked buster.

    $ sudo apt-get install certbot python-certbot-nginx -t buster

This worked as did `$ sudo certbot --nginx`

## I ran this command and it produced this output:

    $ certbot-auto renew

output: 

```Requesting to rerun /usr/local/bin/certbot-auto with root privileges...
Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)
Get:1 http://mirrordirector.raspbian.org/raspbian buster InRelease [15,0 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease [15,0 kB]      
Get:3 http://archive.raspberrypi.org/debian stretch InRelease [25,4 kB]                     
Get:4 http://mirrordirector.raspbian.org/raspbian buster/main armhf Packages [13,0 MB]
Get:5 http://archive.raspberrypi.org/debian stretch/main armhf Packages [223 kB]
Fetched 13,3 MB in 9s (1405 kB/s)                                                                                                          
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ca-certificates is already the newest version (20161130+nmu1+deb9u1).
gcc is already the newest version (4:6.3.0-4).
gcc set to manually installed.
openssl is already the newest version (1.1.0j-1~deb9u1).
openssl set to manually installed.
python is already the newest version (2.7.13-2).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libssl-dev : Depends: libssl1.1 (= 1.1.0j-1~deb9u1) but 1.1.1b-2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

## Certbot's behavior differed from what I expected because:

The error is in the end: ` libssl-dev : Depends: libssl1.1 (= 1.1.0j-1~deb9u1) but 1.1.1b-2 is to be installed`

How to handle this?

## Here is a Certbot log showing the issue (if available):
I checked `/var/log/letsencrypt/letsencrypt.log` no problems there. since this is an installing problem I'll keep this out for now. (will add if needed)

**Comment by sydneyli** [comment]
Seems related to #5698 -- you're using two different installation methods of Certbot (via packages, and via certbot-auto). Does plain old `certbot renew` work?

**Comment by janw-me** [comment]
Fixed the error installed `libssl-dev` first via buster

    $ sudo apt-get install libssl-dev -t buster

**Comment by janw-me** [comment]
> Seems related to #5698 -- you're using two different installation methods of Certbot (via packages, and via certbot-auto). Does plain old `certbot renew` work?

yes `sudo cerbot renew` works. I was not aware these are different things.
