### ISSUE TITLE
FreeBSD Port: security/py-certbot cron not found

### ISSUE THREAD

**Issue by Oclair** [certbot/certbot#7006]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
FreeBSD 11.2p9

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Via Ports 

## I ran this command and it produced this output:
crontab as root
0 0,12 * * * python2.7 -c 'import random; import time; time.sleep(random.random() * 3600)' && certbot -q renew --renew-hook "service nginx restart"
now my crontab sends root back an email that 
"/bin/sh: certbot: not found"

# locate certbot
/usr/local/bin/certbot-2.7

## Certbot's behavior differed from what I expected because:
because it used to work

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
not relevant

Who renamed the executable for FreeBSD Port: security/py-certbot?
why?

Did you update the docs on the certbot website as well?
Why did letsencrypt not notify users of their solution of this change?
Why is this not added to UPDATING?

Thank you for your support for open source!

**Comment by Oclair** [comment]
#Solution
pkg delete py27-requests-toolbelt

Updating database digests format: 100%
Checking integrity... done (0 conflicting)
Deinstallation has been requested for the following 3 packages (of 0 packages in the universe):

Installed packages to be REMOVED:
	py27-requests-toolbelt-0.8.0
	py27-acme-0.31.0,1
	py27-certbot-0.31.0_1,1

Number of packages to be removed: 3

The operation will free 8 MiB.

Proceed with deinstalling packages? [y/N]: y

#then enter
cd /usr/ports/security/py-certbot && make install clean

**Comment by adferrand** [comment]
As the upstream developers of Certbot, we are working closely with integrators that package Certbot on the OSes, but we are not accounted for. So how Certbot is distributed in FreeBSD is more a question for FreeBSD maintainers.

About the documentation, a recent PR has been merged to update instructions regarding the Python 3 that should be used now: https://github.com/certbot/website/pull/408

If the documentation is still not accurate, do not hesitate to open an issue about it on the certbot/website project.

**Comment by Oclair** [comment]
As a user of Certbot I submitted an issue which is relevant to my OS.  My post was followed by an answer how to get things working again after former versions of Python are depreciated (it will happen again).  The Certbot instructions published mentions using pkg and ports, so the support mechanism has been informed and appropriate decisions on how to inform their other users (my fellow colleagues) is purely up to them (the certbot developers and docs maintainers).  
Thank you for your contributions to free software!
OC
