### ISSUE TITLE
certbot-auto prints empty line with --quiet

### ISSUE THREAD

**Issue by nerijus** [certbot/certbot#7027]
I have such command in cron:
```
certbot-auto --standalone renew --pre-hook "service httpd stop &>/dev/null; \
iptables -t nat -I net_dnat -p tcp --dport 443 -j ACCEPT" --post-hook \
"iptables -t nat -D net_dnat -p tcp --dport 443 -j ACCEPT; \
service httpd start &>/dev/null; service dovecot restart &>/dev/null; \
service mailscanner restart &>/dev/null" --quiet
```
2 days ago certbot-auto autorenewed itself and now this command prints empty line when run, so I get email from cron. I did not get emails before.

**Comment by adferrand** [comment]
Hello, thank you for your report! 

This will be fixed on certbot 0.34.1, that will be released on next Monday. Related PR is #7016, you can find temporary mitigations in #7012.
