### ISSUE TITLE
Seg Fault when Apache Config is very large (90,000+lines)

### ISSUE THREAD

**Issue by lrirwin** [certbot/certbot#7035]
## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt-get update
apt-get install software-properties-common
add-apt-repository ppa:certbot/certbot
apt-get update
apt-get install python-certbot-apache

## I ran this command and it produced this output: certbot renew
.... Segmentation fault (core dumped)

## Here is a Certbot log showing the issue (if available):
2019-05-06 12:20:26,593:DEBUG:certbot.main:certbot version: 0.31.0
2019-05-06 12:20:26,594:DEBUG:certbot.main:Arguments: []
2019-05-06 12:20:26,595:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2019-05-06 12:20:26,604:DEBUG:certbot.log:Root logging level set at 20
2019-05-06 12:20:26,604:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2019-05-06 12:20:26,613:DEBUG:certbot.plugins.selection:Requested authenticator <certbot.cli._Default object at 0x7f97f6690e10> and installer <certbot.cli._Default object at 0x7f97f6690e10>
2019-05-06 12:20:26,623:DEBUG:certbot.storage:Should renew, less than 30 days before certificate expiry 2019-05-23 20:28:01 UTC.
2019-05-06 12:20:26,623:INFO:certbot.renewal:Cert is due for renewal, auto-renewing...
2019-05-06 12:20:26,623:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2019-05-06 12:21:01,910:DEBUG:certbot_apache.configurator:Apache version is 2.4.29

## This is the one that works:
```
User www-data
Group www-data 
ServerSignature Off
ServerTokens Prod
AddHandler cgi-script .cgi .pl .php
AddHandler php5-script .php
<Directory />
  Require all denied
</Directory>
<Directory /u/www>
  Options -Indexes +FollowSymLinks +Includes +ExecCGI +MultiViews
  AllowOverride None
  <RequireAll>
    Require all granted
  </RequireAll>
  <FilesMatch "^\.ht">
    Require all denied
    Satisfy All
  </FilesMatch>
</Directory>
<VirtualHost *:80>
  Redirect / https://asp.ccamedical.net/
</VirtualHost>
<IfModule mod_expires.c>  
  ExpiresDefault "access plus 1 day"
</IfModule>
<IfModule mod_ssl.c>
  <VirtualHost *:443>
    SSLEngine on
    SSLCertificateFile    /etc/letsencrypt/live/asp.ccamedical.net/cert.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/asp.ccamedical.net/privkey.pem
    SSLCACertificatePath  /etc/letsencrypt/live/asp.ccamedical.net/
    SSLCACertificateFile  /etc/letsencrypt/live/asp.ccamedical.net/fullchain.pem
    SSLHonorCipherOrder On
    SSLCipherSuite ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:EDH-RSA-DES-CBC3-SHA:AES256-SHA:ECDHE-RSA-RC4-SHA
    SSLProtocol All -SSLv2 -SSLv3
    SeUser www-data
Group www-data 
ServerSignature Off
ServerTokens Prod
AddHandler cgi-script .cgi .pl .php
AddHandler php5-script .php
<Directory />
  Require all denied
</Directory>
<Directory /u/www>
  Options -Indexes +FollowSymLinks +Includes +ExecCGI +MultiViews
  AllowOverride None
  <RequireAll>
    Require all granted
  </RequireAll>
  <FilesMatch "^\.ht">
    Require all denied
    Satisfy All
  </FilesMatch>
</Directory>
<VirtualHost *:80>
  Redirect / https://asp.ccamedical.net/
</VirtualHost>
<IfModule mod_expires.c>  
  ExpiresDefault "access plus 1 day"
</IfModule>
<IfModule mod_ssl.c>
rverAdmin admin@ccamedical.com
    ServerName asp.ccamedical.net
    ServerAlias asp.ccamedical.net
    DocumentRoot /u/www
    LogLevel warn
    ErrorLog ${APACHE_LOG_DIR}/pe5-ssl_error.log
    CustomLog ${APACHE_LOG_DIR}/pe5-ssl_access.log combined
    <FilesMatch "\.(cgi|shtml|phtml|php)$">
      SSLOptions +StdEnvVars
    </FilesMatch>
    <FilesMatch "^\.ht">
      Require all denied
      Satisfy All
    </FilesMatch>
    <Directory /u/www/pe5/>
      Options -Indexes +FollowSymLinks +Includes +ExecCGI +MultiViews
    </Directory>
  </VirtualHost>
</IfModule>
```

## The only difference is in the <Directory /u/www> section that makes it seg fault:
```
<Directory /u/www>
  Options -Indexes +FollowSymLinks +Includes +ExecCGI +MultiViews
  AllowOverride None
  <RequireAny>
    Require ip 1.2.3.0/24
    Require ip 1.32.232.0/21
    Require ip 3.0.0.0/32
    Require ip 3.2.0.0/15
.... (90,000 + more of these US CIDR's)
    Require ip 220.243.242.0/24
    Require ip 223.26.16.0/22
    Require ip 223.27.21.243/32
  </RequireAny>
  <FilesMatch "^\.ht">
    Require all denied
    Satisfy All
  </FilesMatch>
</Directory>
```

**Comment by lrirwin** [comment]
Found this in /var/log/kern.log this morning:
May  7 08:18:37 localhost kernel: [171003.978855] certbot[2252]: segfault at 7ffc72dabff8 ip 00007fcf1c4c2d08 sp 00007ffc72dabff0 error 6 in libaugeas.so.0.24.0[7fcf1c491000+4d000]

**Comment by lrirwin** [comment]
And found a reference to the same issue at: https://github.com/hercules-team/augeas/issues/569

**Comment by lrirwin** [comment]
It appears that this was addressed in libaugeas 1.11.0 and Ubuntu 18.04.2 has version 1.10.1...

**Comment by lrirwin** [comment]
Work-around that succeeded on 5/8/2019 in the early morning:
`# Must put in a smaller config or it causes cerbot to end with seg fault/core dump
/bin/systemctl stop apache2
/bin/cp -p /etc/apache2/sites-available/002-pe5-ssl.conf.allowall /etc/apache2/sites-available/002-pe5-ssl.conf
/bin/systemctl start apache2

certbot renew

/bin/systemctl stop apache2
/bin/cp -p /etc/apache2/sites-available/002-pe5-ssl.conf.requireips /etc/apache2/sites-available/002-pe5-ssl.conf
/bin/systemctl start apache2
`

**Comment by Lolnarr** [comment]
Same issue appeared for me with a large Apache config (112k lines). I would have never thought about this being the problem, so thanks a lot for the workaround!
Anyway, I would love to see this being fixed. 👍
