### ISSUE TITLE
Use some of "unofficial bash strict mode" in certbot-auto

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7039]
If we don't kill certbot-auto with https://github.com/certbot/certbot/issues/5884, I think we should rewrite certbot-auto to use Python over shell scripts as much as possible.

We may not be able to completely escape shell scripting though. If we cannot, I think we should take ideas from http://redsymbol.net/articles/unofficial-bash-strict-mode/ and apply them in `certbot-auto`. We already use `set -e`, but `set -u` would have prevented https://github.com/certbot/certbot/issues/7031.

While I like `set -o pipefail`, I don't think it is POSIX compliant, but we could also look into setting `IFS`.

**Comment by ohemorange** [comment]
I'm closing this because we're really truly trying to kill certbot-auto.
