### ISSUE TITLE
Implement RFC 8555 Subproblems

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7046]
This is to make use of boulder's work at https://github.com/letsencrypt/boulder/issues/4193. I think a good starting point here is just making sure the field is properly parsed and displayed to the user.

I'm putting this in the next milestone because I think doing this is both valuable and shouldn't be too difficult.

**Comment by adferrand** [comment]
Hello @cpu! 

From the RFC 8555, I see that an error containing subproblems will have the key `subproblems` in the JSON representing the error. Testing if the key exists and does not contain an empty object or assimilate, would be a reliable way to trigger a suitable display logic on client side, right?

**Comment by adferrand** [comment]
One potential complex situation I see here to handle.

The `acme` module in Certbot implements a message error as an object with a `typ` (and `code`) parameter, calculated from the `type` received in the JSON from ACME server. This is used in someplaces to trigger some specific branches, like here:
https://github.com/certbot/certbot/blob/18797dca79c163449ab6892649da82ae4a89f22b/acme/acme/client.py#L1180-L1185

In theory, an error with sub-problems may contains a specific type like `badNonce` in one of the sub-problems, with another more generic error at the top-level.

So I imagine that we need to implement in our own representation of ACME error messages (`acme.message.Errors`) some ad-hoc methods to match a given error code not only at the top level, but also in sub-problems if they exist.

@bmw, your thought on this?

**Comment by bmw** [comment]
> To try and account for this I made an effort to include at least one identifier in the top-level problem detail anywhere we return a problem with sub-problems so that clients like Certbot that display only some fields of the top-level problem will still be giving actionable information. Adding explicit display of the sub-problems will be a big improvement 🎉

Thanks @cpu! Are there any areas where you expect Certbot's error output to get significantly worse as a result of these changes server side until we implement subproblems on our end? Also, when do you expect the use of subproblems to be enabled in production?

> So I imagine that we need to implement in our own representation of ACME error messages (acme.message.Errors) some ad-hoc methods to match a given error code not only at the top level, but also in sub-problems if they exist.

That's a good idea! My initial instinct on how to structure this part of the code is to add an optional `subproblems` field to `acme.messages.Error` which would contain a sequence of additional `Error` objects along with a property like `codes` which would be the sequence of all error codes in both the original `Error` and its subproblems.

**Comment by cpu** [comment]
> Are there any areas where you expect Certbot's error output to get significantly worse as a result of these changes server side until we implement subproblems on our end?

I don't think there will be anywhere that gets significantly worse with perhaps one particular corner case. (If I turn out to be wrong about this I would definitely be willing to revisit it Boulder-side as the situation merits).

The one corner case where I expect Certbot (and likely other ACME clients) to take a small usability hit is the case where an RFC 8555 Order with many names is being finalized that has authorizations requiring CAA recheck (e.g. its authzs were validated >8hrs ago) and more than one recheck produces a CAA error.

Previously in this case Boulder joined all of the failing domain names into one (ugly) comma separated detail in the top level: https://github.com/letsencrypt/boulder/blob/6f93942a0449ea6bc0f6927c5e7520c1034f49b6/ra/ra.go#L905-L907

In the new sub-problem version the top level problem will only have the first erroring identifier and the remaining will be in the sub-problems. I think that's slightly inconvenient for users that can't see subproblems but it seemed like an acceptable trade-off when I implemented it.

> Also, when do you expect the use of subproblems to be enabled in production?

Subproblem support is in [release-2019-06-03](https://github.com/letsencrypt/boulder/releases/tag/release-2019-06-03) and should be going to staging today and prod on Thursday.

**Comment by bmw** [comment]
That all sounds great. Thanks for the additional info.

I want to implement this soon, but I wanted to make sure there weren't any major downsides if we didn't get to this for a release or two.

**Comment by JamesBalazs** [comment]
I started looking at this yesterday in an attempt to get closer to a fix for #9251 

Here's my initial PR: https://github.com/certbot/certbot/pull/9258/

Review and any pointers would be greatly appreciated 🙂

**Comment by alexzorin** [comment]
`acme` now implements subproblems thanks to @JamesBalazs' work in #9258. Thank you.
 
What remains is to review and implement the UX side of this. I've opened https://github.com/certbot/certbot/issues/9273 to track that.
