### ISSUE TITLE
please remove retired Google+ from Main certbot site https://certbot.eff.org/ 

### ISSUE THREAD

**Issue by aleon1220** [certbot/certbot#7050]
The main site https://certbot.eff.org/ has a misleading link to google plus that should be removed since is a retired google product. 
Perhaps a new idea would be to add a LinkedIn Link :-)

**Comment by bmw** [comment]
Thanks for pointing this out @aleon1220. I opened an issue about this in the repository for our website at https://github.com/certbot/website/issues/410.
