### ISSUE TITLE
Handle Apache modules for SUSE

### ISSUE THREAD

**Issue by joohoi** [certbot/certbot#7051]
SUSE Linux supports enabling and disabling Apache modules through `a2enmod` and `a2dismod`. 

We should adapt the implementation from [override_debian.py](https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/override_debian.py) to suit SUSE.

**Comment by RaymondFallon** [comment]
Hey @joohoi, the override_debian.py link you posted appears broken.

**Comment by snosratiershad** [comment]
@RaymondFallon I think now it refers to [this file](https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/_internal/override_debian.py)
