### ISSUE TITLE
Cert not yet due for renewal, but Let's Encrypt Expiry Bot complains

### ISSUE THREAD

**Issue by Harvie** [certbot/certbot#7062]
I receive emails like this from letsencrypt:
"_Let's Encrypt certificate expiration notice for domain "*.example.com" (and 2 more)_"

But when i do `certbot renew` it gives me this:

Cert not yet due for renewal
...
No renewals were attempted.

I guess there is some inconsistency in timings. Can you please set the certbot to renew certificates before letsencrypt starts complaining?

**Comment by alexzorin** [comment]
Please check https://letsencrypt.org/docs/expiration-emails/ , in particular:

> If you’ve issued a new certificate that adds or removes a name relative to your old certificate, you will get expiration email about your old certificate

It is very common to receive this email if you have added or removed names from a certificate.

If you wish to post this question and your domain name to http://community.letsencrypt.org/ , people will be able to check whether that's the case.

**Comment by Harvie** [comment]
Wonder if certbot can deregister the old certificate from expiration notice, when creating new cert with superset of names...

**Comment by adferrand** [comment]
Indeed. For you information, expiration notice mails will start 20 days before effective expiration, while certbot will try to renew certificates one month before their expiration date. 

As @alexzorin said, a new certificate adding names to the old one does not revoke this old one. So it will stay in the LetsEncrypt database, even if you do not use it anymore. It would be the same situation for any other certificate that is removed from your local installation of Certbot without revokation.

Anyway this situation is expected and normal.

**Comment by Harvie** [comment]
> new certificate adding names to the old one does not revoke this old one

When i am adding new names, the certbot asks me if i want to add it to existing certificate or create new one. Would be cool if it also asked if i want to revoke the old one.
