### ISSUE TITLE
Dump failed test farm tests logs in Azure

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7071]
After all of my current PRs are merged to get test farm tests running in Travis, one remaining pain point in my opinion is the fact that when tests fail on an instance, the only relevant output will be something like:
```
1 ubuntu18.04LTS fail
```
This will tell us that a test is failing, but we'll have no idea why until we run the tests again locally.

All output from the test instances are saved in log files, but these aren't included in the Travis output. I think they probably should be in a way that ensures the logfile contents aren't overlapping in Travis' output.

**Comment by adferrand** [comment]
Still relevant.
