### ISSUE TITLE
No module named certbot.main

### ISSUE THREAD

**Issue by dellarte** [certbot/certbot#7078]
## My operating system is (include version):
Debian GNU/Linux 9.9 (stretch)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt-get install certbot -t stretch-backports

## I ran this command and it produced this output:
certbot certonly

Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 7, in <module>
    from certbot.main import main
ImportError: No module named certbot.main

## Certbot's behavior differed from what I expected because:
it shouldn't output this error

## Python version in use : 
Python 2.7.13

**Comment by bmw** [comment]
I think you have multiple Certbot installations on your system that are conflicting with each other. The executable from the Debian package isn't placed in `/usr/local/bin`.

Cleaning up this 2nd installation should resolve your problem. If you need additional help with this, I recommend making a post at https://community.letsencrypt.org where there is a large community of people familiar with the project who would be happy to help you.

**Comment by dellarte** [comment]
You saved my life

**Comment by dandv** [comment]
I've run into the same error on Ubuntu 20.04, with an existing installation I thought I had completely removed by running `sudo apt-get remove certbot python-certbot-nginx`, then following the [Snap installation instructions](https://certbot.eff.org/lets-encrypt/ubuntufocal-nginx).

> The executable from the Debian package isn't placed in `/usr/local/bin`.

Where should the executable be installed on Ubuntu?

Anyway, I ran `sudo rm /usr/local/bin/certbot`, then `which certbot` returned nothing. That made me think the Snap installed certbot in `/usr/local/bin/certbot`, but I Snap is weird and doesn't play with `which`? Running `sudo certbot...` actually work, even though I have no idea where in $PATH `certbot` is.
