### ISSUE TITLE
dns-rfc2136 challenges run infinitely for invalid DNS servers

### ISSUE THREAD

**Issue by tambry** [certbot/certbot#7084]
1. Set `dns_rfc2136_server` to something invalid, e.g. `dns_rfc2136_server = 2001:db8::`.
2. Try to obtain certificates.
3. Challenges run forever.

CTRL+C during a challenge:
```
[... usual]
Performing the following challenges:
dns-01 challenge for [...]
dns-01 challenge for [...]
Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/certbot/auth_handler.py", line 75, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/usr/lib/python3.7/site-packages/certbot/auth_handler.py", line 139, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/usr/lib/python3.7/site-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/lib/python3.7/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 76, in _perform
    self._get_rfc2136_client().add_txt_record(validation_name, validation, self.ttl)
  File "/usr/lib/python3.7/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 112, in add_txt_record
    domain = self._find_domain(record_name)
  File "/usr/lib/python3.7/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 186, in _find_domain
    if self._query_soa(guess):
  File "/usr/lib/python3.7/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 209, in _query_soa
    response = dns.query.udp(request, self.server, port=self.port)
  File "/usr/lib/python3.7/site-packages/dns/query.py", line 240, in udp
    _wait_for_readable(s, expiration)
  File "/usr/lib/python3.7/site-packages/dns/query.py", line 157, in _wait_for_readable
    _wait_for(s, True, False, True, expiration)
  File "/usr/lib/python3.7/site-packages/dns/query.py", line 131, in _wait_for
    if not _polling_backend(fd, readable, writable, error, timeout):
  File "/usr/lib/python3.7/site-packages/dns/query.py", line 87, in _poll_for
    event_list = pollable.poll()
KeyboardInterrupt
```

**Expected:**  
Certbot should set a reasonable query timeout ([this is supported by `dnspython`](https://stackoverflow.com/questions/8989457/dnspython-setting-query-timeout-lifetime)) and alert the user of an issue with the DNS server.

**Comment by ohemorange** [comment]
How would you recommend going about picking a reasonable query timeout? For some of our users, DNS propagation might take a while, and we don't want to cut off before that.

**Comment by tambry** [comment]
@ohemorange This isn't related to propagation. Per my understanding, the SOA is queried to get the information necessary for even adding/deleting the TXT record. If the SOA can't be queried in a reasonable time (probably 5s) then there's likely something wrong with the server and it ought to let the user know instead of waiting infinitely for a response that isn't coming.

Since the DNS server is queried over UDP, it would also be sensible to add a retry mechanism.

**Comment by noci2012** [comment]
Hm maybe this is less about the delay & timeout and more about selecting the right server.
Getting the SOA record and from there determine the primary DNS (first field after SOA).
and try to query that server and maybe try a probe update (before starting to handle the actual challenge) to test if can be updated in reasonable time.

**Comment by osirisinferi** [comment]
> Since the DNS server is queried over UDP, it would also be sensible to add a retry mechanism.

That isn't correct entirely correct. The `dns-rfc2136` plugin uses `dns.query.tcp()`, not `udp()`, for the adding and removing of TXT records and tries `dns.query.tcp()` first for the SOA query before falling back to `udp()`.

Also, the propogation delay is indeed something different. That's handled in `certbot/certbot/plugins/dns_common.py` after the DNS plugin has added the required TXT records. Any query timeout should &ndash; I think &ndash; be handled by the DNS plugin indeed.

The [`dns.query.tcp()`](https://dnspython.readthedocs.io/en/stable/query.html#dns.query.tcp) has a default timeout of **forever**. I've made a PR to add a timeout to the plugin.
