### ISSUE TITLE
Certbot does not redirect my VPS IP Address

### ISSUE THREAD

**Issue by sasatefa2009** [certbot/certbot#7086]
### My operating system is (include version):
Ubuntu 18.04
----------------------------------

The issue is that I found that certbot does not redirect my VPS-IP-Address whether in http or https.

This is the new lines added by Certbot for redirection
```
server {
    if ($host = www.example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot



  listen 80;
  listen [::]:80;
  server_name example.com www.example.com xxx.xxx.xxx.xxx;
    return 404; # managed by Certbot

     }
``` 
_example.com is my domain name and xxx.xxx.xxx.xxx is my VPS-IP-Address._

<br>

Certbot uses the above config to do this
1. Redirect http (www and non-www) domain name to https
2. Block access to VPS-IP-Address **only in http** with return 404 
-----------------------------
The problem here is that my website is still accessible through https://VPS-IP-Address

This is how I fixed it
1. Deleted My VPS-IP-Address and added a new redirection and this is the final config
```
server {
    if ($host = www.example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

  listen 80;
  listen [::]:80;
  server_name example.com www.example.com;
    return 404; # managed by Certbot

             }

server {
  listen 80;
  listen [::]:80;
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name xxx.xxx.xxx.xxx;
  return 301 https://example.com$request_uri;
}
```
_example.com is my domain name and xxx.xxx.xxx.xxx is my VPS-IP-Address._

now anyone visits http://VPS-IP-Address/ _or_ https://VPS-IP-Address/ will be redirected to my domain with https.

**Comment by ohemorange** [comment]
Due to a series of things inherent in how Nginx and certificates work and also in how Certbot automates updating configuration files, this sort of edge case is unlikely to ever be automated by Certbot. Thank you for providing an example of how to manually change around a config file!
