### ISSUE TITLE
System requirements/overhead for snapd

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7087]
The questions I have that I'd like exact answers for are:

1. What architectures does `snapd` support?
2. What are the CPU and memory requirements/overhead of running the `snapd` daemon?
3. What are the CPU and memory requirements/overhead of running `snap` which is needed to install packages?
4. What is the disk space required for `snapd`?
5. What is the disk space required for the "core snap" that the [Certbot snap](https://snapcraft.io/certbot) depends on? (Alternatively, we could answer what is disk space taken of installing the Certbot snap on a new machine without snapd previously installed.)

**Comment by adferrand** [comment]
About 1)

Launchpad offers builders to build a snap on various architectures. This gives a comprehensive list of supported architectures: amd64, arm64, armel, armhf, i386, powerpc ppc64el, s390x

See:
* https://launchpad.net/builders
* https://kyrofa.com/posts/building-your-snap-on-device-there-s-a-better-way

In term of OS, snap is supported on Linux only. All major distributions are supported.

See:
* https://docs.snapcraft.io/installing-snapd

**Comment by adferrand** [comment]
About 2)

A very exhaustive study has been carried out by snap dev team. Results shows that running an application through snap is impacting only the startup time, typically ~300ms on each execution of a software, but has a negligeable impact on the runtime compared to other variables (hardware, version of the software ...)

See:
* https://snapcraft.io/blog/i-have-a-need-a-need-for-snap

Also from observations on my machine, I saw that the `snapd` process, idle and on high uptime, add 25Mo of RAM reserved, and usually 0% of the CPU occupied, with a spike at 0.3% each minute.

**Comment by adferrand** [comment]
About 3)

On a server with decent connection, 2VCPUs, it took ~2s to download  the certbot and core snaps and install them.

**Comment by adferrand** [comment]
About 4)

From a new and standard system as configured by Digital Ocean.

On Fedora 30, snapd packages (and its dependencies) represents a total of 151MB to download
On Debian 9, snapd installation (and its dependencies) takes 33MB on the disk.

**Comment by adferrand** [comment]
About 5)

Snaps filesystems are located in `/snap` once uncompressed. Core takes 253 MB. Certbot takes 77 MB. Note that snap seems to have a snapshot mechanism, so old versions of a snap can be stored also in `/snap`.

**Comment by adferrand** [comment]
All questions asserted.

**Comment by bmw** [comment]
> 

> About 1)
> 
> Launchpad offers builders to build a snap on various architectures. This gives a comprehensive list of supported architectures: amd64, arm64, armel, armhf, i386, powerpc ppc64el, s390x
> 
> See:
> 
> * https://launchpad.net/builders
> * https://kyrofa.com/posts/building-your-snap-on-device-there-s-a-better-way

I pulled cpu stats from PyPI and got https://gist.github.com/bmw/c36e9bf6171f0b953e116dd4dc2c9558. For the architectures with any significant amount of users, it looks like armv6l won't be able to use snaps, but I think this is OK and they can use our more manual instructions for people not using snaps.

**Comment by bmw** [comment]
> About 2)
> 
> A very exhaustive study has been carried out by snap dev team. Results shows that running an application through snap is impacting only the startup time, typically ~300ms on each execution of a software, but has a negligeable impact on the runtime compared to other variables (hardware, version of the software ...)
> 
> See:
> 
> * https://snapcraft.io/blog/i-have-a-need-a-need-for-snap

I played with this a little on the smallest sized CentOS 7 droplet DO offers and saw some unpleasant results.

The first time I ran `certbot --version` with the Certbot snap, it took 1 minute and 45 seconds. Subsequent `certbot --version` runs took ~2.25 seconds. Another strange thing I saw is the first run after restarting the system took ~16 seconds.

In contrast, running `certbot --version` from the EPEL package took ~.5 seconds.

When running non-interactively, I don't think this matters much, but when you interactively run Certbot, I worry that the snap makes it feel pretty slow...

**Comment by basak** [comment]
> Snaps filesystems are located in `/snap` once uncompressed. Core takes 253 MB. Certbot takes 77 MB.

Note that they're only mounted in /snap and decompressed on the fly. AIUI they therefore don't need more disk space than their compressed versions that appear in `/var/lib/snapd/snaps/`

**Comment by adferrand** [comment]
> I played with this a little on the smallest sized CentOS 7 droplet DO offers and saw some unpleasant results.
> 
> The first time I ran certbot --version with the Certbot snap, it took 1 minute and 45 seconds. Subsequent certbot --version runs took ~2.25 seconds. Another strange thing I saw is the first run after restarting the system took ~16 seconds.
> 
> In contrast, running certbot --version from the EPEL package took ~.5 seconds.
> 
> When running non-interactively, I don't think this matters much, but when you interactively run Certbot, I worry that the snap makes it feel pretty slow...
> 
> EDIT: I did the same tests on Debian 9 and the times there were ~35 seconds after reboot and ~1.75 seconds after that.

Here are new results for Ubuntu. I took the smallest DigitalOcean droplet on Ubuntu 18.04. Snap is preinstalled. Using `snap install certbot --edge --classic` to install certbot.

Results:
* first execution ever, just after installation: ~3.2 seconds
* subsequent executions without restart: ~1.8 seconds
* first execution after restart: ~3.5 seconds

**Comment by adferrand** [comment]
New test on CentOS7, using smallest droplet, following official instructions to install snap, and installing certbot using `snap install certbot --edge --classic`.

Results
* first execution ever, just after installation: ~3.2 seconds
* subsequent executions without restart: ~2.4 seconds
* first execution after restart: ~3.4 seconds

**Comment by adferrand** [comment]
New test on Debian 10, using smallest droplet, following official instructions to install snap, and installing certbot using `snap install certbot --edge --classic`.

Results for `certbot --version`:
* first execution ever, just after installation: ~2.8 seconds
* subsequent executions without restart: ~1.7 seconds
* first execution after restart: 35 seconds - 1minute

Here again I notice a very slow startup of the certbot snap after restart.

**Comment by adferrand** [comment]
I continue investigating this morning. I cannot find a pattern about the slow startup of snap after a machine reboot. Today for instance with ubuntu 18.04 I saw a 25 seconds startup after reboot, then a 5 seconds startup after reboot. And a 2 seconds startup on ubuntu 19.04.

The issue here may be unrelated to snap itself, and more of some I/O issue specific to DigitalOcean droplets.

**Comment by adferrand** [comment]
> I continue investigating this morning. I cannot find a pattern about the slow startup of snap after a machine reboot. Today for instance with Ubuntu 18.04 I saw a 25 seconds startup after reboot, then a 5 seconds startup after reboot. And a 2 seconds startup on ubuntu 19.04. Then, on a new Ubuntu 19.04 droplet, again a slow startup.
> 
> The issue here may be unrelated to snap itself, and more of some I/O issue specific to DigitalOcean droplets.

To continue in that direction. I tested locally the snap, using a VirtualBox machine on my computer with similar specs than the smallest sized DO droplet: 1VCPU, 1GB RAM. Tested on Ubuntu 19.04.

I could not reproduce the slow startup upon reboot, and obtained the same startup time after reboot than for the first run of the snap: ~2 seconds

**Comment by bmw** [comment]
> The issue here may be unrelated to snap itself, and more of some I/O issue specific to DigitalOcean droplets.

This is quite possible. It's a little disappointing because we won't be the only ones running Certbot on DO, but I think it's probably worth to continue to do a little testing on other platforms such as VirtualBox or AWS.

Some other things I'm personally curious about are:

1. Assuming others are getting the ~0.5 second `certbot --version` outside of a snap, why is the Certbot snap so much slower than what is advertised on https://snapcraft.io/blog/i-have-a-need-a-need-for-snap?
2. Is the performance issue just increased startup time or is the entire execution slowed down? I expect it to just be the former, but I think it's worth verifying/testing.

**Comment by adferrand** [comment]
New results, on AWS, using a `t2.nano` instance. Snap is installed using official documentation, certbot snap is installed using `snap --classic --edge certbot`. Here are the startup time to execute `certbot --version`.

* Ubuntu 18.04

- first execution ever: ~2.1 seconds
- subsequent executions: ~1.3 seconds
- first execution after reboot: ~2.2 seconds

* CentOS 7

- first execution ever: ~1.8 seconds
- subsequent executions: ~1.1 seconds
- first execution after reboot: ~2.1 seconds

* Debian 9

- first execution ever: ~2.2 seconds
- subsequent executions: ~1.1 seconds
- first execution after reboot: ~2.2 seconds

**Comment by bmw** [comment]
Oh wow! While that performance hit does seem worse than 300ms, it's significantly better than the times on DO.

**Comment by adferrand** [comment]
> Oh wow! While that performance hit does seem worse than 300ms, it's significantly better than the times on DO.

About the 300ms, in fact, it matches the expectation: from a certbot instance installed using `tools/venv.py`, on the `t2.nano` AWS instance on Debian 9:

-> first execution ever: ~ 1.1 seconds
-> subsequent executions: ~0.9 seconds
-> first execution after reboot: ~2.0 seconds

**Comment by bmw** [comment]
Interesting. Those times are double or quadruple what I saw testing on DO.

Any hypothesis of what the first execution after reboot is so slow outside of the snap?

**Comment by adferrand** [comment]
No I do not know. I can suppose that after a reboot, the system needs some time to stabilize, in particular in finishing all the startup job. However, I waited a little, and checked that the load average was low. Maybe a lack of entropy in the cryptographic operations ?

**Comment by adferrand** [comment]
Runtime test, to compare the execution time of certbot on snap (out of the startup time).

Tested on a standard DigitalOcean VM (2vCPU, 4GB). Using certbot 0.35.1. Goal is to check a standard certificate issuance against a Pebble instance running locally. Protocol:
* install assets (including certbot-auto, snap, tools/venv.py)
* run `run_acme_server`
* invoke `time certbot_test certonly --standalone -d example.com`

Done with the certbot binary installed by `tools/venv.py`, and as a snap.

Results:
* snap
```
real    0m5.906s
user    0m3.035s
sys     0m0.301s
```

* tools/venv.py
```
real    0m5.091s
user    0m2.254s
sys     0m0.235s
```

**Comment by adferrand** [comment]
I give up the test on Docker for Windows, since snaps are not installable/runnable easily in a Docker.

**Comment by bmw** [comment]
Thanks Adrien.

I was able to reproduce the slow run of Certbot on startup in EC2.

I think there's a good chance you're right about it being due to lack of entropy too. I recently upgraded (rather than reinstalled) the VPS I use for testing from Ubuntu 16.04 and Ubuntu 18.04 and Certbot occasionally hangs for me now. When it does so and I kill the process, it's was in cryptography waiting on entropy.

Your tests with standalone are interesting. .9 seconds isn't that bad, but it is a little more than the times you were seeing in other tests and it's 3 times the 300ms suggested by Ubuntus blogpost. I'd be interested in seeing the times for creating multiple certificates and then running `certbot renew --force-renewal`. 

I think not testing on Docker on Windows is fine.

**Comment by adferrand** [comment]
@bmw here are the results for `certbot renew`.

Protocol: standard DO instance (2vCPUs, 4Go). Certbot run as a snap, and from a venv created using `tools/venv.py`. Certbot launched using `run_acme_server` and `certbot_test` from Certbot-CI to validate the certificates against a local instance of Pebble. Debug and verbose mode are off. Tests are executed 4 time for each number of certificates to renew. Execution time are expressed in seconds.

Raw data:

Nb certs | Snap | Venv
-- | -- | --
1 | 7,1 | 4,3
1 | 5,2 | 4,1
1 | 5,5 | 6,3
1 | 5,7 | 4,2
2 | 8,3 | 6,8
2 | 9,5 | 7,1
2 | 9,5 | 5,6
2 | 6,5 | 6,8
3 | 10,6 | 9,5
3 | 12,4 | 9,4
3 | 10,4 | 9,5
3 | 8,9 | 9,3
5 | 12,8 | 15,4
5 | 12,7 | 13,6
5 | 14,7 | 12,5
5 | 13 | 13,7
10 | 22,3 | 25,4
10 | 23,8 | 29,8
10 | 20,9 | 25,3
10 | 28,3 | 21,2
20 | 39,5 | 42,3
20 | 42,6 | 42,1
20 | 47,7 | 41,7
20 | 44,4 | 38,6

![image](https://user-images.githubusercontent.com/9728851/64457351-ae831500-d0f2-11e9-9de8-6d623c62fd77.png)

As one can see, running certbot as a snap has a negligeable effect on renewal times, and there is no divergence between certbot as a snap or installed directly.

**Comment by bmw** [comment]
Nice! Thanks for looking into that.

I'm closing this issue as resolved.
