### ISSUE TITLE
How would plugins work in a Certbot snap?

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7088]
If Certbot was distributed as a snap, how would plugins work?

@basak said he'd get us some more info here, but some things for us to look into/consider are:

### External virtual environment

We could create a virtual environment outside of the Certbot snap installation which Certbot could then pick up and use. Some questions that come to mind for me if we went this route are:

1. How would dependencies that are already included in Certbot core be handled? For instance, every plugin currently has to depend on Certbot. Would a 2nd copy be installed in the venv? What about the Python version in the snap and upgrades to it?
2. Would paths to things like shared libraries work when the venv is loaded from the snap?
3. What would we do with our own optionally installed plugins?

### Add interface to snapd

This is something that Robie suggested. The way this would work is we'd add interfaces to `snapd` itself and users would need an updated version of the snap software to use the Certbot snap. In addition to just needing to know more about how snap interfaces work, my questions are:

1. Can whatever Certbot/plugin code that uses these interfaces be used outside of the snap system or is it snap specific?
2. How up-to-date are the various packaged versions of `snapd`? In particular I'd be curious about Debian, EPEL 7, RHEL/EPEL 8, OpenSuSe, and older versions of Ubuntu?
3. Would plugins also need classic [confinement](https://docs.snapcraft.io/snap-confinement) or could they use Certbot's? If the latter, are the snap maintainers OK with 3rd party plugins inheriting Certbot's classic confinement?

### Content snaps

This is something else that Robie suggested. In addition to just needing to know more about how these work, my main questions are:

1. Can whatever Certbot/plugin code that uses these interfaces be used outside of the snap system or is it snap specific?
2. Would plugins also need classic [confinement](https://docs.snapcraft.io/snap-confinement) or could they use Certbot's? If the latter, are the snap maintainers OK with 3rd party plugins inheriting Certbot's classic confinement?

### We change how Certbot plugins work

#6613

**Comment by ohemorange** [comment]
Design doc: https://docs.google.com/document/d/1OB5WCDz2mBMgRvtnvo4FSjWHPBDlt1NpccJ5sNrhWIw/edit

**Comment by ohemorange** [comment]
@basak reports initial optimistic results -- `certbot plugins` sees the plugin from a different snap, and `certbot plugins --prepare` seems to be happy. He plans to consult with some snap experts to lose some of the hardcoding, and will hopefully have something to demo soon.

**Comment by bmw** [comment]
We need to design and implement a way to make the dangers of connecting a plugin to the Certbot snap more clear as described at https://forum.snapcraft.io/t/certbot-request-for-classic-snap-approval/6240/19, but the [design for Certbot snap plugins in general](https://github.com/basak/certbot-snap-build/tree/snap-plugins/doc) LGTM and has been approved by the snap team as long as we make things a little more explicit.

**Comment by bmw** [comment]
I'm closing this issue in favor of some minor, more specific issues like https://github.com/certbot/certbot/issues/7667 and https://github.com/basak/certbot-snap-build/issues/19.
