### ISSUE TITLE
Update SSL session cache size to match Mozilla recommendations

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7089]
This is a followup from the research issue at #6903.

Ideally, https://github.com/mozilla/server-side-tls/issues/198 is resolved and Mozilla updates their recommendations. If not, I think we should update our value in https://github.com/certbot/certbot/blob/master/certbot-nginx/certbot_nginx/options-ssl-nginx.conf.

Exactly what these values should be is up for discussion, however, nginx's default timeout of 5 minutes seems like a reasonable place to start to me. I don't know of the top of my head how I think the cache should be configured.

**Comment by bmw** [comment]
For what it's worth, I looked into why our current cache size deviates from Mozilla's recommendations. Our current value comes from the initial PR that added the Nginx plugin which was https://github.com/certbot/certbot/pull/351. Mozilla has had its current recommendation from before that though: https://github.com/mozilla/server-side-tls/commit/b201a1191ba38e6f933cd02a4f425f683ffa9be4#diff-368131f28b06d0d830e9140e471682f9R43

I can't find any explanation to why we chose this value, however, we used to use [Ivan Ristić's Bulletproof SSL and TLS for ciphersuite recommendations in the nginx plugin](https://github.com/certbot/certbot/pull/351/files#diff-e1efd816f9338b4bd93f7f0ff456c7bdR7) and that book recommends our current `ssl_session_*` values so I think that's a safe bet.

**Comment by sydneyli** [comment]
Ivan commented on that thread up there!
> These days I'd probably reduce the maximum session duration to 4 hours, down from 24 hours currently in my book. But that's largely based on a gut feeling that 4 hours is enough for you to reap the performance benefits, and using a shorter lifetime is always better. But, as I said, the only correct approach is to understand your exposure, measure and tune.

**Comment by bmw** [comment]
To update this issue with my understanding of the current state, @sydneyli talked to jsha about this who suggested we keep the 24 hour value which is fine with me.

Do we want to update the cache size to 50MB to match Mozilla? Unless we have a reason not to, I think we should just to not unnecessarily deviate from their recommendations and then I think we can close this PR.

What do you think @sydneyli?

**Comment by sydneyli** [comment]
Yes, that's broadly the consensus. The primary concerns are related to trackability of user clients across different sessions, but jsha brought up the point that it's not relevant for the Certbot plugins since neither apache nor nginx log session IDs.

SGTM. Opened #7163. Thanks for following up on this issue, @bmw!

**Comment by sydneyli** [comment]
As per [this comment](https://github.com/certbot/certbot/pull/7163#issuecomment-503339548), waiting on upstream recommendations to change to a smaller cache size.
