### ISSUE TITLE
certbot enhance --must-staple does not work

### ISSUE THREAD

**Issue by XanC** [certbot/certbot#7094]
I’ve been successfully using Let’s Encrypt on a particular domain for quite some time. I’ve chosen it to experiment with Must-Staple. So I issued the command:
$ certbot enhance --must-staple

certbot configured Apache to start stapling. But it didn’t create a new certificate. hmm. So I forced a renewal of the certificate. It renewed, no problem. But the renewed certificate does not have Must-Staple enabled.

Is something broken or am I doing something wrong?

I posted this earlier to the Let's Encrypt forum ( https://community.letsencrypt.org/t/certbot-enhance-must-staple/94107 ).

**Comment by ohemorange** [comment]
Hello! Looks like this was answered fully at the community forum, so I'm closing this issue.

**Comment by XanC** [comment]
It certainly was not answered fully, or even at all, really.  I believe the behavior of "certbot enhance --must-staple" is badly broken.  Quoting from my last post over there:

I stand by my assertion that the “–must-staple” enhancement is broken:
  * “enhance” is intended for security, which failing to enable Must Staple is not achieving.
  * the enhancement is named “must-staple”, which is not what it seems to actually do.

**Comment by ohemorange** [comment]
Thank you for your feedback, it has been noted!

**Comment by XanC** [comment]
Since this bug is still closed, am I to understand that the current behavior is the correct behavior?

**Comment by ohemorange** [comment]
Your feedback has been valuable for our overarching usability improvement project, where we're trying to make Certbot as understandable as possible for most users and will be taken into account when we're looking at this section of the codebase and help output.
