### ISSUE TITLE
Can't find 0.34.x and 0.35.x on DockerHub

### ISSUE THREAD

**Issue by guessi** [certbot/certbot#7100]
## My operating system is (include version):
- N/A

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
- N/A

## I ran this command and it produced this output:
- N/A

## Certbot's behavior differed from what I expected because:
- `0.34.0` should be available on https://hub.docker.com/r/certbot/certbot/tags
- `0.34.1` should be available on https://hub.docker.com/r/certbot/certbot/tags
- `0.34.2` should be available on https://hub.docker.com/r/certbot/certbot/tags
- `0.35.0` should be available on https://hub.docker.com/r/certbot/certbot/tags
- `0.35.1` should be available on https://hub.docker.com/r/certbot/certbot/tags

## Here is a Certbot log showing the issue (if available):
- N/A

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
- N/A

**Comment by joohoi** [comment]
Thanks for opening the issue. We got recently bitten by changes to how DockerHub integrates to GitHub for automated builds. We're in the process of getting this fixed, the changes are tracked in issue #6630

I'll leave this open for now so others who have stumbled upon this can find the answer quickly.

**Comment by guessi** [comment]
I found that it have been fixed and released with [v1.36.0](https://github.com/certbot/certbot/issues/6630#issuecomment-514835330)
I'm wondering if there is any plan to re-upload for the missing tags?
- `0.34.0`
- `0.34.1`
- `0.34.2`

**Comment by joohoi** [comment]
Hi, the DockerHub builds are indeed back online for the current version and for the future. We're not currently planning to build the missing tags. If you however need some of the missing versions, it's quite simple to build them yourself using [the provided tooling](https://github.com/certbot-docker/certbot-docker/blob/master/build.sh).

**Comment by guessi** [comment]
Just wondering if they will re-publish again.

I've tested [v1.36.0](https://github.com/certbot/certbot/issues/6630#issuecomment-514835330), work perfectly :)
