### ISSUE TITLE
Cant install on RHEL 7

### ISSUE THREAD

**Issue by joehoeller** [certbot/certbot#7104]
```
**sudo yum install certbot**
Loaded plugins: enabled_repos_upload, package_upload, product-id, search-disabled-repos, subscription-manager
rhel-7-server-extras-rpms                                                                            | 2.0 kB  00:00:00

rhel-7-server-optional-rpms                                                                          | 2.0 kB  00:00:00

rhel-7-server-rpms                                                                                   | 2.0 kB  00:00:00

No package certbot available.
Error: Nothing to do
```

**Comment by sydneyli** [comment]
Did you enable the EPEL repository? The instructions to follow are [here](https://certbot.eff.org/lets-encrypt/centosrhel7-other).

If you're still having trouble afterwards, you'll have better luck asking this question on the [Let's Encrypt Community Forums](https://community.letsencrypt.org/c/help), where there's a larger audience of people familiar with the project. You'll get faster help there, too!

**Comment by joehoeller** [comment]
Yes you idiot, I DID FOLLOW THOSE INSTRUCTIONS. You went ahead and made a
false assumption and closed it because you suck.

**Comment by sydneyli** [comment]
Hi! We don't respond well to name-calling-- we're a limited number of humans working on a large software project and other things, and have process to make that load less.

Sorry for being unclear! I closed the issue not because I assumed it was resolved, but because this sort of question is best answered on the community forums.

There's also a note about using RHEL on EC2 in those instructions-- does that pertain to you?

**Comment by joehoeller** [comment]
No, it seems to not work on an internal domain like, my-private.ip.xyz.

**Comment by sydneyli** [comment]
I'm not sure that would affect your installation difficulties. Not to sound like a broken record here, but for installation help, you really will get better and faster aid on the [community forums](https://community.letsencrypt.org/c/help)-- there have been lots of similar issues that were resolved there as well!

We don't necessarily recommend it, but you can still use Certbot on internal servers if the domain itself is publicly resolvable and you control the DNS records for that domain. But it's more complicated, and involves using the DNS challenge (ideally w/ an automated [DNS plugin](https://certbot.eff.org/docs/using.html#dns-plugins)) for Let's Encrypt to validate you have ownership of the certificate domain.

**Comment by sydneyli** [comment]
We removed an earlier comment that was not productive and in violation of our [Code of Conduct](https://www.eff.org/pages/eppcode).
