### ISSUE TITLE
Add dependency on docker-compose to certbot-ci

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7110]
It's written in Python and it not being installed regularly bites me. I often install it in my venv so I have a newer version available than that provided by the OS without making global changes to my system, but when I recreate the venv, I often forget.

I'm not sure what other devs setups look like, but making this change would make mine easier.

What do you think @adferrand?

**Comment by adferrand** [comment]
This is a good idea. It is a python project, we should definitively take advantage of it to make the dev environment more portable.

So it is implemented here: https://github.com/certbot/certbot/pull/7120
