### ISSUE TITLE
`--eab-hmac-key` cannot start with `-`

### ISSUE THREAD

**Issue by oskarwiksten** [certbot/certbot#7114]
## My operating system is (include version): 
openSUSE Leap 15.0

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
package manager: `zypper install certbot`
```
# certbot --version
certbot 0.30.2
```

## I ran this command and it produced this output:
```
certbot certonly \
    --non-interactive --no-verify-ssl \
    --standalone --http-01-port 3380 \
    --agree-tos \
    --config-dir=config/ --work-dir=work/ --logs-dir=logs/ \
    -m test@localhost \
    --domain certbot.integration.test \
    --server https://127.0.0.1:8443/pgwy/acme/directory \
    --eab-kid certbot-account-prereg-keyid-310358708 \
    --eab-hmac-key -G7br10aPrU-iTbGgx7HVYXwp3t4owtQXNd39oUt3bw
```

Output:
```
usage:
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate.
certbot: error: argument --eab-hmac-key: expected one argument
```

## Certbot's behavior differed from what I expected because:
* The `eab-hmac-key` contains 32 bytes of data that is randomly generated, encoded using base64 url-safe encoding.
* It happened to start with a leading `-`. 
* If the b64-encoding does not start with `-`, everything works as expected.

## Here is a Certbot log showing the issue (if available):
See issued command above.

**Comment by alexzorin** [comment]
Seems like it comes down to this argparse bug: https://bugs.python.org/issue9334

**Comment by oskarwiksten** [comment]
As noted in the above linked argparse bug, specifying the parameter like this works:
`--eab-hmac-key=-G7br10aPrU-iTbGgx7HVYXwp3t4owtQXNd39oUt3bw`

**Comment by alexzorin** [comment]
The workaround doesn't seem to be universal. It worked for me in Leap 15.1, but not in Ubuntu Xenial:

Certbot:

    root@4287da3ce53a:/# certbot --version
    certbot 0.31.0

Execution:

    root@4287da3ce53a:/# certbot certonly \
    >     --non-interactive --no-verify-ssl \
    >     --standalone --http-01-port 3380 \
    >     --agree-tos \
    >     --config-dir=config/ --work-dir=work/ --logs-dir=logs/ \
    >     -m test@localhost \
    >     --domain certbot.integration.test \
    >     --server https://127.0.0.1:8443/pgwy/acme/directory \
    >     --eab-kid certbot-account-prereg-keyid-310358708 \
    >     --eab-hmac-key=-G7br10aPrU-iTbGgx7HVYXwp3t4owtQXNd39oUt3bw
    usage:
      certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

    Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
    it will attempt to use a webserver both for obtaining and installing the
    certificate.
    certbot: error: argument --eab-hmac-key: expected one argument

Argparse:

    root@4287da3ce53a:/# dpkg-query -l python3-configargparse
    Desired=Unknown/Install/Remove/Purge/Hold
    | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
    |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
    ||/ Name                 Version         Architecture    Description
    +++-====================-===============-===============-=============================================
    ii  python3-configargpar 0.11.0-1+certbo all             replacement for argparse with config files an
    root@4287da3ce53a:/#

**Comment by adferrand** [comment]
Indeed, this is a problem. And we cannot fix on our side, since the bug is in argparse, and we will have a inconsistent behavior here, because it depends on the actual version of argparse installed along certbot.

Maybe we could accept two representations of the hmac key to pass to the flag, like `--eab-hmac-key=-G7br10aPrU-iTbGgx7HVYXwp3t4owtQXNd39oUt3bw` and `--eab-hmac-key=base64:-G7br10aPrU-iTbGgx7HVYXwp3t4owtQXNd39oUt3bw`, to avoid the leading dash in the HMAC base64 value ?

cc @bmw

**Comment by bmw** [comment]
It's strange. On Ubuntu Xenial, both [this code snippet](https://bugs.python.org/issue9334#msg128025) works but `certbot --eab-hmac-key=-G7br10aPrU-iTbGgx7HVYXwp3t4owtQXNd39oUt3bw` does not. Any idea why?

Also, do we know what versions of Python are affected?

Depending on the answers to those questions, I'm initially a little tempted to try and work around the problem in the code ourselves. It wouldn't be pretty, but we can do whatever we want to `sys.argv` before we give it to `argparse`.

**Comment by adi658** [comment]
Hello.. Any clue where the account key is stored after the account registration happens? Can I know the path to the account key?

**Comment by schoen** [comment]
@adi658, you can find that information in `/etc/letsencrypt/accounts` (I'm not sure that question is related to the subject matter of this issue, so please open a separate issue in the future when asking unrelated questions).

**Comment by alexzorin** [comment]
>Also, do we know what versions of Python are affected?

It turns out the issue is not in `argparse`, but `ConfigArgParse`. I've bisected the issue to `ConfigArgParse>=0.11.0`, which means it affects Ubuntu Xenial, CentOS 7, etc.

The workaround succeeds in openSUSE Leap because its Certbot package comes with `ConfigArgParse==0.10.0`.

**Comment by bmw** [comment]
Aha! That also explains why I was unable to reproduce the problem after using `=` with argparse above.

Thanks for doing that digging @alexzorin. That is very helpful.

Unfortunately, configargparse is largely unmaintained nowadays (see https://github.com/bw2/ConfigArgParse/issues/133), but I created https://github.com/bw2/ConfigArgParse/issues/154 to track the issue there regardless.

**Comment by bmw** [comment]
I probably won't be able to get to it myself anytime soon, but the maintainer of configargparse expressed an interest for a patch to fix this at https://github.com/bw2/ConfigArgParse/issues/154#issuecomment-539533263.

**Comment by bmw** [comment]
This has been fixed in `configargparse` 0.15.2. Unfortunately, most LTS distros won't see the update so their Certbot packages will be affected until the distro releases a new LTS version that contains the fix.

I think when we've dropped support for Python 3.4 though, we should upgrade configargparse used in certbot-auto and close this issue.

**Comment by bmw** [comment]
I'm closing this in favor of https://github.com/certbot/certbot/issues/7358 which is tracking making the change I described above in both configargparse and other dependencies.

**Comment by Apollo3zehn** [comment]
For me it only works with a single backslash (`--eab-kid=\-xyz...`) but I am using the fish shell, which might be the reason.
