### ISSUE TITLE
Add missing error types and descriptions from RFC 8555 to acme

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7116]
https://github.com/certbot/certbot/blob/b0d960f102c998d8231c0ee48952b488f10864ac/acme/acme/messages.py#L20-L36 defines a number of ACME error types and their descriptions, however, that list is not up to date. We should add the missing error types from https://tools.ietf.org/html/rfc8555#section-6.7 to this `dict`.

**Comment by ddrobner** [comment]
I made a pull request for this. Feel free to suggest any changes that you see fit.

**Comment by bmw** [comment]
Fixed in #7131.
