### ISSUE TITLE
Failed to apply for a certificate

### ISSUE THREAD

**Issue by hughcube** [certbot/certbot#7123]
If I apply for multiple domain name certificates, such as example.com and *.example.com, the DNS authentication method, the record value of _acme-challenge.example.com will be added twice different values, resulting in authentication failure. Excuse me. How should I solve the problem?

Parameters -d *.example.com -d example.com

**Comment by alexzorin** [comment]
If you apply for a certificate for `example.com` and `*.example.com`, then the correct procedure is to ensure that two `_acme-challenge.example.com` TXT records are created - one for each respective challenge.

As long as the ACME server can find each respective value among the TXT records that are present, the challenge will succeed. 

If you need further help, please post a thread on https://community.letsencrypt.org/ .

**Comment by hughcube** [comment]
我在设置cdn解析前会删除所有的记录,   非常感谢

**Comment by bmw** [comment]
You'll get better help using Certbot by posting questions to the community forum at https://community.letsencrypt.org. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

For this reason, I'm closing this issue.
