### ISSUE TITLE
certbot-auto and cPanel httpdconf

### ISSUE THREAD

**Issue by CanadianJeff** [certbot/certbot#7125]
I use cPanel/WHM and ran certbot. All my certs installed and are working
I confirmed with ```sudo apachectl -S``` 

certbot-auto put ```Include conf/httpd-le-ssl.conf``` in ```conf/httpd.conf``` however if on a cPanel server you run ```/scripts/rebuildhttpdconf``` the Include gets wiped out causing hours of frustration they suggest you put your Include statements in ```conf.d/includes/pre_main_global.conf``` so I did this on my server and it works perfectly

My ```pre_main_global.conf``` looks like this
```
# Supplemental configuration
#
# The configuration files in the conf/extra/ directory can be 
# included to add extra features or to modify the default configuration of 
# the server, or you may simply copy their contents here and change as 
# necessary.

# Server-pool management (MPM specific)
#Include conf/extra/httpd-mpm.conf

# Multi-language error messages
#Include conf/extra/httpd-multilang-errordoc.conf

# Fancy directory listings
#Include conf/extra/httpd-autoindex.conf

# Language settings
#Include conf/extra/httpd-languages.conf

# User home directories
#Include conf/extra/httpd-userdir.conf

# Real-time info on requests and configuration
#Include conf/extra/httpd-info.conf

# Virtual hosts
#Include conf/extra/httpd-vhosts.conf

# Local access to the Apache HTTP Server Manual
#Include conf/extra/httpd-manual.conf

# Distributed authoring and versioning (WebDAV)
#Include conf/extra/httpd-dav.conf

# Various default settings
#Include conf/extra/httpd-default.conf

# Secure (SSL/TLS) connections
# Listen for virtual host requests on all IP addresses
#NameVirtualHost *:443

# Go ahead and accept connections for these vhosts
# from non-SNI clients
#SSLStrictSNIVHostCheck off
Include conf/httpd-le-ssl.conf
#Include conf/extra/httpd-ssl.conf
#
# Note: The following must must be present to support
#       starting without SSL on platforms with no /dev/random equivalent
#       but a statically compiled-in mod_ssl.
#
```

**Comment by alexzorin** [comment]
The short story is that you should never use the Certbot Apache plugin (authenticator or installer) on a cPanel server. It is dangerous and does not mesh with cPanel's management of virtual hosts and their certificates.

Also relevant: https://github.com/certbot/certbot/issues/6576

If Certbot were to ever support cPanel as an environment, the "cPanel plugin" should use the appropriate cPanel APIs to perform both authentication and installation.

**Comment by bmw** [comment]
Sorry for the trouble @CanadianJeff. I'll be honest and say that I'm personally not very familiar with CPanel, but if our plugins work that poorly with it, we might want to bump the priority of #6576. I'll make sure we look into it.

In the meantime, you might have better luck with https://documentation.cpanel.net/display/80Docs/Manage+AutoSSL. If you need help using that or trying to configure Certbot's Apache plugin for use on your setup, I recommend posting to https://community.letsencrypt.org. There is a large number of people familiar with the various projects around Let's Encrypt who should be able to help you.
