### ISSUE TITLE
certbot-auto not working with Python3.6 and new setuptools

### ISSUE THREAD

**Issue by pratibhajagnere** [certbot/certbot#7126]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
CentOS6

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
sudo ./certbot-auto

## Certbot's behavior differed from what I expected because:
I dont have Python3.4 installed but I do have Python3.6. running certbot gave error of missing pkg_resources. 

After reverting back to Python3.4 and using older setuptools, it worked fine.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

I renamed /opt/eff.org because earlier certbot-auto ran with Python3.4 which was in my system. Later I upgrade it to Python3.6 which removed Python3.4

$ sudo ./certbot-auto
Bootstrapping dependencies for RedHat-based OSes that will use Python3... (you can skip this with --no-bootstrap)
yum is /usr/bin/yum
yum is hashed (/usr/bin/yum)
Loaded plugins: fastestmirror, presto
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror.eu.oneandone.net
 * centos-sclo-rh: centosmirror.netcup.net
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: mirror.ratiokontakt.de
 * updates: mirror.ratiokontakt.de
Package gcc-4.4.7-23.el6.x86_64 already installed and latest version
Package augeas-libs-1.0.0-10.el6.x86_64 already installed and latest version
Package openssl-1.0.1e-57.el6.x86_64 already installed and latest version
Package openssl-devel-1.0.1e-57.el6.x86_64 already installed and latest version
Package libffi-devel-3.0.5-3.2.el6.x86_64 already installed and latest version
Package redhat-rpm-config-9.0.3-51.el6.centos.noarch already installed and latest version
Package ca-certificates-2018.2.22-65.1.el6.noarch already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package python34.x86_64 0:3.4.10-1.el6 will be installed
--> Processing Dependency: python34-libs(x86-64) = 3.4.10-1.el6 for package: python34-3.4.10-1.el6.x86_64
--> Processing Dependency: libpython3.4m.so.1.0()(64bit) for package: python34-3.4.10-1.el6.x86_64
---> Package python34-devel.x86_64 0:3.4.10-1.el6 will be installed
---> Package python34-tools.x86_64 0:3.4.10-1.el6 will be installed
--> Processing Dependency: python34-tkinter = 3.4.10-1.el6 for package: python34-tools-3.4.10-1.el6.x86_64
--> Running transaction check
---> Package python34-libs.x86_64 0:3.4.10-1.el6 will be installed
---> Package python34-tkinter.x86_64 0:3.4.10-1.el6 will be installed
--> Finished Dependency Resolution

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
NA

**Comment by bmw** [comment]
`certbot-auto` is currently set up to use Python 3.4 on CentOS 6. If you want to handle installing OS dependencies yourself, you can pass the flag `--no-bootstrap`.

I wasn't able to reproduce the issue with Python 3.6 and new setuptools. Installing Python 3.6 from SCL and running `certbot-auto --no-bootstrap` worked for me. Can you provide a log of the problem?

**Comment by pratibhajagnere** [comment]
@bmw Thank you. Using `--no-bootstrap` , I am able to use Python3.6 with certbot-auto.
