### ISSUE TITLE
certbot on nginx + Docker + ubuntu?

### ISSUE THREAD

**Issue by pmury** [certbot/certbot#7128]
I'd like to have certbox-nginx as Docker/Ubuntu flavor (to setup an apt mirror).

What I've found out so far:
- official certbot installation script does not work inside Docker with Ubuntu
  https://devops.stackexchange.com/questions/8326/certbot-installation-fails-inside-docker
- there is a nginx Docker package available out there for certbot but it's for Alpine   
https://hub.docker.com/r/linuxserver/letsencrypt/

Any ideas?

**Comment by sydneyli** [comment]
Hey @pmury, thanks for your interest in the project! I suggest you first ask this question on the [Let's Encrypt Community Forums](https://community.letsencrypt.org/c/help), where there's a larger audience of people familiar with the project. You'll get much faster help there!

I'm closing this issue for now.
