### ISSUE TITLE
Support of TNauthList extension

### ISSUE THREAD

**Issue by grindsa** [certbot/certbot#7134]
Hi,

Are there any plans to include the support for [TNAuthList profile](https://tools.ietf.org/html/draft-ietf-acme-authority-token-tnauthlist-03) into certbot?

BR GrindSA

**Comment by sydneyli** [comment]
Not at the moment, AFAIK. It looks like the IESG hasn't started processing [that draft](https://tools.ietf.org/wg/acme/) yet-- so we might hold off on that for now.

**Comment by sydneyli** [comment]
Going to close this issue for now. You can ask questions like this in the future on the [feature requests category on the Let's Encrypt Community Forums](https://community.letsencrypt.org/c/feature-requests)!
