### ISSUE TITLE
nginx reload is not working

### ISSUE THREAD

**Issue by NTMS2017** [certbot/certbot#7135]
I install nginx using certbot and also I get letsencrypt with this.
I try to modified my nginx and reload but reload is not working.

Process: 17324 ExecReload=/bin/kill -s HUP $MAINPID (code=exited, status=1/FAILURE)

any idea?

**nginx.service - nginx - high performance web server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-06-08 13:51:51 EEST; 18s ago
     Docs: http://nginx.org/en/docs/
  Process: 17957 ExecStop=/bin/kill -s TERM $MAINPID (code=exited, status=0/SUCCESS)
  Process: 17324 ExecReload=/bin/kill -s HUP $MAINPID (code=exited, status=1/FAILURE)
  Process: 17983 ExecStart=/usr/sbin/nginx -c /etc/nginx/nginx.conf (code=exited, status=0/SUCCESS)
 Main PID: 17991 (nginx)
    Tasks: 9 (limit: 19140)
   CGroup: /system.slice/nginx.service
           ├─17991 nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf
           ├─17994 nginx: worker process
           ├─17996 nginx: worker process
           ├─17997 nginx: worker process
           ├─17998 nginx: worker process
           ├─17999 nginx: worker process
           ├─18000 nginx: worker process
           ├─18001 nginx: worker process
           └─18002 nginx: worker process

Haz 08 13:51:51 niyazi-virtual-machine systemd[1]: Starting nginx - high performance web server...
Haz 08 13:51:51 niyazi-virtual-machine systemd[1]: Started nginx - high performance web server.**

**Comment by sydneyli** [comment]
Hey @NTMS2017, thanks for your interest in the project! I suggest you first ask this question on the Let's Encrypt Community Forums, where there's a larger audience of people familiar with the project. You'll get much faster help there!

I'm closing this issue for now. If a problem persists in Certbot, in the future, please open an issue and fill out the issue template to the best of your ability.
