### ISSUE TITLE
where are the openSUSE LEAP 15.1 packages ?

### ISSUE THREAD

**Issue by udf2457** [certbot/certbot#7139]
```
$ sudo zypper install certbot python-certbot-dns-rfc2136 python2-dnspython
Loading repository data...
Reading installed packages...
'python-certbot-dns-rfc2136' not found in package names. Trying capabilities.
'certbot' not found in package names. Trying capabilities.
```

Any chance you guys can push out an openSUSE Leap 15.1 build to the openSUSE repo ? (15.1 was released 22nd May https://news.opensuse.org/2019/05/22/opensuse-community-releases-leap-15-1-version/) 

Thank you !!

**Comment by alexzorin** [comment]
What's your `/usr/lib/os-release` say?

The packages are present: https://software.opensuse.org/package/python2-certbot-dns-rfc2136?search_term=python2-certbot-dns-rfc2136

    9822fa053d41:/ # cat /usr/lib/os-release
    NAME="openSUSE Leap"
    VERSION="15.1 "
    ID="opensuse-leap"
    ID_LIKE="suse opensuse"
    VERSION_ID="15.1"
    PRETTY_NAME="openSUSE Leap 15.1"
    ANSI_COLOR="0;32"
    CPE_NAME="cpe:/o:opensuse:leap:15.1"
    BUG_REPORT_URL="https://bugs.opensuse.org"
    HOME_URL="https://www.opensuse.org/"


    9822fa053d41:/ # zypper info python2-certbot-dns-rfc2136
    Loading repository data...
    Reading installed packages...


    Information for package python2-certbot-dns-rfc2136:
    ----------------------------------------------------
    Repository     : Main Repository
    Name           : python2-certbot-dns-rfc2136
    Version        : 0.30.2-lp151.1.1
    Arch           : noarch
    Vendor         : openSUSE
    Installed Size : 55.6 KiB
    Installed      : No
    Status         : not installed
    Source package : python-certbot-dns-rfc2136-0.30.2-lp151.1.1.src
    Summary        : RFC 2136 DNS Authenticator plugin for Certbot
    Description    :
        RFC 2136 DNS Authenticator plugin for Certbot.

**Comment by sydneyli** [comment]
Thanks for your interest in the project @udf2457! 

As @alexzorin mentioned, it looks like it [should be available](https://software.opensuse.org/package/python2-certbot-dns-rfc2136?search_term=python2-certbot-dns-rfc2136) in LEAP 15.1!

If you're still having trouble, I suggest asking this question on the [Let's Encrypt Community Forums](https://community.letsencrypt.org/c/help), where there's a larger audience of people familiar with the project. You'll get much faster help there!

I'm closing this issue for now. If a problem persists in Certbot, in the future, please open an issue and fill out the issue template to the best of your ability.
