### ISSUE TITLE
Access the certbot/Letsencrypt account/client key

### ISSUE THREAD

**Issue by adi658** [certbot/certbot#7150]
Hello

I want to know where is the account/client key getting stored
1) Want to extract the client key from a working Certbot environment, 
2) the task isn’t to extract the SSL certificates and keys.  Rather it is to extract the ACME client account key used for authentication to the ACME server.  
3) I guess It’s a public/private key pair associated to the ACME client when it first registers with the server.

I see some of it in /etc/letsencrypt/accounts/acme-v02.api.letsencrypt.org/directory/80332f4536b5b08a976dd483c4078ad4
meta.json
private_key.json
regr.json

but the private_key.json has some generated RSA key pair in JWK format
How do i just get the acocunt/client key

Can someone help me with the location

**Comment by alexzorin** [comment]
> but the private_key.json has some generated RSA key pair in JWK format

This is is the ACME account key.

By your question, I assume you are maybe looking for the key in PEM or DER format? If so, you can convert between JWK and PEM encodings.

You would need to write a short program to do this, e.g. https://play.golang.org/p/Vyx1RyPMWx5 (but if you run this, run it locally on your computer with the real private_key.json, not on the playground link).

**Comment by adi658** [comment]
Awesome, thanks for your reply @alexzorin
Also, do you know by anychance that if I use this key in say "cert-manager" by Jetstack.. will that work?

I want the certmanager to work but it needs ExternalAccountBindings which I think is currently not supported by Jetstack Certmanager. So I complains about "account not registered", where as the certbot thing works using the following command

sudo certbot -i apache -d mydomain.com --eab-kid xxxxxxxxxxx --eab-hmac-key xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --server https://myacmeserver.com/xyz
  
 Is there a way i use this account key in certmanager and make the Issuer registration successful

**Comment by adi658** [comment]
> > but the private_key.json has some generated RSA key pair in JWK format
> 
> This is is the ACME account key.
> 
> By your question, I assume you are maybe looking for the key in PEM or DER format? If so, you can convert between JWK and PEM encodings.
> 
> You would need to write a short program to do this, e.g. https://play.golang.org/p/Vyx1RyPMWx5 (but if you run this, run it locally on your computer with the real private_key.json, not on the playground link).

Also i ran the program on my local computer using the link that you provided.. It gives me a Private key. Does it also have a public key by any chance? And is the returned private key -> the certbot/letsencrypt account/client key??

**Comment by sydneyli** [comment]
Thanks for your interest in the project @adi658!

Changing the line in the Go script from `(*rsa.PrivateKey)` to `(*rsa.PublicKey)` that should give you what you want. The package it's using is [here](https://github.com/square/go-jose) and you can check out the API for yourself.

For your other inquiries, I suggest you ask these questions on the [Let's Encrypt Community Forums](https://community.letsencrypt.org/c/help), where there's a larger audience of people familiar with the project. You'll get much faster help there!

I'm closing this issue for now. If a problem persists in Certbot in the future, please open an issue and fill out the issue template to the best of your ability.

**Comment by adi658** [comment]
@sydneyli Just on the same topic

Hello @munnerz 

This may be a silly question but 

How do you make changes to the repository "locally" and test it out?? For example, say I ws trying to check if we can add the EAB for certmanager by referring to Lego repository, 
https://github.com/go-acme/lego/blob/master/acme/api/account.go (Line 30)

But for that how do I proceed? How do I edit the code locally and then create the Docker Image out of it and then use those Docker images? 

Say if I add a couple of functions in the account.go or somewhere else, how do I make my current certmanager setup use those new changes?

**Comment by sydneyli** [comment]
Do you mean making changes to Certbot? We have a [developer guide](https://certbot.eff.org/docs/contributing.html) that will help you get set up. If you're having trouble, getting set up, we have a public [Mattermost instance](https://www.eff.org/about/opportunities/volunteer/coding-with-eff) you can join to ask for help!
