### ISSUE TITLE
Don't send OCSP requests for expired certificates

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7152]
Let's Encrypt doesn't update OCSP for expired certificates. They are not required to do so. When someone runs `certbot certificates` with expired certificates and they're using our Python support for making OCSP requests rather than shelling out to `openssl`, they get output like:
```
Invalid OCSP response for /etc/letsencrypt/live/example.org/cert.pem: param nextUpdate is in the past…
```
There's not actually a problem here so we shouldn't be printing these warnings to users. 

The code that does this is at https://github.com/certbot/certbot/blob/d75908c645e0d13827b60c4c94491e0c41859ad4/certbot/cert_manager.py#L264-L267

Fixing that is simple enough, however, I think [one of our tests is relying on this behavior](https://github.com/certbot/certbot/blob/9a7f774706484dcec10cf5247d31bb547a5e1160/certbot-ci/certbot_integration_tests/certbot_tests/test_main.py#L545) (and if so, the test should be deleted) and we may also want to add code in `certbot.ocsp.ocsp_revoked` to check if the certificate is still valid before querying OCSP to help prevent this problem in the future.

This was reported at https://community.letsencrypt.org/t/invalid-ocsp-response-nextupdate-is-in-the-past/95640.

**Comment by ohemorange** [comment]
> Fixing that is simple enough, however, I think one of our tests is relying on this behavior (and if so, the test should be deleted)

After changing the relevant `if` to an `elif`, `tox -e integration-certbot` and `tox -e integration` both still passed. Am I not running the right thing to hit that test?

**Comment by bmw** [comment]
No I think you did the right thing. Looks like the test isn't relying on the behavior.
