### ISSUE TITLE
Insecure protocols need to be removed from options-ssl-nginx.conf

### ISSUE THREAD

**Issue by dan-willett** [certbot/certbot#7158]
The NGINX config file: certbot/certbot-nginx/certbot_nginx/options-ssl-nginx.conf

contains the following line: 

ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

this needs to be changed to:

ssl_protocols TLSv1.2 TLSv1.3;

The TLSv1 and TLSv1.1 protocols are a major security risk, and the certbot config for NGINX should not be turning the on.

**Comment by SubaruSama** [comment]
Hey, how are you?
I've made a pull request for this subject: https://github.com/certbot/certbot/pull/7159

Thanks!

**Comment by schoen** [comment]
Hi folks,

I think I largely agree with this, but after a lot of investigation in the past, we had decided to try to follow

https://mozilla.github.io/server-side-tls/ssl-config-generator/

which has been taking into account some compatibility vs. security trade-offs. Do you know if Mozilla is in the process of changing its recommended defaults with respect to TLS versions prior to 1.2? Would you be willing to discuss the recommendations with the responsible parties at Mozilla to see if they'll update their published advice?

**Comment by bmw** [comment]
> Do you know if Mozilla is in the process of changing its recommended defaults with respect to TLS versions prior to 1.2?

They are. They haven't quite finished working out the details, but you can see a preview of the changes they're planning on making at https://ssl-config.mozilla.org/.

Once they finalize these changes, we will be updating our nginx configuration to follow the new recommendations.

**Comment by nmxcgeo** [comment]
They have finished it now. It would be nice to update [centos-options-ssl-apache.conf](https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/centos-options-ssl-apache.conf), [options-ssl-apache.conf](https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/options-ssl-apache.conf), [options-ssl-nginx-old.conf](https://github.com/certbot/certbot/blob/master/certbot-nginx/certbot_nginx/options-ssl-nginx-old.conf), [options-ssl-nginx.conf](https://github.com/certbot/certbot/blob/master/certbot-nginx/certbot_nginx/options-ssl-nginx.conf) and possibly other files that follow these recommendations.

**Comment by bmw** [comment]
I agree! I created #7204 and #7205 last week to track specifically what I think needs to be done here. Since resolving those issues will also resolve this, I'm closing this issue in favor of those.
