### ISSUE TITLE
Typo in usage output for deprecated update-registration command

### ISSUE THREAD

**Issue by os-99** [certbot/certbot#7160]
I have just copied a old command from the internet to update my email for certbot and found a typo in the usage output. In the last line you write certbot with out the first "t" and the shell doesn't recognize the command:

root@myserver:~# certbot register --update-registration --email xxxx
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Usage 'certbot register --update-registration' is deprecated.
Please use '**cerbot** update_account [options]' instead.

OS:
Ubuntu 18.04.2 LTS

Version: 
0.31.0-1+ubuntu18.04.1+certbot+1

**Comment by lmeerwood** [comment]
I'm happy to try fix this. Would that be alright, @schoen?

**Comment by lmeerwood** [comment]
Never mind. This issue was fixed in pull request #7118.

**Comment by sydneyli** [comment]
Closing as fixed.
