### ISSUE TITLE
Unpin os x image in Travis

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7168]
In https://github.com/certbot/certbot/pull/7167, I pinned the macOS image to the latest version to workaround https://travis-ci.community/t/xcode-8-3-homebrew-outdated-error/3798. I think there are pros to pinning this image in the long run as it could make the tests more stable, but I don't think it's worth it. We haven't had many problems due to using Travis' default here, I think it's easy to forget to update this pinning, and I think using a non-default value here makes our config more unusual and therefore more likely to hit bugs. I think https://github.com/certbot/certbot/pull/7167 should be reverted when the upstream issue is resolved.

**Comment by bmw** [comment]
As of this morning this still isn't fixed.

**Comment by adferrand** [comment]
Is there some bug tracking to check the work in progress? I do not see a response from the Travis dev in the community forum.

**Comment by bmw** [comment]
I believe BanzaiMan who responded at https://travis-ci.community/t/xcode-8-3-homebrew-outdated-error/3798/2 works for Travis. He's at least a [member of their org on GitHub](https://github.com/travis-ci/travis-ci/issues/6726#issuecomment-425414639).

**Comment by bmw** [comment]
This issue still is not resolved in Travis. I just bumped the thread but moving this to the next milestone for now.

**Comment by bmw** [comment]
This is still broken and I sent an email to Travis support about the problem.

**Comment by bmw** [comment]
This is still broken. See https://travis-ci.com/certbot/certbot/builds/130319416.
