### ISSUE TITLE
How will permissions on Windows work with Apache, nginx, etc.

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7169]
Currently we're creating the files to be only accessible by adminstrators, `SYSTEM`, and the user who ran Certbot. This likely isn't enough for webservers like Apache which I'm told it is suggested to create a new user for. We need to figure out how this is going to work.

@joohoi proposed creating a special group that Windows users can add the user for their server processes to.

**Comment by joohoi** [comment]
The piece of Apache HTTPD documentation I was talking about can be found here:
https://httpd.apache.org/docs/2.4/platform/windows.html#winsvc

**Comment by adferrand** [comment]
Go away stalebot, this issue is still relevant.

**Comment by mikenor** [comment]
No, nobody has "made a lot of changes" to "how permissions on Windows work". This is still relevant to issues such as #8420.
