### ISSUE TITLE
Sending non-empty JSON body on validation check requests

### ISSUE THREAD

**Issue by dopey** [certbot/certbot#7171]
https://community.letsencrypt.org/t/acme-spec-asks-for-empty-json-blob-in-challenge-validation-request/96252/2

The acme spec (https://ietf-wg-acme.github.io/acme/draft-ietf-acme-acme.html#rfc.section.7.5.1) requires that clients send an empty JSON body ({}) for client validation checks. Certbot appears to be sending a non-empty payload 

```
{
  "resource": "challenge",
  "type": "http-01"
}
``` 
which is not in accordance with the acme spec and will illicit malformed request errors from servers that are strictly adhering to the ACME spec.

**Comment by bmw** [comment]
Thanks for the issue @dopey. I agree we should fix this.

Currently it's slightly complicated by the fact we're maintaining our support for "ACMEv1", but we could still do this for "ACMEv2". We'd accept a well written PR for this if you're interested in working on it.

This is related to https://github.com/certbot/certbot/issues/5708.

**Comment by cpu** [comment]
@bmw FWIW As of [Pebble v2.1.0](https://github.com/letsencrypt/pebble/releases/tag/v2.1.0) you can use `pebble -strict` to verify the fix for this issue.

**Comment by adferrand** [comment]
I increase this issue priority, since actually, we are not compliant against Pebble v2.1.0.

**Comment by bmw** [comment]
This was fixed in #7176.
