### ISSUE TITLE
Acme module is not compliant with RFC 8555

### ISSUE THREAD

**Issue by adferrand** [certbot/certbot#7177]
On several areas regarding the JWS tokens, `acme` is not compliant with RFC 8555. As a consequence, Certbot is not working anymore with Pebble v2.1.0+ in strict mode.

In particular, all Travis builds (PR or nightly) cannot succeed until this issue is fixed. See for instance: https://travis-ci.com/certbot/certbot/builds/116546080

You can see here the additional controls added to the compliance check Pebble side, that Certbot does not pass: https://github.com/letsencrypt/pebble/pull/246

I propose two solutions in two PRs for that:
* first one is a simplistic solution that just disable strict mode for now in integration tests: https://github.com/certbot/certbot/pull/7175
* second one is a real solution, that makes `acme` compliant using an approach that may imply discussions: https://github.com/certbot/certbot/pull/7176

**Comment by bmw** [comment]
This was fixed in #7176.
