### ISSUE TITLE
Install doesn't work on Debian 9.8

### ISSUE THREAD

**Issue by rokcarl** [certbot/certbot#7179]
## My operating system is (include version):

    $ cat /etc/debian_version
    9.8

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Using apt-get.

## I ran this command and it produced this output:

    $ sudo apt-get install certbot python-certbot-nginx -t stretch-backports
    ...
    The following packages have unmet dependencies:
     certbot : Depends: python3-certbot (= 0.28.0-1~bpo9+1) but it is not going to be installed
     python-certbot-nginx : Depends: python3-certbot-nginx but it is not going to be installed
    E: Unable to correct problems, you have held broken packages.

## Certbot's behavior differed from what I expected because:

It should now be installed.

I tried everything from #5573:

    $ cat /etc/apt/sources.list | grep stretch
    deb http://deb.debian.org/debian stretch-backports main
    deb-src http://deb.debian.org/debian stretch-backports main contrib non-free
    
    $ sudo apt --fix-broken install
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    The following packages were automatically installed and are no longer required:
      libdate-manip-perl libsys-cpu-perl libsys-meminfo-perl
    Use 'sudo apt autoremove' to remove them.
    0 upgraded, 0 newly installed, 0 to remove and 139 not upgraded.

But the same error still happened.

**Comment by alexzorin** [comment]
One simple (but tedious) way to narrow down which package is causing the conflict is to try to individually install the broken packages. 

Every time you see:

    python-certbot-nginx : Depends: python3-certbot-nginx but it is not going to be installed

Try install the dependency directly:

    apt install python3-certbot-nginx

Which will lead to another broken package ... rinse and repeat until it becomes obvious what is wrong.

**Comment by rokcarl** [comment]
I did do something similar before, I iteratively added packages to my command and then some conflict arose.

But this time I went your way and arrived to this:

    # apt install python3-acme
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    python3-acme is already the newest version (0.22.2-1ubuntu0.1~16.04.1).
    The following packages were automatically installed and are no longer required:
      libdate-manip-perl libsys-cpu-perl libsys-meminfo-perl
    Use 'apt autoremove' to remove them.
    0 upgraded, 0 newly installed, 0 to remove and 139 not upgraded.
    
    # apt install python3-certbot
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:
    
    The following packages have unmet dependencies:
     python3-certbot : Depends: python3-acme (>= 0.26.0~) but 0.22.2-1ubuntu0.1~16.04.1 is to be installed
    E: Unable to correct problems, you have held broken packages.

**Comment by alexzorin** [comment]
> python3-acme is already the newest version (0.22.2-1ubuntu0.1~16.04.1).

That's not right. Is it possible you tried to use an Ubuntu PPA to install Certbot, previously? Maybe leftovers packages from that have created this conflict.

Maybe try remove `python3-acme` first  ... and use `-t stretch-backports` as per the instructions @ https://certbot.eff.org/lets-encrypt/debianstretch-other .

**Comment by rokcarl** [comment]
That was indeed the case, I must have used an Ubuntu PPA, so now not sure how to clean it up. I did remove `python3-acme` and I used `-t stretch-backports` as per my commands at the top. Tried it again, didn't help. `apt-cache show python3-acme` gives me [this](https://gist.github.com/rokcarl/e3fecb50a9e14ee2cc924e54a7f2258c).

**Comment by alexzorin** [comment]
Looks like you still have the PPA installed. You can get rid of it by removing it from `/etc/apt/sources.list.d/` (named something like `certbot-ubuntu-certbot-disco.list`) and then `apt update`.

You might still need to first remove `certbot`, `python3-certbot`, `python3-acme` etc, any packages that came from the PPA. Then installing from stretch-backports should work. I'm not aware of any way to do that quickly.

**Comment by rokcarl** [comment]
I had the old sources in `/etc/apt/sources.list` from some previous configuration. I've commented those out and now it works, thank you!

**Comment by adferrand** [comment]
Thanks a lot guys for the successful handling of this issue! I just add the related tags for archiving purpose.
