### ISSUE TITLE
letsencrypt client and dealing with non-standard Nginx configurations

### ISSUE THREAD

**Issue by centminmod** [certbot/certbot#718]
With the letsencrypt client I see you can pass specific Nginx `--nginx-server-root` and `--nginx-ctl1 parameters but I assume the tool has also made specific assumptions about where nginx vhost files will be located etc and the format they take ? For non-standard Nginx configurations what would I need to do ? Can I tell the letsscrypt client to look for my specific custom Nginx paths and locations ? or would I need to use standalone method and then script it to place the obtained SSL certs and files in my custom locations ?

For instance on my Centmin Mod LEMP stack and example `newdomain2.com`, my nginx SSL configuration is located at `/usr/local/nginx/conf/conf.d/newdomain2.com.ssl.conf` with install for Nginx at `/usr/local/nginx` and SSL certificates end up in directory at `/usr/local/nginx/conf/ssl/newdomain2.com`. Example of [how newdomain2.com Nginx vhost was generated](http://centminmod.com/http-public-key-pinning.html).

Basically, I am looking to integrate letsencrypt into my Nginx vhost creation routine :)

thanks

George

help

```
letsencrypt --help nginx
usage: 
  letsencrypt [SUBCOMMAND] [options] [domains]

The Let's Encrypt agent can obtain and install HTTPS/TLS/SSL certificates.  By
default, it will attempt to use a webserver both for obtaining and installing
the cert.  

positional arguments:
  SUBCOMMAND
    run                 Obtain a certificate and install.
    auth                Authenticate & obtain cert, but do not install it.
    install             Install a previously obtained cert in a server.
    revoke              Revoke a previously obtained certificate.
    rollback            Rollback server configuration changes made during
                        install.
    config_changes      Show changes made to server config during installation
    plugins             List server software plugins.

optional arguments:
  -h, --help            show this help message and exit
  -c CONFIG_FILE, --config CONFIG_FILE
                        config file path (default: None)

nginx:
  Nginx Web Server

  --nginx-server-root NGINX_SERVER_ROOT
                        Nginx server root directory. (default: /etc/nginx)
  --nginx-ctl NGINX_CTL
                        Path to the 'nginx' binary, used for 'configtest' and
                        retrieving nginx version number. (default: nginx)
```

**Comment by centminmod** [comment]
not working or incorrect syntax ? on centos 6.7 with python 2.7

    ./venv/bin/letsencrypt -d le1.http2ssl.xyz auth --nginx --nginx-server-root /usr/local/nginx --nginx-ctl nginx
    usage: 
      letsencrypt [SUBCOMMAND] [options] [domains]
    
    The Let's Encrypt agent can obtain and install HTTPS/TLS/SSL certificates.  By
    default, it will attempt to use a webserver both for obtaining and installing
    the cert.  
    letsencrypt: error: ambiguous option: --nginx could match --nginx-ctl, --nginx-server-root

or

    ./venv/bin/letsencrypt -d le1.http2ssl.xyz auth --nginx-server-root /usr/local/nginx --nginx-ctl nginx        
    usage: 
      letsencrypt [SUBCOMMAND] [options] [domains]
    
    The Let's Encrypt agent can obtain and install HTTPS/TLS/SSL certificates.  By
    default, it will attempt to use a webserver both for obtaining and installing
    the cert.  
    letsencrypt: error: unrecognized arguments: --nginx-server-root /usr/local/nginx --nginx-ctl nginx

**Comment by diracdeltas** [comment]
> I assume the tool has also made specific assumptions about where nginx vhost files will be located etc and the format they take

Let's Encrypt looks for a file named `nginx.conf` inside the directory specified by `--nginx-server-root`, or `/etc/nginx` by default. All hosts included via `include` statements are parsed recursively.

nginx itself lets you specify the full path to the config file, whereas we require the base config file to be named `nginx.conf`.

In your case, if `/usr/local/nginx/conf/conf.d/newdomain2.com.ssl.conf` is included in `nginx.conf` somewhere, Let's Encrypt should be able to find it and modify it to set up SSL. You simply pick the host name to enable SSL for. If it doesn't work, that is probably a bug with the Nginx config parser.

**Comment by diracdeltas** [comment]
Try running 

`./venv/bin/letsencrypt  --nginx-server-root /usr/local/nginx -d le1.http2ssl.xyz auth`

instead

**Comment by rbonomo** [comment]
This works for me with Nginx conf files located in /usr/local/nginx
```
sudo certbot renew --dry-run --webroot -w /path/to/webroot
```

**Comment by schoen** [comment]
I'm going to assume that the helpful suggestion from @diracdeltas made almost 4 years ago works properly. @centminmod, please feel free to let us know if you still have an nginx configuration structure that you can't get our nginx installer to interoperate with properly!
