### ISSUE TITLE
Certbot installation failure because of temporary breakage of Python 3.4 on Debian 8

### ISSUE THREAD

**Issue by adferrand** [certbot/certbot#7180]
Our CI is broken because Python 3.4 is currently broken for Debian 8. This issue has been reported upstream and fixed few hours ago: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931044

This bug makes the installation of `python3.4` package of Debian 8 fail during the debconf invocation:
```
Setting up python3.4 (3.4.2-1+deb8u3) ...
  File "/usr/lib/python3.4/http/client.py", line 1014
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
                                                                     ^
SyntaxError: invalid syntax
dpkg: error processing package python3.4 (--configure):
 subprocess installed post-installation script returned error exit status 1
```

As a consequence, `apache_compat`, `nginx_compat` and `le_auto_jessie` are broken.

Some users may also encountered the issue when installing certbot on Jessie using certbot-auto or debian packages.

Hopefully the issue will be resolved without manual intervention once the new packages are published to Debian repo.

**Comment by adferrand** [comment]
I will rerun regularly our CI until the issue is fixed, and will update this issue accordingly.

**Comment by adferrand** [comment]
This issue is now fixed, since the new `python3.4` package has arrived in Debian repos.

**Comment by dapearce** [comment]
@adferrand I am getting this error today when I run the CLI commands to install certbot as outlined here: https://certbot.eff.org/lets-encrypt/debianjessie-apache

Is there something I can do to request the updated python version?

**Comment by MaffooBristol** [comment]
This is by no means a real fix, but if you edit `/usr/lib/python3.4/http/client.py` and change lines 1014 and 1015 to this:

```python
             raise InvalidURL("URL can't contain control characters. {!r} ".format(url) + 
                              "(found at least {!r})".format(match.group()))
```

It should allow it to work. Of course I'm not condoning this, I shouldn't really have to explain why modifying Python source is not a good idea!

**Comment by Aminadav** [comment]
@MaffooBristol  Thanks. Working for me
