### ISSUE TITLE
Remove Ubuntu Trusty packages from the PPA

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7183]
The system has reached it's end-of-life for the public and trying to support the system will get harder and harder due to issues like https://github.com/pyca/cryptography/issues/4923. I think the packages should be removed.

cc @oerdnj @NCommander

**Comment by devec0** [comment]
I have initiated deletion of Trusty packages given Trusty Tahr has been EOL for some time now.

**Comment by bmw** [comment]
Thanks @devec0!

Closing this as resolved.
