### ISSUE TITLE
Distribute certbot-ci

### ISSUE THREAD

**Issue by adferrand** [certbot/certbot#7186]
As a generic integration tests framework for Certbot, I think certbot-ci could be useful for external developers, that could reuse some parts of the logic it includes. 

Then maybe it would be interesting to make this project a part of the release process, and push it to pypi?

What do you think of that @bmw?

**Comment by bmw** [comment]
As a test framework for Certbot or for ACME clients in general? If the former, who is the target audience? If the latter, don't the tests need to be generalized a bit (and maybe renamed)?

**Comment by adferrand** [comment]
For Certbot. Primarily Boulder and Pebble, after, people that build things around Certbot (I am part of this group also).

**Comment by bmw** [comment]
Has the boulder/pebble team expressed interest? Also, how would this work for using an a different ACME server or Certbot wrapper? Isn't most of that stuff hardcoded? Is there any kind of stable API we're going to offer to allow people to extend it?

I'm not necessarily against the idea, I'm just trying to get a little more info about how people other than the Certbot dev team would be expected to use this.
