### ISSUE TITLE
Bad instructions for adding cron job for Debian

### ISSUE THREAD

**Issue by alexkingnz** [certbot/certbot#7192]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Debian GNU/Linux 8.7 (jessie)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto following https://certbot.eff.org/lets-encrypt/debianjessie-apache

## I ran this command and it produced this output:
echo "0 0,12 * * * python -c 'import random; import time; time.sleep(random.random() * 3600)' && certbot renew" | sudo tee -a /etc/crontab > /dev/null

# cat /etc/crontab 
# /etc/crontab: system-wide crontab
# Unlike any other crontab you don't have to run the `crontab'
# command to install the new version when you edit this file
# and files in /etc/cron.d. These files also have username fields,
# that none of the other crontabs do.

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# m h dom mon dow user	command
17 *	* * *	root    cd / && run-parts --report /etc/cron.hourly
25 6	* * *	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
47 6	* * 7	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
52 6	1 * *	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )
#
0 0,12 * * * python -c 'import random; import time; time.sleep(random.random() * 3600)' && certbot renew

## Certbot's behavior differed from what I expected because:
As I read the above, a username field is missing.  As I understand it, Cron will try to run the command "-c" as use "python".

## Here is a Certbot log showing the issue (if available):
# grep -i cron /var/log/syslog|tail
...
Jun 25 22:31:01 yourmantra cron[1658]: (*system*) RELOAD (/etc/crontab)
Jun 25 22:31:01 yourmantra cron[1658]: Error: bad username; while reading /etc/crontab
Jun 25 22:31:01 yourmantra cron[1658]: (*system*) ERROR (Syntax error, this crontab file will be ignored)

This is concerning me, because it seems that people following your instructions will not know about a problem immediately.  But certbot will not renew certs.  And it seems like whole system crontabs in /etc/cron.* are now broken?

Please fix the instructions on your website.

**Comment by alexzorin** [comment]
Looks like the new cron instructions were introduced a few weeks ago with https://github.com/certbot/website/commit/4a5e05b96d157dfb399a8aa08403f3afea663f07 . 

Issue should probably be moved to https://github.com/certbot/website/issues
