### ISSUE TITLE
Make changes to the Images/Code locally and use them

### ISSUE THREAD

**Issue by adi658** [certbot/certbot#7199]
This may be a silly question but 

How do you make changes to the repository "locally" and test it out?? For example, say I ws trying to check if we can add the EAB for certmanager by referring to Lego repository, 
https://github.com/go-acme/lego/blob/master/acme/api/account.go (Line 30)

But for that how do I proceed? How do I edit the code locally and then create the Docker Image out of it and then use those Docker images? 

Say if I add a couple of functions in the account.go or somewhere else, how do I make my current certmanager setup use those new changes?

**Comment by cpu** [comment]
@adi658 Did you perhaps open this issue on the wrong repository? I think you might have intended it for the [cert-manager](https://github.com/jetstack/cert-manager) repository instead of **Certbot**.

**Comment by bmw** [comment]
Yeah since this seems to be about cert-manager rather than Certbot, I'm closing this issue but if you think I've misunderstood, please let me know!

**Comment by adi658** [comment]
Oops so sorry.. Been working on certbot and certmanager repos..
