### ISSUE TITLE
Update the Apache plugin's TLS config to follow Mozilla's new recommendations

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7204]
This can be found at https://ssl-config.mozilla.org. In general, doing this is a little tricky because we don't want to break people with old versions of Apache/OpenSSL. Looking at the code that is used to generate these config snippets may be useful for this which is found at https://github.com/mozilla/ssl-config-generator.

For now, I don't think we should be enabling HTTP2, HSTS, or OCSP stapling as part of this. We may want to reconsider doing this in the future, especially for HTTP2, but so far we've thought about these things as an optional security enhancement for Certbot and I think deciding to enable these features on all configs should be a separate issue.

**Comment by bmw** [comment]
@adferrand, this is tentatively assigned to you for our next release, but we'll chat more during our 1-1.

**Comment by ohemorange** [comment]
I think this should block on un-reverting the session tickets machinery and implementing #7350.

**Comment by bmw** [comment]
When doing this we should continue allowing `TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA` like we did in the nginx plugin in https://github.com/certbot/certbot/pull/7414.

**Comment by fleish** [comment]
Hi @bmw, is there a reason this keeps getting pushed out? If I'm reading correctly it's now slated for 1.2.0 in February 2020 which means current installations of certbot+nginx are still supporting TLSv1.1 & even worse, TLSv1. I understand from previous issues the certbot team is taking direction from Mozilla, but they are no longer recommending this (for many months now) and both of these protocols have been widely considered deprecated since June 30, 2018.

**Comment by bmw** [comment]
Thanks for the nudge on this @fleish.

To be clear, this issue is about Apache, not nginx. We've been following Mozilla's updated TLS recommendations for nginx since August. See https://github.com/certbot/certbot/blob/master/certbot/CHANGELOG.md#0370---2019-08-07.

The reason this issue hasn't been resolved though is due to the combination of this issue being pretty difficult to fully implement (see https://github.com/certbot/certbot/issues/7350) and us having commitments to work on other aspects of Certbot. We know it's important and I honestly think we'll get it to it soon, but the small team of people maintaining Certbot just haven't been able to tackle this issue yet.

With that said, if I'm wrong and we cannot resolve this issue the way we want in the long term soon, we may be able to pretty easily update cipher suites and disable TLS<1.2. This wouldn't include conditionally enabling TLS 1.3 and disabling TLS session tickets which we want to do in the long term, but it would eliminate the problems you flagged in your post.

I'll try and make sure that at least this aspect of this issue is included in our release at the beginning of February.

**Comment by bmw** [comment]
@ohemorange, with #7712, this issue is resolved except for #7350 right?

If so, I think we should close this issue.

**Comment by ohemorange** [comment]
> @ohemorange, with #7712, this issue is resolved except for #7350 right?

Yes, that's my understanding.
