### ISSUE TITLE
Update the nginx plugin's TLS config to follow Mozilla's new recommendations

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7205]
This can be found at https://ssl-config.mozilla.org. In general, doing this is a little tricky because we don't want to break people with old versions of nginx/OpenSSL. Looking at the code that is used to generate these config snippets may be useful for this which is found at https://github.com/mozilla/ssl-config-generator.

For now, I don't think we should be enabling HTTP2, HSTS, or OCSP stapling as part of this. We may want to reconsider doing this in the future, especially for HTTP2, but so far we've thought about these things as an optional security enhancement for Certbot and I think deciding to enable these features on all configs should be a separate issue.

**Comment by ohemorange** [comment]
>  In general, doing this is a little tricky because we don't want to break people with old versions of nginx/OpenSSL.

Could you say more about this? Which part of this might break these configurations, and are we choosing to support something that Mozilla doesn't think still needs to be supported?

**Comment by bmw** [comment]
When you go to https://ssl-config.mozilla.org/ the default nginx config it generates as of writing this is for nginx 1.17.0 and openssl 1.1.1c which were both released last month. When you have recent versions of both, you are recommended to enable the latest and greatest security features such as TLS 1.3 and disable problematic features like TLS session tickets.

Unfortunately, most people's versions of nginx and openssl are older than this though and not all of them support these features. You can specify an older version of nginx/openssl into Mozilla's config generator and it will leave these settings out of the generated config.

While we could just use the settings for the oldest possible configuration we're still supporting, I personally think we should dynamically use newer configuration options as they become available. Not doing this is what caused us to not disable TLS session tickets until recently and I think there's value in us actually trying to follow Mozilla's recommendations as close as we can.

Luckily, I suspect this will be pretty easy. I think whoever works on this issue should verify this, but I think the only things we have to worry about handling dynamically are TLS session tickets (which we already handle) and TLS 1.3.

**Comment by ohemorange** [comment]
Ah, gotcha. Yeah, looks like barring the things you mentioned in the original post, the only other changes are in this section:

```
# intermediate configuration
ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
ssl_prefer_server_ciphers off;
```

The first two are explained [on the site](https://wiki.mozilla.org/Security/Server_Side_TLS). But as for `ssl_prefer_server_ciphers`, as far as I can tell that's `off` for all of their recommendations, even though we have it as `on`. Do you remember why we do that?

**Comment by bmw** [comment]
It's what they recommended in the [old version of the config](https://web.archive.org/web/20190425121155/https://mozilla.github.io/server-side-tls/ssl-config-generator/) before their recent update.

A description of why they made this change is at https://github.com/mozilla/server-side-tls/issues/260.

**Comment by ohemorange** [comment]
Ah, cool, so gotta be sure to keep that option coupled with offering a narrower range of secure-only ciphers.

**Comment by bmw** [comment]
Keeping in mind that you should probably double check everything that I'm saying to make sure I'm not misreading things, but I believe their current recommendations for their intermediate config always results in the same values for `ssl_ciphers` and `ssl_prefer_server_ciphers` for all versions of nginx and openssl.

**Comment by ohemorange** [comment]
You're right, I was confusing `ssl_protocols` and `ssl_ciphers`; it's just that older versions of Nginx won't have newer `ssl_protocols` available.

I am surprised to see that no matter how old you put either Nginx or OpenSSL, all the ciphers are always available. Must be that it's letting OpenSSL figure out dynamically if it has that cipher available.

**Comment by bmw** [comment]
It's also possible that their config generator is buggy here. I'm not aware of any current issues, but from watching their repos I've seen at least a couple bugs that have since been fixed caused by them not properly filtering values for older versions of different software.

I think it's probably worth us spinning up an ancient version of Debian/CentOS/Ubuntu and verifying that the recommended values work.

**Comment by ohemorange** [comment]
tested on centos6 with nginx 1.10.3, intermediate config, OpenSSL 1.0.1e-fips: works fine

how ancient do you think we can reasonably expect to get with distros we still support?

**Comment by ohemorange** [comment]
tested on debian jessie with nginx 1.6.2, intermediate config, OpenSSL 1.0.1t: works fine

**Comment by ohemorange** [comment]
for tls1.3, we need:
- nginx >= 1.13.0
- openssl >= 1.1.1 (being careful about them adding letters to their versions)

**Comment by bmw** [comment]
> how ancient do you think we can reasonably expect to get with distros we still support?

I personally think checking the oldest not EOL'd versions of CentOS, Debian, and Ubuntu is good enough. In this case, Debian Jessie is older than Ubuntu 16.04 so we should be good there too.

I'm not aware of any systems with packages older than that that are still supported by the distro maintainers. If they do exist, they are a very small minority.
