### ISSUE TITLE
Usability improvements for dns-rfc2136 plugin

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#7206]
[This community thread points out](https://community.letsencrypt.org/t/supported-bind9-dns-challenge-client/96542) two issues with the current plugin:

 - The name is confusing. Most people don't know what RFC2136 is. We should probably add an alias like `dns-bind` or `dns-nsupdate` (after the widely used CLI update tool).

 - [The instructions to use dnssec-keygen](https://certbot-dns-rfc2136.readthedocs.io/en/stable/#sample-bind-configuration) should be replaced with tsig-keygen for Bind 9.13+. Though @joohoi pointed out on chat that most distros are still on Bind 9.11 so far.

**Comment by noci2012** [comment]
bind is not the only server providing this service based on RFC2136.
PowerDNS should also support this.
dns-dyndns might be confusing as well as dyndns is also used for other servicees where someone can update only it's own record. mostly through specific other tools.

**Comment by mnordhoff** [comment]
\*pokes bot\*
