### ISSUE TITLE
[docs] `sudo certbot` should be `sudo certbot-auto`?

### ISSUE THREAD

**Issue by michielbdejong** [certbot/certbot#7219]
I visited https://certbot.eff.org/lets-encrypt/ubuntuother-other and found that

`sudo certbot certonly --standalone`

in step 3 does not work, but

`sudo certbot-auto certonly --standalone`

does.
Which makes sense because that's the executable filename used in step 2:

`sudo mv certbot-auto /usr/local/bin/certbot-auto`

**Comment by joohoi** [comment]
Hi @michielbdejong and thanks for opening the issue!

You are spot on, it definitely is a bug in the instructions. The website repository can be found at https://github.com/certbot/website/ and this issue should be opened there. Would you like to do it, or should I open an issue for you?

**Comment by michielbdejong** [comment]
Thanks! continued there ^
