### ISSUE TITLE
Update targets.yaml to test against Debian 10

### ISSUE THREAD

**Issue by maximillianh** [certbot/certbot#7225]
Debian 10 Buster has been released and should be added to the test farm tests.

**Comment by pierreDebuisson** [comment]
I have an issue when installing the certbot nginx plugin on Debian 10 with the buster-backports... I have the following error :

<img width="729" alt="Screenshot 2019-07-20 at 01 04 27" src="https://user-images.githubusercontent.com/27561000/61570093-d955d300-aa8a-11e9-9b4f-0adaaafeddce.png">

How can I resolve this problem ?

**Comment by bmw** [comment]
@pierreDebuisson, I recommend you post to https://community.letsencrypt.org where there is a large community of people familiar with Certbot who should be able to help you fix the problem.

As for the original issue here, it doesn't look like there any official Debian 10 AMIs offered by either Amazon or Debian. I think we should delay doing this until there is one.

**Comment by bmw** [comment]
Moving this to 0.39.0 because as of today, official AMIs still do not exist.
