### ISSUE TITLE
"certbot renew" with manual plugin should give a clear, useful error

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#7227]
We have a considerable volume of forum posts where people get the  `PluginError(‘An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.’,)` message

https://community.letsencrypt.org/search?q=%22authentication%20script%20must%20be%20provided%22%20order%3Alatest

and it seems that a very high fraction of people who encounter that error don't understand what it's trying to tell them. They often don't know what an `authentication script` is in this context, some don't know what `the manual plugin` is, and most don't realize that `using the manual plugin non-interactively` means "running `certbot renew`".

This error exists for good historical reasons, but the way that it appears is most often unhelpful to people who don't understand much about Certbot plugins and challenges. We should find a way to totally revamp this output and give people more specific and practical advice about what's happening and what they can do about it.

**Comment by schoen** [comment]
I suggested as a strawman proposal

>  You tried to renew a certificate "foo" using the certbot renew command, but this certificate was originally obtained using --manual, because it is a wildcard certificate. This renewal process requires human intervention to complete; Certbot can't complete it on its own.

>  You can try again using certbot --cert-name foo certonly and following the steps when prompted. (You will have to do this every time that you renew this particular certificate, because it will always require manual intervention.)

> Alternatively, you can switch to a method that automates the DNS record updates, so that this certificate can be renewed non-interactively in the future. For more information about this option, please see https://certbot.eff.org/docs/switching-from-manual.    [note that this particular resource doesn't currently exist]

**Comment by schoen** [comment]
Duplicate of https://github.com/certbot/certbot/issues/6280.

**Comment by augchan42** [comment]
To set a pre-existing manual certificate to auto renew, I ran certbot --nginx again.  This let me select the existing certificate by number and I then selected option 2 - Renew & replace the certificate. 
I'm on certbot 1.28,.0

**Comment by Obad94** [comment]
@augchan42  I executed the command certbot --nginx, and it effectively renewed the wildcard certificates upon selecting the specified options. How will the automatic renewal occur using the method mentioned above?

**Comment by fschossler** [comment]
What is worth to mention is that Let's Encrypt forces you to use [DNS Challenge to issue wildcard certificates](https://letsencrypt.org/docs/challenge-types/#dns-01-challenge) 💡

In this case just an automation with your domain provider can help with the automation of these certificates.

**Comment by Obad94** [comment]
Hi @fschossler, Thank you for the response.
Hello @fschossler,

Thank you for your response. I'm pleased to inform you that I have successfully completed the automation process. I obtained the API key from the domain provider, allowing certificates to be renewed automatically before expiration. Everything is running smoothly and efficiently.
