### ISSUE TITLE
Path Error, when exec from PHP shell

### ISSUE THREAD

**Issue by surjit** [certbot/certbot#7228]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 18.04 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
ppa

## I ran this command and it produced this output:
<?php 
shell_exec("certbot --apache -n -d mydomain.com");

  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 232, in prepare
    self._verify_exe_availability(self.option("ctl"))
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 274, in _verify_exe_availability
    if not util.exe_exists(exe):
  File "/usr/lib/python3/dist-packages/certbot/util.py", line 116, in exe_exists
    for path in os.environ["PATH"].split(os.pathsep):
  File "/usr/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'PATH'
2019-07-10 18:16:35,007:ERROR:certbot.log:An unexpected error occurred:

## Certbot's behavior differed from what I expected because:
It should work as it work perfectly from terminal

**Comment by surjit** [comment]
I ran this command and it produced this output:
```
<?php 
shell_exec("certbot --apache -n -d mydomain.com");
```

> 
>   File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 232, in prepare
>     self._verify_exe_availability(self.option("ctl"))
>   File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 274, in _verify_exe_availability
>     if not util.exe_exists(exe):
>   File "/usr/lib/python3/dist-packages/certbot/util.py", line 116, in exe_exists
>     for path in os.environ["PATH"].split(os.pathsep):
>   File "/usr/lib/python3.6/os.py", line 669, in __getitem__
>     raise KeyError(key) from None
> KeyError: 'PATH'
> 2019-07-10 18:16:35,007:ERROR:certbot.log:An unexpected error occurred:

**Comment by ohemorange** [comment]
Hey @surjit! Looks like the PATH isn't getting passed into php, which indicates to me that this isn't a bug within certbot itself. Please first try asking for help at https://community.letsencrypt.org/. There is a much larger community there of people familiar with the project who will be able to more quickly answer your questions.

**Comment by diego-lipinski-de-castro** [comment]
@surjit did you ever solved this?
