### ISSUE TITLE
Certbot docs should instruct you how to change Domain Records

### ISSUE THREAD

**Issue by JimTheMan** [certbot/certbot#7234]
Took me hours debugging this:

```
Failed authorization procedure.
...

To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
```

because no where in the docs does it say anything about what A records to change...

**Comment by bmw** [comment]
Yikes. I'm sorry to hear you had to spend hours debugging.

The full error output should have looked something like:
```
 - The following errors were reported by the server:

   Domain: example.org
   Type:   unauthorized
   Detail: Invalid response from
   http://example.org/.well-known/acme-challenge/JMyvuxwe727YNjkuviWmlqKHXYh9U-DForUtaHPQgnI
   [2606:2800:220:1:248:1893:25c8:1946]: "<!doctype
   html>\n<html>\n<head>\n    <title>Example Domain</title>\n\n
   <meta charset=\"utf-8\" />\n    <meta http-equiv=\"Content-type"

   Domain: www.example.org
   Type:   unauthorized
   Detail: Invalid response from
   http://www.example.org/.well-known/acme-challenge/6SDKVCyt4UsCQUXRQy3O-mCAG3Rn9T8oDb3zlN-WSLU
   [2606:2800:220:1:248:1893:25c8:1946]: "<!doctype
   html>\n<html>\n<head>\n    <title>Example Domain</title>\n\n
   <meta charset=\"utf-8\" />\n    <meta http-equiv=\"Content-type"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
```
Would changing this to reference "the domains listed above" solve this problem for you?

**Comment by JimTheMan** [comment]
"To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address."

No, because it still requires googling to figure out what "correctly set the DNS A/AAAA records" means.

**Comment by bmw** [comment]
Well unfortunately, I don't think Certbot can realistically explain DNS A/AAAA records in the output here. I think giving you that phrase which you can then Google to learn what it means and fix your DNS is probably about the best we can do so for that reason I'm closing this issue.

Thanks for taking the time to file an issue though!
