### ISSUE TITLE
Doc Request: Challenge failed for domain; no workaround for server in private network with no public DNS?

### ISSUE THREAD

**Issue by petjal** [certbot/certbot#7235]
In retrospect I guess of course it makes sense that certbot/letsencrypt cannot be used to create certificates for servers accessible only from within a private network with no public DNS records.  

Maybe that's obvious to most folks, but without it being clearly stated early in the docs or scripts as a fundamental limitation or requirement with no work-around, I flailed around today trying to make it work and of course failed.  

The error messages I was seeing were fairly obvious and straightforward, like:
   _make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client_
but I wasn't sure whether some other incantation of command line options might work for my situation.  

I've already created a local CA for this purpose, and that works fine, but I was playing around with certbot/letsencrypt today in hopes that maybe letsencrypt would eliminate the need to add my local root CA to all our various kinds of clients.  

Regardless, thanks for a great service to the community!

**Comment by bmw** [comment]
Thanks for the kind words @petjal.

I think this is a problem that won't affect most Certbot users, but better documenting it for those it does would certainly be helpful.

@ohemorange, do you have an opinion on where something like this should go?

**Comment by ohemorange** [comment]
On https://certbot.eff.org/, we have a "To use Certbot, you'll need..." box that we use in a few places. In these requirements, we have "that is already online" with "already online" a click-for-more-info box. Inside that box we talk about the requirements, with the following wording:

> Certbot is usually meant to be used to switch an existing HTTP site to work in HTTPS (and, afterward, to continue renewing the site’s HTTPS certificates whenever necessary). Some Certbot documentation assumes or recommends that you have a working web site that can already be accessed using HTTP on port 80. That means, for example, that if you use a web browser to go to your domain using http://, your web server answers and some kind of content comes up (even if it’s just a default welcome page rather than the final version of your site). Some methods of using Certbot have this as a prerequisite, so you’ll have a smoother experience if you already have a site set up with HTTP. (If your site can’t be accessed this way as a matter of policy, you’ll probably need to use DNS validation in order to get a certificate with Certbot.)

We could modify this language to make the requirement explicit here.

**Comment by petjal** [comment]
Similarly, on this page:
https://certbot.eff.org/
at the bottom it says:
_Don't have these requirements?
Not to worry! Some hosting providers automate the HTTPS process. See the full list of hosting providers, or find out more about how to set up your system._
which links to 
https://certbot.eff.org/help#webserver
I would think, near or at the top of that page, as well as near the top of the FAQ
https://certbot.eff.org/faq#what-tools-can-i-use-for-debugging-my-site-s-https-configuration
 it could say something like:
_If your server is inside a private network and you cannot modify your public DNS records, then LetsEncrypt won't work for you.  For other options, see, for example,
https://community.letsencrypt.org/t/adding-a-lets-encrypt-server-in-a-offline-network/21705
and
https://jamielinux.com/docs/openssl-certificate-authority/index-full.html (to use openssl to set up a local CA)
and
https://www.xinotes.net/notes/note/1094/ (to add SAN DNS and IP records to your CSR to avoid Google Chrome's ERR_CERT_COMMON_NAME_INVALID warning)._

**Comment by bmw** [comment]
Good ideas! I created https://github.com/certbot/website/issues/448 for us to track this work on the Certbot website.
