### ISSUE TITLE
certbot_apache lacks testing of certbot.compat

### ISSUE THREAD

**Issue by hlieberman** [certbot/certbot#7237]
As of v0.36.0, certbot_apache depends on certbot >= 0.36.0 because of the import of `filesystem` from `certbot.compat`.  However, this dependency is only exposed at run-time and in setup.py -- there is no test coverage that runs this import.

This exposes a risk that CI/CD systems will not catch a broken import.  A test should be added to require the filesystem import during test time.

**Comment by adferrand** [comment]
Hello @hlieberman!

Now there is at least one unit test in apache package that explicitly imports and use `certbot.compat.filesystem`:
https://github.com/certbot/certbot/blob/40da709792d0e5907207ce1346020c72d8ec34be/certbot-apache/certbot_apache/tests/configurator_test.py#L19

I suppose it is sufficient to trigger alarms if the import is failing?

**Comment by adferrand** [comment]
Ok, closing the issue now, since there is an explicit import of the `filesystem` module in one of the test modules.
