### ISSUE TITLE
dns-rfc2136 plugin: once again fix CNAME/DNAME behavior

### ISSUE THREAD

**Issue by hpax** [certbot/certbot#7243]
The fix for bug #7142 once again introduces bug #6787. Note that the patch proposed by myself for #6787 is automatic, rather than expecting manual configuration as in the botched #7029 

I have refreshed the patch on top of the current master and will submit a pull request shortly.

**Comment by schoen** [comment]
@bmw, could you take a look at this because you created the fix @hpax is referring to?

**Comment by bmw** [comment]
I'm going to close this in favor of the PR implementing this at https://github.com/certbot/certbot/pull/7244 and the general issue tracking this for all of our DNS plugins at https://github.com/certbot/certbot/issues/6566.
