### ISSUE TITLE
Set secure flag on cookies in the Apache/Nginx plugin?

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7253]
In making some changes to the Apache plugin, we came across [this commented out directive](https://github.com/certbot/certbot/commit/68f85d9f1abc2b66a6a9a0bd970d42f37395f217#diff-ec7fe1c264165d04b90669d6784c4fa9R23) from 2012 suggesting we set "Secure" on cookies. While I recommended we delete these commented out directives for now, this might be something for us to look into.

I asked jsha about this who said:
> It would be nice. It definitely has breakage potential.
>
> If we have set HSTS we can be pretty confident in setting the Secure flag for cookies that are origin-scoped, but a lot of cookies are bound to origin plus subdomains. We have no way if the site owner is relying on non-secure cookies getting sent to subdomains.
>
> There's also a lot of potential to mis-parse cookies when looking for where to add the secure flag. For instance, there's the newer __Secure- prefix, which we can't use (because it would rename people's cookies), but it could get parsed as the presence of a secure flag: https://googlechrome.github.io/samples/cookie-prefixes/.

With these concerns in mind, this seems like a bit of a wishlist ticket for me and not something that should be enabled by default, but here's a ticket for us to maybe look into the issue in the future.

**Comment by joohoi** [comment]
On the same topic, but from a different angle: We probably shouldn't provide commented out configuration directives within our configuration includes at all.

While it's good to reference some options that the users can set manually, the include file (at least for Apache plugin) is a very wrong place to have it. The only intuitive action the user can take with those would be commenting them out if they want to benefit of them - resulting into Certbot not being able to automatically update the include file when needed.

**Comment by joohoi** [comment]
I think this also depends on redirecting HTTP to HTTPS per default, as in most cases it would break the HTTP site functionality.

**Comment by bmw** [comment]
While I think this is still an interesting idea, I can't imagine us being able to prioritize it in at least the next couple years so I'm closing this for now.
