### ISSUE TITLE
Override the distro overrides in the Apache plugin

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7255]
As also suggested at https://github.com/certbot/certbot/issues/7106#issuecomment-507584244, I think we need a way to manually specify which "distro override" to use in the Apache plugin at https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/entrypoint.py.

There is a user at https://community.letsencrypt.org/t/noinstallationerror-cannot-find-apache-executable-apache2ctl/97980 for whom the Apache plugin seems completely unusable due to us not properly detecting their system and they have no way to mitigate the problem.

Alternatively, we could create yet another command line flag allowing them to control the SSL options, however, they may just be other problems that arise once this is resolved.

@joohoi, if you have any high level thoughts about this problem, I'd be interested to hear them!

**Comment by joohoi** [comment]
I think being able to define the override to use as a template would be the best approach indeed. In fact #7191 is removing the file name constant completely, which I think is a good move as filename - especially as it's bundled in our packages - is not very transparent for the user.

Also; we apparently found the first case of `/etc/os-release` not being available! That's Scientific Linux 6. The next version - 7 has it, and it's properly composed as well. 

The `/etc/os-release` in SL 7 defines `ID_LIKE` which we use as a fallback information if we cannot find the exact override defined by `ID` variable. In case of SL 7, we would pick the CentOS override based on the first value, which is `rhel`. A snippet from SL 7 `/etc/os-release` below:
```
NAME="Scientific Linux"
VERSION="7.6 (Nitrogen)"
ID="scientific"
ID_LIKE="rhel centos fedora"
VERSION_ID="7.6"
PRETTY_NAME="Scientific Linux 7.6 (Nitrogen)"
```

**Comment by bmw** [comment]
I think a flag to choose the override to use is a bit awkward as I've never seen any program accept a parameter like this before, but it probably gives a better UX than making the user manually set a half a dozen flags.

At a bare minimum, I think the help text for the flag should say what values are accepted. It'd also be nice if there was a way to see what the different values for each Apache flag was with each override.

How to do this is a bit tricky structurally though. One of the first thing that Certbot does is [find it's plugins](https://github.com/certbot/certbot/blob/71ff47daad97dab3c2659a705d036428275c7bd2/certbot/main.py#L1352). At this point, the code in https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/entrypoint.py runs and the selected class is saved as an attribute of these [PluginEntryPoint objects](https://github.com/certbot/certbot/blob/0c5f526f8bd69de37ee7b6de05f45040394cd6f2/certbot/plugins/disco.py#L21). I'm not sure how we're going to change this later.

**Comment by jsoref** [comment]
It isn't just Scientific linux that doesn't have this file.
```sh
# lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 6.10 (Santiago)
Release:	6.10
Codename:	Santiago
```
```sh
# ls /etc/os-release
ls: cannot access /etc/os-release: No such file or directory
```

(I'm here because I'm pretty sure I hit the same problems as #7248)

**Comment by joohoi** [comment]
A missing `/etc/os-release` should not be (and shouldn't have been) an issue for distributions that we have specific rules for. If the file isn't found, we fall back to `platform.linux_distribution()` (previously) and `distro.linux_distribution()` (now). 

The issue was only with distributions we were not supporting directly, and `/etc/os-release` would have helped Certbot to pick the correct configuration template through its `LIKE` - variable.

The `distro` library is doing a good job in OS detection, and as the first step is using `/etc/os-release` as one if its primary detection methods. It also natively provides an interface to the `LIKE` variable as well. We should probably drop the manual parsing of the `/etc/os-release` in the future completely in favor of the interface provided by `distro`.

**Comment by ohemorange** [comment]
Just putting this here for posterity:

Scientific Linux release | Full updates | Maintenance updates
-- | -- | --
6 | Q2 2017 | 2020-11-30

If we don't get to this issue by November, we might just be able to close it.
