### ISSUE TITLE
remove cloudxns support please

### ISSUE THREAD

**Issue by xiaohuilam** [certbot/certbot#7276]
Cloudxns terminated its service.

**Comment by mnordhoff** [comment]
If I run Google Translate on their website, it sounds like they're terminating the free service but continuing to offer a paid service. Is that correct?

The plugin might still have value... On the other hand, it might not be feasible to test it...

https://www.cloudxns.net/Support/detail/id/3381.html

**Comment by xiaohuilam** [comment]
> If I run Google Translate on their website, it sounds like they're terminating the free service but continuing to offer a paid service. Is that correct?
> 
> The plugin might still have value... On the other hand, it might not be feasible to test it...
> 
> https://www.cloudxns.net/Support/detail/id/3381.html

CloudXNS terminate its free service means sentence its 99.5% customers  transferred to elsewhere. so keep its certbot support is meaningless.

**Comment by schoen** [comment]
Thanks @xiaohuilam, is there any way to verify this impact?
