### ISSUE TITLE
Specify that we require a newer version of Python on Windows

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7279]
@adferrand pointed out that for Windows our packages will probably include their own copy of Python and as a result of this can probably work around problems like https://github.com/certbot/certbot/issues/7115 by simply requiring a newer version of Python on Windows.

To do this properly though, we need a way to dynamically specify the Python version required in the affected setup.py files. How to do this in a way that doesn't break wheels due to problems similar to those described at https://github.com/certbot/certbot/pull/6964#issuecomment-484311124 requires a bit of research.

**Comment by adferrand** [comment]
Sadly, after checking, environment markers are not supported in `python_requires` setuptools parameter, so we cannot use the dedicated approach to specifically set the python compatibility for Windows ...

https://github.com/pypa/packaging-problems/issues/209

**Comment by bmw** [comment]
I see. Thanks for looking into this Adrien.

I personally am still interested in trying to solve some of our Windows problems by just requiring a new Python version despite this though.

@erikrose, do you have any ideas on how to accomplish this despite the limitation Adrien found above? Maybe we could make separate Windows wheels (or not offer a Windows wheel at all)? Maybe we can just make Certbot fail fast on Windows if it's running on old version of Python?

**Comment by erikrose** [comment]
I don't know much about Windows. But if your problems are at runtime (rather than build time) as they seem to be, failing fast at runtime seems like the most foolproof way. We could also, as you suggest, make separate, pickier wheels for Windows, but there's nothing keeping someone from using an sdist and having it break on their old version of Python.

**Comment by bmw** [comment]
Correct. Our problems are mainly at runtime.

(The minor exception to this that I can think of is I think we could have issues on Python 3.4 at install time because there are no sdists or wheels for our dependency `pywin32` on PyPI for Python 3.4, but we're actively working on dropping Python 3.4 support which should avoid that issue.)

The main thing I was trying to accomplish in this issue is specifying in our packages the best way that we can that Certbot only supports Python 3.6/3.7 on Windows while keeping support for other versions of Python on other systems. I think we could change the wheels we offer and make `setup.py` error on Windows for the case of installing an sdist, but honestly that all sounds kind of annoying to me.

I think we should:

1. Add a check at the beginning of Certbot's execution about this and crash with a good error message if you're running on an old version of Python on Windows.
2. Keep an eye on https://github.com/pypa/packaging-problems/issues/209 and update our `setup.py` files if this is ever supported.

**Comment by erikrose** [comment]
Does it end up easier just to carry around fixed versions of the buggy routines, as in #7115?

**Comment by bmw** [comment]
I personally don't think so unless there's significant problems in just catching old Python versions at runtime. Raising an exception on Windows for old Python versions is a couple lines of code. There's a lot more complexity in #7115 which we would otherwise have to maintain. In fact, we've already found limitations of that code in #7262 which I otherwise think we'd have to fix.

**Comment by erikrose** [comment]
Fair 'nuf!
