### ISSUE TITLE
Let's make certbot-auto mostly pass the shellcheck linter

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#7283]
There is a nice linter for shell scripts called `shellcheck`. I just ran it on `certbot-auto` right now and it definitely did not pass. :-)

There are a few things that we might not care about, but we can definitely clean up the content of this script in a few ways using this linter.

**Comment by bmw** [comment]
This is a more specific version of https://github.com/certbot/certbot/issues/5280.

Also, while I don't want to dampen your excitement to work on Certbot, we've actually been treating certbot-auto's code as frozen except in rare circumstances. See our note at https://certbot.eff.org/docs/contributing.html#updating-certbot-auto-and-letsencrypt-auto.

I'm personally OK maybe deviating from this if you're really excited to do this work now, however, I'll flag that any changes should not only be POSIX compliant (i.e. they have to work with more shells than bash), they should work with busybox which at least historically didn't provide a full POSIX shell. See #3797.

**Comment by bmw** [comment]
certbot-auto has been deprecated, will error out on new systems, and existing installations are no longer receiving updates so I'm closing this.
