### ISSUE TITLE
Github IPV6 issues when trying to download latest update

### ISSUE THREAD

**Issue by erik998** [certbot/certbot#7286]
## My operating system is (include version):
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

Linux 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## I installed Certbot with:
I used these instructions:
https://computingforgeeks.com/how-to-install-dokuwiki-on-ubuntu-18-04-with-nginx-and-letsencrypt/

```
sudo apt-get update
sudo apt-get install wget nginx
wget https://dl.eff.org/certbot-auto
chmod +x certbot-auto
sudo mv certbot-auto /usr/local/bin/certbot-auto
```

## I ran this command and it produced this output:

```
> certbot-auto
Requesting to rerun /usr/local/bin/certbot-auto with root privileges...
Upgrading certbot-auto 0.33.1 to 0.36.0...
Couldn't download https://raw.githubusercontent.com/certbot/certbot/v0.36.0/letsencrypt-auto-source/letsencrypt-auto. <urlopen error [Errno 101] Network is unreachable>
```

## Certbot's behavior differed from what I expected because:
github does not support IPV6.
Many lowend boxes only support IPV6.

Here is a relevant posting about IPV6 support
https://github.com/isaacs/github/issues/354#issuecomment-385746014

Any plans to implement support for IPV6 restricted servers? Maybe use an alternate repository to download the latest script?

## Work Around Solution:
certbot-auto --no-self-upgrade

**Comment by joohoi** [comment]
Thanks for opening the issue. This is very unfortunate. We'll have to see if there's anything we can do, but it's going to take a while if GitHub / Fastly (which raw.githubusercontent.com is using) are not able to provide it.

**Comment by bmw** [comment]
In the meantime, I recommend you follow [our instructions to configure Nginx with Certbot](https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx) which doesn't use certbot-auto and avoids this problem.
