### ISSUE TITLE
Suggestion for Letsencrypt Certificate Manager for dealing with key backups

### ISSUE THREAD

**Issue by centminmod** [certbot/certbot#729]
As suggested by @schoen submitting a feature request for what I outlined at https://community.letsencrypt.org/t/tools-for-ssl-key-management/536 for extending The Letsencrypt Certificate Manager with backup features for HPKP support :)

> extending Let's Encrypt Certificate Manager to backups might be good for HPKP so you could back up the backup keys for HPKP and also allow folks to view with SSL certs and sites have what specific key pins associated with their sites
> 
> Maybe even add external check function in the Let's Encrypt Certificate Manager could curl the site's headers and check if the live sites pins match what was backed up and generated in the Let's Encrypt Certificate Manager backup copy ? Maybe could eventually used as part of a verification process for auto rotating HPKP policy every 90 days ?

**Comment by J0WI** [comment]
This blocks me from using letsencrypt.
Is there a way to sign an existing key?

**Comment by devnsec-com** [comment]
Hi, @J0WI 
Yes, there's a way to sign a CSR:
```
letsencrypt --csr /path/to/csr auth
```

But for the HPKP, sign a CSR could be painful for renew. My currently solution is pinning the LE root CA certificate instead of my certificate.

**Comment by J0WI** [comment]
pinning the root certificate would not be vaild

**Comment by devnsec-com** [comment]
@J0WI Sorry, I missed your last comments. Pinning the root cert is not useless, it prevents any other (compromised) CAs issue a cert for your site.
If you have pinned the root cert, and a hacker want to MITM attack your website without being noticed by normal users, the hacker has to compromise the CA that issued your cert, instead of any CAs in user's OS/browser's trust list (which could be hundreds CAs) , this make the hacker's life much harder.

**Comment by J0WI** [comment]
Yes but we already learned that not every CA takes care of issuing multiple certs.
And hackers or governments can still misapply a CA.

**Comment by J0WI** [comment]
So what need to be done here:
- add an option that creates backup key and csr if no exist and use backup csr to renew if one exists
 - see also #407 for something like `rekey --backup`?
 - multiple old backups should be cleaned up
- add cmd to output current/backup pub keys (may be separate issue)
- auto-conf is #1611 and #624

**Comment by schoen** [comment]
As a belated follow-up, do people who requested this think that HPKP has enough of a future or enough of an application that you would still like HPKP tooling to be added to Certbot?

**Comment by J0WI** [comment]
HPKP is the only way to reject and monitor certs issued by bad CAs or middleware.
I cannot understand the proposed complete removal of this feature in Chromium.

**Comment by J0WI** [comment]
There is still no proper solution for key backups and backup rotation.

**Comment by J0WI** [comment]
*bump*

**Comment by schoen** [comment]
@J0WI As I'm no longer a Certbot developer, I can't reopen it myself, but hopefully someone else can.

Could you restate what you're looking for on this issue? Would it be sufficient to be able to reference an existing private key and have Certbot then use that as the private key for a new certificate request (that ends up in `/etc/letsencrypt` like other autorenewable certificates)?
