### ISSUE TITLE
Enhancement Request: --cron switch (Rand sleep & quiet.)

### ISSUE THREAD

**Issue by DanStaal** [certbot/certbot#7290]
This is an enhancement request: Could we get a switch (likely `--cron`) which enables a random sleep for up to one hour?  Likely also it should bundle in the functionality of the `-q` switch, but that can be left to a dedicated switch if desired.

This would allow the common scenario of running certbot from cron without having it automatically hit at the same time, and sidestep issues on having the user manually create a good randomizer - especially cross-platform (as cron doesn't always behave the same), or in conjunction with other scripts in the same cron entry.

All the switch needs to do is if present delay execution of the rest of the script for a random time up to one hour.

**Comment by sydneyli** [comment]
Hi @DanStaal, thanks for reporting! This should be happening for non-interactive runs of `certbot renew`, with a delay up to 4 minutes: #6391 and with our [prepackaged cron](https://salsa.debian.org/letsencrypt-team/certbot/certbot/blob/master/debian/certbot.cron.d) on Debian, it performs a randomized sleep up to 12 hours! Is that amount of randomness sufficient for your use case?

The random sleep during non-interactive runs also isn't documented anywhere, so adding the documentation label.

**Comment by DanStaal** [comment]
This is more for the benefit of Let's Encrypt than for me - whatever level of randomness they're comfortable with to spread the load on their servers would be fine.  We're working on deployment practices for a moderately large scale, and the prepackaged crons don't work well for that.  (They are designed for much simpler cases.)

If the 4 minute delay is enough to spread out the load for them, that's fine.  My own thought would be a longer time - with the thought of 60 minutes, and having time zones therefore spread it moderately evenly throughout the day.  But I wouldn't want to roll that directly into renew, as there would be cases where you might run it non-interactively but still expect it to be fairly responsive.

Mostly, it should be good enough to be used in Let's Encrypt's [certbot instruction page](https://certbot.eff.org/instructions).  (Which currently uses 3600 seconds, or one hour.)

**Comment by sydneyli** [comment]
Yep, that makes sense! We originally added the random sleep in order to lessen the load spikes on LE servers.

@schoen, would you like to update Certbot documentation to mention the non-interactive sleep by default?
