### ISSUE TITLE
Better renewal support for short-lived certificates

### ISSUE THREAD

**Issue by mmalone** [certbot/certbot#7291]
I'm working on ACME support for [an open source internal CA](https://github.com/smallstep/certificates) and I'm trying to document best practices for using `certbot` to get certificates.

I'm running into a bit of an issue getting everything wired together -- certbot is tuned for Let's Encrypt's 90 day certs in a couple ways:
* Renewals occur if a certificate is within 30 days of its expiration
* Renewal attempts are scheduled (via cron or systemd timer) to occur every 12 hours
  * Jitter is configured to spread load across those 12 hours
  * It appears as if [additional jitter is hard-coded](https://github.com/certbot/certbot/blob/v0.36.0/certbot/renewal.py#L435-L442) (up to 8 minutes)

By default our CA issues shorter-lived certificates with 24 hour lifetimes. Accommodating this requires re-tuning, which seems harder than necessary.

### Adjusting when certificates are renewed

To adjust when certificates are renewed right now you need to manually edit a per-domain renewal configuration and add something like `renew_before_expiry = 8 hours`. This works. But it seems like this could be captured as a command-line flag during certificate issuance and stored in that config file automatically, which would save a lot of hassle.

### Adjusting frequency of renewal attempts

This is harder. The default cron timing, every 12 hours, is fine for Let's Encrypt. I can't think of any good way to make this configurable so this might just require a manual edit.

Technically, 12 hours would work for 24 hour lifetimes except that, ideally, it'd be nice to have multiple renewal attempts ahead of expiry for some resilience in case of CA downtime. Maybe there's a middle ground with a default of 4 or 6 hours instead of 12, considering most runs will be quick no-ops.

The [hard-coded jitter](https://github.com/certbot/certbot/blob/v0.36.0/certbot/renewal.py#L435-L442) is a bit more concerning. It might break things by surprise if you pushed cert lifetimes to something extremely short. I'm not sure when this conditional is triggered, though, so maybe it's a non-issue. Just figured I'd bring it to everyone's attention.

**Comment by sydneyli** [comment]
I believe the hard-coded sleep can be removed by disabling the flag `random_sleep_on_renew`. As of #7290, we still need to document that it exists somewhere! It is triggered on non-interactive runs of `certbot`, like during an automated cronjob.

Having `renew_before_expiry` settable at the command-line makes sense to me!

**Comment by mmalone** [comment]
Awesome! Where does `random_sleep_on_renew` go? Is it a command line flag or does it go in a global or per-domain config somewhere?

And to clarify "non-interactive mode" means "`-n` or `--non-interactive` was passed", right? It's explicit. `certbot` doesn't do anything fancy that might trip people up -- like look at whether it's attached to a tty -- and go into "non-interactive mode" without being asked to?

**Comment by sydneyli** [comment]
The flag to pass should be `--no-random-sleep-on-renew`. Huh, it looks like it's suppressed in the [`help` output](https://github.com/certbot/certbot/blob/20b595bc9ee271e638cef3d6c7f5e7d1d9864835/certbot/cli.py#L1221).

> certbot doesn't do anything fancy that might trip people up -- like look at whether it's attached to a tty -- and go into "non-interactive mode" without being asked to?

It does! Here is the line:

https://github.com/certbot/certbot/blob/v0.36.0/certbot/renewal.py#L405

And the discussion about the feature: #6391
