### ISSUE TITLE
/usr/bin/certbot: line 3: __requires__: command not found  Ubuntu 18.04.02 Server Edition

### ISSUE THREAD

**Issue by marcoippolito** [certbot/certbot#7292]
In Ubuntu 18.04.02 Server Edition withnginx version: nginx/1.14.0 (Ubuntu) I need to automatically renew certbot's certifications. 

sudo nano /etc/bin/certbot :  

     #!/usr/bin/python3
     # EASY-INSTALL-ENTRY-SCRIPT: 'certbot==0.23.0','console_scripts','certbot'
      __requires__ = 'certbot==0.23.0'
    import re
    import sys
    from pkg_resources import load_entry_point
    if __name__ == '__main__':
        sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
        sys.exit(
            load_entry_point('certbot==0.23.0', 'console_scripts', 'certbot')()
        )

      marco@pc:/etc/systemd/system$ systemctl status certbot-renewal
      ● certbot-renewal.service - Certbot Renewal
         Loaded: loaded (/etc/systemd/system/certbot-renewal.service; static; vendor preset: enabled)
         Active: failed (Result: exit-code) since Sat 2019-08-03 11:22:01 CEST; 1h 43min ago
       Main PID: 1857 (code=exited, status=2)
 
      Aug 03 11:22:01 pc systemd[1]: Started Certbot Renewal.
      Aug 03 11:22:01 pc bash[1857]: /usr/bin/certbot: line 3: __requires__: command not found
      Aug 03 11:22:01 pc bash[1857]: /usr/bin/certbot: line 4: import: command not found
      Aug 03 11:22:01 pc bash[1857]: /usr/bin/certbot: line 5: import: command not found
      Aug 03 11:22:01 pc bash[1857]: from: can't read /var/mail/pkg_resources
      Aug 03 11:22:01 pc bash[1857]: /usr/bin/certbot: line 9: syntax error near unexpected token `('
      Aug 03 11:22:01 pc bash[1857]: /usr/bin/certbot: line 9: `    sys.argv[0] = re.sub(r'(-script\.pyw?|
      \.exe)?$', '', sys.argv[0])'
      Aug 03 11:22:01 pc systemd[1]: certbot-renewal.service: Main process exited, code=exited, 
      status=2/INVALIDARGUMENT
      Aug 03 11:22:01 pc systemd[1]: certbot-renewal.service: Failed with result 'exit-code'.

    marco@pc:/usr/bin$ sudo certbot renew --dry-run
    Saving debug log to /var/log/letsencrypt/letsencrypt.log
    -------------------------------------------------------------------------------
    ** DRY RUN: simulating 'certbot renew' close to cert expiry
    **          (The test certificates below have not been saved.)
    No renewals were attempted.
    ** DRY RUN: simulating 'certbot renew' close to cert expiry
    **          (The test certificates above have not been saved.)
    -------------------------------------------------------------------------------

How to solve the problem?
Looking forward to your kind help.
Marco

**Comment by ohemorange** [comment]
Hey @marcoippolito! Please first try asking for help at https://community.letsencrypt.org/. There is a much larger community there of people familiar with the project who will be able to more quickly answer your questions.
