### ISSUE TITLE
Certbot Package for Ubuntu 14.04 in PPA

### ISSUE THREAD

**Issue by jasonrogena** [certbot/certbot#7296]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 14.04.6

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager

## I ran this command and it produced this output:
```
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:certbot/certbot
sudo apt-get update
sudo apt-get install certbot
```

## Certbot's behavior differed from what I expected because:
It seems the `certbot` package is no longer being distributed for Ubuntu 14.04 in the `certbot/certbot` PPA. I just wanted to confirm that this is true.

## Here is further proof that, at least for me, the package no longer exists
```
grep ^Package /var/lib/apt/lists/ppa.launchpad.net_certbot_certbot_ubuntu_dists_trusty_main_binary-amd64_Packages 
```

outputs:
```
Package: python-cookies
Package: python3-cookies
```

**Comment by alexzorin** [comment]
> It seems the `certbot` package is no longer being distributed for Ubuntu 14.04 in the `certbot/certbot` PPA

That's right, (https://github.com/certbot/certbot/issues/7183), it was dropped because Ubuntu 14.04 itself stopped receiving updates (except for paid Canonical customers) in April 2019.

**Comment by bmw** [comment]
I think alexzorin answered the question here so I'm closing this issue.
