### ISSUE TITLE
Nightly AppVeyor builds

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7304]
Currently, we're just running tests on PRs for AppVeyor. When we start shipping on Windows though, I think it's important that we make sure the `master` branch passes all tests on AppVeyor before doing a release. Without this, I think it's possible for two PRs to land which in combination break Windows support and we wouldn't know about it until running tests on another PR.

If possible, I think we should set up something similar to what we have with Travis which is the full test suite on `master` is run nightly and failures are reported to Mattermost/IRC.

**Comment by ohemorange** [comment]
We're no longer using AppVeyor, and have nightly tests in Azure.
