### ISSUE TITLE
Fix pywin32 dependency in setup.py

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7305]
As of writing this issue, our code in `setup.py` to declare a dependency on `pywin32` on Windows looks like this.
```
# Add pywin32 on Windows platforms to handle low-level system calls.
# This dependency needs to be added using environment markers to avoid its installation on Linux.
# However environment markers are supported only with setuptools >= 36.2.
# So this dependency is not added for old Linux distributions with old setuptools,
# in order to allow these systems to build certbot from sources.
if StrictVersion(setuptools_version) >= StrictVersion('36.2'):
    install_requires.append("pywin32 ; sys_platform == 'win32'")
elif 'bdist_wheel' in sys.argv[1:]:
    raise RuntimeError('Error, you are trying to build certbot wheels using an old version '
                       'of setuptools. Version 36.2+ of setuptools is required.')
```
I think this code is insufficient though as a dependency on pywin32 will not be added when not using a prebuilt wheel with an old version of setuptools on Windows.

To fix this, I think we can just add to the bottom of this code:
```
elif os.name == 'nt':
    install_requires.append("pywin32")
```
Alternatively, we could error out when we're run with an old version of setuptools on Windows, however, we cannot do this in general because of ancient distros where we're still seeing updates.

What do you think @erikrose?

**Comment by adferrand** [comment]
OK I would add something here. We see that tracking down all flavors of dependency versions in various Linux distributions that need to be supported implies a tremendous amount of work and tests.

I definitely not want to impose the same situation for Windows. There will be a unique flavor of depency versions for a given version of Certbot for Windows. And if we need a recent version of setuptools to make things work, so be it.

I said it before, but I say it again here: the Unix philosophy of "one tool, one purpose" is not for Windows. On that platform, it takes dozens of gigabytes to have a system working, and each program just vendors every library it needs.

The design I have in mind (and in PR) for the Certbot installer follows that: it does not need an existing Python distribution. It install its own, for the specific purpose of Certbot, and all required dependencies as a specific dist-packages for it.

This approach will allow us to focus the user acceptance tests on unique environment settled for the installer on the next version of Certbot to release. Like on Linux, installing from `pip` is not officially supported. Upgrading, as supported by the NSIST installers, and similarly to certbot-auto, just wipe out everything and create a new environment.

**Comment by bmw** [comment]
Yep. I still agree with all of that.

I just personally think that as an easy wishlist item we can more accurately represent the requirements in the package here either by erroring out in this case or correctly adding the dependency. I think the benefit of doing this is it prevents the problem from going unchecked to hit us or our users later in execution.

**Comment by adferrand** [comment]
OK, I just wanted to be sure that we are on the same page, and that the efforts done to increase certbot compatibility does not become an unnecessary commitment. Quite similarly to the unpinned tests we are doing in nightly tests, I agree with you that it is certainly appreciable for developers that would like to reuse the work done here on more exotic configurations.

**Comment by erikrose** [comment]
@bmw The way you have it above, you're testing `os.name` in setup.py, which is going to return the OS of the machine that *builds* the package. But I think we can do something that'll work. Packages like [cryptography](https://pypi.org/project/cryptography/#files) build Windows-specific wheels. If we do that, we can stick Windows-specific requirements in those. And, of course, anybody who pulls the sdist on Windows will execute any conditionals we care to stick in setup.py.

**Comment by bmw** [comment]
I don't think I explained the problem very well. Our current code is:
```
# Add pywin32 on Windows platforms to handle low-level system calls.
# This dependency needs to be added using environment markers to avoid its installation on Linux.
# However environment markers are supported only with setuptools >= 36.2.
# So this dependency is not added for old Linux distributions with old setuptools,
# in order to allow these systems to build certbot from sources.
if StrictVersion(setuptools_version) >= StrictVersion('36.2'):
    install_requires.append("pywin32 ; sys_platform == 'win32'")
elif 'bdist_wheel' in sys.argv[1:]:
    raise RuntimeError('Error, you are trying to build certbot wheels using an old version '
                       'of setuptools. Version 36.2+ of setuptools is required.')
```
which I believe results in correct, universal wheels when a new enough version of pip/setuptools/wheel is used. I think this is nice because we can stick with a single wheel.

This approach does nothing to protect against the case of trying to run the sdist on Windows with an old version of setuptools though. This is a minor concern, but this was the reason I created this issue. I think we could catch/fix the problem early rather than failing later when trying to run Certbot.

To fix this, I proposed adding a final condition to that code of:
```
elif os.name == 'nt':
    install_requires.append("pywin32")
```
This will result in this dependency being added when running the sdist on Windows with an old version of setuptools.

From my initial post I also said:

> Alternatively, we could error out when we're run with an old version of setuptools on Windows, however, we cannot do this in general because of ancient distros where we're still seeing updates.

**Comment by erikrose** [comment]
Ah, thanks. That helps. Also, I haven't got the project loaded into my head very well, and I apologize for that.

I think that's a fine idea. Because it's in an `elif` and because we check for bdist_wheel above, it won't kick in (and try to make Linux users install pywin32) if somebody tries to build a universal wheel on a Windows box.

**Comment by bmw** [comment]
No problem!

Thanks for the sanity check. I opened #7384 to make this change.
