### ISSUE TITLE
Why does our tests on RHEL 7 fail to install packages sometimes

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7319]
A log of this is 
[6_RHEL7 (1).log](https://github.com/certbot/certbot/files/3484202/6_RHEL7.1.log). We've seen it fail at this spot multiple times but it's not consistently reproducible.

If I'm reading yum's output right, it's not failing to download the packages, it's failing to install them. I believe our RHEL 7 AMI hasn't been updated in a very long time. Maybe simply updating it will solve the problem?

**Comment by joohoi** [comment]
I'm thinking that this might be related to [Fabric](http://www.fabfile.org/) that's apparently used for provisioning in a way or another, by looking at the stacktrace. Reading through [yum man pages](http://man7.org/linux/man-pages/man8/yum.8.html), the return code `-1` isn't listed anywhere there either (not that it would not return it).

**Comment by bmw** [comment]
Reading these logfiles from our test farm tests is a bit insane, but our code uses fabric for running the tests on the EC2 instances which is where that traceback comes from. I'm not sure if -1 is the return code fabric got from running the test script on the remote instance. Hopefully that error message is reliable and gives a little more info to help us track down the problem.
