### ISSUE TITLE
Test for other Python 3.8 problems after #7106 is resolved

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7333]
~~I think there are some such as the [use collections.Mapping here](https://github.com/certbot/certbot/blob/2911eda3bda95340b12d6deb096e7c15bdd5f44b/certbot/plugins/disco.py#L183) instead of `collections.abc.Mapping`.~~

There may not be any, but I had trouble getting all of our tests to pass as expected as described at https://github.com/certbot/certbot/issues/7333#issuecomment-525926864.

To run tests in Travis, you can probably make use of the [3.8-dev or nightly Python builds offered by Travis](https://docs.travis-ci.com/user/languages/python/#python-37-and-higher).

**Comment by bmw** [comment]
Makes sense.

I tried to run tests on Python 3.8 so I could identify the remaining individual problems with our support there outside of not using `collections.abc` as described in my initial post in case you or anyone else wanted to take a crack at fixing them.

The good news is there may not be any problems in Certbot since #7337 was fixed. Apparently removing the ability to access ABCs directly on the `collections` module was [pushed back to Python 3.9](https://github.com/python/cpython/pull/13409) and [our unit tests are passing on Python 3.8](https://travis-ci.com/certbot/certbot/jobs/229075761).

The bad news is that I can't quickly completely verify that there are no problems because our [integration tests are failing on Python 3.8 due to a giant drop in code coverage](https://travis-ci.com/certbot/certbot/builds/124983353). A lot of our test framework also uses Python so it's probably just a problem there, but I can't be sure without further digging.

**Comment by bmw** [comment]
The current status of this is we need to figure out what's causing our test failures and fix them. I don't think we can really claim to support Python 3.8 without all our tests passing on the system.

**Comment by ohemorange** [comment]
After the current run adding `--append` to `combine` I'm going to try this: https://github.com/pytest-dev/pytest-cov/commit/24ba975fdd1b620f4b7289d4f3564e7c5ddc9697

**Comment by ohemorange** [comment]
Specifically intrigued by the line [here](https://coverage.readthedocs.io/en/coverage-4.4.2/cmd.html#data-file): "This behavior was the default before version 4.2."

**Comment by ohemorange** [comment]
Pretty sure this doesn't apply to us but flagging it anyway: "If the different machines run your code from different places in their file systems, coverage.py won’t know how to combine the data." again from [here](https://coverage.readthedocs.io/en/coverage-4.4.2/cmd.html#data-file).

**Comment by ohemorange** [comment]
Another interesting tidbit to try: "For parallel runs we need to set some dependencies and have an extra report env like so"

https://github.com/pytest-dev/pytest-cov/commit/24ba975fdd1b620f4b7289d4f3564e7c5ddc9697

**Comment by ohemorange** [comment]
I have to run, but looks like [tests are now passing](https://travis-ci.com/certbot/certbot/builds/126304545). Next step is adding the changes to `dev_constraints` and `tox.ini` to get tests working, and then adding the tests themselves to the Travis matrix. Do we want them all added as `not-on-master` as they are in the current matrix on `test-py38`?

@bmw: we can probably remove the `-ra` flag on `pytest` right? that was just to get more information during testing"
