### ISSUE TITLE
Disable TLS session tickets in Apache

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7350]
With the resolution of #7322, we now seem to have a way to do this safely. The solution is not only to check that Apache supports disabling TLS session tickets, but also to only do so if the version of OpenSSL used by Apache is 1.0.2l or greater.

The best way to get the version of OpenSSL used by Apache (which may not be the same version of OpenSSL output by running `openssl version` or checking the version of OpenSSL used by Python) is a bit of an open question. The ideas that have been proposed to me that seem viable are:

1. Parsing openssl version from apache.  Potential problems here are needing to figure out the path to the logfile because it's configurable and making sure that the version number is in the logfile when we look. Could we potentially read the file before it was written? What if these files are configured with something like logrotate? Might the `openssl` version no longer be in the log?
2. Finding the `mod_ssl` shared object file and seeing what version of ~Apache~OpenSSL it links to. Potential issues I see here are finding the path to the module as it's configurable, reliably figuring out what it's linked to (do some systems statically link while others dynamically link?), and if it's possible, how to do this if any systems include `mod_ssl` in Apache as a built in module rather than one that is loaded externally.

For error handling, I talked about this with people and right now we're thinking that:

1. If for some reason we fail to determine the OpenSSL version, we should keep session tickets at their default of enabled. Doing anything else isn't worth breaking people's servers.
2. This could potentially be done in a later PR, but we should set up test farm tests that check that we can determine the OpenSSL version used by Apache on all systems the tests are run on.

The combination of these two things should stop us from breaking people's servers if something changes around us detecting these versions and will let us know if this detection is broken on a major system that we support.

@adferrand, you're welcome to pick this issue up if you find the spare time.

**Comment by nmxcgeo** [comment]
Hi, I would like to push this as I think, it should be a priority to configure up-to-date crypto. But another point to consider is that at the moment certbot is configuring nginx in a different way than apache because its plugin has already been upgraded. This is an inconsistency that will be hard to spot and explain if anyone gets problems with it.

**Comment by bmw** [comment]
I don't think it's fair to say we're not prioritizing pushing up-to-date crypto. In case you're not familiar, we landed this feature last month but had to revert it due to a bug in old versions of OpenSSL. We are now working on this again and trying to work around this OpenSSL bug, but doing this work is not trivial due to some of the complications described in my initial post. This issue is assigned to someone, being actively worked on, and is part of our milestone for our 0.39.0 which is scheduled to be released in the beginning of October.

**Comment by bmw** [comment]
Awesome!

To clarify, my comment at https://github.com/certbot/certbot/issues/7204#issuecomment-571838185 partially resolves that issue, but not this one.

**Comment by ohemorange** [comment]
Tentative plan based on preliminary research:

1. Check for custom location set by a directive such as `LoadModule ssl_module /usr/lib/httpd/modules/mod_ssl.so`
2. If no directive found, check the system's `modules` folder for `mod_ssl.so` (for example, `/usr/lib/apache2/modules/`)
3. Instead of checking what OpenSSL version `mod_ssl.so` is linked to (and therefore dealing with potential static vs dynamic problems), grep in the `.so` as shown here: https://unix.stackexchange.com/questions/191213/how-to-check-mod-ssl-so-version TODO: check that this works for older versions of Apache

On Ubuntu, built-in modules are placed in the same `modules` folder that user-installed modules are placed in. TODO: confirm this is true for other systems.

**Comment by bmw** [comment]
Awesome! I'm excited to have made a little progress here. Thanks for looking into it!

The two initial thoughts/questions I personally have based on that are:

1. Did you consider trying to read Apache's logs and if so do you like this approach better?
2. I think it may be hard/impossible for us to get this right 100% of the time. If that's correct, I think searching for `LoadModule ssl_module` might get us most of the way there and I wonder if we might be able to reasonably skip item (2) at least in the initial version. This requires testing, but I think all of the major distros will have a `LoadModule` directive.

**Comment by ohemorange** [comment]
> Did you consider trying to read Apache's logs and if so do you like this approach better?

Yes, I did. I swear I recall a conversation about some of the challenges there a while back, but can't seem to find it now, but your discussion above is a good summary of why I decided to focus on the second option.

> 1. Potential problems here are needing to figure out the path to the logfile because it's configurable

This is probably exactly as hard as checking for the LoadModule directive, though maybe slightly harder if there are different types of directives that can redirect the logs.

 > and making sure that the version number is in the logfile when we look. Could we potentially read the file before it was written? What if these files are configured with something like logrotate? Might the openssl version no longer be in the log?

These are the parts I was more worried about. What's nice about NGINX is that it writes out the version number every time it runs, but I remember that not being the case for Apache, although I would love to be misremembering here. I don't know of a simple, non-hacky way to read the file before it's written. I'm happy to go off and learn about what setting log locations looks like in Apache if the reason you're asking is because you have a sense that this general approach is more viable; I basically focused on the second because my intuition went the other way. 

> 2. I think it may be hard/impossible for us to get this right 100% of the time.

Why do you think this? I think the only case where we couldn't figure it out is in cases where someone has a custom compilation of the module that doesn't have the OpenSSL version number in it. To be clear, I'm talking about searching through the loaded apache config tree, not the filesystem or anything like that.

> This requires testing, but I think all of the major distros will have a LoadModule directive.

Oh, that's even nicer! I'd assumed by the "how to do this if any systems include mod_ssl in Apache as a built in module" comment that systems doing so would be relatively common, but that's probably reasonable enough to check.

**Comment by bmw** [comment]
> I'm happy to go off and learn about what setting log locations looks like in Apache if the reason you're asking is because you have a sense that this general approach is more viable; I basically focused on the second because my intuition went the other way.

I don't think that's necessary. My intuition is the same as yours. I was just curious if you had any new research on the logfile approach to share. If we think parsing the shared object file will work, we may as well do that.

> > 2. I think it may be hard/impossible for us to get this right 100% of the time.
>
> Why do you think this?

I haven't looked into any of these problems to know how much they'll affect us, if at all, but a few concerns I have are:

1. Can the `.so` file be either statically or dynamically linked to OpenSSL and will our approach work in either case?
2. Can `mod_ssl` be compiled inside the Apache binary like other modules can be? If so, is anyone doing this and if they are, can we still figure the OpenSSL version?
3. Might a compiler strip the symbols we're looking for from the shared object file?

> > This requires testing, but I think all of the major distros will have a LoadModule directive.
>
> Oh, that's even nicer! I'd assumed by the "how to do this if any systems include mod_ssl in Apache as a built in module" comment that systems doing so would be relatively common, but that's probably reasonable enough to check.

I'm not aware of anyone doing this and systems like Debian, CentOS, and Ubuntu are not (at least by default). I know it's possible to be done with modules in general though.

On Debian based systems, you can see the list of modules built into Apache by running a command like `sudo apache2ctl -t -D DUMP_MODULES | grep static`. I haven't really looked into this, but my understanding is that the code for these modules is literally inside the Apache executable and not loaded from any other files on disk.

**Comment by ohemorange** [comment]
> 1. Can the `.so` file be either statically or dynamically linked to OpenSSL and will our approach work in either case?

The former is a good question. I suspect it's usually statically linked (given that searching inside the `.so` works), but in cases where it's not, we should still be able to find the file it's linked to and search inside that. Hopefully it's always the former, but if it's the latter it's still doable. 

> 2. Can `mod_ssl` be compiled inside the Apache binary like other modules can be? If so, is anyone doing this and if they are, can we still figure the OpenSSL version?

It could theoretically be, if you did a custom build, but I haven't yet heard of anyone doing this. The (I realize now very unclear) todo above is referring to checking on this in various systems. If someone is, the same approach will work, we'll just grep in the Apache executable.

> 3. Might a compiler strip the symbols we're looking for from the shared object file?

Almost certainly not. It's a part of the OpenSSL API which is called to write the OpenSSL version out to logs, so as long as the executable plans to continue doing that, it's going to need it in there.

>  I haven't really looked into this, but my understanding is that the code for these modules is literally inside the Apache executable and not loaded from any other files on disk.

Yup, that seems to be correct, based on the strings available in the Apache executable, and also my understanding of what "statically linked" means. As I mentioned, I plan to check if anyone's doing this, but so far I haven't seen it.

**Comment by bmw** [comment]
That sounds good to me!

I personally think the cases I mentioned give us a fair bit of complexity in trying to handle this reliably on all systems that theoretically could exist, but I'd bet in practice just searching for `LoadModule` and looking at the `.so` file at that path will (almost) always work. I don't immediately know how we'd find the version of OpenSSL the `.so` file dynamically links to (if that's even possible for the `.so` file to do), but you're probably right that handling those edge cases if we want to may not actually be that bad either.

I also didn't realize the string we were searching for is actually part of the OpenSSL API. That helps a lot.

One final thought: On Debian based systems, we will enable mod_ssl automatically if it's not already enabled. See https://github.com/certbot/certbot/blob/2338ab36fd70e9d65eeafb8e22cd05b3ac879e3f/certbot-apache/certbot_apache/_internal/configurator.py#L1114

I bring this up so we can make sure we search for the `LoadModule` directive after we know mod_ssl is enabled in the Apache config tree.

**Comment by ohemorange** [comment]
On enabling mod_ssl automatically in debian based systems if it's not already enabled:

Currently, `install_ssl_options_conf` (which involves searching or having previously searched for `LoadModule`) is called during `prepare`, but `enable_mod` is called during `_deploy_cert` (after prepare). Either we can move one of these, or re-call `install_ssl_options_conf` after calling `enable_mod`. Not being very familiar with the configurator code, I don't have a sense of which one of these is most preferable given existing conventions in the plugin, thoughts?

**Comment by bmw** [comment]
I'd recommend calling `install_ssl_options_conf` again after `enable_mod`. We could maybe only conditionally call `install_ssl_options_conf` during `prepare` if `mod_ssl` is available if we wanted and it makes sense with the implementation.

I don't think we should move calling `enable_mod` to `prepare` because I think it significantly complicates properly disabling that module if something goes wrong (or if the user was just using Apache as an authenticator but not an installer).

We could completely move calling `install_ssl_options_conf` to after `enable_mod`, but I think the benefits of also calling it during `prepare` are:

1. `prepare` is called more often meaning that the TLS config will be more quickly updated thanks to Joona's AutoHSTS and OCSP prefetching enhancements.
2. After we install the first certificate, the Apache plugin's behavior will stay consistent with nginx in that the file is updated during the call to `prepare`. I've made use of this fact a few times by telling people who just wanted to update the file to run `certbot plugins --prepare`.

**Comment by ohemorange** [comment]
Actually, I'm no longer worried about this, since we only call `enable_mod` if `ssl_module` wasn't previously available, in which case OpenSSL wouldn't have been set.

**Comment by lyda** [comment]
Is it possible for the apache SSL conf include file could stay in this location now?  Moving it tends to break things...

**Comment by bmw** [comment]
We make no promises about the location of this file, especially if you're now reaching into `certbot_apache/_internal/tls_configs` to access the file directly. If you would like us to consider changing this, please open a new issue describing your use case.
