### ISSUE TITLE
How to renew SSL certificates in linux server using amazon ec2 instance?

### ISSUE THREAD

**Issue by shelza1305** [certbot/certbot#7362]
when i use this command to renew ssl certifcate:

      sudo ./certbot-auto certonly --debug --webroot -w ~/www/ -d doyogame.org -d www.doyogame.org —no-bootstrap

Then error comes like this:

./certbot-auto --debug renew

Requesting to rerun ./certbot-auto with root privileges…
Bootstrapping dependencies for Amazon… (you can skip this with --no-bootstrap)
yum is /usr/bin/yum
To use Certbot, packages from the EPEL repository need to be installed.
Enabling the EPEL repository in 1 second…
Loaded plugins: priorities, update-motd, upgrade-helper
amzn-main | 2.1 kB 00:00
amzn-updates | 2.5 kB 00:00
1065 packages excluded due to repository priority protections
Package epel-release-6-8.9.amzn1.noarch already installed and latest version
Nothing to do
yum is hashed (/usr/bin/yum)
To use Certbot, packages from the EPEL repository need to be installed.
Enabling the EPEL repository in 1 second…
Loaded plugins: priorities, update-motd, upgrade-helper
1065 packages excluded due to repository priority protections
Package epel-release-6-8.9.amzn1.noarch already installed and latest version
Nothing to do
Loaded plugins: priorities, update-motd, upgrade-helper
1065 packages excluded due to repository priority protections
Package gcc-4.8.5-1.22.amzn1.noarch already installed and latest version
Package augeas-libs-1.0.0-5.7.amzn1.x86_64 already installed and latest version
Package 1:openssl-1.0.2k-16.150.amzn1.x86_64 already installed and latest version
Package 1:openssl-devel-1.0.2k-16.150.amzn1.x86_64 already installed and latest version
Package libffi-devel-3.0.13-16.5.amzn1.x86_64 already installed and latest version
Package system-rpm-config-9.0.3-42.28.amzn1.noarch already installed and latest version
Package ca-certificates-2018.2.22-65.1.20.amzn1.noarch already installed and latest version
Package python27-devel-2.7.16-1.129.amzn1.x86_64 already installed and latest version
Package python27-virtualenv-15.1.0-1.14.amzn1.noarch already installed and latest version
Package python27-tools-2.7.16-1.129.amzn1.x86_64 already installed and latest version
Package python27-pip-9.0.3-1.26.amzn1.noarch already installed and latest version
Nothing to do
Creating virtual environment…
Traceback (most recent call last):
File “”, line 27, in 
File “”, line 19, in create_venv
File “/usr/lib64/python2.7/subprocess.py”, line 185, in check_call
retcode = call(*popenargs, **kwargs)
File “/usr/lib64/python2.7/subprocess.py”, line 172, in call
return Popen(*popenargs, **kwargs).wait()
File “/usr/lib64/python2.7/subprocess.py”, line 394, in init
errread, errwrite)
File “/usr/lib64/python2.7/subprocess.py”, line 1047, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by sydneyli** [comment]
Thanks for your interest in the project! We don't officially support Amazon Linux, but some advice on getting it working can be found at #2544. If you're still having trouble, we recommend asking for help on the [Let's Encrypt Community Forums](https://community.letsencrypt.org/c/help), where there's a larger audience of people familiar with the project. You'll get much faster help there!

I'm closing this issue for now.
