### ISSUE TITLE
Disable InsecureRequestWarning for the SimpleHTTP.simple_verify

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#737]
This warning is being spit onto STDOUT and it confuses people, c.f. #734.

**Comment by Athanasius** [comment]
Oh yes, please either squelch this warning, or implement certifi usage as per https://urllib3.readthedocs.org/en/latest/security.html#insecurerequestwarning

**Comment by bmw** [comment]
Would be fixed in #2505.

**Comment by bmw** [comment]
We don't use this method anymore.
