### ISSUE TITLE
Make Certbot logging more systematic and flexible

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#7373]
A user request from the forum (https://community.letsencrypt.org/t/letsencrypt-log/101556/9):

> i) I recommend that EVERY log entry include the name of the certificate to which it pertains, ie that the current “cerbot.cli” or “certbot.renewal” (becomes more specific); when possible/applicable. This will enable/ease log post-processing and administrative reporting.

> (further)
> ii) I recommend the inclusion of a switch in the (/etc/letsencrypt/)cli.ini configuration file to allow administrators to select a logging level, ie to be able to exclude DEBUG communications. This will reduce the volume of log-entries (a somewhat weak justification!), and improve readability for more mature installations. (cli.ini should be installed with the ‘maximum setting’ and alteration be a user-choice and require deliberate (SysAdmin) user-action).

> NB recommendation (i) is likely a more appropriate solution (in this scenario) than, but may have the effect of reducing use-cases for the “failure hook” proposal.

**Comment by kghbln** [comment]
I have a similar request. In stead of digging trough server logs I would like to get only notified about failures. 

Currently I run `certbot renew` via cron and every run I get a notification via e-mail that no renewals were attempted. Instead I would only like to get a notification as soon as "Congratulations, all renewals succeeded. The following certs have been renewed:" is part of the logging and more importantly if the process failed for some reason (yes this happens once in a while for a number of different reasons.)

Some flags like e.g.  
- `--verbose-on-renewal`
- `--verbose-on-failiure`
would help a lot.

Currently I just filter the e-mails client side which contain the "No renewals were attempted" message.

**Comment by kghbln** [comment]
Is still believe this will be a very useful feature for operations. Looked at the current docs but did not find an implementation like this.

**Comment by bcdady** [comment]
I concur this would be a very beneficial improvement.

Is there currently any (undocumented) means of configuring the logging level, such as in the cli.ini file?
