### ISSUE TITLE
Cannot import name ssl_match_hostname on openSUSE Tumbleweed despite the package being installed

### ISSUE THREAD

**Issue by fililip** [certbot/certbot#7381]
## My operating system is (include version):
openSUSE Tumbleweed 20190917 (Linux 5.2.14)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager

## I ran this command and it produced this output:
sudo certbot renew
```
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.38.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 17, in <module>
    from certbot import account
  File "/usr/lib/python2.7/site-packages/certbot/account.py", line 17, in <module>
    from acme import messages
  File "/usr/lib/python2.7/site-packages/acme/messages.py", line 11, in <module>
    from acme import challenges
  File "/usr/lib/python2.7/site-packages/acme/challenges.py", line 12, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python2.7/site-packages/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python2.7/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
  File "/usr/lib/python2.7/site-packages/urllib3/packages/__init__.py", line 3, in <module>
    from . import ssl_match_hostname
ImportError: cannot import name ssl_match_hostname
```

## Certbot's behavior differed from what I expected because:
I cannot use Certbot at all, not even check its version.

**Comment by ohemorange** [comment]
As mentioned on the [community forum](https://community.letsencrypt.org/t/cannot-import-ssl-match-hostname/102128), looks like this is the same bug as https://bugzilla.opensuse.org/show_bug.cgi?id=1143069. I'll see if our openSUSE maintainer knows anything about this.

**Comment by ohemorange** [comment]
@fililip, any chance you could jump into the opensuse bug to help the maintainers there repro the issue?

**Comment by R-Adrian** [comment]
**CentOS 7 has the same bug with the recent epel packages...** 
```
yum[19841]: Updated: python2-acme-1.0.0-1.el7.noarch
yum[19841]: Updated: python2-certbot-1.0.0-1.el7.noarch
yum[19841]: Updated: certbot-1.0.0-1.el7.noarch
yum[19841]: Updated: python2-certbot-apache-1.0.0-1.el7.noarch
yum[19841]: Installed: python2-pyparsing-2.4.6-1.el7.noarch
yum[19841]: Erased: pyparsing-2.4.0-1.el7.noarch
```
I had to purge the epel RPMs and install certbot directly from pip3 (Python 3.6), and it works again:
```
# ln -s /usr/local/bin/certbot /usr/bin/certbot
# pip3 install --upgrade pip certbot acme PyOpenSSL six urllib3 idna certifi pycparser parsedatetime cryptography
```

imho certbot should already be marked everywhere as not compatible with Python 2 anymore, but somehow is still beind distributed packaged as a python v2 app. :(

**Comment by bmw** [comment]
@R-Adrian, if you can reproduce this problem starting with a common base image like the CentOS 7 Docker image, instructions on how to do so would be useful!

**Comment by Comsolvia** [comment]
> **CentOS 7 has the same bug with the recent epel packages...**
> 
> ```
> yum[19841]: Updated: python2-acme-1.0.0-1.el7.noarch
> yum[19841]: Updated: python2-certbot-1.0.0-1.el7.noarch
> yum[19841]: Updated: certbot-1.0.0-1.el7.noarch
> yum[19841]: Updated: python2-certbot-apache-1.0.0-1.el7.noarch
> yum[19841]: Installed: python2-pyparsing-2.4.6-1.el7.noarch
> yum[19841]: Erased: pyparsing-2.4.0-1.el7.noarch
> ```
> 
> I had to purge the epel RPMs and install certbot directly from pip3 (Python 3.6), and it works again:
> 
> ```
> # ln -s /usr/local/bin/certbot /usr/bin/certbot
> # pip3 install --upgrade pip certbot acme PyOpenSSL six urllib3 idna certifi pycparser parsedatetime cryptography
> ```
> 
> ~imho certbot should already be marked everywhere as not compatible with Python 2 anymore, but somehow it is still being distributed and packaged as a python v2 app. :(~
> 
> **edit:** seems that this error only happens if python3 is also installed alongside python2. I just tested epel's certbot on another CentOS 7 system that has no python3 packages installed and it works.
> So... i think this only happens in a mixed environment, when both python2 and python3 are installed.

Same here, we're using CentOS 7 and are getting the same errors.
However I',m not sure we have Python 3 installed, `python --version` reports 2.7.5. `rpm -qa | grep python` reports some python packages with version 3, like _python-backports-ssl_match_hostname-3.5.0.1-1.el7.noarch_ - Maybe that is what causes this...
