### ISSUE TITLE
Apache plugin doesn't respect custom server root

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7385]
One of the flags accepted by the Apache plugin is `--apache-server-root` which allows the user to specify a custom path to their Apache configuration. This setting is used in some places inside the Apache plugin, but I don't think it's used everywhere it should be.

For instance, when calling `apache2ctl`, the value isn't set. This has the effect of `apache2ctl` using the default server root on the system for things like config tests, restarts, etc. We do this properly in the Nginx plugin. See [config_test](https://github.com/certbot/certbot/blob/e4af1f331979a178b0579bbb21cc24f063e2ab18/certbot-nginx/certbot_nginx/configurator.py#L921-L930) or [nginx_restart](https://github.com/certbot/certbot/blob/e4af1f331979a178b0579bbb21cc24f063e2ab18/certbot-nginx/certbot_nginx/configurator.py#L1177-L1210).

I haven't seen any users complain about this behavior, but I think we should either fully support this feature or remove it entirely. I'm leaning towards the former as a wishlist item but I'm open to either.

One complication here is times when we need to use the init system to interact with Apache, specifying a custom server root may be hard or may not make sense. If we do decide to do it, we may be able to use environment variables like [this](https://github.com/certbot/certbot/blob/b1f3c6f859b3ac8fb2f7df0a3cebd18a6d1d9345/certbot-ci/certbot_integration_tests/apache_tests/apache_config.py#L85) depending on the details of the init script.

@joohoi, what do you think? Anything you disagree with here?

**Comment by joohoi** [comment]
Because of the nature of `apache2ctl` (or `apachectl` depending on the environment), the default paths are often preconfigured by the operating system or the script itself. The main difference here is that the `apache2ctl` script bears a burden of over 20 years of distribution specific modifications to it, and there's many variations of it in different distributions. As an example we had to [submit a bug](https://bugs.gentoo.org/634414) in order to get it to accept _any_ kind of parameters whatsoever. 

There might be value in trying to notify the user to specify `apache2ctl` path when a custom `--apache-server-root` is present, but I feel that in most of the cases this isn't relevant (if the `apache2ctl` is accessible through `$PATH` anyway).

**Comment by bmw** [comment]
Are there any distros other than Fedora (and historically Gentoo) where `apache(2)ctl -d /some/other/path` doesn't work?

What prompted me to create this issue is all the complexity Adrien had to go through in https://github.com/certbot/certbot/pull/7359 to try and make Apache integration tests that did not modify the system it was run on.

**Comment by bmw** [comment]
Another problem area would be the Debian specific scripts like `a2{en,dis}mod`.

As I said in my initial post, I think another option is we just deprecate having a user configurable `--apache-server-root`, but I don't think our current half working support is a good idea.

**Comment by joohoi** [comment]
I agree on somewhat-working combinations not being the best idea. However there are use cases which the current model supports, like custom root installations (or vanilla Apache installation, when built from the source), CentOS installations from SCL or other repos that use non-default paths.

However trying to bend `apache2ctl` to support any kind of server root configuration is in some cases out of our control, and even ín Debian, CentOS and the rest - it sometimes calls (re)starts through `systemd`, which does not accept our custom parameters like `-d /some/other/path` would be. The whole thing unfortunately is a mess.

This far we have been opting to let the operating system decide of the configuration paradigm, and the way to configure Apache through using the OS tools like `a2{en,dis}mod`.

**Comment by bmw** [comment]
That's a good point about the flag still having value in some setups. I'm not super worried about us doing something here now, but I think we could and should do a better job in communicating/working around the limitations here. I didn't realize how bad it was and it was almost impossible for us to write Apache integration tests that didn't make modifications to the default installation.

I agree we can't support it everywhere, but I think we could on most systems through `-d` and the environment variable `APACHE_CONFDIR` which Adrien found that is supported by the Apache scripts on Debian based systems from jessie through sid. As far as I'm aware. it's only RHEL/Fedora where we currently couldn't fully support it.

Do you think it's worth doing that and warning when we can't support it or do you think we should do something else entirely?

**Comment by joohoi** [comment]
I think a warning would be a really good addition. Most of the users that should need to set a non-default server path will find the probably more technical warning message as this actionable (where possible).
