### ISSUE TITLE
Standalone server waits forever to drain clients during shutdown

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#7386]
Originally discovered in [a help thread on the forums](https://community.letsencrypt.org/t/certbot-hangs-on-stopping-server/102450?u=_az).

## My operating system is (include version):
Ubuntu 19.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
    sudo certbot-auto certonly -d certbot.eff.org --standalone --dry-run

and simultaneously in a second terminal:

    nc -vvv localhost 80

Causes an infinite hang until the `nc` client disconnects:

    2019-09-20 19:29:28,932:DEBUG:certbot.error_handler:Calling registered functions
    2019-09-20 19:29:28,932:INFO:certbot.auth_handler:Cleaning up challenges
    2019-09-20 19:29:28,932:DEBUG:certbot.plugins.standalone:Stopping server at :::80...

## Certbot's behavior differed from what I expected because:
The standalone servers should not wait forever for clients to drain. I don't think they should wait at all and instead should just close the server socket. There is no reason to expect further legitimate traffic to the server. 

If a very patient internet crawler happens to hit the port, we need to dispatch of it quickly.

It may be appropriate to also add read and write timeouts to the socket, since it is practically always going to be exposed to the internet.

**Comment by joohoi** [comment]
Thanks for opening the issue. I labeled it as both; bug and a feature request, as it falls between the two.
