### ISSUE TITLE
Config directories _should_ be relative

### ISSUE THREAD

**Issue by kreempuff** [certbot/certbot#7389]
Reviving this https://github.com/certbot/certbot/issues/3953

If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version): 
AWS codebuild docker image

## I installed Certbot with (certbot-auto, OS package manager, pip, etc): 
with pip

## I ran this command and it produced this output:
```

$ certbot certificates

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
No certs found. 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
```

## Certbot's behavior differed from what I expected because:
I can specify the config, log, and working directories as relative directories but they don't affect the config when the full file path changes, such as when Codebuild adds a random id to the full path or more commonly, if I decide to change the directory that certbot runs and stores files for architectural reasons, but want to keep existing certs.

**Comment by kousu** [comment]
I've migrated to https://github.com/acmesh-official/acme.sh on Linux and https://man.openbsd.org/acme-client on BSD. They have much more manageable configurations that don't have this problem.
