### ISSUE TITLE
Drop support for Python 3.4

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7393]
This can only be done after we've released a version printing a deprecation warning.

To do this though, we need to:

- [ ] Remove Python 3.4 from the [classifiers in setup.py](https://github.com/certbot/certbot/blob/8cb57566c0be9fbed6d86316a0afb18e86d9f481/setup.py#L137) for each package.
- [ ] Update the [python_requires value](https://github.com/certbot/certbot/blob/8cb57566c0be9fbed6d86316a0afb18e86d9f481/setup.py#L125) in each packages setup.py file to exclude Python 3.4.
- [x] Update any tests in `.travis.yml` using Python 3.4 to a newer version of Python or delete the test entirely. (Done in #7394)
- [ ] Remove the deprecation warnings added in https://github.com/certbot/certbot/pull/7378.
- [x] Update any files such as [contributing.rst](https://github.com/certbot/certbot/blob/8cb57566c0be9fbed6d86316a0afb18e86d9f481/docs/contributing.rst#notes-on-os-dependencies) or [install.rst](https://github.com/certbot/certbot/blob/8cb57566c0be9fbed6d86316a0afb18e86d9f481/docs/install.rst#id16) to not claim support for Python 3.4. (Done in #7395)

**Comment by TheNavigat** [comment]
If no one is working on this I'd love to have it assigned to me. It has been a while since I last contributed to Certbot and I'd like to ramp up a bit. This looks like a very simple task I can use to ramp up.

**Comment by bmw** [comment]
Hi @TheNavigat!

You're more than welcome to work on this, but I want to flag that the step "Remove the deprecation warnings added in #7378" won't be possible yet and the PR may not be reviewed/merged for a few weeks while we finish the process of migrating people off of Python 3.4. It'd still be useful to have this PR ready though!

**Comment by TheNavigat** [comment]
Hey @bmw,

I think I should be able to break down the PR into multiple ones. We can start by a PR that drops testing for Python 3.4, followed by another that updates documentation, followed by another that drops support. The order of merging might change, of course.

What do you think?

**Comment by bmw** [comment]
Splitting the work into separate PRs sounds fine to me!

Also, in case you stopped by #letsencrypt-dev in IRC and found it empty, we've moved! We now have a Mattermost channel described at https://certbot.eff.org/docs/contributing.html#asking-for-help which is connected to the #certbot-devel IRC channel on Freenode.

**Comment by bmw** [comment]
@TheNavigat, are you available and interested to work on the other parts of this issue in the next week or two or would it be better if I did it myself?

**Comment by TheNavigat** [comment]
@bmw I think I should hand it over. I'm pretty overwhelmed right now and I don't want to be blocking anyone.

**Comment by bmw** [comment]
Sounds good. (To be clear, the "blocked" label was because landing this work was blocked on us dropping Python 3.4 support, not because it was blocked on you.)

**Comment by TheNavigat** [comment]
@bmw Yep, I figured, but I'm assuming this issue has some deadline. If that's not the case, if the deadline is flexible, would you be willing to let me work on it?

**Comment by bmw** [comment]
We want this for our release in a week and a half so there is a bit of a deadline. How about I take it and you take a different issue?

I'd recommend https://github.com/certbot/certbot/issues/7046. If you're interested, please leave a comment on it so people know you're working on it. If you'd be interested in working on something else instead, I'm happy to chat to help you find something.

Glad to hear there was no concern about the "blocked" tag. I just wanted to make sure.
