### ISSUE TITLE
certbot-auto doesn't support CentOS 8

### ISSUE THREAD

**Issue by arcdetri** [certbot/certbot#7396]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
CentOS 8

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
wget https://dl.eff.org/certbot-auto
mv certbot-auto /usr/local/bin/certbot-auto
chmod 0755 /usr/local/bin/certbot-auto

## I ran this command and it produced this output:
There appears to be a bug that causes certbot-auto to end with Creating virtual environment... followed by OSError: [Errno 2] No such file or directory. A workaround to prevent this is to issue the additional command:

yum install python3-virtualenv

## Certbot's behavior differed from what I expected because:
Certbot should not need a workaround to create a virtual environment

**Comment by bmw** [comment]
Yes. `certbot-auto` doesn't support CentOS 8 yet but making it do so should be pretty easy. It basically just involves setting the variable `RPM_USE_PYTHON_3` to 1 on the platform in the block [here](https://github.com/certbot/certbot/blob/8a570b18e91b53b2e598f0255c726eee7f62456c/letsencrypt-auto-source/letsencrypt-auto#L751).

If anyone knows of any prebuilt images in Docker, AWS, etc. that we could use to help us test support here, I'd appreciate it!
