### ISSUE TITLE
Error in /etc/httpd/conf.d/ssl.conf on CentOS 8

### ISSUE THREAD

**Issue by arcdetri** [certbot/certbot#7397]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
CentOS 8

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
/usr/local/bin/certbot-auto certonly --apache -d www.example.com

Error message refers to /etc/httpd/conf.d/ssl.conf, saying file '/etc/pki/tls/certs/localhost.crt' does not exist or is empty. 

Need to fix this error by deleting the erroneous configuration file and rerunning the Certbot command:

rm /etc/httpd/conf.d/ssl.conf
/usr/local/bin/certbot-auto certonly --apache -d www.example.com

## Certbot's behavior differed from what I expected because:
certonly should not create /etc/httpd/conf.d/ssl.conf in the first place, and it should not contain an error, as I will create the SSL virtual host manually

**Comment by alexzorin** [comment]
>certonly should not create /etc/httpd/conf.d/ssl.conf in the first place

I don't think that's what's happening.

Try this:

1. Install blank CentOS 8
2. `dnf -y install httpd mod_ssl`
3. `apachectl -t`

Result

    [root@7a8cbcb0d9f5 /]# apachectl -t
    AH00526: Syntax error on line 101 of /etc/httpd/conf.d/ssl.conf:
    SSLCertificateFile: file '/etc/pki/tls/certs/localhost.crt' does not exist or is empty
    [root@7a8cbcb0d9f5 /]# rpm -qf /etc/httpd/conf.d/ssl.conf
    mod_ssl-2.4.41-1.fc30.x86_64
    [root@7a8cbcb0d9f5 /]#

The act of installing `mod_ssl` (which Certbot depends on) creates a broken Apache configuration.

**Comment by arcdetri** [comment]
Thanks. My test confirms your findings. I have filed this result with CentOS, though my report appears to be held in a moderation queue.

**Comment by bmw** [comment]
I think you can fix the problem by (re)starting Apache through `systemd`. I think this is the CentOS 8 version of https://github.com/certbot/certbot/issues/7273.

**Comment by rizkyarlin** [comment]
> I think you can fix the problem by (re)starting Apache through `systemd`. I think this is the CentOS 8 version of #7273.

Running systemctl restart httpd gave me See "systemctl status httpd.service" and "journalctl -xe" for details. on CentOS8

**Comment by rizkyarlin** [comment]
Fixed mine by removing `/etc/httpd/conf.d/ssl.conf`, then rerun `sudo /usr/local/bin/certbot-auto --apache`

**Comment by worthwhileindustries** [comment]
When the mod_ssl package is installed, it should create a self-signed key and certificate files for the localhost. If the files are not automatically created, you can create them using the openssl command:
```
sudo openssl req -newkey rsa:4096 -x509 -sha256 -days 3650 -nodes \
  -out /etc/pki/tls/certs/localhost.crt \
  -keyout /etc/pki/tls/private/localhost.key
```

then run certbot-auto again

**Comment by mattsimpson** [comment]
@worthwhileindustries Yes, that definitely creates the missing `localhost.crt` file needed by Apache. Thanks for that.

This has got to be a bug though. @arcdetri Did anyone ever get back to you about the bug report?

**Comment by mattsimpson** [comment]
Hm. It appears this is just "the way" now?

https://bugzilla.redhat.com/show_bug.cgi?id=1764838
> Yup, you need to run `/usr/libexec/httpd-ssl-gencerts`

**Comment by geocfu** [comment]
Confirming this. I was searching for at least 1.5 hours because my virtualhost was not being resolved.

Deleting ```/etc/httpd/conf.d/ssl.conf``` and running ```sudo certbot --apache``` did the trick for me.
