### ISSUE TITLE
Remove custom os-release parsing code

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7399]
As pointed out by Joona, we have custom code in `certbot/util.py` parsing `/etc/os-release` but our new dependency `distro` seems to have equivalent code that does the same thing. I think we should verify `distro`'s versions work the same way and if it does, remove our custom code in favor of just using their code.

**Comment by joohoi** [comment]
When mapping the now manually parsed `ID_LIKE` field as a fallback we need to take care of the following:  ensure that the strings we got from `distro.linux_distribution()` match the `ID_LIKE` strings in `/etc/os-release`. The raw values from `ID` have been working correctly for the time being, but `distro.linux_distribution()` [may return something else](https://github.com/certbot/certbot/issues/7402). This is important to take look into, if the os version fingerprints in our mapping change after resolving #7405

**Comment by bmw** [comment]
@joona, with `distro.linux_distribution()` not using `ID_LIKE` from `/etc/os-release` does https://github.com/certbot/certbot/pull/7467 resolve this issue for you as well?

**Comment by bmw** [comment]
I think this has been resolved so I'm closing this for now. Please reopen if you disagree.

**Comment by joohoi** [comment]
Yeah, this was resolved, we're separately calling `distro.like()` where needed like previously.
