### ISSUE TITLE
Use platform.linux_distribution where we can

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7402]
I briefly looked into problems such as https://github.com/certbot/certbot/issues/7390 which seem to be due to the switch from using `platform.linux_distribution` in the standard library to `distro.linux_distribution` from https://github.com/nir0s/distro.

It seems like there are a lot of potential issues. In addition to the issue above, I've seen the same problem on Oracle Linux 6 when lsb-release is installed. The standard library seems to [only use OS specific files in `/etc`](https://github.com/python/cpython/blob/b2d29bfa5be5a0794c7c69078c43953967fcacf4/Lib/platform.py#L369) (with a [few exceptions on more obscure systems](https://github.com/python/cpython/blob/b2d29bfa5be5a0794c7c69078c43953967fcacf4/Lib/platform.py#L234)) while [distro prefers `/etc/os-release` and `lsb-release` before those files](https://github.com/nir0s/distro/blob/cdfe85d15bd366820db6a1cfdc6cf9a0a5de7e37/distro.py#L714).

To resolve these issues for now, I think we should remove our dependency on `distro`, calling `platform.linux_distribution()` when it's available, and just using the value in `platform.system_alias()` if not. The relevant code is https://github.com/certbot/certbot/blob/8cb57566c0be9fbed6d86316a0afb18e86d9f481/certbot/util.py#L387-L401

Alternatively, we could keep `distro` and use it on Python 3.8 only but all of the problematic systems we've seen using this `linux_distribution` code are based on RHEL 6 which does not have Python 3.8 and since its return values are very different from what we're used to, I think there's not much value without taking the time to do additional work.

I'd like to hear what others think here.

**Comment by joohoi** [comment]
I suggest that we try to use `platform.linux_distribution()` wherever possible (ie. on py < 3.8) and only fall back on `distro.linux_distribution()` on 3.8, so basically with you on your first suggestion. This is based on Python 3.8 not being available for most of the distributions that would hit the issue.

That said, I think we should properly utilize `distro` in the near future, preferably by removing our manual parsing of `/etc/os-release` at the same time, and this should probably take place sooner than later. It would give us a "single source of truth" and while `distro` itself is digging the distribution information from various sources, we would at least have consistent results per OS. The work would include repopulating our list of distribution fingerprints as well.

I created #7403 implementing this behavior. If you (or others) do not agree with this approach, feel free to close it.

**Comment by bmw** [comment]
The approach you took in #7403 is what I had in mind with my suggestion:

> Alternatively, we could keep distro and use it on Python 3.8 only but all of the problematic systems we've seen using this linux_distribution code are based on RHEL 6 which does not have Python 3.8 and since its return values are very different from what we're used to, I think there's not much value without taking the time to do additional work.

Calling `distro.linux_distribution` on Python 3.8 certainly could help in some scenarios so I'm fine keeping it.

I agree that there is more work to be done here and that it should probably be done soon. I think the most important aspect of this is properly handling the values returned by `distro`. I'll create https://github.com/certbot/certbot/issues/7405 to track this. Please add a comment if you think I missed something.

**Comment by bmw** [comment]
This was fixed in #7403.
