### ISSUE TITLE
Consistently and reliably use distro detection

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7405]
As described at https://github.com/certbot/certbot/issues/7402, it appears that `distro.linux_distribution()` cannot be used as a replacement for `platform.linux_distribution()` with the way we use the return value in the Apache plugin which is expecting specific strings to be returned.

We fixed this in https://github.com/certbot/certbot/pull/7403 by continuing to use `platform.linux_distribution` when we can, but this means we still have problems when run on Python 3.8 on Linux systems without `/etc/os-release` (which is the only time `*.linux_distribution` is called).

Unfortunately, we cannot completely remove this fallback while still supporting RHEL 6 based systems. There may be other niche systems relying on this too, but it's the only one we're aware of.

I'm open to other ideas, but to propose a way to accomplish this, I think we could:

1. Revert #7403 so we consistently use `distro` rather than having different behavior on different Python versions.
2. When not calling `linux_distribution` to build the user-agent string, call `distro.linux_distribution(full_distribution_name=False)` since it maintains an explicit list of the values it may return at https://github.com/nir0s/distro/blob/cdfe85d15bd366820db6a1cfdc6cf9a0a5de7e37/distro.py#L134-L166.
3. Add any missing strings we want to handle to the [dict in the Apache plugin](https://github.com/certbot/certbot/blob/8cb57566c0be9fbed6d86316a0afb18e86d9f481/certbot-apache/certbot_apache/entrypoint.py#L17).

As a bonus, we could maybe tackle https://github.com/certbot/certbot/issues/7399 at the same time, but I don't think this is absolutely necessary.

**Comment by bmw** [comment]
@joohoi, do you have any concerns about my proposal here?

**Comment by joohoi** [comment]
No, this looks good! In the scope of #7399 we might need to do some additional mapping, but I'll add the details to that issue.
