### ISSUE TITLE
Certbot Ubuntu 18.04 PPA is out of date (again)

### ISSUE THREAD

**Issue by ytterx** [certbot/certbot#7418]
## My operating system is (include version):
Ubuntu 18.04.3 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt-get (package manager)

Certbot is now on 0.39, the on in Ubuntu PPA is still on 0.31.
This is an issue as config-ssl-xxx.conf's have been updated to use TLS 1.3 for example. All "default" installed websites on Ubuntu through PPA still don't have that enabled.
See also https://github.com/certbot/certbot/issues/6770 as it basically reported the same thing a few months ago.

**Comment by ohemorange** [comment]
Thanks for reporting, it's helpful for us to understand how this is affecting users. We are aware of the issue and are working on getting it resolved.
