### ISSUE TITLE
[Feature Request] Configurable port for standalone server

### ISSUE THREAD

**Issue by lonix1** [certbot/certbot#7419]
**Background**
It is well known that certbot doesn't play nice in a dockerized environment, because certs must exist before nginx can serve, etc. The typical workaround is to initially run the `--standalone` server, get the certs saved in a docker volume, and thereafter run in `--webroot` mode in tandem with nginx.

**Problem**
But the `--standalone` server only works on port 80, the same port as the web server. This is a real hassle, and is messy.

**Solution**
*Please allow us to configure the standalone server's port.*

If we could do that, then we could run certbot alongside nginx, always in `--standalone` mode. It would do it's thing and save the certs to a docker named volume. Then a post hook could be used to reload nginx (which also has that volume mounted).

That would be MUCH simpler to setup, and MUCH simpler to run.

I've read that this was not done because 80 can only be used by a sudoer, and allowing a port which is >1024 could cause security risks.

Solutions:
- Allow us to do so anyway, but force use of `sudo`
- Use a port <1024 which is not generally used
- **Allow us to choose the port as long as it's <1024**     <--- best option!

Please do this, certbot is unnecessarily complicated because of this.

**Comment by ohemorange** [comment]
Hi @lonix1, will the `--http-01-port` option work for you?

```
$ certbot --help all | grep -A 4 http-01-port
  --http-01-port HTTP01_PORT
                        Port used in the http-01 challenge. This only affects
                        the port Certbot listens on. A conforming ACME server
                        will still attempt to connect on port 80. (default:
                        80)
```

**Comment by lonix1** [comment]
@ohemorange I saw that but didn't try it because

> ...A conforming ACME server will still attempt to connect on port 80. (default: 80)

Maybe I read it wrong - I assumed the acme server (letsencrypt) would *only* connect on 80, so why does this setting exist?

Would you mind explaining the nuance here?

**Comment by alexzorin** [comment]
Certbot doesn't get to decide what port to use for HTTP validation. That's a mandatory part of RFC8555:

>   3.  Dereference the URL using an HTTP GET request.  This request MUST
       be sent to TCP port 80 on the HTTP server.

`--http-01-port` can be useful because you might write your nginx configuration in this way:

```
location /.well-known/acme-challenge {
    proxy_pass http://localhost:41234;
}
```

You could use `--standalone --http-01-port 41234`, permitting nginx and Certbot's standalone server to run simultaneously.

But the connection that comes from the external internet will invariably be over port 80.

Hope that sheds some light.

**Comment by lonix1** [comment]
Thanks @alexzorin! Please tell me if I understand you correctly?

The problem is the RFC says letsencrypt's server MUST contact my web server on port 80.

So the setup should be:
- certbot runs in docker, listens on port X (`--http-01-port X`), and saves to "certs" docker volume
- nginx runs in a docker container, and accesses the same "certs" volume
- nginx proxies letsencrypt's requests (port 80) for `/.well-known/acme-challenge` to port X
- once certbot completes its work, I use a post-hook to reload nginx's config (for updated certs)

And the result is:
- I don't need to use "standalone" for registration and "webroot" for renewal - I use "standalone" mode to register AND renew certificates
- certbot does not interact with nginx directly

**Comment by alexzorin** [comment]
It might be best to continue by posting a description of your setup and objectives on https://community.letsencrypt.org/ , where you can get some in-depth answers.

**Comment by lonix1** [comment]
OKay, thanks.
