### ISSUE TITLE
Set up CentOS 8 test farm tests

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7420]
CentOS 8 didn't have AMIs available when i wrote https://github.com/certbot/certbot/pull/7406 but when it does, I think we should add it to our test farm tests. Doing so should be easy and helps prevent regressions.

**Comment by bmw** [comment]
As far as I can tell, there are no AMIs put out by Amazon or CentOS yet. Rather than using a random third party image, I think we should wait until a more official image is available.

**Comment by bmw** [comment]
These images still don't exist, but the CentOS team is actively working on the issue and it should be resolved soon. See https://bugs.centos.org/view.php?id=16614.

**Comment by bmw** [comment]
There is an official CentOS 8 AMI now! See https://wiki.centos.org/Cloud/AWS.

**Comment by ohemorange** [comment]
Is there some additional setup we normally do on top of the base AMIs when adding them? The `apache2.sh` test is failing with:

```
2020-07-01 01:23:11,847:ERROR:certbot.util:Error while running apachectl configtest.

AH00526: Syntax error on line 85 of /etc/httpd/conf.d/ssl.conf:
SSLCertificateFile: file '/etc/pki/tls/certs/localhost.crt' does not exist or is empty
```

**Comment by ohemorange** [comment]
`leauto_upgrades.sh` is also failing, because it can't seem to install the initial version that it upgrades from, `0.37.1`.

**Comment by ohemorange** [comment]
Um, do we even expect this to pass? Certbot-auto now uses python3 for centos8, but it didn't in certbot-auto from 0.37.1. Not sure how we can expect it to bootstrap itself properly...

**Comment by bmw** [comment]
The Apache issue is https://github.com/certbot/certbot/issues/7273. I personally think we should just leave CentOS 8 out of `apache2_targets.yaml` for now.

For the `leauto_upgrades.sh` issue, I personally think we should just update https://github.com/certbot/certbot/blob/f743dbec3a04349533735a161b650f02844b2294/tests/letstest/scripts/test_leauto_upgrades.sh#L26-L27
to 0.39.0 and make the comment reference CentOS 8.

**Comment by ohemorange** [comment]
Agreed on both counts.

**Comment by ohemorange** [comment]
`leauto_upgrades` and `test_tests` are now passing.
