### ISSUE TITLE
Nginx installer not properly reloading configuration 

### ISSUE THREAD

**Issue by Ackis** [certbot/certbot#7422]
Detailed conversation could be found here:
https://community.letsencrypt.org/t/cannot-renew-create-a-new-cert-when-i-had-no-issue-previously/103040/

## My operating system is (include version):
Ubuntu 18.04.3 LTS
Nginx 1.17.4 (note, this isn't the version of nginx that's part of Ubuntu's repo's)

## I ran this command and it produced this output:
`sudo certbot renew --cert-name ackis.duckdns.org --debug-challenges --dry-run`

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/ackis.duckdns.org.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert not due for renewal, but simulating renewal for dry run
Plugins selected: Authenticator nginx, Installer nginx
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for ackis.duckdns.org
Waiting for verification...

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Challenges loaded. Press continue to submit to CA. Pass "-v" for more info about
challenges.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cleaning up challenges
Attempting to renew cert (ackis.duckdns.org) from /etc/letsencrypt/renewal/ackis.duckdns.org.conf produced an unexpected error: Failed authorization procedure. ackis.duckdns.org (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from https://ackis.duckdns.org/.well-known/acme-challenge/7bO_DNxtDDyO_hPdRJcpGWEJHaLTRwtTsMWpWtQREDE [174.3.126.96]: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx</center>\r\n". Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/ackis.duckdns.org/fullchain.pem (failure)

- - - - - - - - - - - - - - - - - - -  - - - - - - - - - - - - - - - - - - - - -
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/ackis.duckdns.org/fullchain.pem (failure)
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates above have not been saved.)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1 renew failure(s), 0 parse failure(s)

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: ackis.duckdns.org
   Type:   unauthorized
   Detail: Invalid response from
   https://ackis.duckdns.org/.well-known/acme-challenge/7bO_DNxtDDyO_hPdRJcpGWEJHaLTRwtTsMWpWtQREDE
   [174.3.126.96]: "<html>\r\n<head><title>404 Not
   Found</title></head>\r\n<body>\r\n<center><h1>404 Not
   Found</h1></center>\r\n<hr><center>nginx</center>\r\n"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
```

## Certbot's behavior differed from what I expected because:

Certbot should have renewed the certificate.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

```
# HTTP server - redirect to HTTPS
server {
        listen                                  80;
        listen                                  [::]:80;
        server_name                             www.ackis.duckdns.org ackis.duckdns.org;

        location / {
                return                          301 https://ackis.duckdns.org$request_uri;
        }

        # Workaround LE and certbot not working with nginx
        location /.well-known/acme-challenge/ {
                                                root /var/www/letsencrypt;
        }

        access_log                              syslog:server=localhost,tag=nginx_access_internet,severity=info;
        error_log                               syslog:server=localhost,tag=nginx_error_internet;

        add_header                              Strict-Transport-Security "max-age=31536000;";
        add_header                              X-Frame-Options SAMEORIGIN;
        add_header                              X-Content-Type-Options nosniff;
        add_header                              X-XSS-Protection "1; mode=block";
}

# www domain - redirect to domain without www
server {
        listen                                  443 ssl;
        listen                                  [::]:443 ssl;
        server_name                             www.ackis.duckdns.org;

        location / {
                return                          301 https://ackis.duckdns.org$request_uri;
        }

        access_log                              syslog:server=localhost,tag=nginx_access_internet,severity=info;
        error_log                               syslog:server=localhost,tag=nginx_error_internet;

        ssl_certificate                         /etc/letsencrypt/live/www.ackis.duckdns.org/fullchain.pem;
        ssl_certificate_key                     /etc/letsencrypt/live/www.ackis.duckdns.org/privkey.pem;

        server_tokens                           off;
        etag                                    off;

        add_header                              Strict-Transport-Security "max-age=31536000;";
        add_header                              X-Frame-Options SAMEORIGIN;
        add_header                              X-Content-Type-Options nosniff;
        add_header                              X-XSS-Protection "1; mode=block";
}

server {
        listen                                  443 ssl default_server;
        listen                                  [::]:443 ssl;
        server_name                             ackis.duckdns.org;

        access_log                              syslog:server=localhost,tag=nginx_access_internet,severity=info;
        error_log                               syslog:server=localhost,tag=nginx_error_internet;

        ssl_certificate                         /etc/letsencrypt/live/ackis.duckdns.org/fullchain.pem; # managed by Certbot
        ssl_certificate_key                     /etc/letsencrypt/live/ackis.duckdns.org/privkey.pem; # managed by Certbot

        server_tokens                           off;
        etag                                    off;

        add_header                              Strict-Transport-Security "max-age=31536000;";
        add_header                              X-Frame-Options SAMEORIGIN;
        add_header                              X-Content-Type-Options nosniff;
        add_header                              X-XSS-Protection "1; mode=block";

        location ~* /\.\./ {
                deny                            all;
                return                          404;
        }

        location ~* "^(?:.+\.(?:htaccess|make|txt|test|markdown|md|engine|inc|info|install|module|profile|po|sh|.*sql|theme|tpl(?:\.php)?|xtmpl)|code-style\.pl|/Entries.*|/Re$
                return                          404;
        }

        location = /favicon.ico {
                try_files                       /favicon.ico =204;
        }

        location / {
                root                            /var/www/internet;
                index                           index.html;
        }
        location /nginx_status {
                access_log                      syslog:server=localhost,tag=nginx_access_admin,severity=info;
                error_log                       syslog:server=localhost,tag=nginx_error_admin;
                allow                           192.168.0.0/24;
                deny                            all;

                auth_basic                      "Restricted access";
                auth_basic_user_file            /etc/nginx/auth/admin.htpasswd;

                stub_status                     on;
        }

}

```

**Comment by alexzorin** [comment]
> Nginx 1.17.4 (note, this isn't the version of nginx that's part of Ubuntu's repo's)

Was it installed from https://nginx.org/en/linux_packages.html#Ubuntu or elsewhere?

**Comment by Ackis** [comment]
> > Nginx 1.17.4 (note, this isn't the version of nginx that's part of Ubuntu's repo's)
> 
> Was it installed from https://nginx.org/en/linux_packages.html#Ubuntu or elsewhere?

Yes, it's from their official repo.

**Comment by joohoi** [comment]
Thanks for opening the issue. I wonder if there's something different in the systemd service that gets installed with the nginx version from Nginx repositories.

**Comment by alexzorin** [comment]
I tried to reproduce this with Ubuntu 18.04.3, nginx 1.17.4 from nginx mainline, Certbot 0.31.0 from PPA, using the posted configuration (with the domain name substituted and chopped-off regex fixed). Everything worked OK.

Would you be able to zip up your entire `/etc/nginx` directory and upload it? From your thread, I believe there are a large number of other virtualhosts on the server also. They could be having an influence.

I'd also like to see whether there are nginx packages from multiple locations installed:

    dpkg-query -l "*nginx*"

**Comment by Ackis** [comment]
`dpkg-query -l "*nginx*"`

```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                Version        Architecture   Description
+++-===================-==============-==============-===========================================
ii  nginx               1.17.4-1~bioni amd64          high performance web server
rc  nginx-common        1.10.3-0ubuntu all            small, powerful, scalable web/proxy server
un  nginx-core          <none>         <none>         (no description available)
ii  nginx-doc           1.14.0-0ubuntu all            small, powerful, scalable web/proxy server
un  nginx-extras        <none>         <none>         (no description available)
un  nginx-full          <none>         <none>         (no description available)
un  nginx-light         <none>         <none>         (no description available)
ii  python-certbot-ngin 0.31.0-1+ubunt all            transitional dummy package
ii  python-certbot-ngin 0.23.0-1       all            Nginx plugin documentation for Certbot
ii  python3-certbot-ngi 0.31.0-1+ubunt all            Nginx plugin for Certbot

```

And my nginx config files are here: https://ackis.duckdns.org/nginx.tar.gz

**Comment by beret** [comment]
I've faced similar issues on my deployment (16.04 LTS, NGINX PPA, Certbot PPA)
Details here: https://community.letsencrypt.org/t/unable-to-renew-cert-using-nginx-plugin-fresh-cert-creation-succeeds/102843
My pastebin links, converted to attachments: [certbot issue 7422 - nginx -t.txt](https://github.com/certbot/certbot/files/3704995/certbot_help_topic_102843_-_nginx_-t.txt)
[certbot debug output with split root domain blocks - http tls.txt](https://github.com/certbot/certbot/files/3704997/certbot_with_split_root_domain_blocks___http_tls.txt)

Since reporting that issue, I reviewed my certbot per-site configuration files. I removed some pre and post hooks for legacy certificates, and unified them to all use the nginx validation and installer plugins. However the impacted certificates, including my test-case in that thread, were already inline with the modern plugins and no special hooks.

I've been able to complete those outstanding renewals, but I had to rerun `certbot renew` repeatedly as it churned through the renewals, failing to complete some renewals with similar failures consistent with improperly reloaded server configs.

In my test cases, I've been able to make renewals succeed just by running `systemctl reload nginx` repeatedly in a second window.

**Comment by Ackis** [comment]
My nginx reloads instantly, but seems to take over a minute to restart.

**Comment by beret** [comment]
@Ackis Yup, that's similar to my experience. Starting it again takes longer.

Reload has been sufficient for applying the .well-known validation interception hook to the config. By my rough reading of the nginx plugin code, I think certbot is *supposed* to call a reload when deploying and validating certs too.

**Comment by mustanggb** [comment]
Also having this issue.

To test I made the vhost modifications manually, did an Nginx reload, and made the request.

It took around 16 seconds for Nginx reload to complete, then a further 16 seconds before the response changed from 301/HTTPS to 200/token, for a total of 32 seconds for the correct response to be sent.

So could it be that the reload delay, or presumably more likely the second delay whilst waiting for the response to change, be the issue?

I've tried disabling any fastcgi and proxy caches in Nginx, but still having this 32 second gap.

**Comment by eccentric** [comment]
I'm also having this problem... It seems to be very much related to the time it takes to reload nginx, which causes the authentication to fail (gets a 404) when it requests immediately after reload. On this particular server we have 400+ .conf files that are being loaded in, with proxy_pass statements. I'm not entirely sure why the long reload, but I suspect it could be due to bad domains in some of the config files which nginx is failing to resolve which takes some time, or just the parse time of that many config files?

I realized I could force a bit of a slowdown in the nginx authenticator by adding a delay after reload, which looks to solve the problem completely in my case. I simply modified the ```certbot/certbot-nginx/certbot_nginx/_internal/configurator.py``` file and added a ```time.sleep(5)``` after the nginx_restart call (line 913):
```
        nginx_restart(self.conf('ctl'), self.nginx_conf)
        time.sleep(5)
```

This allows the nginx server to finish reloading before the api calls are made, and so it then correctly responds with the valid token instead of a 404.

This is not a proper solution, and it likely has to do with a specifically (badly) configured nginx, but it does fix the issue is this particular case. Maybe there could be a certbot nginx option to add a delay for slow web servers?

**Comment by mustanggb** [comment]
Yes, I think this bug can be summarised with the existing todo in `certbot/certbot-nginx/certbot_nginx/_internal/configurator.py`.

```
TODO: Check for expected servername and loop until it
appears or return an error if looping too long.
```

We basically need to wait until the restart has completed before carrying on.

**Comment by mustanggb** [comment]
Okay, so here's a pull request that waits for the restart to complete. #7740

**Comment by scr4bble** [comment]
Is there a possibility to solve this in a better way than specifying a constant delay?
Any plan from Nginx to make a synchronous reload?

**Comment by bvrulez** [comment]
I came across this from this post of the OP: https://community.letsencrypt.org/t/unable-to-renew-cert-using-nginx-plugin-fresh-cert-creation-succeeds/102843/9

I just tried to renew my certs on my Raspberry Pi and it did not work until I manually stopped nginx and then renewed. I then had to kill the process NGINX which apparently was started by the renew process. After this I restarted my systemctl service nginx.

NGINX 1.18
certbot 1.14
Raspbian Buster

**Comment by marcinex7** [comment]
Today I had the same problem. First, I had old installation of certbot (it was certbot-auto, on the server for like a 2-3 years) and old nginx (1.14). Later on I've removed certbot and reinstalled it from snap, I've also upgraded nginx to 1.21. same error was over and over again (with invalid verification). It stated working when I've shutted down nginx from systemctl, but also another process of 'nginx' appeared not connected to systemd after certbot successful job.

Is there any solution out there, or we're isolated cases here...?

P.s. I don't have too many vhosts on this server. Max 4 domains with couple subdomains - total of 15 maybe.

**Comment by alexzorin** [comment]
Hi @marcinex7,

>P.s. I don't have too many vhosts on this server

Despite Is this still happening if you include a sufficiently long `--nginx-sleep-seconds`? Although you said you don't have many vhosts, it would still be really helpful to rule timing out as a cause. If it still happens after that, then we can look into whether there's something funky happening between Certbot, `nginx -s reload/restart` and systemd.

**Comment by DenoGeek** [comment]
I think I'm having a similar problem. In my case, the HTTP challenge was failing. On further debugging I noticed that 

1. Certbot updated the Nginx virtual host with the challenge
2. But trying to access the challenge on my browser resulted in a 404
3. I restarted Nginx manually, and the challenge completed without problems
