### ISSUE TITLE
Set up notifications for Azure Pipelines

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7430]
As pointed out by Adrien at https://github.com/certbot/certbot/pull/7377#issue-317382853, we should set up notifications in Azure Pipelines so we know when a build fails.

[Unlike Travis CI](https://travis-ci.community/t/feature-request-mattermost-notifications/2992) we may be able to set up notifications directly to Mattermost. See https://docs.microsoft.com/en-us/azure/devops/notifications/howto-integrate-third-party-services?view=azure-devops and know that Mattermost supports Slack's API.

**Comment by adferrand** [comment]
Oh, I did not know that Mattermost was supporting the Slack's API. I was already thinking of a custom bash/Powershell/python custom script in Certbot repo that would be called to either connect to Matrix or Mattermost APIs.

Definitely things will be way easier with the builtin Slack support in Azure!

**Comment by bmw** [comment]
I did this. It's currently set up to report any failures of the advanced pipeline. Notifications are not sent for builds that pass, are canceled, or "partially succeed" (whatever that means).

It's currently going through my personal account, but I'm working on getting permissions to set it up through a separate bot account.
