### ISSUE TITLE
tests fail due to dist() and linux_distribution() functions being deprecated

### ISSUE THREAD

**Issue by flokli** [certbot/certbot#7450]
## My operating system is (include version):
NixOS 19.09

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Package Manager, https://github.com/NixOS/nixpkgs/pull/61203 (certbot v0.35.0)

We run builds in an isolated environment, without network access inside the tests at all.

## I ran this command and it produced this output:
```
pytest certbot-ci/certbot_integration_tests
```

Log: https://privatebin.net/?78cc31158bd54f60#AFcgAejVbz8KUaSAH3y3QDeCxwXqeEcuaCQnprqGTHY5

## Certbot's behavior differed from what I expected because:
Certbot already boots up pebble as an acme endpoint. We should not need to do any network access.

**Comment by bmw** [comment]
You shouldn't package certbot-ci. We do not distribute it and it's a utility we use ourselves for testing.

**Comment by flokli** [comment]
We don't intend to package it. Idea is that we run some integration / unit tests during the certbot package build, to ensure certbot works.

We have some much higher level NixOS vm tests at https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/acme.nix - still it'd be good to check failures earlier.

Do you have some unit tests that we could run instead?

**Comment by bmw** [comment]
Yep! Each of our packages contain a `setup.py` file which you can use to run tests by running `python setup.py test`.

**Comment by flokli** [comment]
Okay, so this would basically mean running `pytest certbot` from the repo source.

Doing that fails in a lot of places:
```
============================= test session starts ==============================
platform linux -- Python 3.7.5, pytest-5.2.1, py-1.8.0, pluggy-0.13.0
rootdir: /build/source, inifile: pytest.ini
plugins: xdist-1.30.0, forked-1.1.3
collected 909 items                                                            

certbot/plugins/common_test.py ...................................       [  3%]
certbot/plugins/disco_test.py ............................               [  6%]
certbot/plugins/dns_common_lexicon_test.py .............                 [  8%]
certbot/plugins/dns_common_test.py .......................               [ 10%]
certbot/plugins/enhancements_test.py ....                                [ 11%]
certbot/plugins/manual_test.py .........                                 [ 12%]
certbot/plugins/null_test.py .                                           [ 12%]
certbot/plugins/selection_test.py ..................                     [ 14%]
certbot/plugins/standalone_test.py ............                          [ 15%]
certbot/plugins/storage_test.py ........                                 [ 16%]
certbot/plugins/util_test.py ..                                          [ 16%]
certbot/plugins/webroot_test.py ......................                   [ 19%]
certbot/tests/account_test.py ..................................         [ 22%]
certbot/tests/auth_handler_test.py .............................         [ 26%]
certbot/tests/cert_manager_test.py ..................................... [ 30%]
                                                                         [ 30%]
certbot/tests/cli_test.py ..FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF...FFFF      [ 34%]
certbot/tests/client_test.py FFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF..  [ 39%]
certbot/tests/configuration_test.py .........                            [ 40%]
certbot/tests/crypto_util_test.py ...................................... [ 44%]
.                                                                        [ 44%]
certbot/tests/eff_test.py ..........                                     [ 45%]
certbot/tests/error_handler_test.py ............                         [ 47%]
certbot/tests/errors_test.py ....                                        [ 47%]
certbot/tests/hook_test.py ..................................            [ 51%]
certbot/tests/lock_test.py .........                                     [ 52%]
certbot/tests/log_test.py ........................                       [ 54%]
certbot/tests/main_test.py .FFF.FFF...FFFFF...........FFFFFFFFFFFFFFFFFF [ 59%]
FFFFFFFFFFFF.FFFFFFF..F..F.FF.....FFFFFFFFFFFFFFFFFFF....FFFFFFFFFF..    [ 67%]
certbot/tests/notify_test.py ...                                         [ 67%]
certbot/tests/ocsp_test.py .........                                     [ 68%]
certbot/tests/renewal_test.py .........                                  [ 69%]
certbot/tests/renewupdater_test.py ..........                            [ 70%]
certbot/tests/reporter_test.py .......                                   [ 71%]
certbot/tests/reverter_test.py ..............................            [ 74%]
certbot/tests/storage_test.py .......................................... [ 79%]
....                                                                     [ 79%]
certbot/tests/util_test.py ............................................. [ 84%]
.........                                                                [ 85%]
certbot/tests/compat/filesystem_test.py sssssssss.ssssss.s....s......... [ 89%]
                                                                         [ 89%]
certbot/tests/compat/os_test.py .                                        [ 89%]
certbot/tests/display/completer_test.py .....                            [ 90%]
certbot/tests/display/enhancements_test.py .....                         [ 90%]
certbot/tests/display/ops_test.py ...................................... [ 94%]
...                                                                      [ 95%]
certbot/tests/display/util_test.py ..................................... [ 99%]
.......                                                                  [100%]

=================================== FAILURES ===================================
```

Looking at the logs, all of these failures (?) seem to be caused by
```
E       DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
```

Shouldn't this fail in your CI, too?

**Comment by bmw** [comment]
Whose `pytest.ini` file are you using that is erroring on warnings? Our `pytest.ini` file is not included in the Certbot package at https://pypi.org/project/certbot/.

I would also recommend against running `pytest` directly over `python setup.py test`. Certbot's plugin system relies on `setuptools` to register and find its plugins and some distros that have tried to run `pytest` directly have had trouble here in the past.

**Comment by flokli** [comment]
@bmw we are fetching the sources directly from github, so the `./pytest.ini` is included.

I got it to work by the following patch:

```patch
From 2cd9baeb4bf781555c7c7e74e012f5bb567abc2d Mon Sep 17 00:00:00 2001
From: Florian Klink <flokli@flokli.de>
Date: Sun, 17 Nov 2019 15:56:18 +0100
Subject: [PATCH] pytest.ini: ignore dist() and linux_distribution()
 deprecation warnings

---
 pytest.ini | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/pytest.ini b/pytest.ini
index 6c2404056..ab6b44ad4 100644
--- a/pytest.ini
+++ b/pytest.ini
@@ -10,9 +10,11 @@
 #      but it should be corrected to allow Certbot compatiblity with Python >= 3.8
 #   4- ipdb uses deprecated functionality of IPython. See
 #      https://github.com/gotcha/ipdb/issues/144.
+#   5- deprecated dist() and linux_distribution() functions
 filterwarnings =
     error
     ignore:decodestring:DeprecationWarning
     ignore:.*collections\.abc:DeprecationWarning
     ignore:The `color_scheme` argument is deprecated:DeprecationWarning:IPython.*
     ignore:.*get_systemd_os_info:DeprecationWarning
+    ignore:.*dist() and linux_distribution() functions are deprecated.*
-- 
2.23.0

```

So it's definitely an issue in not ignoring these deprecation warnings properly from `pytest.ini`. Another occurence: https://github.com/certbot/certbot/pull/7535#issuecomment-554753770

**Comment by bmw** [comment]
> @bmw we are fetching the sources directly from github, so the ./pytest.ini is included.

OK. Know that things might not be as stable for you with this approach. In addition to problems like the ones you've had here, we're currently in the process of moving the location of the Certbot package in this repository in https://github.com/certbot/certbot/pull/7544 for instance.

Is there a reason not to use our built packages? Do Python sdists in general not play nicely with NixOS?

> I got it to work by the following patch:

Well the good news is that patch shouldn't be necessary starting with our 0.40.0 release a few weeks ago.

It is interesting that that the tests weren't failing for us before though. Are you able to provide output similar to `pip freeze` of all the Python packages and their versions that are installed in your setup? I was unable to reproduce the error using  Python 3.7.5 on the `v0.35.0` tag.

**Comment by flokli** [comment]
We want to easily notice breakages caused by package bumps of dependencies (or bumps of the package itself). In nixpkgs, it's common practice to automatically run unit tests in a separate phase of the package build recipe, to quickly identify breakages.

Just checking the version bounds on the requirements file are satisfied doesn't provide that guarantee, but unit tests hopefully do a better job :-)

I'll take a look at how things look like with 0.40.0.

**Comment by bmw** [comment]
Sure, but like most Python packages, our unit tests are included in the Python packages on PyPI. With the exception of a couple of things like [certbot-git](https://aur.archlinux.org/packages/certbot-git/) on Arch's AUR repo, nixOS is the only system I'm aware of packaging directly from our GitHub. I just think that using the PyPI package could avoid you all some unnecessary headaches.

**Comment by flokli** [comment]
I assume there were some reasons on why we did it back then - maybe we were depending on something not yet released and only available in master. I'll give this a go with the packages from PyPI soon and will report back.

**Comment by flokli** [comment]
@bmw I got the unit tests to work from the latest pypi release. Thanks for your patience :-)
