### ISSUE TITLE
Remove deprecated flags

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7451]
I think we should delete all calls to `certbot.util.add_deprecated_argument`. All of these flags have been deprecated for a long time and I think can be safely removed.

If someone gets to this issue first, I would recommend leaving the deprecated TLS-SNI flags to be removed in https://github.com/certbot/certbot/issues/7214.

**Comment by moore3071** [comment]
I left the function for creating deprecated arguments in case it's needed later. If you'd rather, I can delete those functions too (or a maintainer can when merging. Whatever works best for you guys).

**Comment by bmw** [comment]
I think leaving the function itself was the right call.

**Comment by bmw** [comment]
This was done in #7482.
