### ISSUE TITLE
Remove --update-registration

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7452]
The command `certbot register --update-registration` has been deprecated for a long time in favor of `certbot update_account`. Let's remove `--update-registration` and the code that uses it.

**Comment by TheNavigat** [comment]
In addition to https://github.com/certbot/certbot/issues/7454, I'd also love to work on this if no one is already assigned

**Comment by bmw** [comment]
We'd like this to be included in our next release in the beginning of December. @TheNavigat, are you still planning on working on this or would you like one of us to take it over?

**Comment by TheNavigat** [comment]
@bmw Sorry for the delay. Let me give it a shot this week and see how far I can go. If I got stuck I can hand it over. What do you think about that?

**Comment by bmw** [comment]
That sounds good to me!
