### ISSUE TITLE
Document stability for Certbot 1.0 as an application

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7463]
In a similar vein as https://github.com/certbot/certbot/issues/5775 but about the behavior/scriptability of Certbot itself.

Proposal is at https://docs.google.com/document/d/1mSAVmdItebe8FAlc12P1xF7DcX886m5qywslxMoZEq0/edit?usp=sharing.

**Comment by bmw** [comment]
I'm assigning this to Joona for now because he said he wanted to review my proposal here.

**Comment by joohoi** [comment]
I think the propsal is good, with one potential addition, and it isn't a big deal to leave it out either. The current line between the core and the (core) plugins is a bit vague in this regard as well. All in all, looks good.

**Comment by bmw** [comment]
Thanks for taking a look!

> The current line between the core and the (core) plugins is a bit vague in this regard as well.

I agree. I think everything I said in that doc apply to our plugins as well. Do you think just including language to say that this includes Certbot's official plugins solves this problem?

**Comment by joohoi** [comment]
> Do you think just including language to say that this includes Certbot's official plugins solves this problem?

Yeah mainly, though we probably should elaborate the term "official" somewhere in the doc as well to clarify that by official we mean plugins maintained by EFF within the core project repository.
