### ISSUE TITLE
Certbot resolves IDN wrong

### ISSUE THREAD

**Issue by TaaviE** [certbot/certbot#7468]
OS: Ubuntu 18.04.3
CertBot: 0.31.0
CertBot source: official repository

What I did:
Tried renewing existing certificate of an IDN.

What happened:
It exited claiming `NXDOMAIN`, which is blatantly false because both unicode and punycode versions resolve using not-certbot and also on different machines. 
CertBot error output: `DNS problem: NXDOMAIN looking up A for ex\xfcmple.com` which seems like it converts `ü` incorrectly.

What I expected to happen:
CertBot to renew the cert that was even once acquired.

**Comment by TaaviE** [comment]
@alexzorin 
Then the bug is in Boulder or something. The fact is that it works for literally everything else, it's not the domain.

**Comment by alexzorin** [comment]
Sure, I am not trying to dismiss that possibility. There have been numerous cases of Unbound bugs in the past. Posting on the forums will get the ball rolling on a diagnosis and fix if necessary.

**Comment by TaaviE** [comment]
Unbound fails on that page when using the unicode variant giving a `404 page not found`, entering the punycode version works. I'll open a thread on the forums, thanks anyways.
