### ISSUE TITLE
Upgrading certbot-auto 0.36.0 to 0.39.0 urlopen error timed out

### ISSUE THREAD

**Issue by hanq** [certbot/certbot#7471]
## My operating system is (include version):
Ubuntu 14.04 LTS

## I ran this command and it produced this output:
sudo /usr/local/bin/certbot-auto --nginx

## Here is a Certbot log showing the issue (if available):

Upgrading certbot-auto 0.36.0 to 0.39.0...
Couldn't download https://raw.githubusercontent.com/certbot/certbot/v0.39.0/letsencrypt-auto-source/letsencrypt-auto. <urlopen error timed out>

**Comment by adferrand** [comment]
Hello!

I think you encountered a temporary network failure, either on your side (machine or network) or on GitHub side. You should try again the command.

I confirm from two different networks + machines that https://raw.githubusercontent.com/certbot/certbot/v0.39.0/letsencrypt-auto-source/letsencrypt-auto is reachable.

If it still does not succeed, I invite you to post on our dedicated Support Forum https://community.letsencrypt.org/ to get the appropriate help.
