### ISSUE TITLE
Remove Ubuntu 18.10 packages from our PPA

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7472]
Ubuntu 18.10 reached its end of life in July. See https://lists.ubuntu.com/archives/ubuntu-announce/2019-July/000246.html.

@devec0

**Comment by alexzorin** [comment]
18.10*

**Comment by bmw** [comment]
Nice catch. We definitely don't want to delete Ubuntu 18.04 LTS Bionic packages.

**Comment by adferrand** [comment]
For something like the next 9 years ;)

**Comment by devec0** [comment]
This is now done

**Comment by bmw** [comment]
Awesome. Thanks @devec0!
