### ISSUE TITLE
missing info in CHANGELOG about removal of certbot-postfix

### ISSUE THREAD

**Issue by computersalat** [certbot/certbot#7495]
`certbot-postfix` got removed, but there is no Info about that in `CHANGELOG.md`
Can you please update CHANGELOG

thank you

**Comment by adferrand** [comment]
Hello!

We put entries in changelog only for assets that are published (like the packages `certbot`, `acme`...).

`certbot-postfix` has never been published, that is why we did not add it to the changelog when it has been removed with #7097.
