### ISSUE TITLE
Email address sent to EFF before certificate is successfully created

### ISSUE THREAD

**Issue by mfb** [certbot/certbot#7512]
Certbot sends the user's email address to EFF as soon as the user first runs certbot (if --eff-email option is on, or user opts in at the prompt), but before a valid certificate has been created.  I'm concerned that this behavior might be contributing to a higher than expected bounce rate for the subscription confirmation emails EFF sends out.

How hard would it be for certbot to only send the email address to EFF after a valid certificate has been created successfully?  This should cut down on the proportion of bogus email addresses - in some sense acting like a sortof "captcha".

**Comment by bmw** [comment]
It'd be a bit of work honestly. The main difficulty is the user may not have provided their email address on the same run they issue their certificate. We'd have to store the need to offer to register their email with EFF somewhere on disk, check that after issuing certificates, and then delete it after the first certificate is issued. Obviously not impossible, but more work than just moving a function call later in execution.

**Comment by mfb** [comment]
Yes I was imagining that the preference could be stored in the json files (or a new json file if need be)?

I wasn't sure on some of the details for how this would need to work - like is each instance of certbot tied to one email address, or could you create different certs with different email addresses on the same host, and send each of those email addresses to EFF?

**Comment by bmw** [comment]
> Yes I was imagining that the preference could be stored in the json files (or a new json file if need be)?

Yep! We'd just have to shuffle some code around and then write the code to write and read it. We'd also have to decide if we want to ask about sending your email address to EFF when you first give us your email address like we currently do or only before we'd want to send it after you obtain your certificate.

> I wasn't sure on some of the details for how this would need to work - like is each instance of certbot tied to one email address, or could you create different certs with different email addresses on the same host, and send each of those email addresses to EFF?

It's the latter. One of the first steps in the ACME protocol used by Let's Encrypt in Certbot is for the user to create an account. This account can contain 0, 1, or even multiple email addresses. Certbot only allows you to have one account per server at a time, but you can always delete your account and create a new one or change the email addresses associated with your account.

**Comment by mfb** [comment]
> We'd also have to decide if we want to ask about sending your email address to EFF when you first give us your email address like we currently do or only before we'd want to send it after you obtain your certificate.

Either way could work, but I guess it would be preferable to ask users to opt-in at the time of cert generation, since this would be closer in time to when the data is actually sent to EFF (and they receive the subscription confirmation email).

**Comment by bmw** [comment]
When designing the implementation here, I think forwards compatibility is important. We won't be able to have older versions of Certbot understand that it needs to submit the email address to EFF once it has issued a certificate, but I think we should make sure that older versions of Certbot don't crash with it encounters whatever changes to Certbot's storage we make in this PR.
