### ISSUE TITLE
Offer 64 bit versions of the Windows installer?

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7522]
With our Azure setup, it seems to me like doing this should be pretty easy, however, what happens if a user gets both the 32 bit version and the 64 bit version installed on their system? Is that even something we should worry about?

cc @adferrand

**Comment by adferrand** [comment]
Yes adding the 64bits version is quite simple, it is a matter of enabling the correct Python version in the pipeline, and make `PYTHON_BITNESS` configurable from CLI.

The overlapping handling between two versions of Certbot installed in 32bits and 64bits is a real problem that should be taken into account. Maybe there is already something in Pynsist. 

But to be honest on Windows, 64bits version of things is not really a big deal. Every framework in Windows is available for both bitness, and it is not going to end considering the retro-compatibility commitment on Windows. 

I now a lot of Windows softwares that are available only in 32 bits. A significant part were nobody cares about the 64 bits version. And none in top of my head were 64 bits availability was a deal breaker.

Considering the complexity it adds to handle parallel versions of Certbot, I do not think it is worth it.

**Comment by bmw** [comment]
Fair enough. Let's wait and see if a demand for it arises.
