### ISSUE TITLE
scl_source may not exist

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7524]
As described in the comments following https://community.letsencrypt.org/t/certbot-failing-to-find-python-version-on-centos-6-10/105634/5, it's possible that `scl_source` does not exist on RHEL 6 based systems. To reproduce this in the CentOS 6 Docker image, run:
```
yum install epel-release -y
yum install scl-utils-20120229 -y
```
You can enable the SCL repository and install `rh-python36` after this and a newer version of `scl-utils` containing `scl_source` will not be installed.

I think we should fix this before rereleasing the code migrating people to Python 3.6 on SCL.

To do this, I think we can either try to make sure a new enough version of `scl-utils` is installed (although I'm not sure the best way to do that) or stop using `scl_source` and either manually modify our `PATH` or manually source `/opt/rh/rh-python36/enable`.

**Comment by bmw** [comment]
cc @adferrand, @joohoi

**Comment by bmw** [comment]
I talked with Elyscape about this Mattermost and they recommend changing the calls to `scl_source` to `. /opt/rh/rh-python36/enable`. See https://opensource.eff.org/eff-open-source/pl/rqxhh1dcap81dyuoxurgjz56iy.

I think I'm convinced that is the best approach.

**Comment by adferrand** [comment]
> I talked with Elyscape about this Mattermost and they recommend changing the calls to `scl_source` to `. /opt/rh/rh-python36/enable`. See https://opensource.eff.org/eff-open-source/pl/rqxhh1dcap81dyuoxurgjz56iy.
> 
> I think I'm convinced that is the best approach.

I am too, it was my previous implementation of the enabling. If you remember, we moved to `scl_source` in case the path to the enabler script was not standard, since `scl_source` contains code to find it.

**Comment by bmw** [comment]
Yeah. Turns out it should be standard but the presence of `scl_source` is not :(

I think I'm in favor of including this change in https://github.com/certbot/certbot/pull/7519 just in case we have to revert the whole thing again, but I don't care too much.

**Comment by DimaVIII** [comment]
As the update was pushed and it broke all live Certbot installation on CentOS 6, so Certbot is not able to startup on it self and load update any patches. This means I need to manual fix all my CentOS 6 server that are running Certbot?

**Comment by bmw** [comment]
@DimaVIII, if they upgraded during the few hour window where the buggy release was live unfortunately you do have to manually fix it. I wrote how to do this at https://community.letsencrypt.org/t/certbot-failing-to-find-python-version-on-centos-6-10/105634/3.

**Comment by DimaVIII** [comment]
@bmw If I run certbot-auto after 'rm -rf /opt/eff.org/' it asks me for a lot of inputs, how can make it run without inputs? I need now to update few hundred servers. :/

**Comment by bmw** [comment]
If you're on CentOS 6 you can include `--non-interactive` on the command line.

**Comment by mnordhoff** [comment]
FWIW, on the forum, [daTourist posted that they](https://community.letsencrypt.org/t/certbot-failing-to-find-python-version-on-centos-6-10/105634/9?u=mnordhoff):

> ... solved it by updating scl-utils-* while excluding the EPEL repo:
>
> `yum --disablerepo=epel  update scl-utils-*`
