### ISSUE TITLE
Default developer instructions should work in py3-only environment

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#7548]
Right now the developer instructions say to run:

```
./certbot-auto --debug --os-packages-only
```

Right now on Ubuntu, that will install `python` and `python-dev` (the Python 2 packages). However, latest Ubuntu (19.10) ships with `python3` and `python3-dev`, but no Python 2. Since we fully support Python 3, we shouldn't encourage people to install older Pythons. That's likely to mask issues with Python 3 support that we otherwise might find during development.

Since the list of packages in `--os-packages-only` has been static for a while, I recommend just hoisting the list of packages into the developer instructions, and replacing `python` and `python-dev` with `python3` and `python3-dev`. This avoids risks in changing certbot-auto.

**Comment by adferrand** [comment]
Yes, we can expect Certbot contributors to know how to use their package managers. A dedicated block of instructions for each major package manager would be really suitable instead of certbot-auto in my opinion.
