### ISSUE TITLE
Improve informations about module nginx failing create or renew certificates

### ISSUE THREAD

**Issue by jadjay** [certbot/certbot#7555]
## Certbot's behavior differed from what I expected because:

Sometimes nginx has too much configurations files, which lead it to reach its open files limits,

At this point, `nginx -s reload ` doesn't reload configuration, 

⚠️ but it exits with the 0 state, and do not print errors messages ⚠️ 

You have to check in /var/log/nginx/error.log to see that it fails reloading the configuration because : "too much open files"

So certbot fails to reload nginx while changing the configuration for authentification,
So let'sencrypt fails authenticating
So certbot give you : Authentication fails

## What is expected

> nginx reload must exit with state error !

Certbot may : 
* Informs user that error comes from nginx reload failed (and stop without trying auth)
* Try restart if reload is not enough

**Comment by ohemorange** [comment]
To be clear: when this happens, nginx claims that it exited successfully and doesn't print any errors? This seems difficult for Certbot to catch in that case.

**Comment by alexzorin** [comment]
> To be clear: when this happens, nginx claims that it exited successfully and doesn't print any errors? This seems difficult for Certbot to catch in that case.

I think this is the same problem that is at the root of #7422. 

All `nginx -s reload` does is `kill -HUP <nginx pid>`. 

There is no mechanism for actually knowing whether (relevant to this issue) or when (relevant to the other issue) the reload actually succeeded.

**Comment by jadjay** [comment]
> A potential, but probably-too-complex solution: Certbot could put a canary virtual host in the configuration (not a public domain, only listens on loopback) that it could use to verify that the configuration has reloaded, up to some timeout.

Ok, maybe it could be part of the explanation of the error ... at least.
