### ISSUE TITLE
Unable to install certbox

### ISSUE THREAD

**Issue by dineshv1234567** [certbot/certbot#7573]
I am unable to install certbox

## I tried installing Certbot with -
 sudo yum install certbot certbot-apache

## I ran the above mentioned command and it produced this output:
Loaded plugins: ulninfo
Resolving Dependencies
--> Running transaction check
---> Package certbot.noarch 0:0.39.0-1.el7 will be installed
--> Processing Dependency: python2-certbot = 0.39.0-1.el7 for package: certbot-0.39.0-1.el7.noarch
---> Package python2-certbot-apache.noarch 0:0.39.0-1.el7 will be installed
--> Processing Dependency: python2-acme >= 0.29.0 for package: python2-certbot-apache-0.39.0-1.el7.noarch
--> Processing Dependency: mod_ssl for package: python2-certbot-apache-0.39.0-1.el7.noarch
--> Processing Dependency: pytest for package: python2-certbot-apache-0.39.0-1.el7.noarch
--> Processing Dependency: python-augeas for package: python2-certbot-apache-0.39.0-1.el7.noarch
--> Running transaction check
---> Package mod_ssl.x86_64 1:2.4.6-90.0.1.el7 will be installed
--> Processing Dependency: httpd = 2.4.6-90.0.1.el7 for package: 1:mod_ssl-2.4.6-90.0.1.el7.x86_64
--> Processing Dependency: httpd-mmn = 20120211x8664 for package: 1:mod_ssl-2.4.6-90.0.1.el7.x86_64
--> Processing Dependency: httpd for package: 1:mod_ssl-2.4.6-90.0.1.el7.x86_64
---> Package python-augeas.noarch 0:0.5.0-2.el7 will be installed
---> Package python2-acme.noarch 0:0.39.0-1.el7 will be installed
--> Processing Dependency: python2-josepy >= 1.1.0 for package: python2-acme-0.39.0-1.el7.noarch
--> Processing Dependency: python-ndg_httpsclient for package: python2-acme-0.39.0-1.el7.noarch
--> Processing Dependency: python-requests-toolbelt for package: python2-acme-0.39.0-1.el7.noarch
--> Processing Dependency: python2-cryptography for package: python2-acme-0.39.0-1.el7.noarch
--> Processing Dependency: python2-pyasn1 for package: python2-acme-0.39.0-1.el7.noarch
--> Processing Dependency: python2-pyrfc3339 for package: python2-acme-0.39.0-1.el7.noarch
--> Processing Dependency: python2-requests for package: python2-acme-0.39.0-1.el7.noarch
--> Processing Dependency: python2-six for package: python2-acme-0.39.0-1.el7.noarch
---> Package python2-certbot.noarch 0:0.39.0-1.el7 will be installed
--> Processing Dependency: python-parsedatetime for package: python2-certbot-0.39.0-1.el7.noarch
--> Processing Dependency: python-zope-component for package: python2-certbot-0.39.0-1.el7.noarch
--> Processing Dependency: python-zope-interface for package: python2-certbot-0.39.0-1.el7.noarch
--> Processing Dependency: python2-configargparse for package: python2-certbot-0.39.0-1.el7.noarch
--> Processing Dependency: python2-distro for package: python2-certbot-0.39.0-1.el7.noarch
--> Processing Dependency: python2-future for package: python2-certbot-0.39.0-1.el7.noarch
--> Processing Dependency: python2-mock for package: python2-certbot-0.39.0-1.el7.noarch
---> Package python2-certbot-apache.noarch 0:0.39.0-1.el7 will be installed
--> Processing Dependency: pytest for package: python2-certbot-apache-0.39.0-1.el7.noarch
--> Running transaction check
---> Package httpd.x86_64 0:2.4.6-90.0.1.el7 will be installed
--> Processing Dependency: httpd-tools = 2.4.6-90.0.1.el7 for package: httpd-2.4.6-90.0.1.el7.x86_64
--> Processing Dependency: libaprutil-1.so.0()(64bit) for package: httpd-2.4.6-90.0.1.el7.x86_64
--> Processing Dependency: libapr-1.so.0()(64bit) for package: httpd-2.4.6-90.0.1.el7.x86_64
---> Package python-ndg_httpsclient.noarch 0:0.3.2-1.el7 will be installed
---> Package python-requests.noarch 0:2.6.0-7.el7_7 will be installed
--> Processing Dependency: python-urllib3 >= 1.10.2-1 for package: python-requests-2.6.0-7.el7_7.noarch
---> Package python-requests-toolbelt.noarch 0:0.8.0-1.el7 will be installed
---> Package python-zope-component.noarch 1:4.1.0-5.el7 will be installed
--> Processing Dependency: python-zope-event for package: 1:python-zope-component-4.1.0-5.el7.noarch
--> Processing Dependency: python-zope-interface for package: 1:python-zope-component-4.1.0-5.el7.noarch
---> Package python2-certbot.noarch 0:0.39.0-1.el7 will be installed
--> Processing Dependency: python-zope-interface for package: python2-certbot-0.39.0-1.el7.noarch
---> Package python2-certbot-apache.noarch 0:0.39.0-1.el7 will be installed
--> Processing Dependency: pytest for package: python2-certbot-apache-0.39.0-1.el7.noarch
---> Package python2-configargparse.noarch 0:0.11.0-1.el7 will be installed
---> Package python2-cryptography.x86_64 0:1.7.2-2.el7 will be installed
--> Processing Dependency: python-idna >= 2.0 for package: python2-cryptography-1.7.2-2.el7.x86_64
--> Processing Dependency: python-cffi >= 1.4.1 for package: python2-cryptography-1.7.2-2.el7.x86_64
--> Processing Dependency: python-enum34 for package: python2-cryptography-1.7.2-2.el7.x86_64
---> Package python2-distro.noarch 0:1.2.0-3.el7 will be installed
---> Package python2-future.noarch 0:0.16.0-15.20181019gitbee0f3b.el7 will be installed
---> Package python2-josepy.noarch 0:1.2.0-1.el7 will be installed
---> Package python2-mock.noarch 0:1.0.1-10.el7 will be installed
---> Package python2-parsedatetime.noarch 0:2.4-5.el7 will be installed
---> Package python2-pyasn1.noarch 0:0.1.9-7.el7 will be installed
---> Package python2-pyrfc3339.noarch 0:1.0-2.el7 will be installed
---> Package python2-six.noarch 0:1.9.0-0.el7 will be installed
--> Running transaction check
---> Package apr.x86_64 0:1.4.8-5.el7 will be installed
---> Package apr-util.x86_64 0:1.5.2-6.0.1.el7 will be installed
---> Package httpd-tools.x86_64 0:2.4.6-90.0.1.el7 will be installed
---> Package python-cffi.x86_64 0:1.6.0-5.el7 will be installed
--> Processing Dependency: python-pycparser for package: python-cffi-1.6.0-5.el7.x86_64
---> Package python-enum34.noarch 0:1.0.4-1.el7 will be installed
---> Package python-idna.noarch 0:2.4-1.el7 will be installed
---> Package python-urllib3.noarch 0:1.10.2-7.el7 will be installed
---> Package python-zope-component.noarch 1:4.1.0-5.el7 will be installed
--> Processing Dependency: python-zope-interface for package: 1:python-zope-component-4.1.0-5.el7.noarch
---> Package python-zope-event.noarch 0:4.0.3-2.el7 will be installed
---> Package python2-certbot.noarch 0:0.39.0-1.el7 will be installed
--> Processing Dependency: python-zope-interface for package: python2-certbot-0.39.0-1.el7.noarch
---> Package python2-certbot-apache.noarch 0:0.39.0-1.el7 will be installed
--> Processing Dependency: pytest for package: python2-certbot-apache-0.39.0-1.el7.noarch
--> Running transaction check
---> Package python-pycparser.noarch 0:2.14-1.el7 will be installed
--> Processing Dependency: python-ply for package: python-pycparser-2.14-1.el7.noarch
---> Package python-zope-component.noarch 1:4.1.0-5.el7 will be installed
--> Processing Dependency: python-zope-interface for package: 1:python-zope-component-4.1.0-5.el7.noarch
---> Package python2-certbot.noarch 0:0.39.0-1.el7 will be installed
--> Processing Dependency: python-zope-interface for package: python2-certbot-0.39.0-1.el7.noarch
---> Package python2-certbot-apache.noarch 0:0.39.0-1.el7 will be installed
--> Processing Dependency: pytest for package: python2-certbot-apache-0.39.0-1.el7.noarch
--> Running transaction check
---> Package python-ply.noarch 0:3.4-11.el7 will be installed
---> Package python-zope-component.noarch 1:4.1.0-5.el7 will be installed
--> Processing Dependency: python-zope-interface for package: 1:python-zope-component-4.1.0-5.el7.noarch
---> Package python2-certbot.noarch 0:0.39.0-1.el7 will be installed
--> Processing Dependency: python-zope-interface for package: python2-certbot-0.39.0-1.el7.noarch
---> Package python2-certbot-apache.noarch 0:0.39.0-1.el7 will be installed
--> Processing Dependency: pytest for package: python2-certbot-apache-0.39.0-1.el7.noarch
--> Finished Dependency Resolution
Error: Package: python2-certbot-apache-0.39.0-1.el7.noarch (epel)
           Requires: pytest
Error: Package: 1:python-zope-component-4.1.0-5.el7.noarch (epel)
           Requires: python-zope-interface
Error: Package: python2-certbot-0.39.0-1.el7.noarch (epel)
           Requires: python-zope-interface
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

## I even tried:
$ yum -y install yum-utils
$ yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional

But the error remains same !!

**Comment by bmw** [comment]
Let's move this to https://community.letsencrypt.org/t/unable-to-install-certbox/106880. If it ends up being a bug in the EPEL packages, we can open an issue here or bugzilla.
