### ISSUE TITLE
wrong "issued to"

### ISSUE THREAD

**Issue by quantrpeter** [certbot/certbot#7591]
Hi
   I successfullly applyied cert to my apache, but the cert is in wrong "issued to" name. how can i change it?
thanks
Peter

**Comment by alexzorin** [comment]
Hi Peter,

Could you please post your question, along with a screenshot of the wrong "issued to" name, on https://community.letsencrypt.org/? 

Thanks

**Comment by quantrpeter** [comment]
ok, thanks
