### ISSUE TITLE
Move tests for acme and plugins out of the importable code

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7593]
This is a piece of #5775 that would be nice to have for 1.0. An important thing to test here is that `MANIFEST.in` is updated so the tests are still included in the built package and run with `python setup.py test`.

There is a lot of individual pieces of this such as `acme`, `certbot-apache`, `certbot-nginx`, and `certbot-dns-*` that should probably be split into separate PRs (and could even be worked on by separate people).

**Comment by maximillianh** [comment]
@ohemorange I think this is a nice-to-have for 1.0 if you can fit it in, but it's fine to let it slide.

**Comment by bmw** [comment]
I think this has been resolved!
