### ISSUE TITLE
Modernise logging

### ISSUE THREAD

**Issue by nhey** [certbot/certbot#7602]
I request integration with journald or at least the ability to log to stdout.
Currently it is only possible to specify a logs directory, which means I have to patch the logging module in order to write to stdout.

Would something simple like a stdout commandline flag be accepted upstream?
From `log.py`:
```
def setup_log_file_handler(config, logfile, fmt):
...
++   if config.log_to_stdout:
++     handler = logging.StreamHandler(sys.stdout)
...
++  else:
      util.set_up_core_dir(config.logs_dir, 0o700, config.strict_permissions)
      log_file_path = os.path.join(config.logs_dir, logfile)
      try:
          handler = logging.handlers.RotatingFileHandler(
              log_file_path, maxBytes=2 ** 20,
              backupCount=config.max_log_backups)
      except IOError as error:
          raise errors.Error(util.PERM_ERR_FMT.format(error))
      handler.doRollover()
    handler.setLevel(logging.DEBUG)
    handler_formatter = logging.Formatter(fmt=fmt)
    handler.setFormatter(handler_formatter)
    return handler, log_file_path
```

**Comment by bmw** [comment]
In addition to the logfiles, Certbot logs to stderr. This is set up [here](https://github.com/certbot/certbot/blob/e32033f1ec6fa910007d2454f6210e27fe7f98d7/certbot/certbot/_internal/log.py#L61-L63) and the logging level is adjusted after parsing command line arguments [here](https://github.com/certbot/certbot/blob/e32033f1ec6fa910007d2454f6210e27fe7f98d7/certbot/certbot/_internal/log.py#L116).  You can provide `--verbose` on the command line for the same information to be logged to both stderr and Certbot's logfiles.
