### ISSUE TITLE
No arguments available in manual hooks

### ISSUE THREAD

**Issue by DrP2016** [certbot/certbot#7617]
Hi everyone,

i am using a GoDaddy domain and succesfully requested a wildcard certificate for this domain via the DNS-01 challenge. I ran this command:
`sudo certbot certonly --manual --manual-public-ip-logging-ok --preferred-challenges dns-01 --server https://acme-v02.api.letsencrypt.org/directory -d "*.mydomain.com" -d mydomain.com`
I added the two Tokens i got shown to the DNS-TXT-Records and certbot succeeded. 

As i want to automate the renewal i wrote both hooks auth.sh and cleanup.sh, but I cant get the arguments $CERTBOT_VALIDATION and $CERTOBT_DOMAIN in my scripts, it doesnt matter if i do a dry-run or not. My Renew-Command looks like this:
`sudo certbot renew --dry-run --manual --manual-auth-hook /etc/letsencrypt/renewal-hooks/pre/auth.sh --manual-cleanup-hook /etc/letsencrypt/renewal-hooks/post/cleanup.sh `
For testing my auth.sh looks like this:
```
#!/bin/bash
echo $@
echo $CERTBOT_VALIDATION
```
And the Script outputs nothing. Am i doing something wrong?

**Comment by alexzorin** [comment]
By placing your cleanup and authentication hook in `/etc/letsencrypt/renewal/hooks/{pre,post}`, you are essentially doing:

    certbot renew --manual-auth-hook /etc/letsencrypt/renewal-hooks/pre/auth.sh \
    --manual-cleanup-hook /etc/letsencrypt/renewal-hooks/post/cleanup.sh \
    --pre-hook /etc/letsencrypt/renewal-hooks/pre/auth.sh \
    --post-hook /etc/letsencrypt/renewal-hooks/post/cleanup.sh

Predictably, this produces confusing results, because the same script is being used for different types of hooks. `--pre-hook` runs first, and of course, `$CERTBOT_VALIDATION` is not set, because `--pre-hook` does not receive any arguments.

If I am guessing your intention correctly, you need to move your hooks outside of `/etc/letsencrypt/renewal-hooks`, and keep them in `/etc/letsencrypt/` or somewhere like that.

**Comment by DrP2016** [comment]
Hi alexzorin,

my certbot version is 0.31.0, installed via apt-get on debian buster. I tried your solution to move my hook-scripts and expanding the certificate. As you mentioned the arguments did not get populated to the `--pre-hook` and `--post-hook` scripts, at least in a dry run. It was quite a wild ride to find out which hooks run at what time, with or without arguments; but i got everything working with your clarification.
Expanding my certificate did the trick to get the `--manual-auth-hook` flag to run correctly, so I replaced the `certbot renew ...`  for testing with `sudo certbot certonly  --dry-run --cert-name mydomain.com --manual --manual-auth-hook /home/user/Authenticator.sh --manual-cleanup-hook /home/user/Cleanup.sh --manual-public-ip-logging-ok --preferred-challenges dns-01 --server https://acme-v02.api.letsencrypt.org/directory -d testtest.mydomain.com`

and i got the result i wanted:

```
>> PRE >> Adding ACME-Token "tokentokentoken" to "_acme-challenge.mydomain.com"
>> PRE >> Added ACME-Token as DNS-TXT-Record!
>> PRE >> Wait 30 seconds until the Token is propagated
```
I know, that it should be `_acme-challenge.testtest.mydomain.com`, but the wildcard certificate covers all subdomains, so my hook only adds the ACME-Token to the maindomain.

My final setup looks like this:
Authenticator.sh
```
#!/bin/bash

#+---------------------------------------------------------------------+
#| Authenticator.sh                                                    |
#|                                                                     |
#|  >> CertBot - Hook Script, adds a DNS-TXT-Record to GoDaddy         |
#|  >> Use for Main-Domain and Wildcards, other subdomains not tested! |
#|                                                                     |
#|                                         Github, DrP2016, 02.12.2019 |
#+---------------------------------------------------------------------+

## GoDaddy API
API_SECRET="GoDaddyProductionApiSecret"
API_KEY="GoDaddyProductionApiKey"
API_URL="https://api.godaddy.com"

## Certbot ACME Variables
ACME_FULL_DOMAIN="${CERTBOT_DOMAIN}"
ACME_MAIN_DOMAIN=${ACME_FULL_DOMAIN#*.}
ACME_SUB_DOMAIN=${ACME_FULL_DOMAIN%%.*}
ACME_TOKEN="${CERTBOT_VALIDATION}"
ACME_NAME="_acme-challenge"
ACME_TTL="600"

echo ">> PRE >> Adding ACME-Token \"${ACME_TOKEN}\" to \"_acme-challenge.${ACME_MAIN_DOMAIN}\""

## Add new DNS-TXT-Record via API Version 1
curl -X PATCH "${API_URL}/v1/domains/${ACME_MAIN_DOMAIN}/records" \
     -H "accept: application/json" \
     -H "Content-Type: application/json" \
     -H "Authorization: sso-key ${API_KEY}:${API_SECRET}" \
     -d "[{\"name\": \"${ACME_NAME}\", \"ttl\": 600, \"data\": \"${ACME_TOKEN}\", \"type\": \"TXT\"}]"

echo ">> PRE >> Added ACME-Token as DNS-TXT-Record!"
echo ">> PRE >> Wait 30 seconds until the Token is propageted"

## Wait
sleep 30
```

Cleanup.sh
```
#!/bin/bash

#+---------------------------------------------------------------------+
#| Cleanup.sh                                                          |
#|                                                                     |
#|  >> CertBot - Hook Script, replaces ALL DNS-TXT-Records on GoDaddy  |
#|     by replacing them with a dummy entry of your choice             |
#|                                                                     |
#|                                         Github, DrP2016, 02.12.2019 |
#+---------------------------------------------------------------------+

## GoDaddy API
API_SECRET="GoDaddyProductionApiSecret"
API_KEY="GoDaddyProductionApiKey"
API_URL="https://api.godaddy.com"

## Certbot ACME Variables
ACME_FULL_DOMAIN="${CERTBOT_DOMAIN}"
ACME_MAIN_DOMAIN=${ACME_FULL_DOMAIN#*.}
ACME_SUB_DOMAIN=${ACME_FULL_DOMAIN%%.*}
ACME_TOKEN="--no-token--"
ACME_NAME="_acme-challenge"
ACME_TTL="600"

echo ">> POST >> Replacing -ALL- of the DNS-TXT-Records with a dummy entry on \"${ACME_MAIN_DOMAIN}\""

## CleanUp DNS-TXT-Records - One entry left, as GoDaddy does not support completely deleting TXT Records 
curl -X PUT "${API_URL}/v1/domains/${ACME_MAIN_DOMAIN}/records/TXT" \
     -H "accept: application/json" \
     -H "Content-Type: application/json" \
     -H "Authorization: sso-key ${API_KEY}:${API_SECRET}" \
     -d "[{\"name\": \"${ACME_NAME}\", \"ttl\": 600, \"data\": \"${ACME_TOKEN}\", \"type\": \"TXT\"}]"

echo ">> POST >> Replaced the DNS-TXT-Records!"
```
Command line for renew that should work (and needs to be added to a weekly cronjob):
`sudo certbot certonly --manual --manual-auth-hook /home/user/Authenticator.sh --manual-cleanup-hook /home/user/Cleanup.sh --manual-public-ip-logging-ok --preferred-challenges dns-01 --server https://acme-v02.api.letsencrypt.org/directory -d mydoman.com -d "*.mydomain.com"`

The only two things that would be interesting to know are: 
1. How long does the authorization for that domain stays flagged as "recently" so i can do a real test-case?
2. In what way would version >0.40.0 affect my setup/usage?

**Comment by alexzorin** [comment]
Good to hear you got it working.

>How long does the authorization for that domain stays flagged as "recently" so i can do a real test-case?

It changes without notice. At the moment it seems to just a bit over 1 month. You can check for yourself in `letsencrypt.log`, finding the `/acme/order/` URL, opening it in your browser, and looking at the `expires` field of each URL listed under `authorizations`.

>In what way would version >0.40.0 affect my setup/usage?

In 0.40.0, `--dry-run` always gets "fresh" authorizations. In other words, it would be easier to test your hook because it would reliably be called every time.

**Comment by DrP2016** [comment]
Hi alexziron,

that is really good news! I have to take a look into updating my certbot to 0.40 so i dont have to wait a month to finally test my setup.
