### ISSUE TITLE
undue expiration email

### ISSUE THREAD

**Issue by paolobenve** [certbot/certbot#7621]
I have a certificate which in the past week I have added more domains.

Today I received an email from expiry@letsencrypt.org, saying:

> Your certificate (or certificates) for the names listed below will expire in 9 days (on 13 Dec 19 04:15 +0000).

However, `certbot-auto certificates` tells me that that certificate has 

> Expiry Date: 2020-01-31 12:20:15+00:00 (VALID: 58 days)

It looks like the email source hasn't updated the certificate expiration date the last time a domain was added to it (and the certificate was therefore renewed).

**Comment by alexzorin** [comment]
Hi Paolo,

The expiration emails aren't a part of the Certbot project. Your question would be welcome on the Let's Encrypt community forums at https://community.letsencrypt.org/ .

>I have a certificate which in the past week I have added more domains.

Getting unexpected expiration emails is a common side effect when you add new domains to a certificate. 

There is some information about this phenomenon on this page: https://letsencrypt.org/docs/expiration-emails/#when-you-get-an-expiration-email

Specifically:

>We consider a certificate to be renewed if there is a newer certificate with the exact same set of names, regardless of which account created it. If you’ve issued a new certificate that adds or removes a name relative to your old certificate, you will get expiration email about your old certificate

If you've got further questions or feedback about it, please join us on the forums!
