### ISSUE TITLE
Certbot keep in memory old domains

### ISSUE THREAD

**Issue by tutosfaciles48** [certbot/certbot#7626]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
debian buster 10.0

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
I install certbot with pip3

## I ran this command and it produced this output:
`/usr/local/bin/certbot certonly --dns-ovh --dns-ovh-credentials /root/.ovhapi --non-interactive --agree-tos --email me@email.fr -d domain.tld` (OK)

`/usr/local/bin/certbot certonly --dns-ovh --dns-ovh-credentials /root/.ovhapi --non-interactive --agree-tos --email me@email.fr -d *.domain.tld` -->Failed

## Certbot's behavior differed from what I expected because:
`
Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate.
certbot: error: unrecognized arguments: dl.domain.tld ipv6.domain.tld misc.domain.tld scontent.domain.tld
`
(probably) Cause: By the past, I manually add the domains (and uninstall certbot before delete him)
I also reinstall the system

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
Not applicable

**Comment by schoen** [comment]
Hi @tutosfaciles48,

In this case I think you're just having a problem with your Unix shell interpreting the `*.domain.tld` as a shell wildcard and replacing it with names of files that are found in the current directory. Instead of `*.domain.tld` you should write `"*.domain.tld"` in your command line to protect the wildcard from the shell and ensure that Certbot itself sees it.

**Comment by schoen** [comment]
You can also see this contrast with

`echo domain.tld`

`echo *.domain.tld`

`echo "*.domain.tld"`

**Comment by bmw** [comment]
I think @schoen answered you question so I'm closing this issue.
