### ISSUE TITLE
Aggressive `certbot delete` behavior can delete all

### ISSUE THREAD

**Issue by beret** [certbot/certbot#7629]
#6218 should be reopened as it was closed as stale.

This issue/potential enhancement is still relevant and unresolved in the current PPA codebase. Enter at a blank selection will erase all certs. An explicit selection or confirmation (as described in the past ticket)  may be more suited to provide delete all.

As it stands, an errant enter keypress with a blank selection can efficiently wreck an environment.

**Comment by alexzorin** [comment]
Did you mean to link a different issue?

**Comment by beret** [comment]
Yes, thank you! It's #6218 - Certbot might delete all certificates

**Comment by bmw** [comment]
Thanks for flagging this. I'm reopening #6218.
