### ISSUE TITLE
Update the pinned version of lexicon after we drop Python 3.4 support

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7631]
A number of issues in our DNS plugins can be fixed by using a new version of Lexicon such as

* https://github.com/certbot/certbot/issues/6972
* https://github.com/certbot/certbot/issues/7411
* https://github.com/certbot/certbot/issues/7425

Unfortunately, we cannot easily update the version of Lexicon pinned in this repo causing a new version of Lexicon to be used in our Docker images because Lexicon has dropped Python 3.4 support and we have not. Once we've done this (which is tracked by https://github.com/certbot/certbot/issues/7393), we should update the version of Lexicon pinned in `tools/dev_constraints.txt` to the latest version.

**Comment by bmw** [comment]
This issue is blocked on https://github.com/certbot/certbot/pull/7709 because dependencies like `requests` need to be updated to use the latest version of `dns-lexicon`.

**Comment by adferrand** [comment]
> 
> 
> This issue is blocked on #7358 because dependencies like `requests` need to be updated to use the latest version of `dns-lexicon`.

Unblocked ^^

**Comment by bmw** [comment]
Thanks 😄
