### ISSUE TITLE
renew-hook script not found in PATH but it is there

### ISSUE THREAD

**Issue by wsw70** [certbot/certbot#7635]
# My operating system is (include version):

Ubuntu 18.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

docker (image is `certbot/dns-ovh`)

## I ran this command and it produced this output:

```
# /usr/bin/docker run \
--rm \
-v /etc/docker/container-data/certbot/etc/letsencrypt:/etc/letsencrypt \
-v /etc/docker/container-data/certbot/var/lib/letsencrypt:/var/lib/letsencrypt \
-v /etc/docker/container-data/certbot/var/log/letsencrypt:/var/log/letsencrypt \
-v /tmp:/hook \
certbot/dns-ovh \
certonly \
-n \
--server https://acme-v02.api.letsencrypt.org/directory \
--dns-ovh \
--dns-ovh-credentials /etc/letsencrypt/ovh.ini \
-d *.something.something \
--email someone@somewhere \
--agree-tos \
--renew-hook "/usr/local/bin/docker-compose -f /etc/docker/docker-compose.d/10-caddy.yaml restart"

Unable to find renew-hook command /usr/local/bin/docker-compose in the PATH.
(PATH is /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
```

## Certbot's behavior differed from what I expected because:

The renew hook script **is** in the PATH:

```
 # ll /usr/local/bin/docker-compose
-rwxr-xr-x 1 root root 16M May  3  2019 /usr/local/bin/docker-compose
```

**Comment by alexzorin** [comment]
The `--renew-hook` runs *inside* the Docker container, not on your Docker host.

`/usr/local/bin/docker-compose` is not included with the `certbot/dns-ovh` image, so the error message is correct.

If you wanted to do this, you would need to mount both `docker-compose` and your Docker daemon socket inside the container.

**Comment by alexzorin** [comment]
I'm going to close this because you've opened [a thread on the community forums](https://community.letsencrypt.org/t/renew-hook-script-not-found-in-path-but-it-is-there/108137?u=_az), which is definitely a better place for this question. Thanks!

**Comment by wsw70** [comment]
@alexconlin oh yes, you are right, thank you very much! - I completely forgot that the command would run in the docker file. I will update my question in the forum with the setup which works:

```
(...)
-v /var/run/docker.sock:/var/run/docker.sock \
-v /usr/local/bin/docker-compose:/usr/local/bin/docker-compose \
-v /etc/docker/docker-compose.d/10-caddy.yaml:/tmp/caddy.yaml \
(...)
--renew-hook "/usr/local/bin/docker-compose -f /tmp/caddy.yaml restart"
```
