### ISSUE TITLE
HTTP status codes fail to be parsed when using an old version of the requests library

### ISSUE THREAD

**Issue by regner** [certbot/certbot#7651]
## My operating system is (include version):
CentOS 7

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Installed with Puppet using the letsencrypt module (https://forge.puppet.com/puppet/letsencrypt/)

We are specifically on cerbot 0.39.0, however as far as I can tell this issue would be present in 1.0.0 as well.

## I ran this command and it produced this output:
certbot --text --agree-tos --non-interactive --test-cert certonly --rsa-key-size 4096 --cert-name 'something' -d 'derp.domain.com' --dns-nsone --dns-nsone-credentials /etc/letsencrypt/nsone.ini --debug

## Certbot's behavior differed from what I expected because:
It failed to create the TXT record at all.

## Here is a Certbot log showing the issue (if available):
```bash
(22:44:48)-user@somevm:~# certbot --text --agree-tos --non-interactive --test-cert certonly --rsa-key-size 4096 --cert-name 'something' -d 'derp.domain.com' --dns-nsone --dns-nsone-credentials /etc/letsencrypt/nsone.ini --debug
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-nsone, Installer None
Starting new HTTPS connection (1): acme-staging-v02.api.letsencrypt.org
Renewing an existing certificate
Performing the following challenges:
dns-01 challenge for derp.domain.com
Starting new HTTPS connection (1): api.nsone.net
Cleaning up challenges
Starting new HTTPS connection (1): api.nsone.net
Exiting abnormally:
Traceback (most recent call last):
  File "/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.39.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 1378, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 1265, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 116, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/lib/python2.7/site-packages/certbot/renewal.py", line 307, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 348, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 384, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 69, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/lib/python2.7/site-packages/certbot/plugins/dns_common.py", line 58, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/lib/python2.7/site-packages/certbot_dns_nsone/dns_nsone.py", line 51, in _perform
    self._get_nsone_client().add_txt_record(domain, validation_name, validation)
  File "/usr/lib/python2.7/site-packages/certbot/plugins/dns_common_lexicon.py", line 40, in add_txt_record
    self._find_domain_id(domain)
  File "/usr/lib/python2.7/site-packages/certbot/plugins/dns_common_lexicon.py", line 95, in _find_domain_id
    raise result
PluginError: Error determining zone identifier: 404 Client Error: Not Found.
Please see the logfiles in /var/log/letsencrypt for more details.
```

## The Issue

The plugins (in our case cerbot-dns-nsone) require `dns-lexicon>=2.2.1`.  That package uses the Python `requests` package but critically does NOT specify a package version in its dependency.

I am raising this issue here because the version of `requests` doesn't really effect `dns-lexicon` however the plugins for `certbot` do actually depend on a minimum version of the `requests` library.

A specific example, and what caused me to run into this, is this line here: https://github.com/certbot/certbot/blob/v0.39.0/certbot-dns-nsone/certbot_dns_nsone/dns_nsone.py#L76

The plugin is looking for a string that starts a very specific way. However that string has not always been the same. In version 2.8.0 of the `requests` library that string changed.

The commit causing the change is here: https://github.com/psf/requests/commit/e3bdec5934a4bdd00405acbb714aec81980f6097

On a fresh install of CentOS 7 running the puppet module ends us with version 2.6.0 of the `requests` library. 

Don't get me wrong, this is a laughably old version of the `requests` library and we will upgrade it which will solve our problem. However there should probably be an excplicit dependency listed on `requests>=2.8.0`.

**Comment by regner** [comment]
Continuing the fun, when installing `certbot` via package on CentOS 7 it depends on the package `python-requests`. Makes sense. Except the newest version available in yum is 2.6.0-8.

yaaaaayyyyyyyyyyy

**Comment by joohoi** [comment]
Thanks for opening the issue and debugging the root cause, it helps a lot! 

When installing Certbot from the distributions own package repositories, the packagers are in many cases required to split the dependencies to separate packages or using already existing ones. As `python-requests` is used by multiple packages, updating it may break other things depending on it.

This may, or may not be the case here as well, but I'm thinking of changing the error message parsing code in the `dns-nsone` plugin.

**Comment by regner** [comment]
That makes sense. Glad I could help in some way.
