### ISSUE TITLE
Potential dependency conflicts between acme and requests

### ISSUE THREAD

**Issue by NeolithEra** [certbot/certbot#7655]
Hi, as shown in the following full dependency graph of  **_acme_**, **_acme_** requires **_requests >=2.4.1_**， while the installed version of **_requests-toolbelt_**(0.9.1) requires _**requests >=2.0.1,<3.0.0**_.

According to Pip's _“first found wins”_ installation strategy, _**requests 2.22.0**_ is the actually installed version.  

Although the first found package version _**requests 2.22.0**_ just satisfies the later dependency constraint （_**requests  >=2.0.1,<3.0.0**_), it will lead to a build failure once developers release a newer version of **_requests_**.
### Dependency tree--------
```
acme - 0.30.0
| +- cryptography(install version:2.8 version range:>=0.8)
| +- josepy(install version:1.2.0 version range:>=1.0.0)
| | +- cryptography(install version:2.8 version range:>=0.8)
| | +- pyopenssl(install version:19.1.0 version range:>=0.13)
| | | +- cryptography(install version:2.8 version range:>=2.8)
| | | +- six(install version:1.13.0 version range:>=1.5.2)
| | +- setuptools(install version:42.0.2 version range:>=1.0)
| | +- six(install version:1.13.0 version range:>=1.9.0)
| +- mock(install version:3.0.5 version range:*)
| +- pyopenssl(install version:19.1.0 version range:>=0.13)
| | +- cryptography(install version:2.8 version range:>=2.8)
| | +- six(install version:1.13.0 version range:>=1.5.2)
| +- pyrfc3339(install version:1.1 version range:*)
| | +- pytz(install version:2019.3 version range:*)
| +- pytz(install version:2019.3 version range:*)
| +- requests(install version:2.22.0 version range:>=2.4.1)
| | +- certifi(install version:2019.11.28 version range:>=2017.4.17)
| | +- chardet(install version:3.0.4 version range:<3.1.0,>=3.0.2)
| | +- idna(install version:2.8 version range:>=2.5,<2.9)
| | +- urllib3(install version:1.25.7 version range:<1.26,>=1.21.1)
| +- requests-toolbelt(install version:0.9.1 version range:>=0.3.0)
| | +- requests(install version:2.22.0 version range:>=2.0.1,<3.0.0)
| | | +- certifi(install version:2019.11.28 version range:>=2017.4.17)
| | | +- chardet(install version:3.0.4 version range:<3.1.0,>=3.0.2)
| | | +- idna(install version:2.8 version range:>=2.5,<2.9)
| | | +- urllib3(install version:1.25.7 version range:<1.26,>=1.21.1)
| +- setuptools(install version:42.0.2 version range:*)
| +- six(install version:1.13.0 version range:>=1.9.0)
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution

Fix your direct dependencies to be **_requests >=2.4.1, <3.0.0_** to remove this conflict. I have checked this revision will not affect your downstream projects now.

@bmw May I pull a request to solve this issue?

**Comment by bmw** [comment]
Thanks for the detailed issue and PR @NeolithEra, but I don't think we should change anything on our end.

Duplicating `requests-toolbelt` dependencies in `acme` gives us the burden of monitoring their dependencies and remembering to update our `acme` module when they change. It can also cause `acme` to break for the same reason that you described here if `acme` is installed through `pip` as a dependency of other software that depends on both `acme` and `requests`.

In general, I recommend that people don't install our code through `pip` and instead use the installation mechanism recommended for your system at https://certbot.eff.org/instructions which avoids these problems one way or another.

Luckily, the real resolution of this issue in my opinion is https://github.com/pypa/pip/issues/988 which is being actively being worked on.
