### ISSUE TITLE
Ubuntu ppa missing packages for 19.10 (eoan)

### ISSUE THREAD

**Issue by paulschreiber** [certbot/certbot#7658]
The Ubuntu PPA is missing builds for 19.10 (eoan)
http://ppa.launchpad.net/certbot/certbot/ubuntu/dists/

**Comment by bmw** [comment]
We're tracking issues like this at https://docs.google.com/document/d/1AW1Lcm7Sb7VaxwbBbaPiuIt77BNS0phtyS3qwNNyEso/edit?usp=sharing but I'm happy to leave this issue open so people can easily get updates when it's resolved.

cc @devec0

**Comment by bmw** [comment]
We're deprecating the PPA with the plan to make use of [Certbot's SRU exception](https://wiki.ubuntu.com/StableReleaseUpdates/Certbot) so I'm closing this issue.

If you're interested, there are also Certbot snaps available which you can find instructions for using at https://certbot.eff.org/instructions.

**Comment by andreymal** [comment]
@bmw snaps are awful
