### ISSUE TITLE
AcmeV2 error on CentOS 7.x with latest version from Epel.

### ISSUE THREAD

**Issue by bdelamatre** [certbot/certbot#7666]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):

CentOS 7.7

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Epel (version 1.0.0 installed)

## I ran this command and it produced this output:

certbot --text --agree-tos --non-interactive certonly --rsa-key-size 4096 -a webroot --cert-name 'grafana.3pth.com' --webroot-path /usr/share/nginx/html -d 'mydomain.com'

Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
An unexpected error occurred:
The client lacks sufficient authorization :: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2
/ RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.

## Certbot's behavior differed from what I expected because:

Expected a certificate to be issued. 

Not really sure what I am supposed to do in this scenario even after reading the documentation in the error message. I am using the latest version of Certbot as far as I can tell, I am using the latest Centos 7.x release, I installed the package from Epel per the documentation (https://certbot.eff.org/lets-encrypt/centosrhel7-apache.html) and as far as I can tell I shouldn't need to specify which Acme version I am using. 

Am I missing something?

**Comment by alexzorin** [comment]
It may be that some configuration file (like `/etc/letsencrypt/cli.ini`) on your system is forcing Certbot to use the old ACME server.

    grep -R acme-v01 /etc/letsencrypt

**Comment by bmw** [comment]
If you're still having this issue, it's likely due to your preference for Let's Encrypt's old endpoint being explicitly set somewhere like alexzorin said. If you need additional help, I recommend posting to https://community.letsencrypt.org where there is a large community of people familiar with Certbot who can help you.
