### ISSUE TITLE
nginx leaves dirty/modified config files

### ISSUE THREAD

**Issue by marcan** [certbot/certbot#767]
When letsencrypt-renewer is run, it makes temporary changes to the web server configs, reformatting everything in the process (at least for nginx). Those changes are not fully cleaned up after the renewer is done. Running 'letsencrypt config_changes' after as a workaround implicitly performs that cleanup (`rev.recovery_routine()`) and puts back the original config files. The renewer should be doing this itself.

Note: my use case is letting letsencrypt manage config changes for domain validation, but making the persistent changes to deploy the new certs myself; thus, I don't expect letsencrypt to ever make lasting changes to my nginx config files.

**Comment by bmw** [comment]
This is not technically a renewer problem, but a Nginx problem. The renewer modifies files in the Let's Encrypt configuration directory, but relies on the plugins to make modifications to the web server configuration if necessary. Removing the `renewer` label.

**Comment by tcz001** [comment]
Any instruction to reproduce this?

**Comment by pde** [comment]
@marcan I realise this report was a while ago, but there's a team now polishing the nginx plugin for release; is there any chance you could still provide repro instructions?

**Comment by bmw** [comment]
Fixed in #3204.
