### ISSUE TITLE
Determine and set up Certbot snap channels for beta

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7670]
You can read about snap channels at https://snapcraft.io/docs/channels.

I personally don't think we need multiple "tracks" or "branches", but I would like to make use of multiple "risk-levels". During the Certbot snap beta, I think we should have the latest, stable version of Certbot in "latest/beta". I'd like to more regularly push to "latest/edge" and for now suggest it's done nightly.

What do people think?

**Comment by adferrand** [comment]
I think it is a sane way to deal with the releasing at this time.

As a side note, after the snap moved out from beta, I think the beta channel could still be useful. Indeed we see that regularly we need to push point releases few days after the minor one (mostly about certbot-auto that said). We could consider pushing a new minor version to beta first, and to stable only one, two weeks, or a month after. 

It would give us the time to catch tricky bugs before they impact the largest users population. This becomes particularly relevant, in my opinion, considering that snaps will become the almost only way to get the new version of Certbot, while currently it is balanced between an immediate availability through certbot-auto, and with weeks/months of delay through OS packages.

**Comment by bmw** [comment]
I think we have a pretty good plan here and haven't heard any objections or alternate suggestions so I think we should go forward with this and close this issue.
