### ISSUE TITLE
sudo certbot certonly -- nginx --ERROR

### ISSUE THREAD

**Issue by li-jiancheng** [certbot/certbot#7676]
## My nginx is not under / etc / nginx, but when I use sudo certbot certonly -- nginx, I will go to / etc / nginx / nginx.conf by default. What shall I do?  I'm CentOS 7

## error log
PluginSelectionError: The nginx plugin is not working; there may be problems with your existing configuration.
The error was: MisconfigurationError('Error while running nginx -c /etc/nginx/nginx.conf -t.\n\nnginx: [emerg] open() "/etc/nginx/mime.types" failed (2: No such file or directory) in /etc/nginx/nginx.conf:16\nnginx: configuration file /etc/nginx/nginx.conf test failed\n',)

**Comment by m0namon** [comment]
Hi, thanks for reporitng!

You can use the `--nginx-server-root` flag to specify the directory that contains your server configuration files. For instance, this might be invoked as `--nginx-server-root /etc/nginx`. More info here: https://certbot.eff.org/docs/using.html#certbot-command-line-options

Closing for now; feel free to ask me to re-open if you're still having trouble, or make a new issue. You can also ask for usage help on https://community.letsencrypt.org/ , where there's a large audience of people familiar with the project. You might be able to get a faster answer there in the future.
