### ISSUE TITLE
Valid & invalid DNS response at the same time

### ISSUE THREAD

**Issue by PELock** [certbot/certbot#7679]
Debian Buster, certbot-auto v1.0.0

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Please deploy a DNS TXT record under the name
_acme-challenge.domain.com with the following value:

**-q8shkQajDXfUQGfUywK10EEATA74xO9bzSo0DPyny4**

Before continuing, verify the record is deployed.
(This must be set up in addition to the previous challenges; do not remove,
replace, or undo the previous challenge tasks yet. Note that you might be
asked to create multiple distinct TXT records with the same name. This is
permitted by DNS standards.)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Press Enter to Continue
Waiting for verification...
Challenge failed for domain domain.com
dns-01 challenge for domain.com
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: domain.com
   Type:   unauthorized
   Detail: Incorrect TXT record
   "**-q8shkQajDXfUQGfUywK10EEATA74xO9bzSo0DPyny4**" found at
   _acme-challenge.domain.com

So how can it be it request the exact DNS response it get, but it's invalid???

**Comment by bmw** [comment]
Looking at the server logs, it appears you were trying to request a single certificate for `*.example.com` and `example.com`. When you do this, you need to create multiple TXT records for `_acme-challenge.example.com` with each value output by Certbot.

`-q8shkQajDXfUQGfUywK10EEATA74xO9bzSo0DPyny4` was the contents of one of the expected TXT records, but not the other. Let's Encrypt successfully found this record, but was unable to find the other one so they generated this error message.

If you need additional help with this, please post to https://community.letsencrypt.org where there is a large group of people familiar with Let's Encrypt and Certbot who should be able to help you further.

**Comment by PELock** [comment]
Good to know it needs multiple records because the console messages doesn't say a word about it!

**Comment by bmw** [comment]
If you're performing DNS challenges with the manual plugin for multiple domains (such as `*.example.org` and `example.org`), the output should look like:
```
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Please deploy a DNS TXT record under the name
_acme-challenge.example.org with the following value:

ew7fvyN0NG91Lx7fcMz5UmpCEjXDJWJZF3KrpICSEoY

Before continuing, verify the record is deployed.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Press Enter to Continue

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Please deploy a DNS TXT record under the name
_acme-challenge.example.org with the following value:

B8aDrsTwLRaz0qCTWPF-Mynd5fkbnhebhzgJ-Y6ESsY

Before continuing, verify the record is deployed.
(This must be set up in addition to the previous challenges; do not remove,
replace, or undo the previous challenge tasks yet. Note that you might be
asked to create multiple distinct TXT records with the same name. This is
permitted by DNS standards.)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Press Enter to Continue
```
If that's not what you saw, I'd be happy to take a look, but please open a new issue and completely fill out the issue template.

**Comment by PELock** [comment]
That's what I saw, but I thought I had to deploy the same record each time because it expired, the message wasn't clear enough that it should be 2 of them at the same time.
