### ISSUE TITLE
Old version of certbot in ubuntu repo

### ISSUE THREAD

**Issue by podolinek** [certbot/certbot#7688]
Hello,

are any plans for update repo on ubuntu?

I am using certbot installed from certbot repository (certbot/certbot) and last version installed on my Ubuntu 18.04 is 0.31.0-1. I updated acme servers of old certificates and try --dry-run option, but fails - returned 

> *.conf produced an unexpected error: urn:ietf:params:acme:error:malformed :: The request message was malformed :: Method not allowed. Skipping."

I found it is caused by old certbot, but I have last from repo...

Thanks.

**Comment by bmw** [comment]
The PPA not having the latest packages is being tracked by https://github.com/certbot/certbot/issues/6770.

The packages currently in the PPA work though. One person who had a similar problem resolved it by updating python3-acme through the command:
```
apt update && apt install --only-upgrade python3-acme
```
See https://community.letsencrypt.org/t/attempting-to-renew-cert-from-etc-letsencrypt-renewal-domain-conf-produced-an-unexpected-error-urnparamserror-malformed-the-request-message-was-malformed-method-not-allowed-skipping/110021 for more info about that.

If you need additional help, I recommend posting to https://community.letsencrypt.org where there is a large group of people familiar with Certbot who should be able to help you better than the small Certbot development team we have here.

**Comment by podolinek** [comment]
Ha, problem with acme library was caused installed by python2.7 as default. 

switch to 3 by update alternatives solved the problem.
