### ISSUE TITLE
Properly use collections.abc

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7692]
Python 3.9 is planning on enforcing that abstract base classes in the collections module are imported from `collections.abc`. See https://docs.python.org/3/library/collections.html#module-collections.

We currently are not always doing this in Certbot and are ignoring the deprecation warning about it at https://github.com/certbot/certbot/blob/6e07e8b5c0f3c6da2ae03a2a63adc7ce8e15a202/pytest.ini#L16

Properly testing and finding all occurrences of this problem is a little tricky (see https://github.com/certbot/certbot/issues/7691), but we should fix this and remove the `pytest.ini` entry well before Python 3.9 is released.

**Comment by tirkarthi** [comment]
Report in Fedora : https://bugzilla.redhat.com/show_bug.cgi?id=1793478
