### ISSUE TITLE
Certbot forgets key size

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7694]
If you run a command like
```
sudo certbot certonly -d example.org --standalone --rsa-key-size 4096
```
it will result in a renewal configuration file containing the following renewal parameters:
```
rsa_key_size = 4096
authenticator = standalone
```
If you then run
```
sudo certbot certonly -d example.org --standalone --reuse-key --force-renewal
```
`rsa_key_size` is dropped from the renewal configuration file despite it still being a 4096 bit key.

I think we should preserve this value.

**Comment by osirisinferi** [comment]
Not sure if this is related or perhaps should be in its own issue, but the `certbot` output is also confusing:

```
(...)
Reusing existing private key from /etc/letsencrypt/live/example.com/privkey.pem.
Generating 2048 bits RSA key
(...)
```

While I tested with `--rsa-key-size 4096` too.

**Comment by bmw** [comment]
@osirisinferi I wasn't able to reproduce this. Do you have the RSA key size set explicitly to 2048 in something like `/etc/letsencrypt/cli.ini`?

If not, can you open a new issue describing how to reproduce this so we can take a look?

**Comment by osirisinferi** [comment]
@bmw Sorry, my bad, I had my git branched from `master` (trying to look into this issue), but my server was still running my custom ECDSA branch.. :blush: 

I'm having a hard time figuring out where the config item is dropped though :stuck_out_tongue:
