### ISSUE TITLE
Certbot fails to work with Apache vhost site setup when they are placed in sub directories using IncludeOptional

### ISSUE THREAD

**Issue by glennpierce** [certbot/certbot#7714]
## My operating system is (include version):
Centos7

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
pip

## I ran this command and it produced this output:

I was trying to setup up an number of sites by organising the apache vhost setups in sub directories on the conf.d folder.
I did this by specifying 
IncludeOptional conf.d/mysite/ 

This allows apache to read conf files from that directory and any directories under that.
The site works fine in the browser

 When running certbot I get the error

certbot --apache -d ****************
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator apache, Installer apache
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for *******************
Waiting for verification...
Challenge failed for domain *******************
http-01 challenge for ******************************
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: ***************
   Type:   unauthorized
   Detail: Invalid response from
   *******************/.well-known/acme-challenge/8wmdI2VGuHzUeUiNiY-dPQrWiYNFf5iFrCOZq3LbsoM
   [89.200.139.212]: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML
   2.0//EN\">\n<html><head>\n<title>404 Not
   Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.

If I move the .conf files for the apache setup directly to the apache conf.d directory
then certbot succeeds. So it seems certbot does not like vhost configs placed in subdirectories.

## Certbot's behavior differed from what I expected because:

Certbot should work with apache conf subdirectories.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

[certbot.log](https://github.com/certbot/certbot/files/4102990/certbot.log)

**Comment by joohoi** [comment]
Thanks for opening the issue, Certbot should be able to work with subdirectories as well. What is your exact inclusion directive there (and the full file path to the virtualhost file in question)?

I'm thinking that `IncludeOptional conf.d/mysite/` might not be specific enough, and that it probably should be `IncludeOptional conf.d/mysite/*` instead.

**Comment by glennpierce** [comment]
I think it may have been as I had *.inc and *.conf files under the subdirectory and the apache was reading the inc files as well as the conf file that includes the inc files.
I think we can close the issue and it was likely a bad configuration.

Thanks
