### ISSUE TITLE
certbot-ci and accounts from previous runs

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7716]
As reported at https://github.com/certbot/certbot/pull/7583#issuecomment-577433664, if you had used `certbot_test` with an ACME server that is no longer running, running mosts commands will fail after starting a new server because the account saved at `.certbot_test_workspace` no longer exists.

What can we do to avoid devs hitting these issues?

**Comment by Tugzrida** [comment]
My first thought was that something could be added to the pebble script that removes the account details from `.certbot_test_workspace` on every startup, although I'm not sure if this would hinder other test cases. Maybe add an option to do it?

**Comment by bmw** [comment]
Good idea.

To iterate on that slightly, I think the design that initially seems best to me is to unconditionally rename any existing `.certbot_test_workspace` directory to something like `.certbot_test_workspace.<timestamp>.bak` when starting a new server. This preserves the directory but gets it out of your way by default. We take this approach in some of our other dev scripts like our `tools/venv*.py` scripts at https://github.com/certbot/certbot/blob/2f24726d4cd8fa9b6c58cf8e80876082c960ab73/tools/_venv_common.py#L175

**Comment by adferrand** [comment]
It was my initial design to rollout the temporary folders at each run, but removed it for sake of simplicity, because initial implementation of certbot-ci was already quite complex.

Time to improve that!

**Comment by adferrand** [comment]
Still relevant.
