### ISSUE TITLE
Remove ssllabs from Certbot output

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7728]
When testing our Apache plugin on CentOS 6, I was surprised to find a "B" score from https://www.ssllabs.com/. The reason this happened is that SSL Labs tries to connect to your site without SNI and includes your server's behavior without SNI in your score.

Our Apache plugin has always expected connecting clients to support SNI and I do not think we need to change this behavior. Because of it affecting your score from SSL Labs though, I think we should remove the link to SSL Labs from Certbot's output as I think it has the potential to confuse users.

This has already been proposed at https://docs.google.com/document/d/1aKnQYEzCrZgYX-iuE-ErOdIKERUuLmZSX_BDb7d0M6I/edit which has alternate text we should use instead.

**Comment by ohemorange** [comment]
Wait, are we sure we don't actually want to fix this? Your server's behavior without SNI seems important as a potential security hole. Does this only happen on CentOS 6?

**Comment by bmw** [comment]
To explain a bit more myself, what's going on here is if there is no SNI value that Apache can use to differentiate between SSL vhosts, it will fall back to the default SSL vhost. Certbot may not have modified this virtual host because we only modify the vhosts for the domains you request certs for.

You can reproduce this on other OSes and even with the nginx plugin if we don't modify the default HTTPS server block for whatever reason.

If we didn't modify the vhost, this vhost would be using a different certificate that isn't trusted for the domain (unless the user manually configures it that way). If the default SSL certificate is untrusted, SSL Labs also adds a warning to the top saying "This site works only in browsers with SNI support." At least from the standpoint of HTTPS, this setup seems pretty safe to me because if an attacker did something like strip out the SNI value, the certificate used by the server wouldn't be trusted.

Does that assuage your concerns or is there something else here that I might be overlooking?

**Comment by ohemorange** [comment]
Are we sure this is what's happening? That seems like a weird choice for SSL Labs to have made. I agree that the situation you're describing seems safe, and I'm surprised that SSL Labs would disagree, unless there's something about the situation that I'm missing. Do you have an example result you could point to? Looking at [a recent example](https://www.ssllabs.com/ssltest/analyze.html?d=kongregate.com&s=13.35.125.98) from their results list, it seems like SSL Labs does give A grades while having the "This site works only in browsers with SNI support" banner.

**Comment by bmw** [comment]
Yeah I'm pretty sure that's what's going on.

I tested this on a bunch of systems using SSL Labs, `nmap`, and `openssl s_client` client side to test the server while recording the network traffic server side to look at in Wireshark. When the default vhost supports SSLv3 both SSL Labs and `nmap` list SSLv3 as supported for the domain and you can connect to the server using SSLv3 with `openssl`.

In all cases though, the certificate being returned by the server is the one configured in the default virtual host. This initially seems like strange behavior to me from tools like `nmap`, but looking into the issue, SSLv3 technically doesn't support SNI because it is a TLS extension and neither `nmap` or `openssl` send the value when using SSLv3. In this case, the web server is falling back to the default vhost using a different certificate as we'd expect.

(With that said, [SSLv3 does leave space in the protocol at the end of the client hello for arbitrary data with the goal of forwards compatibility](https://tools.ietf.org/html/rfc6101#section-5.6.1.2). This is where TLS extensions would go if they were defined for SSLv3 and I have packet captures showing SSL Labs adding the SNI extension to SSLv3 despite being told from [SSL Labs devs that SNI isn't supported in SSLv3](https://discussions.qualys.com/thread/20547-inconsistent-behavior-from-ssl-labs-without-sni#comment-50243). When SSL Labs does it though, Apache rejects the handshake at least when the vhost for that domain doesn't support SSLv3.)

I completely agree that this is strange behavior from SSL Labs though. I have a thread suggesting they change the behavior or at the very least enlighten us why they have it if there is a good reason for it that we may not be aware of, but I have not gotten a good answer yet. That thread is at https://discussions.qualys.com/thread/20547-inconsistent-behavior-from-ssl-labs-without-sni. I'm planning to continue to push the issue though.
