### ISSUE TITLE
Certbot package missing in backports PPA for Ubuntu - can't upgrade to v2 protocol

### ISSUE THREAD

**Issue by issmirnov** [certbot/certbot#7736]
Hello all,

I received a notification email that my client is using the v1 ACME protocol. Upon investigating the upgrade path, I realized I don't see a viable way to install v1.1.0 on Ubuntu 18.04 LTS.

Output of `apt search ^certbot`:

```
certbot/bionic,bionic,now 0.31.0-1+ubuntu18.04.1+certbot+1 all [installed]
  automatically configure HTTPS using Let's Encrypt
```

Checking the `certbot/certbot` PPA (https://launchpad.net/~certbot/+archive/ubuntu/certbot) which is linked in the [install instructions](https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx) I see that it's entirely missing the certbot package:

![image](https://user-images.githubusercontent.com/5771615/73615044-b23f9880-45b9-11ea-848d-4564c2654a17.png)

Cross checking with this command also shows that the package is not present in the PPA.
```
grep ^certbot /var/lib/apt/lists/ppa.launchpad.net_certbot_certbot_ubuntu_dists_bionic_main_binary-amd64_Packages
# no results found
```

So, two issues here.

1. Certbot is missing from the PPA
2. There doesn't seem to be a way to install a v2 compatible certbot client on ubuntu 18.04

**Comment by alexzorin** [comment]
0.31, the version packaged for Ubuntu Bionic in the PPA, is compatible with and defaults to the ACME v2 server. 

The Ubuntu packages additionally include fixes backported from future versions as necessary to keep working.

I'd double check that you haven't got acme-v01 hardcoded somewhere in your configuration - that would result in Certbot downgrading from ACME v2 to ACME v1:

  sudo grep -R --exclude-dir=accounts acme-v01 /etc/letsencrypt

**Comment by issmirnov** [comment]
@alexzorin thank you, good to know that 0.31 is compatible with v2.

Thank you - I checked and turns out I had the server hardcoded in every single config. I've updated my ansible role to reflect the new endpoint. I was able to update all the existing configs with a simple:

```
find /etc/letsencrypt  -type f -exec sed -i 's/acme-v01/acme-v2/g' {} \;
```

**Comment by alexzorin** [comment]
>I was able to update all the existing configs

Great! That should be `acme-v02` - the full URL is `https://acme-v02.api.letsencrypt.org/directory`.

**Comment by issmirnov** [comment]
Ah, good catch!
