### ISSUE TITLE
RandomizedDelaySec conflict in certbot.timer 

### ISSUE THREAD

**Issue by udf2457** [certbot/certbot#7739]
The packaged `/lib/systemd/system/certbot.timer ` seems to set `RandomizedDelaySec=43200`

This seems rather nonsensical ?

Unless my maths is wrong, 43200 = 12 hours.

`certbot.timer` is scheduled to run every 12 hours (`OnCalendar=*-*-* 00,12:00:00`)

So it seems rather silly to wait up to 12 hours betwen a run ?

Not only that but you have a potential race condition by setting 12 hours ?

Let's say the 12:00 execution decides to "randomly" wait 12 hours.  That means it will run at 00:00. Meanwhile the 00:00 execution starts and decides to run at 00:01.

Surely `RandomizedDelaySec=3600` would be more than sufficient ?

**Comment by osirisinferi** [comment]
Correct me if I'm wrong, but the certbot team doesn't package packages with systemd timers. At least I couldn't find it in the Ubuntu PPA package.

Perhaps you could explain more about the distribution you're using and where you're getting your certbot from?

**Comment by udf2457** [comment]
@osirisinferi `apt-get install certbot` on Debian 10 (as per the offical Certbot install guidelines).

```
Package: certbot
Source: python-certbot
Version: 0.31.0-1
Installed-Size: 68
Maintainer: Debian Let's Encrypt <team+letsencrypt@tracker.debian.org>
Architecture: all
Replaces: letsencrypt
Provides: letsencrypt
Depends: python3-certbot (= 0.31.0-1), python3:any
Suggests: python3-certbot-apache, python3-certbot-nginx, python-certbot-doc
Breaks: letsencrypt (<= 0.6.0)
Description-en: automatically configure HTTPS using Let's Encrypt
 The objective of Certbot, Let's Encrypt, and the ACME (Automated
 Certificate Management Environment) protocol is to make it possible
 to set up an HTTPS server and have it automatically obtain a
 browser-trusted certificate, without any human intervention. This is
 accomplished by running a certificate management agent on the web
 server.
 .
 This agent is used to:
 .
   - Automatically prove to the Let's Encrypt CA that you control the website
   - Obtain a browser-trusted certificate and set it up on your web server
   - Keep track of when your certificate is going to expire, and renew it
   - Help you revoke the certificate if that ever becomes necessary.
 .
 This package contains the main application, including the standalone
 and the manual authenticators.
Description-md5: deb7e404ce1b150b59379c3f9a73ac1a
Homepage: https://certbot.eff.org/
Section: web
Priority: optional
Filename: pool/main/p/python-certbot/certbot_0.31.0-1_all.deb
Size: 38512
MD5sum: eb2ebc4772d883a4e4da556a6298a8e0
SHA256: acebfb2d4b0ae3d6fde64a70de4da08f8d6f9266abaca9cfaa95731f7264baf5
```

**Comment by osirisinferi** [comment]
You can find the contact information for the Debian certbot package [here](https://packages.debian.org/buster/certbot).

Personally, I think it's sensible to use a random delay a little bit longer than 1 hour. Timezones are separated almost always by one hour, so you'd *say* 1 hour is a nice value. However, the human population (and thus Let's Encrypt users) aren't uniformly divided among all the time zones. So even with a 1 hour random delay, you'd still be "clustering" all the renewals.
However, I agree 12 hours seems a little bit too long. It also might mean certbot runs at a time of high loads, which one would like to prevent probably. What maximum delay *is* a proper one? I don't really know. I'd say about 4 to 6 hours.

**Comment by alexzorin** [comment]
Have a look at [this commit](https://salsa.debian.org/letsencrypt-team/certbot/certbot/commit/e6f673cdbd95c8ec5f13608c312187eca54f8d9d) from @hlieberman, the Debian maintainer:

>**Switch to spreading renewal over 12 hours**
>
>In talking to the Let's Encrypt team, they're seeing quite intense
spikes at the midnight and noon hours.  To help them reduce the load
and spread it out more evenly, we'll spread the load out over the
entire window.

FWIW, the EPEL package does the same thing.

**Comment by hlieberman** [comment]
The reason it's set to 12 hours (the same as the run interval) is to spread the execution time over the entire period.  If the renewals were all set to delay up to an hour, for example, then the Let's Encrypt servers would get hit harder depending on what timezones people were commonly using for their servers (especially UTC).  By setting the interval and delay to the same amount, though, it means timezones won't cause spiking -- because no matter the timezone you're in, you have an equal chance to wait.

There is a very small chance that you could get a race between two instances of certbot -- if one RandomizedDelaySec picked 12 hours and the next one picked a few seconds, but this is relatively unlikely to occur.  Even in that unlikely case, certbot's internal locking will just cause the conflicting run to be skipped.  (This isn't a huge deal, as renewals happen days in advance.  The 2-per-day interval is to allow Let's Encrypt to push out emergency updates and has never been used.)
