### ISSUE TITLE
Apache plugin should work with restrictive umask

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7741]
This problem was initially described at https://github.com/certbot/certbot/issues/1761#issuecomment-581678866.

##  I ran this command and it produced this output:
```
# umask 0077
# certbot -d example.org --apache
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator apache, Installer apache
Registering without email!
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for example.org
Enabled Apache rewrite module
Waiting for verification...
Challenge failed for domain example.org
http-01 challenge for example.org
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: example.org
   Type:   unauthorized
   Detail: Invalid response from
   http://example.org/.well-known/acme-challenge/dYsk27k0uIUgA1QOewleMrShVzv_BLZx7nP5H5eDfww
   [2604:a880:2:d0::578:6001]: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD
   HTML 2.0//EN\">\n<html><head>\n<title>403
   Forbidden</title>\n</head><body>\n<h1>Forbidden</h1>\n<p"

   To fix these errors, please make sure that your domain name was 
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
```

## Certbot's behavior differed from what I expected because:

The challenge failed.

## Discussion

The problem is we're not accounting for the possibility of a restrictive umask in the Apache plugin when setting up the challenge. We should fix this like we do in the webroot plugin.

~~I also think we should check if we have the same problem in the nginx plugin.~~

**Comment by osirisinferi** [comment]
nginx doesn't seem to make directories for the challenge, it modifies the nginx server block and adds a `include /etc/letsencrypt/le_http_01_cert_challenge.conf;` to the top.

I'm not sure if a restrictive umask would lead to problems in the case of nginx?

**Comment by bmw** [comment]
> nginx doesn't seem to make directories for the challenge, it modifies the nginx server block and adds a `include /etc/letsencrypt/le_http_01_cert_challenge.conf;` to the top. That conf doesn't actually use a webroot, but handles the challenge in the conf itself with a `return` directive.

Ah you're right! I forgot about that. Thanks for looking into it.

This should just be a problem in our Apache plugin then.

**Comment by alexzorin** [comment]
I'm confirming this as a current bug, opened #9423 to track it.
