### ISSUE TITLE
Deprecate certbot-auto on Gentoo, macOS, and FreeBSD

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7747]
For the sake of killing certbot-auto and doing it gradually, I would like to start deprecating the script on more systems. For systems where snaps are supported, my current inclination is to wait until we think our snaps are production ready and then direct them to use the snaps.

For systems where snaps cannot be used and we have other installation instructions available, I think it may be worth deprecating the script on these systems now. This would currently be Gentoo, macOS, and FreeBSD systems. Our current instructions at https://certbot.eff.org tell people on these systems to use their OS package manager and all of their Certbot packages are up-to-date. (Some haven't packaged our 1.2 release from yesterday yet but they all have Certbot 1.1+.)

I have two small hesitations with this. The first is that I'm not aware of a technical reason that snaps do not work on Gentoo, it's just that there is no snap package available or any other [instructions on how to install it](https://snapcraft.io/docs/installing-snapd). We could maybe wait and try to nudge Gentoo to package `snapd`, but as of 3 months ago, [we have less than 5000 Gentoo users](https://gist.github.com/bmw/4559c2cd50aa2c1fda5ca996a434ea2c#file-out-L25) so I'm unfortunately not sure it's the best use of our time.

My second hesitation is in the long run, to fully resolve ourselves from distro politics, I'm tempted to provide general instructions for smaller systems like this and describe how to install OS dependencies, create a virtual environment, and use `pip` to install Certbot, but realistically I think the current OS packages will work better for these users.

Despite those two concerns, I personally still think we should do this but I'm curious to hear what other people think.

**Comment by osirisinferi** [comment]
> I'm tempted to provide general instructions for smaller systems like this and describe how to install OS dependencies, create a virtual environment, and use pip to install Certbot

I'm pretty sure this won't fly well with Gentoo users. Using pip next to "emerge", Gentoo's package manager is [recommended against](https://wiki.gentoo.org/wiki/Pip). A venv might provide some protection, but I think a non-pip-solution for Gentoo users is preferable.

There already exists a (probably functioning) snapd overlay](https://github.com/zigford/snapd). However, it seems snapd is systemd only? As Gentoo uses [OpenRC as their default init](https://wiki.gentoo.org/wiki/Comparison_of_init_systems), this might be a rather big problem to support snapd officially.

Also, it's very much possible that if official support for system packages is removed, Gentoo users will be stubborn enough to keep using unofficial system packages, because Gentoo makes this soooo easy to do.

In any case, the `certbot-auto` script is superfluous on Gentoo IMHO.

**Comment by adferrand** [comment]
A note about emerge VS pip: this is true for any OS package manager (apt, yum...) vs pip. And virtual environments is the usual answer to this problem. Any decent certbot manual installation will require to create a virtual environment first.

**Comment by bmw** [comment]
Yeah. We also [do not recommend installing Certbot through pip](https://certbot.eff.org/docs/install.html#installing-from-source) and a virtual environment solves the problems here. (`--user` also works to a lesser extent, although this doesn't work well for Certbot which usually needs to run as root.)

> There already exists [a (probably functioning) snapd overlay](https://github.com/zigford/snapd). However, it seems snapd is systemd only? As Gentoo uses [OpenRC as their default init](https://wiki.gentoo.org/wiki/Comparison_of_init_systems), this might be a rather big problem to support snapd officially.

Ah you're probably right! That would make sense for why Gentoo doesn't officially support snapd.

> Also, it's very much possible that if official support for system packages is removed, Gentoo users will be stubborn enough to keep using unofficial system packages, because Gentoo makes this soooo easy to do.

I suspect many users on most distros won't follow our instructions and will just use their package manager. In most cases, that will work just fine, but they will probably get an older version of Certbot which opens them up to problems fixed in newer versions.

Because of that, we'd like to provide people with reliable instructions on how to get an up-to-date version of Certbot. In the past we've relied on distros packaging Certbot and keeping it updated, but this hasn't gone well. We haven't had many problems with this on Gentoo so maybe we could keep recommending the packages there in the long run. That makes Certbot significantly easier for them to install, but it's opening us and our users up to potential problems caused by package maintainers in the future which instructions on how to get Certbot directly from us wouldn't have. It also gives us less control over things like what versions of our dependencies are used. It's a tradeoff.

**Comment by osirisinferi** [comment]
> We haven't had many problems with this on Gentoo so maybe we could keep recommending the packages there in the long run.

Gentoo doesn't actually "package" anything because most packages are just "instructions" for Portage how to compile a package directly from the source (except some very large stuff like Libre Office or Chromium, such packages are available as binary builds). Therefore, any non-major version increment is mostly just copy/pasting an ebuild (the Portage file for the package) to a new ebuild with a different version in the filename. Sometimes dependencies change indeed, so of course a maintainer needs to keep an eye on that. Big changes might need more changes to the ebuild obviously, but in my opinion, Gentoo's packages are rather easy to maintain.

In any case, what option might be chosen, I'm pretty sure `certbot-auto` isn't one of them :wink:

**Comment by ohemorange** [comment]
> For systems where snaps cannot be used and we have other installation instructions available, I think it may be worth deprecating the script on these systems now.

The only hesitation I would have here is if it looks like snaps coming to these systems is imminent. Sounds like that's not the case for Gentoo; do we have a sense of if it is for the other two?

> I'm tempted to provide general instructions for smaller systems like this and describe how to install OS dependencies, create a virtual environment, and use pip to install Certbot, but realistically I think the current OS packages will work better for these users.

Agreed with everyone here about not recommending pip. In addition to the reasons stated, we regularly have weird things happen with pip installation that leads us to say not to use that installation method.

**Comment by bmw** [comment]
> The only hesitation I would have here is if it looks like snaps coming to these systems is imminent. Sounds like that's not the case for Gentoo; do we have a sense of if it is for the other two?

Yeah I think that's even less likely. Snaps rely on a lot of Linux features and I couldn't find any serious discussion of people trying to make it work on other OSes. Here's a couple threads if you're curious:

* https://forum.snapcraft.io/t/freebsd-port-snapd/8632
* https://forum.snapcraft.io/t/support-for-macos/1290

> Agreed with everyone here about not recommending pip. In addition to the reasons stated, we regularly have weird things happen with pip installation that leads us to say not to use that installation method.

At some point, I'd like to fully lay out what I had in mind here for what this documentation would look like, how it'd avoid most/all of the pitfalls brought up in this thread, and what kind of support we'd give these users, but I think we can talk about this another time and just point these users to the OS packages for now.
