### ISSUE TITLE
storage.py should be more paranoid

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#775]
`storage.py` often assumes that files exist in the right places (and that config files can be read and contain the required elements) because it creates and updates them correctly itself. But it's possible that a disk error could occur or that a user could tamper with the files after they've been created. In this case, storage.py should detect this and raise an appropriate exception, which other code that tries to work with lineages (like for renewal purposes) should be on the lookout for.

In theory we could check for file existence on _every_ access, to avoid race conditions (for example, if one of the elements of a lineage gets deleted after the object is instantiated and before that element is accessed!), but at a minimum we should use the sanity checks whenever first instantiating a `RenewableCert` from a renewal config file.

Edit: per #1214, another thing to check is that the `accounts` directory exists!

**Comment by N3X15** [comment]
Should probably also write to temporary files, and then move them into place when writing is complete.  Certbot appears to start writing my config files, and then something happens, causing certbot to exit prematurely and it blanks the .conf file.  Once I figure out what's going on, I'll make an issue.
