### ISSUE TITLE
ModuleNotFoundError: No module named 'certbot_apache.entrypoint'

### ISSUE THREAD

**Issue by 3n-k1** [certbot/certbot#7750]
Attempting to use certbot from the master branch of this repo produces the following error: `ModuleNotFoundError: No module named 'certbot_apache.entrypoint'`

How do I fix this?

**Comment by bmw** [comment]
There is no reference to the string `certbot_apache.entrypoint` in `master`. You probably have an old version of our Apache plugin installed on your system which did use this string and it's conflicting with the version of the plugin in `master` which does not contain it.

If you are a user, we don't support running directly from `master` and instead you should follow the instructions at https://certbot.eff.org/instructions. If you're trying to work on Certbot, you should follow the instructions at https://certbot.eff.org/docs/contributing.html#getting-started which describes how to set up a virtual environment to avoid these issues.
