### ISSUE TITLE
Convert Sphinx todos to comments or issues and disable the todo extension

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7752]
In Certbot's code there are a number of todos written in the Sphinx syntax described at https://www.sphinx-doc.org/en/master/usage/extensions/todo.html. In the config generated by default with `sphinx-quickstart`, these todos are shown in our documentation by default.

I think the intended audience for these todo comments is Certbot developers rather than Certbot users. Because of this, I don't think our Sphinx docstrings is the best place for these comments. I think we should move all existing todos into regular comments outside of the docstrings or make GitHub issues for each of them.

Once this has been done, I think we should disable the Sphinx todo extension both in all of our packages as well as in `tools/sphinx-quickstart.sh`.

**Comment by fish-dango** [comment]
First time contributor. I can take a try here!

**Comment by vernazxx** [comment]
Hello!
I made some changes to address this issue. Is it still useful to open a PR?

**Comment by bmw** [comment]
3 years later, I now think that what I did in https://github.com/certbot/certbot/pull/7753 is good enough so I'm going to close this issue.

@vernazxx, thanks so much for taking a look at this though. If you see any other issues that you'd be interested to work on, by all means add a comment to the issue and we can chat about it.
