### ISSUE TITLE
Error Running Script Using --deploy-hook

### ISSUE THREAD

**Issue by bettyvschmartz** [certbot/certbot#7769]
## My operating system is (include version):
CentOS Linux release 7.7.1908 (Core)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Using yum

---
There appears to be an issue running cerbot using the deploy-hook to run a bash script. 

I have tried running the script as:

`certbot --force-renewal --deploy-hook /path/to/myscript.sh`

Which fails immediately with:

> Unable to find deploy-hook command /path/to/myscript.sh in the PATH.
> (PATH is /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)

To fix this I tried:

`certbot --force-renewal --deploy-hook "/bin/sh /path/to/myscript.sh"`

Which fails during renewal attempt with:

> deploy-hook command "/bin/bash /path/to/myscript.sh" returned error code 127
> Error output from deploy-hook command bash:
> /bin/bash: /path/to/myscipt.sh: No such file or directory

Adding this script to _/etc/letsencrypt/renewal-hooks/deploy/_ similarly fails:

> Running deploy-hook command: /bin/sh /path/to/myscript.sh
> deploy-hook command "/bin/sh /path/to/myscript.sh" returned error code 127
> Error output from deploy-hook command sh:
> /bin/sh: /path/to/myscript.sh: No such file or directory

There doesn't seem to be a way to reference a shell script with the _deploy-hook_.

-- BVS

**Comment by schoen** [comment]
Hi @sapientsaxonsaboo ,

Are you sure that

* `/path/to/myscript.sh` is fully readable to the user you're running Certbot as?
* the script is marked executable in the filesystem?
* the script starts with a `#!` line that references a valid interpreter?
* you've correctly spelled the script path everywhere that you've referenced it?
* the script can run if you invoke it directly from the command line?
* you're not using a system security tool of some kind that limits the system calls that specific applications can make?

**Comment by sapientsaxonsaboo** [comment]
Hi @schoen,

Thanks for the reply. I forgot to mention a few further points of which you've raised. Let me give you some more context about what I am trying to achieve.

I create a renewal script which firstly checks for renewal using `certbot renew` then proceeds to convert the _fullchain.pem_ to a keystore file and import it into a JKS. The associated service that uses the JKS is then restarted. This script works, and in fact is currently running using a systemd service and timer. The problem with the script is that the cert conversion and service restart will happen every time, irrespective of renewal. Therefore, I would like to update the service to run `certbot renew --deploy-hook /path/to/myscipt.sh` and on renewal hand-off to my updated script (with renewal section removed).

> - /path/to/myscript.sh is fully readable to the user you're running Certbot as?
> - the script is marked executable in the filesystem?
> - the script starts with a #! line that references a valid interpreter?
> - you've correctly spelled the script path everywhere that you've referenced it?
> - the script can run if you invoke it directly from the command line?
> - you're not using a system security tool of some kind that limits the system calls that specific applications can make?

- Yes, fully readable by the user
- Yes, running as root with _r+x_ permissions
- Yes, starts with #!/bin/sh which on CentOS should symlink to bash I believe
- Yes, as far as I can see - plus when I add it directly to the _deploy_ directory it still doesn't work which doesn't rely on script name
- Yes, can call from the command line
- No security tools that would limit this I don't believe

As I say, the script works fine from the terminal and via a systemd service.

-- SSS

**Comment by schoen** [comment]
Which user are you running Certbot as? You're not running with a chroot or a container or something?

**Comment by matze18888** [comment]
same problem here, running in a docker container... Worked always perfectly, but now with a new image I always get the error 127...

**Comment by matze18888** [comment]
nevermind, it was formated in crlf instead of lf...

**Comment by Dikakus** [comment]
Same issue with a systemd script.

**Comment by gertcuykens** [comment]
same issues using podman 

```
alias certbot='docker run --rm --name certbot \
    -v "/etc/letsencrypt:/etc/letsencrypt" \
    -v "/var/lib/letsencrypt:/var/lib/letsencrypt" \
    certbot/certbot'
```

```
Hook 'deploy-hook' reported error code 127
Hook 'deploy-hook' ran with error output:
 /bin/sh: /etc/letsencrypt/renewal-hooks/deploy/hook.sh: not found
```
