### ISSUE TITLE
Is there an apt package of NS1.com plugin for Ubuntu?

### ISSUE THREAD

**Issue by loganmarchione** [certbot/certbot#7770]
Is there a way to install the [NS1.com plugin](https://certbot-dns-nsone.readthedocs.io/en/latest/) on Ubuntu via an apt repo? I see in #6770 that the PPA is out of date, so I'm assuming this is affected by that issue...

I've been using [pip](https://pypi.org/project/certbot-dns-nsone/) to install in plugin, which is already not advised. That works for the initial install, but:

- I can't run `certbot` as my user, because it requires root
- When I try to run `sudo certbot`, it then can't find the executable, because it was installed under my username instead of root
- Now I'm having to run `sudo /home/myusername/.local/bin/certbot`, which is not ideal

If there was an apt package for NS1 (like the other DNS plugins), that would be much easier.
```
$ sudo apt-cache search certbot-dns
python-certbot-dns-cloudflare-doc - Documentation for the Cloudflare DNS plugin for Certbot
python-certbot-dns-digitalocean-doc - Documentation for the DigitalOcean DNS plugin for Certbot
python-certbot-dns-dnsimple-doc - Documentation for the DNSimple DNS plugin for Certbot
python-certbot-dns-google-doc - Documentation for the Google DNS plugin for Certbot
python-certbot-dns-rfc2136-doc - Documentation for the RFC 2136 DNS plugin for Certbot
python-certbot-dns-route53-doc - Documentation for the Route53 DNS plugin for Certbot
python3-certbot-dns-cloudflare - Cloudflare DNS plugin for Certbot
python3-certbot-dns-digitalocean - DigitalOcean DNS plugin for Certbot
python3-certbot-dns-dnsimple - DNSimple DNS plugin for Certbot
python3-certbot-dns-google - Google DNS plugin for Certbot
python3-certbot-dns-rfc2136 - RFC 2136 DNS plugin for Certbot
python3-certbot-dns-route53 - Route53 DNS plugin for Certbot
```

Am I missing something, or is pip the only way to install this plugin right now?

**Comment by bmw** [comment]
Yeah this plugin is missing from the PPA right now and adding it as well as the other missing DNS plugins is tracked by https://github.com/certbot/certbot/issues/6053.

If you want to use the plugin in the meantime, we'd recommend [using Docker](https://certbot.eff.org/docs/install.html#running-with-docker) which would avoid the problems of using `pip`.
