### ISSUE TITLE
Stop configuring self signed certs in the nginx plugin

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7791]
In [_make_server_ssl](https://github.com/certbot/certbot/blob/fc7e5e8e6060d9e0df2e704a20103d5c0f456925/certbot-nginx/certbot_nginx/_internal/configurator.py#L642), we call `_get_snakeoil_paths` which generates a 1024 bit RSA key and a self signed certificate. We then configure nginx to use that cert and key.

This seems unnecessary to me. `_make_server_ssl` is only called from `choose_vhosts` which itself is only called from functions deploying a certificate or enabling a security enhancement. In the first case, we know the certificate to use and in the second case, something has gone horribly wrong and we would be leaving nginx configured with this self signed certificate.

In addition to being overly complex and potentially causing TLS errors, I think if we ever tried to write the user's nginx config with these changes, I think we have the potential for problems with file system permissions or [mandatory access control](https://github.com/certbot/certbot/issues/4716). To avoid all this, I think the code should be refactored to provide the cert to use if we're expecting to potentially have to enable TLS or error out if we're expecting the vhost to already support TLS.

@ohemorange, you know this code better than me, so if you're interested and aware of any good reason to keep things as is, please enlighten me!

**Comment by ohemorange** [comment]
Yes, this is just a historical artifact basically. `choose_vhost` was used in `tls_sni_01`, when it might have made more sense to structure it this way to share code between `tls_sni_01` and `deploy_cert`.

**Comment by bmw** [comment]
Thanks for the sanity check!
