### ISSUE TITLE
Stop moving configuration files around every month.

### ISSUE THREAD

**Issue by gnat** [certbot/certbot#7802]
Choose a spot and leave them. Particularly options-ssl-nginx.conf and ssl-dhparams.pem. You're breaking plenty of pipelines when you do this.

**Comment by adferrand** [comment]
Hello @gnat. We are sorry if changing these files broke your CI pipelines, but pieces of software are usually composed of moving parts that are regularly updated to improve the overall quality and increase the number functionalities.

However it is good for the community that some of these parts remain stable. That is why we defined the public API of Certbot with version 1.0. This API is considered stable, and is documented here: https://certbot.eff.org/docs/api.html

Code of the Nginx plugin, and its assets, are not part of it however. If we try to change things without purpose here, you cannot rely on the precise shape of these objects as we consider them as private.
