### ISSUE TITLE
Azure Pipelines is removing vs2015-win2012r2 on March 23rd

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7814]
See https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent.

Unfortunately, I think this means we cannot easily test on this version of Windows Server. We can easily delete these tests, but I think we may also want to update our code/docs to say that we only officially support Windows Server 2016+. If there's a significant demand for Windows Server 2012 support in the future, we could adding it again but I'd rather keep things simple for ourselves until a demand arises.

What do you think @adferrand?

**Comment by adferrand** [comment]
This is unfortunate. But I do not see any other solution on CI side. For instance Github actions runs only Windows Server 2019.

So without a proper build, yes we cannot officially support Windows 2012 R2. 

The only other solution would be to have a private agent, as Azure Pipeline supports it, running on Windows 2012 on a VM we control.

**Comment by bmw** [comment]
> The only other solution would be to have a private agent, as Azure Pipeline supports it, running on Windows 2012 on a VM we control.

Yeah my feeling is setting that up isn't worth it right now unless we see a significant demand for it. I think we should just drop the tests and update https://community.letsencrypt.org/t/beta-phase-of-certbot-for-windows/105822 (which for now is our main Windows docs) to say we require Windows Server 2016+.
