### ISSUE TITLE
Error on sudo certbot renew –dry-run

### ISSUE THREAD

**Issue by NTMS2017** [certbot/certbot#7827]
I got mail today that my LetsEncrypt SSL will expire in 19 days.

When I install LetsEncrypt using https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx 1 I run the “sudo certbot renew --dry-run” and it was okay. After today mail I rerun again and I get an error.

I checked the all port and find out that my firewall already allow both inbound and outbound for port; 80, 443 and 53.

Any idea why I am getting this error?

When I file issue here https://community.letsencrypt.org/t/error-on-sudo-certbot-renew-dry-run/114793/2 only response I get to find the blocking part so my certificate can renew using dry run command. 

Can anyone tell me where is the problem?

**Comment by m0namon** [comment]
It seems like you had your issue answered in the Community Forums, so I'm closing this issue. Feel free to ping me or re-open an issue if that's incorrect.
