### ISSUE TITLE
certbot-auto crashes when virtualenv is installed for Python3

### ISSUE THREAD

**Issue by kyegupov** [certbot/certbot#7828]
## My operating system is (include version):

Debian 9

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

cerbot-auto

## I ran this command and it produced this output:

```
$ virtualenv --version
virtualenv 20.0.7 from REDACTED/.local/lib/python3.8/site-packages/virtualenv/__init__.py

$ ./certbot-auto certonly --webroot --agree-tos --email REDACTED -w REDACTED -d REDACTED --no-bootstrap
Creating virtual environment...
usage: virtualenv [--version] [--with-traceback] [-v | -q] [--app-data APP_DATA] [--clear-app-data] [--discovery {builtin}] [-p py] [--creator {builtin,cpython2-posix}] [--seeder {app-data,pip}] [--no-seed] [--activators comma_sep_list]
                  [--clear] [--system-site-packages] [--symlinks | --copies] [--download | --no-download] [--extra-search-dir d [d ...]] [--pip version] [--setuptools version] [--wheel version] [--no-pip] [--no-setuptools] [--no-wheel]
                  [--symlink-app-data] [--prompt prompt] [-h]
                  dest
virtualenv: error: unrecognized arguments: --no-site-packages
Traceback (most recent call last):
  File "<stdin>", line 27, in <module>
  File "<stdin>", line 19, in create_venv
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['virtualenv', '--no-site-packages', '--python', '/usr/bin/python2.7', '/opt/
```

## Certbot's behavior differed from what I expected because:
certbot-auto does not work

no-site-packages flag has been deprecated in virtualenv

See also https://github.com/espressif/esp-idf/issues/4744

**Comment by m0namon** [comment]
Thank you for the report! It looks like there's a relevant PR open at #7832 to stop using the `--no-site-packages` flag.

@bmw, what do you think about also removing `--no-site-packages` from `certbot-auto`? I don't think it should cause any issues since it's been the default behavior for `virtualenv` for a while.

**Comment by bmw** [comment]
Thanks for taking the time to file an issue @kyegupov, but I'm going to close this as wontfix.

certbot-auto is not the recommended way to install Certbot on Debian 9 and we are planning to deprecate the script soon. Instead, you should follow our installation instructions at https://certbot.eff.org/lets-encrypt/debianstretch-other and use the packages provided by Debian.

Alternatively, if you use the virtualenv package provided by Debian, certbot-auto will still work on the platform.
