### ISSUE TITLE
Certbot fails when it can't update packages that don't need updating

### ISSUE THREAD

**Issue by silverbacknet** [certbot/certbot#7834]
## I installed Certbot with: certbot-auto and some custom scripts

> # certbot/certbot-auto --debug certonly --webroot -w [...] --expand --agree-tos -q --verbose
> yum is /usr/bin/yum
> yum is hashed (/usr/bin/yum)
> Package gcc-4.8.5-1.22.amzn1.noarch already installed and latest version
> Package augeas-libs-1.0.0-5.7.amzn1.x86_64 already installed and latest version
> Package 1:openssl-devel-1.0.2k-16.151.amzn1.x86_64 already installed and latest version
> Package libffi-devel-3.0.13-16.5.amzn1.x86_64 already installed and latest version
> Package system-rpm-config-9.0.3-42.28.amzn1.noarch already installed and latest version
> Package ca-certificates-2018.2.22-65.1.21.amzn1.noarch already installed and latest version
> Package python27-virtualenv-15.1.0-1.14.amzn1.noarch already installed and latest version
> Package python27-pip-9.0.3-1.27.amzn1.noarch already installed and latest version
> 
> 
> Transaction check error:
>   package python27-devel-2.7.16-1.131.amzn1.x86_64 is already installed
>   package openssl-1:1.0.2k-16.151.amzn1.x86_64 is already installed
>   package python27-tools-2.7.16-1.131.amzn1.x86_64 is already installed
> 
> Error Summary
> -------------
> 
> Could not install OS dependencies. Aborting bootstrap!

Amazon released a Python 2.7 update a couple weeks ago to address a security issue. Still not clear what if anything that has to do with this error.

I did my best to get this working on a pure 3.6 workflow, but it was just a complete waste of time.

**Comment by ohemorange** [comment]
Hey @silverbacknet, I'd recommend taking this question to the community forums at https://community.letsencrypt.org/, where there's a large group of nice people who regularly run Certbot on a variety of platforms that might be able to help you get this working. Python 2.7 is deprecated, and Certbot doesn't officially support Amazon AMI.
