### ISSUE TITLE
RFE: certbot certificates ought to show the serial numbers of the certificates

### ISSUE THREAD

**Issue by mgedmin** [certbot/certbot#7835]
For situations like https://letsencrypt.org/caaproblem/ it would be great to have a way of seeing the serial numbers of all the current certificates.  `certbot certificates` can show me the filenames, but then I have to study the openssl(1) manual to figure out how to craft the `openssl x509 -text -noout </path/to/fullchain.pem | grep -A1 Serial` command to see the serial number of each.

**Comment by ohemorange** [comment]
Sounds like a reasonable addition.
