### ISSUE TITLE
Problem with distributing DNS plugins

### ISSUE THREAD

**Issue by runfalk** [certbot/certbot#7836]
I've made two DNS challenge plugins for certbot for two different Swedish hosting providers:

* https://github.com/runfalk/certbot-glesys
* https://github.com/runfalk/certbot-loopia

They have worked for many years with almost no issues. The issue I have is that users are having trouble with how to properly install the plugins. Many users install certbot through their package manager and then my plugin using pip. This causes issues where certbot does not find the plugin (https://github.com/runfalk/certbot-loopia/issues/5).

Is there a way for plugins like mine to play nicely with the system package manager except packaging it for every distribution?

Since I assume it is not desirable to upstream all available certbot DNS plugins to this repositiory: Would it be possible to create a *certbot-dns-contrib* repository that package maintainers could use to create packages from? Maybe it would even be possible to create packages for the major distributions from there?

**Comment by ohemorange** [comment]
Hey @runfalk, we're currently in the process of updating how we distribute Certbot. More information on our plugin approach can be found [here](https://github.com/certbot/certbot/issues/7672) and [here](https://github.com/basak/certbot-snap-build/tree/snap-plugins/doc). Our larger discussion on supporting third-party plugins can be found [here](https://github.com/certbot/certbot/issues/6504); closing this in favor of that issue, but I encourage you to read up and join in over there if you're excited about helping out with our DNS plugin support project.
