### ISSUE TITLE
OSError: Unable to save to file!

### ISSUE THREAD

**Issue by PeterDraex** [certbot/certbot#7839]
## My operating system is (include version):
I'm running an Apache container in Docker, specifically `php:7.4-apache`, which is based on `debian:buster-slim`.

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
In my Dockerfile I install certbot like this:
```
RUN apt-get install -y certbot python-certbot-apache
```

To customize Apache Configuration, I create a symbolic link from the default config to my config file:
```
RUN ln --symbolic --force /srv/app/.docker/vhost.conf /etc/apache2/sites-available/000-default.conf
```

## I ran this command and it produced this output:

I run Certbot during container start:
```
certbot --apache -n --agree-tos --no-eff-email --redirect --hsts --email example@example.com -d example.com
```

Output:
```
web_1  | Running Certbot.
web_1  | Saving debug log to /var/log/letsencrypt/letsencrypt.log
web_1  | Plugins selected: Authenticator apache, Installer apache
web_1  | Cert not yet due for renewal
web_1  | Keeping the existing certificate
web_1  | Created an SSL vhost at /srv/app/.docker/vhost-le-ssl.conf
web_1  | An unexpected error occurred:
web_1  | OSError: Unable to save to file!
web_1  | Please see the logfiles in /var/log/letsencrypt for more details.
```

## Here is a Certbot log showing the issue (if available):
```
2020-03-07 11:29:52,716:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 75, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 139, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 2281, in perform
    http_response = http_doer.perform()
  File "/usr/lib/python3/dist-packages/certbot_apache/http_01.py", line 74, in perform
    self.configurator.save("HTTP Challenge", True)
  File "/usr/lib/python3/dist-packages/certbot_apache/augeas_configurator.py", line 150, in save
    self.aug.save()
  File "/usr/lib/python3/dist-packages/augeas.py", line 488, in save
    raise IOError("Unable to save to file!")
OSError: Unable to save to file!
```

## Certbot's behavior differed from what I expected because:
It produces an error.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
```
<VirtualHost *:80>
	ServerName {{{DOMAIN_NAME}}}
    DocumentRoot /srv/app

    <Directory "/srv/app">
        AllowOverride all
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    SSLProtocol ALL -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
</VirtualHost>
```

## Workaround

The problem seems to get fixed when I replace the symbolic link from 000-default.conf to my config:
```
ln --symbolic --force /srv/app/.docker/vhost.conf /etc/apache2/sites-available/000-default.conf
```

with a hard link:
```
ln --force /srv/app/.docker/vhost.conf /etc/apache2/sites-available/000-default.conf
```

However, I still think this is a bug and worth fixing.

**Comment by schoen** [comment]
Hi @PeterDraex,

Does your symbolic link point outside of the Docker container at the time that Certbot is running? I believe Docker's container model will uniformly stop symlinks from working across container filesystem boundaries. If that turns out to be the issue here, there's no way that Certbot could override this because it would be enforced by Docker as a security policy.

**Comment by PeterDraex** [comment]
Thank you for your answer.

The symbolic link points to a file in Docker volume. Apache is working just
fine with it, so I don’t think Docker’s security policies would be the
issue here.
