### ISSUE TITLE
Lightweight Installer for full integration

### ISSUE THREAD

**Issue by jdkasten** [certbot/certbot#784]
The SimpleFS PR, got me thinking... that we really need a lightweight Installer.  The main functionality of the Installer would be to restart a running webserver.

Use Case
Assuming, user's webserver isn't fully supported.
User wants to automate everything and is willing to help out the plugin.

Work Flow.
User uses the functionality of SimpleFS #757 to automatically get certificate. (Specifies the webroot)
User registers a restart command with the client, to autodeploy new certificates

Now renewal happens seamlessly.  (The plugin can remember the webroot of the server)  This updates the symlinks within storage.py (RenewableCert) and then the client just has to restart the webserver in order to deploy the new certificate.

The other calls would simply prompt instructions.
`Your certificate is located here.... install this symlink on the target server.  Press enter to continue`

**Comment by bmw** [comment]
I think this a really good idea and would be easy to implement building on top of #757. We may want to flag this for issue for launch.

One small issue I see is it is assuming the client will never have to complete a DVSNI challenge for renewal. This is probably a pretty good assumption right now, but there is nothing in the ACME spec preventing this from occurring. If the client did have to complete a DVSNI challenge, it would be unable to do so as the web server will be bound to port 443.

To get around this, we could have the user also register a command to stop their web server. To complete a DVSNI challenge, the client would stop the web server, perform the DVSNI challenge, and then restart the web server (possibly using a third registered command?). This is much less elegant and may not be necessary, but this approach is relying on always being able to use SimpleHTTP challenge to satisfy DV.

**Comment by coloradomountain** [comment]
I haven't looked into the code yet, but what does the verification do exactly?

Could you run a small static server alongside the main web server to allow access to the verification file with no down time?

**Comment by bmw** [comment]
Take a look at our [plugin documentation](https://letsencrypt.readthedocs.org/en/latest/using.html#plugins) for the different ways the  client handles domain validation.

**Comment by bmw** [comment]
We're planning to do more work on this front in #2782, however, this feature as described in this issue is already covered by the renewal hooks.
