### ISSUE TITLE
My options-ssl-nginx.conf installed by Certbot is not the same as the one you will find on Master branch?

### ISSUE THREAD

**Issue by Muddz** [certbot/certbot#7844]
I noticed that this [options-ssl-nginx.conf ](https://github.com/certbot/certbot/blob/master/certbot-nginx/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf) on the master branch is not the same one installed on my Ubuntu server _(etc/letsencrypt/options-ssl-nginx.conf)_ which has these options:

```
ssl_session_cache shared:le_nginx_SSL:1m;
ssl_session_timeout 1440m;

ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_prefer_server_ciphers on;

ssl_ciphers "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS";
```

Shouldn't these versions of _options-ssl-nginx.conf_ be the same? I installed Certbot today

My Setup:

Ubuntu 18.04 LTS (AWS LigtSails)
Nginx Webserver
Installed with command: certbot --nginx

**Comment by alexzorin** [comment]
The Certbot package available in Ubuntu 18.04 is 0.31.0, so you probably have this file: https://github.com/certbot/certbot/blob/v0.31.0/certbot-nginx/certbot_nginx/options-ssl-nginx.conf

You can track the progress of getting newer packages for Ubuntu here: https://github.com/certbot/certbot/issues/6770

You can also use [certbot-auto](https://certbot.eff.org/lets-encrypt/pip-other), which is always up to date.

**Comment by Muddz** [comment]
@alexzorin According to comments in the thread of #6770 a newer version is long due. Should we just manually copy/paste the newest [options-ssl-nginx.conf](https://github.com/certbot/certbot/blob/master/certbot-nginx/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf)?

**Comment by alexzorin** [comment]
You can absolutely make your own changes to `/etc/letsencrypt/options-ssl-nginx.conf` if you feel they are necessary.

The only caveat is that Certbot will avoid overwriting it in future, if it detects that you have modified it. So in effect, you take over responsibility for it.

**Comment by Muddz** [comment]
@alexzorin So the only think that will happend is that Certbot will not overwrite `/etc/letsencrypt/options-ssl-nginx.conf` and not anything else?

**Comment by webmaniak** [comment]
I found this topic when looking for the exact same issue, which is to increase the security of my Web server using nginx and certbot. Since editing the `/etc/letsencrypt/options-ssl-nginx.conf` file is not recommended (not updated afterwards), I followed some advices found in [this askubuntu community thread](https://askubuntu.com/questions/1267190/certbot-package-switching-from-old-package-to-snap-on-20-04) to upgrade my certbot configuration.

If it can help others, I executed the following commands to update my Ubuntu 16.04 server (a reboot is required after installing snap) and make sure I used snap instead of apt to take care of future updates without breaking my existing installation:

```shell
# Install fuse and snapd if you don't have them on your system already
sudo apt install fuse snapd

# Install certbot using snap (which currently is the recommended way of installing certbot)
snap install core; snap refresh core
apt remove certbot
snap install --classic certbot

# Add certbot to your path if it isn't possible to execute it
ln -s /snap/bin/certbot /usr/bin/certbot

# Test certbot
certbot renew --dry-run
```

Hope it can help ;)
