### ISSUE TITLE
Apache parser can crash with empty VirtualHost

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#7845]
As described at

https://community.letsencrypt.org/t/massive-error-log-valueerror-unable-to-insert-label-an-unexpected-error-occurred/115917/

if there is an Apache config file with

```
<VirtualHost example.com:80>
</VirtualHost>
```

the Apache parser can crash with `Unable to insert label!` (which makes some intuitive sense to me; I feel there's no straightforward way to modify this VirtualHost to make it capable of passing challenges!).

I'm not sure how valid this configuration is from Apache's perspective, but it would be better not to crash in this case.

**Comment by srguglielmo** [comment]
Hello!

> I'm not sure how valid this configuration is from Apache's perspective

It's valid and passes a `configtest` as of Apache/2.4.41 on Ubuntu 20.04 LTS. I ran into this same issue. I was _not_ using Webmin, unlike the community post you linked to. Here's an example that throws the certbot error:

```# Global directives apply to all vhosts.
ServerName example.org
ServerAdmin me@example.org
DocumentRoot /var/www/html
ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log common

Listen 80
<VirtualHost *:80>
	# All config is inherited from the "main" server configuration; nothing to override here.
</VirtualHost>

Listen 443
<VirtualHost *:443>
	SSLEngine on
	SSLCertificateFile /etc/ssl/certs/ssl-cert-snakeoil.pem
	SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key
</VirtualHost>
```

When I commented the empty `<VirtualHost>` block, `certbot certonly --apache` gave me another error:

> Unable to find a virtual host listening on port 80 which is currently needed for Certbot to prove to the CA that you control your domain. Please add a virtual host for port 80.

The final solution was to _uncomment_ it and move the `ServerName` into _both_ vhosts. Of course, once I got the https certificate, I added a permanent redirect from http -> https in the vhost block.
