### ISSUE TITLE
Add Ubuntu 20.04 to our test farm tests

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7853]
In the past we've talked about trying to keep the list of systems we test on relatively current I still think there's some value in that.

If the tests don't immediately work, especially due to failures in certbot-auto, I think it probably makes sense to close/kick this issue until we've done some combination of deprecate certbot-auto and rewrite the test farm tests.

**Comment by oracle3987** [comment]
Help to work 2gthr not against me

**Comment by oracle3987** [comment]
> In the past we've talked about trying to keep the list of systems we test on relatively current I still think there's some value in that.
> 
> If the tests don't immediately work, especially due to failures in certbot-auto, I think it probably makes sense to close/kick this issue until we've done some combination of deprecate certbot-auto and rewrite the test farm tests.

Help fix

**Comment by bmw** [comment]
Closing in favor of https://github.com/certbot/certbot/issues/7915.
