### ISSUE TITLE
Update Certbot snap to be based on Ubuntu 20.04

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7854]
[Here](https://github.com/certbot/certbot/blob/5536c912238d96b15295a1b6938472fd24cf40ce/snap/snapcraft.yaml#L18) we define the [base image](https://snapcraft.io/docs/base-snaps) of the Certbot snap to be `core18` which is based on Ubuntu 18.04.

Probably the single most problematic part of packaging Certbot as a snap is going to be when we have to change the base snap in the future which may require all externally packaged plugins to have to upgrade in order to continue to work. More details about this can be found at https://docs.google.com/document/d/1OB5WCDz2mBMgRvtnvo4FSjWHPBDlt1NpccJ5sNrhWIw/edit?usp=sharing.

To delay these problems for as long as possible, I think we should be using the `core20` image based on Ubuntu 20.04 before we publish a stable Certbot snap. I think we may want to consider doing this before adding support for external plugins (see https://github.com/certbot/certbot/issues/7667), but I think that'll depend on the state of the `core20` snap and Ubuntu 20.04. Apparently, it already exists, but I'm not sure how stable it is yet. See
```
$ snap info core20
name:      core20
summary:   Runtime environment based on Ubuntu 20.04
publisher: Canonical✓
license:   unset
description: |
  The base snap based on the Ubuntu 20.04 release.
type:    base
snap-id: DLqre5XGLbDqg9jPtiAhRRjDuPVa5X1q
channels:
  stable:    20 2020-02-10 (347) 62MB -
  candidate: 20 2020-02-10 (347) 62MB -
  beta:      20 2020-03-16 (486) 62MB -
  edge:      20 2020-03-17 (496) 62MB -
```
We should probably look into the state of things with `core20` more when we go to work on this issue.

**Comment by bmw** [comment]
When we do this, we probably will need to update the Python version in `snapcraft.yml` as flagged by Adrien at https://github.com/certbot/certbot/pull/7932#discussion_r414082537.

**Comment by enoch85** [comment]
Quick question, if installing the snap package on Ubuntu 20.04, will it stop working after you pushed the new snap core?

**Comment by bmw** [comment]
As far as I know it shouldn't. It should seamlessly upgrade to the new snap using the new base.

**Comment by bmw** [comment]
I started this in the [core20 branch](https://github.com/certbot/certbot/tree/core20), but it failed because [it seems you need snapcraft >= 4.0](https://github.com/snapcore/snapcraft/releases/tag/4.0) which isn't in the stable channel yet. You can see the failure that occurs when trying to use an older version of snapcraft at https://travis-ci.com/github/certbot/certbot/builds/166993202.

We could update to the candidate channel and remember to downgrade later, but it seems easiest to me to just wait a bit if we can.

Also, when resolving this issue, we should remember to update the [snap-plugin branch](https://github.com/certbot/certbot/tree/snap-plugin) with the same changes.

**Comment by ohemorange** [comment]
When 4.0 is stable, it will probably appear here: https://snapcraft.io/docs/snapcraft-release-notes

**Comment by enoch85** [comment]
Just an FYI, we use the current certbot snap in Ubuntu 20.04 without any issues so far.

https://github.com/nextcloud/vm/blob/master/lib.sh#L463-L467

**Comment by bmw** [comment]
snapcraft 4.0 was pushed to the stable channel this morning!
