### ISSUE TITLE
DNS validation via Lexicon doesn't iterate all domain_name_guesses before raising error

### ISSUE THREAD

**Issue by miff2000** [certbot/certbot#7856]
I'm trying to use Certbot to create a TXT record for DNS-01 auth using the Lexicon provider. What I've noticed is that In the code [here](https://github.com/miff2000/certbot/blob/fc7e5e8e6060d9e0df2e704a20103d5c0f456925/certbot/certbot/plugins/dns_common_lexicon.py#L80) it generates a list of zones which might exist in the account. For a request for the hostname `test.example.com` the list looks like this:

```python
['test.example.com', 'example.com', 'com']
```

The code then iterates through this list to see which domain exists in the account. If the provider returns a 404 (Not Found) however for the list entry, an error is immediately raised. No further iterations of that list occur. This means that, unless you're requesting a certificate for the apex record, it will always fail.

I was planning to put in a PR to ensure it only fails after the list has been fully iterated, but I first want to check that I'm not misunderstanding the behaviour, or that this is by design. If it is a bug, let me know and I'll get a PR put in 😊

I've seen issue <https://github.com/certbot/certbot/issues/6869> by the way too. The resolution to me doesn't make sense though, as the `_handle_http_error()` method has no way of knowing whether the whole list has been iterated or not, to know when to fail. In my mind the logic for eventually failing on the last entry needs to be implemented in `dns_common_lexicon.py`, as that _could_ know whether the whole list has been tried or not. No?

## My operating system is (include version):
Ubuntu 18.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
pip using Python 3.8.1

## I ran this command and it produced this output:
```bash
certbot certonly \
        -d test.example.com\
        --authenticator certbot-dns-safedns:dns_safedns \
        --certbot-dns-safedns:dns_safedns-credentials ~/.config/letsencrypt/dns_safedns.ini \
        --agree-tos \
        --email admin@example.com \
        --server https://acme-staging-v02.api.letsencrypt.org/directory
```

The output is this:
```none
Saving debug log to /home/user/projects/certbot-safedns-test/logs/letsencrypt.log
Plugins selected: Authenticator certbot-dns-safedns:dns_safedns, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for test.gimmeya.ml
Cleaning up challenges
Error determining zone identifier for test.example.com: 404 Client Error: Not Found for url: https://api.ukfast.io/safedns/v1/zones/test.example.com.
```

## Certbot's behavior differed from what I expected because:
It should have looked up `example.com` as a domain, but it failed before it got there.

**Comment by miff2000** [comment]
I notice that in <https://github.com/vshosting/certbot-dns-clouddns> they are pretty much overriding all of the existing methods. Should I be going down that route, overriding the `_find_domain_id` method?

**Comment by alexzorin** [comment]
Don't take this as an authoritative answer, but looking at the official Lexicon-based plugins, they seem to be overriding `_handle_general_error` to prevent "domain not found" conditions from prematurely causing the `_find_domain_id` loop to abort.

https://github.com/certbot/certbot/blob/3bfaf41d3df0417a2d58d088af1a893d320aeb55/certbot-dns-linode/certbot_dns_linode/_internal/dns_linode.py#L104-L108

https://github.com/certbot/certbot/blob/3bfaf41d3df0417a2d58d088af1a893d320aeb55/certbot-dns-ovh/certbot_dns_ovh/_internal/dns_ovh.py#L101-L103

**Comment by alexzorin** [comment]
>The resolution to me doesn't make sense though, as the _handle_http_error() method has no way of knowing whether the whole list has been iterated or not, to know when to

`_handle_http_error` and `_handle_general_error` don't need to know about the iteration, because `_find_domain_id` will throw an error once all the possibilities are exhausted and nothing is found:

https://github.com/certbot/certbot/blob/fc7e5e8e6060d9e0df2e704a20103d5c0f456925/certbot/certbot/plugins/dns_common_lexicon.py#L105-L106

**Comment by miff2000** [comment]
Okay, so in my plugin I'll just capture 404 errors, log a fail using logger, then return False so it doesn't raise an error. I'm happy enough with that. I guess that approach allow for more control my implementers on how errors should be handled.

Thanks @alexzorin 😊
