### ISSUE TITLE
Upgrade the test farm tests to use Python 3

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7857]
Our [test farm test script](https://github.com/certbot/certbot/blob/3bfaf41d3df0417a2d58d088af1a893d320aeb55/tests/letstest/multitester.py) only supports Python 2 which reached its end-of-life and going to become harder and harder to install. It has been removed from Homebrew and is planned to be removed from Ubuntu 20.04 LTS. So we can continue to trigger tests locally which is necessary to do Certbot releases, we should make the script work with Python 3. I do not think we should keep Python 2 compatibility when doing this.

To do this, we at least need to:

- [x] Stop using `urllib2` and instead use [urllib](https://docs.python.org/3/library/urllib.html).
- [x] Upgrade from Fabric 1 to Fabric 2: https://www.fabfile.org/upgrading.html
- [x] Update [requirements.txt](https://github.com/certbot/certbot/blob/3bfaf41d3df0417a2d58d088af1a893d320aeb55/tests/letstest/requirements.txt) with a stable set of dependencies that work on Python 3.
- [x] Update [README](https://github.com/certbot/certbot/blob/3bfaf41d3df0417a2d58d088af1a893d320aeb55/tests/letstest/README.md) to mention new dependencies (Python 3, Fabric 2.0, etc.) and instructions so Python 3 is used.
- [x] Update the [Python version used to run these tests in Travis](https://github.com/certbot/certbot/blob/3bfaf41d3df0417a2d58d088af1a893d320aeb55/.travis.yml#L93-L114)
- [x] Make sure Travis tests pass with these changes

There may be other issues I'm not aware of but that should be most of the work with the most significant work being upgrading Fabric which revamped its API.

**Comment by maximillianh** [comment]
@ohemorange is investigating.

**Comment by ohemorange** [comment]
Just going to start some relevant reminders for myself

- [ ] test with boulder not found
- [ ] test with local repo and with branch not specified
