### ISSUE TITLE
Propose system or user installation on Windows

### ISSUE THREAD

**Issue by adferrand** [certbot/certbot#7883]
NSIS installers, the technology used to build the Windows installer for Certbot, as everything needed to propose user to install Certbot for one user or for all users (system installation). The latter requires administrative privileges.

Installation path is adapted depending on the situation: `APPDATA` for a user install, `PROGRAMFILES` for a system install.

Currently we disabled the user install option because Certbot requires administrative privileges, as explained in #7880 and #7881. Once these issues are closed, we can activate the user install option again.

A specific effort must be put in the Certbot configuration folder setup. For now, it is always `C:\Certbot`.

At the minimum we should adapt this path depending on the installation type. It could be in `PROGRAMDATA` for system install, and `APPDATA` for user install. To do so, on top of modifying the NSIS script accordingly, we need to find a way to instruct Certbot to use this specific folder by default for the current installation, when the configuration flag `--config-path` is not set on Certbot CLI. This could be a part of a global solution for all platforms as described in #7882.

Alternatively we could just put `--config-path` explicitly in the scheduled tasks for certificate renewal, while I am less in favor with this option, since it freezes the configuration that can not be modified easily without a reinstallation of Certbot.

**Comment by justinpawela** [comment]
The [documentation][1] (under _Windows installation procedure_, _1. Important notes_) still points to this open issue. It looks like these changes are still a work-in-progress.

[1]: <https://certbot.eff.org/instructions?ws=other&os=windows&tab=standard>

**Comment by fardarter** [comment]
> The [documentation](https://certbot.eff.org/instructions?ws=other&os=windows&tab=standard) (under _Windows installation procedure_, _1. Important notes_) still points to this open issue. It looks like these changes are still a work-in-progress.

Reiterating this

**Comment by rf532** [comment]
I am working on Node JS server and I want to get a free SSL certificate

**Comment by DIEGOGARCIA601050** [comment]
I want a certificate too.
I am working on nginx server
