### ISSUE TITLE
Do not require mock in Python 3

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7886]
As discussed at https://bugzilla.redhat.com/show_bug.cgi?id=1795666 and https://github.com/certbot/website/pull/557#issuecomment-610182044, our unconditional dependency on the 3rd party `mock` library is causing some problems for EPEL 8 packaging.

To fix this, I think we should make our `mock` dependency conditional on using Python 2 in all of our packages. When doing this, a little care needs to be taken to ensure that:

1. Our wheels will be built properly regardless of the Python version used (see https://github.com/certbot/certbot/issues/3455).
2. The way the dependency is specified creates wheels that works with the version of `pip`, `setuptools`, etc. pinned in `certbot-auto` and the sdist works with `setuptools==1.0` which is used by some distro packaging.

For both of these, I think we can probably reuse an approach similar to the one [here](https://github.com/certbot/certbot/blob/e9895d2ec69395cfcf1cfff35e7668b57e1da00f/certbot/setup.py#L59-L74).

In our testing code, I think we should then write code like:
```
try:
    import mock
except ImportError
    from unittest import mock
```
The reason for continuing to prefer the 3rd party mock library can be seen at https://github.com/certbot/certbot/pull/7755. It appears that mixing the 3rd party and built in `unittest.mock` does not go well and since we have a [test API](https://certbot.eff.org/docs/api/certbot.tests.html), I think it's worth taking a little care to not suddenly break these tests for people if we can.

After these changes are made and we've dropped Python 2 support, I think we should:

1. Remove the `mock` requirement from all of our packages.
2. Print a deprecation warning when using the 3rd party `mock` library.
3. When we release a new major version of Certbot, unconditionally use `unittest.mock`.

These last 3 steps are future work and a new issue should probably be created to track it specifically if the other changes described here are made, but I wanted to lay out the full plan for what I was thinking of for a transition to `unittest.mock`.

**Comment by ohemorange** [comment]
> The reason for continuing to prefer the 3rd party mock library can be seen at #7755. It appears that mixing the 3rd party and built in unittest.mock does not go well and since we have a test API, I think it's worth taking a little care to not suddenly break these tests for people if we can.

My understanding of that PR is that the problem is caused by having a mix between packages. The fix to this seems to be to upgrade all of the packages that use `mock` simultaneously, and update their dependencies. All certbot packages should be using a single version of python, so there won't be any mixing once the PRs are in. Did you mean that we should do it this way just to make writing the code easier, so we can do it module by module?

**Comment by ohemorange** [comment]
I've now done this for some representative modules. Approach should be roughly the same for others; depends/doesn't depend on files changes in `certbot/`.

**Comment by ohemorange** [comment]
> Our wheels will be built properly regardless of the Python version used (see #3455).

#3455 shouldn't be a problem here, since our target audience here is packagers, the relevant version is in fact the version on the machine that the wheel is being built and tested on. Additionally, if someone has written a third-party module, and is relying on a wheel created by someone without mock, but does want to use mock, their code should still work against that wheel given how we've written things, and they'll probably be building their own wheels, where their own local system will be the relevant one.

**Comment by bmw** [comment]
> Approach should be roughly the same for others; depends/doesn't depend on files changes in certbot/. Would love a review before doing the rest, so I don't have to go back and change them all.

Good idea. I reviewed the current PRs and had a nitpick and a question, but they otherwise LGTM!

**Comment by bmw** [comment]
Oh! One thing I do think we should do in one of these PRs though is add a changelog entry stating this change.

**Comment by ohemorange** [comment]
> Oh! One thing I do think we should do in one of these PRs though is add a changelog entry stating this change.

I figured I'd add this to the last one, which should be the dns one, based on this grep:
```
$ git grep "'mock'" 
acme/setup.py:    'mock',
certbot-apache/setup.py:    'mock',
certbot-compatibility-test/setup.py:    'mock',
certbot-dns-cloudflare/setup.py:    'mock',
certbot-dns-cloudxns/setup.py:    'mock',
certbot-dns-digitalocean/setup.py:    'mock',
certbot-dns-dnsimple/setup.py:    'mock',
certbot-dns-dnsmadeeasy/setup.py:    'mock',
certbot-dns-gehirn/setup.py:    'mock',
certbot-dns-google/setup.py:    'mock',
certbot-dns-linode/setup.py:    'mock',
certbot-dns-luadns/setup.py:    'mock',
certbot-dns-nsone/setup.py:    'mock',
certbot-dns-ovh/setup.py:    'mock',
certbot-dns-rfc2136/setup.py:    'mock',
certbot-dns-route53/setup.py:    'mock',
certbot-dns-sakuracloud/setup.py:    'mock',
certbot-nginx/setup.py:    'mock',
certbot/setup.py:    'mock',
certbot/tests/display/ops_test.py:            unicode_error = UnicodeEncodeError('mock', u'', 0, 1, 'mock')
letsencrypt-auto-source/rebuild_dependencies.py:    'mock': '1.3.0',
letsencrypt-auto-source/rebuild_dependencies.py:    #   'mock': [('2.4.0', 'centos:7')]
```

**Comment by bmw** [comment]
The initial work here is done and we no longer require `mock` in Python 3.

The work of removing this dependency entirely is tracked in https://github.com/certbot/certbot/issues/7913.
