### ISSUE TITLE
Drop requests[security] dependency in Python 3

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7901]
Similar to https://github.com/certbot/certbot/issues/7886, it seems we can simplify packaging in Fedora/EPEL by dropping our `requests[security]` dependency in Python 3. See https://bugzilla.redhat.com/show_bug.cgi?id=1813673 which tracks packaging `python-ndg_httpsclient` which otherwise would not be required.

We specify this dependency in `acme` for the code [here](https://github.com/certbot/certbot/blob/8e4dc0a48c6108311cf68ca1c683d29b15d49c97/acme/acme/client.py#L36-L41). This works around problems with the TLS implementation in old versions of the Python 2 standard library and does not effect Python 3.

If we do this, we should be careful that the changes in `setup.py` avoid the issues discussed at https://github.com/certbot/certbot/issues/7886.

Another potential problem I'm not immediately sure how to deal with is we unconditionally depend on `requests` but would conditionally depend on `requests[security]`. If both of these strings are in `install_requires`, does `pip`/`setuptools` do the right thing or are there issues? Is there a better way to conditionally specify these extras? Do you know anything about this off the top of your head @erikrose?

Finally, if this change is made, we should probably open an issue to track completely removing the dependency on `requests[security]` as well as the code in `acme.client` I linked above once we drop Python 2 support.

cc @FelixSchwarz

**Comment by FelixSchwarz** [comment]
Thank you for the heads-up (feel free to cc me for relevant issues in the future). For Fedora/EPEL `python-ndg_httpsclient` is easy to package and does not cause any headache though I appreciate fewer dependencies.

**Comment by hroncok** [comment]
> If both of these strings are install_requires, does pip/setuptools do the right thing...

IIRC it does.

**Comment by bmw** [comment]
> Thank you for the heads-up (feel free to cc me for relevant issues in the future). For Fedora/EPEL python-ndg_httpsclient is easy to package and does not cause any headache though I appreciate fewer dependencies.

In that case, I think we may hold off on this issue until we drop Python 2 support where can simply unconditionally depend on `requests`, but I'll leave this open in case anyone wants to work on it or there are any unexpected hurdles to packaging `python3-ndg_httpsclient` in EPEL 7.

**Comment by FelixSchwarz** [comment]
> until we drop Python 2 support

Btw: Do you have rough timeline in mind for this to happen?

**Comment by bmw** [comment]
I'd guess 4-6 months from now.

**Comment by erikrose** [comment]
> If both of these strings are in install_requires, does pip/setuptools do the right thing

Off the top of my head I don't know; one would have to run an experiment, and it may even be different depending on pip versions. (Though certbot-auto makes that variable go away to a large extent.)

I, too, would wait until we can drop Python 2 support and then excise the `requests[security]` dep from acme.
