### ISSUE TITLE
Investigating CentOS 7 Apache problems

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#7904]
We've been seeing several situations on the forum where people running Apache on CentOS 7 say they're seeing a self-signed certificate returned by Apache for their sites (from the CentOS default VirtualHost in `ssl.conf`), instead of the Let's Encrypt certificate, even after Certbot reports success in obtaining and installing the new certificate.

It's not totally clear whether this is a Certbot bug, but it seems moderately likely to be one; it's also not clear whether it could be related to our old issue #6606. The symptoms that users experience are pretty similar, but @bmw has an explanation of why that issue (which applied to CentOS 6) would be unlikely to have persisted in the same form. The explanation of the problem and solution for the old issue is contained in @joohoi's PR #6784.

I'm creating this issue to track this, and I'm planning to spin up a CentOS 7 VM and see if I can reproduce anything.

Two of the forum posts that inspired this concern are

https://community.letsencrypt.org/t/new-certificate-installed-getting-fails-in-the-browser/118257

https://community.letsencrypt.org/t/how-do-i-replace-information-in-a-certificate/118547

I think there may be other relevant posts too.

**Comment by FelixSchwarz** [comment]
If this happens when using the rpms from Fedora EPEL please feel free to cc me in these cases.

**Comment by bmw** [comment]
Assuming the explanation of this problem is https://community.letsencrypt.org/t/epidemic-of-centos-default-virtualhost-problems/147861/4, what if we checked for the case of a HTTPS vhost without a server name and did...something? That something could be a warning, asking the user which vhost to modify, etc.
