### ISSUE TITLE
Run lint on our tests again

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7908]
When we moved our tests out of our packages, we accidentally stopped running `pylint` on them. Unfortunately, this isn't an entirely trivial fix. `pylint` does not support running tests on all files in a directory that's not part of a package. See https://github.com/PyCQA/pylint/issues/352.

At least a few ways to fix this are:

1. Give `pylint` the path to each individual file in `tests` directories. This is tricky because `tests` may contain arbitrary subdirectories.
2. Make our `tests` directories modules by adding `__init__.py`. My understanding is this is not normally done and I am not sure if there are any downsides to do this.
3. Switch to `flake8` which happily will run tests on all files in subdirectories.

I'm personally most excited by the last option although it is almost certainly the most work.

**Comment by Pierre-Sassoulas** [comment]
pylint and flake8 are not equivalent. You can set up flake8 with zero work `pip3 install flake8`, `flake8 .` that's it. pylint detects other problems (generally more). You could use both :)

**Comment by Pierre-Sassoulas** [comment]
There is a '--recursive=y' option in pylint now.

**Comment by bmw** [comment]
Nice. Thanks for the info.

While I think it'd be nice in theory for us to do this, I don't see it being prioritized anytime soon so I'm going to close this, at least for now.
