### ISSUE TITLE
Remove conditional mock dependency

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7913]
This issue is tracking the follow up work from https://github.com/certbot/certbot/issues/7886.

In particular, once we've dropped Python 2 support, I think we should:

1. Remove the `mock` requirement from all of our packages.
2. Print a deprecation warning when using the 3rd party `mock` library.
3. When we release a new major version of Certbot, unconditionally use `unittest.mock`.

**Comment by ekohl** [comment]
> In particular, once we've dropped Python 2 support

https://github.com/certbot/certbot/issues/8389 tracks that.
