### ISSUE TITLE
Update snapcraft.cfg value by 6/17/2023

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7931]
Automated deployments to the snap store rely on credentials stored in a [secure file](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/secure-files?view=azure-devops) named `snapcraft.cfg` in Azure Pipelines. This file was created by running `snapcraft export-login --channels=beta,edge snapcraft.cfg`.

This credential has a maximum lifetime of 1 year and the current credential will expire on 2023-06-17. The value will need to be updated to use a new credential before then to prevent automated deploys from breaking.

**Comment by vooraviboon** [comment]
CONTRIBUTING.md

**Comment by bmw** [comment]
Rather than duplicating this info here and https://github.com/certbot/certbot/blob/c20d40ddbafb8db9e38cf5ec41b0ec187cc06686/.azure-pipelines/templates/stages/deploy-stage.yml#L12-L35, I propose we close this.

If we want more than the CI config comment, maybe we can put something on a shared calendar.
