### ISSUE TITLE
dns-google plugin fails to use instance authentication

### ISSUE THREAD

**Issue by mloughran** [certbot/certbot#7933]
On GCP, Compute Engine instances have access to a default service account (via a metadata service) which tools are expected to use to authenticate. The [certbot-dns-google documentation](https://certbot-dns-google.readthedocs.io/en/stable/) claims that this is supported:

> If you’re running on Google Compute Engine, you can assign the service account to the instance which is running certbot. A credentials file is not required in this case, as they are automatically obtained by certbot through the metadata service.

However, in my testing this is not the case. Looking through community discussions (see below), I am not alone, and the only offered solution I've see is to use the `--dns-google-credentials` flag. I get the following error on attempting to renew:

```
$ sudo certbot certonly --dns-google -m <snip> --agree-tos -n --dry-run -d '<snip>'
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-google, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for <snip>
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/dns/v1/rest
URL being requested: GET https://dns.googleapis.com/dns/v1/projects/<snip>/managedZones?dnsName=<snip>.&alt=json
Cleaning up challenges
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/dns/v1/rest
URL being requested: GET https://dns.googleapis.com/dns/v1/projects/<snip>/managedZones?dnsName=<snip>.&alt=json
Error finding zone. Skipping cleanup.
Encountered error finding managed zone: <HttpError 401 when requesting https://dns.googleapis.com/dns/v1/projects/<snip>/managedZones?dnsName=<snip>.&alt=json returned "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.">
```

It appears to fail on the call to mangedZones, which can be easily attempted using the `gcloud` tool (which uses the default service account):

```
gcloud dns managed-zones list
```

If I create a JSON key for the default Compute Engine service account (using the same service account to rule out IAM issues) and provide this via `--dns-google-credentials key.json`, everything works.

## Related community discussions

* https://community.letsencrypt.org/t/dns-google-dns-01-gce-authentication-problems/85929
* https://community.letsencrypt.org/t/how-to-use-dns-01-auth-on-gce-by-certbot-dns-google/85380/8
* https://github.com/certbot/certbot/issues/6877#issuecomment-478012652

I have not found any posts claiming to have got Compute Engine authentication working.

## My operating system is (include version):

Debian 10 Buster

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

apt-get (version: certbot 0.31.0).

I also tested using certbot 1.3.0 (installed via pip) with the same results.

**Comment by wsnel** [comment]
Confirming this narrative. In my setup, the certbot also seems to ignore my enhanced service account permissions. CertBot only seems to work when explicitly identifying the service account through the --dns-google-credentials flag.

**Comment by venim** [comment]
The certbot plugin is using an old version of the google-api-python-client module (1.5.5). The api client has been updated with a newer method of authentication (google-auth package) when building API services.

Fix is in https://github.com/certbot/certbot/pull/7959

**Comment by bmw** [comment]
Like venim said, the main problem here is `google-api-python-client` in Debian Buster and Ubuntu 18.04 is too old. Instance authentication works when using a newer version of this dependency.

To solve the problem, I proposed just tightening our version requirement at https://github.com/certbot/certbot/pull/7959#issuecomment-623716032.
