### ISSUE TITLE
pip3 virtualenv not supported? python3-virtualenv not being used? Requires python-virtualenv (python 2)

### ISSUE THREAD

**Issue by jfoliveira** [certbot/certbot#7934]
Can't run `certbot-auto` in a system with `virtualenv 20.0.18` installed through pip3 and with both `python` and `python3` installed.

Not sure if it's a bug or if I'm doing something wrong. Please let me know if there is any workaround or best practice to be followed here that I might be missing.

## My operating system is (include version):
`Ubuntu 18.04.4 LTS` (running in a docker container)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
`certbot-auto` (from git source)

## I ran this command and it produced this output:
Just pulled the source and made `certbot-auto` executable, then:

1) **First attempt**
`/opt/certbot/certbot-auto --no-bootstrap`

Which outputs:
```node
Creating virtual environment...
usage: virtualenv [--version] ...
virtualenv: error: unrecognized arguments: --no-site-packages
Traceback (most recent call last):
  File "<stdin>", line 27, in <module>
  File "<stdin>", line 19, in create_venv
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: 
Command '['virtualenv', '--no-site-packages', '--python', '/usr/bin/python2.7', '/opt/eff.org/certbot/venv']' returned non-zero exit status 2
```

2) **Second attempt**
I thought I had some missing dependency so I ran again without the `--no-bootstrap` param:
`/opt/certbot/certbot-auto`

Output (tried to keep the most meaningful parts):
```node
Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)
...
python is already the newest version (2.7.15~rc1-1).
...
virtualenv is already the newest version (15.1.0+ds-1.1).
...
The following packages were automatically installed and are no longer required:
  python3-acme ... python3.6-venv
Use 'apt autoremove' to remove them.
The following NEW packages will be installed:
  python-virtualenv
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 46.8 kB of archives.
After this operation, 145 kB of additional disk space will be used.
Do you want to continue? [Y/n]
```
Choosing NO, python2 virtualenv is not installed and the operation is aborted.
Choosing yes, it installs python2 virtualenv and then raises the exception:
```node
virtualenv: error: unrecognized arguments: --no-site-packages
```

I noticed through `virtualenv --version` that I was still using python3 version. So I uninstalled related apt and pip3 packages:
```node
pip3 uninstall virtualenv
apt-get remove python3-virtualenv --purge
apt-get remove python-virtualenv --purge
apt-get autoclean
```

3) **Third attempt**
Now with a clean environment, tried again:
`/opt/certbot/certbot-auto`

Successful, but the output confuses me:
```node
Bootstrapping dependencies for Debian-based OSes...
...
python is already the newest version (2.7.15~rc1-1).
python-dev is already the newest version (2.7.15~rc1-1).
...
The following packages were automatically installed and are no longer required:
  python3-acme ... python3.6-venv
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  python3-virtualenv
The following NEW packages will be installed:
  python-virtualenv python3-virtualenv virtualenv
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 94.6 kB of archives.
After this operation, 316 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
```

So, now that I removed `python3-virtualenv` it will be installed again?
Also, `python3.6-venv` that is installed is suggested as no longer useful?

## Certbot's behavior differed from what I expected because:
I noticed the pull request for Python3 supported merged the other day: https://github.com/certbot/certbot/pull/7918

I guess the questions are:
`virtualenv 20.0.18` installed through pip3 is not supported?
Is this by design?
Should I always install `python3-virtualenv` and `python-virtualenv` and not `pip3 install virtualenv` to ensure my system is compatible with `certbot-auto`?

**Comment by bmw** [comment]
The way certbot-auto works makes many assumptions about the system it is run on. In particular, it assumes you will be using the dependencies provided by your OS rather than a mix from various sources. You're welcome to try and make things work with whatever dependencies through `--no-bootstrap`, but we're not able to provide full support for it. For better or worse, I don't think we'll ever change this as things can get complicated quickly if we try to support arbitrary combinations of packages.

> Should I always install python3-virtualenv and python-virtualenv and not pip3 install virtualenv to ensure my system is compatible with certbot-auto?

Yes. The `python-virtualenv` package in Ubuntu 18.04 depends (through a recommended dependency on `virtualenv`) on `python3-virtualenv`. While I would recommend never installing `pip` packages globally on your system as it interacts poorly with the packages from your OS package manager, the problem here wasn't that `virtualenv` was using Python 3, it's that the latest versions of `virtualenv` changed things in a backwards incompatible way that certbot-auto doesn't expect on Ubuntu 18.04.

So while we won't be changing our behavior here, I hope this helps and answers your questions.

**Comment by jfoliveira** [comment]
Hi Brad (@bmw) it definitely helped me and I agree this approach makes sense from the package maintenance standpoint. 
Thank you for the detailed answer!
