### ISSUE TITLE
Fix python-augeas in the Certbot snap

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7943]
As you can see [here](https://github.com/certbot/certbot/blob/cd993cdfb1d847f1170a388ce1c7f74cfb98a17e/snap/snapcraft.yaml#L46), we currently use a fork of python-augeas that Robie created. I think we should avoid using a fork of our dependency if at all possible and we certainly shouldn't expect Robie to maintain it for us.

I looked into using either old versions of `python-augeas` which use `ctypes` to load the Augeas shared object as well as new versions which use `cffi`. In both cases I found that the function `ctypes.util.find_library` is used which hard codes calling `/sbin/ldconfig -p` as a first step of finding the shared library. See https://github.com/python/cpython/blob/v3.8.5/Lib/ctypes/util.py#L276. This executable is on the host system and I don't see a good way for us to control its output from inside the snap. As a result, if Augeas is installed on the host and we remove Robie's patch, we'll try to use it first which I think we should avoid for consistency and reliability. The snap team is looking into fixing this in upstream Python and then backporting it to the Python Ubuntu packages, but this hasn't happened yet so I'm looking into other options. See https://forum.snapcraft.io/t/issue-when-snap-uses-pythons-ctype-util-find-library/9690.

Unless we can resolve https://github.com/hercules-team/python-augeas/issues/32 in a way that also fixes things here, I'm not seeing a good way for us to fix this right now without maintaining patches on our dependencies somewhere...

**Comment by noxidsoft** [comment]
Getting this on Ubuntu 18.04
```
$ sudo certbot --apache -d wwwtest.domain.example
Saving debug log to /var/log/letsencrypt/letsencrypt.log
The apache plugin is not working; there may be problems with your existing configuration.
The error was: NoInstallationError('Problem in Augeas installation',)
$
```

**Comment by bmw** [comment]
I think you're having a different issue. There are no known problems with the way Augeas is used in the Certbot snap right now from a user perspective. My issue here is just tracking changing things so it's a little easier for us to maintain internally. If you are having issues, please open a new issue and fill out the issue template.
