### ISSUE TITLE
Update PPA for Ubuntu 20.04

### ISSUE THREAD

**Issue by thisgeektweets** [certbot/certbot#7950]
Currently the certbot/certbot PPA is missing a release for Ubuntu 20.04 and the version in the archive is somewhat outdated (0.40.0). Would it be possible to have the PPA updated to work on 20.04?

## My operating system is (include version):
Ubuntu Server 20.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Installed with apt from the Ubuntu archive, but the version is outdated. Attempted to add the [PPA](https://launchpad.net/~certbot/+archive/ubuntu/certbot), however there isn't a target for 20.04 as yet.

## I ran this command and it produced this output:
$  add-apt-repository ppa:certbot/certbot
E: The repository 'http://ppa.launchpad.net/certbot/certbot/ubuntu focal Release' does not have a Release file.

## Certbot's behavior differed from what I expected because:
I couldn't install Certbot on this Ubuntu release

**Comment by enoch85** [comment]
Quick fix: `apt install certbot`.

At least that gives you 0.40.1

**Comment by thisgeektweets** [comment]
@enoch85 I did this as a workaround for now which got me running with the `--certsonly` flag! Looks like the ppa wasn't updated for 19.10 either, though. Would be great to have this fixed so I can get the nginx plugins, etc back!

**Comment by enoch85** [comment]
I edited my answer above. :point_up:

**Comment by bmw** [comment]
If you installed Certbot through apt, you can also install the nginx plugin by running `apt install python3-certbot-nginx`.

If you installed Certbot through snap, it has the nginx plugin built in.

**Comment by enoch85** [comment]
@bmw Thanks!

Got this though: 
`root@nextcloud2tb:~# certbot `
`-bash: /usr/bin/certbot: No such file or directory`

**Comment by reedy** [comment]
> @bmw Thanks!
> 
> Got this though after installing the snap:
> `root@nextcloud2tb:~# certbot `
> `-bash: /usr/bin/certbot: No such file or directory`

It's probably somewhere that isn't (currently) in $PATH

**Comment by enoch85** [comment]
@reedy Got it, I needed to type:

```
/snap/bin/certbot --version
certbot 1.3.0
```

**Comment by reedy** [comment]
My reply disappeared...

For future reference `hash -r` should work the same as logging out and in again

**Comment by thisgeektweets** [comment]
For now, the snap package will work for me. I'll keep an eye on this issue to see when the PPA gets updated and revert :)

**Comment by enoch85** [comment]
Just for reference: https://github.com/nextcloud/vm/blob/master/lib.sh#L434-L448

**Comment by Pequito** [comment]
Honest I do not think this is the right way to go if we have the plugin already ready for Ubuntu 20.04 aka python3-certbot-nginx and even one for apache.

Should be focused on the AttributeError: module 'acme.challenges' has no attribute 'TLSSNI01' that happens when we do have the correct plugin installed with Ubuntu 20.04.

**Comment by tekkitan** [comment]
> Quick fix: `apt install certbot`.
> 
> At least that gives you 0.40.0
> 
> Another option is: `snap install --beta certbot --classic`
> 
> Gives you 1.3.0

How is this a legit answer? "Just use this outdated version of the software or use another package manager"

How about just fix the PPA so it has the newest version?

**Comment by maximillianh** [comment]
A comment on this issue was deleted for violating EFF's Public Projects Code of Conduct, which is available here: https://www.eff.org/pages/eppcode

Please keep the conversation respectful and kind. If you have any questions you can reach out to codeofconduct@eff.org.

**Comment by tekkitan** [comment]
> A comment on this issue was deleted for violating EFF's Public Projects Code of Conduct, which is available here: https://www.eff.org/pages/eppcode
> 
> Please keep the conversation respectful and kind. If you have any questions you can reach out to [codeofconduct@eff.org](mailto:codeofconduct@eff.org).

OK so the official answer from Certbot is to keep using the outdated version. Perfect. Nice security guys!

**Comment by thisgeektweets** [comment]
@tekkitan issue is that the outdated version in the PPA wasn’t actually functional as shipped

**Comment by tekkitan** [comment]
> @tekkitan issue is that the outdated version in the PPA wasn’t actually functional as shipped

That isn't the only issue though. There are important security features only supported in the newer versions. Apparently they do not care about security or they would make sure that PPA was updated properly.

**Comment by thisgeektweets** [comment]
> > @tekkitan issue is that the outdated version in the PPA wasn’t actually functional as shipped
> 
> That isn't the only issue though. There are important security features only supported in the newer versions. Apparently they do not care about security or they would make sure that PPA was updated properly.

It looks to me like the official docs have removed reference to the PPA now (https://certbot.eff.org/lets-encrypt/ubuntufocal-apache.html) so that helps this pain a little. Not to mention that they now reference using universe which is mostly “at your own risk”. Whilst I agree that more attention should be paid to either not shipping a broken version, or getting the later versioned upstreamed in to Debian, the snap, or indeed installing via pip, are viable for now at least :)

**Comment by maximillianh** [comment]
We've deleted two more comments that violated our code of conduct and temporarily blocked the user. Thank you all for keeping this conversation respectful and courteous.

**Comment by enoch85** [comment]
Hey guys, no need to use the PPA now when the snap is in place. The snap works really well and will get you the latest version.

> https://github.com/nextcloud/vm/blob/master/lib.sh#L512-L515

```
    apt-get install snapd -y
    sudo snap install --beta certbot --classic
    # Update $PATH in current session (login and logout is required otherwise)
    hash -r
```

**Comment by thisgeektweets** [comment]
Going to close this off since it’s attracting some negative attention, as @enoch85 said, the snap is a functional workaround.

**Comment by tekkitan** [comment]
Workarounds instead of actually fixing stuff. You're still going to have people using apt to install it and until you care about security, certbot will not be recommended.

**Comment by thisgeektweets** [comment]
> Workarounds instead of actually fixing stuff. You're still going to have people using apt to install it and until you care about security, certbot will not be recommended.

I’m not actually a contributor and my own personal issue is resolved hence closing. The documentation has been updated as far as I can tell to get a working version installed for most users and the recommendations here to install via snap seem reasonable.

**Comment by tekkitan** [comment]
Reasonable for you, but leaving giant security flaws in systems across the globe. No one here cares about security apparently which is hilarious since this is a tool for generating SSL certificates.

**Comment by thisgeektweets** [comment]
You're welcome to raise a bug regarding getting the latest version into the Ubuntu archive, I'm sure. 

Until then, most reasonable sysadmins would do their due-diligance before blindly installing a package from universe or a PPA in my experience.

**Comment by tekkitan** [comment]
THEIR OWN DIRECTIONS SAY TO USE APT AND USE THE UNIVERSE REPO.

https://certbot.eff.org/lets-encrypt/ubuntufocal-other

If you expect everyone to know to do that, then you obviously know nothing about secure software either.

**Comment by enoch85** [comment]
@tekkitan 

> You're still going to have people using apt to install it and until you care about security, 

Well, if you care about security you should use the snap and get the latest version. Things evolve, so does certbot and the ways of installing it. I'd consider the PPA to be legacy.

If you installed certbot my guess is that you're somewhat interested in technology, and with that an interest to follow the development. This is the development: certbot now install as a snap.

**Comment by enoch85** [comment]
@tekkitan 

> You're still going to have people using apt to install it and until you care about security, 

Well, if you care about security you should use the snap and get the latest version. Things evolve, so does certbot and the ways of installing it. I'd consider the PPA to be legacy.

If you installed certbot my guess is that you're somewhat interested in technology, and with that an interest to follow the development. This is the development: certbot now install as a snap.

> Until then, most reasonable sysadmins would do their due-diligance before blindly installing a package from universe or a PPA in my experience.

100% agree! It's common sense regarding PPAs.

**Comment by Exoyds** [comment]
I'd like to add to this issue that the snap distribution currently does not support wildcard certs, and so is not the best workaround.

**Comment by alexzorin** [comment]
@Exoyds on that front, the only thing remaining is an announcement (https://github.com/certbot/website/pull/613). You can try issue wildcards using the available DNS plugin snaps right now.

**Comment by philippjorek** [comment]
Hey there,
i updatet ubuntu from 18 to 20 in februrary 2021, but the "PPA" problem is there still.
I testet snap, but it does not work, if i start updating ppa:certbot/certbot after that.

any ideas? i'm looging for some days for an idea, but nothing works. :-(

**Comment by bmatthewshea** [comment]
No snapd/snap needed now.
What I did following Ubuntu upgrade from 18 to 20:

Remove PPA in case it wasn't disabled:  
`sudo add-apt-repository --remove certbot/ppa`  

Also, you can delete any inactive sources (from upgrade) **for certbot** in `/etc/apt/sources.list.d/`. To determine if they are inactive, just look at files and see if they are commented out from upgrade. If so, clean them out. No point keeping.  

Remove old install that used certbot ppa:  
`sudo apt remove certbot`  

Run apt update to make sure no outside repo/ppa is loading (namely certbot):
`sudo apt update` -> Check list. It should be all Ubuntu sources immediately following upgrade. If you see certbot, the ppa is still installed/active. Go back a couple steps..^^^

Install certbot from Ubuntu Focal repo/ppa (along with any Python plugins you need):  
`sudo apt install certbot python3-certbot-(plugin_name)`  

Test:  
`sudo certbot --dry-run renew`

Works for me.

Tried without `--dry-run`. Also worked.

**Comment by dregad** [comment]
@bmatthewshea I did the same and can confirm it does work indeed, but be aware that on 20.04 Focal you will get certbot 0.40.0 and not the [latest release](https://github.com/certbot/certbot/releases) (1.16.0 as I write this). This may or may not be a problem for you. 

I remember facing issues with certbot on earlier Ubuntu LTS versions (e.g. bionic archives only offer 0.27.0) so I turned to the certbot PPA before it was decommissioned. 0.40.0 works fine for me, but YMMV...

**Comment by bmatthewshea** [comment]
@dregad
 Thanks for the info. Yes, I am running 0.40.0 with _standalone_ and _route53_ plugin. Those were the only two methods I was worried about and that were tested in last post above. I did face many problems with DNS validation in the past, though. I also used the Certbot PPA versions previously due to this problem (lack of DNS validation).
