### ISSUE TITLE
Unable to install on Ubuntu 19.10

### ISSUE THREAD

**Issue by kittenswolf** [certbot/certbot#7953]
## My operating system is (include version):
Ubuntu 19.10

## Command I ran
`sudo apt-get install certbot python-certbot-nginx`

## Output
```Reading package lists... Done
Building dependency tree
Reading state information... Done
Package certbot is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'certbot' has no installation candidate
E: Unable to locate package python-certbot-nginx
```

Yes, I ran `apt-get update` and `apt-get upgrade` before trying to install certbot.

**Comment by kittenswolf** [comment]
Fixed by running

```
apt install software-properties-common
apt-add-repository universe
```

**Comment by bmw** [comment]
Thanks @kittenswolf and sorry for the misinformation in https://github.com/certbot/certbot/issues/7947.

I'll update https://certbot.eff.org to include this step for systems that may not have the universe repository already enabled.

**Comment by kittenswolf** [comment]
All good, glad to have helped 😀
