### ISSUE TITLE
Digital Ocean dns-digitalocean-propagation-seconds always getting 10s

### ISSUE THREAD

**Issue by allanesquina** [certbot/certbot#7965]
Hi guys, I'm using `docker-letsencrypt` in my Digital Ocean droplet and I can't validate my DNS challenge. My `TTL` is set to `30s` which is the minimum value allowed. I figured out that the `default_propagation_seconds` is hard coded, is that true? I'm always getting `10s` of propagation time.  Is there any way to change that variable using ENV vars? Am I doing something wrong? Could you help me guys? 

The file is https://github.com/certbot/certbot/blob/master/certbot/certbot/plugins/dns_common.py#L33

```
def add_parser_arguments(cls, add, default_propagation_seconds=10):  # pylint: disable=arguments-differ
```

Thank you very much.

**Comment by osirisinferi** [comment]
10 seconds is just the default value. According to [the documentation](https://certbot-dns-digitalocean.readthedocs.io/en/stable/), you should be able to set another propagation time with `--dns-digitalocean-propagation-seconds`.

**Comment by allanesquina** [comment]
Hi @osirisinferi, yup but how can I change that using `docker-letsencrypt`? Can you help me?
Is this file that I need to change? Because it seems to be setting already. Is there any other file to change so that I can build my own image?

https://github.com/linuxserver/docker-letsencrypt/blob/master/root/etc/cont-init.d/50-config#L174

Thank you very much!

**Comment by allanesquina** [comment]
Hi, I was able to change the propagation seconds but then I figured out Godaddy changed my DNS servers from Digital Ocean to default instead. I have no idea why this happened since it was working just fine. It's working now. Thanks.
