### ISSUE TITLE
Support the DNS plugin for hetzner

### ISSUE THREAD

**Issue by kritzl** [certbot/certbot#7966]
I recently saw that hetzner (https://www.hetzner.com/) now has an API for DNS entries.
And someone has already written a plugin for it!
It would be great if this was officially supported:

https://github.com/ctrlaltcoop/certbot-dns-hetzner

**Comment by alexzorin** [comment]
From [the contributing docs](https://certbot.eff.org/docs/contributing.html#writing-your-own-plugin):

>The Certbot team is not currently accepting any new DNS plugins because we want to rethink our approach to the challenge and resolve some issues like #6464, #6503, and #6504 first.
>
>In the meantime, you’re welcome to release it as a third-party plugin. See certbot-dns-ispconfig for one example of that.

**Comment by bmw** [comment]
I'll leave this issue open to track us supporting this DNS provider's API in some way in the future.

**Comment by FelixSchwarz** [comment]
Just wanted to add that dns-lexicon also has a Hetzner plugin so a generic certbot plugin might be able to reuse that.

**Comment by robertoschwald** [comment]
There already exists an excellent certbot plugin for Hetzner-DNS: https://github.com/ctrlaltcoop/certbot-dns-hetzner

**Comment by MrSpoocy** [comment]
@bmw if you want, I can make a pull request from my repository. It uses dns-lexicon (https://github.com/MrSpoocy/certbot-dns-hetzner).
