### ISSUE TITLE
Allow setting DNS TTL  in DigitalOcean

### ISSUE THREAD

**Issue by vrga** [certbot/certbot#7969]
This is more of a conceptual bug, but here goes
Running certbot with --test-cert first, getting a test certificate issued, then trying the same command without --test-cert will fail, if ran again within the TTL time of the TXT record made in DO.

It seems that the default TTL of DNS records in DO is 1800, so you cannot reliably get a certificate in testing and then in non-testing within this timeframe.

I know that you can set the TTL on certs in datadog's api on creation time, so maybe using the value provided by "--dns-digitalocean-propagation-seconds" as the record TTL would be a good idea.

**Comment by allanesquina** [comment]
Hi, it may be solved by this PR:
https://github.com/certbot/certbot/pull/7725

I'm not sure if it can solve my problem:
https://github.com/certbot/certbot/issues/7965

Any idea? Thanks!

**Comment by vrga** [comment]
Yes, that PR would "solve" this for me. In my case, the solution was just to wait for 30 minutes, which was fine.
Your problem is slightly separate and would probably require you to modify/make a pr against the repo of the docker container as well.

**Comment by ohemorange** [comment]
Thanks for reporting, looks like that PR will solve this issue.

**Comment by FaustTobias** [comment]
Are there any news on this? This seems like a really simple change that will enhance this provider a lot.
