### ISSUE TITLE
Upgrade Zope dependencies in Certbot to work with setuptools>=46

### ISSUE THREAD

**Issue by adferrand** [certbot/certbot#7976]
In setuptools 46.0.0, a deprecated API have been removed: `setuptools.Feature`. This can break some installations, as explained in https://github.com/pypa/setuptools/issues/2017, and it precisely break ours during the compilation of the Certbot dockers, because the base docker contains now this latest version of setuptools.

It seems also from this same issue that `zope.interface<=5.0.0` is still using this deprecated API during its installation.

We should update our dependencies to zope in order to get rid elegantly of this error, and allow certbot installation in most recent versions of setuptools.

**Comment by bmw** [comment]
Fixed in #8012.
