### ISSUE TITLE
Write community forum post about disabled ACMEv1 validations

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7978]
I/we probably should have looked into this a long time ago, but I personally was under the impression our ACMEv2 migration had been fully accomplished last year prior to Let's Encrypt disabling ACMEv1 registrations.

[Let's Encrypt is planning on disabling ACMEv1 validations on July 2nd with brownouts starting on June 1st](https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430/9).

I pulled some stats today to see how many Certbot (or letsencrypt client) users were still using ACMEv1 to issue certificates. In the past 2 months, roughly 8% of Certbot installations (190k) issued certificates with ACMEv1.

Diving into who these users are, 90% of them are using a ~2+ year old version of Certbot that doesn't default to ACMEv2. Of these, there is a very long tail of different OS and version combinations, but with the exception of Debian 8 which is EOL'd next month, all significantly sized groups seem to be people using OS packages who aren't installing updates.

As for why 10% of our ACMEv1 users (or .8% of our total users or 18k people) whose version of Certbot does default to ACMEv2 continue to use ACMEv1, a few options are: 

1) They are requesting the ACMEv1 server through the --server flag on the command line or [global configuration file](https://certbot.eff.org/docs/using.html#configuration-file).
2) They explicitly requested ACMEv1 once and Certbot remembered their choice.
3) There maybe is/was a Certbot bug. I haven't tried to reproduce it, but I think @mnordhoff  may be on to something with people who have only used `certbot renew` on a lineage that was initially issued with a ~4 year old version of Certbot.

Only users in the first case will be affected by Let's Encrypt's changes in the next couple months because the other two issues only affect renewal.

Therefore, our instructions to keep Certbot working past LE's upcoming changes are:

1. Install Certbot 0.26.0+ which we have instructions for every major OS we support at https://certbot.eff.org.
2. Don't explicitly request `--server <ACMEv1 URL>` on the command line or a manually edited [global configuration file](https://certbot.eff.org/docs/using.html#configuration-file).

I suspect it to be extremely rare for users to unknowingly do the latter, so really all people should need to do is follow our installation instructions and things should keep working for now.

**Comment by mnordhoff** [comment]
Three recent threads where Ubuntu 16.04 was in use:

* https://community.letsencrypt.org/t/some-certificates-use-acme-v02-olds-use-acme-v01/117818
* https://community.letsencrypt.org/t/update-your-client-software-to-continue-using-lets-encrypt/119402
* https://community.letsencrypt.org/t/ubuntu-16-06-xenial-certbot-still-using-acmev1-last-package-version-is-certbot-version-0-31-0/121489

It got me wondering if users might have issued certificates using 0.4.1 (released around 2016-04 and originally packaged by Ubuntu) and then upgraded to something much newer.

(The third thread linked to a tutorial that [currently] says to use the PPA from the beginning, though.)

I just reproduced it on Ubuntu 16.04 using the staging and production environments, creating a certificate using 0.4.1 (I still have it installed, heh) and then renewing it with 1.4.0 (certbot-auto, installed to a different path).

```
mnordhoff@clover:~$ sudo -H /usr/bin/letsencrypt certonly --webroot -w /srv/www/certbot -d origin-mn0-f0.mattnordhoffdns.org

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/origin-
   mn0-f0.mattnordhoffdns.org-0001/fullchain.pem. Your cert will
   expire on 2020-08-04. To obtain a new version of the certificate in
   the future, simply run Let's Encrypt again.
 - If you like Let's Encrypt, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

mnordhoff@clover:~$ sudo -H certbot renew --cert-name origin-mn0-f0.mattnordhoffdns.org-0001 --force-renewal
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/origin-mn0-f0.mattnordhoffdns.org-0001.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Plugins selected: Authenticator webroot, Installer None
Renewing an existing certificate

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
new certificate deployed without reload, fullchain is
/etc/letsencrypt/live/origin-mn0-f0.mattnordhoffdns.org-0001/fullchain.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/origin-mn0-f0.mattnordhoffdns.org-0001/fullchain.pem (success)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
mnordhoff@clover:~$ sudo -H certbot renew --cert-name origin-mn0-f0.mattnordhoffdns.org-0001 --force-renewal
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/origin-mn0-f0.mattnordhoffdns.org-0001.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Plugins selected: Authenticator webroot, Installer None
Renewing an existing certificate

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
new certificate deployed without reload, fullchain is
/etc/letsencrypt/live/origin-mn0-f0.mattnordhoffdns.org-0001/fullchain.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/origin-mn0-f0.mattnordhoffdns.org-0001/fullchain.pem (success)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

`/etc/letsencrypt/renewal/origin-mn0-f0.mattnordhoffdns.org-0001.conf`:

* 0.4.1: https://mn0.us/9kRx/origin-mn0-f0.mattnordhoffdns.org-0001.conf_0.4.1
* 1.4.0: https://mn0.us/jenC/origin-mn0-f0.mattnordhoffdns.org-0001.conf_1.4.0

**Comment by bmw** [comment]
You probably shouldn't take the time to read this post, but for knowledge sharing/documentation purposes....

### Why does Certbot have the behavior in the previous post?

My expectation of what's going on is prior to Certbot 0.5.0 (really `letsencrypt` 0.5.0), Certbot saved every configuration value in the renewal config file under `/etc/letsencrypt/renewal`.

Starting with our 0.5.0 release, we added a whitelist causing Certbot to only save "relevant" values in the renewal configuration file. When Certbot writes those files, any options in the whitelist that were explicitly set by the user are saved. Similarly, when certbot renew is run, any values from the renewal configuration file on that whitelist are preserved.

This was the case until our 0.26.0 release where we made a couple of changes:

1. We changed the default server to LE's ACMEv2 endpoint.
2. We made Certbot always save the server value in the renewal configuration file.

This caused new certificate lineages created with Certbot 0.26.0+ to automatically use LE's ACMEv2 endpoint and to save that `server` value in the renewal configuration file.

It also caused every certificate lineage initially created with Certbot versions 0.5.0 to 0.25.1 which would have no `server` value in their renewal configuration file unless they explicitly requested one to automatically switch to ACMEv2. The absence of a `server` value meant the user relied on the default which had been changed to ACMEv2.

The problem here though is if you initially created your lineage with Certbot 0.4.2 or older and have since then only used `certbot renew` to maintain it, you do have an explicit server value for ACMEv1 which modern versions of Certbot treat as if you had explicitly requested that server to be used so it will continue to try to use that server.

This was a mistake on our end, but again, given how few people should be affected that we can help like I described in my initial post, I don't think we need to make any code changes here.

### What about the user in the community forum post who claims to have always used our PPA?

As far as I can tell, the first version in the Certbot PPA was Certbot 0.9.3 and was uploaded in September 2016. If the user in the community forum post had always used the PPA, my explanation of the bug here is incorrect/incomplete.

I do think they had initially used an older version of Certbot though. If I'm correct that 0.9.3 was the first version in the PPA, then date in the URL of the tutorial they used predates our PPA. I suspect they had initially used `letsencrypt-auto` or `letsencrypt 0.4.2` from Ubuntu and the tutorial was later updated to follow our instructions to use the PPA.

Another piece of data supporting this is https://certbot.eff.org wasn't even updated to advertise the PPA until March 2017. See https://github.com/certbot/website/commit/5e5e7e4afec1fd1c8460b7bd7e5b0b9bc57cd5ef.

**Comment by jsha** [comment]
Thanks for the repro, @mnordhoff. That's super helpful. If I'm interpreting right, it sounds like folks who have been using 0.4.1 will have an explicit server URL in their config, and so won't get the benefit of automatic upgrade to the acme-v02 URL. Is that right?

I like Brad's idea of creating good documentation / a guide. But also what about doing the automatic upgrade to acme-v02 even if acme-v01 is specified in the config? We know it won't work after a certain point. And even though we probably can't get the latest Certbot backported into old OS', there are two cases where this helps:

 - User on an old OS updates their OS, and gets an up-to-date Certbot but still has the explicit server URL breaking things.
 - User on an old OS manually installs the latest version of Certbot (e.g. from source, or via certbot-auto or pip).

**Comment by bmw** [comment]
> If I'm interpreting right, it sounds like folks who have been using 0.4.1 will have an explicit server URL in their config, and so won't get the benefit of automatic upgrade to the acme-v02 URL. Is that right?

Yep! To be slightly more precise, this affects certificate lineages where 0.4.2 or older was ever used to obtain a certificate and since then only the `renew` subcommand had been used to update it.

> And even though we probably can't get the latest Certbot backported into old OS', there are two cases where this helps:
>
> - User on an old OS updates their OS, and gets an up-to-date Certbot but still has the explicit server URL breaking things.
> - User on an old OS manually installs the latest version of Certbot (e.g. from source, or via certbot-auto or pip).

That's true. I had only considered people who were already installing updates in my initial post.

Another similar and surprisingly common case seems to be people who are using an ancient version of Certbot despite an up-to-date version being provided by their current OS ☹️

I don't think we have a good way of knowing how many of the people with ancient versions of Certbot have `server` set this way. With that said, the fix should be trivial (although testing could be tricky) so we may as well do it.

I created https://github.com/certbot/certbot/issues/7979 to track this. I'm currently just planning on including this in our 1.5.0 release at the beginning of June, but if people want to argue for doing a special bug fix release for this change, let me know.

**Comment by bmw** [comment]
It was recently pointed out to me that  LE's changes in the next couple months only affects validations for new domains meaning renewals are not affected.

I updated my initial post to reflect this. The new text added was:

> Only users in the first case will be affected by Let's Encrypt's changes in the next couple months because the other two issues only affect renewal.
>
> Therefore, our instructions to keep Certbot working past LE's upcoming changes are:
>
> 1. Install Certbot 0.26.0+ which we have instructions for every major OS we support at https://certbot.eff.org.
> 2. Don't explicitly request --server <ACMEv1 URL> on the command line or a manually edited global configuration file.
>
> I suspect it to be extremely rare for users to unknowingly do the latter, so really all people should need to do is follow our installation instructions and things should keep working for now.

Because of this, my proposed plan for now is:

1. Not write any special guide to work around LE disabling validations for new domains.
2. Fix https://github.com/certbot/certbot/issues/7979 and bring the issue up with Debian/Ubuntu to see if they will update their packages to fix the problem prior to LE's changes next year.
3. When LE is planning on disabling ACMEv1, pull new statistics. If we still have many users using ACMEv1, we can write a much simpler guide which hopefully will just say to install Certbot using a distribution method we control (like the Certbot snap) and things will be automatically fixed for you.

As usual, if people have thoughts, please share.

**Comment by jsha** [comment]
This sounds like a good plan, but I'd still like to treat #7979 as urgent, so there's plenty of time for the results to make it through various release processes. In this way our staged release process is serving its intended purpose - by getting everyone's attention urgently on the issue while there's still plenty of time to make changes.

Also, I think it's still worthwhile writing a post describing what needs to be done with old installs. There will definitely still be people in this situation next year, and we will want something to point them to. Also, Let's Encrypt will probably start sending out "your setup will break" emails well before the June 2021 date, and it will be nice to have something to link people to in case they have this problem.

**Comment by bmw** [comment]
I agree we should still prioritize #7979.

As for a post now to work around disabling validations for new domains, all we really have to say now is to install updates to get Certbot 0.26.0+ (and don't include `--server <ACMEv1 URL>` on the command line). Every distribution channel I'm aware of (outside of Debian 8 which is EOL'd next month) has packaged this version of Certbot or newer.

We can write that post if you want, but I'd like to wait a few months before writing the post to get everyone off of ACMEv1 entirely. Right now it involves an ugly `sed` command while in 3-4 months I expect the instructions can be to just go install the Certbot snap.

**Comment by bmw** [comment]
Discussion died down here and I think we were mostly in agreement so I'm closing this issue in favor of #7979, https://github.com/certbot/certbot/issues/8004, and https://github.com/certbot/certbot/issues/8005.

Feel free to ping me wherever if you disagree.
