### ISSUE TITLE
Automatically fix ancient Certbot renewal configs

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7979]
A very verbose description of the problem can be found at https://github.com/certbot/certbot/issues/7978#issuecomment-625442870 under the heading "Why does Certbot have the behavior in the previous post?"

Especially since I think fixing it should be easy, we may as well fix this problem in new versions of Certbot by automatically changing `server` values set to LE's ACMEv1 endpoint in renewal configuration files to ACMEv2 on renewal. We have done this kind of thing before to migrate config options for the `webroot` plugin so I think we can follow a similar pattern.

What I had in mind was updating `certbot._internal.renewal._restore_str` so that if the variable name is `server` and its value is the ACMEv1 URL, return the ACMEv2 URL. This should work, but I haven't tested it and I'm open to other approaches.

**Comment by ohemorange** [comment]
A similar but slightly different approach is to always check the `server` value around where it's used (rather than where it's read from the renewal conf), and do the upgrade there like we do for the default.

**Comment by mnordhoff** [comment]
Asking from the peanut gallery, would there be value in a special "0.31.1" point release, or an easily backportable patch, that could be SRUed by Ubuntu 16.04 or any other particularly affected distros?

**Comment by bmw** [comment]
> A similar but slightly different approach is to always check the server value around where it's used (rather than where it's read from the renewal conf), and do the upgrade there like we do for the default.

I might be fine with that depending on where exactly you had in mind.

One thing I'm personally a little hesitant to do is to make `certbot --server <ACMEv1 URL>` use the ACMEv2 URL. If you're running Certbot and explicitly requesting ACMEv1, ignoring that and switching to ACMEv2, especially before ACMEv1 is fully shut down next year, seems annoying to me.

We cannot easily get data on this, but I suspect the number of users doing this accidentally is very small so I'd personally rather respect the user's choice than ignoring it and moving it to ACMEv2.

> Asking from the peanut gallery, would there be value in a special "0.31.1" (edit: or "0.27.2") point release, or an easily backportable patch, that could be SRUed by Ubuntu 16.04 or any other particularly affected distros?

The way I expect this to work is once we have fixed the problem in Certbot, we can bring the issue up with our Debian and Ubuntu package maintainers. If they want to fix the problem and will not fully update Certbot, we can help them backport the fix to whatever version they have.

**Comment by ohemorange** [comment]
> One thing I'm personally a little hesitant to do is to make certbot --server <ACMEv1 URL> use the ACMEv2 URL. If you're running Certbot and explicitly requesting ACMEv1, ignoring that and switching to ACMEv2, especially before ACMEv1 is fully shut down next year, seems annoying to me.

I actually initially assumed that this was the full ACMEv1 shutdown, which is why I proposed this. Your suggestion makes much more sense in light of that.

**Comment by bmw** [comment]
I had assumed that as well and implied it in #7978. Thankfully, I was wrong and that's not until next year.

**Comment by alexzorin** [comment]
>One thing I'm personally a little hesitant to do is to make certbot --server <ACMEv1 URL> use the ACMEv2 URL. If you're running Certbot and explicitly requesting ACMEv1, ignoring that and switching to ACMEv2

Isn't this what will happen at the next renewal anyway? Or is the user expected to modify their cronjob to explicitly feed it `--server <ACMEv1 URL>` as well?

**Comment by bmw** [comment]
Yeah on the next renewal they will be automatically updated to ACMEv2 unless `--server` is set on the command line or in a [global config file](https://certbot.eff.org/docs/using.html#configuration-file).

I suppose I don't have that strong of an opinion here, but commands like `certbot certonly ---server <ACMEv1 URL>` blatantly ignoring the requested server feels bad to me personally.

**Comment by bmw** [comment]
@alexzorin, I saw you created a commit implementing this feature with tests last week. Were you planning on opening a PR? Were there other aspects of this you wanted to look into first?

**Comment by alexzorin** [comment]
@bmw sorry. It took some time to get a testing regime setup for this particular change. I wanted to manually test this against lots of releases. I then hit a snag with a scenario involving the ACMEv1->ACMEv2 upgrade introduced in 0.26.0.

When I renew the certificate using https://github.com/alexzorin/certbot/commit/8a15bd7927e2b8956bb1f4d062423e471e473ccf, I'm hitting:

    $ certbot --config-dir ./conf --logs-dir ./log --work-dir ./work renew --cert-name hello.wtf --force-renewal
    Saving debug log to /home/alex/devel/certbot-test/log/letsencrypt.log

    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    Processing /home/alex/devel/certbot-test/conf/renewal/hello.wtf.conf
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    Using server https://acme-v02.api.letsencrypt.org/directory instead of legacy https://acme-v01.api.letsencrypt.org/directory
    Plugins selected: Authenticator standalone, Installer None
    Renewing an existing certificate
    Attempting to renew cert (hello.wtf) from /home/alex/devel/certbot-test/conf/renewal/hello.wtf.conf produced an unexpected error: urn:ietf:params:acme:error:malformed :: The request message was malformed :: KeyID header contained an invalid account URL: "http://acme-v01.api.letsencrypt.org/acme/reg/43". Skipping.
    All renewal attempts failed. The following certs could not be renewed:
      /home/alex/devel/certbot-test/conf/live/hello.wtf/fullchain.pem (failure)

The same thing happens in master, actually. The symlink gets created and then Boulder rejects the request because the ACMEv1 URL is being used from `regr.json` against the ACMEv2 server.

Either I've done something wrong in my setup or account reuse is broken, blocking this change. I think it's probably best somebody else try tackle this, given the priority.

**Comment by bmw** [comment]
I personally don't have an ACMEv1 account laying around anymore.

@mnordhoff, are you able to easily test this? If you haven't set up our dev environment before, the instructions are at https://certbot.eff.org/docs/contributing.html#running-a-local-copy-of-the-client, although you'll need to use Alex's repo and branch rather than ours.

If we're not able to quickly confirm it's something weird in Alex's setup, I think we should ping jsha. Looking at the code at https://github.com/letsencrypt/boulder/blob/4a2029b293f0fcc38bd3988c91081a2ad01e50d9/wfe2/verify.go#L409, I think this is still supposed to work and it may be a bug or misconfiguration on the boulder side.

**Comment by alexzorin** [comment]
@bmw  thanks, you are right, account reuse is working. As I had no ACME v1 key either, I had being using my own Boulder + some /etc/hosts + proxy setup. Once I fixed up the legacy prefix in the Boulder config, everything worked, including my branch.

**Comment by ohemorange** [comment]
Hey @alexzorin! The code in your commit is looking good; do you want to open a PR or would you rather someone else take it over? We're hoping to get it in during June.

**Comment by alexzorin** [comment]
Yes, please take over. Sorry about missing 1.5.0.
