### ISSUE TITLE
Unable to generate a 1024-bit certificate

### ISSUE THREAD

**Issue by lukeescude** [certbot/certbot#7980]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Linux (CentOS x64)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS pkg manager (yum)

## I ran this command and it produced this output:
certbot certonly --standalone --rsa-key-size=1024

Error message: An unexpected error occurred:
The JWS was signed by a public key the server does not support :: Error finalizing order :: invalid public key in CSR: key too small: 1024

## Certbot's behavior differed from what I expected because:
Would have expected a 1024-bit key/certificate being generated.

Thanks!

**Comment by alexzorin** [comment]
Hi @lukeescude,

Certbot does support generating 1024-bit CSRs, but the CA (Let's Encrypt) won't sign it. The requirements for the certificate key can be found [in Let's Encrypt's CPS](https://letsencrypt.org/documents/isrg-cps-v2.7/#dv-ssl-end-entity-certificate) and also [in the Baseline Requirements that all CAs conform to](https://github.com/cabforum/documents/blob/master/docs/BR.md#6153-subscriber-certificates).

**Comment by ohemorange** [comment]
+1 to Alex's answer, thanks!

**Comment by nasedkin** [comment]
certbot certonly --rsa-key-size 2048 --key-type rsa  -d *.domain.com --email mail@domain.com
