### ISSUE TITLE
Certbot installation not working with RHEL 8.1 and Apache WebServer

### ISSUE THREAD

**Issue by MvanKan** [certbot/certbot#7983]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
RHEL8.1

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
all python3 packages are installed
wget https://dl.eff.org/certbot-auto

## I ran this command and it produced this output:
sudo /usr/local/bin/certbot-auto certonly --standalone --no-bootstrap

Traceback (most recent call last):
  File "/tmp/tmp.tVimBbVxRF/pipstrap.py", line 177, in <module>
    sys.exit(main())
  File "/tmp/tmp.tVimBbVxRF/pipstrap.py", line 158, in main
    for path, digest in PACKAGES]
  File "/tmp/tmp.tVimBbVxRF/pipstrap.py", line 158, in <listcomp>
    for path, digest in PACKAGES]
  File "/tmp/tmp.tVimBbVxRF/pipstrap.py", line 117, in hashed_download
    response = opener(using_https=parsed_url.scheme == 'https').open(url)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>

## Certbot's behavior differed from what I expected because:

installation not complete; urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>

**Comment by schoen** [comment]
Hi @MvanKan,

I don't think this is likely to be a problem in Certbot's code, but rather something about your network or server environment (such as a firewall). Could you please try starting out on the Let's Encrypt Community Forum at https://community.letsencrypt.org/ and seeing if people there can help you? That forum has a *lot* more participants than this GitHub issue tracker, so you're more likely to get useful help there.

Thanks!

**Comment by MvanKan** [comment]
Hi Schoen,

Thank you for your fast response.  I will contact the Letsencrypt community.

Kind regards,  Michel

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
