### ISSUE TITLE
Create directories with secure permissions regardless of the umask and python version

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7993]
In Python 3.7, a significant change was made to `os.makedirs`. From the [os.makedirs documentation](https://docs.python.org/3/library/os.html#os.makedirs), that change was:

> Changed in version 3.7: The mode argument no longer affects the file permission bits of newly-created intermediate-level directories.

The reason this change is relevant for us can be seen below. Starting on a machine with Certbot installed using Python 3.7+ but never having run it, as an unprivileged user with `sudo` privileges you can run:
```
# Let Certbot initially create files with an empty umask
$ sudo sh -c 'umask 0 && certbot certificates'
...
# Then use Certbot to obtain a certificate
...
$ rm -rf /etc/letsencrypt/renewal-hooks/pre
$ mkdir /etc/letsencrypt/renewal-hooks/pre
$ echo -e '#!/bin/bash\necho I am malicious\necho I am running as user: $(id -u)' > /etc/letsencrypt/renewal-hooks/pre/hook.sh
$ chmod +x /etc/letsencrypt/renewal-hooks/pre/hook.sh
$ sudo certbot renew --force-renewal
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/example.com.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Plugins selected: Authenticator standalone, Installer None
Running pre-hook command: /etc/letsencrypt/renewal-hooks/pre/hook.sh
Output from pre-hook command hook.sh:
I am malicious
I am running as user: 0

Renewing an existing certificate
```
The reason this is possible is because `/etc/letsencrypt/renewal-hooks` is world writeable due to being created as an intermediate-level directory by `os.makedirs` with a umask of 0.

While most/all UNIX systems should be protected due to the default umask, I don't think we should fully rely on this.

To fix this, I think we should update `certbot.util.make_or_verify_dir` to temporarily set the `umask` before calling `filesystem.makedirs`. I think the umask value should be:
```
temporary_umask = current_umask | mode_given_to_make_or_verify_dir
```
This should give us consistent behavior around creating files like this on all Python versions.

**Comment by bmw** [comment]
I just corrected what I think the temporary umask should be in my initial post.

**Comment by adferrand** [comment]
We discussed that on live, but wanted a confirmation: does it make sense to implement this fixing logic on `filesystem.makedirs` instead of `certbot.util.make_or_verify_dir`. The benefit I see is that it would make all makedirs operations consistent in all Certbot codebase. The drawback is that it does not follow anymore the logic of the local Python distribution on dirs that do not need a specific security strategy.

**Comment by bmw** [comment]
I'm personally a little torn, initially favored doing it in `certbot.util.make_or_verify_dir` to avoid deviating from the Python standard library on UNIX systems, and I verified that approach is safe with all of our current uses of `filesystem.makedirs`.

With that said, I could see not fixing `filesystem.makedirs` introducing bugs in the future and it is the behavior of the standard library in Python < 3.7 so fixing it there is probably for the best.

Thanks for asking about this.
