### ISSUE TITLE
Cloudflare dns verification is changing proxy setting

### ISSUE THREAD

**Issue by torresdrew** [certbot/certbot#7996]
When verifying domain ownership the dns entry for the domain is changes to DNS only. If that is needed for verification that is fine, but please verify what the setting was before and change it back to proxied if that was the setting before verifying domain ownership. Other application using API access for domain verification have an option to set the proxy status to proxied.

**Comment by alexzorin** [comment]
Certbot's Cloudflare plugin adds/removes `_acme-challenge` records of the `TXT` type. These do not have a proxy option to begin with. Other records are not modified.

What version of `certbot` and `certbot-dns-cloudflare` are you using? Could you post a `/var/log/letsencrypt/letsencrypt.log` which includes a run that resulted in your proxy status being toggled?
