### ISSUE TITLE
"Could not find ssl_module; not disabling session tickets."

### ISSUE THREAD

**Issue by LeoShivas** [certbot/certbot#7998]
Hi everyone,

##  My operating system is :
`CentOS Linux release 8.1.1911 (Core)`

## I installed Certbot with :
`wget https://dl.eff.org/certbot-auto`

## I ran this command and it produced this output:
`/usr/local/bin/certbot-auto renew --apache --apache-server-root /local/httpd/current --apache-challenge-location /local/httpd/current/conf`
```
Upgrading certbot-auto 1.2.0 to 1.4.0...
Replacing certbot-auto...
Creating virtual environment...
Installing Python packages...
Installation succeeded.
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/wiki.my-domain.com.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert is due for renewal, auto-renewing...
Could not find ssl_module; not disabling session tickets.
Plugins selected: Authenticator apache, Installer apache
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for wiki.my-domain.com
Waiting for verification...
Cleaning up challenges

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
new certificate deployed with reload of apache server; fullchain is
/etc/letsencrypt/live/wiki.my-domain.com/fullchain.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/www.my-domain.com.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert is due for renewal, auto-renewing...
Could not find ssl_module; not disabling session tickets.
Plugins selected: Authenticator apache, Installer apache
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for plex.my-domain.com
http-01 challenge for www.my-domain.com
http-01 challenge for www.another-domain.fr
Waiting for verification...
Cleaning up challenges

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
new certificate deployed with reload of apache server; fullchain is
/etc/letsencrypt/live/www.my-domain.com/fullchain.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/www.another-domain.fr.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert is due for renewal, auto-renewing...
Could not find ssl_module; not disabling session tickets.
Plugins selected: Authenticator apache, Installer apache
Renewing an existing certificate

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
new certificate deployed with reload of apache server; fullchain is
/etc/letsencrypt/live/www.another-domain.fr/fullchain.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/wiki.my-domain.com/fullchain.pem (success)
  /etc/letsencrypt/live/www.my-domain.com/fullchain.pem (success)
  /etc/letsencrypt/live/www.another-domain.fr/fullchain.pem (success)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

## Certbot's behavior differed from what I expected because:
It displays an error about ssl_module which is missing, but I had staticly compiled it in Apache and it works perfectly :
```
[root@myserver ~]# httpd -l
Compiled in modules:
  core.c
  mod_authz_core.c
  mod_socache_shmcb.c
  http_core.c
  mod_mime.c
  mod_log_config.c
  mod_proxy.c
  mod_proxy_http.c
  mod_proxy_fcgi.c
  mod_proxy_wstunnel.c
  mod_ssl.c
  event.c
  mod_unixd.c
  mod_dir.c
  mod_alias.c
  mod_rewrite.c
```
So, the error is meaningless.

## Here is a Certbot log showing the issue :
The error is mentionned above in the output command : `Could not find ssl_module; not disabling session tickets.`

## Here is the relevant Apache virtualhost for the domain I am configuring :
This is my compile options :
```
[root@myserver httpd-2.4.41]# cat config.nice
#! /bin/sh
#
# Created by configure

"./configure" \
"--prefix=/local/httpd/current" \
"--enable-ssl=static" \
"--enable-ssl-staticlib-deps" \
"--enable-socache-shmcb" \
"--enable-proxy" \
"--enable-proxy-http" \
"--enable-proxy-wstunnel" \
"--enable-proxy-fcgi" \
"--disable-proxy-connect" \
"--disable-proxy-ftp" \
"--disable-proxy-scgi" \
"--disable-proxy-uwsgi" \
"--disable-proxy-fdpass" \
"--disable-proxy-ajp" \
"--disable-proxy-balancer" \
"--disable-proxy-express" \
"--disable-proxy-hcheck" \
"--disable-so" \
"--enable-rewrite" \
"--enable-mods-static=ssl socache-shmcb proxy rewrite authz_core log_config alias dir unixd mime" \
"--enable-static-rotatelogs" \
"--disable-access_compat" \
"--disable-auth" \
"--disable-auth_basic" \
"--disable-authn_core" \
"--disable-authn_file" \
"--disable-authz_groupfile" \
"--disable-authz_host" \
"--disable-authz_user" \
"--disable-autoindex" \
"--disable-env" \
"--disable-filter" \
"--disable-headers" \
"--enable-mime" \
"--disable-reqtimeout" \
"--disable-setenvif" \
"--disable-status" \
"--disable-version" \
"--disable-authn_dbm" \
"--disable-authn_anon" \
"--disable-authn_dbd" \
"--disable-authn_socache" \
"--disable-authz_dbm" \
"--disable-authz_owner" \
"--disable-authz_dbd" \
"--disable-auth_form" \
"--disable-auth_digest" \
"--disable-allowmethods" \
"--disable-file_cache" \
"--disable-cache" \
"--disable-cache_disk" \
"--disable-cache_socache" \
"--disable-socache_dbm" \
"--disable-socache_memcache" \
"--disable-socache_redis" \
"$@"
```

**Comment by alexzorin** [comment]
As described in #7350, Certbot can't detect `mod_ssl` when it is a prelinked module. This could be fixed by parsing the output of `DUMP_MODULES`, and then joining it to the result of the `LoadModule` parsing.

**Comment by bmw** [comment]
We could and I think that's the best solution here when the module's path is `None`, but I think there are at least two complications:

1. On some systems, Certbot never uses the Apache executable directly and instead uses control scripts like `apache2ctl`. We'll need to give the Apache plugin the name/path of the Apache executable on the different OSes or allow the user to provide it.
2. If we get this wrong because for example the user is using a custom version of Apache at a custom path and has the version provided by their OS installed and we inspect the wrong one, we may try to disable session tickets without being able to safely do so resulting in the confusing behavior investigated in https://github.com/certbot/certbot/issues/7322.

For these reasons, my initial thought on a design here is:

1. Add a command line flag like `--apache-executable` that defaults to `None` on all systems.
2. Update the warning printed in this case to reference this flag.
3. If we don't have a path to `mod_ssl` and `--apache-executable` is set by the user, inspect that file for the OpenSSL version in the same/similar way we do the externally loaded module.

**Comment by alexzorin** [comment]
I've tried to implement that design in #8007, and have also tested it against @LeoShivas' compile options.

I'm not entirely convinced about (2) and the need for the CLI flag, but I do trust that you have the best feeling for the dangers involved. It just "feels like" since `apachectl` is a shim for `httpd`, and we already have `--apache-ctl`, there should be a way to derive it without making an additional demand from the user.

**Comment by bmw** [comment]
Thanks Alex.

> It just "feels like" since `apachectl` is a shim for `httpd`, and we already have `--apache-ctl`, there should be a way to derive it without making an additional demand from the user.

If people have ideas on how to do this in the general case, I'd happily consider them. I agree it'd be better if the user didn't have to provide extra flags, I just don't immediately see a good way to reliably do this.

I also personally think very few people will hit this problem and because of that am leaning towards keeping the workaround for the problem in Certbot simple for now.

**Comment by LeoShivas** [comment]
As I provide `--apache-server-root /local/httpd/current` to Cerbot, isn't it possible to run `httpd -l` from the `bin` directory to list static modules ?

Example from my server :
```
[root@myserver ~]# /local/httpd/current/bin/httpd -l|grep mod_ssl
  mod_ssl.c
```

Another example with both cases :
```
[root@centos8temp ~]# /local/httpd/current/bin/httpd -M 2>&1 |grep mod_ssl || /local/httpd/current/bin/httpd -l|grep mod_ssl
  mod_ssl.c
```

**Comment by alexzorin** [comment]
>isn't it possible to run httpd -l from the bin directory to list static modules

We know the module is static via `apachectl`. We then need the path of the `httpd` bin, to extract the OpenSSL version from, but `${server-root}/bin` is not reliable. For example, it would not work if the Apache is built from Debian sources.

@bmw I'm tempted to not pursue this kind of fix it requires a new flag. What about just changing the prompt to something like: 

>Unable to determine if it is safe to disable session tickets. You may wish to add `SSLSessionTickets off` to your configuration, if your software is newer than Apache 2.4.11+ and OpenSSL 1.0.2l+.

**Comment by bmw** [comment]
My main concern with that is I believe we will continue to print the warning every time the Apache plugin is used. For the sake of things like root email, I think it'd be good if we could give people a way to silence this warning. Maybe we could add/adjust logic to work around that?

**Comment by bmw** [comment]
I'm personally still leaning towards the solution proposed at https://github.com/certbot/certbot/issues/7998#issuecomment-631115800, but if other people have more thoughts I'd be interested to hear them!
