### ISSUE TITLE
Is there a bug in how certbot-dns-rfc2136 finds the DNS record to modify?

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8001]
See https://community.letsencrypt.org/t/problem-updating-dns-txt-record-over-posh-acme-rfc2136/121952/22.

I didn't take the time to read through that post and our code and come to a conclusion to the question in the title of this issue yet, but we probably should at some point.

**Comment by osirisinferi** [comment]
It was a bug in Posh-ACME unrelated to the certbot RFC 2136 implementation according to the developer of Posh-ACME:

https://community.letsencrypt.org/t/problem-updating-dns-txt-record-over-posh-acme-rfc2136/121952/26:

> Just to follow up on this. Upon further testing, the assumption is not flawed. Only my implementation of it was. I was misinterpreting the output of nslookup because it doesn’t differentiate between displaying the actual query answer versus the authority portion of the answer unless you run it in debug mode.
> (&hellip;)
> In any case, there’s nothing wrong with how the certbot RFC2136 plugin functions.
