### ISSUE TITLE
Bring up #7979 with Debian/Ubuntu

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8004]
To do this, I would:

- [x] Pull stats from Let's Encrypt to help estimate how many users should be affected. To do this, I think we can look how many Certbot users have the version packaged in their distro and are still using ACMEv1. We should probably filter this a bit to not count things like a random certbot-auto users on another platform that isn't upgrading, but I think if we explicitly search for Debian/Ubuntu, we can easily miss derivatives of those OSes who would also benefit from an update. With that said, I think we should just come up with the best estimate we easily can here.
- [x] Create issues upstream describing the problem and their options for fixing it. A couple examples of me doing this in the past are at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=932248 and https://bugs.launchpad.net/ubuntu/+source/python-certbot-nginx/+bug/1875471/comments/0. The process for doing this on Debian is described at https://www.debian.org/Bugs/Reporting. The process for doing this on Ubuntu is https://help.ubuntu.com/community/ReportingBugs. For Debian, I may have used `reportbug` in the past, but I know I have also just sent an email. For Ubuntu, I always [file the bug manually on Launchpad](https://help.ubuntu.com/community/ReportingBugs#Filing_bugs_manually_at_Launchpad.net). When describing their options for fixing the problem, I think we should:
  - [x] When Let's Encrypt is planning on shutting down ACMEv1 which is described at https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430.
  - [x] Describe the option of backporting #7979. I don't think we need much more than that suggestion and link the the relevant commit.
  - [x] Describe the option of updating Certbot to 1.6.0+. One thing to keep in mind here is Certbot deprecated Python 3.5 support in 1.7.0 which may be relevant on older systems. I think this should also include:
    - [x] Which of our other components will need to be updated? `acme`? `josepy`? What about the plugins? None of our 3rd party dependencies should need to be updated.
    - [x] The backwards incompatible changes we made from our 0.40.0 and 1.0.0 releases which would affect their users.
    - [x] Maybe say why this option may be preferred from our perspective citing things like the other improvements we've made and the fact we're sticking to well tested versions of Certbot rather than backporting individual changes.

**Comment by ohemorange** [comment]
![Screenshot from 2020-08-20 17-55-12](https://user-images.githubusercontent.com/1227205/90840241-526ace00-e30e-11ea-8652-d799d5b2b751.png)


Here's the code I ran:
```
_sourceCategory=prod CertbotACMEClient (endpoint=/acme/new-cert) (code=201 OR code=200)
| parse field=useragent "CertbotACMEClient/* (*) Authenticator/* Installer/*" as version, os, authenticator, installer nodrop
| parse field=os "*; *" as ua, opsys nodrop
| where ua != "certbot-auto"
| where ua != "letsencrypt-auto"
| where version = "0.23.0" AND os matches "*18.04*" OR version = "0.27.0" AND os matches "*16.04*" OR version = "0.27.0" AND os matches "*18.04*" OR os matches "*stretch*" AND version = "0.28.0" OR version = "0.31.0" AND os matches "*buster*" OR version = "0.40.0" AND os matches "*20.04*"
| top 100 version, os
```
Then I manually combined different sub-versions because it seemed faster and easier than figuring out the syntax to do that.

I don't use sumologic often so I'd love a double-check that I didn't miss anything major and that these numbers seem plausible. I ran it for the last 30 days.

**Comment by ohemorange** [comment]
>  Which of our other components will need to be updated? acme? josepy? What about the plugins? None of our 3rd party dependencies should need to be updated.

Trying to think how to go about testing this. Open an older box, install certbot from package manager. Install newer certbot packages from pip? I don't want to update 3rd party dependencies. If I install just certbot from pip onto the system, will it use the system's packaged dependencies? These are either questions for myself to look into tomorrow or questions for others if they know them off the top of their head.

**Comment by ohemorange** [comment]
I've also drafted the text for the posts (contingent on confirming the various facts mentioned) here: https://docs.google.com/document/d/1vy7_qgS6LDHZKc-vvkZtiy7kVYCD_hpQkH0VT2ezap4/edit?usp=sharing

**Comment by mnordhoff** [comment]
> Install newer certbot packages from pip? I don't want to update 3rd party dependencies. If I install just certbot from pip onto the system, will it use the system's packaged dependencies?

pip\* is generally eager to reinstall as many dependencies as it can think of, but you run like `sudo pip3 install -U --no-deps acme certbot whatever` it should update the packages you explicitly list on the command line without touching anything else. (Even if that would leave them with missing dependencies.)

\* Unsure about newer versions, but they're less relevant here anyway.

**Comment by bmw** [comment]
I started to try and describe how I'd go about figuring this out, but it's a bit tricky. Instead, as a starting point here, I think we should just flag that if they just upgrade Certbot, they will be updating Certbot across the 1.0 API changes so many of Certbot's plugins may need to be updated as well. `acme` will probably also need to be updated to satisfy Certbot's dependency on it. I would check what version of `josepy` we require and see if a new enough version is also in their repos.

One other thing I happened to think of that we should mention for Ubuntu is if they update Certbot to 1.6.0 they'll also need to package the `distro` library (or patch Certbot 1.6.0 losing some of the value of a clean update). See https://github.com/certbot/certbot/pull/7337#issuecomment-525523875.

**Comment by ohemorange** [comment]
The debian bug is available here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=969126

The ubuntu bug is available here: https://bugs.launchpad.net/ubuntu/+source/python-certbot/+bug/1893274

**Comment by bmw** [comment]
Great! Thanks for picking this up.

We now just need to answer any questions they have in response to this. I sometimes also help with testing.

We may also want to poke them if they're not making progress on this, but I'm personally less motivated to do this than I used to be. I do think we should poke Harlan and Robie about Debian and Ubuntu respectively if it seems like they haven't seen it after at most a week or so though.

You accomplished the purpose of this issue though so I think we can close it.
