### ISSUE TITLE
Write community forum post to get people off of ACMEv1

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8005]
Once we have stable Certbot snaps containing the fix for #7979, I think we should probably write a post on the community forum telling people that if they want to get off ACMEv1 they should install Certbot using the latest instructions for their OS. For most users, I think we'll recommend the Certbot snap, but we should make sure we have good instructions for all systems. If some users cannot easily get the fix for #7979, we may have to suggest an ugly `sed` command to work around the problem, but I think us needing to do this is unlikely.

**Comment by WouterVH** [comment]
How you use ACME2 with certbot? Is it possible? How?

As far as I see, certbot is broken because is keeps using ACME1.
It even recommends to use a different ACME-client that supports ACME2

Using python3.7 + virtualenv with
certbot==1.4.0
certbot-dns-route53==1.4.0
certbot-nginx==1.4.0
This is what I get:

```
acme.messages.Error: urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Account creation on ACMEv1 is disabled. Please upgrade yourACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
2020-05-30 17:32:09,306:ERROR:certbot._internal.log:An unexpected error occurred:
2020-05-30 17:32:09,306:ERROR:certbot._internal.log:The client lacks sufficient authorization :: Account creation on ACMEv1 is disabled. Please upgrade yourACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
```


Solution: use acme.sh instead of certbot

**Comment by bmw** [comment]
Glad `acme.sh` works for you!

If you'd like help using Certbot with ACMEv2, I recommend making a post at https://community.letsencrypt.org where there is a large community of people familiar with the project who can help you.

**Comment by bmw** [comment]
I'm going to flag this as blocked on issues like https://github.com/certbot/certbot/issues/8280 and https://github.com/certbot/certbot/issues/8246 (although I'm less worried about the problems in alternative shells than I am with the problems with `sudo` discussed in the fix for that issue at https://github.com/certbot/website/pull/640).

**Comment by bmw** [comment]
Here's my current draft of a post here. I don't love that the final step is just wait and see if you have more problems, but I couldn't really come up with anything better.

# Troubleshooting a Certbot installation that continues to use ACMEv1

Let's Encrypt is in the process of shutting down their ACMEv1 endpoint as described at https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430. The vast majority of Certbot users have already transitioned off of ACMEv1 and do not have do anything, however, if your Certbot install is continuing to use ACMEv1, this post is for you.

### Step 1: Ensure you have an updated version of Certbot

The easiest way to do this is to follow the installation instructions at https://certbot.eff.org/instructions.

In particular, you want to make sure you have Certbot 1.6.0+ or an OS package that has had the changes from Certbot 1.6.0 backported to it. The following packages have backported fixes and can be used instead of Certbot 1.6.0 if desired:

* The Certbot packages in Ubuntu 18.04 Bionic and Ubuntu 20.04 Focal
* The Certbot packages in Debian 9 Stretch and Debian 10 Buster (the update to Debian 10 Buster hasn't been released yet, however, it has been approved and scheduled for release in early February)
* The Certbot packages from Certbot's now deprecated PPA

If you installed Certbot through one of these sources, make sure your package is up-to-date. If you installed Certbot through another source and `certbot --version` outputs a version number older than 1.6.0, you'll need to find a different way to install Certbot and I'd recommend checking out the link above.

### Step 2: Make sure you're not explicitly requesting ACMEv1

It is unlikely that many people did this, however, I'm documenting this just in case for completeness. If you're explicitly requesting Certbot use ACMEv1, you need to stop doing that in order for it to switch to ACMEv2.

First, if you have any scripts, cron jobs, systemd services, etc. running Certbot, make sure they are not setting the `--server` command line option.

Second, make sure that the server option is not set in [Certbot's configuration files](https://certbot.eff.org/docs/using.html#configuration-file). You can check for this by running the following two commands:

    grep -l "server.*acme-v01" ${XDG_CONFIG_HOME-~/.config}/letsencrypt/cli.ini 2>/dev/null
    sudo sh -c 'grep -l "server.*acme-v01" /etc/letsencrypt/cli.ini ${XDG_CONFIG_HOME-~/.config}/letsencrypt/cli.ini 2>/dev/null'

If either command outputs a filename, you should update that file to stop specifying the ACMEv1 server.

### Step 3: Ask for help if you continue to use ACMEv1

If after following these steps you continue to receive emails from Let's Encrypt for using ACMEv1 or are being affected by ACMEv1 brownouts, create a new thread to ask for help.

**Comment by alexzorin** [comment]
Playing catch-up: 

1. What of the Xenial package? Backport not possible there?
2. What release is this fix in on Debian Stretch? I can't see it on https://sources.debian.org/patches/python-certbot/.

>In particular, you want to make sure you have Certbot 1.6.0+ or an OS package that has had the changes from Certbot 1.6.0 backported to it. The following packages have backported fixes and can be used instead of Certbot 1.6.0 if desired:

It could be worthwhile to be more explicit here about package names and required versions. 

On a previous occasion, we had quite a few "message was malformed" threads, caused by users not upgrading the `python-acme` package.

For many, it is not obvious which package one needs to upgrade, and some users are afraid of a system-wide `apt-get upgrade`.

Maybe the post could benefit with an external link to [some kind of reference with names/versions/commands](https://gist.github.com/alexzorin/b2abc1baba16c48b22291bc18862ec47), i.e. "see here for exact details if you have installed Certbot from `apt`".

**Comment by bmw** [comment]
Thanks for the feedback!

> What of the Xenial package? Backport not possible there?

I don't remember seeing an explicit conversation about it, but I think the reason Canonical didn't do this in response to https://bugs.launchpad.net/ubuntu/+source/python-certbot/+bug/1893274 is Xenial will essentially reach its EOL before ACMEv1 is shutdown completely. (It only has paid "extended security maintenance" support after April.)

> On a previous occasion, we had quite a few "message was malformed" threads, caused by users not upgrading the `python-acme` package.
>
> For many, it is not obvious which package one needs to upgrade, and some users are afraid of a system-wide `apt-get upgrade`.
> 
> Maybe the post could benefit with an external link to [some kind of reference with names/versions/commands](https://gist.github.com/alexzorin/b2abc1baba16c48b22291bc18862ec47), i.e. "see here for exact details if you have installed Certbot from `apt`".

Thanks for creating that table! I'd bet they're right, but as a reminder to myself, we should double check those version numbers before posting it.

I'm happy to link to your/a gist if you prefer that, but what do you think about essentially replacing my bullet point list with your table and adding a sentence about `dpkg-query` below it? Does that resolve all of these concerns or do you think there is more we could/should do here?

**Comment by ohemorange** [comment]
I made a few small copy edits inline. For the final step, we can instead have people manually renew with the `--force`-whatever option. This will change their cycle, but it's probably best to find out while they're looking rather than at an unexpected time. Obviously there's the danger of running into rate limits there, but we can tell people to wait a week, and that should handle that.

**Comment by bmw** [comment]
Thanks for the copy edits.

I certainly could be overlooking something, but I think using `--force-renewal` really only works well once ACMEv1 is offline. Otherwise, unless we happen to be in a brownout period, `--force-renewal` may work and continue to use ACMEv1. (We could also include instructions for checking the logs for which server was used, but I personally prefer the wait and see option over recommending people use `--force-renewal` until the logs show ACMEv2.)

**Comment by alexzorin** [comment]
>but what do you think about essentially replacing my bullet point list with your table and adding a sentence about dpkg-query below it

I don't mind. I suggested an external link because inlining a table felt like it'd take too much space, but it's probably fine.

**Comment by ohemorange** [comment]
Yes, I was in fact thinking we also include instructions to check the logs to see what server is used. That would be pretty straightforward to grep for. Waiting is also fine, figured I'd propose an alternative since you seemed to not love that.

**Comment by bmw** [comment]
I merged Alex's table into the post with minor edits.

Thanks for trying to brainstorm ideas to avoid waiting to see if the problem is fixed which I do think is awkward. If you have more ideas you like, please share, but I otherwise personally think waiting is good enough for now and we can update the post if people have trouble.

Unless people share more suggestions, I'll post this soon.

**Comment by bmw** [comment]
With thumbs up from both of you, I went ahead and posted this at https://community.letsencrypt.org/t/troubleshooting-a-certbot-installation-that-continues-to-use-acmev1/143839.

Thanks again for taking a look!
