### ISSUE TITLE
Cannot find any Pythons; please install one! (Yet it exists!)

### ISSUE THREAD

**Issue by fisharebest** [certbot/certbot#8008]
## My operating system is (include version):

RHEL 8

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

`wget https://dl.eff.org/certbot-auto`

## I ran this command and it produced this output:

```
$ ./certbot-auto renew
Requesting to rerun ./certbot-auto with root privileges...
Bootstrapping dependencies for RedHat-based OSes that will use Python3... (you can skip this with --no-bootstrap)
dnf is /bin/dnf
dnf is hashed (/bin/dnf)
Updating Subscription Management repositories.
Last metadata expiration check: 2:05:27 ago on Thu 21 May 2020 14:55:36 UTC.
Package gcc-8.3.1-5.el8.x86_64 is already installed.
Package augeas-libs-1.12.0-5.el8.x86_64 is already installed.
Package openssl-1:1.1.1c-15.el8.x86_64 is already installed.
Package openssl-devel-1:1.1.1c-15.el8.x86_64 is already installed.
Package libffi-devel-3.1-21.el8.x86_64 is already installed.
Package redhat-rpm-config-122-1.el8.noarch is already installed.
Package ca-certificates-2019.2.32-80.0.el8_1.noarch is already installed.
Package python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64 is already installed.
Package python3-virtualenv-15.1.0-19.module+el8.1.0+3514+14e79d98.noarch is already installed.
Package python36-devel-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64 is already installed.
Package mod_ssl-1:2.4.37-21.module+el8.2.0+5008+cca404a3.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
WARNING: couldn't find Python 3.5+ to check for updates.
Creating virtual environment...
Cannot find any Pythons; please install one!
```

## Certbot's behavior differed from what I expected because:

It cannot find python, which exists, and was installed via the package manager in my OS.

## My diagnosis and fix

The `certbot-auto` script has a function `DeterminePythonVersion().`
This function gets called twice.

The first time, it sucessfully finds `/usr/bin/python` (which is a symlink to `python3.6` ).

The second time it enters a "python3" branch, which seaches for an executable `python3` - which doesn't exist, and you get the error about missing pythons.

On my RHEL8 servers, I don't have `/usr/bin/python3`…

```
$ ls -l /usr/bin/python*
lrwxrwxrwx. 1 root root  9 Apr 30 11:23 /usr/bin/python -> python3.6
lrwxrwxrwx. 1 root root 31 Jun  7  2019 /usr/bin/python3.6 -> /usr/libexec/platform-python3.6
```

So, the solution for me is `sudo ln -s python /usr/bin/python3`

I'm not a python dev, so don't know if the missing python3 executable is normal - but I have several RHEL8 servers, which all have the same problem.

**Comment by bmw** [comment]
Strange. That's not the behavior RHEL 8 had before and it is not the (default) behavior documented at https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/using-python3_configuring-basic-system-settings.

I don't think we'll fix this though as we're about to stop recommending `certbot-auto` to RHEL 8 users once https://github.com/certbot/website/pull/581 lands and are planning on deprecating the script entirely in a few months. To get Certbot on your RHEL 8 systems, I recommend following those instructions which are to enable the EPEL 8 repository by following the instructions at https://fedoraproject.org/wiki/EPEL#Quickstart and then installing the Certbot packages available there through `dnf`.

**Comment by fisharebest** [comment]
> I don't think we'll fix this

That's fine.  I posted this as a documented solution as much as anything.

BTW - I was only using `wget certbot-auto`, because `dnf install letsencrypt` failed with a missing dependency on `python3-mock`.

**Comment by bmw** [comment]
> That's fine. I posted this as a documented solution as much as anything.

Thanks for taking the time to do so!

> `dnf install letsencrypt` failed with a missing dependency on `python3-mock`.

That dependency was removed in our release at the beginning of the month which should be in EPEL 8 soon, however, it can be resolved by enabling the codeready-builder-for-rhel-8-*-rpms repository. From https://fedoraproject.org/wiki/EPEL#Quickstart, the command to do that is:
```
   # ARCH=$( /bin/arch )
   # subscription-manager repos --enable "codeready-builder-for-rhel-8-${ARCH}-rpms"
```
