### ISSUE TITLE
Certificate still valid after being revoked.

### ISSUE THREAD

**Issue by WqyJh** [certbot/certbot#8014]
I've revoked an certificate yesterday, but I can still view the site without being warn about certificate verification failure. I tried to revoke the copy of the certificate, but got `The request specified a certificate to be revoked that has already been revoked :: Certificate already revoked`. Therefore, I'm pretty sure that the certificate has been successfully revoked. So how long it will take before the certificate become completely invalid?

## My operating system is (include version):

CentOS Linux release 7.8.2003 (Core)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

pip

## I ran this command and it produced this output:

```bash
sudo certbot revoke --cert-path /etc/letsencrypt/live/xxx/fullchain.pem --key-path /etc/letsencrypt/live/xxx/privkey.pem

Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Would you like to delete the cert(s) you just revoked, along with all earlier
and later versions of the cert?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(Y)es (recommended)/(N)o: (Y)es (recommended)/(N)o: Y

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Deleted all files relating to certificate xxx.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Congratulations! You have successfully revoked the certificate that was located
at /etc/letsencrypt/live/xxx/fullchain.pem
```

**Comment by alexzorin** [comment]
Hi @WqyJh,

Revocation checking delays are influenced by a number of factors:

- Whether OCSP stapling is used on the webserver
- The behavior of the webserver's OCSP stapling implementation
- The behavior of the browser's OCSP implementation

From the Certbot point of view, all it can do is ask for the CA to revoke the certificate. After that point, it's up to the webserver and browser to detect and report the revocation.

If you can post this question to https://community.letsencrypt.org/ with more detail about your domain and webserver, the users there will be able to help you figure out why your certificate's revocation is not being detected.

**Comment by WqyJh** [comment]
Thank you very much!
