### ISSUE TITLE
letsencrypt-auto.template to detect correct system version of virtualenv

### ISSUE THREAD

**Issue by bsodmike** [certbot/certbot#8018]
This is a request for improvement of `letsencrypt-auto-source/letsencrypt-auto.template`; I've only run into this issue so far on one of our systems which is a Ubuntu LTS server.

The system version `/usr/bin/virtualenv --no-site-packages` supports this just find.  Its version is `15.0.1`.

However, `/usr/local/bin/virtualenv` is of version `virtualenv 20.0.7 from /usr/local/lib/python3.5/dist-packages/virtualenv/__init__.py` and this version does not support the flag `--no-site-packages`.  Ideally we should check to see if the version picked up by the script is actually the system version or not. Most likely, the patch should be applied here: https://github.com/certbot/certbot/blob/master/letsencrypt-auto-source/pieces/create_venv.py#L18

When the script picks up the wrong version (the non-system version of virtualenv) this is the error seen:

```
virtualenv: error: unrecognized arguments: --no-site-packages
Traceback (most recent call last):
  File "<stdin>", line 27, in <module>
  File "<stdin>", line 19, in create_venv
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['virtualenv', '--no-site-packages', '--python', '/usr/bin/python2.7', '/opt/eff.org/certbot/venv']' returned non-zero exit status 2
```
 
Reference:
- https://github.com/certbot/certbot/issues/7897

**Comment by m0namon** [comment]
Hi @bsodmike ,
Thanks for looking into this and the detailed issue description. Unfortunately we don't currently recommend or support using `certbot-auto` for installation on Ubuntu; see https://certbot.eff.org/lets-encrypt/ubuntufocal-other.

We're also planning to deprecate this method of installation soon, so I'm going to close this as a wontfix. See another related issue: #7828
