### ISSUE TITLE
DNS plugin for ArvanCloud

### ISSUE THREAD

**Issue by sijad** [certbot/certbot#8019]
ArvanCloud is a DNS and CDN provider.
you can find DNS API here: https://www.arvancloud.com/docs/api/cdn/4.0#tag/DNS

Update: I've create a package https://github.com/sijad/certbot-dns-arvancloud
but it'd be nice to have official support

**Comment by m0namon** [comment]
Thanks for creating a plugin! Just so you know, right now we are not currently accepting new DNS plugins. We want to make a decision on some of the issues like #6464, #6503, and #6504 first -- see those issues for more discussion.
