### ISSUE TITLE
Ensure pip/setuptools are pinned in our snaps

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8023]
While it's rarely a problem, over the years we've found it useful to pin `pip`, `setuptools`, etc. to specific versions rather than always using the latest version. Currently, snapcraft doesn't seem to allow this and they always update to the latest version.

I think it may be possible/the default when the snap is based on Ubuntu 20 though. Looking through the code at https://github.com/snapcore/snapcraft/tree/master/snapcraft/plugins, the Python plugin when used in `core20` seems to just use `python3 -m venv` instead of manually downloading the newest version of `pip`.

We should verify this when https://github.com/certbot/certbot/issues/7854 is resolved. That may be good enough for us or we can maybe add another part to our snap config that runs before all our parts that pins `pip` & co to specific versions before installing other packages.

**Comment by adferrand** [comment]
Certainly way more feasible with snapcraft 4.x, that is about to be released. Indeed a lot of plug-ins have been reworked with this release.

In particular, for our interest, the python plugin is claimed to mostly behave has a proper virtual environment, and so in theory the existing pinning logic for certbot should work with very few adaptations.

See  https://github.com/snapcore/snapcraft/releases/tag/4.0

**Comment by bmw** [comment]
This was done in https://github.com/certbot/certbot/pull/8443 and https://github.com/certbot/certbot/pull/8553.
