### ISSUE TITLE
certbot.ocsp changes for Apache OCSP prefetching

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8024]
For https://github.com/certbot/certbot/pull/7649, we need a way to query OCSP and if the OCSP status is good, get the raw bytes of the OCSP response as well as the nextUpdate timestamp.

Unfortunately, this is a little tricky with the current functions we have in `certbot.ocsp`. The current functions in `certbot.ocsp` only return a `bool` whose value is only `True` if the OCSP status has been validated as revoked. If it has a different status or an error occurs, the value is `False`. We need to fully validate things like the OCSP signature, timestamp, etc. for "good" OCSP responses as well as get more information out of these functions.

To do this, I'd like to propose API changes like those seen at https://github.com/certbot/certbot/compare/ocsp-response-interface.

The reason I'd like to add all these interfaces is to:

1. Minimize passing around raw `bytes`.
2. Allow us to provide an OpenSSL (or other) implementation of this interface in the future without making API changes. (The hard parts of an OpenSSL implementation already exist in #7649. I just want to leave it out for now because I think we may not really need an OpenSSL implementation and to get the initial version of that feature out the door.)

To reuse code, I'm planning on essentially fixing up the current `cryptography` code path to implement the new function and then just checking the `certificate_status` attribute to return `True` or `False` for `ocsp_revoked*`.

Please treat that code as a little pseudocody, but if someone can give any feedback on the high level proposal before I dive deep into an implementation here, I'd really appreciate it!

**Comment by adferrand** [comment]
I think that an OOM approach makes a lot of sense when we are dealing with APIs that needs to be stable. The overall complexity does not seem very high, so I have nothing against, in particular considering that the other parts of OCSP logic in certbot are moving in the same direction, and `acme` module globally uses the same approach with `josepy` classes.

**Comment by bmw** [comment]
@joohoi, thanks for offering to take a look at this. Since you're most familiar with #7649, I think your feedback here is most valuable. To provide some more context for you specifically, the problem here is I don't think this comment is true:
https://github.com/certbot/certbot/blob/ae76f2d3b5baed6ed8c95b47a9f443310215d15c/certbot-apache/certbot_apache/_internal/prefetch_ocsp.py#L156-L157

`ocsp_revoked_by_paths` will also return `False` if there was a network failure, the OCSP response is expired, it's not properly signed, etc.

Another point I wanted to expand on for you is not including an OpenSSL implementation for now. To do this, I was planning on updating [_ensure_ocsp_prefetch_compatibility](https://github.com/certbot/certbot/blob/ae76f2d3b5baed6ed8c95b47a9f443310215d15c/certbot-apache/certbot_apache/_internal/prefetch_ocsp.py#L108) to check `certbot.ocsp.CRYPTOGRAPHY_OCSP_AVAILABLE` and raise a `NotSupportedError` error for now if it's not true.

I just wanted to minimize the work to get this feature out and we can open an issue and save the OpenSSL implementation in a branch for later. I think it's also possible we won't really have a need for it given the direction we're going with packaging and Debian backports, our PPA, and the stable Debian/Ubuntu repositories rarely seeing Certbot updates.

**Comment by joohoi** [comment]
Sorry that it took a while to respond. I'm completely on board with your proposal. In addition to what was said here, the OpenSSL implementation in #7649 was indeed messy from the API standpoint. 

The proposed interface will make a world of difference for handling OCSP related functionality in the current and future code. Nice job!

**Comment by bmw** [comment]
This is implemented in the `ocsp-response` branch for us to use in the future.
