### ISSUE TITLE
Docs regarding ciphersuite updates are out of date.

### ISSUE THREAD

**Issue by RasPat1** [certbot/certbot#8027]
The certbot docs show a method to update the security level on the accepted ciphersuites and protocols.  These commands are invalid and I believe the docs need to be updated. Is that feature still supported?

Here's a link to the relevant documentation:
https://github.com/certbot/certbot/blob/f66314926aa842804b8b64af785f2cef5296e0c5/certbot/docs/ciphers.rst#changing-your-settings

**Comment by bmw** [comment]
The current documentation is pretty misleading. In the prior section it says:

> It will be possible to ask Certbot to instead apply (and track) Modern or Old configurations.

And then the changing your settings section talks about how "This will probably look something like..." and links to an issue I closed in 2017 saying we wouldn't implement it.

If someone wants to submit a PR removing the quoted sentence and deleting the "Change your settings" and "TODO" sections, that'd be great!

Thanks for flagging this @RasPat1.

**Comment by RasPat1** [comment]
Sure, I can update the docs. PR included
