### ISSUE TITLE
Apt package: remove dependency on universe repo

### ISSUE THREAD

**Issue by mohamedhafez** [certbot/certbot#8028]
Depending on the universe repo for a security-critical tool such as this is pretty scary, I've definitely seen packages in universe with known security issues not receiving updates in the past. It would be great if the Certbot PPA would include it's own, up-to-date versions of packages currently taken from universe, such as `python3-ndg-httpsclient`, etc

**Comment by bmw** [comment]
I don't think we'll ever do this because it causes other problems such as https://github.com/certbot/certbot/issues/5234.

If we did anything here, I think we'd either try to keep the universe packages secure or drop any dependencies on packages in universe. Other than `python3-ndg-httpsclient`, do you know what other packages there we depend on?

**Comment by mohamedhafez** [comment]
It looks like the packages from universe are:

python3-configargparse
python3-mock
python3-ndg-httpsclient 
python3-zope.event

Perhaps instead of dropping dependencies on packages from universe, a better solution that would address this and https://github.com/certbot/certbot/issues/5234 would be to just switch to snap packages as the preferred installation method. I know there's a snap package in beta at https://snapcraft.io/certbot, it would be great to see it getting attention and getting priority over the PPA since it would solve all of these problems

**Comment by mohamedhafez** [comment]
Looks like your way ahead of me! https://github.com/certbot/certbot/issues/5234#issuecomment-594217439. I wasn't sure if the snap was just a side project or something, it's great to hear you guys are hoping to transition to that as the official way of installing! I'll close this bug since that would address my concerns.
