### ISSUE TITLE
Build, test, and deploy Certbot DNS plugin snaps in CI

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8041]
Blocked #7672 which tracks creating these plugin snaps and https://github.com/certbot/certbot/issues/8064 which tracks ensuring we can always build them and https://github.com/certbot/certbot/issues/8071.

I think we probably also want to block deploying the DNS plugin snaps on https://github.com/certbot/certbot/issues/7935 which tracks creating a EFF/Certbot snapcraft account. (Note: account is created, though that issue is still open because ownership has not been transferred. That shouldn't block this issue though.)

I also personally think it's fine if the initial version of this just supports amd64, although I think all architectures we're building Certbot snaps for should be supported in the near future.

**Comment by bmw** [comment]
To add tests for the DNS plugin snap, we'll need to make sure the Certbot snap it is connected to is built from the same source because otherwise the Certbot snap may not have changes to Certbot's API that the plugin snap requires.

**Comment by bmw** [comment]
I played with `snapcraft remote-build` a bit this morning. Things I found:

1. At least by default, it sends the contents of your current working directory, including uncommitted changes, to launchpad. Other files in the git repo are not sent.
2. The build times suggested by launchpad were wildly inaccurate for me. It told me twice my build would take 45 minutes to an hour to start, but the longest I waited for any architecture was 10 minutes.
3. We'll need to update the DNS plugins to include build dependencies for cryptography/cffi.

Erica's idea of not resolving [#8100](https://github.com/certbot/certbot/issues/8100) and just creating this file before running `snapcraft remote-build` should work well I think.

One potential problem is git metadata doesn't seem to be preserved which we make use of in the Certbot snap to determine the version, however, this isn't currently a problem in the DNS plugin snaps because we just grab the version from `setup.py`. We could just change the Certbot snap to do the same thing if there are no downsides.

**Comment by ohemorange** [comment]
> One potential problem is git metadata doesn't seem to be preserved which we make use of in the Certbot snap to determine the version, however, this isn't currently a problem in the DNS plugin snaps because we just grab the version from setup.py. We could just change the Certbot snap to do the same thing if there are no downsides.

Oh my god I can't believe this worked. Another idea:

```
erica@ebp-dell:/tmp/certbot$ cp -r .git certbot-dns-dnsimple/
erica@ebp-dell:/tmp/certbot$ cd certbot-dns-dnsimple/
erica@ebp-dell:/tmp/certbot/certbot-dns-dnsimple$ git describe
v1.5.0-51-g95ef53e5d
```

**Comment by bmw** [comment]
To share a little context here, I assigned this to Adrien because I think it is largely blocked on and/or conflicts with the transition to Azure Pipelines which he is working on. The plan was for him to start working on this as soon as the Azure Pipelines work was merged and to even get a head start on it by building off of the unmerged https://github.com/certbot/certbot/pull/8098 if he's waiting on me for review.

What he is planning to set up is a simple build and test pipeline for the DNS plugins building the snap locally in Azure and only for amd64. He and I are both leaning towards switching the builds to `snapcraft remote-build`, but he's not planning on setting this up in the initial version of this.

Maybe some of that work and/or some of this issue could be done more in parallel, but I think without some pretty careful planning which I don't currently have an idea for, there will be conflicts. Because of that and the fact we certainly aren't short on Certbot work right now, I wasn't going to worry about trying to parallelize this stuff now, but if other people would like to and have ideas, don't hesitate to chime in!

**Comment by bmw** [comment]
Also, the credentials set up in Azure _should_ have permissions to push to the newly registered DNS plugin snaps on the snap store. I exported the credentials beforehand, but I did not limit the snaps on my account they could push to.

If it doesn't work, I think we should tackle https://github.com/certbot/certbot/issues/8119 as part of fixing it.
