### ISSUE TITLE
Stop using adferrand/snapcraft

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8045]
Similar to https://github.com/certbot/certbot/issues/7943, https://github.com/certbot/certbot/pull/8016 proposed using the `adferrand/snapcraft` Docker images until the needed features land upstream which is tracked at https://github.com/snapcore/snapcraft/pull/3144.

I personally think this is totally fine for now, but if https://github.com/snapcore/snapcraft/pull/3144 doesn't land in the near future, I think we should probably move the Docker images and the code for them under Certbot on GitHub and Docker Hub.

**Comment by abitrolly** [comment]
It looks like `snapcraft` doesn't have the capacity for reviewing Docker stack.

**Comment by bmw** [comment]
To accomplish this, I think we should probably switch things over to using `snapcraft remote-build`.

**Comment by bmw** [comment]
You'll probably need me to set up credentials here. It'd be useful if you could test it and tell me what's needed, but the only documentation I've seen about this is at https://forum.snapcraft.io/t/preview-snapcraft-remote-build/11541?u=bmw. We may be able to use the same credential for both `remote-build` and `upload` but I'm not sure.

Also, we should be careful that no secure files are uploaded with `snapcraft remote-build`.
