### ISSUE TITLE
Update snap docs to say we support more architectures

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8051]
After we've pushed snaps for other architectures to the beta channel, we need to update our docs. Off the top of my head, I think we need to update the Certbot website, the static docs in this repo, and update and/or create a new post on the community forum. It'd be good for whoever takes this to double check I didn't miss anything though.

**Comment by adferrand** [comment]
Once #8174 and https://github.com/certbot/certbot/pull/8174 are merged, we need to create a post in the community forum.

**Comment by bmw** [comment]
Thanks. I'll take care of that piece.

I personally think we should merge the community forum posts about this, DNS plugins, and a stable Certbot snap into one.

**Comment by bmw** [comment]
Community forum post is at https://community.letsencrypt.org/t/certbot-snap-updates/130301.
