### ISSUE TITLE
Docs have low font weight / contrast

### ISSUE THREAD

**Issue by cgay** [certbot/certbot#8052]
Hi all. I just want to let you know that the docs on the website, for example
https://certbot.eff.org/docs/using.html#renewing-certificates, are quite difficult for me to read because of the very light "weight" of the font (i.e., the lines are so thin), on top of the fact that it's fairly low contrast. It would be great if a higher font weight and/or contrast could be used.

Using a Chrome extension like "Just Read" helps, but those are often not great for technical docs because of the way they reformat the page.

**Comment by cgay** [comment]
For a little context, I do wear glasses, but only a very mild prescription, which is to say that I don't think I'm so far off normal sight that I'm an outlier.

**Comment by alexzorin** [comment]
Would you be able to include a screenshot? Font rendering varies wildly between browser/OS combos. It would be useful to see exactly what you see.

**Comment by cgay** [comment]
![f5XsTSur4ue](https://user-images.githubusercontent.com/491829/83824223-dfa16d80-a6a3-11ea-9c49-f3db9bf442a9.png)

**Comment by cgay** [comment]
By the way, on my screen (a 2015 Macbook Pro Retina) looking at the screenshot I uploaded at 100% magnification looks **very** different from what I actually see on my screen.  In fact the fonts are much thicker and easier to read, so I'm not sure how useful it is for evaluating what I see.

**Comment by alexzorin** [comment]
Does the 300 weight look OK to you on https://fonts.google.com/specimen/Roboto?

If not, what weight does?

**Comment by cgay** [comment]
The 300 looks totally readable, yes.  The 100 is too thin for sure.  Thanks for looking at this, Alex.

**Comment by kden** [comment]
I will try working on this one now.  Will update if it's beyond my current capabilities.

**Comment by kden** [comment]
@cgay I'm following up on this, and had a few more questions.  The body text on the renewing certificates page you linked is 300 font-weight but the default size is 16px.  The samples on the Google fonts page are 30px.  If you zoom out to 50% on the Google fonts page so that the text sizes are about the same, what is the lowest font weight that is comfortably readable for you?  

Does it work for you to zoom in on the renewing-certificates page, or does that make the page difficult to use?

**Comment by cgay** [comment]
On the Google fonts page, zoomed out to 50%, 400 is the one that feels right.

Zooming in to 125% or 150% on the renewing-certificates page starts to feel comfortable.

Again, don't get me wrong, I can most definitely read the existing doc at 100%, it's just got that indefinable quality of stressfulness. :)

**Comment by cgay** [comment]
The page in my original comment definitely looks better now. Easy enough to read at 100% (i.e., no) magnification. Thanks!

**Comment by cgay** [comment]
The current pages are very readable. Thank you for fixing this.
