### ISSUE TITLE
Automatically catch Sphinx errors

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#8060]
Copied from #7991:

> If you look at https://certbot.eff.org/docs/api/certbot.compat.filesystem.html, you'll notice many formatting errors which should be fixed.
> 
> That's the bare minimum which I think should be done, but I think we should also see what we can do to avoid these problems from happening in the future. Is there a way we could build the docs in CI and check for these problems? Unfortunately, Sphinx doesn't seem to currently warn about all of the problems here, at least with the warnings it currently has. (Maybe new warnings will appear after others are fixed?)
> 
> Finding a way to better catch these problems could be left for future work.

Now that those specific errors are fixed, we should also find a way to automatically check for them.

**Comment by Farchanter** [comment]
hey @ohemorange , could you describe what the formatting issues looked like? I'm just coming on to the project and didn't see the badly formatted page until it was fixed.

**Comment by ohemorange** [comment]
Hm, if I remember correctly, it things getting smushed together and maybe some weird bolding? If you look at the PR, you can see the types of changes we had to make: https://github.com/certbot/certbot/pull/8058/files

It's mostly about making sure there are appropriate spaces, and that code (underscores, parens) is appropriately marked with fixed-width text markers:
```
`
```
