### ISSUE TITLE
rfc2136 failing for a few wildcards names

### ISSUE THREAD

**Issue by GuillaumeBibaut** [certbot/certbot#8069]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
FreeBSD 12.1-RELEASE

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
```
# pkg info -a -o | grep certbot
py37-certbot-1.5.0,1           security/py-certbot
py37-certbot-dns-rfc2136-1.5.0 security/py-certbot-dns-rfc2136
```

## I ran this command and it produced this output:
Command (61 seconds was my latest test):
```
SUDOCMD="/usr/local/bin/sudo"
CERTBOTCMD="/usr/local/bin/certbot"
CERTBOTUSER="certbot"

${SUDOCMD} -u ${CERTBOTUSER} ${CERTBOTCMD} renew \
    --quiet \
    --disable-hook-validation \
    --dns-rfc2136-propagation-seconds 61 \
    --config-dir /usr/local/etc/letsencrypt \
    --work-dir /var/db/letsencrypt \
    --logs-dir /var/log/letsencrypt \
    --deploy-hook /root/bin/certbot-hook.sh
```
Output:
```
Challenge failed for domain user1.site1.dev.example.com
Challenge failed for domain user1.site2.dev.example.com
Challenge failed for domain user2.site3.dev.example.com
Challenge failed for domain user2.site4.dev.example.com
Challenge failed for domain user3.site3.dev.example.com
Challenge failed for domain user3.site4.dev.example.com
Challenge failed for domain user4.site5.dev.example.com
Challenge failed for domain user4.site6.dev.example.com
Challenge failed for domain user4.site1.dev.example.com
Challenge failed for domain user4.site7.dev.example.com
Challenge failed for domain user4.site4.dev.example.com
Challenge failed for domain user5.site2.dev.example.com
Challenge failed for domain user6.site3.dev.example.com
Challenge failed for domain user6.site7.dev.example.com
Challenge failed for domain user7.site3.dev.example.com
Challenge failed for domain user7.site8.dev.example.com
Challenge failed for domain user8.site5.dev.example.com
Challenge failed for domain user8.site6.dev.example.com
Challenge failed for domain user8.site8.dev.example.com
Attempting to renew cert (dev.example.com) from /usr/local/etc/letsencrypt/renewal/dev.example.com.conf produced an unexpected error: Some challenges have failed.. Skipping.
Challenge failed for domain a1.site2.example.com
Attempting to renew cert (a1.site1.example.com) from /usr/local/etc/letsencrypt/renewal/a1.site1.example.com.conf produced an unexpected error: Some challenges have failed.. Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /usr/local/etc/letsencrypt/live/dev.example.com/fullchain.pem (failure)
  /usr/local/etc/letsencrypt/live/a1.site1.example.com/fullchain.pem (failure)
2 renew failure(s), 0 parse failure(s)
```
This output is due to a dev server on which I've got something like 8 users, and for each user, the ability to test at least 10 differents web sites. So this means I've got at least 80 wildcards configured.
In march 2020, and before that, the certificate was well issued with no problem.

Also for a1.site1.example.com, I've got 3 websites per server, and 8 servers. The certficates are well issued for the 3 websites `a2.*.example.com`. Each server gets a certificate with the 3 websites for this server.

I've verified each renewal config, and they are all set to rfc2136 as intended.

My DNS server is configured to accept a wildcard grant for the dev.example.com server and is configured this way:
```
include "/usr/local/etc/namedb/certbot.keys";

zone "example.com" {
[...]
update-policy {
                grant local-ddns zonesub any;
                grant certbot.dev. wildcard *.dev.example.com. txt;
                grant certbot.front. wildcard *.site1.example.com. txt;
[...]
```
here is a subset records from the DNS zone:
[zone-records.txt](https://github.com/certbot/certbot/files/4764903/zone-records.txt)

While the command is executing, I can check some DNS TXT records, and they are available and set with a value, here are some example:
```
## While the command was running
# host -t txt _acme-challenge.user8.site8.dev.example.com                                                                                                        
_acme-challenge.user8.site8.dev.example.com descriptive text "wKrMDGvmNxdqxN46Wcr4uGsMXJHG4e4qgp06tgciy7E"
## After the command ran
# host -t txt _acme-challenge.user8.site8.dev.example.com                                                                                                        
_acme-challenge.user8.site8.dev.example.com is an alias for dev.example.com.
```
So I cannot see why the command results with failed challenge since TXT records are updated.

To issue all the certificates I need for my company, I've got to run the command many times, some certificates fail, some are issued. Then I run the command again, and some failed ones before are now issued correctly. But It'm still getting these errors for dev.example.com and a1.site1.example.com

## Certbot's behavior differed from what I expected because:
I don't know why this was working fine 3 months ago, and now it's not working correctly anymore.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
This log has been modified extensively to obfuscate any sensite data. And it is long.
[letsencrypt.log](https://github.com/certbot/certbot/files/4764655/letsencrypt.log)

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
Not relevant, I'm using rfc2136.

**Comment by bmw** [comment]
Thanks for the detailed writeup @GuillaumeBibaut.

The behavior you described of challenges sometimes succeeding and sometimes failing sounds to me like the value of `--dns-rfc2136-propagation-seconds` needs to be updated to a longer value. Another thing to try while debugging is including `--debug-challenges --dry-run` on the command line. The first flag causes Certbot to wait before telling Let's Encrypt to validate challenges giving you time to inspect things while the latter uses Let's Encrypt's test server without saving the resulting certificates. The benefit of `--dry-run` is you are not subject to as strict of rate limits and Certbot doesn't allow Let's Encrypt to reuse authorizations making sure it validates the challenge for each domain.

I'd also recommend you make a post at https://community.letsencrypt.org about this as there is a much larger community of people familiar with Certbot and server administration. They should be able to help you track down the problem and if it's a bug in Certbot, we can help get it fixed here.

**Comment by GuillaumeBibaut** [comment]
I've tried to set to 180 seconds, but it doesn't seem to help (enough?).

I'm going to follow your advice and post this on the let's encrypt community.

**Comment by GuillaumeBibaut** [comment]
It seems pushing to 300 seconds made it.

But now... to apply 300 seconds to every renewal ( < 30 days), I think it would be too much. Do you know if there is a way to configure that propagation seconds inside the `config/renewal/domain.name.conf` for example? So that I could tell 300 seconds for the big one (lots of DSN in one certificate), and less for small ones.

**Comment by GuillaumeBibaut** [comment]
I've checked the configuration files created on my system, it seems that there is such a parameter. I'm going to test this without the certbot argument to check if configuration file contextual value is applied.

Thank you for leading me to a solution.
