### ISSUE TITLE
Apache find_dir, arg search should look at variables and unquote args

### ISSUE THREAD

**Issue by jdkasten** [certbot/certbot#807]
Finish #806

Look at find_dir documentation for details for fix.

**Comment by pde** [comment]
@jdkasten should this be a **1.0 for launch** ticket?

**Comment by pde** [comment]
or **nice for 1.0**?

**Comment by SwartzCr** [comment]
mentioning this to @joohoi

**Comment by joohoi** [comment]
Adding as note; related to #2481
