### ISSUE TITLE
multiple modules reference github.com/letsencrypt/letsencrypt as their url, not github.com/certbot/certbot

### ISSUE THREAD

**Issue by jvanasco** [certbot/certbot#8082]
I was going through the source in certbot and needed to reference the ACME library

I found the package on PyPi.org, clicked the link for the homepage, and was sent to https://github.com/letsencrypt/letsencrypt 

Ultimately that redirected here, but the source code should really be updated at some point. 

It looks like all the projects in this repo use the same line in `setup.py`

* https://github.com/certbot/certbot/blob/master/acme/setup.py#L70
* https://github.com/certbot/certbot/blob/master/certbot/setup.py#L130

**Comment by ohemorange** [comment]
Nice catch, we should probably get around to updating that at some point. I wouldn't be shocked if something in `letsencrypt-auto` is relying on that URL, but maybe someone else knows.

**Comment by ohemorange** [comment]
hah, yeah, we should still fix this
