### ISSUE TITLE
Default Python does not send http/1.1 ALPN extension causing problems

### ISSUE THREAD

**Issue by paulmenzel** [certbot/certbot#8087]
Certbot fails to update the certificates, if the [Coturn](https://github.com/coturn/coturn/) TURN server is installed, which is common for WebRTC videoconferencing systems like [Jitsi](https://jitsi.org/).

```
2020-06-07 06:50:35,733:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 07 Jun 2020 04:50:35 GMT
Content-Type: application/json
Content-Length: 1325
Connection: keep-alive
Boulder-Requester: 80920184
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0102urbeva1ZSfJjKYRifmJK3JbS_ur6FfGJvmMsnXT6fu0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "jitsi.molgen.mpg.de"
  },
  "status": "invalid",
  "expires": "2020-06-14T04:50:30Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:connection",
        "detail": "Fetching https://jitsi.molgen.mpg.de/.well-known/acme-challenge/wKiGofUFEJHnZyh9-a_N-elRQDa0wuAP2OngqA_gLaA: Error getting validati
on data",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/5071692239/SI7c-Q",
      "token": "wKiGofUFEJHnZyh9-a_N-elRQDa0wuAP2OngqA_gLaA",
      "validationRecord": [
        {
          "url": "http://jitsi.molgen.mpg.de/.well-known/acme-challenge/wKiGofUFEJHnZyh9-a_N-elRQDa0wuAP2OngqA_gLaA",
          "hostname": "jitsi.molgen.mpg.de",
          "port": "80",
          "addressesResolved": [
            "141.14.220.179"
          ],
          "addressUsed": "141.14.220.179"
        },
        {
          "url": "https://jitsi.molgen.mpg.de/.well-known/acme-challenge/wKiGofUFEJHnZyh9-a_N-elRQDa0wuAP2OngqA_gLaA",
          "hostname": "jitsi.molgen.mpg.de",
          "port": "443",
          "addressesResolved": [
            "141.14.220.179"
          ],
          "addressUsed": "141.14.220.179"
        }
      ]
    }
  ]
}
```

As it works with curl and browsers, but failed with Python, @tiran figured out, [that no http/1.1 ALPN extension is sent](https://bugs.python.org/issue40968), and even created https://github.com/python/cpython/pull/20959.

It’d be great of you could update your installation, to sent the extension.

**Comment by bmw** [comment]
If I am understanding you correctly and you are claiming that no http/1.1 ALPN extension is sent by the software validating the challenge to prove control over your domain which is causing the challenge to fail in this setup, then this is not a problem with Certbot. Certbot is the client software that runs on your machine to communicate with an external server running other software which is responsible for validating the challenge. In this case, the external server is run by Let's Encrypt which is run by a different organization whose server software [boulder](https://github.com/letsencrypt/boulder/) is written in Go. If you think their software is incorrect, I encourage you to open an issue there.

I'm closing this issue for now, but if I have misunderstood you, please comment and I'll reopen this issue.
