### ISSUE TITLE
centos 7 snap apache plugin crash: `version `GLIBC_2.18' not found`

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8093]
## My operating system is (include version):

    centos-release-7-8.2003.0.el7.centos.x86_64

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

snapcraft: https://certbot.eff.org/lets-encrypt/snap-apache

## I ran this command and it produced this output:

    [root@toast-garlic ~]# certbot --apache
    Saving debug log to /var/log/letsencrypt/letsencrypt.log
    Error while running apachectl configtest.

    httpd: Syntax error on line 56 of /etc/httpd/conf/httpd.conf: Syntax error on line 6 of /etc/httpd/conf.modules.d/10-php.conf: Cannot load modules/libphp5.so into server: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /snap/core18/current/usr/lib/x86_64-linux-gnu/libstdc++.so.6)

    The apache plugin is not working; there may be problems with your existing configuration.
    The error was: MisconfigurationError("Error while running apachectl configtest.\n\nhttpd: Syntax error on line 56 of /etc/httpd/conf/httpd.conf: Syntax error on line 6 of /etc/httpd/conf.modules.d/10-php.conf: Cannot load modules/libphp5.so into server: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /snap/core18/current/usr/lib/x86_64-linux-gnu/libstdc++.so.6)\n",)
 

## Certbot's behavior differed from what I expected because:

No crash should occur. Here is the `pstree -lagpsS` dump from when `configtest` is running:

    ├─sshd,1053,1053
    │   ├─bash,1055,1055
    │   │   └─python3,32361,32361 /var/lib/snapd/snap/certbot/345/bin/certbot --apache --staging
    │   │       └─apachectl,32416,32361 /usr/sbin/apachectl configtest
    │   │           └─httpd,32420,32361 -t

Running the same program directly from the host system is fine:

    [root@toast-garlic ~]# /usr/sbin/apachectl configtest
    Syntax OK

Here is an strace of `httpd -t` running under the Certbot snap's namespace: https://paste.sr.ht/blob/9144377dcbe5b1276605d523de46be2d49c1afcb 

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

<details>

<summary>Log</summary>

    2020-06-19 07:32:49,188:DEBUG:certbot._internal.main:certbot version: 1.5.0
    2020-06-19 07:32:49,190:DEBUG:certbot._internal.main:Arguments: ['--apache', '--staging']
    2020-06-19 07:32:49,191:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
    2020-06-19 07:32:49,210:DEBUG:certbot._internal.log:Root logging level set at 20
    2020-06-19 07:32:49,211:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
    2020-06-19 07:32:49,212:DEBUG:certbot._internal.plugins.selection:Requested authenticator apache and installer apache
    2020-06-19 07:32:49,287:ERROR:certbot.util:Error while running apachectl configtest.

    httpd: Syntax error on line 56 of /etc/httpd/conf/httpd.conf: Syntax error on line 6 of /etc/httpd/conf.modules.d/10-php.conf: Cannot load modules/libphp5.so into server: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /snap/core18/current/usr/lib/x86_64-linux-gnu/libstdc++.so.6)

    2020-06-19 07:32:49,288:DEBUG:certbot._internal.plugins.disco:Misconfigured PluginEntryPoint#apache: Error while running apachectl configtest.

    httpd: Syntax error on line 56 of /etc/httpd/conf/httpd.conf: Syntax error on line 6 of /etc/httpd/conf.modules.d/10-php.conf: Cannot load modules/libphp5.so into server: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /snap/core18/current/usr/lib/x86_64-linux-gnu/libstdc++.so.6)
    Traceback (most recent call last):
      File "/snap/certbot/345/lib/python3.6/site-packages/certbot_apache/_internal/configurator.py", line 2436, in config_test
        util.run_script(self.option("conftest_cmd"))
      File "/snap/certbot/345/lib/python3.6/site-packages/certbot/util.py", line 89, in run_script
        raise errors.SubprocessError(msg)
    certbot.errors.SubprocessError: Error while running apachectl configtest.

    httpd: Syntax error on line 56 of /etc/httpd/conf/httpd.conf: Syntax error on line 6 of /etc/httpd/conf.modules.d/10-php.conf: Cannot load modules/libphp5.so into server: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /snap/core18/current/usr/lib/x86_64-linux-gnu/libstdc++.so.6)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/snap/certbot/345/lib/python3.6/site-packages/certbot/_internal/plugins/disco.py", line 134, in prepare
        self._initialized.prepare()
      File "/snap/certbot/345/lib/python3.6/site-packages/certbot_apache/_internal/configurator.py", line 311, in prepare
        self.config_test()
      File "/snap/certbot/345/lib/python3.6/site-packages/certbot_apache/_internal/override_centos.py", line 52, in config_test
        super(CentOSConfigurator, self).config_test()
      File "/snap/certbot/345/lib/python3.6/site-packages/certbot_apache/_internal/configurator.py", line 2438, in config_test
        raise errors.MisconfigurationError(str(err))
    certbot.errors.MisconfigurationError: Error while running apachectl configtest.

    httpd: Syntax error on line 56 of /etc/httpd/conf/httpd.conf: Syntax error on line 6 of /etc/httpd/conf.modules.d/10-php.conf: Cannot load modules/libphp5.so into server: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /snap/core18/current/usr/lib/x86_64-linux-gnu/libstdc++.so.6)

    2020-06-19 07:32:49,290:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * apache
    Description: Apache Web Server plugin
    Interfaces: IAuthenticator, IInstaller, IPlugin
    Entry point: apache = certbot_apache._internal.entrypoint:ENTRYPOINT
    Initialized: <certbot_apache._internal.override_centos.CentOSConfigurator object at 0x7f49b5de8358>
    Prep: Error while running apachectl configtest.

    httpd: Syntax error on line 56 of /etc/httpd/conf/httpd.conf: Syntax error on line 6 of /etc/httpd/conf.modules.d/10-php.conf: Cannot load modules/libphp5.so into server: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /snap/core18/current/usr/lib/x86_64-linux-gnu/libstdc++.so.6)

    2020-06-19 07:32:49,292:DEBUG:certbot._internal.plugins.selection:Selected authenticator None and installer None
</details>

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

N/A, just standard empty port 80 virtualhost. `httpd` and `php`/`mod_php` installed from CentOS 7 base repos.

**Comment by bmw** [comment]
I just hit almost the exact same error with the nginx plugin running `certbot plugins --prepare` with the edge version of the Certbot snap on Ubuntu 18.04.

My current theory is we need to clean up environment variables such as `PATH` and `LD_LIBRARY_PATH` before calling external programs. As of writing this, those are the only two relevant environment variables explicitly set in our [snapcraft config](https://github.com/certbot/certbot/blob/0f53e8ad4e336b9742ffef9efa98b0198bc3a009/snap/snapcraft.yaml#L24-L27), however, there may be others that are set automatically when running the snap.

**Comment by powerh0use** [comment]
So I think I found the root of my issue.
When I run "certbot --apache" I get
`The following error was encountered:
[Errno 13] Permission denied: '/var/log/letsencrypt/.certbot.lock'
Either run as root, or set --config-dir, --work-dir, and --logs-dir to writeable paths.
`
So I "sudo certbot --apache" and get:
`sudo: certbot: command not found
`
So I "echo $PATH" and see:
`/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/var/lib/snapd/snap/bin:/home/orca/.local/bin:/home/orca/bin
`
which has the snapd in PATH.  This tells me snapd is not connecting sudo to the snapd or certbot? ***scratches head***

**Comment by adferrand** [comment]
Hello @powerh0use. I know that outside Ubuntu, one manual action is needed to make snaps with classic confinment to work correctly. You can look at the relevant instructions for CentOS7 here: https://snapcraft.io/docs/installing-snap-on-centos

**Comment by powerh0use** [comment]
> Hello @powerh0use. I know that outside Ubuntu, one manual action is needed to make snaps with classic confinment to work correctly. You can look at the relevant instructions for CentOS7 here: https://snapcraft.io/docs/installing-snap-on-centos

Thanks for the reply.  I have snapd installed on my machine already.  
Upon my research I discovered:
`[orca@orcacomputers log]$ systemctl status snapd
● snapd.service - Snap Daemon
   Loaded: loaded (/usr/lib/systemd/system/snapd.service; disabled; vendor preset: disabled)
   **Active: inactive (dead)**
[orca@orcacomputers log]$ 
` That's the first time I ran that command.  I feel like I just leveled up and found the root cause of the problem. 
So now, turn snapd on right? Yeah, let's go with that "systemctl enable snapd" ~ Will this work idk.....

`[orca@orcacomputers log]$ systemctl enable snapd
**Created symlink** from /etc/systemd/system/multi-user.target.wants/snapd.service to /usr/lib/systemd/system/snapd.service.
`  So yes your intuition produces results when professional judgement is used. 
See, it even created a syslink successfully! That is a good thing.  So know let's "systemctl status snapd" And we should be active and up and up out of this rabbit hole.  
Swing and a miss!
`[orca@orcacomputers log]$ systemctl status snapd
● snapd.service - Snap Daemon
   Loaded: loaded (/usr/lib/systemd/system/snapd.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
`So that was a bit of a surprise.  Now let's look at the instructions adferrand hooked us all up with.

So lets try this mofo, `sudo systemctl enable --now snapd.socket`.  Command went through snapd status inactive (dead)...
Continuing instructions with binary form.

Result:
`[orca@orcacomputers log]$  sudo ln -s /var/lib/snapd/snap /snap
[sudo] password for orca: 
ln: failed to create symbolic link ‘/snap/snap’: File exists
`And so this brings us full rabbithole circle to my [original post on snapd](https://forum.snapcraft.io/t/failed-to-create-symbolic-link-snap-snap-file-exists/18281) How's that for a symbolic link.  K I', going to go re-read the thread again. 

`[orca@orcacomputers log]$ snap list
Name               Version                     Rev   Tracking       Publisher     Notes
certbot            1.5.0                       345   latest/beta    rbasak        classic
`There is certbot classic like [willnilges was wondering](https://forum.snapcraft.io/t/failed-to-create-symbolic-link-snap-snap-file-exists/18281/2?u=powerhouse1).

**Comment by powerh0use** [comment]
`[Errno 13] Permission denied: '/var/log/letsencrypt/.certbot.lock'
`and says the next step 
`Either run as root, or set --config-dir, --work-dir, and --logs-dir to writeable paths.`
So maybe configure the root directory to snapd? Naw...Yeah I just don't know at this point.  

This is my bottleneck fellas, would be asking for help if I didn't need it, cheers go open source!

**Comment by ohemorange** [comment]
Places I can't reproduce this:
- apache and nginx on ubuntu20 with snaps from master
- apache and nginx on ubuntu18 with snaps from master
- apache on centos7 with snaps from master

Places I can reproduce this:
- nginx on centos7 with snaps from master

I actually suspect this is not a `PATH` issue, but a need-to-stage-something-else issue.

**Comment by alexzorin** [comment]
>apache on centos7 with snaps from master

Is there a doc for how to install the snap from master? I could help with a reproducer for this one.

**Comment by ohemorange** [comment]
@alexzorin yup, it's here! https://github.com/certbot/certbot/tree/master/snap/local/README.md
Feel free to ignore the additional DNS plugin instructions.

**Comment by ohemorange** [comment]
Based on [this](https://github.com/brave/brave-browser/issues/4280) thread, I suspect the missing package is one of [these](https://github.com/brave/unofficial-snap/blob/master/snap/snapcraft.yaml#L29-L43).

**Comment by ohemorange** [comment]
Oh hey, looks like someone may have solved this here: https://forum.snapcraft.io/t/glibc-mismatch/4059

**Comment by ohemorange** [comment]
Oh, I see what Brad is saying now -- that the local programs are trying to use our staged versions of libraries, rather than Certbot trying to run something and failing because it's finding the local library. That would certainly make life easier.

**Comment by alexzorin** [comment]
There's a somewhat straightforward, which is to run on CentOS 7:

    # yum -y install httpd php
    # snap install --classic --beta certbot
    # snap run --shell certbot
    ## apachectl -t 
    ## unset LD_LIBRARY_PATH
    ## apachectl -t

    [root@soprano-gorilla certbot]# apachectl -t
    httpd: Syntax error on line 56 of /etc/httpd/conf/httpd.conf: Syntax error on line 6 of /etc/httpd/conf.modules.d/10-php.conf: Cannot load modules/libphp5.so into server: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /snap/core18/current/usr/lib/x86_64-linux-gnu/libstdc++.so.6)
    [root@soprano-gorilla certbot]# unset LD_LIBRARY_PATH
    [root@soprano-gorilla certbot]# apachectl -t
    Syntax OK

I don't know whether it happens on master or not, though.

**Comment by ohemorange** [comment]
Nope, but it just doesn't print anything with or without it set, including "Syntax OK".

**Comment by ohemorange** [comment]
Aha! But `httpd --version` DOES trigger it.

**Comment by ohemorange** [comment]
Anyway, currently thinking of adding a `subprocess.Popen` wrapper to `plugins/common.py`.

**Comment by ohemorange** [comment]
I think we probably won't need to modify `PYTHONPATH`, since we put the user's `PYTHONPATH` before anything we add.

**Comment by ohemorange** [comment]
Well, I tried this approach for Nginx, on the `external_paths` branch. Results are the same as before, but I did just notice that Apache and Nginx are complaining about different versions of GLIBC, which is fun.

```
* apache
Description: Apache Web Server plugin
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache._internal.entrypoint:ENTRYPOINT
Initialized: <certbot_apache._internal.override_centos.CentOSConfigurator object
at 0x7f47c2e631f0>
Prep: Error while running apachectl configtest.

httpd: Syntax error on line 56 of /etc/httpd/conf/httpd.conf: Syntax error on
line 6 of /etc/httpd/conf.modules.d/10-php.conf: Cannot load modules/libphp5.so
into server: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by
/snap/certbot/x3/usr/lib/x86_64-linux-gnu/libxml2.so.2)

* nginx
Description: Nginx Web Server plugin
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: nginx = certbot_nginx._internal.configurator:NginxConfigurator
Initialized: <certbot_nginx._internal.configurator.NginxConfigurator object at
0x7f47c2e63b20>
Prep: Error while running nginx -c /etc/nginx/nginx.conf -t.

nginx: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by
/snap/certbot/x3/usr/lib/x86_64-linux-gnu/libstdc++.so.6)
```

**Comment by ohemorange** [comment]
Haha, that's because we call `certbot.util.run_script` in Nginx, so I didn't actually catch all the instances of `subprocess.Popen`.

**Comment by ohemorange** [comment]
Yay, this worked once I caught them all for nginx!

**Comment by bmw** [comment]
> I think we probably won't need to modify `PYTHONPATH`, since we put the user's `PYTHONPATH` before anything we add.

I still think we'll probably want to modify `PYTHONPATH`. I suspect most users won't have this value set but even they did, the addition of new packages in Python's search path could cause code with conditional dependencies to try and load code from the plugin snap which can easily break because the versions of the package, Python, or external libraries needed may be different.

I think things are especially problematic because of [how Python uses `PYTHONPATH`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH) where it is searched before any of the default search paths determined by the Python installation causing us to easily mask packages found on the host.

**Comment by keunes** [comment]
@bmw I think I'm running into this issue, too. I installed the certbot snap on Raspbian. `sudo certbot --nginx` returns `sudo: certbot: comma nd not found`. I have certbot version 1.7.0 installed now - is it possible that this doesn't include #8108 yet?

**Comment by bmw** [comment]
This is a different issue than the one fixed here. Run `hash -r` and try running the command again. Your problem is that your `PATH` environment variable hasn't been updated to include `/snap/bin`.

If you need additional help with this, I'd encourage you to make a post at https://community.letsencrypt.org where there is a much larger group of people familiar with the project who should be able to help you.
