### ISSUE TITLE
Create constraints file in the DNS plugins' snapcraft.yml

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8100]
This is https://github.com/certbot/certbot/issues/7957 for the DNS plugins. To copy much of the the text from that issue and update it:

Solving this issue isn't necessary right now (although it may be in the future to build the DNS plugin snaps with `snapcraft remote-build`), but it could make working on the snap a little easier and more pleasant and for that reason, I think it has significant value.

Currently one step in building our snap is creating a constraints file for `pip`. See step 4 [here](https://github.com/certbot/certbot/tree/035b6514db9c2aa76adaf5b2ab3c0ccdf7fc64f3/snap/local#build-the-snaps), although the steps taken here are currently incomplete as described by https://github.com/certbot/certbot/pull/8104. The need to do anything like this is a little awkward, especially when building the snap locally because it requires you to manually make persistent local changes to our repo to make the snap build work. Instead, why not just generate this file in `snapcraft.yml` as part of the build process?

We did this for the Certbot snap in https://github.com/certbot/certbot/pull/8097, but the reason this is hard to do in the DNS plugin snaps is because the necessary directories are not in the build context of the snap since they're outside of the directory of the DNS plugin.

Is there an easy way to work around this, ideally one that would still work with things like `snapcraft remote-build` where we have less control over the build context and scripts wrapping `snapcraft`?

The best idea I have right now would be to maintain a copy of this file in each DNS plugin, write a script to automatically update all copies of it, and have CI error if this script needs to be run. This is somewhat similar to the approach used for the `*-auto` scripts in the root of the repo. It's not pretty but it works. I'm certainly open to other ideas though.

**Comment by ohemorange** [comment]
> The best idea I have right now would be to maintain a copy of this file in each DNS plugin, write a script to automatically update all copies of it, and have CI error if this script needs to be run. This is somewhat similar to the approach used for the *-auto scripts in the root of the repo. It's not pretty but it works. I'm certainly open to other ideas though.

This is also similar to what we do to generate each plugin's `snapcraft.yaml` file, though that should theoretically be changing less often.

**Comment by bmw** [comment]
Since I created this issue and I'm personally satisfied with what we have now, I'm closing this. With https://github.com/certbot/certbot/pull/8404, we scripted away this step along with other commands we have to run first anyway such as generating the `snapcraft.yaml` file for the plugin for `snapcraft` to use.

If anyone disagrees, feel free to reopen this.
