### ISSUE TITLE
Each release breaks the previous version! 

### ISSUE THREAD

**Issue by timothymarois** [certbot/certbot#8107]
Why does every release have to break the previous working copy? 1.5 now make 1.4 completely useless. Is this really necessary? It prevents any new SSL renewals unless you upgrade, and when doing auto-upgrading, it fails, so you have to resort to other manual installs.

**Comment by alexzorin** [comment]
New releases shouldn't break anything.

If something is going wrong with upgrades on your system, please provide information about what's going wrong, including any error messages and everything else asked for in the issue template.

**Comment by timothymarois** [comment]
@alexzorin Yeah I get that its not suppose too, but its the 2nd time it happened in the last 6 months, the only way I found out was monitoring one of my domains went offline due to not having the SSL renewed. Cronjob for renewal failed because the update failed. Manually running the renewal tried to update certbot, but failed, had to run this (was the only way for it to successfully update).

`sudo /opt/eff.org/certbot/venv/local/bin/pip install cryptography interface zope` 

 I have a dozen more instances that probably need to be manually updated, I'll see if I can grab the errors from one of those.

**Comment by timothymarois** [comment]
And to be clear what I'm running on the cronjob for renewals (let me know if I should modify anything here to prevent breaking updates)

`0 8 * * * root /root/certbot-auto renew --debug --post-hook "sudo service httpd restart"` 

Is there a place where certbot stores error logs? I can grab that to show you which errors I received, maybe that will help figure out the root cause.

**Comment by alexzorin** [comment]
OK, so you are using `certbot-auto`. Every time there is a new Certbot release and `certbot-auto` runs, `/opt/eff.org/certbot/` gets removed and re-installed. That's how it performs upgrades.

From your post, I would guess that something is going wrong with the re-installation part. You shouldn't have to mess with `pip` inside the virtual environment.

If you delete that directory and run `certbot-auto`, does it succeed or do you encounter an error?

>Is there a place where certbot stores error logs?

Certbot stores its logs in `/var/log/letsencrypt/`. However, if it is the re-installation part which is failing, you probably won't find anything in there.

What is your Linux distribution and version?
