### ISSUE TITLE
Update minimum PyOpenSSL dependency

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8110]
We're currently maintaining compatibility with the versions of our dependencies found in LTS distros such as Debian 8, RHEL 7, and Ubuntu 16.04. To help us do this, we regularly run tests on Certbot with the oldest versions of our dependencies we must support to ensure everything still works.

We're having some trouble with `PyOpenSSL` though. We're currently supporting version 0.13.1 for compatibility on RHEL 7 based systems, but getting this to compile in CI has become more and more of a hassle. For example, see https://github.com/certbot/certbot/pull/8098#discussion_r444472106. In fact, it doesn't even compile on RHEL 7 systems without patches to the C code found in the PyOpenSSL RPM package.

To resolve this, I would like to bump our minimum required PyOpenSSL version to 0.15.1 which will resolve these compilation issues on some systems simplifying our testing. When doing this, we don't have any plans to make use of features at runtime that require 0.15.1 so things will probably still work with older versions once they're built, but since we won't be testing with those versions anymore, I do not think we should claim support for them on our end.

@FelixSchwarz, if we did this, how annoying would this be for you? I would imagine you all relaxing the PyOpenSSL dependency on your end and running tests like normal to ensure things still work if you wanted to update the packages while remaining on Python 2. I think this situation should be pretty temporary though because the only Python 3 PyOpenSSL package I could find in RHEL/EPEL 7 is `python36-pyOpenSSL` which is version 17.3.0, but if I'm wrong about that please correct me.

**Comment by FelixSchwarz** [comment]
I'll probably regret but I think you don't have to worry too much about EPEL 7 :-) Worst case we'll have to skip 1-2 releases in EPEL 7 until I got all the necessary Python 3 dependencies into EPEL 7 (just two new packages to submit if there are no additional dependencies hidden in augeas and python-configobj).

**Comment by bmw** [comment]
Thanks @FelixSchwarz. If it becomes a problem, let me know and I'll be happy to help.
