### ISSUE TITLE
Register snaps for DNS plugins and add Erica and myself as collaborators

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8112]
I think this should be blocked on https://github.com/certbot/certbot/issues/7935 to avoid having to transfer ownership of the snaps to the Certbot/EFF account which is a process that I believe requires manual action by the snap store team.

I think Erica and myself should be added as collaborators on each snap so we can manage the snaps from our personal accounts for convenience and to minimize the use of the shared credentials.

Some documentation about how to do this can be found at https://snapcraft.io/docs/store-brand-accounts.

**Comment by ohemorange** [comment]
This is done.
