### ISSUE TITLE
Command to automatically regenerate symlinks b/w live and archive folders

### ISSUE THREAD

**Issue by frnsys** [certbot/certbot#8130]
When migrating to a new server with several sites using certbot, I have to re-create all of the symlinks between the live and archive folders. Would it be possible to add a command, e.g. `certbot relink` or something, that does this automatically?

**Comment by alexzorin** [comment]
A simpler approach could be to document that symlinks must be preserved when archiving/copying, and examples of how to achieve that.

**Comment by schoen** [comment]
Hi @frnsys,

Could you let us know whether the existing `certbot update_symlinks` does what you want, or whether it's missing some functionality for your suggested use case?

**Comment by frnsys** [comment]
Thanks, this looks like it does it.
