### ISSUE TITLE
Certbot snap leaving beta checklist

### ISSUE THREAD

**Issue by mohamedhafez** [certbot/certbot#8138]
Hi, perhaps there could be a checklist issue for whats left for the certbot snap to leave beta and be fully supported? Personally I'm holding off on switching to certbot until that's been completed, perhaps others are as well, and it would be nice to know how close things are getting, or when an expected date is. Thanks and as always thanks for the work on this project! <3

**Comment by bmw** [comment]
Good idea @mohamedhafez, however, we're actually so close doing this that I don't think a checklist is needed. See https://github.com/certbot/certbot/issues/8140. Basically the only checklist item is not having any major bugs reported against Certbot or the Certbot snap in the next couple weeks.
