### ISSUE TITLE
Search location for cli.ini on Windows

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8144]
At the moment, Certbot for Windows only appears to look for `cli.ini` in `C:\Certbot\`. 

If the user wants a non-default install location, they can't readily achieve that without passing everything in on the command line every time, or creating`C:\Certbot` anyway just for the sake of `cli.ini`.

Is there an analogue to `$XDG_CONFIG_PATH` that could be added to Windows? Something like `%USERPROFILE%`? Or if there is another approach used on Windows, could we update the documentation with it?

There was this forum thread yesterday where the user ended up modifying the Certbot source code instead: https://community.letsencrypt.org/t/certbot-configuration/128189.

**Comment by schoen** [comment]
@adferrand, could you please take a look at this question?
