### ISSUE TITLE
Copy live cert to other folder by --manual-cleanup-hook, cert in tart folder can not be used!

### ISSUE THREAD

**Issue by ufgeorge** [certbot/certbot#8172]
My manual-cleanup-hook script as below:

`#!/bin/bash`
`rm -f /etc/nginx/html/.well-known/acme-challenge/$CERTBOT_TOKEN`
`rm -rf /data/ssl/$CERTBOT_DOMAIN`
`cp -R /etc/letsencrypt/live/$CERTBOT_DOMAIN /data/ssl`
`nginx -s reload
`
The source folder "live" is 0755 and cert in live folder are 0777.
But I found the cert in target forder /data/ssl/$CERTBOT_DOMAIN can not be used! (No such file)
I can only transfer cert to my computer then upload it.

Anybody can help? TKX very much!

**Comment by alexzorin** [comment]
You should use `--deploy-hook` for this.

    --deploy-hook DEPLOY_HOOK

      Command to be run in a shell once for each
      successfully issued certificate. For this command, the
      shell variable $RENEWED_LINEAGE will point to the
      config live subdirectory (for example,
      "/etc/letsencrypt/live/example.com") containing the
      new certificates and keys; the shell variable
      $RENEWED_DOMAINS will contain a space-delimited list
      of renewed certificate domains (for example,
      "example.com www.example.com" (default: None)

> But I found the cert in target forder /data/ssl/$CERTBOT_DOMAIN can not be used! (No such file)

The reason this happens is that the certificate and key files do not yet exist at the time that the cleanup hook runs. You will either copy nothing, or the previous (non-renewed) certificate. Neither of which you want.

Use `--deploy-hook` and I suspect it will solve your problems.
