### ISSUE TITLE
dns-digitalocean plugin: Attempting to renew causes dns_common to throw 'File not found' error for credential file that definitely exists

### ISSUE THREAD

**Issue by jgwheeler** [certbot/certbot#8175]
Using the dns-digitalocean plugin. Initial cert creation/installation worked OK, but autorenewal did not happen several months later. When a manual renewal was attempted, verbose logging showed that the certs were provisioning OK but the DNS-based challenge could not complete because the file containing the Digitalocean credentials could not be found. The file is in fact present on the filesystem in the exact referenced location.

## My operating system is (include version):
Ubuntu 18.04.4 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager w/ certbot ppa

## I ran this command (as root) and it produced this output:
`certbot renew`
...
```
2020-07-24 18:25:32,154:DEBUG:acme.client:Storing nonce: 0001aSkG_k8KAwFD7MjEhp-LDnnRN0p-Kl1p3uOcbOaHeCM
2020-07-24 18:25:32,154:INFO:certbot.auth_handler:Performing the following challenges:
2020-07-24 18:25:32,154:INFO:certbot.auth_handler:dns-01 challenge for [DOMAIN]
2020-07-24 18:25:32,154:INFO:certbot.auth_handler:dns-01 challenge for [DOMAIN]
2020-07-24 18:25:32,155:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 75, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 139, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 47, in perform
    self._setup_credentials()
  File "/usr/lib/python3/dist-packages/certbot_dns_digitalocean/dns_digitalocean.py", line 42, in _setup_credentials
    'token': 'API token for DigitalOcean account'
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 170, in _configure_credentials
    credentials_configuration = CredentialsConfiguration(self.conf(key), self.dest)
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 247, in __init__
    validate_file_permissions(filename)
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 312, in validate_file_permissions
    validate_file(filename)
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 303, in validate_file
    raise errors.PluginError('File not found: {0}'.format(filename))
certbot.errors.PluginError: File not found: ~/.secrets/digitalocean.ini

2020-07-24 18:25:32,156:DEBUG:certbot.error_handler:Calling registered functions
2020-07-24 18:25:32,157:INFO:certbot.auth_handler:Cleaning up challenges
2020-07-24 18:25:32,157:WARNING:certbot.renewal:Attempting to renew cert ([DOMAIN]) from /etc/letsencrypt/renewal/[DOMAIN].conf produced an unexpected error: File not found: ~/.secrets/digitalocean.ini. Skipping.
```

## Certbot's behavior differed from what I expected because:
The credentials file is in the referenced location and has correct permissions.

**Comment by jgwheeler** [comment]
Additional note: Manual renewal by passing credential file location via --dns-digitalocean-credentials command line param works fine.

**Comment by alexzorin** [comment]
Tilde (`~`) expansion is a functionality of your shell. Python doesn't know about it:

    >>> os.stat('~/')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    FileNotFoundError: [Errno 2] No such file or directory: '~/'

I wonder how the `~` version got into your renewal configuration file. Did you edit it manually? 

That's the only way I can imagine this could have happened. If you had done it in the below way, the shell would have expanded the tilde before executing Certbot, and your renewal configuraiton file would contain `/home/whatever/.secrets/digitalocean.ini`:

    --dns-digitalocean-credentials ~/.secrets/digitalocean.ini

**Comment by nightduck** [comment]
Semi-related digitlocean question: what if the file doesn't exist? Where's it supposed to be?

**Comment by alexzorin** [comment]
@nightduck the file is supposed to be created by the user, after obtaining their API key from Digital Ocean. Have a look at [the certbot-dns-digitalocean user guide](https://certbot-dns-digitalocean.readthedocs.io/en/stable/).

If you have questions about the Digital Ocean DNS plugin, I invite you to ask them on https://community.letsencrypt.org/.

I'm going to close this issue for now as the reporter did not respond for a few months and we did not get any other reports.

**Comment by esturniolo** [comment]
Hi guys.
Same problem here but with a simple docker run command:

```
docker run --rm -v /path/to/my/nginx/config/letsencrypt/etc/letsencrypt/:/etc/letsencrypt certbot/dns-digitalocean certonly --dns-digitalocean --dns-digitalocean-credentials /path/to/my/digitalocean.ini --register-unsafely-without-email --agree-tos -d example.com -d *.example.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-digitalocean, Installer None
Requesting a certificate for example.com and *.example.com
Performing the following challenges:
dns-01 challenge for example.com
dns-01 challenge for example.com
Cleaning up challenges
File not found: /path/to/my/digitalocean.ini
```

I tried to change the permissions, owner, move it to another path, etc...

**Comment by alexzorin** [comment]
Hi @esturniolo,

I don't see `/path/to/my/digitalocean.ini` being mounted anywhere in your Docker command.

If the file is on the host, then you need to add a `-v` for it as well.

**Comment by esturniolo** [comment]
Mhmhmh so I should share the ini with the guest?
Because the docs don’t mention it.

https://certbot-dns-digitalocean.readthedocs.io/en/stable/

So, in which directory should I mount the ini?

**Comment by alexzorin** [comment]
>Mhmhmh so I should share the ini with the guest?

Yes. Certbot runs inside the container and it needs to be able to read the credentials file in order to use the DigitalOcean API.

>Because the docs don’t mention it.

I guess that's true. Maybe we can add it somewhere on the main Docker instructions at https://certbot.eff.org/docs/install.html#running-with-docker.

>So, in which directory should I mount the ini?

Up to you. I think you should be able to keep the same path and just add a second volume mount for it:

    -v /path/to/my/digitalocean.ini:/path/to/my/digitalocean.ini

**Comment by esturniolo** [comment]
> I guess that's true. Maybe we can add it somewhere on the main Docker instructions
I’ll appreciate that. Thanks for this.
I’m glad to discover (?) this.

> Up to you.
Perfect!! I’ll try it. If you want I can keep you posted. Or if you prefer close the topic, it’s ok too.

--

**Comment by esturniolo** [comment]
`- Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/example.com/fullchain.pem`

Hooray!
I worked like a charm.

Thanks!
