### ISSUE TITLE
Can't install multiple snapped DNS plugins

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8181]
## My operating system is (include version):
Ubuntu Focal 20.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
snap

## I ran this command and it produced this output:
    $ sudo snap install --edge --classic certbot
    certbot (edge) 1.6.0-21-g086c8b1b3 from Certbot Project (certbot-eff✓) installed

    $ sudo snap set certbot trust-plugin-with-root=ok

    $ sudo snap install --edge certbot-dns-luadns
    certbot-dns-luadns (edge) 1.7.0.dev0 from Certbot Project (certbot-eff✓) installed

    $ sudo certbot plugins
    Saving debug log to /var/log/letsencrypt/letsencrypt.log

    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    * apache
    Description: Apache Web Server plugin
    Interfaces: IAuthenticator, IInstaller, IPlugin
    Entry point: apache = certbot_apache._internal.entrypoint:ENTRYPOINT

    * dns-luadns
    Description: Obtain certificates using a DNS TXT record (if you are using LuaDNS
    for DNS).
    Interfaces: IAuthenticator, IPlugin
    Entry point: dns-luadns = certbot_dns_luadns._internal.dns_luadns:Authenticator

    * nginx
    Description: Nginx Web Server plugin
    Interfaces: IAuthenticator, IInstaller, IPlugin
    Entry point: nginx = certbot_nginx._internal.configurator:NginxConfigurator

    * standalone
    Description: Spin up a temporary webserver
    Interfaces: IAuthenticator, IPlugin
    Entry point: standalone = certbot._internal.plugins.standalone:Authenticator

    * webroot
    Description: Place files in webroot directory
    Interfaces: IAuthenticator, IPlugin
    Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    $ sudo snap set certbot trust-plugin-with-root=ok

    $ sudo snap install --edge certbot-dns-digitalocean
    certbot-dns-digitalocean (edge) 1.7.0.dev0 from Certbot Project (certbot-eff✓) installed

    $ sudo certbot plugins
    Saving debug log to /var/log/letsencrypt/letsencrypt.log

    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    * apache
    Description: Apache Web Server plugin
    Interfaces: IAuthenticator, IInstaller, IPlugin
    Entry point: apache = certbot_apache._internal.entrypoint:ENTRYPOINT

    * dns-luadns
    Description: Obtain certificates using a DNS TXT record (if you are using LuaDNS
    for DNS).
    Interfaces: IAuthenticator, IPlugin
    Entry point: dns-luadns = certbot_dns_luadns._internal.dns_luadns:Authenticator

    * nginx
    Description: Nginx Web Server plugin
    Interfaces: IAuthenticator, IInstaller, IPlugin
    Entry point: nginx = certbot_nginx._internal.configurator:NginxConfigurator

    * standalone
    Description: Spin up a temporary webserver
    Interfaces: IAuthenticator, IPlugin
    Entry point: standalone = certbot._internal.plugins.standalone:Authenticator

    * webroot
    Description: Place files in webroot directory
    Interfaces: IAuthenticator, IPlugin
    Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

## Certbot's behavior differed from what I expected because:
The DigitalOcean plugin should show up, but doesn't.

From playing around, it seems that at-most one DNS plugin will show up, no matter what I try.

## Here is a Certbot log showing the issue (if available):

    2020-07-30 07:20:58,355:DEBUG:certbot._internal.main:certbot version: 1.7.0.dev0
    2020-07-30 07:20:58,356:DEBUG:certbot._internal.main:Arguments: []
    2020-07-30 07:20:58,356:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#dns-linode,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
    2020-07-30 07:20:58,369:DEBUG:certbot._internal.log:Root logging level set at 20
    2020-07-30 07:20:58,369:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
    2020-07-30 07:20:58,369:DEBUG:certbot._internal.main:Expected interfaces: None
    2020-07-30 07:20:58,370:DEBUG:certbot._internal.main:Filtered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#dns-linode,PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#webroot)

**Comment by bmw** [comment]
Thanks for reporting this Alex!

Each DNS plugin snap is supposed to connect to the Certbot snap in two ways. One allows Certbot to find the plugin while the other allows the plugin to make sure it is supported by the currently installed version of Certbot to provide some stability during upgrades.

During most of our initial testing, we had to manually create these connections (which you can read more about at https://github.com/certbot/certbot/tree/df1ca726f975b4f2cf96ada29785a4d35027e5f9/tools/snap#build-the-snaps if you're curious), but in https://github.com/certbot/certbot/issues/8142 I noted that it appears this happens automatically when installing our snaps from the snap store. It appears however, that the connection allowing Certbot to find the plugins is **not** made automatically for subsequent plugins.

```
$ sudo snap install --edge --classic certbot
certbot (edge) 1.6.0-21-g086c8b1b3 from Certbot Project (certbot-eff✓) installed
$ sudo snap set certbot trust-plugin-with-root=ok
$ sudo snap install --edge certbot-dns-luadns
certbot-dns-luadns (edge) 1.7.0.dev0 from Certbot Project (certbot-eff✓) installed
$ sudo snap set certbot trust-plugin-with-root=ok
$ sudo snap install --edge certbot-dns-digitalocean
certbot-dns-digitalocean (edge) 1.7.0.dev0 from Certbot Project (certbot-eff✓) installed
$ sudo snap connections
Interface            Plug                                       Slot                        Notes
content[metadata-1]  certbot-dns-digitalocean:certbot-metadata  certbot:certbot-metadata    -   
content[metadata-1]  certbot-dns-luadns:certbot-metadata        certbot:certbot-metadata    -   
content[certbot-1]   certbot:plugin                             certbot-dns-luadns:certbot  -
```
After running `sudo snap connect certbot:plugin certbot-dns-digitalocean`, the DO plugin shows up for me:
```
$ sudo /snap/bin/certbot plugins
Root logging level set at 10
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Expected interfaces: None
Filtered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#dns-digitalocean,PluginEntryPoint#dns-luadns,PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#webroot)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
* apache
Description: Apache Web Server plugin
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache._internal.entrypoint:ENTRYPOINT

* dns-digitalocean
Description: Obtain certs using a DNS TXT record (if you are using DigitalOcean
for DNS).
Interfaces: IAuthenticator, IPlugin
Entry point: dns-digitalocean =
certbot_dns_digitalocean._internal.dns_digitalocean:Authenticator

* dns-luadns
Description: Obtain certificates using a DNS TXT record (if you are using LuaDNS
for DNS).
Interfaces: IAuthenticator, IPlugin
Entry point: dns-luadns = certbot_dns_luadns._internal.dns_luadns:Authenticator

* nginx
Description: Nginx Web Server plugin
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: nginx = certbot_nginx._internal.configurator:NginxConfigurator

* standalone
Description: Spin up a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = certbot._internal.plugins.standalone:Authenticator

* webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```
To fix this, I think we should tell people to always run that connect command. If the plugin is already connected, it appears to be a noop. The command produces no output and exits with a zero exit code.

**Comment by bmw** [comment]
I think this will probably be fixed by the documentation created in https://github.com/certbot/website/pull/613.

**Comment by alexzorin** [comment]
Cool, that works, thanks.
