### ISSUE TITLE
Reword options-ssl-*.conf documentation to be more clear that modifications are permitted

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8205]
# This file contains important security parameters. If you modify this file
    # manually, Certbot will be unable to automatically provide future security
    # updates. Instead, Certbot will print and log an error message with a path to
    # the up-to-date file that you will need to refer to when manually updating
    # this file.

[On the forum](https://community.letsencrypt.org/t/editing-etc-letsencrypt-options-ssl-nginx-conf/130982?u=_az), I see users often interpreting this to say: "don't modify the file, you have been warned". 

>If you modify this file manually, Certbot will be unable to automatically provide future security updates.

There should be a way to improve the above phrase to more explicitly offer the choice of managing the file yourself, or allowing Certbot to keep maintaining it. 

----

Additionally, as raised in that thread, the same clarification could be made to `-ssl.conf` Apache & nginx vhosts generated by Certbot.

**Comment by evittech** [comment]
Agreed.

**Comment by rmendal** [comment]
How does this sound @alexzorin  & @evittech?

```
# This file contains important security parameters. You may modify this file
# manually. If you do so, Certbot will be unable to automatically provide
# future security updates as the file hash will no longer match the default.
# Instead, Certbot will print and log an error message with a path to
# the up-to-date file that you will need to refer to when manually updating
# this file.
```

**Comment by evittech** [comment]
@alexzorin I agree with where you are going on this. IMHO opinion, it still is unclear what will not work if you manually edit these files. A detailed explanation should be in the documentation. Additionally, for example, the same wording exists in the Apache and Nginx config files. Users need to edit those to turn off and on features all the time. Clarification and further documentation would help.
