### ISSUE TITLE
Hooks on Windows unable to locate executables in PATH if `.exe` omitted

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8215]
First reported at https://community.letsencrypt.org/t/dry-run-failing/131124/9?u=_az

## My operating system is (include version):
Windows 7, Windows Server 2019

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Windows installer.

## I ran this command and it produced this output:

![screenshot](https://tools.letsdebug.net/Screenshot_2020-08-15_08-29-46.png)

## Certbot's behavior differed from what I expected because:
`net.exe` is in the PATH. 

Omitting `.exe` (or other extensions) is a valid way to invoke the executable on Windows. 

Certbot should mimic or somehow reuse the behavior of Windows: https://docs.microsoft.com/en-us/previous-versions//cc723564(v=technet.10)#command-search-sequence

If this is not possible, we should at least update the https://certbot.eff.org/lets-encrypt/windows-apache instructions so that it includes the `.exe`.

**Comment by ddelcastilloRSMG** [comment]
Still having this issue with version 2.6.0

**Comment by ohemorange** [comment]
Instructions on the live site are now updated, but presumably we still want to fix the underlying issue?

**Comment by ohemorange** [comment]
Live here: https://certbot.eff.org/instructions?ws=other&os=windows

![Screenshot from 2023-05-18 16-21-08](https://github.com/certbot/certbot/assets/1227205/47c3b79e-ec2b-483c-ac0d-33ad0f46bf66)
