### ISSUE TITLE
Don't list wildcard domains as authenticatable

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#822]
Steps to reproduce:

In /etc/apache/sites-available/SITE, have the line:

`ServerAlias *.example.com`

Run `letsencrypt`.

Actual result:

At the "Which names would you like to activate HTTPS for?" menu, *.example.com is listed. However, if you select it, you get the error:

`Error: unauthorized :: The client lacks sufficient authorization :: Error creating new authz :: Syntax error`

Expected result:

Wildcard names should not be listed. Possibly the app should acknowledge that they exist but make them unselectable, with help text explaining that LE doesn't support wildcards.

**Comment by kuba** [comment]
Related: #830.

**Comment by kuba** [comment]
More generic approach + compliant with spec #965.

**Comment by SwartzCr** [comment]
But we will soon support wildcards! So what does that mean for this issue?

**Comment by jsha** [comment]
We can close it.
