### ISSUE TITLE
Stop running the test_tests.sh test farm test (after certbot-auto is EOL'd)

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8221]
As documented at [the top of the script](https://github.com/certbot/certbot/blob/acb6d34c5f2658653687fade6a6f5b81a0ca0caf/tests/letstest/scripts/test_tests.sh#L3-L5), we run `test_tests.sh` as part of the release process to test that the wheels for the release were built correctly. This is just to make sure that any conditional dependencies specified in `setup.py` are properly captured in the wheel. I don't think we should do this anymore.

While it's true there could be problems in our wheel that aren't caught by our other tests, I think it's quite unlikely we'll have any problems as I think we know how to do this now, rarely add conditional dependencies, and have multiple examples of it in our `setup.py` files.

More importantly, I think there is almost no downside of a problem existing here. Our wheels are only used by people installing directly from `pip`. [Our](https://salsa.debian.org/letsencrypt-team/certbot/certbot/-/blob/master/debian/watch) [packagers](https://src.fedoraproject.org/rpms/certbot/blob/master/f/sources) don't use them and instead use the tarballs we upload to PyPI. Our distribution methods like Docker, snaps, and Windows use our source files directly instead of the built packages. The only fully supported installation method that uses are wheels is certbot-auto where we have multiple other test farm tests being run.

It probably doesn't hurt to continue to run the tests until certbot-auto dies (although I'm personally also fine not doing that), but I don't think we should do it any longer than that. I don't think there's much benefit and after certbot-auto dies, this will be the only test that we run at the end of the release process and the only test that necessitates the server discussed at https://github.com/certbot/certbot/issues/8151.

My thinking is if we're OK with removing test_test.sh either now or in the near future, we don't have to resolve https://github.com/certbot/certbot/issues/8151. Once certbot-auto is deprecated on Debian/Ubuntu, that server will continue to use the last version of certbot-auto that works on the system (which is kind of a nice test of the deprecation mechanism anyway) for what should only be a couple months and then we can just shut the server down entirely and remove the step of manually running test farm tests from the release process.

Any concerns with this plan?

**Comment by bmw** [comment]
@adferrand and/or @ohemorange, do you have any concerns with this plan?

**Comment by adferrand** [comment]
I largely agree with this plan, since it covers a situation that is not officially supported (pip installation), and certbot-auto good behavior (which implies a correct installation of wheels) is already tested. Given that it adds a significant complexity to run that test, I am even in favor of removing it now.

**Comment by ohemorange** [comment]
> Our wheels are only used by people installing directly from pip

My one concern is that we had discussed having people install through `pip` as our preferred alternative to `certbot-auto`. If we go with that plan instead of having people build from source as our officially recommended alternative, we'll probably want to keep `test_tests` around.

**Comment by adferrand** [comment]
I suppose here that you are talking to the alternative that will be ultimately proposed to people running on non Windows OSes where snap is not available? Is there some design document or discussion stream somewhere about this by the way?

Given that context, still, the current form of this test could largely be simplified in my opinion. First, I guess that the AMIs on which this farm test is run are OSes where snap is available. So it is testing on environments where pip would not be the recommended method.

Maybe this test could be transformed into something that is not required to be run after the release, and with a farm test approach: for instance, building the wheel locally (I mean on the CI VM), install it with several significant pip versions, and assert certbot is running, would be a decent replacement.

**Comment by ohemorange** [comment]
> I suppose here that you are talking to the alternative that will be ultimately proposed to people running on non Windows OSes where snap is not available? Is there some design document or discussion stream somewhere about this by the way?

Yes. Hm, I don't remember where we discussing that, maybe brad does?

> Given that context, still, the current form of this test could largely be simplified in my opinion. First, I guess that the AMIs on which this farm test is run are OSes where snap is available. So it is testing on environments where pip would not be the recommended method.

Good point, we should use the test only for the actual systems it will be run on.

**Comment by bmw** [comment]
> If we go with that plan instead of having people build from source as our officially recommended alternative, we'll probably want to keep test_tests around.

I disagree. I just don't think the effort involved in maintaining & migrating a server and continuing to manually run test farm tests as part of the release process justifies the additional check we get here. From before we had this test, I could only find [one user report about problems like this](https://github.com/certbot/certbot/issues/2178) and we [left it unfixed for over a year](https://github.com/certbot/certbot/pull/4313) without complaint. [Most major Python projects also have wheels](https://pythonwheels.com/), yet I've never seen any that have a test like this.

> > Given that context, still, the current form of this test could largely be simplified in my opinion. First, I guess that the AMIs on which this farm test is run are OSes where snap is available. So it is testing on environments where pip would not be the recommended method.
> 
> Good point, we should use the test only for the actual systems it will be run on.

If we limit the test to OSes where snaps are not an option, I think we have to get pretty obscure which makes the tests even more questionable in my opinion. Non-Windows users who can't use snaps are people on obscure architectures or OSes like Gentoo, Devuan, BSD, or macOS.

I also think the tests the Adrien's describes have somewhat reduced value in that the environment that builds the wheel during testing is not the same environment that builds the released wheel. The general problem being tested for here is that if conditional dependencies are specified incorrectly in `setup.py`, the wheel will contain the dependencies from the outcome of the condition on the system that built the wheel rather than the logic for the condition itself. The conditionals can have different results in CI than what they have locally based on things like the version of Python being used.

What I think we should do is stop running `test_tests.sh` now, but create an issue for building our PyPI packages in CI in the future and maybe also adding back tests like this. Doing that not only simplifies the release process, but it removes the differences between the build environment for testing and production. We could also add a reminder somewhere in documentation to check for this problem manually when adding conditional dependencies, but I honestly think that has limited value.

What do you think @ohemorange? Do you still want to push for running this test?

> I suppose here that you are talking to the alternative that will be ultimately proposed to people running on non Windows OSes where snap is not available? Is there some design document or discussion stream somewhere about this by the way?

I haven't fleshed out all the details or written this all up in one place anywhere yet, but I've briefly mentioned the idea in threads like https://github.com/certbot/certbot/issues/7747 and https://github.com/certbot/website/issues/619.

**Comment by ohemorange** [comment]
> What I think we should do is stop running test_tests.sh now, but create an issue for building our PyPI packages in CI in the future and maybe also adding back tests like this. Doing that not only simplifies the release process, but it removes the differences between the build environment for testing and production.

I really like that solution, especially since as you say, we haven't run into issues with this in practice. I also think that given that people have the option to install from source, there's not too much risk here overall. I'm now on team remove-the-tests.

**Comment by bmw** [comment]
Great!

I did the following:

* Removed `test_tests.sh` from our release instructions
* Created https://github.com/certbot/certbot/issues/8227 to track automating our package builds in CI.
* Closed https://github.com/certbot/certbot/issues/8151 with the plan to let certbot-auto maintain that server until we shut it down.
* Created https://github.com/certbot/certbot/issues/8228 to track shutting down the server.


I left `test_test.sh` thinking it may be useful for manual testing, but if someone would prefer to remove it, submit a PR and I'll approve it.
