### ISSUE TITLE
Change how ctypes.util.find_library finds libraries

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8229]
As described briefly at https://forum.snapcraft.io/t/issue-when-snap-uses-pythons-ctype-util-find-library/9690, when the Python standard library function `ctypes.util.find_library` is run inside of a classic snap, it will first search for libraries on the host system rather than limiting itself to or prioritizing libraries included in the snap. I am aware of no way to change this behavior without modifying the the Python standard library.

The reason this happens is the first thing this function tries to do is call `/sbin/ldconfig -p`. See https://github.com/python/cpython/blob/v3.8.5/Lib/ctypes/util.py#L276. This path is hard coded and will refer to the executable on the host system when it is run inside of a classic snap. As a result, if the library being searched for is installed on the host, `find_library` will find it and not any libraries it may otherwise fallback to that are included in the snap. This is a problem for consistency and reliability of classic snaps.

I think we should work with the Python core developers to fix this. It would be nice if `ctypes.util.find_library` would restrict itself to or prioritize searching for libraries found at a path set by an environment variable like `LD_LIBRARY_PATH`. This would allow developers of classic snaps (and maybe other packaging methods such as standalone Python executables built by tools like Pyinstaller, flatpaks, appimages, etc.) to ensure that any dependencies can properly load the libraries they need without patches like we've been doing for Augeas in the Certbot snap.

**Comment by bmw** [comment]
@alex, @reaperhulk: Since you know this space much better than I do, I would love to hear any thoughts you have about this if you find the time.

To provide additional context about snaps in case it's useful, all of the snap's files, including the Python installation, are under a path like `/snap/certbot/x1/` and we would like Python to prioritize or restrict itself to searching for libraries under that path.

**Comment by alex** [comment]
It does seem like `LD_LIBRARY_PATH` should be preferred when searching for where to load a library from. What, in certbot, is actually using `ctypes` though?

**Comment by bmw** [comment]
We're not using `ctypes` ourselves, but we currently depend on `python-augeas` for parsing Apache config files which depending on the version uses `ctypes` or `cffi` to load an Augeas shared object and `cffi` calls `ctypes.util.find_library` internally.

**Comment by alex** [comment]
It's worth noting that `LD_LIBRARY_PATH` _is_ checked, it's just not given priority: https://github.com/python/cpython/blob/v3.8.5/Lib/ctypes/util.py#L309-L312

**Comment by bmw** [comment]
Thanks a lot for taking a look at this!

I'll do some more digging into the history to verify, but the note at https://docs.python.org/3/library/ctypes.html#finding-shared-libraries says:

> Changed in version 3.6: On Linux, the value of the environment variable LD_LIBRARY_PATH is used when searching for libraries, if a library cannot be found by any other means.

I wonder if it was a design decision to only use `LD_LIBRARY_PATH` as a fallback for backwards compatibility.

Regardless, I'd like to see this changed and I'll start a conversation with the Python core devs.
