### ISSUE TITLE
certbot-dns-cloudflare snap can't be found by certbot snap

### ISSUE THREAD

**Issue by asantoni** [certbot/certbot#8235]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):

Ubuntu 19.10

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

snapd

## I ran this command and it produced this output:

```sudo snap install --classic certbot
snap install --edge certbot-dns-cloudflare
snap set certbot trust-plugin-with-root=ok
```

```
root@x:/snap/certbot-dns-cloudflare/current# certbot plugins
*** stack smashing detected ***: <unknown> terminated
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
* apache
Description: Apache Web Server plugin
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache._internal.entrypoint:ENTRYPOINT

* nginx
Description: Nginx Web Server plugin
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: nginx = certbot_nginx._internal.configurator:NginxConfigurator

* standalone
Description: Spin up a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = certbot._internal.plugins.standalone:Authenticator

* webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

```

I also tried running `sudo snap connect certbot:plugin certbot-dns-cloudflare` and it made no difference.

## Certbot's behavior differed from what I expected because:

The Cloudflare DNS plugin just can't be found by the main snap for some reason. 

`/snap` contains `certbot` and `certbot-dns-cloudflare`, so it looks installed.

**Comment by bmw** [comment]
Does
```
*** stack smashing detected ***: <unknown> terminated
```
always show up in your `certbot plugins` output?

Does the output change if you run `sudo /snap/bin/certbot plugins`?

What is the output of `sudo snap list` and `sudo snap connections`?

**Comment by alexzorin** [comment]
snap version

may be useful too.
