### ISSUE TITLE
Cant run certbot

### ISSUE THREAD

**Issue by KatzeMau** [certbot/certbot#8240]
Hi, i had a cert for ibiza.thecatcloud.de, but now i want one for spain.thecatcloud.de
And it does not work
Raspian Newest

Certbot / apt-get

## I ran this command and it produced this output:
Certbot

root@raspberrypi:~# certbot
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Error while running apache2ctl configtest.
Action 'configtest' failed.
The Apache error log may have more information.

AH00526: Syntax error on line 34 of /etc/apache2/sites-enabled/000-default-le-ssl.conf:
SSLCertificateFile: file '/etc/letsencrypt/live/ibiza.thecatcloud.de-0001/fullchain.pem' does not exist or is empty

Certbot doesn't know how to automatically configure the web server on this system. However, it can still get a certificate for you. Please run "certbot certonly" to do so. You'll need to manually configure your web server to use the resulting certificate.
root@raspberrypi:~#

**Comment by osirisinferi** [comment]
Your Apache configuration seems to be broken. You probably won't even be able to (re)start it in its current configuration. Looks like you've deleted a certificate in certbot without changing or removing the Apache configuration which was created during the initial certificate creation/installation.

**Comment by ohemorange** [comment]
+1 on what @osirisinferi said, thanks!
