### ISSUE TITLE
Add a --preconfigured-renewal flag

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8241]
We should create a `--preconfigured-renewal` flag that we can set in environments where Certbot should have automated renewal preconfigured. Feel free to change the exact name of the flag. It's just the first thing that came to my mind.

The idea here is we can then modify Certbot's output about renewal based on this flag. This flag should have `help=argparse.SUPPRESS` set because it's not something that users should mess with.

Things that should be done here as part of this:

- [ ] Set this flag in `certbot.wrapper` for snaps.
- [ ] Document this flag in https://github.com/certbot/certbot/blob/master/certbot/docs/packaging.rst.
- [ ] Ping Certbot's Debian packager about this telling them the syntax for them to use to set the flag in `/etc/letsencrypt/cli.ini` and in what release it will be added.

I think actually changing Certbot's output based on this flag can come later.

**Comment by adferrand** [comment]
I would like to challenge the need of a flag for that. One may consider that flags on CLI or for users, not packagers who need to change some internal logic to the program. In that extent, something less committing like an environment variable could be sufficient for that purpose?

**Comment by bmw** [comment]
I discussed this with Harlan in our public Mattermost channel and he said a flag would be easier to implement such that it would be set for all invocations of Certbot so I think a hidden CLI flag is the best way to go here.

**Comment by ohemorange** [comment]
We will probably want to remind our debian packager about this after our next release.
