### ISSUE TITLE
Apache plugin does not parse variables correctly

### ISSUE THREAD

**Issue by johnfawcett** [certbot/certbot#8243]
My apache webserver site templates make use of a variable to avoid errors where other values depend on the server name.

Define servername example.org
ServerName ${servername}
DocumentRoot /var/www/vhosts/${servername}
ErrorLog /var/log/httpd/${servername}.error.log
CustomLog /var/log/httpd/${servername}.access.log combined

However the apache authenticator and installer does not pick up on the sites configured this way.
The authenticator does not list the configured sites. The installer installs to the wrong configuration files.

## My operating system is (include version):
Centos 8.2

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
package from epel

**Comment by alexzorin** [comment]
Thanks for your report.

I think this is the same problem as #7447, so I'm going to close this in favor of the existing issue.

Certbot currently records defined variables only after evaluating the entire configuration. Defined variables are actually [in the global scope:](https://httpd.apache.org/docs/2.4/mod/core.html#define)

>**Virtual Host scope and pitfalls**
>While this directive is supported in virtual host context, the changes it makes are visible to any later configuration directives, beyond any enclosing virtual host.

As a result, Certbot ends up substituting the wrong value for `servername` and misinterpreting your configuration. 

For now, the Apache plugin won't work with this type of configuration, but you can still use `certonly` and `--webroot`.
