### ISSUE TITLE
Audit Apache/webroot plugin output

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8253]
Like was done for the nginx plugin (and standalone plugin according to the open questions section) in https://docs.google.com/document/d/1aKnQYEzCrZgYX-iuE-ErOdIKERUuLmZSX_BDb7d0M6I/edit?usp=sharing, I think we should audit Certbot's output when the Apache or webroot plugin are used and suggest improvements that can be made. We can just focus on the Apache and webroot specific output since Certbot's common output was looked at in the design doc.

**Comment by bmw** [comment]
With https://docs.google.com/document/d/1RcBPHGkFiY4vospMVwlAG1mRqetWNIi-9Ei2ArCywfk/edit?usp=sharing, is this done?

**Comment by ohemorange** [comment]
This issue is probably done, but let's make an issue for implementing those changes.

**Comment by ohemorange** [comment]
Closed by #8852.
