### ISSUE TITLE
certbot edits wrong vhost and breaks server

### ISSUE THREAD

**Issue by dotysan** [certbot/certbot#8258]
## My operating system is (include version):
Fedora 32

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
`dnf install certbot python3-certbot-nginx`
`certbot --nginx`

## I ran this command and it produced this output:
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator nginx, Installer nginx

Which names would you like to activate HTTPS for?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: intortus.greenkey.net
2: foo
3: bar
4: baz
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate numbers separated by commas and/or spaces, or leave input
blank to select all options shown (Enter 'c' to cancel): 1
Cert not yet due for renewal

You have an existing certificate that has exactly the same domains or certificate name you requested and isn't close to expiry.
(ref: /etc/letsencrypt/renewal/intortus.greenkey.net.conf)

What would you like to do?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: Attempt to reinstall this existing certificate
2: Renew & replace the cert (may be subject to CA rate limits)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 1
Keeping the existing certificate
Deploying Certificate to VirtualHost /etc/nginx/conf.d/0go-away.conf
nginx: [warn] conflicting server name "intortus.greenkey.net" on 0.0.0.0:80, ignored
nginx: [warn] conflicting server name "intortus.greenkey.net" on [::]:80, ignored
Redirecting all traffic on port 80 to ssl in /etc/nginx/conf.d/0go-away.conf
nginx: [warn] conflicting server name "intortus.greenkey.net" on 0.0.0.0:80, ignored
nginx: [warn] conflicting server name "intortus.greenkey.net" on [::]:80, ignored

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Congratulations! You have successfully enabled https://intortus.greenkey.net
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/intortus.greenkey.net/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/intortus.greenkey.net/privkey.pem
   Your cert will expire on 2020-12-02. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot again
   with the "certonly" option. To non-interactively renew *all* of
   your certificates, run "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le
 ```

## Certbot's behavior differed from what I expected because:
The nginx server{} block matching the certificate hostname "intortus.GreenKey.net" wasn't edited. Instead a duplicate server{} block was created and settings borrowed from a different poison server{} block!

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
```
2020-09-03 23:59:57,041:DEBUG:certbot.crypto_util:Generating key (1024 bits): /var/lib/letsencrypt/snakeoil/0000_key.pem
2020-09-03 23:59:57,058:INFO:certbot_nginx._internal.configurator:Deploying Certificate to VirtualHost /etc/nginx/conf.d/0go-away.conf
2020-09-03 23:59:57,058:DEBUG:certbot.reverter:Creating backup of /etc/nginx/conf.d/stub-redirects.conf
2020-09-03 23:59:57,058:DEBUG:certbot.reverter:Creating backup of /etc/nginx/nginx.conf
2020-09-03 23:59:57,058:DEBUG:certbot.reverter:Creating backup of /etc/nginx/mime.types
2020-09-03 23:59:57,059:DEBUG:certbot.reverter:Creating backup of /etc/nginx/conf.d/0go-away.conf
2020-09-03 23:59:57,059:DEBUG:certbot.reverter:Creating backup of /etc/nginx/conf.d/foo.conf
2020-09-03 23:59:57,059:DEBUG:certbot.reverter:Creating backup of /etc/nginx/conf.d/bar.conf
2020-09-03 23:59:57,059:DEBUG:certbot.reverter:Creating backup of /etc/nginx/conf.d/baz.conf
2020-09-03 23:59:57,059:DEBUG:certbot.reverter:Creating backup of /etc/nginx/default.d/doc.conf
2020-09-03 23:59:57,061:DEBUG:certbot_nginx._internal.parser:Writing nginx conf tree to /etc/nginx/conf.d/0go-away.conf:
```
## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
/etc/nginx/nginx.conf:
```
http {
    include /etc/nginx/conf.d/*.conf;

    server {
        listen       80;
        listen       [::]:80;
        server_name intortus.GreenKey.net;
#...
    }
```
/etc/nginx/conf.d/0go-away.conf:
```
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name  _;
    return 444;
}
```

Instead of editing proper vhost inside nginx.conf it edits conf.d/0go-away.conf and injects the poisonous directives from the *wrong* vhost:
```
2020-09-03 23:59:58,169:DEBUG:certbot_nginx._internal.parser:Writing nginx conf tree to /etc/nginx/conf.d/0go-away.conf:
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name  _;
    return 444;
}
server {
    server_name intortus.greenkey.net; # managed by Certbot
    return 444;

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/intortus.greenkey.net/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/intortus.greenkey.net/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}server {
    if ($host = intortus.greenkey.net) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80 ;
    listen [::]:80 ;
    server_name intortus.greenkey.net;
    return 404; # managed by Certbot

}
```

The above edit completely kills nginx for the host in question, `intortus.GreenKey.net`.

I've since fixed...by manually moving the wrongheaded certbot edits to conf.d/0go-away.conf into the *proper* server{} block in nginx.conf.

A quick glance at the code makes me think that choose_vhosts() inside certbot_nginx/_internal/configurator.py is making some grave assumptions.

Can we improve choose_vhosts() to better select which nginx config file to edit?

**Comment by alexzorin** [comment]
@dotysan could you please take a look at #6776 and see whether that sounds like the same problem you are experiencing?

**Comment by dotysan** [comment]
@alexzorin yes, studly caps breaks certbot in choose_vhosts().

**Comment by dotysan** [comment]
Bug is here. https://github.com/certbot/certbot/blob/master/certbot-nginx/certbot_nginx/_internal/configurator.py#L400

In _get_default_vhost() It does not even attempt to match the vhost domain name. But instead arbitrarily matches on default_server. Which is bogus!

**Comment by alexzorin** [comment]
Hi @dotysan,

If #6776 fully explains your issue (thanks for investigating and confirming), I think we should consolidate the discussion there. Leaving a :+1: on that issue would help bump its priority as well.

I think the bug is probably [somewhere like here](https://github.com/certbot/certbot/blob/3ce87d1fcb1a11b554c9e22727d602cb86f0b8bf/certbot-nginx/certbot_nginx/_internal/parser.py#L498). I think the basic idea for a fix could start with something like:

```diff
diff --git a/certbot-nginx/certbot_nginx/_internal/parser.py b/certbot-nginx/certbot_nginx/_internal/parser.py
index bb0bb7d6f..9a7c0d3e7 100644
--- a/certbot-nginx/certbot_nginx/_internal/parser.py
+++ b/certbot-nginx/certbot_nginx/_internal/parser.py
@@ -496,8 +496,7 @@ def get_best_match(target_name, names):


 def _exact_match(target_name, name):
-    return name in (target_name, '.' + target_name)
-
+    return name.lower() in (target_name.lower(), '.' + target_name.lower())
```

but there's certainly other places where similar changes should be made and thoroughly tested.

I'm going to close this as a duplicate, but please continue in #6776.

**Comment by dotysan** [comment]
Actually _get_default_vhost() does not honor it's own parameter, domain. So I suspect this is a logic error, not a case-sensitivity issue.

**Comment by alexzorin** [comment]
To the best of my understanding, `_get_default_vhost` [is only used](https://github.com/certbot/certbot/blob/3ce87d1fcb1a11b554c9e22727d602cb86f0b8bf/certbot-nginx/certbot_nginx/_internal/configurator.py#L327-L345) when Certbot has already exhausted a search for a virtualhost matching `intortus.GreenKey.net`.

If Certbot can't find a matching virtualhost using `_choose_vhost_single`/`_choose_vhosts_wildcard`, it then tries to find the default virtualhost in the nginx configuration, so it can clone it and use it to authenticate your domain.

I think the fact that `_get_default_vhost` accepts the domain as an argument is misleading. 

I'm still satisfied that #6776 is what you're experiencing.
