### ISSUE TITLE
Switching the certificate to another domain

### ISSUE THREAD

**Issue by LukaMarcel** [certbot/certbot#8261]
Hello!
I currently have to domains running to a hostsystem.
Certbot runs on one domain but I want to swith the certificate, but the bot only recognizes one domain:

![image](https://user-images.githubusercontent.com/6438316/92285054-a88d6300-ef03-11ea-9d83-2f4f916a0d93.png)

How can I "add" the other domain so I can switch the certificate?

Thanks for your help!

**Comment by adferrand** [comment]
Hello!

I think what you could use is: https://certbot.eff.org/docs/using.html#changing-a-certificate-s-domains. Keep in mind that in this case, the actual name of the certificate (so it's location under /etc/letsencrypt/live) will not change, but it will support more than the one domain it has been created for.

However if you are talking about the fact that Certbot is unable to detect the other domain that your HTTP server is serving, then it largely depends on the actual HTTP server and your specific configuration. In this case I invite you to ask for support on the Let'sEncrypt community forum (https://community.letsencrypt.org/) where you will get the appropriate help.
