### ISSUE TITLE
Store DNS plugins arguments values in renewal config file

### ISSUE THREAD

**Issue by DgINC** [certbot/certbot#8265]
Hi guys! I wrote a DNS plugin for Yandex, but I am confused by credentials.
I would like to specify it once, for example _--dns-yandex-auth-token "blablabla"_ 
and this parameter would be saved in _../renewal/domainname.com.conf_
For later use _certbot renew_ without any parameters.
<pre>
<b> Example config for Yandex DNS </b>

# renew_before_expiry = 30 days
version = 1.7.0
archive_dir = /etc/letsencrypt/archive/domainname.com
cert = /etc/letsencrypt/live/domainname.com/cert.pem
privkey = /etc/letsencrypt/live/domainname.com/privkey.pem
chain = /etc/letsencrypt/live/domainname.com/chain.pem
fullchain = /etc/letsencrypt/live/domainname.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 0123456789abcdefghijklmnopqrstuvwxyz
authenticator = dns-yandex
server = https://acme-v02.api.letsencrypt.org/directory
rsa_key_size = 4096
manual_public_ip_logging_ok = True

<b>#Custom field for dns auth plugin
[authenticator]
auth_token = blablabla</b>
</pre>

Having rummaged in the source code, I understand that this functionality is not provided.
If I'm wrong, stick my nose where to dig.
And if the truth is not like that, let's write this shit.

**Comment by alexzorin** [comment]
`/etc/letsencrypt/renewal/*.conf` is world readable. Therefore, the idiom with plugins is to keep the API credentials in a separate file.

You can see in your plugin that it declares a `credentials` argument:

https://github.com/DgINC/certbot/blob/ce408c89be93f3ef603c39467cf10191f4bcca0c/certbot-dns-yandex/certbot_dns_yandex/_internal/dns_yandex.py#L32-L35

You can then proceed to use it:

    --dns-yandex --dns-yandex-credentials /path/to/yandex.ini

The path to the credentials file will be persisted in the `/etc/letsencrypt/renewal/*.conf` file, to be reused at renewal.

**Comment by DgINC** [comment]
`/etc/letsencrypt/renewal/*.conf is world readable.` - this is wrong for *nix(with the exception of win). We can set 640 on this files and store everything we need here. (also. I have no idea what to do with win platform, but doesn't matter in this time) 
These files are needed only by certbot, and therefore it makes no sense to let everyone read them.

Why i think, `/path/to/yandex.ini` is bad idea. Because it is another pseudo-secure vault which the user should take care of.
And if he does not do that, or force majeure occurs, then forgive the domain and / or access to the account.
I hope I have explained clearly.

**Comment by alexzorin** [comment]
I am not going to agree or disagree with you about what the permissions should be, or the merits of separate credential files. That can be a matter for separate issue, if you want to raise it. 

I only wanted to answer your question and explain how all of the existing DNS plugins (including third-party ones) work right now.

If you wish, can directly create an `auth-token` parameter under `add_parser_arguments` and it will do what you are asking - you can pass `--dns-yandex-auth-token` and it will be persisted directly in the renewal parameters file. But it would not be safe, given the current permissions model used by Certbot.

**Comment by DgINC** [comment]
I understand it. In general, I need to hear the opinion of the main development team. Since I was planning to push the changes to the main branch.

**Comment by alexzorin** [comment]
No problem. [Keep in mind](https://certbot.eff.org/docs/contributing.html#dev-plugin):

>The Certbot team is not currently accepting any new DNS plugins because we want to rethink our approach to the challenge and resolve some issues like #6464, #6503, and #6504 first.
>
>In the meantime, you’re welcome to release it as a third-party plugin. See certbot-dns-ispconfig for one example of that.

**Comment by DgINC** [comment]
Then do not close the topic and wait for responses from contributors about storing additional data in the renewal configuration files.
<details>
  <summary>About third-party plugin off-top</summary>
I read everything, of course I did not understand something, but I caught the general idea.
If anything, I'm ready to support the Yandex DNS plugin and ensure its delivery in the form of packages for RHEL distributions.
</details>
