### ISSUE TITLE
MAC-Based Recovery

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#827]
We need to implement [MAC-Based Recovery](https://letsencrypt.github.io/acme-spec/#mac-based-recovery) as per current ACME spec.

**Comment by kuba** [comment]
Blocked on #826

**Comment by kuba** [comment]
Blocked on https://github.com/letsencrypt/boulder/issues/855.

**Comment by pde** [comment]
This isn't implemented in boulder, and won't be for launch, so kicking this down the road for now.

**Comment by bmw** [comment]
This feature has been removed from the ACME spec so I'm closing this ticket.
