### ISSUE TITLE
Handle snap upload problems

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8273]
During our 1.8.0 release, one of the snaps failed to upload. See https://dev.azure.com/certbot/certbot/_build/results?buildId=2628&view=logs&j=d150120f-6634-5552-7a3b-78014609a3b1&t=2d30e1b7-c9fe-5ba3-0bfd-8fc22bc0dee6&l=12840. Despite this failure, the Azure job still "passed". I only noticed this when I went to manually promote the snaps to the stable channel and found that this snap did not exist.

I think the reason the Azure job passed is due to Azure having the default bash behavior where it keeps running after a failed command and the entire bash step is only considered to have failed if the last step failed.

How should we deal with this? My initial idea is:

1. Use something like `set -e` here (and everywhere else we use `bash` in Azure).
2. If `snap upload` fails, try it again a set number of times.

I think step 2 is necessary once step 1 is implemented because last I checked `snap upload` will fail if an identical snap has already been uploaded meaning that we cannot just kick the build to solve the problem. Once at least one snap has been uploaded, future upload jobs using the same snaps will always fail (unless we add additional logic to check for this case).

**Comment by bmw** [comment]
It looks like someone proposed changing Azure's default behavior here but it never happened. See https://github.com/microsoft/azure-pipelines-tasks/issues/10125. The workaround is to manually include `set -e`.

(For what it's worth, I tested GitHub Actions and it does fail if any shell command fails. I believe Travis also had the same behavior.)

**Comment by ohemorange** [comment]
I agree that just retrying upload for individual failed snaps is best, but we could possibly also catch errors and delete all uploaded snaps if any snap upload fails. Not sure if there's an api for deleting snaps.

**Comment by ohemorange** [comment]
Another thought; if we manually cancel the build mid-run, we'll fail subsequent runs. Not sure of the best way to handle that, if we set `-e`.

**Comment by ohemorange** [comment]
Do single-line bash runs need `set -e`?

**Comment by bmw** [comment]
Single command bash scripts shouldn't need `set -e`, but it doesn't hurt anything either.
