### ISSUE TITLE
PluginError parsing Apache mod_deflate.conf

### ISSUE THREAD

**Issue by esherwoo77** [certbot/certbot#8277]
I receive a PluginError when Certbot attempts to parse my Apache2 config that includes a mod_deflate conf. I don't receive the error if I disable mod_deflate. The error when I do a Certbot renew dry-run (or when I run certbot --apache) is:

> Could not choose appropriate plugin: The apache plugin is not working; there may be problems with your existing configuration.
> The error was: PluginError('There has been an error in parsing the file /etc/apache2/mods-enabled/deflate.conf on line 7: Syntax error')
> Attempting to renew cert (tbep.org) from /etc/letsencrypt/renewal/tbep.org.conf produced an unexpected error: The apache plugin is not working; there may be problems with your existing configuration.
> The error was: PluginError('There has been an error in parsing the file /etc/apache2/mods-enabled/deflate.conf on line 7: Syntax error'). Skipping.
> All renewal attempts failed. The following certs could not be renewed:
>   /etc/letsencrypt/live/tbep.org/fullchain.pem (failure)

Line 7 of the deflate.conf file is:
>`<ifmodule mod_deflate.c="">`

And, the letsencrypt log says:

> 2020-09-09 14:36:01,965:DEBUG:certbot.cli:Var dry_run=True (set by user).
> 2020-09-09 14:36:01,965:DEBUG:certbot.cli:Var server={'staging', 'dry_run'} (set by user).
> 2020-09-09 14:36:01,965:DEBUG:certbot.cli:Var dry_run=True (set by user).
> 2020-09-09 14:36:01,965:DEBUG:certbot.cli:Var server={'staging', 'dry_run'} (set by user).
> 2020-09-09 14:36:01,965:DEBUG:certbot.cli:Var account={'server'} (set by user).
> 2020-09-09 14:36:01,974:INFO:certbot.renewal:Cert not due for renewal, but simulating renewal for dry run
> 2020-09-09 14:36:01,974:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
> 2020-09-09 14:36:02,073:DEBUG:certbot_apache.configurator:Apache version is 2.4.41
> 2020-09-09 14:36:02,372:DEBUG:certbot.plugins.disco:Other error:(PluginEntryPoint#apache): There has been an error in parsing the file /etc/apache2/mods-enabled/deflate.conf on line 7: Syntax error
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/certbot/plugins/disco.py", line 130, in prepare
>     self._initialized.prepare()
>   File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 257, in prepare
>     self.parser.check_parsing_errors("httpd.aug")
>   File "/usr/lib/python3/dist-packages/certbot_apache/parser.py", line 132, in check_parsing_errors
>     raise errors.PluginError(msg)
> certbot.errors.PluginError: There has been an error in parsing the file /etc/apache2/mods-enabled/deflate.conf on line 7: Syntax error
> 2020-09-09 14:36:02,373:DEBUG:certbot.plugins.selection:No candidate plugin
> 2020-09-09 14:36:02,374:DEBUG:certbot.plugins.selection:No candidate plugin
> 2020-09-09 14:36:02,374:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
> 2020-09-09 14:36:02,374:INFO:certbot.main:Could not choose appropriate plugin: The apache plugin is not working; there may be problems with your existing configuration.
> The error was: PluginError('There has been an error in parsing the file /etc/apache2/mods-enabled/deflate.conf on line 7: Syntax error')
> 2020-09-09 14:36:02,375:WARNING:certbot.renewal:Attempting to renew cert (tbep.org) from /etc/letsencrypt/renewal/tbep.org.conf produced an unexpected error: The apache plugin is not working; there may be problems with your existing configuration.
> The error was: PluginError('There has been an error in parsing the file /etc/apache2/mods-enabled/deflate.conf on line 7: Syntax error'). Skipping.
> 2020-09-09 14:36:02,376:DEBUG:certbot.renewal:Traceback was:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/certbot/renewal.py", line 449, in handle_renewal_request
>     main.renew_cert(lineage_config, plugins, renewal_candidate)
>   File "/usr/lib/python3/dist-packages/certbot/main.py", line 1202, in renew_cert
>     installer, auth = plug_sel.choose_configurator_plugins(config, plugins, "certonly")
>   File "/usr/lib/python3/dist-packages/certbot/plugins/selection.py", line 235, in choose_configurator_plugins
>     diagnose_configurator_problem("authenticator", req_auth, plugins)
>   File "/usr/lib/python3/dist-packages/certbot/plugins/selection.py", line 339, in diagnose_configurator_problem
>     raise errors.PluginSelectionError(msg)
> certbot.errors.PluginSelectionError: The apache plugin is not working; there may be problems with your existing configuration.
> The error was: PluginError('There has been an error in parsing the file /etc/apache2/mods-enabled/deflate.conf on line 7: Syntax error')
> 
> 2020-09-09 14:36:02,376:ERROR:certbot.renewal:All renewal attempts failed. The following certs could not be renewed:
> 2020-09-09 14:36:02,376:ERROR:certbot.renewal:  /etc/letsencrypt/live/tbep.org/fullchain.pem (failure)
> 2020-09-09 14:36:02,377:DEBUG:certbot.log:Exiting abnormally:
> Traceback (most recent call last):
>   File "/usr/bin/certbot", line 11, in <module>
>     load_entry_point('certbot==0.40.0', 'console_scripts', 'certbot')()
>   File "/usr/lib/python3/dist-packages/certbot/main.py", line 1382, in main
>     return config.func(config, plugins)
>   File "/usr/lib/python3/dist-packages/certbot/main.py", line 1287, in renew
>     renewal.handle_renewal_request(config)
>   File "/usr/lib/python3/dist-packages/certbot/renewal.py", line 473, in handle_renewal_request
>     raise errors.Error("{0} renew failure(s), {1} parse failure(s)".format(
> certbot.errors.Error: 1 renew failure(s), 0 parse failure(s)

**Comment by alexzorin** [comment]
Thank you for your report. I can confirm that Apache is happy with below syntax, but latest Certbot crashes on it.

```apache
<ifmodule mod_deflate.c="">
```

Omitting the `=""`, Certbot no longer crashes. 

I don't think that syntax is doing anything useful. According to http://httpd.apache.org/docs/current/mod/core.html#ifmodule, `IfModule` does not support expressions like that. It just takes a name.

Based on Apache's [hand-rolled parser](https://github.com/apache/httpd/blob/8e2385e1bd10918d012ab24ae52d26542c4a3c92/server/core.c#L2905), I believe Apache itself interprets that to mean "is there is a module named `mod_deflate.c=`?", which would never be the case.

We could try fix Certbot's parser to more closely mimic what Apache's parser does here.

**Comment by esherwoo77** [comment]
Thank you. Removing the `="" `  from the ifmodule statement on my server no longer causes Certbot to crash.
