### ISSUE TITLE
Write instructions for how to continue to use the Identrust intermediate with LE

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8282]
Let's Encrypt is changing the default intermediate they use on September 29th. We should write a community forum post describing how users can continue to use the old intermediate with Certbot.

While I think we should double check this by looking at the certificate chain LE plans to serve and keeping in mind that [it's not a fatal error if we can't find the requested intermediate](https://github.com/certbot/certbot/blob/2b425110dc1c68110921ae648613a8c25db4d450/certbot/certbot/crypto_util.py#L558-L562), this should be as simple as setting `--preferred-chain "DST Root CA X3"` on the command line or in [cli.ini configuration file](https://certbot.eff.org/docs/using.html#configuration-file).

EDIT: Users also need to make sure they have Certbot 1.6.0+.

**Comment by alexzorin** [comment]
I've written it up [in this gist](https://gist.github.com/alexzorin/f0f62d95540567a9b0c3ff36403249eb). 

- The commentary on "what should I do?" might not be welcome or might overlap with whatever ISRG is going to say. I'm happy to cut it out.
- The "legacy"/"modern" wording can be changed as well, couldn't think of better words.

cc @maximillianh

**Comment by Tugzrida** [comment]
Just saw that [the switch has been delayed again until Jan 11 2021](https://community.letsencrypt.org/t/transition-to-isrgs-root-delayed-until-jan-11-2021/125516/3)

There's less time pressure now, but here's my suggestions for that draft:
- Personally, I find yyyy-mm-dd dates harder to parse over a written form like January 11 2021

- I'd incorporate the "Which chain should I use?" section into the first section - then someone can know if they actually need to use the DST chain before getting to the instructions. Something like:

    ...You do not need to do anything to begin using the new certificate chain.

    This new chain is however not compatible with some older devices, including:
    (existing incompatibilities section)
    The legacy chain will remain available until September 29 2021. If you wish to remain compatible with these older devices for an additional year, you may choose to use the legacy chain.

**Comment by alexzorin** [comment]
Updated with new dates and some of your suggested changes.

**Comment by alexzorin** [comment]
A few threads cropped after https://letsencrypt.org/2020/11/06/own-two-feet.html was published and widely shared. Do we have a timeline about getting some instructions out?

**Comment by bmw** [comment]
What you wrote looks good to me! Thanks a lot for picking this up

I think you should feel free to post it on the community forum and close this issue.

I can also do that myself if you prefer.
