### ISSUE TITLE
Remove all conflicting server names from nginx compatibility tests

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8285]
In the nginx configs in `certbot-compatibility-test/certbot_compatibility_test/testdata/nginx.tar.gz`, there are a number of domains that have conflicting server blocks. You can see nginx complaining about these names in the logs with output like [this](https://dev.azure.com/certbot/certbot/_build/results?buildId=2650&view=logs&j=250aa146-b243-5f8f-bf86-17a529c9fb7e&t=9baa2014-9673-5e78-8f4f-7a463caf2bfa&l=1525).

When nginx is configured like this, one of the server blocks takes precedence, but this isn't something that Certbot's nginx plugin (or the Apache plugin) understands. We do not try to handle configurations like this and instead expect there to only be one server block for a domain. When there is more than one, we arbitrarily pick one.

A change in the server block we arbitrarily pick caused the tests to fail when I upgraded them to Python 3 in https://github.com/certbot/certbot/pull/8248. Now for some reason, it's broken again as you can see at https://dev.azure.com/certbot/certbot/_build/results?buildId=2651&view=logs&j=765a0b30-9c0a-5d8e-384b-769728e3bd67&t=c86e32a1-1e12-5ad8-2876-6d701afb3a84.

Let's fix this once and for all by removing all duplicate server names that nginx is complaining about.

The configuration at `certbot-compatibility-test/nginx/nginx-roundtrip-testdata` largely copies the config from the tarball so it would be great to fix this problem in those configs too when doing this.

**Comment by alexzorin** [comment]
>or the Apache plugin

Nit: The Apache plugin does handle this situation properly since #6729 (0.31.0). Doing the same for nginx would still be nice because it would fix the Cloudflare problem (#7275). 

But yeah, unless/until that's tackled, no point keeping these cases around.

**Comment by bmw** [comment]
Thanks for correcting me. I had forgotten that we handle this case automatically in Apache when solving challenges.

**Comment by alexzorin** [comment]
In the `nginx-roundtrip-testdata` and the tarball configs, only `[www.]random25863.example.org` is a duplicative domain. I think it alone is what causes the test failure - #8286 should fix it.

I think the other instances of `conflicting server name`, occurring during the installation and enhancement stages, are caused by some kind of defect in the nginx installer.

In the `lots/` configuration from the tarball, you will see e.g. that `random25266.example.org` is not duplicative, but Certbot ends up creating duplicative HTTPS virtualhosts for it. I don't yet understand why it's happening, but it seems like it should be addressed separately.

**Comment by bmw** [comment]
Nice catch! I started to create a new issue for us to look into that eventually and if you think we should you're welcome to do so, but I think that output will disappear after https://github.com/certbot/certbot/pull/8237 lands. If you/Erica wanted, we could change things to always log that output at the debug level (and fix the compatibility tests so the plugin's log output is printed?), but otherwise, while I do think this would be good to look into, if our tests don't even show the problem without modifications, I think there are probably higher priority things for us to work on especially if there aren't any real bug reports of a problem like this.
