### ISSUE TITLE
Recover registration URI

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#829]
As per [ACME spec](https://letsencrypt.github.io/acme-spec/#registration):

"If the server already has a registration object with the provided account key, then it MUST return a 409 (Conflict) response and provide the URI of that registration in a Location header field. This allows a client that has an account key but not the corresponding registration URI to recover the registration URI."

This is not implemented by the `acme` module

**Comment by kevgliss** [comment]
Has this been worked on? It's pretty key to some integration I am currently writing. If no one has taken a stab at this I will submit a PR.

**Comment by kuba** [comment]
@kevgliss, I have some code to support this bug in my local branch. Maybe I could try to upload it... Though New Year's Eve is close, so it might not happen until first days of January :)

**Comment by kevgliss** [comment]
@kuba sounds good, I took a look at look at the client yesterday but could not find a particularly clean way of doing this. Will look forward to seeing your changes and maybe I can iterate on them.
