### ISSUE TITLE
Upgrade tools/dev_constraints.txt 

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8290]
Some of our packages pinned there are quite old and their age is causing problems like https://github.com/certbot/certbot/issues/8204. I think we should update these packages.

Doing this is a bit of a manual process. The way I would do this is to empty the contents of the file, create developer virtual environments on a couple popular systems where we expect people to be working on Certbot, run `pip freeze`, and merge the results after filtering out things like our local packages. When picking systems to gather these dependencies on, we should gather dependencies for both Python 2 and Python 3 if Python 2 is still supported when working on this. I would also like to have macOS included in this for my own sanity since it's different enough from Linux, but I'm happy to help do this.

When merging the output of `pip freeze`, if there are packages that are only sometimes installed, they should still be included in the file. If the same package has different versions installed, this will have to be manually inspected and a single version picked that works everywhere.

**Comment by adferrand** [comment]
Could we reuse `letsencrypt-auto-source/rebuild_dependencies.py` here ?

**Comment by bmw** [comment]
A couple potential gotchas that come to mind if we try to use that are:

1. `letsencrypt-auto-source/letsencrypt-auto --install-only -n` used by that script will stop working soon.
2. It doesn't capture important targets like Python 3 on Ubuntu 20.04 which is used by some Certbot devs and our snaps or macOS used by me.

With that said, that script could certainly be part of or the starting point of the solution here.

(For what it's worth, I'm also open to other options here for how to pin our dependencies for development, testing, snaps, and Docker images. I'm not familiar with an option for doing this across a variety of environments though which I think we need if we want to pin down our development environments.)

**Comment by adferrand** [comment]
> (For what it's worth, I'm also open to other options here for how to pin our dependencies for development, testing, snaps, and Docker images. I'm not familiar with an option for doing this across a variety of environments though which I think we need if we want to pin down our development environments.)

In the long term, but it is way beyond the scope of this issue I think, we should pipstrap to a recent version of `pip`, and embrace PEP 517/518 by moving to `poetry.toml` and a build tool that supports dependency locking.

**Comment by bmw** [comment]
This conversation about longer term changes that I started here is somewhat offtopic, but while we should probably do what you said anyway, do any of these build tools support dependency locking across multiple environments? For example, can they help us be sure that dependencies are pinned for devs on macOS, Ubuntu, Windows, etc where different conditional dependencies will be used?

**Comment by adferrand** [comment]
I realized that I never answer to your question.

I will talk for poetry only, since I use it, but I expect other tools that support this kind of locking would have similar features. Yes, it can help you lock your dependencies for all OSes, and in both dev/non-dev environments. The poetry lock file, name `poetry.lock` contains all possible packages required by the dependency tree, and includes environment markers, and categories for dev/non-dev dependencies and extras.

I leverage this feature in two ways:
* first, for the main purpose, which is to setup in one command a virtual environment with the precise set of dependencies as locked for development purpose (tox uses also it to setup its test virtual environments)
* second, to generate `constraints.txt` files that can then be used to setup the runtime installation for packaging purpose

**Comment by bmw** [comment]
Really? I think listing all possible packages in the dependency tree is at least in theory impossible. If one of your dependencies doesn't offer a wheel, your only option is an sdist. Using an sdist, you have to run arbitrary Python code to determine what the dependencies are and that code's behavior can be different on different platforms. Maybe you can build the wheel from the sdist and inspect that, but there may be reasons why the project doesn't offer the wheel and conditional dependencies are not properly specified.

Do you know if Poetry does anything to help handle this case? What about the case where a project publishes multiple wheels? In that case, I think you need to inspect each of them to build the full list of potential dependencies.

You have more experience with these tools than I do, but I always thought your dependency lockfile was specific to the environment where it was created.

**Comment by adferrand** [comment]
Ah yes. To be clear, I was not saying that poetry could, from one environment, anticipate the dependency of another environment. I was saying that the lock file can support multiple resolved dependency trees for multiple environment, but you still need to make the actual resolution of them on each target environment.

At least the workflow here seems to be to find the correct set of dependencies in `pyproject.toml`so that the generated lock file is working for each target environment. I remembered in particular poetry failing one or two times since I use here because some packages resolved in the tree were incompatible with lock file (non existent or version mismatch). Each time I solved that by refining the `pyproject.toml`to solve the ambiguity. 

That said, for instance with dnsrobocert, poetry successfully stores the set of requirements related to certbot on Windows, since dnsrobocert requires certbot, even if the resolution is executed on Linux. So there is some kind of foreign resolution working on here. I would add here that on an initial resolution (without an initial lock file), the computation can take several minutes, so there is some heavy lifting done in the lock file construction.

Now there is certainly some limits. You talked about sdists, to push things to the extreme one could imagine a `setup.py` that picks random dependencies at each installation. How poetry reacts in this kind of situation? I will try. I expect that in this case you need to set explicitly all possible transitive dependencies in `pyproject.toml`.

But provided that a project has dependencies that create deterministic dependency trees and you have integration tests to verify that, these kind of tool can help industrialized the pinning logic done in certbot.

**Comment by bmw** [comment]
I see. I would be interested to learn more about what tools like poetry do to help solve this particular problem of needing to pin dependencies for multiple environments. This problem in general isn't something I've seen much discussion about in the Python community.

If, for example, poetry keeps track of all the environment markers it sees during dependency resolution and records them even if they were not needed for the target environment, that could be useful. It may not be sufficient though and we may have to stick with installing Certbot in multiple environments and then merging the list of installed dependencies like we've been doing. At that point, there may be other reasons for us to use a tool like poetry, but for this particular problem, `pip freeze` may be just as good.

As a bit of a tangent, I had an idea for a related side project that I'll probably never get around to building that essentially solves this problem. The tool would take as input a list of Python projects specified in some way (project names on PyPI, local `pyproject.toml` files, etc.). For those projects, it determines every possible build and runtime dependency for every system variation that can be specified in environment markers or understood by tools like `pip` when it chooses wheels from PyPI.

In some cases like we talked about in our last two posts, this cannot be done. If the project only offers a `setup.py` file and no wheel, you cannot reliably figure this out. In this case, the tool would explain the problem to you and give you options on how to resolve it (e.g. you could tell the tool to ignore that dependency and you figure that out yourself, you could tell it to skip pinning for particular CPU architectures or OSes that you don't need to support, etc.). This tool would be slow and I think resolving the different conflicts the tool can't help with in a way that allows the user and the tool to be sure that all dependencies are really satisfied everywhere could be quite annoying. With that said, I think such a tool is exactly what we want here and I think the tool would get better overtime as more projects offer wheels and use `pyproject.toml` files.

I personally don't think it makes sense for the Certbot team to prioritize building such a tool as I think there are more impactful uses of our time and we can by with something less exhaustive and then just running tests to make sure it works, but this is something I've been thinking about and I'd be curious to hear your thoughts Adrien.

**Comment by bmw** [comment]
I continue to be surprised how little discussion there is about this problem online, but `poetry` does seem to help here. When I generate the lockfile, it seems like all specified dependencies are recorded recursively including all dependencies with environment markers. Dependencies with environment markers that don't apply to the current system are still downloaded and recorded in the lockfile recursively.

I may have missed something, but it seems like `pipenv` in contrast does not do this and instead only locks the dependencies for the current platform. See https://github.com/pypa/pipenv/issues/857.

For the reasons I described in above posts, I think fully solving this problem in theory is impossible, but I wonder if in practice `poetry` coupled with all of the testing we do which would hopefully catch any potential problems could replace a lot of the custom `pip` tooling we have.

**Comment by bmw** [comment]
To continue rambling/documenting my thoughts, concerns, and research here, I'm a little worried about our ability to sanely use poetry directly due to our giant monorepo containing multiple Python projects. I've worked around this for testing purposes by creating a top level `pyproject.toml` that depends on everything else, but this certainly doesn't seem to be the intended way to use `poetry`. After doing that though, I could lock the dependencies with `poetry lock` and even export them to a standard requirements file with `poetry export`.

**Comment by bmw** [comment]
@adferrand, I've written a lot here and tagged you on a lot of issues/PRs recently but if you have the time and interest, I'd be curious to hear how feasible you think it'd be to adopt `poetry` for some of our work on Certbot. I'm very impressed with Poetry's handling of its lockfile, but I don't see a great way to integrate it with our big monorepo containing many separate packages. Do you immediately see a good way around that or do you also think it's going to be a bit awkward to get it to work?

**Comment by adferrand** [comment]
Always glad to participate!

Sadly I have to agree with you. Poetry is great and I appreciate its functionalities in my projects, but I do not see how to integrate it nicely in a multi-project repository layout.

Just to give some partial reflexions about this. I think we could work with separated lock files for each package if it is only about controling the set of dependencies used to distribute Certbot during a release. It would require some adaptations for each distribution method, but nothing too much complex in my opinion.

However the packages are connected, with common developments which require a unified environment experience. Indeed you can achieve this by creating some kind of top-level project, but it kinda defy the purpose of poetry and will make deployable artifacts more complex to build.

Things could improve in the future. Poetry is under active development, so the required functionalities could be added at some point. In particular a design proposition for subprojects support has been written: https://github.com/python-poetry/poetry/issues/2270

Certbot repository could also evolve to a simpler layout eventually, with only few packages if not one. I think in particular of the DNS plugins that would be totally disconnected from Certbot using an agnostic plugin interface. The Apache and Nginx plugins as well, or integrated as extras in Certbot. In these situations it would be workable to migrate to poetry.

**Comment by bmw** [comment]
Thanks for sharing your thoughts!

Because of all that, I think we shouldn't try to fully incorporate `poetry` now, however, I am thinking about using it to help us generate our requirements files. I'm essentially imagining creating a dummy, top level `pyproject.toml` file tucked away in `tools` somewhere that depends on all of our other projects and any extra tools we need like `pip`. We'd then use `poetry` to generate a lock file for that project, export it to a requirements file using [poetry export](https://python-poetry.org/docs/cli/#export), and then filtering out things like our own packages, hashes, and environment markers as needed. We could also
create an another dummy `pyproject.toml` file for our oldest tests that depends on the other top level file as well as our "oldest" dependencies.

As part of this, I think we could simplify our pinning files to just have one normal file and one oldest file. If you have concerns with this plan at a high level, please let me know soon as I'm planning on working on this this week.

**Comment by bmw** [comment]
Fixed in https://github.com/certbot/certbot/pull/8741.
