### ISSUE TITLE
Renew Hook argument

### ISSUE THREAD

**Issue by davidebelloni** [certbot/certbot#8299]
Hi,
it would be nice if the domain for which the renew has been performed should be passed as an argument to the post hooks.

Use case is cert and key concatenation for haproxy

Thanks

**Comment by alexzorin** [comment]
You may wish to use `--deploy-hook` for this instead, which will have `$RENEWED_LINEAGE` (the certificate name) and `$RENEWED_DOMAINS` (the list of domains on the certificate) in the environment. That would be a suitable place to perform the concatenation.

There is a feature request at #6722 to include the full list of renewing/renewed certificates in the pre/post hooks, respectively. If you would like to see this implemented, you could leave a vote or comment there.

Does that sound like it will work for you?

**Comment by davidebelloni** [comment]
Hi,
you are right.

Sorry but I'm a newbie about certbot and this option wasn't clear to me

Thanks
