### ISSUE TITLE
Detect wildcard domain names in authorization requests

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#830]
According to the [ACME spec](https://letsencrypt.github.io/acme-spec/#authorization-objects):

"Wildcard domain names (with “*” as the first label) MUST NOT be included in authorization requests."

`acme` module should guard that

**Comment by pde** [comment]
Since #1421 has landed, this is no longer an issue with the Python client.

**Comment by schoen** [comment]
Also, wildcards are now allowed. :slightly_smiling_face:
