### ISSUE TITLE
Figure out how to test against Sectigo ACME server

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#8302]
If they have a staging server, that will work. If not, we'll need an account/login from Sectigo.

Further information available here: https://docs.google.com/document/d/16qxEe7FqhBgsHqpYf7zc_xpyMQw5VNZlmxxijJQok2E

**Comment by ottok** [comment]
Is Sectigo the only alternative to Let's Encrypt? Should perhaps some more generic testing be planned for to support all ACME compatible providers that Certbot users might be interested in?

**Comment by maxadamo** [comment]
The last time I have asked, they did not have a staging server. 
However,

- the purpose of the staging server IMO, is to overcome the rate limits of the production LetsEncrypt. But SectiGO does not have rate-limits. Just in case, you could use `--dry-run` (not mandatory). 
- even if they had a staging server, SectiGO requires to use the so-called `hmac-key` authentication and I doubt that you can use the same access keys against the staging and production, and one of the purposes of testing, is to ensure that your keys are working.
