### ISSUE TITLE
Key pinning (ACME)

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#831]
According to the [ACME spec](https://letsencrypt.github.io/acme-spec/#https-requests):

"Clients SHOULD support HTTP public key pinning [RFC7469], and servers SHOULD emit pinning headers. "

This is currently not supported by the `acme` module

**Comment by jsha** [comment]
FWIW, I would consider this relatively low priority. I don't think implementing pinning headers in Boulder is at the top of the priority list.

**Comment by chriscroome** [comment]
For the `webroot` plugin it would be ideal, for Apache, if it wrote a `/.well-known/acme-challenge/.htaccess` file containing something like this:

```apache
<IfModule mod_headers.c>
Header set Public-Key-Pins "pin-sha256=\"klO23nT2ehFDXCfx3eHTDRESMz3asj1muO+4aIdjiuY=\"; pin-sha256=\"633lt352PKRXbOwf4xSEa1M517scpD3l5f79xMD9r9Q=\"; max-age=2592000; includeSubDomains"
</IfModule>
```

The above example was [taken from here](https://raymii.org/s/articles/HTTP_Public_Key_Pinning_Extension_HPKP.html)

**Comment by thomaszbz** [comment]
This feature shoud _never_ be enabled by default, because people really need to be aware of side effects, when enabled.

References:

- https://blog.qualys.com/ssllabs/2016/09/06/is-http-public-key-pinning-dead
- https://www.heise.de/security/artikel/Wachsende-Kritik-an-Public-Key-Pinning-fuer-HTTPS-3324703.html

Still, nice to have for those who want it (I'd rather go for DANE).

**Comment by ArchangeGabriel** [comment]
@thomaszbz This is not about enabling HPKP on people server I think, but rather on Let’s Encrypt ACME server side: you might want to be sure you’re sending your CSR to Let’s Encrypt ACME server, and not to some other server MITM’ing you with a certificate issued by another CA…

**Comment by thomaszbz** [comment]
@ArchangeGabriel Now that this issue is about communication between certbot and LE's servers I go along with your post. Still, DNSSEC/DANE would be an option for that, too (maybe in the long run).

**Comment by ArchangeGabriel** [comment]
Yes, for sure. :)

**Comment by schoen** [comment]
Sad to say, from my point of view, HPKP seems to have been deprecated by its inventors and it's not mentioned normatively at all in the current ACME spec. :cry: So unfortunately, this is no longer relevant to spec compliance!

**Comment by ArchangeGabriel** [comment]
Indeed, but then something like DANE should be implemented instead. ;)
