### ISSUE TITLE
certbot on windows issue

### ISSUE THREAD

**Issue by darkworks** [certbot/certbot#8311]
Hi am running windows 10 with Apache web server.

i have installed certbot on my system and have generated certificates for my domain.

so 3 moths ago when i run it generated certificates it this location

```
C:/Certbot/archive/mysite.com/fullchain1.pem
C:/Certbot/archive/mysite.com/privkey1.pem
```

and i added this to my apache config file like

```
SSLCertificateFile "C:/Certbot/archive/mysite.com/fullchain1.pem"
SSLCertificateKeyFile "C:/Certbot/archive/mysite.com/privkey1.pem"
```

so now after 3 months when its near to expiry i renew them and i noticed it generated new  certificates with name like

```
C:/Certbot/archive/mysite.com/fullchain2.pem
C:/Certbot/archive/mysite.com/privkey2.pem
```

this mean every time i renew certificates i will have to update my apache config file by increasing number like

```
SSLCertificateFile "C:/Certbot/archive/mysite.com/fullchain2.pem"
SSLCertificateKeyFile "C:/Certbot/archive/mysite.com/privkey2.pem"
```

so it will will be good if cerbot overwrite old certificates instead of creating new file and increment it with number so that we do not have to update apache config files everytime on renewal .

thanks

**Comment by alexzorin** [comment]
>so it will will be good if cerbot overwrite old certificates instead of creating new file and increment it with number so that we do not have to update apache config files everytime on renewal .

Indeed! 

That is the purpose of `C:\Certbot\live\` - https://certbot.eff.org/docs/using.html#where-are-my-certificates. You can point your Apache configuration to the files in that directory, and they will always point to the latest certificate.

I'm going to close this as this should hopefully solve your question, but if you have anything further to add, just reply back.

**Comment by darkworks** [comment]
ya but in live directory there are shortcuts , i tried apache pointing to it and it give me error was not able to read

**Comment by alexzorin** [comment]
I see. Indeed they are symlinks, but you shouldn't be having any trouble with Apache reading them.

Could you please share exactly what error message Apache gives, and also what method you used to install Apache (i.e. XAMPP or anything like that)?

**Comment by darkworks** [comment]
when in apache config i add

```
SSLCertificateFile "C:/Certbot/live/site.com/fullchain.symlink"
SSLCertificateKeyFile "C:/Certbot/live/site.com/privkey.symlink"
```

am getting error 
`SSLCertificateFile: file 'C:/Certbot/live/site.com/fullchain.symlink' does not exist or is empty`

and without extenstion 

```
SSLCertificateFile "C:/Certbot/live/site.com/fullchain"
SSLCertificateKeyFile "C:/Certbot/live/site.com/privkey"
```

am getting error 

`SSLCertificateFile: file 'C:/Certbot/live/site.com/fullchain' does not exist or is empty`

**Comment by alexzorin** [comment]
I think that's just Windows Explorer being confusing. The file extension of the symlinks is still `.pem`:

![windows screenshot](https://i.imgur.com/2nyzL4K.png)

**Comment by darkworks** [comment]
thanks .pem extension worked :)
