### ISSUE TITLE
Improve successful status messages in terminal output

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#8329]
"Please read the Terms of Service" uses agree/cancel, and "Would you be willing to share your email address", which is printed directly after, uses yes/no. We should harmonize these. If we change the former, we may want to check with a lawyer.

`Obtaining a new certificate` --> `Requesting a new certificate for example.com [and N more domains].`

`Cleaning up challenges` --> 
```
Successfully received certificate.
Certificate is saved at /etc/letsencrypt/live/example.com/fullchain.pem
Key is saved at /etc/letsencrypt/live/example.com/privkey.pem
These locations are symbolic links that point to the currently valid versions. Certbot will automatically update the files at these locations before the certificate expires.
This certificate will expire on 2019-03-14.
```
(where this is printed may need to be moved)

`Deploying Certificate to VirtualHost /etc/nginx/sites-enabled/example.com` --> `Deploying certificate to /etc/nginx/sites-enabled/example.com`

```
Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/example.com/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/example.com/privkey.pem
   Your cert will expire on 2019-03-14.
```
--> `Congratulations! You have successfully enabled https. You can confirm this by navigating to https://example.com in a browser.`

**Comment by alexzorin** [comment]
Closed by #8852.
