### ISSUE TITLE
Delete reporter.py and IReporter interface

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#8331]
Certbot's code no longer uses reporter.py as of #8852. We should now remove the parts that require a breaking change in the next major version.

Keep in mind that depending on how this is done, this may be a breaking change requiring Certbot 2.0. See https://github.com/certbot/certbot/blob/95a6b61cdc630dff91b9e9368914c04bd2a6a146/certbot- apache/certbot_apache/_internal/configurator.py#L1517. Our plan for dealing with API changes like this is at https://certbot.eff.org/docs/compatibility.html.

We may not actually want to rip it out, especially until after we've looked at renewal. Basically the problem is that we stick too much stuff in there that would be better put contextually; we should have little enough output that important information is clear in context, as it's logged.

We may want to block this on the renewal work described in https://github.com/certbot/certbot/issues/8330.

**Comment by alexzorin** [comment]
Based on [UX discussions](https://docs.google.com/document/d/1viiuYQafSxrTQtBI2a1_p3Q_IBVDAZAw8xkSWOQglHM/edit?usp=sharing), we will be able to fully remove all first-party usages of `IReporter`.

I suppose we will have to keep the actual interface in place until at least 2.0, per backwards-compatibility guarantee.

Renewal was found not to be a blocker.

**Comment by bmw** [comment]
For the sake of making the list of issues in our current milestone a little more attainable, I'm moving all of the issues in the UX project that are currently blocked to the next milestone, but feel free to recategorize it if you disagree.
