### ISSUE TITLE
Certbot renew systemd timer starts before nginx and starts it unconfined (SELinux)

### ISSUE THREAD

**Issue by driskell** [certbot/certbot#8346]
## My operating system is (include version):
CentOS Linux release 7.8.2003 (Core)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager

## I ran this command and it produced this output:
If a machine is rebooted just about when the timer is due to fire - or if it is switched off at the time and then booted up. This actually causes the nginx plugin to start nginx manually. Unfortunately, on an SELinux machine, this form of starting nginx outside of systemd causes it to run in the unconfined domain and causes the subsequent nginx start via systemd to fail due to permissions issue due to the domain mismatch.

Overall this creates a downgrade situation where confinement is completely lost at startup and an internet-facing service essentially runs unconfined.

Furthermore, the PID file in /var/run is created with incorrect SELinux context and thus cannot be access by nginx in the httpd_t domain. Thus you have to manually remove it in order to recover the nginx service again.

Below is the journal contents (condensed):

```
Oct 05 10:42:37 XXX systemd[1]: Starting This service automatically renews any certbot certificates found...
-- Subject: Unit certbot-renew.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit certbot-renew.service has begun starting up.
Oct 05 10:42:38 XXX certbot[570]: Cert is due for renewal, auto-renewing...
Oct 05 10:42:39 XXX certbot[570]: Plugins selected: Authenticator nginx, Installer nginx
Oct 05 10:42:39 XXX certbot[570]: Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org
Oct 05 10:42:47 XXX systemd[1]: Starting nginx - high performance web server...
-- Subject: Unit nginx.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit nginx.service has begun starting up.
Oct 05 10:42:47 XXX systemd[1]: Failed to parse PID from file /var/run/nginx.pid: Invalid argument
Oct 05 10:42:47 XXX nginx[1270]: nginx: [emerg] open() "/var/run/nginx.pid" failed (13: Permission denied)
Oct 05 10:42:47 XXX systemd[1]: Failed to start nginx - high performance web server.
-- Subject: Unit nginx.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit nginx.service has failed.
--
-- The result is failed.
Oct 05 10:42:47 XXX certbot[570]: Performing the following challenges:
Oct 05 10:42:47 XXX certbot[570]: http-01 challenge for XXX
Oct 05 10:42:47 XXX certbot[570]: nginx: [error] open() "/var/run/nginx.pid" failed (2: No such file or directory)
Oct 05 10:42:49 XXX certbot[570]: Waiting for verification...
```

I'm fairly familiar with SELinux so happy to assist with that knowledge, as I maintain a few modules within my company. I think generally the issue lies with the starting up of nginx by the renewal script which should go via systemd. The certbot binary is bin_t so starts as unconfined_service_t so I think should be able to use systemctl OK as below rule exists in system policy.

```
allow unconfined_service_t systemd_unit_file_type : service { start stop status reload enable disable kill load } ;
```

## Certbot's behavior differed from what I expected because:
Nginx plugin should start nginx via systemd and not run it directly, so as to prevent loss of confinement.
When loss of confinement occurs, SELinux context on the PID file is incorrect and as such prevents startup of nginx in the httpd_t domain. Normally the PID file transitions to correct state when created from httpd_t domain but as nginx isn't running in that domain the transition doesn't take place, and it creates with the default var_run_t context, whereas httpd_t domain can only handle httpd_var_run_t files.

## Here is a Certbot log showing the issue (if available):
See above journal logs - everything within certbot itself is generally fine. This is relating to the timer itself.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
N/A

**Comment by driskell** [comment]
This is correct context for nginx.pid:

```
-rw-r--r--. root   root   system_u:object_r:httpd_var_run_t:s0 nginx.pid
```

When the issue occurs it's actually `var_run_t` instead. Thus the permissions error.

Audit then shows this:

```
type=AVC msg=audit(1601894567.193:94): avc:  denied  { read write } for  pid=1274 comm="nginx" name="nginx.pid" dev="tmpfs" ino=16274 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:var_run
_t:s0 tclass=file permissive=0
```

**Comment by alexzorin** [comment]
Relevant previous discussion: https://github.com/certbot/certbot/issues/4716#issuecomment-331970072

Avoiding touching the nginx plugin or the EL SELinux policies, I wonder if this specific issue could be avoided by adjusting the Certbot timer such that there is minimum delay after boot.
