### ISSUE TITLE
Leave blank to delete all !

### ISSUE THREAD

**Issue by funbot-co-uk** [certbot/certbot#8348]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## I ran this command and it produced this output: certbot delete
pick a number or "Leave blank to delete all certs"

## Certbot's behavior differed from what I expected because: I have deleted all my certs twice

I have mentioned this on the letsencrypt forum and it was suggested that I report it here
It seems a strange default behaviour to delete ALL certs without a confirmation - there is a warning but I have managed to trash 2 production servers. 

perhaps
#are you sure you would like to delete all certs (Y/n)

great software tho - thanks

**Comment by alexzorin** [comment]
Fixed by #8349.
