### ISSUE TITLE
Remove CentOS/RHEL 6 instructions from the Certbot website

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8358]
I'm creating this issue here instead of the website repo since we use this issue tracker more.

[CentOS 6 reaches its EOL at the end of November](https://wiki.centos.org/About/Product) so we should remove installation instructions for CentOS/RHEL 6 from the website.

It's important to do this before our December release because we're planning to fully deprecate certbot-auto then and the deprecation message tells users to visit the Certbot website where we currently tell these users to use certbot-auto.

**Comment by ohemorange** [comment]
I see this is in the current milestone, even though it's deprecated yet. Is that correct?

**Comment by bmw** [comment]
I think you accidentally wandered into next month's milestone.

This is in the [1.11.0 milestone](https://github.com/certbot/certbot/milestone/90) which is for our December release. The current milestone as of writing this for our release next week is the [1.10.0 milestone](https://github.com/certbot/certbot/milestone/88).

**Comment by ohemorange** [comment]
😮 That would certainly explain things! I saw 11 and 12 and assumed that since 12 exists, 11 must be the current one. Oops!

**Comment by billwanjohi** [comment]
FYI, `RHEL 6` is still in maintenance support until 2024...

**Comment by billwanjohi** [comment]
To elaborate, I maintain RHEL 6 systems that I must now scramble to manually renew certificates for because of this change, and the associated rapid discontinuation of `certbot-auto`. My only options are to install from source (explicitly discouraged), figure out how to install Snap (unsupported by ), or move to a completely different solution. I didn't anticipate any of this until yesterday.

**Comment by bmw** [comment]
@billwanjohi, sorry for the trouble and confusion, but it is not correct that you have to scramble to find another option to renew your certificates right now. You can find more details about the change to certbot-auto at https://community.letsencrypt.org/t/certbot-auto-no-longer-works-on-debian-based-systems/139702/7.

If you need additional help, I suggest making a post on that forum where there is a much larger community familiar with the project.

**Comment by billwanjohi** [comment]
Thanks for the clarification @bmw, I incorrectly assumed that my renewal failure was related to the deprecation message, but I had another, more local problem, and your message prompted me to just fix that for the time being.

You may still want to reconsider whether RHEL 6 users should be given any guidance, but as you say, administrators that have already installed certbot-auto are not yet in the lurch.

**Comment by bmw** [comment]
That's fair feedback. Unfortunately, making more recent versions of Certbot work on RHEL 6 is going to be hard. We were previously relying on Python 3.6 from the Red Hat Software Collections Library, but [that reached its EOL](https://access.redhat.com/support/policy/updates/rhscl-rhel6) the same time that CentOS 6 did.

With that said, we're currently working on instructions for how to essentially install Certbot from our source files. See https://github.com/certbot/certbot/issues/8422. Once those instructions are available, taking that approach would be some work for you, but it'd certainly possible to follow those instructions to install a newer version of Certbot on RHEL 6 if do not yet want to upgrade to a newer OS.
