### ISSUE TITLE
Option to install latest certbot on Ubuntu 20.04 without snap

### ISSUE THREAD

**Issue by paulocoghi** [certbot/certbot#8360]
Is there an option to install latest certbot on Ubuntu 20.04 without using snap?

In our scenario, snap is heavy and not an option because we are using really small Ubuntu servers.

**Comment by paulocoghi** [comment]
I am evaluating the alternative clients listed on https://letsencrypt.org/docs/client-options/

But I would like to know which one is "standalone" and provides a similar experience than Certbot, because I'm not understanding exactly the account private key requirement. With certbot we just ask for a certificate.

**Comment by paulocoghi** [comment]
I believe I found an alternative. [hlandau/acmetool](https://github.com/hlandau/acmetool) is very similar, provides a single-file dependency-free binary and it can be installed through a PPA and .deb.

**Comment by alexzorin** [comment]
I am a fan of acmetool, but be wary the author has not published binaries or packages for ACMEv2 yet. You won't be able to use it unless you build it from source or use the community-build binaries.

To answer your original question directly: Ubuntu 20.04 still has a `certbot` package available in `apt`.

**Comment by paulocoghi** [comment]
Thanks, @alexzorin for all the info! You are right and I will check `lego`.

> Ubuntu 20.04 still has a `certbot` package available in `apt`.

Yes, but unfortunately it's not the latest version.

**Comment by fake-name** [comment]
This is really, /really/ needed. I'm migrating to a new webserver for a project, and a `snapd` dependency is a showstopper. Snapd is huge and bloated, installs crap that runs at every boot, and clutters up `mount`.

Really, snap makes deelopment a little bit easier by basically shitting on all the end users. It's just a mistake in general.
