### ISSUE TITLE
Disambiguate certbot certonly/run behavior on existing ECDSA certificates

### ISSUE THREAD

**Issue by adferrand** [certbot/certbot#8365]
This issue concerns the ECDSA certificate generation feature provided by #8254. It is about how Certbot should behave when `certonly` or `run` command are run to generate a certificate for an existing lineage (either explicitly with `--cert-name` file or implicitly because of the set of domains required), as described in the design document: https://docs.google.com/document/d/18pr4F4SVim-bSR6izNV5ZYwolnvitTvmP6gqElDdZPU/edit?usp=sharing

Indeed since the default type of key used is RSA if `--key-type` is not set, we do not want Certbot to silently switch a ECDSA certificate for a RSA, and should in fact expect explicit user approval: passing explicitly the relevant CLI flags.

This will also fix the inverted situation with existing RSA certificates, when/if Certbot switches to ECDSA keys by default.

So, for both `certbot certonly` and `certbot run`:
1) If `--cert-name` is set, `--key-type` is not, a certificate exists for that lineage, and its type is not the same than the target type computed by Certbot, then an error should be raised, asking the user to set `--key-type` explicitly.
2) If neither `--cert-name` and `--key-type` are set, a certificate with an identical/subset of the requested domains exists, and its type is not the same than the computed target type, an error should be raised, asking the user to set `--key-type` and `--cert-name` explicitly.

**Comment by adferrand** [comment]
Block on #8254

**Comment by osirisinferi** [comment]
> 2. If neither --cert-name and --key-type are set, a certificate with an identical/subset of the requested domains exists, and its type is not the same than the computed target type, an error should be raised, asking the user to set --key-type and --cert-name explicitly.

Is an explicit use of `--cert-name` really necessary in that case? Certbot already has identified the existing lineage. Currently, it isn't required in those specific situations. It asks if you really want to re-issue it or just try to reinstall or it asks to expand an existing certificate, all without the explicit use of `--cert-name`. What's the added benefit when `--key-type` comes into play?

**Comment by bmw** [comment]
Partially due to things like reactions to my post [here](https://github.com/certbot/certbot/issues/2163#issuecomment-548528167), I think there will be a significant number of Certbot users who want to maintain both ECDSA and RSA certificates for their domains and this check removes any ambiguity about whether the user wants to issue a cert of a different key type along side their existing one or change the key type for that cert name.

The doc that Adrien linked above proposes adding an interactive prompt about this rather than erroring out in the future.

**Comment by adferrand** [comment]
Unblock #8254

**Comment by adferrand** [comment]
Fixed by #8435
