### ISSUE TITLE
Provide a documentation to migrate to ECDSA certificates

### ISSUE THREAD

**Issue by adferrand** [certbot/certbot#8366]
This issue concerns the ECDSA certificate generation feature provided by #8254. It is about to provide proper guidance to users in how to migrate to ECDSA certificates, as described in the design document: https://docs.google.com/document/d/18pr4F4SVim-bSR6izNV5ZYwolnvitTvmP6gqElDdZPU/edit?usp=sharing

Indeed we should write documentation with the recommended workflow for changing an existing certificate and an existing installation to use ECDSA keys, and also for requesting a new ECDSA certificate. This should include a warning that users who obtain certificates with ECDSA keys should be careful to not downgrade their Certbot version if they change installation methods because using ECDSA keys with older versions of the client is not supported by the Certbot team.

When this feature is released, someone from the core Certbot team should post this documentation to the community forum.

**Comment by adferrand** [comment]
Block on #8254

**Comment by adferrand** [comment]
#8254 partially fixes this issue, by providing instructions to migrate an RSA certificate to ECDSA. On top of it we should add the warning about downgrades, and post the documentation to the community forum.

**Comment by adferrand** [comment]
Unblock #8254 from #8431

**Comment by bmw** [comment]
I'm about to open a PR to flesh out the ECDSA docs. If it lands, all I think we need to do here is to update the Certbot submodule on the website repo after our next release and add a comment to the thread for the release linking to these docs.

**Comment by bmw** [comment]
PR is #8464.
