### ISSUE TITLE
[Apache] Certbot Fail attempt to install cert on WSGI

### ISSUE THREAD

**Issue by DevDorrejo** [certbot/certbot#8373]
## My operating system is (include version): 
OpenSUSe Leap 15.2

## I installed Certbot with (certbot-auto, OS package manager, pip, etc): 
pip

## I ran this command and it produced this output: 
certbot --apache

## Certbot's behavior differed from what I expected because:
Not install the existing cert on the Vhost

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
```
2020-10-13 15:18:09,200:DEBUG:certbot._internal.error_handler:Calling registered functions
2020-10-13 15:18:09,200:CRITICAL:certbot._internal.client:Rolling back to previous server configuration...
2020-10-13 15:18:09,463:DEBUG:certbot._internal.reporter:Reporting to user: We were unable to install your certificate, however, we successfully restored your server to its prior configuration.
2020-10-13 15:18:09,463:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
File "/opt/pip/lib/python3.6/site-packages/certbot_apache/_internal/configurator.py", line 2446, in config_test
util.run_script(self.option("conftest_cmd"))
File "/opt/pip/lib/python3.6/site-packages/certbot/util.py", line 115, in run_script
raise errors.SubprocessError(msg)
certbot.errors.SubprocessError: Error while running apache2ctl configtest.

AH00526: Syntax error on line 4 of /etc/apache2/vhosts.d/pg.example.com.conf:
Name duplicates previous WSGI daemon definition.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/pip/bin/certbot", line 8, in <module>
sys.exit(main())
File "/opt/pip/lib/python3.6/site-packages/certbot/main.py", line 15, in main
return internal_main.main(cli_args)
File "/opt/pip/lib/python3.6/site-packages/certbot/_internal/main.py", line 1362, in main
return config.func(config, plugins)
File "/opt/pip/lib/python3.6/site-packages/certbot/_internal/main.py", line 1115, in run
_install_cert(config, le_client, domains, new_lineage)
File "/opt/pip/lib/python3.6/site-packages/certbot/_internal/main.py", line 759, in _install_cert
path_provider.cert_path, path_provider.chain_path, path_provider.fullchain_path)
File "/opt/pip/lib/python3.6/site-packages/certbot/_internal/client.py", line 530, in deploy_certificate
self.installer.restart()
File "/opt/pip/lib/python3.6/site-packages/certbot_apache/_internal/configurator.py", line 2409, in restart
self.config_test()
File "/opt/pip/lib/python3.6/site-packages/certbot_apache/_internal/configurator.py", line 2448, in config_test
raise errors.MisconfigurationError(str(err))
certbot.errors.MisconfigurationError: Error while running apache2ctl configtest.

AH00526: Syntax error on line 4 of /etc/apache2/vhosts.d/pg.example.com.conf:
Name duplicates previous WSGI daemon definition.

2020-10-13 15:18:09,464:ERROR:certbot._internal.log:Error while running apache2ctl configtest.

AH00526: Syntax error on line 4 of /etc/apache2/vhosts.d/pg.example.com.conf:
Name duplicates previous WSGI daemon definition.
```
## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
```
<VirtualHost *:80>
ServerName pg.example.com

WSGIDaemonProcess pgadmin processes=1 threads=25 python-home=/opt/pip
WSGIScriptAlias / /opt/pip/lib/python3.6/site-packages/pgadmin4/pgAdmin4.wsgi

ErrorLog /var/log/apache2/pg-error_log
CustomLog /var/log/apache2/pg-access_log combined

<Directory /opt/pip/lib/python3.6/site-packages/pgadmin4>
WSGIProcessGroup pgadmin
WSGIApplicationGroup %{GLOBAL}
Require all granted
</Directory>
</VirtualHost>
```

**Comment by ohemorange** [comment]
`pip` is not our officially supported installation method. Can you try installing certbot using [our snap instructions](https://certbot.eff.org/lets-encrypt/snap-apache) and let us know if the problem persists?

**Comment by DevDorrejo** [comment]
> `pip` is not our officially supported installation method. Can you try installing certbot using [our snap instructions](https://certbot.eff.org/lets-encrypt/snap-apache) and let us know if the problem persists?

Hello, thank you for the fast reply, but i found the issue and the only-right solution for this.

the problem when redirecting to https is, that the firts process :80 is running and on WSGI can't be a duplicate process name, so the solucion is:

on this line:

WSGIDaemonProcess pgadmin processes=1 threads=25 python-home=/opt/pip 

do a search for the name of the process "pgadmin"

and on the new vhost -le-ssl.conf

change the name for pgadmin-ssl

add the ssl on the ssl vhost is the solution.

**Comment by alexzorin** [comment]
I believe this is also related to https://github.com/certbot/certbot/issues/4797, where it should consider `WSGIDaemonProcess` with an identical identifier duplicate.

I am glad to see that you found a way to get it working.

**Comment by DevDorrejo** [comment]
> I believe this is also related to #4797, where it should consider `WSGIDaemonProcess` with an identical identifier duplicate.
> 
> I am glad to see that you found a way to get it working.

it is possible instead of creating a new vhost -le-ssl, the original one be modified, i had found on internet examples of having 2 <virtualhot> the first one will be the :80 that that will content the redirect of the https and on the same file the <virtualhost> with :443, that way will not be more files and maybe will be less issues

**Comment by RoboSparrow** [comment]
I'm late to the party but leave this here in case someone needs it. A possible solution to prevent duplication is to wrap the Daemon config into an `<IfDefine>` directive

```
#... set up shared vars (optional)

Define wsgi_daemon "my_process"
Define path_django "/path/to/django/app"

#... inside vhost

<IfDefine !wsgi_init>
    WSGIDaemonProcess ${wsgi_daemon} python-path=${path_django}
    WSGIProcessGroup ${wsgi_daemon}
    Define wsgi_init 1
</IfDefine>
```

**Comment by DevDorrejo** [comment]
> I'm late to the party but leave this here in case someone needs it. A possible solution to prevent duplication is to wrap the Daemon config into an `<IfDefine>` directive
> 
> ```
> #... set up shared vars (optional)
> 
> Define wsgi_daemon "my_process"
> Define path_django "/path/to/django/app"
> 
> #... inside vhost
> <VirtualHost *:80> # replace with your condition
>     # ...
>     <IfDefine !wsgi_init>
>         WSGIDaemonProcess ${wsgi_daemon} python-path=${path_django}
>         WSGIProcessGroup ${wsgi_daemon}
>         Define wsgi_init 1
>     </IfDefine>
>    # ...
> </VirtualHost>
> ```

wow, nice thanks

**Comment by MichaelClerx** [comment]
> <IfDefine !wsgi_init>
>         WSGIDaemonProcess ${wsgi_daemon} python-path=${path_django}
>         WSGIProcessGroup ${wsgi_daemon}
>         Define wsgi_init 1
>     </IfDefine>

I just had to do this to make certbot work. Used a newly installed `snap` version of certbot
