### ISSUE TITLE
--dry-run shouldn't be invoking the installer

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8375]
## My operating system is (include version):
Ubuntu 20.04.1

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
snap

## I ran this command and it produced this output:
    certbot run -i apache --webroot -w /var/www/html  -d example.com
    certbot renew --dry-run

## Certbot's behavior differed from what I expected because:
Since this is a dry-run renewal and the Apache authenticator is not used, there is no reason that Certbot should interact with Apache.

Instead, Certbot performs a graceful Apache restart at the end of the dry-run renewal. This can be verified by watching the Apache error log.

It shouldn't do this.

`certbot._internal.main.renew_cert` should be modifying its behavior based on whether it's a dry-run. 

This code dates all the way back to https://github.com/certbot/certbot/commit/21fe41c53b6cb8847680715497fef54614076ff2 so I am cautiously guessing that it's just an oversight that nobody ever noticed.

**Comment by ohemorange** [comment]
Closed by #8852.
