### ISSUE TITLE
Write macOS dev instructions

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8385]
https://github.com/certbot/certbot/blob/cb916a068228e7f2e49d1edac8e096dbde2f59ee/certbot/docs/contributing.rst#running-a-local-copy-of-the-client recommends that macOS users use our development Docker setup. I don't do that and setting up a Certbot development environment on macOS isn't that hard.

I didn't verify this and I may be forgetting some steps, but it should be as simple as installing Homebrew, running `brew install augeas python`, and then following our instructions like normal. (If someone wants to use a different copy of Python, they may hit some issues with [System Integrity Protection](https://support.apple.com/en-us/HT204899) which I worked around by creating symlinks to Augeas under `~/lib`, but using Homebrew is easy and works so I think we should recommend that as a starting point.)

I haven't seen any demand for this, but if there becomes some or we find the time in the future, I think it'd be good to do this. I also think this is a decent initial issue for someone on macOS and I can try to help if people hit issues.

**Comment by aeturnum** [comment]
I'm developing on os x and modifying cerbot was quite straightforward without using docker, but I'm not sure that the work I'm done reflects the full range of certbot development tasks. It might be useful to add a list of tasks that should be runnable under os x to the bug description (getting the dev copy of certbot on `PATH`, running the unit tests, the integration tests, etc).

**Comment by bmw** [comment]
Good idea. Some if not all of the items on that list would be:

- [ ] certbot and development tools like ipdb, ipython, pytest, and tox are available in the shell where you ran the command after activating the virtual environment described at https://certbot.eff.org/docs/contributing.html#running-a-local-copy-of-the-client.
- [ ] You can run unit tests using the different approaches documented at https://certbot.eff.org/docs/contributing.html#running-automated-unit-tests and most importantly `tox --skip-missing-interpreters` works.
- [ ] You can build the documentation as described at https://certbot.eff.org/docs/contributing.html#updating-the-documentation.

One problem is I think running either manual or automated integration tests as described under https://certbot.eff.org/docs/contributing.html#testing will not currently work on macOS. Fixing that is tracked by https://github.com/certbot/certbot/issues/6959 but for now, I'd recommend adding a note about this to the docs and suggesting people just open PRs once other tests pass to let CI run it for them.

I think all/most people working on Certbot regularly very rarely run these tests locally anyway and just let CI do it. That's what I do personally.
