### ISSUE TITLE
Remove or update tools/venv.py

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8387]
Once we drop Python 2 support, we don't need `tools/venv.py` anymore. We could just delete it or we could make it use Python 3. If we did the latter, we could either keep `tools/venv3.py` working too or move everything to `tools/venv.py`. We may also want to consider renaming the Python 3 venv to just `venv`.

The only strong opinion I have on any of this is I think we shouldn't keep our Python 2 venv creation script around. If we're changing things in a way that affects Certbot devs, I think we should check in with them about the changes here before they land.

**Comment by bmw** [comment]
My preference is to go with the thing that is the simplest/cleanest in the long term which I think is to remove `tools/venv3.py`, make `tools/venv.py` use Python 3, and use the name `venv` for the virtual environment instead of `venv3`.

@adferrand, @alexzorin, or @ohemorange: Do any of you have a problem with this change which breaks the convention we've had for years and you may be used to?

**Comment by adferrand** [comment]
Given that `venv.py` is a development tool, it is very likely that any contributor to the project will be fine with a script moving from Python 2 to Python 3 one year after the official deprecation of Python 2. On top of it the behavior of this script to always recreate an entirely new virtual environment at each run will ease the transition.

I agree with the plan to have `venv.py` only and that it creates Python 3 virtual environments.

**Comment by ohemorange** [comment]
No opinion.

**Comment by bmw** [comment]
Thanks. I just wanted to avoid people being surprised/frustrated when this suddenly changes. I'll try to remember to post a message in Mattermost when the PR for this lands.
