### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8389]
This is blocked on https://github.com/certbot/certbot/issues/8388 having been resolved and included in a release.

Once that happens though, we should drop Python 2 support by

- [ ] Removing Python 2 from the [classifiers in setup.py](https://github.com/certbot/certbot/blob/8cb57566c0be9fbed6d86316a0afb18e86d9f481/setup.py#L137) for each package.
- [ ] Update the [python_requires value](https://github.com/certbot/certbot/blob/8cb57566c0be9fbed6d86316a0afb18e86d9f481/setup.py#L125) in each packages setup.py file to exclude Python 2.
- [ ] Update any Azure tests using Python 2 to a newer version of Python or delete the test entirely.
- [ ] Remove the deprecation warnings and pytest changes to ignore them added to fix #8388 
- [ ] Update any files such as [contributing.rst](https://github.com/certbot/certbot/blob/8cb57566c0be9fbed6d86316a0afb18e86d9f481/docs/contributing.rst#notes-on-os-dependencies) or [install.rst](https://github.com/certbot/certbot/blob/8cb57566c0be9fbed6d86316a0afb18e86d9f481/docs/install.rst#id16) to not claim support for Python 2.
- [ ] Pinning an exact version of `dnspython`. See https://github.com/certbot/certbot/pull/8460#discussion_r526477723.

This list may be incomplete. I copied it from https://github.com/certbot/certbot/issues/8150, but we may have more code relying on Python 2 that we have to clean up.

**Comment by atombrella** [comment]
I think this should follow a small update in the style guide to avoid `assertTrue` and `assertFalse` when better `assert`s exist. You can see this list: https://docs.python.org/3/library/unittest.html#unittest.TestCase.debug (it's just a fragment). It's obviously a huge task to replace all of the existing asserts, but any new assert should preferably be specific.

https://pypi.org/project/flake8-assertive/ lists much better alternatives for common patterns.

The problem with `assertTrue` is that `assertTrue(any positive value)` will pass, but you probably want to check if it's a boolean with a true value.

**Comment by bmw** [comment]
There are pieces of this which can be done in parallel with https://github.com/certbot/certbot/issues/8580, however, I expect that issue to be a bit of work and I think it should be resolved before we can fully close this issue.
