### ISSUE TITLE
challenge bug

### ISSUE THREAD

**Issue by gkissand** [certbot/certbot#8402]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

**Comment by gkissand** [comment]
OS "Ubuntu 18.04.5 LTS"
installed certbot from deb http://ppa.launchpad.net/certbot/certbot/ubuntu bionic main version 0.31.0-1+ubuntu18.04.1+certbot+1
I host http://www.ecovillas.gr/ and https://www.ecovillas.gr/ recently moved to a new server
in virtualhost for http://www.ecovillas.gr/  I had these lines
        RewriteEngine Off
        RewriteCond %{HTTPS} off
        RewriteRule (.*) https://%{SERVER_NAME}/$1 [R,L]
When I tried to update the cert, certbot was including the temporary file that includes
writing a pre config file with text:
         RewriteEngine on
        RewriteRule ^/\.well-known/acme-challenge/([A-Za-z0-9-_=]+)$ /var/lib/letsencrypt/http_challenges/$1 [END]
AFTER the configuration above
As result RewriteRule was not applied and cert update was failing
After I commented out my configuration (RewriteEngine Off) everything worked fine

A check must be included if there is a "RewriteEngine Off" in http virtualhost or in global apache config

**Comment by alexzorin** [comment]
Hi @gkissand,

This seems to be the same issue as https://github.com/certbot/certbot/issues/8367. Does that sound right to you?

**Comment by gkissand** [comment]
Hi @alexzorin 
Yes it's the same issue. I'll close mine as duplicate

**Comment by gkissand** [comment]
Duplicate with https://github.com/certbot/certbot/issues/8367

**Comment by JialuZhang** [comment]
@gkissand 

This setting “RewriteEngine Off” alone is a misconfiguration and adding it to your system will not change any system behavior. 

More importantly, the default value of “RewriteEngine" is already an "off", so adding “RewriteEngine Off" is quite unnecessary and it may cause confusion to users.

Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule"
}
```
