### ISSUE TITLE
Write instructions for installing Certbot from source

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8422]
This issue is intended for https://github.com/certbot/website.

While installing the Certbot snaps or Docker images provides a way for most people to get an up-to-date version of Certbot directly from us, that's not an option everywhere. If a person doesn't use those options, what should we tell them?

The best option I think we have right now is essentially telling them how to "install Certbot from source". This option will be much more manual work than something like snaps, but it's certainly possible. (If someone has an idea they like better, by all means propose it.)

Exactly what these instructions should look like is a bit of an open question, but to throw some ideas out there as a starting point:

* I would start with the simplest reasonable version of instructions like this and we can expand on it as we need/want to.
* I think we probably want to make it clear the level of support we'll provide for this use case. If something like `cryptopgraphy` fails to compile on an obscure or heavily customized system, how much time are we really able to invest in helping them work through this?
* The user will need at least Python 3.6+, packages for compiling `cryptography` if they're on a non-x86_64 system, and Augeas for the Apache plugin. See https://certbot.eff.org/docs/contributing.html#running-a-local-copy-of-the-client.
* We should make sure the instructions do not cause conflicts with other Python packages on the user's system (e.g. no `sudo pip install`).
* How does the user install plugins?
* Consider using something like [pipx](https://pipxproject.github.io/pipx/) to cleanly install a Certbot executable in a virtual environment. My biggest concern here personally is how annoying is it to get plugins in that same virtual environment and update everything in the future? Is that headache worth it?
* In the future, I think we may want to offer a requirements/constraints file to pin our dependencies to exact versions, but I'd personally leave this out for now. We test with many versions of our dependencies, including [the latest offered on PyPI](https://github.com/certbot/certbot/blob/e570e8ad3230ed5ce24191cde9bbbc6d2a54b630/.azure-pipelines/templates/jobs/extended-tests-jobs.yml#L17-L20), every night.
* How should the user update their Certbot installation? This can maybe be left out of the initial version.

If someone other than me ends up working on this, I'm happy to help brainstorm about all this.

**Comment by ohemorange** [comment]
We should clean this circular reference up when we finish these instructions: https://github.com/certbot/website/issues/667

**Comment by nfcopier** [comment]
Very much yes, please.

I've been bashing my head against the desk trying to figure out how to run certbot on Amazon Lightsail. The issue is that Amazon's latest custom Linux distro, Amazon Linux 2, doesn't support snapd. For now, just to save myself some more headache, I will likely be switching to their Ubuntu distro.

**Comment by adferrand** [comment]
Here is my proposition draft using pipx: https://docs.google.com/document/d/1Xwbq_PGwBNbRPw225n3RNx47kLJ0SqKnGqeoFiSE6XM/edit?usp=sharing

**Comment by bmw** [comment]
Assigning Erica based on the conversation on the call, but if that changes for some reason, by all means unassign yourself.

**Comment by ohemorange** [comment]
Started drafting a version of this that uses virtualenv, viewable here: https://docs.google.com/document/d/1H4n_LNr4QSV12AK6dNB-rglz2nPpBurs0jqqB9wmUPc/edit?usp=sharing

**Comment by Tectract** [comment]
This is now critically, critically important to some of us who still have systems running on python2.7, as they have just been deprecated.

Any instructions or help on upgrading certbot and certbot-auto to use python3 by default would be much appreciated!

**Comment by ohemorange** [comment]
@Tectract what system are you on? can you use the suggested certbot installation method for that system at certbot.eff.org?

**Comment by Tectract** [comment]
Thanks! I am still running some servers on Linux Mint 17, based on Ubuntu14.04. The reason we haven't upgraded to a systemd-based operating system is described in detail [here.](https://ungleich.ch/en-us/cms/blog/2017/12/10/the-importance-of-devuan/). I need to move everthing to Devuan but we just haven't had time at my startup company to allocate the resources for that, yet.

Certbot is still currently running on my servers, I did succesfully renew a cert yesterday no problem, but I just got a deprecation notice that it is EOL, sadly. This OS did ship with python3.4 so... I'm honestly not 100% sure I understand the problem. Can't it just detect python3.4, and use that now? Can't I just install python3.6/3.7 and just point it there? Has apache config file format changed or something?

If you guys are willing to continue supporting my OS via some sort of --support-deprecated flag or whatever, I'd be willing to make a gitpay donation to the team :)

Cheers!

**Comment by ohemorange** [comment]
Oh, I see. No need to be overly worried -- we're not going to make certbot stop working on your system. You just won't be getting more updates, since our latest versions won't necessarily work on deprecated systems. If you feel like testing out the new install, you can check out either of the draft installation instructions above, but the easiest thing is probably to just upgrade your entire system when you get a chance and install via snap on that system.

**Comment by ohemorange** [comment]
Ok, I'm actually pretty happy with the draft of these instructions, and would love review/discussion before migrating to the website.

**Comment by bmw** [comment]
I added a few minor comments/suggestions, but I agree at a high level that it looks good!

**Comment by Tectract** [comment]
So if I run certbot under a virtual env, it will still interact with my apache installation that is not in the virtual env? I'm not really experienced with venv, thanks for this help! It should be linked to the README when it's finalized please :)

**Comment by Tectract** [comment]
Is there a reason certbot can't just check for python3.6 and just use it by default if it's available?

**Comment by ohemorange** [comment]
Started migrating these instructions to the website at https://github.com/certbot/website/pull/698

**Comment by kallisti5** [comment]
snapd as a hard requirement for some python scripts is pretty horrid.  As an example, 1GiB is plenty to run a small + quick webserver with nginx and certbot.  Now per the certbot site I have to install an entire package management subsystem / snapd... for some python scripts.

Come on folks.

**Comment by Tectract** [comment]
Oh man, I'm never *ever* planning to use snapd. Please give us another option.

**Comment by ohemorange** [comment]
@Tectract, that is in fact the stated goal of this precise issue.

**Comment by bmw** [comment]
These instructions are live now at https://certbot.eff.org/lets-encrypt/pip-other.

**Comment by Tectract** [comment]
Hey can someone answer my questions about this PR? 

1. Why can't Certbot simply use python3.6 if it is available. Why is a virtual env necessary?

2. If installed under a virtual env, will certbot interact normally with my apache installation that is not installed under the virtual env?

Thanks!

**Comment by adferrand** [comment]
The virtual environment isolates the python dependencies required by certbot to run, so that they are not installed globally where they could mess up with you OS python packages.

Certbot will behave in this case exactly as expected against your Apache installation.

**Comment by dylode** [comment]
> These instructions are live now at https://certbot.eff.org/lets-encrypt/pip-other.

**oops! (404)
Page not found

**
