### ISSUE TITLE
Multi-domain certificate will not renew on certbot renew

### ISSUE THREAD

**Issue by AuspeXeu** [certbot/certbot#8423]
I am creating a certificate like this

```
certbot certonly --webroot -w /var/www/certbot \
    --email support@example.com \
    --expand \
    -d domain1.com,domain2.com,domain3.com \
    --rsa-key-size 4096 \
    --agree-tos \
    --no-eff-email
```
However, subsequent `certbot renew` runs do not renew this multi domain certificate it seems?

**Comment by ohemorange** [comment]
Hey @AuspeXeu! Looks like this is a support request rather than a bug. Please first try asking for help at https://community.letsencrypt.org/. There is a much larger community there of people familiar with the project who will be able to more quickly answer your questions.
