### ISSUE TITLE
Upgrade the pinned version of mypy

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8425]
I tried doing this as part of https://github.com/certbot/certbot/issues/8134 and hit ~400 new errors when checking our code with mypy.

This can be reduced to ~125 errors (many of which are repeated errors about the same code), by [disabling mypy's strict optional checking](https://mypy.readthedocs.io/en/stable/kinds_of_types.html#no-strict-optional). This check became enabled by default since we last upgraded `mypy`. I think we probably should consider enabling this check, but I would recommend disabling it while working on this issue and creating a separate issue to track maybe enabling it and fixing those errors.

**Comment by bmw** [comment]
@adferrand, I think we may want to do this early on in our mypy work. What do you think?

**Comment by adferrand** [comment]
Indeed. I believe that between current version of mypy + more annotations dynamically computed vs newer version of mypy with better capabilities in terms of type inference + more type stubs, a lot of new errors detected are shared.

Going to the most up-to-date mypy first, given the more up-to-date stubs, may also provide a better accuracy when new annotations are extracted through static analysis or dynamic one.
