### ISSUE TITLE
Switch to Python 3 style type annotations

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8427]
Once we've dropped Python 2 support which is tracked by https://github.com/certbot/certbot/issues/8389, we can use Python 3 style type annotations which makes the type annotations real syntax of the language rather than comments. I personally think this is nicer and may make `pylint` stop saying our `typing` imports are unused.

This issue is just to look into doing this. One outcome could be a PR implementing this, but another could just be a comment describing why this isn't worth it. I'd recommend checking if there are tools we can use to convert our code to the new syntax automatically.

**Comment by adferrand** [comment]
Like https://github.com/ilevkivskyi/com2ann?

**Comment by bmw** [comment]
Exactly like that :smile:

I'm not familiar with that tool or any others that do it, but I'd be surprised if something didn't exist.

**Comment by adferrand** [comment]
Pycharm also has this capability: https://www.jetbrains.com/help/pycharm/type-hinting-in-product.html#convert-comment

**Comment by bmw** [comment]
This should also be done on the `josepy` repo.

**Comment by bmw** [comment]
Adrien said he was planning to take a look at this. @adferrand, if this changes, go ahead and unassigned yourself.
