### ISSUE TITLE
Deprecate Apache 2.2 support

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8462]
With [CentOS 6 reaching it's EOL at the end of November](https://wiki.centos.org/About/Product), I think we can deprecate Apache 2.2 support. No non-EOL'd versions of CentOS, Debian, or Ubuntu still package Apache 2.2 and it is different enough from Apache 2.4 that removing support for it is good from a maintenance perspective.

This issue is just tracking printing a warning when Apache 2.2 is used while https://github.com/certbot/certbot/issues/8461 is tracking actually removing support in a new major version of Certbot.

**Comment by Tectract** [comment]
Please please don't deprecate Apache2.2 support. There are a TON of people still using it, including me.
