### ISSUE TITLE
Upgrading certbot to latest snap causes DigitalOcean DNS renewals to fail

### ISSUE THREAD

**Issue by Niek** [certbot/certbot#8466]
## My operating system is (include version):
Ubuntu 18.10

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Latest snap package

## I ran this command and it produced this output:
```bash
$ certbot renew --dry-run
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/domain.com.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Renewal configuration file /etc/letsencrypt/renewal/domain.com.conf (cert: domain.com) produced an unexpected error: 'Namespace' object has no attribute 'dns_digitalocean_credentials'. Skipping.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)

No renewals were attempted.

Additionally, the following renewal configurations were invalid:
  /etc/letsencrypt/renewal/domain.com.conf (parsefail)
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates above have not been saved.)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
0 renew failure(s), 1 parse failure(s)
```

## Certbot's behavior differed from what I expected because:
It worked fine before (old version was 0.x). I upgraded to the latest snap package and DigitalOcean DNS renewals no longer work.

I also seem to be missing the ``dns-digitalocean-credentials`` flag as documented in https://certbot-dns-digitalocean.readthedocs.io/en/stable/:
```bash
$ certbot --help certonly | grep digital -A1
  --dns-digitalocean    Obtain certificates using a DNS TXT record (if you are
                        using DigitalOcean for DNS). (default: False)
```

**Comment by bmw** [comment]
In both the Certbot snaps and OS packages which I assume you were using previously, the DigitalOcean plugin is not included by default and it is in a separate snap/package. I don't think you have the certbot-dns-digitalocean snap installed.

To do install it, run
```
sudo snap set certbot trust-plugin-with-root=ok
sudo snap install certbot-dns-digitalocean
```
Afterwards, commands like `certbot plugins` should list the DigitalOcean plugin and assuming there are not other problems with your setup, `certbot renew --dry-run` should work.

If you need additional help getting this set up, I recommend posting to https://community.letsencrypt.org where there is a much larger group of people who are able to help with things like this. I hope that helps!

**Comment by Niek** [comment]
Thanks, that fixed it indeed!

The confusion came from that certbot lists the `--dns-digitalocean` parameter even though it's not installed. It would also be helpful if the [plugin documentation](https://certbot-dns-digitalocean.readthedocs.io/en/stable/) would mention the need to install the plugin first.

**Comment by bmw** [comment]
Thanks for following up with the suggestions. I think https://github.com/certbot/certbot/issues/1549 is tracking removing `--dns-digitalocean` from core Certbot and I created https://github.com/certbot/certbot/issues/8470 to track mentioning the fact the plugins are packaged separately in the plugin docs.
