### ISSUE TITLE
Future work around ECDSA certificates

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8468]
This is a quick, catch all issue to track things under the "Future work" section in the [ECDSA design doc](https://docs.google.com/document/d/18pr4F4SVim-bSR6izNV5ZYwolnvitTvmP6gqElDdZPU/edit?usp=sharing).

**Comment by certbotissue** [comment]
You could start by stop lying to people about ECDSA. The American EFF pretends they issue ECDSA certificates but in reality they only issuing RSA certificates: https://github.com/certbot/certbot/issues/8529#issuecomment-743910705 Nothing surprise me, Americans lost they goddamn mind. Fuck America I hope all of you get bombed soon.

**Comment by certbotissue** [comment]
Signature Algorithm: sha256WithRSAEncryption is for you ECDSA you retard?

**Comment by certbotissue** [comment]
I getting close to declare EFF an American terrorist organization if you keep telling me that sha256WithRSAEncryption is ECDSA! Stop fcking lie to the public, you spy on everyone and get money from the NSA for your public CA. Is some Department of Defense program to run a public CA from America? I get it why you don't want to implement EdDSA.. You only implemented UNSAFE NIST curves approved by the NSA.

https://safecurves.cr.yp.to/ by Bernstein clearly warning about all curves you pushing for in 2021..

**Comment by certbotissue** [comment]
I was friendly initially but I getting close to declare EFF an American terrorist organization if you keep telling me that **sha256WithRSAEncryption** is ECDSA! Stop fcking lie to the public, you spy on everyone and get money from the NSA for your public CA. Is some **Department of Defense** program to run a public CA from America? I get it why you don't want to implement EdDSA.. You only implemented **UNSAFE** NIST curves **approved by the NSA**. 

https://safecurves.cr.yp.to/ by Bernstein clearly warning about all curves you pushing for in 2021..

**Comment by certbotissue** [comment]
I getting close to declare EFF an American terrorist organization if you keep telling me that **sha256WithRSAEncryption** is ECDSA! Stop fcking lie to the public, you spy on everyone and get money from the NSA for your public CA. Is some **Department of Defense** program to run a public CA from America? I get it why you don't want to implement EdDSA.. You only implemented **UNSAFE** NIST curves **approved by the NSA**. 

https://safecurves.cr.yp.to/ by Bernstein clearly warning about all curves you pushing for in 2021..

**Comment by certbotissue** [comment]
Come and tell me Mr. @bmw since when RSA keys become ECDSA? How much money you get from NSA for doing this?

**Comment by lubo** [comment]
@certbotissue Certificate public key algorithm and certificate signature algorithm are two separate things. You can use ECDSA key pair just fine, but currently, Let's Encrypt provides RSA signatures only. See [Upcoming Features
](https://letsencrypt.org/upcoming-features/#ecdsa-root-and-intermediates) for the rationale. Also, there's this thing called CA/Browser Forum, so there are lots of things that Let's Encrypt and EFF aren't single-handedly responsible for. I'm sorry, but you seem confused. It might be a good idea to tone down on the rhetoric and to read up on these things. I'd also like to encourage you to be mindful of your fellow users, as they're being spammed by your baseless claims in multiple threads just like me.

**Comment by certbotissue** [comment]
Whats the point to claim ECDSA is implemented when it is not! The whole thing is about speed and because it is still an ECDSA certificate there is absolutely nothing changed. Baseless claims? Show me any other curves they implemented than those which approved by the NSA. They did not implemented anything which is recommended by professional cryptographers and you know why? Because they are Americans working closely with the NSA. 

Everywhere where Americans who up there is terror and blood so tell me that EFF is fully independently running a CA in San Francisco from the Pentagon.

The main point is to switch RSA to a smaller ECDSA but you see that is not the case here, they are liar fascists like just any other American. 

I going to massacre Americans just as they massacred millions in the middle east.

**Comment by HITLER-is-a-US-citizen** [comment]
You in Slovakia can't stop sucking Hungarian dicks? Orban did fuck your ass already? LOL. Slovakia don't even have History you are literally Hungarian sucking Orban's dick... @lubo

**Comment by bmw** [comment]
Per our [code of conduct](https://www.eff.org/pages/eppcode), repeated personal (and misguided) attacks against the project and the community are not tolerated.

I'm going to clean up our GitHub a bit so your comment may look out of context, but thanks a lot for taking the time to politely provide the correct explanation @lubo.

**Comment by zoracon** [comment]
Just referencing issues that are related as I close them so they won't be lost:

- #2209

**Comment by bmw** [comment]
I think this is now tracked by the less verbose https://github.com/certbot/certbot/issues/9185 and can be closed.
