### ISSUE TITLE
Flag that DNS plugins are distributed separately from Certbot

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8470]
https://github.com/certbot/certbot/issues/8466#issuecomment-730593901 pointed out that if you land on our DNS plugin docs (as opposed to something like https://certbot.eff.org/instructions), it does not point out that the DNS plugins are distributed separately from Certbot and need to be installed.

I think adding something about this near the top of the docs for each DNS plugin should be easy to do and make sense.

**Comment by ooojpeg** [comment]
I could look at this, @bmw in your opinion would it be enough to add they are distributed seperately or additionally add links to something like: https://snapcraft.io/install/certbot-dns-digitalocean/ubuntu?
