### ISSUE TITLE
[wish] in case of errors, show again log path

### ISSUE THREAD

**Issue by zeroheure** [certbot/certbot#8471]
Certbot print "Saving debug log" message at the beginning. It would be useful to print it again at the end when something goes wrong, for user don't forget to have a look into logs.

**Comment by alexzorin** [comment]
Hi @zeroheure,

We have a similar change planned already. 

When an error occurs, we will show: the error message, path to the debug log, and link to the community forums, together at the end of the output.

**Comment by bmw** [comment]
Thanks for grabbing this Alex. I didn't know about the planned change.

**Comment by ohemorange** [comment]
Closed by #8852.
