### ISSUE TITLE
DNS-01-related: Slow down verification after DNS challenges

### ISSUE THREAD

**Issue by noseshimself** [certbot/certbot#8474]
## My operating system is (include version):
Any OS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
installed by apt

## I ran this command and it produced this output:
root@tool:/etc/letsencrypt# /usr/bin/certbot certonly  --dry-run --non-interactive --manual --preferred-challenges dns --manual-auth-hook /etc/letsencrypt/bin/manual-auth-hook.sh --manual-cleanup-hook /etc/letsencrypt/bin/manual-cleanup-hook.sh -d domain1 -d domain2 ... -d domainn
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for domain1
dns-01 challenge for domain2
[...]
dns-01 challenge for domainn
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. domain1 (dns-01): urn:ietf:params:acme:error:dns :: During secondary validation: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.zner.net - check that a DNS record exists for this domain
[...]

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: domain1
   Type:   None
   Detail: During secondary validation: DNS problem: NXDOMAIN looking
   up TXT for _acme-challenge.domain1 - check that a DNS record
   exists for this domain

## Certbot's behavior differed from what I expected because:
Looking at the named-update logs shows that the names are registered within 2 seconds and removal starts 5 seconds after the last registration. The name lookup packets are arriving at the public-facing servers before a full zone update can be performed.

Either add a default enforced break between creation of DNS records and requesting verification or make the thing command line configurable. A crude hack consisting of adding a time.sleep (3) as last line to _perform_achall_with_script in manual.py is solving my local problem

There must have been some changes in letstencrypt infrastructure in the last few days; it has been working perfectly a few days ago.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
DNS-01 -- nginx is irrelevant.

**Comment by alexzorin** [comment]
The approach so far has been for users to implement any required delays directly into the `manual` authentication hook. e.g. Throw a `sleep 3` in there.

The actual DNS plugins [like `certbot-dns-rfc2136`](https://certbot-dns-rfc2136.readthedocs.io/en/latest/) do have a built-in default and configurable delay. These defaults vary by provider and reflect the propagation times of each provider.

The `manual` plugin on the other hand, does not have this built-in delay. This seems appropriate because hooks perform some arbitrary task with unknown propagation characteristics. The hook has the best knowledge of what delays it requires.

Hypothetically one could add `--manual-auth-propagation-seconds`, but I'm not convinced of what benefit it would have over the status quo: hardcoding the delay into the hook itself. 

What do you think about that?

**Comment by noseshimself** [comment]
> The actual DNS plugins like certbot-dns-rfc2136 do have a built-in default and configurable delay. These defaults vary by provider and reflect the propagation times of each provider.

There is a reason I did not want to use it -- at least with bind using text-based zone files dynamic DNS updates render the zone files uneditable so I'm using CNAME entries in static zone files pointing to a zone (acme-z.one was still available at that time) and update that zone. This is rendering only one zone unreadable.

> The manual plugin on the other hand, does not have this built-in delay. This seems appropriate because hooks perform some arbitrary task with unknown propagation characteristics. The hook has the best knowledge of what delays it requires.

> Additionally, since Certbot 1.4.0, you may avoid excessive sleeps for multi-domain certificates. Check $CERTBOT_REMAINING_CHALLENGES in your --manual-auth-hook, and only perform the delay once it reaches 0.

I didn't see that one (the documentation is a bit sparse) so I could of course use  it easily (which I'll do next). Still: The hook doesn't know anything about the inner workings of the mechanism it is connecting too, either. It is sending some kind of update (whatever the mechanism being triggered might be) but doesn't know much more about the service behind that.

> Hypothetically one could add --manual-auth-propagation-seconds, but I'm not convinced of what benefit it would have over the status quo: hardcoding the delay into the hook itself.

Another war story in this: I always hated the specialized registers of the 6502 and really enjoyed the 68000. If it is possible to reach some kind of symmetry I always go for it and I like having all configurable parameters in one place.

To be honest: I was wondering why there were so many --propagation*seconds option instead of one global "--delay-verification" option that would make certbot take a break between updating authentication and requesting verification in a central location... It might make things easier if you add further authentication/verification methods.
