### ISSUE TITLE
Remove the hyphen from the acceptable character set for _acme-challenge TXT records.

### ISSUE THREAD

**Issue by Dygear** [certbot/certbot#8477]
## My operating system is (include version):
Client: macOS 11.0.1 with Terminal and SSH into ...
Server: Ubuntu 20.04 LTS running nginx.

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS Package Manager.

## I ran this command and it produced this output:
`certbot certonly --manual --preferred-challenges=dns  --email Mark@MimoCAD.io --server https://acme-v02.api.letsencrypt.org/directory --agree-tos -d mimocad.io -d *.mimocad.io -d stonybrookems.io -d *.stonybrookems.io -d stonybrookems.com -d *.stonybrookems.com -d stonybrookems.net -d *.stonybrookems.net -d stonybrookems.org -d *.stonybrookems.org -d wlvac.com -d *.wlvac.com -d wlvac.net -d *.wlvac.net -d wlvac.org -d *.wlvac.org -d wlvacems.com -d *.wlvacems.com -d wlvacems.net -d *.wlvacems.net -d wlvacems.org -d *.wlvacems.org -d mimosdr.com -d *.mimosdr.com -d mimosdr.net -d *.mimosdr.net -d mimosdr.org -d *.mimosdr.org`

## Certbot's behavior differed from what I expected because:
```
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Please deploy a DNS TXT record under the name
_acme-challenge.mimocad.io with the following value:

6-K6v7VjtVpGhJk4d6Zx8qxsg6JFUZbGnnr-bDpKpSc

Before continuing, verify the record is deployed.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Press Enter to Continue
```

As you can see the requested deploy `_acme-challenge` body includes a hyphen character `6-K6v7VjtVpGhJk4d6Zx8qxsg6JFUZbGnnr-bDpKpSc`. This is the current behavior that I would like to change.

## Here is my issue.

As you can see I'm configuring a large number of domains at once. What I would like to do is remove hyphens (`-`) from the acceptable character list. This is allow people to simply double click on the string to copy it's entire length. Currently when I double click on a string within macOS using Terminal it will stop it's copy at the boundary of the string (A space for example) or in this case, at the undesirable to do so, hyphen character as well. This is a usability issue as it is expected behavior that it should copy the whole string to make it less error prone when copying over to a DNS server record.

## My feature request.

Simply remove the hyphen (`-`) from the acceptable character list for this type of TXT record. It will give people like me an easier time of it when moving a large number of domains.

**Comment by ohemorange** [comment]
This isn't caused by Certbot, it's provided by Let's Encrypt as defined by the ACME spec: https://tools.ietf.org/html/rfc8555#section-8.4

There's a mailing list for the spec that you can find on the IETF site if you'd like to take it up there. It's a good idea, I'd suggest you do so!

**Comment by Dygear** [comment]
Subscribed and I'll shoot an email off to the acme@ietf.org mailing list. Thanks for pointing me in the correct direction.

**Comment by Dygear** [comment]
Their suggestion is that the spec shouldn't really be changed, but the tool can reject and re-roll the token until it doesn't contain hyphens. On average they expect that to be around two rolls if the first already did contain it. So I think I'm going to make that pull request once I find out the section of code that I need to modify. Hopefully that will land here.

**Comment by ancarda** [comment]
Perhaps you can create an issue in [letsencrypt/boulder](https://github.com/letsencrypt/boulder)? You might be able to just change the code that generates tokens to never produce a hyphen - that seems cleaner than having the client retry multiple times.
