### ISSUE TITLE
Remove PyOpenSSL dependency

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8492]
I'm creating this issue based on https://github.com/certbot/certbot/issues/1301.

I think doing this would be an API change, but I think just relying on `cryptography` may be possible for us. This reduces our dependencies and I believe the pyca team would still like to deprecate pyopenssl in favor of pure `cryptography` someday.

**Comment by alex** [comment]
If there's specific feature areas pyca/cryptography can grow to allow dropping pyOpenSSL, please let us know!

**Comment by bmw** [comment]
Thanks! We'd have to look, but I'm not aware of any additional features we need. We just have to do/prioritize the work.

**Comment by alex** [comment]
Did this happen, or wontfix?

**Comment by bmw** [comment]
Short answer: wontfix

Long answer: I was closing out issues that I do not currently imagine us getting to anytime soon. This could certainly change in the future though if there's people wanting to do this work or you all are wanting to finally kill off pyopenssl.
