### ISSUE TITLE
Consolidate date/time parsing dependencies

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8493]
We currently depend on pytz, parsedatetime, and pyrfc3339. Do we really need all of these? Can we get by with fewer dependencies here?

**Comment by ekohl** [comment]
pytz is only used for `pytz.UTC` at runtime. Python 3.2 introduced `datetime.timezone.utc` which I think provides the same object. In the tests it's also used for `pytz.timezone('Asia/Shanghai')` (in `certbot/tests/storage_test.py`) which can probably be rewritten as a static offset. The only thing it's testing is that it maintains the offset. It should also be verified that no dependency pulls it in again. For example, pyrfc3339 also depends on it. It should be noted that Python 3.9 introduces `zoneinfo` which will replace the need for pytz, but that's probably far in the future. Backports are available on 3.6-3.8 though.

parsedatetime is only used to parse the `renew_before_expiry` configuration option [here](https://github.com/certbot/certbot/blob/31b5f1310e1fd0331faaa7efbcb8cccdfee93e78/certbot/certbot/_internal/storage.py#L83-L104) via [should_autorenew](https://github.com/certbot/certbot/blob/31b5f1310e1fd0331faaa7efbcb8cccdfee93e78/certbot/certbot/_internal/storage.py#L930-L965).

pyrfc3339 is used to parsing and generating datetime objects from external data (JSON, X509 certs). This looks like a sane dependency. It's small and focused. It should drop its dependency on pytz though.

**Comment by bmw** [comment]
Thanks for looking into that!

**Comment by ekohl** [comment]
> It should drop its dependency on pytz though.

Took a stab at this in https://github.com/kurtraschke/pyRFC3339/pull/15
