### ISSUE TITLE
manual-public-ip-logging-ok deprecation leads to error

### ISSUE THREAD

**Issue by st-h** [certbot/certbot#8495]
I am regularly running Certbot (latest docker image) to obtain new certificates when necessary. Tonight the Certbot command failed, which seems to be related to the deprecation of `manual-public-ip-logging-ok` within version `1.11.0`. Seems like this flag now requires an argument, which it previously did not. This is easy to fix, as it just means to remove the `--manual-public-ip-logging-ok` flag and things run fine again.

```
Use of --manual-public-ip-logging-ok is deprecated.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...
Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: argument --manual-public-ip-logging-ok: expected one argument
```

**Comment by alexzorin** [comment]
Hi @st-h,

Could you please share the exact command which produces this error?

**Comment by st-h** [comment]
This is the command when it failed:
```
certbot certonly --manual --preferred-challenges dns-01 -m $ACME_EMAIL --manual-public-ip-logging-ok --agree-tos --no-bootstrap --non-interactive --manual-auth-hook './src/authenticate.sh' --manual-cleanup-hook './src/cleanup.sh' --deploy-hook './src/habitat.sh' --domains *.$DOMAIN,$DOMAIN --cert-name $DOMAIN --server $ACME_URL
```

This is the log output when getting the docker image.
```
Using docker image sha256:c3703e180159a0e6660a648f890a9ab8bc5317f8a20541fbd52dc656b9a5aee5 for certbot/certbot with digest certbot/certbot@sha256:86264d55274f9c9bcc59572e0394f9bbc84463c0ca0990bbb92d31a7122685b6 ...
```

**Comment by alexzorin** [comment]
I'm still having problems reproducing this.

Here is what I'm trying on the latest Docker release, adapted from your command (just replaced the env variables):

    $ sudo docker run --rm -it certbot/certbot:v1.10.0 certonly --manual --preferred-challenges dns-01 -m test@letsdebug.net --manual-public-ip-logging-ok --agree-tos --no-bootstrap --non-interactive --manual-auth-hook '/bin/true' --manual-cleanup-hook '/bin/true' --deploy-hook '/bin/true' --domains example.org --cert-name example.org --server https://acme-staging-v02.api.letsencrypt.org/directory
    Use of --manual-public-ip-logging-ok is deprecated.
    Saving debug log to /var/log/letsencrypt/letsencrypt.log
    Plugins selected: Authenticator manual, Installer None
    Account registered.
    Requesting a certificate for example.org
    Performing the following challenges:
    dns-01 challenge for example.org
    Running manual-auth-hook command: /bin/true
    Waiting for verification...
    Challenge failed for domain example.org
    dns-01 challenge for example.org
    Cleaning up challenges
    Running manual-cleanup-hook command: /bin/true
    Some challenges have failed.

    IMPORTANT NOTES:
    - The following errors were reported by the server:

      Domain: example.org
      Type:   dns
      Detail: DNS problem: NXDOMAIN looking up TXT for
      _acme-challenge.example.org - check that a DNS record exists for
      this domain

**Comment by st-h** [comment]
@alexzorin sorry, but I currently don't have an idea what might has been causing this then. (I am running this within gitlab CI, and retriggering the failed built produces the same error). Please feel free to close, though. It's fairly easy to fix in case someone has identical issues, so probably not worth the time to dig further.

**Comment by alexzorin** [comment]
I can reproduce it. The key is that the error will only happen if the certificate issuance is successful.

Apparently `storage.new_lineage` eventually triggers reparsing of all of the CLI arguments. `storage.new_lineage` triggers this error in `relevant_values` -> `cli.set_by_cli`:

https://github.com/certbot/certbot/blob/31b5f1310e1fd0331faaa7efbcb8cccdfee93e78/certbot/certbot/_internal/storage.py#L1056

The second reparsing of the CLI arguments is going wrong and somehow it thinks that `nargs=1`. I'm not sure why yet.

**Comment by st-h** [comment]
That's a bit weird. In my case the successful run after the failure did not renew the cert, but prints:
```
certificate not yet due for renewal; no action taken.
```
Just looked it up, the certs have been renewed a week ago. I run Certbot once a day. So, I shouldn't be seeing another renewal today. But probably the outcome of a noop and a renewal is the same in this case.
I'll be happy to re-run the failing build once this is fixed to verify.

**Comment by alexzorin** [comment]
The renewed certificate does get saved, but Certbot crashes while it is saving the renewal parameters file.

**Comment by st-h** [comment]
@alexzorin I am very certain that this hasn't been the case. When Certbot successfully renews a cert, it uploads it to a central storage. The cert then gets distributed to all the nodes that need it. In case Certbot crashes, the whole thing just aborts. But anyway, I suspect that this does not matter at all regarding the cause of this issue.

**Comment by alexzorin** [comment]
>When Certbot successfully renews a cert, it uploads it to a central storage. The cert then gets distributed to all the nodes that need it

Sorry, I should have been more clear. Certbot is crashing before the `--deploy-hook`, but after it has written the updated certificate files to `/etc/letsencrypt/{live,archive}/`. The "Congratulations!" never gets a chance to be printed either.

**Comment by st-h** [comment]
thanks for clarifying. But as Certbot renewed the cert a week ago, it shouldn't be renewing it again today... Even if it crashed after writing the new cert to the file system, the next run of Certbot would not know about that cert, because it would have never been saved to the storage. Each run starts with a clean file system. 

Yet, I don't think that matters much. I am certain when I rerun the failed build it will work fine after the issue with renewal is fixed.
