### ISSUE TITLE
More helpful output from simple_verify

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#850]
Right now simple_verify just returns true or false, which means we can't display to the user a problem description, like "Content-Type header was incorrect." We should change the return value of simple_verify to be None if there are no problems, or a string describing the problem otherwise.

**Comment by kuba** [comment]
Agreed that `simple_verify` could be more helpful. I'm just not sure about this (`None` vs `str`) particular implementation (at least as a long term goal) - `acme` is meant to be dev library, so it should return more machine-meaningful output (maybe some kind of enum or raise well defined exceptions?).

**Comment by jsha** [comment]
Yep, returning an enum or raising an exception with a certain class both sound like nicer ideas. Both cases should have some default message that can easily be displayed to users though.

Part of the reason I think this is especially valuable is that we don't yet have a good way for Boulder to convey information about validation failures to clients, and so simple_verify is the best possibility for catching such problems in a place where it's relatively easy to notify the user. Eventually we do want Boulder to provide more detailed feedback too.

**Comment by RaGaPlanet** [comment]
+1
In the console I only got the feedback "Self-verify of challenge failed."
The log /var/log/letsencrypt/*.log mentioned the HTTP response code "403" Forbidden for fetching the verification file from the web server, which is much better feedback.
Other than the error a hint regarding the logfile might be helpful and what next steps to take (reverify?).

**Comment by kuba** [comment]
Well, as you can see there is already enough information in the logs to pin down the problem: to be precise all but one branches of the code contain logging statements that allow one to recognize the problem, the remaining one branch can be detected by absence of logging messages... :) Of course I'm not saying this is fully satisfactory solution, but at least its severity is not as high as one might expect by reading this bug report.

**Comment by jsha** [comment]
I think this is obsolete and we don't use simple_verify anymore.
