### ISSUE TITLE
Certbot snap is loading plugins from the host

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8502]
To the best of my understanding, we do not want plugins installed by e.g. `pip` to be loaded by snapped Certbot. And that our snap is designed in a way to only load Python code from within.

However, it seems that this does not hold. [Reported on the forum](https://community.letsencrypt.org/t/certbot-dns-plugin-listed-in-certbot-plugins-but-still-not-working/139614/4?u=_az):

1. Install Ubuntu Focal
2. `apt update && apt -y install snapd python3-pip`
3. `snap install --classic certbot`
4. `pip3 install --user certbot-dns-hetzner`

result:

    root@nova-janet:~# certbot plugins
    Saving debug log to /var/log/letsencrypt/letsencrypt.log

    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    ...<snip>

    * dns-hetzner
    Description: Obtain certificates using a DNS TXT record (if you are using
    Hetzner for DNS).
    Interfaces: IAuthenticator, IPlugin
    Entry point: dns-hetzner = certbot_dns_hetzner.dns_hetzner:Authenticator
    ...<snip>

also running `python` from inside `snap run --shell certbot`, one can see that `/root/.local/lib/python3.8/site-packages` is listed in `sys.path`:

    >>> sys.path
    ['', '/snap/certbot/784/usr/lib/python38.zip', '/snap/certbot/784/usr/lib/python3.8', '/snap/certbot/784/usr/lib/python3.8/lib-dynload', '/snap/certbot/784/lib/python3.8/site-packages', '/root/.local/lib/python3.8/site-packages', '/snap/certbot/784/usr/lib/python3/dist-packages']

**Comment by alexzorin** [comment]
@bmw I noticed there's at least 1 user who is under the impression that this is working as intended, and I'm a little worried that not shutting the door on this quickly might lead to pain later on.

My thinking is that we should strip anything outside of `$SNAP/` from `sys.path`? Though I'm not sure whether there's a better/different way to suppress this happening in the Python runtime.

**Comment by bmw** [comment]
Thanks for the ping. I agree we should fix this.

If that user is on the community forum, I think we should make it clear that this is not intended behavior and is a bug.

I think it'd be best if we could take care of this before starting Python. I think it's unlikely to matter in practice, but I otherwise think it's possible packages get used from outside the snap before we have a chance to clean up `sys.path`. To accomplish this, I think we may be able to specify the value of the `PYTHONPATH` environment variable in snapcraft.yaml. See https://docs.python.org/3/library/sys.html#sys.path.

**Comment by alexzorin** [comment]
>I otherwise think it's possible packages get used from outside the snap before we have a chance to clean up sys.path

Good idea.

`PYTHONPATH` doesn't seem to make any difference, but [PEP 370 -- Per user site-packages directory](https://www.python.org/dev/peps/pep-0370/) suggests that this can be suppressed by:

- Setting `PYTHONNOUSERSITE`
- In CPython, `python -s`

It should be easily enough to do that in `snapcraft.yml` with the env variable.

**Comment by bmw** [comment]
Nice find!
