### ISSUE TITLE
certbot-auto marked as deprecated on Debian 10

### ISSUE THREAD

**Issue by SoftCreatR** [certbot/certbot#8507]
## My operating system is (include version):

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

`$ wget https://dl.eff.org/certbot-auto`

## I ran this command and it produced this output:

```
$ ./certbot-auto
Skipping bootstrap because certbot-auto is deprecated on this system.
Your system is not supported by certbot-auto anymore.
Certbot cannot be installed.
Please visit https://certbot.eff.org/ to check for other alternatives.
```

**Comment by adferrand** [comment]
Hello! Yes `certbot-auto` installation method on Debian is deprecated since Certbot 1.10, and will be soon the same for all systems. You should have a look at https://certbot.eff.org to get instructions on the official supported way to install Certbot, which is `snap`.
