### ISSUE TITLE
Design proposal for an alternative Certbot installation procedure

### ISSUE THREAD

**Issue by adferrand** [certbot/certbot#8510]
Related to https://github.com/certbot/certbot/issues/8345, I would like to propose the following procedure to install Certbot on systems where the official methods cannot or should not be used.

The design proposal can be seen here: https://docs.google.com/document/d/1Xwbq_PGwBNbRPw225n3RNx47kLJ0SqKnGqeoFiSE6XM/edit?usp=sharing

**Comment by bmw** [comment]
Thanks a lot for getting started on this @adferrand!

Did you see https://github.com/certbot/certbot/issues/8422 prior to working on this?

Either way, do you care if we add a link to your doc to that issue and close this?

**Comment by adferrand** [comment]
Yes it was in fact a response to this issue, and I created a separate one to open the discussion in order to refractor it a bit before it becomes maybe the approach to follow, but if you prefer I can link directly to it.

**Comment by bmw** [comment]
I have no real preference, however, I think at the very least https://github.com/certbot/certbot/issues/8422 should link here. At least prior to my referencing it in my previous comment, there was no mention of this issue in #8422.
