### ISSUE TITLE
Improve tracking of code coverage thresholds

### ISSUE THREAD

**Issue by adferrand** [certbot/certbot#8512]
In the past the code coverage validation on unit tests and integration tests was done by [Codecov](https://codecov.io/), which allowed dynamic assertions regarding the past coverage observed on the same branch than a new commit or the target branch (for a PR).

However Codecov failed repeateadly to assert correctly the coverage, making it effectively useless and we removed it eventually (see https://github.com/certbot/certbot/issues/6888, https://github.com/certbot/certbot/pull/7811, https://github.com/certbot/certbot/pull/6934 in particular).

Nowadays a minimal code coverage set statically is required to make the unit tests and integration tests coverage pass. If it is sufficient to detect massive drop of coverage, it does not offer a simple way to update the threshold when it becomes irrelevant. Typically increase it progressively to always require a better coverage of the software.

@alexzorin proposed [here](https://github.com/certbot/certbot/pull/8469#discussion_r536351187) write a logic to fail also the tests if the observed coverage is too far from the threshold.

**Comment by bmw** [comment]
I wonder if codecov might work better now that we're using a single CI provider? Coveralls may also be an option with some work or hackiness. See https://github.com/coveralls-clients/coveralls-python/issues/220.

**Comment by adferrand** [comment]
Yes I wanted also to try and see if things improved on that matter.
