### ISSUE TITLE
[FR] flatpak / flathub build missing

### ISSUE THREAD

**Issue by rayfoss** [certbot/certbot#8515]
I already have flatpaks installed on all my many systems, from Raspberry Pi's to servers to Crostini Chromebooks. When I use Ubuntu, I use apt preferences to blacklist snapd from ever coming back and hogging my limited RAM... Please make a flatpak for our convenience.

Why did I switch to Flatpaks? 
* Third party repositories are not a thing in Snapd, which is extremely undesirable
* Flathub is Open Source, Snapcraft is not
* AppArmor (Key to Snap security) leaves serious holes on Fedora/RHEL/CentOS
* Blender and Gimp ran so slowly on snapd that I thought the package was broken... snapd also takes a big chunk of my Raspberry Pi's RAM, which is antithetical to the purpose of Systemd's efficient socket triggered services. I've had almost no issues with Flatpaks on the other hand. 

**Thank you!**

## My operating system is (include version):
Debian Buster

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
flatpak

## I ran this command and it produced this output:
```
flatpak install certbot
Looking for matches…
error: No remote refs found similar to ‘certbot’
```

## Certbot's behavior differed from what I expected because:
Flatpak is easy to support and becoming the most loved container format... yet certbot isn't ported

## Here is a Certbot log showing the issue (if available):
![Screenshot 2020-12-07 at 13 20 25](https://user-images.githubusercontent.com/876076/101395050-03ca4b00-388f-11eb-921e-faffeee2522b.png)

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
https://github.com/flathub/org.freedesktop.Platform.ffmpeg

**Comment by ohemorange** [comment]
We're unlikely to take this up in the near future, since we recently decided on snaps after an extensive research phase, and one of the main benefits is to not have to support multiple distribution methods.

**Comment by rayfoss** [comment]
The other, bigger, main benefit is resilience against dependencies braking the program and giving you control over update timelines... that would prevent people like me who are using way worse alternatives that create massive headaches to the internet as a whole when updates are needed.

Seems like investing an hour on Flatpak support could save the community thousands of hours down the road... perhaps Flathub will take on the project.

**Comment by ohemorange** [comment]
That would be great if they would! It's not just an hour, it's hours of upkeep every month, and fixing bugs in alternate distribution methods, and additional support for users having trouble with the distribution method.

**Comment by kallisti5** [comment]
groan.  snapd was such a horrible decision.  I have VM's with 1GiB of ram running nginx... now suddenly I have to toss snapd on top of it to run some python scripts?  Seriously?

**Comment by zoracon** [comment]
The Certbot team has taken into consideration different perspectives with snapd and has come to the conclusion that best supports a wide variety of adaption for their users. As well as being able to maintain the project efficiently. Refrain from belaboring the point on several issues in the repository, this triggers burdensome triage and we want to be able to move the conversation forward on the project. Please refer to hour [Code of Conduct](https://www.eff.org/pages/eppcode) to maintain a friendly and respectful community. Thank you.

**Comment by kallisti5** [comment]
@zoracon  comment deleted as it does come off as complainy.

 I'd argue however expressing disappointment in a descision shouldn't be aginst the EFF guidelines since the EFF stands up for free speech on the open internet (it's why I continue to donate to the EFF). I also did not attack or belittle anyone, my frustration was pointed at a descision in general terms and no individual.

With that said... if the "descision has been made", why is this ticket still open?

**Comment by zoracon** [comment]
@kallisti5 the CoC addresses the multiple comments across several issues and platforms about the same topic, that is already open on all platforms, is what triggered the warning.
https://github.com/certbot/website/pull/698#issuecomment-789237333
https://github.com/certbot/certbot/issues/8422#issuecomment-789256926
https://community.letsencrypt.org/t/certbot-non-snapd-instructions/146534/7

As you saw, non-`snapd` instructions are being worked out [here](https://github.com/certbot/website/pull/698).

As far as decisions on issues, the Certbot team will determine how to close this out. Thank you for using Certbot and donating to EFF.

**Comment by smithfred** [comment]
Snap is tied to a single "store" (source of Snaps) - Snapcraft - controlled by a single vendor - Canonical. Canonical will loudly protest that "you can install Snaps from anywhere". But what they actually mean is you can manually download and install Snap files, not have access to other/multiple sources through the client.

This is in contrast to Flatpak, which is *not* tied to a single store, and *does* support multiple sources for Flatpaks when using a Flatpak client.

Additionally, the server code for Flathub (the main Flatpak store/source) is [open source](https://github.com/flathub/linux-store-frontend), whereas Snapcraft's is not.

Finally, Snap depends on AppArmor, so it definitely shouldn't be recommended for use on Distributions that don't use AppArmor for mandatory access control (e.g. Red Hat/Fedora), since the format has no meaningful MAC-based protections on those distributions.

**Comment by rayfoss** [comment]
Have we considered making a Certbot Snapd distribution with Flatpaks? There seems to be not technical limitation aside from a slight increase in overhead... But Which Snapd users won't notice

**Comment by zoracon** [comment]
For now we do not have plans for Flatpak distribution. A lot research and discussion came yielded the conclusion Certbot architecture, a CLI based program, does not pair very well with Flatpak without having many issues. This experience was a complicated conversation in the [Flatpak repository itself](https://github.com/flatpak/flatpak/issues/1188). Closing out for now and if distribution for CLI based software with Flatpak gets better in the future, we can reconsider.

**Comment by GlenKPeterson** [comment]
Thank you for certbot!  It has changed the internet for the better.

I'm currently in the process of uninstalling snaps and replacing them with flatpaks, with a long-term personal goal of moving from Ubuntu to Fedora Silverblue.  Certbot is one of a handful of holdouts.

If it were easy to package certbot as a flatpak, someone would have done it already.  I'm willing to help with testing installation and basic use of flatpak alpha-builds on my systems.  If anyone makes progress on a flatpak certbot, please contact me or post a link.

**Comment by q2dg** [comment]
> We're unlikely to take this up in the near future, since we recently decided on snaps after an extensive research phase, and one of the main benefits is to not have to support multiple distribution methods.

Sorry for being mr obvious, but that was a very bad move. At least provide a flatpak package too, please
