### ISSUE TITLE
can't run `tox -e lint` on docker

### ISSUE THREAD

**Issue by lfundaro** [certbot/certbot#8517]
Hi ! 

I'm trying to develop something on Certbot and getting my environment set up doesn't work as per [instructions for docker](https://certbot.eff.org/docs/contributing.html#running-the-client-with-docker).
Steps to reproduce: 

```
git clone git@github.com:certbot/certbot.git
cd certbot 
docker-compose run --rm --service-ports development bash -c 'tox -e lint'
```

**What I expect**

`tox -e lint` to run successfully 

**What I get**
```
Creating certbot_development_run ... done
lint create: /opt/certbot/src/.tox/lint
ERROR: invocation failed (exit code 1), logfile: /opt/certbot/src/.tox/lint/log/lint-0.log
====================================================== log start =======================================================
Already using interpreter /opt/certbot/venv3/bin/python
Using base prefix '/usr'
New python executable in /opt/certbot/src/.tox/lint/bin/python
Installing setuptools, pip, wheel...

  Complete output from command /opt/certbot/src/.tox/lint/bin/python - setuptools pip wheel:
  Looking in links: /opt/certbot/venv3/lib/python3.7/site-packages/virtualenv_support
Collecting setuptools
Collecting pip
Collecting wheel
Installing collected packages: setuptools, pip, wheel
ERROR: Could not install packages due to an EnvironmentError: [Errno 5] Input/output error

----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/certbot/venv3/lib/python3.7/site-packages/virtualenv.py", line 2619, in <module>
    main()
  File "/opt/certbot/venv3/lib/python3.7/site-packages/virtualenv.py", line 867, in main
    symlink=options.symlink,
  File "/opt/certbot/venv3/lib/python3.7/site-packages/virtualenv.py", line 1159, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "/opt/certbot/venv3/lib/python3.7/site-packages/virtualenv.py", line 1009, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "/opt/certbot/venv3/lib/python3.7/site-packages/virtualenv.py", line 1096, in _install_wheel_with_search_dir
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=script)
  File "/opt/certbot/venv3/lib/python3.7/site-packages/virtualenv.py", line 960, in call_subprocess
    raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode))
OSError: Command /opt/certbot/src/.tox/lint/bin/python - setuptools pip wheel failed with error code 1

======================================================= log end ========================================================
ERROR: InvocationError for command /opt/certbot/venv3/bin/python -m virtualenv --no-download --python /opt/certbot/venv3/bin/python lint (exited with code 1)
_______________________________________________________ summary ________________________________________________________
ERROR:   lint: InvocationError for command /opt/certbot/venv3/bin/python -m virtualenv --no-download --python /opt/certbot/venv3/bin/python lint (exited with code 1)
```

I'm trying to debug this, but haven't had any luck so far and thought you might be able to shed some light. 

Thanks in advance.

**Comment by alexzorin** [comment]
Disk full? What OS are you running this on? The command works for me on Ubuntu Focal, so i think there's a good chance that it's something about the environment.

Since the Docker instructions are planned to be deleted (#8386), it'd probably be better to avoid it.

**Comment by lfundaro** [comment]
I checked the disk and is not full:

```
Filesystem      Size  Used Avail Use% Mounted on
overlay          44G   36G  6.4G  85% /
tmpfs            64M     0   64M   0% /dev
tmpfs           491M     0  491M   0% /sys/fs/cgroup
shm              64M     0   64M   0% /dev/shm
/dev/vda1        44G   36G  6.4G  85% /etc/hosts
grpcfuse        234G  211G   15G  94% /opt/certbot/src
tmpfs           491M     0  491M   0% /proc/acpi
tmpfs           491M     0  491M   0% /sys/firmware
```

Also, a docker inspect on the running container gives this info about mounts:

```
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/Users/lorenzofundaro/certbot",
                "Destination": "/opt/certbot/src",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "0c6649622c08da8c738c2bf165be91b223e65a6e669780dc6156471a9732b3d6",
                "Source": "/var/lib/docker/volumes/0c6649622c08da8c738c2bf165be91b223e65a6e669780dc6156471a9732b3d6/_data",
                "Destination": "/opt/certbot/venv",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ]
```

what caught my eye though is that the volume `/opt/certbot/venv` as specified in the `docker-compose.yml` doesn't have a mode. I wonder if that could be a problem.

**Comment by lfundaro** [comment]
> Disk full? What OS are you running this on? The command works for me on Ubuntu Focal, so i think there's a good chance that it's something about the environment.
> 
> Since the Docker instructions are planned to be deleted (#8386), it'd probably be better to avoid it.

did you try the reproducing steps ?  starting from a fresh git clone and just do `docker-compose run ...` ?

**Comment by lfundaro** [comment]
> Since the Docker instructions are planned to be deleted (#8386), it'd probably be better to avoid it.
I know but until then i think it's fair to expect this to work. People trying to jump in this project for the first time don't necessarily know about the existence of #8386

**Comment by alexzorin** [comment]
>did you try the reproducing steps ? starting from a fresh git clone and just do docker-compose run ... ?

I did yes, on a fresh Ubuntu Focal server.

>grpcfuse        234G  211G   15G  94% /opt/certbot/src

Ah, Windows?

Previously @adferrand has remarked to me that there are some issues relating to Windows and Docker, in the context of testing Certbot. I'm not sure exactly what they are, but he might be able to shed some light on it.

**Comment by adferrand** [comment]
Well, the issues encountered on Docker on Windows are more networking issues. For instance it can be tricky to make the dockerized applications communicate with the host (Windows itself) or other Hyper-V VMS (like WSL2). 

However here the `"Source": "/Users/foo/certbot",` makes me think more of a Docker for Mac.

**Comment by alexzorin** [comment]
Good point, thanks.

@lfundaro could you please try uncheck "Use gRPC FUSE for file sharing" in Docker Desktop and see whether it solves your problem?

**Comment by lfundaro** [comment]
@alexzorin , I did have "Use gRPC FUSE for file sharing" checked. Unchecking it made this work. 
Thank you very much !
