### ISSUE TITLE
certbot-auto uninstall instructions

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8545]
Alex flagged that we should write some certbot-auto uninstall instructions. The idea was to write it somewhere under `certbot/docs` and then link to it in our snap install instructions in our instruction generator in the step about uninstalling other Certbot packages.

To delete `certbot-auto`, you essentially just need to delete the virtual environment and the script itself. This leaves behind any OS dependencies that may not be needed anymore, but I don't think documenting all the cases here is feasible.

We could also write some more general instructions about whether or not you want to delete Certbot's directories, but I personally think we should leave this out, just make it certbot-auto specfic, and maybe consider also writing general Certbot uninstall instructions in the future to resolve https://github.com/certbot/certbot/issues/1245.

**Comment by alexzorin** [comment]
>To delete certbot-auto, you essentially just need to delete the virtual environment and the script itself

If it doesn't overcomplicate the instructions, mentioning that they should remove certbot-auto's cronjob would be nice too.

**Comment by bmw** [comment]
I got started on this and described what needs to be done next at https://github.com/certbot/certbot/pull/8552.
