### ISSUE TITLE
How can we easily use snaps to have people test new features?

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8546]
There is so much with [channels](https://snapcraft.io/docs/channels) and [progressive releases](https://snapcraft.io/docs/progressive-releases) we could do to help segment our users to prevent everyone updating at once. Segmenting our users like this reduces the impact of a bad release and I think is something all/most people on the Certbot team are excited about.

While I'm more than happy to brainstorm about our possibilities here, the thing I'm personally most interested in now is what can we easily do to start doing things like this. The two ideas that were proposed are:

1. Effectively skip a release for a month and put what would have been the release in the candidate/beta channel. When it comes time to do the next release, do the same thing, but also publish the previous release to the stable channel.
2. Publish `master` to the `beta` channel weekly.

If 1 is pushed to the candidate channel, I personally like both of these ideas, however, 2 seems to me like an easier place for us to start.

**Comment by adferrand** [comment]
I think I expressed my opinion somewhere else but I will write it here again. I am very in favor of doing 2. right now. It does not cost anything, and brings the ability to have early adopters that would greatly benefit on anticipating issues before the release.

1. is nice also but I think it would need some synchronization with the other distribution methods (Docker and Windows installer) to offer a similar candidate/stable channel feature.

**Comment by bmw** [comment]
(1) is definitely harder. I personally think it's OK if we don't offer it for every distribution method, especially initially, but I think there are still some things that would have to be figured out such as version numbers, saving/reusing/rebuilding all artifacts a month later, etc. while publish the snap to the beta channel weekly is pretty straightforward.

I personally think if (2) is set up and then a post is made on the community forum to announce we're doing this, we can close this issue.

**Comment by bmw** [comment]
For now, I'd like to document [here](https://certbot.eff.org/docs/install.html#snap) and on the community forum that people can use `--edge` to try our nightly builds and help us test Certbot. After doing that, I'd like to close this issue. Doing something larger here is still tracked in the Certbot Projects & Priorities doc.

**Comment by ohemorange** [comment]
Maybe we could additionally pin that post on the community forum?

**Comment by bmw** [comment]
I'd personally like to check in with ISRG before doing that and I think it only makes sense to pin it for a little while, but I think it's a good idea to help more people see the post. This work for you?

**Comment by ohemorange** [comment]
Yes, that's all what I had in mind.

**Comment by bmw** [comment]
Nice. Glad to hear you were a couple steps ahead of me.

I asked ISRG about this and they said it's fine.

**Comment by bmw** [comment]
Per https://docs.google.com/document/d/1t02y0qQvTgc4eNPY4OwfYu7oW41DEBNhr8fq_O97kXo/edit?usp=sharing, I think we should do this after releasing a stable version of Certbot 2.0.

**Comment by zoracon** [comment]
Considering the work that we have done to integrate Progressive releases. I think we can close this out. I don't think we are at the rate where need to test new features frequently, but have the tooling to do so when we would like to do this. What do you think?

**Comment by bmw** [comment]
I agree!
