### ISSUE TITLE
Upgrade boto3 to support Route53 in AWS China

### ISSUE THREAD

**Issue by alongwill** [certbot/certbot#8548]
## My operating system is (include version):
Ubuntu 18.04.5 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
snap
```
# snap list
Name                 Version    Rev    Tracking         Publisher     Notes
certbot              1.10.1     793    latest/stable    certbot-eff✓  classic
certbot-dns-route53  1.10.1     372    latest/stable    certbot-eff✓  -
```
## I ran this command and it produced this output:
`certbot renew --dry-run`

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/boshu.cn.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert not due for renewal, but simulating renewal for dry run
Plugins selected: Authenticator dns-route53, Installer None
Simulating renewal of an existing certificate for *.boshu.cn
Performing the following challenges:
dns-01 challenge for boshu.cn
Cleaning up challenges
Attempting to renew cert (boshu.cn) from /etc/letsencrypt/renewal/boshu.cn.conf produced an unexpected error: An error occurred (InvalidClientTokenId) when calling the ListHostedZones operation: The security token included in the request is invalid
To use certbot-dns-route53, configure credentials as described at https://boto3.readthedocs.io/en/latest/guide/configuration.html#best-practices-for-configuring-credentials and add the necessary permissions for Route53 access.. Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/boshu.cn/fullchain.pem (failure)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/boshu.cn/fullchain.pem (failure)
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates above have not been saved.)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1 renew failure(s), 0 parse failure(s)
```

## Certbot's behavior differed from what I expected because:
The Route53 API call fails.

## Here is a Certbot log showing the issue (if available):
```
  File "/snap/certbot-dns-route53/current/lib/python3.8/site-packages/certbot_dns_route53/_internal/dns_route53.py", line 68, in perform
    raise errors.PluginError("\n".join([str(e), INSTRUCTIONS]))
certbot.errors.PluginError: An error occurred (InvalidClientTokenId) when calling the ListHostedZones operation: The security token included in the request is invalid
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
`N/A`

## The underlying problem is:
The version of `boto3` currently used in the snap doesn't support Route53 in China.
```
/snap/certbot-dns-route53/current/lib/python3.8/site-packages/boto3-1.11.7.dist-info
```

I've tested the following version of boto3 using a simple python script which does work:
```
boto3 (1.16.38)
botocore (1.19.38)
```

```python
# export AWS_DEFAULT_REGION=cn-northwest-1
import boto3
client = boto3.client('route53')
print(client.list_hosted_zones())
````

**Comment by bmw** [comment]
Thanks for taking the time to look into this and file an issue @alongwill. We can update our pinned version of botocore/boto3.

If anyone would like to help by submitting a PR for this, these packages are pinned in `tools/dev_constraints.txt`. Hopefully only dependencies there need to be updated, however, the pinnings at `letsencrypt-auto-source/pieces/dependency-requirements.txt` take precedence and they can also be updated if needed.

**Comment by bmw** [comment]
Fixed in https://github.com/certbot/certbot/pull/8741.

**Comment by alongwill** [comment]
Just for completeness - I tested renewing a certificate using the `dns-01` challenge using tag `1.14.0` and it worked.

The one gotcha was I had to set the `AWS_DEFAULT_REGION` otherwise it failed. Many thanks @bmw 🙏 

```bash
AWS_DEFAULT_REGION=cn-northwest-1 certbot certonly --dry-run --cert-name 'foo.cn' -d '*.foo.cn' -d 'foo.cn'
...
IMPORTANT NOTES:
 - The dry run was successful.
```

**Comment by vainkop** [comment]
Please update documentation as it's currently missing the requirement for `AWS_DEFAULT_REGION` environment variable
https://certbot-dns-route53.readthedocs.io/en/stable/

![image](https://user-images.githubusercontent.com/28118190/115699993-e80f9f00-a36e-11eb-96d3-e5259162da50.png)

**Comment by bmw** [comment]
That variable doesn't always need to be set does it? If not, when does it need to be?

Any additional links with info or even a PR would be much appreciated.

**Comment by vainkop** [comment]
> That variable doesn't always need to be set does it? If not, when does it need to be?
> 
> Any additional links with info or even a PR would be much appreciated.

I don't know about "always" but I tried to request a certificate using `dns-01` + `certbot/dns-route53:v1.14.0` docker image without `AWS_DEFAULT_REGION` variable set and it failed. It succeeded after I set it.

**Comment by timeswind** [comment]
> > That variable doesn't always need to be set does it? If not, when does it need to be?
> > Any additional links with info or even a PR would be much appreciated.
> 
> I don't know about "always" but I tried to request a certificate using `dns-01` + `certbot/dns-route53:v1.14.0` docker image without `AWS_DEFAULT_REGION` variable set and it failed. It succeeded after I set it.

This `AWS_DEFAULT_REGION ` variable need to be set when the user host the domain in cn-northwest-1 and cn-north-1 regions, since those two regions are separate from the 'aws' namespace and are under 'aws-cn' namspace. So does for the [AWS GovCloud (US)](https://aws.amazon.com/govcloud-us/)
