### ISSUE TITLE
Timeout during connect (likely firewall problem)

### ISSUE THREAD

**Issue by yzy-china** [certbot/certbot#8550]
https://acme-v02.api.letsencrypt.org/acme/chall-v3/9378946468/NxDojQ

**Comment by yzy-china** [comment]
what reason can is be?

**Comment by yzy-china** [comment]
{
  "type": "http-01",
  "status": "invalid",
  "error": {
    "type": "urn:ietf:params:acme:error:connection",
    "detail": "Fetching http://www.domain.com/.well-known/acme-challenge/8559FK5mRvcvk6Ahzo9QsAMEoTGpH2K3VdykYKCmv_4: Timeout during connect (likely firewall problem)",
    "status": 400
  }
}

**Comment by alexzorin** [comment]
Hi @yzy-china,

This issue tracker is for bugs and feature requests in the Certbot software.

I suggest posting your question to https://community.letsencrypt.org/, where there is a large community of users who will be able to help you figure your connectivity problem out.
