### ISSUE TITLE
Certbot renew --dry-run does not honor http-01-port

### ISSUE THREAD

**Issue by claweyenuk** [certbot/certbot#8562]
## My operating system is (include version):
Ubuntu 18.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
pip

certbot 1.10.1

## I ran this command and it produced this output:

I believe this is related to #8485 

`sudo certbot certonly --standalone --http-01-port 8081` worked, and the conf file was good (had port 8081). 

I tried both:
`sudo certbot renew --force-renewal --dry-run` and `sudo certbot renew --dry-run`

Both commands ran into the error below. Suspiciously, the URL mentioned does not use the http-01-port:

```

...

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: test.domain.com
   Type:   unauthorized
   Detail: Invalid response from
   http://test.domain.com/.well-known/acme-challenge/DFrV_uVlWxdUVtGt5P6agrUwigEFgITOFlSfoZM03kA
   [192.168.68.62]: "<html>\r\n<head><title>502 Bad
   Gateway</title></head>\r\n<body
   bgcolor=\"white\">\r\n<center><h1>502 Bad
   Gateway</h1></center>\r\n<hr><cen"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
```

When running `sudo certbot renew --force-renewal` renewal succeeded.

## Certbot's behavior differed from what I expected because:

`--dry-run` should be have passed like the "real" command. It appears the http-port-01 is not used.

## Here is a Certbot log showing the issue (if available):
I can generate some if required.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
N/A (hopefully)

**Comment by alexzorin** [comment]
I tried to reproduce this again using Ubuntu 18.04 and Certbot 1.10.1, but once again, it worked as expected.  (But I do believe that this is happening to you).

For the record, here are my steps that fail to reproduce the issue: https://gist.github.com/alexzorin/e0731cf9db4c844e2e83476c22c40ff7

If you can identify any divergences from your situation, that would help.

**Comment by claweyenuk** [comment]
That's for the quick followup!

In your steps, I see that nginx is listening on port 80 and forwarding requests to port 8081. In my setup, port 80 is not touched. I believe removing these lines will reproduce the issue:

```
  location /.well-known/acme-challenge/ {
    proxy_pass http://localhost:8081/.well-known/acme-challenge/;
  }
```

I'm currently under the assumption that `--standalone` means that cerbot can run without touching port 80, but I also see adding the lines above could be a potential workaround.

**Comment by alexzorin** [comment]
I see. To clarify something,

>In my setup, port 80 is not touched

>Suspiciously, the URL mentioned does not use the http-01-port:

An ACME server will *always* connect to port 80 when performing the HTTP challenge. There is no choice in the matter.

The purpose of Certbot's `--http-01-port` is to facilitate reverse-proxying situations such as that shown in the `proxy_pass` sample configuration.

Regardless of what port you ask Certbot's standalone server to use, the challenge itself must be accessible via your domain's port 80 webserver.

**Comment by claweyenuk** [comment]
Ah, I see, I missed that in the CLI help notes, thanks for pointing this out!

And thanks for sharing gist, it made it very easy to spot the difference. I'll incorporate the nginx config change to get this working.

I think there may still be a small bug though, but not with the `--dry-run` feature.

For the original setup, I am fairly certain port 80 was unavailable, yet worked. And currently, for renewals, I can see that nginx is not configured to forward anything to `--http-01-port` but renewals are working. So I think for the initial setup and for renewals, the ACME server goes directly to `--http-01-port` - this bug is not present for `--dry-run` though.

Is it worth following up on that? I assume that since this is meant for the serving side, the `--http-01-port` should not be sent to ACME server, but my guess is that it is getting sent and use for initial setup and for dry runs.

**Comment by alexzorin** [comment]
>For the original setup, I am fairly certain port 80 was unavailable, yet worked

This might be getting confounded by [authorization caching](https://letsencrypt.org/docs/faq/#i-successfully-renewed-a-certificate-but-validation-didn-t-happen-this-time-how-is-that-possible). In other words, at some point in the 30 days previous you successfully completed an authorization for a domain, and when you order a new certificate, that entire process is skipped. It doesn't matter that the webserver was unavailable because no challenge was performed.

`--dry-run` ensures that all authorizations are fresh and is the more trustworthy option when testing your renewal setup.

**Comment by claweyenuk** [comment]
Ah, got it, that was definitely it. I'll close this issue, thanks for all the help!
