### ISSUE TITLE
Apache virtual host configuration file line with just a tab yields Could not reverse map the HTTPS VirtualHost to the original

### ISSUE THREAD

**Issue by kdolum** [certbot/certbot#8567]
## I ran this command and it produced this output:

certbot --apache

## Certbot's behavior differed from what I expected because:

Instead of creating the mydomain.com-le-ssl.conf file it gave the error
Could not reverse map the HTTPS VirtualHost to the original

## Here is a Certbot log showing the issue (if available):
2020-12-27 15:22:24,271:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 515, in deploy_certificate
    self.installer.deploy_cert(
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 384, in deploy_cert
    vhosts = self.choose_vhosts(domain)
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 408, in choose_vhosts
    return [self.choose_vhost(domain, create_if_no_ssl)]
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 587, in choose_vhost
    vhost = self.make_vhost_ssl(vhost)
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 1171, in make_vhost_ssl
    raise errors.PluginError(
certbot.errors.PluginError: Could not reverse map the HTTPS VirtualHost to the original

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

<VirtualHost *:80>
ServerAdmin kdo@cosmos.phy.tufts.edu
ServerName mydomain.com
ServerAlias www.mydomain.com
DocumentRoot "/var/www/MyDomain/"
</VirtualHost>
	
----------------------------------------------------------------------------------------------------------
There is a line containing only a tab at the end of the conf file above.  If I remove this line (or just remove the tab), then certbot is able to create the mydomain.com-le-ssl.conf file and continue operations.  With it there, I get the error Could not reverse map the HTTPS VirtualHost to the original.

I was able to reproduce the problem by adding or removing the line with the tab, deleting mydomain.com-le-ssl.conf, running certbot --apache again and choosing "Attempt to reinstall this existing certificate".

**Comment by alexzorin** [comment]
Thank you for the detailed report and analysis. I believe this is the same problem behind #8224 so I'm going to close this in favor of the existing issue.
