### ISSUE TITLE
Cert files suddenly removed from /etc/letsencrypt/live

### ISSUE THREAD

**Issue by glebmlk** [certbot/certbot#8568]
Hello,
We use Certbot v0.31.0 for linux. We removed standard `certbot.service` and `certbot.timer` and using self-written script, that runs by cron and check if certificates needs to be updated. If it needs, we just run `certbot renew —webroot -w <directory> —cert-name <domain>`.

Using this flow, we faced a problem: files for a bunch of domains has been removed from folders `/etc/letsencrypt/live` and  `/etc/letsencrypt/archive` (but still exist in `/etc/letsencrypt/renewal`). The strange thing is renewal config is not removed. Is there any flow that certbot could remove files from `/live` and `/archive` folders? In the logs we see a bunch of messages saying that renewal config is broken because of a file in live folder supposed to be a symlink, but it is not (it is removed) 

Logs
`DEBUG:certbot.cert_manager:Renewal conf file /etc/letsencrypt/renewal/krugames.ru.conf is broken. Skipping.
certbot.errors.CertStorageError: expected /etc/letsencrypt/live/krugames.ru/cert.pem to be a symlink
DEBUG:certbot.main:Arguments: ['--webroot', '-d', 'krugames.ru', '-w', '/var/www/html', '--email', 'email@example.com', '--agree-tos', '-n', '-n']
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "krugames.ru"\n    }\n  ]\n}'
      "value": "krugames.ru"
    "value": "krugames.ru"
INFO:certbot.auth_handler:http-01 challenge for krugames.ru
    "value": "krugames.ru"
          "url": "http://krugames.ru/.well-known/acme-challenge/G7nl0slR8h8bq69oR3dP2GR1x6TXxzPlcrmAUCl17RU",
          "hostname": "krugames.ru",
      "value": "krugames.ru"
      "value": "krugames.ru"
DEBUG:certbot.storage:Archive directory /etc/letsencrypt/archive/krugames.ru and live directory /etc/letsencrypt/live/krugames.ru created.
DEBUG:certbot.storage:Writing certificate to /etc/letsencrypt/live/krugames.ru/cert.pem.
DEBUG:certbot.storage:Writing private key to /etc/letsencrypt/live/krugames.ru/privkey.pem.
DEBUG:certbot.storage:Writing chain to /etc/letsencrypt/live/krugames.ru/chain.pem.
DEBUG:certbot.storage:Writing full chain to /etc/letsencrypt/live/krugames.ru/fullchain.pem.
DEBUG:certbot.storage:Writing README to /etc/letsencrypt/live/krugames.ru/README.
DEBUG:certbot.storage:Writing new config /etc/letsencrypt/renewal/krugames.ru.conf.
`
and some time later
`DEBUG:certbot.cert_manager:Renewal conf file /etc/letsencrypt/renewal/krugames.ruconf is broken. Skipping.
certbot.errors.CertStorageError: expected /etc/letsencrypt/live/krugames.ru/cert.pem to be a symlink`

**Comment by alexzorin** [comment]
>The strange thing is renewal config is not removed. Is there any flow that certbot could remove files from /live and /archive folders?

`certbot delete` [deletes the both the renewal config and the entries in the `live` and `archive` directories](https://github.com/certbot/certbot/blob/75499277be6699fd5a9b884837546391950a3ec9/certbot/storage.py#L311-L374). 

I can't identify a situation in which one would be deleted and not the other.

I suspect that something other than Certbot removed the directories, but you could search in `/var/log/letsencrypt/` for `Removed ` to see whether the above code path ran at all.
