### ISSUE TITLE
What access is needed for the certbot-dns-linode API token?

### ISSUE THREAD

**Issue by jilleJr** [certbot/certbot#8570]
I'm reading the docs on certbot-dns-linode (<https://certbot-dns-linode.readthedocs.io/en/stable/>, and if I press "Edit on GitHub" it directs me to commit 64543d49704be2180668371cdcff3b42521b51b2), and the page instructs me to create an API token for my Linode account.

But what access level is needed for that token?

> ![Linode API tokens creation from the Linode Manager](https://user-images.githubusercontent.com/2477952/103414153-0150cd80-4b7d-11eb-9077-7807690460f0.png)
>
> ^ screenshot taken after clicking "Create a Personal Access Token" on <https://cloud.linode.com/profile/tokens>

This would be great if it was added to the documentation. Anyone know? I can only guess and do not want to sit there are try out different combinations while my client errors out all the time.

**Comment by alexzorin** [comment]
"Read/Write" to "Domains".

**Comment by jilleJr** [comment]
It's fine to close it.
