### ISSUE TITLE
Please add a "certbot-dns-oracle" plugin for Oracle OCI workloads

### ISSUE THREAD

**Issue by adacaccia** [certbot/certbot#8571]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 18.04 on OracleCloud (OCI) Instances

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Docker image on Kubernetes

## I ran this command and it produced this output:
Ther'e a certbot-dns-digitalocean available, a certbot-dns-google available, but no certbot-dns-oracle available to support automation of DNS01 challenges for wildcard certificates running within OCI.

**Comment by ohemorange** [comment]
https://certbot.eff.org/docs/contributing.html#writing-your-own-plugin:

>The Certbot team is not currently accepting any new DNS plugins because we want to rethink our approach to the challenge and resolve some issues like #6464, #6503, and #6504 first.
>
>In the meantime, you’re welcome to release it as a third-party plugin. See certbot-dns-ispconfig for one example of that.

If you do package a third-party plugin, you could add it to the list here: https://certbot.eff.org/docs/using.html#third-party-plugins

**Comment by forney-tehama** [comment]
@adacaccia - I came across this issue while looking for the same thing. I ended up with a solution that makes use of the `--manual-auth-hook` option

For example, the original request looks like this (define your variables accordingly - in my case I'm using the certbot staging dir until I've worked out all of the kinks in my flow):
```
certbot certonly --manual --config-dir ${CERTBOT_CONFIG_DIR} --logs-dir ${CERTBOT_LOG_DIR} --work-dir ${CERTBOT_WORK_DIR} --agree-tos -m ${CERTBOT_CONTACT_EMAIL} -d ${CERTBOT_DOMAINS} --preferred-challenges dns --server ${STAGING_URL} --manual-auth-hook ./create-ssl-certificate-manual-auth-hook.sh
```

And then ./create-ssl-certificate-manual-auth-hook.sh basically looks like:
```
#!/bin/bash

DNS_PARENT_COMPARTMENT="(YOUR OCI COMPARTMENT)"

echo "--Auth hook vars--"
echo "CERTBOT_DOMAIN: The domain being authenticated: $CERTBOT_DOMAIN"
echo "CERTBOT_VALIDATION: The validation string: $CERTBOT_VALIDATION"
echo "CERTBOT_TOKEN: Resource name part of the HTTP-01 challenge (HTTP-01 only): $CERTBOT_TOKEN"
echo "CERTBOT_REMAINING_CHALLENGES: Number of challenges remaining after the current challenge: $CERTBOT_REMAINING_CHALLENGES"
echo "CERTBOT_ALL_DOMAINS: A comma-separated list of all domains challenged for the current certificate: $CERTBOT_ALL_DOMAINS"

/path/to/oci dns record domain update -c ${DNS_PARENT_COMPARTMENT} --zone-name-or-id ${CERTBOT_DOMAIN} --domain _acme-challenge.${CERTBOT_DOMAIN} --items "[{\"domain\": \"_acme-challenge.${CERTBOT_DOMAIN}\", \"rtype\": \"TXT\", \"rdata\": \"${CERTBOT_VALIDATION}\", \"ttl\": 30}]" --force
```

Disclaimer - this is a really, really stripped down, gritty version of what my final implementation is going to look like but this should help you get unstuck.

**Comment by adacaccia** [comment]
@forney-tehama Hi Bradley, thank you so much for sharing this, I was trying now to do this exact thing!
However, I'm now giving a try to go-acme/lego, since I both like Golang and it has already support for OracleCloud DNS!

**Comment by goldstar611** [comment]
Thanks for mentioning your plug-in @therealcmj It's one of the last pieces I need to switch from AWS to OCI.

**Comment by therealcmj** [comment]
@goldstar611 in case you're interested I also wrote an installer that puts the acquired cert into OCI's certificates service.

https://github.com/therealcmj/certbot-oci-certs
