### ISSUE TITLE
certbot-dns-rfc2136 does not support delegated validation domain

### ISSUE THREAD

**Issue by cklin** [certbot/certbot#8572]
## My operating system is (include version):

Debian 11

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Debian python3-certbot-dns-rfc2136 1.10.1-1

## I ran this command and it produced this output:

Command:

```
certbot certonly --dry-run --dns-rfc2136 --dns-rfc2136-credentials my_credential_file -d *.aaa.bbb.ccc
```

Response:

> certbot.errors.PluginError: Unable to determine base domain for _acme-challenge.lab.non.one using names: ['_acme-challenge.aaa.bbb.ccc', 'aaa.bbb.ccc', 'bbb.ccc', 'ccc']

## Certbot's behavior differed from what I expected because:

_acme-challenge.aaa.bbb.ccc is CNAME to validation.eee.fff, and I expect certbot to follow the CNAME and attempt to respond to the challenge at validation.eee.fff, as described in https://www.eff.org/deeplinks/2018/02/technical-deep-dive-securing-automation-acme-dns-challenge-validation

I suspect that dns_rfc2136.py needs the following changes:

- It needs to allow using separate DNS servers for querying and for updating the TXT record.   The DNS server used for updating the TXT record may not have any knowledge of _acme-challenge.aaa.bbb.ccc and may not allow recursive queries.
- _query_soa() needs to check for and follow CNAME records.  This part could be a little tricky and really should be done by common certbot code instead of being implemented separately in each DNS plugin.
- _find_domain() needs to return a (validation_record, validation_domain) tuple instead of just the name of the domain because the validation DNS record name may be different (due to CNAME records).
- add_txt_record() and del_txt_record() need to use the validation record returned from _find_domain().

**Comment by alexzorin** [comment]
I think this is the same broad feature request as #6566. There are some PRs written, including for RFC2136 (#7244), which would achieve this.

I'm going to close this as a duplicate, but please contribute any further thoughts to those issues.
