### ISSUE TITLE
Is there a consistent location where renewed certificates are saved?

### ISSUE THREAD

**Issue by darenas18** [certbot/certbot#8585]
I've had to manually write the certificate into a file for my nginx server to read for AWS. So when I auto renew, it doesn't work because nginx is still pointed at the old file. Certbot recently auto renewed my certificate and wrote it to this location:

Writing new private key to /etc/letsencrypt/archive/www.customcompressionapparel.com/privkey4.pem.
Writing certificate to /etc/letsencrypt/archive/www.customcompressionapparel.com/cert4.pem.

My question is, will this file path/name be the same every time? If not, what will it change to each time?

**Comment by alexzorin** [comment]
Yes, use the symlinks in `/etc/letsencrypt/live/...`, which will point to the correct files in `archive/`.

The `live/` directory is what is reported when creating a certificate and also when listing them using `certbot certificates`.
