### ISSUE TITLE
Allow running oldest tests on macOS

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8589]
After my fix for https://github.com/certbot/certbot/issues/8580 is merged, it should be possible to run our oldest tests locally on Linux but not on macOS. This is because of the problem described at https://github.com/pyca/pyopenssl/issues/874 and my desire to continue to support older versions of both `cryptography` and `asn1crypto` (which we only depend on transitively) to help Certbot OS packaging.

The way I would like to fix this is to specify a different oldest supported version of either `cryptography` or `asn1crypto` on macOS. This at bare minimum needs to be done in our pinned versions, however, I think it should also probably be done in `setup.py` using environment markers. I think the best way to do this in our pinned versions is a bit of an open question because newer versions of `pip` only allow very basic constraints, however, maybe we could do something like add `tools/macos-oldest-constraints.txt` which overrides `tools/oldest-constraints.txt` when running on macOS? That's not exactly elegant in my opinion, however, it somewhat matches the pattern provided by things like our `local-oldest-requirements.txt` files and could work.

Another option could be switching from constraints files to requirements files and specifying environment markers in our pinnings as well.

**Comment by adferrand** [comment]
Are you dropping the dockerized approach in your implementation?

**Comment by bmw** [comment]
Yep! On Linux we don't need it anymore, at least with an older version of Python 3.
