### ISSUE TITLE
Apache ssl_module is searched relative to httpd.conf, not ServerRoot

### ISSUE THREAD

**Issue by SamsonovAnton** [certbot/certbot#8593]
## My operating system is:
FreeBSD 12.2-RELEASE-p2

## I installed Certbot with:
`pkg install py37-certbot py37-certbot-apache`

## I ran this command and it produced this output:
```
# certbot-3.7 certonly --apache -d mysite.tld
No such file or directory: '/usr/local/etc/apache24/libexec/apache24/mod_ssl.so'
Unable to read ssl_module file; not disabling session tickets.
```
(The final outcome was successful, though.)

## Certbot's behavior differed from what I expected because:
Certbot attempts to read *mod_ssl.so* (to parse OpenSSL version) at wrong location:

* */usr/local/**etc/apache24**/libexec/apache24/mod_ssl.so* — attempted location;
* */usr/local/libexec/apache24/mod_ssl.so* — actual location.

That is, the module appears to be searched relative to *httpd.conf* location — that is not how it should be done.

## Here is a Certbot log showing the issue:
```
DEBUG:certbot._internal.main:certbot version: 1.8.0
DEBUG:certbot._internal.main:Arguments: ['--apache', '-d', 'mysite.tld']
DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
DEBUG:certbot._internal.log:Root logging level set at 20
INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
DEBUG:certbot._internal.plugins.selection:Requested authenticator apache and installer apache
DEBUG:certbot_apache._internal.configurator:Apache version is 2.4.46
DEBUG:certbot_apache._internal.configurator:[Errno 2] No such file or directory: '/usr/local/etc/apache24/libexec/apache24/mod_ssl.so'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/certbot_apache/_internal/configurator.py", line 256, in _open_module_file
    with open(ssl_module_location, mode="rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/etc/apache24/libexec/apache24/mod_ssl.so'
WARNING:certbot_apache._internal.configurator:Unable to read ssl_module file; not disabling session tickets.
```

## Here is the relevant Apache server config excerpt:
```
# /usr/local/etc/apache24/httpd.conf
ServerRoot "/usr/local"
Module ssl_module libexec/apache24/mod_ssl.so
```
According to Apache HTTP Server documentation, relative paths in [`LoadModule`](https://httpd.apache.org/docs/2.4/mod/mod_so.html#loadmodule) directive should be resolved against [`ServerRoot`](https://httpd.apache.org/docs/2.4/mod/core.html#serverroot) rather than the topmost configuration directory.

**Comment by bmw** [comment]
Thanks for the detailed bug report.

Looking into this a bit, it seems like this problem is at least partially caused by a downstream patch. https://svnweb.freebsd.org/ports/head/security/py-certbot-apache/Makefile?revision=491714&view=markup runs:
```
@${REINPLACE_CMD} -e 's|/etc/apache2|${LOCALBASE}/etc/apache24|'  ${WRKSRC}/certbot_apache/configurator.py
```
on our code and as a result the default value for the Apache server root is `/usr/local/etc/apache24`.

You can see this by running `certbot --help apache` which shows:
```
  --apache-server-root APACHE_SERVER_ROOT
                        Apache server root directory (default:
                        /usr/local/etc/apache24)
```
Are you interested in reporting this bug to the FreeBSD package maintainers?

Also, now that the Apache plugin is package on FreeBSD, if someone was interested in helping with it, we could potentially add an `override_*.py` file in https://github.com/certbot/certbot/tree/434ca1985f26b08de18728e70e86813f357f6b65/certbot-apache/certbot_apache/_internal like we do for other systems so FreeBSD doesn't have to maintain a patch on their end.

**Comment by SamsonovAnton** [comment]
> Are you interested in reporting this bug to the FreeBSD package maintainers?

Reported as [Bug 252776](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=252776).

> It seems like this problem is at least partially caused by a downstream patch on our code, and as a result the default value for the Apache server root is `/usr/local/etc/apache24`. Also, we could potentially add an `override_*.py` file like we do for other systems so FreeBSD doesn't have to maintain a patch on their end.

While writing that bug report, I looked into Certbot code and stumbled upon the fact that it does not seem to retrieve `ServerRoot` from *httpd.conf* at all. It only has a notion of `OS_DEFAULTS["server_root"]`, which is not `ServerRoot` itself, but only a path to *httpd.conf* where the real `ServerRoot` is defined and should be read from (but is not). Therefore this issue may in fact be a flaw in Certbot design rather than a distro-specific mishandling, which cannot be fixed by *override_*.py* because that only serves to initialize `OS_DEFAULTS["server_root"]` without passing `--apache-server-root` command line argument.

**Comment by bmw** [comment]
Thanks for creating that bug report and digging into this some more.

Taking another look myself, there are changes that need to be made to our code for this to work. There may be more but one is that we assume that the root Apache config file is the value for `--apache-server-root` + one of `"apache2.conf", "httpd.conf", "conf/httpd.conf"`. See https://github.com/certbot/certbot/blob/00235d3807f298c3cee700ed946a2fc6c3bf8145/certbot-apache/certbot_apache/_internal/parser.py#L926-L932

A quick fix for that on FreeBSD should be adding `etc/apache24/httpd.conf` to the end of that list.

I agree that it would be nice for us to also update the value of `ServerRoot` dynamically based on parsing the config, however, I think that'd be a larger project that we at least couldn't get to ourselves for a quite while. It also raises questions for me about the best behavior when the user is explicitly telling Certbot what the server root is. In the meantime, I think it shouldn't be too hard to get things working if `--apache-server-root` has the correct value either through proper defaults or the user providing it.

**Comment by d00rsfan** [comment]
Hi, all! Looks, bug stil persists:
```
certbot --version
certbot 3.2.0
```
mod_ssl located:
```
ls -lfa /usr/local/libexec/apache24/mod_ssl.so
-rwxr-xr-x  1 root wheel 238944 Jan 28 16:43 /usr/local/libexec/apache24/mod_ssl.so
```
but certbot is looking in wrong path:
`FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/etc/apache24/libexec/apache24/mod_ssl.so'`
