### ISSUE TITLE
Certbot doesn't wait for the Pre Validation Hook to return but continue immediately

### ISSUE THREAD

**Issue by honglim-bd** [certbot/certbot#8594]
## My operating system is (include version):
Windows 10 Pro 19042.685

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-beta-installer-win32.exe

## I ran this command and it produced this output:
```bash
$ certbot --manual --preferred-challenges dns certonly -d *.mydomain.com --dry-run --manual-auth-hook ./authenticator.sh --manual-cleanup-hook ./cleanup.sh
Saving debug log to C:\Certbot\log\letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Simulating a certificate request for *.mydomain.com
Performing the following challenges:
dns-01 challenge for mydomain.com
Running manual-auth-hook command: ./authenticator.sh
Waiting for verification...
Challenge failed for domain mydomain.com
dns-01 challenge for mydomain.com
Cleaning up challenges
Running manual-cleanup-hook command: ./cleanup.sh
Some challenges have failed.
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: mydomain.com
   Type:   unauthorized
   Detail: No TXT record found at
   _acme-challenge.mydomain.com

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
```

## Certbot's behavior differed from what I expected because:
I expect that the Certbot should continue only after the `authenticator.sh` is returned. What's inside the `authenticator.sh` is, it contains the Azure CLI that add a TXT record into the DNS. Due to the Certbot doesn't wait for the `authenticator.sh` to return and proceed immediately, therefore it can't find any TXT record in the DNS.

However, I am able to proceed with no error if I execute the command without the `--manual-auth-hook`, which means that when I add the TXT record manually into the DNS.

I am using Git Bash 2.27.0 to execute the Certbot command.

**Comment by bmw** [comment]
Thanks for the detailed bug report. I was able to reproduce this.

Testing on Windows Server 2019 running Certbot in Git Bash, I created a manual auth hook containing:
```
#!/bin/bash
echo hi
sleep 60
```
Passing this file to Certbot with `--manual-auth-hook`, what I saw was a separate terminal window open that printed "hi" and waited while my original terminal window running Certbot continued running without waiting for the hook to finish.

@adferrand, do you have the time and interest to take a look at this?

**Comment by G-Cottin** [comment]
I have encountered this issue today.
I'm using certbot version: 1.20.0 for Windows.
Any way trick to resolve this?
