### ISSUE TITLE
Scheduled Task on Windows is missing

### ISSUE THREAD

**Issue by marveloo** [certbot/certbot#8604]
Operating system: Windows Server 2008 R2
Certbot version: 1.11.0 (installed via Certbot installer for Windows)

<hr>

[Certbot doc page for Windows](https://certbot.eff.org/lets-encrypt/windows-other) says:

> The Certbot installation on your system comes with a pre-installed Scheduled Task that will renew your certificates automatically before they expire. You will not need to run Certbot again, unless you change your configuration.

Unfortunately, I can't see not a single Scheduled Task pre-configured on my machine:

![image](https://user-images.githubusercontent.com/36376767/104393813-02570700-554e-11eb-8400-83eee5e1b570.png)

**Comment by ohemorange** [comment]
@adferrand, launching this your way for Windows.
