### ISSUE TITLE
Certbot-auto on Elastic Beanstalk is depreceated

### ISSUE THREAD

**Issue by FlorianRuen** [certbot/certbot#8609]
Hi there,

I'm using AWS Elastic Beanstalk to deploy my application, which run inside Docker Container (Java application). To access my website, i'm using certbot-auto to automatically get / renew certificates when I deploy my application (using .ebextensions post deploy commands) like this : 

`container_commands:
  10_installcertbot:
    command: "wget https://dl.eff.org/certbot-auto;chmod a+x certbot-auto"
  20_getcert:
    command: "sudo ./certbot-auto certonly --debug --non-interactive --email ${CERT_EMAIL} --agree-tos --standalone --domains ${CERTDOMAIN} --keep-until-expiring --pre-hook \"service nginx stop\" --post-hook \"service nginx start\""
  30_link:
    command: "ln -sf /etc/letsencrypt/live/${CERTDOMAIN} /etc/letsencrypt/live/ebcert"
  40_config:
    command: "mv /etc/nginx/conf.d/https_custom.pre /etc/nginx/conf.d/https_custom.conf"
  50_renew:
    command: '(crontab -l ; echo ''0 0 1 * * ./certbot-auto renew --standalone --pre-hook "service nginx stop" --post-hook "service nginx start" --force-renew'') | crontab -'`

But since my last update (yestarday), I got an error which say "Certbot-auto is depreceated, can't install on current system", so my production application was down ...

Today I'm searching something to fix this or to bypass it (maybe using acme.sh or something else that can auto renew and get the certs wtith the same way)

**_EDIT: For now, the only solution is to keep the old version of certbot auto to run and get my certificate. But i'm looking for something better_**

## My operating system is (include version):
Platform is Amazon Linux running docker container (Amazon Linux 64 bits version 2.16.3)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Using wget to download it directly (which is runned by .ebextension when deploy is successfull)

Someone have the same problem ? Maybe a solution to fix this

Thanks again,

Kind regards,
Florian

**Comment by ohemorange** [comment]
I'm not personally familiar with your setup; you might be able to find someone who is on our community forums at https://community.letsencrypt.org/. Otherwise, you can try installing via our [certbot snap](https://snapcraft.io/certbot) or check out our in-progress draft of instructions for installing via pip [here](https://github.com/certbot/certbot/issues/8422). In any case, this issue tracker is for bugs in certbot, and certbot-auto's deprecation was certainly planned and intended, so I'm going to close this issue.
