### ISSUE TITLE
Improve the confusing message: Congratulations and Unable to install the certificate

### ISSUE THREAD

**Issue by neoneye** [certbot/certbot#8610]
## My operating system is (include version):

macOS Big Sur 11.1

```
PROMPT> uname -a
Darwin abcdef.home 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
```

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

```
PROMPT> brew install certbot
PROMPT> certbot --version
certbot 1.10.1
```

## I ran this command and it produced this output:

```
PROMPT> sudo certbot --nginx
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator nginx, Installer nginx
No names were found in your configuration files. Please enter in your domain
name(s) (comma and/or space separated)  (Enter 'c' to cancel): subdomain.example.com
Requesting a certificate for subdomain.example.com
Performing the following challenges:
http-01 challenge for subdomain.example.com
Using default address 80 for authentication.
Waiting for verification...
Cleaning up challenges
Could not automatically find a matching server block for subdomain.example.com. Set the `server_name` directive to use the Nginx installer.

IMPORTANT NOTES:
 - Unable to install the certificate
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/subdomain.example.com/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/subdomain.example.com/privkey.pem
   Your cert will expire on 2021-04-18. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot again
   with the "certonly" option. To non-interactively renew *all* of
   your certificates, run "certbot renew"
PROMPT>
```

## Certbot's behavior differed from what I expected because:

The command appears to have finished unsuccessfully.
- It both says `Unable to install`, which seems like unsuccessful.
- And it also says `Congratulations`, which seems like a success.

Perhaps printing out `Congratulations` only when it's a true success,
without any errors. Otherwise users may be confused.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

I don't think this is relevant for my issue.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

I don't think this is relevant for my issue.

**Comment by alexzorin** [comment]
Much of this output has been redesigned. It's going to look closer to this (but the example below is already outdated in some respects):

    $ sudo certbot run -a webroot -w /var/www/html -i apache -d www.example.com
    Saving debug log to /var/log/letsencrypt/letsencrypt.log
    Requesting a certificate for www.example.com

    Successfully received certificate.
    Certificate is saved at: /etc/letsencrypt/live/www.example.com/fullchain.pem
    Key is saved at:         /etc/letsencrypt/live/www.example.com/privkey.pem
    These files will be automatically updated every time the certificate is renewed.
    This certificate expires on 2025-11-30.

    Deploying certificate.
    Failed to install the certificate (using the apache plugin). Try again by running:

      certbot install --cert-name www.example.com

    Certbot could not find a VirtualHost for www.example.com in the Apache configuration. Please create a VirtualHost with a ServerName matching www.example.com and try again.
    Ask for help or search for solutions at https://community.letsencrypt.org. See the logfiles in /var/log/letsencrypt or add -v for more details.

>Perhaps printing out Congratulations only when it's a true success,

Fundamentally there are two distinct operations when you run e.g. `certbot --nginx`: getting the certificate and installing it.

I'm not sure that we could/should hide this distinction from the user. 

What I am *hoping* is that by a) more clearly separating the two operations in the output and b) prompting the user to re-run the install portion, it will be clear what has failed, and what the user should do next.

Since you were motivated enough to report this, I'd be keen to hear your opinion on the new proposed output.

**Comment by neoneye** [comment]
UX for command line is so tricky and I'm no expert in this field. 

I think I yesterday would have liked to know is how far am I from reaching the final goal. Am I halfway there, or did it fail in the beginning, or did it fail at the very last step. Perhaps a progress indicator, ala `STEP x of y - Description of step.`. This may make it easier predict how many obstacles are in front of you.

```
$ sudo certbot run -a webroot -w /var/www/html -i apache -d www.example.com
STEP 1 of 3 - Creating certificate.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Requesting a certificate for www.example.com
Certificate is saved at: /etc/letsencrypt/live/www.example.com/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/www.example.com/privkey.pem
These files will be automatically updated every time the certificate is renewed.
This certificate expires on 2025-11-30.

STEP 2 of 3 - Deploying certificate.
Failed to install the certificate (using the apache plugin). Try again by running:

  certbot install --cert-name www.example.com

Certbot could not find a VirtualHost for www.example.com in the Apache configuration. Please create a VirtualHost with a ServerName matching www.example.com and try again.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfiles in /var/log/letsencrypt or add -v for more details.
```

**Comment by alexzorin** [comment]
Thanks, that's a pretty good idea! I'll bring it up and see where it goes.

**Comment by alexzorin** [comment]
We talked about it and a progress indicator like this makes sense and is something we'd like to add. Thanks for suggesting it.

There are a few questions without obvious answers (is account registration a step? are hooks a step? should all output belong to a step?). I don't think we can fit that work in the upcoming UX changes, but I hope we can do it some time after.

**Comment by alexzorin** [comment]
One of the things we did in Certbot 1.16.0 was reducing terminal output and more specific to this issue, adding a "NEXT STEPS" concept for things like installation errors:

![image](https://user-images.githubusercontent.com/311534/121319810-ea927c00-c94f-11eb-9144-3ff39fa41cc8.png)

It's definitely inspired by your suggestion but also based on what we had wanted to change originally.

I'm going to close this because we completed this iteration of improvement, but more of the constructive feedback you've already given is definitely welcome.

**Comment by neoneye** [comment]
Seems like a good solution. Looking forward to try it out. Thank you very much.
