### ISSUE TITLE
Distribution not found error

### ISSUE THREAD

**Issue by sidelux** [certbot/certbot#8611]
## My operating system is (include version):
Debian 9

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager

## I ran this command and it produced this output:
certbot

## Certbot's behavior differed from what I expected because:
When i start certbot it say:
```
Traceback (most recent call last):
  File "/usr/bin/certbot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3257, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3240, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3269, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 582, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 899, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 785, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'certbot==0.28.0' distribution was not found and is required by the application
```
And nothing to do to fix.

## Here is a Certbot log showing the issue (if available):
Empty logs.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        ServerName fenixweb.net
        SSLCertificateFile /etc/apache2/ssl/certificate.crt
        SSLCertificateKeyFile /etc/apache2/ssl/private.key
        SSLCertificateChainFile /etc/apache2/ssl/ca_bundle.crt
</VirtualHost>
</IfModule>
```

Thanks a lot.

**Comment by alexzorin** [comment]
Hi @sidelux,

It sounds like something has gone wrong with the Python packages on your system. This is sometimes caused by installing packages using `pip` and that resulting in them overwriting Python packages managed by `apt`.

You could try forcing that package to be re-installed from `apt` (as well as any other packages which report a similar error):

    sudo apt install --reinstall python3-certbot

The official installation instructions for your environment can be found [here](https://certbot.eff.org/lets-encrypt/debianstretch-apache). They suggest removing the `apt` package and installing the Certbot snap.

**Comment by 4external** [comment]
Hi!

I have on server python from "box" - 2.7 + 3.5, then I installed Python 3.7 for some project and than had error like you. Than i edited /usr/bin/certbot and change first line to #!/usr/bin/python3.5

This is helped me.

Idea - apt installs Certbot and python3-certbot install packages for 3.5, but actual version python3 is python3.7 not 3.5

**Comment by djratza** [comment]
> Hi!
> 
> I have on server python from "box" - 2.7 + 3.5, then I installed Python 3.7 for some project and than had error like you. Than i edited /usr/bin/certbot and change first line to #!/usr/bin/python3.5
> 
> This is helped me.
> 
> Idea - apt installs Certbot and python3-certbot install packages for 3.5, but actual version python3 is python3.7 not 3.5

Thank you, this fixed my issue
