### ISSUE TITLE
manual: when not using hooks, tell the user they need to wait for DNS propagation

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8612]
One of the usability things I came across in #8514 was that it's not terribly obvious when setting up TXT records manually that with some DNS hosts, you need to wait a while. 

https://github.com/certbot/certbot/blob/adb7e5e62f4c96be678c5af3e55a82ddcc717590/certbot/certbot/_internal/plugins/manual.py#L45-L51

This bit of vague text could be rewritten in order to convey the advice more directly: 

> Before continuing, verify the record is deployed

I think it would be ideal if we only showed this on the very last DNS challenge, but I'm not sure whether the logic of Certbot will permit that. I don't think it's a big deal to show it every time.

**Comment by ohemorange** [comment]
Nice catch, totally agreed on all counts.

**Comment by osirisinferi** [comment]
@alexzorin I think my rendition of a possible fix to this issue [is a little bit long](https://github.com/certbot/certbot/pull/8770), what do you think?
