### ISSUE TITLE
Remove six dependency in josepy

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8627]
This issue is for the repository https://github.com/certbot/josepy, however, I'm creating it here for better visibility.

Now that `josepy` doesn't support Python 2, we should remove the `six` dependency from our code.

**Comment by atombrella** [comment]
https://github.com/certbot/josepy/pull/81 So maybe this issue can be closed?

**Comment by bmw** [comment]
Yep! Thanks for pointing that out.
