### ISSUE TITLE
1.12.0 fails to build manpage

### ISSUE THREAD

**Issue by hlieberman** [certbot/certbot#8633]
Because of the addition of `man` to the `exclude_patterns` list in docs/conf.py, sphinx is no longer able to build the manpage `certbot.1`.

This has been fixed downstream with the deletion of the directory from the `exclude_patterns` list.

**Comment by alexzorin** [comment]
@adferrand, having reviewed #8530, do you happen to know what should be done here?

**Comment by vitlav** [comment]
It is due adding man dir to exclude_patterns in conf.py:
https://github.com/certbot/certbot/commit/7399807ff2b4f8ac1f97e4f037f374610ca88797

```
exclude_patterns = [
    '_build',
    'man',
    'challenges.rst',
    'ciphers.rst'
]
```

removing man from the list resolves the problem.

**Comment by sommersoft** [comment]
As the author of #8530, this one is on me. I didn't test building the man page. I'll dig into it and see if I can get this fixed.
