### ISSUE TITLE
python3: can't open file 'tools/venv3.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by paragk05** [certbot/certbot#8642]
i am facing this issue.

**Comment by adferrand** [comment]
In witch context exactly are you encountering this issue? What are the commands you launched?

We have renamed the `venv3.py`script into `venv.py`recently, so you are targeting the wrong script name explicitly or implicitly.

**Comment by paragk05** [comment]
I was referring this link.

https://gist.github.com/bradtraversy/cd90d1ed3c462fe3bddd11bf8953a896

**Comment by adferrand** [comment]
Sorry, this gist is not related to the certbot project.

You should reach its author directly to check with them what needs to be updated regarding recent evolutions that could have been added to certbot since the instructions have been written.
