### ISSUE TITLE
Allow Certbot to skip creating a lockfile for read-only operations

### ISSUE THREAD

**Issue by AJRepo** [certbot/certbot#8651]
I have an opensource HaProxy deploy script which runs in /etc/letsencrypt/renewal-hooks/deploy/ . The script copies the contents of the keyfile and crtfile into a suitably named PEM file in a directory where HaProxy reads them and automates the HaProxy/TLS protections. 

I looked to see what variables are pushed to the deploy script and found only these two variables are sent to deploy scripts
```
#  Confirmed DEPLOY Hook Variables
#    RENEWED_LINEAGE
#    RENEWED_DOMAINS (note: could be wildcard. E.g. *.domainname ) 
```
I looked for and found these variables were NOT passed

```
#  Varables that are NOT passed to deploy hooks
#    CERTBOT_CERT_PATH
#    CERTBOT_KEY_PATH
#    CERTBOT_ALL_DOMAINS
#    CERTBOT_DOMAIN
```

Since the keyfile and crtfile variables are not provided to the deploy script. I needed a way to find those files. 

From the variable $RENEWED_LINEAGE one could guess the full path to the keyfile and crtfile,  but why guess? The command   `certbot certificates -d www.example.com` tells where the actual keyfile and crtfile are. 

Unfortunately - when certbot is renewing a certificate it leaves the lockfile there even while the deploy scripts are running.  So in the deploy script a command to certbot to query the certificates locations as 

`certbot certificates -d example.com` 

gives the error

`Another instance of Certbot is already running.`

I tried using temp working dirs as 
`certbot --work-dir $CERTBOT_TMP_WORKDIR --logs-dir $CERTBOT_TMP_LOGDIR `

to see if that would get around the issue, but because there is still a lockfile  in the config-dir you get the same error. 

This is similar to issue #4628 asking for the ability to run two certbots at once, but I am asking for a more narrow feature of allowing one to call certbot in a read-only manner without a config-dir lockfile. Thus you can call `certbot` as a read-only manner from deploy scripts to get the key and crt file paths or, perhaps in future usage, other unknown future added information.

Now that I know why the deploy scripts were failing I have the workaround to guess the keyfile and crtfile from the RENEWED_LINEAGE variable, but would be great to not have to make that filename assumption and worry about certbot naming changes in the future.

So if one can run `certbot --work-dir $CERTBOT_TMP_WORKDIR --logs-dir $CERTBOT_TMP_LOGDIR certificates -d www.example.com`  without worrying about the lock file in /etc/letsencrypt, that would allow the deploy scripts to run and get the correct filenames from certbot. 

## My operating system is (include version):
Ubuntu 18.04, 20.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
`apt install certbot` and also downloaded from git and used `python3 tools/venv.py` to see if a read-only feature was in the latest git release. 

## I ran this command and it produced this output:

`Another instance of Certbot is already running.`

**Comment by alexzorin** [comment]
>From the variable $RENEWED_LINEAGE one could guess the full path to the keyfile and crtfile, but why guess? The command certbot certificates -d www.example.com tells where the actual keyfile and crtfile are.

The names of the certificate and key files are part of Certbot's public interface and are **guaranteed** not to change suddenly. https://certbot.eff.org/docs/compatibility.html makes that promise. We expect users to hardcode  `/etc/letsencrypt/live/$RENEWED_LINEAGE/{fullchain,privkey}.pem` into their deploy hooks.

The paths are also present in `/etc/letsencrypt/renewal/$RENEWED_LINEAGE.conf`, but neither the contents of that file nor the output of `certbot certificates` are covered by the compatibility guarantee.

>but I am asking for a more narrow feature of allowing one to call certbot in a read-only manner without a config-dir lockfile

Another Certbot process could be half way through writing or renaming some files and you wouldn't know it. The best Certbot could do is allow multiple readers via a readers-writer lock, but as of right now I can't think of any legitimate usecase for that enhancement.

Hopefully the first part of my response cancels out your motivation for this proposal, though.

**Comment by AJRepo** [comment]
I read the compatibility guide. Thanks. 

I see it says

> /etc/letsencrypt/live/<domain>/{cert,chain,fullchain,privkey}.pem where <domain> is the name given to --cert-name. If --cert-name is not set by the user, it is the first domain given to --domains.

It seem that that naming convention breaks with naming conflicts and wildcard domains. For example, I have a certbot server handling domains *.example.com and example.com . Certbot created directories

`/etc/letsencrypt/live/example.com `  

and

`/etc/letsencrypt/live/example.com-0001` 

So perhaps it should say 

'/etc/letsencrypt/live/<domain>/{cert,chain,fullchain,privkey}.pem where <domain> is the name given to --cert-name. If --cert-name is not set by the user, it is the first domain given to --domains. If using a wildcard domain like *.example.com the * is dropped. To avoid naming collisions between *.example.com and example.com, if both are used then <domain> becomes  or example.com-0001.`

That's probably a different ticket. 

In any case since $RENEWED_LINEAGE/ covers that exception and given the promise that filenames are not going to change, I'm ok closing this ticket.  

I wrote the deploy script to be able to be called manually outside of certbot's deploy process (when $RENEWED_LINEAGE is unset) too and thought I could just always use `certbot certificates -d `. I agree - it's probably best if it does fail/wait if certbot is writing to those files. Given your answer, I now have the script so that if $RENEWED_LINEAGE is not set, it looks to see if certbot is running, waits, tries to get via `certbot certificates -d <domain>` and fails if it can't.   

If certbot has a per-directory lockfile that would potentially help avoid collisions where the files needed aren't the ones being updated, and perhaps allow parallel usage, but that is probably also a different ticket.

Thank you very much for an awesome tool! 

I'll close this ticket.
