### ISSUE TITLE
Certbot no longer works because python2.7 has been deprecated

### ISSUE THREAD

**Issue by Tectract** [certbot/certbot#8662]
## My operating system is (include version):
Linux Mint 17.03 (ubuntu 14.04 based)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
git repository install

## I ran this command and it produced this output:
./certbot-auto

    Your system is not supported by certbot-auto anymore.
    certbot-auto and its Certbot installation will no longer receive updates.
    You will not receive any bug fixes including those fixing server compatibility
    or security problems.
    Please visit https://certbot.eff.org/ to check for other alternatives.
    /opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a release (2.7.7+) that supports hmac.compare_digest as soon as possible.

## Certbot's behavior differed from what I expected because:

I need to figure out how to get certbot running on Ubuntu14.04 again, I cannot upgrade the system version of python on this machine, but it does have python3 installed. I cannot simply "upgrade my operating system" to fix this cert issue, I have servers all over the nation with this problem now. The reason we cannot upgrade past Ubuntu 14.04 is because of systemd, it will never happen.

What can be done?

Is there a way I can tell certbot to use python3 and get past this issue, and stay on the upgrade path for certbot here?

Systemd avalanche is affecting certbot now...

**Comment by alexzorin** [comment]
Hello,

Beyond dropping support for certbot-auto Python 2, Certbot doesn't support EOL operating systems.

We have an open issue which tracks installing Certbot from source using Python 3.6+: https://github.com/certbot/certbot/issues/8422. I would guess that the resulting instructions probably *won't* work on a distro as ancient as Ubuntu Trusty, but you are free to use them another systemd-free distro like Devuan.

**Comment by Tectract** [comment]
Hey I understand your position but there is actually a good reason I'm still running this operating system, and it's because it's the last linux operating system that doesn't run on systemd as PID1, which I consider a critical stability and security issue. I'm running what I consider the most recent stable and secure version of Ubutu/Mint.

I would like to understand how I can run certbot using python3 instead of python2. There's no reason I shouldn't be able to run python3 programs, python 3.4 came installed with this OS so it should work. I would implore you guys not to drop apache2.2 support also. My servers have no known TLS or web security issues right now, there's no reason we should be forcing people into switching operating systems unless there is an actual technical need/reason why they can no longer operate securely on theirs.

**Comment by alexzorin** [comment]
For many reasons, I don't think that it's going to be possible to accommodate your request. However, you might be interested in some other [client options](https://letsencrypt.org/docs/client-options/) that might still work on Ubuntu 14.04. [lego](https://github.com/go-acme/lego/) is a great choice that should work in literally any Linux environment, even if it lacks some bells and whistles.
