### ISSUE TITLE
Certbot doesn't differentiated between staging and production certificates.

### ISSUE THREAD

**Issue by bsutton** [certbot/certbot#8667]
I've built a application for managing certificates for nginx.

During deployment testing we use a staging certificate for obvious reasons.

One of the issues that we have encountered is certbot's inability to distinguish between production and staging certificates.

We have a unit test that tests switching from staging to production. The unit test was failing as when we ran 'certbot certonly' it reported that the existing certificate didn't need to be renewed.

The existing certificate was of course a staging certificate and we wanted a production certificate.

I've had related issues when trying to revoke a certificate  that was a staging certificate but I had left off the --staging flag. Instead of reporting that the certificate was of the wrong type it reported something along the lines of unrecognized issuer.

These type of issues take some time to diagnose. 

There appear to be a number of certbot commands that don't take the --staging flag (delete , ?).

In my opinion it would be better if staging/production was always explicit and an error thrown if you attempt an operation on the wrong type of certificate.

```
sudo certbot --version
certbot 1.7.0
```

**Comment by alexzorin** [comment]
>I've had related issues when trying to revoke a certificate that was a staging certificate but I had left off the --staging flag

I'm a little surprised that `certbot revoke` does not respect the `server` value from `/etc/letsencrypt/renewal/{name}.conf`. Leaving a reminder to check why ^^.

**Comment by ohemorange** [comment]
As alex mentioned above, that one in particular is almost certainly a bug, and should be pretty straightforward to fix.

As for other situations, our general goal with `--staging` is to be as close to production as possible, so that it's an accurate test when preparing for production. So we try to keep differences between the two paths as minimal as possible, and when it shouldn't matter to the particular action, just act on the certificate. It might be possible to update your test -- have you seen `certbot certificates`? That will show you if a particular certificate uses the staging server or not (staging certs will have `INVALID: TEST_CERT` next to the expiry date).

**Comment by bsutton** [comment]
@ohemorange thanks for the feedback. I am aware and use certbot certificates.

When my code is working correctly it uses certbot certificates to parse the certificates and identify staging/production certificates.

The issues is when I've had bugs in my code and then certbot throws errors that make no sense.

Whilst I agree that the paths should be as close as possible I think the api should force the user to be explicit in each instance.

This will allow the api to throw an appropriate error and would have save me a lot of time.

**Comment by ohemorange** [comment]
Ah, I see. I don't think we want our users to have to specify production every time; you can see how that would be unnecessarily verbose in most cases, right? We use explicit flags for testing.

**Comment by bsutton** [comment]
Having production as the default is fine but staging should always be
require.

**Comment by osirisinferi** [comment]
I'm not so sure if this is an "easy fix". Let me explain:

The current way certbot differentiates between production and staging certificates is *very* simple:

https://github.com/certbot/certbot/blob/40ae5d939ee0449ce54b8bf12e75e9311e361d91/certbot/certbot/util.py#L599-L607

where `STAGING_URI` is hardcoded to only the Let's Encrypt staging URI:

https://github.com/certbot/certbot/blob/40ae5d939ee0449ce54b8bf12e75e9311e361d91/certbot/certbot/_internal/constants.py#L125

However, other ACME servers may (and do) have *other* names for their staging server, for example, the testing environment for the BuyPass ACME server is: https://api.test4.buypass.no/acme/directory

It is *not* listed in the `STAGING_URI` string, as it's Let's Encrypt-only and does *not* contain the string "staging", but "test".

Of course we could modify `is_staging()` to include "test", but that's just a hack waiting to go wrong. Personally, I think certbot should be URI-oblivious and somehow **store** whether a live or staging URI was being used.

That said, currently certbot only supports non-Let's Encrypt ACME servers using the `--server`. And currently, it's not possible to override `--staging` by `--server` to somehow signal certbot the ACME server used is staging:

> --server value conflicts with --staging

So my proposal:

* store whether a staging server is used in the renewal configuration file, e.g. `staging=True`
* When `--staging` and `--server` are combined, the `--staging` option signals that the ACME server in `--server` is a staging server without of course overriding the URI from `--server`.

**Comment by bsutton** [comment]
I'm not familiar with the structural limitations of certificates but can the certificate contain a property staging=true.
Then if there is a mismatch between the certbot flag and the certificate property or the responding server an error can be thrown. Dependency on the url is a really bad idea, the current method of including a string 'invalid' with the date also feels like a hack.
The staging flag should also be passed to the server so it can confirm a match between the requested certificate type and the certificates the server issues is consistent.

I get the impression this information is currently inferred which always results in unstable APIs.

**Comment by osirisinferi** [comment]
> I'm not familiar with the structural limitations of certificates but can the certificate contain a property staging=true.

As far as I can tell from some searching, X.509 doesn't have an *easy* method of adding such a property. Some sites do give some methods to add "custom" stuff to a X.509 certificate, but it feels like hacking it together. Or one would require to add such a staging property to X.509 in some official way.

> Dependency on the url is a really bad idea (&hellip;)

I agree.

> (&hellip;) the current method of including a string 'invalid' with the date also feels like a hack.

Not sure what you mean by this, do you mean what is seen when you run `certbot certificates`?

> The staging flag should also be passed to the server so it can confirm a match between the requested certificate type and the certificates the server issues is consistent.
> If you need to know if the server is staging before requesting a certificate then add a url to the protocol to check the type of server.

These suggestions would require an amendment to the ACME protocol, because as far as I can tell, such feature currently doesn't exist. Currently, the ACME protocol doesn't mention anything about staging or testing certificates. Currently, it's artificially generated by running multiple ACME servers without any ACME support itself. Good suggestions IMHO I might add, but I'm afraid it isn't something quickly done.

**Comment by bsutton** [comment]
@osirisinferi 

>  (…) the current method of including a string 'invalid' with the date also feels like a hack.

>> 'Not sure what you mean by this, do you mean what is seen when you run certbot certificates?

Yes. I assumed it was some hack in the date field.

If I read the article correctly it appears you can add custom fields:
https://dustinoprea.com/2014/04/18/adding-custom-data-to-x-509-ssl-certificates/

> but I'm afraid it isn't something quickly done.

My immediate problem is solved so I'm not looking for a quick solution, I'm looking for the correct solution.

I have to say that lots about certbot feel underbaked. It would be nice to see these sort of problems solved in the correct way , even if it takes longer.

**Comment by osirisinferi** [comment]
> Yes. I assumed it was some hack in the date field.

That's not directly from the certificate, the output from `certbot certificates` is all [formatted in Python](https://github.com/certbot/certbot/blob/ae2247163e42934c0486c36079bc7ae50bc4d4e2/certbot/certbot/_internal/cert_manager.py#L263-L309) with *some* information from the certificate.

> My immediate problem is solved so I'm not looking for a quick solution, I'm looking for the correct solution.

Well, I'm not sure if we've even established what the "correct" solution actually is to be honest :slightly_smiling_face:

**Comment by bsutton** [comment]
> Well, I'm not sure if we've even established what the "correct" solution
actually is to be honest 🙂

Maybe not but my point was that what we have now isn't correct and that
rather than put in a half baked solution let's find the correct one even if
it takes a bit longer to be released.

**Comment by bsutton** [comment]
So how does it determined that the certificate is a test certificate.

**Comment by ohemorange** [comment]
Ah, clarify, those tags were for the particular `revoke` issue that was fixed in #8591; additionally, I think we could always improve the wording of our errors, but we're probably not looking to fundamentally change how we handle certificates right now.

**Comment by lordspace** [comment]
I noticed that certbot saved staging certificates into /live/ folder when I did --manual set up.
I did request only for *.staging.qsandbox.net

# certbot --version
certbot 0.40.0

# lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal


root@staging:/mnt/hdd2/apps/qsandbox/staging.qsandbox.net/vhost# 
DOCUMENT_ROOT=/mnt/hdd2/apps/qsandbox/staging.qsandbox.net/htdocs certbot certonly \
> --manual \
> --test-cert \
> --webroot-path /mnt/hdd2/apps/qsandbox/staging.qsandbox.net/htdocs \
> --manual-auth-hook /home/slavi/orbisius_dns_manager \
> --manual-cleanup-hook /home/slavi/orbisius_dns_manager \
> --email admin+apps+qsandbox+stg@example.com \
> --rsa-key-size 4096 \
> --agree-tos \
> --manual-public-ip-logging-ok \
> -d '*.staging.qsandbox.net' | tee -a ssl_tests.log
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Obtaining a new certificate
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/staging.qsandbox.net-0001/fullchain.pem
   Your key file has been saved at:
   **/etc/letsencrypt/live/staging.qsandbox.net-0001/privkey.pem**
   Your cert will expire on 2022-11-22. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
