### ISSUE TITLE
Mention that config files come from Mozilla's ssl config generator

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#8670]
Based on the discussion in #8635, let's add a note to the comments in our Apache/Nginx TLS configuration file that the contents are based on https://ssl-config.mozilla.org/. That way, people who might be using this file can just grab directly from the source instead, since the source is intended for being directly in people's non-certbot-managed configurations, unlike our Apache/Nginx TLS configuration file.

**Comment by ohemorange** [comment]
We should do this, and this is also actually a good first issue for anyone looking.

**Comment by amplifi** [comment]
First time contributor. I can open a PR for this.
