### ISSUE TITLE
CERT_PEM_REGEX potentially incorrect

### ISSUE THREAD

**Issue by jvanasco** [certbot/certbot#8672]
While working on another client/certificate-manger that leverages some Certbot utilities, and an archive of LetsEncrypt certificates, I discovered a possible issue with the CERT_PEM_REGEX https://github.com/certbot/certbot/blob/master/certbot/certbot/crypto_util.py#L516-L524

The PEMs of the first two LetsEncrypt certificates (now retired) use boundary markers that end with a space character:
   * https://letsencrypt.org/certs/letsencryptauthorityx1.pem
   * https://letsencrypt.org/certs/letsencryptauthorityx2.pem
   
My reading of the RFC (https://tools.ietf.org/html/rfc7468#section-2) is that whitespace is insignificant (but recommended against) within encapsulation boundaries, but the encapsulation boundaries are strictly defined as the line beginning with five dashes, the BEGIN/END label, a space, the object label, and ending with five terminal dashes; as such trailing whitespace would not be permitted within this "line". 

If the original LetsEncrypt certificates are properly formatted, future certificates could appear in with trailing whitespace in the boundaries, so CERT_PEM_REGEX should be accordingly altered with something like ` *?`.

    CERT_PEM_REGEX = re.compile(
        b"""-----BEGIN CERTIFICATE----- *?\r?
    .+?\r?
    -----END CERTIFICATE----- *?\r?
    """,
        re.DOTALL,  # DOTALL (/s) because the base64text may include newlines
    )

All that being said, the correct interpretation of the RFC, whatever that is, is irrelevant.  The only thing that matters is Certbot and ISRG coming to an agreement on whether or not trailing whitespace should be allowed in the boundaries.

**Comment by ohemorange** [comment]
Nice catch, thanks! Do you know if any currently-valid certificates have this issue as well? I'm leaning towards sticking to what's specified in the RFC, as long as we know there aren't examples that we'll have to deal with in the wild in practice.

**Comment by alexzorin** [comment]
I [dropped a comment on the forums](https://community.letsencrypt.org/t/were-the-retired-x1-and-x2-pem-certificates-properly-formatted/145717/8?u=_az) explaining why whitespaces were not included in this regex.

**Comment by jvanasco** [comment]
> Do you know if any currently-valid certificates have this issue as well? 

None of the other ISRG certificates available on their web systems implement this detail.  No clients I have seen implement this detail either.  Looking at the archives of old certificates we use for testing, I believe some legacy clients either used this certificate as-is, or instructed users to download it from the website.

@alexzorin's note on the Forum references #7877 and implementing `stricttextualmsg` and not `textualmsg` as per the ACME RFC (8555).

ISRG pushed a fix and is more aware of these compatibility issues, so this should not happen in the fiture and this ticket should be safe to close.

**Comment by ohemorange** [comment]
That's what I like to hear! Thanks for catching this!
