### ISSUE TITLE
Certbot doesn't seem to pick the right architecture type on ARM64

### ISSUE THREAD

**Issue by RandomInsano** [certbot/certbot#8679]
## My operating system is (include version):

Amazon's ARM64 version of Ubuntu 20.04

```
me@ip-172-31-7-202:~/website-compose$ uname -a
Linux ip-172-31-7-202 5.4.0-1037-aws #39-Ubuntu SMP Thu Jan 14 02:53:31 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
me@ip-172-31-7-202:~/website-compose$ cat /etc/issue
Ubuntu 20.04.2 LTS \n \l
```

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Docker from both of these:
* certbot/certbot:arm64v8-latest (works)
* certbot/certbot (grabs x86_64 I assume)

## I ran this command and it produced this output:

`docker-compose up`

Output:

`standard_init_linux.go:211: exec user process caused "exec format error"`

## Certbot's behavior differed from what I expected because:

Seems to be trying to run the x64_64 version of some binary instead of the ARM64 version. I need to manually select ARM64 which is unlike the PHP, MariaDB, nginx docker images that make up the whole system.

## Here is a Certbot log showing the issue (if available):

Not much luck with this command:
```
# docker cp docker-compose_certbot_1:/var/log/letsencrypt /tmp
Error: No such container:path: docker-compose_certbot_1:/var/log/letsencrypt
```

Despite the weird wording on the error, the format of the command seems correct as I can copy files _into_ that container with it.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

Not applicable here.

## Other stuffs

Here's an older version of this error which was using the wrong tag ("latest" in that case):
https://github.com/certbot/certbot/issues/6878

Tagging does seem to work, so I'm not blocked now. It's just odd that certbot is the only piece that didn't automatically select ARM64 for its architecture. I'm unfortunately unsure what magic is needed to get that working. Here are all the images I'm using:

```
$ grep -rn "FROM" *
certbot/Dockerfile:1:FROM certbot/certbot:arm64v8-latest
database/Dockerfile:1:FROM mariadb:latest
nginx/Dockerfile:1:FROM nginx:alpine
php-fpm/Dockerfile:2:FROM php:7-fpm-alpine
ssh/Dockerfile:1:FROM alpine
```

**Comment by alexzorin** [comment]
I believe this is the same as https://github.com/certbot/certbot/issues/8225. 

Certbot's images don't (yet) have multiarch support, which is still marked as an "experimental" feature in Docker.

**Comment by RandomInsano** [comment]
Definitely looks like it. I’m fine to close this one if you are. I’m a bit surprised that it’s so widely adopted if it’s experimental.

**Comment by alexzorin** [comment]
Great! Hopefully it'll leave experimental status soon, but if not, we could re-evaluate the decision to wait.

**Comment by adferrand** [comment]
Well, to be fair, it has been in experimental state for years, and still it is largely used in the docker community, including for the official and most used docker images.

This is certainly something that could be restudied in a near future in my opinion.

To post a piece of information somewhere about that, enabling manifests (which is what is required to build multiarch images) would be done in the easiest way along with buildkit, and with reduced boilerplate code with the official extension buildx that leverages buildkit.

However buildkit created some problems in the past when building the Certbot images, so one would keep that in mind while designing a new multiarch build approach.
