### ISSUE TITLE
Documentation about --elliptic-curve is outdated

### ISSUE THREAD

**Issue by tacerus** [certbot/certbot#8684]
Hi,

I only have an improvement concern for the documentation, sorry if this is the wrong place.

In https://certbot.eff.org/docs/using.html the following is stated:
`--elliptic-curve N    The SECG elliptic curve name to use. Please see RFC 8446 for supported values. (default: secp256r1)`

The specified RFC (https://tools.ietf.org/html/rfc8446#page-96 point 7.4.2) states the following 
`For secp256r1, secp384r1, and secp521r1, ECDH calculations (including parameter and key generation as well as....`

...suggesting those are the supported curves. However from from what I can tell, secp521r1 is no longer supported, rendering this documentation snippet misleading.

I suggest updating it to make it clear only secp256r1 and secp384r1 are supported (that is if there aren't any others which I am unaware of).

**Comment by alexzorin** [comment]
Hello @tacerus,

>However from from what I can tell, secp521r1 is no longer supported

What makes you say that `secp521r1` is not supported? It is certainly supported by Certbot today.

There was a bug before where `secp521r1` wasn't actually usable, but it was fixed in 1.12.

**Comment by tacerus** [comment]
@tacerus My bad - I received an error message upon trying to use it, and the only references in regards to certbot I found using a web search were the following text:

"Let’s Encrypt accepts RSA keys that are 2048, 3072, or 4096 bits in length and P-256 or P-384 ECDSA keys. That’s true for both account keys and certificate keys. You can’t reuse an account key as a certificate key." on https://letsencrypt.org/docs/integration-guide/ and a post about Chrome removing secp521r1, hence I concluded it was simply not (or no longer) supported in certbot - I failed checking if I was using a faulty version.

Thank you very much - possibly consider adding it in the integration guide!

**Comment by alexzorin** [comment]
Ah I see! We had a discussion about whether to update Certbot's documentation to mention that various restrictions on certificates are subject to the policies of the CA you are using (#8557) but eventually decided against it.

Explicitly documenting that P-521 keys are not supported, in the integration guide, might be reasonable, but it's not up to us. You could propose that change at https://github.com/letsencrypt/website/issues and see what the response is.

I'm going to close this issue as I don't think this is something for Certbot project to solve.

**Comment by tacerus** [comment]
@alexzorin Thanks for the input and sorry for the false alarm!
