### ISSUE TITLE
OSError ctypes.util.find_library() did not manage to locate a library called 'sndfile' 提示没有找到 'sndfile'，python2.7   pip install SoundFile==0.9.0.post1 仍然报错？

### ISSUE THREAD

**Issue by zhangxiudan** [certbot/certbot#8686]

**Comment by alexzorin** [comment]
Hi @zhangxiudan,

Certbot does not use `sndfile`. 

Did you encounter this error while using Certbot, or did you mean to open this issue on another project?

**Comment by zhangxiudan** [comment]
在另一个项目上打开此问题 ，第一次提问，抱歉哈 发布错误了

**Comment by alexzorin** [comment]
No problem!
