### ISSUE TITLE
unable to select alternative chain if CN is the same

### ISSUE THREAD

**Issue by rakkhin** [certbot/certbot#8688]
```
certbot --version
certbot 1.12.0

uname -a
Linux REDACTED 5.4.0-1040-azure #42~18.04.1-Ubuntu SMP Mon Feb 8 19:05:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

When using `certbot run -d 'somedomain' --preferred-chain 'Subject Common Name'` the expected behavior is to receive new certificate issued using chain anchored at root certificate with CN = Subject Common Name, but when CA offers multiple chains like this:
```
Primary Chain                          Alternative Chain
----------------------------------------------------------
ROOT                                   Subject Common Name
\/                                     \/
Subject Common Name                    Intermediate
\/
Intermediate
```

certbot will pick first chain returned by CA, making it impossible to use alternative chain. First example that comes to mind is Let's Encrypt staging CA, which served two chains in that configuration:
* primary chain's root certificate CN = (STAGING) Doctored Durian Root CA X3 signs CN = (STAGING) Pretend Pear X1, which in turn signs CN = (STAGING) Artificial Apricot R3, which is the issuing CA
* alternative chain's root certificate CN = (STAGING) Pretend Pear X1 signs CN = (STAGING) Artificial Apricot R3, which is the issuing CA

`certbot --apache -d "domain" --staging` produces the same result as `certbot --apache -d "domain" --staging --preferred-chain "(STAGING) Pretend Pear X1"`
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator apache, Installer apache
Renewing an existing certificate for domain
Deploying Certificate to VirtualHost /etc/apache2/sites-enabled/domain.conf

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Your existing certificate has been successfully renewed, and the new certificate
has been installed.

The new certificate covers the following domains: https://domain
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/domain/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/domain/privkey.pem
   Your certificate will expire on 2021-05-26. To obtain a new or
   tweaked version of this certificate in the future, simply run
   certbot again with the "certonly" option. To non-interactively
   renew *all* of your certificates, run "certbot renew"
```
certbot does not print out message about alternative chain not present and falling back to primary, but it will do that if preferred chain is specified using thumbprint, like this
```
certbot --apache -d "domain" --staging --preferred-chain "66493ba4f36d1731729b1118c7f5e2d540e3f37b"
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator apache, Installer apache
Renewing an existing certificate for domain
Certbot has been configured to prefer certificate chains with issuer '66493ba4f36d1731729b1118c7f5e2d540e3f37b', but no chain from the CA matched this issuer. Using the default certificate chain instead.
Deploying Certificate to VirtualHost /etc/apache2/sites-enabled/domain.conf

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Your existing certificate has been successfully renewed, and the new certificate
has been installed.

The new certificate covers the following domains: https://domain
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/domain/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/domain/privkey.pem
   Your certificate will expire on 2021-05-26. To obtain a new or
   tweaked version of this certificate in the future, simply run
   certbot again with the "certonly" option. To non-interactively
   renew *all* of your certificates, run "certbot renew"
```

The best solution would be to allow selecting alternative chains using either common name or certificate thumbprint, it won't break existing deployments and will allow resolving issue of ambiguity.

**Comment by alexzorin** [comment]
Hello @rakkhin,

>certbot --apache -d "domain" --staging produces the same result as certbot --apache -d "domain" --staging --preferred-chain "(STAGING) Pretend Pear X1"

Are you sure? I just performed the same test with Certbot 1.12, and it properly selects a different chain.

The first command saves the default staging chain (3 certs) and the second one selects the alternate chain (2 certs).

**Comment by rakkhin** [comment]
Just tested it today on fresh VM in Azure on Ubuntu 18.04.05, installed apache2 from main repo and certbot from snap, whole chain of events:
```
 history
    1  apt install apache2
    2  snap install --classic certbot
    3  ln -s /snap/bin/certbot /usr/bin/certbot
    4  certbot -h run
    5  certbot --apache -d "dom.x-kom.it" -n -m "REDACTED" --agree-tos --expand --staging --preferred-chain "(STAGING) Pretend Pear X1"
    6  history
```
and got
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator apache, Installer apache
Account registered.
Requesting a certificate for dom.x-kom.it
Performing the following challenges:
http-01 challenge for dom.x-kom.it
Enabled Apache rewrite module
Waiting for verification...
Cleaning up challenges
Created an SSL vhost at /etc/apache2/sites-available/000-default-le-ssl.conf
Enabled Apache socache_shmcb module
Enabled Apache ssl module
Deploying Certificate to VirtualHost /etc/apache2/sites-available/000-default-le-ssl.conf
Enabling available site: /etc/apache2/sites-available/000-default-le-ssl.conf
Enabled Apache rewrite module
Redirecting vhost in /etc/apache2/sites-enabled/000-default.conf to ssl vhost in /etc/apache2/sites-available/000-default-le-ssl.conf

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Congratulations! You have successfully enabled https://dom.x-kom.it
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/dom.x-kom.it/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/dom.x-kom.it/privkey.pem
   Your certificate will expire on 2021-05-27. To obtain a new or
   tweaked version of this certificate in the future, simply run
   certbot again with the "certonly" option. To non-interactively
   renew *all* of your certificates, run "certbot renew"
```
Everything is fine so far, but when trying to view cert chain of https://dom.x-kom.it/ i get
![image](https://user-images.githubusercontent.com/8458755/109276078-dd74d580-7815-11eb-8c8c-f28f3aedb316.png)
It's giving me cert issued using the long chain with expired root even though i specified `--preferred-chain "(STAGING) Pretend Pear X1"` on command line. I'm at a loss here.

**Comment by alexzorin** [comment]
First, thank you for endeavoring to provide reproduction instructions. It's very much appreciated!

>Everything is fine so far, but when trying to view cert chain of https://dom.x-kom.it/ i get

Ahhhhh! Unfortunately, browsers do not accurately show what the actual certificate chain is. What is shown in your screenshot is subject to some weird caching/key sharing heuristics inside the browser.

It can be very misleading at times, especially when cross-signs are involved. I recommend using other tools to check your server's chain.

e.g. in the below, you can see there are only two certificates, no Doctored Durians anywhere:

    $ openssl s_client -connect dom.x-kom.it:443
    CONNECTED(00000003)
    depth=1 C = US, O = (STAGING) Let's Encrypt, CN = (STAGING) Artificial Apricot R3
    verify error:num=20:unable to get local issuer certificate
    verify return:1
    depth=0 CN = dom.x-kom.it
    verify return:1
    ---
    Certificate chain
    0 s:CN = dom.x-kom.it
      i:C = US, O = (STAGING) Let's Encrypt, CN = (STAGING) Artificial Apricot R3
    1 s:C = US, O = (STAGING) Let's Encrypt, CN = (STAGING) Artificial Apricot R3
      i:C = US, O = (STAGING) Internet Security Research Group, CN = (STAGING) Pretend Pear X1

**Comment by rakkhin** [comment]
Omg, that clarifies everything. Thank you very much for pointing out this behavior to me.

Still, I would be nice to be able to specify preferred chain by thumbprint.
