### ISSUE TITLE
Offer non-snapd installation instructions

### ISSUE THREAD

**Issue by kallisti5** [certbot/certbot#8698]
By requiring snapd, certbot is now requires installing snapd on systems which can be already limited on memory.
It seems pretty odd to be honest to require installing an entire package subsystem for a set of python scripts.

As a user story:
* VM with 1GiB of ram running nginx (common cheap vm @ hosting providers)

certbot's native python scripts and nginx run fine here. With this snapd requirement change, you now no longer have enough ram to run nginx and certbot

## My operating system is (include version):
ArchLinux, Fedora, CentOS, BSD

**Comment by alexzorin** [comment]
Hello,

This is tracked by #8422 for our first-party non-snap instructions. 

You also have the option to use packages from AUR/EPEL/Ports, respectively, though those won't necessarily all be the primary installation method on our instruction generator.
