### ISSUE TITLE
Break snap builds into different jobs by architecture

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8700]
Erica suggested this at https://opensource.eff.org/eff-open-source/pl/xjp8kdjnib839remmyphcgf1oh. I think the main benefit here is we will no longer have the problem of trying to build the same snap multiple times with different architectures failing each time. With this approach we build the architectures separately so the job will pass for the snap if it is successfully built.

**Comment by bmw** [comment]
@adferrand, were you wanting to work on this? I think you expressed interest in Mattermost.

Either way is fine, I just wanted to make sure we're all on the same page.

**Comment by adferrand** [comment]
Yes I confirm.
