### ISSUE TITLE
Regularly scan Certbot's pinned dependencies for security vulnerabilities

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8705]
Looking at pages like https://github.com/certbot/certbot/network/dependencies, I don't think GitHub is monitoring Certbot's Python dependencies that we pin in `tools/certbot_constraints.txt`, `tools/dev_constraints.txt,` and `tools/pipstrap_constraints.txt` for security vulnerabilities. I think doing this is especially important now that we're relying more on our own distribution methods that bundle these dependencies than OS packaging.

Two of the possibilities to fix this are to reorganize things so GitHub scans these files or find another tool/way to regularly scan our list of pinned dependencies in something like CI.

**Comment by zoracon** [comment]
As a trick in the past, I have made "shadow files" that Github will pick up on if I couldn't immediately rename the dependency file to `requirements.txt` for some other reason at the time.

**Comment by jvanasco** [comment]
Github will read the files referenced in a toplevel `/requirements.txt`, so you should be able to simply list the relative paths to the existing per-project requirements files and not aggregate them all in a system that may be harder to maintain like you did in #8741 . 

for reference, here is what warehouse (PyPi.org) does:

* https://github.com/pypa/warehouse/blob/aafc5185e57e67d43487ce4faa95913dd4573e14/requirements.txt

and you can see them built into the scanned graph here:

* https://github.com/pypa/warehouse/network/dependencies

**Comment by bmw** [comment]
Thanks for the info. I don't think we have clean, existing per-project requirements files though. Instead what we currently have is a somewhat strange custom system with multiple levels of files used as constraints that override each other in different ways depending on the context using custom code. Check out [pip_install.py](https://github.com/certbot/certbot/blob/fa25d8356d8b5ae3c454f13ccd3e1d371d873f75/tools/pip_install.py) if you're really interested.

The end goal of the direction I took in #8741 is essentially two files:`requirements.txt` and `oldest-constraints.txt`. Either of these files is the sole file passed to `pip` as constraints depending on the context.

If you have specific concerns about the maintainability of #8741, I'd be interested to hear them, but I personally prefer the approach I took there over what warehouse does for our particular project and use cases.

**Comment by jvanasco** [comment]
> If you have specific concerns about the maintainability of #8741, I'd be interested to hear them

My concern with maintainability was just in creating the administrative tools and source files.  I didn't realize you already had code like `pip_install.py` that can analyze and create reporting/generating requirements in place, and that must of this was automated. I agree, you landed on a much better solution.

**Comment by bmw** [comment]
Thanks for taking the time to provide feedback!

I do dislike how much custom tooling there still is in #8741, but it was the simplest solution I was personally able to come up with. I think the main reasons it's tricky for us are:

1. We have many different Python projects all in one repo.
2. We want to pin dependencies across a wide variety of environments such as our snaps, Docker images, and Windows installer.

If you're really curious, take a look at https://github.com/certbot/certbot/issues/8290 and https://docs.google.com/document/d/12AP7JfY_uq0QAt-dwqdUX4NYUtjQ-MmDTS8ldoLI38I/edit?usp=sharing where I wrote about these problems in a lot more detail.
