### ISSUE TITLE
Using --reuse-key doesn't seem to reuse the key

### ISSUE THREAD

**Issue by paladox** [certbot/certbot#8710]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Debian 10

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt

## I ran this command and it produced this output:
certbot --force-renewal --reuse-key --expand  --no-verify-ssl -q --noninteractive renew --cert-name <domain>

## Certbot's behavior differed from what I expected because:
I expect that when I supply --reuse-key it should reuse the private key but generate a new certificate.

The renewal config:

```
# renew_before_expiry = 30 days
version = 0.31.0
archive_dir = /etc/letsencrypt/archive/xxx.pl
cert = /etc/letsencrypt/live/xxx/cert.pem
privkey = /etc/letsencrypt/live/xxx/privkey.pem
chain = /etc/letsencrypt/live/xxx/chain.pem
fullchain = /etc/letsencrypt/live/xxx/fullchain.pem

# Options used in the renewal process
[renewalparams]
authenticator = webroot
webroot_path = /var/www,
server = https://acme-v02.api.letsencrypt.org/directory
rsa_key_size = 4096
account = xxxx
[[webroot_map]]
```

We use certbot version: 0.31.0

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

I do see:
```
2021-03-10 01:44:39,993:DEBUG:certbot.storage:Writing new private key to /etc/letsencrypt/archive/xxx/privkey14.pem.
2021-03-10 01:44:39,995:DEBUG:certbot.cli:Var reuse_key=True (set by user).
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

```
	location /.well-known/acme-challenge/ {
		alias /var/www/challenges/;
		try_files $uri =404;
	}
```

We are trying to get it so existing private keys are used by only generating a new certificate.

**Comment by osirisinferi** [comment]
How have you tested the private keys for being different?

**Comment by paladox** [comment]
Sorry for wasting your time. We've discord that the certificates had a different private key. We just updated all the certificates which has fixed the issue.

**Comment by Iizuki** [comment]
I too thought for a while that `--reuse-key` didn't work, as new key files kept popping. Turns out they are indeed identical. Not what I expected, but ohh well.

This is still somewhat inconvenient for maintaining file permissions on keys.
