### ISSUE TITLE
cannot snap-exec

### ISSUE THREAD

**Issue by felix-albrecht** [certbot/certbot#8721]
## My operating system is (include version):
Ubuntu 20.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
snap

## I ran this command and it produced this output:
Certbot ran just fine up until now.
running certbot gives `cannot snap-exec: cannot exec "/snap/certbot/1043/bin/python3": no such file or directory`.

The path links over several symbolic links to `/snap/certbot/1043/usr/bin/python3.8` which is a file I can open.
But just running `/snap/certbot/1043/usr/bin/python3.8` again gives `no such file or directory`.

Certbot log shows nothing. I don't know if this is the right place to ask, no-one on the web seems to have this issue...

`snap list` shows

Name.        Version  Rev    Tracking       Publisher     Notes
certbot       1.13.0   1043   latest/stable  certbot-eff✓  classic
core            16-2.49  10862  latest/stable  canonical✓    core
core20        907    latest/stable  canonical✓    broken
hello-world 29     latest/stable  canonical✓    broken

**Comment by ohemorange** [comment]
This looks like a breakage in the core20 snap. They're released on a percentage basis, and it looks like you're in the testing category, since my machine is showing "core20 904". You may want to try posting on the snap forums about this. If you need certbot urgently, you can try installing everything (including the core20 snap) using the `--beta` flag, or use our `pip` instructions found at https://certbot.eff.org/ by selecting `pip` from the `System` dropdown.

**Comment by gopromaster** [comment]
Thanks for the tip. I've already posted on the [snap forum](https://forum.snapcraft.io/t/certbot-cannot-snap-exec/23475), let's see if someone knows something.

**Comment by whaikupu** [comment]
Hi all; I just tried "certbot --apache" and have be rewarded with the same error. "snap list" shows this:

Name              Version    Rev    Tracking         Publisher     Notes
amazon-ssm-agent  3.0.529.0  3552   latest/stable/…  aws✓          classic
certbot           1.13.0     1042   latest/stable    certbot-eff✓  classic
core              16-2.49.1  10908  latest/stable    canonical✓    core
core18                       1988   latest/stable    canonical✓    broken
core20                       904    latest/stable    canonical✓    broken
ffmpeg                       1286   latest/stable    snapcrafters  broken
lxd                          19647  4.0/stable/…     canonical✓    broken

Any thoughts/ pointers/ etc?

D.

**Comment by ohemorange** [comment]
This is very strange -- any hints on something I could try to get a repro on my end? Have you installed or uninstalled anything else recently? Have you ever had a different version of certbot installed on the macchine?

Also, have you tried uninstalling and reinstalling the listed snaps? Your existing certs should not be affected.

**Comment by gopromaster** [comment]
I un- and reinstalled certbot, core20, hello-world (using `snap remove`), and now it works. Let's hope it stays that way.

As to why it happened in the first place - I believe I didn't install anything else, so I have no clue...

**Comment by ohemorange** [comment]
Thanks for trying that, glad to know at least we now have a recommend should others encounter this!

**Comment by ethaniel** [comment]
Looks like certbot decided to update on it's own without me giving it permission. As a result I got 2 errors:
1. internal error, please report: running "certbot" failed: cannot find installed snap "certbot" at revision 1201: missing file /var/lib/snapd/snap/certbot/1201/meta/snap.yaml

So I deleted and reinstall certbot, got:
2. cannot snap-exec: cannot exec "/var/lib/snapd/snap/certbot/1280/bin/python3": no such file or directory

Then I did `snap remove certbot core20` and reinstalled certbot and now it's working ok.

Guys, seriously, stop fucking with this stuff. First the questionable snapd solution, now - unpredictable updates.

**Comment by Kramerican** [comment]
Saw this today.

Tracked it down to snap doing an auto-refresh on boot, which can take a while on some systems. Check with `snap changes` and `snap tasks`. Once the auto-refresh is done, Certbot can be run normally.

**Comment by synalice** [comment]
Got the same problem.
Output of `snap list`:
```bash
Name     Version      Rev    Tracking         Publisher     Notes
certbot  1.29.0       2192   latest/stable    certbot-eff✓  classic
core     16-2.56.2    13425  latest/stable    canonical✓    core
core18   20220706     2538   latest/stable    canonical✓    base
core20   20220719     1587   latest/stable    canonical✓    base
lxd      5.4-82d05d6  23339  latest/stable/…  canonical✓    -
snapd    2.56.2       16292  latest/stable    canonical✓    snapd
```

**Comment by synalice** [comment]
I removed snaps `lxd`(required by `core20`), `core20` and `certbot` itself, then reinstalled Certbot with `snap install --classic certbot` and the issue was solved.

**Comment by killmasta93** [comment]
hi guys i was wondering if someone can shed some light having same issue no ideas why 

`cannot snap-exec: cannot exec "/snap/certbot/3024/bin/python3": no such file or directory`

i removed it 

`snap remove certbot`

and reinstalled it 
`
sudo snap install --classic certbot`

still same issue any ideas what else?

**Comment by wgreenberg** [comment]
@killmasta93 could you post your OS version & result of `snap list`?

**Comment by killmasta93** [comment]
hi @wgreenberg 
currently using ubuntu 18.04 LTS
```

root@mail:/snap# snap list
Name    Version    Rev    Tracking       Publisher   Notes
core    16-2.59.5  15511  latest/stable  canonical✓  core,disabled
core20  20230801   2015   latest/stable  canonical✓  base

```

**Comment by killmasta93** [comment]
solved it updated snapd

```
root@mail:~# snap list
Name     Version    Rev    Tracking       Publisher     Notes
certbot  2.6.0      3024   latest/stable  certbot-eff✓  classic
core     16-2.60.2  15925  latest/stable  canonical✓    core
core20   20230801   2015   latest/stable  canonical✓    base
snapd    2.60.2     19993  latest/stable  canonical✓    snapd

```

**Comment by wgreenberg** [comment]
glad to hear it!

**Comment by ccriptdev4** [comment]
Facing same issue

`cannot snap-exec: cannot exec "/snap/certbot/3700/bin/python3": no such file or directory`

this is my snap list

```
Name     Version    Rev    Tracking       Publisher     Notes
certbot  2.10.0     3700   latest/stable  certbot-eff✓  classic
core     16-2.61.2  16928  latest/stable  canonical✓    core
core20   20240111   2182   latest/stable  canonical✓    base
```
