### ISSUE TITLE
Problems with nginx with many configs 

### ISSUE THREAD

**Issue by windos32** [certbot/certbot#8735]
Hi!
I am use centos 8.3.
The problem is in certbot 1.13.0 installed with the of snap, as well as in version certbot 1.12.0 installed using the EPEL repository.
This problem did not exist in certbot-auto, but now certbot-auto does not work ( 

I cannot issue certificates for my sites:
   Type: unauthorized
    Detail: Invalid response from
    https: //domain/.well-known/acme-challenge/d8oLXK4fO_xVYD7w1UvwHZ2v1UNc4TGzvz_Sptb8JfU
    [address]: "<html> \ r \ n <head> <title> 404 Not
    Found </title> </head> \ r \ n <body> \ r \ n <center> <h1> 404 Not
    Found </h1> </center> \ r \ n <hr> <center> nginx </center> \ r \ n "

In my case, nginx has a lot of  small configuration files .conf, it looks like this is causing problems for certbots. Now I have 1000+ config files, if I reduce them to about 500, then the certificate is issued normally. 

Please need help!

**Comment by windos32** [comment]
There are many more such errors in letsencrypt.log 

2021-03-24 14:32:42,318:DEBUG:certbot_nginx._internal.parser:Could not parse file: /etc/nginx/conf/settings/individual.conf due to Expected {Group:({[<SPC><TAB><CR><LF>] "#" rest of line}) | Group:(Forward: ...) | Group:({[<SPC><TAB><CR><LF>] {Combine:({{quoted string, starting with " ending with " | quoted string, starting with ' ending with '} ")" [Re:('(\\$\\{)|[^{;\\s]')]...}) | Combine:({Re:('(\\$\\{)|[^{};\\s\'\\"]') [Re:('(\\$\\{)|[^{;\\s]')]...}) | quoted string, starting with " ending with " | quoted string, starting with ' ending with '} [{<SPC><TAB><CR><LF> {Combine:({{quoted string, starting with " ending with " | quoted string, starting with ' ending with '} ")" [Re:('(\\$\\{)|[^{;\\s]')]...}) | Combine:({Re:('(\\$\\{)|[^{};\\s\'\\"]') [Re:('(\\$\\{)|[^{;\\s]')]...}) | quoted string, starting with " ending with " | quoted string, starting with ' ending with '}}]... [<SPC><TAB><CR><LF>] Suppress:(";")})} (at char 0), (line:1, col:1)

**Comment by alexzorin** [comment]
Hello @windos32,

Thank you for your report.

I think it would help to first determine whether this problem is only because of the size of your config, or because of what that configuration says.

1. Could you please try see whether running with `--nginx-sleep-seconds 30` allows you to issue a certificate with the full 1000 virtual hosts enabled?
2. Would you be able to please post the contents of the files that Certbot is triggering the "Could not parse file" error on, like `/etc/nginx/conf/settings/individual.conf`?

**Comment by windos32** [comment]
> * Could you please try see whether running with `--nginx-sleep-seconds 30` allows you to issue a certificate with the full 1000 virtual hosts enabled?
> 
> * Would you be able to please post the contents of the files that Certbot is triggering the "Could not parse file" error on, like `/etc/nginx/conf/settings/individual.conf`?

With this --nginx-sleep-seconds 30 - work! Thanks.

I want to clarify that I do not have 1000 virtual hosts ( } server ), , but 100, just each host contains additional configs (like settings, blacklists, etc. ). 
Could not parse file - It does not depend on the content of the file, it may even be empty.

**Comment by alexzorin** [comment]
>How i can add this --nginx-sleep-seconds 30 for snap.certbot.renew.service for autorenewal???

Hi @windos32,

Once you renew with this flag once, you should find it in the `/etc/letsencrypt/renewal/*.conf` for the certificate you renewed.

You can also put:

    nginx-sleep-seconds = 30

into `/etc/letsencrypt/cli.ini`,  to make it global.

**Comment by windos32** [comment]
> 
> 
> > How i can add this --nginx-sleep-seconds 30 for snap.certbot.renew.service for autorenewal???
> 
> Hi @windos32,
> 
> Once you renew with this flag once, you should find it in the `/etc/letsencrypt/renewal/*.conf` for the certificate you renewed.
> 
> You can also put:
> 
> ```
> nginx-sleep-seconds = 30
> ```
> 
> into `/etc/letsencrypt/cli.ini`, to make it global.

Ok, this work! Thx
