### ISSUE TITLE
Delete certbot-auto, letsencrypt-auto, and its signature

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8742]
One of `certbot-auto` and `letsencrypt-auto` in the root of our repo and `letsencrypt-auto-source/certbot-auto.asc ` are used to update the files at https://dl.eff.org such as https://dl.eff.org/certbot-auto. I think we should decide what behavior we want from that site (404 or continue to serve last version?), coordinate with tech ops to ensure we get this behavior without breaking things, and then delete the files.

**Comment by ohemorange** [comment]
Personally, I think we should continue to serve the last version in tandem with our decision to keep around the files that we release under the new git tags; that is, in a few months, look at statistics to see if any stragglers are actually still updating to the latest version, and when they're not, delete it all.

**Comment by bmw** [comment]
Serving the last version of the files from https://dl.eff.org works for me.

Do you also want to keep the files around in our GitHub repo for now though? I think we could talk with tech ops about continuing to serve those files and delete them from GitHub.

**Comment by ohemorange** [comment]
I was planning to decide that based on how techops is doing things. If it copies over the file anyway, it's not much work to stop doing that, but if it's just a symlink to the files on our github, I think it's ok to temporarily keep them around here.

**Comment by ohemorange** [comment]
Either this issue or #8812 (whichever comes later) should delete `tests/modification-check.py` and its callers.

**Comment by ohemorange** [comment]
You know, actually, I changed my mind and think there's no reason to be serving it there; we don't actually want people downloading a fresh copy of certbot-auto. I wonder if we should have it serve a readme pointing people to certbot.eff.org though. Also, we currently use that to host our PGP key, as mentioned in `certbot/docs/packaging.rst`. Do we still need to do that?

**Comment by bmw** [comment]
Serving 404s from https://dl.eff.org now is fine with me too.

> I wonder if we should have it serve a readme pointing people to certbot.eff.org though.

How would that work? https://dl.eff.org/certbot-auto changes from a script to a readme file?

> Also, we currently use that to host our PGP key, as mentioned in certbot/docs/packaging.rst. Do we still need to do that?

Good question. @FelixSchwarz and @nbebout, we originally started hosting our PGP key at https://dl.eff.org/certbot.pub because the Fedora maintainer Eli Young requested it [here](https://opensource.eff.org/eff-open-source/pl/77cjs51kptdwpxwwr93kkmdrky). Is that still useful for you all? Looking at https://src.fedoraproject.org/rpms/certbot/blob/f34/f/certbot.spec#_23, it doesn't look like you're using it to me.

**Comment by ohemorange** [comment]
> How would that work? https://dl.eff.org/certbot-auto changes from a script to a readme file?

Yes. Or maybe a script that when run, prints README contents.

**Comment by FelixSchwarz** [comment]
A publicly accessible GPG key is still useful for Fedora (and actually mandated). I think what happened is that I exported the GPG key manually in late 2019 because there was no publicly accessible GPG key and @elyscape then asked you (as per Fedora guidelines) to host your GPG key.

Unfortunately when you provided that I think he forgot to update the Fedora spec file. Until now I was not aware of a public GPG key URL/did not check what the certbot spec files where using.

I would like to use an https URL to your keyring as that makes it easier for others to verify the origin of the GPG key used to verify sources going into Fedora so if you could continue hosting these somewhere that would be great.

**Comment by bmw** [comment]
@FelixSchwarz, thanks for the info. I think we can easily leave our key at that URL.

> Yes. Or maybe a script that when run, prints README contents.

@ohemorange, I personally don't like changing the script to a README since I think many people and automated systems will try to execute it.

We could replace it with a new script, however, on a system that doesn't have an existing certbot-auto installation (which I assume would be the majority of people explicitly downloading the script from https://dl.eff.org), certbot-auto's output since December on all systems has been:
```
Skipping bootstrap because certbot-auto is deprecated on this system.
Your system is not supported by certbot-auto anymore.
Certbot cannot be installed.
Please visit https://certbot.eff.org/ to check for other alternatives.
```
This output could be better, but I'm personally not sure it's worth the effort to make a custom script just for https://dl.eff.org after almost 5 months of this behavior.

I personally think it's fine to just start serving 404s for these files and move on, but if we wanted to be more cautious, we could try to get download statistics for https://dl.eff.org to see how many requests we're still getting for these files to help guide our decision here. What do you think?

**Comment by FelixSchwarz** [comment]
@bmw I updated the Fedora spec files so they refer to https://dl.eff.org/certbot.pub (we are "caching" the file in Fedora's dist-git though). Thank you.

**Comment by ohemorange** [comment]
Given that we exit 1 after printing that message, I think it's safe to close it down now. I'll open a ticket with techops.

**Comment by ohemorange** [comment]
https://redmine.eff.org/issues/26739
