### ISSUE TITLE
Warning on stdout should be labeled as a warning

### ISSUE THREAD

**Issue by kenberland** [certbot/certbot#8745]
Reopening https://github.com/certbot/certbot/issues/6221

## My operating system is (include version): 

```
Ubuntu 14.04.6 LTS
4.4.0-124-generic #148~14.04.1-Ubuntu SMP Thu May 3 07:26:53 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

`Python 3.9.2, pip 21.0.1, certbot 1.13.0`

## I ran this command and it produced this output:

`certbot -q renew`

> Could not choose appropriate plugin for updaters: Could not select or initialize the requested installer apache.

This is a warning, I suppose, because the certificate was properly renewed.

## Certbot's behavior differed from what I expected because:

The warning is labeled as such in the log, but not on `stdout`.

> 2021-03-26 12:32:34,686:WARNING:certbot._internal.updater:Could not choose appropriate plugin for updaters: Could not select or initialize the requested installer apache.

**Comment by ohemorange** [comment]
This isn't quite a duplicate of #6221; that was about when the installer is set to `None`, whereas this is when the installer is set to `Apache`.

I have several questions here. First, why is it printing to `stdout` at all? I thought warnings shouldn't be shown. Do you have `-v` or something set in `/etc/letsencrypt/cli.ini`? (Would you mind posting the contents of that?)

Second, do the logs indicate why apache couldn't be selected or initialized? Would you feel comfortable uploading your (redacted) logs, or at least the relevant section?

Third, I see you're on the latest version of certbot -- which installation method did you use? Snap? Pip?

**Comment by kenberland** [comment]
Coming back to this, I'm pretty sure it's a combination that no other user will create. Feel free to ignore this and let me figure it out, post, and close.


1. I guess because of `-q`? The ini is empty:
```
$ cat /etc/letsencrypt/cli.ini 
# Because we are using logrotate for greater flexibility, disable the
# internal certbot logrotation.
```
2. Redaction will take some time.
3. I'm on `Ubuntu 14.04.6`. So I had to install `Python 3.9.2, pip 21.0.1`.  I installed with `pip3 install certbot`. Although I'm using configs from version `0.22.2`

**Comment by kenberland** [comment]
Getting back to this. I reinstalled with `pip install certbot-apache` making sure to set `PATH` and `LD_LIBRARY_PATH` for `Python 3.9.2` and the problem is resolved.

Sorry for the churn.

**Comment by ohemorange** [comment]
Thanks for posting your resolution, hopefully it will help someone else in the future!
