### ISSUE TITLE
Warn user for broken webserver configurations when deleting a certificate (after revoking)

### ISSUE THREAD

**Issue by osirisinferi** [certbot/certbot#8755]
Currently, when the user revokes a cert, it gets the following question:

https://github.com/certbot/certbot/blob/8759ccaecb69ea93c5b3c95f6af71bb9130117b1/certbot/certbot/_internal/main.py#L597-L602

Today, someone on the Community was left with a "catch 22" (broken webserver getting in the way of getting a new certificate): https://community.letsencrypt.org/t/had-to-revoke-some-certs-now-im-stuck/148574

I'm not sure what the generic cert delete command gives as a warning, but I would like to propose **adding a warning to every certificate deletion action in certbot** that it might leave your webserver configuration broken!

We've seen this quite often on the Community and not many users are aware of this fact.. Especially as certbot can perfectly do the HTTP to HTTPS transition, but is NOT able to transition back again from HTTPS to HTTP.

**Comment by alexzorin** [comment]
See also https://github.com/certbot/certbot/issues/6734.

**Comment by bmw** [comment]
There are additional ideas for how to deal with this problem at https://community.letsencrypt.org/t/certbots-cert-revocation-needs-an-update/148588.

**Comment by alexzorin** [comment]
I intend to tackle this soon. 

My plan is to extend the apache+nginx authenticators to detect if the lineage being deleted is in-use, and to stop (warn) the user with a list of the relevant vhost files.
