### ISSUE TITLE
Update our tools

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8782]
In https://github.com/certbot/certbot/pull/8741 I pinned back a number of our tools like pytest, coverage, etc. because updating them broke things. I think we should make things work with new versions of the tools, unpin the dependencies from `pyproject.toml`, and rebuild our requirements file.

To share some of the digging I did on different pieces of this:

### Updating pytest

I did some work on this in the `update-pytest` branch. The remaining problem is a somewhat spurious `ResourceWarning` caused by us not closing a file. I hit this problem almost every time I ran the tests in Azure, but was never able to reproduce the problem locally.

### Updating coverage

I think to continue to use `--cov-append`, we need `parallel=True` in our coverage config, but whether we set that option or stop using `--cov-append`, coverage seems to drop dramatically for a reason I didn't immediately understand. I switched to updating `pytest` first to rule out old versions of `pytest` being a problem.

**Comment by bmw** [comment]
@alexzorin, do you have any tips on how to track down the cause of `ResourceWarning` in our tests? The errors[[1](https://dev.azure.com/certbot/certbot/_build/results?buildId=4048&view=logs&j=4e0d8942-23d8-5aaa-8766-579d61fc3008&t=1d64c8f1-f045-5d47-521b-a4f5386bcdcd&l=678)][[2](https://dev.azure.com/certbot/certbot/_build/results?buildId=4034&view=logs&j=058d0a92-9016-58fa-921c-b79fa325e374&t=a9dc3d0b-d1f1-5ea5-ac3f-2cb535e7ad5b&l=624)] I'm getting are spurious and I'm doubtful the output accurately refers to the source of the problems here. I ask because you fixed some of these problems before in https://github.com/certbot/certbot/pull/8747.

**Comment by alexzorin** [comment]
Breakpoints and strace, which is probably not what you want to hear. Sorry.

**Comment by bmw** [comment]
No worries. Thanks for the quick response.
