### ISSUE TITLE
Confusing docs with HTTP-01 port and redirection

### ISSUE THREAD

**Issue by strowk** [certbot/certbot#8788]
Documentation here https://letsencrypt.org/docs/challenge-types/ 
says 
> Our implementation of the HTTP-01 challenge follows redirects, up to 10 redirects deep. It only accepts redirects to “http:” or “https:”, and only to ports 80 or 443.

and next 

> The HTTP-01 challenge can only be done on port 80

Could you please clarify that a bit? Is port 443 allowed or not? 

I'm trying to use webroot method.  My server always redirects from http to https and from 80 to 443. So the only way to get stuff is from https and port 443, everything else will be redirected. For some reason my approach does not work. I checked several times, if I place file in <webroot>/.well-known/acme-challenge/teststuff , it is correctly served on 
`https://<mydomain>:443/.well-known/acme-challenge/teststuff`

## My operating system is (include version):
ubuntu

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
docker

## I ran this command and it produced this output:
```
docker run -it --rm --name certbot \
    -v "/etc/letsencrypt:/etc/letsencrypt" \
    -v "${WEBROOT}:${WEBROOT}" \
    certbot/certbot certonly \
        --webroot -d "${DOMAIN}" \
        --webroot-path "${WEBROOT}"
```

`Timeout during connect (likely firewall problem)`

**Comment by bmw** [comment]
Sorry you're having trouble, but I don't think Certbot's issue tracker is the best place to answer questions about Let's Encrypt's practices. I'd recommend creating a post on Let's Encrypt's forum at https://community.letsencrypt.org/ where there is a much larger community familiar with both Let's Encrypt and Certbot who should be able to help you.
