### ISSUE TITLE
Certbot online user guide version seems to be lagging behind

### ISSUE THREAD

**Issue by osirisinferi** [certbot/certbot#8793]
Currently, it seems the [certbot user guide](https://certbot.eff.org/docs/using.html) is for 1.10.0 (the title still says it's for 1.11.0.dev, but I believe that should mean it's for 1.10.0). However, 1.14.0 is already released.

This was confusing for me, as I saw the CLI flag `--preconfigured-renewal` [on a Community thread](https://community.letsencrypt.org/t/certbot-dns-linode-in-cron-an-authentication-script-must-be-provided-with-manual-auth-hook-when-using-the-manual-plugin-non-interactively/149563), where I couldn't find it in the User Guide.

Now, I'm actually not sure if this flag is even *supposed* to end up in the User Guide, but it *is* a fact the version of the title isn't correct :stuck_out_tongue:

**Comment by bmw** [comment]
Yeah. This is a result of the website current using submodules that must be manually updated. See https://github.com/certbot/website/issues/682.
