### ISSUE TITLE
Clearly link to pip instructions on "Get Certbot" page

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#8798]
We don't seem to list them there, and we should. That page could probably use a larger overhaul, but this should be short and is necessary.

**Comment by bmw** [comment]
I think [we do in master](https://github.com/certbot/certbot/blob/master/certbot/docs/install.rst#pip) but the submodule needs to be updated. I created https://github.com/certbot/website/pull/706 to do that.

**Comment by ohemorange** [comment]
cry emoji, I had a whole thing where I was like did we not already do this?? but then couldn't find an issue for it. maybe we do need to revamp this system...

**Comment by bmw** [comment]
Yeah maybe. I agree with you all that it certainly could be worse, but I also dislike this manual process and the amount of bugs I just had to fix to try and get https://github.com/certbot/website/pull/706 mergeable.

**Comment by bmw** [comment]
I think this was fixed by https://github.com/certbot/website/pull/706.
