### ISSUE TITLE
Determine how the renewer will run given different installation methods

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#880]
We need to figure out how the renewer will be configured to run automatically regardless of how the user installs Let's Encrypt. When prepared for use with an operating system package manager, this setup should be done by the package maintainer.

If installed through something like PyPI, we should help the user with this configuration. This could be anything from providing documentation to attempting to automate the process for the user (after getting their approval). Another idea is to include crontabs, systemd timers, etc. with Let's Encrypt to help the user through the process. Regardless of how this done, we should help the user with this instead of leaving them to figure it out on their own.

**Comment by HLFH** [comment]
Cool. I would love systemd timers support. I don't use cron.

**Comment by GreatEmerald** [comment]
+1 for including a timer unit. The additional nicety of that is that the user needs to explicitly enable timers by default, as opposed to crontabs that run by default and are rather difficult to disable without confusing package managers.

**Comment by sandys** [comment]
hi,
is there a systemd timer documented anywhere (even if it is not used in the package). We are starting to use letsencrypt and we are baking this in our Docker images. Would love to have this in already.

**Comment by bmw** [comment]
`letsencrypt-renewer` (a separate executable from `letsencrypt`) is still under heavy development and is not ready for use. There are no cron tabs or systemd timers right now.

**Comment by pde** [comment]
Proposed solution for 0.4.0: print a URL to renewal documentation :)

**Comment by pde** [comment]
(Or print the documentation)

**Comment by pde** [comment]
Actually maybe we do still want some automation for this, but it's 0.5.0.

**Comment by schoen** [comment]
@bmw, do we still consider this a separate issue from #3522?

**Comment by bmw** [comment]
I don't think so.

Our supported methods of installation are OS packages, certbot-auto, and Docker.

Configuring renewal in OS packages is outside of our control, #3522 handles certbot-auto, and #6657 handles Docker.
