### ISSUE TITLE
Remove references to certbot-auto from docs

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#8813]
- `certbot/docs/install.rst` points to certbot-auto uninstall instructions
- `certbot/docs/uninstall.rst` certbot-auto uninstall instructions
- `certbot/docs/using.rst` certbot-auto is mentioned as a deprecated installation method that people might need to change the command in response to

At some point, we should probably remove these, possibly depending on how our usage statistics look.

**Comment by ohemorange** [comment]
This could use clean-up at this point.

**Comment by gurmatsinghsour** [comment]
@ohemorange Hey, is this issue resolved? if not then I would like to work on this. Also, would you like me to remove the documents file or do I have to remove some part of the mentioned file names.

**Comment by alexzorin** [comment]
Fixed by #9333.
