### ISSUE TITLE
Certbot Route53 without ListHostedZones

### ISSUE THREAD

**Issue by matiasgarciaisaia** [certbot/certbot#8816]
I've asked about this issue [in the forums](https://community.letsencrypt.org/t/certbot-route53-without-listhostedzones/150802).

Currently, certbot's route53 plugin requires [`route53:ListHostedZones`](https://github.com/certbot/certbot/blob/e7499374655e5e3ac1da2e3bec283710354a92be/certbot-dns-route53/examples/sample-aws-policy.json#L8) permission to perform the DNS challenge. That permission can't be restricted to a specific subdomain/hosted zone (it allows to list every domain in the user's AWS account), and is [only used to identify the Hosted Zone ID](https://github.com/certbot/certbot/blob/7f9857a81b7064d767f694e033b29dc4bb942406/certbot-dns-route53/certbot_dns_route53/_internal/dns_route53.py#L77-L105) the plugin has to update.

**I'd like to have an option to tell certbot the Hosted Zone ID via configuration (instead of the plugin looking for the ID itself), so the AWS User doesn't need the `route53:ListHostedZones` permission.**

In my specific use case, I'm trying to use certbot on a server shared with a third-party in which I can't perform an HTTP request (network policies don't allow incoming HTTP connections from the open internet to that server). So I'm willing to use the Route53 DNS challenge, but I'd like to restrict the credentials used so that they're only good to update only the required records - and avoid leaking extra info.

**Comment by bmw** [comment]
Thanks for digging into this @matiasgarciaisaia and offering to write a PR. I agree that being able to restrict your DNS credentials is valuable.

I don't think we'll accept a change like this right now though. In the next 6 months or so, we're planning on completely rethinking our approach to DNS plugins in Certbot and probably transitioning them to something else. Any additional features complicates that transition so we're effectively treating the plugins as frozen for now. I'm happy to leave this issue open for when that changes though.

In the meantime, you could fork the plugin and write a [3rd party plugin](https://certbot.eff.org/docs/using.html#third-party-plugins), but I think it'd probably be easiest for you to accomplish what you want by using the [manual plugin](https://certbot.eff.org/docs/using.html#manual) which allows you to provide your own executable command/script/program that Certbot will call and rely on to set up the challenge.

I'm sure this isn't exactly what you wanted to read, but I hope this helps!

**Comment by apeeters** [comment]
@matiasgarciaisaia Are you still considering working on this? I believe it is a very valid request: least privilege should always be preferred.

It might not be easy to implement though (given multi-domain certificates).

**Comment by matiasgarciaisaia** [comment]
I haven't done anything about it in the last two years, and it'll probably stay the same. I'd really love to, but it's not becoming a priority for now.
