### ISSUE TITLE
Add black code formatter and flake8 linter, remove pylint

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8818]
We'd like to use [black](https://black.readthedocs.io/en/stable/) to automatically format the Python code in this project, and replace pylint with flake8 for linting. See also [previous Mattermost discussion](https://opensource.eff.org/eff-open-source/channels/certbot/9w9qgwwxgjyqbq4f6fujet8fwo#).

A starting plan:

1. Introduce black to one project (e.g. `acme`).
  i. [Harmonize](https://github.com/psf/black/blob/master/docs/compatible_configs.md#formats) `.editorconfig` and black.
 ii. Get tox to run black for this project and fail if the output differs.
iii. Commit hooks? Update contributing guide?
2. Introduce flake8 to that project?
  i. [Harmonize](https://github.com/psf/black/blob/master/docs/compatible_configs.md#flake8) flake8 and black.
 ii. Get tox to run flake8 for the project and fail on any warnings.
iii. Rip out pylint for that project?
3. Repeat for remaining projects.
4. Remove pylint fully.

Some things to figure out:
- [ ] Preventing black's bulk changes from clobbering git history. [`git blame --ignore-revs-file=...`](https://github.com/psf/black#migrating-your-code-style-without-ruining-git-blame) is an option, but every developer would have to opt-in to this manually on their cloned repo. The GitHub code UI [doesn't support this](https://github.community/t/support-ignore-revs-file-in-githubs-blame-view/3256) either. Personally I use the web interface quite often while navigating blame; this is painful.
- [ ] Rewrite [our custom pylint plugin](https://github.com/certbot/certbot/blob/master/linter_plugin.py) as a flake8 plugin.
- [ ] Picking out some flake8 plugins. It seem that pylint "does more" than flake8 out of the box. Let's not lose any lints that we care about. Let's add those that make sense (like for the `unittest` PRs we've been merging).

cc @atombrella, if you have any thoughts on the approach.

**Comment by atombrella** [comment]
Outline of the approach seems good. I don't think `isort` is actively tested for in the pipeline; at least I don't see it in 
https://github.com/certbot/certbot/blob/master/tox.ini#L120-L128 There are a couple of different ways of importing stuff.

I can toy a bit around with the flake8 plugin. There are some tutorials on Medium and other places.

https://github.com/github/feedback/discussions/5033 I gave :+1: to this thread. @alexzorin I suppose you already did this.

Possible flake8 plugins to take into consideration:
- https://pypi.org/project/flake8-comprehensions/
- https://pypi.org/project/flake8-assertive/

Searching the web yields various curated lists of other plugins to consider.
