### ISSUE TITLE
Configuration File Update w/o Certificate Issuance

### ISSUE THREAD

**Issue by GriffinSoftware** [certbot/certbot#8822]
This is really more of a feature suggestion.

Over in the Let's Encrypt Community, we frequently see certbot users trying to make changes to their renewal configurations. Some try to edit the files manually, which often results in disaster. Others try to issue a certbot command to make the changes, which we usually recommend to avoid the former situation. The trouble is that in order to have the parameters actually written to a renewal configuration file, a certificate must actually be successfully issued, even if the user only wanted to reinstall their existing certificate! This leads to use of the dreaded `--force-renewal` parameter and the consequences thereof, which include, but are not limited to: hours of struggle, potential downtime due to hitting Let's Encrypt rate limits, and verbal lashings from some less polite community members that are often accompanied with an RTFM sentence.

It would be awesome if there were some way to run a certbot command to just update the renewal parameters *without* issuing a certificate. This could then be tested with `renew --dry-run`. The saving of the renewal parameters could even be contingent upon a successful dry run if deemed necessary.

It would be an added bonus if dry run would actually exercise the deployment hook so it could be tested without forced renewal or waiting two months.

Let's Encrypt Community: griffin

**Comment by alexzorin** [comment]
See also 

- #5828 for modifying renewal parameters without actually renewing
- #5658 for invoking hooks on dry runs

**Comment by GriffinSoftware** [comment]
It appears from the history both here and in the Let's Encrypt Community that demand for this functionally has remained strong for years. While I've been advocating for some time now the splitting of acquisition and installation functionality, perhaps there may be separate merit in creating a division in all aspects of configuration and live operation.

**Comment by ohemorange** [comment]
This is worth doing, but may be tricky because the code around it is a little complex.

**Comment by ohemorange** [comment]
So, I'm starting to look into this, and I've love to know what sort of changes people would want to be making. Is it what plugin they use for the cert? Hooks? Domains? (If it's domains, that's an even bigger reworking, as domains aren't currently saved in the renewal conf file at all, just in the cert, so we'd need a whole way to say "on the next cert, use these domains instead.") I see a change from nginx to webroot in one example, but I'd love to know what the most common asks are.

**Comment by ohemorange** [comment]
Some notes from a discussion about what to focus on here:

* Changing the domain list is not as important
* Changing the authenticator (like webroot path) is more important
* Might want to add renewal hook to existing cert, but could instead change authenticator to address the root problem
* Basically things we want to change are the ones that live in the renewal.conf
