### ISSUE TITLE
It's always a pain in the ass to install certbot for cloudflare

### ISSUE THREAD

**Issue by Nottt** [certbot/certbot#8823]
I have a script that install certbot for cloudflare with pip3. Everytime I run it there is a issue with some random package that i have to fix and break my automatic installation.

Installing from snap store? Well it succeed but I can't find the executable anywhere to call it...

Can we get at least a requeriments.txt for it so I can have it on my script and trust that it will really be installed? 

`pip3 install --upgrade --force-reinstall certbot-dns-cloudflare `doesn't work

**Comment by alexzorin** [comment]
Hi @Nottt,

Sorry to hear that. I think we have tried to address all of the problems you're hitting via the instructions on https://certbot.eff.org/instructions.

Are you the author of that install script or did you find it somewhere?

> I have a script that install certbot for cloudflare with pip3. Everytime I run it there is a issue with some random package that i have to fix and break my automatic installation.

It sounds like you might be installing these packages globally, which attracts a chance of conflicting with OS packages.

Instead, the [Certbot pip instructions](https://certbot.eff.org/lets-encrypt/pip-other) instruct you to use a virtual environment, which isolates dependencies in a reliable way. 

> Installing from snap store? Well it succeed but I can't find the executable anywhere to call it...

I think this question is probably answered by the [Certbot snap instructions](https://certbot.eff.org/lets-encrypt/snap-other), step 6 in particular.

**Comment by AkashicSeer** [comment]
It's a royal pain in the ass to install certbot period. So many damn steps I makes me wan to break things.
