### ISSUE TITLE
Can we retry more things in nightly tests to reduce failures?

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#8840]
We seem to hit spurious failures pretty often. We could either add some more general retries (maybe? I'd have to look into how best to do that in azure), or add retries whenever we see particular failures. Here are some failures from the past week:

spurious failure pushing snap to snap store
https://dev.azure.com/certbot/certbot/_build/results?buildId=3890&view=results

repeated network error downloading the rust code needed to compile cryptography
https://dev.azure.com/certbot/certbot/_build/results?buildId=3902&view=results

different snap failed 3 times for the same reason  :angry: 
https://dev.azure.com/certbot/certbot/_build/results?buildId=3902&view=results

yet another snaps has squashfs problems
https://dev.azure.com/certbot/certbot/_build/results?buildId=3902&view=results

**Comment by bmw** [comment]
I completely agree with you that Azure fails far too often.

I just wanted to add that the first 3 of these are already retried 3 times, although part of the first problem is apparently uploading snaps isn't always retryable. See https://dev.azure.com/certbot/certbot/_build/results?buildId=3890&view=logs&j=376285d6-0386-579f-1ddc-6416908765ca&t=f3c5e7e8-305a-5f5f-08e7-84cb522964d5&l=7381.

I think we could add a retry for the last one, but we'd need to restructure things a bit. There was a problem in the `snaps_build` job that wasn't caught until the `snap_dns_run` job. I think we essentially want to retry the snap build if tests on the snap failed. That certainly seems possible, but I'm not sure the best way to put all that in a large retry loop.
