### ISSUE TITLE
Webroot crashes on Windows

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8847]
## My operating system is (include version):

Clean install of Windows Server 2019

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

Windows installer

## I ran this command and it produced this output:

```
> certbot --staging --agree-tos --debug-challenges --register-unsafely-without-email -d windows.bmw.cbtesting2.com --webroot certonly
Saving debug log to C:\Certbot\log\letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Account registered.
Requesting a certificate for windows.bmw.cbtesting2.com
Performing the following challenges:
http-01 challenge for windows.bmw.cbtesting2.com
Input the webroot for windows.bmw.cbtesting2.com: (Enter 'c' to cancel): C:\inetpub\wwwroot
Cleaning up challenges
Encountered exception during recovery: FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\inetpub\\wwwroot\\.well-known\\acme-challenge\\vg6t3Te8rbrCVdQexfqAfePD2TCfcTTOkMYP_FLTu-A'
An unexpected error occurred:
pywintypes.error: (1307, 'SetFileSecurity', 'This security ID may not be assigned as the owner of this object.')
Please see the logfiles in C:\Certbot\log for more details.
```

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

https://gist.github.com/b59fb6c93502757e7b61fa4897155776

**Comment by webprofusion-chrisc** [comment]
The `C:\inetpub\wwwroot` folder and subfolders is usually administrator only (and SYSTEM), this helps prevent random/nefarious processes from injecting content into the users websites. While most files should be readable by any user, writing requires elevated privileges (just like `sudo`) even if you are signed in as Administrator.
