### ISSUE TITLE
Add--preconfigured-renewal flag to Certbot's cli.ini in EPEL package

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#8889]
In Certbot v1.9.0, the CLI flag --preconfigured-renewal was added (https://certbot.eff.org/docs/packaging.html):

`--preconfigured-renewal` should be included on the CLI or in cli.ini for all invocations of Certbot, so that it can adjust its interactive output regarding automated renewal (Certbot >= 1.9.0).

Certbot will be making use of this flag in its upcoming v1.16.0 release, in order to provide instruction to the user about automated renewal.

Certbot packages which include a cronjob or timer to perform automatic renewal should run with this CLI flag enabled.

One way to do this would be to include or merge it into the cli.ini file (similar to what the Debian package currently does to disable log rotation):

```
$ cat /etc/letsencrypt/cli.ini
preconfigured-renewal = True
```

The equivalent for debian is being tracking at https://bugs.launchpad.net/ubuntu/+source/python-certbot/+bug/1928311, but this still needs to be done for Fedora/redhat/EPEL. @FelixSchwarz do you think this could be added to the package?

**Comment by FelixSchwarz** [comment]
@ohemorange I'll have a look. Currently a lot of work on my plate so it can take a bit longer than I'd like. (cc  @nbebout just in case he'll work on this).

**Comment by FelixSchwarz** [comment]
I added [bugzilla issue #1971500](https://bugzilla.redhat.com/show_bug.cgi?id=1971500) so we do not forget this.

**Comment by ohemorange** [comment]
Thank you! Please let us know if any questions come up.

**Comment by bmw** [comment]
@ohemorange, do we only want to do this if the systemd timer is automatically enabled? For the longest time, our Fedora/EPEL packages shipped with a systemd timer but it was disabled by default. Last I heard, it was enabled by default in Fedora and they were going to look into if it could be done for EPEL. I never heard back or followed up to see if that happened, but I can if you like.

**Comment by ohemorange** [comment]
Yes, that's correct. I had thought it happened, but I might have just confused it with Fedora. Ideally with should both add this flag and enable it by default.

**Comment by bmw** [comment]
I just emailed Matthew Miller and Nick Bebout who were helping us with this for an update. If anyone here wants to be added to that thread, let me know.

For now, I only know for sure that Certbot's renewal timer is supposed to be enabled by default in the Fedora packages with the resolution of https://bugzilla.redhat.com/show_bug.cgi?id=1940211.

**Comment by bmw** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1986205 was opened to track Certbot's renewal timer being enabled by default with EPEL as well.

**Comment by FelixSchwarz** [comment]
I just checked our package and so far we are not shipping `/etc/letsencrypt/cli.ini` in our RPMs. I assume it is ok for certbot if we just ship `cli.ini` with only `preconfigured-renewal = True`?
We ship an [`/etc/sysconfig/certbot`](https://src.fedoraproject.org/rpms/certbot/blob/897f42fdfea686298df9e633e3684baae10dc9c0/f/certbot-sysconfig-certbot) file but I think that is not the right place to add the option...

Is the option harmful/bad for users if the timer is not enabled? (i.e. I'm not sure what the current state in EPEL is though it would be a bit easier if I can just push the same config for EPEL8 + Fedora)

**Comment by bmw** [comment]
Hey @FelixSchwarz. Sorry for the delayed response here. I missed the notification about this somehow.

> I just checked our package and so far we are not shipping /etc/letsencrypt/cli.ini in our RPMs. I assume it is ok for certbot if we just ship cli.ini with only preconfigured-renewal = True?

Yes that should be just fine.

> Is the option harmful/bad for users if the timer is not enabled?

Kind of. What this option controls is Certbot's output after a certificate is obtained. If `preconfigured-renewal` is set, we tell the user their certificate will be automatically renewed. If it's not, we tell the user that they should now set up automated renewal to keep their certificate from expiring.

**Comment by FelixSchwarz** [comment]
`certbot-1.18.0-2.el8` was pushed to stable so this issue should be fixed. Please let me know if I did not apply the change correctly :-)

**Comment by bmw** [comment]
`/etc/letsencrypt/cli.ini` looks good to me!

I don't understand how `certbot-renew.timer` is automatically enabled though. After updating and installing everything, I see:
```
# systemctl list-timers --all
NEXT                         LEFT          LAST                         PASSED    UNIT                         ACTIVATES
Wed 2021-09-29 21:55:29 UTC  10min left    n/a                          n/a       systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service
Wed 2021-09-29 22:05:54 UTC  20min left    n/a                          n/a       dnf-makecache.timer          dnf-makecache.service
Thu 2021-09-30 00:00:00 UTC  2h 14min left Wed 2021-09-29 21:05:36 UTC  39min ago unbound-anchor.timer         unbound-anchor.service

3 timers listed.
# systemctl status certbot-renew.timer
● certbot-renew.timer - This is the timer to set the schedule for automated renewals
   Loaded: loaded (/usr/lib/systemd/system/certbot-renew.timer; disabled; vendor preset: enabled)
   Active: inactive (dead)
  Trigger: n/a
```
Why doesn't `certbot-renew.timer` show up in that list and why doesn't isn't it listed as active/enabled?

**Comment by FelixSchwarz** [comment]
Thank you for testing. I'll check the certbot timer issues.

**Comment by bmw** [comment]
Thanks a lot Felix. I personally think next month is fine. I'll test this out again then.

**Comment by ohemorange** [comment]
Looking into this to see if we can close out this issue, I'm now seeing it show up in the list, but it's still saying `inactive (dead)`. Any thoughts as to why that might be?

```
$ systemctl list-timers --all
NEXT                         LEFT          LAST PASSED UNIT                         ACTIVATES
Fri 2022-03-11 01:35:38 UTC  1min 58s left n/a  n/a    systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service
Sat 2022-03-12 00:00:00 UTC  22h left      n/a  n/a    unbound-anchor.timer         unbound-anchor.service
n/a                          n/a           n/a  n/a    certbot-renew.timer          certbot-renew.service
n/a                          n/a           n/a  n/a    dnf-makecache.timer          dnf-makecache.service

4 timers listed.
```

```
$ systemctl status certbot-renew.timer
● certbot-renew.timer - This is the timer to set the schedule for automated renewals
   Loaded: loaded (/usr/lib/systemd/system/certbot-renew.timer; enabled; vendor preset: enabled)
   Active: inactive (dead)
  Trigger: n/a
```

**Comment by wgreenberg** [comment]
i think systemd timers/services are disabled by default on Fedora due to a policy (https://fedoraproject.org/wiki/Packaging:Systemd#Why_don.27t_we....), but if you run `systemctl start certbot-renew.timer`, it runs without issue:

```
[root@localhost-live liveuser]# systemctl status certbot-renew.timer
○ certbot-renew.timer - This is the timer to set the schedule for automated ren>
     Loaded: loaded (/usr/lib/systemd/system/certbot-renew.timer; enabled; vend>
     Active: inactive (dead)
    Trigger: n/a
   Triggers: ● certbot-renew.service
[root@localhost-live liveuser]# systemctl start certbot-renew.timer
[root@localhost-live liveuser]# systemctl status certbot-renew.timer 
● certbot-renew.timer - This is the timer to set the schedule for automated renewals
     Loaded: loaded (/usr/lib/systemd/system/certbot-renew.timer; enabled; vendor preset: enabled)
     Active: active (waiting) since Wed 2022-04-27 19:50:47 EDT; 12min ago
    Trigger: Thu 2022-04-28 05:54:03 EDT; 9h left
   Triggers: ● certbot-renew.service

Apr 27 19:50:47 localhost-live systemd[1]: Started This is the timer to set the schedule for automated renewals.
```

**Comment by bmw** [comment]
@FelixSchwarz, does this mean it's not possible to make `certbot-renew.timer` run by default when Certbot is installed? If so, I don't understand what https://bugzilla.redhat.com/show_bug.cgi?id=1940211 accomplished. Do you know what's going on here?

**Comment by bmw** [comment]
What about you @nb?

**Comment by bmw** [comment]
@FelixSchwarz, @nb: Any ideas here? If the timer isn't enabled by default, I think you all shouldn't be setting `preconfigured-renewal = True` in `/etc/letsencrypt/cli.ini`. That option causes Certbot to tell people that renewal will be handled for them automatically which isn't true if the timer isn't enabled.

**Comment by bmw** [comment]
I have no idea the status of this anymore, but since we've kicked this from milestone to milestone for 2.5 years and I see no user demand for changes here, I'm going to remove this from the current milestone.

**Comment by zoracon** [comment]
Closing, if demand comes up, we can reopen.

**Comment by scottjmaddox** [comment]
FWIW, I recently encountered this, and wanted to verify that it was actually set up to auto-renew. It wasn't, because the timer was inactive (dead). But `systemctl start certbot-renew.timer` appears to have resolved that. Perhaps the "Certbot has set up a scheduled task to automatically renew this certificate in the background." note could be expanded to mention that you might need to run `systemctl start certbot-renew.timer`?

**Comment by FelixSchwarz** [comment]
> FWIW, I recently encountered this, and wanted to verify that it was actually set up to auto-renew. It wasn't, because the timer was inactive (dead). 

The timer should be **enabled** (but not started). So after the next system restart, its should be working as expected. I am not sure why it is not started by default though and my time is just too limited to dive into that.
