### ISSUE TITLE
apache authenticator should authenticate all duplicate vhosts

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8890]
See https://community.letsencrypt.org/t/cant-renew-certificate/153274/3?u=_az. I've seen this a few other times as well.

The Apache authenticator needs to authenticate all of the virtual hosts which could match the requested domain, including duplicates and HTTPS ones.

#6729 fixed this for the most part, but there are seemingly still some edge cases left over.

Let's investigate and fix those.

**Comment by alexzorin** [comment]
Another one today https://community.letsencrypt.org/t/renewal-on-a-roundcube-config/153393/5?u=_az.

So I think what's happening is that `ServerName`, omitted in the `000-default.conf` file on Debian, is being default-evaluated at runtime to the `hostname` of the machine.

If this name happens to overlap with the requested certificate, there's basically a random chance that authorization will fail, because the authenticator will skip over this host.

If we get the authenticator to recognize this scenario, we might be able to fix this problem for our users.

**Comment by bmw** [comment]
What if we just always modified any nameless vhosts that are listening on the right port to respond to the challenge? This seems simpler and would cover all cases, however, there may be downsides or problems with this approach that I'm not thinking of.

**Comment by alexzorin** [comment]
Thanks. 

>What if we just always modified any nameless vhosts that are listening on the right port to respond to the challenge

Now that I read the authenticator more closely, it seems that this type of eager coverage is something the authenticator already does. When no vhosts match by name, we are scooping up every vhost on that port and configuring it (`_relevant_vhosts`).

So now I feel pretty good about extending that eagerness to the initial case: if we did match some vhosts by name, let's tack on all the nameless ones too. Otherwise, fallthrough to `_relevant_vhosts` as before.
