### ISSUE TITLE
nginx produces a warning when encountering an empty file

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8894]
In #8765 we increased the logging level of this error:

https://github.com/certbot/certbot/blob/78261dbae2571d9a52d6fee7ffc8802f1104aec9/certbot-nginx/certbot_nginx/_internal/parser.py#L219-L220

from `debug` to `warning`.

The problem is that this change interacts poorly with #7103 and produces this during the nginx plugin preparation phase:

    Could not parse file: FILE.conf due to Expected {Group:({[] "#" rest of line}) | Group:(Forward: {Group:({[] {Combine:({{quoted string, starting with " ending with " | quoted string, starting with ' ending with '} ")" [Re:('(\$\{)|[^{;\s]')]...}) | Combine:({Re:('(\$\{)|[^{};\s'\"]') [Re:('(\$\{)|[^{;\s]')]...}) | quoted string, starting with " ending with " | quoted string, starting with ' ending with '} [{ {Combine:({{quoted string, starting with " ending with " | quoted string, starting with ' ending with '} ")" [Re:('(\$\{)|[^{;\s]')]...}) | Combine:({Re:('(\$\{)|[^{};\s'\"]') [Re:('(\$\{)|[^{;\s]')]...}) | quoted string, starting with " ending with " | quoted string, starting with ' ending with '}}]... []}) Suppress:("{") Group:({[{{Group:({[] "#" rest of line}) | Group:(: ...)} | Group:({{{{[] {{Combine:({{{quoted string, starting with " ending with " | quoted string, starting with ' ending with '} ")"} [Re:('(\$\{)|[^{;\s]')]...}) | Combine:({Re:('(\$\{)|[^{};\s) | Group:({[] {Combine:({{quoted string, starting with " ending with " | quoted string, starting with ' ending with '} ")" [Re:('(\$\{)|[^{;\s]')]...}) | Combine:({Re:('(\$\{)|[^{};\s'\"]') [Re:('(\$\{)|[^{;\s]')]...}) | quoted string, starting with " ending with " | quoted string, starting with ' ending with '} [{ {Combine:({{quoted string, starting with " ending with " | quoted string, starting with ' ending with '} ")" [Re:('(\$\{)|[^{;\s]')]...}) | Combine:({Re:('(\$\{)|[^{};\s'\"]') [Re:('(\$\{)|[^{;\s]')]...}) | quoted string, starting with " ending with " | quoted string, starting with ' ending with '}}]... [] Suppress:(";")})} (at char 0), (line:1, col:1) 

If the user has any empty files included in their nginx config, they will always see this, and probably in their cronjob output too. 

We need to either revert the promotion of that message to `warning`, or actually fix the parsing problem in #7103 so it doesn't crash on empty files.

**Comment by alexzorin** [comment]
@ohemorange do you have a preference about fixing this? Re-muting parser errors, or fixing the parser?

Even if we change the parser to handle empty files, we'd still be loudly logging about other potential parsing errors. Those other errors, strictly speaking, may not affect authorization outcomes, as was  the case here.

I'm not really leaning one way or the other.

**Comment by ohemorange** [comment]
Hm, in my ideal world, we will only produce that error on cases where it might actually be a serious problem because we couldn't parse an important file, in which case a warning is appropriate. To get to that, we should match what nginx allows as closely as possible, meaning fixing #7103. Not sure how I missed #7103, should be an easy fix.

**Comment by ohemorange** [comment]
I created https://github.com/certbot/certbot/pull/8895 to fix #7103.

**Comment by alexzorin** [comment]
Fixed by #8895.
