### ISSUE TITLE
Feature Request: security headers in nginx

### ISSUE THREAD

**Issue by tjapro** [certbot/certbot#8902]
After issue https://github.com/certbot/certbot/issues/8882 become corrected, I wonder if it is possible to add automatically this headers in Nginx conf:

```
add_header Content-Security-Policy upgrade-insecure-requests;
add_header X-Content-Type-Options "nosniff";
add_header X-Frame-Options SAMEORIGIN always;
```

Other headers are welcome! 
PR's are welcome too!

> See more at https://infosec.mozilla.org/guidelines/web_security
> Through https://community.letsencrypt.org/t/unsupported-enhancement-ensure-http-header/153111/9
> Note: HSTS is already set by Certbot.

- My operating system is (include version): CentOs 7
- I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc): snap

**Comment by bmw** [comment]
Thanks for taking the time to express your interest in this.

I think Alex is correct at https://community.letsencrypt.org/t/unsupported-enhancement-ensure-http-header/153111/9 that supporting upgrade-insecure-requests in nginx might be easier now. Other headers like those you suggested could be possible too. I personally like https://infosec.mozilla.org/guidelines/web_security as a resource here.

With that said, there's a lot more security enhancements we could implement in Certbot beyond HTTPS with redirects, HSTS, and OCSP stapling. Doing more here is something we talk about pretty regularly, but for now we're just focused on polishing what we currently have so I doubt we'll implement this anytime soon. I'll leave this issue open though so people can do things like add :+1: reactions to your post to help us gauge user's interest in features like these.

**Comment by tjapro** [comment]
Thank you @bmw for your comment and suggestions.
I edited the description accordingly.

**Comment by tjapro** [comment]
Hello! It's true this issue is became stale for so long, but I'm guessing this will be useful.
