### ISSUE TITLE
OpenSSL config and Certbot compatibility issue (MinProtocol = TLSv1.3)

### ISSUE THREAD

**Issue by ammnt** [certbot/certbot#8905]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):

```
Distributor ID: Debian
Description: Debian GNU/Linux 10 (buster)
Release: 10
Codename: buster
Linux 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
OpenSSL 1.1.1d  10 Sep 2019
```

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
Snap:
`certbot  1.16.0 1201 latest/stable  certbot-eff✓  classic
`
## I ran this command and it produced this output:
`sudo certbot certonly --manual --preferred-challenges=dns -d 'test.ammnt.app' --rsa-key-size 4096 --key-type ecdsa --force-renewal`

```
An unexpected error occurred:
requests.exceptions.SSLError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1123)')))
```

## Certbot's behavior differed from what I expected because:

These directives has been added to the OpenSSL config file (/etc/ssl/openssl.cnf) before:

```
[default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
MinProtocol = TLSv1.3
CipherString = DEFAULT@SECLEVEL=2
Ciphersuites = TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
Options = ServerPreference,PrioritizeChaCha
```
Works fine if `MinProtocol = TLSv1.2` is installed. Same error with Certbot from Debian repos🤔

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
[letsencrypt.log .zip](https://github.com/certbot/certbot/files/6642829/letsencrypt.log.zip)

**Comment by alexzorin** [comment]
Hi,

It doesn't look like the https://acme-v02.api.letsencrypt.org endpoint currently supports TLS 1.3 clients.

You will have to ask this question on the community forums (https://community.letsencrypt.org/), because that infrastructure is managed by a separate team to the Certbot project.

Thanks.
