### ISSUE TITLE
Should `certbot install` update renewal params with the installer?

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8906]
While working on #6734 + #8755, I noticed something unintuitive about how `certbot install` works.

If you do something like:

    certbot certonly -d example.com --webroot -w /var/www/html
    certbot install --cert-name example.com -i apache

then the `renewalparams` won't be updated with the `installer`.

Consequently, at next renewal, the webserver won't be reloaded.

I think this is surprising.

It also causes a potential gap for the functionality I am working on. I am referencing the `installer` from the `renewalparams` to perform the "is this currently in-use?" check.

I don't know whether this is a significant edge case or not, but thought I'd pose the question anyway.

**Comment by ohemorange** [comment]
That seems reasonable to me at a high level. On an implementation level, I think we currently don't fully `reconstitute` all renewal config values on an `install` call, so if we're going to write it back out, we'd want to do that. And hopefully it doesn't interfere too poorly with our default detection mechanism, but no promises.

**Comment by GriffinSoftware** [comment]
Hmmm... does this (and several other things on the table of late) sound so familiar... 🤔

Ah... I wrote a rather grotesquely playful jab at @bmw back in September...

https://community.letsencrypt.org/t/discussion-the-certificate-handbook/133296/42?u=griffin
