### ISSUE TITLE
Need instructions for an old debian 7

### ISSUE THREAD

**Issue by realtebo** [certbot/certbot#8908]
We have an old debian 7 with apache which we cannot upgrade because customer doesn't pay upgrade.

I now need to switch to certbot/let's encrypt for certificates.

I am no able to find instructions on how to manually installa certbot-auto or similar on this old debian 7.

**Comment by alexzorin** [comment]
Hi,

Sorry! Debian 7 is simply too old. The Certbot project doesn't support end-of-life operating systems.

You might have better luck with one of the other options from https://letsencrypt.org/docs/client-options/ like acme.sh or lego.
