### ISSUE TITLE
Access denied on snap install certbot-dns-cloudflare on Debian 9 only

### ISSUE THREAD

**Issue by shivampaw** [certbot/certbot#8922]
## My operating system is (include version):
Debian 9 (tested on a fresh DO droplet)

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
snap

## I ran this command and it produced this output:
On a fresh Debian 9 Digital Ocean droplet:
```
apt update
apt install snapd
snap install core
snap refresh core
snap install certbot --classic
snap set certbot trust-plugin-with-root=ok
snap install certbot-dns-cloudflare
```

## Certbot's behavior differed from what I expected because:
```
error: cannot perform the following tasks:
- Run hook prepare-plug-plugin of snap "certbot" (run hook "prepare-plug-plugin":
-----
error: access denied
Only connect this interface if you trust the plugin author to have root on the system.
Run `snap set certbot trust-plugin-with-root=ok` to acknowledge this and then run this command again to perform the connection.
If that doesn't work, you may need to remove all certbot-dns-* plugins from the system, then try installing the certbot snap again.
-----)
```

This differs to #8182 because:
* the dns plugin was not installed beforehand
* this only seems to happen on Debian 9 (Debian 10 is working fine for me)
* it happens on a fresh Digital Ocean droplet

## Additional debugging:
If I `snap install hello-world` and run `snap run --shell` followed by `snapctl` in the shell the error received is:
```
error: snapctl cannot run without args
```

If I run that command in the certbot shell (`snap run --shell certbot`) the error received is:
```
error: access denied
```

## `snap version`
```
root@debian-s-1vcpu-1gb-lon1-01:~# snap version
snap    2.51
snapd   2.51
series  16
debian  9
kernel  4.9.0-15-amd64
```

**Comment by alexzorin** [comment]
Thank you for the report. I have submitted a bug at https://bugs.launchpad.net/snapd/+bug/1933392.

**Comment by alexzorin** [comment]
Hi @basak,

Are you able to say whether you have seen this affect anybody else or whether this is already on the radar at all? 

I wasn't able to find any similar reports on the snapcraft forum or launchpad.

Thanks!

**Comment by djmoto24** [comment]
Hi
We have a similar error, but after the installation microk8s.

**Comment by basak** [comment]
I've passed this on and I hope somebody will be able to investigate this soon.

**Comment by jrogers-strategiaanalytics** [comment]
I have the same error when running `sudo snap install certbot-dns-cloudflare` on a fresh google cloud debian 9 vm.

**Comment by danielburrell** [comment]
is there a workaround?

>The problem isn't new though, it must have been the case for a few years already, I suppose the affected snap didn't use snapctl before.

They make it sound like this is a known issue,  but it's not clear if there's a way round it.

**Comment by ohemorange** [comment]
Workaround:
1. Install a newer version of python, such as 3.9: https://tecadmin.net/how-to-install-python-3-9-on-debian-9/
2. Follow certbot's pip instructions: https://certbot.eff.org/lets-encrypt/pip-other

**Comment by anonymouse64** [comment]
Has anyone tried upgrading the version of the snapd debian package they have installed to something newer than 2.21?

**Comment by fgc0109** [comment]
I have same error

```
root@WIKIHOST-200916KN8THQ:~# snap install certbot-dns-cloudflare
error: cannot perform the following tasks:
- Run hook prepare-plug-plugin of snap "certbot" (run hook "prepare-plug-plugin": 
-----
error: access denied
Only connect this interface if you trust the plugin author to have root on the system.
Run `snap set certbot trust-plugin-with-root=ok` to acknowledge this and then run this command again to perform the connection.
If that doesn't work, you may need to remove all certbot-dns-* plugins from the system, then try installing the certbot snap again.
-----)
```

**Comment by danielburrell** [comment]
> Has anyone tried upgrading the version of the snapd debian package they have installed to something newer than 2.21?

The error occurs even after upgrading to the latest version.

**Comment by ohemorange** [comment]
Hey @basak, the wide-ranging launchpad bug was downgraded to medium. This is a new issue and in the core snap itself, so it feels weird to make a workaround just for certbot, which we'll otherwise have to do. Now that the priority is medium my understanding is that it won't actually be fixed anytime soon, would you say that's accurate?

**Comment by anonymouse64** [comment]
> The error occurs even after upgrading to the latest version.

What is the version of snapd debian package you have installed?

**Comment by alexzorin** [comment]
Closing because this should no longer happen with the latest version of the Certbot snap.
