### ISSUE TITLE
Python library OAuth2Client deprecated

### ISSUE THREAD

**Issue by grawlinson** [certbot/certbot#8926]
The [OAuth2Client](https://github.com/googleapis/oauth2client) library has been deprecated by Google since 2018, and there is a replacement library [google-auth](https://github.com/googleapis/google-auth-library-python).

https://github.com/certbot/certbot/blob/8b610239bfcf7aac06f6e36d09a5abba3ba87047/certbot-dns-google/certbot_dns_google/_internal/dns_google.py#L8

**Comment by ohemorange** [comment]
Thanks for letting us know. We would accept a well-written PR replacing the library.

**Comment by soham4abc** [comment]
I would like to work on this issue

**Comment by Tdowneydev** [comment]
> The [OAuth2Client](https://github.com/googleapis/oauth2client) library has been deprecated by Google since 2018, and there is a replacement library [google-auth](https://github.com/googleapis/google-auth-library-python).
> 
> https://github.com/certbot/certbot/blob/8b610239bfcf7aac06f6e36d09a5abba3ba87047/certbot-dns-google/certbot_dns_google/_internal/dns_google.py#L8

**Comment by mike-kfed** [comment]
Is there a release of the fixed version soon? Gentoo Linux will remove `dev-python/oauth2client` package beginning of March 2023 rendering e.g. the certbot-dns-google plugin unusable. I guess other distros will follow suit, as this old package is incompatible with modern Python versions.

**Comment by osirisinferi** [comment]
Yeah, I noticed my CI failing due to the fact `dev-python/oauth2client` is already masked (i.e.: not installable by default) in Gentoos package repository.

**Comment by osirisinferi** [comment]
Gentoo [has removed `dev-python/oauth2client` from their repository](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=96f18d1fb9e250cbfa3e2eb0d3129e5ee4d3b2d9), breaking `certbot-dns-google` for all Gentoo users.

@soham4abc could you please update #8928 as shown by Alex so the PR can be reviewed and merged?
