### ISSUE TITLE
Certbot delete with missing renewal configuration

### ISSUE THREAD

**Issue by GriffinSoftware** [certbot/certbot#8927]
This is a feature request driven by many problem cases encountered within the Let's Encrypt community.

We frequently encounter situations where certbot users have missing renewal configuration files. Attempting to use the `sudo certbot delete --cert-name X` route to remove the remaining cruft associated with the certificate results in an error. The only recourse is usually taking the gloves off and performing a dangerous series of `sudo rm -rf` commands to surgically remove the remaining cruft so that the certificate can be cleanly reissued and a new renewal configuration file written. Implementing this feature request in a "directory-name-only-blast" fashion would also aid in alleviating situations where certificate symlinks have become "cross-referenced" between certificates. It's almost always far easier to explain, safer, and faster to just detonate things with one certbot command then reissue with another than it is to edit configuration files and/or fix/restore symlinks.

**Comment by alexzorin** [comment]
I think this might tie into a broader discussion about the (currently not very useful) `update_symlinks` subcommand and improving the current error messages (`expected {0} to be a symlink`, `missing a required file reference`), which I was planning to take a look at soon.

It may turn out that nuking the lineage is the best thing to do, but I want to check out all the options.

**Comment by GriffinSoftware** [comment]
I concur about the less-than-usefulness of `update_symlinks`. I think I've had it help in about 15% of the cases where it has been called for. Not being able to recreate deleted symlinks accounts for the majority of the cases of uselessness.

**Comment by alexzorin** [comment]
I've been playing around a bit with the relevant error messages related to storage that crop up on the forum:

- `missing a required file reference`
- `expected {0} to be a symlink`
- `target {0} of symlink {1} does not exist`
- `error parsing {0}`
- `archive directory exists for`
- `live directory exists for`

My idea was to clarify these errors and include link to a new section in the documentation relating to "Troubleshooting storage errors". This section would basically explain that you shouldn't touch the storage directly, and that if you did, the only thing you can really do is manually (`rm`) delete the relevant files and start again. (Or ask for help to carefully restore the state).

However, reading over the threads on the forums and evaluating it against the text I had written, I'm not convinced that this is going to be worthwhile. I'm finding that the likely outcome is that users will have to reach out for help anyway. So, I think I am abandoning that idea.

Regarding `certbot delete` being more aggressive about cleaning up all files possibly related to a certificate after the user has done something bad to the storage, I think it's probably a fine idea. It might be safer to hide this behind a `--force` flag, but not necessarily so. I'm not planning to work on this though, so if anybody wants to pick up and write a PR, we'll review it.
