### ISSUE TITLE
Certbot documentation about ECDSA keys

### ISSUE THREAD

**Issue by yardissimo** [certbot/certbot#8935]
Certbot documentation section for [changing existing certificates from RSA to ECDSA](https://certbot.eff.org/docs/using.html#using-ecdsa-keys) states that you can simply add the following line to the Certbot's configuration file to obtain certificates with ECDSA keys in the future:

`key-type = ecdsa`

However, I noticed that Certbot kept autorenewing with RSA keys and deleting this line from the configuration file, so I obtained a different certificate with ECDSA keys using the command setting `--key-type ecdsa` to look at its configuration file.

Turns out that Certbot inserted this line:

`key_type = ecdsa`

The [Configuration file](https://certbot.eff.org/docs/using.html#configuration-file) section also refers to `key-type`:

> \# Use ECC for the private key
> key-type = ecdsa
> elliptic-curve = secp384r1

I just added `key_type = ecdsa` to the first configuration file and I'll wait 43 days to find out with the next autorenewal. No rush.

#### Certbot 1.17.0 on Ubuntu 20.04.2 LTS installed with snapd, Apache/2.4.41

**Comment by alexzorin** [comment]
Hello @yardissimo,

Thank you for reporting this.

>add the following line to the Certbot's configuration file to obtain certificates with ECDSA keys in the future

"Configuration file" here refers to the global `/etc/letsencrypt/cli.ini` file, not to the per-certificate renewal configuration file (e.g. `/etc/letsencrypt/renewal/example.com.conf`). 

The two configuration files types are not interchangeable.

Making the change as described in the documentation should work, provided that the right configuration file is chosen.

Of course, if the documentation is confusing in this respect, it should be changed for clarity.

Do you feel that I understood your issue correctly?

**Comment by yardissimo** [comment]
Absolutely @alexzorin

Now I got that both sections of the documentation actually refers to the **global configuration file** that generally is not present in default installations.

By "configuration file" in the RSA/ECDSA section, I mistakenly thought it was the per-certificate renewal configuration file, just like you described.

It was very easy and convenient to test that single line in the renewal config file to switch from RSA to ECDSA keys in the next autorenewal.

Maybe the documentation is missing that part about `key_type = ecdsa` in the per-certificate renewal config file if that's a valid method to accomplish the switch from RSA to ECDSA keys without a global configuration file including `key-type = ecdsa`.

if it isn't, then the documentation just needs some clarification about which config file is referring to.

Thanks again @alexzorin

**Comment by alexzorin** [comment]
> I think that's why I assumed that key-type = ecdsa from that global config file example could be set in the per-certificate renewal config file.

Ah yep, I see. The idea being implied here is very misleading; we should rewrite this.
