### ISSUE TITLE
Certbot can't parse Report-To headers

### ISSUE THREAD

**Issue by InterLinked1** [certbot/certbot#8943]
Running Apache 2.4, tried to run certbox on an existing system with LE certs and got:

The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('There has been an error in parsing the file /etc/apache2/sites-enabled/main.conf on line 84: Syntax error')

which corresponded to:

Header set Report-To: {"group":"default","max_age":31536000,"endpoints":[{"url":"https://redacted.report-uri.com/a/d/g"}],"include_subdomains":true}

Seems like it can't handle the braces used here, but as this is a valid header, it should account for that.

Commenting this out temporarily allowed the certbot wizard to proceed.

**Comment by alexzorin** [comment]
Hello,

Thank you for the report.

I think this is much the same issue as #7413 and would require a fix to Certbot's Apache configuration parser.

You can make Certbot happy by wrapping the JSON portion of the directive in single quotes:

```apache
Header set Report-To '{"group":"default","max_age":31536000,"endpoints":[{"url":"https://redacted.report-uri.com/a/d/g"}],"include_subdomains":true}'
```
