### ISSUE TITLE
document renew_before_expiry config file option

### ISSUE THREAD

**Issue by collinanderson** [certbot/certbot#8972]
Hi All,

I don't see `renew_before_expiry` documented anywhere. If it's a config file option it should be documented.

Thanks,
Collin

**Comment by alexzorin** [comment]
Thanks for reporting this. I more or less agree.

One challenge here is that the renewal file configuration options are de facto "undocumented" and don't seem to be covered by the compatibility guarantee (https://certbot.eff.org/docs/compatibility.html).

It's not super helpful that https://certbot.eff.org/docs/using.html#modifying-the-renewal-configuration-file acknowledges the existence of these options but stops there.

I will raise the question about what we could do to improve this part of the documentation.
