### ISSUE TITLE
macOS cron instructions don't work because Certbot isn't in the cron PATH

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8974]
Reported here: https://community.letsencrypt.org/t/certbot-macos-crontab-instructions-need-fixing/157215

The issue needs to be verified, but if installing Certbot via `brew` doesn't put `certbot` into the `$PATH` that the cron runs under, then we need to fix it.

The issue is present both on the instruction generator (https://certbot.eff.org/lets-encrypt/osx-other) and in the documentation (https://certbot.eff.org/docs/using.html#setting-up-automated-renewal).

**Comment by gitfu** [comment]
#### _If certbot is not in the crontab path_  here are three ways to fix it.

* __Change or Set PATH__  in the crontab file

```sh 
a@fumatica:~/threefive$ crontab -l
#
SHELL=/bin/sh
# This is the crontab PATH 
PATH=/bin:/sbin:/usr/bin:/usr/sbin 
HOME=/var/log
...
```
### OR

* Use the __absolute path__ instead of just calling certbot

```sh
/usr/local/bin/certbot renew
```
### OR

* Use  the __which__ command with back ticks

```sh
    `which certbot` renew
```

> This is not a problem with certbot, it's just how cron works.

**Comment by bmw** [comment]
I think this is correct. `$PATH` in cron on my system seems to be `/usr/bin:/bin` and Homebrew places Certbot under `/usr/local` on Intel Macs and `/opt/homebrew` on ARM Macs.

Maybe we can change:
```
echo "0 0,12 * * * root python -c 'import random; import time; time.sleep(random.random() * 3600)' && certbot renew -q" | sudo tee -a /etc/crontab > /dev/null
```
to
```
echo "0 0,12 * * * root python -c 'import random; import time; time.sleep(random.random() * 3600)' && $(command -v certbot) renew -q" | sudo tee -a /etc/crontab > /dev/null
```

**Comment by alexzorin** [comment]
Thank you.

That's a bit annoying because I was hoping to continue having unified instructions which would work even if a user moved between installation methods. i.e. Whatever is currently in the cron PATH is the right one.

Maybe:

1. For the macOS instruction generator, fix it with `command -v`.
2. For https://certbot.eff.org/docs/using.html#setting-up-automated-renewal, redirect macOS users to the instruction generator, just as we tell Windows users to ignore that section entirely.

Some context about https://certbot.eff.org/docs/using.html#automated-renewals: We direct users there as a "NEXT STEP" from the Certbot CLI  when `--preconfigured-renewal` is absent (pip, Homebrew, ?). It was already a bit borderline with bouncing users between the documentation and the instruction generator. Dealing with macOS in this way is going to further complicate the flowchart. I'm open to better suggestions about what to do. Maybe doing away with these generic instructions and more heavily emphasizing on the instruction generator once again.

**Comment by bmw** [comment]
Ah I see. That is a bit annoying. I was hopeful we could just symlink Certbot into `/usr/bin` like we do in our `pip` instructions, but `/bin` and `/usr/bin` are read only by default in macOS.

It's not the most elegant, but the majority of our users are on Linux by a large margin so I personally think your plan is fine for now.
