### ISSUE TITLE
indicate ERROR when printing errors

### ISSUE THREAD

**Issue by laf0rge** [certbot/certbot#8980]
As can be seen with "archive directory exists" in https://github.com/certbot/certbot/issues/5395, error messages are not clearly indicated as such.   certbot may internally raise an exception of type CertStorageError, but when that exception is printed to the user, nothing indicates that this is actually a fatal error.

I would like to suggest that whatever generic code is used to print exceptions in certbot will prefix those messages with a clear indication that a fatal error has just occurred.  "archive directory exists" looks completely innocent and doesn't even suggest that anything abnormal has just happened.

I would write a patch but after a quick glance I could not find any __str__ or __repr__ methods for those exceptions, so it's unclear to me how printing them actually works.

**Comment by alexzorin** [comment]
Thanks for reporting this.

For reference, the error looks like this in the latest Certbot:

![image](https://user-images.githubusercontent.com/311534/129108221-93144b6b-c465-4827-893e-280356454d43.png)

This error, and a number of other errors, need to be rewritten to be useful to the user. I think this would largely address the problem of clarify for users.

That's a work in progress but we would welcome PRs for any individual error message as well.

>I would like to suggest that whatever generic code is used to print exceptions in certbot will prefix those messages with a clear indication that a fatal error has just occurred

For some errors, Certbot prefixes the message with `An unexpected error occurred:`, and in other rare cases, `Exiting abnormally:`.

In other cases (namely, when the error descends from the base `certbot.errors.Error` class), no prefix is printed. I suppose the assumption here is that anything descending from that error type should be able to stand on its own.

As such, my suggestion is to just improve those error messages.

On the other hand, I don't know whether it still makes sense to differentiate errors like this. I think it's worth reviewing.
