### ISSUE TITLE
Make plan for Python 3.6 support

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8983]
I believe we were initially planning on not supported EOL'd Pythons, but EPEL is asking us not to do this and keep Python 3.6 support at https://bugzilla.redhat.com/show_bug.cgi?id=1813670. What are we going to do?

**Comment by osirisinferi** [comment]
I know I'm not part of the certbot team, but I *do* have a question:

If upstream (i.e.: Python) isn't going to support 3.6 "indefinitely" and the RedHat team is nevertheless going to support Python 3.6 until EPEL7s EOL, why should certbot upstream (i.e.: you) keep supporting Python 3.6? Why would you be responsible? If they want to keep 3.6 around against all knowledge, why should you bear the burden? My *personal* opinion is the burden should be with the one deciding against upstream decisions.
