### ISSUE TITLE
No way to update renewal config file without also renewing a certificate

### ISSUE THREAD

**Issue by raforg** [certbot/certbot#9003]
Various command line options make magical undocumented changes to the renewal configuration file. Sometimes, the user just wants to make changes to the renewal config files to affect subsequent renewals. But since the renewal config file format is deliberately undocumented, the only approved way to make the changes is via the command line, and it results in an unwanted certificate renewal. Only the change to renewal config file change is wanted. Please add a --no-renewal command line option (or similar) to suppress the renewal, while still performing the modification to the renewal config file.

**Comment by alexzorin** [comment]
I am going to close this in favor of https://github.com/certbot/certbot/issues/8822, but I welcome any additional comments there.
