### ISSUE TITLE
Letsencrypt, Certbot, Chirpstack, PostgreSQL12, Ubuntu 20.04

### ISSUE THREAD

**Issue by EES-IoT** [certbot/certbot#9007]
Hi,
We had a functional ChirpStack server integrated with PostgreSQL using MQTT bridge. Recently we have tried to obtain and install encryption and certificate generated from Letsencrypt and provisioned Certbot to renew it.

Proccedure we followed:
For Letsencrypt & Certbot:   https://certbot.eff.org/lets-encrypt/ubuntufocal-other 
                                              https://snapcraft.io/docs/snapcraft-overview 
For PostgreSQL:    https://pavelevstigneev.medium.com/postgresql-ssl-with-letsencrypt-b53051eacc22
                             https://loganmarchione.com/2020/10/securing-postgres-connections-using-lets-encrypt-certificates/

For Chirpstack: We took idea from ChirpStack forum:   https://forum.chirpstack.io/t/using-secure-websockets-with-basic-station/7166 

Problem: After the the generation of the certificate and configuring all the .conf and .toml files, the **ChirpStack UI** is not online. **PostgreSQL 12** is not active. [error: (code=exited, status=1/FAILURE)]

We are planning to start over the full encryption process. Could you please provide some handy instruction to make the **ChirpStac**k, **MQTT**, **PostgreSQL** work together after getting the Keys from Letsencrypt running on **Ubuntu 20.04**?

Thanks in advance!

**Comment by alexzorin** [comment]
Hi,

The Certbot issue tracker isn't really a place for support questions, sorry!

We have a community of users at https://community.letsencrypt.org/ who should be able to help you diagnose why Postgres is not starting after trying to secure it with a certificate. I encourage you to post your question there and any other community forum related to the software you're trying to run.
