### ISSUE TITLE
unable to run python setup.py install for pocketsphinx-python

### ISSUE THREAD

**Issue by umarfarouk98** [certbot/certbot#9012]
C:\Users\fyunu>cd pocketsphinx-python

C:\Users\fyunu\pocketsphinx-python>python setup.py install
running install
running build_ext
building 'sphinxbase._sphinxbase' extension
swigging deps/sphinxbase/swig/sphinxbase.i to deps/sphinxbase/swig/sphinxbase_wrap.c
C:\Users\fyunu\swig\swig.exe -python -modern -threads -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/win32 -Ideps/sphinxbase/swig -outdir sphinxbase -o deps/sphinxbase/swig/sphinxbase_wrap.c deps/sphinxbase/swig/sphinxbase.i
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
![visualC++](https://user-images.githubusercontent.com/55334829/131232892-62d63d46-e0c9-4782-8faa-6345a4e9b05e.jpg)

please anyone available to help me out ?

**Comment by umarfarouk98** [comment]
![vscode](https://user-images.githubusercontent.com/55334829/131232916-5cf7a627-5b17-403a-9c54-b2592897b7cc.jpg)
here is a picture of the versions of MSVC which i have installed on my pc but still getting the error after i restarted my pc several times

**Comment by alexzorin** [comment]
Hello,

This issue tracker is for the Certbot project.

You probably want to open an issue on the pocketsphinx-python project.

**Comment by umarfarouk98** [comment]
Yeah I thought I opened a new issue... My bad
