### ISSUE TITLE
Certbot errors out when an alternative chain returns a 404 file not found

### ISSUE THREAD

**Issue by osirisinferi** [certbot/certbot#9019]
I was looking at #434 and messed around a little bit with the Pebble code to actually provide relative URLs, so I could possibly fix #434. That included checking relative URLs relative to the base server URL (i.e., a relative URL starting with a `/`) *and* also relative to the current "file" (i.e., a relative URL starting *without* a `/`).

So I ended up with certbot trying to download `/certZ/certZ/f0fd6e693f016b/alternate/1`. Notice the double `/certZ/`, due to the fact that Pebble provided an **incorrect** relative URL (one without a `/` in the beginning, but starting with `certZ/`).

Of course the above URL returns a 404 file not found when queried at the ACME server in this case and yes, that is a gross misconfiguration of the ACME server to begin with obviously.

But should certbot error out when it encounters such a 404 file not found when trying to download the alternative chain? The option isn't called **preferred** chain without a reason of course: no guarantees.

So I'd think a *warning* is warranted, but certbot shouldn't quit with an error.

**Comment by alexzorin** [comment]
On balance, I agree.

One thing to note is that Certbot/`acme` will only try to download the alternate chains if explicitly requested (i.e. `--preferred-chain` is set). 

It's a bit unfortunate that making this change will result in Certbot replacing the installed certificate chain with the wrong chain (potentially breaking IoT devices or whatever).

It does seem better than the alternative though, which would be Certbot blowing through CA rate limits by repeatedly failing to persist a renewed certificate. We should, if possible, try really hard not to crash, after the CA has expended resources to issue a certificate.

I think we'd accept a PR to swallow+warn for errors when fetching alternate certificate chains.
