### ISSUE TITLE
Certbot failing on renewing on nginx

### ISSUE THREAD

**Issue by VirtuousDeath** [certbot/certbot#9028]
I am having trouble renewing my certificates in Ubuntu, not sure which version.
I am using Docker version of certbot which is broken.
I cant install plugins nor run --nginx from scratch.
I ran this command:
$ sudo docker exec -it $(docker ps --filter name=certbot -q) certbot certonly --standalone --agree-tos --renew-by-default -d domain.com
not only this, but any certification command is broken on nginx
it shows that the authorization failed, the log is the default authorization error on route not found.

My nginx config is simple and clean, the delay on restart is some seconds less than 20.
I cant seem to turn around this problem, the version of docker is broken, since I cant install plugins and it doesnt come from scratch.

I am running my server without certificates, which is problematic.
I dont wish to install nginx and certbot on my vps, the docker version has to be fixed.

I am looking foward to this issue, hoping to be fixed soon.

**Comment by bmw** [comment]
From this description, it's not clear that this is a problem with Certbot as opposed to another issue with your setup. I recommend making a post at https://community.letsencrypt.org/ where there is a much larger community of people familiar with Certbot and server administration that can help you figure out the problem.
