### ISSUE TITLE
certbot-dns-route53 - no clear way to handle duplicate zone definitions

### ISSUE THREAD

**Issue by nneul** [certbot/certbot#9030]
## My operating system is (include version):

Ubuntu 20

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

pip

## I ran this command and it produced this output:

NA

## Certbot's behavior differed from what I expected because:

Code for certbot-dns-route53 has no way to handle the scenario of multiple zones covering same domain - such as if you have both an internal and an external zone for same domain housed on same AWS account. 

It appears that it is coded to handle finding longest(best) match, but only handling otherwise is to skip 'Private' zones. 

I'd like to see either:

A) option to use "all matching zones" of same 'name' when there are duplicates

B) option to be able to pass in a "domain: resource id" mapping -- this seems like it could be generalized across multiple dns plugins, with the 'id' to be interpreted by the particular plugin.

i.e. allow me to say 

`    --dns_zone_map "{ "example.com' : 'ABCDEF123123123123' }"
`

to allow explicitly telling the plugin "use this particular zone" instead. 

C) [likely simplest option to implement and maintain] option to be able to pass in one or more resource IDs to ignore from consideration when scanning for candidate zones to update. 

`
   --dns_zone_ignore "ABCDEF666777888999"  --dns_zone_ignore "EEEFFFGGG1231231231231" 
`

That would allow for me to trivially code in a list of zone ids that should never be used.

**Comment by nneul** [comment]
Looks like could add an 'append' mode argument in certbot/certbot/plugins/dns_common.py populating something like 'default_dns_ignore' - and then leave that up to each individual plugin to implement or not as it suits.

If a change of this form is likely to be accepted, I'll work on a PR.

**Comment by nneul** [comment]
Could also make it specific to route53 module like the 'credentials' option on the luadns module. Which would be preferred?

**Comment by alexzorin** [comment]
Could you clarify what is motivating this feature request? i.e. What is the use case where it makes sense to pick anything other than the most specific public zone?

Are you running an ACME CA inside a VPC which has a view of the private zone?

**Comment by nneul** [comment]
Correct. I have both an internal and a external zone defined/housed on route53 within this single AWS tenant, but both zones are 'accessible' externally.

IF there is a "most specific public zone" - current behavior is fine. The issue is if there are "two equal most-specific public zones". I could easily deal with it by 'not using certbot' or 'go through headache to change how our environment is set up' -- neither is preferred option.

**Comment by nneul** [comment]
(it's not defined as a private zone within r53 for accessibility reasons)

**Comment by nneul** [comment]
Ah, @alexzorin  I just reread your message - NO, not running a CA, rather using LetsEncrypt - rest of answer stands.

**Comment by nneul** [comment]
This is still "valid", but still an unplanned feature request.

**Comment by alexzorin** [comment]
I didn't realize that Route53 allows you to create duplicative public zones. I have written a PR implementing your option (b). I don't know if other DNS providers have the same characteristic, but if they do and users are hitting it, we can generalize the flag at a later time.
