### ISSUE TITLE
certbot libaugeas.so.0 error

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [certbot/certbot#9031]
## My operating system is (include version):
Fedora 34 64bits

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
snap

## I ran this command and it produced this output:
/var/lib/snapd/snap/certbot/1434/bin/python3 -s /snap/certbot/1434/bin/certbot -q renew

An unexpected error occurred:
OSError: cannot load library 'libaugeas.so.0': /snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/lib64/libaugeas.so.0)

**Comment by bmw** [comment]
That command is not going to work. The Certbot snap needs to be run through snap/snapd.

If you follow the instructions at https://certbot.eff.org/lets-encrypt/snap-other, running `/snap/bin/certbot` (which we recommend you symlink to `/usr/bin/certbot`) should accomplish this for you so you command should be `/snap/bin/certbot -q renew`.

**Comment by ROBERT-MCDOWELL** [comment]
this command is in the snap.certbot.renew.service provided with certbot

**Comment by bmw** [comment]
Really? On a 64 bit Fedora 34 VPS I just spun up:
```
# cat /etc/systemd/system/snap.certbot.renew.service
[Unit]
# Auto-generated, DO NOT EDIT
Description=Service for snap application certbot.renew
Requires=var-lib-snapd-snap-certbot-1434.mount
Wants=network.target
After=var-lib-snapd-snap-certbot-1434.mount network.target snapd.apparmor.service
X-Snappy=yes

[Service]
EnvironmentFile=-/etc/environment
ExecStart=/usr/bin/snap run --timer="00:00~24:00/2" certbot.renew
SyslogIdentifier=certbot.renew
Restart=no
WorkingDirectory=/var/snap/certbot/1434
TimeoutStopSec=30
Type=oneshot
```
What is the content of that file for you and what are the instructions you followed to install the Certbot snap? Does reinstalling it with a command like `sudo snap remove certbot && sudo snap install --classic certbot` fix the problem?

**Comment by ROBERT-MCDOWELL** [comment]
remove and reinstall cerbot did the trick.

**Comment by bmw** [comment]
Great. If anyone is able to provide instructions on how to reproduce the initial problem here, please comment or create a new issue.
