### ISSUE TITLE
How to handle dependency on dnspython >= 2.0 for RHEL/CentOS

### ISSUE THREAD

**Issue by FelixSchwarz** [certbot/certbot#9033]
Since commit 295dc5a2 (#8990) the plugin uses dnspython's `is_address()` helper function which was added in dnspython 2.0 ([commit 037dfe7f](https://github.com/rthalley/dnspython/commit/037dfe7f71f21e37fade0e3a203e38b675a1aa43)).

Actually this change is just a quick fix to get the correct dependencies. Actually the problem for CentOS is that RHEL 8 ships python3-dns 1.15.0-10.el8 in base which means upgrading that dependency is close to impossible. To continue shipping the latest versions of certbot to RHEL/CentOS users I need to come up with a workaround.

Ideas:

- Add a copy of `is_address()` to certbot's rfc2139 plugin (as compat fallback only)
- If dnspython is too old and `is_address()`  is not available, just skip validation (same behavior as certbot 1.18)
- downstream patch for RHEL only (I'd like to avoid that if possible!)

cc @osirisinferi, @alexzorin as you were involved in the original pull request.

**Comment by alexzorin** [comment]
Thanks Felix. My bad for not noticing that function not present in our oldest dependencies.

>Add a copy of is_address() to certbot's rfc2139 plugin (as compat fallback only)

An unrelated PR [recently added this function to `certbot`](https://github.com/certbot/certbot/blob/bd5f4f2d8ac3ad9e5afecab28d4806c538b1dc4d/certbot/certbot/util.py#L567-L587), so I think we can go with this option.

**Comment by osirisinferi** [comment]
> function not present in our oldest dependencies

Hm, so the test suites don't filter uit dependency issues?

**Comment by alexzorin** [comment]
There are tests against the oldest versions of deps we intend to support, but the deps themselves [are a manually managed list](https://github.com/certbot/certbot/blob/bd5f4f2d8ac3ad9e5afecab28d4806c538b1dc4d/tools/pinning/oldest/pyproject.toml#L39-L93). `dnspython` is missing (probably an oversight) from that list, so [the resulting "oldest" constraints](https://github.com/certbot/certbot/blob/bd5f4f2d8ac3ad9e5afecab28d4806c538b1dc4d/tools/oldest_constraints.txt#L25) include `dnspython==2.1.0`.

Had oldest `dnspython` been pinned, the error would have been caught and the `dns-oldest` tests would have failed:

    ____________________________________ AuthenticatorTest.test_cleanup _____________________________________
    [gw0] linux -- Python 3.6.8 /certbot/.tox/dns-oldest/bin/python

    self = <dns_rfc2136_test.AuthenticatorTest testMethod=test_cleanup>

        def setUp(self):
    >       from certbot_dns_rfc2136._internal.dns_rfc2136 import Authenticator

    certbot-dns-rfc2136/tests/dns_rfc2136_test.py:29:
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

        """DNS Authenticator using RFC 2136 Dynamic Updates."""
        import logging
        from typing import Optional

        import dns.flags
    >   from dns.inet import is_address
    E   ImportError: cannot import name 'is_address'

    certbot-dns-rfc2136/certbot_dns_rfc2136/_internal/dns_rfc2136.py:6: ImportError

I am intending to add that pinning once #9035 is merged.

**Comment by osirisinferi** [comment]
Ah, I see. So it seems it was a number of coincidences. It also doesn't help the [dnspython documentation](https://dnspython.readthedocs.io/en/latest/utilities.html#dns.inet.is_address) does not specify in which version a specific function was added (like in the Python documentation). It isn't also [mentioned in the Whats New](https://dnspython.readthedocs.io/en/stable/whatsnew.html#id2) page. You'd have to go directly to [the source on Github](https://github.com/rthalley/dnspython/blame/e863a2cb6837b8c0339f1dba803230d1c093d798/dns/inet.py#L119) and by using the "Blame" feature to check in which commit/PR the function was added and with that which version...
