### ISSUE TITLE
Host new PGP keys on dl.eff.org

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#9038]
We're planning on replacing https://dl.eff.org/certbot.pub with three new keys. Any of these keys may be used to sign a Certbot release.

I've generated these keys and signed them with the current key, but now we need to host them somewhere. @FelixSchwarz, is it OK with you if we just replace https://dl.eff.org/certbot.pub with the new keys?

EDIT: We should also remember to update the documentation found at https://certbot.eff.org/docs/packaging.html when doing this and notify our Debian and Fedora packagers of this change.

**Comment by FelixSchwarz** [comment]
> @FelixSchwarz, is it OK with you if we just replace https://dl.eff.org/certbot.pub with the new keys?

In Fedora there is no automation to refresh the signing keys for packages like certbot so no constraints from that side. I'll make sure I get the new keys once they are public. Ideally you would provide a single file which contains all the keys.
