### ISSUE TITLE
In Windows, specify the full path to the certbot command in the renewal task to prevent hijacking and other unpredictable behavior

### ISSUE THREAD

**Issue by GriffinSoftware** [certbot/certbot#9041]
I don't know if this has been fully addressed already, but...

Unlike \*nix, Windows uses a global PATH searching algorithm to determine the appropriate command to run when a suitable one is not found in the current directory. Additionally, Windows assumes that an extensionless, specified command actually refers to an extensioned command ending in `.com`, `.bat`, or `.exe`. To see the problems here and what an unmitigated disaster not being specific can cause, please see [this thread in the Let's Encrypt Community](https://community.letsencrypt.org/t/windows-tries-to-regularly-open-certbot-file-and-fails/155248?u=griffin) .

Please pay particular heed to these two posts:

https://community.letsencrypt.org/t/windows-tries-to-regularly-open-certbot-file-and-fails/155248/14?u=griffin

https://community.letsencrypt.org/t/windows-tries-to-regularly-open-certbot-file-and-fails/155248/11?u=griffin

**Comment by alexzorin** [comment]
Even if we fixed [`renew-up.ps1`](https://github.com/certbot/certbot/blob/abe23c0e6014a647f58c85aef2edb1c639204fe4/windows-installer/assets/renew-up.ps1#L7) for the Scheduled Task to run Certbot by its absolute path, the user would still be unable to run Certbot interactively from `cmd` or from the included launcher program. 

It would be more ideal to apply some kind of fix to the way we add Certbot to the `%PATH%`, or documentation fix, so that the problem is addressed fully, but I don't know what that would look like yet.

**Comment by GriffinSoftware** [comment]
For the renewal at least, it might be possible to take a page from the playbook of old school DOS games by simply creating a custom environment variable that contains the path of the certbot folder or even the entire path of the certbot command (think `%certbot%`):

https://helpdeskgeek.com/how-to/create-custom-environment-variables-in-windows/

This would work universally for all of the launch methods of concern.

**Comment by GriffinSoftware** [comment]
If you want to modify the official PATH environment variable, the key is to *prepend* the specific path to the PATH EV. For flexibility (and to prevent further bloating the PATH EV), you can create a custom environment variable path as I mentioned in my previous post then prepend that "reference" to the official PATH EV. This enables customization of the certbot directory without needing to alter the process of setting the PATH EV.

https://superuser.com/questions/284342/what-are-path-and-other-environment-variables-and-how-can-i-set-or-use-them
