### ISSUE TITLE
dnsimple: option to use API sandbox

### ISSUE THREAD

**Issue by snoopdouglas** [certbot/certbot#9048]
dnsimple has a sandbox API that'd be perfect for usage with `--dry-run`. See: https://support.dnsimple.com/articles/sandbox/

So, could I request an option to either specify the dnsimple API endpoint or similar?

## My operating system is (include version):
Ubuntu 20.04

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
pip

## I ran this command and it produced this output:
n/a

## Certbot's behavior differed from what I expected because:
n/a

## Here is a Certbot log showing the issue (if available):
n/a

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
n/a

**Comment by alexzorin** [comment]
It looks like the underlying Lexicon library supports an `api_endpoint` option for this DNS provider, so this feature request should be possible.

Could you elaborate more on why you would find this useful? It seems to me that you could `--dry-run` using the live API endpoint. It seems like the most relevant use case for the sandbox is when you don't have a DNSimple account with a real domain name - something that is useful for developers (like the Certbot team), but not especially so for our users. Happy to hear your thoughts here.

**Comment by snoopdouglas** [comment]
Nice!

For me, this is purely be so that live API tokens are kept away from our dev environments entirely; there are a few DNS operations we need to make apart from the DNS01 challenge in the same environment, so it'd be good to keep them away from production entirely, when we're not actually in production.
