### ISSUE TITLE
Can't renew certificate from newly deployed Ubuntu DNS server. Error parsing credentials configuration

### ISSUE THREAD

**Issue by sbltv** [certbot/certbot#9049]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 20 LTS

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
apt install certbot python3-certbot-dns-rfc2136

## I ran this command and it produced this output:
certbot certonly  --dns-rfc2136 --preferred-challenges dns  --dns-rfc2136-credentials /etc/bind/letsencrypt_keys/letsencrypt_wildcard_key.conf  -d 'ngnx.com' -d '*.ngnx.com' --email monitoring@ngnx.com

Plugins selected: Authenticator dns-rfc2136, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for ngnx.com
dns-01 challenge for ngnx.com
Cleaning up challenges
Error parsing credentials configuration: Parsing failed with several errors.
First error at line 1.

## Certbot's behavior differed from what I expected because:
I was expecting to receive a new cert  or a message that cert is not due to renewal yet

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
2021-09-29 13:16:42,679:DEBUG:acme.client:Storing nonce: 0102qpvBtSZfb0N-lf6ZFTWR_WDLOuUyWIe4lvHAcukVssY
2021-09-29 13:16:42,679:INFO:certbot.auth_handler:Performing the following challenges:
2021-09-29 13:16:42,680:INFO:certbot.auth_handler:dns-01 challenge for ngnx.com
2021-09-29 13:16:42,680:INFO:certbot.auth_handler:dns-01 challenge for ngnx.com
2021-09-29 13:16:42,681:DEBUG:certbot.plugins.dns_common:Error parsing credentials configuration: Parsing failed with several errors.
First error at line 1.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 251, in __init__
    self.confobj = configobj.ConfigObj(filename)
  File "/usr/lib/python3/dist-packages/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/usr/lib/python3/dist-packages/configobj.py", line 1318, in _load
    raise error
configobj.ConfigObjError: Parsing failed with several errors.
First error at line 1.
2021-09-29 13:16:42,684:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 251, in __init__
    self.confobj = configobj.ConfigObj(filename)
  File "/usr/lib/python3/dist-packages/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/usr/lib/python3/dist-packages/configobj.py", line 1318, in _load
    raise error
configobj.ConfigObjError: Parsing failed with several errors.
First error at line 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 48, in perform
    self._setup_credentials()
  File "/usr/lib/python3/dist-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 64, in _setup_credentials
    self.credentials = self._configure_credentials(
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 171, in _configure_credentials
    credentials_configuration = CredentialsConfiguration(self.conf(key), self.dest)
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 254, in __init__
    raise errors.PluginError("Error parsing credentials configuration: {0}".format(e))
certbot.errors.PluginError: Error parsing credentials configuration: Parsing failed with several errors.
First error at line 1.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
N/A  this is a DNS server

**Comment by sbltv** [comment]
Related part of **dns_common.py**

class CredentialsConfiguration(object):
    """Represents a user-supplied filed which stores API credentials."""

    def __init__(self, filename, mapper=lambda x: x):
        """
        :param str filename: A path to the configuration file.
        :param callable mapper: A transformation to apply to configuration key names
        :raises errors.PluginError: If the file does not exist or is not a valid format.
        """
        validate_file_permissions(filename)

        try:
            self.confobj = configobj.ConfigObj(filename)
        except configobj.ConfigObjError as e:
            logger.debug("Error parsing credentials configuration: %s", e, exc_info=True)
            raise errors.PluginError("Error parsing credentials configuration: {0}".format(e))

**Comment by alexzorin** [comment]
Hello,

> /etc/bind/letsencrypt_keys/letsencrypt_wildcard_key.conf

What is the contents of this file?

There is an example of what the file is meant to look like here: https://certbot-dns-rfc2136.readthedocs.io/en/latest/

**Comment by sbltv** [comment]
Thank you for looking into this. Here is requested config and I did the test also for dynamic update.

**/etc/bind/letsencrypt_keys/letsencrypt_wildcard_key.conf**
key "letsencrypt_wildcard" {
        algorithm hmac-sha512;
        secret "Kf2KwezImQdlOwC524FyPVOUGZbbjs1mqICTDkBkWnhdPZjkhBjhgbILHlkh5hCVJSYUAAWrlUFRD2g1LWkw==";
};

**nsupdate -k /etc/bind/letsencrypt_keys/letsencrypt_wildcard_key.conf -v**
server 10.10.10.10
debug yes
zone ngnx.com
update add _acme-challenge.ngnx.com. 60 TXT "test"
show
Outgoing update query:
;; ->>HEADER<<- opcode: UPDATE, status: NOERROR, id:      0
;; flags:; ZONE: 0, PREREQ: 0, UPDATE: 0, ADDITIONAL: 0
;; ZONE SECTION:
;ngnx.com.              IN      SOA

;; UPDATE SECTION:
_acme-challenge.ngnx.com. 60 IN TXT     "test"
;; TSIG PSEUDOSECTION:
letsencrypt_wildcard.   0       ANY     TSIG    hmac-sha512. 1633007788 300 64 Y4giK7vB2Ds7rXOCQ== 6400 NOERROR 0


Reply from update query:
;; ->>HEADER<<- opcode: UPDATE, status: NOERROR, id:   6400
;; flags: qr; ZONE: 1, PREREQ: 0, UPDATE: 0, ADDITIONAL: 1
;; ZONE SECTION:
;ngnx.com.              IN      SOA

;; TSIG PSEUDOSECTION:
letsencrypt_wildcard.   0       ANY     TSIG    hmac-sha512. 1633007788 300 64 ccmNxC4BETAUPUR4Q== 6400 NOERROR 0

**dig @10.10.10.10 -k /etc/bind/letsencrypt_keys/letsencrypt_wildcard_key.conf _acme-challenge.ngnx.com. Any**
; <<>> DiG 9.16.1-Ubuntu <<>> @10.10.10.10 -k /etc/bind/letsencrypt_keys/letsencrypt_wildcard_key.conf _acme-challenge.ngnx.com. Any
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46960
;; flags: qr aa rd; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 2
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: a8e97d3cc803617a010000006155ba9b6edd674f1af923a0 (good)
;; QUESTION SECTION:
;_acme-challenge.ngnx.com. IN   ANY

;; ANSWER SECTION:
_acme-challenge.ngnx.com. 60 IN TXT     "test2"
_acme-challenge.ngnx.com. 60 IN TXT     "test"

;; TSIG PSEUDOSECTION:
letsencrypt_wildcard.   0       ANY     TSIG    hmac-sha512. 1633008283 300 64 l6F5iodBT+ZzLQ75MWejbuQ0L1r6Y7Ywak2KD7uLNFGv+Nx5BqFRzr8w MG6xXao1lrCVkuE1Lry7wLPn+fszjQ== 46960 NOERROR 0

;; Query time: 0 msec
;; SERVER: 10.10.10.10#53(10.10.10.10)
;; WHEN: Thu Sep 30 09:24:43 EDT 2021
;; MSG SIZE  rcvd: 249


I don't see any issue with key :-(

**Comment by alexzorin** [comment]
Please read over the documentation for the RFC2136 plugin [here](https://certbot-dns-rfc2136.readthedocs.io/en/latest/), specifically the "Credentials" section. 

You are giving passing Certbot a BIND key file for ` --dns-rfc2136-credentials`, which is different to what Certbot is expecting.

If you need further help with getting that working, please open a thread at https://community.letsencrypt.org. Thank you.

**Comment by sbltv** [comment]
OMG !

Alex, you are rigt. I was using wrong file for credentials. Thank you.

root@ns1:~# certbot certonly  --dry-run --dns-rfc2136 --preferred-challenges dns  --dns-rfc2136-credentials /etc/bind/letsencrypt_keys/certbot.ini  -d '*.ngnx.com' -d 'ngnx.com'
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-rfc2136, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for ngnx.com
dns-01 challenge for ngnx.com
Waiting 60 seconds for DNS changes to propagate
Waiting for verification...
Cleaning up challenges

**IMPORTANT NOTES:
 - The dry run was successful.**
