### ISSUE TITLE
RFC8738: support for IP address SANs

### ISSUE THREAD

**Issue by KazamaSion** [certbot/certbot#9060]
## My operating system is (include version):
Alpine Linux v3.12 (Environment: Official certbot docker)

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
docker

## I ran this command and it produced this output:
```
certbot certonly --agree-tos --manual \
  --preferred-challenges http \
  --server https://example.com/directory \
  --eab-kid abcdefg \
  --eab-hmac-key abcdefghijklmn\
  -d 1.1.1.1 -v
```

> Requested name 1.1.1.1 is an IP address. The Let's Encrypt certificate authority will not issue certificates for a bare IP address.

## Certbot's behavior differed from what I expected because:
Should not detect if requesting IP certs while using custom ACME server.

**Comment by alexzorin** [comment]
Support was recently added to the `acme` library, but Certbot itself still does not support IP SANs.

The error message could perhaps more accurately say "Certbot does not support ...".

**Comment by alexzorin** [comment]
I'm going to rename this issue, as resolving it requires implementing RFC8738 fully, and not just removing the check for the IP address. We still do not have any plans to work on this.

**Comment by jshufro** [comment]
Looks like this is being added https://github.com/certbot/certbot/pull/10468
