### ISSUE TITLE
Feature request: operation in testing environment

### ISSUE THREAD

**Issue by rafalkrupinski** [certbot/certbot#9098]
As a DevOps engineer I'd like to test my provisioning automation that includes generating certificates with certbot, in a virtual server environment, that's not reachable from the Internet. I don't care much for the verifiability of the certificates, as long as my servers (nginx/apache/etc) get properly configured.

I think it would be similar to --dry-run flag (obtaining invalid test certificate) with the following differences:
- run successfully when it's not possible to authenticate, but should attempt to listen to the auth request and fail on error i.e. when cannot bind to a port,
- keep all the changes as normal operation does.

Thank you :)

**Comment by adferrand** [comment]
This is essentially the purpose of the subproject https://github.com/certbot/certbot/tree/master/certbot-ci.

We use it to run integration tests, that consists in spinning up a real ACME Server (Pebble) and run actual commands of certbot against it to verify the main user flows and tricky regressions encountered in the past.

The implementation is done through pytest and its hooks, and so offers a strict isolation of the operations on real flows while testing Certbot as a black box. Pytest reports and logs capabilities are leveraged through this implementation.

Tests cover the core part of certbot and its integrated plugins (`standalone`, `webroot`, `manual`) but also certbot-nginx: in this case the locally installed Nginx instance is instrumentated to run inside the isolation environment set up by certbot-ci, and here also real certificate issuance and installation in Nginx is tested.

I recommend you to look at this subproject, and open specific issues or PR contribution to improve it.

**Comment by rafalkrupinski** [comment]
So you're saying I should run pebble server for my tests. Cheers
