### ISSUE TITLE
certbot --apache fails if vhost configuration filename contains a space

### ISSUE THREAD

**Issue by Deracination** [certbot/certbot#9104]
## My operating system is (include version):
Centos 8.3.2011

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
snap

## I ran this command and it produced this output:
certbot certonly --apache

"Unable to find a virtual host listening on port 80 which is currently needed for Certbot to prove to the CA that you control your domain. Please add a virtual host for port 80."

## Certbot's behavior differed from what I expected because:
Virtual host is running on port 80 as certbot requires.

I renamed the configuration file "/etc/httpd/conf.d/25-host\ non-ssl.conf" to "/etc/httpd/conf.d/25-host-non-ssl.conf" (replacing space with '-') and certbot successfully obtained a certificate.

**Comment by bmw** [comment]
Thanks for the bug report. I was able to reproduce this on Ubuntu 20.04. This is not just a problem with our Apache plugin on CentOS.
