### ISSUE TITLE
OVH-DNS Documentation: Permissions for one domain?

### ISSUE THREAD

**Issue by rvalle** [certbot/certbot#9109]
The OVH-DNS documentation instruct to generate an API credentials with the following access rules:

```
  GET /domain/zone/*
  PUT /domain/zone/*
  POST /domain/zone/*
  DELETE /domain/zone/*
```
This will grant access to all zones in the OVH account.

if one wanted to generate certificates for one domain only, say ```example.com``` what are the required access rules?

the following does not work:

```
  GET /domain/zone/example.com
  PUT /domain/zone/example.com
  POST /domain/zone/example.com
  DELETE /domain/zone/example.com
```

I have tried other combinations, such as ending by * and still does not work, the error is not very splicit:

```
Error determining zone identifier for example.com: 403 Client Error: Forbidden for url: https://eu.api.ovh.com/1.0/domain/zone/.
```

any idea which credentials need to be granted for managing certificates for one domain only?

**Comment by adferrand** [comment]
Before acting on the actual zone you want to edit, the system will first try to verify that the credentials you are using can see this domain. This involves a request to with `GET /domain/zone/` essentially.

Also all calls further will be done to subpaths of `/domain/zone/example.net/`, so you will need to append `/*` on the scope to match these subpaths.

At the end I think a working restrictive scope should be:
```
GET /domain/zone/
GET /domain/zone/example.com/*
PUT /domain/zone/example.com/*
POST /domain/zone/example.com/*
DELETE /domain/zone/example.com/*
```

**Comment by rvalle** [comment]
@adferrand , I think I tried that combination.... but I tried so many that perhaps it did not happen exactly. I will try and let you know.
I also think it would be worth adding to the documentation, has value.

**Comment by alexzorin** [comment]
I agree. I think we'd accept a PR to the documentation which includes an example of restricting scope to a single zone.

**Comment by alexzorin** [comment]
Closing, as this was completed in #9109.

**Comment by bfontaine** [comment]
Correct link: #9419
