### ISSUE TITLE
Apache 2.2 support in certbot-apache?

### ISSUE THREAD

**Issue by atombrella** [certbot/certbot#9116]
From https://httpd.apache.org/ 

> The final release 2.2.34 was published in July 2017, and no further evaluation of bug reports or security risks will be considered or   
> published for 2.2.x releases.

I think for RHEL 6 based systems that used 2.2 reached end of maintenance in November 2020. certbot-apache is Python 3.6 only. 

Under `ApacheConfigurator.prepare`, there's a comment about it: 

```
        elif self.version < (2, 4):
            logger.warning('Support for Apache 2.2 is deprecated and will be removed in a '
                           'future release.')
```

**Comment by alexzorin** [comment]
It appears that the plan is to do this in the upcoming 2.0 major release of Certbot: https://github.com/certbot/certbot/issues/8461

Going to close this as duplicate but further discussion is welcome in that issue.
