### ISSUE TITLE
Attempting to renew cert: unexpected error: bad handshake

### ISSUE THREAD

**Issue by YuGiOhJCJ** [certbot/certbot#9118]
## My operating system is (include version):
Slackware 14.2 (64-bit)

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
From source code (certbot-1.4.0, certbot-1.4.0.tar.gz)

## I ran this command and it produced this output:
I ran this command:
```certbot renew --config-dir=config --logs-dir=logs --work-dir=work```

It produced this output:
```Attempting to renew cert ([...]) from /home/[...]/[...].cf.conf produced an unexpected error: bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],). Skipping.```

## Certbot's behavior differed from what I expected because:
Renew failure.

I don't understand it worked for years and now it does not work anymore, I am unable to renew my certificate, do you know why please?

Thank you.
Best regards.

**Comment by alexzorin** [comment]
This sounds like an issue with the CA certificate store on your system. 

I left a suggestion to fix this on the community forum thread you posted earlier, but I'm going to close this issue as the forum is a more appropriate venue.
