### ISSUE TITLE
Optionally sign SOA query in dns_rfc2136

### ISSUE THREAD

**Issue by warewolf** [certbot/certbot#9123]
I created a pull request: https://github.com/certbot/certbot/pull/9106

I run my own nameserver and have split views for internal and external versions of the same zone.  Since I'm running certbot on the server itself, it finds the *internal* (non authoritative, does recursion) zone I'm trying to do dns_rfc2136 challenges for, and the dns_rfc2136 checks fail.

So I RTFM'd python's DNS library and figured out how to have it sign the SOA query, to make the checks pass.  Now I can generate letsencrypt certs with dns_rfc2136 challenges.

Thanks,
Richard

**Comment by warewolf** [comment]
Is there anything I can do to help this along, besides ... writing code?

**Comment by osirisinferi** [comment]
@warewolf Would your issue be fixed by #9408 too by any chance?

**Comment by warewolf** [comment]
*groan*

**Comment by alexzorin** [comment]
Fixed by #9408.
