### ISSUE TITLE
Missing certbot --help output

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#9129]
It looks like something broke in Certbot's `--help` output since the last release. See https://github.com/certbot/certbot/pull/9128/files#diff-0aafb69468d2e7d422472b877bf504077a04491f69118527f0ae815a09711329. Using `git bisect`, it looks like the commit that introduced the problem was 86406ab63aebf463ca4aa0381a55ddeb91231cd2 from https://github.com/certbot/certbot/pull/9087.

**Comment by alexzorin** [comment]
To narrow it down a bit further, it looks related to this change: https://github.com/certbot/certbot/commit/86406ab63aebf463ca4aa0381a55ddeb91231cd2#diff-b72a441a43c744bfd9409184c39c7811ceecd884484d7fc96efb6452e848c0dcL370-R379

What that failed to account for is that `None` is a valid topic.

**Comment by adferrand** [comment]
Yes I see that. Do you want me to do a PR ?

**Comment by alexzorin** [comment]
Sure, that would be good. Thank you.

So far I haven't been able to find any side effects to the problem other than the help text being suppressed. At least, with the default set of plugins.

**Comment by adferrand** [comment]
Yes the impact is that flags associated with the `None` topic are not displayed. We could factor a bit more to avoid this strange map of keys of type str or `None`, but my PR fixes the problem for now.
