### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by MannyLama** [certbot/certbot#9138]
## My operating system is (include version):
`NAME="Oracle Linux Server"`
`VERSION="8.4"`
`ID_LIKE="fedora"`
`PRETTY_NAME="Oracle Linux Server 8.4"`

`uname -a` returns
`Linux server00 5.4.17-2102.206.1.el8uek.aarch64 #2 SMP Wed Oct 6 17:35:01 PDT 2021 aarch64 aarch64 aarch64 GNU/Linu`

## I installed Certbot with snap:
`yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm`
`yum install snapd`
`systemctl enable --now snapd.socket`
`systemctl start snapd`
`ln -s /var/lib/snapd/snap /snap`
`snap install core`
`snap refresh core`
`snap install --classic certbot`
`ln -s /snap/bin/certbot /usr/bin/certbot`
`certbot`
`Segmentation fault `

## I ran this command and it produced this output:
`certbot`
`Segmentation fault `

## Certbot's behavior differed from what I expected because:
It should not throw a segmentation fault.

## Here is a Certbot log showing the issue (if available):
No log available because the application would not start.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
Not relevant

##
Core dump is available, just don't wan't it to put it here in the open.
Got this two times after a fresh new VM. If any more information is required, I would be pleased to provide that.

**Comment by alexzorin** [comment]
I wasn't able to reproduce this on Oracle Linux 8.5 using an x86_64 AMI off EC2.

Two suggestions:

1. If you upgrade your VM and its packages to the latest point release, is it resolved?
2. Is the VM image something that can be accessed publicly? On some cloud provider?

**Comment by MannyLama** [comment]
@alexzorin I forgot to mention the architecture I am running. It is aarch64, I edited the original post. It's a VM based upon A1.Flex. I have some other VM's also running Oracle Linux Server 8.4 on the X64 (E2.1.Micro) architecture and Certbot works just fine on them.
It is a VM machine in the Oracle cloud that I'am running.

**Comment by alexzorin** [comment]
Thanks. I can reproduce it.

It looks like these specific Oracle A1 aarch64 machines don't like the `python3.8` ELF that gets installed from the `core20` base image. Canonical's `snapcraft` classic snap exhibits the same problem; it's not isolated to Certbot.

Following my own suggestion, upgrading all of the packages on the system did not help.

Supposedly the call to `execve` to start Python is returning `EINVAL` which indicates:

>An ELF executable had more than one PT_INTERP segment (i.e., tried to name more than one interpreter). 

but I'm not sure that's right:

        [root@instance-20211213-1950 ~]# objdump -s -j .interp /var/lib/snapd/snap/snapcraft/6956/bin/python

        /var/lib/snapd/snap/snapcraft/6956/bin/python:     file format elf64-littleaarch64

        Contents of section .interp:
        41d5a8 2f736e61 702f636f 72653230 2f637572  /snap/core20/cur
        41d5b8 72656e74 2f6c6962 2f6c642d 6c696e75  rent/lib/ld-linu
        41d5c8 782d6161 72636836 342e736f 2e3100    x-aarch64.so.1.

I guess we should file an issue upstream with snapcraft about it.

In the meantime, I think Certbot from EPEL should work on these OL8 machines (`yum install certbot` assuming EPEL has been enabled).

**Comment by cristianarnaud** [comment]
Hi @MannyLama Any luck with this? I'm facing the same problem. Exact same configuration.

**Comment by MannyLama** [comment]
> Hi @MannyLama Any luck with this? I'm facing the same problem. Exact same configuration.

Yes and no. I could work around by skipping the install with snap. I installed Certbot through `yum install certbot`.

**Comment by MrVeink** [comment]
I have otherwise the same setup with Oracle Linux 7.9. Snap doesn't work, but didn't know there was an EPEL package for certbot

**Comment by hiriumi** [comment]
Hi, I'm having the same issue on Oracle Linux 8 on Arm64 on OCI.

**Comment by duongapollo** [comment]
me had the same issue on OL8, arm64 on OCI

**Comment by duongapollo** [comment]
[Solved]
install using yum

yum install certbot
yum install python3-certbot-nginx
