### ISSUE TITLE
Certbot renewal no env variables for hooks

### ISSUE THREAD

**Issue by t0mtaylor** [certbot/certbot#9141]
Certbot renewal no env variables for hooks

when setting the post and deploy hook, the environment variables are not set by cerbot

```
$RENEWED_DOMAINS
$RENEWED_LINEAGE
```

I have tried `printenv` in the hook script and the variables dont exist

**Comment by alexzorin** [comment]
1. `--post-hook` doesn't set these environment variables. This is intentional, because a post-hook may be covering multiple certificates:

    >If multiple renewed certificates have identical post-hooks, only one will be run.

2. `--deploy-hook` always sets these environment variables. If you have found a situation where this isn't a case, it would be a bug.

**Comment by harridu** [comment]
RENEWED_DOMAINS could provide a space-separated list (as indicated by the name).

About case 1:
Not sure about the pre-hooks, but apparently all post-hooks are run, even if only one cert got renewed. This can be pretty expensive. How could this be avoided in the post-hook script without information provided certbot? It would be easy to ignore these variables in the script.

**Comment by alexzorin** [comment]
> apparently all post-hooks are run, even if only one cert got renewed. This can be pretty expensive. How could this be avoided in the post-hook script without information provided by certbot

Yes, if you put pre/post hook scripts into the `/etc/letsencrypt/renewal-hooks/{pre,post}/` directories, they will all be run indiscriminately. They are global.

If you want to a pre/post hook which is specific only to one certificate, issuing the certificate with the `--pre-hook` and `--post-hook` CLI flags will achieve that. Certbot will remember, at the next renewal, to run those hooks, for that certificate specifically.  The setting will be remembered in the `/etc/letsencrypt/renewal/*.conf` file.

**Comment by harridu** [comment]
You mean I have to put the pre- and post-hook scripts into another directory to make sure that they are run only if "their" certificate got updated? Can this still be a common directory for all certificates?

**Comment by alexzorin** [comment]
I think it's helpful to think of the `pre/` and `post/` directories as global. For example, if all your certificate renewals require stopping and starting nginx, then it's a way to do that in a single place.

Otherwise, anything certificate-specific should go outside of those directories and be set per-certificate, yes.

**Comment by harridu** [comment]
I wonder where this could be found in the man page?

**Comment by alexzorin** [comment]
A lot of this information is buried in https://eff-certbot.readthedocs.io/en/stable/using.html#renewing-certificates, but it could be improved, yes.

**Comment by lordspace** [comment]
I am testing the --deploy-hook command line argument with **--dry-run** and **--force-renewal** and my php script is NOT receiving the environment variables that it's supposed to. I have tried to access them via getenv() function and also using $_ENV and $_SERVER arrays too.

Do you have an idea why

**Comment by alexzorin** [comment]
`--dry-run` does not invoke `--deploy-hook`.

**Comment by Pakbon** [comment]
I'm having the same issue as @lordspace , however I'm not using **dry-run**.
In my case, the manual-auth-hook and manual-cleanup-hook are both Python scripts and neither can get the environment variables using os.environ['CERTBOT_DOMAIN'], the scripts fail instantly the moment I try to read out the env vars.

What I think(90% certain) is actually happening, is that not environment variables are set, but **Bash** variables are set, which are not readable to other interpreters, like Python.

**Comment by lordspace** [comment]
Cool. Will test this in the next few weeks
