### ISSUE TITLE
Question: Certbot 1.22 and Python 3.10

### ISSUE THREAD

**Issue by lorand-horvath** [certbot/certbot#9143]
I'm not sure where else to ask this, sorry for posting here.
The release notes for Certbot 1.22.0 https://github.com/certbot/certbot/releases/tag/v1.22.0 mention support for Python 3.10
`Support for Python 3.10 was added to Certbot and all of its components.`

Is Python 3.10 being actively used everywhere in Certbot instead of the previous version 3.9, or is it just partial support in certain components? What does support mean in this case? In case it helps, I'm using the Windows version of Certbot (32-bit beta).
Thanks!

**Comment by bmw** [comment]
In the distribution methods we control where we bundle a copy of Python such as our Windows installer, snaps, and Docker images, an older version of Python is being used.

By adding support, we mean that Certbot completely works when run with Python 3.10, we regularly test against it, and people should expect it to work if they do something like install it themselves using `pip` on Python 3.10.

Let me know if that doesn't answer your question.

**Comment by lorand-horvath** [comment]
@bmw Thanks for the reply. Am I to understand that in the latest Windows release of Certbot 1.22 (32-bit beta) only Python 3.9 is used? I've just checked the installation folder `C:\Program Files (x86)\Certbot` and I see Python 3.9 in the Python folder. Can I assume that Python 3.10 is in fact NOT used anywhere in this Windows package?

**Comment by bmw** [comment]
That's correct.
