### ISSUE TITLE
debug-challenges doesn't actually stop

### ISSUE THREAD

**Issue by jaymzh** [certbot/certbot#9151]
When using `--debug-challenges`, it claims it's going to wait, but it never does:

```
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Challenges loaded. Press continue to submit to CA. Pass "-v" for more info about
challenges.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cleaning up challenges
```

This was from running `certbot renew --debug-challenges --debug`

## My operating system is (include version):

Debian 11.1

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

Apt.

## I ran this command and it produced this output:

See above.

## Certbot's behavior differed from what I expected because:

It should stop and let me debug, but it does not.

**Comment by alexzorin** [comment]
This is an unfortunate limitation of `renew`. It forces `--non-interactive`, which disables interactive prompts, such as the `--debug-challenges` one.

We should probably include this limitation in the help text for the flag.

I'm not sure how simple fixing this to work would be. One workaround is to use `certbot certonly --dry-run` when debugging things.

**Comment by jaymzh** [comment]
I tried that (`certonly ... --debug-challenges`), and it gives the same behavior.

Basically, I have 2 subdomains that use the same webroot that are failing, thus my cert is not renewing. The system reports a 404 when it tries to grab the challenge. If I touch that same file, it seems to work. But I need to debug before it cleans them. I'm using the `webroot` plugin. I can't seem to find a way to debug this, given this bug, without digging into the code and commenting out all the cleanup stuff, which I was trying to avoid.

**Comment by osirisinferi** [comment]
> This is an unfortunate limitation of `renew`. It forces `--non-interactive`, which disables interactive prompts, such as the `--debug-challenges` one.

Why doesn't renew rely on `sys.stdout.isatty()` to make it interactive or non-interactive? Personally, I run `renew` manually instead of through cron.. So I wouldn't care if it was interactive or not.

**Comment by jmlord** [comment]
Still an issue with certbot 2.8.0: `--debug-challenges` does not stop with option `renew`.

Suggested workaround `certbot certonly --dry-run --debug-challenges` works for me.
