### ISSUE TITLE
Nginx plugin doesn't check in a common subdirectory for nginx.conf file

### ISSUE THREAD

**Issue by bgashler1** [certbot/certbot#9162]
## My operating system is (include version):
Raspberry Pi OS 9 (Stretch)
Certbot 1.22.0

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
Snap

## I ran this command and it produced this output:
`sudo certbot --nginx --nginx-ctl /usr/local/nginx/sbin/nginx --nginx-server-root /usr/local/nginx`

> Error while running /usr/local/nginx/sbin/nginx -c /usr/local/nginx/nginx.conf -t.
> 
> nginx: [emerg] open() "/usr/local/nginx/nginx.conf" failed (2: No such file or directory)
> nginx: configuration file /usr/local/nginx/nginx.conf test failed
> 
> The nginx plugin is not working; there may be problems with your existing configuration.
> The error was: MisconfigurationError('Error while running /usr/local/nginx/sbin/nginx -c /usr/local/nginx/nginx.conf -t.\n\nnginx: [emerg] open() "/usr/local/nginx/nginx.conf" failed (2: No such file or directory)\nnginx: configuration file /usr/local/nginx/nginx.conf test failed\n')

## Certbot's behavior differed from what I expected because:
The Certbot tests to see if the `nginx.conf` file is in the `server_root` only, even though it often lives one level deeper in a subdirectory called `conf` (when nginx is built from source). Certbot isn't checking this [common location](https://docs.nginx.com/nginx/admin-guide/basic-functionality/managing-configuration-files/#:~:text=the%20location%20depends%20on%20the%20package%20system%20used%20to%20install%20NGINX%20and%20the%20operating%20system.%20It%20is%20typically%20one%20of%20/usr/local/nginx/conf) and instead only looks in the `server_root` itself.

The problem is potentially here
https://github.com/certbot/certbot/blob/ed7964b424345b5d8ad98335be8f98d5c21059a6/certbot-nginx/certbot_nginx/_internal/configurator.py#L87

My workaround (which is not intuitive or clean) was to create hard links to the `server_root`
> i.e. `ln /usr/local/nginx/conf/nginx.conf /usr/local/nginx/nginx.conf` for the `nginx.conf` file and "include"d files within it, such as `mime.types` as even those were being checked for erroneously in the `server_root` exclusively instead of within the common subdirectory `conf`.

People like me who build nginx from source often struggle how to make `certbot --nginx`. It's not obvious from a UX-perspective that you have to specify with flags the directories of your binaries and configs.

## Here is a Certbot log showing the issue (if available):
```
2022-01-06 19:46:15,782:DEBUG:certbot._internal.plugins.disco:Misconfigured PluginEntryPoint#nginx: Error while running /usr/local/nginx/sbin/nginx -c /usr/local/nginx/nginx.conf -t.

nginx: [emerg] open() "/usr/local/nginx/nginx.conf" failed (2: No such file or directory)
nginx: configuration file /usr/local/nginx/nginx.conf test failed
Traceback (most recent call last):
  File "/snap/certbot/1669/lib/python3.8/site-packages/certbot_nginx/_internal/configurator.py", line 975, in config_test
    util.run_script([self.conf('ctl'), "-c", self.nginx_conf, "-t"])
  File "/snap/certbot/1669/lib/python3.8/site-packages/certbot/util.py", line 121, in run_script
    raise errors.SubprocessError(msg)
certbot.errors.SubprocessError: Error while running /usr/local/nginx/sbin/nginx -c /usr/local/nginx/nginx.conf -t.

nginx: [emerg] open() "/usr/local/nginx/nginx.conf" failed (2: No such file or directory)
nginx: configuration file /usr/local/nginx/nginx.conf test failed


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/certbot/1669/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 160, in prepare
    self._initialized.prepare()
  File "/snap/certbot/1669/lib/python3.8/site-packages/certbot_nginx/_internal/configurator.py", line 190, in prepare
    self.config_test()
  File "/snap/certbot/1669/lib/python3.8/site-packages/certbot_nginx/_internal/configurator.py", line 977, in config_test
    raise errors.MisconfigurationError(str(err))
certbot.errors.MisconfigurationError: Error while running /usr/local/nginx/sbin/nginx -c /usr/local/nginx/nginx.conf -t.

nginx: [emerg] open() "/usr/local/nginx/nginx.conf" failed (2: No such file or directory)
nginx: configuration file /usr/local/nginx/nginx.conf test failed

2022-01-06 19:46:15,789:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * nginx
Description: Nginx Web Server plugin
Interfaces: Installer, Authenticator, Plugin
Entry point: nginx = certbot_nginx._internal.configurator:NginxConfigurator
Initialized: <certbot_nginx._internal.configurator.NginxConfigurator object at 0x734d9e50>
Prep: Error while running /usr/local/nginx/sbin/nginx -c /usr/local/nginx/nginx.conf -t.

nginx: [emerg] open() "/usr/local/nginx/nginx.conf" failed (2: No such file or directory)
nginx: configuration file /usr/local/nginx/nginx.conf test failed

2022-01-06 19:46:15,792:DEBUG:certbot._internal.plugins.selection:Selected authenticator None and installer None
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
(Not applicable; everything works when I do the awkward workaround I mention above)

**Comment by alexzorin** [comment]
It warms my heart to read such thoughtfully considered and written feedback. Thank you ❤️ .

Since the nginx documentation specifically calls out `/usr/local/nginx/conf/` as a possible location for `nginx.conf`, I am feeling convinced that we can accommodate this variation in the plugin.

Some of the plugin code appears already to be set up to support this, though it looks like the change will have to be made in a couple of places:

https://github.com/certbot/certbot/blob/30b066f08260b73fc26256b5484a180468b9d0a6/certbot-nginx/certbot_nginx/_internal/parser.py#L222-L231

I think we would review a PR to also check in `${server_root}/conf/nginx.conf`. I am not eager to put any magic logic around detecting`/usr/local/nginx` in the `--nginx-server-root`, since a source-based installation could plausibly go to any other install prefix.

>People like me who build nginx from source often struggle how to make certbot --nginx. It's not obvious from a UX-perspective that you have to specify with flags the directories of your binaries and configs.

I think we should additionally clarify exactly this topic in the documentation at https://eff-certbot.readthedocs.io/en/stable/using.html#nginx.
