### ISSUE TITLE
nginx plugin UX should infer paths when nginx is built from source

### ISSUE THREAD

**Issue by bgashler1** [certbot/certbot#9163]
## My operating system is (include version):
Raspberry Pi OS 9 (Stretch)

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
Snap

## I ran this command and it produced this output:
`sudo certbot --nginx --nginx-ctl /usr/local/nginx/sbin/nginx --nginx-server-root /usr/local/nginx`
Everything worked normally after I did the awkward workaround for bug #9162

## Certbot's behavior differed from what I expected because:
It's not clear to users they need to specify paths to Nginx's configuration file or binary through flags or how to do so (e.g. run `which nginx` to find the path to their binary and enter it with a flag). Some people (including me, until recently) simply assume that `certbot --nginx` will not work for Nginx when installed from source and opt for manual setup when it actually can.

**⭐️ Opportunities to improve the UX: ⭐️ **
- Instead of failing when Certbot doesn't find the `server_root` or config files where it expects (i.e. only looking where they would be if Nginx was installed via a package manager such as `apt`), it could check the [3 most common places](https://docs.nginx.com/nginx/admin-guide/basic-functionality/managing-configuration-files/#:~:text=(For%20NGINX%20Open%C2%A0Source%20%2C%20the%20location%20depends%20on%20the%20package%20system%20used%20to%20install%20NGINX%20and%20the%20operating%20system.%20It%20is%20typically%20one%20of%20/usr/local/nginx/conf%2C%20/etc/nginx%2C%20or%20/usr/local/etc/nginx.)) instead of failing outright with a generic error.
    - In the (hopefully) rare event Certbot finds multiple inferred paths, it could prompt the user which one they want (e.g. if it sees multiple `nginx` binaries or server roots in say `/etc/` and `/usr/local/`...)
- Could Certbot also attempt to infer where the binary for Nginx is by checking the PATH or relative to where we find the config (e.g. it's *very likely* in `/usr/local/nginx/sbin` or `/etc/local/nginx/sbin`, or `/usr/sbin`)? Sensible default behavior could save people from going [here](https://stackoverflow.com/questions/36109112/shell-cant-find-nginx).
- As a last resort fail-safe, could the command return helpful hints, such as
    - "We couldn't find your Nginx server root, which includes your config and other server files. Try re-running this command as `sudo certbot --nginx --nginx-server-root /path/goes/here`, changing the path to point to your `server_root`
    -  We couldn't find Nginx installed. Either make sure the `nginx` command is included in your PATH or try re-running this command as `sudo certbot --nginx --nginx-ctl /path/to/nginx`, changing the path to point to Nginx.
    - [A third message that combines parts of the two above...]

## Here is a Certbot log showing the issue (if available):
N/A

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
N/A applies to whole setup of nginx

**Comment by alexzorin** [comment]
In addition to my comment at #9162, I am partial to (at least initially) the idea of helpful hints.

If (after #9162 is fixed to search in the second location) the `nginx.conf` still cannot be found, my thinking is that it is safest for Certbot to respect the value of `--nginx-*` flags, but to present an explanation to the user about what might be going wrong.
