### ISSUE TITLE
hooks: investigate decoding errors in subprocess code

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#9171]
See https://community.letsencrypt.org/t/using-certbot-renew-with-pre-posthook-in-windows-10-shows-error/169591?u=_az

**Comment by alexzorin** [comment]
Hey @adferrand I'd appreciate your input on a couple of Windows-related matters:

1. Could we set `-ExecutionPolicy Bypass` on Certbot's invocation of PowerShell to work around policy set on the machine?
2. It would seem from that thread, that Python is trying to decode the output from PowerShell (the `UnauthorizedAccess` error) as CP1252. I wonder, why? The console host used by PS would ave to be on some other encoding to show the error in the first place? UTF-16 probably, per #7800? What do you think we should do? We need to be able display the output ourselves, without crashing Certbot. Do we set the `encoding=` on `subprocess.run` to UTF-16-LE? Do we take it out as `bytes` and then do error-tolerant decoding?

**Comment by SamLowryMOI** [comment]
It is important that the scripts work, especially with wildcard certificates, to automate the creation (and deletion) of TXT records.

**Comment by SamLowryMOI** [comment]
My cmd and also my PowerShell codepage is 850. And it's hard to change that. Please refer [https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window](https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window). Maybe this helps.

**Comment by SamLowryMOI** [comment]
I think I found a solution for the encoding problem.

certbot/certbot/certbot/compat/misc.py

> [...]
> try:
>     from pywintypes import error as pywinerror
>     **from ctypes import windll**
> [...]
> 
> [line 164]
>     proc = subprocess.run(line, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
>                           universal_newlines=True, check=False, env=env,
>                           **encoding='cp{}'.format(windll.kernel32.GetConsoleOutputCP())**)
> 
> [...]

No more 'charmap' codec can't decode byte' errors.

BTW: I installed certbot on windows via python and pip instead of using the installer. Then no errors occur. Is the linux variant then executed?

**Comment by SamLowryMOI** [comment]
In the new version 1.25.0 the hook scripts work on Windows. There are still character set errors, e.g. if you output German umlauts in the script, but the scripts run without errors. In order to output the umlauts (and characters contained in other character sets) without errors, further changes are probably necessary.

**Comment by SamLowryMOI** [comment]
Yes, the problem still exists, but I have a hint. 

```
C:\Certbot\_utils>CertTest.bat
ÄÖÜäöüß
Saving debug log to C:\Certbot\log\letsencrypt.log
Exception in thread Thread-1 (_readerthread):
Traceback (most recent call last):
  File "C:\Users\ItIsMe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\ItIsMe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ItIsMe\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1568, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
  File "C:\Users\ItIsMe\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 19: character maps to <undefined>
An unexpected error occurred:
AttributeError: 'NoneType' object has no attribute 'strip'
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile C:\Certbot\log\letsencrypt.log or re-run Certbot with -v for more details.
```

To be able to output German umlauts in the command line, you have to change the encoding of the batch file to codepage 850 (which is also the codepage in a German command line). And there seem to be problems with this. Certbot should recognize the encoding of the batch file when opening it and tell python accordingly.
