### ISSUE TITLE
Prepare for Windows 2016 removal from Azure Pipelines

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#9176]
See https://github.com/actions/virtual-environments/issues/4312.

We should remove it from CI, but we also need to do something about users on that version of Windows. Since Windows still isn't very popular for us, we haven't merged the auto-update mechanism, and Windows support is still in beta, I propose we just only claim support for the versions of Windows we can easily test on which is what we were doing before.

**Comment by bmw** [comment]
Alex flagged that this may be more complicated than I described here. See https://github.com/certbot/certbot/pull/9145.

**Comment by adferrand** [comment]
Closed by #9202.
