### ISSUE TITLE
`Segmentation fault` when creating certs

### ISSUE THREAD

**Issue by MrVeink** [certbot/certbot#9183]
## My operating system is (include version):
NAME="Oracle Linux Server"
VERSION="7.9"

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
Installed it via snapd with following command: `sudo snap install --classic certbot`.

## I ran this command and it produced this output:
The command ran was: `sudo certbot certonly --standalone --preferred-challenges http -d xxx.example.com` and I got a single line error: `Segmentation fault`.

## Certbot's behavior differed from what I expected because:
I've used this software before and I got the cert files. Now it errors.

## Here is a Certbot log showing the issue (if available):
There was no log file.

**Comment by alexzorin** [comment]
I'm going to close this in favor of https://github.com/certbot/certbot/issues/9138, which is a duplicate.
