### ISSUE TITLE
Handle pip warnings in release script

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#9195]
We recently started getting warnings from `pip` when running our release script due to https://github.com/pypa/pip/issues/10825#issue-1113248408. Essentially, the problem is the server we have `pip` install packages from isn't compliant with Python packaging standards. The raised warnings look like:
```
warning: bad-index-doctype

× The package index page being used does not have a proper HTML doctype declaration.
╰─> Problematic URL: http://localhost:1234/certbot/

note: This is an issue with the page at the URL mentioned above.
hint: You might need to reach out to the owner of that package index, to get this fixed. See https://github.com/pypa/pip/issues/10825 for context.
```

_Maybe_ we could convince ourselves the warning is OK and live with it, but I think it'd be best to fix the problem. What's a better way to install local packages that `pip` doesn't complain about?

This probably also needs to be fixed in the `josepy` release script.

**Comment by ohemorange** [comment]
Well, for the easiest fix, it shouldn't be too hard to match the spec they're looking for right? We might just be able to throw in a `<!doctype html>`, maybe enclose the whole thing in `html` tags. Where does the code that sets up that custom index live? Or was it just manually created?

**Comment by ohemorange** [comment]
1. Wait, then why were we spinning up a local server in the first place? To smooth the transition from a previous version that used a remote server? Documentation [seems to imply](https://packaging.python.org/en/latest/tutorials/installing-packages/#installing-from-a-local-src-tree) that you can basically just point it to the local files. Though it's possible that won't work, in which case the next recommendation on that page is to basically do what we're doing, if you need anything fancier. But they do have a page explaining how it's really [not that hard to do so](https://www.python.org/dev/peps/pep-0503/), if we do need to.

2. Hm, we might be using the locally installed package to grab `cli-help.txt`, but that seems to be the only thing, and might not necessarily need it to be installed. It might be providing something nicer than what you get from just the local package possibly.
