### ISSUE TITLE
cert-path and key-path ignored

### ISSUE THREAD

**Issue by pelacables** [certbot/certbot#9203]
## My operating system is (include version):

Scientific Linux 7.9

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

pip

## I ran this command and it produced this output:

`/opt/certbot/bin/certbot -vvvvvv  certonly --cert-path /etc/ssl/vieas00114.cert  --key-path /etc/ssl/vieas00114.key  --standalone --text --agree-tos --non-interactive -c /etc/letsencrypt/cli.ini --rsa-key-size 4096 --renew-with-new-domains  --config-dir /opt/certbot/root/etc --work-dir /opt/certbot/root/var --logs-dir /opt/certbot/root/log -d mytest.eu.boehringer.com`

```
Writing new config /opt/certbot/root/etc/renewal/mytest.eu.boehringer.com.conf.
Notifying user:
Successfully received certificate.
Certificate is saved at: /opt/certbot/root/etc/live/mytest.eu.boehringer.com/fullchain.pem
Key is saved at:         /opt/certbot/root/etc/live/mytest.eu.boehringer.com/privkey.pem
This certificate expires on 2023-02-15.
These files will be updated when the certificate renews.

Successfully received certificate.
Certificate is saved at: /opt/certbot/root/etc/live/mytest.eu.boehringer.com/fullchain.pem
Key is saved at:         /opt/certbot/root/etc/live/mytest.eu.boehringer.com/privkey.pem
This certificate expires on 2023-02-15.
These files will be updated when the certificate renews.
```

## Certbot's behavior differed from what I expected because:

certificate and key are not saved in the path specified with --cert-path and --key-path

**Comment by osirisinferi** [comment]
If I read and understand the documentation correctly, the behavior you want is *not* where the options are intended for. From the documentation:

> paths:
>   Flags for changing execution paths & servers
> 
>   --cert-path CERT_PATH Path to where certificate is saved (with certonly
>                         --csr), installed from, or revoked (default: None)
>   --key-path KEY_PATH   Path to private key for certificate installation or
>                         revocation (if account key is missing) (default: None)

So it seems `--cert-path` is actually only useful when you're using the `--csr` option when acquiring a certificate, not when you're running Certbot regularly.

Same goes for the `--key-path`, which seems to be useful only when revoking a certificate.

(NB: it seems there is *no* explanation given in the documentation for when `--chain-path` and `--fullchain-path` are used, but I wouldn't count on it for being useful in your situation.)

**Comment by wgreenberg** [comment]
The docs could stand to be clarified here, but yeah as @osirisinferi said those parameters only affect `certonly` when getting a cert w/ `--csr`.

In general, certbot wants to manage its certs in its config dir (`/opt/certbot/root/etc/` in your case), and if you need them available elsewhere, I'd recommend either symlinking `/etc/ssl/vieas00114.cert` to `/opt/certbot/root/etc/live/mytest.eu.boehringer.com/fullchain.pem` or creating a post hook to copy it into the right place.
