### ISSUE TITLE
Give external contributors access to triage doc

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#9206]
We have a document describing how we respond to issues and PRs on an internal wiki. We've had more external contributors helping us with that lately and I'd like for them to have access to that doc so they're aware of our processes.

We could potentially give these people access to the internal wiki, but I'd personally prefer to move this wiki entry into `certbot/docs` or reopen the wiki on this public repo.

**Comment by ohemorange** [comment]
Went with wiki re-opening option. Cleared out old pages (just deleted them, if we need them for any reason the history is there), created a [new page](https://github.com/certbot/certbot/wiki/Triage-instructions) with the copied triage instructions, added some intro text to the triage page, and briefly updated the description on the public wiki [homepage](https://github.com/certbot/certbot/wiki). Also the [private page](https://github.com/EFForg/certbot-misc/wiki/Triage) now links to the public one for instructions so we don't have it in multiple places. Rotation info is still on the private one. Let me know if there's anything I can improve or add.

**Comment by bmw** [comment]
Love it. Thanks a lot Erica.
