### ISSUE TITLE
Certbot installation failed on macOS Big Sur

### ISSUE THREAD

**Issue by shekhardhar** [certbot/certbot#9215]
## I ran this command and it produced this output: brew install certbot

Warning: No available formula with the name "certbot".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by alexzorin** [comment]
Works for me.

Check:

    brew doctor

**Comment by shekhardhar** [comment]
~ % brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew/homebrew-core was not tapped properly! Run:
  rm -rf "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core"
  brew tap homebrew/core

Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo homebrew/core) checkout master
  

Fixed the warning and now I am able to install certbot. Thanks, @alexzorin for the help.
