### ISSUE TITLE
regex in server_name not match

### ISSUE THREAD

**Issue by qian2501** [certbot/certbot#9221]
Need some help on server_name with regex
I have some thing like:

> server_name sub.[0-9]+.somewhere.com;

nginx can handle it and connect, but `certbot —nginx` does not show this host

**Comment by alexzorin** [comment]
Hi @qian2501,

Thanks for the report.

Certbot requires the pattern to be denoted with a delimiter (tilde `~`), to understand that it is a regex: 

```nginx
  server_name ~sub.[0-9]+.somewhere.com
```

The nginx documentation states:

>Regular expressions are specified with the preceding “~*” modifier (for case-insensitive matching), or the “~” modifier (for case-sensitive matching).

I hear your point that nginx seems to work without the tilde anyway. Nonetheless, I do not think that this is going to be something we're going to try fix. My suggestion is to include the tilde in your patterns, if you wish to use Certbot.

**Comment by qian2501** [comment]
Thanks a lot, I just need some enlightening here, and sorry, I should have ask this kind of question on SO
