### ISSUE TITLE
How to install custom authenticator plugin on windows

### ISSUE THREAD

**Issue by Silex** [certbot/certbot#9222]
Hello,

I see that the windows installer installs Python 3.9.7.

My goal is to use https://github.com/Infomaniak/certbot-dns-infomaniak which wants to be installed using `pip`.

Am I right thinking that the windows installer is a dead end? I should probably uninstall it, then install python/pip for windows and install certbot using pip and then attempt the authenticator plugin installation right?

**Comment by osirisinferi** [comment]
I'm not sure it's wise to mess around with a whole separate installation using pip on Windows.

I'm also not sure if the following is good advice, but I've just tried to install the plugin you've mentioned manually and that seems to work. Where "seems to work" means I can see the plugin when running `certbot plugins`.

What I've done is the following:

* Download the `wheel` ("Built Distribution", file with `.whl` extension) from https://pypi.org/project/certbot-dns-infomaniak/#files
* Unpack the `wheel` file, which is just a ZIP file, into `C:\Program Files (x86)\Certbot\pkgs`
* You can just rename the `.whl` file to `.whl.zip` if necessary
* You now should have the directories `certbot_dns_infomaniak` and `certbot_dns_infomaniak-0.1.15.dist-info` in the `pkgs` dir, among all the other packages
* Remove the file `dns_infomaniak_test.py` from the `certbot_dns_infomaniak` directory, it isn't necessary and requires unavailable dependencies
* Edit the file `METADATA` in the `certbot_dns_infomaniak-0.1.15.dist-info` directory using WordPad (NotePad doesn't recognise the newlines correctly):
  * Look for the lines containing `Requires-Dist: mock` and `Requires-Dist: requests-mock`
  * Remove those two lines
  * Save the file and close WordPad
* Now Certbot should recognise the plugin.

**Comment by Silex** [comment]
@osirisinferi: thanks a lot! I'll give it a try and report. If the windows route doesn't work I'll have it generated on a linux box and copy the results to the windows machine.

Maybe it even makes sense to have one centralized linux box that generates the various certificates for other boxes.

**Comment by Silex** [comment]
Everything works! I was able to generate a certificate using the plugin. Thanks a lot 👍

**Comment by bmw** [comment]
If you're familiar with things like Python virtual environments (so you don't clutter the global Python installation) and manually configuring Certbot to renew your certificates before they expire, installing Certbot on Windows through `pip` _should_ work.

With that said, https://github.com/certbot/certbot/issues/8048 is tracking developing a better way for people to do this.

**Comment by osirisinferi** [comment]
> installing Certbot on Windows through `pip` _should_ work

That would require installing Python separately from Certbot first and then use the [virtual environment instructions](https://packaging.python.org/en/latest/tutorials/installing-packages/#creating-and-using-virtual-environments), right? And when that's set up and activated, you can use the [pip instructions of Certbot](https://certbot.eff.org/instructions?ws=other&os=pip) to install Certbot. And if necessary, install a third party plugin using `pip` too.

**Comment by bmw** [comment]
> That would require installing Python separately from Certbot first and then use the [virtual environment instructions](https://packaging.python.org/en/latest/tutorials/installing-packages/#creating-and-using-virtual-environments), right?

Exactly.

While our `pip` instructions at https://certbot.eff.org are UNIX specific, you'd essentially want to take the equivalent actions on Windows.
