### ISSUE TITLE
Out of date python in snap?

### ISSUE THREAD

**Issue by mohamedhafez** [certbot/certbot#9257]
After installing the certbot snap on Ubuntu 20.04 and running `/snap/certbot/current/bin/python3 --version`, it tells me the bundled python version is 3.8.10. This is several security releases behind the current 3.8.13.

1) Is this using Ubuntu 20.04's patched version of 3.8.10 that includes all the recent security fixes?
2) If not, has someone carefully examined the issues fixed between 3.8.10 and 3.8.13 and determined they don't apply to certbot?

If neither 1) nor 2) is the case, then its necessary to update the bundled python and keep it up to date with security releases. Otherwise, sorry for the false alarm, just checking!

**Comment by alexzorin** [comment]
>Is this using Ubuntu 20.04's patched version of 3.8.10 that includes all the recent security fixes?

Yes, that is exactly right. The Certbot snap gets Python 3.8 from the `core20` base, which is based on Ubuntu 20.04:

    root@primary:~# snap run --shell certbot
    root@primary:~# grep python3.8 $SNAP/snap/manifest.yaml
        - libpython3.8-dev=3.8.10-0ubuntu1~20.04.2
        - libpython3.8-minimal=3.8.10-0ubuntu1~20.04.2
        - libpython3.8-stdlib=3.8.10-0ubuntu1~20.04.2
        - libpython3.8=3.8.10-0ubuntu1~20.04.2
    ....

 This comes with backported security fixes: http://changelogs.ubuntu.com/changelogs/pool/main/p/python3.8/python3.8_3.8.10-0ubuntu1~20.04.4/changelog.

**Comment by alexzorin** [comment]
1.26.0 was released today and the snap contains an updated release Python 3.8. I'm going to close this as I think the question is answered.
