### ISSUE TITLE
certbot-dns-google 1.25.0 vulnerabilities?

### ISSUE THREAD

**Issue by vankatamarinov** [certbot/certbot#9265]
Hello,
in this security month, one of our security reports informs us about vulnerabilities but we are not sure which of them are real and which are false positives? Can you help me evaluate them?

Can be seen here: https://pastebin.com/5cd3rXLL

**Comment by alexzorin** [comment]
Hello,

I don't think we have the resources to go through the results of a automated code scanners like this one.

At a glance, I did not see anything useful in this report.

We do receive and triage alerts about known vulnerabilities in our dependencies, through other channels.
