### ISSUE TITLE
No ipdb in dev venv environment

### ISSUE THREAD

**Issue by Ignalion** [certbot/certbot#9270]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
MacOS 12 Monterey (M1 chip)

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
git clone

## I ran this command and it produced this output:
tox -e py3-cover

```
>       import ipdb; ipdb.set_trace()
E       ModuleNotFoundError: No module named 'ipdb'
```
in venv
despite the fact that it is installed. I think something with venv paths in 

## Certbot's behavior differed from what I expected because:
The Development Guide says that:
After running this command, certbot and development tools like ipdb, ipython, pytest, and tox are available in the shell where you ran the command. 
Actually, it's true for three commands except ipdb. It isn't present in terminal and interpreter can't see it.

**Comment by alexzorin** [comment]
Reading over https://pypi.org/project/ipdb/, it looks like they named it `ipdb3` in Python 3. Certbot dropped Python 2 support some time ago.

That binary is available in my venv.

**Comment by Ignalion** [comment]
Well, the binary `ipdb3` is indeed present, although for some reason ipdb module itself isn't in the venv path so I still getting error:
```
>       import ipdb; ipdb.set_trace()
E       ModuleNotFoundError: No module named 'ipdb'
```

**Comment by osirisinferi** [comment]
That piece of Python code is from your own hands, right? I believe @alexzorin means you should use `ipdb3` in your code, like: `import ipdb3`.

**Comment by alexzorin** [comment]
For me, `import ipdb` within the venv's copy of Python, is successful.

Did you set up the environment using `tools/venv.py`? Are you using `venv/bin/python` as your interpreter when you try to import it?

**Comment by Ignalion** [comment]
> For me, `import ipdb` within the venv's copy of Python, is successful.
> 
> Did you set up the environment using `tools/venv.py`? Are you using `venv/bin/python` as your interpreter when you try to import it?

Yes, i'm using `tools/venv.py` i'm activating the environment and I'm using tox from venv as test runner. So, maybe that's the issue, maybe tox don't use `venv/bin/python ` interpreter?
I printed sys.path and it does include `.tox/py3-cover/lib/python3.10/site-packages` but doesn't include `venv/lib/python3.10/site-packages` where ipdb is actually installed.



> That piece of Python code is from your own hands, right?

Yeah, I'm trying to set a breakpoint in the code actually

**Comment by alexzorin** [comment]
Aha, good catch. I believe this is intentional.

`tox` installs `certbot[test]`.

However, `ipdb` is only available in `certbot[dev]` and `certbot[all]`.

If you want to make `ipdb` available during unit tests, you will need to temporarily add `ipdb` to the `test_extras` of the module you are testing.

**Comment by Ignalion** [comment]
Oh, I see. Thank you for the info! It works now
