### ISSUE TITLE
How to configure policy file for certbot-dns-route53 in order to constrain modifications to a single subdomain?

### ISSUE THREAD

**Issue by nicolas-van** [certbot/certbot#9281]
Currently the [documentation of certbot-dns-route53](https://certbot-dns-route53.readthedocs.io/en/stable/) gives the following policy file example:

```json
{
    "Version": "2012-10-17",
    "Id": "certbot-dns-route53 sample policy",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "route53:ListHostedZones",
                "route53:GetChange"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect" : "Allow",
            "Action" : [
                "route53:ChangeResourceRecordSets"
            ],
            "Resource" : [
                "arn:aws:route53:::hostedzone/YOURHOSTEDZONEID"
            ]
        }
    ]
}
```

This example works without problem. Unfortunately it's giving a bit too much power to the user as it confers full edition capabilities to all records in the hosted zone.

Does anybody already created a policy file that works correctly but constrain the user to editions related to a single subdomain ? Is it technically possible? (I'm not 100% sure DNS01 challenge could work by editing only subdomain records, nor am I sure that IAM allows to specify access right with that kind of granularity).

**Comment by bmw** [comment]
In general when writing our DNS plugins, we unfortunately found that most DNS APIs required the user to supply very broad permissions like this. https://www.eff.org/deeplinks/2018/02/technical-deep-dive-securing-automation-acme-dns-challenge-validation is a blog post one of Certbot's engineers wrote on the topic.

The most relevant bits about this topic and route53 in particular are:

> ### Separate and Limited Privileges
> Strictly speaking, in order for the ACME client to handle updates in an automated fashion, the client only needs to have access to credentials that can update the TXT records for "_acme-challenge" subdomains. Unfortunately, most DNS software and DNS service providers do not offer granular access controls that allow for limiting these privileges, or simply do not provide an API to handle automating this outside of the basic DNS zone updates or transfers. This leaves the possible automation methods either unusable or insecure.
>
> A simple trick can help maneuver past these kinds of limitations: using the [CNAME record](https://en.wikipedia.org/wiki/CNAME_record). CNAME records essentially act as links to another DNS record. Let's Encrypt follows the chain of CNAME records and will resolve the challenge validation token from the last record in the chain.
> ### Ways to Mitigate the Issue
> ...
> #### Limited DNS Zone Access
> ...
> Route53 and possibly others allow their users to create a subdelegate zone, new user credentials, point NS records towards the new zone, and point the "_acme-challenge" validation subdomains to them using the CNAME records. It’s a lot of work to do the privilege separation correctly using this method, as one would need to go through all of these steps for each domain they would like to use DNS challenges for.

If you'd like more help with this, I recommend you make a post at https://community.letsencrypt.org where there is a larger community familiar with server administration which can likely better help you with this kind of thing.

**Comment by spladug** [comment]
In case it's helpful to anyone else coming across this issue, I found that you can apply some conditions to the `ChangeResourceRecordSets` action like so:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "route53:ListHostedZones",
                "route53:GetChange"
            ],
            "Resource": "*"
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": "route53:ChangeResourceRecordSets",
            "Resource": "arn:aws:route53:::hostedzone/YOURHOSTEDZONEID",
            "Condition": {
                "ForAllValues:StringEquals": {
                    "route53:ChangeResourceRecordSetsRecordTypes": "TXT"
                },
                "ForAllValues:StringLike": {
                    "route53:ChangeResourceRecordSetsNormalizedRecordNames": "_acme-challenge.*.mydomain.com"
                }
            }
        }
    ]
}
```

You could change the `ChangeResourceRecordSetsNormalizedRecordNames` condition to match specific hostnames or broader wildcards depending on your needs.

**Comment by razvanphp** [comment]
hey @spladug, THANK YOU!

Yes, this definitely should go into the readme, please submit that PR; from a DevOps perspective, the Principle of Least Privilege (POLP) is a must in any decent SMB. [Recently AWS Route53 added this feature](https://aws.amazon.com/about-aws/whats-new/2022/09/amazon-route-53-support-dns-resource-record-set-permissions/) so the blog post linked above is irelevant now.

For posterity, I just want to link this article here: https://paulgalow.com/aws-route-53-iam-policy-letsencrypt-dns/

I've tried a variation with `StringEquals` and `_acme-challenge.domain.com` and it **didn't** work. Not sure why, since locally with aws-cli it works (also works with `.*` like in your snippet), not sure what the script tries to do, I get this in the logs:
```
2023-08-11 00:18:03.428054+00:00E0811 00:18:03.427873       1 controller.go:167] "cert-manager/challenges: re-queuing item due to error processing" err="failed to change Route 53 record set: AccessDenied: User: arn:aws:iam::5900000000:user/TrueNAS2 is not authorized to perform: route53:ChangeResourceRecordSets on resource: arn:aws:route53:::hostedzone/Z0981737XXXXXXXX because no identity-based policy allows the route53:ChangeResourceRecordSets action" key="ix-prometheus/prometheus-tls-0-jblwz-1250387731-3242818995"
```

**Comment by SiC-IoNs** [comment]
Hey thank you for your previous posts!
I found a way to set permission challenges only for a specific domain or subdomain.
I think the cerbot sends a challenge under domain name `_acme-challenge.<DOMAIN_IN_CERTBOT_COMMAND>.`
Therefore, you have to specify in the permissions policy file under `"ForAllValues:StringLike"` with `"route53:ChangeResourceRecordSetsNormalizedRecordNames":_acme-challenge.<DOMAIN_IN_CERTBOT_COMMAND>`.

To clear confusion here is what i used.
To test the DNS01 challenge for domain `alpha.example.com` use a dry run:
`sudo certbot certonly --dry-run --test-cert --dns-route53 -d "alpha.example.com" -i apache -v`
With permission policy file:
```{
    "Version": "2012-10-17",
    "Id": "<YOUR-POLICY-ID>",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "route53:ListHostedZones",
                "route53:GetChange"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect" : "Allow",
            "Action" : [
                "route53:ChangeResourceRecordSets"
            ],
            "Resource" : [
                "arn:aws:route53:::hostedzone/YOURHOSTEDZONEID"
            ],
            "Condition": {
                "ForAllValues:StringEquals": {
                    "route53:ChangeResourceRecordSetsNormalizedRecordNames": [
                        "_acme-challenge.alpha.example.com"
                    ],
                    "route53:ChangeResourceRecordSetsRecordTypes": [
                        "TXT"
                    ]
                }
            }
        }
    ]
}
```
It should not grant you permission if you send the challenge for a different subdomain as `beta.example.com`:
`sudo certbot certonly --dry-run --test-cert --dns-route53 -d "beta.example.com" -i apache -v`.
