### ISSUE TITLE
Allow use with internal CA

### ISSUE THREAD

**Issue by toftstade** [certbot/certbot#9290]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Windows Server 2019 Standard (1809)

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
Installer / certbot-beta-installer-win_amd64.exe

## I ran this command and it produced this output:
input:
`certbot certonly --webroot --server ***.com --preferred-challenges=http -d ***.com --webroot-path C:\*** -m "test@***.com"`

output:
`An unexpected error occurred:
requests.exceptions.SSLError: HTTPSConnectionPool(host='internal.acme.server', port=443): Max retries exceeded with url: /acme/directory (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))`

## Certbot's behavior differed from what I expected because:
Server url provided with --server switch points to an internal CA with a private CA Root.
Certbot seems to use urllib3 when making requests without providing any means to also accomodate for a private CA using internally trusted certificates. One solution would be to use python-certifi-win32 with the windows-version. I tried exporting certificates to base64-encoded files and setting REQUESTS_CA_BUNDLE environment variable but it didn't seem to work.

## Here is a Certbot log showing the issue (if available):
See above

**Comment by alexzorin** [comment]
`--no-verify-ssl` will do what you want.

**Comment by alexzorin** [comment]
I've given `REQUESTS_CA_BUNDLE` a try using the 1.24.0 release of Certbot for Windows.

It appears to work OK:

    C:\Program Files (x86)\Certbot>certbot register --server https://untrusted-root.badssl.com --register-unsafely-without-email
    Saving debug log to C:\Certbot\log\letsencrypt.log
    An unexpected error occurred:
    requests.exceptions.SSLError: HTTPSConnectionPool(host='untrusted-root.badssl.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
    Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile C:\Certbot\log\letsencrypt.log or re-run Certbot with -v for more details.

    C:\Program Files (x86)\Certbot>set REQUESTS_CA_BUNDLE=C:\untrusted-root.pem

    C:\Program Files (x86)\Certbot>certbot register --server https://untrusted-root.badssl.com --register-unsafely-without-email
    Saving debug log to C:\Certbot\log\letsencrypt.log
    An unexpected error occurred:
    acme.errors.ClientError: Unexpected response Content-Type: text/html
    Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile C:\Certbot\log\letsencrypt.log or re-run Certbot with -v for more details.

    C:\Program Files (x86)\Certbot>

If you can provide more detail on what you're doing differently then we might be able to help you, but I can't reproduce this for now.

**Comment by toftstade** [comment]
It seems my certificate export was to blame; after exporting from web browser again it worked fine. Sorry about the trouble and thank you for your time.
