### ISSUE TITLE
Using certbot inside an Apache httpd container

### ISSUE THREAD

**Issue by o-alquimista** [certbot/certbot#9291]
The documentation for [running with docker](https://eff-certbot.readthedocs.io/en/stable/install.html#running-with-docker) says:
> This mode of operation is unable to install certificates or configure your webserver, because our installer plugins cannot reach your webserver from inside the Docker container.

With certbot containerized, it can't reach httpd on your host. Fine. I actually have httpd in a container. What if I run certbot *inside* the httpd container?

The documentation doesn't cover it, but I wanna try this. If it works, I can make a contribution.

Using image `certbot/certbot:1.26.0`.

**Comment by wgreenberg** [comment]
running certbot in the same container as httpd should work, the most obvious potential issue being that certbot uses `systemctl` to restart/reload Apache depending on the detected OS, which won't work within a container. i haven't tested this personally, but if your container's OS is arch linux, certbot will use `apachectl` which might just work.

also, definitely make sure to bind-mount or volumize `/etc/letsencrypt` (or wherever you're storing your certs)!

**Comment by o-alquimista** [comment]
I've got certbot installed inside an alpine-based httpd image, but using the standalone plugin. The complete code is [here](https://gitlab.com/crimson.king/portfolio).

This is working well, but the approach I'm using makes the image extremely large (about 800 MB). Could I somehow bundle everything into an executable file? Or maybe I could get it from the Docker Hub image, but I couldn't yet figure out which file(s) to copy.

It's important to handle the differences in architecture, because I'm running both `amd64` and `arm64` over here.

`httpd.Dockerfile`
```Dockerfile
FROM httpd:2.4-alpine AS httpd

ARG USER_ID
ARG GROUP_ID

#
# dev stage
#

FROM httpd AS httpd_ssl

#
# prod stage
#

# https://github.com/certbot/certbot/blob/v1.26.0/certbot-apache/certbot_apache/_internal/tls_configs/current-options-ssl-apache.conf
COPY ./docker/httpd/certbot-ssl.conf /usr/local/apache2/conf/extra/certbot-ssl.conf

# Virtualhost for port 443
COPY ./docker/httpd/example.org-ssl.conf /usr/local/apache2/conf/extra/vhosts/example.org-ssl.conf

# Entrypoint script
COPY ./docker/httpd/ssl-entrypoint /usr/local/bin/ssl-entrypoint

# This is where I'm cloning the certbot repository
WORKDIR /certbot

# Get certbot and its dependencies
# "musl-dev" is Alpine-specific; venv.py fails without it
RUN apk update && apk add \
  git \
  python3 \
  python3-dev \
  gcc \
  musl-dev \
  augeas-libs \
  openssl \
  openssl-dev \
  libffi-dev \
  ca-certificates \
  && \
  git clone --branch v1.26.0 https://github.com/certbot/certbot . && \
  python3 tools/venv.py

# Equivalent to `source venv/bin/activate`
ENV PATH="/certbot/venv/bin:${PATH}"

# Fix permissions of directories used by certbot
RUN mkdir -p /var/log/letsencrypt /etc/letsencrypt /var/lib/letsencrypt && \
  chown -R ${USER_ID}:${GROUP_ID} /var/log/letsencrypt /etc/letsencrypt /var/lib/letsencrypt

VOLUME /etc/letsencrypt
VOLUME /var/lib/letsencrypt

ENTRYPOINT ["ssl-entrypoint"]
```

`ssl-entrypoint`
```sh
#!/bin/sh
set -e

# Run certbot before starting httpd

certbot certonly --standalone \
-d example.org -d www.example.org \
-m example@example.org \
--agree-tos --non-interactive

httpd-foreground
```

**Comment by wgreenberg** [comment]
I suspect a decent amount of the docker image's size is due to cloning the entire certbot repo & installing packages used only for setting up certbot from scratch (e.g. gcc, git, etc). Is it possible to just use the `certbot` package on alpine, rather than setting it up manually? Looks like they've v1.26 for both amd64 and arm64.

**Comment by osirisinferi** [comment]
Why not just build a multi-stage build using the Certbot docker image in combination with the httpd docker image?

**Comment by o-alquimista** [comment]
> Why not just build a multi-stage build using the Certbot docker image in combination with the httpd docker image?

That would save a lot of space. I just need to figure out which files to copy from `certbot/certbot` to `httpd` and how to run it. From a quick look at this [Dockerfile](https://github.com/certbot/certbot/blob/v1.26.0/tools/docker/core/Dockerfile) I guess it's the `/opt/certbot` directory. I'm also going to need Python at runtime.

**Comment by osirisinferi** [comment]
> That would save a lot of space. I just need to figure out which files to copy from `certbot/certbot` to `httpd` and how to run it. From a quick look at this [Dockerfile](https://github.com/certbot/certbot/blob/v1.26.0/tools/docker/core/Dockerfile) I guess it's the `/opt/certbot` directory. I'm also going to need Python and other dependencies at runtime.

I think that might work indeed.

Alternatively, you could run `apk add certbot-apache` in your `httpd` container and call Certbot using `certbot --apache --apache-server-root /usr/local/apache2 --apache-ctl apachectl` (at least for the first time, not sure if Certbot remembers the `--apache-server-root` and `--apache-ctl` options. If not, you probably could add them to the `cli.ini` file.)

**Comment by blackblather** [comment]
@o-alquimista How does certbot complete the CA challenge if it is executed before the webserver is running?

**Comment by o-alquimista** [comment]
> @o-alquimista How does certbot complete the CA challenge if it is executed before the webserver is running?

Certbot spins up its own webserver (`--standalone`) for the challenge.

**Comment by blackblather** [comment]
Ah thank you. You cleared up some misconceptions I had regarding `--standalone`. 👌
