### ISSUE TITLE
Certbot should stop querying when order status is invalid

### ISSUE THREAD

**Issue by billsg** [certbot/certbot#9296]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 20.04

## I ran this command and it produced this output:
sudo certbot certonly --server *** --domain *** --preferred-challenges=http --manual

## Certbot's behavior differed from what I expected because:
In RFC8555: [7.1.6](https://datatracker.ietf.org/doc/html/rfc8555#section-7.1.6).  Status Changes
When getOrder action returns invalid, certbot should stop querying.
However certbot continue querying getOrder url until timeout.

**Comment by alexzorin** [comment]
>  When getOrder action returns invalid, certbot should stop querying.
> However certbot continue querying getOrder url until timeout.

To clarify the scenario, the ACME server is setting the order `status` to `invalid` during finalization, but the `error` field is not set?

**Comment by billsg** [comment]
If we return AcmeError, then there is no need to return getOrderResponse anymore. 

However we still hope that if we retuen getOrderResposne with status "invalid", the client should stop querying the back end.

And we notice that even we return invalid status with cert URL, the client still trying to download the cert and shown successful enrollment:

HTTP/1.1 201 Created
Replay-Nonce: MYAuvOpaoIiywTezizk5vw
Link: <https://example.com/acme/directory>;rel="index"
Location: https://example.com/acme/order/TOlocE8rfgo

{
    "status": "pending",
    "expires": "2016-01-05T14:09:07.99Z",

    "notBefore": "2016-01-01T00:00:00Z",
    "notAfter": "2016-01-08T00:00:00Z",

    "identifiers": [
        { "type": "dns", "value": "www.example.org" },
        { "type": "dns", "value": "example.org" }
    ],

    "authorizations": [
        "https://example.com/acme/authz/PAniVnsZcis",
        "https://example.com/acme/authz/r4HqLzrSrpI"
    ],

    "finalize": "https://example.com/acme/order/TOlocE8rfgo/finalize",

     "certUrl":"https://example.com/acme/cert"
}

**Comment by alexzorin** [comment]
We'll fix order finalization to pay closer attention to the order `status. However;

>If we return AcmeError, then there is no need to return getOrderResponse anymore.

I'm not sure I understand you here. The Order resource has an `error` field: https://datatracker.ietf.org/doc/html/rfc8555#section-7.1.3. If you set an order's `status` to `invalid`, setting the `error` field is also helpful to Certbot because we can display the reason for the failed issuance to the user.

**Comment by alexzorin** [comment]
Could you please show me the order response which generates the above screenshot?

**Comment by osirisinferi** [comment]
Maybe the Certbot log file might be handy too, methinks.

**Comment by billsg** [comment]
> Maybe the Certbot log file might be handy too, methinks.

Yes. It just not very convenient for the customers.

**Comment by osirisinferi** [comment]
> Yes. It just not very convenient for the customers.

I meant for in this issue for debugging purposes :)
