### ISSUE TITLE
Mac 12.4 plugins install brew install -cloudflare does not work

### ISSUE THREAD

**Issue by jamengual** [certbot/certbot#9298]
## My operating system is (include version):
Mac 12.4
brew --version
Homebrew 3.4.11
Homebrew/homebrew-core (git revision deafcf6ae27; last commit 2022-05-20)
Homebrew/homebrew-cask (git revision f7afed5cb1; last commit 2022-05-20)

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
brew install certbot

## I ran this command and it produced this output:
brew install -cloudflare
Error: ambiguous option: -cloudflare

## Certbot's behavior differed from what I expected because:
Expected installation of the plugin to work

Workaround :
pip3.9 install certbot-dns-cloudflare ( use whatever pip was installed with brew in your system.

**Comment by osirisinferi** [comment]
If I look at https://formulae.brew.sh/ there are no DNS plugins available for Homebrew it seems. Even though the Certbot instructions suggest as such, but incorrectly. @alexzorin has already opened an issue about this in the `/certbot/website/` repository: https://github.com/certbot/website/issues/767 Therefore I'm going to close this issue as a duplicate, even though it's a different repository. :slightly_smiling_face: (As it's not a Certbot issue, but an instruction issue.)
