### ISSUE TITLE
`show_account` broken in combination with ACMEv1 account reuse using symbolic links

### ISSUE THREAD

**Issue by osirisinferi** [certbot/certbot#9306]
Reported on the Community here: https://community.letsencrypt.org/t/certbot-show-account-fails-with-acme-v01-api-letsencrypt-org-dns-lookup-failure/178367

Since #6156 ACMEv1 account reuse is done using symbolic links. 

In #9127 the `show_account` subcommand was introduced, making use of the [`query_registration`](https://github.com/certbot/certbot/blob/5c111d0bd1206d864d7cb93754e101f6073bc669/acme/acme/client.py#L641-L655) function of the `acme` library, passing the `regr` object from the account to that function.

However, when symbolic link account reuse is in place, the `regr` object contains an account `uri` of the ACMEv1 protocol, including the now-nonexisting `acme-v01` API URL. That URI is directly used in [`_send_recv_regr()`](https://github.com/certbot/certbot/blob/5c111d0bd1206d864d7cb93754e101f6073bc669/acme/acme/client.py#L84), triggering a DNS error.

Possible fixes:

* Detect ACMEv1 account URI and translate it into an ACMEv2 account URI *in Certbots `main.show_account`* and keep using `query_registration`, or
* Detect ACMEv1 account URI and translate it into an ACMEv2 account URI *in acme's `client.query_registration`*, or
* Rewrite Certbots `main.show_account()` to *not* use `query_registration` but build a signed request for `newAccount` on its own.

**Comment by alexzorin** [comment]
Assuming that the `acme` module makes it possible, I prefer the `newAccount` option. 

However, in the past I noticed that the possibility to do this is not part of the public API: see `acme.ClientV2._get_v2_account`. Neither `new_account` nor `query_registration` fits the bill for what we want to do. 

I am wondering out loud: why we can't change the implementation of `query_registration` to call `_get_v2_account`?
