### ISSUE TITLE
Change snapcraft authentication to use SNAPCRAFT_STORE_CREDENTIALS

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#9323]
CI [is failing](https://dev.azure.com/certbot/ba534f81-a483-4b9b-9b4e-a60bec8fee72/_apis/build/builds/5568/logs/431) with:

    2022-06-15T06:21:43.1199655Z --with is no longer supported, export the auth to the environment variable 'SNAPCRAFT_STORE_CREDENTIALS' instead                                               
    2022-06-15T06:21:43.1204431Z Login successful                                                               
    2022-06-15T06:21:45.0246699Z This login method is not longer supported

This refers to the `snapcraft login` line here:

https://github.com/certbot/certbot/blob/7505bb0c6007621fe390dc712c37917ef6b6be38/.azure-pipelines/templates/stages/deploy-stage.yml#L67

This has happened because in snapcraft 7, [it seems that this authentication method is no longer supported](https://forum.snapcraft.io/t/call-for-testing-snapcraft-7/30201?u=_az):

>Store operations with externally generated credentials
>
>Snapcraft has migrated to usinng [craft-store 3](https://craft-store.readthedocs.io/en/latest/). The authentication mechanism has changed, impacting those integrating with CI/CD. The `snapcraft login --with` command structure is no longer supported or required. The value of export login needs to be exported into the appropriate environment variable (i.e.; `SNAPCRAFT_STORE_CREDENTIALS`).

I think we need to replace the credentials file with the environment variable populated by the evaluation of `snapcraft export-login`, make it available in the `nightly` and `release` pipelines as described originally, and then remove the call to `snapcraft login` (? unclear if last thing is necessary):

https://github.com/certbot/certbot/blob/7505bb0c6007621fe390dc712c37917ef6b6be38/.azure-pipelines/templates/stages/deploy-stage.yml#L12-L35

**Comment by ohemorange** [comment]
Hm, the docs sound like even the credential generation process is updated, so we'll probably have to generate them using the new method: https://craft-store.readthedocs.io/en/latest/howtos.html
