### ISSUE TITLE
On Windows, doesn't create scheduled task when installed with pip

### ISSUE THREAD

**Issue by WhileLoop** [certbot/certbot#9325]
On Windows, Certbot doesn't create the scheduled task when installed with pip. On the same system, I installed Certbot from https://dl.eff.org/certbot-beta-installer-win32.exe and confirmed that the task was created.

I would prefer to use the Certbot Windows installer but I don't see a way to install plugins to the bundled Python distribution.

Steps to reproduce:
* Launch Windows Server 2022 Datacenter VM
* Install Python (https://www.python.org/ftp/python/3.10.2/python-3.10.2-amd64.exe)
* Run `pip install certbot certbot-dns-azure`
* Run `certbot certonly --preconfigured-renewal --authenticator dns-azure --preferred-challenges dns --noninteractive --agree-tos --dns-azure-config C:\azure-dns.ini -d example.com`
* Check Scheduled Tasks, Certbot task is not present.

**Comment by osirisinferi** [comment]
Is it even, in general, *possible* to install a Scheduled Task using `pip`?

**Comment by WhileLoop** [comment]
@osirisinferi This may be a documentation issue. The Certbot website says a scheduled task will be automatically created but doesn't make it clear that is only the case when installed with the Windows installer. Maybe a note there would suffice.

**Comment by osirisinferi** [comment]
> The Certbot website says a scheduled task will be automatically created but doesn't make it clear that is only the case when installed with the Windows installer.

Which page are you referring to exactly?

**Comment by alexzorin** [comment]
Our only `pip`-based instructions can be found here: https://certbot.eff.org/instructions?ws=other&os=pip. Although they are UNIX-oriented, there is a step there to set up a scheduled task.

`--preconfigured-renewal` is an internal and hidden flag. It is used by our snap, our Windows installer and our distro packagers to signal to Certbot program, that a scheduled task has been added externally. This allows us to vary what messages we display to the user when a certificate is issued. It doesn't do anything else.

Installation of plugins on Windows is tracked by #8048.

Certbot installing a scheduled task on its own is most likely not going to happen. We use the installers for this, and in the (partially-supported) case of pip-on-UNIX, it's up to the user to follow the provided instructions.

In a similar vein, I don't think we are prepared, for the time being, to be including pip-on-Windows as an option in our documentation.

Thanks
