### ISSUE TITLE
Implement locking to ensure two clients do not run at once

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#933]
Does the letsencrypt client establish a lock while it is running, so we don't have two separate LE instances trying to modify the same configuration files at once?

**Comment by bmw** [comment]
It does not. Running two instances of the client is a good way to break your config. Problems can also occur if the client and the renewer run at the same time. We may want to tag this issue for launch.

**Comment by kuba** [comment]
Dupe of #335 and #564?

**Comment by jsha** [comment]
Those are slightly different: they are about individual components: the cert db and lineage data. I'm suggesting an overall lock for all letsencrypt-related changes, which is probably simpler to reason about.

We would probably also want to make sure that manually-run clients time out after some time, to ensure that if you leave a terminal hanging in the middle of a `letsencrypt run` instance, it does not prevent renewals from happening.

**Comment by laebshade** [comment]
Isn't the binary ad-hoc?  Why prevent users from intentionally shooting themselves in the foot?

**Comment by bmw** [comment]
Reopening, but this will be done for 0.13.0.
