### ISSUE TITLE
[Feature Request] Private HostedZone support in certbot-dns-route53

### ISSUE THREAD

**Issue by aad** [certbot/certbot#9338]
Apologies if this is has been discussed.

In our aws setup, the aws's private hosted zone is kind of 'public' in our internal network since Its resolvable by all other machines internally. The cert signing for aws private hosted zone is managed by our internal pki, including the internal acme server (--server).

When we tried to create cert for the alias in private hosted zone, we found private hosted zone is skipped intentionally in the current certbot-dns-route53 plugin (https://github.com/certbot/certbot/blob/v1.28.0/certbot-dns-route53/certbot_dns_route53/_internal/dns_route53.py#L87-L88), hence certbot can not continue.

Is it possible to support considering private hosted zone in certbot-dns-route53? Happy to give it a try if its acceptable.

Thanks!

 
## My operating system is (include version):
Mac/Linux

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
pip

**Comment by qmugnier** [comment]
Too bad, it was actually making sense when you want to use acme implementations of apps like hashicorp vault or openbao internally to leverage the generation and auto renew of certs with standard clients like certbot as long as the vault server can resolve the internal names.
