### ISSUE TITLE
Certbot sends GET request to the order URL

### ISSUE THREAD

**Issue by creatica-soft** [certbot/certbot#9350]
## My operating system is (include version):
Windows 10

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
with OS installer

## I ran this command and it produced this output:
certbot.exe certonly --manual -d example.com
##other options are in config file
It sends GET request to order URL

## Certbot's behavior differed from what I expected because:
According to https://datatracker.ietf.org/doc/html/rfc8555#section-6.3 GET requests should only be
sent to NewNonce and Directory

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
2022-07-15 01:40:16,196:DEBUG:urllib3.connectionpool:https://server:443 "GET /acme/accounts/17845651851233067750/orders/14507744743890048869 HTTP/1.1" 405 77
2022-07-15 01:40:16,196:DEBUG:acme.client:Received response:
HTTP 405
Content-Type: application/problem+json
Content-Length: 77
Connection: keep-alive
Cache-Control: no-store
Replay-Nonce: MTMxMjc2NTU1MzEzNTc2MzA2MTc1MDQ0NTIxMDY1MDc2NTYyNzQ2MjUxNA

{"type":"urn:ietf:params:acme:error:malformed","detail":"method not allowed"}

**Comment by alexzorin** [comment]
I think we will need more detail (like the full log file) to identify what's happening here.

**Comment by creatica-soft** [comment]
It happens after submitting CSR and then polling for the certificate issuance.

2022-07-15 01:40:15,138:DEBUG:urllib3.connectionpool:https://server:443 "POST /acme/accounts/17845651851233067750/orders/14507744743890048869/csr HTTP/1.1" 302 713
2022-07-15 01:40:15,143:DEBUG:urllib3.connectionpool:Resetting dropped connection: pki.techcorpapps.com
2022-07-15 01:40:16,196:DEBUG:urllib3.connectionpool:https://server:443 "GET /acme/accounts/17845651851233067750/orders/14507744743890048869 HTTP/1.1" 405 77 

I don't know why it begins polling by sending POST to csr url instead of order url, I also was not able to find out why it gets redirect (302) to order url it seems logical. What is not logical is why it changes POST to GET after redirect.

**Comment by alexzorin** [comment]
>Unrelated issue is non-empty payload in POST-AS-GET to challenge url:

Are you sure that this is a POST-as-GET? It looks like the challenge response to me: https://datatracker.ietf.org/doc/html/rfc8555#section-7.5.1.

>and somehow status gets changed to 302

This doesn't sound likely to me. If the Certbot log says that it received an HTTP 302 from your ACME server, then it probably did.

**Comment by osirisinferi** [comment]
> This doesn't sound likely to me. If the Certbot log says that it received an HTTP 302 from your ACME server, then it probably did.

If I read the log correctly, it's the ACME server sending a HTTP 302 to the initial POST which results in a [Post/Redirect/Get](https://en.wikipedia.org/wiki/Post/Redirect/Get).

**Comment by creatica-soft** [comment]
Sorry if I wasn't clear. I don't think I've ever said that certbot changed the server's response. Of course, it was the server that sent 302. And I even tried to identify possible reasons for why it did it (RFC8555 lists it in its example with status code 200. Obviously, it is meaningless with 200. I think it might have been that the server's code was not explicit on the status code and later either php-fpm or nginx seeing the Location header, set 302. Anyway, this is no longer the issuer. I appoligise for creating this unnecessary issue and thanks for you help to understand what actually happened.

As the non-empty payload in POST-AS-GET concerns, I may not fully understand what challenge response means. But the log is clear, it is certbot's payload:
```
2022-07-19 14:43:33,175:DEBUG:acme.client:Sending POST request to https://pki.techcorpapps.com/acme/accounts/14336688870470774508/orders/7080861310268238649/authorizations/9240296490710005702/challenges/9636213494679776807:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vcGtpLnRlY2hjb3JwYXBwcy5jb20vYWNtZS9hY2NvdW50cy8xNDMzNjY4ODg3MDQ3MDc3NDUwOCIsICJub25jZSI6ICJNekV6TnpReU1qYzBNRFl4TlRVeU56UTNOVFUyTnpReE1EYzNNelEyTXpFMk1EQTJNalEwTXpZeU5BIiwgInVybCI6ICJodHRwczovL3BraS50ZWNoY29ycGFwcHMuY29tL2FjbWUvYWNjb3VudHMvMTQzMzY2ODg4NzA0NzA3NzQ1MDgvb3JkZXJzLzcwODA4NjEzMTAyNjgyMzg2NDkvYXV0aG9yaXphdGlvbnMvOTI0MDI5NjQ5MDcxMDAwNTcwMi9jaGFsbGVuZ2VzLzk2MzYyMTM0OTQ2Nzk3NzY4MDcifQ",
  "signature": "m417cjrUktpgqWtcLlMFt6Qv-IqsaZLMtHQba7peJHAWDKuH4GjISpfvdAYe23wu61C-CCNbXOn5WcNXEzpqLMH4fjtGr8KB6j0pZmOSd9xB-3S3qjWE0WjpSOqwqipDoa50xitatkCYEcGeH8vnfn_wzFv-Qv9H739hMd5TsIM1v-UMQi7XZUtUSQdAlgOk6q1a-JWCGBZda8SMk8cMCKSDLJAwtqFw1nDHU-60OSjaXPFo44DdpXZ3MWrAVnJLRPYMcPL4zx4zfFqbGXXba3AoxRsD8VDQvcWmgHElO73gyJF1l-IoCRULiNW1PMEo-5D20wYC9V7bz7oOZw_e-A",
  "payload": "e30"
}
```
My understanding RFC8555 is that after I fulfiled the manual challenge (save the file in /.well-known/acme-challenge/, the certbot sends the POST-AS-GET request to that challenge url, indicating to the server that the challenge is complete and ready for verification.

**Comment by creatica-soft** [comment]
This issue can be closed. I'd would really like if someone updates the certbot documentation in terms of explaining how to use REQUESTS_CA_BUNDLE or CURL_CA_BUNDLE to provided trusted root certs and that -eab-hmac-key is base64url encoding of raw key bytes. This would have made my experience with certbot ideal ) In any case, it is the best ACME client I have tested so far.

**Comment by osirisinferi** [comment]
> and that -eab-hmac-key is base64url encoding of raw key bytes. This would have made my experience with certbot ideal. In any case, it is the best ACME client I have tested so far.

Well, according to RFC 8555 the MAC key SHOULD be the base64url-encoded form of the key. CAs and ACME clients alike, doing their job correctly and adhering to the RFC, should thus all do the same. A user *should* not have to worry about which format the MAC key is, the user should just be able to use the stuff the CA/ACME server provided.

Adding more and more details to the documentation can also perhaps confuse users.. I.e., "Should I base64url the key I just got from the CA?", which potentially could lead to doing a *double* round of base64url encoding.
