### ISSUE TITLE
Trusted Certs option seems to be missing at least in documentation

### ISSUE THREAD

**Issue by creatica-soft** [certbot/certbot#9351]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Windows 10

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
installer

## I ran this command and it produced this output:
certbot.exe certonly --manual --no-verify-ssl -d example.com

without --no-verify-ssl it refuses to connect.

c:\Program Files (x86)\Certbot\pkgs\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'pki.techcorpapps.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

## Certbot's behavior differed from what I expected because:
The root and intermediate certs are trusted by Windows but certbot ignores this and I can't find any options to provide trusted certs.

**Comment by alexzorin** [comment]
Unfortunately the library we are using, `requests`, does not use the operating system trust store. 

[There is another option](https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification):

>https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification

**Comment by creatica-soft** [comment]
Great, this worked for me. Thanks a lot!
