### ISSUE TITLE
CSRs are not compliant with RFC 2986; use incorrect version

### ISSUE THREAD

**Issue by blackbird1999** [certbot/certbot#9362]
We've written an ACME server and the CSRs being sent by certbot are not compliant with RFC 2986. Instead of having a 0 in the version field (see section 4 of RFC 2986 which it states the version shall be 0) certbot's CSRs have a 2. A properly conforming certificate authority will reject these CSRs are being out of spec.

**Comment by bmw** [comment]
I believe this was fixed in https://github.com/certbot/certbot/pull/9334 in our last release. If you think I'm mistaken, please let me know and I'll take another look.

**Comment by blackbird1999** [comment]
Cool. We'll try the latest and greatest then.
