### ISSUE TITLE
`install` subcommand documentation missing from User Guide

### ISSUE THREAD

**Issue by osirisinferi** [certbot/certbot#9373]
When looking at https://eff-certbot.readthedocs.io/en/stable/using.html I can't find any documentation about the `install` subcommand. The only thing mentioned is:

> install:
>  Options for modifying how a certificate is deployed

It's not even mentioned in the "obtain, install, and renew certificates:" section.

However, when running `certbot --help install`, I'm seeing:

> install:
>   Options for modifying how a certificate is deployed
> 
>   --cert-path CERT_PATH
>                         Path to where certificate is saved (with certonly --csr), installed from, or revoked (default:
>                         None)
>   --key-path KEY_PATH   Path to private key for certificate installation or revocation (if account key is missing)
>                         (default: None)
>   --fullchain-path FULLCHAIN_PATH
>                         Accompanying path to a full certificate chain (certificate plus chain). (default: None)
>   --chain-path CHAIN_PATH
>                         Accompanying path to a certificate chain. (default: None)
>   --apache              Obtain and install certificates using Apache (default: False)
>   --nginx               Obtain and install certificates using Nginx (default: False)

There are multiple things, if you ask me, not complete with this:

* User Guide is missing the `install` info seen above;
* The above `certbot --help install` output is rather weird: whu do `--apache` and `--nginx` mention "**Obtain and** install (&hellip;)"?
* Generic documentation about how one would install an already issued certificate (e.g. with `certonly`) in their webserver. Does it take a `--cert-name` option? Or perhaps a `-d` option? I don't know. It's not documented.

**Comment by bmw** [comment]
I think there are a few subcommands not documented in our user guide. For instance, `register` isn't documented there either. Should it be? Arguably, but the guide is already quite long after focusing on the more commonly used functionality. We could/should create more comprehensive documentation somewhere, but I'm personally not sure if relying on `--help` output for this functionality is too bad.

> * User Guide is missing the `install` info seen above;

If you mean that these flags aren't listed, it's due to how `argparse` in the Python standard library works. You can't list a flag under multiple sections so we have these common flags listed under "paths" or "plugins" in the full help output shown in the user guide.

> * The above certbot --help install output is rather weird: whu do --apache and --nginx mention "Obtain and install (…)"?

Because the help text for these flags is generic. Maybe we could say "Obtain and/or install (...)"?

> * Generic documentation about how one would install an already issued certificate (e.g. with certonly) in their webserver. Does it take a --cert-name option? Or perhaps a -d option? I don't know. It's not documented.

The full output of `certbot --help install` on my system is:
```
usage: 

  certbot install --cert-path /path/to/fullchain.pem  --key-path /path/to/private-key [options]

options:
  -h, --help            show this help message and exit
  -c CONFIG_FILE, --config CONFIG_FILE
                        path to config file (default: /etc/letsencrypt/cli.ini and ~/.config/letsencrypt/cli.ini)

install:
  Options for modifying how a certificate is deployed

  --cert-path CERT_PATH
                        Path to where certificate is saved (with certonly --csr), installed from, or revoked (default: None)
  --key-path KEY_PATH   Path to private key for certificate installation or revocation (if account key is missing) (default: None)
  --fullchain-path FULLCHAIN_PATH
                        Accompanying path to a full certificate chain (certificate plus chain). (default: None)
  --chain-path CHAIN_PATH
                        Accompanying path to a certificate chain. (default: None)
  --apache              Obtain and install certificates using Apache (default: False)
  --nginx               Obtain and install certificates using Nginx (default: False)
```
Are you seeing something else? If not, there is an example there at the top with `--cert-path` and `--key-path`. I think the reason those flags are used in the example rather than `--cert-name` is `--cert-path` and `--key-path` should always work even if you did something like obtain a certificate with `--csr` while `--cert-name` or `--domains` would not. Maybe we could list multiple examples, but I personally think we should continue to document the most powerful/flexible option here.

**Comment by osirisinferi** [comment]
> For instance, `register` isn't documented there either. Should it be? Arguably, but the guide is already quite long after focusing on the more commonly used functionality. We could/should create more comprehensive documentation somewhere, but I'm personally not sure if relying on `--help` output for this functionality is too bad.

That's of course your prerogative :slightly_smiling_face: Although with a properly structured user guide I'm not seeing the issue with the length of the guide: as long as the user can find the information they need quickly and simply.

> Because the help text for these flags is generic. Maybe we could say "Obtain and/or install (...)"?

Generic text probably should be generically usable, so using "and/or" should probably be better methinks indeed.

> Are you seeing something else?

No, I'm seeing the same.

> I think the reason those flags are used in the example rather than `--cert-name` is `--cert-path` and `--key-path` should always work even if you did something like obtain a certificate with `--csr` while `--cert-name` or `--domains` would not. Maybe we could list multiple examples, but I personally think we should continue to document the most powerful/flexible option here.

In the `--help install` output I'd say to be relatively brief, but that's probably why I'm personally missing this subcommand in the User Guide.

> there is an example there at the top with `--cert-path` and `--key-path`.

The example is flawed, at least, it doesn't work on my system:

```
server ~ # certbot install --cert-path /etc/letsencrypt/live/le-test.ml/fullchain.pem --key-path /etc/letsencrypt/live/le-test.ml/privkey.pem 
Saving debug log to /var/log/letsencrypt/letsencrypt.log
(...)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: Apache Web Server plugin (apache)
2: Nginx Web Server plugin (nginx) [Misconfigured]
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 1

Which names would you like to activate HTTPS for?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(...)
36: le-test.ml
(...)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate numbers separated by commas and/or spaces, or leave input
blank to select all options shown (Enter 'c' to cancel): 36
Deploying certificate
Some rewrite rules copied from /etc/apache2/vhosts.d/vhosts/le-test.ml.conf were disabled in the vhost for your HTTPS site located at /etc/apache2/vhosts.d/vhosts/le-test.ml-le-ssl.conf because they have the potential to create redirection loops.
Could not install certificate
Please provide the --fullchain-path option pointing to your full chain file
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
server ~ # certbot install --fullchain-path /etc/letsencrypt/live/le-test.ml/fullchain.pem --key-path /etc/letsencrypt/live/le-test.ml/privkey.pem 
Saving debug log to /var/log/letsencrypt/letsencrypt.log
(...)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: Apache Web Server plugin (apache)
2: Nginx Web Server plugin (nginx) [Misconfigured]
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 1

Which certificate would you like to install?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(...)
17: le-test.ml
(...)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-21] then [enter] (press 'c' to cancel): 17
Deploying certificate
Successfully deployed certificate for le-test.ml to /etc/apache2/vhosts.d/vhosts/le-test.ml-le-ssl.conf
server ~ # 
```

Also, weird behaviour by the `apache` plugin: the list of FQDNs is suddenly completely different when using `--cert-path` or `--fullchain-path`, which I did not expect. It's both shorter the for the latter *and* all the hostnames are mostly different: 6 are identical, the former has 31 unique hostnames and the latter has 15 unique hostnames

**Comment by bmw** [comment]
> That's of course your prerogative 🙂 Although with a properly structured user guide I'm not seeing the issue with the length of the guide: as long as the user can find the information they need quickly and simply.

Someone on the Certbot team was previously working on a major rewrite of the user guide. I think that project may have stalled, but if you're potentially interested in helping, I can put you in touch.

> Generic text probably should be generically usable, so using "and/or" should probably be better methinks indeed.

I'd approve a PR changing this.

> The example doesn't work I'm afraid, at least, it doesn't on my system:

Ah nice catch. As you've probably figured out yourself by now, this should be `--fullchain-path` rather than `--cert-path`. I'd also approve a PR changing this.

> Also, weird behaviour by the `apache` plugin: the list of FQDNs is suddenly completely different when using `--cert-path` or `--fullchain-path`, which I did not expect. It's both shorter the for the latter *and* all the hostnames are mostly different: 6 are identical, the former has 31 unique hostnames and the latter has 15 unique hostnames.

Do you think this is something we should prioritize looking into? If so, do you mind opening another issue with more details on how to reproduce this?

**Comment by osirisinferi** [comment]
> Someone on the Certbot team was previously working on a major rewrite of the user guide. I think that project may have stalled, but if you're potentially interested in helping, I can put you in touch.

That's probably not going to fit in my schedule I'm afraid, I do realise rewriting the user guide probably takes a lot of time and effort. I'm also not sure if rewriting is really necessary, it's pretty good, but IMO it could be more complete.



> I'd approve a PR changing this.

> Ah nice catch. As you've probably figured out yourself by now, this should be `--fullchain-path` rather than `--cert-path`. I'd also approve a PR changing this.

Will do :)

> Do you think this is something we should prioritize looking into? If so, do you mind opening another issue with more details on how to reproduce this?

I haven't really started debugging that specific issue, I thought I'd just mention it, maybe it was already known. I'll try to debug when I find the time and open a new issue.
