### ISSUE TITLE
certbot revoke with parameter delete for single command

### ISSUE THREAD

**Issue by guilhermealano** [certbot/certbot#9380]
## My operating system is (include version):
Ubuntu 18.04 

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
pip

## I ran this command and it produced this output:
certbot revoke --cert-path /etc/letsencrypt/archive/siteexample123.com/cert1.pem

Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Would you like to delete the cert(s) you just revoked, along with all earlier
and later versions of the cert?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(Y)es (recommended)/(N)o: yes

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Deleted all files relating to certificate siteexample123.com.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Congratulations! You have successfully revoked the certificate that was located
at /etc/letsencrypt/archive/siteexample123.com/cert1.pem

## Certbot's behavior differed from what I expected because:
Hi, in the command ``certbot revoke`` is it possible to pass some parameter so that the certificate is deleted without it being manually confirmed in the CLI? Since when running the command, the question for deletion is returned. As per the above output.
``Would you like to delete the cert(s) you just revoked, along with all earlier and later versions of the cert?``
Something along the lines of ``certbot revoke --delete-cert --cert-path /etc/letsencrypt/archive/...``

**Comment by osirisinferi** [comment]
Adding the `--non-interactive` (or `-n`) option will make Certbot choose the default option, which is "Yes" in this case.

Return question: are you using Certbot to automatically revoke certs for some reason? If so, what's the reason? Usually, there is no need to revoke a certificate, so I'm wondering why this is bothering you.

**Comment by guilhermealano** [comment]
It's just that we have as a product, the whitelabel delivery to customers. And that if the customer cancels the contract before the certificate expires, it would revoke to guarantee. Or should I just delete it?
