### ISSUE TITLE
dnsmadeeasy vs aws api-auth options

### ISSUE THREAD

**Issue by sjackson0109** [certbot/certbot#9382]
This is technically a feature request.

If we compare the DNSMadeEasy plugin with the AWSRoute53 plugin. AWS accepts the API-KEY and API-SECRET as environment variables.
Comparison:
https://certbot-dns-dnsmadeeasy.readthedocs.io/en/stable/
```
- ...file can be provided interactively or using the --dns-dnsmadeeasy-credentials command-line argument [--dns-dnsmadeeasy-credentials]... containing dns_dnsmadeeasy_api_key  and dns_dnsmadeeasy_secret_key values.
```
https://certbot-dns-route53.readthedocs.io/en/stable/ shows:
```
- Using the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables.
- Using a credentials configuration file at the default location, ~/.aws/config.
- Using a credentials configuration file at a path supplied using the AWS_CONFIG_FILE environment variable.
```
The AWS config file is a true .INI file-type, as it contains the [default] header.
The DNsMadeEasy one does not contain any headers.

Looking only at non-interactive mechanisms... AWS provides 3x options, and DNSMadeEasy provides 1x.  Why is that? Surely all DNS provider plugins were created equally; no?

Assuming someone wants the task:
Can someone improve the DNSMadeEasy plugin to accept the following environment variables without the use of the `--dns-dnsmadeeasy-credentials` switch?
```
- dns_dnsmadeeasy_api_key
- dns_dnsmadeeasy_secret_key
```

Additionally if the ENV variables above don't exit in memory, and the `--dns-dnsmadeeasy-credentials` argument is not specified to cerbot; can the dnsmadeeasy plugin simply check and import from the following location: `~/.dnsmadeeasy/config'?

Thanks
Simon

**Comment by osirisinferi** [comment]
> Why is that? Surely all DNS provider plugins were created equally; no?

Nope.

The `certbot-dns-route53` uses the [`boto3` library](https://github.com/boto/boto3) as underlying library providing all the AWS connectivity, whereas the `certbot-dns-dnsmadeeasy` makes use of the [`dns-lexicon` library](https://github.com/AnalogJ/lexicon) to make the necessary DNS API calls.

Both of these underlying libraries have different kinds of configuration options and these differences are translated directly to how the user can configure the Certbot DNS plugins.
