### ISSUE TITLE
Request: Certbot to pass new ENV vars to the –manual-auth-hook and –manual-cleanup-hook

### ISSUE THREAD

**Issue by lordspace** [certbot/certbot#9383]
**Request: Pass two new environment variables to both hooks**
CERTBOT_WEBROOT_PATH
CERTBOT_MANUAL_EVENT=auth or cleanup

**Reasoning:**
I am calling certbot without specifying the preferred challenge. For this reason certbot attempts 
http challenge for staging.example.com and dns/txt for *.staging.example.com.
I am also using the same program for auth and clean up hooks.

**Current Workarounds**
1) use dns for both request => the drawback is that this requires 2 request. One to create and 1 to delete the record.
2) Pass DOCUMENT_ROOT environment variable before calling the certbot.

**Command**
certbot certonly \
--manual \
--test-cert \
--webroot-path /var/www/apps/qsandbox/staging.example.com/htdocs \
--manual-auth-hook /home/slavi/orbisius_dns_manager \
--manual-cleanup-hook /home/slavi/orbisius_dns_manager \
--email admin+apps+qsandbox+stg@example.com \
--rsa-key-size 4096 \
--agree-tos \
--manual-public-ip-logging-ok \
-d staging.example.com \
-d *.staging.example.com | tee -a ssl_tests.log

**Related**
https://community.letsencrypt.org/t/certbot-to-provide-webroot-path-to-the-manual-auth-hook-and-manual-cleanup-hook-and-event-if-its-auth-or-cleanup/183368

## My operating system is (include version):
lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc): 
apt install certbot

certbot --version
certbot 0.40.0

**Comment by bmw** [comment]
I don't think we're going to do this.

Certbot has a [plugin architecture](https://eff-certbot.readthedocs.io/en/stable/using.html#getting-certificates-and-choosing-plugins) and `--manual-*-hook` are manual plugin specific flags while `--webroot-path` is a webroot plugin specific flag. If you're not using the webroot plugin (which you're not), `--webroot-path` has no effect and I don't think we're going to change it to make it have effects outside of that plugin. Additionally, the only reason you can't tell whether it's auth or cleanup is you used identical scripts/commands for both hooks.

In general, the way I'd recommend fixing this is either through setting your own environment variable with the webroot before calling Certbot or modifying the hook commands you give to Certbot. You can do things like pass arguments to your script through something like `--manual-auth-hook '/home/slavi/orbisius_dns_manager auth'`. You could also pass the webroot path in this way.

I think other ways for you to deal with the auth vs. cleanup problem is to split the code into two scripts or make a symlink like `/home/slavi/orbisius_dns_manager_cleanup` to `/home/slavi/orbisius_dns_manager`, use the symlink in one of the Certbot hook commands, and then check the name that was used to invoke the program in your code.

This almost certainly isn't exactly what you wanted to hear, but I hope these suggestions help.

**Comment by lordspace** [comment]
Well, there is good discussion here & somebody provided a fix too
https://community.letsencrypt.org/t/certbot-to-provide-webroot-path-to-the-manual-auth-hook-and-manual-cleanup-hook-and-event-if-its-auth-or-cleanup/183368/18

**Comment by lordspace** [comment]
Thanks @bmw for the suggestion to pass an argument to the auth hook!
Do you know if I need to wait 30 seconds in that program before returning?
