### ISSUE TITLE
faild run generate cert on fedaro 36

### ISSUE THREAD

**Issue by fireinrain** [certbot/certbot#9384]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
os. Linux fedora 5.18.19-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Aug 21 15:52:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
python version 3.10

certbot version: python3-certbot-nginx-1.29.0-5.fc36.noarch.rpm

when i run :  sudo certbot --nginx --agree-tos --redirect --hsts --staple-ocsp --email sunrise@fireinrain.com -d local.fireinrain.com

get an error:
<img width="658" alt="image" src="https://user-images.githubusercontent.com/14249262/186770913-235ae101-0c44-4327-844b-716d25f7d220.png">

but actually  idna package has been installed on my machine.

here is:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/14249262/186771180-4736f190-481f-4851-adc2-f85e161e0601.png">

is this a bug? or something else

**Comment by alexzorin** [comment]
Mixing `pip`-installed and `dnf`/`yum`-installed packages has a pretty good risk of breaking things.

Maybe try:

    yum -y reinstall python3-idna

**Comment by fireinrain** [comment]
> certbot --nginx --agree-tos --redirect --hsts --staple-ocsp --email [sunrise@fireinrain.com](mailto:sunrise@fireinrain.com) -d local.fireinrain.com

Thanks, It works.

**Comment by fireinrain** [comment]
> Mixing `pip`-installed and `dnf`/`yum`-installed packages has a pretty good risk of breaking things.
> 
> Maybe try:
> 
> ```
> yum -y reinstall python3-idna
> ```

Thanks, It works.
