### ISSUE TITLE
How to add chain certificate to certbot?

### ISSUE THREAD

**Issue by ghandhikus** [certbot/certbot#9387]
Hello, I am struggling with certbot, we are generating the certificates automatically and we are looking for a way to add another `test_cert.pem` to the fullchain.pem. Adding `--chain-path test_cert.pem` does not seem to do anything. Is there any way in certbot to add custom certificates to full chain generation without doing it manually?

**Comment by alexzorin** [comment]
There is not, no. We are open to reasonable suggestions but off the top of my head, I can't think of a situation where this would be helpful to our users.

You could use a `--deploy-hook` to generate a further certificate and storing it elsewhere. I highly recommend not modifying the certificates that Certbot, as it could affect some functionality (like revocation checking).
