### ISSUE TITLE
Certbot on Freebsd

### ISSUE THREAD

**Issue by PythonLinks** [certbot/certbot#9394]
## My operating system is :
FreeBSD 13.0-RELEASE-p5

Your website says I should use the following command. 
 
pkg install py37-certbot

Sadly that does not exist. 

pkg install py39-certbot

exists and installs, but sadly it says

> This port installs the "standalone" client only, which does not use and
is not the certbot-auto bootstrap/wrapper script.

This page  also has  incorrect instructions about installing from ports. 

https://www.digitalocean.com/community/tutorial/how-to-secure-nginx-letsencrypt-freebsd

## I ran this command and it produced this output:

`cd /usr/ports/security/py-certbot
 make
===>   py38-certbot-1.21.0,1 depends on package: py38-acme>=1.21.0,1 - not found
===>  Staging for py38-acme-1.21.0,1
===>   py38-acme-1.21.0,1 depends on package: py38-cryptography>=1.2.3 - not found
===>   py38-acme-1.21.0,1 depends on package: py38-cryptography>=1.2.3 - not found
*** Error code 1

Stop.
make[2]: stopped in /usr/ports/security/py-acme
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/security/py-certbot
*** Error code 1

Stop.
make: stopped in /usr/ports/security/py-certbot
`

## Certbot's behavior differed from what I expected because:
I expected installation to work. 

I think the safe thing is to install certbot on Linux.   Sigh.

**Comment by PythonLinks** [comment]
Maybe the problem is not with certbot, but with the installation scripts. 

Since it is python, next up I am trying
`
python3 -m venv /path/to/new/virtual/environment
pip install certbot
`

Wish me luck.

**Comment by laffer1** [comment]
pkg install py38-certbot

**Comment by grahamperrin** [comment]
Side note: [python3 and python: 3.9 by default : freebsd](https://old.reddit.com/r/freebsd/comments/vm3tkh/python3_and_python_39_by_default/) (June 2022)

**Comment by PythonLinks** [comment]
Thank you. 
That works on one of my freebsd servers. 
On my upgraded server I have to do. 
pkg install py39-certbot

pip install also installed.  Just the ports tree has
 problems.

**Comment by bmw** [comment]
So `pkg install py39-certbot` works? If so, we can get our instructions on pages like https://certbot.eff.org/instructions?ws=webproduct&os=freebsd updated. (Additionally, it looks like [our Apache and Nginx plugins are now packaged on FreeBSD](https://www.freebsd.org/cgi/ports.cgi?query=certbot&stype=all) so we can update our instructions for those webservers to use those plugins rather than standalone/webroot.)

The text

> This port installs the "standalone" client only, which does not use and
is not the certbot-auto bootstrap/wrapper script.

is something that must have been added by the FreeBSD package maintainers. I think it's also a bit misleading because we killed certbot-auto a little over a year ago and certbot-auto's purpose was just to automate the process of getting Certbot installed on your system (and keep it up-to-date) which FreeBSD's package/ports system handles for you.

Does installing from ports not work on an updated system though? If not, this should get reported to the FreeBSD package maintainers (potentially as well as encouraging them to remove the note about certbot-auto).

**Comment by PythonLinks** [comment]
So 

pkg install py39-certbot

installed something on one of my servers and did not crash. 

pkg install py38-certbot

did the same on the other server.  I have not yet run them to see if they work . 

I am just jumping back and forth between caddy and nginx.  
Right now, I am making progress with caddy.  The problem with nginx and certbot, 
is that they have to install a lot of crud in each file for each domain configuration.

Caddy does that all automatically.   DRY, do not repeat yourself. 

The problem with caddy, is that the cache handler is not included in the main distribution, and the documentation is not very good.  It took me quite a while to figure out how to not cache results from logged in users. 

On the other hand Caddy Cache has some great features.  NGINX is more mature.  GoLand has more upside. 

I am sorry if that does not answer your question.  I hope it helps.  If I end up ditching caddy and returning to NGINX, I will update this thread.

**Comment by PythonLinks** [comment]
And yes installing from ports did install something, but that message scared me off, and I do not know if it would run correctly.

**Comment by laffer1** [comment]
@bmw You should update the FreeBSD instructions since the default version of python has changed. 

I've been using older package versions on nginx with a FreeBSD 12.3 install without issues 

For nginx: 
py37-certbot-nginx

**Comment by PythonLinks** [comment]
##  py37-certbot-nginx did not work. 
 
 pkg install py37-certbot-nginx
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
pkg: No packages available to install matching 'py37-certbot-nginx' have been found in the repositories


## py39-certbot 

certbot
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Certbot doesn't know how to automatically configure the web server on this system. However, it can still get a certificate for you. Please run "certbot certonly" to do so. You'll need to manually configure your web server to use the resulting certificate.

# Reddit
Let me mention this reddit thread.  Where one person claims it is working. 
https://www.reddit.com/r/freebsd/comments/x3fw1a/lets_encrypt_certbot_not_working_on_freebsd/

They also recommend dehydrate and acme.sh

I probably could get it to work, but there is too much uncertainty in what to do.  Easiest is to leave my web servers on linux, and run my application servers on Freebsd.  It was quite painless on Linux.  Sigh.

**Comment by grahamperrin** [comment]
> pkg: No packages available to install matching 'py37-certbot-nginx' have been found in the repositories

This is not a certbot issue. 

<https://www.freshports.org/security/py-certbot-nginx/#packages> py37-certbot-nginx is currently not packaged for `FreeBSD:13:amd64`. 

NB <https://github.com/certbot/certbot/issues/9394#issuecomment-1234927023> above. <http://beefy14.nyi.freebsd.org/build.html?mastername=131amd64-quarterly&build=8327a5f1bca6> (running), py39-certbot-nginx is currently queued. 

> FreeBSD 13.0-RELEASE-p5

End of life.

**Comment by bmw** [comment]
@PythonLinks, assuming your FreeBSD server is running nginx, did you install `py39-certbot-nginx`?

I'll get our FreeBSD instructions at https://certbot.eff.org/instructions updated to list the `py39` packages as well as recommending the Apache and Nginx plugins now that they've been packaged on FreeBSD.

**Comment by PythonLinks** [comment]
Repeating from my original post. 

> pkg install py39-certbot

>exists and installs, but sadly it says

>" This port installs the "standalone" client only, which does not use and  is not the certbot-auto bootstrap/wrapper script"

**Comment by bmw** [comment]
To elaborate on my last post, if your FreeBSD server is running nginx, I recommend also running `pkg install py39-certbot-nginx`. That package contains Certbot's integration with nginx.

**Comment by PythonLinks** [comment]
> On 7 Sep 2022, at 19:06, Brad Warren ***@***.***> wrote:
> 
> py39-certbot-nginx.

Thank you for the repost.  My eyes saw py39-certbot, and the rest of the line did not reach my brain. 

I do not want to touch anything the day before I leave for a conference, but I will take a closer look at it when I return. 

Thank you hugely. 

Christopher Lozinski
***@***.***

**Comment by bmw** [comment]
FreeBSD aficionados, is it possible and advisable to update our instructions to remove the specific Python version? Like, is there a command that's sane which looks something like `pkg install py-certbot` that'd use whatever version of Python FreeBSD currently defaults to?

I'm asking because this isn't the first bug report we've gotten about our docs here being out of date so I think it'd be nice to write them in away to avoid the problem in the future.

**Comment by grahamperrin** [comment]
> our instructions

Where? URL please.

**Comment by grahamperrin** [comment]
See the **pkg-install(8)** _SYNOPSIS_ at <https://www.freebsd.org/cgi/man.cgi?query=pkg-install&sektion=8&manpath=Ports#SYNOPSIS>.

<https://certbot.eff.org/instructions?ws=apache&os=freebsd> for example, 

> `pkg install py37-certbot`

-- becomes: 

> `pkg install security/py-certbot`

FreshPorts is our friend. <https://www.freshports.org/security/py-certbot/#add> offers the two examples that fit the synopsis. 

A demonstration, _not_ installing: 

```text
root@mowa219-gjp4-8570p-freebsd:~ # pkg install -n security/py-certbot
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
Updating poudriere repository catalogue...
poudriere repository is up to date.
All repositories are up to date.
The following 10 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        py39-acme: 1.29.0,1 [FreeBSD]
        py39-certbot: 1.29.0,1 [FreeBSD]
        py39-configobj: 5.0.6_1 [FreeBSD]
        py39-josepy: 1.13.0 [FreeBSD]
        py39-parsedatetime: 2.6 [FreeBSD]
        py39-pyrfc3339: 1.1 [FreeBSD]
        py39-requests-toolbelt: 0.9.1_1 [FreeBSD]
        py39-zope.component: 4.2.2 [FreeBSD]
        py39-zope.event: 4.1.0 [FreeBSD]
        py39-zope.interface: 5.3.0 [FreeBSD]

Number of packages to be installed: 10

The process will require 7 MiB more space.
1 MiB to be downloaded.
root@mowa219-gjp4-8570p-freebsd:~ # 
```

**Comment by grahamperrin** [comment]
> _SYNOPSIS_

FreeBSD bug [266406 – Superfluous underscores in, for example, synopses](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=266406)

**Comment by bmw** [comment]
Perfect. Thanks so much grahamperrin.

**Comment by PythonLinks** [comment]
THAT WORKED
But the docs could be improved (to put it politely)

It was recommended that I do 
pkg install py39-certbot-nginx

I fired up a new freebsd server.  Insalled what was needed then installed and ran the above command. 

>The client requires the ability to bind on TCP port 80 or 443 (depending
on the --preferred-challenges option used). If a server is running on that
port, it will need to be temporarily stopped so that the standalone server
can listen on that port to complete the challenge authentication process.



Then it says: 

>In order to automatically renew the certificates, add this line to
/etc/periodic.conf:

    weekly_certbot_enable="YES"

So it is not clear to me if is a stand alone server, which requires stopping NGINX, or it can run weekly.  

Turns out that file is in 
/etc/defaults/periodic.conf

I did add that line to that, but I suspect I have to do something to have the OS reload the file. 

Also I had a hard time finding and running the certbt. 

find / -name py39-certbot-nginx

find / -name certbot-nginx

neither yielded anything.

find / -name certbot

The last one worked, and certbot seems to have done the right thing. 

Well at least I finally seem to have gotten the basics working. 
Now let me see if I can configure it for me needs. 

Using Caddy on FreeBSD was worse.  

Thank you for all of the help.

**Comment by utkonos** [comment]
@grahamperrin You are exactly correct. I ran into this problem following the instructions on the website here:

https://certbot.eff.org/instructions?ws=other&os=freebsd

Both Freshports and your comment here are absolutely the correct answer. I have opened an issue on the website repo so that the documentation on the link above can be updated.

https://github.com/certbot/website/issues/762

**Comment by bmw** [comment]
This has been fixed.
