### ISSUE TITLE
Fix  tools/snap/generate_dnsplugins_snapcraft.sh for some users

### ISSUE THREAD

**Issue by casualscripter** [certbot/certbot#9397]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):

Ubuntu 20.04.5 LTS (Focal Fossa) and/or macOS 12.5.1 (Monterey)

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

snap (1.29.0)

## I ran this command and it produced this output:

tools/snap/generate_dnsplugins_snapcraft.sh certbot-dns-desec/

That generated certbot-dns-desec/snap/snapcraft.yaml (excerpt) with multiple lines:

```
summary:     long_description = f.read()
deSEC DNS Authenticator plugin for Certbot
    long_description=long_description,
    long_description_content_type="text/markdown",
description:     long_description = f.read()
deSEC DNS Authenticator plugin for Certbot
    long_description=long_description,
    long_description_content_type="text/markdown",
```

## Certbot's behavior differed from what I expected because:

certbot-dns-desec/snap/snapcraft.yaml (excerpt) should only have two lines:

```
summary: deSEC DNS Authenticator plugin for Certbot
description: deSEC DNS Authenticator plugin for Certbot
```

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

- (is not part of running certbot)

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

- (is not part of running certbot)

## What is the problem?

There is no need for two interconneced (pipe) processes. (optional improvement)

The regular expression in the grep part is not strict enough in some cases (presence of "long_description").

sed does not seem to support perl regular expressions ("\s").

Some Python developers prefer single quotes over double qoutes. Some even go so far as to adapt generated templates (eg. setup.py).

# What's next?

A pull request is in progress...

**Comment by bmw** [comment]
Fixed in #9398.
