### ISSUE TITLE
Log files in /tmp do not have "certbot" or similar in filename

### ISSUE THREAD

**Issue by WesleyAC** [certbot/certbot#9405]
## My operating system is (include version):

Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

OS package manager (apt)

## I ran this command and it produced this output:

N/A

## Certbot's behavior differed from what I expected because:

Certbot created approximately 264,744 log files in `/tmp/` from failing to get a lock (I think this is due to the specific way I run certbot in a cronjob). I asked in #9173 and was told this was expected behaviour, and I should delete them if I don't want them. However, since the files are simply named `/tmp/tmpXXXXXXXX` (where the Xs are random characters), it's impossible to delete just the certbot crash logs just by name — I need to either blow up every file starting with `/tmp/tmp*`, or write a script to grep for some specific string.

Instead, they should be named something like `/tmp/certbot_error_XXXXXXXX`.

## Here is a Certbot log showing the issue (if available):

N/A

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

N/A

**Comment by bmw** [comment]
If there's a way to do this safely with minimal changes to our code, I'd accept a PR for this.
