### ISSUE TITLE
certbot-nginx Expected string_end, found 'http'

### ISSUE THREAD

**Issue by uriesk** [certbot/certbot#9416]
If certbot-nginx parser encounters comments in a multiline log_format definition, it will throw an `Expected string_end, found 'http'` error.

https://community.letsencrypt.org/t/certbot-nginx-expected-string-end-found-http/185067

like this:
```
	log_format  main  '$remote_addr > $remote_user [$time_local] "$request" '
            '$host $http_host '
	    #'$status $body_bytes_sent '
	    # 'request_time=$request_time '
	    # 'upstream_response_time=$upstream_response_time '
	    '"$http_user_agent"';
	log_format  error  '$remote_addr > $binary_remote_addr > $remote_user [$time_local] "$request" '
	    '$status $body_bytes_sent '
	    '"$http_user_agent"';
```

**Comment by alexzorin** [comment]
Thank you for finding this and taking the time to report this.

I think this is a fairly uncommon case and it is not likely we will prioritize fixing this today. If we receive more reports, that may change.

**Comment by TimB87** [comment]
Still an issue
