### ISSUE TITLE
certbot-dns-rfc2136:  Feature request of variable propagation delay

### ISSUE THREAD

**Issue by rcarsey1** [certbot/certbot#9429]
I -think- this is a feature request, as I do not see a way to currently do this.

I use the RFC2136 plugin to publish a TXT record to my (hidden) master external DNS server.  I must wait until the slave servers pick up the new record.. which is sometimes immediate, but could be up to a couple hours.  I do not have control over that because I use a hosting company.   The only way I can handle this is to use --dns-rfc2136-propagation-seconds xxx;  and choose a delay that is absurdly long.

Ideally, I'd like the plugin to have some additional parameters:

--dns-rfc2136-slave-server-check _hostname_ 
--dns-rfc2136-slave-server-interval _secondsA_  
--dns-rfc2136-slave-server-timeout _secondsB_  

Where, once the TXT record is published, we query _hostname_ every _secondsA_ for a maximum of _secondsB_  and wait until either the specified dns server returns the correct txt record (then, we can tell the ACME server to go and check the record) or until we timeout (in which case, we should delete the TXT record and quit).

In this way, we only need to wait the necessary amount of time before asking the ACME server to check the published TXT record.

**Comment by alexzorin** [comment]
Can you set your master up with `NOTIFY` to trigger an immediate zone transfer on the slaves? I think this is the usual way to deal with this problem. 

That being the case, I don't think it's likely that we would prioritize this as a feature. It is a bit of a half measure as well;  seems like it would be more robust and useful if it checked all the nameservers.

**Comment by rcarsey1** [comment]
Of course.  They are NOTIFYd (to a special IP address, not the active slave servers) as soon as the zone modification occurs, and they initiate a zone transfer almost immediately.  However, it seems to be some time until they push the new zone out to their operational slave servers.  Without naming names, its a large operation that only handles DNS...and they make it easy for customers, ahem.  so I'm sure they are doing this to reduce load on their farm.

I agree that its a half measure; ideally, we'd need to check ALL the published nameservers for the zone.  If memory serves, I believe the nameserver we sent the add/update to must also be queryable.   We can ask for the NS records and check each, up to a specified timeout (at which case we can report that nameserver xyz didn't have the correct record and timeout was reached).
