### ISSUE TITLE
Add Python 3.11 support

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#9441]
[Python 3.11 is out](https://www.python.org/downloads/release/python-3110/) and I think we should support it. People on faster moving OSes will try to run Certbot on Python 3.11 if they haven't already.

I described the main difficulty in resolving this in [Mattermost](https://opensource.eff.org/eff-open-source/pl/wn7cixjqff8p9kydz3cceibsiy) where I said:

> Our pinned version of pylint doesn't work with Python 3.11. Upgrading pylint spews a ton of errors [like normal](https://opensource.eff.org/eff-open-source/pl/3fqsi7zjqifhfb6y9xiipwz7zy). I've been poking around with black and flake8 this morning, but making these large code changes while maintaining both master and 2.0.x feels a little tricky to me.

We could block adding Python 3.11 support on https://github.com/certbot/certbot/issues/8818, however, that's a ton of work and like I said feels especially icky due to us maintaining two branches right now.

Alternatively, to fix pylint, we need to update our pinnings [here](https://github.com/certbot/certbot/blob/7ab82b6f64353349bcc1a1cc4b0c6b45d08965d8/tools/pinning/current/pyproject.toml#L9) to say we only want to support Python>=3.7.2. This is because all newer versions of pylint do this (which you can see [here](https://github.com/PyCQA/pylint/blob/v2.14.0/setup.cfg#L57) for pylint 2.14.0 which is the next oldest version of pylint) and poetry complains that it's impossible to upgrade pylint and satisfy our dependency for Python >= 3.7.0.

If we go this route, we could also go through the process of deprecating and dropping support for Python<3.7.2 or Python<3.8 (although [Python 3.7 is supported by the Python team until July 2023](https://devguide.python.org/versions/)) in Certbot itself like we did for Python 3.6 at https://github.com/certbot/certbot/pull/9160 and https://github.com/certbot/certbot/pull/9216 respectively, but I don't think it's worth it. pylint is only an optionally required test dependency of ours and I think we can realistically get by saying that we only support Python>=3.7.2 when generating our pinnings and still claim support for Python>=3.7.0 in Certbot. We're certainly not in the practice of testing against all patch versions of Python and have instead just focused on the major and minor version number.

What do people think? I'd like to get a +1 from someone before we start implementing something here.

**Comment by alexzorin** [comment]
>Alternatively, to fix pylint, we need to update our pinnings [here](https://github.com/certbot/certbot/blob/7ab82b6f64353349bcc1a1cc4b0c6b45d08965d8/tools/pinning/current/pyproject.toml#L9) to say we only want to support Python>=3.7.2

What would be the difference between doing this and making `pylint` a [Python restricted dependency](https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies)? Would doing the latter allow repinning to work on Python <3.7.2, with the exclusion of `pylint`, which is optional anyway?

Overall, I think this plan sounds good. Debian 10 has Python 3.7.3 and older distros have Python 3.6 or older. My understanding of our use of Poetry is that doesn't affect anybody downstream (like packagers). I can't see any problems.

**Comment by alexzorin** [comment]
Completed via https://github.com/certbot/certbot/pull/9471.
