### ISSUE TITLE
nginx: repeatedly running the installer inserts blank lines

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#9445]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 22.04

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
snap, 1.31.0

## I ran this command and it produced this output:
    certbot install --nginx

## Certbot's behavior differed from what I expected because:
Certbot should not insert new blank lines in the SSL `server` block upon repeatedly running the installer. Eventually you end up with:

```nginx
server {
        server_name example.com;

        location / {
                return 403;
        }

    listen 443 ssl http2; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot




}
```

It's worse if you have one config file where you have multiple virtual hosts, so the nginx installer puts the file through a lot of parse/save cycles.

**Comment by pcarioufr** [comment]
FWIW, I replicate the issue within `nginx:1.23.2-alpine`

Dockerfile
'''
nginx:1.23.2-alpine

[some stuff]

# Install Certbot
RUN apk add certbot certbot-nginx
'''

Repeated certbot command in the container
'''
certbot --nginx -n --agree-tos -m ${CERT_EMAIL} --rsa-key-size 4096 --redirect -d ${APP_HOST}
'''
