### ISSUE TITLE
Windows renew task created for groups "Administrators" results in multiple concurrent executions.

### ISSUE THREAD

**Issue by ams-tschoening** [certbot/certbot#9446]
## My operating system is (include version):

* Windows 10 22H2, Build 19045.2130
* Windows Server 2019 Version 1809, Build 17763.3406

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

Using the official Windows installer:

* https://dl.eff.org/certbot-beta-installer-win_amd64.exe
* https://certbot.eff.org/instructions?ws=other&os=windows

## Certbot's behavior differed from what I expected because:

The automatically created renew task in the Windows task planner is created for the group `Administrators`:

![Screenshot](https://user-images.githubusercontent.com/6223655/198521103-d7f577bf-16d6-4a7a-93b1-a5004a99a530.png)

While that is not too much of a problem on my client Windows, as there's only one admin used, that's different on some server where I deployed Certbot. That is part of some domain and multiple domain users are members of the server-local group `Administrators`. All of those admins login to the server using RDP possibly concurrently and don't necessarily logoff when their work has finished, but only close the RDP window. So it might be that multiple RDP sessions are open at any given time.

What I have recognized during testing the renewal process by manually triggering the created task is that Certbot will be executed for each and every individual admin session currently logged in using RDP. At my session I even visibly saw some created shell during renewing. Though, certbot isn't designed to run concurrently and instead logs warning for the other admin users. The following is the error printed for all but one currently logged in admin user, simply the path changes per user:

```
Another instance of Certbot is already running.
Ask for help or search for solutions at https://community.letsencrypt.org/. See the logfile
C:\Users\USER1\AppData\Local\Temp\tmpwy2okd0d\log or re-run Certbot with -v for more details.
```

This doesn't happen when the task is executed for one individual member user of the `Administrators` group only. Not sure what the reason for using this group is, possibly because some versions of Windows disable the default `Administrator` account. But it might be better to simply create a distinct renewal user for the task being member of the `Administrators` group. Some other apps like OpenVPN, VMware Workstation etc. simply create users and groups during their install process for various purposes as well. I did create such a user `certbot_renew` manually and the task seems to work fine this way, executed only once and stuff.

**Comment by bmw** [comment]
Thanks so much for the detailed bug report.

We should fix this to avoid unnecessary work and misleading output from Certbot.
