### ISSUE TITLE
Switch from probot/stale to actions/stale

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#9456]
Our stale bot seems to be broken and deprecated. See https://github.com/probot/stale/issues/385. I think we should uninstall our current stale bot and set up https://github.com/marketplace/actions/close-stale-issues.

Our current stale bot config can be found at https://github.com/certbot/certbot/blob/master/.github/stale.yml.

**Comment by bmw** [comment]
I wanted to check in on the status of things here. It looks like we're still setting `debug-only`: https://github.com/certbot/certbot/blob/dc07dfd07b2c137630b931cc10f69ec0c41c1150/.github/workflows/stale.yml#L14-L15

Do we need to do anything before we remove that? I opened a PR to fix the only thing that looked strange to me in the [run history](https://github.com/certbot/certbot/actions) at https://github.com/certbot/certbot/pull/9577.

**Comment by wgreenberg** [comment]
ah yes, i'd left the debug flag on while debugging why we weren't seeing any issues in the dry-run output, but that seems to be fixed w/ the operations # change. i think we're probably good to remove the dry-run flag now!
