### ISSUE TITLE
Apache tests crash on Debian unstable

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#9481]
Reported by @hlieberman [in Mattermost](https://opensource.eff.org/eff-open-source/pl/cqzhdazg97raxqbj3atid86wpy).

Initially I thought this might have something to do with how we replaced [`distutils.version.LooseVersion`](https://github.com/python/cpython/blob/v3.10.0/Lib/distutils/version.py#L205-L347) with [our own implementation](https://github.com/certbot/certbot/pull/9077/files#diff-2d6ee57700dc1f66f9f464b21ba4a9b3892ac453cd1964bb97fef6f8c59d7826R645).

But, the crash would have happened even if we were still using the `distutils` module:

```
>>> version.LooseVersion("bookworm/sid") > version.LooseVersion("9")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/venv/lib/python3.11/site-packages/setuptools/_distutils/version.py", line 84, in __gt__
    c = self._cmp(other)
        ^^^^^^^^^^^^^^^^
  File "/private/tmp/venv/lib/python3.11/site-packages/setuptools/_distutils/version.py", line 352, in _cmp
    if self.version < other.version:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'str' and 'int'
  ```
  
The unsafe comparison was introducing in [this recent change](https://github.com/certbot/certbot/pull/9402/files#diff-d73d138390e77dafcc6b579a463523bf493d9763c2e2d2f005f7ad63612acedeR64) which was fixing our RHEL9 support:

https://github.com/certbot/certbot/blob/c78503f21d6b631265a18f3b55f06f1ac448aec5/certbot-apache/certbot_apache/_internal/override_centos.py#L61-L62

We could probably fix this in a simple way by preventing the unsafe comparison to begin with:

```patch
diff --git a/certbot-apache/certbot_apache/_internal/override_centos.py b/certbot-apache/certbot_apache/_internal/override_centos.py
index de5c31268..737e6d26d 100644
--- a/certbot-apache/certbot_apache/_internal/override_centos.py
+++ b/certbot-apache/certbot_apache/_internal/override_centos.py
@@ -58,8 +58,7 @@ class CentOSConfigurator(configurator.ApacheConfigurator):
             "rhel", "redhatenterpriseserver", "red hat enterprise linux server",
             "scientific", "scientific linux",
         ]
-        at_least_v9 = util.parse_loose_version(os_version) >= util.parse_loose_version('9')
-        return rhel_derived and at_least_v9
+        return rhel_derived and util.parse_loose_version(os_version) >= util.parse_loose_version('9')

     def _override_cmds(self) -> None:
         super()._override_cmds()
```

but I wonder if we shouldn't make `parse_loose_version` return a class instead with a type-safe comparison function on it instead, to prevent this issue recurring in the future. Backwards-compatibility is a pain though.

Also, why didn't `mypy` save us here 😠 ?

**Comment by hlieberman** [comment]
As discussed in Mattermost, [the proposed patch above](https://salsa.debian.org/letsencrypt-team/certbot/certbot-apache/-/commit/959c34b85d0be2a33a7f659e154d4b8341ff65e5) has been included into the python3-certbot-apache release, version 2.0.0-1.

**Comment by bmw** [comment]
I dug into mypy here and asked about this upstream at https://github.com/python/mypy/issues/14227.
