### ISSUE TITLE
enhacement - support DNS Provider - Flexible Engine Cloud

### ISSUE THREAD

**Issue by flyflyinit** [certbot/certbot#9483]
Hello,

Flexible Engine is a global France public cloud solution based on OpenStack technology. It is aimed at European companies of all sizes, especially those with an international presence.
https://www.orange-business.com/en/products/flexible-engine

I think it's a good idea to have a FlexibleEngine DNS provider in your catalog, as the cloud platform is highly growing and there are a lot of clients out there, looking for CERTBOT DNS FlexibleEngine Support.

I have already worked on the FlexibleEngine platform. please let me know if you need any help.

Thank You.

**Comment by alexzorin** [comment]
The Certbot team isn't currently accepting or writing any new DNS plugins.

You are welcome to [write and publish your own](https://eff-certbot.readthedocs.io/en/stable/contributing.html#writing-your-own-plugin) and optionally include it on our list of [third-party plugins](https://eff-certbot.readthedocs.io/en/stable/using.html#third-party-plugins).
