### ISSUE TITLE
Renew process failed for asterix cert if directory contains a similar file/directory

### ISSUE THREAD

**Issue by airween** [certbot/certbot#9487]
## My operating system is (include version):

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
```
apt install certbot
...
dpkg -l certbot
...
ii  certbot        1.12.0-2     all          automatically configure HTTPS using Let's Encrypt
```

## I ran this command and it produced this output:
```
# cd /path/to/vhosts
# ls -1
www.mydomain.com

# certbot certonly --debug -d *.mydomain.com -d mydomain.com --manual --server https://acme-v02.api.letsencrypt.org/directory
usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: unrecognized arguments: www.mydomain.com
```

## Certbot's behavior differed from what I expected because:
If I step into the directory where there is a file/directory with name which matches the requested domain, the renew process has failed. If I change the working directory, it works.

This is not a critical behavior, but may be it is good to know...

**Comment by alexzorin** [comment]
Yes, wildcard globbing in shells is unfortunate. By the time Certbot runs, it's too late, because the shell has already substituted the wildcard.

If there are any places in our documentation where we are not quoting wildcard arguments, like `-d "*.example.com"`, then we should update those.

Otherwise, I don't think there's a lot we can do about it.
