### ISSUE TITLE
Deprecate certbot.util.parse_loose_version

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#9489]
We use this function for comparing version strings but it's not type safe in a way that mypy doesn't currently check for. See https://github.com/certbot/certbot/issues/9481.

Because of this, I personally think we should completely stop using this function, deprecate it, and switch to a TBD safer alternative.

**Comment by zoracon** [comment]
Considering the type safety work that was done https://github.com/certbot/certbot/pull/9177, I am closing for now. We can re-open if that assumption is not correct.
