### ISSUE TITLE
Fix josepy GitHub actions warnings

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#9499]
This issue is for https://github.com/certbot/josepy but I'm creating it here for visibility.

While working on https://github.com/certbot/josepy/pull/149, I noticed our [CI setup is triggering a lot of warnings from GitHub Actions](https://github.com/certbot/josepy/actions/runs/3640586621). I think we should fix this before things break.

**Comment by wgreenberg** [comment]
These all seemed to stem from using old versions of various Github Actions. Here's a PR that updates them: https://github.com/certbot/josepy/pull/151

**Comment by ohemorange** [comment]
Closed in https://github.com/certbot/josepy/pull/151
