### ISSUE TITLE
Certbot snap install on CentOS 7 segfaults

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#9503]
This has been reported a couple of times on the forums already.

	[root@armor-client ~]# snap install --classic certbot
	error: cannot perform the following tasks:
	- Run configure hook of "certbot" snap if present (run hook "configure":
	-----
	fatal error: unexpected signal during runtime execution
	[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

	runtime stack:
	runtime.throw({0x7257cd, 0x0})
			/usr/lib/golang/src/runtime/panic.go:1198 +0x71 fp=0x7fffdbc5b340 sp=0x7fffdbc5b310 pc=0x435291
	runtime.sigpanic()
			/usr/lib/golang/src/runtime/signal_unix.go:719 +0x396 fp=0x7fffdbc5b390 sp=0x7fffdbc5b340 pc=0x44aa16

	goroutine 1 [syscall, locked to thread]:
	runtime.cgocall(0x5e9a70, 0xc0000a76c0)
			/usr/lib/golang/src/runtime/cgocall.go:156 +0x5c fp=0xc0000a7698 sp=0xc0000a7660 pc=0x40551c
	crypto/internal/boring._Cfunc__goboringcrypto_DLOPEN_OPENSSL()
			_cgo_gotypes.go:603 +0x49 fp=0xc0000a76c0 sp=0xc0000a7698 pc=0x5366c9
	crypto/internal/boring.init.0()
			/usr/lib/golang/src/crypto/internal/boring/boring.go:46 +0x45 fp=0xc0000a76f8 sp=0xc0000a76c0 pc=0x537445
	runtime.doInit(0xad84a0)
			/usr/lib/golang/src/runtime/proc.go:6498 +0x123 fp=0xc0000a7830 sp=0xc0000a76f8 pc=0x4449a3
	runtime.doInit(0xad61a0)
			/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0000a7968 sp=0xc0000a7830 pc=0x4448f1
	runtime.doInit(0xad9280)
			/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0000a7aa0 sp=0xc0000a7968 pc=0x4448f1
	runtime.doInit(0xad8260)
			/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0000a7bd8 sp=0xc0000a7aa0 pc=0x4448f1
	runtime.doInit(0xad9bc0)
			/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0000a7d10 sp=0xc0000a7bd8 pc=0x4448f1
	runtime.doInit(0xad7220)
			/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0000a7e48 sp=0xc0000a7d10 pc=0x4448f1
	runtime.doInit(0xad7fe0)
			/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0000a7f80 sp=0xc0000a7e48 pc=0x4448f1
	runtime.main()
			/usr/lib/golang/src/runtime/proc.go:238 +0x1e6 fp=0xc0000a7fe0 sp=0xc0000a7f80 pc=0x437926
	runtime.goexit()
			/usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000a7fe8 sp=0xc0000a7fe0 pc=0x464361

	goroutine 2 [force gc (idle)]:
	runtime.gopark(0x0, 0x0, 0x0, 0x0, 0x0)
			/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000032fb0 sp=0xc000032f90 pc=0x437d36
	runtime.goparkunlock(...)
			/usr/lib/golang/src/runtime/proc.go:372
	runtime.forcegchelper()
			/usr/lib/golang/src/runtime/proc.go:306 +0xad fp=0xc000032fe0 sp=0xc000032fb0 pc=0x437bcd
	runtime.goexit()
			/usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000032fe8 sp=0xc000032fe0 pc=0x464361
	created by runtime.init.8
			/usr/lib/golang/src/runtime/proc.go:294 +0x25

	goroutine 3 [GC sweep wait]:
	runtime.gopark(0x0, 0x0, 0x0, 0x0, 0x0)
			/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc0000337b0 sp=0xc000033790 pc=0x437d36
	runtime.goparkunlock(...)
			/usr/lib/golang/src/runtime/proc.go:372
	runtime.bgsweep()
			/usr/lib/golang/src/runtime/mgcsweep.go:163 +0x88 fp=0xc0000337e0 sp=0xc0000337b0 pc=0x4243a8
	runtime.goexit()
			/usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000337e8 sp=0xc0000337e0 pc=0x464361
	created by runtime.gcenable
			/usr/lib/golang/src/runtime/mgc.go:181 +0x55

	goroutine 4 [GC scavenge wait]:
	runtime.gopark(0x0, 0x0, 0x0, 0x0, 0x0)
			/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000033f80 sp=0xc000033f60 pc=0x437d36
	runtime.goparkunlock(...)
			/usr/lib/golang/src/runtime/proc.go:372
	runtime.bgscavenge()
			/usr/lib/golang/src/runtime/mgcscavenge.go:265 +0xcd fp=0xc000033fe0 sp=0xc000033f80 pc=0x4224ad
	runtime.goexit()
			/usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000033fe8 sp=0xc000033fe0 pc=0x464361
	created by runtime.gcenable
			/usr/lib/golang/src/runtime/mgc.go:182 +0x65

	goroutine 5 [finalizer wait]:
	runtime.gopark(0xaec640, 0xc000032770, 0xf1, 0x48, 0xad75e0)
			/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000032630 sp=0xc000032610 pc=0x437d36
	runtime.goparkunlock(...)
			/usr/lib/golang/src/runtime/proc.go:372
	runtime.runfinq()
			/usr/lib/golang/src/runtime/mfinal.go:177 +0xb3 fp=0xc0000327e0 sp=0xc000032630 pc=0x419f33
	runtime.goexit()
			/usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000327e8 sp=0xc0000327e0 pc=0x464361
	created by runtime.createfing
			/usr/lib/golang/src/runtime/mfinal.go:157 +0x45
	-----)
	[root@armor-client ~]# ^C
	[root@armor-client ~]# snap version
	snap    2.57.6-1.el7
	snapd   2.57.6-1.el7
	series  16
	centos  7
	kernel  3.10.0-1160.45.1.el7.x86_64
	[root@armor-client ~]# rpm -q snapd
	snapd-2.57.6-1.el7.x86_64

**Comment by alexzorin** [comment]
Posted to snapcraft: https://forum.snapcraft.io/t/snap-exec-segfaults-on-centos-7-2-57-6-1-el7/33030

**Comment by ShaneKing** [comment]
same too, mark.

**Comment by chris43123** [comment]
Got the same error two days ago.

**Comment by ergotone** [comment]
Same here, just did requested SNAP updates, and now certbot crashes on 'certbot certificates' ( or any other command...)
(our live CentOS7 server running certbot with 20+ domains)

**Comment by plao** [comment]
Same issue for me, same versions also:

[root@mail ~]# snap version
snap    2.57.6-1.el7
snapd   2.57.6-1.el7
series  16
centos  7
kernel  3.10.0-1160.80.1.el7.x86_64

[root@mail ~]# rpm -q snapd
snapd-2.57.6-1.el7.x86_64

[root@mail ~]# cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)

How to fix this, please?

Thx in advance!

**Comment by ergotone** [comment]
Checked the yum history details...

Packages Altered:
    Updated snap-confine-2.55.3-1.el7.x86_64  @epel
    Update               2.57.6-1.el7.x86_64  @epel
    Updated snapd-2.55.3-1.el7.x86_64         @epel
    Update        2.57.6-1.el7.x86_64         @epel
    Updated snapd-selinux-2.55.3-1.el7.noarch @epel
    Update                2.57.6-1.el7.noarch @epel
history info

But an explicit yum downgrade failed for me too... :-(

yum downgrade snap-confine-2.55.3-1.el7.x86_64  snapd-2.55.3-1.el7.x86_64 snapd-selinux-2.55.3-1.el7.noarch
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: lesnet.mm.fcix.net
 * epel: ziply.mm.fcix.net
 * extras: mirror.esecuredata.com
 * remi-php80: mirror.team-cymru.com
 * remi-safe: mirror.team-cymru.com
 * updates: mirror.esecuredata.com
No package snap-confine-2.55.3-1.el7.x86_64 available.
No package snapd-2.55.3-1.el7.x86_64 available.
No package snapd-selinux-2.55.3-1.el7.noarch available.
Error: Nothing to do

**Comment by Wlogzz** [comment]
Hi everyone!
Since yesterday I had such problem in nginx, I have managed to fix it as follows: (it worked for me vps)

**Install snapd**
	sudo yum install snapd -y
	sudo systemctl enable --now snapd.socket
	sudo ln -s /var/lib/snapd/snap /snap
	sudo snap install core; sudo snap refresh core

**Instalar cerbot**
	yum install certbot-nginx
	certbot --nginx

**Auto Renewal Script**
	sudo certbot renew --dry-run

**Comment by plao** [comment]
> Checked the yum history details...
> 
> Packages Altered: Updated snap-confine-2.55.3-1.el7.x86_64 @epel Update 2.57.6-1.el7.x86_64 @epel Updated snapd-2.55.3-1.el7.x86_64 @epel Update 2.57.6-1.el7.x86_64 @epel Updated snapd-selinux-2.55.3-1.el7.noarch @epel Update 2.57.6-1.el7.noarch @epel history info
> 
> But an explicit yum downgrade failed for me too... :-(
> 
> yum downgrade snap-confine-2.55.3-1.el7.x86_64 snapd-2.55.3-1.el7.x86_64 snapd-selinux-2.55.3-1.el7.noarch Loaded plugins: fastestmirror Loading mirror speeds from cached hostfile
> 
>     * base: lesnet.mm.fcix.net
> 
>     * epel: ziply.mm.fcix.net
> 
>     * extras: mirror.esecuredata.com
> 
>     * remi-php80: mirror.team-cymru.com
> 
>     * remi-safe: mirror.team-cymru.com
> 
>     * updates: mirror.esecuredata.com
>       No package snap-confine-2.55.3-1.el7.x86_64 available.
>       No package snapd-2.55.3-1.el7.x86_64 available.
>       No package snapd-selinux-2.55.3-1.el7.noarch available.
>       Error: Nothing to do

Same for me...I solved reverting (thanks to God we are using VMs) with VEEAM Backup to a previous version of the VM and adding an exclusion for snap* to the YUM config...

**Comment by fuwenjiang-cd** [comment]
$ snap --version
snap    2.57.6-1.el7
snapd   2.57.6-1.el7
series  16
centos  7
kernel  3.10.0-1160.el7.x86_64

$ cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)

same for me，ask for help……………………

**Comment by kormorix** [comment]
hello,
same problem for me!
Also on Centos 7.9 after update of snapd.
Waiting for solution.
kormorix

**Comment by kormorix** [comment]
.... obviously downgrade of snapd to the previous version does not work?!

**Comment by plao** [comment]
> I think downgrade will work, and prefer to perform a downgrade, but the previous version 2.55.3-1 is not provided anywhere. Anyone should share the previous version?

Right! It seems the problem is:

**_No package snap-confine-2.55.3-1.el7.x86_64 available.
No package snapd-2.55.3-1.el7.x86_64 available.
No package snapd-selinux-2.55.3-1.el7.noarch available._**

**Comment by Access-deny** [comment]
> > I think downgrade will work, and prefer to perform a downgrade, but the previous version 2.55.3-1 is not provided anywhere. Anyone should share the previous version?
> 
> Right! It seems the problem is:
> 
> **_No package snap-confine-2.55.3-1.el7.x86_64 available. No package snapd-2.55.3-1.el7.x86_64 available. No package snapd-selinux-2.55.3-1.el7.noarch available._**

Found it on http://ftp.ecslb.sjtu.edu.cn/epel/testing/7/x86_64/Packages/s/

**Comment by Ahmadhashem86** [comment]
I have downgraded  snapd  and then it works
remove snapd-selinux, snap-confine, snapd för version 2.57.6-1.el7 
# yum remove snap*
install the version before 2.57 ehich is 2.55.3-1
# rpm -Uvh https://mirror.lt.ucsc.edu/epel/7/x86_64/Packages/s/snap-confine-2.55.3-1.el7.x86_64.rpm
# rpm -Uvh https://mirror.lt.ucsc.edu/epel/7/x86_64/Packages/s/snapd-selinux-2.55.3-1.el7.noarch.rpm
# rpm -Uvh https://mirror.lt.ucsc.edu/epel/7/x86_64/Packages/s/snapd-2.55.3-1.el7.noarch.rpm
run snapd 
# sudo systemctl enable --now snapd.socket
# sudo ln -s /var/lib/snapd/snap /snap
Log out and log in again then instal core via snap
# sudo snap install core; sudo snap refresh core
Install certbot via snap
# sudo snap install --classic certbot
# sudo ln -s /snap/bin/certbot /usr/bin/certbot
# certbot renew
Now the important part is to disable auto renew for snap until snap fix this problem
# nano -w /etc/yum.conf
exclude=snap*
# yum update

**Comment by vividy163** [comment]
Thank you very much! Worked for me too!

**Comment by ZeusF1** [comment]
same issue on Centos7...
yum undo not working

Not available:
 snapd                                             x86_64                                 2.55.3-1.el7                                         -                                       0.0
 snapd-selinux                                noarch                                 2.55.3-1.el7                                         -                                       0.0
 snap-confine                                 x86_64                                 2.55.3-1.el7                                         -                                       0.0

so yes, only install from rpm is an solution

**Comment by vividy163** [comment]
Here is the correct URL.
https://mirror.lt.ucsc.edu/epel/7/x86_64/Packages/s/snapd-2.55.3-1.el7.x86_64.rpm

**Comment by okazuya** [comment]
yum --enablerepo=epel-testing update snapd

**Comment by alexzorin** [comment]
Per the last comment, a fixed version of snapd has been pushed to EPEL7 testing (`yum --enablerepo=epel-testing install snapd`).

It will be pushed to EPEL7 once https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-4790972cca has 3 votes, or in a weeks time, whichever is sooner.

I believe this should fix the crash for all CentOS 7 users and I'm going to close this issue, thank you.
