### ISSUE TITLE
Do not touch modified options-ssl-apache.conf

### ISSUE THREAD

**Issue by purple512** [certbot/certbot#9504]
Hello,

I modified options-ssl-apache.conf to my requirements. The comment at the top of the file says that these modifications will be respected.

Today I encountered downtime because certbot did not respect these changes and modified this file, making clients unable to connect due to improper cipher settings.

This is very frustrating. **I want certbot's nasty little hands to never touch this modified file.  I know better and do not want any of this "help" in choosing cipher suites.** How can I achieve this? I do not want to go through this again on a future renewal.

Apache on Debian 11 x64, using debian packaged version of certbot [1.12.0-2]

**Comment by alexzorin** [comment]
I unsuccessfully tried to reproduce this on Debian 11 with `python3-certbot-apache 1.10.1-1`/`python3-certbot 1.12.0-2`.

1. Ran `certbot --apache`
2. Modified `/etc/letsencrypt/options-ssl-apache.conf` so that it said `SSLProtocol all` rather than the original line.
3.  Ran `certbot renew --force-renewal` 
4. Ran `certbot install --cert-name example.com`. 

My change from (2) was preserved and not overwritten. 

If you can provide instructions on reproducing this, we can investigate. Thanks.

**Comment by purple512** [comment]
Okay, well I'm glad to hear that this is not intended behavior.

The steps leading up to the incident were:

- had Debian 10 with working setup
- dist-upgrade to Debian 11 on 2022-11-07
- that resulted in a new `options-ssl-apache.conf`, which I manually edited back to the desired value
- at the time I did a simulated renewal to make sure certbot was working, and it succeeded
- worked fine for a month or so, then on 2022-12-12 a renewal happened and it clobbered the config file

I suppose I might have triggered some hard to diagnose issue, in which case I'm not sure how to reproduce as I can't really revert a working system to Debian 10 to try again. I realize this is probably not enough information to reproduce anything, but it's the best I can do.

**Comment by alexzorin** [comment]
Mm, `dist-upgrade` would for sure not modify `options-ssl-apache.conf`. The Debian package is maintained [here](https://salsa.debian.org/letsencrypt-team/certbot/certbot-apache/-/tree/debian/1.10.1-1/) and you can see that it does not have any knowledge about this file.

(Unless you mean that you modified the one located inside `/usr/lib/python3/dist-packages/certbot_apache/_internal/tls_configs/`. If you did that, all bets are off).

I wasn't able to reproduce this even when upgrading from Debian 10, sorry. 

The only thing I can imagine is that, by coincidence, your modification might have exactly matched [one of the known previous versions of the file](https://github.com/certbot/certbot/blob/a807240db7b8ca60bc1bd637a66282b3ca449417/certbot-apache/certbot_apache/_internal/constants.py#L19-L38). If this was the case, Certbot would assume that the file has not been manually modified, and would proceed to overwrite it anyway.

**Comment by purple512** [comment]
Ah, now we're getting somewhere. I believe the cipher suite setting I used was one that an older version of Certbot had originally installed.

I guess I'll go add some whitespace to make sure that doesn't happen again.
