### ISSUE TITLE
Certbot looking for Apache SSL module in wrong folder

### ISSUE THREAD

**Issue by episodeiv** [certbot/certbot#9511]
On Gentoo with certbot 1.32.0, the following warning is logged when renewing certificates:
```
Apache version is 2.4.54                                                                                                                                     
[Errno 2] No such file or directory: '/etc/apache2/modules/mod_ssl.so'                                                                                       
Traceback (most recent call last):                                                                                                                           
  File "/usr/lib/python3.10/site-packages/certbot_apache/_internal/configurator.py", line 297, in _open_module_file                                          
    with open(ssl_module_location, mode="rb") as f:                                                                                                          
FileNotFoundError: [Errno 2] No such file or directory: '/etc/apache2/modules/mod_ssl.so'                                                                    
Unable to read ssl_module file; not disabling session tickets.                                                                                               
```

The module path should be `/usr/lib64/apache2`, not `/etc/apache2/modules`, which doesn't exist. If I symlink the latter to the former, the warning goes away.

I haven't yet been able to determine where certbot gets that path from...

**Comment by bmw** [comment]
The relevant code here is [this](https://github.com/certbot/certbot/blob/27af7b5d152ef89f1eb78e60972ee644a3238fdb/certbot-apache/certbot_apache/_internal/configurator.py#L304-L345) and maybe [this](https://github.com/certbot/certbot/blob/27af7b5d152ef89f1eb78e60972ee644a3238fdb/certbot-apache/certbot_apache/_internal/override_gentoo.py).

I'd want to be sure this is a problem in Gentoo more generally and not just your system, but I'd otherwise accept a PR for this.

@osirisinferi, if and only if you have the time and interest, I suspect this is something you could help us with as I suspect you have easier access to Gentoo machines at the moment than I do 😜

**Comment by osirisinferi** [comment]
I'll check my experiences with Apache and Gentoo later today or tomorrow, but I can already tell you my default Apache on Gentoo doesn't have any issue with Certbots Apache plugin. But I'll try to dive in a little bit deeper later :)

**Comment by osirisinferi** [comment]
Ah, I think I understand. Earlier I thought this was an issue about an *error* but it's indeed a warning I'm constantly getting too.

In [`ApacheConfigurator.openssl_version()`](https://github.com/certbot/certbot/blob/3bc463a66f13b44343b938ded86cfa79defbae58/certbot-apache/certbot_apache/_internal/configurator.py#L304-L345), Certbot uses [`ApacheParser.standard_path_from_server_root()`](https://github.com/certbot/certbot/blob/3bc463a66f13b44343b938ded86cfa79defbae58/certbot-apache/certbot_apache/_internal/parser.py#L654) to concatenate the module location `modules/mod_ssl.so` on to the Apache root, which usually is `/etc/apache`.

This however seems to be based on an assumption, if I read the code correctly: there is no actual logic to determine or to override the location of the modules: it's just assumed to always be under the Apache root directory. And, for Gentoo, this is indeed not the case.

**Comment by bmw** [comment]
Thanks so much for doing all of that digging Osiris.

Most distros have their own tooling wrapped around Apache and I think we're probably not understanding that tooling properly on Gentoo. Ideally this would be fixed, but I agree with Osiris that I'm not sure this is worth the effort for us right now. I think it'd be a decent size chunk of work without much benefit. Because of that, I'm closing this for now as wontfix.

**Comment by osirisinferi** [comment]
> I think it'd be a decent size chunk of work without much benefit.

I'm willing to put a little effort into this a few minutes at a time, one or two days per week :stuck_out_tongue: But of course only if the Certbot team is interested and willing to review the PR :slightly_smiling_face:

**Comment by bmw** [comment]
I'd only be interested in reviewing it if the resulting code change is fairly small, straightforward, properly handles all cases, and is a clean long term solution. I'd want to avoid just hardcoding `/usr/lib{,64}/` and actually parse the system and/or apache config to figure out where the file should be. I worry that doing that though conflicts with the other goal of the code being fairly small and straightforward but if you think you have an idea on how you can accomplish all of those things, by all means reopen this and take a crack at it.

Sorry if that's not what you wanted to hear, but as usual, we're stretched pretty thin and fixing a warning on Gentoo which is about 0.1% of our user base (and that's all Gentoo users, not just Gentoo Apache users) shouldn't be a big priority for us right now I think.

**Comment by osirisinferi** [comment]
> Sorry if that's not what you wanted to hear

I don't mind, I suggested it wasn't worth the effort in the first place :wink: I've also ignored this error for ages and it didn't bother me personally. But it would be nice to have it fixed (for "completeness" sake), but within the understandable constraints. :slightly_smiling_face: 



> fixing a warning on Gentoo which is about 0.1% of our user base (and that's all Gentoo users, not just Gentoo Apache users) shouldn't be a big priority for us right now I think.

I couldn't agree more!

**Comment by romariogland** [comment]
On Gentoo
```
cd /etc/apache2
ln -s /usr/lib64/apache2/modules modules
```

maybe not very correct, but it works and will work after the update of the certbot
