### ISSUE TITLE
Docker immage for RPI 4B (linux/arm/v7)

### ISSUE THREAD

**Issue by rafalolb** [certbot/certbot#9515]
## My operating system is (include version):
RaspberryPI 4B (linux/arm/v7)

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
I want to install certbot in my docker container.

## I ran this command and it produced this output:
> rafal@raspberrypi:~ $ sudo docker run -it --rm --name certbot \
> -v "/home/rafal/Certs:/etc/letsencrypt" \
> -v "/home/rafal/Certs:/var/lib/letsencrypt" \
> certbot/certbot certonly --manual -d *.mydomain.pl
> (...)
> Status: Downloaded newer image for certbot/certbot:latest
> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no > specific platform was requested
> standard_init_linux.go:219: exec user process caused: exec format error

## Certbot's behavior differed from what I expected because:
Could you create an docker image for linux/arm/v7?
or
Could I create an docker image for linux/arm/v7 and share it for other people?

**Comment by bmw** [comment]
Does replacing the 4th line of that command with:
```
certbot/certbot:arm32v6-latest certonly --manual -d *.mydomain.pl
```
work for you?

**Comment by rafalolb** [comment]
It works, tnx 🙂
