### ISSUE TITLE
PyPI search fails for some subpackages

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#952]
Searching for any those yields `letsencrypt` instead of the intended subpackage:
- https://pypi.python.org/pypi?%3Aaction=search&term=letsencrypt-apache&submit=search
- https://pypi.python.org/pypi?%3Aaction=search&term=letsencrypt-nginx&submit=search
- https://pypi.python.org/pypi?%3Aaction=search&term=letshelp-letsencrypt&submit=search

Those are OK:
- https://pypi.python.org/pypi?%3Aaction=search&term=acme&submit=search
- https://pypi.python.org/pypi?%3Aaction=search&term=letsencrypt&submit=search (returns main package only)

**Comment by kuba** [comment]
Fun part: `letsencrypt` is marked on PyPI as "Hidden", everything else is "Hidden: No". WTF?

BTW, these are just fine:
- https://pypi.python.org/pypi/letsencrypt-apache
- https://pypi.python.org/pypi/letsencrypt-nginx
- https://pypi.python.org/pypi/letshelp-letsencrypt

**Comment by pde** [comment]
Seems to be fixed now.
