### ISSUE TITLE
Missing pypi artifact for 2.1.1 release

### ISSUE THREAD

**Issue by chenrui333** [certbot/certbot#9521]
👋  not sure if that is a miss, but the pypi artifact is missing for the 2.1.1 release, thanks!

**Comment by alexzorin** [comment]
This was intentional, see the [note in the CHANGELOG](https://github.com/certbot/certbot/blob/master/certbot/CHANGELOG.md#211---2022-12-15):

>This release was not pushed to PyPI since those packages were unaffected.

**Comment by chenrui333** [comment]
Thanks for confirming it!
