### ISSUE TITLE
Documentation / Question: How to configure the automated renewal (snap.certbot.renew.timer) with pre/post hooks?

### ISSUE THREAD

**Issue by jdix531** [certbot/certbot#9522]
Hi, I am using letsencrypt to get certificates for our openvpn server. We use the amazon provided ami which seems to be ubuntu 18.04 and it has the snap version of certbot installed. After some digging I found https://eff-certbot.readthedocs.io/en/stable/using.html#automated-renewals which explains the /etc/letsencrypt/renewal/*.conf files a bit.

However all information I see in the docs state that pre/post hooks are for the manual switch only (https://eff-certbot.readthedocs.io/en/stable/using.html#pre-and-post-validation-hooks). I am not sure how to tell exactly what the snap.certbot.renew.timer is doing as I'm new to systemctl timers and found them only by digging where the renewal attempts were being generated in syslog.

Since I'm using a non-standard server and using the standalone method in my config file we then run some steps post-renewal to configure the openvpn server. We currently do this in place like:

```bash
certbot certonly --force-renew -d vpndomain.com --standalone
sudo cat /etc/letsencrypt/live/vpndomain.com/fullchain.pem /etc/letsencrypt/live/vpndomain.com/privkey.pem > /etc/letsencrypt/live/vpndomain.com/bundle.pem
/usr/local/openvpn_as/scripts/sacli --key "cs.priv_key" --value_file "/etc/letsencrypt/live/vpndomain.com/privkey.pem" ConfigPut
/usr/local/openvpn_as/scripts/sacli --key "cs.cert" --value_file "/etc/letsencrypt/live/vpndomain.com/fullchain.pem" ConfigPut
/usr/local/openvpn_as/scripts/sacli --key "cs.ca_bundle" --value_file "/etc/letsencrypt/live/vpndomain.com/bundle.pem" ConfigPut
/usr/local/openvpn_as/scripts/sacli start
```

```bash
root@ip-ip:/home/user# cat /etc/letsencrypt/renewal/vpndomain.com.conf
# renew_before_expiry = 30 days
version = 1.32.2
archive_dir = /etc/letsencrypt/archive/vpndomain.com
cert = /etc/letsencrypt/live/vpndomain.com/cert.pem
privkey = /etc/letsencrypt/live/vpndomain.com/privkey.pem
chain = /etc/letsencrypt/live/vpndomain.com/chain.pem
fullchain = /etc/letsencrypt/live/vpndomain.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = redacted
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = rsa
```

So I'm left unsure how to best automate things. I am presently thinking of disabling the automation certbot brings by removing /etc/letsencrypt/renewl/*.conf and creating my own script set up in cron. 

Thoughts? Thanks in advance for any help

**Comment by osirisinferi** [comment]
I think your question is better suited for the Let's Encrypt Community where we also often discuss clients such as Certbot. You can find the Community at https://community.letsencrypt.org/

**Comment by alexzorin** [comment]
In general, modifying the cronjob/systemd timer is not the right thing to do. Leave it alone and do everything either through a) the renewal `.conf` file, b) `/etc/letsencrypt/cli.ini` or c) `/etc/letsencrypt/renewal-hooks/deploy/`.

If you only have the one certificate, you could modify `/etc/letsencrypt/renewal/vpndomain.com.conf` so that under `[renewalparams]` it includes:

    renew_hook = /path/to/your/openvpn/certificate/deploy/script

making sure that the script is executable and doesn't contain any interactive commands (like `sudo` potentially).

We have an upcoming feature (`certbot reconfigure`) which will make it much easier to add a renewal hook to an existing certificate, but it's not quite there yet.
