### ISSUE TITLE
EPEL timer doesn't get enabled by default

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#9525]
It appears that the old issue might be back. It seems very reproducible: https://community.letsencrypt.org/t/automatice-renew-not-working-certbot-renew-timer-missing/190281/4?u=_az

**Comment by bmw** [comment]
We asked Certbot's Fedora/EPEL package maintainers about this in the thread starting at https://github.com/certbot/certbot/issues/8889#issuecomment-1064684113 but got no response 😩
