### ISSUE TITLE
Certbot 1.32.2 can hang polling Sectigo/ZeroSSL authz

### ISSUE THREAD

**Issue by mnordhoff** [certbot/certbot#9526]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 20.04 (amd64)

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
snap (Certbot 1.32.2)

## I ran this command and it produced this output:
2022-12-20:
```
$ sudo certbot certonly --cert-name dynroute53.mattnordhoff.net-ecdsa --key-type ecdsa --manual --manual-auth-hook "/opt/certbot_dns/certbot_dns.py --auth --config /opt/certbot_dns/certbot_dns.ini --route-53" --manual-cleanup-hook "/opt/certbot_dns/certbot_dns.py --cleanup --config /opt/certbot_dns/certbot_dns.ini --route-53" --preferred-challenges dns-01 --server https://acme.zerossl.com/v2/DV90 -d dynroute53.mattnordhoff.net -d www3.mattnordhoff.net
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Requesting a certificate for dynroute53.mattnordhoff.net and www3.mattnordhoff.net
Hook '--manual-auth-hook' for dynroute53.mattnordhoff.net ran with output:
 {"value": "\"XB7wfYhYVeZ2IFzi8RcxpLSQItb4qCr54NhZ7GNbJfc\"", "debug_host_name": "_acme-challenge.dynroute53", "zone_id": "Z098584139YZXBJKADLJ1", "version": 2, "debug_change_id": "C06296722GWQXDI0GI4RE", "debug_zone_name": "mattnordhoff.net", "fqdn": "_acme-challenge.dynroute53.mattnordhoff.net."}
Hook '--manual-auth-hook' for www3.mattnordhoff.net ran with output:
 {"debug_host_name": "_acme-challenge.www3", "version": 2, "fqdn": "_acme-challenge.www3.mattnordhoff.net.", "debug_zone_name": "mattnordhoff.net", "value": "\"nlX5TU5kV8EcUY6Ca16Vf2klaBMYOMgfnFo0Kc2dGbM\"", "debug_change_id": "C03741053SSN8JIFWERCD", "zone_id": "Z098584139YZXBJKADLJ1"}
^CExiting due to user request.

2022-12-21 00:00:11,171:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/snap/certbot/2618/lib/python3.8/site-packages/certbot/_internal/auth_handler.py", line 106, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/snap/certbot/2618/lib/python3.8/site-packages/certbot/_internal/auth_handler.py", line 164, in _poll_authorizations
    time.sleep(sleep_seconds)
KeyboardInterrupt
```

2022-12-31: It was the snap certbot renew timer; n/a.

(I haven't published `certbot_dns.py`.)

## Certbot's behavior differed from what I expected because:
Recently, on two different systems (both using 1.32.2 from snap), Certbot hung while polling an authz from ZeroSSL (which uses Sectigo's white label ACME API).

The first time, I hit ^C after an hour. The second time, I sent SIGTERM after over 12 hours. Both times, I noticed a CLOSE_WAIT connection to the ACME server, e.g.:

```
$ sudo lsof -ni | rg python
python3   2657947       root    8u  IPv6 232524025      0t0  TCP [2604:a880:400:d0::83:2002]:47062->[2a0e:ac00:c7:d450::5bc7:d450]:https (CLOSE_WAIT)
```

Sectigo/ZeroSSL is often so slow that Certbot gives up and exits, but it's not supposed to *actually freeze*. It seems like there's a bug somewhere. Maybe there's a polling issue. Maybe the connection gets into a weird state and Certbot/requests/Python doesn't handle it well. I dunno.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
2022-12-20: https://mn0.us/oT3aso7eoMVo/letsencrypt.log
2022-12-31: https://mn0.us/QruuC4BbvaBJ/letsencrypt.log

It doesn't show much; Certbot doesn't have a log entry for "nothing is happening". :-)

The second one shows an OCSP query timeout (which is somewhat common). The OCSP hostname uses Cloudflare but the ACME hostname does not, AFAICT.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
Not relevant.

**Comment by alexzorin** [comment]
I would guess that Certbot is doing its best to respect this response header:

>Retry-After: 86400

**Comment by osirisinferi** [comment]
Note that Certbots parsing of `Retry-After` headers *might* be buggy, see https://github.com/certbot/certbot/issues/9319

**Comment by mnordhoff** [comment]
1.) Oh jeez. I didn't even notice the Retry-After header.

That makes sense. The one with a traceback was in the middle of `time.sleep(sleep_seconds)`. (I didn't read the code to check for context, though.)

Well... Now what?

We haven't confirmed it, but everything may be working as designed.

What about changing the bug to something like, "Certbot should error out if Retry-After is more than 30 minutes?"

2.) I forgot to mention it, but I'm using UTC.

**Comment by mnordhoff** [comment]
If I'm reading my logs right, the poll interval makes no sense. It looks like Certbot interprets `Retry-After` like:

* `5`: 5 seconds
* `10`: 0
* `60`: 0 the first time; 60 seconds the second time
* `300`: 0
* `86400`: At least an hour

What in the world?

I wonder if Sectigo is treating the traffic as abusive -- although that's not fair when it starts out at 5 seconds.

**Comment by mnordhoff** [comment]
From another perspective, it's a bug that Retry-After can exceed the overall issuance timeout.

**Comment by osirisinferi** [comment]
> * `10`: 0
> * `60`: 0 the first time; 60 seconds the second time

I haven't checked it *thoroughly* but this is probably a misreading of the logs as I believe Certbot couples a certain retry-after to the type of POST that was send. E.g., if a *challenge* POST returns a retry-value of 10 seconds, Certbot doesn't have an issue with trying an *autz* POST immediately after the *chall* POST.

**Comment by mnordhoff** [comment]
Ah. I didn't compare the URLs before.

My first log has:

```
2022-12-20 22:55:16,410:DEBUG:acme.client:Sending POST request to https://acme.zerossl.com/v2/DV90/chall/vfH1QY8aC0PddRkyNzc0Zw:
2022-12-20 22:55:17,126:DEBUG:urllib3.connectionpool:https://acme.zerossl.com:443 "POST /v2/DV90/chall/vfH1QY8aC0PddRkyNzc0Zw HTTP/1.1" 200 163
2022-12-20 22:55:17,127:DEBUG:acme.client:Received response:
Retry-After: 10

2022-12-20 22:55:17,130:DEBUG:acme.client:Sending POST request to https://acme.zerossl.com/v2/DV90/chall/s1W6Zsm1LskamUNnQu2eOA:
2022-12-20 22:55:17,712:DEBUG:urllib3.connectionpool:https://acme.zerossl.com:443 "POST /v2/DV90/chall/s1W6Zsm1LskamUNnQu2eOA HTTP/1.1" 200 163
2022-12-20 22:55:17,712:DEBUG:acme.client:Received response:
Retry-After: 10

2022-12-20 22:55:18,715:DEBUG:acme.client:Sending POST request to https://acme.zerossl.com/v2/DV90/authz/POqcNQdCSmPrxb4jQWAx1A:
2022-12-20 22:55:19,406:DEBUG:urllib3.connectionpool:https://acme.zerossl.com:443 "POST /v2/DV90/authz/POqcNQdCSmPrxb4jQWAx1A HTTP/1.1" 200 460
2022-12-20 22:55:19,407:DEBUG:acme.client:Received response:
Retry-After: 5
```

Maybe it's specific to the exact URL, or the exact object, rather than just the type?

**Comment by osirisinferi** [comment]
> or the exact object

It's  probably that indeed. Certbot seems to be associating the retry after values to the exact object, but the Sectigo ACME server seems not to:

From your first log file:

Timestamp | Type | ID | Retry-After
-- | -- | -- | --
22:54:11 | authz | POqcNQdCSmPrxb4jQWAx1A | 5
22:54:12 | authz | U9Ucx8a8A4G7EOtiUZZpnw | 5
22:55:17 | chall | vfH1QY8aC0PddRkyNzc0Zw | 10
22:55:17 | chall | s1W6Zsm1LskamUNnQu2eOA | 10
22:55:19 | authz | POqcNQdCSmPrxb4jQWAx1A | 5
22:55:20 | authz | U9Ucx8a8A4G7EOtiUZZpnw | 5
22:55:25 | authz | POqcNQdCSmPrxb4jQWAx1A | 5
22:55:26 | authz | U9Ucx8a8A4G7EOtiUZZpnw | 5
(...) |   |   |  
22:56:16 | authz | POqcNQdCSmPrxb4jQWAx1A | 60
22:56:17 | authz | U9Ucx8a8A4G7EOtiUZZpnw | 60
22:57:19 | authz | POqcNQdCSmPrxb4jQWAx1A | 300
22:57:20 | authz | U9Ucx8a8A4G7EOtiUZZpnw | 86400

The last few retry after values go from 300 to 86400 with no regard to the actual object ID. And in your second log, it goes from 5 to 86400 immediately without the 300 in between. Maybe it depends on the current load on how long it delays clients?

**Comment by alexzorin** [comment]
I am struggling to guess what the intention of Sectigo sending 86400 is vs. a permanent error to make the client go away and come again another day.

I checked lego and acme.sh, they will hang around for 100 seconds and 90 seconds respectively. 

Certbot (without `Retry-After` involved) hangs around for (30 retries * 3 seconds default interval) = 90 seconds.

A simple approach might be to keep [`_poll_authorizations`](https://github.com/certbot/certbot/blob/b81ef33f33d69451f1ab981583240a1bac79f7c0/certbot/certbot/_internal/auth_handler.py#L145-L210)'s current approach of `max_retries`, but to set a hardcoded deadline of 30 minutes on the function, as suggested by @mnordhoff. Any sleep longer than that gets truncated.

That way, we give the server some wiggle room to delay clients, but not excessively so. Notably, it keeps Certbot's default 90 second behavior in the absence of `Retry-After` - we wouldn't be changing that.
