### ISSUE TITLE
/etc/letsencrypt/ folder is not created on installing of the certbot

### ISSUE THREAD

**Issue by stokito** [certbot/certbot#9530]
I installed the certbot with snap (edge) but the /etc/letsencrypt/ wasn't exists. 
I wanted to issue a cert but I need to put my deployment hook and I didn't know to where to put it because the /etc/letsencrypt/renewal-hooks/ didn't created yet.
So I just left it somewhere and specified the path directly. And after issuing a cert it finally was created.
This seems like a minor issue but I spent for some time and possibly might made a mistake. For such critical things like TLS issuing this is important to have all as clear as possible.

Could you please add some post install hook and create the folder structure?

Similar when I installed on Ubuntu with apt the /etc/letsencrypt/ was created but only with one cli.ini file.

For a Debian packages this is very easy to specify needed folders in the control file but I didn't found debian folder in sources. That means that the certbot is debianized by maintainers which adds a work for them and don't allow to build a deb package yourself.

P.S. When installing a new server ideally I want to just upload files with scp and reboot the server.
But I have to ssh into it and perform some commands to issue a cert. This is very inconvenient.

**Comment by alexzorin** [comment]
>Debian

The deb is maintained at https://salsa.debian.org/letsencrypt-team/certbot/certbot. 

>That means that the certbot is debianized by maintainers which adds a work for them and don't allow to build a deb package yourself.

Due to resources and team size, we only maintain packaging scripts for the packages we publish ourselves (snap, Docker, pip).

>my deployment hook

Using the CLI argument `--deploy-hook` is generally the right thing to do. 

Using `/etc/letsencrypt/renewal-hooks/deploy` is different in an annoyingly subtle but important way: it doesn't get invoked for the initial issuance of a certificate. Only for renewals.

If you want the hook to be executed for the initial issuance AND renewals, do it the former way.

>Could you please add some post install hook and create the folder structure?

I don't know off the top of my head whether we'd want to do this. Maybe.

My personal view is that because: 

a) this seems like a fairly uncommon requirement, and 
b) we'd have to implement this separately for the deb, rpm, pip and snap, (two of which requiring involving external volunteers),

 ... I'd rather just shift the burden of pre-creating relevant directories to the user, if it is relevant for them (config management tools, deploy scripts, whatever).

FWIW, running `certbot certificates` (or any verb, actually) is sufficient to create `/etc/letsencrypt/renewal-hooks/{pre,post,deploy}`.

**Comment by stokito** [comment]
Thank you for the detailed explanation.

I'll send a merge request to the Debian with the `dirs` file.
Here I found a sample from the ssl-cert (snakeoil) that creates `/etc/ssl/private` folder: https://salsa.debian.org/apache-team/ssl-cert/-/blob/master/debian/dirs


For the snap maybe we can add few lines here https://github.com/certbot/certbot/blob/master/snap/hooks/configure

> Using /etc/letsencrypt/renewal-hooks/deploy is different in an annoyingly subtle but important way: it doesn't get invoked for the initial issuance of a certificate. Only for renewals.

Thank you for letting me know. This would be a problem for me. I need the deploy hook just to copy certs into the `/etc/ssl/private`. And even the simplest thing has a problem :(

I have another similar one issue: when I first issuing a cert I need for a standalone mode but on renewing the 80 port will be used by my app that will serve the .well-known challenge.
So if I issued a cert with standalone mode then when the certbot tries to renew it will fail (right?).

This is not a big deal but I have to deploy and run my app first, then issue a cert and restart it. And only then continue with other software like prometheus-node-exporter for monitoring.
Previously when my app failed to start without certs I just started `busybox httpd` to serve the webroot.

I know that 99% users are just have the nginx behind and they don't have such stupid problems like me.

**Comment by stokito** [comment]
I created a PR for Debian https://salsa.debian.org/letsencrypt-team/certbot/certbot/-/merge_requests/7

**Comment by stokito** [comment]
Fedora/RedHat package sources https://src.fedoraproject.org/rpms/certbot/tree/rawhide

I sent a letter to a their dev and hope for an answer

**Comment by stokito** [comment]
> Using /etc/letsencrypt/renewal-hooks/deploy is different in an annoyingly subtle but important way: it doesn't get invoked for the initial issuance of a certificate. Only for renewals.

@alexzorin is any ticket about this? Maybe while we on the topic we can create `/etc/letsencrypt/renewal-hooks/issue` folder specifically for initial deployment hooks. Thus we can keep a backward compatibility

**Comment by alexzorin** [comment]
I haven't seen that suggestion before. Backwards compatibility is definitely important here and that's a good approach. 

In my personal opinion the `renewal-hooks` directory is a bit of a misfeature and hard to use and the `--{deploy,pre,post}-hook` CLI options are preferable in most circumstances.  But I welcome you to make the suggestion in another issue for consideration.

**Comment by stokito** [comment]
This is a minor change but when we talk about security the minor things may count. Especially for a popular project.

Reasoning:
1. -1 step for instructions. At first time I was lazy and just uploaded the deploy hook into `/opt/` and forget. I'm afraid other may do the same.
2. A user may create the folder but make a mistake or mess with perms and it's certs won't be updated properly.
3. A user can just make scp upload into the existing folder.

Still a user needs to ssh into a VPS and execute the cerbot command and that's something that I discussed #9642

I initially expected this would be an easy and quick change :*

**Comment by jonathanspw** [comment]
> Sorry, I initially expected this would be an easy and quick change :(

It will be, I just want to follow upstream (certbot) guidance for the aforementioned reasons :)

**Comment by stokito** [comment]
@alexzorin 
> CLI options are preferable in most circumstances. But I welcome you to make the suggestion in another issue for consideration.

Maybe we can decide this in scope of the ticket while we on the topic?
The `/etc/letsencrypt/issue-hooks/{deploy,pre,post}` seems like a reasonable place to store the hooks.
Then it will be minus one option in the certbot command.

**Comment by alexzorin** [comment]
>Maybe we can decide this in scope of the ticket while we on the topic?

I don't think so, please suggest it separately if you want to. I don't think there is an obvious best solution here.

**Comment by bmw** [comment]
I'm sorry this complicates your setup @stokito, but I don't think we're going to do this on our end and I recommend that @hlieberman and @jonathanspw do not either.

As Alex said, you can have your tooling run an arbitrary Certbot command like `certbot certificates` after it is installed and it will create these directories for you. I do not think it's worth automating this in N different ways across N different distribution methods after 7+ years of little to no other complaints about this especially when `/etc/letsencrypt/renewal-hooks` doesn't currently do what you wanted this directory to exist for in the first place.

I'm sure this isn't what you wanted to hear, but I hope it makes sense and sticking a `certbot certificates` command in your tooling helps you.
