### ISSUE TITLE
Vhost Parse Error (but apache vhost config file is valid)

### ISSUE THREAD

**Issue by RougeB** [certbot/certbot#9549]
I have have a new vhost with a non basic conf.
Certbot fails to parse the apache vhost file.

After analisys, the line that makes certbot fail is : 
define certificate "CN=%{SSL:SSL_CLIENT_S_DN_CN}s"

when running certbot --apache the output is : 

Saving debug log to /var/log/letsencrypt/letsencrypt.log
**Unexpected number of equal signs in runtime config dump.**
The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('Error parsing Apache runtime variables')

when i remove (or comment) the define line, it works .

Certbot says there are too much equal signs on the line... but the contempt of the variable shouldn't bother certbot.

I had to comment the define to have certbot run. After that, i uncomment the define ( and reload apache, of course) and the vhosts works fine.

## My operating system is (include version):
Ubuntu 20.04.1
Certbot is 0.40.0

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
apt-get

**Comment by alexzorin** [comment]
This part of Certbot's code was rewritten in newer releases. If you are able to use a newer version of Certbot and still experience this issue, please write back and I will re-open the issue.

More generally, variables that are defined at Apache runtime are not well supported by Certbot's Apache plugin. If the variable does not appear in `apachectl -t -D DUMP_RUN_CFG`, then it is likely that Certbot won't be able to work with it. In that case, you will probably have to avoid using the Apache plugin, until the parser improves its handling of runtime variables.

Thank you.

**Comment by RougeB** [comment]
ok, so i removed the apt-get version of certbot and installed the snap version (1.32.2) and : IT WORKS.

thanks a lot ! ticket closed ;-)
