### ISSUE TITLE
certbot getting "'Namespace' object has no attribute 'auth_chain_path'" error during ECDSA certificate request

### ISSUE THREAD

**Issue by rumato163** [certbot/certbot#9562]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version): 
Linux 5.15.26-gentoo

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc): 
pip

## I ran this command and it produced this output:
`certbot certonly --config certbot.ini --config-dir /opt/certbot/config --email email@test.com --key-type ecdsa --domain le-test99.test.com --cert-name ecdsa.le-test99.test.com -vvvv`

certbot.ini:
rsa-key-size = '2048'
key-type = 'rsa'
preferred-challenges = 'dns'
authenticator = 'dns-powerdns'
dns-powerdns-credentials = '/opt/certbot/pdns-credentials.ini'
max-log-backups = '0'
dns-powerdns-propagation-seconds = '15'
work-dir = '/opt/certbot/work'
config-dir = '/opt/certbot/config'
logs-dir = '/opt/certbot/logs'
non-interactive = true
agree-tos = true
disable-renew-updates = true
no-autorenew = true
no-directory-hooks = true
force-renewal = true
expand = true

And getting an error :
AttributeError: 'Namespace' object has no attribute 'auth_chain_path'
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /opt/lemg/logs/letsencrypt.log or re-run Certbot with -v for more details.

## Certbot's behavior differed from what I expected because:
Looks like I can't sign ECDSA certificate with non-standart cert-name

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
Root logging level set at -10
Saving debug log to /opt/certbot/logs/letsencrypt.log
Requested authenticator dns-powerdns and installer None
Single candidate plugin: * dns-powerdns
Description: Obtain certificates using a DNS TXT record (if you are using PowerDNS for DNS.)
Interfaces: Authenticator, Plugin
Entry point: dns-powerdns = certbot_dns_powerdns.dns_powerdns:Authenticator
Initialized: <certbot_dns_powerdns.dns_powerdns.Authenticator object at 0x7f08395d0520>
Prep: True
Selected authenticator <certbot_dns_powerdns.dns_powerdns.Authenticator object at 0x7f08395d0520> and installer None
Plugins selected: Authenticator dns-powerdns, Installer None
Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/', new_authzr_uri=None, terms_of_service=None), , Meta(creation_dt=datetime.datetime(2023, 2, 1, 9, 13, tzinfo=<UTC>), creation_host='', register_to_eff=None))>
Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 659
Received response:
HTTP 200
Server: nginx
Date: Fri, 03 Feb 2023 13:31:17 GMT
Content-Type: application/json
Content-Length: 659
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
Notifying user: Requesting a certificate for le-test99.test.com
Requesting a certificate for le-test99.test.com
Generating ECDSA key (2048 bits): /opt/certbot/config/keys/0078_key-certbot.pem
Creating CSR: /opt/certbot/config/csr/0078_csr-certbot.pem
Requesting fresh nonce
Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
Received response:
HTTP 200
Server: nginx
Date: Fri, 03 Feb 2023 13:31:17 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

Storing nonce: 
JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "le-test99.test.com"\n    }\n  ]\n}'
Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": 
  "signature": 
  "payload": 
}
https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 345
Received response:
HTTP 201
Server: nginx
Date: Fri, 03 Feb 2023 13:31:17 GMT
Content-Type: application/json
Content-Length: 345
Connection: keep-alive
Boulder-Requester: 
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/16
Replay-Nonce: 
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "ready",
  "expires": "2023-02-10T13:23:17Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "le-test99.test.com"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/16"
}
Storing nonce: 
JWS payload:
b''
Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/:
{
  "protected": "
  "signature": "
  "payload": ""
}
https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/ HTTP/1.1" 200 519
Received response:
HTTP 200
Server: nginx
Date: Fri, 03 Feb 2023 13:31:18 GMT
Content-Type: application/json
Content-Length: 519
Connection: keep-alive
Boulder-Requester: 943516077
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "le-test99.test.com"
  },
  "status": "valid",
  "expires": "2023-03-05T13:21:08Z",
  "challenges": [
    {
      "type": "dns-01",
      "status": "valid",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/",
      "token": "",
      "validationRecord": [
        {
          "hostname": "le-test99.test.com"
        }
      ],
      "validated": "2023-02-03T13:21:06Z"
    }
  ]
}
Storing nonce: 
CSR: CSR(file='/opt/certbot/config/csr/0078_csr-certbot.pem', data=b'-----BEGIN CERTIFICATE REQUEST-----
Will poll for certificate issuance until 2023-02-03 16:32:48.207651
JWS payload:
b'{\n  "csr": 
Sending POST request to https://acme-v02.api.letsencrypt.org/acme/finalize/16:
{
  "protected": 
  "signature": 
  "payload": 
  }
https://acme-v02.api.letsencrypt.org:443 "POST /acme/finalize/16 HTTP/1.1" 200 449
Received response:
HTTP 200
Server: nginx
Date: Fri, 03 Feb 2023 13:31:18 GMT
Content-Type: application/json
Content-Length: 449
Connection: keep-alive
Boulder-Requester: 
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/16
Replay-Nonce: 
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "valid",
  "expires": "2023-02-10T13:23:17Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "le-test99.test.com"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/",
  "certificate": "https://acme-v02.api.letsencrypt.org/acme/cert/"
}
Storing nonce: 
JWS payload:
b''
Sending POST request to https://acme-v02.api.letsencrypt.org/acme/order/:
{
  "protected": "
  "signature": "
  "payload": ""
}
https://acme-v02.api.letsencrypt.org:443 "POST /acme/order/16 HTTP/1.1" 200 449
Received response:
HTTP 200
Server: nginx
Date: Fri, 03 Feb 2023 13:31:20 GMT
Content-Type: application/json
Content-Length: 449
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "valid",
  "expires": "2023-02-10T13:23:17Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "le-test99.test.com"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/",
  "certificate": "https://acme-v02.api.letsencrypt.org/acme/cert/
}
Storing nonce: 
JWS payload:
b''
Sending POST request to https://acme-v02.api.letsencrypt.org/acme/cert/:
{
  "protected": "
  "signature": "
  "payload": ""
}
https://acme-v02.api.letsencrypt.org:443 "POST /acme/cert/ HTTP/1.1" 200 5341
Received response:
HTTP 200
Server: nginx
Date: Fri, 03 Feb 2023 13:31:20 GMT
Content-Type: application/pem-certificate-chain
Content-Length: 5341
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/cert//1>;rel="alternate"
Replay-Nonce: 1
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----

Storing nonce: 
Non-standard path(s), might not work with crontab installed by your operating system package manager
Creating directory /opt/certbot/config/archive/ecdsa.le-test99.test.com.
Creating directory /opt/certbot/config/live/ecdsa.le-test99.test.com.
Writing certificate to /opt/certbot/config/live/ecdsa.le-test99.test.com/cert.pem.
Writing private key to /opt/certbot/config/live/ecdsa.le-test99.test.com/privkey.pem.
Writing chain to /opt/certbot/config/live/ecdsa.le-test99.test.com/chain.pem.
Writing full chain to /opt/certbot/config/live/ecdsa.le-test99.test.com/fullchain.pem.
Writing README to /opt/certbot/config/live/ecdsa.le-test99.test.com/README.
Requested authenticator dns-powerdns and installer <certbot._internal.cli.cli_utils._Default object at 0x7f083917bc10>
Var rsa_key_size=2048 (set by user).
Var key_type=ecdsa (set by user).
Var pref_challs=dns (set by user).
Var autorenew=True (set by user).
Var config_dir=/opt/certbot/config (set by user).
Var work_dir=/opt/certbot/work (set by user).
Var logs_dir=/opt/certbot/logs (set by user).
Var authenticator=dns-powerdns (set by user).
Var dns_powerdns_propagation_seconds=15 (set by user).
Var dns_powerdns_credentials=/opt/certbot/pdns-credentials.ini (set by user).
Exiting abnormally:
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.9/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot==2.1.0', 'console_scripts', 'certbot')())
  File "/root/.local/lib/python3.9/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/root/.local/lib/python3.9/site-packages/certbot/_internal/main.py", line 1736, in main
    return config.func(config, plugins)
  File "/root/.local/lib/python3.9/site-packages/certbot/_internal/main.py", line 1590, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/root/.local/lib/python3.9/site-packages/certbot/_internal/main.py", line 138, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/root/.local/lib/python3.9/site-packages/certbot/_internal/client.py", line 529, in obtain_and_enroll_certificate
    return storage.RenewableCert.new_lineage(
  File "/root/.local/lib/python3.9/site-packages/certbot/_internal/storage.py", line 1120, in new_lineage
    values = relevant_values(vars(cli_config.namespace))
  File "/root/.local/lib/python3.9/site-packages/certbot/_internal/storage.py", line 294, in relevant_values
    rv = {
  File "/root/.local/lib/python3.9/site-packages/certbot/_internal/storage.py", line 297, in <dictcomp>
    if _relevant(namespaces, option) and cli.option_was_set(option, value)
  File "/root/.local/lib/python3.9/site-packages/certbot/_internal/cli/__init__.py", line 539, in option_was_set
    return set_by_cli(option) or not has_default_value(option, value)
  File "/root/.local/lib/python3.9/site-packages/certbot/_internal/cli/__init__.py", line 489, in set_by_cli
    if not isinstance(getattr(detector, var), _Default):
AttributeError: 'Namespace' object has no attribute 'auth_chain_path'
An unexpected error occurred:
AttributeError: 'Namespace' object has no attribute 'auth_chain_path'
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /opt/lemg/logs/letsencrypt.log or re-run Certbot with -v for more details.

**Comment by bmw** [comment]
Hmm. I wasn't able to reproduce this. Are you able to do so after installing Certbot and the DNS plugin you're using in a virtual environment by following instructions something like those at https://certbot.eff.org/instructions?ws=other&os=pip? Python environments can get weird if you're using `pip` globally where you also have packaged provided by your operating system.

**Comment by osirisinferi** [comment]
Or use the Portage Certbot package, it's very up to date. If you'd want, I could add the [`certbot-dns-powerdns`](https://pypi.org/project/certbot-dns-powerdns/) to my [third-party Certbot plugins overlay](https://github.com/osirisinferi/third-party-certbot-plugins).

**Comment by rumato163** [comment]
Yes I'm using portage Certbot package and pip installation of all other modules required for it
So It would be great to get 'certbot-dns-powerdns' plugin via portage package.

But I can't really get th eclue of that error.
Is that mean that Imissed some python module or smf similar?

**Comment by rumato163** [comment]
Thank you, guys!

I've set it up in venv and it looks good. Can't reproduce it there also.
Guess it's related to OS python environment or gentoo portage certbot package.

Looks like I can close the ticket
