### ISSUE TITLE
Docker certbot:arm32v6 > v1.29.0 not working

### ISSUE THREAD

**Issue by PonyOny** [certbot/certbot#9578]
## My operating system is (include version):

> Raspberry Pi 2 Model B Rev 1.1
> Linux rpi-lab 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

> certbot:
>         container_name: certbot
>         restart: unless-stopped
>         image: certbot/certbot:arm32v6-latest
>         volumes:
>             - /home/pi/docker/certbot/conf:/etc/letsencrypt
>             - /home/pi/docker/certbot/www:/var/www/certbot
>             - /home/pi/docker/webserver/www:/var/www
>         entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

## Certbot's behavior differed from what I expected because:

> Certbot will not start

## Here is a Certbot log showing the issue (if available):

> Traceback (most recent call last):
>   File "/usr/local/bin/certbot", line 33, in <module>
>     sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
>   File "/usr/local/bin/certbot", line 25, in importlib_load_entry_point
>     return next(matches).load()
>   File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
>     module = import_module(match.group('module'))
>   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/opt/certbot/src/certbot/certbot/main.py", line 6, in <module>
>     from certbot._internal import main as internal_main
>   File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 6, in <module>
>     import logging.handlers
>   File "/usr/local/lib/python3.10/logging/__init__.py", line 57, in <module>
>     _startTime = time.time()
> PermissionError: [Errno 1] Operation not permitted

**Comment by alexzorin** [comment]
I suspect this might be related to https://github.com/docker/for-linux/issues/1145. I'm not sure there's anything we can do about it.

You could try running the Docker container with privileged by setting `privileged: true` in the `docker-compose` manifest.

**Comment by PonyOny** [comment]
Working all fine, closing the issue.
