### ISSUE TITLE
certbot fails with munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by houmie** [certbot/certbot#9590]
## My operating system is (include version):
```
Debian 11 (5.10.0-8-amd64)
Debian 11 (5.10.0-21-amd64)
```

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
```
apt update
apt upgrade
apt install certbot
```

## I ran this command and it produced this output:
```
root@AE-FUJ-W-4:~# certbot
munmap_chunk(): invalid pointer
Aborted
```

## Certbot's behavior differed from what I expected because:
It doesn't run. I can't even do a `certbot --version` it fails too.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
No log file present.
Nothing found in syslog either.

**Comment by alexzorin** [comment]
What happens when you run these commands:

    python3 -c "print('hi')"

and

  python3 -c 'from certbot import main; main.main("--version")'

This one might be illuminating as well, if you can upload the resulting `certbot-strace.txt` file in a comment:

    strace -o certbot-strace.txt certbot --version

**Comment by houmie** [comment]
Thank you for your response.

First one:
```
root@AE-FUJ-W-4:~# python3 -c "print('hi')"
hi
```

and the next one:
```
root@AE-FUJ-W-4:~# python3 -c 'from certbot import main; main.main("--version")'
munmap_chunk(): invalid pointer
Aborted
```

And the log file for the last one is attached.

[certbot-strace.txt](https://github.com/certbot/certbot/files/10798060/certbot-strace.txt)

Thanks

**Comment by alexzorin** [comment]
Looks like a crash related to the `readline` module. I'll try take a look tomorrow.

**Comment by houmie** [comment]
@alexzorin Thank you. I'm happy to test the PR when you are ready. I suppose I have to compile from the source for the test.

**Comment by alexzorin** [comment]
I don't think it's likely that the crash can be fixed in Certbot project, rather that something has gone wrong in your server's environment. `readline` [is a standard Python module](https://docs.python.org/3/library/readline.html) and your Python is crashing when that module is loaded.

I tried downloading Debian 11 and installing Certbot the way you did, and it does not crash for me.

Does this crash for you?

    python3 -c "import readline; quit()"

**Comment by houmie** [comment]
Yes, you are right. This seems to only happen with a VPS provider I'm with. I wonder what they have done.

```
root@AE-FUJ-W-4:~# python3 -c "import readline; quit()"
munmap_chunk(): invalid pointer
Aborted
```

Yes, this crashes for me too.
