### ISSUE TITLE
The Certbot Docker image does not have an arm64 build under latest tag

### ISSUE THREAD

**Issue by dneary** [certbot/certbot#9593]
## My operating system is (include version):
Rocky Linux 8 on Ampere Altra (Tau T2A instance on GCloud)

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc): 
Docker

## I ran this command and it produced this output: 
```
docker-compose run --rm  certbot certonly --webroot --webroot-path /var/www/certbot/ --dry-run -d example.org
exec /usr/local/bin/certbot: exec format error
```
This was with "image: certbot/certbot:latest" in docker-compose.yml - the error is because the only binary for certbot/certbot:latest is an AMD64 image

## Certbot's behavior differed from what I expected because:
I expect the `latest` tag on a container to be a multi-architecture container that will run on aarch64. There is an arm64v8_latest image I used instead, but I would love to help others avoid this issue in the future.

**Comment by bmw** [comment]
This was fixed in https://github.com/certbot/certbot/issues/8225 and will take effect in early March.

In the meantime, you can use the image `certbot/certbot:arm64v8-latest`.
