### ISSUE TITLE
High CPU utilization / long delay during "Cleaning up challenges"

### ISSUE THREAD

**Issue by matthewbjones** [certbot/certbot#9594]
## My operating system is (include version):
`Linux nginx-primary 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
```
snap --version
snap    2.58.2
snapd   2.58.2
series  16
ubuntu  18.04
kernel  4.15.0-112-generic
```

## Certbot's behavior differed from what I expected because:
Previous to the release version `2.3.0` (`Feb 14, 2023`), the average time between `"Cleaning up challenges"` and the next log line output on our machine was approximately `30 seconds`. Starting `Feb 15, 2023`, after `certbot` was auto-updated to `2.3.0`, we started getting high CPU utilization reports (using ~95% of the CPU) when attempting to secure a new certificate. Also, the time between `"Cleaning up challenges"` and the next line spiked to `1 hour to 1.5 hours`, and then eventually seemingly settled at an average of `~3 minutes`.

### Example log history prior to 2.3.0 / Feb 14, 2023
```
2023-02-12 10:29:30,109:INFO:certbot._internal.auth_handler:Cleaning up challenges
2023-02-12 10:30:00,318:DEBUG:certbot._internal.client:CSR: CSR(file='/etc/letsencrypt/csr/264088_csr-certbot.pem', data=b'-----BEGIN CERTIFICATE REQUEST-----\n[redcated]\n', form='pem')

2023-02-13 00:44:13,040:INFO:certbot._internal.auth_handler:Cleaning up challenges
2023-02-13 00:44:45,110:DEBUG:certbot._internal.client:CSR: CSR(file='/etc/letsencrypt/csr/264203_csr-certbot.pem', data=b'-----BEGIN CERTIFICATE REQUEST-----\n[redacted]\n-----END CERTIFICATE REQUEST-----\n', form='pem')

2023-02-13 00:59:12,926:INFO:certbot._internal.auth_handler:Cleaning up challenges
2023-02-13 00:59:44,519:DEBUG:certbot._internal.client:CSR: CSR(file='/etc/letsencrypt/csr/264213_csr-certbot.pem', data=b'-----BEGIN CERTIFICATE REQUEST-----\n[redacted]\n-----END CERTIFICATE REQUEST-----\n', form='pem')
```
Note the time difference between the two lines.

### Example log history after 2.3.0 upgrade / Feb 15, 2023 and onward
```
2023-02-16 01:25:30,996:INFO:certbot._internal.auth_handler:Cleaning up challenges
2023-02-16 02:21:00,166:DEBUG:certbot._internal.client:CSR: CSR(file=None, data=b'-----BEGIN CERTIFICATE REQUEST-----\n[redacted]\n', form='pem')

2023-02-17 10:16:18,451:INFO:certbot._internal.auth_handler:Cleaning up challenges
2023-02-17 11:50:31,763:DEBUG:certbot._internal.client:CSR: CSR(file=None, data=b'-----BEGIN CERTIFICATE REQUEST-----\n[redacted]\n-----END CERTIFICATE REQUEST-----\n', form='pem')

2023-02-22 14:43:55,446:INFO:certbot._internal.auth_handler:Cleaning up challenges
2023-02-22 14:47:04,871:DEBUG:certbot._internal.client:CSR: CSR(file=None, data=b'-----BEGIN CERTIFICATE REQUEST-----\n[redacted]\n-----END CERTIFICATE REQUEST-----\n', form='pem')

2023-02-22 20:10:23,585:INFO:certbot._internal.auth_handler:Cleaning up challenges
2023-02-22 20:13:38,653:DEBUG:certbot._internal.client:CSR: CSR(file=None, data=b'-----BEGIN CERTIFICATE REQUEST-----\n[redacted]\n-----END CERTIFICATE REQUEST-----\n', form='pem')

2023-02-22 20:04:09,426:INFO:certbot._internal.auth_handler:Cleaning up challenges
2023-02-22 20:07:21,719:DEBUG:certbot._internal.client:CSR: CSR(file=None, data=b'-----BEGIN CERTIFICATE REQUEST-----\n[redacted]\n', form='pem')
```
Note the vastly increased time difference between the two lines.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
Using NGINX challenges.

I was attempting to dig into this further, but from what I could tell, the NGINX plugin doesn't seem to write log entries very often, so I'm not sure what it's doing during "Cleaning up challenges" that is taking so much longer compared to the previous release.

Our server has about ~2000 domains / certificates active.

**Comment by wgreenberg** [comment]
Sorry to hear that! Do you happen to know the exact certbot version that corresponds to your earlier logs? Prior to release 2.3.0 generally, the version was 1.32.2 -- were you using that?

**Comment by alexzorin** [comment]
Does doing a dry run also exhibit the high CPU usage?

    certbot certonly --nginx -d example.com --dry-run

If it does, something that might help bisect this issue might be to try install different versions of Certbot and the nginx plugin [in a pip virtual environment](https://certbot.eff.org/instructions?ws=nginx&os=pip) and try run that above command. You'd have to amend the instructions to be something more like:

    sudo /opt/certbot/bin/pip install certbot==2.1.0 certbot-nginx==2.1.0

It would be helpful to know, which of the following releases the issue first appeared in:

- 2.0.0
- 2.1.0
- 2.3.0

**Comment by matthewbjones** [comment]
> Sorry to hear that! Do you happen to know the exact certbot version that corresponds to your earlier logs? Prior to release 2.3.0 generally, the version was 1.32.0 -- were you using that?

Great question, I was able to get that info from the logs files.

Previous version:
`2023-02-14 20:30:59,521:DEBUG:certbot._internal.main:certbot version: 1.32.2`

Current version:
`2023-02-15 05:56:04,506:DEBUG:certbot._internal.main:certbot version: 2.3.0`

**Comment by matthewbjones** [comment]
> Does doing a dry run also exhibit the high CPU usage?
> 
> ```
> certbot certonly --nginx -d example.com --dry-run
> ```
> 

It does, here's the output of `top` when running a dry run:

```
top - 15:31:25 up 924 days, 13:05,  2 users,  load average: 1.27, 1.13, 1.20
Tasks: 135 total,   3 running,  87 sleeping,   0 stopped,   0 zombie
%Cpu(s): 98.3 us,  1.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.2 si,  0.5 st
KiB Mem :  4039260 total,   479264 free,  1623292 used,  1936704 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  2061952 avail Mem 

  PID USER            PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
15093 [redacted]      20   0  519452 472364   9976 R  98.7 11.7  13197:28 python3
24295 [redacted]      20   0   96036  54628  15456 R  97.4  1.4   0:12.33 python3
```

I'll also mention that the command line output (not the log file):
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Simulating a certificate request for [redacted]

Certbot failed to authenticate some domains (authenticator: nginx). The Certificate Authority reported these problems:
  Domain: [redacted]
  Type:   dns
  Detail: DNS problem: NXDOMAIN looking up A for [redacted] - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for [redacted] - check that a DNS record exists for this domain

Hint: The Certificate Authority failed to verify the temporary nginx configuration changes made by Certbot. Ensure the listed domains point to this nginx server and that it is accessible from the internet.
```

Between the `"Saving debug log"` and the next line `"Simulating a certificate request"` took what felt like ~30 seconds.

The entire dryrun process ran for over 4 minutes 45 seconds. After the `"Hint: The Certificate Authority..."` nothing was outputted for several minutes.

I will try to attempt the pip virtual environment approach you recommend and will report back, but wanted to pass along this datapoint in the meantime.

The other thing I'll mention is, the CPU spike alarms we're receiving seemingly only happen when adding new domains to our system. I haven't verified yet, but assuming the automatic renewals are still working, we're not getting CPU alerts when that process is running. I haven't dug through logs yet to determine how long each renewal is taking and if that is also askew.

**Comment by alexzorin** [comment]
I have a mild suspicion that my change in #9475 may have caused this performance regression. Checking that the issue is absent in Certbot v2.0.0 but present in v2.1.0 should confirm whether that's the case.

**Comment by matthewbjones** [comment]
I'm currently stuck here and still trying to figure out (I'm not a python expert)

```
/opt/certbot/bin/pip install certbot==2.1.0 certbot-nginx==2.1.0
ERROR: Could not find a version that satisfies the requirement certbot==2.1.0 (from versions: 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.11.1, 0.12.0, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.16.0, 0.17.0, 0.18.0, 0.18.1, 0.18.2, 0.19.0, 0.20.0, 0.21.0, 0.21.1, 0.22.0, 0.22.1, 0.22.2, 0.23.0, 0.24.0, 0.25.0, 0.25.1, 0.26.0, 0.26.1, 0.27.0, 0.27.1, 0.28.0, 0.29.0, 0.29.1, 0.30.0, 0.30.1, 0.30.2, 0.31.0, 0.32.0, 0.33.0, 0.33.1, 0.34.0, 0.34.1, 0.34.2, 0.35.0, 0.35.1, 0.36.0, 0.37.0, 0.37.1, 0.37.2, 0.38.0, 0.39.0, 0.40.0, 0.40.1, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 1.10.0, 1.10.1, 1.11.0, 1.12.0, 1.13.0, 1.14.0, 1.15.0, 1.16.0, 1.17.0, 1.18.0, 1.19.0, 1.20.0, 1.21.0, 1.22.0, 1.23.0)
ERROR: No matching distribution found for certbot==2.1.0
```

**Comment by alexzorin** [comment]
You won't be able to use Certbot >=1.24.0 from Python 3.6 unfortunately. Instead I've built the Certbot snap with c178fa8c0be8266a6edd9be5973bc1c135734c38 reverted (download here: https://github.com/alexzorin/certbot/releases/download/v2.4.0.dev0/certbot_2.4.0.dev0_amd64.snap), to see whether the hypothesis is right.

You can install it with:

    snap install --classic --dangerous certbot_2.4.0.dev0_amd64.snap

and try the dry-run again. 

To go back to the stable snap (though `refresh` might need to be `install`, not sure):

    snap refresh --stable certbot

**Comment by matthewbjones** [comment]
After being on the struggle bus for a bit, finally was able to install python version `3.7.5`.

Here are my timed runs of the dry run:

### certbot Version 2.3.0
```
time stats:
real	3m21.278s
user	3m5.032s
sys	0m2.624s
```

### certbot Version 2.1.0
```
real	3m5.279s
user	2m51.956s
sys	0m1.607s
```

### certbot Version 2.0.0
```
real	1m0.351s
user	0m45.585s
sys	0m1.713s
```

All three version used ~100% of the CPU (one `python3` process), however, version `2.0.0` ran significantly faster.

Out of curiosity, I tried installing version `1.32.0` (note: my logs showed we were using `1.32.2` but that is apparently not installable via `pip`). After installing, I tried running the same dryrun but then got:

```
Traceback (most recent call last):
  File "/opt/certbot/bin/certbot", line 5, in <module>
    from certbot.main import main
  File "/opt/certbot/lib/python3.7/site-packages/certbot/main.py", line 6, in <module>
    from certbot._internal import main as internal_main
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 28, in <module>
    from certbot import crypto_util
  File "/opt/certbot/lib/python3.7/site-packages/certbot/crypto_util.py", line 42, in <module>
    from certbot import interfaces
  File "/opt/certbot/lib/python3.7/site-packages/certbot/interfaces.py", line 21, in <module>
    from acme.client import ClientBase
ImportError: cannot import name 'ClientBase' from 'acme.client' (/opt/certbot/lib/python3.7/site-packages/acme/client.py)
```

So I downgraded back to python `3.6.9`, and the latest version of certbot I was able to install was `1.23.0`.

CPU was also ~100% and the time was:

### certbot Version 1.23.0
```
real	1m5.534s
user	0m51.981s
sys	0m1.870s
```

Given that in all the versions tested, the CPU was fully utilized, I guess that was a false issue raised by myself. I think it was never noticed in the past is because the length of time `certbot` runs for, in the older versions it is about 60 seconds, too short to be noticed by our monitoring tools. However, with version `2.1.0` and onward, taking 3 to 3.5 minutes, probably long and sustained enough to trigger some alerts (or maybe this is the optimal run time, and in some cases may take 5+ minutes?)

I hope this is helpful?

**Comment by alexzorin** [comment]
That makes sense to me and confirms my suspicion. 

The issue with large nginx configurations and a big number of certificates, Certbot's nginx plugin can take a lot of CPU time to parse and update the nginx configuration. The plugin doesn't scale amazingly, but it does a decent job for the typical installation.

That 2.1.0 is 3x slower for you than 2.0.0 says to me that we should just revert https://github.com/certbot/certbot/pull/9475. The functionality is nice to have, but not worth such a dramatic performance loss.

It will be reverted for v2.4.0. In the meantime you can use the dangerous snap I built in my last comment, but otherwise v2.4.0 should be available in the first week of March.

**Comment by matthewbjones** [comment]
Okay great thanks. I think we'll end up just waiting for the 2.4.0 release, for now we're able to tolerate the performance regression and know what the CPU alarms are about, but good to know we can use the dangerous snap as a short term option of we need to.

I recognize that our usage of certbot + nginx is not a common one (using nginx as a reverse proxy for SSL for several thousands of custom domains backed by our service) but appreciate the willingness to continue to support our larger installation use case. Now that I have an approach to replicate our production instance and then perform these performance experiments on, if you ever would like us to performance test a release or a development build, do reach out to me and we'd be more than happy to assist with that effort.

Let me know if you would like me to update the title of this issue to be more reflective of the issue and conclusion, just let me know what to change it to.
