### ISSUE TITLE
please document how to set server CA certficate

### ISSUE THREAD

**Issue by calestyo** [certbot/certbot#9609]
Hey.

In my systems I typically don't want to set default CA certificates in `/etc/ssl/certs/` for security reasons.

Because of that, `certbot` fails as it cannot verify the certificate of the ACME server.

As far as I could see, `certbot` itself doesn't provide an option to set a trusted certificate specifically for `certbot` only (which it should however).<br>
But at least one can use python-requests `REQUESTS_CA_BUNDLE` e.g. like `REQUESTS_CA_BUNDLE=/path/to/cert.pem`.

I think it would be nice if this was documented (or an according option provided).

Cheers,
Chris.

**Comment by alexzorin** [comment]
https://eff-certbot.readthedocs.io/en/stable/using.html#changing-the-acme-server

**Comment by calestyo** [comment]
Oh, I meant in the manpage. But if you figure it's enough to have it there, than just close the ticket.

**Comment by alexzorin** [comment]
It's in `man 7 certbot` but not `man 1 certbot`. 

We don't put much focus on the man pages, as the website is the primary source of documentation. 

I think we can improve `man 1 certbot` by adding a "SEE ALSO" section which can include a reference to the website and also to `man 7 certbot`.

**Comment by calestyo** [comment]
Thanks.

What would IMO be even better:
Is there any chance to make this an option, that is also stored in the account data? That would simplify renewals.

**Comment by calestyo** [comment]
Closing this, since he main point (adding documentation about `REQUESTS_CA_BUNDLE`) was already in place and I just haven't seen it. (Sorry for the noise).

Added the feature request about having a real option for this as a #9610.
