### ISSUE TITLE
Outdated instructions

### ISSUE THREAD

**Issue by stamanker** [certbot/certbot#9616]
Hi,
Instructions from
https://wstutorial.com/rest/spring-boot-with-lets-encrypt.html
https://dzone.com/articles/spring-boot-secured-by-lets-encrypt

## I ran this command and it produced this output:
certbot# ./certbot-auto --help
bash: ./certbot-auto: No such file or directory

**Comment by alexzorin** [comment]
Official instructions for using Certbot can be found at https://certbot.eff.org/instructions.

If you need help getting it to work with Spring Boot, you can ask for help at https://community.letsencrypt.org/.
