### ISSUE TITLE
DeprecatedArgumentAction doesn't print anything

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#9618]
In the UX overhaul (originating [here](https://github.com/certbot/certbot/pull/8765/files#diff-2d6ee57700dc1f66f9f464b21ba4a9b3892ac453cd1964bb97fef6f8c59d7826L441), I changed (for a reason that is not documented and I can't recall) `logger.warning` to `warnings.warn(..., DeprecationWarning)`. 

Only problem is, this doesn't print anything in a default Python runtime.

I think that we probably do want to emit output here. So, either promote `DeprecationWarning` to something that prints by default, or go back to `logger.warning`.

**Comment by bmw** [comment]
I think we should switch back to `logger.warning` with the main reason being that I don't think we should expose the user to every `DeprecationWarning` that comes up in our dependency tree. What do you think?

**Comment by alexzorin** [comment]
Hmm, turns out `logger.warning` doesn't print either. 

The reason is that `pre_arg_parse_setup` sets the pre-arg-parsing logging level to `constants.QUIET_LOGGING_LEVEL` and the UX overhaul reduced this from `WARNING` to `ERROR`.

I think at the time, we did not recognize the effect this would have.

I am tempted to do the simple thing and to set the logging level in `pre_arg_parse_setup`directly to `WARNING`, instead of it using `QUIET_LOGGING_LEVEL`.

Does that sound OK?

**Comment by bmw** [comment]
Oh geez. I feel like there's a couple of things we could improve here such as:

1. Stop the pre-argparse setup from not printing messages that would have been printed with the logging setup used after argument parsing. I think an approach with another memory handler could be used here.
2. Think about how we want to warn users about problems more generally. I've previously always used `logger.warning`, but if `--quiet` results in the ERROR logging level, this doesn't work. That's assuming we want to warn people using that flag about things aren't total errors at least sometimes. You and Erica may have already done some of this thinking though and I'm just unfamiliar with it.

I think your approach is a clever solution for now though, especially if it's coupled with a comment explaining why WARNING is being used.
