### ISSUE TITLE
certbot/dns-route53 does not exit with code 1 when it fails

### ISSUE THREAD

**Issue by ghnp5** [certbot/certbot#9626]
Hello,

I'm running a command such as:

`docker run --rm --name certbot --env AWS_ACCESS_KEY_ID=... --env AWS_SECRET_ACCESS_KEY=... -v "...:/etc/letsencrypt" certbot/dns-route53 certonly --text -vvv --agree-tos --dns-route53 --non-interactive --email ... --cert-name ... --expand --keep-until-expiring -d '*.xxx.com' -d 'xxx.com'`

And I'm expecting to exit with a return code > 0.

However, it appears that `$?` is 0, and therefore my cron script believes it succeeded,
when it crashed completely, with loads of outputs of python stack-traces, e.g. `Traceback (most recent call last)`

--

The bottom of the output, for reference:

> Traceback (most recent call last):
>   File "/usr/local/bin/certbot", line 33, in <module>
>     sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
>   File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
>     return internal_main.main(cli_args)
>   File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1864, in main
>     return config.func(config, plugins)
>   File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1597, in certonly
>     lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
>   File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 141, in _get_and_save_cert
>     lineage = le_client.obtain_and_enroll_certificate(domains, certname)
>   File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 516, in obtain_and_enroll_certificate
>     cert, chain, key, _ = self.obtain_certificate(domains)
>   File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
>     orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
>   File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
>     authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
>   File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
>     resps = self.auth.perform(achalls)
>   File "/opt/certbot/src/plugin/certbot_dns_route53/_internal/dns_route53.py", line 68, in perform
>     raise errors.PluginError("\n".join([str(e), INSTRUCTIONS]))
> certbot.errors.PluginError: Unable to locate credentials
> To use certbot-dns-route53, configure credentials as described at https://boto3.readthedocs.io/en/latest/guide/configuration.html#best-practices-for-configuring-credentials and add the necessary permissions for Route53 access.
> Unable to locate credentials
> To use certbot-dns-route53, configure credentials as described at https://boto3.readthedocs.io/en/latest/guide/configuration.html#best-practices-for-configuring-credentials and add the necessary permissions for Route53 access.
> Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.

**Comment by alexzorin** [comment]
It seems to give a correct non-zero exit code for me:

    $ docker run --rm certbot/dns-route53 certonly --non-interactive --dns-route53 -d route53-example.com --dry-run --agree-tos --register-unsafely-without-email; echo $?
    Saving debug log to /var/log/letsencrypt/letsencrypt.log
    Account registered.
    Simulating a certificate request for route53-example.com
    Unable to locate credentials
    To use certbot-dns-route53, configure credentials as described at https://boto3.readthedocs.io/en/latest/guide/configuration.html#best-practices-for-configuring-credentials and add the necessary permissions for Route53 access.
    Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
    1
