### ISSUE TITLE
domains parameter not honorating CN subject

### ISSUE THREAD

**Issue by vekexasia** [certbot/certbot#9633]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## I ran this command and it produced this output:
```
certbot certonly --non-interactive --agree-tos --manual-public-ip-logging-ok --manual --preferred-challenges=http \
  --manual-auth-hook ./authenticator.sh \
  --manual-cleanup-hook ./cleanup.sh \
  --logs-dir ./logs \
  --work-dir ./ \
  --config-dir ./ \
  --agree-tos \
  -m domains@xxxx.com \
  -d www.blabla.com -d blabla.com



## Certbot's behavior differed from what I expected because:
It successfully generated a certificate but with blabla.com as CN subject and not www.blabla.com as suggested by the help which states that the first specified domain is going to be the subject.

## Here is a Certbot log showing the issue (if available):
###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

**Comment by vekexasia** [comment]
thanks for the explanation @alexzorin closing

**Comment by alexzorin** [comment]
For anyone else watching, it turns out Let's Encrypt did change something on their end. They [used to](https://community.letsencrypt.org/t/domain-ordering-not-respected-unexpected-certificate-subject/195337/6?u=_az) use the first (unsorted) domain, but now they use the first domain post-sorting.

**Comment by eworm-de** [comment]
> > as suggested by the help which states that the first specified domain is going to be the subject
> 
> Our documentation should not say this. I had a look in the User Guide and I couldn't find where this is stated. Are you able to point me to where you read this? Thanks.

This was changed in d4b2d3202bb7cb58d3e24bcc95b104b102600005.
