### ISSUE TITLE
Search key_dir when performing Proof of Possession

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#964]
`proof_of_possession.py` currently relies only on the `installer` to determine the location of potential private keys that could be used to complete the challenge. While the `installer` should continue to be used, the code should also check the `key_dir` of the main configuration. This is where the client stores all private keys it creates when generating a CSR.

This will require a little refactoring, but `continuity_auth.py` has access to the configuration and should simply forward it along to `proof_of_possession.py`

**Comment by bmw** [comment]
Significant progress has been towards this in the `search_key_dir_in_pop` branch.

No one else should try to work on this until PoP is supported in the client again.

**Comment by schoen** [comment]
It seems like this concept has been totally removed from the ACME work (for example, it's not present at all in https://www.rfc-editor.org/internet-drafts/draft-ietf-acme-acme-18.txt, which is about to become RFC 8555). So I don't think we need to keep issues open about it; I'm not aware that there are any current WG proposals to reinstate this mechanism.
