### ISSUE TITLE
Issue with wildcard when using --manual-auth-hook settings

### ISSUE THREAD

**Issue by Pbast** [certbot/certbot#9645]
Hello,

With custom manual-auth-hook it is impossible to get full DNS name with wildcard.

CERTBOT_DOMAIN and CERTBOT_ALL_DOMAINS contains domaine names asked with -d but without wildcard

Then, it is impossible to add example.com and *.example.com in one cert.

I want to contribute in this nice code but I need some help for this.
I want to add this environment variable :
```
 CERTBOT_ALL_DOMAIN_WITH_WILDCARD= *.example.com | example.com
 CERTBOT_DOMAIN_WITH_WILDCARD=example.com,*.example.com
```
inserted her:
https://github.com/certbot/certbot/blob/d2440133559ea1df864ab68abc2bc08a724c0df1/certbot/certbot/_internal/plugins/manual.py#L197

but I can't get full domain with wildcard, because  `achalls` variable contains domains with already removed wildcards...

Could you help me, how can I get all domain list with wildcard asked with -d, in this script manual.py from certbot ?

Edit **TLDR;**
How can I pass this domains list
https://github.com/certbot/certbot/blob/a42cffc3517776e53df3750ce8c981db67f029e5/certbot/certbot/_internal/main.py#L126
in manual.py ?

Thxs

Pascal B

**Comment by alexzorin** [comment]
Could you please explain why it would be helpful?

Hooks only have knowledge about challenge domains, which are not the same as certificate domains. There is no guarantee that challenge domains are the same as certificate domains, which is precisely the case when a wildcard domain was requested on the certificate.

When you order a certificate for `[example.com, *.example.com]`, you will get two challenges for `[example.com]` and as a result, you need to create two TXT records for `_acme-challenge.example.com`.

**Comment by Pbast** [comment]
Because of this
I try to fix this issue:
https://community.letsencrypt.org/t/problem-with-wildcard-certificate-renewal-example-com-example-com-in-one-cert/68556 I didn't understand how he fix it anyway...

In my –manual-auth-hook script, I need to know which record DNS I create. It is required by our custom DNS provider to find where I must create the _acme-challenge record.

By the way, when ordering a unique cert for [example.com, *.example.com], what is the workflow ?
manual-auth-hook script create 2 TXT records and certbot check and create cert, or manual-auth-hook script create first TXT record, cerbot check and manual-auth-hook script  create second record and certbot check and finaly create cert ?
Because in one case, there are conflict with acme-challenge.example.com record.

**Comment by alexzorin** [comment]
>Because in one case, there are conflict with acme-challenge.example.com record.

There is no conflict. In DNS, it is perfectly common and valid to create two DNS records of the same type on one DNS name.

So the workflow is:

1. You order a certificate for `[example.com, *.example.com]`
2. Your authentication hook is called for `example.com` with `CERTBOT_DOMAIN=example.com` `CERTBOT_TOKEN=abc` 
3. Your authentication hook is called for `example.com` with `CERTBOT_DOMAIN=example.com` `CERTBOT_TOKEN=def` 

4. After the hooks have completed, your DNS zone looks like this:

       _acme-challenge.example.com.               300     IN      TXT     "abc"
       _acme-challenge.example.com.               300     IN      TXT     "def"

5. Certbot submits the challenges and the certificate is created.

6. Certbot calls the cleanup hook in the same fashion as (2) and (3).

I think this feature request is likely based on a misunderstanding of how the DNS challenge works. If you need further help, I recommend asking on https://community.letsencrypt.org/.

**Comment by Spudz76** [comment]
```
Renewing an existing certificate for *.example.com and example.com
Performing the following challenges:
dns-01 challenge for example.com
dns-01 challenge for example.com
Waiting 10 seconds for DNS changes to propagate
Waiting for verification...
Challenge failed for domain example.com
dns-01 challenge for example.com
Cleaning up challenges
Failed to renew certificate example.com with error: Some challenges have failed.
```

PowerDNS doesn't appear to support multiple TXT or something else is broken.  Running renew again and again eventually works, but only when it decides to make only a single record per domain or subdomain.

Very annoying as far as cronjob ever being successful.
