### ISSUE TITLE
Vultr API needs upgrade to v2

### ISSUE THREAD

**Issue by cliffjao** [certbot/certbot#9667]
When using certbot as part of swag (https://github.com/linuxserver/docker-swag) on Vultr, I get the following error message:

`Failed to add TXT record for "REDACTED.com": Error fetching DNS domains list: 503 - Sorry, all newly created accounts are forbidden from using API v1, all other accounts are able to use this deprecated API until June 30, 2023 at which point Vultr API v1 will be sunset. Please use API v2.`

**Comment by osirisinferi** [comment]
Certbot does not have a Vultr plugin. I think it's probably better to file a bug report with swag.

**Comment by alexzorin** [comment]
Thanks. Reaching out to the author of the affected plugin is the right course of action here.
