### ISSUE TITLE
rfc2136 broken with hidden primary setups

### ISSUE THREAD

**Issue by benweeks2** [certbot/certbot#9671]
https://github.com/certbot/certbot/pull/9408 has caused certbot to fail in hidden master setups because the SOA query fails due to an unknown TSIG key.

For security reasons, keys are only stored on a hidden primary, hence the secondary rejects the TSIG signed dns query.

suggest this commit be reverted or logic added to make TSIG signatures on DNS queries optional.
Fundamentally, TSIG is only required on DDNS updates (and zone transfers)

**Comment by alexzorin** [comment]
What if we put a retry on the SOA query, without authentication?

**Comment by benweeks2** [comment]
I think retrying the query without TSIG is a not a good solution because:

1. Spurious NotAuth traffic and log entries are a hindrance to administration and troubleshooting;
2. It is entirely unclear to me what purpose this change serves given that BIND has 'in-view' in all supported versions and documentation on how to use it can be found in [Special considerations for multiple views in BIND](https://certbot-dns-rfc2136.readthedocs.io/en/stable/#special-considerations-for-multiple-views-in-bind);
3. If indeed signed queries are a requirement they would only be needed rarely hence this functionality should be optional and disabled by default; and
4. You seem to already have a better thought out implementation in https://github.com/certbot/certbot/pull/9106

**Comment by alexzorin** [comment]
OK, thanks for the feedback.

**Comment by benweeks2** [comment]
I would suggest that https://github.com/certbot/certbot/pull/9408 be simply reverted. It is flawed and unnecessary for the reasons given above.
