### ISSUE TITLE
Warning dns-route53-propagation-seconds deprecated?

### ISSUE THREAD

**Issue by pek77** [certbot/certbot#9674]
Hi team, 

This prompt appeared when I upgraded to 2.5. What is the reason for deprecating this function? Could there be some explanation?

Because I think it will take at least some time for DNS propagation to take effect.

**Comment by osirisinferi** [comment]
Please see the changelog for 2.5.0 here: https://github.com/certbot/certbot/blob/master/certbot/CHANGELOG.md#250---2023-04-04
