### ISSUE TITLE
Certificate not yet due for renewal, return None

### ISSUE THREAD

**Issue by pek77** [certbot/certbot#9675]
Hi Team,

When I use python to renew the certificate without force renew, if the certificate has not expired, renew will not be executed. But `certbot.main.main` also returns None.

May I ask if you can give some more status to represent the success of the renew, or the status of renew was not performed because the certificate has not expired

**Comment by alexzorin** [comment]
I don't think we'd do this. `certbot.main.main` is not intended to be a public API. Use `--deploy-hook` to be notified of renewals.
