### ISSUE TITLE
typing-extensions not found on Windows

### ISSUE THREAD

**Issue by carlosjourdan** [certbot/certbot#9682]
## My operating system is (include version):

Windows 10

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

https://dl.eff.org/certbot-beta-installer-win_amd64.exe

## I ran this command and it produced this output:

certbot produces the following error

←[31mAn unexpected error occurred:←[0m
←[31mpkg_resources.DistributionNotFound: The 'typing-extensions>=3.7.4' distribution was not found and is required by typing-inspect←[0m

**Comment by alexzorin** [comment]
Does uninstalling and reinstalling Certbot still result in this issue?

I'm unable to reproduce the issue.

You can also try https://github.com/certbot/certbot/releases/download/v2.5.0/certbot-beta-installer-win_amd64_signed.exe.
