### ISSUE TITLE
New Test Type: Old Config Files against Modern Certbot Functionality

### ISSUE THREAD

**Issue by zoracon** [certbot/certbot#9686]
Related to: https://github.com/certbot/certbot/issues/9635

Future Preventative measure:
1. A collection of older renewal config files to start
2. A mechanism to collect & cache renewal config file as it changes
3. An integration test built to test modern Certbot functionality against these older renew config files

**Comment by adferrand** [comment]
This seems to be done already as part of #9636 (diff: https://github.com/certbot/certbot/pull/9636/files#diff-5b499a0e629a96ac16cd6d3a937f18070292b19b3a1e9659f2970b8cd58d4df4), right?
