### ISSUE TITLE
Please reopen #8921 Unable to find pre-hook command net in the PATH. [Windows]

### ISSUE THREAD

**Issue by ddelcastilloRSMG** [certbot/certbot#9698]
### **My operating system is (include version):**
Windows Server 2019

### **I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):**
Windows installer

### **certbot Version** 
2.6.0

### **I ran this command and it produced this output:**
certbot renew --dry-run --pre-hook "net stop Nginx" --post-hook "net start Nginx"

### **Certbot's behavior differed from what I expected because:**
I returns the following error:
```
Unable to find pre-hook command net in the PATH.
(PATH is C:\Program Files\PowerShell\7;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Amazon\cfn-bootstrap\;C:\Program Files\PowerShell\7\;C:\Program Files\Certbot\bin;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\Certbot\Python)
See also the --disable-hook-validation option.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile C:\Users\ADMINI~1\AppData\Local\Temp\2\certbot-log-opu91qqr\log or re-run Certbot with -v for more details.
```
### **Link to previous issue**
#8921

**Comment by alexzorin** [comment]
https://github.com/certbot/certbot/issues/8215 is still open. Closing as duplicative.
