### ISSUE TITLE
clarify --preconfigured-renewal documentation

### ISSUE THREAD

**Issue by calestyo** [certbot/certbot#9699]
Hey.

There seems to be no documentation in the manpage or `--help` about the option `--preconfigured-renewal`.<br>
That should perhaps be added, but apart from that...

The only reference I could really find (except for the code locations) is:
https://eff-certbot.readthedocs.io/en/stable/packaging.html#notes-for-package-maintainers
where it seems package maintainers are advised to generally include it in `cli.conf`.

I wondered... if this is really meant for general inclusion therein, why not simply defaulting it to be enabled?<br>
Or is it rather meant to be **only** included... if the `certbot` is invoked for automatic renewal (via e.g. cron job or systemd timer)?

In that case, wouldn't it be a better advise to only include the option in such cron job / systemd timer - and not `cli.conf` where it would also be used for any manual invocation?

Thanks,
Chris.

**Comment by osirisinferi** [comment]
As far as I know, the only thing that option does is change/add a specific remark regarding the fact that auto-renewal has already been enabled when a certificate has been issued. But that remark should obviously ONLY be included if the package maintainer *actually* added a systemd timer/cronjob entry with their Certbot package.

So this option is:

1) not for users but indeed for maintainers
2) not to be *always* enabled, but conditionally

**Comment by calestyo** [comment]
> As far as I know, the only thing that option does is change/add a specific remark regarding the fact that auto-renewal has already been enabled when a certificate has been issued

That's what it looked like, when I searched through the code.

Okay... then the best way to go would actually be:<br>
Use the option, but only when the timer/cronjob is actually enabled... cause even if the packager does ship such timer/cronjob... it's perfectly valid that the admin disables it.

But that in turn wouldn't really work currently... cause `certbot` would need a way to check whether auto renewals are enabled or not, e.g. via some callout script or so.

**Comment by alexzorin** [comment]
> it's perfectly valid that the admin disables it.

That's fine. The admin is aware they disabled the timer, which means they've taken the time to consider the effect.

The flag serves the purpose of telling the uninformed user about what they can expect for renewal and whether they need to intervene.

A user who installed Certbot from `pip` or `brew` will always see this message:

>The certificate will need to be renewed before it expires. Certbot can automatically renew the certificate in the background, but you may need to take steps to enable that functionality. See https://certbot.org/renewal-setup for instructions.

... even if they already followed the instructions the last time and set up a cronjob. That's also fine, it doesn't need to perfectly reflect the state of their system. It's just there to set expectations about what will happen with renewal.

**Comment by leegarrett** [comment]
I think the flag should still be documented. In Debian for example during dist-upgrade this config option was showed to me to be included in the config. Without documentation it's not clear from the sysadmin point of view what it does.
