### ISSUE TITLE
When using Ansible:   CertUtil: -MergePFX command FAILED: 0x80090016 (-2146893802 NTE_BAD_KEYSET) 

### ISSUE THREAD

**Issue by mademan5** [certbot/certbot#9704]
Hi Team,

We can run this command manually, but once trying with Ansible we receiving the error below.
I was already trying many versions, but could not solve it.
Want to use Certbot with Ansible on Windows hosts. Unfortunately when we want to merge the certificate into PFX, we receiving this issue. 

"cmd": "certutil -f -p "password,password\" -mergepfx server.pem server.pfx"

"stdout_lines": [
        "CertUtil: -MergePFX command FAILED: 0x80090016 (-2146893802 NTE_BAD_KEYSET)",
        "CertUtil: Keyset does not exist"
        
       
"src": "C:\Program Files\acme\certs\live\servername.com\fullchain.pem",
"dest": "C:\Program Files\Certbot\server.pem"  
"src": "C:\Program Files\acme\certs\live\servername.com\privkey.pem",
"dest": "C:\Program Files\Certbot\server.key"

**Comment by alexzorin** [comment]
Hi,

This is not the kind of question we can help with, on this issue tracker. https://community.letsencrypt.org/ might be a better place to ask.

I'm not familiar with `certutil`, but this OpenSSL command could help:

    openssl pkcs12 -export -out server.pfx -inkey C:\Program Files\acme\certs\live\servername.com\privkey.pem -in C:\Program Files\acme\certs\live\servername.com\cert.pem -certfile C:\Program Files\acme\certs\live\servername.com\chain.pem
