### ISSUE TITLE
The signature files disappeared from PyPI

### ISSUE THREAD

**Issue by MeggyCal** [certbot/certbot#9707]
Hi, I am a packager in SUSE and I am trying to update the whole certbot ecosystem to 2.6.0. I was on a longer leave, so the last version in openSUSE was 1.31.0. We used to package also the signatures for certbot and acme (the *.tar.gz.asc files), but now I am not able to download them from PyPI from the usual place anymore, not even for the older versions. It seems they have been dropped.

I just wanted to ask: is this intended? I couldn't find any notice in the changelog. There is no problem in packaging Certbot without the signatures, I just wanted to let you know in case it is something unexpected.

**Comment by osirisinferi** [comment]
The signature files have been dropped from the PyPi website when they migrated to the software backend Warehouse. See https://pyfound.blogspot.com/2018/03/warehouse-all-new-pypi-is-now-in-beta.html

Luckily you can still download the `.asc` files manually by simply adding the `.asc` to the extension as explained here: https://warehouse.pypa.io/api-reference/legacy.html#get--simple--project--

**Comment by alex** [comment]
Be aware there's a plan to remove PGP support from PyPI entirely: https://blog.pypi.org/posts/2023-05-23-removing-pgp/

**Comment by MeggyCal** [comment]
Thanks a lot! That fully answered my question, I will close this issue now.
