### ISSUE TITLE
ImportError: cannot import name 'standalone' from 'certbot.plugins' 

### ISSUE THREAD

**Issue by cgxxv** [certbot/certbot#9720]
## My operating system is (ubuntu 22.04):
<img width="722" alt="image" src="https://github.com/certbot/certbot/assets/6456505/761907a1-b813-468b-a909-9cc73e0b09fe">

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
follow this docs: https://certbot.eff.org/instructions?ws=haproxy&os=ubuntufocal

## I ran this command and it produced this output:
certbot --help
<img width="1387" alt="image" src="https://github.com/certbot/certbot/assets/6456505/a8a08c8b-1293-40ee-8fc8-27b415e7d770">

## Here is a Certbot log showing the issue (if available):
<img width="1891" alt="image" src="https://github.com/certbot/certbot/assets/6456505/bc465fbb-5934-4f32-95cc-016f33e5c682">

**Comment by osirisinferi** [comment]
The instructions you've linked show Certbot being installed using snap. However, the screenshots show Certbot located in `/usr/local/lib/python3.10/`, which is not the location of the snap distributed Certbot. Looks more like `pip` to me.

Also, Certbot doesn't distribute a `certbot-haproxy` plugin. How did you install that one?

**Comment by alexzorin** [comment]
Yes, please continue this conversation on the community forums.
