### ISSUE TITLE
acme v1.23.0 is incompatible with pyopenssl>=23.2.0 on python 3.6

### ISSUE THREAD

**Issue by jvanasco** [certbot/certbot#9722]
This took a bit of debugging to figure out.

pyopenssl v23.2.0 introduced a backwards compatible change[, in which invalid versions create errors.](https://www.pyopenssl.org/en/latest/changelog.html#id1)

this makes it incompatible with acme, [due to a line in crytpo_util.py invoking an invalid version](https://github.com/certbot/certbot/blob/v1.23.0/acme/acme/crypto_util.py#L252)

          csr.set_version(2)

The traceback is:

    File "/_venv_py36/lib/python3.6/site-packages/acme/crypto_util.py", line 252, in make_csr
      csr.set_version(2)
    File "/_venv_py36/lib/python3.6/site-packages/OpenSSL/crypto.py", line 1017, in set_version
      "Invalid version. The only valid version for X509Req is 0."
    ValueError: Invalid version. The only valid version for X509Req is 0.

This can break legacy systems that run py3.6 [as the pyopenssl version does not have a maximum pinning](https://github.com/certbot/certbot/blob/v1.23.0/acme/setup.py#L11)

A potential fix would be release a v1.23.1 that simply adds a max version to setup.py 

    PyOpenSSL>=17.3.0 and pyOpenSSL<=23.1.0

However, no fix is likely needed as anyone encountering this issue will likely now find this Issue and be able to install the version themselves on the commandline:

    pip install "pyopenssl==23.1.0"

So the existence of this issue should probably be enough to close it.

**Comment by alexzorin** [comment]
This would be fixed by https://github.com/certbot/certbot/pull/9717, but I'm stuck with a silly macOS Augeas issue.

If somebody wants to submit a separate PR to set the version to `0`, I'll approve and merge that.

**Comment by alexzorin** [comment]
The X509Req thing is now fixed in `master`, and Python 3.6 is otherwise no longer supported by this project, so I'm going to close the issue.
