### ISSUE TITLE
certbot failure when parsing apache2 configuration containing loadbalancer

### ISSUE THREAD

**Issue by iancroberts** [certbot/certbot#9726]
After we added apache2 loadbalancer configuration into the config file, certbot fails.  Apache2ctl configtest says everything is ok and apach2 is working as expected with this configuration.

## My operating system is (include version):
Ubuntu 20.04.5 LTS

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
Snap

## I ran this command and it produced this output:
certbot renew --dry-run
2023-07-04 12:35:49,091:DEBUG:certbot._internal.plugins.disco:Other error:(PluginEntryPoint#apache): There has been an error in parsing the file /etc/apache2/sites-enabled/002.conf on line 42: Syntax error
Traceback (most recent call last):
  File "/snap/certbot/3024/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 111, in prepare
    self._initialized.prepare()
  File "/snap/certbot/3024/lib/python3.8/site-packages/certbot_apache/_internal/configurator.py", line 388, in prepare
    self.parser.check_parsing_errors("httpd.aug")
  File "/snap/certbot/3024/lib/python3.8/site-packages/certbot_apache/_internal/parser.py", line 121, in check_parsing_errors
    raise errors.PluginError(msg)

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

        ProxyHCExpr check1 {hc('body') !~ /Initializing/}    ***** this is line 42

        <Proxy balancer://prtg-backend>
                BalancerMember https://server1.fqdn hcmethod=GET hcexpr=check1 hcuri=/index.htm hcinterval=5
                BalancerMember https://server2.fqdn hcmethod=GET hcexpr=check1 hcuri=/index.htm hcinterval=5 status=+H
        </Proxy>
        ProxyPass / balancer://prtg-backend/
        ProxyPassReverse / balancer://prtg-backend/

As a workaround I just commend out these lines and run certbot manually.

**Comment by alexzorin** [comment]
I think what Certbot's parser doesn't like is the enclosing curly brackets `{` and `}`. To fix this, some changes would need to be made to the [Augeas lens](https://github.com/certbot/certbot/blob/4fc4d536c1acc65646189c5b5aaf02aaa88c3f4a/certbot-apache/certbot_apache/_internal/augeas_lens/httpd.aug#L153-L184).

Playing around myself, I noticed that the brackets enclosing the expression can be substituted for double quotes:

    ProxyHCExpr check1 "hc('body') !~ /Initializing/"

I am satisfied that a workaround is possible here.
