### ISSUE TITLE
letsencrypt requires root for "plugins" command, Manual Authenticator, generic plugins

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#973]
Since https://github.com/letsencrypt/letsencrypt/pull/843 was not pulled in, we need ways of allowing people to run the client without root for the following cases:
- `letsencrypt plugins`, possibly other subcommands
- `letsencrypt -a manual auth` or anything else using Manual Authenticator: paranoid people don't want to run our code as `sudo` - we should make it easy for them to do that
- in general, plugins might not require `sudo` at all: #496 is an example, but we can't anticipate for what reasons 3rd party plugins would not require `root`, so we need a generic solution.

Assigning to @pde.

**Comment by schoen** [comment]
Most of these things now work *in some circumstances*, but definitely not in all circumstances. I think #3079 supersedes this as more specific for the remaining problems, so I'll close this issue in favor of that one.
