### ISSUE TITLE
Wrong error message "Incorrect TXT record" while doing DNS challenge for wildcard cert

### ISSUE THREAD

**Issue by konstantin83** [certbot/certbot#9741]
Hey. I'm trying to get a wildcard certificate with certbot through DNS confirmation.
`certbot --manual --agree-tos --preferred-challenges dns certonly --server https://acme-v02.api.letsencrypt.org/directory -d *.mydomain.ru -d mydomain.ru`

I get the first task:
```
Please deploy a DNS TXT record under the name:

_acme-challenge.mydomain.ru.

with the following value:

************
```
Than make a DNS TXT record at CloudFlare with above value. Than wait for several minutes and press Enter to go on.

Then I get the second task with another value, let's say `%%%%%%`. Change the needed DNS TXT record to this new value, also wait a couple of minutes and again press Enter.

And then I get an error message saying that: ```Certbot failed to authenticate some domains (authenticator: manual). The Certificate Authority reported these problems:
  Domain: mydomain.ru
  Type:   unauthorized
  Detail: Incorrect TXT record "%%%%%%" found at _acme-challenge.mydomain.ru```

Here's the screenshot, where you can see that value in error and value in second task and the value assumed to be incorrect in error message are exactly the same.

<img width="658" alt="certbot" src="https://github.com/certbot/certbot/assets/13274062/3bd28218-3b3b-4b8d-9043-7c2c10b650b1">

How do I fix this behavior?

**Comment by alexzorin** [comment]
Both records have to exist at the same time. Please post https://community.letsencrypt.org/ if you have further questions about the process.

**Comment by arekm** [comment]
(note for anyone who lands here trying to figure out "Incorrect TXT record" real meaning)

Server side checks if any of txt records (found via dns query) match expected sha256 key authorization.
If no txt record matches then server returns "Incorrect TXT record" with information about txt records found in dns.

So if it returns "Incorrect TXT record"  it means that it found txt records (in dns) but these were not matching expected sha256 key authorization server wanted to check.

https://github.com/letsencrypt/boulder/blob/46013eaec0fcefcc6e2eb9984dfa2fc0c640bd45/va/dns.go#L101-L141
