### ISSUE TITLE
certbot with plugin certbot-dns-standalone works with verb certonly but not with verb renew

### ISSUE THREAD

**Issue by md-admin** [certbot/certbot#9742]
I've already opened a bug with the plugin author at: [https://github.com/siilike/certbot-dns-standalone/issues/23](url) and he suggested to open a bug report for certbot itself.

## My operating system is (include version): 

openSUSE Tumbleweed (with all current updates)

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc): 

`zypper` 
```
S  | Name                         | Type    | Version      | Arch   | Repository
---+------------------------------+---------+--------------+--------+-----------
i+ | python311-certbot            | package | 2.6.0-1.2    | noarch | twI.oss
i  | python311                    | package | 3.11.4-1.1   | x86_64 | twI.oss
i  | python311-pip                | package | 23.1.2-2.2   | noarch | twI.oss

```

## I ran this command and it produced this output: 

`certbot renew`

**certbot.errors.AuthorizationError: None of the preferred challenges are supported by the selected plugin**

## Certbot's behavior differed from what I expected because: 

The error only occurs for our wildcard certificate when something like: `certbot renew -v --dry-run` is run or from /etc/crontab: `certbot renew`. If I use: 

`certbot certonly -v --dry-run --config /etc/letsencrypt/cli.ini --preferred-challenges dns-01 --authenticator dns-standalone --dns-standalone-port=53 --dns-standalone-address=#.#.#.# --domain "domain.tld,*.domain.tld"`

from the commandline everything is carried out without any error (even without --dry-run).

## Here is a Certbot log showing the issue (if available): 

[le.log.zip](https://github.com/certbot/certbot/files/12250237/le.log.zip)

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring: 

`n/a`

**Comment by alexzorin** [comment]
> 2023-08-02 15:25:02,989:DEBUG:certbot._internal.cli:Var pref_challs=http-01 (set by user).

It looks like you are probably setting `preferred-challenges` in `/etc/letsencrypt/cli.ini`. This has the highest possible precedence and will affect all certificates. It's not compatible with a certificate that is configured to renew via the DNS challenge.

Get rid of it and everything should work as expected. You might also be able to set it like this, but I'm not sure:

    preferred-challenges=http,dns

If you have a mix of HTTP and DNS based challenges, then you cannot force everything to the HTTP challenge, which is what your current setting does.

Closing as invalid.

**Comment by md-admin** [comment]
> It looks like you are probably setting `preferred-challenges = http-01` in `/etc/letsencrypt/cli.ini`. This has the highest possible precedence (other than setting `--preferred-challenges` on the CLI, which is exactly why `certonly` worked for you) and will affect all certificates.

Thank you for giving this hint. I removed that setting and tried `certbot renew  -v --dry-run` with a positive result:

```
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/domain.tld.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Certificate not due for renewal, but simulating renewal for dry run
Plugins selected: Authenticator dns-standalone, Installer None
Simulating renewal of an existing certificate for domain.tld and *.domain.tld
Performing the following challenges:
dns-01 challenge for domain.tld
dns-01 challenge for domain.tld
Waiting 0 seconds for DNS changes to propagate
Waiting for verification...
Cleaning up challenges
Dry run: skipping deploy hook command: /etc/letsencrypt/renewal-hooks/deploy/notifyByMail

```
