### ISSUE TITLE
HTTP 400 “Bad Request” error using certbot-dns-linode

### ISSUE THREAD

**Issue by inspector-g** [certbot/certbot#9745]
I posted this to the Let's Encrypt community forum yesterday, but it appears that either a) Linode might have made breaking changes to their API, and/or b) certbot might need to update their ​usage of the API (if perhaps Linode does not revert). I will include the basics from the forum post here for convenience, but [have a look at the full post for full context/logs](https://community.letsencrypt.org/t/http-400-bad-request-error-using-certbot-dns-linode/203134).

Before today I have successfully used Let's Encrypt with certbot on Ubuntu with the Linode DNS plugin, but now (on a new installation) I am receiving an HTTP 400 error.

This is on Ubuntu 22.04 with certbot 2.6.0, and the Linode API key has R/W access to domains. These are the commands I have run to setup the environment and request the certificate.

```
sudo vi /root/.linode_api.ini
# Added following lines (uncommented):
# dns_linode_key = <key redacted>
# dns_linode_version = 4
sudo chmod 600 /root/.linode_api.ini

sudo snap install core; sudo snap refresh core
sudo snap install --classic certbot
sudo ln -s /snap/bin/certbot /usr/bin/certbot
sudo snap set certbot trust-plugin-with-root=ok
sudo snap install certbot-dns-linode

sudo certbot certonly --dns-linode --dns-linode-credentials /root/.linode_api.ini --dns-linode-propagation-seconds 180 -d everythingcode.net -d "*.everythingcode.net"
```

Which gives the following output:

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-linode, Installer None
Requesting a certificate for *.everythingcode.net
Performing the following challenges:
dns-01 challenge for everythingcode.net
Cleaning up challenges
Error adding TXT record: 400 Client Error: BAD REQUEST for url: https://api.linode.com/v4/domains/2675616/records
```

Thanks!

**Comment by inspector-g** [comment]
Looks like Linode has fixed this with reverting the recent breaking change.

**Comment by osirisinferi** [comment]
As it looks like this is more a Linode API change issue than something related to Certbot, I'm going to close this issue as fixed.

Also, any API related changed (beside the API URI) would probably need to be addressed in the [`dns-lexicon`](https://github.com/AnalogJ/lexicon) library, which is used by the Certbot Linode DNS authenticator and handles all the API communication.
