### ISSUE TITLE
Ability to combine HTTP and DNS challenges in a single certificate?

### ISSUE THREAD

**Issue by catharsis71** [certbot/certbot#9751]
Currently it's impossible to do something like this:

```certbot certonly --dry-run --dns-cloudflare -d example.com --apache -d example.net```

There are legitimate scenarios where only DNS authentication can be used for example.com, and only HTTP authentication can be used for example.net, but a person would still prefer to create a single certificate for both rather than two certificates.

[acme.sh can do this](certbot certonly --dry-run --dns-cloudflare -d example.com --apache -d example.net) and possibly other ACME clients

is there any possibility of adding this feature to certbot?

**Comment by osirisinferi** [comment]
Please see the [Certbot user guide about combining plugins](https://eff-certbot.readthedocs.io/en/stable/using.html#combining-plugins).

**Comment by bmw** [comment]
i agree that this would be nice, but it'd require significant rearchitecturing of certbot and it doesn't seem like this feature would get much use so we're closing this as wontfix

i'm sure that's not what you want to hear and i'm sorry about that, but it's the reality of our priorities and bandwidth right now
