### ISSUE TITLE
Please bring back DNS challenges on nginx plugin.

### ISSUE THREAD

**Issue by altrgeek** [certbot/certbot#9757]
certbot version:  latest/stable:  2.6.0. (snap)

certbot http challenge never worked for me that is why I use snap version. now snap version drops support for DNS challenges on nginx plugin. Is there any way to make it work using dns challenges with auto deploy certificates on nginx vhosts?

**Comment by osirisinferi** [comment]
I don't understand: the nginx authenticator never supported DNS challenges?

You can combine the nginx *installer* with a DNS *authenticator* plugin, but that has always been the case, before and after snap.

**Comment by altrgeek** [comment]
It was a missing DNS entry.
