### ISSUE TITLE
Please provide a method to initialize a correct certbot directory structure from a set of existing certificates.

### ISSUE THREAD

**Issue by dunkelziffer** [certbot/certbot#9760]
## My operating system is (include version):

Ubuntu 22.04

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

apt

## Preface: My use cases

My use cases are the following:

Use case A:
- I backed up the last valid set of certificates from a server
- I reinstalled the server
- I want to re-deploy my certs to the server
- I want certbot to be able to successfully renew them in the future

Use case B:
- I add a new site to an existing server
- I want to start nginx with snakeoil certificates
- I want to run certbot immediately afterwards to get actual certificates

Why am I having these use cases:
- reason for use case A: I am trying to automate my server setup. As I am self-teaching, I often experiment and then wipe my server afterwards. To not run into the Let's Encrypt rate limiting, I backup my certs and want to continue using them after reinstalling the server again.
- reason for use case B: I want to add a website under a new subdomain 2 to an existing website under subdomain 1, withouth interrupting the the service of the site at subdomain 1. As far as I know, it is not possible to have subdomain 1 on SSL and subdomain 2 without SSL. Therefore I want to use snakeoil cert during the setup of subdomain 2 so I can successfully restart nginx with SSL on all domains. Then, I want to renew the cert for subdomain 2 immediately afterwards. I am not using wildcard certificates, because it's difficult to automate the required DNS zone changes.

For both of these use cases I want to deploy an existing set of certificates onto my server and then tell certbot to renew them.

## I ran this command and it produced this output:

What I tried:

Attempt 1:
- I put my existing certs under `/etc/letsencrypt/live/{{ domain }}/`
- I ran `certbot certonly --webroot -d {{ domain }} -m {{ email }} -w /va
r/www/_letsencrypt -n --agree-tos --force-renewal` (or alternatively wait until `certbot renew -q` gets run by a cronjob)
- It failed with `live directory exists for {{ domain }}`

Attempt 2:
- I put my existing certs under `/etc/letsencrypt/archive/{{ domain }}/`
- I symlinked to them from `/etc/letsencrypt/live/{{ domain }}/`
- I ran `certbot certonly --webroot -d {{ domain }} -m {{ email }} -w /va
r/www/_letsencrypt -n --agree-tos --force-renewal`
- It failed with `archive directory exists for {{ domain }}`

## Certbot's behavior differed from what I expected because:

There seems to be no method of initializing a correct directory structure with existing certificates while telling certbot that it's OK to renew them and that it's OK that the correct file structure is partially in place already.

I am fine with this "renewal of externally provided certificates" not taking place silently. It's probably for the better. But I want a feature to explicitly tell certbot to accept a set of certificates.

Potential usage:

- I put my existing certs under `/etc/letsencrypt/live/{{ domain }}/`
- I run `certbot import -d domain`
- certbot creates a valid directory structure around these certificates
- I run `certbot certonly --webroot -d {{ domain }} -m {{ email }} -w /va
r/www/_letsencrypt -n --agree-tos --force-renewal`  (or alternatively wait until `certbot renew -q` gets run by a cronjob)
- It works

## Here is a Certbot log showing the issue (if available):

see above (Attempt 1 and Attempt 2) for the error messages.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

```
	ssl_certificate /etc/letsencrypt/live/{{ domain }}/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/{{ domain }}/privkey.pem;
	ssl_trusted_certificate /etc/letsencrypt/live/{{ domain }}/chain.pem;
```

## Known workarounds

I could simply put my existing certificates in a different directory. Drawbacks:
- I would have to adjust the paths in my nginx config as soon as certbot retrieves the first set of new certificates. This would be doable in use case B as the first renewal is part of the initial server setup here. I could automate that. However, in use case A, there is a time gap between deploying the backup certs and the first certbot run. I would e.g. need to modify my nginx config as a certbot post renewal hook. That seems pretty ridiculous and doesn't look like a best practice.

**Comment by githubRover** [comment]
> Use case A:
> I backed up the last valid set of certificates from a server

Why can't you just backup the whole /etc/letsencrypt folder structure preserving symlinks?  At least one key piece is missing (the /renewal folder) which is likely causing Certbot to think it is a fresh cert when it is not.  The renewal conf file is an essential part of the Certbot "database".

> Use case B:
> As far as I know, it is not possible to have subdomain 1 on SSL and subdomain 2 without SSL.

nginx supports server blocks in any combination.  You just make a new server block for subdomain 2 with a listen on port 80.  You then run Certbot for subdomain 2 which gets a cert with just that name in it.  If using --nginx plug-in Certbot will create the server block for HTTPS (port 443) otherwise you then code that server block yourself.

**Comment by dunkelziffer** [comment]
> Use case B:
> As far as I know, it is not possible to have subdomain 1 on SSL and subdomain 2 without SSL.

I think I managed to resolve this by `removing the whole server block on port 443` instead of just `turning off SSL for port 443, but leaving the remaining block in place`.

Consider this use case solved.

> Use case A:
> I backed up the last valid set of certificates from a server

I want my individual deployments to be as decoupled and independent as possible. I could backup the whole certbot folder, but the restore would need to happen one-by-one for each deployment individually to ensure this decoupling. So I can't simply restore the certbot folder as a whole.

I would have to pick-and-choose the correct files from my backup. Yes, I can automate that, but that's pretty cumbersome and additionally forces me to encode knowledge about certbots internal file structure into my playbooks.

I would not consider this use case solved.

For now, I will try to simply backup the renewal conf file in addition to my certs and hope that this will suffice. I still think an `import` utility would be a nice feature.

I took a look at the code and it looks like it should be possible to implement that with minor changes: https://github.com/certbot/certbot/blob/cc359dab469281fec10357c81b9dd2d4e06290b3/certbot/certbot/_internal/storage.py#L1035C50-L1035C55

Outline of `certbot import -d {{ domain }}` command:
- read `bytes` of all certs from the `live` directory (or a given path)
- pass those into `new_lineage` as arguments.

Required changes to `new_lineage`:
- don't fail, if the `live`directory already exists
- I'm not sure, how `os.symlink` behaves, if a file exists where the symlink should be. Potentially the imported cert would need to be deleted before creating the symlink

That should be it. Maybe I'm too naive and it's more complicated, but if not, this might be a nice convenience feature for certbot.

**Comment by dunkelziffer** [comment]
Update: yes, putting the renewal file into place seems sufficient.

Do you know, if the index of the certs in the archive folder is of any significance or can I just reset those back to `1` when restoring?

**Comment by githubRover** [comment]
The symlink in /live/ points to the most recent set in /archive/

Starting with Certbot 2.3 fewer previous copies are retained in /archive/
See

https://github.com/certbot/certbot/blob/master/certbot/CHANGELOG.md#changed-4

I don't recall what version is in apt for Ubuntu 22 but see below for snap install which is recommended
https://certbot.eff.org/
