### ISSUE TITLE
dns-cloudflare fails token auth when using python-cloudflare above 2.8.15

### ISSUE THREAD

**Issue by snk-nick** [certbot/certbot#9768]
First ran into this when using the `certbot/dns-cloudflare` docker image and attempting to use a token rather than an API key, the following error occurs when a certificate is requested: 

`Error determining zone_id: 6003 Invalid request headers. Please confirm that you have supplied valid Cloudflare API credentials. (Did you copy your entire API token/key? To use Cloudflare tokens, you'll need the python package cloudflare>=2.3.1. This certbot is running cloudflare 2.11.7)`

The command being run inside the container is:

```
certbot certonly \
    --dns-cloudflare \
    --dns-cloudflare-credentials /cloudflare.ini \
    --agree-tos \
    --no-eff-email \
    -n \
    -m $CLOUDFLARE_EMAIL \
    -d $CLOUDFLARE_DOMAIN_LIST
```

With `/cloudflare.ini`:

`dns_cloudflare_api_token = $CLOUDFLARE_TOKEN`

Couldn't get things working so created a new container using `python:3.11.5-slim` as a base and installing via pip. Same result until I started messing with package versions and found that if I dropped the `python-cloudflare` down to version `2.8.15` the token was accepted no problems (note: only tested latest of each minor release).

Dockerfile:

```
###################################################################################################
# Dockerfile for Certbot / Cloudflare DNS testing
# Author: snk-nick
#  
# Required environment variables:
# CLOUDFLARE_TOKEN: Cloudflare token with appropriate permissions (NOT an API key).
# CLOUDFLARE_EMAIL: Email to register domain with.
# CLOUDFLARE_DOMAIN_LIST: List of domains to register in certbots expected format, eg:
#                         "domain.com"                       - Single domain
#                         "*.domain.com -d test.domain.com"  - Multiple with wildcard
#
# Configured as is it will obtain the certificate then wait 12 hours/attempt a renewal.
###################################################################################################

# Build args
ARG IMAGE=python
ARG TAG=3.11.5-slim

# Package version args
ARG CERTBOT_VERSION=2.6.0
ARG CERTBOT_DNS_VERSION=2.6.0
ARG CLOUDFLARE_VERSION=2.8.15 

# Pull the base image
FROM ${IMAGE}:${TAG}
ENV DEBIAN_FRONTEND=non-interactive

# Init args
ARG CERTBOT_VERSION
ARG CLOUDFLARE_VERSION
ARG CERTBOT_DNS_VERSION

# Install Python packages via pip
RUN pip install --no-cache-dir certbot==${CERTBOT_VERSION} certbot-dns-cloudflare==${CERTBOT_DNS_VERSION} cloudflare==${CLOUDFLARE_VERSION}

# Copy init script
COPY init-certbot.sh /init-certbot.sh
RUN chmod +x /init-certbot.sh

# Runs the init-certbot script on launch then every 12 hours aftwards. 
# Output is logged to /var/log/certbot.log
CMD ["/bin/sh", "-c", "trap exit TERM; while :; do /init-certbot.sh >> /var/log/certbot.log 2>&1; sleep 12h & wait ${!}; done"]
```

`init-certbot.sh`: 

```
#!/bin/sh
# Creates the required .ini file for cloudflare-dns and obtains/renews certificates

# Create the authentication .ini
echo "dns_cloudflare_api_token = $CLOUDFLARE_TOKEN" > /cloudflare.ini
chmod 600 /cloudflare.ini

# Run certbot
certbot certonly \
    --dns-cloudflare \
    --dns-cloudflare-credentials /cloudflare.ini \
    --dns-cloudflare-propagation-seconds 30 \
    --agree-tos \
    --no-eff-email \
    --staging \
    -n \
    -m $CLOUDFLARE_EMAIL \
    -d $CLOUDFLARE_DOMAIN_LIST
```

Did a quick test by installing into a venv using `pip` in a VM and behaviour is identical. Same error message until the python-cloudflare package version is pinned to `2.8.15` and then it works again. 

Final test I rolled the package back in the official image:

```
###################################################################################################
# Dockerfile for Certbot / Cloudflare DNS testing - built off official release.
# Author: snk-nick
#  
# Required environment variables:
# CLOUDFLARE_TOKEN: Cloudflare token with appropriate permissions (NOT an API key).
# CLOUDFLARE_EMAIL: Email to register domain with.
# CLOUDFLARE_DOMAIN_LIST: List of domains to register in certbots expected format, eg:
#                         "domain.com"                       - Single domain
#                         "*.domain.com -d test.domain.com"  - Multiple with wildcard
#
# Configured as is it will obtain the certificate then wait 12 hours/attempt a renewal.
###################################################################################################

# Build arguments
ARG IMAGE=certbot/dns-cloudflare
ARG TAG=v2.6.0

# Package version arguments. 
ARG CLOUDFLARE_VERSION=2.8.15 

# Pull the base image
FROM ${IMAGE}:${TAG}

# Init version args/envs
ARG CLOUDFLARE_VERSION

# Install Python packages via pip
RUN pip install --no-cache-dir cloudflare==${CLOUDFLARE_VERSION}

# Copy init script
COPY init-certbot.sh /init-certbot.sh
RUN chmod +x /init-certbot.sh

# Runs the init-certbot script on launch then every 12 hours aftwards. 
# Output is logged to /var/log/certbot.log
ENTRYPOINT ["/bin/sh", "-c", "trap exit TERM; while :; do /init-certbot.sh >> /var/log/certbot.log 2>&1; sleep 12h & wait ${!}; done"]
```

And it's all working as expected.

Haven't had time to go hunt for the actual bug but I imagine you'll find it a lot faster than me regardless, hope that helps :)

**Comment by osirisinferi** [comment]
I can't reproduce your issue with Cloudflares Python library 2.11.6 installed? It works perfectly with a CF API token here?

**Comment by snk-nick** [comment]
> I can't reproduce your issue with Cloudflares Python library 2.11.6 installed? It works perfectly with a CF API token here.

Is that using the container? My tests on a VM installing via snap did not result in the same problem, only when using the official container or installing via pip.

**Comment by osirisinferi** [comment]
Using `pip`. I've tested multiple versions of the Cloudflare library now, 2.11.7, 2.11.5, 2.11.4, 2.11.3 and 2.10.1 and they all work with my token.

Maybe you just have to roll your API token or something like that? Maybe a typo has been introduced or some other issue at Cloudflares side.

**Comment by snk-nick** [comment]
Every single one of those fails for me in both the official container, the one I built, and a VM installed using `pip`.  I've generated dozens of tokens to test with and they're all valid (tested with curl etc). 

You're using a token right, not a global API key? The key works no problems, it's the API tokens that fail.

**Comment by osirisinferi** [comment]
Yes, an "API Token", *not* a "global API Key". I'm not sure what to say other than I personally can't reproduce it using `pip`.

What I did was:

* `python -m venv certbot`
* `cd certbot && source bin/activate`
* `pip install certbot-dns-cloudflare`
* `certbot certonly --staging --certbot-dns-cloudflare --et-cetera`

Works nicely.

**Comment by snk-nick** [comment]
Interesting, I'm going to run the exact same thing on a VM shortly.

What permissions did you give your token?

**Comment by osirisinferi** [comment]
> What permissions did you give your token?

Only "DNS edit" permissions for a single zone.

**Comment by snk-nick** [comment]
Same as mine then. 

I ran the exact same commands as you and got the same error.

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Account registered.
Requesting a certificate for testingagain.snkdev.au
Error determining zone_id: 6003 Invalid request headers. Please confirm that you have supplied valid Cloudflare API credentials. (Did you copy your entire API token/key? To use Cloudflare tokens, you'll need the python package cloudflare>=2.3.1. This certbot is running cloudflare 2.11.7)
```

Ran `pip install cloudflare==2.8.15` then immediately ran the same exact command, successfully obtained. 

Something does actually occur to me.. which is that I'm 95% certain that all the containers I've been using have a base image of Debian Bookworm, which is my default VM OS. Going to test out another OS real quick.

**Comment by snk-nick** [comment]
No luck there either. Built a container image using python:3.11.5-alpine3.18 to rule out Bookworm being the problem but same behaviour. 

Does the following work for you?

Dockerfile:
```
###################################################################################################
# Dockerfile for Certbot / Cloudflare DNS testing
# Author: snk-nick
#  
# Required environment variables:
# CLOUDFLARE_TOKEN: Cloudflare token with appropriate permissions (NOT an API key).
# CLOUDFLARE_EMAIL: Email to register domain with.
# CLOUDFLARE_DOMAIN_LIST: List of domains to register in certbots expected format, eg:
#                         "domain.com"                       - Single domain
#                         "*.domain.com -d test.domain.com"  - Multiple with wildcard
###################################################################################################

# Build arguments
ARG IMAGE=certbot/dns-cloudflare
ARG TAG=v2.6.0

# Package version arguments. 
ARG CLOUDFLARE_VERSION=2.8.15 

# Pull the base image
FROM ${IMAGE}:${TAG}

# Init version args/envs
ARG CLOUDFLARE_VERSION

# Install Python packages via pip
RUN pip install --no-cache-dir cloudflare==${CLOUDFLARE_VERSION}

# Copy init script
COPY init-certbot.sh /init-certbot.sh
RUN chmod +x /init-certbot.sh

# Runs the init-certbot script on launch, output to stdout
ENTRYPOINT ["/bin/sh", "-c", "/init-certbot.sh"]
```

init-certbot.sh:
```
#!/bin/sh
# Creates the required .ini file for cloudflare-dns and obtains/renews certificates

# Create the authentication .ini
echo "dns_cloudflare_api_token = $CLOUDFLARE_TOKEN" > /cloudflare.ini
chmod 600 /cloudflare.ini

# Run certbot
certbot certonly \
    --dns-cloudflare \
    --dns-cloudflare-credentials /cloudflare.ini \
    --dns-cloudflare-propagation-seconds 30 \
    --agree-tos \
    --no-eff-email \
    --staging \
    -n \
    -m $CLOUDFLARE_EMAIL \
    -d $CLOUDFLARE_DOMAIN_LIST
```

Build commands:
```
docker build --build-arg CLOUDFLARE_VERSION=2.8.15 -t certtest:old .
docker build --build-arg CLOUDFLARE_VERSION=2.11.7 -t certtest:new .
```

The `docker-compose.yml` I'm using for testing:
```
version: '3.9'

services:
  certbot:
      image: ${CERTBOT_IMAGE_NAME:-certtest:new}
      volumes:
        - ssl_certs:/etc/letsencrypt
      environment:
        CLOUDFLARE_TOKEN: "<token>"
        CLOUDFLARE_EMAIL: "email@domain.com"
        CLOUDFLARE_DOMAIN_LIST: "test.snkdev.au"

volumes:
  ssl_certs:
```

Log when using certtest:new
```
$ CERTBOT_IMAGE_NAME=certtest:new docker compose up
[+] Running 3/0
 ✔ Network certbot-cf-dns_default      Created                                                                                             0.1s 
 ✔ Volume "certbot-cf-dns_ssl_certs"   Created                                                                                             0.0s 
 ✔ Container certbot-cf-dns-certbot-1  Created                                                                                             0.0s 
Attaching to certbot-cf-dns-certbot-1
certbot-cf-dns-certbot-1  | Saving debug log to /var/log/letsencrypt/letsencrypt.log
certbot-cf-dns-certbot-1  | Account registered.
certbot-cf-dns-certbot-1  | Requesting a certificate for test.snkdev.au
certbot-cf-dns-certbot-1  | Error determining zone_id: 6003 Invalid request headers. Please confirm that you have supplied valid Cloudflare API credentials. (Did you copy your entire API token/key? To use Cloudflare tokens, you'll need the python package cloudflare>=2.3.1. This certbot is running cloudflare 2.11.7)
certbot-cf-dns-certbot-1  | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
certbot-cf-dns-certbot-1 exited with code 1
```

Log when using certtest:old
```
$ CERTBOT_IMAGE_NAME=certtest:old docker compose up
[+] Running 1/0
 ✔ Container certbot-cf-dns-certbot-1  Recreated                                                                                           0.0s 
Attaching to certbot-cf-dns-certbot-1
certbot-cf-dns-certbot-1  | Saving debug log to /var/log/letsencrypt/letsencrypt.log
certbot-cf-dns-certbot-1  | Requesting a certificate for test.snkdev.au
certbot-cf-dns-certbot-1  | Waiting 30 seconds for DNS changes to propagate
certbot-cf-dns-certbot-1  | 
certbot-cf-dns-certbot-1  | Successfully received certificate.
certbot-cf-dns-certbot-1  | Certificate is saved at: /etc/letsencrypt/live/test.snkdev.au/fullchain.pem
certbot-cf-dns-certbot-1  | Key is saved at:         /etc/letsencrypt/live/test.snkdev.au/privkey.pem
certbot-cf-dns-certbot-1  | This certificate expires on 2023-12-15.
certbot-cf-dns-certbot-1  | These files will be updated when the certificate renews.
certbot-cf-dns-certbot-1  | NEXT STEPS:
certbot-cf-dns-certbot-1  | - The certificate will need to be renewed before it expires. Certbot can automatically renew the certificate in the background, but you may need to take steps to enable that functionality. See https://certbot.org/renewal-setup for instructions.
certbot-cf-dns-certbot-1  | 
certbot-cf-dns-certbot-1 exited with code 0
```

If you get a different behaviour I guess the only thing left is that it's *something* to do with my account. I have no idea what, but.. something.

**Comment by snk-nick** [comment]
Added above test to a repo for ease of use: https://github.com/snk-nick/certbot-cf-dns

**Comment by osirisinferi** [comment]
When I just run `docker run f99cf08369e9` (which is `certtest:new`), it just works :man_shrugging: 

```
osiris@erazer certbot-test $ docker build --build-arg CLOUDFLARE_VERSION=2.11.7 -t certtest:new .
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  4.608kB
Step 1/9 : ARG IMAGE=certbot/dns-cloudflare
Step 2/9 : ARG TAG=v2.6.0
Step 3/9 : ARG CLOUDFLARE_VERSION=2.8.15
Step 4/9 : FROM ${IMAGE}:${TAG}
 ---> f7b45422a6a7
Step 5/9 : ARG CLOUDFLARE_VERSION
 ---> Using cache
 ---> 90e37f79cc6f
Step 6/9 : RUN pip install --no-cache-dir cloudflare==${CLOUDFLARE_VERSION}
 ---> Running in c494bff8867e
Collecting cloudflare==2.11.7
  Downloading cloudflare-2.11.7.tar.gz (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.3/81.3 kB 428.0 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: requests in /usr/local/lib/python3.10/site-packages (from cloudflare==2.11.7) (2.28.2)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/site-packages (from cloudflare==2.11.7) (6.0)
Requirement already satisfied: jsonlines in /usr/local/lib/python3.10/site-packages (from cloudflare==2.11.7) (3.1.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/site-packages (from cloudflare==2.11.7) (4.12.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/site-packages (from beautifulsoup4->cloudflare==2.11.7) (2.4)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.10/site-packages (from jsonlines->cloudflare==2.11.7) (22.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/site-packages (from requests->cloudflare==2.11.7) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/site-packages (from requests->cloudflare==2.11.7) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/site-packages (from requests->cloudflare==2.11.7) (1.26.15)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/site-packages (from requests->cloudflare==2.11.7) (3.1.0)
Building wheels for collected packages: cloudflare
  Building wheel for cloudflare (setup.py): started
  Building wheel for cloudflare (setup.py): finished with status 'done'
  Created wheel for cloudflare: filename=cloudflare-2.11.7-py2.py3-none-any.whl size=74092 sha256=8d8e0c2031abda66e6e05719e2c2dd15caef90c101f7982172c10055a15cea38
  Stored in directory: /tmp/pip-ephem-wheel-cache-oobp4b1m/wheels/e0/b5/dd/5c38b38067b67a5c55f8878ea436d747c122740b3ff88e75b8
Successfully built cloudflare
Installing collected packages: cloudflare
  Attempting uninstall: cloudflare
    Found existing installation: cloudflare 2.11.1
    Uninstalling cloudflare-2.11.1:
      Successfully uninstalled cloudflare-2.11.1
Successfully installed cloudflare-2.11.7
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
Removing intermediate container c494bff8867e
 ---> d7d6a1ca0cbb
Step 7/9 : COPY init-certbot.sh /init-certbot.sh
 ---> a15b735c28b4
Step 8/9 : RUN chmod +x /init-certbot.sh
 ---> Running in e57b2e3755ac
Removing intermediate container e57b2e3755ac
 ---> 65318c8bc51b
Step 9/9 : ENTRYPOINT ["/bin/sh", "-c", "/init-certbot.sh"]
 ---> Running in b4fab51cc3df
Removing intermediate container b4fab51cc3df
 ---> f99cf08369e9
Successfully built f99cf08369e9
Successfully tagged certtest:new
osiris@erazer certbot-test $ docker run f99cf08369e9
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Account registered.
Requesting a certificate for example.com
Waiting 30 seconds for DNS changes to propagate

Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/example.com/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/example.com/privkey.pem
This certificate expires on 2023-12-15.
These files will be updated when the certificate renews.
NEXT STEPS:
- The certificate will need to be renewed before it expires. Certbot can automatically renew the certificate in the background, but you may need to take steps to enable that functionality. See https://certbot.org/renewal-setup for instructions.
osiris@erazer certbot-test $ 
```

Not sure what to say except that I don't think this is a Certbot issue.

**Comment by osirisinferi** [comment]
I didn't get it working unfortunately (couldn't find a way to let the Cloudflare library accept the `mitmproxy` CA cert), but you might be able to use the guide at https://byteplumbing.net/2018/01/inspecting-docker-container-network-traffic/ to capture the different TLS connections to Cloudflare and compare them.

**Comment by snk-nick** [comment]
Well I'm at a loss. I've run this from every possible platform I can, on every OS I have. I downloaded Docker Desktop for Windows and ran it from there and I've got the exact same issue. I created a token in a different account for a different domain then ran it from a laptop I hadn't used for testing connected to a wifi hotspot and I get the same results again. 

I've tapped a few friends to test for me and I'll see the results they get, I just can't understand how I'm getting such consistent failures but you're getting the opposite. 

I've also contacted Cloudflare to see if they have any ideas and I'll look into your suggestion and compare the connections.

**Comment by osirisinferi** [comment]
Maybe someone else has a genius insight, as I just tested using `pip` (which is failing for you) on a different host and that works perfectly too. I even tried it on my Raspberry Pi 4B running an entirely different architecture, OS, Python et cetera. It just works for me?

**Comment by snk-nick** [comment]
Yeah I'm very confused as I just had a friend test it out and they're getting the same results as me. 

We're based in Australia... I can't possibly think how that would matter but I'm running out of variables to try! I'll get some more people to test for me.

**Comment by snk-nick** [comment]
OK, we have an answer! Mahtin over at `python-cloudflare` figured it out: https://github.com/cloudflare/python-cloudflare/issues/172#issuecomment-1729885563

Because I used `CLOUDFLARE_EMAIL` for the API key version of this script both to list the email for Cloudflare and then again to register for notifications from LetsEncrypt for certificate expiries etc I never removed it from the script when I moved it from tokens instead of API keys. 

When I initially suspected environment variables not passing through correctly, the tests I ran were on a system that still had them set.. even though the script was no longer using them the Cloudflare library picked up on the fact that `CLOUDFLARE_EMAIL` was still set and so the behaviour remained. 

I am still baffled at how you didn't get the same error using my tests though. Either way changing from `CLOUDFLARE_EMAIL` to `LE_NOTIFY_EMAIL` has fixed it.

**Comment by osirisinferi** [comment]
Glad you found the issue! I'm sorry to say I cut some corners with the """reproducing""" part and didn't use the `CLOUDFLARE_EMAIL` environment variable. It should have triggered me, as we previously have seen some issues with token vs. key issues. That's on me.

**Comment by Coderomus** [comment]
- Debian GNU/Linux 13 (trixie)
- certbot 4.0.0
- cloudflare 2.20.0
- python3-certbot-dns-cloudflare 4.0.0

I'm using a Cloudflare Account API token allowed to edit zone DNS limited to one zone.

When running this:
```shell
sudo certbot certonly \
    --dns-cloudflare \
    --dns-cloudflare-credentials ~/certbot/cloudflare.ini \
    -d { my domain }
``` 
With this inside `~/certbot/cloudflare.ini`:
`dns_cloudflare_api_key = { api token }`
`dns_cloudflare_email = { my email }`

I'm getting this error message:
`Error determining zone_id: 6003 Invalid request headers. Please confirm that you have supplied valid Cloudflare API credentials. (Did you copy your entire API token/key? To use Cloudflare tokens, you'll need the python package cloudflare>=2.3.1. This certbot is running cloudflare 2.20.0)`

When I tried to change `dns_cloudflare_email` to `le_notify_email` like suggested here https://github.com/certbot/certbot/issues/9768#issuecomment-1730523396 and run it again, I got this error message:
`/home/admin/certbot/cloudflare.ini: dns_cloudflare_email is required when using a Global API Key. (should be email address associated with Cloudflare account)` 

But when running this:
```shell
sudo certbot certonly \
    --dns-cloudflare \
    --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini \
    -d { my email }
``` 
With this inside `/etc/letsencrypt/cloudflare.in`:
`dns_cloudflare_api_key = { api token }`
`dns_cloudflare_email = { my email }`

I'm getting this error message:
`/etc/letsencrypt/cloudflare.ini: dns_cloudflare_email and dns_cloudflare_api_key are not needed when using an API Token`

After removing `dns_cloudflare_email = { my email }` from `/etc/letsencrypt/cloudflare.ini` it worked perfectly.

Only significant difference I can see is a location of `cloudflare.ini` which is `~/certbot/cloudflare.ini` vs `/etc/letsencrypt/cloudflare.ini`. I have no idea why it's behaving this way.
