### ISSUE TITLE
About 2.7.0 release

### ISSUE THREAD

**Issue by chenrui333** [certbot/certbot#9781]
👋 it looks like 2.7.0 did not get marked as latest release, raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/149402

**Comment by bmw** [comment]
This should be fixed soonish. There were some minor tooling problems that prevented us from fully finishing our normal release process yesterday that we're still working on.

**Comment by chenrui333** [comment]
@bmw thanks for confirming it, i will wait a bit then. Cheers!
