### ISSUE TITLE
dnssimple not supported by Lexicon

### ISSUE THREAD

**Issue by CTech-NicholP** [certbot/certbot#9786]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 22.04.3

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
snap

## I ran this command and it produced this output:
`sudo certbot -i nginx --dns-dnsimple --dns-dnsimple-credentials ~/.secrets/certbot/dnsimple.ini -d example.com`

## Certbot's behavior differed from what I expected because:
Received the following error:
Unexpected error determining zone identifier for example.com: This provider (dnssimple) is not supported by Lexicon.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
```
	server {
	server_name portainer.example.com;

	location / {
		proxy_pass https://127.0.0.1:9000;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection keep-alive;
		proxy_set_header Host $host;
		proxy_cache_bypass $http_upgrade;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	 }
	}

	server {
	server_name example.com;

	location / {
		proxy_pass https://127.0.0.1:9001;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection keep-alive;
		proxy_set_header Host $host;
		proxy_cache_bypass $http_upgrade;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	 }
	}
```

**Comment by bmw** [comment]
Thanks so much for taking time to file an issue.

@adferrand, it looks like the provider name in Certbot should be `dnsimple`, not `dnssimple`. I fixed this in https://github.com/certbot/certbot/pull/9787, but it looks like [we had `dnssimple` before which supposedly worked](https://github.com/certbot/certbot/pull/9746/files#diff-9f1e98727189e8489757bb46f3920b997e28506fe6d1d5343598d55607b5a8fdL73-L80). Any idea what's going on? You don't necessarily need to explain it to me. I'm just trying to make sure Certbot and Lexicon are both working more or less as we/you expect.

**Comment by osirisinferi** [comment]
Probably related to https://github.com/certbot/certbot/pull/9746 where `dnssimple` is used as the provider name. That incorrect provider name was also used elsewhere in the code that's now removed, but I guess there it wasn't critical.

@CTech-NicholP Can you perhaps modify your Certbot instance and in `certbot-dns-dnsimple/certbot_dns_dnsimple/_internal/dns_dnsimple.py` change

```
    @property
    def _provider_name(self) -> str:
        return 'dnssimple'
```

to

```
    @property
    def _provider_name(self) -> str:
        return 'dnsimple'
```

(just remove that one `s`)

and see if that works?

**Comment by bmw** [comment]
Beat ya to it by seconds Osiris 😜

**Comment by osirisinferi** [comment]
Yeah, sorry, on my phone from another continent (Africa), so too slow 😁

**Comment by adferrand** [comment]
So, before my changes, the provider class was explicitly loaded in the plugin code, so how the provider is named on Certbot side had no impact. Now this task is delegated to the Lexicon client, that needs the correct provider name à defined on Lexicon side to work properly. This name is returned by the implementation of the property `_provider_name` required by the authenticatior plugin implementation. 

On Lexicon, the provider is named `dnsimple` (which is the correct one by the way). During the refactoring, I wrongly used `dnssimple`, probably influenced by the typo made in the Certbot plugin name. Very sorry that I missed that...

**Comment by bmw** [comment]
No worries! Thanks for the explanation and quick review.

**Comment by CTech-NicholP** [comment]
@bmw @adferrand Thanks! Do you know when this bug fix will be released?

**Comment by bmw** [comment]
I'll try to do one next week. Ideally on Tuesday.

If you'd like a workaround before then, you can (temporarily) track our nightly snap releases on your system by running:
```
sudo snap refresh --edge certbot
sudo snap refresh --edge certbot-dns-dnsimple
```
If you do this, you can to switch back to our normal/stable releases once we've done a full release by running:
```
sudo snap refresh --stable certbot-dns-dnsimple
sudo snap refresh --stable certbot
```

**Comment by bmw** [comment]
I did a release this morning containing our fix for this.
