### ISSUE TITLE
Feature request: Provide a hook after renew

### ISSUE THREAD

**Issue by fishy** [certbot/certbot#9840]
My understanding is that `certbot renew` as executed from the cron job would only restart/reload http server (nignx/apache) only if the cert it's renewing is using the nginx/apache module.

Which means if I use manual dns hook to get the certs, it won't auto restart my http server after renewing.

Further more, not all certs are used by the traditional http servers. For example I also has a cert used by [ocserv](https://gitlab.com/openconnect/ocserv).

So:

1. It would be great if we can add an option to auto restart/reload the http server after success renewal
2. Or better yet, add an option to run a custom hook after success renewal (so I can handle the restart of http server and/or other servers using the cert(s))

## My operating system is (include version):

Debian testing/trixie

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

apt

**Comment by osirisinferi** [comment]
Please see the ["Renewing certificates" paragraph of the Certbot User Guide](https://eff-certbot.readthedocs.io/en/stable/using.html#renewing-certificates), especially the part about the `--deploy-hook`, which is what you're requesting here.
