### ISSUE TITLE
Expiration date to install Certificate in Ubuntu 16.04

### ISSUE THREAD

**Issue by cesarsantoscode** [certbot/certbot#9842]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 16.04.4 LTS
Nginx (nginx/1.10.3)

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
OS package manager

## I ran this command and it produced this output:
Does not apply

## Certbot's behavior differed from what I expected because:
Does not apply

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

My client version is (for example, if you use certbot, show the output of certbot --version or certbot-auto --version): certbot 0.22.2

My question is to confirm until what date there is support for installing the certificate using Certbot for the Ubuntu 16.04 LTS distribution. We need to schedule an upgrade to Ubuntu 18.04 LTS and we would like to confirm which one is from Deadline to complete this upgrade.

Previously we had a problem with another server with OS Ubuntu 14.04 LTS which stopped having support and even no longer appeared in the list of distributions on the official Certbot page and we were forced to upgrade to 16.04. This latest version (Ubuntu 16.04 LTS) has any end date of support for installing a certificate using Certbot?
![image](https://github.com/certbot/certbot/assets/33211028/07dd46c5-2828-4a2a-9de1-193c9bdd0121)

Link of those reported in the Let's Encrypt forum:
https://community.letsencrypt.org/t/fecha-de-caducidad-para-instalar-certificado-en-ubuntu-16-04/209216

Additionally, it would also be good to know when there is support for Ubuntu 18.04 LTS.

Thank you very much in advance.

**Comment by osirisinferi** [comment]
(Note that I'm not a member of the Certbot team.)

> OS package manager

The Certbot team actually recommends *against* using the OS package manager. If you actually look at the Certbot Ubuntu instructions, you'd notice all instructions for Ubuntu are the same and all instructions for Ubuntu use `snap`. That way you'll always have the latest version of Certbot, regardless the version of Ubuntu.
