### ISSUE TITLE
Add dev release script to Travis build matrix

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#985]
I'm considering adding `./tools/dev-release.sh` to the Travis build matrix, so we're sure we can release at any point of `master`.

**Comment by TheNavigat** [comment]
Copied from the IRC:

> bmw: An even better test would be to run the script, install the resulting packages and run integration tests. But just running the script is a great start.

**Comment by bmw** [comment]
I want to do #4080 before we do this.

**Comment by zoracon** [comment]
Structure has changed since this was opened.
