### ISSUE TITLE
docs error duplicate word on https://certbot.eff.org/instructions?ws=other&os=pip

### ISSUE THREAD

**Issue by ian-kelling** [certbot/certbot#9856]
that page says "sudo /opt/certbot/bin/pip install certbot certbot"

run that you get:

```
Double requirement given: certbot (already in certbot, name='certbot')
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by ian-kelling** [comment]
If you remote the duplicate word, it works: sudo /opt/certbot/bin/pip install certbot

**Comment by osirisinferi** [comment]
This is better addressed on the website repository at https://github.com/certbot/website. If I could, I would move this issue, but I'm afraid Github can't do that.
