### ISSUE TITLE
Combine pem files

### ISSUE THREAD

**Issue by mrx23dot** [certbot/certbot#9864]
Please add an option to combine these files, or do it out of the box:

`cat /etc/letsencrypt/live/web.itzgeek.com/cert.pem /etc/letsencrypt/live/web.itzgeek.com/privkey.pem > /etc/letsencrypt/live/web.itzgeek.com/web.pem`

Since at least lighthttpd requires a combined fine for 
`ssl.pemfile= xxx.pem`

There is a no point doing it manually,
and it's one more step that can go wrong in cron job.

Applicable to every version I guess.

**Comment by osirisinferi** [comment]
This has been requested many times before, the first one back in 2015 already:

#1201 

#5643

#5087 

Those issues also have very simple workarounds using simple scripts in deploy hooks.

But I'm going to close this issue as a duplicate now, as the last issue I mentioned above is still open.

**Comment by gstrauss** [comment]
> Since at least lighthttpd requires a combined fine for
> `ssl.pemfile= xxx.pem`

@mrx23dot that is incorrect (and the server is named "lighttpd", a portmanteau of "light" and "httpd")

Since lighttpd 1.4.53 (released Jan 2019), lighttpd supports having a separate file for the private key:
```
$SERVER["socket"] == ":443" {
    ssl.engine = "enable"
    ssl.pemfile = "/path/to/site/fullchain.pem"
    ssl.privkey = "/path/to/site/privkey.pem"
}
```
