### ISSUE TITLE
Use 308 Redirect to keep Request Method #7407 

### ISSUE THREAD

**Issue by ismxilxrif** [certbot/certbot#9865]
Reopening this #7407 

letsencrypt/certbot should (ideally) "just" add HTTPS to the existing site without changing existing behaviour. This works very well for all GET requests, but as the default is an 301 Redirect. Which is not correctly implemented in the most common browsers. So the idea is to change the redirect to a 308.

## My operating system is (include version):

Ubuntu 22.04.3

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

snap

## I ran this command and it produced this output:

certbot --nginx

## Certbot's behavior differed from what I expected because:

use return 308 instead of 301

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

```
server {
    if ($host = <fqdn>) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80;
        listen [::]:80;

        server_name <fqdn>;
    return 404; # managed by Certbot
}
```

**Comment by osirisinferi** [comment]
Reopened #7407, closing this issue in favor of the former :slightly_smiling_face: Please continue the discussion there: any signs of resolving of the compatibility issues?
