### ISSUE TITLE
Nessus Found Vulnerability: SSL Certificate Cannot Be Trusted

### ISSUE THREAD

**Issue by DaUmega** [certbot/certbot#9867]
The website works fine, but from a Nessus scan, it found this vulnerability with a CVSS score of 6.5, this will likely get flagged by other scan tools and discourage users from using certbot. I appreciate what certbot does, and hope to see it succeed. Here's the nessus report in detail:

The server's X.509 certificate cannot be trusted. This situation can occur in three different ways, in which the chain of trust can be broken, as stated below :

- First, the top of the certificate chain sent by the server might not be descended from a known public certificate authority. This can occur either when the top of the chain is an unrecognized, self-signed certificate, or when intermediate certificates are missing that would connect the top of the certificate chain to a known public certificate authority.

- Second, the certificate chain may contain a certificate that is not valid at the time of the scan. This can occur either when the scan occurs before one of the certificate's 'notBefore' dates, or after one of the certificate's 'notAfter' dates.

- Third, the certificate chain may contain a signature that either didn't match the certificate's information or could not be verified. Bad signatures can be fixed by getting the certificate with the bad signature to be re-signed by its issuer. Signatures that could not be verified are the result of the certificate's issuer using a signing algorithm that Nessus either does not support or does not recognize.

If the remote host is a public host in production, any break in the chain makes it more difficult for users to verify the authenticity and identity of the web server. This could make it easier to carry out man-in-the-middle attacks against the remote host.

Output:
The following certificate was part of the certificate chain
sent by the remote host, but it has expired :

|-Subject   : O=Digital Signature Trust Co./CN=DST Root CA X3
|-Not After : Sep 30 14:01:15 2021 GMT

## My operating system is (include version):
Linux kali 6.1.0-kali7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.20-1kali1 (2023-03-22) x86_64 GNU/Linux

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
snap

## I ran this command and it produced this output:
Standard automated certbot setup with apache server

## Certbot's behavior differed from what I expected because:
Nessus found a vulnerability, this means other software may find similar problems, making certbot less trustworthy.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
N/A

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
N/A

**Comment by osirisinferi** [comment]
Certbot is an ACME client and is capable of using multiple different ACME servers. Let's Encrypt is the default ACME CA and indeed sends a certificate chain including an intermediate chaining up to an expired root. This is on purpose and you can read more about that at https://letsencrypt.org/2020/12/21/extending-android-compatibility.

This is colloquially called the "long chain". However, the intermediate cross-signed by the DST Root CA X3 root is also expiring on September 30th 2024. Thus Let's Encrypt is transitioning to the regular "short chain". You can read more about this transition at https://letsencrypt.org/2023/07/10/cross-sign-expiration.

Certbot has the `--preferred-chain` option to be able to select alternative chains if offered by the ACME server. Let's Encrypt currently offers the "short chain" as an alternative chain.

In any case, this is not a bug in Certbot, thus I'm closing this issue :slightly_smiling_face:
