### ISSUE TITLE
Muilti Domains with -D but only get one cert?

### ISSUE THREAD

**Issue by Handsome1080P** [certbot/certbot#9868]
Env:

1. Debian 12 with apt installed certbot.
2. Debian 12 with official docker certbot.

Use -D try to get multiple domain certs,like -d 123.xyz,go.123.xyz,data,123.xyz.But only get 123.xyz,only one cert.This is my command below:
```
certbot \
    certonly --standalone --staple-ocsp --agree-tos \
    -m xxxxxxxx@gmail.com \
    -d www.123.xyz,123.xyz,go.123.xyz,cloud.123.xyz,data.123.xyz


```
Bcz the logs have a lot of private info,i can't post it.But there is no any error in logs.And the live folder only one cert.

**Comment by Handsome1080P** [comment]
And i tested,wanna get multi domains cert can't use one commands,need -d one by one.How?I remembered before not need like this.

**Comment by michaelAschmid** [comment]
I just now ran into this weird behaviour. When calling certbot with the option `-d`  and append multiple domains and all get into one cert file. For now I just worked around it, simply only unsing one domain...

**Comment by osirisinferi** [comment]
This is as intended. E.g. Let's Encrypt allows for 100 hostnames in a single cert. By using multiple `-d`s or by using a comma separated list, you can get a multi-SAN cert.

For multiple certs simply run Certbot multiple times.

**Comment by Handsome1080P** [comment]
> 这正如预期的那样。例如，Let's Encrypt 允许在单个证书中包含 100 个主机名。通过使用多个`-d`s 或使用逗号分隔列表，您可以获得多 SAN 证书。
> 
> 对于多个证书，只需多次运行 Certbot 即可。

U mean it just store all domains to one file , right?

**Comment by Handsome1080P** [comment]
> This is as intended. E.g. Let's Encrypt allows for 100 hostnames in a single cert. By using multiple `-d`s or by using a comma separated list, you can get a multi-SAN cert.
> 
> For multiple certs simply run Certbot multiple times.

U mean it just store all domains to one file , right?

**Comment by osirisinferi** [comment]
> U mean it just store all domains to one file , right?

Yes, one run of Certbot results in one certificate. That's the design.
