### ISSUE TITLE
stop releasing the windows installer

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#9897]
we said we were going to do this at https://community.letsencrypt.org/t/certbot-discontinuing-windows-beta-support-in-2024/208101. let's update things so we follow through.

**Comment by githubRover** [comment]
As one action would you please make note of discontinued support on your Windows Installer page?  
https://certbot.eff.org/instructions?ws=other&os=windows

At least replace this line
`Certbot is now officially available for Windows. `

with perhaps a link to your post here
https://community.letsencrypt.org/t/certbot-discontinuing-windows-beta-support-in-2024/208101

Thanks

**Comment by pasturryx** [comment]
what can i use now ?

**Comment by githubRover** [comment]
This link describes several options
https://community.letsencrypt.org/t/certbot-discontinuing-windows-beta-support-in-2024/208101

Here is a list of suggestions from Let's Encrypt.  If you are still not sure try posting at the Let's Encrypt community forum
https://letsencrypt.org/docs/client-options/#clients-windows-/-iis

https://community.letsencrypt.org/
