### ISSUE TITLE
Look into replacing Boulder tests w/ Pebble tests (or removing it entirely)

### ISSUE THREAD

**Issue by wgreenberg** [certbot/certbot#9898]
Our boulder tests have recently been breaking due to a change in boulder, but pebble (https://github.com/letsencrypt/pebble/) is the recommended test util for testing against ACME servers. Can we convert our boulder tests to use pebble, or if we deem them unnecessary, remove them entirely?

**Comment by jvanasco** [comment]
FYI, I implemented pebble tests for our client in a very simple but inelegant way.

I use a decorator to spin up a version of pebble for each test (https://github.com/aptise/peter_sslers/blob/main/tests/_utils.py#L288-L334) using psutil.

I also manipulate the hosts file on the github setup (https://github.com/aptise/peter_sslers/blob/main/.github/workflows/core-tests.yml#L48-L51)

This has made unit and integrated tests very easy.  There is a bit of an overhead to spin up pebble for each test, but the entire pebble database is localized to the test.

**Comment by wgreenberg** [comment]
oh nice! that's a handy setup. though actually, certbot's already got a harness for running pebble tests (i didn't do a great job explaining this in the issue description), we just also have a parallel set of tests that use boulder which we run in certain circumstances.

**Comment by wgreenberg** [comment]
With https://github.com/letsencrypt/pebble/issues/433 landed, this is just blocked on the next Pebble release, which itself is blocked pending their CI overhaul (https://github.com/letsencrypt/pebble/pull/444).

**Comment by wgreenberg** [comment]
New pebble release is out, so this should be good to go. I'll open a PR shortly
