### ISSUE TITLE
Feature Request: Add a .txt file extension to the ACME challenge files

### ISSUE THREAD

**Issue by snayagar-crono** [certbot/certbot#9911]
I spent 2 hours trying to figure out why my challenges were failing, despite having port 80 open.

It turns out that my webserver (Kestral) does not support serving files of unknown types up default. The current challenge files are generated without an extension so the web server does not know how to serve them. It can be configured to assume unknown files are text type but this is not how it is configured by default. This will save a lot of frustration for other users using Kestral which is the default web server for dotnet applications.

Its a pretty easy fix and i don't think it compromises any security by adding a file extension on to the challenge files.

## My operating system is (include version):
Ubuntu

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
Snap

**Comment by osirisinferi** [comment]
> Its a pretty easy fix

I'm afraid it's not: it's not Certbot controlling the file name of the challenge, but the ACME server. Certbot simply does what is asked by the server. Changing the challenge file name by Certbot would only result in a 404 file not found error by the webserver.
