### ISSUE TITLE
snap package Win.Virus.Expiro-10026576-0 FOUND

### ISSUE THREAD

**Issue by franciscoarnaldog** [certbot/certbot#9929]
I'm having recurrent virus warnings by clamscan , now with version 3700:
/snap/certbot/3700/lib/python3.8/site-packages/pip/_vendor/distlib/t32.exe: Win.Virus.Expiro-10026576-0 FOUND
/snap/certbot/3700/lib/python3.8/site-packages/pip/_vendor/distlib/t64-arm.exe: Win.Virus.Expiro-10026576-0 FOUND
/snap/certbot/3700/lib/python3.8/site-packages/pip/_vendor/distlib/t64.exe: Win.Virus.Expiro-10026576-0 FOUND
/snap/certbot/3700/lib/python3.8/site-packages/pip/_vendor/distlib/w32.exe: Win.Virus.Expiro-10026576-0 FOUND
/snap/certbot/3700/lib/python3.8/site-packages/pip/_vendor/distlib/w64-arm.exe: Win.Virus.Expiro-10026576-0 FOUND
/snap/certbot/3700/lib/python3.8/site-packages/pip/_vendor/distlib/w64.exe: Win.Virus.Expiro-10026576-0 FOUND
/snap/certbot/3643/lib/python3.8/site-packages/pip/_vendor/distlib/t32.exe: Win.Virus.Expiro-10026576-0 FOUND
/snap/certbot/3643/lib/python3.8/site-packages/pip/_vendor/distlib/t64-arm.exe: Win.Virus.Expiro-10026576-0 FOUND
/snap/certbot/3643/lib/python3.8/site-packages/pip/_vendor/distlib/t64.exe: Win.Virus.Expiro-10026576-0 FOUND
/snap/certbot/3643/lib/python3.8/site-packages/pip/_vendor/distlib/w32.exe: Win.Virus.Expiro-10026576-0 FOUND
/snap/certbot/3643/lib/python3.8/site-packages/pip/_vendor/distlib/w64-arm.exe: Win.Virus.Expiro-10026576-0 FOUND
/snap/certbot/3643/lib/python3.8/site-packages/pip/_vendor/distlib/w64.exe: Win.Virus.Expiro-10026576-0 FOU

Where I can report this if not here?

## My operating system is (include version):
debian 9.13

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
snap

## I ran this command and it produced this output:
clamscan daily scan

## Certbot's behavior differed from what I expected because:
no

**Comment by osirisinferi** [comment]
Seem to be false positives by a recently added signature, see e.g. https://www.mail-archive.com/clamav-users@lists.clamav.net/msg53007.html

**Comment by osirisinferi** [comment]
The `Win.Virus.Expiro-10026576-0` signature has been removed again: https://lists.clamav.net/pipermail/clamav-virusdb/2024-April/008624.html

So indeed a false positive, thus I'm closing this issue as fixed. Please update your clamav DB, so you won't get this false positive any more.
