### ISSUE TITLE
certbot-dns-cloudflare treats the subdomain as the zone during API call

### ISSUE THREAD

**Issue by fluffypony** [certbot/certbot#9947]
## My operating system is (include version):

Ubuntu 22.04.3 LTS

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

apt

## I ran this command and it produced this output:

certbot renew --dry-run -vvv

## Certbot's behavior differed from what I expected because:

My LE certificate is for sub.example.domain. However, when making the API call to Cloudflare, certbot treats sub.example.domain as the zone, instead of example.domain, leading to an API call failure. There appears to be no way to override this and tell certbot what the parent domain is.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

```
Calling registered functions
Cleaning up challenges
Starting new HTTPS connection (1): api.cloudflare.com:443
https://api.cloudflare.com:443 "GET /client/v4/zones?name=sub.example.domain&per_page=1 HTTP/1.1" 400 None
Encountered error finding zone_id during deletion: Error determining zone_id: 6003 Invalid request headers. Please confirm that you have supplied valid Cloudflare API credentials. (Did you copy your entire API token/key? To use Cloudflare tokens, you'll need the python package cloudflare>=2.3.1. This certbot is running cloudflare 2.8.14)
Failed to renew certificate sub.example.domain with error: Error determining zone_id: 6003 Invalid request headers. Please confirm that you have supplied valid Cloudflare API credentials. (Did you copy your entire API token/key? To use Cloudflare tokens, you'll need the python package cloudflare>=2.3.1. This certbot is running cloudflare 2.8.14)
Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot_dns_cloudflare/_internal/dns_cloudflare.py", line 183, in _find_zone_id
    zones = self.cf.zones.get(params=params)  # zones | pylint: disable=no-member
  File "/usr/lib/python3/dist-packages/CloudFlare/cloudflare.py", line 672, in get
    return self._base.call_with_auth('GET', self._parts,
  File "/usr/lib/python3/dist-packages/CloudFlare/cloudflare.py", line 126, in call_with_auth
    return self._call(method, headers, parts,
  File "/usr/lib/python3/dist-packages/CloudFlare/cloudflare.py", line 498, in _call
    raise CloudFlareAPIError(code, message, error_chain)
CloudFlare.exceptions.CloudFlareAPIError: Invalid request headers
```

**Comment by osirisinferi** [comment]
Looking at the error message, I'm pretty sure it's a problem with the credentials.

Please open a thread on the [Let's Encrypt Community](https://community.letsencrypt.org/) where we also help people using Certbot to get their certificate.

**Comment by fluffypony** [comment]
@osirisinferi I think there are two things here. The first is the "invalid request headers", which might be a red herring, but if I *only* put dns_cloudflare_api_key in my .ini file it complains and says that for a global API key it also needs dns_cloudflare_email. As best I can tell, this is incorrect, as Cloudflare only requires an API key?

But the second issue (ie. the one in the subject) is still correct. I hope it's somewhat obvious, and [borne out in the Cloudflare API documenation](https://developers.cloudflare.com/api/operations/zones-get), that calling the "zones" API endpoint with a subdomain (that is NOT a zone!) is going to cause an issue.

Here's an example that shows both (1) that you can call the API without needing an email address, and (2) that you need to use the parent domain when calling /zones.

```
root@cloud38056:~# curl -sX GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
      -H "Authorization: Bearer TOKEN_GOES_HERE" \
      -H "Content-Type:application/json" | jq
{
  "result": {
    "id": "xxxx",
    "status": "active"
  },
  "success": true,
  "errors": [],
  "messages": [
    {
      "code": 10000,
      "message": "This API Token is valid and active",
      "type": null
    }
  ]
}
root@cloud38056:~# curl -sX GET "https://api.cloudflare.com/client/v4/zones?name=domain.example" \
      -H "Authorization: Bearer TOKEN_GOES_HERE" \
      -H "Content-Type:application/json" | jq
{
  "result": [
    {
      "id": "xxxx",
      "name": "domain.example",
      "status": "active",
      "paused": false,
      "type": "full",
      "development_mode": 0,
      "name_servers": [
        "beth.ns.cloudflare.com",
        "kip.ns.cloudflare.com"
      ],
      "original_name_servers": [
        "ns1.maindrv.net",
        "ns2.maindrv.net"
      ],
      "original_registrar": null,
      "original_dnshost": null,
      "modified_on": "2024-05-29T12:36:03.351887Z",
      "created_on": "2017-10-25T16:16:48.929572Z",
      "activated_on": "2017-10-25T17:51:31.748160Z",
      "meta": {
        "step": 4,
        "custom_certificate_quota": 0,
        "page_rule_quota": 30,
        "phishing_detected": false
      },
      "owner": {
        "id": null,
        "type": "user",
        "email": null
      },
      "account": {
        "id": "yyyy",
        "name": "zzzz"
      },
      "tenant": {
        "id": null,
        "name": null
      },
      "tenant_unit": {
        "id": null
      },
      "permissions": [
        "#zone:read",
        "#zone_settings:read",
        "#dns_records:edit",
        "#dns_records:read"
      ],
      "plan": {
        "id": "0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
        "name": "Free Website",
        "price": 0,
        "currency": "USD",
        "frequency": "",
        "is_subscribed": false,
        "can_subscribe": false,
        "legacy_id": "free",
        "legacy_discount": false,
        "externally_managed": false
      }
    }
  ],
  "result_info": {
    "page": 1,
    "per_page": 20,
    "total_pages": 1,
    "count": 1,
    "total_count": 1
  },
  "success": true,
  "errors": [],
  "messages": []
}
root@cloud38056:~# curl -X GET "https://api.cloudflare.com/client/v4/zones?name=sub.domain.example" \
      -H "Authorization: Bearer TOKEN_GOES_HERE" \
      -H "Content-Type:application/json" | jq
{
  "result": [],
  "result_info": {
    "page": 1,
    "per_page": 20,
    "total_pages": 0,
    "count": 0,
    "total_count": 0
  },
  "success": true,
  "errors": [],
  "messages": []
}
root@cloud38056:~#
```

The solution to the second problem is either (1) the certbot-dns-cloudflare package needs to try various forms of the FQDN to guess the parent domain if it hits an error, or (2) there needs to be a new option to specify the parent domain.

Just to rule out the obvious, is there a newer version of certbot-dns-cloudflare than the one that is installed by snap with certbot 2.10.0 that addresses either of these issues?

**Comment by osirisinferi** [comment]
> The first is the "invalid request headers", which might be a red herring, but if I _only_ put dns_cloudflare_api_key in my .ini file it complains and says that for a global API key it also needs dns_cloudflare_email. As best I can tell, this is incorrect, as Cloudflare only requires an API key?

`certbot-dns-cloudflare` either uses `dns_cloudflare_email` in combination with `dns_cloudflare_api_key` ( "global API key, not recommended) **OR** *just* `dns_cloudflare_api_token` ("API token", recommended). See https://certbot-dns-cloudflare.readthedocs.io/en/stable/.



> the certbot-dns-cloudflare package needs to try various forms of the FQDN to guess the parent domain if it hits an error

It already does this:

https://github.com/certbot/certbot/blob/v2.10.0/certbot-dns-cloudflare/certbot_dns_cloudflare/_internal/dns_cloudflare.py#L189-L198

> Just to rule out the obvious, is there a newer version of certbot-dns-cloudflare than the one that is installed by snap with certbot 2.10.0 that addresses either of these issues?

No, 2.10.0 is the latest version and [there has not been any significant change in the code for about 2 years now](https://github.com/certbot/certbot/commits/v2.10.0/certbot-dns-cloudflare/certbot_dns_cloudflare/_internal/dns_cloudflare.py).

That's why I asked to open a thread on the Community as I'm pretty sure you're not the only user of this plugin requesting certificates for subdomains. And thus my estimate is that the problem is not with the plugin, but with your setup.
