### ISSUE TITLE
IPv4 vs IPv6 misleading error message with certbot 2.9.0 on ubuntu 24.04

### ISSUE THREAD

**Issue by aduzsardi** [certbot/certbot#9957]
## My operating system is (include version):
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble

certbot 2.9.0

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
apt package manager

## Certbot's behavior differed from what I expected because:
**The error message is very misleading and causes to run into rate limits**
The message implies that the IPv4 address refused the connection but in fact the challenge failed on the IPv6 address.
Once i enabled the IPv6 listener on the webserver , the validation suceeded

`certbot certonly --staging -a webroot --webroot-path=/var/www/letsencrypt -m myemail@mydomain.com --agree-tos -d example.com`
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Requesting a certificate for example.com

Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: example.com
  Type:   connection
  Detail: 168.71.x.x: Fetching https://example.com/.well-known/acme-challenge/n1ikuwo4OV1MV2Jjp3NCOaDmVmgG_Um4Ix8UfAEPU1k: Connection refused

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.

**Comment by osirisinferi** [comment]
That is an error message from the ACME server, not from Certbot. Certbot doesn't do the validating, the ACME server does.

That said, the Boulder (software developed and used by Let's Encrypt) developers fixed something like this a few months ago when I raised this exact issue (I think) at https://github.com/letsencrypt/boulder/issues/7347. Fix is here: https://github.com/letsencrypt/boulder/pull/7468. So I'm puzzled why you're seeing this problem still.

In any case, it's not a Certbot issue, thus I'm closing this issue. Feel free to comment in my issue I linked earlier or perhaps start a new issue at the Boulder repository.
