### ISSUE TITLE
HOW EDIT TXT recorsd

### ISSUE THREAD

**Issue by goshalainfo** [certbot/certbot#9980]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

**Comment by osirisinferi** [comment]
I'm pretty sure your 4 "word" question is not suitable for this place, especially if you leave at just that: 4 words without any more information.

My advice would be to ask for help at the Community linked in the template, but if you do, please provide WAY more information than you've done here.

In any case, does not look like an actual issue with Certbot per se, so I'm closing this issue.
