### ISSUE TITLE
Remove deprecated features

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#9988]
When searching through our code, I found the following deprecated features we can definitely remove:

- [x] Route53 propagation seconds deprecated in https://github.com/certbot/certbot/pull/9619
- [x] Update symlinks deprecated in https://github.com/certbot/certbot/pull/9592
- [x] `NamespaceConfig.{csr,key}_dir` deprecated in https://github.com/certbot/certbot/pull/9537

We can also maybe remove:

- [ ] Old `dns-lexicon` usage depending on the status of https://github.com/certbot/certbot/issues/9776

and the following two features that were deprecated before our release of 2.0, yet were never removed for some reason:

- [x] `--manual-public-ip-logging` deprecated in https://github.com/certbot/certbot/pull/8381
- [x] The public DNS Route53 Authenticator class deprecated in https://github.com/certbot/certbot/pull/4747

**Comment by ldlb9527** [comment]
Hello, this is my first time submitting code to Certbot. I'd like to start by addressing the last two issues first, and then I'll work on resolving the others later.

**Comment by bmw** [comment]
with everything but https://github.com/certbot/certbot/issues/9776 handled, the status of the plugin transition there remaining uncertain, and us having plans to do another major release in a few months to migrate away from pyopenssl during which we could also make other breaking changes, i'm going to mark this as resolved
