### ISSUE TITLE
Plugins post-refresh snap hook seems to crash (but still exits with 0)

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#9990]
I'm just preparing my plugins for the transition to `core24` and while reviewing the post-refresh hook:

https://github.com/certbot/certbot/blob/7b2b2b168595614f5a06be000835d247b4cfbcc1/tools/snap/generate_dnsplugins_postrefreshhook.sh#L26-L28

I'm seeing that if the `python` command succeeds, then `exit_code` will be unset, and the `if` condition on the next line will fail.

Take for example:

```shell
#!/bin/sh -e

python3 -c "import sys; sys.exit(0)" || exit_code=1
if [ "$exit_code" -eq "1" ]; then
    echo "Blah blah"
    exit 1
fi
```

results in (bizarrely still reporting a success)

    $ ./test.sh
    ./test.sh: line 4: [: : integer expression expected
    $ echo $?
    0

It might be better to do something like:

```shell
if [ "$exit_code" = "1" ]; then
```

which won't crash if `exit_code` is not defined.

**Comment by wgreenberg** [comment]
ack, thanks for the report & diagnosis Alex! opened a PR with your proposed fix (though i'm not sure why we aren't just checking `$?` directly in the first place)

**Comment by alexzorin** [comment]
Thank you!

> though i'm not sure why we aren't just checking $? directly in the first place

I think it's because the script runs with `-e`, so it would just terminate if not for the `||`.
