### ISSUE TITLE
Missing dependency in certbot instructions

### ISSUE THREAD

**Issue by Juul** [certbot/certbot#9998]
I followed the official instructions for `Apache` and `pip` [here](https://certbot.eff.org/instructions?ws=apache&os=pip) and realized that those instructions are missing a step. After the command in Step 5 the following command should be added:

```
sudo /opt/certbot/bin/pip install certbot-apache
```

If the `certbot-apache` pip package is not installed then the command in step 7 will give an error saying: `The requested apache plugin does not appear to be installed`

## My operating system is (include version):
Ubuntu 24.04

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
pip

## I ran this command and it produced this output:
Ran:
`sudo certbot --apache`
It told me that:
`The requested apache plugin does not appear to be installed`

## Certbot's behavior differed from what I expected because:
Following the official instructions should work :)

**Comment by MatthijsReyers** [comment]
I have exactly the same issue with the official instructions for Nginx: https://certbot.eff.org/instructions?ws=nginx&os=pip&tab=standard. Very annoying

**Comment by jamesyoung-15** [comment]
Also had same issue when following the official instructions. I feel like they should add a step in the instruction page that tells users to install the plugin eg: `sudo /opt/certbot/bin/pip install certbot-nginx`  to save some time.

**Comment by wgreenberg** [comment]
This is fixed now, thanks!
